>B
vqghqqgthkdvfpdkkltsptchegkkvrldaeclnytklisgrhkr-n
sfqlfwegflplf-------asrphskkgemahhkiaeqrvtdnsyllga
vpggsqds----yvykv---pfyynffgvvfyeacfdgdyeavlkcg---
--rimnytqsasltktlpgvkteikacsadlydawlvkkhtpsvsaatlq
casprtqwetndkgvksdsfkvgtlanlqtgpppgsvavkdvqdvfqcqr
yktgtsgavvpsensklgaaeclayntmagnaigsvlleknigqektgai
erqgleaianivindqgfgle-----knakveyeeggvprvsvlfkpagr
ckskllvrpkvk--------glcqq--avskei-ktdlylsagefpfkna
dlaef-egalktvlnhq-cyhsgtqlavtwasqlgsqvfalnftgtgtl-
-----girgsspafiqclvtavfpyke-----------elgetatcs---
--gvraetikeplntikqklvcsnkapqvfkaqggialdgnevnanascg
tll----grdskgsagcrdkrtg---c
>node10
iasahisn--evyd------fecpdavtgdkgnlcenrymgcetshvr-q
cfkkywkellpha-------lkhpqnnfeesdavkkgshalkdigfnltv
rt-kpaei-------si---rf----lvlkaasscfekrdhkyhrsa---
--glfnweatvshhravaldrsdlpncstkagsqeaigkhlsgylsgkvt
cvkpgglwm----aavsdrldatalpdmkkcgplv-qgiagahsvlpeaq
dppggcpnsnaltaslfksv---pfr--agiaaed---ekmvspddknkc
enqgkggveknsgkigsfale-----araqandiahggsysdivfkprhl
amgiarkhdrvq--------lriis--pgprkviheslckdagrfrfkgd
qdlafaidyfqaslvgqicthpglqtslswgahfgagpismsfeptacl-
-----nkkgqnmnfiggqvgdtvthsdv---tpltdkppqgqsiett---
--klkaqntllthgasirtp---sltgsvglgskgitlgprfdpkvpsct
vck----swas------wvgapn---c
>node3
vqgqqlgthkdvypdnklttpgchegkkvklnstclnftslcagrhkr-n
afhqfwenilpll-------snrprskqgemahqktpdhaltdnsyllsa
gpggaqds----yafki---pf----lgvifydacfagdyeailksn---
--rifnyslsanltrtlpglktpltpcttdltearlvskhnatvssngvp
cskpptqweindvgvksdsfrvgtvpdlqtgappasaavqggqpvlqadr
ykngasppvlpftnahlgsancaayntmaggattmlllernigqhntgac
nrqgleaiaaialkddgfgle-----prakveeeeagvsytavlfkphgr
clgnllisqhvk--------glcqq--avpkqv-kddltieaaefcfkaa
neggf-igilhtvlvnq-cfhdgtqlavtwgahlgseafafafdgsssl-
-----atkgsppafieclvsagfshkev---hpfgdgpeqgetatcd---
--girsetiqeplnaikqpvvsnkkapqvpkeqdgialdghdvdangccg
tlm----grds------wdrrag---c
>E
vasksdsn--glyd------facpdsvapnkgllcdnrymscgnthvrgq
cfkkywnqllphv-------lahaqnhfeekdaaarvshalkeiafdltm
rk-kiael-------rv---rf----lvfkagspcfdgdshkyhrsa---
--vkfnweatvghhkavalgrqdfprcatkigrqdavgnhisaylsvsvt
avnpgsllm----grlvdrldrnayrdqkqcgpla-qgiggahhvlpsaq
dpaggcpnsnaltkglyrdn---pfh--vgisakd---ekmvtpdekkkc
enqgkggvdtnsgkigkfaltk----asahtnpiahggsvndlvfrprhl
vmgmarkhddiq--------lrntnrcpgqskishetlckdggrfrfkan
qdlamnigffqtgllgqlcthsgmhdsltwsahfsagqrlmapdptecl-
-----akkgesmnfigsqvgdsvthgnv---vpltpkgnqgqgveas---
--niragntlsiyagairtp---sfagsvglgsrgitlnpqfdprvpgrn
vck----nwag------wvgerk---c
>node13
vqtetvsd--kvydssalkepecveglaadkknmcn--ymgasgtlsp-r
cfyqywkellpqv-------tkgsqnpegssaalkkgehvlaasgynldc
it-tpnep-------vy---gf----lglidaaicfarrdrkshrst---
--slyewnipaayqrplsihksslprcaakagpqdavnkhlagylsekat
svqpgslwm----avvseqskaspvpeyikpgpvv-edivgsekpvpvsr
espggcshvqtfspgllgsv---gfr--ggfanmd---nklassaekhkc
dnqgkagrasnsskiagfale-----araqagdhaqgvsynkfvfipkhl
amgnmdksdrvk--------arcfs--agpsevisdsliqnagrfgfran
kdaafeidyfhsrlvgqcsvhsgiptggswgphvaagrealaveatscl-
-----nkkgqdkdqagaqcddglshret---npltdkppggqdatct---
--alksqhalpvkdaairsh---dvnesmgfgdkghtlcnrnnekagccv
aik----nwag------wvraak---c
>D
pdghdfggpgnefyrrvlrrqgcdegtisdingrclsmciacvalsrk-e
cfekfwqdklail-------akkpkategdegsysipdhflanktyllsi
tk-gaqgp----ymfki-kvpi----pglmtyescfasrtesflkya---
--rlfnwdvpsgiptelapetaplnpckkdstadallnsleatiltgaap
clksrkvwvvqigeitaaeftnggipdlnagavftsdklegsdpplqant
ggagscqtlfpqssdimaraecggynnkcgfnmvkllfnkkvlvhevntc
ktagsnatsckglrqssfgla-rtklpgakveggtesvkyapivlqpvgr
cvgelmsgkren--------nrclq--kaprpv-nndlillaakscfasa
yeqgfkleyvhtkllfq-cflpvtplaahwgshlgdlefslvfdgttsl-
-----gkldsstggvdclvgqtkphret---helkvagkegkqspcdhvk
akklasevvlaaldppeqttvekkeekevpteskgtklagenltaegcce
apm----lwds------wlvrlv---s
>node14
veserisd--evydssdlkepdcsegvaadkdnlcehfymgctgshgr-q
cfkqywkellpqt-------tkspqnnfgdsaankkgnhalkdagynltv
it-tpeei-------sl---sf----lglidagscfarrdqkyhrsa---
--slyewnipvsyhralaldrstlprcstkagsqeaigkhlagylsgkvt
cvkpgglwm----aviseqsraspvpdlispgplv-qdiagghsvvpegr
espggcphvetftpglfstv---pfr--agfaned---ekmvspddkhkc
enqgksgvdsnsskiagfale-----akahaddvahggsyskivfmprhl
amgnmkkservk--------arcls--pgprkvisdalikdagrfsfkvn
kdaafeidyfhatlvgqtcihsglqvalswgahvgagkismafdptacl-
-----akkgqanafigaqvgdslshrev---spltdkppegqtiact---
--slksqhtlatmgaairtt---dltesigfgnkgitledrnnekagcct
vik----swas------wvraak---c
>C
khgqdfdapgdgfagnklkragchegnqpnsggaclslcivcvgfhrk-n
gfqhipqditpliqtvdgdvsgrpksdegdaaayakpehkltdksylfsl
gt-aghgtakeayafkt---pl-----glpffkacfsggadkslryfhdn
ddkqfgvsv--klpsalansslpldtcktdttfdailntdvatyfsggvs
ylkseslwvahvpgvttsaftnasvperhtgavttaenvagggpllraeh
ggagtcedvfpqnaellglaactgygticafktaklkmdkvvgvgevntc
nsaglsaiaskglksggfgle-----patevdmgaclvsvkayilhcqgr
wfsqlmlsktvr--------hkclh--kgprpv-rnevvlgapsmcfapa
ydggfktnyshtsllfr-cfmpvapgilawggaigsddfsllfggvtsl-
-----gklepscaslecwqgka-----v---hqlrvapqpseqpacdsqk
knnlaselvlealdastqtiaekkdepetpledknvnldgeaetakgcci
sll----iwdg------wnrrpq---g
>H
vhtetvgd--kqydspalkpedcvegltankkpmcn--ykgafetlaf-r
cfsdywkallppv-------tkgsqtpdgsssslkk----------nlds
ks-tpndp-------vy---rf----lslinaaicftkrdqkdhrst---
--slyewsipaayhhplsihkaslprcgnrpgpqnavgehlerflsetat
svepgslwk----avvgdeskaspipeyvkpgsvv-evtvgnetpvavsr
sspgdcahmetfapdlrgmv---gfr--tgyanmd---nkavssaeshkc
esdgkamgasstqstagitna-----skaqagdktqrvlfskimfipkhl
amgnmnkshrvn--------hrtfs--agpsevcqnatvendgrfghran
kdvsfeidcfhaklagqvgdhagillggpwvpkapsgrdaqgveaassl-
-----ikkgqdkdqpgcqiddelsqket---kpmkdkppgtqdglct---
--alnsqhqfpvkedairgs---dvnesmgfadkghtictrdddmsgcci
air----nrtg------wvsasn---c
>node15
vqaqalsshgevydnsdlkkpgchegvaidlgsacqhiyilctgrhkr-e
cfkqywqellpta-------tkspknklgevpaykkanhalkdagyalsg
tt-npeei-------kv---pf----lgliyygpcfaarddtyhrsa---
--ylfqwsipvnlhralaperatlmrcttdagsegvvgkheagflsgkva
cvkppglwmnhevavtsgkasaaavpdlhsggplvsedvegghsvvpenr
ehpggcphsdpfttahlgsascspyr--cgfasialkmekvvgpedshkc
enqgqtavsskalkiagfsle-----tkakvedvaaggsyskilfmpqgl
amgnlkmnarik--------aqcld--pgprkv-kdalvkdagkfvfkva
ndaafkigffhskligq-cihsglqvaltwgehvgvgnfsmafdgstsl-
-----gkkghvaafietqvgdtlahrev---hpltddpqeaqtaact---
--nlkneqvleamgatvktt---knspaipfphkgitledrkveaegccm
tvk----twns------wvraaq---c
>G
lngeqkgs--klcdsgtldenlcgdgapgekkilcd--ymgisgalss-r
cfyqywrknlehv-------akgsrnpegsgaylkkeeqvlsgslyphnc
tt-tpnep-------vy---gf----lglvdaalcfarknrkshrtr---
--slynwkfpaaikrplamqqgslptctskagppdtsnkhlmgylcestq
kvqpgslwk----ssvsehgkcsptgdyikpgpva-deiygsgkpvpatr
qnpgacthvttftngllksv---gfr--asfahqd---nklinsaerhmc
dnqgkdgrtgssskiasfdle-----qradvddlvqgvsytkfvfipphl
amgqllvstrvk--------arcfs--tgpseiisetliqntgrfgfrak
kgaafevqyfaarl-gqctvgsgctaggtrgphcdksrealpveatkcf-
-----hnkgqikdqagtqcekgwghred---qlltssppggqpetct---
--alktdhaapikkaaqssh---dvnesmgfgakghslcnrtaqkpgccv
rik----nwgg------wvrsgkglhn
>F
iaciniss--dvyd------fecqn---gekenlcakvyvgcavpqvr-q
cfkkywkdivpeg-------lkhpqdtfaeedavadsahslkdvgfnliv
rt-kpaei-------kdf--rw----ivlkvaskcfekkdkkyhqsa---
--gtitkdgtvalqkvlanaranlphcytkagsrsakgkqytgylrgklt
cvkpgglwm----aaidtaldatalpdgkkcgpli-hkvvgahtvlqeaq
dppggcpnitalttalfrqi---gfr--agvaaee---hkpfrteqknkc
dnqgkapvqndlgkissfale-----argqghgtvpggnysyivfrprhl
algvkrkrnrvqlkcaelpglrtvs--pgrrkaihgslckdagrfrfkgi
sqlslhinygaanlvglvctdpglqsglswgvhfdadpasmsfertgcli
rrdmqnkkgekaafisghvgkvvlhpev---aplndkpaegqsvett---
--klkalntlltqgdtlsns---sltgvvalgdkgiiigtrfqpkipact
vckpnylswgs------wiraqn---c
>node6
pqgqdfgapgeafssrklkrpgchegaksdiggtclsmcivcvgfhrk-d
cfqqfwqdllpll-------skkpkstegdigsystpdhvltdksyllsl
ts-aeqgt----yafki---pf----pglifydscfdgrtesylkya---
--rlfnysvpaklptelanqkapldpcktdatadallntheatflsggvp
clkspslwiahiggvtaadftnsgvpelhtgavltsnnveggnpllqaeq
gssgscqsvfpqnsellgraacaaynticgfktaklkldkvvgvdevntc
ksaglsaitskalkssgfgle-----pstqveagsasvtynaivfqsqgr
cmgelmmgkrvk--------hkclq--kgprpv-knelvldaakicfasa
ydggfkiayvhttllfr-cflpvtplamswgshigadefslafdgttsl-
-----gklgsssaalecltgetkahrev---hqlrvapqpsdqsacdsvk
kknlaselvleamdatsqttvenkdepevplenkgiklagegltadgcce
tlm----lwds------wlrrpq---g
>node7
vqgqplgthgevyddnkltkpgchegskidlgstclsicilcvgrhkr-d
cfqqfwqnllpll-------skrpkskqgevgnyktpdhaltdksyllsg
ss-asqrt----yafki---pf----lglifydpcfagknetylksa---
--rlfnyslpanlpkalpsqkatlapcktdateeglvgkheaaflsggvp
cvkpptlwinhdvgvtsgnfsaaevpdlhtgaplassdvegghsilhaer
grpgacpnvlpltsahlgrascapyhticgfatamlkldkvvgqdeshac
krqglspisskalkdagfgle-----psakveegaagvsynavlfkshgr
cmgdlmmsqhik--------gqclq--agprqv-kddlvldaakycfksa
ndggfkidifhtvlidq-cfhsgtqlamtwgahvgsddfalafdgsssl-
-----gkkgrspafleclvgdslahkev---hplpdnpqqadavacd---
--nlssetvleamgattqttvenknapqiplqhkgitldgnkvsangccg
tlm----nwds------wvrrpq---c
>A
tegqhtgtkknvypnnrlttpscneakkvelkgtclyftrlcpgkqkq-n
kfhefwddifpli-------cnsprtkqggmahhkvenhalgdnsyemar
gpgsaads----yayki---af----lacifydscfagdydailkkk---
--iifnyalsadltrtlphlktpftpcathlsegrlvsdhnasvskselp
atklpsqwklneigvnsesflggtlpdvkagtpaaseavdggqsllqanr
ykdsaspplapftnahlvssncsgynklsgdaktmlllgsgkgqpktgdc
nrhplevravkavnknvfgle-----qkgkviedeaggayaaglfnrqgr
clgklllsqhvp--------gtcqq--avpyqv-keditiaatqfcikad
seggs-igvlhvvltnn-cfgdgtllavvwssllgteaftftfdasatl-
-----atrgfeptflecwvsasfshtdvttgfpfgegpqqglqatcd---
--virsatiqiplkginqpaqsnkpaqqvstvqsgitldghdgdtdgacg
vlm----gthg------wdrrgd---a
