>node6
hllsqrdppqtlyaescl---shcaqmhdh-----seikrdsfsgkev--
------------ktafqnkaqgti-lklgq--rsftqmcytysd--vnhp
aaqalplnlikglstfeey-----------------------vcnkvnth
kqviqky----siqkppvdgrpanyrg-egwsnnplgtavc-pekhdpel
dyr---stpklnpgsipgsgkaegt---vfffnvtkglnlvdnwicffdp
qvqgmplarkikkscef--mklhfvgsawirgtqpscakpdvhivaargg
kdaelactkeytlasnsvrrvkglgpfgprfsanrvdnaqgsqfqcpkaa
ckeavkalvfl---hlllllrqtvws-vdeylhsdyatpaiqrnnagvdg
dfsrskqrgagphvtkgaglt--ftspqkfsfvphcplpqpfvktg-vrg
------ras---ldiqaeegg--hrrphvfhdmcvggvlvlrsrlmagsa
atgaerstyfctskaleaprsyaksgrllfgascyhtdmspeepitakah
teknyac
>node3
tifvgieppvilradncl---rhcsqrhhn-----getkrdtikvagt--
------------qrayngsahgsv-msfgq--rtytvmn-kfst--vshh
alrsipltlarqlplfdhy-----------------------ackkv-qn
deviqky----nlvtppvqasrtdyrd-qswadnplgsvic-sesekpel
syr---gssklnrgsvpgsnksdgtkglvgffnvtkglnrisnwscffhr
nnpgmpvgrkaekpc----pcleyhgdphtkkdqppcakpnveagtalgg
tgkaldcaleymmsgsstprpktlgayvpqfstepvnhppgthfhcpraa
ckepvrtmafl---gellllrhgvwalldgylhtkyepptvdrhgqgldg
kfprtkqrrsgppvttgaglk--flntvkyqlinrcqapqalvranfirh
------kat---ldihkeatk--hkkqhrfhlaclsevlilsvrlmtggg
ttgsqrstyyctsknldrmaafakaapllfgpscyntekglpnpngadyr
rskdgnc
>node14
dmntakdpptalqtdegl---hhntqrpdk-----sepkratvrgedt--
------------kshvdvaqdgtt-kalgpdlqagpavd-sfcg--rahq
kvhslpttlpkelasfmqykfnkmllhvstpsitalksrllvfcqrv-es
lvalewc----hlagcpvdgsaargka-qnwardalg-plc-fnahqpgl
sfg---gcgfllagpfpnadnvqgnpgadfvfkltdglghvdnwvclldp
rqkgmptekka--pkef--gkpqyisaahkskkqppcpqpethvltskgg
gahassctslymvfgytvspsktlgvygpgfgaarvthpqgsgfhcnknr
creiarkldflcdfgiilllqqpvwe-lqannhthyssptlsrappdakg
gyargkqrgadkhvhvraqlh--fgrslrfqvvekchkpeafirlgfvkd
------kqy---levhksdta--yrqtflyyyecaahvlvv---rdigsg
gigvqkakyscvrmnlsrptgigqaaplffgatcfhtensfpissglpfq
lqesfrc
>G
ditprndppqnlettetm---hydeprser-----tsyksaavr--sk--
------------kdrvdtlqegslsknntqdlpagpnid-rfcg--gqdm
dvdsvsvvlpkdlgsffqyrfdrkhlhvdtptikalkdpfltychkv-aa
lvaqdwc----slsedpesggnasakt-aswdkegkd-tla-vhahhpgl
sfgaqegtgflfpgphpaakttkdnlsaaflfrlsdnlgnsagwicllap
p-qglttgecd--pgef--gkgeyipaehkhqksskcpesttnalgggre
gppshpctpvymefgyimpttkelgvygptfgvtrgvhgdgsafmcskfk
ckqalpkldflytfginlllgnpawi-lptnpqsrhasvhlsntsnsgeg
gygmtsvrladnelhvrspln--fgqclsieviqkchrahlfaklgfkre
------khy---lacyktdaptdytydflyyyactahviav---kavpqa
higv-ktkydsvklkiktasgdgeggqlyfgakcihtetqfpiktnlrfq
ppghfkc
>node13
sistandpptslqtnegl---hhqhhrmdk-----neykhatvr--dk--
------------kehpdtaqdgst-keftpdlpagasid-tfcg--gqhq
kvdslpvvlpkelasfmqyridrkvlhvstpsitalkdrfltfcqrv-rn
lvaedwc----nlqegpvnggdasaka-aswdrdale-plc-fhahhpgl
sfgivggcgflfagphpnakttkdnpgakfvfklsddignspgwvclltp
p-qgmpvgkse--pkef--gkpeyvvaahksrksskcpqsgthvltskge
gppshsckslymkfgyilpsakelgvygpcfggtrvvhsdgsafhcskrk
crqilkkvdflytfginlllegpawi-lqaephtrhasptlsrasidaeg
gygmssqrgahnqlhvrapln--fgrslmiqvvdkchrpqgfirlgftrd
------kqy---lechksdas--yrydflyyyqctahvmav---rainqg
sigv-nakydcvkmnlktasgdgeggplffgskcfhtdksfpistvlpfq
apghfrc
>C
hllsqrdgprtlypqscv---phctqlqdh-----anikrnsfagtkv--
------------ktthenkcqgti-nrlgk--rkftqmcntysd--vthp
aalaqplslykglgtfeey-----------------------vckkintk
kqvidpy----pihkppvhgrpanyrg-egwsneplgtavcapeklepel
dyr---gnmslkaatkpssgkpdgq---vfffkitkglnivntwrcffnp
hvgslslsrkikkacaf--kkfhflgsafirgtqascqrgksfqvkargg
kdaelacrtrypllqndvraiegsgpfgprwaadrgsnpqgfqlecpkta
ckeaakvlifl---hnllgllqtaws-aedylhsiyevpsmqrstaghgg
dftrtrqrgagphvtkgnslt--stspqkisfkphcalpkpfakng-vrt
------ias---ldrasengg--nhhvhvthdmciggvlvlssslmggst
vngaqrstflcnskglgaprgyaksgrllfaarcihtnispakpgtssaq
tetnyac
>node7
tilidkdppttlrtencl---rhcsqrhqn-----sepkrdtikgeet--
------------ksayqgsaqgsi-mslgq--rtfspvn-tfsd--ishe
alqalpltlakqlssfaqy-----------------------acekv-eh
deviqky----nlvkppvdgsaanyrg-qgwsnhplgtavc-sesqdpel
ayr---gssklnpgpipgsekaegtpglvfffnvtkglgridnwvcffdp
ndqgmpvarkiekpcqf--pklqyvgaahtkkdqppcakpdvhivtaqgg
kgkalecakeymmsgnsvsrpkglgtygpqfstervnhpqgpqfhcpkaa
ckepvrtlgfl---gvllllrqgvwa-ideylhskyatptvqrhnpglng
dfarskqrgagphvttgaglt--ftssikfqlinrcplpqalvragfvrn
------ras---ldihkeegg--hrrthvfhalcvgdvlvlrgrmmtgsg
ttgtqrstyfctsknlerpssfakaapllfgascyhtekslpepnaaeyr
tektyqc
>D
nllsqrspsatlyaescl---rhcdkkheh-----searpdafggkev--
------------rrgyanktqgni-lklgq--rtftkmcytfkd--vlhp
asqvlpkylikgvrtieey-----------------------vskkvelh
kqviqky----srknqpiegrsaqyra-egwsnnpegtagc-pekhdpel
dfr---stpilepatipgsgktegt---vffntvangltlvdkwicafth
qvlgmplgrkiqkscpfgrmklhfvggawvrgtnascgmkdidcyaahgd
ydaelsctkeytldsdsvrr-kslgnfgsrfsatrvnddlgsrfqcpkae
ceedihalvfl---nlllllrqtvwt-iseylhpnyaaaalrpdaasvdg
e--rqkqrgaapqatknaglt--fssnlkftfvpfcplslpfvtag-vwg
------raa---laiqadgag--krkphvfhdmcvgwilavrskllagse
etgaerttylctckptepprtyakggrllfssscyhaslsseeaitalaq
tkrnyac
>A
smfvaieppkflkqekcl---rhcsqqahn-----geankdtirvtgt--
------------qrgylgrvhgsv--sfgq--daysvmt-gfst--sahn
glrripitlarelpvydry-----------------------acmkv-qn
dntiqky----nlitsplpssradyrd-qewaekplagivc-caaekqev
ryq---grsklhrgsvegsnkhngrkgivgfsnvekginrinywscffhr
sdpgapvgrkaempc----ppleyhenphgkkdqspcakptgedgtalng
sgvgldcaleymksggetprpkslgayvkdfgvdpvthrpsthfhcprat
ckaplqtmgfl---selmalrhgpwallddylhtryqpaaadrhglglda
kfpgsqqrrggppitagsglk--flnkvkfglinryqrptavvrakfvre
------lst---lnihkersk--hhnevrfhlaclsdvllvsarhmtsag
tagsgmspyyctaknldrmgnfadenpllfgascynldkglpnpngadyr
rskdgnc
>node15
dimiakdppttlrtedsl---hhksqrhqk-----sepkresvkgedt--
------------ksnyqgsqkgtv-kslggelrtspsvd-tfcg--rshq
rlqalpttlpkelasfaqykfnkmllkvsspsvtvlkdrlamfcerv-eh
eetlqnc----hligppvdgsaarckg-qgwsndplgqpls-fdsqspsl
afk---gssylkpgpfpghdngqgepglvfffnvtdglgrvdnwvclldp
reqgmptarka--psqf--dklqyisaahkskdqppcpkpethvltskgg
kgqamecasqymvsgytvarpkslgtygpsfasarvthpqgsdfhcpknr
cregarkldfl---gvllllrqpvwa-lqeylhsqyatptvaraspdlng
dyargkhrganphlhtgaglt--fgsslkfqtvnkchkpqalvrggfvrd
------ras---ieihkeeta--hrrthvfyylcaghvlvlrgqrltgsg
sagtqkssyacvsknlerptgipkaaplffgatcyhsekslaepsgapyh
teltyrc
>B
nifvgldperklrlndclkcilhanqrhhnsglrhgpikkktvlpahn--
------------rrsydgsdhgav-ktfga--rlytdvd-klst--vehk
tmksiplslthkkplfdhy-----------------------tikki-qn
aqvvqky----dlvtppvndsqseyrn-qsweeqplgamts-sesgkpev
syk---gasrlsk-skpettksdgvkgvagffkmnialgrksnatcffnr
nnqampvgrsgekpc----pnlqypgdvhdkkdqpqcakpnvtaatglgg
sgnaldcpqefmksgsknaapklagayglqyatepidhppgvhfqcpyaa
ckqpvrtlpfl---aellllrhpvwgllngylhqkyqppteerhgqevdd
kfprgkqrraglpvkagaclq--flnavkhqfinrcgdaqalvcaewirq
------kat---lninkesae--pkrq--lqlaclvevliatvrlmtggv
atgtqretyycttknpdklnafespapllfgpscyntakglpnpkeadyh
kskkktc
>H
niaagentpddldsdega---hhqhhrmkk-----neydqptir--dn--
------------kkrstsaqdsss-kdiipqvpagasmn-tfcg--gqha
kidtlshvlfqelasfmeyrinkkvahvsapsltalknrfltfcqrt-rn
lvtedwa----gfeaapvkggtansti-tawqrdale-pmc-fhakhtgl
qfglvggpgflfadshidlrttpdnsaaefafklsndigsspgwvcylap
p-psksvgkse--pdey--nkpdyvgaahqtrksstcpqsgtevvtdkge
gfpphnckshymklgycvpsakglgvygacfggtkqvksegasfhatrrk
csqimkqreflysygidllldgprwf-lradpgtrhsnpslskaeidaeg
aygmssaagahnqlhvpvpcn--fdrglmiqvadhahnpmgvkrvgfdrt
------kky---lecnnsdta--yrydflyyyectahlqvv---paisqg
sigv-gpkyncvkstlktsagdcdvspaffgakcfhsntslpistilplq
lpghfkc
>F
dmitdddqpksacieqvm---hlqsarndk-----pqpkrtrfkgqda--
------------kanlevgegghl-kplggdlrhdda-t-chca--ldel
dvqglrtadngepgaylfyafinmmvsvgrsalttlkslfeilcgrv-at
viglqwpmdadqvavctmkgtaasdka--------lg-psa-fstakpvl
sfs---gyptllvgafqgvaarpspeggtivfkltkiflakkgfvcllds
rqkpmltdkks--pkai--gapeltygaesnaksapcekqeshlls-lgg
naes---tglfgvfgyavarqkvlavcehtfgatsatplqasgfnctrtk
crkkgkelgyislfg-llgldskere-lqpksnlhinaptlsraspqakt
gytkgkekvtnskvdiknnlasllgkqprfpdvdkkhepegflhnnfvkd
------kq-----tvahkdtg--yhqsftyyyecaehvpdv---qdipcv
algvekgncpssrkrlarrcnfsdeapelfkgvcfyvqtsfndsggrifr
lqesfqa
>node10
dmttdddqrralctdegl---hhksarpdk-----pepkrtrvkgqda--
------------kshidvaeggpt-kplgpdlqadeavd-chca--kdhq
kvqglptslpgesgsftfyafnkmllhvsrnsvtalksrflvlcgri-at
lvglews----qiagcpmngsaargka-gewtkdsig-plg-fnaeqppl
sfs---gcpillagafpgvasrqgqpgatfifklskgfstvngfvclldp
rqkgmptdkks--pkaf--gtpqfvygaqpkaksppcerqeshvlsckgg
nahs---tglfvvfgytvasrkvlsvcgpgfgaakatplqgagfnckrtk
crtkgrqldficnfg-ilglqqtewe-lqakthlhinaptlsraapnakt
gyakgkqkgsdkvlhvrndlh--lgrtprfqdvdkshkpegfirngfvkd
------kqy---rtvqhadtg--yhqtftyyyecaehvlev---qdigst
glgvekancssvrkklsrqsgisqdapelftgscfytsksfpdsggrpfr
lqesfra
>E
dmtteenqrrqlciddgl---hhktgqpdk-----qspgrtpvngsdaiv
etgakgnsrladnshinvaegnpp-splgkvvqadtave-chcacvkavq
avqglqislsgqagsytffafdkrlmnvtraaitslksyflvlcski-av
lvvvewg----pkagcamngpgargkvhgewargsmg-lag-fndqqktl
sks---gspialagafpgissrqgqpgatfifli---yanvdgkiylldp
rekgmptdvkg--pkar--gtpefvygkqpkaespgydkqesdvapckgg
nard---tglfvvfghnvaerrlltvcgvgvgakgatpmqgggfdckrvr
crtkkrqpdficgsd-iiglqtsgwe-lqaltflhcsapglartqpsgnt
gyakakqsgsprilhlknnlh--lgrtprfqdigashrpeafirhgfskd
kepllvkqydqigavehadtg--yhktftyyygcaesalev---qdigsk
glkvrdghcssirkklsrqigitqraptlrsggcfftkksfmdagnrefi
gqqgfta
