>E
pqekcrvikrvlglrqevkcsgdfl--vgeynt-----glrmdtaaaq-a
psdeqssftqmgtdpkgsfppavvmqgpeqqslfkpevakarelskadll
sfedwa-nvtaviqrdrevs-ralpvhigklhrpgkpgksvgvrcsmlel
krlcighlsedpprdpksmvsqk--t-ydtrgeasvpipkmlgnagqctt
gepfsktlgehgpvehlhresrvmcv----ikghhaflyyissnlikcnm
acalvvnt------ktrcackkfaentsakgvmegdcagiadgseyakp-
----dtlggtrangghp--enistvtgpeyyiyiqstdskgymkhtvrgk
vsvslppgnqs------kktfantplpsvitdgspylgvctlv-----tt
yywqtlyklcmcgklqqisttekeqnpdtiglfinkyrgttmfhypkvcl
klylpntkhianahclikevvtftniarplraldedtlatekfakdsmka
mplnankgycivat-qpiryshvvstspypervtsdash
>node10
lrqrcrvikrilglrgkvkcsenfl--pdeyht-----glrndqaaaq-a
vgakqtafsqmgsdpkatfqpavvmdgielqtlfkpevakarelvsadll
sfdcws-tatalvqqtkevs-rmalvhkgtlhrpgktgrsvsarcsfnal
krlckgnlsqtasrtaknlvsqk--d-ykarglaacetpkilkdaggctt
ntqffktvgehgpvdalnkesrimcv----akghhpvlylvnsnlikclm
acalivst------ktkcsckkfventkakgalhgdcdglqdgseysel-
----ealggsegdggwq--qnvttvtgneyyvy------------smpgk
vtarlppgdqg------kktfadtslpgvikngdvylggcdli-----tt
ytketlyklcmcghlqltsgtekqqnpdtigvfinkyrgtamfhfplicl
rlylpdtkhivlahcliqevvtitniaralrgldddtlatakfpkdsmka
tsmeggrgycfiat-eptryshvvetspypkratrdaah
>node15
lkkkchvnakilsliaktrcqaafl--shsytg-----klkenatead-a
vhakavtfalvgsypeakwqpnivmlviqqqklykaiaakgkqllagdll
sapcvg-ssaalsrklmakg-kkamvhtsslhtpgkshrmratqksfapl
khackegsggvharsikdlanqm--d-yssiglagaksqkiheallkcsa
nvqffktvgdhgpleclkpeckvqcr----akrhhpilyltstelfscll
pcalmlatginrkfrtkrpckadgnaakgngalhgtaeglkdssefkea-
----qalagttsdsawq--eavttthggqyyvf------------ekagl
itpqltppprafcegarmktfsdtgvsglikegpaylgvykliehkttie
ytniklprlclcghlilksmadkqpkletmatfidrfrsslmvnfrklcl
mgelqyegtivesaaqfkevgsktntttv---lddgklatvkyvkpamkt
kecgsglnysfsnpseesrysrycetatfpkkgkkndyh
>node13
fkryanvkakflglraavrcgekll--phhyns-----kvkegateae-s
vaakacayktvgadskmkfepgvvilgidlqklfkaidtkakhffaadkl
dadcvr-tttalgaslkrvs-kiaealdsslfkpgkagrstsarrsfppl
nrlskgglggvasrtikdlacql--v-ygavgvaaasthkthpnlgdcpa
hktflktvnehgplkaldreikilcqydpcgkhhhpllylgktgrvtcev
kcafvlakglkqklktkapckkaggvakqngghhsecdglnaahlykel-
----pslgggnsaggwh--gsvtsvtgiefyvf------------egvgk
iiprlvpsakg------mkaysdtnlsglikegkvhmgaynlieqnstgd
yskqtlsklclcghaklakksdmkprletmadfikgyrgslmflflllsl
hlylpyaghivanaiqldeeashtnsgqs---ldnetlptekllkqatkt
kscgnnqvycftnsndrsrysqvceagrfpnaaakdqmh
>D
idlkksvsasimllivktrkgvdhl--sqalqa-----rwaeanimgs-n
ahlksivfslspegpactwssktaklviedqnwikagnskprlllaggli
kvacvg-sasatakdsavsg-qpal------rssghsrrllaeqvnfyhg
khkcaqdsrgfeakwtndyespv--d-fevmglkggsgerihepllkcdp
hpdffgaigdhggldclkaesrlsaa----srgsnplryiedreafacll
pcavkaetgiqqkiadrppchiayhvdfihvevhgnadsltgvlafphv-
----sprggaltehswa--hgmpttrgsrsyvv------------qklgl
ligtkskaerdlcarqraksfantglatlitkgkdyttiylleghkpisk
fqsvaaarltwiawmpakgvetgsgkaqpkfvfgarsrktngvnfkmkcl
igsgeysrhspqrgkksidtrqkgetsdg---qgtsalgpvtwvqrenrn
ppinpvlnlrfmvqae-styyrycmrhlfakkkgkanyl
>node14
lrkkchvkakilglrakvrcpekfl--phsyts-----kvkddatead-a
vaakavafavvgsdpkakfqpgvvmlgielqklykaitakakhfvaadll
tfdcls-aatalsqslmevs-kkamvhkaslhrpgkagrasstrrsfapl
krlckgglggvasrtikdlanql--d-ysavglaaaktqkihkdlggcta
nkqffktvgdhgplealkreikilcr----gkhhhpllyltksdlvscll
tcalvlasglkqkfrtkspckksgsaakangalhgdcdglndaslykel-
----ealggsesdgawq--qtvttvtgneyyvy------------ekagk
itprltpparg------mktfsdtnlsglikegnvymgaynlieqntttd
ytkdtlarlclcghlhlssksdkqpkletmatfiksyrgsvmfnfrllcl
rlylpyaghivlaaaqiqevvaktnsarv---ldddtlstekfvkqamkt
kecgsgqvycftnsnensryshvcetstfpkraskndlh
>C
ldakkvvm----iaaaktpsaienl--aqalqa-----rwakanisgp-s
ahanavtfnlvadspeatwtprlasavvnyqdwyksgaskdklliaanll
tvyctg-ranalarsisasg-hktv------ntpgkarkmktahagfyqa
rdttaenahgfeakwldeyaepv--d-feavglsganahkvhdslldc--
------aigehasleclraacklata----thrknpllfvsnkdkytcll
pcavkakkgvdqkvgklrpchiatentiisvgshaaantltsvltfknv-
----qhnggklrdsklg--hnrpstrggwhyvl------------rnesl
vtgqkstntkevcseqrtksfsntglvdllndeaeyqgayllaqqkaltk
ntagtdprlcsisllrkkgivsssektqrkfvfaekfrratgcafvlkcl
vgqveyaqssalrskqsrpalsmqstwav---rsdsallalrmierefrk
q-lgptikltfmtqke-hvfyrycvrkllankqkmsdyv
>B
ldativivaivakiivsdksatcellkshglka-----rwkdntamgrfg
gklgtghlglaaavtragrkidivfnvtqkmkwfeeltsesklllamnll
sqvyvg-lskskskklaagggqksl------qgfakcnparpqkikflsg
khtcvehakglktkssdsladqv--q-lresgesgcswdrcsdtllvsse
htefigdiggrgspqclnpeshlpci----tefyapvlflksttkyaclk
pvpqkpgtlpnrkisarrnchgggraginhaalhevsegiggeghfmnla
fehceplsgaindkvwt--havnvdrgemtfql------------vkagl
vltdlddnlkapcagsklrtfaqdefgqlikvgskreaavglveqntrfd
ysaiaparhcvqskvpdngangkgnnadtkftlkdkfkvvimveyrykys
kgkvrfsptqipkganfrasttsrrngvv---avaksvgslkyvknsfna
kqvggghrwnfaeqsg-ahytaycvgksfpqtgkrnhyh
>A
leqtivfitivnmlivfnklagcdi--shtlkg-----rwkdnsamgr-s
ghlktvqfglqaavpegqwksdiallvnlekkwyrptatesklnlagnll
s---vg-saseankaitggggqktl------ssfgrnhrmraqttsflsg
nhtcaehsmglktksaddlaqqveve-lqqgnyngamwnrcrealleasd
hnyffgqignrgplqcllqecklpci----aknsaqilylksvekytyll
qcvqkpgtyaqrkiskrhpcqggertaiadgalhdtndglggdqhfksi-
----sqlggaltgkdwptfhcihvtrnnkefvl------------ikepl
iacqltknlgipiqatklkafraneidnvvksgasrlaaaelveqktlfn
ftatttnrlalnssltnlgadgkqskspaqfifitcfkvvikvnyrfkcv
qgevkyaakakqreaefreggskrrngav---asirataglrelkagfnt
rqigggfswkftessl-vhynkfcegsmfpkngkrdqyh
>H
fksclnvkstyvelraadkcgrkla--pheyna-----kkgdgtveai-s
vaargcnyktkgadskmkfepaevilgtdlqkvfeaidtshshyfkadkf
dlncvqpttsalaasqshvs-dfaetlqsslfkpgkagrttsrhrsfvpl
ntlsmsglggvasksvmglacla--v-ygadgaganssheahpnlgdcps
hktflktlaehdplkslereikvlcqcepcgkhtrpllylgkagritcev
kcefvleiglrqtlktkscskkaggtpknngghhaecdlwnapdlfknl-
----kslsegasaggwr--gsvanesaiefyrf------------agvak
itprlvpsakg------akaytnthlsqlviegavhmgtyantdttstgk
yskrtlsklclcghakvaqkanmkpiletqcdfirdfidslmflyvlmal
hlyapfsekvvekhiqldeepshttsghs---ltneylpqerllkqpnls
kgcnddevycfthsddrvrysdqastgtfpnadekdqag
>G
fkryadvkakflglraaircgdklg--pdhvta-----kdkvgtteek-n
aaakacayktiganskikfepgvgilgihlqklfkvkdtaakrfyatakl
dadcvr-sttaltadimrvs-figeavssllfgtsqagrstqarrslqpl
nrlskgglggvvsrtvddlfcql--tvygavgleatsthsvkesmgdcpa
qntfmrpgndhapgkaieiqitilcqfdpcarhqhpfiylgrtgrimcel
ksafalakalkqkleakahcykaggvargngghptecngipaarlykel-
----pksrggnseggwh--gpvttitgiefyah------------dglgr
ivprlarsdqg------lkvyankresglimetkvhlgsyllitssstgd
tnrqhlsklclcghsglamkadmkprletmadvvkdyreallflflllsh
hlylpyaakivaggs-lddeashtaspqs---mnnenlptanllkqpvka
rscanmsvycfanssdcsrarqlcepgkfptvaaadqmh
>node6
ldakkvvsatvlvliaktrsgvehl--sqalha-----rwaeanimge-s
ahaksvtfnlaadipeatwtsriaklviqdqnwyksgasksklliagpll
tvacvg-sanalardmaasg-qpal------httgkshkmkatqvpfyqa
khkcaensrgfeakwlddyaepm--d-fepiglaganaekihdplldcse
htdffaaigehgsleclkaecklaas----tkrsnpllyvsnrekyacll
pcavkansgvdhkiakprpchiaadvdiihvavhatangltdvlafknv-
----qpnggtlndstwa--hgmptarggrhyvl------------qkegl
itgqkskavrdvcaqdraksfantglanllkkgaeylsvylleqhkaiak
ytavtaprlcsisllrskgiesssdkvqrkfvfvekfrrttgvnfkmkcl
igeveysksstqrskqsrptqsksststv---rsngalaavkfvdrafrk
qpvgpvlklafmvqse-avyyrycvrnliakkqkksdyv
>F
lrercrivmrnlgmrgkvkcsenfl--peqyhtnsdlpglrdpgaatq-t
vgpklsafsqmgt----sfqnavamngnelntlfkpqvprarelvgrdvl
pfdcwt-tapvliqqpkeap-rmalvhnatvtrpgksqhtlsarctfdal
krlckgglshtatrtakamisem--d-ypargaracqrmklakdagastn
ntdllktvgddgklgsltkeskimcv----kkgfypvlylvntnlikcyl
acklivkt------kskcpckr--dntkhnqalhndcqglqedaefsel-
----galgggesqagwq--qnvystkgneyyvv------------slpgy
vsahlppgeqs------kkaisdtsqpgvikngnvylggcglt-----ta
atrdnlfklclcghlqitsnkekqqnpdtiggylnkyrtdgifvf-lfcl
rly-------------isevqtvtklvrdvrglkeqalatpkfpkdaeka
tnmaggrgycfiag-easrfsqvvevspykkratreaah
>node7
ldekyvvnakvlrliaksrcaaanl--shalnp-----rwkengamge-s
ghaktvtfglvasipeatwksdivmlviqdqkwykagasksklllagdll
saacvg-sanelsrnlaagg-eqal------htfgkshrmratqasftpa
khtcaensggfkarsindlaeqm--d-yepvglagansqkihdallncse
htdffsevgdhgpleclkpecklqck----akrsnpvlyltstekfscll
pcalkpntaidrkiskrrpchaagnaaighgalhataegltdveefkni-
----eplggtlndsvwa--hamnttrggqnyvl------------qkegl
vtsqltkpvravcagarlktfaetgianliksgaaylgvygliehktiie
ytaitaprlcmishlrikgieakqdkvnqkfvfvekfrvtlmvnfrmlcl
igeveyagtatqrsaqfretgsksststv---rdngalatvkyvkrafks
kqvgsglklsfteqse-aqyyrycvtslfpkkskkndyh
>node3
lddkiviiaivakiivsnklaacdl--shglkg-----rwkdnsamgr-s
ghlktthfglaaavpqakwksdivllvsqemkwykpsasdsklllagnll
salcvg-saselsknltagggqksl------hafgkahrmraqqasflpg
khtcaehstglktkssddlaeqv--e-lqeggengaswnrcrdallesse
hteffneignhgplqclepecrlpcn----tknsapvlylkstekytcll
pcaqkpgtyadrkiskrrpchgggraaighgalhdtseglsgdehfmnl-
----eplggalngkvwp--haihitrggmnyvl------------ikegl
vlsqltknlkapcagtklktfaeneianlikagasrlaaaglveqktifd
ytaitaprlcmesslrdngadgkqnknnakfvfidkfrvtimvnyrykcv
qgevryaatanqkgaefresgssrrngtv---attkaiaslryvknsfkt
kqiggglrwnfaeqsg-ahytkfcggslfpkkgkkneyh
