>node15
kyivlgqfdkdmlrlagnqtikrnnnsspedgflg----fqaknfdq--d
vasgrefetttvcktaqkqhtnpseflssvvtwdlanhaypvfrgficce
vsllqgttklgflwavckmpliqdskeigdspvlggnvthrgkgv-fhav
lffkkagttvdgghsslpftlaresalkiypvgtspsgsfkwnlalvqqm
rllpts--tpqfkiyedhnpqhvll----lmvkdesakelmppaaadgyd
favwvdpiynathpdltsekgenkggnklttrl-qapgvvcs-igiafhk
e-gepggstlpfcagvvhlllgkesf-----------kvcwsedkhtnkf
kdsga---lqkkkcetscttdfeyes------------isitlrpgynaw
eidqka----e--cqprdekghgfhn--chkgemcglkcknssngqqpar
------tyhaalvefgcnlgnspqapptythmdkridhqpkrankayaph
gqlsggglvkqyagsslvglesaageysen--tn--dvdacviiktstan
vmlnyeafai
>E
kfkvlgtfdaaelvvtgihpcsrkllvepiadfla----fhakiydr--e
vakgkefqkksvpkligmqhgsgtdyvcgvvswqvaqfafsvllgfikcq
iyla---------yagckktlkeqrkpvaqqpeetgd--kvgdg---hai
iylekgatafnganacvafmlpsngavsayppgekdypkfkwtlalsqpa
ylltns--kraippypnetplsilm----adlldtaakklvtpnftkgfa
fgiwvsqiwrashsdlasqkldktpgeetsgil-kvpvsicaeisviyhn
k-kdpkmnglsfcddivgvtivvesf-----------kvqwne----ttg
myrgs---vhkskcqkscknvlkyge------------lgivlkpgypgr
yrnhqp----e--vepsnekgdgfqe--cnkgakcgakcvgtkaekesal
iprpsafntdylvgfgcrlgvnpvpdasta-----ideagkkdtrtyann
aivnalnlhddyaegpfiglakaqdqwkqafskdgedteqccikkggtgk
pllmleafsv
>G
gfahigpmdkeelstsfaaalprrlegypisefle----yiakkfsq--i
cvssreteskavckllddghalpntfgrniivdaladlafrvlldfiacd
tylg---------wtackvvflqgcsplgngrklkgs--hldkgv-lpai
lygkaggntingghtttnfvlpdgddlplypdsrlgygrvkwtfplcgqs
rllsns--aqayqvhegeetsttlh----lmvtetpaedahtpnfkhifn
favrlenvyrqshpiissqagdnkagntltgap-pagvgvck-aeliypg
enahigsnglafcegvlsltvgkisf-----------ianwtad-----g
kakqt---lhdgecdhnckkeakycp------------fssrlkseyktw
dlnhkq----g--cgnkgkkgegflg--cykratcgarcekyctgqhpsk
------atetqiaefrcrlhglgeraptlvatdkgvghqakkaekpfdsh
srlafmtlqeqfsgapfselqrladdwrek--tg--die---iqssggak
sglmyasfsl
>D
avhtlgkiesnkvklvaaayrrkknpeekdnvllt----fsvahfek--k
aacgpsiqdaevpkcgdtaqnspicfipvvgvwkltadiyapllgimscq
ariwsgvtndnfytqaclkplsatalktgnteelggtldatglcvsrhav
v--kktglkdsgthnsaeftlsstsvlenganegpagaafqwslgfieav
rvepve--apiftndetqrpaayllalqdvstpdesgkqlfpstsppgye
fyvwvypilptaeanlpsgknhdkssdkpqnwl-heisgtcc-ieitfrk
s---aafvgllycvgvldllqfkagg-----------nlawvldryhsls
knkal---lsknkyaddcfgykgdhystigaeaaffigfgktdvqpagsw
svarkaqpspp--idlkddkghlyhsaiphdgetiglkcaareagqdtek
------thqhlvcnfgcnhaksarktpaytnegmrvnqdpervarsydrq
nqmsggalvqgypatpvvgkdsaadhytqy--st--hvspcliiktskvh
vvldsleftl
>node6
kvhtlgqidtnkrrlveaasrkkknngapedvflt----fsitnfdk--k
aacgpsiqtaavcktgtsahakptcfigavgtwklpadiyspflgfmcce
arifggvtednfitsackkplmatalnigngpelggdvdstgkcv-ihav
v--kktglrvngghsavafslnravvlkngatdsspgegfqwtlgfvqqv
rvepit--apifsndetnkpssyll----aaasepsakelfpstspsgye
favwvdpiypttadnlpngknhnkggdkpntkl-hevsvvcs-ieiafhk
g---agfvglqycagvvdlllhkagg-----------klcwvhdryhsls
knqdl---lnktkyedscsgnfdnhyetigtdvklfiglgktdrqpqspw
siaqkahpscp--vqtrdnkghgfhs--phngemsglkcsakstgqdtek
------tyhrvltnfgcnyansakpapaythagkrvdhdpkrvarsyspq
gqmtggglvqeyavsplvgknsaaeqytqn--st--hagscliiktskvn
vvldsadfsm
>B
kletl-ktdknleqlahlaslrrsvktqpaaaltg----yresqfrr--e
skcgsddqttakcrsshnertspkcflgsygtrklphnvykinkqffccs
eqtlgttlsanfkspkclkelieqteavangpalgatltdikktv-fhgv
l--frtglkaegannnhafavflsrtlkmfglgaspgnrfqwsfalkkaf
rlessncaadpfrimkeqiprdyvl----llskedskkyvldpkvpdtfk
fnvimep-------dllggtqqnhggekvgirilhgvripsa-qpirlhk
d-gradfegagtcngvvnlmvkaveqendladwslfrkiywktakytlra
reail---fgstnfqhsctvdfedqy------------lsgakreeyapw
aqneke----s--chpredkghgfie--thlsrmcttncneaveamepgr
------tfydqlagmgcgfastarvahtftpleaaiehgpkavemtlaah
dvmdngsivmeyttsalsgknttvseytnd--pa--taaaammsfgaekt
amlqypsfyk
>A
klqilveldkdlrklaesamerrsaslqtpaamtg----fnestfsr--g
kkcasefqtattcdkgtdaraaptcflgsygvwkipqdvyrhndgffccs
ghalggvtsinhmtgicikpligqpnstgngpslggghndvkkpi-fnsl
i--ltagvpasgadtshpfvvsrsallavfaagdnpgpafqwkyalreef
pqepnqytnttfmieidedprkyvf----iqaqdksrkkilapmvadglq
lnawgdalfasekgdlaegkdhtnggdkvgprl-hgvrtvns-eg-----
y-eesdvasvgicdnvvelllkkadpgddlpdwslfhqaclksakyglrt
kepav---lgsvkseqkctgqfedfy------------lttstrkeyntw
thtqke----d--chprqvkghgfvk--thqkamcglkchstvdtheaar
------tfvgqlapygcqysntnkvahcytplqnsiehspkavqmayaah
eqmhdgpkvkhydtamlsgkgsavseyine--pc--apgkciitfdadrp
tmyhcesfyt
>C
kahtlgqvetnkrrlvdavsskkknnaapeglflv----fsittfdk--k
aacgppiraaiscktgkgahakpacfigatgtwqlpadiyssflsfmccq
prifasdaqdnfisgacktalattalnigsgpessggvgstgkcv-lsav
v--kktalksngghtevdfamdraiagkdgasadspadgyswtlgfvqqv
rvetit--aiifstdnpvlpniyll----anvtepapdeffpskgpsgfe
gamwvdpaypktcdnlpngkkhngggdrpnpkl-heisvvct-veaathk
l---lglvgleycaglsalllhkagg-----------glcwvhdryhsls
anhdm---lnksnyaeacaenfndhyptigsevklfinlgktnrqpqspw
sleqkahspcpdevqtrqakghgfaa--lhngdassltcsatsvdeetek
------tfngvlmdftcnyannaklspgitnagkrvdhdprrvsrayspe
gqmtggglvreysitsllakqpdaeiytnd--st--hagdcliikmskvi
vvqsspdfak
>node13
tfsvlgpfdkdelstsggsalprkldgnpisgfla----fiakkfsr--k
cvssreieskavckvlnnvhavpnafgqnvviwalvdlafsvlvefincd
vylg---------wtvckvtflagctpigsnralngs--hlgkgv-lpai
lyikkggstldgghttttftlpsdgdlaiypegklaygsfkwtfalcaqm
rllrns--aeafqiyeeekteavlh----lmvtetaakeartpnftqafn
favwvngiyrashpnissqkgdhkagneltgap-pigvgvcs-aalnyps
e-gkigseglafcdgvvsltvgkesf-----------imdwten-----g
kqkgv---vhdgecehnckkefkysp------------fstklkagynnw
dldhka----d--cqpkdkkgegfkd--chksalcgakcehyskgqqpak
------stdaeiaefkcrlqgtgepaptfvqkdkgvghqpkrankpydph
srlsfgtlqqqfagapfvelqqieddwren--tn--die---iqksgtak
vgllyevfsl
>node10
kykvlgqfdkdaldvagihacsrrnfaspiadfla----fhakifnr--e
vatgkefqtkgvckltgsqhsiptdygcgvvtwaaaeyafavllgfikcq
vyla---------fagckktliqqrkpignkkaingd--hlgkg---hai
iyldkggtainggnacvsfalpsngaisvyppgdmsyakfkwtlalcqqm
flltns--krafpryehempldvlm----aalldtaakelvtpnftkgfn
faiwvnqiyrashsdltsqkpdkkpgedlagil-kvpvaicgeiaviyhn
e-kgpkmeglsfcdeivgmtlatesf-----------kvqwnqhekmttg
mnrgs---vhkkncanscktvfkyse------------vgivikpgysaw
yldhgp----e--yqpsndkgdgfqd--chkgamcgakcnhtsggqqsps
------gsteylvafgcrlgntpassptta-----idhaskkdtkayaah
gkvdgaslhqeyadgpfiglqkaesewkqssptn--dtedcaikktgtgk
pilmleaysi
>node14
kyivlgqfdkdilstagnhaiprrnnaspvagfla----fqaknfnr--d
vapgrefetkavckllpkqhtipsdfgssvvtwalanyafavligfiycd
vyla---------wtvckmtllqastpigsnkalngn--hlgkgv-fhai
lflkkggttidgghasvpftlpsdgalsvyppgkmaygsfkwtfalcqqm
rllpds--asafriyedqkpqdvll----lmvkdtaakelmtptftngyn
favwvnpiyrtshpdltsqkgdqmagndltgal-qvpvgvcg-ialdyhk
e-gepgseglefcdgvvsmtlgnesf-----------kvdwtedkhlhkf
knrgv---lhkkqcdnscktdfkyse------------isivlkpgysaw
eldhkp----e--cqpkdekgegfqd--chkgemcgakckhssngqqpps
------tnaaalvefgcrlgntpqpaptyaqkdkhidhqpkrankgyaph
gkldgaslhqqfagapfiglessedewres--tn--dieacaikktstak
vvllyeafsi
>H
sfgvagpfdrdelntaggnalspnldgnpfsglpg----fiagklerryk
cissreiqgktdckvlnnigdvpgafgpsvviwelvdit-gvlvdfidcn
ayag---------wtvckadylaggtpvggnralpgs--kvskpn-lpai
lytkkrgpalegghddaqfslpcdgklpinpqgkvaygsfdwaypfcspm
kllwhg--vkafeiysdgkhagilh----lalpataag---tskftqsfh
fvvwvngiyraehpviasqngdqkagneltgss-plgcgvqs-aalafpa
d-gktgrsgqafsngvvaltvgkqaf-----------rmnwtvn-----a
rrkgv---thegecehrckqefryda------------fatklkaqytnw
nldhrp----n--kqpkdkkgegike--nhratlcgvksekynkgqqpak
------stdsqraefgcgveqvgdhtsvfvqkedgvghqpkrrngpyeph
armsfstlqeefagppfveldqaednwrea--tn--qvk---mlktetst
ialdaqifsl
>node7
kvevlgqidkdlrrlaesathkrnnnsapedvflg----ftatnfdr--k
aacgpefqtatvcktgtsehanptcflgsvgtwklpnniyppfkgficce
arllggitkvnfmsavckkpliaqakeigngpalggsvadtgksv-fhav
v--kktgmavdggqssqaftlsraavlkisppgaspgesfnwtlaliqql
rvepts--apqfkinenhnprnyll----laaqeqsakellppvapdgye
favwvdpiyestngdllsgknhnkggekvntrl-hevsvvct-igiafhk
e-gqagftgmvfcagvvdlllnkads-----------kvcwsadkytnrs
kdqav---ldktkfenactgdfenpy------------lsktdrqgynaw
aitqka----e--cqnrdkkghgfhn--ahngemcglkcnasssaqdaar
------tyhralanfgcnygnsakpapsythmdkrldhnpkrvarayaph
gqmpggglvqqyavsslvgknsaaseytqd--ts--aagscviiktsean
vmlhydsfpi
>F
kyqvledfdddalgvsgyhpcsrreftspiehllaacfvfhekifnk--a
vaagkefqtrgicklsggehsvatnygcgkiklaaadyafgvglafdkye
lfla---------ftnckktvvqarqpvankpainnh--hlshg---pnm
lnlkktgksinggatcvskahpksgairvyrpghqkydkfkrtirlclqv
flltns--ksafprtdhamgpdvlm----aall-satkelltpnftrgfc
fatwvnsiyrahhsdltsgkadkkmgedmsgil-kvhvaicaeiasvfha
k-rgpkmenfsfcdeqksmtlaaksf-----------rvpwnqheklatg
mnrgsgggvhkrtcanscptifkysp------------vkeveepgysaw
yakhqs----g--yqpgsergegfrd--shkgnksgerckhmngeqqtht
------gsteylvafncr----ppshpcta-----tdhkpnrgttaytah
gnvdqmslhteycagayvgmqkddsewkqsstvd--daddcaikksgaeq
piimletiei
>node3
kleilveldknlrrlaqsatnrrsaksqpadaltg----fnesnfrr--e
ancgsefqtattcktgtaerasptcflgsygtwklphnvyrpnkgffccs
ahalggttsanfmsaickkpliaqpkevgngpalgatrtdikkti-fhsl
i--lktglhasgansshafsvsrsavlkifaagaspgnafqwtyalkkef
rlesanysatqfrieedhdprnyvl----lqaqdeskkellppvvpdgfq
fnvwmdplfqsskgdllsgknhnsggekvgtrl-hnvripsa-esirfhk
n-geadfagvgtcdgvvdlllkkadsgndladwslfkkvcwkaakytlrt
keaal---lgntkfehactgdfedhy------------lssakrqeydsw
ahtqke----e--chprekkghgfik--thhsemcglkcnatveaqeaar
------tfydqlagfgcgyantakvahsftpldasiehgpkavsmayaah
gqmnngsivqqyatsalsgknsavteytnd--ps--aagscvitfdadst
amlhypsfyt
