>node7
gdntevedlklat-icldavracnlgafrpvmilgykenanlqcrd--ek
dtlksksrqligffiglslyrqtqkncindkdtpkhfgitltaq------
--teggkhtcdlvpdnqpylggkfgyh-egif-fcly------pyvgflq
qddgtgpnlptfggksqhspwapvannnakaicsagellvqsadrrllcg
----thedskvrk-afspvknmacqetqqn--tggkgegaeraqnesnsm
lanhdqsht---rkgackpahik---kpidntdhspqtminseeaneedi
eknsflcmpsyhalgfvhlagasvreemyyaqhinplnyddeiagsaiss
ymcv-----csslhdegfsfragddllpgrhmpkepkdfvivvqkgalmk
s--ghdkpreeefelfpqyvpa-----vvysyklpqkacvekdkplkdpc
kakeiaigvprvlkdgkldmvscsftvfkk--giqvpdiyglelapfs-l
gvvkqelddtgdktnqedaevqrhgldalglaedslsddktgealrdgfd
>G
idktaitsmkrvpilytedipgchmtkfkggrvlgcmdranfqcdk--qa
dcrdksdrtavggyviafpysvtqdcsvfekkaprmyl--mlad------
--addsahqccvtprnssyvdakmehgekdil-ycty------rnaaflq
tgdgerivprifaskhtgsrgkqggadhckavcrtatglalktpfrfqcg
----teeqvhsdlqpltancplgcqptnen--gsrrsaasgkapqelqnl
gvlhspdsa---kqnspintifk---gpi-kkndpplgrvpegasae---
-lknfsflctchvvvypviaphsmkkgiyheqhrlpvswenkvggltvad
yltk-----kktvyqdaltiwngeeilpgsnldkrs---evvlkhgdtnk
t--flsktraddvdsfpkastp-----lgykyeepgkgclgeendlkaac
aakqfpfgerlafkednipvkgcalgvlgi--siqvtgvygadsaplecl
cvamqdlrgnfadln--pastkiyqmqslaqargikgkrnsteslsagyg
>E
ttdvkeialnrap-lcikgirtcalsqfkggkiltykeketlqcrkpadg
darkcaepgtvafyneefgissghghclhtkeemrayvvpldgd------
--sdgpqnrcgaipedelcaetgfnts-ekla-yciy------tndaflg
hpqqtsealpkfnfkdaitkwspdnnlhcksvcrqatllvhdkqfhfkcq
----stdelmidkqalppncrntchts-ee--kggqsapsgkypghlrdk
pedeevtdkesafrgacsrsflk---kavnedtdaphtrmtegaeyesmv
klgkyeftc---aivahdtgqaairestyyalnkspllweeetkdltida
ymgk-----gdtmmeggfhywgdedklpgrplghnc---vvvlkkgekpk
s--slnkprkdqlvdyrrpaasgansdmafrytipggdvlcdivatkgvc
msklrgigeplayknvwfptvaceft---k--svrvrevyslesdpsaif
tvlrqaldtnttsan--hglhrglklihlasksnslphsyivgvlkyskg
>node13
snnsevismkrtp-lyntdipgchmskfkggrilgyknrenfqces--qa
dcrdnsgkasvglyvpafaynstqdhsvnekktprmyqisltad------
--sedsdhrcdvippndsyvdtkfeys-edil-ycmy------rndaflq
ggdgvggtlpifgskhthsrwtqggennckgicreatglsqknqfrfecg
----tdeelkndkqaltpncplacqptqqd--kgrrsnasgkapqelqkm
svfhdedss---kqgscrnaifk---kpi-knnnpplgsvtegaatedte
dlksfgflctchvvtypvigphavkegtyyaqhripvsweekvggltvaq
ymtl-----kativqdglcywdgedilpgsdldkrs---evvlkkgevhk
s--alskprtdevssfpqacqp-----lgykyeqpgkdclgeetelkaac
gakefpfgeslafkdinlpvvscafsvvgk--dievtgvygaddaplgcl
svasqdlkangtqas--aaiakeyqlkhlaqkrnasgkrkstetlnvgyg
>node15
gqnaevedlklaa-iclagvracllgafrgvrilgykenedlqcrd--eg
dsmrskarqkigifigasayqptqkhcihdkdtpkrygitltaq------
--segpkhecdvvpqnqpyvevkfsyh-egif-fcly------pyvsfmq
hpdgahvtlptfggrsqdsqwaqvgnnnckgicrdaellvqsnnfrfmcg
----thedskvrkhafpavspqacqataqn--kgengegperapneartm
lanhdeget---rrgacksaqik---kpidktdnspltkivseeaseeee
dlksfiylctyhtlpyvnlagasvregtyyaqhrlplnweddiggltias
ymav-----catlvddgfcfqagedllpgrhlpkes---vivlkkgelfr
s--ghkkprddefeqfpqyvpp-----lvysyklpakkcvgnekqlkepc
kakelaigaprgikdlklgmvscafgvlgk--svqveelygleltpftcl
gvvkqeldetgnstn--eaeakqhglialsqaddslsedytvealrqgfd
>node6
gtvfevhglvlap-vcldavracmpaafnpveiigyknndggtcrd--gm
dtlkskskqligffigvglykqtqrncigekdtpkhfgldltaq------
--keigkhtpgvvpgthpyvggkfgfh-egif-fclf------phvgflr
kdastgpglgtfggkaqygplaraaakhakaicsavellvqgndqpllcg
----ahddnkvrq-vfdplkylgcqettqn--aggqddgnerapnecasl
lanhdqpht---rtstckpahik---raikntdhsaqtmvkgeeadiedv
eknqfvcmptyhalgfvhetgahvrddfyfpqffnglifddevagravvd
ylcv-----skrqhdeghafrdgdellpgrhmpkkpqeflivlqkgallk
t--ghekpreqefelgpqyvpa-----lvynyklpvkecvendkplkdpc
kgdlksigvsrvlknksldlvtcsftvfkk--gltvpdehgldlgpla-l
gaveqqg--tgdrrdidhaeirrhgldalglaedslsdnktgeeprdsfn
>B
vdttsvqdnnlat-acletlpscklehtiphltlgtkqdpdlscrn--sr
dtip---raligyfpgpkvyrqkdkkciegihspqnygvtligh------
--tqggkdsceliddalpflgtkfgit-kelf-mcly------pyvgfld
hqegdgpdvpafgghceqtpwepvisrqakficargelvphfastmllsa
----mrkeprark-dytkirnkpcaeadqtqtscadvnesdngahdendv
sdkrnmsti---rdadckephrk---qpitgkkhkpesvihrdeaaekrf
lhegflclpaycslgfvllagtrikaemy---hitpggkddeifggsika
ymcm-----crnlhdgpsiirhcedlltgkgmkkdekgmhvvvdagnmfk
n--sadaprekkfqlfppyipa-----gtfsykl---etiakeeavkrkc
kekahrvgipqdskdgkqnlatcgfamykq--vvelseeydlviapfs-l
nldaleltdgglsgthqppeidrqgldalgmrgeklhdqrpgsdlpdgfg
>C
gtvmdvhglelap-icltavracmpatfnpaefigfrnnqsgtpvn--gl
etlkskskqligyfiggalykhtqrhcigekdtpkhfsleltat------
--reigkhtpgevpesppygagdfgfh-agif-felhdgsmfwphmallc
kdeatgpglgtfggkdqygalarsaathgvalcscvtllvkgnaqallcg
----dhddtrprq-lfealkylgcqetten--adgqddgntkvpndcasl
laghdhqat---ptstckpnhyk---kaiknvdqrtqtmvkglsndktdi
ekdqfvsmptyhglpfvhevpahvrdsfyfpqffgglifqegvggrtvvh
ylci-----srfendegntlrdgtellpgrhmgkkpqkylvvlhkglllt
t--ghqkprqqefdlgpsyvpa-----lvynynlpvkecvekakplkdpc
kgllat-gvsrgvknksialvvcsfiifklacglnapddqaldlgpit-m
gavkpqg--lgdrtdtsseeiwkqavdalaltddalsewrdaqeprdsld
>H
snvsnvismsctp-lyynsirgcfvrkfkgvqvlgfknregiqcet--qa
dcikrtrmtgielhvptfsynstedqgvgsshqprfyhiglead------
--thitdhrcnvvhpkdsyvqdkyeyk-eqilefcmy------rndsfae
ggagvggalptfggnhthnqstpggenkcagecrgatglnqenefrfeci
sfqatndelkndrqallpdcplasqpteed--kgrrsdaggkaphklekm
avfrdedss---kqggcrnaifd---kpi-knhdpplgsvkegaetadte
dlnnfgflctcqviaypvvnphalkdgayyvqhciptqweakvaalavaq
ymttrkgetkrtivedglcywagddmlpggdldrqp---elvlkagevhk
gltalrkpradgisvfaqacqk-----lg------nkdclpedteldaac
gakefglgeslafkstnlpvvtcafavlgg--eievssvygadesplgcl
avasehlkidglhas--sditkeylakhvvqlltasskrktiealnagyg
>A
sessslenhklat-nclaavrsckleqifpvmtlaakqqatlqcra--ek
dtmiadgrqliglfpgpkvyrpkdkkylkgehkskhagitfegr------
--seggkntcvfvnnealylgtmfgyq-telf-yaly------pyiplld
agqgmgpdvpelsgkvehtpwncvtarqmkfvcaadneipkfadrtllan
----fhnsprlri-eftqiksmsceqaghselvgedgkaeeradndpnns
ldnrsesgi---rranckeaqrk---hhmagsdhtpdtgihpdgenaehf
iheaflclgdyqsvgfvplagrkikqalyyhhhiiplgladeiggaaika
ymcm-----cgrlhngggpssnveelltgkhmpkeeiifvilvqagallk
n--dtdapreqrfelfpqytpg-----ehlgykltlkdycarsdpvkqhc
iekeaaihvrkhlsegkqrlvdcgfavlkk--iyllsstygliiapfs-v
nleqqtqgsaghktkhtdaeverdsfepwvvkgdkvsdskagsalpkgfg
>node3
sdntsvedhklat-icletvrscklgqifpvmtlgakqdanlqcrn--ek
dtlksdgrqligyfpgpkvyrqkdkkcitgkhtpknfgvtligr------
--seggkntcelvndeqpylgtkfgyq-telf-fcly------pyvgfld
qeegtgpdvptfgghsehtpwgpvvsrqakficaagelvpqfadrrllan
----mhdnprvrk-efsqiknmpcqeagqselagadgegadraqndsnsv
ldnrnqsti---rkaeckeghrk---qpiagtdhtpesvihsdanneehf
lheaflclpsyhslgfvhlagtkvreemyyqqhitplglddeiagaaika
ymcm-----csrlhdgggsfrhcedlltgkhmpkeekdfvivvqagalmk
s--sadapreqkfelfpqyipa-----evysykltqrdyiareepvkqpc
kekeaavgvpqdmkegkqnlvtcgfavfkk--viqlsdaygliiapfs-l
nleqqnlddsgdntnhqdaeverhgldplglkgdklsdekpgsalpdgfg
>F
nanneglalkqap-iclkgirscpltrfkedklla-pekenlncqn--dg
dahrcheptsvglyvsqftskmtkghcindkakprryvvnlsad------
--sqgpknqckaipleefyiktnyeyq-eglc-ysvy------ihdgflp
hpqsaedsipklvfknaltpwdanrahhcrgkcreqalankettikydyq
----gaydlvvdkvtfsancqttcgkv-ae--kgrqgsatgnspdelrnk
sqaheinkkgpyvrgrctkgfikhaaksvdetgnqphprateigsydsde
alnvydylsvyhftitaangqpalsektyytshrtpelweeavgslttaq
fmgq-----spamieggfslwgddemlpsrnlssdi---livlkqgqkhk
l--nkskprkdelahlrqnttpsdnghltfhyhlpdentlcddvptknas
vnklrqvseplaykdlkfptvacnfsllgk--svtvrevyglqddplaal
svlrhelnantqkan--isiqrdlmvihlpqksngvprpyttgelavgfg
>D
gavievhglvles-lcleavrtcmpvafnpvaiieyndkgggtcrd--gl
ktlkskckeligffigiglykqpesdcigvkdtprqfalqldaqystlal
krkeig--tsgvapgshayvggrlgyh------------------vgflr
teaksapglgtfngksqygplsqaaarhvksicssvqllvqgddqallaa
----ardsnktrq-vfgalkhagcqstdqh--gggnddgkergenecdsl
lanhqepht---katkc-pgyvn---haikncdhsatkmvvsqeadisdk
eknqrvclstyhaaafvhatgahvrddanlpqffdglvfddeasgraivg
flcv-----sarqhddghatsqgdsllpnqfmpkkpqsfaqalqlgali-
-----erpmgqelehgpkylpa-----lvctnklevkeclqtdsplkdsc
kgelksigvsrilkdksfelvtharvvinr--glt--deraldlgala-l
gvveqqg--tgnvrdinhaeirrnelktlglaedhlsakkhgdiprdsfn
>node14
snnsqvvalkrap-fcltgiracplgkfrggrilgykekenvqcqn--eg
dtrkskgratigiyvsafayqstqghcvhdkdtpkrygisltaq------
--segpdhqcdvipqnqlyvdtkfdyh-egll-fcly------rneaflq
hpdgtgetlpifgskntntrwtqggnnnckgicreaallsqenqfrfecg
----teedlkvdkhalppncpsacqataqd--kgkkgeapgkapdelrnm
vasheenes---rrgacrnalik---kpidknnnspiskitdagatedde
dlnsftflctyhtvtyvdlgpaavregtyyaqhrlplnweekvggltiaq
ymal-----kativddgfcywggedilpgrhlakdc---vvvlkkgevhk
s--glskprkdelktfpqaaap-----lvyryrlpgkdcvgdekelkeac
takelgigeplgfkdlnlpvvscafsilgk--svqvrevygledapsgcl
svlrqelkangtstn--aaiakdyklihlaqknntvgknystetlrvgfn
>node10
ssdtqaialkrap-iclkgirscplskfkggkilaykeketlqcqn--dg
darkchepatvglyasafafkstrghcihdketprsyvvslsad------
--segpdnqcdaipqeelyvetgydyq-egla-yciy------andgflq
hpqateetlpkfpfknaitkwnpnsnhhckgvcreaallsqdtqfhfncq
----gaedltidkqalppnckntcqtt-qe--kgrqgaspgkapdqlrdk
aadheindkepalrgacrrsfik---kpvdkdtnsphartteagaydsme
klnsyeflcvyhaivtvdngeaairedtyytqhrtpllweeevggltidq
ymgl-----gasmveggfcywggedmlpgrnlssdc---lvvlkkgekhk
s--slskprkdelatyrqaaapdansslvfryrlpgentlcdevetkdac
mtklrgvgeplaykdlnfptvacafsllgk--avqvrevygldddpsail
svlrqalnanttsvn--vaiqrdlklihlpqknnsvsrsyttgelrvgfg
