>node13
slleyhhailvcgdlrggedcrdgglny-------efsls--tkec--gl
ivvnh-----liqydftlydgdrkffhqdcpkfyrtt-ikfifl--eeev
chgfdshvkkfeagfklaryeasr-------pagqtagagcpqtpdvpse
vkeswtwrnvfysgmfksgqylsc-dlvtddsnsekrkhsghrclsiker
---lgwetkc----------hlafllvyvlgcnevhh----k-vgfkyeg
kklysikktlkslsgavecvqrlgnlade------aeiggdnvikklaas
isqvckcc--iwscdrfvkeylgglhrepswatiltckt-tfnyha----
-----naffcitelekkvgvcft--fanmmypetvesqifgkkkeelekg
kktcywkkrigtkgeqrlgkeppkisagnleqsrcpsskdstqhytacnv
etgiditaceigdlekqnwglftrleklsggpaswtlynagtgthl-lgi
----avsttrvvptrh---pvahsakhsfsdrkrpaddcgnsqdsrtgyd
acyknggsgdlledgyeimesqgtefsf
>B
glvty-----vcnclwgsfpccgpgfkl-------hagetdeepifgenl
lgytr-----vvhfs-stdqgstkllalscnplsgrs-aggtlatpehev
aqffhsqkplfgkefcvg--gwlgqagstlerhgrpeyseahgaseksrd
naelwvwtpvflkamfrgvqqsltidkesgeeycngkrssgasgldakak
---lgkeefd----------idvmkiqf---------------lvyc---
kdsfgeknkykidkpkntagekwktmsta------tdidksaiveamags
lpavykccrvehrakcfnhkyvggvgqsggwggpafcer-pfnyra----
-----vgyfcpvplkmrpatkfkrafrrkrhkakvmetvfgkakndkatn
nvihysldklpaagdnrlgadvllvttnvlagprcpqpikheinftpdkc
vethnaqtsflglvekqevgglnelkkil-gagcaeqeqfnlgsamrpsq
----vlpltavhqnks---pvayfathafaglkkvkeapedsanerdefl
gcnkaakpr------yhcqparstdfkt
>H
pllqfhqnilvigdlrsgeacregslly-------dfsle--tsec--cl
lvvnp-----liqtdftlyegdkrvfhedcpkfyrtt-pkfiml--eeai
chgfeshvsafelgyklslyatgr-------pagepngagcpqtpdvpke
hkagwtwknvfygsafds--h-sv-dlvtessnseqrkhtghrslpiker
---lgwntkc----------nlkfllvyvlgcnevhh----h-ltfkfkp
kklysikkttkglslavecvhrlgnlalegsradrfeiggdqikkelsvk
yghvcgcc--vwncdrfvkaylgglhkeafwhvilicdt-afeyhacfsl
halstnaffcitalekpvgacfi--ydkmiypetvepqvfakkqselekg
grtcywkkskgakgeqrlgkdpgkigasnleqskaqsgrgkqqhysgcsi
ntdvgitacvvdkldkqtyglltrleklagrppswtlfelgvgthl-lgi
----avstarvvptks---pvaqspkhqfsdrkrpaadsgdgqdsptgfd
acyksggssdlldkgydimekpgtefsf
>G
adlelhqgvlicgdlrgaedcndggldy-------dfslt--tkac--gl
lvvnh-----lvkydfvtyrqakkyilvecnrfyrttqlkfiyl--eeev
chafdsnvkkfeggfrlahlqesr-------pngqtagfgypntpdvese
vkeawvwkhalytgsfksgpyltc-dlvkdnsntgprrhngrpcseikdr
---lg--tec----------nlaf-----lacneihhsqsak-isfsyeg
kkmfsikktlksssgqvecvqrlgdltne------aevggdniikklaag
iktvckcc--fwdcertvneylgalqrepswaiilaskt-afnyhp----
-----haffcitelarkigacfq--fadmtypeavgsqsffsskdeletg
rklcywtkrigtrgdqrgykekpkisagdieqstcpaakdripeyatcni
ttgiditgceiteiekeewalftildklsgepdswgfsnagagthi-qgv
yrdkavstsriaptkh---pvahsakhsfserkkpdeecgngaaswsgyd
acykntgggdllkdkyglienggtgfsf
>C
gphtldttflpcdelwpqsptcngalkf-------kagesnkargfsenl
lgsgr-----vvretstsyesl-kffvtlaphfgnha-vgyalvtpsndv
aflakyqkpghtkdpcntsfirwk-------khcqkkpanihgti--srq
kveawewaclfnllklhsigqavc-dikqdqtfdrskrtagavgldckkt
vtplakenms----------qevsdivyegarqrqkh----hhilyk---
kklfgvvlqfhkdggalddsdnwaampss------kevgknniiqs----
isdldkcrri-------------altetgawagpilcep-pfgyga----
-----qswykiitvrmnpatvfv--srhkkrlenvdgrifgkskieqaha
ktlyykkdlapakpeqkvgfaahfshtniklaarcppaagfqvsfsakts
aeasivhraviqvvrdtavaamlqlklia-gtacwpmencev-gtmcigs
----tiplpqllllkh---pikhgtrhvltglkvvaehsdtakgdrpgpl
hcfsedkpa------ehchpsksaeyrf
>D
glntlatplivskelwpafpccdaglkf-------tagqtsraaifgqkl
igsdkkhcakvvratfssyqat-affltlspefgdkv-lgfalvtpghea
avlsnyqaaahvkqfclktfvhck-------qhtqsvvqpaqgal--prl
aidarlwkclfnlaklhgmghalc-elnekktfsrikstegpvsvevksd
---lakgala----------vespglvyvsrrpralh----ddilyk---
kklygvhlqfnkdgvtmdqtdnwgdmpns------keadkdkliqs----
vaelymccrk-------------nlahradwpgrvmstp-sfgyil----
-----dsyvvlvsvhknprvvrv--grhqrnldkqagrvfgkdgldaahp
ktpyyrrdlspskgatnvkfaaqftqtdimavvrppegteheisfspkta
vdtallnravlgnlrrppvgqladlklvt-ggtywplakctlctamcevl
----qvslgpllvdkh---pidhdgphafsgl--veehtdngagdqpghl
ncfsrdnpg------erhhgeemkhfrf
>node14
clieyeqaflvceelrgaydccesglky-------efsls--tpkc--gl
ifygr-----lvpydftlydgdskffhqdcpklnrta-vvfpflvkehev
chvfnshvkkfskgyklgrfdtas-------ehcqtdgtgcpqtpdvpqe
iieswawrnlffssmfqsgqylsc-dlatetaydnkrkhsgprclgkkek
---lgwetkn----------einpkivyvigheevhh----d-vvfkyeg
kklysikktlkslnnavesserldamaee------aeidknnvvaklaak
isevckcc--iwpckrfakeylgglhrdpswattvtckt-tfhyhv----
-----ssffclvalemrvgvgfd--fankmypgtvaskifgkakdelarg
kkvcywedrmgkkgeqrpgkeapkisagtleqsrcpestepaeaygpksa
qtginitpieignlqkqswglftdleala-gpscwtlqdvgtgttlcigm
----ainttrfvssrh---pvahsgkhsfsgkksvddqsgdsgdartgyg
gcfkndapg------yeimestgtqfsf
>node7
glvsydapflvcdqlwgsfpccdaalkf-------sagetdkapafgenl
lgfgr-----vvrytfssyegstkffaeecpqfskss-vgftlatpghdv
ahlfnthkpkytkdfclgsfiqtn-------nhcqsdaaeahgapdkpre
aveawiwtslffkamfhgvaqalc-emstndtyekskrasgpralevkdt
---lgkdakd----------eempkvvyaiaranvqh----ddivyr---
kklygarnefkkeggaveavekwhemqae------neidkgtivdalagr
laevykccrtefptkrfkdqylgglgrsgawgdpvlckp-pfqyav----
-----esyfclvplrmrpgvvfd--frhkrhkgkvngkvfgktnteaaka
ktlyyrkdrmpakgekrvgadaalvhtntlaavrcpqptghevnfgpkts
vdtahvqrailgnvqrhslgvlaelkliv-gascwpledyalstamcisl
----amplsplhegks---pvahtgkhsfaglktveeaseesaddragyl
gcfkkerpg------yhchpsnstqfrf
>node10
clmiyehefamcwlmkgvydcsesglky-------qfslp--vpkc--gl
-fggr-----lvpydftlydddttyyhtdcnkvnrvs-vlfsftvkqhal
clvfklhikkfdqgyklgrfdmsa-------ehcrtggtgcpatadipqg
iietwvwkelffssmfdsnqyhsc-dlstetvynnkrhhsgqrtlakkem
---tewqtkh----------dvnpkiayvigheeahh----d-vvfryeg
kk----kktlktlnnalessehtgamaqk------egvqksnilntpsvk
vgelckdc--iwsckhfaneylgslnrdpgwattvtcga-tfhhnv----
-----gsffclvalnmrigvafn--fgnkmapgtnhnkvfakakddltrg
kkasswadrmgkkgqpgpgkeapkieggyleqnscpqftdpvetygpkst
aigisatpleigngqkqnwslfanlqafa-stscwvlqvasadtllciga
----tvnatlfvsgrh---pvshagkhtfngakfvesesgasgdartgyg
gcfqnnapg------ysikkatgnqfsf
>node6
glhtldtpllicnelwpefpccdaalkf-------kagntskapafgenl
lgsgk-----vvretfssyegt-kffvslspefgnka-vgfalvtpghev
ahlanyqapghtkdfclksfiqck-------nhcqskvaeahgai--prq
aieawiwsclfnlaklhgmaqalc-dlnekktferikrtagpvslevktn
---lakdama----------eespkvvyeaarqradh----hdiiyk---
kklfgvhlqfhkeggtlddtdnwgdmqss------kevekndiiqs----
iaelykccri-------------nlahsaawagpilcep-pfgyav----
-----qsyyvlasvrmkpsvvfv--frhkrhmekvdgrvfgksnteaaha
ktlyyrkdlspakgeqkvgfaahfkhtdimvavrcphgtghevsfsskts
vdtalvdravlgnvrrhavaalaelklit-gatywplencalsatmcial
----avplapllvnkh---pvthggrhaftglkvveehtdssagdrpghl
ncfskdkpg------ehchpskstqfrf
>F
clmiyeeefmlcwlmdgvydcrdpavky-------qhdlp--lprc--gl
-fgsr-----lcpydftlyddettfynttckrvsrva-vlftytvkqhal
ylifklhikkfgegyklarfdmsa-------dhckggsagcpaltdipqg
imvkwvwkamffsnmfnsdqyhtc-dagkepiyssrr--savwaigkmel
---stwhaky----------eiqpkiayviahrealh----d-tvfsfag
kr----kktlksfkaaldssdqsggmsqq------eeaqnsgflytastk
vgalcnec--irscehfaneylsgld-----------vcstthenv----
-----gtfsclvslkmkmtvasn--fgdkmapgtevnrmfkkakadltrv
kqasswpervqkighpgpgkeaprianqymqhnscpqitepvetyspksy
avgsaatplelnhgekqnwelfpclhafa-stacwvlqvdsldtlwtigs
----svdanlfvngrh---svhhsgkhtfngakyvdhnagaspdarsgyg
gcgqndapa------yailkatenrfqf
>E
glmiydhqiamcwlakgvydcfqagiky-------qfsla--lpnc--aq
-fgsr-----mipydftlydeaktyyhtqcnkvsnvn-vlfsitvtenql
civykhhikrfkqgyklgvfdlsg-------dlcrtgntpctpthdipqg
ieea---tealtasmfdvdeyntc-elntetvlnnnrhqpgqralskpek
---tewltka----------dvnskiefvignpashh----d-vvfayes
kk----nktlktlnnaletsdhtsagwqk------eglitsnilhshnvk
vaelckgc--vwpckqyahgylgdlgrepgwasavtcgi-kfqhav----
-----ppffclvtlngrigv--------mmaaganhikvfskakddwlrg
kksetsdecrskkgqtgpvkedvklngefvepnscptftdpvgqfgaksv
aigisalplecgfgqkqdwslfaklqamt-stscwvvqgatvetklclga
----pvngvlfvsgrq---pvkhngkhtfdggkfvkgetgitgnarigyg
gcfmntepg------ytikkavqhrfsf
>A
slntyngptlvtvclwgdfpscapeilvgnvvppllagqlaqepfflenl
lgfsp-----vvragfsafegwtkqlpgsclrlsgks-vgnalgtavhnv
heyyntkkplydkqfclg--alig-------vhcepaeagahgasgkprn
tsgkwdwqsvyikglfhgiqrnlciekavneefkkgsstpgarevelkln
---lgkdttdqetvwifsqvmgmn-----ygrpndqh----devvyc---
kelfdsktdtkigkkaiaavesstikhah------leidkhsivdqmsgr
lpevykccpteqsikpfedkylggigrsgswnspvfcep-afnygd----
-----vsyfclvplkmrapithk--fwhnrhksrvydtvlakesndttks
kiilyrinrmpasgdkrqgpdetlvtaniladarcpqplsheviltgnkg
vgtpnvnkwflghahrhplgvlqslkvcv-gnscmplqeykpgasmkpsk
----dmplealhqnrsaqdkvayfadhgfeglkvvktageespdnraifl
gcykkdrpa------fqcqpgrttnfns
>node3
glttydgpalvcnclwgsfpccapglkl-------nagetdkqpafgenl
lgfsr-----vvrftfssyegstkflpgsctplsgks-vgftlgtadhdv
sqyyntqkplytkefclg--slig-------shcrpeaaeahgagdkprd
ttqpwiwtsvflkgmfhgveqslciekssneeyekgkrtsgpraleakin
---lgkeatd----------iemgkivyslarantqh----delvyc---
kelygakndfkiekpattavenwhimhae------teidkgtiidamagt
lpevykccrtehstkrfkdkylgglgrsgnwgspvfcep-pfnyad----
-----vsyfclvplkmrpgitfk--frhkrhkakvmdtvfgktsndnaks
kiiyyrldrmpasgekrlgadeplvstnvlaaarcpqptghevnftpnks
vdtpnvqksflghverhslgvlqelklii-gascnpleqydlgssmrpsl
----amplsalhqnks---pvayfadhsfaglkvveeaseesanerahfl
gcykkdrpp------yhcqparstdyks
>node15
vlvyyeapflvcdelrgafsccdnalkf-------efafaekapnf--nl
isfgr-----vvqytfnhyegdskffhqecpqlsrss-vvfalcvkshdv
shlfhthipkytkgfclgrfnhan-------ehcqtdsagcprapdvpke
aieawswsnlfftnmfqgvqhtsc-elstntayenkkrhsgprglekkek
---lgkdakt----------eekpkvvyvighdnvhh----d-vvyr---
kklysaknelkkengaveggerwnamqte------neidkntivtklagr
laevckcc--nfpckrfkseylgglgrdgawgsavackp-pfqyhv----
-----dsffclvplemrvgvgfd--frhkrhpgtvaskvfgkitsedard
ktlcywedrmpakgemrvgkeaelistntlamarcpqptdhaesfgpkst
hdtvniprealgnvqrhslglltdlella-gpscwpledyalntamciam
----pmsssplhqgqn---pvahggkhsfagkksvddqsgqssdartgyg
gcfknerpg------yhcmesagtqfpf
