>node3
kclplnilsvq-ggwtaqngtalwllkyrvtcggalsvdsptgllghhen
hfaariqldtq-igh--------isytpnlsndgdvgtiytlyevfdvak
hfdiaaykikslnl-----tcikehtnmhyd-ntdt-krgigkwffqkla
teylggkdpgesghpfyagrqdskngeltftesansnnpemnfvegwmss
iyrrgqg-gdydegdisglqvdhgktktvpkks---mslpgvtsgaecql
ilt-wakcklrtsgdsgg-raecklgadlgfhhadch-------------
-atdtallhe-kqgageerikkeilklrkcfmfkagvvstqyfpatsidy
cvkkdnfsgnerl-gsgsltyplttgdtvkqmpkawnlsvcsndepm---
--wriagvgklatslfivfkirkqltkfldvpagakavlknqkqgpstnm
d------gktrnsvaetepshakkdpganpfkqnpqlpvapafapp----
---atlgyskcvmspvvgipeqrtgvgneyggvsvl
>E
rcdperclnvg-thyeekddviyylvplrkvcsgel--nccmefdgkeke
vytsgvglpga-lgh--------dgyfsclqlkhe--dpprmptkgnlsl
alhagtikariskahaaymacikkyspvhggfvler-krgstrfytvtlt
ishvggknsgekadafyarseqdgnqakslaetkdhagpafklgdgwnkv
tlrcgld-rtiekcdykpikvpkggvkttpsdvghgkqacvdklsavcer
mld-wakdkvqvraaaandkaacenklqykiqqtrgrfkfpidrdanass
keanleivlpsgqgaqegrqqetvrkvkkdylykelgsripyvrqgqvpt
cekaqpfeenlnvldgglltfifledsklsilpdewgklaakklaal---
--nqm--dg------flafhlrlhllekagnapgnlnvtgt-arhvahkl
t------gnsqdragladigk-p-epgcpvyekg--vgia-tfvks----
---tkaayrkgvfggilesfaa---lgfhqgqvqqp
>H
rcpirstvkvggasfsspsdityfvlaarrvcaaalsleccvqygggdig
dytthvflysa-lga--------vtyfgtikqckqvgdvvrveailtvdl
qmaawatrggtlkaeqsfvncvkklaavhat-nsdsqtraamffyyeeva
vdyvgskddtdsgdaseagihkdsnahkaftfsnkkagpayklgevwnkl
vkrcaeg-nnlvgleflgkstrkgselstplevgtgqgggastlgsncea
vedhwittkleprggiga-dgdc-tdvnfeteqidthtnfsrhftsddre
kggtr-lmltagqvtpgnrvqsmv-klkglvlykevgkrphqihppvipy
sladhcfeadiyvvdtpslgftyvenvdlmklpmkwalmisksqdnv---
--ariaceg------fllyhlnlhlqedttaylgdkkvshkddlagmakl
e------vegedspgetdkgn-gkeqasgayagq--qsaa-ifvik----
---qqlhyrgngfntilervvp---vgfvrakdqvk
>B
kclplktlpvq-ggwtgfngsalwllkyritcggalagnsptallghhak
hftpqitldrh-igh--------isyfpslgnngdvgtvytlytifdrak
hfdiavykikpmkl-----tcikedtavhyd-ntdt-krgtgrwffqsla
senggsgepatsghaiyigrqkskkgelsfvesashhnpqkpyvsg---a
iyrrgqg-grydegeirglnp------tvakkt---mnvpavtsgaecql
ilv-wakaklwsagdsg--kmkcslgaelpfhhadih-------------
-gedtpllha-kdeikndrvsqnifkvpnhfmfkagvistqyfkyvgidy
cvkkanfsgndrl-gsgtlkypfkagpevkqmpkawefrvcskdqpm---
--wrfssveklgttlflvlknskqilkyldvpatqkaalknkkenqslnl
dalvgltsknkdnvtitdpshadkdpganpyvqdpslpmspafdap----
---atlgycvclqepavgvpesrgglpdeyggvsvl
>C
qflgvktldvt-kayvnekkvtfwilvfravcggplslgcpcnllndein
kfstyaklegd-ggh--------anfipelvqegdinqifklknvlnlth
qfvlntfrimslkq-----gcvknqakmryk-etat-kshfekffsqald
teypgpresadaghpyyincqmkkkqhiiytksaktappkial-qs----
--acahl-ptadkkdftdasskkggktpppsgpdagltlpvcvpkeecpl
lpk-wvkaplkttgepag-kaqcppemgfnthhtqchyqfgskcvveaat
ttftlylins-ksgageqriihvvlkyercfrlrvafvgdnslpmasvgy
cfvsknfrgnall-gpgeltytlapvtsiknmakswdlaslrddnsm---
--nlvlgtekledalyecfhirrhltvyqdilhgsvavmqderlgsackn
a------gdtvnlmyqsqpahcendtasdafkga--lsasngypep----
---asthykepykfaaicmandrcgvnlaykevaae
>G
hcperrtspegsypysspkgvtlflavlrrlcsevlglehcvqfagsnte
dfekrvmlitg-lghhkaqnyldnrffanvhkaaqvadvfkinsiltvtm
pmaarpvkgrslmgkhhflacikkhaklhag-ngaaqpkgstefynkhsg
vqclgstghdpktdaayagllkeaddsneftfphkpagptfkvhqgwnyl
akrcgev-envhrnkllqlkkqkrgaqntplqegaglhlgandlgsnceg
vie-wfstkldakalige-kgtchdnvdyiieqtaghtsgnrdgasdtrk
rggevflvltagqalpddiiqamv-kvkgaflyqdagkknryytqvvipy
clkahcydgeinilgqkslffthlkqaglrklpkswvlmtasg--tv---
--aregcaa------fllahlklheedeattylgskkvshdqefakgasl
q------gdgeamvgecnrgd-gkepadaafage--qaka-pfcik----
---dvgsyrgngfgdilevfgp---lafvrgriqvk
>D
vlldvlilnvl-sgytdaklttlwllifrtmssaplelecacellaeein
kytvtiklesh-pph--------tnfvpsvinesqinkiyrlkpvislak
efvlasyktlslrt-----ncvnpqakmkyk-agdn-kynfekffsqevn
tdylairdaeetdqpttvsrqmknnqeivatqsagstgagidl-ps----
--agghtygslekndltafdaakggkdpppkknhtgsllavsiskeecem
ltk-wadakfpasgvadg-kaeckglpefnyqpfhchfffasncptepps
kavelyllae-rggageeslkqvllrfrrcfnfrtgyvsdqslpcagicy
cfksttfrgggll-gpgvfkeladggqavkkmanawdhpsqrhs------
--nnvigtisggnlllecfhfrkhlgayldilhgneavqkdqklgwtckn
a------ghtvniayhtypahsnkdaasnsfqga--erpassylep----
---asmgyrecymgasiyesgercgvtvdyaqaeae
>node6
qflgvkilnvg-ngytdqkmvtlwllvfrkvcggplslncpcellgdein
kfstrvklegd-lgh--------tnfipelvnegdvnkiyklksvmnlak
qfvlasfkimslka-----dcvkdqakmkyk-eset-kknfekffsqevn
teylgardaaetgqpyytnrqmkknqhivftesakttppsidl-ps----
--acghp-gsmekndltgysakkggktpppkkdntgmvlpvciskeecel
lpd-wanaklktsgaavg-kaeckggpdfnfhhthchfsfgsncvveaps
katelyllge-rggggeerlkqvvlkfrrcfrfragyvndhslpsasisy
cfksenfrgngll-gpgeltytlaggqaikkmakswdlpsqrndqsm---
--nnilgtgkledtllecfhmrkhltayldilhgsmavlkdqrlgstckn
a------ghtvnmmyqtqpahsnkdaasnsykaa--lrpavsypep----
---asmnykecymgaaicisgercgvkldyaevevq
>node15
rcsaknsltvg-ggytsqsavtffllvhrkvcsgalaldcciqlagneke
dfssrvalene-lgh--------vsyvpplvnnedvgkvyrlktileltm
qlaaavvktktlkahrkflscvkrhaklhyt-ssnn-krgtkkfyaqevg
ieyigsknddesgdpfyagvqqdsndesgfgistkqappnfdlgegwktl
lvrcghg-anmqkeelaglkvrkggerpvpkeagtgmhlaavmlgaecah
via-wakiklstsadtgg-kaackggvdynfhqpqchfnfgieevgtapn
katelflvleeqegapeerlekmvlrirkcfmfkqsavkthylnntsvvy
chknqsfsgnekl-sggsltfplvenepikkmptewhlpnarnddsv---
--nriggtgklqinvfivyqlrnhlttlitvtkgdmavlksdnlsisckl
a------gegqdmvgeaqpthtskdpgskpykns--lsvtasfara----
---prvgyrksymggvleifedkcglgldygqvevk
>node10
rcsperclnvg-gdyneqddvsfflvalrkvcsgdl--ncclqyggkeke
vyttsvslpst-lgh--------vgffssllkkqe--dpprlptkvdltl
emhgstvkarimkahagyltcvkrhasvhgdfiaen-krgttsfysvslt
ishiggkredekadafyagsqqdanqaknfaiskkhagpafdlgegwnkv
alrcgqe-qtvnkadfkplkvpkggakstpneighgkqagaaklgavcer
mld-waknkldaraktegnkgacenkleykiqqtagrfkfpidkngdapt
kgsnlyvvltagqgapdgrkqemvskikkdylykelgkkltyithghvpf
cqkqqpfeedlnvlnggvltftfledseltrlpddwgklnakkldal---
--drmggng------flafhlrlhlqeqettakgdlnvtqs-nkritrsl
t------geehdsiglaeigk-gkepgnkvyqkg--lsia-afvkt----
---akvgyrkgvfggvlesfsp---lgfhqgqvqak
>F
rcgleycinvp-gdyneqddlafflvalrrccdndl--hcclpyggkeka
pystaaslpgt-lgh--------vgyfggllkkqe--sppslparvdltk
tmhgstvsasimkatagyltvvkrqasahgdfitqd-khgtqkfyscslt
ishiggiaaderidafyaakqhdssqakifaitkkhngpgfnlvegwnkv
amrcghe-qtvgktdfkelrvlkggakagpnekghgkksgsarlgavinr
mle-wdkshldarakiegkkdgceskldykiqqgagrfrfpydkngdaat
kgsda--ilnaaqaapdgrkqammpkikkdylykelgkkmtnlvcghvpf
cskvqpfeedmiilsggvvtftflqpseltflrddwekvhqnkldal---
--srsggdg------flpfdlqlnlqelenttmgdlhtvqt-nlkmerpl
t------gnsqdgagnvqfgk-gpspgniiyqkg--lste-afvrt----
---kkvdyrkdvfgsvlisfsl---lgfhegqveak
>node14
rcspkralnvg-geyssqsditffllvlrkvcsgalsldcciqfagndke
dyashvslpta-lgh--------vsyfptlvkkqevgnvyrlntileltl
qmaasvvkarslkadrsflscvkrhakvhan-nsns-krgttkfyaqsva
ieyigsknedekgdafyagvqqdansekdfgistkqagpafdlgegwnkv
llrcghg-qnvqknefkglkvrkggerstpnevgtglhagatmlgaecer
via-wakskldaragtsg-kgackdsvdyniqqtdghfnfpidkagkapt
kgselylvltaaqgvpddrlqkmvakikksflykqagkkthyfthvhvpy
cqknqsfsdelnvldggtlsftyiedsalkklptdwhlqesksqdav---
--nriggdg------flayhlrlhlqeettatkgdmkvsqsdnmsiassl
q------gegqdmigeaekgh-gkepgskayvne--lsia-tfvkt----
---qrvgyrksafggvlevfgp---lgfrhgqvqvk
>node7
rclgmnmltvg-ggytsqsavtlwlliyrkvcsgplsldcpigllgdekn
efsarvalene-lgh--------isyvpdlvndgdvgkiyklntvldlak
hfttatykikslka-----ncikdqakmhyk-nset-kkgtekfynqeva
teylggknagesgqpfyasrqenknqeitfgesaketspavdlvegwksp
lyrcgqg-gnmekdditglqvkkggkkpvpkktgtgmhlpaviagaecql
ita-wakaklstsgdtgg-kaeckggvdinfhhaqchfefgtnpvgsaps
katelylihe-rsgggeerlkkvilkirkcfmfkagavkthylpstsiay
ciknenfsgnekl-gpgsltyplvggqavkkmpkawnlpaarndesm---
--nriggtgklqtslfivfhmrkhlttfidvsqgdmavlknqklgasckl
a------gntqnmvaetqpthtkkdpgsnpfkns--lrvaasfanp----
---atvgykkcymgavigiseercgvgldygqvevq
>node13
rcpikrtvkvggapysspsdvtffllvlrrvcsaalaleccvqfaggdte
dyathvmlfta-lgh--------vsyfasinkcsqvgdvyrlnsiltvtl
qmaawavqgrtlkgehsflscikkhakvhag-nsasqtrgsskfytedva
veyigssdddnkgdaayagvqkdtddnkefdfsdkragptfklgegwnkl
akrcgqg-qnvnrntflglktrkggelntplevgtglhggatdlgsncea
vid-wittkldaragigg-kgtckdnidyniqqtdghtnfprdtasdtrt
kggtvflvltagqavpddrlqsmv-klkgtflykeagkkthyftqvvvpy
clknhcfdgeinvldaaslgftyveqsdlkklptnwalmdsksqdsv---
--grigceg------fllyhlklhleeeataylgdkkvshkddmatgakl
e------gegedmvgesdkgh-gkepgsaayage--qsaa-ifvik----
---qqvnyrgngfgsilevfgp---lafirgqvqvr
>A
nclpmdilsvq-kgwaaqsgtalwllkyrvicggglsiegptgllghhqe
hfaariqldlkgiar--------itfspnlskngdigviytlyetfefpk
qfdkaaykiksldk-----pcfkthtgmeyd-ctks-kraigkwffrala
tdylgskdpgerghcfyagkqeagngelsftvctesnkpqlqfvegwmhs
iyrrgag-gdydkgsvgglqadnvktkdiskkt---vglpglsagaqcql
ilg-wgrcklikyneage-rddcklgsnlaftaagch-------------
-qtepqllhe-kqsagnghitksivqlrkcfmfkaavvsdqyfpataiey
cvkkdtfagndkl-gagsrtypmstgysvkqmpkawnltvcesdnplala
irwriggvgklasslyilfrnrdqlstflpvanaakavldnhkegpsskv
d------gktlksvseteeshskdeaaakpfkrnpqlpvcpcfepvmrec
mlkttlgyakclknplvaipaeraaiannyggvsvv
