>C
ttgaspkdqgsipkssafthmlsyyaivshkfahsggevpiytlaq----
-gigdak-lrfakstalvgkfaleslgppttfpckvvkeklydrcfgevy
hnaphsafdt--glggykkcpkslfcavaenglqtfratahqq-iaspgy
felevitkkellfklhlsnllikgvlgcafspyveahlvekdtmecflhg
cgqlgvtyrkvgesftfkinpsqtgaffecldkawgcietcvik------
-sed---yeqfhaghftgtafvsavgllnlwhvqtnfllch---arapdi
qflq---gkvgtvdgtgdktkysllq---lacaylvwlhslvdcgkatsk
vplffifdnpsslnanatkegpdkakt--iasenkrrggdshgngtgpvl
yctilktvqqgqqfvrwrvsehsptqcatpkqlpd-vgipvedakv---a
glestakggcfevfike-nigdceeifhcctlgiqdvpkdlvvkifhkyl
eahhvhemldkhnsvghndkasracyivcngkrpgfkheftpqtinsk
>node13
dygpvkkkedtvnrspkldamlkfyakaldrfqkeknkvasmclveakrr
rgipkpakvdfartgahvsrfndekfpapsqapcnvirmalydkph----
qhtmfegiegacsmtqfg--phtaynnvsalplpafmfnkapksrpekqy
ys-gpfikhcpplkfslrr---rgyiaggvnpyvqslllmkgsmgpvahs
cgkssnacakkggevlfdgcqteallnpvrkragwpylphcgra------
-akk---fhtfhvghqshkhtesrlaltnyfahastsqsyqeimfsgagi
vyieyfkvd------kddpqsvap-k---lsaefdlwvqg-----lefks
felfflflgp-----dqktqkhgsghe--tekccpplagaktp-gdlp--
ickaikgidhtdnyspwkn-----d------tksp-maaavasgik---i
nllgtlrgvryktlvvshlkkncdevyhccmlgtkieaphivv-------
hfhdvytndhipggmehddkldiccyff--tdrrgflyglnkpglakg
>H
dygsvtkkddavnrspkyisglpry-kaldrfqtqkdkatsmclvaakpr
rgipkpaktnfarnvsqvcrfndekypmpkqakcsvtrmvpyrkps----
retmfegikavckktqfa--sntlyntmselplpafmldqgskpqseksf
ym-gpfikhcpplrfmakr---lqwvaggvdpyrqglflvdes-----es
cgkgtaacvkkagevlfhgtptdtllnserknegwpylthcgstvdnryr
vrkt---fvkyhvghhsrkndnsrhlltnyvvhgatarsyheimekgpgi
vyfdyfsvh------desdqsaas-n---lneefdlwvrl-----feyks
felffvilgd-----nqkvqeqvaghe--aekccpplsgasip-gdlp--
vckavkgtdh---yppwkn-----e------tkgp-masavhsgak---i
lvlgtlrdikyktlilshlksssdevyhccvlgakieaphlvv-------
ifhevytgdhgpgvmqddnkldiccyff--nhrrgflhglkkpnftkg
>node3
dagevpdkqnsvtksqsfgamveyfaspkhpfgnnksgvvaycyae----
-diarss-lgfvegaagiqqftrevlhppprngckavkgklykkcfvplf
ghgdtdgiek--gllayencpkqvyrnvaknplgtfkfikeppgianvty
fradsfkrkclllkyhlrrllqmkavdccaspfvrghllerptmgpilag
csdmnskcpkeggglsfqgilteaatsfacktvgwqclhrcskn------
-tdd---fqlfhsskgtqthtagtasitrfwpvqtsfslch---sssgdl
qfme---thggtlletqtpvnaav-r---lvstyqiwghavadcqkpdtq
palmfifqsgttvdgkvkdgapdkgsaglvpkgcrgregvsqpasnpp--
yckalrgvqhqqdfmgwrgpaepanqcagpgelpr-vgvgtaggsv---t
gldftvkggcykgianelsikacdvyfrcckfgvpqigkilillrfkeki
dghdfldlygahgnvanddkfchgcfif--gkppgymhsfkasaltng
>node14
dygpvrndqdtvnkspkfgamlefyakalnrfeddkdkiekvclve----
-gipkppkvnfasteahvcrfatekfpapsaspcntvrgalydkpv----
ahnqfegfeggcsmtdlekcpangynsvtslplstfkfnknpksrpgdty
ysasvlerkcmplklqlkr---raviggglnpyiqshllmkanmgpvlhs
cghssnscakkggdvkfdgrptdallrftrkrdgwrclpqcara------
-adk---fhtfhvghqsqahtagklaltdyfalettyqicqermfgaagi
vyldyfkvt------kqdpqneal-k---lasefdlwahg-----layke
ldlffvflgptgkdgqrksqrhssgnp--tskacpalggvntp-gdlp--
fckalrgidhadnfspwkg-----dqasgakdkps-mdaavvngim---v
nlqttargscykslignqflkhceavyhccklgsqhitehivl-------
hihevysnshvpggmepdekfnigcyff--tnhrgflyglnsaglnkg
>node7
dagevpdkqnsipkspafgamleyfakavhrfanekpdveayclae----
-gipkss-lgfvdgaaeisrfareilsppskspckvvrgklydkcfiavy
ghnqidgfet--altayekcpkqvyrsvtknplaafkftkepqgiaspty
fsldvftrkclllklhlrrllamkvigcgfspyvpghlldkesmepilhg
csdmdvscpkeggglkfkgipteagvhfackntgwaclnrcskn------
-sed---fqtfhsghesqthtagtlsltdfwnvqtsfglch---fspadl
qfle---nkggtlletqdpaneal-q---lastyqvwahavadcqkpntq
adlffifhfpttidgniktegpgkgna--vakackgrggvnepagnpp--
yckalrgvqhgqdfmnwrgpaespaqcagpnempq-vgaavangtv---s
gldatvkggcykvfvnelsikecevifhccklgvqhiakhlilkrfknyi
dgheilemigvhgnvghddkfcrgcyif--gkrpgfkhsftasglnkg
>F
--gplresqtaqrstpssgvlldmvpkglngfekdaakvskaclvg----
-gapqppkivfrstdqhvcrftnekfalarptpcntvkgkvlkkqi----
sldgednfasachmtdlmk-ptkgypevmslalttrafngspkartgghy
ynagiidrkcvpikiqmks---rnvvgsglshyiephclarvn-------
cgkcsktcpyqgggasfdghptsalirftqkkiswrcqphcvrs------
-gss---mhsfrapdfetsihegggglsaffavhstyqmcdkrefgaagv
hylaffkis------rekpqyspl-n---lggkyilsnha-----lsyks
ldlfhvfqvytgaggeksaqwhgdagh--tsktcpgmtgmdkt-gdma--
ysrslpsiirasqfskwqs-----eqatnqsdgpp-lqaalvasi-----
---gknrgacykglikqefhkhcdsvfkvcklssqppiesivl-------
ashnmnsndfspaalqkdeafnsvcvgy--lghkeyiyglkstalfkt
>B
-padvpgkqkgltmgksfgamvaffssprhvfgnnkgglvgyccpn----
-digtks-lgfitvlagtqqftpialhppprhgckgvkqklykkcfiplv
gsglndgvdk--slpgyhacskmgykavaknplgkfkfiktppgvatvty
fradafsrkcialiyplvrllqmkaanccaapflrsrlldaptmgpivsq
csdkdtecptyg---syqgilketatsfnckavewqclrrcakn------
-tde---fqlyhtkkstgthtsgssnttrfwpgqtpfsvcl---tesgdl
qfma---thgvsllgtqtpteaai-a---lvttydiwghqegecqkpdad
pslmfvfqsdttvdgtlkggakeesngglvpkevqgreggsqppsqpp--
kcsilrgllhhqdfmgwraatgsaddcagpgelpr-vgeghaggsv---t
elnaevrgacykgtayelgiktcqvfyrcckfgvpqlgkilglrrfklni
dgqefldlygshgavandykfchesfif--anp----tsskgsnltnv
>node6
atgpaskdqnsipkspafshmlsyfaiishrfaneegdvpiytlae----
-gipksk-lkfakgtahagrfareilspptkspckvvkeklydrcfievy
dhnqnsafet--altgykkcpkkvycsvadngldtfkssthpqsiaspty
fslevftkknlllklhlryllatpvlgcgfspyveahlvdkdsmesflhg
cgqldvtcrkvgeslsfkgdpteagdqfectntgwgcidrcrin------
-sea---fetfhsghvththyvgtlgllgfwhvqtsfglch---taspdi
qflq---dkggtvvqtedqtkysl-q---lastyqvwmhaildcekattk
nhlffifhnpttingnqtkegpdkakt--iasecksrggvnqgagnpp--
yckslravqhgqqfvrwrdpahspaqcagpkelpd-vgvpvanakv---g
glegtvkggcysvfvneatvpdcevifhcctlgiqdipkalvlkrfhnyi
eahqilemlavhgqvghndktsrgcyiv--gkrpgfkhslsaaglnkg
>E
dygpfrndqnvqrvtpkgqvllneyakalggyekdngkvqmndhme----
-g--------fapsaqhvcrlsggkfpakrgtpcdtvkervlnrpv----
avdqqdnpasgghttvlmk-ptegypevmslplttrvfntnpksrrgadl
ytarlffrkcmplkfagtr---dnaigaglrlfiephlkavmd-------
cgrcskscayrgggvsfdgrpsgamerytqlrqgwrclpqcart------
-sdk---lytfqtphlgeepheggggmsnfyakhrtfsvchkrranaagi
hyvdyfmvn------rqspqkqnl-k---lgsqfdlwshp-----lgfks
qdlfhviamfaggeghkdrsrvgsanp--slkastnlngvdta-gdya--
ftksmepea-negfskwhe-----eqaegqndrhp-leiglisdhfkaca
nsqgaarspcymglanqnylstcesvyncckmgtahsnqamvl-------
pfhdvarnsftedtvvkdenfnpacygf--lgnseflygvwstglfks
>node15
dagevpddqdsiakspdfgamldyyakalhrfendkpdiesiclve----
-giptsk-lgfadgaaevcrfateissapsnspcnvvrgalydkcf----
ghnqfegfet--altdldkcprqgynsvtgkplatfkfnkepnsipapty
fnaavykrkclalklhlkrllakkvigsgfspyiqghllkkasmepilhg
cselnvscpkeggdlkfkgiptealvrftskhqgwrclnqcpra------
-add---fhtfhvghqsqahtagklsltdfwplettfglcqntmfgtadi
qfldyakvkgatlvekqdpeneal-k---lasqyqlwahg-----layke
adlffifhgptgkdgnikteppgkgnp--takacpgsggvnepagnlp--
yckalrgvqqsddfmhwkgpasapeqcsgandmps-mdaavangim---s
nldntarggcyksfsdrqfirhcdviyhccklgvqhiakhlvl-------
hvhevynatsvvggmgpeqkfiigcyif--sdhrgfkysisgsglnkg
>A
dagecpekqepvtrsesfgvlveyyashkhpfgndkssvqpycyaq----
-eiahst-lgfvegkegfqaftrdvlppppitgcmvvkgklskkfffplf
ghgqadgidk--gvlayekppkqiyrptaknplatfkfvkespgkdnvsy
gshnsfkrdcllpklhlsrllnmkvvdccgppfvrghtserqnlgplles
csdlhsscpkdggglyyqdvyidastafacksigweclhrcskd------
-tta---gqlshaskgtqphskgqasitrfwpvrtifslsh---gtsgdl
plve---ahgatllstqtptdgav-a---lvctyrtwdeavvecqnsemq
aalmfifpsgttvevkiqdgvadkgsdkllpkgcrgregvtqmasnga--
ypkalrgvqrldgfmgwrgpaepasecacngeapr-vgvgtpggtv---t
elafvvkegsyraitseirikscdmffrcckflvpqlgmtlqllrfkqkt
dgkdflelyaaqghvsndkkfchgcavf--vkppgyvhtfkagalakp
>G
mygpikrkeelrhrgpklgfmlkfygkannrfqkknkkvasmclvevkrr
rgtpkpaavdfarasanvsrfkdkkfpgpnqapcivgrmaltddrh----
eqtmfeglegacsmaqfg--pnttynkvaalplpafmfskspksrpakef
fs-gpfikqcrplkfsrnr---rgfipagvspyvrslllmkgsmgaadqs
cgknsnvcakkggevvfdvceteallnptrksagwpylhhcgra------
-aklevefhsfqvghpngkhtdghsnltiyyahanksqayqeckfsgagv
tcieyfkve------annlkdvaq-kisylseefdiwvkg-----iefks
felfflflgp-----sqktvkdgsgne--terccaplggkksp-gdlf--
lcegikgvnhtsdysgweh-----s------aesp-magaiaslts---i
nvlgtfqgiryntlvvshlkkgcdevyhcgllgtkveaatitl-------
nfhdvyanvhipggmehddkadivlyff--tdrriylyqlnkpglskg
>D
atdqagrgqksvpkapgfhltlcyyavlshrfanqdgecpaytlan----
-gtaksr-vkfskgnahggrftrevlspkaktvckgvkdklydecfidvy
qhlkdstfet--sltnyktcpkkiycpiapdgidvfmrctyphtlacpvy
fslqvltkqnallelylryllpatvlgcgfaayvethlvnknskesflsg
cgelpltcrkvgqsvnftgdpketgeqlqctntgwacldkclvn------
-sea---leelhagqsththyvgklgmlafwqvqtgmvlcn---asspdh
qflq---ekgssevanedqtkynl-s---ltstyaiwmhsimdcekitvk
qhlfflyhqpitvnggqtkdgperakt--vaaepksg----------p--
yykafypvqnanqsvkwreqvhspnecvgpkegpnsvgapvasarv---g
slqgtvkgacyqmflaegatpdchvifhccslgiqsnpnalvllrfhlfi
ephqllamlaihgqvshedkasrgcyqr--glrpeirhnltdgglnkg
>node10
eygpvrddqtaqrtspkggvlldmypkalnsyekdkakvhkaclie----
-gtpqppkivfasteqhvcrfstekfpaarptpcntvkgrvldkpv----
ahdqqdnfasgchmtdlmk-ptdgypevmslplttrkfngnpksrtgghy
ysapilnrkcmplrfqakr---rsviggglspyiqphllarad-------
cgrcskscayqgggvsfdgrptsalirftqkrdswrclphcvra------
-gdk---mhtfhvphlnkaiheggggltdffalhatyqichkrrfgaagi
hyldyfkis------rqdpqneal-k---lgaqfdlwnha-----lsyks
ldlfhvfamftgtdghrdsqrhgsggp--tskacpalggvdta-gdlp--
fckslrsiehaenfskwhg-----eqatgqkdrpp-mevalvagim---a
hvqgtargacykglikqqflkhcesvyhccklgsqhanesivl-------
pfhdvgsnsftpeamekdekfntacygf--lghreflyglkstglfkg
