>A
emskqtpdkahcvgkgqlktrpla---sgadaalqhtkvdeaevtdew-p
ipyplnlhvdattdglyviglevgmkvpsvdgskiagpqat-dgappetg
idvsttsvsryshkvarysalsglnadcwpkggvehtkkspieyykivvf
eik-cthgsescqppervvaaednvmghnlvkdmsifelwqledykldss
hfkgnfgrglhkdmktkek---qqvpiaagsdqmkysaesymlcylas--
lmsgrcen------eplaqpgyskrvmtgrvcsgvkaaskikvsnssraq
lekavlatv--------rtttse---adfs----dfleeearyq-tissg
-relhralvsskfnvdvadnaqynglkllgtmvdafgpsvykgk--sc-a
kvgspigmrkaaqvcidaldnakrnpiv----yqlagqalsfqivvgyyd
qalepcaasqpyrlgnqflknpawpk--kkywdnwtlksrcdcttck--c
piskstdskn----edtsdanmsyrkegfcang-v-----ggvcmggnia
kaegvnerca
>node7
klekpppemsqc---relrtrtqt---seseaslhqsevdtdtvnddk-s
krykiplniqlasaglvvieltvdikappvdgsqvaqrqvt-dgvpaekg
lsvpvttpsffrhkvrrystletlssdcwpkgayghskkckeeyyritgf
vik-vtylretcaptenpdpqddnasghnlfknmayvelwrlndyglqcs
hlhgefgpglhpqmknkkk---gqnsiqapsgqvdlssedylicfltikt
dlaswrig------spmdnpvygkqvitgkfcvesiskgklkvpscvgqq
lgknplagv--------tsttae------a----ggladdahyq-tkkfl
-rqlhqdlgasrfqvevtdsaiyeglklsgavvagwaegayksn--sc-a
avsaeigmrkaeqvavneldaarrssav----yslaevslsfqyvlayyg
rtlctcsvaqsyilkhiflkikawsr--qrywktythksryecadck--c
pidvstdvmk----sntsqaavckrtdffadah-i-----gkysvgrdla
ktegvttgct
>G
kldgpplglqsc---rqlrharae---cstdaqincgdaktekfndak-s
qrnrlklrvqlaav-lvgvgllvgvrevvlgpgqkphkrvg-nlvni-aa
lgvaetssaffkhrylkisqlevigcdcwrdapfkratvcmnnfyrlgnf
ils-vpflqgaciptqgamnasdpqashhtsiesgytdlytkhsygmdve
afggkfgaganplqtsqrr---gagdlhliceqarmeeggffvttlvlkt
iagmwrlg------apldnvlcarevpssnscvavtrtsknfvgrdrkvk
avsatggsv--------egppae------ttqartplaqhatld-prygl
skaykndlklgrydhdstqkltyaeikptgevpgdfagaalhaqgqsc-a
ykgsfrghqtveptneehlgkdlrcyen----ykfirgtltfiyalsfya
rsscagglveagidthgylkehvwnk--ikfwpseshanlfgcslcr--c
pchvtgdvik----shgskgtstgkfayfkskd-t-----crkglgwell
kldrntpacs
>node15
kldwppqemdac---revhhrtrt---sesdaglhhddvdtdkfnenk-k
hryhiplriqlasa-lvvvellvevktppvgpgqvarrqid-daapaetg
lavagtttsffkhkviryssletvssdcwvkgaygnstscmeeyyrltgf
iik-atylrgtcaptqgaspqddnqngqdlfidmayvelwrlhdyglscs
hlhgnfgpgmhaqmkhkkk---gqgslellcgqvrlsaedflvcfltvkt
dlaswrig------spidspmvpkqvakgafcvasasigklkipscagqe
lgpnplggv--------tnapae------v----gsladdahfc-trtll
-kqihqdleasrfqievtddatyrgtkltgdvvsdwadgaykst--ac-a
yrsaemglrkaepkaqdelagdhrgskv----yslvevnlgfqfvlnfya
rtlctcsvaesyllkhiflkiqawsr--qrywkkkshkelyncadck--c
paevstdvvk----tnipraavtantdffadad-g-----skvglgrela
ttegvttsct
>node10
klnspadglnsc---relqhgire---cdgdpgleagevssakfhrts-k
hrfkfslraqsatt-lvvvellvsvkesvvgpgqvprrqvq-hdagg-lg
lvlagvtkyffkskfvrypcldvvlcscwvdgaypkatscmsdyyrvsdf
iin-aaslhsecaptqgpsntnddhnnqefalqmayvdlyklhqyklkce
viggdfvpgmhammatqav---kagslkltckqqrltaedfficilrfmt
slgmwrla------dpvdyplmaketaaganclgdrkvgralipnspgev
lgpkpvgvp--------pkappe------vngsqgqlaqqanfq-kklil
-keakqdlkigrfdietadkatfqviklneevasdrccgvyqka--acea
ykndymgerkagpksqealvtelhhthf----hdmvhshlgfhfnlefqv
rvhctcgmeegarvkhvylnsqewsp--lrywlaqcpgnlfacseck--y
pahvqahavn----nhvpkraigsdveffnqkn-trvcsksrvglareiv
tleglt-ast
>node13
kldspplglesc---rqlrhgkke---cgsdpqincgdvkserfndtk-k
hrnqlklrvelaat-lvvvgllvtvretvlgpgqvprrqve-hlvst-as
favagtnsaffkhkyvkysslevvgcdcwtdgpykkntvcmadffrlgnf
ilt-apylqgdcipthgalnandaqagqnssiesnytdlyiahnyglncn
afggkfgpgvnplmaskkk---gagelhltceqarldagdffvcilvfkt
taalwrlg------apvdsplsakevtksascvaptsvgknfvardrnvi
avpkpvgev--------tnkpae------ttqartplaqhanfs-trmgv
-keynndlkmgrfdhdsadkltyqdikptsnvpsdwcggvyhaa--sc-a
ykgayrghqkvepaaeeqlgkdlrcsqt----yklvrlnlsfqfalnfya
rsscacglvqggitkhvylreqvwak--lrfwksenhadlfgcseck--c
phhvagdivk----tnvpkgvittkfsyfisqd-a-----arsglgwelv
tvdratpact
>C
qntktptdvsnc---halkkrtkatngsgasgfleqkemdtkalsdli-s
kaysmtlnirlyslgltviklkvslktapletkdatrrnle-aevtsrkk
qsapikssnfscykvrryarldallsacwpkggyaektnckenfyrysgf
vas-mtfateistgsqavdvrkntapgqymgmahvgldtwrrtgcgiqct
cvsmeistglhneflgrkr---vnngieapvggqdlgsegyqicfltinl
dlgpwseg------spefdpvygkqasksslcvaplsstkidvptcvgvk
lakqqlpakglvldhwktggrae------p----agidendqye-tkslt
-gkvhqallgnrfaqavkrhglyegassagpivagweeqayasl--tc-a
avganimirsaenvktvdldalwrrvda----ytlaelsldfefplsqyg
ralcvcfvalkgflrhlwlvfgswsm--dryrkayidrsqyacsscippc
ppdvateagk----asislsvickrqsyfhvdh-i-----gkytvgrdls
kdeaftisct
>node3
kmdkptpdkshcrtkvelktrtla---sdsqaslqeskvdaatvseda-p
ipyrielnisvktaglvvvelavqikippvdgsdvagsqvt-dgappekg
isvtttspsrfrhkvarysalaglnadcwpkgayghskksreeyyriigf
aik-ctylrascappekpdapddnasghnlfknmaffelwrlndyslecs
hfhgefgpglhkqmkdkqn---aqnsirahsdqeklsgddyllcyles--
alasrceg------splkqpvyakqvitgkfcsgvraaaklkvpscggqq
lgknplasv--------atatae---adfg----daiadeahyq-tinvg
-kelhqdlgasrfhvevsdnavydglklvgtmvngfgpgaykgn--sc-a
kvgsilgmrkaaqiavdkldsakrngav----yslaeaalsfqyvlayyg
qtlcpcstqqpyrlkhqflknpawpr--krywktwtlksryecstck--c
pieratdskk----edtsqgemcnrtdgfathh-i-----gkvcmgvsla
ktegvnskcn
>D
qatkpstdtsqc---qelqskinatnnagasgfvdrdevddktfkdnn-a
krykssfsisktspdlvlfevivsleigalngsrntrrnltsegipgekg
lsgpippepfscykirmyrspdnllsvcwpkglfehsvkckqnyyritgf
vak-itftiascpgaqgpetqnatpgghyagknlakietwrlndytshcn
hlnaqfaatlyeemlgrkkleyhkesvqsphaavdlgsddyqicylpikl
dldafshaqvgdvagpafdplyfkevsttalcvstiprdkietpncvgpk
laktglpakgdilanwktaatge------s----dgadeddai-----lv
-pqlhqrrlgsrfshyvkrstlynslsvrgpmvpgwdqqayksf--tt-a
gasasimmrkeekvatceasplwkridvgaleytqaevsldvqyvvahyn
kalctcgvnmkasqrhlwlifkawdraserkrdshahsiryfcpncivpc
kkdpatdvvk----tgkgqaavskrksyfpvgt-i-----gkycigrafa
keeatatgct
>node6
qatkpptdvsqc---qelksrtkatnasgasgfleqnevdtktindne-s
kkyktslnirlaslglvvieltvslkaaplngsdatrrnlt-egvpgdkd
lsgpvptesfscykvrrypsldallsscwpkgayahstkckenyyrisgf
vak-vtfaidtcassqgpevqnnsasghymgknlakietwrlndygiqcs
hlngefaaglhnemlgrkk---hnnsiqapngavdlgsedyqicyltikl
dlapwsia------sptydpvygkqvatsalcvapisngkidvpscvghq
laktnlpakglildhwktgatae------s----sgadeddqye-tkkll
-pqlhqgllgsrfahavtrstlydglslkgpmvagwdeqayksl--tc-a
avsasimmrnaekvatseldplwrridv----ytlaevsldfqyvlahyg
ralctcavaqksflrhlwlvfkpwsr--eryrntythksryacanciapc
pidaatdvvk----tnvsqaavckrksyfpvgh-i-----gkytvgrdls
keeavttgct
>E
klttraeginsc---revahgvrq---cdgdsgl-agelgatkfhrtf-k
krskfsiransvst-lfvaellvsvkatksshskmprkqve-heagg-lg
lvlagiskhlfkpkfvrcscvqvvlctcwgdgaypkaascdldyyrvsaf
iid-aaslrsaappttgpfntndnhndqdfvnqinyvniykmhqyglkcv
vaggaiapgmhapmvttac---kaeslrincklrrltaddlfycilrfas
tmamwrlk------dpmkyalgakassksanclddrkvgralipespvev
igpkpigla--------pklppd------adgsngqfaqltalqlrklvl
-eegrrelktgifdievadratfqviklddtvatdrccgeyqky--acda
ykgkymg----gpknleplvsilrftrf----ndgihddlawhytlifqv
pehctcameersklrhvvvnseqwfe--lrywlpgcpghlfacplck--y
ppvvrgqavn----nhvpksgvgsk----------rvcskskvslaqeiv
tlehln-est
>node14
kldsppeglssc---relqhgtrn---cdsdpglnsgevksdrfnetk-k
hrfqlplrvqlatt-lvvvellvsvkesvvgpgqvprrqve-qeapa-ag
lavagtttsffkhkfvryssldvvvcdcwvdgaygkntscmsdyyrlsnf
iik-aaylqgdcapthgasntnddqdgqdssidmayvelyklhdyglncs
vlggnfgpgmhammaskkk---gagtlkltcdqvrltaedffvciltfkt
slamwrlg------apvdsplvpkevatgancvgsrsvgkamipscsgqi
lgpkpvggv--------tnapae------vseargplaqhanfs-trmll
-keytqdlkmgrfdietadkatyqtikptadvasdwcsgvyqsa--ac-a
yksaymgqrkaepkaqealgtdlrisqt----ynmvqvnlgfqfalnfya
rtnctcgmeegaltkhiylrsqgwsk--lrywkgqshgdlfgcseck--c
pahvsadvvk----tnvpkavvttdfeyftnkd-a-----trvglgrelv
tiegvtpact
>H
nlnslplgladc---rqirhekid---cgcdsqigcgdvkserykdkk-k
hskqlklkvelaad-vaigglevtirdavlgpgnaprrive-qlkss-ss
fqvagikaaffkhkyvdysslevvtcdcwvggnynknlvvhadafrldnf
sln-apfatddciptngslnnnsesagegksisaqysdvyithntaldcn
afggkfppgvstwmtwkkh---vagelhltceqgrqdagdfyvcilvfst
taalwrld------apldspfstkdvtkgqsctsptyigktfvardrgai
gvpkpydhv--------tnspgefev---ttqarqpvsqhvkfs-trkgv
-kesknelkmarfehdsadrlsyrkiepttnqpmgwcqgvyhah--nc-g
ykgchrarqkvdplaaeqlgkdlrcsqt----ykvvrlsltfqfvlsfyi
sdgcacglvkgngpkivsvpdqvwak--lrfwpkldrsplfgcpeck--c
prhvagdivrrsafsvvakavfstrfgyfichg-a-----vrsglgwelv
tvvrdappcp
>B
kmdeptdgka-cridtqlrrrtvt---sdsesnlqdskveaatvceqs-p
ipy--qlnvsmknvalllvdlavqfkipptdggdlaesqan-daaspedg
iviittaferfrdktslypglagmnedcwpkggyeiekktrqeyvriigf
svk-cavrrascnprekpdgaddlasghhvfknmgffqlwplndygldcn
niqskfgpllhkemkdkqd---kqdpiraytdqhklsgddhlqcyles--
elptrcpg------kplkcptyakqvvtgkfcsgcrakhrfmvrgcggqp
lakdpfpqi--------atavne---epfg----dtiedeahye-ainvg
-kslnrdagassfpvavsddavceglpmvgtvvngfggggykgn--ic-a
kvdsiqstrksaqfaankldhpmtngna----ssiyavletyqyvlqyyg
qklcqcseqapyrvknqflknpewqk--khynkavvvksrldcvtck--s
pfersadnrk----tdssegekcsrpdafathh-v-----gkvcmavsla
ekegqgskcn
>F
ksedstdglhsc---reftegire---cdgnpglhaadvggdnfhrvsgr
hrfsfllschksas-hvvvelhisckeqvvghglvdkrqvq-levnd-lg
lvlvgetkyffkskflryccfdvllcscwvdgaypiavscmceyyrvsef
lingapslhedcaptqgpsktnddetnqefglemayvelfplnqykfkce
tipaelvpgmhtmkapgav---kagalkltckehrateeeffacylkfmi
slgmwpls------gqvdytlatkqtsagcaclgkrgvgrtllpnaegnv
sgakpvgvq--------pksppe------vngsqgqfahhtkfq-kssil
-gdckqklkiarfqletsesatfqgvkvdeevvadrccgvyqsa--acnt
ykskymgcrragpksletlvtdlhlthf----helvhshldfhfnvslqi
rvvctadmeegargkhvymsgqnwgp--lrywlavcigdlyacddcg--y
sehaaeqavn----shvskraigedvdfferkdn--vcaidpaglereiv
tlqglt-agn
