>D
vpcakhaegahsyvtvisk---------vlytlflsqsvfcacdklkstk
qfpiggdgfhhggadllpkcrdagfkcdkaqfllslfklspiaaklqsnh
pmasigpngqfli-tkndgrvdegea--digkayhgpsdcrhksennrcs
ryhslliksgvvctlaaainipatigqpvyidgtetaplskplwgtggaf
gdttgmlpaigvhdll------vlrsmlscnkmhfcpvr---rvlkggik
ntlkadlpqiavipqlahg----caeafedfqvhlgangnmggev-alek
vtttdlentclhcifgenkgkakeaeyaiefngllevrsgpnfestipsw
-----lgfsalehevtg-achhkvveeihaweglytypgtlygspslldh
hylk---------dgp--yvsdkytgcksapgp---resapak------q
lcrlsvdgsgnterlrearekt--------fallcaye---------iyc
grhdadvflqedfvspn---------vnincder-yakkdncr---pc--
--nstl
>C
lpcakpvdsmtlfetiisk---------ilmalflrlvvacacsklglgk
qfgggddlaryggggmlpkcvdagyrchkalwllgfflleaaadklmseq
acsglgnstnflsdtiennevpeges--qapkyyhgptacrdkeetkvcn
ayhsllmkrglpctddqslrmrevigrplygvgtliaplskplwgtgnal
aeitnmlpgigvpellikkplntlpkwlycnrfhfcpvr---kevrvgie
etlkadlpalavvphlahg----kplaaadfqvqlsphgnineqv-pldk
intseiqsacleclisekqenpydteaalefyglidlryapnyenlvptw
-----lgisalqhentg-gchgkfikgihase-yfsfpaihysvpelhen
hyhk---------dgp--rdaskvanctsapks---rlklkss------h
pcqlevdgsttsprleparhkk--------ihllynfp---------iyc
grldsdvyleanivpknhlskrrlsevgsdceaq-yakndnpa---pc--
--ngiy
>node15
nlatehgsamalflstvekglafma-pivlsyllvriagivvcdkvelgk
rfdgikaftryaggglaptcvnagfrskmlfwmmgyfllppavgrqvqeq
vsaglggggsfvsdtredarvgedda--dvgggyhspgvckdnesgkaca
kyssllvktgrpcasnrgvqtratigeklyvdgedakpldkklwrtsdtl
edatgllpgvnlkpflqtkslkylkkgfycgfkhyvpvkkclkkdkfdld
dalmpkkpalqtepklthg----aglwyvafkavlfskervgdev-plnp
ahvtviehqcsetlingknergyeiapaldlgclvetryspfykaqisgw
-----qgtsavehsrlg-aclgvvikgqfpsn-f---nvskyglclvseh
hytr---------kgk--ksvdraivskgtpkp---kv-aksk------q
mydydenggghkgkltttrtkrdsdfpekfgpllcphn---------syc
ghnspgvylhvnavtmknlskkrlsegnrgfedq-ynkrtaei---gc--
--sniv
>node10
nlaiqhnsivsafnakeemgltyka-pvgakkalvkikkcplvnkvelgk
rfsggktfsatagvglspvcgragfrpkqlywlpayvllapalsknvleq
gasglgngta--sgtkedgrigeddn--gvgggyykpkvarddengegtt
pktawfdnhskayytgagvqakakhalkgymeseagkgvdkklrhrrnsl
ggaagslpgvklksfvqtkrvklpkkvyfcgikhyatvkkclqrdkldlg
dalikkktalstgpkliaa----sglwyvayraivfppqvveqqi-plhd
aqvpsieshcvttlpdggndrgyeltatvrlgcslaarykiyfraklngw
-----qgwsaaidvrlg-tciglvclahflyn-l---nvaktglcmvaek
hysh---------sad--hsidratvslssakn---kv-iksk------q
kfnydcmggthrdkltetrvnrdahnpekfvplivkhqcy-------pyc
gtkvnsiyplkstvamntvaekrlspttrgfegqgstdrteav---dc--
--lkia
>H
nlvteqndviihvlevvakaiawsy-gipmryllvsidgctfrdnvnvdh
lflensvfreteggslntecgkggyrpnepfwkpayfpltpaleklttgq
gsnglskgaefvlsavenrmkgqkdl--avagayhgvslcwdrdeg--cs
nyiswmqyhkvafgppdslqakag-------sggtsngaekkldnkndal
gggqglipavdlkafaqgqrfdfarprffcgfqdeprivkslqrqkenle
qritkpdtikvpsrdlphg----tnqwfvvfkiilfapervqkvi-plhh
eegaaavgecveplpkgasaksgekmpaaklgc--eikyevnftiklkqs
-----qdskevv-vrlq-tclaliiyqtfqsh-l---givklqscamaed
psnrgidiqimgkdgk--hsadkakinfasake---ki-vkrk------h
mfdyedspashydkilrkkgkhkddmaek--------------------c
psstngvyhvisgitaralkkkrerrqersftdqgepkriggmakdnc--
--srvv
>node6
vpcakhangmhlfltvisk---------ilytlflrqtvicaceklelgk
qfeggsdlgryggggllpkcvdagfrcdkalwllgffllsaaasklmseq
aaagvgnngnflsdtiengevgegea--dvgkafhgpsacrdkeetkacs
kyhsllfkrglpctldqslkiratigqpiyvdgtqteplskplwgtgatl
gevtgmlpgigvhellsrrplnvlkkflycgrlhfcpvr---kiakvgid
etlkadlpqiavipqlahg----salayadfqvqlsphgkiadqv-aldk
inttdiesaclhcligekrengyevesalefcgllevryapnyestiptw
-----lgasalqhestg-gchgkvikgihase-yfsfpatqydvpvlheh
hyhk---------dgp--kvadkvagcksapkp---rvnakas------q
lcqldvdgsgnverleparekr--------fhllcsfs---------iyc
grhdsdvylqvnivtmnhlskkrlsevgsdcder-yskkdnar---pc--
--ngvl
>G
nlvtdqddilnhvlhmgsmgfnwsyvpiglrylpvsiggcllrdnidigs
rftenktfth-qggsmeaacgkgghkpneavwkpsyfllipglskkitdq
gtggqgdgasnyirlvenrrrgtkdl--gvansfhtanlcnekeegnsct
qfapwlayhkvafeppngvldkaq-------nagtmkevdrkvkhsreal
ggstsifpavklhafaegqrfpfpkptyfcgfqreptvqkprsrkndhlh
gsvlrlndimpqskdltha----tklwkvifrtvllypevlervt-plhh
thaanvsgdceetfpdgckcraegyspaarlvc--qaeydvyfhtvmkgs
klhysqgtkkvi-adlh-tclalvifgtylsn-l---gvlpeklcvasqa
icek---------ngnlglpadrakvnlgdtkk---kv-akrk------d
lfeyedhgctkgdklvqmqgkkkdqkpek--------------------c
pcdtagvyhviaqvsvkaltkrkkkradkgfkeqketrraggvveqdc--
--fdti
>node14
nlatqhnsvvshfltkvemglayka-pialsyllvringcvlvdkvelgk
rfdggktftataggglaptcgrggfrpkqlywmpayfllppalgkqvveq
gsaglgdgaayvagtkedsrigdddt--gigggyhtpnvckddengtacs
qysawlahhgkaysssngvqakakragklyvdsesgkavdkkirhsrdsl
ggatgilpgvklksfvqnkrlkfpkkafycgfkhyssvkkclqkdkldld
dalmrkktalstgprlthg----tglwyvafrailfspevvehav-plhh
ahvaaiehqcvetlvdggnergyelapaarlgcllearykvyfraklngw
-----qgtkavihvrlg-aclgliiygqflsn-l---nvaktglclvaen
hysk---------kgk--hsadraiislgsakn---kv-iksk------q
myeydenggthrdkltdtrakrdshnpekfapltcshhcs-------pyc
gqnedgiyhlksavtmknlskkrlsssnrgfedqantnrtadv---dc--
--sniv
>node13
nlvteqndivshvlqkvamglawry-pialryllvriggcifrdnvnvgk
rfsenktftntqggglntacgkggyrpnepywkpsyfllipglskqvtaq
gteglgegasfvisvvenrrkgqkdl--aigggyhsanlcnekengnscs
qyanwlayhkvafsppngvqakat-------sagsvkgverkikhsrdal
gggtgiipavklksfaqgqrfkfpkprffcgfqheptvrkslqkkkehlq
etilrkntimssgkdlthg----tnlwtvvfravlfspdviervv-plhh
ahvasvdgqcaealpdggssrahelgpaarlgc--eakydvyfrtklkgs
-----qgtkevi-vklq-tclaliifgtflsh-l---givkiqlcvvted
qcak---------dgk--hsadrakvtlgsake---kv-vkrk------q
mfeyedhgathydkltqkrgkrkdhkpek--------------------c
pastngvyhvisavtvkalskkrirrsdkgfkdqgeqkrtggvaqqdc--
--snvv
>A
vistkraagvnlylstvss---------lhsglllrvtslagcgklglgg
qyncdsglphyiggglqsmrvlggyaakklvwlagylllatgegklsheq
lsdgvkhgkpllsdckekgrvscsdp--glitpynnrgysqgtdpdrtcq
klpelmikayvvctldrhaktrsavgeklavsgaegkrlaakshktqadv
ddvaavlpnistllllvrlywkyydkakyvgnlyymhvegcakkgkftld
kslteqapavrivphlglpwkdisalkfi---svfsaddriagqapnlhk
sntteaerfcsgsliyekddggyeanstlelgalapvrysgaynvspckw
-----lgygglnpkpagfkchctavkadhsdp-flafhcpkcvillahpl
hyak---------sag--kivettvsersfsvsktrrv-tkpw-------
-ykyessggkhegkhnmirdkk--------gpllcphd--ktcyswllyc
gleandgyllkelsalenlkkkrltavnmnyepr-ysvrdrqr---dclt
lcafhi
>E
nlaiehnaivsgfkdkdqmnwtyka-vvsakkplvkikkcalvgkiqfgm
rfnggktftgtaeaplppvcgraghkpkqvywlptfvllapglmknhlet
gtsplgsgda--sgtnedepigkqenyygmgggyytpqvgrdqdkgegpq
pktshynkhaqsyvtssgmqsdakhalkgylesesgtsvekklkhrsnak
ggtegglpgiklasfvqrkelslpnskyfcgakayspvtrcvqrnklelr
dalikkkiplsvgpklcan----kglwyvpsrsliypphvveqqi-pihe
eqvpsleshcvstlpngsldrgysitatvrlgcslsarymiflrsklngw
-----qgwsgtidvrvg-kcvglvclrtfmyn-l---tv-kkgvclvagk
qysh---------san--hrlqrvtvsissa-n---at-iknk------e
kfsydcmagthrdklsetkvdrdankteafiplcvkhqcy-------pyc
gakfdsiyplks---lttvaakrlapttkgfagqgftdrteav---dc--
--lsfa
>node3
vvatkraagmdlfltvvpk---------ihsflllrvtelaacdklnlgg
qfdadnnlahyiggglapkrikggytakkliwmagylllatgegklsheq
vasgvkhggsllsdcrekgrvshgdp--glvtgynnrgvsqdtepdkscq
kfpnllvkvyvlcsldrpiktraavgenvyvegaegkrlaaklyktdagv
ddvtavlpgigtilllhrlylnymekssycgsmfylpvqscmkiskfald
dslkaevpairiipqlghe----salkyi---amfsndgriaeqa-tlnk
sntaevarvcsgslinekddggyevdstlelgglssvryagsynvqvckw
-----lgysglnhkpagfgchgtvvkgafpgq-flgfhaskcglslvqph
hytk---------dgg--kiaetavssnsipia---rv-tktr-------
-yeydssggkhegkhdlvrdkk--------apllcphd--rt-yawliyc
gleasdvymqnevttlghlkkkrltetnmnfdqr-ysvrdrvr---dcfa
lcsfkv
>node7
vpcvkhasgmnlfltvvsk---------ilsflllrvtaivacdklelgk
qfegnkelsryaggglapkcvdagfrskkllwmlgyfllpaavgrlmqeq
vaagvnnggsflsdtrengrvghgda--dvgkayhnpgvcrdteadksca
kypsllvktglpcslnrpvkiraaigekvyvdgteakpldkklwkagatl
devtgllpgiglrlllqrkslnylrksfycgsmhyvpvqkcmkidkfgid
dvlkaklpaiavipklghg----salryisfqvslssdgriadev-tlnk
sntteiaracseslinekhengyevepalelgglvevryapsynaqistw
-----lgasalehkstg-gchgkvikgifpse-flsfnatkyglslvqeh
hytk---------dgg--kildkaivskstpkp---rv-aktk------q
lyeydsdggghkgklelardkk--------gpllcphn---------iyc
ghdssdvymqvnvvtmghlskkrlteanagfder-yskrnsvr---sc--
--sgiv
>F
nlsvqhnpivsafeakgelglaymv-pvgdkkslvkfkkcplagkvilga
rfgggktftesggaglsavcghagikpkdlyeiaatvllspqlsknvldq
gtphlgdstg--sgtkdegrfgdgde--gvgggyckprvarstdngepst
pkaawfdehskayytgagvepqakhplkgytsseagkgeeeklrhrrnqm
nvaagslvsielrsyvqskmvdlpkprnyfgikhyattkkclqrdkldlg
halndqksalstgakliak----sglwylsyskvafspqcveqai-prhd
aqvsgidahclfslpdgatsrgyeltatvkfgctlaaryqfyfkyklegw
-----qgwtagfdlrlg-tciglvclihflyn-l---nvakagicylshk
hfsf---------psk--hkigratvglsstkn---kv-vkakgrytrgq
kysyqcmggthrqkldgtrgdrdgveeekyvplvvshqcy-------pyc
ytkvkaiylnkstvemhvtaqkrmapatqgfegqgkkdrtadi---dc--
--lmia
>B
viakkkstgmdlflkavpk---------lhaflllrltmlkeceklsigg
qlnannnlaqyigkslapkrikggitakkqiwmaayllqaleavkishaq
vataikhggslvsgckekgrtshgdp--gsdtgcnsrgvsdnaapkkrcd
qmpnalvkvyilckldrpidkkptvgesvyvrgaagtrlfavmykaaagv
aditavlpgigttllfrrlylnykekanycgslfylpvgcclkeedials
dkltadvpakriiphlste----salklt---asynrggriaeha-slnk
spiakiavvcagrkvnekedggysadathdlgglalvkytnsdntqvckw
-----lgynglthnpnglgchgivvkgafpgk-flglhaskcllplvlph
hynk---------dgg----------gndipvq---rv-kktr-------
-ykydsavskhegnwdlvrekk--------splkcghk--rt-ypwlvts
gletndvnfqeeltllahlkkkrltntnlhydrn-ytyrdrir---dcfa
tcafkv
