>D
-------------epvmklrgscgtcdkgrl-aeiknqqiarthsaknef
lieearfacegtdrsvgfdlvhlfgagvsnesnalalakhfvekcnpa-f
mhgspdikwwaqnkcdaagtskggaekakkavgimgvpaqdnaegg--vy
-lar----atkhvikltastdggvsayarrgyyekdeqegmskrqh---c
f-afgtiggflf-anlpglkkvkvadrwhdigvakphdhfseyirlalty
seysaaknigne--kklcvtcrgleqhvwlac-dllersk----dv--de
fkee-aikkvgsllvgpvegaesnhqdfrikspvvlvqsrvafgvllivt
ksgptagvnitalgvhtakkfvdtpktppladdgvrstqrvtgqngageh
ggspinaksdtvganvltkldsq-krlvgke----sktgqteteatk-ik
slvkvygidglgkrrgferlrvgyywratatpkppvqgcrcrgisgativ
ecg------gaiirvlvlaevadapapgmqaffmafgsidadrsteyhpg
falrcpqv
>node7
-------------dplkkfrapcgicgnqdl-vvinqdrvgwtdstslpf
llfankfecggtdkacgfqlcqvfgtgdtnkgqdlclesgfcsscmpevy
mtglletkwwnqdkcddagtlkg--eksnkpigtvgypeqhnstgg--vy
-lap----qtknviklagagd-----------fnsdqkegmskkhewnkc
f-lygafgpylf-anlpglktmqtadqwhaigvtkqhdlpmqyiflrlny
dqysaatsvgpe--hklnyfckglvqheylec-dylehsk----ll--ee
ekea-siilvrtvlagdvedgetsvqdfatkqpnlllpsklvfgillivg
nseptqsveietlsvpiskkyvdgpklppldqtgarleqraaghpgsteq
dhqplkakspklasgglgqldgqnkrlcgve----agtvqsncesam-dr
ayilvygsdavgrrknwyalrigyysrsvdsqwepvdgcwcngtagntif
kcg------gkaigkmvltqagaplapgkneffrayarigadrlfeysek
halkcpqv
>A
-------------apfakflapcghcgdqgl-teidphhvawtdsanlpv
iyfddkfdcsksnskcgfglcevfggedtdkgqglcpdsgfcasclpdvf
fkgqlkttfwnsnkcdsegglql--spcekqvsaenyaeenrgpfm--ef
-wap----qtvgnismagaga-----------lgsdakdkiskk-ewiac
f-lypsygpfly-annpglkklevidqwafigltkendvpmryssnilsy
dheskatgvgsdgvhnlkyyysgllqdeyyqc-dylnhsdcidsll--dd
ekey-vvslgktvldgevgnddaggqgfpssqagfikpgk-------ivg
kqqpgktvefetagapisgqy----mlgpldqesermqhqdskhpeatpk
danpvkarsaklaqgglsqvdgqehrlcsve----iasaankcaspksdr
yyalgynvdkvgrkqhwyglpyslylrtanrawdfgdqcwcdgeadettf
kcg------arsvgksklkqktitytppknefytkyasigiftkiiysek
pvgfcpqf
>node3
-------------dpltkfhapcgvcgnqdl-taidphrvawtdstnlps
iyfndkfdcggsdtacgfqlcqvfgtgdtnkgqglclesgfcasclpdvy
lkgllktkfwspdkcdnagalqg--gkcekqistvsypeqhrgsyt--ef
-wap----qavntikmagagd-----------fgadakegiskkhewnec
f-lyssfgpylf-aqapglkkmqeadqwafigltkqhdlpmryaynflsy
ehdsnatgvgsdsvhnlkyfynglvqeeyfec-dylnhsecigsll--dd
ekqf-aillnqtvlagevgddesgvqdfatkqaalimpsk-------ivg
nqepaqtveletvgvpisgqy----mlppleqngdrmeqrnakhpgstpq
dnsplkaksaklaegglsqldgqhhrlcsve----easaatncespk-dr
eyvlvyssetvgrkqhwyglpinlynrsvnrewdpgdecwcdgeamdtnf
kcg------aravgkmqlkqttapyppakneffntyarigtirmiiysek
haatcpqf
>F
-------------nflpkyrategvchddte-aqckhaltgllqsyaipy
vareetydsaecdksctlnlcqvhtrpdtsvkqsksikrlfheacfremf
tegalstawwheannapstafaa--nsvgpgagtigyesklsgkgg--pv
-lsp-----avltvahggadd-----------fkarhkggkkiphvwtgc
f-fiasagayvl-ielsalrelaagglwnatalrkdddlpgqyifirmsc
dgngttdplske--rkvkfmsgifeqqdylmcrdysqdnk----am--rv
dkqa-latlvgsllngdltkqepgingyvnryphavlavevvvglmlpvg
gavadkkanfetlslvignrcfpslprlaiqqsgvkydqsflvvsggasq
lhegrrgksqqvgsqglghleggraplcqaekgfestatlgecnish-gk
gnhlgsgskecklledkfavrpayytsksgnqwntldgcwcsgteaadpk
tcg------gkilkldghaefsvclsseatayfwgyarvestflfdfged
hslkcpkk
>node15
-------------nplpkfrapcgvcnddgl-veinqdmigwtestsvpf
llfadkydcgsadkhcsfplckvhgtgdtnkehdttvasgfapsclrety
magklesdwwhedkcaqagakra--eeagkpvatigypeqrnstgg--rl
-lap-----tkgnvmlagaad-----------yksdhksgmgkkhawdkc
f-lygtsgayll-adlaglrtlqagadwhgngitkqndlpvpylfvrlsy
ekysattkvgre--hklhyfssgfiqhdyldc-dyqehak----lh--se
ekqp-sialvrtvlsgdveggqsavhkfatkepnlllpsklvfglvlivg
ggpptqnvaidtlsvpvskmylngpkrpalgqtgarfeqrygglkgtmeq
eheprkaksfklgsgglgsldgnkthlclae----agsvksdcdgak-dr
gylltygydncrrvkaryglripyysrnvdsqweplggcwcsgtagnkig
kcg------grilpmqvlkqvgkemtpgkneyfrayarvgatllfkygek
htlkcpek
>node10
-------------nplpkyratvgvchddgn-veinhaltgllqsyaipy
lkheetydcgecdksctlplcqvhtkpdsnmkhsesvkqafdqacfremy
sdgplvndwwhegkyaattafsa--ddvgvgaatlgysskqagkgg--pv
-lsp-----avlnvahggaed-----------fkskhkggtkkphawtgc
f-figspgayvl-velsslrdlaagggwnasgltkdddlpgsyifvrlny
dkngatdalgre--rkvkfisaifeqqdylmcddysqdsk----mv--ka
ekqp-latlvktmlngdlvaeesafngyttkypeavlaedvvvglvlpvg
gavpdkkvtfetiglviddrcfpslprsaveqsgvkfdqsfaavngaatq
ehepkkpkssklgsqglghleggrtqlclaekgfdgtavlgecngah-gk
gnnltsgnneckllenrfgvragyynsnsgsqwkglggcwcsgtegadpr
kcg------gkilnlegykqfgrnlsspaagyfwgylrvestflfdfgek
hslkcpkk
>E
-------------kphpkyrgkatqcpddgd-aefndaltalqqsyaasy
lkdedtydcgdcdsmpplavcavqtsqkanidhtesvkygfdqscfidly
segpllgdwratgdyhastafsa--davgmgagilgyaskqagkgg--pl
-lsp-----avlhvahdgsde-----------fptkhkhgttaaepwtsc
f-figapgayil-ihashlkrlvtgggwngsgltknkhvpasyffirlsy
dkksakdalgkd--rkvkypsaefehqdylmcedyaqdsk----lv--ks
dkqp-leslvktilngdlaavesageayttkypeevmadnivvglilpvg
gkvrekavtfeaigliiddrcfpslpksdvqqsgikfdesfstvngmatq
dhkpkkpkpsnlnsrglghlegghadlcvadqgfpgtavlgncnevh-gk
gtnmksgnhecklvqnrfgvragyysetagnqwksfggcwvagaaggepk
kcg------gkilslegykqfgrdlaepgasvfwhflrvepaflfafser
hnlkcpkr
>node14
-------------nplpkfratigvchdhgl-vevnqaltglvdsnsvpy
llvsetydcgscdksctfplcrvhtagdsnmehdqtvasafekscfrety
tagpmedqwwhegkysaagafra--deagrsnatlgyssqqgadgg--ri
-lsp-----akanvvqagaqd-----------yksnhasgvakshawsgc
f-lygaagayll-velaglrtlqagsgwdgsgltkendlpspylfvrlsy
ekysattdvgre--hklkyfraafgqqdylacddyqensk----lv--se
eknp-tvtlaktvlngdviagespvhgyttkepeavlpenlvsglvlavg
ggvpdqdvafetvgvpvserclpslprsaveqngvkfeqsfggvkgsmeq
ehepkkaksfklgsaglghldgdktqlclaengfngttvlgdcngas-gk
gnnltygynacrlvkaryslrveyytsntgsqwqglggcwcsgtngtdan
kcg------ghilnlevykqlgreltdgadeyfwsyarigatllfnygek
hslkcpek
>C
-------------epvmkfrgscgiagrsnrhaiikeeqvnraqstkhaf
vlsnirydcegterttkfnkthlygvgaeneghqlcnscsfvnkcipe-f
mdgtvevkwwahekcddsgplkg--ekpskaygtvggqkqhhedgg--vi
-igg----aarhvikltgaangghsancrrtyfhkdeyeflskkqhwnkv
f-sfgafggylf-tklaglkttkraqhwhgdgigkqhdkfeiyisfamdy
nnydvpayvgpe--kkagvicrglithlrlvc-ellehnr----lgakpd
ekkd-ginmvnklltgeveggnfshpdfpnrapvmllpsklafgvlliip
asepagpvgteaiessttkklvaepklgplkddsphteqritadagvseh
dgaplrkkapsvaqagtqplagqgrrlagqa----sntavtqteagm-dr
gsilvygsdglgrrrgtyslrlgyywrvtaahrepvdgcwckgttgseil
kca------giatesmaltapadqlapgngaffmeyaripadrgplyspk
falktpql
>node6
-------------epvmkfrsscgicgnsnl-avikqqqvdrtqstkkaf
llssvrfacegtdrtcgfelvhlfgagasneghalclasnfvnkcmpe-f
mhgtldikwwaqekcddagtlkg--ekpskavgtvgypeqhnedgg--vy
-lap----atkhvikltgatdgghsayarrayfnkdeqegmskkqhwnkc
f-afgtfggylf-anlpglktvkvadqwhgigvtkqhdlfeeyiflalny
nqysaasnvgpe--rklnvicrgliqhvwlec-dllehsk----ll--ee
ekkd-giamvknllagdvengesshqdfpskqpimllpskpafgvlliva
esepaapvniealgvattkkfvdgpklspldedgarteqriagqagaseh
dgsplnakpstlaagglikldsqgkrlvgqe----sntaqtdtegvm-dk
gfilvygsdglgrrrgfyalrigyywratasqsepvdgcwckgiagttiv
kcg------gvairgmvltevadalapgnnaffmayaridadrsteyspn
falkcpql
>G
-------------nklpkfrtpiailldhvl-aeiaeavkglsttgaapy
rliadvfdcgsvneacdfsvcrvhkeddsnmahrqtvaspydrtafwqec
tagpqqsvwwgggklsgpgayqa--gekgkssavlafnatkelsaa--wi
-fra-----gkanvikggape-----------fksdhpaasgrsatweic
k-lysttgsfranvslvglratqaaygladpplikenrteapflyvriny
ekyktvvdmtri--hklkyfqanlgkhrfvecegyqennk----dl--ad
dkak-avsltrrplqedvltansnvhgftvkepeavlgeelvcghilsgg
ggshnedttydtvgvrts----------tlektglkydesfgsakgamdf
rhdpkknkeieigceglgpldasksqsclakhgydgvvylgdveglp-tn
ggnvsigfgacrfiqapypvkvdyydpr-gsqwqglgfceccankstesn
kcaettktvahilnkgvnrslgreltlaadeyfwstakisgtllfkydqv
vsikclnr
>H
-------------kklptfraaigvlqdenl-edceqtlkslvdsagipl
lltvecfdcgscrkpcklglcsvhadssasmnhpeeittgydspaywdtc
tsgseesqwrgqtkytgpgayrt--gqkskastilayallkaldgggnri
synp-----aadsathggsqn-----------yqsnhppsgaraptwggc
f-lsssagayalkielvtlralqsgssfpqaglikkndlptnflhvrlsy
ekykttddagrd--hklkyfkaalgtqkflecdgyqeass----dv--ae
elsd-svvvvgtpfndpiitsnssvngftakepgavlsedlirnkilgvg
gevnhetgkfdtagvrvrgrcftalsrtgvelsglkfe---------men
tlepnkdsgwklgceglghldadgtesclakhsydgtihlepvtglp-gk
vtsvsasyaacrfvdarfatkveyyapr-gsqwagvgscqcqankstqsp
kceekgkvvshmlslgiakrltraltlaaddyfwtyarvandllfkydav
hslkctak
>B
egsqklgaddtlnndtikfhgpcgkcgnqql-taidqhkvewsnsynlhs
vvynakfdcggsgtgcafqlcqvfgtggtgdgqglclesgfsgtcladvy
lkgllntkfwmpnkcndasslqa--grcekqitpidfpdqqggsyt--ef
-waplsksravdeiklagdgh-----------fpadsaegtskkheweec
lplasgvsavlf-kqepplknvqeanvwvfvglikgndipikyayafisy
ersqkatgllgssvvnlqyfhtglipeeyfgc-tflnqt--ftsll--nd
ekqflaillqltvlsgevgddddgvqafatkraalimptk-------ivg
dqepvqsveielvgvpiegqy----flpkleqdgqrmdqrtakspsavps
eshplraksakspegrlrqlvaqhhplcsle----dqeaatncepak-dr
eyvlvycseavgrkqdwyglpinlynhsserefeqgdecwcdgeamdtny
kcg------prvvgkmkraqatapnppvssefftey-rvgkvratkfner
isaqcgkf
>node13
-------------nrlpkfraaigvlqdhgl-qeieqtvkglvdsstvpy
lliadvydcgscskpckfglcrvhtegdsnmahpqtvatsydktafwdec
tagpeesqwwghgkysgpgayqa--gekgkasatlaysalkalngg--ri
-ynp-----akanvvqggaqd-----------yksnhppgvarsqtwsac
f-lysaagayllkvelvglrtlqagsgfpepglikendlpspflyvrlsy
ekykttidlgrd--hklkyfkaalgkqkflecdgyqensk----di--ae
ekak-tvtltntpldeevitgnsnvhgftakepdavlaenlvsgkilgvg
ggvhhedvtfdtvgvrvserclaslsrtgieqaglkyeqsfgsakgamei
thepkkdkgfklgceglghldadktqsclakhgydgtvylgdvdglp-an
gsnvtigyaacrfvdarysvrveyytpr-gsqwqglggcqcsankstesn
kcdettktvshilslgihkrlgreltlaadeyfwtyariaatllfkynqv
hslkctdk
