>node15
lasssvqgnpptvvelplgetrvntcqrqcvvmtayyryeisdeekglwa
qylieyiqnyyygiavadhlmniwitgrcstlggighilvqlfavagqyl
cftaflngsslrhkaslafgp-------makgc-----tyelkylnrqek
ktiygnh-alfysllarlspeyvankpmscpveisqkvpflkqeaevggt
sgdppplgasv--vvkdarqalld-----------anpdggplgpvkgla
vfvtgwahq------etafafa--gpgancyqktcqpvkqlfgpdgqdgc
gygkrpkthillapstihltgp--eqhanvlgqaeifffngraeqlgesk
tragpdtlmaarlksgllk-rskrikqiedda---lggypqvhyggmenk
gkaqiniqgg----cpvgklg-pvvlifepptaggdd----lltqgpgfv
eggyphsklv-----dcncktgksvvidhrslspcel--rlefa--ftce
pgdslvliqahhlwealhhilnyskdgahmtggeksaqnggclkypemhh
seiggrpt
>D
matpgvdgcrpgggalplgavkvsncvkqcvlnafcfkrqiagktkglwl
lylaqkrcssaynlvldehlvncwgvtacndlglvtkvllqkfaaakdya
cffcflpggnrrgkaslqlgp-------qarfc-----vygl----kddn
kaiigar-dlffsmqalfvasyneekpvvcgpsiskkgpvlrqggnlags
dsddpplgesv--vlknkwhalrt-----cfwannpniegsklnevgglv
ifitmwehk------shefsya--gqsadanhtacqgdkelkagdgevkc
gygdapaahilleaatdrlgga--dahiailgkgsefffhakkssdnvsv
apvgpptlveekisgllmk-rvekaehldlqa---ldgysapaysaqehk
sraalpvsag----atigkigisecavfvppscggpd----lltkevgfn
esqfrqsavlrvgttdchcrasksdviedynfvpcnp--wlefv--ftts
vetstvsvksndksagmhsvhlyskynpckkapnkdd----pvnvpsmha
vdl-----
>A
lipkpvhggrqgvllmplgqvrvsncqakpvglngsykldltesqkafwa
sfllgyy-------smtdvinaswiiekcknvgliervvtplfsletgyi
tflcfirggdlknqsalalar-------avkeciskcmiyqd----kaed
ldlygev-wlfyallkmlsgewsskkelgcpvilsqmvpflqtgttvegg
acdppplaan----pkhrrqaffn-----cswkakvapnsgamdntggyl
lfitkwpnh------evaftye--ghsehckhkacappkelvasakhvdc
gyvegpkadivlspgakyvasn--ppqanilapqpafyfhpkaealsesq
artgpdkliahrvkkqllk-edpksseidfrg---lahfsfatlgkmdsk
gksqpcikva----ctvgllavslllimepptgaape----litggpgfv
agnvpessnr-----gctaqggqsvkiekvvfspcdishrveyg--ftt-
-adssikiaphdrpggfhhvilyspagptrpaggvgkqqegctvcpgmst
eei-----
>C
lapigsngcrpggghvvmgevqlshcirptvvqeysfrlegagqskglwl
kylapyrvdsiyalstaeqmihsyslktatglgmydkylvqefgpasgfl
cfmcflpggntraiaglpvgp-------mptfc-----gysa----tdpd
kavaase-klfvsvfamfasqycqekevecgvdvsqkaafvkeggslsgt
ssdppplgdsv--tprnkrqqfks-----cywpkhvantggplgvvaglp
vfitkwdhk------ghdsafa--nqsadaqsqacrgakelldgdgqvhc
gynkapaaqirldpgsqrlatn--dellnimvrhchffyhdklkdaaveg
atggsstvvedrltklllr-ryakkshievqg---lngysapaytsqent
aksvlplksg----cnlgkaglavvavfappdtgtpa----lqakapsfs
etkfrqsglvrstgvdvpcrsdksiiidemtfapcqv--rlefa--fats
edkgtltvkpnersaglhshhlfanfspcktapgdkeqeggplygpamhv
vhv-----
>node10
laatsvqfepknvanskagsdrpqdcarrclvmvayyrftfaeenkglwt
dyliagiealyygdcvldnllalwiserctalgalgktlvqlyaltgqfg
cfncfladpaveckgtltfaq-------maegc-----tyelkypnkpsk
kilfkeqfdvfyllgdrlpaayvaskasncpvevklnvpslgavapvgpr
lggqsalgtpv--hiqdlrdllld-----------tsrdgaplgpmtpvv
eflnsysks------dvagndalcapgpqaylavcqetkqlfapesqggs
gygprplnqlvlapptlhfagp--sqvptilgqahlyfysgrlqnladsk
qwagpdlllsaaldndlvdkwvrpvkqvnslp---lggyeqtqyggslsk
gkngnktdkk----cpvgpvg-nsvvlfespkadgse----vetqgpnfa
epgcphhkia-----dcncnvensvvvahrslrpcel--hlkftfslmpe
cgrnlvlveqhhlwdlekqiipyskdilhttggkrtrhnggclmyhdmdh
fdvgirpt
>F
laatsvefepktvansrggrnhpqdcarrcllavayhkftfadehkglws
eyliagiealyfgdcvlenlltlwisercttagklgkelmraysvagqle
cfncflvdpagdcrgvtafae-------mgkgc-----tyelkypfkstk
flllndrfvlfyllggrlpasyakfkaancpiqvklnvpalsagapippr
lggqsalgypv--hiqdvrevllv-----------esrdggsmssmtavv
ellngyakv------dtsghdglcavgahaplavcqeskqlltpviqlgc
gygpsslnqltlappvvnfagp--nqlptflmeghfffyggrvaclansq
qwagpdilitaaldkdltdkwvvavqqvsgtp---lggynmteyggalsn
kkgtnksdkktssgcrlgpvg-danvlyegakkegsq----veskgpnfa
kpgqpqhdia-----dcncnletsvivsrrplkpsdl--nlnfvlslkpd
capnallgeqhhlwelekmyiqydktyldttdgtrqrhnggclmyrdmnh
fdvgnfag
>G
iastantfapaevlhpgihrsrlhayrwkchhvtvhfqickhidwn----
------------gg--ldvvygvwdaarattlsagahkmsqlfdttghfa
chtcvtdtatlqmkgalvair-------mnlgc-----nfqqqyvqspek
gvsfrdifavfssqterldnviiakktlncpvlvr-evqiirvgaavghr
gappptasyslalqsqklgsqlge-----------garhhkpmepkkqma
wfvegyedklklikldiqgnnplgnnspvcylkaceatkqkfgpevqgva
gygkrphthkileh--gqligsasgpvpktlesaqswfhagktqmlgqqn
pwvksdprlganytdqlmk-plqegtevqgfp---qgkqpqnsygglmkk
getakksaak----waegnlg-geavktvipkgtgse----rerha----
-----hdkyt-----vchcrlvksdvihhkdlmpcel--qvnfassfese
kgwalvlckvhpawallkaklnyvtevghvkvvdksqelggclnypevhh
neigdkpl
>node7
lapnsvqgarpgvvqlpllevrvnhcqrqcvvmdscfrldiadeekgmwa
qyliqyiqnsfypivmtdhliniwfvrkcnnlgliarilvqqfavasgyl
cftcflnggnlrnkaalalgp-------makgc-----iysa----kedn
kdiygeh-slfyallamlapeyvadkpvdcpvemsqkvpflkqgasvggt
scdppplaasv--vpkdkrhafkn-----cfwtnkatpdagplgdvsgla
vfitkwahk------evafafa--gqgpncnkktcqpakelfgsdshvnc
gygkrpkthillapntkhlagn--dqhinilgqaaafffhgkaedlgvsk
aragpdtlianrlkkallk-reekasqiedqa---lsgysqvtygamenk
gkaqlaikgg----csvgkigtpvvlifepptnggpe----lltqapgfv
egkfpqsali-----dchcrsgrsvviddvsfapcdi--rlefp--ftta
egnsavkikphdksgglhhvllyskagpsmtsggtsaqnggcvaypgmhq
tei-----
>node6
lapsgvdgcrpggvqvplvavkvshcarqcvlkefcfrleiagedkglwl
kyleqyrvnsiyplvmtdhliniwsvktctnlglaarilvqqfapaggyl
cfmcflpggnvrgkaglplgp-------makfc-----iysa----kddn
kaiaaar-nlfyplnamfapqyaedkpvdcgvnvsqkvpflkqggsisgt
ssdppplgasv--vpknkwhafrt-----cfwansaapdggplgvvsglp
ifitkwehk------ghdfafa--gqsadtdkmacqgakellggdgqvnc
gyakspaahillepktkrlagn--dahlnilgkacafffhdkkedaavsn
arggpetlieerltklllk-rveksshievqa---lngysqgayssqenk
aktqlpikag----ctvgkvgialvavfappstgspe----lltkepgfd
eskfrqsalvrpsgidchcrsgksividdinfapcqv--rlefe--ftta
edngtvavkpndksaglhnvhlyskfnpcktapgdtdqdggpvnvpsmhv
vel-----
>node14
lastsvqfdpknvvnstlgsarvqtcqrrclvltayyrfafseenkglwt
dylvagiqnyyygisvldhlmaiwitgrcsalgavghklvqlfavtgqfa
cftcfmgdaalerkgslafsq-------madgc-----tfelkylnrpek
kvlfkdqfavfyilvdrlspeyvankpmscpvevsqnvpilkqgaqvgqk
sggppalgssv--hirdlrqqlle-----------asrdgaplgpmtpla
efvtgyahk------evagasalcgpgpqcylkvcqpakqlfgpdgqggc
gygkrpkthvilappafhltgp--gqvpnilgqaeiffysgraqnlgesk
awvgpdallgaklesglvk-rvrrikqvqgnp---lggyeqthyggmlkk
gkagmklenk----cpvgklg-gavvifespkadgse----vetqgpgfa
eggcphhklv-----dcncrieksvvvnhrslspcel--hlkfafsftae
agrslvlvqqhhlwalqkqilnyskdilhmtggernahnggclkypdmhh
feigirpt
>B
lvpnsveggragvlkvplgevrvtrsqakcvvmngcykldiaqgktgfwa
qfmskyi-------lmtdhqvtawfvqkcgnlkllcrfltqvvcfetgyv
cflcwvtgpdlrthsplslghvvgiqegrpleclgkcliypp----kaad
levygka-tllykllamlnpewaskkpldspvemsqsdqfikqaksvgan
acdapalaap----pkgrrhaffdldlfngfwtskgsapsgnlgksggml
tyftkwpnl------disftyt--ghapnsqkkacngatqvfaadtltac
ayvsrpktevlfdptatkvasl--eqqndvlgpatlvyfapksdnlgsnk
ppsganglivarlpnaalk-kcqplsvidqqgqgylaeytpeklgkmeqr
gkaqsctkgp----yplgvinvpillklepptiniad----llsagpafd
eakipqskdq-----gchcpsgasvqfqeivftscdi--glefg--ftea
dghrlvktvphegqaglrkvllyskvgsslssggstaqdagcgpyrpmhh
pet-----
>H
iastasnmppdscvhsalghawsnpyrspanhlaggysyafcvhhk----
------------gi--nnrmytawdagrcitltaggfkmsqffdavgqfs
cftcvvgsatfemrellafiq-------laqgc-----nfamvyvqtpqk
gvsfkdafavfgtqsdklaksfvakktvsfavivr-dleiikhgpivskr
ggpppglsttlgihvgklsrkhie-----------ashnygplgprkvla
afvegyedklhlvkanisgagalggisppcylkscesgkeyygahgmglh
vyakkpetfkvlah--yqltgm--gavpsildtpqawffngkitqlgqsk
gwvkpdirleakyanalak-pvlvakqiegfp---lgghahtshggvmkq
gdagkklikk----hgvsptg-gemvkyvspkaagevyhggrnaqarglh
tapcnmndls-----acepriqkssvvihkeltpcel--hvkfgfsfase
tawsqaldendpawailetklnyvteipdmhigdraqpnggclkypdihy
feigerhl
>node13
iastaptfapkdvvhpaigkarvhayrrrchhltghfrfafcvdhk----
------------gf--ldhlysvwdtgrcstlsagghkmtqlfdvtgqfa
cftcvlgsatlemkgplvfiq-------maqgc-----nfeldyvespek
gvsfkdafavfytqsdklansyvakktvscpvavr-dvpiikhgaevger
ggpppglsstlglhvaklssqlie-----------asrnyapmgpkkala
qfvegyedklrlvkvniagasalgglsphcylkaceaakqkfgpegqgvs
gygkrphthkilah--fqltgs--gpvptiletaqswfyagkiqqlgesk
awvkpdarlaakyanalvk-plqqatqvqgfp---lgghaqthyggmmkk
gdagkkletk----havgnlg-gdvvkyatpkaegse----reeqargfh
saacphdkla-----vcncriqksnvvnhkelkpcel--hvkfafsfase
agwslvlvqghpawallkaklnytteiphmtvgdrnqnnggclkypdvhh
feigdrpl
>E
iattsvafsppetgntddgcdstqdcsrrclvflayynttfaieanalla
gtliesiqgvyysdcvldalltlwisirctalgaltktleklyalpgqfg
cfncflaaaavectgpivfpr-------mgqgc-----tfeltfplkapk
kslskdkfnviyllgdrltvsfhgpkssicpvefklgvpaigsvgavgdr
kgaqpalgtpl--hlqdvkellfd-----------vsragvplgpmnpvv
pylsdypkn------nvaskdalctpapqiylavcqetkqlfapeaqgst
gygahplgilvlappslhfsvp--hdvsnilgaaplyyyagrldsladar
gwagpglllngtldddlhdkwtrpvkhvsvlp---vggydqgqyggspkk
gkngnktesk----cavgavg-npvvlfdhpksnese----ietklpnms
epgcphndis-----dcrcnignevtlahrskhpcev--sgkitfnlmph
cgkplmlaekqhlwelqkqiipytediihttggkrtrnngsclmyhsigp
fdvainet
>node3
lapnsvqggrpgvlmmplgqvrvnhcqaqcvvmngcykldiaegqkgfwa
qfliqyi-------lmtdhiasswfvqkcnnlgliariltqlfsletgyi
cflcfikggdlrnksalslgh-------aakeclgkcliyee----kaed
ldmygev-wlfyallamlspewaskkpldcpvimsqtvpflkqgtsvggn
acdppplasp----pkhrrqaffn-----cfwtnkatpnsgslgdtggll
lyitkwpnq------evsftyn--ghapncqkkacspakqlfasdthvdc
gyvsrpktdvllapssklvgsn--dqqnnilgpatafyfhpksedlgesk
arsgpdgliahrlkkallk-keertsqidqqg---laeyspatlgkmenk
gkaqtcikga----csvgminipvllilepptnaapd----lltgapgfv
qgkvpqsknq-----gcqcrsgqsvqieevvftpcdi--rlefg--ftta
egdsavkiaphehsgglhhvllyskagpsmtsggsgaqdagctvypsmhq
vev-----
