>node6
aidgp-------kpilpdgkhyqdvdsphlsptagaqeeleapsgdtlkg
knlgggkgsecnydtmgtsdhmtdaagirldp----vivvqranyfpget
dyeegplqysrgnacayngdsptgv-vvasssy-ltwanfg--i-anmng
ilcwldacinvyvdelqllnekakvnhylgkallahtscqtegn-hmf-s
--ksrdlfsvaeklgkfvndkykflhlfgtakdeadad-------glkhf
padacgagrgelgtgfeqgkglqg--wnskaekemeessntlelgysgyq
aeefeqkyqicrvtpsvrklketfcsqcepktlts----ltgevaci--k
ckkgegmkkvevgdwdpvnariievycagatndraptaiilrrkwncgfg
fqgtgpsicflvddq--a---ygyktakgstaqdwapratdflvpkatha
hcaglkghcgkklvfftvqcvrhgaeh---mgvtsfgaypaptqsvigii
amsgmpatfgeegpnpnckgsvvipprcgm---rfagy---ylstctpfc
p-i
>C
tvdep-------kpilpdgqhyhdvasahlgptgtargdleapsaetlkk
knlsvgkgsepryktmgtcdkltdkkdiqldpilydvivvqwqdyypget
qyekgslqykrgascgyngirkkdv-svastky-ltwakya--i-anlag
ilcwldaclpvyseelqllhektkvnhylgkallahvschtegn-qma-s
rgkpreifsvsedldkfikakykflkkfdvanteange-------gikqf
kadaclagrgelsrgfeqgkglqgtlwpknvdkekdeashllglgfggyq
deqfpqkyqirrvapsvrklkedicpqcepksltspgvsltgevpci--k
cgkgegmkkvkvgnwnpdeariidiycagatgkraptaislsrkltctfp
fqgtgptlcylvdan--s---ygyqtaksetaqdwtprgsdfllpkaves
hcaglrghcnkheafftvecvpygaeh---mgttsfgaypdetqnvigii
amsglpatggeeapgpnckggvvi--rcgt---kfgsy---flascalcc
s-i
>F
tkqen-------gedrwkelvyhfahsahknnpttsrdseeqsigssdng
kitdv------akgkvacreeleectgvklkp----aelvesawffarnl
tyvvn------gqgaaprgeqdkgv-avlserlilgwekylkqlclills
ivethgpcfplykgrflllknedrvgslsmnclrpdtvyvgrechkld-t
--msrvlfra----sqfissnyifesglralkgkkfnniywfrmegtray
cndtcaakkvalaneqydgrratg--vktkhsskkieddewiqleyrdye
agkdlqkirfceiskpfiklknnavekagtvdvtn----lndpvatl---
--eidphk---allnqr-rarlanvactglsikvgivpvalkk--rsdwg
fmnpfkgaclftgspggrmsalyydyslvnnpktfedraaaflvnlagpc
pkaplnakakk-svgllseikkhrtvh---tgalpfsagpaqlsgtsgtd
vpgltpqtysldqsepdlkqqlstaerckq---rlvqfikvfltgcrgfv
ysv
>node7
pkdgp-------khilpqtkdyhqpdsptldptagaqeqldapsgnttkg
kalgsgkgaycnigtrgaqdhmkdsagirlep----mvpiesanyfpmav
eyqea------gsgcakksesrtgv-vvssnrf-ltwakfg--i-lnlka
ihcwlnpcisvyvdefqllaekakvnhhlgkallphtncltdgn-hmf-e
--rsrdlfavmvklgkfvnnkckflhlfgapkepsdag-------ggkef
agdtcshgrlalaagfekgksllg--lkskedkemgeandtieigysnyq
teefqqkyqvckvttsvrklretfvsdispkaltn----lsgedvsi--y
ckkssplkqviagnhdpvnariievycvgatqaivtaaiilrrkrkcafg
ftgpgfaecffvaeq--agnlyqyttskrttaqqwkpratdflvpkatht
hcasfkghcgkklvfftkqcvrhhaah---mgvtpfgaypapsstpngti
lsggapatfgeeqshpdckenvmipqrcdq---rftay---flstcttfi
y-i
>node10
tkkes-------gelrrkshvyhfphsaekdsptvprdsqeqsrgsddkg
kvtdv------adgkvacseelkkytgiklkp----aelveagwffprsl
ayvvg------gdgcgkrgeqdtgv-alladrlilgwskylkqlclills
ilgthgpciplylgrflllqeedkvpslkmntlrpaatyvdkpahkld-t
--lprvlfra----thftstkcifekgfaakkqkkiagklffrieggrqy
cndtcaakqlnlanelykgkqlmg--vkakhasqkaeedesiqldyanye
aekalqkvhfceisssfikaktdfaeklgakaltd----lheqvvpf--y
apqiephk-vkaglnqq-rariantvcgggsikagvvpvglrkrrrsewg
ftgpskggclfigshdgqmslfkyetpnvsnpknfedraatflvnmaspc
akaplsaktkk-piyitkeikkhrtvh---mgvlafsagpnqpcgssgsd
vsgdtpesysqdqnqpemkqnvsttercdq---rfiqfielflsgcfgfi
yav
>node3
pkdgg-------nqivsptkdyhqpesgsldeaagsqgsldastgnmskg
klleagkgaycsiatkgapdhmkectgirlep----lrpiesgeyypmtv
eyqea------sdgcakkrssrtsv-ivtthhy-vswakfg--a-lnlkt
thcwqdfcisvyvdefqlmaekanvehhlnislllhtncltegk-hmf-q
--rnrnlaamvvkvspiannkcnilhlfaapkqpgket-------spkdf
ggiscsrdrvainagfesgrslla--vksnesqelgedndtvqdvhsnyq
tggfsdkyhaskvsyevrkmrdsflsdvmsqklkn----lsgedvdi--h
cppsphlkeaiagsrdpvnskiigvycvgstqsivtanivlrrqnkcpfg
ftgpgfaecffttqq--agnhahygtlvrataahskpkatgflvpkelht
ncaefmgkcgkksvyfaaesvrhhaah---mghtkfdaynaetgapkgti
lfggpsanlgeeashpsckehvmlpercdk---eftgy---ylstcvafi
y-i
>A
pknggvievahdnqivtqakdyhspepgwldgaagpggrvgpitdnmskg
kllqhargiycssppg-spdpknectgiqlqp----lkpidrgeyypktv
efrqa------sdgcasnrgsrask-ttpthhy-vswatfv--v-lnlkt
shcweefcikiyandfkllaekdsyqhelyirlalhkdcltegq-hmh-q
--rnrnleamlvkvnpipnskcnvlhlfaankqpgket-------adsdf
ggiscshdrvtinnefdsgrsllt--vkshemqqtgvdhdtvednqgnyq
aggytdkyhasrvsyetknmrdsflsgvllqelkg----lngdnvdf--n
cpaskhlkdaivgssdpgkskivgvycvgsilqvvtadivlrkrntcsfg
fngpsnaqcfflsqh--agqhvhfgdllkaaathsrpkttgfvlakslht
kcadfvskcikkkiyfaaysvrhracr---mghtkfhsynaetgtpkgai
kfggpnaslgeeavhppckdhvmlpehcan---eitgw---ylrtclafi
y-m
>G
ntggt-------akgfgrkhifhfpaahsfepgtgsrglqnesrgtspda
rgngvvqvvhcwagkftcsaglhnyagihlqq----gkpimanwyfprai
syigp------tnfcgqrgnlrtav-svltetittcwykye--lvlglvq
ahpwhapceaqylgkflliqstqgvvlhradklesnpscaakpl-elf-h
--lsrglfmv----ghvvst--iitgtlggakesirvg-------ggaey
gqgcctssklalaaefykgkqilg--lrekhtrdekdnddsfqlgfsnye
nldmvlkvdrcqlqcsltklkenllvtaeaktlih----ihkgklpf--i
aeqvdpgk-attgedla-rsksnndspaaahvtvnivplvfieaarcgwg
vvgpgfgtcffltdtdaaaalykcgpskhdgcklwdlwv---------ha
hkkpmvgkger-msllskelkkyaaiveahmgilpftstsnppcapngs-
---------------simkddldtsarcdq---kyshasgkyldgcysyl
ykl
>node13
tkgga-------gdvlgrkhvfhfpltarfdpatgsrgnqdpprgtepdg
rpsgveqvahcwtgklacadglhkyagvhlqq----vkpiianwyfprai
gyasp------gngcgkrgeqwsav-avladkltlcwakye--vvlglvq
ahpwhapcialylgkflilqdsesipahrgeaiqaspsciakpl-qlf-n
--larglfrv----thavst--iiikslttakdsitpg-------ggqey
cndscstgqlalaaefekgkqllg--lrekhtkqedanddsvqlgfndye
dedillkvdicqiessliklkenflikavaktleh----lhdnpvpf--y
ctqvdpkk-vttgedqa-rsksstsacaaasikvgvvplqlrkaarcgwg
fvgpgfgacfflseediasnlfkcttpkrsdaklwdsra---------ha
hrtpklgkger-mayitkelkkhrtih---mgilpfssnsnppcapngse
lggetpagfaqeqshsimkedvstkercdq---rfghfgskflsgcysyi
yti
>B
pkdgp-------nqvvspdadynqpesgsadpptashgsleaptsnkkrg
klldapkgaycsiskkgapshvkectnlslep----lrntepgeyyppav
eykea------sekcakirsprkpvaihtthhy-tswhkfa--a-lil--
----qdfcisvyvdefqlmaekahvaqhlnltllkkttcltsgk-qtf-q
--rdknlavmvlkrspisnskcnvlhqmpppkwpgkes-------srkgf
ggvgcgrgrvavgtgfpsgrglli--vkgnepseltedsdqiedvhsnya
pggfsdkyhagkhsyevkkmrdtflgdvmsaalrd----fsgqesdi--h
chrgpplretpagskdptkskvigvycidsidnvtlagivlkrqnkcpfg
ftgpgftectfttqq--agnhghfgtltrdnaahskpkntsmlvpkevht
kyseftggcgkkrvyfgalsvkhkgah---lgqpkldayhantgtrkdti
lfggkmadlgdershpsskdvvmaadkcdk---eftgf---ylsvsspfl
y-t
>node14
tkgga-------geilpkshvyhfpvspnadpatatrdsqdqprgsdskg
qasgvekintcsagklacaeelkkyagvhlqp----vepiiaswyfprai
aypsa------gdgcgkrgeqrsgv-avladkftlawakyg--lcltllr
ihcwhgpcislylgkflllqekdkvpghkgealqsatsyvdkpl-elf-e
--lprglfrv----thfvstkcifikafaakkepkisg-------ggrdy
cndscspgqldlaaqfekgkqllg--lkakhakqkaegdesiqlgfsdye
aekalqkvhicevassfiklrenflekasakaltd----lhdqvvpf--y
cpqidphk-vkagqdqa-raristsvcagaaikvgvvpvvlrkrrrcgwg
fvgpgfgacfflgeedtaknlfkyttpkrpnpknwdnratsflvsmasht
hrspllgktek-lvyitkeikkhrtvh---mgvlafsstpnepctpngtd
lggetpegfsqeqshsdmkenvsttercdq---rfgqfidkfltgcfgfi
yti
>node15
vkdgp-------khilpqshdyhipespaadpvaatqdtddhpsgndskg
kalgvnkgnycsigtlgcqeqmkdyagihlsp----mvpveaanyfpkam
sypaa------gsgcgkrsnarsgv-vvlsdkf-lawakfg--iyltlkr
ihcwqgpcislyldkfqlllekdkmpqhkgtalvphtsyvtepl-elf-e
--rsrglfrv----thfvsnkcifiqafatpkepreng-------ggkey
cgdscsdgqlalaadfekgktllg--lkakhdkeknegnetvelgynnyq
tesaeqkysickvassiiklrdnfledtspravte----lndevvpi--y
crkndphkkvmagqqdp-rarisivycanaaekivtaaavlrkkrkcgfg
fvgpgfaacfflgeq--adnlfsyttamrktaqkwnqrasdflvskatht
hrsslkgkcgkslifltkeivrhhtah---mgvlpfaataaesstpngtn
lgggapggfgqeqshpdskenvmvserceq---rftaylgafltgcntfi
yvi
>E
dkqed-------kelaskghvysfphasakdkptvrknaqgqsrgsddsg
tstav------ekgkaacredlkkytgfklkp----aqlfevswffprsl
tylva------gdgcgkqgdqntgv-allpdrlilgwtpfkkalcsills
tlgthgtcdrlylgrflihqeenkvpslkmdgikpgvdyvdesahaia-t
--lprvlyns----ahftssscvfdkgfaakkvkkitgnlffriqgsrqf
cndtcadkalnlanslyrgkkltg--akttqapqradedesiqadyasye
eekavqrvqyheissslvkaktvfseklgqkaltd----lrdqvvpf--y
apqigsqg-mkaglnqa-rgravivvcgggsikagvvsvglrkkarddwg
ltgpdksgcifvasqdgqmslfkyytpfvsnrkdfeqrlavhwanmaspc
aksplgsktkk-piyftkalrknktvq---lgvlqfsdspnqpsgpivne
vrgtapeayspdlnqpdmmqnvpeaskcdq---aftqfidlflsgcfgfl
fsg
>D
klnga-------kavfpegthyqdldrpktsaaigaqenlespsgdtlta
kslgggkgsecdydtkgttdhmtgaggdrpdk----avvvqhahyfpget
kydeapleysrgnaceyggdsptpv-vvagesy-mtwskit--i-vdmnd
ilcwlnacialygselqllgekardkqylgrgllehascqtggd-aff-q
--saralfsvaeklgkfandkykflhvlgtakdeaele-------glkhf
psdgcgevkgemgtgyeqgkglqg--wnadaekeleeasdqlgltfsgnq
leefeqktqvsrvapsvrklkdsfcsdcqpktltn----lpqeshcldpk
ckkgeskkihevgdctqvtaraivvycagatndrspqaiilrrkwscgyg
fqgkgssicflvkdv--a---ygydtdkgasahhwssrrteflaskvtng
ecaglevqchkkllfytgqcvkhaadh---kgvtslgaipspshsvtgir
aksgagnkkgeagpnatckgavvvppncglffarfaky---ynsictpfc
p-i
>H
tkpga-------gdvlgrkhvfhfpltarfgpaiasrgthdparntnpdg
rpssveivahpwtgnlaclsglhkyiglhyeq----ikpqltnwyfprtk
gypsp------gsgcgkpgeqwsdq-agladnlslcwpkyq--talvlak
kqpwhafckvlylgrfyilqekenlnahrgrniesgpkclakpv-qlfed
--larglfwv----ahalss--svvknataskeslapg-------ggrgs
ckdscntggsslaaqfakgkhllg--lkekhvkqeeaddgtvqlgtddye
didl-lkvgachieqsliklndnflikatsttlqr----lhetpvpf--y
csdvkpkk-itagekta-rcqstvtgctaasikigvvplqlrktarcgwg
fvtpmfgpcfflnqqdiasnlikattpkrseakvwdsrt---------qa
tkapklskgdr-maytgpalvkhrtih---lpmlqfssksnppcpppgte
lggdaaagyapeqdhsvvkedvsksdwyte---nyghfagkfphgcysyi
yti
