>node14
gffvtahcspmtyckdcvesleagrnfkgmhkkmlkagifk-----khsk
vgtsydspysykvfgvhldkglglgvvkletkqgkrcwgslclgsdvtaq
fdacgdgphhgrgmr-nsll-ggmegaaqrayiispnravgvklkcasik
eag-----ficslqwtkimsrysvpneaatawdhsddgsgtshskkelda
evdpdakstdrn--kkksrsectrqepsasinacnsqaftqqegghcnvy
eahtqdlvagtqglydvksay-ipmpkkqpeqg-sdaknghsrgs-----
--ftketipkndptyqkkcldiapvveekchiytaackakk--pmny---
-wdhkgetlvfvlnitetellgfeklaiat---------nverrlklrgv
----ttsypkpthastkyentqatkc-----eyevkvvakengkfaiafk
aipqeynpqmamte--------kddvtshpeeitsyeelllvgelrvrpt
llfgskaepvqlalecsnslvvgqgfe-----gelsgfnmdkytmavstn
ccirvag
>node13
gffqtsdfsptsyckaciesleggrpfksahkkmlkpnifk-----ihse
igtvydspytykvfgvhktkglglclqkiepkqgkkcwgslclgsdqtah
fntcggsphhskslr-nclv-isvegsairgflncpnknygvvfkcasik
dggrl--dfvcelewtkimsqysisnrtatawnnkqdgtgtshskrelqa
eatvqakstari--nkgsraecsreepsapisacnaqaltqqeegpcrvl
eahghelvaggqslydvksay-islpksqpeqs-kddkggssran-----
--ftnqtipkseptyq--chdkapiveekcrvytgpckvkk--plky---
-wdhkgqtlgylldi---------kltiat---------nierrlkiqgv
----rtgypkpthaspkyansqvtrc-----eyelkidvkenksfaiafk
aipqefnpkmamle--------kdqtpgqpdditsyeellavgglrvcpq
svfgskaepvqlaldctnslpvgqgfs-----gdlsefnkskftmgvwnk
ysikvag
>C
gtvar-s-rpifqvgkcknslmtkksfkgkrskmlnsgcya-----eplq
vphtmkvpyigkaygmvvglllsdlaktmvapagnpewcslclghetpks
hptcge--hqsssgvkksmi-dpmdfherrtyithtrveivvtlnctris
eqg-----ascalkyhdfnapydggvdqyvswehkipvaayngrkknakg
vvesaaktldhnsclksnkpvtteqiathqleqcahcafkaqkgehcgly
gnfdasqaagkedmyspgheyaipahekpeglaydgca-gkksga-----
--fisncvpsssskkvtgcvdvgagtigksliksqaapkns--plry---
-wskndagaaspigvdqlnllsydskklip---------naeiqvnyqtv
----llsfelprdgieayqnarsakrsddlkiiseavrgldaerytcqkv
adperydptmglnrpgsprnempvqqdnrheglsaytnfiierglkhhtc
leyav----vamglircaplpisqcfigvcrqsifprfpvdpftletyae
-cdksqk
>node6
gsvas-s-spifqvkkckdslmtnrsfkgkrnkmlnsgcya-----tptk
vphavevpyiskaygmvmgqnlsdldttmvtrpgnkawcslclghdapkh
hspcgd--hpcsavv-ksmi-dpmdsqerksyithtkvqiavnldctkin
egn-----ascelkysdfstpydgsgeqvvcwehtkpvpgyngrkkqsks
qvescaktldhdscmspnkagstqriethklyqcnhcafkgqkgehcdvy
gsysaslnagkvdiyspghayaipahekpqglgygvcn-gkksgs-----
--fakntipsagskkandcidvgtiavgkshiksheapdng--aarc---
-wnhkdafasfpiatdqldllgyeskkmtp---------kaeiqvkyqnv
----vtsfekprdgvnkyensksakcsddakvlsqnvipkdserftcqkv
tsperyqptmpldnpgvprddksvelagrhepltayqgliitrdlrhrdc
leyaa----vemglercsplpvsqcfpgvcrqgtlpgfpmdrftmevyae
cckkvqg
>node15
gffatdhygpiihvkkcrdtleagrafkgmhnkmlqagiya-----kpsk
vaqsyevpyttkvygivmgkslglgvvslltkhgkkcwcslclgkevtan
fdacgd--hhcqtvr-tsli-ggmesnqprayitspkreiavkllcasik
eag-----licdlewtkfsspysvpneptvcwehpkaapgtqnskkhsnt
eveasakaadrd--maqsrsdctrqedndriyecnsnsftdqngehchvy
eaysedltagtqglyqvgnay-ipvpkkvpdlgfsdakhgqsngs-----
--ftkdtipkkgnteqnkclhiaqitadkshintatcktkk--avkc---
-wnhkgetlafalgigesellgyekadisp---------ksdkqlkyrvv
----ttsyknpkhgatkyektqstkc-----aynhkvvakdndqftiqrm
stpeqynpdmtltepghrrvdkkddatshhepitsyqnllvvgelrvrrc
leyts----vqlalescsalmvgqcfa-----galtgfamdkytmevysn
ccikvaa
>B
gafsaigyspiyqvkkckqylgterthegeherpvnagcyvtvgdylpad
vsqavsilfgcnkygllhgknlsqlaaglwpelatrshcslcltkavssn
npasgd--fessplr-qhli-samevqrpmvednnvqiqasvdlkcyspk
apg-----dssdlewaeynppydaygiqvqchahkkpgpsynprqkaaat
eiqvsgkvvtrgtcatpvkgdgsdrskhdhvfrc-hcklrdhkvdagday
ke--ghlpectahiyyashsf-tpchrpnpglgysqcrhskpvat-----
--fak-------gtrtnrcitvaasgvdkgetdapaapanqalgynvvip
swshkpqtmafrikltaieklacdnrallp---------kgepekryrag
----vakydkakegvskctkslstwcgtmakvvarvvglsdnnefscskv
akaaktepdmvlgspgvdrkdkavaitadhen--kynalappmdlrqkec
laytk----iqhdleacpplavgqilasaviaatfssfpeerftigiyka
ccekftg
>node10
gffvaaqctsmvyckecvesldaerklagmhkkiakagikk-----khsk
vgtsydsgycfkvkgttlgkglglgvvklqskqgkrfwgklclgadstaq
fmacgpsphfssgmq-nsll-gglggaderyhliepgidvgvrmkcasik
eld-----fvctlqsprtqsryaipdeastawdhceagsginhakdeldg
aadpdaksadkn--kkkvrtqctrqksfvlvgacnpgsftqqd---cngy
dshsqelaagsvdlfdvmpvy-iplarkkparg-sdvkgghnkgs-----
--ytketipksnptyqkkcldvapvveencecyastckagk--plny---
-wdhkadalifvlnaspkqllgfakldiatnrqvfltg-nverrlklrvv
----ttgypkpthvttsyehvnatkc-----pyelklvsteagkftiayk
vipeecnpqmatte--------kddctahpdeitsydelllfgdlrarpd
mlfgnkgeplelalacsnqlvngdgfa-----gavsnfemskytmamskd
ccirvag
>D
galaa-----------cedslmqdqgvkakrnkmvscgcea-----apsk
vahgveapyigktygmvigqklfdldttyidrpgnkawcnlclghtaakr
hspcgt--hpcgavv-kdai-dpmdpqekkryishtqvnfevdlqctsed
qgn-----ascelkypefstcyagtseqvicwghttpapgyngrkknkks
hmeacaktldrevcsepakagsrqgiethklytcshcaykgqkgeecdvy
gpsaasnnqgqvdiyqpahtyafpshekpp----gvcy-gkrsna-----
--fakhtaqavgsgkaddclaegtigiakthtksqeapdkg--garc---
-wnfklafiavpiatnplavlgyetkkmaq---------kaavgvkyqnv
----vrgfekprdgvggyenakqakcsddakvlvrslipkesegfvcvav
tsperlqpampvtnpgtprdgksmagagrhkpvsayqgplitrnlrvrec
ldysm----vskivdrcgplimsqcftgicrqgtlpgfpmd---------
-----qv
>F
gffiavecqamlyckacvdsmnaerklagmhkktaksglkn-----khsk
egtsyatrfcfkiklttlgkgiglghvklesktgnrylgklcltadcsaq
fkacgpephftpgkq-dsll-ggldgaqdryhlvdpgidigvwmkclain
ked-----fvctlkstrtagryttpdkqsaawdhceadsgvnhakneldg
aaspdsksadkn--kc----------gfvlvnpcgpgsysqre---cngc
etdsedlefgqvdlfdempvy-aaqirksaaqa-seiegghnkgd-----
--laketlpkasqpyqtscldvapcveknsecyatacltvm--plsy---
-wdhsanalefhlnaspkpllsfgkldkgtkrqvfltninierklklrvv
----ttgsptpthltnsyehvdaakc-----pyelklvdaaagaftiayk
vkpqecnpqmgtae--------kndrtahpdaitsddplllygefvarpn
llfghksqplgiamscgnqlvngdgfn-----gevphfemskytkalskd
ccvriag
>G
gffpttefsiatfcksciesatasrpfrtahmkmvkpeifa-----irse
igiiyknpftykvfnvrktkglsvcvqkvdekhnkrcss----asneiah
fntcggsphqsesir-qclvtvilegserlgflncpnksygvsfkcayik
dgnrl--gfvcqldwtkimsdysissrtatpwarkqdgtggndgememds
vetspakktari--hkasrahcsreepsasifackaqsllqqdelpcrvl
daaghqlaaegtpvynantiy-vkmpdphpeqa-kdgeggsseak-----
--ftkqaipkrqptfi--chdrgpiterkcrvytgpctvkk--elkh---
-wehkgvelgylldi---------gltvss---------dvegrkkfegv
----rigysqpthsspnysgsevvrc-----syelkfdvkedksyaiafk
plpqefnpkmamld--------kdqtsgqpdditkiqqplpvgglsvcpq
siigskaapiqhalqcsnclpvaqgfa-----gelsnfnsakftmgvnnn
tfikvvg
>E
gfflagqctplvyckecvqkiqaesklgsmhgkiskhgvvk-----khak
vstaydkgycfkpknsilgkvfglatvklkacqgkrfwgklilgkeskee
fmqcgqrpvfvstaa-tsll-ggvggadpryhlvdnsidvvvrlkcssiy
tqe-----fviqleaerthsryvtpdqacttrghcevsppvdlakdaldg
adepdvksgpmn--knkvrteytrqnkftmvavsnpgafteqk---cngf
dshgvdlatgsvdlyammpvy-iglarrkpsre-awvkggpeksm-----
--ytrqtipiveptykktcldltpmveghcpcyasscksgk--pkpy---
-wdqnsnplvftlnasatdllgfanldvaddhqafltp-kkqhryklrav
apkgttgypptshvptaferanaskc-----pyhnklanaeamtfynqyk
iipnncnrqmmkte--------sincnmhpdphdpydnlllfsdlrlrpd
llfglkgeelelalgcsnqlvhgesyg-----aavanfemsdytmalkkq
ccirvag
>node3
gafssisyapiyhvkkckqflgtgrahkgdhqrllnagcyvtvgdfmpak
vpqavavlfgadeysmvmgrnlsqltaglltdngnrcwcslcltkavasn
nescgd--fdcstlr-qnli-sameaqrpmititnvqiqvgvdlkcasvt
sag-----etcdlewseyeapydaagqqvachahskpapgynprkkqsat
eiqgsakvisrdacttsvkgdasnrenhdnvyec-hcqlkgqkvengdey
deytgslsectadiyyvghay-tpshrmppglgygacrhgkpvas-----
--ftketapkkggtktnkcitvasatvdkgnvdapiardnkalgnks---
-wnhkpaalafpiaiaeieqlacnsramtp---------kgetemryrga
----vttyekakdsvskytkslntrcgdgakvvarivgakdnssftcskv
ataerthpgmvldnpgvkrkdksvditadhenltkyqallcvmdlrqrdc
ldytk----vdqdleacsplpvgqclasvvcggtfsgfpedrftvaiyte
ccekfrg
>node7
gsfasnsyapifhvkkckdtletgrafkgkhskmlqagcya-----kpak
ipqaaevpyitkaygmvmgknlseltaslltkhgnkcwcslclgkevtsn
hngcgd--hhcstir-qsmi-sgmesqqpktyithakiqiavklqcasin
eag-----dtcdlewsdfaapyeangeqvvcwehtkpapgydprkkqskt
qvegsaktverdacmtpskadstrredndriyecghcsfkgqkgehcdvy
daysgsltagtadiysvghay-ipahkkppglgygnckhgkpngs-----
--ftkdtipkkgstkqnkcidvaqitvekshvdspeapdne--aakc---
-wnhkdaalafpiainemellgyegremsp---------kgdkqlkyrgv
----vtayekpkdgaskynnslstrcgegakvvshkvvakdndrftcqrv
spperynpdmvlddpgvprddknidatshhepitsyqgllvvkdlrhrdc
leyts----velglescsplpvgqcfasvvsggtltgfpmdrftmevyae
ccdkvqa
>A
gafkgfsdapvfhvkkchqflgvgrahkgdndrllniacfykvgnfmptk
ltqgasllfggdehamvvgrnlsqltaglltdnankcwcglcltkavssn
keasvd--ldceslr-qpii-samdaqrqmitipdiqiqigidlkcasat
epg-----escdlewseysapyerpgngvschthtdpkpgyapvkhryat
eiegaamittrdgcttavrgdsdnrekhdnvygc-hcqldgqklskgdey
veytggvskctaviaysghay-tpsqrmppglgfgpchhakpvasigkee
vpfssksapakgktttskcltivsvtadknnidsafardakalsnks---
-wnpkpaslafpiciaeienlgcnesaktp---------kvdaqmryrda
----ittyekakdsaakyvkagnnrcgdgtrmvarivaa-------ctkv
sdaarthpemtldnvgvkhkeksvditsshekltryqalfcilplrqrnc
lnygk----vdddlsacpplpigsclvsvacgatftgilenaftvavyte
cvcarrg
>H
gvfsaseisptsycnkcidnleggrpfksihkkmlksnihk-----vnte
igtvlespytykifgvhetkglgltlhklepmqgkkcwgnlclasnqtah
fntygggshwrkslr-nclv-tnvqgspireylkcpnkkygtvlkcanik
dgarlklgaccelqwmkirsrysidvptstcwnnkpastgtahtqrelqa
paaskadasgqi--nkgskaqcsrekasavvcacnaqplpqreqgpcavl
navgrdlvaggqplykvssay-ishpdrmkeea-kdenggstkan-----
--fknqtmpksqknyq--chdkaavmeskcmvytapckikk--plky---
-wnhkgqalgkvldi---------kltiat---------naerrlkiqgv
----kqgytkntppsakyanpeanmc-----nyrlkdntkadksfiiglk
aipkdlnpqmaelg--------kdqasgdpsditaveklvivggvkvceq
avfggkvepiegadecddnppvgqgip-----eaanefigskftmgawdn
ykikvpg
