>C
dkwvviicgwgdskfhm-----ntktaqsag-----evplvkppaavekg
pltrkqcnfgle-------qsqhktqceeca---g--gghylscwnavak
q-a----grrfgqeggkdvskttvgak----tpshhdaydanypyggpsv
hrfr------gaqqwilaqhpasrdlalnliegwhsftnlksafaekgdl
viaisykltrsqcsrihggsdvltkcy-yisdlr-----ndvvalqdaim
pasdmkfr--hqgfsifsiedcyicnp-ldpktkfsdkgktfvlygqerr
rltpfvsrnlikslapggeigaldahvkgc--------aggigy--ctke
plfaypiatkggnhplgmrldmtaaewskqla-tndaadtasegyllgfl
iagdgvselsdhhtkgdkftvagtaffllkydqgqsvgvtvaevdqssla
fdkllng-----tstktlaslqepgvtgidvslnnevdeqgalvgenped
kdqtvsfllravtelllsadlnilntsnevmgllpkrkfaaytktlp---
--
>G
knkhiqgvgweaakhnllgpngtnqngralttivgkdnglysmataagla
plgrheanvcvd------lpskpcysc---g---dptvve---cvkecay
r-vgmngnwpnvsentlnekkhseavl----rqnaqdtavqkvafpvkfg
vrtv------ktkywhpslra--ihliialqhkytnralhqavyvgkgdm
lieqeheiikgicatlqlnqsikmpsy-kakvnlppgspnaeiplsnqfv
apvhvfpesyelllgisahgecfnchmsagpkepgdvpqmgl--rnkegg
lviqllqsttlrdlfqigkptgypghaedcsydv-qisca-pvypsclrs
ppkqkptksrgpegegdnkvsptkrnwhtady-lkeaaptddkeyghdfm
wkattvlsaklskdkehvckitespfkqpnennntpvfpkpqhfltssap
vdqlvqd-----qngtatglthqpdvlgsknlitkcaigavaettrhdsv
khkvnpfdlvqawygftrndfqtvekvqdviaiylklkqlvlkqangqar
sg
>B
kkssvgkaglnsvknhv-----ktklaqgkg-----pkp-ktqpgatdkg
gltkshcdvglk-------ttesqgncqqrslgta--anhfaeevkevaa
l-l----gwklksnreiaiahptiglflykrtpdhrhashqgltypvnfh
hmnh------qsgfpspvhhv--vel--------pafaelkagyadsgel
atalkyeaakaigsllskpqgnkgkcf-cvkspg-----vylpgarldig
ldhepsyh--hrglgvhqedncqpcek-lspahqigikakaf--ygqgkk
tgigymesslakalstiggarclkekvkdcgaak-hdgassqsy--clne
alsskptstggpgqpierrkhksagdwsdqls-mnkslcrtrtstiltfm
wsgsdikdhglphdkyrqfqagdapsnvr----dnhvthtsdavhaagva
ydslerg-----vagahleeaqnygvlganlllssttsiqvflfakssss
adsrenfeiivfgdllhagmdnplnsstlvknqlnlptletyrkalkdg-
wm
>node10
kkhpnkglswdtdkhnplspphkyeasrgks-----dgdlvtiktnlalg
algrhgdnvplevgvvealhvkagtnc---g---ednivpfgnclqpiae
p-vdfcpkwpmhdedelevptrtaafl----rhgqqyttlqav-lptcfg
ssti------rskytnpsqhh--pelitgldevygsfillmsvyklkgkk
lleqnaaatvqvcstiheaesvkeaqf-yvkikvpagsndaaaayrndil
ktshlseqsmniilsighsegcyschd-tgpaqteeiagltf--tgdtmr
kavnhlqasplsvlskanggadnvahvegchsevlhmgcngtiypsclrt
vlkvkpshikdpggnkqapargtqahwknass-vakgigskskdyvnmym
wkgksaassnlqpgtenpipvnegpislpklvknngvgekdeyfatttva
avglgcgtrllhskvtpnqskhdrdllggeklmtilgaaavvlktsrasp
khscdlselvkagerfrndkyetlqkthdviafltkptyltykdepglk-
kg
>node15
kkravrdlgwgsgkyhl-----kkdegrgst-----etqlvtpstalelg
slgrhhanvple------lhanlntncaqcg---g--ttplanclkdiar
q-vnicwkwslneeddlnvpkrtcall----klghhnaknptipypscfh
qrnr------dskfwesvhhv--vdliialeelydafallmavfpekgdl
vvvmkqeatkglctrmhepqkvlgsgf-yvkkkr----adaitalrddim
pptqleih--nlvlainhqedcfncne-mgprqqlgmrgktf--tgqekk
kvisflqadklktlaeggsaadtgahvegctsgv-hvgsggpvypsclkt
plklkptvtrepgepvehrgrktpahwstqls-indgvvtdqkdyalsfm
wngssvaetalhhskenpftvneesftipkiqkdnnvgdksdhletttva
feklvng-----vrgtpldssqergvlggdslltttstaevvlgtgrsgv
khtadpfllihiahplksdkfstldktqevvnlltkpsyltytdelslg-
qg
>node6
nkwvvricgwgdgkfhl-----ktklnqgtg-----eaplvkaptevekg
pltrqdcnfgle-------hadaktqceecp---g--ggpfakclkkiak
q-a----grrfsqedgldvpkrtvgak----tpsnhsandsgvpypgsfl
hwkr------tnmqwdsvhhv--vdlalnlaqgwhsfaelksafaekgdl
ivaisydatkglcsrihgssdlltkcy-yisdlr-----nevvalqdaim
patevafr--hqalgifhiedcyicdp-lgpkhklgdkgktfalygqdkk
rvvsylsnnliktlapggdfeslddhvkgcvsgh-akgsggigy--ctkn
plysnpiaskggdhptasrthmtasewstqla-tnegpdtsrnsyllsfl
wdgedvselalhhttydkftiadsaffilkydqdqkvgvavaeveqpsla
fdkllng-----vsvktlaswqdpgitginvklntevdeqgllggtrsge
kdqteafllnavtelllsdklssleksdevmglltkrkfaaytktlt---
--
>node3
kksmvrktgwtegkyhv-----ktklaqgkg-----akp-ktpptaveig
sltredcdvgle-------hteahgnceqrgl--a--aghfadcvkevas
q-t----kwkltsneevdvarkttgll----spshhsashpslqypgtfh
hrny------fagfwapvhhv--vel--------pafaelkagfaesgdl
avalkyeatkalcsllqnppgnkgkcf-yvkspg-----aklpaaradim
ldtepsyh--hrtlgihheencypcek-mgprhqigikaktf--ygqgkk
kgisymeasltkalagvggasclkehvkdcasge-hegaasvgy--clka
plnskptttngpgepierrkhkasaewsdqls-tndnlcktrtsyiasfm
wsgsdikdkalphskykhftagdapssvp----dievghtsgeveatnia
ydkllmg-----vagshlddpqnygvlgadlllsttttiqvflgatssge
kdntenfllimmgdllladmissldksqfimdqlnmrslltysnaltlg-
rm
>D
npwtvricgwgegkfkl-----ktelnvakg-----elplvkaaseveks
pvtrqdchfplh-------nadaktqcercp---g--ggpfakclktvdr
hgg----vkafspdgggdvpkhsvgaf----vssahsapengvpypgsyl
hwrr------timqwqsmhri--vntaldlaqlfhsfaelkrafaakgal
vvalstnatktlcnrihgneelltkcy-yiqdlk-----nempvlrdail
paevvafr--hhaisifhiincyvcda-lgpghklgnktliyaaygqdkk
rvvayltgefiktlaaglnfqslgnhvsscvsgh-akvsggigy--cmka
cmysnptvskggeyltasrthltvrewsedlattnegpdtrrdadllsfl
ydgpdtaslsmtvssyssfgiaasafyslryetdhktgvtiaitahssla
f--lita-----vskkrmaswedpgitsisvklntevdqhgllggtrsge
diqseafvldayvqlllsdalgsleksdevmglltkrkfgaymatls---
--
>node14
kknaikglgwdtgkhhlfspahkkeagrgkt-----dsqlvtvstalela
algrheanvple------lhgkpatnc---a---edsvvplanclqeiay
a-vnfcrkwpmhdedelnvpkrtaafl----rhgqhnttiqtvryptcfg
trtl------kskywepgqhp--veliialeeiytsfallmavyrekgdk
lieqkqsatkgicstmqeqqqvmesdy-yvkinvptgsmdaatalrndim
spvhlseqsmniilginqhedcfnchd-mgprqqdemsgmtf--tgkekk
kainllqasnlsvlseggsaadnsahvegcssev-hvgctgavyptclrt
plkvkpthsrdpgetvenrarktqahwntats-vsdgvgtdnkdyvntfm
wegtsiadadlhhdtenpitvnegpfrlpkidknngvgdkaehfqttava
letlvng-----srgtpndstherdvlggdnlltdagtaavvlttarsgp
khtaapfelvhvthpfkhdkyetlektqdvialltkptyltykdepslg-
qg
>A
kkasvrktgwsdnqvac-----ktklfaakg-----gkp-aspaaarlig
pltrikcsvgie-------hatthgdceqrgl--g--aghfgdcvkeias
q-i----nwkiksndetsvamvtlgll----gpsqesssqsglqyppalh
hren------ftgywipihva--vel--------pafaelkagyaeggdi
tvalkyqaqkalcsllqnppgangkvf-yvkspg-----aklhaavadvm
mttspnnt--nrsvgihhaanctpcks-mgvrhqvgikattf--yeqgkk
kglsymeaslakglteisgaasvgghvkdcasge-yagdasvgh--clna
pldgsptqsnggggpsekrkhkptaewsdqfn-tndelckartsyiasfm
wsca--sakilpdsiykhfaagdapngvp----kvvvdhspgevdatnia
yvklvvr-----cvgnhvddtdnygilgprlllaktsaieeflgglssge
kdetekffmvmvvdllldgqtssidksqftadqldlrsllsydnaiklg-
rm
>E
kknpnkglswenkmqkplspphkysawlgrs-----qgtlvsikaalslg
avgkagdnvplevgvvdalhvkagagc---a---edni-sfggcpkpiaq
t-idfcpkwpmwdktpmevptststil----thgkqyttvqag-lpssfg
sqav------rssytsasqhq--paliea---------------------
----naagtvdlcstihdaeagkdadfyylkikvpaatddaaaaysanil
kksrlkeqsmvliltishsdg-----d-tgpahtnevamltf--fgphmr
kavnqlktssavflgkgngsadalarvngchgeiftlgcdgteyqsclwt
vlkakashikdqggdkmapkrgkkghwmdnas-vpkgigvasmdyihmyv
wkgksstasslapgaenpmpldegpkslpklvkengvcekndyfegsvvt
avglgvgtwllsskitnnqskqthdllggeklltllgagavvtrtsrgpp
khscdnstlvlhgerfrnsaheslqkthdviaflssgnyltyktepglt-
ka
>node13
knkhikglgwdaakhhmlgptgtkedgrqks-----dnqlitmstalela
algrheanvsle------lpgkpcync---a---desvvp---cveqyvy
p-vgmcgkwppandntlnatkrsetvl----rhnaqdttvqkvvyptsfg
trtl------ktkywepsqrp--ieliialqqiytnfalhmavyvqkgnk
lienkqeaikgicsalqlqqkvknsdy-yvkvnlppgsmdaaiplknqfv
apvhvfeqsdqlilvisahdecfnchdragprepkdipqmgl--tgkekn
kvvhllqatnlrdlsqmgsaadysahaegcsldv-higca-avyptclrs
plkqkpthsrapggtvenraeptqhnwntatf-lkdaiatdeknyvhefm
wdatkvmeadlshdnehactitespfkkpkidknnsvgekpqhfqtssvp
ldtlveg-----qngtatdpthqrdvlgsknliaqagtttiilttkhdsa
khtvnpfdlvhvwysfthdsfesvdktqdviaiftkptqlvlkqargng-
qg
>F
qkypkkgltfttdkhtplippvragpsrgkf-----naqlvkiknnialg
gigphenqiplgaaaietvhakaplhc---g---edsiipfgncaqpise
p-vgycpkwemgadhelevptrpaafl----rhssqyatltgg-lpscfg
gdav------kakytdpnqrh--phfvtgldivygsivllmslyklkgks
ileqdgaaavqvcstihshasvkeakf-yiqiklpagrndattpyrndie
ktsqlgehpmdilmsiahkegcaachd-kgpcqseespslav--ggeamt
kavnqlaatplsvlskikkatdtvahadgchiealrlscngtiyprclrt
vlklkashikdpgggeqaparntqvhwrstqs-vvmgiaskvqdystmym
wrgksaassdlrtttentipvdegpiclqrlvkdgglnekdeyiaptsva
avglacstrklhsgvtpnaskrdsellgseklmvmlghttdvlktnretr
ahscelshlvkaadqfrddkfeilqrdhevikfltkptylayrddsglk-
ka
>node7
kkwvvretgwgegkyhl-----ktklnqgsa-----qtplvtpptavevg
slarhdcnigle-------hadantnceqcg---g--ggpfanclkdiak
q-a----kwrlseeddldvpkrtvgll----kpshhsanhpgipypasfh
hrnr------angfwesvhhv--velivslaegyqsfaelkavfaesgdl
ivalkyeatkglcsrihepsdllgkcf-yvkklr-----eevtalrddim
pntevafh--hhalgihheencytcek-mgprhqlgikgktf--ygqekk
rvisylqanltktlakggdaaslndhvkgcasgq-hkgsggvgy--clkn
plyssptvtkgptepierrthktaaewstqls-tndgvcttrtsyvlsfm
wdgddvsdkalhhskynhftvadapfsipkldkdnnvghssgqveaaava
fdkllkg-----vagkalessqdrgilgadsllattitiqvllgatrsge
kdqtdpflliaiselllsdkissldksqevmdlltkrnyltytdaltmg-
qg
>H
knncikgvgwtaaprhmlgstgtkesgrqas-----enqlltlstsleqt
clgrheanisqi------lsgkpcyqc---a---degvvp---giqqnvy
p-vgmcapwppahdntlnaarrgytll----ryhaeatkvqgvvyqtsfv
iptlhlsfklktryweessrg--ielinslqqiyidfvlhlaayvaksnk
vfeakentakavc---tlhskikhsay-cvrvtlpegaihanvklrsqfv
qpahvfqqgnnlavmvdahdecfschgsagprepseiqkmgl--sgkekg
kmvhllqttklqdlnqlgsepdyaahseqcsaav-hlgca-dvyptcvrs
plqhkasqstapggrvenrqiptqhdwssgtm-lkeataheeksyphdfm
wdaiqvmettvshdslevcscverpfdkakkdkhdsvgeksdpyrtsava
lealveg-----qngtavnprhvsdvlgdkrleaqegttkiivgvkheta
khpvepselvhlwnsfthdgfdrvdktqdvigifakpaqfvakqargng-
qg
