>node11
ngvffvcahadhhkklgsdcrfercghccpvwhagrg----lqsknignc
ildeslapfrakcltpkdscvaaagdfiitpqsvraifcevnpgqnsskt
ekpdfdigtefevadkypsykmqcgirglcnkhl-------gginashfi
a--gnlhknrifqdtd---np--acacwtpgllqftqgeldpvlaemaak
crkgtldfnkddnkplagvkgcrklvkdkevstangaseykkpakaklke
ql--dtpdsfdrlrslqpfegflde--------eliqslkdiyakegrdy
heqsaakgcmflnglfgsvpralqlgtvq-dgyytshkpkgpgt-reqmc
ddnsatpntldgvfansgggtppvgstfkihggnpasfnkpfgf-npqpl
appygtadlak--assgiphlgepvtnkcfrelqrrhvkaasgfsmndvd
wlflpqfdhhkfilyesialcrdsattrmaaqgtnkgapshaantvwqcs
svgaiakfhi---y----hegfnapastspphlakltsep
>ENV_HV2NZ/24-502
nkvyfsaahpshnqrigsdcrfercgnccptwdagkg----lqsknishc
ilaeslapfrakcltpkdscvaatgdlfikpecvraifcevnpgkgsski
ekpdfdigselgaadnyssfkmpcgiralcnkyl-------ggihtkqfi
a--ghlhnmriyqead---kp--gcaiwtsgllqyteaesepilpevaak
crkgtldfnrdnskpmaglkgcrklvkdkevttrdgaspykksakaklke
pl--dtptslrrlksiqpyagfldd--------eliqnlreiyskegrey
hdqvagkgemflnglfgtv--alqlgtga-rgyytsvkpkgrgt-rde--
-ntgatpqtmdavfanspggvppigstfkinggnagsfnkpfgf-npqpl
tppsgtselak--assgepqlgepitnrcfrelqrrhvktassfglndid
wlflpqfqthkfvlyesigvcreaattplavqvtnkgapasaantvwris
nvgsvakfhi---y----qegfnapsssspanfsklpsqp
>node19
ngvffvaahpdhhkklgsdcrfercghccpvwhagrg----lqsknignc
ildeslapfrakcltpkdscvaaagdfiitpqsvraifcevnpgqnsskt
ekpdfdigtefevadkypsykmqcgirglcnkhl-------gginashfi
a--ghlhkkrifqdtd---np--acacwtpgllqftqgeldpvlaemaak
crkgtldfnkdnnkplagvkgcrklvkdkevstangaseykkpakaklke
ql--dtpdsfdrlrslqpfegflde--------eliqslkdiyakegrdy
heqsaakgcmflnglfgsvpralqlgtvq-dgyytshkpkgpgt-reqmc
ddnsatpntldgvfansgggtppvgstfkihggnpasfnkpfgf-npqpl
appygtadlak--assgiphlgepvtnkcfrelqrrhvkaasgfsmndvd
wlflpqfdhhkfilyesialcrdaattrmaaqgtnkgapshaantvwqcs
svgaiakfqi---y----hegfnaptstspphlakltsep
>ENV_HV2D1/24-501
ngvffla----gckklgsecrfercghccpvwhaerg----lqsknqskc
ildesvapfrvkcitpkdsctgaagdfiinpnsvrpifcefapgqassks
ekpdfdigtefevatrypsyhvkcgirglcnkhl-------ggvqgsrfi
a--gnmhkkrvfkdad---yi--acacwtagqlhyteselepvlteikak
crkgtlgfgkdndrplhgvkgcrklvidhevsttngasdykrpakaklke
ql--ntsekfdrltslqpfeglldk--------qlihnlkdiyakegrvy
heqtgakdcfflnglfggvpraaqlgvvn-ngyytghklkgpgt-veqkc
ddesategtldgvfptsgggsppiaatfkihapnpaqfnkpfgf-npepm
aspyrtadimk--vssgiphlgapttskcfrelqrrhvkaaagfsmndmd
wlflqqfdhdkfilylsralcrdtattpqaaqsthkgapshaantawhcs
svgkiakfri---f----hegfnapessspphlvkltlep
>ENV_HV2G1/23-502
sgvffvcahadqhkklgsdcrfercghccpvwhagrg----lqskdmgsc
ildeslapfaascltpkescvaasgdffitpqsvralfcevnpgqnsskt
ekpdfdigtefevankypsykmqcgvrglcnkhl-------ggilaghfi
a--gslhktrifqdtd---np--agacwtpgllqllegelapvlaamaak
crkktldfnkdnnkpfagvkgcrklvkdkevstangasdydkpakaklke
ql--dgpdsfdrlrsvqpfegflqe--------eliqrlkdlytkesrdy
hedeaakgcmflnglfnsvpralqlgtve-dgyhttskpkgpgt-reqmc
ddntatsntldsvfantgagtpavgstfkihggkpasftkpfgf-npqpl
tppygtadlak--assgipdlgepvtnkcfrqlqrrhvkaasgasmddvd
weflpefqhhklilyesiavchdtattrmvaqgtn-gapsqaadtvwqcs
sasaiakfhi---y----hegfnappstspshlakltsep
>node9
ngvifhcahashlkklerdcrfkrcghccpvwhagrg----lqskrigtc
ildenlapfrtkcvghkdacvaalgdfiftpesiraifcdinpgqnsska
eksnidigteyevadkypsykmqcgirtlcnqhv-------gginashfs
q--edlhknriaqdtd---dp--acacwtpsllqftqaeldpvlaemaak
crkgtldfnkddnkplagvksckklvkdkevctawgaaaykkplkaklke
ql--dspdsldalrslqpfegflde--------eliqslkdiyakqgrty
heqstekgcmfmnglfgtvpralklgavh-eayykghspkgpgt-rqrmc
ddtsatpntmtgvfansgggtphvsstfkihggnpasfdkvfgf-npqpl
appygtaelak--agsnvahlgepvtpkcfrelrrrhvncasgfamhdve
wpflpqfdhhkfilyesielcrdatttrmaaqgtpkgapshaanlvwqcs
slgaiakfhi---y----hegfsapantshpqlakllsas
>ENV_HV2CA/25-512
ssvflvathpdhhkklgsdcywercghccpvwnasrg----lqskdignt
ilddslaafrakcltpkdscvtaaadfiidaqsiravfcevnpgqnssky
ikpdfeigaefevahkhpsykmqcgirglcskyl-------ggihtnhfv
s--grqhkmrifadae---nprpacacwtpgllqftnaeldpvlaevtak
crkgsldlnkdgtkplttmkgcrklvtdkevttahgaseyiqpakaspge
pl--dtptsfrrlrsvqpfesfldd--------glingldsiyaklgsdy
haqgqvegkmfvnglfgtipralqlgtgq-kgyyahhkpnkpga-rekmc
edttetpgtldcifvssaggsppisatfkvhggapasinkpfgf-npqpl
tppygtadlak--assgipqlgepvpnecfrelqrrhvkaasgfslndvd
wlflpqfqhhkfilygsivicrdaaatpmavqasdkgapshktntvwpcs
svnaianfqf---y----hegfssptstcpahlaklsadp
>ENV_SIVV1/24-538
kaslyhcpnedflpaleldctldrcgnccaiwprgeg----kk--tavtc
laathfaplkaenrshqelcvltvgaicfkdatiektfavvkgkqe----
getnagvtaafetpgsletlnmncgvtrfseqyv-------gslsvahts
k--n---kqkvcnegdvcsdp--pcnewpaalagfl-----aplpalagk
ckkstlsfvgpsdnsfsgkkpsnstpknrpsatsheggrtakaekakfkt
ee--gqpdslhllrs-----gylkg--------allecldnvydsh---f
pdqdlakmkvyanglkskapndiklgtvrrneyfp-lvrthagspreqvc
sktgnnpksavgvfapspgrvlvvepqykknsnmtrqlstpfaf-heaps
papiltprlat--qgvrlshignvlmskcfanlkrrhttcpgafkspdvt
faaeesfdqaglmnyvsleicpeeyrqwmqaksrppgrpahpvnlmwkpe
tfgtmnfvif---r----qdawsgraaghhpqldeslhvt
>node7
kgqlfhcandeflpaleldcafkrcgsccpvwhpgng----kq--ssgtc
ivstqfapfkyesrshlelcvlavgaivfkdesiisvfsvvkpkqe----
geantgvsvsfetpgslenlnmncgvtlysdqyv-------ggvsvahta
k--n---karispegd---dp--acstwtpalvafl-----thlaelsgk
ckkstlsfigaeqdsfsgikasnktprerpdatsfeagiraravkaklrk
ql--gepdalhllrs-----gyldg--------kliqclndvyenhlktf
heedlaklkvylnglkgkapknlklgtvhmqeyyq-ltranagsprdqvc
dktgnnpksaagtfasspggvlvvspqfkkngdkssqlnagfgf-heapr
gaprlaaslls--egvrvshlgdvlmckcfaqlkrhhvlcpaafkmpdit
faflesfdhallmnyvsleicpeaytqwmhavsrpagrpahivnlmwkae
tfgtmeymtf---h----qegfpvmaagnhpqlkdelhat
>node10
ngvffvcahashhkklgsdcrfkrcghccpvwhagrg----lqsknigtc
ildeslapfrakcvthkdscvaalgdfiitpesvraifceinpgqnsskt
eksdfdigteyevadkypsykmqcgirtlcnqhl-------gginaahfs
q--gnlhknriaqdtd---np--acacwtpgllqftqgeldpvlaemaak
crkgtldfnkddnkplagvkgckklvkekevctawgasaykkpakaklke
ql--dspdsfdrlrslqpfegflde--------eliqslkdiyakegrdy
heqsaakgcmfmnglfgtvpralqlgtvh-dgyykshkpkgpgt-rqqmc
ddtsatpntldgvfansgggtppvgstfkihggnpasfnkvfgf-npqpl
appygtadlak--asssiahlgepvtpkcfrelqrrhvkaasgfamhdvd
wlflpqfdhhkfilyesialcrdsattrmaaqgtpkgapshaantvwqcs
svgaiakfhi---y----hegfnapastshphlakltses
>ENV_HV2BE/24-510
ngglfaaahndhhkklgsdcrrelcgqccpvwgterg----lqsknighc
tldenlapfwakcltpkdacvaaagdfiitpesvrvifcefnpgqtskka
lkpdfdittefevtdkypayhvmcdirgscnkhl-------gginashfi
a--ghlfkkqifentd---nt--acacwtpgllqftqgeldpileelsak
crkgtldfgddskrplngvkgcrklvithevskangaseynkpakaklke
ql--dcpdsfdrlralqpfeefldk--------efihslkenyakegrvy
heqtgakpciffnalfgsvpralqlgsal-dgyytghkskgkgt-vepmc
ddtsethktlegvfatpgggakevgatfrihagnpaqfnkpfgf-npqpl
appfgtadlak--sssgipqlgepttsrsfrelqrrhvkaasgftmndmd
wlfleqfnhhkfslfesralcrdevytpqaaegiahenpshaaatqwqcs
svgviaklqi---n----negfypptrtspphlvkltsep
>ENV_SIVM1/24-528
dglifhcshashlrsldrdcrfkrcgqccpvshrgrg----lqtkrigtc
iadenltpfnttcvghkdacaaaltdfiftpekiraifcdispgqnsska
gkshtdygseyditdkypsykmrcgvktlcnkhv-------ggitashfg
qdgedlhknriaqqtd---st--acaywtpsllqfkqanlhpvlaemaan
crkgtlqpkkenntplvgvksckylvktkeictswgaaeykkplkcklke
pl--espdsldalrslqpfegflee--------eliqglrgiytkqgrty
heqstgkgcmfmkgffgtvprplkmgavh-etyykghspngpet-rqrqc
ddesasptamtgvfansgfgtpnvssafkihggnpasfdkvfgfltpqpl
appyptaelak--vgsnvahlaepvtpkcfrd-------casgfamhdve
wpflpqfnhhkfilyelielcknatstrlasqgtpkgapstaanlvwqcs
svggiakfhi---y----hegfpapantsqpqlakllsas
>ENV_SIVG1/22-522
qgqlfhctndellpavelecafkrcgscchvwhpgpg----kq--tpgtc
ivktqsapfkyetrnhlelcnlalgailfkdesivnvfsvakpkhe----
gesntgvsvsfetpgslenldvncvealysdqyv-------ggvsvahtd
k--q---kariqpegd---dp--tchtwapalvafl-----thlaeiggk
ckidtlsfigaekdnfsgikapektakdrpkassfeagiiashvhaklrk
elaqgeedalwllrl-----gylng--------klinclkdvyqnhlktf
hekdlaklkvymngkkgkapknlklgtvhmenyyq-lthanagsprdqvc
dktgnnpksaggtfesspagvlvvepqykkkadnvtsltagfgf-hevpr
gaprlaaslas--egvrvshmgnvlkckclaqlkrlqvlcpqgfklpnva
fdflesgdhgllmnyisleicpaaytqrihavsrpatrpahiinlqwksk
kfgtmayvaf---h----deglrvmaagnhpelkeqlnst
>ENV_SIVGB/47-569
ltrllkgitgnyviclgleccfikcfkccsrwhpgqilamyrl--krrcp
aksgqlvaypysshgvdlvcvllieifiytrgtergvtcivhvrnq----
dkaptcidvayasaaclvkeqkaasvdlyvancliletyllsgsdlglka
g--tskqkekimpdhs---eh--eyavwspklkkrv-----kasaafaap
ikkedlrsaanrqethsgvktslakrmgrnpvpgfeggpaaeayeaaepk
ga--ehsaqqqnmqi-----gavricpnmaggavladcvgkvfqkglkai
krhnsskfiitkagvdakaprdvragnqa-sgyfg-lavanlgn-ksglc
eksavsmgeqpletnatrgll--pvnlfnkeglpctdlhksagq-dgakn
krfflglandselykisvtenfalvqpnsyghivthsilcpsglkldyie
qmsfewldlpdlpyggpgsispsgltnhthnvavsapaylnqlgflwmyr
qfrldpyllr---fngtrhagl-vlpqgeqph----lscd
>node17
nsvffvaahpdhhkklgsdcrfercghccpvwhagrg----lqsknignc
ildeslapfrakcltpkdscvaaagdfiitpqsvraifcevnpgqnsskt
ekpdfdigtefevadkypsykmqcgirglcnkyl-------ggintnhfi
a--ghlhkmrifqdad---np--acacwtpgllqftqaelepvlaevaak
crkgtldfnkdnnkplaglkgcrklvkdkevttangaseykkpakaklke
pl--dtptsfrrlrsvqpfegfldd--------eliqslkdiyakegrdy
heqsaakgsmflnglfgsvpralqlgtgq-kgyytshkpkgpgt-rekmc
ddtsatpntldgvfansgggtppigstfkihggnpasfnkpfgf-npqpl
tppygtadlak--assgiphlgepvtnkcfrelqrrhvkaasgfsmndvd
wlflpqfqhhkfilyesialcrdaattpmavqvtnkgapshaantvwqcs
svgaiakfqi---y----hegfnaptstspahlakltsep
>node14
ngvffvaahpdhhkklgsdcrfercghccpvwhaerg----lqsknignc
ildeslapfrakcltpkdscvaaagdfiitpqsvraifcefnpgqasskt
ekpdfdigtefevadrypsyhvmcgirglcnkhl-------gginashfi
a--ghlhkkrifqdtd---nt--acacwtpgllqftqgeldpvlaemsak
crkgtldfgkdnnrplngvkgcrklvidhevstangaseykkpakaklke
ql--dtpdsfdrlrslqpfegfldk--------elihslkdiyakegrvy
heqtgaksciflnglfgsvpralqlgtvq-dgyytghkpkgpgt-veqmc
ddnsatpgtldgvfatsgggtppvgatfkihagnpaqfnkpfgf-npqpl
appygtadlak--assgiphlgepttnkcfrelqrrhvkaasgfsmndmd
wlflqqfnhhkfilyesralcrdaattpqaaqgtnkgapshaantvwqcs
svgaiakfqi---f----hegfnaptstspphlvkltsep
>node18
ngvffvaahpdhhkklgsdcrfercghccpvwhagrg----lqsknignc
ildeslapfrakcltpkdscvaaagdfiitpqsvraifcevnpgqnsskt
ekpdfdigtefevadkypsykmqcgirglcnkhl-------gginashfi
a--ghlhkkrifqdtd---np--acacwtpgllqftqgeldpvlaemaak
crkgtldfnkdnnkplagvkgcrklvkdkevstangaseykkpakaklke
ql--dtpdsfdrlrslqpfegfldd--------eliqslkdiyakegrdy
heqsaakgcmflnglfgsvpralqlgtvq-dgyytshkpkgpgt-reqmc
ddnsatpntldgvfansgggtppvgstfkihggnpasfnkpfgf-npqpl
appygtadlak--assgiphlgepvtnkcfrelqrrhvkaasgfsmndvd
wlflpqfdhhkfilyesialcrdaattpmaaqgtnkgapshaantvwqcs
svgaiakfqi---y----hegfnaptstspphlakltsep
>node8
kgeifhcanaeflpgleldcafkrcgrccpvwhpgkg----kq--rsgtc
ilssqfapfkydsrshldlcilavgafvfnpesirpvfcvvkpkqe----
dkantgvstsydtpgslqnlkmdcgvtlysdqyv-------ggvsvghaa
q--nnlskarispetg---dp--acsswtpalvayl-----ahlaelsgk
ckkgtlafigadqdsfsgiksskkiarereastafeagirakavkaklrk
ql--ddpealhllrs-----gylng--------kliqclnkvyenplrtf
heedlakltvyleglkgkapknvklgavq-eeyyq-ltranvgt-rqrvc
dktgvspkskagtfasspggvlvvspvfktngnkpsqlnavfgf-hpapr
sapslaasltt--egsrvshlgevlmpkcfaqlkrrhilcpagfkmhsia
rpflesfdhpllmnyasldicpdaytqwmhavstpagnqahavnlmwksq
mfgtvayltf---h----qegfpvlaegnhphlkdqlnst
>ENV_HV2D2/24-513
dsvffvcahtsyhkrlgsscrfkrtghccptwhagrg----kqgknigtc
ildeclntfkvkcvthkdscvtsvknfivapesvklifceinpgqegdkt
eksdfdigtdyevarkhpgyklqcgavtlcnqhl-------gppysatfg
y--gnlhksriaqayd---np--acacwtvglhqygqgelhptlfdadah
crkasldfnknqnealaglkgceelgkskesctawgqsayekpaklklke
ql--dtpdgfdhlrplqpfegflde--------glihsvkdiyfkegrdy
heqrsakkcifmsdlfttvpavqqlgtvh-ddyyktkkpkgpas-rqqic
datapapdtldgviansgggtppsgstfklcgglpatfekvmgf-npepl
gppygtadllk--psatlarigtaenpksfrelnrrhveaatgfaskdld
wlflpqleehkgqllesitlcrdasktrmatqgtpkgsashaanivwqcr
svgdlskfhiepsy----hegsnapsstshphlakltses
