>ENV_HV2G1/23-502
nsgtakfangnkvatkfqsqcsscgvaadearaeggvvktgycrfdlya-
---------eetllnvsatplp---irksathlgygeacyvdmtgshthe
nqlcsgrlvaivgd-fc--raatngvvmthncvtrfrhplvnqgkaslan
vsvfdiy--klvgth--ggps--dh---gqpfaknrtqtytvdvklgrkg
agtgldrartkci---eptrnnpgayyarkggndcemskahhynhfwfle
tkgpnsamagdqdadrkttqcerggkgvgkkfrwaettst--igkk----
--gerek-----vggnsnmptvglgieddhtkfaevvtaakqpqstgngq
hdgsfgvkyldkkliflkgddsvplknskfkngsaklcrfs--yasafd-
-lvahhsncnkqyglv---hisaagdtgskpyfqlqtmnadydkstvgfp
emdkedpfwc--------------qvsqgqdtpgssfg-kv------ska
lk----------dtsdyfaldilgtkiicadaadqlaslgdegsghhrts
vsagqkcgnrsrvcffgftgfiggsvaii
>ENV_SIVG1/22-522
atgskaltaq---elnphnnctecpnaggdalpvlsiarggycrqnlcg-
------ayckrtvvsdcatplp---fnnsyihlgineaclvnlggscgdd
ldlpigqiva-lgtyfcnvrgteksveglhdfvsrfrgkqllpgkttlqk
vlpfsfy--dlggah--sckncken---gttdlsaradsynasthlglgg
galahdravvscv---aatktspgkyyar---kgealqkhhqikmfrvvn
plfkdqdgtdknhsareitrcrwgrgdtgekvrwltagks--laal----
--syqnr-----ignptrkgaetvgdndghnqissvvlavgdpntirrsq
htstfgmgtlamkllyqhidcgqlkrktnvapdaprlssfa--fvtsfed
glrmhgsncgpdrnkqnrnttsgttatggsthfplerlgsdfqrddpnvv
emvleaaflcgqhlyhsiigfaaaqvlssdeltnyqyf-ntttedgspsl
vkrccpisytyyqnrrafaicaisstrpsgdaeksystaglegwgyqvgs
vcvlqkcqkpcracffgnttstrtstavi
>ENV_SIVGB/47-569
lsicvqlmkm---tlvftdkgnvathpggdawlflgslplgihnnrrsah
qekkltdfchgetiencdtlla---iakhydrvv---v-------acgkn
lvtaifsgla-mdt-fcpplhkdslvvdyskfqdtykgveelqlddalhg
vldlnff--shygrshlkcaickhqlgnqntalkmrqgsyhgngrldlrq
gasefprstvvceehtherlvtcspyykrrqaepesmstiviyt------
--fsvkgqtggafkgwtlpgcswgnlsvgdavswlglneacglagearve
lgglqnakvgigsmqpsdkatdtlkddqklksvgdvainadasasehisn
hsefydmsmtkdaesfccapatg----dvvtpsgpsaiflt--fdfilia
alkkqstesgqasdfkkcsetkgmtttsg------------fkrtgeiii
kvyilgpytsgsskfeseesfefvkvnktrlltdfpyadkighnegradf
yk---ynhkgqydkhrvlcvkliraavkcpniaiafhsqvqpewvfytgk
lyafkkcqgqcrvgstkssvpgggknpnv
>node7
ttgskaltaq---elnphnnctecpnaggetrpilsvargayckqnlca-
------ayckrtivsdcatplp---innsyihlgideaclinlggscgnd
lnlaigqiva-lgtyfcnprsteksveglhdfvshfrgkqllpgkttlqr
vlpfefy--elggth--sctscken---gktelsargdsydasvrlglgg
gasahdravascv---eatkdspgnyyarkdsqgealdkhhqikkfkvvn
plfkdqdgtgkdfsareitecawgradvgekvkwltagds--lasl----
--syqnr-----ignptrksaetvgdnedhnqvnslvlavgdpstirrsq
htsafgmssltmklifqhidcgqlmkrtnvtpggprlcrfa--fvtsfed
slklhpsncgpdrskqncnnvggtsatggkkhfplervgpdfqregpnvv
emvieaafacghhlynsvegfaaaqvlksegltnyqyf-nttlnegspsl
vkrccpisytyyqnrrafaiaalsstrnssdaedvyataglegwgfhvgs
vcvlrkcqkpcrvcffgnttatssstaci
>ENV_HV2NZ/24-502
rigetkft--nkivtkfesacascgaesdrphaelgvikpgycrfevyl-
---------dstlvnvsttplp---fknptidlaygiscyvdmtgshtqd
selcagrlvavvge-fc--raatssvtsghncvsrfrhplvsqskasvah
asnfdvy--kqqgth--saps--dh---graskkhrtqtagvqvglgikg
agtglyrarakci---egtsssaaayyahkagnecemssshhynhfwile
trgisamiagtgvsernnaqcasggknvgdkfrrpdtakt--lgtd----
--gnrek-----iggllnmptggfgleddhdnfttvqtaakqpkvtgsgq
hdnsfglkyldnkliflkgpstiplknsklsngsaklcsfs--ydsafe-
-lvanhancgriygsr---higakgdtgtkayfqletlnaeynrpavefa
emdkeqpffe--------------aakqeqdapssdys-kn------aks
lk----------gtpksmaldilgsqtictdtadvtaslgsqgtgslvsc
tsaghgcggrsrvcfngfstliggsvaci
>ENV_HV2CA/25-512
rtgt----tgkksvtkfqsqcsscsaaqeqahaevglvkvgycrfelyl-
---------eetlvnisvtplp---yknpaislayanlcyvdmsgshthe
dtlcsgrlaavvve-fs--raatsgvvtghkcvckyraplvtqggaswan
vsnfsiy--klqgah--napt--dh---gspsdknrsatysievklgikg
agtgldrarthci---eaasspsgayyirkagsacqkskshhyhqfwild
trgpntliaatevserknaqcasggrnvgekfrwsetkkp--lgkk----
--gnred-----innnsnmaggglgiqddhdnfsalatvakqpkatgqsq
hlgafgvkfldnkliylkgdsvvplkstrlkndsaklckfs--yasafg-
-lvdhhtnckrqygtr---higmegdtgrksyfqletmdanynraadgfa
emdkeqpfws--------------hvkhaddppgmehn-kn------akg
lk----------dtsknmaldilntknvctgtadptasltdvgsgahvss
vaagqkcgnksricflgltgligssvayi
>node19
rsgtakfatgnkvatkfqsqcsscsaaadqaraelgvvkagycrfelyl-
---------eetlvnvsttplp---iknsaihlgygdacyvdmtgshthe
nklcsgrlvaivge-fc--raatsgvvsghncvsrfrhplvnqgkaslah
vsvfdiy--kligth--naps--dh---grpsdknrtqtysvevklgikg
agtgldrartkci---eatssssgayyarkagnecemskahhynhfwild
trgpnskiagnqdsdrknaqcesggknvgdkfrwsettst--igkk----
--gnrek-----iggnsnmptgglgieddhtkfatvataakqpkatgngq
hdgsfgvkyldkkliflkgddsvplknsklkngsaklcrfs--yasafe-
-lvtnhancnrqygsr---higaagdtgskpyfqletmnadynrstvgfp
emdkeqpfwc--------------qvsqgqetpgsefs-kt------sks
lk----------dtsktfaldilgtknictdaadvnaslgdegsgshvss
vsagqkcgnrsrvcffgftgfiggsvaci
>node9
ssgtskfatgnkgatkfqsqcsecspaadearselgvvkagycrfdlyl-
---------eativnvcttplq---iknssihlgygdacyvditgshahe
lklcsgrlva-ige-fc--ktaasgvvaghncvsrfrgplvnegkaslah
vlvfdfy--kligth--scpa--qn---grpdaktrtntysvevklging
aatgfdrartkci---eatsdnpgayyarkagngaemskhhhynnfriln
tvgpdskiagnqasvrknaqcesggknvgdkfkwleasst--igkk----
--gnrqk-----iggssnmptdgvgieadhtkfmtvilaanqpnattqgq
hdgsfgvkyldkkliflhvddamllkktklkdgsaklcrfa--yagafe-
-lvtnhsncckqyglr---higaagdtggkshfqletmaadynrddvgfp
emdkespfwc--------------qvsqgqetpgsefs-ktsendgtskl
lk----------nstktfaldilgsknlcadaadvyasasdegtgshvgs
vsafqkcgnrsrvcffgftgfkggsvaci
>ENV_SIVM1/24-528
ssgtskfttgnkgadkfagrckkcspaadeiradlgvvkagycrfdvyl-
---------estivivctlplqaftiksdnihlgygedcfdditgshahe
lklcsgrlvs-vge-fc--ktastgvvaggncvsrfrgplveegkanlah
vltfdfy--kligth--scpa--qd---grpdtktrtntysvevklging
taagfnvartkci---datgdnpaayyardegnggemskiphyntysild
nlgpdskaagghtsvrmngqcesgktnvddkfkwleasat--igrk----
--ghrqk-----isgssnmptdgagieadhtkfvttileanqpsattqgq
hdgsfgvkylnkkfiflqvddamllkktklkdnsaklcrin--yagafe-
-lgsnhsncckkyglr---ligaaddtggmshfqletmaadysadsvgfp
emdkessfwc--------------kvshgqeapgsefs-kttesdgtskl
lk----------nstktfaldilasksvcadaadvyssasdegtgshvgs
tpafdkcgnrsrvcyfgftkfkggsvacl
>ENV_SIVV1/24-538
tsgtkchtaq---alsprtgctecpnaggetrpilsvaravycktnlce-
------dyykrsvvnncgsplp---vansylhlgkdggclinvggtcgnq
lelavg-lvs-lgtffsdagnienacellldfaghfrgeqllrtqstfiw
viafefy--elggah--ecvacrin---gktelaagnnsydagvrlalgg
gpspkdqavasca---ettpgrpgnklttkgtqgnaidtphqikr--svn
pplsnqqstgktlstreitkcewarpavgtkvkwlnvgns--lapl----
--aydhr-----igspkikhgqtvgdnddraqvnvlilavgepagirryq
dkgeiglstltmklvfdqfvcgqiltktevtpgnarlckfadcfvitfed
vlklvpsncgtnrpkqdcanvgnttatpgkthfpleragpdfqkdspsva
dmviqtafqcgrhlhnsgdgfaathtl--eglgdynyt-gttlkessqsl
ikrcctitftyyehrralaaaaltstdgnsdgsdvfitsnmqswgftvgd
vcvlskckkncrvsffgitvetgneggcf
>node18
rsgtakfttgnkvatkfqsqcsscsaaadqahaelgvvkagycrfelyl-
---------eetlvnvsttplp---yknsaihlgygdacyvdmtgshthe
nklcsgrlvaivge-fc--raatsgvvsghncvsrfrhplvnqgkaslah
vsvfdiy--kligth--naps--dh---grpsdknrtqtysvevklgikg
agtgldrartkci---eatssssgayyarkagnecemskshhynhfwild
trgpnskiagtedsdrknaqcesggknvgdkfrwsettst--igkk----
--gnrek-----iggnsnmptgglgieddhtkfatvataakqpkatgngq
hdgsfgvkyldkkliflkgddsvplknsklkngsaklcrfs--yasafe-
-lvtnhancnrqygsr---higaagdtgskpyfqletmnadynrstvgfp
emdkeqpfwc--------------qvkqgqetpgsefs-kt------sks
lk----------dtsktfaldilgtknictdaadvnaslgdegsgshvss
vsagqkcgnrsrvcffgftgfiggsvaci
>node11
rsgtakfatgnkvatkfqsqcsscsaaadqaraelgvvkagycrfelyl-
---------eetlvnvsttplp---iknsaihlgygdacyvdmtgshthe
nklcsgrlvaivge-fc--raatsgvvsghncvsrfrhplvnqgkaslah
vsvfdiy--kligth--naps--dh---grpsdknrtqtysvevklgikg
agtgldrartkci---eatssnpgayyarkagnecemskahhynhfwild
trgpnskiagdqdsdrknaqcesggknvgdkfrwpettst--igkk----
--gnrek-----iggnsnmptgglgieddhtkfatvataakqpkatgngq
hdgsfgvkyldkkliflkgddsvplknsklkngsaklcrfs--yasafe-
-lvtnhsncnrqygsr---higaagdtgskpyfqletmnadynrstvgfp
emdkeqpfwc--------------qvsqgqetpgsefs-kt------sks
lk----------dtsktfaldilgtknicadaadvnaslgdegsgshvss
vsagqkcgnrsrvcffgftgfiggsvaci
>ENV_HV2D1/24-501
rlgtpkfttgskvatrfasecvacssandqahaelgvakagycrfelyl-
---------wetqvlvsttplp---ykspaihlgygdscyvdmtgshthe
nklcsgrlqsivge-fc--raasssvvsshkcvsrfrhplvnqgkaslgh
vsvfnvy--kligth--nppk--dh---grpsdkdrsntysvelklsmka
agtgldraktkci---ektssssgayyakkngsecnmskphhykhfwild
thgpnsiiagvqdsdk---qcepggknvgdkfrwpettss--igkk----
--gnrqm-----iaghsnmpthglaisndhskfatvatgakqpkatghgq
hdgsfgvkyidkkliylkgddtiklknnklkngraelcrfs--yakafe-
-lvtnhlpcnrqygsr---htgaagdtgnkpafeletknsdylagtvqfa
emdheqpfwc--------------qvqkgqetpgsefs-kp------tkt
lk----------etsktfaldilgtknlcahaadlnasmgdegagselds
vsagqkcgsrervcffgftgfigasvaci
>node10
rsgtakfatgnkgatkfqsqcsecspaadearaelgvvkagycrfdlyl-
---------eetlvnvsttplq---iknsaihlgygdacyvditgshahe
lklcsgrlvavige-fc--rtaasgvvaghncvsrfrhplvnegkaslah
vlvfdiy--kligth--sapa--dn---grpndknrtntysvevklgikg
agtgfdrartkci---eatsnnpgayyarkagngaemskhhhynhfrild
trgpdskiagdqdsvrknaqcesggknvgdkfrwpessst--igkk----
--gnrqk-----iggnsnmptgglgieddhtkfatvitaakqpkatgqgq
hdgsfgvkyldkkliflkgddamplkksklkngsaklcrfa--yasafe-
-lvtnhsncsrqyglr---higaagdtgskpyfqletmaadynrsdvgfp
emdkeqpfwc--------------qvsqgqetpgsefs-kt------skl
lk----------dtsktfaldilgtknicadaadvyaslgdegsgshvss
vsagqkcgnrsrvcffgftgfigasvaci
>node14
rsgtakfttgskvstkfasqcvscssandqahaelgvvkagycrfelyl-
---------eetqvnvsttplp---yknsaihlgygdscyvdmtgshthe
nklcsgrlqsivge-fc--raatsgvvsghncvsrfrhplvnqgkaslah
vsvfdiy--kligth--naps--dh---grpsdknrsdtysvevklgikg
agtgldraktkci---eatssssgayyakkngnecemskshhynhfwild
trgpnsiiagtedsdrknaqcesggknvgdkfrwsettss--igkk----
--gnrek-----iagnsnmptgglgisddhtkfatvataakqpkatghgq
hdgsfgvkyldkkliflkgddsvplknaklkngsaelcrfs--yakafe-
-lvtnhlpcnrqygsr---higaagdtgnkpyfqletmnadynrstvtfp
emdheqpfwc--------------qvkqgqetpgsefs-kt------sks
lk----------dtsktfaldilgtknictdaadvnaslgdegsgspvss
vnagqkcgnrsrvcffgftgfigasvaci
>ENV_HV2BE/24-510
ssgtakftngsrastkfarqcvsctnandqahaelgvikagyctfelhl-
---------ekthvnlsakplp---hkntaihlgsgescyvdmtgghthq
nklcrgrlqsvvge-fc--rqatagvvsgkscvsrfrnpdvnqgkasidh
vsvfdiynmkliath--naqs--eh---grpsnrnkadtysvevklgikg
agtgldrektkcv---eathkakgayylkkngnactmskshhyihfwlle
trgpnsiiagtedsnrsqaqcesgatnvgqkyrwgettas----mq----
--gnreq-----iagnnnmvagglgvsdnhakfaisptaakqpkhtahgq
ndgnfgvkylnkkliflkgddsaplkdaklkngtaeicefn--hakafe-
-llghhlpcarqygsr---rigaagdtgtkpyfqletlthqynsstvtfr
emshdqpfwc--------------qvkhgqgvpgcdfs-kt------vks
lk----------dssktfpldilgtreihtdaaevgas-gdegtgspvts
vd-----gnrtrvcffgftafigasvaci
>ENV_HV2D2/24-513
rssiakfeagkkgatrfqsqcseclvaadaarnelgvvkagycrfdfyl-
---------eetlvninstepq---iksseihlgygdqcyvsvtgshahe
lslcegrlaavlge-fc--rtaasgvvasqgcvsrlrqplvneakaslah
tlgydvy--kligth--sapa--dn---gkqheknrtnpyhvevklgvkg
sgtgpeedrikcv---aattsnpgayyarkaseggelfknhkynhfhkle
tqgpdasaagaqdsvrkkarcenggknlgatrkwpnphst--iark----
--gqhak-----iggdanmpigglsieddhtkfgtvitaagqpsaegqgq
hsgrfgvkyldnkqiflkgdaamplkksslknasaglcrfa--yaaagq-
-lvtnyfnccrefgir---nigtagdegdkayfqletidadynrtevgfs
nlekeqaywc--------------qasqgqpthgneal-kt------kkf
lk----------ksaktfatdmlsaknicangadvyaslpdagsgshrts
vnsgqkcgnrsrvcflgftsfigttaaci
>node17
rsgtakfttgnkvvtkfqsqcsscsaaadqphaelgvvkagycrfelyl-
---------eetlvnvsttplp---yknpainlaygdacyvdmtgshthe
ntlcsgrlvaivge-fc--raatsgvvsghncvsrfrhplvnqgkaslah
vsnfdiy--klqgth--naps--dh---grpsdknrtqtysvevklgikg
agtgldrartkci---eatssssgayyarkagnecemskshhynhfwild
trgpnsmiagtevserknaqcasggknvgdkfrwsettkt--lgkk----
--gnrek-----iggnsnmptgglgieddhtnfatvataakqpkatgngq
hdgsfgvkyldnkliflkgdssvplknsrlkngsaklcrfs--yasafe-
-lvanhancsrqygsr---higaegdtgskpyfqletmnadynrpavgfa
emdkeqpfws--------------qvkqaqdtpgsefs-kn------aks
lk----------dtsktmaldilgtknictdtadvtaslgdqgsgshvss
vsagqkcgnrsrvcffgftgliggsvaci
>node8
ttgskafaaq---glnshnqctecadaagearpilgvakaayckenlca-
------aycnrtivtdcatplp---iknsyihlgfdeaclinlggncghd
ltlaigqiva-lgd-fcnpestessvvpvhdfvsnfkgnqllpgktglqq
vlpfefy--elagth--sctsckqn---gktelssrsdsydadvrlglgg
gasafdravagcv---eaakdssgsyyarkgspgeamskhhpfnkfrivn
plfddrdssgknfgareitecewgradvgdkvkwltagds--lgsk----
--nfqnr-----ignpaqkpadtvgdnedhnqvnslilavedpsttkrsq
htgafgmsfltdklifehvdngqlmkrtnvtpggprlcrfa--fvtsfed
slklhpsdcgedkglencnniggtsatggkkhflleavgpdferdgptiv
emvieagfscghnlynsvqgfaavqvlkgkgtsnyqys-dtthnegsqsl
vkkcipisysyyqssrafaiaalsstrncsdaedvyataglegwgfhvgs
vcgfrkcqkqcrvcffgytsanssstaci
