>node18
dnksyttkdtdfet---ksatntfhpykfkdqsrsncfehivmpyna---
-sclevp--evhyglkneflclldrrgrgtafglgvpcrplkdafrtavl
awinqq----------rmgskqaglyrattdravkvh--spkrglvayer
paprcsdlfermlalqccqlkk--fkghgqapsmagglgaqgvrlskeht
vhqvkpapyawelggnilevstaeykdaphkryksggsdfkknvwthlkr
ckkhnkltiatkmfggevelleygaldqtktlagv--rpikkgaqgsfas
qhn--fa--gleddnllvyvpeattsattarntiktpqa-----------
-gmlfiksapvtidnvdhatgvevpkfeglckqtynqslldlpvcktcl-
dckqhffdsvd--karsnfkgacn-itydvspqcsan-illvakdavlsn
avakkiyrvqyaqittgrgsq-nlsm-ekgarniggrnfpvfdksvckgn
gmqccskgptqntkecfwipghvrkcagmssgchkrwvnsnyhvswpq
>ENV_SIVV1/24-538
eenpykpclgqidy---litaknfdvaqfsqkpsggc-edkvlkyktvwg
agciayy--qicyaiavilnhmrsgkshesqftyfypchdvgghfhpvsv
ewvvhq----------kedygeipifrpsdnkndkvenrsrtksfnrlqe
pcskcetlpnnqfsinlcqkkl--lkgkasrnengtkg----icpttrvs
vlhhrpaeaawgh-aqtfkaakgayelgqlkknrasglafrrkrwdksrn
cgerkvnaifvsqfggeidltpcgdtdqnpyfravitqnvkaatqgvyvv
kdi--fsgtavkddevvffltentaqeidlrliggapefgsqgysgksgn
aggqyvkgskvppdqpqhptsvsvvsfdkeckqaytpvwlalpgcmh---
dkcae--svad--kdrenylgden-laydvssvcilr-swavlddqvikg
sceakiyrvelpefvanktcg-elnf-vkgvskctargygifskprtvlt
aksecengssnkrd-cywepphvsrcgeidksgegtwlsstydltlnq
>ENV_HV2D1/24-501
dnktyatketdfet---ksttgtsqpykfedktrsncnehlallyna---
-sclgie--dvhyglaneflclldrrgrgilfglgipcrplkdafrtavl
gwitqq----------rmgskqaglyrastdravsvh--spkpglvayer
paprcstlfehmltleccqlkk--fksdgqspnmagglgaegvrlskeha
vhqikpapypwelggnilevstadykdaphkcykslavdflrnrwtilkp
akthkkltiatkmfggqvkllqygavqqtktlggv--rpekrgaqgsfas
qqn--fa--gledenllvyvsnattsataardtietpqa-----------
-sklfiksaplvldnvdhtpgvavpkfkglctqtynnalldmav---cl-
dckqhffdtvd--karatadgpcn-ltydvspqcttn-illvakaavlsn
gtaikiyraqytnistgagsd-nlsm-ekdarniggrnypvfdksickan
gmecsrkgpaqnnkecfwipghvrkhagmgsgcngkwvgsnyhtswpq
>node14
dnksyttkdtdfet---ksatntfhpykfkdqtrsncfehiamlyna---
-sclqve--evhyglkneflclldrrgrgiafglgipcrplkdafrtavl
awinqq----------rmgskqaglyrattdravsvh--spkrglvayer
paprcsslfermltlqccqlkk--fkghgqapsmagglgaqgvrlskeht
vhqvkpapyawelggnilevstaeykdaphkryksggsdfmknvwthlkr
ckkhnkltiatkmfggqvklleygaldqtktlagv--rpikkgaqgsfas
qhn--fa--gleddnllvyvpeattsattarntiktpqa-----------
-smlfiksapltidnvdhttgveapkfeglckqtynqglldlpvcktcl-
dckqhffatvd--karsnfkgpcn-ltydvspqcstn-illvakdavlsn
avakkiyraqytqittgagsd-nlsm-ekgarniggrnfpvfdksvckgn
gmqccskgptqntkecfwipghvrkcagmgsgchgrwvnsnyhvswpq
>node10
dntsytttdadfet---ksatntfhpykfkdqsrsncfehigmpyna---
-scldvp--qvhyglnneflhllkrrgrgtafglgvpcrplkdafrtavl
awvneq----------rtgskqaslyrattdrsvkvh--spkrglvafer
paprcsalsermlalqccqlkm--fkghgdapsmsgglgaqgvslsneht
vhqikpapyawelggnilevstgeykdaphkryksggvdfkrnvwthlkr
ckkhnkltivtkmfggevelleygaleqtktlagv--rpikkgaqgsfas
qhn--fs--gleddnllvyvpeattsattarhtiktpta-----------
-gvlfiksapvtidnvnhatgvdvpqfeglckqtynqslldlpvcktcl-
drkqhffdlvd--karsnfkgacn-itydvspqcnln-illvvkdavlsn
avakkiyrvqysqittgrgsq-nlam-skgaknitgrnfpvfdksvckgn
gmqcctkgetqntkecfwapghvrkcagmsggchkkwvnsnyhvnwpq
>node19
dnksyttkdtdfet---ksatntfhpykfkdqsrsncfehivmpyna---
-sclevp--evhyglkneflclldrrgrgtafglgvpcrplkdafrtavl
awinqq----------rtgskqaglyrattdravkvh--spkrglvayer
paprcsdlfermlalqccqlkk--fkghgqapsmagglgaqgvrlskeht
vhqvkpapyawelggnilevstaeykdaphkryksggsdfkknvwthlkr
ckkhnkltiatkmfggevelleygaldqtktlagv--rpikkgaqgsfas
qhn--fa--gleddnllvyvpeattsattarntiktpqa-----------
-gmlfiksapvtidnvdhatgvevpkfeglckqtynqslldlpvcktcl-
dckqhffdsvd--karsnfkgacn-itydvspqcsan-illvakdavlsn
avakkiyrvqyaqittgrgsq-nlsm-tkgarniggrnfpvfdksvckgn
gmqccskgptqntkecfwipghvrkcagmssgchkrwvnsnyhvswpq
>ENV_SIVG1/22-522
degqyrgcdgqvey---nivaksfdvykfsqkqsagcfehkvlsydcvwg
pgclayy--qihytvgillnhqrkpkghekefsyifpckqlqahfrgvvm
ewvvhq----------resysespiyrpgdnksekvh--artkglnrldk
pcsrcntipykllgiplchlnl--lkgkakrpgddnde----vclstrvt
vvkvrpvgcawpm-apsfknkkgeyaegdlkrhpigglafrrhhwtkssh
cgqrkisvifarqfaseidlsscgeaenssavvgiachstkgagqgvyva
adifgfsgtavsddqivfyltenparttnlrvgsgapee-----------
-gvlyvkgskvspdepehrttvaapsfekdckqaysgvwvqlpscirifl
dkste--dvvp--knreaylpddn-ltyqvlsecalr-awavlnesivas
tcpkkiyrvplppygagktcg-elsf-tqgekqcaahdyslsakprsvmt
akkvcgegehtgre-cyyapphgtrcneiddsgeqewlhstydlsilq
>node9
dntsytttnadfet---ksatnafhsykfkdqsrgncfehiglpyna---
-scldlp--qvhyglgkefnhllkargrgtafglvvpcrplkdafrtavl
awvneq----------rtgskqasyyrattdrsvkvh--spkrglvtfdr
paprcsalsermlalqccqlkm--ikgnedspsmdggagaqnlclsgqht
vhdikpasyawalhgncleastgeykdaahkryksggvdfkrdvwtrlkr
ckkhnkltivtkmfggevelleygaleqtktlagv--rpikngaqgsfas
qhn--fsgygleddnllvyvpeattsatttrhtaktpta-----------
-gvlfiksapvtidnrnhstgvdvpqfegackqtynqtlidlpvcktcl-
drkadffdlvd--kargnfkgacn-itydvspqcnln-illvvkeavlsn
avakkiyrvqysqittgrgcq-nlal-skgaknitgrnfpvfdkskcssn
gmqccskgetqnnkecfwapghvskcagmsggchdewvnsayhvnlaq
>ENV_SIVGB/47-569
taacyrraegsgksegg---kaqfelykyretsrescfgngqigyea---
-lcgtlq--galyangvwfgtlngttgfniqfalitpcrpkncefpgsaf
swvlkh----------snqyegsgvykkgknaklgve--drrptlhkapg
pskecnkaaqktitsnqfdddlkqek-kdilanhfgvp----pcnektip
vrkpkpgdttsyy-gsef-----ayedgatekektgsfifgrekrvkerp
ciaksvgalvsskltgacqveg---athtttaaappeqarhrfpraalpa
svi--fkttga-anvlplyhtaagdpirsldtshtngeh-----------
-g-------ktgpnsqepaaqltspafkkacsqarendtlalttcvsls-
eaheylhnlad--sgwigslseqa-laiksvsdsels-vkqslrkqilpg
vfakkkhq--lgeihshtprm-elafevqtvkgalagtfwlfhglghala
vksrtgfgearkdg-aywkadhdddccdgeaqgyrlplpsqdefsfpa
>node8
daaeyrgspghvdt---kitansfdvykfsqtprggcfdhkvlnynt---
-aclala--qihyavgilfnhmkkpkghekdfayiipcrplqahfrgavm
awvihq----------rhqyseapiyrpgknksekvh--srkkslnrldk
pcsrcnkiphklfpislchlnl--lkgkdaspsvdnge----vclstqit
vhivkpvsctwpl-gsafkstkgeydegdlkryrvgglsfrrkrwtklrh
cvdhkiavvlarqfageidleayggtehvsaiagvtchaiknaapgvyaa
qel--fsgtaldqdaivlyltetgartttlreasgtpeh-----------
-gvlyvkgakvtpdgpehrtgvaapefnkdckqaytgdwvalpacitia-
drsteffdlad--kdrgnyigdad-ltydtssecels-illvlkeailpg
acpkkiyrvqlsqigsgkacq-nlaf-mqgeknctgrnfplfdkarsvmt
akkccgkgdnhkne-cywapghvtrcaalddggsqdwlhsayelslaq
>node11
dnksyttkdtdfet---ksatntfhpykfkdqsrsncfehivmpyna---
-sclevp--evhyglkneflclldrrgrgtafglgvpcrplkdafrtavl
awinqq----------rtgskqaglyrattdravkvh--spkrglvayer
paprcsdlfermlalqccqlkk--fkghgqapsmagglgaqgvrlskeht
vhqvkpapyawelggnilevstaeykdaphkryksggvdfkknvwthlkr
ckkhnkltiatkmfggevelleygaldqtktlagv--rpikkgaqgsfas
qhn--fa--gleddnllvyvpeattsattarntiktpta-----------
-gmlfiksapvtidnvdhatgvevpkfeglckqtynqslldlpvcktcl-
dckqhffdrvd--karsnfkgacn-itydvspqcsan-illvakdavlsn
avakkiyrvqyaqittgrgsq-nlsm-tkgarniggrnfpvfdksvckgn
gmqcctkgptqntkecfwvpghvrkcagmsggchkrwvnsnyhvswpq
>ENV_HV2BE/24-510
dqkdyttsdtdfet---ksatnafqpykfkeqtrsncfiqiymlyna---
-ncltve--evhyglknaflclldrrgkgiagglgipcrplkdafrtavv
dwinqg----------qmhkkqaglyrattdravsvh--sqkrgivayek
paqrcsslfevvltlqccqlkd--fkghaqapamesglgaqgvrlskehr
vhqvrpasyawelggnildvstnevkdsphktyknggsdfgntvwtalkk
cnkhnkltialkmfggqaklleygalsqtktlagv--rpikkgaagsfas
qhn--fa--gfedddllvyvpaatdspikgrntittpqa-----------
-smlfiksapltvdlvehttgvevpsfeglckqsynqglldlavckgcl-
dcqqhffatvd--kardnfkgpcn-ltydvgpqcsta-if-------lsd
avakkiyraqytqqttgaqvd-nlsm-ekggrniggqnfpvfeksvcngn
glqcaikgptqntkecfwiplyvskcsgmgsgcrkqwlesayhvdwpq
>ENV_SIVM1/24-528
dagsyltvnadfen---ksatnefhsykfkdqsrgncfehiglaytq---
-ssidap--evcaglgkefthlhqakgrgtafglvvpcrtlkdafrtavl
awineq----------rtgnkqegyyratteksvkah--spkrglvtfdr
paprcsalssrmlalqccqlkm--ikgnedppsqnggggaenlclagqhs
vqdikytsyawalhgncleantgeykeaahkryktagvdfkseiwtllkr
ckkcnkltlvtdlfggevelleygvleqtkalakm--rpikkgaqgsfas
qhh--fsaygleddnllvyipeattsasttrhtaktpta-----------
-gvvfiksarvtidhrnhssgvdvpliegkckqlysqtli-----ttcl-
erkadffaaveadkargnfkgacnlitydvspqcsln-vllvaneavlyn
gvakniyrcqysqiatnrgcr-nlal-skgaknitgqgfpyfdnskcasn
gmqcsrkgetqagkecfwapghvskcagesggchdqwvnsayhvslah
>ENV_HV2NZ/24-502
enksyta----------vgntntfhpskfkdqrrpaclqhdvmpska---
-lclsvp--evqyglknaflclldrrgngtafgvgvpcrplkdafraavv
swvhqeclpapshhirrlgskqtglyravterqqkvh--spkrgllayer
paprcsdlfkrmmaleccqlkk--fkghgqapsmsgglgaqgirlsmehf
vhqikpnpygwefggvvlevktaeykdtpedsyksggsgfkkavwtqlgr
ckkhnkftvatdmisgevslleyaaldktktlagt--kpitkggqgafss
dhn--fa--glanesllvyaseatiavasaretiktaqa-----------
-gllfidnapvtvdnvnhptgiqvakfeglcnqtlrqpalklpvcntcl-
dykqhffdsvd--kdrgnfkgagn-inyditppcsad-illvakdavlap
avpkkafrvqyaqittgrglqknlgm-hkgarnigghnflvfdasvcsgn
gmqccskgpsnntkecfwlpgvvpkcanmssgcdkqwvnsnyhvgwpq
>ENV_HV2CA/25-512
dnksytskdtdfek---ktatnpfhpykfadqtrsscfdrivmpyka---
-kcleap--evhyglkkeflclldrkgrgtafglgvpcrplkdafrtmvl
swinqq----------rmgskaagmfrtttnkqveve--spkrsllayer
atpacsqlfemmlamhccqlkk--fkghgqapsmtgklgaqgvrlsnest
vhqvkpapygwelagnvikvitasykeqphkrhtgggsdfnknvstklkr
ckkqnkltiatkmysgevalleygaldqvktlagr--rpikkgaqgsfas
ehn--fa--nlenesllvfvstattaatvardsietpqg-----------
-vllfaksapltidnvdhttgvevskfqglckqaynqallelpvckacl-
dckhhffdsgd--kkwsyskgacn-itydiqa---as-ivnvvrnavlss
svakniyrvqyaqvttgrgsq-klsm-ekgarnlggrnfpvfdktvcegn
gmnccskgptqetkecfwipghglkctgmvsgcdkqrvnrnfhvswpg
>node17
dnksyttkdtdfet---ksatntfhpykfkdqtrsscfehivmpyka---
-sclevp--evhyglkneflclldrrgrgtafglgvpcrplkdafrtavl
awvnqq----------rmgskqagmyrattdrqvkvh--spkrgllayer
paprcsdlfermlalqccqlkk--fkghgqapsmsgglgaqgvrlskeht
vhqvkpapygwelggnvlevstaeykdtphkryksggsdfkknvwthlkr
ckkhnkltiatkmfsgevalleygaldqtktlagv--rpikkgaqgsfas
ehn--fa--glendsllvyvseattsattardtiktpqa-----------
-gmlfiksapvtidnvdhatgvevpkfeglckqtynqplldlpvcktcl-
dckqhffdsvd--kkrsnfkgacn-itydvspqcsan-illvakdavlsn
avakkiyrvqyaqittgrgsq-nlsm-ekgarniggrnfpvfdksvckgn
gmqccskgptqntkecfwipghvrkcagmssgcdkqwvnsnyhvswpq
>node7
desqyrgcdgqvdy---qitaksfdvykfsqkpsagcfehkvlsyntvwg
pgclayy--qihyavgillnhqrkpkghekefayifpcrelqahfrgvvm
ewvihq----------redysespiyrpgdnksekvh--artkslnrldk
pcsrcntiphklfaiplchlnl--lkgkasrpaddnge----vclstrvt
vvkvrpvsctwpk-asafkntkgeydegelkrhrvggltfrrkrwtksrh
cgdrkiavifarqfageidlsacgdaehssaivgvtchsiknaaqgvyva
adi--fsgtavnddqivfyltenparttdlrvgsgapeh-----------
-gvlyvkgskvspdepehrtsvaapsfdkdckqaysgvwvalpacikial
dkste--dvad--kdrenylgddn-ltydvssecalr-awavlkesilpg
acpkkiyrvqlpqfgagktcg-dlnf-vqgekectgrnyplfakprsvmt
akkccgegennkre-cywapphvtrcseiddsgeqdwlnssydlsllq
>ENV_HV2D2/24-513
dntnytvtdadyes---kesthtgnpykfkntsssscmkhiglgysa---
-gclnlkdrqlhyvqndekltqlkrsgtgtvfglghpcralkdafrivvl
afvkee----------itgnnqaklirattkqsvkih--spkkglvafir
pgpattalqerqlalqscqlrl--fkgngdapskaggiasrgvnltnehi
sqevksrpynyelggdlhevstgeykdephkrykgraiefkrevwthlkr
ckkhnkltivtkmfgsevdllhygalehtkalagv--ppikngaqgsfas
qnd--is--vldednllvyvpqattsasdakhtikvaaa-----------
-givfmnsspvtidntdhatgidvpetqgfckqgysqgllelpvcktcl-
drkqhffslad--rarsslkgacd-itldvtpecylnlillvagdailkd
tvakkrysvqytqnttgrgsp-hlam-nkggknikgqhfqvfsksvckgn
gmqcstkaetqktaecfwapgsvykcagmsgscakkwvdsnyrvhwpk
>ENV_HV2G1/23-502
dnksytikdtdfet---ksaantfhpykfkdqsrsncfecivmsyta---
-sclevp--evhyglkneylcllekrgrgtafglavpcrplkdafraavl
awinqq----------ktgskqaglyratrkravkvh--spkrslvaydr
paprcsdlfqrvlalqccqlkk--fkehaeapdsaaglgaqgvrlskehs
vhevnpapyawelagsslevnsteykdaphkkykagevdfkkniwthmkr
ckkhkkftiavkvfggdvslleysaldqtktlagv--spikkgaqgsfas
qhn--ya--glendnplvfvpepntssstarstiktpta-----------
-vqlfiksapviidnvdqatgvvvpkfeglckqtynqslldlpvckacl-
dckqhffdrvd--karsnfkgyid-isydvspqcsen-illvvkdavlsn
avakkiyrvhyaqittgrgsq-nlam-tkgarniggrnfptfdksvckgn
gmvccskgptqngkecfwvsghvrkcagmsggchkrwvnsnyhvswpq
