>ENV_SIVM1/24-528
lnetsda---flpscktdkssnkhkftrtlnla-ed--skletltrgnfv
havptktdfiasgyktslyek---l-vmisgdgasgrg-kllkddihqnd
keareihgpqisitkhavaegasdyqdepsgnr-tvc---paak----gr
prlllkacpnselllkpprdssrtldrishlphksmapvgllkrkp----
atakitfhsltyasatalgvagr--fkgasgpvqvsgpska-----trss
cakcmflkpalklih--kpgvatlfllekhpagteprslsriyvfnkkkq
earnpchkktgplessmiarqaadfygydtvnrkghpagaihgkmghaal
lveakglcnkvgraqracepvckqsva-khlglf-gsekydadstamfks
atptapteelcsdgrrghagkgeql--kvcldsdgqevrifvlvarkktl
nylkvvnhyewkn-p---splgc--eaa------i---sggkkmvgdepk
gligvskpaanavgthlpsagkvtqslspfdtqvrlpapiinanhgkh
>ENV_HV2D2/24-513
akdtsat---yldhcknqkasnkhpygrnmdll-ed--skwkgmkrgkfv
vaeatrteftyagyilsmfdr---l-vltsgsgildrtpkllkrnihqnq
hgtpdlpgpqeqivkhavaggsddyqrrpssqs-nvn---sgar----gr
palflkvcahkglllkpptnehgtlqryshlphecmvtvallkrrplthv
asvkltfhdlgsasinhlvtpdq--ykgadgavk--hssia-----saaa
yakkaflkppvilah--kpglatvfkidkhclggathglpriyalnkkke
ndfnqchkksgpltgsmiardaknafgygttarnnhpkefqhgksgkevl
lkdgkgacatigraerycdatckesvatkhlglf-gpkkysagp---fkr
atesatveelcaeikkgdngkgell--ivcvqcngiedrifvliarvkaw
tylrltdhldskn-p---splss--qad------s---lggkkiigdess
slvgtskpdasavgthirsagkvdewlspp-tevklpapeieanhnkh
>node11
akessat---ylpdckgqkasnkhkyaqlmdla-ed--skwkaltrgkfv
vavatrteftyssfklnlfsk---l-vmtsgtgaldrt-kmlkdkihqnq
hhapdlpgpqisitkhsvaggasdyqdrpngsr-nvs---pgak----gr
pklllkvcpnkglllkpprnssqslqryehlphkcmapvallkrrp----
atvkitfhsltsasvdplviphr--fkgaegtvkvmgasia-----saaa
yakcnflkpalklih--khgmatvfklekhctgaapqslsriyafnkkrq
gefnqchkksaalegsmiareaadafafdtvnwkgnpateahgkmgldhl
vaeakaacaksgraerycdaickespatkhlglf-gsdnysadatavfqp
atpaeeaeelcadvkkghngkaeql--kvcvdssghsnrifvliarkktl
nylrlvnhydsnn-p---splgc--ead------srcwtggkkivgdepk
slvgvakpeanavgthirnagkvkqwlspf-tevrlpapkidadhnkh
>node17
akessat---ylpdckgnkgtndhkyaqlmdla-ed--skwkaltrgkfv
vavatrtdftyssfklnlfsk---l-vmtsgtgaldrt-kmlkdkihqnq
hhapdlpgpqisitkhsvaggaskyqdrpngsr-nvs---pgak----gr
pklllkvcpnkglflkpprnssqslqsyehlphkcfapvallkrrp----
atvkitfhslttasvdpavvphr--fksaegtvkvmaasva-----saaa
yavcnflkpalklih--kkgmatvfklekhcggaapvtlpriyafnkkrq
gafnqchkkssalegsmiarealdafafdtvnwkgppateahskmgldhl
vaeakaacaksgrgerycdaicsespatkhlglf-gsdnysadvtavf--
-tpaeeaeelcadvqrgnngkaeql--kacvdsnghsnrffvmitrkktl
nylrlvnhydsnngp---splgc--ead------srcwtagkkivgdepk
slvgvakpeahavgthirnagkvkhwlspf-telrlpapkidadhnsh
>node10
aketsat---ylpdckgqkasnkhkyarnmdla-ed--skwkaltrgkfv
vavatrteftysgyklslfsk---l-vmtsgtgaldrt-kllkdkihqnq
hhapdlpgpqisitkhavaggasdyqdrpngsr-nvs---pgak----gr
pklllkvcpnkglllkpprnssrslqryshlphkcmapvallkrrp----
atvkitfhsltsasvdplvipdr--fkgaegavkvmgasia-----saaa
yakcnflkpalklih--kpgmatvfklekhclgaapqslsriyafnkkkq
gefnqchkksgplegsmiareaadafgfdtvnwkghpansahgkmglevl
laeakgacaksgraerycdpvckesvatkhlglf-gsdsysadptaifks
atpaadaeelcadvkkghngkgeql--kvcvdssghsnrifvlvarkktl
nylrlvnhydskn-p---splgc--ead------s---sggkkivgdepk
slvgvakpeanavgthirsagkvkqwlspf-tqvrlpapkieanhnkh
>ENV_HV2D1/24-501
vkessat---ylpdckgapptnkhkytqlmnlaled--skwnaltkgkfv
iavatrteftyspfllnlfkr---i-vmtsgsaildrt-kmikdkihktq
hhapelagppisitkhsvaggatnyearpglnr-nvsensggak----gr
pkllvkvcphkvlllklprnasqslqnf----hkcmapvallrrrp----
atvkvvasgltsarvdpiviprr--fksaegtvkvmgpsta-----aaas
yfkatflkgamklih--kqpmatvfkldlncggaepqslpriylfankrq
gafnechkksaalegsmiareatdsfafdtvkwkknpgteahgkmgndhl
vaaastacaktgraerycdalckeppaskhlglf-gsdnysadvtlvfrp
avpteyaedlcanaqkgnngksdql--kacvdssghfnrffvmitrgktl
kylrlvnhydsgk-p---aplgc--dpkdedpgdstcwnggkkvagtepa
hlvgvakkaanavsthivsagkvkqwlssf-tegklpapkidsehnkh
>node18
akessat---ylpdckgnkatnkhkyaqlmdla-ed--skwkaltrgkfv
vavatrteftyssfklnlfsk---l-vmtsgtgaldrt-kmlkdkihqnq
hhapdlpgpqisitkhsvaggasdyqdrpngsr-nvs---pgak----gr
pklllkvcpnkglllkpprnssqslqsyehlphkcmapvallkrrp----
atvkitfhsltsasvdplviphr--fksaegtvkvmgasia-----saaa
yakcnflkpalklih--khgmatvfklekhcggaapqslpriyafnkkrq
gafnqchkksaalegsmiarealdafafdtvnwkgnpateahgkmgldhl
vaeakaacaksgraerycdaickespatkhlglf-gsdnysadvtavfqp
atpaeeaeelcadvqkgnngkaeql--kacvdssghsnrffvmiarkktl
nylrlvnhydsnn-p---splgc--ead------srcwtggkkivgdepk
slvgvakpeanavgthirnagkvkqwlspf-telrlpapkidadhnkh
>ENV_SIVGB/47-569
ahialgaecdpmpwskgnkcekdhatdynvnle-tldtsqfnkartnkmt
lgrtlaaatfmaalkphlygkdgalkvhekgarwmalv-ievcaknstta
mkkdkleavvlgltlpdsrndygdfpkegkgqsgtei---lsas----sq
pksgasqckqsrlllknnykdandvqiltsgvdsgrlvaafrsrls----
kaiagfkktlkfefygglvespq--llfpsgklamtssttgvnavgrnpn
yvqaarlkipagptkacldpapviiallseciaqvtnkltttragtftah
pkwqicfdvaeplsltnmnadlelrfgl-tmknlhhethtvhfnlmysyh
atsgsvsctkqgvinlacdrqyacvikvkilrlfsghvnyinvkrqllws
tyk---gggirrealerppcndapkmaksadayqheacirfffpqmhsaq
dylrvvpsynqkn-crsavsketcleng------l---fhvd---gppys
ntsnlhpfllkqvyvfkgkdehvllppdhfcavmhlatailagrdgdl
>ENV_HV2NZ/24-502
ikqssat---ylpdhkggkgnndakyaqlmela-kn--pkwkalargkfv
vaiqtktefcyssfklnlfsk---l-vlttgtgaldrt-kmlkdkihqnq
hhgadlpgpkisitkhsvaggaskyhdrpngsr-svs---pgak----gr
pklllkvcpdkglflkpprnqaqglqpykllphkcfapvtllkrkp----
atvhitfhsqttasldppliphr--fksaegtvkvmaasms-----aaaa
yavcnflkpalkllh--skglatvfklekhcggaapvslsriyafnkkrq
gafnqchkksktlegsmavrydhdtfthdtvnwkdppateqhsemgndhl
hpelkavcaksgrgerycdaicsespatknlglf-gsdnysadvtavf--
-tpadeavilcaeiqrgnqgkaeqi--kacidsnghstrffmlitrkktl
nylrliyhyenytgp---splgc--qnq------srcwtggkkivgdepk
clvgvakpeahavgthirnagkakhwlnaf-telrlpapkidsdhnsr
>ENV_SIVG1/22-522
eknlhgp---vlp--iaknttsqhktrknkqle-eelpakwdaldkgkvi
eaakagdanfkpgfnaglynr---lvivtkggaalgnt-rlcshkengkk
kaaresaepevtlvdrseredhtdyqksaakeklsif---vpak----gs
aqvvqrp--lkdlmlrpqleteklvqhlshneqkckgllglvgkmp----
ecvgiltqslt-pscvilvitgk--vlipygslgtvgtpsqgqpyagtpn
hkrvmylkmamrlvn--epnpgalfalqkfctgvaskelaqgtlrkkkvv
qssslchsrgpdldptiivkqadkvvdfvaqtrrdhpvetsqkkmmyerq
ldepkepcpreesggrycerissavtnakglslf-ghpnfevpseallwg
afsagptgelcvngmrgsgsdggpl--kgctdfspdvctlyvtvhiksvf
tfmrvagqygwrd-d---ggfegpleev------i---vsek---gpeik
savdttlfdpdsaevhlstgtktilstvpfcaqvripapvthikpqad
>node8
ekhvnga---ilpcckgkkvssqhkirknlele-evltakwealdkgkvi
vaikasdanfkpgfkvelydk---lvirtkggaalgkt-rlyehkihgkq
knakeltdpeitvvartareghtdyqkeaggaklsis---aaak----gs
pklvkkpckkkelllrpqlntaksvqrfsysphkckgvvglvtrmp----
ecvgvfrqslkyasvavlvitgh--llipygplgtqgtppqghaggstpn
ykkimflkeasklih--hpgpsslfklqkhctgaaskelahgllrhkkkq
ssssqchsrgpglepsliarqaddifsfatvskkshpveashdkmmyenq
leegkgpcakdgagerycericsaivntkqlslf-ghlsfaapnqallwg
afsaeptgelcmdsmrangedggpl--kgcgdfsgdscslfvivhrksvl
dflrvvpqyewkd-p---geneapleee------i---vsgk---gpqfk
slvqlslfeadadgvhlssgnkvvlslapfctqvrlpapvinakpnkh
>ENV_HV2G1/23-502
akassat---fvpackgqkasnkhkyaqlmdla-ed--skwkaltrekfv
vavatrtefkfasfkvnlfsn---l-vmasgtesldrt-kathdkqhene
hhapdlpgpqisitkssvtggaspyrdrpngsr-nvp---pgkk----gr
pklnlkvcpnkglllkpprnssqslqryqhlphkcmapvallkrrp----
gtnkivfhslttasvdplvvpha--fkpaegtvkvmglsia-----saaa
fakcnflkpalkltc--kpgmntvfrlethctgaaqqslsriyvfnkkrq
gefnqchkksavlegsmiakeaad--gfqtvnlrgnpatdahgkmgldnl
vseakaacadsgraerycdaickespptkhlglf-phinysadattglrp
atpaeeieelcadvkvkhngkaqql--kccvaksghssrifvliarnitl
nylrlvnsydwnn-p---splgc--ead------drcwtggkklvgdepa
nlvgvakpeanavgthirnagkvkhwmnpf-aeaklcapkidadhnkh
>node14
akessat---ylpdckgnkptnkhkyaqlmnla-ed--skwkaltrgkfv
iavatrteftyssfklnlfkk---i-vmtsgtgaldrt-kmlkdkihqnq
hhapdlagprisitkhsvaggasdyqdrpqlnr-dvs---ggak----gr
pklllkvcpnkglllkpprnssqslqnfehlphkcmapvallkrrp----
atvkitfhsltsasvdplviphr--fksaegtvkvmgassa-----saaa
yakanflkpamklih--khgmatvfklekncggaepqslpriyafnnkrq
gafnqchkksaalegsmiarealdafafdtvnwkknpgteahgkmgldhl
vaeaktacaksgraerycdaickespatkhlglf-gsdnysadvtavfqp
aipaeyaeelcadaqkgnngkaeql--kacvdssghsnrffvmiarkktl
nylrlvnhydsgn-p---splgc--esd------srcwtggkkivgtepr
slvgvakpeanavsthirnagkvkqwlssf-telrlpapkidadhnkh
>ENV_HV2BE/24-510
etessat---ylpdckgtkrtdkhkytqlmnla-ed--skwkglfrgkfv
vavayrteftysafklklakk---i-vmasgsgaldrt-kmlndkihqnq
hhapdlagpplsitkhsvaggssdyqdkplfdr-dmp---egak----gr
sklllkvcpnkglllkpprsssqalqtfehgshkcmspvallkrrp----
atlkitfhslssgsvdtlvepsr--fkcaqgsvkvmgatsa-----saaa
flpadfllpaqklih--khgmavvfkieqncgstepqtlpriyafnnkkq
gsfnqcqkkndalqgymdtrealdafafdtvnwkktpgteghgkmalehl
vaetktacaksgraeqycdaickeapaskqlglf-grdnyladvpavfqp
aipaeyaqelcadaqkgnnvkaerl--kacvesngqsnrffvkiarkktl
nylnlvnhydsgn-p---tpkgc--dse------sqcwtgggkivgtepr
tyvgvgkkeshavsthvrnagttkqwlsty-tdlrlpvpkfdadhnkh
>node19
akessat---ylpdckgnkasnkhkyaqlmdla-ed--skwkaltrgkfv
vavatrteftyssfklnlfsk---l-vmtsgtgaldrt-kmlkdkihqnq
hhapdlpgpqisitkhsvaggasdyqdrpngsr-nvs---pgak----gr
pklllkvcpnkglllkpprnssqslqsyehlphkcmapvallkrrp----
atvkitfhsltsasvdplviphr--fkgaegtvkvmgasia-----saaa
yakcnflkpalklih--khgmatvfklekhctgaapqslpriyafnkkrq
gafnqchkksaalegsmiarealdafafdtvnwkgnpateahgkmgldhl
vaeakaacaksgraerycdaickespatkhlglf-gsdnysadatavfqp
atpaeeaeelcadvqkgnngkaeql--kacvdssghsnrffvliarkktl
nylrlvnhydsnn-p---splgc--ead------srcwtggkkivgdepk
slvgvakpeanavgthirnagkvkqwlspf-tevrlpapkidadhnkh
>ENV_SIVV1/24-538
ekhlnqa---idpcckgkditaqhkiakkknln-ellvskwdaldrgklq
vdmkqkdahfkpgfsamlykk---ttistkgattlggs-rlcahkihgdv
taskkqaepeitvvanseresneeyekedgegklgip---fagk----ss
pelvkpe--lkqvlykrqldnersvqrlsycshrckgvlglaekmp----
qclgnltqslstpvcpllvikgtrlrllpfgpiatvgspaggqryagtvs
ekkimfwkeaghlas--qpgpgsmfrlqkfcsgapskelahgllsnkkmv
etadqcrnkgpdlepalivkkgdkqlnamnlsrkdkpvasnhaklsyekq
lekgkeecsmqdsggrycqfvcapvvsthglgif-gtltfvasneallwa
kfgagatqgfcltnirgdgtdagnl--kgcgdyssqgctlffavsiknlf
lfmrvapqygwkg-d---gtkevelpaq------i---lsek---hpnik
tpvklplfdldgtashlssgdptvlsetafceqarisapvahitpngh
>node9
lketsat---ylpsckgekasnkhkfarnldla-ed--skwealtrgkfv
vavatrtefiasgyktslydk---l-vmtsgdgalgrt-kllkdeihqnq
kearelpgpqisitkhavaegasdyqdhpngsr-nvs---pgak----gr
pklllkscpnkelllkpprnssrslqryshlphkcmapvgllkrrp----
atvkitfhsltyasvdalvipdr--fkgadgpvkvqgaska-----saas
yakckflkpalklih--kpgmatvfklekhcvgaapqslsriyvfnkkkq
eernqchkktgplessmiareaadfygfdtvnrkghpansahgkmghevl
laeakgacaksgraerycepvckesvatkhlglf-gsetysadstaifks
atpaapaeelcsdvkrghngkgeql--kvcldsdghsvrifvlvarkktl
nylrvvnhyewkn-p---splgc--eae------i---cggkkmvgdepk
slvgvskpeanavgthlrsagkvtqslspfatqvrlpapiieanhnkh
>node7
ekhlnga---ilpcckgknvtsqhkirknkqle-etlpakwdaldkgkvi
eaakageahfkpgfnvglydk---lvirtkggaalgnt-rlcehkihgkk
kaakepaepeitvvarterenhtdyqkeagegklsis---vask----gs
pelvkrp--lkelllrpqldteksvqrlsysphkckgvlglatkmp----
ecvgiltqslkypscpvlvitgr--vlipygplgtvgtpsqgqpyggtpn
hkkimflkeasrlvn--epgpstlfklqkfctgaaskelaqgllrnkktv
qsssqchnrgpdldptlivkqadkvldfanqsrkdhpvetshekmmyerq
leqgkepcpredsggrycervcsavvntkglslf-ghlnfvapneallwg
afsagptgelcvngmrgngsdggpl--kgcgdfssdsctlfvtvhiksvf
efmrvapqygwkd-n---geneapleee------i---vsek---gpeik
spvqlslfdpdsagvhlssgdktilstvpfcaqvripapvthikphad
>ENV_HV2CA/25-512
akessat---ylpdckddkgandhkyaqlmkla-nd--skwkgltrgklv
ihvttktdytyssfklalfak---l-vmtdgtgaldtt-tllknkvhhnq
hnapnlpgpqisvganavaggasksqnrpngar-nvn---ggaklvrngn
aklllevcpksglvlkpprdtsqslqcyehlppkcfapvallkprp----
atvkisfrclsnaavdpavvphr--fksvegtpkvvtasva-----saaa
yavcdflmaalklih--kigkthvfklekhignaapvklpriyafdkkre
gpfeqchkkssaleasmiarealdafafdtvnwkgqpgtephtrmgldhl
vaeakaacdksgrggrycdgicsetgdikhlglf-gpddysadvtavf--
-tpaeeaeelcgdvqsgnngkneel--kacvdeagnsnrffimitkkkil
nylrllnhfeapagp---splgc--ead------sqcwtpgkkivadepn
slvgvakpeahildehtrnagkvdhrhspf-telrapapkvsadhnkh
