>ENV_SIVV1/24-538
fkklwaaddlgaldvnigipvsgfailvmeikaengylglvktqnsrfif
aydgs-tne----aavs-slitlfpnv---vlghv-clengk-liwsilm
pvkafsltttlkgveaggetfiiqvggvhqeahscvklltfdkrldlagh
giacdhkrsdvlpsgkkdteknavseiih-----------levneagkcc
hvvlekvde------iieldgwnciaftwrqfmkdnysqaktsdcctyyp
gantdpyglaasiavedanvtgqan--knlnpvvrvphvgsenvnvekyt
krnghntcdrlfagnnrvvstaehlcflaygekepwmmcseqagpllhkw
falsdg-sfvcs--eavkcakfsgffvvnawiekcdhpnlttynvinggr
npavpnstsgdygstpndprlggflgkaeiakavglqqstslrnfqfcdn
glkq----kfeelqcsehkprdvcvpapcmciilrkirgpalwwtcpall
sqlgsalatpstrnegrkellaqtmcdehvalydscfq--sgsamayfe
>node18
fvhewkadclgpfeayvftstntffhvslqielrngflalpeiqe-----
alaaa-asefldaaglh-klnhlatds---slaia-canfgr-lfwdgvh
gfseitvkislkainmvgvgmd--pagshsagydgvkqklydgkvelvss
kgisnaircktvdgakddvgpgamqalvc-----------ldtsagakcc
efvvgslnv------lldldgwlcgd-klrlyvndgfaleqdvdcclyck
eynanafgmrigaildegqlq-aaktvnvfhaftqqpalpdsthafqlyk
kktgritkdcllkksyrlfqlafklfffaygckpkwvavfdatnclvnkw
fgllng-kfvgh--gvsr--klsgytlledwflkpdkgdwvhykgyqggk
rpklplaisgdtgtngsksqagpirlkpkapkgagahantglkgfnlcer
gmdp----diqytdhsdskgegpckrkpclsltrrqvpgvaaertceipl
aelgsalkagpayha-----laqticgniamlctergl--asisscffv
>ENV_HV2D2/24-513
fvhewkrdclgafeayvfsalngffhsvlqidfrngylenpelle-----
alfsa-sseflegagle-llkhsasda---klhia-ctnfgr-lfwdsak
gfseitakivlkarnkvgvgis--pqdrhnpgfngvkemlyagkfelvgs
dgisnavrcssmanakecvgpkaiealmc-----------lnisagpkcc
tlvvsslnv------llrldgwlcge-clrlytrdafeneqdvgcclfck
dylvntfgmrigaildegele-apntvhifaalsqqplmpdrshafllyi
kkygkkkkdillkksfrlfqlafkmffyvygctplwvaafaatdclvnkw
fahled-kfvgn--diar--klsgytlledwtlkpgdgdwihykgyhggq
rpkvplaikgnagtgsrrnqagsimlskmapksagahatvglksfnlcer
ginp----dheytehsnpkgsgpcsnkpvlslasdqvpgtatdracevpq
tqmgpalgagpcyrv-----lvenicgdtnllctdtsm--aaiksifmv
>node7
fkklwgadslgafnanigipttgfhilamevtlqngylglvqvqesrftf
alggs-tnq----aals-glihlfenv---vlgtv-cieygk-liwsill
pvkafslqatlkvvniggetmvsqvggthqddhecvklltfdrkldlagh
gmacdhkkcdvvssskkdtsknaireivh-----------lavsaggkcc
hvvvgdvna------vieldgwdcidytlrlyvkdgysqasnidccvycp
dseaelfghlvsnavedatvt-qak--kvleavvrtpvlgdknlkiamyt
krnghstsdhlfagnyrvinlaenlcflaygskpdwmmcsdhtgplvhkw
falldg-tyvnn--qvakcekfegfivveawisktdhsnlttynvfhggr
spqlpnsitgdygttlskarsggflakahiakaislqqrtglrdyefcdq
glnq----kfqetpcgdskppgvcvpspclciilrrirgislywtcplll
sqlgtslatpntknd-----laetmcdghvalcttafn--tesamcffe
>node11
fvhewksdclgpfeayvftstntffhvslqielrngflalpeiqe-----
alaaa-asefldaaglh-klnhlasds---slaia-canfgr-lfwdgvn
gfseitvkislkainmvgvgmd--pagshsagydgvkqklydgkvelvss
kgisnaircktvdgakddvgpgamqalvc-----------ldtsagakcc
efvvgslnv------lldldgwlcgd-klrlyvndgfaleqdvdcclyck
eynanafgmrigaildegqlq-aaktvnvfaaftqqpalpdsthafqlyk
kktgritkdcllkksyrlfqlafklfffaygckpkwvavfdatnclvnkw
fgllng-kfvgh--gvsr--klsgytlledwflkpdkgdwvhykgyqggk
rpklplaisgdtgtngsksqagpirlkpkapkgagahantglkgfnlcer
gmdp----dfqytehsdskgegpckrkpclsltrrqvpgvaaertceipl
aelgsalkagpayha-----laqticgniamlctergl--asisscffv
>node19
fvhewksdclgpfeayvftstntffhvslqielrngflalpeiqe-----
alaaa-asefldaaglh-klnhlasds---slaia-canfgr-lfwdgvn
gfseitvkislkainmvgvgmd--pagshsagydgvkqklydgkvelvss
kgisnaircktvdgakddvgpgamqalvc-----------ldtsagakcc
efvvgslnv------lldldgwlcgd-klrlyvndgfaleqdvdcclyck
eynanafgmrigaildegqlq-aaktvnvfhaftqqpalpdsthafqlyk
kktgritkdcllkksyrlfqlafklfffaygckpkwvavfdatnclvnkw
fgllng-kfvgh--gvsr--klsgytlledwflkpdkgdwvhykgyqggk
rpklplaisgdtgtngsksqagpirlkpkapkgagahantglkgfnlcer
gmdp----diqytehsdskgegpckrkpclsltrrqvpgvaaertceipl
aelgsalkagpayha-----laqticgniamlctergl--asisscffv
>ENV_SIVGB/47-569
fmklwksqcgggvkseggfttgrqkltilifgldepfllllaihereytl
afgna-tkaypaqgvmc-alidfvaernaankpid-afkrsknvkvrilq
glwilaaaavghvgklagdaga--pggkgpdekrgdellaedwdfnipee
gvkcgrqsdtnaklpiaantadkpvhldinwvvt------mdekggdkcc
hgcvgvtqsgrektsvleeapleasdyalnlaggeavinqegvaqcnleq
htnatvsgrtraktlgdgvaa-atd--sfsgnvypdtvigdgdltsalfe
kalpggaqnpllaggyngitlgvglfflfcgkcpnwvlcggsthshvelr
aglvep-rmfnhdeliascqkyegitmkdayfsrvtfdnwrhydvdqaag
e--fptpitgvvltrlsgkkvpddglrn---kgtgvgdpqineenlvvva
gdiglqetkfqhthygnctggnsiardpnfhwikrclisiavgipcslfa
ctigqpdnipdkknq-----ltgiapidhlvgtgvdsdvc-tldgplng
>ENV_SIVG1/22-522
fkklwgadslgafnedigipttgfeilamevtlengyldlaqvvearftf
algas-knq----atls-gl--lfdnv---vlgtayciqygk-liwsnll
pvkafsledtlkviniggetmvsqvggthpddrecvklltfnskvdlmgh
tmacdhkkcivistsrkdksmnavretih-----------lavgaaddcc
hvvvgdvdg------aielqdwdcidytlrlyvkdgysaasnvdccgycp
vseaelfghlvsntvedatgt-kgk--kvveavvrtpvlgdanekiamyt
krnghstsdhlfagsyrlinlaenlcflaygskpdwmmcnhhtgpsvhkw
falldgntyvnn--qiadsekfegfvvvevwisktdnnnlatyhffhggr
spqlpnsitsdygttlckargsgfltkaniakaislqqrtglrdysfckq
gl-------fhdtpcgdtsppgscvptpclcillrrirgvslyrpcplll
sqagkslatpntkne-----ltetkcedhaalcttafn--tetamcffe
>ENV_HV2G1/23-502
fahewngdcvgpfeayaiastntffhvslqielpd-----velqd-----
alaaalasefldasglh-klnhlasds---slava-canfgv-vfwdgvn
vfsghagkislkainmvgvgmd--pagshsagydgvkqkvydgavelvss
kgisnaircsdvdgqkdnvgpgamqalrc-----------ldtsagckcc
qyvigslnv------lldlvgwlcgd-klrlyvndgfvleqdvdcclhcq
qyngnafgmrispildqgqlq-nakttnvfaaftqqpalsdsthvfqlyk
kkkgritkkcllaksyrmfqlafklfffaygcspkwvavfdytaclvnkw
fgllng-kfvgh--gvsr--klngyvfledwflrpkkgdwvhykgyqgtk
rpsfplaisgdvgtngskslagpirlkpdapkgaaehantglkgynlcer
gmdp----dfeytehpkskgegpckkipclslprrqvpgvavqpsynipl
aelgsalkagpayha-----vaqkicgniamlctergl--asiascffv
>node8
fkrlwgaeclgafnadagvptngfhllaleiglkngylglvqvqesqftl
alggs-aneyteaaals-glihlfenv---vlgiv-cedygk-lfwsill
pvktftlqailkvvnfggsamv--pggtheedhecakllmydsklelpgq
glacnhkkcnvvksskkatskdaikdims-----------ldvsagekcc
hvvvgdvka------liemdpwecadytlrlyvkdgyaqdnnidccvyck
dsdaelfghivsnaiedatvs-tak--kileavvrtpvlgdknlkiamyk
krngrstsdhllagnyrvlslpmnlyflaygskpqwmacsdatgclvhkw
fslleg-kfinh--lvakcqkfegfivledwiaktdnnnwthynvfhggr
spqlpgsitgaygtnlskaksggillkpqiskatsiqqrtdlkdyefcdq
glnq----kfqetpygdskpegvcvrapclsiivrripgislkwtctllv
sqlgsalaapdtken-----laetmcdnhvalctttgn--tassmcfft
>node14
fvhewkadclgpfeayvftstntffhvslqielrdgflglpeiqe-----
alaaa-asefldaaglh-klnhlatdt---alaia-sanfgr-lfwdgvh
gfseitvkislkainmvgvgmd--pagshsagydgvkqklydgkvelvss
kgisnaircktvdgakddvgpgamqalac-----------ldtsagakcc
efvvgslnv------lldldgwlcgd-klrlylndgfaleqdvdcclyck
eynanafgmrigaildegqlq-aaktvgifhaftqqpalpdsthafqlyk
kktgrvtkscllkksyrlfqlpfklfffaygckpkwvavfdhtnclvndw
fgllng-kyvgh--gvsr--klsgytlledwflkpdkgdwvhyrgyqggk
rpklplaisgdtstngsksqagpirlkpkapkgagahansglkgfnlcer
gmdp----diqytdhsdskgegpckrkpclsltrklvpgvaaertceipl
aelgsalkagpaypa-----laqticgniamlctergl--asisscffv
>node9
fvhewkseclgafdayvftstngffhaslqiglrngylalpdiqe-----
alaaa-aseffdaaglh-klnhlasds---alaia-cadfgr-lfwdavn
gfseftikivlkainmvgvamd--pagshnqgydgvkqklydgkvelvgs
ggisnakrcksvdsakddvgpgaveelmt-----------ldisagekcc
efvvaslnk------lldldgwtcgd-klrlyvndefdleqdvdcclyck
eysanvfgmrigsildegqlq-aakivqvfealtrqpalpdrthlfqlyk
kkygrttkdhllikeyrilqlafklfffaygctpkwvavydatnclvskw
fgllng-kfvgh--gvsrcyklegytlledwflkpdlgdwvhykgyqggk
spklplaisddtgtngskaqsggillkpkapkgagvhantglkgfslcqr
gidp----dfeytphsdpkgegpcerkpclsltkrqvpgiaqertceipl
telgsalgsspayda-----laqticgniaalctdagl--aaisscffv
>ENV_HV2BE/24-510
fvhefkvdclgpfdayvftsskrffhvslpidlrdgflglpekde-----
elaaa-pddfvdaaglh-klnhlatdt---alaih-sanfgq-mfwdgvh
gfsaikvkislkatnmvgagmd--pagshnsgydsvkqklydgtveivss
kgignaircktvnaaedavgpgavqvlvc-----------ldteagfkcc
efvkgslnv------lleldgwvcgd-klrlynsdgfaleqnfdcclyck
eyntnafgmrigavldegqlq-aaktaglfhaftqqpglpdstftfhlhk
kktgrvtkscllkkayrlfqlpfkifffafpckhkwvavfdhtnclaeaw
fgllng-kyvdh--gvsq--klsgyplledwflkpskgnwveyrgfqggk
rpklplavsgdtsaaggkspegpirlspkppagsgahpdsglkgfglcer
gidp----diqytqhsnskgegpckrnpclslsrklvpdvaaertcelpl
aelgsalkagpdyat-----ltheicgniamlctgrgl--geitncffv
>ENV_HV2D1/24-501
fvhewkidclgpftayvftttssffhaalqielrdgflglhevke-----
alsaa-asefldaaglhtrlnslatdi---alaia-sggwnr-lfwdgvh
gfseitvkiclkainmvgvnmd--paglhsggydgvkekvydgkvelvss
kgisseircktvagakddvgrgalaalaa-----------ldtsggaknc
dfvvgslnv------llelqgw-----------ddgfaleqdvdccreck
efnapafgkrigaildeghiq-sattlgifhafphqpalpdsthtfqlyk
qnagpvtksclmkksyklfqlpfklfffahgckpkwvavfdhteclvndy
fgllng-kyvgh--gvsr--klsgytllddwflkpdkgnwrhyrgyqggk
rpklklaisgdtstngsksqpgpirlkpkapkgagghaasgikgfnacqr
gmda----diqysdqsdsngemackskpclsltrklvpgvagertceipl
edlgsalkvgpaysa-----laqavcssiamlcqergl--aslskcgfl
>ENV_HV2NZ/24-502
fvhewktnclgpfeayvfkktktffhislqie------elpeiee-----
alaqa-gsefadaaglh-klsflstda---nlaia-cgafgr-lfwdgvh
nhreitvpvsilminmigvgmd--pagshsagydvvkqklfdgqvelvss
kgtcnaircktvdgakntigpgamqalvc-----------lntsagrkcs
efvvgtldv------lldldgwlcgd-klrllvndsyvmeqdvdccatck
eynansfgvrigdilnsgelq-agktppvlhvftqqpalpgqshafllyt
rksgriegecflkrsyqlfqlafklyafaygcnpkwviqfdasnclitrs
fgling-kfvgq--gvar--krdgftlledwflnpdkgdivhykgynggk
rpklplaissdtganggkrqagpihlkpkapkgagnhtnyvkkgftlcer
gvdp----ddqytdhsdskteepckrkpclplthkqvpgvpakrtckicl
aelgsslkayptyng-----lthtvcgsiarlctdlgl--asvsscifi
>node17
fvhewkadclgpfeayvftstntffhvslqidlrngflalpeiqe-----
alaaa-gsefldaaglh-klnhlatds---slaia-canfgr-lfwdgvh
nfseitvkislkainmvgvgmd--pagshsagydgvkqklydgkvelvss
kgicnaircktvdgakndvgpgamqalvc-----------ldtsagakcc
efvvgslnv------lldldgwlcgd-klrlfvndgfaleqdvdcclyck
eynanafgmrigaildsgqlq-aaktvnvfhaftqqpalpdsthafqlyt
kktgritkdcflkksyrlfqlafklftfaygckpkwvaqfdatnclvtkw
fgllng-kfvgh--gvsr--krsgytlledwflkpdkgdivhykgyqggk
rpklplaisgdtgangtksqagpirlkpkapkgagnhantglkgftlcer
gvdp----diqytdhsdskgegpckrkpclsltrrqvpgvaakrtckipl
aelgsalkaapayha-----lahaicgniamlctergl--asisscffv
>ENV_SIVM1/24-528
fvqehkseclrafdsylftstsgffhahlemglqngylalpdlde-----
avaag-aseffdpaglh-kldhlasns---slaia-caefgr-lfwdavs
gfsefaikivleaismvnvvme--pagsynhgydgvkqklydgtqelvgs
gdisnakrckrvdsskddvgpgavedlft-----rtplpilgiaagekcc
elvvaslnn------llgldgwtcgd-klklyvkddfelvhdvdaclyck
eysasvfgqrigsildedqlq-tltvvqvfegltsqpylpdrthvfqqyk
kkygrttinhqlikeyrilqlafksfffaygctprwaaiydttnclvskr
-----g-dflgh--gihrcyklqglclpadwflkpelvnwvhykgyqagk
spdlpleisddtgpngskahsagilhrpkapksagvqanidlkgfticqp
giea----dfesspttdpkgegpcerkpclsltkrhvpglapertceipl
telgsalggspayda-----laqticsniaglcadagl--samsscffi
>node10
fvhewksdclgafeayvftstngffhaslqidlrngylelpeiqe-----
alaaa-asefldaaglh-klnhlasds---slaia-canfgr-lfwdavn
gfseitvkivlkainmvgvgmd--pagshnagydgvkqklydgkvelvgs
ggisnaircksvdsakddvgpgavqalmc-----------ldisagakcc
efvvgslnv------lldldgwlcgd-klrlyvndgfdleqdvdcclyck
eysansfgmrigaildegqlq-aaktvqvfealtqqpalpdrthafqlyk
kkygrttkdcllkksyrlfqlafklfffaygctpkwvavfdatnclvnkw
fgllng-kfvgh--gvsr--klsgytlledwflkpdkgdwvhykgyqggk
rpklplaisgdtgtngsksqagpillkpkapkgagahantglkgfslcer
gidp----dfqytehsdpkgegpckrkpclsltkrqvpgvaaertceipl
telgsalgagpayha-----laqticgniamlctdagl--asisscffv
>ENV_HV2CA/25-512
fahewkadclspfeayvftstntffhvsfhieirngflalpeiqd-----
alapa-ssefldaagfy-kfnhlvtda---glaia-adefar-lmwegvh
hfseitvrtglksydmagvgmd--paeshsagfdgvqeklrdgkvelvss
kgicrsircgsvngakngvasgampplvc-----------ldtsagakcc
qfivgslnv------lldldgwlcge-klrifvddgfalehdvncclyck
eysdncfgmkigalldtgdld-saktvnlfhaftqepalpdnahafqlcv
kktnrstkdyflkkpyrlfqlafklftfahgckpkwvaqfdtqnclvtkw
fgllng-kfggh--gvsr--krsgytlaedfflkpdkgdilhyqgyqggk
rpkkp-aisgktgaggtksqagpiklkkkapkgagnhpnsglkgftlcer
gvdp----qiqytdhsdmkcegpckrkpclgltrrqvpgvagkstckkpl
aklgsslkaapayrl-----lahaacgniakvctergl--ksistcffv
