>ENV_HV2CA/25-512
nsc--------elfgeaaf--irasrlrgvgrkdaelrcagkgci---dt
nkkcgkiehsgvcsqktpppdknakky--atgrllingparivveqalgg
frpagrqpnvttncveasfeysgvhaapeag--gkkygyslekehtrggf
kckkaksldlfavpkfdvkpk--wteciltlqiekhlvce--savftsyv
qtneltlnatvikcnifsktslhgclfqqqp---vtsaqlcs--venqvq
gkagleckspaantlk--kpgyamgcavgllavqkwvkrksvaqatdeki
qgkyvisalralfvktgrcvvaveivynrlyflterkchwef-grthvcg
pykilakahpv--gapevsrdllckkkelikqcltkdatscahlqk-hsg
ghgdtegngnfesssqkpkpgpsyc--hvffgtha-------chrsrlic
sqfplvvrsrisskqtaspmakggqaeav----vgqrkgfkipdlrtcis
kgkgrvkglvnkspgkthitctkvtr--------------aaytegnpgg
krcliggagaygp
>ENV_HV2D2/24-513
tsa--------avygataf--vrpddlagvarkdlefrcsgdgci---at
hkkcgnikhsgtcnerkgppnsetgkf--aagk----gaanlvveqalgg
frssqkqrsisercyqarfefsvthatpdte--gkkfdyiiekehnsggy
rcgkdkqldlfpspsffvvpk--waaciltleverhltsq--qavfggyp
dtkemnignngvscnaftqtrlhncifstap---aksaqlcs--vkslvq
gkeglpciskkagslk--kpgfyvacdvsllpiakwvrkksvevsvddkl
qgkyvitplacsyvktgfcvvgieilykrtyyafkrkcqwef-gapnict
pfkalgkahsv--aapeinrnlvskgkelqkgcetqdanpsadkqk-ysg
lvgnarqaasfeplsktttpnpayc--edlipthspafqntncqrrslvc
sefpghcrssmrsreyappmtkggqeeav----vasrvifpigtlqicis
gpnervkgfvklapgrgnptctnitr--------------etyaienpga
krclvggagpfrp
>node19
nsp--------alfgetaf--vrpntlrgvarkdvelrctgkgci---at
nkkcgkikhsgvcsqkkpppdkeadky--atgr----gaasivveqalgg
frpaarqrkvasscyearfeysgahatpdta--gkkfgyslekehtrggf
kckkaksldlyatpkfhvapk--wsgciltleiekhlpse--psvfagyv
dtneltinnsvvkcnafsktqlhacvfasap---vksaqlcs--vknevq
gktglecksskagtlk--kpgyamgcdvgllavakwvrkksvvittdekl
qgkyvitpmrskfvktgfcvvaveivynrlyflferkcqwef-grshvcg
pykalakaqsv--gapeisrdllckakelikacqtkdatpsahlqk-ysg
shgdtrgganfdsssqspkpnpsyc--edfisths-------cqrsrlic
sqfpglvrsrvraketvspmakggqaeav----vnkrvifpigdlrtcis
ksngrvkglvklspgkahitctnitr--------------atytaenpgg
krcliggagafsp
>ENV_SIVV1/24-538
iyd--------alfadklcvrsrhdtptkdkdtklnlfvfgeecf---al
kenrcevqkagtcggrrsgsaaneiey--feir----ngswlilqkvias
fgptgpknksntacndargsakiidstplvafcgkqygyetadkvkggef
sykehhfmelfaspklhvepe--wsealpvqqlqrkarkv--iarglayg
kgsdlsrgstyvnckpfpkghvrvnlfelvgkcaieatspcn--mlt---
------tnftaggtfr--sedtysacktalhglgqwvrgctlglptgvky
gghvdfakarrvairrgmcdvteeavysavvvdyerqcpaeiggskvvcs
fykepsayrtv--gacdvkkalfckakskpkqeelkkttsggpnhk-sgp
tktesraevnlrtlektgkvsstsc--derawept-------dtrvpmlc
avfqkrcrllvkrknfiaadikgsnakaa----aylrhafqvnalkdygs
kepkeiqghfsfapttkqgssahnlfadtthgepcslcfphgytrqaqsp
tgqles-ptvlyp
>node17
nsp--------qlfgetaf--vrpntlrgvarkdvelrcagkgci---at
nkkcgkikhsgvcsqkkpppdkdadky--atgr----gaasiiveqalgg
frpaarqrkvasncyearfeysgahaapdsa--gkkfgyslekehtrggf
kckkaksldlyatpkfhvtpk--wsgciltleiekhlvse--pavfagyv
dtneltinntvvkcnafsktslhacvfasqp---vksaqlcs--vknevq
gktglecksskagtlk--kpgyamgcdvgllavakwvkkksvvittdekl
qgkyvitpmrskfvktgfcvvavevvynrlyflferkcqwef-grshvcg
pykalakaqsv--gapeisrdllckkkelikacltkdatpcahlqk-ysg
shgdtrgganfdsssqspkpnpsyc--evfinths-------cqrsrlic
sqfpgvvrsrvrakettspmakggqaeav----vgkrvvfpipdlrtcis
kgngrvkglvknspgkahitctnvtr--------------atytaenpgg
krcliggagafgp
>ENV_SIVGB/47-569
sytgvvdlkgl-lfadvlf--qrkpgkqtncdsrsqislaakatlwfyek
nidcpgfkigsncqtidsgadrdkldf--lvgp----agcaldgqrplra
fatlaslivwaiagydselfavlmaslplkv--terlgmkltkppiiggy
ryktgtlldhyvaskihvgqd--wsvksptsqlragereg--pasvmcyi
attghtaekqekkygtysrvhlkdimygnqg---fvpatvcs--vla---
------krfirdgametfdvslhtecalaihgvgcylqppyvslaqpaas
gpgfafhwgdkrflptayctpsennsklnvqfggirtcitgi-akrvvcc
kycsqgqhrarqltnarcatilaapdhtvpkntetaripgsgrkgds---
---easeglerdvlsqegkvracscpcttmarcgt-------vgpmqpsy
gvlnmtgqkltgvgeknftdiaagladsfkpscgftfdvfkatysdqckt
tkkaavgedyttpprtdgydceevqk--------------tnylrektsv
hdqvvgvpfgvqp
>node10
ssp--------alfgetaf--vrpntlrgvarkdvelrctgngci---at
nkkcgnikhsgvcsqrkpppdseadky--atgk----gaasivveqalgg
frpaarqrkvasscyearfefsgahatpdta--gkkfsyslekehtrggf
rckkakqldlfatpkfhvapk--wsgciltleverhlsse--pavfagyv
dtneltignsgvscnpfsktqlhacvfaaap---vksaqlcs--vknevq
gkvgleckskkagtlk--kpgfymgcdvgllaiakwvrkksvplttdekl
qgkyvitpmrskfvktgfcvvaveivynrlyfaferkcqwef-grshvcn
pykalakaqsv--gapeisrdllckakelikacqtkdatpsahlqk-ysg
shgdlrgganfesmskspkpnpsyc--edfisths-------cqrnslic
sqfpglcrsrvrakeyvppmakggqaeav----vnkrvifpigdlrtcis
kangrvkglvklspgkahitctnitr--------------atytaenpgg
krcliggagafsp
>node18
nsp--------qlfgetaf--vrpntlrgvarkdvelrcagkgci---at
nkkcgkikhsgvcsqkkpppdkeadky--atgr----gaasivveqaigg
frpaarqrkvasscyearfeysgahatpdta--gkkfgyslekehtrggf
kckkaksldlyatpkfhvtpk--wsgciltleiekhlvse--psvfagyv
dtneltinnsvvkcnafsktqlhacvfasap---vksaqlcs--vknevq
gktglecksskagtlk--kpgyamgcdvgllavakwvrkksvvittdekl
qgkyvitpmrskfvktgfcvvaveivynrlyflferkcqwef-grshvcg
pykalakaqsv--gapeisrdllckakelikacqtkdatppahlqk-ysg
shgdtrgganfdsssqspkpnpsyc--edfinths-------cqrsrlic
sqfpglvrsrvraketvspmakggqaeav----vnkrvifpigdlrtcis
ksngrvkglvklspgkahitctnitr--------------atytaenpgg
krcliggagafsp
>node9
nat--------alfgestf--vrpntlrggarkdvelrctgngci---as
nkkcghikhsgvcsqrkpppdsqadky--atvk----gaasivveqalgg
frpaarqrkiasschearfqfsgahstpdta--gktfayslekqhtsggf
rckkdkqldlfagpklhvapk--wsgciltleverhlssq--pavfagyv
dtnalsisnsgvscnpfsktqlhacvfaaap---vkstqlcs--vknevq
gkvgleckskkggtlk--kasfymgcamgllaiakwvrkksvelstnekl
qgkyvitplrpkfvkkgfcviaveiiynklyfafekkcewef-grshvcn
pykalanaqsv--gapeisrdllckakelikasqtkdatpsahlek-ysg
thgdlrgganfeamsksakpnpsyc--edfisths-------sqrnallc
sqfpgpcrsrvrakeyvppmakggdanav----vnkrvifqigdlrncik
kangrvkglvklspgkahatcthitr--------------htygaenpgg
krcliggthafsp
>node11
nsp--------alfgetaf--vrpntlrgvarkdvelrctgkgci---at
nkkcgkikhsgvcsqkkpppdkeadky--atgr----gaasivveqalgg
frpaarqrkvasscyearfeysgahatpdta--gkkfgyslekehtrggf
kckkaksldlyatpkfhvapk--wsgciltleiekhlpse--psvfagyv
dtneltignsvvkcnafsktqlhacvfasap---vksaqlcs--vknevq
gktglecksskagtlk--kpgyamgcdvgllavakwvrkksvvittdekl
qgkyvitpmrskfvktgfcvvaveivynrlyflferkcqwef-grshvcg
pykalakaqsv--gapeisrdllckakelikacqtkdatpsahlqk-ysg
shgdtrgganfdsssqspkpnpsyc--edfisths-------cqrsrlic
sqfpglvrsrvraketvspmakggqaeav----vnkrvifpigdlrtcis
ksngrvkglvklspgkahitctnitr--------------atytaenpgg
krcliggagafsp
>node7
lyt--------alfgdklypsarhdtprknpdtklnlwvigencf---al
kenvcdvkkagtcggrksgcganevky--sdir----dgswvelqkaies
fgpegrrrksdtschdtrasikvcqttplva--gkqygynvadqvtgggf
rykehhlmelyaspklhvepm--wsealpaqqlqrklrnp--paigvtyv
kasdlsigpayvncapyskaqvriclfgqaetcqitstqpcn--mlt---
------tkfirggtfr--teglysgckvalhgigkwvrgctlalpttady
ggkisfaqlrrktlrkgfcdvteqavyvsvvfdfdrncpadiggrkvacs
rykqpsayrai--gasdvkrallckakpqakqqelkkttsagpahk-stq
tkadsraevnlqalekqgkpkptsc--derewept-------dhrvgklc
tvyqgrcrllvnhktfvvadikgsdanas----gylrhvfqanalrdyvt
kersdiqghfslsptrvqagcshvlrteckhgeacslcfshsyksqqqsa
tgkleg-pnalip
>node14
nsp--------qafggtaf--vrpntlrgvarkdvelrcagkgci---at
nkkcgkikhsgvcsqkkpppdkeadky--atgr----gaasivveqavgg
frpaarqrkvasscyearfeysgahakpdta--gkkfgyslekehtrggf
kckkakslslvgtpkfhvtpk--wsgciltleiekhlvse--psvfagyv
dtneltisnsvvkcnafsksqlhactfasap---vksaqlastsvknevq
gktglsckwskagtlk--kpgyaqgcdvgllavakwvrkksvlvttaakl
qgkfvitpmrskfvktsfcvvaveivynrlyflferkcqwef-grshvcg
pekatargqsv--gapeisrdllcktkelikacqtkdatppahlqk-ysg
shgdtrgganfdsssqspkpnpsyc--edfinthg-------cqrsrlic
sqfpglvrtrvraketvspmakggqaeav----vnkrvifpigdlrtcis
ksngrvkglvklspgkahitctnikh--------------atytaeppgg
krcligaagafsp
>ENV_HV2NZ/24-502
nsp--------qlfgetaf--vapntl--vnrtdvdlrcagsgci---aa
ngkcgkirhsgvcsqkkpphdkdadky--atgr----gaagiiaeqalge
lrpaararkpatdcyefrfeysgahgagdna--gkkfgyslpkehipggf
kcskaksldlygkpkfhvkpk--wggcvlhlevenhlvse--pavfagyl
dtnelaitgtvakcnafiktsfhgcifgkqp---ikgaqlct--vkhrag
akpslecksskagvfk--kpgyamgcnlgllavakwivkntvvettdeki
entgtitsqrsklvnsgfcqvsvevvydrlyflfdrkcqwef-grsqvcg
pysalaktknv--gapevsrellcklkdlikacltkdatpcahlqk-qcg
ghgdsrggpnldsssqspkanpsyc--evfvntts-------cersrlic
cpfpgvirsrvkgtvttspmasgghadai----vekrivfpipdlktcvs
kgngrvkglvknspalahvactnltr--------------atytvenpgg
rrcligavggfgp
>ENV_HV2D1/24-501
qrp--------qafggtaf--vrantlhgiakkdvdtkcaakgci---vt
skkcgkikhdgvctqkkpppnkeasky--atar----gaasiiveqavgg
f-pgardrkvasacyearfeynpahakpata--gkkfdyslenectrggf
kcrkakslylvgtpmfhvapk--wsgckltleltkhvvsnrtpnvfagyv
dgneltientvdkcaafsksqlnaatyasap---vkssqlasssvknele
gkaglsckwskagnlk--kpgsaqgcdvgllavarwvrkksvlvttatkl
qgkfvvtpmecpfvktsfcvvaveivynrlyflfefscqwef-grshvcg
pekaaardqsv--gapqitrdllcttrnlikgcstndatppahlqk-fsg
shgdtrggahfdsssqsprpnpsfc--edfvnthg-------cqhsrlmc
sqfpgllrtraraketvspmakggqpmav----vnkrvifpigdlrtcis
ktngrikglvklspgkahitcvkvkh--------------atyaaeppgg
krclmsqagafsp
>node8
nyt--------alfgdklf--arhdtvrknadtkldlrvageacf---al
ehnccdikkggtcgvrkggpdaneiky--sdir----dgswveiqrpies
fgpggrrrksvtschdtrfsvkvpqstplta--gkaygynlakqvivggf
rykshkllelyaspklhvepm--wsgslpthqlqrdlrns--pavsvtyv
kasdlsispnavnctpfskaqvriclfgaad---itstqacn--vlt---
------tkyirggtfr--neglylgcdealhgigkwvrgctldlsttsdy
ggkysfaqlrrkflrkgfcsvaeqavyqkvvfgfdpncdadi-grkivcs
qyrapsdsrai--gapqisrallcqakplakqkeqkkttpagpvek-stq
tkadgrakvnlqalekqgkpnptsc--deiewepk-------egrvaklc
tvyqgrcrllvnvktfvvanikgsdadas----gylpsvfqanilrdcvt
kdraniqghyslspsrtqagcshvlr--------------hsyksqrqsa
ngklvggpnafip
>ENV_SIVM1/24-528
nap--------slfgessf--lrpatirggarkdvellctgnsci---ds
akkcnhvkrsgmcsaskpppnaeadkm--atvk----gaasivvdqalga
frpasrsrgiaaschearfhfkgahrtpdta--gktfsfsheknqvsggf
rckkdkqldlfqgpklhvapk--wsamvltledqrhlssk--pavitgyv
dtngmsisdspvacnpfnkkqlhgcvfaaar---vkstqlcs--ckndvv
gkvglecpskkggtlk--kagfcmgcamglliiakwvrkksvdlsknkkl
qgkylvtplrpnfvkkdfcviaveiiynrlffafedkcqwaf-gkshicn
pykalttaqsv--dtpeisrellckaktlvkaaqtseatssahldk-ysg
thgdlrsganiepmsksekpgpsyc--edfvssds-------gqrnallc
shfpgpcksrvrakdtvppmdtggdenav----inkrvtfevfnlrncik
kangrvkglvklapgkahatcthitq--------------h-ygaedkgg
kkciiggtqafap
>ENV_SIVG1/22-522
lyt--------alfgdtlysssqhktprknrdtklelwvvhsycf---el
senlcgakkagtcg-rkgacganelky--sdir----dgswvelqkaigs
fgpegryrktdtscndtrssikvcqtaalva--gkqygydvadeitgngf
hykehhlvklymlpnlhvepm--waeavpiqqlqrklrnr--peigvsyl
kasdlsigpsyvncapykksqkriclfgegetcqitstqpct--mlt---
------tkfvrgstyr--teglysgckvalhmvgkwvr------pttasy
ggkisfaqlrrktlraafcdvteqavymnvvfdfdrnvpadiggrkvecs
rykqpsayrai--gesgvkralickakpgakqndlskttsagpahk-ttq
tkadsraevnlkaleahgkpkpssm--derewtpt-------gqrvsmlc
tayqgrcrllvnhktfavidfhgsdanas----gflrhvfevdvlrdyvt
kkrpqitghfglrptrgepgchhilrseckcgetcslcfapayksqqqsa
tgkleg-pnalip
>ENV_HV2BE/24-510
nsp--------qafggtaf--vrpntlqgverkdvelkcagkgsi---et
dkncgkikhsglcsqkkpppdkeanky--adgl----gadaivveqdigg
frpasrqrkvasscyearfeysgahakpdta--skkfgytlevehtrggy
kckktkslslvgtskfqptpkkgwsgcvltvaiakhlvse--psvlagye
dtsaltisnsivkcnnfskgelracsffrap---vktgqaaptsamnelq
gktglsckwakatvln--kpgyaqgcdvgllavakwvrknsvlaltaakl
egkfetaplrstllktsfctvavhivyntlyfifektcqwdi-gkshvcg
pekatakgqtv--gsnaisrdllckhkelinacqtkditppahqqk-yhg
sngdtkmsahfdsssqgpkpnppyc--enfintqg-------cqrvrlic
gqfpglvktrvrakeavspmakngvaqaa----vekrvifpigklhvyid
ksngrikgtvkvspasahitctaikh--------------aayimqppgg
krcligpadafsp
>ENV_HV2G1/23-502
nap--------alfgetaf--vrpntlkgvarkdvnlrctgkgci---at
nkkcgkiknsgacsqkkpppdkeadkylqatgr----gaasivveqalgg
yrpaqrqrklasacfearfeysgavaapeta--gkkfgtrqekehtrggf
pckkaksldlyatpkfhvggk--wtgciltleiedhlpke--psvfagyv
dtnqltigdsvvkcnafsktqvascvfaeap---vksqelcs--vkneiq
gktglecksskvgtlk--klgyalgcpvgllavakwvrkkavvittdekl
hgkyvitpmriksvkpgfcvvaiqivytrlyflferqcqwef-grthvcg
pykalvkansv--aaneisrdlvcqakelgkacqtkdatpsahlqk-yss
shgdirgganfdsssqspkanps-c--neiisthg-------cqrtklic
nqfpgltrsrvrakktvsprgkggqaqav----vnkrvlfpigdlrtcis
ksdgrvkglvklspgaahitctnitr--------------atytaenpgg
krcllggagafst
