>node18
gpdatllidrakrr----vskpagqcktdlsvqgnvk---iaklkticlh
eqngcratagngdgq---nyasf------gddrkwh--dlhl----yyik
qivaqgfkgvcnlklwaafwetigivnrlgv-g------vn--kghhd--
---kagq--kyewktckkglltepdggnvwplely----ipkgtvseigg
aihplcafgncnikvgfgarkgdtegg--lsefagapihncefvklenld
lcdvcgpknnckcscsr---qemenchnrktqkqhslcrdgllrsylgrs
rhldlvtlqlasqtdtlgaegpncsetlpctgipssmestlpdc--lekv
ewkkkndvvkiygycvgnktkivmttvqgrfdfgeqdpnfasggfgd---
----iafgsttdasavesglapkrgwaysdgaafttpqdvltncvgpryv
rtsgsqnvnndgmntfvskiskgaafendcevksaypssivlak------
------------dggyepsgglcfsfgtihtkcgka--------------
-------tltnldqtvwtgagnnvkdgasrggsnlkkqqitavei
>ENV_HV2CA/25-512
geaatlliqrakrr----vskqagdcksaidvqgnvd---iakitticln
eendcrltagngdgq---gyapf------gddmkwh--nlvl----yyik
kiveqkfkgvcnlkiwagfwqtigivnrlgv-gellrdvqn--kghhe--
---rsgq--ahewkeckrglltnpdgitirplely----ipktnvseigg
aihplcafgncdikvgfgaskadtegg--lsefaglpihscdfvkldnle
lcdvcgpkancmcpckr---qemdnchnrktqkqnslcsdallreylgrg
rllelvtlqlkspaetlgadgpyctdtvpctgipstmestlpdc--mqkv
ewkkkneavkasgycvgnktkiilttvqgrydfgeqdhtfasggygt---
----iafgsttdasavennlapkrgwgysegaaltapqdvltacvspkyv
mtsasqnvnnssmttfvskiskaaafendcevkgaypssmmlsk------
------------egnsaptiglcfgfgtihtkcgka--------------
-------tltyldqtiwaeagstvkdnasrgssnlkkqqihagai
>ENV_SIVM1/24-528
gskstllidrakrr----vsmpsgqcrtdlsiqgnvk---ipnlgticsh
ernqvraaagsdngq---haasf------geqrkwlfknlht----yyfk
afisegfkgachlelwaafwesvgignilgvhg------vg--kghhv--
---qagq--kypwkdckkgllaepdgddiwtlely----apkgtiseiga
sinpicqyhpcnikagfgahkgdtsgg--lsnfagaaihscefvgldele
lchscgaksnckisctq---qemnnvanhvtqkthslcrdgilraalgrs
rhlelvtlqlesqtntagiegpgctgtvpctaisasmdstlldc--ldtv
awkkkedvvkiygysvgkktkvvltklqgqfdlgeqqgafnngkfgd---
----gafgsnsdstaansgtapkkgwrysdspafqapadvlnkcvgvrav
rttgtqkvqnngmntfgskvskgaeyeddcqvkspypstivltk------
------------nggyeplgslcaalgtimtkcgka--------------
-------tmtdleqtiwtatgnavkdgdtrggrkldrrqllapaa
>node9
gskstllidrakrr----vskpdgqcrtdlsvqgnvk---ipnlgticlh
eqnecradagngdgq---hyasf------gadrkwlfknlql----yyik
aivsegfkgachlelwaafwesigivhklgvhg------vn--kghhe--
---kagq--kypwkdckkgllaepdggdiwplely----vpkgtiseigg
aihpicafnkcnikagfgahkgdtsgg--lsnfagapihscefvkldnle
lcdscgaksnckisctq---qemnnvanrvtqkqhslcrdgllrsylgrs
rhlelvtlqlasqtdkagaegpgctgtipctsisssmdstlpdc--letv
ewkkkedvikiygysvgkktkvvmttvqgrfdfaeqdpnfsngkfgd---
----iafgsnsdstavnsgtapkrgwaysdspafqtpadvltkcvgprav
rttgtqnvhndgmntfiskvskgaeyeddcevkspypstivlak------
------------dggyepsgglcagfgtihtkcgka--------------
-------tltdleqtvwtgtgnnvkdgetrggrnlekqqitavdi
>ENV_SIVG1/22-522
gsrpdllrpeghrk----ltkddsycrkatgvsaeih---cvalqviclq
dqat-rdkqavsggn---qyanmkhvswaggankwlfldpvvnnacyptr
vvapegfraacqvilwaglwegvgvlqhlvvlq------vd--egrqg--
---psds--rytwkecsavlkseqsggemwpldyytsf---satlpnlgq
pvsmlcefdfcvlqegfgaacgmtgsgaclgsfgpeninacvyvylgdee
lclgygkrnakplqqvt---qgleavrdgatqkphglchegllenyawqr
lalsqgkpeltcrddkkvldeeackgpvpchtisfn-tqglticallatl
qwkkr-nvvsiyacsigkftqaqaklisdkteldhqkas-vnprfns---
----lgftskdgatsvkggdgpacgwpgatgptnqthvdqlgkctgvrqv
hlvttnkikddilkikgstvpsskeypdkcdlkapfkstiflck------
------------adafkklaracvglgtihpqcklsieigqicdlfdeal
aihflkrdltnvshriwtgtgnkrdeeqgkkaksknkkhieacdy
>ENV_SIVGB/47-569
trlvnlwa-dphrk----iqr-qgtakgngelgnkvn---aaefkkpclh
tagd-dvdigientdaniyykll------ggdniwmctgggi----lfpt
a-gtsgfqessrcvlwgclwyavsdvvkhtths------ld--gctptci
yllaled--rykwkscaqeten--ndmdqwntrsykv------liskadh
qerivsaskhakchaaagsqegtkgqp--lkgtapkgiklsgfqflesvd
pptgyykndvvnfdgqm---kfvsalnhhgpeephgldqigriqgaapkr
nsisqpklaasyehpllglkgegccclakcgphsyh-pknvveaellgsl
qltse-vdkgvcicgaagknppvdksneenygvsvngqdyehtlfpw---
----ldfeqkaeapeirgteghvsswgvallrsfafqadsrekcptgnqq
epalyaagkrkplivflngvakgsgwelggdmsraydgliylkelspkft
isqtyvdhytiyakkgadlckdevpcgalqsncapipvkkttsrygglfi
tcpvskd--hnlhaemligtsakyhispdrgqnagkkqdcvnyvy
>ENV_HV2G1/23-502
gpdatllidrakrr----vqkhagqcrmnlsvqgnvrkcpcakllteclh
denacradagngdtq---nyasf------adarkwh--nlhl----yyik
plvcqtfkgvcnlklwaafsetvgtvkrlgv-p------vn--yghhd--
---ksgq--kyewkdctsglltepnggnvwqlemy----iakgaqseigg
aihpvcafgncnikvgfgarkgdtegg--lnefagapvhncqfvmmedld
lcdmcgpknnckcscsr---qekedcnnrktqkhhslrrdgllrsslgrs
rhldfvtlqlaaetdtlgaegpdcketipctgipssmdstlpas--lekv
ewkkkndavkiygycvgnktkivmttvqgrfdfgqqdpnfatggfgd---
----vafgsstgasavesgvapkrgwsysdaaafqepqdvltncvgpryv
rtsspenvpndgkntfigkiskgstfeddcavksaypssvklak------
------------dggyepagglcfgfetihtkcgka--------------
-------tltsldqtvwtgaghtvkdgadrggrnlkkqqitevem
>node8
gsrptllkneghrr----ltkddgtcrknagvgaeth---vpaleviclq
dqte-radvgvnggg---hygnm------ggdnrwlylnatvgnecyltr
ivaaegfretcqvilwaalwegvgvlqkhsthg------vn--egrhe--
---rted--rypwkecstgleaqqnngemwpldfygtfylssatlanige
pvsmicsfnfcdiqagfgssngktsss--lggfapeninscdyvylgnve
lcegyaarnaspmdaal---qgllavrhvatqkphglchdgliqtyigrr
ralsqgkieltcqddkyglqeegcakpvpctsvsfn-tqglsecalletl
qwkkk-nvvgiyacgigkktkvvakkitdksglaaqnpsfanhrfqf---
----lgfgskgeaasvksgdgpvrgwpsstsptyqthvenlgkctgakqv
rsvtsqtidddvlkifvskvarskeyqddcelmdpyasviflak------
------------enafdklgkacvglgtihpkcdmsvevtqicdlndqvl
tipfckhtltdlqeriwtgtgnkrddaetkgakskekrhidayqf
>node19
gpdatllidrakrr----vskpagqcktdlsvqgnvk---iaklkticlh
eqngcratagngdgq---nyasf------gddrkwh--dlhl----yyik
qivaqgfkgvcnlklwaafwetigivnrlgv-g------vn--kghhd--
---kagq--kyewktckkglltepdggnvwplely----ipkgtiseigg
aihplcafgncnikvgfgarkgdtegg--lsefagapihncefvklenld
lcdvcgpknnckcscsr---qemencnnrktqkqhslcrdgllrsylgrs
rhldlvtlqlasqtdtlgaegpncsetlpctgipssmestlpdc--lekv
ewkkkndvvkiygycvgnktkivmttvqgrfdfgeqdpnfasggfgd---
----iafgsttdasavesglapkrgwaysdgaafttpqdvltncvgpryv
rtsgsqnvnndgmntfvskiskgaafendcevksaypssivlak------
------------dggyepsgglcfsfgtihtkcgka--------------
-------tltnldqtvwtgagnnvkdgasrggsnlkkqqitavei
>ENV_HV2D2/24-513
gpdatllidraarrkkrkvvkeggqcrtelaydgntk---iqalkaicls
eqdgcradtgegdgd---hyigf------dtdrrwh--alhl----yyik
qlfsqdflgpcnlglwaafwesigivthlgv-g------vn--kahqn--
---kagk--nyewkdcrkglltgpdggdvwpleil----vgkgsiseing
vitqlcaignckvrvsfgsrkadtegg--lgefpgaaihdcdfvhlknld
lcsvcapkhacicacsq---pemakcknskthrqhslcqdgllrqylarp
rhldivslmldtqteepaaegpncsgtnpctgisssddttlpsc--ldkv
qwkkdndlvnivgycygkkagtivstvsgrldfgeekpnyknakfed---
----hgfgsttdsagmdtgvapkrgwayqdgaafrtpaeaitncisprav
rttcsqgvaddgmnsfitsinkeaafkndcevraaypgaivlak------
------------lasyepsgslcfsfgtghakcgka--------------
-------tltnveqtvwaeaghnlkdgaskggrnlkkqqitsvei
>node17
gpdatllidrakrr----vskqagdcktdisvqgnvk---iakikticlh
eqngcratagngdgq---nyasf------gddrkwh--dlhl----yyik
qiveqsfkgvcnlklwaafwetigivnrlgv-g------vn--kghhd--
---kagq--kyewkeckkglltepdgqtvwplely----ipkgtvseigg
aihplcafgncdikvgfgarkgdtegg--lsefagapihncefvklenle
lcdvcgpknnckcpckr---qemenchnrktqkqhslcsdgllrsylgrs
rlldlvtlqlksptdtlgadgpnctdtlpctgipstmestlpdc--letv
ewkkknevvkiygycvgnktkiimttvqgrydfgeqdpnfasggfgt---
----iafgsttdasavesglapkrgwaysdgaafttpqdvltncvgpkyv
ktsgsqnvnndgmntfvskiskgaafendcevksaypssivlak------
------------dggsepsvglcfgfgtihtkcgka--------------
-------tltnldqtvwtgagsnvkdgasrggsnlkkqqitagei
>node14
gpdatllidrakrr----vskpagqcktdlsvqgnvk---iaklkticlh
eqngcratagngdgq---nyasf------gntrkws--dlhl----yyvk
qivaqgfkgvcnlklwaafwetigvqnrlgv-g------in--kghhd--
---kggq--kyewktckkgllkepdggnvwplely----ipkgavseigg
aihplcafghcnikvgfgarkgdtegg--lsefavapihncefvklenik
lcdvcgpknnckcscsr---qemenchnrktvkqhslcrdgllrsylgrs
rhldlvtlqldsqtdtlgaegpdcsstlpctgipssmestlpdc--lekv
ewkkkndvvkiygycvgnktkilmstvqgrfdfgeqdpnfakggfge---
----iafgsttdasavesglapkrgwaysdgqafttpqdvltncvgpryv
rtsgsqnvnndgmntfvskiskgnafendcevksaypssitlak------
------------dggyepsgglcfsvgtihtksgka--------------
-------tltnldqtiwtgdgnnvkdgfsrggsnlkkqqitavei
>ENV_HV2D1/24-501
gpdptqlidrakrr----vskpagqcktdlsvpgnak---iskhkticlh
eqngckttagngdgq---nyanf------antrkws--dlhl----yyvk
qitaqgfkgvcnlklwaafwetigvqnrlgv-g------pn--kghhd--
---kggq--kyqwktckngllkesqggsvwpldly----ipkgavslivg
aihplcafghcnmkvgfgarkgdtegg--lnefavkginnceyvklenik
lcdlcgpknncqcscsr---kemsnchsrntvkqhklcrdglmraylgrs
rhldlvtlqgdsqkdtlgaedpecssalkctgipssmesqlpdc--lekv
ewkkqnnvvkiygycvgnktkifmstvqgrfdfgdqepnfakgglge---
----iafgqtidatqvesglapkrawayndgqmyttpadvltncvgpryv
ktsgnqsvnsdgmnsfvpkiskgaafendctvkrayttsitlak------
------------davyepsgglclsvgtihtktgka--------------
-------tlsnldqsiwtgdgnnvkdgfsrggsqvekqqitavdi
>node10
gpdatllidrakrr----vskpagqcrtdlsvqgnvk---ianlkticlh
eqngcradagngdgq---hyasf------gadrkwh--nlhl----yyik
qivsqgfkgacnlklwaafwetigivnrlgv-g------vn--kghhd--
---kagq--kyewkdckkglltepdggdvwplely----ipkgtiseigg
aihplcafgkcnikvsfgarkgdtegg--lsefagapihscefvklenld
lcdvcgpknnckcscsq---qemencnnrktqkqhslcrdgllrsylgrs
rhldlvtlqlasqtdkagaegpncsgtipctgisssmdstlpdc--letv
ewkkkndvvkiygycvgkktkivmttvqgrfdfgeqdpnfsngkfgd---
----iafgstsdstavdsgvapkrgwaysdgaafrtpadvltncvgprav
rttgsqnvnndgmntfiskiskgaafeddcevksaypsaivlak------
------------dggyepsgglcfsfgtihtkcgka--------------
-------tltnleqtvwtgagnnvkdgasrggrnlkkqqitavei
>node11
gpdatllidrakrr----vskpagqcrtdlsvqgnvk---iaklkticlh
eqngcradagngdgq---nyasf------gddrkwh--dlhl----yyik
qivaqgfkgvcnlklwaafwetigivnrlgv-g------vn--kghhd--
---kagq--kyewktckkglltepdggnvwplely----ipkgtiseigg
aihplcafgncnikvgfgarkgdtegg--lsefagapihncefvklenld
lcdvcgpknnckcscsr---qemencnnrktqkqhslcrdgllrsylgrs
rhldlvtlqlasqtdtlgaegpncsetipctgipssmdstlpdc--lekv
ewkkkndvvkiygycvgnktkivmttvqgrfdfgeqdpnfasggfgd---
----iafgsttdasavesgvapkrgwaysdgaafttpqdvltncvgpryv
rtsgsqnvnndgmntfiskiskgaafeddcevksaypssivlak------
------------dggyepsgglcfsfgtihtkcgka--------------
-------tltnldqtvwtgagnnvkdgasrggrnlkkqqitavei
>ENV_HV2BE/24-510
gpnatllidrakrr----vsksegesltdlsvdgnir---ivklkticlh
eqngcratagngdgq---hyasf------gsarlwa--dlhl----wyvk
qivaqgfkgvcnlklymamwktiglenhlgv-g------in--kgqhd--
---kggqsakyewktckqgllkaphlgnvwplqly----ipkgavsevgg
pihplcafghcnikvafgtrksktegg--lselavadthncefvklenik
lcnicgpknnckcscsk---qemancdnrgkmkqhslcragllrsylgrk
rhldlltlqlksqtgtlgaegpdcsstlpcsgipramdstqpdc--lakv
ewtrkndvvkiygycagnktkilrstvqgrfnfgeqdpafakggfge---
----iafgsktdavavesgiapdrgwaysegqafttpqevltncvgprya
rvsgshnytndgmntlvskvsagnafeddcevksaypsstslsk------
------------dggkdpsgglcfsvgtihtksgka--------------
-------tltnldqtiwsgngsnvkdgfsrggsnlkkqqina--i
>ENV_HV2NZ/24-502
gpdatllidrerrr----vgkqvgdckydlsaqgdvk---iakiksicld
eqngcratagngdgl---nyssf------ganrkwd--gtpl----yvik
qiveqtfkgvcnlalwsafwetvgivnrlgv-p------ktpskghhq--
---kafq--kyewreckkglltgpdgqtvwpfely----ipkgtvaeigs
aihplcafgnceikvgfgarkgdaegd--lksfapapyhncdfvklenle
lcevcgpknnckcpckr---qemkschnrnkqkqhslctdgllrgflgsp
qlldlitlqvknpmdtlgadgpectntlpctglpstmegtlpdc--letv
dwkrknevvkiyghcvgdsnkivmtti-gkydfghqdphfasggfgtasq
lhaeiafastvdasavetglspkrgwaysagvafitpqdvltncpepkyi
ktsgsqdvkhdgmntfvgkitegktlendcevkaaypssillar------
------------dggsepsvglcfgfgtihtkcgka--------------
-------tltnlaqhvwtgaesnhkdsasrggsslkkqqitagei
>ENV_SIVV1/24-538
nakptlfrnyghnk----ltkndgtcrassastarth---cvalaldcle
dqae-rgkphs--gd---qyadl------ggadrwlflsavagtachvtr
vvvtdgfrdscdvilraalwegivvmdhlslhq------vq--egrng--
---aagp--qygwkecslglkttqsggalwplpyfssfylgsktlalvge
spsfecqfnfcvvhtg----sgksggk--lstfgvdtvnscvyvyagane
nchgyaqrndkpmngvdvykqgleavrergtqkphglchesliltgakrr
rgvsqgstelncendkngldeggckvpvpcarisfn-tqkyslcvmlksl
qwnsr-elvaiyasgkgkklkvvakgitdkteferqsntfstprfty---
----lafgdkdeaasvkggegpvrgwigpsgstgqthveklgtctgarki
hlvstesisnailkisnnwgpsskgyhddaelkrtyasvkflcs------
------------avaynnlgktcaglgkihpkcdmtpdvvyicdtrneal
kinikkhsltsiqdniwagkggnrdegkgqkakssnrkeidacry
>node7
gsrptlfrneghrk----ltkddgtcrkntgvgaeth---cvaleviclq
dqae-rdkpdvnggn---hyanm------gganrwlflnavvgnacyvtr
vvapegfreacqvilwaalwegvgvlqhlsmhq------ve--egrqg--
---asds--ryawkecstglkaqqsggemwpldyyssfylgsqtlanigd
pvsmicefnfcviqagfgssggktgss--lgsfgpeninscvyvylgdae
lcqgyatrnakpmdkvt---qgleavrdgatqkphglchdglietyanrr
ralsqgkaeltcrddkkgldeegckgpvpcatisfn-tqgltacalletl
qwkkr-nvvgiyacgigkktkvvakkitdkteldqqsasfvnprfng---
----lgfgskdeatsvkggdgpvrgwpgatgptnqthveklgkctgarqv
hlvttqsinndilkisgskvasskdyqddcelkapyasviflck------
------------adafnklgkacvglgtihpkcdmsvevtqicdlndeal
aihfhkhdltnaqeriwtgtgnkrdeeqgkkakskekkhidacqf
