>ENV_HV2D1/24-501
--gswrgtlm-----------t-glsali-------knrnerrhtm--t-
-ce-------------ssnwv----grg---ag---hlkcn---gkghet
r--lpv------------gk-------gsa------agtp-----iiwsn
g----ar-ryfkqcte-----iaq-------------------gryh---
hpgcl-lshfqd------fkvv--seqg---sa-h-qriaamdvtpap-p
pkyvvfnpnt-lkikarytd-sa-ng-----------------v-y-grh
i--va---hlvath------atyg-----shgg---kclkkke--sgp--
-mtvdihckldl---ld---------------agdfpas--fy----pkp
rltlvlgv-kqlv-----g-------------vv---di----ggisdvy
rsvp-----lvsqis--t--i-----------------------------
------------------------------t-s-slk-ield------h-
-----lctataslcl-plgpkkr----hpsal-------wtpcsleqsia
p---nasi-nk-cvtvcddf----------f-------------------
-------lla-cfeekytnsvtdkn------gitpnsyat-rk--t---y
---snhvv------evk----d-------sgakel-lppittfk-pay--
na-----avg------------fga-------td----elqkc---pgrc
lsdrcr----------ehndiadvea-krva-----l---fh--ltkgl-
-l----scl--s------sgd--a---itqdgpkkravvvqnwqka--dk
-lkglllqaggvek--------ppvv------------vg--ygtt-fva
glcsnnl---kgat----dqs
>node9
--gsfratlfmisq--g-p-lt-gltqiv-------khkhdrhhsm--s-
-ce-------------sanwv----sha---ag---hlicd---gkgrev
r--lpi------------gn-------gkd------tqgp-----itwsn
------r-qyf--ctd-----laq-------------------gnnt---
hsccl-lphygdtre-ssfkvv--geqs---sa-a-qriaskdflpep-p
--cviftpap-kkikpryke-st-n------------------v-f-vrh
ippaa---qlvath------ga-------phgg---kclktke--nal--
-m-vev-vkldl---la-----r----g-dmdvgdfpan--fy----kkp
rlasvfai-nqlv-----y-------------vv---al----ggiadvy
rsvp-----lvadks-------------k---------------------
---ef--stalelt--e-----pq---ggwk-a-nlk-ield------h-
-----lcnapaslcn-hlgpkkk----hqeal-------wtpcaleqmla
ecalkvae-nt-cvticdnfplkfhdsl--y-------------------
-------lla-cseenytaaatd--------aitpgdytt-rn--t---f
---snqlv------qyk----d-------snakrl-lppittfk-pgy--
nv-----avg--n--d---vlrfae-------ts----elhsc---pgrc
lsdrcrlri---g-rnehnsiseldp-krva-----l---fd--ls-gi-
-l----scl--s------ssd--v---igqdspskpavvvqkwqka--qk
wlmgll---ggvek--------spvv------------vg--ygtv-dv-
-lcsnnl---kgaa----dq-
>ENV_SIVM1/24-528
--gsfqanlfmvkq--g-p-ln-eltlir-------khkhdmnham--s-
-ce-------------sanfv----she---an---hltce---gkgrgv
r--lpi------------gn-------gsd------tqap-----itwsn
------r-hyy--ctd---dmla---------------------------
-avcl-lphygdtre-tsfrvv--geqs---ta-a-arvaskeflpap-p
--cviftdap-kkik----------------------------------h
lppa---------h------ga-------phgg---pclktke--dal--
-m-ier-vkldl---lt-----r----s-tmevgefpad---h----lkp
rla--fai-nqlv-----y-------------av---al----ggiaevy
rgvp-----lvadkt-------------a---------------------
---ef--etalelp--e-----gq---ggwk-g-ylk-idls------h-
-----lchapqslcaphl--kkkilvrqqeal-------wapcaleqmla
tcalkv---ns-ciricdvfplkfhdsl--y-------------------
-------lla-cskenytcaasd--------aitpgdytt-rn--s---f
---sgqrv------qyd----d-------sypkqlkmspittyk-pgc--
na-----avg--n--d---vlrfae-------ts----elhsc---pgrc
lsarcrlki---g-rnehnsiseles-kwvg-----m---fe--la-gi-
-l----acl--s------agd--v---igqdgrmkpavvvqkwqsp--qk
wlmglw---tsvek--------ssvv------------lg--ygtv-dv-
-lcannl---kgts----dq-
>node19
--gsfrgtlfmish--g-p-lt-glsqiv-------khkndrhhsm--t-
-ce-------------sanwv----ghg---ag---hfkcd---gkgrev
r--lpv------------gk-------gka------aqgp-----itwsn
------r-ryf--cte-----vaq-------------------grnh---
hsgcl-lphfkdtre-snfkvv--geqg---sa-h-qriaamdftpep-p
--yvvfspap-kkikprytd-sa-n------------------v-y-arh
i--va---hlvath------at-------shgg---kclkkke--agl--
-mtvnifvkldl---la-----r----g-amdagnfpas--yy----pkp
rltsvfgi-kqlv-----s-------------vv---ni----ggiadvy
rsvp-----lvsqks--tativrm----k---------------------
---ef--stawe---------------q-wt-s-slk-ield------h-
-----lcnapaslcn-plgpkkr----hpsal-------wtpcaleqsla
ecalkvti-ns-cvtvcddf----------y-------------------
-------lla-cfeenytasatd--------gitpndyst-rn--t---y
---snhlv------eyk----d-------snakrl-lppittfk-pgy--
nv-----avg--n--d---vlrfaa-------tk----elhnc---pgrc
lsdrcrlri---g-rsehnsitdvea-krva-----l---fn--ltkgi-
-l----scl--s------ssd--v---vgqdspgkpavvvqnwqka--qk
-lrglllqaggvek--------ppvv------------vg--ygtt-dv-
-lcsnnl---kgaa----dq-
>node7
--glf----fmigq--pdv-le-gltdvn-------khkhnrannq--k-
-c---------------dnwvvysgyl----sg---hfrcn---grsrqv
a--lpv------------ls-------gkd------rpgs-----gt---
--------q----cpg-----ltkp--s-----glk----lsgtnefadh
---nl-lkqcsears-vtyklv--g-ls---vg-a-h-sapkd------p
--clafvptggkkmk------ss-l-------tv-------lde-f-t--
--paekshkla-----ethiec--aqgprphgslsnkclk--p--enl--
-l-vnt-vlpdi---ls-----vnkskg-qldlgdleap--fy----tlr
rlyskfsi-ttev-----s-------------ig---sagaaiannakvf
rgvppsv--l--gtp-------------ad-lqtekstrrickakqta--
---ef--pscl-lsyke-----ppvicsalitalela-v---------k-
----p------yl-------rsk-----ngdl-------wtpcglpemly
--gl--lkmg-----------------ggkystlq-dvrvicflefs---
-------tls-cgknkyf-nate--------p-----fak-rnhkm---f
---esklv------ayk----kt-k---askykkf-lppittfhapgi--
gp-----atg--t--s---vtrsgp-------pk----dlh------gra
lperghlki---g-r-------k--p-kega-----l--sysdelh-pl-
-l----dcl--q------qgs--vt--ggeda-----efg----ks--er
tlassi---nsitr--------gpca-ldti--dvaaspsrqygsv-pd-
-lc------------------
>node11
--gsfrgtlfmish--g-p-lt-glsqiv-------khkndrhhsm--t-
-ce-------------sanwv----ghg---ag---hfkcd---gkgrev
r--lpv------------gk-------gka------aqgp-----itwsn
------r-ryf--cte-----vaq-------------------grnh---
hsgcl-lphfkdtre-snfkvv--geqg---sa-h-qriaamdftpep-p
--yvvfspap-kkikprytd-sa-n------------------v-y-arh
i--va---hlvath------at-------shgg---kclkkke--agl--
-mtvnifvkldl---la-----r----g-amdagnfpas--yy----pkp
rltsvfgi-kqlv-----s-------------vv---ni----ggiadvy
rsvp-----lvsqks--tativrm----k---------------------
---ef--stawe---------------q-wt-s-slk-ield------h-
-----lcnapaslcn-plgpkkr----hpsal-------wtpcaleqsla
ecalkvti-ns-cvtvcddf----------y-------------------
-------lla-cfeenytasatd--------aitpndyst-rn--t---f
---snhlv------eyk----d-------snakrl-lppittfk-pgy--
nv-----avg--n--d---vlrfaa-------tk----elhnc---pgrc
lsdrcrlri---g-rsehnsitdvea-krva-----l---fn--ltkgi-
-l----scl--s------ssd--v---vgqdspgkpavvvqnwqka--qk
-lrglllqaggvek--------ppvv------------vg--ygtt-dv-
-lcsnnl---kgaa----dq-
>ENV_SIVV1/24-538
--glf------------ev-ld-gttkan-------khrhnreann--r-
-c---------------kdwvvysgyl----sg---hfhcn---gmsfqv
skplpv------------la-------gkd------rpgs-----gg---
--------q----cp---------p--nhegrpgls----lsgthefanh
---tl-limgtqars-vnfdlv--q-lg-npvg-a-h-aas---------
--claykaagv--qm------tg-i-------vd-------edsef-e--
--fgnkshkla-----dthid----qgprphgald---mg--l--etl--
-e-vda-llpsi---lslstfhvekakg-nldlgsleapakffhtnatlr
rlygkitv--aev-----s-------------id---ssgattsnnsmlf
rgvppsa--l--gsp-------------akllqsdkgtkrickgnqttts
eafef--ppcl-layke-----ppaicdalfsalels-p---------k-
----p------yl-------rsd-----gidl-------wapcelselly
--gf--mklg-----------------tgkyttld-htkvlcfqdvs---
-------tls-cgkvkyf-nste--------p-----fakprghkm---f
---pmklv------pyk----ktrk---atkyksl-l-------pagi--
gp--ehgatg--k--p---ldr---------------------------a
lgergrlki---g-r-------g--p-eaga-----i--pysgelh-pl-
-lk---dhigre------qgr--vt--gsgev-----qfs----ky--er
tiggfm---dhath--------gpsa-lati--d-agapsrqsgrp-pe-
-vc------------------
>node10
--gsfrgtlfmish--g-p-lt-glsqiv-------khkndrhhsm--t-
-ce-------------sanwv----gha---ag---hfkcd---gkgrev
r--lpi------------gk-------gkd------tqgp-----itwsn
------r-qyf--cte-----laq-------------------grnt---
hsccl-lphygdtre-snfkvv--geqs---sa-a-qriaamdftpep-p
--cvvfnpap-kkikprykd-st-n------------------v-y-arh
ippva---qlvath------gt-------shgg---kclkkke--aal--
-m-vevfvkldl---la-----r----g-dmdagnfpas--fy----kkp
rltsvfgi-kqlv-----y-------------vv---ni----ggiadvy
rsvp-----lvsqks--tativrm----k---------------------
---ef--stawe---------------g-wk-s-slk-ield------h-
-----lcnapaslcn-hlgpkkk----hpdal-------wtpcaleqmla
ecalkvtq-nt-cvtvcddfplkfhdsv--y-------------------
-------lla-cfeenytasatd--------aitpndyst-rn--t---f
---snhlv------eyk----d-------snakrl-lppittfk-pgy--
nv-----avg--n--d---vlrfae-------tk----elhsc---pgrc
lsdrcrlri---g-rsehnsisevea-krva-----l---fd--lt-gi-
-l----scl--s------ssd--v---vgqdspskpavvvqnwqka--qk
-lrgll---ggvek--------ppvv------------vg--ygtt-dv-
-lcsndl---kgaa----dq-
>ENV_HV2G1/23-502
--gsfrgtlllishlmg-p-lt-glsqiv-------khksdrhhsm--s-
-ce-------------sanwv----glg---ag---qfkcd---gkgrvv
r--lpv------------gk-------aks------aqgs---------n
------rkryf--cae-----vaq-------------------grnq---
hsgcl-lpqfkdtqe-snfkvv--geqa---ga-h-qriaamdftpep-p
--yvvfsptp-kkikprysd-sa-e------------------v-y-grh
i--fl---hlvath------at-------shgg---kclkkqe--ggi--
-mtsnifvklel---la-----r----l-amdapsfpas--yy----pk-
rlssvfg-----------sqkfqliacvlvdegv---gi----agtadvy
rsvp---gllvsqks--tptidrm----k---------------------
---ef--sttwe---------------q-wt-s-slk-ield------h-
-----lcnapaslcn-plgpkar----hkkal-------wipctleqsla
ecalkvti-nt-cvtvcddf----------y-------------------
-------llaicfeenftasatd--------altpndytt-ag--t---i
---snhlv------eyk----d-------tnakrl-lppittfk-pgy--
gv-----gvg--n--d---vlkfea-------tk----elhnc---pgrc
ls-rcrlri---g-rsehnsmtdvpa-rrvd-------------itkgi-
-l----scl--s--lkeftsd--i---vgqdspgkpaiviqnwnka--qk
-lrglmlqaggqqk--------ppvi------------vg--ygtt-av-
-lcsnnl---kgav----dq-
>node18
--gsfrgtlfmish--g-p-lt-glsqiv-------khkndrhhsm--t-
-ce-------------sanwv----ghg---ag---hfkcd---gkgrev
r--lpv------------gk-------gka------agsp-----itwsn
g----sr-ryf--cte-----vaq-------------------grnh---
hsgcl-lphfkdtre-snfkvv--geqg---sa-h-qriaamdftpep-p
--yvvfspap-kkikprytd-sa-n------------------v-y-arh
i--va---hlvath------at-------shgg---kclkkke--agl--
-mtvnifvkldl---la-----r----g-amdagnfpas--yy----pkp
rltsvfgi-kqlv-----s-------------vv---ni----ggiadvy
rsvp-----lvsqks--tativrm----k---------------------
---ef--stawe---------------q-wt-s-slk-ield------h-
-----lcnapaslcn-plgpkkr----hpsal-------wtpcaleqsla
p---kvvi-ns-cvtvcddf----------y-------------------
-------lla-cfeenytasatd--------gitpndyst-rn--t---y
---snhlv------eyk----d-------snakrl-lppittfk-pgy--
nv-----avg--n--d---vlrfaa-------tk----elhnc---pgrc
lsdrcrlri---g-rsehnsitdvea-krva-----l---fn--ltkgi-
-l----scl--s------ssd--v---vgqdspgkpavvvqnwqka--qk
-lrglllqaggvek--------ppvv------------vg--ygtt-dva
glcsnnl---kgaa----dq-
>node17
--gsprgtlfmish--g-p-lt-glsqiv-------khkntrhhsm--t-
-ce-------------wanwv----ghg---ag---hfkcd---gkgrev
r--lpv------------gk-------gka------agsp-----itwsn
g----sr-ryf--cte-----vaq-------------------grnh---
wsgcl-lphfkdtre-snfkvv--geqg---sa-h-qriaqmdftpep-p
--yvvfspap-kkikprytn-sa-n------------------v-y-arh
i--la---hlvath------as-------shgg---kclkkke--agl--
-mtvdifvkldl---la-----r----g-amdagnfpas--yy----pkp
rltsvfgiakqvv-----s-------------vv---ni----ggiadvy
rsvp-----lvsqks--tativrm----k---------------------
---ef--stawe---------------q-ws-s-slk-ield------h-
-----lcnapvslcn-plgpkkr----hpsal-------wtpcaleqkla
p---kvvi-ns-cvtvcddf----------y-------------------
-------lla-cfednytanate--------gitpneyst-rn--t---y
---snhlv------eyk--vtd-------snakrl-lp----fk-agy--
nv-----atg--n--d---vlrfaa-------tk----elhnc---pgrc
lsdrcrlri---g-rsehnsitdveackrvatqpsal---fn--ltkgi-
-l----scl--s------ssd--v---vgqdspgkpavvvqnwqka--qk
-lrglllqaggvek--------ppvv------------vg--ygtt-dvg
glcsnnl---kgaaakgvdq-
>ENV_HV2BE/24-510
--gkwratlm-----------t-glgqil-------khrnarlhtinhtp
rce-------------sanwv----grg---ak---hlncsccvgkare-
---lpv------------gk-------gkpndvgkpagsq-----iiwsn
gdrpgsr-ryf--cte-----vaq-------------------grnh---
hpgclilphfqd------fsvf--geqgv--sa-h-qriaavhfrpep-a
--yvvfspap-lkikphytd-sa-n------------------v-f-grh
i--ve---hlvavh------at-------sqgg---tclkkke--agl--
-mtvdifvkldi---la-----r----g-amdagdfpas--yy----pkp
rltsvfgi-kqlv-----s-------------vt---hi----ggvgrvy
revp-----lisqkk--tatiipr----k---------------------
---ef--gtawe---------------h-rt-s-slk-ipld------e-
-----lctapaalcn-algpkgr----------------wapcsleqsia
----kvvf-nn-cvfvcddf----------y-------------------
-------lfa-cfeekniasatd--egkfsggitpnsyag-rn--a---y
---atqvv------eyk----d-------ggakrl-lhpittmk-pgy--
ki-------------d---vlrfaa-------tk----elhac---psrc
laercryri---g-rtehtpitdvev-krva-----l---fn--ltkgl-
-v----scl--s------sgdmvi---vgqeapgkpacvvqklqka--qp
-lrglllqaggvqk--------qpvm------------va--ygtt-dva
glcsnal---kava----de-
>ENV_HV2NZ/24-502
--snpkgtlfmish--g-p-le-glsqia-------mhedtrhhsm--t-
-cq-------------wanwv----ghg---ag---qfkcn---gkgrev
r--lpv------------nk-------gka------agsp-----itwnn
g----gr-ryf--cee-----vaq-------------------grdy---
wsgcf-lghfkntre-snfevvk-geqn---sanh-qrieqin-------
--yvvfsaap-k--ksrftn-ss-n------------------v-y-akh
i--la---qlvath------as-------------------ke--agl--
-maieafaklel---le-----r----a-akdagnfpgs--yf----pdp
rlss--gitkqvv-----s-------------vv---gi----gaiadvy
rsvt-----ltskka--taaivrmqpdik---------------------
---ef--stdre---------------q-wy-s-glk-ield------h-
-----lcntpvslcn-plgpkrr----rsgaltfvvaakwapcaleqkla
p---kvvi-ns-cvtvcddf----------f-------------------
-------lla-cfeenyashate--------gitsheypt-kn--a---y
---vshlv------eykip----------snakkl-lp----fk-agy--
nvak---aig--n--e---vlr--a-------am----elhsce--pgrc
lsdmcrlrl---a-rsehksvnnveackrvatqpsal---fn--ltksi-
-l----scl--s------agd--v---ldegspgkpavvvqnwqka--qk
-lrglllqagsvek--------ppiv------------dg--ygtt-elg
glssnnlgqvkgtdakgvdq-
>ENV_SIVG1/22-522
--glf----fmlgq--pdv-le-gltdvv-------khqhdrsniq--k-
-c---------------anwvvyagyl----sg---hfrcn---ektrqi
l--lvv------------ls-------ggd------rags-----gt---
--------q----cpg-----ltkp--s-----plk----lggkneytdh
---el-laqcseaws-vkyklv--g-ls---vr-a-h-saakd------p
--vlafvptggkkqk------sn-l-------tv-------lde-f-t--
--paekshkla-----easiec--aqgprphgslgkkclr--p--egl--
-l-vka-vlpdi---ls-----vnkrdg-ql--ggldap--fy----tlr
rtyskfti-ttev-----s-------------ig---sagaaiannakvf
rgvpasa--l--gtg-------------tk-lqtek-trkictakqsa--
---ef--pscm-lsyke-----ppvicsalitnlela-i---------r-
----p------cl-------rsk-----ngdl-------wtpcglpemly
--gl--lkkg-----------------ggkyst-q-dvriicfldfn---
-------tls-cgknkyf-dkte--------p-----fak-rnhkm---f
---esklv------ayk----kt-k---askykkl------tyhaptl--
gp-----lt------s---vtksgp-------pk----hlh------gra
lpe-ghlki---g-r-------k--p-kega-----l--sysdelh-pl-
-l----dtl--q------qgt--vt--ggeda-----efd----knscqk
tlvdsi---nsitr--------gpce-sdti--dvaanpsrqygwv-pd-
-nc------------------
>node14
--gswrgtlm-----------t-glsqil-------khrndrhhtm--t-
-ce-------------sanwv----grg---ag---hlkcd---gkgrev
r--lpv------------gk-------gnp------agsp-----iiwsn
g----sr-ryf--cte-----vaq-------------------grnh---
hpgcl-lphfqd------fkvv--geqg---sa-h-qriaamdftpep-p
--yvvfspap-lkikprytd-sa-n------------------v-y-grh
i--va---hlvath------at-------shgg---kclkkke--agl--
-mtvnifvkldl---la-----r----g-amdagnfpas--yy----pkp
rltsvfgi-kqlv-----s-------------vv---ni----ggiadvy
rsvp-----lvsqks--tativrm----k---------------------
---ef--stawe---------------q-wt-s-slk-ield------h-
-----lctapaslcn-plgpkkr----hpsal-------wtpcsleqsia
p---kvsi-nk-cvtvcddf----------y-------------------
-------lla-cfeekytasatd--------gitpnsyat-rn--t---y
---snhvv------eyk----d-------sgakrl-lppittfk-pgy--
nv-----avg--n--d---vlrfaa-------tk----elhnc---pgrc
lsdrcrlri---g-rsehnpitdvea-krva-----l---fn--ltkgi-
-l----scl--s------sgd--v---vgqdapgkpavvvqnwqka--qk
-lrglllqaggvek--------ppvv------------vg--ygtt-dva
glcsnnl---kgaa----dq-
>ENV_SIVGB/47-569
---tf----ykk----slrc-ie---q-----------rqdg--gq--k-
-cpkqnlkvsqelyagas-wve--tfg-ydeqgkrehldad---qpa--s
d--ldlyqtedpsaksptllmgtlelfgge------gstkegpvsts---
--------q----ypakqk--vtspncm-----ssnfgfnll----svda
----------------llgdva-ng-ad---ts-g-r-erilg-----tk
--aldyh----kald-----fvhge-iypedl-ialerfsvvsl-vfa--
--kgtkg-rl--pagvetvkpl---------tp-----lk--sygcaidg
hq--sp-kvkei---mp-----t---vsr--ggshlrde--f--------
nffs------a-vvmgwy---------------gsng-----------h-
---------l--gkk-------------r---------------------
---efeeegcy-lt-pnhntkmi-----------gwkqn---kfpashth
aakkg-------------------------i-----------------le
--ny--st--------------------ghhavlqk-k-slpy-erkhfl
fesqkavgla-aaykkdc-ags----------------ad-rdfsftkhy
----vkyvldgiks--------f-arqnksl--kl-laktdvlh-p-lkg
------------egnllkkpirhgqckphcvcaaksskyihpc-------
----nnpgvkiagg--lfictcq--s-rdtq-----lkfvaq--ll-sqn
ai-laqtcf---------pad--lvks--ad-------lk----ne--ed
plgnvf---elmvktasrtnnvrssaraqytetgvaghc-----rlimt-
-lcc-----------------
>node8
--gsf----fmisq--pdv-le-gltevd-------khkhnrsndq--k-
-ca-------------ddnwvh--syl----ag---hlrcn---grarqv
a--lpv------------ls-------gkd------rpgp-----gt---
--------q----cps-----ltkp--s-----glk----lsdtndfanh
---nl-lkqcgdars-vsyklv--g-vs---vg-a-h-sapkn------p
--cltfpptpmkkmk------ss-n-------tv-------lde-f-a--
--saekghklailpgmethiqc-------phgsfenkclk--p--eal--
-l-vki-vlpdi---lt-----v---kg-eldlgdlrap--fy----klr
rlyskfai-ttdv-----f-------------ig---sagtakgdnakvl
rgvppsv--l--gtp-------------a---------------------
---ef--ptcl-lsyke-----pp---stvkealelt-i---------k-
----p------yl-------rsk-----qddl-------wtpcglaemln
--gl--lkmd-----------------tgkysslq-karvlcflefs---
-------tls-cgthkyf-vate--------p-----fak-rdnrl---f
---esklv------ayk----kt-k---atnykkf-lppistfhapsi--
np-----aag--t--n---strsae-------ps----dlhac-grpgrc
lpershlri---g-rneflslse--p-kqaa-----l--gys--lh-pl-
-l----acl--q------qgn--vd--ageda-----plg----ks--ek
tlassv---gpitr--------gpca-hdai--evnahps--ygsv-dv-
-lcv-----------------
>ENV_HV2CA/25-512
--gsprnalfmksn--g-p-lh-glsqiv-------thkntrcnsk--t-
-ce-------------waglv----g-----------fkcd---gkgrev
r--lpv------------gk-------ska------ggsp-----itwsn
g----nr-ryf--cte-----vaq-------------------grnh---
wsgcl-lphfkdkrd-snfrve--geqg---sa-h-qkiaqadfsa----
-----fgpap-kkikqrytn-sa-n------------------v-y-arh
t--ln---hllakh------qs-------shgg---kclkkkn--agi--
-mtviifvkleftggla-----r----g-pmdfgslpas--yy----hkp
rlnsvfssqkqmv-----s-------------ta---nv----ggiadty
rtvp-----ldsqktaqtasivrm----k---------------------
---ef--stvwe---------------q-ws-s-slk-ield------h-
-----lcnapvslah-plgpkqr----hplal-------wspcaleqkla
p---kv-l-dgrcvtvcddf----------y-------------------
-------lla-cf-dnytgdkte--------gikpnqyst-rn--t---y
gklsnhlv------yyk--atd-------anassv-lp----fk-dgy--
nv-----cig--n--k---vlrfga-------tk----elhtc---pqkc
lsspcrlti---g-rseqnstsdieacervatqpsam---ln--ltngv-
-l----kcl--sfd----asd--v---vgqdrpgkpavvvqewqkk--qk
-lrglll--ggvdk--------apiv------------vg--ygtn-alg
glcsknl---kgeaakgvdr-
>ENV_HV2D2/24-513
kggrfrgtlfmish--g-p-lp-glsqivdysvfda---ndrqhp---t-
-cn-------------ntswv----gha---ag---r---------gq--
----s--------------k-------gks------tq-----------g
------k-qnf--cte-----msq-------------------grka---
hsccl-lahygdtrelhkykvl--ddqt---aa-an----tmdstakp-c
--cvafsppp-kkirprykt-vt-n------------------i-y-akh
ftpva---alvash------gt-------khgd---kclknre--aal--
-----vfvkldt---la-----h----g-didagnftaa--fy----kkp
rltsvmgi-kqqv-----y-------------av---ni----ggivdfy
rsvp-----lvrqkn--tatvvrm----k---------------------
---sl--stawq---------------g-wk-----k-inld------h-
-----lcnapadlcn-qlgpkkk----hpaal-------rgpcaltqqla
dcrltvtq-kt-hgt--aefalqfhsgv--y-------------------
-------pla-cfeeksta--td--------av-pyeyst-k-------f
---iqhlv------ehd----d-------tnamil-qnpiitfk-vgy--
kv-----gvgdgs--e---glrfge-------ti----elhpv---agrc
lsdrrrlri---g-ksdngsit--dv-krva-----l---fd------i-
-l----gcl---------ssd--t---vgqnspsnptvvvqswnse--qk
-lrgll---ggvek--------ppvv------------vg--yeat-dv-
-qcteql---kgqa----kq-
