>ENV_SIVG1/22-522
lgkrsslafe------dg-estkn-----------------------qck
vkaeggr---r----yfqglkdt--malpgtepqedn-----t-l-lkr-
-----s---pkssnvtyck---s-------------atate--pthiikn
lasap---kilakaaq--dgeqt---sqsg------aysvkavr------
--------qpv--lss---g---nhkktg--------atniadetcv---
vnmavkrsvtk---makfcktssitfefrika--agras-khlm---f--
--iak-lmg-----itytptkav--paliknl------c--dehllhvak
--d-e--egtektmgq---psttldqrgq-ag-----aelq---------
----------------frfwapq-gqvpd-nvr---sa----l-------
-l--shg------i--knkhgar--------htgentt--de--r---cy
ywgtadagvmmkf-gyvvk-kar-gskdlgf--flgktlskhdedglapp
raalgsvl-----------k--c-----ta--------------p-sk--
------s-------qgqssfv----nc---el----------y-------
-pkeailaahcvgt-plr-------kqngvlkve----vie------hcf
vklfcgaal--liweviltdgsvaata-kah-phm--l------------
---------fanpelh----------------vitt------k-at-wdp
ppce--eglrcnt-----nd-------------ygylryets---pnyd-
-lvayrsa---aehl-agplasl------c--ptsa---daq----k
>node9
ls-qqdvq------------tvkglpyggve-nl-------sllnin-hr
pkaispr---rkg--lfatlias--kd----aaedks-----k-l-l-r-
-----g---p--e---fcg---admnkd-------idseqekkpqdhpsn
ltedn---kllsaake--rdqqm-kssegg------cytl-dahglfgf-
-t-----kqsv--kkkthae---vhryks-sakhnlltpkankeakv---
gklfq----nk---lgkrckvsk-----lfes--sdpss----m---f--
--vrkpcfs--------ekttts--i-kikll------vggeqallhdpp
--e-v--e----glge---pv-alnnrglwlt-----d-le------hek
tsh--gh-kh------f-----k-gqapdlsva---ts----l-------
-l--sqk----kgv--kt-------------htegdll--pk--p---cy
ywgatdag----i-gyn---ekr-etlqagc----a--vskqqas--ape
rpnitslt-----------g--c-----qk--------------p-fksv
atqysas-------kggaaia----ec---d-----------f-------
-nagtvlvmhcvkgs--k--------------ve----vir------pcy
v----------lfr---niasivantt-ksv-nrdfahkq----------
nllcinkhyi---qlnca-sdpg---------r--q------w-pdgysa
dpie--esahctn-----yh-------------yaa------ncgpgye-
-tvdypda---geyl-glplvdt------cyta---------lce-s
>ENV_HV2BE/24-510
ls-gqevq------------tirglpy-gva-hl--------lla-k-rr
pkgishkkqdvkg--llatligv--ke----aasdks-----k-l-l-l-
-----a---p--e---ycsgelsdmhkqkafalvivdneqdnkpqnhpan
ltadh---klivapke--rkmlqakssegs------yatl-erpalfsf-
-s-----dqkt--ktrihae---ahryksqsskhnllpskp--eekt---
g---------k---laksckvlr-----lfqsplddpss----v---fmr
tcvqagclskldfh---ekltti--i-kikfl------lgeeqgpvhdpp
--e-e--e----slgnlldnv--kynrgl------------amnnpfhed
tlh--ah-kn------i-----n-dqqngltas---tc----l-------
-------pkvkrgm----------------------la--rk--p---cy
ywgpasqa----a-gyq---dkk-iplqagc----a-------as--aq-
---iaclt-----------gric-----ek--------------a-f---
-kryspsga-ttd--ggaama----dc---d-----------f-------
-a-----tgpiikge--kvfvkrts-------heellyvvpkqnqs-pcy
v----------lfk---nsgfivvntv-stt-nrnfahmq----------
gllyinkavi---linggpcnpg---------n--e------w-pdgysa
dpvd--etahrasfel--yh-------------yas------ncapgsq-
-aldypda---geyl-glalvvs------cytv---------lce-s
>ENV_SIVV1/24-538
lgtknswafegmkkspdg-gt------assa-ev-------kyl---hck
vkaevgr---r----sipglqdt--ekltittpqenn-----t-l-lqrs
knftws---p--g---yck---aaadks-------qtsaak--cphvikp
ngnds---hevgksaq--dgpph---gesgk-----vygakavk------
--------epvvllgg---h---ahkkgg--------tikiadqscv---
---gv----sk---l--lchtstiafhfrfev--laksw----l---f--
--vnm-ikg-----syytplkav--p-lvkll------c--defvlnvkk
--e-ea-dgtdktmgr---vaaalnsrlw-mg-----gele---------
----------------f-----q-gvvpnlhis---t-------------
------------------kqgakrqvkskw-qkggssi--dk--raipkf
hwgspdagvlkkf-gyvvt-qks-etknlgyrd-lakdvfkpedsgipph
haalgeaq-----------e--c-----eq--------------p-sk--
------h-------nervtfvlarwnc---ek----------f-------
-tleevlayrcvdt---k-------aqns--kid----tie------hcf
p----------liwevll--gntssta-kmf-phi--d------------
---------fanaeme----------------piks------k-rk-weg
vacq--eglkcsa-----fd-------------yaylryend---pkyn-
-lv----a---akylagkilasgkarpstpadpptaafrdlq----k
>node8
lgkrtdvpyv------ag-etikglpyggst-nv-------nllkvkqhk
pkavapr---r----hlsglqdt--ealpgsapqenn-----k-l-lkr-
-----g---p--d---yct---strnkk-------ieaetn--prhipkn
lpsds---kllgkaaq--ngeqi---gqsg------vysaknvr------
--------esv--lgs---e---ahkkrg-------pttkisdencv---
vhmhh----nk---makfckvssipfhflfql--aarrs----l---f--
--vdk-lmg-----stfpptkat--p-likll------csgdenllhvar
--d-e--egtdssmge---pv-sldqrgl-sg-----eelq------hsg
ns---ln-kf------f-----h-gqvpdlnvs---sa----l-------
-l--shs------i--kakhgak--------htegeav--nk--w---cy
ywgiedagvlkkv-gyiit-kir-atqdlgy---lgndlsrpdadgltpt
rasigsah-----------v--c-----ek--------------p-sk--
------n-------kgnttfv----nc---e-----------f-------
-pkdtvlaahcvgst--k-------rqds--kvd----vie------tcf
v----------law---ningtvagta-kgf-phlyan------------
---------fsnselh----------------pivs------r-pt-wga
spce--dgahctt-----ad-------------yaylryqth---pnyd-
-vidydka---aeyl-asplasv------cfapaia---dle----k
>node18
ls-aqevq------------tvkglpyggve-hl-------nllnik-hr
pkaispkkqnrkg--lfatliaa--ke----aaedks-----k-l-l-r-
-----g---p--e---ycg---sdmnkdk----aiidneqenkpqdhpan
ltadh---klisaake--rkqqmakssegg------yatl-eapalfgf-
-t-----kqtv--ktkvhae---vhryksqsskhnllapkadkeakv---
gklfq----nk---lgkrckvsr-----lfqsplddpss----v---fmr
vcvrkpcfs--------ekttti--i-kikfl------lgdeqgplhdpp
--e-e--e----glgelldpv-akynrgl------------kmnnpfhen
tnh--ah-kn------i-----n-dqqpgltvs---ts----i-------
-------qkvkrgv--kt-------------htegdll--sk--p---cy
ywgaaaqg----s-gyn---dkk-etlqagc----a-------as--aqe
rpsiaclt-----------gilc-----qk--------------a-frai
asryspsgg-tsdgkggaaia----dc---d-----------f-------
-n-----vmhcikge--kkfvkats-------ge----vvrkqnqc-pcy
v----------lfr---naasivvntv-stv-drdfahkq----------
nllyinknyi---lingg-snpg---------r--q------w-pdgysa
dpid--etahcasf----yh-------------yas------ncgpgae-
-avdypda---geyl-glplvvt------cyta---------lce-s
>ENV_HV2G1/23-502
ls-aqaih------------tvkalnyggve-yl-------kilnik-nr
skaigpkkqnrkg--lfaaliaa--ke-----aedks-----k-lll-r-
-----c---p--e---ycg---aamnksk----aiidnenekrpeehpan
-tseh---kliresse--rkqqmaksnegg------yatl-egpalfgf-
-t-----kdqv--ktkvhae---vhrykspsskhnllapkadkeaki---
gnl-------k---makrckvsr-----lfqsplddpsk----v---fmr
vcvrkacfs--------aktttslgs-iirfl------lgddqgplhdpp
--e-e--e----glgelldpi-akyntsl------------kmnnpfqgs
tnh--ah-kn------i-----d-gqepamt-----vs----i-------
-------qkvkrgt--kn-------------htdfdll--dk--p---cy
ywaaspqg----p-gyn---dkk-eklqagc----a--vqkqqap--ake
hphiacly-----------gilc-----qk--------------t-frav
asrnspsgg-tsdgkggaait----dc---d-----------f-------
-s-----vmhcvkge--k--------------ge----vqrkenqc-acy
v----------lfr---naasivvntv-stv-drdfahkq----------
hllyintnyi---lingg-snpg---------------------pdgysa
dpid--etahcvsf----yq-------------yan------t-----e-
-avdypna---gqyl-glpivvs------cyta---------lce-n
>node19
ls-aqevq------------tvkglpyggve-hl-------nllnik-hr
pkaispkkqnrkg--lfatliaa--ke----aaedks-----k-l-l-r-
-----g---p--e---ycg---sdmnkdk----aiidneqekkpqdhpan
ltadh---klisaake--rkqqmakssegg------yatl-eapalfgf-
-t-----kqtv--ktkvhae---vhryksqsskhnllapkadkeakv---
gklfq----nk---lgkrckvsr-----lfqsplddpss----v---fmr
vcvrkpcfs--------ekttti--i-kikfl------lgdeqgplhdpp
--e-e--e----glgelldpv-akynrgl------------kmnnpfhen
tnh--ah-kn------i-----n-dqqpgltva---ts----i-------
-------qkvkrgv--kt-------------htegdll--sk--p---cy
ywgaaaqg----s-gyn---dkk-etlqagc----a--vqkqqas--aqe
rpniaclt-----------gilc-----qk--------------a-frai
asryspsgg-tsdgkggaaia----dc---d-----------f-------
-n-----vmhcikge--k--------------ge----vvrkqnqc-pcy
v----------lfr---naasivvntv-stv-drdfahkq----------
nllyinknyi---lingg-snpg---------r--q------w-pdgysa
dpid--etahcasf----yh-------------yas------ncgpgae-
-avdypda---geyl-glplvvt------cyta---------lce-s
>node14
ls-aqevq------------tikglpyggve-hl-------nllnik-hr
pkaispkkqnrkg--lfatliga--ke----aaedks-----k-l-l-r-
-----g---p--e---ycg---sdmnkdk----viidneqenkpqdhpan
ltadh---kliaaake--rkqlmakssegg------yatl-eapalfgf-
-t-----kqtv--ktkvhae---vhryksqsskhnllapka--eakv---
gklfq----sk---lgkrckvsr-----lfqsplddpss----v---fmr
vcvqkpcls--------ekttti--i-kikfl------lgdeqgplhdpp
--e-e--e----glgelldpv-akynrgl------------kmnnpfhen
tnh--ah-kn------i-----n-dqqsgltvs---ts----i-------
-------qkvkrgv--kt-------------htegdll--sk--p---cy
ywgaaaqg----s-gyn---dkk-itlqagc----a-------as--aqe
rpaiaclt-----------gilc-----ek--------------a-frai
asryspsgg-tsdgkggaama----dc---d-----------f-------
-g-----vmhcikge--krfvkrts-------pe----vvrkqnqc-pcy
v----------lfr---naafivvntv-stv-drdfahkq----------
nllyinkavi---lingg-cnpg---------r--e------w-pdgysa
dpid--etahcasf----yh-------------yas------ncgpgae-
-avdypda---geyl-glplvvt------cyta---------lce-s
>node11
ls-aqevq------------tvkglpyggve-hl-------nllnik-hr
pkaispkkqnrkg--lfatliaa--ke----aaedks-----k-l-l-r-
-----g---p--e---ycg---sdmnkdk----aiidneqekkpqdhpan
ltadh---klisaake--rkqqmakssegg------yatl-eapalfgf-
-t-----kqtv--ktkvhae---vhryksqsskhnllapkadkeakv---
gklfq----nk---lgkrckvsr-----lfqsplddpss----v---fmr
vcvrkpcfs--------ekttts--i-kikfl------lgdeqgplhdpp
--e-e--e----glgelldpv-akynrgl------------kmnnpfhen
tnh--ah-kn------i-----n-gqqpgltva---ts----i-------
-------qkvkrgv--kt-------------htegdll--sk--p---cy
ywgaaaqg----s-gyn---dkk-etlqagc----a--vqkqqas--aqe
rpniaclt-----------gilc-----qk--------------a-frai
asryspsgg-tsdgkggaaia----dc---d-----------f-------
-n-----vmhcvkge--k--------------ge----vvrkqnqc-pcy
v----------lfr---naasivvntv-stv-drdfahkq----------
nllyinknyi---lingg-snpg---------r--q------w-pdgysa
dpid--etahcasf----yh-------------yas------ncgpgae-
-avdypda---geyl-glplvvt------cyta---------lce-s
>ENV_SIVM1/24-528
lg-qqdiq------------ttkglpykdvd--v-------sllnid-hr
praiesr---rkg--lfgallan--kd----ave-kl-----k-l-l-r-
-----g---a--e---fcg---pdmnkd-------idteqekkpedqppn
ltedn---kllsaske-----qm-ktsegg----egcyvl-sahglf---
-tkvkhykqtv--kkksdae---vhryks-sakhnlltpkadkeakv---
gklfq----nk---lgkrckisk-----lfes--sepfs----m---f--
--vrkprfs--------ekksss--i-kvkhlnsprkkvggeqavlhepp
--e-i--s----glge---pv-alkgrglwla-----d-le------hdk
nahpmnh-kh------y-----q-gqapessva---vnlphkleqadagn
al--slk----kgg--kt-------------hsegell--prtsp---cy
ywgptetg----iigyn---ekrietlqagc----a--vskqlmt--apq
rpnltslt--------tgyg--c-----qk--------------p-fksv
atqysds-------kgeaaia----kclavd-----------f-------
-kagtvlimhcvngs--k--------------ve----vir------pcy
a----------lfr---s-asvvaftt-ksi-nrkfehkq----------
nllcitkhy--------------------------q------w-pdgyga
dptq--esakctk-----fq-------------faa------gcspgyq-
-tvdyena---geyl-glplvdt------csta---------lse-s
>node7
lgkrsslpfe------dg-etiknlfyggna-nv-------nll---qck
vkaeggr---r----flpglqdt--ealpgtapqedn-----t-l-lkr-
-----s---p--n---yck---saqdkk-------iatate--pshiikn
lasdp---kilgkaaq--dgeqi---sqsg------vysakavr------
--------epv--lgs---e---ahkkng--------ttkiadencv---
vhmav----sk---makfckvssisfhfrfql--aarss----l---f--
--vak-lmg-----ttytptkav--p-likll------c--dehllhvak
--d-e--egtdksmgq---psttldqrgl-sg-----aelq---------
----------------f-----q-gqvpdlnvs---sa----l-------
-l--nhg------i--kskhgar--------htggdtv--dk--r---cy
ywgtpdagvmkkf-gyvit-kir-gtndlgf---lgkdlskpdedglapp
raalgsaq-----------e--c-----ek--------------p-sk--
------n-------kghttfv----nc---el----------f-------
-pketvlaahcvgt---k-------kqns--kve----vie------hcf
v----------liweviltdgsvaata-kvf-phm--n------------
---------fanpelh----------------pitt------k-rt-wda
rpce--eglrcst-----ad-------------ygylryetn---pnyd-
-lidyssa---aeyl-asplasv------caeptta---dle----k
>ENV_SIVGB/47-569
rgkasdlkei------gge-----t--gklp-aehtsgpflqpelpkkpk
mvncsp----d--gsnadalqs---------yps-yq-----tch-ytr-
-----g---h--q---rca---sggk-----------------klvva--
--------klsgv---------------dr-tha--lya-----------
--------------------------nra-------pgctlcdkecvlkf
sr--p----dkppv-fkfckvtilplsylyln--skd------myavf--
--lak-khs-----cpeq-------a----hg---------kekl----a
gsdyg-la----nndd---gf-tmteakl-fkidacl-------------
----------------y-----ireg-----etgflae----i-------
-ityghe------dnaktkdvar-------aqnkpapigv-e--------
yy-----ktl--p-alptmn-vy-tg--------v-plfpkgdsngrrae
lpvvgertvgkkltlq-------------ktnvhtvsaqkymdki-----
--------------kllaafy----kc---k-hktiigqehtrvetgkyc
s----llt--yvnyg--t-------staa---v-------y-----ksay
t--------pywp----------ppg---afapsvyl-------------
---------------------------------slcvkvstn--------
-gsa--e----gp---kcp---------------s---yeae---kkkea
hn-e-yltgmt---l-hpnfkd--------fhrpil---tla----t
>node17
ls-pqevq------------tvkglpyvgve-hi-------nllnik-hr
pktispkkqnrkg--lfatltat--ke----aaedks-----k-l-l-r-
-----g---p--e---ycg---sdmnkdk----aiidneqenkpqdhpan
ltddh---klisaake--rkqqmakskegg------yatl-dapalfgf-
-t-----kqtv--ktkvhae---vhqykaqsskhnllapkadkeakv---
gklfq----nk---lgkrckvsr-----lfqsplddpss----v---fkr
vcvkkpcfa--------ekttti--l-kikfl------lgdeqgplhdpp
--e-e--e----glgelldpv-vkynrgl------------kmnnpfqen
tnh--ah-kn------i-----n-dqqsglavs---ts----i-------
-------ekvnrgv--kt-------------htegdll--sk--p---cy
ywgsaaqg----s-gyn---dkk-etlqagc----a-------as--aqe
rpsiaclt-----------gilc-----qk--------------a-fhpl
dsryspsgg-tsdgkggaaia----dc---d-----------f-------
-n-----vrhcikge--kkfvkaty-------ge----vvrkqyqc-pcy
v----------lfr---naasivvatikstv-drdfaqkq----------
sllninknyi---lingg-snpg---------r--q------w-p---sa
dpid--ettlcatf----yh-------------yps------ncgpgae-
-gvdypda---geyl-glplvit------cyta---------lce-s
>ENV_HV2D2/24-513
la-q--vq------------tvkglsyggie-sl-------glleip-hr
pkaispkrekrkg--lfktlisa--ke----sqqdkasnnlfk-l-l-r-
-----e---a--s---ncg---gdvtke-------iacaq------hpgn
ltvdhltkllltaakh--adqqmakssegg------cytl-ecspnfgle
wq-----sqtv--ktavhaeaagph-ykgqsasdnklapkaskeakv---
gklfq----nk---lgmsckvkr-----lfesysssptg----v---fss
vcvrkpcss---------nttis--i-kf-fl------lgee-alirnhq
--d-q--e----glgelldpi-alynqgl------------klknpfhsh
inq--ah-khyvmasgi-----p-gqqpdltrd---ts----y-------
-------pkikkgv--kt-------------hepsdll--sk--p---cy
ywgpaaaa----g-gyi---edn----qtgc----a--vlksqaa--ape
ppnitclt-----------d--c-----qk--------------p-fsnv
stqysgs-------kgatvis----ec---d-----------f-------
-n-----vmhcakge--k--------------gs----tvr-qdqc-pcn
v----------lfk---esas--vdpv-ktl-nrdl---d----------
alltihi--i---lispa-qdvg---------r--q------wapdgyaa
epigegevahcas-----fh-------------ppc------ncgpsye-
-svdypdr-----yl-glpvved------cyta---------lse-t
>node10
ls-qqdvq------------tvkglpyggve-nl-------sllnik-hr
pkaispkkenrkg--lfatliaa--ke----aaedks-----k-l-l-r-
-----g---p--e---ycg---admnkd-------idneqekkpqdhpan
ltadh---klisaake--rdqqmakssegg------cytl-dapalfgl-
-t-----kqtv--ktkvhae---vhryksqsakhnllapkaskeakv---
gklfq----nk---lgkrckvsr-----lfespssdpss----v---fmr
vcvrkpcfs--------ekttts--i-kikfl------vgdeqallrdpp
--e-q--e----glgelldpv-alynrgl------------kmnnpfhen
tnh--ah-kh------i-----n-gqqpdltva---ts----i-------
-------qkvkkgv--kt-------------htegdll--sk--p---cy
ywgaaaqg----s-gyn---ekk-etlqagc----a--vqkqqas--ape
rpnitclt-----------g--c-----qk--------------p-fksv
atqysss-------kggaaia----dc---d-----------f-------
-n-----vmhcvkge--k--------------ge----vvrkqnqc-pcy
v----------lfr---naasivvntv-ktv-nrdfahkq----------
nllyinknyi---linsa-sdpg---------r--q------w-pdgysa
dpie--etahcas-----yh-------------yas------ncgpgye-
-avdypda---geyl-glplvet------cyta---------lce-s
>ENV_HV2NZ/24-502
ls-qqpvp------------takgl--mgve-hi-------nelkik-hp
pktiepvkqnrkd--lfatltat--nd----kheeks-----k-l-l-r-
-----gtrhp--e---ycd---sdm-kdk----tiasteqenkiqdhpad
l---h---klipaakelmrkqqmtkstegg------yatl-dtpalfgf-
-t-----kqtp--ktkvqae---vhqyka---------pkadklakv---
gklfd----da---lakackvsr-----llqqplddpsg----v---fkr
icvkkpcfa--------aktttv--l-kikfl------lqdeqgpvhdpp
--k-q--e----gldelldpi-vkynrgl------------kmndsfqeq
tnh--ah-kn------t-----h-dqesglvvs---nv----i-------
-------arvlrgs--kt-------------d-----l--sk--p---cy
ywgstten----s-gyn---dkk-etlkngc----a-------ag--aqe
rptiaclt-----------gnt----------------------safrpl
dsryspsggetidgkggtaii----ec---d-----------f-------
-s-----vrhcikga--nkfvraty-------ge----vvrkqyqc-pcy
v----------lfa---saasflvatvkstv-----aqkk----------
allnitksci---lingg-snpg---------r--q------w-p---sa
naie--ettlcatf----yq-------------yps------ncgssae-
-genypda---geyl-glalvva------cs-a---------lcv-s
>ENV_HV2CA/25-512
hs-pqevl------------tvqglpfvgge-hl-------nlldik-hr
pktispktqnrlg--laatltatskke----aaedkk-----k-l-l-k-
-----g---p--e---fcs---sdmqks---------nde-nkpldvpan
ltddh---nl-ctske--rkqvmakskegg------ypal-dgpalfgf-
-i-----kqtv--ktkvnae---vhhykaqsskhdllgpk-ekdakv---
grlfa----nn---l----kvar-----lyqsslddpgsk---v---fkf
vcvkkpcfa--------dkttai--l-kikfl------lgseegplheap
--------------gksrdpv-vkyeral------------kange----
snh--sn-kn------i--------qqsglavs---ts----i-------
-------ekinrgv--kt-------------hvqgdll--sk--l---cf
-wgsaaqg----s-gyn---dkk-etlaagc----a-------as--aee
rpsieclt-----------gilc-----qk--------------v-ffsl
dsrysp--g-dadeksgaaia----dc---d-----------f-------
-n-----irhcvkge--kkfvkaty-------ge----vvrkhyac-ptn
d----------lhr---naasigvasiyttv-dqdfaskhaakntvashy
sll-ihanyi---linsg-snqa---------k--q------f-p---sa
dprd--etel-syl----yh-------------fps------ncdpgae-
-gvdfpda---geyl-glpliit------cyta---------lce-s
>ENV_HV2D1/24-501
ls-aqeve------------tikg---ggvevhm-------nllnik-hr
pkpfspkkvnrkg--lfatlika--ke----aaedks-----k-m-l-r-
-----g---p--e---fcg---sdmhkdk----vvidge-enkpqddpan
ltadh---kliaaske--pkqlmeksse-v------yttl-eapal----
-a-----kqiv--ktkvhae---vhryssqss-hdllapka--eakv---
gklfq----gk---lgksckasr-------------sss---------mc
-----pcls--------eattti--i-kipfl------vkdevgplhdpp
--e-k--e----glgelidpv-akyrrgl------------kmdnpfesd
fkh--ahfkn------i-----n-dqqsgltvs---ts----v-------
-------qklkrgv--kp-------------htegdll--sk--k---iy
ywgaaahg----s-gyk---ekk-itlgagc----a-------as--gqe
rpa-aclt-----------nilctvaffek--------------a-frai
apryspsgg-sseskggaaka----dc---d-----------f-------
-g-----vmhcikgd--rrfvarls-------pe----vvrkqfgc-pcy
------------yr---natfivvstv-sti-drdfahkp----------
nllitnkavi---hing-----gslfkfpftkf--e------w-pdgy--
--id--etahcasf----yhfkysgatmaypvgyas-------cgpgse-
-tvdypda---gefl-glplvvt------cyta---------lceqs
