>ENV_HV2G1/23-502
-------fk------dg-----sg---------spi--csgdtrv-glck
apkaevlfksvq-qgv-ggegk--fe--k----a------s---ryallg
-nsa-------------ipfs---adefqpl--dqqmdmrthlgrp--es
akltmdkatalyndtga--ekkkfktgpsd---g---dvekglqy---yn
kysvealkvy-a----syas-----------------------------y
pwe--------hhv----llmpry-smr--gkhaivtpde-------ec-
igk---------ep----s---dselgnfp---afl------a---apms
e------vt-tglfgkaqhelall-------v-----pvgsq-idalek-
----------ls-------v---------rweeslvgds-n--r-mseqv
------aegk--lsk-------stadvsg--sadtgn-----l-----es
ttqskkma----plvrsltpkirthvlyvclq---ta---lpqtc-----
-----------agseg------lk--s------cvh------ykh---l-
---------vahnqq--yd--i-------lntlt-kffpyi-nsf--n--
------------------------------sgvgtyt-g--------ckk
lhairdqa-v------------acln--g----s---slfscnt--v-l-
------l-till---qsvi----kg--dq--qvlkindgkh--an-yfks
c-ylim--w-nlv---lnagg---trgtag--------fwsaisda-kgv
kpepli-i---tedrahc-----apasle-vgegg--avckv--adarf-
sc-ae--wa---vg----g-tqfg----lgflkkl---s-vklsi-----
------teqll-----gla------------p-----------------p
--dknq--der---------------------------------------
---ie---------q-----t------haw
>ENV_HV2NZ/24-502
-------fk------dc-----se---------sviktcsantrv-glck
aqkaevlfksvqtqsv-ggeek--yq--a----vgpa---s---rya-lp
-qsa-------------ipfa---adeiqpl--dqrvd--arlgrp--en
aklslakgtalyddags--ekkkyktgtsv---s---aveqgldf---yt
meagedlmvy-a----ay-------------------------------y
swe--------hkv----ll-pry-ekr--gnhdi-apde-------ec-
igkdl-------vp----w---esdldlfpstkafl------a---pars
eanlnvlvt-dglfgkakgevslv-------i-----pvgsq----sde-
----------lsltyrfykv---------tlegflhvqn-n--k-lsdqg
------aegk--igd-------stsdi-g--asdaggsv---l-----gs
ttqskgmv----plvksftpkvrshvlyvcmq---saapllpqtc-----
-----------ahqdg------ik--ss-----cvh------ykhaskl-
---------ishnqdvfsak-i-------ldclavkffgyv-nef--q--
------------------------------pgcgt---a--------ck-
-h---aha-l------------tc---------s---gllgcht--v-l-
------l-tlil---qspa----kg--hd--qvltynvskn--an-y---
c-yldt--w-klm---lnpggsea-rttev--------f-caigds-kgv
npepqi-i---tedrsfs-----apasld-vnqgg--gvckv--sdapf-
kc-fa--ra---as----g-tqfg----mgfitkl---s-vklks-----
------tn--l-----gla------------p-----------------p
--arnqasthr---------------------------------------
---ig---------s-----t------qaw
>node8
-kva---fkaivllgtamka-npgs-----qigrmv--cgqqtkkn----
------------tsgv-pk-----fe--k----t---lk-d---r-ellg
-taarlcyevpa-----vafe---peefhplpgy----------------
-alklskgtti----gaglekqkwitgass---a---aveeafdf---yg
ptggsagqvyfagdgkhye-kt---gkidgm-dl--------------cy
twg--------hhc----vm-phf-cvq--d--vl-d-ga-------ka-
pge--tvlrl-ged----w---ee-g--r-vvseflkraht-a---lpf-
d------vs-tglynl--pelhlv-------vgpdwipdagq----l---
-------------------vam--lfdnn---------npk--r-vnmre
vattkfa--------------------------dtgg-----l----kes
qnkskknv----p-----tqkp--hvnyvnlf--vaa---gpetaavg--
--------mhhtdsas------vd--a-kva--tvh-----e--------
---------tavsqh--fs--ikgmqwfmls----kffpff-kif--k--
------------------------------rfiasfaag--------crk
vi---nqa-l------------dclt--tkkavs---pvygcpv--l-l-
------la----------k----kn--dd--qdft-iggkh--vq-f---
c-y--k--w-n-m---li-gv---tklatv--------y-atm----avm
tkeslesvrckgqespfc---st-apvad-tedse--fk--i--veanfg
vc-ta--wg---qa----gl-dhk----lgfikrkg--aminlmf-----
------te--lc---mglsvrakr-------pmknp--sphe------ip
sgdkas--dek---------------------------irt-ls----sp
tkgie---------h-----kfygaknlvw
>node17
-------fk------dg-----sg---------svi--csantrv-glck
apkaevlfksvqthgv-ggeek--fe--t----a------s---ryavlg
-ssa-------------ipfs---adefqpl--dqqmdmrtrlgrp--es
akltlakgtalyndags--ekkkyktgtsv---s---aveeglef---yn
mesgedlkvy-a----syas-----------------------------y
pwe--------hkv----ll-pry-ekr--gnhdi-apde-------ec-
igk---------vp----w---dselglfptskafl------a---ppms
e------vs-tglfgkaqeelall-------v-----pvgsq----lde-
----------ls-------v---------tleeflvvdn-n--k-mseqg
------aegk--lgk-------stsdvsg--gsdtgg-----l-----ds
ttqskkmv----plvrsltpkirthvlyvclr---sa---lpqtc-----
-----------aqqeg------lk--s------cvh------ykh---l-
---------iahnqe--ynk-i-------lntla-kffgfv-nsf--n--
------------------------------pgvgtyt-g--------ckk
ih---dqa-l------------tcle--s----s---slfgcht--v-l-
------l-till---qspi----kg--nd--qvltinvgkn--an-y---
c-yldm--w-klm---lnpgg---arttav--------f-saigda-kgv
npepli-i---tedrsfs-----apasld-indgg--svckv--adapf-
nc-aa--wa---ag----g-tqfg----lgfikkl---s-vklks-----
------td--l-----gla------------p-----------------p
--dknq--dhr---------------------------------------
---ie---------q-----t------qaw
>ENV_HV2D2/24-513
-------fk------ng-----s----------------kansfv-glck
asgaqalfksvqthga-gggdp--fe--a----a-----lp---rntllg
-gga-------------ihfqnlnagefipl--dqqvdmkp----p--qg
adivldkgiglyndsac--qkkkcqagp--------------lqf-ilfn
qdseddlkvy-n----syasnhfgagkvnnq-el--------------cy
pwd--------hhv----ll-pkyvskr--gkhal-s-ek-------ac-
igk---------ea----r---daelglf-taeayi-----------lms
e------is-tgly--veaeiall-------n-----pvgga----ldh-
---------ils-------v---------tlsetlivdn-s--k-msdrg
------aesd--lgkalkspstsssivpgkkgadkgg-----l-----dt
ttqnkkav----plirslsarkrihvtyv-lk---ta---ipqtc-----
-----------vqstg------qq--g------cvh------gkn---l-
---------ithnhq--yd--i-------lktla-kmypyv-hsf--n--
------------------------------rsvgtydpg--------cgr
ts---eqn-l------------acln--s----g---svsgcntcdm-l-
------l-vtllcdvvsla----kg--dd--qiltlrvg-----------
-----------mm---lnngg---triigv---pcpkvf-seig------
--spli-i---agdksfc-----a----------g--fvcsv--sdapf-
is-ae--wg---sa----g-sqfg----lgfnkgl-aqt-vtlkf-----
------td--lclvdlgvh------------h-----------------p
--dqna--dqr---------------------------------------
---ik---------q-----t------qaw
>ENV_SIVV1/24-538
-kla---ftaiglavlardasppgsym---rmgrlv--cgvqtkss----
------------cegf-ak-----f--------t---fk-dpqgr-etlg
-iaehlc--iplvktttveft---plkfhp---y----------------
-slkpsree-------asldkqthttrdcy--------heesfi------
ptgg----vyfigdtkyye-ps---ktsegmidl--------------yy
tw-----------------m-khs-cvq--e--gl-q-a-vf------pk
pse--talrigpts----w---ge-g--k-ymse--krvht-l-all-f-
d------vvpdgfyal--pnlhvvkgeqsnaygpqwlrdagq----l---
-------------------atlfivlnth---------npk--r-asfre
visteyt--------------------------sngs-----l----kqs
qrvskrpinasg------tdkp--siaysdly--atg---daesaaiglv
wapdraet-lspdtes------md--g-kit--pa------e--------
---------gtvsrh--fn--imsmpwfmls----kffpff-ril--evy
clydkecsnavtdcvvrfvkgnqqlypgnlrflaklaag--------ckn
vl---ngpmmvgcgpqcyiggddclk--pktaip---pv-gcrl--i-l-
------le----------kphqrsn--en--kdkt-iagke--aq-f---
c-h--ka-w-s-i---mg-gl---tqlatvgca-----f-vak----ava
tkqalkgirsig-enafc---sa-atiae-keeae--fk--l--vdadfg
nc-as--wa---dg----gv-end----lgffkrka--qvin---dpyaq
acipkqqs--lc---tgvsik--r-------pkkkpytrpveea------
-----a--eekhgcksggr-------------------iniplchtaise
apa-e---------h-----kyvncknfrw
>node11
-------fk------dg-----sg---------svi--csantrv-glck
apkaevlfksvqthgv-ggeek--fe--t----a------s---rytllg
-nsa-------------ipfs---adefqpl--dqqmdmrthlgrp--es
akltldkgtalyndags--ekkkfktgpsv---g---aveeglef---yn
qesgedlkvy-a----syas-----------------------------y
pwe--------hhv----ll-pry-skr--gkhai-apde-------ec-
igk---------ep----w---dselglfptakafl------a---ppms
e------vs-tglfgkaqaelall-------v-----pvgsq----led-
----------ls-------v---------tleeslvvdn-n--k-mseqg
------aegk--lgk-------stsdvsg--gadtgg-----l-----ds
ttqskkmv----plvrsltpkirthvlyvclr---ta---lpqtc-----
-----------aqseg------lk--s------cvh------ykh---l-
---------iahnqq--yn--i-------lntla-kffpyv-nsf--n--
------------------------------rgvgtyt-g--------ckk
ih---dqa-l------------acln--s----s---slfgcnt--v-l-
------l-till---qspi----kg--dd--qvltinvgkn--an-y---
c-yldm--w-nlm---lnpgg---trttav--------f-saigda-kgv
kpepli-i---tedrsfc-----apasld-indgg--svckv--adapf-
sc-ae--wa---ag----g-tqfg----lgfikkl---s-vklks-----
------tn--l-----gla------------p-----------------p
--dknq--dhr---------------------------------------
---ie---------q-----t------qaw
>node18
-------fk------dg-----sg---------svi--csantrv-glck
apkaevlfksvqthgv-ggeek--fe--t----a------s---rytllg
-nsa-------------ipfs---adefqpl--dqqmdmrthlgrp--es
akltldkgtalyndags--ekkkyktgpsv---g---aveeglef---yn
qesgedlkvy-a----syas-----------------------------y
pwe--------hhv----ll-pry-ekr--gkhai-apde-------ec-
igk---------ep----w---dselglfptakafl------a---ppms
e------vs-tglfgkaqeelall-------v-----pvgsq----led-
----------ls-------v---------tleeflvvdn-n--k-mseqg
------aegk--lgk-------stsdvsg--gadtgg-----l-----ds
ttqskkmv----plvrsltpkirthvlyvclr---ta---lpqtc-----
-----------aqseg------lk--s------cvh------ykh---l-
---------iahnqe--yn--i-------lntla-kffgyv-nsf--n--
------------------------------pgvgtyt-g--------ckk
ih---dqa-l------------tcld--s----s---slfgcnt--v-l-
------l-till---qspi----kg--nd--qvltinvgkn--an-y---
c-yldm--w-klm---lnpgg---arttav--------f-saigda-kgv
kpepli-i---tedrsfc-----apasld-indgg--svckv--adapf-
sc-aa--wa---ag----g-tqfg----lgfikkl---s-vklks-----
------tn--l-----gla------------p-----------------p
--dknq--dhr---------------------------------------
---ie---------q-----t------qaw
>node7
-kva---fiaiillllakkatnpgs-----qmgrlv--cgqqtkss----
------------sdgv-pk-----fe--k----t---fk-d---r-ellg
-taerlc--ipavkiamvefe---pdkfhpfpgy----------------
-alklsret-i----aagldkqkwitkact---m---svdetfiy---eg
ptggssgqvyfagdakhye-pt---gandgmndl--------------yy
twn--------hhc----vm-phf-cvq--n--il-d-g---------a-
pge--kvlri-pqn----w---ge-g--r-amse--kraht-m-ailpf-
n------vgptglyhl--pelhlv-------vgpdwipdagq----l---
-------------------vamfilfdnn---------npk--r-vnmre
vittkya--------------------------dnsg-----l----kes
qnvskrni----p-----tqkp--nvkycnly--vtg---gpetaavg--
--------lhhtdtas------md--g-kva--av------e--------
---------gavsrh--fs--imgmqwfmls----kffpff-kif--k--
------------------------------rfiaslaag--------crq
vi---nqp-l------------eclt--tkkavs---pvygcpl--l-l-
------la----------k----kn--sn--qdyt-iagkq--vq-f---
c-y--ke-w-n-i---lv-gl---tklatvgca-----y-vnm----avm
tkeslkgircigqehpfc---sa-apvad-kedse--fk--i--veanfg
vc-aa--wg---da----gl-dhk----lgflkrkg--avinlmydpyt-
--kpkhne--lc---eglsirarr-------pdknp--rple------hp
sgdkas--dek---------------------------ist-lshvavse
skgie---------h-----kfygcknlvw
>node19
-------fk------dg-----sg---------svi--csantrv-glck
apkaevlfksvqthgv-ggeek--fe--t----a------s---rytllg
-nsa-------------ipfs---adefqpl--dqqmdmrthlgrp--es
akltldkgtalyndags--ekkkyktgpsv---g---aveeglef---yn
qesgedlkvy-a----syas-----------------------------y
pwe--------hhv----ll-pry-ekr--gkhai-apde-------ec-
igk---------ep----w---dselglfptakafl------a---ppms
e------vs-tglfgkaqaelall-------v-----pvgsq----led-
----------ls-------v---------tleeflvvdn-n--k-mseqg
------aegk--lgk-------stsdvsg--gadtgg-----l-----ds
ttqskkmv----plvrsltpkirthvlyvclr---ta---lpqtc-----
-----------aqseg------lk--s------cvh------ykh---l-
---------iahnqq--yn--i-------lntla-kffpyv-nsf--n--
------------------------------rgvgtyt-g--------ckk
ih---dqa-l------------acln--s----s---slfgcnt--v-l-
------l-till---qspi----kg--nd--qvltinvgkn--an-y---
c-yldm--w-nlm---lnpgg---arttav--------f-saigda-kgv
kpepli-i---tedrsfc-----apasld-indgg--svckv--adapf-
sc-ae--wa---ag----g-tqfg----lgfikkl---s-vklks-----
------tn--l-----gla------------p-----------------p
--dknq--dhr---------------------------------------
---ie---------q-----t------qaw
>ENV_HV2D1/24-501
-------fk------dg-----ng---------svi--caantrv-glck
aprqevlfnsvdtpav-ngeek--fe--t----a------s---rytlln
-nsa-------------ipft---adefapl--dqdmdmrihlgrp--qe
aklnldkvtalykdags--dkkkyktgpsv---g---ateegles---yn
hesgedlkvy-a----kyas-----------------------------y
pwe--------hhi----ll-pry-gpr--grhai---td-------ec-
igk---------ep----w---dselglfpaakafl------a---ppms
e------vs-aslfgkaaeelall-------v-----pigsq----ied-
----------la-------v---------gleeflvvda-n--k-lsdqg
------agap--lgk-------stsevsg--gadtgg-----lylpa-ds
-tqskkvt----slvrdlapkirthvlyvclr---cc---lpeec-----
-----------aesqs------lk--a------cvn------yqh---l-
---------iahnqe--y------------------ffgyv-nsf--a--
------------------------------pgvgtyt-v--------ckk
ih---eqa-l------------tcle--s----n---slfgcnt--v-l-
------l-tdll-----------ka--edfaqvltinvgke--an-y---
c-ytam--wgkll---lnpag---artggg--------f-saigea-kav
nsdplv-i---tetrsfck----appsle-inagg--gvckt--gdapf-
dckag--wa---ag----g-aqfg----lgfvrsl---s-vklks-----
------tk--l-----gla------------p-----------------p
--dknq--nhr---------------------------------------
---ie---------q-----t------qaw
>node10
-------fk------ng-----sg---------svi--csantrv-glck
apkaevlfksvqthgv-ggeek--fe--t----a------s---rytllg
-nga-------------ihfs---aeefqpl--dqqmdmrt----p--es
skltldkgtalyndsgs--ekkkyktgpsv---g---aveeglqf---yn
qesgddlkvy-a----syaskh---gniddq-dl--------------cy
pwe--------hhv----ll-pry-skr--gkhai-a-ee-------ec-
igk---------ea----w---dgemglf-takayl------a---ppms
e------vs-tglygnvqaelall-------v-----pvggq----ldd-
----------ls-------v---------tleeslvvdn-n--k-mseqg
------aegk--lgk-------stsdvsg--gadtgg-----l-----ds
ttqskkmv----plvrsltpkirthvlyvclr---ta---lpqtc-----
-----------aqseg------lk--s------cvh------fkh---l-
---------iahnqq--yn--i-------lntla-kffpyv-nsf--n--
------------------------------rgvgtyapg--------csk
ih---dqa-l------------acln--s----s---slfgcnt--v-l-
------l-tillcdivspi----kg--dd--qvltlsvgkn--as-y---
c-yldm--w-nmm---lnpgg---trttav--------f-saigda-nav
ksepli-i---aedrsfc-----apasld-indgg--fvckv--adapf-
ic-ae--wg---ag----g-tqfg----lgfikkl---t-vklkf-----
------td--lc---lgla------------p-----------------p
--dknt--dqr---------------------------------------
---ie---------q-----t------qaw
>node14
-------fk------dg-----ng---------svi--csantrv-glck
apkqevlfksvqthgv-ngeek--fe--t----a------s---rytllg
-nsa-------------ipyt---adefqpl--dqqmdmrthlgrp--es
aklnldkgtalyndags--dkkkyktgpsv---g---ateegles---yn
qesgedlkvy-a----syas-----------------------------y
pwe--------hhi----ll-pry-ekr--grhai---ed-------ec-
igk---------ep----w---dselglfptakafl------a---ppms
e------vs-tglfgkaqeelall-------v-----pigsq----led-
----------ls-------v---------tleeflvvdn-n--k-lsdqg
------aegk--lgk-------stsdvsg--gadtgg-----l-----ds
ttqskkvv----plvrdltpkirthvlyvclr---tc---lpqtc-----
-----------aqsqg------lk--s------cvh------ykh---l-
---------iahnqe--yn--i-------lntlg-kffgyv-nsf--n--
------------------------------pgvgtyt-g--------ckk
ih---dqa-l------------tcle--s----s---slfgcnt--v-l-
------l-till-----------kg--nd--qvltinvgkd--an-y---
c-yldm--w-klm---lnpgg---arttav--------f-saigea-kgv
kpepli-i---tedrsfc-----apasld-indgg--svckv--adapf-
dc-aa--wa---ag----g-tqfg----lgfikkl---s-vklks-----
------tn--l-----gla------------p-----------------p
--dknq--dhr---------------------------------------
---ie---------q-----t------qaw
>ENV_SIVM1/24-528
-------fk---llgng-----sg---------s-------narvhglck
apkddvvfksihvnga-ggeak--fe--t----a------s---rytllg
-tsa-------------ihfs---peelqpl--dqqknmrk----pares
tklqldigtglhadsgs--ekkkfitgpsv---d---svceglqf---ys
kesgddpkvy-p----ayaikh---lntdeq--l--------------sa
awe--------nhr----ll-phy-sdr--gkhgi-l-ee-------qg-
igk---------na----w---s-qmgly-tanafl------------fs
e------vs-tglygvvqvelnll-------v-----pagge----lnd-
----------lg-------i---------tldesleagn-n--k-vvdqd
------aggkdhlav-------spsdvsg--gadtpg-----l-----aa
npgskkkv----s-----kpkirthviyvclr---tt---apqlcaf---
--------qqceqsen------lk--v------cvh------akh---f-
---------vtvsqh--ys--i-------ln----kffpyv-hsv--h--
------------------------------r--gdyapg--------csk
vh---nht-v------------aclnfrt----s---slfacak--v-l-
------f-hf-------p----------e--kvwtlkvgkh--as-v---
c-flgm--w-avm---lnpgg---tkltvv--------f-smigda-nam
tae--isi---tetrsfc-----aaealk-vndgg--fvce---vdapf-
ic-vp--wg---agalggg-tifg----lglvkkl---y-vklk------
--------------------hakk-------p-----------------p
--dkqa--dqr--------vdiqkaetpttdvnasnrnakp-lq----ah
-ngae---------q-----t------eaw
>ENV_HV2CA/25-512
s------fk------dg-----ag---------svv--csassrv-glck
askaeilfksvqthgv-gvser--f--------a------s---rfaltg
dssa-------------ipfs---adefqll--dqqmd-------s--ds
akltlakgtslyndsgc--ekkkyktgtsv---s---aieegidfg--yn
letgenlkvn-a----sysd-----------------------------y
swq--------h-v----ll-srv-ekk--gh----spde-------dc-
igk---------vp----w---daelnls----afl------a---ppms
d------ir-tslfgkaqaelplw-------v-----pigsqs---nde-
----------l-----------------------lvidn-s--kavseqg
------aeds--l-------------------letgg-------------
ssqakkmv----pivrsltptvkthvlyiclr---sa---lpqtc-----
-----------aq--a------lk--p------cvh------ykh---l-
---------isddqe--ynk-i-------lntla-kffgfv-nsf--n--
------------------------------pgvgtyt-k--------ckk
ih---dqg-l------------gcle--s----g---slfgchn--v-l-
------l-aill---qgpi----kg--ne--qvht-nv------------
c-yldm--w-klmgftktagg---rrsaai--------f-sgig-a-kgv
nperli-i---se--nfs-----apgsld-lnggs--stckt--aeaqf-
nc-lagqwd---ag----g-tqfg----lgfikdl---g-vklrs-----
------se--l-----gla------------p-----------------p
--dknq--ahr---------------------------------------
---ie---------qkdirgt------qlw
>ENV_SIVG1/22-522
-nva---yleidhlllakkdtnpgt-----ekgrlv--cgrqskss----
------------sdgv-ak-----fe--r----t---fk-d---r-ellg
-taeqlc--ipnvkiaivdle---vdkfhhfkgy----------------
-alqlsret-l----aagldkkkwvtsact---m---svdetyiy---eg
stgsasgqvyfagdakhyd-pt---nanegkndliskihtcrdesqsdyy
twn---------hc----vm-ahf-cvq--n--fl-d-g---------a-
hge--kvlri-pqn----w---ge-g--r-am----kraht-ly----f-
n------vgpnglyel--penrlv-------sgpdwipdag-----l---
-------------------vatfilfdks---------npk--r-vkmke
vittkya--------------------------nnsg-----l-------
------------------------nvrycnlynqitg---gpasavvg--
--------vhhtetas------ld--g-kva--av------e--------
---------gavsph--ls-hilgmqwfrlt----kffpyf-kffsyk--
------------------------------qfiasyaag--------crq
ci---nqp-l------------eclg--tkkdvs---pvygspl--l-l-
------lt----------k----kn--a-----yt-vagkq--iq-f---
c-y--ke-w-n-i---lv-gp---tklatvaca-----y-vim----avm
kkeslkgircvgqehpfc-ycta-apvad-kedse--lk--i--iaanfe
vc-av--wgikkda----ai-dnn----lgflkrka--vvidlkydpft-
--kpkhne--lc---eqlsirark-------pdkta--rpld------hp
sgekas--dee---------------------------atl---------
skgee---------h-----nfygckslvw
>ENV_HV2BE/24-510
-------fk------ng-----ng---------svi--caantav-glck
apkndvlfkavqthsv-ngeak--fe--t----p------s---cyvllg
-itt-------------ipft---skdfqpl--dqqmdmrshlgra--es
aklnldketaleddass--dkksyksgasrnivg---atsegles---ye
qqsgtnlkvy-a----syas-----------------------------y
pws--------hgia---ll-qry-err--grhai---ed-------ec-
igk---------ep----w---dgelglwswarafl------a---pems
d------vs-tgl----eeelgll-------v-----pigsq----ldd-
----------ls-------g---------tlgqflvvdn-n--k-lsdqa
------pegk--lgk-------stsevsg--gadtgg--nvhl-----da
ttqskkiv----plvrdltpkvrthvlyvclr---tc---fpqtc-----
-----------aqtqg------lk--s------cvh------yrl---l-
---------ialhqe--yd--i-------letlg-kffgyv-nsy--n--
------------------------------agvgtyt-a--------ckg
ih---dsa-l------------scle--s----s---slfgcn-------
--------till-----------kg--td--qllninvgke--sn-y---
c-yldm--w-klm---lnpqg---erttav--------f-satgea-cgk
kpdpli-i---tedrsfc-----apasldfinaga--svcdvrladt-f-
ks-aa--wa---av----m-tlfg----lgfikkv---s-vllmv-----
------tn--i-----glv------------a-----------------p
--dknq--dhr---------------------------------------
---ae---------q-----k------qpw
>node9
-------fk---flgng-----sg---------svi--csantrvhglck
apkdevmfksvqthgv-ggeak--fe--t----a------s---rytllg
-tga-------------ihfs---peefqpl--dqqmdmrt----p--es
tklkldkgtglyadsgs--ekkkyitgpsv---g---aveeglqf---ys
kesgddpkvy-a----syackh---gniddq-dl--------------cy
twe--------hhk----ll-phy-skr--gkhgv-a-ee-------qa-
igk---------da----w---egemglf-takayl------a---ppfs
e------vs-tglygvvqaelall-------v-----paggq----lnd-
----------ls-------i---------tldeslvvdn-n--k-vseqd
------aegkellak-------stsdvsg--gadtgg-----l-----ds
ttnskkkv----t-----tpkirthvlyvclr---ta---apqtcaf---
--------eqcaqseg------lk--s------cvh------fkh---l-
---------vtvnqh--yn--i-------ln----kffpyv-nsf--h--
------------------------------rgvgtyapg--------csk
ih---dqt-l------------acln--s----s---slfgcak--v-l-
------l-si-------pi----kn--de--qvltlkvgkh--as-y---
c-fldm--w-nvm---lnpgg---tkltvv--------f-smigda-nam
tkeplisi---aedrsfc-----aapsln-indgg--fvcev--vdapf-
ic-ap--wg---ag----g-tqfg----lgfikkl---t-vklkf-----
------td--lc---lglavhakr-------p-----------------p
--dkda--dqr---------------------------akp-lr----sh
rkgie---------q-----t------qaw
>ENV_SIVGB/47-569
-altkktdaqkv---------dtgg--tmkqsg-pc--cgr--vkr----
---------------vyae---qvygmcefflr---------------fe
-sant--------------fe---gndysefgay----------------
-h-----d------------d------------sgtvgaseafkf---pg
ctkgg---itlghagm--k-kt---gik--l-------------------
awwatpsltgtlcs-rlwsl-aaf-slhglq--gs-y-gp--ldiaakt-
e-s--aeng---dksqvqwkglaa-n----gt----salapta---lif-
d---------ggfhd---ldyhta-------hrpswmsdged----l--g
pgvpamkrd----------v--------n---------wekner-lplrd
htageel--------------------------idev-----l----k--
------------------------------il--a--------skll---
---------thsanadagtkgvvdngv-trtri-aifsqsht-------g
frvtnfgkdntvg-------------------------gfyd-yf-----
--------------------------------------avfyllgsthrm
lm---vhg-----------------------clvceqgvytcai--lgvr
ktitstga----------k----krgd------------vvlkiehf---
cgh--g-nr-a-t---ns-aa---ke-vel--------y-kkl---epfl
ce------kckpenppfm---av---tgs-kpkdaddid--------efg
hc-aa--fv---as----nv-l-isegs--mfv--g--vgaewm------
-----------c---srlsinesrwtnssagmln-g--l--a--rgqssl
vg------------------------------------------------
----isvcvlikgk------tfkv--gl--
