>ENV_HV2G1/23-502
-------lpn--------------dkgemk---g---g---------phe
anqiqtanenachaplgsnq---------qs--dpgtw------ky-gev
fyig-------crfl-llnsd----------------ktv--pcqcklwt
al----g------er---------gq--ytgvdk-s-----------ykc
vtaq--d---g--------egvk------phngk---------vl--hrk
aianll-tflva------geeeqs-----pralvpniaqlthietatttd
vfnkp-ydykkytfte------------rin------rkt----------
---agptwggv---ialggskrdyi--kcffdsw----k--------fl-
----q-tklavik------arf----gsgh-------pittd-----ldw
vtlcav--panipl--vdeslstlakr---t----e-p--t---wmpkn-
----elasa---gkhwhdynv-slc----a-----------ktdid--t-
----e---ahnddgprdvsp--------li-alvfsp-------------
--la--------fdha---lktnmdl-g--------s----dqsafh--v
f---pldesa-niypa-thfgqiscavclmsa-------illkkvy-spd
tlp-vivsg-----p--hktivg------y--tkvlle------------
hnh---t---------kean-aen-y-q-tpselvvstmpaskaythspr
l------------------lalallled-----r------me----pav-
-----------nnhvf---k-sg--lqpv--cegdis-qptralhanay-
fkpe---i-daydf------------------------------------
--vgfp---dycqtkt-----------------yfkn-------------
------epwg------eq---------------kfqlaq---cs-ltfif
vnhc-------rpdsr--gmsr---alqc-g-naaragc-----------
v--k-v--a
>node11
-------lpn--------------ekgdma---g---g---------phg
anqiqtanintchaplgsnq---------qs--dpatw------ky-ghi
fyig-------crfl-llnsd----------------ktv--pcqcklwt
al----g------er---------gq--ytgvdn-s-----------ykc
---p--d---g--------agvk------phngk---------il--h--
---nll-tflvv------geedqs-----vralaaniaqlthietatttd
vfnip-ynykkytftd------------rin------rvt----------
---dgptwggv---ivlggskrdyi--kcffdsw----k--------fl-
----q-tklavit------arf----gdgh-------plttd-----ldw
dtlcav--palvpm--v-----tlakk---t----p-p--t------kn-
----klana---gkhwhdynv-slc----g-----------ktdvd--t-
----e---anpddgprkvap--------li-alvfsp-------------
--le--------fdha---iktnldl-g--------lpnlysqsafs--v
f---pldesa-niypa-thfgqiscavclmsi-------illkkvy-spd
tlp-vivsg-----p--h----g------y--skvvle------------
hnh---t---------kean-aek-y-h-tpsel--------rayshspr
l------------------ldlalmlee-----r------md----pav-
-----------snhpl---k-sg--lqpv--cegdis-q---alhanty-
fkpe---i-daadf------------------------------------
--vgfp---dycqtkt-----------------ffkn-------------
------eawg------eq---------------kfq-aq---cs-l--if
vnnc-------rpdlk--gmsr---alqc-g-haaragc-----------
t--k-v--p
>node7
-------lgs--------------dhddldft-n---aiavsty-spehg
tap-qvddengckadmsgkd--------wpsvg---er------ai-cha
yflgkc-----ckfl-mgh----g------l---qvak--gvkc------
------n------tr---------gqwqyvaaee-n-----------yka
---sdqa--lv--------agikkfckea--qgr---------las-h--
---i-lkaflv------k-dheat-----k-hfqanigagsw--------
-fgvr-hsykysaysl------------rdslr---lnak----------
adhdspgwdgc---v---gaiqahs--tcff--w----a--------fl-
----vd----ir-------aqf----sdaalnsgd--plgpe-----ddr
ae------atqvgfww---------te---d----s-l--e------kl-
----sl-qiavsvlq-----i-glc----q-----------vgavgpdng
----q---vnr-------eg--------li-kivftv-------------
--la--------fltvviklkgelil-g--------tstl----------
f---svdrgandvyga-thlg------valaa----st-i--kkvc-i--
tt------------r--p----e------e--gkvllf------------
sghqcns---------kpnhyplk-y-nkt---l--------taiv----
l-------s---adp--vlidlalageayt---kpqk---ah----vsv-
-v------spgknpkyt--------rkpt--cqgsnpaq---lqpatlc-
fi-----tdngvnlghke--nk--------vssngh---n-hedaymcvp
n-dgya---afchadnlrs---ha---canas----slatmkpasflkg-
esqaiagawd------et---------------nae-------efl--sy
mqta-------rvdlt--plgw---elps-g-gatnkac-----------
p-eg-----
>node8
-------lgn--------------dhddldft-g---giavtty-spphg
tahtevdedngckaemggnd--------wqstg---kr------kf-sha
yflgkc-----ckfl-mgh----n------l---qvattnavkc------
------k------tr---------gq--yvaaeg-n-----------ykt
---s--d--lv--------agikkfctei--qgr---------las-h--
---i-lkaflvipn---k-dqeat-----k-hfhtnigegsy--------
-fgvk-ysykyyaysl------------rds------hak----------
adldspgwkgv---i---gairaha--kcff--w----a--------fl-
----d-sklniv-------ahf----stga-------plgpe-----ndr
ns------atqvafrw---------ke---k----s-l--e------kl-
----vl-qi---vlq-----v-glc----q-----------lgsvg--a-
----e---anr-------eg--------li-klvftv-------------
--la--------flaivirfkgelel-g--------tstlytqge-----
f---rldrga-diyga-thlg------valas----st-i--kkvc-s--
tt------------r--p----d------e--gkvlvf------------
nthqcts---------kpnhyplk-y-h-tlael--------sevi----
l-------p---aap--vlvalalmgeact---kppk---ah----vsvv
vv------spgsnphli--------rkpt--cqgshraq---lqhatlc-
fkad---sndgvnltnkn--hk--------vsgngh---n-hedtymcvp
r-egfn---afchksnfrs---ha---vakas----s-------------
------gawd------et---------------nvq-------qfl--sy
mqta-------rvdlt--plgw---qlps-g-gatskac-----------
p-dg-----
>node19
-------lpn--------------ekgdma---g---g---------phg
anqiqtatintchaplgsnq---------qs--dpatw------ky-ghi
fyig-------crfl-llnsd----------------ktv--pcqcklwt
al----g------er---------gq--ytgvdn-s-----------ykc
---p--d---g--------agvk------phngk---------il--h--
---nll-tflvv------geedqs-----vralaaniaqlthietatttd
vfnip-ypykkytftd------------rin------rvt----------
---dgptwggv---ivlggskrdyi--kcffdsw----k--------fl-
----q-tklavit------arf----gvgh-------plttd-----ldw
dtlcav--palvpm--v-----tlakk---t----p-p--t------kn-
----klana---gkhwhdynv-slc----g-----------ktdvd--t-
----e---anpddgprkvap--------li-alvfsp-------------
--le--------fdha---iktnldl-g--------lpnlysqsafs--v
f---pldesa-niypa-thfgqiscavclmsi-------illkkvy-spd
tlp-vivsg-----p--h----g------y--skvvle------------
hnh---t---------kaan-aek-y-h-tpsel--------rayshspr
l------------------ldlalmlee-----r------md----pav-
-----------snhsl---k-sg--lqpv--cegdig-q---alhansy-
fkpe---i-daadf------------------------------------
--vgfp---dycqtkt-----------------ffkn-------------
------eawg------eq---------------kfq-aq---cs-l--if
vnnc-------rpdlk--gmsr---alqc-g-haaragc-----------
t--k-vatp
>ENV_HV2BE/24-510
-------lpn--------------sksdma---g---g---------ghg
adqiqtatintchi---kne---------qs--dptdw------ky-ghl
fyig-------crfl-lvqad----------------skv--acecslwt
al----g------er---------gq--ytgqdk--------------kc
---p--d---e--------asvk------phagk---------il--h--
---nll-tfliv------geedha-----vralaehvaklthletattad
v-nip-ypyekytfadakykntaecgvkril------rvl----------
---ngrtwggt---ivvgaskrdyi--kcffndw----k--------fl-
----q-tklavit------trf----gvgd-------pltne-----ldw
dtfcav--pa---------------kk---t----p-p--t------kl-
----rlant---gkewqayav-slc----g-----------kteie--t-
----------------------------li-atvfnp-------------
--mr--------feht---ikakldltg--------lgslysltefs--v
f---ileesa-diypa-thfgqikcavclmkm-------fllkkvk-spd
slp-vivsg-----pnmq----dae----y--akvvle------------
hnh---t---------kaan-ad--y-h-tptel--------rtyskspr
f------------------ldlalmleq-----p------mdtekppan-
-----------enhsl---k-gg--mqpv--cegdtg-q---all-----
fspd---i-esadf------------------------------------
--lkfp---dycqtkt-----------------ffks-------------
------eawg------------------------fe-aq----a-l--if
innc-------rpqlk--gmsr---alq---------gc-----------
s--k-vitp
>ENV_SIVG1/22-522
-------lgs--------------ehsnlaft-k---giavtty-spkhg
ttp-hvndgsgckaqmsgkd--------wpsig---dk------at-chp
yflgkc-----ckfl-mgh----g------l---evak--gfkc------
------n------tr---------qqwryvag---n-----------yka
---idqg--iv--------agikkfckea--qgr---------las-h--
---k-lkaflv------n-dheas-----i-hfqgviaagkw--------
-fgvk-ssyrhaaysl------------adplr---ldak----------
sdhdspgwdgc---v---eavqahs--tcff--w----a--------fl-
----vd----ic-------aqf----gdsaldagd--plgpe-----edr
ae------alqvgfww---------ta---d----s-l--e------kl-
----eq-qiavsvqq-----i-dlc----q-----------vgavgpdng
----q---vtr-------eg--------qi-kiifnv-------------
--la--------fetvvikwkgelil-g--------sgtl----------
f---tverg--dvy---thlg------valta----st-i--kke-----
-----------------v----e------e--gk-llf------------
sghq--g---------kpnhfplk-y-nkt---l--------tgiv----
l-------say-adp--vlielalageayk---rpqk---ah----vsv-
-v------apgqnnkyn--------rkpt--sqganpsq---lqpatlc-
fi-----vesgvklghkq--nk--------vnsngh---n-heqaytcip
d-deyk---vfcdadnlrt---ta---canat----slatmkpanflkg-
esqaiagawd------et---------------nae-------efl--sh
mdta-------rvdln--plgw---elga-g-gktskac-----------
p-en-----
>ENV_HV2D1/24-501
-------lpn--------------ekgqma---g---g---------phg
anqiqtatikachaplganq---------qk--dpakw------ky-ghi
favg-------ckfl-llhgd----------------ktv--pcqcklwt
al----g------er---------gq--ytsvdt-s-----------ykc
---p--d---g--------aglk------phsgk---------il--h--
---nil-tyliv------geddqpdtaqdvraiaaniiklthletastad
vfnip-ypykehafae------------ren------rit----------
---kgptwngt---vvlggskrdyi--kcffdsw----k--------fl-
----q-tklaait------trf----gage-------pltte-----ldw
dtfcav--pafvpm--v-----tlakr---t----p-p--t------kn-
----klana---akewhdyag-slc----gfsqiefpkphfktdie--a-
----e---anpdsgphkvsp--------li-alsfsp-------------
--lqsktdvklcldqa---iktkvdl-a--------mpklysqsafs--v
f---pledsa-niypa-thfgqvkcavclm-k-------ihlk-------
--p-vivsg-----k--h----gae----y--skvvle------------
hnh---tn--------kaan-ae--y-h-tpsel--------rayghcpr
l------------------lklil--ee-----r------vd----pai-
-----------snhsl---k-sg--lqpv--cegdmg-q---alhanpy-
ykpd---y-dsadf------------------------------------
--agfp---dycqakt-----------------ffkn-------------
------eawv------en---------------kfe-aq---cs-l--af
vnnc-------rpdlk--gm-------qc-g-hasrags-----------
t--k-qgtp
>node14
-------lpn--------------ekgdma---g---g---------phg
anqiqtatintchaplgsnq---------qs--dpanw------ky-ghi
fyig-------crfl-llhsd----------------ktv--pcqcklwt
al----g------er---------gq--ytgvdn-s-----------ykc
---p--d---g--------agvk------phagk---------il--h--
---nll-tflvv------geedqs-----vralaaniaklthletattad
vfnip-ypykkytfad------------rin------rvt----------
---dgptwggv---ivlggskrdyi--kcffdsw----k--------fl-
----q-tklavit------trf----gvge-------pltte-----ldw
dtfcav--palvpm--v-----tlakk---t----p-p--t------kn-
----klana---gkewqdyav-slc----g-----------ktdie--t-
----e---anpdegprkvsp--------li-alvfsp-------------
--lq--------fdha---iktkldl-g--------lpnlysqsafs--v
f---pleesa-niypa-thfgqikcavclmsm-------illkkvy-spd
tlp-vivsg-----p--h----gae----y--skvvle------------
hnh---t---------kaan-ae--y-h-tpsel--------rayshspr
l------------------ldlalmlee-----r------md----pai-
-----------snhsl---k-sg--lqpv--cegdig-q---alhansy-
fkpd---i-dsadf------------------------------------
--vgfp---dycqtkt-----------------ffkn-------------
------eawg------eq---------------kfe-aq---cs-l--if
vnnc-------rpdlk--gmsr---alqc-g-haaragc-----------
t--k-vatp
>ENV_HV2NZ/24-502
-------ipnashgyalsvfgq--qlgdla---g---g---------phg
anqiqtatintchaklgqng---------qk--ecgpw------ny-dyi
ffis-------crfl-llnsn----------------ktv--pcecklwt
al----gylfegvdm---------gk--ytgvdn-s-----------ykc
---p--d---g--------advk------phsgk---------ci--h--
---nll-tfvvv------aeeaqs-----irel-aniarlthietatttp
ifnip-ypykkypfsq------------rin------rv-----------
---dgptwggv---ivlgaaksdyiakkcffksf----k--------tl-
----e-tklavipafqtqlgrf----gvnr-------plttd-----idr
pyfcpv--ptlvpi--y-----tlgkk---t----i-p--v------ki-
----klans---gkhwqn------------------------tdve--i-
----epglanpddgpr-vap--------li-alvfkp-------------
--le--------tdda---ikt----------------nlydqsaftdfv
f---sldesa-siypa-thfndtkcpiclmsi-------ialkkvy-psd
t-------------------------------------------------
psh---t---------kaad-aek-f-h-tpsdl--------sayshlf-
l------------------fdlalilek-----r------md----pev-
-----------snqsi---kasdftlepv--cqg-vg-q---tlpansf-
vkaq---------f------------------------------------
--vgfphtadycdkks-----------------ffki-------------
------eawg------eq---------------kvs-sq---cs-i--vf
annc-------rpglk--gmsr---plhc-g-hiaragc-----------
t--rgvanp
>node10
-------lpn--------------ekgdma---g---g---------phg
anqiqvaninachatlggnq---------qs--spatw------ky-ghi
fylg-------ckfl-llnsdfks------lq--evnktv--pcqcklwt
al----g------er---------gq--ytgvdn-s-----------yki
---p--d---g--------agvk------phngk---------il--h--
---n-l-tflvv------geedqs-----vralaaniaqlthtetaqttd
vfnip-ynykkytftd------------ren------rvt----------
---dgptwggv---i---gskrdyv--kcffdsw----k--------fl-
----q-tklavi-------arf----gdgh-------plttd-----ldw
dtlcav--palvpm--v-----tlakk---t----p-p--s------kn-
----mlana---gkhwhdydv-slc----g-----------ktdvd--t-
----e---agpdegpskvap--------li-alvfsp-------------
--le--------fghavlkiktnldl-g--------lpnlysqsafs--v
f---pldasa-niypa-thfgqiscavclmsi----tg-illkkvy-spd
tlp-vivsg-----p--h----g------y--pkvvle------------
qnh---t---------ksad-aek-y-h-tpael--------rtishspr
l------------------ldlplmlee-----r------md----pav-
-----------shhpl--rk-sg--lqpv--cegdis-q---alhanty-
fkpe---i-daadf------------------------------------
--vgfp---dychtktfls---p-----srsrvffkn-------------
------eawg------eq---------------kfq-aq---cs-l--if
vnnc-------rpdlk--gmsr---alqc-g-haartgc-----------
t--e-v--p
>ENV_SIVGB/47-569
etvgalaaai------------inihvkaessgvianntk-mlf------
-h------t--ceqsfgtgkksirydgk----g---aagrknkpaghall
f----h-----s--g-lah----ktepngnl-ekslg--rnckc------
--amvaa------akylemmvvlq--------qtqdnlsvtlgrggnys-
---k--c--lvdnpnpkev--sek--t----kya---------fpd-h--
---l-a--syllediacn-rrmgg-----n-h------------------
----e-lnft-----i------------ria------ytr-------grc
ats-------a---v---g-lqaka--agkd--nnikakhelhvsdpfa-
----k-sklsiv-------vdf-----tcs-------pqh-n--------
------------glaf-------------------kgmlgqtat---rys
ifgges-lc---klt-----dlclclsfk------------lgvia--v-
gvyyg---ekr-------aa---iqrvapve--alip---------lfhv
ne----------------------------------------qte-----
iniq----vl-tvl----------------asahpl-sil--kgsr-t--
ka------------m--p----g--tskepgtdrgwaytqlktt------
----cdl-yaitsgqg-lk--------------i--------fskq----
lmlaketkn--lv-kefiwiy------qcvasnktiatylvy----saiv
vtgseckrhr-----------------sl--senplpdq---laqsskce
lgadklg----v----hayeqracsvykhvitgglhgdrtm---------
-----e---alch-----gphdfapgt-vke-------------------
------gv--------et-vsnrgftkanipwaqva-------m------
---------------egg-sfratkdmak-a-ssas-vcnqpdlpgartl
cegg-----
>node18
-------lpn--------------ekgdma---g---g---------phg
anqiqtatintchaplgsnq---------qs--dpatw------ky-ghi
fyig-------crfl-llnsd----------------ktv--pcqcklwt
al----g------er---------gq--ytgvdn-s-----------ykc
---p--d---g--------agvk------phngk---------il--h--
---nll-tflvv------geedqs-----vralaaniaklthietatttd
vfnip-ypykkytftd------------rin------rvt----------
---dgptwggv---ivlggskrdyi--kcffdsw----k--------fl-
----q-tklavit------trf----gvgh-------plttd-----ldw
dtfcav--palvpm--v-----tlakk---t----p-p--t------kn-
----klana---gkhwhdynv-slc----g-----------ktdvd--t-
----e---anpddgprkvap--------li-alvfsp-------------
--le--------fdha---iktnldl-g--------lpnlysqsafs--v
f---pldesa-niypa-thfgqikcavclmsi-------illkkvy-spd
tlp-vivsg-----p--h----g------y--skvvle------------
hnh---t---------kaan-aek-y-h-tpsel--------rayshspr
l------------------ldlalmlee-----r------md----pav-
-----------snhsl---k-sg--lqpv--cegdig-q---alhansy-
fkpe---i-daadf------------------------------------
--vgfp---dycqtkt-----------------ffkn-------------
------eawg------eq---------------kfe-aq---cs-l--if
vnnc-------rpdlk--gmsr---alqc-g-haaragc-----------
t--k-vatp
>node17
-------lpn--------------qkgdma---g---g---------phg
anqiqtatintchaklgqne---------qs--epapw------ky-gfi
fyig-------crfl-llnsd----------------ktv--pcecklwt
al----gylfetver---------gq--ytgvdn-s-----------ykc
---p--d---g--------agvk------phngk---------ii--h--
---nll-tflvv------geedqs-----iralaaniaklthietattts
vfnip-ypykkytftd------------rin------rvt----------
---dgptwggv---ivlggakrdyi--kcffdsw----k--------fl-
----q-tklavit------trf----gvnh-------plttd-----ldw
dtfcav--palvpl--v-----tlgkk---t----p-p--t------kn-
----klans---gkhwhd------------------------tdve--t-
----e---anpddgprrvap--------li-alvfsp-------------
--le--------tdha---iktdldl-g--------lpnlysqsafa--v
f---pldesa-aiypa-thfneikcavclmsi-------illkkvy-ppd
t-------------------------------------------------
hnh---t---------kaan-aek-y-h-tpsel--------rayshlpr
m------------------ldlalilee-----r------md----pav-
-----------snhsl---k-sg--lqpv--cegdig-q---alhansy-
fkpe---------f------------------------------------
--vgfp---dycqtkt-----------------ffkn-------------
------eawg------eq---------------kfe-sq---cs-l--if
vnnc-------rpdlk--gmsr---alhc-g-haaragc-----------
t--k-vatp
>ENV_HV2CA/25-512
-------lpn--------------akgdva---g-------------pyg
asqiktaqigtchekvgqan---------qs--epppw------ky-vfi
fyig-------ctfl-llnsd----------------kgv--acecklwt
al----gylfqdver---------gd--ytgsen-s-----------ykc
---p--eve-g--------agvk------phngkktvngvasli------
-----l-tflvi------geedqt-----vralaaniatitplelat--n
vfnkpgysykkytftd------------rin------kvk----------
---dgptwngv---vvlgg--rdyi--kcffdae----k--------fl-
----r-vklgavk------trf----gvnh-------pltan-----ldw
atfcav--aalvpv------------k---t----p-p--s------kn-
----klsnv---gkdwhd------------------------tdag--t-
----a---anendgprrvgppde-----li-algfsp-------------
--le--------tdhg---tkidqdl-g--------lpnlysqsafa--v
f---plketa-aiypa-thfnkikcavclmpi-------fllkkvy-ppd
t-------------------------------------------------
hah---t---------kpan-aed-y-n-sqtel--------rafehlpr
i------------------ldleltlde-----r------md----aav-
-----------knqsl---k-sg--lape--cegemg-q---ilhanpy-
fkpe---------f------------------------------------
--agfp---dycqtkt-----------------ffkn-------------
------epwg------dq---------------kfe-sq---ct-l--if
vnnc-------kpdlk--gmsr---alhc-n-haaragc-----------
t--k-vatp
>ENV_SIVM1/24-528
-------lpk--------------qngdlg---g---g---------phg
anqiqvanlpachgtlghnq---------qs--spgtw------ky-ghv
yylg-------ckylcqlns----------lq--evdknv--pc------
------g------qr---------gp--ytgven-s-----------yki
---i--d---g--------aatk------phngk---------yl--h--
---s-l-aflav------gdq--------vka-qanvaklnhte--qttg
vfnip-anykkytfke------------ree------rvt----------
---daqtwggi---i---gtnrd-v--kcffdsw----k--------ylq
vpvcq-ikiaai-------arf----gd----------ltpd-----tdr
dalctvkqpalvpl--v-----glakk---i----t-a--s------kn-
----mlakv---gklwhdydv-elc----a-----------ksdmd--t-
----e---pgtgeg---vcp--------ii-al--s--------------
-------------ghavikiknnldv-g--------lnslysqetft--v
y---rldrga--iypa-klfaqisstvclmsi----sg-illkkvy-apd
tlqkvicng-----p--h----s------y--lkvllg------------
------t---------kgag-pqk-yth-tpael--------htvshtps
l------------------levvlmgnp-----r------ld----pavi
g-------sttshhhlvfrk-sg--ldpv--cggkas-q---plhcntf-
frpd---i-naadl------------------------------------
--pgmp---hychtktfls---a-----srpriffyn-------------
------dalg------ek---------------kfq-aq---cs-l--iy
vskc-----qlrpelr--gmss---vlqc-a-hnrrkav-----------
t--e-----
>ENV_HV2D2/24-513
-------lpl--------------ekgdma---g---g---------avg
s------nindchatlggnq---------qs--nevaw------ry-gnv
fyag--fefavckil-llns---s------lq--yvniti-----cmlwt
pl----g------dn---------gq--ltgnin-a-----------ysi
---p--d---g--------agak------glngk---------il-k---
--------flgi------sqddaw-----vrnlavnvdqlvh----qttd
vfnap-ypykkyvftd------------ren------rv-----------
---dgpawggl---i---gdkrdyf--rcffdtw----k--------fl-
----e-tklavi-------arfgtcdgngq-----ekpttth-----ldw
dqlcag--stlvpl--v-----vladh---a----p-p--s---------
------anv---vkhwqeydh-amg----------------rtdie--t-
----e---tg--egnski-p--------le-avlets-------------
--le--------fghailkiktnlnl-skvinktgw-pilytpsnfd--l
-----lddia--------hfgqisctvclmcl----ng-illkkvy---e
tlp-vivsgnhhnia--s----a------y--pstcle------cpkkfa
akh---t---------lsid-tek-y----------------rtvthspk
l------------------ldlplmlee-----r------md----pri-
-----------thhsl--rs-gg--lqpv--cegdis-t---slhanyy-
ytpe---v-ngadf------------------------------------
-svgfn---nychtniflt---p-----aqtrvfftn-------------
------aawgvqvevkeq---------------kfl-vqvgrcs-l--if
vndc-------rpdln--gisr---tlyc-g-htsrtqc-----------
i--e-v--p
>ENV_SIVV1/24-538
-------lgt--------------rhedlgfs-n---aittsaygsavhg
tpp-qgetdisckaglngkd--------wpavp---ar------pi-cng
ffvgkc-----ckfl-lgh----g------a---mvak------------
-------------tt----------------aae-y-----------yta
---ldra--la--------agllkfcqea--qsk---------lgs-h--
---v-lgsflv------k-dqeat-----p-hleanigp-----------
-------aykysayal------------rdpmnkfnlnskghrrtlg---
anniskgwngciikv---gelaahk--------w----d--------it-
----ac----ir-------aql----sdpylkdga--plgpedldtpddr
ad------aaivgfwh---------tepkedknrvg-l--e------qh-
----sl-qiavsilh-----v-amc----q-----------agavgpena
----q---vsr-------dg--------li----fsvptgellggc----
--ln--------fltmviklkgklvl-g--------tstl----------
f---pvdegandvfgvftslg------valaa----kt-i--krvcnl--
----------------------g------p--grvllf------------
s--qsdg---------kpdhyplday-nkp---l--------dtly----
l-------s---ver-----glglkdesyv---kpek---ah----vsv-
-v------spgavpkyt--------rkprfpcqmsnpaq---lqpsqlr-
fi-----ngngvnvahre--ds--------vssngh---n-hsdgsmcvs
g-dgfn---efchadilrf---aa---ag-gr----svsqme--sflsga
egqaitgawt------ete--------------yse-------afm--sy
kqkaetgrm--rvglt--plgw---qyptegegatakac-----------
p-eg-----
>node9
-------lpk--------------engdla---g---g---------phg
anqiqvaninachatlggnq---------qs--spatw------ky-ghi
yylg-------ckfl-llnsdfks------lq--evnktv--pc------
------g------er---------gq--ytgvdn-s-----------yki
---p--d---g--------agik------phngk---------yl--h--
---n-l-aflav------geedes-----vralqaniaqlshte--qttd
vfnip-ynykkytfte------------red------rvt----------
---daptwggi---i---gskrdyv--kcffdsw----k--------fl-
----q-tklavi-------arf----gdgh-------pltpd-----tdr
dalcav--palvpm--v-----tlakk---t----t-a--s------kn-
----mlanv---gkhwhdydv-slc----a-----------ksdmd--t-
----e---agtdeg---vap--------ii-alvfsp-------------
--le--------fghavlkikdnldl-g--------lsnlysqsaft--v
f---rldrga-niypa-thfgqiscavclmsi----sg-illkkvy-spd
tlq-vivsg-----p--h----g------y--pkvllg------------
qnh---t---------ksad-aqk-y-h-tpael--------htishspr
l------------------lelalmgee-----r------md----pavi
gv------gndshhhlifrk-sg--lqpv--cegtfs-q---alhanty-
frpe---i-daadf------------------------------------
--agfp---dychtktfls---p-----srsrvffkn-------------
------dawg------ek---------------kfq-aq---cs-l--iy
vnnc-------rpdlk--gmsr---elqc-g-htarkac-----------
t--e-----
