>ENV_SIVV1/24-538
eel-----ed---nnstrgi-q-------------mqt--g---------
-y-cv-------egk----adhq-----dty---g--d---dh----sn-
--hl---palae-----kpalldplhlify---n-vlidsy---------
---aksichsd----i-----p----idgkqrtlvvasgiknsgnyeana
cvmg-lg--g----n----------ndhgdmkiv-rt-------------
---ep---ig------tygvtlvnghqrdeatgv----krad-lppdnwl
kdcnns-digfs--kk--------kecidacci---s-gycc-mk-kfl-
tpamtdppkglcgll------ntyl---amslv------ggy-----esq
aavtvahat---e--alagkk-lgdmedfvvv----ng-tlm-vknl---
-vt--i--le--gq------enanyrrsnvkkd---------------l-
---------------------------lyw------gkfkhh--------
-h--f-arsi---v-qsgplgtvlkksvtrhr---e---------gfgda
ck-stvp--------------iy-------------avsadavdg---tv
ehql-ac-ava--hi------y---qs-gds-kdve-qdympadepeigi
kg--c--ftepghet----------rgd--sacfak-llnqngvi--ksm
qdga----lgna----tgdkylaa-wadsrelalhitpkprtgfesfrcq
pl--------ae---gpvkhalapk---fvqdt---df--vkfgvlrasl
-p--tpat--e----tv--------t-t-------nqfeig--se--i
>ENV_HV2G1/23-502
elvhlfkvkpra-esggkglmswnv----------lqtsad---------
-miavfhqgstadvh----kqklhnl--ss----a--efhlkq----gd-
--ya---fln----------llet------mylg-vlk-kf---------
---t------t----r-----ptkhetglpqr-----------vqsraik
cnmg-ag--taeffk----------kvfgdnkttpkap-----d--ylav
nrrrpt-mftfksqfr--ggktingana-----i----dsddelaqdkwq
-----a-eplyg--np--------kecggpcrk---v-nf----yqalf-
eapk--llkglcptak-----nsyq---aqgll------s-y-----apd
aqvpqatnkesal--dktakk-q------nalsisysg-lalkfdyld--
ekchlf--td--tv------enanlksravkrg---------------wg
v----h---------dsf---klglvpldwhs---kgkfq-s-------s
lh---r-knvpneq-kghqvapag--p-----------------------
c-----t--------------sysqp-anggdrl-pvevviplgs---g-
------esglkaksig---rignpnhs-epglkgatatkfieeksry---
h---syklat-tqvtsl------lakks--pscsieallnqikti--kqv
l---a---lgvarfqgaynkfisv-wa-----------------------
--cegssarkhqap--p--gt--pt---y-dgq---rws-----------
-p--gp-a--e----q-----------a-------------------t
>node7
dev-----se---nnstrgikq-------------lqt--d---------
-yvsv-------dgk----enhh-----dt----g--eyqldh----sn-
--ha---fglte-----kpallqplhlify---n-vlidty---------
---tkstchsn----i-----p----itfkqrtitiasgimnggnyeana
cvmg-lg--g----h----------dnhgekkii-rtp-----l--ynt-
-krep---iv--------gsksinghnpgepasv----dstd-lppdnwl
kdcnit-nigfa--kk--------kdcvtkccv---d-gycc-ly-sfa-
ippmgdltkalcatv------ntyl---tmalv------sgy-----esg
gdvtvatit---e--altgkk-ig----lvvl----ng-alm-yknlp--
eht--i--se--ga------ddanyrksnvkkd---------------w-
---------------------------lywhk--ksgkfq-e--------
-h--i-prni---a-rsgplgsvhqka-trhr---e---------efgdc
ck-strp--------------ny-------------avaakpigg---tv
qhqipas-ava--ti------ydk-es-ges-kevv-qgympdaept---
rg--c--laddshatsl------llrqg--pacysk-llnhytvv--ksi
ldgta---lgia----tfkkylga-wantrdla--ita-prasfesfrcq
pl--------aq---ep--haiapk---fvedq---kyg-vkfgvlrgkl
ns--tplt--q----ll--------l-t-------ndfeig--snapi
>ENV_HV2D2/24-513
elihllkakprn-nnggkgikewtv----------let--n---------
-leavfedgakadvh----kqslhd----l----a--efql-q----ah-
--ya---fgnktaeyhaakpllat---------g-cveekydqklgpcha
rfhs------d----p-----dtnhasglpak-----------vlipnvr
---g-ag--taeffr----------ktfgdkkitvktp-----t--yksv
nnrkpt-kfdlkaqln--ggksihggnldtpitl----dsdnalaaeswh
-----a-dqlyg--ns--------kec-----n---vkhf----fqviy-
nppkcaslkklcptvsp--sknsfe---ahgll------t-y-----gpp
pevpqavek---s--tctakk-e------iqasvvyng-leq-feyld--
ekc--f--td--ia------eepelkdnkvkrg---------------wg
awqsprtngtcapvfnsf---al---pldmhs---qgkfq-n-------s
lh--vr-knrsseq-rghevgadr--p-----------------------
c-----t--------------gykaglenggasl-adevvipvgs---g-
------qggingnsiancgr----hps-epglkagtgatfiegksey---
h---a--lat-tqvtdk-kagqvmvris--ascsvaallnqlksi--kev
l---a---lgvgrfdgaynkflgv-war----------------------
v-cdg-gtrkhqgpav----k--aa------gq---rwg-a---------
-p--th-a--q----ev--------l-akcqavlilewa----rqypt
>node17
elvhlfkvkpha-enggkglkawng----------lqtgae---------
-liadfhqgstadvh----lqklhnl--ss----a--efqlkq----gn-
--ya---fan----------lldt---------s-vlqeky---------
---s------d----k-----ptkhesglpqr-----------iqsreik
vnmg-tg--iveffr----------kvigdkkitpktp-----d--yasv
nrrrpt-mftfksqfr--ggktiqganaadpiti----dsddelaqdswq
-----a-kqlyg--ns--------kecggpclk---v-nf----hqalf-
eapkstllkklcptvsrspsk-sye---aqgll------s-f-----aps
ahvppaank---l--tltskk-q------nalsiayng-lal-feyld--
ekc--f--td--tl------ehanlkdkavkrg---------------wg
a----r---------etf---av---pldwha---qgkfs-s-------s
-----r-knvpneq----qvgpgq--p-----------------------
c-----t--------------syrqgl-nggarl-paevvipygs---g-
------etglnakvia---rignmnhs-epglkgatatkfikqkppy---
h---t--lat-tqvtsl------lvkts--sscdvaallnqikti--kev
l---a---lgvsrfqgaynkfvgv-war----------------------
s-cegssakkhqgpavp--gy--pt---y-dgq---rwg-----------
-p--sp-a--e----hv--------l-akrqavlhlewd----rqypt
>ENV_SIVM1/24-528
elihlfsvkprg-esggkgikawdl----------let--e---------
--iaiynqgltrnvh----kpklhnl--eq----e--efvlqh----gn-
--ha---ftnkt----aspplaep---------g-lienky---------
---g------d----p-----aakhetglpdk-----------vlnraav
csmg-sg--taeffr----------ktfgekkdspktg-----d--ftni
hkrrrt-mfamksalk--gsetlhtana--pipr----dsddelakdtwq
-----t-eelyg--nr--------kecavpcls---p-ny----yrsf--
-----mllkklcptlsc--gknsye---iqgl-------s----------
akvlq---k---e--dldark-r------kpl----dgglam-feyvs--
eky--y--nf--tpssvrkpdesnlrdnkvkrg---------------wg
a----r---------gtf---al---altwhf---qgkfe-h--------
-h--vr-knvpnen-ratqvgpgq--p-----------------------
c-----v--------------sfk------gsrlptaevvvpigs---g-
------egafhtksianyg--gdmpht-eqglkevtstkflahsspy---
n---t--lsh-trityl------llrag--ttcyiaallesikvi--kdv
lngpg---vsvsrfegahnkflgv-war----------------------
r-cdgsatkrhqgggvp--dpiaps---y-agq---rwn-g---------
-s--ap-a--d----el--------l-tkskavlnlqwd----kvypv
>ENV_SIVGB/47-569
dli-----as---qnnhnairv---sikqgdrqahlsl--neaevgvvre
sclqs-----ypegepranrkrm---gga-----y----dllnnkpltvl
gaacnwyfg-------------dwgi--yt---ea-l--kv---------
---d------eglvsp-----g----ilfkhnfksgf-----------ap
iakn-lgnr-----------------ggglwa-----ptgeartgv--kv
egrwp---iv--------aakcll-ata-spagsdnkralgt-f-gesns
-----devvffl--sv--------ad--pqcyvdyy----tck----fsq
lqgmgfschhl---nan----gtem-qsattdidselfm--y-----cpv
apv---------eatavse-------------------------------
--c--t--sd-nep------nttshliggk-pqmqvsglcrssdtvedw-
---------------------------pr--r--i-rvys-q--------
-l--vkakcl---tpr---------------vlypa-------krneava
i-----s------pmlqngga-----------------pkpavakgalv-
------k-gic--ll------hit-kdm-------------aecagr---
k-dt----ddqgrsq-----------rlckea------a-----flg-a-
-kgtqdeeltsa----gfktytvdlwhgtrn-----ka-irpdaqrarl-
----------hn---nn--n--asntqn------------kkgalh-g--
-kahmlliykv----qkitgapsanm-r-------aiygvqcykakdq
>node19
elvhlfkvkpha-enggkglkawnv----------lqtgad---------
-liavfhqgstadvh----kqklhnl--ss----a--efqlkq----gn-
--ya---fan----------lldt---------g-vlqeky---------
---s------d----r-----ptkhesglpqr-----------vqsrdik
cnmg-ag--taeffr----------kvfgdkkitpktp-----d--yasv
nrrrpt-mftfksqfr--ggktiqganaadpiti----dsddelaqdswq
-----a-dqlyg--ns--------kecggpclk---v-nf----hqalf-
eapksallkklcptvsp--sknsye---aqgll------s-y-----aps
aqvpqaank---l--tltakk-q------nalsiayng-lal-feyld--
ekc--f--td--tl------edanlkdkavkrg---------------wg
a----r---------etf---al---pldwhs---qgkfq-s-------s
lhvyvr-knvpneq-kgsqvgpgq--p-----------------------
c-----t--------------syrqglenggarl-paevvipigs---g-
------esglnaksia---rignmnhs-epglkgatatkfieqkspy---
h---t--lat-tqvtsl------lvkts--pscdiaallnqikti--kev
l---a---lgvsrfqgaynkfigv-war----------------------
s-cegssarkhqgpavp--gy--pt---y-dgq---rwg-----------
-p--gp-a--e----qv--------l-akrqavlnlewd----rqypt
>node14
elvhlfkvkpha-enggkglkawnv----------lqtgae---------
-liavfhqgstgdvh----kqklhnl--ss----a--efqlkk----sd-
--ya---fat----------lldt---------g-vladky---------
---s------n----k-----pikhesglpqr-----------vqardik
vnma-tg--vseffr----------kvfgdnkitaktp-----d--yasv
nrrrpt-mftfksefr--ggktiqganaadpvti----dsddelaqdswq
-----a-dqlyg--nl--------kecglpclk---v-nf----hqalf-
eapksallkklcptisp--sknsye---aqgll------s-y-----aps
aqvapaank---l--tltakk-q------galsiayng-lal-feyld--
ekc--f--td--tl------edatlkdkavkrg---------------wg
a----r---------etf---gl---pldwhd---kgkfq-k-------s
lhvyvr-knvpneq-kgsqvgpgq--p-----------------------
c-----s--------------syrqglenggarl-pdevvipigs---g-
------etglnaksia---rignmnhs-dpglkgatttkfieqkspy---
h---t--lat-tqvtsl------likts--pscdvaallnhikti--kev
l---a---lgvsryqgaynkfigv-war----------------------
s-cegpsakkhqgpavp--gy--pt---y-dgq---rwg-----------
-p--gp-i--e----qv--------l-akrqavlnlewd----rqypt
>ENV_HV2D1/24-501
elihlfkvkp------gnglkawnv----------lqtgse---------
-lfavihqgatgdvh----kqklhnl--st----a--efelkv----sd-
--ya---fit----------pldt---------g-vlagky---------
---s------n----k-----pikhesglpq-------------qarntk
cnla-ng--vseyfk----------kaygdnkitsrtp-----d--yasv
nrrrps-mytfkaefr--ggstiqgsnaadpvvi----dsddeltqnswn
-----a-sqlfg--nl--------kicdlpclk---v-nf----hqqlf-
eapksailkklcpti------nnyh---akgl---------y-----aps
aeva-adnk---l--tltakk-g------galsiayng-lal-seyld--
etc--f--tdh-tl------gdaalkdkavkrg---------------wg
a----s---------eal---gl---pldwqa---kgkfq-kdrrertds
ldiyir-kavpneq-kgsqagpgh--p-----------------------
c-----s--------------tyrqglqdvgirl-peevvipigs---g-
------etvlnansia---rignmnpa-dpglsgaiatkliedhspy---
h---t--lah-tevisl------laits--pscdvapllnhiksl--kqv
l---a---lgvsryqgaynkfigv-wap----------------------
s-cegpsakkhqgpavp--gy--p----l-dga---rwg-----------
-p--gp-e--e----ev--------l-akre-ylnlewd----rsypi
>ENV_HV2CA/25-512
---hlfkvkpha-dnggkglkawag----------lltgpe---------
-liaefhqg--fdvh----lqnlhnl--ss----danefql------gn-
--ya---fen----------lldt---------s-vvqaky---------
---s------d----k-----pkkhesglpqr-----------vqsriik
vkmg-tg--ivdffrgs--------kvigdkkitprtp-----g--aamv
nrrrpt-mftfkaqlr--ggktiqgangadpati----gsddelakeqwq
-----v-rqlygktns--------eecggpclk---v-nf----yqall-
eapkskvfkklcptvsrspak-sye---aqg--------s-------a--
ahvpptank---l--tlaskk-q------dtlsidyng-lgl-fkyme--
ekc--f--td--tl------ehanakdkavkrg---------------fg
d----q---------etflladl---pl--hh---qg--s-s-------s
-----q-knvpdeq----qvgplk--p-----------------------
c-----k--------------scrqgl-nggarm-psevvnpygs---g-
------evglnakiia---rvgdmnhs-spglkganakkfikekppy---
h---t--lat-tqitelv-----lvkeh--lscevaalinqikqi--kdv
l---a---lgvsrfqnaykkfiav-w------------------------
--cegssak----pevp--gy--ps---f-dggnterwg-----------
-p--sp-a--eypmehi--------l-akrqavlnldwa----rqypt
>ENV_HV2NZ/24-502
elvhlfkvkpha-enngkglkawgg----------lqtgad---------
-liadfhngstakg------aklhel--ag----a--efqltq----gn-
--yg---fan----------lldt---------s-vledky---------
---a------d----kgglknptevesglaqr-----------iqarylk
vnmdgtg--ivefyr----------evigdrhitpktp-----e--yanv
nrrrpt-tytmksdfr--ggkaiqganaadpiti----dskeelaqdswq
-----a-kqvyg--ng--------kecpgaclk---v-ny----hqplf-
eapkgt----lcptvaaspsk-sye---gqgll------s-f-----apv
ahvppaank---l--plssk----------alsvnyna-lel-fqald--
elc--fev------------dhaalkeka-------------------wg
a----q---------etf---av---pldwqa---qmkfs-s-------p
----------pneq----qvgpnq--p-----------------------
c-----t--------------syrqgl-eggarl-paevvipygs---g-
------ekglnkrvia---rigsmnhs-epglkgasattfnkqkppf---
h---t--vit-tqvtal------lvktt--sscdlaellnqikai--keg
l---s---lgvsrfqgaynkfvsv-waq----------------------
s-cegsrakkqqgqavp--gv--pt---y-dgq---rwg-----------
-p--ap-a--p----cv--------l-vkrqavlhlewd----rqypt
>ENV_HV2BE/24-510
d---------ha-ed--kglkawtv----------lqtgae---------
-liavfhqgvtgeve----kqklhnl--ks----a--efqlkk----sd-
--ya---faa----------llet---------g-vladky---------
---s------n----k-----pvknenglpar-----------vqgrdvk
lnta-tg--i--yfr----------kvfgdntitaklp-----k--ynsv
nrrrptgm-tfksafr--ggktiqnantadpvtv----dsedelaqdswq
-----a-dqlyg--nlkhpaeldgrhcglpclk---r-nf----hqalf-
eatkdallkklcpiisl--sknsyq---asgll------s-hsvgnlaps
aqvapaank---l--tlkakkve------galstaysg-l-l-feyldye
ekc--f--ge--tl------edatlkdkalkrg---------------rg
a----r---------etf---al-------hd---qgkfq-k-------s
lhsyvk-knvpkeq-hgsqvgpge--p-----------------------
c-----n--------------eyrqglenggehn-pkdivipigs---g-
------etllpakkia---kinnmnhn-epgikgatttkfieqkspy---
h---t--lat-tevasl------llkts--pscdvadllnhikai--kal
l---a---lgvsryqkayntfigv-rar----------------------
s-cegpsakkhqgptvp--ny--pt---y-dgq---rwgk----------
-p--gp-v--d----kv--------lfdkrqavsnlewk----rhypt
>node9
elihlfkvkpra-enggkgikawsl----------let--e---------
-liavfhqgltaevh----kqtlhnl--dr----a--efqldh----gn-
--ya---fankt----aspplldp---------g-vleeky---------
---s------d----p-----ptkhesglpqr-----------vlnravr
csmg-ag--taeffr----------ktfgekkitpktp-----d--yasv
nkrrpt-mfamksqlr--ggktihganaadpiti----dsddelaqdswq
-----t-delyg--nr--------kecpvpcls---p-ny----yrtff-
eppksallkklcptvsa--sknsye---aqgll------s-y-----gsg
aqvlqavek---e--tltark-q------nal----dg-lam-feyld--
ekc--f--td--tp------desnlkdnkvkrg---------------wg
a----r---------gtf---al---pldwhs---qgkfe-n--------
-h--vr-knvpneq-rgtqigpgq--p-----------------------
c-----t--------------syk------gsrl-saevvipigs---g-
------eggintksianyg--gdmrhs-epglkgvtatkflaqsspy---
h---t--lan-thvtnl------liras--ttcyiaallnqikvi--kev
lngpa---lgvarfrgaynkflgv-war----------------------
s-cegsstrkhqgptvp--gttapt---y-dgq---rwg-g---------
-p--ap-a--n----el--------l-akrqavlnlewd----rhypt
>node10
elihlfkvkpra-enggkglkawnv----------let--d---------
-liavfhqgatadvh----kqtlhnl--ss----a--efqlkq----gn-
--ya---fankt----aspplldt---------g-vleeky---------
---s------d----p-----ptkhesglpqr-----------vlsrdvk
cnmg-ag--taeffr----------ktfgdkkitpktp-----d--yasv
nkrrpt-mftfksqlr--ggktihganaadpiti----dsddelaqdswq
-----a-dqlyg--ns--------kecgvpcls---v-nf----yqalf-
eppksallkklcptvsp--sknsye---aqgll------s-y-----gps
aqvpqavek---s--tltakk-q------naltiayng-lal-feyld--
ekc--f--td--tp------eeanlkdnmvkrg---------------wg
a----r---------etf---al---pldwhs---qgkfq-n-------s
lh--vr-knvpneq-rghqvgpgq--p-----------------------
c-----t--------------sykqglenggarl-paevvipigs---g-
------egginaksianygrignmnhs-epglkgvtatkfieqkspy---
h---t--lat-tqvtsl------lvras--ptcsiaallnqikti--kev
l---a---lgvsrfqgaynkflgv-war----------------------
s-cegsstrkhqgpavp--gt--pt---y-dgq---rwg-g---------
-p--sp-a--e----ev--------l-akrqavlnlewd----rqypt
>node8
elv-----aq---nnstrgikq-------------lqt--d---------
-yvsv-----avegd----enhh-----dt----g--efqldh----sn-
--ha---fgltd-----kpallqpvhlvfy---g-ilidny---------
---t------n----p-----p----aafkqrtttaagaamnggnyqana
camg-lg--g----h----------tdqgekdii-rtp-----f--yntv
ekrep---iv--------gsksihghnpaepasv----dstd-lppdnwl
-----t-nvffa--kk--------kdcptkcya---q-gycc-ly-sfa-
ippmgdlskalcatipa----ktyl---tsglv------sgy-----asg
gevvqatvt---e--altgsk-s------tvl----dg-glm-ykflp--
dhc--i--ne--sp------edanfrdnnvkrd---------------w-
---------------------------lywhk--kqgkfq-d--------
-h--vrprni---a-rsnplgsah--s-trhr---e---------efgdc
c-----t--------------ny-------------avaakpigg---t-
------s-aie--ti------ydk-ds-ass-kevt-qgfmpdanpt---
r---c--laddshatsl------llrpg--sacyvs-llnhyavv--knv
ldgta---lgva----tfnkylga-wsnsrdaa--lna-prpgfesfrck
pl--------nq---ep--qatapk---f-edq---kyg-vksgvmrg--
-p--tplt--e----el--------l-n-------adfeip--snspi
>node18
elvhlfkvkpha-enggkglkawnv----------lqtgad---------
-liavfhqgstadvh----kqklhnl--ss----a--efqlkq----gn-
--ya---fan----------lldt---------g-vlqeky---------
---s------d----k-----ptkhesglpqr-----------vqsrdik
vnmg-ag--taeffr----------kvfgdkkitpktp-----d--yasv
nrrrpt-mftfksqfr--ggktiqganaadpiti----dsddelaqdswq
-----a-dqlyg--ns--------kecggpclk---v-nf----hqalf-
eapksallkklcptvsp--sknsye---aqgll------s-y-----aps
aqvppaank---l--tltakk-q------nalsiayng-lal-feyld--
ekc--f--td--tl------edanlkdkavkrg---------------wg
a----r---------etf---al---pldwhs---qgkfq-s-------s
lhvyvr-knvpneq-kgsqvgpgq--p-----------------------
c-----t--------------syrqglenggarl-paevvipigs---g-
------etglnaksia---rignmnhs-epglkgatatkfieqkspy---
h---t--lat-tqvtsl------likts--pscdvaallnqikti--kev
l---a---lgvsrfqgaynkfigv-war----------------------
s-cegssakkhqgpavp--gy--pt---y-dgq---rwg-----------
-p--gp-a--e----qv--------l-akrqavlnlewd----rqypt
>ENV_SIVG1/22-522
dem-----se--gnqstrgikq-------------lq-------------
----v-------dgk----ekhq-----er-igdg--eyqldh----sn-
--va---fnlte-----kpallqplhlify---d-vlidty---------
---tkstchss----i-----p----itfkqrtivigsgdmkggnyeada
cvmg-lg--g----h--qwedgpsr--hgeakii-r--------------
-kras---iv--------gskainghnpgepesv----dstd-nppdnwl
kdctit-sisfa--kk--------kncvtkccv---d-gycc-ly-sls-
ippmgdltkalcaav------ntyls--tqalv------fgy-----esg
adaavatit---e--altgkk-vg----lvvv----ns-alm-yknlp--
eht--i--sq--ga------dkasykk--vkkd---------------w-
---------------------------lywhkaqksgkfq-e--------
-h--i-p--v---a-rsdplgslhqk---rqk---iglegpii--efgdc
ckgsarphnaswk--------ny-------------avtakpigg---tq
qhqvpas-ava--tf------ydk-es-ges-kevv-qgympdeept---
rg--c--lapnt--tsl------llrqg--p------llnhyavv--kkv
ldgtk---igia----tfkkylga-wgnsrdla--vta-grasfesfrhq
pl--------ta---aa--haispk---yvedq---kyg-vkpgvlrgkl
ds--tpla--q----ll--------l-t-------nafeig--snaki
>node11
elvhlfkvkpra-enggkglkawnv----------lqtgad---------
-liavfhqgstadvh----kqklhnl--ss----a--efqlkq----gn-
--ya---fan----------lldt---------g-vlqeky---------
---s------d----r-----ptkhesglpqr-----------vqsrdik
cnmg-ag--taeffr----------kvfgdkkitpktp-----d--yasv
nrrrpt-mftfksqfr--ggktiqganaadpiti----dsddelaqdswq
-----a-dqlyg--ns--------kecggpclk---v-nf----yqalf-
eapksallkklcptvsp--sknsye---aqgll------s-y-----aps
aqvpqaank---l--tltakk-q------nalsiayng-lal-feyld--
ekc--f--td--tl------edanlkdkavkrg---------------wg
a----r---------etf---al---pldwhs---qgkfq-s-------s
lhvyvr-knvpneq-kghqvgpgq--p-----------------------
c-----t--------------syrqglenggarl-paevvipigs---g-
------esglnaksia---rignmnhs-epglkgatatkfieqkspy---
h---t--lat-tqvtsl------lvkts--pscdiaallnqikti--kev
l---a---lgvsrfqgaynkfigv-war----------------------
s-cegssarkhqgpavp--gt--pt---y-dgq---rwg-----------
-p--gp-a--e----qv--------l-akrqavlnlewd----rqypt
