>node8
in----hpkgvkeiark------------felpkfydld--g-na--ltt
qmvlggvig---qd-igd-----plt-l-gkfqvnnkagpldwrwskcpv
vhyvpf------------la--------rpg-lkcaddfpq--l------
---lt-pcilsp-----a---qgtwyigl--le-g---dqndk---salk
-----flesdkf------ssvtg----pp-kt----l---------g---
-aglhreel-r--priptl--i---gnpy-----k-a-rlh-vhici-si
dg-h--csd-ndt--ltgag--khfp---alsp-r---ftvtn-i-ys-l
tq-tkaq---lgth----a-nle--me---k--lq--fr-p---l----t
qmfdldtastt---ar-w--cfs---dc----plgls----gwgkd-lfn
at----t--------itfkyhwny------------a--f----------
-s------aievghqssm--------------k-----v----ginnksw
--r----kgtpq-pcakdds-pksf--avk----gi---f------fcp-
--m-is------ra-t--gpet---wvvpn------krk----r-qiptv
--vryyrwsr--lcaaakav---------aytsmhl--fgschhc----n
vst--gakv----v----------h-----------f------aa-q--l
-fe--rpgs--------a-------takl--fyraypdtr--ismkl---
--kdtn-gcayet---d----ssdwkv-----ek-ledrlaasf-acn--
-pd----da-----------hqn-estngd---hgg--------------
--gptasfk---d--aem------ragkc----dlqg-daggapkva--l
pgetglln---------rkad-sc------gd-dknvsdhevd-------
-------nwk--fepk----i---vedpvtypegi-am---d-aw-----
---------------tg--hcpi-------qv-----------kfmtt-a
-s-------i-v-c---df
>ENV_HV2D2/24-513
vn----hprgsth---k---------------psfyevdayp-kv--p--
-------ie---hh-vg-----------tgryaqndtsgplawrwi-ppl
vsyief------------lpydcgiaefses-lqcaeafvk--lkiqstp
sva---pcliaa------v--ikywy------a-g---e--da---ppfd
-----av-----------tnh-k----na-ht----a---------h---
-w----ddl-q--pk-qtq--t---gtds-----k-aqr-----------
-------ae-aahdaitgsg--klfprydvslp-e-----lam-i-cr-f
th-tg--------r----t-------k---r--v-----gp---h----l
iv--lgsvta----------nyn---et----rfaftna-ggwvt---id
vf----f--------aa-rylsdyvaleiscvhclta--i----------
-k------aq---hkafl--------------alyly-c----avtekdw
nft----rakqkprcakegqgseif--ylt----di---flacr--ict-
--m-vk------pdts----------kapand----skkethvr-qiplv
lqvayyhwg---qcsatn--sfhrv--------------gs--h------
-rp--dpsr----vscvlgtt-lqh-----------f------aa-lsgl
--k--rvadklyeygsdn-------tkal--fyapfagta--vsmdalgf
legeanlgc-yna---gngtaledwsi-----kkklqnn----fgvcg--
-hd--------ysvln----tsr-faldeq----dq--------------
ksapdekfk---klhlet------rgng-------ad-n-ggt-keagll
vtegk--g---------pase-gcmdansngs---------vp-------
-------dwt--fgpv----a---ap---------------d-vw-----
---------------qarehsp----------------------------
-------------c---et
>ENV_HV2CA/25-512
vn----hargsde---k---------------esfydid--a-qv--v--
-------ve---hhpvg-----------gghymrndplap---rwa-apl
vthief------------lpyd-----fnha-llcafpfpk--l------
---lt----iga------v--nkcwfrgl--ia-g---d--ip---pvlr
-----av-----------agq-d----aa-ht----l---------h---
-tvlhredl-h--phdqtq--g---gnda-----k-nqr-----------
-------ad-ish--itgdg--kafs---vpqscd-----lgs-i-cr-f
gh-va--------r----g-vve--vk---r--i-----k----------
------------vgch-w--dcsvvadt----rfgftnatggwgk---vd
vg----y--------ts-pqkryfgpadv--lhcisa--f----------
-k------nt---ndpal---------------m----------lsekgi
gyt----rspkspqctkegkg------ystgcyndi---fwpck--icp-
--p-vp------p--sfggp--------pinn----tr-------qfplv
sqvefysweh--qcyank--pifkim---dftdaqw--fag--h------
-ai--vpgr----vscvl-st-lqp-----------f------al-v-gl
i-k--rvas--------d-------tksl--fykgyagka----maa---
--dsltldc-feh---a--tttqnwki-----ek-ldtg----f-acg--
-hd----ysivysffd----tqkkfklnggifardr--------------
--aakekyk---klhlqa------rakar----rlasln-g---------
--eaelagasklvvhekpapd---------vs----------p-------
-------dwk--fgpt----m---tv---------------e-vw-----
---------------qa--nspl-------ea-----------------v
tt---------i-c---ef
>node7
in----hpkgvkeiask------------felpk--ngd--gvha---st
qmvlg-vtg---qd-igd-----plt-q-gkfqvdhkagplnwrwekcpv
vhyvsf------------ls--------rpgtlkcaddfpe--l------
---lt-ssllspafdtla-vkegtwyigq--le-g---sqndkniwpalk
-----lletdkvn-a---p---g----pa-ks----l---------g---
-ag-hrdel-r--priptl--t---gnph-----k-a-rlh-vhicf-sa
et-h--cne-hev--ltglg--khir---ktap-r---fvvmn-m-ys-l
ga-lkaq---lgth----a-nla--me---g--lq--yr-p---q----t
emfdldtastt---vr-w--cfs---nc----plgln----gwhke-lfe
ki----l--------itykyqwqy------------tngf----------
-s------a--vgpqssm--------------k-----v----ginhksw
--r----kgapq-pcekeds-pksf--avk----gv---f------fcv-
--m-iatfckd-ra-t--gpet---wavpn------krk----p-q-ptv
--vryyrwsr--lcaaanai---------aftsmhl--fgschhc----n
vstikgakl----l----------h-----------f------aa-q--l
-fi--rsga--------gpaltsifagkl--fyraypdtr--ipmkl---
--kdtg-gcayet-aed----asnwkv-----ek-lhnrlaasf-tck--
-l------a-----------hen-el-------hgg--------------
--kptasfk---d--sem------ragkc----dlqg-sasgapqmt--l
psetglln---------pkad-sc------gd-lknvnshevnkkstq--
-------nwd--fehk----i---venpvtytegv-am---dfaw-----
---------------ag--hcpa-------hv-----------kfiamlv
-s-------v-v-c---df
>ENV_SIVGB/47-569
apgthdfaql-----k--------------skp--------------lpq
vq-hgnvvgcripk-sglwdfnk--scd-ettaairka-gapral-----
-ny--tklkqvslikisgla--------rs---gcac-------------
---kalp--------------------kl--le-d---tks-----pkgn
csgalyl--qhe--------cfa----t----------------------
---anrrgl-v--khkqkr--vrttg------------------mgl-et
kagktkiiq-pas--gpa-----------arrg-dvrgfhave----e-l
lqqriskntalgphpcnk-------------------vl-ndqkcpcnrt
k---------p---ad-w--aie---g-----nyglv----nngkdvlfg
al----ayfktqhsdva----------------------kcylagvgpgt
itsaefkpkvgvvtelsaetspylilkallrck----qg----g-anrgf
--sgmaglgakg-gcaqdd--a--mnd-------qk---y----vqccsp
vlmpva-------a-----pka-vptaip--------q-------p---l
--lkafr-----------ne------qpaaygglklrsqggaelc----k
-------------v----------v---caqssike--------------
--apqrdes--------p-------iii------acldakfwlel-----
--kggt-pcqcd---------saawrtglfrtek-km--fgaal-lkd-a
e------qv-------kgyehhd-npspm-----ggggtqcfsgskarca
--qsglifn---t--dimfravcv---------------asntpvv----
-sia-fah---------kkaqntc------kl-gadtggeddl-------
-------swshv-aagdakh------kt------i-sinkt---l---as
pdeergrwvpivteq----qclvgppgglsqkvpagdfyrdgpiqmyi--
-tdngfdtcfhvfcpvapl
>node18
vn----hprgste---k---------------psfyevd--p-kv--l--
-------ie---hhpvg-----------gghymrndplgplawrwt-ppl
vtyief------------lpyd-----fshs-lhcaesfpk--l------
---lt----iga------v--nkcwfrgl--la-g---d--id---pvlr
-----ai-----------tsq-n----pa-ht----v---------h---
-svlhrddl-q--phdqtq--g---gnds-----k-aqr-----------
-------sd-sah--itgdg--klfs---vpqp-d-----las-i-cr-f
gh-ta--------r----g-nve--vk---r--i-----n----------
------------vgck-w--dys---dt----rfgftna-ggwgk---ie
vs----f--------at-rhmshygpadi--yhciaa--f----------
-k------nq---hdaal--------------sm----------vteknw
nyt----rskkspqcakegrgsavf--ymt----di---fwpck--ics-
--p-ik------pdts--gppt---wiapinn----sr-------qfplv
lqvayyrwan--qcsask--affrvm---efttmqw--fgg--h------
-ai--dpsr----vscvl-st-lqp-----------f------aa-v-gl
--k--rvae--------d-------tksl--fykdyagta----mqa---
--egttlgc-fgg---gngtttenwki-----ek-ldnn----f-acg--
-hd----ysiyysvld----tqk-fslngg---rdr--------------
--aakekfk---klhldt------rasgr----rlas-n-g---------
--eaelag---------pane-gc------va---------vp-------
-------dwk--fgpv----v---tt---------------e-vw-----
---------------qa--hspl-------ea-----------------a
kt---------v-c---ef
>ENV_HV2BE/24-510
vn----qpr-ste---nyvsgdqtrrvwa---pslyevd--p-kvkn---
--------e---hhavg-----------gahymrneplgplawrwt-pel
vtaiaf------------lpyn-----fshs-fhcadsypk--l------
---lt----isg------v--nkcwfrglkama-ataed--ls---pvlr
-----ai-----------tnq-n----pa-ht----v---------h---
-svlhhenl-q--phqntr--m---gndstsvsek-aqr-----------
-------sdaagh--iigdg--klss---ipqp-e-----lasli-crtf
gh-vd--------g----g-dispmtk---n--i-----n----------
------------vgck-w--pyt---dh----rfgfcna-gewgk---ie
v-----------------rnksgygstdf--yhciei--f----------
-k------nq---hdaav--------------vm----------vteanw
kyt----kgnksercekegrgsavf--ymt----ti---fwpck--mcs-
--p-ik------pdts--gpst---wvanisn----sr-------afplv
lqvaihmwan--ecsg-k--gffrvm---eyttmqw--f-g--h------
-pi--saar----nacvl-sv-lqppcg--------f------aa-i-gl
--k--haae--------n-------tknl--fykdyagtt----mpa---
--egtnlgc-fggk--sngttpdnwki-----ek-ldsk----f-acgy-
-ha----ysifysvlg----ter-fnli----------------------
----kekfk---klhldt------rasgr----rlat-d-a---------
--paelag---------qake-gc------vak--------va-------
-------dwk--fqpv----v---kt---------------q-vw-----
---------------qq--rspl-------ev-----------------t
kt---------v-c---ef
>node19
vn----hprgste---k---------------psfyevd--p-kv--l--
-------ie---hhpvg-----------gghymrndplgplawrwt-ppl
vtyief------------lpyd-----fshs-lhcaesfpk--l------
---lt----iga------v--nkcwfrgl--la-g---d--id---pvlr
-----ai-----------tsq-n----pa-ht----v---------h---
-svlhrddl-q--pqdqtq--g---gnds-----k-aqr-----------
-------sd-sah--itgdg--klfs---vpqp-d-----las-i-cr-f
gh-ta--------r----g-nve--vk---r--i-----n----------
------------vgck-w--dys---dt----rfgftna-ggwgk---ie
vs----f--------at-rhmshygpldi--yhciaa--f----------
-k------nq---hdaal--------------sm----------vteknw
nyt----rskkspqcakegrgsavf--ymt----di---fwpck--ics-
--m-ik------pdts--gppt---wiapinn----srkeshvr-qfplv
lqvayyrwan--qcsask--affrvm---efttmqw--fgg--h------
-ai--dpsr----vscvl-tt-lqp-----------f------aa-v-gl
--k--rvae--------d-------tksl--fykdyagta----mqa---
--egttlgc-yga---gngtttenwki-----ek-ldnn----f-acg--
-hd----ysiyysvld----tqk-fsldgg---rdr--------------
--aakesfk---klhldt------rasgr----rlas-n-g---------
--eaelag---------pane-gc------va---------vp-------
-------dwk--fgpv----v---tt---------------e-vw-----
---------------qa--hspl-------ea-----------------a
kt---------v-c---ef
>ENV_SIVV1/24-538
rs----hpyavrevalk------------felpk--ngg--gvra---ss
qmivg-gag---qd-isd-----sla-t-akfhadhkiralnwksenapa
lhyvkl------------ls--------rpgtlkcpddfle--l------
---lt-gtlepptfntla-iiegswy-ge--vemg---sqndknirpvli
-----llkvdkvndp---p---g----ps-kt----l---------gevd
l---hqg---------psl--t---ggp--------------vhvcfasa
et-n--cne-hev--ltglgddahik---kts---------tn-l-ys-l
g-----q---lgth----a-aia--ledrag--leiyya-p---k-----
elfdletasta---va-w--cfs---hcdkllplgmn----awhkn--fe
kvktrvl--------mtgn-swhy------------angf----------
-s------a--vgp-sse--------------k-----vktelglshtsl
--s----qgesq-ccdrdrs-aksf--avk----gvtgff------fcv-
--m-vgafckkern-s-----cn--wavls--akqkkrk----p-q-itv
--trfyswnrgslc---nav---------aftamhl--sg-cchcdnepn
iptikgakl----l----------h-----------g------sa-t--l
-fl--rasa--------gpaltsifvgkl--fyrgypkt-----------
----l--gcayet-aed----asnwtv-----ek-ihnrlpasf-tce--
-l------a-----------hsk-el-------hgg--------------
--kpe-------d--aem------ragkc----dlq--sangaga-h--v
psstgenn---------prpn-sc------gd-lktakrhevnkmltq--
-------gwd--fdhk----i---ae----ynegstam---kfmw-----
---------------gg--hspg-------hv-----------kfiailv
-s-------v-v-c---df
>ENV_SIVM1/24-528
vs----hprek-----------------------yfavd--p-kv--l--
-------td---hh-vg-----------g--htragpsgp---hwt-tpl
ttyldy------------lvyk-----fsqs-lhcmnafpk--l------
---lt-pcltga------i--dkcsyrgl--l------dlked---palk
-----dm-----------tsq-n----cp-ht----v---------h---
-aethsdel-hpvpkqqqq--a---gkds-----k-aqr-----------
-------sd-sgh--itseg--klfp---vlqp-d-----vas-vacr-f
gt-dm--------t----g-nle--lk---r--i-----nv---l----m
vk--lgtakts-igcn-w--nys---dt----rfgftna-agwgk---fe
gt----f--------at-kymvnygaldi------aa--f----------
-n------aqgs-----l--------------slyly-s----avsegpw
nyk----tgkqtkqcakeahgpraf--tmt----di---flpcm--ics-
--m-vk------pdts--gppt---wvaplnn----nrneshtr-qipai
lhvpyyrwak--pcsgsk--dffrvl---tfttmhl--fgt--h------
-ri--dpar----vgcvl-tallqh-----------f------ta-v-gl
--k--rvgh--------e-------tksl--fykpyagtc--ismqs---
--adtnltc-ygn---gngatsddwki-----ek-leks----f-acg--
-hd----nniyysvld----qer-fsvdgd---wdq--------------
--atkasfr---klhlda------saskc----qlag-n-ggaa-----l
asqaq-------------hkd-gc------is---------ip-------
-------dwk--fgpt----i---tt---------------e-iw-----
---------------qg--hspl-------da-----------k-----a
ka---------v-c---ef
>node10
vn----hprgste---k---------------psfyevd--p-kv--l--
-------ie---hh-vg-----------gghytrndpsgplawrwt-ppl
vtyvef------------lpyd-----fsqs-lhcaeafpk--l------
---lt-pcliga------v--nkcwfrgl--la-g---d--ed---pplr
-----ai-----------tsq-n----pa-ht----v---------h---
-salhrddl-q--pkdqtq--g---gnds-----k-aqr-----------
-------sd-sah--itgdg--klfp---vsqp-d-----las-i-cr-f
gh-ta--------r----g-nve--lk---r--i-----np---l----m
iv--lgtvkta-vgck-w--nys---dt----rfgftna-ggwgk---ie
vs----f--------at-rymsnygpldi--yhciaa--f----------
-k------aq---hdaal--------------slyly-c----avteknw
nyt----rgkkspqcakegrgsavf--ymt----di---flpcr--ics-
--m-vk------pdts--gppt---wiapinn----srkeshvr-qiplv
lqvpyyrwan--qcsask--affrvm---tfttmqw--fgs--h------
-ri--dpsr----vscvl-tt-lqh-----------f------aa-v-gl
--k--rvae--------e-------tksl--fykpyagta--igmqa---
--egtnlgc-yga---gngtstenwki-----dk-lenn----f-acg--
-hd----yniyysvld----tqk-fsldgg---rdq--------------
--aakesfk---klhldt------rasgc----rlan-n-ggaekeagll
asqaelag---------pane-gc------vs---------vp-------
-------dwk--fgpv----v---tt---------------e-vw-----
---------------qa--hspl-------da-----------------a
kt---------v-c---ef
>node9
vn----hprgste---k---------------ptfyavd--p-kv--l--
-------ig---hh-vg-----------ggkytradptgplawrwt-tpl
vtyvef------------lpyk-----fsqs-lhcaeafpk--l------
---lt-pcliga------v--dkcwyrgl--la-g---dlked---palr
-----ai-----------tsq-n----pp-ht----v---------h---
-salhsddl-h--pkdqpq--a---gnds-----k-aqr-----------
-------sd-sah--itgdg--klfp---vlqp-d-----vas-i-cr-f
gh-tm--------t----g-nle--lk---r--i-----np---l----m
ik--lgtvkts-vgck-w--nys---dt----rfgftna-ggwgk---fe
vt----f--------at-kymsnygpldi------aa--f----------
-k------aqgvghdaal--------------slyly-c----avseknw
nyk----rgtqtpqcakesrgpkaf--tmt----di---flpcs--ics-
--m-vk------pdts--gppt---wiapinn----nrkeshtr-qipai
lqvpyyrwak--qcsask--affrvm---tfttmhl--fgt--h------
-ri--dpsr----vscvl-tallqh-----------f------aa-v-gl
--k--rvgd--------e-------tksl--fykpyagtc--igmqa---
--ddtnlgc-ygt---gngtstdnwki-----ek-lens----f-acg--
-he----nniyysvld----qqr-fsldgd---rdq--------------
--aakasfk---klhlda------raskc----qlag-n-ggaakeagll
asqaelag---------phne-gc------is---------vp-------
-------dwk--fgpv----i---tt---------------e-vw-----
---------------qg--hspl-------da-----------k-----a
ka---------v-c---ef
>ENV_HV2NZ/24-502
v-------------------------------esfyaig--p-qv--l--
-------vd---hhpvg-----------svhymrnaplgp---rwt-gpl
vqyvdf------------lp-d-----fshp-lhcvesfpk--l------
---lt----iga------v--skcwfrgl--la-g---d--in---pvfr
-----ai-----------tng-d----aarht----v---------h---
-gilhrddl-q--pvdqaqeia---gnes-----k-tqr-----------
-------ad-sah--ltgdg--klet---vpqp-d-----las-i-cr-f
gh-va--------r----g-nvd--vk---r--t----------------
---------------m-wfadcg---di----rfgfteatsvwgk---ie
vs----f--------an-rhmshygaadl--yqcisp--f----------
-k------tt---hnaap--------------sm----------vaqhnl
gyt----rspksvqctkegrgsmvf--fma----dv---lwpck--lck-
--p-ik------s--s--gppt---wiapikn----tr-------qfqlp
tqkeyykwan--qcpaqk--pffqym---efsamqw--fgg--h------
-el--dpar----vscvl-st-vqg-----------hevsqcgaa-v-gl
--k--riae--------d-------sksl--fykdyagta----------
------lgc-ygg---a--ta--nwki-----er-lnng----f-acg--
-hdglplydiyygvld----tvk-fsinggifardr--------------
--pakqkfk---klplda------rasar----rlss-s-g---------
--elemggdgslvvhekpgpe---------va---------ep-------
-------dwk--fdev----mgeptt---------------e-vw-----
---------------qa--hspl-------ea-----------------v
tt---------i-c---df
>node11
vn----hprgste---k---------------psfyevd--p-kv--l--
-------ie---hhpvg-----------gghymrndplgplawrwt-ppl
vtyief------------lpyd-----fshs-lhcaeafpk--l------
---lt----iga------v--nkcwfrgl--la-g---d--ed---pplr
-----ai-----------tsq-n----pa-ht----v---------h---
-svlhrddl-q--pqdqtq--g---gnds-----k-aqr-----------
-------sd-sah--itgdg--klfs---vpqp-d-----las-i-cr-f
gh-ta--------r----g-nve--vk---r--i-----n----------
------------vgck-w--dys---dt----rfgftna-ggwgk---ie
vs----f--------at-rhmshygpldi--yhciaa--f----------
-k------nq---hdaal--------------sm----------vteknw
nyt----rskkspqcakegrgsavf--ymt----di---fwpck--ics-
--m-ik------pdts--gppt---wiapinn----srkeshvr-qiplv
lqvayyrwan--qcsask--affrvm---efttmqw--agg--h------
-si--dpsr----vscvl-tt-lqp-----------f------aa-v-gl
--k--rvae--------d-------tksl--fykdyagta----mqa---
--egttlgc-yga---gngtttenwki-----dk-ldnn----f-acg--
-hd----ysiyysvld----tqk-fsldgg---rdr--------------
--aakesfk---klhldt------rasgr----rlas-n-g---------
--qaelag---------pane-gc------va---------vp-------
-------dwk--fgpv----v---tt---------------e-vw-----
---------------qa--hspl-------ea-----------------a
kt---------v-c---ef
>node14
vn----hprgste---n---------------pslyevd--p-kv--l--
-------ie---hhpvg-----------gghymrndplgplawrwt-ppl
vtyief------------lpyd-----fshs-lhcaesypk--l------
---lt----iga------v--nkcwfrgl--la-atmed--id---pvlr
-----ai-----------tsq-n----pa-ht----v---------h---
-svlhrddl-q--phnntq--g---gndsssvsek-aqr-----------
-------sd-sah--itgdg--klfs---vpqp-e-----las-i-cr-f
gh-ta--------r----g-nis--vk---r--i-----n----------
------------vgck-w--dys---dt----rfgfcna-gdwgk---ie
vs----f--------at-rhkshygptdi--yhciaa--f----------
-k------nq---hdaal--------------sm----------vteknw
nyt----kskksercakegrgsavf--ymt----di---fwpck--ics-
--p-ik------pdts--gpst---wiapinn----sr-------qfplv
lqvafyrwan--qcsask--affrvm---efttmqw--fgg--h------
-ai--dasr----vacvl-st-lqp-----------f------aa-i-gl
--k--rvae--------d-------tknl--fykdyagta----mqa---
--egttlgc-fggk--angttpenwki-----ek-ldnk----f-acg--
-hd----ysiyysvld----tqk-fslngg---rdr--------------
--aakekfk---klhldt------rasgr----rlat-d-g---------
--eaelag---------qane-gc------va---------vp-------
-------dwk--fgpv----v---tt---------------e-vw-----
---------------qa--hspl-------ea-----------------t
kt---------v-c---ef
>ENV_HV2D1/24-501
vk----hgrgste---t---------------sclyevd--e-kv--l--
-------ie---hhpve-----------gghymkndplgplawrwa-ppl
vtyipf------------lpyd-----frks-lqcaegypk--l------
---li----ig-------v--nkcwfrgl--la-aaved--id---pvir
-----ae-----------asq-nvevapa-htelamv---------h---
-sm--rael-q--phnnkq--g---gnds--vsek-aqr-----------
-------sd-sa----tgdg--klfg---vpkp-e-----las-i-cr-f
gh-ta--------r----i-nis--vk---rgqi-----n----------
------------vgcs-w--typ---dt----rfgfcna-gdwgk---ve
as----f--------av-rhrshygptnv--fhclea--f----------
-k------dq---hnapl--------------sm----------vteknw
nys----ksnksdrcakegrgsavf--fms----ei---fwack--ics-
--p-ir------pdes--gpst---witpinn----tr-------qfplv
lqvalykwan--qcsaak--affrlm---efatmqw--fqg--n------
-ai--dtrrigapvacal-at-vqp-----------f------aami-gl
--k--rvae--------d-------tknlkkfykdyagta----lqa---
--emttlgc-fggk--anattpegwgi-----dk-ldqr----f-scg--
-------fsiyysvle----krk-ftlkng---rnr--------------
--gakakfk---klhldt------redgr----rlat-k-g---------
--eaelqg---------qaie-gc------va------------------
---------k--fgpv----i---tt---------------e-vw-----
---------------ha--hsel-------ea-----------------t
kt---------v-k---ef
>ENV_SIVG1/22-522
tn----hpkgvkeiasr------------felpk--ggd--gvhn---s-
--alg-ntc---qd-igd-----plt-q-gkfqvdhkagplnlr-ekcpv
vhyvsf------------ls--------rrgdlkcandipekll------
---lt-sallspaf-dla-ikegtw-------d-g---aqeekniwpplk
-------qtdsan-alvcp---g----pa-ks----l---------g---
-sg-hrdeler--pkiptk--t---gnph-----kls-rfqnvhvcf-ta
en-h--che-hdv--lhtlg--keir---mtap-r---fevmt-m-yn-l
ga-lkgq---lgth----agnla--me---g--ll--yr-p---r----t
emynldgastt---ir-r--cfg---nc----nlgvn----gwhke-lfe
ki----q--------itykyqwqy------------sngl----------
-s------a--vqpqtsv--------------k-----l----gishmsw
--k----dgapq-pcekeds-pkst--avi----gv---f------fcs-
--m-i--------g-s--gtdt---wpvrn------rrk----p-q-rtv
--vryyrwps--lcaaandi---------aftprhl--fgschhc----n
vstikgakl----l----------h-----------y------aa-q--l
-fi--msga--------gpglttifagkl--fyrsypdtr--ipmkl---
--kdsg-gcayet-aed----asnwkv-----ek-fhnrlnatf-vck--
-f------a-----------het-el-------h----------------
------sfkqin----------------i----dlqg-easgckqmt--l
pietgllp---------pkad-sc------ge-lknvnrhpvnkknlqkg
pvkqlgdnwd--fshk----i---venpvtytagv-am---dlawgkn--
---------------ag--hcpa-------qi-----------kfvsslv
-s-------i-v-c---kf
>node17
vn----hargste---k---------------esfyeid--p-qv--l--
-------ve---hhpvg-----------gghymrndplgp---rwt-ppl
vtyief------------lpyd-----fshs-lhcaesfpk--l------
---lt----iga------v--nkcwfrgl--la-g---d--in---pvlr
-----ai-----------tsq-d----aa-ht----v---------h---
-svlhrddl-q--phdqtq--g---gnds-----k-nqr-----------
-------ad-sah--itgdg--klfs---vpqp-d-----las-i-cr-f
gh-ta--------r----g-nve--vk---r--i-----n----------
------------vgck-w--dcs---dt----rfgftnatggwgk---ie
vs----f--------as-rhmshygpadi--yhcisa--f----------
-k------nt---hdaal--------------sm----------vteknl
gyt----rspkspqctkegrgsavf--ymt----di---fwpck--ics-
--p-ik------p--s--gppt---wiapinn----tr-------qfplv
tqveyykwan--qcsask--pffrvm---efttmqw--fgg--h------
-ai--dpar----vscvl-st-lqp-----------l------aa-v-gl
--k--rvae--------d-------tksl--fykdyagta----mqa---
--egttlgc-fgg---g--tttenwki-----ek-ldng----f-acg--
-hd----ysiyysvld----tqk-fslnggifardr--------------
--aakekfk---klhlda------rasar----rlas-n-g---------
--eaelagdsnlvvhekpape---------va---------vp-------
-------dwk--fgpv----m---tt---------------e-vw-----
---------------qa--hspl-------ea-----------------v
kt---------i-c---ef
>ENV_HV2G1/23-502
gs----hprgste---k---------------psfyevd--p-sv--l--
-------ie---hhptg-----------gghymrhdvlgplswrwt-ppl
vtyigf------------lh--------sgs-lqcaea-pk--l------
---li----iga------v--nkcwfrgl--ia-g---d--ek---pplr
-----ai-----------vsa-n----ga-hs----vikarflgcah---
-gvlhhddl-q--prdptq--s---gnds-----k-aqr-----------
-------sd-sah--isgqg--klyg---vpqp-d-----las-i-cr-f
kr-ta--------r----g-nae--vk---r--i-----n----------
-----------v-vckfw--dys---dt----sfgfvna-ggrgk---ie
vs----f--------at-r------pldi--yhciat--f----------
-k------nq---hdaal--------------sk----------vtqknw
nyt----rnkkspqcakegrgsavy--yvt----qi---fwpck--ict-
--m-is------pd--------------pinn----arkekhvrgqiqmv
lqfpyyrwah--hcsaak--ahfrvl---eyttmqw--agg--n------
-si--dpqr----vscvl-st-lap-----------f------aa-i-gl
--k--rvae--------e-------tksl--fykdyagta----kqa---
--egttlgc-yga---gngstsenwki-----dk-ldnn----f-gcg--
-hd----ysiyyavld----tqk-fsldgg---rdr--------------
--aaketfk---klhlds------kasgralqlrlas-n-g---------
--qaelag---------pade-gc------vs---------ap-------
-------dwk--fgpv----v---ts---------------e-iw-----
---------------qa--hspl-------ea-----------------a
kt---------v-c---ef
