>node14
-f------ap-g---sf-sg------shann------pfw---------s
elrt----c----ihk---k----cr-apvlqqv----------------
----hsstfys-------------eyge----yle------cv---apvy
------l----t---kv-acqtpttlvfekdvnc--kkyhkcf-vchyhs
pqrkpq--am-------p----g---haytikkqp--p-nf---------
-------sakmv--g----kckflapysv----------------hkcnn
adkkfa-kpffqsr-yla-lk-------------tlrl--------ad--
------tgk---cv----kq-nnwd-gged---fv------y--htsqld
--ilgs----------tl--lap--igpn---ik-f------lftissty
snsrttvlgeigkssf----------wqeslsqp-n----kf--------
------------e--t-vl-kryn------g-vtclh--laegied--n-
------tavtpea-------------------kkplyselrwksphpeeh
nrggveraiiq-g-v-ncq-l--dkl--ekt-hdnlre----l-a-----
-tf----k--k------l---------gfppghf------------h---
-----dkntfylep-----d-------m---qnfk--livd----svael
flayteas----sfgenltggqphars---lvggady--ge--al-----
k------eltktgasls---vt---av--k------sdp---hvdghfra
gl----ns---------e-skhhage----rpaeky-i-gf---w--avi
eharq-p-----f--sdepgtdslasneafdq--------lifdtmelfg
gcnan----------d--dd-vlsvaaehgse-pslgti
>ENV_HV2NZ/24-502
-f------vp-a---mf-id------shlnd------sfw---------s
dlrt----c----ahk---k----cs-apvlrqt----------------
----hastfys-------------eygq----yle------ci---apvy
------l----a---kv-acqvpvtlvfehevsc--kpyhkcf-vchyha
pqrkle--am-------p----g---hgynvkkpp--p-nf---------
-------takmvktg----k-------cv----------------hkcde
sdkkfa-kpfyqsr-yra-vkk----------g-twqlq-dwyqpkad--
------tgk---ci----kq-nnwd-tvqd---fv------y--nttqld
--vlgs----------sl--lap--igph---in-y------lfslstty
snsknadggeigkstf----------wkeslshp-nqlsprf--------
------------e--s-vv-kpfn------g-vtcln--ltdgiqd--n-
------tavtpea----------------fdikkglftelrwksphaeeh
drggversllqds-igdcq-m--dkl--ekk-hdtlre----l-a-----
-tvkweak--k------f---------gfppshfdpnsadlrv--vh---
-----ekngfylee-----d-------l---q------vvd----svadl
flaytkaa----sfgeslaggqpqarl---ltggady--gq--al-----
h------eltktgasld---vt---tf--k------nde---hvdghfra
al----nsivagtegvke-skhhage----rpaeky-k-gf---w--avi
enarq-p-----f--hsspgtdslpsgevpdv--------lisdtmalfg
gcnan----------d--de-vlsvaaehgee-qklqti
>ENV_SIVG1/22-522
-f------ft-l--ttydtgkssvvg----p------qswfyvyafpnit
e--dkcelc----fqagcksprkvcr-tavlv-at--cth----------
----q---flnmqalgnlayvvptpyta----ypdgkdnsgcp---p--t
------lasvqt---nlnec-prftikfd---tl--kpc-k-f-lceyst
-----achet---tyqkv----v---acysiqkpi--p-kf---------
-------aakmi--n----r-------pl----------------hmcae
l--------linvryl----------------------------nsge--
------tlk---cv----npenpwh-gpgd---fv------y--hqaqld
tqktgsngknd-egg--isclerakdvte---vq-fqepsrgrq----s-
------hredtsksdy----------wlhstahp-h----h---------
------------ddet-tl-ktfylsts--g-kgclr--ldg------s-
------trayskmssg-------aamfnyaginrtlygkw----phpasg
--kkhrrhitk-a-m-dcp-l--qamgeddylde--------l-l-----
-sf----kvk-knftea-----------gggqdtipkl-------thq--
-----------iy------------------rhft--lifp----a-sne
fvyya--------fgtahehtspesit-----la-ny--ye--kl-----
r------nktst--pra---------vnsq------pep---hvknmkrn
al----gv---------dhkg---------q--qgy-gynf---w-lavl
esrqk-m-----itf-------g--g-gtaqh--------yvfiale--g
ec-mey-ce--i--ee--qe-qvk-ls---------hhf
>node19
-f------ap-g---af-sg------shann------pfw---------s
elrt----c----ihk---k----cr-apvlqqv----------------
----hsstfys-------------eygq----yle------cv---apvy
------l----t---kv-acqtpttlvfekdvnc--kayhkcf-vchyhs
pqrkpq--am-------p----g---haynikkqp--p-nf---------
-------sakmv--g----k-------sv----------------hkcnn
adkkfa-kpffqsr-yla-vkk----------g-tlrlq-dwyqpead--
------tgk---cv----kq-nnwd-gged---fv------y--htsqld
--ilgs----------tl--lap--igpn---ik-f------lfsktsty
snsrttvsgeigkssf----------wqeslshp-n----rf--------
------------e--t-vl-kpyn------g-vtclh--laegied--n-
------tavtpea----------------fdvkkglyselrwksphpeeh
drggveraiiq-g-i-ncq-l--dkl--ekt-hdnlre----l-a-----
-tf----k--k------l---------gfppghfdpnt-------vh---
-----dkntfylep-----d-------m---qnfk--livd----svadl
flayteas----sfgenltggqphars---lvggady--ge--al-----
k------eltktgasls---vt---av--k------sdp---hvdghfra
gl----ns---------e-skhhage----rpaeky-i-gf---w--avi
eharq-p-----f--sdepgtdslpsqeaadq--------lifdtmelfg
gcnan----------d--dd-vlsvaaehgde-pslqti
>node8
-f------ps-h--ity-agqssilg----s------qgway-----nit
e--e----c----fqqgckt----cr-apvlv-vk--cth----------
----hsqvfldlqalaelayivpssygq----ype------cp---ptvl
------l----a---kidecqprfsikfd---nl--kdc-k-f-vcqyts
-----dchet---iyypq----g---scynihkqt--p-kf---------
-------sakmm--n----r-------al----------------hkcae
l--------fiktr-yls-iske--v--vaqrg-y--------lnsgq--
------tlk---cv----nh-tawh-gpgd---fv------y--hqaqle
a-klgsn-kndadggnfi--larqrevrq---va-fqeksdarh----s-
------lrgdvsksny----------wleslahp-n----h---------
------------a--t-tl-ktfylgas--g-laclr--leg------t-
------trtypkmsgg------lagmydyagikrelygkwrwgtphpeen
--kalkrhiae-g-m-dcp-l--egm--denlde--------l-m-----
-sf----kvaqknfftpv---------agggpdaipkl-------ghri-
-----------ps------------------qhfr--lifp----aesnl
yvaya--------fgssldhsspetss-----va-ef--ye--kl-----
r------nktst--sla---lp---ivdgk------pnp---hvkglnrn
al----gp---------qdks-q--t----q--qgy-g-gg---w-havi
epsmk-a-----lgf-------s--mddaaqp--------aifiamelfg
gc-key-cq--i--ge--ae-iik-as---------qqf
>ENV_HV2G1/23-502
-f------tp-g---af-sg------shann------pfw---------a
elqt----c----ihk---k----------lqqv----------------
----etstfys-------------eygq----yae------cv---apvy
------l----t---kv-acqppltlvfegdvnc--ksyhkcf-gchyhs
pqgkpq--am-------p----g---htyhikkqp--m-nf---------
-------sakmv--g----k-------sv----------------pkcnn
atkkfa-kpyiqsk-yla-lkq----------g-tlrlq-dwyqpeae--
------tgk---cv----kq-nnwd-gged---fi------f--htsqls
--ilss----------tl--vap--igpn---ik-l------lfsstsry
nnsrttvsgeigkaaf----------wqeilsnp-n----rf--------
------------e--t-vl-kpyk------g-vtclh--laegidd--n-
------tavapqa----------------fdvkkalcnelrwkgphpeqh
nrggierailq---i-dcq-l--ekm--ekt-hdnlre----l-p-----
-tf----k--k------l---------gfgpghydpnt-------vh---
-----dkntfylgp-----d-------k---qnfkqklivd----gvadl
ylgyteap----slgvnltggqphahs---legqadyksga--al-----
kkserheeltk--esls---it---gv--k------sep---htdghfrs
gl----ss---------e-skhhsge-idhkpaeky-v-gf---r--tvi
tlarq-p-----f--sdtpgtdslpsqdgrdq--------lklptqelfg
gcnen----------d--dd-vlsvaaehgde-ptlqti
>ENV_HV2D1/24-501
-f------ap-g---kf-sa------whasn------piw---------s
enrt----i----ink--------crvppvlqev----------------
----hstsnys-------------eyge----yle------cv---apvy
------l----t---kv-acqiptplvfekdlnc--kkyhkcf-vchyhs
pqrkpq--am-------p----g---haytikkqv--p-nf---------
-------sekmv--g----kckflassav----------------hkcnn
sdkkfp-kpffqsr-yls-lk-------------tlrl--------ae--
------sgk---cv----sq-nhwd-gged---fv------y--htsqld
--ilge----------sl--hap--igpk------f------lftissty
snskttvlakigkstf----------wqeslsep-n----kf--------
------------e--t-vl-kryn------g-vtclh--laesied--k-
------tgvipea-------------------kkpscstlrwksshpesh
drggmeraiiq-g-v-ncq-l--esl--qkv-hdnlreqnsdl-aktvsd
ttf----k--k------l---------gfppghi------------h---
-----nknthylepqfgsvd-------m---qnfr--tivd----svael
flayteas----sfgesltggqthgrs---lvggady--gd--al-----
p------eltktganls---vtsimav--k------sdp---cvd---ga
gl----n-------------khhage----rpaeky-i-gf---r----i
eharq-p-----f--sdepspdaltsneafdq--------liidsmelfg
gcnst----------e--gd-ilsvaaehgsegpslhti
>ENV_HV2D2/24-513
-i------ap-g--laf-rg------thqgp------pfw---------s
dhre----c----rhk---k----cr-apllrqv----------------
----hmpsffc-------------aygq----yle------cv---apvy
----------------t-ecqnpftlvfekdvtc--klyhk-----hy--
-----n--at-------p----g---lsyki--------nf---------
-------gskms--g----k-------sv----------------hncnn
aikkfahkpffqtk-yls-pkk-enl--gsesa-tvrvldswyqgqqdgq
qgsavvtlk---ck----kl-newd-gsed---fp------y--hkpeld
--ilgs----------il--lsp--igpn---ik-f------lf----ty
snsrctvagqig--sl----------weeslshg-i----rf--------
------------e--a-vl-ssfn------g-agclh--laegndd----
------tvvtpha----------------fhvkkglyselrwgsph---h
enggv-rn-vq-g-i-nhq-l--dki--eatlhdhlrk----lsa-----
-sf----k--q------i---------afgpahfdhnl-------vq---
--rptekhtfylqp-----e-------m---esfk--lrvdhvsrtppti
yla-ge-s----tlgqniargephasq---lvggddy--ad--al-----
k------nltdtganhs---va---rv--d------sni---hiegsfra
ka----ns---------e-srhlqte----rvaqrs-i-afdsnw--tvi
dhare-p-----y--snqpgtdylpaaeagdq--------avfdtmemfg
---------------------------dhgtg-pglqqf
>ENV_SIVM1/24-528
-f------aa-a--laf-sg------geqns------pgw---------s
dfre----c----ihkccak----cr-apvleev----------------
----ssssfye-------------eygq----yne------cv---stvy
dqgrcgl----s---kv-ecqptftlvfdksvtc--kayhk-ffvchyhg
pqrkq------------h----g---aaynikkqt--prnf---------
-------sakmv--g----r-------sv----------------hnchs
ftkkfaekhffa-r-yla-vkk-qnv--ngetg-tlrmq-nwylakse--
------tlk---cv----ka-nswn-nsedvwtfv------y--hksqlg
--ilgg----------vl--laa--espt---ik-f------lf----t-
------lsgeigkacf----------weeslshp-n----wf--------
------------n--t-vl-kaff------g-itclh--laegaed--k-
------tavipeaag--------nglfgyftv----fseirwgsphpedh
dpkglaraiie-a-i-dcp-l--nsm--eetghs--------l-m-----
-sf----k--p------l---------gfgpghfgpal-------ghklg
-----dncnfylgp-----n-------k---erfk--livd----qppnl
ylayaeas----rlgenltpaqphakn---lisganf--ns--av-----
k------eltrt--gla---lt---ag--k------tdp---hvqghfkl
kl----cr---------e-nqdnades----pee-f-p-gf---w--avi
ehare-pdpaisf--cnephsdslplqee------------ifetm---g
gcnap----------d--ad-ilkvapedgee-pslqqf
>ENV_SIVGB/47-569
vfiaqellaryhas----------lg----krdthgl--rtg------nt
a--a----c----frtlhiw--------qnl--vs--csqpnlalghveg
edfsndh--prlk----i-kl---lfkqskdllps------cfntasvdv
------p----ggkksysecafkasfiln---dlps--------------
-----ecptt---iyygqeclv-----cyvaaadgkp---f-hswefleg
ddasckk----k--d----l-------fl---igtvskncgqlrqlk-s-
----------------dk-vads--gsalgrdt-y--------dasee--
------evt---cf----cd-enwif------------------qqarve
h-taagy-remtgqpkp---gerqkpmvq--t------svhpry----d-
------lnvnvggrvythttlnvretwlvalnhytn----d-psktiams
ndkelksrtvqga--k-aqf---y-gaqts--yl-ltrherr------kv
lyvlev-ksknpqaspgyacqkl----------rh----wdwgtp--hld
--q-lrmgidq-gtf-pvvllqhthg--pqntn---------l-m-----
-iy----tfnhqq---tltiksspnih---sa----------------t-
gp---------pw---------------yvd--------fa----klt--
-v------------carlnkc-----d-----vs-ki--yq--kgwkkdv
-----------d--lshktfes---vvdql------t--------vleva
sl----ck---------yskp-e--h----m--egyqn-ml---k-atlf
dpspvsp-----vay-------t--lq-lv-p-----flngvimtqerys
t----ckpkgky--qg--kd-lfa-ea---------kqf
>ENV_SIVV1/24-538
-f------ft-r--gty-aghntevs-----------qtwiy-----dia
e--k----cveegiqagvns----cr-avilv-aavvctq----------
----ktqwflnlqsegnleyvvpakyst----ypd------cp---ptvl
------isg-hk---nitecqprfaik-e---yi--nqc-a-y-lc----
------cret---tyf------g---pntsipkpv--p-kfi--------
-------sekmi--ngfvgr-------pl----------------hmcaq
l--------litvraypggidmh--r--lapagen--------mdsge--
------tlsprtca----i-rkmw--gagn---yelgvslsyldhhaq-e
aq---sdgdnd-dgg--m--lgreaevcepn-vdsfnea----n------
------hrgdikksny----------wlksttyp-g----q---------
------------d--t-tl-kgf----r--ghksclr--vdg----taa-
------tr---nlage-------tgmfayegvqrslygkf----phpgst
--kalr-hige-a-m-dcp-l--eal--dnyldq--------l-m-----
-sf----tvarknffeg-----------mggagesgnl-----tmghv--
-----------py------------------dhfk--lifp----aesne
fvaya--------fsmapdql-peftd-----va-qn--ydmieq-----
q------nktls---------------dnnkketssphp---hikdlkin
al----ak---------qnsa-i--i----q--qgy-gfai---r-lgv-
-gpvk-k-----lsf-------g--gnvtaqhteflk---lvfkvmelfg
qc-kvy-cq--eth-mylqe-iin-as---------hhf
>ENV_HV2BE/24-510
-f------ap-g---tf-qn---------an------pfw---------n
elrt----c----ihq---k----cr-a-vlqqv----------------
----hsstiyt-------------dyge----yle------c-----pvy
------l----t---qn-aseapgtmvfekdvhc--kkyhk---vc---s
pqrkpq--sm-------p----ggkahaysikkqp----nf---------
-------sakmv--g----ncrflaqfpv----------------hkcnn
adkk----pffqsr-yla-lk-------------alrl--------v---
--------k---cv----kq-hnwd-sged---fv------y--htaql-
--------------------lap--igpd---lt-f------lftiksty
sds--nalgeiakssf----------wqedlaqp-n----kf--------
------------e--t-al-kktn------g-isclq--liecied--n-
------tavapea-------------------kkplyselswkaphpee-
---gverqiiq-g-i-nce--------------dnlre----l-a-----
-tl----k--k---------------------------------------
------kstfylel-----e-------m---qnfk--livd----svadl
flaytetsspgdshgedltggqptsrstkshvgvadr--ge--al-----
k------eltdttlsli---fh---gv--r------snpnqrnidghfqa
plcpktss---------a-nkhhagk----rpaany-r-gf---w--pvi
ehprk-g-----f--ppepgteslassedfdq--------lifdamdlfg
ncsak----------n--dd-vlsvapehaye-hslgti
>node11
-f------ap-g---af-sg------shann------pfw---------s
elrt----c----ihk---k----cr-apvlqqv----------------
----hsstfys-------------eygq----yle------cv---apvy
------l----t---kv-acqppttlvfekdvnc--kayhkcf-vchyhs
pqrkpq--am-------p----g---haynikkqp--p-nf---------
-------sakmv--g----k-------sv----------------hkcnn
atkkfa-kpffqsr-yla-vkk----------g-tlrlq-dwyqpead--
------tgk---cv----kq-nnwd-gged---fv------y--htsqld
--ilgs----------tl--lap--igpn---ik-f------lfsktsty
snsrttvsgeigkssf----------wqeslshp-n----rf--------
------------e--t-vl-kpyn------g-vtclh--laegied--n-
------tavtpea----------------fdvkkglyselrwksphpeeh
drggveraiiq-g-i-ncq-l--dkl--ekt-hdnlre----l-a-----
-tf----k--k------l---------gfgpghfdpnt-------vh---
-----dkntfylep-----d-------m---qnfk--livd----svadl
ylayteas----sfgenltggqphars---lvggady--ge--al-----
k------eltktgasls---vt---av--k------sdp---hvdghfra
gl----ns---------e-skhhage----rpaeky-i-gf---w--avi
eharq-p-----f--sdepgtdslpsqeaadq--------lifdtmelfg
gcnan----------d--dd-vlsvaaehgde-pslqti
>node18
-f------ap-g---af-sg------shann------pfw---------s
elrt----c----ihk---k----cr-apvlqqv----------------
----hsstfys-------------eygq----yle------cv---apvy
------l----t---kv-acqtpttlvfekdvnc--kayhkcf-vchyhs
pqrkpq--am-------p----g---haynikkqp--p-nf---------
-------sakmv--g----k-------sv----------------hkcnn
adkkfa-kpffqsr-yla-vkk----------g-tlrlq-dwyqpead--
------tgk---cv----kq-nnwd-gged---fv------y--htsqld
--ilgs----------tl--lap--igpn---ik-f------lfskssty
snsrttvsgeigkssf----------wqeslshp-n----rf--------
------------e--t-vl-kpyn------g-vtclh--laegied--n-
------tavtpea----------------fdvkkglyselrwksphpeeh
drggveraiiq-g-i-ncq-l--dkl--ekt-hdnlre----l-a-----
-tf----k--k------l---------gfppghfdpna-------vh---
-----dkntfylep-----d-------m---qnfk--livd----svadl
flayteas----sfgenltggqphars---lvggady--ge--al-----
k------eltktgasls---vt---av--k------sdp---hvdghfra
gl----ns---------e-skhhage----rpaeky-i-gf---w--avi
eharq-p-----f--sdepgtdslpsqeaadq--------lifdtmelfg
gcnan----------d--dd-vlsvaaehgde-pslqti
>ENV_HV2CA/25-512
-f------ap-g---af----------hasn------pfw---------s
elrt----c----ihk---a----cs-aevlqqv----------------
----hdsnfyq-------------eytq----yle------ci---aevy
------l----t---kv-acstplklvsekdvnc--kayhkcf-ichyhs
pqiknq--gvdst----------------sikkqp--p-nf---------
-------sakmv--g----k-------gvrdp-------------hk---
-dkkfa-kpffq---yls-vtk----------r-tlrlq-dwyqpead--
------tad---cvgpqakq-nnwd-g-------v------y--htsqld
--ilgs----------al--lap--cghn---ik-f------lftlnpty
stkrttvggeitkssf----------whaslsha-n----rf--------
------------e--trvi-kpyn------g-ttclh--ltdg--d--n-
------tavtata----------------fdikralyqelr---------
-------aivq-g-i-tcq-l--tkl--lsg-rdnlrd----l-a-----
-tf----k--g------l---------gfppghfdpni-------tq---
-----dksthylea-----ncglsmtam---qnfk---ive----pvadl
-iayseas----sfghsatggqphars---lvggany--gd--pl-----
k------qlsgtgasls---------v--k------sdp---hvdgyfra
gp----kl---------n-------e----rpaeky-i-gf---we-avi
ehgrq-p-----y--sdspgteclpsrivad------------dtmslfk
gcnan----------d--dkkiltgagehvdn-hcleti
>node9
-f------ap-g--laf-sg------ghqns------pgw---------s
efre----c----ihkccak----cr-apvldqv----------------
----hsssfye-------------eygq----yne------cv---stvy
------l----t---ki-ecqptftlvfdkgvtc--kayhk-f-vchyhs
pqrkpd--at-------p----g---aaynikkqs--p-nf---------
-------sakmv--g----k-------sv----------------hnchn
ftkkfaekpffasr-yla-vkk-qnv--ggetg-tlrlq-nwylpese--
------tlk---cv----ka-nswd-gsed---fv------y--hksqld
--ilgs----------il--lap--egpn---ik-f------lf----t-
------lsgeigkssf----------wqeslshp-n----rf--------
------------d--t-vl-kaff------g-itclh--ladgaed--n-
------tavipkaag--------nglfgyfnvkkglyselrwgsphpeeh
drkgvaraiie-g-i-dcp-l--dsm--eetlhe--------l-m-----
-sf----k--e------l---------gfgpghfdpsl-------ghklg
-----dncnfylgp-----n-------m---ehfk--livd----qppnl
ylayaeas----sfgenltsgqphars---lvagany--ge--al-----
k------eltrt--sla---lt---av--k------tdp---hvnghfrl
kl----np---------e-nqdhaae----qpaenf-s-gf---w--avi
ehare-p-----f--cdepgsdslplqeaadp--------aifdtmelfg
gcnkn----------d--pd-vlkvapedgde-pslqqf
>node10
-f------ap-g--laf-sg------thqnn------pfw---------s
elre----c----ihk---k----cr-apvlqqv----------------
----hsssfys-------------eygq----yle------cv---apvy
------l----t---ki-ecqppftlvfekdvtc--kayhkcf-vchyhs
pqrkpd--at-------p----g---haynikkqp--p-nf---------
-------sakmv--g----k-------sv----------------hncnn
atkkfaekpffqsr-yla-vkk-qnv--ggetg-tlrlq-nwyqpeae--
------tlk---cv----ka-nnwd-gsed---fv------y--hksqld
--ilgs----------il--lap--igpn---ik-f------lf----ty
snsrttvsgeigkssf----------wqeslshp-n----rf--------
------------e--t-vl-kpfn------g-vtclh--ladgned--n-
------tavtpea----------------fnvkkglyselrwgsphpeeh
drggveraiiq-g-i-ncq-l--dkm--eetlhdhlrd----l-a-----
-sf----k--q------l---------gfgpghfdpnl-------vh---
-----dkhtfylep-----d-------m---enfk--livd----sppnl
ylayaeas----sfgenltggqphars---lvggady--ge--al-----
k------eltktgasls---vt---av--k------sdp---hvdghfra
kl----ns---------e-skhhaae----rpaeny-i-gf---w--avi
eharq-p-----f--sdepgtdslpsqeaadp--------aifdtmelfg
gcnan----------d--dd-vlsvaaehgde-pslqqf
>node7
-f------ft-h--tty-agrssvvg----s------qgwfy-----nit
e--e----c----fqagckt----cr-aavlv-at--cth----------
----qtqlflnlqalgnlayivpspysa----ypd------cp---ptvl
------lag-qs---ninecqprftikfd---tl--kqc-k-f-lcqytt
-----dchet---tyyqv----g---acysiqkpi--p-kf---------
-------sakmi--n----r-------pl----------------hmcae
l--------likvrayrs-iskq--v--laqig-y--------lnsge--
------tlk---cv----nhqnpwh-gpgd---fv------y--hqaqle
aqkvgsngknd-egg--i--lgrerevae---ve-fqessdgrq----s-
------hrgdvsksny----------wlestahp-n----h---------
------------e--t-tl-ktfylsts--g-kaclr--ldg------s-
------traypkmsgg-------aamfdyagiqrelygkw----phpass
--kalrrhiae-a-m-dcp-l--qam--ddylde--------l-m-----
-sf----kvaqknffea-----------gggqdaipkl-------ghq--
-----------py------------------qhfk--lifp----aesne
fvaya--------fgtshdhsapettt-----va-qy--yd--kl-----
r------nktst--sma---------vdnk------pnp---hvknlkrn
al----gn---------qdkg-q--i----q--qgy-gfgi---w-lavi
esppk-m-----lsf-------g--gdgtaqh--------fvfiamelfg
ec-mey-cq--i--ee--qe-iik-as---------hhf
>node17
-f------ap-g---af-sg------shann------pfw---------s
elrt----c----ihk---k----cn-apvlqqv----------------
----hsstfys-------------eygq----yle------ci---apvy
------l----t---kv-acqtpttlvfekdvnc--kayhkcf-vchyhs
pqrkpq--am-------p----g---haynikkqp--p-nf---------
-------sakmv--g----k-------sv----------------hkcnn
adkkfa-kpffqsr-yla-vkk----------g-tlrlq-dwyqpead--
------tgk---cv----kq-nnwd-gged---fv------y--htsqld
--ilgs----------sl--lap--igpn---ik-f------lftlssty
snsrttvggeigkssf----------wqeslshp-n----rf--------
------------e--t-vv-kpyn------g-vtclh--ladgiqd--n-
------tavtpea----------------fdvkkglyselrwksphpeeh
drggveraiiq-g-i-ncq-l--dkl--ekt-hdnlre----l-a-----
-tf----k--k------l---------gfppghfdpna-------vh---
-----dkntfylep-----d-------m---qnfk--livd----svadl
flayteas----sfgesltggqphars---lvggady--ge--al-----
k------eltktgasls---it---tv--k------sdp---hvdghfra
gl----ns---------e-skhhage----rpaeky-i-gf---w--avi
eharq-p-----f--sdspgtdslpsqeaadq--------lifdtmalfg
gcnan----------d--dd-vlsvaaehgde-pslqti
