>ENV_SIVGB/47-569
ghh--r-------------aqvvelp-----------mak--l----e-d
dsew---vpck-----sqa---et-----------gcl--------l--g
ka-gvenlpnvck-sv-r-----------lswafcckgdpeafdkvdshy
gkvdsgv--------sdqppc---dagla------------y--------
----d-ceq--vvankqhsqh------lhdarvpgpga--avp-----fg
rl-----------esrlpltgsnspatklanstp-----esc------vn
lg------------------------dnelrls---fq--------rkfi
s-vrgkktslvltgll----------------ailgk-----iaakdki-
asgigggcd------g---t-p--------p-klctpvltdws----vgq
ghyaiggilvhspffnpags-------p----sgivsegdte-rfkl---
-slyqe-----agrydinpnhl-------------arkkf-sfldapaat
kneflka-----------------af----sftqtk-lvgt---g----l
a-----fgpaaiiepvdmcpkagl-aell---gn--------sefgaq-y
vlisg----vldagm-------dasapftsvtvep---as---kpkasse
gn-pf-------kvpgkgle-asseaivpsas-si---h----nnd----
----dtclkqgtfqfkvkl-------div---fv-w--itf-a---nrft
tteftshdvflagerilwdwkl---nyhaqsd------g-ledcps----
----nsne---------p----rte-lqscq-----------qkmacts-
-ksriiieyli-iqf-lysssyydageqsalnlqaqvntq------d---
-yeksnc-c--t---------vq--gylgtkiwc----------iaahhg
--i-w-----tlv-----s-qs---------ygqiie-le
>node18
---cdg-------ysgqmnkl--shkyd---kf---alg-gvp----g-i
vrkd-------------av---ankkhtg--f-rephi--------k-cq
vf-ak----fpki---ak--vs---ekakigs---a--------------
-nhp--sdr-vtgqegnstgc--vel---v------ntsaaaetgy----
----a-vqehls---------------dnenkfsqlgvknsrcgvdawft
leg----p-glvyh-------------------g------ac--------
rg------dvrg--------------amvlqy-dvlcravha-qkphkhv
d-a-----c-----vll-----cvmgt-----af-grsp---kynkkkt-
----descd------skgnylvagegetndphg--ksvvvnwt----q--
----dtgs----s---vp----skklnf------------------d-np
lgyg-glfl--a----tna--idr-----------rtpal-ea---itts
kahlwn-ar-dkqfylgd----a-af--aqhi--dp-v-dahpqa----a
patasrvkq----------g-----ghct---elkl------v----r-f
glvaa----i-----alsh-psd---------------tv--deqge---
--sprr-q-ynikinnqsvi-sg----------rf---ikpfggya----
iq--l-c------------p------e-k--pwvqv--hkd-tnlwrk--
-a-----------qdvlwnwk--igalp--er------epn----l----
----eqisgcfia----t----d--kl----mat----kkfae---cgth
gkaslklqeifnvaf-ayist--lrgq--g----------spnlvkg---
--qalsc-cngqask----yick----------cc---------tga-sq
--g-r-----sig-----i-gll--ag----ygalfq-v-
>node9
---cdg-------ykghmqkl--nhkyd---ky---tlg-gvp----s-v
vrkd-------------at---ankkhtg--f-tdphe--------k-cq
af-ak----fpki---ak--cs---nsakigs---p--------------
-ahp--idr-vtgqegkstgc--pdl---v------gsnavaqagy----
----e-vqehls---------------dnehkfsqlgvknsrcgadawfk
lvg----pealvyh-------------------g------ac--------
rg------gvrg--------------nmvlqy-dvlckavha-kkphkfv
d-a-----a-----vl----------------tf-grsr---kynkkkt-
----eqscd------a---ylv--------phg--ksivvnwt----h--
----dtgs----g---ap----akglnf------------------d-np
lgyglvvfl--a----tna--idk-----------rtpal-qa---ista
kahlwn-ar-viqyywad----a-af--aqhi--kp-v-dahpqa----a
p-----vkq----------g---l-ghci---dlkl------h----r-f
glvat----i-----elih-psd---------------sv--dekge---
--sprr-q-lnikinnksvi-se----------rf---ikpfggys----
ie--l-cvkevktp--cknp------e-k--pwvhv--gtd-tdlwrn--
-a-----------kdvlwkwk--igalp--es------epn----l----
----eqisgcflg----t----n--kl----lat----kkfte---cath
gkaqlklqeifnvef-ayist--lraq--gkt----vy--tprlvkg---
--qglsc-cnnqask----ylck----------cc---------vgg-sq
--g-r-----sig-----i-vtlvlag----ygalfq-v-
>ENV_SIVG1/22-522
ikg--n-------------lf--klale---ry-k-mlg-all----e-g
qllh---gp-rkeppnnv-gyfgkrhlcllsy-teppd--------m-fg
kf-ay----fedh---tr-----------lvt---k--------------
-giv--vgv-s--hgektaga---qaaagi-----------g--------
---ad-v----g--------k------dtdvkvkgdsladgis-----yk
mvgk--q-----ygre-evp------------qp------ps--------
gg------------------------nmdley-aplcka----shrrkn-
k-rktt--g-----vl-------------------gk-----rypkdkm-
----prgce------g---yle--------pqgacrslrtawn----y--
----dsga----g---atgtpgkknmhf----dgtde--pgaqrfpa-gt
ldlgfivglpta----ik---i-------------erpdl-qt---gekd
kelqwa-kl-v--y-ynp----a-vy--aecfskhsgv-gfqpla----a
p-----gsqv---------h---l-ehvr---el--------a----dty
lvgpg----s-----glmy-psd----y-------lnapf--eeste---
--dpkrvq-vivaiypktti-sd----------ef---tkpfavfsgngn
imsalkclkdv-hgrkgnlppel---eek---wi-g--svd-s---rntn
are-gp-ddfssgkevawswkl-itdlc--dk------d-s----v----
----g-fqncfmlnnfis----h--dm----let----kkldkwvvcst-
-kgklkqqytr--afllytsn--qsts--tlt----ts--k-vlvgg---
--ngnncsc--d-------hlce----------cc---------lgssan
--gfw-----qiv-----c-vtlkrge----yadtfd-lv
>ENV_HV2D2/24-513
---cdg-------yqgqmykt--nkkyn---ky---tvg-gvl----g-v
yrve-------------av---tnkkqng--f-aephs--------k-cp
lf-ag----fpki---pr--cg---ekpnivt---s--------------
-ghp--snr-vsgqqgnntgc-tvnl---v------gsnfvgttgy----
----e-aedhlp---------------edqhnfskwgp-nsrcgvkaffd
llg----reylvy---------------------------ac--------
rq------evrg--kvakavteqgvatmvlqy-qilcra--plknahkhv
k-a-----c-----vlnreipdcmsgi-----af-gfsrkae-ynkkki-
----lepcd------tsgnylv--------pqg--ksavvnwt----q--
----dsgt----g---ap----anrltf------------------n-ng
lgyk-avfl-------------dr-----------rtpalaea---vsat
kshlwn-ak-vkqfylgd----awaltcanhi--dp-i-eahpqaldsad
p-----vkq-------------------t---elkl------y----r-y
gavgmrvail-----alfh-tsd---------------tv--dkkge---
--sprr-a-ldiminnkavvfdg---------vrf---iksfgaya----
le--l-cvkevktp--ckep------e-g-i--vhv--gnd-tglwrn--
-g-----------kevlwkwk--igllp--erakntesehn----l----
----eaisacfvg----s----a--kl----liv----rkfad---vatr
eklqlrleatfnitf-vfisd--lrsq--gda----qa--tpslpkg---
--dalnc-clgqask----ylcq----------cckaecnfhykang-sd
rfg-r-----saa-------dtc--ag----yyqlfq-v-
>node14
---cdg-------ysgqmnkl--shkyd---kf---slg-gvp----g-i
vrkd-------------av---ankkhtg--f-rephi--------k-cq
vf-at----fpki---ak--vs---ekakigs---a--------------
-nqp--sdr-vtgqqgnstgs--vel---v------ntsaaaetgy----
----a-vqehls---------------dnenkfsqlgvknsrcgvdawft
leg----p-glvyh-------------------g------ac--------
rg------dvrg--------------amvlqy-dvlcravhc-qkphkhv
d-a-----c-----vll-----cvmgt-----af-grsp---kynkkkt-
----descd------skgnylvagegetndphg--ksvvvnwt----q--
----dtgs----s---vp----skklnf------------------d-np
lgyg-glfl--a----tna--idr-----------rtpal-ea---itts
kahlwn-ar-dkhfylgd----a-af--aqhi--dp-v-dahpqa----a
patasrvkq----------g-----ghct---elkl------v----r-f
glvaa----i-----slsh-psd---------------tvgsdeqge---
--sprr-q-ynikinnqsvi-sg----------rf---fkpfgnya----
iq--l-c------------p------n-k--pwvqv--hkd-tnlwrk--
-e-----------qevlwnwk--igalp--er------epn----l----
----eqisgcfva----t----d--kl----mat----kkfae---cgth
ggaslklqeifnvaf-vyist--lrgq--g----------spnlvkg---
--qalec-cdgqask----yickgg--------cc---------dga-sq
--g-r-----dig-----i-gll--eg----ygalfq-a-
>node11
---cdg-------ysgqmnkl--shkyd---kf---alg-gvp----g-i
vrkd-------------av---ankkhtg--f-rephi--------k-cq
vf-ak----fpki---ak--cs---ekakigs---a--------------
-nhp--sdr-vtgqegnstgc--vel---v------nssaaaetgy----
----a-vqehls---------------dnenkfsqlgvknsrcgvdawft
leg----p-glvyh-------------------g------ac--------
rg------dvrg--------------nmvlqy-dvlcravha-qkphkhv
d-a-----c-----vll-----cvmgt-----af-grsp---kynkkkt-
----eescd------ssgnylv--------phg--ksvvvnwt----q--
----dtgs----g---vp----skklnf------------------d-np
lgyg-glfl--a----tna--idr-----------rtpal-ea---itts
kahlwn-ar-gkqfylgd----a-af--aqhi--dp-v-dahpqa----a
patasrvkq----------g-----ghct---elkl------v----r-f
glvaa----i-----alsh-psd---------------tv--deqge---
--sprr-e-ynikinnqsvi-sg----------rf---ikpfggya----
iq--l-cvkevktp--ckdp------e-k--pwvqv--hnd-telwrk--
-a-----------kdvlwkwk--igalp--er------epn----l----
----eqisgcfia----t----d--kl----mat----kkfae---cgth
gkaslklqeifnvaf-ayist--lrgq--gkn----vy--spnlvkg---
--qalsc-cngqask----yick----------cc---------tga-sq
--g-r-----sig-----i-gll--ag----ygalfq-v-
>ENV_HV2CA/25-512
---ckk-------ysnqmnkl--shkyd---ky---alg-gip----e-i
akkd-------------ii---ankkhsd--f-rdshv--------k-sd
vf-ak----fp--------------------s---a--------------
-nlp--sqrl--gqepnssgsv-vel---v-----------adtvy----
----advaehln---------------nnenrfsqqglmasrssvdallt
lkg----p-glvyh-------------------g------ac--------
rg------evrg--------------alvlqn-dvlcravha-qkphkhv
d-a-----c-----ill-----cvlgspragkaf-grsp---kyfkkkt-
----descdslckplskgnylvageaetndphs--ktvvvdwm----q--
----dvgs----s---va----skkldf------------------d-np
lgyg-glfl--a----tnp--idr-----------rtqal-et---iams
kahlwn-ar-dkkffqgd----a-af--keht--dp-v-dlhlqa----a
sptpnkfrq----------g-----ghct---elkl------v----r-f
gltap----d-----alghtpsd---------------tv--deege---
--nprr-q-yaikiendaai-ag----------rf---iegfgsya----
iq--l-c-------------------q-k--pwvqv--hke-tnlwrk--
-a-----------qdvwwnwn--igalt--er------epn----l----
----eqisncfie----tlytvd--kl----m-------kfae---csth
gkaylplhqvfnvaf-ayist--lrgh--g----------tpglvkg---
--qalac-angqtsk----ficq----------cc---------tga-sq
--g-r-----dhg-----i-g-----g----ygalfq-v-
>ENV_HV2D1/24-501
---cdgqrhwlnqysgqmnkl--shpyd---kf---slg-gvp----g-i
vrkd-------------at---s----sg--fprephv--------k-cq
vf-at----fpkv---ak--v-----kamigs---a--------------
-nqp--str-vtgqqtnstgs--vel---v------nt---aetgy----
----a-vqqnls---------------dnevkgsqqgvknsrtnvdswyt
leg----p-glvyh-------------------g------ec--------
rg------dvrgkh------------ptvley-gvlcwavhc-kkpeshv
d-a-----c-----vgl-----cvmgs-----ay-grtp---kyhkkktg
----descd------skgnylhagegetanlyg--kgvvvnwg----q--
----etgk----c---vp----skklnfeekl--------------dinp
lgyg-glfl--a----tna--idr-----------rtptl-qa---yvts
nahlwn-ar-dnhfylgd----a-sf--aqhi--qp-v-dahpqa----t
patvsrvrq----------g-----ghca---elk-------v----r-f
glvaa----i-----s------d---------------avgsdetge---
--sppr-q-ysiklnnpsai-sg----------rf---fkpfgnya----
iq--l-c------------p------n-----wvlv--qtd-tn--rk--
-e-----------qevlwnwk--vgalp--e-------epn----l----
----eqinscfva----t----d--kp----matlaaekhfaq---cgth
dgsslk----------vyist--lrgq--g----------spnlvkg---
--halec-cdgqask----yickgg--------tc---------dga-sh
--v-s-----dtg-----f-gll--eg----ygalfs-a-
>node10
---cdg-------yqgqmnkl--nhkyd---ky---tlg-gvp----g-v
vrkd-------------av---ankkhtg--f-sdphi--------k-cq
lf-ak----fpki---ak--cs---ekakigs---a--------------
-nhp--sdr-vtgqegnstgc--vel---v------gsnaaaetgy----
----a-vqehls---------------dnehkfsqlgvknsrcgvdawft
lvg----pealvyh-------------------g------ac--------
rg------evrg--------------nmvlqy-dvlcravha-kkphkhv
d-a-----c-----vll-----cmmgt-----af-grsr---kynkkkt-
----eescd------asgnylv--------phg--ksvvvnwt----q--
----dtgs----g---ap----akklnf------------------d-np
lgyg-alfl--a----tna--idr-----------rtpal-ea---ista
kahlwn-ar-vkqfylgd----a-af--aqhi--dp-v-dahpqa----a
p-----vkq----------g-----ghct---dlkl------h----r-f
glvat----i-----alfh-psd---------------tv--dekge---
--sprr-e-lnikinnksvi-sg----------rf---ikpfggya----
iq--l-cvkevktp--ckdp------e-k--pwvhv--gnd-telwrk--
-a-----------kdvlwkwk--igalp--er------epn----l----
----eqisgcfla----t----d--kl----lat----kkfae---cath
gkaqlklqeifnvaf-ayist--lrgq--gkt----vy--spslvkg---
--qalsc-cngqask----ylck----------cc---------agg-sq
--g-r-----sig-----i-stl--ag----ygalfq-v-
>ENV_HV2G1/23-502
---cdg-------ypgqmnkl--shkfd---kf--ralg-gvpdqlpg-i
vqnd-------------av---ankrntg--f-qaphi--------k-cq
vf-gk----fpkv---dk--cp---ekkkigs---a--------------
-nhp--sdr-vtgqegnstgc--vel---v------nssatsetgy----
----g-vqehls---------------dneikfsrlgvknsrcgvdvwfs
leg----p-gviyn-------------------g------ac--------
rg------dvrg--------------nmvlky-dvlcvavha-qkphkhv
e-a-----c-----ill-----cimgt-----af-grsa---kynkkkt-
----eescd------stgnylv--------phg--ksvvvnwi----l--
----daas----g---vp----skklnf------------------d-np
lgyg-glfv--a----tda--idr-----------ktpal-ea---itts
kahlwn-ar-gkhfflgd----s-af--aqhi--dp-t-dahpqa----m
padssrvkp----------g-----gh------lkl------i----h-l
glvga----i-----alah-psn---------------tv--deqge---
--sprr-e-ygikinnqsvi-sg----------ri---ikpfggya----
ip--l-cvkevktp--cqdp------e-k--pwvqv--hne-telwrk--
-a-----------kdvlwkwk--igalp--dk------ppd----lggyv
lpkgeqisgcfia----t----d--kl----mnk----krfae---cgah
gkpslklqevfnvef-aylst--lrgq--gkn----ly--spnlvsa---
--qalsc-cngeask----yick----------cc---------tga-sh
--g-r-----sig-----a-gll--ad----ygalfl-v-
>ENV_SIVV1/24-538
ika--n-------------lf--klale----ytk-k-g-all----e-g
qlphsplnp-rtd-pnhv----gkrklcl--y-t------------tqyg
rf-y-------ah---tr-----------lvs---s--------------
------aai-a--asdratgs---qsslga-----------g----maig
slfed-vkk-----------k------gketnlkgdgvkgdrr-----ar
mvgnqa--------------------------------------------
-q------------------------kleldy-dqlckt----ahsawn-
nrkqqt--e---------------------------k-----rypkdkm-
----pktce------g---yln--------aagvcksir-aweqynhy--
----dsg-----a---taga-aggnmcf----dgtde--agg-kfs---t
vslgfivilptq----lqq--i--sehkakltgiydrpdl-di---gakd
knllpg-kg-v--y-yepgscdg-ay--akrftkdtkv-gaqpqa----a
p-----gapcai---ikacd---l-gqlr---dl--------a----aty
-vaag----v-----glmh-pse----y-------yyqpv--dnktd---
--sskrir-vrakiypkvfi-ep----------sf---ikpavvytvk--
im--lrclkgvefnrkatlp-eldtneqkt--wv-sdasvd-a-----kp
prp-ka-defvqgkqvpgswkl-vantc-----------------s----
----aapqksflg---------h--dm----lae----k-lenrpqhna-
-kpklteqypy--afllytqn--qstg--nmk----sd--i-vlvggaea
t---knchc--s-------hlce----------cc---------mggsnk
--gfn-----givetrla--vslekpskkdvyaqsfd-lv
>node7
ikg--n-------------lf--klale---ky-k-mlg-all----e-g
qllh---gp-rkdppnnv----gkrklcl--y-teppd--------m-yg
rf-at----fdnh---tr-----------lvs---s--------------
-glv--vav-a--hsekvtga---qaslgv-----------g----faig
slfed-vkdhls--------k------dkdtklkgdsvkdgrs-----yk
mvgk--q-----ygrq-evs------------qp------pc--------
qg------------------------nmeley-dplcka----shrskn-
t-rktt--g-----vl----------------le-ge-----rypkdkm-
----pkgce------g---ylv--------pqgacksirtawn----y--
----dsga----g---atgapgkkdmsf----dgtde--agaqrfsm-gt
mdlgfivivptt----lqa--i-------------drpdl-qt---gekd
kellwn-kv-v--y-ydp----a-ay--aerfskhsrv-gtqpla----a
p-----gnqtai---irvcn---l-ghvr---el--------a----ety
lvgpg----a-----glmh-psd----y-------lyqpv--ddrtn---
--dpkriq-vrvkiypktii-se----------df---vkpftvfsvn--
im--lkclkevsnnrkgtlptel---eek---wi-s--svd-s---rntn
are-gp-ddfvsgkevpwswkl-vtdlc--ek------q-s----v----
----eafqncfmgsdfip----h--dm----lat----kkletwvacnt-
-kaklkqqyty--qfllytsn--qsts--tmt----an--m-vlvgg---
--ngnncsc--d-------hlce----------cc---------mggsan
--gfw-----qiv-----c-vtlekge----yaetfd-lv
>ENV_HV2NZ/24-502
---cdg-------ysgqmnkl--ahkyd---kf---alg-gap----g-i
arkg-------------il---spkshsg--y-rephigrrre---k-cq
af-tk----fp--------------------s---a--------------
-nhp--sqrlitgqegestgc--vey---v------ttsskadagy----
----a-vskhlg---------------dnenrgskmglknsrcgvedwft
leg----p-gavfh-------------------g------ac--------
kgkfnsscdvrg--------------llilqy-etlcravha-qkaskhv
d-a-----c-----vll-----cvigt-----af-grsp---synkkks-
----aescn------sqgdylvagegetndphd--ktvvvkwl----q--
----ntas----d---vs----skklnf------------------e-np
vgyg-glff--a----sna--iar-----------rrpsl-qa---vatg
kahlws-araekkfklge----a-af--aqhi--ep-v-darpqa----v
patanrvke----------g-----ghcntsvalnlllllsqv----r-f
glvga----i-----alsh-esq---------------av--deqge---
--npkr-q-yalkidsdsvv-ag----------rf---irgfggss----
dq--l-c-------------------q-k--pwiqv--hkerttlwrk--
-a-----------qkslwnws--iagqk--er------dpn----l----
----ekisgclia----s----e--km----mpt----ykfae---cgth
gktslklqevfdval-lyvts--lrgt--g----------spglvkg---
--ealsc-cnghass----y-ck----------cc---------tga-te
--g-rdhttsshg-----f-gll--ag----ygalfq-v-
>node19
---cdg-------ysgqmnkl--shkyd---kf---alg-gvp----g-i
vrkd-------------av---ankkhtg--f-rephi--------k-cq
vf-ak----fpki---ak--vs---ekakigs---a--------------
-nhp--sdr-vtgqegnstgc--vel---v------nssaaaetgy----
----a-vqehls---------------dnenkfsqlgvknsrcgvdawft
leg----p-glvyh-------------------g------ac--------
rg------dvrg--------------amvlqy-dvlcravha-qkphkhv
d-a-----c-----vll-----cvmgt-----af-grsp---kynkkkt-
----descd------ssgnylv--------phg--ksvvvnwt----q--
----dtgs----g---vp----skklnf------------------d-np
lgyg-glfl--a----tna--idr-----------rtpal-ea---itts
kahlwn-ar-dkqfylgd----a-af--aqhi--dp-v-dahpqa----a
patasrvkq----------g-----ghct---elkl------v----r-f
glvaa----i-----alsh-psd---------------tv--deqge---
--sprr-q-ynikinnqsvi-sg----------rf---ikpfggya----
iq--l-c------------p------e-k--pwvqv--hnd-telwrk--
-a-----------kdvlwnwk--igalp--er------epn----l----
----eqisgcfia----t----d--kl----mat----kkfae---cgth
gkaslklqeifnvaf-ayist--lrgq--g----------spnlvkg---
--qalsc-cngqask----yick----------cc---------tga-sq
--g-r-----sig-----i-gll--ag----ygalfq-v-
>node17
---cdg-------ysgqmnkl--shkyd---kf---alg-gvp----g-i
arkd-------------iv---ankkhsg--f-rephi--------k-cq
vf-ak----fp--------------------s---a--------------
-nhp--sqrlvtgqegnstgc--vel---v------ntsaaaetgy----
----a-vqehls---------------dnenrfsqmglknsrcgvdawft
leg----p-glvyh-------------------g------ac--------
rg------dvrg--------------alvlqy-dvlcravha-qkphkhv
d-a-----c-----vll-----cvmgt-----af-grsp---kynkkkt-
----descd------skgnylvagegetndphs--ktvvvnwm----q--
----dtgs----s---vp----skklnf------------------d-np
lgyg-glfl--a----tna--idr-----------rtpal-ea---iats
kahlwn-ar-ekkfylgd----a-af--aqhi--dp-v-dahpqa----a
patanrvkq----------g-----ghct---elkl------v----r-f
glvaa----i-----alsh-psd---------------tv--deqge---
--sprr-q-yaikinndsvi-ag----------rf---ikgfggya----
iq--l-c-------------------q-k--pwvqv--hkd-tnlwrk--
-a-----------qdvlwnwk--igalp--er------epn----l----
----eqisgcfia----t----d--kl----mat----ykfae---cgth
gkaslklqevfnvaf-ayist--lrgq--g----------spglvkg---
--qalsc-cngqask----yick----------cc---------tga-sq
--g-r-----shg-----i-gll--ag----ygalfq-v-
>node8
vkg--s-------------lf--klale---ky-k-mlg-alp----e-g
ellh---gp-r-----nvs---etrkhcv--f-teppd--------m-ig
rf-at----fedh---sr-----------lts---s--------------
-glv--val-i--hsdkstga---qaslgv-----------d--------
----d-ikehls--------n------dndtklngnsvkdgrs-----fk
vvgk--q-----yqrq-evs------------qp------ac--------
qg------------------------nmeldy-dplcka----thpskfv
t-rktt--g-----vl----------------ai-ge-----ryskdkm-
----qkgce------g---ylv--------phgecksvqtawn----y--
----dggt----g---aagapgkkgmnf----vgvke--agqvrfsm-dt
mglglvvflpts----lea--i-------------krpel-qa---aend
kahlwd-kq-v--y-wdp----a-ay--aerftkrp-v-gtspla----a
p-----vnepai---iricn---l-ghvi---dl--------a----e-f
vlvag----a-----glih-psd----y-------g-ppv--ddrtn---
--qpkriq-vhvkiypktii-sd----------qf---vkpfagystn--
if--lkclkevstnrkaklptel---evk---wv-a--gvd-s---rntn
are-gp-ddfvsgkdvlwswkl-vtdlc--en------e-d----l----
----eaiencflgnp--p----h--dl----lat----kkleervacat-
-kaklklqytf-mef-pytsa--qsas--tmt----an--mpalvgg---
--ngsnc-c--d-------hlcq----------cc---------mggpat
--g-w-----niv-----c-vtlvkad----ygeifq-lk
>ENV_HV2BE/24-510
---cdg-------ygg-mn----shkyd---kf---slg-a-p----g-f
irkd-------------a----ankkntv--f-rephi--------k-ck
lf-as----fpkia--akqriskgqekakigs---a--------------
-nqs--anr-vtgqikkstgs--vel---vglakaknssaaaea-y----
----a-gqeqls---------------dgenkfrqlgvkdsrcgvdawft
leg----p-glvyh-------------------skatlr-achlhdle--
kg------dvrs--------------vmvlqy-dvlcrathc-rkphkhv
d-g-----c-----vll-----cvmgt-----sf-grsp---kynkkkt-
----eescd------skgnylvagegetnsplg--rsvvvswt----q--
----gtga----k---vp---------f------------------e-np
lgyg-glil--a----sea--idr-----------ttsav-qa---ints
kahlwn-ar-dkhfylgn----s-af--gqhi--dp-a-dahpqt----k
pptasrvkq----------g-----ghct---elk-------v----r-f
glvas----i-----tlsh-pse---------------vvgsaeqve---
--svrr-p-ynikinnqsvi-sg----------rf---fkpfgdya----
iq--l-c------------p------h-s--awvqv--hkd-tnlwrk--
-e-----------qevlwnak--igalp--pr------qpn----i----
----eqisgcfva----t----g--kl----mtt----kkfae---cgth
vgeslkleeifnvam-vyvst--mraq--g----------gpnlvkg---
--qalqc-cdgqastfl--ficrgg--------cc---------dga-te
--g-r-----eig-----vsgli--dg----eealfq-a-
>ENV_SIVM1/24-528
---cdg-------ykghaqkv--thkydplakl---tls-gva----sak
vrkd-------------at---gnkkhng--y-sdphd-----aslk-cq
afeak----fpka---tk--cs---nsakiss---p--------------
-ghp--idh-vtgqegsstgc--ptl---v------gss---qagy----
----e-vqehls---------hsgsvfdnehkfselkiknsrcnadaffk
qvg----pealvyd-------------------g------ac--------
kg------gvrg--------------smvlqy-dglcksvss-krahkfv
d-a-----s-----vl----------------tf-gssr---eyskkkt-
----gqacs------a---ylv--------phg--ksivvlwt----h--
----dtgs----g---fs----akglnf------------------d-np
layalvifl--a----tga--idk-----------ktaaf-qa---ista
kahlwn-qr-vrqyywaf----a-nf--amhl--rp-l-dahpra----a
p-----vkq----------v---lqghci---dlkl------h----k-f
gmvat----i-----nlln-psd---------------sv--dekgq---
--sprr-kklnqkindlsvi-se----------rfkghikpfggys----
ie--l-cvkevktp--cknp------e-k--qwahv--vt----iwrn--
-a-----------kevawkwk-vigalp--dq------epk----l----
----eecsgcflg----t----n--kl----laa----kkfte---cath
g-----lqeifnvef-ayist--lraq--gkt----vy--tarlvkg---
--qglns-ctnqksk--sgylck----------cg---------vgg-tq
--a-r-----sig-----v-vtlvlpe----ygalfqai-
