>ENV_HV2D1/24-501
-sism----igkgntek----------gh---glavmvggmsc------g
svva-----------h-appkl-kvrg---------gsilfdlqa-----
lsd-s-----f--ddlqivlyhearddesdt-tqnnypqikk--pn-ivr
kpge--mfkfa-----sksklagpdyggvlskavg---------------
-k---q---gg---s-vsk-g-ip----f-l--t--------l-------
--------t---gg-----a--tfkwi------gvayy------ncrkvv
vm-------adgk--------vd----lfpl--h----p-----q--klp
--ndpsfeacvndfvrfg-ke--gv-vs----ypgnktseqhwqqr---v
--isqgepdgvk----kgeqdkverggradinne-gdeg-k-se------
--dgkp-----------------------fvalvpcpdhnvt--gdf-vl
g---pv-yqdreddp------------------cklwnkpvag-----da
---------------aedyfwpk-----------s-lv-nlyv-akalge
iyypn--hf-verh------------------vq-a----fwlkwlqdim
isqtqppa--epsyrlctktnrdg---fsl--nedl-----s--alktyn
rnyeivmcc----l--kl-q--p--s--fd----aah-atidpv---dp-
------------ll-----------s---------------------s--
n----qrlq-------in--ar-----------------cqetptti---
-e---------kigagv--r---aalnsa--pipveqakhmv---p----
------sc-----------------fadtd---------sg--------c
lfrtgkai-krgay--akifh-lka-laqki---earfdck-tpcm-gye
lf--lksn------------ayts-tasmd
>ENV_HV2CA/25-512
-siep----iqklaaak----------gh---plasqvg-----------
slvp-----------h-appdl-rvhg---------tavtfdl-------
--q-a-----f--d----vlyqqnrneqrns-tqkdypnark--in-fvr
kpge--sfkfa-----skv-------gagvsmqvd---------------
-k------------a-lsk-g-il----f-lygt--------v-------
--------ttpsgg-----k--afk-d------svsyykafdatdcrkai
ll-------asgk--------hnik--lfpllgh----p-----qcpklp
--sdphyhatvndavkye-kg--avgvs----ypgeisseev--sk---v
--isqkgang-----------kvekna----nse-gdea-k-sh------
--dgkp-----------------------flalvqspspgvs--tdf-tl
g---pi-yqdrekvp------------------cklwnkpvag-----da
---------------aqdyywpi-----------n-lvfnlfhtekatgd
vytpv--vi-verh------------------fk-a----lwl-------
------pa--ppgfplclkksrdg---fsld-ttal-----a--diktfn
kkyeivmct----l--kl-e--s--k--fa----aah-svntiv---gp-
------------ll-----------s---------------------s--
n----eqlq-------ih--ar-----------------cdetisti---
-k---------kvgggl--a---asl-----tirvaqakpmv---e----
------sc-----------------frdtdklndvtflksg--------c
tfr-l-ii-kpgcy--veilrglip-vaqki---earfdck-agcaegyd
lf--srgn------------afts-tgcmd
>ENV_HV2BE/24-510
-nlsp----ipkgnaer----------gy---alaemigglsc--h---d
stvp-----------h-ippnl-kvrg---------astvfdlqa-----
msd-a-----f--ddmtivlyqqardehtnt-tqnnypqakkghp----r
kpge--kfkfd-----sks-------ggglsirvg---------------
-k---t---gg---s-vsn-s-vs----f-l--t--------l-------
--------t---gg-----t--afkwdg-----gaayy------dcrkmv
vi-------iagktavgdgdlvn----lfpl--h----a-----q--d--
-----hfqacvkdivkfgekd--gv-va----ypgnksteeh--qr---q
--irkaepkggk----kgghsrvekng----nne-gdgapk-sq------
-----p-----------------------fiaavlcpspnvt--gdfktl
g---pi-yddrengp------------------cnlwnkpaag-----da
---------------aedyfwpi-----------s-li-hlyi-ekavee
iftpg--hi-verh------------------rd-a----fwlk-----m
-----ppa--spsfktclkksrdg---fkld-dssl-----n--siktfe
rkyenvmca----q--kq-q--p--n--fp----aah-avigsv---ep-
------------ll-----------l---------------------s--
a----qqlq-------vn--tr-----------------ctetitai---
-e---------kagggi--a---sal-----pvpvahakplv---e----
------sc-----------------fintdslnnitflksg--------c
ifr-gkai-rpgay--akffq-lka-vaqri---egrfdyk-agca-gyn
vf--lngt------------syp-----ld
>node11
-siep----iskgeaea----------gh---alaamvgglsc--h---g
avvp-----------h-appnl-kvqg---------aailfdlqa-----
msq-a-----f--ddltivlyqptrdehtnt-tqnnypqark--pn-i--
-pge--kfkfa-----ski-------ggglskavg---------------
-k---q---gg---s-isk-g-ip----f-l--t--------l-------
--------t---gg-----t--sfk-d------gvsyy------ncrkvv
vi-------angk--------vn----lfpl--h----p-----q--klp
--ndphfeacvndavkae-kd--gv-vs----ypgeksseeh--qr---v
--isqkeadgak----kslqnkvekng----dne-gdea-k-sq------
--dgkp-----------------------fialvqcpspnvt--gdf-vl
g---pi-yqgrdnvp------------------cklwnkpvag-----na
---------------aedyywpi-----------n-lv-nlyv-ekavge
iytps--hi-verh------------------iq-a----lwlk-----m
-----ppa--ppsfrlclkknrdg---fsld-nedl-----s--niktfn
rkyeivmca----l--kl-q--p--n--fp----aah-avitsv---ep-
------------ll-----------s---------------------s--
n----eqlq-------ih--ar-----------------cqgtitai---
-n---------kvgggv--a---aal-----pipvaqakpmv---e----
------sc-----------------fketdklnninflksg--------c
kfr-g-vi-rpgay--akifr-lka-vahki---earfdck-agca-gfd
lf--lkgniwglknsgpfmlayta-tacmd
>node18
-siep----iskgeaek----------gh---alaamvgglsc--h---g
avvp-----------h-appnl-kvqg---------asilfdlqa-----
msq-a-----f--ddltivlyqqtrdehtnt-tqnnypqark--pn-ivr
kpge--kfkfa-----ski-------ggglskavg---------------
-k---q---gg---s-isk-g-ip----f-l--t--------l-------
--------t---gg-----t--sfk-d------gvsyy------ncrkvv
vi-------angk--------vn----lfpl--h----p-----q--klp
--ndphfeacvndavkye-kd--gv-vs----ypgeksseeh--qr---v
--isqkeadgak----kglqnkvekng----nne-gdea-k-sq------
--dgkp-----------------------fialvqcpspnvt--gdf-vl
g---pi-yqdrenvp------------------cklwnkpvag-----na
---------------aedyywpi-----------n-lv-nlyv-ekavge
iytps--hi-verh------------------iq-a----lwlk-----m
-----ppa--ppsfrlclkknrdg---fsld-nedl-----s--niktfn
rkyeivmca----l--kl-q--p--n--fp----aah-avitpv---ep-
------------ll-----------s---------------------s--
n----eqlq-------ih--ar-----------------cqetitai---
-n---------kvgggv--a---aal-----pipvaqakpmv---e----
------sc-----------------fkdtdklnnisflksg--------c
kfr-g-vi-rpgcy--akifr-lia-vaqki---earfdck-agca-gyd
lf--lkgn------------ayta-tasmd
>node17
-siep----iqkgeaek----------gh---plaamvg-----------
avvp-----------h-appnl-kvqg---------asilfdlqa-----
lsq-a-----f--ddltivlyqqnrdehpnt-tqnnypqark--in-ivr
kpge--kfkfa-----ski-------ggglskqvg---------------
-k---q---gg---s-isk-g-ip----f-l--t--------v-------
--------t---gg-----t--afk-d------gvsyy------dcrkvv
vi-------angk--------hn----lfpllgh----p-----qcpklp
--sdphfeacvndavkye-kd--gvgvs----ypgeisseeh--sr---v
--isqkeadgak----kglqnkvekng----nne-gdea-k-nh------
--dgkp-----------------------fialvqspspgvt--gdf-vl
g---pi-yqdrenvp------------------cklwnkpvag-----na
---------------aedyywpi-----------n-lvfnlfvyekavge
iytpv--vi-verh------------------iq-a----lwlk-----m
-----ppa--ppsfrlclkknrdg---fsld-neal-----s--niktfn
rkyeivmct----l--kl-q--a--n--fa----aah-avttpv---ep-
------------ll-----------s---------------------s--
n----eqlq-------ih--ar-----------------cqetitai---
-k---------kvgggv--a---aal-----sipvaqakpmv---e----
------sc-----------------frdtdklnnisflksg--------c
kfr-l-vi-rpgcy--akifrglip-vaqki---earfdck-agca-gyd
lf--lkgn------------ayta-tasmd
>node7
-sl--------k---ql----------gh---avtksvpc--saqk---g
aa-pya---pv-qnvq-epml---yhs---------ramvfevcvvgqed
wrk-a-----y--kslkfn----shadsvcvrhvaecerk----gd-e--
-agd--sf-ld-----dqa-------e-----n--clelkvfgetlsggp
ve---qnrtgg---nfaw--gstq----i-h--s-----er---------
------------gd-----p-nkfk-h-wlfdvgpdyy------ncrkvv
---------avgp--------la--anrfpl--v----a-----s--kmp
plgdshf--claaaikgg-pe--p---g----ypakendteh--kw---v
------gsdgng--whktfve-ge-eg----qlkvsnha-k-nl------
--dgepsatracvp---------dgy-d----ll---ahkvt--snf-vl
q-is---yk-rknkstiagfearlvtffgalkeckkwdkagav-------
-----------q-rasrtyiwpifgatlk--------v-g----------
-hcpkakhl-ndrnghdpkckrligmt--tvw-q-e----lymk-----s
-----paq--gacnta-i----ng---yhlh-vnhlnsprvsfalvdtfs
kkyqmvhsv----ip-ll-gflp--tltwctywiqlcqgii-lf---kpk
f---graanlysfl-----------svrskpts-------a-nln-ps--
t----khsk-------eh--nk------hvdcqs----lctkawavvdvm
qnetks---tgllgdlv--d---tgl---saeap----nsss---f-alf
cresfktc-----------------wddlpglgdvringdgcgslhlipc
kyr-e-viqrgggl--akcfr-lkt-vltrvcsnpgr-------ca-gih
lf--tdtsgwgtvffslylltypa-svcqd
>ENV_SIVG1/22-522
---------------------------------vtksvsc--saqk---g
aa-pyamvqpv-rdvqg---l---yqn---------ramvfhvtvvgqed
wrksa-----v--kslkfn----shanslcvrhvaecepk----gdnq--
-aad-----ldwphrvdqh-------e-----n--clelkifgstlsgsp
ve---qnrtgg---nfaw--gstl----i-h--s-----ar---------
------------gdgeaffp-hrfk-h-wlfdvgpdyy------ncrkvv
---------avgp--------la--aerfpl--v----a-----s--k--
-lgtphf--ciaaaikag-pergp---g----ypakesdteh--kw---v
------gsdgne--wnkifve-ge-eg----elkvsnha-k-nl------
--dgepratrasvp---------dgy-d----ll---alkvt--vny-vt
q-is--qye-r---stiagfdgrlvtffgaikeckkwekagav-------
-----------q-rasrtyiwtifgatlk--------v-g----------
-ncpkakhl-ndrnghdpkcnrligqkwksvw-e-e----lyvk-----s
-----paq--gicntg-i----na---yvlh-vnelesp-vsfalvdtfn
nrnhmvnsi----ia-lh-gflp--altwcvywiqlcqkli-lf---kpk
f---gsavslysfl-----------svrsvptd-------a-nld-ps--
t----khsk-------eh--nk------hidcqs----lcnkdlavvevm
qnasks---tgllgdlv--d---tgl---aaedp----nsks---f-alf
cresfkscaspa-------------wsdlpglgdvringdgcgalhlipr
ksr-p-liqrgggl--akcfl-lks-vfartcsnpgh-------cd-dth
lf--tdvsgwgtvfft--lltypl-svcqd
>node9
-slep----iskgdaea----------gh---alaasvgglgc--h---g
avvp-----------h-appnl-kvqg---------aailfdlqa-----
lsq-a-----f--kdltivlyqptreentna-iqtnysqark--pn-i--
-pge--kf-fd-----ski-------gnglskavgcw---------ts--
-n---qirgag---s-ir--g-ip----f-l--t--------l-------
--------t---gg-----t--sfk-d------gvsyy------ncrkvv
vv-------angt--------mn----ifpl--h----p-----q--klp
--ndphf--cvqdavkae-kd--sv-vg----ypveqsseeh--er---l
--isayeaegtk--wnkslqnkaenng----qniignha-k-sp------
--dgkpp---------------------vfvalvqcpgskvt--adf-vl
s---pi-yqtrgnlp------------------cklwnkpvag-----na
---------------aeeyiwpi-----------n-li-nlyv-ekavgq
iysps--hi-vdkh------------------iq-a----lylk-----g
-----ppa--ppsfrlcl----dg---ysld-nedl-----s--iietys
rkyeivmca----l--kt-q--p--nldfp----vay-avitsi---ep-
------------ll-----------s---------------------s--
n----sqlq-------ih--ar-----------------cqgtiavi---
-d---------kigggv--e---aal-----pip----kpmg---n----
------sc-----------------fketdklaninflksg--------c
kfr-d-vi-kpgay--akifr-lkt-vahri---earfdyk-agca-gfd
lf--ldgnlwglksygpfmlayta-aacqd
>ENV_HV2D2/24-513
-senp----islgepea----------gd---siav-vealgc--h---g
--ap-----------h-apanl-kvdg---------aallfdk-a-----
mak-a-----fldqnlthvlyqpvsdentdk-tqslyaqcrs--pn-i--
-pge--tf-fa-----sgi-------ggglgragg---------------
-a---qthg-----s-ifml---s----f-l--k--------l-------
--------a---gg-----a--afr-e------gityy------kcrrvi
vv-------asgi--------vk----iftq--h----p-----t--kvp
--dnphfgaca-----an-kd--al-ts----ytgerqadeh--qq--pl
gdisqkeaefak----kslqkkgdkdp----anq-neha-k-ap------
--dakpp---------------------vfialvqcpsptvt--gdf-tl
g---p----greni-------------------ck----dvig-----aa
---------------iedyywpk-----------shli-tls--ekpvge
iytpy--hi-vdrh------------------il-s----lflr-----e
-----pht--pasfrlclrkdrdg---fsld-desl-----g--nvk-tn
qky-lvlca----l--kled--p--k--fp----aey-gvltgv---ep-
------------vf-----------s---------------------d--
s----eqlq-------ih--ar-----------------cqatipai---
-e---------kdgagv--v---aml-----qip----tpkv---n----
------sa-----------------fketeklsni-flk-g--------c
kfv-n-vi-ipvay--akisr-lka-vsqri---qarylckraaca-gfd
lf--legncwglkpygptmlayta-aacpq
>node10
-slep----iskgeaea----------gh---alaamvgglgc--h---g
avvp-----------h-appnl-kvqg---------aailfdlqa-----
msq-a-----f--qdltivlyqptrdentnt-tqtnysqark--pn-i--
-pge--kf-fa-----ski-------ggglgkavg---------------
-k---qirggg---s-irk-g-ip----f-l--t--------l-------
--------t---gg-----t--afk-d------gvsyy------ncrkvv
vv-------angk--------vn----ifpl--h----p-----q--klp
--ndphfeacvqdavkae-kd--gv-vs----ypveksseeh--er---l
--isqkeaegak----kslqnkvekng----ene-gdha-k-sp------
--dgkpp---------------------vfialvqcpspkvt--gdf-vl
g---pi-yqgrdnip------------------cklwnkpvag-----na
---------------aedyywpi-----------n-li-nlyv-ekavge
iytps--hi-vdrh------------------iq-a----lflk-----v
-----ppa--ppsfrlclkknrdg---fsld-nedl-----s--niktyn
rkyeivmca----l--kl-q--p--n--fp----aay-avitsv---ep-
------------ll-----------s---------------------s--
n----eqlq-------ih--ar-----------------cqgtisai---
-d---------kvgggv--a---aal-----pip----kpmv---n----
------sc-----------------fketdklsninflksg--------c
kfr-d-vi-rpgay--akifr-lka-vahki---earfdck-agca-gfd
lf--legniwglknygpfmlayta-aacqd
>ENV_HV2G1/23-502
-sieprftpiskgeada----------sh---alaamvgglsc--h---g
avvp-----------h-adpkl-kvqg---------atilfemqa-----
msq-a-----l--ddltivlyqptrdehtnt-rqnnypqark--pk-i--
-aae--kfrfa-----ski-------ggdlskavg---------------
-gplsq---gg---s-isk-g-ip----f-l--t--------l-------
--------t---ga-----t--sfk-d------gvsyy------nsrkvv
vi-------sngk--------tq----lfsl--h----p-----q--klk
--ndphfeacvndavkae-kd--gv-vs----yp-ekasesh--qr---v
--isqkeadgak----kslqnnvekng----dne-g-------q------
--dgkp-----------------------fiaiaqcaspnvs--gdf-vl
g---si-yqgrenvp------------------cqlwnkqvvgdkgaada
---------------aesyywpi-----------n-lv-nlyv-ekavge
ittps--hc-verh------------------iq-a----lwlk-----m
-----ppe--ppsfrlc------g---fsld-nedl-----t--niktfn
rkyeivmca----l--kl-q--p--k--lp----aah-avitsl---ep-
------------ll-----------v---------------------s--
n----eqlq-------ih--ar-----------------cqgfitai---
-n---------kvdggv--a---aal-----piavaqakpmv---d----
------sc-----------------fketdk-nginfvkng--------c
syr-g-vi-rsgay--akvfr-lka-vahki---earfdck-agca-gfd
lf--lkgniwglkntgpfmlaytg-taymd
>ENV_SIVV1/24-538
-sl--------k---ql----------gh---nvnkripc--tnhk----
---pya---pvhdhvt-spml---yhs---------ramvfe------ee
wrs-s-----f--isl----------gkvcvrdvsecqrd----vd-q--
-pgs--sy-la-----eqs-------e-----n--cldipvlghtlsgdp
ve---hnptvg---sigw---smq---------------er---------
------------gd-----ptrkfk-q-wlflv--nya------ncrkty
---------ivgp--------lg--firfpv--v----a-----s--kmp
-lvdstf--ctaatrkgg-pe--p---gpgdwyrdkegdkgh--kw---v
------gdkvsg--whktfvg-gd-q------lkvtlha-kgdf------
--egdatavkactp---------tgy-n---------ahkvt--lmf-vl
e-lr---yk-sknk----------vnyfp---dcrkwdkaasv-------
-----------k-rparsqfwaiyganlk--------i-g----------
-ycpkp--i-pdrngkdpkctmlmgma--tvw-q-e----lyfk-----g
-----pse--n-cnta-i----qd---yrlh-anqinsphtgfplletft
kkyqlvn-v----iaall-gflf--taawctywiq---gii-lf---krk
----gkaanlysfv-----------avkssptk-------a-sln-pg--
kdtgh--nr-------ehgpkk------evncds----lcaeg----dvm
enetnsnptvglladll--q---kal---sqivp----nmsp---fmvlf
cresfknc-----------------wgd--gigevlinadgvgs--miac
kfr-e-taesgegi--sncfr-l---------alasm-------ca-gth
lllsldkkgr--v------tt---------
>ENV_SIVGB/47-569
iee--------r---datsscdpklndgidrwhav-------astlqasg
tr-n-----------d-qgev---yqatseygvekppsvv----------
----gcehivf--esiev---------------vrecvkk----gn----
--ggqlah-t-----------------------------i-dvat----s
pe------ngesnmnfaa--sgss----ith--tcalhgsslfripkemf
lmygnklm--------------a-r-r-------pv----------wvee
--fadgtagagea--------np----sypl--g----ssadhpa--rgp
pmgsgdk--ctgdavkcv-re------s----nrsvk--kvr--sw---a
------raks----wpgnsik--s-yg------iesfiq-k-algtggyv
slaaqags----fkaanlsgavkpphaa----hg----------------
ves----ykievstecv-------------------rgelcfa-----sr
pnfpsvallrlgqdqgkty--tvfdl--kreqptg-av-h----------
-hcvsstglinqrkrhgqqcctl------ivw-dgagddlryen-----d
-----maaamtvcnak-v----apekaktynp-------rs--d-iktkr
-ksnpi-------ls-il----------wh--wt--t-ftd-rystqigs
fgtnavgs----rllvfsgfirgdas---tcyganqsmcc-ggracpeet
a----ka-rqstmppl-h--etfeelal----vsfydavcassppdvp--
-a---------vcgshldkviil---------is----egselvnl----
--prvsnp----atvsfetedlktlw---------n----------iivc
ksh-e-glsrp--fcw---fp-ikegkigrh-------------------
tf------mwkaalfiplrisvsviagsan
>ENV_SIVM1/24-528
-ylpp----iskgeaea----------kh---alydsvgglgc--r---g
atvp-----------q-gprnl-svqg---------adilydlqa-----
lsq-a-----w--rdltivlyqpngedntta-vqtnytqgrk--vn-i--
-pge--kf-fd-----ski-------gnglqkavgcw---------ts--
-n---kiqgag---p-ir--a-ipakvsf-l--s--------l-------
--------p---gg-----t--sfk-d------gvsyy------ncrkvv
va-------aagt--------mn----alpl--hhlyrr-----q--k--
-----hf--ctqdateae-kk--sv-vg----ypveqssdeh--erqg-l
--isayeaegtkfv---slfnkaenng----qelignha-k-sp------
--dgkpp---------------------vfvalvqcpgstvtldady-ll
s---pi-yhtkgnap------------------ckkwnkpvag-----na
---------------aeqyiwpi-----------s-qi-nlfv-ekdvgq
lysps--hi-vdkh------------------vq-d----l--------g
-----ppa--ppsfrlcl----dg---yrld-neel-----s--ki----
-kyeivmca----l--km-q--a--nldft----vsy-aivtsi---ep-
------------ll-----------s---------------------p--
d----sqvq-------ih--ad-----------------cqssiavi---
-d---------kigggv--e---asl-----sst----kplg---f----
------sc-----------------fkepdkianinllgsg--------c
kfq-d-ii-kpgay--aklfr-lks-vadrv---qakfdyk-agca-gfd
lf--ldgdlwglksygplmlayta-aacqk
>ENV_HV2NZ/24-502
-svea----vgkgeaek----------gh---pmaamtg-----------
avip-----------h-appnigkieg---------gsilfnlq------
----------f--aeltivlyqhirdehpnt-tqnkypearr--kn-ivk
npge--kfkfa-----ski-------g-----------------------
--------------------------------------------------
------------gg-----v--qfk-d------gvsyy------dcrqvv
vl-------angk--------hn----lfpllah----p-----qapklp
--sdppfeacvt-------nd--gvdvs----ypgiilseeh--tr---v
--i--------------------eknp----nve-gdea-r-nh------
--dgkp-----------------------lialmqspspgvk--gnf-vl
s---pm-fqdhesvp------------------ckvwdnrvvg-----na
---------------aedyywsi-----------s-lifhllvydkpige
iftpv--ii-lerh------------------iq-a----lwlm-----m
-----ppt--spsfrlclkrksdg---fsld-neal-----g--diktfn
rkyeivmcatphpl--kl-q--atas--ia----aah-avttav---ep-
------------ll-----------s---------------------s--
n----eqlq-------ih--ar-----------------cqetitai---
-k---------klgggv--a---vnl-----slklaqakskv---e----
------sc-----------------frdtekvnnitflksg--------c
kfr-l-vi-ragcy--akifrglit-vaqkv---enrfdcg-agca-tyd
sf--lkgs------------pyaa-natmq
>node19
-siep----iskgeaea----------gh---alaamvgglsc--h---g
avvp-----------h-appnl-kvqg---------asilfdlqa-----
msq-a-----f--ddltivlyqqtrdehtnt-tqnnypqark--pn-ivr
kpge--kfkfa-----ski-------ggglskavg---------------
-k---q---gg---s-isk-g-ip----f-l--t--------l-------
--------t---gg-----t--sfk-d------gvsyy------ncrkvv
vi-------angk--------vn----lfpl--h----p-----q--klp
--ndphfeacvndavkye-kd--gv-vs----ypgeksseeh--qr---v
--isqkeadgak----kslqnkvekng----nne-gdea-k-sq------
--dgkp-----------------------fialvqcpspnvt--gdf-vl
g---pi-yqgrdnvp------------------cklwnkpvag-----na
---------------aedyywpi-----------n-lv-nlyv-ekavge
iytps--hi-verh------------------iq-a----lwlk-----m
-----ppa--ppsfrlclkknrdg---fsld-nedl-----s--niktfn
rkyeivmca----l--kl-q--p--n--fp----aah-avitpv---ep-
------------ll-----------s---------------------s--
n----eqlq-------ih--ar-----------------cqetitai---
-n---------kvgggv--a---aal-----pipvaqakpmv---e----
------sc-----------------fketdklnnisflksg--------c
kfr-g-vi-rpgcy--akifr-lia-vahki---earfdck-agca-gyd
lf--lkgniwglknsgpfmlayta-tacmd
>node14
-siep----iskgdaek----------gh---alaamvgglsc--h---g
avvp-----------h-appnl-kvrg---------asilfdlqa-----
mse-a-----f--ddltivlyqqardehtnt-tqnnypqakk--pn-ivr
kpge--kfkfa-----sks-------ggglskavg---------------
-k---q---gg---s-vsk-g-ip----f-l--t--------l-------
--------t---gg-----t--sfkwd------gvayy------ncrkvv
vi-------angk--------vn----lfpl--h----p-----q--klp
--ndphfeacvndivkfg-kd--gv-vs----ypgnksseeh--qr---v
--isqsepdggk----kgaqnkvekng----nne-gdea-k-sq------
--dgkp-----------------------fialvpcpspnvt--gdf-vl
g---pi-yqdrengp------------------cklwnkpvag-----da
---------------aedyfwpi-----------n-lv-nlyv-ekavge
iytpn--hi-verh------------------iq-a----fwlk-----m
-----ppa--ppsfrlclkknrdg---fsld-nedl-----s--niktfn
rkyeivmca----l--kl-q--p--n--fp----aah-avitpv---ep-
------------ll-----------s---------------------s--
n----qqlq-------in--ar-----------------cqetitai---
-e---------kvgggv--a---aal-----pipvaqakpmv---e----
------sc-----------------fkntdtlnnisflksg--------c
ifr-gkai-rpgay--akifq-lka-vaqki---earfdck-agca-gyd
lf--lkgn------------ayta-tasmd
>node8
-sl--------k---ql----------gh---altksvps--sdqk---g
aa-p-----------q-eppl---yrs---------paivfevcv-----
wkq-a-----y--kslkfn----chadsvcvrhvaecark----gn-e--
-age--sf-ld-----dqv-------d-----n--clelkvpgetlsgnp
vd---qirtgg---sfvs--gstq----i-h--s-----erml-------
--------t---gn-----t--rfk-h------gpayy------ncrkvv
---------avgp--------lt----rfpl--a----a-----s--kmp
plgnshf--ctdaaikaq-ae--p---g----ypipenddeh--dw---v
------gsdgnp--whktfve-ae-gg----qlkvsnhs-k-nl------
--dgepnasrpcvp---------day-d----ll---lhkvt--sef-vl
q-ic---ykvrknksavagf-----------keckrwdkaaav-----ek
-----------q-raartyiwpifgi--kk-knit-qv-g----------
-ycpkaihl-ndrnkhdpkckrl------vvw-q-e----lylk-----s
-----paq--gvchta-i----dg---ydln-vnhlnsprvsfalvetfr
kkyeivhsv----ip-ll-gflp--nltwctywvvly-gii-nf---qpk
f---grap----ll-----------strgkatg-------aknin-ps--
t----shsr-------dh--nk------pvdhqs----vcastwavvdvv
qn---------ligdlv--e---tgl-----eap----nsss---f-alf
srqsfatc-----------------wddvsglgdiringdgs-slylipc
kyr-e-viqrsgaf--ekcfr-lkt-vltrvcsdpgr-------ca-gfh
lf--vdtsawgttffsqymltypa-sacqd
