>node19
k-------t--sakk---gatllgaerggee-------------------
-----a---hfe-----gcggrk-------ehr-vhei---aft---nad
e-----ilkls-------------------gg-sa---------g----v
hkvs-gnls--lggkyhrksgtecgktnhllpmldp-t-gpg-q----kd
-----cda-----l----hr------pkkqagqthp---v-------v--
vp-alqychkc---s---giyilna-------k-------------nlwk
aqgvnghrswd--lvsl--vackg--------vavasear----le--nd
--ianr-----------------l----annedcr--rl-kmtfa-----
--dh----aqp-----vkc---igeq------ygral---pavd------
-----gkvgah-st-------kqc--gnhldrt-------------v--n
ledft--taikvdveippvg--c----tg-----------sylsnsl--p
hans---------knhl-sggksf---lklfvglptnl--ktgkspgncl
prvam------av-gm---------a--llvakclga--enrre-lhel-
-l-------aafkligfhila-------kqdglglkssndlf-minfgar
wt---------g-kkil--fy------ae-grl--a-------faf-fa-
--l--------cc--frkqcatilq----------mtd----f-kg----
e---gsdr---al---al--nqgvafpsd------k------la------
r---lw-elc-p--ggfrygk-------pfegkvkdve-el--k-q----
ikkgrpyv----------------------kp-sqig-ft----arl--g
tceek-f-cpkk-s-gvkpp---------awt---h-----eqv--len-
------slfnlq----------ti---gyyg-----n
>ENV_SIVGB/47-569
k-----------g-----qlvrlvnlvgk-aag-pv-----------vdh
l-ddvl---sl------k-------------daivvd------shlssgp
----------k-------------nnpnat----dsskmlcikscv---t
pi----pkkaalhg------r--an--------k-qny-----------e
-----stgekskrl----nr----fk----kpgq-e---sgqylnlya--
lskklhc-------ngka---ep-----wkelk-------------kmlk
pl---------------ylmrchelkllccpe-----------------g
eg--------------------------c-----l--re-qs----el--
--tl----swg-----iks---a-------------g--p---daakt--
-------yn-tlnsrehinqhvpcep----akk-------------q--r
vskml--gf-----------lpcsglhvg-----------nfd---i---
-------------rs-------gf---leyd-----ll--hpg---gqtw
gslhm------rvesg---------i--m----cvglilg-krgssqqli
lfglidrnyp-----a----ttdddlll--gnr-----y-segpr---vk
wsf-----gl-d-kkds----------rt-kaviifagnihmffpyvvvw
-v---------cl--gkhd--llakepyetpgcrhd----kst-ksfivg
vcfsav-----q-------------rsieskctth-------rapg--dv
--------mc-i--rglrfesctlksatgygvkfrtq-gdldeg-v----
d--gf-gim-------gsapape--eqt-l----kst-md---k------
vsh-evl-c-ekvs-cs-chl--iynhwkaef----------ge-r-pqp
--ds--atyhld------rfvi-----ly-thhrrgw
>node14
k-------s--spkk---gatllgaerggde-------------------
-----a---hfq-----gcggrk-------ehr-vhei---aft---nad
e-----ilkls-------------------ag-sa---------g----v
nkvs-gnls--lgakyhrktgtgcgktnhllpmldp-t-gsg-q----kd
-----cdt-----l----hr------pkkqagqkhp---v-------v--
vp-alqychkc---s---giyilna-------k-------------nlwk
aqgvnghrswe--lvsl--vackg--------vavasear----le--nd
--iadr-----------------l----aknddcr--rl-kmafa-----
--dh----aqp-----vkc---igee------ydral---pave------
-----gkvgah-st-------krc--gnhldrt-------------v--g
leaft--taikvdvdippvg--c----tg-----------sylsnsl--t
--ns---------knhl-sggmgf---lklfvglptnl--ktgksagnaf
prvam------av-gm---------a--llvakclga--enrre-lhel-
-l-------pafkligfhila-------kqdglglkssndlf-minfgar
wt---------g-kkil--fy------ae-grl--v-------faf-fa-
--l--------cc--frkpcatilq----------mtd----f-kg----
e---gsdr---al---al--nqgvafpsd------k------la------
r---lw-elc-p--ggfrygk-------pfegkikdve-el--k-q----
ikkgrpyv----------------------kp-sqvg-ft----arl--g
tceek-f-cpkk-svgvkpp---------awt---h-----eqv--len-
------slfnlq----------ti---gyyg-----n
>node18
k-------t--sakk---gatllgaerggee-------------------
-----a---hfq-----gcggrk-------ehr-vhei---aft---nad
e-----ilkls-------------------gg-sa---------g----v
hkvs-gnls--lggkyhrksgtecgktnhllpmldp-t-gpg-q----kd
-----cda-----l----hr------pkkqagqthp---v-------v--
vp-alqychkc---s---giyilna-------k-------------nlwk
aqgvnghrswe--lvsl--vackg--------vavasear----le--nd
--ianr-----------------l----annedcr--rl-kmafa-----
--dh----aqp-----vkc---igeq------ygral---pave------
-----gkvgah-st-------kqc--gnhldrt-------------v--n
ledft--taikvdveippvg--c----tg-----------sylsnsl--p
hans---------knhl-sggksf---lklfvglptnl--ktgkspgncl
prvam------av-gm---------a--llvakclga--enrre-lhel-
-l-------aafkligfhila-------kqdglglkssndlf-minfgar
wt---------g-kkil--fy------ae-grl--a-------faf-fa-
--l--------cc--frkqcatilq----------mtd----f-kg----
e---gsdr---al---al--nqgvafpsd------k------la------
r---lw-elc-p--ggfrygk-------pfegkvkdve-el--k-q----
ikkgrpyv----------------------kp-sqig-ft----arl--g
tceek-f-cpkk-s-gvkpp---------awt---h-----eqv--len-
------slfnlq----------ti---gyyg-----n
>ENV_HV2BE/24-510
r-------a--sekk---eavklggergade-------------------
-----a---hfk-----gcsgrktgmktclehr-vqea---aft----an
e-----ilkls-------------------ag-sa---------g----v
nkvs-gdln--fgskyhrktgtvcgktnhllpmldp-n-gs--------d
-----cdt-----l----hk------pkkqtgqdvp---i-------i--
vp-alqfchkc---s---giyilna-------q-------------etwk
aegvn-----enllvql--vpvkg--------vavasgvr----le--nn
--madr-----------------l----adnddcr--rl-kvafa-----
--dh----aqp-----vkc---igee------yaral---pdvd------
-----akigah-st-------ksc--gnhlart-------------v--g
meaft--aaiktdtei------c----tg-----------syltesl--t
--ng---------knhl-ssgmgf---lklfvglptnlst--grtagsaf
pksam------av-gm---------awtllaakclgq--enrre-yhsl-
-l-------pafvltgfhila-------kqeglglksshdlf-minygar
wt---------n-e------y------ae-gr-------------f-fe-
--l--------cctgrrkpcatill----------mtd----fckg----
e---nskr---allddal--negvafrsd------k------la------
r---mw-dlc-a--gnfrygt-------pfegkikdve-el--k-q----
ikkgrpyv----------------------kp-sqvg-fa----a-l--g
aceek-f-cpkk-svgvkpp---------awisgah-----eqv--ven-
------slfnlqsphhli----ti---ayyg-----g
>node8
k-----------a-----qpsmlgddrggvghglhe-----------s--
-kgdhg---hfk-----gckkhf-------dyk-lreg---sfah--kan
----------awvaataagk---lsknf--rr-ch---------cp---i
hila-ggnagplhg------s--tg--------l-dea--ag-r----qd
-----cds-----l----dr------p--qvtrn-s---a-q-----i--
lt-klvychkc---p---gs-vvpgayqfkqfk-------------klwk
aq-----------------mpchg--------gpvasdetgrgdvn--de
--t-------------------------p---dcw--pi-epelwiad--
--ey----aet-----imc---i-------------s---plla------
-----sqvgeq-fr-------vqc--gshlsrp-------------f--g
vedyl--gs-------------c----vg-----------pfnkval--a
---k---------kg-------ay---lklt-----dl--hpgr--gnsw
pwiam------pv-gg---------i--v----cvga--d-rrq-khel-
-fti-ekiyq-----g----a-------kqtqp-----ypfm-mrifggr
wtf-----alng-kksk----------ee-rll--n-------frf-hvt
rgi--------cv--srkdcgtiaq----spglkaetdkmksf-rg----
e---lk-----ql---al--kq-tplpse------k------kgmg--eq
--------sc-l--dgfkygt--n-tpkpfdtkfqtk--elgtg-r----
e--gf-yva-------sh--a-a--hap-l----qtv-lg---q--vecg
qcqed-v-cpkdle-gvspdltfltk--mkwt----------tilg-kdp
--qpflsgydle----------tf---ay-g-----h
>ENV_SIVV1/24-538
t-----------a-----qpsmlgdnrgtvsqvlhd-----------c--
-rgeys---hfk-----gckshf-------hyk-hksg---drdh--ran
----------awlngt---kgkniskni--wr-lh---------cp---i
hilqkdgnegpldg------g--ng--------e-dds------------
-----ce------n----epfvpt--d--qvtrn-s---a-r-----v--
iv-qlvy-hsarkgp---gn-hvpgtgpykqyksmkkglfliictkklwe
pk-----------------epcha--------gpiase-------t--qe
--s---h-------------------------------------what--
--ty----gdskprlivmc-----------------------ka------
-----geiaga-yk-------elr--ggslvrh-------raqdwqy--a
vdgafapas--------------------------------fr-itlfv-
-------------rg-------eylahlelw-----hl--hppr--gqgw
twttm------da-tv---------l--v-------c--n-dnq-tesv-
-ftl-etdfq-----d----p-------kdkpp-------------fggh
--h-----tlds-kkst----------ga-rml--l-------fkv-nve
r---eqlrwgicv--sr------------spaikrnrkkm----qg----
e---ls--kdgal---al--kt-lrmqae------k------kg--pken
--------gc-l--dgfkfga--t-tikpydskfqhg--nlgsg-rspkn
d--af-ivevghtshras--c-npvnkppl----ksv-ggkaiq--necg
pcqed-v-cpmelq-gvapdltflgm--mkfv----gee------g-kep
--qpyfggyd--------------------a-----h
>ENV_SIVM1/24-528
k-------g--pakksvegstllgaergged-------------------
-----a---hfh-----vcggrr-------eyr--spv---aitl--kdd
ysmnsktlklg-------------------gakva---------s-hdav
hris-gggakslggtyhrkpdascgklnhml-kl-pet-gpg-q----kd
-----cda-----l----hr------p--qaeqn-p---v-------h--
va-vlgychkc---d---gsyvlna-------d-------------nlwk
rqgveahrtwg--i-pl--vackg--------atvassar----lqrknd
--iahr-skrgildkpilkvfyhl----pnaedcr--rl-kitft---dk
sldhsaqsaqa-----ikc---lgdv------ygral---pavd----gf
nkissgqvaen-ky-------kqc--gnhlek--------------v--a
leddl--takkadveappvg--c----sg-----------syfsdsl--p
hkpa---------qnrlssggtqf---lklfvgllvnl--kigrspgncl
pwlam------si-gm---------i--k----slga--enrre-nhel-
-l-------agfklig----a-------nqeglgl-sannvm-mqkfgnt
wta-----taeggrkil--iy------te-gwl-----------af-ts-
--l--------cv--frkdcatiiq----------mvd----f-rg----
e---gs-----ql---al--nagvafpsd------k------lg------
k---lw-knc-p--dgfkygk--n-aev-----mqdvn-el--k-q----
vkkgrtyve-------vl--e-g--det-lke-nqig-ft---qasl--g
tcqee-f-cpkk-s-gvkpplaffvg--fawt---h-----eqv--lkn-
------sifelq----------ti---gyyg-----g
>node9
k-------t--pakk---gatllgaergged-------------------
-----a---hfh-----gcggrk-------eyr-vrev---aftl--kad
ys---kilkls-------------------gg-va---------s----v
hkvs-ggsagslggtyhrksgaecgktnhll-ml-pet-gpg-q----kd
-----cda-----l----hr------p--qanqn-p---v-------v--
va-vleychkc---s---gsfvlna-------n-------------nlwk
aqgvnahrswd--i-sl--vackg--------aavasear----le--nd
--iahr-----------------l----pnaedcr--rl-kitft-----
--eh----aqa-----ikc---igev------ygral---pavd------
-----gqvged-sh-------kqc--gnhldrt-------------v--t
lednl--tankvdveippvg--c----tg-----------syfsdsl--p
havs---------knhlssggksf---lklfvglpvnl--ktgrspgncl
pwvam------sv-gm---------i--m----clga--enrre-nhel-
-l-------aafklig----a-------kqdglglksandim-mqkfgar
wtt-----taeg-rkil--iy------ae-gwl--a-------faf-ya-
--l--------cv--frkdcatiiq----------mte----f-rg----
e---gs-----ql---al--nqgvafpsd------k------lg------
r---lw-dnc-p--ngfkygk--n-aevpfegklqdve-el--k-q----
vkkgrtyve-------il--d-g--det-lke-sqig-ft---qarl--g
tcqee-f-cpkk-n-gvkpplaffvg--fawt---h-----eqi--lkn-
------slfelq----------ti---gyyg-----n
>node11
k-------t--sakk---gatllgaerggee-------------------
-----a---hfe-----gcggrk-------ehr-vhei---aft---nad
e-----ilkls-------------------gg-sa---------g----v
hkvs-gnls--lggkyhrksgtecgktnhllpmldp-t-gpg-q----kd
-----cda-----l----hr------pkkqagqtgp---v-------v--
vp-alqychkc---s---giyilna-------n-------------nlwk
aqgvnghrswd--lvsl--vackg--------aavasear----le--nd
--iahr-----------------l----pnnedcr--rl-kmtfa-----
--dh----aqp-----vkc---igeq------ygral---pavd------
-----gpvgad-st-------kqc--gnhldrt-------------v--n
ledft--tankvdveippvg--c----tg-----------sylsnsl--p
hans---------knhlssggksf---lklfvglptnl--ktgkspgncl
pwvam------av-gm---------a--llvakclga--enrre-lhel-
-l-------aafkligfhila-------kqdglglkstndlf-minfgar
wt---------g-kkil--fy------ae-grl--a-------faf-fa-
--l--------cc--frkqcatilq----------mtd----f-kg----
e---gsdr---al---al--nqgvafpsd------k------la------
r---lw-elc-p--ggfrygk-------pfegkvkdve-el--k-q----
ikkgrpyv----------------------kp-sqig-ft----arl--g
tceek-f-cpkk-s-gvkpp---------awt---h-----eqv--len-
------slfnlq----------ti---gyyg-----n
>ENV_HV2D1/24-501
k-------a--spkr---gagllgaergade-------------------
-----agawhfq-----gcagrk-------eh---het---afs---nae
e-----ilkls-------------------ag-ss---------g----v
nkvs-glls--lgtkyerktgagcgr-ghllpllda-s-gag-q----kd
-----cgt-----l----hr------pkkqasqknp---v-------v--
vp-alqycrkc---s---giyilna-------k-------------nlwe
aqgvnghrtwq--lvsl--vkakg--------iavasagr----le--ne
--iaqr-----------------l----aknddcr--rl-kmafa-----
--d---------------c---vgee------ydral---aave------
-----gkvgah-st--------sc--anhldrtlpehwkk------vgvg
leaft--talkvdidippvv--c----tv-----------sylsnsl--v
--nl---------knhl-s-glgf---lkwfvglptty--ktgkvagaai
prval------ah-sm-------------------------rrq-lhel-
-l-------pafkligyeila-------nedglglksckelf-mvnfgar
wt---------g-knil--fy------ae-grl--v-------faf-fa-
--l--------cc--frktcatilp----------mtd----f-kg----
e---gsdr---al---al--nqgvafasd------k------lt------
rkptlw-elc-p--ggfrysk-------pfngkvkdve-ql--k-q----
ikkgkpyv----------------------kp-tqvg-fk----arl--g
tcdek-f-cpkk-svgvkpp---------awt---h-----eqv--len-
------qlfdlq----------ni---gfyg-----n
>node10
k-------t--pakk---gatllgaerggee-------------------
-----a---hfe-----gcggrk-------ehr-vrev---aft---nad
y-----ilkls-------------------gg-va---------p----v
hkvs-gnss--lggtyhrksgaecgktnhllpml-p-t-gpg-q----kd
-----cda-----l----hr------p--qagqtgp---v-------v--
vp-alqychkc---s---gifvlna-------n-------------nlwk
aqgvnghrswd--i-sl--vackg--------aavasear----le--nd
--iahr-----------------l----pnnedcr--rl-kitfa-----
--eh----aqp-----ikc---igeq------ygral---pavd------
-----gavged-sh-------kqc--gnhldrt-------------v--t
ledfl--tankvdveippvg--c----tg-----------sylsdsl--p
hans---------knhlssggksf---lklfvglpvnl--ktgkspgncl
pwvam------sv-gm---------a--llhakclga--enrre-lhel-
-l-------aafkligfhila-------kqdglglkstndim-mqkfgar
wt---------g-rkil--iy------ae-grl--a-------faf-fa-
--l--------cc--frkecatilq----------mte----f-kg----
e---gs-----ql---al--nqgvafpsd------k------la------
r---lw-dlc-p--ngfrygk-------pfegklqdve-el--k-q----
ikkgrpyv----------------------kp-sqig-ft----arl--g
tceee-f-cpkk-s-gvkpp---------awt---h-----eqv--len-
------slfelq----------ti---gyyg-----n
>ENV_HV2NZ/24-502
k-------k--sqkk---satllgvepgdee-------------------
-----a---hfq-----gcaerk-------ehr-vkei---aft---nad
e-----vlkls-------------------gd-ss---------a----t
hkvs-gn----lggkyhrksggecgrtnhllpmldp-vtgpglq----kd
-----cqg-----l----nr------pkdqigkshp---v-------vrf
vp-alrych-------------l-----------------------liwk
eqavnghrawe--lvnl--vachg--------llvanear----le--da
--innr-----------------l----phtddcn--rl-kmgfa-----
--vh----mqp-----ikcygvi--qgnidsaygral---tave------
-----gsvggm-st-------kqc--gnyadrs-------------l--n
lgdft--taikmdieiiavg--c----tg-----------vylshsl--r
hans---------enhl-sggktf---lkllvglpvnf--qngksagncl
pkaam------av-gm---------s--mmvakclga--enrrn-lhal-
-l-------aefkldefhila-------qqdglglkssndlf-miifgar
ws---------g-kkiv--fyeqslkead-grl--d-------faf-fa-
--l--------cc--frdhcatilq----------l--------------
-----------al---al--negvafpnd------t------lr------
h---lwpelc-p--ggfrygk-------pfegkikeie-el--k-p----
vkkgrpyv----------------------kp-sqvgwft----grl--a
scedk-f-apkk-s-gaepp---------awt---h-----eql--leh-
------dlfnlh----------tippagyyg-----r
>node7
k-----------a-----qpsmlgdergsvghvlhe-----------c--
-kgeyg---hfk-----gckkhf-------hyk-lreg---niah--kah
----------awlagt---k---lsknf--rr-th---------cp---i
hild-ggnhgplng------s--tg--------h-dea--ng-r-qesqd
-----cqa-----n----dpfvst--d--qvtrn-s---a-r-----v--
iv-klvychkpkkgp---gs-vvpgayqfkqfkrik--lfliicttklwk
pk-----------------lpchg--------gpiase-------n--ee
--t-------------------------p---dcw--pi-vpelwhat--
--ey----aet-----vmc-----------------------la------
-----gqvpdq-fk-------hqa--gghlarh-------------y--g
vegal--as-------------c----vg-----------sfk-valfv-
-------------rg-------ay---lelt-----hl--hpgr--gnsw
pwiam------pa-gg---------l--v----svga--d-rkq-thsv-
-fti-ekefq-----a----a-------kdtpp-------------fggr
-tf-----aldg-kkak----------ea-rll--n-------frl-nvn
rgflervrwgicv--srkqcgti------spglkktsdkmksf-rg----
e---ln-----ql---al--kq-tsmpae------k------kg----eq
--------ec-l--dgfkygt--n-tpkpfdskfqnk--elgtg-rgakn
d--ay-tvevghst--tp--a-s--aap-l----ktv-gg---q--secg
pcqed-i-cpkelq-gvnpdltflsk--mkft----------vilg-kdp
--qpyfsgydlq----------tf---ay-g-----h
>ENV_HV2G1/23-502
k-------s--eak----gptllnaerggee-------------------
-----a---hye-----gigvrk-------ehr-vhei---aft---nad
e-----ilkls-------------------pa-sa---------g----v
hrvs-gnls--lggkyhr----ecgaddhllpmldp-t-gpa-q----ke
asyvgcda-----l----hr------pksqagqtgp---h-------v--
vp-alqychkc---s---giyqlna-------s-------------nlwk
aqgvnghksws--lvsl--vackg--------ievasear----ie--nd
--iaha-----------------vdcffpnnedsr--kl-rmtfa-----
--dh----ahp-----vkc---igeq------ygqal---savd------
-----gpvsad-st-------kqc--gnhldkn-------------v--n
ledft--glnkvdveippvg--c----vakiqvkssdgeesylsnsl--p
hanscalswsyfdknhmsaadksf---lellvglptnl--ktgkgpgncl
pwvam------al-gm---------a--llvakclga--enrre-lhel-
-l-------aaf-li-------------kedglgikstndlf-mihfgar
wt---------g-pkil--fy------ae-nrl--a-------faf-fa-
--l--------cc--frkqcattlq----------mtd----f-eg----
e---gqgr---gl---pl--nqgvafpse------k------la------
r---lw-elc-p--ggfphgk-------pfegkvkdve-na--k-q----
ikkgrpyh----------------------sp-tqtg-rs----arl--g
tceek-f-cprk-e-gvkpp---------awt---h-----eqv--len-
------slfnlq----------ti---gyyg-----n
>node17
k-------k--sakk---gatllgaergdee-------------------
-----a---hfq-----gcgerk-------ehr-vhei---aft---nad
e-----ilkls-------------------gg-sa---------a----v
hkvs-gnls--lggkyhrksgtecgktnhllpmldp-t-gpg-q----kd
-----cda-----l----hr------pkkqagkthp---v-------v--
vp-alrych-------------lna-------d-------------liwk
aqavnghrtwe--lvsl--vackg--------vavasear----le--nd
--innr-----------------l----annedcr--rl-kmafa-----
--dh----aqp-----vkc---i--q------ygral---pave------
-----gkvggh-st-------kqc--gnhldrt-------------v--n
lgdft--taikmdveiipvg--c----tg-----------sylshsl--p
hans---------knhl-sggksf---lklfvglpvnl--ktgkspgncl
prvam------av-gm---------a--mlvakclga--enrrd-lhel-
-l-------aafkldgfhila-------kqdglglkssndlf-minfgar
wt---------g-kkil--fy------ae-grl--d-------faf-fa-
--l--------cc--frkqcatilq----------lsd----f-kg----
e---gsdr---al---tl--nqgvafpsd------k------la------
r---lw-elc-p--ggfrygk-------pfegkikdie-el--k-q----
vkkgrpyv----------------------kp-sqig-ft----arl--g
tcenk-f-cpkk-s-gvkpp---------awt---h-----eql--leh-
------slfnlq----------tisp-gyyg-----n
>ENV_HV2D2/24-513
kidlygpdt--lakk---gatllgterggeq-------------------
-----t---tye-----gcgkik-------thr-irevlpk---------
------ilels-------------------ak-ia---------p----v
hkvs-gncg--laecynrtseaesgktnhflpsl-s-t-fpg-q----kd
-----cdv-----l----rk------a--qagqasv---v----------
------ychkc---f---gifglsa-------n-------------slwk
tqgvnghrssd----------ckg--------aaiaseak----aq--kd
--ladr-----------------l----ggskdcr--rt-kitfa-----
--dp----aep-----ikc---vg------------------vd------
-----g------------------------qrt-------------v--t
lndfv--va---dvectaag--c----pg-----------aylsehl--p
hads---------knhlssggksf---lrifvglnvdf--ktgsspgnc-
-wvsv------ss-gm---------a--llhakclga--ekrrs-lqel-
-l-------atfkligfhila-------kqgelqltatnavm-lqkftas
wt---------g-rkilngiy------ha-grl--a-------fdf-fa-
--v--------cc--frkicctf-e----------fte----f-kg----
e---gs-----el---allcsqamgfkkd------v------lp------
r---lw-df-------fkypr-------pfhgklqdve-al--k-i----
lkkgr-------------------------kk-sqig-ft----akl--g
a--ee-fccgkg-s-gvkpp---------awt---q---cveqv--i---
--------felq----------ti---ayyd-----h
>ENV_HV2CA/25-512
k-------kmksakk---gatllgaekgnee-------------------
-----a---hfq-----gcgerk-------ehr-lhei---aft---nad
e-----imklk-------------------gg-sa---------a----v
hkls-gtls--lkgkyrrksgtecgkrnrllpkldp-t-grg-q----kd
-----cev-----lesaphr------pkkqagkthp---v-------v--
vp-alrycw-------------lda-------d-------------liwl
aaaitghrlwe-----l--vacyg--------vsvasekr----le--nd
--innr-----------------l----anddncsplrllkmafa-----
--dr----aep-----vkc---v--q------ygral---aavd------
-----gkvggh-st-------kqc--gnhldrt-------------v--n
lgdfs--tairmqvgiipvn--c----tg-----------sylshgl--p
qan----------knhl-rggkpf---lklfvgppvnl--ktgkspgncl
prvamnnpgsftv-gm---------a--mlvakclgs--gkrkn-lhel-
-l-------qefkldgfhlla-------kqnglglksandly-minfggr
wt---------g-kkil--yy------aelgkl--d-------faf-fg-
--l--------hc--frkecatilr----------lsd----f-ng----
e---gtnr---al---tl--nqgvaiasg------kplerhvla------
r---lw-elc-p--gdfryak-------sfegkiksle-el--k-q----
vkksrpyv----------------------kpttqig-ft----arl--g
vcenk-f-caks-s-gvkpp---------awv---h-----eql--leh-
------slinlq----------tisp-gyyd-----n
>ENV_SIVG1/22-522
k-----------a-----qptmlgdergsvgnvlhgrldcflskltnc--
-kgeyg---pfkawvgggckthf-------hys-lrvg---hiah--kaq
----------awlagt---k---fsrqf--rr-sr---------cp---i
nild-ggfnepldg------s--ag--------h-eea--ng-rdeesqq
-----cqa-----n----dpfvsg--n--qvtkn-srqed-r-----v--
iv-kivychk---gp---gs-vvpsayqfknfkrik--lflilc-----k
ka-----------------vachg--------gpvase-------n--qe
--d-------------------------p---daw--pi-vpemw-----
--ef----aqk-----alc------------------ir---lt------
-----eqvpnq-fk-------hqa--gnhlarq-------------y--g
aegal--as-------------c----vg-----------sfk-vslfv-
-------------kg-------an---ld-q-----hv--npkr--gnsw
pwiar------pa-sgldkkahkpcl--v----sags--d-rkq-shsv-
-fti-ekdfq-----p----a-------rdtsp-------------pgsr
-tfsetpsaldg-kkak----------ev-rll--n-------frl-nvn
rgflesvr---cv--sekqcgti------spglrvtadkmksf-rg----
a---ln-----el---pl--gq-tsqpae------k------kr----eq
--------eyrlcsdgikygt--k-takefdakfqgk--emgtgkrgpkn
d--ay--vevghat--ta--a-s--aaa-l----ktv-ka---q--adcg
lcqqe-i-cskelq-gvnpdldflkk--lkfp----------vilg-kdp
enqpyfsgydlq----------tf---ay-g-----h
