>node7
-g-----gktldve----------v-----lend-la--------mvhkh
--skyk--stl----y----a--maaaanl----------py-dptfk--
--segaedlh-avl-kegy---igtcarqa---fqgyikdk----h----
-----sf--------------pt-ncl--tnhtgsg--v-vg--alvre-
anrkag-cdd----------aee------------ssp-vdlqgys--q-
----ici-----ntvg--hn---kyte-criegeawhfsenevwst--ta
ngvg-----tr---------myvs--gglkm--veli-----caiftgt-
------------------tvvvg-----kpkt-k-qkgk-pkkse-dqla
lghq-tfgwqt--pk-qh--gklpgvtmpce----hilvmfaagr-----
---vrrfsgvq-------gnpvs-------------tlpglslektnd--
--ryse---ad---qg--as----atah--t-lmpk---evkpahs----
------ie-y----------cgyiqvipgal---fqige--lnlkea--c
tek-sgg---l-hwglhctdikg-------iewll--------q--tl--
-er----iane--a---g------acma-gl-kf----yfndtdhhvh--
ea-ts-nlheqgafg----gvl-------pad-gsaqipflga-qa----
--vd-l---kenvsgp---s-gla-evdradl-nmvkgli----------
------lgpgggkyp----ylk-asgg--sp-tdcrlecapp-vpa-sk-
---------acp--al-------v--ayev-l--ce-n------------
-l--ip-nr---------------etplk-ievr
>node18
kf-----tirltrg----------vpi--veatqvla--------liakr
--ekyp-fhnf----h----d--mvniitl----------pa-kpnlr--
--npgkeslhg-------y---iggcvdrt---hagyka-k----a----
-----rllhily---aeeyfkpt-rcl--gqhaatr--v-ls--plhvh-
--p-dtkcga----------asy------v----dsrpv---ggyg--qe
lnraivs-----f---llag---dyna-ykkd--------cglfdgsevt
d---lnellpkpak--tggglmma--phltm--eamc-----csafaaal
tniklpgcqls-----tgtiine-----m--v-s-qqdr-ntq-d-dn--
-nkh-gygwp----------------qlqvh----l---mv--sh-----
---l-sgsglh-------g-nvk-------------rgpvvalvrgsd--
--------------a-rvsslhvlstsk--vsa--t-rfglnrsds----
------ieaf-----------eyvlt--glleaaer------emqsp--s
vek-yggaa-a-swtatttdard-------tewfvvfld----d--le--
--r----ihmeycm---e------ackc-gf-q------fdatmhsvh--
ea-tanalhdkhpft----kviyy----yhpesdpgqtdfapllqq----
--le-lpyknakvknr---s-sg-devkpydl-clvrsdt----------
------iepaganytvtdvyai-nddg--grdsdkr-----------sk-
-----------pktgf-------g--t-ev-l--cg-s------------
-q--fh-klpaf------------vlslkliptk
>ENV_HV2G1/23-502
kflhvpetirlksa----------vpi--veatqvka--------liakr
--eryp-fhef----h----g--svniitl----------pa-kpnl---
------eslhs-------y---iggcvsst---q---ka-s----a----
-----rilhily---aeeyfkps-mcv--aqhaatk--v-la--plhvh-
--p-dakcga----------asy------vls--dsrpt---fgyg--qe
lsrpivsklsilf---llag---eynl-ykkg--------cgifdnsevr
d---lnelkfkpak--t-gglmma--ghltm--eakc-----cstfaaal
lnfkitgcqls-----tgsiine-----m--v-s-eqdr-ntq-d-kn--
-nkq-gytwp----------------qlqvh----l---mv--sh-----
---l-sgsglh-------g-nlk-------------rnpvialvdssd--
--------------a-svsslhvisssk--vsa--a-wfglnrnea----
------ieaf-----------dyvlt--gllepver------emqsp--s
lek-yg--g-a-swtatitdsrd-------tqwfvvfld----d--le--
--r----ihldycm---etggnndacka-gf-q------fnatkhrvh--
ea-tanalhdkhpft----kvi-------hpendpgqtdfapllqh----
--ld-lnyknskvknr---n-sg-devspynl-cmvksdt----------
------iepagsl------------------dsdkr-----------sk-
-----------pstnf-------g--t-ev-v--cg-s------------
-q--fh-klpvf------------vlslkliptk
>node8
-g-----gkqleve----------i-----lend-la--------mvhkr
--skyk-fstl----y----e--mssaani----------pn-npnfk--
--segteslh-av---egy---igtcaqra---fpgyikek----h----
-----sl--------------pt-ncl--thhtgsg--v-lg--tlvrq-
kdrkag-cdg----------ake------ilgtlgssp----qgyp--q-
----ici-----ftig--hg---kyse-criegeawhlrepaiwsncett
ngvg-----trpvk--qgggmyls--ealkm--veli-----cgiftgt-
------------------tvvvg-----kpkt-k-qkgr-pkkse-dqla
lghq-tfgwqt--pk-qh--gklpgvvmpvq----h---mfaagr-----
---vgrgsgvq-------gnpvs-------------tlpgmsiergnd--
--rygq---ad---qn--asihvlatah--s-i--k---evkpahs----
------ie-y----------cgyiqviigtl---yqvae--ldlkea--a
vek-ngg---l-hwgftctdars-------lewll--------q--ai--
-ar----iaee--a---s------acma-pl-hf----yfedtthqvh--
da-avielhehgafg----avl-------pgdagsaqtpflpaeqa----
--ve-l---kekvsgs---n-al-ievdrsdl-nlvrsli----------
------lgpgganyp----ylk-tsgg--ss-tdcrlacppp-vkp-sk-
-----------p--al-------v--a-ev-l--ce-n------------
-q--ip-kr---------------atplk-ipvr
>node10
kf-----avrltrg----------vpi--veatqvla--------liakr
--ekyp-fhnf----y----d--maniiti----------pa-kpkfk--
--tpgkeslh--------y---iggcvdrt---hagyka-k----a----
-----rlihily---aedyfkpt-mcl--gqhaatk--v-ls--plhvh-
--p-dakcga----------ase------vls--dsrpv---ggyg--qe
lnraivs-----f---llag---dyna-ckkd--------cglfngsdat
g---lnelmpkpak--tggglmma--phlnm--eamc-----csafaaav
tdiklegcqls-----tgtiide-----k--v-k-qqdr-ntq-d-dn--
-nkh-gygwp----------------qlqvh----l---mv--sh-----
---l-rgsglh-------g-nvk-------------rgpavalargsd--
--------------a-svaslhvlstsk--vsi--t---glnrnds----
------ieaf-----------eyilt--glleaaer------emqep--d
vek-yggaa-l-swtatttdars-------vewlvvfld----d--le--
--r----iameyca---e------ackc-gf-q------fdatmhsvh--
da-eanalhdnrpft----kviyy----yhpesdpgqtpfapllqq----
--le-lpykkakvknr---s-sv-devnpydl-clvrsdt----------
------iepaganyt----yls-tdgg--grdsdkr-----------sk-
-----------pktgf-------g--a-ev-l--cg-s------------
-q--fh-klpaf------------vlslk-iptk
>ENV_SIVGB/47-569
--------------------------------ak-vekledfcwd--a-r
--enykt-giiapslffdsgygdt-----a----------gnkspeyafa
sgesekdfls-df---gty---ag-rtqsganvfaktltkhwvcaehsga
atkrevl--------------ptlkcv--avqnse---in-v--------
--mvqt-vad----------rtvvlawlcq------ca----keyp--t-
----ycv-----ymlp--r----vhsqe--------wlrq-qvyn--saf
dema-----vspevacnwadv--k--eypk----eki-----cin-----
------------------anl----------m-v-lkgk-ahkse-kqy-
sgkknqy------hks------lgqilireq----q---aalggsldltp
vlg----pgta-------gtqpl-------------plpcaavnvgaath
avtp-----lk---qp--lalylwpv------l--k---lvcrkfl----
------ka-c----------rgsteflvglv---sdqrqmd--srdaagg
nhk-qpa---q-n-------akg--vapik--ali----v---g--aa--
-tk------------------------qvel-qitgsey--mttlrea--
nsgavvalfrkhaig----a-l-------gh--------------p----
-lkl-v---ketvsgg---tq-l-tpf------svisftvgsvkgaaqff
dstasflgifds--------grv----------gcahkckra-lrva---
---------------ilqakfrlg-q-----l--cvmskdfllytpepeg
-dlyvppga---phgdknqkkkqisgnfe-tpl-
>node14
kf-----tirltrg----------vpi--veatqvla--------liaar
ktekyp-fhdf----h----d--mvniitl----------pa-kpnlr--
--npgkeslhg-------y---iggcvdrt---hagyka-k----a----
-----rllhvly---aeeyfkpt-rcl--gdhaatr--v-ls--plhvh-
--p-dtkcga----------asy------v----dsrpv---ggyg--qe
lnrails-----f---llag---dyna-ykkd--------cglfdgsevt
d---lnellpkpek--tggglmma--phltmlieavc-----csafaaal
tniklpgcqlp-----tgtiine-----m--i-s-qqdr-ntq-d-dn--
-nkh-gygwp----------------qlqvh-aktl---mv--gh-----
---l-kgsglh-------g-nvk-------------rgpvvalvrgtd--
--------------a-rvsslhvlstsk--vsa--t-rfglnrsds----
------ieaf-----------eyvlt--glleaaer------emqsp--s
vek-tggaa-asswtatttdard-------teffvafld----e--le--
--r----ihmeycm---e------vckc-gf-q------fdatmhtvh--
ea-tpsalydkhtft----kviyy----yhpesdpgqtdnapllqq----
p-le-lpynnakvknr---s-sg-devkpydl-clvrsdt----------
------iepaganytttdvyai-nddg--skdsdkr-----------sk-
-----------pktgf-------g--d-ev-l--cg-s------------
-e--fh-klpaf------------vlslklipts
>node9
kf-----avrldkg----------vpi--veatq-la--------liakr
--ekyp-fhnf----y----d--maniati----------pq-kpkfk--
--tpgkeslh-vi-----y---iggcvdrt---hagyka-k----n----
-----rlihaly---aedyfkpt-mcl--shhagtk--v-lt--tlhvhg
kgpadakcga----------ase------vls--drrpv---kgyg--qd
lnrgivp-----f---llag---dysa-ckmd--------cglfngsdat
g---lnelmprpak--tggglvma--phlnm--mami-----csafagaa
adiklegcqls-----tgtivde-----k--v-k-qkdr-itq-d-dnlp
lskh-gygwp----------------qlqvh----l---mv--sh-----
---l-rgsgvh-------g-nvg-------------kgpgvaltrgsd--
--------------a-svaslhvlstsk--vsi--t---glkkkds----
------ieaf----------ceyilt--glleaaervae--aemqep--a
vek-yggaa-l-swtftttdars-------lewlvvfle----d--lv--
--r----ialeyca---e------acka-af-q------featmhqvh--
da-eaialhdnrpft----kviyy----yhpesdagqtpftpllqq----
--le-lpykkakvkhr---p-sv-devnpydl-vlvrsdt----------
------lepaganyt----yls-tdgg--srdsdkk-----------tk-
-----------pktgf-------g--a-ev-l--cg-s------------
-q--fh-kkpvf------------vlslr-iptk
>ENV_HV2NZ/24-502
k------tiklnrg----------lpy--vestqvla--------lvtrr
--dqyp-fhay----h----n--gvniatl----------pg-kanlg--
--d----slag-------ymlfiggcvaka---hv--ka-k----a----
-----rllhily---aqeyfkps-rcl--gqh---------g--plhih-
--p-dskcea----------asf------l----dsgpv---ggyg--qe
lnrarls-----f---evas---dynn-y--d--------cglfdgsdvt
d---lnelltnpak--ta---------hmsm--elmc-----ctnfaasl
tklklpgcqls-----sgtiine-----l--t-a-qqdi-nth-d-dn--
-nnq-gygwp----------------qlk------l---me--sd-----
---l-sgsglh-------g-dvk-------------rgpvvalvrgae--
--------------a-rfssptvlstsk--lsa--asrygltrr-s----
------ieaf-----------eyilt--glllagaq------emhsp--s
aek-ygaap-g-swtatdtdasd--------dwfvvfle-------letv
f-r----ihaeycl---e------ackc-df-q------fetpmhsvh--
na-tanslhskhp-d----siiyy----yhpatapgqadftpvlqqhscs
--lemlpykn---kgr---t-sg-nqvkphnf-clvrsdt----------
------lepsgstytvt-vyal-dddg--v-dddkr-----------sk-
-----------pktgf-------a--t-ev-l--cg-c------------
-l--fq---ptg-------------------ptk
>ENV_SIVV1/24-538
-t--------lnaeyvwyaassilg-----lqsd-lv--------mvhkh
--kkyd--aad----f----a--mvavstl----------gy-dptfk--
--avgvdpld-nllnkegy---vgacaken---fsg----k----p----
-----sf--------------ec-dclpltthsgsg--i-vn--al----
asknsg-cdn----------tea------------g---vdirsys--q-
----dcv-----naih--hg---kytd-crpqgdhwhysanevstt--av
dgvs-----ar---------myis--gaiqm--velk-----cptftgs-
-----------nfwf----------------t-a-qkgdvatknq-hqlv
cgyq-tlgwqt--nk-vnyagklpgvtmpce----hil-mfaggr-----
---vr--sgvs-------gnala-------------alpgk-lertnd--
--gyskmvypddgthg--av----sdah--h-lm-----elkpanm----
------le-y----------agy-----gal---fpige--lslkee--c
lvkksgg--el-hwg-------g-------i-------------------
-grgqklianq--a---g------aclt-am-ky----ylndtdqhfhac
da-ts-n-----hfg----gva-------pad-gssqapflgs-ea----
--vd-----ktnvsgpdnc------eperetl---ekglv----------
------aeggig--------lk-assivs-p-secrrhcapp-vpp-kk-
---------aca--gv-------v--aydv-l--ce-d------------
-l--vp-dr---------------etplk-ievr
>node17
kf-----tirltrg----------vpi--veatqvla--------liakr
--ekyp-fhaf----h----d--mvniitl----------pa-kpnlr--
--dpgkeslag-------y---iggcvdrt---hvgyka-k----a----
-----rllhily---aqeyfkps-rcl--gqh---------s--plhih-
--p-dtkcga----------asy------i----dsspv---ggyg--qe
lnrarvs-----f---llag---dyna-ykkd--------cglfdgsevt
d---lnelltnpak--tggslmma--phltm--eamc-----csafaaal
tniklpgcqls-----sgtiine-----l--v-s-qqdr-ntq-d-dn--
-nkh-gygwp----------------qlqvh----l---mv--sd-----
---l-sgsglh-------g-dvk-------------rgpvvalvrgad--
--------------a-rvsslhvlstsk--vsa--ttrfglnrsds----
------ieaf-----------eyvlt--glleaaer------emqsp--s
vek-yggaa-a-swtatdtdard-------tewfvvfld----d--letv
f-r----ihmeycm---e------ackc-gf-k------featmhsvh--
ea-tanalhdkhpft----riiyy----yhpasdpgqadftpllqq----
--lellpyknakvknr---s-sg-devkphdl-clvrsdt----------
------iepagsnytvtdvyai-nddg--vrdsdkr-----------sk-
-----------pktgf-------g--t-ev-l--cg-s------------
-q--fq-klpaf------------vlglkliptk
>ENV_HV2BE/24-510
kf-----tirltra----------vpi--veatqvgg--------llaas
ktekyt---ef----h----d--mgntmtlgdsynapdtppk-tpnvr--
--npgkeclhg-------y---iggcvnr-----anykt-k----a----
-----tlwkily---aeeyfhpt-rcl--gdhadtrlqv-ls--plhvh-
--p-dtkcgg----------asy------v----gsrpv---ggyg--qq
wnralls-----f---lwag---dy-----kd--------cglfngsevt
d---lndllpkpek--tggglmgg--phitmlveavc-----csafatpl
tilkipgcqlp-----p-tiine-----m--c-s-qqdr-naq-d-dn--
-nkh-gynwp----------------qlqmh-aktl---mv--gh-----
---l-kgsglhvgsnglsg-nvkhaisalrgvhlairgpvvalvrdtd--
--------------t-kvaalhvlsttm--vsq--t-rfglnrdds----
------keaa-----------eyvlt--klkeaaer------emqsp--g
gik--ggta-asgwtsttadard-------taffvsfld----e--lk--
--r----ihmeycm---e------gckc-gf-q------fdatmdtvh--
ea-tpgtmydkrtft----kviyy----yrresdpgqswngkllqq----
g-le-lpynnakvkak---s----sevisydlvclmrsdt----------
------iepasadctctdvypi-neng--sknsdks-----------sr-
-----------plvgf-------g--d-ev-i--cg-n------------
-g--fh-klpaf------------vlslkldpss
>ENV_SIVG1/22-522
-g-----gktldve----------v-----leyv-la--------mvhrh
--skyn--stg----y----a--mesaakl----------pf-dpafk--
--svgaedls-avl-kdgy---igafakqa---fegyikdk----l----
-----sf--------------pi-dcl--tnptgrg--v-ag--alvre-
anrkag-csd----------aes------------ssp-vdlqg-a--p-
----ici-----ntda--nk---kyge-csieghawsfsenevwst--ta
ndvg-----dr---------myvn--gglkl--vdli-----caiftdt-
------------------svvvg-----kpnt-k-ekgk-pkkse-dqla
ighp-tfgwvtcgp---h--gnlpgvtlpcd----hilvmfaagr-----
---vrnfsdvq-------gnpvs-------------tlpglsiektqe--
--kysg---qe---rg--an----ataq--t-lmpk---dvkpahlaaap
hllfasik-ytvsalcvalqcgyvqvi-------yqiqd--lnlkev--c
tek-pag---l-hwnlhctdlrgkp-----idwlf--------qpntl--
-de----ivnq--a---g------acla-gl-kf----yfddtdhhvh--
ea-ts-nlheqgafg----gvl-------pag-gsnqipflga-qa----
--ve-l---kenvsgg-------a-eldrldl-nmvkgli----------
------lapggekyp----ylr-asgg--sp-ldcrlsceppelps-dk-
---------acp--gl-------vv-aynv-lvgce-n------------
-l--ip-nr---------------ekslk-invr
>ENV_HV2CA/25-512
kf-----tirplrg----------vtl--veathvla--------liakr
--dkvp-fhlf----h----d--kaaivtl----------pa-kpnlg--
--gpskpslag-------y---tggcvert---hvglig-k----a----
-----rlhhily---aqeyvkps-r-l--gqh---------a--plhfr-
--p-dtkcga----------aay------l----easpv---gkyg--qe
lnrprva-----f---ll-g---dyna-ykke--------sglfdtsqiq
d---lnellsdpak--tggsllma--phlpm--eaec-----cspfaaal
tdiklpgcqls-----sgtiine-----l--v-stqqds-ntq-d-dn--
-kkn-gygwp----------------qlqvh----l---iv--sd-----
---l-sgsglh-------g-d-k-------------rapvgqlvrgad--
--------------a-rvtdlhvwstsk--vca--atkfglnhsen----
------inaf-----------qyvlt--gllkkver------etqsp--s
idk-yggas-a-swtatdtdare-------sewfevfld----d--leav
f-r----ihmtycmydgq------cckc-gf-s------leatmrgvh--
ea-tana-fqkhpftqgavriiyy----ytpasdpgqadftpllqq----
--lellpfmnskvtnr---s-pg-devkphhl-cliksds----------
------iepagsnftvvdvfsi-nddg--vkdgdkr-----------nkn
spqtakaai--pkkgf-------g--t-ec-l--ca-e------------
-a--fq-klpaf------------vlslklvptq
>node11
kf-----tirltrg----------vpi--veatqvla--------liakr
--ekyp-fhnf----h----d--mvniitl----------pa-kpnlk--
--tpgkeslhg-------y---iggcvdrt---hagyka-k----a----
-----rllhily---aeeyfkpt-mcl--gqhaatk--v-ls--plhvh-
--p-dtkcga----------asy------vls--dsrpv---ggyg--qe
lnraivs-----f---llag---dyna-ykkd--------cglfdgsevt
d---lnellpkpak--tggglmma--phltm--eamc-----csafaaal
tniklpgcqls-----tgtiine-----m--v-s-qqdr-ntq-d-dn--
-nkh-gygwp----------------qlqvh----l---mv--sh-----
---l-sgsglh-------g-nvk-------------rgpvvalvrgsd--
--------------a-svsslhvlstsk--vsa--t-wfglnrnds----
------ieaf-----------eyvlt--glleaaer------emqsp--s
vek-yggaa-a-swtatttdard-------tewfvvfld----d--le--
--r----ihmeycm---e------ackc-gf-q------fdatmhsvh--
ea-tanalhdkhpft----kviyy----yhpesdpgqtdfapllqq----
--le-lpyknakvknr---s-sg-devkpydl-clvrsdt----------
------iepaganyt----yli-tddg--grdsdkr-----------sk-
-----------pktgf-------g--t-ev-l--cg-s------------
-q--fh-klpaf------------vlslkliptk
>ENV_HV2D1/24-501
kf-----tirltrg----------vpi--vdvtpvlv--------liagr
ktnkyp-fhdf----h----d--mvniiti----------pa-kpnlr--
--ipgkqslhg-------y---iggcva-s---hdgyka-k----a----
-----rllqvly---aeeyfypd-rcl--gdhaatr--v-lt--plhvh-
----dqkcgavhvlllhpnrvsy------v----dsrpv---agyg--qe
fnrails-----f---vlag---eynv-krkd--------cglfdaseit
n---lnellpkpek--sgcglmma--phltmlieavc-----csafaagl
tniklpgcqlp-----tgtiine-----m--v-s-qqdr-ntq-didn--
-n---sygwp----------------klqvhlsktl---iv--gh-----
---l-kasglh-------g-nvk-------------agavvslvrgte--
--------------a-rvsslhvlgtsk--vsa--t-rfplnrsdt----
------ieaf-----------dyvlt--dllnaper------emqst--s
ves-tggaa-as--tatttdpta-------leffvgfld----e--le--
--p----ihmeycm---e------ackc-gf-q------fdatmhtvh--
eg-kpsalydrhtft----kviyy----yhsesdpgqtekatllem----
s-ae-lpynnakvknr---s-ng-devkpydl-crvrsat----------
------ieplganytttdfyai-hddg--skdsdkr-----------pk-
-----------pnggf-------s--d-ev-l--cg-s------------
-e--fh-kleaf------------vlslklipts
>node19
kf-----tirltrg----------vpi--veatqvla--------liakr
--ekyp-fhnf----h----d--mvniitl----------pa-kpnlk--
--tpgkeslhg-------y---iggcvdrt---hagyka-k----a----
-----rllhily---aeeyfkpt-rcl--gqhaatr--v-ls--plhvh-
--p-dtkcga----------asy------vls--dsrpv---ggyg--qe
lnraivs-----f---llag---dyna-ykkd--------cglfdgsevt
d---lnellpkpak--tggglmma--phltm--eamc-----csafaaal
tniklpgcqls-----tgtiine-----m--v-s-qqdr-ntq-d-dn--
-nkh-gygwp----------------qlqvh----l---mv--sh-----
---l-sgsglh-------g-nvk-------------rgpvvalvrgsd--
--------------a-rvsslhvlstsk--vsa--t-wfglnrsds----
------ieaf-----------eyvlt--glleaaer------emqsp--s
vek-yggaa-a-swtatttdard-------tewfvvfld----d--le--
--r----ihmeycm---e------ackc-gf-q------fdatmhsvh--
ea-tanalhdkhpft----kviyy----yhpesdpgqtdfapllqq----
--le-lpyknakvknr---s-sg-devkpydl-clvrsdt----------
------iepaganyt----yli-nddg--grdsdkr-----------sk-
-----------pktgf-------g--t-ev-l--cg-s------------
-q--fh-klpaf------------vlslkliptk
>ENV_HV2D2/24-513
kf-----avrlsrg----------vpidgvdasqvl------------mr
--atyp-fgnf----y----d--manviai----------pa-kpnfk--
--tpakgylh--------f---lggcve--------yra-k----a----
-----ilihvly---a-a--kqt-lcl--tqfatgk--v-as--pidvh-
--p-nehcaa----------lpe------vl--------------gpaqk
lnrnvvp-----f---llag---dyds-ckkd--------cglfnasnst
g---lndamskrak--tggdlmqapvptldv--eamc-----csgfaaai
iaikmaacpls----ftgtiine-----k--v-k-qqdr-htq-d-dn--
-nka-aygwp----------------glqih----l---mv--aq-----
---l-rts-------------vk-------------rnpavargrggg--
--------------a-avsslnvldtskevt----s---gptrsns----
------iqay-----------ifila--gllegdnr------emlep--d
vek-fdavv-l-kwtatttdart-------vewlavyle----d--vq--
--r----iaseyca---e------tckc-nfdr------fea--vdvh--
ea-ennalhdnrcfs----kaiyy----yhpvsnpgqtpfgalsqd----
--re-lpykkakvkdr---g-sv-aevdpynl--llgsda----------
------eepappdyk----ylt-vdgg--grdsdkk-----------sk-
-----------pktgf-------g--a-eapm--cg-s------------
l---ih-klfs-----------------k-ists
>ENV_SIVM1/24-528
----------lnka----------vpi--aeavq-la--------liakr
--ekyp-fhnf----y----a--vanvsti----------pq-apk-k--
--tpqkdslh-vi-----y---iggchirt---hagfkg-k----n----
-----rlinalyfghsedyfnpt-mcl--shhagtk--v-ltttilhvhg
kgpadskcgs----------aae------vlt--drrpv---kgyg--qd
lnmg------------llpgipqdysa-akmg--------cgifdgsdat
p---lnglmprpak--tggglvma--pplnm--mamvhtltvsaafakaa
adrklegcels-----tgtvvdeargrgk--vd-----------d-dilp
vgkh-gygwp----------------qlelh----l---mv--sh-----
---l-vgsgvh-------g-nvg-------------rgpgvaltkssd--
--------------a-svaslnvlslsk--vsi--t---glrkkdv----
------ieaf----------ceyilg--slleaaervse--sdmqep--d
vdk-yggaa-l-swtfttadart-------lewltvfla-ltcd--lv--
--r----ialdyca---e------nckm-af-q------featmhavh--
da-eaialhhdrpft----kviyynkwayhsetdagatpftrllqq----
--le-lpyknakvkhr---p-sv-devdpydl-vlvrsdv----------
------lepa----t----yls-tega--srdsdkr-----------tk-
-----------yktgf-------g--a-nv-l--cg-s------------
-q--fh-kkpvf------------vlslr-vptk
