>ENV_SIVGB/47-569
drfsas----------qtqsddydk-----eag--------------tqs
khkgclgqqcpqttkkgdkadkggcpes------------y-ep------
-------hrslncgkgd-stplkeenlmygkkgkkgngvanl-lgpsg--
-ksrei--av--------------------------ei-vwrvhs----y
---pv-------dn--pf--hmrle-gas-sgfgwqdr-e-skpvk-lt-
-rklgdaqr-statdvgye-------aflmqnpngaqpctr----g---f
tepnskeapyldkare--m--qnpsmrc--tslekrgaditeaiqvcety
ssqsavvs-l-------------------------dcanyiiig-sv--k
vyvesples--lgkwrfggr---tv----nnwvcls---akvac-givpg
rmamtgc-------tegf---k------yqplhgdd-----dk-------
cetsyvl--mgmilivlqgdqppaf---sg--------------kyllap
ehtgqnqt---r--v---------------pvf--hl-kfsaskn-----
-im--i--------------------------dasday------------
----------a---dglmevakfpkngkgckc----t-v--eksi-----
----i--l-prdvespcsatkpkyqpesgypvegvnscgerilgeancyk
keealalawcvgtenapvgsf--mekleha-evrs------------kna
h-qn-kshr--kgrmdlvs-hyy--------------hamfkye------
----------t-epeslgffinphytsarssdktpgvirsr-etcdig--
---------------i------------------giwpvgialr--pf--
-s------------d-----taa--------------dn-----------
---lggptlpggvnnsgal
>ENV_SIVV1/24-538
----akai-------vheangndstqrwv-dlklscpfpaprlclcf---
------------------i------a-pvqmad--sgkfqfvvl------
-------d--------p-fgask-----tty-----------clpaha--
-igafg--ii---ae----------fk-------sgqrlqwaedvrvivy
---nv----gtkea--rf--qw---ngei------nalctgc---a-sna
tayltpklp-ggeha-----------ss--------lgmlwspats----
----------hadkllalh--kp---ta--gti------------lpasy
ik----qt-gillvvtpkeqegrsvcathaig---q--gnifgi-ad---
---------ge-k----agrsrs--vsafqps-cvtg--gsg--------
----------w---r--g---------gydalrgk--------llkpfpa
a-----feskdth------v-----pk-enp----------as-raf--e
thym----arta--d---------------tdpllq-ldhaspita--ki
ekkakis--spyfh---erg---adf-----esvik--------------
----------e---d----------------c----lyk--vliypkvdv
cshl-qelrkkg-------tqea---------------------kvdc-n
pd-------------------qasalveqa-avtmasska---k-gsmyk
h-ld-ikqggkakaeelvg-lffrsespdnesignashnrppt-------
------------tgekdkavcspay--------tga-mttq--kyrip--
---------------ah--------------asdkysskwgvyr--si--
-t-ek------n-yk-----a-------ilghfll--ts-----------
-------------------
>ENV_HV2NZ/24-502
----argdia-ykfgvhlardqkqs--wiskra-----------------
------------------i------gsi----t--dgklkf-ev---cit
hpafgshe--------q-facck-----kqy-----------cltapa--
-legi-gwkl---lg-------kttfkvmhyfvd--hvyawqqstr---l
---hi-------kg--ny--el---gge--------skcdps---h-l--
-rhltsiaf-taelva---s--qlkhtf------vpsar-----------
-----------aehrrvii--ea--ivg--gik------------q-pry
rr----vn-fi---------------------------ghfah-dk-av-
---------a-v-qwregsrnqkvn----qnc-cika------c------
-----r-ks-----r--g---s-----gyvsvrtgt-------p--ks-a
k-----m--avph------s-----saa-sggriv-vrcnsgktrgl--d
gefg----prggltkli---------gdfiesg--g-ivlsllvi---na
qklrnfk--sayyvleqahr---p-c-----nlaisaf------------
----------d---d----------------c----t-kaptgnf-----
-----hsidtk--------trantg--gkk-vvt---------gtkdkyt
e------------------------llecv-wlskavevaktal-gvkst
k-pa-ktrn--hagvklv-mvff----ver-------gskppgs------
----------a-isdvkkaivqpts---------------k-rncnvstt
--srdatenddfrlyphned--ksptgasriegsq-wpttgslrfipvsk
klrkdfnlkgqg-ks-rgkfggdrl----------pansaarcpfhgyck
pag----------------
>node11
----argdiv-hkfavhlardkkes--wiskka-----------------
------------------r------gsv----t--dgklkf-ev---yit
hpa----e--------q-facck-----rqy-----------clttra--
-ldgf-twel---lg-------ktsfn--------ahvyawdqgtrvatl
---hi-------kg--hy--ql---gges------dskcsps---h-l--
-rhltnmal-daesvp---k--qlkhtf------vpsav-----------
-----------sdrrhvii--ep--ivv--glk------------p-pky
rk----va-fi--vs----------------nivgl--gnlkn-dk-dv-
---------a-i-qwrggsrdqkvn----eac-cina------c------
-----r-ts-----r--s---a-----gyvslrvgt-------p--kt-t
s-----m--avph------t-----saapgaariv-vrrhsgktrgl--d
gdya----praglanlk---------gd--ksg--g-ivlsflam---na
qklrdlk--sayyvleqaht---p-y-----nlvmnai------------
----------d---d----------------c----t-kalaglf-----
-----hsvdsk--------trtatg--gkk-vvn---------vtkdiyt
t------------------------llecv-sldmaadvaktal-gvkst
k-pa-rtrd--hagvklv-mlff----vekvslsdtggtmppas------
----------t-isdvekaivdpts---------------k-rkcnvstt
--srn-----dyrlyvhned--kdpagasriegtqywptagtlr--pv--
-lcknfnlkgqg-ks-wgkfssdrl----------pchsaarcpfhgy-k
pag----------------
>node14
----argdlv-hqfavhlardkkes--wiskka-----------------
------------------r------ggv----t--dgklkf-ev---hik
hpa----e--------q-facck-----rky-----------clttra--
-ldgf-twel---lg-------ktsfk--------ahvyawdqgtrvatl
---hi-------kg--hy--ql---ggqs------dskcsps---h-l--
-rhltnmal-daesip---k--qlkhaf------vqsav-----------
-----------tdhrhvii--ep--ivv--glk------------t-pky
rk----va-fi--vs----------------nivgl--gnlkh-dk-dv-
---------a-i-qwrggsrdqkvn----eac-cina------c------
-----r-ts-----r--s---a-----gyvslrvgt-------p--kt-a
s-----m--avph------t-----seapgaariv-vrrhsgkttgl--d
gdya----praglanlk---------gd--ksg--g-ivlqflam---na
qklrdlk--sayyvleqaht---p-y-----nlvmnain-----------
--------vad---d----------------c----t-knlvgvf-----
-----hrvdsk--------traatg--gkk-vvn---------vtkdvyt
t------------------------llecvysldfaadvaktal-gvkst
ktga-rtrd--hagvklv-mlff----vekvslsdtggtmppaaefihlv
chphysyvtft-csdvekaivdpts---------------k-rncnvstt
--srn-----dyrlyvhned--kdpagasriagtqywptagtlr--pv--
-lcknfnlkgqg-ks-wgkfssdrl----------pchsaarcpyhgy-k
pag----------------
>ENV_HV2D1/24-501
----argdlvdhqfavqlgrdkkda--weskka-----------------
------------------r------ggv----g--d---kf-ei---hik
hps----e--------e-faccn-----kky-----------clttra--
-adgf-swel---lg-------knsfk--------anvyawdqgtrvlsl
---hi-------ng--hy--ql---vgqs------dskcsvs---h-l--
-rhltdmal-naesvp---k--qlkhaf------vqsav-----------
-----------tdhrhvli--ev--llv--glk------------t-pkf
rk----aa-fi--is----------------givgl--gnlkh-dk-dv-
---------d-t-qwqggswdqkvn----eac-cisd------c------
-----r-is-----r--skfta-----gyvslrvgt-------p--kt-a
s-----m--avph------a-----sgapgrar-v-vrrvrgnttg----
------------lanlm---------gd----g--g-iilk--------s
qklrdlk--sayymleq-ha---p-y-----slvsnait-----------
--------vpd---d----------------c----s-knlvgvf-----
-----yrvdsk--------traasg--gyk-av----------vekdvyt
t------------------------lshcaynl-ipaavaktgl-gvkki
ktgq-rtkd--hagvklv-m-----------slsdaggimppaiefihlv
chvhygyitlt-cadvedeivdptt---------------klrkcnvslt
--srn-----eyrlyvhntd--kdpggasriagtqywrtagtlr--pv--
-lcknfdvkgqg-ks-wgkfssdrl----------pcnsaarcvyhgy-k
qag----------------
>node17
----argdia-ykfavhlardkkqs--wiskka-----------------
------------------r------gsv----t--dgklkf-ev---yit
hpa----e--------q-facck-----rqy-----------clttra--
-ldgi-twel---lg-------ktsfnvmhhfvd--hvyaweqgtrvakl
---hi-------kg--hy--ql---gges------dskcdps---h-l--
-rhltsmal-daesvp---e--qlkhtf------vpsak-----------
-----------tdhrhvii--ep--ivv--glk------------p-pky
rk----va-fi---------------------------gnlkn-dk-dv-
---------a-i-qwrggsrdqkvn----eac-cina------c------
-----r-ts-----r--s---a-----gyvslrvgt-------p--kt-a
s-----m--avph------t-----saa-gaariv-vrrnsgktrgl--d
gdya----praglanla---------gd--ssg--g-ivlsflvm---na
qklrdlk--sayyvleqaht---p-y-----nlvlnai------------
----------d---d----------------c----t-kalvglf-----
-----hsvdsk--------traatg--gkk-vvt---------vtkdiyt
t------------------------llecv-wldmaaevaktal-gvkst
k-pa-rtrd--hagvklv-mlff----vekvslsdsggsmppgs------
----------a-isdvkkaivhpts---------------k-rncnvstt
--srd-----dfrlyihned--kdpagasriegtqywpttgtlr--pv--
-lcknfnlkgqg-ks-wgkfsgdrl----------pchsaarcpfhgyck
pag----------------
>ENV_HV2CA/25-512
----argdia-fkfavhlqrdkdqg--wishka-----------------
------------------r------gsv----t--dgklkf-nv---yit
hga----e--------q-facck-----rqy-----------clttgv--
-legi-twelytnlg-------kthsdvmhhfvd--hvfewemgirvikl
---hp-------kg--ha--ql---agds------dtkcdqv---ngl--
-rhlkslal-dgesvp---e--hvkntr------lpkak-----------
-----------tdqrhvvi--ep--ivv--glt------------p-pky
rk----va-fl---------------------------dn-kn-dk-dv-
---------a-i-mwtgggreqeve----eac-cins------c------
-----r-ts-----r--s---a-----gyvsfragt-------p--r---
-----------ph------t-----sar-eavriv-vrrnsgktrgl--d
gdva----pragaenla---------gi--ssg--g-ivlsflit---da
pnlrelk---ayyvledaha---p-y-----alvlkpi------------
----------dqlpd----------------c----t-kalinlf-----
-----qahdsk--------traatg--akk-vvt---------vvkdiyt
t------------------------llecl-wldmaaevaksal-gvksp
k-ae-rtpd--faggklv-glf-----pekvsssdsggsmppgs------
----------a-isevkkeivipns---------------k-pncnvstt
--n-e-----efrlyihned--kdpagtpriegnqywpttgtlr--pv--
-lvknfnlkgqg-kg-wgkfagerl----------pcesaarcplhgycp
sag----------------
>ENV_HV2BE/24-510
----vmgdlv-qqfpthltrekkds--sikkka-----------------
------------------r------ggg----t--qgklkf-ev---hvk
qpa----e--------q-faccn-----kky-----------cltnra--
-ldgf-nwev---lg-------htsfk--------ahvyawdqnakvapl
---hi-------kg--hy--ql---ggqsi-----dpkcsps---n-l--
-rhltnmalleaervp---k--qlkhaf------iqsai-----------
-----------tdhrhvif--ep--ivv--glk------------t-pky
kk----iaafi--at----------------h---q--ntlkh-dk----
-------------qwrgggrsqktn----eac-cina------ck-----
-----r-ts-----r--s---a-----kytslrvgkagtvk--p--kt-a
s-----l--avph------t-----yeapgaaril-vkrhkgkttgl--d
gdya----pkaglenln---------rd--kg-----lvlqflam---na
qklrdlk--styfvleqaqt---p-y-----nillnainllasstgaivs
fpakiaepvad---s----------------c----t-nsligvf-----
-----hriktk--------arattg--gkk-vvd---------vtkdvyt
t------------------------llecvytldfaadvaktal-gakav
kt-a-ptrd--hagvklv-mlff----lekvslsdtggtqppaaegphlv
cwphysyvtft-csevnkavvdpts---------------k-knc-----
-----------yrvyvhked--kdpasairiagaqywptagtir--pv--
-sckn----gqs-ks-wgkfnndr-----------------rcp-qgy-k
pag----------------
>node7
----gkni-------vhqakgkssthiwv-dli-----------------
------------------i------p-p----t--dgkfqfval------
-------d--------q-hagak-----taf-----------clnaha--
-igafg--hi---de----------fk-------dgqvliwnqdsrvvvy
---tvkakqgkkda--ry--qw---ngeq------delctst---a-ls-
-ryltpmmp-ggepdl---k----kqsf--------qgvlw----s----
----------ladkrlavv--kp---va--gli------------isasy
ik----ht-pi--vv---------------ivlt-h--envfai-th---
---------g-ik----agrsqnigvkdfqps-cvtg--asn--------
----------w---r--g---------gydglrgk--------llnplpt
a-----f--knpf------v-----ak-gap----------as-rgi--e
thya----prtg--e---------------kns--q-lkhsspvts--rl
hkkkkis--spyfh---esg---aef-----enlmk--------------
----------e---e----------------c----tyk--vliyakvsv
chgl-qtlrtkg-------tsta---------------------kadc-k
pd-------------------qanalldqa-avmmsspsa---l-gsmyt
h-le-ikqgnsaealelmg-lff----pdevslgnaghsrapts------
----------t-agetdkvvcnpay--------taa-vktr--kcaik--
---------------ah--------------asdkfwgtwstfr--si--
-t-nk------g-yr-----a-------ilghfll--ts-----------
-------------------
>ENV_HV2D2/24-513
----adgdiv----aahlerdknes--wlekrd-----------------
------------------r------gpv----cyrdgplkf-kgiieyit
hsa----e--------h-fgcpk-----vqy-----------cltqra--
-ldgf-twel---lskkrg---kisfs--------a--yawdqgtrlvtl
---hi-------daanhy--ql---ghes------ankcsps---h-m--
-rhltnlgl-qaettq---kwhhlkqtf------vpsdt------sggq-
----------lsdrrhviv--qp--ivittglk------------p-pky
pt----va-fk--va----------------nmigv--eeldn-eq-dv-
---------a-i-ewrggsseqkid----ea----nq------c------
-----r-kpngs--r--s---kltgtgtyvslrvga-------p--tt-t
l-----v--yip-------a-----taapgtariv-grrnsgklrgl--d
gnym----prkgfadlk---egtqigge--kag--g-ivlsflav---na
gklrdsd--ttyyv--paht---p-ynvghlklimnei------------
----------d---k----------------c----n-kalaglf-----
-----hgvdsr--------trtate--gkk-vvv---------vtddiyt
te-------------------imhallecv-qltmtanvvkpalqgvent
k-la-rthd--hsgakmv-migf----vekveismsggrmppad------
----------s-isdvqksivdptt---------------k-qkceitta
--cks-----tyrlflhgkn--kaptgvsi-----fwpvsgtlr--al--
-lcmnfnlkgqg-krawvkftsdrv----------pchsatrcpf----k
pag----------------
>node8
----gknl-------vhqakgkssthiwv-dsi-----------------
------------------k------spp----t--dgkfqf-al------
-------n--------q-hadsk-----tgf-----------clnaha--
-igafn--hv---de----------fk-------dgqvlvwnqasrvavy
---lv-------da--ry--ql---nges------dekcapt---t-ls-
-ryltsmap-ggepdl---k----khsf------vvegvlw----s----
----------ladrrltiv--kp--iva--glm------------isasy
rk----vt-ai--vv----------------tlt-v--enitai-th---
---------g-ikkwrnagrdqnvg----eas-cvng--atnqc------
-----glradw---r--g---k-----gydglrgsd-----gqllnnl-t
a-----f--ygpf------v-----at-paa----------ak-rgi--p
ehya----prsg--a---------------kng--r-lrlsspvtk--nm
hkkkkis--spyfh---eps---ady-----nnimkpy------------
----------e---e----------------c----t-k--eavf-----
-----qtlrttg-------trattepngdk-vqn---------fgadcfk
pd-------------------lvkalldqa-svmmsapsa---l-gskft
h-le-ikqg--aealellg-lff----pdevslgqaghnmaptp------
----------t-agetdkvvvnpay--------tpa-vrtr-gkcevk--
---------------vh--------------egnkfwessaefr--pi--
-t-nk------g-kr-----sdnpfledimghfll--ts-----------
-------------------
>node9
----argdiv-hnfavhlardkhet--wisdka-----------------
------------------r------gpv----t--dgkldf-ev---yit
hka----e--------q-fadck-----ady-----------cltsrs--
-ldgfttwgv---ng----------fk-------nahvyawdqttrvail
---hi-------dg--hf--ql---gges------ddkcaps---h-l--
-rhltnmal-daeavp---k--qlkhtf------vpsaviw----sggl-
----------ltnrrhvii--ep--ivv--glk------------p-pky
rk----va-fi--va----------------nlvsv--aalss-dt-ev-
---------a-i-kwrggsrdqkvn----eas-cvna------c------
-----r-ksdgs--r--s---k-----gyvslrvgd-------a--kv-t
s-----m--fvpf------t-----saqpaaakig-irrhsdk-rgl--d
edya----prsgfaalk---------gd--ksg--g-lvlrflam---nm
qklrdtk--tpyfv---aht---p-y-----nlvmnai------------
----------d---d----------------c----t-kalkglf-----
-----hsidskg-------trtataphgkk-vvn---------vtkdiyt
te-------------------lthalleca-sltmtadvakaal-gskst
k-la-vtrd--hegvklv-mlff----iekvslgdaggnmppas------
----------s-vgdaekaivdpas---------------k-rkcnvttt
--crn-----dyrlyvhnnnsqkdpagasscegtqywqtagdfr--pv--
-lckkfklkgag-kr-wgkfssdplfddiahhfll--hsasrcpfhgy-k
sag----------------
>ENV_SIVM1/24-528
----argdlv-hnfqshlardghet--wisdka-----------------
------------------r------gpv----t--dglldf-da---yit
rka----q--------h-fsdck-----tdy-----------cltsrs--
-legyttwnv---ng----------fk-------sahvyadnqntrvavl
dacpi-------da--hf--al---gg----------ncaps---h-l--
----enmal-dadavp---k--qlkhtf------vptaviw----sggl-
----------ltnrrhveifiep--ivv--glk------------p-pky
ik----va-fi--va----------------hlvsl--aalaa-et-dv-
---------a-k-kwqggsrdqkte----eas-cvna------c------
-----r-asdgs--r--s---k-----gyvflrvge-------a--kv-t
g-----m--fvpf------t-----cahpaaakig-irehsdk-kgl--d
e--------ksgfqalkkka------gg--ksg--g-mvvrflam---nm
kklrgskhrapyfv---gnt---p-y-----rlvmnvt------------
----------k---d----------------c----t-nslmglf-----
-----ysisskg-------tr--------k-evn---------vt-----
----------------------ahalpeca-slt----vvkaal-gykst
k-laiikrd--hdgvklv-mlff----vdkasmgdaggnmppas------
----------skvgdaekaivkps-------------------ncnfttd
--cra-----dyryyihnngs-kdpngasscegtqfwqeagqf---pv--
-lckkmnlkvagvkh-wgkfssdplfeniahhfll--hsaarcpfhsy-k
see----------------
>node19
----argdiv-hkfavhlardkkes--wiskka-----------------
------------------r------gsv----t--dgklkf-ev---yit
hpa----e--------q-facck-----rqy-----------clttra--
-ldgf-twel---lg-------ktsfn--------ahvyawdqgtrvatl
---hi-------kg--hy--ql---gges------dskcsps---h-l--
-rhltnmal-daesvp---k--qlkhtf------vpsav-----------
-----------sdhrhvii--ep--ivv--glk------------p-pky
rk----va-fi--vs----------------nivgl--gnlkn-dk-dv-
---------a-i-qwrggsrdqkvn----eac-cina------c------
-----r-ts-----r--s---a-----gyvslrvgt-------p--kt-t
s-----m--avph------t-----saapgaariv-vrrhsgktrgl--d
gdya----praglanlk---------gd--ksg--g-ivlsflam---na
qklrdlk--sayyvleqaht---p-y-----nlvmnai------------
----------d---d----------------c----t-kalaglf-----
-----hsvdsk--------traatg--gkk-vvn---------vtkdiyt
t------------------------llecv-sldmaadvaktal-gvkst
k-pa-rtrd--hagvklv-mlff----vekvslsdtggtmppas------
----------t-isdvekaivdpts---------------k-rkcnvstt
--srn-----dyrlyvhned--kdpagasriegtqywptagtlr--pv--
-lcknfnlkgqg-ks-wgkfssdrl----------pchsaarcpfhgy-k
pag----------------
>ENV_HV2G1/23-502
----argdiv-hkfavhlarekkgd--wisrkg-----------------
------------------r---------------------f-ev---yit
hpa----e--------hpfacck-----rqy-----------cittra--
-legf-kwel---lg----lrikysfn--------ahvftwdqgtrvstl
---hi-------kg--hy--kl---gges------dskcsps---h-l--
-rhltnmai-dadsvp---k--qlkhaf------vpstd-----------
-----------gdrrhvii--ep--ivv--glk------------p-pky
rk----va-fv--vs----------------nivgl--gnlkn-dk-dv-
---------a-i-qwrggsrdqkin----aac-cvna------c------
-----p-ts---fnr--s---t-----gyvslkvgt-------s--as-t
s-----m--avph------s-----sasagparitsvrrhpgktrgl--q
aqya----praglanlk---------gn--kdg--g-ivlsflsf---nv
qqlrnvk--sayyvleqani---p-y-----nlimnvi------------
----------d---d----------------v----t-malagff-----
-----hsvdsk--------tptatg--grr-vvn---------vtrdvyt
t------------------------llvcv-sldmaadvaktvl-gvkas
k-pa-rtrd--hsgvrlv-mlff----vekvnltdtmgtthpss------
----------s-isdvekavvdpts---------------k-rkcnvatt
assrn-----dyrlyvhded--kgpagasriedtqywptagtlr--pv--
-lcknfllkgqg-ks-wg-fssdrl----------pcssaaacpfhgf-k
pgg----------------
>node10
----argdiv-hkfavhlardknes--wiskka-----------------
------------------r------gpv----t--dgklkf-ev---yit
hpa----e--------q-facck-----aqy-----------cltsrs--
-ldgf-twel---lg-------ktsfn--------ahvyawdqgtrvatl
---hi-------dg--hy--ql---gges------dnkcsps---h-l--
-rhltnmal-daetvp---k--qlkhtf------vpsaviw----sggl-
----------lsdrrhvii--ep--ivv--glk------------p-pky
rk----va-fi--va----------------nlvgv--galkn-dk-ev-
---------a-i-qwrggsrdqkvn----eac-cina------c------
-----r-ksdgs--r--s---k-----gyvslrvgd-------p--kt-t
s-----m--yvpl------t-----saapgaariv-vrrhsgkirgl--d
gdya----pragfadlk---------gd--ksg--g-ivlsflam---na
qklrdtk--tayyvleqaht---p-y-----nlvmnai------------
----------d---d----------------c----t-kalaglf-----
-----hsvdsk--------trtata--gkk-vvn---------vtkdiyt
te-------------------ithallecv-sltmtadvakaal-gvkst
k-la-rtrd--hagvklv-mlff----vekvslsdaggnmppas------
----------s-isdvekaivdpts---------------k-rkcnvttt
--crn-----dyrlyvhnnn--kdpagasviegtqywptagtir--pv--
-lcknfnlkgqg-kr-wgkfssdrl----------pchsasrcpfhgy-k
pag----------------
>node18
----argdiv-hkfavhlardkkes--wiskka-----------------
------------------r------gsv----t--dgklkf-ev---yit
hpa----e--------q-facck-----rqy-----------clttra--
-ldgf-twel---lg-------ktsfn--------ahvyawdqgtrvatl
---hi-------kg--hy--ql---gges------dskcsps---h-l--
-rhltnmal-daesvp---k--qlkhtf------vpsav-----------
-----------tdhrhvii--ep--ivv--glk------------p-pky
rk----va-fi--vs----------------nivgl--gnlkn-dk-dv-
---------a-i-qwrggsrdqkvn----eac-cina------c------
-----r-ts-----r--s---a-----gyvslrvgt-------p--kt-t
s-----m--avph------t-----saapgaariv-vrrhsgktrgl--d
gdya----praglanlk---------gd--ksg--g-ivlsflam---na
qklrdlk--sayyvleqaht---p-y-----nlvmnai------------
----------d---d----------------c----t-kalvglf-----
-----hsvdsk--------traatg--gkk-vvn---------vtkdiyt
t------------------------llecv-sldmaadvaktal-gvkst
k-pa-rtrd--hagvklv-mlff----vekvslsdtggtmppas------
----------t-isdvekaivdpts---------------k-rncnvstt
--srn-----dyrlyvhned--kdpagasriegtqywptagtlr--pv--
-lcknfnlkgqg-ks-wgkfssdrl----------pchsaarcpfhgy-k
pag----------------
>ENV_SIVG1/22-522
----gkdi-------vhqakgnspthvwv-nli-----------------
------------------v------p-p----t--dgkfefval------
-------d--------q-ha--k-----taf-----------cltavavs
yagafg--hi---de----------fk-------qgqvlnwnqdskvvvy
---tvrarqtkqdv--rfgmgw---sgek------ddltvna---g-ls-
-ry-tpmmp-ggepdl---k----kqsf--------qyilw----a----
----------lakkrlstv--kp---va--glv------------lsasy
ik----ht-pi--vv---------------ivlt-h--esvfai-gv---
---------g-ik----asvsqhi-vkefdpd-c-tgfppgn--------
----------w---r--a---------gydslrgk--------llnplng
a-----f--knpf------v-----ak-gap----------ps-kgi--d
thya----ppag--e---------------kns--q-mrhgspvtsynsl
hkkkkig--apyfh---ergaayaef-----aglmk--------------
----------e---e----------------tehcntyk--vliygkvtv
chgl-qtlrtkg-------tsta---------------------kadc-k
pd-------------------qgkalldqa-avmmsspla---l-gkmct
h-le-skqgniaealellg-lff----pdaislgdaghskalts------
----------t-lgesdkavyspay--------sai-vatr--rcaik--
---------------gh--------------esdkfwetwstfr--vi--
-a-nk------g-yr-------------v---fll--ts-----------
-------------------
