>node7
htli--------c---gfgdcaaqqi-----vavlwalel--rnqssh-c
drgcqlit-kdgs---gqengsclvpvpelptytn------npitakceg
qenqvlctcqalchtgntscgtgahfsqkgtn--rltpsfvvkdgm---v
dfegvvsdhlgkpk-qvcyhptglspahgvl--ehtyvihfvvedffapk
gphasngkr------maleyyfddqktqnaalvdt-alitgnnykcyngk
arpikekrldradlr---lrhlktgtqncry----fpkdeanc---kglr
tlvdclllplavadqfkptkeairtrieaslhthfcakqnvcedhien--
a--rnyesrretndgltqkadgepnahgne-----fvfkdagdi--ldsn
kdtwtvvnkvspqldde--rddgshkvtiaycnkivadyerm-vylsgtg
laqgaaesgfdfkvs---------tygf---hqkiaipk----lmsdalg
dnfkap--getrmsgksdlk---gerpgvplihti---gyefttvcqlyd
leskaakvkkkflggk--kppgflcs--snaa--sq
>ENV_HV2D1/24-501
snii--------ylmdgfrscearis-----lsiilthlm--swinah-c
tkgakftc-edga---gkdhaksfvalpameefaygdaakgsmlanqckd
pkgdvictchalshsvktrckkdphfkksdrgqqslvevfmrkl---ytl
tvsqilnqflgkdk-rffirpaevkanksav--qhkyllafvikefippg
glsltkakr------kgvdfyldtlkheqkdpddv-psamagiyrsyrvt
aigkhqkv----tlr---vtkeatgaqecaf----fendapfcvrtkgvk
svsgcgk-plpv---fkakkesirgrivkrmsaefcvdqalchemred-y
g--qcfasvavvqgglngksntdmvccdseph---gtykggges--gsvg
ksqltkqgaspphlnna--qspggfyicvasphkdlghfept-lyisaid
ltqvpeffqqatkca---------lysf---yarhflsk----lipdala
kefkk-sganqktatrtemk---gdkpavplteivqytffqfgpgcqvfn
vknrcgklnkvylggk--eedtyvcsnklklalrvd
>node17
ynqi--------ylpdglrscaervs-----lsiilshlm--awinah-c
tkgvkfic-kdga---gkdhatcfvaqpaleafay------nmlanqcdd
rdgdlvcscqalshsvkspcskdahfkksergqgslieifmska--pytl
nidqvlnqflgkdk-rffvrpgsvknnvsav--qhryllqfvvkeffppg
glnltnakr------kgvpfyldtlkhekkdpddv-psamggiykcyrvt
aigrhqkv----slr---vtrlatssqecgf----fpneapfcvrtkgvk
tindcgk-slpv---fkakkesirgriakrmsaefsvdqalcheyhed-y
g--qcfasiaavegglngksntdlvccdseph---etykggget--gssg
knqltkngassphldna--rstggfyiyvapphkvlghfeps-lfisgit
ltqapeafqqattcg---------mysf---yqkhylsk----lipdala
gefkk-sgankktggrtdlk---ggrpavplvnlvqyaffqfgpgcqmfe
vknrcgklqkvylggk--eastyvcsstlklalrvd
>ENV_HV2BE/24-510
fnqi--------ylpdglkscaeivs-----lsiilahlv--awinah-c
tkevkfsc-edga---gkdqtv-fvtlpalesfayghgdkgnmlaiqckd
regdllctcqalshsvkkrckkdahfqkadkgqdslvdifmlkt--pyil
nidqvlnqflakek-rhfvrpgevkksasai--qhryllqfvaseiippg
glhlykakr------kganfyletlkheqkdpddv-psamgdsyrsfrct
svgrhqki----alr---vtnlatssqecaf----fpnaqpfvarakgik
slsgcgk-slpv---feaetesirariakrmsaefcvdqelcheydeggy
a--qcflsvgacegllhgksnsdlvccnseph---gtykggget--gstg
knkttkngasapfldne--hspgafyicvspprpalghfaps-lfisgid
ltqapdnfasastcg---------myil---yhmqflck----lipdala
kqfkk-agankqtaartgln---ggkpnvplvelvqyafiqsgpgcqmft
lknrcgkldkiylggd--epsayvcsstlklallvd
>node14
fnqi--------ylpdglrscaervs-----lsiilshlm--awinah-c
tkgvkfic-kdga---gkdhatsfvalpaleafayghgakgnmlanqckd
regdlvctcqalshsvktrckkdahfkksergqeslveifmska--pytl
nieqvlnqflgkdk-rffvrpgevknnqsav--qhryllqfvtkefippg
glhltkakr------kgvnfyldtlkheqkdpddv-psamggiyksyrvt
aigrhqkv----tlr---vtrlatssqecaf----fpndepfcvrtkgvk
sisgcgk-slpv---fkakkesirariakrmsaefcvdqalcheyhed-y
g--qcfasvaavegglngksntdlvccdseph---gtykggget--gssg
knqltkngasaphldna--qspggfyicvapphkvlghfeps-lfisgid
ltqapeafqqattcg---------mysf---yqkhflsk----lipdala
kefkk-sgankktasrtelk---ggrpavplvelvqyaffqfgpgcqmfn
vknrcgkldkvylggk--eastyvcsstlklalrvd
>node9
ynqi--------ylpdglrscaqrvs-----msiilahlm--awfnah-c
argvnlic-kdga---gkeqgscfvpqpaleafay------dmfanecdd
reedlvctcqalshsvktpckknahfkksahgvgslvqlfmtka--pytl
dfeqvlnqflgkek-kvfyrpgsiknnqgvv--qhiyllqfiakelfppg
gmhltsgkr------kgvpfyldtlknqkkepvdv-psamggnykcykvt
aigkkqki----elr---ltrlatssqecaf----fpndepncvwtkgik
tlsdcgk-slpv---fkakkesvrarikkrmnahfcvdqalchdyhed-y
g--qcftsraavdgglagksdtdltscdseph---stykgggdt--gssg
knswtkngtssprldna--qsskgfyicvasthkllghfeas-lflsgia
ltqapeafqrattcs---------iysf---hqkhflsk----liadama
defkk-qgansktggrtdlk---ggrpavplvnliqyaffefgpgcqmye
vknkcgklekvylggk--eastyvcssalkla--vd
>ENV_SIVG1/22-522
halt--------c---gfgecaakqi-----vtvlwalel--rnqssh-c
drgcqlit-kdgs---gqengaclvpvgelptyvn------aritaeceg
qenqvlctcqawchsnntwcgtgryfeqkgsh--rvtpffvvkdgl---v
tfegvvsdelgkpk-qvcylptglspahgvl--ehvyvihfviedffapk
gphaangtr------tvleyifddqktqnapladt-alitannykcyngk
arpikekrldradlr---lkhlktgnkncry----fpkreanc---kglr
tlvdcillpfsvadefrpvkegirtridasihthfsakmnvcedhiea--
asmrnyeskretqnglsqkadgepnahghe-----fafkdagdi--laed
kdvwavvtkidpqldde--rddgshkvtiaychkivaeyhrl-vylsggg
lapeaaesgfeykva---------tygf---qqkiaipg----lmsdglg
dnfkap--getrmsgssdlk---gerpgvplihsi---afefttvcqlyd
lqskadkikkkflagk--kapgflcs--snag--sq
>ENV_SIVM1/24-528
ysqt--------ylgaglrscaqkvs-----mdvilphlmyyawfnah-c
grgislic-kdga---gknqgscfvpqpileafay------dmfanecdd
readlvctcqalsssiktpckknchfkrsahsvgkliqlfmtka--pytl
dfdqvlnqflgkek-kvgyrqssikdnqgvl--thiyplrfiakelfppg
gmhltsgkr------mgvpfylgtlknqqpeptdv-ssalggnyrcykvt
aigkkqki----tlr---ltrlntssqecaf----fpnddpncvwtngrk
tladcsk-tltv---fkdksesvrarinkrkkahfcidqglchnyhed-y
g--qcfaargavngglggksdidlissqseph---ssfkgggdt--sggg
knrwtkngtsnprlena--qsskgyylcvaanhkllghfaan-aflsgta
ltqapegiqrattss---------iyaf---hqkhflar----lvadama
enikk-qgansktggrtdlk---ggrkavplqnliqyaffefcpgcqmye
fkekcgkledvylavk--eastyvcssalkls--vp
>ENV_HV2NZ/24-502
yhqa--------yladavrscadrcs-----lsiilshlm--awinar-c
tkgvkfic-kegi---gkdhatcfaaqpalegfay------lslpnqced
rdgslvcscqalshsvkspcskdpffkksergqgslieifmskq--pytl
nsdqvlaqflsknk-rfyagpgssksnrsav--ahrfmiqfvvkeffppg
glnltnakr------kevpfyletlkhqkkepddl-psesgaiykcyrvk
aigrhhkv----alkgspiarlatgsqecgf----ypnetppcvktlgik
tikacgk-srpi---fgakkssvrgrvgkrasadfsvnqvlcheyhed-f
g--qcfggmaivdgglkgkgntdlvccdaeaq---etykngget--gssg
knqltknssspphldia--dh---fyiyvapphkvlghfeptslyfsgvt
vsqapeafqqattcgrfvpvepekmyaf---yqkhylsv----lipdala
gefdk-sgankktggrtdlk---ggrpavplvnlvqyafyqfgpgcqmfe
qknrcgklqkvfldgd--etssyvcsstlilalrvd
>node19
ynqi--------ylpdglrscaqrvs-----lsiilshlm--awinah-c
tkgvkfic-kdga---gkdhatcfvaqpaleafay------nmlanqcdd
regdlvctcqalshsvktpckkdahfkksergtgslveifmska--pytl
nidqvlnqflgkdk-rffvrpgsvknnqsav--qhryllqfvvkeffppg
glhltkakr------kgvpfyldtlkhqkkepddv-psamggiykcyrvt
aigkhqkv----slr---vtrlatssqecaf----fpndepfcvrtkgvk
tisdcgk-slpv---fkakkesirariakrmsaefcvdqalcheyhed-y
g--qcfssiaavegglngksntdlvccdseph---gtykggget--gssg
knqltkngassprldna--qssggfyicvapphkvlghfeps-lfisgia
ltqapeafqqattcg---------mysf---yqkhflsk----lipdala
gefkk-sgansktggrtdlk---ggrpavplvnlvqyaffqfgpgcqmfe
vknrcgklqkvylggk--eastyvcsstlklalrvd
>ENV_SIVV1/24-538
hats--------c---gfgdcasqef-----vpllrafnl--rnrss---
----tnis-kdgsqnlgqengscicpvpelptygn------ipiigkceg
hrkqtlctceglcntgnvscvsgkhfsqkgsy--ritpsflvkdvi---v
dfsgvledhlgkpkvqicysptalpgthgvl--chkyvihyvvedlfepk
gpqapdgkn------ltlnyyfdkqktlnaasgek-avitgvnykcangr
arqiyeqplgr-------lrnlkggtqncsy----fpnddaac---tglk
tlthc-----svasdfkpikegiktkveaalrphfvakqavcedhiqn--
k--leyksrsqadqglikkvegepnpfgdq-----fvfgstgdi--lesn
kdtwtvvs------------edgsqklaigycdkfvadesrs-aflpgcg
lgqgaadagfdfkvs---------tygfenleqkivipk----lvddslg
sgfkap--gpvrgvgrsdlr---gerpaiaqihta---gyeftwaselyd
gaaksatlnrtflgar--kppgfmcn--leaa--nq
>ENV_HV2G1/23-502
ynqi--------flpeglractqrtn-----lsnilshlm--ewinah-c
tkgvkfic-rdga---gkhkatcfvaqpaleafay------nmlanqcdd
regdivcscqalshsvrtpckknahfkksergtgelveilmska--pttl
nidqvlnqflgkak-rffvhpgsvknnqsav--qhryvlqfvvkeffppg
gqhlskakr------krvayyldtlkhqkkepddv-psamggiykchkvt
argkhqkv----slr---vtrvatssdectf----fpndepfcvrtkgvk
tisdcgn-slpt---fkakkesirarvakhmgaefcvdqslcheyqed-y
g--qvfssiaavegglngksknnlvccdydphggsgtykggget--gssg
knqvtdngassprldns--qs-ggfyicvapphkvlghfepg-liisgiv
laqapeayrqattcg---------mhsf---yqkhflsk----sipdala
gefkk-ngansktggrtdlk---ggrpavplvnlqqyaffqygpfcqlfe
vknrcgklqklylggk--qaspyvcsstlklhlrad
>ENV_SIVGB/47-569
knes--------c---dttkcqphevttvrcndvlwahqc--aekagqec
rklcaalqmkaap---a--vpacmlctgalptahd------gpstyttad
neshvfskcmgtsrtvpvncsqveqfrcqgvk--raqaefmagkdf---l
g--hva-altgghn-rvmvrgectvpnkdta--ktsyg---------sak
pthvafdigivarhilalnyyaen--ttvspc-dl-aafakieykcywkn
itkvapircepitfr---arvprsahfkqslllla-rsvgnecywytgav
aivaignppqdvnpqiaeyytalperperrlpahvcegtklpmspign--
n--rtltpkhkkygkgwanitfvftdcvq------------gnigifald
qnrwkdsgsqrssieks--hsnhaqaasgdypiqlvgrshvh-rflagkg
lvlgmgkggsnargf---------qf-----hqesaagaglynllmdelp
gqfgp----------ishlrgsviekasgpsaeyv---sflfskgtqlyd
atgkpsriggqylgrksnlsysilskayhpvn--ds
>ENV_HV2CA/25-512
ysqvercecalvylpnglrscaervi-----lsivlshlm--awikgh-c
tk-ikfic-kdga---dkdhatcmvaqpamealty------nmlalqcdd
qdgdlvcscqalthsvkspcskdahfkkssrgqgklieifvqka--pytl
nisqvlnqflakqk-rffvrpgavknsvves--qhryklqfavkeffpps
glnltntnr------kglpfylqtlthekkepndvtspamggiykcyrvt
smgrhekv----slm---ytrlaansqecgf----fpkeaafcvrakgvk
ainecgk-slpv---lkekkesdrgrivkkmsagfgvdealcheyped-y
g--qcfasiafvdgglngkanadlvccdweah---etykggges--gstg
ksqltkngadsphlnyt--katggfyiyvapphevlghfeps-lfiqgit
lteapeafqqattcg---------mytf---iqkhylsk----lekeala
gafmk-sgankktaaradlk---ggrpavplinlvryaffqfapgcqmfa
vknrcgklkkvylgge--eastyvcsstlkldvrva
>node18
ynqi--------ylpdglrscaervs-----lsiilshlm--awinah-c
tkgvkfic-kdga---gkdhatcfvaqpaleafay------nmlanqcdd
regdlvctcqalshsvktpckkdahfkksergqgslveifmska--pytl
nidqvlnqflgkdk-rffvrpgsvknnqsav--qhryllqfvvkeffppg
glhltkakr------kgvpfyldtlkhekkdpddv-psamggiykcyrvt
aigrhqkv----slr---vtrlatssqecaf----fpndepfcvrtkgvk
tisdcgk-slpv---fkakkesirariakrmsaefcvdqalcheyhed-y
g--qcfasiaavegglngksntdlvccdseph---gtykggget--gssg
knqltkngassphldna--qssggfyicvapphkvlghfeps-lfisgia
ltqapeafqqattcg---------mysf---yqkhflsk----lipdala
gefkk-sgankktggrtdlk---ggrpavplvnlvqyaffqfgpgcqmfe
vknrcgklqkvylggk--eastyvcsstlklalrvd
>node11
ynqi--------ylpdglrscaqrvs-----lsiilshlm--awinah-c
tkgvkfic-kdga---gkdqatcfvaqpaleafay------nmlanqcdd
regdlvctcqalshsvktpckknahfkksergtgslveifmska--pytl
nidqvlnqflgkdk-rffvrpgsvknnqsav--qhryllqfvvkeffppg
glhltkakr------kgvpfyldtlkhqkkepddv-psamggiykcyrvt
aigkhqkv----slr---vtrlatssqecaf----fpndepfcvrtkgvk
tisdcgk-slpv---fkakkesirariakrmsaefcvdqalcheyhed-y
g--qcfssiaavegglngksntdlvccdseph---gtykggget--gssg
knqltkngassprldna--qssggfyicvapphkvlghfeps-lfisgia
ltqapeafqqattcg---------mysf---yqkhflsk----lipdala
gefkk-sgansktggrtdlk---ggrpavplvnlvqyaffqfgpgcqmfe
vknrcgklqkvylggk--eastyvcsstlklalrvd
>node10
ynqi--------ylpdglrscaqrvs-----lsiilshlm--awinah-c
trgvkfic-kdga---gkdqgtcfvaqpaleafay------nmlanecdd
regdlvctcqalshsvktpckknahfkksahgtgslvqifmtka--pytl
nidqvlnqflgkdk-rffyrpgsvknnqsav--qhryllqfivkeffppg
gmhltkgkr------kgvpfyldtlkhqkkepddv-psamggiykcykvt
aigkkqkv----slr---vtrlatssqecaf----fpndepfcvrtkgik
tlsdcgk-slpv---fkakkesirariakrmnahfcvdqalcheyhed-y
g--qcftsiaavegglagksntdltscdseph---gtykggget--gssg
knqwtkngassprldna--qsskgfyicvapphkllghfeps-lfisgia
ltqapeafqqattcs---------mysf---hqkhflsk----liadama
sefkk-sgansktggrtdlk---ggrpavplvnlvqyaffefgpgcqmfe
vknrcgklekvylggk--eastyvcsstlklalrvd
>ENV_HV2D2/24-513
ynqi--------ylpdglrscaqrfd-----lgfilshlm--awiteh-c
trglkfic-kegt---gkghgtcfagqpaldsfvy------nmlanacdd
kdgdlectclalnhsvktpgkksghfkdnphgtgslvqiymtks--piti
d--qvlnqfngkdr-rffyrpgsvknkqiaicaqnsyllqlivreffppg
amnlakakr------kgvpfylntlkhqsldpddv-psalgsiykcyqvt
avgrkqka----tfr---vtrlaahaeecvf----fptdqsf---tkgfk
tlpdcgk-alpv---fktkkdsirmgigkrknahfcvdhafchgyhqn-y
g--qcfasiaaiegalegktstdltsadseph---gtykggget--gtsa
kqqwkdigasspkledtrgqgpkgvyicvavpvnkqghfqpa-lvvsgia
ltqaaegfqqatsha---------iynf---kpkhflak----liadnla
sefdk-agehsktggrldlk---ggraavplvsplryaffefgpvcerld
vknrcskleklylggk--etstysssstlklsikvd
>node8
hnqi--------c---gfgecarqli-----anilwahel--rnqssh-c
drgcelis-kdgs---gqetgscmvpipdlptytt------dpttakcen
qesqvvctcqalchtvntscgsgahfqnkaan--rlvqpfvikegi---v
efenvvsdflgkpk-qvcyrpsglssaqgvv--ehtyvnhfvandffapk
gahagngkr------mgleyyfddqktqnaalvdv-aalvghnykcykam
aigikhkrldkavlr---lrhlktgqqncry----fpkdeancvwtkglr
tlvdclllplpvadqfkptkeairarieaslhthycakqnicednian--
g--rifesrretndgltgkadgepntcgne-----safkgggdi--ldsg
kntwtvvnkhsprlade--qddnghkvtiaycnkligdfekr-lylsgtg
lsqgaeksgfdgrvs---------tyaf---hqkitipk----lmsdalg
eqfkap--getrmggksdlk---gerpgvplvhti---ayefttgcqmyd
lnskagkvekkflggk--kapgilcsmalnls--se
