>node8
tgakarhnpvavedstilekgfqa--dcl--vflesavsshyvey-----
-----kqkaagynkirh-----rasvvp--fpde------lasgsnscy-
s----d--cthaq--qygytfgllrlsg-ktehqlaggkvksr-raes-a
ldntmkslaskhnl------nlp--t-----------------flgkapf
krvvtllpstisvgt--eafghltss---------lkdrpaqlngdrqsl
lqvgevdshrqsrtvdqqvreepg--csynceelafl-asdqickvhlpy
pteppaqensigvkdqktrt-tqyddyiggaqeakkilkhgkdirvgyfs
gglafpa----nfklnvpawgngkavgegvltngaslaeakkvdsgvkdt
ckl--------sgtlpkmmgvmgpkvg-aglalyanvgv----kt--aal
vdfnivgvkfiscddttaidggeqllpspvagklkslyackardlsng-k
hl-savldmayss-tk-qhql----tpettkackhrktqhtqyqq--wke
vlkgaagpketpgekspt-aapdkagskvllkfivii------ikea--e
kfggicwcl----cq-
>ENV_HV2D1/24-501
snaqsgvepvslaqsallastfqp--dsl--vapegatkgevggy-----
-----hgkkasynqvrkagsekstkvvh--fsdd------epagcsass-
a----g--crdya--dyhftfwlhy------dhevgdrkvtsk-kgve-s
-qkdf-plseevgnlfckgiydl--n-----------------ihg-gtf
ksdpivspasaapgs--etfnskttqkdkasaavgfkdkqkqehfgkqdi
lqvgeka---lsksgslqvkpehgirytyhcnqlkfm-tsahrckarlay
padpqgqstklgrkkeaght-arysdysapggnatkmvqhvdqvraavpt
sglgfiscgpenfeygevswdpakptvvgvesggpalcqsmslsagknte
cki--------pvqltrleatlppnig-agialydn--i----qf--iap
vhqktdgiq--pcsdcksidgdrqglpt-rtarlinfhyckaraqsgfmr
dl-daamttlypd-vs-qldl----tppsvttpktnnpvrtafnl--crs
vlkgntgpktlnamndpv-tgpdqkgqkitfkfvltg------inakage
qypgnywsl----cp-
>node14
snaqsgvdpvsieqsallastfqp--dsl--vspegatkgevggy-----
-----hgkkasynqvrk-----stkvvh--fpdd------ekagcsass-
a----g--crdka--dyhftfslhy------dhevgdkkvtsk-kgve-a
-qkni-plseevgnlfckgeydl--t-----------------ihg-gtf
ksdptvspasaapgt--etfgskttqkdskssavgfkdkqnqehfgnqdi
lsvgeta---qsrsgdlqirqehgvrytyhcdqlkfl-tsvhrckamlay
padpqgqrtklgrkgeagha-arysdysasggnatkmvqhvtqvrvgvpt
sglgfiscgpenfqygniawdpakptgdgvesvgpalcqskslsagknke
cki--------pvsltrleatlppnia-agialydn--i----nf--iap
vhqktdsiq--pcsdsksidgdrqgipt-rtarlinlfycksraqsgfmr
hl-daamttlyvs-vs-qldl----tpptvttcktnkpvrtafnl--crs
vlkgatgpkqvnanndpv-tgpdqkgqkilvsfvltg------inamdge
nypgnywsl----cq-
>ENV_HV2BE/24-510
rnsqggvnpcsreqsellaspfqp--dsl--vsgegatkgevggy-----
-----hgkktafnqlrq-----sdkivh--fpdd------ekagcsgsk-
g----g--crdka--dyhftfslhy------dhevgdknvvsk-ktve-p
-ekni-pkseevgslfckgqydl--t-----------------vhg-gtf
ksdptvspgsaapgt--etygsqttqkdskkgatdfgekqnqehfsnqdi
lsvgeta---qtrsgdlqarqehgvrytyhcdqlkfl-tgvhrcramlay
padaqeqrtklgrkgeagha-arysdysasgggatkmvqhvdqvrvgvpt
kglgfigcgpenfqygnitwd-pkptgdgvpnvgpslcqskslgagpnke
skv--------pvpltrgeaslppaia-vnvtlf---------vf--hap
vhqksdriq--pcgdgksidgdrqgipn-rsprllsllycrsraksgfmr
hl-dpamttlyva-vs-qldl----tpptattcktdkpvrtgfei--crs
ilkgpaksqqvnannepv-tgpdqkgqkilvsfvatg------ieamgge
nypgnywsl----cq-
>ENV_HV2NZ/24-502
nnaqsgrdpvsidpialldtefnn--asl--appegasknevggy-----
-----vgkiaavkdgrk-----ptkvvh--fpia------ekggcaasp-
a----kvdcrnkp--qykfglslhy------dhtvgnenvqtr-tgve-a
-qkni-plkentgtllckgdtnl--t-----------------fha-gkf
rsdpavssasaapgi--etfgckvtetdskrsavglkdkqneqhfgvqai
lsvgeta---snrsgelqlrqeagvryafhcdplkflatckhrckamlay
apdpqgqrqkfgrrgdavra-plysdesgsggmaakqvahvsqarvgyrs
sglgfpscgpeifqfqkiswdpekpsgdgaesvggalcqenpldpgkqka
c----------gipltrveeslppnva-agialyet--k----nfahkap
vhqvidaiq--pcsdakiingdtqgipa-rtarlinlfyckgraqsgfkr
hl-davmltlyvs-vskqldlvhsaapstvtthktnkpvrtafnl--crg
vhksatgpkqvkaesdpv-tlpeqkgqkilvkfvltg------inaldge
dypsqywspleeicq-
>ENV_SIVV1/24-538
kgekashhgvgledttrlayqfqa--qcl--vvfeaakattys-------
--------tadysliqh-----rasviq--ylne------laggsnscf-
c----d--ctfaq--iygyifgllvdsg-kshhqvqggklkek-rdng-g
ldhtmksktgkhkl------nlp--v-----------------almkasf
arlsnllvktlyeal--dsyghlsks---------lkngntslrgdrqta
mqvrdmgpnkqarivgqrtrespa--ceyhyeelavl-vteerckihlpy
atephrqekstdtssettea-tqyddksgdatestdtlthfkelmvsyic
gdtafaa----tfkvdvplwgvgkrv-dgvlkkdggmaeakv-ssglkst
cpl--------pgafpskmfvmgakvn-agla-----ak----kt--sem
vdlnvigvkfisckgnddieggaaivpssvvgrarglytckarnfspg-k
halgavlqmsysa-tk-qtel----taeppepckhriahsdqlaa--wki
dirgkigaketpggkg---kastkttskvlnkflnip------tkaa--d
kfaelcwcl----ca-
>ENV_SIVG1/22-522
tgnkaglnavgaedstelakhkqa--ncm--vilespmttvyk-------
--------rarynkirh-----rasvvpmsfsne------lasgtkscf-
q----d--ntnah--qfgnvfgllilsg-dadhqtaggksker-rpas-t
lnntkkskagkhsl------nvp--t-----------------algkvaf
krlsnllpntlyggt--dayghltgs---------mkngasqlagdresa
lqvgniesnnharivnehvrdvpa--csykcedlafl-vsdhtsyvhley
ptesgsqesgigkknqktqt-hqyadyvggaaeaknvlthfkelrvkyfs
gslafae----vfklnapawgngksv-egvltkdatmtdtkgvasglkqs
ckl--------pgtfsammfvmgakak-alll-----pkllilqt--tpl
vdlnvlgvdfrscdsttniqgvdpvipspvvgklkglftckaqnlshg-k
am-spvmgmayss-dd-qtql----kpesaeacrhritqhdqyah--wki
vlsgkvgaketagakart-gtadkagskvllkslvii------vket--e
kfgglcwcl----cq-
>ENV_SIVGB/47-569
fvaqvgtctgkrgssrvllqlfpv--gclpallmnptlgarfldr-----
-----rkkllkysnvlh-----s--lll--fparhtlytvfsdsefggyl
fvkfad--iaggtaasyglqmalveqdedkidhgvnglkavsltralrha
leqactteafkhvl------espldprrlsdlgadkntsysnhlgikray
eitldmesssvspaaikigfkalclg---------srdrpsqlgghnaag
lkigdl-----gndimkqkkkdgi--ckyctatlngl-gsprgcicftig
lstatahegdrggas--irvktfcgkymkvsskfgkaldnlrlisiayfk
fgqklae----veklgtakwg-sdivlsqnldnpgdavngnllegkvdvs
dnlsigsavefactlhksmaaverqsh-iglayyakiit----eg--asr
leqtvlqkrmkictlg-----gegyltsvvlaslcllvvckl-------k
sv-wvllmqpfae-qt-gqkf----dpetarkcevrqnkearfttaktkd
vrpaqtgpkrkatqrslartrtdgegttviprfddvhptpyagvsql--e
nfifirvsh----csg
>node17
nnaqsghdpvsieqtallassfhp--asl--vppegatkgevggy-----
-----vgkvaaynqvrk-----ptkvvh--fpdd------ekagcsass-
a----kvkcrnkp--dykfglslhy------dhevgdekvysr-kgve-a
-qkni-plsentgtlfckgdtdl--t-----------------fha-gtf
rsdptvspasaapgi--etfgskttqkdskrsavglkdkqdqqhfgnqdi
lsvgeta---qsrsgdlqlrqepgvrytfhcdqlkfl-tsvhrckamlay
padpqgqrqkfgrkgdagha-alysdesgsggtatkmvahvsqarvgyrs
sglgfpscgpenfqyqkiawdpakptgdgiesvgpalcqskpldagknke
c----------gvsltrleeslppnia-agialyen--i----nf--vap
vhqkidsiq--pcsdaksidgdrqgipd-rtarlinlfyckgraqsgfmr
hl-daamttlyvs-vs-qldl----tpstvtthktnkpvrtafnl--crs
vlkgatgpkqvkadndpv-tgpdqkgqkilvkfvltg------inamdge
nypgnywsp----cq-
>ENV_HV2D2/24-513
pspqsglepvsieqtahlasafqp--esv--vplqgstkgevggfqvgka
aspegngksaayhkvrt-----hlkvvq--vpkd------eksactiga-
p----k--craka--dyhfsfdlpy------qfeaspkkptsr-kvve-s
-qkni-pltdklgdlftkgeyel--e-----------------ahg-gtf
ksdktvsptsdapgt--esfgsktterdskfsqvgle-iqdqlhfgiqes
gsvgqta---tgrtghldvretpgvkstyhchqlkfl-asvhnckakiay
nadpeanrkrlgrkgdagha-taysdysgsggsaskmvqcashvrvgfpa
saasfpssgaesfeygnfdwgpakqtgegiigmgkalcqskpldvgknke
cki--------avsltklesclppniv-ggvalydn--v----kf--vpl
phhkvdsiq--ptsdaktieghhqtlpt-rkaqlrnvifckgrsqtg---
-p-gaqmttlyvr-vq-sldv----appev-tcktkkpvrtafai--crs
tlpgatgpkqvkadndev-ag---kgqkilskgvltg------vnef--n
hypgnywgv----yn-
>node19
nnaqsghdpvsieqtallastfqp--dsl--vppegatkgevggy-----
-----hgkkaaynqvrk-----stkvvh--fpdd------ekagcsass-
a----k--crnka--dyhftfslhy------dhevgdkkvtsr-kgve-a
-qkni-plsenlgnlfckgeydl--t-----------------fhg-gtf
ksdktvspasaapgt--etfgskttqkdskssavglkdkqdqqhfgnqdi
lsvgeta---qsrsgdlqirqepgvrytyhcdqlkfl-tsvhrckamlay
padpqgqrqklgrkgeagha-alysdysgsggnatkmvqhvsqvrvgypt
sglgfpscgpenfqygniawdpakptgdgiesvgkalcqskpldagknke
cki--------pvsltrleaslppnia-agialydn--i----nf--iap
vhqktdsiq--pcsdaksidgdrqgipt-rtarlinlfyckgraqsgfmr
hl-daamttlyvs-vs-qldl----tpstvttcktnkpvrtafnl--crs
vlkgatgpkqvkadndpv-tgpdqkgqkilvkfvltg------inam--e
nypgnywsl----cq-
>node9
pnaqsahepvsvedtallatafqp--dsl--vplegatkgdvggy-----
-----hgkkaaynqirr-----hakvvq--lpdd------eksgcsass-
a----k--cmnka--dyhftfslhy------dhevgnkkptsr-kgve-a
-qkgikplneklnnlfskgeydl--t-----------------fhg-gtf
krgktvfptsaapgt--esfgsktte---------lkdkqaqlhfnnqsv
lnvgqta---qsrsadlqireepgvrctyhcnqlkfl-tsehicksklsy
padpqgqkqklgrkgeagha-tlysdyigaggnatkmlqhvsqvrvgypa
kglgfpt----nfkygniswgpakptgdgidsvgkalnqskpldtgakka
cki--------svsltkmeaslppnia-agialydq--i----kf--vav
vhhktdsiq--pcddaiaidgdrqliptprtarlinlyyckgraesgfmr
hl-gatmtslyvt-vs-qldl----tpstvttcknnkpqrlafnl--crt
vlkgaagpkqvendndpv-agpdqkgqkvlvkfvlta------inam--e
nyggnywsl----cq-
>node18
nnaqsghdpvsieqtallastfqp--dsl--vppegatkgevggy-----
-----hgkkaaynqvrk-----stkvvh--fpdd------ekagcsass-
a----k--crnka--dyhftfslhy------dhevgdkkvtsr-kgve-a
-qkni-plsentgnlfckgeydl--t-----------------fhg-gtf
ksdptvspasaapgt--etfgskttqkdskssavglkdkqdqqhfgnqdi
lsvgeta---qsrsgdlqirqepgvrytyhcdqlkfl-tsvhrckamlay
padpqgqrqklgrkgeagha-alysdysgsggnatkmvqhvsqvrvgypt
sglgfpscgpenfqygniawdpakptgdgiesvgpalcqskpldagknke
cki--------pvsltrleaslppnia-agialydn--i----nf--iap
vhqktdsiq--pcsdaksidgdrqgipt-rtarlinlfyckgraqsgfmr
hl-daamttlyvs-vs-qldl----tpstvttcktnkpvrtafnl--crs
vlkgatgpkqvkadndpv-tgpdqkgqkilvkfvltg------inamdge
nypgnywsl----cq-
>ENV_HV2G1/23-502
nnaqsghdpvsieqtgllasafqa--ell--vpsegttkggiggy-----
-----hgkkaaynqvrk-----stkclh--fpgd------qkascstss-
v----k--crnka--nyqvtfslhy------dhevgdkkvtgr-kgve-a
-qknl-pllekhgnmfckgqydl--t-----------------fhg-gaf
ksdktvspasaapgt--esfgskttqkdskatpvglkdkqdqqhfenqdi
lgvgqnv---asrsgdlqlrqepgvrysyhpdllkfl-ssvrrckamlay
padpqgqkqklgrksdaghv-alyndysgsggttgkmvqhvsqvqggyat
sglgfpscgpenfqygniawdpakhtgdgiesvgselcqrkpfdagknke
cki--------pislkrldsslppnia-dglalydn--i----qf--tap
vhqktdsiq--pcsdektidgdrqaipt-rtaklinlfyckgrdqsgtmr
ql-davmttlyvs-vs-qldl----vpstvttckthkavrtaftl--crs
ilkgatgptevraegdpv-tgpdqkgqriivkfvltg------inam--k
nypnnytsl----ca-
>ENV_SIVM1/24-528
pnadsahepvsvqdtallattfapfidsl--vplegptkndvsgy-----
-----sgkksgynqskr-----hagvgq--lpdd------yknacsass-
v----r--clnks--nyhftfglyy------eaevgnkkptsr-kgva-a
-qkrikplnqklsdlfssgpydl--t-----------------fhg-gtf
krgqtvfptsaapga--esfgsratd---------lkvsqaqlhfnnqsv
lnvgqtl---qaraadlqirelpgvrctvhcnqlkfl-tsehicnsklay
padpqgqkdglgragetgna-tlysdyignggnatkmlqnvshtrvgyra
kglgfpt----nfqygdiswgparpvgkg---vgkslnqskpldtgaika
ckv--------svsltkmeaslppgia-agialyde--i----kf--vav
vhhkkdkih--pcddainldgdrpfvptprtarlvnlyyckgraetgfmr
hl-gadmtnlyvt-vs-qlsl----npstcstcktnkpqrlafnl--crt
vlvgnagptqvendnnpv-pgpdqkgqkvlvkfvlta------vnap--e
nyggnywsl----cq-
>node10
pnaqsghdpvsieqtallasafqp--dsl--vplegatkgevggy-----
-----ngkkaaynqirk-----htkvvq--lpdd------eksgcsass-
a----k--crnka--dyhftfslhy------dhevgdkkptsr-kgve-a
-qkni-plseklgnlfskgeydl--t-----------------fhg-gtf
ksdktvsptsaapgt--esfgsktterdskssavglkdkqaqlhfgnqdi
lsvgqta---qsrsgdlqireepgvrctyhcnqlkfl-tsvhrckaklay
padpqgqrqklgrkgeagha-tlysdysgsggnatkmvqhvsqvrvgypa
sglgfpscgpenfqygniawgpakptgdgiesvgkalcqskpldagkkke
cki--------svsltkleaslppnia-agialydn--i----kf--vav
vhqktdsiq--pcddaksidgdrqaipt-rtarlinlfyckgraqsgfmr
hl-gatmttlyvs-vs-qldl----tpstvttcktnkpvrtafnl--crs
vlkgatgpkqvkadndpv-agpdqkgqkilvkfvltg------inam--e
nypgnywsl----cq-
>node11
nnaqsghdpvsieqtallasafqp--dsl--vppegatkgevggy-----
-----hgkkaaynqvrk-----stkvvh--fpdd------ekagcsass-
a----k--crnka--dyhftfslhy------dhevgdkkvtsr-kgve-a
-qkni-plseklgnlfckgeydl--t-----------------fhg-gtf
ksdktvspasaapgt--esfgskttqkdskssavglkdkqdqqhfgnqdi
lsvgqta---qsrsgdlqirqepgvrytyhcdqlkfl-tsvhrckamlay
padpqgqrqklgrkgeagha-alysdysgsggnatkmvqhvsqvrvgypt
sglgfpscgpenfqygniawdpakptgdgiesvgkalcqskpldagknke
cki--------pvsltrleaslppnia-agialydn--i----nf--iap
vhqktdsiq--pcsdaksidgdrqaipt-rtarlinlfyckgraqsgfmr
hl-daamttlyvs-vs-qldl----tpstvttcktnkpvrtafnl--crs
vlkgatgpkqvkadndpv-tgpdqkgqkilvkfvltg------inam--e
nypgnywsl----cq-
>ENV_HV2CA/25-512
nsaqsghnpvsieqtallatgyhp--asr--vppenatndevggy-----
-----vgkvaafnqvpk-----pakmvn--faen------dtaacsass-
a----kvycrskp--dykfglslhy------dhevgdqkvypr-kgve-a
-qkdi-plsensdtlfckgitdl--t-----------------fha-gtf
rraptvspasgapgi--ekfgaktsqkdakrs---lkdrqdqqhfgnqdi
lsvgets---qasggdlqlrqepglrytfhceqlkfl-tavhrckamlpy
pgapqgqrqkfghkgnaaht-avlsdesgsgggatkmvakvsqakvgfkt
rglgisscapenfqyqkvawdpakpkgdgiesvgqalcqrkpldagknke
c----------gvsltrleeklppnvacagiamydg--i----tf--map
vheyidsiq--pcdstkaldgapqgipe-rtarlinlfyckgraqqgfmr
hl-dtavttlyigvvr-qldl----tpstvtthktkkpartafnl--crs
vlkgatgpkqmkmdndpv-tgpdqkgekilvkivltg------fnaldgq
nypgnwwap----cq-
>node7
tgekashnavgvedstilakhfqa--ecl--vilesamstnyv-------
--------aaeynkirh-----rasvvp--fsne------lasgsnscf-
s----n--cthaq--qygyvfgllilsg-kadhqiaggkvker-raas-a
ldntmkskagkhsl------nlp--t-----------------algkapf
krltnllpntlyggt--dayghltss---------lkngatqlngdrqsa
lqvgdidsnkharivdqqvrdtpg--csyncedlafl-vsdqickvhlpy
ptepssqeksigkknqktqt-tqyddyvggaaeaknilthfkdlrvsyfs
gslafaa----afklnvpawgngksv-egvltkdasmaeakgvdsglkes
ckl--------pgtfptmmfvmgakin-agla-----ak----kt--apl
vdlnivgvkfiscdsttdieggepvvpspvvgklkslytckarnlshg-k
pm-savldmayss-tk-qtql----tpetteackhritqhdqynq--wki
vlkgkvggketagdkart-aaadktgskvllkfliii------ikea--e
kfgglcwcl----cq-
