>node11
aftkdkp-kspakkafmryaipgsvlgsksl---alltarthlnkrntay
tifgctddlkdvssftavk-gdqtiktgtpiss-qqagvrnmgvy--caf
fitkishdgqmacggp----vklgig-ktkmqkedkpsken-ehghhnav
qdsakeahrlcawshafrapgpveaaiclla--v--errrqmqpldttpc
hyfa-qlnhfvqgsipahfl--hamaqmlgflyefglpssivspnaegaq
kslkakfigeg---------lv----anhlrtkgavkey--ynte-----
--vdfelaleavlmrvlrasdqv--aayggnkvrepaskgpfvqncrega
tanftpcpcsvctmvywemkkvdevalgtvdfaed---------egaflk
pd-syyvghvkggrlryanakqsrltakgkshhgnalgkhvqkngllcns
csrfghpkkqqikelgyldnaqskqcdiakaklnpcrl-p-tsehkqqvw
sgqqaesg--lkkskhg--------tpqpgkktyhyl-girkldvktqtt
hv--dk-svsedkyp-qkagavlgf
>node10
aftkekp-kppagkafmryaipgsvlgqksl---alatarthlnkrntay
tifgctddlkdvssftavk-gdqtiktgtpisa-qqaavrnmgvy--caf
fvtrishdgqmacggp----gklgigeksklqkedkpsken-ehghhnnv
qdsakeahrlcawshafrapgpveagiclla--v--evrrqmqpldttnc
hyfa-qsnhfvqgsipahfl--hamaqllgflyefglpasivspnsevte
kslkarfigeg---------lv----anhlrfkgavkey--yntd-----
--vdfelaleavlmrvlrasdqv--aayggnkvrepaskgefiqdcrega
tanftpcacsvcplvywemkkvdevalgtvdfaee---------egpflk
pd-syyvghvkggrlryanakqsrltakgkshhgnalgkhaqkngllcnt
csrfphpkkqqikelgyldnarssqcdvakgnlnpcrl-p-ttehkqkvw
sgqqaesg--lkkskhg--------spqpgkktyhyl-girkldvktqtt
hv--dk-svsedkyp-qkagavlgf
>node7
gfdkerp-pv-vadafnrygitgaclgltalyarithlarshl-kkhp--
-efchpadlngmtkflcak-ghlsllgpdrldg-nfaairqlgiy--tcy
flfnarhekqkecgkp----akrevgakvqlrkvendakva-vaahhng-
aaspkcahrvcahkaslrasepvdvliclld--l--khgrdvqpleylac
hpfn-eskhfid-avngsflfkramaas-gglyitglpapisardsesgd
kvlkadykdhgvnkkvllvglg----lqylrikggirnilslnaq-----
--infesgveagl--etrqkdn---gkfgkgkawqapskskyfqdckfgg
ttdyvccackvcallywe-kkvggpvlgsisapnn---------egaylk
aa-glyvgsvqdggaaysplksdkmsvkhkarhesevpdnleavalfyps
cpkfshpsqqvskdisylekaksdqctmikadinvchl-p-splnshsal
gshhaerg--lpefklg--------kqqpgsrsggal-svwrldvenhsl
ls--ek-gtlekrfp-akcsrvlgf
>node14
aftkdkp-kspakkafmryaipggvmglksw---alltarthlnkrntay
tifgctddlkevssftavh-gdqkiktgtpist-aqagvrnmgvy--cef
fvtkishdgqmacggp----vklgig-ktkmqkedkpsken-ehghhnai
qdsakeahrlcswshafraagpveaaiclla--v--errrqmqplditpc
hyfa-qlnhfvqgsipahfl--hamaqmlgfvyefglpssivspnaegaq
kslkakfngdg---------li----tnhlrtkgavrey--ynte-----
--adyefaleavlmrvaraseqv--aayggnkvrepaskgpflqncrega
tanftpcpcsvctlvywemkkvdevalgtvdfaed---------egaflk
pd-ayyvghvkggrlryakskqsrltakgkshhgnalgkhvqkngrlcns
csrfghpkkpqiktlgyl---qskecdiakakmnpcrl-p-taehkqqvw
sgqqaesg--lkkskhg--------npqpgkktyhyl-girklivktqtt
hv--dk-svcedkyp-qkagavlgy
>node9
aftkerp-kppagkafmryaipgtvlgqksl---alavarthlakrnavy
tifcctddlgdvqsftavk-gdqtintsdpisa-qqaavrnmgvy--caf
fvtrishdsqmtcgap----gklgigaksqlqkedkpsknn-ehghhnnv
qdsakeahrlcawshsfrapgpvdagiclls--v--evtrqmqpldimnc
hyfa-qanhfvegsisatfl--hamaellgflyefglpasivspnsevte
kslkapfvgeg---------lg----anhlrfkgahkey--yntd-----
--vdfewaleavlirvlrssdqv--aayggnkvrqpaskgefiqdcregg
tknfvpcacsvcpliywemkkvgevklgtvdfaed---------egpflk
pd-syyvghvnggslryanakqarltakgkshhgnalgkhaqktgllcpt
cskfphpkkqqikelgyldnarsnqcdvakgnlnpcrl-p-tpehkqkvw
ssqqaesg--lkksklg--------spqpgkktehyl-gvrkldvktqtt
hv--dk-svsedkfp-qkagpvlgf
>ENV_HV2BE/24-510
afakdkt-kspekksfmryaipsgtmglksw---allkarthlkrkntay
ttfgctddlkelssftavh-adqkittgtpiat-vqagvremgvy--cef
fvtsiqhdgqmacggp----vklgig-mtkmqkedkptknn-ehghhnai
hdsarephrlcswnhafraagpveallclla--vggerrsqmepmdvtpc
hyft-elnhlihgsipahff--hataqmlgllyefglpgsisspdaegaq
kslkakfsgdg---------pi----anhlrtksevrey--ykte-----
--adeefaleavlmrvasasgqv--aayggekvrepagkgtfledcregp
tanfppcpcsvctlvywdmkkvdevalgsmdfaeedhehaglrkhgaflk
ad-atyvghakggrlrylksrqsrltanpkphhgnalnksvqkngrlc--
csrfghpkkpqiqalgyl---qskecdlakakmnpcri-p-taehkqqvw
sdeqaedv--lkkskhgagyvckccnpqpgnktyhyl-gipklivktqrl
hv--er-svcenkyp-ekggavlgy
>ENV_HV2D2/24-513
nftnskp-kpkgqkpflqyadpgsvlghksi---alatahkhlnkrasty
tifdctdelkeitsfltik-gertvkvstvisp-eqaavrkkgfyhacal
fvprisqdddmacaga----salgigekgklqktekpkkey-dhghhgav
qesikcatkfcawhhefrrsgpvetaacllg--v--evrrqmqvikqagc
hyfa-qstrfinfsphahfl--haaaqllgfvyefglpasvvtppsevth
kslkarfigas---------lv----qhhlrfkgpvkey--yntn-----
--vdndlaleailmrvkrasdqv--aaygsnksrepaskgefiqncrpgk
tanftpcscsgcplifwqmkkvkelalgsldtved---------egpflk
td-nycvghikggrmryetpkqsrvsdkgkthhgnllgrhahqnghlckt
cskfprpkkgsvmelgyfdnarssecdvekgstdacrl-p-atqdkdkdw
ssqqaett--ltkskng--------ssetgkkhynyl-girklnirtkmt
hl--dk-avsedkln-qkagsvlgf
>ENV_HV2CA/25-512
afskpkq-kspakkafkrtatpgsllgsktl---mlltvrtylnkkntvy
tifgcgdelkdvssfisvk-sdgtlkagaprsivatagvrnigvy--caf
fatkiktdgqmpcngp----pklaig-rtkipkedkplkgn-ehghhnaa
qasakeahplcvwmhafrapgpveaamalla--i--erhrhlqpvdtspc
hyfa-qlhnfvqgsipaifl--hameqmlgylydfglassivspgaegai
kslkakfsgeg---------ll----tnhlstkgamkee--ftke-----
--vefqfalefvvmrvlrasdqiaegaylgnrvrepgskgpfvqdcrega
tanftacpcavctmvywpmkkvhevalgdvefaed---------edaflk
ad-sfyvgivkggrlryanlrqrrlttkskshhgkalgkhvqkngrlcnt
csrfghpkpdsvmeigfl---eskqcdiakakln-yrl-p-ttaksqqvs
sgqqrefg--vkkskhg--------npspgkmpyhyi-girkldiytett
qv--gk-svcddkyp-ekagavlay
>ENV_SIVV1/24-538
gfdkdkp-pi-vkdahnkhgiddacliltamvsrpshlarshs-kkhp--
-kwcnfvnldgiskflcakenhlgqllpdrleg-nfeaiahlpvy--tcy
ylfnsrqerq-dcgkp----asinvgamkqlrdvendlnia-vvakhkg-
rdspkcphrvcghissfrtsepteviiclld--v--khgrdgkaceylac
hpfkketkqftd-avksaflfnralmas-agvylaglpapetpkdsesgn
kvikteykdhgvgqkvlvvglg----ldynsikgklnnmlslngq-----
--nayq---dagl--etqqddd---gkfgkgkawqtpsksky------aa
atdyvccsckgsapqywe-knvsgpvlaairaphh---------ngaylk
aavglyvgsaqdgaaayspfktepmsvkhknrnekeipdnleyvalfypp
srmfsfasmqvmketeyfeksgtdqcilikadisvchlgp-kpknsnsnl
gkqhaerg--lpefkma--------kpqpgsrssgah-arwklgvdnhpl
lg--ak-dtlekrfpdtkcsgvlgf
>ENV_HV2D1/24-501
sftkdkp-kgpakkafsryawpagvmglksw---ailtarthlnergtay
tifgitddlsevsaftsvh-aeqkiktgtpist-aqagvrdmgvy--cef
fvtn----gqmacggp----vklgtg-ktkmqkddkpskek-qhghntgv
lnsakesqrlcawtnafrgagpveasiclla--v--errrqmqplditpc
hyfa-qlnhfvqgsipahfl--hamaqllgfvyefglpsnivsptangae
dslkakfngdg---------ll----gnhlrtkgavrey--ynte-----
--adyefvldavlmrvarasdev--gayggepvrepagngpflqncwega
tan-tpcpcsvcklvy-emikadevalgtvdfaed---------dgsflk
pd-ayyvghvkg----yaaskqsklttkgkshhgnnlgehvqkngklcns
asrfghpkkpqiktlgyl---qskecdiakqkvnpcri-pvtvehkqavw
sgeqpesg--lkksrhg--------npqpgqktypyl-alrkllvktqtt
hv--dk-sicedkyp-qkavtvlgy
>node18
aftkdkp-kspakkafmryaipgsvlgsksl---alltarthlnkrntay
tifgctddlkdvssftavk-gdqtiktgtpist-qqagvrnmgvy--caf
fvtkishdgqmacggp----vklgig-ktkmqkedkpsken-ehghhnav
qdsakeahrlcawshafrapgpveaaiclla--v--errrqmqpldttpc
hyfa-qlnhfvqgsipahfl--hamaqmlgflyefglpssivspnaegaq
kslkakfsgeg---------lv----tnhlrtkgavkey--ynte-----
--vdfefaleavlmrvlrasdqv--aayggnrvrepaskgpfvqncrega
tanftpcpcsvctmvywemkkvdevalgtvdfaed---------egaflk
pd-syyvghvkggrlryakakqsrltakgkshhgnalgkhvqkngrlcns
csrfghpkkqqikelgyl---qskqcdiakaklnpcrl-p-taehkqqvw
sgqqaesg--lkkskhg--------npqpgkktyhyl-girkldvktqtt
hv--dk-svcedkyp-qkagavlgy
>ENV_HV2NZ/24-502
efskdkp-ksknkkafmryatpgsvlgctsl---dllsvkshlekrlkay
ttygcsde--dvssftaik-gdqtvktgtpvgi-qpagvrtsgvy--caf
fvnrnshdgqmacggpvgaqvkmglg-ktkmakenrpfkge-rhghhsaa
qedakeahrlcgwthafrnpgpveaaiclls--i--enhrneqplnstsc
hyfv-pvnhfaentiinifl--htmaqmlgflyefplpssivspdaagae
kslktkfsgeg---------lf----snglrtkgavkey--ytte-----
--iefqfalefvlmralrtndqv--aanggarvrepnskgpfiencrega
tanfspcpc---tmiywemkkvdevalsvvdfkes---------egaymk
pn-syyvghvkggrlrfakakqssltskgdahhgnalgkhvqknirlcts
cssfghpkkqqikdigyl---qskqcdigkvkmn-arl-p-taadsnpiw
sgqqnesg--lkkskhg--------nstpgkmpyhflggirkldvytqat
qv--dk-pvcedkyp-qksgavlsy
>ENV_HV2G1/23-502
aftkdrt-kspnkkafmryeipgpvmgsksl---alytarthlakrntgy
tifgctddlkdvssftpvk-gqdtiktgtpiss-qqagvrnmgvy--caf
fvttithdgqqncggp----vklgig-ktkkqkedrpsken-ehghhnev
qdsgkeahrlcawshafrapgpvdiaiclla--i--errrqmqpldttpc
hyfa-qlnhfvqgsipahfl--hamasmlgy------pksivspkaegaq
kslkakfigeg---------lv----anklrtkgtvkey--ynte-----
--vdfelalegvimrvlrasdqv--aayggnkvhepaskgpfvqncrega
tanftpcpcsvcamvcwemkkveevalgtvdfaeg---------egaflk
pd-eyyvghvkggrlryanvkqsrlqakgkshhgtalgkhsqsngllcss
csrfdhpkkmqikelgyldkaqskqcdiskaklnpcrl-p-tsehkqqvw
sgnqsesg--lkkskhg--------tpqpgkktyhyl-girkldvktqat
ai--dk-svsedkyi-qkagavlgf
>ENV_SIVG1/22-522
gfdkarp-pv-vadafnkygitgsclgrtalyarithlarshl-kkhp--
-qfchpadlngmtkflcgk-gqlnllgpdrldn-kfaairqlgis--tcy
fqfsarhekqrecgkp----pkrevgaktqlrnvennakva-aaaqhng-
tgkpqcphrvcahkaslrasepvdiliclle--l--khgkdvqpleylac
hpfg-nskhfvd-avngsflytrhmaas-gglyitglpapisarssesgd
kvlkadykdhavnknvlmvgla----lqyprikgdlrailslnnqpavad
vfanfnsgvdagl--etrqkes---gkfgkgkawqtpskqkyfqdckfgs
tteyvcclclecgllfwe-kkvsgpvlgkitppsq---------daaylk
sa-glyvssvqdggtaysplkgqkasvkrkarhenevknnleavalfypk
cpkythttqqiskdigyledaksdpsklikadmnvchl-p-splnchsal
gtnhadrg--spefklg--------kphpgsrsggal-svwrldvdnhgl
ls--kn-giaekrad-lkcsrvlgf
>ENV_SIVGB/47-569
gaarnvdkav-epeafamycvnsecvdadplyvkvraprrphneaqkgh-
ashckskgledpkktqtad-ggqlvfkeewlkp-aftgvkqfgif--lcf
fvldcrgskaltsrka----wgchl-lmvgfkqgiyasalg-gpihstd-
ritpevgrr------svkadggvhavsglynaga--lekwdiap--fnhc
lrfa-vgkhcgs-segsm-kvmkakrds-klifsklvptyllgkftdtfg
nalkgdgkrtq---------tgkyaanwyvkfrrfhiefedyddi-----
--ilig---m--v--dmgaggg---vrfeegakwqkqtslvwfgqcicgp
ks-yscpackicglsfwk-snighvwlgtsaaaln---------lrp---
gn-efiigadiggrlqlqlidghkavrrnktryredlvasla-slllvpf
ctsqdegipemdrvlkirpnapgndchnlkpatfacqs-l-atkstqelt
ivhhtrsgiylpgagpg--------kenhipkagqfv-mvwtpsleqq-v
kstwqqrkslrgkee-ikagvgldf
>node17
afskdkp-kspakkafmryatpgsvlgsksl---alltvrthlnkrntay
tifgctddlkdvssftavk-gdqtiktgtpvsi-qqagvrnmgvy--caf
fvtkishdgqmacggp----vklgig-ktkmqkedkplkgn-ehghhnaa
qdsakeahrlcawshafrapgpveaaiclla--v--erhrhmqpldttpc
hyfa-qlnhfvqgsipaifl--hamaqmlgflyefglpssivspnaegae
kslkakfsgeg---------lv----tnhlrtkgavkey--ytte-----
--vdfqfalefvlmrvlrasdqv--aayggnrvrepgskgpfvqncrega
tanftpcpcavctmvywemkkvdevalgtvdfaed---------egaflk
pd-syyvghvkggrlryakakqsrltakgkshhgnalgkhvqkngrlcns
csrfghpkkqqikeigyl---qskqcdiakakln-crl-p-taahsqqvw
sgqqresg--lkkskhg--------npqpgkmpyhyl-girkldvytqtt
qv--dk-svcedkyp-qkagavlay
>ENV_SIVM1/24-528
aftkerp-kpptgkafmhyaingtvlgqkal---aleqarvhlpkknavy
tifccaddlgdipsytavg-gdqtinssdpisa-qqtavrnmgvy--csf
evtrrahqsqmtcgap----gklgigaksqlqkedkpskanfqhghhnnv
qnsakgahrlcawshsfrgpgpvdaaicllp--t--avtrqvqpleimnc
hyfg-qanhfaqgsssatfv--sglaellgflyeiglpraigspnsevae
sslkapfvgeg---------lg----adhlrfsgtvqey--yskd-----
--gdlewaleavlisalrssdev--aayggnkvrdpsskgafiedcreag
tknfvpckcnvcpviywdmkkngevrlgsvdfved---------qapflk
pd-syylghvkegplryadtkqarltskskshngnalgkhaqktgllcpt
cikfphpkdrqikelgyfknaqsnqcdiakgnlnpcrl-p-tpehkhkvs
ssqqaesg--lknsklg--------spqpgkktdhyl-garklnvkttsy
hv--gk-tesdaksg-qrrgpvlgi
>node19
aftkdkp-kspakkafmryaipgsvlgsksl---alltarthlnkrntay
tifgctddlkdvssftavk-gdqtiktgtpist-qqagvrnmgvy--caf
fitkishdgqmacggp----vklgig-ktkmqkedkpsken-ehghhnav
qdsakeahrlcawshafrapgpveaaiclla--v--errrqmqpldttpc
hyfa-qlnhfvqgsipahfl--hamaqmlgflyefglpssivspnaegaq
kslkakfsgeg---------lv----tnhlrtkgavkey--ynte-----
--vdfelaleavlmrvlrasdqv--aayggnkvrepaskgpfvqncrega
tanftpcpcsvctmvywemkkvdevalgtvdfaed---------egaflk
pd-syyvghvkggrlryakakqsrltakgkshhgnalgkhvqkngllcns
csrfghpkkqqikelgyl---qskqcdiakaklnpcrl-p-taehkqqvw
sgqqaesg--lkkskhg--------npqpgkktyhyl-girkldvktqtt
hv--dk-svcedkyp-qkagavlgf
>node8
gfdkerp-pv-iaasfgryaitgaclgltplyarttpltrnhlskkhpr-
akfchpadlndmskflcak-ghqsllgpdplds-nfaairqlgiy--acy
fvfqarhekemecgkp----gkhevgakvqirkvendakva-iaahhng-
kaspkeahrlcawmasfratepvdtliclld--l--kagrdvqpleylnc
htfn-eskhfid-aingsflfkkamaes-gflydtglpapivardsessd
kilkadykdhg---------lg----vhylrfksgrrnylsynae-----
--vnfessveaal--elrqkdn---gkfgkgkawqapskgkffqdcrfgg
tkdyvccackvcaliywe-kkvggpalgsvaapnd---------egpylk
pg-sfyvgnvqgggaqyspakrtkmsakhksrhenevpdnlestcllypt
csrfkhpsqqvskeiayldkaksdecnsikadintchl-p-spknkqsal
vphhaerg--lkefklg--------taqpgkrsgayl-gvwrldvedqsl
qs--ek-ttlekrfp-akcapvlgf
