>ENV_HV2BE/24-510
ktkclgkkyy-qklhfn-------dtlqqiktgqniy----evhagaegl
takqrqli--khlgdveiyvetsr-eatc-sidpt---gdpnlwftcndr
--kkstad---hcklpdpfnts---------facggvtdkdavdae----
--lprgnikqrahekkeihsedkktlhdpavevykkv-wfmprdakgldc
lsalsagihvdnifaikalgtmkitfifffnhyfdgphysnlsaamndll
igd--gqlisgdq--eahg---acrgghfdtaveky---nrvcvcac-ig
kaglykqflllgikspllg-----d-pvgkfvs-nkarainatallled-
--------------adg-pvrntgkepttkppcrglgfkpfedlgftlir
fhdtamya-kspgkkleerrfprafqfgiqqagctlwai-ghsd-ge-qr
llvcllnraerfi------hhmha-lk---hdm-kglpdgvaigragtls
efghttantvniplssyk---------lgagrgtysdslvsnfirfvspt
n--ppstkatvgahttagykanvev-y---nespgpgtghpvggagcesf
nfps
>ENV_SIVM1/24-528
ktkciqkkyy-hrlqfk-------tdlqqvksgngiy----evha-aegl
takehryi--ahlgevsvyvatkk-qatc-padpd---gsrd-wfsceek
--nktnan---dcrietpfqts---------feiggvrekdr-qda----
--lprgtatqrvcdkksvhsssskvlenfavealkag-wflpkckkglag
lipeafgkhiekitatlalngqkitfffyfnqyfngphisqlpsathe-l
ige--hqelagtr--efng---scnggfydtaveqy---ikgcvcrc-ag
aagifkqvll-----pllg-----dvpagtlls-nkpraikntmlgmqa-
--------------adg-cvrdtgkdvatkpicqgagfkpfqelgfslvr
fhkalmya-kspgkklqerrfpkafqigiggegcalwtigghse-gdwtr
llvcilnpadkkf------hllpa-vs---hdm-gkltngkdggkgspmp
efgstavttvflpqspyk---------qgpsvvmyndsvvsnsirfasgt
dqspsstktsvgthpsmgysislkv-y---adlpghgsgillgpgaietf
dypg
>ENV_SIVV1/24-538
strcvdkryt-h---fs-------sdlqqvklsskln-------mive--
-gkqlgla--pllgdvglwryalsdrdfd-amepg---gqadlnkgyeng
--gsdnag---sssendafhst---------fgildvltkmredstagqf
alvvksa-----------aghgs--telpgtqlreaknfflprckgglak
lvatpfdiravssvpvrdlqrahfpyvftyykylekggydelpeggca-q
ine--gynlcsaakvdffh---acrggffeqdidqk---epgcicac-kg
vgpllldflk-----hivgprqlnkapsakilkagmtrtvkavlanlnqh
ec------------ensacvqnlgkrpkdyatrrgngskklhavgaglim
fhkamfyg-hppsnrldherlvcqfgipvygakctfwsinpnse-tk--r
lk----attkkkf------hvlhs-ackpgqis-dkdrlamagarktpip
-----gtntlftqlgtqr---------skpvqcskvealpgnatrfgttt
rpgssfsr-qsqnqasmgcqapgnm-v---kgipkedtpsiaaggscsrs
eylg
>node8
atkcvkkkyt-h---fr-------sdlqrvtltaaiy----svplgtegl
aarqhalg--pflgevvlhryalddkesd-gaeag---geaglkkgcdek
--ssanas---tcsntsalqnt---------fefldviekirennaagqf
vlllrgatvlfwckeaevqghga--leqpdtdlretkdlflpkcneglag
liatpfgvrvastapdiaeqrakfpfvfsfykyldkasynnlpagtcg-q
ige--gqklsgaskvdffp---acrggffgssleqk---trgctcec-tg
aasilkdflq-----plcgprklddtpvakilkpgnpktistmledlne-
--------------adg-cvqptakrprkypickgnglkklhavsfglim
fhkvkfyg-kgpalrleqdripcgyvlnvsgakctfwgihphte-kg--r
lk----trsnrkf------hllqs-vc---hds-gklrngmgggrrepla
-----gegtaftplgpek---------sgpsgctnveaqagnsirfstgt
rqgpafsrkqsqaqpamscnasekt-f---kdipneatgslvgggscsrf
dypg
>node14
ktkcigkkyy-hrlhfn-------dslqqvksgqniy----evhagaegl
takqhrli--rhlgdvtiyvetsk-eatc-sidpn---gapnlwfscndr
--nestad---hcripspfnts---------facggvtdkdavdae----
--lprgtrqqrtcerkeihsedkktlqdpavevykkv-wfmpkdakgldc
lsaqsygihvdniaatlalggmkvtflfyfnhyfngphfsnlsaamndll
igd--gqllagar--dfhg---acrggyfdtaveky---nrvcvcrc-ig
kaslfkqfll-----pllg-----dvpvgklls-nkarainatlllled-
--------------adg-pvrdtgkepatkppcrglgfkpfqdlgftlir
fhdtlmya-kspgkkleerrfprafqiginqagcalwtitghsd-gewqr
llvcllnraerfi------hflha-lk---hdm-ktlpngmgcgraspls
efgnttpstvyiplspyk---------lgavqgtyqdsvvsdsirfaspt
nqgppstkatvgthstagykanlev-y---netpgrgtghlvggggcesf
nypg
>node10
ktkcigkkyy-hrlhfn-------dslqqvksgqgiy----evhagaegl
takqhrli--rhlgevtiyvetsk-qatc-svdpn---gapnlwfsceer
--nkstad---hcripspfntt---------faiggvtekdavdae----
--lprgtrtqrlcekkeihsqdsktledpavevykkv-wfmpkeakgldg
liaesygihvdniaatlalagmkitfffyfnhyfngphfsnlpaathe-l
igd--gqqlagar--dfhg---acrggyfdtaveqy---irvcvcrc-ag
kaslfkqfll-----pllg-----dvpvgklls-nkpraikatllflee-
--------------adg-cvrdtgkepatkprcrgagfkpfqdlgftlir
fhkslmya-kspgkkleerrfprafqiginqegcalwtitghse-gewqr
llvcilnradksf------hflha-vk---hdm-gtlpngmgggrasplp
efgktapttvylplspyk---------kgpvqgtyqdsvvsnsirfaspt
nqgpasskatvgthstmgykaalkv-y---knipgrgtghlvggggcesf
eypg
>ENV_HV2G1/23-502
ntkcigkkyy-hrlhft-------dsltpiksgpsiy----dvhggaegv
dgkqhkli--rhlgdvtiyveesr-qatc-eitpn---gapnvwfacndr
--nestad---hcrvpspfnts---------faigavidkdavdte----
--lpkgtrehracekkeihsedkktlenpavevykds-wfmpkeakgldc
liaqsfgihveniaaslalggmkltfffyfshyfngphfselpgalneli
igd--sqqlagar--dfha---asrggyfdsaveqy---irvcvcrc-vg
kaslfkqflf-----pllg-----dvpagklls-nkaraikatlllled-
--lgvcllglnknlang-pvrstgkqpaskprcrgagfkpfqdlgfklir
flkslmyt-kspekkleerrfprafaiginqagcalwtitgqse-gewrr
llvsllnraerff------hflha-vk---hdm-gtlpqgmgcgraspls
efgksspttvfiplspyk---------lgpvqgtyqdgvvnnsmrfaspt
eqgppkskatmgthstmgykaalev-y---nnlpgrgtghliggggcesf
eypg
>ENV_HV2NZ/24-502
ktkcigkkyf-nrvhfn-------dtlqqaksgqnic----emhagaegl
takrqrli--khlgdvtiyvetsr-qgtc-svdsn---gssnlwhkcner
--nestae---hcnepasfsat---------ftsagvtdykavdte----
--sprgtrqgrtcerkeihsedkrlleqppcevfesv-nfmpkdakgldc
ltaqsygihvadiavalalggttltfffffhhafngphfgnlpqtkaell
vad--gqqlagsq--efhg---acrdgyfdaaseky---ervcvcrc-ag
kaplvkqfll-----pltg-----dkpvgklls-nkarvlkaslllled-
--------------add-pvrdtsnepatkprcrglgfkgfqdlgftlik
fhksltca-ktpekmleerkfprafkiglnqagcalwtasshsd-gdwqk
llvclhdreerff------hfldc-vk---hdm-gtlpsgmgcsrasams
elgktdrttvyialskyn---------lgaipgaytdplvtnavrfpsp-
----pstkatvgrhttmgyttdldv-y---ndipgrgtghlvggggcesf
eypa
>node7
ttrcvkkryt-h---fr-------sdlqrvkltaaly-------mgregl
aarqqalg--pflgevvlqryalddrgtd-gmesg---geaglkkgcdng
--tadnas---scsntaafqnt---------ftfldvlekirensaagqf
vliliaa-----------sghga--veqpdtelreakdlflpkcngglak
liatpfdvrvawtvpsiaeqrakfpfvfsfykyldkasynelpdgtcg-h
ige--gfklsaaakvdffp---acrggffggdleqk---srgctcec-kg
vgpllrdflq-----hlvgprqldktpvakilkpgsartvsatledlne-
--------------ansacvqpltkrprnypickgnglkklhavsaglim
fhkvmfyg-eppstrleqnrlpcqyvievygakctfwginphse-kg--r
lk----trsnrkf------hilqs-vc---qds-dkdrlamggarraplp
-----gantlftplgpek---------sgppgcpkvealagnstrfgtgt
rqgsafsr-qsqgqpamscqasekm-i---kdipneataslagggscsrs
qylg
>ENV_HV2D2/24-513
ktkcigrrsy-hrhhfn-------dslqrlkssqg------dvhagavgl
takqhrvf--rhlgiviifvetqm-qatc-svdpn---gasnlwfsseer
--nkstad---hcrlpspfnvk---------imigggvekdaidad----
--largactqrlcekedlhsldsktleqnapqlykkf-wfmpkelqlldg
lilesfgvhfegiaaalelagmkitfflyftryfngphfsneagathe-l
igdsggqhldgss--dlhg---tcrggyfdgaieqy---ircsvcnc-sd
kaslfkqfml-----pllv-----evpggsllt-gssraikaallflqg-
--------------tdg-cvrd-gkepakkpscrpagfkpfqqlnfglvr
fhkflmia-kspgkkleqrrfprafqigveqdgcdlwvttghse-gewqr
lavcilkktvqsf------qylha-vk---hqs-nafptgmggsraftlp
pfqktapaaaylplspyk---------kgpvqttyqdsv-kinirfadpk
nsgnaaagatvgthsamgykaalkv-ygaakdipqrgaghlvggggaekg
eyst
>ENV_SIVG1/22-522
tsrcvklrfe-h---fr-------celrkvklaavsy-------msregl
aarhqalg--allgdvvikryalddrgtd-gaesd---gevglrkgcdng
--eadnas---gcsntaaf--t---------ftflgvlarlrqysaakqf
vllliav-----------gshga--tdqadtelrttkdiflpkcnsgltk
lkavpldvkvawfvpsiaaqrarfpvvfsfykyl-kasyqelpkgtcg-n
vgq--gfklsagervdffp---evrggffsgdlepksfvfrgctcec-kg
ggpltsdflr-----hltgsqqsdmtavakilkpgsartvkatlidlnv-
--------------ansacvqpltrryrkypdcngnglkklpavaaslim
fhkvmayg-eppstrleqnrlpcqyvvqaysakctywgihpsse-kg--r
lr------snrsl------qilqsvvc---qds-gkerlvmggarraglp
-----aahtlftplgkek---------ggppgv--vdalspnstrfgtgt
kqsaafer-ksqgqqamscqasekm-v---kdipneatasvagggscsss
dylg
>ENV_SIVGB/47-569
gqgcvad-ytis---frfngdivffesdk-------kpkyydlaipssnf
fpsgqhmv--pfvghvmlhrfsvcrrdketcteavkdmikkaarascdkv
--prlrln---apnggtalfldvpldqwvrfydwsvtadkigqesgggaf
pdalrfsgilf----------------mtsagfrathsllldkcadaltp
lfgrtfgakksa--revq-magkh-tafsfinyldktgliplr-mnpg-d
vdg--ksrvmkdkklhyfpifhggnkkfflqdvpeq---mcvcvyasavn
i---lafflt-----pvt-csktgkasgacspkpgspaaiflklttchk-
--------------gsv-ckkkkvvprgtgplckspgfvkcelmeidvhl
fkglklyg-advilklgeekvrstyvgevnyamctlwgtppfqgylc--r
lf----seahrky------ephhp-st---ddaaekltegpkegrt----
------agaklsp---------------gplvctnv-----khsrfh---
--dqdhlrkdaegeervvctytskraf---kkkhkppagmwntggschrf
plcl
>node9
ktkciqkkyy-hklhfk-------tdlqqvksgqgiy----evhagaegl
takqhrlv--phlgevsiyvettk-qatc-sadpd---gsrnlwfsceer
--nkttad---hcriptpfqtt---------faiggvtekdradne----
--lprgtatqrlcekkeihskdsktledpavealkat-wflpkcakglag
liaesfgvhidkiaatlalagqkitfffyfnqyfngphfsklpsathe-l
ige--gqqlagar--dfng---acrggfydtaveqy---irgcvcrc-ag
aagifkqfll-----pllg-----dvpvgklls-nkpraikatllnlqe-
--------------adg-cvrdtgkepatkpicrgagfkpfqdlgftltr
fhkslmya-kspgkkleerrfprafqigiggegcalwtisghse-gewqr
llvcilnradknf------hllha-vs---hdm-gklsngmgggrasplp
efgktapttvflplspyk---------kgpvqgtyqdsvvsnsirfasgt
nqgpasskttvgthptmgykaslkv-y---kdipghgtghlvggggcesf
dypg
>ENV_HV2D1/24-501
ktryigkkyy-hrlhfe-------dslqpvksgqdiy----qvhdnaeal
satqhrlipekhlgditiyvdtdk-actc-sldpn---gapslwfscndr
llndstadhpaqcr--spfitp---------facgggadkqateae----
--lprgtqqqrtcerkdmhsedkagaqdpavevykkv-wfmqkdekgldc
lsaqsygihadniaatlalggmkvtylfffnhyfngshfanldaamnnll
ige--gqllgsar--dfhd---acrggyfdsavesy---nrtcvcrc-ik
qaslfkpfll-----pllg-----dapvgklls-nkaqcinatlllled-
--------------edg-pvrdtgkepasnppcrglgfktfkdlgftiik
fhktlvyadsspgkkleerrfprafqiainqagcalwtiashsd-gewqq
llvcllnraerficqetvehflha-ls---gdm-ktlpngmgcgrasals
dfgnttpstayiplspyqkmypglflllgaaqgtyqepvvsdsirfaspt
nqgpprtkaavgthstagyksnlel-y---ngtpgrgtghvvggggcesf
nypg
>ENV_HV2CA/25-512
ktkcmgkkyi-hrfnfg-------dtlqqvksgqnvy----dvhsaaegl
takdqrlv--rhlgdvtlhvdtsk-qatc-sqdae---gtinlwfvckdr
--nessad---hcsipspfntt---------fpsggvtdkdgvdtq----
--sp---raqricekkeinheekklledpavevykkv-wflpkdakglac
liadsygvhvdgiaatlnlggkklafffyvhhafn-phfgtlppavlell
igd--gqqisgar--dfhg---acrgaffetaveky---srvcvcrc-vg
kaslftqfll-----pllg-----dvpvgklls-nkaraikaslqlqed-
--------------sag-svrgtqkqpatdppcrglkfkpfqdlgltlir
yhkslmca-kspekmleerrfprplqiginktgcalwtltghse-gdwek
tlvclldrsgpff------hflha-vk---hef-ntlpagmgcgranpls
dfgrttpttayiplrpyk---------lgavpatsaddvvsnsvriaspn
tqgppstnatvgknttvgyttdltv-f---sqipgrgtghlvggggcesf
eypg
>node11
ktkcigkkyy-hrlhfn-------dslqqvksgqniy----evhagaegl
takqhrli--rhlgdvtiyvetsr-qatc-sidpn---gapnlwfscndr
--nestad---hcripspfntt---------faiggvtdkdavdte----
--lprgtrqqrtcekkeihsedkktledpavevykkv-wfmpkdakgldc
liaqsygihvdniaatlalggmkltfffyfnhyfngphfsnlpaamnell
igd--gqqlagar--dfhg---acrggyfdtaveqy---irvcvcrc-vg
kaslfkqfll-----pllg-----dvpvgklls-nkaraikatlllled-
--------------adg-pvrdtgkepatkprcrgagfkpfqdlgftlir
fhkslmya-kspekkleerrfprafqiginqagcalwtitghse-gewqr
llvcllnraerff------hflha-vk---hdm-gtlpngmgcgrasplp
efgkttpttvyiplspyk---------lgpvqgtyqdsvvsnsirfaspt
nqgppsskatvgthstmgykaalev-y---nnipgrgtghlvggggcesf
eypg
>node18
ktkcigkkyy-hrlhfn-------dslqqvksgqniy----evhagaegl
takqhrli--rhlgdvtiyvetsk-qatc-sidpn---gapnlwfscndr
--nestad---hcripspfntt---------fasggvtdkdavdte----
--lprgtrqqrtcekkeihsedkktledpavevykkv-wfmpkdakgldc
liaqsygihvdniaatlalggmkltfffyfnhyfngphfsnlpaamnell
igd--gqqlagar--dfhg---acrggyfdtaveky---nrvcvcrc-vg
kaslfkqfll-----pllg-----dvpvgklls-nkaraikatlllled-
--------------adg-pvrdtgkepatkprcrglgfkpfqdlgftlir
fhkslmya-kspekkleerrfprafqiginqagcalwtitghsd-gewqr
llvcllnraerff------hflha-vk---hdm-gtlpngmgcgraspls
efgkttpttvyiplspyk---------lgavqgtyqdsvvsnsirfaspt
nqgppstkatvgthstmgykanlev-y---neipgrgtghlvggggcesf
eypg
>node19
ktkcigkkyy-hrlhfn-------dslqqvksgqniy----evhagaegl
takqhrli--rhlgdvtiyvetsr-qatc-sidpn---gapnlwfscndr
--nestad---hcripspfntt---------faiggvtdkdavdte----
--lprgtrqqrtcekkeihsedkktledpavevykkv-wfmpkdakgldc
liaqsygihvdniaatlalggmkltfffyfnhyfngphfsnlpaamnell
igd--gqqlagar--dfhg---acrggyfdtaveqy---irvcvcrc-vg
kaslfkqfll-----pllg-----dvpvgklls-nkaraikatlllled-
--------------adg-pvrdtgkepatkprcrglgfkpfqdlgftlir
fhkslmya-kspekkleerrfprafqiginqagcalwtitghse-gewqr
llvcllnraerff------hflha-vk---hdm-gtlpngmgcgrasplp
efgkttpttvyiplspyk---------lgavqgtyqdsvvsnsirfaspt
nqgppstkatvgthstmgykaalev-y---nnipgrgtghlvggggcesf
eypg
>node17
ktkcigkkyf-hrlhfn-------dtlqqvksgqniy----evhagaegl
takqqrli--rhlgdvtvyvetsk-qatc-sidan---gapnlwfacndr
--nestad---hcripspfntt---------fasggvtdkdavdte----
--sprgtrqqrtcekkeihsedkklledpavevykkv-wfmpkdakgldc
liaqsygihvdniaatlalggkkltfffyfhhafngphfsnlppamnell
igd--gqqlagar--dfhg---acrggyfdtaveky---nrvcvcrc-vg
kaslfkqfll-----pllg-----dvpvgklls-nkaraikanlllled-
--------------adg-pvrdtgkepatkprcrglgfkpfqdlgftlir
fhkslmca-kspekmleerrfprafqiginqagcalwtitghsd-gdwqk
llvclldraerff------hflha-vk---hdm-gtlpsgmgcgraspls
efgkttpttvyiplspyk---------lgavpgtyadsvvsnsvrfaspn
tqgppstkatvgthttmgykadlev-y---neipgrgtghlvggggcesf
eypg
