>ENV_HV2NZ/24-502
gdllsd-----pcvgseaalpr---kllakgkkam-----vh--ts-pl-
htpgnsvrmratqksfaplkhayqggrggiqaqdikdlgdemeysdigl-
vgsssmkin-ngl----------lqcs-gnvqf-fktvgd-kgsleclkp
eckvqcrak----------rhhpvlygtsve--lfscdlpcpnmlatgtd
rkfrtkrp---ckadgnaakgkgglhgsa--eglkaaseykeakalpsts
ggtewqeaiettwhrghggqyygfekaalftpplihpppalcegarmktf
setaivgliksgpafqgvfkliepktt-vqytniklprlclcgpll----
-lksmgdkqpkl--ekmatf-------ldkf-rnslvvniwkl-------
---cltpelqyegaivesaaqfkevgpksntatvqddailatvknvkpat
k------tlecqaglnfsgsnpskesqytrycdtatfpkkgskne-yhnl
pekknngktgtarapgakfhs-gigaagv---wlts-----dqlgiknrt
--kakgrsdditdsgdtilvst-----nmpkyqqadgqcvknss------
--inl
>ENV_SIVM1/24-528
gellaa-----pcvgktcavss---kpkakknhav-----lh--tt-sl-
htpgkghrlrsnqkslaplrcagksgvggvharsvkilgnqmtysligl-
lgdksqklh-edl----------lscs-anllf-fkavad-hgalqclkp
eckaqcrak----------rhhpilyltate--vfgclipcalksaagin
rkdrtqrp---vkadgkagkgnaalhatt--eglkngnefkegqvldglt
sdsawpaatttt----hagqyyvfdkaglvtpqltvpprafcegarmdtf
pgigvsnlikegpvylghykvvqhkvt-iqyteiklhrlclcghli----
-tkgmadkqppr--samgtf-------inrf-rnalmvnfrkldyieqsa
avdcllgelryqgnvqetgvqfkdvgsktnvtpvldnaklgsvrhvkpsl
k------qrecgggldypycspsenarynkycktvtfptkkkksd-whqq
vekknngkattvrahgsknqs-gtngagv---wltaeqmaentlgfkari
--kaigrgehitdrnseilvgs-----ikpkyqckhgqlvmsag------
--ini
>ENV_HV2G1/23-502
gellsa-----pcvessaalsr---klmangkkam-----vh--ta-sl-
htpgkshrmkatqksfaplkctakegsggsharsikdlanqmdygsigl-
ggaksqeih-esl----------lkcs-anlqf-fktvgd-rgpleclkp
eckvqcrak----------rhhpilyltsne--lfscllpcalmlatgin
rkirtkrp---caadgkaakgngalhatagdeglkhgsdfkaaqalagdt
adsawqdavttt----qggqyyvfetaglinpqltppprafcegermktf
gdtgvaslfkdgpaflgvykltehkst-ieyasiklprlclcghli----
-lksmadkqpkl--etmatf-------idsf-qsslmvnfrkl-------
---clmgelqydgtvvesaaqfkeigsktntttvvddgklasvkyvkpam
k------trecgkglnysfnnpdeesryaryceiatfpkkgkrnd-cqnl
vekkdkgkgatarghgartts-gtgpagv---wltgqrttehqigikgrt
--katgrggditdsgseilvas-----nmpkfqqkngqcktsag------
--ini
>ENV_HV2D2/24-513
gdllsa-----pivggsaaltq---klmgkgktam-----vh--gg-slv
htagkshvmretqkafaalkcackdgsggvqarsikalakevdysaigl-
sgdkgqkah-etl----------lkcg-anvkf-fntigd-htpivcfep
eckvdcrsk----------rhqpikfleatq--lfsclvpcaimlamgih
rkfrtyrp---cnadgyaakgneaghgta--agikagaeykeavtlagkd
sdsawaetvisn----hggeyyvfekngl-tpsltppprafceggsmkkl
pddgvtghinevpaylgvyklighkts-lefaeislpriclcgnli----
-lksmaeappyl--etmdgypepharyvetf-rvslkmsfskv-------
---clmgdleyaglavaaglqfkavgsktdsatalddgklatvkhvrpdl
k------drdcgtglgnsfsdpsnespy--yivkatfprkakrmd-yhds
vepkkngkgatghghgikwhs-sdaaggv---wltgnrthehvlgisant
qlkakersddqtdsggellvat-----nmpkyqrrhgqvvsseg------
--ina
>node7
gevlla-----qc----vglts---glktkakqai-----lakshvdgt-
hspgsstrlsktkkvhtslksgcy----lvhtkcrkdlpedllyntitl-
aiggsnsvs-dgl----------lkcp-apcff-mnafad-rcpvagsts
------sal----------kvhqilytthtkgrratckircilmlptalr
ktainkak---avktgstaqresaisett--dnlhtt--------ldgmt
wsskwranattd----dkgqiytfpkealilphltplpkvfcegtrmaff
yaaavhkmtaedpvyrgevkdvehkvk-ieyttftlndlplcqgpagkel
skkamaknisdqdaaavpki-------rkvy-kdkiivsfgkldyisdyr
tvnylrgdlsyeggveatavlfthvgvtstrltqlaegtvdtirflagsl
r------arecfpssgygycgpssnsrfgeyceatdfpfrnqdgtqwhel
vskrlnakiegirshdladhp-gasagpr---wtvckrgsrhaigfkgir
--k-kdkvekvladggayl-dd-----fkpkyeletghvvtptg------
--tsa
>ENV_SIVG1/22-522
gqvlla-----qc----vglss---glktqakqav-----fakshldst-
hspgastrltktskvptslkygty----pvhtpyrkdlpedllypsial-
avggsdsvs-dgl----------lkcp-apcff-mkpfag-rcpfagkts
------sal----------kvhdnlysthtksrrdtckircllilptalr
ktainaa----avktgstadrdsaisdtn--dnlhtt--------ldgmt
wsskwratattd----ekgqiytfptgaiilphltplpkvfcegtrmaff
yaeathkmtaedpvyrglvkdvehkvk-ieyttstlndlyhcqgaagdel
skkamennisdkdaavvpki-------rkvy-ddtiimsfgkqdyisdyr
dqdywrgdlsyelgveaatvlfthvgvtstrltglsqgnvatirflagsl
r------grecfpnkgyaycgpatnnrfgdfcedtdfpfrledstqwhdl
vsk-lnstiegirshhladhp-pasggpr---wtvckhgsrhaigfkgir
--k-kdqvekvladgaeyl-dd-----fkpkyelktnhvvtpvsglspvn
lptsd
>ENV_SIVV1/24-538
gevlla-----sc----vaitgkklnlkkrakqai-----lsksiaaga-
nnpdtsrrknktknvh-alksgcy----llhikcskdlpetlllnvmnl-
apagtntvt-ngp----------lkcv-apvff-msgfad-rcpkagsta
------agl----------kihailytthskgrkascnlrcvlvlptalr
etavndam---sdyaapsaqhegalnats--h-lhta--------ldgki
wptkwksdttae----ekgqilafsketlelshltplpkvycegkrmaff
faaailkataedaaykgdakdvdfsvr-tqattfalgdlpiakcpmgphl
skkamstgeadgdssagrkv-------kkvf-kdkiivsfgildyievyr
kvevlrgsmsyegseeanpmlftyidvtpakltqltegnpqsvrfligtl
rpcltpcardcypaspyavcgptskirfeefcrttdapfrdndgvdwhnl
vaksldakiqarrshglashkggatagpr---wtvckrgskhaisfe-tr
--t-keklekvvgkgglyl-ap-----fkpnyeldlghvvtatg------
--tsa
>ENV_SIVGB/47-569
eeglpd-----nc----rslai---alsvkhsknd-----ki--ecpgq-
qgeesikgvvkapqvlveikctcydaq-------sedailecpfshtait
akhsgrvvtayaplrprfaqlcflkcr-avcky-ldkvgewkcpcltvve
------cpvemdiavvadltadllaeltvadg--ggratrcgqvlslatr
heaisegk-hsgavgdrwgt-----ne-----alell--------fvgls
wkqlwaateega----hk--igayakdsaglsslsgtsntfcellrgkny
ddaalkralpappefkgqvpahikdgkvidfavfgahgpalvlnss----
-rvafradaipe--devell-------stlysigvidvcfgsatfqklek
ygiilkltikyvfagppilalfaggelakyrervlpacalvtksffegal
r------ahgct----ypftgdahgdtygvlceitgypfpivdatawpkn
itnvagdggd-vkk---kvrk-ag---dd---wtvnkrgrvstysldwks
--g-gvrktsefsgdggfq-qdkmavqknppyemdlglg----g------
--kal
>ENV_HV2BE/24-510
shmlsslaspppcvgsgvalpr---nlmakgkkamkanrevh--tt-tl-
hipgksrrikatlksfaplk----egsggvhtrpkkdyanmmdysaigl-
agaksqkiq-eal----------lkcs-advqy-fttvgd-qasleslkp
eckvqcrak----------rhhptlyltsiq--nfscllpcalllatgik
rrfrtkhpa--ckadgnaakgngakhgta--eglkddstfkrgqalagtg
gdsawqeavivt----hgglfyvfekigqfapqlvppprlfcegarmktf
gdtgvsalvkdgpaylgvykliehktv-feytsttvpslclcghli----
-lksmvqkqpkl--ptmatf-------igrf-rsnlmvnfrrv-------
---clmgeleyegtivesvapfkevssktntttvldggklatvkyvkpgm
k------tkdcgsgldysysnpsdessytrycetaafp-kgkkhn-y---
----------tsrahgakths-gigasdv---wltgqrstqhqvgikgre
--nakgradditdsgeqilvpt-----dkkkyqqknrecvksag------
--knv
>node10
gdllsa-----pcvgssaalsr---klmakgkkam-----vh--ts-sl-
htpgkshrmratqksfaplkcackegsggvharsikdlanqmdyssigl-
agdksqkih-eal----------lkcs-anvqf-fktvgd-hgpleclkp
eckvqcrak----------rhhpilyltate--lfaclipcalmlatgin
rkirtkrp---ckadgnaakgngalhgta--eglkdgsefkeaqalagtt
sdsawpeavttt----hggqyyvfekaglitpqltppprafcegarmktf
pdigvsglikegpaylgiyklidhktt-ieytniklprlclcghli----
-lksmadkqpkl--etmatf-------ierf-rsalmvnfrkl-------
---clmgelqyegtivesaaqfkevgsktntttvlddgklatvkyvkptl
k------trecgsglnysfsnpseesrysrycetatfpkkgkksd-yhdl
vekknngkaatarahgaknhs-gtaaagv---wltgerttehtigikgrt
--kakgrsdditdsggellvat-----nmpkyqhkhgqvvksag------
--ini
>node9
gdllaa-----pcvgssaalss---klkakkkkam-----vh--tt-sl-
htpgkshrlrskqksfaplkcacktgtggvharsikelanqmkysaigl-
agdksqklh-edl----------lkcs-anvlf-fktvgd-hgpleclkp
eckaqcrak----------rhhpilyltate--lfaclipcalmlatgin
rktrtkrp---ckadgnagkgngalhgtt--eglkngsefkegqaldglt
ndsawpeavttt----hggqyyvfekaglvtpqltppprafcegarmetf
pdigvsnlikegpvylgqykviqhkvt-ieytniklhrlclcghli----
-vksmadkqpka--aamatf-------ierf-rnalmvnfrkldyveqak
avdclmgelqyegtvaetavqfkevgsktnttpvldngklatvkyvkptl
k------trecgggldysycspsenaryskycdtatfprkkkksd-whdl
vekknngkaatvrahgsknhs-gtagagv---wltgerttehtigikgri
--kakgrsenitdsggellvat-----ikpkyqhkhgqvvksag------
--ini
>node14
gdmlsa-----pcvgsgaalsr---klmakgkkam-----vh--ts-sl-
hmpgkshrvkatqksfaplkhackegsggvharpikdlanqmdyssigl-
agaksqkih-eal----------lkcs-anvqy-fqtvgd-hgpleclnp
eckvqcrak----------rhhpilyltsiq--nfscllpcalmlatgik
rkfrtkrpa--ckadgnaakgngalhgta--eglkdasefkeaqalagtt
sdsawqeavttt----hgglyyvfekiglitpqltppprafcegarmktf
gdtgvsglikegpaylgvykliehktt-ieytnikvprlclcghli----
-lksmadkqpkl--qtmatf-------idrf-rsslmvnfrkl-------
---clmgelqyegtivesaaqfkevgsktntttvlddgklatvkyvkpam
k------tkecgsglnysfsnpsdesrytrycetatfpkkgkknd-yhnl
vekknngkaatarahgakths-gigaagv---wltgqrttqhqigikgrt
--nakgradditdsgeeilvpt-----nmpkyqqknrqcvksag------
--ini
>node19
gdllsa-----pcvgssaalsr---klmakgkkam-----vh--ts-sl-
htpgkshrmratqksfaplkhackegsggvharsikdlanqmdyssigl-
agaksqkih-eal----------lkcs-anvqf-fktvgd-hgpleclkp
eckvqcrak----------rhhpilyltste--lfscllpcalmlatgin
rkfrtkrp---ckadgnaakgngalhgta--eglkdssefkeaqalagtt
sdsawqeavttt----hggqyyvfekaglitpqltppprafcegarmktf
sdtgvsglikegpaylgvykliehktt-ieytniklprlclcghli----
-lksmadkqpkl--etmatf-------idrf-rsslmvnfrkl-------
---clmgelqyegtivesaaqfkevgsktntttvlddgklatvkyvkpam
k------tkecgsglnysfsnpseesrysrycetatfpkkgkknd-yhnl
vekknngkaatarahgakths-gtgaagv---wltgqrttehqigikgrt
--kakgradditdsggeilvat-----nmpkyqqkngqcvksag------
--ini
>ENV_HV2CA/25-512
gdllat-----pcagseaalsr---kpladdvkal-----ah--tr-pm-
htpgkahrmraaskefapfkhgckevsggvhamgirdlgnqmdysstgl-
agaktmkih-esl----------akcsganvef-fkdvgn-hgpleclkp
eckvqcrak----------rhhpvlyltsee--lfgsllpcaqmlvtgin
rrfrtkrp---csidgnasrgkgalhgsa--ealkeasqfdqalalsgvt
sasawveavtts----cdgeyymfekaglvtaqltpparafcpsarmkaf
sdtavsglikegptylgvykliehkkt-veftniklpklcncgllv----
-lksmedkqpkl--eamatf-------inkf-ptslmvnfkkl-------
---clmaelqyesriveaaakytevgaktntatvhddailasvkyvrpam
k------tkecgvglnysynnpsnespysryceqaefpkkgkmnd-fhnl
aekknngkagtarapgaktqa-gtgapgv---wvtn-----knlgikgrv
--qakgreddesdnggevlvps-----ympqyqqtngqcvkssg------
--fkl
>node11
gdllsa-----pcvgssaalsr---klmakgkkam-----vh--ts-sl-
htpgkshrmratqksfaplkcackegsggvharsikdlanqmdyssigl-
agaksqkih-eal----------lkcs-anvqf-fktvgd-hgpleclkp
eckvqcrak----------rhhpilyltste--lfscllpcalmlatgin
rkirtkrp---ckadgnaakgngalhgta--eglkdgsefkeaqalagtt
sdsawqeavttt----hggqyyvfekaglitpqltppprafcegarmktf
sdtgvsglikegpaylgvykliehktt-ieytniklprlclcghli----
-lksmadkqpkl--etmatf-------idrf-rsslmvnfrkl-------
---clmgelqyegtivesaaqfkevgsktntttvlddgklatvkyvkpam
k------tkecgsglnysfsnpseesrysrycetatfpkkgkknd-yhnl
vekknngkaatarahgakths-gtgaagv---wltgqrttehqigikgrt
--kakgradditdsggeilvat-----nmpkyqqkngqcvksag------
--ini
>node18
gdllsa-----pcvgssaalsr---klmakgkkam-----vh--ts-sl-
htpgkshrmratqksfaplkhackegsggvharsikdlanqmdyssigl-
agaksqkih-eal----------lkcs-anvqf-fktvgd-hgpleclkp
eckvqcrak----------rhhpilyltsie--lfscllpcalmlatgin
rkfrtkrp---ckadgnaakgngalhgta--eglkdasefkeaqalagtt
sdsawqeavttt----hggqyyvfekaglitpqltppprafcegarmktf
sdtgvsglikegpaylgvykliehktt-ieytniklprlclcghli----
-lksmadkqpkl--etmatf-------idrf-rsslmvnfrkl-------
---clmgelqyegtivesaaqfkevgsktntttvlddgklatvkyvkpam
k------tkecgsglnysfsnpsdesrysrycetatfpkkgkknd-yhnl
vekknngkaatarahgakths-gtgaagv---wltgqrttehqigikgrt
--kakgradditdsggeilvpt-----nmpkyqqkngqcvksag------
--ini
>node17
gdllsa-----pcvgseaalsr---kllakgkkam-----vh--ts-pl-
htpgkshrmratqksfaplkhackegsggvharsikdlgnqmdyssigl-
vgaksmkih-esl----------lkcs-anvqf-fktvgd-ngpleclkp
eckvqcrak----------rhhpvlyltsve--lfscllpcaqmlatgid
rkfrtkrp---ckadgnaakgkgalhgta--eglkdasefkeaqalagtt
sgsawqeavttt----hggqyyvfekaglitpqltppprafcegarmktf
sdtavsglikegpaylgvykliehktt-ieytniklprlclcghli----
-lksmadkqpkl--eamatf-------idkf-rsslmvnfrkl-------
---clmgelqyegtivesaaqfkevgpktntatvqddailatvkyvkpam
k------tkecgsglnysfnnpsnesrysrycetatfpkkgkknd-yhnl
aekknngkagtarapgakths-gtgaagv---wltn-----hqlgikgrt
--kakgredditdsggeilvpt-----nmpkyqqkngqcvksag------
--inl
>node8
gevlla-----qc----vglts---glktkktqai-----la--hvegt-
htpgkstrlsktpkvltslkcacykgegavhakcrkelpeeaqynaitl-
avdgsdsvs-dgl----------lkck-gpcff-lntvad-rcpvvcats
------sal----------kvhtilysahtkgrrgtctvrcilmlptgih
ktaiskak---gidagstgkreaaleett--dnlhts--------ldgms
wsskwpaddttn----nkgqiytfgkealvlphltplpkgfcdgtrmaaf
hdagvskltaedpiyrgevknvehkvk-ieyttftlndlplcqgpa----
-kkamaddtpdq--asvaki-------mkiy-kdkikvsfskldyisdhr
tvsylrgeltynggvaatavlftqvgvttnrktvlaegkidtirflattl
r------arecgpsagysycgpssasrygeycdagnfpfrkqdgaswhel
vsknanasadgirshglkdhp-gssaggr---wtickrgthhsfgfkgik
--k-kervekvltkggsfl-dd-----fkpkyeletgqvvtstg------
--asa
>ENV_HV2D1/24-501
gdmlsa-----pcvgsgsalgr---elmakgkkal-----vh--tt-sl-
hmpgkahrvkatqksflplkhackegsggvearpikdlanqityssigi-
agaksqkih-eaq----------lkcn-anveywfqavgd-hgpleclhp
eckvgcrad----------rhhpilyltniq--nftcllacclmlatgik
rkfktkrpa--ckadgnaakgngglhgta--dslkdasetkeapalaggt
sdsawqeaqttt----qgsiyyvfakiglitpeltpsprslcegir----
--tgvtglikqgpaylgvyrliqhktt-ieytnikvprlclcghli----
-lksmgdkqpkl--qtmatl-------idtf-kssimvnfrkl-------
---clmaellyegtivesaaefkevgnststtav-----fiivkyvkpam
k------tkecgsglnysfsnpsdesrytrycesaafskrgkknd-fhnl
vekknngkaatarahgakshd-glgtngvyaswltgqrtadhqigikgrq
--nakgkadditdsgeenlvpt-----hlpkykqtnrqcvksag------
--ini
