>ENV_HV2CA/25-512
-ipsrmsrhlssfatkstdlrkiklklnkttgtqcaaqll-iltktifmt
eltms--kplgctdprisrw-gveingathrelwklkpgpeclvkgkedq
seckrqwakdsvgkadkskigchlknlrydtnrnfd------yk--tgna
dkqnatdsaneglttdnrgakaygalavigq--ftgevtttsmlpgngt-
-kgtddtgrltvl-----patracllwldrsakrrwrgvsegdts--lli
glcgltskahgl---wcfssgrsclnqy-tve--sdsa----qne----q
qsgkwngsqnlkfssrafvllygecl-f-hnhfyllyqpegkyfsstpey
rv----klhg---iclqalsknnalqvsgrmkytskplkehakvlqnkir
vpdercgrhtt-ggidpvakpsnpaeandnpggdlpikpaelnlcc--kr
tendpslcm-eevysh-----------gneesld---akiveaqptdsrh
arsspk-----vqtricavnatafsklpafklr---espfgllfll--af
kkpddshfentgcdpqggeen-yla
>node19
-vpsrmkrhlsnfskkstdlkkiklklskttntqcaaqll-rltktifmt
dltas--qplgctdpriskw-giaiagaihrelwklkpgpeclvkgkedq
techqqwakdhvskpkksriachlanlkydtnsnfd------ys--tgea
eravakdggneglttdnrgekaygelaligk--ltgqvgtgtmlavsgt-
-rgtkatgrltvv-----patkgcimwldreakrrwsgvaevdtg--llr
glcgqsrkahgl---wffnsgricvnqy-taa--tena----qne----q
ksgvwnssqnlkfsskafvllysecl-f-hdhfyllyhpegqyinstpdy
rv----tlag---iclqglfktntlqvagkmayaenplkqhvktlqnrtr
vpdqrcgrhtt-ggeepvakpsdpaeanespggelpiepaeldfcc--kr
sdnepsmcmgsnayph-----------gndesld---ckivdtqpadsrh
gpsspk-----vhtricavnatafnkleafklr---nspfgllflk--al
ndpddshfeptgcegqggeen-yla
>node10
-vpyrmkrhlknfskkstdlkkiklklskktndncaaqll-rlaktlfms
dltes--qplsctnpriskw-giaiagaihrellklkpgpeclvkgkedq
techqqwakdhvskpkkfriachlanlkydtnsgfd------ys--tdea
eravakdggneglttdnrgekaygeealigk--itaqvgtgtmlavagt-
-rgtkgtgrvkvv-----patkscikwldredkrrwsgvaevdtg--llr
glcgasrkahgl---wffnsgricvnqy-taa--tena----qne----q
ksgvwnssqnlkfsskafvllysecl-f-hdhfyllyhpegqyvnstpdy
rv---amlsg---iclqglfktntlqvagkmaygenplkqhvktllnrtr
vpdqrcgrfttqggeepvakptnpaeanespggelpiepteldfcc--kr
sdnepsmcmgsnayph-----------gkqqsld---ckivntqaadsrh
gpsspk-----vhtvicavnatafnkleafklr---ntpfallflk--al
edpdhshfeptgcesqggeen-yla
>node11
-vpsrmkrhltnfskkstdlkkiklklskktntqcaaqll-rltktifmt
dltas--qplgctdpriskw-giaiagaihrelwklkpgpeclvkgkedq
techqqwakdhvskpkksriachlanlkydtnsnfd------ys--tgea
eravakdggneglttdnrgekaygelaligk--ltgqvgtgtmlavsgt-
-rgtkatgrltvv-----patkgcikwldreakrrwsgvaevdtg--llr
glcgqsrkahgl---wffnsgricvnqy-taa--tena----qne----q
ksgvwnssqnlkfsskafvllysecl-f-hdhfyllyhpegqyinstpdy
rv----mlag---iclqglfktntlqvagkmayaenplkqhvktlqnrtr
vpdqrcgrhtt-ggeepvakpsdpaeanespggelpiepaeldfcc--kr
sdnepsmcmgsnayph-----------gndesld---ckivdtqpadsrh
gpsspk-----vhtvicavnatafnkleafklr---nspfgllflk--al
ndpddshfeptgcesqggeen-yla
>ENV_HV2G1/23-502
-vqsrmkrhltnfsrkatdlkkvtlklskktstqcadqll-rlvktifts
dltps--qplgctdpriskw-giaitsyihrelwelkpapeclvkdkedq
techqqwakdhmskpkknriacdlanlkyddnnnfd------yt--tgea
aravakdganeglktdnrghnaygelaltgk--lagqigtatmlavcgt-
-rgtratgrltvv-----pgtkgcikwldrgakrrpsgvaevstg--llr
glcgqsrsahgl---wffntgricvary-aaa--tena----qne----q
nsgvwnssqslkfsskafvllydecl-f-hndfyllyhaegqyisstpdy
rv----mlag---iclqglfktstlsvagkmgyrenplkqhlktlqnrts
lpdqhcgrhtt-ggeepvvkpsdpaeayedpegeapiepagldfcc--kr
fdtdesmcmgsnayph-----------gndedld---ckivdtqpadsrh
gptspk-----vltvicavnatafnsleafklr---nspfgllflk--al
nepddshfyfsgcqsqggeen-yla
>ENV_HV2BE/24-510
-vssrakkqlskfpkkktdlkkvkvklsgtssthcaatlf-rlsklvfva
dlaas--hglgctapriskw-giavagaifrelwklkpgpeclvkgqedp
terhqqwakdhvsrpkksriachladlkydtrdnfd------ys--tkea
ersvpkdggneglttnnrgdktygelaligk--fysmvetgpmlaisgk-
-ratkstgrlt-vpvgaapatkscimwldretkrrwsgcaevdvs--llq
glcgqsr----l---whfssghicvnhy-tat--tena----qge----h
kpgvwnsaqnlkynskafvllysdcl-f-qdqfhllyheegkyvdsapdy
rv----tiag---vclegvyktnslqtagkmaysedplkqhvktlqnrtr
vpdqrcgrhtt-ggphpvaapsepae--saqggelpvepaeldlcc--kr
sanepsmcmgssaypq-----------daddsld---ckivdtqpadsrh
gpss------------------sfnkleafklr---dnpfgllflk--al
ndiednhfeskacegqggeengylg
>node17
-vpsrmsrhlssfskkstdlkkiklklskttgtqcaaqll-tltktifmt
dltas--qplgctdpriskw-gtaitgaihrelwklkpgpeclvkgkedq
techqqwakdnvskpkkskiachlanlkydtnrnfd------ys--tgea
eravakdggneglttdnrgekaygelaligq--ltgeigtgtmlaasgt-
-rgtkatgrltvv-----patkgcimwldrsakrrwsgvaevdtg--llr
glcgqsskahgl---wffnsgricvnqy-taa--tena----qne----q
ksgvwnssqnlkfsskafvllysecl-f-hdhfyllyqpegqyinstpey
rv----tlag---iclqglfktntlqvagkmaytenplkqhvktlqnrtr
vpdqrcgrhtt-ggeepvakpsdpaeanespggdlpiepaelnlcc--kr
sdnepslcmgsnaysh-----------gndesld---ckivdsqpadsrh
apsspk-----vhtricavnatafnklqafklr---nspfgllflk--al
ndpddshfeptgcegqggeen-yla
>node18
-vpsrmkrhlsnfskkstdlkkiklklskttntqcaaqll-rltktifmt
dltas--qplgctdpriskw-giaiagaihrelwklkpgpeclvkgkedq
techqqwakdhvskpkksriachlanlkydtnsnfd------ys--tgea
eravakdggneglttdnrgekaygelaligk--ltgqvgtgtmlavsgt-
-rgtkatgrltvv-----patkgcimwldreakrrwsgvaevdtg--llr
glcgqsrkahgl---wffnsgricvnqy-taa--tena----qne----q
ksgvwnssqnlkfsskafvllysecl-f-hdhfyllyhpegqyinstpdy
rv----tlag---iclqglfktntlqvagkmayaenplkqhvktlqnrtr
vpdqrcgrhtt-ggeepvakpsdpaeanespggelpiepaeldlcc--kr
sdnepsmcmgsnayph-----------gndesld---ckivdtqpadsrh
gpsspk-----vhtricavnatafnkleafklr---nspfgllflk--al
ndpddshfeptgcegqggeen-yla
>node8
-vpyriklkernasgrltdlldi--kfsamakdacdaalftqqvahlyms
qtpet--lqlackdpeisew-glepstaivrelvklrsdpecvltkkqsm
tecdqtwekdkvsdpkafsveyaiaqllcdfssgle------cs--keas
ekvvegsagtlaqnksakadktagetdlnpk--ltepigsavdltisga-
-rkirangrgkta-----padkscvifvvaadksrw--------a--vlk
glsaagrhyqgf---ylfrsgficpkaysnaa--vedk----hty----q
ek-------dlsfssgtfvllyqavl-y-kehayllyfaeghyvdsspva
rv---tiktawiskaldglyktgelkpeymstygepplkqhhksildtnk
--slktgrptilgfggsvskpykaandkrngvgslslsplildfct--kk
ldyeagmcldgsayak-----------ikaqpln---ctsvkmdslhnrq
etsepkldylhvhnvncaitsppfnkfssfrip---ltalglgflh--gl
vdadqaefnsdgcdtecasda-yla
>node7
-vpfrvrlkdrnaegrftdqldi--kfsammkdtcdaatftgqvahlyvs
qtpdt--lqlackdpeisew-gleasvairkkllngrsdpecvltkkqsm
tecdqnwekdkvnapkafaseyaiaqalcdftdfle------cs--keas
ekpvqggagtlaehkggktdktaghtdlnpd--qtepvgsavdlaissa-
-kkikanargkta-----padkvcviyvvaadksrw--------a--vhq
gltaaakhylgf---flfrsqficpkaytqaa--vedk----nti----q
dk-------elssssstfvlmyqavl-y-rehaylllsaevhladstpva
rv---tikntwvskaldglyktgeltpkymgshgepplkqhhsvileanq
--siktgrpnvvgfgahvskpykaasdkrtgvgslslsllildfct--kk
ldyvagmcldgaaits-----------imahpln---ctdtkmdslqnrq
etseprldylhvhkvacaistppfdkfspfhip---lsklglgylhaegt
vgadqaefntdgcdtdcasda-ylt
>node14
-vpsrmkrhlsnfskkktdlkkiklklskttntqcaaqll-rltktvfmt
dltas--qplgctdpriskw-giaiagaihrelwklkpgpeclvkgqedq
techqqwakdhvskpkksriachlanlkydtnsnfd------ys--tgea
eravakdggneglttdnrgekaygelaligk--lygqvgtgpmlavsgt-
-rgtkatgrlt-vpvgaapatkacimwldreakrrwsgvaevdvg--llr
glcgqsr----l---wffnsgricvnqy-taa--tena----qne----q
ksgvwnssqnlkysskafvllysecl-f-hdhfhllyhpegkyinstpdy
rv----tlag---iclqglfksnslqvagkmayaenplkqhvktlqnrtr
vpdqrcgrhtt-ggeepvakpsdpaeanesrggelpiepaeldlcc--kr
sdnepsmcmgsnayph-----------gnddsld---ckivdtqpadsrh
gpsspk-----vhtricavtatafnkleafklr---dspfgllflk--al
ndpddnhfeptgcegqggeengyla
>ENV_SIVGB/47-569
-fsytiamshqksgqrvagglgg--qfhimtrkscnvapfaltanqryms
trrmkpqimltclsppihaw-vlktrlksarhivvidadaecafesghkl
k-nkdlyeglgvfepnagkfaystgelqs------heaahlgcasnkdae
knvsgghtgapklgkaindgdggkttaqtvhdifaegackdrtlaikpp-
----lgksk---------ergkkcqlfilaldpaqw--------gtslvg
gggnigghvqgflkmtafegpfecrpiygaladlatdkpdvlgayllvg-
------------fetggfvalsdpapgf-idkaylvvlapgsahahnvvl
hp---pvkpnfvlddvsgiydaaqlkpiekgdleappvqshvlpsvnsar
--llrtgphsdkgfgklaakankgatssisalggielasfldhfcafaky
vamtigmclkgggrfrlttgmlrwdcaikivgla---kgnvktgyvkspt
gqaqtnlayk-vkkmncnm--tgylkiqllkap---tvglgmqflr--kl
ievqatkfklngedgeahdaa-ylc
>ENV_SIVG1/22-522
-tpyrvrlkdrsaetrlttqidn--kfaammkgtcnaatftgqvahlyvs
qkpdt--lqlacknpivsew-glegslsirkkllsgrsdpecaltikegm
tqcesnwekekinapkafaqeyylaqamcdfanfle------ct--keas
eqtvqggagtlaehnggktddtcghvdlnpd--qtepvgsaldlaisra-
-kkikanarsktm-----psekvcviyvviadkarw--------a--vsq
gliaaakhylgf---flfrsqficpkqftqaa--vtdk-----ai----q
dk-------klgsntstlvllyqavl-h-rqhayllhcaelhladstpva
rv---tikktwmskaldglyktgqltpkyigshgepplkqhhstiaednq
--rimtgrpsgvgfgahiakpkkaatekrtsvgslslallildfct--kk
ldycaamclpvaaits-----------immhrmn---ctdtkmasmqnkq
gtsesrldelhvhslscaistppfdkfspfhip---lsriglgylhaegt
vgadqlelktnecdkdcatna-ylk
>ENV_HV2D1/24-501
-vprrmkrqlsdfskkktkakkiklkmskttntqcaaqll-rktktvfmt
dlvas--qplgctdprirkw-giavtgtthrelwklkpgpeclvkgqegq
techqqwaadhvskckkswiachlanlk-dtnanfd------yd--tgaa
kravvkdggkeglstdnrgdkaygelaligk--lygevgtgamlavtgt-
-rgtkatarlt-vpvgaapaskacimwlvreakqrwsgvaevdvg--llr
glcgqsr----l---wffnsgrtcvdqy-vdl--tads----qnq----q
kselwnsseklkkssrafvllysecl-f-hdhfhllyhpegkymnktpey
rv----llpg---iclqglfksnamavagkmataenplkqhlktlqsrtr
vpdqacgrhas-ggeedkak---ppeanqsrggqlpiepadlnlcc--nr
snaspsvcmgsnpsph-----------gnedsld---ckivstppadsrq
gssspk-----vhpricavtatafndleafklr---dspfsllflk--al
ddpddnhfepigcegqggdengyla
>ENV_SIVV1/24-538
-vpfrvrlketeaegkftgqldi--nlgatmkdt-qpaafigqelhtyvs
qttet--lqlvckdpeisew-gvqaavnirknllnankepdcaltkkqgm
secaqnwekskvndasafsstytiaqalcgftdfap------cs--kqra
etvvtggavllayhkggktdqaagqgdlnpe--qsapvgsgvrlaivsd-
-kkiranargknq-----aaekvcvlyiisgdevrw--------a--gqq
sltiarkh--gf---ylfreqffcvkayeqaa--vdek----gta----q
dk-------elsssaatfvlmgqhvf-y-kehdyvllagevhvadntdvp
rvpkstethtwvskdldglyktgeltpkymgsfeepplkqqhahiltalq
--siksgrpsvvgfasqvskpfkagtnkrtgvddlplmplvfdfca--kn
mdyvaglcligp-vsc-----------imahpls---cpdsmvnslekre
enaephldslhvhsvactidttlfskfapfqipdsgqkkialgylhpegt
vgdertafnthgcdtdcrsea-yla
>node9
-vpyrmkrhlrnaskkstdlkkiklklsrktndncaaqll-rlartlfms
dltes--lplscsdpriskw-gvsiagaihrellklkpdpeclvknkqdq
vechlkwakdhvskpkkfriachlsnltydtnsgfd------ys--tdes
erivakkggnegqttenrgekaygedtligk--itaqvgtgtmlaisgt-
-rgtkgtgrvkvv-----palkscikfldvedkrrwpgvaevdtg--llr
glcgasrkargl---wffnsgricvnqy-ata--tena----qse----q
krsvwntsqnlkfasqafvllysevl-f-hdhfyllyhpegqyvnstpay
rv---ailtg---icldglyktatlqvagkkaygenplkqhvktllnrtr
vpdqragrftkqggeepvakptnpaetnessggelpieptaldfcc--kr
idnepsmclgsnayph-----------gkqqald---ckivntqsldsrh
epsspk-----vhtvicavnatafnkleafkir---ntpfallflk--al
edpnhshfpptgcesqggeen-yla
>ENV_HV2NZ/24-502
evpsrmsrnlssfpkkstdltkirlklakgtgtecaaqll-titktifms
alsgk--vplgctd--ilkw-gkaitnaihseldklkpgpeclvkgkgdv
t-chqawandeannpnk--------dlkyntlrpfe------ys--saaa
qraiatdgennglttddrgenaygelaligq--aageigtgtmftasgtg
vrgtknpgrqtvv-----patkgcimwldraakrrwsgvaeidtg--rlr
glsg--skshgl---wffdsgricvdqy-tia--sdya----qnk-----
--gisnssqnfkfsskafvllfrdcp-fyhdhfyllyeaegqyvkatpey
rv----tlag---vslqglfktgtlqvagkmaytenplkqklktlqektr
vpdqrcgrhta-ggeepvakpsdpaeanaslggelpvqpatlnlcc--kr
kdnepsmcigs--ykh-----------gndesld---ckildsqpaesqh
apsspd-----ihtricavnaisfnnlqamklr---kspfgplflk--aw
nspdgshyeptgcagqdgnen-ylv
>ENV_SIVM1/24-528
-vpyrvkkhlrsasktstdlkkiklrldrktndscpaqll-pltrvlhms
dltes--lplacsdpriskwdgvsiagaihhellmlkpdpeclvknkqdq
vechhkwakdhlnkpkdfkiachlsklnyetnsgfe------yr--tdks
qrivakqggnqgqtaenrgemaygfdkligk--vtaeigtgsmlaistt-
-rgtkgtgrvkvv-----nslksrmkfqdeedkrrwpgvaevdtg--lwr
glcgasrksrgl---rffnsgricvnqf-atp--tena----eke----q
kksvwnasqslkfasqafvllygevl-y-hdhffllydpegqyvdespae
rv---ailna---icqeglyktaklqvagkkaygenplkkhvktllnktr
vpeqramriakqgnqepiakptgpvdtnesss--lpieptaldfcv--rr
cdnepsrcigsdayeh-----------gkdeald---crivntqsldsrh
eptspk-----vhtvickvnatafkklealkir---ntpfallflk--al
edpnvghfpptgcegqggeeg-ysa
>ENV_HV2D2/24-513
-vpyrmkhhlkefgkksddlrksklkpskktnagsagqll-slaktmfms
dlten--qplschspriskw-giakagaihrevpklrpgpeclvkgkedg
sechpqwpkdhiqkdkkfriacqltdlkfdtgpgsd------fs--tdek
dravvkeagivglttdnrgaqayeeqvligs--itlevgtgtmlavage-
-anakgsgrvqvv-----parrccikwldreerrrwsgvaeidtg--llr
nlcgatrsaqgv---wffnakkicvkqy-taa--tesa----ake----q
ktgiwnnsqnanleskafsllysecl-v-eehfyllyhangeyvnatrdy
pv---smfsg---iclqglf----lqdtgkkpygdnplqqevksqlnrtr
ipdqkcgkfktqagtepvakptkplepredpggslpiepteldfcc--ar
gdddqgmcmgsgaypn-----------dkqqsmdaskckivatqta--rh
gpnspk-----vhtvictvnatafnkltgyklr---dapfallflr--gl
qesdhshfeptgcenhggeeh-ila
