>ENV_HV2D1/24-501
anhtkhhllgrh--qfqnygf---rqgnr-akkpcfs--kpseawylvtp
-eandlaprdvcaaanglcl-arnlthgfpanhyltkvvylfgqdrfgdv
vde-ayt-angatrascqlntmmkgidvpfegtrgl-sycdldsqah-gh
qkiavlmcyl----drdsqkgsdrpfiwriylvf---yptsg--g--klv
rkeansa----fvvfsrakcgasffgqsclv-------gvvkdg------
--------lsrctcaaevseqmypaylksaepkcenehlnpfcdk---yi
akhgliivayataalanml-evthygeiaaivadsvnahidgclgighns
ngyqlypksplskpngekrsi------sfggr-gl--sr-sgtkadglkv
ssnsavq--f-anppnvpahdvltdlyskllfgkfegesgpyfnivaqva
tasftfknccy-yrkkdfvfsskkq----iyyktac--dssisg----ad
qkiepnflggi-slnlflfstptgalhescntlskslsadtcskgan-lg
akltvandnavngyps-tqndgevlhat
>node11
anhtahhllarh--rfekhgf---rqgnr-akkpcfa--kpspswypvtp
-eaddlspkdvcaasnalcl-arnlthgfptnhtltkvvymfghdkfgdl
vde-ayt-snganrascqlgtmmkgvevqfdgtrgl-sycdlssqdh-gh
qkiavlmcyl----dresrkgcdrpfiwritlvf---ypthg--g--dlv
rkeansa----fvvfshancgasfigapclv-------gvvkdg------
--------lsrctcssemsgqmyaaylksaepkcenehlepfcdk---yi
akhglvivaystaalanml-qvthyggvaaidadsvgatidgcfgighns
dgyelypkssltkangekrsikdtkyasfggr-kl--sr-sgnkadglpv
rrnskis--f-anppnvfaqevltdlyskllfgkfdgqtgpyynevaeva
tg---fknccyeyrrpdfvfiskkq----vyykvic--dsgisg----ad
qkiepnflgai-slnlflfststgalhessnsisssmsaatcskaan-lg
aklttindvaangfas-aqndgdvlhat
>node10
anhtahhwl--h--rfekrgf---rqgdr-gkkpcfa--kvssswypvtp
-eandlspnevcgasnalcl-srnltngfptnhtltkvvymfghdkfgel
vde-ayt-snganrascqlgtmmkgmevqfdgtrgl-sycdlssqdr-gh
qkiavlmcyl----dresrkscdrpfiwritlvf---yqthg--e--dlv
rkeansa----fvvfshancgasfigapclv-------gvvkig------
--------lsrcrcsseksgqmyaaylksaepkcenehlepfcdk---ym
akhdlvivaystaaldnml-qvthyqgvaainadsvgatidgcfgighns
dgyelypksgltkangekrsirdtkyeafggr-kl--sr-pgkkadalpv
rrnskis--f-snppnafeqevltdlystlvfgkfdgqtgpyyneiaeva
ng---fknscyeyhrpdfvfiskkq----vyykvic--dsgisg----ad
qkiepnslgei-slnlflfststgalhessnsisssmsaatcakaan-lg
aklttindvaahgfad-aendgdvlhat
>node18
anhtahhllarh--rfekhgf---rqgnr-akkpcfa--kpspswypvtp
-eaddlspkdvcaasnalcl-arnlthgfptnhiltkvvymfghdkfgdl
vde-ayt-snganrascqlntmmkgievpfdgtrgl-sycdlssqdh-gh
qkiavlmcyl----dresrkgcdrpfiwritlvf---ypthg--g--dlv
rkeansa----fvvfshsncgasfigapclv-------gvvkdg------
--------lsrctcssdmsgqmyaaylksaepkcenehlepfcdk---yi
akhglvivaystaalanml-qvthyggvaaidadsvgatidgcfgighns
dgyelypkssltkangekrsikdtkyasfggr-kl--sr-sgnkadglpv
rqnskis--f-anppnvfaqevltdlyskllfgkfdgqtgpyynevaeva
tg---fknccy-yrrpdfvfiskkq----vyykvic--dsgisg----ad
qkiepnflgai-slnlflfststgalhessnsisssmsaatcskaan-lg
aklttindvaangfas-aqndgdvlhat
>node14
anhtahhllarh--rfekhgf---rqgnr-akkpcfa--kpspswypvtp
-eaddlsprdvcaaanalcl-arnlthgfpanhiltkvvylfghdkfgdl
vde-ayt-snganrascqlntmmkgievpfdgtrgl-sycdlssqdh-gh
qkiavlmcyl----dresqkgcdrpfiwriylvf---ypthg--g--elv
rkeansa----fvvfshskcgasfigapclv-------gvvkdg------
--------lsrctcsadmsgqmyaaylksaepkcenehlepfcdk---yi
akhglvivaystaalanml-qvthygsvaaidadsvganidgcfgighns
dgyelypkssltkpngekrsikdtkyssfggr-kl--sr-sgtkadglpv
rqnsaiq--f-anppnvfaqevltdlyskllfgkfdgqtgpyynevaeva
tgrftfknccy-yrkkdfvfiskkq----vyykvic--dsgisg----ad
qkiepnflgai-slnlflfstatgalhessnsisksmsaatcskaan-lg
aklttindiaangyps-aqndgevlhat
>node9
anhtshhwl--h--rfekrgf---rqqdr-gnkpcft--knssswypvtp
-eakdlspnevcgtsnalcl-srnltngiptnhtltvvvymfgpdkfgel
vde-ayt-snganrascqlgtlmpgmdvqfdgtrgl-sycdlssqds-gh
qkiavlmcyl----nkesrkscdrpfiwritvvf---yqthg--e--dlv
rkdagsa----fvvfshencgasfigapcea-------gvvkig------
--------larcrcsseksgqkyaaylksaepkcenehlepfcdk---ym
akhdlvivaystaaldnml-qvthyqgvasisadsvgatidgcfaighns
dgyelypksgltqaagekrsirdtkyeafggr-kl--sr-pgkkadalpv
srnskis--f--kaqnafepevlaelysslvfgkfdgqtgsyyneiaeva
dg---fknccyeyhspdfvfisksq----vyykvic--dagisg----ae
qkidpnslgei-alnlflfststgalhassnsissnqnaatcakaan-lg
aklttihevaahgfad-aendgdvlhpt
>ENV_HV2BE/24-510
anheahhllarh--ryekhgf---rrgnt-akkpcfp--kpssswypvtp
-ekddlsprevcsaanslcl-nrdltngmsanhiltkvvylfghdkftel
vda-eyt-sdgshramcqlnttmkgievpfdgtrgl-aycdlsspnh-gh
qkiamlqcylnantnresqkgcdraflwriylvf---npphg--r--elv
rknansa----fmvfshnkcgssfigppclv-------gvvkdg------
--------lsretcslnmsaqlyaaylksaepkcenehlepfcdk---yl
gkhglvivaystaalanml-qvthygsvaeidadsvganieecfgtgqna
dkyqlypksvltkpkgekrsikdtkyssfggr-kl--sr-sgtkttglev
rqvsaqq--f-anpsdvflqegltelysqllfgkfdgqsgpyysnaakva
tghytykdccy-yrkkdfgfiskkq----iyyknvs--dagisg----ad
qkiepnflgai-svnlltfstptnalhescnsisksldavtcskaanglg
aklttinditangypp-lqqdgdvlhat
>node19
anhtahhllarh--rfekhgf---rqgnr-akkpcfa--kpspswypvtp
-eaddlspkdvcaasnalcl-arnlthgfptnhiltkvvymfghdkfgdl
vde-ayt-snganrascqlntmmkgievpfdgtrgl-sycdlssqdh-gh
qkiavlmcyl----dresrkgcdrpfiwritlvf---ypthg--g--dlv
rkeansa----fvvfshancgasfigapclv-------gvvkdg------
--------lsrctcssdmsgqmyaaylksaepkcenehlepfcdk---yi
akhglvivaystaalanml-qvthyggvaaidadsvgatidgcfgighns
dgyelypkssltkangekrsikdtkyasfggr-kl--sr-sgnkadglpv
rqnskis--f-anppnvfaqevltdlyskllfgkfdgqtgpyynevaeva
tg---fknccy-yrrpdfvfiskkq----vyykvic--dsgisg----ad
qkiepnflgai-slnlflfststgalhessnsisssmsaatcskaan-lg
aklttindvaangfas-aqndgdvlhat
>ENV_SIVGB/47-569
piankrswl--smcqqsrigifcevqssg-kgkskcseynqyagryavep
-vnscdgtqtpcqnkddtci-fnrllaqrsfdnqfvlvlh-ldqavvgsv
----fygrhgdtqth-capfefipgvvevfpp-lninifcfitcqqkkig
vvpwhasyyl----ggkagnyclkdlilscagviapgykgmg--giaglv
gieggka----istycnaycalafltpseevqkscdpgtklqvgfeiqap
kthlkvdvhkaepcflkkksptaaeyqklgkvkcalvffnetknrfvfyd
slkyapvsay----leyaatesqyecgekwikvapcsck--aefpvicvs
dafgvdgkgl----lialmnhsapkfdvvgdrfal--sl-skvagytrvp
lhqpied--a--kppqvfqgslqqqky-dlissdgkanhanytalvgaav
ve---fscycyeykeasyplvncnr----affhmgygldkrvgg----gt
tkfqrvkkand-nlnafvlesvlnqrkaekpgyhsqlpfagtdikel-la
vt-eqgidvrehdagglssfsadtmkpt
>ENV_HV2CA/25-512
vkhtahhllarh--ifdihtf---rqmsr-tkkpcfa--lpdpswypfip
-esddvspkdvcggcnalcl-akslthgfpinhiltkiiymfghdssgkl
vde-vtt-atgaarascqldtmlkgisvpf-stkgl-gycdlssqdh-gh
ekiavlmcyl----sredrkgcdrtfiwrvnlvf---hptcg--a--dli
rkegdss----fvlvshpdcgtdfigsrclv-------ginsng------
--------iarckcasdmsaqfyavylktadpkcedehleplceh---yi
tnfgllivaystaalanml-qvtryggvsaieadp--atidgsfgighnp
dgynlypksqltaangekrrikspkyasfggr-kl--sr-tdgkadglpv
rmnadis--l-anpanvfaqevlsplyekllfgrfhgenapyynevaeve
eg---fkncsy-yrrpdfafiskeq----vyykvic--angisg----sd
vklqplfagti-plnlftfstsagdlhessksvagsvstaacskdan-ln
aklttirdvaaggfas-aqddadvlhat
>ENV_HV2D2/24-513
akhtahhwl--p--qfqkcgf---rqsqk-gkkpcfa--kvssmwfpvta
-dendlspnevcgaynvlcl-aknlengfptndsimkviymygqdkfgel
iee-aft-dnganrasceigkmlkgkqiqfeg---l-sycnlagqdr-gc
qkhdvlmcyi----erkamknsdrafiwrttlvf---yethgane--ilv
rkdssam----faiishancgasfigaaclv-------atvkid------
--------ltrcrc--eepgemygaylkgaepkankehlepfcdk---ym
ikhdlivveyaaaaldtvl-tvnhyqgvaritansvnvsiegcsklgqav
dgyelypksaltkehkqvwssrddkyesyggr-kl--aq-agtkaddspv
rrdakia--fvkippdaieqevltllfrtlaygkfdgqtgelyneerhvk
sa---frhscyeyvrpefvflskkl----vffkevc--dsgvsg----vd
eknepnvlgsv-tldlfmfsanagqlhetnesisssvtalgcgkqad-ls
vklttvnevaaigfpe-tqnegkvthit
>node17
vnhtahhllarh--ifdkhgf---rqgnr-tkkpcfa--kpnpswypitp
-eaddlspkdvcagsnalcl-arnlthgfpinhiltkviymfghdkfgdl
vde-avt-sngadrascqlntmmkgievpfdstrgl-nycdlssqdh-gh
qkiavlmcyl----dresrkgcdrpfiwrinlvf---ypthg--a--dlv
rkeanss----fvvfshsncgasfigapclv-------gvvsdg------
--------larctcssdmsgqfyaaylksaepkcedehleplcer---yi
tkhglvivaystaalanml-qvthyggvaaidads--atidgcfgighnp
dgyelypkssltkangekrsikdtkyasfggr-kl--sr-tggkadglpv
rqnskis--f-anppnvfaqevltdlyekllfgkfdgqtgpyynevaeva
eg---fknccy-yrrpdfvfiskqq----vyykvic--dsgisg----ad
vkiqpnflgai-slnlflfststgslhessksiadsmsaatcskaan-lg
aklttindvaangfas-aqddgdvlhat
>ENV_SIVG1/22-522
dttlarvwl--hlkrkdkqgn---vqqdgigskpvgt--eqtl---gitt
ndtaeatpagnceasaavcltdrtltrslahehtlilvvh-ltsslgsgl
nhr-ayt-vvsadanschd-tmmtelgvllea-lai-pfchlsaesp-gg
dpmtvvlkyl----aakthkac------gipail---yyvmg--e--tvv
rldagqvrtlalviyshencgkvflnapgqg-------kaiaig------
--------vtrnhcakskktpmvggylksgekkcqltfleafcdk---yn
trsnfiygtfqagaldp--------hgaqryrappvgcavqghfdiacdk
dsyefighsvlpctqvargkpsedryemfgdk-ki--sscpagkaqalag
qrnaknd--v--tshtafqgdvqgqry-slisgdycsrtgatehkagimi
sg---yhcccysyhtsqfpyishnq----kyledrcdldagsvg----ia
fklepeaqata-thtlflfqgatgpihgnkqcfetsqgaatctaisk-ln
anltrsvqvtahefqd-geneplmlrna
>ENV_SIVV1/24-538
vetlarvwl--hlkrqnvkak---vgqngiggmavst--eealswlpvat
sdtaennpdqncevsatdclndrtlagnvgsgrklilvih-lapklgrel
msragyt-ivcvdehschdstmlndqavlfgp-ldi-pychindqgs-ag
esilvylkyl----epekhkgc------gapaiv---nytrg--e--tvv
rlgqadvrtvslaiyshedcgkvmlnapsqg-------pvikvg------
--------mkrghcaktkktptvggnlmpaerkcklsflehfcdk---yn
trnnfvlsvfeagamdp--------hpseivrlapvfcfveghfqvsctl
dsyemkgnsvapkdetkknkpkddqyemfgqr-ki--ak-pkgkdqaltg
qskangn--v--ssqeafigniqdqly-alvtadycdktgsyyhkagivl
ts---fdcnchtqhavqftyishshggtqkyyqdhcdldsrvdggtwela
rrletewqaan-tvsill---eiapirgkkacystsqgsikcieisk-fd
aelarsveissqtfay-kenepqvllqs
>ENV_HV2NZ/24-502
vkptahvlvarh--ifdkhgf---regnr-tktpcfa--kkapsryvltp
-aaddlspkdvctgsnalcl-aralthgfpithivtkiiylfahdqfgal
vae-avt-snganrascqlntmlkgievpydstrgl-dfcdlssqdh-gh
qkiavpmcyl----dresrkgcdrpfifrislvf---ystpg--a--dlv
rsaanss----fvvfshskcgasfigapcvv-------gyvsdg------
--------lsrctcssdmegrfsaaylkshepkcedehleplcer---yi
tkhglvivaystgalanml-qapvysgvaavdadc--atidgcfgtghnp
dgyelyekssltkangekmtikdtkyas---------sr-tggkadglav
hepskvt--f-gdppnvfpqhvlhevyetmlfgkfdgktgpyykevaevt
eg---fknccs-yrrpdyvfiskrn----vyykvic--dsglsg----ae
vkiqsnflgadesldlflfstctgsqhesakeiansmsaatcskaas-qg
tsftalndgaanggar-aqhdgdvlhng
>node8
pttltriwl--hlkrynkkgf---lqqdq-gskpvst--kesvswfpitt
-naseatpeascgtsatlcl-drtltpaigsdhdlvlvlh-lganhvsnl
vdr-ayt-vvtadrnscqdstmmpgkgvlfep-lai-pyctlsaqqs-gg
diltvllyyl----aaeahkacvrdliwripaim---yvgmg--d--nvi
rkdagev----laiythedcgsvflgapgeg-------svikvg------
--------lkrshcamgkktqkaagylksgepkcqltfleafcdk---ys
aragilvttyspvaldnml-qvtynhgaarvkaapvgcavdaqfavacdi
dsyemmgkavltrtqvakkkssenryemfger-kl--ts-psdkdqalpg
srdakdn--v--sshdafqgevlaepy-slvngdfsddtgayyhivgivi
dg---yhcccytyhtsqfpfvsnnq----vyyedrcdldsgvdg----ss
hklqpesqadn-thslflfqtavgplhgnkecfesaqgtatctavsk-lg
atlkrsveitahdfan-gdnepdmlrps
>ENV_SIVM1/24-528
hnhtshhwv--f--rfekrgf---rkqar-gnkpcft--knsaswypltp
-evtdqspnkvcgtthalcl-traltngiptnhaltvlvfmfgpekfgel
vde-ayt-gngansaycqlgtlmpgkdvefdgtqgl-sycdlpsqds-gh
etfavlvcyl------esrkscnrafiwritvvf---yqmhs--e--alv
rrdagga----fvlfthencgasfigspcet-------tivkiv------
--------larcrcssersaqkyaaylkaaepkcisehlepfcdk---ym
akhrlvivayssaalnnll-avthyqgvasiaadevgatsdgcfa---ks
egfemypksgltracgekrsfrdtrfdasger-rl--sk-sgkksnaspl
krnskipvkl--kaqeafepeilgelynslafgkfdgqtgsfynaiteva
de---mnnvcyeyhspdfifipksl----vyykvic--eagitg----ae
qkidpnclgei-shnlfifsaavgglhatknsinslkhgatcaktvn-lg
aklgsihevsahgfad-aaddgdvlhpt
>node7
pttlgrvwl--hlkrhdkkgk---vqqdgigstpvst--eetlswlpitt
ndtaeatpdenceasatvcltdrtltpslgsdhtlilvvh-lasslgsgl
kdr-ayt-vvtadsnschdstmmpdqgvlfep-lai-pychlsaqss-gg
drltvllkyl----aaethkac------gipail---yyamg--e--tvv
rkdagqvrtlalaiyshedcgkiflnapgqg-------kvikvg------
--------vkrshcakskktpmvggylksgekkcqltfleafcdk---yn
trsnfilstfeagaldp--------hgaervkaapvgcavdghfdvacdn
dsyemmghsvlprtqvaknkpsedryemfghr-ki--as-padkdqalpg
qrnaknn--i--sshdafqgdvqgqly-slvtgdycdktgayyhkagivi
tg---yhcccytyhtsqfpyishnq----kyyedrcdldagvdg----ia
rklepesqatn-thslflfqsatgpihgnkecfetsqgtatctaisk-in
atltrsvevtahdfqd-genepqmlrps
>ENV_HV2G1/23-502
anhtahhllakh--rydkhaf---qqgnr-akkpcfp--kpspswyevss
-eanglspenvcsesnllcl-arnlthgfpnnhtltavvymfghdkfgdl
vge-ays-sngakrascqlgimlkgvevhfdgtrgl-sycnlspgdh-gh
akiavliccl----drdsrkgcdrpflwrnalvf---ypthg--g--dlv
rkeansa----ivvyshpncgesylgatclv-------gvvkeg------
--------lsrctcsaemaghmyahylksqepkcenehlepfcdq---yi
akhglvivaystaalapml-qslhygslaainadsvgatiegcfgighns
dgyelygkssltkcngekraikevkyasfggr-klagsr-sgnkanglpv
rreekia--f-atppnvfaqdvlsdlhskllfdkfdgqtgpyynevaevs
tg---fknccyeyrspdfvfiskkk----ayykvic--kegisg----sd
qkitsnylgai-dlnlylfststgvlhessnsisssmaattcskaas-lg
aklttindvaangs------ngdvlsat
