>ENV_HV2D2/24-513
nqkqn--vmkhikyytn----psclrpvevgdfvvdwdawgsld------
-gegkgdgyhthy---hdpecnmadqvghlkaevcgvflfhkkaissay-
-assdgvny--calgrksivyagyvkpg----grl---------ckrihd
pakmkifvfgmtaragcfrhpcintgvimqvqlwiqsldgdychvfphvf
qhik-sealtiv-------idppavvt-----------gltayaln---k
ashesaeaarhpvpvvdcvhpch----kvthrypiei------alslksm
qaspanlefmyekrarcrierldktmst-qreethai----------llf
--edgfgpsfp-dqsr-ikglglvsgrgksgsakkmfth-----------
-qeieylwdsgchkrgtvqilpesvclnklmlnckaflrq----qfkvwv
agggcaagi-dfklgakdsknqvkmgfhkei---naklwrfqalitv---
----etqalgkln----fpw--vqgvaqksya-----sdvvvhfg---tl
e---tsk-gtrfwsvlkgcprvmeshaaseacrhktqtaenfvlmhveld
rvpnedtisrqgclseniwpve
>ENV_SIVG1/22-522
knqkq--vf-ldppytdqatskqt--avnvngfipgwe------------
-seqqvsafetvfcccrapkvak--aidhlsmgtcvafkyqkavkersy-
-hadqglry--aastkqslltliaiaepklvvghq---------cspwad
aknlpfvgfllttkkdsfdkpvintglnkqvnmlpevlktnyadvfkd--
-vci--aantvq-------kedpaqqa-----------gvehyadk---n
ntqatgddvdspnvnsqctfpcdppl----krgaatv------tl-vnta
gcdnihvellfkgsikcpygklnktlptklqtvllng----------lmy
vakeawsegfp-lqvk-gkegtlsndqgk--agvwmdah-----------
-qsvsarsgadnnrpgnvnieppgfclkmkvldcegslhe----qfnvvm
qphdcisgdvdtklcvkpkktkgrigyskgi---ykklwefl-likelea
prqtkkkgkgkssldfnypr--gsgiaaywyt-----cetivhfk---pi
k---gkk-atrfwaffgtcprnldaeedsltlkhl-ekheciavfymiva
rpvaesgfgqpaclpeggnsek
>node11
khqen--vmkldksyta----psclrpvelgdfvtdwdtwiald------
-gehhgggyqshy---ndpecgmadkvddlmsevcgvflyrkrvkssyy-
-haskgvay--savgrktiisaayvktg----grt---------ckrfrd
pakaafvgfpmtartdcfrnpcinsglimqveiwiqaldgdychifpnvp
qhck--ealtii-------idnpaatt-----------gvkeyaln---n
essssaentqhpvpvtdctypchpplkkvthryaiei------gislkvm
qsnaakmefmynmkakclferldkslnt-qraetnti----------lmf
--sdgfspgfp-eqrr-ikgrglgagrgksaianrmfth-----------
-qelaylwdskcnkpgtvqlapqsvclkklvlnckaalrq----qfkvrv
agggcangi-dyklglksvktegklgfhkei---npklwrfqalisv---
----esqvlgkld----fpw--vegvtqrwya-----gnvvvlfs---rl
e---tgk-strfwsvlnscpravdsvadaehirhktatsecfalahavlg
rvpgektfskhgclsdnawpvd
>node14
khqen--vmkvdksyta----psclrpvepgdfvtdwdtwials------
-gahhgggyqsqy---ndpecgmadkvdklmsetcgvflyrkrvnsryy-
-hnskgvsy--ssvgrktivsaayvktg----gri---------ckrfhd
padaafvgfpmtartdcfrnpcinsglimqveiwiqalngdvshifpsvp
qhck--ealtii-------idnpaatt-----------gvkeyaln---n
egssagentqhpvpvtdctypchpplkkvthryaiei------gislkvm
qsnaakmefmynmkdkcfferldkslnt-qreesnti----------lmf
--sdgfspafp-nqrr-ikgrglgggrgksaianrmft------------
-hqlaylwdskcqkpgtvqlapqsvclrklvldckaalrq----qfkvrv
agggcangi-dyklglksvktegklgfhkei---npklwrfqalvsv---
----esqvlgkld----fpw--iegvtqhwfa-----gkvvvlfg---rl
e---tgk-strfwsvlnscpravdsvgtaehirhktatsecfalahavlg
rvpdegkfsdhgcltdnawpvd
>ENV_HV2G1/23-502
khqtn--vmkleksyta----psclrpvelgdlvtdwdtwiald------
-geqrgggyqshy---ndpecgmadkvddlmnevcgvflyrkrirgsyy-
-haskgvsy--savgrktiigaayvkte----grt---------ckrfrd
paktafigfpmtartgcfrtpcinsglimqvqiwiqamegdychlfp---
-------------------------tv-----------gmktfgld---n
essssaenirhpvplthctypcqpplkkvthkyaiai------ginlkvm
qsnaakmefmydmkakclferldkslnt-qrqetsti----------lmf
--rdgfstgfp-eqrh-iqsrglgagrgksaianrsfth-----------
-qelaylwdskcnkpgtvqllpqgvclkklvlnckaalrq----qfkvrv
agggcvggi-dyklslksvsqegklgfhkem---npklwrfqtlvsl---
----enqvlgkld----fpw--pegitqrwya-----grvvvlls---rl
e---tgk-strfwsvlnscpssvdsvadvahirhkaansacfalahavlg
hvpgerafskhgclsgnawpld
>node9
knqen--vakldknyta----psclrpvelgdfvadwdtwpald------
-gehhgggyqthf---ndpacgmadkvdhlmsevcvvflyrkrvknryy-
-hsskgvaf--satgkktlmsagyvktg----grt---------ckrfrd
panmsfvgfpmttrtdcfrnpcinaglimqveiwhqaldgdychifpnap
qhck--ealtii-------idspaakt-----------gvteyslk---k
eshtsaentqhpvpvtdcthpchpplkkvthryaiei------glslkvm
qsnpakmefmynkkakclfgrldkslst-qraetnti----------lmy
--qdgfspgfp-dqsr-ikgrflgagrgkssiadrmfth-----------
-qdvaytwdakcnkpgtvqlapqsvclkklvlnckaalrq----qfkvlv
pgggcasgs-dyklgvksiktegklgynkei---naklwrflalisa---
----etqvlgkld----fpw--vegvaqrwyt-----cnvvvhfg---rl
d---tgk-strfwsvfnscpravdsvtddeairhtkatsqcfafahcvlg
rvpgedtfskhgclsenawpvh
>ENV_SIVV1/24-538
kkada--lf-leppytaqqtgdhtlnsvsiaafvaewe------------
----liggsdtvfccgkskmvpt--nndhlpvgvctafkypgglkdrcy-
-hggaglky--aadtfksllakfditeeklvvghq---------ckkfvd
akelpfvglqlntindsfgkavvntgitkhvatlpqtlsvnypsvftk--
-vtv--sadtvykpvdqsgkedaaart-----------gvtscvdk---h
dtqasndevenpikdskchypcdpplkksgsrkatkvtgvntrtl-lkia
gcdkihvellfkaktkhaygklkkglpadtdtvvlna----------lmy
vasqafadaypgaqinandkgtinddpgkgnlgiwmdph-----------
-spvgskcgpendkpgnvhidapniclkmdvldckvkyhe----qltvvl
aphtcvagg-dtklcvkpsntngp---nkgi---wrklwrfl-likdlda
srqtehepkgkvqlkitfpr--avgrsaywys-----cdvighkk---pl
k---akk-asrkwayfskcprnlevdedsitlkhg-akqdcnavfyliva
raapasgfgkpaclpdagwadk
>node19
khqen--vmkldksyta----psclrpvelgdfvtdwdtwiald------
-gehhgggyqsqy---ndpecgmadkvddlmsetcgvflyrkrvkssyy-
-haskgvsy--savgrktiisaayvktg----grt---------ckrfhd
pakaafvgfpmtartdcfrnpcinsglimqveiwiqalngdychifpsvp
qhck--ealtii-------idnpaatt-----------gvkeyaln---n
essssaentqhpvpvtdctypchpplkkvthryaiei------gislkvm
qsnaakmefmynmkdkcfferldkslnt-qraetnti----------lmf
--sdgfspgfp-eqrr-ikgrglgagrgksaianrmfth-----------
-qelaylwdskcnkpgtvqlapqsvclrklvlnckaalrq----qfkvrv
agggcangi-dyklglksvktegklgfhkei---npklwrfqalisv---
----esqvlgkld----fpw--vegvtqrwya-----gnvvvlfs---rl
e---tgk-strfwsvlnscpravdsvataehirhktatsecfalahavlg
rvpgegtfskhgcltdnawpvd
>node17
khqen--vmkveksyta----pnclrpvelgdfvtdwdtwiald------
-gehhgegyqsqy---ndpecsmadkvdklmsetcavflyrksvkssyy-
-hnakgvsysksavgqktiisaayvktg----grt---------ckrfhd
pakaafvgfpmtartdsfrnpcinsglimqveiwiqplngdyshifpsvr
qhck--aaltii-------idnpaatt-----------avkeyaln---n
essssaentqhavpvtdctypchpplkktthryaiei------gislkvm
qshaakmefmynmkdkcfferldkslnt-qkaesnti----------vmf
--sdgfspgfp-dqrr-ikgrdlgagrgksaivnrmfsh-----------
-qelaylwdskcnkpgtvqlapqsvclrklvlsckaalrq----qfkvqv
agggsangi-dyklglksvkaegklgfhkei---npklwrfqalisv---
----esqvlgkld----fpw--vegvtqrwya-----gnvvvlfs---rl
e---tgk-strfwsvlnscpravdsiataehirhktassecfalahavlg
rvpgegtfgkhgcltdnawpvd
>ENV_SIVM1/24-528
knqen--iakldrnwta----pgclrpvekgdfvaewstlpald------
-gdhhgggyqsnf---ndpscgmadevdhlisevcvvylyrkrvraryy-
-hskkgvaf--saagkktlmsggyvktg----grt---------ckkfrn
paeksfvgfpmttradcfrnpcvkaglimqveiwhqaldgdychifpdap
qhck--ealt------------paakt-----------gvteyslk---k
eshtsaedtqhpvpvtncfnpchpplk-vahkkgiei------glsltmm
esnpakmefmyskrakclsgrlakslgt-qqaeknti----------llh
--tdgftsgfp-dqsr-imgrflgggrgsasfadrmfth-----------
-qdvsytwnakcdkpgtvq---------kvmlnchaalrqrvfaqfavll
pgggcasgr-dfklgiknikqegeagynkei---nskiwkfldlisa---
----ksqvlgkfd----fpw--aegvaqrwyt-----cnvvvhfg---rl
d---ggk-ntrywsvfnscpravdsvtdhevirhfkgagqcfafahcvva
rvpgedcfskhgclseaawpvh
>ENV_HV2NZ/24-502
khqgd--vmkversytp----pnclrpvelgafvadwecwiald------
-gsahgegyqsqy---ddpecamadkvdklmsstcavflarkgvksnfy-
-hnackvsysktavghkniiaaayikgg----grt---------ckrfhd
gataafvgfpmtarsaafrnpciksgllrqvekwiqvlngdythvfpsvr
qhcn--aaltii-------idnpaatt-----------evkgyald---n
essasgentdhavpvtectypchapskktthryaiei------gialkll
qshaakiefmynvkdkcflehltkslka-dkaetsai----------avf
--sdgfspgfp-dqrr-lkgpdlgagrgrpavvnrmfgh-----------
-lelaylwdskcnkpgtvqlapsfvcvvklvlsckaaliq----hfkiqv
agggsangd-dyklslksvqaegklnfhkef---spkvwrfqalitv---
----esevlgkld----fpw--lagvtqrwyt-----gdvvvlfg---rl
e---tg--strfwsllnasvravdsiataehirhktaqsecfalahgvlk
rvpgegiygkhgcltdngwpvh
>ENV_SIVGB/47-569
kcges--af-y--arvegtsmhlatltdgvinpisgwg------kehspl
ydiwlavpddsveccadlpslga--qvekllsavcvprmlhkhvrevykl
mhhg---vy--wgaflgylltvysrvac----pkdksglgsihecdrfad
-regsffikdliagtpeymksipegaapg---iwaadtsggyranfat--
-ival-aggyiv-------aesqalthfkhldlpaaglvvwhfetsapkr
cmrlaadgterakppgacshpcnshdgkagefynnqq------aaarvlt
tcdaglnelmvkdvmnlqfgkiqetvgv-dtgpklei----------ivv
etd-pfvpvkc-rnle-nqawllntgaklgsqatmaaakvgqcdgeaast
vgt---lrppehgqvgrvg----------kilksknevii----tittlm
pkvgcpqtv-aaklctqflddngmissnkgphsgeihyedfl-tiek---
----dvcag---e----fhw--seignlswfggelicclcychwkisdch
akpqtkkadqrrwpgfrdqykslsataagqckkhe-galmclvctnnyag
riccdqpitrlncl-gmgrkih
>ENV_HV2BE/24-510
khqenksvlkgdkgynv----psclrpvepgnfvtdwndwatls------
-eahhgggyqsty---ndpecglvdkvdklmsetcgvflyrksvnsryy-
-hnskgvry--ksvgrktmvstayvktg----grs---------ckrfhe
pgdaafvgfpmsaqsncfrnpcagpslimqveiwiqaldgsvssifpsvp
ahck--ealili-------innpaatt-----------gtkeyaln---n
egaaagentqqpvpvtdgtypchppkkkvthryayei------fislklm
qstaakmhfmknmkgkcfferldkslna-qraesnaivhslvlfikplpf
--sdgfspafp-nqrn-ikgrglgggrgksavankmft------------
-hkleykwnskcqkggtvqlapqavcmrklvldckaalrh----qfkvrv
pggstangi-dyklglksantdskldfqkei---npklwrhqalvhv---
----esqvl--ld----fpw--igtltqhwfa-----gkvvvlfg---rl
e---tgk-strfwsvlnacpravdsvgtaehikhktaashcfalahavld
rvpddgkfvdhgcltdntwpvn
>node18
khqen--vmkvdksyta----psclrpvelgdfvtdwdtwiald------
-gehhgggyqsqy---ndpecgmadkvdklmsetcgvflyrkrvkssyy-
-hnskgvsy--savgrktiisaayvktg----grt---------ckrfhd
pakaafvgfpmtartdcfrnpcinsglimqveiwiqalngdyshifpsvp
qhck--ealtii-------idnpaatt-----------gvkeyaln---n
essssaentqhpvpvtdctypchpplkkvthryaiei------gislkvm
qsnaakmefmynmkdkcfferldkslnt-qraesnti----------lmf
--sdgfspgfp-dqrr-ikgrglgagrgksaianrmfth-----------
-qelaylwdskcnkpgtvqlapqsvclrklvlnckaalrq----qfkvrv
agggcangi-dyklglksvktegklgfhkei---npklwrfqalisv---
----esqvlgkld----fpw--vegvtqrwya-----gnvvvlfs---rl
e---tgk-strfwsvlnscpravdsvataehirhktatsecfalahavlg
rvpgegtfskhgcltdnawpvd
>ENV_HV2D1/24-501
khqen--vmkvdksyta----ppclrpvgagdfvtdwdtwials------
-gahhgggyqspy---ndpacgmydsvsklmtetcgvylyekrvnsryy-
-hnskgvsy--ssvgrktlvsaayvktg----ggl---------ckrfhd
padagfvgfpltartncfrnpcinsglvmqvqiwiqalngdvshifpcvp
qhck--daltii-------sdnpaatt-----------gvteyaln---n
dgssqgentqhlvpvtactypchpplakvnhsysiei------gislkvm
qsnsakmeflynmkdksfferldkslnt-vrsesnti----------lmf
--sdgfsaayp-nqrr-ikvrglgggrgksaianreft------------
-tqlsylgdskcqnpgtvqlapqtvclrklgldckaalrq----hfkvev
agsgcgkgi-dyklglksvknegklgfskei---npklwrflalvsi---
----ehqhlgkfd----fpw--tegytqhwfa-----gevvvlfg---rl
e---tgk-strfwsvlnscpravdpvgtaehirhrtatpecfalghavlg
rvpvegkftdhgcltenaspve
>ENV_HV2CA/25-512
ktqnn--vmkvehsyta----ssclrpielgdfvtdwdtwiald------
-gerhgegfasqy---nesecsiaekvdklmsetcsvflyrkgvssnyy-
-hnakgvsysksavgqdtiisaayvktg----gra---------ckrfkd
pakakfvgfpmtfradsfrnpcinsglimqadiwiqphngdysnifpnvr
lhck--asltii-------vdnpaata-----------avkeysln---n
esstaaegtqhevpvtdcthacqppiektthryaiqv------sislkvm
qsqaakmtftydmkdkcffqrydkslns-qksessti----------vlf
--sdgfapgyp-dqrr-ikgrdlgagrersaivdrmfsp-----------
-selasawdakcekpgtvqlaaqsvclrklvlkckvalrq----qfkvql
agggganqv-dyklglklvkvegklgfhkdi---npklwrfqaiisv---
----essvfvkld----fpwlcvegvtrrwya-----gdvvvlfs---rl
e---tgk-sarfwpvlnscpramdniataehlphktagsdcfglahnvls
avpgdstyakhgcltddlwpvd
>node10
khqen--vmkldknyta----psclrpvelgdfvadwdtwaald------
-gehhgggyqshy---ndpecgmadkvdhlmsevcgvflyrkrvkssyy-
-hsskgvay--savgkktiisagyvktg----grt---------ckrfrd
pakmsfvgfpmtartdcfrnpcintglimqveiwiqaldgdychifpnvp
qhck--ealtii-------idspaatt-----------gvteyaln---k
eshssaentqhpvpvtdcthpchpplkkvthryaiei------glslkvm
qsnpakmefmynkkakclferldkslst-qraetnti----------lmf
--qdgfspgfp-dqsr-ikgrglgagrgksgiakrmfth-----------
-qeiaylwdskcnkpgtvqlapqsvclkklvlnckaalrq----qfkvrv
agggcasgi-dyklgvksvktegklgfhkei---naklwrfqalisv---
----etqvlgkld----fpw--vegvtqrwyt-----cnvvvhfg---rl
e---tgk-strfwsvlnscpravdsvadseairhktatsecfalahavlg
rvpgedtfskhgclsenawpvd
>node8
knqde--vf-ldqsytqgatakqvllavnvnafiagwd------------
-gehlegaydtvfcccrapkval--kvdhlmmgvcvaflyrkavkdryy-
-hsgqglky--aastnenlltafdvkep----ghe---------ckrfvd
akemqfvgfelttstdpftkpvintglnkqvemwpetlkggyckifte--
-tci--aentvl-------gedpsara-----------gvpqyskk---n
nahatgdsvdrpdrvsqcsypcdpplqkvapryaakv------alavnma
scaaahvelmfkgkvkcqygklnkslav-aqaillng----------lmy
iakegfspgfp-nevr-gkagtlnkgegkgnvgirmsph-----------
-qsvaarsdadnnkpgnvhleppsiclkmkvldckaalhe----qfgilm
pqpgcvsgd-evklcvkplktegrlgynkgi---ysklwefl-lika---
----eqkplgkls----fpw--gagiaqkwyt-----cnvivhfk---pl
k---gkk-atrfwaffsscprevdaaeddltlkhe-aiqeclaifyvvva
rvasesafgkpaclpdaawsvh
>node7
knqde--lf-ldppytdqatskqtllavnvnafiagwe------------
-gehlvgafdtvfcccrapkvpt--kidhlamgtcvafkyrkavkdrsy-
-hagqglry--aastnqnlltlfeitepklvvghq---------ckrfid
akelqfvgfqlttnndsfdkpvvntglnkqvnmlpevlktnypnvfte--
-vci--aantvl-------kedpaara-----------gvphysdk---n
ntqatgdevdspdrdsqcsypcdpplqkvakrnaakv------tl-vnma
gcdkihvellfkgkikcpygklnkalpaktqtvllng----------lmy
vakeafsegfp-aqvk-gkagtlnnnegkgnvgiwmdph-----------
-qsvaarsgadnnkpgnvhieppniclkmkvldckaslhe----qftivm
aphncitgd-dtklcvkpkktngrlgynkgi---yrklwefl-likelda
preteqkpkgklsldftypr--gagiapywyt-----cnvivhfk---pl
k---gkk-atrfwaffgtcprdvdadedsltlkhe-akheciavfyviva
rpasesgfgkpaclpdagwsek
