>ENV_HV2D2/24-513
wisa-ttedtakqelplgpps---pyttracnawllacgfagsc----gl
vck----cvhhdhvmdlc-------sp-kkirtqnhvlh--elmlsptvn
wtks--ciflptgsvrhqklltaa---anhdppydqiq-ygdaswrihq-
gdly------mieykpvvhegtlllflqnasdp-----tqccnkvpgws-
-qeghatlglyp---lhfkrga------ggkf------agsvhslffrsd
tpvaevedyggmkhgi-----tkglehtavnsslwranvsrsrhs----k
fyqataeffagcglsllttwcti----haytq--vt-vtvrdcldikdgl
ksrv----------tvqedhkgsavrltilgsgseksktikaygvtslve
eicapypdekpgynlketkagn--tgpesavndalsahdntdagvgvgvr
gklltwnnepgtfghlehcqsheggkegesatiafda-----cihsnmlp
spisfaayasggl-nlkyrrnrgrgld-shpkgpgw-fqgtrladgryf-
---ghtrv--ikwkc----pkdapdltivq--kgavqgg--gkdkiateg
li--n
>ENV_HV2G1/23-502
wvav-tpenaakqelvvgppqpkpsystrecngslkecgfancc----df
vcn----cthhtnsmrlc-------sr-gririqqhilh--qligaptvd
rsts--cefistqkirqqhllvaagyctnhdpcydqvq-anvagwrisq-
gqly------ridykptkeegtlalfitdasgp-----pqccpfvpgrs-
-divhatlgmya---lyfktgp------ggkf------afavdtaffknd
afvkkieeysgknvgi-----akgteqtavpsslwrsnvslsrqa----k
fyqgtldffqgcglslltkwctlelvnhnyfq--vt-vtvrdcldikegl
kgrv----------vcqethkemcmratilgsnnekaktvkpygvnalie
emcahypnelagyn----kaav--sspetavgkavfahdnsvcgvgigvr
gklltwydepvtygdleecnghpkgkemdtttvaldt-----cfhttllp
spnkas-yalggldnmkyrrnkvrglk-sppfgpgwlgqtarlaekryf-
---ansrvnlikwks----tkttedlnlgd--kgavegg--gkdniatea
li--k
>ENV_HV2BE/24-510
wfac-tsedsakqelvaghpq---systreccgslkecafancc----gf
vti----cthhtgrmilc-------sr-skirteghilh--qligkralr
rptd--ceflatnavrqqqlliaa---tnhdpcydpvq-tsvagwrisq-
gqly------mtefkpirnegdlilyiikalgp-----pqccpfvpgwn-
-diyhatlkmyp---lhfkpga------g-----------saqtnffkkd
alvkqiehyagksnai-----ekgseqtlvscslwrwnvsqakqs----p
fyegtldfyvgcgltlltkwctlelvhhnyfq--vs-vtlracfdikegl
karv----------vcqedhknmpvrasilgsasekaktirpyginnlie
qicehypdekpgyk----ktadlpssvesavgkalfshensvagvglgvt
gklvtwysepvaygkleqcqgnpngkemdsitvalds-----cfnnkllp
npnhasayslgglddmkyrrnkgrgek-tkpfgprwlaelaraaekryf-
---qhsrvavikwkc----trtaddlnvae--kgavesg--gkdniatea
li--n
>node11
wiav-tsedsakqelvvgppq---systrecngslkecgfancc----gf
vsn----cthhtgsmrlc-------sr-akirtqehilh--qligsptvn
rsts--ceflstqsvrqqhllvaa---tnhdpcydqvq-agvagwrisq-
gqly------midykpvrnegtlilyiinasgp-----pqccpfvpgws-
-divhatlgmyp---lhfkpga------ggkf------afsvqtaffkkd
afvkeieeysgknhgi-----akgteqtavssslwrsnvsqsrqs----m
fyqgtldffqgcglslltkwctlelvnhnyfq--vt-vtvrdcldikegl
karv----------vcqedhkemavratilgsasekaktvkpygvnglie
eicahypdekpgyn----kaad--sspesavgkalfahdnsvagvgigvr
gklltwysepvaygdleecqghpngkemdsvtvalda-----cfhakllp
spnnasayslggldnmkyrrnkvrglk-tspfgpgwlgqlarlaegryf-
---ehsrvnlikwkc----tktaddlnlge--kgavegg--gkdniatea
li--n
>ENV_HV2NZ/24-502
wvav-tgedsdhqelvavppq---systrecqgslkecgfancc----gf
van----sahhtgamrlc-------ak-arlhtqehllh--qligsptan
ksts--cdflstqsvrqqhlfvav---knytpcydqvq-asvagwrlse-
gqly-------vdykpiknegtlilyfidalgp-----pgccpfvpgwa-
-eivhgklamyp---lhfkpga------ggmf------ayseqtsffkkd
ksvkniedysgknngl-----akgtehtpasssfwrsnvshpres----m
fyqgtlnffqgcslslltkwcslqlvkhaffq--ts-avvvnclnikegl
kvrv----------vceqehkemaaratilgneaekaktvtpsgvnllie
eicrhyhdekpnfn----ktad--pppeaavgkalfahsndlagvdinvk
gklltwysepiaygdleqcqghpkgkqmdsvsaelea-----cfhakvlp
spnnasyyslggldsmkirrnsvrglk-tssfgpgwlaqlakltegryf-
---ehsrvnlikwec----tktaddlglgl--kaalegg--gkdnvltea
li--n
>node10
wiav-tsedsakqelvvgpps---syttracngslkecgfancc----gl
vsn----cthhtgamrlc-------sr-akirteehilh--qliasptvn
wsts--ceflptqsvrhqqllaaa---tnhdpcydqiq-ageagwrirq-
gely------midfkpvrhegtlilyiinasgp-----pqccpfvpgws-
-devhatlgmyp---lhfkpga------ggkf------afsvqtgffkkd
afvaeieeysgmkhgi-----tkgteqtavssslwrsnvsqsrqs----m
fyqgtadffqgcglslltkwctlelvnhnyiq--vt-vtvrdcldikegl
karv----------vvqedhkemavratilgsasekaktvksygvsglie
eicahypdekpgyn----kagd--tspesavgkalfahdnsgagvgvgvr
gklltwysepvaygdleecqghpngkeadsvtvafda-----cfhpkllp
spnnasayslggldnlkfrrnkgrglk-tspigpgwlgqgarlaegryf-
---nhsrvnlikwkc----tktaddlnlvq--kgavegg--gkdniatea
li--n
>node8
wvpa-vgedmakadlvsgppv---aytsrsckgplkdcglfnca----kv
vsn----ctlhtpdeklc-------sn-ekvknqdhilhmwqlnvsgtvk
wnta--cpflfdqkvrredlmpae---rdhdpcynqpq-acdsqwwerr-
vqlyiqnfehlagfkearhngsrmkyisdqlka-----patcmyhahwe-
-tavnakfsmyg---yqfkads------gakf------altvelglfkkg
tfvialathtgmgegl-----tnghhq-gmetplwrdtvanerhp----l
ryrgaspgyqgcclhllspwsilslthnncnethir-yhvrecldkresi
kakv----------ivheshatgsvrstmakni--kpkttvsadhpglvk
qiqagyck-tpgyn----kftd--vrpetavskdtfahedagagvgegvr
aalftwyneqvfygkvdecdnnsnstlstgatflleaypevtcfepgmah
k-gggasnslagkhiltfkegkgkgvr-nsaiqpgwlaqkmiladsr-vs
vqndhtrvrptdfkcpvlevktttdsnlvd--ksavkgg--gkdnlmrea
lv--n
>ENV_SIVM1/24-528
wipv-snentakqelvvgpps---ayttreckgrlkeceigscc----sl
vsk----cthktgamrlc-------nh-akirsekhilh--qliasalvh
watk--cellpvesvpyeqliaqd---tdhdpcydq-----aagwsirq-
vely------midfipirhegalilyiidagga-----sqccpflpgwp-
-gevhaslgvyv---yhfkpav------gtkf------afsvetglfkkd
afvaekseyssmkhti-----lkgakqscvssslwrpgvsnarnp----m
wyqgtadgfqgchlnlltdwcalhlthhnciq--vt-ltvrqcldikegl
kprv----------vhaddhntlavratalgsaieknkqvksygvsglvn
dicthypdeapgfk----ksgd--tssessagkglyahddsgasvgegnr
grlltwyrepvnysdleecqghnngtetdpvsavfds-----cfhpkllp
spntgsayslgawdg----rnkgrgtk-tspigpawlgrgaklaegryfa
aqnnndhvdligwkc----tktsaelnlie--kgavkag--gkeniasep
li--n
>node19
wiav-tsedsakqelvvgppq---systrecngslkecgfancc----gf
vsn----cthhtgsmrlc-------sr-akirtqehilh--qligsptvn
rsts--ceflstqsvrqqhllvaa---tnhdpcydqvq-agvagwrisq-
gqly------midykpvrnegtlilyiinalgp-----pqccpfvpgws-
-divhatlgmyp---lhfkpga------ggkf------afsaqtaffkkd
afvkeieeysgknhgi-----akgteqtavssslwrsnvsqsrqs----m
fyqgtldffqgcglslltkwctlelvnhnyfq--vt-vtvrdcldikegl
karv----------vcqedhkemavratilgsasekaktvkpygvnglie
eicahypdekpgyn----kaad--sspesavgkalfahtnsvagvgigvk
gklltwysepvaygdleecqghpngkemdsvtvalda-----cfhakllp
spnnasayslggldnmkyrrnkvrglk-tspfgpgwlaqlarlaegryf-
---ehsrvnlikwkc----tktaddlnlge--kgavegg--gkdniatea
li--n
>ENV_SIVV1/24-538
waia-vaedlqkaipvmgapg---aysknsckgplkecglfkck----kl
lsn----clghqpteklc-------ha-ssvsgqdhllqmwelevrgtvq
wnap--cvllfdqrvkredlmnae---rh--pcyseef-tcdgqwwevk-
ikgylqdfvhkpaakgarlqgprmkcvsdsvka-----paacmyvthwe-
-tvinpkvskysdmwfklvpds------gaki------attvqlavfkdg
afflsfkkkkgmasplfeagftdghhq-geendlrrgaldsehhp----l
qyratspqyqrcalmllkpwsilelvhnecththyr-ynvrqclnrgttv
kvki----------raedghptglarsgmakrq--kfkthktgeaaslvn
qvdgsycc-lpgys----qfsd--irpdtpvsrdtferdkagvpatqgsr
agdykwynqhvfyggggdcsavsgkglstgattflecysaihcdepgmat
k-gagataslagkralsfkekkgkglk-tspieramlaqklvlpnhk-iv
idaekakvaptdfdcpvlearttanvntvg--kpatdsg--akdslirep
lk--d
>ENV_SIVG1/22-522
wvva-vgedmnkamlvsgppg---gytkhqcrgslkdcglfncs----kv
ksn----cavhtpdqklc-------sn-etvadqdhilqmwqlevngsvq
wnta--cpflfdqqvkrhdlkhne---rhndpcydqaf-tcddqwwkkr-
iklyiqdfehvagfkearldgpkqkcisdvvka-----paacmyvatwe-
-tvinlkltlyg---yifktdk------aaky------alavdlglfkkg
nfyitlkretglaeglfdlnftndhhe-esesplwrdkvanerhp----l
rykgaspnyegcclmllspwsilhflhikctdtqmr-ykarqcldrgesk
kvki----------rlheahdsklvrsgmaknl--kpkttitarhpslvk
qvqgqyck-tpgcs----dftn--irpearvsrdtfasedvgvavgqglr
aadytwynqqtfydkgadccngpdktlntgstfllesyiaiscfepgmah
k-gagastslagkhaltikegkgkairvncpiepvwlaqkmflpnsr-va
vegdhakvkpsdfkcpvleattttdsdlsq--kpaakag--gsdnlerep
lv--d
>ENV_SIVGB/47-569
wiiaiddfmmdrrqlkctakm---s---sspmpalakkeayagqhlltne
yemytklaslhdnqatycdlikdnsvskeakkgqalltpiwrfgnagalk
kknpigckfkyedktkhailvahd---kkahqckhdphkvcethwwdkak
qqgnwtcfeqlefykgkk-----lkyiiklaqacaakfdtvcfyevqwak
fytiglrfnvfg---fvylkqnsglwivlpkmiagsrta---dvglykwg
gfilg-eipncadetm-----fvcsqk-dmdspgerqvvtsdahgnyklm
kfhsdgppktgcclqll------tlqkricvsfhlnkyetct-kkkrrty
ykeaetvyaaaelnls--hgvthagqrgq--il--giktlvvtkrpgvdr
etkpglcs-sigcs----rfsd--l--ekiapmhyiieeksd------mt
igmyiwfsveifagmmmectvcipgklvagasftlfdltefrpfaatgnn
p-psrtqnklmvdlellfttktgnnvk-shtm--mycsqkfvknesg-ve
vgtrrlrlivrelraptpapsmgedgylvasaggnvktaveqksslrref
ltste
>ENV_HV2CA/25-512
wiav-tgedsarqelmvappq---sfstrecngslkecgfgncc----gf
agn----tvvhngsmrmc-------sk-akiwtqdhily--qltgsptvy
rsns--ceflskqtvrqrhlllav---nnydpcydevq-asvagwriaq-
gqly------midfkpirdeptliiyiinnlgp-----kqccplvpgwp-
-diihgllgmfp---lhfkpgn------ggks------afseqaaffkkd
tfvkelgqytgmdngl-----akgteqdaistslwrdndsqprqg----m
fyqgtldffqgcgfsmltkwcskslvnreyfk--at-atvrecldlkenl
kvrv----------vtqedhkemaarsvilgsssefaktvapggvnglie
eicahypedkpgyn----rttd--savepavgkalfahtgsvagvgigvk
gklltwyse---ygdleecqgrtigkqmdtvtvdlss-----cfhpkllp
spgnasayslggldnakvnrnlvrgls-tsafspswlaqllrlaegryf-
---dhnranlvkwkc----pisaddlglge--kaepegs--gkdsiatda
li--n
>node9
wipv-tsedsakqelvvgpps---ayttrackgslkecgfsncc----sl
vsn----cthhtgamrlc-------sh-akirteehilh--qliaspsvn
wsts--ceflpvqsvrheqllaad---tdhdpcydqiq-ageagwrirq-
vely------midfkpvrhegalilyiidasga-----pqccpfvpgwp-
-gevhatlgmyv---yhfkpgl------gtkf------afsvqtglfkkd
afvaeieeysgmkhsi-----tkgteqsavssslwrsnvsnsrnp----m
wyqgtadgfqgcalsllttwctlhlthhnciq--vt-ltvrdcleikegl
kvrv----------vvqedhkelavratilgsavekaktvksygvsglve
eicahypdekpgyn----ksgd--tspesavgkglfahddsgagvgegvr
gklltwysepvaygdleecqghnngseadpvtavfda-----cfhpkllp
spnagsayslggldalkfrrnkgrglk-tspigpgwlgqgarlaegryfa
aqnnhsrvnlikwkc----tktaaelnlvq--kaavkgg--gkeniatea
li--n
>node17
wiav-tgedsakqelvvappq---systrecngslkecgfancc----gf
vsn----sthhtgsmrlc-------sk-akirtqehilh--qligsptvn
rsts--ceflstqsvrqqhllvav---tnydpcydqvq-agvagwrisq-
gqly------midykpirnegtlilyiinalgp-----pqccpfvpgws-
-divhgklgmyp---lhfkpga------ggkf------afseqtsffkkd
tfvkeieeysgknngl-----akgteqtavssslwrsnvsqsrqs----m
fyqgtldffqgcglslltkwctlelvnhnyfq--st-atvrdcldikegl
kvrv----------vcqedhkemaaratilgsasekaktvkpsgvnglie
eicahypdekpgyn----ktad--sapesavgkalfahtnsvagvgigvk
gklltwysepiaygdleecqghpngkqmdsvtvalda-----cfhakllp
spnnasayslggldnmkirrnlvrglk-tsafgpgwlaqlarlaegryf-
---ehsrvnlikwkc----tktaddlglge--kaavegg--gkdniatea
li--n
>node7
wvva-vgedmnkailvsgppg---aytkhsckgplkdcglfnca----kv
vsn----cavhtpdeklc-------sn-ekvtnqdhilqmwqlevsgtvq
wnta--cpflfdqkvkredlmhae---rhhdpcynqaf-tcdgqwwekr-
iklyiqdfehlagfkearldgprmkcisdslka-----paacmyvahwe-
-tvinaklsmyg---ynfksds------gakf------altvelglfkkg
sfyialkretgmaeglfdadftnghhq-gketplwrdtvanerhp----l
ryrgaspqyqgcclmllspwsilnlihnectdthlr-ynvrqcldrgesi
kvki----------ivhenhptglvrsgmakni--kpkttitadhpslvk
qvqgqyck-tpgys----kftd--irpetavsrdtfaredagvavgqgvr
aadytwynqqvfygkggdcsnspdktlstgstflleayiavscfepgmah
k-gggasnslagthaltfkegkgkgir-nspiepvwlaqkmilpnsr-va
aendhakvrpsdfkcpvleattttdsnlve--kpaakgg--gkdnlvrea
lv--d
>ENV_HV2D1/24-501
wiav-tsedsanqnlvvghpq---systrecnhslricgfancc----gf
isn-------ntgskrls-------sr-kkirtqdhilh--smigkptvn
rats--ceflttqsvrqqhllvaa---tnhdpcydavq-sgsagwrige-
vqly------qidykpirnggtlilyiinalsp-----lqccpfvqgws-
-eivhatlgmyp---lhfkpga------ggkf------afsaqtaffkmd
afvkaidqfagknngi-----ekgtertavtsslwwdnvsqarqn----m
fydgtldlfvgcglqlldkwcqlelvhndyfq--it-vtlrdcldikigl
karv----------vcqednkekpvkatilgsesqm--------vnglie
qicqnypnekpgyk----ktad--rasesavgkalfaqtnsvagvgvgvk
gklltwycepvpygeleecqgepnskemds-tvalna-----cfhakllp
spnnatayslggldnmkyrmnkvrges-tspfgphwlaqlarlaekryf-
---ehsr---ikwkc----tktmenlhfae--kgavegg--gkdnietea
li--d
>node14
wiav-tsedsakqelvvghpq---systrecngslrecgfancc----gf
vsn----cthhtgsmrlc-------sr-skirtqdhilh--qligkptvn
rats--ceflstqsvrqqhllvaa---tnhdpcydpvq-agvagwrisq-
gqly------midykpirnegtlilyiinalgp-----pqccpfvpgws-
-divhatlgmyp---lhfkpga------ggkf------afsaqtaffkkd
afvkeieqyagknngi-----ekgteqtavssslwrsnvsqarqs----m
fyqgtldffvgcglslltkwctlelvhhnyfq--it-vtlrdcldikegl
karv----------vcqedhkempvratilgsasekaktvkpygvnglie
qicqhypdekpgyk----ktad--sssesavgkalfahtnsvagvgigvk
gklltwysepvaygdleecqghpngkemdsvtvalda-----cfhakllp
spnnasayslggldnmkyrrnkvrgqk-tspfgpawlaqlarlaekryf-
---ehsrvnlikwkc----tktaddlnlae--kgavegg--gkdniatea
li--n
>node18
wiav-tsedsakqelvvgppq---systrecngslkecgfancc----gf
vsn----cthhtgsmrlc-------sr-akirtqehilh--qligsptvn
rsts--ceflstqsvrqqhllvaa---tnhdpcydqvq-agvagwrisq-
gqly------midykpirnegtlilyiinalgp-----pqccpfvpgws-
-divhatlgmyp---lhfkpga------ggkf------afsaqtaffkkd
afvkeieeysgknngi-----akgteqtavssslwrsnvsqsrqs----m
fyqgtldffqgcglslltkwctlelvnhnyfq--vt-vtvrdcldikegl
karv----------vcqedhkemavratilgsasekaktvkpygvnglie
eicahypdekpgyn----ktad--sspesavgkalfahtnsvagvgigvk
gklltwysepvaygdleecqghpngkemdsvtvalda-----cfhakllp
spnnasayslggldnmkyrrnkvrglk-tspfgpgwlaqlarlaegryf-
---ehsrvnlikwkc----tktaddlnlge--kgavegg--gkdniatea
li--n
