>ENV_HV2NZ/24-502
ldk--elpadrdpslgtql-------ffaaflsnqveptehfaakgclrk
nesdssqhkdvreehekki----glwldhpavteqklshgvgwgkksegq
dasafkvndtaeikfqegtvaqle----glkyapyrkmcagnlrkrg-ks
aaqlpgr-a---gknkttqlg-----nassgsevtvrpneightrdsvkp
nsstvyvpcgtndgahlaatdgssfdikglskmktgfaasvdnimkptla
mfgiagcgvliqmcadktkfec-----------wrg-vpce-qneyvpgv
k-------a--g-gadswrsdaglngrqtqldtgkaydgrhhgc-p-fvg
telaqpysdgpsktksp-------gygclpdf--s-lstdakhgtnyisc
t-----ivtkvlsl---haqv-h----hkrkcahtsytgskq--------
-agkiwvktasqetsfkflgsffenassrasrlgtpssfsvhhqscpltf
tah-kaferfnvfpscqkrgngg---vck----pd--qla-eg--ildki
aaaaraasplvgs---liqvgshliclskepfiaedhsvvss
>node19
ldk--eipmdraeslgaql-------ffgpflsnqvdpsehynvrgclrk
hdsdssqhkdvredhetkk----kmwvdhpavtepklthgvgwgkksegq
dagpyqvssthkinfkestvsple----nlkyaqlrkmctgdlrdrg-ks
aahlpgr-a---gknkpaqls-----naasgsdvtvrpnevnhtrdsvkp
ksstvyvpcgtndgellaltdgssfdmkfmpkfksgfagsvdaimkpkla
mfglvgcgvliqmcaemikfdcnpgrtlpellgwsg-ipcg-qndtvpgv
k-------a--g-gaaawrsdeglegkqtqldtgkaydgrnhgc-phfvg
tdlaqaysqgpvktksp-------gygclpdf--g-lptdarhgtkfitc
t-----dvakvlsl---haqv-h----hkrecphtsytgakq--------
-vgkiwvktasentsfkflgtfyqnksprasrlitpqsysvhh----lvf
tah-ksftrfgvfpscekrgdgg---vck----pa--qia-dg--ilddt
aaaaaaaaplvga---virlgshliclnnepfiaenhgvvas
>node7
ve---saviamaiplganl-------fylqllrdaispsedykvkgslek
hdeetkvkngikn-kvksryqtckpwvnrdftpplplnhemdweelvege
e-----------------vdlalg----klklaqlidlcddrlrrmtiva
sahlpdrin---agkrdlqli-----dvggpcsahgiaqkskqgdecinm
kqstkyesgtvsegeilckpdlavfkvklkgrnnrtfpssiearqspire
lfslvgcsimlfag-tlvkftvnasrtlhdnsgwas-vgya-ysatppgv
prvstesfm--r-gppawrntleknskqttlhtgrayvneengd-sqyss
ldlypaygqvsisanpp-------sfrclkaf--l-gpvacrqgenlfsc
svsaaaggpkvlnl---sahe-l----lpkacphtaesgwef--------
-pkatwaevhsgsygykfietffaagnskskklvvpsaysags----lvf
taq-arfaaf-lfddcqt----g---gce----cadsptt-gd--piaal
idknappaalsmi---igpkinhmiclnddylvghvhaavsg
>ENV_HV2D1/24-501
lek--eipmdraeslgarl-------yfgrflsnqvgpsegynvrgclrk
hdsdrsqhrnvredhdtkk----kmwvdqaattepklthgvgwgskgegq
dagpydacstnkitfkestvsple----llkypqlrkmctgdlrdng-kd
yahlpgr-a---gknkpaqls-----naagstdmtvranevnhtqdnvkp
nsstvyvpcgtnegnllaltdgssfdmkfmpsfklgfagdvdatmkpkla
mfglvgcgvlislcaemikfdctpgttlpellgwrg-ipsg-qndtvpav
m-------a--g-saaawrsqeglegkqklldtgkacdtknhgc-phlid
telaqafgqgpqktksp-------gygcvpdf--g-lptdarhgskfitc
t-----lmgkvlsl---kgqv-h----fkracpktsytgckq--------
-igkawiksanqyttfkflttfyqnksprmsrlitpdsysvhq----lvf
tah-ksftrfgvfpscelrgdgg---ick----sa--qia-vg--ileds
aiaaaaftpliga---pirlgwhlvclnneaflaenhgvigs
>node17
ldk--elpmdrapslgtql-------ffapflsnqvdpsehfnargclrk
hdsdssqhkdvreeheikk----kmwvdhpavtepklthgvgwgkksegq
dagayqvsgthkinfkegtvsple----glkyaqlrkmctgdlrdrg-ks
aahlpgr-a---gknkpaqls-----nassgsdvtvrpneinhtrdsvkp
ksstvyvpcgtndgehlaltdgssfdmkfmpkfksgfaasvdaimkpkla
mfgiagcgvliqmcaemikfdcnpgrtlpelwgwrg-ipcg-qndtvpgv
k-------a--g-gadawrsdegldgkqtqldtgkaydgrhhgc-phfvg
tdlaqaysdgpaktksp-------gygclpdf--g-lptdarhgtkfisc
t-----ivakvlsl---haqv-h----hkrecahtsytgakq--------
-agkiwvktasentsfkflgtfyqnksprasrlitpqsfsvhh----lvf
tah-kaftrfgvfpscekrgdgg---vck----pa--qva-dg--ildkt
aaaaaaaaplvga---virlgshliclsnepfiaenhgvvss
>node9
ldklceigldraeslgaql-------fflpflrnqvdpsehydvrgclrk
hdsdskqhkdvreihetkq----klwvdhnaapqpklthgvgwgknsegq
dtgpyhassshklnfkettvtpld----nlkyaqirkmctgdlrdrs-ka
nadlpgr-a---gknkpaqlt-----nlasgcsvtvsenqvshtrdsikp
ksstryvpcgandgellaltegssfnmkfkskhkkgfagsvdatmkpklq
mfglvgcgvllqmcvemikfdcntgrtthdllgwsg-ipcg-hndtvpgv
ssaspntya--g-gtaawrsgqgldgkqtaldtsksytgqdhgc-phfvg
adlaqaysqgpvptksp-------gygclrdf--a-lpvdsrhgtkfitc
d-----eaakvlsl---qdqv-l----hkrecphtsytgskq--------
-vakiwvktdsestsfkflgtfyeggspraaklitpqsyavhp----lvf
tah-nsftrfsvfnscekrgdgg---vck----sa--qia-dg--ildat
aataaaaaplvga---viwlgshliclnnepfigenhgavas
>node10
ldklceipmdraeslgaql-------ffnpflsnqvdpsehydvrgclrk
hdsdssqhkdvreihetkk----kmwvdhsavtepklthgvgwgkksegq
dagpyhvssthklnfkettvsple----nlkyaqvrkmctgdlrdrg-ka
aahlpgr-a---gknkpaqls-----naasgcdvtvspnevnhtrdsvkp
ksstvyvpcgandgellaltegssfnmkfmskfkkgfagsvdaimkpklq
mfglvgcgvliqmcaemikfdcnpgrtlhdllgwsg-ipcg-qnetvpgv
t-------a--g-gtaawrsseglegkqtqldtgkaydgknhgc-phfvg
tdlaqaysqgpvktksp-------gygclpdf--g-lpidarhgtkfitc
t-----eaakvlsl---hdqv-h----hkrecphtsytgakq--------
-vgkiwvktasentsfkflgtfyqgnsprasrlitpqsysvhp----lvf
tah-ksftrfsvfnscekrgdgg---vck----pa--qia-dg--ilddt
aataaaavplvga---virlgshliclnnepfiaenhgavas
>node8
ve---nvvidkaiplganl-------fylqflrnaispsedykvrgclrk
hdnetkvnngiksikeraryqtckpwvnhdftpppslahetdweelpegp
e-----------------vdlalg----klklaqlitmcddqlrnlt-ka
saelper-e---agkrpaqli-----dvnggcsahvlanqskqteetinm
ktstkyesgtvsegeiltepdlsafkvklknrndrgyagaiearkspvre
lfslvgcgillrac-tmvkftvnnaktvhnnsgwas-vpys-ysdtspgv
srvstetfq--r-gppawrnglekngkqttlntgrsyvgqdhgd-sqasg
qdlyhaygqvsasakpp-------sysclrdy--l-apvdsregqqlfsc
stsaaaggpktlkl---sade-l----hpkacphtaesgwqv--------
-akktwaevhsssyaykfietffpagnsrtkklvapesysags----lvf
tiq-arfdsf-lfdecqk----g---gce----cgdsptt-gd--pvsat
adenappapltgi---agpkinhliclnddyqigqvhapvgs
>node11
ldk--eipmdraeslgaql-------ffgpflsnqvdpsehynvrgclrk
hdsdssqhkdvredhetkk----kmwvdhpavtepklthgvgwgkksegq
dagpyqvssthklnfkettvsple----nlkyaqlrkmctgdlrdrg-ks
aahlpgr-a---gknkpaqls-----naasgsdvtvrpnevnhtrdsvkp
ksstvyvpcgtndgellaltdgssfdmkfmskfksgfagsvdaimkpkla
mfglvgcgvliqmcaemikfdcnpgrtlpellgwsg-ipcg-qndtvpgv
k-------a--g-gaaawrsdeglegkqtqldtgkaydgrnhgc-phfvg
tdlaqaysqgpvktksp-------gygclpdf--g-lpidarhgtkfitc
t-----dvakvlsl---haqv-h----hkrecphtsytgakq--------
-vgkiwvktasentsfkflgtfyqnksprasrlitpqsysvhr----lvf
tah-ksftrfgvfnscekrgdgg---vck----pa--qia-dg--ilddt
aataaaaaplvga---virlgshliclnnepfiaenhgvvas
>node18
ldk--eipmdraeslgaql-------ffgpflsnqvdpsehynvrgclrk
hdsdssqhkdvredhetkk----kmwvdhpavtepklthgvgwgkksegq
dagpyqvssthkinfkestvsple----nlkyaqlrkmctgdlrdrg-ks
aahlpgr-a---gknkpaqls-----nassgsdvtvrpnevnhtrdsvkp
ksstvyvpcgtndgellaltdgssfdmkfmpkfksgfagsvdaimkpkla
mfglvgcgvliqmcaemikfdcnpgrtlpellgwrg-ipcg-qndtvpgv
k-------a--g-gaaawrsdeglegkqtqldtgkaydgrnhgc-phfvg
tdlaqaysqgpvktksp-------gygclpdf--g-lptdarhgtkfitc
t-----vvakvlsl---haqv-h----hkrecphtsytgakq--------
-vgkiwvktasentsfkflgtfyqnksprasrlitpqsysvhh----lvf
tah-ksftrfgvfpscekrgdgg---vck----pa--qia-dg--ilddt
aaaaaaaaplvga---virlgshliclnnepfiaenhgvvas
>ENV_HV2G1/23-502
ldn--eipmdkaeklgaql-------ffgaflsketdpsghynvngclrk
hdsdcsahkdvradhetkk----kmwvdhpdatdpklthgvgwgkksegq
dagpyqtnsthklnfkgtfvsrle----nlkyaeqrkmctgdlrdrg-ks
aahlpgr-a---gknkpiqlctqtkynaisgsdvtlrptevnttrdsvkh
kaskiylpcgtndgellaltdgfsfnmnfmskfssdyagsvdaimkpkla
mfglvgcgvliemciemikfdcnpgrtlpelfgwtgklpsg-qfdsvpgv
k-------a--g-gaasrrsdeslegkqtqldtgqaydgrnhgc-phfvg
pdliqaycegpvlsksa---fqcggygclpdf--g-lpidashgtkmitc
t-----dvakvlsl---hkqv-h----hkrecphtgytgtkq--------
-vgkiwvkt--------flgtfyqskspkasrlikpqgysvhr----lvf
dah-kaftsfgvfnscdkngdcg---ack----pa--qil-dg--ildds
aataaaaaplvga---lirlgchliclfnepfiaeshgvvas
>ENV_HV2D2/24-513
ldkicevpmeraetyvpqi-------ffdpflgsqadppgnyevrgclrk
lsseasqakgvrqchefkk----klfveqsaiaepkltngvgwgkasegq
dagpyhvscvhklkfkettsspld----tlkyaqvkkmctgdmkdrg-qe
alrlpgr-angtgknkaalld-----aaargcdltvgpnavahardsvkg
kaatvyvpcgamdgqllsltegssvtmkfmtkfnkgydgsvdtvmqsklq
mllltecgiltqmcsdlftfdvhpgrtlhkllawan-vscg-qngsvpsv
v-------a--g-gtgasrasealeakqtqlatgkafdnkkrgc-phfcg
tdlaqslaqgpvatqkp-------kygclphfrqg-kaidtghgskfetc
t-----saarqkpl---ldqi-hcckwqprecshtpylgekq--------
-vgtvwvktetenvsfkflgvyyqgnspradrlitfqsfclhp----lif
iah-ksftrfsvfaaceksgdgg---vcr----pn--qip-ng--ilenq
asttaaaipliga---vvrlashltc-nktppiaarhgavps
>ENV_HV2BE/24-510
lek--eipmdrsdslgaql-------ffgrflsgqvdpsdgydvrgclrr
hdsdasqfkdvredhnakk----kmwvdhptttepklahvvgwgkksegq
dagpydagsthkitfkestvgpte----glkyaqlrksctgdlkdng-ka
ylhlpgr-s---gsnkpiqls-----eassgydvtvrpdevkhtkdsvkp
k-stvyiacgtddgelialtdgssfdmkfmgkfklgfarnvdaimnpkla
mfgl-gcgvliqmcaemikfdcnpgralpellgwhg-mpsg-qnkkvpgv
k-------a--g-gaaawrseeglegkqtpldtgdacdgrshgc-phfvg
tdlaqtfsqgpvktksp-------gygcmpdf--gyllsdarhetkfvtc
t-----tvekvlfl---dgqvqh----fnracphtsytgakq--------
-igkewvkpasenttfkflgtfyqekaprasrlitpqsygvhy----ivv
sph-ksftsygafptcikrgdggpegick----pa--qla-dg--ilddt
agadaaaanlvvk---virlgqellclnnesfiadghdvist
>ENV_SIVM1/24-528
ldrlceigldrleglglqf-------fflpflrdkagpsehyqvrkclre
hdsdrtqhkeirefhttkq----klwvdrnaapqpkkthavnwgknsdgq
dtgpyhassshkvhftaasvcpld----nlkyaqirkmctgelrdrr-ra
ngdlpgr-a---gktkpahlt-----nlangssvtvaenqvshtraskkp
ksctryvpcgqndgellgllegscfdmkfksmhkkgvagmidatmkhklq
mfnlvgcgvllgmctqmikfdcntgrtthdllgws--ipcg-hkdavpgv
ssaspntya--g-gttewrsgqgldgrqtaldtsnsynghnpgc-phfvg
adlaqgytqgcvptksp-------gygclrdf--a-lpvetrhvirfvtc
d-----egakvlsl---qdqt-l----hkrecpytgytgskn--------
-vakiwv-tdsesttfeflgtfyeggsprgaklvspqtyavhp----lvf
tahnhsftrfsvfnasekrvdgs---vck----ta--hia-dg--tldat
aataataappiga---viwlgtqliclnnepyiteehgavas
>ENV_SIVGB/47-569
vc---tneitkatalkeaigkdetggkyddwlhsllvdvmqsvvratfrk
qndh-dlkpgaggf----kaescgefiddeflllpgigaqadskdhaphp
g-----------------vveeag----rlmlgglalkceehgktln-ht
ttkfasq-l---vddqpkcyt-----dlsggcisrvngtstkvad-tvii
nnaskfknvpctlvdftsafdlkqlninvkgkhcen-----tnanrtsre
alnliisdlfllnc-anlniathslwkaapliswie-spfaaytevippv
rqehtd-fr--pvdspgwligvdksgrdin----rgyrgdevvgstqipa
qdyfrtyhkf----pthgrf----afsclrsf--y-pdqikkfpgaifvc
gssgppggkhalhcgnenldt-l----kikhclttsevgwel--------
-vkkkwgpercwafdflepktifpapryptrktkhinpyssgg----svf
kah-safepk-iynecqk----g---ice----rsgifdr-nernpask-
ahhnhkelplsl----yeevianlvcvkkvfhvcqggiavas
>ENV_SIVG1/22-522
ve---savievavplpdnl-------fyihllrdavspsndykvkgalqk
ndketkvkngikn-kvksryqsckpwvnrdftppavlnhemdweeiaege
n-----------------vdialgigavk----hlidlcddrlprmtiva
sahlpdiia---tgkrdleli-----evggpcsqhaiaqkskqgdecvam
kqstkyesgtvsegeilckpdlgvfkvvlsgrnnrtfptsiparqsslre
lfslvgcsillfgg-llimftvnaspalhdnpgwag-vgya-yspspqai
prvseesfm--r-gppawrnvleknnqqttlqtgrayvneeqge-sqyss
lslypayaqvkigdnpp-------sfqclkaf--l-gpvacrqgenvfsc
gvsggsgvpkvlnl---sahe-l----lpkacphsadsgwlf--------
-pkatwaevhagsygykfdqtafaagnnkpnklvvpgafsagg----lvy
taq-arfaaf-lfdncnt----g---gce----csespst-gd--pigal
idknappaglsmi---igpkvnhmvclgdeyfvshtyiavsg
>ENV_SIVV1/24-538
vh---savvarairlgnnl-------fymqalrdalddsgeykvkgslek
hdgatqvkngikd-tvksraqgckpwiakeftpslilnaemeweelvdgd
e-----------------velalg----slnhaqlfd-----lrrmaeva
qadlpnrin---g-krdlqli-----dvdgecpcqiivqnskqgdecihm
khsakyqgaevsegeilcepdlqviktkkqgrn----pakiephqsavrn
lfllvghptlvlaa-tlvkftvnakrqlhdsrgwes-geng-ycvappgv
pkvstqkfm--r-ghpdwrhkldkeakqstlrkdkdylaqdagd-gqyss
ldlfaayvgvtiqegpp-------tfrclkdf--l-gpasckvgeklfac
sgshdagaakvlnn---tene-l----atkacapthdggwadsketslgg
vpkagwleapaepygykfincffvngkqkskiivppsaysmgn----lvf
kag-akfnaf-lfeeclp----g---gcecpercsdnptt-gd--pitgk
akknappgtlgmlgptighkiahmvcmddqylvahhhaggsg
>ENV_HV2CA/25-512
ltk--eldlqhaptkatql-------flalflsnqvahsehfnqkgclrk
hksdtkqhknvrdehnikk----kmwvdhpavtepklthgvgwgkksenq
dagnyqvagthkinpkegkvsple----glkytqlrklctgdlrdqg-ks
sshlagr-p---gkdkpaqls-----dassgsdvtvrpnqinqtqdsrkp
kqgvvyiscgiddgehlalagggsfdlnfmpkfksgfafdvdaimkpklp
mfgvagckvliemcaemikfdcnpgrtlpelwswrg-ipcg-qidtvpav
k-------avav-gadawrsdegldgkqtqldtgkaydgkhhgc-phfvg
thiaqaysdgpaktksp-------gygclpdf--g-lqtdakhgqkfvkc
n-----gvikkwsl---hapt-h----hkrecartsytgakq--------
-agkiwvssaseyssftflgnfyqkkspralrlltpqsfsvhh----lvf
saq-kafttfgiftscgkrgdgg---vck----pa--eiafdg--ildkt
aaaaaafttlvga---virlgthliclsnesfiaeehavvss
>node14
lek--eipmdraeslgaql-------ffgrflsnqvdpsegynvrgclrk
hdsdssqhkdvredhdtkk----kmwvdhpattepklthgvgwgkksegq
dagpydacsthkinfkestvsple----nlkyaqlrkmctgdlrdhg-ks
yahlpgr-a---gknkpaqls-----nassgsdvtvrpnevnhtrdsvkp
ksstvyvpcgtndgellaltdgssfdmkfmpkfklgfagnvdaimkpkla
mfglvgcgvliqmcaemikfdcnpgrtlpellgwrg-ipsg-qndtvpgv
k-------a--g-gaaawrseeglegkqtqldtgkacdgrnhgc-phfvg
tdlaqafsqgpvktksp-------gygcmpdf--g-lptdarhgtkfitc
t-----vvakvlsl---hgqv-h----fkracphtsytgakq--------
-igkiwvktasenttfkflgtfyqnksprasrlitpqsysvhh----lvf
tah-ksftrfgvfpscekrgdgg---ick----pa--qia-dg--ilddt
aaaaaaaaplvga---virlgshliclnnepfiaenhgvigs
