>ENV_HV2G1/23-502
tfshigd-yprnckfkwtlinhnhnlypdktlqen-pigsklveavvcsg
vtemg---yvntdqmvkgmwvatkktvdyvascgyvckdtvgnavckyks
nsnvitgvc-------t----epicvek---vist----------gtlqp
-------elrh---tknqpvlpllqpkafgdlnkvvgptne-------dp
efadyhyadysiq----dsdtnfqdlignctlgeknvnnviglhytkrn-
-paidwvvaektgadgt--q------gtlcstndpkdqls--pke-ag-p
sk-tghnydghqinparvpdtqpyavqtgfrksgnafhdsikddakrvtk
msrkrppvpgkslvgq-----ksgtnhsrilggilendpkmvgmlgdai-
-----cckcffh---leyrqilqtk-----mivkdwwptkavvq----cf
ynspgitgt------trrc---igktihvlkfrqtlskkrpigskgdklp
pp---ltdskp----eqdeil----rvv--------etfvmaadhacvka
alng-lidsaacakqegrfttfaslsladflalmhnggsylsfhselfqp
clg----ptaavicprapqla
>ENV_HV2D1/24-501
kfshign-yprlckfkwtliqhnhnmypdktlqqn-pigsklanaivtgg
vtavg---yvnddhkvkdqwvatkktvdyagscgyvckhsvgsivckyks
ksnvisvvcpegdsqya----epicvdk---visk----------ltlep
-------elrr---trdhpvlpllrsktfgslgsilgpvnd-------dp
efadyhyaeysiq----dkdgnfqaldgnctlgekkvnnliglhytkrn-
-pgidwvvakstgadghhiqikngkhgafcathqandqlk--akg-sg-p
nr-tgrkfdshqinavrvsdtqayavqaglrkgghaihdpikddqkrvtk
vqknrppvhgkaligq-----ksgtdhsrvltgvlegdpkmvgllgsat-
-----cckcffd---lqyrqlidtk-----liiqdwwpakavvq----cf
ldtpgitgt------trrc---mgktihvlkfrqtlrknrpdgskgdklp
rp---gtdnkp----tedeil----rva--------vtftmapdhacvkp
altg-lvesaacvkqtpkfntfaslklasflaplhnggsyfsfhtklfep
cvg----ptaavfcarapslq
>node19
kyshigd-yprnckfkwtliqhnhnlypdktlqen-pigskladaivsgg
vtemg---yvnddhkvknmwvatkktvdyaascgyvckdsvgnavckyks
nsnvitavc-------t----epicvdk---vist----------gtlep
-------elrh---tkdhpvlpllrpktfgnlnsivgptnd-------dp
efadyhyaeysiq----dkdtnfqaldgnctlgeknvnnliglhytkrn-
-paidwvvanktgadgt--q------gtlcatndpkdqls--pks-ag-p
sk-tgrnydghqinpvrvpdtqayavqagfrksgnafhdsikddakrvtk
mqknrppvhgkslvgq-----ksgtnhsrilsgvlegdpkmvgmlgdai-
-----cckcffd---lqyrqiidtk-----miirdwwptkavvq----cf
ldspgitgt------trrc---igktihvlkfrqtlsknrpigskgdklp
pp---wtdnkp----qqdeil----rva--------etfvmaadhtcvka
alng-lidsaacakqqskfdtfaslslasflaplhnggsyfsfhtelfqp
cvg----ptaavicprapqla
>ENV_SIVGB/47-569
hfth------tq---lr---ehvtdglede--dpq-nv-psqnrridtfa
nggva---stsi--rqdrhwacafiflkrndvsgylvats---t------
p--v---at-------sttvl---cnydglvffdqaveshqksvtgitnq
-------dlkhahagy----mvtvkfk-----eagchekssqtypsivak
afdv---vlstshitglhkkpifp----pcng-------yrkvqlsedn-
-srgvwspglgv--nrd--t------itpcdnnerkslca--gstkqn-l
frgladpsnppsldigyr--hqppamkdfaktga-dfygac-s-------
--------i----adgkehiaqegngedhtp--------riltdlelyv-
-----cnlysse---vkkrgtkgsa-----viiahwwlt-tlvgvvpfcv
tsvedttkp------vkscevpasrhlgvlkaaatlawkahtttmpgela
pqrrdln---m----nnqkvlcdkikld--------dadlaadfkncpkn
algtaeskvhvggmtaaepqssthcpnaay----eagtcfllntlrvfgk
kyf----evcqagcknaspss
>ENV_HV2CA/25-512
kyshigdpyprnckfkwtlishnhniykdkalnen-plgpkladailssg
vtqmg---yvnddhkvknmwvnsnktveyasacgyvckesygnavckyks
kanvitavc-------t----epicvhk---miss----------galep
-------vlrn---tkehpvlpllrpknfgslsstvgqagd-------ep
elgdyhyaeypiq----qrdtsfnvidgncslgeknindliglhytkrn-
-pplnwlvaaktgaagt--q------gtlcctnepkeqls--sks-eg-p
ss-vgslydgqqinpvrvpntqayalqsdfkssgntfhdkikedekrltk
mqknrppvhgkslvaa-----ksggnhnrflsgvlegepastgllgdai-
-----ccncffg---lqykqiidik-----viirdwwpnkavvq----cf
lqppkktgt------trrc---igitfhvlkfreslaknrpigsegeklp
pp---wtdnpp----qqdeil----ria--------etfvaeadhtclkc
pfkg-lvdgaacakqhskmdtgaslsvagfltplhnggtyfaihtelfqp
cvg----ptarvicprapqls
>ENV_SIVV1/24-538
hyth------dq---nrlflareqkikgekalgennpigtggdvhqqigg
ivgaq---svdevrridhlrsetrhfgnwkkkcaflkvrggled------
vgslgtkve-------cepts---cvks---wadk----------tpvkr
lpssthhdlkelpavy----lvgldsktf--anea--pgcd---------
-----iqvtftvdpyklretgifq----dctlgadaghhftg---kend-
-p--awptrpdgngdet--r------ttlcakrspnsnca--ntg-gd-p
gssqtedntdpgvspviq--qp---iraffkkgpdqfegga-q-------
--------sayafidl-----aaghnslkevgdvlgsgptfvnmlvclvg
hvegecaacflq---letinsidtk-----lvtnkwwsh-tvle----cf
vsitgaahv------lstc---iapdeqvlkvraqhakrrpdnctllpqg
tm---wa---lgqltlpsnvv----raa--------nieimml---caes
kfkgkfadrnncqcgkdrvhscadcelanl----hgggsfhsyctpifag
eipqlrqecynvscakgshfr
>node11
kyshigd-yprnckfkwtliqhnhnlypdktlqen-pigskladaivsgg
vtemg---yvnddhkvkgmwvatkktvdyaascgyvckdsvgnavckyks
nsnvitavc-------t----epicvdk---vist----------gtlep
-------elrh---tkdhpvlpllrpktfgnlnkivgptnd-------dp
efadyhyaeysiq----dkdtnfqaldgnctlgeknvnnliglhytkrn-
-paidwvvaektgadgt--q------gtlcatndpkdqls--pks-ag-p
sk-tgrnydghqinpvrvpdtqayavqagfrksgnafhdsikddakrvtk
mqknrppvhgkslvgq-----ksgtnhsrilsgvlegdpkmvgmlgdai-
-----cckcffh---lqyrqiidtk-----miirdwwptkavvq----cf
ldspgitgt------trrc---igktihvlkfrqtlsknrpigskgdklp
pp---wtdnkp----eqdeil----rva--------etfvmaadhtcvka
alng-lidsaacakqqskfdtfaslslasflaplhnggsyfsfhtelfqp
cvg----ptaavicprapqla
>ENV_HV2BE/24-510
kfkhigd-yprnckpkwtliqhnhnlypdkalqen-sigtqvasalvsgg
ftevg---yvnddpkvknmwvatrksvdypatcvytckhdvgnavcryks
ksnvitavc-------t----epicvds---ni------------gtlep
-------elrh---tkdhpvlpllrsktfgnlntivgptne-------dp
efadyhynetria----edsknfqelqgdctlgekninnliglhytkrdk
spgidwvvsnktgadgn--qikgaahgtlcatddskdevh--aks-ae-p
nk-trrtfdghqikavrtseaqayavkagfrksgngfhdtikseqkrltk
vhkkrppvhgkhlimq-----ksgvnhnrnlstvlegdpkmvgvlgdai-
-----cckcyfd---lqykqiidtk-----fiirewwpsravhh----cf
ldlpgitgt------trrc---vdktihvlkfsntlkksrpvnrkgnklp
pp---wtdntp----qqddil----ria--------esfvmaadhayvka
alng-liakatcvkqikkfdtfaslknasfltplhnggaylsyqtelfpp
cvg----atvavicpkapklq
>node7
hyth------eq---nrlflaheqkiygdkaltqs-pigigadkhvqigg
iggqr---hvddehkiehmwaqtrhfvdwdsacgflkvqtgled------
tgslgthve-------ceqts---cvds---wtdm----------ssvkh
lasfthhelkalpavy----ivpirsktf--inlg--pgcd---------
-----vhvlfgvdplklhqtgtfq----dctlgdkaghhfigmhfkknd-
-pkihwptqpngnadet--r------pslcstdspnseca--sts-gd-p
atdqaekhndhsvspvfk--el---irtffkkgphqfdgga-q-------
--------tayalvgq-----ssghdniaeiggvletqpkivnllaclv-
-----caacflh---veiinstdtk-----lvvnnwwpt-tvve----cf
vpikgasht------lrtc---iardvqvlkvrqqharrrpdnctalpqg
tk---wa---g----lpknvl----rlt--------nieimaifntcaea
kltgrfadrnscqsgppkvqecadcalaal----hlgssfhsfctpifag
sip----qcydvacakgaqfr
>ENV_SIVM1/24-528
kfnh------rhckfdwtyiqhnhnlyaektlkdg-pignklataivpgg
vtetg---yvndehkvrgvsaatkkfvdytascgyvcvdstgna------
ksnvvtdve-------t----epicvde---iint----------gtvdp
-------klrs---akdhpvlpllrpkiignlniivssand-------na
eftnyyyeeysid----drqtnlqaidgnctlgeknvnsliglhfskrn-
-pavdwavadkagadgt--q------gtlcatddakdhls--pmf-gn-p
rk-tgkhydghqinplfvadtqaiarsaffrpsgnafhdgskdeakrvgk
kqtnrqevkgksldgq-----dsgashvrilsnvlqnepkilgmlgdav-
-----cggcyfh---vqyrkridte-----malrdwwpthtvlq----cf
ldpfgvsdi------lrkc---igksihllksrqtlsknrpigskahklt
pv---wtenkp----sqdail----kvm--------aqfvmaadntcana
glgg-lihsaacakqeakftafqglslasflthlhgggtyfshftelfqp
cva----atcavicphgpqla
>node9
kysh------rnckfdwtfiqhnhnlypdktlkeg-pigskladaivsgg
vtetg---yvnddhkvkgmwaatkkfvdyaascgyvcidsvgns------
ksnvitdve-------t----epicvde---iist----------gtvep
-------klrd---vkdhpvlpllrpktfgnlniivspand-------dp
efanynyeeysie----drqtnfqaldgnctlgeknvnnliglhfakrn-
-pavdwavadkagadgt--q------gtlcatddpkdqls--pks-gg-p
kk-tgknydghqinpvfvpdtqayavsaffrksgnafhdgskddakrvtk
kqknrqpvngrslvgq-----ksgtnhvrilsgvlegepkilgmlgdai-
-----ccacffh---vqyrqiidtk-----miirdwwpthavvq----cf
ldppgitdt------lrkc---igktihvlkarqtlsknrpigskahklt
pa---wtenkp----sqdeil----kva--------eqfvmaadntcaka
glgg-lidsaacakqqakfqtfatlslasflahlhnggsyfsfftelfqp
cvg----ptcavicprgpqla
>ENV_HV2NZ/24-502
kyahvgd-yprnckfkwtlirhthalfpgkslqen-plgsklsdgiksgg
vremg---yvnqdhrvktkwvaakkivnycascgcvcgnnvghpvckyks
ksnvitavc-------t----epecvdt---litt----------gtlep
-------plhh---kkghpalpllkpktfgtlnstvgptgq-------ep
dgldyhhaeypvq----dhdadfnaldgacslgekntnnligldytkrn-
-paadwvvaagtgadst--q------atlcatndpkeqlsrgsks-aa-p
sk-taklyggheinhvrvpetqayavhagfrksgstyhdklkddekratk
mqknrppvhgkslvga-----kaggvhsailsgtlegnptmsgklgqan-
-----cckcffd---vqlrqiintk-----ykirewwptksvaq----cf
ldssgisaa------trrc---tgksihvlkfrqtlaknkpigsmgdklp
pp---wsnhqp----lqnevl----kaahkfcaeefetfvmagdhavvkt
pfag-liasatcakqdstfdtfaslslvgrlaplhdggsyfsfhtelfqp
cvg----ptaavmcprapqlq
>node14
kfshigd-yprnckfkwtliqhnhnlypdktlqen-pigskladaivsgg
vtevg---yvnddhkvknmwvatkktvdyagscgyvckhsvgnavckyks
ksnvitavc-------t----epicvdk---vist----------gtlep
-------elrh---tkdhpvlpllrsktfgnlnsivgptnd-------dp
efadyhyaeysiq----dkdgnfqaldgnctlgeknvnnliglhytkrn-
-pgidwvvanktgadgn--qiknaahgtlcatndpkdqls--aks-ag-p
nk-tgrnfdghqinavrvsdtqayavqagfrksgnafhdtikddqkrvtk
vqknrppvhgksligq-----ksgtnhsrilsgvlegdpkmvgmlgdai-
-----cckcffd---lqyrqiidtk-----fiirdwwptkavvq----cf
ldspgitgt------trrc---mgktihvlkfrqtlsknrpigskgdklp
pp---wtdnkp----qqdeil----rva--------etfvmaadhtcvka
alng-liesaacvkqqpkfdtfaslklasflaplhnggsyfsfhtelfep
cvg----ptaavicprapqlq
>node17
kyshigd-yprnckfkwtliqhnhnlypdktlqen-pigskladaimsgg
vtemg---yvnddhkvknmwvaakktvdyaascgyvckdsvgnavckyks
ksnvitavc-------t----epicvdk---mist----------gtlep
-------elrh---tkdhpvlpllrpktfgnlnstvgptgd-------ep
efadyhyaeypiq----dkdtnfnaldgnctlgeknvnnliglhytkrn-
-paidwvvaaktgadgt--q------gtlcatndpkeqls--sks-ag-p
sk-tgrlydghqinpvrvpdtqayavqagfrksgntfhdkikddekrvtk
mqknrppvhgkslvga-----ksganhsrilsgvlegdpkmsgmlgdai-
-----cckcffd---lqyrqiidtk-----fiirdwwptkavvq----cf
ldspgitgt------trrc---igktihvlkfrqtlaknrpigskgdklp
pp---wtdnqp----qqdeil----rva--------etfvmasdhtcvka
pfng-lidsaacakqhskfdtfaslslasflaplhnggsyfsfhtelfqp
cvg----ptaavicprapqla
>node8
kysh------kq---nrlflahehkiysdkalkqg-pvgadavkhvqegg
iggqm---fvnnehkvkhmwaqtrhfvdwdsacgflsvdsgaed------
pgsigthve-------ceqts---cvds---wiet----------ssvkh
-------elkalpaly----ivsirsktf--inmgthpacd-------gp
dfprrvhvlysvdpmklhqqgdfq----dctlgdkpghhfiglhfkknd-
-pkvhwptapkanadet--r------ptlcstdnpkkecp--ptt-ge-p
andqaekyedhsvepvyr--elpygirtffkktphqfhggd-q-------
--------lahtlvgq-----ssgnnnvaviggvlqtqpkildllaanv-
-----caacflh---veirnstdtk-----mvvrdwwpt-tvve----cf
agmrgvtht------lrtc---itrdiqvlkvrqqharrrptgctalplg
pk---wa---a----aqkavl----rlt--------ddefmaifntcaka
kltgrfadisscpsgppkvqecadcalasf----hngssflsfctpvfae
svp----pvcdaacakgaqfk
>ENV_SIVG1/22-522
hytn------ee---nrlflahegkiygnkaltns-pigigedkhvqigg
iggqrkdphiddehkidhmwaqtrhfvdwdnpcgflkvatgied------
tgsigthve-------ceqtp---cvds---wtdm----------tavkh
lgvfihhelkalpavc----lvpiksktf--idlg--pgch---------
-----vhilfgveplnlhesgtfq----vcklgdkagnhfiamhykknd-
-prihyptqpsgnadet--r------pslcqtnsphgeca--sks-gd-p
atdedenhnehkvtpvfk--el---irtffkkgphqfdgga-q-------
--------tayplvge-----dsghdniaeigavlenqpkivqllaclv-
-----saacfmh---lgiisstdtkyyppllvvnnwwpt-avve----cf
mpiggakhn------lrdc---iardvqvlharqqhvrrsadnctalpqg
ak---wa---a----lpknvl----k-----------velkvifntcael
klagrfaertdcvsgnpkvqacencaltsl----hlgssfhsfctaiftg
sap----qcfdmtcpkgsqsr
>node18
kyshigd-yprnckfkwtliqhnhnlypdktlqen-pigskladaivsgg
vtemg---yvnddhkvknmwvatkktvdyaascgyvckdsvgnavckyks
ksnvitavc-------t----epicvdk---vist----------gtlep
-------elrh---tkdhpvlpllrpktfgnlnsivgptnd-------dp
efadyhyaeysiq----dkdtnfqaldgnctlgeknvnnliglhytkrn-
-paidwvvanktgadgt--q------gtlcatndpkdqls--pks-ag-p
sk-tgrnydghqinpvrvpdtqayavqagfrksgnafhdtikddakrvtk
mqknrppvhgkslvgq-----ksgtnhsrilsgvlegdpkmvgmlgdai-
-----cckcffd---lqyrqiidtk-----fiirdwwptkavvq----cf
ldspgitgt------trrc---igktihvlkfrqtlsknrpigskgdklp
pp---wtdnkp----qqdeil----rva--------etfvmaadhtcvka
alng-lidsaacakqqskfdtfaslslasflaplhnggsyfsfhtelfqp
cvg----ptaavicprapqla
>node10
kysh------rnckfkwtfiqhnhnlypdktlqen-pigskladaivsgg
vtemg---yvnddhkvkgmwvatkktvdyaascgyvckdsvgnavckyks
nsnvitavs-------t----epicvdk---vist----------gtlep
-------elrn---tkdhpvlpllrpktfgtlniivspand-------dp
efadynyeeysiq----dkdtnfqaldgnctlgeknvnnliglhfakrn-
-paidwivaekagadgt--q------gtlcatddpkdqls--pks-ag-p
ak-tgknydghqinpvfvpdtqayavqaffrksgnafhdgakddakrvtk
mqknrqpvhgrslvgq-----ksgtnhsrilsgvlegdpkmlgmlgdai-
-----ccqcffh---vqyrqiidtk-----miirdwwptkavvq----cf
idspgitdt------trrc---igktihvlkarqtlsknrpigskgdklp
pa---wtdnkp----eqdeil----kva--------esfvmaadhtcvka
slng-lidsaacakqqskfdtfaslslasflahlhnggkyfsfhtelfqp
cvg----ptaavicprtpqla
>ENV_HV2D2/24-513
kyph------rnakfkwtfiqlnhplyakktlqke-plgsrladsivsgg
vtdlg---yvkddhkvkgmwvatkktsnyvascgyvckgpv-eaackfkt
dsnvvtsmn-------v----epicvik---vlat----------gslep
-------elrl---nkthpvlpmlkpkgfntlnyivspant-------np
efgeynfdiyriq----ekdinfqetngnctlseknvhnliglhfavnn-
-pnidwpvdekagtdct--e------gtlcatdnprdqvs--pls-aglp
ak-tgkdyeghqinpvivpdtkaypvqtmfrrsantfhggakddarrvtk
ehkkrepvhgrasvgk-----nsvsnhkrrlngvlegdakmlgmlgtai-
-----ccqcfmhsdmvqerqiidsk-----mvirdwwpttavvr----cf
idspglantsdwvkytprc---igkmihvlmardtlsknrp--akgdklp
pa---wpgnks----eqderl----kva--------esfveapghscikt
slng-ltiseacakvaskfdtfatlalaslvahlhnggryfafetelfqp
cvg----ptspiicpktpdll
