>ENV_HV2NZ/24-502
melatyakv--eaeafpeqlpgddhdkyrsvyrgsgdqsdaipgvsrdci
grpdlsdlvpgenlglnlk---isaarktlkacf---ylalkatilvivp
clgt-n-------nrnf---ndakts----lcvswddkcsgiy-arrcya
--fahlyprmkpk----ekavkapwa-pfdtrvapsrfqpkrctpafyra
gadskcvpesrp----kgknnstyslqilcp---ggiqgkk--ttwfana
anqdmsqpkgsnfdfvlqtytdgt-igvsyaggyssfrlpggpnvls--v
iita--vtyeidphvekeiq--qvkffeaqfak-ggrqccslis----gw
hhlheptv-vaaigvkgphgakaqyergelidsspstdgwfnhgkknett
sfplqgcglp-retipeirrstilaereeihtlt-lcdqel-----nala
gpkkpek----klalgtsdvsrprklfieke--kmsh-----tl------
---tfkihyleavgpqpdylslsfvapyscdaggfk-plqyvgsdspart
sgvthlfdekkpasvgstlpegldteadlhkega
>ENV_SIVV1/24-538
aavnirkkaslmqksvatvlaskskskyktlfhgfanacdgivslvp---
-kaglkscfqgtksglalg---lgglrpaakeca---ypiillkqivgrn
ciga-e-------gkkfdthrppttv----vcqnlls-----l-nlfcfa
elftftferkrnklavherlekgpwg-phnanveparnndk--rpgftgn
aaqs-saaspdp----tqkimptfrygvgckfglgaarasp--t--fesh
afgllkqsepsgfafaantfqitg-laikysaefvafrissdvgl----t
-hgv--leskpdsirgnsshwthgaffggayep-spksccslmc----gw
tpvgppvvtifpllidggatp------gysihphlrngawyvhgspahga
rkqaegcgaivheafpqlkrss----------kg-hcdqgl-----krds
gdqkgaklclykdalgndniqrpdvifcqvn--qtag-----sv------
---entlhyfyklgdgasydgisf-frltcklddvk-ptehimhdtvpvk
ggsknlfdhdrag----elgivnsgagglqkenl
>ENV_HV2CA/25-512
telanfakv--dptayaaeftgedhdkyrsiykatgeesdaipgesrdct
grpnlaklvpgeslggalk---isaartnlkacf---cmaqkatilvvvp
claq-n-------drnf---pdskts----lcvswkdkcdsvn-trrcyv
--fthmyhrvkpk----qktekapwa-pldarvkpsrfeikqct-afvsa
gadslcvpeerp----aaknnsdywlailcpghqggvqggk--t--fasa
aysamsqekgvnfdfvfetynagk-igvayaggsctfrlptgpnvls--v
itsv--vtytiephvvksil--avtfyaacfag-ggrsscglia----gw
qhlhesev-vaaimdtggngakgqyergelvdsqpatdgwfqhgrkkegt
afpiqgcdap-retfpeirkaavnalredmhtlt-lceqal-----kama
gpkkpdk----kltlgtskvdrpqkifveke--rkgh-----sl------
---appihyldgvgpqveylslnfttpyscdeggmr-playegsdnkaht
igathlfddnrpasvgptldlgydtegdfhkags
>ENV_SIVGB/47-569
hglwvyspv--dpqsvqfnlagvpsqkvaeyfvpgptscayptklht---
-qkvlkqptsaa---lvmdgaplqgakaalagcf---stqyds-------
-niedqgtedaddsqcfstpqpstvvagkdrcrewrsksktayakfpcfy
tiflgllgavsgsvsytgqvehgpfesalagstiaahfety--lngtyqt
hgrr-candmdpskcanttaglgyrlgesckehvqakatei--k--y---
tcgvikaekdtpvtlvaavynqan-lsskf---ftahsvgtkvlavpkam
-kpqplaqakadaeidkeis--aahfhqatydvgsvkascall-------
vrgehd-igvlakkvsggtth------gknvqpthrggqwyalalpgaic
pkeqdacaslperdhhhyscql----------ng-vcasgf-----rle-
---apr--------------ehpkapfitetenhaaagdkgigkemhklk
vlgnecvdtlvnvagknsyesesfqfrkackaendqgeteseqkekhrv-
--kkgvihhmgkk----klktlvsvgtqvgwsdg
>node7
tpvksygkmtlmpqsvatvlpdksksryhpiyhgfsttcdgivglva---
-rddlkasfpgagsglgla---leglrpgekdcf---yaiiilkrivgrn
ciga-e-------gmkfqthssattv----vcpdweskpfnif-glfcfa
elytftyesmrrklavqerlekgpwg-phnsnvdparyqdk--apgfagd
lnns-snsgsep----tgkftptfrvgvgcknhggaaqanp--t--fesn
afdllkqtdatgfdfaadnyqasg-lgkkytgefvafrlpagvslya--i
-ggv--leaktesikgkatqwthgsffggtyev-spksccgllc----gw
epsgphvvailpilidggasd------gqsiqprqrngawyvhgspghgv
rkqangcgaivhaafpqlkrss----------qg-hcnqgl-----kles
gdqkgak----rnelgndkiqrpdtafitkn--rtae-----at------
---dgsvhyldnlgsgasydgisfhfryscaieaik-ptdhimhdtvpvk
agtkhlfdqdrpg----elgivnpgggglekagr
>node14
mevanyakv--epeafaeqlpsddhdkyrsvyigtgdqsdaipgvsreci
grpalsglvpgenlglalk---isgarnhlkpcf---ylalkatilvgvp
clga-n-------nrnf---sdakts----lcvswkdkcdgty-srrcya
--fahmyhrmlpk----ektektpwq-pldsrvkptrfqnkqcapafysa
gadskcvpesrp----kgkynsnywlrilcpghqsgiqggr--t--fasa
ayqsmsqpkgtnfdfvletytags-igvsyaggssslslpsgpnvls--l
itnv--vtytidphveknvq--qatffaa-fag-ggrqccglia----gw
nalhesev-vaainvkggngakgqyergelidsapstdgwfnhgrknett
sfpiqgcgap-resfveikrstilalreeihtls-lceqel-----kala
gpkkpnk----klslgtsnvdrpqklfiqke--rkah-----sl------
---afeihyldavgpqadyldlsfvipyscdaggfk-playigedsnaha
agiahlfddnrpa----tldqgydtegdlqkags
>ENV_HV2D2/24-513
vevsnyeqv--epaafadqlpdnshdkyhavykstpdvpeaipgvgrqci
gspnvsglapghplglavn---vsgaknhlktcf---yesliativvgva
cigc-g-------nrnf---ydlhtt----lcvtwkdkcngiy-arrcis
--vghmyhkmspk----eeiqkgpwl-pldsrvkpsqsqnrqcapaftse
grefkcvpasrp----kgkfgtayslqiicaahqgganhgrqss--yqgt
aydamsqhkatsfdfvleaysagd-igvsfagggvtyrmpsgenmis--v
iknv--vkytivphvekkdq--qatlfaayfag-varkccglla----aw
halgsadv-vaavnvrggtgasglnkkgenvdptpsadgwfshgrkhlai
sfttqgcgvp-pesfpkikrttllarreeihsls-icqqel-----kalg
gpkksnk----klqlctsdlerpekptiekv--kkga-----sl------
---alsvdfldavgpeadyldlkfvtpydcdaggfk-kfah-----kghs
agithlfndnrpa----tldvgyniegdlqkags
>node17
melanyakv--epeafaeqlpgddhdkyrsvykgtgdqsdaipgvsrdci
grpnlsdlvpgenlglalk---isaarnhlkacf---ylalkatilvvvp
clgt-n-------drnf---sdakts----lcvswkdkcdgvy-trrcya
--fahmyhrmkpk----ektekapwa-pldsrvkpsrfqnkqctpafysa
gadskcvpesrp----kgknnsnywlrilcpghqggiqggk--t--fasa
ayqamsqpkgtnfdfvletytagt-igvsyaggsssfrlptgpnvls--v
itsv--vtytiephvekniq--qvtffaaafag-ggrqccglia----gw
hhlhesev-vaainikggngakgqyergelidsapstdgwfnhgrknett
sfpiqgcgap-retfpeirrstilalreeihtlt-lceqel-----kala
gpkkpek----klalgtsdvdrpqklfieke--rkgh-----sl------
---afpihyldavgpqadylslsfvtpyscdaggfk-playvgsdsnaht
agvthlfddnrpasvgptldegydtegdlhkags
>ENV_HV2BE/24-510
mgvanyekv--lpeaftlqlpsddhdkyrtvyigtgeksdaipgvsreck
grpalkglspgenlglalk----sgarihakpcf---ylalkitilsgvp
clga-d-------vrnf---pdaktn----lcvrwkdkcdgty-srqcya
--fdhmyhrmmpk----entektpwq-pldsrgkisafqnkqcapifyta
ganprcmpdgrp----kgkynsnywlrvsspgdqrgiqggr--t--yasa
ayqslcqpkgvqfdfvletigagssigvhnaggrsslslptgpnels--l
ikgv--vtysieprveksve--qatflpq-fag-ggrqccgliallscg-
---hesev-vaainvkggkgskgqyergelidsapvidgwfnhgrknett
afpiqgcgap-kssfvevkastilalrdeihkls-lceqel-----kala
gpnkpnk----kvslgtddvdrpqklfiqks--rkth-----al------
---afdihyldavepqadyldlsivipfscdpgkft-pldycgkdsdaha
agiahlfedsrpa----tldqgtdtegdlqkasc
>ENV_SIVG1/22-522
tpvktygkmslmpqsvitvlsdkiksryhpiyngfstpcdgivgavt---
-reelkaslpgagcgigla---legvqpgekdcf---yaieilrrivgr-
--gs-e-------garfqthtsattv----vcpdwqskpfnif-glfcfg
slyaftyermkrklgvlerletgsag-phntnvdparyadk--ppafagd
lnns-sgsgsep----tgkftptlrvgvgcdnhggaaaanp--t--fvgk
aldllkqtdstgfdfaadsyqasa-lgkkytfefvafrvpagvslya--i
-ngv--ldaktesiqgkatqwthgsffggtyvv-tpksccgllc----gw
epsgshvatllpllipggnsd------gqsiqprqrngawyvhetpghgi
rkqahgcgaivhaafpqlkras----------dgqhcnqgl-----klds
gaqtnak----rnamaddktqrpdetfttks--ktae-----at------
---dgsvhyldnlgsggsydgisfhfrfscalaaik-ptghimhdtvpvk
agvehlfeedrta----elgivnvggggfekagr
>ENV_SIVM1/24-528
ltvsgyakv--eptsladtmptnnhdkyhsayrgtkdpndgvpgvsraci
gevnlkglvpgealglalk---vggtrnhlmncf---ylaliatevvdvp
cled-d-------traf---tdakgt----lcpgwrdksngvy-trrcfa
--fvhmy----------ekaeqapwg-plnsrvrgsryqnkqvaaafyse
ggdskclpgrrp----kgkfkstywlriscpghqggiq----------aa
ayda---------klvlegytagd-vgvkfaghfvnfrtpsgnnits--v
-ahv--itysiepqvetnvq--ratffaaayag-vaqcccgllc----aw
qaldesav-vaetylkggsntkgeyekgqlidptpsangsfiqgsanekt
sfqiqgagdv-qtsvpdakrsm-----qeihalg-lcdeel-----rvla
gprkpnm----klrlgtgdvdrptklftpkg--qkah-----sl------
---appvhfldavgpeagyldlsfvtpysceaggik-playigsdsntis
aglyhlfddnrpv----tyavayqsqgglqkags
>node18
mevanyakv--epeafaeqlpgddhdkyrsvykgtgdqsdaipgvsreci
grpnlsglvpgenlglalk---isgarnhlkacf---ylalkatilvgvp
clga-n-------drnf---sdakts----lcvswkdkcdgvy-trrcya
--fahmyhrmkpk----ektekapwa-pldsrvkpsrfqnkqcapafysa
gadskcvpesrp----kgkynsnywlrilcpghqggiqggr--t--fasa
ayqamsqpkgtnfdfvletytags-igvsyaggsssfrlpsgpnvls--v
itnv--vtytidphveknvq--qatffaaafag-ggrqccglia----gw
nalhesev-vaainikggngakgqyergelidsapstdgwfnhgrknett
sfpiqgcgap-resfpeikrstilalreeihtls-lceqel-----kala
gpkkpnk----klslgtsdvdrpqklfieke--rkgh-----sl------
---afeihyldavgpqadyldlsfvtpyscdaggfk-playigsdsnahs
agithlfddnrpa----tldqgydtegdlqkags
>node10
mevsnyakv--epeafaeqlpgddhdkyhsvykgtsdqsdaipgvsreci
grpnlsglvpgenlglalk---vsgarnhlkacf---ylaliatilvgvp
clga-n-------nrnf---sdaktt----lcvswkdkcngvy-trrcfa
--fahmyhrmkpk----ektekapwa-pldsrvkpsrfqnkqcapafyse
ggdskcvpgsrp----kgkfnsaywlrilcpghqggiqggr--t--fasa
aydamsqhkgtnfdfvletytags-igvsyaggfvnyrlpsgpnvis--v
ianv--vtytidphveknvq--qatffaaafag-varqccglla----aw
naldesev-vaainikggsgakgqyekgelidptpsadgwfnhgrknqtt
sfpiqgcgvp-pesfpeikrstilalreeihtls-lceqel-----kala
gpkkpnk----klslgtsdvdrpeklfieke--rkgh-----sl------
---afsvhfldavgpqadyldlsfvtpyscdaggfk-playigsdsnahs
agithlfddnrpa----tldvgydtegdlqkags
>ENV_HV2G1/23-502
mevsnyakv--epeafaehlpgddhdk---vykgtgdnsdgienvskecl
gkpnlsggvpgenlglalk---isgpknhlkacf---ylamkatiligvp
clga-n-------drnf---pdakti----lcvswkdkcngay-trrcfa
--fahmyhrmkpk----aktekspwd-plnsrvkpsrfqnkqcapafyse
gsdskcfpasrp----kgkynsnvwlsilcpghqsgvqggr--t--fasa
ayqamsqhkgtnfdfaletyaags-igvsyaggsssfrlqfgpnvls--v
itna--vtytidphvnrnvq--qatfsssafag-garmccglia----gw
nalhkcea-atainikggkkakgqyergelidpnastdgwfshgrkkett
sfriqgrgvp-resfpekkratflalrqevhals-lceqel-----kala
gpkkpnk----ksglgasdvdrpqklfieke--rkgn-----sl------
---afqidaldavgpeadfldlsfvttyscdaggfk-playigsdskaha
aaithlfdshrpa----tldagydtegdlqkags
>node8
tavkaygkm--epqptasilpdknksqyhpiyhgfsstcdgivglaa---
-rddlkgaipvegpglgla---leglrsgekgcf---yaaiillrligra
ciga-e-------gmkfethssattv----vcpdwknksdtif-klfcfa
elfahayesmrrkvgvqeklekgpwg-plnsnvdparyqdk--apgfygd
qnns-cnsgsqp----kgkftptyrvgvgckghggtieadp--t--fesn
afdllkqtdatgfdfvvdtyqagg-lgvkytgefiafrlpagvdvia--i
-agv--leaktepiktkdie--hasffaatypv-slraccgllc----gw
eptdnqvvailailidggase------gqsiqprqrngpwyvhgspghsv
rrqndgcgaivqaafpelkrst----------qg-hcdqgl-----klqv
gdqkgak----rlvlgsdeierpdtafitkn--rtae-----ap------
---dgsvhyldsvgpsasyndisfhfryscaiesik-ptdhikndtntvk
pdskhlfdqdapv----elaivypggeglqkags
>ENV_HV2D1/24-501
mevanyakv--epeafaellpsdthdkyqgvyiktgnqs-tipglsreci
grpalsglvtgenlalalk---isgarnhlkpcflpkymalkaailvgvp
clga-n-------nrtf-----akts----lcvswkdkcdgty-srqcya
--fanmyhrmlpk----qktektpwq-pldsrvkptrfqnkqcppgfyta
gadskcvpesrp----kgiynsnywlkilcpghksgiqgdr--t--fasa
ayqtmsqpkgtnfdfvletytags-iglfyaggsgrlplssgpnvls--l
itgv--vsytidphveknvq--qttffga-fag-ggrsccglia----gw
nalhetev-vaaenfkgpngakgqyergelidsapitdgwfnhgqknett
sfpiqgcgap-resfveikrssilalreeihals-nceqelsghlgkplg
gpkkpnk----klnlgvvnvdrpqklfiqke--rkah-----tl------
---afeiyypdavgpqadypdlsfvipyscdagsfk-playvgvdsnaha
agiahl-ndnrpg----tldqgydtegnlqqags
>node19
mevanyakv--epeafaeqlpgddhdkyrsvykgtgdqsdaipgvsreci
grpnlsglvpgenlglalk---isgarnhlkacf---ylalkatilvgvp
clga-n-------drnf---sdaktt----lcvswkdkcdgvy-trrcya
--fahmyhrmkpk----ektekapwa-pldsrvkpsrfqnkqcapafysa
ggdskcvpesrp----kgkynsnywlrilcpghqggiqggr--t--fasa
ayqamsqpkgtnfdfvletytags-igvsyaggsssfrlpsgpnvls--v
itnv--vtytidphveknvq--qatffaaafag-garqccglia----gw
nalhesev-vaainikggngakgqyergelidpapstdgwfnhgrknett
sfpiqgcgap-resfpeikrstilalreeihtls-lceqel-----kala
gpkkpnk----klslgtsdvdrpqklfieke--rkgh-----sl------
---afeihyldavgpqadyldlsfvtpyscdaggfk-playigsdsnahs
agithlfddnrpa----tldqgydtegdlqkags
>node11
mevsnyakv--epeafaeqlpgddhdkyrsvykgtgdqsdaipgvsreci
grpnlsglvpgenlglalk---isgarnhlkacf---ylalkatilvgvp
clga-n-------drnf---sdaktt----lcvswkdkcngvy-trrcfa
--fahmyhrmkpk----ektekapwa-pldsrvkpsrfqnkqcapafyse
ggdskcvpesrp----kgkynsnywlrilcpghqggiqggr--t--fasa
ayqamsqhkgtnfdfvletytags-igvsyaggsasfrlpsgpnvls--v
itnv--vtytidphveknvq--qatffaaafag-garqccglia----gw
nalhesev-vaainikggngakgqyergelidpspstdgwfnhgrknett
sfpiqgcgvp-resfpeikrstilalreeihtls-lceqel-----kala
gpkkpnk----klslgtsdvdrpqklfieke--rkgh-----sl------
---afeihyldavgpqadyldlsfvtpyscdaggfk-playigsdsnahs
agithlfddnrpa----tldqgydtegdlqkags
>node9
msvsgyakv--epesfadqlpddnhdkyhsvyrgtsdpsdgipgvsreci
grpnlkglvpgenlglalk---vsgarnhlmdcf---ylaliatilvgvp
clga-e-------trnf---sdaktt----lcpswkdksngvy-trrcfa
--fahmyhrmkpk----ekaekapwg-pldsrvkpsryqnkqvaaafyse
ggdskclpgsrp----kgkfnstywlritcpghqggiqggr--t--fasa
aydamsqhkgsnfdfvletytagg-vgvsfaggfvnfrlpsgsnvis--v
-anv--vtytidpqvetnvq--qatffaaayag-varsccgllc----aw
qaldesev-vaeiyikggsdakgdyekgqlidptpsadgwfihgsqnqtt
sfqiqgcgtv-qtsfpeikrst-----eeihals-lcdqel-----kvla
gprkpnk----klrlgtgdvdrpeklfieke--qkgh-----sl------
---assvhfldavgpqadyldlsfvtpysceaggik-playigsdsntvs
agithlfddnrpa----tlnvgyqtegdlqkags
