>node11
sslaiacanfgrlfwdgvngfse---itvkislkainmvg--vgmdpags
hs-ag-ydgvkqklydgk-velv---gskgisnaircktveg---akddv
gpgamqa-lvcldtsagakccefvagslnv--lldldgwlcgdklrlyvn
dgfaleqdvdcclyckeynanaf--------gmrigaildegqlqaa---
---ktvn-----vfhaftqqpalpdsthaf-q------lykkksg-ritk
dcllkksyrlfqlafklfffaygckpkwvavfdatncl-vnk----w-fg
llngkfvghgvsrklsgytlledwflkpdkgdwvhykgyqggkrpklpla
isgdtgtngsksqagpirlkpkapkgagahan-tg--lkgfnlcergmdp
diqytehsdskgegpckr----------kpclsltrrqvpgvaaertcei
plaelgsalkvgpayhalaqticgnia----mlcterglasiss----cf
fvfpnqdvrhyecpllsyylgdp----yaaiatsneekrtggqdggavep
q-----lga--snq---mgtitlnnc----iq-------ytlcqgt
>node14
sslaiacadigrlfwdgangfse---itvkislkeismvg--vgmdpags
hs-gg-ydgvkqklydvk-vslv---askgisnaircktvdg---akddv
gpgamqa-lvcldtslgakccefvvgtlnv--lldldgwlcgdklrlyvn
dgfaleqdvncclyckeynadaf--------gmrigvileegqlqaa---
---ktvn-----vfhaftqqpalpdsthaf-q------lykkktg-ritk
dcllkksyrlfqlafklfffaygckpkwvavfdatncl-vnk----w-fg
llngkfvspgvsrklsgytlledwflkpdkgdwvhykgyqggkspklpla
isgdtgtngkksqagpvrlkpkapkgagahan-tg--lrgfnlcvrgmdp
diqyteqsdskgdgpckr----------kpclsltrrqvpggaaertcei
plaelgnalkagpayhalaqticgnia----mlcterglasiss----cf
fefpnqdarhtdcpllsyyvggp----yaaiatsneekrtggqdggavep
q-----lgs--snq---mgtitidnc----iq-------ytlcqgt
>ENV_SIVG1/22-522
gtlhiecrnfvkgfwtsngskgk---lslgnsdaifnvvd--vdfsavgs
nr-ka-wtglkqfph-----qll---drps--tgpwcasvtt---lrtei
apavvrvilmcldknnsdrcfeygagllrtflllalhgwtcagkqqlyah
rpftseqempccllckdyscdgf--------rirvgeyvsevqhkte---
---ktvl-----ilfeyna-ssfqaqkpaf-t------lyqhkqt-kkdk
hcldakayktmtmafkiflfvyacapswdsvyehtlcldsnm----w-lg
yttdkflghgvercktgyvlvdawflaadvnrwahlagytvgtnlssilg
schgagrtnpkpdlnpprfgv-dekttgatakl-------felcelqktp
dkeytnhsatktd-pckr----------kpclmlhkhevcganaqrvlai
eledesaslksgpvyealnqtvsqafassfdhactvkglasvvrliamcf
llftqqavrayacsildgylndg----fgslaaccgnkrigdtstpavde
yhykakhst--tkdgygadtaislvckciyld-------haiipgv
>ENV_HV2CA/25-512
lsmaiacanvgrlkwdgvvgfse---ikvktslkpiniva--igmavsgp
ns-pg-ydvvkqklydgq-velv---sskpssnaircksvdn---akgdv
gpfvkqk-lvcletslgakccefavgslha--llnldgwlcgdrlklfvn
ngfaiqhgvdcclyckdknagaf--------gmrigaildegqlqaa---
---ktvn-----vfhaftpqqalptsthaf-e------lykkksc-rvtk
dcllkkgyrlfqlafklffyaygskplwvavfdatncl-vrk----w-fg
langkfsgsgvsrklsgyttleewflkpdkpnwvqykgyqggkrsklpls
isgetgtggskshagpirlkpkapkgagahep-td--kkghnlcprggap
diqctehadsreegpcpw----------ka-lsltkrqvpgvpaertcei
plvelgselkagpaehcllqtdcgniq----mmcterglvgiss----cf
fifpnqnvkhtecaslsyylsdp----ygaiatsneakrtggqnggavss
k-----lga--snq---laivslnnc----ih-------ytycqgt
>ENV_SIVM1/24-528
sslasqcanfgklfsesvdgfaeyrdinvgirlkaikmigqtvgmapsgs
hs-av-yigvkrkly-----elv---gsdgisslvkckkkeg---ckkqv
sqgalqt-vvcqdtsasskcldfvagglkefilldlegwlcgdklrlyat
agfglkhdvncclrcddyhaegf--------gmrlgqiiddsalqga---
---ktvn-----vlhafseqpaipestqaf-h------lykqkag-ritk
qclarksfrifqlafslfffvygckpkwvavfkpahcl-vni----w-fs
yldgkfvghgpgqklsgytlledwflspdkgqwvhyknydggkrpktkla
isgdtgtsgsksaagpirfqlrapkgagangq-ta--lksfalcdreikp
diqyddhddskgggpckr----------kpvlslasrqvagapaertcel
plaelgaaakvgpayhalasvlceyia----mlctarglaeist----ct
fvfpnqtvwhyecpvlsvylggp----yaaigsageekrtkgqdggavep
r-----lga--srqdvmmgtttinpc----iq-------ytlcqga
>node9
sslanqcanfgrlfwesvdgfse---itvgirlkainmvg--vgmdpsgs
hs-av-yegvkqkly-----elv---gsggisnairckktea---ckdqv
gpgalqi-lvcldtsasakclefiagslnafilldldgwlcgdklrlyvn
dgfalehdvdcclyckeynadgf--------gmrigeildegqlqaa---
---ktvn-----vfhafseqpalpdstpaf-q------lykqkag-ritk
qclakksfrlfqlafklfffvygckpkwvgvfdsancl-vnk----w-fg
yldgkfvghgpnrklsgytlledwflgpdkgnwvhykgydggkrpktkla
isgdtgtsgsksaagpirfqarapkgagahan-ta--lksfnlcergmdp
diqygdhsdskgsgpckr----------kpclslarrqvagvaaertcei
plaelgpalkigpayhalaqtlcenia----mlctarglaeisr----cf
fvfpnqtvrhyecpvlsyylgdp----yaaigttneekrtggqdggavep
q-----lga--srqdfmmgtttlnpc----iq-------ytlcqga
>ENV_HV2D1/24-501
sslaiacadigrlfweaasgysd---ilvkislkeismvg--vgmkpagt
hn-na-ykgvkqklydvkyvglv---gpkgisnacrckivdg---akddv
gpgkmqa-vvcldsslgakccefmvgtlnv--llnldgwlcgdklriyvn
dgfalendvncclsckdynadaf--------gmrpgiileeghletayta
llpkavn-----lfhgltqqpalgdct-----------------d-iitr
ncvlkksyrlfklafklfffaygckpdwiavfdattcl-vsk----w-fg
lntgmyvspgvnrklsgytlleawflkpdkgdwlhykgyqtgkkpqlpla
isgdtgangkkseagpvrlkpkaakgagahpn-tg--lrgfnlcirgmdp
aiqypdqsdssgdgpsrr----------kpclsltriqmpggaaertcei
aladlghelkagpayhalaqticgdia----ilcterslacgsd----cf
fqfpkkearhtdcsllsyyvggp----ysaistsdeekraggqdgpavea
q-----lgs--snq---kgsikidnc----il-------ytlcqdt
>ENV_HV2G1/23-502
aslavacanfgrlfwdgvngfsn---isvktslkainlvg--igmdpags
hs-vg-ydgvkqklykgk-velv---gpkgisnaircqsveg---akdev
npspmqa-lvcldtsagakccefvagsldv--sldldvwlcgdklrlyvn
esfalaqevdcclyckeydanaf--------gmstgaildegplaaq---
---ktvq-----vfgaftqepampdsthsf-q------lykkksg-riak
kgllgksyrlfqlvfklywfaydckptwvavfdatncl-vnk----w-fe
llngklvghgvskkltgytlledwflkpdkgdwvhykgyhggkrpklpla
is-dtgmdgtktqvnpmhlkpkspkgagahan-ss--lkgfnlcergmdp
diqfsehadskgegpckrhgcpaaknatkaclslnrrqvsevaaertcei
pladlgsalkvgeayhalaqticgpia----mlcterglasias----cf
fvfpnqdvvhyecpllsyylgnapatayatiatsneekrtggqngngvep
q-----lga--snt---mgtitlgnc----vq-------ftlcqga
>ENV_HV2NZ/24-502
scilipcanvgrlfwngvngfse---ikvkiklka--------gmdvagp
hs-ag-fegvkqrlyegk-velv---sssrisnaircktven---skddv
gpgvqna-lvcldtglgakccefaignlhv--lldlddwlcgdrlrlyvn
ngfaleqevdcclyckernpgaf--------glrigpildqgqlqas---
---ksvn-----vvhafgpqqalptithaf-q------lykkktg-tink
dcllkksyrlfllafklffyaygskckwvavfeatnsl-vnr----w-fg
lfsgqfvgrgvsrklsgytlleawflkadkgtwvhvkgyqggkrpklpla
isgetgtngsgsqagpirlkpkapkgpgahar-tg--lkgfnlcpreadp
dilctehkdsksegpakr----------tpcvsltkrqvpgvaqertcei
plgelgsalkagplpnclaqticgnfk----mlckerglaaisg----cf
fvfpdqavrhtecpllsyylgkp----ygaiatsnqvkrtggqeggrvdp
d-----lgt--snk---latvglnkc----fq-------ytlcqgt
>node8
gtladecenfvkvfwtsagnfsq---vsignrksvfnlvg--vgmsaaga
nd-ea-wtglkqllh-----ell---grgs--taarcnrvtt---mrdki
cpgvvrv-lvcldtnssarcfefdagllktflllalngwvcsgklrlysn
rpftleqemaccllckdftcdgf--------smrigeslnellnkna---
---ktvl-----ifyefndrasvqarrpgf-p------lyqhkea-kkdk
qcfdskayktmkmefklfffvygcqpswasvfdhalcldvdk----w-lg
ylndkflahgvdrsktgyvlvdawflgadvnrwshfkgytggtnlssilg
vcgaagntdpksalppprfdvrdekttgafaklmq--lksfklcekgknp
dveygdhsstkna-pckc----------kpclmlnkrevggadiermppi
aleddppalkrgpvyealnqtvaqniaaafehactakglasivr----cf
llftqqaaraydcsildgylnda----ygglgtccgnkriggrngsavde
hhykathsa--akegfaadtaillvc----ln-------ytiipgv
>node17
sslaiacanvgrlfwdgvngfse---ikvkislkainmvg--vgmdvagp
hs-ag-ydgvkqklydgk-velv---sskpisnaircktvdn---akddv
gpgvmqa-lvcldtslgakccefavgslhv--lldldgwlcgdrlrlyvn
dgfaleqdvdcclyckeknagaf--------gmrigaildegqlqaa---
---ktvn-----vfhaftpqqalptsthaf-q------lykkktg-ritk
dcllkksyrlfqlafklffyaygskpkwvavfdatncl-vnk----w-fg
llngkfvghgvsrklsgytlleewflkpdkgdwvhykgyqggkrpklpla
isgetgtngsksqagpirlkpkapkgagahar-tg--lkgfnlcprgadp
diqctehadskgegpckr----------kpclsltrrqvpgvaaertcei
plaelgsalkagpaehclaqticgnia----mlcterglagiss----cf
fifpnqevrhtecpllsyylgdp----ygaiatsneekrtggqdggavdp
q-----lga--snq---mgtvslnnc----iq-------ytlcqgt
>node10
sslaiacanfgrlfwegvngfse---itvkislkainmvg--vgmdpngs
hs-ag-ydgvkqklydgk-velv---gskgisnaircktveg---akddv
gpgalqi-lvcldtsasakchefvagsldv--lldldgwlcgdklrlyvn
dgfaleqdvdcclyckeynanaf--------gmrigaildegqlqaa---
---ktvn-----vfhafsqqpalpdsthaf-q------lykkksg-ritk
qcllkksyrlfqlafklfffaygckpkwvavfdttncl-vnk----w-fg
lldgkfvghgvsrklsgytlledwflkpdkgnwvhykgyqggkrpklkla
isgdtgtngsksqagpirfqakapkgagahan-tg--lksfnlcergmdp
diqygehsdskgsgpckr----------kpclslarrqvpgvaaertcei
plaelgsalkvgpayhalaqtlcgnia----mlctarglasisr----cf
yvfpnqdvrhyecpllsyylgdp----yaaigtsneekrtggqdggavep
q-----lga--srqdfmmgtitlnnc----iq-------ytlcqgt
>ENV_SIVGB/47-569
nvmtlq-dl--hllwkngcnvkv---tctdekr-llrlks--lsvg----
gnkdg-ateprqlla-----dllvnggtap--aadkcksdnt---vkhrt
cakvlke-lvadatdtk---yglfssi-ttllildltknlcqlalplf--
--qeepeeagcgllcsqkvcegfmlqnveltftrvgeaaedvlsrqm---
---nith-----ilfqgticksleaklpdc-v------lyrytkdyrklq
prlaaieyktmqpevvmtglvfhcysngrknigh-----vqtcqairvvv
alagkflnqvhssmkggyilpndwflnmkadrwakfpesdgghslayigi
rgesaetdeekanlpqphidgsgeatsclfvrvlt--isclvhcskqdsd
aihfsgngkavks-aerc----------ascetlvnhsaeryevvkrppi
gli--lqslskapl-waltrtv-lncgqefdqtcdgkglhsvmk----yt
mffkanhgqgyvyaki-------------mfgtcptllafgntdkksfdv
tgykraepevmdtagqgpagalwkvc----lknayvenpfkraqav
>node18
sslaiacanigrlfwdgvngfse---itvkislkainmvg--vgmdpags
hs-ag-ydgvkqklydgk-velv---sskgisnaircktvdg---akddv
gpgamqa-lvcldtslgakccefvvgslnv--lldldgwlcgdklrlyvn
dgfaleqdvdcclyckeynadaf--------gmrigaildegqlqaa---
---ktvn-----vfhaftqqpalpdsthaf-q------lykkktg-ritk
dcllkksyrlfqlafklfffaygckpkwvavfdatncl-vnk----w-fg
llngkfvghgvsrklsgytlledwflkpdkgdwvhykgyqggkrpklpla
isgdtgtngsksqagpirlkpkapkgagahan-tg--lkgfnlcergmdp
diqytehsdskgegpckr----------kpclsltrrqvpgvaaertcei
plaelgsalkagpayhalaqticgnia----mlcterglasiss----cf
fvfpnqdvrhtecpllsyylgdp----yaaiatsneekrtggqdggavep
q-----lga--snq---mgtitlnnc----iq-------ytlcqgt
>node7
gtlhaecrnfvkvfwtssgskst---lsignsdsvfnlvd--vgfsaags
na-ka-wtglkqlph-----ell---grgs--tgprcnsvtt---mrtei
cpgvvrvilmcldknnsdrcfeydagllktfllltlhgwtcagkqrlyad
rpftleqdmaccllckdytcdgf--------sirigeyvsqiqhknd---
---ktvl-----ifyeynarasvqaqkpaf-t------lyqhkqa-kkdk
hcldskayktmsmefkifffvyacapswasifehalcldadm----w-lg
ylnekflahgvdrsktgyvlvdawflaadvnrwahlkgytvgtnlssilg
lchsagstnpkadlnpprfdvrdekttgataklmr--lkdfelcekgknp
dkeygnhsstkkd-pckc----------kpclmlhkqevgganaervpai
aledepaalkrnpvyealnqtvsqnfassfdhactakglasivr----cf
llftqqagraydcnildgylnda----ygslgaccgnkrigesstpavde
yhykathsa--tkdgygadtaislvckaiyln-------haiipgv
>ENV_HV2D2/24-513
hylatycanfgrgfwqgsngfne---itvkdpeksalmlg--vgmecsga
hl-vggydggkqelydgk-velv---nskgisaairckkvhg---gkddv
gpeelqi-lvcldtktcskchdfidgsldv--mldsvgwlcgdklrqsan
dglsleqdiacclfcgeynanaf--------gmrigakldqgklqss---
---dikg-----ifhafshhpalpdvtnaf-q------lfakkss-----
qcllrktyklyqpafksfffaysvkpkwvamfdtkncl-vak----w-fg
llngkfvghgvsrkvegyatleewflkpdkadwvhckgyqggkrpkfkla
vssengangskgqsgpvsfqakapmgagphtn-as--lkkfnlcdrgmdp
dvqygehpqtkgtgpcks----------kaclalarrqvpgvsahsscqi
plaelgsalkvalayhalsqtlcgnia----mlctqrklagitd----cf
cafpnlavrhyecpllsyylvep----yasigtgdheqktggqdggavep
q-----lga--hkqdfmmgtvtlnyc----iq-------ytlcdgt
>ENV_HV2BE/24-510
sslaigcakigrlfwdgasgfse---iavkiglrelsmig--vgmqpags
hs-sg-yegakqklydvk-vslv---askaisnaircktcdg---aaniv
ghgamqa-lvcldtsqgakccefivgvlnv--lldldgwlcgdklrlyvs
dsfqlgqdvncclyckeynseif--------vmrigvaaeqghtqda---
---ktvt-----vfharthqpalpdnthafkd------lyknktg-ritk
qcllkkpyrlfelafklfffaygckdkwvdvfdat--l-vnk----w-fg
llngkfvsasvtkelsgytllddwflkpdkggwghysgyqggkspklpla
vsgdtgtdkkksqaaqvrlkpkapkgseaptn-tg--lrgfnlcvrgmdp
digcdessdskgdgnckr----------kppislsrrqtpggasdrtcei
plaelgnalnagpayhslgqticgnsa----vlcterglasisg----cf
fefpkqdtrhtdcpllayyiagp----faaigssgeerriggedggavep
h-----lgs--sdq---mgtitidkc----iq-------nalcqgt
>ENV_SIVV1/24-538
gtlhaacltgagmfwassgsktt---lsmghwesalslvs--vkaaakas
qa-ka-wtglkqlpn-----dil---grgt--tctntnqvavesnmrtdi
cpavlrviaicvksnnsercfe---gllkdyvllllhgftcagkqrlnap
rpfdlemeqvccalctdytsgnf--------sirigeyvrqvehkha---
---ntmlkvdshiyyeysarpsslsqkppf-igaqevvlhdqkqi-kndq
hcldskafntmhmelnvfffgyacapswasifdhalcldkda----w-lg
ylderflehsvarskssfilvdawflahevnrwahlteytvgsslcsavg
lclsagganpknelaaprfdvrpeksrgnsaklmrkflsefelcektknp
dkeygnfsatkkd-pckv----------rpclmlhqeeigeqkkertvsi
aledkpaelkkn---salarsirqsfaqnfdqsctadglksllr----yf
lqfarmggrkfecnnlggylsda----fspmgdccgknrigeggtptpde
yhynathga--skdglgkdthlklccsp---d-------hsivpgq
>node19
sslaiacanfgrlfwdgvngfse---itvkislkainmvg--vgmdpags
hs-ag-ydgvkqklydgk-velv---sskgisnaircktvdg---akddv
gpgamqa-lvcldtsagakccefvvgslnv--lldldgwlcgdklrlyvn
dgfaleqdvdcclyckeynanaf--------gmrigaildegqlqaa---
---ktvn-----vfhaftqqpalpdsthaf-q------lykkktg-ritk
dcllkksyrlfqlafklfffaygckpkwvavfdatncl-vnk----w-fg
llngkfvghgvsrklsgytlledwflkpdkgdwvhykgyqggkrpklpla
isgdtgtngsksqagpirlkpkapkgagahan-tg--lkgfnlcergmdp
diqytehsdskgegpckr----------kpclsltrrqvpgvaaertcei
plaelgsalkagpayhalaqticgnia----mlcterglasiss----cf
fvfpnqdvrhtecpllsyylgdp----yaaiatsneekrtggqdggavep
q-----lga--snq---mgtitlnnc----iq-------ytlcqgt
