>node17
fqyhncaklmccsplyvgptrqgqlvcarqlslgklttidlcestmwkgt
kckaklgfagpsvvyvknss-sacl----se--gkekqckkgkg-ksg--
-----lvkgyltskivvpsetaamaqdatlnfrpigstgfkvekvvkmis
-g------as-p------agaagtvlrrg------kgfggcse--vt--f
mfvg--cdimlhlldgvvclkqgtyl-r--rkth-kalrdefgkanacga
gs-e-klknkvellwskvahdfmqgvettv-llgtgcgeggfdnrecgvg
ps-grggpgtnvlvgavrfcvtlgtnegykvlpkpdwsqkalrgk-hcgf
-tlwkveidakhvdktlpsgsrkapkklatcs-----p-----trdvlia
vqvrptvdglpveasqsa--keteaignlgpkagskidncpvevqwldss
qanahfsdppkignhdvkvmsek--sgkeegykiegl---qgsprdilsc
fvsyi--kamamcyqgfdekrakrahpqpcyd-c-gadhgpttr-vnvaa
vasgyerreivnriitlirfftdnngatkntwmk
>ENV_HV2G1/23-502
yqynncakltcchplyvgparqedltcgqqlslgklktidlcestmwpgt
kckeelgfggpgvkyvknes-sacl----sn--gkekqcrkgkg-gsg--
-----lvkgllasktvvpretapmaqdatlgfrpigctdfkvekvvkmin
-g------as-p------sgaagavlrrg------dgfgkcse--vt--f
mfvg--cdimlalvgsvvcmkqgtyl-r--rkth-kapkdefgradtcga
gs-e-klknkvdllwdkvyrdfmqgvettv-ilgtgcgeggfdnnecgvg
ps-grgnpstavlpgavrfcvnlgfnegykvkpkpdwvqkavrgk-hcgf
-tlwkveidakhvdktlpsgsrkapkklpncs-----p-----trdvlia
vqiiptvdglpvdasqfa--kekeaigllgpkaiskidncpvevqwldss
qvnahfsdppkvgthevkvlsek--sgketgyivegl---dgsprdilss
fvsyi--savamcyqgfde-----------yn-c-gashgpttr-vslaa
vasgyekreivnsiiplirfftdsngrninkwms
>node19
yqyhncaklmccsplyvgptrqgqlvcaqqlslgklttidlcestmwpgt
kckgelgfagpsvvyvknss-sacl----se--gkekqckkgkg-ssg--
-----lvkglltskivvpsetaamaqdatlgfrpigstgfkvekvvkmis
-g------as-p------agaagtvlrrg------kgfggcse--vt--f
mfvg--cdimlhlldgvvcmkqgtyl-r--rkth-kalrdefgkanacga
gs-e-klknkvellwnkvahdfmqgvettv-llgtgcgeggfdnrecgvg
ps-grggpgtnvlpgavrfcvnlginegykvkpkpdwsqkavrgk-hcgf
-tlwkveidakhvdktlpsgsrkapkklatcs-----p-----trdvlia
vqviptvdglpvdasqsa--keteaignlgpkaaskidncpvevqwldss
qvnahfsdppkignhdvkvmsek--sgkeegykvegl---dgsprdilss
fvsyi--kamamcyqgfde-----------yd-c-gadhgpttr-vnvaa
vasgyekreivnriitlirfftdsngatintwms
>ENV_SIVGB/47-569
ldfhephyyqccaaletpakgk-dtcrpmlcsppellcvvgctqghwlds
lcpggggleapsqsfpkkvk-ghklvsvfnhedadawqcdkmlafaqedp
nvclalsk----------------tkentea-kcvgshtvakgsp--vak
ys------ynmd------ssnrgclltte------iegaacah--vi---
------hltwqeagpcdtctntfcli-khqr-----------------pv
phyvglsainewsnwikvnh-------ntv-dlldpccmckfpdqgklie
dp-araapaqkaivafthfcfalpttnafraalvakwckllnqmg-hcqi
-itlkvhahcvwtereigtavqpas-----sgakhpgskdpqsvvmvffd
lygirhpgdv-n-aypeslid-tqtpektqhqssdglifcgvdc------
-ckgssaekplagshgkavgant--vtlssncldigtpfrkvkknaygqv
ifayklvl---------gn-----------sarvvlagdnkvda-phvkv
atggfgsgdl---vkglikiyqagpinaenkykv
>node14
yqyhncaklmccsplyvgptrqgqlvcaqqlslgklaainhcestmwpgi
kckgklgfggptvvyvknss-sacl----se--gkekqckkgkg-ssg--
-----lvkglltskivvpsetatmaqdatlgfrpigstgfkvekvvkmis
-g------as-p------agaagtvlrrg------kgfggcpe--vt--f
mfvg--cdemlhlldgvvcmkqgtyl-r--rkth-kalrddfgkanacga
gs-e-klknkvellwntvahdfmqgvettv-llgtgcgeggfdkrecgvs
ps-grggpgthvlpgavrfcvnlginegykvkpkpdwsqkavrgk-hcgf
-tlwkveidakhvdktlpsgsrkapkklatcs-----p-----trdvlia
vqviptvsglpvdasqsa--keteaignlgpmaaskiencpvevqwldss
qanahftdppkignhdhkvmsek--sgkeegykiegl---qgsprdilss
fvsyi--kamamcyqgfde-----------yd-c-gadhgpttr-vniaa
vasgfkkreivnriitlirfftdnngatkntwms
>node7
fevhdcqyllccsspygndctkgavccailvstseyasvvicesllwsns
rstdeegltgigmvfikdsn-gmsv----ph--adaiectkqlvlete--
-----lgk----------------aenkalg-kcvggkafnpepc--mvv
-l------tt-e---------lapllqke------gsfgacae--it--k
mhvh--chvfhkllagpacpargtyl-raeq-----------------rm
ar-v-siadkvdlgwhrfah-------lsv-dwdngcgegafqsrengve
se-gktgpgfhvvhgtsqfcvkfhanqgyeqgsgpywkqkavrep-hcai
-alaqvrfehssisttlgsairsnp-----as-----p-----vtdvfiv
aegvpkvgdlpi-aypeaffkatgkvgfagpqhadqcdycatqa------
-shkqfgshpytdlhnysnksqk--dklqlacndgta---aakpreiqsl
kfnkd--kqvskcpggffq-----------yv-c-gsgdgpttr-lnvgi
iianygkdds---ivtmikfyesgqvttsipwmv
>node18
yqyhncaklmccsplyvgptrqgqlvcaqqlslgklttidlcestmwpgt
kckgklgfagpsvvyvknss-sacl----se--gkekqckkgkg-ssg--
-----lvkglltskivvpsetaamaqdatlnfrpigstgfkvekvvkmis
-g------as-p------agaagtvlrrg------kgfggcse--vt--f
mfvg--cdimlhlldgvvcmkqgtyl-r--rkth-kalrdefgkanacga
gs-e-klknkvellwnkvahdfmqgvettv-llgtgcgeggfdnrecgvg
ps-grggpgtnvlpgavrfcvnlginegykvkpkpdwsqkavrgk-hcgf
-tlwkveidakhvdktlpsgsrkapkklatcs-----p-----trdvlia
vqviptvdglpvdasqsa--keteaignlgpkaaskidncpvevqwldss
qanahfsdppkignhdvkvmsek--sgkeegykiegl---qgsprdilss
fvsyi--kamamcyqgfde-----------yd-c-gadhgpttr-vnvaa
vasgyekreivnriitlirfftdnngatkntwms
>ENV_HV2D2/24-513
ydfhncvklsccsplyggfnrqgdiacvqalslgklpsiaicestlwpgt
nckgqlgeagptliyvkdss-sncl----td--gkpkqckkgks-gsg--
-----avaglltskivaptdtaamsdaaklgfrgtgstdfsvnkvvnqis
-g------gs-p------agavgtvlekg------kgfdgcsdsgvt--e
mfvg--ceialhllegvlcvmkgtylak--rkth-kslknafgkanacgt
ga-d-klknkvdlfwvkvadefmrdidttvlilgaacggggyknrgcgig
psggqgvegtnvlplgtrycvplgveksnavkhkpdwtqkpvrak-hcgf
-tlwnididgtqvdktlpngvrkvpkklttva-----p-----trdvlil
vqvipkvgglpvnalssn--sdpeasgevg----nkidncpvenqwldss
qgnahfqgppkighhdvriksektrsgkntgchagdl---dgsprdifts
fltyh--ksvelcyegfge-----------yd-v-mgdhgpttl-vsvaa
vvsaykkvqp---ictliriftnsnganvvkwqs
>node8
feyhecryllccrslygedcrkgevccavlvstsdyacvvvcesllwset
rctgeegltglslifikdsn-smsl----ph--adaiectrqlvlnqe--
-----lgk----------------aensalg-kcvggktfgpeac--miv
-v------tt-e------agtlgtllqke------gsfgacae--it--k
mhvq--cnvfhqllagpacpargayl-rseh-----------------rm
ar-v-siadkvdlgwhriah-------lpv-dldngcgesafasrengve
pa-gkagpgshvvpgnsqfcvnfhanegykqgsmpywkqkavrek-hcai
-alaqvhfqcssvettlgsairrnh-----as-----p-----asdvfia
aegvpkvgdlpi-ayaealfkatgkvgkagaqqadhidycpaqa------
-chaqfsshpitnlhnysnktqk--sklqlgcldgta---ngrprdiqsl
rfsyt--kqismcslgfvq-----------yi-c-gagdgpttr-ldvas
vaanygkdda---ivtmikfyengqittsipwmv
>ENV_HV2NZ/24-502
fqyhncasllccsplyigptrqgdlvcgrrlslgklapielcegtmwkgt
ackprlgfagpelvyvkaas-sscl----se--gkdkqpkkgng-kgg--
-----qvkgyltakivvpaetaamaqdaainfrsigsagfkvekvvkvis
-g------as-p------ageaatvlrrg------kgfggcse--vt--f
gfvgyscdfmlrlldgvvclkqgtyl-r--hkttpkaqkaafgkanacgg
gs-e-klsskveliwskvahdfmqgvqttv-llgtgcgeggydsrecgcg
ps-arggpgtpvlvaavrfcvtlgskegyktlpkpnwsqkalrgkqhcgf
vtlntveidaqpvdrtlssgsrkapkkvatcs-----p-----trdalis
vqvrptvdglpaeafqsa--ketekstnlppkagskdddcpvevqwldas
qqtahfsdppkigghdaktmsqs--sgkedgykiegl---qgaprdilkc
fvtyi--kamamcypgfderrtkrahpqpcyd-c-gadhgettravnvga
vtsgyerrenlnrvitlvrfftdnnnstknarmk
>node10
yqyhnctklmccsplyvgptrqgdlvcaqqlslgklttiavcestmwpgt
kckgelgfagpsviyvkdss-sacl----se--gkekqckkgks-gsg--
-----lvkglltskivvpaetaamaedatlgfrpigstdfkvekvvnmis
-g------as-p------vgaagtvlrrg------kgfggcse--it--i
mfvg--ceimlhlldgvvcmmkgtyl-r--rkth-kalknefgkanacge
gs-d-klknkvelfwnkvahdfmqgldttv-ilgtgcgeggfdnrecgvg
ps-grggpgtnvlpgatrfcvnlginegykvkpkpdwsqkavrgk-hcgf
-tlwkveidgkhvdktlpsgsrkapkklatvs-----p-----trdvlia
vqvipkvgglpvdaspsa--keteaignlgpkaaskidncpvevqwldss
qvnahfsdppkignhdvkvmsek--sgketgclaggl---dgsprdilts
flsyi--kavamcyegfde-----------yd-c-gadhgpttr-vnvaa
vasgydkrea---iitlirfftdsngatvnkwms
>ENV_HV2D1/24-501
yqyhncprlmccsplylgptrqgqvvcaqqlslgklavinhcestmwkgi
kckgklgfgkptvvyvkass-sacl----sn--gkdkkckkgkg-nsg--
-----likgtlhskvvvpsdsatmaqdatlgfrpiaptgfkaeknvkmis
-g------as-p------lgaagtvlrkg------kgfggcpe--vt--f
mfvg--cdemlhlldsvvcmnqgtyl-r--kkth-kalrddfgkasacgs
gs-s-klknkiellwntvahdfmqgvettv-llgtgcgdggfdfrecgvs
ps-gkggpvtpvfhgavrfcvnlginegykvkpkpdwaekavrgk-hcgf
-tlwkvetdaksvdktlgsgsrkapkklakcg-----e-----trdvlia
vqviasvsglpvdisqst--keteaignlgpmaagtiencpvevqwldss
lanlqfaappkignhnhrvmsea--sgkesgykidcl---lgsprdilss
yvtyi--kamamcyqvfeq-----------yd-c-gadhgpttr-vniaa
vingfkereevgrtitlirfftdnngaskgtwms
>ENV_HV2CA/25-512
feylncadlmccsplyvgptrqgrlvcarqlslgelgtidlcestmwkgt
eckaklgfvgpsqvyvknad-sacf----sd--gkekqc------sgg--
-----lakgyllsktvtdsetealaqdvtlkfrpigstggkvekviklis
-g------aa-p------agsagtvlrrg------kgfggcse--atfcf
mfvg--cdimvhlldgvvclkhgtyt-r--rksh-ktlrgefgnanacgg
gs-e-rlsanveilwsrvahdfmqgvettv-llstgcgeggfskkncgvk
ps-grggpgtnvlvgavrfcvslgtnegykalpkpdwsqkavrgk-hcgf
-tmwkvevdakqvdrtvptgsrkapkrlatcs-----p-----trdvlva
vkvratvdglrseagqsa--ketsatgdrgpkagskindcpvevqrldsn
qknahfsdppkignqqvkvvsen--sgaevsfkiegl---qgsprdilsc
fvtyc--spmsmcyqgldekrakhahpqpsyn-c-gadhgtttr-vnlaa
vesgyekrevvnriirlirfftdhnsatkntwlk
>ENV_SIVM1/24-528
yehhdcrklmccdplygvpckqgdlvcaqqldltklasvelcestlwpga
scagelgfagssiihvkdss-savl----re--gtsqdcdqsms-gag--
-----fvkglltskigvpaettsqaedaalgfrpkgstdfkiksivnmis
-g------ps-p------vgaagtvlkrqrictgn---ggsaq--vh--i
mfvg--ceimlnvldggncmmkgtym-k--r-----------------ag
ea-d-klknivelfwarvahaylqsldtdi-ilgagcaeggfdtrdcdvg
pg-gkggpgqnvlpgntrfcigfnvnegnkvkpkpewtqkdvrgt-ecgl
-tlrkdkidgkqvdktlpdgskkapkslttvs-----p-----trevvla
ilvipkinglpvdatpsa--keteaisalgakalskvdhctvgv------
-vndhyssqpiianhdvtlmsek--sgqdggclagal---qgdrrdvltl
flcyi--kgvamcynafdq-----------yd-c-gadqgptsr-lnasa
vasgndkvea---lvtliryfaesngagankwms
>ENV_SIVV1/24-538
feanschyllccsrpygndcarglicaeilvsitefacvvitpsllwnss
rptgvealtgigmvsikesn-gmsl----pq--anatecskqlvvete--
-----lhn----------------gkseklg-kcvggkkfepdpc--lvv
-vssvffnst-e---------lepllqrd------gsgaayae--ik--k
lhan--ctvfhkllggpacpgrgtyl-raep-----------------rv
dr-l-sirnkveldwnrfgh-------lpi-kweercsegasqawetgve
se-gktkpafhvlnsanqfclkfvakqgfqhgsgdywkqkaarkp-hcay
-ilgqvrtvqssikttlgsai---l-----ts------------qdvlvv
tlsvpkvgdlpi-nvpdiffkatakvgfgapenvdecdhcstqn------
-aqklfgsneyteyhhyankkgk--ekvqlacsdgtg---tarsheipsq
hftkp--kqgigcgggffq-----------yi-c-gnsgiplar-lnvgp
givnfgkena---vqtlittyesgqdaagipwma
>node11
yqyhncaklmccsplyvgptrqgdlvcaqqlslgklttidlcestmwpgt
kckgelgfagpsvvyvknss-sacl----se--gkekqckkgkg-gsg--
-----lvkglltskivvpsetaamaqdatlgfrpigstdfkvekvvkmis
-g------as-p------agaagtvlrrg------kgfggcse--vt--f
mfvg--cdimlhlldgvvcmkqgtyl-r--rkth-kalrdefgkanacga
gs-e-klknkvellwnkvahdfmqgvettv-ilgtgcgeggfdnrecgvg
ps-grggpgtnvlpgavrfcvnlginegykvkpkpdwsqkavrgk-hcgf
-tlwkveidakhvdktlpsgsrkapkklatcs-----p-----trdvlia
vqviptvdglpvdasqsa--keteaignlgpkaaskidncpvevqwldss
qvnahfsdppkignhdvkvmsek--sgkeegylvegl---dgsprdilss
fvsyi--kavamcyqgfde-----------yd-c-gadhgpttr-vnvaa
vasgyekreivnriitlirfftdsngatinkwms
>node9
yeyhdcrklmccsplygdpcrqgdlvcaqqlslsklatvvvcestlwpgt
kcagelgfagtsiihvkdss-sacl----se--gkerdckkgms-gag--
-----lvkglltskiavpaetasmaedaslgfrpigstdfkiesvvnmis
-g------as-p------vgaagtvlrrq------kgfggcse--vt--i
mfvg--ceimlnlldgvvcmmkgtyl-r--r-----------------ge
es-d-klknrvelfwnrvahaflqgldtnv-ilgtgcgeggfdnrecgvg
ps-gkggpgtnvlpgntrfcvnfninegykvkpkpdwtqkavrgk-ecgf
-tlwkveidgkqvdktlpsgsrkapkslatvs-----p-----trdvlia
vqvipkigglpvdaspsa--keteaiaalgakaaskidncpvgv------
-vnahfssppiisnhnvtlmsek--sgkdggclagsl---qgeprdilts
flsyv--kgvamcyeafdq-----------yd-c-gadhgpttr-lnvaa
vasgydkrea---ivtlirffadsngatankwms
>ENV_HV2BE/24-510
yqyhhcaklmccsplyagatrqgqlvclqelslgklaavnacestmwpgi
kckaklgfsgptvvyvhnnn-hacl----pe--gkeqqckkgkg-kag--
-----lvkglltgsialvsetatmpadatmglrpigstgfkvekvvimis
-g------as-qrlvtffagqagtvlrhg------kgfggcpq--it--f
mfvg--cdemlrlldgvvcgkqgtyl-r--rkth-kalkddfgnanpcga
ss-e-klknnvellwnkvahnfmqdvgttv-flgtgcgeggfdkrqcgvs
ps-grggpgphvlpgqvsfcvnlgindgqkvkfkpdwsqksvrnk-hcgf
-tlwkvevdtkhvpktlhsgsrkppkklagcs-----h-----trdvpia
vqvipttsdlpveasqss--ketegignlgpmadskiencpvevqwldes
qknghftdppkignhehkvmsek--sgkeagykiegl---qgsprdilra
fvsyi--kamamcyqglde-----------yd-c-gadhgpttr-vhisv
vasgfkkrevansiislirfftdnnggtkntwms
>ENV_SIVG1/22-522
fevhdcqyllccsspylhdctkgsvcsavlvssseyasvyicetllwans
rstdeegltgigmpfikdrsdgmnv----ph--cdaiectkqkvlete--
-----vgk----------------aenkalg-kcvggkafneepc--mvm
-l------tl-e---------lapllqke------ggfaaca-------k
vhvh--cqvfhkllagpacpatgtyl-qsep-----------------rm
ar-v-svadkidlgwhmfvh-------lnv-ewengcgegafnsrangvd
cq-gktepgfhvvhgtsqfcvkfdasqgyqqgsgpywkqkaghep-hcpi
-alasvklenpsfsttlgtdiqsnp-----ae-----p-----vtdvfvv
aqavpkaddlpi-aypdsffkvtgsstfagpghsdqcdycakhv------
-stnqftnhqfndlhnnsnksqk--dkmqlacndgtq---aatprqiqsl
kfnkd--kqgskvpggfsq-----------yv-c-gsgdsptsr-lnvgi
iianygkqdk---ivtmikfyekghvavsipwiv
