>node19
cvegesrlrdvas-ahsral-----cdynasservkdcstacfavkyfdp
vgdkirdltkvahleavlkqaigkwrrflnttywhnepmnglrmmfkqad
ictcc-----aigacypyl-qalpktdggcgkyccnnervpfidhga--t
iqssgndvtlpsagsmgstgmlyrdaamlddvtrfmfrsssvmk-----e
gatpgkevkpnsalgtlnahnmnvggdph---qcadydpydghppdnvag
reknqclhkaqsngpefesecldrkdgcispvalgaipynghycvkgkgq
flvvdelscc-sah-tcqkadvkgdsldlddalv----vkhaglf-apay
relklhi-----qqhpyakytantiavgle----g--lfslypldshvcr
fev-isgqtcyaegaer----gmapeqhvylam-gdddllglhrkvkd--
arivgpgmtlkdsg--islhggqngaakatpplfpelanle-esrcgftl
--iqpgkgka-fil---afka--qiheltd---ltkaknelsrlst--sg
nnelsntkysesra
>ENV_HV2G1/23-502
caegearlhnvas-ahnrnl-----cnynasaervkdcstacfavkyfep
vgdkirdlakvahleavlkhgigkwarflnttywhnepmnglrmmfkdad
ictcc-----aigacypyl-qalpktdggygryccnndpvpfidhga--t
iessgnhctvpsassmgscgmlyrdnamlddvtrfmfkdssimk-----e
gstadkevkpnsafgplnihnmnvggdph---hcadydpydghkgdlvag
rekhqclhkeqsnkpeyeaecldrqegcirppalgaipytghyclkgkgk
favvdeiscc-sah-tcqkaeikgdslildealvvlgnvkhggly-apvy
relrlhi-----qqhhyakykantiavgle----g--efslfaldshvcr
fem-isgqtcfaggaer----gmypqqhvylal-sdddflglhrsvkd--
arivgpgmtskesg--inlhggqngaakgtpplfpelaglk-esrcgfal
--iqpgkgkd-yil---afka--qtheftd---lalaknplsrlst--sg
ntelsntkyseska
>ENV_SIVV1/24-538
sptnhaktlagngdeepyal-----ahlnaknhratgcstycfvskklst
dvkkvkdvlrsdnmakiwlqtegrwprllndfywrespktkfrlmyrkkg
pcecg-----spqesyrflcdpaatkdgkcelecclagpapfnergttak
nekkteeatltphgvlgsssllyk--pygeaatifvrkvgalse-----q
vsnpakqvrdhryllqlrghtlngkdgtn---kcqeahpfdghtsqevta
kdytnhlqkgpgklpgsdsevlekpspnvgpltegaapyvthfcwtsrgs
ygivedegcc-esr-acpkhegdqgvldlddyla----aipapiy---qy
rekrnht-----mqhkreklspkahavdkhdfpvnvalf-gflaqtevcr
fla-gtdhpyysagvap----gitqsahvkakaapgesltgnhvylkhdl
arvvdadrtkfrng--lllhqgqygitgaranmlqattslg-atdcafet
vqvngerdkt-ydr---rfgd--ltngvqg---aartkppmanqgv--sc
kevlqdsrynetld
>ENV_SIVM1/24-528
ctdgesrlrgkas-alsral-----cdfkerrelvkdcpaacfavqyfdp
anttirevtrvahleillkqavgnwrrflnevywhkppmdkfrmmfkqae
ictcc-----aigacyqfl-gaapetdggcgkncchgdrvpfidhga--t
ihgsgndvtlpaagpmgskgmlyrdaamleeitrfifrthsvkq-----d
gatnnqevkpnsalgtlsvnemsvgsdphgshqcadydpfdghp-envag
rdnaqcleraeaegpafgaeel-kkkgcitpleaggapyngayctdskge
favaddlscc-cah-pcvmanvngdgldlddalv----ikhaalflipqy
rdlglvi-----hqgayprytastlnvalq----g--lfslyaleslvcq
fev-itgqscysegaer----gmaptkhislam-sdesliglhkklks--
arilgpgmspkdsg--islhgsqnagpkappslfpmktnls-dshcgftl
--vhpgkgka-yil---lfka--qthsiad---ltkaknnitrfss--tg
qnelsktkynesrn
>node11
cvegesrlrdvas-ahsral-----cdynasservkdcstacfavkyfdp
vgdkirdltkvahleavlkqaigkwrrflnttywhnepmnglrmmfkqad
ictcc-----aigacypyl-qalpktdggcgkyccnndrvpfidhga--t
iqssgndvtlpsagsmgstgmlyrdaamlddvtrfmfrsssvmk-----e
gatpdkevkpnsalgtlnahnmnvggdph---qcadydpydghppdnvag
reknqclhkaqsngpefesecldrkegcispvalgaipynghycvkgkgq
favvdelscc-sah-tcqkadvkgdsldlddalv----vkhaglf-apay
relklhi-----qqhpyakytantiavgle----g--lfslypldshvcr
fev-isgqtcyaegaer----gmapeqhvylam-sdddllglhrkvkd--
arivgpgmtskdsg--islhggqngaakatpplfpelanle-esrcgftl
--iqpgkgka-fil---afka--qiheltd---ltkaknelsrlst--sg
nnelsntkysesra
>ENV_SIVGB/47-569
cpsarvrlgkkkt-sdpfaylgegevrcsqkthaltccdvycfdpllkag
avrtakpgkpiqrhegicgvdtviwtlichkyrwv------yaecaerkg
giacc-----gktarpdlmeaplhltegeciasccyssfgelhersalpr
riaqcpgdavelggignglgtlisghpykig--aiefvtppqad-----l
nspnk-rles------aisyaasgagnps---qcsell---qtvaikc--
ghaidntatqrmtpvgfskshlaksgmvvegtsegavevr----tvkqs-
cg--aeqgcsdnka-kcelsgsddvvlllgsfls----lrhdi-y---py
klkkhnadhlglkelpyvkaegtgtaqgdr----p--cf-dvsaqewkca
fef-gsenavftdqktc----glgkkpctrldskctkrlvktqanlad--
vtgiggnapkeaveadaplalttfatagsrasvmaqm--ig-dsqcflpp
--atpsiqketfvd---sfaqavdrhkekt---laltpenatllddecvd
adalelakyslara
>ENV_SIVG1/22-522
spthqghshqksn-egpyal-----avlereahrikgcatycfvvekmas
eskkvkqvkdsgkmaslwahtagrwprlledfywrnppktkfrlmykkmd
gcdcy-----apetafhflcdnlptkngdcelecclagasplgehgthsk
seseadeatltpngagannsilyr--pygqavvifiravggvsn-----q
lpapatqvrehkylvslrghtlkgkdgid---dcselepfeghkstrvag
ndsamhlnknpgsspgsqsdflekakpsispiteggvallghfcwvgwga
faivedrgcc-hga-scakheenngllhldgnls----nkapkii---py
rerkldt-----dhhaqkkftaqahsvtkhdksvavalf-gllaqadvcr
fhl-gsehtcynaesat----glaksphg-----pnesltkdhvylkh--
yrlvspgktkkpag--ltlhdgqygvpaprpnllqgstlfdrekecafdt
--vapetdka-yar---rfgd--psdnahg---ltktttelaslha--th
kdticatkydetrn
>node17
cvegesrlrdtss-aqsral-----cdynasservkdcstvcfdvkyfep
vgdkirdltkiahleavlkqaigkwrrflnttywhdepmnglrmmfkqad
ictcc-----aigtcnpyl-qalaktdggcgkyccnnervpfighga--t
iqssgndvtlpsagsmgstgmlyreaamlddvtrfmfrsssvmk-----e
gaapgkevkpnsalgslnahlmnvggdph---qcadyepydghppdnvag
reknqclhkaqsngpefesecldmkdgcispvdlaaipynghfcvkgkgq
flvvdelscc-sah-tcqkadvkgdsldldealv----vkhvglf-apay
relklhv-----qqhpyakytantiavgle----g--lfslypmdshvcr
fev-isgqtcyaegaer----gmapeqhvylam-vdddllglhrkvke--
ariagpgmtlkdsg--mslrggqngaakatpplfpelanle-esrcgftl
--iepgkgea-fil---afka--qihelad---ltkaknelsrlst--sg
nnelsnakysesra
>node9
cvegesrlrgkas-ahsral-----cdfnasservkdcstacfavqyfdp
vgdkirdltkvahleavlkqavgkwrrflnttywhnppmnklrmmfkqae
ictcc-----aigacyqfl-qalpktdggcgkncchgdrvpfidhgt--t
iqgsgndvtlpsagsmgstgmlyreaamledvtrfifrtqsvkq-----e
gatpnkevkpnsalgtlsahnmnvgndph---qcadydpydghppdnvag
rdnaqclhkaqsngpafesealnrkegcitplamgaipynghyctkgkgq
favvddlscc-cah-pcekanvngdtldlddalv----vkhaalf-ipqy
rdmglhi-----qqhayakytastlavslq----g--lfslypldslvcr
fev-itgqtcyaegaer----gmapsqhvklam-sddnliglhrkiks--
arivgpgmtskdsg--islhggqngapkaspslfpskanlt-esrcgftl
--vhpgkgka-yil---afka--qihnlad---ltkakneltrlst--ag
nnelsntkysesra
>node7
spthhgrthaksn-egpyal-----avleaeghrikgcatycfvikkmas
dakkvkdvkksgkmaslwahtagrwprllndfywrnppktkfrmmykkkd
acqcs-----apqtsfhflcddlptkdgkcelecclagsvplnergthak
sesktdeatltpngagggnsilyr--pygeavvifirnvgsise-----q
vptpatqvrehkylvtlrghtlkgkdgpn---dcseyepfeghkpqrvag
sdkanhlnknpgsspgsetevlekaapgvspltegavpyvghfcwvgrga
fgivedrgcc-hga-scakqegdsgildldgyls----akpakvf---py
rekklqt-----qqhaqakltaqghsvtkhdipvsvalf-gflaqaevcr
fhl-gsehtcynagvas----glaksphgkakaapdesltgnhvylkh--
srivgpgktkkpsg--ltlhngqygvpgprpnllqettaig-etecafdt
--vspethkt-yar---rfgd--qtnnvqg---ltkakaelakmna--sh
kdvlpatkydetra
>ENV_HV2NZ/24-502
cvegesrlrdtrs-aqsral-----cdydassqrpedcstvtfevkyfep
vadkirdlakiahlelvlkqaigkwrrflnyyywhdepmsslrkmfkiad
ictcc-----aigacapyl-qalaktdsgcgkyccnservpyighge--t
iqgsgknvtlpskgaiggtgmlsreagilddvtrymfrssavms-----e
gaapgkevkpsgslktlnahlqnvngdpr---qcadftpydgappdnvsg
rsknqclskaqsngpgfeseilnmkdgcmspldlgaipyngqfcvkgrgq
llpveelscc-sah-tcqkahlkgisldleea-------ehaglf-apay
remklhv-----aqhpyakytaaliavgle----g--lrslypmdshvcr
fev-vsgqtcyaqgear----gkapeqhvylsm-vkqdqlaldrkvnd--
srtagpgvtlkdsg--msirggqggaamatpptyselatlq-esvcgftn
--idpgkgda-mil---vfka--qvhelad---ltgannelsrlgt--sg
nkelsnaknsesra
>node8
cpthqgrlhakss-enpypl-----ahleaeghrvkecatycfvikyias
dakktkdvkksgkmdalwrhtagrwprllnnfywhnppntkfrmmykkke
tcqcc-----asqtnfdflcddlptkdgkceldcclagsvplqergthak
tdsktneasltaagsgggnsilyrgvpyseavvififstgsise-----q
gptpakqvkehgylvtlsshtlkgtnapn---ecveyepfdghkpdrvag
sdkanhltkeqgnkpafetevlekaeagvsplaegavpykghycrvgrga
fgivedlgcc-cgd-scakadgdsgildldgyls----arpaslf---py
rekklqt-----qqhahakltgqalsvvkq----s--lf-gylaqaevcr
fhi-gsehtcytagvas----glaknphvklkmnadeslvgnhvklkh--
arivgpgkskkggg--lalhngqfgvpgprpnllqqtaalg-etecafdt
--vtpdtnkt-ysq---afgd--qthnvpa---ltkakeelrrlaa--th
kdalsttkydetra
>ENV_HV2BE/24-510
ctegqarlrdaar-adnral-----cdysassdrvndcntacfavkffdp
kgdknrgltkdahveavmkqaiakwrrfldntywqneikdglrmmfkqtd
ictcc-----aigacysyl-eal--------kyccndervpfvdhga--f
iqssnkdgtlpsagsmgshgmliressmlndvtrfmfksstvmk-----e
saapgkevkpnsklgtlnahnahvggesn---qcaeydqydghhpddvtg
reknqclhkaqssgpefesecldkkdgclspvalnairfnghyyvkgmgq
flavdvlrcc-sthftaqkakvkgdeldldgatv----vkhvglf-ipat
rnlklhv-----qehpyakytantiavgle----g--lfelypldshvcr
lavsiagqtcyaegaehglhvgkcsdqsvwlam-gddatldlhrdikd--
ahivgpgmtlkdst--islhagkngnhkaappmfpelantd-edrcgftl
--ilsgkgka-filltgaykd--qvqdltd---vtaaknelsrlsk--sg
snevsntkygqsra
>node14
cvegearlrdvas-adsral-----cdynasservkdcntacfavkyfdp
vgdkirdltkvahleavlkqaiakwrrflnttywhnepkdglrmmfkqad
ictcc-----aigacypyl-qal--------kyccnnervpfvdhga--t
iqssgndvtlpsagsmgsngmlirdaamlndvtrfmfrsssvmk-----e
satpgkevkpnsalgtlnahnlnvggdph---qcadydpydghhpdnvtg
reknqclhkaqsngpefesecldrkdgcispvalnaipynghycvkgkgq
flvvdelscc-sah-tcqkakvkgdnldldnalv----vkhvglf-lpay
rnlklhi-----qehpyakytantiavgle----g--lfglypldshicr
fevsisgqtcyaegaer----gmapdqnvylam-gdddllglhrkvkd--
arivgpgmtlkdsg--islhggqngaakatpplfpelanle-esrcgftl
--iqpgkgka-filltaafka--qiheltd---ltkaknelsrlst--sg
nnelsntkysesra
>ENV_HV2D1/24-501
cvdgaeklrgvas-adsral-----cdynasshrvkdcnpncfavkyfdp
vgakirdltmighlevqlkqaiaewrrflnttywhnepkdglrmmfkaae
icacc-----kigacypyl-qal--------kyccnnervpfvdhga--t
iqssgndvslpsganmgstgmliqdlamlndvtrfmfrsssvmk-----e
sngpgkdvkphsalgtvnahnlnvggdph---qcadyqpygghhpdsvtg
keknqcvhkaqsngpgfesecldqkdgcispvaldaipynghycvknkgq
flvvdesacc-tah-acqkpkvkgknldldtalv----ikhvgll-lpvy
rdlklhi-----qahpyalytadaesvele----g--lfglypldahitr
fevsvsgqtcy--gaer----gmaadenvylak-gdddlmglhrkvkd--
arivgpgmtlkesg--islhggqsapakatppsfpelanle-esr----l
--iqpgkgka-filptasfkp--qiheltd---lskakselsslst--sg
nnelgttlyaesrg
>node10
cvegesrlrdmas-ahsral-----cdfnasservkdcstacfavkyfdp
vgdkirdltkvahleavlkqaigkwrrflnttywhnepmnklrmmfkqae
ictcc-----aigacypfl-qalpktdggcgknccnndrvpfidhgt--t
iqssgndvtlpsagsmgstgmlyreaamlddvtrfmfrsqsvkq-----e
gatpdkevkpnsalgtlsahnmnvggdph---qcadydpydghppdnvag
reksqclhkaqsngpefesecldrkegcispvalgaipynghyctkgkgq
favvddlscc-cah-pcekadvkgdsldlddalv----vkhaglf-apqy
rdmglhi-----qqhpyakytastlavglq----g--lfslypldshvcr
fev-isgqtcyaegaer----gmapeqhvylam-sddnllglhrkvkd--
arivgpgmtskdsg--islhggqngapkatpplfpslanle-esrcgftl
--ihpgkgka-yil---afka--qihnltd---ltkaknelsrlst--sg
nnelsntkysesra
>node18
cvegesrlrdvas-ahsral-----cdynasservkdcstacfavkyfdp
vgdkirdltkvahleavlkqaigkwrrflnttywhnepmnglrmmfkqad
ictcc-----aigacypyl-qalpktdggcgkyccnnervpfidhga--t
iqssgndvtlpsagsmgstgmlyrdaamlddvtrfmfrsssvmk-----e
gatpgkevkpnsalgtlnahnmnvggdph---qcadydpydghppdnvag
reknqclhkaqsngpefesecldrkdgcispvalgaipynghycvkgkgq
flvvdelscc-sah-tcqkadvkgdsldlddalv----vkhvglf-apay
relklhi-----qqhpyakytantiavgle----g--lfslypldshvcr
fev-isgqtcyaegaer----gmapeqhvylam-gdddllglhrkvkd--
arivgpgmtlkdsg--islhggqngaakatpplfpelanle-esrcgftl
--iqpgkgka-fil---afka--qiheltd---ltkaknelsrlst--sg
nnelsntkysesra
>ENV_HV2CA/25-512
cvegerrlretss-aqsrat-----cdtkastervkacstvcfdvkyfep
vgekiredtkiahleal-kqsigkwrrfltttfwedepldglrkmfkqae
icncc-----aidscnhyv-qalgktkggcgkyccnkervpfikhgv--f
iqssgnevtlpfagamgstgilykeegllddvtiflfrsssvmk-----e
niapgkdvkphsalgslnahiqnvggnsh---qcadyepydghpsdnvas
kdknvclhraqsspaefeeecldkkngcisvvdlksiphngnfcvkgkgq
fllvddlgcc-sah-tcqkgevkgdsleldealv----vkhvgif-apay
relklhc-----qqhpyakytantitvgte----g--lfslypmdnhvcr
fev-lsgqtpyaqgaqr----smapdqhvylam-vndelfslhrrlke--
anipgpgmtllnsg--mslrggqdgaakktpplypelanie-esrcgfti
--iepgkgea-fiv---sfkp--qihelad---ltkakkeltrlst--qg
ksalstakfsesre
>ENV_HV2D2/24-513
ciegqsrlkdtas-eheral-----cdfkagaerykdvsatclavkyfep
ignkirelakvpnlpcvlkqavgkwrrfmnitywhndpinklrrlirqae
vctccclivnalgrchpfl-qdipktdggcgksccgngrppliqhgt--v
iqsrpkdvtlptansmgstgvlyresamleditrflfgssevkqnmklce
gatqdkevkpasalgalaahnlnvegeph---pcaaknmygghpsdgtvg
kerthclhkhqangaefeseclyrkegcistvplgaipynshyctrgkge
faavdslscs-cah-pcekavvkaesldlndalv----vshgglf-epqh
rkmglhi-----gphaylkysasalavsll----g--lfslyhldshlcr
fdv-insqtnyaegaer----gmasenhvflam--dtdllglhrkvkd--
arivgpgkaskdqs--lelhdgqnggptatqpvgpslanle-nhkcgftl
--rhhgkgns-fil---nfka--etrnttnykalaypkeelsrlst--qg
dnqlsgtkysgsra
