>node14
rvgsekngvsggfakhieprrkdkknakeh-----w-em--ncandkvck
gfstnsakttvfcviap--krtelkakvpsyvvgeklagaakvm---ame
vgkesf---pkedthhvtlkeeqsalnldfkptglgtq----lckpadlq
npkpgdgcivrin-sgt--rlsrinttplfllastvveldvqiqrdgqkv
diyipgpvvh----pyydsgaklskvfqrak-------hlmlagtlgrlk
gdthvghvelsnihpyvsvqhs--krkcklkn----yspppgtvslr---
ewglgsekpkdcgvvsknlspakeatgtksvvltfglakfflavdrp-ev
erkfvvgsnkgv---------------eecv--lve---rkaenlpfvki
ckgiavlsgfdplskdvnveswtd-------lflnlsppwgterkyssiq
hvrhd------n----dactpelstgacfkqrecrklpfyggekfvekgn
tdepsvcge---------avkrkgkpdfrqstglfklearqsyksnpa--
ggkatggskgchi---------caq-----lngs----ggasp-gq---c
rrvelgqdnscghc
>node18
rvgsektgvsggfakhieprrkdkknareh-----w-em--ncandkvck
gfstnsakttvfcviap--krtelkakvpsyvvgekligavkvm---ame
vgsesf---pkedthhvtlkeeqsalnldfkptgfgtq----lckpadlq
tpkagdgcivrin-sgt--rlsrinstplfllattvvaldvqiqrdgqkv
diyipgpvvh----pfydsgaklskvfqrak-------hlmlagtlgrlk
gdthvghvelsnihpyisvqhs--krkcklkn----yspppgtvslr---
ewglgsqkpkdcgvvsknltpakestgtksvvltfglskfflavdlp-ev
erkfvvgsnkgv---------------eecv--lve---rkaenlpfvki
ckglavlsgfdplskdvnvepwtd-------lflnlspqwgterkytsiq
hvrhd------n----dactpelstgacfkqrdcrklpfyggekfvekgs
tdepsvcge---------avkkkskpdfrqstglfklearqsyksnpa--
ggkatggskgchi---------caq-----lngs----ggasp-gv---c
rrvelgqdnscghc
>node7
fsagaktgsagvlsdqknpkatsnhalrap-----w-eklvpcsntevck
gnsagppats-fciptt--knkvlrtkfsgfvvgttlsgggtrm---gld
vgsdki---vqtemmavst---qlaqlldydakgfvsd----vckpagfg
trprkeatvlkle-pepainlghmkanplfflaasvgmlgmrwqkegedv
skvlp---ip----pfsdsgtksckvdhfvkdrlviacqlkgvgklgsld
vapgtgvnelaeinvynaceha--dtncklkg----ye------slp---
mwdlttakfmgcalaaislatswqtastenvvlwyainkyfv----nfgl
rarfvvagdnlerpdrsvnglklqglhanckpalveaas-reqklsflnr
cpsivvlsgfaampkvteaq---y-------nlpairvkwsketryceaq
gfrkn--ynkke----dvcaceltpghclkqwqvrplaf--petfganga
ldskekvtd--------------lrc--rletglfkqevraagkpppkrt
ggkataellscvaqlvkdsvhdcee-----argk----pgaig-gy---s
nr---gqpgkqg--
>ENV_HV2CA/25-512
rlgsektgvaggfakhvdprrkdkknaker-----w-em--ncpnedvcs
gfsansskvtvfiviap--kktelrakipsyvaveklighikgf---amd
vasesy---pkddshhktlkeeqsalkldlkptgfgaq----lckttnlq
lpkagegcivrml-sgs--klsrinstplyllattvmalgvqiqmdgakt
dayipgavvh----pfyekggklsklferak-------hlmlaaaigrlk
gdthvghielssvhpfisvqha--krkcklknyvrcyspap--islr---
ewglgsqkpkdcsvvpkdvtrakestgtksvvltfglskfflalhlp-dq
arkfvvgsnkgv---------------qecv--vvd---rkaeelkfvki
ckgmavlsgfaplmkdvniepwsd-------lfmylsgqwvterkytsiq
hcrhdsm----n----eectaelstgaclkqsdcrklpfyggdkfpekgs
teepaicge---------nvlkkirpgtrqstayfklegrqsykskpv--
ggkasggskgcni---------caq-----lkgr----gaaap-gv---c
rkvqlgqdsacgqc
>ENV_HV2BE/24-510
rvgsdkngvsggfakhiaprrkdkkdameh-----waqm--ncandnvck
gfstnsaktivycpigp--krteltakiptyvvgeklagaakim---ami
lgkesf---pkedthhvtlkedqsalnlnfkptglgtq----lckaadlq
npkpgdgcivrin-sgt--qfsridttdlfyvastvveldvqimrngqkv
dkyipgpgvn----pyydsgaklakvfqrak-------hlmlagtlarlk
gdnhvghvklsnihpyvtvhhs--krkcelkd----lssppgtvgls---
ewglgtekqndcgvvsknlspakeatgtksvvlpfglakfllavdap-av
erkfvigsnggl---------------eect--fve---kknenlpflki
ckgaavlsgfdplskdvnveswtd-------vflnlsppwgterkfstiq
evhhg------n----dactpelssgavfkqrecgklpfagadkfvekgn
tdeppicge---------avkrkgkpsfrqstglfklearqsyktdpa--
ggkasggskgrhi---------cad-----lngm----ggaap-gq---c
rkveagdnnscghc
>ENV_SIVM1/24-528
qvgsattgvsgvyvrhveprredkrsakeh-----w-dm--gcannkvck
tysvnsaktkafcirap--kkkdldpkvssyvdgekliggvkvr---gme
iggesf---psddtehitvkedqnavtlhygpngfgyv----lctpvdlq
trkagedvlvsyt-agt--kvsrinstpvfllaskvvaldvqiqrsgq--
--vipspavp----pfydngaklcrifqrgk-------hlmvaatlgklk
gathvghvelrnihpyigvepp--dkkcklkg----yd------slrlst
ewglgcqkpmecvvlsdsltganeksgsksvvlsfglskffllvdlp-ev
epkfvvggkrnv---------------esck--lveenskkkeslpfvkv
ckglgvlsgfdplpkdvsvepwaa-------lflelslkwgkkvryakvq
qirkd------n----dactahlktgqsfsqkdcrklpfygpekftekga
ldqasvcgesngqdatdvavkknskqvfmqstglfklegwgsnknnpsit
ggkatggskgchaqlhdrpfhkc-------lngs----ggahp-gv---c
rrlelgqdsrcg--
>ENV_HV2NZ/24-502
rvnsqktgvaggfalhvdprrkdslnameh-----w-ym--ycendavck
gfatnsakatvfcvisriarrtdlrtnvesyvvgeklngavlvf---amq
vgsesf---nkedtntvtlkeeqsalvldfkpkgfatq----lckpadlq
tvkagdgcivrln-sgs--klsrinstalyllttavvaaevqiqqdgqkv
dvyipgqivt----pfydsgaklskvfqrak-------hlmlagtlgrlk
gskqvghvelssihpygsvkha--krkckkks----yfpppgtls-----
ehglgsirpndcgtvskdltrakqstnakgvvltfglskfflavdla-av
vrqfavgsnkgv---------------egcv--lve---rkaedlpfvke
ckgmevlagfkplaknvnvepwsq-------lffslnpewgtdrgytsiq
hirad------n----dactpelrtgaclkqrdckklrfvggdrlvekgs
tdepnvcge---------kvlkmskpefrqakglltlearqsyksnpg--
gakgtggskgcni---------caq-----lkgs----ggpsp-gvpnny
rrvqlgqdtscnhs
>ENV_HV2G1/23-502
tvg--ktsvsggfakhiekaqk--knvreh-----w-dm--ecandkvck
gfssnsakttvfcaiap--srtelggkmpsyvvgekliaavkvl---gme
vgeetf---psedlhhvtlreeqtslnlgfkptgygaq----lckpadlq
tpkagegcivrih-ngt--rlsrinttplfllattvvalniqiqrdkqqv
aiyipgpvvh----pfydsgaklskvfqrak-------hlmlsgtlgrgk
gdtnvgdvevsnihpyvsvqhs--krkcklsn----ygpaagtlalr---
ewglgtqktkdcsvvsknltvakestgtksvvltfglskfflavdlp-ev
erkiivgsnkgv---------------decm--lve---rgaenvpfvki
ckglavlsgfdplsndvnvepw---------lflnlspqwgthrkytsiq
hernd------n----dactpelatascfkqrdcrklpfyggekfvekgp
tdepsvcae---------vvktkskpdfrqsaglfkleargsyksnpsrt
ggkatggskgchinlhespfqkcaq-----lkqh----gaatp-gv---c
srlelgddnscghc
>ENV_HV2D1/24-501
rvgskkngvaggfarhletrrkdkktakan-----w-em--ncenhkack
gfstnsvkttlfgvaap--krtelrakipssvvgeklagadkim---alq
vgkesf---pkdddhhv----eqfglnldfkgtgigtq----mckpadlq
npkpgdgcivsit-sgt--rlsrinttplflraytvveldvqiehdsqkv
diyipgavvh----pyydggaklpkvferak-------hlmsagtlgrlk
gdphvghtdlsnnhayvsvqhs--krkckvkn----fspppgtvslr---
ewglgsekpkdcgakskklspakiatgtkpvvltfdlakfflavdta-gv
prkfvvgtkkdv---------------edci--lve---pmaeslplvki
ckgvsvlsgfqpmgkdvnveswvd-------lfevlspfwgterkysaiq
hvrhd------n----dactpqlstgacfkqreskalpfyggekfvekgn
tdepsvcge---------avkrkgksgfrqstglfklearqsyknkpq--
ggkntggskgchi---------caq-----lnis----ggasp-gq---c
rrvelsqdnscghc
>node11
tvgsektgvsggfakhieprqkdkknareh-----w-em--dcandkvck
gfstnsakttvfcviap--krtelkakipsyvvgekligavkvm---gme
vgsesf---psedthhvtlreeqsalnldfkptgfgtq----lckpadlq
tpkagegcivrin-sgt--rlsrinttplfllattvvaldvqiqrdgqkv
diyipgpvvh----pfydsgaklskvfqrak-------hlmlagtlgrlk
gdthvghvelsnihpyisvqhs--krkcklkn----yspppgtvslr---
ewglgsqkpkdcsvvsknltpakestgtksvvltfglskfflavdlp-ev
erkfvvgsnkgv---------------eecm--lve---rkaenlpfvki
ckglavlsgfdplskdvnvepwtd-------lflnlspqwgterkytsiq
hvrhd------n----dactpelstgacfkqrdcrklpfyggekfvekgs
tdeasvcge---------avkkkskpdfrqstglfkleargsyksnpsrt
ggkatggskgchiplhespfqkcaq-----lngs----ggasp-gv---c
rrlelgqdnscghc
>ENV_SIVG1/22-522
fkagaktgsagvlanqknpkattnhalrapak---w-eklvpctntnvck
gnkagppats-acippl--krkvlrtdfagfvvgttlcgggtrfekigld
vgadni---vete---pss---elarlldydvkgfvse----vckpagpg
trprkeaavlkle-aeppislahmkenplfflgasigmlgmrrqkegedv
trvlp---lp----pfsd---ksckvdhfvkvrlviacqlkgvgdlgnld
vadgtgvnelaeknvnnacera--dtnsklkg----ye------slp---
mweltvakfmgcalsairlatswqaedtekvvlwyainkyfa----nfgl
rakfivegdgldrpersvnglklqglhgdckpalvegas-reqnlsflnr
cpsivvlcgyaaipkvtevq---y-------rlkairvrwsketryceaq
gyrnn--ynnke----tvcacelapahclkqwqvrpvaf--pqtfgangs
ldakekvtn--------------lrh--klqtglfkqvvraaakpspkrt
ggkataeifscveqpvkdsvhdced-----vrgk----pgtig-gy---g
sr---gqpgkqg--
>node8
fsagaktgsagvfsdqkdprassnhalkap-----w-eklvpcsntdvck
gnsagppsts-fcippt--kkkvlktkfsgfvvgttlggggtrm---gld
vggekl---vqtdtmpvst---qlaqaldydakgfgsd----vckpadfm
trhrgeasvlkle-pktaiklgklkanplfflaasvgalgmrwqkegedv
nkvlp---vp----pfddsgtksckvyhfvkerlviscqlmgvgklgrld
vapgvgvnelaeinvysgcehs--akncklkg----ye------glr---
kwdlvtskfmacalyaeplattwqsagtenvvlwyainkyfv----nfgl
rsrfvvagdnlerpdrsanaikltglhteck--lveans-kqqklsflnr
cpsivvlsgfavmskvteaq---y-------nlvslrvkwsketryckaq
efrkn--ynkte----dvctcellpghclkqwqvrplaf--petfgdkgt
ldqkakstd--------------arc--rldtglfkeevrgagktppkrt
gskatpellgchaqlisdpvhqcee-----lrgk----pgtig-gt---s
kr---gqpgkag--
>ENV_HV2D2/24-513
tvgsektgaaggfakhvkprtkdkniareh-----w-ek--gcgnkpvcr
systnsvsdtvfcviap--krtdlkakvpnfviseklitagkvm---avk
vgfenh---pfeshphvtlreeqsayglyfkpdgfgah----mcksgvlq
tktagedcikrin-fgs--klsrmstlplfllattvvalddqiqrdgdkl
kvimpeflvp----pfynsgfklckiydqgy-------hnmmggtlgwlk
nethvghvglvkthpyinvqhs--kkkcklng----yp------tlr---
mwglgrkkphdssvvgqdlapanensgskavvlnfglraffilielp-ev
prrfvlgsdgnv---------------eecm--ive---rksenllfckl
ckdvavlsdfdplakdvnveawyk-------lfvnlspqwskekrytkiq
evkks------ktttkdactaklstdecmnqrdcrklpffgpqkfvpkgg
kqeasvcgd---------avkkkskpdirdstglfsmdargsnacspssk
ggkaatgskgcqfpfhespfqkciq-----legs----ggasprgv---s
salelgqdkscgh-
>node19
rvgsektgvsggfakhieprrkdkknareh-----w-em--ncandkvck
gfstnsakttvfcviap--krtelkakvpsyvvgekligavkvm---gme
vgsesf---psedthhvtlreeqsalnldfkptgfgtq----lckpadlq
tpkagdgcivrin-sgt--rlsrinttplfllattvvaldvqiqrdgqkv
diyipgpvvh----pfydsgaklskvfqrak-------hlmlagtlgrlk
gdthvghvelsnihpyisvqhs--krkcklkn----yspppgtvslr---
ewglgsqkpkdcsvvsknltpakestgtksvvltfglskfflavdlp-ev
erkfvvgsnkgv---------------eecm--lve---rkaenlpfvki
ckglavlsgfdplskdvnvepwtd-------lflnlspqwgterkytsiq
hvrhd------n----dactpelstgacfkqrdcrklpfyggekfvekgs
tdeasvcge---------avkkkskpdfrqstglfklearqsyksnpa--
ggkatggskgchi---------caq-----lngs----ggasp-gv---c
rrvelgqdnscghc
>ENV_SIVGB/47-569
fsglletgiavfraankeatapaerafaia--qmfs-defidgmetqacg
gnkqdghaep-fstppt--klkvlhkapkttpggk---gnhpkm---dgt
vndkrmvvhfelktcaqag---thfmavlyyskghsqmtfkrkcdfakyl
tvqgseraiqegeirkalmtlgsskaalirfeaqeatgvaltwarsslae
eklvs---gapaftsfe---ankcqitrlmkeemyaaciftkhgglsalp
vskgtflkrlsnrrpydccyqsqatrnckast----fk------tdv---
kskavasrftvsptagkpigdkwtsretgntllwflmhhywv----emdp
rv-fmilgdtidmpsrgvsllhvtgllkdcn--lmeheg-knqepaflym
psnsvrmhaftanntvqtta---cgktelyfnhggkrpawakddrtapag
kgnyf--nfr------kfcvceilskh-----tvqgipr--plvaekegv
rg---------------------------fgpnmkveyikngsslsargt
gpkhksgflgcpaelmdipktqmednlssliken----neqid-pt---s
kk---gkanraa--
>node17
rvgsektgvaggfakhieprrkdkknareh-----w-em--ncandnvck
gfstnsakttvfcviap--krtelrakvpsyvvgekligavkvf---ame
vgsesf---pkedthhvtlkeeqsalnldfkptgfgtq----lckpadlq
tpkagdgcivrin-sgt--klsrinstplyllattvvaldvqiqqdgqkv
diyipgpvvh----pfyesgaklskvfqrak-------hlmlagtlgrlk
gdthvghvelssihpyisvqha--krkcklkn----yspppgtvslr---
ewglgsqkpkdcgvvskdltrakestgtksvvltfglskfflavdlp-ev
arkfvvgsnkgv---------------eecv--lve---rkaedlpfvki
ckgmavlsgfdplskdvnvepwsd-------lflslspqwgterkytsiq
hvrhd------n----dactpelstgacfkqrdcrklpfyggdkfvekgs
tdepsvcge---------avlkkskpdfrqstglfklearqsyksnpg--
ggkatggskgcni---------caq-----lkgs----ggasp-gv---c
rrvqlgqdsscgqc
>ENV_SIVV1/24-538
fsagarvdsagllgdfqnpkaksqqalkvi-----w-ihlvpcshtevck
knsagppast-----tt--knkvlkakfagfvigstfngggtrm---ald
agqedi---mvremtagas---avaqllkfgakeftsd----dckssgyg
dsprkatvilklg-pepalnlghmkakpvffltlpvgllgvrwqkagekv
t--lv---gr----pfsdnatgackvhhfvrnrlveaceskggaqlgcid
fakgtganklaeisvyaacshm--nnncklkt----ye------slv---
mweatpsknm--alavvmldaqwqtasgsnlvlwyaiqkyfv----tfal
rsrfpaasdrlhrpgrsmnglklphllvtckpalvefsk-rtqqlafvpr
cati--lggfesepkvtesq---t-------dllavavkwskqarycees
vfrkn--knkgh----dvcscelhpehclrqwearalef--tenfgdndg
in-nehlsd--------------arc--kfgaglfkgdvqasgkppprkp
ggkavaeilscvgqlandgvhncve-----lrskkqpttgtvg-gf---s
nr---ghpgmqg--
>node10
tvgsektgvsggfakhveprrkdkknareh-----w-em--gcannkvck
gfstnsakttvfcviap--krtelkakipsyvvgekligavkvm---gme
vgsesf---psedthhvtlreeqsalnldfkptgfgtq----lckpadlq
tkkagedcivrin-sgt--rlsrinttplfllattvvaldvqiqrdgqkv
divipgpvvp----pfydsgaklckifqrgk-------hlmlagtlgrlk
gdthvghvelsnihpyinvqhs--dkkcklkg----ys------slr---
ewglgsqkprdcsvvsenltpanestgsksvvlsfglskffllvdlp-ev
erkfvvgsnknv---------------eecm--lve---rktenlpfvki
ckglavlsgfdplskdvnvepwtd-------lflnlspqwgkerrytkiq
qvrkd------n----dactaelstgecfkqrdcrklpfygpekfvekgs
tdeasvcge---------avkkkskpdfrqstglfkleargsnksnpsrt
ggkatggskgchaplhespfqkcaq-----lngs----ggasp-gv---c
rrlelgqdnscghc
>node9
qvgsektgvsgvfakhveprrkdkknareh-----w-dm--gcannkvck
gystnsakttafcviap--kkkelkakissyvvgekliggvkvm---gme
vggesf---psedtdhvtlkeeqsavnlnykptgfgtq----lckpadlq
trkagedclvgid-agt--klsrinstplfllattvvaldvqiqrdgqdv
divipgpavp----pfydsgaklckifqrgk-------hlmvagtlgrlk
gathvghvelsnihpyigvehs--ekkcklkg----ye------slr---
ewnlgsqkpmecvvlsesltsanestgsksvvlsfglskfyllvdlp-ev
eskfvvgskrnv---------------eeck--lveadsrktanlpfvkv
ckglvvlsgfdplskdvsvepwta-------lflnlsvqwgkeiryakvq
eirkd------n----dactaelstgqcfkqrdcrklpfygpekfvekga
ldqasvcge---------avkkkskpdfrqstglfklegwgsnksnpsrt
ggkatggskgchaqlhespfhkcaq-----lngs----ggakp-gv---c
rrlelgqdnrcg--
