>node8
yalviypllgsve---sqpgg------ssq---akkkq-an--n-iedgg
atvagk-safgnkgkfenkvvkygalgaagdncwivggwdnptscmdayy
-rltgvivppafkqgtcaptdganp----qeyclflaginrkgitlfgdl
vfrqlrrqhdyslscslplyftstpgrntqmkhnkkgssgltttcgalka
gsaa-flsalltmkddl----------k----plvardvfk--ga---fc
asdkpilkvkiqicphdtlktaglgvstnsggdv------ittttpmafa
tqmllkethpqmdpatfhikipesakyrgstlcta---ivetf---dved
yt-dlt--cslkteqm------pykapaelggq---nkgakgesalkpah
gfqhavtfntkelctc--vsadsykikevplhfq--awdr------ktka
lgqlytcvnchydg----lratrivksddtkatvtgntepwctsqghegg
lgrnldt---------pggtavtctt---rknhnkv--sfllndkttevr
crtscltpkeldtttnvvpgkdqemsnatipltlaaklc
>ENV_HV2BE/24-510
aatvvielmlevt---dppag------lgq---vaerq-ied-avpaesg
latpgt-ttt----fykhkvirytnletvttdcwvkeaylnrtsckeeyy
-rltkfvvkasylrgtcapkqgasa----qd-------dnqwgqdliiim
ayvqtwrlhdyglscl-hlhvnfgpgkhpqmthkkkgqgaleldcgqvrl
saek-flvcfltvktdvgswrigsslds----tmvpkqvek--ga---fc
vgsesrgklkipacagqeqgpnplggitnppadv------gsladdahfc
trrllrqihqdleatrfqievtdeatyrstkltge---vvssw---sdga
yq-stp--cayrsadlglkkavp-knhddland---hkgskaytlvevnl
gsqfalnfyartlcic--pvadsyvlnhiflqiq--ewsrq--rywksks
hkelydcghvncaa----evsadvvknniprakitnsteffadasgskvg
lgkefat---------tegvvasg-----akfvdka--gflldknfdevq
twirrlphre----tkvvprkdeeltnvlqplvikhklc
>ENV_SIVG1/22-522
yplviypyle-ve---sppgg------csqisqskksl-an--n-igeas
aavpnk-sayghk--hdnkvvqygalaaggdtcwilgdwddpascmsayq
-rltggvvppkfkqhtvarvdaanp----qeyclgvttinrkgftifddl
vfrqlrrqqdfslscpapmylmskpgsntlqahnkrassgfaptcgaike
gsat-flsslvtmddev----------k----plvaqevfk--gr---fc
padkpilkvridicradtlktaalgfstksggav------vtvasplafa
aemgwkqthpqldhqtfkilipepakyrgstlcta---lvetf---dcge
ha-dln--cslitaem------tyksavdvggq---nraakgdgvlnpsv
sfqetvtfntipacsq--vaadaykipevplhve--awnr------eikq
lgqvyfcvvckydg----lrttrvvkfedtkstitgrtgewctsqghecg
lgtkldsakgv--lvqpggakvtctg---rkntdnv--aflltdktteer
crtacltpknlenttmvlsgkpmgmnngtypynlngklc
>node17
salvvvqllvevk---tppvg------pgq---varrq-idd-aappetg
lavagt-tss----ffkhkviryssletvssdcwvkggygnstscmeeyy
-rltgfiikatylrgtsaptqgasp----qg-------ddqngqdliidm
ayvnlwrahdyglscl-hlhgnfgpgkhaqmkhkkkgqgslellcsqvrl
ssed-flvcfltvktdaaswwigspids----pmvpkqvaklsga---fc
vasasigklkipscagqelgpnplggvtnapaev------gsladdthfc
trtllkeihqdleasrfqievtddatyrgtkltge---vvsdw---adga
yk-sts--cayrsgemglrkaqp-kaqdelagd---hrgskvyslvevnl
gfqfvlkfyartlctc--svaesyllkhiflqiq--swsrq--rywkkks
hkelyncadcncpt----evstdvvktnipraavtantdffadadgskvg
lgrelat---------tdgvttsgtt---akfgdks--gflldksfnevr
cwtrrlrhre----tkvspkkneeltnvlqllvikhklc
>ENV_HV2CA/25-512
stlvvipllvevk---tppvg------pvr---vakre-idd-aappets
lavavt-tss----ffkhkviryagletvgcdcwvrggcgngtscmeeyy
-rlsgfivkgaylrgtsaptqgaap----qg-------ddqkgqdlvidm
syvnlwrandygvscl-hlhgsfgpgkhaemshknkgqnslellcaqvrl
gsde-flvcflgvktnqaywsignpids----pmvpqqvgklsga---fc
vasasigklevpscagqelspntlggvaqagaev------sslaestqfc
trtllteihhdlaasrfqievtddasyrgakltgt---vvsdw---adsp
yk-wts--cayrsgemglrkaqp-kaqdelaad---hrgskmnsmvavnl
gfqfvlkfnartlctcfesvaesyllkhifiqir--swsrq--sswksrs
hkelfncaeckcpf----pqstdvvktniprppvtgnadffagaqgsaig
lgrelaa---------tdgvtasgtt---ekggdka--gfmldksyaevh
cwtrrlkqke----tkvspnkveqlthvlqlllikhkkc
>node14
aalvvvelmlevk---tppvg------pgq---vaarq-idd-aapaetg
lavpgt-tts----ffkhkviryssletvstdcwvkgayanrtsckeeyy
-rltgfiikatylrgtcaptqgasp----qd-------dnqngqdliidm
ayvetwrlhdyglscl-hlhvnfgpgkhaqmkhkkkgqgalellcgqvrl
saed-flvcfltvktdlaswrigspids----pmvpkqvek--ga---fc
vasesigklkipscagqeigpnplggvtnapaev------gsladdahfc
trtllkqihqdleatrfqievtdeatyrgskltge---vvsdw---adga
yq-sts--cayrsaemglrkaep-knqdelagd---hrgskvyslvevnl
gsqfvlnfyartlctc--pvaesyllkhiflqiq--awsrq--rywkkks
hkelyncadcncpa----evstdvvktnipraaitantdffadadgskvg
lgrelat---------tdgvvasgtt---akfvdka--gflldknfnevr
cwtrrlphre----tkvrprkneeltnvlqplvikhklc
>ENV_HV2D1/24-501
talvvvellvevk---tppvg------tgq---vaart-ldd-aapdetg
lavpgt-tts----fykhkvirhsslesvstdgwtkgvyakstsckdefy
-rltgfiikatylrgtcapsqgtsp----ed-------dhqygqdqvigm
fyvrtwrlhdyglscl-qlhvnfgpgkhpqmphkkkgqgaleflcsqvrl
nped-fvvcfltvktnfaswrigspids----pmvptqtek--la---mc
ianqsigklkipscagqeigakplggvtnapadi------asladdvhfc
arkllkeihqdleaarfeievtdestlrgskltge---vvttw---adga
yq-ttk--cayrsaemglrktes-knqdalagd---hrgskvyslvaanl
gsefvinfyartlcsc--hvtdtfllrqiflqiq--awsrq--tywkkks
hkelyscadcncpa----evstdvvrtniprtattantdffadadgnkig
lsrdlgt---------tdgvvagvss---akfvdka--gfllvrnfaavr
cwtrrlpnrq----tkvkerkneelqnvlpplvvkhklc
>node11
salvvvellvevk---tppvg------pgq---varrq-idd-aapaetg
vavagt-tts----ffkhkviryssletvssdcwvegaygnstscmeeyy
-rltgfiikatylrgtcaptqgasp----qdyclfseldnqngqdlfidm
ayvelwrlhdyglscs-hlhgnfgpgmhaqmkhkkkgqgslellcgqvrl
saed-flvcfltvktdlaswrigspids----pmvpkqvak--ga---fc
vasasigklkipscagqelgpnplggvtntpaev------gsladdahfc
trtllrqihqnleasrfqievtddatyrgtkltgd---vvsdw---adga
yk-sta--cayrsaemglrkaep-kaqdelagd---hrgskvyslvevnl
gfqfvlnfyartlctc--svaesyllkhiflkiq--awsrq--rywkkks
hkelyncadckcpv----evstdvvktnipraavtantdifadadgnkvg
lgrelat---------tegvttsctt---akfvdka--gflldknfnevr
cwtrrlphre----tkvrpkkneeltnvlqplvikhklc
>node18
salvvvellvevk---tppvg------pgq---varrq-idd-aapaetg
lavagt-tts----ffkhkviryssletvssdcwvkgaygnstscmeeyy
-rltgfiikatylrgtcaptqgasp----qd-------dnqngqdliidm
ayvelwrlhdyglscl-hlhgnfgpgkhaqmkhkkkgqgslellcgqvrl
saed-flvcfltvktdlaswrigspids----pmvpkqvak--ga---fc
vasasigklkipscagqelgpnplggvtnapaev------gsladdahfc
trtllkqihqdleasrfqievtddatyrgtkltge---vvsdw---adga
yk-sts--cayrsaemglrkaep-kaqdelagd---hrgskvyslvevnl
gfqfvlnfyartlctc--svaesyllkhiflqiq--awsrq--rywkkks
hkelyncadcncpa----evstdvvktnipraavtantdffadadgskvg
lgrelat---------tegvttsgtt---akfvdka--gflldknfnevr
cwtrrlphre----tkvrpkkneeltnvlqplvikhklc
>node10
salvvvellvevk---tppvg------pgq---varrq-vdd-aapadig
vavagt-tcy----yfqhkvvrysslstvssdcwvegaygsstscmeeyy
-rltgfiikatymrgtcattqaasp----qdyclfaelddqngqnlfidm
ayvelwrqhdyglscsshlygnfgpgmhaqmkhkkkgqgsleltcgqvrl
saed-flvcfltvktdlgswrigspids----plvskqvak--ga---fc
vasasigklkipscagqelgpsplggvtntpaev------gsladdahfc
trallrqihqeleasrfqidvtddatyrgtklcgd---vvadw---adga
yk-eta--cayrsaemglrkaep-kaqdelagq---hrgskvyslvevnl
gfqfvinfytrtlctc--pvaesyllkhiflhiq--awsrq--rywkkks
hkelyncadckcpi----evstqvvktnipraavtantdifadadgnkvg
lgrelat---------aegvttsctt---akfvdka--gflldknfnevr
cwtrrlppreldgktkvrpkkneeltnvlqplvikhklc
>ENV_SIVGB/47-569
vaplvylqtghic---tevgi------gdv---pvndh-sp-pn-sdkrg
lcvvaigsgclhhsndqn-spryehlslesrvakllgghnttegggegyf
-vptgillprafvndicncmgglet----iaycmfmagvhtktsaivgqv
iflgvqqaggklkycglp-ffdasveflrsltktlvlhaskptkcsksay
gesetlysslslvdlkv----------qqlfhgla-rrlfk--gf---yc
astkeidpikvvkcqtkclkagglaitgggkvdt------vtacsamltl
vqvmgkacragsgnvglareaphgdkyakfvlsgt---ldqeh---slde
qeddla--cnfeaaga------lfkdekhlafttvaprlmks-tgttpnn
kfdnedststqd-cmc--vgmamskvs----hyk--sevt------kykc
sthynscatdiypg----glavk------dkdkmeasleermtargrngs
lgghlgd---------pgafqqtctppktapkkakvggtyvkgaeydktk
tsshcif---------vmpgsvkgignkgihlkisrggc
>ENV_SIVM1/24-528
nalvvfvllvevk---tppvg------tgq---vmkrq-say-alrgdvg
vklagt-trf----yfqqkvlrysalstvgckcwinggwgsstscmeaky
-rltgfckvatfmrgtcpttqsarp----qdy----elddrqernlfidl
gylelsqqhetglscashyygnfgsgmhvhmkhkkkgqgg-alecghvrl
sadd-flvcflgpktdlgtwkigyairg----pllskqtat--ga---fc
vpsaalgrlkippcdgqqggatplgnstnkpaei------gsledpdhyc
trnllrnthreleasrfqidisddgkyrgskltad---vvptw---ddga
ys-etavpcayrsgdmglrkaep-tgeeelagh---ekvekvcntaelnl
gyqlvvdfytrtlctc--pvaesyllkqiflhiq--swsrrlvrywkkrs
hedlyncadckcpi----evgyqhvktniprdgvtantnafsdgegskvg
kgrgltt---------segvspscat---akycdkp--aflldedfshir
cwtrrlppkeldgktktrpnqdgeltnavqplvikqklc
>ENV_HV2D2/24-513
savilvevilevk---tspvn------vaq---verrq-ede-dapadig
vdvagt-tcy----yfqhkvskynplgiiadncwvigaygnstscmeeyy
-qltgfnitttymrgtcataqaaspltvhmdyclfaelddqnghnlfidm
afvelwrkkefglscethhygntgpgmhatmkhfkkgpgsleltcgdvrl
sase-levafltvktdrgswrikapldt----plvtsqggk--ga---fc
vasapigkldipastgqelgpcalggvsittaev------aelasavhic
yrallrqiqqqleakrfqrdvtsdatyqgaklceh---pvanw---avsv
yk-eaa--cvyrstqmglkndda-kvqdelagq---hfgkkdyslvevgl
gfehvmkffsrtlctc--pvaatyllsnvflqlqseewrrl--kfwrkka
pkelyncgdckgpi----elngqsvttkvpraalsahsdvfaeadgtkvg
igrdlkn---------a---tascmt---gkyvdka--eflleknfngvk
cwtrrlpprelngktsiqpkknealttvlqpivikhklc
>ENV_HV2G1/23-502
kalvvvellvevk---tppig------pgq---varrq-idd-alpadng
vavagt-tta----ffkqnviryssletigsdcwvegaygds-scmeeyy
-rltgfiikatylrgncaptqaasp----qdyclfdeldnqsgqdlfidr
afvelwilhdyalgcs-hlhgdfgtagraqmkhkkkgqgslellcgnvrl
taed-flacfitvkanlaswrigspita----pmvpkqvgk--ga---fc
vasasigklkipscvglelgpnplggvtntpaev------gslmddanfc
artllrhihqnleasrfqlevtnnatyrgtkltgd---vvsdw---adga
yk-sae--cafrsedmalrkpep-kaqdeldga---hrgssvyglveinl
gfqfvlnfyartlctc--saaetyllkhvflkvl--awsrq--rywkkkg
hkglygcadckcvv----elstdvvkmnmpraartaitdifadadgnkvg
lgrelal---------tsgavtsctt---skfvdka--gfslgknfdevr
cwsrrlphre----ttvrpkkneevtnvfqplvikhklc
>node7
yplviypylgtve---sppgg------csqcsqakkkp-an--n-igeas
atvpgk-saygnkgkfenkvvmygalgaagdncwivgdwddpascmdayt
-rltgvivppkfkqntcakvdgagp----qeyclgvsginrkgftmfedl
vfrqlrrqhdfslscplplyfastpgsntqqkhnkrgssgltptcgaika
gsat-flsslltmkddv----------k----plvaqevfk--gr---fc
padkpilkvkidicpadtlktaglgfstksggav------itvttplafa
aqmglkethpqldpqtfhilipepakyrgstlcta---ivetf---diee
ya-dlt--cslkteem------pykaavdvggq---nkgakgeavlkpaq
gfqetvtfntiqacsh--vaadaykinevplhfq--awnr------qikq
lgqiyfcvvceydg----lrttrvvkfedtkatvtgrteewctsqghesg
lgssldtakgv--lvqpggssvtctt---rknlnkv--sfllsdktteer
crttcltpknldtttsvqsgkiqkmsnatiplslagklc
>ENV_SIVV1/24-538
ypivfypylgtvqfllsphgg------csgcsrskiktinn--h-vgqgs
ptvpgr-kaygnkgcfnhkivmygalgaatdncwlmgdwtepsasmnayt
hglsgvavdpkfkqttcakvdgagk----aeyclglsgiahkgftmgael
vfrqlhnlhkfslrhpltlnydgtpgsqaeqkkngngrtglspacgaisa
astt-flrglltkkkdl----------k----plvtrevyk--grvldfc
pakqpiilvklekcptdtlkrtgvgfsttagaavlgqeytvtvttpnaaa
ahmglkqvhghlhpqtfhitfpepakyrgttlcea---vvntatgqdieq
yp-hmp--calktdel----------avavggq---dksakgdpilspar
afqetltfntiracsh--vpadpyrvdeiplnfq--trlr------qikq
lgqiyfcclceydgfdcrlrgarvlkfegtqannhg-tdewctpqggegl
lgarldtekgvailvqpggstvactt---rknlgkv--dfllsekvykas
irtaclnprnldlttsvqsgkkqkisnstipmsltgkwv
>node9
salvvyallvevk---tppvg------tgq---vkrrq-vse-aapadig
vsvagt-tcy----ffqhkvlrysalstvgsdcwieggwgsstscmeayy
-rltgfiikatymrgtcattqsarp----qeyclflelddrdgrnlfidl
ayvelwrqhdyglscashlygnfgpgmhaqmkhkkkgqgslaltcghvrl
saed-flvcfltvktdlgswrigsains----plvskqvak--ga---fc
vasasigklkipscsgqelgptplggstntpaev------gsladpahfc
trtllrqihqeleasrfqiditddakyrgtklcad---vvatw---edga
yk-eta--cayrsaemglrkaep-taqdelagq---nkgskvystvevnl
gfqfvvdfytrtlctc--pvaesyllkqiflhiq--awsrk--rywkkks
heelyncadckcpi----evstqvvktnipraavtahtdafsdgdgnkvg
lgreltt---------pegvttscat---akyvdkp--gflldqnfthir
cwtrrlppkeldgktkvrpnkdeeltnalqplvikhklc
>ENV_HV2NZ/24-502
aalvvvqllvevk---sppvgksldavpsq---varrq-idd-vappevn
lagagt-tss----ffkhkvvryssletvtsdcwlkagygkttssveeyy
-rltgfiikatylrgtgapteganp----qv-------ddqnahnliiel
vyvnlwrshdygvscl-hlhgnfgpgkhpkmdhkkkgqgnlelacsqvrl
ssed-flvcllkvltdaakwwigepids----pavpkqvaklsga---fc
vaggsiaklripscaaqelgpnplggvgkapsev------isiadnthfc
trtllkeihqkleasrfqievtddgsyrttkltpeacyvisdw---adga
yk-sts--canssdemglrkaqp-kgqdslagd---hrgskvyskveidl
gfqfvlkfiartlctc--saaaayllkhiflqih--swgrq--rywkkkt
nkeayncadc-cpt----ilsidvvkiriprseitgktnffsdadgskig
larelpt---------tdgvatngtn---tklgeks--tflldksfdttr
cwprrlrhrd----hdcspkkneeltnmlqllvikhklc
>node19
salvvvellvevk---tppvg------pgq---varrq-idd-aapaetg
lavagt-tts----ffkhkviryssletvssdcwvkgaygnstscmeeyy
-rltgfiikatylrgtcaptqgasp----qd-------dnqngqdlfidm
ayvelwrlhdyglscs-hlhgnfgpgmhaqmkhkkkgqgslellcgqvrl
saed-flvcfltvktdlaswrigspids----pmvpkqvak--ga---fc
vasasigklkipscagqelgpnplggvtnapaev------gsladdahfc
trtllkqihqdleasrfqievtddatyrgtkltgd---vvsdw---adga
yk-sta--cayrsaemglrkaep-kaqdelagd---hrgskvyslvevnl
gfqfvlnfyartlctc--svaesyllkhiflkiq--awsrq--rywkkks
hkelyncadckcpa----evstdvvktnipraavtantdffadadgskvg
lgrelat---------tegvttsctt---akfvdka--gflldknfnevr
cwtrrlphre----tkvrpkkneeltnvlqplvikhklc
