>node17
l-------tqkige--eaaktrayerqatn--msagapscsgqntpkggq
d----faaviavstqlelf---rktg------sqstnmmtrhnrghtdgn
gfeane-----krghladktatvdakagnh-pklsyl-----salqd--m
rpfvdkknewaraefrraasasnvkka--nvtqqdiylkqt-----hevr
elayllkfsahcsrvdgvcik--sgdcgl--elttaldvyptlnlc-qcq
---vyeaglicahsfav--tvtavqrt---seitiyivaslpggaccgct
lgpvrkkklssvttatialagtdldtfawehlvcisnlaktgallrspvl
gnkwktelmssnghavdgtciafslyvshfy-stleskmfdesressvvf
pgvyge-------eshilgkitfelasgsagevvqfytgfnakcmgelcy
dkaklivfekaffgtcavqvtasqekldlgtdpkvinq------------
-enyikialckeklptyn---tqrsyathasvkggvllcrk---------
----sfvqnadypinveahmplgav-rvikgnavysvkskpntff
>node18
l-------tqkige--eaaktrayerqatn--msagaprcsgqntakggq
d----faahiavstqlelf---rktg------sqstnmmtrhnrghtdgn
gfeana-----krghladktaevdakagnh-pklsyl-----salqd--m
rpfvdkrnewaraefqraasasnvkkt--nvtqqdiylkqt-----hevr
elayllkfsahcsqvdgvcik--sgdcgl--qltsaldvyptlnlc-qcq
---vyeaglicahsfav--tvtavqrt---seitiyivaslpggaccgcn
lgpvrkkkltsvttatialagtdldtfawehlvcisdlaktgallrspvl
gnkwktelmssnghaidgtciafslyvshfy-ttleskmfdesressvvf
pgayge-------eshilgkitlelasasagqivqfysgfnakcmdtlcy
dkaklilsekaffgtcavqvtafqeklnlgtdpkvinn------------
-enyikialckeqlptyn---tqrsyathasskggvllcrk---------
----sfvqnanypinvethmplgav-rvikgnavysvkskpniff
>node19
l-------tqkige--eaaktrayerqatn--vsagaprcsgqntakggq
d----faahiavstqlelf---rktg------sqstnmmtrhnrghtdgn
gfeana-----krghladktaevdakagnh-pklsyl-----salqd--m
rpfvdkrnewaraefqraasasnvkkt--nvtqqdiylkqt-----hevr
elayllkfsahcsqvdgvcik--sgdcgl--qltsaldvyptlnlc-qcq
---vyeaglicahsfav--tvtavqrt---seitiyivaslpggaccgcn
lgpvrkkkltsvttatialagtdldtfafehlvcisdlaktgallrspvl
gnkwkselmssnghaidgtciafslyvshfy-ttleskmfdeskessvvf
pgayge-------eshilgkitlelasasagqivqfysgfnakcmdtlcy
dkaklilsekaffgtcavqvtafqeklnlgtdpkvinn------------
-enyikialckeqlptyn---tqrsyathasskggvllcrk---------
----sfvqnanypinvethmplgav-rvikgnavysvkskpniff
>ENV_SIVGB/47-569
iakagghckvraaq-skgprq----ktagn--gvnqleecthqaartgvt
s----wgg-kdnl--fkqv---gecqlsktafssheqgssrntesgeggy
rysnvvltscctptniggkyghfeagiiqptkscahescdnlpdihn--v
aptyvhdtka--dhldrivtakknaknmaaagseqltihes-----gkip
althlkkyc-hce-------q--csycsstgsvkncvvcydg-----qgk
vaelkefelkcglnlll--agghaatgqqglhkaayvihpldggkcclcq
cgafgdmqstkpsrtvlalpdkplqqttivrlesaiqlarg------pct
--ktrssclentlvsvng-cgtmkvsfpyfdeegaeak-qlretefwvvy
tqvnlg-------rkkalgadtaqflgyhnedhkrftaalkakclgvlci
qsrplvllgkiylpscrfgig--qvhlepgppfksfak------------
-gsrlkvcgfsdy-svyd---teqtqsgkitakgarigcid---------
----ksvrh--dllscaaffpvglt-fsntgkpglvnmvtldlhf
>ENV_HV2BE/24-510
l-------tqkigs--dalktrayerqatd--msagapkcggertakggq
d----faahiavsnqlell---rksg------tqstskmtprnrvhsegn
gydaaa-----krghlgdrtaevnnkvsnh-sklsyl-----sdlee--m
rpfsekrnnwalgefqrsamssnvk-----------ylsqt-----hdvr
dlafdltfashcgqvdgvcik--cgdcgl--dvtsasdvypalilc-qce
---vweaglicahsfak--tltnvqvm---sdftiyilpslpgggccgcn
lgpvrkrklqsvtlatialagtdeetfawehlvcisdlaktgallrs-vl
gnkwktelmssng-aitsncvtfslymshll-ttlegkmfdesreqpvvf
dgayae-------dshilvgitlelagaragqimqfysgfeakcmdtlcy
dkaklilcekafygtctvevpafqeklnlgtepkvina------------
-enyiriamcreqlpvcn---iqrtyethacakggvllcrkgceggladq
fiakdfvqnvkypinaetdmplgav-htirgtavwsvktkpdiff
>ENV_HV2G1/23-502
l-------tqrige--eaaktrayergptn--vsapapvcsgqntakggq
d----faavvavptqldlf---rktd------sqttnrmtrnnrghtdgn
gygana-----gkghladktaevdaksgnq-kklayl-----sslqd--k
rpyvdkrdewdradfqraasassvkkt--nvtqqdiylkqtiagpghdvr
elayllkfsahcsavdgvcik--sgdcgl--qltsalnvyptldlc-qcr
---vyeaglvchhnfav--tvtevqrt---seitiyivavlpggdccgcn
lgpvskkkltyrttasislagtdldtfafshlvcvsalakqgallrssvl
gnkwkselmtphghsidgsciafglyishfy-ttlqsamfdeskestkvf
pgayge-------eahilakitlelasasagqiveyysgfnakcmetvcy
dkaklilsekhffgtcevqvtafqeklqlgtdpevinh------------
-ndyikialckeqlptfn---aqrsyathgsrkggpllcrk---------
----gfvhnanypanvethnplgaa-rvikssavysvrskpniff
>ENV_SIVV1/24-538
l-------raamdg-ghaqsel-lgrdvaa--aagaglgcplptretngd
t----ndr-mhnn--felvedvraciftttsfkateesaprnddgh-kgq
afdatp-----nkpplayragscdaqtvtg-eeltmngcgpfappaq--v
kafygrkfaw--aslepissag------aavakpdlakagn-----sqna
hlvgalayt-hcall----ie--nvycntdgevakclaiygh----gqyq
---vkegelicplltqe--tinpsesg---ceptpyavgfvnggkaclc-
kspfrrlqlgpvgspksclvdttadieaigelpsitglseg------pvt
sdkvrtslfnemlvalanlcgglthflqylh-tdlegk-vlkekdywviy
heacvd-------dqpvlgmetiemlarkddhtthydttfqdecigamcf
dkssivvygsaylascpvmvt--qkavppsedlensshngaafitdgidf
cersikicdcehffprytyelsqtyyafkakekgaglscrs---------
----hrtrh--galpigthfklgep-rcitgkteyvqktgeplff
>ENV_HV2CA/25-512
l-------tekigd--edaktrayerqatn--mspgepscsgqnfpkggq
depekvaaviavgnelelf---kktg------sqstnmmnrhtkgpqdgn
gfqane-----ernhlpdktaavdgdagnh-pklnyl-----aalqe--m
rpfvdkrndwaraefrraawtsnvnkg--ngtqediylkqt-----hevr
elaylfkfsahvsrsdgvcikdlsgdcgl--nlataldvypglnlc-qcq
---vynaglicehvsal--svtavrkt---sactiyivgalpggaccgct
lapvrkkklgwittatialagtdldtfawehlvcfhnvartgallrspvl
ghkwktelmtsnghavdgtciafsayvthfy-kpleselfddnkessigf
pgvyaq-------eshtlgkitfdlstgsagevvrfytgfnakvmgelty
dkaklivfekaffgtcalqvnasqekidlagdpkvynq------------
-enyikvamckeklptye---tqssfgthvsvkegvllcrk---------
----sfvqnadlpinveghmplgac-rcikghavnsvmskpntff
>node8
l-------ratvge-andakel-lgrevaa--peaaasnctlesaansgk
t----ysg-ihns--lelv---recaftngkfrptqenisrnneghtkge
kfdgtt-----kknsltsrtgacdpqtitg-qemsmpgcgpynpfhe--v
spfydrkinw--aefqtmvspdsvektvaaiaspeiarktt-----eeag
qlvrmlkyc-hcsel----id--agfcnlnadvarcigiygg-----qcq
---vyeaelicallfqv--tvtptdtg---cevtpyavglvsggkcclch
sgpfrrlqlspvsspamclvdtslniqaisklacvadltkg------pvt
gdkartglfdnklvaidglcvgftvyfqyfh-tgldkk-aleereywviy
hdnyvd-------gepvlgmdapellgakaghtdhydstfqgecmnalcf
dksalvlngkayfpscvvmva--qtslspgedleginh------------
-errihicvckhflptyt---sqrsygfkasdkggqlscrs---------
----qrvrn--yalpvgahfplgap-rcikgkteyvhktaepiff
>node7
l-------ratmge-skaasel-lgrdvaa--qegaalnsplsspansgk
t----ngg-ihds--lelv---recsftnkkfkpteenvprdddgh-kgq
afdgts-----nknslasragacdaqtitg-eeltmpgcgpynpshq--v
kpfydrkisw--aslqpivspesldhtvaaiaspeiakasn-----sqaa
qlvgmleyp-hcsll----id--agfcntntdvsrclgiygg-----qcq
---vyegelicallvqi--tihptdtg---ceptpyavglvsggkccvc-
sgpfrrlqlgpvgspakclvdtttniqaisdlacvaglteg------pvt
gdkmrsalfddrlvcigalcvgltvylqylh-tglegk-aledkdywviy
hdtcvd-------nepvlgmdaaellgrkaghtqhydttfqgecmnafcf
dkssivlygsaylascvvmva--qktlfpgedlegrshnghafitdgiaf
cersihicdcehflpryt---sqssygfkakekggalscrs---------
----qrtrh--aalpigahfplgep-rcikgkteyvhktgeplff
>ENV_HV2D2/24-513
i-------sqgigdhnqgaktrayekqsllltiaagasrcfgqntakggl
d----fka-iavsklleil---kqtg------hqstdimvrtnhghadnt
gfngga-----kkghqddkiadfdaktgnh-pgicyl-----gafqe--m
rpyvdrrieraqgafertasassvd-y--nvtrqelymkqt-----hdar
qlayllkfsahchmldsvcve--sadcgl--qltgsigsypdlnlc-qsi
---typdglicapsfai--tltavvrt---seitmmivavkpsteccgce
lgsvrtkkitsisaglveltgtaldhygfshllcvsdlekagqllrepai
gakwttelmdsgchalgatciafplyvthfy-naldtnlydeaaesgmvf
pgaypr-------sshilgsiilelhsasaghivhyysgykakcknnlcf
dkaklilsdkaffgkcatq-----gklnlsvkpkaikn------------
-dnyitiflckiqlptyn---pqrkyatsrsnfgdvllcrr---------
----sfvhnadypinvethlplgas-rsakgdavhevkgkalkff
>ENV_HV2D1/24-501
l-------aqtige--eaastrayerqatn--msagaercsgqhtakgsq
d----fpahsavskdlelf---rdtg------sqstnkmsrhkrghtdgq
gfdaka-----nkghladktaevdakggnh-pklsyl-----salqa--m
rpfrekrnewalgefqraasstdvrkt--gvaqqdiylkqt-----hevs
eiayllkfaahcgrvdgvcik--cgdcgl--dvthavdvyptlslc-qcq
---vyeaglicecgfsvthtvtavqka---seisiyikaslpggsccgcn
lgpgqknklksvtfavialegtdldtftwehlvcisdlaktgallrsqvl
gnkwktevmssnghaitgkcvafslyishfl-ttletkmfgearessvvf
egayag-------eahilvkitlelngasaghilqfy-gfnakcmdtics
dkakmilsekafygtclvqvtafqeqlnlgtdpkvlnn------------
-enyvkiglckeqlptyn---tqrsyephaskkggvllcrk---------
----pfvqnakypinaekhlplgmv-rvirgsavwsvkskpnvff
>node9
l-------sqkigehqdaaktrayekqats--psagaprcsgqdtakggk
d----yag-iqvgtqlnlf---rkcg------rqsadmmyrhnhghtdgt
gfegna-----kknhladkaaevdpktgns-pklsfl-----galqd--m
rpfvdkriewseaefqkaasaskvkkt--nitqddvclkvt-----hevr
elayllkfcahcsqlagvcvk--sgdcgl--qmtsafnvyptltlc-qcq
---vyeaglicahsfav--tvtpvgrt---seitiyivasvpggdccvcn
lgpvrkkklapvtsatvalagtsldtfafshlvcvadlakagsllrspvt
gakwktelmeskghaidgtcvgftlyishfy-ttleskmydedkewsvvf
pgayge-------espilgkiilelisasaghashfysgfnakcmdtlcf
dkakliltekayfgtcvvqvt--qeelnlgadpkvinh------------
-esyitialckqklptyn---sqrsyatnasnkggvllcrk---------
----ssvqnanypiavetqlplgaa-rcikgnavysvksksniff
>node14
l-------tqkige--daaktrayerqatn--msagaprcsgqntakggq
d----faahiavstqlelf---rktg------sqstnkmtrhnrghtdgn
gfeaka-----krghladktaevdakagnh-pklsyl-----salqd--m
rpfsekrnewalgefqraasssnvkkt--gvtqqdiylkqt-----hevr
elayllkfaahcgqvdgvcik--cgdcgl--dvtsavdvyptltlc-qcq
---vyeaglicahsfav--tvtavqka---seitiyivaslpgggccgcn
lgpvrkkklksvtlatialagtdldtfawehlvcisdlaktgallrspvl
gnkwktelmssnghaitgtciafslyvshfl-ttleskmfdesressvvf
egayae-------eshilvkitlelagasagqivqfysgfnakcmdtlcy
dkaklilsekafygtcavqvtafqeklnlgtdpkvinn------------
-enyikialckeqlptyn---tqrsyethasskggvllcrk---------
----dfvqnakypinvethmplgav-rvikgnavwsvkskpniff
>ENV_HV2NZ/24-502
q-------tqeige--stastreyerqaan--msagapscsgqntpkggq
g----fgaeiavtdqldlf---rktg------sqesqmmtrhyrghtdgn
eheete-----krnnlndmtatvdakagnh-aklsyl-----salddpqm
rpfiskknewaraafrrlasasnvkka--nhtqqdiylkqt-----hevr
glayllkgaahcrkvkev------vdcgl--elttaldvyptanlc-qcq
---vykagvicahsyav--avtgvqrt---seitiyivgalpggaccgct
lgpvrkkklsevttgtialagvdldtfawdhlvcisglaktgallrspgl
gtkwktelmsrnghakegtciafslyvshfy-gale-kmfeet-gssvvf
pgvygekpnfrqcehhilekityelrggsagevvqfytafnakcmgelcy
eksklivfekaffgacavqvtqsqakldlsnipkvilq------------
-esyikitlckeklpsyn---tqrayeehasvkggvllcrr---------
----sfvqnadypvnveahmplgav-rlvkgnavysvkskpnnff
>ENV_SIVG1/22-522
l-------rgalnd-nktasdl-lnadvqa--eegalinsplsipaspgk
t----ggg-ihds--qelv---recnfankkf--teekvprdssgn-kaq
afsgtd-----eknslasragacnataltq-aeltmpgcdpynpshq--v
kpfyerkisw--sslqpivtpnslnhsvaeiaspeiaaakn-----sqaa
qlvgmleyp-hcslv----vh--ngfcntntevprclmiygg-----qcv
---vyegelicallvqi--kipptdag---ceptpyavglvsggkccvc-
lgpfrriqlspvggpakclvdtttdiqaisilacvaglteg------pvs
gdkgrsdlfndrlvcigplcvgltlylqylh-tglegq-aetekeywviy
hetcvd-------d----gmdivdllgrktght-hyettfqgecmnafci
dkastvlygsayltscvetva--qftlirgedlqgrshdghafitdgidf
ckrdvytcdcehflpryt---sqasygfkakeksgalscrn---------
----qrtrh--evlpigahfpigdplrckkgktvyvhktgeslyf
>node10
l-------tqkigehteaaktrayekqatn--vsagaprcsgqntakggq
d----faa-iavstqlelf---rktg------sqstnmmtrhnhghtdgt
gfegna-----krghladktaevdaktgnh-pklsyl-----galqd--m
rpfvdkriewaqaefqraasasnvkkt--nvtqqdiylkqt-----hevr
elayllkfsahcsqlagvcvk--sgdcgl--qltsafnvyptlnlc-qcq
---vyeaglicahsfav--tvtavgrt---seitiyivasmpggdccgcn
lgpvrkkkltsvtsatvalagtsldtfafshlvcvsdlakagtllrspvl
gakwktelmesnghaidgtciafslyishfy-ttleskmydeakessvvf
pgayge-------eshilgkiilelasasaghivhfysgfnakcmdtlcf
dkaklilsekaffgtcavqvt--qeklnlgadpkvinn------------
-enyitialckqqlptyn---sqrsyatnasnkggvllcrk---------
----sfvqnanypinvethmplgaa-rcikgnavysvkskpniff
>node11
l-------tqkige--eaaktrayerqatn--vsagaprcsgqntakggq
d----faahiavstqlelf---rktg------sqstnmmtrhnrghtdgn
gfeana-----krghladktaevdakagnh-pklsyl-----salqd--m
rpfvdkrnewaraefqraasasnvkkt--nvtqqdiylkqt-----hevr
elayllkfsahcsqvdgvcik--sgdcgl--qltsalnvyptlnlc-qcq
---vyeaglicahsfav--tvtavqrt---seitiyivaslpggdccgcn
lgpvrkkkltsvttatialagtdldtfafshlvcvsdlaktgallrspvl
gnkwkselmssnghaidgtciafslyishfy-ttleskmfdeskessvvf
pgayge-------eshilgkitlelasasagqivqfysgfnakcmdtlcy
dkaklilsekaffgtcavqvtafqeklnlgtdpkvinn------------
-enyikialckeqlptyn---tqrsyathasskggvllcrk---------
----sfvqnanypinvethmplgaa-rvikgnavysvkskpniff
>ENV_SIVM1/24-528
l-------sqkigehqdaaktraydkqats--pnaaaprcsgqdtakgvq
d----yag-iqvgtqlnlf---qkcg------rqaadmvyrhnrghtkgt
gfeaka-----rknhltqpaaevdpktgns-pklsfl-----galqa--m
rafvdkriewsqeefqktasaskvkkt--nithddvclkvr-----hevr
elvyllkgcancpnaagacvk--sgdcgl--qktseynvyptltlc-qcq
---vyeagiicahsfav--titpvgrt---aditiyivssvpggdccvcn
lpplrkkklkpvasatvanagtsldsfafshlvcvadlaksgsllrspvt
gakwkselneskgdaidgtvvgfalyisdfy-gllesemyned-ewsvvf
pgaygq-------espilgkiilefirasvghastffsalnakpmdtlcf
dknkliltdkaifggavvqvk--eeelnlganakvinh------------
-aayiaislckqklptfn---sqrsytsnanakgggllckk---------
----asvvnanypisvesqvpvgea-rcikgnavysiks-----y
