>node9
-------------yq-eprsyeiytgtp----whatelcvgqkye-ydrs
ksa------pedfaslai--ayakp---wsthfgkqltkftwvalatyki
akqsplqrsinqdkpnklhfvsqnck-elrlgskmhktfnkgnlayavmg
aarsyk-t----pe--v-n--ggst-lprlnstyv--fkaaaghaw----
-----pkksldsdkghe-----n-ceqdagktsgqnhgre-----svngp
ysdenpfarytmgqklslnsampvvqaqn--innqtfgalskhktgesky
cgcl----virptshv---ipdlsdefnpsrsslhkersevvdrcnlfk-
kpsaa--gstysldvkpdflttlyfhagpm-idklveppgvksqvlqltk
agvakgll-----ampnsleylgpkisvsn------lagvaadgvkyk--
---------ktsqksprtcspvlgq----advhvefqfglnlsktqhkk-
-vsccdsilpakfcrrpkdedrtneeasndqlaqr-it----ggafnccf
dylyvtqnvgaklcndfyhhgtsepkl--viiqkveqekacgkypkallg
gsr
>node11
-------------yq-eprsneiytgtp----whgtelcagqkyg-fdrs
ksa------penftslav--ayatp---wsthigkqltkftwvalatyki
tkeaplqrsisedkqaiqgfisqnck-elrlgykmhktfnngnliyaimg
aarsyk-t----pa--v-g--agtn-lphlnstys--fkaaahhawfmdd
sgnihpkksldsdnghe-----e-deqdggkasggnhgrn-----tvngp
yadenpfarytmgqklslnsafpvvhpqn--snshtfgslskhvtgesky
cgci----virptdhv---ipdltdefnpsrspthkdrseavgrcnlfa-
kpaaa--ggsdsldvkpefltalyghaepm-idklvdqpgvksqvmqlvk
agvadgll-----efpnnleylgpkisvsn------lagqaadgskyk--
---------ktsqkspracspvlaq----sdvhlqfqfslnlaktqhkf-
-vtccdsilpakfcrrpkdadittedeandqlaqr-it----ggtfnccf
gylyvtqsvgaklshdfyahktsepkl--vilqkveqekacgkypkallg
gsr
>ENV_HV2NZ/24-502
-------------sq-ephsnelyygtp----wrgtdlcagekyg-fekr
ksa------tenftslgv--pfetp---wsvnvgtqlpkftwvlladyki
tkestlqrsikenkqadqgfmaqnck-dlrlgfrthktfnngglifaime
aarsak-a----pa--v-g--agvn-lphlnstks--fkaadhnswmleg
agnihpkkslavqnghe-----e-dgqdrgkasggshgrt-----svngq
yaqnnpfrrytmgqtleldnafpvvqpqs--gsthtfgkknqhvtgdsky
cgci----vvretehe---epkladefepssspthknrtssvgrcnlfa-
spgqg--ggsnasdvkpefltalygqadpm-idksiqqpgvkapvmqlvk
agvidgll-----efpldleylgpkisvsk------lageaaigtkyk--
---------ktgesgprnctpvlap----sdvhlqfqfslnlaktqhkf-
-vtccesilpgklcrrskntdvttedeaenqlasr-vt----agtfdccw
gylyvtqsvgtklshdfyshkasdpkl--vilqkveqqkacgpypmalla
gir
>ENV_HV2CA/25-512
-------------ye-eprsneiytgtp----whgtelcaglnfg-ydrh
ksa------prnfaslpv--ayktp---rstkiggkltiftwvvladhki
tkeatlqrkimegkqaiqvfmsqnck-dlrlgyrmhktfnngntihaime
aarsyk-t----aa--i-s--natn-lphlnstya--ytaaakhgwfmda
hgsihpkpsldvqdghe-----e-eaqdggkssggnharn-----tvngp
yadegpfmrysmgnklalgsafsivkpas--dathtfgglakhvtgasqy
cncl----viratdhs---iptltdefnpskspthknrssaagrcnlfa-
tpaas--skstaldvkpdyltalygpdeam-idklldqpgvkahvmqlvk
agvadall-----qfpndleylgpkvsvdk------fpaqaeegskyk--
---------ktsqksprscspvacqaphgsevhlpfqyslnlakthhkf-
-veccssvlpqkfcrrakdtdvttedaankqltqi-it----ggafhccy
gylyvtqsvgaklrrsfyaqktsepkl--iilekveeekvcgkyakgllg
gsh
>ENV_HV2D1/24-501
-------------yq-eprsneiyasns----shdtdlcpgqkyg-ydrh
kqa------pdnfnslav--ayssp---wsthigkqvtkftwvafpsyqi
aneaplqrplsedkqaiqgfiaqack-elrlgfklhktfnngkliyaimg
gnrsyk-t----aa--v-g--adtn-lahlnssys--fgatshhawfmed
qgnihpkkslqrqnghd-----evdeqdggkasngnhgrn-----avngp
yadekpfdrytmgqklsfnkgfpvvhpqs--nnghslgslnkhvtgaeky
cgci----eikpthhe---vpdlkdefnpsrpatlkdrtevvgrcnlfa-
kpaag--ggsdkldgkpefltalyghanpm-veklgdqhgvnaqvmqgvk
agvddgllttkvkefpddleylgpkvevgn------lngqaadgskyk--
---------knankreracspvlnq----ndvhiqfqfslnlaktpqky-
-itcchsilpgkfcrrp-dadvtppdeandqlggr-ig----ggtfschf
gylyytqsggsklrhesyasktttpkh--vilpkveqekacgkypkallg
gsr
>ENV_SIVGB/47-569
-------------fkpsdkknakgvaldi------gtfkinckfhgfdkg
tgkmycyemvqtftgvvafyradkkaaywqmvydkkaah-mfrgtsryal
svaqdgkr-tgmrda-klvasvcactieefgaadiqktvpegglgkqdrs
yverltfi----ep--g-gpdggccpltklletyltthpddpslgw----
-----mkrrrha---gdfalgkg-np------hdvkdihavtalgnghst
alkltppnyyflgikavv-------kdrd--lscemtavvkkvkaqgpky
ktvl----vvpsnaaa---stdvltlvreagvylhkydqhvicqcelplk
wcqyf-kcelnelselpsfgertykelgnaksvrlvypdepgrpivstka
agvleeqa-----dlsgvlqvvgdsdykvweksnfilqpkkltvdadlsp
edkkqacragkg-tvsdncndival----savhkepemglgpsgklqete
vtfccdrsapmnffrcpkp--dkkvanqvksrdkm-lg----ediiglst
e-------q------------mfdpskpegaytgyiqskddgrdagillq
ceg
>node18
-------------yq-eprsneiytgtp----whgtelcagqkyg-fdrh
ksa------pdnftslav--ayatp---wsthigkqltkftwvalatyki
tkeaplqrsisedkqaiqgfisqnck-elrlgykmhktfnngnliyaimg
aarsyk-t----pa--v-g--agtn-lphlnstys--fkaaahhawfmdd
sgnihpkksldsqnghe-----e-deqdggkasggnhgrn-----tvngp
yadenpfarytmgqklslnsafpvvhpqs--snshtfgslnkhvtgasky
cgci----virptdhe---ipdltdefnpsrspthkdrseavgrcnlfa-
kpaag--ggsdsldvkpefltalyghaepm-idklvdqpgvkaqvmqlvk
agvadgll-----efpndleylgpkisvsn------lagqaadgskyk--
---------ktsqkspracspvlaq----sdvhlqfqfslnlaktqhkf-
-vtccdsilpakfcrrpkdadvttedeandqlaqr-it----ggtfnccf
gylyvtqsvgaklrhdfyahktsepkl--vilqkveqekacgkypkallg
gsr
>node10
-------------yq-eprsyeiytgtp----whgtelcvgqkyg-fdrs
ksa------penftslav--ayatp---wsthfgkqltkftwvalatyki
tkqaplqrsisedkpnkqgfisqnck-elrlgskmhktfnkgnliyaimg
aarsyk-t----pe--v-g--agtg-lprlnstys--fkaaahhaw----
-----pkksldsdnghe-----d-deqdagktsgqnhgrn-----tvngp
ysdenpfarytmgqklslnsampvvhpqn--tnnhtfgtlskhvtgesky
cgcl----virptnhv---ipdltdefnpsrsplhkerseavgrcnlfa-
kpaaa--gsthsldvkpefltalyghagpm-idklveppgvksqvmqltk
agvadgll-----empnsleylgpkisvsn------lagqaadgskyk--
---------ktsqksprtcspvlsq----sdvhvefqfslnlaktqhkm-
-vtccdsilpakfcrrpkdaditteeesndqlaqr-it----ggtfnccf
gylyvtqsvgaklcndfyahktsepkl--vilqkveqekacgkypkallg
gsr
>ENV_HV2G1/23-502
-------------yq-qprsneiytgsp----whgaelcagqkyg-fdra
kav------aenftslav--aystp---wssqigsqltkftwialatykf
tkeaplqrsiseakeaiqgfisqnck-dlrlgykvhktfnhgnliyaimg
aarmcr-t----ef--v-g--ggtn-lphlnstys--fkatahhawfmde
sgnihpkkslesdnghe-----e-deqdggkatggnhgrn-----tvngp
yaeenpfarytmghklsinaafkvvhpqn--ansptfgslskhvtgqsky
cgci----iirptehp---ipdltdefnpsrspthkdrseavdrcelfa-
lpaas--sasgslavkpefltalyghpepm-ieklvdqpavksqvrqlik
agvadgll-----efpgnleylgpkisvsn------lagqavdgskyk--
---------ktslksqracspvlaq----sdvhlqfqfslnlaktqhk--
-vsccdsilppkfcrrptdadvntedeandqlkhk-itkkrlggtfnccf
gylyvtqsvgakmsqdfyaqktfepkl--vilekveqdkncgkypkalfa
gsr
>ENV_SIVG1/22-522
-------------ft-ewrehqketgvaitvslatpclvvackfh-fdrg
naaky----mhtfaslpq--nfakp---wnsvllkhlekpkwlgltsykl
sgdsadkr-lvkvkqhmqhfsgdsck-alilgnrslkifqlkvlgldikg
virpie-i----af--m-sqrgspa-isrlnevyveqyteaqshgw----
-----pktdqes---hd-----g-chrgtgkngplhsgrq-----paagp
nwqrivlsahaqgssvdvpntlqaldpqe--vdkqmygtvfynaavgedt
egcl----vlgtstngg-fadqilnglkpapfflhteptetvarcsvgl-
wpisvl-aesydldtmprfgdslylhglpe-vgklfqpasvnhhvleilk
kghykavl-----plsnvfeylgekvnvcn------lhstgapgvrye--
---------ndg-tdmslcsdgegt----sdrhsefklglgqsntvqkl-
-agccdgdlpkrfpncpnneprsrnkskedrkkqr-ia----ealvdhcl
g-------mtitwcgeffphgrtaasa--gvytakdnlgsngqipkvlld
tse
>ENV_HV2BE/24-510
-------------yq-eprcseiytgng----wqgvelcagqkyg-yarh
sss------penfsslsv--ayttp---wsshagnqltkftwvaftkyev
theapaqkalsedkqaiqgfisqtck-dlklgykmhksfkngklayaimg
gvrnck-t----pavtvsg--agtn-lphmnstfs--fkaaahhawfiea
sgnfhpkkgldrqdshe-----evdeqdggkaspgkhgrn-----gings
yvdedpfakykmsqklsldgnfpvvhpqs--snshsfgslnkhvtgknky
sgci----viaptnhd---vpdltnefnpskspthkdrseaqgkcnlfa-
kpsag--ggsdsldikaefltalyghaipm-vhkltdkpsvkgqvvkmvk
asva--------------ldylgpkinisg------lagqaadgskya--
---------kygkkspracspvlae----sdvhlqfsfsldlgktqakf-
-vtccdsilpalfcrkpkdsdvksedeanavlagk-ig----agtfdcsf
gylyytqsvgsklrhdayghktstqkl--vilqkvgpertcgkypkallg
gsr
>node14
-------------yq-eprsneiytgnp----whgtelcagqkyg-ydrh
ksa------pdnftslav--ayatp---wsthigkqltkftwvafatyei
tneaplqrslsedkqaiqgfisqack-elrlgykmhktfnngkliyaimg
garnyk-t----aa--v-g--agtn-lphlnstys--fkaaahhawfmed
sgnihpkksldrqnghe-----evdeqdggkasggnhgrn-----avngp
yadenpfarytmgqklslnsafpvvhpqs--snshtfgslnkhvtgasky
cgci----virptdhe---vpdltdefnpsrspthkdrseavgrcnlfa-
kpaag--ggsdsldvkpefltalyghaepm-vdklvdqpgvkaqvmqlvk
agvadgll-----efpndleylgpkisvsn------lagqaadgskyk--
---------ktsqkspracspvlaq----sdvhlqfqfslnlaktqqkf-
-vtccdsilpakfcrrpkdadvtsedeandqlagr-ig----ggtfnccf
gylyytqsvgsklrhdfyahktstpkl--vilqkveqekacgkypkallg
gsr
>node17
-------------yq-eprsneiytgtp----whgtelcagqkyg-fdrh
ksa------pdnftslav--ayatp---wsthigkqltkftwvvladyki
tkeatlqrsikedkqaiqgfmsqnck-elrlgyrmhktfnngnliyaime
aarsyk-t----pa--v-g--agtn-lphlnstys--fkaaahhawfmdd
sgnihpkksldvqnghe-----e-deqdggkasggnhgrn-----tvngp
yadenpfmrytmgqklslnsafpvvhpqs--gnshtfgslnkhvtgasky
cgci----virptdhe---ipkltdefnpsrspthknrssavgrcnlfa-
tpaag--ggsdsldvkpefltalyghaepm-idklvdqpgvkaqvmqlvk
agvadgll-----efpndleylgpkisvsk------lagqaadgskyk--
---------ktsqkspracspvlaq----sdvhlqfqfslnlaktqhkf-
-vtccdsilpakfcrrpkdtdvttedeandqlaqr-it----ggtfnccf
gylyvtqsvgaklrhdfyahktsepkl--vilqkveqekacgkypkallg
gsr
>ENV_SIVM1/24-528
-------------yq-epssveiylgtp----whatelcvgekye-ydrs
ksa------rdgfislai--ayaqp---wsnnfgkqltkfnwvalgteki
akqsplqrtipqekpnklhfvsencq-elrlgskmhatf-kgnlayavsg
largyk-t----pe--v-n--ggtk-lprlnstfv--fseavghaw----
-----pkrsldsdkghs-----n-caqtagktsgqnhnra-----svsgp
ysdenpftryilgqklslnnampvvqaqn--cntqsfgalgkhktgesky
cgcl----qirptsht---ipdlseefnparsslhkekcevvdrcnlfk-
rlnat--gstysldvrpdalttlyihtdpm-gdkliepagvasqvltltk
adiakqll-----ampnsleylgpkisvsk------lagvgadgvkfr--
---------kisqksprtcspvmgq----advheafqfglslaktrhkk-
-vsccdsilpakfcrrpkdedrtkeeasndqltqrgit----ggafnccf
dylyvaqnigadlcnnfyhhetnepkl--viiakveqekacgtypkallg
gsr
>ENV_SIVV1/24-538
vnycaqfrqsyeqfv-awsnhanaegppntassvspglmvickfg-felg
npgky----shtfaslvh--nfrkp---wnsvagkhlekphwkvsekykm
raqcshkk-liqikadllhfnsdscg-eveldqrkqkifqlkvlgmgrrg
fikpie-ktkmplf--g-nergghi-ltkgnevyvdeefnvgshaw----
-----kkteren---he-----g-chrskgrsailhtdre-----psagp
nyekyplnayalgsavaiphalpplesqetdvnkqiydsvfyneevgpky
egcvvfew--gtnanggcfvdqilhgvkpapfhyhtaptqkmpscrtgl-
wpiy---------etlphfgddlymhggpq-mcklfap----hhalevlk
kgnykavl-----rlntifdylankthvcn------lsasgangcayk--
---------svg-temnlsadgkgt----adrhtgfklglgqrkslqkl-
-rsccggvlprrfcdkhedeprsreqttderkklk-vs----ealsdlcv
p-------msitwsgeffpqgratpsg--g--egkqalsgkgqvpsilfa
tyd
>node7
-------------ft-dwrnhqkatgvaitvswaspslvvackfh-fdqg
naaky----shtfaslvq--nfakp---wnsvslkhlekpkwlglakykl
sgdlshkr-lvqvkdhmlhfsadsck-elilgqrkqkifqlkvlgldirg
firpie-i----af--a-nqrgsha-itrlndvyveqftetpshaw----
-----pktdres---he-----g-chrstgrsgvlhsgrq-----paagp
nwqkvplsayalgssvdvpntlpalepqe--vdkqmygtvyyneavgeky
egcl----vvgtstngg-fadqilngvkpapfflhteptetvarcsvgl-
wpiyv--gdsydldtmphfgdelymhggpq-vcklfqpagvnhhvleilk
kgnykall-----slsnvfeylgdkievcn------lnatgasgikyk--
---------gdg-tdmslcsdgagt----sdrhtefklglgqsksvqkl-
-asccdgvlpkkfcncpnneprsrnkskddrkkqr-ia----ealadlcf
a-------mtitwcgeffphgrstpsa--gayaakdnlgsngqipkvllh
tse
>node19
-------------yq-eprsneiytgtp----whgtelcagqkyg-fdrs
ksa------penftslav--ayatp---wsthigkqltkftwvalatyki
tkeaplqrsisedkqaiqgfisqnck-elrlgykmhktfnngnliyaimg
aarsyk-t----pa--v-g--agtn-lphlnstys--fkaaahhawfmdd
sgnihpkksldsqnghe-----e-deqdggkasggnhgrn-----tvngp
yadenpfarytmgqklslnsafpvvhpqs--snshtfgslnkhvtgasky
cgci----virptdhv---ipdltdefnpsrspthkdrseavgrcnlfa-
kpaag--ggsdsldvkpefltalyghaepm-idklvdqpgvkaqvmqlvk
agvadgll-----efpndleylgpkisvsn------lagqaadgskyk--
---------ktsqkspracspvlaq----sdvhlqfqfslnlaktqhkf-
-vtccdsilpakfcrrpkdadittedeandqlaqr-it----ggtfnccf
gylyvtqsvgaklrhdfyahktsepkl--vilqkveqekacgkypkallg
gsr
>node8
-------------ft-errthqiatgipisa-waspelcvgckyh-fdrg
ngaky----seafaalia--nfakp---wesvyakniakpkwlglakykl
sgelsnkr-igqvkehrlhfstesck-elflgerkhkifqlgalgldirg
firsye-t----ks--a-nqrggsa-ltrladvyvaqftetpghaw----
-----pkqdhes---he-----g-chrdtgrstvlhrgrq-----pvagp
nwnktplsaytlgdsldvpttlpaleaqd--idrqmygtvnynkavdqky
qgcl----vvgsttng---ppqvrdlvkpapfflhteptevvarcsvgl-
wpmyv--gdsynldtmphfgdalymhvgpq-vcklfeppgvnhhvlelmk
egvykall-----tlsnvfeylgdkisvcn------laatgasgikyk--
---------gtg-ttmstcsdvaga----sdvhaefklglgqsksvqkk-
-asccdgvlpkkfcgcpnneshkredskddqkker-ia----dglvdlcf
e-------laatwcgeffphgssspna--gvyatnenekstgkvpkvllq
gse
>ENV_HV2D2/24-513
-------------ye-qcrsygiysgta----whgtelcvgqky----rt
kea------pqywavlav--ayatp---wnvhfdrvvvkvtwlalatlki
tkqgaldrgtafdkpnkqgfvslyck-dllissklfktfnkgyliyavms
aaknyk-t----pe--i-g--agtg-lpivgsgys--fknaahhar----
-----pkksidsenghk-----d-dvqdagkvsgqdngrs-----tvngp
psdgkpfarstmgqklsltsavpvgspsh--tndhafgtlsmh---epny
cgcv----airptnhv---ipdlkdefnpsraplqkekdeplghcllfa-
ketaa--gstesldvkpeflaglyg-lgpm-idklvephsvkcevvqlsk
saaaagll-----ampttmeylsfkitvgs------iagqaadnskyh--
---------resqkstkpcapv----------hvdfqftinanktqhkm-
-iaccdsilaakfclvaknaditgnlepndhvsqr-ia----gatfnccg
eyldvaevigaklcndfythkkkqprl--vylqkaehekackk---tlig
gsk
