>ENV_HV2CA/25-512
elavpkrtc---------------------------allnlgh-----hd
aeaptipyptcfnephrqstf-----------wesvhhvvellia--lee
lytafallmn--vfpekgd---pqkqeatkslctrmhepqrhleagfyik
pkredaitalrdnfkpp--gqlqihd------lil--allqhedcfnckq
mgerq----qhgmrgtaftgqekkdv--csfltaek---qktladsgdaa
degahiegctagvhtpsggsvfpgc-----lktplklkptk--trqpgel
veh---kggstrchwstcqlslndgvvtdekdyalsvmwngqsvaettlq
qlke--npftvsneyvtipkl-hkekn-vg-atqsqqtttv-a--feslv
----gg--lrga-----klassqeraafgghn-llattft---pdvvlgt
gmsgvkhst---dpfllvqiahpvksetfttldkteevvnlytkpsyliy
tdeltlgqgga---slmcclkyrlrmgwgdgagnrcnkgaivapdlrgmk
taga-pkdtkifg------ystrigaatagadgtcasvscnm--haev--
--evcde--kllg--epqepmg
>ENV_SIVGB/47-569
g-------ciaqglrkaykv--ychsaee-------ailkvas-----hs
tkdtvcdrakylld---vghl-----------rk----glgvllr-----
fcieqtalmg------srgatitqieaplrgvsvgreaeggalgvtlare
kdhknpglaalsaahhr--vyadtsq------ppf--naqfanscytskt
----plysphmgrkna-gfhmltkkkqlvlgmligspfgvgn--------
sagrnvagcsgsvk--qygitcqlapdkhlpgselqtidsv--vqnvggv
vayeaqvgaktgdyfdn-dsktka------hglvedrfvlgstilgldhs
qgrkfqthltlklcfivpspg-at--a-fstnpqyyaapchra--wyhlq
knmdlv---fdlpnslwpytkrkgeraaasvrvhhgateakyyqkrqcsy
--kdyk--dtaa--lanvdl-gpiqveklspdhghdedvrspvsst-vty
ggtleadvkfcdvkknvtaiqyiasiawtlstrktadefaervelpedae
cssleekgaksetedlll--gsslhisd---sqtcqqatahh--fgdisi
tatfckq--tysdlqytetqig
>node9
nanvpkrtcesaaqqglskvrdsceckqigkviapfalvklgh-----hn
aksptiaypscfhqrrkdskf-----------we----vvdltla--lde
fydafallma--vfsdkgdlvvpmkqeatkgvttgmhepqkalgsgfyvk
kkradvivalhddimpp--tqleihn------lvv--avnnrmdcfncse
----q----qvgmrgktflsqekkkv--isflqadk---lntlvdggtaa
dtgalvegctsgtqvgsggpvcpfa-----aktplklkpsv--trelgep
veh---sgnktpsnwsn-qltindgaiknqkdyalsfmwagsnvaetalh
hskq--npftvndetftvprm-nkdnn-vgdksdhletttv-t--fsklv
----ng--vrgt-----pyddgqergvlgkda-lltaqst---qecvlgk
arsgvkhta---dpfllihlseplkndrfstldktqegvkllikctylvy
tdeltlnqggv---kvmcclkyrirmgwgdlqsnrcnkgaikkpdlrald
sngl-pkntkvfg------ystrigvttsgvdagcnsistal--haev--
--apcda--klls--qiqarlg
>node19
dlnvpkrtc---------------------------allklgh-----hn
aknptipypscfhqrnrdskf-----------wesvhhvvdliia--lee
lydafallma--vfpekgdlvvvmkqeatkglctrmhepqkvlgsgfyvk
kkradaitalrddimpp--tqleihn------lvl--ainhqedcfncne
mgprq----qlgmrgktftgqekkkv--isflqadk---lktlaeggsaa
dtgahvegctsgvhvgsggpvypsc-----lktplklkptv--trepgep
veh---rgrktpahwst-qlsindgvvtdqkdyalsfmwngssvaetalh
hske--npftvneesftipki-qkdnn-vgdksdhletttv-a--feklv
----ng--vrgt-----pldssqergvlggds-lltttst---aevvlgt
grsgvkhta---dpfllihiahplksdkfstldktqevvnlltkpsylty
tdelslgqggv---kvmcclkyrlrmgwgdlqgnrcnkgaiakpdlrsld
tagl-pkntkifg------ystrigvatsgadgtctsisaam--haev--
--avcda--klls--qiqerlg
>ENV_SIVV1/24-538
rssvdrkpcagsdqpklhgvrlacegads------yg-rktth-----pk
vktgvvtapsffqdk-kiakvlsgkfhrlddpwd----pvgimldkhlep
fcktlttlma------sagaliptrqdafrhmslgqkdqrrclghgllvd
tkgkenqvnllhgimpeen--------------nf--dineksdpcscmk
----h----qvtskqsgsidhqkktn--viflvlsk---lagmlqgmaaa
avaravrncetveqsnagvsvtnfg-----vkshtkltnsv--ttelgks
tea---nidkepawypn-qlqqngapllnvkgsapgfkllgqnilidala
dtkr--cklfitktslepqak-gv--s-vgeiheegaykynqp--fykel
----mrfcvrga-----pfedektkvplahetlpmgasatgnvhgccldy
tkgnlrkkn---ndlflvrv-gpltea----fnkasdsirvdikaiylif
aeelklkargy---k-irrlkyiarldwspfepadclgasqrraqrkdvt
lagk-hcddnayg----lftgtksgven---taacgsvsgak--hggv--
--hpcns--ellg--eiqlrla
>ENV_SIVM1/24-528
eanvpkrtcesaaqqgvskvkdpcdckqigkviapfalvklgh-----nd
akaatvaypscf----kdskl-----------re----mvdltlg--hee
fynafallmp--vfsdkgdlvvpmkqeatkgvtsgshephkalgkgfyvk
kkranllvalhddimsp--tqleihn------lavdmalnnrmdvfncsn
----q----qvgmrgkaflgqentki--isflqadk---lhtlvdggtaa
dtgalvedctsgtqvggggplcvma-----aktplklkesv--tremgtp
veh---sgnktpnnwse-qlsindgliknqkdyaltymwggsdvpatpmq
hsrq--npftvtdetytvarm-nkdnn-vgdksdlletatv-t--fsklv
----ng--arga-----pyddgqekevlgdda-llaaqat---qacvlgk
arrgvktta---dpfllihlsdplkndrfstldktqtggkllikcpylvy
tdelnfnqggv---gvmcclryqirmgwgdlpknmcakgaikkpelrale
sngl-pkntrkfg------ystrmgvtttgvdggcnvistal--haev--
--afceagvklls--evqgrlg
>ENV_HV2NZ/24-502
dlkvpkrgc---------------------------allklghgtnfhhk
tknetipypgcfrerhrdgtf-----------weavhhnvelfla--nee
lydaf---mnltvfpekgdlvvvmkqeatkglcfrmhepqnvlgsgfyvk
kkreeaiaamppeimpp--helevvd------lvl--aithdedafscde
mgarv----vkgmrgktfsgqekkdv--isflkadk---lkalveggdaa
dtgahvqgcksavhagaggpiysgc-----lktplklkptvrl--qpgep
veh---kgrktpahwsn-qlgindgiitdqkdyvlsvmwdgdsvaatslq
hike--nqftineesfavpkl-nkdsn-vgdksqplqattv-t--feklv
----st--vrgt-----plagsedrgvlgghn-lletcks---aqvglgt
grpgvkhsa---dplllfhpahplksekfstldktqevvnlltkksyity
ndelpleqggv---kfmcclqyrlrkgwgdlqgnrcnsgahakpdlrgld
tvgl-pknvkifr------ystsiglatsdadgtctstsasm--haev--
--pecda--kils--qpqdrlg
>ENV_HV2BE/24-510
dlnvakrtc---------------------------allklgh-----hn
ttaptipnpscfhqrnrdsky-----------wenvyhvvdliia--lde
lfdatallvk--vfpekgdlvvvkkqeategqctrmhepqkvlgsgfyvk
kkaedaitaarddfmpp---qlefhsvaampflvl--amshdeqcfncng
mgprq----mpgmkggtysgqekfkv--taflqpdk---lktlaeggsaa
dtglhvegcisgshvgsggvifesg-----lktpyklkrtv--trepgep
veh---kgrkapdhrat-clsitqgllcdqkdsslpfmwdgssegdtslh
hsge--ksfnvkeesftapkvvqrddgvvgdsndhlenhti-a--feklv
----ng--tkgt-----pldsqqergvlggen-llttcsv---kqvvlgt
grsglkhta---dpillihianplksdqfatldqtqevvdlltkptymty
tdelalaqggv---karcclkyklkmgwgelhgnrcdrgaiskvqvrnfe
taga-pkhnkifg------fsrwigvatsgkdgkctsfsaam--haev--
--avtnr--tllr--viqeklg
>node18
dlnvpkrtc---------------------------allklgh-----hn
aknptipypscfhqrnrdskf-----------wesvhhvvdliia--lee
lydafallmn--vfpekgdlvvvmkqeatkglctrmhepqkvlgsgfyvk
kkredaitalrddimpp--tqleihn------lvl--ainhqedcfncne
mgprq----qlgmrgktftgqekkkv--isflqadk---lktlaeggsaa
dtgahvegctsgvhvgsggpvypsc-----lktplklkptv--trepgep
veh---kgrktpahwst-qlsindgvvtdqkdyalsfmwngssvaetslh
hske--npftvneesftipki-qkdnn-vgdksdhletttv-a--feklv
----ng--vrgt-----pldssqergvlggds-lltttst---aevvlgt
grsgvkhta---dpfllihiahplksdkfstldktqevvnlltkpsylty
tdelslgqggv---kvmcclkyrlrmgwgdlqgnrcnkgaiakpdlrsld
tagl-pkntkifg------ystrigvatsgadgtctsisaam--haev--
--avcda--klls--qiqerlg
>ENV_HV2G1/23-502
alnvpkrtc---------------------------dllklgh-----hn
akeptipypscfhqrnrdskf-----------wesvhhvvdlsia--lee
lyeafallla--vfpekgdlvvvmkqeatkglcarmhepqkaqgsafyvk
kkradaitalqddimhp--tqleihn------lvl--ainhqedcfncre
mgpkq----klgmrgksftgqekkkv--esflqpdk---lktlaeggsaa
dtgshvekctsgvhvgsigpvypsc-----vktplklkpsv--tqepgep
veh---rgkktpahwst-qlsindgvitdqqdyalsfmwngsnvadtalq
hnke--npfgvneerftirki-qkdnn-vgdkvaqlettta-a--feklv
----ag--vrnt-----gldssqergvlggdn-llnttst---aevvlgt
grsgvkhtg---dpfllihiahllkndkfstlettqevvnlltkpsylty
tdelslgqggv---rvmcclkyrlvagwgdlqgnrcnksaiakpdlrald
tagl-pkntkifg------ystrigvavsgldgtcasipaav--haev--
--gvcga--kifr--qiverlg
>node10
nanvpkrtc---------------------------alvklgh-----hn
aksptipypscfhqrkrdskf-----------we----vvdlila--lde
fydafallma--vfsdkgdlvvpmkqeatkglctrmhepqkalgsgfyvk
kkradaitalhddimpp--tqleihn------lvl--ainhaedcfncne
mgprq----qlgmrgktftsqekkkv--isflqadk---lttlveggtaa
dtgalvegctsgvqvgsggpvcpsc-----lktplklkpsv--trepgep
veh---sgrktpahwst-qlsindgaitdqkdyalsfmwagsnvaetalh
hskq--npftvndetftipki-qkdnn-vgdksdhletttv-a--feklv
----ng--vrgt-----pldssqergvlggds-lltttst---revvlgk
grsgvkhta---dpfllihlahplksdrfstldktqegvnlltkptylvy
tdelslnqggv---kvmcclkyrlrmgwgdlqsnrcnkgaiakpdlrald
sngl-pkntkifg------ystrigvatsgvdgtcnsisaam--haev--
--avcda--klls--qiqerlg
>node11
dlnvpkrtc---------------------------allklgh-----hn
aknptipypscfhqrnrdskf-----------wesvhhvvdliia--lee
lydafallma--vfpekgdlvvvmkqeatkglctrmhepqkalgsgfyvk
kkradaitalhddimpp--tqleihn------lvl--ainhqedcfncne
mgprq----qlgmrgktftgqekkkv--isflqadk---lktlaeggsaa
dtgahvegctsgvhvgsggpvypsc-----lktplklkpsv--trepgep
veh---rgrktpahwst-qlsindgvitdqkdyalsfmwngsnvaetalh
hske--npftvneesftipki-qkdnn-vgdksdhletttv-a--feklv
----ng--vrgt-----pldssqergvlggds-lltttst---aevvlgt
grsgvkhta---dpfllihiahplksdkfstldktqevvnlltkpsylty
tdelslgqggv---kvmcclkyrlrmgwgdlqgnrcnkgaiakpdlrsld
tagl-pkntkifg------ystrigvatsgadgtctsisaam--haev--
--avcda--klls--qiqerlg
>ENV_HV2D2/24-513
nanlpkasc---------------------------alvklga-----hn
aksptvpypscfhernkdsky-----------we----lvnlilg--mde
fhdahtllma--vfaskddlvapfkqegtkglctrmhekqkalgagfyve
kkradtvtgipndillp--vqlsvhs------lvl--aiqhsedcyncnd
mgprq----elgiraktytsqdrkkv--asflkafk---hatlleagtpg
ntgvlvegcaggvevss-glvcpsc-----lktpwsakprv--araagpp
veh---sarktaahwat-qvavndggiqkpnnyrlsfmwagwnipdtalh
qfkq--npfevkdetfsipki-qadnp-tadksdhlettta-afpfdklv
----ng--vegt-----pldtsqehgflggdt-llttdca---rhvklgk
grsgvkhta---apyllihlaqgfksgsfstlgkvhekgsnllkptylvf
t-------------allcclkyklklgwgeaeagrcdkgaiaspdakpld
sdgl-pkttilft------yntrisiatagvtgtcnaisaamkqnadv--
--avcka--kll----cqqrls
>ENV_HV2D1/24-501
dlnvpkrts---------------------------sllklgq-----hn
arcptipypscfhqlnrdskf-----------wesvhhvvdliia--iee
lfhafp---k--vfperddlvvlknqesteglctrmhapqkvlgdgfykk
kkrehaitalrddympp--tqlevhnvqamaylvl--aynhqaegfncne
mgprq----llgmrgktftgpekkka--isffqgdk---lktlaeggsaa
dtgahveectsgchygsggplfpsg-----lstpfrlkrtv--trapged
veh---kgqgtpahwst-alfiddgvltdhdeytlsfmwkgasiaetelp
hgke--ntfnkkeqsfsapki-qrdnl-vgdksahietkti-a--fekiv
----ng--tsgt-----pvdsqeergvlggds-llpttca---pevvlgt
grsgvkhta---dpfll-hiahplkadkfstldktqevvaaltkpnyltf
tdelalgqggi---karcclkirlkigwgelqanrcnrgalskpdlrsl-
-agl-pknikifg------ysprigvapsgaagtctsisaam--haei--
--avsda--kllc--iiqekig
>node17
dlnvpkrtc---------------------------allklgh-----hn
aknptipypscfherhrdgtf-----------wesvhhvveliia--lee
lydafallmn--vfpekgdlvvvmkqeatkglctrmhepqkvlgsgfyvk
kkredaitalrddimpp--kqleihd------lvl--ainhqedcfncde
mgprq----qlgmrgktftgqekkdv--isflqadk---lktlaeggdaa
dtgahvegctsgvhagsggpvypgc-----lktplklkptv--trepgep
veh---kgrktpahwst-qlsindgvvtdqkdyalsvmwngssvaetslq
hike--npftvneesftipkl-qkdnn-vgdksqhlqtttv-a--feklv
----ng--vrga-----plassqergvlgghn-lltttst---aevvlgt
grsgvkhta---dpfllihiahplksekfstldktqevvnlltkpsylty
tdelslgqggv---kfmcclkyrlrmgwgdlqgnrcnkgaiakpdlrgld
tagl-pkntkifg------ystrigvatsgadgtctsisasm--haev--
--avcda--klls--qiqerlg
>node14
dlnvpkrtc---------------------------allklgh-----hn
aksptipypscfhqrnrdskf-----------wesvhhvvdliia--lee
lfdafallmk--vfpekgdlvvvkkqeateglctrmhepqkvlgsgfyvk
kkredaitalrddfmpp--tqleihnvaampylvl--alnhqadcfncne
mgprq----qlgmrgktftgqekkkv--isflqadk---lktlaeggsaa
dtgahvegctsgchvgsggplfpsg-----lktpfklkrtv--trepgep
veh---kgrktpahwst-qlsindgvltdqkdyalsfmwngssvaetslh
hske--npfnvkeesftapki-qrdnn-vgdksdhletkti-a--feklv
----ng--trgt-----pldsqqergvlggds-lltttsa---pevvlgt
grsgvkhta---dpfllihiahplksdkfstldktqevvdlltkpsylty
tdelalgqggv---karcclkyrlkmgwgelqgnrcnrgaiskpdlrsld
tagl-pkntkifg------ystrigvatsgadgtctsisaam--haev--
--avsda--klls--iiqeklg
>ENV_SIVG1/22-522
edsvpkkpcdgpteptlhmvrlacedveq------yditklth-----ss
aktsviatptfllek-rlakvgsvrmsrld-pwe----pvgltankylep
fcktltalmt------kagliirvrqdeyrdktvgtkdqkdslgdvmlve
kkvrakgvnllhegkpsesltldlhg------lcf--svhdkgdpyaarn
----h----kvtakakgaikhqkkkg--vaflaask---latvlpglapa
asartnagcnsgaqsgsgvsvsnlg-----issqlkvngsv--srilaks
ten---nvnkppsyytn-qlqtdgapvanhkgstpgfsmigsniliaala
dtkr--aklaltmgnlekdai-sv--s-vgglsalggykahqa--ffkal
----mk--vrga-----pyedertkvrlaqqtnhqgskatgevhdcyldf
aksnvkqsa---allflvrv-gplqeakksnadnasdvvrgeektiylrf
gddlkmkvrgl---krirclkyiarltwsqidpssclapterrvlvrnvt
yagk-pmddkefg----lftgtkhgrst---thasggvggal--hggi--
--rpcnn--ellg--eiqlrla
>node7
rdtvdrrpcdgpdqpklhkvrlacedvee------yaitklth-----ss
aktsvvatptfmqek-rlakvgsvkmqrld-pwe----pvgvmmdkylep
fcktltalma------tagliirtrqdefrqmtvgtkdqrkclgdvllve
kkgkekgvnllhgvkpdeslylelhg------lgf--avheksdpysckn
----h----qvtskakgaikhqkktg--vaflqask---latmlqglapa
atariaagcnsgaqsgsgvavsnfg-----irsqlkvngsv--trelgks
sen---nvnkspsyytn-qlqtnggavanhkgstpgfmfsgsniliaala
dtkr--aqltltmgnlereai-sv--s-vgtlteheaykahep--ffkal
----mk--vrga-----pyedektkvrlgpqtnhqgstatgnvhdccldf
tkgnvkhta---nvlflvrv-gplddartnnadkasdvvrveiksiylrf
gdelkmktrgl---krirclkyiarltwsqiepseclgaterreqvrdvt
yagk-pkddksyg----lftgtkhgvgn---thacggvggal--hggv--
--spcnn--ellg--eiqlrla
>node8
kenvtrrpcdasnqpklhkvreacedaee------yaivklth-----ha
vktsvvnpptymqqr-rmakv-----------we----avgvmmekyldp
fcktfaalma------tagliirtkedpfkgmtvgtkdqrkclgdillve
kkgkekgvallqgvkpp--lylelhe------laf--avheksdcydckg
----h----qvgskakgalsqekkng--vsflqask---latmleglapa
atgrlvagcnggaqsgsgvpvcnfg-----arsqlklnegv--irelghs
aeh---nanknpsyysn-qlktnegavasqkgntpgymfsgsdivisala
ntkr--apltlttgaftrspv-sq--n-vgtktehvetkahep--ffkim
----mk--vrgv-----pyddekdkvrlgkdtnhqgatatgdvqdccldf
trsnvkhta---nvlllvhl-gpldnarmsnddktsevvrveikctylrf
geqlnmkdrgl---kvihclkyiarltwseiepseclgaaerkeqvrdvt
csgl-pkdakqyg----lftgtrlgvnd---thacsgvggal--hggv--
--spcnn--qllg--evqsrla
