>node3
---in-ffegsgwagk-------rrcs-n-------cfy---hqytr-sl
ga---hq--------a---ivlskclh-tmsdgehva---cpnat--th-
-----------------------------v-pcrkvk-------f----c
dk----fmhst-------edyqpigqasfav---e-----dk------yg
qqev-pvmiggcmkkgagsylstyas--tq--------------tl----
gg-----dkqg---gl-----ssvhl--lal--ivealiprdpgg--f-p
---------shgfelkgvvgsvfd---dtfea-vetmiwt-----ilfak
dq----r-lkchnv------------------e-----------fkpik-
dd-----------fshdht-----la--vdfr-cnatd------------
-----g---yvv-alllevw---plsdnmg-----ew----vthswrgan
lfppl----nsqg-----kr-kel-mtd-----egna-ren-n--v----
-----------hedehvk--------viscl-rysslfhfav------ck
ngrgv--iv-----------h-------r-kys-----------------
-f------acvtkevrmealal---k-slti---yldqvv-vdsfe---q
itd-a--kvqd----q----akdcksl--l-------gev---------g
g-ngspcd----s-r---fw--------------a------vep-nq---
--rv---------------------grks-kiy-a--iegv-yl-----i
-d----lv----kay-----k----s----vl-----------pgy----
----lshsaakfv-----------v----efd--htkkrv----wkes--
dh--h------dlv--ssriars--s-lepft--------------chag
g-c-------cflitgehaig-kcmsv-----------v---------e-
---ne--ktklygsgkkqpssrg--ndal
>node13
pleil-f---g----kdqv----lncaghllerat--ft---rkfkk-ss
ek---qd--------nnkcvl----------------------em-gslv
----------------s-------atgh---kckaik-------f----c
aa----fl------------hqafgpgifpi---a-----sr------lt
deqp---------------------t--v---------------akv--l
ga------sqa---sagkgly---------------qlkkrgpqgptf-p
----------------fkv---gealqpnvn--lpvliwadhdnillypq
nt----r-elcqva--rapfg-----------qhitydrnst--------
------------qygkqt----------yghp-c-----v--g----mlf
gshgsgg--yam-asnlavw-----sdvlgdp---------nthgskegt
vfc---------n-----kr--ca-----------f-------askwg--
-l-kse----ahnd--lr--------------------------------
----------------------------r-emkelsfh----qkhitsln
gfis----gt-----------i---ec-------ykeqlv-lrcfq---e
lmr-t-rqvhe----e----shanegr--l-------arg---------g
g-dgtadee--aa-l---kwlk--spkyag---pc------lgpgsp---
ltilq-n--cveawdqelgify---sa-sa-ly-s--lggi-ylpe---f
-k----lg----r-fsyd-vk----ghg--llvlhl-------lpw----
---------tkfs-----------i----arf----kv--------gpvf
maeth------dlv--v-----------rhlp--------------mgrt
dec-------c---------l--cka-nnpcg-----kipa-------n-
---es--ksp------rgeegkg--grs-
>H
pl--------s----mnkvgkkglnc--sllerst--ft---rkfkk-sp
eklapdd--------skncvp----------------------em-gell
----------------s-------itgh---rckaikrgkgtccf----c
ts-------------------------ltsv-------------------
aqhp---------------------t--v---------------akv--l
ga------nh----naskglf---------------flnkrvpqgprf-p
----------------vkv---gaskdpnva--npaliwanldvialype
nt----r-elcaia--rtpfg-----------ehitydrypt--------
------------gygkht----------yghp-c-----a--g----flf
garsdgg--wam-asnltvw-----shvlgn-------------------
--c---------n-----kr--ca-----------l-------askw---
----gh----ahnd--lr--------------------------------
----------------------------r-smkel--------kqmktld
gyit----gt-----------i---ec-------vkghla-lrcfh---e
lin-t-l--ye----d----shsvdgr--l-------ssd---------a
g-tataeellnn------------------------------gpgsa---
lnild-n--avhgwd-sfgifl-----------------ivgylaa---f
-i----lg----r-tsyg-vm----gha--llilnl-------lrw----
---------ikfs-----------i----prf----kv--------gpvf
msepq------klt--v-----------khtp--------------mgrt
ksc-------s---------l--cta-nkscg-----kkpa-------k-
---e---nsk------rategng--sad-
>node14
---il-fmqsg----kdea----lscaghqldrad--ft---rkfkk-el
gk---qe--------n---vl----------sne---------em-gslg
----------------a-------tenh---rckaik-------y----c
aa----fmakvpk------nhqpfgpqvfpl---a-----er------lt
edqp---------------------t--i---------------arvepl
gi------kqs---st-----rsvr-----k--vwsqlkkkdpqgatf-p
----------------gla---gealrphle--lpveiwadhdkiilypk
ds----k-nlcqsa--rvtfa-----------q-----------fnskrm
ek-------kprqyaskq----------fnhm-c-----v--g----rlf
gsresg---yam-stnlslw-----sdglgqp---------pthgtksgt
ffsp--------n-----kq--cttsre-----egi-------tskrg--
-l-nse----rhnd--vk--------l------------ggv------ck
kglgp--tv-----------a-------r-dvk---fh----hshatsgl
kfin----gt-----------i---e-a------ykeqlv-lhcfq---e
lkn-t-rqvhh----e----kkqndgr--l-------aqg---------g
g-dgtacd----a-l---ywtk--spkyas---pc------lgpgtp---
--llq-s--aaqawqqelgify---se-ta-fy-a--lgni-ylpq---l
-k----lg----r-f-----k----gqg--llvlhl-------vaw----
---------skfs-----------i----akf--ptkv--------gpti
lq--h------dlv--mtspsrq--wevrpfp--------------agpa
a-c-------c---------llacks-dagsgnl-srki---------n-
---hs--ksa------keeeerg--gvs-
>F
---vl-f--se----ktpa----rasvvn-qargg--fi---rk------
qr---hechngpapcd---vl----------tgp---------nm-gsls
----------------k--srsytarfn---rckrvk-------y----c
-k----flvk-ek-----------gpavfdl---prilsdqr------li
sehp---------------------lhrm---------------krgipl
gr------kqmeikaa-----rpvk-----k--vwshlkakisqgtvf-p
----------------aka---ggalhtfkt---pldi---rs-lilkpt
ne----k-plhasrrl----------------q---------vgfsskpk
ekcqgchklkdkqyps-e----------fprv-c-----v-------all
gasvta-----yrsaglplh-----ldnlg-g---------kihgtrrgs
ir-h--------d-----kh--ctdtre-----hnt-------aatrvne
s----iflvtrq------k--keiehi------------kkv------sk
gdlda--ar-----------p-------k-esk---ys----gshatsrl
hfva----mi-----------rkssa-v------lkgqki-lhcfq---q
ledvk-negphdnvfe-----kaqhgplgl-------ans-smtrnmyag
n-d---cd----r-lipnfwnk--tvkyapefypc------lvagsa---
--liq-pcrdgltwqkplgi-----se-ce-fcrt--lgev-ylsq---l
-tngtklg----g-l-----p----sqg--llp-----------------
----------afs-----------l----lif--s---------------
-------------------rspa--wiapp--rlmtqqtvklvgdia--g
a-c-------p---------laacra-aagt-glisrkv--a-pvv--e-
---nv--qna-------------------
>node15
---il-fmqgg----k-------lrctdh-------ify---rkhrk-el
gr---he--------a---vllskclp-vy-sgenat---srsem-dshg
----------------ale-----tephev-rckaik-------y----c
aa----fmarvak-----gnhqpfgqevypv---a-----ek------wt
hnep---------------------t--t---------------am----
sv------kes---av-----rsvp-----k--aseelinkdpqgatf-p
-----------smflrgaakrvnda-rnalq--vpvqiwtdhdkrilypk
dk----k-nlcqsa--rvafa-----------d-----------fnvtkl
dk-----------fsckq----------mnfm-c-----i--aa--khlf
g--gsg---yam-asllelw-----sdgmgrp---------pthgsrsgn
ffsp--------d-----kq--cvskre-----egi----n-ktrk----
-----------pddehvk--------liccl-c---lfhgav------ck
kgkgt--tv-----------h-------r-nes---f---------atgi
kfydi--igc-----------i---a-a------ykeqlv-lhsyq---e
man-e-rqvqh----q----nkqsdgr--l-------gea---------g
g-dgtqce----a-r---ywtk--sqkyps---pc------ldpgtq---
--alh-c---------glsvfyealsqkta-vy-a--vgnv-yl-----i
-d----lg----r-f-----k----gqg--llvlhf-------agr----
----lahsaakfv-----------v----tky--ptkk--------dpki
tr--h------dlv--lnstsrk--revkpft--------------cgag
a-c-------cyliies---glmcmtvd-----m-srni---------n-
---he--kat------keeedrg--die-
>G
aleil-y---g----kdhv----lncagyvearnt--fs---rkftk-ns
e--------------yskcil----------------------aqhgslv
----------------s-------aegv---kcrgik-------yhdakc
as----fl------------qhafgagifaf---s-----srkngtnwlt
deqp---------------------t--v---------------skp--l
ga------sqt---gastglc---------------q---sgpqgpnf-p
----------------frt---gaalvptvh--lpvlvwa-----lispv
nt----k-dlctia--tkpfgiyakgsdl---qhivydryst--------
------------qytkqt----------ygyp-c-----alkg----lln
gshgsga--yav-pedlaiw-----semlgep---------nshstkigt
vfc---------vme---kr--ca-----------f-------nqkwd--
-llksk----shkd--lq--------------------------------
----------------------------r-dlkevnfhggncqlhitnlg
gfis----gg-----------i---tc-------yqesll-qrcfd---v
amh-t-rqvle----necisshanvgr--l-------argl--------k
------sek--mp-l---kwls--spkysg---ac------mgegrplhs
lkvlq-n--cvsawqddlgifh---ta-ns-my-g--apgv-ylpd---c
-k----lg----k-gsfddvnlnwtghg--llvthl-------law----
---------vgfs-----------ikllfarft----v--------gtvf
madvh------nl---v-----------r-----------------rgra
eectf-----c---------l--ckg-gnpcg-----kepa-------h-
---kn--d--------------gydgrh-
>B
---in-nlepsgwg---------rkcp-r------tcfy---hqyti-sl
ga---hh--------q---vvldkcld-ttgdgdhva----stgt--th-
-----------------------------p-kcwevk-------f----c
ek----ffhsa-------delkpisqtsfav-----------------yg
kqea-pakigvcmkraavsstatyat--aq---------qenaity----
gssw---dtts---gl-----hlkal--lpf----talipgvpg---f-p
flgakgcmy---fdlkgvvgsvfd---ktfeagletmvws-----ilfak
dq----r-lnchsv------------------a-----------fkpmt-
nd--------------dhtgdplclvgkvefh-csatg------------
-----g---y-v-plllkvw---pipdsmg-----ewaagalshswhggp
lfppllwlggarg--irckr-tel-ttn-----dgea--dn-s--i----
-----------kqeerik--------imsclvyytssfhfav------cr
ng-gv--ia-----------haavcnkgr-tya-----------------
-f------scvikrprmnalai---k-lltsvyrylkq-----------q
lve-s--gvkd----e----akdcksi--i-------glv---------a
g-ngspcd----s-r---fw--------------a------iep-dr---
--ie---------------------gaki-rlt-a--idgi-yf--ffki
-e----lv----kay-----k----s--vtvl-----------pey----
----lsatgtkfv-----------a----nfd--hskrrlapgvwkdg--
dh--h------dml--qhriark--s-leaft--------------chag
e-c-------ciiimaehsvs-kcssv-----------v-------yps-
---agvgktkly---------ks--stal
>C
---am-flevgvwgsk-------rrcn-s-------affkhl--htr-e-
-----hq--------s---lvktan-vlptisash------kses--ttv
yf------keevagadiln-----tdphpg-rcrkpr-------y----c
itvqlafvnll-------dphesfggapnsiyhpn-----t---------
hdenf-----------l-----nypt--h-lemkqgtsl-----sm----
ag------rsd-------------a-----m--vihdf---e-----h-p
-----------tftlamvinsmp-----alh----------nekpnlfpk
ne----m-l----g------------------e-----------fklnk-
qd-----------mgtghn-----l------k-cyaqlpa--pa--hhfg
h--asg---ygm-ag-ldlw-----sfnkgdkitsar----hnqnarvsn
afpt--------------cq--vaskreflltaski----i-k--v----
-----------e----------------------------mvwvvhaack
rsrgn--vidadkpkgvlssh-------ptkn------------------
---akglidc-----------h------------ykkknv---vf-----
--------v-----------aknyeql--lklplcrggk-----------
----apct----g-r---fweq--npsyqs---ac------lgr-ka---
--kls-c---------vea----algqik--------igtc-yr-----f
-d----lg----a-------k----g----sr-----------tvk----
----l-rpc-afelavnnlrikskv-----lh--gtkp--------hs--
gp--h------sqs--vktvemtct--ikvlt--------------cggr
g-n--aiggqsfyalkrlplgfmcl-ve-----g-srgv---------s-
---qm---akvlgtgphaqenkg--nsld
>A
----s-linap--sg--------rklg-n-------caf---hqetrftl
ga---hq--------a---iilgtcls-nmsdgekvalvsctead--th-
-----------------------------v-----vk-------f----c
dk----fmeai--tyasneesepigqaiftv---e-----dn------yg
sqdm-viriggcmtklvasylvgyaa--ta--------------al----
gs--vlcdkqg----------lsivgral---------iprgags--fvp
---------shdfeledrlgsvfd---dafaa-vetviwa-----elfal
dq----rslkch-v------------------e-----------fkppk-
ee-----------fnynnt-----la--idfr-cegpd------------
-----v---yve-vilstvwdktplsnsmn-----ew------hswkgtd
lfppl----nsqg-----gr-nel-ktd-----egntkrgg-n--v----
-----------ymdshvk--------vlscl-rytplfhyav------ck
rgsga--ie-----------h-------r-kys-----------------
-f------acvtkevrmfalai---k-hlti---yldqvvgvdsye---q
kke-a--kvae----q----n-lcdsi--l-------gev---------g
g-ngtsse----nnr---fw--------------d------veg-nk---
--rv---------------------grks-kls-afttegv-fl-----i
-d----iv----kay-----k----s----vi------ssitalgkiagn
iyhhlshsaa-------------------efe-epktksv----lkdt--
ah--e------ylv--sscvsrt--s-vqpft--------------chag
g-c-------cfniaggdsin-rrlat-----------v---------e-
---ne--knkqygagkkheas-------l
>node6
---vm-fmeggawaak-------rrcn-s-------cfykla--htr-e-
-----qd--------s---vipstk-h-partaah------pnat--tnv
yyytqtfhkqeiggadtlg-----tdphea-rcrkpr-------y----c
ig----flnll-------dphkpfgqapndvyhpn-----k---------
hden------------v-----nypt--hql------sp-----tm----
gg------keg-------------a-----m--virelirkesegl-h-p
-----------gftlpmvvdsmpns-keale----------hekrilfpk
nq----m-llctna------------------e-----------fkptt-
dd-----------fsakhk-----l------k-cyarlpv--va--qhfg
q--psg---ygm-asllelw-----sinqgdpelser----pthnarvgn
lfpp--------------rq--asskrdflltcaki----d-k--v----
-----------pdd-----------------------fhlmvw----ack
rsrgn--iis---------hh-------r-kn------------------
---am--idc-----------h------------ykkrnv-vdtfs---q
aas-q-rqvqh----q----akdyesl--l-------geg---------p
g-agspck----a-r---ywnt--kpkyps---ac------ler-nv---
--kln-c---------ves----algqik--------igtc-yl-----f
-d----lg----s-f-----k----g----li-----------svh----
----l-rpa-dfa-----------v-----fh--ptkp--------hp--
ar--h------aea--lktmems--r-ikplt--------------cggr
g-s----ggqcfyllkrhalgfmclqvn-----v-argi---------s-
---qm--kakvmgtgaraehnrg--ksqn
>node10
---vl-fvesg----ktdp----lasvqh-qargn--fl---rkfkk-el
gk---qenhkgptpcd---vl----------tna---------em-gsla
----------------k-------aryh---rckrik-------y----c
-k----ffvk-pk-----------gplvftl---aqllseqr------li
ddqp---------------------t--l---------------arvipl
gr------kqi---aa-----rpvk-----k--vwshlkaknpqgtvf-p
----------------gma---gkalrrfld---plei---rdkiilkpt
ns----k-alhasarl----------------q---------vgftskpa
ek-------kerqyps-q----------fnhv-c-----l-------rlf
gdsesg---yiv-stglplw-----sdglgqg---------pthgtrsgs
ff-p--------d-----kh--ctksre-----hgl-------tstrvpe
hm-hsv----rhsd--vkk--kiiehl------------gev------tk
gelga--sa-----------a-------k-ekk---yd----nthatsel
kfvn----iv-----------ikhsa-a------lkgqiv-lhcfq---q
lsnvk-rqghh----e-----kaqqgr--l-------sqs---------g
n-egtscd----a-lipdnwnk--svkyap---pc------lgpgta---
--liq-scrdglawqrplgi-----se-ta-fcka--lgdv-ylsq---l
-k----lg----r-f-----p----gqg--lhm-----------------
----------sfs-----------l----lkf--ptkv--------gpat
lh--n------dfa--mggrspq--wdvqp----------------a--g
a-c-------c---------laacrs-sagt-gl-srka--akavi--d-
---ns--ksa------k------------
>node7
---il-fmeggawagk-------rrcv-n-------cfy---rkhtr-el
gk---hd--------a---illskclh-tsstgehat---cpnat--thv
----------------glg-----tdphev-rcrkvr-------y----c
dk----fmnsl-------ddhqpfgqapypv---e-----dk------wg
hnes------------a-----dyss--tdf-------------am----
gg------kqg---gv-----saip-----l--vveeliakdpdgl-f-p
-----------gfnlrgvvgsvtdr-kdtlq--vpvqiwsdhdkrilfpk
dq----k-llcqsg------------------e-----------fkptk-
dn-----------fsckhm-----lg--tkfk-cyarvpi--aa--khlf
g--esg---ygm-asllelw-----stnmgnpq--ek----pthgsrsgn
ffppl----htpq-----rq--avtkre-----egi----n-k--v----
-----------pedehvk--------liccl-r---lfhmav------ck
nsrgt--iv-----------h-------r-kns-----------------
-ffki--iac-----------l---k-s------ykdqvv-vdsfq---q
ian-q-rqvqh----q----akncnsl--l-------gev---------g
g-egtpce----a-r---fwtk--kpkyps---pc------lep-nq---
--klh-c---------ges----algqktgkvy-a--ignv-yl-----i
-d----lg----k-f-----k----g----ll-----------ssh----
----lshsaakfv-----------v----tfh--ptkk--------ep--
ar--h------dlv--lnsters--r-ikpft--------------cgag
a-c----ggqcfliteshalgfmcmtvn-----m-srgi---------d-
---he--kakaygsgakeeddrg--nsqn
>D
---vl-fniggawaak-------rrcd------------------ar-q-
-----qn--------k---vipstk-h-partaah------t-------i
yyytqtfhkkeige----------tdphdarrcrkpr-------y----n
vg----flqll-------dphy-----p-kvyhph-----k---------
rdve------------t-----nfpt--hql------sp-----tm----
es------keg-------------e-----mfk--ralfrkegqsl-h-v
-----------kftlpmvvnsmvrs-aenle----------hekrrlfpk
kkrnlgq-llctqa------------------e-----------fkttt-
ea-----------fsakhn-----i------kacyarlpa--ithl--fg
h--psg-spygt-ssllelw-----pdsendeemtgr----pghnaqvgn
lfps--------------shl-anskrefllscvkm----vkk--v----
-----------pnd-----------------------fqlliw----nca
rakgn--igs---------hq-------r-kn------------------
---af--idc-----------l------------yskinv-altfs---q
aqs-q-rhvqc----q----tkdfstl--k-------gdg---------p
g-agspct----a-r---ywg-----kpss---vcknhkskwer-pv---
--klnlc---------vqt----aigkik--------igtc-yl-----f
------lg----s-f-----t----g----lm----ap-----wph----
----l-rk----a-----------m-----fl--pvkp--------qv--
ar--hkaivegasa--litmd-c--k-ippla--------------sggk
v-s----ngqcfylf-rhglgfmceqen-----v-pkvi---------s-
---qm--kakimgtsartdhgrg--krmn
>E
---vliyvngg----k--q----lssvqh-qargn--fl---rkiks-el
gk---qen-kgatpcd---vl----------ast---------nm-gsla
----------------k------------------vk-------y----c
-k----fyvk-pk-----------gplvftl---a---------------
egqp---------------------a--l---------------trvipl
gr------kqs---aa-----rpvk-----k--iwahleatnrdgtvf-p
----------------tma---gk----------alev---rgki-lqpp
ls----s-alhaseri-------------lfgq---------vgfsthpg
ek-------kekqfv-------------fkhv-c-----l-------plf
g--egg---yi------plw-----tdglgmg---------pphgl----
--------------------------------------------strvpe
hm-hsv----rssd--akkcgkildhl------------gev------mk
gelgatlse-----------a-------k-dkk---ce----nkhptsel
kgvn----ia------------ahaa-a------lkrqmv-lhcfrnskh
ltgvkd-enhh----e-----kavqgr--l-------tns---------g
gqeghcsn----s-livdkwnkwgtikyak---pc------lgpgta---
--lik-sciag-ardrlhgt-----se-ta-fcka--lggv-yssq---l
qq----lgqeafr-f-----p----gqw--lhm-----------------
----------tfk-----------l----lkf--pttv--------gpkt
vh--n------nfsmgmgerppe--wdvlp----------------a--g
a-c-------c---------lnvckk-gast-gl-srka---ktii--ek
sqqns--qta------q------------
