>E
kkctkna-ma-------------dfi----avi----md----------m
l-------d--kl---leepeglhfwlgelaglekpldpp---vgvval-
----v-----sqpye----i-----ecdq----ikd--gv----------
----f--------------g------tensrvtyapes-kslev--f---
pipe-----------qg----lv----------aeeyfvk-kqa------
---------------------------------l---lkdrdrt------
--------------qagsrn-----------------glyi-avn---pp
l--i-wiekeys--p--adn---------s--sepcvdncgtlhlhagtr
evv------------tie-ntlpkqtgevipp-l-----avi-------e
sqh---pkmfitrgnrvqica--a------dwaeeakavhhk-g---cri
v---lpfws----iipcchdgni-l-----ls--------h---------
-----ik-------------------mqpll-espq-------------h
pa-----c------------als--sc-ls---csl-ghntdgg------
---------ryrf-----ip--fnrypvklyhek----yctctv------
--gtqrnhgqdgep-------dneaihhdvpn--g--lycecktlvn---
-ttc----g-ka-------ft--e---------------rs----hi-yf
sf-----eckgpksa----n--plavccvftatfee-i--gm--------
----epgkvlrtklhrgefdrc-ncd-yasgfprhvkt-----vm-----
----------d-kha--------------rtfv--lftlsp-fi--k---
-------------pf-----eldrscs-kag-ade---------velg--
----l-at--thsncgq-seithanprsq----veat--ic---------
---tssvdfgl-sff-ns---nrynlka---dw---fi-kdt-----kip
gss---pt--naglartyvla----------------saeag-----wt-
-vwgsk---dvg--yalyd-----------
>node13
qk-teaa-ms--------a----tyi----avt----dd----------r
----------------asklegpyy--------------gcgqlaicai-
----e-------pfd----c--------g----yk---tm----------
----f--------------mhlgfdttd-tkvvcspds-kpm----f---
appe--e-gn-----es----tv----------s-syfir-kqfae----
-----k------v-----v--------lf----vr--lqsknrp------
--------------papt---------------------ydqi-----kp
latv-wikseyt--p--vdpv-----s--p--dq-------------sar
-ilcvflstdndcsctmdknta----------gftqslks----------
------akkvrgdrkaidwcs--q------kwadngql--ar-v---c--
----isfrs----tipcctvgsiva-----llqgs-na-tn--------p
-va----g---y----psg----eekfppll-dsads-----------pq
raa-pqcc------------t----hc-vahlfcslc-----dt------
---------kfay-----vp--ygqyrlalladl----fcscpg------
--ktknnhitqvep-------nt---dldlgh--g--lychcgl------
-vt-----g-set------fgcnp---------------kr----ki-lf
gf-----qckgrlasa--fg---------------erl--gg--------
----fpa--hrkhlsk-afk-c--qs-f------svkk-----iv-----
-------kk-d-kyqmpqg---lsssregktfq--lf-lss----ge---
-------------er-----e-----p-rpg---n------s--vd-s--
----l-p-----pdcqr-grlna-------------t--ncr--e-----
r--ta-idkka-syy-t------fkfegyp-gw---farsha-----kip
ena---pk--eknyrresimktg--eshknr-rtgypkaeep-----wkh
avyasg---e---------nsayrg----a
>node6
qqc-aqp-vg---------vvkvtyikc--skp--esed----gehgkmr
----------------ca--ahayyw------mis-sdsi-----irymv
--lka--scpprila----a-----ecca----hr---kg----------
----ynrdsikr-lmvq-hl------ie-ls--cg-d-------gnhvrv
kep----lvk-----e-----ltslk---hhgtt-iqfid-sqyan----
-----t------vgc-ifa--------v-----liglmv-----------
fdipiaeyrrg-wkq-fpin-----------------asfvevvh---ss
-vvqsk-aketk--p--v--------s--e--------------------
---------------------------------------agvdl-----t
svheklpshy---------ctrgr------gsadggaa--sr-g---cqa
h---tsf------s---cpvgpv-i-g---la--------v--------i
-vg----s---y----hkg----gekilyce-gndvsgcg------rdlk
kt------------------pvg--ks-vl---cakhdriknnyfv----
---------pesy----tin----------egvhavvh-crigg--gpvc
kr--------fnkk-------vf---hl---h--v--lyveykvnlp---
-i------sasr-------lgchh-----glrh------vk----kv-ft
pvm----ecasrlnha--y----------------------t--------
----fen--gkahlgk-pyrh---gp-l------sika-----ct-----
-------kkks-aad--------------kgfkfqvfg-ae----gm---
-------------qr-----d-----------aka------nf-ikvs--
----a-pnhgiphagdk-g--------------he---------i-----
k--tk-ve--------a------y-ise----w---llrgqe-----kkk
gaprtham--r--hp----lngd--dardhe-hkafdnaedplwq-fws-
-iwtia---k---------eeayvi----c
>node15
ekc-aas-mn-------------tfisd--tls--dsgd----aqagkmr
----------------ygrlegayyw------mkspleka-----mspll
--lkv--myrpriyd----c-----dccg----hk---km----------
----y-----------q-hl------td-frvvcgpds-kgi----h---
aip-----vn-----e-----lvsml---drnss-vlfik-aqfad----
-----t------vg--v-a--------lf----lt--lk-----------
fq-----------ksnasie-----------------gtyvqvid---rp
fvva-rikretp--p--vekv-----s--p--eneit----af-------
---------------------------------------sgv-------t
nshqklpqkf---------ct--q------nwadggpa--sr-v---cri
a---tsf------n---cpvgpi-alngrpll--------s--------p
-va----a---y----hng----gdkvralv-ednvs-----------lh
rt-----c------------alt--ra-vv---cskcdhkknnv------
---------vyay-----ip----------lgel--vpfckigg------
--evraahfayddp-------sh---hl---q--a--lycecklnln---
-i------g-sa-------lgchq-----gl-h------ar----ri-yf
pl-----qcqgrlnna--fg--pvv----------d-t--gd--------
----fpv--nkghltk-pfkrc--ea-f------nvkd-----vi-----
-------kkke-nyd--------------kafe--lft-sd----ge---
-------------qr-----d-----------gdn------gi-vnvs--
----i-pe--ihhdcqk-gdiad--krsk----sdqqgpvck--v-----
r--tt-ve--------n------ygfag----w---yirghg-----kih
gsp---pm--a--yrrdsilkas--aahehr-ragyenaeds-----wk-
-iwvsg---e---------ssaytv----c
>B
kkc-adp-vy---------liivafvlekttlr--ehg-----ahevmi-
-----------------arlcssyy--------vgpr--y-----vpsls
--l-gditttprifa----v-----evcg---------kgvcvspnlrqn
----h-----------n---------es-fpinca-e---------hmsr
st------vg-----e-salslvgla-----gkm-tmfidvalfad----
-----s------vd-hv-v-pamfalfl-ngllvns-lv-----clthle
fkvsiskykktd--qdlkvv---asdn----------atfke-ad---ss
-------akqkp--k--v--------ssidarvi----------------
--------------------------------------------------
--dkktpspf---------ci--q---chtnevdggqv--sp-gvaeckp
-----af----tsa---cpvgpl-hva---lp--------s--------v
-v-----l---f----h-------aki-----asdvskc-------relg
rs------------------gsg--rk-qv---------rkl--------
ggvygtqpgsssc-----vg----------ags------ckvgk--gevc
kr--------f-----------------------v--qysqyaanlk---
-k------glsi-------lschq-----vg-k-aigtegq----r--fa
-y-----gce-klvra--fa--pi-----------a-shlgi--------
lctyfet--slthmsv-pyakc--gsel------pvkv-----c------
-------sgkd-p-n--------------cpfqfnlyk-aa----gal--
--vgmqhtqshsshnprlvke----------qdrd------gfpvkvn--
----a-pnkgaphevdktrd-----trdkefdgnd-------esv-----
k--kn-ed-------es------y-v------wrvlllrgqahggqprvp
-sp---tl--t--y------vgn----vnhhglhpyekaekstpgqfwk-
-vrt---------------qdayniie---
>C
tac-tq---g---------vvyiayikc--srp--eaek----sahnkmr
----------------ca--ghayyw------lir-adsi-----irymi
pgleh--acpp----------------------hr----g----------
----yngkgikr-vmvral-----------y--cg-d-------gqdvrl
kee----lgk-----e-----lttlm---vqgtt-iqliv-atyee----
-----t------igc-yfqp-------v-----lialmt-----------
feipiteynra-wdq-ypkt-----------------asfvevvh---cg
-iaesk-akqqk--erkv--------s--e--------------------
---------------------------------------agiar-----t
avhekltthy---------pprgk--n---gtaegssa--sk-g---cqa
h---ttf------s---cqv-----------s--------v--------v
sig----a---y----pkg----serllyce-aneiagcsirqla-rdlk
---------------------vg--kaetl---cakhdridnnfigkntd
---------pedy----t-h----------eganglgh-crig---gpti
kr--------fnkkcgpntk-vf---hl---h--v--lyveftvnlq---
-i------sasr-------vg--h-sftnglrh------ir----kv-la
tav----ecvsrln-a--y----------------------aphisaskq
----fan--gkvhigk-pyrq---ap-l------tvka-----cv-----
-------krts-ptd--------------kgfnfsvfg-ad----nm---
-------------sa-----v-----------akakvtdtfhf-ikga--
----v-rnhglphaldk-a--------------ne---------v-----
k-----qg--------n------y-ise----w---llkghe-----kkr
gaasdhamkek--np----ldas--dardpd-edafdkaedalwq-fkh-
-----g---q---------e----------
>node3
ekc-aqp-vg---------ivkvefile--tmr--ehgelhvqahqgllr
----------------yarlsssyy--------vgpaety-----vpsle
--lkg--satprifa----i-----eccg---------kg----------
----y-----------n-hm------se-fpvdca-d---------hmsr
si------vn-----e-----lvgll---prgsk-tlfidvakfad----
-----a------vg-nv-t--------l-----vdamlv-----------
fkvaiaeyrrtd--qnlkvv-----------------atfed-vd---rs
-------akqkp--k--i--------savearvnqvd----af-------
---------------------------------------sggel-----t
ssdqkkpspf---------ct--q------neadggpv--sp-gvpgckt
h---tsf----gsa---cpvgpv-iva---lp--------s--------v
-v-----i---y----h-------ekvrynn-gsdvsgc-------relg
rt------------------gvg--ra-qv---------rkk--------
---------psac-----in----------pgs------crvgg--gnvc
rr--------yddp------vff---hg---h--v--lyseykanlt---
-i------glna-------lgche-----el-d-digsapk----r--ff
-l-----gcdsrldsa--fa--pii----------a-n--gi--------
vcpifev--dkghmtv-pyerc--asel------avkv-----ce-----
-------tdkd-p-d--------------cpfqfdlfk-ad----gel--
--vgmrhaqqhssqsprlvdd-----------gkd------gf-vnvs--
----a-pnsgvphevdk-rd-----krekefdgnd---------v-----
k--ak-ne-------ed------y-fqe----wri-llrgqa-----ria
-sp---tm--t--y--hsekvgd----hnhqvlnpyenaekstpshfwk-
-vwv---------------qdaynilevec
>node10
qkcsraa-mg-------------qfi----svi----ae----------m
l-------d--rl---ltrlegpsfwsdelaglekpldpa---isvcal-
----v-----gqpye----c-----ecee----lkd--ki----------
----f--------------g------ke-skvtygpes-kgmev--f---
rtpefa--gn-----eg----lv----------a-eyfvk-kqf------
---------------------------------lp--lkdsdra------
--------------qagsin-----------------glyieain---sp
l--k-wikkeys--p--vdkv-----n--p--sepcvkncgtfhlhagtr
eiv------------tletnslpkqggevvig-i-----avv-------e
sqh---pkkfrtkrnrvdwct--m------nwaddars-har-v---cri
a---ltfws----iipcchdgni-a-----la--------h--------p
-aydlaks---f----hng----neqmqpll-eare-------------h
pt-----c------------als--sc-lv---cslcnyntdng------
---------ryqf-----ip--ynqypvklfhem----fcscpg------
--gtsaanimdgep-------nn---hhdvpn--g--lycecklnin---
-tt-----g-na-------ft--q---------------kr----hi-yf
pl-----qckgplsra--fg--pvavccmfgepfee-i--gm--------
----fpg--qkshlsk-dfnrc--se-f------dvkt-----vv-----
-------kk-e-kya--------------rafq--lftlsp-fipgd---
-------------af-----eltrscs-rag-add------ni-velg--
----l-aa--thtdcek-aeltevnprgq----ieat--ick--i-----
radtnavefkl-sff-kcnllnifnlkg---gw---fi-kds-----kip
gsa---pt--dsgytrtyilptg--aal--r-rtgydgaeaa-----wk-
-vwvsk---eva--yslfi-----------
>D
qqc-aqpyvn---------vvkvtylrc--cspgnetad----gehhrmr
----------------ca--ahayyw------mis-------------vv
--lkt--scppvila----t-----eccskaqlhk-cykg----------
----vnrntinaivvvh-ql------ie-lf--cg-d-------ghhlpv
kep----llkayggre-----laslk---hhntd-iqfie-anyanrgll
ss---mhfeyagvgc-dfa--------l-----lkgqml-----------
lqipipsy----wrv-fpin-----------------agyldmgh---ss
-vvqsr-akqtknrp--i--------a--v--------------------
---------------------------------------sgvdl-----s
svheklpphy---------ct-gr------gst-ggta--crkg---cqt
h---vsf------s---cavg-----------------------------
-vt----s---y----hkg----gekilycv-gpdvspcg------rdlk
-t------------------pag--kt-il---cakhnriknnlfh----
---------sqsyhfvvtfd----------egvtavvg-crtds--ap--
kq--------fdkk-------vf---hl---h--v--lyveykvclp---
-v--segnsagr-feivknkschh-----glreg-----vg----ka-fs
temnsegacgsrlhna--y----------------------h--------
----fen--gk---gk---------------------g-----cn-----
-------krsv-sa-----------------frfevfg-ai----gm---
-------------qe-----h-----------aka------tf-tkig--
----agpkagtphagdk-g-------------------------------
----k-vk--------r------y-ise--------------------kk
ggspaqpm--r---------------------lkkednannplwq-ywa-
-awtiadkkq---------eathv------
>F
----rva-mg-------------qfp----avv----ne----------m
llghaeredskrl---lagfegksfwandlhflektleka---vsacgs-
----v-----gqayd----c-----ecke----lre--mv----------
----f--------------s------ks-a---yasqs-agmea--y---
rtvdfa--gt-----eg----lv----------a-eyyvk-kqf------
---------------------------------ep--l------------
--------------engkid-----------------gltiesidggl--
---k-wik-tye--p--vdkv-----d--p---epvvgdcgtfhkhegar
div------------tshad--nkqggdgqkd-i-----etv-------t
srh---skkfktssdrvdwca--mvk----nladd--------------i
a---lkfwa----iip-----nl-a-----lv--------q--------p
-ayevakt---l------p----edqgqpll-qaiq-------------h
pt-----c------------nla--fc-mi---csqcnyatdet------
---------ryqf-----ip--ynqypvmlfhkl----fcecpp------
--ataaanilggep-------sn---hrdvps--e--ly--ckidin---
-tt-----g-na-------et--m---------------rkmalqhi-fy
sv-----ecsgpviht--fg--pvisccmfgepfke-l--em--------
----fpg--qdsqank-afkrcv-se-f------dakl-----vv-----
-------kk-k-kfa--------------rgfq--lltlppdfl--s---
-------------qv-----elnrscp-ris-ddn------gi-veigqh
wvngl-aa--shadcdk-rsl-evnprgk----iett--fae--iesvpl
radsnpldyhl-sff-kckllnivnlkg--s-----fi---n-----svg
gga---pc--dlsytrtyiipvggfdsl--q-ktgydganla-----wk-
-vwvvk---etaawyslfi-----------
>H
qk-tsra-mskdngplsa------av----svy----dd----------r
----------------i-dleasyy--------------vcghla-----
------------afdlatvc--------g----yr---t-----------
------------------------------kvvsspegrkpm----f---
tppe--a-gd-----et----tv----------s-pafvr----ae----
-----k------v-----i--------nf----vr--lqsknrp------
--------------ptpi--lag----------------ydqi-----sp
laam-wvkfeyt--p--ieavgkqcgt--l---k-------------gvk
-ylsmflaanndcdca------------------tqtlta----------
------arknkgdrkasewck------------ntghl--tk-l---c--
----mtirs----tspcctvgggvh-----llqgs-da-tap-------p
-va----d---y----sssclsvveifppll-dnaks-----------pq
rdanpqccyiks--------p----ha-vpllfcpvc-----em------
---------aiay-----tl--yepfrlsllfdl----ycschg------
--rgpnehiaqvtp-------ny---dlevgh--g--lychcgl------
-ct-----g-aes------facyps--------------tr----ki-pf
gf-----qcsgrlagaclfg---------------irp--gg--------
----fpa--hrrhvgg-ayk-c--rs-f------sakkdqlseivykfin
l------qk-d-typvpqtetqlsssres--yq--ff-lrs----at---
-------------ds-----q-----tqrpg---n------k--ad-s--
----l--------------sln-----------------gcr--e-----
r--sa-ikikagsyy-t------ftyegf---w---fagsht-----kip
eat---ps--ekdyrrenilitl--dghknr-p-gypkadep-----sgh
svfatg---e---------nkacra----a
>A
qkc-aha-mg---------iakvefvle--tmk--ehsnlhlqehqalvr
-------------qgsysrmsssyy--------agsaetc-----vpsle
--mka--saiakifa----fkishvgc------------g----------
aqahy-----------n-hl------se-fpvac-------------msc
si------in-----e-----l---ldlippgrk-tlfleva-lad----
--ltdp------vg-sv-t--------m-----vgaqlv-----------
fktsia----td--qnlkii-------vsdcplghqrsa--d-vd---rc
-------akhsp--n--r--------navdarlsqda----af-------
---------------------------------------l-geltalyrv
ssdakrpspf---------ct--k------nqqeggav--dg-gvpgckt
h---tpf--vlggc---cvagav--ve---lp-----------------t
-a-----vqahy----h-------qkvlyqs-gsdvsnc------wrqvg
rt----------kkwtvdilgagiars-qv---------rkk--------
---------paac-----vn----------pvs------cfvsgtygsac
rr--------y-dp------iyf---hq---h----------ksn-----
----------na-------lgcte-----el-d-dvgvapa----r-eff
-i-----acnsrlstt--fprqpil----------a-n--a---------
--aifev--daghmkv-sthrc--acdi------agkv-----cd-----
-vsiasptdkn-a-g--------------cpfrfdnf--dn----gamrn
lsvgdkhgqehssqssrlksd-----------gnn------ef-inva--
----v--nssvanelsk-kd-----lkekefsgqe---------i-----
k--sr-ns-------dd------y-fqi----rpl-flqgsk-----hvp
-mp---tm--k--y--hs-tigs----hshqvlnpyesaekttpshfwk-
-vwv---------------kdayeilevec
>node7
ekc-aqa-vg---------vvkvtfimd--tmp--esgd----aqhgkmr
----------------yarlseayyw------mvsplenf-----ipslv
--lkg--tctprile----a-----dccg----hr---kg----------
----y-----------q-hl------td-fpvdcg-d---------hvrs
sip-----vn-----e-----lvsll---hrgst-tlfid-tqyad----
-----t------vg--v-a--------l-----ltgmmv-----------
fkvpiavyrrlswkedvria-----------------atfvevve---rs
-vvanr-sketp--p--v--------s--easvlevd----vf-------
---------------------------------------sgvel-----t
sshqklpsnf---------ct--q------nnadggpa--sr-g---cki
h---tsf------t---cpvgpv-vla---la--------s--------v
-vg----t---y----hkg----gekvryvd-gddvsgcg------rdlh
rt------------------pig--rs-vv---ctkcdrrknny------
---------peay-----in----------egdh--vp-crigg--gpvc
rr--------yndp-------vf---hl---h--v--lyseykvnlt---
-i------gvna-------lgchq-----gl-h------ak----ri-ff
pl-----rcasrlnsa--fa--piv----------a-t--gn--------
----fei--nkghlsk-pykhc--aa-l------dvkv-----ca-----
-------kkke-atd--------------kafqfdlfg-ad----ge---
-------------qr-----e-----------gkn------gf-vnvs--
----a-pesgvphevdk-gd-----krdke---nd---------v-----
k--tk-ve--------n------y-fse----w---llrgqe-----rid
gsp---sm--t--yrrqsilngd--aahdhq-rtqydnaedsvsa-fwk-
-iwvig---d---------ddayvv----c
>G
rk-tena-ms--------a----tyv----ait----td----------r
----------------agtqegpyy--------------gctqlavcai-
----e-------pfd----c--------l----hk---tm----------
----l--------------mhygfdnkd-tkvlcspds-kpm----f---
appd--e-gn-----en----av----------s-nyf-r-kkyae----
-----m------v-----v--------lf----vr--lrnknre------
--------------sspp---------------------ysqa-----kk
letp-aikaqtt--g--vdpt-----s--p--dq-------------ans
-ilcvflstdndctctvaklta----------gftdsle-----------
---------asvekkaidwcs--r------kw---------s-g---y--
-vdaisfkn----tvpictvsavvs-----llqgalnglkh-ckafsptp
-va----s---ygysnc-------------lrdpads-----------pe
rca-pqcc------------t----hc-vshlfcafc-----e-------
-----------ay-----vparyyqyklavlsdl----fcscpg------
--ktkshhitqvep-------ha---elalghefgaylychcgl---tpv
lan-----g-rtn------fgvep---------------kv----ki-lf
gf-----qckgklast--fg---------------vrf--kg--------
----fps--q---lgk-ark-c--ns-f------svnk-----fv-----
-------kk-dqsyqmpqg---asskrggkpfq--yf-l-s----ge---
-------------er-----e-----p-qpg---k------a--ve-s--
----l-p-----pdchh-etqnr-------------g--nck--n-----
r---p-idkkt-gyy-t------fkfegfp-sw---fdwghg-----kis
elp---pk--iknysresikpvg--esh-----tgypkaeaq-----wmh
aayasg---a---------gsgyrg----a
>node14
qkctqaa-mg-------------tyi----avt----dd----------r
----------------lgrlegpyyw------lespldkacgqisvcal-
----v--mykphpye----c-----dcig----yk---km----------
----f--------------m------td-srvvcgpds-kgm----f---
aipe--s-gn-----eg----lv----------s-ryfik-kqfat----
-----g------vg--v-a--------li----lp--lkntnra------
--------------paatie-----------------glyvevin---rp
lvta-wikseyp--p--vdkv-----s--p--eepcv----ayhlhassr
-iv------------tmnvnsa----------af-----asv-------e
kqh---pkkfrgdrkrvewct--q------nwaddgpa--ar-v---cri
a---isfrn----nipccpvgsi-a-----la--------s--------p
-va----g---y----hng----eekfrpll-esaes-----------lh
rt-----c------------als--rc-vv---cslcdhktnns------
---------ryay-----ip--ygqyalallldl----fcscpg------
--gtraahitegep-------nt---hldlph--g--lycecklnln---
-tt-----g-sa-------fgcnq---------------kr----ki-yf
pl-----qckgplasa--fg--pva----------d-v--gg--------
----fpv--hkshlsk-pfkrc--ea-f------qvkd-----vv-----
-------kk-e-kyd--------------kafq--lftlsd----ge---
-------------qr-----e-----s-rag-gdd------gi-vdis--
----l-pa--nhpdcqk-galae--grnk----iqqt--ick--v-----
r--ta-ieike-syy-k------fnlng---gw---firshg-----kip
gsa---pl--ernyrresilktg--aahknr-rtgypnaees-----wk-
-iwvsg---e---------ssayrg----c
