>B
lifalk--ag-pef------vlnqa----ke-tv-----ieg-------i
aaipad-tyqpaptsfqhgtlsvcykksd----------hir------q-
a-----qnr--------ia---pfayyqsn------kgkdaap------s
yg--rdaf------c-----------------l---h------------n
yad-s---e----------l--kak-vq-------------ap----snk
-feql---d----arsn-yflqsck-----qn-s-heg-vnfhy-----r
---lgeaaksetgvsglltqgkeks----fa--iaeetskllteklqlln
--akh--am-f---------------rsai--s----------s--ttpv
---gr---------------------------------rg-vkgadlsvs
cgey----vtslnp-wgk--hdy---dnydapl--gqntgn-kss-h---
---------ila-pahaav-gl---------------lnvd---------
---------------a---------------------------fe-y---
-------v-----ag--sc---------at---qn--kf-----------
----g---l--dyappikpr--sk-------------lkdtlhvrnfw--
--------------------------------qdlserrd------fvl-
---lv----m-----alsnfgn---nga---veka---sklgpt------
-------pgrkl----gsnrkt------h----fgfd----------lf-
---ckl--grd-----gnavrvkvyfs--------------caki-----
-t------ladr--------v----ldk-------nedah-----me---
g-w----------k-eyrlgmasltgatl-----evrdgksegvmptp--
---vqvt-----elekv--------gt----p--hvgvvtwllielcqca
kqpmsafsgqfqd---idknsvdi-------gl------i---lw-f-dh
vgdga-g-vye--tfs-c--------l-d----ffkmfydgi--------
-ssk-
>node10
lafv----gessdl------sklwkk-eypg-gv----------------
---------------------------------------rls------p-
c-----fck----s-kcla---sfv-------------kgtqdtfpls-i
qtlsnat--q---lkhll---anlraevllsak-schk--m------kvf
ynh-i---k----------l--nd--iherdlt------gkat-----ql
-nerl-eiq----hhsti----ecky----ek-e-eaepi---y------
---ifehpnq-------tar-ka-s----fg--dt-eg------------
wqp-cgygl-ygsavg--dgvt----tgrrayns----rcygtkvflayl
---skf-a--k-vyl---l----------a----elifag-aaghrl--a
ckgy----lgtlsilwga---yk---dlysls------tve-vfd-nhta
wdc--t---vlkhsv-----af---------------v--a---------
-l----------lleqlrr-------h------iall--t---fe-y---
-------v-----lpie-c---------a-----e--kc-----------
----a--hi--i-------wiliraraaghiafcfesa-----ageawph
--y---vlsp-lqla-------------y-dpa--lscrdgtfv------
---sl--flp-e---vlravgd-gpgpvgeareah---nteg-rkdkrks
deeng-kgnfkv----t----g--------------g----------lyk
vaectk--gy--dqnygreaed-ryfa------sak-----c-mgq----
sd------lpnhip----kvi----kntleglyeqynrera--tqis---
q-w----------kgdya-----leenesdtrl-g------------a--
---alsv-----emvliiale----rarckad--yn--------------
-----anc-qakd--vva-----k--------lnsg-----sdv--f-l-
--gt-----yaeekfvtcsaagh--fprdsgshva---------------
-----
>C
lgaeqlpgie-nly------m-nfgd-iynedil-iltnvev-------i
rt----------------------ykpedsimdksaaasdiv------q-
t-------kgqvpgr----------------------kkds-n-----lk
-------t------raqlyet--------medl-sketptl------qlk
ygtge---d----------f--kgk-il-------------de--vskdn
tfhhn---d----aklpvyflakcky---qlpps-teesv----------
------nngk-------vgsgms-s----ig-------------------
------------a-----k-------tkdmeyf----------hgee---
----iy------------------------------tlkfsgegnktmpt
vehy----lgglvplhgk---ef---tvfsish--yrdgve-ngp-h---
------lhflkdsdt-----mlfeaasldveidsnkrinvg---------
---------------al-rppralkss------l-tskds---ir-y---
-----qkv-----v----c---------p----en--ky----------g
qnvlv---aped-------q--tk-------------p---k-----w--
ki---fr------sn-------------pnalheghnck-------fif-
---ll--ycl-l-davlg-----ppklk---rnpa---vqkg-k------
-------vgrrl----g----sgdgisah----k-fntlynkscwvtls-
---cwqnnnhk-----grasdhstvfn------ktkeaicrn-rth----
te-tdrdkliqq-------ki----vki-------hedkt-----td---
r-w----------k-kyrlc---m--------------------------
-------------l------------------------------------
----------------cet---klrlshaid-eera-ari---vq-f-ic
igas-----fdsqqfn-csvkgntlfhti----lddlyrdll--------
-kscv
>E
lnyv----gessel------skvwkk-eypa-gpa---------------
---------------------------------------h-k------p-
cfmgtnfck----a-ecvslrftta---------e---k-sp---pqs-i
qthp-gt----------l---anvgtgcllsak-gcek--m------nif
yyh-i---k----------vyqne--aydtsmttglhglekat-----el
-derl-evq----hhssl----eckl----qk-q-eakpi---y------
---lfehpnq--------ak-ka-a----hg--ht-ep------------
wqp-cnygl-ygspfgrgdgvv-----grrannsshlcrcyntkiflayl
kkkatf-allk-vyl---l----------a----elliag-aaghrl--a
cmgy----vlslsilwgtwv-yk---diyals------dvacifn-thsa
wdcmdl---vlkesv-----------------------------------
-------------qsrvrr-------nedliprisll--t---fe-y---
-------l-----lpie-c-------------------------------
--------a----------fllirarsqg--aicfesa-----aseawpr
--y---vltp-lqli-------------y-----------vifv------
---alkgllp-e---vvk-vgd-gpgvvgeapqay---pveg-kkdkrks
qeeng-kgnfkglkgft----g--------------a----------lik
vagcsk--gy--egayqrsgde-tyfekmklfette-----s-mgn----
sd------gpnhip----aqi----ghtlgglfqqynrevaavgais---
l-w----------t---p-----ladnkpdssl-g---------------
---algv-----nmllirdle----rlrykse--yn--------------
-----akc-eaka--qva-----k--------leaa-----tdv-sf-l-
--gt-----eaeeifatcsavgh--fprdskshva---------------
-----
>D
lpydilrtve-vvy--------------------------sr-------f
ht----------------------ymaee----------ect------s-
t-----fsk----e-akmg---pfayfges------hkkdg-l-----lr
-------t------rhrfysl--------madl-skykpsf------ded
yatgikyig----------l--rgk-vl-------------ne----ken
-fhrn---d----griavyflarcky---reppa-teqsv----------
------dgae-------agngma-g----ia--qg-g-------------
wqa-n--an-lad-----t---lvyggvqrqhy----------playspl
------------------------------------dlryagagn-mlpt
vqsy----lgsvvplddk---ef---qmyaaah--drsa-d-dlv-h---
---------vlnsht-----glfagvsi---------ig-----------
--------------------------s------l-as---------c---
-----rkv-----de---cfgkskvyiqq----qd--ky----------g
eetgt---p----------------------------p---p-i------
--ykcvr------d---------------salhnehlchr------fif-
---ll--ycl-e-matvg-----sislk---rkpstsaiqka-q------
-------rgrkl----g----p------h----y-fk----------lf-
---cke--shn-----lratahs-----------akeev-----vhskts
td------l-dl-------kn----lnv-------s--kt-----iiapy
r-w----------g-eynmc---fvlvt----------------------
------n-----nl------------------------------------
----------------vdt---rmr---kvt-es-annri---vy-y-ic
igvgg--aqfdhqkfh-cgakg--vfhqp----ieglfrell-agiahgg
tsgks
>H
lpfpsg--g-rstlspakdg-mvphn-a-----------l--atlyalvi
sy-------------------------------------ksa------sc
c-----fsk----p-esl-------y----alga----vgrdl------v
lsy-nsgysp-----hll---skqrgerp---l-gd------------df
ses----------------l--ae-nth-------------ri----k-a
-yes-k--etrcehn-------qcry----ak-t-eekpt---f-----r
---kfegped-------ia-------------------------------
----------------------------shtva----------kvflail
---dry-a--tavyd---ldmvqvpsdie---qrdvewpt-gckgrl--g
iiay----laklgslwgs---tkfqsnifsvnr-----svn-gfsq----
------------ger-----rf---------------l--d---------
-lkgpvrn----liahlce-------h------iaal--tesgsdtyrgi
kqkgk--t-----fp---c---------t-----s--kcdiadsiqrqf-
----v--tv--v-------wfeds-------------t-----lgevf--
--y---mlcprld-s-------------f------hmt--pafv------
-------fyv-qr--plttvgr-pggpvpslqkad---isng-hkkkgks
dedntqkgrlql----a----g--------------i----------sye
vtlcpa--gydcd---gmenp-----------------------------
-v------lvqdassqpdkag----lde-------nerqrp--v-cs---
e-w----------kssys-----lleeep-----g------------pcg
fst-vmt-----sv------d----kfr---t--ye--------------
-----ayc---ksidvre-----i--------lakg---ectss--f-py
ntek-----wgenpfircppa----fpp--k---egm----l--------
-cie-
>G
lafpks--a-rfalysvqlsiatkkkwt-----------l---------i
ty-------------------------------------r--------k-
c-----fsr----p-rcl-------y------------kgrdt------d
lsl-dggysp-----dvl---agqrsert--qvdgnht--ymtllfgqny
fpt-q---d----------l--se--th-------------kg----pks
-yqklk--ecnapih-------ncry----ek-sreanpi---fvagmar
---aysetf--------vakfks-viviev--------------------
----------ygp-vg--t--a----airrtva----------kvflafm
---gkvd-----vyepsql----------tiqqrlvvfrs-paghrl--s
capy----lhnfgtlwgg---dffesevyqvtrqt--pkid-gfsqahy-
---------ifkfhq-----tf---------------i--d---------
-l------eldllaehmcq-------------------------l-y---
-------t-----fp-----------------------------------
-------------------wfvek-------------e-----vgeaw--
--y---mlvp-lqlsfhianevkqdeaef------lng--gvya------
-------yykaei--altalg-----eipdlkktd---sdae-ekekgkn
dpdsg-kgnfkl----a--------------------------------n
vtvcgk--gyatn---tmgsg-----------------------------
-gd-----lyagia----kvvphnyieq-------nakers--p-cs---
qew----------sdg-------tqqeep-----g------------qce
fpv-gmvdtlchna------dgadakfr---kynfe--------------
-----ntc---ksvdvkt-----i--------ltkn-skhcttp--f-ay
ldnt-----faddsftkypta----fpqfnknsldam----p--------
-cre-
>A
litalp--sa-pgf------lltla----de-tv-----ieg-------v
aivptgnt-----------aaslcfkegn----------qakprqctsp-
t-----qkr----r-rclv---pfayyhat-----fktrdeah------r
na-----f------tqmlyvsv---------dl-sdhqphf------dvn
yvg-p---g----------a--mg------------------------nk
-fdql---d----trad-yflvask-----hh-s-hgtvikt--------
------taksqasfpgtvtaiqq-a----fg---ieendklltgklqiln
fgtkh--asaf---------------stmikya----------dvllvpl
---pr---------------------------------aa-gqgenlgls
cgsygacyagsigc-wpk--ydl---diytttf--ghdngd-ave-h---
---------ila-psypavkay---------------gnvg---------
---------------a---------------------------fd-f---
-------pehtssse---c---------svackqg--ky-----------
----t---f--ehdpnlepr--kg-------------lkqklqpr--w--
--------------------------------edthdchd------f---
---li----v-e---tsarfgnraepag---ldaa---skfgct------
-------pgakm----tgdrkt------htspkf-fd----------lf-
---crl--snd-----gragkhgvyfs------g-k-----s-ti-----
-t------fadr--------a----lei-------k---p-----fe---
r-w----------n-efklgvetlhsnqvkf---e------------p--
---vql--------v-----------t----p--htg-------hvcqca
thpmkafsgkysd---idd---dv-------al------i---vw-f-eh
it-aa-g-vye--a------------------------------------
-rsk-
>node15
lpyqtk--gqpsaf------lmswak-vypd-ai-----vef-------i
kt----------------------y---d----------ris------s-
c-----ftk----p-kcva---afayyhdg------ckknsdq------k
qg--adgy------khll---v-------meal-skhk--f------his
ynd-a---e----------l--sdk-vh-------------pa----kek
-yeql---d----ghssvyflkpcky----qk-s-daeai---f-----r
---pfdkaks-------vnngka-g----fg--qv-et------------
wea-c--gi-yss-ag--s-lt----saektys----------kvnltfl
---srf-e--e-------------------i--rdlslas-segnrl--n
cegy----lgslsvlwgt---dy---dtfsann--nkktve-tsp-nhs-
---------ilkhtt-----dl---------------v--s---------
---------------glrr-------h------v-tl--s---fd-f---
-------v-----ge---c---------s----qn--ky-----------
--vlg--kv--n-------w--dr-------------p-----vgdtw--
--y---k------lt-------------h-klh--ldcpkdk--kgfvr-
---ll--ycm-d---tlkaian-aespi---rnad---tedg-rrqkska
nltsg-kasfkl----t----g------h----h-yg----------lyk
lgicsh--glaeg---graann-tyfa------esk-----c-tih----
at------ladhin----kri----lnt-------tekqi-----vk---
r-w----------ngnyr-----lnsqetel---n------------p--
---gmmv-----dlilviald----ear---d--ht--------------
-----afc-qvtd---iak---ei--------lnkg-criccqvf-f-ay
dsqgse-qvynehtfvncsakad--fgpn----megmyydll--------
-yks-
>node6
lpydilrgie-vif------lvnfaq-iykedil-ll--ids-------i
pt----------------------ykpge----------eit------k-
t-----ftk----e-knmt---pfayfhes------hkkdp-l-----lk
-------t------rhqlynv--------meel-skhkpnl------dld
yatga---e----------l--kgk-vl-------------ne----kdn
-fqqn---d----grlsvyflakcky---qapps-teqsv----------
------tdvk-------vgngme-s----ig--hg-ea------------
wqa-h--an-lde-----t-------ssdmqyf----------kaelspl
---try------------------------------elrhsgegnkllps
vesy----lgaltplhgk---ef---emfavsh--nrdgve-nav-h---
---------vlnsgt-----glfeavsi---------invg---------
---------------gl-r-------s------l-ts--s---fd-y---
-----rkv-----ee---c---------p----qn--ky----------g
nnvla---apdd-------k--tr-------------p---p-irevw--
--yksfr------at-------------hgplhdehnchq------fif-
---ll--ycl-e-katig-----seklk---rdpa---vqkg-k------
-------sgrkl----s----s------h----y-fd----------ly-
---ckq--shk-----gratdhstyfn------etkeaicrc-rih----
te------lvdh-------ki----lnv-------aedkt-----ve---
r-w----------n-eyrlc---lanvt----------------------
------n-----kl------------------------------------
----------------vdt---kirlghkva-eska-sri---vy-f-ic
igagg--aqfedqqfh-cpakgdslfhvs----meglyrdll--------
-tgkt
>node14
lpfptk--gqrtnl------fmtwkk-dypd-gv-----l---------i
ky-------------------------------------rvs------s-
c-----ftk----p-kcva---afvy------------kgsdd------i
qtl-ndgysq---akhll---vnlrsertmqsm-sshk--l------qif
ynn-i---k----------l--sd--ih-------------pt----kek
-yekl---d----hhstvyflqqcky----ek-s-esepi---f-----r
---afenpke-------vakfka-g----fg--ea-et------------
wep-c--gl-ygs-vs--d-lt----pakrtys----------kvfltfl
---srf-a--g-vfl---l----------aidprelvlas-gagtrl--g
cagy----lgslgvlwgg---dk---evysvnr--pkhtve-afd-nhc-
---------ilkhqa-----af---------------v--g---------
-l----------liehlrr-------h------iasl--t---fe-y---
-------v-----lp---c---------t-----n--kc-----------
----g--hv--i-------wildr-------------p-----ageaw--
--y---slsp-lqlt-------------y-kpa--lncrdgsfvk-----
---ll--yym-e---tlravgn-apgpvgearnan---sseg-rkqkrks
nmsng-kgnfkl----t----g--------------g----------lyk
vaicth--gydvd---greand-tyfa------eak-----c-tiq----
tg------lvnhih----kii----lnt-------ydkqra--pqvs---
q-w----------ngnya-----leenetqmrl-g------------p--
---glmi-----elvlviald----kar---d--yd--------------
-----ayc-qvnd--ivd-----i--------lnkg-crecstv--f-py
dtgs-----ygehtfvkcsakah--fppnnpahveam----l--------
-cke-
>F
fafc----gdsadl------t----k-efpk-kv----------------
---------------------------------------ais------p-
c-----fck----s------------------------k-----fpla-i
qtqar----qkdqityll---aelraevllpek-dchk--m---------
----p---keadqqvsgavl--ne--tyeselt------daanqy---ql
-t----qiq----khstf----acvferh-ek-e-pgapv---y------
skavfehpsq-------teh-ka-p----ygvkdt-eg------------
wqp-ygygl-ygs-va--dgvt----tgrrlynt----rsygtkilltyl
---gff-p--e-vyl---l----------a----elivag-vaghrl--a
clgy----fgalsvlwga---fk---nlygvd------tve-vfd-nhaa
wdc--s---alkhst-----al---------------v--sqalgvacia
ll----------llehlrs-------q------lagl--t---fe-y---
----------------e-c---------v-----elykc-----------
----lgahi--i-------wvyir--------fcyqda-----kgpaskh
--y---emtq-lllp-------------s-gps--vscndgsfv-----l
yvlsl--flg-d---vifnpta-gpgpireardaq---styg-k---rks
ggavg-hgnfkv----d---------------------------------
----tk--df--dehy-rdedd-hyft--------------c-mgq----
ge------lpqvfv----nii----ksnldglykdynrgrg--sevs---
h-wigakvattqc-gsya-----le---geerlng------------a--
---alkv-----ekvvvisle----rarckad--nh--------------
-----dsc-takd--vva-----k--------lhag-----ksv--ldl-
--gs-----yav-kfllcdkagh--fprhpgthva-------y-------
-----
>node3
liyalp--se-pef------llnla----ne-tv-----ieg-------v
aavptg-t-----------tasvcykpgd----------qts------s-
t-----qkr----s-rciv---pfayyhas------rskdaap------r
ng--rdgf------thmlyvsv---------el-sdhkpdf------evn
yad-s---e----------l--kgk-vp-------------ap----snk
-feql---d----arsn-yflkack-----qs-s-heqvvnthf-----k
---lgesaksqtafpgivtqgke-a----fg--hveetdkllsgklllln
weakh--am-f---------------ssaiqya----------dvllspv
---sr---------------------------------rg-gqgenlgts
cgsy----mgsltp-wgk--ydy---aiyiash--gqntgd-ass-h---
---------ila-pshhavkal---------------lgvg---------
---------------a---------------------------fd-y---
-------v-----ad---c---------at---qn--kf-----------
----a---l--dydpplqpr--sk-------------pkhklhvrnmw--
--------------------------------qdthdche------fif-
---lv----m-e---tlsnfgnfaekpa---rdaa---srlgct------
-------pgrkl----tgdrkt------h----f-fe----------lf-
---crl--gne-----gratkhatyfs------gak-----c-ti-----
-t------laer--------i----lnv-------keddt-----me---
r-w----------n-eyrlgvnslasqelqf---d------------p--
---vqli-----elvlv--------gs----p--hvg-------elcqca
tqpmkafsgqytd---iek---di-------gl------i---vw-f-eh
igdga-g-vye--ays-c--------l-s----mfdmfydlm--------
-ssk-
>node7
lpyail--ge-pay------lmnfaq-vyne-vi-----ves-------i
pa----------------------ykpgd----------qis------s-
t-----ftk----s-kciv---pfayyhas------hkkdadq------r
ng--sdgy------khmlydvv-------meel-skhkpnf------eid
ydd-a---e----------l--kgk-vh-------------ae----nek
-fqql---d----grsnvyflnpcky----qp-s-eeqavnthf-----k
---lfetaks-------vskgke-a----fg--hv-et------------
wea-h--ai-fse-lg--s-------saamqys----------kveltpl
---srf------------------------------dlrs-gegerlgps
cesy----lgaltvlwgk---dy---dmftatn--nkdtve-ssa-n---
---------ilahtt-----al---------------vgvg---------
---------------glrr-------n------l-al--s---fd-y---
-------v-----ae---c---------p----qn--ky-----------
--vlg---a--d-------r--dr-------------prhkpfvkdvw--
--y---r------lt-------------h-klqdahdchk------fif-
---ll--ycm-e---tlsqfanyaekps---rdaa---tekg-k------
-------sgrkl----t----s------h----y-fd----------ly-
---csl--gla-----gratnhstyfs------dsk-----c-tih----
aa------laeh-------ri----lnv-------tedrt-----me---
r-w----------n-eyrlg---laneeaql---n------------p--
---immv-----elvlp--------gar---d--hi--------------
-----afc-qvtd---iek---di--------lnka-cri---vf-f-vc
igegg--avfeeqafv-cpakad--flps----msdmyydlm--------
-snk-
>node13
lpfptg--a-rtnlhpakqgfmtsrk-t-----------l---------i
sy-------------------------------------ria------a-
c-----fsk----p-kcl-------y------------kgrdv------i
lsl-nggysp-----hll---sgqrsert--nm-gdht--l------qnf
fat-v---n----------l--se--th-------------rv----kks
-yeklk--esrsahh-------qcry----ek-s-eeepi---f-----r
---afespne-------iakfkp-v----l--------------------
----------ygs-vg--t-gt----pvrrtva----------kvflafl
---grf-a--t-vya---l----------ainqrqvvlps-gagsrl--g
cagy----lnglgslwgs---dkfqsevysvnr--peatve-afsqnhy-
---------ilkgqq-----tf---------------i--d---------
-l----------liehlcq-------h------iapl--t---fe-y---
-------t-----fp---c---------t-----g--kc-----------
----v--hv--v-------wfedk-------------p-----vgeaw--
--y---mlsp-lqls-------------f------lns--gafv------
-------yyv-ev--altavgn-aggpvpdakkad---ssag-hkkkgks
dddng-kghfkl----a----g--------------a----------syk
vaicah--gynvd---gmens-----------------------------
-g------lvanvs----kvi----lee-------ndkqrp--p-cs---
q-w----------ndaya-----lqedep-----g------------pce
fsv-vmv-----ea------d----kfr---d--ye--------------
-----aac---ktidvke-----i--------ltkg-skdctta--f-py
ntgt-----fgdnpftkcpaa----fpppdknhaeam----v--------
-cre-
