>E
---tt--ryslhn---fhvl-----------lvl----p--np-gkntr-
-ealt-ekksvvg-hnda-----hggyggdlpi------ig----krlin
e--------------lygqg--k--e-dqgylcavk-kalyelas--qe-
a----ra-dk---lvdismyved------rkef-rlimnq-tns--c---
---ylerv---------------rqgtvcltgcg-vgs---vplpk--tl
fs--------eae-y----------evkdelnkgkang-it-------d-
-qgfislah-----vfhqcsedylgtgv-i--qgnlplkwfl--h-----
---k-----ligss------------qlg-g-------------------
----------k---tede---yekpgvataikgs---aeipw-----gan
afav--------hlv---ln-kmvydlacr---k---------ksyaadi
----vi----------v----cyavkaladgtlelv-----nedlsafgn
aaakgatkd-la---hfrd-t--vkgyyanpylcttgadqlp--htryss
------------tay------igvvglgnpfn---q----dyd-an---e
pnl------kn------wqn--dlegls--lkil-srtld---pkil-fl
--------------------------------------------------
------------sqccvegskaatqkltfvglflaaapla--ldatqad-
tkslalngnaa--rgpvpe-------lhqvdlssespy------------
--------------y---se---------gi-------------gk--g-
---ksyggqktrr--------lsmql-sgslpdlk--------gk--prq
lldtknlpe---epp------fisf-----k-----kfantnepg--pt-
--ee-g--------ykakneltyvedavkqsttkqlev-py---ket
>C
---tq-key---------yq----------g--fggrap--ppfkkhar-
-gs---eknkvtvvmafd-----aggy------gmdggg-dtl-------
---------------------------fagyic-tk------------s-
dneraraesv---va--l----f------ker--kgvln----tgpr---
---alg-v---------------r-------g-g-akk---vsatgm-as
ys--------asy---------lqisrt--------slpfl---------
-------da-csf-r---ctlctwna-----------ldwdv--i-----
---s-----llpggqklaphpdf----vs-nf-----fgt--y----aan
li---kcgp-la---yek---fqrvgpmhsnkhc---it---q-----fd
nlytalkkcyhghkisvvfp-agtl--ncnnesqyhvdcipkvkiftsvf
ksff------alk---lamg--yg--c------dalsyvfthqn-hrfa-
ranv-a--ya-----------------------vesmaa-----rtsipq
------------vrc--arksrkvlalqhcf----ttf-------q----
---------qe------h--kkllgalp--ltn-----------------
-------------------e--------k--fvlfkclinler-npls--
-edasv--d------------papigvcrt--------ml----------
------pdk----klpaah--irdpfl-----------------------
--ieckvks----grkl--tyklfgplcevvtpsdfcaqtvkpvdt--h-
nyrhd------ahmggy--g--rtnlklst----i--------da-----
-mghahrnd---kkssr-------------g-----kfv------vdkp-
--ft-d--------sqd---------kpi---fkplqragh---nag
>node10
---tt--hyklhq---fhil-----------lcl----p--mp-gnepr-
-eglk-dkntvmk-qada-----dgsy------------ng----pllid
ellf----q----qllyghgegs--e-aqgylcglr-kalcdlas--dd-
a----ra-dk---lvdiakyvdd------rkef-rgtlnq-vda--c---
---hlgrv---------------rvdtisltgcg-vgs---vplpp--tv
yt--------pse-y----------evadeldnsgfnm-yv-------n-
-krfiqlah-ctttv---cekdslgsgi-i--qaglplkwil--h-----
---k-----ilgac------------qlf-gm-----l---------aiq
llnfvka---kgcqtede---yetpgvntgqkgh---ae----g-asgan
tntq--------alv---la-kmifelacr---k---------ksyaagi
----li------h---v----pfadka------elv-----hed-ssfgt
gtamgatrg-fl---hfrd-t--vqgycndrylcstgadelr--htryts
------------ary------igvvglghpfl---s----dys-an---a
vnl------kn------wdl--nldgvs--lkfldsrtle---nrei-il
------------------kd--------km-iv--------pkiicp---
--sfni--trgpgqccl--sraaadklgfvglfltsspla--l----td-
ireldlsddaa--rgpvpe-------lh----------htl---------
--l----ag----ai---ke---------si-------------gk--q-
---tn------km--------ltaql-ngnlselk--------gk--pra
llegiqmpe---etp------fisf-----k-----kfgnnndpgvhqv-
--nd-g--------ykakneltyveevvkqkttkhlqg-ph---kdt
>node14
---tn--hyhlhq---fhil----------dmcla--aa--mpvgkgas-
-eglk-edsgvmkmlald-----dgky------------ydaakgpflia
dllf----q----q--fgngngs--q-adgytcglk-mtlceftg--ed-
p----ra-nv---lidhakamae------rkd--rgtldq-lna--s---
---hlgrv---------------k-------g-g-tgt---vpapt--av
yg--------dke-y----------evpadldncgfdmpfv-------p-
-nrfvhqah-cstkv---ckkkalgsgv-r--qsglpltwvl--h-----
---k-----ilgsc------------tif-tf-----lgs--y-v--aiq
ilnfvkcap-tg--tgdk---yeapgvdtgqkah---ak----s-ataad
tdtt--------hll---vs-nmifaltcr---k---------ksyatgl
kgfvll----n-n---vvlttpfa--a------ell-----hqd-itfgt
atti-a--a-flygthfke-t--------drylcttgpdelr--rarfla
------------sri------icvvglghpyt---dqyi-dys-an---a
--l------dn------wdl--gldgip--lrflttksle-----eg-il
------------------kk--------rf-nv--------pkvgce---
--gfnv--trgpgn--l--nraaaegvglvglfftptslalgl----td-
irevdlsepag--rgpape-------l-----------------------
--lyievad----ti---ke---------nv-------------gk--h-
---td------kmv--y--adlspql-lgnlseli--------nk-----
-lggmqapi---ettr---mgfigf-----n-----kfdynsqpevqqv-
--ld-g--------ysa---------lviqk-ikplqg-gh---khv
>node7
---se-keyelhqgl-fafl----------k--fggdap--ppfekdas-
-kg---ekggvevfltfd-----ngey------------cdgkkhl----
---------------------------legyvc-akdlavysfla--ed-
e----rgdav---li-hy----e------rde--rgcle----tg-h---
---slghm---------------k-------g-g-agt---vsatr--av
yt--------ekh--l----nqgkcdlt------pfdlpll-------g-
-iafviddk-cassi---carstwga-----------ltwiv--r-----
---p-----ilagg------------lvf-ef-----fgs--y----tve
llgfvkcgp-vs--kgek---fqslgpehsqkhc---st---ra-psgsd
tvyt--------hki---lp-tvvlalscr---n---------ksfgael
knfv------slk---falngefs--a------ellny---hqe-kafa-
rgtv-a--stf-------d-tfs------ka--cetgpq-----ksrfid
------------trc------qcvlglahty----nkf---yn-td----
---------qs------h--k-gleglp--lafaat--le--------nl
-------------------r--------km-av--------pk-dcq---
--ertv--n------------aaeegvgpv--------ll----------
------sdk----rlpvad-------l-----------------------
--lycklkn----gr--tdetk---p-cqvi-------------nn--h-
---rd------aml--y--g--dskl-lnt----i--------nt-----
-lggahapa---dgespg-spflaf-----g-----kfv------vdet-
--ld-g--------tad---------lai---ikplqhfgh---kag
>node13
---any-hfhlhl---fhil----------slchg--ta--mpvgegdg-
-edlk-eqgdttrilgld-----e---------------------gnlka
dllf----m----l--f---n-nknq-ldgypcgfk-mthcefte--ed-
p----kt-nvfsivvdvstamas------rkn--k--idq-lgh--gkgg
---rlakl---------------n-------g-q-tgp---tpaka--sr
yg--------dke-f----------dl-idqdtcgfampfv-------p-
-trfvrqah-csakv---ckkkalgsni-r--paplplawvirfq-----
---k-----iegsc------------a-f-vf-----lgt--y-vtgamq
rlnfikcss-ve--tddk---ndgpgvetsqktr---ar----s-attaq
tdtv--------hll---is-rmifaldcr---k---------kryatgl
qgfvll----n-ngslvvlttqfa--g------e-l-----hed-ivwst
attf-p--s-flydthfkd-g--------dk-------------rqklaa
------------sri------iciaglghpyt---nkyiddyates---t
--ealnwgies------wdl--gldgip--qrmltissle-----eg-vl
rigt-lw---hda---spkk--------rf-iv--------srvgce---
--ganv--qkgpg------------gvgwvglf-tpndlmlgl----se-
ireialssp-e--k---pval-----l-----------------------
--lyteva------i---re---------av-------------eksahn
---ha------miv--y--etlpvql-lanlskli--------t------
-l----ahv---ittr---lgfigf-----draskek--yhsqpeiahvd
gkld-gqkrlirchyta---------lvlq---lplrg-ge---kvt
>G
hrragy-hfhlhl---fhil----------tls-----a--mpvgegdg-
-edlk-eetdktrtfgil-----q---------------------gnlqi
kliyrakgmsgfyl--y---s-nknq-legyactak-mtlcqfqd--ed-
p----kt-atfsivndlaaakas------hke--h--meqtlwh--gksg
g--slakl---------------c-------s-k-lgp---tpgka--sh
yggchddkgkdqd-f----------el-ldqdacg--mpfv-------p-
-trlaihshyrsksi---ckakslg-------paplplvwvd-ys-----
---k-----idgnc------------a-f-vf-----lss--y-vtgamq
hlfffkcts-ve--tedn---nngssidtsqktr---tr----sgattat
tntl--------hll---ia-alvlaldcr---k---------rryaa--
qgfvlt----n-ngs--vlgtkfg--g------e-l-----hee-vgwya
gstf-p--g-flydthwkg-g--------ek-------------rdnlya
------------srlst--------tfg-------gkycv----es---t
--gqlnwgitg------wtl--gmdgvpikqrmltisslelkk--ege--
--ga-lwkfshdv---s-k--------------------------ce---
--gaea--qkgpg------------gvgwigal-dlnkhllgl----py-
iqevalstp-e--t---png------------------------------
-------s------i---qe---------vv--------------ktahn
---ha------miv--a--ete--sl-lanlsrli--------t-rv---
-a----ghv---lss------ykga-----draskdm--------vsdvd
gdvd-gqlrlirchyts---------hvlh---iplsg-aq---kcc
>F
---kt--hyklhh---fhrl-----------lcl----spplp-anepr-
-eglr-dtptvkk-dada-----pp-y------------tg----vqlid
ellg----q----qvlyghgenr--dpvrgflcllv-ratcdles--en-
a----r------------kyvdd------rkef-kgtisq-vdk--c---
---hlgrl---------------rvdnlfltgca-vgs---ippsp--sv
yt--------pre-h----------kvadeldksgfnl--q-------i-
-krpl-----cttta---cekntlggg--iqkqagl---wil--hdwmtv
spdr-----ltdsc------------qlf-am-----v---------gie
llnfvkp---d----dtd---yetpgvntaqkgh-----------aegvq
tstq--------alv---la-rvtfel-----------------------
----iv------q---v----pfadka------eli-----hea-tsfgt
gaamgttrs-fl---hlrd-a--ingycderylcgtavdelrrthtryts
------------nrc------vtvvslgdpfl---k----dys-ap-gwp
vn-------ak------rdl--nlggva--lyaldsktlg---srei-il
------------------kd------------t--------pkifcp---
--sf-------------------anmlvlmglft---ega--l----adc
irdldlsgdgkelrgplr---------h----------htl---------
--l----aq----ai---re---------ni-------------sd--q-
---te------km---------tasf-nvnl------------gk--pta
lvegsqmpy---eqh------fasy-----p-----kfasqaevsvcqv-
--kt-g--------yea---ltyiekiikqkttihleg-pq---kdt
>node15
---te--qyelhq---fhil----------dmcfg--ap--vpvgkaas-
-kg---edggilkmltld-----dsky------------ydgkkal----
----------------fgpgadg--q-adgyvc-sk-mtlysfla--ed-
p----rg-av---lidhtsamae------rke--rgaleq-mas--n---
---algnm---------------k-------g-g-tgt---vsapq--av
yt--------ekh------------dls-dlnhcnfdmpfi-------s-
-irfvhqar-catti---carstwgsgv-n--naglpltwil--r-----
---p-----ilagg------------sif-ef-----lgs--y----ave
llgfakcgp-ts--kgdk---yqspgpdthqksc---gk----a-ptasd
teya--------hki---ls-tmvfaltcr---k---------ksfatgl
kgfv------nvs---ialtgefs--a------elldy---hqd-kafgs
rntv-a--a-f-------d-tfa------ddylcvtgpe-----ksrfla
------------trc------qcilglghayi---dqf---yn-ae---a
--l------qs------ldvk-gldglp--lafavtknle--------vl
-------------------r--------kf-gv--------pk-dce---
--grnv--tmgpgn--l--aragaegvgpv--------la----------
------set----rspape-------l-----------------------
--lyckvan----ti--tkevk---p-cqtv-------------sk--h-
---td------gmv--y--a--ssrl-lgs----v--------nk-----
-lggvqapv---endrpa-sgflaf-----n-----kfvy--rpevdqi-
--ld-g--------yss---------lvvq--ikplqqfgh---kpi
>node6
---se-kdye-------ayq----------a--fggkap--ppfkknap-
-kg---ekggvevamsfd-----nggy------------pdgv-------
---------------------------legyic-tk------------d-
eddrargesv---lv-el----e------ket--rgile----tgps---
---slghv---------------r-------g-g-agk---vsetrm-at
yt--------akh---------gkcdlt------lfdlpll---------
-------ds-ctsdi---ctvctwga-----------lkwdv--r-----
---p-----ilpgga-laphpefpgnlvn-lf-----fgt--y----ape
ligfikcgp-la--kyek---fqrlgpvhsqkhc---tv---ad---gsd
nlyt--------hkisvafp-tatl--ncr---q---------ksfsael
knfi------alk---lalngafg--a------dvldyvfthqe-kpfa-
ratt-a--stf-------d-tfs------kg--cesqaa-----ktriae
------------vrc------qcvlalahsy----dkf---yn-gd----
---------qd------h--k-vlgalp--lsnagk--le--------gl
-------------------e--------kl-fv--------dk-dslg--
-eektv--d------------gapagvcpt--------ll----------
------ank----rlpvan--krdpfl-----------------------
--lycklkq----grkl--dtk---picevvapsdfcaqptipaet--h-
---hd------akm--y--g--dtkl-lst----i--------dt-----
-lgdahapg---kgesrg-npflrl-----g-----kfv------vdep-
--yk-e--------ted---------kpi---vkplqhagh---kag
>node3
---kd-keyelhhgq-la-lcygisvavile--fggeap--l----gst-
-kg---ekggvai-lafdv---rrgdy------------cd--dhl----
---------------------------legvvc-aki----afls--qd-
e----kgda-----i-ay-----------kde--rgc-e----tp-h---
---sighl---------------k-------g-g-agi---ghntr--av
ft--------anh--ltvhrnngkcelt------tvdlsak-----qkg-
-vafl--------av---aargswgv-----------lswrt--r-----
---a-----iitge------------lrfkif-----fga--y----ive
llsfvkcgpnaa--taek---fqslgpehsqtgc---cd---rl-ptgnk
tvy---------hkl---lv-tvvldmsar---n---------ksygae-
--fv------slk---iamngefg--t------gl-dy---hee-safa-
rgev-a--stf-------dhsyg------kp--cktgtg-----qvrfid
------------krc------qcvlglkqth----dpw---sd-kd----
---------ea------h--k-gaeglp--lafakg--lg--------hl
-------------------t--------km-al--------ak-ecq---
--ertvrcd------------aaaggvapv--------ll----------
------sdk----nlavin-------l-----------------------
--sykslknegyygr--tddtk---p-l-----------------a--h-
---kd------aml--y--g--dgkl-len----i--------ht-----
-qggavala---daespa-spflaf-----g-----rfv------iven-
--le-g--------aed---------vri---isplqhfan---kag
>A
---kr-keaelrhgqalv-lgnlisvpvive--ftgdak--v----dstl
lkg---eqggvsv-lafavyqdrrgdy------------cd--dhv----
---------------------------lealqc-pki----tflq--h--
-----kgas-----v-ay-----------kee--rgc-g----ip-h---
-tksigl-----------------------------gv---ahnds-ttv
ft--------add--ltvprhngkcelv------tlelsgk-----lkg-
-vafl--------av---margsw--------------swra--r-----
---a-----iiage------------lrf--f-----fge--y----vee
llsfvkc-----------------pnpnhsqtgc---ce---rl-ptahi
tvf---------hrm---lv-tvmlnmsar---k---------knynne-
--fv----ycpla---itkngdfq--t------dl-ey---hq--seya-
r-------------------sna------kp--cktgtg-----lvrfik
------------krc------ecvlslkrth-----pw---sg-rn----
---------aa------h--r-gydglp-----------g--------hl
-------------------t--------rmfql--------ak-ecq---
--erkvrce------------aaae--pav--------------------
--------s----tltvin-------f-----------------------
--sykswhndgyyqt--cddtk---p-l-----------------e--h-
---ke------aml--y--g--dgrl-len----i--------ha-----
-qgdtvgla---eaaspa-apfldf-----g-----rfv------egdi-
--fq-g--------a-d---------mki---is------------g
>D
---fe-ksy--------nyq----------g--fggkap--ppfftnap-
-pg---ehgsmeitmsld-----yggy------------pkgv-------
---------------------------legymc--d------------d-
ederargesv---lv-el----knfekcckes--rgivn----pgpk---
---stgpv---------------r-------g-g-ati---vsarrm-ns
yt--------akq---------gkcht-------lvhlpll---------
-------es-ckgdi---itvctwga-----------lkwdl--a-----
---papaasilggga-lsphpefqgnlvn-lf-----fgt--f----vst
ligfikcgp-ls--kykk---frrlgpvqaekhclvvvv---vd---gad
nlyt--------hktsvlfpdtttl--qcd---q---------lsfaakl
lsfl--gh--nlk---lalngafg--a------eeldfvfsdee-kpfa-
rltt-t--saf-------a-tfs------kg--cpsqpp-----rtrlte
------------arc------kcvlglahsy----ekf---fn-gd----
---------qd------n--n-ilanmp--iaasgk--ae--------gl
-------------------eggpgegagkl-ft---------k-dtlgla
seektl--e------------gppagicpa--------ls----------
------sek----qlpian--krdpfl-----------------------
--lfcklk-----grrl--etk---pgseiyvqssfcdgpnkplat--h-
---id------akm--ygn---hikl-lat----a--------et-----
-ls-------------rggh-flrv-----e-----qlv------ends-
--yd-e--------ted---------kpm---------ggh---kgg
>H
---any-hfhihl---lyil----------qlchg--kv--lplgeteg-
-adlr-dqgqtsrvlgla-----e---------------------ltlk-
--------l----a--f---n--kne-igaypcgfk-ldscqfgh--edf
p----di-siftyiieintavss------rkd--s--avq-lgh--ggag
---rlakmdlsaek---------s-------g-h-dgvgppappsa--gr
ys--------dkevf----------dl-vdqdsvsfampfvtpksp--a-
-arfvrqaq-sseki---ckknflsssiek--pgpmplvwvvrfq-----
---k-----vtgtc------------a-f-afgckfllgafahaltadlq
rlefikcan-vd--tndk----lgpgvdtsaktr---ar----a-acstq
tetv--------hlr---ls-rmaailecr---k---------kgy-tvl
qgfvlf----s-ngtlivltvqas--a------e-l-----het-ih---
--tf-p--s-ylfqthfka-g--------en-------------rnklva
------------d-------------lg--yt---dqyiesyatetv--k
--aavnwcgasldaaiswdl--glda-v--qrkltksgle-----d---l
rigtnlw---hdmlldapak--------k------------sriagd---
--gasv--qkvpg------------gygwvgvf-tpntrmlgl----fq-
iret--gsp-e--k---pvsl-----l-----------------------
--lynev-----------qa---------av-------------dktshn
---ls------i---------lase---andsnlsegdvykdyt------
-l----ayvgvpitsk---lgfigfwgsgtdngskak--fhsqpekahgd
ggmsigqkalvtchlvp---------lqlq---ldlrg-ge---kvt
>B
------rqydlhrgd-ll-lcygicatlila--fggeep--l----gse-
-kg--r----crv-lgfdl---rqady------------cd--dhl----
---------------------------lggvvc-tki----eflscpld-
e----agga-----i-ay-----------tee-grgc-e----p------
---siggs------nnavageaya-------g-gvlgi---gaktr--sv
fl--------apr--lsilrtkgkcelv------tvn--av-----qksv
hvall--------av---taretwgv------------vwkt--r-----
---g-----iitge------------lryklv-----yap--y----mie
alqfvvcgaqaa--ssnkdnvfqelgpehskegc---sd----f-ptgnk
tff---------hk-------sqtlnmper---n---------ksygad-
--ft------rlk---iamigefg--s------gl-dy---qen-sphg-
pggv----ppy-------dhayg------rp--catgtg-----hvryfd
vhgsrklqfawfkrc------qcvlklkman-lsvdsw---gd-en----
---------ea------h----gaagmp--ltyskg--ls--------ql
-------------------t--------km-al--------gs-dcq---
--trtikcd------------aaqggvarv--------ll----------
------snk----nvaavt-------l--------------dkfvmlqgl
pngcasmkppgyyvr--gdnsk---e-l-----------------a--h-
---kd------lml--h--g--ggkl-len----i--------h------
--ggaialt---daeg----pflaf-----g-----rfm------ive--
--lq-g--------tdq---------ari---iapra-fgtepfqtt
