>node14
----pfrflt-----av------savdvaafgcfv------kddkdgls-
------------dnqa--nhpv--------lhtll--------h--nggp
der------t-gp--fhc----------lla-------pttv-cqpeytt
pgfak---eet------r--------c--ghq---i--------tafdsl
t--------------ndke-----k-d-rcvkv----yv------eikks
vn--------vnd-a---ks------f-ka--dcntvmqf----el----
--------s-------p--wwr-----------g-------velehsecg
---------gg--pinhck------a-tc--rhqkgfp-p----------
--------r-rtakvldtt-q----s--qsi----gdw---ed--dv---
gca-ic------a-e--t--fggp-gyrgs--n---s--emesakh----
-----------------la-----------------g----y---l----
-----a----t-cg--hiaasgllete--fis------------------
--k-a---hd------kis--e------------------gl--slltd-
----ds-khr------gksgvcgl---q-------------vggip--ns
ypkpkg----egddadk-------------r--e-a--------pqfp--
vksevk---aqkkvyk------------kn-vnitv------------m-
----v-----as-----ghthdac---swg------------------df
-lqspqvtkak---vl--i------gkty----s-hiiysg----d----
--q---lse----ty---td-cftkk-gsecrnflg----l-svrel--k
-h-----vvce-sfglveehp-ik-----lgt-----f---vsvgl----
-----ttgactsi----------griqk--gnl--l--gryqsaytrtq-
------------tw-----gv----aqggskptfdkakvn------ail-
-avkp---------svygve-------gte--ktaeavakfl-------a
nvgt-pyksknry----ipspa
>node3
neggpfr---nnnvkas------svl--------k---yglgglhdaln-
------------ddqaeykkssa---llpgltqll--------qggrgca
-----------gg--fqs----------l-----------------iy-a
igylk---esg------knqkpvgkgg--kia---i--------lgfnsl
a--------------tnkd-----k-parcakn----yk------nt---
----------vta-e---kn------y-rr--dckselr-----el----
--------hvnvsifka--wwr-----------daarpttehe-hwaacd
---------gs--pngqck------m-kd------ay-----kk----fn
qgel----a-ktsalldspde----s--n-----------------v---
a-a-ic------v-e--e--fgga-lfkst--n---k--dmqrgpe----
-----------------lp-tl-----vray---qda----s---r----
-----g----v-cr--dtdawt-leea-gfmd------------------
--kcn---n--------it-llkgtdpkegsnal---eqggl--amfk--
----gpfsd-------knapgasq---sl----------v----------
ipd-ta----hgenrds-------------r--e-c--------adfp--
vng-edpgqnanrcyh-fdrshatpakgkk-g-vnv------------yr
fseag-----tp-----gnvqnig---sws------------------gf
-lh-------------llm------gkv------khrtshe----e----
--h---lsraycdiy---tg--ftak-tsgct---g----lpndmrf--k
-t-----cigg-g--vvedyp-ed-----ll-----------qrflk--a
ynlvstsvgckcm----------grllq--aglvrg--g-yqcvlv----
------------qw-----gv----aagpkrpqfqqakws------ell-
-tgkp---------kaygke--------------tesvskfl-------h
pvst-awkcmv--ffckyaeld
>H
----afrftt-----cv------apln-------vs-----kedndglgd
rhlsti----ftgird--pqkv--------d---------------sgaq
kdralykeyl-ga--fhc----------lllk------vaev-cwpeyss
pgfst---ede------q--------c--ve-danl--------rgyksl
a--------------anaesishek-e-sciev----yc------ti---
----------vhh-c---kg------f-kvgalcdhlmrf----elkrn-
--------a-------l--ww------------t-------v--ehnecg
---------ap--pvgvcdptelltd-scarsc---qp-p----------
--------g-rl-kh-ah--e----g--svi----gvw---eg--dl---
gca-tc------a-k--s--v-------gtk-n---s--dkqeqkh----
------------------a---l-------------galtey---l----
-----adahat------laasgilqte--flt------------------
--k-i---ds------nlt--a------------------anpvsaetd-
----ht-alp------gkttv--e---q-------------igtvp--a-
--kprn----kgggddkkgescrlnakhyhp--k-avkvh----palp--
kktdgk---aakkvfpq-----------nq-itasiqidyvstailcrl-
----v-----dc-----gdphkkcfalcwg------------------tf
-lcsadehrtk---vl--i------gkiy----m-npdfgt----a----
--q-----------y----qrcfeet-tkacrnfld----l-lsrel--k
-h-----gicvsmfalpedae-v------ggv-----f---vtigl----
-----ksepcral----------vrfqk---av--k--gqngkafkgtp-
------------tw-----av----gqhgsnpamdsmkvn------asvq
vsdri---------gpyavk-------gqd--taaiec-kfl-------t
nasg-pykckdty----lcgha
>node6
----sgr---dkas----------ll--------l---ygpaglpqgkn-
------------ddga--tkah--------lvstl--------q--rggp
-----------gs--fhc----------l-----------------vy-a
vgysk---egt------l--------g--ara---i--------lefdpl
a-------------vtdkn-----n-e-ssgkn----yk------nakta
t-------------e---gsag----y-r----cttnlq-iss-nv----
--------t-------a--wwr-----------t-------vq-ewdscg
---------sg--ptshct------m-hs------gyktagakk----qg
igel----k-ksa-vldqa-e----g--gafgkvksaw---gd--eg---
a-t-ic------i-e--alsfgga-llkgn-ed---g--emqkdsh--pn
sv-ep--ivsaetlvcglpita-----vpay---dna----gttil----
----pg----v-cr--dknawk-leqe--fmy------------------
--k-s---e--------t-----------------------------k--
----gs-rn-------akvgatlv---ef----------v----------
fpk-sa----sgdekev----------------d-c----gttkfhfp--
vngn------------------------kt-dgvgv------------t-
----i-----tp-----gkgkptl---dwt------------------ef
-lqaplgiets----vlsf------gtiy----gghraskecftkqrarp
dee---lsqgakhsyyrrkg--htnklrsgci---g----lppelsf--k
-sa----cvca-g--ivedyp-ik-----lv-----------qv---qkg
-----tradcacirg-atlyflnsrllrpmiglvkv--g-yqcvlakts-
------------sw-----sv----aeggkraeygr---sfscyklliv-
-alep------------gqe--------------aasvaqff-------y
hvat-swkcma------apgpe
>E
----gfrfvt-----gf------ngldiaaygcyd-pt---rddrdnls-
------------dnrs----------------svl--------d--ests
dqr-------------------------------------------aclk
-afer---hessnkfash--------clkgpn---vtaawaspqtnfdsv
a--------------qdk--------d-rckkp----he------eitkg
ldv-----slvsd-vavppn------l-----vcd--mq-----dv---k
fsyklrain-------s--whkedl-awvgpgsn-------velevahcg
-vacaaiyrgg--eiyyck------i--c--kqehglp-p----------
--------wsraasvlntt-h----s--qeg----hgy---dn-leirvg
gca-vv------g-c--h--fags-gfagl--h---skgdsntt------
-----------------la----gl-----------g----f---l----
-pee-d----t-cg--et-ig--leta--fislakmvhkvahkknar---
vsk-s---ndyepslakitm-e------------------gl--sll-sk
pftlka-k-l------s---tcgv---q-------------ag--a--aa
kfsnig-----gdatnk---------------------------cq----
-----------pgiym------------kk-vnltg------------i-
----l-----ac-----gpthiic---kwr------------------si
-lqsphgekaktvev-----------tsy----r-hvayar----y----
--dgnplra----sy---tv-cypk------knilg----l-nttlltek
-n-----vmcf-mlgdsephg-fkaahralfvpgefaladlsgtgs----
-----dqaactmi----------skla--------------qfpyt--r-
------------dk-----iv----ag--qkptftgeqst------eil-
-qv--------------qadcllhikddadssksaesgakfiddvvvvhm
nigigpylskg-------pga-
>A
neggpfr---nkciias------avh--------k---yglgdlhdtln-
------------ndqaeyikssaschllpglhpql--------qgesgca
-----------eg--fdp----------l---------------------
---le---gsg------kn---vdrgg--kts--------------f-gl
v--------------tnks-----k-pakcark----yk------tt---
----------vat-e---mn------y-rr--dckdeln-----dl----
--------hitvavytakew-r-----------naarptlehd-hwasvd
---------gs--degmck------m-ke------py-----kksygivr
hv-l----e-kasnllentdd----svgn-----------------a---
t-a-ic------v-e--d--lggaevfv---------------gpe----
-----------------vp-t--------------dd----t---r----
-----g----v-cravdtdawt-lsea-gfme------------------
--nch---e--------ds-llkgtdpnegsdal---engav--tmfk--
----hpfid-------knaegaae---gqceilskpvket----------
igd-aa--pvlgqpsds-------------rfie-c--------adlp--
vng-kdtaqkdnrc---fdpsrnttangk-----vi------------yk
flqag-----tp-----stv-gvg---sws------------------gf
-la-------------lla------mqv------khrtl-e----e----
--e---lkralceiy---va--fsak-tsgct---g----vagnmrv--k
----------------v---p-da-----le-----------hrflk--p
cdmvkkntgskcl----------ahlle--adlvqalsg-yqcvlv---l
stdtyiksrgrsqwwkgpkg------------afqsp-ws------qlw-
-tkiskimndksasksygke--------------fetackfl-------h
pvst-iwkcmv--ffckyvele
>B
nekgsfr---nnqiqgs------gvl--------k-------glhraln-
------------egqaahnkss--------ltqla--------q--rgca
----------tag--fqs----------k-----------------ly-a
vgyliasiesg---------kpvgpgg--tia---i--------lgfksl
g--------------tdks-----v-paktakn----yk--kvasns---
----------vaa-i---ky------ylrr--dckgdlr-----ev----
--------eldvsvlqt--nwr-----------dairatmeha-hwplca
---------gt--pngpck------m-kd------ay-----ek----fy
qlel----g-ktsallqsaae----a--e-----------------t---
a-a-ki------dae--e--fgga-lfrst--t---n--dltrgpf----
-----------------ap-tl---skvray---qna----s---r----
-----g----v-cr--qqdaw---dea-gfvq------------------
--kcgfaen--------cn-llkgsnppeganslkkyergal--nmfk--
----galsd-------knapeapechstl----------v----------
ipd-kp----kgenmds-------------r--n-s--------ntfplk
vdg-edpgqndtrcyh-fdpphatagkgkk-g-i-k------------yr
lsqag-----td-----gsvqnig---sws------------------gf
-lh-------------vvm------gkv------klrgshe----g----
--h---l--aycdih---tg--itvk-tvgct---g---yvptdlrf--k
-t-gkdtcvgg-g--vvenyp-eg-----vq-----------qrgln---
--ii------kam----------pmllg--mglikg--q-yqcvmv----
------------qw-----gv---kaanakrpqfveakws------elf-
-enkr---------kaygkd--------------sesvkkfl-------h
a-st-swrcmv--ffceyaqld
>F
----pirfva-----gt------ngldlatygcgt-sn--------dms-
------------dnqe--khdi--------lhkvl--------n--essp
der------a-nisafhc----------lp-----------v-cetsysh
pgfhk---rdttlksisq--------cikgkk---v--------ksfdgl
gceydvddaqkiak-hhke-----f-q-rcgtp----ye------qivkg
anikgslaslvfk-v---rg------l-ka--rckkvmqi----pi---k
ipyklkssw-------p--wwhealsew-cagrs-------laqshshcg
gskcmlayygsfleinhck------a--c--kreqnmp-r----------
--------wskntnymdtt-qgvfes--qdi----adw---nn--qvqet
tcp-vc------g----r--frap-pissv--n---stgktpptrh----
-----------------lg-----------------g----f---ledif
lahk-a----t-cg--stagg--lqcs--f--------kve------vsq
vsr-a---td------kisl-m------------------gl--pl----
--------------------tcqm---r-----------------nlskp
ktpplg-----vdatqk---------------------------ph----
-----------ksiim------------kd-vnitv------------i-
----ttqgeascayvakghthd-------s------------------nv
-l-tphaangk---vt--t------tksy----r-yivyas----e----
--apdrlna----sy---aa-qytrk-vaecthflepsp-l-hvrdlter
an-----vmcv----iaeeha-fynr--elgskndtqf---anvkl----
-----nqtmcssi----------grfa----------------pys--r-
------------tw-----npgmv-at--dkvtfnkvqse------eil-
-g----------------------------------avakfl-------m
nvni-pyltrn-------sspa
>D
----sgr---dkss----------li--------l---ygptstnqgks-
------------edga--ttah--------lvgtl--------d--rgga
-----------gp--f------------------------------vf-a
tdfkk---dst------l--------g--ars--------------fdkl
a-------------vtesn-----trd-angrn----ykdv----gtkta
t-------------e-------------k----cttes---aywhv----
--------v-------f--wwq-----------t-------tq-ewsscl
---------sg--kashst------m-dh------gykipgamk----qa
igdl----k-kks-----e-e----g--gtfakvksfw---sn--dg---
a-tdiatvnklkv-e--alsfvel-llggn-dd---g--dmvkes---pn
sikqp--ivsgetvgcslpftg-----vpgy---gst----gttll----
----pg----iach--dktswk-leqdy-fly------------------
--k-g---e--------t-----------------------------k--
----gs-rk-------akv--------------------v----------
fpk-kaa---sgsekdi----------------n-c----fttrfqfs--
vngk------------------------kv-egmkv------------t-
----i-----tp-----gkgkpal---swsphfenlvspmtgkvlcyrey
-lqsplgvems----ilpeldm---gaifapepgghkas-ecfnkqvakp
add---lsnganhvycrrkg--hvnklrvaci---g----laaeinf--k
-aa----csva-t--iihdyg-ik-----va-----------ev---qks
-----trvacacvkae-----lqtrllrpmggavkl--g-yqcvvlkts-
------------sw-----sm----slggkrgsygq---tyscfkvliv-
-alas--------------d--------------aaavi----------y
hvts-pwrcka------dkgpe
>node15
----pfr---dnaikav------avlnaaafgcfl------kdikdals-
------------dgqa--thas--------lhkll--------q--nggp
-----------ga--fhc----------l-----------------ey-s
pgyak---eet------r--------c--vag---i--------lafqtl
t--------------ndkd-----k-q-rcvkv----yt------eikkg
ln--------vad-e---ka------f-kk--dcntvlqf----el----
--------t-------p--wwr-----------e-------velehaecg
---------gg--aanhck------m-ac--qqqkgyp-l----------
--------r-ksarvldtt-e----s--qsigkdksqw---gd--dv---
gca-ic------v-e--a--fgga-aykgt--n---g--emesaph----
-----------------lptal-----vp-----dea----t---l----
-----a----v-cg--ndnawg-leee--fms------------------
--k-a---nq------kis--er----------l---gpggl--kplte-
----es-ks-------skvavaal---ev----------vqvgnip--tn
ypk-kg----egdepdk-------------r--d-v--------aefp--
vngevk---apkkvyk------------kk-vnvsv------------d-
----v-----as-----ghtqnns---swg------------------ef
-lhspqdtkpk---vvaav------gtty----gkhlkcsd----d----
--e---lse----ty---tg--ftnk-gsgcsaffg----l-nemdf--k
-a-----vvce-glgvvedyp-ve-----li-----------svllkhed
-----tkvgcssl----------grllk--aglvkl--gkyqsanirtk-
------------tw-----gv----aqggtrpgfnrakvs------lil-
-tvkp---------riygke--------------tdsvakfl-------n
nvst-hyksksry----iprpd
>G
----pyryls-----cfgttkvdsald----gcgcg-----qnekds-a-
-----lhgklf--ikg--dqpv--------l---------------gget
dervvyaeym-ga--srtrkhtfyclg-lqvnggaeqfvahivsf---s-
-glaa---adt------t--------c--vdqsqnt--------kpfdsf
p--------------ande-----k-p-pcvelyknqfs------dlp--
----------iqh-a---ng------f-el--lceqll-------l----
--------p-------t--wws-----------t-------v--aqtscg
---------ag--pighcp------a--carkc---kp-d----------
--------s-ktanvlas--y----s--ysv----anw---dqf-si---
eca-yc------a-k--s-----------sk-s---s--qpmdanhpn--
------------------f---q-------------g----c---l----
-----g----t------vapgglltte--flh------------------
--r-v---td------kvt--l------------------glagssate-
----ds-sfd------gkkavcgs---q-------------vpeip--ds
fpkprg----egsdehkedvscrltarhyhp--mdgeeva----a-----
kktksg---sskkafr-------------glvriaiiid---------l-
----e-----vt-----gevsgacmelcwg------------------tf
a--------------l--v------grty----m-hrcygg----v----
--q-----------y---ke-cfedk-tkacrdflp----l-lsref--k
-h-----gvcqsnfalceehsli------ggt-----f---mtipl----
-----grggcisl----------akl----gal--k--gkdqsassknp-
------------aw-----av----gqvgrkpaldsvnin------avlq
vnvkl---------gvygte-------gre--gagid-------------
--tg-py---diy----vtphp
>node13
----pfrflt-----ci------tald----gcfvs-----kdekdglgd
rklsil----f-sirn--eqpv--------l---------------sggp
ddrslykeym-ga--fhc----------llik------vtdi-cfpefts
pgfaa---edt------q--------c--veqneei--------kpfdsl
t--------------tnde-----k-t-rcvev----ys------evr--
----------vhh-a---tg------f-kv--lcdhlmrf----el----
--------p-------p--wws-----------t-------v--ehsecg
---------gg--pvghcp------a-scarkc---mp-p----------
--------s-rtakvlan--e----s--tsi----gnw---ee--di---
dca-tc------a-n--s--i-------gak-n---s--dmqeakh----
------------------a---q-------------g----y---l----
-----a----t------laasgllqte--fld------------------
--k-i---dn------kvt--v------------------glagsaste-
----dt-shp------gkksvcgr---q-------------vgsvp--ds
ypkprg----egsdedkkdescklsanhyhp--m-akeva----pifp--
kktegk---askkvfk------------kg-vnitveid---------l-
----v-----ac-----gdthdacfalcwg------------------tf
-lcsaeqnrtk---vl--i------gkty----m-hrnygg----a----
--q-----------y---ke-cfeek-skacrnflg----l-lsrel--k
-h-----gvceskfalveehp-i------ggt-----f---vtigl----
-----stgsctsl----------ariqk--gal--k--gknqsafkktp-
------------aw-----av----gqvgsnpafdsmkvn------ailq
vsvki---------gvysve-------gqe--nagienakfl-------a
nvtg-pykskdiy----vssha
>node10
----pfrfit-----gi------sgleiaafgcfv-sn---rddkdgla-
------------dnqs--nhpv--------lhkvl--------n--esgp
der------t-di--fhc----------lp-----------v-cepsytk
pgfqr---qetankttsh--------cikgqq---v--------tsfdsl
g--------------ndke-----f-d-rcakp----ye------ditkg
idv-----slvsn-v---rg------l-ka--rckkvmqf----di---k
isyklravs-------p--wwneal-awvgagsn-------velehshcg
-vtcaaayrgg--einhck------a--c--kqekgmp-r----------
--------wnktanvlntt-q----s--qei----hdw---en--evrvg
gca-vc------g-s--q--fagp-gfsgv--n---skgesastkh----
-----------------la-----------------g----f---l----
-ped-a----t-cg--htasg--lqvg--fisipkmvhkve------vgq
vsk-a---nd------kitm-e------------------gl--slltn-
----es-k-k------a---tcgv---q-------------vg--p--ap
kpspig-----gdatek---------------------------pq----
-----------rdvym------------kn-vnitv------------i-
----i-----sc-----ghthdvc---kws------------------nv
-lqsphgakak---va--i------gksy----r-hivyss----e----
--aadrlsa----ty---ta-cytkk-aaecrnflg----l-svkqltek
-n-----vmci-mfnlaeeha-frsshralfskgdaqf---astgl----
-----nqgactsi----------grfak--ssm--l--t-yqspyt--r-
------------tw-----gv----at--dkptfnkaqse------eil-
-av--------------evd-------gtetvktaeavakfl-------m
nvgi-pyltkn-------psps
>node7
----pfr---dnavkas------svl--------l---ygpaglkdaln-
------------ddda--tkas--------lhsll--------q--rggp
-----------ga--fhc----------l-----------------my-a
vgyak---egt------r--------g--ria---v--------lgfqsl
a--------------tnkd-----k-q-rcvkn----yk------ntkka
ln--------vtd-e---ka------y-rr--dckselq-----el----
--------t-------a--wwr-----------d-------va-ewaacg
---------gg--panhck------m-ks------gypmistkk----sk
igel----r-ksakvldst-e----s--nsfgkdksqw---gd--ev---
a-a-ic------v-e--a--fgga-lfkgt--n---g--emqrgph----
-----------------lpttl-----vpay---dna----g---l----
-----g----v-cr--etdawt-leee--fme------------------
--k-n---n--------it--dk----------l---epggl--apfk--
----gs-kn-------skvaaaav---sl----------v----------
fpk-tg----egderds-------------k--d-c--------sdfp--
vngdvk---aakkcyk------------kk-gdvgv------------d-
----v-----tp-----gkpqnts---sws------------------ef
-lhgpqdtdpk----vlaf------gtiy----gkhrgsne----d----
--e---lseaacnty---tg--ftnk-hsgct---g----lphdmsf--k
-s-----cica-g--vvedyp-vn-----li-----------qvllkqes
-----tkvgcscm----------grllq--aglvkv--g-yqcalvkts-
------------tw-----sv----aeggkrpqfnrskss------lil-
-tvkp---------ksygke--------------tdsvakfl-------h
pvst-swkcma------ipspd
>C
----mgn---etag----------ll--------l---yghanlpqgkd-
------------adga--tksh--------lvptltdagnrgmg--rggp
-----------gs--lgh---------fl-----------------vy-e
ngysk---agt------l--------g--ara---s--------leldpl
a-------------vtdkn-----n-i-sapkp----fk------sdksa
k------------va---gstgkacr--r----cngnlq-iss-nv----
--------t-------s--fws-----------k-------lq-rwkvcg
---------tg--ptghct------lehk------gykdaggkk----vg
vgglknnik-ksa-vleev-r----s--galnrvkpawsei-n--eg---
a-s-mh------l-elgavrftga-llkgn-ndldpa--dmkketh--pn
av-dppgdvagvtlvcsypiat-----vagyrkkdne----svtil----
----p-------yr--dkqswk-lkke--fmh------------------
--k-p---e--------t-----------------------------k--
----gt-rd-tkrsehanvgctlv---eg----------a----------
tps-sd-i--spedndi----------------d-c----gtak--fa--
-------------------------------davgi------------t-
----i-----tp-----akdkpsl---eli------------------if
-vanpmgietq----vpsf---iligply----gg-----ecytkpay--
dmn---lsqgakhs-----g--hthkaqsncy---g----lppegsf--k
-sl----cvca-g--vvedyr-i------li-----------e-------
------rgdcacvrg-atlyflntkllrpmiglvtv--a-ylcvlih---
-------------------sv----n-ggkrteygr---gfscfklaiv-
-llep------------g-a--------------kitvceff-------y
pvgt-swgs-a------apgpv
