>C
----fspsvclfaiv----avaqr-gvg-dllt-a--latgqayifg--v
eaygsl--t---skk---kg------esvsp-------f-fr--knykal
vagakrspesvyla--------wf---------ishs--pg--l-----v
s----pl-----lsc--yqk-a---ac----nh-------------nngp
----------------t---and----dg---------vp-----nkgsg
spvf--------fvne----------------------------------
-----dpyg--nnas---r-------ygdvfiraravnrvc------s-a
f-------fgslg---g--shgkss--------------tva--mgagdk
nqvae------al----------l----w---------d---n-----k-
-clhicfh-m---------------kklltd--------lar-kdphg--
snwqs------------lnssgmrqn----------------sglk--tk
----------r---av-vsvtt--qn-gienhhekfr--dsaahv-----
------------------------v----------nn-----kpft----
---ha--gtrttlalp-envfn------agd-----sqaggavlrplhl-
------------g----nnp-dthedys--lrkfn--ggpf--------f
ag----gggspnkpdqks--tglk---------tv---------s-----
-knvvalsaptsk------dnrk--mrf------w----emslssv----
----dakitkitkghr---iagsg---tfg----------sv---lgcca
sg-ps------llve----------------------illhs---l----
-----e----------------------t-------lge-hv-sssl---
----------t--------gkevvlgleqsrf---sqryilrkigla--l
-----ahhystfg---r-pt-kal-------sg-----tfthdla----d
hgrge------s-lsita--------------------------------
-------rldlwaqgpyvgsq------cntf-lhldnnn-lii-gthssg
-gkrgtgkemc-----------ilpyrs-------g--ki-----a--na
ksapetl--
>node7
----aap------lv----tiegr-amg----c-s----ag-aylfg--v
nn--gfy-t---gha---eg------ttits-------f--r--ssaqat
gtct---------n--------wf---------giht--ne--l----da
k----pf-----nsc--fvk-t---ac----nr-------------nqge
kv---------rpsqst---gcd----sg---------kp-----skgtg
kntf--------fanda---------------------------------
-----dpyg----rs---r-------yg------------c------sgg
f-------ygkfa---e--nnlrkp--------------sva--igatls
ikvag------en----------l----w---------a---g-----k-
-clhicnq-e---------------krll-a--------lhp-t---g--
eswep------------ls-----dnfl-----------khqsglq--tr
----------g---pt-at---q-kk-getalh---k--dsaahv-----
--------------------dnr-a----------er-----kdfp----
---nh--gtrcsldsp-ts--------kkae-----skggsaimtp----
-c-----ff--kg----sdk-qth---aqigqhkk--eggl--------y
attietgdgaphrsqqht--n--p---------ai---------s-----
-gniigltma--k------edrk--vrf------w-------peesn---
----iak---itqghk---vkgfsiknrfvsg----q--del---lgcca
sg-psln---tlvvp----------------------flltgwvfl----
-----sklvi-----a-----------lt-------saherq-p--l---
----------a--------g-easfrlehaqy---yqky----vgla--l
-----adly-t-a---q-aa-kamkfsd---tg-----plshald----d
sgr-h------v-lpadslslkiveygvd-v------rssts--------
------rrtelwtqapy--sk------cdsl-lsldnts-lia-gtdssg
d---------c-----------llpyra-------g--ki-----a--ga
kcipetlsh
>node14
a---van------lv----iaedv-dmg----sks----ag-dylla--i
ag--gfsrt---gke---e----------nn-------f--r--ntevgy
gacs---------d--------wf---------gtpn--ne--l----da
k----pqkagasics--fvt-v---ecgvspsrtn--mskenlrtakd--
-a---------ktqean---gcdkestkg---------mp-----gkqta
krsf--------fgddkngavel------qlnlp----------------
-ahaykpyn----ra---r--ence-lg------------c---ncapgn
f-------cvsia---drrdnlrka--------------etg--vgasma
kkls-------lk----------l----w---------s---g-----a-
-dvytcne-d---------------krll-e--------lhs-a---s--
hd----------------------deyl-----------khqtglq--tr
----------g---tt-vh---d-qaksatshq---l--df---------
--------------------egk-v----------gh-----enfakew-
---nr--ntrc-t------------------------egagmmmtp----
-c-----ff--sg----s----------------g--kvdv--------y
gttisindg--nr--------------------pv---------i-----
--nifdvtks--r------gdrtsaigy------w-------pesrk---
----sek---il-----------------vnv----h--lnlg--lacca
pk-psms---slvvpnykwsri-qv---m--ll----flltgcdfhvvy-
----nhdvfi-----a-----------lg-------cshske-p--l---
----------a--------n-qfsfhlen-a------------vala--l
-----adly-i-e---pvve-----fqe---tg-----plghafync-rn
ggh-q------i-lpgks---qltefg-m-v------ikivk-f------
--ssipwhgtnraqhpy--pa------pdsv-leldspsvygp-ggnteg
g---------ckp-------a-wlp-pv-------g--km-----a--ga
qc-vdt---
>G
e---nac------ll----vmadt-gnep---sksdi--pg-qfvvt--l
an--kfqrg---gke---n----------nd-------f--rtsgr----
-nmp---------dmpi-----wf---------gt-k--kd--l----dt
k----p----qkfcd--yvtpk-----gvsvgstg-------t-ttsn--
-m---------paqv-a---gcesetkav---------snasetlnkavl
kksf--------sgqeknpsvel-----lelkl-----------------
----gkpynrg--k-glsr--edvh-lg------------ctsircvpak
f-------ciivg---akrenlkiat-atsknv------eq---------
qkqg-------arhdvyahldgtl----wiqveeyqiig---g-----g-
-t-yncns-tsrrqitarc-napiykhll-p-------------------
-h----------------------aeylcvrtgksylk-kqas-fefvnr
-------------at---l---qthhqgeptqp---lckdy----vf-lr
tekiagktkckgdgwmlqrkeg--v----------chmgh--asya--w-
---tcr---------------------------------msmm-------
-----------------g----------------v--qlmvtviavravw
kp-v-knne--a---------------------avg--------i-----
--ggfhvsmt--r------gln---vgy------w-------pegtk---
----avl---il-----------------vgaggfshgglslnm-laccl
hk-pgag---vlvspkyqwlri-qv---m--llky-afa-------ttye
nkqnklgvfv-----t-----------lgkq-----sshakd-p--v---
---------------------efglstdk-l------------legt--l
-----aepy-i-n---algn-----wqe---ss-----tlghlfyac-t-
eaq-k------i---ads---qdlkli-mnv------ik-vqrf------
--s--pwqgtdrgecly--p-------qgte-lelafpiiypq-ttnkea
e---------ckp-------s-wfp-at----dgqg--rm-----q--gg
ac-mat---
>node15
t---vad------lv----tiegr-dmg----css----ag-aylfa--i
tn--gfs-t---gye---hs------dtesn-------f--r--dseqsy
gact---------d--------wf---------gihs--de--l----da
k----pf-----ncs--fvk-v---ecgvspnr-------------kekd
ke---------kphess---gcdkettkg---------kp-----gkgts
kntf--------fgdds---------------------------------
-----dpyg----ra---r-------lg------------c---ncapgs
f-------cvsla---drrtnlrkp--------------etg--igatma
kkvas------lk----------l----w---------s---g-----k-
-nlntcne-d---------------krll-a--------lhp-t---g--
qs----------------------dqyl-----------khqsglq--tr
----------g---tt-va---q-ks-setghh---k--dfaaav-----
--------------------dgr-v----------gh-----kdfgs-r-
---nh--atrcstaca-ts--------ktae-----thgasmmmtp----
-c-----ff--kg----s----------------g--daav--------y
attisigdg--nr--------------------hi---------s-----
--niigltma--k------gdrtsavry------w-------peerk---
----tek---it-----------------vng----q--ldls--mgcca
pg-pnme---slvvp----------------------flltgwdfv----
-----hkvyi-----a-----------lg-------sshsrq-p--l---
----------a--------s-efsfrlehae------------vgla--l
-----adly-v-a---p-va-va-kfad---tg-----plnhalnnc-ke
agr-n------i-lpghsaclklvefglm-v------lsivg--------
------rhselqaqnpy--st------pdsi-lvldkpspyva-ggdetg
e---------ckp-------e-llp-ra-------g--km-----a--ga
kcisdtlsh
>node10
a---vss------lv----iaedv-emn----tka----fg-dyeva--i
ag--gfqts---gke---g----------nk-------fl-r--nvdagy
gtct---------e--------wf---------atps--we--g----dp
k----tqkagmslcn--yvs-v---dcdi--srttpqifkpdlrnsfn--
-v---------iagdah---gpakksgkg---------lr-----gnasv
nrnl-------------tgalkl------gltlptvasnfy-----ahkt
tahaykpyr----rg---rep-----------------------acgp--
--------cvala---ekrdnlrkp--------------esg--agagkt
srlt-------lk----------l----w---------s---g-----d-
-seytcne-d---------------krvl-q--------lhr-a---w--
he----------------------ddfl----------skhqtgvq--tr
----------g---vg-vh---d-dvk-----------------------
---------------------gkti----------ge-----dsfakgwt
--ink--n-hc-t------------------------fganmmmip----
-s-----ff--sgdgggs----------------g--kvdv--------y
glavaa--g--sr--------------------qv---------v-----
--nvfdvaka--r------gdrvsaigyygl-atw-------pepks---
----sev---il-----------------aev----h--ldlg--yacce
qkdeaks--mglivpyykwprikkvsgl---nl----flltdtdfhvvy-
----thdvfi-----a-----------sg-------cggtkg-p--l---
----------k--------d-efsfhled-a------------vgfa--g
-----adty-i-e---p--e-----fqq---tg-----plg--fync-rt
ggh-g------v-ipges---q------m-p------ikiik-f------
--ssipwhgthhaahpy--pa------pesv-velhspsvinp-ggntdg
s---------ckp-------acwls-pv-------e--fmvkvats--gp
qc-------
>E
a---vls------lv----iaedtegmd----ttg----ig-dygia--v
ag--ggqst---eke---g----------kk-------fl-r--dgdagy
alct---------a--------wf---------aktshtwgiagttdqec
q----tqdagmflcp--yvt-v---scdv--arpapqifrpamrtsfa--
-l---------vaasthqsiqhakrynkg---------lr-----gnn--
--g--------------tgalkl------pqtl---aatfy---------
---aytpf------p---hqp-----------------------pcgp--
--------cvsll---dkraehrkp--------------nss--agaakt
srvt-------lk----------l----w---------s---s-----da
gseyacke-d---------------rrvq-h--------lqs-n---w--
hd-----------------------dvl----------akhqpnvq--tr
----------g---vg-th---e-tak-----------------------
---------------------gkti----------ag---lgqniimewt
--ikl--s-hc-t------------------------igangmmvv----
-s-----fl--tqdgggp----------------s--kve---------y
glavda--g--ga--------------------qv---------v-----
--dtfsvaky--ktagtlagakkaaigyygl-cgw-------papkg---
----neg---il-----------------gd--------lelg-ayscce
qkdddkt--tglv----------k--------l----illsdqefhlvy-
----rhsvii-----e-----------st-------ctgakg-p--l---
----------k--------d-eltfhieg-t------------lgfa--s
-----aday-a-pgdcp--e-----fqr---tp-----pfg--fydc-k-
egh-s------v-tgmen---q------l-pahntvaikkrk-f------
--talawhgphhaaq-f--p---------------rsansvspg--yqds
s---------tka-------acwla-pv-------p-g---kvats--gp
ic-------
>node13
e---tac------lv----iaeet-disn---sks----pg-qyvva--l
in--gfprs---gke---q----------dd-------f--r--gcdvay
gdis---------d--------wf---------gtpk--kd--l----dt
k----p----akfca--fvt-k---ecgvspshtg-------irttkd--
-a---------kaqi-s---gcdsessav---------rsasdtsnkqvt
kkaf--------fgddknaavel-----lqlkl-----------------
----gkpygra--r----r--envd-lg------------c---ncapan
f-------cvivg---prrdnlrrascatiksv------ekg--vgasma
akqg-------irhg--------l----w---------g---g-----s-
-etytcns-d-arst----ytaviykhll-a--------fd---------
-d----------------------eeyl-----------kqatglq--nr
----------aimas---l---q-hdqgasthq---i--ny----e-gla
tekvvgktkckgegwmvlreeg--v----------ch-----asfa--w-
---trv---------------------------------agmm-------
-----------------s----------------a--qvmv--------y
kp-i-tnde--ak--------------------gv---------i-----
--gkfhvprs--l------gdnttsigy------w-------pegrk---
----sel---il-----------------vng----hgglnlam-laccl
pk-pglg---slvspnyewlri-qv---m--lldy-eflftgcdfnvvye
nnqnklnvfi-----t-----------lskhrnqpdcshakd-p--v---
---------------------efglhidk-a------------lasp--l
-----aepy-i-n---plge-----wqd---ss-----plghvfyac-t-
ggh-k------i---ans---qltdla-m-v------ikivq-f------
--s--pwhgtnrgqcpy--p-------qdta-leldnptayps-dgnkeg
e---------ckp-------s-wlp-aa-------g--km-----a--gg
nc-vat---
>B
----gsn------ll---wsiegr-smg----c-g----gv-aylfg--a
ms--gf--skghgha---hg--nmettvvts-------y--r--cvast-
-------------s---atay-wl---------gfhg--se--l----gs
------------nec--egr-s----------------------------
-ekpygaqlkgrayshs---pcg----avtlgttkdacrp-----gngpk
kntf---------pkea---------------------------------
-----spyg----qp---s------tyg------------c------mvs
f-------ygafp-qps--stlrlp--------------einfp----ls
htrsg------nn----------lgmaaw---------qaapd----aq-
-cihictttq------------------d-a--------ahpar---q--
naw-pdiydrprynalkkn-----skfl-----------kqqlt------
---------------nkln---q-kk-aeralh---v--elgspi-----
--------------------p-m-r----------er-----kgfp----
---sq--pnrccldg-pta---gydaikkfe--pkasre-----tp----
-c-----y-------------qkq---hmggkhkksyeggl--------y
dtgv-tkdtapsptdfhtat---p---------pi---------s-----
-alyiglw-t--k------dyh----------------------qed---
----vak---iacailftsikglpvknrf-------r--eel---la---
---ahlk---ivvvs----------------------lllngtvf-----
--------vi-----t-----------ly-------nph--d-t--v---
------ynavs--------g-eatsrwnradynncyd------iglp--k
-----asly-t-p---s-kg-ikmk-te---qp----------le----s
agv-y------kllpsrsfassvpqygsd-e------k-s-d--------
------rrtqlwlkta---sk------cdnl-lllgkfd-lng-qvismh
d---------c------------lpyid-------d--ql----------
-giadsanh
>D
-kdpfgp------lv----tvegs-aqg-ell--a----agqa--fs--v
dn--ely-t---aq----ns--------vtc-------f--r--scypqs
yacd---------n--------wf---------di-i--sg--f-----g
c----sa-----stagsyvk-slildc----nc-------------nnse
ki---------qpeddt---gkd-----g---------vl------kgag
npgh--------fvys----------------------------------
-----dryg----k----r-------ag------------a------v-g
fscssafvfgkfgh--g--nqakhp--------------svv--msgild
edvadyagcakqv----------l----l---------g---g-----k-
-clhlcyq-l---------------pqvl-h--------agk-gapkg--
ehwnp------------vs-----eg----------------sgyk--kr
----------h---p--pt---q-ak-dndalq---v--gsapht-----
------------------------t----------dt-----kata----
---gg--atrteldlp-sn--------dkggrt---lkgas---sp---k
tc-----lfafkg----seplegh---g--dvnks--eggl--------f
la----gggn-nklqqla--se-k---------as-ayyeatwpt-----
-mniivmtaa--r------dsrk--vrf------w-------megv----
----sgkpngiikaea---vskfg---tfgqg----f--hnl---lgccs
ag-pslh---rllvn----------------------illhgwmfl----
-----qklvf----tq-----------at-------mak-hq-p-dlenq
nislka----a--------g-hisfklkhaqf---ytky----vgvs--k
-----kahy-t-t---r-pt-kal-------rg-----pfrhe-------
--------------sntnlclklfrfn-------------gm--------
------rkldlwfqyar--td------cdpf-lnldgnc-gve-gtdsse
----------c-----------shdykc-------g--ki-----a--ga
ksapeti--
>node6
----fgp------lv----tvegr-gmg-dllc-a----agqayifg--v
dn--gly-t---aqt---ng------etvtc-------f--r--ssfqat
vacs---------n--------wf---------diht--sa--l-----a
s----pl-----lsc--fvk-s---dc----nh-------------nnge
ki---------qppeet---ggd----sg---------vp-----nkgsg
npgf--------fvnd----------------------------------
-----dryg----ks---r-------fg------------c------s-g
f-------fgkfg---g--nhgrkp--------------tva--mggvlt
nqvae------ei----------l----w---------g---n-----k-
-clhlcyq-m---------------krll-n--------lar-tdpkg--
eswep------------ls-----en----------------sgfk--tr
----------r---pv-vt---q-qk-gddalh---r--dsaahv-----
------------------------a----------da-----kafa----
---gg--gtrtslnlp-sn--------dkge-----skggtailrp---k
kc-----ff--kg----ddp-dgh---g--grqkn--eggl--------f
aa----gggspskaqqnt--ngak---------tv---------s-----
-kniivltaa--k------dnrk--vrf------w-------mdsv----
----dakinkitkghr---itgfg---tfgeg----v--nel---lgcca
sg-psln---rllve----------------------illhgwlfl----
-----dklvf----sl-----------at-------maq-hq-pssl---
----------a--------g-elsfslehaqf---yqky----vgla--l
-----adhy-t-a---r-pt-kal-------rg-----pfshelp----d
pgk-q------s-lsvtslslkivrfg-------------as--------
------rrldlwaqapy--sk------cdsf-lhldnns-lia-gtnssg
----------c-----------mlpyrs-------g--ki-----a--ga
kcapdtl--
>H
e---sec------ligis-iaeet-enne---g------pg-eyasa--l
in--gffer---gka---q----------en-------f--r--hssipy
gkis---------q--------wl---------gapk--kd--l----gt
r----a----arfca--fvt-k---ecgvapedtg-------kkttkd--
-a---------rarl-d---gcdsist-v---------rsatetsksqvt
kkgf--------fggdkdagvdlfygsklhlkl-----------------
----gkpygra--r----k-----d-lg------------v---ncsaag
i-------c---g---prrdslkavscnsikgvlfct---kg--vgvpla
akdg-------lrhg--------i----w---------g-----------
-edyscn--e-ailg----ftgvvyky-l-gspaeaegnle---------
-d----------------------eeyl-----------krctgyd--nr
----------ammps---l---a-hdhgfstte---l--n-----v-tlt
tekmvgkvkckggpalilreqv--vgrvghlytcgcp-----psfn--w-
---tkv---------------------------------ag---------
----------------------------------s--evsv--------y
kl-i-tnde--qn--------------------gv---------vkdyly
g------------------gdnttscgn------wgksy---tdgrkk--
----tql---il-----------------vng----haglnlsm-lkfyl
pl-psngkn--lvrpqyqwlai-qk---l--lldeeeflytgcdfnvvfe
narnkvhvfm-----t-----------mrkhktr----hakd-p--v---
---------------------qfvvhvvt-d------------agde--l
sklarfdhy-i-n---plde-----wqdvgdaa-----alahsfyic-t-
ggh-k------i---vgs---vladlg-m-v------ieivq-yltdylt
gfg--pwqntnrgqcpy--p-vckqteqdtalieldhptgydc-dgrkeg
d---------ckp-------n-wlp-tsyeyr---g--mm-----a--gg
ns-gst---
>A
----gap------------------img----c-n----aa-gylfgaig
nl--gfy-ekgpiravhfegvyskkgtaivngktlelpy--p--h-----
--ce---------a---etgykwyarpyiigrpafhg--da--l----ga
------------nhi--dgr-s---ac----g----------------gv
kpkpyga---eraqqft---pca----avti------crp-----srtdk
ketfeiglslthypkda---------------------------------
-----dpyt----qn---r------kfv------------c------vpg
f-------fgelp-qad--stlklp--------------dhd--vgatfs
htrsg------qn----------l----w---------paspnvkqsgk-
-ilhicss-a---------------hkne-p--------lhpaa---kdv
darephrydnpwynvmrei-----skfl-----------kpqkave--vg
lyrsafchkyg---as-gs---q-kk-eessli---v--glgahv-----
--------------------d-k-m----------ds-----kgfa----
---wh--gysccaqp--ts---gydcikkae--vkgsk--gaimts----
-c-----f-------------qkh---gaagkhk------l--------y
aadvstgngvpnpteqht--n--gvqkkpcisiai---------s-----
-atciglsms--k------ednt-----------w-------rekqd---
----egk---ltsvkl---v----------------p--dql---th---
---sqln---ifvvp----------------------flksgtvfl----
-----islaf-----t-----------ld-------sphqrean--v---
----------g--------g-datvrlnhaqyd--yd------vgqsvnl
-----tal--t-a---q-agskamy-g-----------------d----a
kgp-n------i-lpqkkfwgktrqfgsd-c------k-ttg--------
------traqlwpkekf--ak------ctql-lllvkfa-lsa-gviamg
d---------c-----------k----e-------d--ql-----ecvkt
ktfgdtssh
>F
a---ity------ma----iaeem-nvh----dkv----fh-etdaa--m
ag--nftaa---a-------------------------------kveag-
-------------n--------wt---------ntha--wk-------dp
rkdfkvrraglslcq--yvp-f---esev--gqadpqilrpklrdeln--
-v---------iateih---gpakksdda---------lr-----gs---
nknl-------------tgtlks------gkvlptvapigyyggfcahki
tahr---yr----ka---rnp-----------------------acgp--
--------cvala---skkeqsrmp------------lsyag--aaapkt
arlt-------fk----------l----w---------e---g-----d-
-sayvcse-h---------------kkil-d--------lal-a---r--
he----------------------nd-l----------skhqtgvq--tr
----------g---vg-i----e-evn-----------------------
---------------------gksi----------aa-----ksfakgwt
lvink-st-nc-t------------------------fgel---vh----
-svqlscyy--nqkgvgs----------------g--rviv--------y
giaeda--a--sr--------------------hi---------v-----
--hafdagra-----------rvaaigyysvfaaw-------ieqks-kf
iyppkdl---il-----------------agv----h--ldig--ysccl
lrddakc--melivpyykwprinkvstl-tspq----flltdsafrvvy-
----hqdifitlph-aalgitmvnfgsmg-------cge-ks-a--l---
----------ktgfgrtlve-eymfhltd-d-------------------
------------d------a-----flq---tgtfvnspig--fyncgrt
gsh-nltcispv-apgei-------------------ikvvk-f------
--aris-hgthys---y--pa-------------------inp-agnang
a---------ckapavtiadacwls--v-------ql-flakvlns--ap
qc-------
>node3
----aas------ll----tiegr-tmg----c-g----ga-aylfg--s
nn--gfy-tkgpgra---eg--tmdtttitn-------y--r--sgaqtt
ekcn---------s---etgy-wf---------gfhg--ne--l----ga
------------nqc--sgr-s---ac----nr-------------nggi
kikpygt---graheht---acg----avti------ckp-----argdk
kntf--------fpkda---------------------------------
-----dpys----qs---r------kyv------------c------vag
f-------ygafp-qae--stlrlp--------------evn--igatls
htrsg------en----------l----w---------aaapd----ak-
-clhictq-e---------------hrld-a--------lhpaa---q--
eawepdkydnprynamkkn-----nkfl-----------khqaale--vr
----------g---pt-ss---q-kk-aetalh---v--glgahv-----
--------------------a-k-a----------er-----kgfp----
---ah--garcclns--ta---gydaikkae--vkvsrggaaivtp----
-c-----f-------------qkh---eaagkhkkkyeggl--------y
ntdietgdgapspseqht--n--p---------ai---------s-----
-atyiglsmt--k------enhk-----------w-------reked---
----vgk---itsaal---vkglpiknrf-------p--del---lg---
---ahln---ifvvp----------------------llmsgtvfl----
-----vslvi-----t-----------ln-------tphere-t--v---
----------g--------g-easmrlehaqye--yd------vgls--k
-----aaly-t-a---q-eg-kamk-se---dg----------le----d
sgp-y------i-lpqksfagktpqygsd-c------k-ttd--------
------rrtqlwqkdqf--sk------cdsl-llldkfd-lsa-giismg
d---------c-----------tlpyid-------d--ql-----dcvkt
ksiadtlsh
