>E
------k---epkyhvpstktg----------kk------r---------
-a-----ly--gtg--la---k--ed-lgygp---p-------gre---c
lhl--e---gdap---ylgyqmkye-----------------qgkke---
pahar--------------lvkaitepcanlgvdttsgfwceddmvetnk
rt-----------lsrgfencgelwrsd-----------------ceqkg
sdvl--ka----------m--g---------i---e------igyf--wg
pslvfeg-qkcchgrgkq-sl-----cgmmnaplgggaffgkldadah-s
a--ll--gqkg-ntpstrgr---ieaekicgksk----gylkmep----i
g--dktipii---------r--pr---saylpl---spksep--vvm-iy
a---pnfcvnc----teka-rphv---kq-dkp-kavllc----ddn---
---dfk-------------------sn--tacf----dda----------
----------------------------------------gt--------
--d----ia-ar------g---fq-s--was-------f--l--------
f-y-rvksgsrs------nrkggglassaassdpnvlfipglnlhnltkq
gsgearv-qmsl--s---lllcvllhk--aanvkdfgk------leckll
gedrl-----c-papew---hspdp---sii----rlsd-----l---gt
vle-----sg-qgstgiyilac---c--sml-vpnrkllfkkdtqkvqkd
t--sm-sgwsemldirnlpasqt--s------iaqcsggg----pakkky
--aer--dglske-------------g-h--gw-------------nael
qvhkv--h----rmihkac
>F
------t---dsky-vqselkg-----------k------k---------
-gafye-ly--gvg--la---a--avl---gm-------------a---c
lel--a---gdvp---ylafg--ye-------------lq-isgske---
pnhvl--------------liysisppcf----ngsveawcsdeanqtke
-s-----------lkndfekceklwvsd-----------------c----
----gepgmkgv------m--t-t------------------igefpkrv
pdlvfeg-qvcanasdke-tl-----c----aplgggpffgqmeadin-c
a--ll--geka-dspdsrdr---yepekkhg-tk----gytklds----i
g--dntt-rl---------r--ar---edflpi---tpnsqr--vvr-iy
s---qafsldcsilhaekg-spht---ke-dks---lllsl--aekd---
---ntr-------------------vgrgtgcf----dda----------
----------------------------------------v---------
-----------d------g---fkst--wga-t---csf--n--------
a-y-dvvtarrgk---aserkga-------swnlqvf-ipgl------kq
gsdnarl-qtsk--g---llt-ivlsk--ka--lnfgn------ldckpl
gne-------c-qppqwvksqepas---svi--whr------------gq
vldvqgsspv-qgrttsatlda---c---vq-ipksvidwekdqqdiskg
gfpsligawkqlgeirnfpagetspg------ivscisgsygclp-tkry
--eer--snl-qk-------------p-n--gw-------------gvel
qvhqv--l------th--c
>C
nrk-ahq---npal-vggqlyikhenp-qil-eghat---rvgafvigvl
avgkkdwvyna----amt---q--ad----spypagmhn----gaf---c
------------t---flp----st-------------gspfq--sk---
a-thp--------------lvt------g----r-----lksvqalkk--
---------------------------vva-----nvvlwkeldvc----
----ksealpvl------y--k-paf--hngdadlhyvise----n--sc
ralvigk-kiipnsrshartn-----t----sqadte-----ianaak--
-----------l---a---w---vppcdtie-giik---yv--lt----t
---it-s-k--------------m---gdyv---------vqhvavm-a-
--------------------------npk-sna-lsl--kl--ektktvn
qeislg---vykcak----------lr--iacf----t------------
--------l--------elay----------------kleavcpnidvv-
-------------mttpke---vg-l--str-----r----varffpaav
y-mtsgrtas--k---e-aaagk-------------------------kh
ilgiwcsa---gtislg------gfth--rsp--lfd-----------yl
kl-------------h------------si-km---lar-----ltiteh
sldsqlpfrglr--mpkhvf--------gvv-isksknvynah-------
---------------skfee--p--rw--maeleqg-------lk---kf
--vh-lak---vt-------------s-sgsaw-caeg---cslkkvkfi
rynsa--t------ahkgs
>D
s---teq---dvtl-dggsvivsyqnpkqvlhes------rfgafvigll
aigawdwvynamlytils---r--ae-----ptsedmra----gafatwc
------------tawtfan----fk-------------dkgwq--ak---
adtql--------------llt------d----g-----nvaaqglkqs-
-------------------------t-cti-----sivlwner-------
----sseapkllsnngc-hedk-pafsaedaeadiqflepep-gsa--li
kafiigs-nltsatrghtrsq-----t----sqshta-----fa--ar-c
aatalapagkgm---n---w---vpplhkle-alie---yl--ap----l
gdmia-s-ql---------lisim---gtyv---------pqgyntl-v-
---------------------------se-rdalftl--km--akmk---
---pag---iyacvgrsqgtdgrakvt--vhcf----g------------
--------l--------evay----------------nlqlacpav----
--------------t-hhn---va-lnfrtt-----k----vsdffvpri
y-ltgaktaf--kdlrg-apqgt-------------------------ka
ylgfncia------sl-evltytgfak--aaptdlyk-----------yl
gl---qte-------q------------ai-kvi--lar-----itltge
pldsqlpfhglk--makkaf--------emi-vfmactnytah-------
----------------rfse--p--rw--nsaleqat------lt---kf
--gsvsyr---et-------------a-t--vn-gdgg---avllevlpi
rnrsa--p------lhkga
>node14
------k---dpkv-vdtnmta----------kk------kdg-------
yggfveyvyqegtg--la---k--ee----dp---s-------gsf---c
lni--d---gdks---ylprg--yn-------------lh-dqgkkd---
pshsl--------------lik------t----nstpapwckvdalktdk
-s-----------lrrefqncaetsvsvgv-----deak--dsegc----
----edkglwti------m--g-ksinsnvki---qyslrkpfgwf--lv
pdlvfgd-qkscnartae-tl-----v----atlsga-----lavdph-c
a--ll--gekf-etps---r---vdvkkkid-ak----gyltaep----i
gnhedts-rl---------w--lh---edflpf---tpnaah--vvm-vn
p---qsfsld------eta-spha---ke-qks-kslllkl--aekn---
---elk-------------------iardaacf----ddad---------
--------t--------glq------------------mett--------
--e------dvk------d---ik-n--wtpik---cqf--n--------
f-v-kgaaaw--k---a-nrkgq-------------------------kq
afasarv-kstlplg---slncialnk--kspvkmfgn------ldckfl
gdd-------c-qssew---h-pds---svv--kfklsq-----l---dd
vlelrgsfsg-kdrtsivtlht---c--gmm-vpktkisygkh-------
---------------rkfpagea--p------ithctsg-ytclpvikry
--eak--q---sd-------------s-n--lw------------ksiel
rvnqv--l------dhkgc
>node13
------kqns----------------------l--------dg-------
haglvklvyqegng--vskggk--qe----ga---d-------gsf---c
vdltfn---geke---ylprg--yg-------------la-keggld---
pscsl--------------iik------a----dsta--wckvdalksqk
-e-----------lkrdlqnc--tsqrigi-----dnrr--qtedc----
----ekkglrsi------v--aqrnkknheei---qfglskpyshs--lv
pdlifgd-dkacqsvtae-tl--ka-i----anmpgg-----ltvtph-c
a--ll--gekf-esft---r---vdvkskid-a------fltaet----i
gh---td-va----tqgtyr--lh---edffpf---tpnaah--ivmaat
p---ssfsld------pvtkqaqaie-ke-lts-tslllrl--aers---
---elk-------------------vatdatcf----eeke---------
--------tkg-hvtnqglq------------------mqsa--------
--g------dvk------d---ik-k--wtptc---cqy--n--------
f-m-kspisw--k---e-nskgq-------------------------kk
thggawv-mdtlpve---plncvaaar--nsaamrlge------ldcqfl
gda-------c-qssew---h-atg---vvs--kfkvkq-----l---ea
alqargsfsg-kdrtdvvklht---c--gmv-kaktrisfgk--------
-----------------fpagev--p------ignctah-ytcfpva-ry
--eak--q---adiv--------igns-g--lw------------ssi-l
rvnqvspl------dhrgc
>node10
------k---npky-vesnmtg----------kk------k---------
-ggfyefly--gtg--la---k--ed----gp---p-------grn---c
lhl--d---gdvp---ylaya--ye-------------lh-dsgkkd---
pnhsl--------------lvksitppca----dgtsepwcqddavetnk
-s-----------lrrdfencaetwvse-----------------c----
----adkglrsv------m--g-tevkcr--i---e------igyf--wv
pdlvfeg-qkccnvrgke-tl-----c----aplgggpffgqldadah-c
a--ll--gqkq-dtpstrnr---teaqkkcg-sk----gylklep----i
g--ektt-rm---------r--pr---edflpf---tpnsah--vvm-iy
p---qnfsldc----teka-spha---ke-dks-kalllsl--adkn---
---dlk-------------------vgkgtacf----dda----------
----------------------------------------ts--------
--d------dvk------g---fk-n--wap-a---ctf--n--------
f-y-rvaaarrgk---a-nrkga-------swnpdvf-ipgl------kq
gsgsarv-qtsl--g---lltcivlhk--kanvkdfgk------ldckll
gee-------c-qppew---hspds---svv--nfrlsq-----l---gd
vlelqgsfsv-qgrtgivtldt---c--smm-vpkskiayekdhqkvskg
a--sl-gawkelfeirkfpaget--g------itqcssgsyaclpaikry
--eer--sgland-------------s-n--gw-------------siel
qvhqv--l------ahkgc
>node7
g---hgq---dpkl-gggavdvkhekt-qilkkk------rqga-vikil
pvgwiefvyhaals--ls---rnaae----kpvted-sa----gaf---c
l----y---edit---ftp----fq-------------gqssqgkag---
aepsl--------------lik------k----v-----wpkvqtlkid-
-------------------------a-vgi-----kdam--etesc----
----dgedlrvl------h--k-pafntaaeqaalqflssep-gsi--ac
kslvvgk-dkspesraqs-tl-----v----ttaeta-----lssaaq-c
sfvll--gvkwa---n---w---vplmkkin-aamqkqtfi--ep----l
gieee-s-kl---------lksmm---gdyvtfvcvtptaphnftvl-v-
---------------------------hd-rea-lkl--ql--akkk---
---plk---dys--r----------vs--vacf----g------------
--------t--------dley----------------klgtsypav---v
kpetgdt--qvnemgapkd---ik-q--rts-----ckl--d--------
y-ltsakaaw--k---t-kakgk-------------------------ka
tlaitcv-dtkvtlg---kltcvgfqk--qsavtlfdk------ldckfl
gat-------y-kske------------al---k--lgk-----lasree
alnsqlpfhglk--mpantf--------gii-isksatnyneh-------
---------------skfqvgep--pw--p--vaqct------lp---kf
--vqqvyk---td-------------g-n--lw-ceeg---stilkvfrv
rhnta--l------shkgs
>B
a--pgvn---qakl-iggdiavknkkp-smmklk---kat-------klq
pigwialaykta----le---anv-e----tgvsse-advpgteyf---c
l----ydnaekis---i-g----fe---p-cgmrhfangeayqpkgg---
idpsi--------------lid------k----a----------tlnvt-
-------------------------g-vak-----kdal--tfetc----
----enqdlwal------n--k-p-------qtpmqfl------hi--rc
ksrpvnkidkstepradv-gl----dv----tqpktd----------avc
al---------e-----------lhllrkv----lnketfi--kp----l
aleee-g----------------iekigervtfscvlpsnphgltal-l-
---------------------------nvahqk-fki--dlfpsekq---
---yyk---iya--r----------vt--gncirclgg---nvkaapd--
----vtqht--------nldf-kyfetskqwksffelslgt--q------
kcetgkt--gvntyekpgggcpvk-h--kts-----ct-saa--------
l-ltggkknw--k---e-kel---------------------------kq
tlpvtcv-vtdisig---hl-c---te-hnggatf-nt------meckfl
gvv-----vcypkqke------------sl---k--lsknkiactaskde
akhdhvpydgls--qpaddl------dkgal-knnssvlyv---------
---------------srisvsen--h---p--sp--a------ip---pi
----gl-----ke-------------d-n--fw-ceea---a--v-----
------------------s
>node15
g---hgk---dpkl-gdtamdv----------kk------keg-------
eggwvefvyhagts--va---knaee----dp---a-ka----gtf---c
lwi--d---ekkt---yapsg--yk-------------lh-sqgkkg---
pensl--------------lik------k----v-----wpkveclkidd
-n-----------lrrefqacad--a-vgv-----deam--esesc----
----ddkdlrti------v--t-eafgsdveevalqyaarkpfgwi--tc
snlvvri-dkspnsrkqq-tl-----v----atasga-----latdsh-c
s--ll--gvkw-etpa---w---valkkkid-aplakqafl--ep----l
gtheehs-rl---------wkklm---edyiaf---tpnaph--vvm-vh
piggqsfald------eta-thns---ke-rea-lkl--kl--akkk---
---elk---kys--r----------varevacf----d------------
--------t--------dley----------------klgttlpvg---l
kpetadd--qvte---pad---ik-q--wtpik---ckl--k--------
f-ltsaaaaw--k---a-knrgk-------------------------kq
tfastrv-dsnvplg---nlicvaflk--qspvtlfgd------leckfl
gaa-------c-kskew---h-pdl---avv--kfklsq-----l---ed
vlnlrgsfsg-r--islstlns---c--gmm-takaatsygkh-------
---------------skfqagep--twpqp--vtqcs------lp---ry
--vqq--q---sd-------------g-n--lw------------ksfev
rvnqi--l------nhkgc
>node6
g---ahq---dpnl-gggsviikhenp-qilken------rvgafvinil
pvgsvdwvyhaalskals---r--ae----spytedmrs----gaf---c
------------t---fts----fk-------------gqswq--ak---
adthl--------------lit------e----a-----hksvqalkqd-
-------------------------a-vvi-----kvalwneievc----
----nsealrvl------h--k-pafsandaeadlqflepep-gsn--ac
kslvigk-ditpesrshsrsl-----t----sqsqta-----lataak-c
gatll--gvkgl---n---w---vppmqkid-aaiq---yl--mp----l
gtmiq-s-kl---------lksim---gdyv---------pqnyavl-v-
---------------------------pe-rea-ltl--kl--akmk---
---plg---vyscar----------vt--vacf----g------------
--------l--------elay----------------kleascpaidan-
-------------mtapkn---vt-l--rtk-----r----vshffpati
y-ltaaktaf--k---a-tangk-------------------------kp
algfscva---ftlsl-etlscmgfak--hspvtlyd-----------yl
gl-------------g------------ai-kmk--lar-----ltlked
aldsqlpfhglk--mpkntf--------gvi-iyksatnynsh-------
---------------skfqe--p--rw--qatleqgs------lk---kf
--vhvvyk---vt-------------a-t--vw-cedg---avilkvlhi
rhrsa--l------ahkgs
>node3
g---vmn---dpkl-tggdvsvknkks-stlklk------lnga-vmkil
pigwiefayrta----ls---rnv-e----tavtee-sdvpeteaf---c
l----y---ekit---f-a----feyvnq-cgmrqftgaqsnqprgg---
aqpsl--------------lin------k----a-----w---dtlsit-
-------------------------g-vgs-----kdam--dletc----
----eledlral------n--k-pafrttatqtpmhfl------hi--rc
knrvvgk-dksieprasg-sl-----v----tqpktd----------avc
sfvll--gvkwa-----------vhllkkln-atmekqtfi--kp----l
aleee-s-il---------vkaki---gervtfscvapsaphnltvl-l-
---------------------------nvshqk-lkl--dlfcakkk---
---ylk---iys--r----------vt--tscfhclgg---ivea--q--
----vtqdt--------nley----------------klgtsyq------
kcetgkt--evnamgspkd---vk-h--rts-----ctlntd--------
f-ltggkrsw--k---e-keled-------------------------kq
tlpvtcv-vidvtig---ql-c---pk--ngattffnk------meckfl
gai-------y-ktkq------------al---k--lskagivcvasree
shhskvpfhglp--mpadtf--------giv-tskssvlymgh-------
---------------srqpvseh--h---p--vp--t------lp---ki
----qv-----ke-------------g-n--lw-ceea---t--lqifqv
rhnia--a------sqkgs
>A
g---vmt---gpnm-tqgelsikakep-stlllk------lnga-vqkal
pigwinflyksa----la---rsv-e----tavt-e-sdvpqteay---f
l----y---qkss---f-e----leyvndk---rqragatnvqpigadtg
tkpsl--------------lvd------k----e-----------lgit-
-------------------------g-vanksapt-g-m-----------
-----vdelral-----qs--k-pafpttgtmsc----------hv--wc
khpvvge-n--tepsisg-sl-----v----tqpctd----------avc
afaf----vkwa--------gdavhlvkkld-akqekqeli--kp----l
aleee-l-tl---------vkakl---geratyscvaksarhnltvl-l-
---------------------------nimgqr-lki--ylfcsder---
---ylklgp-yq--h--------------------lga---igeg--qkp
kppnval-----------kqy----------------slgapyq------
kcedgrt--evdamgsptd---vk-y------------lktd--------
fefsggkraw--a---d-keldq-------------------------kq
klpdtcv-iikvslg---nr-c---pa--sgvtn---kkfphnmmecqfv
atq-------y-ktgq---------slgal---k--lsksgiicvssrep
shhlkvpfqel----psqtg--------giv-tsksa-lyvgq-------
---------------srqalske--h---p--vp--e------lp---ga
----ek-----ke-------------g-d--lw-cseakqwh--lgtyea
rhnia--a------sldgs
>H
------sqns----------------------l--------ac-------
fadlikllkqdvpd--iakgg----e----ga---n-------g------
--laft---gkkd---f---v--tg-------------md-rdggvd---
pscpleqmpdssn------iik------t----vsta--wckvdvlksqk
-d-----------lnrkfqnc--tsdktgi-----dark--fteec----
----gkkalrai------v--aakdknnheev---qfglsksyspp--mv
pnlifgk-nkscqaisaq-sldeks-a----atiqgg-----ltisph-c
t--lf--gelf-etfa---r---vdvnskva-a------fltgkkheiii
gh---td-vsaqsttqgtyr--lh---ddffpf---apnaah--ivmse-
---------d------pgtklavain-ka-ltg-tslll-----------
---nlk-------------------vatetsci----sqkd---------
--------tsg-----egle------------------mpsa--------
--s------nv-----------ik-k--wtpac---cqy--n--------
f-k-ktpvnw--k---e-da------------------------------
-dggtwv-mdalcve---pl-caasppg---samrlgd------gdcqfl
gns-------c-hspqw---h-atg---viv--kfnikl-----m---sp
aleargtfd--kdradvsklltfpac--srv-nartqltvns--------
-----------------favgev--p------igsrstn-ytcfeva-rf
seqka--q---anvthpyrtdgsiglsda--lwi-----------vsv-i
rrnhvpalegae--dhrgc
>G
------kqn-----------------------------------------
-ap--klvnqegyk--vtrgsa--te----ng---e-------gsf---c
valtyn---geee---yqsrg--yg-------------lv-kkg-lh---
pscdl--------cvlktkivk------a----detv--whs----kpqk
-avsahllltgaywnrdlcnc--tahri---------hs--qneec----
----dkk-lpti------s--ssrkrknh--i---qfglckpyses--iv
phdrytg-akavqs-cgq-ei--ka-v----asmage-----nvitph-c
g--ll--kek--dnft---h---vdvkmkid-g------wltaqt-----
-h---av-aa----iqgty--------edfypf---tptaah--ivtvat
k---ssfald------pvtkhgqaie-ks-lts-tclllkl--aerg---
---nlr-------------------vngna--f----eeke---------
--------tngvyvnepslq-g----------------lqsa--------
--g---------------d---vk-k--wsqsccgdcqy--n--------
--------qw--d---q-kpkgq-------------------------kr
thggawv-m-tmpvq----fksv-aar--nesamrlgq------ltcqfv
gdl-------c-yscew---q-lid---vls--gfdvsq-----l---eg
aleakssfs------dvlkahr---c--gmvs--------ak--------
--------------------gsv--p------igsttal-ytcfpva-ky
--nak--e---adiv--------lgns-a---------------------
-vnrpgpl------dergr
