>H
s----------p---------gggnisgg-ptaer------ddhs-tegv
p---gaqyyps----kfnpgyp-----m----------dg-------l-h
a-lslnhi---h-------s-------------ikayk-----r--rgwt
tqnvtcaq-----dvskpdt-v-dkcf-------tq------gk--gfal
i-hk---e-dgqs----ip--------qgwvahym--gqfm---------
--p---shdchd-----a--apgl-----ykg--dgydlntkfeltqstv
arkpyd---g-----------gcpt-------------------------
-----v-----------t-----mhdl-------l---ptph------kd
i----grl---td---------tghsqkfdtlkmcak--gh-------si
dtcs-----------rekgep------------y-------ylsvidpdk
slq-nlfqfgheps----k-pehnp--dterkavdrifsaq-----ilgt
gkcgih---vglssvdsasp----e--p--ldrqlakv--mkan-lnqks
dvlc-mmrrd-------t---------gdntcrtgtr-dey----asdlh
gc---rffvfks-df----------ylya---ss-nst-vtnta------
--------eeg-----ph-------veq---anla---------------
---------------------------d---------------a-----q
------a--e-----itv--eqklt-dasasitt-vtvsg-yvrgem---
-d-nskfq--wnh-gklckv-----a----sr--f--q--yfy-------
e---wscnv---------v-----vygvqnlqkl-g---i----------
------------------------------------------vtdrscsk
-pr-eitftgk--------------gqs---ecv----------------
--arc-------raakacihdta---c----l--t------shgfy---e
-pkcggcl-kv-rkkaegdcl---yaea-------rgthgiq--v-----
------evcsk---------------
>A
l----------ptrhlynkl---------vr--yklleaaefqlfdsksv
d---glkiffc----s----ypm---vvan-mt-sd--se-------epf
giakg---tahytf--ksns-------------atgfq-----ikdrdws
va-vsc-n-----qg--lkgsmpga---------------lrie--gllv
n-av---t-k-av----gng----ka-iq-----e--s------------
--g---sygc-------v-----f-----ptglggeiay--gffk-----
-----a----d-----ta---t--n-----if-----adklggganss--
-fgiam-----------d-----gggggcstys-v---vtyhtd----lr
-----ltv---t--g----gt-tslsd---sin----knip-------se
---t----------dis--vpwkihggypi-ggfetprsknawqtlehtp
glr-k--------t-----hge----------------lsq-----d---
--calnwcvieevasnkep---------tll-a-------aen-------
-----dkvdd-------a--ni--------------p-qqh----fgpmp
q----kgf--naks-----------y-ya---ds-g-----ka-tf----
--------g-------vykvstkeyvdk---pvltg-------allatvs
tp-gsecg----cvvvtlef--pagalhra-----ll-geqyfsspapaa
------ervp-----kki--rqkad--------krkk----y---a--kt
gggplhsrnrwln-tg--qngmgtna----gwkty--p-----lklqfdk
q---hgaac---------q-----chy-------gk---ns---------
---------------vk------------c--fwa--sri--vgnteaeq
-k---adfi----kgd-------d---t---kcvts--lgfqpkvhinr-
--v-d-------l--kp---------vlggkf--as-hhlsnkefyfpsf
----atkvlk---------------atliraaskdrgd---h--l-----
----kidlh-----------------
>F
s----------n-------vkaglrlnpa-p--qk---------f-aeav
s---nvtsytc----t----yp-----i----v-ce--da-------l-l
akvpl-------------------------------eqks---kkpekwk
-s-vsc-r-----ag---------nvf-------a-----n---------
f-nm-----qaqv----v------lqfqa-----v--avfiavetngkdl
srp---rs-------------sglggsmdvvgeteratltpty-a-----
-----d---t-rrskavavlkg--t-------------------------
-----p-----------r-----aqdg-------n---vtyh------lk
velawgtv--kag---------saidq---tak------dnfrsssn---
---glietrlal--qyeravs------------y----------------
skh-r--------g----hkgskksfeh--------lydlg-----pls-
fkcqgt---ivnd-pkqedpllyle--p--mle-------rksw-lyege
-----s-tdstcdvfe-e--yl-----qe---rtgar-aey----vimlh
s-lpl----yfk-ae---gllrtwcylfq--ftd-npa-line-------
--------g-------ah-------vdk---avlp---------------
---------------------------dsg-------------r--g-eg
------a--i-----vsv--eaklq-ak--h-t-----eg-y---nlsdh
es-vlrnp--whp-vd--sc-----f----qh--v--n--vfy-------
n--------------------------ehnlelg-d--------------
----------------------------------ivylgf--vtkktcdk
-krfhq-ygtdalkht-------vcafsrvhkcfke--peartnydaypd
--vk-sc-----v--kect---g--------egfs------sfpllnvsn
d------ikkv-lpqt-saca-s--gev-------ggs---h--h-----
------qlcek---------------
>C
ietnpfq----pvkliyntg----------s---klvkvtefhlakpesa
f---glqfffc----k----yak---gv----p-tq--pkylnvfeim-f
sktaa------ypy--s-kg-------------sadys-----ktppvwn
if-ipc-mycntatk--l-g-t-da------------tgkprlnpsgftl
srki---s-dgaq----gsrgllgva-sl-----q--w------------
--g---sydy--fnptaa--d----------vlvapkay--afph-----
-----aniaad-----va---a--n-------------------------
-----l-----------dsgedvaastfcr-ysfi---vlakqqempl--
l----ktl---sphgtpai---ievkd---akg------dp-------kc
---v----------kip--tpwpg-gpatimggy----dktlw----sna
glhce--------t----gssy---------------tnvt-----r---
--ctlfwctleraansnde---------dll-p-------ksi-------
-----dkgeh-------ivvpi--------------rapefpvsyygv--
h----ngy--ie-e-----------vafs---saek-----gt-tfrlrd
vfrlrsvcg-------vnkc--dsypdkackavldestdc---a---dvc
------------------qf--p----hrt-----nqpakrfaa--g-av
------e--klqvdalk-------------------s-------------
rgglfhtikrwlecpn--nsalgp----------fmygnkyg-------g
a---s---c---------a-----cfp-------pk--fngnrakvtpgs
lgta------ghvha-------------------g--lgd--ag----ek
----------k--rld--aclelq---g------ktv-lgpntrvpi---
-------lgdfri---------------------------tqpriygt--
--k-vevllrvcnak-----s-k---re-------rla---a--l-----
----k-afgvk---------------
>B
q----------rtreiynkc----------k-----ltnaefnmfdshpv
d---glrlffc----s----ynkvfsevtkvvt-adakeh-------a-f
gkggg------lts--r-kt-kntlglksgdppyaglp--alavrpldwt
iv-isc-q-----eg--fse-m-ga---------------lrve--gllv
s-li---a-k-aqlvkggap----dg-gs-----k--n------------
--g---g-gc-------v--daff-----stpl--------syyr-----
-----a----d-----ns---g--n-----sfsklccakqlggganacvn
qlgsgmylkdipcmksl-------gakgtg-yt-l---ctldkdlialln
-----lta-------tsavsletsltq---gin------vp------ys-
-----------------------ihgaypl-vgs----getawealsstk
glr-k--------g-----rgd----------------vmqallkge---
--cpiiwcliekvdgvkee---------tll-h-------egn-------
-----entdh-------a--dl--------------r-qeh----ygppl
d----lgf---p-p-----------ypfn---sp-p-----qa-sf----
--------g-------vhki--ksfvkn---pvitd-------gal--vc
fdkghdcglfsac-vlmlhl--a----hra-----lt-geqyfm-----a
------d--p-----ski--wrktg--------p-vs----y---s--ka
gggpmrvrnanwn-tn--ssgmghsa----kwkty--a-----mkssyck
q---h-------------------ch------------------------
----------------nkyptlkrrtfdrcamfwg--lra--intkeash
qs---mafies--kvd-------e---t---rcvtp-clgvevkvqvhr-
--v-t-------v--kl------katc----tn-g---algqkqlyfaqh
gakcdpvlnrvc-------------st--------dgn---h--i-----
-----idmh--hesycratyqlktfv
>node10
s----------p-------vkagvkvdag-p--qk---------y-aeav
a---nvqsyps----k----yp-----i----a-ce--da-------l-l
akvplthi---r-------a-------------iyveqks---kkpeewk
-s-vnc-e-----ggdkpwy-l-encf-------a-----n---------
f-hl-----hgdv----v------lelqa-----v--gvfi---------
--p---ss-------------sgl-----vtgeteqatltpty-p-----
-----d---sdrrakaaaiaka--t-------------------------
-----g-----------k-----ageg-------l---vtfh------lk
v----gvl--knn---------sdvdq---gak------ah-------ka
---alirt------qiekavg------------y----a--egsvlepae
slq-r--------g----nkaskksy-h--------ifgiq-----pvsv
fkcans---ivndepdqedpalcle--p--mde-------rksw-lyekd
gelc-d-shnscevfp-l--yl-----se---rtgar-aey----tamlh
g--pakhylfsd-ae---gllltwcylfe---sd-npd-ikna-------
--------g-------ah-------vdk---svlp---------------
---------------------------dtg-------------a--g-as
------d--t-----vkv--qgklk-ei--p-t-----qg-y---nlger
qs-vlktp--wdp-vk--rc-----f----qc--v--e--vfy-------
d--------------------------qrnletv-d---kq---------
----------------------------------ivylgf--vakkgcdk
-kr-hq-fatkalkhk-------vcahsrvqkclkn--qevrtnyeghp-
--vktgs-----r--kect---t---k----ee-t------gkpfyaisd
d------miki-lkmt-svct-n--gdv-------kgs---h--q-----
------qlsek---------------
>node6
iethp-s----pakaiyepg----------s---kllrleefhlpkpqsa
p---glryffc----k----ypk---gv----s-te--pt-------m-f
gktat------ypf--s-kk-------------sagyt-----ksppmwn
it-isc-qfcsq-tg--lsg-m-da---------------prln--gfll
g-na---s-dgaq----gdrsmqgig-as-----k--w------------
--g---sydy--fnpcga--d----------vlvaqkay--gypr-----
-----l---ga-----va---a--n-------------------------
-----l-----------nsgedveagtscr-ytli---vlykseeiplld
v----rtl---sscgtpal---tevkd---gkg------dp-------kc
---v----------qia--spwpg-gsypa-ggy----nktal----pna
glh-r--------a----gsgqm--f-q--------gfaiq-----r---
--ctvfwcvlervdntede---------sll-h-------kgi-------
-----dkseh-------v--li--------------rapef----ygp--
y----kgy--ie-e-----------vafs---sadk-----nt-sf----
--------g-------vhkc--dsyptk---avldesadckglallvgvc
-----------------lef--p----hrt-----lqpgmrfvs--g-ga
------d--a-----lk-----kva--------d-isd---y---h--sv
gggalhtqkrwlecpk--nstlgp----------y--g--ygylkqrysg
e---pgcpc---------a-----cyv-------pr---nknsanv----
ldtksdamagqnvha-------------------g--lgc--ag----ek
----------p--rld-------q---g------tt--lgqqtkvpi---
------------i---------------------------gqkrvygt--
--k-apillkvcaak-----s-k---rl-------rla---h--l-----
----k-alavk---------------
>node3
l----------ptreiynea----------r--ykllenaefhlfdshsv
e---glkiffc----a----ypk---evvk-vt-sd--sh-------a-f
gkggg------ytf--k-ka-------------tagia-----ikprdwt
va-vsc-q-----eg--lse-m-ga---------------lrie--gllv
s-lv---t-k-aq----gnr----kg-as-----k--s------------
--g---sygc-------v--dsvf-----stglvgeiay--gfyr-----
-----a----d-----ta---a--n-----if-----adalgggants--
-fgiam-----------d-----dggstcs-ys-v---vtfhrdeialld
-----ltl---t--gtdalsm-tslse---gin------ip-------se
---t----------qis--tpwkvhgaypl-ggf----sktawqaleptk
glr-k--------t-----rge----------------vvq-----d---
--caiiwcviekvdgvkee---------tll-h-------egn-------
-----dktdn-------a--ni--------------r-qef----ygpml
d----kgf--ka-s-----------yayk---na-a-----na-sf----
--------g-------vhkv--keyvkk---pvltd-------gllasvc
ankghdcglfsacivlilel--p----hra-----ls-geqyfs--g-aa
------e--p-----kki--waktd--------n-is----y---s--kt
gggplrsrnawln-tk--nsgmghpa----swkty--a-----lklkysk
q---hgcac---------k-----chv-------pq---nk---------
---------------dk------------calfwg--lrc--ignkeadq
-s---mafieg--kld-------e---t---kcvtp--lgmqtkvhihr-
--v-d-------v--kp---------c----tv-aaerhlsqkeyyfarh
dakcapillkic-------------atl-------rgn---h--l-----
----kidlh-----------------
>D
ie----sveihs---vkepg----------s---kllrleefhlpkpqva
p---glryfyctltsk----yki---di----rq-----a-------m-y
gnsas-------pflms-skr------------paaya-----k-----a
is-isc-qfcse-tg--lak-m-ga---------------pai---gfml
g-ns---ptgpsh----ggmsmqgvg-kt-----kyh-------------
------tyey--fdpcaa--e----------vrdsqkdy--gypr-----
-----l---aa-----if---a--t-------------------------
-----l-----------nanedvgagmsck-ykli---vtykagyisllq
-------l---escdtpal---tevkd---gkd------ep-------kc
---v--------lhqvg--stwpa-apfap-ggf----nktnl----pna
lln-r--------a----asgpk--f-q--------af-iq-----k---
--ctvfwcllqcadgtedq---------rll-h-----vfkgi-------
-----dkaeq------ai--li--------------rapel----fgp--
c----kgy--n---------------afa---gadk-----nt-sf----
--------g--vegmhvhpr--deyakr---gviddradckgldvlvgvc
-----------------mefisp----yrg-----lqpfmkfvs--a-ga
------p--a-----lr-----kia--------d-vdd---y---l--nl
gggswhsekrwlecpt--nsalgp----------y--g--cgfl--kfst
sgaisgcpcpiesqlvqya-----cya-------arnk-nk-ltdl----
lsktsnaminen-------------------------fgcsttg----gk
----------p--rlq-------n---g----------ledqttvvv---
------------i---------------------------gkkrvyma--
--k-apilidlclak-----s-s---rl-------sla---h--l---gv
vantk-aavvk---------------
>E
s----------l-------qkagiktdng-s--qn---------y-aeal
f---hiqnlss----k----yp-----t----a-ce--sa-------l-l
gkiplani---r-------a-------------iyvd--------tdrws
-q-vnc-e-----ggdqpwy-l-enclsnldgksn-----a---------
f-hl-----eanv----v------lelda-----a--gvfi---------
--paavaa-------------sgl-----vtgdteqgtlspty-a-----
-----d---sessaktg-iaka--tvqcvg--------------------
-----t-----------k-----ageg-------lhqevtyh------lk
v----vvlpq------------advdq---aar------ah-------kt
---alirk------qidksvg------------y----t--gggvlavge
slk-r--------g----gkatkkpy-v--------ifhiq-----pvsl
ykkans---vv---pdlnptqlcve--p--leg-------rkrw-lnekd
sdlc-e-ghnssqvyp-l--ys-----se---rtavr-agy----samlh
g--pakdylfsa-an---g-mlrwcyvld---sa-kpdriksa-------
--------g-------sh-------vdk---svlp---------------
---------------------------als-------------t--g-as
ylvaand--a-----ikvliqgklktei--a-y-----hgay---dlgdw
ks-qlrsh--wdv-vk--ec-----y----qc--v--e--vff-------
d--------------------------qrnletv-e---ka---------
----------------------------------avylmf--vskkgcdk
-kk-v--faskalkhd-------vcapssnqkcmkn--lacrt--eghp-
pvvktgs-----r--kect-------k----ed-t------akafyfahd
a------liri-lqts-svctns--gdl-------kgv---n--k-----
------qlsdk---------------
>node7
l----------paralyqpa----------r--kkllrlaefhlfkahsv
p---glkyffc----k----ypk---gv----t-se--es-------m-f
gkagl------ypf--s-kv-------------tagfa-----knpkmwt
it-vsc-q-----ng--lss-m-gp---------------prin--gfll
g-na---s-ngaq----gnr----ig-as-----k--s------------
--g---sygc-------v--dpgf-----ttglvaeiay--gysr-----
-----s---gd-----ta---a--n-------------------------
-----m-----------n-----dggsscq-yg-i---vtfhddeiplld
v----ltl---sscgtael---tdvkd---gmn------ip-------tr
---v----------qit--spwqlhgaypa-ggy----nktalqvldpan
glr-r--------a----argek--f-q--------gfgiq-----q---
--csviwcviekvdetede---------tll-h-------kgd-------
-----dktdn-------v--si--------------r-aef----ygpml
g----kgy--ra-e-----------yays---ss-a-----na-tf----
--------g-------vhkc--kdyvnk---svltd-------gllcgvc
-----------------lef--p----hra-----ls-ggqyls--g-aa
------d--a-----vki--rakva--------n-isa---y---s--st
ggdalrsrkrwld-ak--nsalghpl----sw--y--a--ygylklkysg
q---hgcpc---------a-----cfv-------pq---nk---------
----------------------------------g--lgc--igekgcdk
-p---maflek--kln-------e---s---kcvtk--lgqqtkvhvhr-
--v-d-------i--kp---------c----te-na-rhlgqkafygirh
avkcasillkicaakk-agck-n--arl-------rgt---h--l-----
----kfdlvtk---------------
>node14
s----------p-------mkaggkveag-p--qk------lqhy-aetv
p---glqyyps----k----yp-----i----a-sa--ea-------l-l
akiplthi---r-------v-------------iyeya-----kkpkewt
ls-vsc-q-----gggkpss-l-dhcf-------ahg---srgn--gfll
v-ha---g-hgda----vhk----iglqs-----s--gvfv---------
--p---sssc-------v--qpgl-----vtgeaesysltssfsr-----
-----d---gd-----aa--pg--t-------------------------
-----v-----------s-----asen-------l---vtfh------ld
v----svl---sn---------tnveq---gvk------gh-------kk
---a----------eidkaep------------y----a--elkvlepee
slq-k--------g----dpaakkpy-h--------ifgiq-----kltt
pkcann---iqdddpdeeapsvcie--p--mdq-------kksr-lntks
delc-dmrhd-------m--nl-----sd---ktgar-gey----tgplh
g----khylfrt-aa----------yaya---sd-apd-vtna-------
--------g-------ah-------vdk---svlp---------------
---------------------------deglvhkrta-lgqfla--g-sa
------d--d-----vkv--qsklt-ev--a-ts-itveg-y---nlger
qs-tlrsp--wnh-ak--rc-----l----qr--y--q--yfy-------
d---wscqc---------q-----vfgernlegl-d---kr---------
----------------------------------ivylgf--vaqkgcnk
-pr-emtfstkelkhk-------ncahs---kcvkk--laaktkyeghp-
--vki-------r--kecv---a---c----ee-t------gkpfyaisd
apkcggimlkv-qkkt-secr-n--aei-------rgt---h--l-----
------dlisk---------------
>G
n----------p---------sgskvpgg-peaqr------hgrf-ksgt
pietalqyypd----k-esayp-----p-------------------i-m
sr--ltni-----------------------------------------t
wg-ttc-e-----dv-rpgt-v-aycf-------vq------gk--gfsl
i-hklvv---ghs----vg--------asfvshyk--gmfi---------
--p---shqcld-----ipvktgl-----yks--as--------------
---------------------a--t-------------------------
-----l-----------a-----vhel-------l---nts---------
s----nrl---hd---------tdleq---glk------kh-------tg
di-d-----------qqkvdp------------y----a--glkvidpta
aiq-kllkigddpgdatdg-pandq--n--------iyrte-----klgs
gkcans---y-lnnqedgtpsvcpewtp--merklgd---skakq-----
---c-drahd-------m--kmlvaefge---klgar-ddy----nnhlq
gc---klfvyln-evvdc-------fayast-sa-gad-vtqga------
--------gad-----p--------------vnls---------------
---------------------------degl-------vsqala-----a
------e--d-----ikl--eqkmn-dlsak-ks-vtadg-yvrgdl---
-d-asrgp--wnh-gklrkc-----analdkp--r--q--yvf-------
e---wtcev---------lsadis-----klqkl-p---q----------
------------------------------------------vpqtscsk
-nn-atnftpk-----al-------srs---dcv--------tkyqmtq-
--sqc-------a--kact---a---c----ad-t------gqpfy---g
-skigacllki-hkkt-slca-nhype--------rtv---hgelgid--
------dv------------------
>node15
s----------paqtlyqpm----------r--kk------fehykaaav
p---glkyyfs----k----yp-----i----t-sa--ea-------l-i
gkiplvgi---rpy--n-ki-------------ikeya-----rgpkawt
is-vsc-q-----ngakpss-l-aa---------------srin--gfll
g-ha---g-ngqq----vnr----ig-qs-----k--g------------
--p---sysc-------v--epgl-----ttsltaeitl--tysr-----
-----n---gd-----ia---a--t-------------------------
-----v-----------n-----asgnscq-yg-l---vafhdedipfld
v----sgl---ascgsaey---snvkq---glk------as-------nr
---t----------qia--np------------y----nkkalkvldpek
glr-r--------a----dpask--f-q--------vfgiq-----qsmp
pkctni---iedvdeveea---------tlm-q-------kgnr-lqykr
dnlsedkkhn-------s--sl--------------r-def----ngpll
g----kgy--ra-d-----------yays---sd-apd-etna-------
--------g-------ah-------vnk---svlpd-------gsiegac
-----------------lef--a----nrglvqmria-mgqflg--g-sa
------d--d-----vki--sakla--------s-isv---f---sleek
qddslrsp--wlh-ak--qs-----l----nw--y--q--yay-------
e---wncqc---------a-----vfg-------ph---nr---------
----------------------------------l--lgf--vaekgcnk
-pr-amsfaek--kin-------q---s---kcvek--laqktkvqvhp-
--v-n-------i--kaca---a---c----ee-ta-rhlahkpfyairh
agkcggimlkicrekt-seck-n--api-------kgt---h--l-----
----kydlisk---------------
>node13
s----------p---------aggkiegg-ptaqr------hehy-tegv
p---glqyyps----k-epayp-----s----------da-------l-l
arlplthi---k-------v-------------iygyt-----r--kgwt
ls-vtc-q-----dvskpat-v-dhcf-------th------gk--gfal
i-hk---e-qgqs----vp--------qsfvahym--gvfv---------
--p---shdcqd-----a--kpgl-----ykg--asysltssfsa-----
-----d---gd-----da--pg--t-------------------------
-----v-----------t-----ghdl-------l---qtph------vd
v----nrl---nd---------tgfeq---glk------gh-------tk
dicd-----------qekgep------------y----a--elkvidpee
slq-nllkigneps----k-pansp--d--------ifgtq-----klgt
gkcann---vglddpeegtpsvcie--p--merklad---mkak-lnqks
ddlc-nmrhd-------m--kl-----gd---ktgar-ddy----ngelh
gc---kffvfrs-da----------yaya---sa-asd-vthta------
--------gag-----sh-------vek---vnlp---------------
---------------------------degl-------lgqvst-----q
------a--d-----ikv--eqklt-dlpas-ts-itveg-yvrgel---
-d-nsrgp--wnh-gklrkc-----a----kr--f--q--yfw-------
e---wscev---------v-----ifgdrnlqkl-g---r----------
------------------------------------------vadkscsk
-pr-emtfttk--------------ars---dci--------tkfqghs-
--arc-------r--kaci---a---c----te-t------grpfy---e
-pkcgacllki-hkkt-sdcl-nhyaei-------rgt---h--l-----
------dvvsk---------------
