>A
rl----------------glpmila--------yg-s---------l---
ags-------c-----------------eeanlt---eg---y-l----f
aga--leqg-------vq--tphilqdql-mi-lyl-i----vv--l---
dklvfkfiia-gad--irdfgaqa--q---gqkes----------f--pe
s----n--ekegd---lg-nh--aeteyldynf--a--gytqdhwk----
--rhv--ag-v------qklg-----gskkgqkvtava------gg----
--ksps------a--a----flfi-avcvdla---a-----adsvicapg
--yvkk---ptahs-ki---ipsl--q------------cltvfad-f--
-----ik---gvypen-----ch---gfvi--tpaaacprlakkgkaaak
------vra---------wy----drpg--------------d-------
-------clsp----gsp--h------q------------kn--------
--------------------lc-v---y--------p-vysnnhgp-htt
-ln-tk-hktrnngaqdr-avv-------e---rgg-------valdlfw
mg--i-------------------fvtps-y--ew----a-epkcggf--
----------------gstegvw-----rtae--qndgk-p--kd-----
--qft---p--keppe-fnsvgysnk-phvkw--------ekgpvp---p
g---svctdggks-----l---ptea--------vsqcgll------yv-
------------cc-kl--elftfvsrnfgdvkrdgraa--vsl--i--s
liddpv--------v----sgpneknkahfs-ewhk-----gvktkdl--
--p-------qhydv---rkmheggg-ivl--p---dstfaa--------
---------------laq----vdlv--------i
>F
nt----------------nff-feyqghe--grlaprtlaseterps---
hdyskrkthnclgatltdggkphg----ghpskt---py---v-e----y
rvn--ivya-a-----i------ft--------dy-vs-----dltr---
hrgsfk----tan-----vfdpsttkqcpd----s-------fpaagv-q
h----g-vgv---fvfhi-hl-----e---ikf--e--i-----ah----
--gqtksrt-v-------erl-----s-----ln---dlakhlpkhpapl
astd---gpgnaq--p----tltlknf-anlv-hgl--------------
--------lld-----s---knsi--d-------------iaetgg-f--
-----------csveq-----kh---d-------krv-----------tp
------akc-------sewi----e---------------atg-------
-------mlae----skplgdgv-drlh--------k--s----------
---------------------ycp---i--------t-kpenagqrkshl
-lrkgat----------h-a------clraiml---------------lw
ka-----gl---t-------i--katspp-y---w----nmlhlcgayt-
----kveqlaegavt--------nvmrlq--plkkad------la-h--e
htqslq--n--m--pk-ccap-yadlaas--r-laqhnla-------ln-
a---tg--hgveaksnyefcplpf-----------kdytlv------sl-
------------tspklgmrlfvraafp-------------fkmts---v
pl--v---------l----vlk--frkqscaiawtv--trihq--kesgk
vls-------khqerkgpr---lgsde--l--l---ndqtndeeklrfly
vift---------tkl-q----lplagpsfats-l
>G
s--------------------vfalasvq--nslnpn---------ddka
nnf-------cl----------------kpvpqacl-af---v-t----y
s-----gltks-----md--aesyt-------------------------
frsshd----sek-----ifntpd--acpk----p----------r--gk
afg--skven---fyt----dvd---v---ksii-a--n-----g-swak
lggsv--sg--------ksms-----laarfida---g------gq----
--tt---qppsggtrg----vlvi-tv-mdilqfav-----ad------q
--yak-vhtlh-ntswqaahnrsl--dtpgylktafisg-vaattk-fvl
tfsrnns---ecpvesnwngsqd---e-------ksl-----------tr
------eysktv-csg--wi----d---------------avacald-dt
lagigcfvlvd----tkphlhlh----hd-d-ifklsgttagsk------
-----------------------tekva--------s-atveprkvtd--
---kg-v----------kgs------s------a---------fg---cw
re--ad--m---as-----tv--kftnev-ycr-l----t-nrd----l-
----m-------nvgk-------kirsir--r--gpdaqat--lt-crep
vsantdc-h--m--pe-cys--yqnasa-----lankntl-------vf-
vdtfrg--hvs--ag--kfaslrk-----------tdcvil------ll-
------------cfpgvllgl--rgfy-g---------vafl--------
----sdnshkvaldlsripppk--fkkqphs--------kahg--kptg-
sdar------khrnrkaqk-----tdsgel--g----shkgg---cllla
vvft---------arltqlakklqlv--------l
>node6
kpc--------dpglqlfgfvmlla--------hnga---------e---
aks-------c-----------------seasat---sfv--qal----f
aggkpltda--fplvran--vqtipg-hi-gi-lyylt-----k--l---
hrstik----sgrs--t-dyaavs--h---gqn-r----------l--re
e----s--dk---saslt-hh-----daleyef-fahvq---dhwt----
--shi--s---------knqe-----amrsgttv---n------dq----
--kapeepqvaps--t----avg--evcvdllavgt-----atptlevqa
--yak-l-vqktgdqri---krcl--e----------------ndsaiwv
-----lk---glvasq-----heateiifeaglpht--------------
--------c---------wy----d---------------q-v-------
-------cldt----sst--hiw----qt-n-d---cdsnrktllhwlqp
gsvsr--------------vfc-i---fclirsgevn-kyqaaqdp-kev
-mr-ls----kgs----p-sqvhlktsfmt---rqa-------lql--i-
-at----ie---ls-----tvff-yvtrpnf--sl----c-drrvggyh-
----q-------kgs-------------------------------n--y
ninqmdc-v--rlqpe-ksnf-ysgv-ph--w--------yk----qlyv
g---vacvpaesr-----f---hmdl--------vdqtadv------al-
------------cs-kl--smfslgqyng-------------hl--i--n
lllsal--------l----rptnaiqrshfapnwhr---g-kw--kgs--
--p-------hqler---q---kgai-ivvvgk---ndgdka---clyty
aefs-------vlgklaq----lrlq--------i
>E
qt----------------hfy-fdlhvhaeggslipr---------p---
hdy-------cleenl--------------ptrp---gf---k-eegdly
gag--mtys-g-----dk--vhsft--------sf-vp-----eitv---
hqsefk----p-------vfnkatakkcpk----r-------faavgl-d
h--de----t---fvvri-hl-----e---ldf--e--l-----pn----
--gqakpsk-vrfteagvdtaplh--gplksevv---d------kdqig-
--vn---qpyktq--a----vivl-sf-adllpqal-----q--------
--------ald-haawt---kdsi--e-------------atalag-f--
-----------cpvqq-----kk---e-------rrk-------------
------skc-------seni----e---------------gav-------
-------vlad----seppgklk----qa-psl---r--sq---------
-------------------igysp---v--------y-kleepgaskvhl
-lkkggt----------n-a------tllg---gksklagsen-----lw
ks-----aleqas-------r--tattgp-y---w----k-diqcgdfa-
----kvsq--kgrvt--------kimks----------------t-h--e
llhdles-n-----pk-ccsp-ygdaaks--nvlaqhsna-------ly-
s---tg--q-ieakssndycslsm-----------rdcplt------sl-
------------pfaklslslfkrahfp-------------frl--sqat
lv--md--------l----ktp--yrkhsyaevwsvtitkiht--keksk
las-------rhhakqgnr---kgsdg--l--s---ndqndgvqkilfly
vtfq---------qdl-q----lpli-------rl
>B
ra----------------glpkfan--------fg-v---------l---
sgn-------c-----------------sqasta--esf---h-l----f
ssg--ltgt-------vtlkthavtg-hlgmr-fylit-----e--l---
dssdai----dake--vreyaaqg--s---gqrrp----------l--re
-----l--graaecpvlt-dh-----gvleydf--a--g---dhwa----
--nhd--eeim------rqkg-----gatknekg---t------ng----
--rspt-hqvqap--d----vlgq-tvynell---t-----tdgelc-pa
--yakr---etthpnkv---kasl--d-------------lavlkn-fvp
-----tk---gayaqe-----t----gikm--tlp------------gak
sdwapsvks---------wy----drtgkpvgtgspnkpras--------
-------cltptthvgsk--h------qt-e-r---adnsns--------
--------------------ic-k---f--------p-vftnhqgp-dtt
mld-ai-hpaknsaveqk-gnv-------d---reg-------vak--fr
mg--i-------------------fgtgp-r--gw----a-errcgglh-
----a---------algps-glw-----rtdq--qa-nk-p--kdyk--y
ptgln---p--qypte-ftclscpak-rsfkw--------dk----glyt
g---sgcidggik-----f---ffal--------isncnll--nsgkyve
vgvptedglakpcc-kv--tiypfvsfnf-----dgvae--fsl------
llddel--------l----vppsqnekshfsmdwqp-----gv--kgl--
--p-------qhfav---mkmreggg-lvl--p---ddk-dt---clykn
vdlfaspnvraglptmaq----vvlh--------i
>D
kpc--------spnlnlfg----la--------hngg---------e---
ckt-------c-----------------gdasss---kfisnqaq----f
sggkpltet--fpldqan--vgtfps-rl-gftlyyll-----k--n---
hrskpk----pgrs--s-d-atvs--k---ghn-r----------l--sq
a----n--dk---aasliqhh-----vtleyqf-fshlq---dhrs----
--shi--d---------knkp-----vrrhgnav---n------de----
--kapqesqvchg--l-----vg--evclellav----------lldvrp
--ynk-l-vektgvpri---sscl--e----------------napevrv
-----ltl--gliasq-----heglgiifeaglpnt--------------
--------c---------wy----d---------------q-v-------
-------cldt----saa--qiw----qy-n-k---cdisrdtllhwlmp
gsaav--------------ifc-n---fclirggeingryqpaqep-kqm
-ak-ls----kga----p-skihmrt--tk---rqa-------ldl--i-
-aa----ie---vs-----avlf-yitrpng--nlntcgc-qrrtggyh-
----q-------nes-------------------------------s--y
ninemdc-v--rvqpe-ksdf-ysgl-ne--w--------hk----qlyv
g---vaclpannr-----f---hmalvcvclsqlvgqandvat----al-
------------cs-pl--slf-laqvng-------------vl--k--n
llmkgl--------l----rpvnairrtqftpnwpr---g-kw--kgd--
--n-------hslek------------ivvvgayaadegdkg---clyty
qefk-------------------qlq--------i
>node3
ra----------------glpmfvn--------yg-a---------l---
ags-------c-----------------eeasvs---ef---y-l----f
ssg--ltqt-------vt--thaipgdhl-mi-lyllt-----q--l---
dksnfk----aakd--vreyaaqg--h---gqrkp----------l--re
n----n--dkegdcsala-nh-----galeydf--a--g---dhwt----
--rhv--sg-v------knlg-----gaskgekv---a------gg----
--rsptehqvhap--p----algi-avcvdll---t-----sdgvlcvpa
--yakr---qsthgnkv---kpsl--e-------------lavfnk-fll
-----tk---gvyaee-----tq---giil--tapaac---------gvk
------vka---------wy----drpgk-----------psd-------
-------cltp----gsk--h------qt-d-e---sdenkn--------
--------------------ic-i---f--------p-vyennngp-stt
-ld-sk-hkaknngvqdk-aiv-------e---rgg-------lam--fw
mg--i-------------------fvtpp-r--ew----a-errcggfi-
----a---------algss-gvw-----rtkq--qaegk-p--kd-k--y
ntrla---p--qyppe-fsslgypgk-phvkw--------ek----glys
g---agcidggir-----f---pfal--------isqcgll------yv-
------------cc-kl--evfsfvsfnf-----egvaa--fsl--i--n
llddal--------l----rgpneiekshfsmewhk-----gv--kgl--
--p-------qhyav---kkmhdggg-ivl--p---ddtfds---clykn
vdlf-------glgtlaq----vvlh--------i
>node14
kt----------------gyymfalaghe--gslaps---------a---
hnf-------cl----------------tepekt---gf---i-q----y
gag--lsys-a-----vk--ahtft--------ay-ls-----hldi---
hkssfe----aak-----vfetpg--kcpk----r----------v--ge
n----g-vet---fyikv-hn-----e---fdf--e--l-----ss----
--tka--sg-v------kdre-----gpkkgadi---d------kq----
--tn---qpnnaq--a----vlvl-tv-vdllpvgi-----ad------g
--ytk-l-llqfhkswe---krsl--e-------------iaakek-fgl
-----vn---ncgvdt-----qq---d-------ryv-----------tr
------akc---------wi----d---------------gav-------
-------vlad----stpqghlq----qt-a-l---seanegnklksl--
----k--------------vgyaa---v--------s-steepsepsdnv
-lkkget----------k-a------sllt---gkd-------ygm--iw
kdgsatcal---ss-----tv--kftngp-y---w----n-errcgdfl-
----q-------hvst-------nikslr--n--ksdsn-i--mt-t--p
kvhnlec-h--m--pe-cctp-yaaaaas--w-lankena-------ly-
g---ig--qgvtakgsagfcplpi-----------kdctll------tl-
------------cfpklamslfirvhfrd---------lkffkl--a--t
ll--ve--------l----kps--fkkqpyptvwav--skiha--kgtg-
vnsg------khherkatk---kggdsavl--a---nnqneg---clfln
vvfs---------grlsq----lpla--------l
>C
kpceghfnwsdspglsyvgflilla--------hngd---------q---
akr-------c-------------ikhrt--------afa--hal----f
adgraltdt--fplvaag--vqttp-----gi-lyyknfpap-k--mcrk
hrstik----sgrkffs-dygslt--q---gr------------------
--------------asla-hh-----ealeyef-fahvd---d--r----
--shi--k---------rnqe---fsairpgvvv---i------tq----
------------g--t----pvg--evcvallclvt-----nspklevea
hstvq-l-vqkggdqrl---rrcl--a----------------ddsaila
-----lk-cgglvasq-----heatciifdsgekht--------------
--------c---------wyewghd---------------q-v-------
-------clet----aat--hiw----qtet-e---cesh-------lqp
gsvdk----kpaeaecaqqvlc-d---fclirsgein-pfqsaedr-q--
----ls----kg-----p-sq--iksaymh---rqr-------lrl--k-
-tt----ie---lnacdptpvff-yvyrpnf--lf-------------h-
----r-------sgl-------------------------------d--y
ninqmn-----rlqpetk-----------------------t----kpyv
g-----cvaaeck-----l---qmdl--------ieelaq----------
-------------------svykltqyng-------------nl--v--p
llltal--------l----rlsglverchfapnwhk---g-kw--kgd--
--p-qpdgvthq-er---d---kgaa----van---ddt-ka---clyty
gefs-------vlgkllk----lkmk--------i
>H
t------------------cyifplaain--kskhpt---------dqte
hal-------cl----------------kppqkacy-sf---i-a----y
s-----als-a-----vk--vesft--------ah-ln-----hlsm---
frv---------------iygvps--gcpk----caersqaq---i--ge
k----e-vea---fyk----avd---------------f-----g-----
--tga---g--------tpke-----vevrfadi---a------gq----
--sl---rppnaq-rvrlrkvavv-tl-laglqigirmmlt--------r
--fke-a-slqlstsweavhqrsllydnp-----------iaatak-ftl
-----------cggca-----hq---e-------ryv-----------er
------efckkvpc------------------------------vldgpt
lgnggcfvlvd----sspqahlse---qd-e-i---meltaanklkde--
----rvkkt----------vgyssekva--------h-atvqpekpth--
---kgdc----------kta------silr---tkn-------s------
rddeap--m---as-----pv--kfsnga-y---l----n-nrn----ls
gaidq-------hvsi-------hidnlr--h--kleahlsek---c--p
kcknqdvvhavm--pe-cytp-yeaktts--w-lekkdhl-------v--
----rg--lvatkag--gfcsvs---------------vis------tv-
------------cyprlnlglylrahysl---------vayytl--k--t
ll--te--------knsapnpt--fktpaye--w----skipa--kgtg-
k--g------shhnskakk---mgansgdl--g----vh-eg---clhgn
vvfy---------eklpd----lplv--------l
>node10
kt----------------hfy-falqghe--gslapr---------p---
hey-------clgatltdagkphg----gdpsks---gf---i-q----y
gag--ltys-g-----vk--ahtft--------ay-vs-----dltk---
hkgsfr----pak-----vfdkpttkkcpk----r-------fesvgl-e
h----g-vet---fvvri-hl-----e---fdf--e--l-----pn----
--gqaksst-v------rdqe-----gplksaii---e------khpaa-
--tn---epynaq--a----vlvl-sf-adllphgl-----a--------
--------lld-hkawt---knsi--e-------------vtaaag-f--
-----------cgveq-----rq---d-------rrv-----------tr
------akc-------sewi----e---------------atg-------
-------mlad----skpqgklq----qt-pnl---s--nq---------
-------------------vgysp---v--------t-kpeepgepkghl
-lkkget----------n-a------slla---gkd-------ygm--lw
ka-----al---t-------v--katsgp-y---w----n-nhqcgdfa-
----kvsqlvkgrvt--------nimslr--p--kae------mt-h--e
kahnlec-n--m--pk-ccsp-yadaaas--w-laqheha-------ly-
s---tg--hgveakgsnefcslpl-----------kdctll------sl-
------------vfpklamslfvrahfp-------------fkl--s--t
li--vd--------l----kts--frkqsyaivwav--skiht--kesgk
vas-------khherkgak---kgsds--l--a---nnqndgvdkilfly
vift---------tkl-q----lpla--------l
>node15
ra----------------gyhmfmladhs--aplaas---------a---
hgs-------c-----------------teasvv---af---q-l----f
gag--ltyt-------vk--vqtftg-hv-pi-ay-lt-----hl-i---
hkssfe----aar-----vfetpg--h---gkr-r----------v--ge
n----g--dt---yyili-hh-----galgfef--s--a-----wt----
--knv--sg-v------kdrd-----gpksgani---n------kq----
--sn---pplhpq--e----vlgi-tv-sdllpvgi-----advllcvpg
--yak-v-vqeshgswe---kpsl--q-------------iavrdk-fgi
-----vk---gcgade-----eq---g-------ryt-----------tk
------akc---------wy----d---------------pnv-------
-------vlde----gaa--hvw----qt-a-l---sdaskknmlksl--
----k--------------vtcai---f--------s-syeepdep-dnv
-lk-gd----tysgipdk-ddvhl--tllt---rkd-------ygm--iw
rkgsacctl---ns-----tv--kfangp-f---w----h-ekrpggfl-
----q-------hvsagsn-giwklkslr--d--ksesr-v--ks-n--p
kvhnlec-p--q--pe-cynr-ydavaar--w---------------ly-
g---vgcidsvikkasggfcpapisl--------vkdcqll------sl-
------------cfpkl--siftrvhfng---------l--ftl--a--s
llhkve--------l----rpsgafnkshfntawnr--ssihv--kgtg-
vspg------khhervamk---kggd-vvl--a---nnqddg---clyvn
iefs---------gklah----mple--------l
>node13
k------------------cyifalaaid--qslnps---------adtt
hnf-------cl----------------kppekacy-gf---i-e----y
g-----sls-v-----vk--aetft--------gh-lt-----hlsi---
frtsfe----aak-----vfetpg--ncpk----r----------v--ge
n----e-vea---fyi----dvd---e---kaf--e--m-----g-----
--tsa--gg--------kpke-----gsgrfadi---a------sq----
--tt---qppnaq-rg----vlvl-tv-ldilqvgi-----ad------k
--ytk-i-tlqlntsweaahqrsl--ekp-----------iaatak-fal
-----vn---ncgvss-----qq---d-------ryv-----------tr
------eyckkvacss--wv----d---------------gaacimdgat
lagdgcfvlvd----tspqghlq----qd-d-i---seatagsklqsl--
----r--------------vgysaekav--------s-atvepakptn--
---kgdi----------ksa------sllr---dkd-------yg---vw
rdgaag--m---as-----tv--kftngp-y---l----n-drh----l-
----q-------hvsk-------hikslr--h--kpdaqls--mt-c--p
kcanldc-h--m--pe-cytp-yeaasas--w-lankdnl-------vy-
v---rg--hvatrag--gfcrlsk-----------tdcvim------tl-
------------cypklalglyirvnyad---------vafltl--a--t
ll--te--------lsrapkpk--fkkqpysstw----skiha--kgtg-
gdsg------khhnrkakk---mgtdsgdl--g----ehkeg---clfln
vift---------gklsq----lplv--------l
>node7
ra----------------gfqmfml--------lgga---------a---
ags-------c-----------------teasvn---ef---q-l----f
sag--ltqt-------vn--vqtipg-hv-pi-lyllt-----q--l---
hrsnfk----agrd--t-dfeaha--h---gqr-r----------l--re
n----g--dk---ctsla-hh-----galdyef--a--p---nhwt----
--shv--sg-v------knqd-----garsgakv---n------kq----
--kdpeepqvhpq--a----algi-evcvdllpvgt-----adpvlcvpa
--yak-v-vqkthgnrv---kpsl--e-------------lavink-fll
-----vk---gvvaee-----qq---givt--iahat-----------vk
------akc---------wy----d---------------pnv-------
-------clda----gst--hvw----qt-n-e---sdsskksmlnsl--
----r--------------vic-i---f--------s-syedaqdp-nev
-lk-sn----knsgitdk-tdvhlkssfmt---rqg-------lsm--iw
qtgsvcctq---ss-----tv--kfvtsp-f--ew----c-erraggfl-
----q-------kgsagsh-gvw-----r--e--qaesr-k--kd-s--y
kvhlmdc-p--qyppe-itnl-ypgv-ph--w--------dk----glyg
g---vgcidseir-----f---pial--------vdqtsnl------sl-
------------cf-kl--smfsfvhfng-----egval--fsl--i--s
llhsal--------l----rppnavekshfsvdwhr---n-nl--kgt--
--p-------qhher---k---kggg-ivl--t---ndtdda---clytn
vefs-------tlgklaq----vplq--------l
