>B
-----------gcalk---twlhsav--tvhktkvna-lkpfgkevdi--
nag--h------------------hs-----sa----ek---l-----hd
pssl---ygaamyknc---------------------------nsf-nic
al--gv-----v---------------at-altac---sggrgppehg-q
tse------helaclpdpkv------agcnc-srtvsgkhk-----aapp
evslggrrndpqt-----------------------hqk---pgnqtt--
--pcvdagapr--p-afqkykaedh------------gci----------
-sl--------------er-vtlvg--r-----k---tinkqs---f---
lr-ppt-----------------t-----pknsvvvqv--l-pprtyaig
---caggvysvtpkda-k---------c--qgsadegrfqy----cklqv
qgaglpra--tk-----------------vyiy-nlvprtvte-------
------------m--k--sqkkhk-hl--p--i--ikgtphtceclrg--
-----idc-t--ekst--------yhllsesikg-re--sdepn------
--------s--fkqi--------dlat----------ft-----------
-tvqladtkpfe---kfnrsmrr--gkw---vhhh--vsyfdllaskvea
nkt--g----vma-----lkvetgga-y--------p---q---enmlns
lt--------------edh---kladgc-wrcihtlegla------alaq
a-alkdaay-sf----------gagqn----h-vfvhff----------k
lfrea--srlk---------fy----sdr----gkagt--t-rk--mr--
--at-v---rkglsaaytaqeht-i-----k-------q-sg---ivfts
kkgyre----m--------nt-gkpca-------------------l---
eptvyltt---ta-----------da---------vc---agcwrk----
-------d-kvfyip---------------kqd---------------c-
--------f--s--
>F
sk-------tercayk---dhvrk-a--k---iklsgfikk--ggfak--
rqk--y------------------pase-shtd----hetgkm-----gs
sgnv---acgakcklq----------------------------pfidfs
tl--gq-----k---------------fvraslce---ngts----qg-p
ccd------q-----rqlglnvspek----c-n--v----k-----rddd
epkykp--------------lg--aacafsianlscg-----sghnlgs-
mv-----------n-ll-qafadansskikt--e---vgpgi--------
-ksehflkhldvlen--v----ttg--vpp--akkiti--kdn---y---
--------agklfrrsvdra--ks-----mddkv--ri--t-lh---svk
-----i---------dgik------p---kgna--t----y----ce---
---alglkastl-----------------------------lll---ssl
qls---------slh----nttvk-l------------vsipv-------
---------ggeaavt-------------------scdklhlp-------
---------n-kvrh---sw----vtk----------ldkgt------fc
lsrk-----khe---vy-----------ts-vnta----------v--rs
qnn--a----ila-----lv---asvpv--------a---r---n-----
-----------------ct---yvsanc-------------svs-----h
p--maseq---f-k-------se---e------------------pevgf
l---rdt----r----d-tvkq----gqk----lipgt-lscrnkgak--
--ac-v---ksetsa---g-----i-----nr--vkake-cg-----rfv
ka--kqeiglq--------hptlcsclkkfv-------------kkn---
lnsslksl---sfsntl-------ns---------m--------gkh---
-------h-pv--vp---------------akhqe-----ee-vnnhke-
--------in-dka
>node3
e---------qgcalk---ewlhs-i--kvhkvkiha-lkpfgtevdi--
nag--h------------------hn-----sg----en---l-----hd
ansl---fggaktknc---------------------------dpf-alc
al--gh-----y---------------tn-almsc---sgqrappeeg-q
ice------hglavlptpkl------agcnc-gkpv----k-----eapk
gyglggr--kphr-----------------------hqk---pgnett--
--pcvdaaapr--p-gfrtgkvdih------------gci----------
-aq--------------qv-vtmig--klg---k---t--kss---f---
lr-pptl---------------rg-----pkhgv--qv--l-sp---dvk
-----a---------a-k---------c--edaadk----f----ck---
---glpktpstk-----------------vyvy-dlvprtvtnm---l--
-it---------k--k--sqakhk-qladq--i--ikgtahtcaclrp--
-----vdc-n--dkst--------yhklveqfdg-rq--adesn------
--------n--fsqi--------nlsk----------lt-----------
-tvq-----pfe---rfevrvrs--gkfhd-vhdh----------skvet
nkg--p----vva-----lkviaggv-c--------p---q---dsmlds
lk--------------ddh---klapsc---cihslqgla------amsh
a-aiqdsey-af----------a---p----h-ifvhlf----------k
lfrda--arlkp----t-tify----adr----gkant--t-rk--vr--
--ad-v---kkglgaankaqaht-i-----kp--tstka-sg-----fct
ak--rke---k--------hn-nrvcv-------------------l---
eptvflst---tf-----------ep---------vc---ascwrk----
-------n-dv--ip---------------tqd---------------c-
--------f--s--
>node7
e---------pecrlk---erihq-i--rsnivkvha-lktfnteiel--
hag--h------------------in-----gg----ed---v-----he
ansl---fcggktksc---------------------------dpf-avc
al--gq-----n---------------iksallsc---sgqn----ea-t
icd------hglmvlpnpkl------a---c-gkpv----k-----kapk
gyslgsr--npsr-----------------------hqk---pghels--
--pcvdaapnr--p-gfrpgkidthen--ai--egapgsi----------
-ah--------------qs-vaisg--kvg--dk---t--psg---f---
-r-pptl---------------ha-----lnhgv--qi--l-ap---dvk
-----a---------d-g---------h--eda--r----f----ck---
---glqrkpgtl-----------------vy-y-ql---avtgl---h--
-ia---------n--d--sqakrk-hlaaq--v--vkseahtcgylrp--
-----lcc-d--gstt-----------------g-re--atasn------
--------n--fahi---------mak----------lt-----------
-skk-----pfd---qfe-------gkysd-vhdr----------sgvqt
nkg--a----iva-----lkilasgv-c--------p---q---dymlda
lk--------------dsl---ylapsc---cihshqgqg------alvh
p-airntdy-afsr-------ma---t----h-ifvhlfngiftgpnvgt
lysev--vkkkm----t-tvfh----amr----gmstk--t-rk--vr--
--av-v---tkdlsa---asahm-i-----sp--taeka-cg-----fca
se--rke---k--------hk-scvsvnkyv-------------kql---
dctlflpa---lf-----------dp---------ic---adcwsk----
-------a-di--ip---------------tenkr----hn----nhkc-
--------f--arg
>node13
ee-------lee--yk---geike-a--i---vpiqg-lkd--adfee--
gsp--y------------------ne-----sgnv--hhvmset--khea
tgel---fcgdqckvs-ald-ddkktg-----shp------eqkpfinlc
vv--gh-----nld------------vflkgplcr---aaeq----hk-s
icglnklplg-----pqvk----qph----c-t--l----e-----rgdk
dpkyqpq--ngsr-----------------------tga---pgedlgqk
sv-----------psffqevqlnaddk--ke--e---gnl----------
---q--iehsdflpt--e----atg--sig--skkv----ngdktlf---
-krpladrsgkl----tdmtavhnl-lpr-nagv--qi--vwsr---ev-
-----a---------d-akef--k-e-qgsega--r----ygnhrcg---
---gmearagtlgqaaagw--nnktkq-avf-y--a---givql---p--
-la---------k--gvk-qsktk-n------------hkgac-------
---------g--d--s-----------------g-fcewtefp-------
---------r-pvlh---------lvk----------kk-----------
-skk-----dlr---afe-------grltnsvdgk----------v--rt
rke--h----vtvkvnmild---aqiac--------l---q---rfslgk
lk--------------p-t---y---dcg-----------ln---tvllh
p---------tflp-------ge---e----h-r----------gpglgt
l---rgg--kkk----q-qtkp----el-----------ltcrk--ak--
--pk-k---rqdiyi---e-----t-----cq-mpsfkk-cg-----fhv
ks---kd---s--------hgslclcitkfi-------------kkatt-
ictkfks----ff-----------ny---------vcg--ad-wekh---
-------h-sv--vp---------------akhph-----kk-pgddke-
--------fnhn--
>node15
ek-------yeecrfk---gkirq-a--r---vkihg-ekn--teiea--
hpg--h------------------mk-----gg----hdvdkg-----ga
agnl---fcgtktkas---------------------------kpf-alc
vl--gq-----k---------------fmsgllcc---sgqk----ng-t
icg------qglmvlpkpkl----------c-g--v----k-----raak
gpsfvsw--nssr-----------------------eqt---pghels--
--ncvdglvnk--p-mfqqgkidahen--ai--e---ggl----------
-anq--vdhchflehthqs-vaitg--stg--ekkgat--pag---f---
-r-ppal---------------ha-----lnagv--qi--v-ar---dvr
-----a---------d-gk------p-h--dda--r----y----ck---
---gmqprpgtl-----------------af-y-pa---getdl---h--
-la---------d--d---qakrk-hvaiqqsv--vktiavtc-------
---------g--gavs-----------------g-rspwasas-------
---------q-farh---------mvk----------lt-----------
-tkk-----nfh---qfe-------gklts-vhnr----------s--rt
nnd--i----ita-----ltlagsgv-c--------a---q---dyslnt
lk--------------eat---ylapac---ciqshhgqglesnnpalvh
a-aiannqygaysr-------aa---a----h-i----------gpdlgt
l---t--vkkkk----s-tvkh----gmr----gmsakgit-rk--ak--
--av-v---kkdlna---e-----i-----sp--aaaka-cg-----fca
re--kke---t--------hr-dcvcltkfv-------------kkl---
ectlflsa---lf-----------np---------vc---pecwgkr---
-------p-di--ip---------------tkhrr----hn----ahks-
--------f--akg
>node10
sk-------tekceyk---envrg-a--k---vkldg-vkn--ggfkk--
rpe--f------------------qes--gnsd----hdvgke-----ga
sgne---scgakckls---------------------------kpfvnfs
gl--gq-----h---------------fmrgtlcs---ngqk----qg-s
tcd------q-----rqvslnacpek----c-g--v----k-----rddk
epkyepr--sitrgek----lggtaacafs--nlgvt-----sghdlgs-
mv-----------s-llqqalldandnkiki--n---vslel--------
-kneqklnhldvley--s----iag--spe--akkiti--kdd---f---
--------agklfrrkaere--ks-----meakv--qi--t-gr---dir
-----v---------davk------p---agna--k----y----cm---
---gmglkaetl-----------------------------lel---n--
-ls---------t--gev-nskak-h------------vsipc-------
---------ggegavt-----------------g-scekvhlp-------
---------n-hvrh---------lpk----------lkkkt------fc
lskk-----kvh---vfe-------gkmta-vhkn----------v--ra
qnd--a----ita-----la---asvpv--------a---q---dfhlna
l---------------ect---yvstnc-------------sssslalvh
p-amasdqftaylk-------se---a------------------pevgs
l---rdt--kkr----d-tvkq----gqr----liastglpchkkgak--
--ac-v---kpdlsv---g-----i-----sr--akakk-cg-----ryv
ki--kkeigha--------hrslcpclnkfa-------------kka---
lsttfksk---sftanl-------nc---------m--------gkh---
-------h-pi--ip---------------pkhqe-----ek-vsdhke-
--------fn-tka
>E
sk-------sekcnyk---eavrg-p--k---sklgn-lke--ggykk--
rpe--l------------------qgs-agnsd--kfnlagke-----ga
sskedrhscganckls---------------------------kpfv---
ak--gq-----h---------------ymrgtlce---kvnk----qa-c
scd------q-----rqvql-dckeg----c-g--v----kpqacdrnde
eskygpk--aiyrgeypshllgatsacafs--hvgyt-----pgpelgp-
mv-----------s-vlqqsyldanknlykiagn---itlel--------
-r-elklnhldvlvv--s----iql--apqlapqrvni--nsd---flva
--------agklfkrkaern--ky-----idarq--qf--t-gr---dir
pln--v---------ntik------p---tsgg--k----f----cm---
---gi-lkasai-----------------------------lel---n--
-lp---------t--gev-erkak-d------------vratc-------
---------ggigaat-----------------g-scekvqlp-------
---------tgh-hh---------lpk----------lktstekgapeyc
esak-----kgh---vfe-------gnkta-lhkeee--------v--rg
snd--a------------la---asvsv--------g---q---qth--e
l---------------dss---yv-----------------aagslvlvh
t-amlsdq--aylk-------tp---v------------------pevgk
l---ed---------------g----ghr----linstgl-----gnk--
--ac-m---kpdlgv---g-----i-----sr--akakk-ck-----kyi
di--kkhtayspytgliddhhtlckvfnkla-------------kks---
lsttfksk---pfnanl-------dcytfqlarp-m--------gkh---
-------h-ft--ls---------------prhed-----er-isdhge-
--------fn-aka
>node6
q---------pecalr---erike-i--khnivkvhg-lttfnneien--
hggash---------------esfid-----ga----ed---v-----hd
akal---vcggktkag---------------------------npf-avc
al--gq-----n---------------mqgallnc---sgqn--------
icd------hglmvmpspel------e---cpkkpf----k-----rlpk
gyklggt--skce-----------------------hnm---pshels--
--pcvnsapnr--n-rfrpsr--aqes--al--deapgsi----------
-ah--------------qafgaigg--kv-------------g---f---
---pptl---------------ha-----knh-----ltql-fp---elk
-----a---------d-g---------h--add--r----f----ck---
---giernpgtl-----------------vy-y-pl---evtgl---h--
-ikv-lpkpqekk--d--ssakrk-hlfah--n--ikpehf-cgylrp--
-----lcc-d--asaa-----------------s-re--aaasn------
--------n--lari---------mak----------ft-----------
-akk-----pfd---qfe-------gkyss-vhnr----------tevdt
nkg--p----vva-----lkmfasga-c--------pkafekaanymvgg
lk--------------tsf---ylaanc---cinsifaeg------gllh
htvirnady-avdc-------gg---s----h-vyahlfngiftgsdvgn
iykhv--vskkk----i-tkfh----vir----gmdtk--a-kk--vk--
--aa-v---tkglga---asael-i-----sp--aseka-canad--fca
re--rk-------------hk-sclavskyi-------------aql---
dctlflaa---if-----------dt---------ic-katecwpk----
-----pda-ti--iv---------------tealr----rn----ehkc-
--------v--arg
>H
ep-------iee--yrvsngeine-v--i---lptqg-ikd---efed--
gap--yssgrkdtdnfcfccl---pq-----sgnv--ehvrsetnskhea
dgel---fcgdeckvs-alekdd--sgkdfcfglpyrpaqvaqkpflnvc
vvsngh-----aadlgipgivvactevfmkgpycrnppappq----hk-v
vcgfnklklg-----pqig----qpn----c-c--h----e-----rgdn
dlqyqsq--ngsr-----------------------tg----pgedlahk
si---------fkpsglepvqlnnddy--n---------l----------
---------gefvpt--e----aag--pis--stkt----ngdttsf---
-arpladregrl--------svhslh--r-sksk--ql--iwar---qk-
-----a---------d-gkeyekkke-qgsvga--r----ygqhrcg---
---amegtsgthsqaasgwlghskt-q-vvf----------vqa---a--
-la---------q--kvk-tsktk-d------------hkgss-------
---------g--s--n-----------------t-fcewaefg-------
---------r-t-lh-----------------------------------
-skk-----dfr---gfe-------grlsnkldgk----------v--kl
eme--s----v-vkvnmila---aqitc--------l---r---rffpgk
lk--------------p-tdkay-----g-----------dr---tillh
p---------tfap-------te---eplinh-r----------apglgt
l---rdg--kas----q-epkp----el-----------lacrk--lks-
--dkfe---kigyyl---e-----t-----cd-lpsfkkpcg-----frv
ns---k------------------lcrtkff-------------kkait-
icpdfka----lf-----------ef---------nct--dd-wakhmha
vqdpe----fi--a--------------------l-----qk-sgdane-
--------ynhd--
>node14
dk-------tenckyk---gdikq-a--r---vkihg-akn--aefeq--
hpg--y------------------qe-----sg----hdvake-----ga
sgnl---fcgakckis---------------------------kpfislc
vl--gq-----h---------------fmkgllcs---sgqk----hg-s
icg------q-----pqvklgdcsvk----c-g--l----k-----rsnk
npkyqpr--ngsr-----------------------tqt---pghdlgq-
tv-----------p-lfqqvqldaddn--ki--e---ggl----------
-snq--idhtdflah--e----itg--spg--skkltt--pgd---f---
-rrppallsgkl----aqrq--hs-----mnagv--qi--v-ar---dvr
-----v---------d-gk------p-hgadda--r----y----ck---
---gmqaragtlghaianl--tkkakk-agf-y--a---gilel---n--
-la---------k--gvt-qskak-h------------iavac-------
---------g--gavt-----------------g-scewvemp-------
---------r-pvrh---------lvk----------lk-----------
-skk-----kfh---qfe-------gklts-vhnr----------v--rt
qnd--e----ita-----la---agvac--------a---q---dfslsk
lk--------------est---yvtpecg-----------lessnpalvh
p-avannqytaylr-------ae---e----h-i----------gpalgt
l---rgv--kkk----d-tvkq----gmr----mmtckglpcrk--ak--
--at-v---kpdlnv---e-----i-----sr--asakk-cg-----fya
ks--kke---s--------hrslcvcltkfv-------------kki---
lcttfksa---ff-----------ns---------vc---pecwgkh---
-------p-si--ip---------------akhrn-----qk-psdhke-
--------fkhtka
>A
e---------qgcalk---qwlhk-iafkvhrvnlh--lkpwgtpani--
nkg--h------------------hl-----sn----kq---l-----ha
sasl---iggakar------------------------------------
al--gh-----y---------------te-a--sc---igkrt-------
--r------qglavlpspkl------ggcsc-gkav----k-----dvpk
gyglggr--kphg-----------------------dek---tgkytt--
--pcvngvapr--p-girtgdvdeh------------gcl----------
-aq--------------hv-asvia--kma---r---t--gas---f---
-r-iptl---------------mg-----pkqga--ev--l-gq---dvk
-----s---------a-k--------fs--pdatnk----f----ck---
---elpktvask-----------------vcvh-kvvpqsltkk---l--
-ti---------k--k--pqakhkiqmspq--tnnvrgtahtcaslpvld
hvspk---------------------------dg-gq--aaesaclkeke
tlaktcgck--fasi-----ggltvggphegskegecln-----------
-tlq-----pfkprnrfavd-rtglgkfhd-fhgh----------pkvst
dkg--q----vva-----lkaveggf-cakflvsatt---q---dcvvd-
------------------h---alapnc---cvnsfqgvg------akgh
t-aiqdpky-af----------n---p----h-ifmvlf----------k
mlddk--grlra----t-tv-------dr-----nant--a-sd--tr--
--ad-v--lkkglgapndgeghdri-----kp--astta-ne-----fst
ak--rke---k--------hd-hrvct-------------------l--n
nptvflst---tf-----------ap---------vc---ascwik----
-------h-nv--vp---------------vqa---------------c-
--------f--s--
>G
sqgllskpefed--fr---vevtq-k--i---vpiqg-lkd--rdaeq--
gtp---------------------pm-----sgnv--htvmpet--dhea
sgel---fc-dqssvakald-dn-ttg-----ae---------kpfinlg
lv--ah-----nfd------------vflrnplcr---mnnq----hgtg
kcalnllrsa-----peik----qch----c-t--l----d-----qgdk
dpkyqpq--near-----------------------rngiepraadl---
---------------------lnldnn--ra--l---sns----------
---q--vdhsnfvpt--d----ad---------kki----tv-rtlf---
-krpmasrngnq----tdvtpvhdi-llr-nasv--qv--vwak---gv-
-----e-----------------k-e---------r----fgnhrcg---
---gmdaiaaslgqpsasw--ngktkqm-sf-y--s---gtvllwvap--
-av---------s--gvs-qtkky-q------------fkgac-------
---------g--n--c-----------------arfpgwtefp-------
---------l-lvvhltr------mvk----------ak-----------
-pkk-----dlr---afe-------grlddavdgk----------v--rt
dsekeh----atnrvnmild---aqiac--------l---a---rfsmgk
lninrsvlhsivk---s-s---y---dc------------lg---tillh
p---------sflpksyesia----------q-k----------gpglan
l---kga---------q-pnka----ql------------tcrh--ak--
--pd-i---rqlvyv---e-----t-----cqnmpffkk-cv-----fhv
kg---kd---s--------h--------kfiakqdgdlspgwglkkagk-
fctrfkt-gdeff-----------nl---------icg--ed-wetf---
-------h-gv--vp---------------a----------kgsgddqeh
niegalecfghn--
>C
l---------aqcalr---ervke-i--khdivkvhg-lstfkndmegka
aggask---------------arfie-----da----ed---v-----re
vkan---vcgnktkag---------------------------sef-gic
al--glcpaavh---------------migallgc---agqs--------
icg------hklmvfsspel------e---cpkkpf----k-----rlpk
gykvtvg--kkte-----------------------hnm---pnheis--
--pcvtsagnr--n-rfiphr--aqes--vl--gegqnst----------
-nh--------------pafkriggvrpv-------------g---f---
---pptl---------------hv-----klh-----ltel-fa---dlk
-----g---------d-g-------------ee--r----f----ck---
---glerdggtn-----------------vy-ykql---gcn-l---h--
-fklglakpqdkk--k--sslirp-ynysq--l--ikpghf-cnwirp--
-----rccyn--vsas-----------------n-ke--gaass------
--------s--lar------------------------------------
-kqk-----gfd---efe-------gky------r----------sdidi
-kg--p----iva-----lhmfgtge-c--------tkqfkkagdfmlgn
lk--------------tvf---ylsanc---cihglfaha------gilh
htvlrksdy-avdc-------gg---s----hgey-pifngfysgddvge
lykhn--vsrkkvshmvatkfgggsgnyrtaggsmsak--g-kv--ik-a
aeaa-vdv-teclga---asagl--------e--a--------gh--lca
re--rk-------------hs-scsavgqyi-------------gqq---
ncrlflda---ii-----------eg--------iac-kat----y----
-----pda-gi--il---------------aeglv----vd----hht--
--------v--vrg
>D
q---------a---lr---erike-c--kgninkvqs-lttfdneiea--
hpg-------------------tfan-----gg----ad---v-----hn
akaq---vcgnmtkag---------------------------npf-an-
----gn-----e---------------megalfnc---pgqq--------
vca------hglsvmpspel------e---cpkkpf----k-----slpi
dynlggv--gkcs-----------------------qdm---pstqls--
--pvv--------------------ds--sl--deapnsl--sltvfsft
gsq--------------qafaaieg--kv-------------g---f---
---patl---------------ha-----knh-----ls---fp---el-
--------------------------------d--r--------------
----isinpgtl-----------------vk-y-ph---dsisl---h--
-lhv-ltkpnqkk--d--es--rk-hefah--n--cktehf-ckylrp--
-----lcc-d--psgniqeesviv---------p-rs--lsagd------
--------d--lg-i---------kak----------ft-----------
-akk-----pfe---qfe-------grftt-vhdr----------sqvet
nkg--paaacivs-----lklfaagd-c--------pkafeltpdyevgq
lk-----------kpwt-------atgc---cvkaifaeg------gdlh
httvrsidy-svpc-------gl---a----n-ayahlfkgiqtkseggy
tykhv--vskrs----v-pkfh----vir----gmdtk--a-kk--gk--
--dg-v---pknida---sagel-ivglltal--asska-clhdd--fca
aq--hr-------------h--pclrvskyi-------------all---
vctlilsa---sf----ttgikhsdt---------ic--atecwan----
-----pnactv--vvpvranqaglrfkiihtkavavpgkrd----ehkc-
--------v--srd
