>B
--av-----------q-sdrvc----p-------tnlfkgt------laq
h-kehakgrrslfc-------------ncgvg------v--l------tc
-a--kd----n--ss-ive-vaega-----ref--gl----pqrp-dntg
qgsagnyrptqe-ardk---r-----------------------yqleta
kvr-kdylqvg--trsilfrsfek------v-dc-pm-tgghal------
qeqktyihttlptvqvhg---sgnr-eekgdkscdkseyp----------
-------a-fe---l--------sg--grvtknsghaglcksdv----kt
aka--qkrghmgclvilkkef---tce----q-------------nsgtl
stvtgl-tpalggik--------------------gt--cvdgv------
tgf-------lf--srsysvgk-eptk--------ryd--v-shvyl-lg
gylh----thfg-nfhqlkgsiyllnk-ic----nvsqargwnc-qqgac
------eqst---------------fn--l-ge---------tltvqlgg
ga--------e---------------a--tkvg-kla----------p--
pp---nvkv--a-------cfs-gnalv--------f---l--aaiiveg
--lg------a----------------------lw---irl-kf--ckk-
-------drgas-----rksq---------kh----a-----thmaptaf
sdd------kk---vksgwgkpgkfsqta---gse---ivkd--qkka-n
e----a---n-gqlq----e-hf------ehk----w-----agc-----
t--------------rhr--sk--------esphanvp--------s--g
-kt---i------g--gcia-----a--khgcpktd---cnvgptrrrq-
--------hheepkvth----
>node6
pskv--------necq-ndmici---a-------rnviksg------lfk
k-dqhps---qifcy---------terkc--s----aka----------a
-p---k----g-----isa-gdtgn-----rqf--gl----nlsk-ysne
q--------dae-dlrr---v-----------------------aqmk--
-lr-kdy--qgcekkcvl------rqk-rq---evem-keshtl------
n---yylhdtvstlkihg---svgv---hgdsac-ghlhidkg-----vg
llgl--vg-fe---ll-----agqa--sa---------lcypag----g-
-----------lvkgalrtkf----remrlie-------------gthal
hlvaan-katlgegk--------------------ea--ceaav------
tqf-------sit---------------------------gaani-r-ln
kelnlv--dqsg-afhvmvgaiylltdqlc------pd----dg-pqevc
------eest---------------fs--v-ly---------egnpplds
aaek------d---------------avdp----nalvvrqtke---s--
sp---kvgs--k-------iflckvkll---dhnsnf---w--ggdiaaa
--lg----ly-tdk--n-------afl-----elwna-lkg-pv--c-k-
-------gkgts-----kdck----------hvagag-----s--q---f
sdk------kk---aksgwdtaplft------------eikk--eqka-t
v----vfnih-prpk----q-tl------ekk----w-----gac-----
e--------------k-r--ayi-------dspvsypn--------rhig
-ka---iqgwr-ag-igal------aennnsc--yhmqkvkvppprhre-
--------mecg---qc----
>node10
--gie-----da---p-qkl------p-------vdlitgg------ss-
---qhpstri-tp-----------r-ik-sgn----etg--r---dqrtp
-p---qp--qg--pa-hqv-khvdq-----ksy--gl----aahp-ltae
haqigivsqd-elsvsi---y-----------------------sml---
---------al--r----------vvk-s-p-kk-dya---h--------
-----------------------al---hgq-ts-gsdqeaeyknertvg
---l--vv-sq------------------------------pavdknapv
pdqsvlkaah-------ssqp--qgcairlvgftqas--------qheal
tsh--------nt-ktpg-------s--------kin--p----------
-assk-meaqtigstq-------imln----------e--m-tqi-t-is
q--dfv--hpfga------------ag-lc------q------------a
--wrvmdseckfnyllwkaar--pffg--p-pynn----qldes-s----
rr--------r-----------adlfrggk--a-----------y-iqkl
tn---kvas--k-------mlichteve---dvdeaf---w--eapmvae
--lsr------gen--s----ar-qfl-----------------------
--------------------p---------klipgap-----t--g---l
gtk-gq---kd---sdhgwdsppnyk-gr---dnktqkstng--elkgvl
vhalda---h-eksl----p-qicsr--edhkvcnqw-----gaa-----
gn----prnphggakslr--hfanhsfthd-spist-----------elg
-ka----anpklvg-a-----------------------------lhre-
--------ipgk-kskc----
>F
--gle-----da---e-qkl------p-------aelitggdklgkfss-
---dhaasri-tp-----------r-vk-agp----reg--f---dpaka
ap---ipnlqgacpg-hhv-rhqah-----ssy--sl----gahp-ltae
hahigiaedg-qltvav---y-----------------------skl---
----------l--------------vk-s-p-ak-dya---h--------
-----------------------alt--hnq-ag-gpaeea--kgertvg
---l--vi-aq------------------------------kgvsknspv
pdesvlkash-------tsrp--qgca----giadac--------qne-v
ksh--------ns-kspa-------glgegwmkckin--p----------
-sspp-adaatigsaq-------imln----------s--v-dqa-t-al
e--gft--hpysa------------tg-lc------d------------k
-wwkimds---fnyllwkpar--pffg--h-tydd-qtrq-----k----
rk--------rlrdkeayisdhaglqksgk--et----------yatqkl
vn---kvas--k-------klichs-le---dvngsy---w--eapivae
--ldr------gek--eyvtsac-qfl-----------------------
--------------------p-ydvlvdaqkliagpp-----t--g---l
gaq-aq---ke---sdhgwagppnfk-ar---dsyvqnstngrkelsgvl
i-alda---f-eksl----p-rlsas--qehkvcsqw-----vqeatier
gn----frsphggvkslr--hfsspvf--e-spkst-----------elg
-ea----anlklvg-a-----------------------------llrd-
---------pnr-kmkc----
>node7
--av-----------q-hdmvcv---p-------snlirsa------lqk
r-dqhpggrhqifcy---------tdvkcgka----eta--r------ts
-p--ar----g--sp-isa-gdtgn-----rsf--gl----svss-ytte
qagagvaqqdke-dvtk---e-----------------------sqle--
-lr-kdy--vg--kkcvl------kvk-hqv-nc-qm-kaghgl------
n---nylhssvatlkvhg---avgv---hgdkac-gsqhhdks-----vg
vlgl--vg-fe---lf-----ngqg--sr---------lcvpav----as
aka--lrqaqsavkgalrkqf---tcearlve-------------daesl
htvaan-tptlndvk--------------------ns--cedav------
ahf-------migdtr-------iptn----------g--v-shi-m-la
kelnlv--dqfg-afhvmkggiyllts-lc------ae----en-qqsvc
------eqst---------------fs--i-my---------egnvplgg
aa--------d---------------avdilva-dll-----tg---n--
sp---kvga--t-------iffcyvkli---drnknf---w--gseilaa
--lg-------tdk--n----pv-sfl-----hlwnk-lka-pi--c-k-
-------gkgas-----qncq---------nhvagag-----s--e---f
sdk------kk---aksgwdkpplft-ar---ear---eikg--eeka-k
e----a---h-srsk----q-ti------ekk----w-----aac-----
a--------------rhr--nyi-------espvayvi--------kqlg
-ka---iqgwrlvg-ngal------aehnhgcrksh---skvppprrrq-
--------megglkvqc----
>node15
--pve-----dr---q-qdmvcv---p-------selirga------ggk
k-gqhaggrv-if-----------t-ik-qnp----eta--r------ts
-p--ar----g--pp-vsv-kdtgk-----ksy--gl----avds-ltte
qagvgvahqd-e-hsti---a-----------------------smla--
-lr-kdy--ag--k----------klk-hrg-nd-dm-kafhgl------
n---tflkasvldlkvhg---gvsl---hgqkac-gsehhdks-----gg
vlgl--vg-fe---lf-----rsag--sn---------lcvpav----pr
ade--lkaarravkg-lksqv--qtcevrlvs-------------eedsl
hsk-pt---tlnsvrt--sqsaeihg--------kaa--cedai------
ahf-------tigdtk-------ipln----------s--v-shi-t-ia
sslniv--hqyg-pfhlmegaiyllvg-lc------ae----enseqevc
------aqks---------------fg--a-my---------egnipwgg
ai--------n---------------aggvlva-----------y-snka
tn---kvgaggk-------tficytkli---dvdqsf---w--eseilad
--lg-------sdk--s----pr-sfl-----hvwhk-lqa-pi--c-k-
-------gt---f----qgcp---------khipgaa-----s--d---f
gak------kk---aksgwdkpplfk-ar---esk---evkg--eaka-e
e----a---h-eksm----s-ticgk--eekk----w-----gac-----
g------ska----knlr--dfv-------espity-----------tlg
-kaidgiagwrlva-n-----------------------------ahrq-
--------mpgglkiqcynnd
>E
--gid-----da---p-kkl------p-------vhvitga------ts-
---qhpsart-tp-----------r-ik-sgnsctiqaggls---aqrnp
-p---qp--sd--pglhqv-khtdh-----k----gl----aa------s
haevgvvaqp-elavnv---f-----------------------avl---
---------al--r----------vfk-t-p-kk-hyt---h--------
-----------------------al---tqm------dleahykeertig
---l--vi--h------------------------------atgdragpv
pg-tvliaan-------gaapkgqgsstrtvgftpanneegkgklrnqel
tsh--------ht-ktpg-------s--------nin--p----------
-stak-meaqtigstr-------i-------------d--m-iqv-k-ia
e--dfvlfhcfea------------dg-lc------q------------g
--wr----eyk--------er--pfft--p-pyra----nlees-d----
rr--------r-----------a---rads--a-----------y-vhrl
tn---kvas--k-------mlichiivdtln-------------fsmigk
--fgr------gqs--s----arkpfl-----------------------
--------------------p---------klvqg-------t--a---l
gtk-ga---kd---adhsfdkppnyn-gr---pdkkqkptnn--em----
vhsvng---h-qk-f----p-qvssr--gehkvcdn--------------
------prkphggskplrythfadhs---e-apv----------------
--------------------------------------------------
--------aegk-kgkt----
>H
--elesqmtyei---a-dsl---gndsnrdsasdcdlssna------ggk
nggkess-----f-------------v---ns----qat--klwm---vp
-pv--d----g--ap-qagg----------------lqaffgaqp-lnee
kg-sgtveqn-elngiv----------------------------m-y--
-----sh--pn--p----------dvk-pckfrk-efs---hyl------
h---n-----------hv---gisl---ag-tks-ssnqqeaskv-----
------ltsfrstylaglaaeqsntacat---------lcv-sv----pi
ahe--lksmh-------anqp--q-crnrlpg--------------hehv
iap-ea---ylrtitt--phdlgfhs--------kii--c----------
-vtqkpvehqti-----------vfld----------dsgt-aqi-vpit
w--dfc--hpyg-sfpllnsgvyfllf-lc------g------------c
------epaa-------k-ggtasffgesd-my-a----qveepng----
kv--------a-----------------av--a-----------y-kkkr
ap---kvas--k-------tftsytkvg---dldnnfggrwspqtelllp
-slgs------gdt--n----gr-qf--ggrgqawqm-lrl-kvi-s-ky
antpvvsdp---y-ggkegcsq--------kaisgsypqd--v--k---y
gctdth---kn---sdgrwnsapkfk-vrsesskm---t-------ki-l
---------k-h---------efcvrpe--d--irtw-----vaa-----
aavkal-----------r--dfles------itigy-----------rlg
fks----pglklkaia-----------------------------thpml
savalnlkvlgpikdsgdevk
>node14
--aie-----dr---q-qkl------p-------selitgg------ggk
k-gqhastri-vf-----------k-ik-snp----etg--r------tp
-p--aq----g--ps-hpv-ketek-----ksy--gl----aahs-ltae
haevgiveqd-elkgtv---y-----------------------smlp--
-----dy--ag--r----------qvk-rrs-ek-dfa---hgl------
r---t-----------hg---gisl---hgqatc-gsdheeeskheptvg
---l--vt-fq---ff-----rsag--an---------lcvptv----pi
ade--lkath-------asqp--qtcavrlvg-------------ehdal
hsp-aa---ylntart--kqevefht--------kvd--c----------
-htkk-veaqtigntq-------iyln----------e--v-tqi-t-is
r--div--hpyg-pfhlmdggiyllag-lc------a------------c
------epns-------k-gs--pffg--a-myna----qldesst----
ri--------r-----------adlfrggv--a-----------y-iqka
ts---kvas--k-------tficytnvn---dvneaf---w--ekemlad
--lgr------gdn--s----gr-qfl-----qawhk-lqv-vv--c-k-
-------gt---f----qgcp---------knipgaa-----p--n---f
gtk-gh---kk---tdsgwdkppnfk-ar---ddk---avkg--eaka-l
a----t---h-aksl----p-qfcgr--eehkvcraw-----gaa-----
gn----aska----kslr--dfmdhvyshe-spisy-----------qlg
-ka----aglklvg-a-----------------------------ahre-
--------llgglksqcyead
>node13
--aie-----dr---q-dkl---gcmt-------sdlvsaa------ggk
ngglqss-----f-------------v---np----eag--klwm---pp
-pvlae----g--pp-qag-k---k-----kay--el----gaqt-lsqe
qgeagtveqs-elkgiv----------------------------mly--
-----gy--ag--r----------evk-pcs-ek-dft---hvl------
h---t-----------hi---gisl---tg-ttc-gsnhqeeskqeptvg
---l--vt-frkaylfaladlpsag--an---------lcvpsv----pi
ane--lkath-------asqp--qscmnrlpg--------------herl
iap-da---yldtait--khdlefht--------kii--c----------
-itkk-iehqti-----------ifld----------esgt-aqi-v-it
r--dyc--hpyg-tfpllsggvylllf-lc------g------------c
------epgs-------n-ggispffg--a-my-a----qvdepst----
kv--------k---------------rgat--a-----------y-smkr
sp---kvas--k-------tftcytnvg---dldddfggrw--elelllp
-tvgs------gds--s----sr-qflegasgqawdk-lrv-tvi-c-k-
-------ga---y-nqregcs---------knlsgta-----v--q---y
gnnath---kk---tdarwndppnfk-vrggsadk---kika--dvka-l
a----s---k-aksl----p-efcvr--eed--araw-----vat-----
vnakgv-----------r--dfadkvvtnq-stisy-----------rmg
-ks----aglklkg-a-----------------------------thkv-
--------llgglkkqsddvk
>C
pkka--------eesq-pdmict---c-------rgvlrte------lfk
k-dqh-----epfccvkapdykrltekkt--r----awa----------q
-t---s----g-----fga-ddtgn-----rqftggl----klps-hsnq
q--------g-e-dlvr---v-----------------------aqmd--
-vs-kdy--egcqkkavl------vlk-re---evkm-khdqvt------
n------hdtvsilkthg---nv-l---haesac-ahlhvnrg-----ng
ilgi--vn-fg---kq-----sggg--cs---------lcypag----g-
-----------lvkgk----f----rqmalv-----------------al
qldas-----------------------------------etlv------
tef-------sit---------------------------gpadi-r-ln
kelhlv--dqaa-kfhvvv-----------------pd----df-pqav-
-------------------------fs--v-ly---------einhplep
gaednllrawd---------------tldp----nalvgrveke---d--
spegckagy--k-------fficpvkll---nhnssf---w--gggvsag
--lg----ly-tdkpfs-------afl-----elwnv-lkggpv--c-k-
-------grgtg-----ksak----------hvsgag-----a--e---f
gek------kkthneksgsenaplft------------evdk--deks-t
i----vfsiqtgrp-----q-al------e-k----w-----g-c-----
g--------------k-r--ayv-------idavsypn--------rnig
-a-----dgwr-qs-igal------advnkpc--fqmqklpvpppkhrd-
--------veca---rv----
>node3
--av-----------q-nntvcv---p-------ttlfkst------ler
r-dqhpkgrhrsfc-------------kcgka----dta--l------ts
-a--kn----k--ss-isa-gdegs-----rsf--gl----smsr-dnnd
qggaglsrqdke-artk---q-----------------------aqlena
kvr-kdy--vg--skgll------q-q-hev-dc-pm-kgghal------
hedktylhdtaptvkmhg---avnr-eekgdktcdgsqhpdqk-----kg
ilsl--ig-fe---lf-----spsg--sr---------lcvnsv----ks
aka--qksahvgvngalkkef---tce----q-------------naatl
gtvtas-tpalgdik--------------------ag--cvdgv------
trf-------migdtr-------eptk--------kyg--v-shv-l-lg
qnlh----dhfg-afhqlkgsiyllts-ic------ae----es-qqtvc
------dqtt---------------fs--i-sa---------sltvalgg
aa--------d---------------avdikvg-klm-----kg---p--
ap---nvgv--a-------cftcyntlv--------f---w--gaeilaa
--lg-------adk--n----p----l-----qlw---lka-kf--ckk-
-------grgas-----rkcq---------nh----g-----thmepnaf
sdn------rk---vksgwgkpgkfsqar---aar---ivkd--ekka-e
e----a---n-sqsk----e-hf------ekk----w-----agc-----
t--------------rhr--ty--------esphaavi--------s--g
-ka---i------g--galak----adqnhgcrkpd---cnvppsrrrq-
--------heegvkvqc----
>D
rtdv--------deaq-n-mvci---a-------sypiksg------lfk
k-elhss---kifcy---------verkc--s----vka----------e
-----k----s-----lng-gdganiimggkqf--am----nlsksnade
q--------fae-qqrrqfwhiasalqgdgfe------------sqmk--
-lrvkny--dgcnkkcvl------rqk-rq--------kkshvl------
n---fylhd--------------------gdna---hlhigkg-----vg
llgl--ag-fe---hl-----ggqa--ta---------lcypak----g-
-----------vv-galrtkf----remrlve-------------sshnl
hlidan-qqtlasgk--------------------etvgcqsavdiaake
tqf-------sia---------------------------epaka-r-ls
keyai----qaa-aihvv--aiyllkdqlc------ph----ag-pqeic
------aenp---------------fg--valy---------patppras
apaq------e---------------dvdp----halvmrpike---g--
sp---rlgg--k-------i------il---efntnf---w--vgdiaag
--lg----ly-tdk--g-------pfl-----elwidtlka-mi-kc-k-
-------gsgsc-----tgck----------hvagys-----s--i---f
nnq------kk---vkcgwdtaa---------------eikk--dqka-s
i----vfnih-prpk----k-tl------esk----wklvrydac-----
e--------------k-r---fi-------elavtflgtvepdiwarhig
-kn---iqgwr-gg-vgal------addn--------qkvkvepp--re-
--------kgca---dc----
>G
--nie-----dr---qgdrl---ghkv-------selv-gi------ggk
ngglqss-----f-------------v---np----ega--qllm---pp
-cslte----s--sp-qdg-k---k-----nay--el----gaql-ltde
qgaagtvees-dlkgik----------------------------lif--
-----dy--tg--r----------e-k-acg-d----------lesiqke
h---a-----------aicqqgitv---tt-tsc-gmtgqeiskqgpavg
---l--vt-f---ylveyanvptpk--tk---------qcvlav----cv
pvh--lrlah-------asqe--qec---l-g--------------herl
iag-eae--yletavt--kqeanlht--------kfv--m----------
-qtkk-ietqtv-----------t-id----------qest-asi-v-ft
d--dyv--qpyt-sfpllsggvylllf-vcfltq--g------------c
t-----eega-------t-ndqspffg--s-mf-aa---mvsdast----
kv--------k---------------ngaa--m-----------y-pmkr
np---gpak--k----------cytnsg---kaedefggrw--elellkp
tsvgavah---gds--s----ap-pflegasgqswdk-lrv-tvi-c-k-
-------gq---yinqksgts---------kkltata-----v--e---y
senathgaekk---yqkrwdnapdfk-vkggaadk---kmea--dvka-m
s----s---k-aksllkmsp-efclr--rdd--vraw-----aat-----
vnptgk-----------h--tfakkgvt-e-sthny-----------kms
-ks----ggqgfna-a-----------------------------thka-
--------llgslkkqsaelk
>A
---------------q-nktaiv---q-------avlfsgs------aei
r-eqdpkg--ggpc-------------kvlke----dta--l------ts
-a--kn-------ps-ait-gqhgs-----ktf--gf---------gnle
qggvsl----ka-pyaa---k-----------sikcqcrvkdptpslena
rvs-rty--cg--v--ll------q-er-el-dr-pm-kaahgl------
hqektylhdmvptikmhg---ai-k-eekgdkssagkqypdvk-----kg
vlslafi--------------appa--sr---------fcpm-g----is
akg--aktghvgasgalkkev---tcs----d-------------sgatl
aaviag-----g--k--------------------ag--cvqgv------
tkf-------eighik------westkgqadnpgnkyg--v-shv-l-ls
qefh----shyg-acdfvkgclyvlks-la------ae----as-qetvc
------qqtt---------------fs--s-sa---------vvaialgg
as--------n---------------aveikvg-kvs-----kg---p--
ap---nvgn--adhpyvntcfecygvsv--------i---w--seqllag
--lg-------ai---y----p----l-----alw---lps-sf--ck--
------------------kcq---------np----g---agshmepsaf
sdn------sr---tetgwgkpqkfnrap---ktr---iika--ekqa-a
q----a---n-geak----etqf------qkk----w-----agc-----
s--------------rhn--tf--------gdahgavv--------s--g
-tt---i------q--talisqlvfadkddgchkpd---csvpssrrrq-
--------peagvklq-----
