>node14
tnkgagr----h-------e----g--kp-----------r-a----s--
--rth----------k---a-d-ankg----i--n---g---------l-
kf--steg---d-----l---t-gky----asv---snktnkl---d---
kgsk-h--phli-ppe-----------wyfsqhfnngldilamnvga---
-c---kv------np-gkd-ckhlt-yedteilsl-y--gngcaaefd--
q-lrn-gt-------i--------gtaevkvlgf----------lltykk
ikteved-------fs--k-kd-vh--aps------------krdtp---
lsfi-hs---------dl----pgqpav---f--mvpnr-neftg----n
ck----h------vgh---ltksg-r-d---yt-----------------
q-aef--s-hek---------qsm-skkaadan-----s--gtks--aiv
--qlt-i--sil-gpe----pv---gl--------plv-------vaas-
-----aes----------l--gtdtrsdgte----askcsd---le----
--l---------ckcq---vlidgp---dpkfgyksh----------tt-
-------arnc-ld---------kslky-----ksd----lgr---s---
---n---------a-aalapk---ffsk---d-------tnreedkv-pk
--s-vlrc--se---ad----tk-agavkvs----------hkla-----
v-y------rg--avfge-c-arvsecsk-h-----g-ivvavavc----
-taftlpmpglrvspgdqpte--------pv-----nkp------eyait
t---langpds-pkev--sm-------kk-k--------qg-f--kfagp
l--------sdg-----------lfkv---ycmid-------g-----qg
nkpedkyryfdh-----s--nk-----ef-------akfgtvd-------
----------g-------sltlleitq-----lg----qyfgfgamk---
-lf---ii
>F
tnkgtgw----h-------e----g--kpk----------p---------
----k------anamk---s-e-sgag----l--d---a---------l-
kf--prag---q-----l---t-gkf----gks---akkgnkd---gk-e
tgip-n--palv-gp---------------sqhfekdieglemptet---
-c---kv------kk-grd-skdls-yk-----sa-y--gngcsaeyg--
yrvkg-gt-------a--------atfqv----l----------lpdykk
vqadaed-------fv--l-ha-v------a--epgavilhakkete---
lsak---------------------aa-----------r-knfhg----g
cg----rvighgvlgq---lptgg-ithqrccp-----------------
v-sef--r-----------------qkklgtak---------------v-
----t-a--qvl-psefpkaav---gv--------k------------s-
-----s-p----------v--gtptlkqgtg-------qad-sglelacg
eql---------cp------lldvp---spkcnykga----------gt-
--alitlvkdc-i-------------q--------h----lgr---s---
---n---------a-evllpk---lvrk---p-------shretdnvspk
ets-ilkc--se---ad----ak-gg----k----------kfla-----
aiy------eg--asyge-c--kvqdcdd-q-----g-i--pasis----
-tgtalpkagla--p----ts--------pv-----dat------eyavi
t---lengpds-ppea--cm-------krfl--------rg-yqavip--
-------------------------------llie-------grnggtln
qkgnetyqyfvp------pvrhqvcvqd---------vast---------
--------------------gnlafnq-----ya----ay-afkpml--k
vii---ri
>G
gtssggrnv--h-------e----g--lp-----------r-sqirvs--
--saqgrklle----radag-----ag----v--t----nvny---gvl-
rf--pte----------l---t-pny----enn---tekankl---d---
ldc--e--pn-----------------wystihfsagrdnlaqgspe---
-g---e--------e-gkd-ckhls-tegsekisg---eafkcaaefd--
q-lqp-ga-------t--------kvallkvlaf----------lltyd-
-madre--------fe--syvc-eh--epn------------krdtp---
ptfdeqs---------ev----pg-atn---f--mvfgraanttgyyqvq
ct----h------egr---fkqpg-r-d---ya-----------------
s-asf--s-qtl---------hsm-gkmggpgn-----if----------
-------------spe----al---gq--------hmv-------aagkq
k---aaaa----------l--agdl----------qc-------------
---------------------ids----hsqfgfspk----------na-
-------a--s-ln---------iplkq-----kge----lqr---h---
---a--------------------ffyk---g-------tddkpgkl-vk
--c-slrc--sdtypi-----etitnadkvg----------n--t-----
p-ytlmlasng--g--------rvsacsk-h-----g-ivqavavc----
-lpftldvdglllgpadaptatggtqscnav-----lkpivkk-aeyavt
aknstakgtptl---t--gl----------------------f--kysgf
l--------kgg-----------l------rnmck-------g-----gg
hiaesdyrlfdh-----g--kk-----dy-------rkggaek-------
----------g-------tlnvlgvan-----mg----erfgfnlqr---
-lf---ri
>E
ggkvggr----n-------q----g--kkh----------r-k----kv-
--kak----------k---a-e-ankgaagglv-s---v---------lg
kw--tkgg---d-----i---y-gky----gav---sksggke---dgre
kssd-k--pnli-ap---------------gqhlnngvehla--------
------------------y-crvln-yk-----kl-y--gdgkakeyt--
vhlkk-at-------m--------vafqvkllal----------llahkk
tntdide-------ys--m-ne-vhkiaasslcegssv---arsssq---
lgfi-yi---------ga----pghptv---l--ylpna-kkycg----t
cs----n------vgq-----kga-vtetaccp-----------------
heaev--r-----------------fkrlqssk-----s--g-----ai-
----t-n--qvl-avellkapi---sl--------if-----------g-
-----s-pahiaaaglttvkigtaalkegte----grrsag---ldlgc-
qev---------cksqvpq--leip---dqkyg---h----------gn-
-------vtny-ad---------kalk--------n----fgr---g---
---d---------a-ar-------lirq---p-------thkeshgv-pk
tetgvlkcivke---ae----ae-ggalnvd----------hkma-----
a-y------rg--sglge-c-srndncdk-mtkg----------------
-----lpmaglkrgqanepan--------pv-----dk--------hali
s---lggghdn-pkgd--sv--------r-l--------qg--lakfpgp
l------------------------ki---yllve-------gk----fg
akgqekyryfnr-----krivksigkkgf-------dpfte---------
--------------------gfisice-----yapvqgayfgfkamldli
afi---ri
>node6
ttgiggt----h-------r----pslnt-----------rgh----a--
--t--------------------dgka----i--sdlda---------l-
l---avyg--------qsgk-e-d--slvlsgvinsanegtklrg-----
-sgg-h--l--d-ppg-----------fyapqrdd---gvleia---php
qc--rkvl-psv-q---mh-ckql--------l-l-y--gkvsaidla--
k-vrn-kg-------vhg----ll------pqay----------gl----
v---ars-----vtpehap-he-kq---pd------------kev-d--a
l-mv--sg-------ih--------kgv---f--vd----ddfas----t
ck----h------vth---dseag-k-n---fvsk---akntyli--rtk
h-itl-er-qqk---iil---k---------askkpmhi-lnsktdatva
afslg-ikrwfmidpn----gf---slaet--cmwsilghatcaefntq-
-----gqr----------t--gsatkvq-vr-------------------
--------ackyakgr---nledgp---epm----------------sv-
-------gqkppfc---------dalkc-----ased---lakgglldgv
fttg---------nk----lr-ch-------f-------kkvde-se-s-
----------y----------kk-gtiatvk-vwsdpvavdnrta-----
----------------gh-s-tsathctr-q-----g-avmcssdcdpr-
qeantlakkglq-------------------fnlvknea------hygga
-------gq-----ki--ds----ryeda-kk------t-----------
d---------im-----------lfgt---yv-re-------g-------
-----------hsg---a--ta-----dy---------fgnvdrfvl-dv
vlken----is-------am------------l--------ay-------
--------
>node10
tnkgagr----h-------e----g--kpr----------r-s----q--
--rsk----------k---s-e-ankg----l--d---v---------l-
kf--skag---d-----i---t-gky----gtv---skksnkd---dkke
kgsr-k--psli-pp---------------sqhfdngvevlamavga---
-c---kv------ka-grd-ckhls-ye-----sf-y--gngcaaeyg--
vrlkg-gt-------i--------ltfqvrllgl----------lldykk
vktdaed-------fs--m-na-vhkiapnn--egssvvvqarsetq---
lgfi-fi---------sl----pghstv---i--mipdr-kefrg----s
cd----n------vgq---lpkga-itntkccp-----------------
h-sef--s-----------------skklqtan-----s--g-----ai-
----t-s--qvl-pveflkapv---sl--------kl-----------s-
-----s-p----------v--gtstlkegte----asrsad---lelacg
eev---------ckcq---tlldgp---epkygykah----------gn-
-------vknc-ld---------kalk--------d----lgr---s---
---n---------a-aslvpk---lirk---p-------thretdsv-pk
ves-ilkc--se---ae----ak-ggslnvs----------hkla-----
a-y------rg--aayge-c-arvedcdk-q-----g-i--asavg----
-tgftlpmaglkagpgdqptn--------pv-----dkp------eyali
t---lengpds-psda--am-------rr-l--------qg-flavfpgp
l------------------------ki---ylmie-------gr----fg
qkgedkyryfdr-----rpvikkickqdf-------dtfst---------
--------------------gfldisq-----ya----ayfgfkpml--k
ali---ri
>node3
aagvsqa----h-------k----ssisk-----------rgd----a--
--a--------------------ttka----i-tqmiqg---------l-
k---dvdgqaldaq-sqs---d-ekyclilnnv---snagtklrg-----
-fgv-kgvp--k-ppngldhvkapegkf----hdd---kvlqia---php
dckkkkvl--vqle---egscrrag-yg--eilsm-y--gnvcakdla--
k-lrs-kn-------iig----llgla---pqaf----------pla--d
v---akd-----atyehpk-ha-tq---ha------------kna-i--a
lrli-hgg-------tqlffqa---pgm---f--sd----sdfat----t
ck----h------iah---drqads--------s--------fl-----a
t-vml-qt-kqk---via---q---------aetqhmqf--dtktest-y
--gla-ikrslp-dpn----gvglhsl--------tvl-------fs---
------di----------t--g------str-------------------
---pagrygclyphc------ldap---vpl----------------kt-
-------dhdpgmi---------vsmic-----aseq---largnlmes-
-cts---------kk----pr-cf-------a-------asvgd----p-
----------l----------kk-gavgk---lw-dplaadmktsetiqt
n-----------g--sg--s-trish------------sctcadqc----
-eahklakkglr--e-----k------------qvkpe-------syyga
-------gt-----gi--dg----nyqtr-kkkyniecthg-f--nf-dp
n---------ae-----------lfsl---nclad-------g-------
-----------hkg---t--kp-----dy-------qkfkdverldllgf
vleed----ig-------sis-----s-----lg----effty-------
--------
>A
gagvgka--vta-------k----sgvsk-----------rgd----l-m
laa--------------------stkv----n-lqakhg---------l-
k---dvdgssldalpsq---------------v---khggsklsg-----
-fav-k-ap--kvppsfl---kapsgkl----hdd---evlhia---p--
-ckkkkv----------hggcwmtg-yg--eilsm-y--gnvcakdle--
k-lra-kn-------iis----ltgla---pqpl----------sls--s
v---akdkkeeeasyea-k-qpaaq---ha------------kna-ivya
ikli-hagagkstkwtqlffha---pgm---f--ae----sefat----t
ckavrtf------tae---eng----------------------------
t-imp-qt-ttk---fipkaqq---------sepqfmef--dtstast-c
--pla-ikrtlp-eph----alglhsl--------gvl-------fa---
------ii----------t--s------tsp-------------------
---ptarysclyphc------ltap---lpl----------------kt-
-------spg--vw---------vdmvc-----tneq---lakdnamed-
-gts---------st----pr-cs-------skvaeylmaavtd----p-
----------l------dtieek-geagk----w-dpisadmkagdtiat
---------------sg--ml---s--------------ciaandc----
-eahkvakdalr--q-----r------------qvppe-------iyyga
-------gt-----gi--dg----nyqtr-kkkyqi-ctha-f--vf-dp
n---------aryltswprsskkl--------lpe---------------
--------------------kf-----qy-------qkfrdverldilgy
mlqqdeakvigcnadlpdsig-----g-----lg----dffvl-------
--------
>B
gagvtea----h-------kkgpfsgilq-----------rge----t--
--a--------------------atk-----i-tgliqg---------i-
p---gldgegldaq-kqs---d-gkyclvlngv---snagtklrg-----
-f----gvp--t-ppn-lehvkappgs-----hdd---kavkta---php
dcdkkkvl--lqlq---epcchrpakgg--silgmty--gnvcakdla--
k-lrs-ka-------ivg----vlgit---pvsl----------------
-----------------pr-ha-mq---hp------------ksa-f--l
lrli-hgg-------tqlyfva---psm---f--sd----meiat----t
ck----h------fkh---grksds--------s--------il-----s
v-vil-gt-kkk---vwg---q---------agsqvmqf--ntktvsp-f
---en-iprplp-aph----gvelhsl--------sil-------f----
-------i----------n--g------dtk-------------------
---ptg--------c------lnghsayapl------vlkvmfvfnfqc-
-------nhdpgfn---------vsmicwaadsqsehrialtradltds-
-cts---------rk----pr-cf-------a-------eklge------
----------------------k-ckv------w-seraadmktsetvqs
a-----------g--gg--s-arvtr-----------atctckdqc----
-eacklgkkgip--q-----k------------kvtpe-------syyg-
--------l-----gyttdglglhnf-----kkytiacthstf--hf--p
d---------ee-----------lfhl---sclid--kihlfg-------
-----------hng---k--np-----efftvwasikkfkgie-lellsf
vledd----iv-------svs-----p-----ld-----yiky-------
--------
>node15
tngasgr----h-------e----psikt-----------rgg----d--
--smh----------k---g-s-eakg----i--n---g---------l-
k---sveg---dlr--ak---t-gkyrltlgsv---anktnklrsrd---
ksgn-h--p--k-ppn-----------fyfpqhld---nilaiq---pnt
ec---kv------n---mn-ckrlt-yg--eilsl-y--gnicagefp--
t-vrn-gs-------i--------gta---plgf----------llafkg
irveaed-------fsqpk-qe-kh---ps------------krdls---
lqii-heg-------tdl----p--pgv---f--lv----neftg----n
ck----h------vgh---ltkag-r-d---yt-----------------
q-ael-dr-her----tl---q---straqnankehmqs--gtkttetvi
--qlt-ikrwsl-npd----gv---gl--------div-------haaa-
-----adr----------h--gtatrsdgtq-------------------
--------gcnfakcq---klvdap---epmlgykss----------tt-
-------ahnc-le---------vamty-----ksa----mgrgnvedg-
-stg---------t-aslapk---yfsg---d-------tkpdddsv-p-
----------ye---gd----tk-aavvkikevw-dpvyvderlk-----
e--------re--avfgd-c-arvphcsr-h-----g-tvmsagac----
-eahtlampglr-sp-----e--------pigdplknkp------qyaet
t---iangtgp-skgv--dg-------rr-kk------tqg-f--kf-dp
f--------tng-----------lfei---yclid-------g-------
-----------h-----s--ns-----dy-------hkfgnvd-------
----------g-------ams-----p-----lg----qffgygakk---
-lf---il
>H
sekgagp----hegpvtc-k----e--lp-----------r-ehirta--
--sdqgkklld----kteagad-gnkg----i--a---ddvhyqlggvl-
kfi-psks---d-----m---t-gdy----csv---vdkadkl---d---
ldt--q--pe-----------------wyptlhfkdahdnla---ge---
-g---nt------kecgkd---nln-yegseklsg-yavtfkcaaafdev
r-lnvdgn-------t--------vtelgrllkf----------kltyka
lksemed-------fd--k-ed-eh--sst------------krdcp---
lsfn-ks---------------------------mvankaskasgyyevv
cr----h------cgrtak-kkpd-r-n---cn-----------------
g-eef--gphtk---------hgmd--mggdgn-----tv----------
-------------gra----el---gq--------qvm-------vtsrp
keil-----------------atsg------dqekac----h--------
------------s--------iqiy----aefdygsa----------nrs
mk-----a--r-ln---------inlkq-----rse----mgr---p---
---h---------l-paleaac--ffse---e-------taqdgdky-pd
--c-vlpc--td---a-----aki--alkvg----------dkle-----
---------sg--alw-e-c-eritacsrwh-----g-livsvgvc----
-aaftlaikgirlppaeapve--------aa-----drpflpkkaethas
t---aaqaskhl---v--am-------r-----------vv-f--kypgp
qgkghpndragg-----------lfki---yslik-------d-----gg
hsvssgynlfeh-------------------------kygtid-------
----------g-------aldvlevpl----------------allk---
-lfdnltv
>node7
tngvsga----h-------k----psidt-----------rge----a--
--t--------------------aaka----i--qmlqg---------l-
k---svdg---dlq--qs---e-ekyclvlsgv---snegtklrg-----
-sgg-h--p--k-ppn-----------fyfpqhdd---nvlqia---pht
qcktkkvl--avsq---mn-ckrlt-yg--eilsl-y--gnvcagdla--
k-vrn-ks-------ivg----llgka---pqtf----------lla--d
i---akd-----vtyehpk-he-kq---ps------------kka-s--a
lqlv-hgg-------thl----p--pgi---f--ld----sefas----n
ck----h------vgh---dseag-r-n---yts-----snpfl-----k
q-itl-dr-qqk---iil---q---------askkhmqf--nsktkatva
--glt-ikrwfl-dpn----gi---sl--------tvl-------fsaa-
-----gdr----------s--gsatkahgtr-------------------
--------gckypkcr---hlvdap---epm----------------dt-
-------nhnpgli---------valtc-----asek---largglldg-
-stg---------nk----pr-cf-------n-------tkvdddse-p-
----------y----------kk-gtvtkik-vw-dplavderta-----
d--------keiv--fgh-s-arvthcfr-q-----g-tvmcagdc----
-eahtlakkglr--p-----a--------pmfnqvknea------hyfga
-------gt-----gi--dg----hyqnr-kk------thg-f--kf-dp
h---------ag-----------lfai---yclrd-------g-------
-----------htg---s--kp-----dy-------hrfgnvdrlvllgv
vlked----ig-------ams-----s-----lg----qffay-------
--------
>node13
ankgagr----h-------e----g--lp-----------r-nhirts--
--stqgkklld----radag-d-gnkg----i--t---gnvny---gml-
kf--ptea---d-----l---t-gdy----esv---sdkankl---d---
lds--e--pn-----------------wyssvhfsdghdnlalgsge---
-g---nt------ae-gkd-ckhlt-yegsdklsg-yvetfkcaaefd--
q-lkv-gt-------t--------qtalvkvlsf----------lltyka
lktered-------fe--k-td-eh--apn------------krdtp---
ltfneqs---------el----pg-pna---f--mvpnraadstgyyqvv
ck----h------egr---ikkpg-r-d---ya-----------------
e-aef--g-htk---------hgm-skmggdgn-----tf----------
-------------gpe----el---gl--------hvv-------vastq
k---aaea----------l--aadg----------ac-------------
------------c--------iees---hpqfgygpk----------nt-
-------a--r-ld---------islkq-----kae----lgr---h---
---h---------a-aalgtac--ffsk---d-------tnqegdkf-pk
--c-vlrc--td---a-----aritgaekig----------dkla-----
p-y------sg--avfge-c-erisacsk-h-----g-ivvavavc----
-vaftlamdglrlspadepte--------tv-----hrpfiqk-aeyavt
t---tangsvsl---v--gm-------r-----------kg-f--kypgp
l--------sgg-----------lfkv---ysmik-------g-----gg
hnaepkyrlfdh-----g--kk-----ef-------akfgtid-------
----------g-------slnvlevah-----lg----eyfgyglmk---
-lf---ii
>D
trgcggs----n------sr----palni-----------rgq----s--
------------------------gka----m--sdlep---------i-
t--lpayg--------fsgk-e-e--svll---anqphdsssiwg-----
-tge-h--l--e-prg-----------fyap----------eia---phv
ac--rkvlqpev-e---mh-ckql--------l-l-y--srasaidla--
k-irr-kg-------vrgtgsvll------peayfqg-------nl----
v---aks-----atpeheq-hq-sq---pg------------aev-d--s
l-k----t-------ah--------ktv---s--vd----ddfac----t
cs----f------vaq---ksaav-k-n---fvkkpndanntyiivldtk
q-ia--eh-qqk---viv---r---------gskkem-i-lddktdlsve
sfslgyskkwfmidpd----vy---ilaek--cm--i---aacar--ch-
-----ger----------e--gsctnvh-vk-------------------
--------eckfskgr---dldggp---dpm----------------ql-
-------gqkp-----------------------tyd---lamgglfdg-
ftsgptiatkagaik----lr-cr----aprf-------qkvee-sg---
------------------------gqvgsgt-vrsepvsiahpsg-----
----------------gh-g-ttaahctr-q---grg-tvkctddcepkp
--knvlskk--r-------------------fkllkgdg------hvgvp
-------kq-----dt--dg----rfeda-ke------t-----------
n---------tm-----------lfatarsfv-ny-------g-------
-----------hpg---p--t------------------------vl-np
vlken----is-------nl------------r--------d--------
--------
>C
stglggt----y-------r----pgvdt-npkellfaiargh----a--
--t-------------------kdkaa----i--gdl-t---------q-
q---avyg--------gsgkppgn--klmlsklikstddatgl-g-----
-sgglh--l--d--pg-----------ffttqrdd---gvleia---rmp
qc-----l-psv-g---lq-ckll--------l-l-v--skstaineg--
k-vrn-kggnqgncnihg----ll------pqay---gysvhrwgl----
i---ars---------hap-he-kq---pd------------knt-d--s
l-mv--sl-------if--------kggfgclvdvd----defat----s
cr----h------vth---dt-pg-k-s---yvsk---pkhtsmi--sgk
q-itlkqr-rqksgdviv---k---------svtrpm----qgkndtt--
afslg-itkwfmvgsk----df---klaetvpclwkilrhatc-nfn---
------kr----------k--ksatkvq-vr-------------------
--------ackfaaaa---slevgp---dtm----------------k--
--------qkh--cspkhwmrgegilkc-----ssem---laksglpdge
fkag---------nk----lr-ch-------f-------kkaed-se-s-
----------y----------kt-gtiptvf-vw-----avnrta-----
----------------kygl-tsatsctr-e-----g-pgmcsadcqpk-
qernrlakkslq-------------------ftlvkkes------nygsa
-------me-----al--qk----ryeqp-rd------p-----------
e---------im-----------klgt---sq-rdft-----g-------
-----------qqgevkp--tp-----dy---------fgsvgrfll-ea
vlkaa----is-------lf-------vggkvi--------iy-------
--------
