>D
-----------ncc-pnpmyn--saqqch--vqtdg--akv--------f
---fgtk------kvela--h----dgk-l-g--atyqa------d----
-------------kp-y---y-----------------------sqavsp
-kk-kf---agteshw------gdnr---dha---gfkiqrmq-srssgk
fl-------nrkksf----g-keegn----gd--t-------rtldg---
------lrcg--d-----lwv-a-------anw-hvreeqarfa---t--
edgftalrmsngaa--ggkvapg-vp-------a-knk-----pler-v-
-----------k-c------htvkaescsgpry----------------f
rg---lsa----gs-rvy-------------lthavgvp-------tgd-
-lgltknfe-ead-----------------vg-q---h------at-s--
-y--kpitkpalf-lygh-qvl--ml-----lqs----ls----------
-----------------ci---------------------dssv---k-f
l-s------gspa--------------gl-vf-lahptehi---------
---------------yvpi--ar-gd---qeg--------------tlif
gvglk--kt----------------------ppg-liiq-q-w----g--
-----tn----y-----i---l---yfkvlk----l--rn-----qhkep
dvfdsk-----ls----rir-----hh----id-t-------ve--fhvv
-----st--e-----------------isng---a--f--------lpc-
--aps-ansspkcnicv----------lnfda------n----l---r--
v--ytg-------------ltc------c-lqgpgatldpkgviiggksa
ldmyrdeafchpnh--ekdalvq-crtnak--vnrsp---a-a---ln
>G
-----------tycereghfmkl---a----edgksp-hrs--------c
pkkvetd------vthla--d-------------nnyvsnra---r----
-------------kaas---giat--gkgalt---------cknnl-hif
-t--mg---eglenlwaaiavmgaat--knlte----v----i-vhkkng
esgwevfi-nrpftf----g-------seifslpi-------kp-ve---
------lk-h--e-----vaa-t-------vsw-qvptgnmrfsag-psc
pnsggglhgh-gane-f-ah--t-le-------dd-----------pyvh
vaslyan---ynivgpr--yn--------patfqkkphkirdasvp---s
yv---lpkenveq---------------------e---g-------yepa
ssk--f--svpsgc-----------pp--f----p--sngcklpndhg--
-tsqqrlgkci---fscg-qapsial-tsdsv-----------c-vh---
-----yiqms--------viv--r------k-----eal---ddt--egf
vsd------kpnpnnr----sp-----ergey------------------
----------g------ra--sragqngfaqamv-----ng-n--galsy
reg------hqck------kh----------------kl-k-htgpeq--
qksvdlpsfk-f--g------laf-rfklwk----lgd--vsivh-----
---dgilgkpvsc----rlrtkllesm----cdaklsdcrklat--fykv
-----ga--dhktlksfgavqcdgalighth---g--y--------vyv-
--hkp-td--------lsqcgsllgti----d------t----lrpic--
--ppdm-------------fmplpekvgc---stsmvl------------
--------wrn---kg--------vrgdkk--gkn-k---v-a---an
>B
-----------ptc-pep------aakcv-----ng-krqv----arla-
-------------vrlli---------pklypddatwka---dftd----
-------------da-lkeqy-----------------------ea-isl
akerkf---sst------------------------y-----h-tvsnsk
mf-------kiptal----v-edsgp---ggn--ilggvrlsreveg---
------sr-g--d-----vql-rkqggtstvcwwaiv---dlfgaa-q--
adsfsglnp--rre--makl--a-lphangksfhsmks-----glgl-l-
-----------g-c------nklkt--s-ttfyl----fkkgk---ea-l
rg---lds----nvarvy------------mvtsaikvv-------avqg
mlplfkkapsarec-----------gt--lvg-ks-t--------t----
-y-----vnkltkvfyvckvyl--dl-----lgl----vaapm-------
---------pskgvsapca---------------------dyne-lhthg
let------gagt-------mhpnltegs-vylpshfsgga---s-----
----------g------qc--sp-td---nhgclytv--vs-w--stlss
tavk--skpq---------n----------------vvlqsdwy---v--
-----aqnc-------nkdlglp---fqvrk----i--rd----------
---vqkmgknvlc----rlk-----aygraaypqa-------ev--it--
-----aahpv-----------------vakgryvt--y--------ygc-
--sqa-nnaqpcytvgq----------ilwnp------k----lt--r--
i--ltt-------------ldr------c-lypnditlp-----------
--------wvh---rgd-------srvesk--gkg-----g-svfsfn
>C
-------------------------incv--vrtna--htv--------m
---fgkkggngvrkvala--h----ngv-l-agaasyet------ddntk
lerpgachksysykc-t---y------------------------g-vsp
-nk-ky---assdrlw------adsr---dksegvafrirhld-svknks
yf-------qrrngy----eypggsr---ddk--t-------rplvg---
------in-p--dvi-----m-n-------inw-hlkdgpqqygaa-a--
dpgfiglri----d-dagkv--g-vg-------itagk-----glaa-l-
-----------k-c------htids--cgglryp----rlkg----lr-l
wgflslda----gg-riy--------napi-ltnevgvlcgqyssh--s-
-laltkgfenqaq-----------------ig-h---k------es----
----ksmirrcllilygf-lay--el------vliqagn-----------
------------------v---------------------sssv---spf
l-k------etat-------vr-----dk-if-veqevaqvlldg-----
----------gdtkpkvpv--pk-ed---ksgin-----tc-w--itlef
scglrccnph---------ec-lhytadheeppg-lifq-r-wh---g--
-----tp----y-----vql-layvyfkawk----l--rp----------
---d------------------------------v-------vd--fevv
-----hg--a-----------------mrkg---a--y--------ftc-
--ags-hrnspcynfc-------------------------------ras
p--ttg-------------lar------c-llepg--ls-----------
----------------ekdam--acrteak--gkk-----v-v---ln
>node7
-----------scc-pepryn--saqkch--vrtng--rrv--------l
---iaak------krlla--h----qgpsl-gkkatyqt------d----
-------------ka-y---y-----------------------di-itp
-nk-kf---tgieslw------aeak---dqieilsfr----q-sisnek
ff-------rrpnaf----g-kdsgk---ngn--v-------rpleg---
------vk-g--d-----lnl-a-------vhw-qirdgperfgav-t--
addfsalhvs-kad--igkh--a-vp-------apips-----glsa-l-
-----------g-c------nmvka--c-taryp----rlrgi---ma-l
rg---lea----sgvriy-------------ltssvnvv-------tgyv
algltkkleasqec-----------gp--lig-kp-pa------as-v--
-y-qkalvkrlamvfyvy-val--el-----lhl----ldpkk-------
---------p-kg---qcp---------------------dsnt---tsf
lqs------asas-------lq-----er-vy-lphpiehk---g-----
----------g------qi--sr-gd---kagyq-----sc-w--ttlkf
sagr--ckph---------kr-lh-------prg-lvtl-q-wt---d--
-----tpkcl-y--ysgrrl-lpf-ffkvwk----l--rg----------
---ndklgknvlc----rlk-----pf----fpqi-------vi--fnvv
-----sa--d-----------------vsng---g--y--------fyc-
--aqs-ndnnpcysfaa----------vqwnp------n----mg--r--
i--ksp-------------ltr------c-lygpgltldkk---------
--------wgh---kde-------crtdak--gkrap---v-p---ln
>node15
-----------sccarepsyk--ktasch--trgng--rri--------i
---vaak------kalma--h----agpnl-gskisyvs------q----
-------------kpit---tq-------------------cqeni-itp
-l--kf---mgleelwqsfs--gdak---ktikillvr----s-sisndg
ff-------lrpgaf----g-----kksgngt--v-------rplqg---
------lk-s--e-----lag-m-------vdw-qikqgperfgtv-t--
adadsathag-gad--f-kh--a-vs-------savps-----glsafl-
-----------e-v------tlaks--c-tarfp----rlrai---ma-l
rg---lea----rgvrqy-------------lssa---v-------ygyv
afgltkyasapqec-----------gp--lvg-kpgae------ad-a--
-i-dkalvkrlpmvfysr-vsy--al-pgsrlhl----l-pkkc-ih-l-
klsspnakmp-kg---qcpm---k------k-----k--intta---asf
lqs------aacs-------lq-----er-vy-lp-piehi---g-----
----------g------ki--sk-gd---tqtyq-----sc-w--gslkf
qagk--ckah---------kh-----------qg-lvsl-q-ws---e--
d---gtpkci-y--ssgdrl-ipf-ffkiwk----l--re----------
---keklgksvlc----rlk-----pl----lqhi-------iv--fnav
-----sa--dhn---------gmkklvvtnr---g--y--------fyc-
--dqs-kd---cyafga----a----iv---d------i----lgsvs--
iypvsv-------------ltk------c-fyaagltlerk---------
--------wgn---kea-------crvdvkktgkr-k---v-p---vh
>node10
-----------sccgaqptymkl----ch--nkgdtp-rgnnflv----v
---lvvn------qgqsahth----ggpyl-tnvlsyir------r----
-------------kilt---slpv--g---lkggk------caepl-lgg
-l--kc---n-----wkslt--gdskvaetavki-avs----g-------
---------lrpsvf----v-----itsglst-------------sg---
------lk-g--e-----vgp-m-------vdw-ngkkga-----v-s--
adgqfssnag-ghe--f-sh--d-ve-------sdlaytdt--tv-afl-
-----------emvgtstast--------tarlg----klrgf---aaah
fg---lqs----r---------------------a---g-----------
-----------hnc-----------hppklkk-tp--kesaglavn-a--
-tvnkaivksl---fkcs-isg-val-tgtsv-----------c-lh-lv
kl---ylnmc--------viiitr------k-----q--setga---ggf
mqp------nppq-------lr---------y-me-pveha---gkkkig
snniqaselfg------ra--si-enn-ftqsda-----av-w--gdvki
qkg------g---kma-vakh-----------qgalvti-v-ws---e--
d---nlppci-y--dkg----vvf-slkiwk----l--keaqiil-----
---neklgknvic----rlr-----s--------y-------vv--fh--
---------khn---------aeptlv--nr---g--y--------mcv-
--nre-kd--------d----vlvgti----d------f----vgsvc--
gyptkmlpyynsgtsekqaftn------cafyatglml------------
--------wlc---kd--------cf-----sgkd-k---i-g---ch
>A
-----------pcc-adp------agkc---------------------l
---avpk------vrtlt--y----sdakk-ghkatfeg---sfte----
-------------ka-lkqqy-----------------------dl-vga
pee-rl---l-i------------------------y-----tdsvtqtk
lf------gkrpaafgglfg-meagp---gen--v-------repea---
------nk-a--n--kdnl--------------------ddhfgga-t--
addfaalhv--rah--pgk---tylk-------npers-----glda-l-
-----------g-c------ikiqk--c-asftl----rrrqf---rg-l
rg---ven----kti---------------------kav--------gr-
----fnkl-hadet-----------lp--lfg-ks-n-----------ka
ry-----vkkftsvlyvy-ael--kp-----lsl----vqpkv-------
---------p-ks---pcd---------------------dtla-fhthg
ldt------angs-------lpl-lydet-hylrshptggt---g-----
-----------------------------hvgydfavdnsa-w--aqlsf
tagk--ckky---------i----------------vilhi-wc---e--
-----nqscl-y--ftqrdl-lsf-ffaiwn----q--is----------
---lqklgknn--------------py----yaqv-------aa--fnsv
---------------------------vsdd---t--s--------fgcy
ekaqshndntpcfansq----------lq---------------------
--------------------tr------v-vypdegtlhak---------
--------wvh---rpd-------ar--------------g-aaikln
>node3
-----------pcc-pep------gakcv--irtng-kkqv----arval
---aagk------irlla--y----pdpkl-gnkatfka---nftd----
-------------ka-lkeqy-----------------------dt-isp
pne-kf---lsi------------------------y-----h-svsntk
lf-------kipeaf----g-kdsgp---ggn--v-------reveg---
------ar-g--d-----lql-a-------vhw-qivadedhfgaa-p--
addfsalhv--rvn--vgkl--t-lp-------npiks-----glsa-l-
-----------g-c------nkikt--c-safyl----rkrgm---qa-l
rg---len----ttvrvy-------------vassvkvv-------asqv
llhlfkkleaaqec-----------gp--lig-ks-sa------at-vkt
ry-----vkkltsvfyvy-vsl--el-----lhl----vepki-------
---------p-kg---pcq---------------------dtna-fhthg
lqt------asgt-------lhlklades-vylpshptgnt---g-----
----------g------hc--sp-ad---ragyqftvgsts-w--stlsf
tagk--ckph---------k----------------vilql-wc---d--
-----nqkcl-y--ftsrdl-lpf-ffavwk----l--rs----------
---vqklgknvlc----rlk-----pf----ypqi-------aa--ftsv
-----sa--i-----------------vsdg---t--y--------ygc-
--aqs-ndnnpcysiaq----------lqwnp------n----mt--r--
r--ktt-------------ltr------c-lypddvtlptk---------
--------wvh---rdd-------srteak--grg-----g-avfkln
>H
-----------tycerepaymnl---t----a--------t--------v
pthve--------etkma--d-------------dnyisgkg---r----
-------------rai-------a--g-mal----------------vef
-l--ncpaaasmadlwknlsv-gaat--rkacrillvv----v-vvq---
-sgwtmtv-----------------------s--i-------kalad---
------lk-kdmd-----aagat-------isr-lvpaagqrfgtvyp--
asaqrslhvg-gnae-y-ih--s-le-------sd-----------pfaq
iggvlpdshlynmvglk--ts--------pnkfq----rlpgfivpla-v
fa---vqgakver---------------------e---d-------yehv
sfa--g--plpp-----------------vskg----rgaskltvnns--
-avd-sivkcl---f-kg-esp-ial-tgnda-----------c-va---
-----fynms--------vav--t------s-----a--tevedg--kgf
isn------tppn-------ta-----ergah------------------
----------g------ratgsr-eetgftqgfi-----sii---gelsf
teg------hqck------kq-----------sg-lvsl-q-wa---s--
q---slppyv-f--a------ia-------k----vpnksvqkvh-----
---dailgkqvkc----qlhekllrsv----cdlh-------alltffnv
ilfgcga--dqnaltryssadchdniiaheh---g--y--------vhi-
--nkg-tn-------------------------------------gft--
vkansl-------------fmglpdkkgc----taltl------------
--------wkn---kd--------vrvtvq--gkd-antqv-d---ah
>E
-----------rccgdk----kl----ch--dkgdap-randfli----i
---yvvt------ngqsahtshkcsggeyl-nsavsyvr------p----
-------------nilt---svpv--g---ikggd------caep-----
---------------------------------i-avs----v-------
---------lhpsif----v-----lpstlgt-------------agkqp
ekkapkvk-a--e-----vep-m-------ydw-ngkkga-----v-n--
vdgqfda-----qq--y-sn--------------elayann--ml-sft-
-----------etvgtsgant--------rahfg----vlrg-----gad
ft---lnl----r---------------------a---g-----------
-----------hac-----------hspkikp-sp--kqsaalaqp-a--
-avnmplvksl---ykcp-iag-ail-tatsv-----------cnlh-lv
kl---ylntv--------iaivsr------------q--dsts------f
mnp------nppq---dlklfs---------f-mn-pvpha---gkkkvg
tnhlraanl--------ke--ti-nnn-favndt-----tl-ssgg---i
gka------g---rmvvvakh-----------qhalltl-v-ws---d--
d---nlvpci-yngdkg----vvf-alkvwk----l--k-gqikl-----
---keklgkhvic----rll-----n--------y-------vi--fh--
---------rhd---------eegnvc--nr---g--y--------mcv-
--hrk-ad--------d----llvsae----n------qptscvagvc--
gyktsvlpyg-----------n------lafymlglll------------
--------wlc---kh--------cf-----kgkd-d---i-a---ch
>node6
-----------scc-pnpvyn--taqkch--vrtng--skv--------m
---fgtk------kiala--h----ege-l-ggaatyqa------d----
-------------kp-y---y-----------------------dq-vsp
-nk-kf---agteslw------pdsr---dqsevlsfriqhmq-svtsmk
yf-------hrrnsf----g-kgegr---knn--t-------rpleg---
------ik-g--d-----lsl-a-------vnw-hlrdgperfgav-t--
edgftalris-kad--agkv--g-vp-------apisk-----glas-l-
-----------k-c------htvka--cdgpryp----rlkgi---lr-l
rg---lda----gg-riy-------------lthsvgvv-------tgd-
-lsltknfeseae-----------------ig-q---n------as-s--
-y-dkalikrvmlilygy-mal--al-----lhl----ls----------
-----------------ca---------------------dssv---spf
l-a------esat-------ak-----gk-vf-lahptehkl-ng-----
----------getkpkvpi--kk-gd---qsgyd-----tc-w--ttlkf
stglksckph---------gr-lh-------ppg-liiq-r-wd---g--
-----tp----y-----vrl-laf-yfkawk----l--rs----------
---ddk-----lc----rlk-----pf----fpqi-------vd--fqvv
-----sa--d-----------------isng---a--y--------ftc-
--aps-ndnspcysfca----------lhfnp------n----m---k--
v--ytg-------------ltr------c-lrgpgatldkk---------
--------wgh---gaekdal---crtdak--gkrqp---v-t---ln
>node13
-----------tycereppymkl---a----esgesp-hrt--------v
ptnvetn------ethma--d-------------nnyvserg---r----
-------------kais---tlat--g-galt---------ckdal-vif
-v--kc---egmedlwkalsv-gaat--kkatkillvv----v-vfrkdg
tsgwalfi-nrpftf----g-------selys--i-------kalad---
------lk-h--e-----vag-t-------vsw-evatasqrfgtv-p--
ansqsslhgg-gsde-f-th--a-le-------sd-----------pflh
vagllpd---ynmvgpr--st--------pakfq----rlrdfvvpma-v
fg---lqkakver---------------------e---g-------yehv
sfa--s--slptdc-----------ap--ltegkp--rgsskltvdhg--
-tvekslvkcl---fycg-qsp-ial-tgnsv-----------c-vh---
-----yfnms--------viv--r------k-----t--teaedt--egf
vsd------kpss-------tp-----ergay------------------
----------g------ra--sr-gengftqgmv-----nv-w--gdlsy
reg------hqck------kh-----------sg-lvkl-q-wa---e--
q---slppyv-y--a------iaf-yfkiwk----lgdkevqivh-----
---deilgkhvkc----hlrekllesm----cdhk-------ev--ffnv
-----ga--dhntlgsyssadcqqaliahnh---g--y--------vyv-
--hkp-td--------l----sllgti----d------i----lppic--
ikpanm-------------flslpekvgc---atsmtl------------
--------wrn---kd--------vrvdik--gkd-r---v-a---th
>node14
-----------sccdreptymkl---ach--skgdap-rrv--------v
---vatn------kglma--h----ggpyl-astisyvs------r----
-------------kait---tlpt--g---lk---------cqeal-vvg
-l--kc---qgmedlwkals--gdsk--ekavkillvs----a-afrkdg
sf-------lrpsaf----g-----kksglns--v-------ralag---
------lk-s--e-----vag-m-------vdw-nvkkgaqrfgtv-p--
adgqsamhgg-gad--f-th--a-ie-------sdlay-----tlsafl-
-----------emvgps--at--------tarfq----rlrgf---ma-l
ig---lqs----r---------------------a---g-------ygyv
sfg--q--slprdc-----------sp--ltd-kp--kgsaslavd-a--
-tvdkalvksl---fycs-isp-val-tgssv-----------c-vh-l-
kldspylnms--------viv--r------k-----q--tetda---ggf
lqs------npss-------lq-----ergay-ma-pidha---g-----
----------g------ra--sk-genaftqsyv-----nv-w--gdlkf
rsg------e---------kh-----------qg-lvtl-q-ws---e--
n---glppci-y--asg----iaf-yfkiwk----l--keaqich-----
---neklgkhvic----rlr-----sm----cqhy-------vv--fhav
-----gl--dhn---------sqktlivvnr---g--y--------myv-
--nks-kd--------d----alvgti----d------i----lgsvc--
vyptnm-------------ftk------ctfyatgvtl------------
--------wln---kd--------crvdvkktgkd-k---i-g---sh
>F
alrvascgglasccgsiplyinl----crpqgkgdkp-r----------m
---lvts------qkqsehtf----agspl-th------------w----
-------------kllt---glpvpag---skgarkviyalcgeel-lgs
-v--ac---h-----w---t--gqsklaatavki-ait----a-------
---------lrpsgf----v-----lts-ltt-------------cg---
------lk-t--e-----vgh-l-------idw-dgkksv-----a-s--
drgqfsnkag-ghe--y-ah--d-ve-------fdlqytdals---afl-
-----------aevgvsrgst--------ssrlg--------f---tkgr
-------s----r-----cppkkdny------------g-----------
-----------hncyaaghgvkcgyhppevkq-tp--ressglsvn-a--
-tfnk------------------valikatsa-----------c-lhcli
tl---ylkmc--------iivfnraaytnakdqkpcq--seqsa---gvf
mrpqhtkeqnppt-------lr---------y-ke-gvdqa---gmkqig
gnniratalfg------ra--si-dss-ftqshi-----am-w--gnvki
qkg------g---qma-lapqg----------qeglati-r-ws---elk
d---nlppcity--nag----vmf-sliiwkenkkl--keaqvvl-----
---ndklrkhvgcqklvvms-----s--------y-------vv--fh--
---------knn---------ldatlv-------gafyqcpgvpdascv-
--qke-kd--------n----vligtv----drrrfvlf----vgivc--
hyrsemlpyydngtseahqhmg------cafyatdlml------------
--------wls---rd--------cf-----sgkd-a---ilg---cn
