>node7
hdcqsilvk----gf-f----q---------qlkedvm-fvfvf---mqg
-----gdd------av-kvhir----afd-------------------d-
hsslkyvsv----likal--k---------eprydf-------sllkpkl
tnd-----------nspgaa----e------l----rvsa--ag-svl-g
---------a---eevladkygdfyfyrdveaekt--nvk------cag-
-hsqnt--------------ac-rq-----------c-----gcy-----
----dgm--k-----sgehk----psisavkv---cl-ky--lltli-gs
a---lkilyg--------------n--------fypd-------------
---vp-----------------kgvav-g-c-------------------
----e---------gftg--p--egdeit-----------aaf-------
------r--egn---dqkefvlrta--s------------c------giy
r-----frsks---------evffhhr----fn-vid--g-----v-ncm
wgr-kmqvsecatstfelnhgvsm-----ykaggpktfaeskaky---ah
t-v-hfelv---ekkfkme-fgaqvtvtv-----eik---lcatdg--g-
--hd----le---kd--w-gtys-csa--fck--tgv-lk-------grp
dassgvnsqsgtfp--lgtgfyll-----------v-------qyivk-a
nrwdsc--een----n-------daag-----fr---qtg----h--vel
k-----dvssqppg--dnnmrfwsns-qle-ldlmcgr-ekgqh--c---
----asn---kkfaps-----gr--------s-------lpddd--cg-s
rpr--i---------sv-------m---gswvekpvc-hiwftn-nnn-q
f-l-fvytk--kerflic--leyv--qlmyvgr----dddfe---lida-
taspt----dg-----------lg----------------w---hga--f
qq-
>H
kecqsl----------lygp-gttir---nvpr-----pyeicf---vhs
-----aeglkrlhrhg-kwqvk----adt-------------------s-
q---fyenv----ffill--n---------qpky-----------k---f
tse-----------q---sg----k------n----elis--aa-lil-p
td------rfscese-------d----kvidaws----vqlefdgs-gg-
-ndrqchtvqvdyafsegk-ss-chaekkeldscvpclfncfsgae----
----kgt--k--------------etdetagamdkch-ry--rpawg-ls
flnh------------iltatag-n--------tfle-------------
---scr-----nharlttlvl-kh-sk-v-ssn-----------------
----sngvmrpgd-g-ae--s-----qsgaagraykg---akfl------
tv----r---elae-----vrlqkd--d------------c------nkk
k-----ymakaf-----------fyir----fg-dvh--qesevgv-acl
lgl-mkndgqiehatwdlk--vcr-----vkidaksfygq-----sdf--
------------------------------------t---lvgdsslss-
--hr----laiklkc--ws-------vrqf--------ir-------sar
q--------------------yllrn---d-----li------h------
----kcia-vp----cfdedgssvn-a-----tr---q------------
----------------hvriatwttv-lgr-lgg---r-l---p--cmvs
cfqtppp---tkfaas------r-s------cl--------qnl--ciym
-----g---------av-------k--------kevaanewf--meva-t
rvlnaefig--knrflpc--lgv---ngkydgk--ak---ff---lykp-
sahpd----dgf-------aaklk-----pvt--------g---hma--k
qq-
>E
phcdsllld----nfftitk-snsfkaavetpp-----gfqicf---vhs
wqar-iaa----ykn--kmqlk----sath-----a-l----------a-
q---yflgi----lsvei--dqty------kspy-----------lkpkv
rkpgdnlnq-----a---ngnggvt------l----qi-a--pn-evlvt
vd------ka---gn--atrygd----kdietak----lk------vag-
-ndprgpvg---------h-qq-hh-----------a-wncngyyh----
----trmvhr--------------q---sqtt---cl-pfymlchkl-ht
lldv-----g---------------katv----fylvgadskttpsmcsg
tgkip-----------------kadal-gdnve-----------------
----l---------glgg--p------eg--------rgtkayf------
d--------------ealesvlhna--ktehrqklan---c------slp
rsesktfmnka---------qatfyng----as-aip--d-----v-vce
wgl-dmd-g--------------------vsknse---------------
g-f-efgcv---arnsevpkat--------------t---rfatri--g-
--hs----lg---kp--wpg---f--hrpfc-----lnsr-------tns
a--------------------slkrkffc-------t------v------
----pcac-m-----s-------lp-v-----vr---qka----h--n--
-----------pye--dvplkfwa----ar-lkg---r-y---ggnvg--
------p---knfgpp-----vkg--------m-ltr--lsqdidycg-v
rgr--v---------avl------tiiascwvgatvs-hawy--mstr-c
rglgtnyse-eskrhlac--kqykcddgayassgrh-----l---ffea-
aakhd----kes--aggfkiakll--------cysaltdfw---yas--l
qtl
>B
hgcsallvdttcsaf-f----d---------vlkngvl-nvaif---kq-
--------------sv----gm----afq---------------------
hnilkf-----------------------------fay-rpgqdlle-dl
rkd-----------d--gsg----e------l----rvst--ag-avl-g
---------r---tglvidkyaalyff------kt--htk------cna-
-ngqss--------------q--re-----------c-----pcy-----
----egl--k----esgees----dslagama---cfeqy--lttli-ge
e---lraiag-------------ey--------syph-------------
---fa-----------------sgvkv-n-c-------lvmkp---asr-
--hdh--------eglkg--v-d---sll-----------ssf-------
----------gn---dqktyvhytt--s---------ka--gr----aiy
r-----fqskc---------qvffppkkysffg-vve--g-----s-acm
laalnaqtkeckngvlgid---qasaatnysnskpsa----m-rf---ky
e-gvcsemt---erv---e-fgadsditgiplsipls---icatag----
---n----ld---ns--r-gs---c-----st--v----k--------kn
tvtsgieqlygtfpfgkgtdlyvl------gplste-------dalik-d
gkwdgc--epn----s-------a-dg-----fk---qtvvflghakkgf
h-----evgqqpqr------q-aghc-qla-lnlscgr-ghgpr--c---
----cee---nqfaprrfaidgr--------n-------lpenq--cg-r
rprhkvpvclvsetknv-------l---gssadvpvc-ygw---------
----tlydg--kdrfsic--layv--evvfars----dieve---lvea-
antps----dg-----------ag----------------w---kgtanf
er-
>D
psgagve------------------------qraa-v-------------
--------------ai-aphmnvevletd-------------------a-
k-----------mlvtdl--s---------k---ef-------vnlppka
kne-----------kspgaa----g--dlhg------vsmahtgsgi--g
---------n---paal-akfqefn-------hnd--kvv------casv
vhhdni--------------vc-kg-----------g-----pcy-----
----ag----------aehkggpe--vtvvkv---sl-kf--lkplkeqd
d---lsslyc--------------a--------fagv-------------
---qa-----------------lgsggr--------da------------
----v---------afta--p--eaaeiv-----------aty-------
--leek----------ekkvslrta--a------------e------giy
r-----fkpdn--------mgmmfhnv----fgkivt--p-----i-ncm
wgg-kmqvsvcpg--------vnt-----ykepgpptfltegsry---an
v-l-hftla---eaafqlt-lganvrvnv-----elk---icsgda--gp
lf-------h---rgvgw-gtyk-cha--fck--tqv-s-----------
------gnefsafv--laqgyfll-----------l-------qg-----
----gc--gsn---an-------dgag-----f-----------------
----------sipa--dhcmrfwqls-dl-gi-------drgeh--g---
----ardldpgnyvps-----gr--------s-------m---q--ca-a
vlr--l---------gv-------l---gcwverpvc-qm-flk-iel-k
f-l-hkyvr--repfavfegldap--elpyggr----de-f-ssnsvns-
sftpk----dg-----------la----------------rmtvqln--f
ga-
>node3
hgcqsmlvk----sf-f----q---------aiknevl-svcvf---qql
-----gdd------sv----gp----afd-------------------d-
hyllkfttv----gikal--k---------q--yefay-ssgnsllkadl
rkd-----------dppgva----e------l----rvsa--ag-gvl-g
---------r---eallidkyadlyfyreiesekt--hak------cea-
-hgqst--------------qc-re-----------c-----pcy-----
----dgm--k-----sgeqs----sslssamv---cf-ky--lmvli-gs
a---lkiiag--------------s--------sypd-------------
---yp-----------------sgvmv-e-c-------lvmppphkaqr-
--heh--------eglkg--p-d---nvv-----------tnf-------
------r--dgn---dqkafvhtts--s---------kaacgr----gif
r-----frckc---------qvffhpk----fn-vve--g-----t-ncm
wgklkmqisecqssvlgsnqgrslgcalnynagkpks----kaky---ky
a-g-ssemt---ekefkme-fgadsdvtvmplgigit---icatdg--d-
--hd----le---kk--w-ga---cka--fck--tgi-lk-------vkp
tvssgvdeqngtfp--kgtgfyll-----------v-------qaiik-d
grwdgc--esn----s-------eadg-----fr---qtvvflghakvgf
q-----dvgqqpqs------r-sghs-qla-ldlscgr-gkgph--c---
----aee---kefaps-----gr--------s-------lpedq--cg-s
rpr--v---------sv-------v---gssvdipic-yiw---------
----ylydg--kerfiic--leyv--qlvfvgr----dtdve---liea-
aatpt----dg-----------lg----------------w---rgtanf
qr-
>node15
rdcqsllmk----gflfc-p-q---------pt-----gfqitf---mqg
-----gkd------av-kihir----aad-------------------d-
qvflkyvsv----likal--k---------eary-----------lkpkl
tnn-----------dspgag----e------l----qiaa--ag-svl-g
te------rp---de--adkygd----rdietgk----vr------aag-
-hspht--------------ac-kh-----------c-----gcfe----
----dgm--k--------------ehidsika---cl-ky--litli-gt
f---lkilyg--------------d--------ayld-------------
---vp-----------------kgvam-g-cgq-----------------
----q---------gftg--p--gkgeps-----------gafy------
nm----r---dq---dgkdfvlrpe--d------------c------tiy
r-----fksks---------qvlfhhr----fn-iid--d-----v-acm
wgl-kmdisqcanstwelh--vsa-----ykigapkvfvqpkaky---ah
t-v-hfqav---hkeskis-fg--vvatv-----pik---lcatqg--a-
--hd----le---kd--w-gtys--adkafct--tgl-lk-------trp
dk-----skdg---------dylmrk---e-----vk------p------
----sc---ed----d-------asnv-----sr---qtd----h--vdl
---------sqpse--dnslrfwakv-lss-lsl---r-e---v--cgqg
c---asp---khfgpp-----srtt------km-spk--lsqdi--cg-p
kgr--g---------sv-------lflsscwvekpva-hiwfadmtnn-p
rgltvvytt--kgrfllc--leyp--qllysgr----dgdfd---llaa-
taqpe----dgf-------ieklg----------------w---haa--f
qh-
>node13
recesl----------fysp-gtqyr---espk-----gyeicf---vhs
-----aaglkklyrhg-kvqik----aat-------------------d-
q---fyedi----lfkvl--q---------qpry-----------lssaf
vne-----------q---tg----k------a----qlia--at-lvl-p
td------ra---sd-------d----rdieaak----lqiifngk-gg-
-ddpqgnlv---------r-ss-rh-----------clfncfahte----
----kgt--k--------------etphtvgp---cd-ry--kyawq-vs
flnh-----dk----dilsetag-n--------tfld-------------
---ssr-----nraristlvlska-al-a-ssd-----------------
----sdgit-----glag--s-----qag-------g---gafl------
tl----q---el---gglvailmgd--d------------c------tvk
k-----ymnkaf-----------fyir----fg-sih--q-----v-acl
wgl-mkdtgqiedatwdlk--vcp-----ikidaksfygq-----t--nh
t-v-h--at---rkttk-------------------k---lvggsg--s-
--hr----le---kp--wg-------drhfc---tal-vr-------sra
e--------------------yllkk---e-----li------i------
----kcaa-vp----c-------vs-v-----tr---qap----n--k--
-----------gye--hvqikfwtki-igr-lgg---r-l---g--cgqa
cfqaptp---khfaap------rst------cm--------qdl--cafp
knr--g---------sv-------k--------keva-hewf--mesa-c
rglnvaytg--knrflpc--lgf---ngmydgk--pk---fs---lyed-
kaqpd----sgf-------ieklm-----gvv--------w---hmt--l
qt-
>F
rrcddllmh----nflfvsk-nsqf----dtpp-----gfeicf---iqp
wqtm-ksv----yk---klrin----trsqgnrarpyl----------dg
e---yflge----lanelpndqqy------kapy-----------lipkl
dke-----------d---gg----qkn----l----alat--en-svl-t
tnlghiylka---sk--lsryge----ksieiak----lk------stg-
-qq---------------q-qr-hp-----------------gyyk----
----ksk--digky----------e---srta---ck-pyyvlchrl-nn
flgh-----g--------------tnkak----yylvd-----c------
-gkvp-----------------ssltl-ggsmq-----------------
----s---------gleg----------a-----------gvffpavase
sl----slr-eh---dg-glvlrgsntv------------i------ivk
-------i--n-aneksia-etvffnv----as-titttd-----v-vci
wgl-hrd-s---------------------tmhmrklfaq--------ak
g-n-nfaalffl-rscrvprks--------------k---hlgvts--g-
--qs----lg---k---wpg---q--kknfa-----ldlr-------tkt
q--------------------ipkrk---d-----vt------i------
----qcia-ge----k-------va-v-----thalpisa----t--s--
-----------pyf--evhvkfws----sr-lea---r------------
----------kqfgps-----sksa------gmvppk--lsqdaeycs-v
kgh------------avegfadfctmisscwvgktva-qawf--mhte-c
rnlaknyck---tkhlpc--kpfg--dsayvgtgt------l---ifea-
akrhd----tgf-------sikll--------cfpglsdfw---pas--l
es-
>G
kecssl----------fysp-gsqyk---dspk------yelcf---ins
-----feglkkl---glrvhvk----gat-------------------a-
n---fyedi----llkll--q---------qpkf-----------lsspv
tte---------------nd----k------a----mlna--st-lal-p
ve------aa---se-------d----rdtaai-----ldyngngk-tg-
-kdpvgnlv---------rgsk-kh-----------clfkcylntd----
----kgk--k--------------etsptvga---cd-ry--sfawq-ve
flkh-----aktlsndilpe----k--------iflk-------------
---snsgsptqhngrittlvlrka-sl-d-vgt-----------------
----sdgfp-----slqg--s-----rng-------g---g-fl------
tl----a---vl---dariaflmgt--t------------c------tvk
k-----gldkaf-----------fyak----fn-nih--h-----vlacl
rnl-rketgqiedaawdlt--vcp-----eapanksffgq-----t--kh
ttv-h--aa---rkttk-------------------k-----------g-
--hr----le---sp--ws-------arsfc---aal-vrvyrhktcsks
n--------------------ytlkk---g-----ldp-----i------
----q-ag-vpklv-c-------vs-v-----ar---qgp----------
-----------ghq--haqvk-wtki-lgk-lag---r-l---s--cnha
cfeaptv---khfvsp------stp------cm--------ldl--ctfs
knk--g---------di-------n--------kev--hgwf--resypc
kglnaaytg--knhylpc--lgf---ngmydgm--tk---ft---dyts-
k-qadasataaftp-----peklmftsgvgvv--------w---hmt--l
qs-
>A
hacqsrlik----sc-f---a----------aiktevl-gvcvf---qnl
-----gdd------ev----ap----afv---------plggegekvvp-
yyllkfsea----girgl--r---------k--yeftysss----ltsdl
rkd-----------dkpgta----a------ltdpdrhpa--gg-gal-g
-------------davfvskytalyfleeiessatvghst------cga-
-hvqsv--------------qcgwe-----------c-----acy-wvtv
lvqlngk--k-----sgdlg----sslpsqal---cf-ky--lmvmi-gk
a---lkvcvs--------------s--------sypk-------------
---yp-----------------cgvi----c-------lvapppskaqrd
ychqh--------nglkg--p-g---nvv-----------tnf-------
------k--egn---dqeafrhtsv--t---------kstcgknlndgmf
r-----ftync---------qvyfhpi----fl-vvi--g-----t-kct
lgrlkmqvgec-savvgsnqgrllgcslnytdarpk------aky---qn
a-g-esplt---qkdfkkk-kgadaaqtvigfccaityrlicpvgg--d-
--nd----le---qk--w-as---ckp--fcklltgi-lk-------vr-
---sgieepngtfp--kgagf-ll-----------v--rddnksairkgd
akwdgc--egn----s-------eaag-----fr---esasflghaavgg
q-----dvgpqpes------r-dghsrqle-ldlacvhfvkgph--c---
----tka---kpfaps-----gr--vskklhr-------ldeet--cg-v
rss--a---------ek-------v---gktvkvpic-yiw---------
----yvydg--kehfigc--leyv--elvfvgr----qadl----lvegi
altpa----dg-----------lg----------------w---rgqaaf
qr-
>node10
rhcdsllmd----nflfisr-sspfr---etpp-----gfeicf---vhp
wqtk-tta----ykh--kmqik----taaq-----p-l----------a-
e---yflgv----lakav--dqqy------kspy-----------lkpkl
skq-----------d---gg----e------l----qlaa--sn-svl-a
td------ka---sn--asrygd----rdietak----lk------vag-
-hqprgevg---------q-qq-hh-----------a-fncngyyk----
----trm--k--------------e---sqtt---cl-pyyvlchrl-ht
fldh-----g--------------tknav----yylvg-----c------
-gkip-----------------kslal-gdsge-----------------
----s---------gldg--p------ga-----------gayf------
nl----r---eq---dgldlvlrgahtd------------c------tvk
r-----fmnks---------qsvfynv----as-tip--d-----v-vci
wgl-hmd-a--------------------vtmntrkffaq--------ak
g-i-hfqai---aktskvprns--------------k---rlgtsn--g-
--ht----lg---kp--wpg---v--drnfc-----lktr-------tkp
d--------------------ylkrk---e-----vt------v------
----qcas-md----k-------la-v-----tr---qaa----h--n--
-----------pye--evhlkfwa----gr-lea---r-l---ggtcg--
------p---khfgpp-----skst------gm-ptr--lsqdieycs-v
kgr--a---------tvl------tfigscwvgktva-hawf--mtsi-c
rglatnysdkamkrhlpc--kqfk--dgayagsaqh-----l---lfea-
aarhd----tgf-------iakll--------cfaglaefw---nas--l
qs-
>C
rsslsmq--------------------------tedie-hvfiiaiqkea
----ymrd------ft-gqetdvqqagld-------------------m-
rpslkyadvgg---ipal--k---vksqafrprr-f-------inlapka
ind------qsesskhagaa----q--q---------iti--tgcgvl-g
---------i---kvvl---fadfyfyhetqkhne--k--------can-
-htqdi--------------ac-rg-----------a-----rcy-----
----ak----------qhassgse--lstisv---cl-ky--fvtlk-he
a---lsityc--------------h----vvfgfvnv-------------
---qt-----------------gginskg-c--vkedp------------
----v---------gftgsihv-egadtt-----------pst-------
------r--tgy--pdqakislrth--p------------r------giy
r-----fgpta---------pkmfhqr----fk-vla--e----------
----nketsv-pgsnf-------------hkdagfptfletsaqy---ah
i-l-haklv---askflli-f--envvkv-----gvk---kvsada--g-
--hhgqlvla---es--w-gtyn-crp--fck--tai-------------
------e------p--largfyil-----------l-------gs-----
---agc--stn----g-------graaykdknlk---qag----h--vel
kpplkfglndlvpgeaehqmqlwhvk-hlqgl-------ergqq------
-----kn---rksgns-----gs--------s-----acmrngd--ct-i
rpk--v---------nv-------k---gcwiqnpvr-ql-fil-hds-r
i-l-hvygn--kekylvc--lqaa--qls---------d-f----vlds-
afs-t----da-----------ls----------------rmnqqla--f
gq-
>node6
kssasmq------------------------qlkadvk-fvfii---kea
-----mnd------fv-aphinvevlgld-------------------a-
rsslkyvtvgggmlital--k---------rprref-------vnlppka
tne-----------kspgaa----q--qlag------vsv--tgcgil-g
---------s---eavl-tkfadfyfyhetqehse--kva------cpn-
-hhqni--------------vc-rg-----------a-----pcy-----
----ag----------aehkggse--lsvvkv---cl-ky--lktlk-qs
a---lsiiyc--------------h--------fagv-------------
---qt-----------------ggvggrg-c--akedp------------
----v---------gftg--p--egaeit-----------asy-------
------r--tgn---dqkkitlrta--a------------h------giy
r-----frpks---------gmmfhhr----fn-iva--q-----v-hcm
wgr-kmqvsvcpgsny--negvng-----ykeagpptfletdsky---ah
i-l-hfdla---eskflmt-fgadvrvkv-----evk---icsadg--g-
--hr----lt---rg--w-gtys-crp--fck--tav-ak-------trp
gaad--anqsgsfs--laqgfyil-----------l-------qg-----
---agc--gtn----a-------daag-----fr---qvg----h--vel
k-----dissqipg--dhhmrfwhis-hlqgl-------dkgqh--g---
----akn---kkyvps-----gr--------s-------mhddd--ct-s
rpr--i---------sv-------l---gcwvekpvc-qm-fln-hdn-r
f-l-hvyak--kerflic--leaa--qlmyvgr----nd-f----vvds-
sfsps----dg-----------ls----------------rmnaqla--f
gq-
>node14
rqcesllmk----gflfcsp-sgpyr---dapt-----gfeicf---vhs
-----gka----yrha-kvqik----aan-------------------d-
q---fyvsv----lvkal--e---------qary-----------lkpkl
tnq-----------d---ag----k------l----qlaa--st-svl-a
td------rp---ed--adrygd----rdietak----lq------aag-
-hsprtdlg---------r-as-nh-----------c-fncfghye----
----ngm--k--------------ehvnsmnp---cl-ry--lyvwl-nt
flnh-----g--------------d--------ayld-------------
---ip-----------------kglal-g-sgd-----------------
----s---------gltg--p-----daa-----------gaff------
nm----q---eq---dgldavlrge--d------------c------tvk
r-----fmdka---------qaifynr----fs-tie--n-----v-acm
wgl-rmdtgqaadstwkln--vcs-----ikidarkfysq--------ah
s-v-hfqav---hktskvs-fs--------------k---lvgtrg--g-
--hn----le---kp--wgg------drnfcm--tal-vk-------srp
d--------------------ylmrk---e-----vi------v------
----kcas-md----d-------as-v-----tr---qqe----h--i--
-----------pfq--hvqlkfwakv-igr-lgq---r-l---g--cgqa
c---sap---khfgpp-----srst------sm-ptk--lsqdi--ca-p
kgr--g---------tv-------kflgscwvekdva-hawf--mtsn-c
rgltvvytd--kgrflpc--lefk--dgmydgk--pk---fn---lyea-
taqpe----sgf-------iekll----------------w---hat--l
qn-
