>node7
--yfp-sytasat-lka----vsnmsrd-lnss---cl-----------l
---rl-ccgatk-tk-mdtgdy--tg-a----shknevcd-e--------
-an---ks-v------k-h----sfdit-alan-qrgqgl-vg-------
t---d--------lkfpgt---gg------clg-asmfd-i------d--
nlv-lray---------lmrm---npl---qeaaes---knpl---tcim
---lgk-------gtnskay-e----------lyglkk----------aa
--------aakdsmk-kgqv---------------hggp-------d---
eelagf------ifaf-----cslagekmep-pr-cecl---hyq--kli
sdtsttnefv----nf---------------pg-rskpfivtps-dkk-t
ddsae-v---y-n-gk---------l--lkl---qf--c--gm---y---
-dkncsvlnc--sgqn------sk-vllrikvdafnp-t---------g-
-dm--------wsg--dm--ssr-------f-saneane-------lf--
-p---v-wrehm----kqlavl----------is----yacar---klnv
----kvratvfkif-gteayhvpaplg-----fgyasrn-----------
lsieprlrghkkt-ylkp----qncl----natlnmsan-vqkv------
---lklva-f-----y--aqp------rt-h-----rgi----------i
fad---------g------vd----------e----a-------------
r-nsmgna----f------s------------ng--plrklfhtre-i--
---hd---------pfaav---tlettlg---------snfpgp-----n
ldt-y-tls---lalqv-s-s---w--italsmgdles--dsv-a----c
aq-
>node3
--yfpvvyavsat-lka----lsglfkh-lnrt--lcf-----------l
---rl-ccgakk-nksmddgdy--gn-a----lkk-dtca-q--------
-gk---kspv------kph----sfeit-snaa-ersqgl-vg-------
t---d--------lkfpgs---gs------cps-aamfd-i------d--
flk-lrpy---------la-----n------eadep---knql---gcim
---lgk-------gthnkay-q----------lyglkklehqpccawkmp
--------ikkdamr-rgak---------------hggp-------e---
eslegfsekvacvfkf-----cslngekrppsps-secl---hfq--sms
patnktyefv----nf---------------pa-rnkpfhvaps-dkeft
ddagd-v---y-g-gn---------l-glrl---kf--clsgm---y---
-hancslfsc--agds------sr-gllrirvnsfhpst---------g-
-nk--------wsg--dm--tar-------f-sgnean---------f--
va---v-wrehm---ekqldil----------ta----yacar---klgm
----------fyif-gaepyqvpipvg-----fgytsr------------
msieprlrsnkts-ylkp----hncl----katlgmtnn-vqkv------
---lk----------y--aqa------r--h-----rsv----------i
fge---------g------vd----------d----e-------------
r-dsvgh-------------------------dg--thrkwfhrre-t--
---hg-lylvckfppfesv---tfedtld---------skfpgp-----s
lnt-y-tlg---lalqa-s-s---w--idtkslgdlesicdat-a----c
eq-
>node6
--yyp-sytasvtrlkp----vagvsrdaansa---cf-----------m
---cv-cygavkptk-khtgey--nn-a----ghsdetca-e--------
-an---kc---------------------alvt-hvgsgl-vgrvgcskq
t---d--------lkfagt---gg------cqg-astfg-i------d--
n-i-astiakeslgpenl------hpl---aedgea---knplgqmwccm
---lgr-------gtcsreftl----------lygikk----------ta
--------gakdamk-kgdv---------------hngp-------dfrg
eelagf------afal-----ctlageemep-sk-secl-lah-p--nlm
setstsgefa----af--------------gpg-rtk-fiitps-dkr-t
ddlae-v---y-n-sk---------l--ikr---qf--c--ypsgvw---
kelscnellc--qnad------ttcvlmrvnv------------------
-----------wag--em--nss-------y-svdetne-------ly--
-p---v-wrhhm----kklntl------wrqlis----yacar---rlni
----kvratnfklf-gtean----pla-----fgyatrn-----------
lsiekry-ghrks-slkp----qncl----estlnlssn-gqkagdcaar
pdslnlva-f-----y--sep------kt-q-----rge-ls--sknkpi
fge---------g------vg----------e----t-------------
q-nsmgdk----f------a------------sv--slenlfhtde-v--
---h-------------aiqnlalicslg---------sdfpgv-----d
sdt-y-tls---lephv-g-t---w--vtalsmgdlet--ddv-a----c
ahy
>node13
--yfk-dgltln--mkp----gsd-irk-lfgsff-clktaw-------v
----y-vyrst------tagky--ng-t------kt---dai--------
-ap---nt-egnet--k-h----tfdlnfhfag---eh-lnvq-------
s---lqsr----kyrfggp-------------e----ye-f------k--
elvalqvq------------l---tak---qg--------------kcdg
---ciq-------ggngkif-i----------llevdq----------ka
--------rskndikpngyi---------------hgep-------a---
vnqigl------qfafpeyhkc----grf-t-pr-adcl---h-------
----tsnafqeg-elf---------------ea-ral---atpy-eeq-g
netts-l---y-sa-----------ne-ltl---hl--r--el---s---
-eghtnaldc--sgkh------nr-eilhlmhd-ykg-hivkn-ys--q-
-ls--------fvdmf-i--tsk-------f-slteana-------t---
-p---amskglmy-r-tslgvleftcsg----lscndwktcgtippk--p
---------------------gadhla-----g-----vm--ifirlifp
ltvepg----p----kkg----anc-r---h--le-----vskv------
---ln---ff-----f--agp------re-qgvt--rir----------l
lgd---------gdgsy--iskfrlnrdelapfawet-------------
mnttpgacwvdff------h------------sg--plrelfqlfa-v--
---hrd--------pfell---pedsvlg---------srfa-------p
l-----------------f-t---rkgvdvlsvsqsmn----t-------
---
>A
--yfhilfaisat-lka----lcklfkh-lktt--lcf-----------l
---ra-ccgskk-nktmnegdf--gn-a----ekn-ptcd-q--------
-sk---ksaa------qaheaqdaleit-ngavter--sl-tg-------
t---d--------lkfpgc---ge------art-pavyd-i------q--
fgr-lppy---------ls-----l------vatepspqkkql---gcvk
---tak-------gthnkay-q----------vyglkkl-----cgwrlp
--------ikkdesh-rgnk---------------hgga-------d---
eslqg--kkaacvfkf-----gsltgalkppsps-sec------q--css
paddksyefv----tf---------------pa-kakpfhvltsiekaft
ddaqd-l---y-f-gh---------l-glkl---kl--slrgv---y---
-panaslfscgfdgep------nr-gllr--vngfhpsg--------kg-
-sk--------wye--dl--snr-------l-kgheid---------f--
vy---l-wkeqm---ekqldil----------td----nackr-------
-----------yif-vaepypapepvg-----fgytsr------------
msnedkvrnqkga-y--p----ancl----saaldlane-vqkv------
---lk----------f--ara-pkncar-fd-----rcv----------i
fse-------rag------vd----------a----s-------------
k----ah------------------------cds--ayhkw-hrre-d--
---hg-iylvckf---------tfedtle---------skftgp-----s
vnt-s-slg---lsvqs-t-s---w--ittgglvnleahcnat-a----c
ee-
>node10
kayfe-vetgkn--vmp----ldyelgn-vlgtld-ci-----------v
----y-cygsp------sqgkygekk-t------ai---d-k--------
-aq---kk-egsdt--k-h----tydl-fhltg---sq-ldvg-------
s---ihkh----kfkfrgp---gslktysecfe-aqkfa-f------k--
n---vrvh------------l---sar---tg--------------kcyt
---siq-------ksdskiy-l----------lfgveq----------ka
--------inkhdrg-lggv---------------hggr-------h---
ltdkgy------qfpfe---ec----srw-t-pr-cvclk--kfd--n--
-----tttfq----lfg------------f-ea-rsq---karn-neg-g
ndste-a---y-sa-----------k--lal---qfkgc--el---a---
-eghceslec--sg---------r-kllhlmhd-fkg-tgvad-ygd-g-
-da--------fsdaf-p--t-k-------f-glteaia-------m---
-p---p-fkell----srlaslgvacsg----fscvkwyicvtlsnklpe
---------------------gpallg------------m--iftfltfp
ftaeeglnptd----skv----gkc-k---rsmid-----vnnm------
---ld---yfs----f--aga------me-eglt--rirl----------
----------------y--ikk--l--selvgcpwes-------------
sr---gdc----f------n------------sgdk--remyhlfq-s--
---qk---------pfgll---tidkilg---------rrfa-------a
l-----------------s-a---rkgigylsiseiip----p-a----c
ah-
>H
---fk-ngltgd--mkp----gsa-krl-lfgkfl------w--------
-------lrsa------imgky--nati------rt---dai--------
-aa---tt-egtet--k-h----dfdtdghfag---eh-vnv--------
----lasr----k--fssh-------------d----ye-f------k--
elvaqqve------------v---lpk---qg--------------kcdd
---cip-------naaakaf-n----------llaveq----------ka
--------qskddikpk-yv---------------pgep-------l---
vdliel------afafpdyqkc----try-t-tk-adcl---s-------
----isnafddg-elf---------------gt-kal---aspy-seq-s
seatskl---y-sg-----------hd-ltlpacrl--s--dl---n---
-dtqtdalnc--dskh------nr-dflslmhd-ykg-hvvkn-ft--t-
-la--------fgdmf-iastsrsgadsmrf-sqgessaledlilsr---
-p---tmskglly-r-tplgdqaftckg----lgcstwrecgtippk--a
---------------------gednlk-----g-----vl--tfprllfp
ltv-------------rgeeva-ns-r---h-----------kv------
---lk---ff-----ferpgp------te-qgvt--rfr----------l
--a---------engsygpihkfwss---lapfpwaskrkdkflngpsci
mshaqggcwlefy------h------------ng--plreisqlftqvan
lhqqre--------pfell---pedsvwglfsanyskssrfs--fttsvp
l-----------------f-t---rkppsvlavtqsmg----v-------
---
>F
rayyq-gdvgsq--vkp----ldyeldr-ilrnmd-ci----edtap--v
----y-sygsa------skg------------------------------
--hf--kk-vt-gnds-------------hltg---se-ldvt-------
m-------------kfrgp---gtlktyvpcfd-gedfppflyagndr--
n---vrvh------------l---ptrlthtg--------------k---
---riq-------kkdatiy-lfskllklthalveieq----------g-
------------dr--lggv---------------hggr-------q---
ltdkgy------qfpfe---gc----trw-i-gq-cvcla--eynvyk--
-----tqtyq----ffgeaavnayyacfty-eg-rsh---karv-neg-g
gdstd-d---yc-a-----------k--agl---qfrsc--em---a---
-dvhceslec-------------p-hmlhlihd-f-g-tgvdd-yg----
-dl--------fpdif-s--a-r-------f-pgtdgva-------m-na
-p---p-fndll----srlaclv-actg----ficvkwyicvtlgnklpd
---------------------ssalvg------------kgdiftslafp
ssaqdtlnpan----nk---------------aid----hvada------
---lg---yftpllpf--vga------de-ealv--rlrl----------
----------------f--fkn--l--qalvtdrwvi-------------
sr---gdc----fvngdmlk------------egnk--wd--klfq-s--
---kk---------pfpll---sidntlg---------rrfa-------a
l-----------------s-t---rvsagyvrigqlnp----p-a----c
ah-
>G
--ylk-d-ltln--mkpakv-nsd-tks-tfgrff-gmksaw-------v
----y-ay--s------taery--ng-s------qi---dtvtkmfklls
dkp---nt-dndav--k-n----tfdlefnfkg---ef-mnvq-------
sgks-qpqqtdralrfggs-------------e----yn-f------e--
dvralqah------------l---kak---hg----------------kg
---ciq-------ggkvkvf-i----------llevdq----------ka
atfdnel-rakneikpsgfi---------------hgepsgswgeks---
lsligl------qfafpdyhkc----gra-t-pk-adyl---h-------
----sfnalqggsglf---------------ed-kv----------eg-g
leaas-l---y-sa-----------ne-lal---hl--------------
---------------hlkllfynr-eilh-------g-hivky-ys--q-
-ls--------fiell-i--tsk-------r-glselna-------t---
-r---sigkglmtsp-dshpimhftcsg----lgcgnwktcgvvppk--p
---------------------gaanla-----v-----vg--iliriifp
sttepg----p----kka----snc-e---q--lq-----hwkv------
---fn---ff-----f--agp------td-qgvtgdrvr----------l
lgr---------gdgst--innfk-----lapfdwat-------------
mhtvpkscwaaaf------n------------aa--plkelyqiva-v--
---hrd--------pfesl---pedsvl-------------a-------p
l-----------------pet---rkavdvlkvkqdmn----t-------
---
>E
ssyye-iaigkn--vmp----lqweiga-ivaale-ci-----------v
----frcydsp------pqgkyggkk-s------ai---d-k--------
-aq-vgpt-dgsdg--k-h-----------------qq-ldfg-------
s---ih-h----kikfrgp---aslktngdcfn-aqlfp-f------r--
v---vrry------------ltfstsr---tg--------------kcfp
pntsiqlrgqllyklegegy-l----------fyg-eq----------ka
-------l----------------------------ggv-------h---
ltdkgy------qfplq---ec-----kw-t-pricvclk--tld--k--
-----tntfa----lfg------------y-----------ape-ngg-g
snvtq-a---y-da--evrttlflyk--maq---aykgc--el---atkt
-ashcdqlec--sg---------r-nflhlgnd-fkd-ktvas-ygd-r-
-dalidqeddlfsdvf-a--a-r-------y-alie--------------
-p---g-ykdll----sqllslgnvcsg----ftcvkwsicahlkdklss
h----------------------avle------------m--cfafstfp
ftakhglnptd----tii----gks-k---rsmfn-----vdim------
---lt---yfs-------asa------me-rgmt--sirl----------
----------------y--s----l--sqvvgcpwea-------------
qr---ndc----f------kpnlgcfnhhkk-trdk--relyhllp-n--
---qk---------plgll---sidkvlg---------rrfa-------g
l-----------------t-a---skgigylsvsdllh----s-a----a
ah-
>node14
--yfa-ddlakn--mip----veyairn-lfgsfy-cl-----------v
----i-cygst------tqgky--tn-s------ks---n-k--------
-aa---rt-egndt--k-h----tfdltfhlag---gh-ldvg-------
s---iqkr----mfrfagp---gs------cfe-aqrfs-f------k--
elvplqaq------------l---sar---qg--------------kcvs
---siq-------ssdgkiy-i----------lyevnq----------ka
--------itkhdik-kgav---------------hgep-------n---
ldqigf------qfafe---sc----srf-t-pr-cvcl---hfq--nhn
---ctssafq----lf---------------ea-rsk---atpn-eek-g
nette-v---y-aa-----------k--lsl---qf--c--el---s---
-eghcealec--sgth------ar-ellhlmhd-fkg-tgvrn-ys--g-
-da--------frdmf-t--ssk-------f-slteana-------m---
-p---p-wkelm----sklavlgvtcsg----lsckdwyicatlppklee
---------------------gpaplg-----g-----am--iftflifp
ltvepglkphp----nkv----edc-r---rssie-----vsni------
---ln---ff-----f--agp------re-qglt--rir----------l
lgd---------gnq-y--ikkvrlkkdelvpynwep-------------
pdttsgdc----f------n------------ng--plrdmfhlfq-i--
---hk---------pfgll---sedtilg---------srfa-------d
l-----------------s-a---rkgisylsiseiip----a-a----c
ah-
>B
--yfqvvygvsat-lkg----lsglfkh-lsra--vcf-----------l
---tl-ccqalk-gka--------gy-g----fkk-npca-h--------
-gk---kapv------kpa----tyeva-anaa-elsqg---v-------
t---d--------lklptswlsss------css--pmyd-v------dlv
nlk-lrpy---------lt-----k------eakea---knhl---gcv-
-----k-------gtankay-d----------ly-----nhqpscawkip
--------iksdama-sgak---------------hgea-------q---
esfaa---aiacifkf-----cnlkgekrppspg----l---qfq--y--
-atpkpyeft----nf---------------qagrkkpfqgapn-nkdyt
ddagd-v---y-s-gn---------l-gisq---kf--c--gr---y---
-rshcsqlsd--agqs------nk-gllrikinnfqpds---------sl
snk--------wsg--em--tpr-------y-qgnean---------f--
vakskv-wrepl---ekvldyl----------kc----yvcar---klgv
------------il-gaepy----pvacqiqhfgytyk------------
taves-lrsnktp-ylkp----htcl-fhgkatlgltld-vaks------
---dt----------y--mqml-----i--p-----rpv----------i
fegkndmlvk--s------vt----------e----a-------------
r-dsvgh-------------------------dg--thrkwfhmid-t--
---f--kylickqppyetv---tfedald---------tkfpgp-----d
lnt-y-nfggstlalaa-d-s---w--idakglgdlesicgpqka----c
kq-
>node15
--yfa-ndlaks--lqa----vssvsre-lyatfy-cl-----------v
---rl-ccggtr-tk-mttgny--tg-s----aqkd---d-n--------
-ga---kg-h------k-h----tfdlt-hlan-ergq-l-vg-------
f---lqdl----mfrfpgt---gs------cle-perfg-i------k--
dlv-lqaq------------l---nsr---qg--------------tcvg
---lvq-------gtdskvy-a----------lfevnk----------ta
--------itkdsmk-kgqv---------------hgep-------d---
lelvgf------qfgfa---ncllsgprfet-pr-cecl---hyq--kle
--tsttsefe----lf---------------pa-rsk--ivtpk-dek-c
ddsae-v---y-saek---------l--lkl---qf--c--gm---a---
-dnscsamnc--sgth------ak-dllrvild-fka-tgirnpsv--g-
-dq--------wrg--dt--sgk-------f-sateaee-------mf--
-p---v-wrehm----nklavlgvtcsv----lacndwyicanlppklde
----tvrttlfeif--ta-ydgpaplg-----g-----ka--mftfvvyg
ltvephlrthpkkdtnkp----qnc-r---rsslnknah-vqki------
---lnlvaff-----f--akp------ra-hgls--rsr----------l
ftd---------ghq-y--ikkvrlkkdqlveynwea-------------
r-ntsgsa----f------n------------ng--plrklfhtwe-i--
---hd---------pfaav---sldtglg---------skfpgp-----e
l-----------------s-t---wkqisflgigdlip----a-a----c
aq-
>D
--yyp-tynasvkplkp----lggiaqgsangv---cf---------eam
---cv-cygsvraar-khtgey--kn-gevssghtdqasa-e--------
-an---qy---------------------slvt-evcl---agkvgcskp
p---d--------lkfsgt---ga------cqn-patfg-v------d--
n-l-aatiekeslgtdnl------dpl---akepaa---kqelgqmwccd
---ldr-------gtcsrefti----------vygidk----------tf
--------gakeark-kghvsllglrsatpaeytphdgp-------efrg
eelaaf------afaq-----wtlsgd--------tdcl-leh-p--nlm
cagsisgdla----af--------------spg-rgk-fiiapp-dks-t
nmlse-v---y-s-pk---------l--ik--------c--lpfevw---
kdlacanllc--qnrd------ttcvlmrana------------------
-----------wtg--gi--nst-------y-yvsdtde-------lf--
-p---m-wkcye----kklntl------frklis----yvcer---slsi
-mlnrirttdfklf-gieas----kli-----fgyalrn-----------
lsieqva-ghqts-svkp----qscl----qp-lnlsan-gqhs--caar
paglkiia-f-----y--sep------pt-------rae-ltlrsknktv
fge---------g------vg-----------------------------
--agvgdt----f------k------------sa--slddlfhddd-m--
---h-------------gikalellcsll---------sdfpsv-----d
sds-ystls---lepnvsp-p---w--ppamcggdlkt--evv-g----c
pni
>C
--f---sytatvfrlkp---a---vgrnaatsa---cf-----------m
lkacv-cfaalkpsk-khtgaf--dd-a----ghgdetca-d--------
-ak---nc---------------------alvt-hhgsg--------gkh
t---e--------lkfagt---gd------cqgn-stia-----------
--i-astkpkaslspeal------qsl---akdgea---knplgqmwvym
---vgr-------svcpkdysm----------lygmrs----------ts
--------avk---t-kadv---------------qgap-------dfrg
eelvkf------lfal-----stllgepmg---r-ddcl-i---------
------dafa----vf--------------gpg-rth-fiv-pa-dtr-s
ddlee-vvsty-s-s---------------k---e-------pdsaw---
kelscdells--qned------tscvlmrvki------------------
-----------wpg--ea----s-------yt----tga-------ly--
-p---y-wrhhm----kkldal------wralms----ytcar---rlni
----gvrgyniklfdgtdvs----pla-----fgyetrg-----------
lnnhkry------------------------------as-gekgaeca-r
rdslnlva-f-----y--gdp------kt-h-----rge-----skdksi
fse---------g------vg----------e----t-------------
q-qslgek----i------g------------dv--sgdnlfqvda----
------------------iqetalicsld---------nnfpav-----h
sitry-tls---lephv-g-tlshw--iaaramgeldt--dni-ahacgc
khy
