>node10
rawaagvggkg---slstvs------lr----iwhr-rdlakvvidqkff
tskekv-----------nggslvglip--tt----ddcatgiagnvnlpc
-------lggl-------ivltlhleefssrkchskpelkhlrrpwmlgc
egkctitcggalsldiskqeldilfckfdkgicdpegertlcvlpglpgl
ekivedglpyhvakqldhaiclgms---------llhepagtvy-g---f
a--ftpkidtwpi--l--fvy-ittlkyapappkckagyqeaanmkpkgm
ttkalklff-----hvlrgle-------kvrrtnlcfkiia---------
-------------sdh---slaaensrsgphdkg--kmgssrpfaeycdf
adfkn---kiiaaiyphf-----yavialrd--gfvarllndradfklkv
scmqlychsal-------f---eqesayfvevkhgaekihhkgc--vhnq
-vvsidfcl----l--------pfvshhgvtdtmlcpleltdyapn--la
nlqvehtmanwarnqvygrvtrlfpdsya-vwkklkl-aghvksagvfe-
-radkpq-nvrgass--qlk
>H
---gagnggsgpapilatipqwvgvrlr----iwra-qdlkkvvvikrpf
tdkekviya---------dgtlvgltpeltv----ddcetgipgrvnllc
-------lggf--------vltphlqdfasrdckakpelkhlr----lgc
dgqckencggaltlnidkvkldilfckfdkgicd---ertlciipklpgl
eklidatepyhvakgldhticlgmg---------mlhspagpmy-gflkf
g--fmqkidtwai--l--fcy-ikiwkyapvspkckdgymdgatmkpksm
ttkalkl-f-----hllrgle-------qvkltdlcfklitp--------
hrnepvskshdcasdh---hlgteggrggphedt--kmglapptsaycef
gdfknrhsklvgfvyphyaaicgyavlplrd--gfvavladdqadfklkt
cciqlyctgallnaerrrh---edenayliplk-gaarvshkgchslhva
-vasidfcl----l--------tfvaphe-----lcplklkdytnhswva
klqve--ttnwaraqvygrvtrlfgdsya-vrknnnlhagevkssgvfh-
-raeepl-nikgagn--eqk
>E
rawaqgvaarg---slktvs------lr----awhr-rtltkvvfdqkff
askenv-----------nggslvglvp--ta----dtcatgiaghvnl--
------------------ivmtlhleeftarkchegpelkhlrrpwmlgc
esksiitcgagvpldiskqeldilfckfdkgiydpegertlcvlpglpgl
ekkvedglpyhvakrmdeaiclgms---------llpqpaetvy-g---f
g--fapkidtwnk--l--fvy-ittlkyapappkcksgyqegrtmkpkdm
atkalklff-----hvlrglq-------kvrrtklcfkvia---------
-------------sdh---plaaessrsgshdta--kmg-srpfaaycdf
ad--n---kiiasiyphf-----aavialrd--gyvavllndradfklkv
tcmplychsll-------fegl-qesayfvevkvggekihhkgc--chnq
-vvsidfcl----l--------pfvahhsvtdsmlcpkeltdyapn--la
nlevphamanwarnqvygrvtrlfpdsls-vwkklki-agqvk----idr
lradkkq-nprggps--qlk
>F
rlwaagvggkg---svstvs------lm----vwhq-rdvakvtidqkfl
tskekv-----------nsasllglip--tt----ddcakgiagnvglpc
-------lggl-------ivltlqledfssrkcnskpelkhlrrpwelgc
dgkctitcggalslditkheleimfckfdkgicdpegdrklcvlpglavl
ekivedgltyhvakqldnavclgls---------mlhepagtmy-g---f
a--ftpkidispi--i--fvy-ittltyapappkchagydeaqnmkpkgi
aikalklff-----hmvrgld-------kvrrtnlcfpvia---------
-------------adhlreaaaaensragphdkg--kmgssrpfaeycef
pdfkn---kiipaiyphf-----ygvialrn--gfvarllsgradfklki
scmqlyihsvl-------f---eqenayfvevkhgaqiihdkgc--vhnq
-tvsidfcl----m--------pfvsrhgvtdamlcplelmdyapn--fp
dl----tmanwarnevygrvtrlfpdtylapwkklkl-aghvksagtfe-
-radkpq-nvkgags--qlk
>D
---glqmgg------llain------lr----vwsv-stlpgiviglraf
kgkkkvgfdhmpgvkrtndgsigglnpdltp----sncdvgi--------
--------gtfc------illtvhlddlsirechakpslkhlh----mpc
--------ggalilnvpkqeiealfckfdsgihdlhpdri-cilpglpgl
gkklaetlayqgtkplehenclsmgkssngrpqrm--------q-g---f
g--ftpktgtwtimci--hcfeakirkyapaaplckggftksgskkpkgm
sdknfr-tf-----q-------------kvilq---friigleagapica
hkdeplsaahdcssah---sl-----rggpnsntsagmgagaaflnyyd-
d--nssqikfvpavcehfs----laitklrgrtgfvgvmskgrasfklki
ccinlychsai-------f---dyec-fqidvrhgipkvrhlvc--lhan
-lgevewcvvalcl--------pfgapegvtetmlcpmkvrdytpnkwla
klevg--faewq-------tsrvfpecyp-vwew--vqagrvkktglle-
-rtskpqaqmrgavs--qqe
>G
---gagvggsgpaptlasipewvgvklr----iwrs-pqlskviiydspf
tdkdkviyav---pksvnggklvgy--eltt----dscvagipahvnlpc
-------lgal--------vltpnredfstrkchakpelkhlr----lpc
dgqcktscggvltlnvdkadms-----fdraicd---erslcilpglpgl
eklidatepydvakrldhstcigmg---------mlreraspmylgflkf
g--ftqkidtwgi--vnqfcy-itiwkyapvsskckdgfqeggtgkpkgr
stkslkl-frardvyllrgledgydqlcqvrlgdtcfknita--------
hrddpvgkthdcvsdh---algpqnakggphedv--kmgsapptsaycdy
gdfknrgtklvafsyphya----favlplrd--gfvavladeradfmlvv
ccmqlyctvallnserrkf---aqesayliplk-gtgkkvhngchslhkv
-lasldfcl----l--------sfvapsg-----lcqlkladftpnnwla
klqve--vanwaraqvygratrl-------twknvnlhagevknsgvfh-
-ranepq-dvkgasn--eqk
>node7
---gvgmgg------laaid------lr----vwsv-ptlpkiviglraf
kgkkkvifdhmpgvkrsnggslggldpdltt----ddcetgiggggdlpc
-------lgsf-------illtvhlndfsvrkchakpdlkhlq----lpc
--------ggaltlnipkqeidslfckfddgicdpngdri-cilpglpgl
gkkvsaslpyhatkpldhdnclsmgkaskgspqrm--------y-g---f
g--ftpktgtwpivci--hcy-ckiwkyapappvckagfaktgtmkpkgm
seknlr-yf-----qllqglk-------kvilthlgfriialqtgapsca
hkneplstahdcaskh---sl-----rggpnnktsakmgcgppfldysdi
gdfkssqikfvqaiyphyg----yaisalrgragfvgimsndraefkfki
ccmqlychsaf-------f---ehecsyqisvkhgipkvrhlvc--lhnt
-lgaidwcl----l--------pfgapegvtetllcplkvkdytpdkwla
kleve--lanwqrdqvygrvtrlfpdcyp-vwew--vhagqvkkaglle-
-radkpqpqmrgasd--qqn
>node3
---gvgkgs------legid------lr----vwsv-pslpeavigvrhf
kgkkrvifahmpgvnhenggsiggldpdltt----ddcktgidgggdlac
-------lgsf-------iiltvhl-----rkchakphlkhlq----lpc
--------g-svvlnipkeeidslfskfddgicdangdri-cilpglpgl
gkkvdaslpyhatkpldhdnclnmglaskgspqrm--------y-g---f
g--ftpktstwpivci--hcf-ckiwkyapappvckagfaktgtmkpigm
seknlr-y------------------------thlafiiialqtgapsca
hkdeplsaahdc-------al-----rggpnnrtssklgcgpplldysdv
gdyaanqikfvaviyphhg----yeiaalrgrtglvgivsndp-------
--------taf-------f---ehgcayqisvkhgiphtrhlvc--lqht
tlgemkwcl----lsavrsvpkpfggpekvaetlkcplkvkdytpdqflp
klsve--lanwqrdqlygritrlfpdcyp-mwew--evagqiqkaglvs-
-k-dksqpqmrgasd--qqn
>A
---gvgkgq------legin------lk----vwsv-pnlpealigvraf
kgknriifaqmpganhenggpvggldhdltthactdecktgidgggdlac
-------lggl-khlfggilltahl-----rkcgaephlehlq----lpc
--------g-pvv--iskeeidslfskfdegicdaegdri-cilpglrgl
gkkvdaslpyhatkpvdednclnkglaskgsperl--------y-g---y
g--fspktstwpvlci--hcf-ckiwkyapvppvckagfantvtfkaigm
seknln-y------------------------thvafiiialqtggpacs
hkdeplssahec-------al-----rggpnhrvssalgcgpplleysdv
vsyaanqikfvgvaypqhg----feiadlstrtglvgiksndp-------
--------tgf-------f---dhgcgyqisvnrgiphvrhlvc--lqht
algdmiwcl----lnpvrsvpksfggpekva-tlkcpvkhkeytpeqfap
klsie--lanwqrdkly-rvtrlfpdcya-mwew--evagpihkagvls-
-k-dmt----rgtsdlvqqn
>node15
---gggmggls---slaait------lr----vwtv-ptlakiiidqraf
kgkdkviydh---vkrsnggslvglipdltt----ddcetgipgngnlpc
-------lggf-------ivltlhlddfstrkchakpdlkhlq----lpc
dgkcqttcggaltlniskqevdilfckfddgicdpngeri-cilpglpgl
ekkvdatlpyhvtkpldhdiclgmg---------mlhepagpvy-g---f
g--ftpktgtwpivcv--fcy-ikiwkyapappvckagyaetatmkpkgm
aeknlrlyf-----hllqgle-------kvilthlgfriiavqsaapsca
hrneplstahdcaskh---sl-----rggphdkspakmgsgppfldycdf
adfkssqikliaaiyphya----yavsalrg--gfvgilsndradfklki
ccmqlychsaf-------f---eqecsyqisvkhgvdkvhhlvc--lhnt
-vgsidycl----l--------pfgapegvtdtllcplklkdytpqkwla
kleve--lanwqrdqvygrvtrlfpdsyp-vwewiklhagqvkkaglfe-
-radkpq-tmrgasd--qqk
>node14
---gagvggka---slatis------lr----iwhs-pdlakvivdqrsf
tskekviyah---vkktnggslvglipdltt----ddcatgipgnvnlpc
-------lggf-------ivltlhledfstrkchakpelkhlr----lpc
dgkcqttcggaltlniskqeldilfckfdkgicdpegertlcilpglpgl
ekkidatlpyhvakqldhaiclgmg---------mlhepagpvy-g---f
g--ftpkidtwpi--l--fcy-itiwkyapappkckagyqeaatmkpkgm
ttkslklyf-----hllrgle-------kvrltnlcfkiiap--------
hrnepvsnahdcasdh---slaaensrsgphdks--kmgssppfseycdf
adfknrqtkiiafiyphya----yavlalrd--gfvailandradfklkv
ccmqlychsal-------f---eqesaylislkhgaekvhhkgc--lhnt
-vasidfcl----l--------pfvapqgvtdtllcplklkdytpnkwla
klqve--ianwardqvygrvtrlfpdsya-vwkriklhagevksagvfe-
-radkpq-nirgasn--eqk
>C
---gvgmgg------laav-------lrnaaviwsvqptlpvigiglraf
kgkttvnfshmrgikrsnggqmgqlnpdlyp----dnceqgigggdkppc
-------lgtf-------vlftvhlpglslrdchakpslkhls----mpc
--------ggvltlhvskeeieslyckfddgicdlhddrk-cilpglpgl
gkklplslpyhgakpldhdnclsmgkssngslqrm--------q-g---f
gevftpkrstwsimci--ncfeckirkyvpaaplimggfvkngtmkpkgm
ldknvr-tf-----q-------------kvilhqlpfriialeggaaict
hkdeplsaghdcsgkh---sl-----rgdpngktsvslgggpaflnyydi
g--ktsqiklvhadarhfa----yivsslrgrsnfvgitskgrasfklkv
ccsnlychysf-------f---eyeksyqvdvkhgipkvrhlvc--lnnt
-laelawcvtafyl--------pfgapegvtetllcpmkvwdfspnkwpa
kvave--lvewq-------qtrifpecvp-vwew--vhagrvtnsglle-
-rhnkqqtqmkgavd--qqe
>node13
---gagvggsgpaptlatipewvgvrlr----iwrs-pdlskvivkqrpf
tdkekviyah---pkkvnggslvgltpeltt----ddcatgipghvnlpc
-------lggf--------vltphledfstrkchakpelkhlr----lpc
dgqcktncggaltlnidkaeldilfckfdkgicd---ertlcilpglpgl
eklidatepyhvakqldhticlgmg---------mlhepagpmy-gflkf
g--faqkidtwai--l--fcy-itiwkyapvsskckdgyqegatmkpkgm
ttkslkl-f-----hllrgle-------qvrltdlcfklitp--------
hrnepvskshdcasdh---algpenarggphedt--kmgsapptsaycdf
gdfknrqtklvafvyphya----yavlplrd--gfvavladdradfklkv
ccmqlyctgallnserrkf---eqesayliplk-gaakvvhkgchslhna
-vasidfcl----l--------sfvapqg-----lcplklkdytpnswla
klqve--ianwaraqvygrvtrlfgdsya-vwkninlhagevkssgvfh-
-radepq-nikgasn--eqk
>node6
---gvgmgg------laain------lr----vwsv-ptlpgiviglraf
kgkkkvnfdhmpgvkrsnggsmgglnpdltp----dncetgigggsdppc
-------lgsf-------illtvhlndlsirdchakpslkhlh----mpc
--------ggaltlnvpkqeidslfckfddgicdlhgdri-cilpglpgl
gkklsaslpyhgtkplehdnclsmgkssngspqrm--------q-g---f
g--ftpktgtwsimci--hcfeckirkyapaaplckggfakngtmkpkgm
sdknir-tf-----q-------------kvilqqlgfriialeagapica
hkdeplsaahdcsskh---sl-----rggpnnktsasmgggpaflnyydi
g--kssqikfvqavaphfa----yaisslrgrsgfvgimskgrasfklki
ccmnlychyaf-------f---eyecsyqidvkhgipkvrhlvc--lhnt
-lgevewcvvafyl--------pfgapegvtetmlcpmkvrdytpnkwla
kleve--laewq-------ttrlfpecyp-vwew--vhagrvkksglle-
-rankpqaqmrgavd--qqe
>B
---gi----------legid------lr----vwsv-palpkavigvrhl
kgkgmvifahmpgdnrenggevgslepdltt----dnc--aidgggdlac
itrhdlvlgtf-------viltvhl-----rkchakphvkhlq----lpc
--------g-svvlniakedidslfskfddnicdadgdri-cilpglngl
kkkvdaslpyhttkpldhdnclnmglaskdspqrm--------y-g---f
g--fspktstwpivci--kaf-ckilkyapayhhckagftrtgtmkpigm
sekglr-y------------------------scltfiiigllpaspssa
hkdeplspahnc-------pi-----rggpnnrtscklgcgppaldysdt
gdykaehirfveviyphhg----yeiaalrgrtgfggivtvdp-------
--------sal-------f---qhgcayqisakqgvthtrllvc--llht
tlgemkwcl----lsavrkvpkpfggpekvnetlkcplkvkdytpsqflp
klsve--laawqkkqlygritrlfpdcyp-mwew--evagqvqkkglis-
-k-dksqpemrqgsd--qqn
