>node7
dkpdrasgvvt------kcedsedqqetfpyra-------yfaesvlr-g
agdyyvka----khn---gkenvcalyhsnfvgvyve--dser-------
---ppeldplafgnrdggvsnkre----spl-wgspysaikgvavvrqkd
lncggknakhwfctfiihaklfvgdavckskvs-tdsvgvklgfgvkrln
ncikisclav-pskn--------r---nvi---lplvd------k--smk
issdaaagicralmaisgasekskglrslpkvvkskcrtsakv------a
---gclr------kwialfq-----yigngvg---hifgpdag-fhgkdc
vvmapseplnl----------m--gqgkviedcapgll-----yqatlvr
cf------------gtg--sengst---cl-ckpglqsvk---lhssfkp
gid-----vltfsnprtggaacqfvnllktlggvg-cenan--vynwets
kphvlskgptkkqaystshsshlh----cndkswgpgcgsthifsdssss
ekvegr----spklv------snlla-----ad------gdcsvc-yrmp
--tgtfdqegcaciaakqqgedadpaegmnvfgtggvsskrkgegkkdvk
qfaldvllrl
>H
ekpdrgnghit------kcvnwqakqeefyfh---------fe--aih-g
tgnyytka----nnastv---nrcrvyrt----vyvdtekaedqalrega
ehpspalhslvfgtqsggiekkrkqvgdtcl-ygkrypgvk-f----eqd
lnclgnnakhwfcslvewvrefgadtvykvkti-testevqqgfsvmkqd
vckkflclai-dkih--------r---nas---lplinfshtkaiqtdvk
itadckegicrqltptaditdyt---rtvptvvkykcgtggdi------a
---kshr------ewislfqlkgf-yianevg---hpigpksecaq-kdi
avmvp--alni----------sspvqsklfqecasgllkenpeyqaalg-
---------------sg--seggpytakcl-cvpglqtvayaevyssfrd
gie-----sfaftnpfagggacelvnllst---vg-cqkra--vydrdgs
kphaasrgttrsqalstshaahip----ctdrsw----ssteiytdesgn
dqangkykiagpkla------ekllg-----adltevligdsaiciswep
aaast--qencgciadtnigeh----egmsvfgagepksdhkgsqkadvr
qy----ltrf
>node14
ekpdrgsgnit------kcvnwqtkqeefhfrs-------yfedvvlr-g
agnyyvka----krs---gkdnrcavyrtn---vyvdrekseqqam----
---spaldplafgtrsggvdnkre----tpl-ygspypsvk-l----qqd
lnclgnnakhwfcsfiihakkfggdtvgktktk-tdstevqlgfsvmrle
lckkfsclav-paih--------r---evt---lplid------i--emk
itsdctagvcralmpiedasdtk---rtlptvvkfkcrtagdv------a
---kchr------dwialfq-----yigngvg---hifgpnpecfhgkdc
vvmappdplnl----------a--sqsrlfqdcapgllreapeyqaglar
cf------------gtg--aeggpynakcl-cvpglqsvk---lnssfre
gie-----sfafknprtgggacqlvnllkt---vg-cekaa--vydwdgs
kphvvskgatktqafstshaship----cddrswgpgcsstqiypdssgs
eqangkykiagpklv------tnlla-----adltpvlmgdcsvc-ywkp
saagt--qdacaciadtqegengepaegmsvfgaggvssdrkgegkpdvr
qf----llrl
>G
qkpdatsgnvt------kcvnwkakqekfnfhs-------yfe--vfq-g
tgsyyvka----knaspv---nrcrfyrt----vyvdkekaedqal----
---spalqslafgtragginkrreqvgetcl-ygnpypsvk-l----eqd
lnclgnkvkhwfcsmilhrrkfggdtvyktkdk-ttstevqqgfsvmkle
vckkfsclai-ptih--------r---nia---lplfdf-htkaiqtdlk
itseckegvcralmptadaidnt---phvptivkfkcrtggdf------a
---kshr------dwislfq-----yvgngvg---eaigpspqcfegkdc
avmvp--alnv----------aspadskmfgecapgllregpeyqaelgr
ci------------gtnglaeggsytakcl-cvpnfqsvkyaeiassfrd
gmq-----sfafpntfagggacelvnllkt---va-cekaagcvydwdgs
kphvvargvtrthafstsaaship----cndrswdpgcsslpiypddsga
dqapgkykfaspklv------tkllg-----qayspvlmgeksvciswk-
-aagt--qencaciadtnigeh----egmsifgaggpssdrkgeqkadvr
ql----ithf
>node3
ekanrasgvvt------kcedgedqqttfpyra-------yfaesplr-s
agdyyvka----kkn---gkenvcalyhsnfigvyvd--aser-------
---ppeldalafg-kdggvsnk------spltwvspyvaksgvavvrqkn
lnhggknvkhsfctfiihtklfigdkvckndvpafdsvgvklgfgvkrvs
ncikiscvav-askn--------r---nvv---l----------k--smk
issdgaagickalmaingateksiglrslpkvvkskcrtstkagrvlass
---gclr------kwisffk-----yigngvk---hifgpdag-fhgkdc
vlmapseplnl----------m--gegkviedcapsll-----ydatsir
cf------------gtg--setgst---cl-ckpglqsvk---lhsgfsp
ged-----vltfsnprtggaackfvnllrvlggvg-cedak--vynwets
kphllpkqptkkqgypvshtrhlh----cndkswgpgcgsthifadcses
ekveak----dpklv------snlla-----ad------gdcsvc-yrmp
--tgtfdqegcaciaakqqgedadpaagmdiygpggisskrrgegkkdvk
qvtldvllrl
>E
ekpdrsrggissdskgtkcirwqvkqeefhfrh-------yfedvlls-g
----yvka----krs---gkddrcsvyrtr---vyvdrdkceeham----
---tkaldilllgsksggvdhkin----tpm-fgyplt-----------d
lncignktknwfcafvihskkwggdsaaktkq------------svmr-d
lcknfsclev-pvll--------r---evt---lpdid------i--gmq
dtsdategvcrslatfddacntg---ralprvhkfkckvagnv------s
---schr------ewiglfq-----yiaegig---rvvgtdppcfhgphc
vvmtppdplsq----------a--sqrrsfqdcaagllreateyqqg---
cf------------g----aeggpynakclisdpglqtvk---lesafke
gie-----efafknsrngggacqlvnlldt---vg-cdnka--vhnfdgt
rphvgsnggtktna-------nvp----cdarswgsgcsseqi-sacsgs
etasgkytiagnklvvddgratnlla-----idltpvlmytcslc-ywkp
staag--qdagaciaetdegekgepaaessvfgngavaadrkgdnkpevw
qf----llrv
>F
ekpdrgr-git------kcvnwdvk----hfrs-------yftdvvir-g
ansfyvca----krs---gkddrcsvfrtk---vy--rdkceqhgm----
---kraldalaigsrssgvdskiq----tpl-fgysfpavk-i----hqd
lkcigdntknwfcaftinakkwggdtvaktkh------------svmrle
lcksfscldv-paia--------r---dvt---mpdid------i--gmk
gttdltasvcralmtfedgcdsg---rtlprvqkfkcrvagga------e
---kchs------nwialfq----tyiaegig---kvmgpnspcfhgkdc
ivmapsdplsl----------p--sqerafqdcapgltreateyqas---
cf------------g----aqggpynerclisvpglqslk---lessfke
giepkaeqpfafknsrtgggachlvnllkt---vg-cekka--vhdwdgs
kphsvsngglkthalstshsshva----cedrswgsgcsttqi-sgnsds
esengky----kklv------tnllt-----qdltpvliaqcsvc-ywtp
saadt--kdacaciaetdegengepadettvygnggv--dekgdnkpevw
qf----lrrl
>node15
ekpdrgsgkit------kcedrqnkqeefpfra-------yfeesvlr-g
agdyyvka----krn---gkdnvcaiyhsn---vyvd--kses-------
---ppaldplafgarsggvdnrre----gpl-wgspypavk-i----qqd
lncvgknakhwfcsfiihaktfvgdtvcktkvk-tdsvevqlgfsvkrls
ncikisclav-pstn--------r---evi---lplid------k--smk
issdaaagvcralmaiedasdts---rtlptvvkskcrtagnv------a
---kclr------dwialfq-----yigngvg---hifgpdpg-fngkdc
vvmappeplnl----------m--gqsklfqdcapgll-----yqaalvr
cf------------gtg--peggptnancl-ckpglqsvk---lhssfrp
gie-----sftfsnprtgggacqfvnllktlggvg-cekan--vydwegs
kphvvskgatkiqaystshashlh----cndkswgpgcgsthifsdssgs
eqadgryk--gpklv------tnlla-----adltpvlmgdcsvc-ywmp
sasgt--qeacaciaakqqgedgdpaegmsvfgtggvssdrkgegkpdvr
qfaldvllrl
>node6
dkpnraagvvt------kceasedkessfpyrl-------yfadsiik-g
agdyyvkapkfaknd---gkenvvelydsnfigvyve--dser-------
---padldnlafgkrdggvsnkqd----spl-wgspyseikgvavvrqqd
lncggsnskhwfctfiihaklfvgdatckskvt--------lgfgvkhln
ncikiscmav-pgknadgncafdr---nvi---lplve------k--amk
itsdschgicralmaiagasekskglrslprvvkfrcrssakv------a
---sclr------kwitlfq-----yigngvg---vifapeag-fhgkgc
vvlapseplnlqhskqffvelm--gqakviedcapgyi-----yqatlvr
cf------------gsg--sengst---cl-ckpalqsvk---lhssfkp
gid-----vltfsnprtgggacqfvnllkplggvg-centd--vynwets
kphvlskgptkkqayttshsshre----indkswgqgcgathifsdssss
ekvngt----spklv------snlla-----ad------gdcnic-yrmp
--kntfdhegcaciaakqqgeggdpaegeggfgsggvsskrkgegktdvk
qfaldvllrl
>node13
ekpdrgsgnit------kcvnwqakqeefhfhs-------yfe--vir-g
tgnyyvka----knastv---nrcrvyrt----vyvdsekaedqal----
---spalqslafgtrsggidkkreqvgetcl-ygnpypsvk-l----eqd
lnclgnnakhwfcsfivhvrkfggdtvyktktk-tdstevqqgfsvmkle
vckkfsclai-ptih--------r---nva---lplidfnhakaiqtdlk
itsdckegvcralmptadatdnt---rtvptvvkfkcrtggdi------a
---kshr------dwislfq-----yigngvg---hpigpkpecfqgkdc
avmvp--alni----------aspvqsklfqecapgllkegpeyqaglgr
cf------------gtg--aeggpytakcl-cvpgfqsvkyaeitssfre
gie-----sfaftnpfagggacelvnllkt---vg-cekaa--vydwdgs
kphvvsrgatrtqafstshaship----cddrswgpgcsstqiypddsgs
dqasgkykiagpklv------tkllg-----adltqvlmgdssvciswkp
saagt--qencaciadtnigeh----egmsvfgaggpssdrkgeqkadvr
qf----ltrf
>A
eranrasgtvt------kcedeedqqvtfpyra-------ffaa--lr-s
tgdyyvkt----kkn---gkekvcaiyhgnfigvyvd--ader-------
---ppdldalafg-kdggvsdk------spltwtspyvgksgiavvrqkn
ldhsgknvkhsfcsfvfhtkmflgnavckndlpafdsvdvklgfgvkrlg
ncikiscvav---kn--------rslgnvv---a----------k--imk
isddgsagvckslmgvngapektiglrnlpkvvkgkcrtv--tgrvlass
---sclr------ksipffk-----yvgngvk---hifgpdag-fhgkdc
vlma---------------------egkvisdsapsll-----ydatsir
cfstvmlkgisstfgvd--sqtast---cl-ckpglqstk---epfgfsp
ged-----vlhfqnprtggaacnftnllrvlagvg-cd------ygwets
tphltpkqptkkqgypvshtrhlhicshcndkalgpgcgstqilancgeh
ekvesk----daklv------shllatihatld------gnckvc-yrip
--lgsfdqegcackgmkqqgedadpttgmdiyspggigskrrgegkkdvk
qvtldvllrl
>node10
ekpdrgrggit------kcvnwqvkqeefhfrs-------yfedvvlr-g
ansfyvka----krs---gkdnrcsvfrtn---vyvdrdkceqham----
---tpaldplaigsrssgvdnkiq----tpl-fgysfpsvk-f----hqd
lncignntknwfcafiihakkwggdtvaktkq------------svmrle
lcknfsclev-paiv--------r---evt---lpdid------i--gmk
etsdatagvcralmtfddacdtg---rtlprvhkfkcrvagdv------a
---kchr------dwialfq-----yiaegig---rvigpnppcfhgknc
vvmappdplnl----------a--sqsrafqdcapgllreateyqag---
cf------------g----aeggpynskclisvpglqsvk---lessfke
gie-----sfafknsrtgggacqlvnllkt---vg-cekka--vhdwdgs
kphvvsnggtkthafstshsshvp----cddrswgsgcsstqi-sgssgs
esangkykiagkklv------tnlla-----qdltpvlmadcsvc-ywkp
saagt--qdacaciaetdegengepaeessvfgnggvsadrkgdnkpevw
qf----llrl
>D
dkpnraaglvs------kceesdn-esshpyklsrtygkayfadsiiklg
egdyyvkapkfpknh---gkenvvelyssnfigvyme--eker-------
---aadldnlafgkrdggvsnkqd----sgl-wgspyteikgvavvhsqd
lncggsnskhwfctfiihakqfvgeatcktrat--------lgfglkhln
ncikiscmavragknqgggcafnr---iii---lplme------n--amg
itseachgicralmaiggasekskglrslprvvafrcrsfgkv------a
---sc------------lfq-----yvgngig---sifapeag-fhgrgc
lvla--epldlqhlkqfftelm--gqakvledcapgyn-----yqaalvr
cf------------gvg--sengst---cl-ckpaaeavk---llssfkp
gin-----vltfsnprtgggackfvnllkpltgvn-cesvd--vynwgvs
kphvlsngptnkqayttshssdre----indkswaqacgathifcdssss
ekvqgt----spklv------snlla-----ad------qecnic-yrls
--kntldhegcagiaakqkgeggapaegeggfgvggvsskrkgegktdv-
-faldvllrl
>B
ekanrasgvvs------kcedgedqpttfayra-------yfaeallr-k
tgdyyika----kkn---gkknvcavyhanfkgvyvd--ager-------
---ppeldalafg-kdggvsnk------kplrwvspyvaktghevvrqks
mshggksvkhsfcyfiihtkliigdq----------svgvklgfgtkris
ncikiscvkt-askn--------r---kvv---l----------k--pmk
espdgaagickalkaingvteksiglsslpkvvkskcrt---agrvlagt
kmlnilrllaknskwtsffk-----yigngvklfphifgpdag-fhgkdc
vlmaasdplnl----------m--gegrviedcapsll-----ydstsir
cf------------gsg--setgss---cl-skpglesvk---lnsgfsp
geq-----vlafknprtggaackfvhllrvlggvgscedak--vynwevs
kphplpkqptkkqgypvshtkhfh----cedkswgpacgsahifadcses
skveak----dpnlv------sntla-----ad------gdcsvc-yrip
--agmfdqdgcaciaateqse--gqaagmdiygsddisikrrgdgkkdvk
qvtldvllrl
>C
dkpnraacvtt------ktegnedkqssfpyrl-------yfadsiik-g
agnyyvkapkiaknd---grenvvelydanfigvyve--dser-------
---padldnlaygkk--ginkkqd----spl-wgrpys-ikgvavvrpqd
lncggsqskhwfctfiihakifgggdtcktkvt--------lgfgvkhlk
ncvkikcqav-psknsdgncafdr---nvifynlplve------k--amk
itsgschgiirglmaiagasektgglrslprvikgrcrscakv------a
---sclr------kwitlfq-----yisngvg---vlfspesg-fhgkgc
ialdpsdplhlqhskqffvelm--glvkvlaecapgyi-----yqsarvr
cf------------vss--sengst---sl-ckpslqsvn---lhssfkp
apd-----vltfgnprtgggtcqfanllqplgglg-canth--vypwdps
kpyvlskaatkkqayttshsshke----iadkswaq------lfpdssss
egvnst----ssklv------snlla-----vd------gdcnic-ykmp
--kntldheacaciaakqegegadpdegsggfgsggvsskkkeegitdvq
qfaldvllrl
