>D
-sqavgcqdpsiakwvvalagp-khkelwdlkpgpeafvkgkndakdrhq
qwtadqvaqprssp--itchas-nlnynsntdfdyskpeaeqvvakdgvq
eiltpenkgekaygelalvgata-----gaegtnsakyaktvlllpvsgs
rktk---atgrmk-vpatk---gcimwakreqhrrpgwktvaavdtsllt
slcsesr-r--g----pngpgr--------------vcvnqyc-----ga
tghaqaeekggvgipsellkfnshshvvi---fadclfhehfylkhlhh-
-pdgqcpilyirp---------plagiclqhifktkwt----lqvagkmg
ydgipfk-k-hhk---slqnktrltd-----qrcgrhttag-eepvar--
-ptetsdahvalvaevpidkaqldfcckrddddpkmimgpnvyphghdek
lnckvvdlepa--d----srhdkggctpkahqsacalqavvf--------
---nk-epfalchspfgllfikams---kadevhfepagatgce-g----
----------lggednyladyktvknflkncc-----riwitshqdvqke
gfyhdlpkpaspsvrfqlcqvhl-cnl
>C
-sqplgcpdpkiakwvvsiaga-khrelwklkpgpdcfvkgkqdakdkhq
qsakdkvaqprsss--itchmsktlnynnntnfdygnaeaqqvlakeavq
daltaenrgekaygelalvgava-----gaggtiyakyakdmllldvsga
kkanhaladgrkk-vpvgk---gcimwgkreahrrpgwvaiaavetsqla
slcsenkgr--g----pknpar--------------vcvnqys-----ga
teqvqpeekggvglasqllkfsshsnvfi---yadclfhehfylkhlfv-
-pegqspalyirptpa---ykvafagiclqgifkakwd----lqvagkmg
ydafafk-r-hvk---alqnktrvad-----qhcgrhtttg-depvar--
-----aeahvtlvaaltietaqlkfcckrdddepkmcmgpnaypqshdek
fkckvvnthsa--k----arqek--capkvharacalqavvf--------
---gklesfllcrspfglliikpanvctkpeeshfentgatgce-r----
----------lggdlnyladyatcnnflkncs-----varvtshhavqte
gfsndlpksassqarfqlcqvhi-cql
>node10
vseplgctdprvakwgvavaga-ihrqdwklnlggeclgkskeeqtecng
nwapehvskppkg----actla-elkqnadkyfdfststadrtvtkgdgn
egl-agnvgekaygelal-------------gtg------vm--vavlgr
rgik---aigrltvlpqakepdgcivwlnraaskq--wsgvaevdnyllr
glcgqqr-kahsllygffkvgr--------------icvnhht-----nv
tdsahneqksggwrskenlkyssedfdll---yd--mfhehgyl--lys-
-pedq----yldstpd---yrvtlaglclqnlfkts-t----lqvaglma
yavnqlkfq-hvk---tlknrtripdkr----rcghytrkv-qnpaek--
-apdpggsgdsslgelgiepaklefcckrednepsqcmgsntypkgtdea
lhckisdtqpa--d----srh--gpsspkvhtkvcqvdhtaa--------
---dkldaf--rnssfgalflksia---dpenthfe---ptgyg-g----
----------qggegnylanfgsvknflkssc------------hevqye
gfydtlpkglapagryqlckvhv-cql
>B
-s---tcaepkitksgiaiagv-vhktlwklkpgpecyqkaeqaqnerhq
rwaedhaanpkkdrqkiacnis-dlkyntdshfnfsngetektlatdagg
a--sedtrgekaygelslaskitqvnragaigts------tmlhlhfsgv
rgtk---atgrmr-hpttk---gcviwllregkrr--wasiaesdtclmt
glcsanr-rehk----fyqigrkdctgwkavklkssvcenqyt-----gt
sekaqteqt-----ssqalkfsceahhfi---ysdsllqdhfylkhlfh-
-peaqvpalytqptvasyksrhskagicleklfstk-t----lqvidlmq
ytenpfk-k-htr---slqnrtrvsd-----ercgrhrfpg-sepvsp--
-ssataeadvspgtnlsfe--qlnfccqrddndp-mckga-vfphgndds
msckvvntevapke----akhdmspcspkvhlrtcalqgvri--------
---akietvmlctmpfgllfvkaln---esddahfg---ptvcekg----
----------hggeenfdahyktvkgylinccawlslrlwvtsphnvrye
gfyqglpkgnspndkyqicsvhl-cqv
>A
-sqpldcgdpkitkwgiaiaga-vhkalr---papgcyqkgeeeakerhq
rwnedyaakpqkdt--itchin-dlkyntgshfdyqdgeaeqtvakaagg
e--atdtrgakaygelalvskit-----gei----------mlhlaasss
rgtk---atg------------gcivwleresksr--wssiaetdtclkt
glctasr-qshs----fydldp--------------vcinqyi-----gq
tesaqyeqtggvsipsqllkfsshthpfi---ysdslfhdwfylkhlfh-
-pedqvsalyvqptva---srhalagislqklfktk-k----lqvvddmq
ftqdpfk-kyqtr---slqntarvad-----qrcgrhttpg-sepvsp--
-stdtaeadvhpgtnlsipkaaldfcckrednessmckgpsvfpqgndds
mnckvvntqvapkdclriakhekspcspkvnlktcaletvri--------
---gkietfmlcgkpfgllfvkaln---kkddahfe---ptgckgg----
----------hngeehfdahyktvknflksccpwlnlriwvtsphdiryg
gfyqglpkgkspsgryqlctvfl-cdl
>H
ydqpvgctdsrvakwgiavvganlhrdswkmnpgaeglvkgkekhtacsm
qwaadhvskpikk----sctla-eleqdaqkqfeyntgedqrvvskgggk
qgl-tdargeknygalpl-------------gtg------vs--vavsg-
rgir---ligrltvlpnpk---gckiwihgeakkq--wtgvaevdtatmr
glaghss-khtallygffssgg--------------icvnhytekniggc
sdndpseqkcdawrshqnlnegsedevll---ys--kfhs------lfq-
-aenq----yldsnad---ygvtiaeicldglfktk-t----lrvaglfs
yapnqlkfq-rik---slqqrtripdkrvardrcgrhtngasdeptak--
-psgp--psessggdvrvapskftfcckesdkepvs--gtkayprgkde-
---kiadtlpa--n----tkh--gpgsqkiqeaicavn--aa--------
---dkvea---rdspfnalfirspg---spedaryd---ptsce-gmedk
hgldadfllkqggeehyleyfgsvkdliktcc-----plwatshhdaqye
gfyitlpdglapagayvlctihtecql
>node6
-sqplgcqdpkiakwvvaiaga-khkelwklkpgpecfvkgkqdakdrhq
qwakdqvaqprsss--itchms-nlnynsntnfdygnaeaeqvvakdgvq
eiltpenrgekaygelalvgaia-----gaegtgyakyaktmlllavsgs
rktk---asgrmk-vpatk---gcimwakreahrrpgwssvaavdtsllt
slcsesr-r--g----pnnpgr--------------vcvnqyt-----ga
tenaqaeekggvgiasqllkfsshshvfi---yadclfhdhfylkhlfh-
-pegqspalyirptpa---yrvalagiclqgifktkwt----lqvagkmg
ydeipfk-k-hvk---slqnktrvtd-----qrcgrhttag-depvar--
-psetaeahvtlvaalsiekaqlefcckrdddepkmcmgpnayphghdek
fnckvvdtqpa--d----srhekgpcapkvharacalqavvf--------
---nkleafllchspfgllfikamn---kpdeshfenagatgce-g----
----------lggeknyladyktvknflkncc-----riwvtshhdvqte
gfyhdlpksaspsarfqlcqvhl-cql
>node3
-sqplecadpkitkwgiaiaga-vhkalwklkpgpecyqkgeedqkerhq
rwaedhaakpkkdr--itchis-dlkyntnshfdysdgeaeqtvakdagg
e--aadtrgekaygelalvskit-----gaigts------tmlhlaasas
rgtk---atgrmr-vpttk---gcivwlqreakrr--wssiaesdtclmt
glcsasr-rshs----fyqlgr--------------vcinqyt-----ga
tesaqteqtggvsissqllkfsshahvfi---ysdslfhdhfylkhlfh-
-pegqvpalyiqptva---srhalagiclqklfktk-t----lqvvdnmq
ytedpfk-k-htr---slqnrtrvsd-----qrcgrhttpg-sepvsp--
-stdtaeadvspgtnlsiekaqldfcckrddnepsmckgpnvfphgndds
mnckvvntqvapkd----arhemspcspkvhlrtcaleavri--------
---gkietfmlcskpfgllfvkaln---ktddahfe---ptgcedg----
----------hggeenfdahyktvknflknccpwlnlriwvtsphdirye
gfyqglpkgnspsgryqlctvhl-cql
>node7
-sqplgcadpkiskwgiaiaga-vhkelwklkpgpecfvkgkedqkdrhq
qwakdhvakpkksr--itchls-nlkyntnsnfdysngeaeqavakdggn
eiltadnrgekaygelalvgkit-----gaigtg------tmlhlavsgs
rgtk---atgrmk-vpatk---gcimwlqreakrr--wssvaevdtgllt
glcsqsr-rahg----fynpgr--------------vcvnqyt-----ga
tesaqaeqkggvsissqllkfsshahvfi---ysdclfhdhfylkhlfh-
-pegqtpalyiqptpa---yrvalagiclqglfktk-t----lqvagkma
yaenpfk-k-hvk---slqnrtrvpd-----qrcgrhttpg-depvar--
-ptdtaeadvspganlsiekaqldfcckrddnepsmcmgpnayphgndes
lnckvvdtqpa--d----srhekgpcspkvharacaldavvf--------
---nkleafmlcnspfgllfvkaln---kpddshfe---ptgce-g----
----------hggeenylanyktvknflkncc-----riwvtshhdvqye
gfyqglpksnspsgryqlctvhl-cql
>node13
idqpvgctdnrvakwgiavaga-lhrdswkmnpgpeclvkgkekqtacnm
qwaadhvskpiks----actla-elkqdankhfeystseeqrvvakgggk
egl-adargekeygelal-------------gtg------vk--vavsg-
rgik---aigrltvlpttk---gciiwihgeakkq--wtgvaevdtallr
glcghss-kahtllygffnsgk--------------icvnhytakivggc
sdnnpneqksgdwrsqqnlkegsedfvll---ys--kfhn------lyq-
-aenq----yldsnad---yrvtiagicldglyktk-a----lqvaglfa
yapnqlkfq-rvk---slhqrtripdkrvsrercgrhtnga-eeptak--
-psdp--pnessggelrvapakftfcckgsdkeprmclgnnayprgtde-
---kiadtqpa--n----tkh--gpgsqkvqtricavn--aa--------
---dklea---rdspfgalflkspg---spedphfd---ptgce-gmedk
hglnadfllkqggeehyleyfgsvknllktcc-----rlwatshhdveye
gfyitlpdglapagayqlctihvscql
>E
vseplgcsepqvakwnaavasa-ihrqnwklnlggeclgkgkeeqtecng
nwatehdskppkg----acita-elkqnadkyfnfktstadrkvtkgdgn
-gf-aknvgekaygelgl-------------gtg------vm--vavlg-
--------isrltilpqakepdgcvvwlnraaskq--wtgiaevnnyllr
glcgqdr-kahslly---kvgr--------------tcvnhht-----nv
tdsahkdqnsagwrttdnlkygsedlgllktayg--mfhehgyl--fge-
-padq----ylkgtpd---yrvklaglclenlfkts-a----iqvaglma
ygvsqlkfq-hck---tlqnrsrkakrr----rcghytrki-qnpvek--
-apepggsgdqnlgelgiepakldfcckredsepsqctgsntyvkgsdea
lhckvsdaqpa--d----srh--gprspkvhtrlcqvdhtaaaepvglve
khkdkldlf--rnssigalflkalt---tpsnthye---pisyg-g----
----------qggeg--lanfgsvknflkasc------------hevqfe
gfydtlpkdlapagryqlckvhv-cql
>F
vheplgytdprtakwgvavaga-ftrqdwkld-gveclgkskeeqtecag
nwapehvrippkg----actla-elkqnadsyfafststadrtitkgdgd
egk-egnvgekaygelal-------------gtg------vm--vavlgr
rgik---aigrltvlpdakesdgcivwlgrasskq--wagpaevdnyllk
glcgqkr-kghsllygffkvcr--------------icvthnt-----nk
tesahneqksggwkskenlkfssedfdll---td--mfhehgyl--lysd
gpefq----yfdsrpd---yrvtlaglciqhlnkts-tpsylldvaglmp
yavnqlkfq-qvkldetlknraripdkr----rcgnytrkv-qnpaqk--
-apdpggsgdpslgelgiepaklefcckrdanepsrcmgsnaypkgtdea
lhckisdtqpt--n----srh--gptspevhskvcqvdttaa--------
---ekldaf--rddsfgalflksva---dpehthfe---gtgyg-g----
----------qkgegnylanfgavkkflknsc------------hevhye
gfydtipkglaasgryqlckvhv-cql
>G
idlpvgcvegrstkwgiavan---hkdswkmdpgeeclvkgke-qtgctm
qwaadhvskpvks----actla-elsqdarkhfdnsspeeervvaqsggk
egl-adargendygelal-------------dtg------vk--vpvsg-
rgmk---pigrltvlpgtk---gciiwihgeaqkq--wtgvaevdtallk
glcgrss-kahtllykffgagk--------------icvnhytakfvggc
sennpnnqksgdwrseqnlkqgsedfvll---ys--kfhh------lyt-
-aenq----yldsnad---yrvtiagkcid------------ldvaglfa
lapdqlkfq-rvk---alhqrtrvatsrvarercgq-------eptakgt
vpydp--pneksggdlrvasakftftctasenepklclg--acprgtde-
---kiaetepa--s----akh--gpgsqkvqtricavl--at--------
---dkrea---rdspfgalilkspg---spedphfd---ppgca-gleds
hgmnadfllkkggeqhyleyfgsvhkflktcc-----rlwatslkdieye
gffitlpdalepsgqyelctihvscql
>node15
-sqplgctdpriskwgiaiaga-ihrelwklkpgpeclvkgkedqtechq
qwakdhvskpkksr--iachla-nlkydtnsnfdystgeaeravakdggn
eglttdnrgekaygelaligklt-----gqvgtg------tm--lavsgt
rgtk---atgrltvvpatk---gcimwldreakrr--wsgvaevdtgllr
glcgqsr-kahglw--ffnsgr--------------icvnqyt-----aa
tenaqneqksgvwnssqnlkfsskafvll---yseclfhdhfyl--lyh-
-pegq----yinstpd---yrvtlagiclqglfktn-t----lqvagkma
yaenplk-q-hvk---tlqnrtrvpd-----qrcgrhttgg-eepvak--
-psdpaeanespggelpiepaeldfcckrsdnepsmcmgsnayphgndes
ldckivdtqpa--d----srh--gpsspkvhtricavnataf--------
---nkleafklrnspfgllflkaln---dpddshfe---ptgce-g----
----------qggeenylanfdsvknflktcc-----rlwvtshhevqye
gfyqalpksnapagryqlctvhl-cql
>node14
isqplgctdpriakwgiavaga-ihretwklnpgpeclvkgkeeqtecnq
qwaadhvskpkks----actla-elkqdankyfdystseaertvakgggn
egl-adnrgekaygelal-------------gtg------tm--vavsgp
rgik---aigrltvlpatk---gciiwlnreakkq--wsgvaevdtallr
glcgqsr-kahsllygffnsgr--------------icvnhyt-----gv
tdnaqneqksggwrskqnlkyssedfvll---ys--mfhdhfyl--lyh-
-pedq----yldstpd---yrvtlagiclqglfktn-t----lqvaglma
yavnqlkfq-hvk---tlqnrtripdkrvsrqrcgrhttga-eepvak--
-psdpagsnessggelpiepakldfcckrsdnepsmclgsnayprgtdea
lhckiadtqpa--d----srh--gpsspkvhtricavnataa--------
---dkleaf--rnspfgalflksls---dpedshfe---ptgce-g----
----------qggeenylanfgsvksflktcc-----rlwatshhevqye
gfyetlpkglapagryqlctvhv-cql
