>B
gsavdaklmdd-vllelnpff-----epgllkvlserssekgptehnals
frpgtdtkegtykslclnefgnya------he--rncskvwnvrlimkdf
rglhtplgfftee---kfvldtldgtnyvihsqlgvvkrymaptthlkks
wvqssvffrv-akyggegkcvagvslesgvvekggveivssadtvsidgd
tsaqlhntilatgtpatnflrrheaqyckagrnphnpalaenykqha-ta
qgaddclsvwkhtcpisqggpdkdesghnddvfgsfgtv-glkkp--nqy
sglpdkecftlvvslvypltgahltre-s--fvhsk-----ad----ykh
tanklnkvc----d----nfacrqdse-glssgks------ynf--l-sg
ntlsdsaeffd-------svrgesahgchnmpakrfvvlglnlyv-dre-
hthvsvl--hasghnpamsvmdvkear---------aplikyyshkrtvd
agqggg-----c-cesmlgqpc--isvqsi----dvyefvegdds---l-
v--r------easgdiv-tckgdavklrppv----vthgaledrt-qgl
>node13
qsavpanvkgnqallepnsyf-----dgvelrilretsketlpsqhttlt
lrasskvklgnykplslnela-yalqdlkkhd--rksskawnvrlikkaf
rglhlhlgnsape---akcletlakklfviaqalgvtkrlla--------
wtdscvfdrv-anyggdttgvagvtfdsgivqsqgvdargvvetfsregp
tnhslhatvfagntpgekff----a---adgadahenslsnkfehharta
-g----laiskhncplapmapdkgdnknnydifgtkthv-slkkp--dky
gcv-akdtlgltvtlkyplltvhqvse-nylvihsk-----dk----ykh
ttkklekic----n-ckekfackktke-gvnalsm------ykffslggg
galgdtfefykeq-----avgal---gcheaparrymslgladfv-akn-
esilavl--kssghaikngtkeelqas---------npvvnyylhkq---
--ngngfd-fca-cvsilgktcaviepgsi----evyhfaeqgdpvsilt
lagk------kaaviivrackag-nkaklpt-a--vq--plgdes-hgl
>node7
qsavsaklmed-allepnsyf-----dpgllkilketpsetgptehnals
frpssktrsgtykplclnefgdya------hg--rnsskvwnvrlvkkef
rglhlplgfwtee---afvldtlpgthfviasmlgvvkrymaptkhlkng
wvqscvffrv-tkyggetkcvagvtldsgvvekqgvevrssadtlsiegp
tshqlhstifagstpadkffrrhea---kdgrdshdpsltanyktha-ta
-gpdeclaiwkhncpvspggpdkdennhnddlygskstv-glkkp--nqy
sgapdkkcfaltvtlkypllnahlnre-sylavhsk-----ad----ykh
takkldkmc----d----kfacrddse-glsalss------ynf--legg
ntlgdtpeffk-------svpgm---gchdaharrfmtlgldlyv-dkd-
qtivpvl--hasghgitksvmdtkeas---------tplityyshkkamd
agdggg-----c-cvsmlgqscvvisvesi----evyeyaenadpvsil-
v--k------easgiiv-ackggiaklrlav----vh--aladet-qgl
>H
qssvaaavkgnqgllepnsyf-----egievrilreaskdtlpsrhltlt
lrhsskvklgnykplshnela-ynledglthe--rkgshawnaqlidkef
rnlhlhlgnsape---atileklakklfvvaqalgvskrlla--------
wtdssvfgkv-anyggdttsiaggtfaagitqsqgvgargvvetfsrdgp
tnhslhatvfrgnapgekff----a---adgadahehslthkferharpa
-g----laiskhncalahmapdagdnknrydlfgskthv-slkkpvkdky
gcv-skdtlgltvtlkyklltvhqvse-nylvvhsk-----dk----ykh
atkrlenickafvn-crekfackntke-gvnalsm------ykffslggg
gvlgdtfeftkeq-----avgal---gcldmparrymslgladfv-akne
dsilavl--kssthgikkgtkeelqas---------npvvnfyihrq---
--ngnrfdsfca-cvammgkvcsliepgsi----dvyhfaeqedpvaiqt
lagk------kaniiivrackag-nkaklps-a--ap--plgdek-fga
>node14
qsavpanikgn-allepnsyf-----dpvelrilketpketlpsehtalt
frpssktrlgnykplslnela-yalqdlkkhd--rksskswnvrlikkef
rglhlhlgfstee---akcldtlgktlfviaqalgvakrlmaptthhksa
wttscvfhrv-tkyggdtksvagvtfdsgivepqgvevrsavetfsregp
snhslhatvfagstpgekff----a---adgadahenslspkykhharta
-g----laiwkhncalgpgapdkddnkhsddifgtkahv-slkkp--dqy
gcv-dkdsigltvtlkypllnvhqnre-nylvihsk-----ad----ykh
takkldkmc----n-ckekfackkake-gvsalsm------hkffnlegg
galgdtseffkeq-----avnam---gcheapsrkymslgladfv-akn-
qsilavl--kssghaiknsnkdeleas---------splvnyyshkq---
--ngngfd-fca-cvsilgqscaviepdsi----evyefaeqadpvtilt
vggk------naagiivrackag-nkaklat-a--vh--plgdet-hgl
>node15
qsavsakimed-allepnsyf-----dpvdlrilketpsetlpsehtalt
frpssktrsgnykplslneigdyalhdlkkhd--rnsskvwnvrlvkkef
rglhlplgfwtee---amildtlggtlfviasmlgvvkrfmaptkhlkng
wvtscvffrv-tkyggetkcvagvtfdsgvvepqgvevrsavetfsiegp
snhslhstifagstpgdkff----a---kdgrdshdssltpnyksharta
-gpneclaiwkhncpvspggpdkdenkhsddilgskssv-slkkp--nqy
navpdkdcfaltvtlkypllnvhqnre-sylvvhsk-----ad----ykh
takkldkmc----n-ckekfacrkase-glsalsa------ykf--legg
gtlgdtseffken-----avpgm---gchdaharrymslglnvyv-ekn-
qtilavl--kssghgitnsskdereas---------aplityyshkk---
--dggg-----s-cvsilgqscvvisvesi----evyeyaenadpvtil-
vggk------naagiiv-acksg-nklrlai----vh--pladet-qgl
>C
qravsgkllee-allepnsyf-----dpallkilkelrsatapietealn
hrptsktrngtykplclnefgdya------yg--ghsakiwd--------
--------fwtehfnrpfvldtl--thfmiesklgvvnrymapvkhlkkg
wqatcvyvrv-tkyggeskcvvgctlstgvqekqgtevksgpntlsvegp
sshqlhsqvfagstpvdkafrr--k---kdgrdahdrsltanyrthg-ca
-gadgcvaiwkhncpvgpggpdreesnhsngaytskstv-gl--------
--askkkcfaltvtlewrllnahlare-syaavhsk-----ad-------
-akkfeklc----d----kfgckdeie-sd-------------f--ldga
nslgdapdffk--kavsesvpgv---gchdlhsrrfktigldyyvagmd-
qtvvpvl--hlsgysitkmvmsssess---------iplvtyyphkkakd
sgdggg-----cgsvallgqgcamvsvdsi----qvyeyaenaipvsvl-
v--g------ensgimv-sckagidklkvav----ih--asadgt-egl
>A
nravsaklmdd-allqpnpyf-----dpgllkilketgsetgptehkgls
frpgsdtksgdynglvlnkfgsna-------s--rncsavwdvrlikkdf
rglhlplsfwkee---kfvldalsgtnyvihsmlgvvkrykaptkhlksg
wvssevffrv-tsyggeskcvagvtletgvaek----vkssadtlaiegd
tsnqlhkaildtltpatkflrrhdg---kdgrnsntpaltenykeha-tg
qgpdecvsiwrhncpiapggpakqedghsdavygskssv-glkkp--nqc
sgapdaesltlvvssayplagahltke-sylavhar-----ad----ykh
tehklnkvc----n----nfacreege-glsalks------ynf--le-g
nglgdsaeffd-------svnae---gchdahakrfmvlgidlya-dre-
ptivpvl--hasghratmsvmdvkeaa---------aplityyshmkavd
agqgkp-----c-cvsmlgqpc--isvesi----dlyqfvegqds---l-
v--r------eakgiiv-tckgdgaklriat--fivt--gladet-qgl
>G
qsadpatvkglasllepnsyf-----dgvelrilretsketipskhttlt
lrasskvklgnykplelnela-ygleelnmhn--rkskkawnv-------
ltlhqhldnsape---dtcletlnkklfviaqalgvtkrlla--------
wtdacvfdrv-anygsdtasvagvtfdsgvvqsqdvdargvvetfrregp
gnhslhatvfpgntnsekff----a---ldsedahqnslankfehharka
-g----laiskhnc-lapmppdkgdnknnydifgtkahl-nlkkp--dky
gcv-akntlgltgtlkyplltvhqvse-nyqvihgk-----dk----yth
takklqkvc----n-cqskfsctklkq-gvkqlsm------ynffglsgg
galgdtfefykeq-----avga------qeaparrymslglaefv-aks-
gsilavl--ksvghavkngtkeelkas---------gpthnfylhkq---
--ngngfd-fca-cvgmlgstctvidpasi----svyhfaeqgdpvsvlt
lagk------rlaviivrtchag-nkaklat-a--vq--plgdes-pgl
>node10
qwagpvsikgn-vllepnsyf-----dpvdllilkdapaeglpsehtalt
f--------gaykplslgela-yglpeakksd--rksskafnvrllkkef
rglhlhlgfstee---akclntlgrtlfvipqvlgvvkslmsptthhksp
wttscvfhrvstkfggdtksvagvtfdsgivepqglevrsavdtfnpegp
snhslratvfagsnpgekff----a---adgadehenilapkyrhharta
-g----laiwkhscaigpgapdkddnkhsddifatkahv-slkkp--nqy
gcv-vkdsigltmalkypllnvhhnreadylvtqgk-----dk----ykn
takkldklc----n-ckpkfdckkske-gvmalam------hkfynlegg
gtngdtsaffkeq-----alnam---gcheaktrkymslgladfv-akk-
qsiwavl--kssghaik-snkdqlnav---------splvnyynhkq---
--dgngfd-fct-cvsilgqscaviepdsi----evyefseqgapvttlt
vggk------naagiivrackag-nkaklat-a--vh--algnetdhgl
>F
qwpdpvsskgn-vli-----faikmtapvsllilkqapadglpsehlalt
i--------gslkplslgdla-y--pearksd--rkgsaafnvrlvktdy
rglhlnlgfstea---gkcldtlgrtlfviaqvlgvvkslmavtshhkga
wtttcvfhrvstkfggqtksitgvafdsgivepqgldvsravdtfnpegp
gnhslrat-fagsnpeeklr----a---addadehenilapkyqqharta
-g----lagwkhscaigpgtrdkdankhsgalftikahvtslkkp--nqy
gch-vkdsisltmalkypllnvhhhreadylisqak-----dshgvcdkn
tekkkeklc----t-skpkfdckkske-gvmalamtyvlqthkfynlege
gtnketslffkeq-----alnam---gcheaktrkymslglsdfv-akk-
qrvwailqkkssgqavk-snksqvnna---------splvsyyntkm---
--s------fct-cvslvgqscaviepdsi----evyefveqgapvtvlt
vggnslekiniaagiiirackpg-nkaklat-t--vh--algneqdhgl
>node3
nsavsaklmdd-allepnpyf-----dpgllkilketssetgptehnals
frpgsdtksgtykslclnefgdya------hg--rncskvwnvrlikkdf
rglhlplgfwtee---kfvldalsgtnyvihsmlgvvkrymaptkhlkns
wvqssvffrv-tkyggeskcvagvtlesgvveksgvevrssadtlsidgd
tshqlhstilatstpatkflrrhea---kdgrnshnpaltenykeha-ta
qgpddcvsiwrhncpispggpdkqenghnddvygskstv-glkkp--nqy
sgapdkecftlvvslvypltgahltre-sylavhsk-----ad----ykh
tanklnkvc----d----nfacredse-glsalks------ynf--lesg
ntlgdsaeffd-------svpge---gchdahakrfmvlgldlyv-dre-
qtivpvl--hasghgtsmsvmdvkear---------aplityyshkkavd
agqggg-----c-cvsmlgqpc--isvesi----evyefvegdds---l-
v--r------easgiiv-tckgdaaklriat----vn--aladet-qgl
>node6
qravsskllee-allepnsyf-----dpallkilkelrsetgpiehealn
frpssktrsgtykplclnefgdya------hg--gnsakvwn--------
--------fwtehfdrafvldtl--thfviasklgvvnrymaptkhlkkg
wqatcvfvrv-tkyggeskcvvgrtldsgvqekqggevksnpntlsiegp
sshqlhstifagstpadkafrr--k---kdgrdahdrsltanyrtha-ta
-gadgclaiwkhncpvgpggpdreennhsnelygskstv-gl--------
--apkkkcfaltvtlewpllnahlare-syaavhsk-----ad-------
-akklekmc----d----kfackedse-sd-------------f--ldgg
dtlgdapdffk-------svpgm---gchdvhsrrfmtigldlyv-gmd-
qtivpvl--hlsghsitksvmdsteas---------tplityyphkkakd
agdggg-----c-cvtllgqgctmvsvesi----evyeyaenaipvsvl-
v--g------edsgimv-sckggidklrlav----ih--aladgt-egl
>E
qwagpnsvkgn-iylepnsff-----dpvdlliikdtraeglpsehtalt
f--------gaymklslaela-yglaeakksdawrrsskafnvrllkeaf
rgldlhlgftpee---akcllnlgrtlfvapevlgvvktlmsptthrqsa
---scvrhklsdkfgnanksvagvtfvsgivepqglpvrsavetfnpggp
anhslratvfagsnpgekfv----a---sdgadehehilapkyrfharta
-g----lqiwkhscaigpgatdrddpkhsdqifgtkahv-slkkp--aqy
gcv-vkdsialamafafplfnvhhsrhadyvithgkgdialdk----ykd
tdrkldklc----nnckpkfdckkhke-gvmalkm------hkfynlegg
gthgdtstffkqq-----alnam---gcheaktkkyislglanii-akk-
qniwavl--kcsgh-vk-anktqlnavlqlepeqqlsplvnyynhkq---
--egpgfd-fct-cvsligqpcaviepdkikgdvevyefaeqgapvttit
vggk------nasgiiarvctat-hkgklptq----h--glgnetdhgl
>D
qravaskllee-alldpnsyf-----dpa--rilkelkaetgpiereals
frpssktrsvtykplclneygaya------hg--gssakvwn--------
--------fftehfdrpyaldtl--thfvvasklgsvtrymapskhlkkg
wqatcvfvrv-tkyggeskcvvgktldsglqekqggevksdpntlsiegp
sghqlhstifggstpadkafrr--k---kngrdahdrslsanyrtha-ta
-gsdg------hncpvgpggpsreesnhgnelygckstv-gl--------
--spkakcfsltvtnewplldarlare-syaavrkk-----ad-------
-ardlekmc----d----kfacaedsggsd-------------f--ldgg
dtlgeapdffk-------nvpgm---gckdvhsrkfmtiglnlyv-gmd-
ativpvl--hlsghsitrsiidanea------------liay------kd
tsdggg-----c-catllgqgctmvfieni----eayeyaelvipvsvl-
v--g------qdtgllv-acrggidklrlav----ih--alsdgt-egl
