>node15
tpispvts----atvdvrvnfkaltkrctddvyrfcaqsga--------g
egkehs---gfqavc-taggg-ingdagqtdy-----vkvvgksyvyrs-
-------h-----krq-lch--dvhacfigavegas--ds--smgicrlq
valgwlvhslkgnrvpsefelagylaaphasp---------f-lpd---k
kaaffnskqpgvkqhfaa--tegpyigsapagsvrgfhagcenfeetcsp
ivigldemsdvqhrrkcfkeyhvmgkvgacrlgrvcmv----llcnvkpl
qqecqdllk--wgr-cl-kvnlektlflvkgattaslggpthaptgihrv
hehellgln--meavattfllevpvl--vkynrrre--------g---gg
pshnvye------s-wggppndvrdasakcapiqtg----f---------
-ead--pdktslktdstnqliav-v---hledl-flvdikkln----evh
naak---vkcsa-------atdsavrtgvgdsgdfpg-e-dseavd-vkd
frlfalvtkc---cagld---pdg------kevmahltdvynhgpgtcgv
cvacvsilftennql-----------------gg--iagfaalfasfger
ds--klla
>node10
epiapves----avvdlrsrfkleskkctddvyrfcaqssv--------g
ngdeha---gfqavc-tvggg-ingnagktny-----vkvvgkrysyrs-
-------h-----krh-lchskgvhacfigavqfas--dg--akgecrlq
ialgwlvhslrggrvpksfelacylvasnpip---------v-lphagas
rqgffnksqpgikqafga--segpymvsppvglargvhpgcanyeetcsp
ivigldeisnvqhkrscfkqyhves-----rlgkvciv----llcnvrpl
hqrcqdemk--wgn-cl-kih----------ssaaalggptdaptgkhrv
nqndlmglh--miavantfllevplm--vkynirrerlkhnqhkg---gg
tihgvygapqpdty-wdgppadiddas-kcapiqkg----f---------
-eadag-ditslkvesndhligi-a---hlqel-fvvaikkln----evh
dpar---v------------t-----vgvgssgdfsdre-nmeav--ake
frlfllatkc---cagle---pdn------kevmsvltgiynhgpgtcgi
cvaclsil------l-----------------agi-iagfpplfasfger
qs--kllg
>A
tqvsaisa----lgvnir-slkvlakrctsnvyrfcsqdatgagkcvdtg
dgdens---gfeavcsimgtg-iksdkgptai------kvvgisyvyrc-
-------qdvahakrq-lch--gahacfigtv--aepnd--------rle
valgwiihnlkvdrepsefqivgylatpieda---------f-vsp---k
kthffkhdppdckdklct--tdgpyvtnepeanaigfhascnnfedaseq
ivigeddmkgtqnkrkcfgeyhv--kggastlprramvesasllccvyqf
pkecqellk--wgraclskvnlnktlyivkgvtgssyggpsr---gvhki
hehelallh--maasattfifnvpvleaipfhrrqa--------geplgk
kshslye------aiw--ptndardvsrrcgpiqtg----i---------
-pag--pvknsmrtqgtnnlahv-e---hlsalsnmedmkkltt---evh
tetkwtyvkcavfyglknaaedsavrsglgeygnfag-d-hseavd-ikd
yklfilat----tcatpn---png------reavdalaavydlgpgscgv
cvacvtilfvqnnqv-----------------gg--itafgsifastgdr
qa--kllh
>node6
tqisaisc----lsvdvrvhlnvltkrcsndcyrfvavsga--------n
egeqhs---gfkavc-tagag-ikgdsaqtti-----vkvmgksyvfhc-
-------hsaahavrq-lch--dvhgcfigrvqgrd--dq--slgvvrlp
valgwlvhnlkgnrvsskfelagylstphaga---------f-lpt---k
kayffngvapsvknnfcs--tdgpyvgsepeasvigfhagcenfeetrar
evigldemtdaqhrrkcfkeyhvlgklgacrlgrrcmv----llcyvyql
kkecqevl----gracl-kvnqnrtlflvkgvttasiggptreaa----v
hahnllgln--masvaptfvlevpvlaavkyrkrke--------g---gg
pyhklye------s-wglppndvrdasarcgpfqts----f---------
-pad--pgktslktesgnilkdvvewkeeledlgalvditkitvvhgevh
aqvk---vk----yglrsgah-savrngvgeygdfpg-d-hseavd-vtd
yrpfslvtkcyptcasln---png------revma-ltdiykkssntcni
cvgcvsvlfrqknql-----------------gg--itafgtlfssfner
qndaklln
>node13
epvapves----avvnvrspfeastkrctddvfrfctqsaa--------g
egtehsp--gfqavc-taggp-lngnagqtny------kvvgksysyrs-
-------h-----krr-lch--dvhacfigcvefas-------mgvcrlq
valgwlvhsqkgnrvpkefqlacylvapnatp---------v-lph---s
kagffdkaqpgvnqsfga--aegpymgspps-lvrgvhagcevytdtcsp
iatgldeissvhhsiecfkdyqvdgttgacrlekvcns----llcnvgpm
kqqcqdlin--wgn-cl-gid----------sstavlggptnaptgkhrv
nqhelfgln--meavattflltvpll--vkytrrre--------g---gg
sshgvyg------y-wdsppndireas-kcapikkg----f---------
-eadtggkitflkvetnn-llgi-g---hleel-fvvnimkln----tvh
npat---vtcka-------ttdpsvrvgvgesgdfpgre-kveavevvkn
trlfalvtkc---cavld---pdn------devmahltgiynhgpgtcgi
cmacvsil------l-----------------gg--iagfpplfasfger
ds--kllg
>G
eavapves----evvnvqssrlantkrctddvfhfctqsaa--------g
gstthgpnegfqaac-tdggpslsgnsnlt---------vvgkkykyrn-
-------h-----krr-lch--dvhacfigcvefaa-------mglcrlq
valswlvhsqkgnrvpkefqlacylgapnatp---------v-vph---s
qagffdkaqpgvvqpfga--gegaymksppg-lvrgvhggcevttetcsp
iatsldeie--ahsiecfkvyqvdgangacrlttvvss----llcnvgpm
kqqcqdlin--wgn-cl-gid----------sstavlggpttapigkhrv
nqhelfgln--meavattfllt-------kytrrre--------g---gg
sshgvyg------y-wdspvndireas-kcapikrg----feprsshqvk
navdtggsvtylkvetnn-l------------l------lkln----svp
naaa---vtcka-------tkqpavrvgvgesgdfpgle-kveavevvkn
trlfplvtkc---cnvle---pdn------devmahltgyynnspgtcgi
cmacvsil------l-----------------gg--iagfpplfanfger
es--klmg
>H
dpvapvdt----avvnvrspfeastkrctddvfrfctq-fs--------g
egtehsp--gfeavc-taggp-ltgnggqtky------kvvgksysyrs-
-------h-----krr-lch--dlhvcyiscvefas-------mghcrlq
vplgwlvhsqkgnraikefqlncylvsptatp---------illhh---s
kagffdkaqpvvgqsfga--aegpylgspps-lvrgvhspcevyndtcgp
igtglddissvhhgiecfkdyqvdgttgacklekvcng----lfcnvapm
kkqcqdlin--wgn-cl-gid----------astavldgptnartgkhrv
hqhelfgls--meavattllisvpll--vkytrrre--------g---gs
sshg-yg------y-wdappndtrqas-ncapikgg----f---------
-evdaggkitflkcetns-lqgt-g---yaeal-fvvnimtln----tth
npat---vtcka-------ttdpsvrvgvgesgdfpakeskvgaaevvkn
srlfslvtkc---yavmd---pdn------s-vmahttgiynhgtgtcgv
ckgctsil------l-----------------gg--vagfpplfatfser
ds--kllg
>node3
thisavss----lgvdir-slkvltkrctsnvyrfcsqnatgagrcadtg
egeens---gfeavcsiagtg-iksdkgptai------kvvgksyvyrc-
-------qsvahakrq-lch--dvhacfigtv--adpndslmslgvcrla
valgwivhnlkvnrepsefelagylatpheda---------f-lpt---k
kayffksntpgckdkfca--tdgpyvtnepeasaigfhascnnfedtsar
ivigeddmkgaqhrrkcfgeyhvlgkigactlgrrcmv----llcyvyqf
pkecqellk--wgraclskvnlnktlylvkgvttasiggptr---gihki
hehdlllln--maavattfilnvpvleainfhrrqe--------geplgs
pshnlye------siwgsptndardvsmrcgpiqtg----i---------
-pag--paknsmktqstnnlihv-e---hlsdlgsladmkkltt---evh
tqvk---vrctvfyglkngandsavrsglgeygnfag-d-hseavd-vkd
yklfilat----tcatqd---png------reamnaladvynlgpgscgv
ciacvtilfvqdnqv-----------------gg--itafgtifastgdr
qa--kllq
>D
tpitaiac----lsvdvrvhlnvltescsnncf--vaisgs--------n
egeqhs---gfkavc-sagag-ikgdsaptti-----vkvlgksyvfhc-
-------hsaahavrq-lch--dvhgcfkgrvfsrd--dq--slgvvrlp
aalgrlghnlkgnrvsskfal----stphaga---------f-mpt---k
kayffqgvaasvtnnfcsyktdgpfvggepeasvigfhagceqfeetrar
evigldemtdashrrksfrey-----lgacklgkrcmv-----lcyvyql
kkdcqevl----gracl-kvnqnrtlfmvkgvtsasiggetreat----a
hahsllglnaemknvaptfvlevpvldavkyhmrke--------g---gg
pyhklye------t-wglppngirdtsarcgpfdts----f---------
-pad--pgktglktesgnilkdvvewkeeledlgalidisritvvkgevp
aevk---vr----falragah-gavrnavgqygdlpg-d-hsaava-vta
yqsfslvtscyptcasln---pkg------revla-ltdiakkasntcni
ctgcasvflrqknql-----------------gg--iaafgvlfssfnsr
qadfklld
>E
qpiafvet----aivdlisrfkleskkcqd----fcsqasv--------s
dgdaha---sfqaac-tvggg-tnanmgktnygrgltv-----rysyrk-
-------h-----krh-lchskgvhscfigsvqfas--dg--akgecrlq
ialgw------ggrtpksfdlacylvatnpipg--------v-lpqsgas
rqgqfnksqpgikqafga--tegeymvsppvg--rgvhpgcanyeetcsp
ivigldeisnvqhlrscfkdyhvds-----rlgkvcnv----llcqvrkl
hqrcrdemk--wgn-sl-nih----------sstaelggkrdaptgkhrv
eqtdlmglh--miaaantfllevplm--ctynirrkslrhnqhkg---gg
tihsvygapqpety-wdgppgdiddas-kcapiqkg----f---------
-etddg-ditslkaenndhilgi-a---hlqel-yvvavrkln----evh
dpar---v------------t-----vgvgssgdfstre-emdav--atd
frefllatkc---cagleagkpen------kevmsyltgcykhgpgtcgi
cvaclsil------lgdesktglavfkmsw--agi-vagfsplfasfger
qs--kilg
>F
dpiapves----avvdlrsrfhleskkctddvyrisaqspi--------g
agdeqa---vfqtvc-tvggg-vsanagktry-----vktvkkrysyrs-
-------h-----krpplnhskgihacfigtvqfas--ga--akgecrlk
idlewlvhglrggrvpvsfelaiylvatdpip---------v-lphtgtt
rqgffnksqpgikqafga--segpymvshkvglaravhpgcgdyddacsp
ivvglaeianvqhkrscfkqyhvet-----rlgkmcii----lvsnirpl
rqrcqdilkggwgn-ci-kih----------asaaalggptdapagkhrv
dqndlgglh--mienanafllevpll--vkyiicrerl----hng---gk
tihgvygapqpddy-wdnppadisdas-kcaafqtg----f---------
-tgd---ditslkvassdhligi-a---hasel-fvvailkln----dvh
dpar---v------------p-----vgvgtsgdfsdre-nmegv--aee
frlfplaskc---caale---pdtkkqsvfkevmsvlaglfnhgpgycgi
cvacltil------n-----------------asfailgypalfasfger
q-------
>node7
thisavss----lsvdvrvnlkvltkrctndvyrfcaqsga--------g
egeehs---gfsavc-tagag-ikgdsgqtsi-----ikvvgksyvyrc-
-------hsaahakrq-lch--dvhacfigsvegad--ds--slgvcrlp
valgwlvhnlkgnrvpsefelagylatphada---------f-lpt---k
kayffnsnapgvkdnfca--tdgpyvgnepeasvigfhagcenfeetsar
ivigldemsdaqhrrkcfkeyhvlgkigacrlgrrcmv----llcyvyql
pkecqellk--wgracl-kvnlnktlflvkgvttasiggptrapsgihkv
hehnllgln--maavattfvlevpvleaikynrrre--------g---gg
pshnlye------s-wgsptndvrdasarcgpiqtg----f---------
-pad--pgktslktesknnliav-e---hledlgalvdikkltt---evh
aqvk---vkcsvfyglksgandsavrsgvgeygnfpg-e-hseavd-vkd
yrlfilvtkc--tcasld---png------revmahltdvynhgpgtcgv
cvgcvsilftqnnqv-----------------gg--itafgtlftsfger
qs--klln
>node14
epiapves----avvdvrshfkaptkrctddvyrfcaqsav--------g
egtehs---gfqavc-taggg-ingnagqtny-----vkvvgksysyrs-
-------h-----krq-lch--dvhacfigavefas--dg--smgicrlq
valgwlvhslkgnrvpkefelacylvapnatp---------v-lph---s
kagffnkaqpgvkqhfga--aegpymgsppsglvrgvhagcenyedtcsp
ivigldeisnvhhkrdcfkdyhvegttgacrlgkvciv----llcnvkpm
qqqcqdllk--wgn-cl-kin----------sstaalggpthaptgkhrv
nqhellgln--meavattflldvpll--vkynrrre--------g---gg
pshgvyg------y-wdgppndirdas-kcapiqkg----f---------
-eadagaditslkvesnnqligi-a---hleel-fvvdikkln----evh
npak---vtcsa-------ttdpsvrvgvgesgdfpgre-nveaveavke
frlfalvtkc---cagle---pdn------kevmahltgiynhgpgtcgi
cvacvsil------l-----------------gg--iagfpplfasfger
ds--kllg
>B
thitavsg----lgveir-slkvltkrctanvyrfisanvtgagrcaddg
egeens---sfegvcsiagtg-ik----psal------kvvgksyvyrcc
fyvligvqsvahakrq-lph--glqacfigtv--tdpdqslmslgvckla
valgwivhnlkvsrepsefelsgylvtaheda---------y-lpk---k
kayffksntpgckhtfca--tdgpyvtnepeasaigfhascknfedttar
ivvgeddmkgaqhrtkcfgdyqllgkvgactlgrrcgv----llcyvyqf
pkecqellt--wgrscvskvnlsktlylvkgvttasfggptq---gihki
hehnllllk--maavattfilnvpvleainfhrrqe--------geplgs
pshnlte------siwgtptndaqdlsmrcgpiqtggckti---------
-peg--paknrmktlstnylihv-e---sls------amkmltt---evv
thvk---vrctvsygskngsndstvrsglgey-nfag-----eavd-vkd
ykpfilaa----tcatqd---png------regknalgdvydlgpgginv
siacvtvlfvqgnqi---------------lygg--itafgtifastgna
ea--kllq
>C
tqvnaiscgfkvlsvdmrppldvltkrcsndcyrfvavsge--------n
eggqhs---afkavc-ts-------dsaqtti-----vkvmgkryvfhc-
-------hsaahavrh-lch--dlhvcyegrvqvrd--dq--slvvvrlp
valgwlvhrlkgnkvsckfelagylstphgga-chgwqqdqf-lpt---k
kayfynnvaasvknnfcs--tn---vgidpeasvisfhagcsnfeetsar
eviaidgmsdaqnrrkcvkeyhflgklgac----rcmv----llcyvyql
kkdcqevl----grgcl-rvnknrtlflvkgtttasvggpsrsaa----v
hahnalgls--mmsvapsfhlevsvlavvkyrkrke--------g---gg
eyhklyd------s-wglppnnikdasarcgpfqgs----f---------
-ppd--agktdlktdsgnimkdvvewkeifedlgalpdvtkesvahgevh
tqkk---vk----yflrsgrh-savrngvgaygefpg-d-hsdavd-vkd
yrpfslvtksyptcasln---png------rlvma-ltdiyhkasnacna
cvgcv--lfrqknql-----------------dg--itdfgtlfscfneg
mggpklln
