>node14
ktc--hllwapngge-ffinsandldg---gipyrtlkdmpyystisksa
ggifw------tstykgtcsihsrtakmgedwsv-glqitkh--f-hikq
f-----gggiacytipkaikkgngtvmksrtkrtqpgdg-------wlkr
gkgcgylltrivavhndfagahpkk---rs--kfs--ralqpdypfglf-
ikelfgygvsrdcesgtirstllrvl-helhqtlmfaatagvnfgdg--p
vkanqilecakt-pqtfnaqsgkkdfn-----vphdiegal---acslie
vl-------vaavlsnsargfergle-ateftarpcsekkglrhte----
--ilk-alaptgelctcmvpllivywdlvlappksmtvlfpwsekenkey
qyd----t-------avesagaqdqyaisyvkaqfr--------epgkap
gknrsq----apddegdfngryhvsqallkn-----kgdvctvvvtgelk
snkfkgeelalkptravkli---gk----------lyvafgllkhncqll
---------wtiltgle-----spak-------llplggtsdc-----yi
tgvvhdgaayakkaafyrs-lpdp------ns----tvmvktwflnescg
>node3
akc--hlmwvpngge-sfitsssklng---nnpykrlkdmsyyntisgat
tgffwfafsyntstykstceahsrttdm-mdral-nrqitk------vkq
f-----lggiacysvpvaikkgdgl--kshtkrtmkgegydgkcsgwvrt
gkmcayllqkivsvnnefene-pkk---sr--kfk--ralepnyafgff-
vkelfryg--rdceagtirttvlkvl-helrknvifatsa---fgsdkyp
ikanqinncqkt-tqtfsackgldalp-----vehecnagl---gcslle
ilhyqmhpiflrwlkncahsihrg------fytrpcsnkkglrhtd----
--ipm-qlptagelcacmvplliiywdl-lftpkpmtllfpwgnkdktey
qfd----tsvgrl-kgpagmgaqeeylvdyvktqlr--------e-----
-kgksq----apddqgdangriavpnavaknkpgrqkgdvptvavageln
sdryegkeltlkptr---ii---gklkgmstglvklyvafsllkdtcqfl
---------wtiligla-----aiamygid---llplggs---dssnqyv
ngvvhtgaaytekptfyrs-l---------------gvmvdklfldescg
>F
kkc--qalwtatgge-ffiesnadldg---gtpyrklkdmtyystisrdf
ggafr------tttyrgacsihyrfailgddwnv-glqrikh--f-lvtq
f-----gggaacytdpktikkgkgtvmksttkrtqpgeg-------wakr
gqgcgffltkivavpndfagthpkr---ks--kfs--walqpaypnglf-
inelfgygssrdpesgtlrsnllrvl-qeihqtlmfpatadikfgng--p
------ldckkt-thnyngqsgkaefd-----tpndihg------cqlie
vl-------laailkhkangfeegleaakeytaqpcsekkgllhtd----
--iml-aliatgqlracnvplvivywkvalvppkalavlipr--kenkey
qydctltt-------avekagpqdqyaisnvyaq-r--------epgkap
srsnsq----apdsegdfhgryhvsqkllkn-----kgdvcttvvtgelk
snknd-e--alkptravklv---vk----------lyvafrllkhncqls
---------wtilialdtygmnspvk-------llplavtst--------
t----nkaayskkaafyrs-lkdp------gs----svmvktwflnqscg
>node6
hkc--hllwlpsgde-sfitastkvhg---nipyrllkdmsyynkisgat
tgffwfafaynastfkstvdahtksvkm-edraldslditk------ikq
f-----lggiacytvpvn---gdgt--tahtkrtkkgdgydgkcagwirr
gkmcafllqrivavnnemdne-pkq---hr--qfn--raleagytfgyf-
ykelfayg--rdcesgtistsvvkvmyhilrkallfatrs---fgne--p
lkasqilgcqkt-pqtfsacs-----p-----vsheinagl---pcslld
vlhwqmrpvflrmlakcargfqrg---ptefytqacsekkglrhne----
--itk-qlppagelctcmvplqiinwdlvlyppkpstllfpwgekdktey
qfk----tsvgql-kapsnmgaqeeylvvylktqlq--------e-----
-knksq----apddegdfngrytvpeavekn-----kgdvctvavigeln
sdkregkelalkdka---livlagslevmstglsrlyvafsliggecqll
---------wtiiigla-----aiam-------lvplggt---arsneyi
igvvhagaaytetanfyks-l---------------tvmvkmwfldescg
>node13
kec--hllwapggge-ffvnsandlsg---gipfrnlknmpyypsmsksy
ggifw------tatykgtcsvhsrsakmgedwsv-glqitkh--v-hikq
y-----gggiecytipkavkkgngtvmksrtkrtqpgdg-------wltr
gkgcgylvtrvtavhnefagyhprk---rt--kfs--ralqpdypfglf-
vkelfgygtgrdcepgtiretllrvl-hnlhqalmfaattgvefgdd--p
vkankiiecaktipktfeqqtgkknfnlvcksvphdiegal---acelie
vl-------vaavlsntargfergle-ateftsrpcse-kglrhte----
--ilk-alapagelctcvipmlivywdlvlappkpmtllfpwsekenkdy
qyn----t-------avesagnqsqyaiscvkagfrgtekvihddpgkap
ekkrgk----apddegsfnsryhvsdallkn-----kgavctvlvtgeik
snkfkgeeltlketravkli---gk----------lyvaygllkhncqll
hrcggvvqdwtiltgle-----spak-------llplggtsec-----yi
tevvhdgnayakr-sfyrs-lpdplipsnhns----tvlvktwylnescg
>node15
kkc--hllwapngge-ffitsaskldg---gipyrtlkdmpyystisgsa
tgifwfafayntntykgtcdahsrtakmgedrav-glqitkh--f-hikq
f-----gggiacysvpkaikkgdgt--kshtkrtkagdg-------wlkr
gkgcaylltrivavnndfgga-pkk---qa--kfs--ralqpdytfglf-
ikelfgygvprdcesgtirttmlkvl-helratlmfaasa---fgtd--p
vkanqilgcqkt-pqtfsacsgkndfp-----vphqidgal---acslie
vlhyemrpviaavlpnsargfqrg---atefyarpcsekkglrhte----
--ipk-qlaptgelctcmvpllivywdlvlyppksmtllfpwgekenkey
qfd----t-------aaesigaqdqylinyvkvqlr--------e-----
-knksq----apddegdfngrynvpeallkn-----kgdvctvavtgelk
snkfegqelalkptrgikli---gk----------lyvafgllkhncqll
---------wtiltgle-----aiak-------llplggt--------yi
tgivhagaayakkaafyrs-l---------------tvmvkkwfldescg
>B
akv--hlmwgpggge-sfmtsssnldg---n--ykrfkdmsyyntisgat
tgffwfafsyntstyksnceahsraadm-mnral-nraitk------vkq
f-----lggiacylvpvaltsgdvl--kshikrtlkskgydgacsgwvkt
gkkcaylllkvvgvnnefeke-p-kgpfsrdpkfk--raidpnysfgff-
vkelfrfg--rnieedtifatvlkvl-helkesvifatsa---fasdkyp
ikaseirkcqrt-tqaftackdndalp-----veqdcnagl---gcslld
ivhyqmnpiflrwlkncahtarrg------fykrpcsnrkglrntd----
--ipv-qlgtagelca------iiywdl-lftpdpmallfpwgnkdktey
qfd----tttgrl-kgpagmgaqeeflvdyvktqlr--------e-----
-kgkkqndsq-pddqgdengkiavpnavaknkpgrhkgdvptaevadein
sdryegreltltair---ii---gklkgmstslvklyvafsflkdtskfl
---------wtiligla-----afamygidgagllplgss---dasvqyv
ngvghtgaaytekatfyrstl---------------ggmvdklfldescg
>node10
ktc--hllwtptgge-ffinsandldg---gtpyralkdmtyystisrsf
ggifw------tttykgacsihnrtaklgddwnv-glqitkh--f-lvkq
f-----gggiacytkpkaikkgkgtvmksmtkrtqpgeg-------wakr
gqgcgylltrivavhndfagthpkr---ks--kfs--walqpsypnglf-
ikdlfgygssrdcesgtlrstllrvl-heihqtlmfpatadvnfgng--p
------ldcart-phtfnaqsgkaefd-----vphdidgal---acqlie
vl-------laailshsargfergle-ateytaqpcsekkgllhte----
--iml-alvatgqlctckvplvivywdmvlappkvlavlfpwsekenkey
qyd----t-------avesagaqdqyaisnvkaq-r--------epgkap
srnksq----apdsegdfhgryhvsqkllkn-----kgdvctvvvtgelk
snknkgeevalkptravkli---vk----------lyvafsllkhncqls
---------wtilmaldtygmnapak-------llplsgtsq--------
tgvvhdgaayakkaafyrs-mkdp------gs----nvmvktwflnescg
>D
hkv--hllwlpsgdt-nfdtassrvhg---nipyrllpdmayynkisdan
tgfywfafgynasafkptvdayskevkm-enralddldvtt------ikq
y-----lgdiscytlpms---gdga--aahtkrakkaegyfgk----irr
gklcafllqrivadnsemdni-pkq---hh--qln--raleaaytfsyf-
ykelfays--rdcesgqistsvvkvmyhilrkallfdtrs---fgne--q
lkaspvlgcqkh-pqtfnacs-----p-----vpneidagl---pcslld
t------------lekcsrgfqrg---ptefytqacsepkglrhnegtcg
evmtk-qlwpagelctcmvaleisnwdlvlyppkpstllfpwgekkktef
hfk----vsvgql-kapsnmgtqeeylvvyikselq--------e-----
-kngsq----acdeegdfggrytvqegvqkk-----kgdvctvavageln
sdkregkelaqkdka---livlagalevestgltrlsvafglmggscqll
---------waiiigma-----aiam-------laplgnv---ersrdyi
igvvhdsaaytetanfykp-l---------------tvmvlqwfvdescg
>A
arcpkhlm---ngge-sfitsssklng---nnpykrlkdmsyyntisgat
lgyfwfafsyntssykstceahsrttdm-m-sal-erqitk------vkq
f-----lggiacysyavaikqgdgl--kshtkrtpkgegydgkcsgwvrt
gkm------kivsvndefhne-skk---sr--kfk--rvlepnvafvff-
vkelfryg--rdceagti-----kvl-kelrknvifatsa---ftadkyp
ikakqindcqks-tqtfsackgldglp-----vehecnaglclvncslle
ilhyqahpvflrwlkncahsphrg------fyeqpcgnkkglrhsd----
--ipl-elpsagkncaclvplliiywdl-lftpkpmtllfpwgnkdksey
qyn----ssvgrlgkgpagmgarvty--------lr--------e-----
-kgksq----apddqgdaygseavptavaqnkpgrhkgdvpsvavageln
sdryenkeltlkpth---iv---gkikgmsagvvklyvafsllkdtcmfl
---------wtiligla-----akamygvs---lvplggs---gnsnnya
kavvhtgaaytqkpc--rs-l---------------gviveklflddscg
>C
hpc--dllwfpsgdestfdtdstkvhg---nvayrllkdksyynkisgat
tgffwfafnynastfkatvdedtksvkm-edralnslditk------inq
f-----lggiacydvpvd---gdgt--annskrakkgdgydgtcagwirr
gkmcafllqrivavnnekdne-pkq---hr--qfn--kaleagytfgyf-
ykeifayg--rhcqsgtmptsvvkamfh---kallfatwe---y-ne--p
tkasqltgcekt-pqtfsecs-----p-----vahevpagl---pcslld
smpwhlrpiylrllsrcgigfqrg---ptefytiacsekkglrnnd----
--itkcqlppagelctcmvplqninwdlviyapkpstllfpwgekdksqy
qfk----nsmgq--kapanlgaqeeylvvylkgqla--------e-----
-knktk----aaddegdfdgsytvpeavekn-----kgnvcttavigdls
sekregdhlalkdka---lvvlagslevvssglgrlyaafsligeqcqll
---------wtiiigla-----aiam-------lvplggt---arsdeyi
vgvvhagaaytdtahfykn-l-----------llsftvmvkmwfldqscg
>G
kec--hllwapggge-ffvnsgedlsg---gipyrslknmpywpgmskay
ggifw------tavykgtcsvrsrsakmgedwsv-glqitnhgsv-hikq
y-----gglvecytipravkkghshilksrtkrtqsgda-------wler
vkgcgyltprvtavhkefagyhprk---rt--dfs--ralqsdypfglfs
vkelfgygagrdcapgtlretllrvl-hnlhealmfaattgvdfgde--p
v----iiscaktipknfqqqtgnknfnlvckcaphdiqdal---acelie
vl-------vaavlsntargfergle-aneytrrpcsn-kglrhte----
--ilk-astpasalctcvipmltvywdlvlappkpmallfpwgekenkdy
qyn----t-------avesagsqsqymiscvkagyrptekvihddpgkap
dtmrak----apddegsldsryhved----------kgavctvlvag-ik
snkfkgdeltlketravkli---gk----------lyvaygllkqpcqll
hrckgvvqdwtlltgle-----srak-------llplagtsqt-----yi
aevvhdgnafakr-pffrq-qpdplvpsnqnk----svlvktwyl--scg
>node7
akc--hllwvpngge-sfitsssklng---nipyrtlkdmsyyntisgat
tgffwfafayntstykstcdahtrttkm-edral-alqitk------ikq
f-----lggiacysvpvaikkgdgt--kshtkrtkkgdgydgkcagwirr
gkmcayllqrivavnnefene-pkk---hr--kfn--ralepnytfgff-
ikelfgyg--rdcesgtirttvlkvl-helrkallfatsa---fgnd--p
vkanqilgcqkt-pqtfsacsgkdalp-----vsheinaal---acslld
vlhyqmrpvflrvlsncargfqrg---atefytrpcsekkglrhtd----
--ipk-qlppagelctcmvplliiywdlvlyppkpmtllfpwgekdktey
qfd----tsvgrl-kapssmgaqeeylvnyvktqlr--------e-----
-knksq----apddegdfngrytvpeavakn-----kgdvctvavtgeln
sdkyegkelalkpsr---li---gklevmstglvrlyvafsllkdncqll
---------wtiligla-----aiam-------llplggs---nssnqyi
tgvvhagaaytekaafyrs-l---------------tvmvkkwfldescg
>E
ktc--qlfwtptgge-ffvgtaddldgllegtpyralkdmtvyntisrsf
ggvfw------tttykgactihnrtaklnedwnv-glqnlkh--fglvka
f----hgggiacyttpkaikkgqgtarkgmtkvaqpgeg-------wakr
gqgcgylltrivaihngfignhpkr---ks--kfc--walqpvypngll-
ikdlfgygpsrdcecasl-----rvl-peihqtlmfgatadvnfgng--p
------ldcart-phtfnaqag--qfd-----vphaidgal---acqlae
vl-------maavlghtaqgfergle-aaeytaqpcsekagtlhte----
--iml-evvaegqlctckvplrivywdtvltppkvlgvlfpwsekenkef
qyd----t-------svesggtqdqyaisnvkaq-r--------epakap
trnksn----aadgegdfhgryhvsqkllkh-----kgdvctvvvtgelk
snknigeevalkpsravkli---vk----------lyarfsllkhncqls
---------wtilmaldtygmnapak-------llplsatsq--------
tgavhegaayaskacfyra-mkdp------as----nvmvktsflnescg
>H
kec--hllwapggge-ffads-----g---gipyrdlknmpyypaaskay
ggifw------tatykvtcsvhsrsakkgedwsv-glqatkh--v-hikq
yedsn-gggvdcytipkavkkgngtqmksrtkrtqpgd--------wltr
akg-gylvarvtavhnefagyhprk---kd--klssdralqpdlpfgif-
vkdlfgygtgrgcdpgeiretvlrvl-hnlhqalmfasvtgtefgqd--p
vkenkivecaktipksfglqsgkknynlvcksapheiegal---pctlie
vl-------vaavltntargfergle-adeiisrpcse-kglrhse----
--vlk-alapagelctcvipvlivywnlvlappkplnllfpweqkenkdy
eyn----s-------lvesagdqsqyalscvkagfkasskvihddegkap
eakrgk----apedegsfnkryhvndalpks-----vgavytvlvtgeis
pnkfqgeqlylketravnli---gk----------lyvtygllkhkcqll
hrcgavvqdwsiitgle-----sagk-------llplggdnec-----yi
tevvhdgnayakr-sfyrs-lpdplipsnhds----dvlvktwylkepcg
