>node3
fyk-----dsgvfga--pgek-------ridltaektadglvcr----ag
etsivht--khgr--eslwdrqid---khrts---gvk----ecgpgglf
glantpfqagstreklpfsikvtdnlsvagqedvhdqqqdt-artgwlvg
-ykdtaygttkqpqsv-----aqwfta-----pgg---trke-hayvanr
vtvaymtaml---cvhahntarlkgncdfmfraeplcsakglglsprevd
vlqgartii--lkhnnfstlddnp-lsalaleaqaflepfvppvlyimnf
cg------alshpktiqktiretkftlvpaviplgnt------hyqkhgl
mgcqgcwtta---qvyfh-----yesess---------lsgmtssaktfl
hkdd---gdstrivrsdgsagqagcvvmayaiyqi-hqeaagsrikpv--
---gelaakgiaakftni-sep--------aslkavfsqtcedvenkrdk
-eesdslsllgctnl--fphlalnlfmqvtksqncvhqlegvfgp----l
weefglg--fvgppatdll--el----rr--knh-------ginlfhnq-
------lkegeknehdel-ervsaslgyk-tcqasrvtspakadrnwk
>node6
fck-----dsgvyga--pgek-------kinltvektaddlvcr----qg
etpmihhamkhgrceqflwdrqie---kqraq---glm----ecgpggif
gltnnpfaagsspqklsftnkvtqnfsvagrqdvtddkqdt-aqagwlvg
-ykdseyspt-apqtv-----aqwftk-----eggeletrke-hgygsnr
vtvsykiamla--cvlskdkarlggscdfrfraeslcysnqlglsprevd
vlqgaktii--lkhsyfnalddka-lsvla------------svlyikdf
cg------alshrktvqktvkqskfdlvptliqmggs------ay--hgl
mgcqdcwats---qayfh-----yesegs---------lhasttsaksfl
qkdd---gdstrtvhvt--cdqagcvadaylvfpikehngvgsrikkv--
---ggldaksipgkhtnvlaep--------valkavfp----evetkrkq
-eatdslaliastnl--fphlalnlfmdvataetclklleavfapkvmdl
weefgqg--fvgppstell--dl----ar--kkh-------giehfqnq-
------lkegernehgel-ervdasvgyk-acqagqvtspakndrawk
>node7
fck-----dsgvfga--pgek-------kinltvektadglvcr----ag
etsivhq--khgr--eslwdrqid---kqrts---gvm----ecgpgglf
gltntpfaagssreklafsnkvtdnlsvagredvkddrqdt-aqtgwlvg
-ykdseysstkkpqsv-----aqwftp-----pgg---trke-hgyganr
vtvtyriamla--cvlahnkarlegscdfmfraeplcssnqlglsprevd
vlqgsrtii--lnhnyfsalddnp-lsala------------pvlyimnf
cg------alshrktvqktvreskftlvptlipmgkt------ay--hgl
mgcqgcwata---qayfh-----yesegs---------lqgmtssaksfl
hkdd---gdstrivrvt--cgqagcvikaylvfqi-hhdgvgsrikpv--
---ggldaksiagkhtnv-sep--------vslkavfp----dveskrkq
-easdslallactnl--fphlalnlfmqvttgqkcvklleavfapkvmdl
weefglg--fvgppptell--el----rr--kkh-------giehfhnq-
------lkegernehgel-ervdasvgyk-acqasqvtspaksdrdwk
>A
fyk-----dsgvlga--pgek-------ridltaektkdglicq----ag
etsivht--ksgr--eslwdrqid---khrtseqegvk----e-------
-laltpfqegsarenlpfsiketdnlsvaggedvhddqqep-artgwlvp
-ykgtafgttkqpqst-----akwfsa-----pgs---arkdghayvakr
vtvtymtaml-kaclhakssarmkgncefmfraeplssanglglspresd
vlqgartiv--lkhnnfsavnenp-lsalaleaqaflepfvtpvlyimnf
cg------alshpktvqktirqqkftlvpgviplant------hyqkhal
mgcqgcwtsa---qvyfh-----yeqees---------lagltssgktfl
htdd---gdstrevrsagssgqagciviayeiyqi-heeasgnrikpv--
---gelaakgtaakfini-sep--------aslravfgqtcdnvdnkkdk
-eesdclgllgctnl--fphlarnlfmqvtksngcvhilkgvtgq----l
wedfglg--fvsppasdsl--sl----rr--knq-------ginlfhnl-
------lkedekhehedl-erisasfgyk-tcqasrvtspakadrnwk
>node15
fsk-----dgtifga---gdk-------kinktveqtad-lvcrknavag
easfvhq--khgr--eslwdrqidqigkqrts---gvk----pcgpgglf
gltntsfaaesskeklafsnkvtdnatvtgrddvkddrqdt-aqtgwlvg
avkdssypstrkpksv-----aqwftp-----pgg---tske-igyganr
vvvtyriamln--cvvhhnrarkqgscdfmfraeplcssnqlglsprevd
vlegtrsii--lnhsyldalddnp-lsala------------pvlfdmnf
cg------altsrktiqksvreskftlvptliamgkv------ty--hgl
--cqgcwata---qayfh-----yesvgk---------lkgstssaksfl
hknd---sdssrivkvt--cgqggciikaylvfqi-hhagvgprvkpg--
---ggldaksiggkqtnv-sep--------vtlkavfp----dveskrkq
-elsdalp-lactnl--fphlel--fkqv---qkcvkllepvfapkymdl
reefglg--fagpppvell--el----r------qdklppggvehfknq-
------lkegarkehgel-ervdasdryk-acqasevtrpaksdpdwk
>E
dak-----egtifg-vk---k-------kiaktvegptd-lvcrkyevan
pptfvdk--khnr--salwdreidessdqtts---amk----pcgpgalf
altnfnlkaesskdklafsnk---dvaygarelvkdlrqet-yqaswvvg
tlkdssfpksskpksvhnsglvqwftn-----pag---tgk--igfgpnr
iviayqnpaln--cvaqherarkqgtchikfrqqplcsaremgmsprdvd
vlngpasii--fgh----ttkval-ltgla------------psmfalkl
cg------altsykniqkavreg--tlv------kri------sf--rgl
--cqscwa-griyqayfh-----fesgak---------laassesanrfl
hnkq--aa--prfikls--cgeqdcvikkylifpi-nhagvgq-------
---gsleskaivdkhadv-ses--------stlkpvfp----dveskskq
-elanalp-l----l--fkhlkl--fkqv---sktlkllqpmfsskymdl
kqafglg--fakpppvell--dl----r------qdglppgaiehikhp-
------lkegayqkqsq-----desnrym-pcqgkhltrpanvdpewn
>node14
fsk-----dgtifg------k-------kiaktveetad-lvcrknavag
qetfvdq--khnr--nalwereidqigeqrts---glk----pcgpgglf
altninyaaesskekmafsnkvtdnltiggrdevkderqet-yqtswlvg
tvkdssypstrkpksv-----tqwftp-----pgg---tske-igyganr
vviayriaaln--cvaehdrarkqgtcdimfreqplcsanqlglsprdvd
vldgtasii--lnhlyldtldaal-laala------------ptlfemnf
cg------altsykaiqksvres--tlvpmlvamgkv------ty--hgl
--cqgcwatarikqayfh-----yesgak---------lmatresaksfl
hknq---sdssriikit--cgqggcvikgylifai-qhagvgprvkpn--
---ggleakaiggkhtdv-sep--------vtlkpvfp----dveskrkq
-elsnalp-lasanl--fphlel--fkqv---stsvkllepvfapkymdl
reefglg--faapppvell--el----r------qdglppggvehikdq-
------lkegarqkqse-----dasdryt-acqasevtrpakgdpdwk
>G
fdi-----qgtiag------k-------kiaktneeaad-ltcrknsvag
qetfvdq--khnk--halwerdvdglghqrtg---glk----pcgpggpf
alasinasndnsvqkmlfkspvtdnltigggdevkhnrqdtkykiswlvg
tvkdssyksknkpmpf-----tqwfnp-----pgg---nske-igvggnr
vvfsymvpaln--cvtqhtgaekhgscdiifr------anqlglsaravs
vlggtarii--vrrlfldsldtlltfdala------------ptlfqmnf
cg------alfpykavqnavres--slvkmlvdmgkidltpgisf--hal
--cqgcwatarvkqasfhkgtncyesgakghvksqttllranresaksfl
rslq---kdssriikvm--cgqggcvtkgklifpi-ehpgvgprvkpn--
---grleahaiggkhtdv-cep--------atlkpvig----dadskrkq
-elinala-lt------fphlel--frqv---gtsvqllepvyavkymel
reefglg--fsaphtvelllvel----k------edglpag-vahikdt-
------ltegarqkqpd-----dasdrys-dckasdvtrpakgepdwn
>H
lek-----ngtitg------r-------klakspegaan-lacnknglag
qeafvdq--khnr--nagwkrevdqigrqras---glk----pcgagglf
altnvnasaessvqamlfkspvtehltnggraevkderqht-y---wlla
t-----------pmpf-----tqwfvp-----pgg---tskq-fgygdnr
vviafilaaln--cvaehtrakkngscdiifr------angfglsnrmvs
vldgtapiq--vkhlildsldttltqdala------------ptvfefsf
cggpwsglalfpykaiqksvrek--tlvkilsqmgkvnltpgief--hal
--cqgcrstakvkqgsfh-----yassaksh----stlqratrssaknfl
hklqgp-kensqvvkem--cgqggcvtkgnlvfvv-ehpgvgprvkpn--
---grseaksagtnhtdv-snp--------stlkpvfg----nldskrkq
-easnalp-qastsvmsfphldl--frqv---gtsvkllepvyaikfmkl
kqefglg--fsavhtvall--dlerrlk------edgltpggvehlkgvs
fkepgrlmegarqkrpd-----dasdryr-ackasdvtrpakgesqwk
>C
fct-----dsgvyaa--pgekgeqkvldkieltvectaadlvch----qg
etpmvhhamkhgpceeilwdreie---kqraq---glmcrvkecapggiy
gltnnpfavgnstqkls-ynkvtrnfsaagrqdvtddkqdt-avagwlvg
-ykdseyspt-apkav-----aqwftt-----eggsletrre-hgfgsnr
vtvsykiamla--cvlskekahl-gecdfvfrtdslcysnrvglsprevd
vlqgaktii--lkhsyfnslddkv-lsila------------nslyikdf
cg------alshrktvqktvmqtkfalvttliqmsgs------ay--rgl
agcqecwats---qpyfh-----yvtdgs---------lhkstqsakffv
qkke---gdsartvhit--cdqagcvsatylvfpikehnvvgakvkkv--
---ggldaksvpgrhtnvltepfcydcgllvalkaiyc----etetkrke
heaaaslsliasanl--fpnlalnlimdvpsaetclklleavfipkvgdl
weefgsgrn--gppttelv--hl----ar--kkh-------giehfqn--
----------dhnelgelleraddsvgyktacqagqltspaknarawk
>D
fck-----dsnvyga--iget-------kvnltcekkaddvvvr----qg
dnpmihhalkhgsceqflwnsqvs---kqraq---gls----ecgsggif
gltnnpfggprtqqklsftekvtqnfstagrkdvtddkqdt-aha--lvg
-ykdsqvspt-apntv-----a-----------ggeletike-tgfgsnr
vtisyrkamla--cvlskdkaslggscdfrfraqslcysnqlgvsprevq
vlqgaktiiyflkhslfngledsa-lsvll------------svlyikdf
cg------nlsprktvqktvrqqkfdlvptliqvggt------ny--hgl
mgcqdcwats---qayfh-----yetegs---------qhatttsaksfl
dndd---gdssrtvhvt--cdqagcvadeylyfpakehngvggrfknv--
---ngldarstpskhtnvlaeg--------ialkavfp----evqtkrkq
-eaadslalvastnl--fphlalnlfmdvgtaeaclklleavfepgvmdl
weqfgqg--fvgqpgtell--dl----ar--kkh-------giehfqkq-
------lkegerdehgel-krvdagvgyk-acepgqvtsssknarawk
>node13
fek-----ngtiag------k-------kiaktneesad-lvcrknsvag
qetfvdq--khnr--nalwereidqigrqrts---glk----pcgpgglf
altninasaessvqkmlfkspvtdnltiggrdevkderqet-yqtswlvg
tvkdssykskkkpmpf-----tqwftp-----pgg---tske-igyggnr
vviaymvaaln--cvaehtrakkhgscdiifr------anqfglspravs
vldgtasii--vkhlfldsldaaltmdala------------ptvfemnf
cg------alfpykaiqksvres--slvkmlvdmgkvdltpgisf--hal
--cqgcwatarvkqasfh-----yesgaksh----stllratresaksfl
hslq---kessriikvm--cgqggcvtkgnlifai-ehpgvgprvkpn--
---grleakaiggkhtdv-sep--------stlkpvfg----dldskrkq
-elsnalp-qtstnl--fphlel--frqv---gtsvkllepvyaikymdl
rqefglg--fsaphtvell--dl----k------edglppggvehikdt-
------lmegarqkqpd-----dasdrys-ackasdvtrpakgepdwk
>node10
nsk-----ggtifg------k-------kiaktvngpad-lvcrknnvan
pgtfvdq--khnr--salwdreidessdqtts---smk----pcgpgglf
altnfnykaesskdkmafsnk---nvtyggrdlvkdlrqet-yqaswvvg
tvkdssypksskpksvhnsgltqwftn-----pag---tskd-igfganr
iviayqepaln--cvaehdrarkqgtcdimfrqqplcsanelglsprdvd
vldgtasii--lnhlyldtinaal-ltala------------ptlfamkf
cg------altsykniqkavreg--tlv------gki------sf--hgl
--cqgcwatgriyqayfh-----yesgak---------lmatsesansfl
hkeq---s--prfikis--cgeqgcvikkylifai-ehagvgp-------
---gsleakaisdkhadv-ses--------atlkpvfp----nveskrkq
-elanalp-l----l--fkhlel--fkqv---tkslkllepvfspkymdl
rqafglg--fakpppvell--dl----r------qdglppgaiehikhq-
------lkegayqkqsq-----desdryt-pcqgseltrpanvdpdwk
>F
nsi-----ggtifg------k-------iigktmngkad-lvcrkndvan
pg--hnq--ndnr--salwereldestdqtss---smk----pcksggmf
altsfnykaesskdkmafenk---nvtyggndlvealrqea-yqagwvmp
ttkdssypkstkpksvhnsnlvqhftnlecfypag---sskd-igggadr
ivieyqepalh--cvaehsrarsqgtcdimfrqqplctanelglspreva
vldgtaaii--lnhlylntidsal-ftafa------------ptlfavkf
cs------aftpykniqkavreg--arv------gki------nf--hgv
--cqgcwatgrmyqayfh-----yesgak---------llatsesansfl
qkeh---c--prfikis--cgeqgcvikkylifai-ehagvgp-----ga
gpkgsleakaisdkhsdv-res--------aslkpvfs----nvedkrkq
-eladilp-l----l--fkhldl--f-qv---tkglkllepvytpkymdl
reafglg----kppplelm--dl----r------qdglppgaiehiknq-
------lkdgaydkqsq-----dederyt-acqgsqlarqanvdphwk
>B
fykgcspqdsgvfga--pgqk-------ridltadkkadglvck----sg
etgiaht--khgr--eslwtkqid-----rts---gvk----ecspgglf
glvntpyqagwkreklpisikvmknlsvaasedvhdqqqit-artgwlvg
-ykdtgygttkqpqsv-----aqwftl-----png---trkd-hayvsar
atvayitiml---cvnahntarnkgncdimfrilvkcaakglglsprevd
vlqgaptii--lkhnnlstmddnp-lsalaleaqafldpfippvlyimnf
cg------amshektiqktiretkftfvpaviplgnt------hyakhtl
kgcqgcwtta---qvtfh-----yesess---------fsgmtsyaktfl
hkdd---festrivrgdgsagqvgcvvmsfaiyqi-qqegagsrikpv--
---gqlaakgiaakftsi-sep--------aslkavfsqtckdmearrdk
-eeseqlsllsctnl--fphlelrlfldgtgtqncvv-----fg-----l
weefglg--fvapprtdlf--el----aralkah-------ginlfana-
------lkegdcnehdel-ervsvdlgyd-tcnasrltspakadrdwd
