>C
p---g----snkyartlsekllgkgpadlwiedinsg--dgc--cdd-gk
isiiddrdqleldcrpe--ehaayagaplstgkckavf---stvpiq-dt
--sgsksgavtnghnegtngeeeyflqpdfgvfvhkta---hlfkkadd-
---tgarnsalgsaeghpikkrvan-kregtgrlwva--eafs----kp-
--kggiagnipvymfatkgsineyaipkyflalfgsldgeak-----am-
---geagdislkkanaavadycskevdtnfgvchnlava------pklty
pgrklqvhrlkeaaallssl--------------qc----klvethgmrk
qtyflenglatcvvnn----kslvrlsgqkegdvcytdveglpgkllcgy
ehdygemsnqanpkkdlkddyaqlil-gyrvdngatvaftirqser---q
qaavgp--ssvckvqingktkgevvwlektmpsgvkk-lqplvkmqldrl
ilrvsskavclsgg--------gipggvcy------kvgnkdyvkcisnp
ir----qk---ge----mfg---tgd-----lvapvdahkacahtvllte
gavlgglqst---efnltegnwal-----lpk
>node3
p---g----sikiarilserlaivgaaelwinnvnsg--dgt--cddigk
t-tiddpnqldvecrpe--ehagyagappstgkcmtvf---stvslqfdt
--saskakatanahntviapeqsy--------fvsksa---nqftkadp-
---tggrdlalgraegwpirkgvth-rregtarlwaa--eayq----kh-
--gggvtgnmpvymfvekggidehaipkyfvvvfgklegeakgvqpfam-
---geseditlqrakh-----cakegeadfgscqnliln------qkllt
ptrqlgihqlkdtssllssl--------------lcvvgykmvathgmrk
hkyfidnglttgivah----aslirssgrkggeicykevvglpgqfmcgy
eheygemtqqagakkhlkenyaq--l-iyavdngakiafkv---------
--nvgp--astcktqrgagaqadevwlektqpvivnk-lqtvvkmqldql
vlevsaravcvs---khiatqgelpagacv------gaggkgfvacfsnp
vp----qnlvtge----lfg---sgd-----llgpvrshiasahtvllad
ggilgnyqst---efeledgnwal-----ltk
>H
p---g----ssdvtkthmeallikgvammwlsev-agvaegtpgcgdagk
a-ivqdlskldincqke--e--gnaappctagecmvif---kalavdftq
ekdaekkkavagrhnnqv-geqgy--------hglrt-------teaqaa
ggnaetn----------pmrkgiiq-krqgnarlwsa--esy-qslskp-
--gsavvgnvavykfaekgs-qeapvpk-fvvifmklds---------t-
---gdsnnitlqrske-----csqdaaskfgicrsmile------aklli
pkrklvvhpiketsdllsgfgvlemgpek---lkvv----kivqthnlkk
ntyfiengvatpvtsedagaaplvrssvqkggskcfkavpgipekficgy
thvyielvrqegskkdlkanyaq--a-ivridvgvatvfkvadse-----
----ga--ngtc-hqygpgtveeivwqeask-glsrrclqg-ykvgleql
gfkqra-------------mkgelpaegat------gagvkhfpacfsnp
vp-fclahlht-----vmyg---agdaahkwllppsnvhttchhalllge
ggflggyqna---efdaeegawga-----ltq
>node6
p---g----snkvartlseklllkgtadlwiedikag--dgs--cdd-gk
tsiiedrnqldvdcrpe--ehagyagaplstgkckavf---ttvpiqydt
--sgskskavtnahnegitgeqey--------fvskta---hifkkade-
---tgarnlalgsaeghpirkgvan-kregtarlwaa--eafa----kp-
--kggitgnipvymfaekgsineyaipkyfvavfgtlegeak-----am-
---geaedislkkakaavadycakevsanfgscnnltla------pklly
ptrklqvhrlkeasallssl--------------lc----klvqthgmrk
htyfvenglttpvvnn----tslvrlsgqkngdvcykeveglpgrlmcgy
ehvygemthqanpkkdlkdnyaq--l-iyrvdngatiafsvrqser---q
qaavgp--sstcktqigagakgevvwlektqpalvrk-lqtvvkmqldql
ilrvsakavclsggkkhvavqggvpagvcc------kaggknyvkcfsnp
ir----qnlvtge----mfg---sgd-----llapvsshmacahtvllte
ggvlggyqst---efdlsegnwal-----lpk
>node7
p---g----stkvartlseklaikgtaelwindvkag--dgt--cddigk
t-iiedrnqldvdcrpe--ehagyagappstgkcmavf---ttvsiqfdt
--sapkkkavanahnegiageqsy--------fvskta---htftkade-
---tgarnlalgnaeghpirkgvah-rregtarlwaa--eafa----kp-
--gggvtgnipvymfaekgsideyaipkyfvvvfgklegeak-----am-
---gesedialqrskn-----cakegsadfgscqnlile------pkllt
ptrklgihqlkeassllssl--------------lc----kmvqthgmrk
ntyfienglttpvvnn----aslirlsgrkggdvcykeveglpgrfmcgy
ehvygemthqagpkkelkdnyaq--l-iyrvdngatiafkvrqser---q
qenvgp--nstcktqrgagaqgevvwlektqpvivrk-lqtvvkmqldql
vlkvsakavcvs---khiavqgelpagacv------gaggknfvacfsnp
ip----qnlvtge----mfg---sgd-----llppvsshmacahtvlltd
ggilggyqst---efeleggnwal-----ltk
>G
p---g----cnnvtktymeallikgvammwlsev-agiaegt--cgi--k
t-ivedlsqleidcqkd--e--gnavgpcttgeckvif---kaldvefnd
ekdankkktvagrhnkqv-gelgy--------hglrt-------keaela
tg-----------tenppakkavahqrrqgaarlwaa--esy-----kp-
--tsgvlgdvpvykfaekgv-eqypvpktftpiymkldg---------n-
---gdanaiqlrrske-----csqnsssdfgvcrslklecyaahgpkllt
ptkrllvhaikdtsnlh---gllemgpek---vrlv----kmvqaqnlkk
ktyiinhevtaplaaedsggaalvrasggaggsacfkavpaipdkfmcgy
lhvyihlvrragpkkdlkanyhq--a-ivrinvgtankfkitdqek----
----gv--hgtc-hdygpeavgeivwqqkspsgvsrrclka-vevelesl
gfyhra-------------megdlpaesct------aagvkhfpacfsnp
vp-gclahlhegsgfrvmya---ace-----flppqgintacqhalllde
ggflgsyqnagllefdaeggawvllgstalt-
>D
p---g----snkvartlseklllkgtadmwiedikgg--dgs--cdd-rk
tsiieernqldvncrpe--ehagyvganlstgkckavfqfktqtpvqydt
--sgskskavtnahaegitgehdf--------yvnqtapqahiftksde-
---tnarhlqlgsneghpirkvvan-kregtanlwaa--eafa----kg-
--kgaisgnipvtmfaedgsitelaipknfvavfgtlegeak-----amr
lfdgesedisltkakaavakycakevsanfg--nsltla------pklly
ptrrlqahmlkeasallstl--------------lc----klnqdhgmrq
hvyfvenglttpvvek----tslvrmssqkdedicykdvegmpgammcgy
ehvygemshqvnpkkdlkdnyak--l-iyrvdagetiafsirnsecteyq
kaaigpkksstcrtqigagakgdvmwmekiepalvrk-lqtvvamtldql
ilr-sakavclssskknvavqggvpagvccsghdtfkagsknyvkcflnp
ir----qnlvtgd----mfg---ts---------pisshmacahtvllte
dgvlggyqst---efdlsepnwhn-----lkk
>node14
p---g----sskvtrsysekllikgvatmwlnev-agfpegt--cddagk
s-iiedrsqldidcrpe--ehagyagapcttgecmvif---kalavefdq
eknapkkkavagahdkqv-geqgy--------hglrt-------teana-
---ngtrg-algpteghpvrkgvah-rregtarlwaa--esy-----kp-
--gggvtgnipvykfaekgsveeypvpktfvvifmkles---------t-
---gdsetialqrske-----csqdasadfgvcqsmile------pkllt
ptrklgvhaikdasdllsglgvldvgcdk---lslv----kivqthglrk
htyfiehgatapvask----aslvrlsgqkggsacfkeiegipekfmcgy
lhvyiemtrqagpkkdmkdnyaq--a-ivridtgvatkfkvkqaek----
----ga--ngtc-nqygpgavgeavwqensqsgisrrclqa-vkveleql
gfkqsa-------------mdgelpaggct------gagvknfpacfsnp
ipqgclahlhtga----mfg---agd-----llppvsahstcqhtlllsd
ggflggyqnt---efdmeggawvl-----ltk
>node10
p---g----sskvtrsyaeqllmkgvaimwlnkv-agfpegt--cdnagk
n-iiedrsqlnvdcrpe--ehagyagapcttgecmvif---ktlavefdq
eknapkkkaiagahdkqv-geqgy--------hglrt-------teaha-
---ngtrg-akgpteghp-------------arlwaa--eny-----kg-
--gagvtgnipvfnfvektnsedypvpktfvvifldllt---------t-
---senktlalqeska-----csq-----fgvcqsmile------pkllt
ptrklgchaikdgsdllsnlgvldvgcdk---lava----kivqmhglrm
vtyffengadapvast----galvr--gqkggsscfkeiegipekfmcgy
lqvyveltrqagpkqdmksnyaq--etivrldikvetkfkvkqapk----
----ga--ngac-nqygpgavggavw-eniesgisrrclqs-vkvaleql
gfkqsa-------------vdgqipgggct------gigvktfpacfsnp
ipqgclknlhtga----mfg---agd-----llapvsahstcqstlllsd
agflggyqnt---e---eggawvl-----ltk
>A
papka----niklailfseriaivgaaelfinnitkg--ngt--cddigk
s-ttddptgldsdcrae--ehagytganpstgkcmevf---snvslqvst
--stsyakatssahdtviapsqsy--------fvsdsp---nqftkgdv-
---nsghdmalgraegwpirkgvtn-rregiarlwaagqesyq----kht
kagggvtgnmpvytavekggidghdapsyfvvvfaklggeakgvhpfam-
---gesadivlqrakh-----cakdge---grcqtliln------qklla
pthqlgihqlkdlasllssl--------------lcvvgykmiathgmrk
hkyfiddglatgigah----aslirssgrkgsefcykevgglpsqfmcgf
eheygemtqqagaklhlkenyal--l-iyavdggamiqfkv---------
--nvgp--tstckaergagaqadevwlektepiivns-lqtvvkmqldql
vlevspravcvs---khiathgelpaggcv------gvgqkgfvtcfsns
vp----qdlvlge----lfg---sgd-----lygpvrshiasahtvllad
gktlgdyhst---efeleegnwal-----psk
>E
p---g----pskvtrayadrlkmrgvaimwlknv-tgfpegt--cdiask
n-iiedrsqlhvdcrpd--ehagyagapctsgeclvvf---ktfavqfdq
eknapkkaaiagahdthv-geqsy--------hglrt-------reaha-
---ngtrg-akgpteghp-------------arlwaa--ekf-----kg-
--sagvtgnipvypsvektnsedypapktfvvtfsdllt---------t-
---tenktlalqeaka-----csk-----fgvcqsmvle------pklvt
ptrtlgchaikdgsellssngvlnvgsak---lava----kilsmhglqm
vqyffensaaapvptt----galvr--gekggsscfketeglpekfmcgy
ievyveltrqagskqdmkvnyae--etiirvdikvetnfqqkqipk----
----ga--ngpc-nhygpgavggavw-pdiesgisrrclet-akvalesl
gykese-----------------ipgggct------gigvktrpecfttp
mpqgclknlhtga----mfg---age-----llapvkahntclstlllse
agflggyqnt---e---eggewvl-----ltk
>node15
p---g----stkvtrafsekllikgvadlwindv-agfpegt--cddigk
s-iiedrnqldvdcrpe--ehagyagappstgecmvif---ttisvefdt
--sapkkkavagaqdkgv-geqgy--------fvnkt-------tkane-
---ngarg-algnteghpvrkgvah-rregtarlwaa--esya----kp-
--gggvtgnipvykfaekgrvdeypipktfvviflkleg---------t-
---gesenialqrske-----caqegsadfgvcqnlile------pkllt
ptrklgvhaikdasdllsglgvldvgcnk---lslc----kmvqthglrk
htyfiehgltapvvsk----aslirlsgrkggsvcfkeveglperfmcgy
lhvyvemtrqagpkkemkdnyaq--l-ivrvdngvamkfkvkqaer----
----ga--nsac-tqrgagavgeavwlentqsvivrk-lqavvkvqleql
vlkqsakavcvs---khiavegelpaggct------gaggknfvacfsnp
ip----anlhtga----mfg---sgd-----llppvsshsvcehtlllsd
ggilggyqnt---efdleggewvl-----ltk
>node13
p---g----ssdvtktymeallikgvammwlnev-agiaegt--cgdagk
a-ivedlsqldidcqke--e--gnaaapcttgecmvif---kalavefnq
ekdankkkavagrhnkqv-geqgy--------hglrt-------teaqaa
sgnaatn----gptenhpvrkgiah-rrqgtarlwsa--esy-----kp-
--gsgvignvpvykfaekgs-eeypvpktfvvifmklds---------t-
---gdanniqlqrske-----csqdaasdfgvcrsmile------pkllt
ptrklvvhaikdtsdllsglgvlemgpek---lkli----kivqthnlkk
ntyfiehgvtapvasedagaaslvrasgqkggsacfkavpgipdkfmcgy
lhvyielvrqagpkkdlkanyaq--a-ivrinigvatkfkvtdsek----
----ga--hgtc-hqygpgavgeivwqqnspsgisrrclqa-vkveleql
gfkqra-------------mdgelpaesct------gagvkhfpacfsnp
vp-gclahlhtgsgfrvmya---agd-----flppqgvhttcqhalllge
ggflggyqna---efdveggawvl-----ltq
>F
p---gecrasskvtrsyaeqllmkgvaiswlnkv-agftegt--cdgagk
n-iiedpsdlnvgcrpedyehagyanyhcatsecmvvf---ktlavefdq
eknaskkkaiagnhekqv-geqey--------h--rt-------teaha-
---ngtrh-akgpt-------------------lwai--eny-----ig-
--gagatgnipvfnfvektnaegypvpktfvvefldllt---------t-
---senkglalqeskn-----cck-----fgvcqsmile------pkllt
ptrklgchaikegsdllsnkgvldmgcekheglava----kivqmtglrl
vtyafknggdapcast----gglvr--grkggsscfkeiegipekfmcgy
lpvyielsrqagenedskpnfaq--etivrlnikvevkfkvkpatk----
----gt--nsac-nqygpgavsgavw-eniekgisrrclqs-vkvgeerl
gfkqsa-------------vdgqipgggcv------gigvksfpacfndp
ipqgclknlhtsa----kfe---age-----vlkpvsahstcqftlllsd
agflggyqpt---e---eggawvl-----lak
>B
p---g----likiasilserlaiqgaaemwidivdsg--dgt--cddisk
t-siqepnqlnvqasae--ehpgyagappssgkcmtil---skvslqfas
--dpkrakatanah-tviapeqsy--------fvtksa---dqfskfdp-
---tggqdlalgsaegwpirkgvah-rkegtarlwaa--eaye----kh-
--gggvtgnmpvylfvanggidspaigkyfvvvygklegepkgvqpffg-
---gegeditlqrskh-----cakegegdvgppqnliln------qkllt
ptrdlgihqlkdrssllgsl--------------vcvvgykfvashnvrk
hkyfidnglttgflph----pslisspgkkggeicykeavalqgqfmcgy
eqtygemtqesgatktlkedyaq--k-iypvdngakiafkv---------
--nggp--avtcktqrdggaqakqvwlektrpvivnk-fqsvvkmqldql
vlevgaravcvs---prlatqgelpagacv------iatgkrfvecftvp
ip----qnlvtge----lfdccskge-----llgpviphiarartvllae
tgvlgkypgt---efeledgnwal-----ltk
