>node15
sniyaikiqi-ennvllnknvmierpfsaelkgcqkk-neaalve---ta
esplsrksdnsie-----vpviltdardklrkmltpicnlsedflrtpep
tkhlgeh-------lvehpnkklavksggsamcqgkflayagnrerpec-
-----nqqkklracispgwlytyeggcq--e--delpqkpilrtmkgeyc
gfagsea--graaaeserga--tgankkklved-tlllhatlgdkqlhl-
nlqlepdrkdaali-qn-itmevpaalrliistpeatkw-r----svrgr
ealcggehlatnaaggadhapt-eslkyrhasdivpsny----------g
trpctws----------------elgpkq-----rvaisl-sgksltwvl
daqdtcenql---------aahygpvpmkit--ltkktpstrlhtccvkl
hstnardqalekh--gdphlsegahfatlpgikllvpknsfkckfrfgcl
yatigytv--------sdchlggitl-ivsevyelvlslkklagadv---
----vnrqalgyv-f-nnnamatiptay--fawyqlgrsiiassnval--
----tlaaqtcg
>F
thnyvdkihilvlnvglqkdamierpftseakqcqvk-kegtlve---ta
esslhrkteglle-----ppiilaaardilrktltpvvdlsldflrfpdp
sphtaeh-------yaqep-------ssaavmcqgrflkfggnaaipqc-
-----ysqnklrasv--gwlyvfevgcq-vn--deltqkpilaamreeyt
gftgees--glaageamrgs--tgekkrklvdd-tlllhatl----tdl-
ntdfdpdrrdlaligqs-iglevaailrliidgpepvrw-h----kirgk
eskcpkeqlatngaggaahask-eglhfmhpnnlipsny----------g
krpctwg----------------dlgrig-----rvhiai-spkcltwvl
dattacqnll---------aahyakaqmkvv--ltqvepctklytanvkm
qstnvldepfekh--gdpklsegthfaslpgvkllvapysfhckfafgcl
yasightv--------adchfagisl-ivsavyel---lgkngcsei---
--------slsyt-f-sdeamgtaptlf--rpwyqvgrgviassgvsl--
----lagiptcs
>node3
cniyalkiqi-ensvllkktilieksfsaeln--------salim---ar
enplsrksdhsae-----epvlltdakeklrkmltpicnntedflrtndv
akhggeh-------yvehpnkklevksgtglqpqgkffayagnrerpac-
-----nqssklracassgwfytfndgcq--erpdegpdkaiyrtfkgeyc
gaaggea--srataeserga--tgahrkllvee-tlllhat-----ldl-
nlqlepdrkdaali-en-vfmelpaalkliisirdatkq-rasvttvsgr
evlcgaehlahaaakgfdhasa-esvkfkhtsditpasf----------g
trhctwsaqpapsapvcpvdngeelganq----trlaisllagnslvwvl
dnqikcqnqv---------aahcgpvpmkft--ltkktpstrmhtc----
-ntnareealenh--aephlsegghfennvgnkllvpkngfkckfrygcl
yatvgyav--------sncnpggvtl-itteeyelrlalkklasadgqkn
trggvnrqaleyv-y-nknaitvfptay--fawfqldkariaaskvsl--
----tlsaqtca
>node6
sniyaikirn-egnvleekniliekpfsaelkgadrkanesglie---vt
anplsrksdhaiq-----ypvlltsakdklrkmlnpicnlneeflrtpns
tkhggeh-------yvahpnkrlelksgggaqpqgkfyayagnhersec-
-----nqikklraccspgwfytfedgcq--e--geapkkeilrifkgeyc
aisggea--srgtqesevgamvsganrkllvdk-tllleap-----lhlf
elqfgpdrkdaall-qn-vfmelpialalvisipearkryrvsvktvrgr
eaicgaehlahsaargadhatt-etlkykr--ditpssy----------k
arnctws----------------elgakq----srlatsllpgkslvwvl
dpqdkcenmv---------ashyvpvpmkft--ltdktpsvslhnccvkl
hstsardhaldknenadp--segvhfevd-gskllvptnlfeskfrygcl
yatigyav--------sdchalgvtl-ivteeyelilsnkllagada---
----vnrqalsyv-f-nknamttfptay--fawyqlskrrisvsnvsl--
----tlraqtca
>node10
tneyvdkihi-elnvglqkdamierpftaeakqcqkk-kegtlve---ta
esplhrkteglle-----vpiilaaardilrktltpvcdlsldflripdp
sshvaeh-------faqqpnkklstksgaaamcqgrflafagnaeipqc-
-----yrqkklrasv--gwlyvyevgcq-vn--deltqkpilkamkgeyc
gflgeea--glaageavrga--tgekkrklved-tlllhatl----lhl-
ntefdpdrrdaali-qs-ialevaailrliintpepvkw-h----nirgr
esncgkeqlatngaggaahapk-ealrfmhpsnlipsny----------g
trpctwg----------------dlgvid-----rvqiai-sekcltwvl
datdacqnll---------aahygpapmkiv--ltqvipstklytagvsm
qstnvldeafekh--gdpdlsegthfaslpgvkllvprysfkckfafgcl
yatightv--------adchlggisl-ivsavyel---lgklgcvei---
----ctrqslsyt-f-sddamgtvptly--rpwyqlgraiiasngval--
----tagaqtcs
>H
thdyptkilh-endvllqknsmiethfsavmrqcqkk-heggqvq---ta
agslrkkgdgileellasvpislaaardvlrktmapicdlsldflripdp
tkplaen-------laqqpkqklptkngvaamcqgkfldfagskdrpec-
-----nqqkklrasv--gwlytyqggen-ik--daiaakpiigtmkgeyc
gylgses--gltsgiavlga--tgekkkklveeftlllhatl----lhl-
hpgfqp---------nn-islevpgilrlikscpegtkw-r----wgrgr
qalsgkehlgvnagagklhapt-edlkllhpsnlvssny----------a
trpctwg----------------dlgvkespak-kvqiti-seacptwvl
dgpntcqsqm---------apqygsgglkia--lnklv-siklhsssvkl
rktnaadlalern--adpnlsegahfaslpglkaiiprysfkctfefgcl
yaaigqtl--------kecrlpgitldivsnvfelvlglkhlgsvdi---
----ctrqtlgyvlf-sgdemeviktsy--rpwyqtgraiitsanvaf--
----tlsaqtca
>B
cniyavkiqi-qsevllkkvilieksfnaeln--------svlim---ar
enpagrksdraae-----epvlltdakeklrkmltpicnntndflrtndv
akhageh-------fvehpskktevkagnglqpqgkffaytgdrerptc-
-----nqssklravassgwfytfndgcq--drpdegadkaayrtfdgefc
gasggea--smataesarga--tgnfrkllved-tllihta-----lel-
nlqlaptpkdsali-eg-vfkelpaalkliisirdelkq-rasvttvsgr
evlcgsehiahaaatgfehara-esvkfkhtsnispasldtgsppfdihg
trhctws----------------elaapq----kklaislltgnsivwvl
dnvrkcrntv---------aehcgpvpmkyt--ltkktpsarrhpc----
-ntnvqegalenh--agphlsegghfensvgekllvpkhgfk--------
--tggyav------------pggvsm-ttvdeyelrltlkklasadgqkg
trgainkqapeyv-y-aknaitvfpsay--fawfqlikariaastigl--
----t----tca
>G
aheypikisf-dnnvllqknsmierpftavmrqcqkt-deggivq---ta
asplarkgdgvldelvpevpislaaareilhktmtpicdlslnflritdp
tkhlgeh-------lahhpkkklptvngcaaqvqgrflffagdadrpec-
-----nqqksl-asv--gwlytyqggaqfvk--eaeqakpiigtmkgeyg
gylgstnvlglakseamkge--tggkkkkvvea-tlllqatl----lhl-
hlqfep---------nn-islevpallrlikscpegtkw-r----svrgr
qalggnehlglnagggkanapt-ednklmhpshllssny----------a
trpctwg----------------dlggketpsk-rvnist-tekcptwvl
dstdkcqsql---------kaqygpaglkit--mtklvpstklhmcavkl
hstnapdealekh--vdpnlsegahfaslpgikllisrysfkckftfgvl
yviegatv--------kschlsgisl-vvanvfelvlglthlggvdi---
----v-rqtvsyy-fdsddemdvlptay--rawfqagraviaasnvtlkq
gailtlgaqtca
>C
sniyaikmrn-egsiltdknvlierpfegdlknedkkrnesglde---vt
tnpvsrmsdhsik-----ypvlltsaksklrkmlnqicdfneeflrtpds
tkpggeh-------yvah---rlslksgsgaqpqgtfysyagnhdrsqc-
-----nqikklracctpgwfysfeescq--e--geaprkevlrifkseyc
sigsaea--argtqesevgalvsganqkllvnk-klllaap-----lhtf
dlqlgpdrkdaall-qn-vfmelpvalalhmnipearkqvrvsvktrrgr
eaicgaqhvahsagrgtdhatt-etlkykr--dinlsty----------k
arnctws----------------elaakn----rrlspkalkggqlvwal
dplekcenmv---------ashyksvamkfttyltskgpsvslhnrcvrl
hesnardhglskgenadp--seglhfevd-askllvptklfekkfrygcl
yatigyav--------sdchrlgvtl-ivteeyqlildnkilagaev---
----vnrhalsyv-f-nkdamtlfesay--flwyqlskrkvsvsngsl--
----tlraqsce
>A
cniyalniql-ensvllkktiliqksfsaels--------salam---ar
anplsrtsdhsaa-----esvlltdekeklrkvlspicsntqdflraedi
akhggdh-------yvehpskklvvksgtglepqgkffayggnrerpic-
-----netsklracassgwfytfndgca--espdegpekavyrtfkgeyc
gaaggea--srataesergp--sgahkellved-tlllngt-----ldv-
nldlepdrkdatlr-envvymelpaalkliisinsatkq-rasvttvtgr
evlcgseplahantkgydhasa-esikfkhtadiipasf----------a
tkhctwsaqpqpttpvcpvdngeelganq----tqlaiallggnslvwvl
dapikcqnqvtkilslpktaahcgavsmkft--ltkktpsirmhtc----
-ntharegaleth--gephfcdgghfqdnvgnklleakhgfkckfrygcl
yatvgyaianscdpfqsncipggvtl-ittdeyelklalkkladrdg---
-tgamnrqalqyv-y-nknaitvfptay--fsffqldkariaaskvsl--
----tlsaltca
>node13
aheyptkisf-ennvllqknsmierpfsavmrqcqkk-degglvq---ta
asplrrkgdgileellpsvpitlaaardilrktmtpicdlsldflripdp
tkhlgeh-------laqqpkkklptkngvaamcqgrflafagnkerpec-
-----nqqkklrasv--gwlytyqggaq-vk--daiaakpiigtmkgeyc
gylgses--glasgesvkga--tgekkkklvee-tlllhatl----lhl-
hlqfep---------nn-islevpailrlikscpegtkw-r----svrgr
qalsgkehlgvnagggkahapt-edlklmhpsnlissny----------a
trpctwg----------------dlgvketpak-rvqisi-tekcptwvl
dstdtcqsql---------aaqygpaglkia--ltklvpstklhscavkl
hktnaadqalekh--adpnlsegahfaslpgiklliprysfkckfafgcl
yatigqtv--------kdchlsgitl-ivsnvfelvlglkhlggvdi---
----ctrqtvsyv-f-sddameviqtay--rpwyqagraiiagsnval--
----tlgaqtca
>node14
aneypikihi-ennvllqknamierpfsaelkqcqkk-negtlve---ta
esplrrksdgile-----vpiilaaardilrktltpicdlsldflripdp
tkhlgeh-------laqqpnkklatksggaamcqgrflafagnkerpec-
-----nqqkklrasi--gwlytyqggcq-vn--delaqkpilktmkgeyc
gylgsea--glaagesvrga--tgekkkklved-tlllhatl----lhl-
nlqfepdrkeaali-qn-ialevpailrliistpeatkw-r----svrgr
ealcgkehlatnaagganhapt-ealkymhpsnlipsny----------g
trpctwg----------------dlgvke-----rvqisi-sekcltwvl
dstdtcqnql---------aahygpaamkia--ltklipstklhtcsvkl
hstnaadqalekh--gdpnlsegahfaslpgikllvprysfkckfafgcl
yatightv--------sdchlggitl-ivsevyelvlglkklggvdi---
----ctrqslsyv-f-nddametvptay--rpwyqlgraiiassnval--
----tlgaqtca
>D
wniyaakirn-egnfleeksilaqkpfgaelkgadrkenesglie---ik
anplsrksdhaiq-----ypvlltsardklrkmlnpicnlseeflrtpgs
tthegep-------yvghpnkrldlkggggsqpqgkfysyagnhersqcq
hagdanhikslrgccasgwfytfedgcg--e--gempkkeilrifrgeyc
aisggea--srgtqesevgemvsgavskllvdk-tllleep-----lhlf
eiqfgpdkgnsall-qn-ayselafalalvisipearkryrisvktvrgr
eaicgaehlahseargadqattwetlkyrr--diapssy----------k
amncvwa----------------elgakp----srlatsmlpgksltfvl
dpqdkcefmv---------ashyvpvpmkft--ltdktpnvslpsccvkl
hstgardhaldkneitnp--segahfesd-gsgllvntnlfetkfrygcl
yatigyav--------sdchalgitl-ivteeynlilsnqlvagaea---
----vnrsslsyv-f-nknamttfprgy--falyklskrrisvgnvsq--
----tlraqsca
>E
tgeytdkihi-elkvglqsdamierpftaeakqcqkk-kegslvagfhta
esplhretegll---------ilsaardilrktltpvcnlrldflripep
sahvaenisngppilaqqpnkklstksgaaamcqarflafegnaeipqc-
-----yrqkklrasv--gwlyvfevgcq-kk--deltqkpilkgmkgeyc
gflgeea--alaagdsvrga--tgekkrklved-tlllhati----lhl-
ntefdpdrrdeali-qs-ialevpailrliintlepvkw-h----nirgq
enncgklqlaaegasgaahgpk-ealkfmhpanlipsny----------g
thpctwg----------------dlnvid-----rvqial-nercltwvl
daadacqnll---------aahfgpapmqia--ltqvipstklysagvsl
qstdylddafekh--gdpdisegthlasl---kllmprysfkckfafgcl
yqaighyv--------adchlggisl-ivsacyel---lkklgaisi---
----ctrqapsyt-f-sddakgtiptlyhkrnwynlgraiidskgval--
----tagaetcs
>node7
sniyaikiqi-ennvllkkniliekpfsaelkgsdrk-desalie---vt
enplsrksdhsie-----vpvlltdakdklrkmltpicnlnedflrtpds
tkhggeh-------yvehpnkklevksgggaqpqgkffayagnrekpec-
-----nqakklraccspgwfytfndgcq--e--degpqkailrtfkgeyc
giagsea--srataeserga--tganrkllvee-tlllqat-----lhl-
nlqldpdrkdaali-qn-vfmelpaalrliisipeatkr-rasvttvrgr
ealcgaehlahsaakgadhast-eslkykhasditpssy----------g
trhctws----------------elgpkq----srlaisllpgkslvwvl
dpqdkcenqv---------aahygpvpmkft--ltkktpstrmhtccvkl
hstnardqalekh--adphlsegahfenevgnkllvpknsfkckfrygcl
yatigyav--------sdchpggvtl-ivseeyelilslkklagadv---
----vnrqalsyv-f-nnnamttfptay--fawyqldkariatsnvsl--
----tlsaqtcg
