>F
gikvrlqphlfydlfghvgqtlhgtvt-------hdppah-gkscingrl
kgh-gpyhtgdld--------------lgkslynlld-eeagk-----fs
akvvppglsedphtfgrmmkl--envfpgasvatd-rpqsgni-kl-vsf
aildtnklqtgmdcg-n---selngdlaegkvysqlpiaslvymkglsgg
cedv-kelhvaqgfffltrigdtq--spqlmseasigcdvkgk-------
---qh--------lhvfplvcpegswa--alssgekhkllsl--------
---evtyltpgavggvvnrnvac---hlsga-gqv-----hpvysskvfd
dsak-ns----ayrdlp--cscvkngtgv-te----wettc-------dm
vgveklvvhgradrakklhdrntcytgltkrskv----rekhaktgvagi
esadsdivaakfet---vqdk---gadfyfnshvle--gveiahkhcgks
kcdnasacnflthmlacpclfqqy----ekyarnfdi-gkkvvtvacpek
----ktksrmrma------gvkkpk---rvlrgvclpvsppa-------q
--------egpfisitchayvgm-rehasgts
>node14
gtnvrlqphlfydlfg-ighqmhgavt-------hdppth-gktcag---
tgh-apfdtgqldciac-------kiqlgkslyylld-napgkpkapaya
pkivppslsvepqsfgrmmkl--edaypgagvake-rpnagni-kl-vnf
gllehhkarigkdcs-n---sqfhgdlaegkvhah-----lvymkdnsng
cepv-kefhvaqgfffmtriggtq--spqlmsqasigcdakgk-------
---qh--------lhvyplicpenvwd--avsssvrhillslgpricslt
rleevsyltpgaaggvvnrnvdc---hlsga-gkv-----hpvyssmlfd
tsak-nd----lyrvgp--cscvkngtgv-te----wgttc-------sm
lgadktvghgqddrsrllhdrntpyaglskrsav-----ekhartgvggv
egaesdlvaakfpt---vqdk---qldyylnshvlelkgvesahagrgkn
kcenaascdyvnfvlpchclfqqc----kkyasdldi-gkkvvdvvcsek
----agksrmrma------gvngpk---rvlrsvclpappta-------d
--------egpfvsi----yvem-keyps-at
>node15
gtevrlaphlfydlfg-ighqmhgalt-------hdpsth-gkacag---
igq-ppfdesqlgciac-------kiqlgkslyyllk-napgkpkapaya
pkvvppslnvepqsfgrlmkl--edaypdagvake-rpnag-------nf
gllehhkariskncs-n---sqfhgdladgkvhah-----lvymkdyang
cdpv-kefhsvqgfflmtriggtq--spql-aqasigcdakgs-------
---qh--------lhvyplicpenvwd--avgsavrhimmslgpkiyslt
rleqvpyltpgaaggvvnkkvdc---tlsga-gkv-----lpvyssmlyd
ttae-nd----lyrvgp--cscvkngtgt-te----wgttc-------sv
lgsnkteghgkddrsrllhdrntpyggltkrsavvgck-skhartgvggv
eaaesdivaakfpt---vqdk---klehylnshglelkgvnsahagrgnn
kcenatscdyvnfdlscnclfqqq----kkyqadldt-gkkvveivcsek
----agksrmrmslttvhegvngpk---rvlrnvclpappsv-------d
--------egpfvsk----yvek-keyps-at
>node3
gptvrlapklfydlfg-vghkmegplt-------hdpsth-ska------
igr-ppfheaqlgcfac-------kvqlgknlyillk-napgetnapaya
pkgvpnslhverqsfgrlmkl--dda---vgverd-rpnyg-------nf
gllehhnaripkdcs-n---sh---dladgklnaf-----liymkey---
-dpl-kefhgvegffq---vggtq--sgal-aqasigcqskgsyggypfr
ktaqh--------vqiyplicpenvwq--algsavrhllralglktyalt
rlsqvpyltpgaaggvikkkasc---slsgs-gnv-----lpgyrsllfn
ttaq-dg----lfrvgp--cscvktgsgt-de----wtatc-------sv
lgstkteghgkndparlladkntpyggltkrssilgck-skhe-agipgi
eagepd--aanfpt---vqnk---klerf--ahdlvlkgvnnlnagkgnk
kcdtatscdynafkvacncmfqhq----kmyqadlnttgkkvveivcsek
----agksrmrmslttvndgvkgpk---r-lrnvcl---psv-------e
--------dnpfvpk----yvnk-keypk-at
>G
nvnmklqphlyhdlfs-igyqmhgtvt-------fdppah-aqtaag---
tghfapfdegqleciaclattgqgklqlgkglyylldlnapgk--gpaya
pkivpasldvephyfgrmmkl--eqayps---gteartndgsifkl-vha
gllehqrarvgkdct-nagspgfhgdlaegkgqah-----lvytkdn---
cksv-gelr----yffltrigd-t--spdlmcqasi----sgk-------
---qhvlampyndlhvyplvcpgsvwe--avggsvlfilldldprlssqv
rgedvnyltpggaglivhrgvnc---nlsga-gkv-----hpvyasvlfe
ggar-nd----lyvagp--csctkkglgv-tefaatwgttcgegfltlkm
lgadktvsngdddkarllhdlktpyaglrkrtav-----aehartgvdgt
egaesdlvaakfptskmsqdkgslqldyylnshtlqlkgvesahakrgkn
kcanavscdyvnfllpcsclfdhc----naypseldv-gngmvdavcslk
gvgpagkaqlrmn------gvng-----rvlrtvclpappta-------d
--------egpfasi----yvem-peysa-at
>node13
gvnlrlqphlfhdlfs-igyqmhgavt-------fdppth-aqtsag---
tgh-apfdegqldciaclstlnqgkiqlgkglyylldlnapgkpkgpaya
pkivppsldvephyfgrmmkl--eqaypg---gke-rpnagnifkl-vna
gllehhrarigkdcs-nasasqfhgdlaegkghah-----lvymken---
cesv-gefhvaqgyffltrigd-q--spelmsqasigcdakgk-------
---qhvlampfnnlhvyplicpenvwe--avsssvrhillnlaprlsslv
rgedvsyltpgaagevvnrgvnc---hlsga-gkv-----hpvyssmlfe
gaak-kd----lyragp--csctkkglgv-teftvtwgttc-------sm
lgadktvshgqddkarllhdlktpyaglkkrtav-----eehartgvdgt
egaesdliaakfptskmvqdk---qldyylnshtlqlkgvesahakrgkn
kcdnavscdyvnfvlpchclfqhc----kkyaseldi-gkgmvdavcslk
----agksqlrma------gvngpk---rvlrsvclpappta-------d
--------egpfasi----yvem-keypa-st
>node7
gpsvrlapklfydlfg-vghkmqgplt-------hdpsth-ska------
igr-ppfhesqlgcfac-------kiqlgkslyyllk-napgkpkapaya
pkvvpnslnvepqsfgrlmkl--edaypdagvare-rpnag-------nf
gllehhkarikkncs-n---sh---dladgklhah-----liymkey---
-dpv-kefhgvegffq---iggtq--sgel-aqasigcqskgsyggypfk
kpaqh--------lhvyplicpenvwd--avgsavrhlmrslgpktyalt
rlsqvpyltpgaaggvinkkvsc---slsgg-gkv-----lpgyrsllyn
ttae-dg----lyrvgp--cscvktgagt-de----wtttc-------sv
lgstktdghgkndrarllqdrntpyggltkrssvlack-skhertgiggv
eaaepdvlaakfpt---vqdk---klery--ahglvlkgvnsanagrgnk
kcdtatscdyvnfklacnclfqqq----kkyqadldt-gkkvieivcsek
----agksrmrmslttvhegvngpk---rvlrnvcl---psv-------e
--------dnpfvpk----yvek-keypk-at
>H
gvnlrldphlfhdlfs-igyemhgavl-------fnppta-aqtsag---
tkq-apfdegqldciaclstlnqgqvqlgkglyflltlhargkpkvpaya
pkivstglavepryygrmmka--eqaypg---akq-rpdagniftlcvna
gllehhrgrfgkdcs-nasasqfhdalaegkghah-----lvymkqn---
cesv-pefhvaqayfflnrigt-q--speqmsqasigc------------
---qnvlampfsnlhvyplippqgvwe--avssqvrhillnlaprlakll
vgedisyitpgaagesvnrgvaihkkhlsgalgkv-----haiysamlfe
gaak-kd----lyrtgp--cictkkglgv-tdftvtwastc-------sq
lgadktvshgqdnkarllnalktgygdlkkrtgv-----eenahkgvags
esaksdliaaklpsskmvqdk---qleyylnlhtlqmkgvgsshakr---
-cdnalscdyvnfvlpchclfqhc----kkygreldi-gmgmvdavcsvk
----vgksqlrma------gvagpkkrarvlrsvclpaspta-------n
--------egpfati----yvem-keypg-sk
>node10
gikvrlqphlfydlfg-ighqlhgtvt-------hdppah-gkscak---
tgh-apydtgdldciac-------kiqlgkslyylld-nepgkpkapqya
pkvvppglsedphtfgrmmkl--edvfpgasvakd-rpqsgni-kl-vnf
gilatnklrtgkdcg-n---sqlngdlaegkvhsh-----lvymkgnsng
cesv-kelhvaqgfffmtriggtq--spqlmseasigcnhtgk-------
---qh--------lhvyplicpedvwa--alssgvkhkllslgpricslt
rleevtyltpgavggvvnrnvac---hlsga-gqv-----hpvysskvfd
dsak-nn----lyrvgp--cscvkngtgv-te----wgttc-------nm
lgvektvghgqgdrskllhdrntcytgltkrsav-----ekhaktgvagi
egadsdlvaakfat---vqdk---qldfylnshvle--gveiahagrgks
kcdnaaacdylnhilpcpclfqqy----kkyasnldi-gkkavtvvcsek
----kkksrmrma------gvngpk---rvlrsvclpvppta-------q
--------egpfisi---ayiem-rehas-tt
>C
spsvrlgprlfydlfa-cghkmqgplp-------ad---hhskd------
kgr-ppfsdsrtgcfac-------aiqvakslyytlg-nssgkpkppaya
pkv-------epesygrllkl--tsayqdagvtke---------------
--lqahkprfkkacsnn---sd---dladsk--ah-----liymkey---
-dpv-keflgtegffq---vgsta--kael-aqasigcntktayggysfk
qpdqh--------ldiypllcpinvwvtaavgspvrpllpslgpgsyqlt
rltqvpylivgpasgglnkkvac---tlagg-ghvlapawlpklrsllyn
ttae-dgl---lyrvgphkcs--kkstntyde----rattc-------nv
lattkpaghgtnkrarlylkcstpyggltkrssllack-gkhqltgvggv
eaa----------------ee---kvecy--shglvlkgvn------gnk
ktdtatpcnyvdfklncncmfqqqv-kvkkyqasldq-gkkvieivcdsk
-----gpgrmimtldsghegvngpk---rilqnacl---pcl-------h
--------ddgfapk----yhqk-keypk-av
>B
gptvkvapdlfydlfg-vghkmdgplt-------hdsath-hka------
igr-apfheaqlgcfac-------kiql--------k-ktsgetaapsya
akgvpnslhvevqaygrlmkl--dea---vgverd-rpnyg-------nf
gllehhsa-----cg-n---sh---dlaegklnaf-----lfylkey---
-dpl-kdyhgvegyfq---vggtl--tgal-artiigcqsqgtyggypfk
ktaqh--------aqiypllcpenvwq--avgsa-----ralglnayalt
rlaqvsiltpgaqggvckkkvnc---glcgs-qss-----lpsyrsllfn
ttaq-dg-nhclyrlgp--cscvkgpsgt-dq----wtatc-------av
lgstnseghgkndparlladkntpyaglskrssilgch-skhe-agipgi
eagepd--aadfpv---vqdk---kldrf--dhelvmkgvdslnpgkgnk
kcdtatsceynafkvicncmfqhv----kmyqadlnttgkkvvelvsgek
----agkqrmrmslttvsdgvkgpk---r-lrdvcl---pav-------e
--------dnpfvgs----yvdk-keypk-at
>A
gatvklapklfydlfg-vkhksenaltaksvvgahdpaih-skv------
vgs-qpnheanlgcfac-------kvqlgknlytllk-napgetaapaya
pkgvanslhverqsfgrllkl--dea---lgvqrn-rpnyg-------nf
glldqhkaripknct-n---dh---dlsdaklnvf-----liymkay---
-dpl-kmyhgvegffq---vagtq--agal-aqasigcqgtgnygaypft
ktaqh--------lqiyplicpqnvwq--algsevrqllralglktyalt
rltqipyltpgaaggvikgkaqc---slkgs-sgv-----lpaykfllfn
tdah-dg----lfrvgp--cscvktssga-ee----wtatc-------sv
lgdtkaeghgknkparlladkktayagltkratilgcr-skhe-anipgi
eagepg--aagfpt---vqnk---kldrf--ahdlvlggvndlnagkgnk
kcdsgtrcdytafkvacacmfqhq----kmyqadlnntgkkvveigcsek
----agksrlkmslsyvnngvkgpk---r-lrnvcl---pav-------a
yqepggslaspfipk----yvpehkeypt-at
>E
gikvrlqphifynlfg-igrqlhgtvt-------hdppay-gkscav---
tgh-apydpseldcvac-------diplgkplyylld-nepgklkapqya
pkvtppslsedphtfgrmmkl--edvrpaasvakq-rpqsgni-kl-vdf
ailathklrevkdcg-i---nplegplaqnkvhkh-----laymkpesng
cesv-kelhvaqgfffmtrvggaqifspqlmsessigcnhagk-------
---qh--------lhvyplicped-wa--aacsgv-----slpprictlt
rlegvtfltpgevggvvnrnv-c---tlsga-gtv-----hpvnsaknfa
esak-nn----lyrvgp--cscvkegtgi-se----wgrsc-------qm
ltiaksvghgqgdrekllhdrgtcytgltkrtsv-----ekhakigvatv
egtesdivaakfat---vqek---qlnfyinshvle--gieithasggks
kcdnaaacdylnhilghpckfehy----kkyasnldi-gkkavtvicaek
----kkktrmrmf------gvngp----rilqsvclsvpstshtsaahgq
--------enpfvsi---ayvem-rshgs-tt
>node6
apsvrlgprlfydlfa-vghkmqgplt-------hdptvh-skd------
igr-ppfhdsqlgcfac-------aiqlakslyyilk-napgkpkppaya
pkv-------epesfgrlmkl--adayqdagvake---------------
--lqhhkarfkkacs-n---sn---dladgklhah-----liymkey---
-dpv-keflgaegffq---iggtq--sael-aqasigcnsktayggypfk
kphqh--------lhiypllcpenvwv--avgsavrplmrslgpgtyqlt
rltqvpylipgpasgalnkkvac---slagg-ghvltpawlpglrsllyn
ttae-dgl---lyrvgphkcs--ktstetyde----wtttc-------sv
lgstktdghgkndrarllqncstpyggltkrssllack-skhdrtgiggv
eaaepnvlvakfpt---vkek---kvery--ahglvlkgvn------gnk
kcdtatpcdyvnfklncnclfqqqv-hdkkyqadldt-gkkvieivcnek
-----gpgrmimtleavhegvngpk---rilrnvcl---pcv-------q
--------nnpfvpk----yhqk-keypk-av
>D
aspvrlgp-lfyeifa-ighkmqgslt-------hdpavh-gkd------
igk-ppfhdsqlgclac-------ai----slyyilk-sapgkpkppaya
pkv-------epesfgrlkklqsadayqdagvake---------------
--lqhhkarfdkpis-n---sn---dqaegklhah-----liymkqy---
-dpvikdflggegffq---aggtq--sadl-aqssivcnsktnysgypfk
kphqh--------lheypllcpetvwv--avgtavrplrrslgpgtyhlt
rltetpylipgpasgalnkkvac---slsgg-ghvltaawlkgllslvyn
ttaefdgl---lyrigpnkct--ktstntyde----wtttc-------iv
lgstktdghgkndrdrllqnc--ayggltkrstlltcn-rkgdrtsigdv
egaepnvkiakfpt---vkek---kvqsy--shglvlkgvn------gtk
tcdtgspcnlvgfklhcnclfqqqvfhekkyqtdldt-akkvi--acnek
-----gpgrmiitlesvhkgvngpk---nllrnvcl---pcv-------e
--------ndpfvpk----yhrk-kpypk-av
