>node14
-------------rs-kstpenfpslai---aya-gphstfegkqltkft
wvalat----hkvtle-tp--lqrsiaad--kqaipgfi-sqnckqlrlg
-yk-mhktfnngnliyaimgaac-syktpavgsgt-------tysfkasa
heawfld--dpgdihp--kk-sld-nq----ngveed--eqdsgk-----
------aaggphgrntvngpyqdenp-farytmamklslnssfpvvrtqs
sys-----hsfgsldkyvtgd------------skhcgcvvvrptkhvip
plt--detnpswspthksdrseasgrcnlf----anpaggg---gsdsld
vkpeflsalyg-vaessid-----kl-vdepgvk-aramhlvkaavadg-
lleypn-leymgs---kisvsnlagqaadgskykkt--tqrnprecspvl
aqsgvhlqiqfsldaakt-------------etkfttccdtilriigpak
fcrrpkdaeittgeea-ndq-la-----------qritggtfnccfgyl-
yvtqslgaklrhdfyahktsdpklvlllkveqdksckkypkallggnrhk
ds--twksapwidpneqllsnavtpkkng
>node3
-------------qn-ksgppnftgllv---py------thsgkqltrft
rvplat----yeiske-ap--lkrsigev--kqaiqgfi-sqnckelrlg
-gr-aqnffnhgsliyailgldr-syktpavgegsnlphlepnysfapaa
hhawfmd--dsgdvqs--kk-slk-sq----ngneqd--ehdgak-----
------aapgnqgrntqnaayndeap-fgfytvgrtm------pivhtei
gns-----ht--alngqvsgpr----gnscdqlskycacivvkptnrvap
ni-----fhpsrnpthk-srgtqvarcnlf----akpaagv---gsdtle
vkpeflatlyggaeegmikfteltnl-vdqpgvk-sqvmqlvkayvcdg-
tlefpseldylep---kislsklkgqeadgskfkkt--sqkspracgpvl
ahsechlqyqfalnlpks-------------qhkfvtccdsil----sad
fg-rqkdadivhedep-neq-ld-----------qritactfnccfgyl-
ystqs--eklrhnlyghkatepklvalqkveaek------------svhk
dsehawrtapavtphaell---inpqris
>H
-------------rs-kstpqdypslaf---ayq-gphstfegkqlakfk
wvtvaq----rkvtlentp--lqrsmsad--kesipgff-fqnckqlrlg
-fk-rhktfndgsliyaimsaaccgyktpkvasmt-------tysfkpes
hkvwfld--epgginpslrkmnlgcne----hgvqed--ehdngh-----
------gaggpqgrhdvnsryqdeap-farytmamkislnssfpvvrsql
sya-----nslgdkdkyvtgq------------skhcgcvivrasknvip
slt--getnpewfpthssqrsevtgkcnff----anlagig---gslnld
vtpeflaalyg-aashsin-----kl-vddpgvk-trgmhlvkvavgdg-
lleyae-letlat---kislsnlaghkaegseykk-----------tpvl
rvsgghihcqfgmevakt-------------eskyttccntilriagkav
fcdrpsqaeittgkda-pdr-laevagpidewaiqritggtfasctqyl-
fikasfgsklrhdfyahktndqklvlilkpeqdksckkytkalvggnrhk
dg--thkcapwidpneelltqasmpnang
>E
-------------rtlkvsadqfpslet---anaggphsifevkqlakfk
wvalgt----skvtle-ts--qqrstatd--kqafagfi-wqnck-arlg
-ya-lfksfnngnliyaikgpvc--fktpal---------------rgsa
hnnwflnlwgpgdipp--kn-nld-gq----nsveedk-dtdagk-----
------aagdphsrntvngpypdqnp-aawytmamalslishfpvvisqg
nys-----hgfgslekyitga------------skhygclvtkpskhvip
plscedqtgpawsptqrtekseasgrcklfckdeadpgdgag-qgsdsld
vepefvkalfg-vaeatld-----elnvdepgvk-pramhfvemsvadg-
lleypk-leymg-------cgnlighsadnpyckir--tqrdprecspvl
sqtgvnllihfsldgant-------------ytkflsccdtilringsan
fcrrpkradittgeearndq-la-----------qsraactfnccwgyl-
ystqglsanlkhp--------pkdvlalkvgqdeqckkygkalvsgnrhk
ds--nwksapwidpgdkatrnavappkna
>node7
-------------qn-ksapenftgllv---ay------thsgkqltrft
wvalat----yqitke-ap--lkrsiged--kqaiqgfi-sqnckelrlg
-sk-mqkffnngsliyaimghar-syktpavgngtnlphlnpnysfaaaa
hhawfmd--dsgdvhp--kk-sln-sq----ngheed--eqdgak-----
------aasgnhgrntingpysdeap-fgwytmgrtl------pivhtea
sns-----htfgalnkhvtgar----gnscdqlskycacivvrptdrvap
dit--defnpsrspthk-drgaavgrcnlf----akpaagv---gsdtld
vkpefltalyggaaepmik-----nl-vdqpgvk-sqvmqlvkagvcdg-
tlefpndleylgp---kisvsnlkgqeadgskfkkt--sqkspracspvl
aqsevhlqfqfalnlpks-------------qhkfvtccdsil----pak
fssrpkdadivtedep-neq-la-----------qritagtfnccfgyl-
yttqs--dklrhdfyghkasepklvilqkveaek------------srhk
dsehawrtapsvkphaellspavtpqrts
>node10
-------------rt-kvtadqfpslet---anaggphstfevkqlakft
wvalgt----hkvtle-tp--lqrstaad--kqafpgfi-wqnckqmrlg
-ya-lhktfnngnliyaimgaac-tfktpalgkga-------tfsfrasa
hnawfln--gpgdihp--kk-sld-nq----nsveed--etdagk-----
------aagdphsrntvngpypdqnp-iarytmamtlslnsnfpvvvtqs
nys-----hsfgslekyvtge------------skhygclvvkptkhvip
plscedqtgpawsptqrtdrseasgrcklfckdqadpgdggg-qgsdsld
vlpeflsalfg-vaeasid-----kl-adepgvk-aramhfvnmsvadg-
lleypk-leymg-------vgnlagqaadnskykkt--tqrdprecspvl
aqtgvnllihfsldgakt-------------etkfktccdtilrivgpan
fcrrpkrtdittgeea-ndq-la-----------qhrtagtfnccwgyl-
ystqglgaelkhe--------pkqvlalkvgqeeqckkypkalvggnrhk
ds--twksapwidpneratsnavtpkkng
>A
-------------qg-ksgppnftgmlv---py------thsgkqlsrft
svplat----yeieqe-ap--lkrsigev--thsiqgfilfqnckelrlg
tgrvaqnffnhgsliyeilgler-syktpavaegsnlphlqpdysftpaa
hhawfmd--dgndvh-----------q----agnpqd--ahdgak-----
------aapgnqsrntqnaayneepp-fgfytvaqtm------pivqvee
gns-----hv--alngqvsgpr----gnsceqlskycacivvkptnrvap
ni-----fnpsknpthk-shgsqvprcnlf----atsvagv---gsdtke
vkpeflatlyggaeegvikfteltnl-vnqpgvk-sqvmqhvkvyvcdg-
rldfpseldyldp---kislsklkgqeadgtkfkkt--tqkkprvcgavl
ahsqchlqyrfalnlpks-------------qhkfvkccdsil----sad
fg-rkhdadivhedep-neq-ld-----------qritactfpccfeyl-
hstqs--fklrhnlyghkgtepklvalqkveaek------------rvhk
dsehawrtppsvtpaaell---inpqris
>node13
-------------rs-kstpqdfpslaf---ayq-gphstfqgkqltkft
wvtlat----hkvtle-tp--lqrsisad--kqaipgfi-fqnckqlrlg
-yk-khktfnngsliyaimgaaccgyktpkvgslt-------tysfkpss
heawfld--dpgdinpplrkmslg-ne----ngvqed--ehdngk-----
------aaggpqgrnsvngryqdekp-farytmamklslnssfpvvrtqs
sya-----hslgdkdkyvtga------------skhcgcvvvkatknvip
slt--detnpswspthksqrseaagkcnlf----anpagig---gsksld
vtpeflaalyg-vadssin-----kl-vddpgvk-trsmhlvkaavadg-
lleypn-lenlgt---kislsnlagqkaegseykk-----------tpvl
kqsgghiqiqfsmeaakt-------------etkyttccntilriigkav
fcrrpsdaeittgeds-qdr-laqvagpidewaiqritggtfnccfvyl-
fikesfgaklrhdfyahktndpklvlllrveqdksckkypkalvggnrhk
ds--twkcapwidpneelltqasmpkkng
>D
-------------qn-rsapenfsgvla---ay------ansgklltrfr
wvalat----ykavke-ap--vkrsigedvtkqaiegfi-aqackplrla
-nk-kqklfdngdlvkasigdar-lyktaavgndtslphnnpsysfapak
hhawflq--dngdvhe--kk-sln-ss----dgneed-kerdgam-----
------agsqnhardainepykdepa-fawyimgrtl------pvvhtka
tnsnvqngntfgaltkhltgak----tntcdqvskscscivvrtsdrvap
nkv--npynsskspkhk-drglavgrcnlf----aksaagv---gsskid
akpdfltalyggeaepmhk-----nv-veqsvvk-nqsmqlvkagacdgr
tgefpndldymgp---k---snkkaqagdgsnfkks--sqkapriyapgl
araevhlqfqfqlnipkskaniesknnkgdlqnnyvtccdrvl----pak
fsgagkeapivkkdsp-detglv-----------qrctagtfsccfgyl-
fktpa--dvlrhdfyghkasdpklvilqkvesek------------shnk
etehawrtganvkpqaellsq----hrtk
>F
asssivcemagltrt-kvtadqfpslet---gnaggphstfdgkelakfs
wvvlgt----hkvile-ap--lqrstaad--rqafpgfk-weickklrlg
-ya-lhktfnngnlpyaimgapc-tfktpalgkga-------tfsfrasa
hnawfln--gpgdiha--kq-tld-nadfdnnsveed--etdagn-----
------aagkpnsrktvggtypdqhpqiaryamamtlalnsnfpmvttqs
nys-----hnfgslqkyvtge------------tkhygcfvvkpskhvip
plnceeqsspawsptertdrsrtsgrckl--kdqtdpgdgggtqgpdsld
vlpeflsalfg-vaeaaid-----kl-ddgpgvk-aralsflnktsadg-
ladypk-vdymg-------igdlagqaadswkykkkyktqrearecspvl
aqtgvnllihfsldgakt-------------etklrtccesilriigpan
fsrrpkrtevttgeea-ndv-la-----------qhqtsgtfnccwgyl-
ystqglgaalkhe--------pkhvmalkagsqqdckkyektlvsgkrhk
ds--twk-tpwldpnerstsnavtqkkng
>node6
-------------qn-ksapenfsgllv---ay------ahsgkqltrfr
wvalat----yktvke-ap--lkrsiged--kqaiqgfi-sqackplrlg
-nk-mqkffdngdlvkanmghar-vyktpaigngtnlphlnpsysfapak
hhawfmq--dngdvhp--kk-sln-sq----ngheed-keqdgtk-----
------aasqnhgrnainepyrdeaa-fgwyimgrtl------pvvhtea
snshgengntfgaltkhltgak----tnacdqlskycscivvrtsdrvap
nit--dpfnssrspkhk-drgaavgrcnlf----akpaagv---gsskid
akpdfltalyggeaepmvk-----nv-vdqpvvk-nqvmqlvkagacdgr
tgefpndldylgp---kvsvsnmkgqeadgskfkkt--sqkspricapgl
arsevhlqfqfqlnipks-------------qhnfvtccdrvl----pak
fsskskeaeivtkdsp-aeqgla-----------qrctagtfnccfgyl-
yktqt--dvlrhdfyghkasepklvilqkvdaek------------srnk
esehawrtgenvkpqaellsp----qrtn
>B
-------------qn-ksgapnytavlv---py------thsgkqvtrfn
yvslvtdskfyeipkn-agcamkrsigev--kkattgfi-sqnckelklg
-gr-lqtffnhsstiygilgldr-gyitpavgessglphlepnysfaaaa
hhawfmd--dsgdv-v--kk-slk-tq----ngndqd--ehegak-----
------aapgqqgrnsqkaayndeyp-fsfyevgstm------pivntei
gns-----ht--alngqvvaprypqngnscdqlskicaclvvkptnrvap
ni-----fhpsrnpthk-srgtevarcnlf----akpaagv---gsdtle
kkp-flrttyggaeaamakftaltsl-vdepstkvsq--hlakattcng-
tlqlpsqldylepthrkisprkakgqeadgcrfkkt--seaeprscvevl
ahsecqlqyqfgvhlpka-------------qrkfttccdsih----sad
vg-rqkdadivhgdep-neq-id-----------qnitactfn--fgyl-
ystqs--eklrhnlyghkatepklvaqqkveaek------------tvns
dsehawrpgpavtpqadll---inphris
>C
-------------qn-ksdpanfsgllv---ay------aysgkeltrfq
wvvlgt----yetvke-ap--lkraiged--kqaiqgfi-sdackplrlg
-nk-mkkffdkgdlikatmasar-vyktaaigdgtnlshlapwysfapak
qhawamq--gngdvhp--kk-sl---q----dgqeed-keqdgtk-----
------atsqnharntinepyrdeaa-fgwyimartl------nvvhtea
pnghgehgnifaaltkhltgak----teacdqlnkhcdcvvvrtsnrvap
nat--dsfnaskrpknk-drgaaagranlf----atpahgh---gspqie
akpdfltalyggeaepmkr-----nv-vdqpvve--dvlqlvkaggcdgr
tgefpndlaylgp---kvsagnekgqeadgskfkkt--sqksprvcapgl
srsevhlqfpfqlnipks-------------q-nfvtccdrvl----rak
fssqskqaqivteenp-aeqgla-----------rqctagtfncyfgylk
yktqt--kvlrhdfyahkasepklvilrkvda------------------
-sehawrtgenvkpaaellsp----qrsn
>G
-------------nr-rtmpnnfpalaflefayq-gpharfqgkaltkft
wvtlst----hklaad-ts--lqrsiatd--krvipafi-fqnckqlkla
-yk-khktfnngsl-yavtgpyccgyktpkmaslt-------tynftpss
heawfld--dpgdinaplrkmslg-ne----ngfqed--dhdngkpvfsf
kklinyaaggpqernsvpg---dekp-faqytmppklslnssfpvfrtqs
nya-----hglgdkdkltdga------------skhcgctrvkatknvip
slt--devkppwspthksgrseaagkcnll----anpagig---gsksld
vtpeflaalyg-vaeesin-----kl-vddpgvk-tasmhlvkaavadg-
lldipn-lehlgt---rislsnlagqkaegseykk-----------tpvl
teagghiriefsteaakk-------------etkystccnsilriig-tv
fcrrppeaeitvgddk-qdr-laqvagpidewvirrvtdgtfnccflyl-
fikgsfgakvrhdfyahkknapkwvlllrveqnksckkypkslvagnrqk
ds--twkcaswidvceellaqsampkkkg
>node15
-------------rs-ksapenftslav---aya-tpwsthigkqltkft
wvalat----ykitke-ap--lqrsised--kqaiqgfi-sqnckelrlg
-yk-mhktfnngnliyaimgaar-syktpavgagtnlphlnstysfkaaa
hhawfmd--dsgnihp--kk-sld-sq----ngheed--eqdggk-----
------asggnhgrntvngpyadenp-farytmgqklslnsafpvvhpqs
sns-----htfgslnkhvtga------------skycgcivirptdhvip
dlt--defnpsrspthk-drseavgrcnlf----akpaagg---gsdsld
vkpefltalyg-haepmid-----kl-vdqpgvk-aqvmqlvkagvadg-
llefpndleylgp---kisvsnlagqaadgskykkt--sqkspracspvl
aqsdvhlqfqfslnlakt-------------qhkfvtccdsil----pak
fcrrpkdadittedea-ndq-la-----------qritggtfnccfgyl-
yvtqsvgaklrhdfyahktsepklvilqkveqekacgkypkallggsrhk
ds--twksapsidpnaqllnpavtpkrtg
