>node18
asmpt--q-s---ganhgl--vmr--clchialk----------------
--sd-ycpvfltlqhpnyeniaigvhai-----a----------------
----------laaddsrvkhs---flpfpvyfinkdhvadfyalfsrheq
ntah--akg-ivaavcyhiknfvvgntslalegynr--lkinlliekgsv
kfkaqaylklpng----e--------akfykvavekt-vaksgkdgvgaa
--eqrscf-----gendgflvrtferk-lkflgkad-------slclnya
gdmkachlvlvgsmsmnk-clvgntslkqgnkvwglrcqiaahfkyrrrp
tivv---twgg--------kdivdtqvyavn----pyggdghhfcakaqe
ahmleedvka------------------d--l-vqiepeisantikgy-p
----lka-na---------vvgpeladl-ehfqlvvhrdag-----vifl
frapsv--reegtaegggda-gycnallnclpedela--sv---v-----
-----scqeigqlr--tvqdg-aemsvktfepa---ktgaqassfkfgrf
--llktaayhvpilnmg-i--------sscqglcglnyvdgsswalv---
-qvqivehatirvqdlhlrasvfva------niskfahykepagvkfpre
--------lhiqgihg
>ENV_SIVG1/22-522
atkateht-sslva----l--vle--clchiagk----------------
--sd-ycgvlltqqepkyesiliglqnf-----na---------------
-----lpatvlsaddnrikht---vlpyaayfigkqhvadfcclfakqke
patq--ykg-vvpyi-----qfvvdstslvrygfkr--lkvnllvknsrv
tykthtllklpegvkavege-----n-kr------ktgvankg--dvkae
--dlvscf-----geahdflvrsfsqr-lkflgkgd-------alcldyg
s-msic-----------s-cp-gnatlkhgndiwnvrylialgytyrrrp
pvv----awsg-----kgakdivdtdvqavn----pcgsvghp----aqe
shrdkedvkasqcs-tfvte--kaeapvq--l-vgadpdtgfs-ikgy-p
----vkaaktaevadvppaitaqalsdldehyqlv-------------fl
yrapsg--radg------dd-gyynmml---pedqlg--sv---t-----
-----ncdhvgqlk--vtqds-aaitfktfepa---krgsqtpsvifscy
cpqldtp-----slekg-vinepkihatschslcgleyidgatwa-----
--------aevrvqslhlststfcn------vverfghlsvprggklpre
--------lqingi--
>ENV_SIVGB/47-569
vtkga--qlghvvahlhktatikqcactahvavk----------------
--sd-fcnvklkqknpvc------lnnfdvkllaaekgkkstcafcaqye
heqatllvtalqpqdetgrha---ilrysaffvkshhvdgfpcvfgrqdd
paaq--yqgvavpavc-l-tefvvkqtdfqragikrltl--eimlktgrv
k-----ylalpeg----qas-----v-kr------rt-vtkra--gvkse
--evwacfgqsepkda----irifeqr-erflangdnattegvqlcldyr
a-mtfchrph---lg--tecv-gdtt-----------yqvrlgytyqkrp
pvl-llvalvg-----redrdq-qnkvqgvgsacrsfisvghhycattqe
qlrdkksvtrshvvvsfiietvklegavq--l-tgadpqigrt-vkgy-h
sfpriktgksqdieevspsmtvpafsqtveyyqlv-------------fv
yagp-v--trhs------caggyismei---qdeqlgagas---t-----
-----scdhiphlknkvkeegtaaml---sdpg---krgnnadavkysrf
pplhnpg-----ylekvrs--------tschtlcglehtdacswa-----
---------------lnq--qkhcg------svnrygrlsqprg-----a
--------nhisgv--
>node8
atkat--q-sslvarnhkl--vlq--clchiaak----------------
--sd-ycgvlltqqepkyesiliglqaf-----da---------------
-----llstalsaddnrvkht---flpfpayfigkdhvadfcclfarqne
patq--ykg-vvpsvc-qitqfvvdntslvrngykr--lkinllvktgrv
kykthtylnlpeg----egd-----s-kr------ktgvakrg--gvkae
--elvscf-----geahqflvrsfeqr-lkflgkgd-------slclnyg
s-mgichspl---mg--s-cp-gsttlkhgndvwavryqialgytyrrrp
pvv----awgg-----ksdkdivdaqvqavn----pygsvghhfcakaqe
shrekedvkasqcv-tfite--kieapvq--l-vsadpqigss-ikgy-p
----vkaaktqdiadvppamtapalsdldehyqlv-------------fl
yrapsv--raeg------dd-gyynmml---pedela--sv---v-----
-----scdhvgqlk--vtqdg-aamtfktfepa---krgaqassvkfgrf
ppilktp-----ilekg-i--------tschslcgleyvdgatwa-----
--------atvrvqslhlststfcn------tvskfghlseprgvkfprq
--------lhingi--
>ENV_HV2G1/23-502
gsmpq--q-s---vanhgl--vmr--clchialk----------------
--sd-ycpvfltlqhpnyeniafgvhai-----a----------------
----------laaddsrvkhs---fl---vyfinkdhaadfyalfsrheq
ntah--vkg-ivaavcyhiknfvvgntslalegynr--lkinllvekasv
afkaqaylklpng----e--------a--ykvevekt-laksgksgvgae
--eqrscf-----gendgflvrtfgrk-fkflgkad-------slclnya
gdmgec-svlvgsmsmnk-clvgntslkqgtkvwalrcqiaahfkymrrp
tivv---twgg--------kdivdtqvyavn----pysgdghhfcaqaqe
ahmleedvka------------------d--l-vqiepdisansikgy-p
----l---na---------vvgpeladl-ehfqlvvhrdag-----vifl
frapsh--reegtaegggda-gycnallnclpedela--sv---a-----
-----scqeigqlr--tvqdg-aemtvktfepv---ktgaqasgfkfgrf
--llktsayhlpilneg-i--------sscqglcglnyvdgsswa-----
--------atisvqdlhlrapvfvaccisdlniskfahykepagvkfpre
------pelhiqgihg
>node7
atkatehq-sslvarnhkl--vlq--clchiaak----------------
--sd-ycgvlltqqepkyesiliglqaf-----na---------------
-----lpstalsaddnrikht---flpyaayfigkqhvadfcclfakqne
patq--ykg-vvpyi-----qfvvdstslvrngfkr--lkvnllvktgrv
tykthtflklpegvksvege-----n-kr------ktgvanrg--dvkae
--elvscf-----geahqflvrsfeqr-lkflgkgd-------slclnyg
s-msic-----------s-cp-gnatlkhgndvwnvrylialgytyrrrp
pvv----awsg-----ksekdivdtqvqavn----pygsvghhfcakaqe
shrekedvkasqct-tfvte--kieapvq--l-vgadpdtgss-ikgy-p
----vkaaktaevadvppamtaqalsdldehyqlv-------------fl
yrapsg--radg------dd-gyynmml---pedqlg--sv---v-----
-----ncdhvgqlk--vtqdg-aaitfktfepa---krgaqtpsvkfgry
cpqldtp-----ilerg-vinepkihatschslcgleyidgatwa-----
--------atvrvqslhlststfcn------tvsrfghlseprgvklprq
--------lqingi--
>node17
asmpt--q-s---ganhgl--vmr--clchialk----------------
--sd-ycpvfltlqhpnyeniaigvhai-----a----------------
----------laaddsrvkhs---flpfpvyfinkdhvadfyalfsrheq
ntan--akg-ivgavcyhidnfvvgntslalegynr--lkinlliekgsv
kfkaqgylqlpng--------------------------aksgkdgvgaa
--eqrscf-----gendgflvrtferk-lkfpgkad-------slcltya
gdmkachlvlvgsfsmnk-clvgntslkqgnkvwglrcqiaahfkyrrrp
tivv---twgg--------kdivdtqvyavn----pyggdghhfcakaqe
ahmleedvka------------------d--l-vqiepeisantikgy-p
----lka-na---------vvgpeladl-ehfqlvvhrdag-----vifl
frapsv--reegtaegggda-gycnallnclpedela--sv---v-----
-----scqeigqlr--vvqdg-aemsvktfepa---ktgaqassykfgwf
--llktaayhvpilnmg-i--------sscqglcglnyvdgsswalv---
-qvqivehatirvqdlhlrasafva------iiskfahykepagvkfpre
--------lhikgihg
>node19
asmpt--q-s---ganhgl--vmr--clchialk----------------
--sd-ycpvfltlqhpnyeniaigvhai-----a----------------
----------laaddsrvkhs---flpfpvyfinkdhvadfyalfsrheq
ntah--akg-ivaavcyhiknfvvgntslalegynr--lkinllvekgsv
kfkaqaylklpng----e--------akfykvavekt-vaksgkdgvgae
--eqrscf-----gendgflvrtferk-lkflgkad-------slclnya
gdmgachlvlvgsmsmnk-clvgntslkqgnkvwalrcqiaahfkyrrrp
tivv---twgg--------kdivdtqvyavn----pyggdghhfcakaqe
ahmleedvka------------------d--l-vqiepeisantikgy-p
----lka-na---------vvgpeladl-ehfqlvvhrdag-----vifl
frapsv--reegtaegggda-gycnallnclpedela--sv---v-----
-----scqeigqlr--tvqdg-aemtvktfepa---ktgaqassfkfgrf
--llktaayhvpilnmg-i--------sscqglcglnyvdgsswa-----
--------atirvqdlhlrasvfva------niskfahykepagvkfpre
--------lhiqgihg
>ENV_HV2D2/24-513
asmpt--e-s---aanhgl--vlq--clchiaak----------------
--sg-ycpvllalddpnyeniaisvhai-----p----------------
----------l---------s---flpfpvyfinkdhvadfyalfsrhep
ntah--vkg-iiaavcfhidnfvvgntslalegfni--lktnllvekgsv
kfnaraylklpng----e--------akry--------vakkg--gvgae
--dqrscf-----get--fltktferk-lkflgkad-------slclnya
admgvchavl---msmnn-slvgndslkqgnkvwavrcqisahfk----p
pivs---twgg--------sqvvslqcyavn----a------hfcakaqe
ahmleedvka------------------d--lavriepeisantvkgy-p
----lkaand---------vvgpqle-l-evfqlvvhrdagasnhdvifl
frapsv--rgegtaagggda-gfcgalvlclpeddla--ta---v-----
-----scqefgqlr--tvqns-aemtvkvfepa---ktgaeassskygrf
--llktaafhlpilnkg-i--------nqchal--------tswa-----
--------atirvqdlqlrssvfig------nvsgfahykepagvrfare
--------lhiqgihg
>ENV_SIVM1/24-528
asmpt--q-ssvvasnhnt--vlq--clchiavk----------------
--sd-ycpvlltlqnpnyenieievqpi-----a----------------
----------laadnsrvkhshqvflpfpvyfinkdhvadfyvlfsrhee
ptan--ykg-ivsavcfpiknfvvgntklvldgynr--lkinllvekgrv
kfkyeaylklpng----e--------akryrvaaekt-vakkg--gvgaq
--eqrscf-----gesdgflvriferkllkflgkad-------slclnya
gdkgachavl---ms--n-clvgnaslnqgnevwavrcdiavhfkyrrrp
pivv---twgg--------kdivdtqmyavn----pygadghhfcakaqe
ahlleedvka------------------d--l-vqvepeisastikgy-p
----lkaakd---------vlgpeladl-ehfqlvvhrdag-----vifl
frapsv--reegtaegggaa-gycnallh--pedelg--hv---v-----
-----rcqeigqlr--tvqdg-aemtlkafepa---ktggqassfkfgef
--llrtaafh--ilnkg-i--------nschgl------dgstwa-----
--------ttirvqglhlrasvfva------siskfghygepagvkfpre
--------leiqsihg
>ENV_HV2D1/24-501
aslpa--q-s---ganhgl--vmr--clchialk----------------
--ad-ycpvflslqhpnyesigigvhai-----a----------------
----------laandgrvkhs---fmpipvyfinkdhvadfyalfspheq
nvah--a-g-vvnavcyhien-vvgntslalegynr--lkinlliergvv
kfkaqaylklpng----e--------ekfykvavent--aksgkdgvgea
--eqpscf-----gendsflvrtfdrk-lkflgkad-------slcmnya
gdmkachlvlvgsmsmsk-clvgdtslkqgskvwglrcqiaahfkyrrra
tiev---twgg--------kdivdtqvyavn----pyggaghhfcakaee
ahmgeedgka------------------d--l-vkiepeisantikgy-p
----lka-na---------vvgpelatl-ehfhlvvhrdag-----vifl
frapsa--reegtaegggta-gycnallnclpedela--svrfiv-----
-----scheigqlr--tvqdg-aemsvktfesa---ktgaiasgfkfgrf
--llkaaayhvpilnmg-i--------sscqglcgltyhdgsswahv---
-qvqivehatirtqd--------vp------niskfahykepdgvsfprh
--------lhirgihg
>ENV_HV2BE/24-510
asspt--a-s---ganhgl--lmr--clchialqvlrlglksyhqfqemv
kgsdaycpvflslqhpnykniaigvhai-----a----------------
----------laaddsrvkhs---impfpvyfinkdhvadfyalfsrheq
ntah--vkg-ivngvcyliknfvvantslalegynr--lkvglliekgsv
kfkaqaylklpng----e--------akfykvavekt--aksgkdgagaa
--eqrscf-----gendgfllrtydrk-lkfvgkpd-------slcmnya
ggikachlvlvgsmsmnk-clvgntslkqgnkvfglrcq---hfkyrkrp
tiev---twggegeqq---kdivetqvyavs----pyggdghhfcdkaqe
ahlleedv-a------------------d--e-veiqpeinantikay-p
----lka-ka---------avgpeladl-ehfqlvvhresg-----viyl
fsapss--reegtaegggsa-gycnallnclpedela--sv---v-----
-----scqeigqlk--avkdg-anmsvktfept---ktgaqassfkfgrf
--llktaayhvpilaig-i--------ascqglcglnyvdvsswalvtva
lqvqivehttigvqd--------vg------niskfahykepagvkfpre
--------lhiqgihg
>ENV_HV2NZ/24-502
asmpt--q-s---gtnegl--lmr--clchialk----------------
--sd-ycpgflilqhpnyeniaigvhai-----a----------------
----------laaddsrvkhs---flpfpvyfihkdhvddfyalfsrheq
ntak--akg-igsavcyhtdnfvvgntslalegynr--lkinlliekgsv
kfkaqvylhlpng--------------------------aksgkdgvgva
--eqsscf-----gendgflvrtfdrk-lkfpgkad-------glclaya
gdmkachlvlvgsfsmnk-clvgntsfkdgnkvwglrcqiaahfkyrrrp
qivv---twgr--------kaivdtqvyavn----pyggdghhfcakaqe
ahmieeqika------------------d--l-vqiepeisantikgyhp
----lka-nh---------vvgpqladl-ehfqlvvhrddg-----hvfl
frapsv--reegtaegggta-gycnallncltedelt--sv---v-----
-----scqeigqlr--vvqdg-aemsy---epstrgitgvqassykfgwf
--llktaayhvpiqgmg-i--------sscqglcglnyvdgkawflv---
-qvqiiehatvrvqdlhlrasafva------iiskfaqyktpagvkfpre
--------lhikgihg
>ENV_SIVV1/24-538
ptkatehq-ssltarnhkl--vlq--slcqiadk----------------
--sd-ycgtlltqqdpkyesilv---av-----na---------------
-----lpsaalaadddrikpt---flpysayfigkqhvadfcclfakqag
pptsseykg-lvnyi-----qfvveshsvvrhdfkr--lkvnllvktgrv
sykshtflklaegvk---gigfknfn-kr------kcgvanrg--dvkae
--elvscf-----gqanqflvrsfrqr-lkfigkgd-------slclnyg
d-msvc-----------s-cn-gnatmghgnevwnlrylvalgytyarrp
pvv----awsa-----kskkdiidspvqavn----pygslghnfcvka-e
shrekekiksaqct-tfvte--kieapvp--l-vgadpatggs-ingy-p
----vkaaktdhvadtppamaaqalsdlkehyqla-------------fl
yrapsggvradg------dh-gycslmm---pedqlg--sv---vmarlg
defvkncdhvgqlk--vtqdn-aaityktfepa---krgsqtpsvkigry
cpqldsp-----iler--vvnepkvhatcchtlcgleyadgst-------
---------tvrveslhlsasffcn------tvgrfghlsepravklpqh
--------lqin-i--
>node11
asmpt--q-s---ganhgl--vmr--clchialk----------------
--sd-ycpvfltlqhpnyeniaigvhai-----a----------------
----------laaddsrvkhs---flpfpvyfinkdhvadfyalfsrheq
ntah--vkg-ivaavcyhiknfvvgntslalegynr--lkinllvekgsv
kfkaqaylklpng----e--------akfykvavekt-vaksgkdgvgae
--eqrscf-----gendgflvrtferk-lkflgkad-------slclnya
gdmgachavlvgsmsmnk-clvgntslkqgnkvwalrcqiaahfkyrrrp
tivv---twgg--------kdivdtqvyavn----pyggdghhfcakaqe
ahmleedvka------------------d--l-vqiepeisantikgy-p
----lka-na---------vvgpeladl-ehfqlvvhrdag-----vifl
frapsv--reegtaegggda-gycnallnclpedela--sv---v-----
-----scqeigqlr--tvqdg-aemtvktfepa---ktgaqassfkfgrf
--llktaayhvpilnmg-i--------sscqglcglnyvdgsswa-----
--------atirvqdlhlrasvfva------niskfahykepagvkfpre
--------lhiqgihg
>node14
asmpt--q-s---ganhgl--vmr--clchialk----------------
--sd-ycpvflslqhpnyeniaigvhai-----a----------------
----------laaddsrvkhs---fmpfpvyfinkdhvadfyalfsrheq
ntah--akg-ivnavcyhiknfvvgntslalegynr--lkinlliekgsv
kfkaqaylklpng----e--------akfykvavekt--aksgkdgvgaa
--eqrscf-----gendgflvrtfdrk-lkflgkad-------slcmnya
gdmkachlvlvgsmsmnk-clvgntslkqgnkvwglrcqiaahfkyrrrp
tiev---twgg--------kdivdtqvyavn----pyggdghhfcakaqe
ahmleedvka------------------d--l-vqiepeisantikgy-p
----lka-na---------vvgpeladl-ehfqlvvhrdag-----vifl
frapsa--reegtaegggsa-gycnallnclpedela--sv---v-----
-----scqeigqlr--tvqdg-aemsvktfepa---ktgaqassfkfgrf
--llktaayhvpilnig-i--------sscqglcglnyvdgsswalv---
-qvqivehatirvqd--------va------niskfahykepagvkfpre
--------lhiqgihg
>ENV_HV2CA/25-512
asmpt--q-d---gakhgl--vmr--clchialt----------------
--sd-ycpvfltl----yeniaigvhai-----a----------------
----------laaddnkvkhs---flpfpayfinkdhvadfyalfsrheq
ntan--akg-ivgavcyhidtlvvgntsldlegynr--lkin-liekgsv
kyka-gylqlpng--------------------------aksgkdgvgaa
aaeqrscf-----genggflvftferk-lkfpgkad-------ilcltyg
gdmkgchlllvgsfgvnk-clvakssldqgnnvwaircqqaahfkyrrrp
sivv---twgg--------kdimdaqvyain----pyggdghhfcakaqe
aheleedvka------------------dall-vqiepeisantikgy-p
----lka-ns---------vvgpeladl-ehfqlvvhkdad-----vvfl
frapsv--reegaaegggda-gycdallnclpedeia--sv---v-----
-----scegvgqlr--vvqdg-aemsvktfeat---rtgaqassykfgwf
--llkaaaynvpildmg-i--------ssceglcglnyvdgsswalv---
-qvqivehatirvedlhlrasafvp------ilskfahykdaagvkfpre
pdgeke--lhikgihg
>node9
asmpt--q-sslvaanhgl--vlq--clchiaak----------------
--sd-ycpvlltlqnpnyeniaigvqsi-----a----------------
----------laaddsrvkhs---flpfpvyfinkdhvadfyalfsrhee
ptah--ykg-ivaavcfhiknfvvgntslvldgynr--lkinllvekgrv
kfnaqaylklpng----e--------akrykvavekt-vakkg--gvgae
--eqrscf-----gesdgflvrtferk-lkflgkad-------slclnya
gdmgichavl---ms--n-clvgntslkqgndvwavrcqiavhfkyrrrp
pivv---twgg--------kdivdtqvyavn----pygsdghhfcakaqe
ahmleedvka------------------d--l-vqvepeisastikgy-p
----lkaakd---------vvgpeladl-ehfqlvvhrdag-----vifl
frapsv--reegtaegggda-gycnallnclpedela--sv---v-----
-----scqeigqlr--tvqdg-aemtlktfepa---ktgaqassfkfgrf
--llktaayhvpilnkg-i--------nschglcglnyvdgstwa-----
--------atirvqslhlrasvfva------siskfghygepagvkfpre
--------lhiqgihg
>node10
asmpt--q-s---aanhgl--vlq--clchiaak----------------
--sd-ycpvlltlqnpnyeniaigvhai-----a----------------
----------laaddsrvkhs---flpfpvyfinkdhvadfyalfsrheq
ntah--vkg-ivaavcfhiknfvvgntslalegynr--lkinllvekgsv
kfnaqaylklpng----e--------akrykvavekt-vaksg--gvgae
--eqrscf-----gesdgflvrtferk-lkflgkad-------slclnya
gdmgichavl---msmnn-clvgntslkqgnkvwavrcqiaahfkyrrrp
pivv---twgg--------kdivdtqvyavn----pygsdghhfcakaqe
ahmleedvka------------------d--l-vqiepeisantikgy-p
----lkaand---------vvgpeladl-ehfqlvvhrdag-----vifl
frapsv--reegtaegggda-gycnallnclpedela--sv---v-----
-----scqeigqlr--tvqdg-aemtvktfepa---ktgaqassfkfgrf
--llktaayhvpilnkg-i--------nschglcglnyvdgsswa-----
--------atirvqdlhlrasvfva------niskfahykepagvkfpre
--------lhiqgihg
