>node7
ti-ngrkthcyvsetv---h--plvqgdfvc-vef-kdhmwyggn----f
alfl------------c-------mavtevarygprvsaklles-lgdit
dasiafer--gla---siaakhgeshs-----qmnskvl-------tith
yaamrn--ck----r--gwcqlqhgw-is-------cwqqaigltradcy
lyll-tikge--------hwislvk--qpl-----------kny--l-is
krripkfvvgliacl----ggsyk-al-lir---sa----elfhynnmvv
ergkggptmtfrna-----------ievatahatnpghlspl-gsdwswd
kksglgehwlyrrsqkfaatgkgigialnd---ni----pkmddkffdf-
-vkegtdelnkthklssalsg----sgqd-----f-r-hlhsninladp-
inleqhhggmpvcgrs--------dkv-kggidekvfcykarepgp---t
l---lssavtlrrqlg--ksq----hva-------------ggiya----
----ytg-ymshlhdldkm-----------------e----nkpci----
-----siacipsvnhe---h--cgmer--akgr---td-qqlmtl-t--f
sfqkenr-aadphlsdggsggswsal--aeeans---
>node8
ti-ngrkthcyvsetv---h-kpltqgdfvc-vef-kahmwyggn----f
alfl------------c-------mqvtevarygprvsaklles-lgdit
dascaleh--gla---tiaakhgeths-----lmnskvl-------tiah
yaamrt--ck----r--gwcql---l-is-------cwqqaiglqr----
-----tikgd--------hrislvk--epl-----------kny--l-is
krripkfvdgliacl----ggsyk-ah-lir---na----elfhyrsmvv
ergkegptmtfrda-----------ievasqhganpdhlnpl-gsdwswa
hkngfgehwlyrqsdkfaatgkgvgialdd---ni----pkmddtffdf-
-skegsdelskthilsdalsg----sgqnesnyvf-r-hlhsninladp-
inleqhhggmpvcgrs--------dkv-kggidekvfcyaareagp---m
l---lssavtlrrqlg--ksq----hvs-------------ggiya----
----ytg-yisllhdldkv-----------------e----kkpci----
-----ripcipsvnhe---h--cgmer--akgqfyatdvqqlmtf-t--f
sfqkenr-nadshysddgsggswgal--aegens---
>ENV_HV2NZ/24-502
tv-ngrkyhccitear---h-kpvk---------f-ka------------
----ehntaltlaaktc-------i---gvtrqgpigdsklfds-lgdmy
gapcpyeh--gec---tnkakhgsahs-----alkeavliigdspktinh
aagfrsyvck----k--gwcil---l-vnalanlvicwhqavgler----
-----tiksderhprsayhri--vlgattflesndnvcv--kdtsgl-mp
krrilkrv--llgcl----gtsys-ah-lvr---rd----elahyrdmvv
ergkngpymkfrst-----------ievasqqgsyeehldpmggsdwgwa
lkdgfgenwlyrqsd-ftatgkgvpieldearahhtlakesfdetffdf-
-skeaandlsktellstaleg----tgqsskecvl-r-hkhadvrfsdp-
fnleeqqgiiptcgma--------n-----gvsdqvfcyeeedp-----a
l---lss-----rqlgakrdi----wvt-------------ggifakcnk
flasytg-yidllheldkvelvqkn-----------s----skpcirtcp
ayyftklrctknvd-dseahqwckmee--akghyyatavqqllallp--f
nfenair-hteihyaddgkgttwgam--gvgqkg---
>ENV_HV2CA/25-512
tv-narkyhccisear---h-kpvk---------f-ha------------
----ehntaltlgaqvc-------i---gvapqgpigdatlfds-lgdmy
gaacpyeh--gda---ltkakhgsahs-----alkeavaligdspdtinh
taafsg--ck----k--nwciv---l-vsaladlvicwqqevgler----
-----tiksderqrqaayhri--vlgtttylesndnvcva-kdtagl-mp
kkrilkav--llgcl----gtsys-ah-lir---kd----elahyrdlvv
ekgksepyakfrs--------------vasqqgsyeehldpmggsdwswa
lkdgfgenwlyrqtd-ftatgkgvpielteargntalakgtfddtffdf-
-skgasndlsktellgtalng----tgqsssecvl-r-hkdanvrlsd--
------------------------d-----ggdeqvfcyeeqdp-----a
l---lss-----rqlga------------------------ggiflk---
---sytg-yidllheldkvelvqkn-----------s----skpcirtcp
ayyfaklrciknmd-dveaharcsmqe--akghyyavavqqlvallp--f
dfenair-htnihyaddgkgtawgal--gvgkqg---
>node10
tv-nsrkyhccmseav---h-kpvk---------f-ka------------
----ehntaltlgakic-------m---gvarqgpigdstlfds-lgdmt
gascpyeh--gda---ttkakhgsahs-----alneavliigdspktinh
taafrs--ck----k--gwcil---l-vsgladlticwqqavgler----
-----tiksderqrqatyhri--vlgtttflenndnqcva-kdtsgl-mp
krrilkhvdgllacl----gtsyk-ah-lir---nd----elfhyrdlvv
ergkngpymtfrsa-----------ievasqhgsyeehldpmggsdwswa
hkdgfgenwlyrqsd-ftatgkgvpidldeargntalakakmddtffdf-
-skeasndlsktevlsdalsg----tgqsssecvl-r-hkhadvrlsdp-
fnleeqqgivptcgma--------d-----gvddqvfcyeeqdpgp---t
l---lss-----rqlggkrsi----wvt-------------ggifak---
---sytg-yidllheldkveliqkn-----------s----skpcirtcp
ayyfaklrciknvn-e---harckmee--akghyyatsvqqllallp--f
nfqnair-htdihysddgkgtswgal--gvgeng---
>ENV_SIVG1/22-522
ti-ngrtthcyvsetv---t--plvqgdfvc-vef-kdhrwyggn----f
nffl------------c-------msvtev-rygprvsaklles-lgdit
dasiafer--gls---kiaakhgeshs-----qmnskvl-------tish
yaamrn--ck----r--gwcqlqhgw-is-------cwqqaigltrvdcy
lyll-tikge--------hwtslvk--qpl-----------kny--l-ia
krkvpkfvvaliacl----ggsyk-al-liryalsa----dlfhynnmvv
esgkggptitfrnm-----------ievanahptnpghlspl-gsdwswd
kksglgehwlyrrsqkfaatgkgigialnd---ni----pkmddkffsf-
-vkqgtdelnkshklssals--------------f-k-hlhsnisladp-
inldqhhmgmgvcgrs--------dkv-kggiddkvfcykakepgp---t
l---lssavtlrrqlg--ksq----hva-------------ggiya----
----yah-ymshlqdldkm-----------------e----nkvci----
-----tiatipsvnhe---h--camer--akgr---td-qqlmt-----f
sfqkekr-aadphlsdggsggswsal--aeeans---
>ENV_HV2BE/24-510
ti-ngrkyhcciseav---h-kpvk---------f-ra------------
----ehntaltlgakic-------m---gvarqgpmgdstlfds-lgnmy
gascpyeh--gda---ttkakhgsahs-----alneavmiigdspktidn
taafrs--ck----r--gwcil---l-vsaladlttcwqqavglnr----
-----kiksdererqasyhri--vlgtttflenndnvcva-kdasgl-mp
krrilk----llgcl----gtsyk-ah-lir---ndknkkelfhyrdlvi
argkngpymtfrsa-----------id---phgsyeehldpmgg----wa
lkdgfgdnwlyrqsd-ltatgkgvpiekdeargntalakakfddtifkf-
-skelsnelsktellstalsg----tgqspsecvl-r-hkradvilsdp-
fnleeqqgiiatcgmg--------n-----giqdqvfcyeeqdp-----t
l---tss-----rqlggkrsv----wvt-------------ggifak---
---svtg-yidllhelekveliekn-----------t----skpcirtsp
ayyfkklrciknvd-eseahakckmee--akghyyatavqqllalvp--f
dfenairphtdihyaddgkgttwgal--gvgena---
>ENV_HV2G1/23-502
tv-ngrkyhcciseev---h-tpvk---------fska------------
----erntaltlgakic-------m---gvarpdpigdstlfes-lgdmy
gascpyeh--gda---ttkakhgsahslgggyafneavliigdspkyinh
taafrs--ck----k--gwcil---l-vsaladlticwqqaagler----
-----tikvderqrqatyhki--vlgtttflenndnvcvaekdtsgl-mp
krrilkhvkgliacl----gtsfk-ahnllr---dd----elfhyrdrvv
ergklgpymtfrsa-----------ievasqhgsyeehldpmggsdwswa
lkdgfgenwlyrqsd-ftsngkgvpidldeargntalakakfddtffdfi
eskeanndlsktdllsdalsg----tgqssvecvl-r-hkhadvrisdp-
fn---qqdivptcgma--------d-----gvddqvfcyeeqdpgp---t
l---lss-----rnlggkrsi----wvt-------------ggifak---
---sytg-yidllheldeveliqkn-----------s----skpcirvcp
syyfsklrciknvd-eseaharckvee--akghyyatavqqllallp--f
nfenair-hteihyaddgkgttwgal--gvgeng---
>node19
tv-ngrkyhcciseav---h-kpvk---------f-ka------------
----ehntaltlgakic-------m---gvarqgpigdstlfds-lgdmy
gascpyeh--gda---ttkakhgsahs-----alneavliigdspktinh
taafrs--ck----k--gwcil---l-vsaladlticwqqavgler----
-----tiksderqrqatyhri--vlgtttflenndnvcva-kdtsgl-mp
krrilkhv--llgcl----gtsyk-ah-lir---nd----elfhyrdlvv
ergkngpymtfrsa-----------ievasqhgsyeehldpmggsdwswa
lkdgfgenwlyrqsd-ftatgkgvpidldeargntalakakfddtffdf-
-skeasndlsktellsdalsg----tgqsssecvl-r-hkhadvrlsdp-
fnleeqqgivptcgma--------d-----gvddqvfcyeeqdpgp---t
l---lss-----rqlggkrsi----wvt-------------ggifak---
---sytg-yidllheldkveliqkn-----------s----skpcirtcp
ayyfaklrciknvd-eseaharckmee--akghyyatavqqllallp--f
nfenair-htdihyaddgkgttwgal--gvgeng---
>node14
tv-ngrkyhcciseav---h-kpvk---------f-ka------------
----ehntaltlgakic-------m---gvarqgpigdstlfds-lgdmy
gascpyeh--gda---ttkakhgsahs-----alneavliigdspktinq
taafrs--ck----k--gwcil---l-vsaladlticwqqavglnr----
-----tiksderqrqasyhri--vlgtttflenndnvcva-kdasgl-mp
krrilk----llgcl----gtsyk-ah-lir---nd----elfhyrdlvv
ergkngpymtfrsa-----------ievasqhgsyeehldpmggsdwswa
lkdgfgdnwlyrqsd-ltatgkgvpidldeargntalakakfddtifdf-
-skevsnelsktellstalsg----tgqsssecvl-r-hkhadvrlsdp-
fnleeqqgivptcgmg--------d-----gvddqvfcyeeqdp-----t
l---lss-----rqlggkrsi----wvt-------------ggifak---
---sytg-yidllheldkveliqkn-----------s----skpcirtcp
ayyfaklrciknvd-eseaharckmee--akghyyatavqqllalvp--f
nfenair-htdihyaddgkgttwgal--gvgena---
>node11
tv-ngrkyhcciseav---h-kpvk---------f-ka------------
----ehntaltlgakic-------m---gvarqgpigdstlfds-lgdmy
gascpyeh--gda---ttkakhgsahs-----alneavliigdspktinh
taafrs--ck----k--gwcil---l-vsaladlticwqqavgler----
-----tiksderqrqatyhri--vlgtttflenndnvcva-kdtsgl-mp
krrilkhvkgllacl----gtsyk-ah-lir---nd----elfhyrdlvv
ergkngpymtfrsa-----------ievasqhgsyeehldpmggsdwswa
lkdgfgenwlyrqsd-ftatgkgvpidldeargntalakakfddtffdf-
-skeasndlsktellsdalsg----tgqsssecvl-r-hkhadvrlsdp-
fnleeqqgivptcgma--------d-----gvddqvfcyeeqdpgp---t
l---lss-----rqlggkrsi----wvt-------------ggifak---
---sytg-yidllheldkveliqkn-----------s----skpcirtcp
ayyfaklrciknvd-eseaharckmee--akghyyatavqqllallp--f
nfenair-htdihyaddgkgttwgal--gvgeng---
>ENV_HV2D2/24-513
tv-gsrkyhccvseav---h-kpvk---------f-ka------------
----ehdtaltlvakic-------m---dvarqgpigestlfdg-lgdms
gascpyeh--gda---ttkakhgaals-----alnsaviivgenpntinh
aaafra--ck----t--gwcil---l-vsgladlticwqeavgles----
-----titcnekqrqatyqri--algtttfmdnndnqcva-kdtsgk-mp
krrnlkhvdgllacl----lssyr-ah-lir---it----elflyadhvv
ergkngp-ftfrsa-----------ievasqhgsfeehlqpmggtdwswh
hkdgfgenwlyrqse-ftatgkgvppdldeargntalakskmddtffdf-
-skeaskglsktqvlsdalsg----tghssgacvl-k-hnhtdvrlseph
faleeeqgivptcgma--------d-----ggddqvfcyeeadpgpktlt
l--klad-----relggkrsi----rvt-------------ggifek---
---sykg-yidllheldkvelihkn-----------s----skpcirvcp
ayyfamlrciknvk-e---harckree--akghayagsvqpllallp--f
nfqnnyr-ht-ihysedgkstswgal--gvgeng---
>ENV_SIVGB/47-569
kv-dg-------sqavckhhgravkkgdflcdsay-rahlwysgg----g
gt--------------cvtdaqvdlqlvataryesk-vap---geletdt
rgacqlehafglacadtlgsstgdtkn-----lrd-dll-------ptrl
htami---ckkkfki--gwckl---avva-------cwhhpvslps----
----ftlrgd--------hri---k--egl-----------kkf--lyvl
kqlmn-----lvlclykkkggtye-pl-lkr---hn----qlfdf-----
erdqetpta--kds-----------i-kttqpganpdhfspl-gatwpwa
hknafgnhwlyrgenndent----cssled---nl----pkmadpffdf-
-nfqete--skdlvlsdslagparsyegngsrfef-r-aaktgmsisqk-
------qggmpvigkpeavpclltarvhk--ntaqvfcyhvkl-------
----------lrkrlg--krl-rsfhvgvktcfnefveampggefn----
----yssryivlv-klerv------tqklgqldgahefeahkircl----
-----avpaipdidpa---q--cgakcfvkk---yatnvyqlltf-sayf
gyqkdki-etgshfsdkptanpwdsashtesaeteki
>ENV_HV2D1/24-501
tv-ngrkyhccisdav---h-kpvr---------f-ka------------
----ehntaltlganic-------m---gvarqgpigdstlfds-lgdmy
gasckyeh--gqa---ttkakhgsahs-----alneavliigdapktinq
taafrs--ck----k--gwcil---l-asiladlticwqqavgler----
-----tiksderqrqasyhrt--vlgtttflenndnvcra-kdasgl-mp
krrilk----llgcl----gtsyk-ah-lir---nd----elfhyrdlvv
erakngpymtfrsa-----------ievasqhgnytealdpmggsnwswa
lkdgfgdnwlyrhsd-ltptgkgvpieldeargnnalakakfddtvfdf-
-skevsnelsktellstaldg----tg---secvl-r-hkhadvrlsdp-
fnleeqqgvvqtcgmg--------d-----gvddqvfcyeeqdp-----t
l---iss-----rqlggkrsi----wvt-------------ggifak---
---sytg-yidllheldkveliqkn-----------s----skpcirtcp
ayyfaklrciknvd-eseaharckmee--akghyyetvvqqllalvp--f
hfenair-htdihyaed--gttwgal--gvgena---
>ENV_SIVV1/24-538
tiydgkkthcyisetv---h--plvqgdfv------kdhmwyggngikgf
glfl------------c-------fsvtdvaryglrvseklles-lgdit
dgpiafer--gla---svaakvgnshp-----qmnskvl-------aisq
ygamrn--ck----rsqgrcqlqh---is-------cwehaigltpascy
lfll-tvkge--------hwislvr--qpl-----------kny--l-is
krriprfvvglitcl----ggsykdal-lvr---sa----dlfhynimvv
ergkggptmtfrnacntvqapekrelkvytahatn--------gsdwswd
kkaglgehwlyrrsqkfaatskgigialnd---ni----pkmdnkifdy-
-akdgtdelgkthklnsaltg----srqd-----f-rqhlhshinlakp-
inlephhggmpvcnrs--------dkv-kggrdelvfcykgreptp---s
lcv-msgavtlrrqlk--kgqp---hva-------------ggiya----
----ytg-ymshlhdldkm-----------------e----nkpci----
-----siacvpdvhhe---h--cgmmr--akgr---dd-qq---------
----enr-aadphlsaggsggswsal--aqeand---
>node18
tv-ngrkyhcciseav---h-kpvk---------f-ka------------
----ehntaltlgakic-------m---gvarqgpigdstlfds-lgdmy
gascpyeh--gda---ttkakhgsahs-----alneavliigdspktinh
taafrs--ck----k--gwcil---l-vsaladlticwqqavgler----
-----tiksderqrqatyhri--vlgtttflenndnvcva-kdtsgl-mp
krrilkhv--llgcl----gtsyk-ah-lir---nd----elfhyrdlvv
ergkngpymtfrsa-----------ievasqhgsyeehldpmggsdwswa
lkdgfgenwlyrqsd-ftatgkgvpidldeargntalakakfddtffdf-
-skeasndlsktellstalsg----tgqsssecvl-r-hkhadvrlsdp-
fnleeqqgivptcgma--------d-----gvddqvfcyeeqdp-----t
l---lss-----rqlggkrsi----wvt-------------ggifak---
---sytg-yidllheldkveliqkn-----------s----skpcirtcp
ayyfaklrciknvd-eseaharckmee--akghyyatavqqllallp--f
nfenair-htdihyaddgkgttwgal--gvgeng---
>node17
tv-ngrkyhccisear---h-kpvk---------f-ka------------
----ehntaltlgakic-------i---gvarqgpigdstlfds-lgdmy
gascpyeh--gda---ttkakhgsahs-----alkeavliigdspktinh
taafrs--ck----k--gwcil---l-vsaladlvicwqqavgler----
-----tiksderqrqaayhri--vlgtttflesndnvcva-kdtsgl-mp
krrilkhv--llgcl----gtsys-ah-lir---kd----elfhyrdlvv
ergkngpymkfrsa-----------ievasqqgsyeehldpmggsdwswa
lkdgfgenwlyrqsd-ftatgkgvpieldeargntalakasfddtffdf-
-skeasndlsktellstalsg----tgqsssecvl-r-hkhadvrlsdp-
fnleeqqgivptcgma--------d-----gvddqvfcyeeqdp-----a
l---lss-----rqlggkrsi----wvt-------------ggifak---
---sytg-yidllheldkvelvqkn-----------s----skpcirtcp
ayyfaklrciknvd-eseaharckmee--akghyyatavqqllallp--f
nfenair-htdihyaddgkgttwgal--gvgeng---
>node9
tv-nsrkyhccmsetv---h-kpvk---------f-ka-mw---------
---lehntaltlgakic-------m---gvarqgpmgdstlfes-lgdmt
dascayeh--gsa---tikakhgnths-----alnekvliigdspktinh
taafrs--ck----k--gwcil---l-vsgladlticwqqaigler----
-----tikgeerqrqaayhri--vlgtttflenndnhcva-kdtsal-mp
krrilkhvdgliacl----gtnyk-ah-lir---nd----elfhyrdlvv
ergkngpymtfrsa-----------ievasqhgayeehldpmggsdwswa
hkngfgenwlyrqsd-ftatgkgvpidleeakgntalakakmddtffdf-
-skeasnnlsktevlsdalsg----tgqsssecvf-r-hkhadirlsdp-
fnleeqqgivptcgmn--------d-----gvddqvfcyeeqdpgp---t
l---las-----rqlggkrsi----wvt-------------ggifak---
---sytg-yidllheldkv-----------------s----skpcirtcp
tyyfaklrciknvn-e---harckmee--akghyyatsvqqllallp--f
nfqnair-htdihysddgsgaswgal--gvgens---
>ENV_SIVM1/24-528
tv-ngrkyhccmsetv---h-kplk---------f-ka-mw---------
---lehntaltlgakig-------m---gvarqspmgdstlfes-lgdmt
dasctyen--gsa---tikakhgntrs-----alnekvliigdahktmqh
taafrs--ck----k--gwcil---l-vsglaeltlcwlqaigler----
-----sikgeerqrqaayhri--vlqtttflenndnhcva-kdssal-mq
krrvlkhvdgliacl----gtnyk-ah-lir---nd----elfeyrdlvv
ergkngpymtfrsa-----------ievasqhkayqehldpmggsdwswa
hkngfgenwlyrqsd-ftatgkgvpisleeakgstalakpkmddtffdf-
-skeasnnlsktevlsdatsm----tgqtssecvfhr-hkqgdirlsdp-
fnleeqqgivptcgmn--------d-----gvddqvfcyeeqdpgp---t
l---lns-----lqlggkrgi----wvt-------------gglfak---
---sytg-yidllhdlskv-----------------s----sktcirtcp
tyyfakvrcikgvn-e---harckled--akghyyatsvqqllallp--f
nfqnair-htdrhy-ddgsgaswgal--gvgens---
