>ENV_HV2G1/23-502
gskvtlydlgalehadfvmvkfnhrgv-dntve----ptlrc--kelvcl
pekysyvvd--katssghnfaadhelhqdsa------glthaegcns-v-
---ssvarh--d--------cddt--------anwapkhi-inqagtaa-
rpp-vk-swrn-ahnsyihgqktph-lfri--nncasdp--k--------
------------aqtdy---l----ndsa-----------ty---sysv-
-ttppkta---agvidyvar---yagvliggpadqasglgtgkcsrfrkk
fpvqpwccsl-k----diwyvvgp-----------kek---sggqtgfql
c-----a-etghe--hssrrgvk-agy-tdkk---ek--k-------gk-
aa----grsglvkpgkgvhrlcnlepygcts-------qghtwwrhagl-
cnfegr-kqlskgwka--g---------------egdlayss--pvakhg
sqfifasvvs---vygevrv-slq---saqgv--caqaplks--e-lars
alkwskeshlhpaevvkidrmaakl-kd-pvdvfdktthqpk-feepgep
yks------------ystcq-falkntqywe--v--rfkd-drsgnlirq
tnlpicm-tyilkelhpdyngavgtcad----------layplli--fa-
--wltyvmtc----k--
>ENV_HV2D2/24-513
gsnvtiydlgalehaeflmvkfnhrgvvdnv------qklrclikel---
--nfsyvcd--katssghnfaadhdleqdla------glthvegcns-v-
---aslarl--d--------cent--------anwapkhv-vnqagtaa-
rpp-vk-twrc-aqes------tah-lfrv--qgcasdn--k--------
------------aqndy---ltqdpndsaa------ynvdsy---sysv-
-ttppktaqtvggvieyvar---yagvliggpaneapglstgkcgrfrkk
fpiqpwccsl-k----diwyvvgp-----------kek---pggqtpfql
c-----n-ntghe--hssrrgvk-tgy-tdkklkaetvak-------gk-
ka----drsgiv---kgvhrlcildvyvcts-------qghtwwrnagl-
cs-egk-kqlskgwkt--g---------------egdlaymn--pvakhg
sqfifasvik--lvygqvkv-nlq---seqgv--ceqaalka--e-fars
alkwskeshnhpadvtkidragkkl-kd-sva-fdrt------fdqpgep
ytspggeigi-----ystcq-fklkdtrywerfc--rfkd-drsgnldrq
tnlpfcm-tyilkelhpdytgavgtcpd---------cleyplli--fa-
--wlayvmtc----kg-
>node7
ldstklcd-------dfvmfnfqhrgv-dnrvqaemcpslsc--kgl---
--syayvpe--kqtgkghkfasd--lhldsaaveeqyalihaencgnlvy
ksasglvrvtkd--------cnsa--------aswtpkhtltkqggtae-
rptdvk-swnahahns------tpq-iirv--qaclsdeqdk-kghlrht
lytvs--spfvkapsdy---l----gnpgg------yevtay---aytls
atvpqksp---ggvieyvar---eaavliggpseqc-----grcgrqrkk
fgvepwccsl-k----diwyvige-----------kek---ssgrtvfhl
c-----n-ntgqe--has--qvvagay-pdkk---ha--kl-iptptgr-
as----grs-------------ilqvlscts-------tga-fwrhggl-
cn-egrpkqldkgwka--h---------------ef-vtyeneseaakqg
vqfiftaves--lvynetrv-nlk---selgg--cleegvka--e-l---
-l-----dhnhaaiqvkierlakrl-tn-p-------pdhrdgfdqpgep
ydnpggeiae-----fsgvq-falkdvrfwe--cnahfkd-drsgnlvrq
lgip-cmltyiqkelhpdydgavgecad----------leydlii--ig-
--wmayvvlc----kpr
>ENV_SIVM1/24-528
ggevtlydlgtlehadfvmvkfnhrgv-dnkve----sklrc--kel---
--nyayvve--katssghnfaadnklhedsa------glthvegcns-v-
---ggsarh--d--------cddt--------agwapkht-inqggtaa-
rpp-vs-swrd-thns------tpn-lfrv--qgcadde--k--------
------------gqsdy---l----nnsav------yeiety---syti-
-ttppkta---ggvieyvar-akaagvliggpvnqapalgsgkcgkfrkk
gpvqpwccsl-k----diwycvgp-----------kit---sggqtgfqp
c-----n-naghe--qasrrgvk-tgy-tdkk---qt--k-------gk-
aa----grsgli---kgvhrlcifqlyvcts-------tghtwwrhagl-
cn-dgr-kqldsgwka--g---------------eg-leysn--peaktg
iqfvfeslvs--lvygqirv-nlq---seqgv--caqaalka--e-lara
alrwskesknqaaivvkvdrmakkl-ka-pvd-fdkttdqpkgfdqpgep
ysspggevgi-----ystcq-falkderywe--c--qfkn-drsgdliwq
tnlpvcm-tyilkqlhpdydgavgttad----------leyplle--fa-
--wlayvmec----kp-
>ENV_SIVGB/47-569
ldm----c-------pfvmytfnfrgv-dvtle----phfts--vgl---
--sfpyapdipkq-gkkrrfngy--lelega------alvseaacgslvq
----l-arpkkelvnhftygcdtt-----dar---ntghtatkhgssap-
rtt-l--swnehp-da------vsq--------gplgdesgkprakl---
--tvr--ssf----saygkyl----sapgsdvkeadyqinifspvatnl-
-kvpqkca---gavlhfvptv--vatvlvggppanc-----grcdrdrhd
fgvapwccrl-khnhydgwyvage-----------nqkynas--hiqfhv
c-----h-ga-qvgshes----palayfpdek--------la------r-
p----------v---ka-nrlcvfatkkcsp-------kg---lv--gli
c--------------akaqlqdsphclkwgpqpedf-vtyegisdtpkea
-----seharvvmpygsvqt-nmtdaagelgg--sleggvkt--eelrrt
al-----qsahasesgkidrpakrlstt-p-------vhlshmfaqnaal
feaegge--v-----igqcqsfhmkeidfwk--c--hfkdttyyhq----
-glv-----yldkplhseynaavggcgtgkkkftdkg-lkyhilt--fn-
--lh-------------
>node18
gsevtlydlgalehadfvmvkfnhrgv-dntve----pslrc--kelvcl
penysyvve--katssghnfaadhdlhqdsa------glthvegcns-v-
---ssvarh--d--------cddt--------anwapkhi-inqagtaa-
rpp-vk-swrd-ahnsyihgkktph-lfrv--qncasdh--k--------
------------aqtdy---l----ndsaa------yevday---synv-
-ttppkta---agvieyvar---yagvliggpanqasglgtgkcgrfrkk
fpvqpwccsl-k----diwyvvgp-----------kek---sggqtgfql
c-----n-etghe--hssrrgvk-tgy-tdkk---et--k-------gk-
ga----grsglv---kgihrlcildvyvcts-------qghtwwrhagl-
pn---r-kqlskgwka--g---------------egdlaysn--pvakhg
sqfifasvvs---vygevrv-slq---seqgv--caqaplka--e-lars
qlkwskeshlhpaevvkidrmaakl-kd-pvd-fdkttdqpn-fdqpgep
ysspggeigi-----ystcq-falkdtrywe--c--rfkd-drsgnlirq
tnlpicm-tyilkelhpdyngavgtcad----------layplliaafa-
--wlayvmtc----kn-
>ENV_HV2D1/24-501
gsevtlydlgalehaefamlkfnhrgv-dntve----psvrc--velvcl
penysyvve--kaissghnfaadhdlhkdsa------glphvescna-v-
---ssvarh--d--------cdnt--------atwapehi-iiqagtaaa
rpt-vkitwrn-ahnsy------ah-lfrv--qncasdh--k--------
------------aqtdf---m----ndsaa------yevday---sfnv-
-ttppkta---igvieyvar---yggvliggpanqrsglgtgkcg--rkk
fqvqpwccnl-k----diwyrvgphnskpdpismakep---sggqadfql
c-----d-dtgre--hsscsgvk-tgn-tdke---at--k-------gk-
aa----grgglv---kgihrlcilnvyvcts-------qghtwwrhagl-
pn---r-kqlskgwka--g---------------egdlafsn--pvakhg
sqfifasvvs---vygevrv-svq---seqgv--cavaplkamte-lprs
qlkwakeshlhpaevvkidrmaakl-kd-pvd-fdk-tdqpn-fdqpgep
ysspggkigi-----ystcq-falkdtrywe--c--rfkd-drsgnlirq
tnlpicm-tyilkelhpdyngavgtcad----------layqllivafa-
--wlayvmpc----kn-
>node11
gsevtlydlgalehadfvmvkfnhrgv-dntve----pklrc--kelvcl
penysyvve--katssghnfaadhdlhqdsa------glthvegcns-v-
---ssvarh--d--------cddt--------anwapkhi-inqagtaa-
rpp-vk-swrd-ahnsyihgkktph-lfrv--qncasdn--k--------
------------aqtdy---l----ndsaa------yevdty---synv-
-ttppkta---agvieyvar---yagvliggpanqasglgtgkcgrfrkk
fpvqpwccsl-k----diwyvvgp-----------kek---sggqtgfql
c-----n-etghe--hssrrgvk-tgy-tdkk---et--k-------gk-
aa----grsglv---kgvhrlcildvyvcts-------qghtwwrhagl-
cnfegr-kqlskgwka--g---------------egdlaysn--pvakhg
sqfifasvvs---vygevrv-slq---seqgv--caqaplka--e-lars
alkwskeshlhpaevvkidrmaakl-kd-pvd-fdkttdqpn-fdqpgep
ysspggeigi-----ystcq-falkdtrywe--c--rfkd-drsgnlirq
tnlpicm-tyilkelhpdyngavgtcad----------layplli--fa-
--wlayvmtc----kn-
>ENV_SIVV1/24-538
idstnlcd-------dlmlfnhqhrgv-dnavqaemcpslsc--kgl---
--syayvpe--kqtgkghkfasq--lhldsaavieqyaliheedcgsl--
-------rvtkd--------cnsa--------aswtqkhtltkqggtpq-
rptdtk-ewyahahee------tpq-iirvaqhacladevdk-kgqlrhs
lytvsdkspfvkaptdy---l----gnsgg------yettvy---gys-k
aavpqksp---ggvieyvar---eadvliggpseec-----grcgrqrkk
fgvdpwccsl-n----dewygig---------------------rtvfhl
cptwagntntgqe--hss--qtvagay-sdkk---ha--kl-iptptgk-
as----gks-------------mlqvlgcts-------tgt-fwrhssl-
cn-egrpkqldkgwka--h---------------ef-gtvendaenekqg
vqfiftaves--lvynetrv-nlk---selag--cledgvgs--e-l---
-l-----npnhaniqvkietlkkkl-tn-p-------pdhrdgfdqpgep
ydnpggeits-----fsgve-fglkd-rfwe--cdahfka-dragnlvrl
lgip-cmltyiqkelhp---gavgecad----------leyelii--ig-
--wmayvtic----kpr
>node14
gsevtlydlgalehadfvmvkfnhrgv-dntve----pslrc--kelvcl
penysyvve--katssghnfaadhdlhqdsa------glphvegcns-v-
---ssvarh--d--------cddt--------anwapkhi-inqagtaa-
rpp-vkiswrd-ahnsyvhgkktph-lfrv--qncasdh--k--------
------------aqtdy---l----ndsaa------yevday---synv-
-ttppkta---agvieyvar---yggvliggpanqasglgtgkcghfrkk
fpvqpwccsl-k----diwyrvgphnskpdpismakek---sggqtdfql
c-----n-etghe--hssrrgvk-tgy-tdkk---et--k-------gk-
ga----grsglv---kgihrlcildvyvcts-------qghtwwrhagl-
pn---r-kqlskgwka--g---------------egdlaysn--pvakhg
sqfifasvvs---vygevrv-siq---seqgv--cavaplka--e-lars
qlkwskeshlhpaevvkidrmaakl-kd-pvd-fdkttdqpn-fdqpgep
ysspggeigi-----ystcq-falkdtrywe--c--rfkd-drsgnlirq
tnlpicm-tyilkelhpdyngavgtcad----------layqlliaafa-
--wlayvmtc----kn-
>node9
gsevtlydlgalehadfvmvkfnhrgv-dnkve----pklrc--kel---
--nyayvve--katssghnfaadndlhqdsa------glthvegcns-v-
---sgvarh--d--------cddt--------agwapkht-inqggtaa-
rpp-vk-swrd-ahns------tph-lfrv--qgcasde--k--------
------------aqsdy---l----ndsav------yeidty---sytl-
-ttppkta---ggvieyvar---aagvliggpanqasalgtgkcgrfrkk
fpvqpwccsl-k----diwyvvgp-----------kek---sggqtgfql
c-----n-ntghe--qasrrgvk-tgy-tdkk---et--k-------gk-
aa----grsgli---kgvhrlcilqvyvcts-------tghtwwrhagl-
cn-egr-kqldkgwka--g---------------eg-laysn--paakhg
iqfifasvvs--lvygqvrv-nlq---seqgv--caqaalka--e-lars
alkwskeshnhaaivvkidrmakkl-kd-pvd-fdkttdqpngfdqpgep
ysspggeigi-----ystcq-falkdtrywe--c--rfkd-drsgnlirq
tnlpicm-tyilkelhpdydgavgtcad----------leyplli--fa-
--wlayvmtc----kp-
>ENV_SIVG1/22-522
ldttkicd-------dfvmfnfrhrgv-dnrvqgemspslsc--kgl---
--syayvpe--kqtgkghkfasd--lhldraaveeqyalihaen-gnldy
ktasglvrvtkd--------cnsa--------aswtpkhdltkqggtae-
rptdvk-swnahahns------apq-iirv--qaclsdeqdk-kghlrht
lytvs--spfvkapsdy---l----gnpgg------yeasay---aytvs
atvpqksp---ggvieyvar---eaavliggpsekc-----grcgrqrkk
fgvepwccrl-k----diwcvige-----------pek---ssvrtvfhl
c-----n-ntgqe--has--qvvagay-pdsk---ha--pl-iptptgre
ap----gks-------------ivqvlscts-------tgg-fwreggl-
cn-egrpkqldkgwka--y---------------ef-vtyenes-aakqg
vqfiytaves--lvyhetrt-nlk---selgg--cleegeka--e-l---
-l-----dhnhnaiqvkierlakrl-tnnp-------pdhrddfdqpgep
ydaaggeiae-----fsgvq-falknvrfwe--cnahfkn-drsgnlvrq
lgip-cmltyiqkelhanydgapaecad----------leydlii--ig-
--wmayvvmc----kpr
>ENV_HV2NZ/24-502
gsevtlydlgrlehanfvmvkinhrgv-dntve----pslrc--kelvcl
penytyive--kttasghnfaadpdlhqdsa------gvthvegcds-v-
---ssvarh--d--------cndt--------anwapkhf-inqagtaa-
rpp-vk-swrd-ahnsfihggktph-lfrv--qncasdh--k--------
------------aqtdf---l----tdsaa------yeinay---synv-
-ttpikts---agvieyvgr---yagvliggpanqtsglgtgkcgrfrkk
fpvqpwccslvk----diwyvvgp-----------kek---sggqtvfql
c-----n-etgve--hdsrrdvk-tgy-takk---es--m-------gk-
gaaasngrsglm---kgihrlcildvnvcts-------qthtwwrhagl-
pn---r-kqlhkgwka--g---------------egalaysd--pvakhg
sqfvfarvvg---vygdvrvmalr---reqsvifcaqaplkg--e-----
qlkwskekhlhpaevvkidrmadkl-kd-pvd-fdkttdqpn-fdqpgep
ysspggdigvmkskgystcq-falkdtrywe--c--rfkd-drrgelirq
tnlpicm-tyilkelhpsyngavgkcad----------layplliaafa-
--wlsyvmtckaelkn-
>ENV_HV2CA/25-512
gsevtlydlgrlehanfvmvrfnhrgv-dntve----pslrc--kelvcl
pedysyive--kttasghnfaadpdlhqdga------glthvegcgs-v-
---ssvyrh--d--------cdda--------tnwapkhi-inqagtaa-
rpp-vk-swrd-ehnsyihggktph-lhrv--kncaadh--k--------
------------aktdy---l----tdsva------yevnay---synv-
-ttppkta---avvieyvgr---yagvliggpanqasglgtgkcgrfrkk
fpvqpwccsl-k----diwyvvap-----------kek---sggqtgfqh
c-----n-dvahe--hssrrgvk-tgy-takn---ei--k-------gk-
ga----g-sgmm---kglhrlcildvyvctnitnpghyaghtwwrhagl-
pn---r-kqlskgwka--g---------------egdlvysn--pvakhg
sqfifasvvs---vygevrt-slq---svq-----araplkg--e-lars
qlkwskesnl--aevvkidrmaakl-kd-pvd-fdkttdkpn-fdqpgep
ysspggevgi-----ystcq-falkdtrywe--c--rfkd-drsgnlird
tslpicm-tyilkelhpeyngavgtcad----------lpyplliaafah
ffwlayvmtc----kn-
>node19
gsevtlydlgalehadfvmvkfnhrgv-dntve----pklrc--kelvcl
penysyvve--katssghnfaadhdlhqdsa------glthvegcns-v-
---ssvarh--d--------cddt--------anwapkhi-inqagtaa-
rpp-vk-swrd-ahnsyihgkktph-lfrv--qncasdn--k--------
------------aqtdy---l----ndsaa------yevday---synv-
-ttppkta---agvieyvar---yagvliggpanqasglgtgkcgrfrkk
fpvqpwccsl-k----diwyvvgp-----------kek---sggqtgfql
c-----n-etghe--hssrrgvk-tgy-tdkk---et--k-------gk-
ga----grsglv---kgvhrlcildvyvcts-------qghtwwrhagl-
cnfegr-kqlskgwka--g---------------egdlaysn--pvakhg
sqfifasvvs---vygevrv-slq---seqgv--caqaplka--e-lars
alkwskeshlhpaevvkidrmaakl-kd-pvd-fdkttdqpn-fdqpgep
ysspggeigi-----ystcq-falkdtrywe--c--rfkd-drsgnlirq
tnlpicm-tyilkelhpdyngavgtcad----------layplli--fa-
--wlayvmtc----kn-
>node17
gsevtlydlgrlehanfvmvkfnhrgv-dntve----pslrc--kelvcl
penysyive--kttasghnfaadpdlhqdsa------glthvegcns-v-
---ssvarh--d--------cddt--------anwapkhi-inqagtaa-
rpp-vk-swrd-ahnsyihggktph-lfrv--qncasdh--k--------
------------aqtdy---l----ndsaa------yevnay---synv-
-ttppkta---agvieyvgr---yagvliggpanqasglgtgkcgrfrkk
fpvqpwccsl-k----diwyvvgp-----------kek---sggqtgfql
c-----n-etghe--hssrrgvk-tgy-takk---et--k-------gk-
ga----grsglm---kgihrlcildvyvcts-------qghtwwrhagl-
pn---r-kqlskgwka--g---------------egdlaysn--pvakhg
sqfifasvvs---vygevrv-slq---seqsv--caqaplkg--e-lars
qlkwskeshlhpaevvkidrmaakl-kd-pvd-fdkttdqpn-fdqpgep
ysspggeigi-----ystcq-falkdtrywe--c--rfkd-drsgnlirq
tnlpicm-tyilkelhpeyngavgtcad----------layplliaafa-
--wlayvmtc----kn-
>node10
gsevtlydlgalehadfvmvkfnhrgv-dntve----pklrc--kel---
--nysyvve--katssghnfaadhdlhqdsa------glthvegcns-v-
---ssvarh--d--------cddt--------anwapkhi-inqagtaa-
rpp-vk-swrd-ahns------tph-lfrv--qgcasdn--k--------
------------aqsdy---l----ndsaa------yevdty---sysv-
-ttppkta---ggvieyvar---yagvliggpanqasglgtgkcgrfrkk
fpvqpwccsl-k----diwyvvgp-----------kek---sggqtgfql
c-----n-ntghe--hssrrgvk-tgy-tdkk---et--k-------gk-
aa----grsglv---kgvhrlcildvyvcts-------qghtwwrhagl-
cn-egr-kqlskgwka--g---------------egdlaysn--pvakhg
sqfifasvvs--lvygqvrv-nlq---seqgv--caqaalka--e-lars
alkwskeshnhpaevvkidrmakkl-kd-pvd-fdkttdqpn-fdqpgep
ysspggeigi-----ystcq-falkdtrywe--c--rfkd-drsgnlirq
tnlpicm-tyilkelhpdyngavgtcad----------leyplli--fa-
--wlayvmtc----kn-
>ENV_HV2BE/24-510
gsevslydlgglehanfvmvkfnhrgv-dntvd----pslrc--kelvcl
penysyvve--katssghnfapdhdlhqdsa------glphvggcns-v-
---ssvarq--d--------vddtesqkt---anwaqkhi-inqagtpa-
rpp-vkiswrd-ahhsyvhgkkmphklfrv--qncasdh--k--------
------------aqtdy---l----ndnaa------yevday---aynp-
-ttppkta---dgvieyvar---yggvliggpahqa-slgtgmcghfrkk
fpvdpwccsl-k----niwyrvaphnskpdpisvakek---sggqsdfel
c-----n-etghe--hssrrgvk-tgy-tdkk---ea--r-------gk-
ga----grsglv---kgihrlcildvyvcts-------qghvywrhagl-
pn---r-kqlskgwka--g---------------dsdlaysd--pvskhg
sqfifasvvg---vygevrv-siq---seqgv--cavaplks--e-lars
qlkwskeshlhpaevvkvnrlaakl-kd-pve-fdkttdqpn-fdqpgep
ysspggeigi-----ystcq-falkdtrywe--c--rfkd-drsgnvirq
tnlpicm-tyilkelhpdyngavgtcad----------aayqlliaafa-
--wltlvmtc----kn-
>node8
ldsvklcd-------dfvmfnfqhrgv-dnrve----pnlsc--kgl---
--syayvpe--kqtgkghkfasd--lhldsa------alihaescgslvy
ksasglarhtkd--------cdsa--------aswtpkhtltkqggtae-
rpt-vk-swnahahns------tph-ifrv--qaclsdesdk-kghlrht
lytvs--spfvkspsdy---l----nnpgg------yevnay---aytlq
atvpqksp---ggvieyvar---eaavliggpaeqc-----grcgrqrkk
fgvepwccsl-k----diwyvige-----------kek---sggqtvfhl
c-----n-ntgqe--has--avtagay-pdkk---da--kl-iptptgr-
as----grsgli---kashrlcilqvyscts-------tga-fwrhagl-
cn-egrpkqldkgwka--h---------------ef-ityeniseaakeg
vqfiftaves--lvynqtrv-nlk---selgg--cleagvks--e-lara
al-----dhnhasiqvkierlakrl-tn-p-------tdqrdgfeqpgep
ynhpggeiav-----fsgcq-falkdvrfwe--c--hfkd-drsgnlvkq
lgip-cmltyiekelhpdydgavgecad----------leydlii--fa-
--wmayvisc----kpf
