>node9
qsygihvdd-----ia-at-------lalggm----kltfff----yfnh
yfngphfsnlpaamnel--ligdgqql-agar-d---------fhgacrg
gf---fntavegyirvcv--crcvgk---a-------------slfkqfl
lpllgdvpvgkllsnka------raikat--------lll----------
--------gke---patkprcrglg-fkpfqdlgf--tlirfhksl---m
yaks------pekkleerkfprafq-ipqginqagcalwtitghs-----
-----egewq-rllvcllnraer--ffhflhavkhdmgtlpnsmg---c-
--drasp---lpif-----grttp-----ttvy-i--p-----lspyk--
---lgav-qgtyqdsvvsnsirfas-----p---tneg-----ppst---
-k---a-----t----vgthstigykaa------levysnipgkgtghl-
vggggceayeypgkkc------qahk-twqtcskvtgfsiscsrpsehpg
qsldshniggti-cnedfgidfsiqlsynqgqepfs--r-vrkkdprppf
ggmltkfpdyvhlvre-l-----------ila--phca--ngakyfveaa
fhnatinsgkdcfik-trkdggkrvtaagpgkag-np--skqvlkglkky
aerad-------dl-nd--s
>ENV_HV2NZ/24-502
qtyginvdn-----ia-gt-------lal--m----kltiff----yfnh
yfngprfsnlpatlnel--ligdgqql-agar-d---------fhgacrs
gy---fdtavqqyirvcv--crcrgk---a-------------slfkefl
lpllsdvpvgkvlsnka------rs---t--------lllledadgpvrd
t-------gre---patkpkckvls-ykqfqdlgf--tlirfhkpl---m
yak--------ekkleerrlprafq-i--ginqdgcalwtitghs-----
-----egewq-rllvcllnraer--ffhflhavkhdmgtlpngmg---c-
--grasp---lpkf-----gkdlp-----ttvy-i--p-----lspyk--
---lgah-qgtyqdsvvsnsvrfaa-----p---tnqg-----pvst---
-k---a-----t----vgvhstmgykae------levynnipgrgtghl-
vggggcesfeyagkkc------qahk-twqtcsvvtgftiscakpsdqpg
qsldshniggti-cnedfgiefsirlayd---epfs--q-vrskqprpaf
ggmltkfpdyvhlvre-l-----------ila--phca--ngakyfipaa
fhnat-----dcfik-trkegsrritaegpgkag-np--skevlkglrty
aekad-------dl-nd--s
>ENV_HV2D1/24-501
qsygehvdn-----ia-at-------lvlggk----kltfff----yfnh
yfngpqfsnlpaamnel--ligdgqdl-agar-d---------fhgacrg
gy---fdtaveqyirvcv--crcvgk---a-------------alfkqfl
lpllgdvpvgkllsnka------raikat--------lllledadgpvhd
t-------g-----patkpscrglg-fkpfqdlgf--tlirfhksi---l
yaks------pqkkleerrfprafq-i--ginqagcglwtitghs-----
-----egewq-rf-vcllnraer--ffhfihavkhdmgalpnglg---c-
--grasp---lpeftctftgkttp-----ttvy-i--s-----lspyk--
---lgavkegtyqdpvvsnsirfas-----p---tnqg-----ppst---
-k---a-----s----vgthstmgykaa------levynnipgkgtghl-
lggggcesfeyagkkc------qahk-awhtcgkvegftiscsrpseq--
as----niggti-csedfgidfsirlsyn---epfs--r-vkskqprppf
ggiltkfpdyvhlvrn-l-----------ila--phca--egakyfieaa
fqdatihsdkdcfrk-trkdggrrvtaegpgkag-ap--skevlpglkty
aerad-------dl-nd--s
>ENV_SIVG1/22-522
qgygiyv-da----iv-aalyaattnlvvggmgdlprftfff----yfnl
fycgpqfvelpaamnel--imgdlvqltla-r-ae---gt---fhgpcrg
gwtpvflaavegylrvvf--crcvgk---a-i-eghhdfq---klfk--l
laflgdvpvaillnrka------kamkht--------l------------
-----------------------ks-fkpfqdigf--slir---------
--khglifsgpnraldsrtfprsfq-iqe--gick-atwa--eqs-----
-----egewh-rlivcllsra-k--ifhflqtvknamgylpqsrgwfacr
----tgscfnlplf-----grttitpqdgtaayvi--t-----l---k--
---lgtv-hgly-diiktnavwfdqseavgpvlltqeg-----vsaa---
-kcvnt-----n----vskhgtigimpa------ldvyggipgkgtdht-
lnggvcepyehpgkkc------qphk-thqtcakvtgfsisctkreeqag
qsvdkh--aetihclgdf--dfsgtlsyndgkepgdecrsaklkdprppf
ggklaklpnyvhk------------------a--phcnnnk--ky-----
fhner-----tcfik-trkdggakvnestntnagsyl--skkvlkkssky
----e-------av-enpka
>ENV_HV2CA/25-512
qsygihvdn-----ia-at-------lalggm----kltfff----yfnh
yfngphfsklpaarnelnqligdgqqi-agar-d---------ihgacrg
gy---fdtavdqyirvcvltcrcrgk---a-------------slfke--
lpllsdvpvgslltskg------ssikaiescpghlglllledadgpvrd
t-------gke---satkprcrgig-fkpfqnlgf--tlirfhkal---i
yaks------pekkleerrfpralq-i--ginqagcalwtitahs-----
-----egewq-rllvcllnnaer--ffhflhavkhdvgtspngmg---c-
--grasp---lpef-----nkttp-----ttvy-i--pldagrmsayk--
----gav-qg--qdsvvsnsirfas-----p---anqg-----sask---
-k---a-----t----vsthstmgykaa------levyndipgrgtgale
vngggcesfeysgkkc------qahk-twqacsvvtgftiscsraseqpg
vsld-hniggti-cneefgidfsirfsyn---epfs--q-vrskqprppf
ggmltkfpdyvhlvre-lakppytkvq--ila--phca--ngakyfieap
fhnat--sdkdcfir-tkkdggrsvtaegpgnag-np--dkevlkglkty
aerad-------dl-nd--s
>node7
qgygiyv-da----iv-aalygattnlvlggmgdeprftfff----yfnh
yycgpqfpelpaamnel--ilgdlvqltla-r-ge---gt---fhgpcrg
gw---flnavegyirvvf--crcvgk---a-i-eghadfq---tlfk--l
laflgdvpvaillnrka------damkht--------l------------
-----------------------kn-fkpfqdigf--slir---------
--kh------pnrglddrtfprsfq-iqe--gick-alwa--eqs-----
-----egewh-rlivcllsra-k--ifhflqtvknamgylpqsmg---cr
----tgpcfnlplf-----grttv-----taayvi--t-----l---k--
---lgtv-hgly-dvvktnavwfdq-----p---tqeg-----vsaa---
-ncvna-----n----vskhgtigimpa------levysgipgkgtdht-
lnggvcepyehpgkkc------qphk-thqtcakvtgfsisctkraeqag
qsvdsh--getihclgdf--dfsgtlsynqgkepgd--rsakmkdprppf
ggkltkfpnyvhk------------------a--phcnnhk--ky-----
fhnen-----tcfik-trkdggakvnegtntnagayl--skkvlkktsky
sekte-------al-nnpks
>node18
qsygihvdn-----ia-at-------lalggm----kltfff----yfnh
yfngphfsnlpaamnel--ligdgqql-agar-d---------fhgacrg
gy---fdtaveqyirvcv--crcvgk---a-------------slfkqfl
lpllgdvpvgkllsnka------raikat--------lllledadgpvrd
t-------gke---patkprcrglg-fkpfqdlgf--tlirfhksl---m
yaks------pekkleerrfprafq-i--ginqagcalwtitghs-----
-----egewq-rllvcllnraer--ffhflhavkhdmgtlpngmg---c-
--grasp---lpef-----gkttp-----ttvy-i--p-----lspyk--
---lgav-qgtyqdsvvsnsirfas-----p---tnqg-----ppst---
-k---a-----t----vgthstmgykaa------levynnipgrgtghl-
vggggcesfeypgkkc------qahk-twqtcskvtgftiscsrpseqpg
qsldshniggti-cnedfgidfsirlsyn---epfs--r-vrskqprppf
ggmltkfpdyvhlvre-l-----------ila--phca--ngakyfieaa
fhnatihsdkdcfik-trkdggrrvtaegpgkag-np--skevlkglkty
aerad-------dl-nd--s
>node19
qsygihvdn-----ia-at-------lalggm----kltfff----yfnh
yfngphfsnlpaamnel--ligdgqql-agar-d---------fhgacrg
gy---fdtaveqyirvcv--crcvgk---a-------------slfkqfl
lpllgdvpvgkllsnka------raikat--------lllledadgpvrd
t-------gke---patkprcrglg-fkpfqdlgf--tlirfhksl---m
yaks------pekkleerrfprafq-i--ginqagcalwtitghs-----
-----egewq-rllvcllnraer--ffhflhavkhdmgtlpngmg---c-
--grasp---lpef-----gkttp-----ttvy-i--p-----lspyk--
---lgav-qgtyqdsvvsnsirfas-----p---tnqg-----ppst---
-k---a-----t----vgthstmgykaa------levynnipgrgtghl-
vggggcesfeypgkkc------qahk-twqtcskvtgftiscsrpseqpg
qsldshniggti-cnedfgidfsirlsyn---epfs--r-vrskqprppf
ggmltkfpdyvhlvre-l-----------ila--phca--ngakyfieaa
fhnatihsdkdcfik-trkdggrrvtaegpgkag-np--skevlkglkty
aerad-------dl-nd--s
>ENV_SIVM1/24-528
qsygvhvdd-----ia-at-------lalggm----kltfff----yfeh
yfngphfsnlpaamnel--ligdgqsl-agar-d---------fhgacrg
gf---fntavegyirvcv--crclgk---s-------------slfkqfl
lpllsdvpvgkils----------aikat--------lvv----------
--------gkdfefpatkprcrglg-fkpyqdlgf--tlirfhktl---m
yaks------aekkleerkfprafq-epqkinqagcalwtitghs-----
-----egewq-rllvclkara-----fhwlhavkhdmgqlpnsmg---c-
--drass---lpif-----grttp-----ttvf-ikpp-----lapyk--
---lgav-qgtyqddvvsketrfas-----p---tneg-----ppst---
-k---a-----t----vgthqaigykaa------levysnipgkgtghl-
vggagceayefpgkkc------qahn-twqtclkvtgfsisccrpsehpg
qsldahniggti-cnenfgidysiqfsynqgqepfs--r-vrkkdprppf
ggmltkfpdyvylvre-l-----------ila--phca--ngakyfve-a
fhnatlnpgkdcfik-trkdggkrvtaagpgkag-np--gkqvlkglkky
gerad-------dl-nd--p
>ENV_HV2G1/23-502
qsygihvdn-----ia-at-------lalggm----kltfff----yfnh
yfngphfsnlpaamnel--ligdgqql-ggar-d---------fhgac--
-y---fdtaveqyirvcv--crcvgk---a-------------slfkqfl
lpllgnvpvgkllsnka------raikat--------lllledadgpvrd
t-------gke---paskprcrglg-fkpfqdlgf--tlirfhksl---m
yaks------pekkleerrfprafq-ipqginqagcalwtitghp-----
-----egewq-rllvcllnraer--ffhflhavkhdmgtlpngmg---c-
--grasp---lpef-----gkttp-----ttvy-i--p-----lspyk--
---lgav-q-tyqdsvvsssirfas-----p---tnqg-----ppst---
-k---a-----t----vgtkssmgykaa------levynnvpgrgtghl-
vggggsesfeypgkkc------qahy-twqtcskvtgftiscsrpseqpg
qsldshniagti-cnedfgidfsirlsyn---epfs--r-vpskqprppf
ggmltkfpdyvhlvre-l-----------ila--phca--ngakyfieaa
fhnatihsdkecfik-trkdggrrvtkegpgkag-np--skevlkqlkty
gerad-------dldnd--s
>ENV_HV2D2/24-513
qsygihvde-----ia-gt-------lalggl----klpfff----yfnh
yfngphfsnlpaamnel--ligdgqql-agar-d------vlefhgacrg
ga---fdtavegyirvcv--crcvgk---a-------------slfkqyl
lpllgdvsvgkllskka------raikat--------lll----------
-ghlvdlmgke---patkprcrplg-frhfqdlg---tlirf--sllmtm
yakn------pakkleqrkfprafq-lpqainragctlwmitdhs-tvpy
aegcgegewq-rllvcllnraer--ffkylhkvkhdmgtlshsmg---c-
--gragp---l--f-----nkttp-----ttvy-i--p-----ltpyk--
---lgav-qstyqdsvvnnsvrfas-----p---anqg-----ppst---
-k---a-----t----igthgtmgykat------levynnipgrgaaha-
fggggcdafeyagkkc------eank-twqtcskvtgftiscsrpseqpg
qnveshniggti-csddfgidfsiqlsln---eqfs--r-vrkkqprspf
ggmlt------hlqre-m-----------ila--paca--ngakyfidaa
fh-atihsdkdcfik-trkdggkavkaegpgkag-nl--skevfkglksy
adrad-------dl-----s
>ENV_SIVGB/47-569
qmyadyv-ggvrpwvafes-------vvmdgvdeernftffyrledyfch
yyigeffadvpg-mhel--lmlnfvgsnlvqt-agwsslt---fegpsrg
gw---f--sfagimklvf----cvgsedqpevhggegdyraepklft--l
mdwlgeiptaillerka------aniken--------t------------
-----------------------yn-ysspgnyafpgtlsr---------
--kl------snsglgnrrfprafpa----------slwt-aklck----
-------qwqltllvclkgsp-r--ffhflqaqqhams-lpmsmg---ca
qrpktastfkmppf-----grasv-----ptvyir--r-----v---a--
---lgnk-qgly-saqsnaciwfeh-----v---tkeg-----aaat---
-kcgkaegaves----vvdheivgirpa------leifaeicgsgtgsm-
-ngggcasfehvgtkyqggcrkqphk----t---itglttacskk--qte
htlegh--tdeircqsef--dfrknlnfnrgqdngn--rcaskkelrqpy
ggklarlgdivvkfrnnp---------spimegtsrnk--v--ka-----
yhhee-----dcfatatqkddt---sqa-g----afl--crrilkeleqy
aqkadlqlvtrttv-nqpka
>node11
qsygihvdn-----ia-at-------lalggm----kltfff----yfnh
yfngphfsnlpaamnel--ligdgqql-agar-d---------fhgacrg
gy---fdtaveqyirvcv--crcvgk---a-------------slfkqfl
lpllgdvpvgkllsnka------raikat--------lllledadgpvrd
t-------gke---patkprcrglg-fkpfqdlgf--tlirfhksl---m
yaks------pekkleerrfprafq-ipqginqagcalwtitghs-----
-----egewq-rllvcllnraer--ffhflhavkhdmgtlpngmg---c-
--grasp---lpef-----gkttp-----ttvy-i--p-----lspyk--
---lgav-qgtyqdsvvsnsirfas-----p---tnqg-----ppst---
-k---a-----t----vgthstmgykaa------levynnipgrgtghl-
vggggcesfeypgkkc------qahk-twqtcskvtgftiscsrpseqpg
qsldshniggti-cnedfgidfsirlsyn---epfs--r-vrskqprppf
ggmltkfpdyvhlvre-l-----------ila--phca--ngakyfieaa
fhnatihsdkdcfik-trkdggrrvtaegpgkag-np--skevlkglkty
aerad-------dl-nd--s
>ENV_HV2BE/24-510
qsygehvdn-----ia-at-------islggm----kltfff----yfnp
hfngpqysnlpaamnal--liadgqql-agaran---------fhgtcrg
gy---fdsavgqyirvcv--crcvgk---a-------------alfkqfl
lpflgdvpvgkllsnkslaklekkaiqvt--------lllledadgpvrd
t-------gke---patkprcrglggfnpfrplgf--tlirfhksl---l
yaks------pekklerrrfprafq-i--gihqagcalwtitghs-----
-----egewq-rllvchlnraer--ffhflhaviddmgtlpngmg---c-
--grasp---lpef-----gkstp-----ttvy-a--p-----qspykfs
gvslgav-qgtyqdpivsnsirias-----p---tnqg-----ppst---
-k---a-----t----vsthetmgykaa------mevhnnipgrgnghl-
vggggcetfeypgkkc------qahkkawqtcskisgftiscsrpseqpg
asldnrniagti-cnedfgidfnirlsyn---epfs--r-vkskqpr---
--ilt----yvqlvre-l-----------ila--ppcs--ngakyfieda
fhnttihskkdcfrk-trkdggrrvtadgpgkag-np--skealkglkty
aerad-------dl-nd--s
>node14
qsygehvdn-----ia-at-------lalggm----kltfff----yfnh
yfngpqfsnlpaamnel--ligdgqql-agar-d---------fhgacrg
gy---fdtaveqyirvcv--crcvgk---a-------------alfkqfl
lpllgdvpvgkllsnka------raikat--------lllledadgpvrd
t-------gke---patkprcrglg-fkpfqdlgf--tlirfhksl---l
yaks------pekkleerrfprafq-i--ginqagcalwtitghs-----
-----egewq-rllvcllnraer--ffhflhavkhdmgtlpngmg---c-
--grasp---lpef-----gkttp-----ttvy-i--p-----lspyk--
---lgav-qgtyqdpvvsnsirfas-----p---tnqg-----ppst---
-k---a-----t----vgthstmgykaa------levynnipgrgtghl-
vggggcesfeypgkkc------qahk-awqtcskvsgftiscsrpseqpg
asldsrniggti-cnedfgidfsirlsyn---epfs--r-vkskqprppf
ggiltkfpdyvhlvre-l-----------ila--phca--ngakyfieaa
fhnatihsdkdcfrk-trkdggrrvtaegpgkag-np--skevlkglkty
aerad-------dl-nd--s
>node8
qgygiyv-ga----ia-at-------lvlggmgdeprftfff----yfnh
yyigphfpelpaamnel--lmgdlvqltlapr-ge---gt---fhgpcrg
gw---flnavegyirvvf--crcvgk---aqi-eghadfq---tlfk--l
lpflgdvpvavllnrka------daikht--------l------------
-----------------------kn-fkpfqdigf--tlir---------
--ka------pergledrkfprafq-iqe--gmck-alwt-tkqs-----
-----egewq-rllvcllsra-k--ffhflqavkhamgylpqsmg---cr
eihrtgpcfnlplf-----grttv-----ttvyvi--p-----l---k--
---lgtv-qgly-dvvktnavwfdq-----p---tqeg-----aaaa---
-kcvna-----n----vgnhdtigikpa------levysnipgkgtght-
ldgggcepyehpgkkc------qphk-thqtcakitgfsisctkrseqag
qsldsh--geaihcledf--dfsialsynqgkepgs--rsarkkdprppf
ggkltkfpdyvhklreap-----------ila--phcn--k--ky-----
fhnen-----dcfik-trkdggtkvsaatptsagayl--skrvlkklsky
sekae-------al-nnpks
>node10
qsygihvdd-----ia-at-------lalggm----kltfff----yfnh
yfngphfsnlpaamnel--ligdgqql-agar-d---------fhgacrg
gf---fdtavegyirvcv--crcvgk---a-------------slfkqfl
lpllgdvpvgkllsnka------raikat--------lll----------
--------gke---patkprcrglg-fkpfqdlgf--tlirfhksl---m
yaks------pekkleerkfprafq-ipqginqagcalwtitghs-----
-----egewq-rllvcllnraer--ffhflhavkhdmgtlpnsmg---c-
--grasp---lpef-----gkttp-----ttvy-i--p-----lspyk--
---lgav-qgtyqdsvvsnsirfas-----p---tnqg-----ppst---
-k---a-----t----vgthstmgykaa------levynnipgrgtghl-
vggggcesfeypgkkc------qahk-twqtcskvtgftiscsrpseqpg
qsldshniggti-cnedfgidfsiqlsyn---epfs--r-vrkkqprppf
ggmltkfpdyvhlvre-l-----------ila--phca--ngakyfieaa
fhnatihsdkdcfik-trkdggkrvtaegpgkag-np--skevlkglkty
aerad-------dl-nd--s
>node17
qsygihvdn-----ia-at-------lalggm----kltfff----yfnh
yfngphfsnlpaamnel--ligdgqql-agar-d---------fhgacrg
gy---fdtaveqyirvcv--crcrgk---a-------------slfkefl
lpllsdvpvgkllsnka------rsikat--------lllledadgpvrd
t-------gke---patkprcrglg-fkpfqdlgf--tlirfhkpl---m
yaks------pekkleerrfprafq-i--ginqagcalwtitghs-----
-----egewq-rllvcllnraer--ffhflhavkhdmgtlpngmg---c-
--grasp---lpef-----gkttp-----ttvy-i--p-----lspyk--
---lgav-qgtyqdsvvsnsirfas-----p---tnqg-----ppst---
-k---a-----t----vgthstmgykaa------levynnipgrgtghl-
vggggcesfeysgkkc------qahk-twqtcsvvtgftiscsrpseqpg
qsldshniggti-cnedfgidfsirlsyn---epfs--q-vrskqprppf
ggmltkfpdyvhlvre-l-----------ila--phca--ngakyfieaa
fhnatihsdkdcfik-trkdggrrvtaegpgkag-np--skevlkglkty
aerad-------dl-nd--s
>ENV_SIVV1/24-538
plygiyv------------lygdatllvlagm--eprftfff----ynnh
yycgqqfpelpiplnet--ilgelvqltlg-r-ge---gt---fngpcrg
sw---fmnavegyirvif--crcvgk---a-i-eghtdfq---tlfk--l
lafladvpvailltr------------ht--------m------------
-----------------------kn-fkpfqeiaf--plvr---------
--kh------pnrgldnrtlhesfe-iqh--eick-alwa--eqs-----
-----emewh-rlivclvsra-khtifhylqtvknsmgylpqsla---cr
----ngpcfnlplf-----tratv-----taayvi--v-----l---k--
---lgtv-rgly-dvvkasaiwfds-----p---tqegtgstmvqaahai
gnc-na-----nfeaivskhgtigimpaslkavvlevynaipgkgtdnt-
lkggvcepyehpgkkc------qphk-thqsvaavtrynisctkraeqag
qtvdsh--geaihchgnf--dfsgtlsfnqgkdpgd--rsakmktprppf
gskltkfagylhk------------------a--pqcnn-k---y-----
fhnen-----tcfik-trkdggarvnqgtntnagaylvv-kkilkkssry
tekte-------pl-ihpkt
