>ENV_HV2NZ/24-502
lriknqvahsikhrlgtgace--cls--------hlakhqlnctpfst--
----natsplqpipf--diah-vnagdnlhs--keepltnpsl-------
-dnllrv-necadtlwnasvgskepvcqkssh----diyfqv-epern--
----g--svqges-cses-sknk-----dlpc-----yfhgkaqpevvlh
qyyaar---lvthadespgdfpfgs---epa------------ppkvvlt
piakssmgvgqqflmlqdsvllpyh-vphvlykt-----vasitqkstap
dg------tcktkvdakgape--vtdekkhtffdhfilgthanyipnelp
l-------------------alpqqldllgpk-giaslailfssvs---g
rnpkhf------------vhskpghggsypgtgfpsnkaekcsyaevsvg
sfaygcvkl--ksghehp--nagqvvtvmg--------------------
---ksfeedlger-e------kaqrltsmk--y---eqthvtgnvesk--
----igsksspllq---gl-i------kfr---lkvspfr--------rg
gadcdpn------fdyvapli-------------ks---klidat---gf
afagf--priggydpvcep-----------aaaqtfihlch-ga-mlanv
qqsiyligtvqfgngtkwegg-naf-k
>ENV_SIVV1/24-538
vri------------gkkaiq--gl---------avtkhhqvcapfgv--
----nass---sraa--aiah-vvsiqnlrs--thsphnspelqnlsvtl
gqnlirv-nncld---------kspvcqkvkhgfdrdkylkv-eaqrg--
----a--siagea--tks-tkkk---nqnlsgldvanfydgqasvevifh
qyfens---il-cpavtpgnlplgg---dnagsydff---ganslrvvdt
gvhkrpmgpaeqn-vqeetvllnfe-ipnvlckt-----tatvteect--
---------vmasmd-kgeqg--rtehktegffdhfilgth-----gelp
lg---ikftivaaleggmy-----------------lgtityiaasqlgy
kaekhf---eaiprstdcvyydrdhggnyagngfnvstvqec--n-----
-----hvrvfpnrgqntc--vem-vvafv--------fl-nkagt-ksdt
gffkafqvdlsqrrq------kshriirmn--f---pqaeilgsaysk--
----vhsn--pllv---gllfitqfletykvtllrvshf-asgatrc-kg
eancppe------fdgmqalk-------------ks---klisqa---qf
afagl--prvtgynp---p-----------glaqt-ihlch-naakf--v
qqsivlagsi-------wdeg-ai---
>ENV_HV2D1/24-501
vri------------gssacg--cls--------hlakhqlnctpfst--
----natsplqpipf--diah-vnaien-------epftnpsl-------
-dnllrv-kecadtlw------kkpvcqkvshsfdgdiylqv-epern--
----g--svqges-cses-senk-----dlrc-----yfhgkaqpevvlp
qyyaarptf-vayadetpgefpfgs---epa------------ppkvvlt
piakasmgvaaqntllqdsvllpyh-vphvlykt-----vasitqksttp
dg------tcmtkaaakgapk--vtdekkhkffahfilgthanyipnefp
lgtrgieft-----------alpqqld---pk-giaslaitfssvs---s
rkakhf------------vhsapghggsypgtgfpsnksekc--devsvg
sfaygcvkl--ksgherp--sqgqvvtvmvdaqlfelfl-nk-----ten
gffknfnedlger-p------kaqrltsmn--y---eqah-tgsvesk--
----igsksspllr---gl-f------kyr---lkitpf---------rg
gadcapw------fdyvapli-------------ks---rlidatldkgf
afags--pkiggynpvcep-----------glaqtfihlch-ga-ml--v
qqsiyligsvqfvqgtkwegg-taf-k
>ENV_SIVM1/24-528
vri------------gssace--vls--------hiakhrlnctpfst--
----napsplqsrpl--dishkvnaienlrs--keepftnpsl-------
-dnllrv-nqcletiw------kkpvcqkvkhgfdsktylqv-eaern--
----g--svqges-cses-sknk-----qlpc-----yfsgkaqpevvlh
qyyaap---lv-------gifpfgs---epa------------ppkvvlt
piaksplgvaeenqmledsvllpfq-vphilykt-----vasitqksttp
dg------tcmtkvaskghpe--vaeqkkhaffkhfivgthvkyipndlp
lsargiefk-----------alpgqld---pk-giasltitfssvp---s
r---hf------------vhskpghggsypgtgfpsnkadkc--dev---
---ygcvrl--ksgherplsnqgqvvavvggsqlfelfl-nk-----ten
gffksfevdlger-q------kasrltrmk--y---pqahvasnverk--
----igsksspllq---gl-l------vyr---lkvtpf---------ag
gadcapd------fdemaali-------------kslsfklidap---ay
afagf--priggytpvcep-----------glaqtfihlch-ga-kl--i
eqniylvgsvqfg------gg-aaf-k
>node14
vri------------gssace--cls--------hlakhqlnctpfst--
----natsplqpipf--diah-vnaienlrs--keepftnpsl-------
-dnllrv-necadtlw------kkpvcqkvshsfdsdiylqv-epern--
----g--svqges-cses-senk-----dlrc-----yfhgkaqpevvlh
qyyaar---lvthadetpgefpfgs---epa------------ppkvvlt
piakssmgvaaqnlmlqdsvllpyh-vphvlykt-----vasitqksttp
dg------tcmtkvaakgape--vtdekkhaffkhfilgthanyipnelp
lgtrgieft-----------alpqqld---pk-giaslaitfssvs---s
rkakhf------------vhskpghggsypgtgfpsnkaekc--devsvg
sfaygcvkl--ksgherp--nqgqvvtvmvdaqlfelfl-nk-----ten
gffksfnedlger-e------kaqrltsmk--y---eqahvtgnvesk--
----igsksspllq---gl-f------kyr---lkvtpf---------rg
gadcapn------fdyvapli-------------ks---rlidat---gf
afagf--priggynpvcep-----------glaqtfihlch-ga-ml--v
qqsiyligsvqfgqgtkwegg-naf-k
>node9
vri------------gssace--vls--------hlakhrlnctpfst--
----napsplqprpl--diah-vnaienlrs--keepftnpsl-------
-dnllrv-nqcadtlw------kkpvcqkvkhsfdsdiylqv-eaern--
----g--svqges-cses-sknk-----dlpc-----yfhgkaqpevvlh
qyyaar---lvthanetpgefpfgs---epa------------ppkvvlt
piakspmgvaeenlmledsvllpfq-vphvlykt-----vasitqksttp
dg------tcmtkvaskgape--vadekkhaffkhfilgthvkyipnelp
lgtrgieft-----------alpqqld---pk-giasltitfssvs---s
rkakhf------------vhskpghggsypgtgfpsnkaekc--devsvg
sigygcvrl--ksgherp--nqgqvvavvgdaqlfelfl-nk-----ten
gffksfevdlger-e------kasrltrmk--y---pqahvagnvesk--
----igsksspllq---gl-f------tyr---lkvtpf---------rg
gadcapn------fdevapli-------------ks---klidat---af
afagf--priggynpvcep-----------glaqtfihlch-ga-kl--v
qqsiylvgsvqfgngtkwdgg-aaf-k
>ENV_SIVG1/22-522
vri------------gkktid--gl---------avtkhrqicapfgv--
----nass---prsv--diah-lvrienlha--keephtspel-------
-enlvra-nncld---------kspvcqklkhsfdqdiylqv-eaqkd--
----a--svages-ctks-tkkk---nedlsgldvanfydsqanvavvlq
qyfesk---ivtcpsetpgelpfgg---esagsynffgtyaanspkvvlt
giekrpmgpseqklvqeetvllefe-vpnvlykt-----vatvsqect--
---------vmtkih-ggaqg--rtehknegffdhfilgth-----gelp
lgaasi---ivtageggly-----------------lltityisvs---s
kkekhf---gaiprntdcvhserdyggnyagsgfntstvqkc--nevnvg
aigysvvrl--nrgqntp--vef-vvalv--------fi-nkaat-ksdt
gffksfdvelsqrrn------esnrvitmk--y---pqaqiigavvsktg
etgavhsn--pllvatfsl-f--qfletya---lrvsqf-adp-------
-adcapd------fsnlqpli-------------ks---klisqg---qf
afagl--prvtgynp---p-----------glkqt-ihlch-aa-kf--v
qqsiylvgsiefgdggkwdgg-aif-r
>ENV_SIVGB/47-569
irv------------akrtgkkgga-kcwgstkhevakhkeccnppgv--
----ngpsgleprlvdl---l-vhaisklrancledshtcpgl-------
-eglmrv-eqcfe---------kstvckkvshaftralalqlgeqteigh
evegs----sagvesssaitksehgc-edlsvm-mggffagectleivwh
lyfnnk---ivacpcdtqtelpfgcgvaeks------------akrvvlq
pld-kakttseqdllqnedvllhfe-vpnihcek-----iakvt------
---------ckikvn-----gnyrtearengl-dpfll----------is
lgprgtnigvlav----laphhplrad---nkegivlllhpfgsia---g
kkkkhf---glvprrmecvphklshggkyta------nvqic--qa--da
iig--cvql--kksqgtp--saf-vmnqi--------faqnkvgksrfgn
gvfksievee----ntgrhnckaaelikmkgpygtqpdaqlvnpvysk--
----vsqh----------l-y------pyk---lpsstf--------gsg
psdcape------vdelaqlihlsssdswptltrrp---kavdqp---qf
qflsvghnrid----ickp-----------glett-v---hgga-kf--s
spseylagsvpygndgnwsng-snflq
>node17
vri------------gtsace--cls--------hlakhqlnctpfst--
----natsplqpipf--diah-vnaienlrs--keepftnpsl-------
-dnllrv-necadtlw------kepvcqkvshsfdsdiylqv-epern--
----g--svqges-cses-sknk-----dlpc-----yfhgkaqpevvlh
qyyaar---lvthadetpgefpfgs---epa------------ppkvvlt
piakssmgvaqqnlmlqdsvllpyh-vphvlykt-----vasitqksttp
dg------tcktkvdakgape--vtdekkhaffdhfilgthanyipnelp
lgtrgieft-----------alpqqld---pk-giaslaitfssvs---s
rnakhf------------vhskpghggsypgtgfpsnkaekc--devsvg
sfaygcvkl--ksgherp--nqgqvvtvmg--------------------
---ksfeedlger-e------kaqrltsmk--y---eqahvagnvesk--
----igsksspllq---gl-i------kyr---lkvtpf---------rg
gadcapn------fdyvapli-------------ks---klidat---gf
afagf--priggydpvcep-----------alaqtfihlch-ga-ml--v
qqsiyligsvqfgngtkwegg-naf-k
>ENV_HV2CA/25-512
vri------------gtsace--clc--------hlakhqlnctpfst--
----natsplqpipy--diah-vnaienqrd--qedpfanpsl-------
-dnllrv-necadtlw------keptcqkvshsfdsdiwlqv-epekn--
----g--svqges--sls-sknk-----dlpc-----yfhgkaqpevvlh
qyyaar---lvthsdespgefpfgs---epa------------ppkvvlt
piakssmgvaqqnlmlqdsvllpyh-vphvlykt-----vpsitqksttp
dggyalyktcktkvdakgape--vtdekkhaffnhfvlgthanyipnelp
lgtrgiaft-----------alpqqld---pk-diasla-tfssvs---s
rnakhf------------vhsrpgh-------gfpsnkaekc--dkvsvg
sfaygcvkl--ksgherp--nqgqvvtvmg--------------------
---ksfeedlger-e------kaqrltsvk--t---ekahdaghvesk--
----igsksgplkq---gl-i------kyr---lkvtpf---------rg
gadcapn------fdyvapli-------------ks---klidat---gf
aftgf--priggydpvcep-----------alaqtfihlch-ga-ml--i
qqskyligsiargngtkrhggmday-k
>node7
vri------------gkkaiq--gl---------avtkhrqvcapfgv--
----nass---prpv--diah-vvsienlrs--keephtspel-------
-enlirv-nncld---------kspvcqkvkhsfdrdiylqv-eaqrd--
----a--siages-ctks-tkkk---nedlsgldvanfydgqanvevvlh
qyfesk---ivtcpsetpgelpfgg---esagsynffgtfgansprvvlt
giekrpmgpseqnlvqeetvllnfe-vpnvlykt-----vatvtqect--
---------vmtkih-kgaqg--rtehktegffdhfilgth-----gelp
lgtagiaftivaageggly-----------------lltityisvs---s
kkekhf---gaiprstdcvhserdhggnytgngfntstvqkc--nevnvg
aigysvvrl--nrgqntp--vef-vvalv--------fi-nkagt-ksdt
gffksfevdlsqrrn------ksnriirmk--y---pqaqiigsvysk--
----vhsn--pllv---gl-f--qfletyk---lrvsqf-adgatrc-kg
eaecapd------fddlqpli-------------ks---klisqa---qf
afagl--prvtgynp---p-----------glaqt-ihlch-na-kf--v
qqsiylvgsiefgdggkwdgg-aif-r
>node8
vri------------gkraiq--gl---------avtkhrqtctpfgv--
----napsklqprpv--eiah-vvsienlrs--keephtspel-------
-enlirv-nncld---------kspvcqkvkhsfdrdiylqv-eaqrd--
----a--siages-ctks-tknk---nedlsgldvanffhgqasvevvlh
qyfask---ivtcpsetpgelpfgs---eaa------------sprvvlt
piekrpmgpseqnlvqedtvllhfq-vphvlykt-----vatvtqeck--
---------cmtkve-kgaqg--rtedkkegffdhfilgth-----gelp
lgtrgiaftivaagegglypnlprrne---pkkgitlltitytsvs---s
kkekhf---gliprsvdcvhskpdhggnytgngfntstvqkc--nevnvg
sigyncvrl--krgqdtp--aef-vvalv--------fi-nkagt-ksdt
gffksfevdlserrn------ksnrlirmk--y---pqaqiigsvysk--
----vssn--pllq---gl-f------tyk---lrvsqf---------rg
eadcapd------ldelqpli-------------ks---klidqa---qf
afagl--prvggynpvcdp-----------glsqt-ihlch-ga-kl--v
qqsiylvgsvqfgnggkwdgg-aef-r
>node11
vri------------gssace--cls--------hlakhqlnctpfst--
----natsplqpipf--diah-vnaienlrs--keepftnpsl-------
-dnllrv-necadtlw------kkpvcqkvshsfdsdiylqv-epern--
----g--svqges-cses-sknk-----dlpc-----yfhgkaqpevvlh
eyyaar---lvthadetpgefpfgs---epa------------ppkvvlt
piakssmgvaqqnlmledsvllpyh-vphvlykt-----vasitqksttp
dg------tcmtkvaakgape--vtdekkhaffkhfilgthanyipnelp
lgtrgieft-----------alpqqld---pk-giasltitfssvs---s
rkakhf------------vhskpghggsypgtgfpsnkaekc--devsvg
sfaygcvkl--ksgherp--nqgqvvavmgdaqlfelfl-nk-----ten
gffksfeedlger-e------kaqrltsmk--y---eqahvagnvesk--
----igsksspllq---gl-f------kyr---lkvtpf---------rg
gadcapn------fdyvapli-------------ks---klidat---gf
afagf--priggynpvcep-----------glaqtfihlch-ga-ml--v
qqsiylvgsvqfgngtkwegg-naf-k
>ENV_HV2BE/24-510
vmi------------gnsace--cls--------hlakhqlnctpftt--
----natfplqpipf--diah-mnaienlrs--keepftnlsl-------
-dnllrv-gecadtlr------kkqvcqkvshsfnsdiylev-qpern--
----pklsvqges-cses-setk-----dlrc-----yfhgkaqpevvlh
qyyaar---lvshadqtpmefpfga---eps------------spkvvlt
piakssmgvaaqnlmlqdsvllpyh-vp--lykt-----vasitqkstsp
dg------tcmtkaaakgspe--ptddkkhaffkhfilgthpnyipnell
vgtrgieft-----------tlphqld---pk-giaslaitfdsvs---s
rkakhfiqc---------vhskaghggsypatsfpsnkaekc--devsvg
sfaygcvkl--ksgherp--nqgqvvtvmvdaqlfelil-nk-----ten
gffksfnedlger-e------kaqrltsmk--y---ekahvtgnvesk--
----igskssallq---gl-f------kyr---lkvtsf---------rg
gadcapnlvsggkfdyvapli-------------ks---rlidat---gf
afagf--priggynpvcep-----------glaqtfvhlch-ga-ml--v
qqsiyllgsvqfgqgtkweeg-naf-k
>node18
vri------------gssace--cls--------hlakhqlnctpfst--
----natsplqpipf--diah-vnaienlrs--keepftnpsl-------
-dnllrv-necadtlw------kkpvcqkvshsfdsdiylqv-epern--
----g--svqges-cses-sknk-----dlpc-----yfhgkaqpevvlh
qyyaar---lvthadetpgefpfgs---epa------------ppkvvlt
piakssmgvaqqnlmlqdsvllpyh-vphvlykt-----vasitqksttp
dg------tcmtkvaakgape--vtdekkhaffkhfilgthanyipnelp
lgtrgieft-----------alpqqld---pk-giaslaitfssvs---s
rkakhf------------vhskpghggsypgtgfpsnkaekc--devsvg
sfaygcvkl--ksgherp--nqgqvvtvmgdaqlfelfl-nk-----ten
gffksfeedlger-e------kaqrltsmk--y---eqahvagnvesk--
----igsksspllq---gl-f------kyr---lkvtpf---------rg
gadcapn------fdyvapli-------------ks---klidat---gf
afagf--priggynpvcep-----------glaqtfihlch-ga-ml--v
qqsiyligsvqfgngtkwegg-naf-k
>node10
vri------------gssace--cls--------hlakhqlnctpfst--
----napsplqpipf--diah-vnaienlrs--keepftnpsl-------
-dnllrv-nqcadtlw------kkpvcqkvshsfdsdiylqv-epern--
----g--svqges-cses-sknk-----dlpc-----yfhgkaqpevvlh
qyyaar---lvthadetpgefpfgs---epa------------ppkvvlt
piakspmgvaqenlmledsvllpyh-vphvlykt-----vasitqksttp
dg------tcmtkvaakgape--vtdekkhaffkhfilgthanyipnelp
lgtrgieft-----------alpqqld---pk-giasltitfssvs---s
rkakhf------------vhskpghggsypgtgfpsnkaekc--devsvg
sigygcvkl--ksgherp--nqgqvvavmgdaqlfelfl-nk-----ten
gffksfeedlger-e------kaqrltrmk--y---eqahvagnvesk--
----igsksspllq---gl-f------kyr---lkvtpf---------rg
gadcapn------fdevapli-------------ks---klidat---af
afagf--priggynpvcep-----------glaqtfihlch-ga-kl--v
qqsiylvgsvqfgngtkwegg-aaf-k
>node19
vri------------gssace--cls--------hlakhqlnctpfst--
----natsplqpipf--diah-vnaienlrs--keepftnpsl-------
-dnllrv-necadtlw------kkpvcqkvshsfdsdiylqv-epern--
----g--svqges-cses-sknk-----dlpc-----yfhgkaqpevvlh
qyyaar---lvthadetpgefpfgs---epa------------ppkvvlt
piakssmgvaqqnlmlqdsvllpyh-vphvlykt-----vasitqksttp
dg------tcmtkvaakgape--vtdekkhaffkhfilgthanyipnelp
lgtrgieft-----------alpqqld---pk-giasltitfssvs---s
rkakhf------------vhskpghggsypgtgfpsnkaekc--devsvg
sfaygcvkl--ksgherp--nqgqvvavmgdaqlfelfl-nk-----ten
gffksfeedlger-e------kaqrltsmk--y---eqahvagnvesk--
----igsksspllq---gl-f------kyr---lkvtpf---------rg
gadcapn------fdyvapli-------------ks---klidat---gf
afagf--priggynpvcep-----------glaqtfihlch-ga-ml--v
qqsiyligsvqfgngtkwegg-naf-k
>ENV_HV2D2/24-513
vrk------------gssahe--cls--------hlakyqlnctpfstry
cckg-apsslqpief--diah-vnaiegehs--keqpfknlsl-------
-dlllrvpnqcadtiw------kkpvcqkvshsfdadi-lqv-epern--
----g--tvqges-cser-sknk-----dlpc-----yfhgkaqpevvlh
eyyasr---lvthadntpgefpygs---epa------------ppkgvlt
pigeatmgvaqeglmledmvllpyh-vprviyktgpvggvasitvkstsp
dg------tcmtkvaakgape--vtnekkhaffkhfvlgthlnyiprelp
lgtrnieft-----------alpqqld---pk-aiaslt-----lt---s
rkakhf------------vqskgghggpypgagiasnkaekc--devsvg
slgygcvkl--ksgherp--nqgqvvvvmgdaqlfalfl-nk-----t-d
gffksfqedlper-e------naqrltrmk--y---eqahlagntesr--
----agkrsspllq---g---------ryr---lkvtpf---------rg
vkdcapn------fdevkpli-------------kg---klieat---af
afagf--phiggynpacep-----------dlaqthih--h-ga-kl--l
qqsiylvqsvqfgngtkwqgg-aay-k
>ENV_HV2G1/23-502
vrv------------gstace--cls--------hlakhqlnstpfst--
----navsplqpipf--eiph-vnaienlrs--kedpftnpsl-------
-dnllrv-necadtlw------eksvcqkvchsfdsdiylqv-asern--
----g--svqges-cses-sknk-----dlpc-----yfhggaqpevilh
eyyaar---llthadetpgefpygs---eps------------pprvvls
piakssmgvtqqnlmledsvllpyhkvphvvykt-----vaaitqksttp
dg------ecmtkvaak-ape--vtdeknhaffkqfilgthanyipnela
lgtrgneft-----------vlpqqle---pk-giasltytfssvs---s
rkakhf------------shskpghggaypgtgfpsnksekc--devsvg
sfaygcckl--ksghkrp--nqgqvvavmgdaqlfelfl-nk-----tes
nffksfeedlger-i------kaqrltamk--y---eqahvagnvesk--
----igsksspllq---gl-f------kyr---lkvtpf---------rg
gadcapn------fdyvsplr-------------ks---klidat---gf
afagf--priggygpvcepgqiscavclmsglaqtfihlch-ga-ml--v
qqsiylvgsvkfgtgtkwegg-naf-k
