>ENV_HV2NZ/24-502
vyvgsltnh--tstffl----ahdafgwfaphalsdaw-kqig----kkw
draptepkcysavqqqmlq----------------ackflgaprigsnek
galgnfeh-----ddadaisdcagqlstsfqstttawvtghpkgnatfqg
kcfd---ekdl-p--rlikl-dnkkkltnhe--ngqmtg----st-----
---ilprfr----rrnegat----------h----hcygspkanvcravv
el-lvvlkv--gft----dlfd-----lsl----kvhstrfikgvsrraa
litds----kahlhnagnaaailtenlvvgaad---y--lhkcsvfafci
irvlef------mphdtag-se-----gateke----cgaekqamwrvgm
gt-----syqlp----hfattavkderck-----rvhsq---qqiicrfe
pp-----kkskvsg----fagke------------qtnllrtkapkgtv-
---------ne------------------lqhh---tawdvpepkrf---
-----d-------fr--kmvdwc--aqegss------fkmsyp------a
ngeavkncaynde--------akg---------nprsktrdlfdagkv-a
tkh-eepnas-vagkktlsykdtkpgavhqy----stcmhk---eymp--
s--sfsk---rpcgrqafs--lrkre-qegr
>node9
vyvgtlanh--tatffl----dddsfgwfqppalsdaw-kqkg----kew
drsptdckcysatqqqmlq----------------ackflgapragseek
galanyeh-----ddaeaisdeagqlstsfesktaiwvgghpkgnatfqa
kcfd-tkekdl-p--rlikl-ddk-kltnhe--ngqltg----st-----
---ilprfr----rrnegtseqggset--th----hcygkpkdnvcravv
el-lvvlkv--gfv----dlfd-----lsl----kvhssrfikgagrraa
lites----rahlgdagnaaailtedlvvgsad---y--lhkcvvfafci
irvlef------mphdtag-sd-----gttdke----caaekqalrrvgm
gt-----fyqlp----nfattavkdercnpqdcgrvhtq---qailcrfe
ap-----kks-gsg----fagkd------------ktn-----------e
dv------cke------------------lqhh---tawdvpeprqf---
-----d-------fr--krvdwc--ahegsa------fkmvfp------a
rgeavkscaygde--------arg---------nprakardlfdakkvna
skh-keaeas-algkktnaykdtkaaavhqy----atcvhk---eymq--
s--sfskekarpcghqafs--lrkre-qegr
>ENV_HV2G1/23-502
myvgslanh--tst-fl----dhasfgwfqppalsdaw-rqkg----kew
draptdskcysavqqqmlq----------------ackflgaprigssek
galgeyeh-----ddadaisdakgqlstsfqstttiwvgghpkgnatwqg
kcfd-akekdl-p--rvikl-dnk-kqtnhe--ngqltg----st-----
---------------negtteqggskg--th----hcygspkddvcravv
el-lvvlkv--gfv----dlfd-----lhl----kvhsgrfikgvarraa
liaes----kahladagnagailtedlvvgsad---y--llkcsvyafci
vrvlef------kphetag-sd-----gateke----caaekqalwrvgm
gt-----fyqlp----nfattavtdercnpqdcgrvhsq---qqmlckfp
ap-----kkskvsg----fagke------------ktnllvtkppngtve
dv------cke------------------lqhh---tawdvpepkdf---
-----d-------fv--kkvdwc--ahegsa------fkmvfp------a
rgeavkscaygde--------arg---------narakardlfdakkvna
skh-eeaeas-vagkktlsykdtkpaavhqy----atcihk---eymp--
n--sfskmkarpcgrqafs--lrkre-qdg-
>node19
vyvgslanh--tstffl----dhdsfgwfqppalsdaw-kqkg----kew
draptdpkcysavqqqmlq----------------ackflgaprigsnek
galgnyeh-----ddadaisdaagqlstsfqstttiwvtghpkgnatfqg
kcfd-akekdl-p--rlikl-dnk-kltnhe--ngqltg----st-----
---ilprfr----rrnegttehggskt--th----hcygspkdnvcravv
el-lvvlkv--gfv----dlfd-----lsl----kvhstrfikgvsrraa
lites----kahlgdagnaaailtedlvvgaad---y--lhkcsvfafci
irvlef------mphdtag-sd-----gateke----caaekqalwrvgm
gt-----fyqlp----nfattavkdercnpqdcgrvhsq---qqilcrfe
ap-----kkskvsg----fagke------------ktnllmtkppngtv-
---------ke------------------lqhh---tawdvpepkdf---
-----d-------fr--kkvdwc--ahegsa------fkmvfp------a
rgeavkscaygde--------arg---------nprakardlfdakkvna
skh-eeaeas-vagkktlsykdtkpaavhqy----atcihk---eymp--
s--sfskmkarpcgrqafs--lrkre-qdgr
>node10
vyvgtlanh--tatffl----dhdsfgwfqppalsdaw-kqkg----kew
draptdpkcysavqqqmlq----------------ackflgaprigsnek
galgnyeh-----ddadaisdaagqlstsfesktaiwvgghpkgnatfqg
kcfd-tkekdl-p--rlikl-dnk-kltnhe--ngqltg----st-----
---ilprfr----rrnegttehggset--th----hcygkpkdnvcravv
el-lvvlkv--gfv----dlfd-----lsl----kvhstrfikgvsrraa
lites----kahlgdagnaaailtedlvvgsad---y--lhkcsvfafci
irvlef------mphdtag-sd-----gttdke----caaekqalwrvgm
gt-----fyqlp----nfattavkdercnpqdcgrvhtq---qqilcrfe
ap-----kkskgsg----fagke------------ktn-----------e
dv------cke------------------lqhh---tawdvpepkqf---
-----d-------fr--krvdwc--ahegsa------fkmvfp------a
rgeavkscaygde--------arg---------nprakardlfdakkvna
skh-keaeas-vlgkktlsykdtkpaavhqy----atcihk---eymq--
s--sfskekarpcgrqafs--lrkre-qdgr
>ENV_HV2D2/24-513
vyvgtlan---va---l----dhnsfgwfqapalsdaw-kqkg----kew
draptdpmcysa-----qq----------------ackflgaprigsnek
galgdyeh-----eaadntsdaagqlktsfdsktsiwigghpkdnatfqg
ksfd-lkekdlnp--rlfkl-dgk-klnnhe--ngqltg----st-----
---ilprfr----vrnegsteyggsdt--nl----hcygkpkdnvcravv
el-vvvlkv--sfv----dlfn-----lsl----gvhttkfirgvtrkaa
lites----kah---agn-----tedlvvgsgd---y--lhkrgsfsfci
irvlef------mphdtpg-sd-----gttdke----caaek--lwrvgm
st-----fyplp----nfettdvkdercgpqdvgrdhth---qqilcrfe
ap-----kkskgsg----fagke-------------tn-----------e
dv------cka------------------lqhh---tawdvpetkef---
-----d-------fr--krvdwc--ahedsa------fkmafp------a
rgeavkscsygke--------arg---------npraksrdlfdakkvna
skh-kgaeas-vlgkktvsyk-tkaasihqy----atciqk---eygq--
s--aysk---rpcgrqafs--lrkre-qggr
>node8
vfvgtlanh--tqtlfl----ddetlgwsqpnalsdaw-kq------kew
nraptdckcysatqerslt----------------sckflgaqhtgstek
gvvanyeh-----dhsealseqagelstnfgskdaiwiggdpssnacfaa
kcld-dnekvq-p--klqklt-dk-qhtnhe--nggltg----ka-----
---tlprfp----krnegtsqiagset--th----rcygtpkntecrsvv
dlvlav--vsgsfv----dnfs-----sslnarg-vhksrfikgagrras
litec----rehlcdvgnaa-------vvggan---y--mhkcvffayci
irvvhf------lnhdtag-sekvglkgltdkd----csaekqhlsrggm
gt-----yyklp----nfiaiavkddrcnakdcgrvhtq---qdilcrfe
ap-----kka-gds----fvqkghfyie-svdnalktt-----------g
kv------cde--mvlkyckkr-vstsnnlqqh---tgwdvpeyrgf---
-----d-------fkekkhvewcpqahegsa------fklvfp------g
raeavkschygde--------akg---------tpradarqlfesrkvnt
skhekeadas-algkktnsyrdtkaagvhkw----atcvhqkdaeylq--
s--sfskdkarpcgeqafg--lrnre-ee--
>node14
vyvgslanh--tstffl----dhdgfgwfqppalsdaw-kqkg----kew
draptdpkcyssvqqqmlq----------------ackflgaprigsnek
galgnyeh-----ddadaisdaagqlstsfqstttiwvtghpkgnatfqg
kcfd-akekdl-p--rlikl-dnk-kltshe--ngqltg----st-----
---ilprfr----rrnegttehngskt--th----hcygspkdnvcra--
---lvvlkv--gfv----dlfd-----lsl----kvhstrfvkgvsrraa
lites----kahlgdaanaaailtedlvvgaad---y--lhkcsvfafci
irvlef------mphdtagksd-----gateke----caaekqalwrvgl
gt-----fyslp----nfattavkdercnpqdcgrvhsq---qqilcrfe
ap-----kkskvsg----fvgke------------ktnllmtkapngtv-
---------ne------------------lqhh---tawdtsepkdf---
-----d-------fr--kkvdwc--ahegss------fkmvfp------a
rgeavkscaygde--------arg---------nprakardlfdakkvna
skh-eeaeas-vagkktlsykdtkpsavhqy----adcihk---eymp--
s--sfskmkgrpcgrqafs--lrkre-qdgr
>ENV_HV2D1/24-501
vyvgalanh--tstffl----dhdgfgwfqppalsdaw-kqkglvrskew
draptdpkcyssvqhqmlq----------------ackflgaprigsnek
galgayeh-----ddanaisdaagqlttgfqstssiwvtgnpkgnatfqs
kcfd-akekel-p--rlikl-dnk-kltsre--ngqltg----st-----
---ilprfr----rrnegttehsgskt--ah----hcygspkdnvcra--
---lvvlkv--gfv----dlfd-----lsl----kvwstrfvkg-srraa
lites----kgelgdaanaaailtedlvvgaad---y--lhkcsvfafci
iqvlef------mphdtagksd-----gateke----vaaekqalwrvgl
ga-----fyslp----nfattavkdercypqdcgrvqsqpvpqqilcqfe
ap-----kkskvsg----fvgkn------------ktnlpmtkapngtv-
---------ad------------------lqhh---tpwdtsepkdf---
-----d-------fr--krvdwc--ahegcs------fkmvfp------a
rgeavkscayg------------g---------nprakardlfdakkvna
skh-eeaeas-vagkktlsykdtkpsavhqy----adcihk---aymp--
s--sfskmkgrpcgrqafp--lrkke-qdgr
>ENV_SIVG1/22-522
vfvatllsh--tqtlfl----eneslgwshpntlsdaw-kq------kew
nraptdckcyaqtqersls----------------sckflgaqgtgsnek
svvanyehrgqlndnsealseqagelstrfgskdgiwiggdpssnacfka
kcmd-dnekvg-pkqklqklt-dk-hhakhe--hgglig----ka-----
---slprfp----kqnegtaeeadpetmpth----rcygtpkhsecrsvt
dlvvav--vagsfv----dnfg-----eslsarg-phnpkfikgtgsrns
iilec--------cdvgnaa-------vvggan---y--thkciffafci
irpvhf------lnhdtgg-aekvglkglkdkd----caaekqhlsrggm
gt-----yyklp----nfiaiavk--rckakdcgrvhiq---qdrlcrfe
ap-----tka-gds----fvqkghfyid-svsnalkst-----------g
ka------cna--mvlkyckkr-vstsnalqqh---ngwdipeyrgf---
-----d-------fkqkkhvewcaqahpgsa------fklvfp------g
kaetvnschyade--------pkg---------tpradsrqlfesrkrnt
skhqkeaaqs-algkgtnsyrdskaagvhkw----ctcaqrkdaeylq--
t--sfskdkakpcaeqafa--lrkre-ee--
>ENV_HV2BE/24-510
vyvgslanh--tstffl----dhdgfgwfqppalsdaw-kkkg----kew
qraptdpkcyssvqqqmlq----------------ackflgaprigsnek
galgdyeh-----ddgdaisdaagqlstsfqstttiwvtghpkgnatfqg
kcfd-akekdl-p--kllkl-dnk-kltshe--tgqltg----st-----
---ilprfr----rrndgttehngskt--tn----hcfgspkdtvcra--
---lvvlkv--gfv----dlfd-----isl----nvhrtrfvkgvtrraa
litds----kahigdaanaaavlteel---aad---y--lhkcsvfafci
irvlef------mphdtagkpd-----gateke----catekqalwrvgl
gt-----fyslp----nfattavhdd----qdcgrvhsq---qqilcrfa
ap-----kksrvsg----fvgke------------ktsflmtkapigtv-
---------ne------------------lqhh---tcwdtsepkdf---
-----d-------fr--kkvdwc--ahdgsp------fkmvfpvntmhla
sgdevkscaygde--------arg---------nprakardlfdskkvna
skp-seaeat-vagkqtlaykdtkpsavhqy----adcihk---ecmp--
sidsftkkkgrpcgqqafs--lrkre-qdgr
>ENV_SIVV1/24-538
vivatlash--tlklflaakmgieslgwshpdalndawskq------tew
graptdckcyastqertlg----------------kckflgaqgtgstek
svvanyah-----dhsealseqagelstpfgskdgvwiggeasrnacfsa
tcmdrenekvq-pkd----at-dk-nhtnhe--nggltg----kt-----
---tlprfplgcikknegtsnetgpeikpth----rcygtvknsecr-vi
elvtav--vagsfvqlksdgft-----sslnarg-ihncrfikgtgrkaa
iivec----kehscdvgnaa-------vvggan---y--mhkciffcfcl
irpehf------lnhdtag-aekvglkglknkd----caaqkqhlsrgge
gt-----yyklpakvr-fiaiavkqdrckakdcgrvhtq---edilcrfa
ap-----kkn-gds----fvekghyyie-signelksk-----------s
na------cdavtmvlkfckkr-vhtfhnlqph---hqwevpgykgf---
-----e-------fkvkkhvdwcaqihpgsg------fklvfp------a
radtvnschygde--------pka---------tpradsrslfesrkadt
skhekeaaes-algkesnsyrdckda-vhkw----ctcvhrkdaeqlq--
t--afsknkakpcgeqqfa--lrkre-ae--
>node18
vyvgslanh--tstffl----dhdsfgwfqppalsdaw-kqkg----kew
draptdpkcysavqqqmlq----------------ackflgaprigsnek
galgnyeh-----ddadaisdaagqlstsfqstttiwvtghpkgnatfqg
kcfd-akekdl-p--rlikl-dnk-kltnhe--ngqltg----at-----
---ilprfr----rrnegttehggskt--th----hcygspkdnvcravv
el-lvvlkv--gfv----dlfd-----lsl----kvhstrfikgvsrraa
lites----kahlgdagnaaailtedlvvgaad---y--lhkcsvfafci
irvlef------mphdtag-sd-----gateke----caaekqalwrvgm
gt-----fyqlp----nfattavkdercnpqdcgrvhsq---qqilcrfe
ap-----kkskvsg----fagke------------ktnllmtkapngtv-
---------ne------------------lqhh---tawdvpepkdf---
-----d-------fr--kkvdwc--ahegss------fkmvfp------a
rgeavkscaygde--------arg---------nprakardlfdakkvna
skh-eeaeas-vagkktlsykdtkpsavhqy----atcihk---eymp--
s--sfskmkarpcgrqafs--lrkre-qdgr
>ENV_SIVGB/47-569
vlvgvlpeh--kqtifl----etddlgw--------------------ew
aqav--cecygatqrrsltdrhenpqpasgqlspvrskflggtqvgniek
svlanyhg-----hep--------------gsldgcwfggdpaanglf-h
kc-d-endhiq-q--km-kgf-dk-qhpheqrvnngl-g----karhdig
hmgaipsyp----krnestaqlggpne--thlyerlclatsrktmcspvi
slva-------afi----dtfg-----psltgkn-vlksrf---------
-gsdcqqkskpglcdlgsqt-------lvgginkfkyanmhkcayynycl
vkyvhfgtidcifatgtag-tekegpdsfvtasaeticcaekpqlvrggm
gtdaepnyv-------hfvai------------gyvhtr---qdilckfd
cpktetrktp-genylykyvlrglfy-dhpvattlken-----------g
kvysvarkckt--islkkinksrvstckilqahgttqgwgvqeykgfqgq
kedalslnisdaksvpskq------shqpasaceqqhfelvyp------g
kyeavkschfgsetcgkstsrspgfveqsqekt--------llqratlnt
gkhekeadasaglskrvns--pvkatgphkwslspapapnqkrpehpe--
g--fftkakprpcgdesfgnn------ee--
>node7
vfvatlash--tqtlfl----edeslgwshpnalsdaw-kq------kew
nraptdckcyaatqersls----------------sckflgaqgtgstek
svvanyeh-----dhsealseqagelstsfgskdgiwiggdpssnacfta
kcmd-dnekvq-pkekvqklt-dk-hhtnhe--ngglig----ka-----
---tlprfp----krnegtaqeagpetmpth----rcygtpknsecrsvv
dlvvav--vagsfv----dnfs-----sslnarg-vhnsrfikgtgrras
livec----kehgcdvgnaa-------vvggan---y--mhkciffafci
irpvhf------lnhdtag-aekvglkglkdkd----caaekqhlsrggm
gt-----yyklp----nfiaiavkedrckakdcgrvhtq---qdilcrfe
ap-----kks-gds----fvqkghfyie-svsnalkst-----------g
ka------cda--mvlkyckkr-vstsnnlqqh---ngwdvpeyrgf---
-----d-------fkqkkhvewcaqahpgsa------fklvfp------g
raetvnschygde--------pkg---------tpradsrqlfesrkvnt
skhekeaaes-algkgtnsyrdskaagvhkw----ctcvhrkdaeylq--
t--sfskdkakpcgeqafa--lrkre-ee--
>ENV_SIVM1/24-528
vyigtlanqgqaatffl----dddsfgwfqppalseaw-rqkg----kaw
dksptdckcysatqqqmlq----------------mckflgapragsaek
galanyeh-----dsaetasdkagqlstsfepktaiwvgghpkgnatfqa
kcfd-tkekel-p--rlfkl-dek-kltnht--ngkltg----st-----
---ilprfr----rrnegtseqggset--th----hcygkpkdnvcrevv
ql-lvvlmv--gfv----dffdldgstlsl----kvhssrflkgagrraa
lites----rahlgdagnaaailredlvvgsad---f--lhscvvfafci
frvlef------kpndt-g-sd-----nttdke----ctaekqalrrvgm
gt-----fyqlp----nfattavtdercqpqncgrvhtq---qailcrfe
ap-----tks-gsg----fagkd------------kte-----------e
dv------ckd------------------lqhh---tawevpeprqf---
-----e-------fr--krvdnc--ahegsa------fkmvfp-------
-geavkscahgde--------ars---------npraksrdlfdarkvna
skh-keveaa-algkktnaykdtkaaavhqy----atcvhk---eykq--
s--sfskekarpcdhqafa--lrkrepqegr
>ENV_HV2CA/25-512
vyvgsladh--tstffl----dhdefgwfappalseaw-kqkg----kkw
draptepkcysaiqqqmle----------------ackflgaprigsneq
galgnyeh-----ddteai-ksagqlstsfqsttyawvtg----natfqg
kcfd---ekdl-p--rlikl-dnk-kltnhe--ngqltgtnvkst-----
---ilprsr----rknegtt----------h----hcygspkdnvcravv
el-lvvlkv--gfv----dlfd-----lpl----kvqstrfikgvsrraa
lltes----ksqlgdsgpasailtenlvvpaad---y--lhkcsvfafci
irvldf------mphdtag-sd-----gateke----caaekqalwrvgm
gt-----fyqlp----nfattavkderckpqdcgrvhsq---qeiicrfe
ap-----tkskvsg----fagke------------tpnllmtkkpngtv-
---------ne------------------lqqh---tawdvpepkdf---
-----d-------fr--knvdwc--aregsn------fkmvfp------a
rgeavkgcaygde--------akg---------nprakardlfdakkvna
skh-eeaeas-vagkkslsykdakpsaihqy----atcihk---eympkv
s--sfskmkarpcgkqafs--lrkkd-hegr
>node11
vyvgslanh--tstffl----dhdsfgwfqppalsdaw-kqkg----kew
draptdpkcysavqqqmlq----------------ackflgaprigsnek
galgnyeh-----ddadaisdaagqlstsfqstttiwvgghpkgnatfqg
kcfd-akekdl-p--rlikl-dnk-kltnhe--ngqltg----st-----
---ilprfr----rrnegttehggskt--th----hcygspkdnvcravv
el-lvvlkv--gfv----dlfd-----lsl----kvhstrfikgvsrraa
lites----kahlgdagnaaailtedlvvgsad---y--lhkcsvfafci
irvlef------mphdtag-sd-----gateke----caaekqalwrvgm
gt-----fyqlp----nfattavkdercnpqdcgrvhsq---qqilcrfe
ap-----kkskvsg----fagke------------ktnllmtkppngtve
dv------cke------------------lqhh---tawdvpepkdf---
-----d-------fr--kkvdwc--ahegsa------fkmvfp------a
rgeavkscaygde--------arg---------nprakardlfdakkvna
skh-eeaeas-vagkktlsykdtkpaavhqy----atcihk---eymp--
s--sfskmkarpcgrqafs--lrkre-qdgr
>node17
vyvgslanh--tstffl----dhdsfgwfappalsdaw-kqkg----kkw
draptdpkcysavqqqmlq----------------ackflgaprigsnek
galgnyeh-----ddadaisdaagqlstsfqstttawvtghpkgnatfqg
kcfd---ekdl-p--rlikl-dnk-kltnhe--ngqltg----at-----
---ilprfr----rrnegtt----------h----hcygspkdnvcravv
el-lvvlkv--gfv----dlfd-----lsl----kvhstrfikgvsrraa
lites----kahlgdagnaaailtenlvvgaad---y--lhkcsvfafci
irvlef------mphdtag-sd-----gateke----caaekqalwrvgm
gt-----fyqlp----nfattavkderckpqdcgrvhsq---qqilcrfe
ap-----kkskvsg----fagke------------ktnllmtkapngtv-
---------ne------------------lqhh---tawdvpepkdf---
-----d-------fr--kkvdwc--ahegss------fkmvfp------a
rgeavkscaygde--------akg---------nprakardlfdakkvna
skh-eeaeas-vagkktlsykdtkpsavhqy----atcihk---eymp--
s--sfskmkarpcgrqafs--lrkre-qegr
