>ENV_HV2D1/24-501
---hpdwgdraanvklqiklagd-ffnglykancipkn----nglnytev
plal-sn-----ti-gka-tlsatggp-al--e---c---dmdsrni---
cvkkdlewvagqkgslsagdgda---nkgsepcsikdkdaldndgva---
vrentvlvalvfggvrysiwpmvplyifkl-lgat---------------
f--------ecmvifyttrsng------k-----khrlam---tikrlte
ygfn------geahrgqaa-rfvgtlare--gwhrwhhadahvanhrafn
qsmad----wtqa---------lpsgyvqpkqviscp-------n-iggd
etfdkkcaevv-n----vgrglhkthflp-wqh--llvei-cyetlssa-
------egc-fgthhahdpd-fdmqt-vlgk---ika---dtev------
lsdpcik-tqpatnp--aygplmhgycnrlhslklgidc--ev-ckiskn
pv--dpqs-------------p-------vwnsa---kknvcsleryrs-
kfagnrahatanaqh-aavchakvfhael------dt--a--ysenaevk
aas------asaakilpaggcnqlsrqhaegevykdfncffkirfkah--
--ptkvlgedcv-tpigw---------------qphsqadtg-saqedde
af-vrsfca--syhhgarmd-
>node10
---hpdwgdraanvklqvklggd-ffnglykancipkn----nglsytev
peal-sn-----ti-gkt-tqkatggp-al--e---c-vsdmdsrni---
cv-kdlewvagqkg-lnagdgda---nkggepcsikdkdalinntaa---
qrentvlvalvfgggrytiwpmvpafifkl-lgaa---------------
f--------qcmviffttksngqkaatsk-----khrlgm---tikr-te
ygfn------geanrgqsa-rfvgtlvre--gwrrw--------nhkafs
qsmad----wtda---------lpsgyvqpkqvlscg-------n-iggd
etfgkkcaevv-d----vgrdlhkthffq-wvh--llees-cyeslssa-
------egc-fgthqahdpn-fdmqt-vlgk---ika---dnev------
lpdpcik-t--------tygplsrgycnrlnslklgiac--ev-ckiskn
pv--dsks-------------p-------vwnst---krnvcsleryrs-
kfagnranatanaqh-aavchakvfhadl------di--a--ysskee--
--hief---dsaakilptggcdeltrehgegevykdincflktrfkgh--
--ptkvlgedcv-spigw---------------qphsqadtg-saqqdde
af-vr------syhhaasld-
>node7
---hpewgd-a--vklaiklggd-g-nglfkss-iakh----h-----av
qa----------tiegsa-sakakgvaralaadsnsc-agdmdtrvi---
cv-qekpwqaadas-lnsgggta---geg---ctikdk-plihstaa---
prnnsvlvalv----rytlwpmegglifnl-lgaada------kv----l
lptedffdgqcmpiffivkvggeraedtk-----qhrlgm---vikr-ae
ygak------geasrgagaatfigtlvmn--qwrhw--------qheaat
nsitn----ltea---------lpsvhga-----scgsd---sdscingd
etfnkkceavg-d----vdrdlhkahffl-wlh--llses-cydslssa-
------egc-ygkhqgkd-d-ydmnt-vls----ika---nqdv------
lqdpcid-t--------tyvplsrgycnkvdslssgiac--dv-cktska
gv--dsntgmhqgvscty---l-------swnvt---ksnscslesyrn-
k--gnrtnstm-aqk-aeac-anvyyvarnplektnv--a--ysgkce--
--dvef---dspakilptggcdelpk---------eigcflkmrfkfhgp
giatkvleedcg-ksigw-------------rlephcqadtg-gsqqdda
tfgvr------syhyaasld-
>ENV_SIVV1/24-538
---hpewgd-a--vklaiklggd-g-tglfkss-yakhihran-----av
qa----------tiegga-sakakalaralaadtnsc-aanmdsrvi---
cv-ddkpwqasdag-mnsggdta---gda---ctikdk-pkihstaa---
krnnsilvali----rytlwpmeggfifnl-lggadaagmhtcqv----l
lptedfydgegmpifiivkvggergedtk-----qhrlg----------h
ygak------geaskgtgaatfvs---md--qwrnw--------qhqaan
nnvtn----ltes---------lpsvhga-----sctsem--sdacinge
gtfnkkceavg-d----idrdlhkahf---wlh--llres---eslssa-
------agc-yskhqgkd-dsynmna-vls----ika---nqdv------
lqepcld-t--------tyvplkrgycskvdglssgiac--av-ckaska
gv--dsntgthqgvscty---l-------swnvt---ktncc-lesykn-
k--gnrtnstl-aaklaeac-aqvyyvarnplekhnl--a--ysgkce--
--dtef---dspakilpsggcdelsk---------eigcflklrfkfngp
gittkvleeecg-krt---------------rldpscqvdtg-gsqqsaa
tfgvr----gdsyhysasld-
>node18
---hpdwgdraaniklqvklggd-ffnglykancipkn----nglsytev
peal-sn-----ti-gka-tlkatggp-al--e---c-isdmdsrni---
cv-kdlewvagqkg-lnagdgda---nkggepcsikdkdalanntaa---
vrentvlvalvfgggrytiwpmvpafifkl-lgaa---------------
f--------qcmviffttrsng------k-----khrlgm---tikryte
ygfn------geahrgqsa-rfvgtlvre--gwrrwhhadehvanhkafs
qsmad----wtea---------lpsgyvqpkqvlscg-------n-iggd
etfgkkcaevv-d----vgrdlhkthffq-wvh--llees-cyetlssa-
------egc-fgthhahdpn-fdmqt-vlgk---ika---dnev------
lpdpcik-tqp-tnp--tygplmrgycnrlhslklgiac--ev-ckiskn
pv--dsks-------------p-------vwnsa---krnvcsleryrs-
kfagnranatanaqh-aavchakvfhael------di--a--ysskee--
--hief---asaakilptggcdeltrqhaegevykdincffktrfkgh--
--ptkvlgedcv-tpigw---------------qphsqadtg-saqqdde
af-vr------syhhaasld-
>ENV_HV2G1/23-502
---hpdwgdraastklqvklggd-ffnglykadcipkn----nglsytev
peelgsn-----ti-gk--mlkaaggp-al--e---c-isdmvsrni---
cv-kdlewvadqkg-lnagdgds---nkggepcsikdkdalanntaa---
vrentv---lvfgggryivwpmtpafifklklgaa---------------
f--------qcmviffttksng------k-----khrlgm---tikr-te
ygfn------geanrgqsa-rfvgtlvre--gwrrw--------nhka-s
qsmad----wtda---------lpsgfvqpkqvlscg-------h-iggd
etfgskcphvv-dgspragrdlhktqffq-wvy--lleea-cyetlssa-
------egc-fgthhahd-n-fdmqt-vlgk---ika---dnev------
lpdpcik-tqp-tnp--tygplmrgycnrlhslklgigc--ev-ckiskn
pv--egks-------------p-------vwnsa---krnvcsleryrs-
kfagnradatanaqh-aavchakvfhael------di--a--ysskee--
--hief---asaakllptggcdeltrqhaegevykdincflktrfkpq--
--atkvlgedcv-tpigw---------------qshsqadtg-saqqdde
af-vr------syhhvasld-
>ENV_HV2BE/24-510
---hpdwgdrpaniklqvklggd-ffnglykancipkd----nglnytev
paal-sn-----sa-gka-alsatggp-ae--a---c---dmdsrnifwt
cvkkdlewvagqkg-laagdgda---nkggepcsikdkdalgnntav---
vrentvlvalvfgggrytiwpmvpafimkl-lgaa---------------
f--------qcmviffttrsng------kaaadrkhrlgm---tikrlte
ygvk------geahrgqaa-rfvgtlvre--gwrrwhhadahvanhkafs
qsmad----wtda---------lphgytqpkqvlscg-------n-lggd
etfgkkcaevv-d----vgrgahknhflq-rvh--lleer-cyetlsga-
------egc-fgtnqafdpn-fdmqt-vlgk---ika---dnev------
lp------sqpasnplktygplmrgycrflhslklgiac--ev-ckiskn
pa--epks-------------p-------vwnsa---krnvcslsryrs-
kfagnra---anfqn-aavchakvfhael------di--a--rpsnad--
--h------rsapkilptggcdeltrrhaegdvykdvncffkqrfkgh--
--ptkvlgedcv-tpigw---------------qphrqadpg-saqqdde
af----------yhhaasld-
>ENV_SIVGB/47-569
sak--q---------pggklaveag-ngrfkrt-ivqe----s-----al
dt----------pvvgat-saknkgisrtlaldtnsk-a------vv---
ci-ddlpwl-a-ts-lqfgd-epkvf--------tk-----lansda--k
tsagcvlltlv----sysa-----slgyn--------------kv----l
fkvpdffdaq----fflvkvgsakaeeak-----ahplsk---tmkr-ta
ysv--------tgnkcpgagaiiatlvagiadwrhw--------qqgqsp
salvnnrasltpghyhkrvikflptihgg-----scgss-tlfttcihgv
nefdskcqavg-d----idkdl-kahffe-wlyflmleqsgsegnldsap
atfqhpqac-flsh--kgpk-yqkgk-fla----ikavwaakdt------
lldsciqlv--------tndptklgyservtllssgiacntlaecktpkk
tfkadikt----------aakggfmcyav----trkwkgdscslqayqs-
i--etrtdhvv-saq-ae-c-adatcval------dvldt--yngind--
--svelksaesa--tlptggced-qm---------ekasflkmrfknh--
--atkiweedcg-ciign----------------phsgaktggrseqegs
tfgsr------pyrgaslvia
>node11
---hpdwgdraanvklqvklggd-ffnglykancipkn----nglsytev
peal-sn-----ti-gkt-tlkatggp-al--e---c-isdmdsrni---
cv-kdlewvagqkg-lnagdgda---nkggepcsikdkdalanntaa---
vrentvlvalvfgggrytiwpmvpafifkl-lgaa---------------
f--------qcmviffttksng------k-----khrlgm---tikr-te
ygfn------geanrgqsa-rfvgtlvre--gwrrw--------nhkafs
qsmad----wtda---------lpsgyvqpkqvlscg-------n-iggd
etfgkkcaevv-d----agrdlhkthffq-wvh--llees-cyetlssa-
------egc-fgthhahdpn-fdmqt-vlgk---ika---dnev------
lpdpcik-tqp-tnp--tygplmrgycnrlhslklgiac--ev-ckiskn
pv--dsks-------------p-------vwnsa---krnvcsleryrs-
kfagnranatanaqh-aavchakvfhael------di--a--ysskee--
--hief---asaakilptggcdeltrqhaegevykdincflktrfkgh--
--ptkvlgedcv-tpigw---------------qphsqadtg-saqqdde
af-vr------syhhaasld-
>node17
---hpdwgdraaniklqvklggd-ffnglykancipkn----nglsytev
peal-sn-----ti-gkg-tlkatggp-al--e---c-isdmdsrni---
cv-kdlewvagqtg-lnagdgda---nkggepcsikdkdylanntaa---
vrentvlvalvfgggrytiwpmvpafifkl-lgaa---------------
f--------qcmviffttrsng------k-----khrlgm---tikryte
ygfn------geahrgqsa-rfvgtlvre--gwrrwhhadehvanhkafs
qsmad----wtea---------lpsgyvqpkqvlscg-------n-iggd
etfgkkcaevv-d----vgrdlhkthffq-wvh--llees-cyetlssa-
------egc-fgthhahdpn-fdmqt-vlgk---ika---dnev------
ladpcik-tqp-tnp--tygplmrgycnrlhslklgiac--ev-ckiskn
pv--dsks-------------p-------vwnsa---k-nvcsleryrs-
kfagnranatanaqh-aavchakvfhael------di--a--ysskee--
--hief---asaakilptggcdeltrqhaegevykdincfyktrfkgh--
--ptkvlgedcv-tpigw---------------qphsqadtg-stqqdde
af-vr------syhhaasld-
>ENV_HV2D2/24-513
---npdwgdraanvklqvkpggd-ffnglykgncipnn----ngleytev
peal-cn-----ti-gktytqkatggp-al--e---c-vsnmdsrni---
cv-kdlewvngqkg-lhagdgda---gkggepcsikdkdalinhsaa---
qrestvlvvlvfgggrttiwpmvagfifkl-lgaa---------------
f--------pcmsfffsttnndqkaatsk-----khrlgm---tikr-te
vgfd------geafrgqss-rfigtlire--gwrrw--------nnkafs
qsmad----wtda---------vpggyvqpkqvfscg-------n-iggn
atfgkkcaevvgd----vgrdlhkvhffq-wvh--lleeg-cyeslssa-
------dgc-fgthqshnpn-femqt-vlgk---ika---dnev------
lpdpctk-t--------tysplsrgyckrlhslklgiac--ev-ckiskn
pv--dskg-------------p-------vwnpt---krnvcslerhrs-
kfagkratatasaqh-aalchpkvfhsdl------di--ksnysskee--
--hief---daaa-------cdcktrehdegevykgincfnktrfkgh--
---trvlgedcv-spigf---------------qphsqadtg-saqqdde
sf-ir------sfhhgesld-
>ENV_SIVM1/24-528
---hpdwgdraanvkmavtlggd-yfnglyrancipkn----nglsytea
aaal-sn-----ti-gkt-tpsatgtp-al--e---c-vgdmdsrtv---
sv-kdlewiagqtg-lnagdgdv---skggepcsikdhdalinntaa---
qrentvlhalvfgggwytiwpmigefifkl-lgaa---------------
f--------qcmpifftskvnsqksaask-----khrlgmasvtikr-te
ygyn------geanrgqss-rfvgtlvrd--gwrrw--------khrafs
qsmtd----wtda---------lpsgykhpmqvlscg-------n-ingd
etfdkkcaevg-d----vardlhkthffq-wvh--llqes-cyaslsra-
------egclfgshqarepn-fdmqtpvlgk---ika---dnev------
lhdpcik-a--------tyvhlsrgycnplnslklgiac--qv-ckirkn
pv--dsks-------------l-------vwnng---krnvcslqryrs-
kfagnrtdatlnaqn-aavchakvyhael------di--a--ystkae--
--hief---dwaakilptggcdeltkehge-evyknincflktrikgh--
--ptkvlgedcvknpigw---------------qphsqadtg-saqqdda
af-vr------syhhersld-
>node9
---hpdwgdraanvkmavklggd-ffnglykancipkn----nglsytev
aeal-sn-----ti-gkt-tqkatggp-al--e---c-vgdmdsrtv---
cv-kdlewvagqkg-lnagdgda---skggepcsikdkdalinntaa---
qrentvlvalvfgggrytiwpmvgafifkl-lgaa---------------
f--------qcmpiffttklngqkaatsk-----khrlgm---tikr-te
ygyn------geanrgqsa-rfvgtlvrd--gwrrw--------nhkafs
qsmtd----wtda---------lpsgyvqpkqvlscg-------n-idgd
etfgkkcaevg-d----vgrdlhkthffq-wvh--llees-cyaslssa-
------egc-fgshqardpn-fdmqt-vlgk---ika---dnev------
lqdpcik-t--------tyvplsrgycnrlnslklgiac--ev-ckiskn
pv--dsks-------------l-------vwnng---krnvcsleryrs-
kfagnrtnatlnaqn-aavchakvfhadl------di--a--ysskee--
--hief---dsaakilptggcdeltkehgegevykdincflktrfkgh--
--ptkvlgedcv-spigw---------------qphsqadtg-saqqdda
af-vr------syhhaasld-
>node14
---hpdwgdraaniklqvklggd-ffnglykancipkn----nglnytev
paal-sn-----ti-gka-tlsatggp-al--a---c---dmdsrni---
cvkkdlewvagqkg-lnagdgda---nkggepcsikdkdalanntaa---
vrentvlvalvfgggrytiwpmvpafifkl-lgaa---------------
f--------qcmviffttrsng------k-----khrlgm---tikrlte
ygfn------geahrgqaa-rfvgtlvre--gwrrwhhadahvanhkafs
qsmad----wtea---------lpsgyvqpkqvlscg-------n-iggd
etfgkkcaevv-d----vgrglhkthflq-wvh--llees-cyetlssa-
------egc-fgthhahdpn-fdmqt-vlgk---ika---dnev------
lpdpcik-tqpatnp--tygplmrgycnrlhslklgiac--ev-ckiskn
pv--dpks-------------p-------vwnsa---krnvcsleryrs-
kfagnrahatanaqh-aavchakvfhael------di--a--yssnae--
--h------asaakilptggcdeltrqhaegevykdincffkirfkgh--
--ptkvlgedcv-tpigw---------------qphsqadtg-saqqdde
af-vr------syhhaasld-
>ENV_SIVG1/22-522
---hpewgd-a--vrlaiklggd-g-nllfkss-vikh----h-----av
qa----------tiegsa-sakakvvaralsadsnsc-agdldtrgi---
cv-qekpwqapdas-lnsgggta---geg---ctikdk-plihsqaa---
prnnsvlvalv----rytlwpmegglifkl-lgaada------kvivlpl
lstedffdghcmaiffrvkvggeraedt--------rlgm---tikr-ag
ygtk------geatrtagaatfigtlvmn--qwrhw--------qnqqvt
ksitn----ltea---------lpsvhgv-----scgsd---sdscingd
etlnk--eavg-d----verdvhkahffl-wlh--llses-cydslspa-
------egc-ygqhqgkd-d-femnt-vls----ika---nqev------
lqdpcid-t--------tyvplsrgycnkveslsdgiac--dv-cktska
gv--dsntgmhqgtpvty---l-------pwnvs---ksnscslesfrn-
k--gnranstm-aqk-aeac-aivlyvarsplektnv--a--ysgkce--
--dvef---dtpakilptggcaelpk---------eigcfakmrfkfnap
giatnvleedcg-ksigw-----------kfrlephcqadtk-gsqqdda
tfgvr------syhyaasvd-
>ENV_HV2CA/25-512
---hhewgdrasniklqvklggd-mfnglykancisks----kglsytev
aeal-sn-----ti-gkg-tmkat-----l--e---c-isdmdsrni---
cv-kqlewvagqtg-lnpgdgda---hkggapcsikdkdylanntaank-
vrentilvalvfgggrytkwpmvpafifgl-lgaa---------------
f--------qcmviffitrdng------k-----khrlgm---tikryte
ygfn------geahrgqsa-rfvgtlvre--gwrrwhhadehvanhkafs
qsmad----wtes---------lsygyvqpkqvlscg-------n-idgd
etfgkkcvepv-d----vgrelhkthffqswvh--llees-cydtlssa-
------egc-fgthhandpk-femqs-vlgn---ika---ddevlsqtca
ladscvk-vqp-tnp--tygplmrgycnrlhslklgiac--ev-cknskn
pv--esks-------------p-------vwnsa---k-hvcsleryrg-
kfagnqasatanaqf-aavchatvfvaem------ei--a--ysgkee--
--hief---asaakilptggcdeltkqhaegevykdincfyktrfkga--
--ptkvlggdcv-tcigw---------------qphsqadtg-sthqdde
af-vr------syvhaasld-
>node19
---hpdwgdraaniklqvklggd-ffnglykancipkn----nglsytev
peal-sn-----ti-gka-tlkatggp-al--e---c-isdmdsrni---
cv-kdlewvagqkg-lnagdgda---nkggepcsikdkdalanntaa---
vrentvlvalvfgggrytiwpmvpafifkl-lgaa---------------
f--------qcmviffttrsng------k-----khrlgm---tikryte
ygfn------geanrgqsa-rfvgtlvre--gwrrw--------nhkafs
qsmad----wtda---------lpsgyvqpkqvlscg-------n-iggd
etfgkkcaevv-d----vgrdlhkthffq-wvh--llees-cyetlssa-
------egc-fgthhahdpn-fdmqt-vlgk---ika---dnev------
lpdpcik-tqp-tnp--tygplmrgycnrlhslklgiac--ev-ckiskn
pv--dsks-------------p-------vwnsa---krnvcsleryrs-
kfagnranatanaqh-aavchakvfhael------di--a--ysskee--
--hief---asaakilptggcdeltrqhaegevykdincflktrfkgh--
--ptkvlgedcv-tpigw---------------qphsqadtg-saqqdde
af-vr------syhhaasld-
>ENV_HV2NZ/24-502
---hpdwgdradnsklevalggd-ffnglykancmpkn----ngssytel
peal-snsctgntt-gkg-tlklaggp-al--e---clisdmdsrgi---
cv-kdlewvagqtg-lntgdgda---nkggepcsikdkdylanntaa---
vrmntvlvalvfgkgrytiwpkvpafiftl-lgaa---------------
f--------scmviffttrsdg------k-----khelgm---tikryte
yginahaaaqggvhrgqsa-rfvgtlvre--gwrrwhhadghvenhkaft
qsmae----wtet---------lpsgyvnpkqvlscp-------d-iggd
etfgkkcaevv-d----vgrdlhkihffq-wva--llses-cyetlsga-
------egc-fgthhahdpn-fdlqt-vlgkipgika---deev------
ladpcik-tqp-tnp--tygplmrgycnrlqslklgiac--ev-ckiskn
pv--dsks-------------p-------vwnta---k-ngcslerfrsv
kfagnranatanaqh-avvchakvfhpel------di--a--ysakee--
--hief---asaakilptggcdeltrphpegevykdidcfyktrfkgh--
--ptkvlgqecv-tpigwqllaaeakila----qphsqadtg-shqqdde
af-vr------syhhpasld-
>node8
---hpewgd-n--vklavklggd-g-nglfkss-iakn----n-----av
qa----------tiegst-sakakgvaralaadsnsc-agdmdtrvi---
cv-qdlpwmaadas-lnsgdgna---geg---csikdk-plihntaa---
qrnnsvlvalv----rytvwpmegslvfnl-lgaana------kv----l
fptedffdgqcmpiffivkvggekaedsk-----qhrlgm---vikr-ae
ygak------geanrgagaatfigtlvad--qwrrw--------qheapt
esitn----ltea---------lpsvhga-----scgsd---sdscidgd
etfdkkceavg-d----vdrdlhkahffq-wlh--llses-cydslssa-
------egc-ygkhqgkdpn-ydmna-vls----ika---dqdv------
lqdpcid-t--------tyvplsrgycnrvdslssgiac--dv-cktakr
gv--dskt-------------l-------swnvt---kgnscslesyrn-
k--gnrtnstm-aqk-aegc-anvyyval------ni--a--ysgkse--
--hvef---dspakilptggcdelpk---------eihcflkmrfkgh--
--atkileedcg-ksigw-------------rlqphsqadtg-saeqdda
tfgvr------syhyaasld-
