>ENV_HV2NZ/24-502
qlc-------stgd-vcddsstagvptlikmqkvdalkpwsaqrhipqeq
ric--lvhanpsycrkvk-eelwvgaqydnpknrkrhdefqssffasmkg
a----llfgdkdcivp-rftdcillpkklpwesl-----kankdfkvaf-
aag-gfddmwdqnnhtyspa---qvpqekkylevngtsiygkvafigvkd
kvglgqsvai-elw---atkpp-----------klrssvqvat-g----a
--aipkacev----------hfrkpklep---------yavgdeneplgt
kee----knk--kkpad------------kgkkgygpqktritycvtnkp
-dlls--esasalfnlshthpl--ntdwrtdrsy----------ngdgkn
rfgt---tnriena--llklakkqntlf----rlafglekakpvakvsay
ghdkplrvgsgsgsksvkiseslhkkgg-agtminqlmsapsqskpapgp
ly--rkaaidlmt----dtihktkglg-lqwlitlnsghplgsegnyl--
---tet-twgrri----gsee--pvgitsp----s------ieiwdehig
w-------nap----qf--vrlpdfftnh--gs-------l-------ra
hcsvgidtagreakg---kscnrgrltsef
>node19
qlc-------sags-vcddsdtagipslikmqkvdalkpwtaqrnpqqeq
ric--l-halpaycrkvk-eelwtgaqydnpknr---defqsaffanmkg
a----lafgdkdcivp-rftqcivlpkklpwesl-----qankdfkvaf-
aag-gfadmwdqnnhtyspa---qvprdkkylevngtsiygkvafigvkd
kvglgqsvai-elw---atkpp-----------klrssvqvat-g----a
--aipkacdv----------hfrkpklep---------yaksdeneplgt
kee----knk--kkpgd------------kgkkeygpqktritycvgnkp
-ells--esasalfnlghtrpl--ntdwrtdrsy----------ngdgkn
rfgt---tnkient--ll--akkqntlf----ilafgfekaapvakvssy
ghdkplrvgsgs-sksvkisdrlhkngg-agtminqlmsapsqskpapgp
lf--rkaainlit----dt-----glg-lqwlitlnsthrlgsegnyl--
---tet-twarki----gsee--pvgitss----s------ieiwnehig
w--m----nap----ql--vrlpdffteh--gs-------l-------ra
pcsvgtdtaareakgdghkscnrgrl-sef
>node11
qlc-------sags-vcedsdtagipslikmqkvdalkpwtaqrnpqqeq
ric--l-halpaycrkvk-eelwtgaqydnpknr---defqsaffanmkg
a----lafgdkdcivp-rftqcivlpkklpwesl-----qankdfkvaf-
aag-gfadmwdqnnhtyspa---qvprdkkylevngtsiygkvafigvkd
kvglgqsvai-elw---atkpp-----------klrssvqvat-g----a
--aipkacdv----------hfrkpklep---------yaksdeneplgt
kee----knk--kkpgd------------kgkkeygpqktritycvgnkp
-ells--esasalfnlghtrpl--ntdwrtdrsy----------ngdgkn
rfgt---tnkient--ll--akkqntlf----ilafgfekaapvakvssy
ghdkplrvgsgs-sksvkisdrlhkngg-agtminqlmsapsqskpapgp
lf--rkaainlit----dt-----glg-lqwlitlnsthrlgsegnyl--
---tet-twarki----gsee--pvgitss----s------ieiwnehig
w--m----nap----ql--vrlpdffteh--gs-------l-------ra
pcsvgtdtaareakgdghkscnrgrl-sef
>node14
qlc-------sags-vcddsdtagipslikmqkvdalkpwtvqvniqqeq
ric--l-halpaycrkvk-eelwtgaqydnpknr---defq--ffanmkg
a----lafgdkdyivp-rftqcivlpkklpwesl-----qankdfkvafv
aag-gfadmwdqnnhtyspa---evpqdkkylevngtsiygkvafigvkd
kvglgqsvai-elw---atkpp-----------klrssvqvat-g----a
--aipkacdv----------hfrkpklep---------yaksdeneplgt
kee----knk--kkpgd------------kgkkeygpqktritycvgntp
-ells--esasvlfnlghtrpl--ntdwrvdrsy----------nndgkn
rlgt---tnkient--ll--akkqntpf----ilafgfekaapvakvssy
ghdkqlrvgsgs-sksvkisdrlhkngg-agtminqlmsapsqskpspgp
lf--rkaainlit----dt-----glg-lqwlitlnsghrlgsegnyl--
---tet-twgrki----gshh--pvgitse----s------ieiwnehig
w--m----nap----ql--vrlpdffteh--gs-------l-------ra
pcsvgtdtaareakgdghkscnrgrl-sef
>node17
qlc-------sags-vcddsdtagipslikmqkvdalkpwtaqrniqqeq
ric--lvhalpaycrkvk-eelwtgaqydnpknr---defqsaffanmkg
a----lafgdkdcivp-rftqcivlpkklpwesl-----qankdfkvaf-
aag-gfadmwdqnnhtyspa---qvpqdkkylevngtsiygkvafigvkd
kvglgqsvai-elw---atkpp-----------klrssvqvat-g----a
--aipkacdv----------hfrkpklep---------yakadeneplgt
kee----knk--kkpgd------------kgkkeygpqktritycvgnkp
-dlls--esasalfnlghthpl--ntdwrtdrsy----------ngdgkn
rfgt---tnkient--ll--akkqntlf----ilafgfekakpvakvssy
ghdkplrvgsgs-sksvkisdslhkngg-agtminqlmsapsqskpapgp
lf--rkaainlmt----dtihktkglg-lqwlitlnsghrlgsegnyl--
---tet-twgrki----gsee--pvgitss----s------ieiwnehig
w--m----nap----ql--vrlpdffteh--gs-------l-------ra
pcsvgtdtagreakg---kscnrgrl-sef
>ENV_HV2CA/25-512
qlc-------sags-vcddsdtvgipslhkmqkvdalkpwtpqrniqqeq
ric--lvhalpaycrsvr-eelwtgaqydspknr---eefqskffanmkg
g----lafgdkdcivp-rftqcivlpkklpwesl-----qankdfkvaf-
aag-gfasmwdqnvhtyspa---rvpqdkkylevngtsiygkvgfigvkd
kvglgesvai-elw---atrpq-----------klrssvqvad-g----a
--aipkacdv----------hfrkpklqp---------yakadeneplgt
kqe----kns--krpgd------------kgkkeygpqktritycvggkp
-nlls--e-ssalfklghthpl--ntdwrtdrsy----------ngngkn
rf-s---tnkient--ll--akkdntll----mlafgfekarpvakvssy
ghdkplrvgsgs-tksvrisdalhknga-agtminqlmsapsqskpapgp
lf--rkaaidlktgfkcdaihktkglg-lqwlitlnsghragsegnyl--
---tntvtwgrki----gsee--pvaitsa----s------ieiwnehig
w--m----nak----ql--vrlpdffteh--sm-------l-------ra
pcsvgtdtpgreakg---kscnrkrl-sef
>node7
qvc-------aagv-lcqddekpgipalikkekfdalspwdaqreeeqeg
kas--l-halpgfcstskgeq--ssadyshpksm---defqsayf----g
s----lafaekkcvvp-ageacirlpkklkwgnl-----hdsk-------
qdg-gfasmadnnnhvfspa---qiprdkrwld--gs-------fvgvkt
kvgspakvvi-qlw------pp-----------kliasmlvys-g----v
--svqkacd----------------klis---------yyksdeeqplgt
kedwvlekse--kktvgl----------angkkehgp-etris---gkkp
-amls--e----------------ntdwltapsy----------ngdgin
rlea---tgkieht--f------vktia----vlafgfeklepvpklqsy
gheiplavvhan-nk-----------as-pstminplmraraieq---gs
ly--lktaisigv----dk-----glg-lq--ttlnethllgn-knyl--
---iqt-swersa----greeikpcgttar----a------iqvwd----
w--m----ksvkgvsqlk-----dffteh--gs-------lcdgtpdlpg
pcgvgtdta-----adshkscshtkp-sef
>ENV_HV2D2/24-513
qlc--gtgwdtags-yceesdtagipslinmqkvdalkpwtaqrqpqeeq
ric--l-hallaycrkvk-eqvwtgaqydnpkir---sqyqsafyanlkg
e----lsfaekdcavp-rfcqcivlpr-lpwesm-----qankdfkvaf-
tag-gfadmwdqnnhtyspa---qvprdkkalvvngtaiygkvafigvks
kvgigqsvai-tlw---atkpp-----------klrs-------g----a
--anpkacdv----------hfrkpklep---------fnksnenqpmgk
kee----knk--nkpgd------------kgkkeygpqktriaycvgnks
-eils--esasallnlghtrpl--nsdwrtdrsy----------ngdgkn
rfgg---gnkient--ll--drkqnslf----ilafgfekanpvgkvsan
ghdtplrvgsas-aksgkirnrlhsgag-agtgvnllmsapsqskpasgp
lh--rkaalnlit----dt-----g-g-lqwlitlnethnlgs-gnyl--
---aet-kwarki----gsde--pvgatss----slllchaieiwne-ig
w--r----napreigql--trlpdffteh--gk-------l-------ra
pcsvgtdtatreakgdghqscqrgrl-sef
>ENV_SIVV1/24-538
qvc-------vtgv-lcqdsakpgip--ikkekfdalspweiqreeeqeg
rasvcl-halpgfcsiskseq--stadynhpksa---dqfqspyf----g
ks---lafaekkcavp-sgeacirldkknkwgnl-----hdnk-------
qng-sfasmadnnnhvfgpa---qiprdkrwld--gs-------lvgvqt
kagspakvvi-qlw------pp-----------kliasmllygng----v
--avqkace----------------klis----------yrpkdkqplgt
kepwllekseigkktvgl----------tngkkehsp-qtris---gkkp
-emls--q----------------hvdwltkpsy----------ngdgin
rlqaakptgtieht--f------vkkia----llafgfeklepvpklqsy
gheiplasvhad-dk-----------an-pktminplmrgra--q---gn
lygplksaisygv----dk-----glg-lq--ttlnadhllgn-kayl--
---ies-swernc----grdeikpcgttar----a------iqvwn----
w--m----ksvnggsqik-----effgelslgs-------lcqgqpdqpg
pcglgtkta-----adshkscshtkp-sef
>ENV_HV2G1/23-502
qlc-------sags-vcedsdtagipslikmqkidalkpwtaqrnpqqet
ric--l-halpaycrkvk-eelwtgaqydnpknr---gefqsaffanmkg
a----lafgdkdcavp-rftqcmvlpkklpwesl-----qankdikvaf-
aag-gyadmwdqnnhtyspa---qvprdkkylnvngtsiygtvafiavks
kvglgesvtl-elw---atkpp-----------klrssvqvat-e----a
--aipktcdvnlkqsrcatchfrkpklep---------yaksdeneplgt
kee----knk--kkpgd------------kgkkeygpqktritycvgnkp
-ells--esasalfnlghtrpl--ntdwrtdrsy----------tgdgkn
rfgs---tnkient--ll--askqntlf----ilafgfekpapvakvssy
ghdkplrvgsga-sksvkisdrlhkygg-agtminqlmsapsqskpaagp
lf--riaainlit----dt-----glg-fqwlialnsthvlgsegnyl--
---aet-twarki----gsed--pvgitgs----p------ieiwnehig
w--m----nap----ql--vrlpdffteh--gs-------l-------ra
pcsvgtdtaarqakgdgnkscnrdrl-sef
>node18
qlc-------sags-vcddsdtagipslikmqkvdalkpwtaqrniqqeq
ric--l-halpaycrkvk-eelwtgaqydnpknr---defqsaffanmkg
a----lafgdkdcivp-rftqcivlpkklpwesl-----qankdfkvaf-
aag-gfadmwdqnnhtyspa---qvpqdkkylevngtsiygkvafigvkd
kvglgqsvai-elw---atkpp-----------klrssvqvat-g----a
--aipkacdv----------hfrkpklep---------yaksdeneplgt
kee----knk--kkpgd------------kgkkeygpqktritycvgnkp
-ells--esasalfnlghtrpl--ntdwrtdrsy----------ngdgkn
rfgt---tnkient--ll--akkqntlf----ilafgfekaapvakvssy
ghdkplrvgsgs-sksvkisdrlhkngg-agtminqlmsapsqskpapgp
lf--rkaainlit----dt-----glg-lqwlitlnsghrlgsegnyl--
---tet-twgrki----gsee--pvgitss----s------ieiwnehig
w--m----nap----ql--vrlpdffteh--gs-------l-------ra
pcsvgtdtaareakgdghkscnrgrl-sef
>ENV_HV2BE/24-510
qlc-------sags-vcddsdtsgipsmikmqrvealkpwtvqpniqleq
ric--l-halpafcrkvk-eelwtgaqyenpknr---deiq--ffanmkg
a----rafgdkdyiva-rftqcivlp-----esl-----qankdfkvafv
aag-gfaemwdqknrtyspa---evsqdkkylevpgssiygkvgfigvkd
kvglgqsvai-elw---atmpp-----------klpssvqvat-g----a
--aipkacdv----------hfrkpklep---------yaksdeievlgt
kee----kdk--kkpgd------------kgkkeygpqktritycvggtp
-ells--enasvlfdlghtrpl--ntdwrvdrsy----------nndgkn
rlgt---tnkipntktll--aknqntpf----flafgyekaapvakvssy
gndkqlrvgsgs-srtvkisdrlhkngg-agtmekqlmsaperskpsqgp
lf--rkaainli------t-----gvg-lqwlitlnsghrfgsegnyl--
---tet-twgrki----gshh--pvgitre----s------idiwnehig
---------pp----ql--vrlpdffteh--gs-------l-------rs
pcsvgtdtaaqdakgdghkscnrgrl-tef
>node8
qvc-------aagv-lceddekpgipalikkekfdalspwdaqrepeqeg
kac--l-halpgfcskskgeqlwsgadyshpknm---defqsayfanltg
s----lafaekdcgvp-nftaciilpkklkwanl-----hdsk-------
qdg-gfasmsddnnhvfspa---qvprdkrwld--gt-------fvgvkt
kvgsaakvvi-qlw------pp-----------klkasmlvys-g----v
--svqkacd----------------klit---------yyksdeeqplgt
kedwvlekse--kktvgl----------akgkkeygp-ktris---gskp
-amls--e----------------ntdwltapsy----------ngdgin
rfga---tgkieht--fl--akkiktiy----vlafgfeklepvaklqsy
gheiplavvras-sk-----------as-pstminplmrapaieq---gs
ly--lktaisigt----dt-----gla-lq--itlnethmlgn-knyl--
---iet-swersa----gree--pvgttak----s------iqvwn----
w--m----ksvkgvsqlktvrlpdffteh--gs-------lsegtpnlrg
pcgvgtdtaakeakadshkscsrgrp-sef
>ENV_SIVM1/24-528
slc-------sags-vcedsdtagnprlikkqkvdalkpwtaqrnpqqer
ric--l-halpaycrkvk-eqlwktkqyanpknr---ddfqsaffanlkg
a----lafgekdcalp-kftqcivlpkmlpweal-----eenkdfkkaf-
dag-gfddmsdlnkhtyspa---qiprdkkwlevngtaiygkiafvgiks
kvgegqsvai-qlw---atkpp-----------klrssvqvat-g----a
dlavppscdv----------hfrkpkltt---------ynkadeneplgt
kde----knk--kkpvg------------kgkkeygpqkeriaycvgnkp
-ells--esasalfnlghtrql--ntdwmtdrsy----------ngdgkn
rlgt---ttkient--ll--arkqntlf----ilafgfekasplakvsny
ghdiplrvgsas-sksgkvsdrlnkngg-agtminqlmrapsqnq---gs
lf--rkaaielit----dt-----gla-lqwlitlgethklgs-snyl--
---tet-twarki----g-------gttst----s------ieiwnshig
w--m----klpreigql--vrlpdfftdq--gs-------l-------ra
pcgvgtetaareskadghkscnrgkl-spf
>ENV_SIVG1/22-522
qic-------aagv-lcqddekpgipalikkekfdalsardaqre-eqeg
las--l-halpgfcstskgeq--ssad----ke-----eyqsayf----g
p----lafaekkcvvp-egeacirlpkklkwnnl-----hdsk-------
qdgtgfaamaddhnhvfspatm-qiprdkrwld--gs-------fvgvkt
kvgspakvti-qlw------pp-----------kliasalvys-g----a
--svqkacd----------------klislaelsgkeiyyksdaemplgt
kedwvvekse--kktvgl----------pngksehgp-etgis---gkkp
-amls--e----------------ntdwltapay----------sgdgin
rlea---tgkieht--f------vktia----vlafgfeklepvpklqsy
ghdvplaavntn-nk-----------asvpstminplmraraieq---gs
ly--lktaikigv----ek-----glg-lq--ttln---------nyl--
---iqt-swersa----greeikpcgatarvgsga------iqvwn----
w--m----knvkavsqlk-----dffteh--fs-------lcdgtpdlpg
pcgvgtdta-----adehkscshtkp-cef
>node10
qlc-------sags-vcedsdtagipslikmqkvdalkpwtaqrnpqqeq
ric--l-halpaycrkvk-eqlwtgaqydnpknr---defqsaffanlkg
e----lafgekdcavp-rftqcivlpkklpwesl-----qankdfkvaf-
dag-gfadmwdqnnhtyspa---qvprdkkylevngtaiygkvafigvks
kvgegqsvai-elw---atkpp-----------klrssvqvat-g----a
--aipkacdv----------hfrkpklep---------ysksdeneplgt
kee----knk--kkpgd------------kgkkeygpqktriaycvgnkp
-ells--esasalfnlghtrpl--ntdwrtdrsy----------ngdgkn
rfgt---tnkient--ll--akkqntlf----ilafgfekaspvakvssy
ghdkplrvgsas-sksgkisdrlhkngg-agtminqlmsapsqskpasgp
lf--rkaainlit----dt-----glg-lqwlitlnethnlgs-gnyl--
---tet-twarki----gsee--pvgitss----s------ieiwnehig
w--m----napreigql--vrlpdffteh--gs-------l-------ra
pcsvgtdtaareakgdghkscnrgrl-sef
>ENV_HV2D1/24-501
qlc-------sags-tcddsdtagvpslikmqsvdalrpwtvqvnirqeq
ric--l-halpaycrkvk-eelwsgaqydgpkdr---deyq--ffanmkg
a----lafndkdyivp-rftecivlpkklpwssl-----qgskdfkvefv
aag-gfadrwdqnnhkyspa---evpqdkkylevngtsiygkvafrgikd
kvglgqsiai-dlwlgvatkpp-----------klrssvqvas-f----a
--aipkacdv----------hfrkpklep---------yaksdeseglgt
kee----knk--kkpdd------------kgkkeygpqktritycvgdtp
vells--asasilfnlghtrpl--ntdwrvdrsy----------nnegkn
rlgt---tnkiant--ll--akkqntpfaylkilsfgfekaapvakvssy
ghdkqlrvgsgs-sksvkisdrlekngg-agtminqlmsapqqskpspgp
lf--rkaainlit----dt-----glg-lqwvitlnsghrhgsegnyl--
---tet-twgrki----gthh--pvgitse----s------ieiwnehig
w--m----nap----al--vrlpdffteh--gs-------l-------ra
pcsvgsdtaarqakgdghkscnrgrl-sef
>ENV_SIVGB/47-569
evcrn-----aagvvl-ehvg---itgvndkqkgqg-------reaqqks
qa---l---lpgmcdr----qiwacpdfshcknm---dgfk--------p
c-lanmqlaqsdchags-----vl----lk---tlapqlddnk-------
kng-dfaglsavnehifspa--nqvprdnpwld--dr-------fiaida
kigtsnkivaaqlw------ppileypafltmqrmktkslgys-hrlvy-
----i-scd----------------kliv---------yckpnqkgclgt
k-dwgledaq--keavevtsfgkvgnct--krreypd-eer-g---gkkr
-pmlasdq--------------eknnkwdsapnhvlegrlsnggqsdgi-
-fss---sgksdhv--fh--skkllrny----fksahfqsleivaklvg-
---iplvvl-----k-----------gs-dpgtiaplmrrpgyeq---gs
vy--lkttlsvgy----st-----glaglg--fsldqanslnn-ksyfvl
qqkias-kwrrtgdatsgrge--sigsaak----g------saiwa----
wniawinl--vasih---tvklpdf------kspalgrqltn-gspnfeg
pctvgtd-------ndnmla---------f
>node9
qlc-------sags-vcedsdtagipslikkqkvdalkpwtaqrnpqqek
ric--l-halpaycrkvk-eqlwdgaqyanpknr---defqsaffanlkg
a----lafgekdcavp-nftqcivlpkklpwesl-----qdnkdfkvaf-
dag-gfadmsdqnnhtyspa---qvprdkkwlevngtaiygkvafvgvks
kvgegqsvai-elw---atkpp-----------klrssvqvat-g----a
--avpkacdv----------hfrkpklet---------ysksdeneplgt
kee----knk--kkpvg------------kgkkeygpqktriaycvgnkp
-ells--esasalfnlghtrpl--ntdwmtdrsy----------ngdgkn
rfgt---tnkient--ll--akkqntlf----ilafgfekaspvakvssy
ghdiplrvgsas-sksgkisdrlhkngg-agtminqlmrapsqnq---gs
lf--rkaainlit----dt-----gla-lqwlitlnethklgs-nnyl--
---tet-twarki----gsee--pvgttss----s------ieiwnehig
w--m----kspreigql--vrlpdffteh--gs-------l-------ra
pcgvgtdtaareakgdghkscnrgrl-sef
