>node9
--kmfvprsptyldqp---apekklkltenyseklrstass-----ahaa
sgkkamln-a-pk--fspg-llewrwl----glq--aenwpddqdncesf
rnlg-t-saqlnvtggdevtlnlgpkkkidf---------chas----gn
-dewiasknmnwhk-gkdnyyrqypyttagkgdrgvlrteftk-ginygh
klf-------kqygqaiqgvtmgasiqa-------sd-shmwltgtidte
aienyrcvl--r---------hg---gaiqaggaq--k------------
cyymv-nky-glpng---l--lv-kgadnrkvpl--yinadnspkyplls
srgdcfnlqrssgyapvha------centd----aeiasrqakdley-mv
patp-------mkllkvgallhaggf-------tta-dedifkvhps--t
t-vggr---pkaappkhdklggtelsthpaeep------afittaks-if
--psslftdtmqtihplvnaktapch--gta-tqaeaqansfawlelt-e
adipqi----nfkly--ralgrwnnsn---ql-------------kfvfa
ntpallhfkhn------qr--qatvafsvgq-klhatptsqlqpyiakfe
fgi---------keggv-----fqa-k--cgtikvrlitdhdqc-eksk
>ENV_SIVM1/24-528
takmfvprsptyldqp---apgkklmltenyse-----ass-----ahaa
sgkkam-----------------wrwl----glq--aenwpddedncesf
rnlg-t-saqlnvtggdevpfdlgskkkidf---------chaa----gt
-dewias---nwhk-gknnyyraypytiagkgdrgvlwteftk-gvnygh
klf-------kqygqaihgvtmgatcqa-------sd-shmwltgtinte
aienyrcvi--r---------hg---gaiqaggneeskevaaqgsasyan
cyymv-dky-glpng---l--lv-kgadnrkvpl--yinpdnspkyplls
srgdcfnlqrssgyapvha------cpktd----aeiprrqaknldy-mv
papp-------irllkvgallhaggf-------tta-dedlf--hps--t
t-vggr---pkaappkhdklggtelsthpaeep------sfittaks-if
--psylftdtmhtihplvdakkapch--gta-tqaeaqassfawlelt-e
adipqi----nfkmy--ralgrwnnsn---ql-------------kfvfa
ntpaklhfkfn------qh--qatvafsvgq-klhatatshlqpyvarfe
fgi---------keggv-----fqa-k--cgtikvrlitdhnqc-eksk
>node14
--kmfvprsptyldqp---gpekklkltenyse----tass-----ahaa
sgkkamln-k-pk--fspg-llewrwl----glq--aenwp------esf
rnlg-t-saqlnvtggdevtlnlgpkkkidy---------chas----gn
-dewiasknmnwnk-gktnyyrqypyntagkgdrgvlrteftk-nlnygh
klf-------kqygqaidgvtmgasiqa-------sd-spmwltgaidte
aienyrcvl--r---------hg---ngiqaggaq--k------------
csymv-nky-gipdg---l--lv-kgednrkvpl--yigvdnspkypyls
sradcfnlqrssgyapvpt------centd----aeiasrqakdiey-mv
patp-------mkllkvgal--aggf-------sta-dedifkvhss--t
t-vagr---pksapp--dklggtelskhpaeep------afisaaks-if
--pgflftdtmqtihpvvnaktapch--gta-tqaeaqaksfawlels-e
edipqi----nhkly--ralgrwnnsn---ql-------------kfvla
ttpsllhfkhn------qr--qatlafsvgq-klhatpspqlqpyiakfe
fgi---------kqggv-----fes-kllcmtikvrlitdhdqcreksk
>ENV_SIVGB/47-569
---mitpnkpyctvsh---prdkklkltenf-----ehars-----grp-
-snkeklg-q-pileftpgtlltwewt-----lt--tekwpqmeqs-eny
ddng-h-sasahs--sygitknv---awiacaigllkayr-rdeqggdan
-qewipgkgtgwdn-snenfygklsyvimgkhekgiymtntlkkdsdcae
-iffdlvhfviqygrqalkvslggnvvmsvlsytpaevgkr----vvv--
----yacvl--h---------rglslgalqvsgpg--a------------
cyyis-nkytaiqdq---gaav------grkmal--fiktnngvnfplls
f----------------wsarstfdtakle----a------skdkkyiiv
slip-------vkfi-vgalhegagy-------kst-eanvfkvhpi--p
idvaepapyvkadkpnh--ntgtvnakhptcqg------nyv--shrlsl
--gsc----vfdavhpyakakteach--nia-iesldlgdsfawlgmlig
edtsev---ttfklyqt------nnpd---rl--dhhr-----lgkliyi
ag---lhylhd------qrrr--nkaftvplaalhgsp-----phmsgyd
fgt-lrpfal----aav-----fkikh--cegikaalitekeec-s---
>ENV_HV2NZ/24-502
--kmfvqrspiyldqp---gpqkklkltenyse----tass-----ahaa
sgkkamly-k-pk----td-llewrwlihwhglq--aenwh------esi
rnlg-a-saqlnvtggdevtlnlgpkkkidy---------shns----sn
hdewiaskemnwnr-gktnyyrqypntiagkgdrgvlrtdftk-dlnygh
kmf-------kqygqaidgvtmggsiqa-------gd-hhmwltgaidte
a-enyrcvl--r---------hg---ngiqaggah--k------------
psyav-nky-gipdg---l--lv-kgedtrkvpl--ysgvdnspkypyls
nrgdcfnlerssgyapvht------centdmg--aeiasrqakdiqy-l-
patp-------mkllkvgel--aggf-------tta-dedifkvhsslvt
s-vggr---pksapg--dn--gtelsrhpseep------afistaks-if
--pgflftdtmqtihplvnaktapch--gtg-tqaeaqaksfawlels-e
edipqi----nhkly--ralgrwlnsn---ql-------------kfvla
ttpsllhfkhn------qr--qatmafsvgq-klhatptaqlqpylakfe
fgv---------kqggt-----fea-k--cmtikvrmitehdqcreksk
>ENV_SIVV1/24-538
---mfvprspyyldqp---apqksakltdny-----q---s-----aha-
-gkkdvlnaa-pk--fspgtllnwrwm----glm--aeswpdtqqncetf
adp----ksaadv--dddvtise---pkvdy---------csgk----gd
-gewisgkstawhk-akdnyyrqymyvavgknekemfmtp-ikegidygh
kif-------khygraaqkvtlgadskt-------ad-grmwltgdil--
----yrril--r---------qglalgqidvgggq--d------------
cyyviendf-gnpngfell--lvpkgaenqkksl--yikandgpnfpllt
sradifllqrssgyaptna------centq--inagastkpakvldy-iv
tatpagnsrnsmkflqigelggnggf-------ram-dgntykvhpi--t
t-vsgr---vkgklpnh--tggttksahpstqglndfild-----kslvl
--asg------nsth----skaetchtdkvy-vqtlpqpssf--leld-g
ggtgqe---rifrl-----naawnnpk---qlaaehhrdaelefgkfvyv
haaaklhflhd------rr--hasdayaiqqaslhalp-----pqmaqfe
fgifsrpftmynkntavvilldfkl-k--cggikvdlisehdhc-t---
>node7
---mfvprspyyldqp---apqkklklteny-----qtass-----aha-
-gkkdilnaa-pk--fspgtllnwrwm----glm--aeswpdtqqncetf
adpg-q-ksaadv--ddgvtvnv---kkvdy---------cdgk----gd
-dewisgkntawhk-akdnyyrqymyvtvgknekeiymtqftkegidygh
kif-------kqygraaqkvtlgadaqt-------ad-grmwltgsii--
----yrcvl--r---------qglalgaiqaggaq--k------------
cyyvienkf-gipng---l--lvnkgaenrkmsl--yikandgpnfplls
sradcfllqrssgyaptna------centq----aeistkpakdldy-iv
satpaannrnsmkflqigalhanggf-------kat-dgntfkvhpa--t
t-vsgr---vkatppnh--nggttksthpstqalndyildfittakslil
--ass------qsvh----artetch--svy-vqtlaqpssfawleld-g
adigqe---rifrly--rpngawnnpk---qlaaehhrdaelefgkfvyi
haeaklhflhd------rr--hasvafsiqqaslhatp-----phmaqfe
fgifsrpftmynknagv-----fkl-k--cggikvqlitehehc-t---
>node19
--kmfvprsptyldqp---apekklkltenyse----tass-----ahaa
sgkkamln-k-pk--fspg-llewrwl----glq--aenwp------esf
rnlg-t-saqlnvtggdevtlnlgpkkkidy---------chas----gn
-dewiasknmnwnk-gktnyyrqypyntagkgdrgvlrteftk-nlnygh
klf-------kqygqaidgvtmgasiqa-------sd-shmwltgaidte
aienyrcvl--r---------hg---ngiqaggaq--k------------
csymv-nky-gipdg---l--lv-kgednrkvpl--yigvdnspkypyls
srgdcfnlqrssgyapvht------centd----aeiasrqakdiey-mv
patp-------mkllkvgal--aggf-------tta-dedifkvhss--t
t-vggr---pksapp--dklggtelskhpaeep------afistaks-if
--pgflftdtmqtihplvnaktapch--gta-tqaeaqaksfawlels-e
edipqi----nhkly--ralgrwnnsn---ql-------------kfvla
ttpsllhfkhn------qr--qatlafsvgq-klhatptpqlqpyiakfe
fgi---------kqggv-----fea-k--cmtikvrlitdhdqcreksk
>ENV_HV2BE/24-510
--kmfvprsptyldqp---gpekklkltenysd----ta-s-----ahsa
sgkkalln-k-pk--fspg-llewrwl----glq--aenwp------esf
rnlg-t-raqlnvtggdevtlnlgpakkidy---------chas----gk
-dewlasknmnwkk-grpdyyrqypyntagkgdrgvlraeftk-slnygh
klf-------kqygqavdgvtmgasiqa-------sd-tpmwltgaidtd
aienyrcvl--r---------hg---dgiqsggeq--k------------
vsymv-hky-gipdg---l--lv-kgadn--vpl--yigvenspkypyls
sradcfnlqrksgyspvpt------centd----ani-srqakniey-mv
pgtp-------mkllkigal--aggf-------staadedifkvhss--t
t-tagr---pksapp--dklggtelskhpaedp------alistaks-if
--paflftptmqtihpvvnaktapch--ata-sqaeaqaksfawmels-e
edfpqlltv-nhkly--ralgrwnnshhfpql-------------kfvla
ttpsllhfkhe------qr--qatlaisvgq-klhatpspqlqpylakfe
fgi---------kqggv-----fes-kllcmsikvrlitdhdqcreksk
>node10
--kmfvprsptyldqp---apekklkltenyse----tass-----ahaa
sgkkamln-k-pk--fspg-llewrwl----glq--aenwp------esf
rnlg-t-saqlnvtggdevtlnlgpkkkidf---------chas----gn
-dewiasknmnwnk-gktnyyrqypyntagkgdrgvlrteftk-ninygh
klf-------kqygqaidgvtmgasiqa-------sd-shmwltgaidte
aienyrcvl--r---------hg---naiqaggaq--k------------
csymv-nky-glpdg---l--lv-kgadnrkvpl--yigadnspkypyls
srgdcfnlqrssgyapvha------centd----aeiasrqakdiey-mv
patp-------mkllkvgal--aggf-------tta-dedifkvhss--t
t-vggr---pksappkhdklggtelsthpaeep------afittaks-if
--pgflftdtmqtihplvnaktapch--gta-tqaeaqaksfawlels-e
adipqi----nfkly--ralgrwnnsn---ql-------------kfvfa
gtpsllhfkhn------qr--qatlafsvgq-klhatptpqlqpyiakfe
fgi---------kqggv-----fea-k--cmtikvrlitdhdqc-eksk
>ENV_HV2CA/25-512
--kmfvprkptyldqp---gpqkklklvenyse----tass-----ghaa
sgkkamln-k-pk--fspg-lfewrwl----glq--aqnwp------ess
rnlgktftaqlnvtggdevtlnlnpkkkidy---------chas----gn
-dswiasknmnwnr-sktnyyrqypyntegkgdrgilrtdftk-nlnygh
klf-------kqygqdidgvtmgasiq--------ea-shmwtngaidte
aienyrcvl--r---------hg---n-yqaggah--k------------
csymv-----gipdg---f--lv-kgederkvpv--yigvdnspkypyld
srgdcfnlerssgygpvht------cdntd----aeiasrqakdiey-mv
gatp-------mkllkvgal--aggf-------tta-dgeifkvhss--t
t-vggr---p--------------lskhageep------aftgteks-if
--pgflftdtm----plvnaktapch--g-----aeaqaksfawlels-e
edipqs----nhkiy--rasgrwlnsd---ql-------------kfvla
ttpsllhfkhn------qr--qatmafsvgq-klhatptpqlqpyiakfe
fgi---------kqggv-----fgg-k--cltikvhligehdqareksk
>ENV_SIVG1/22-522
---mfvp-kpyyldqphtsapp-rlklteny-----qtass-----aht-
-gkkdilnap-pk--fspgdllswrwm----glm--aeswpdtqqncetf
adpg-q-ksaedv--qngvtvnv---kkvdy---------cdgk----ge
-dewisgkntawhk-akdnyyrhymyvt--knekeiymtqftkegidygh
kif-------nqygraaqkitlgadaqt-------ld-grmwltgtii--
----yrcvl--r---------qglaagaiqaggaq--r------------
cyyviegkf-glpsg---l--lvnkgaenrkmsl--yikandgpnfplls
sradcfllqrssgyastna------cqnsq----aeistkpakdldy-in
satpaaqndnsmkflqfdalhanggf-------kaa-dgntfkvhpa--t
t-vsgr---akatppnh--nggttksthpstqaltdyildfista-----
-----------lsvh----artetch--svy-vqtla----fawleld-g
adigqe---rifrly--rpngawnipk---hlaaehhrdaelefgkfvyi
haeaklhflqd------rr--haspafliqnaslhatp-----phmaqfe
fgifsgpfpmyntnsgv-----fkl-k--cggikvqfitehdhc-t---
>ENV_HV2G1/23-502
--kmfvprsptyldqp---apekklkltenyne----tatsqfvnsahaa
sgkkamln-k-pk--fspg-llewrwl----glq--aenwp------esf
rnlg-t-saqlnvtggdevtlnvgpkkkidy---------chas----gn
-dewiasknmnwnk-gktnyyrqypyntagkgdrgvlrteftk-nlnygh
klf-------kqygqaidgvtmgasiqa-------sd-shmwltgaidte
aienyrcvl--r---------hg---sgieaggaq--k------------
csymv-nky-glrdg---l--lv-kgednrkvpl--yigvenspkypyln
srgdcfnlqrcsgyapvht------cantd----aeiaskqakdiey-mv
p--p-------mtllkvgal--aggfkylgifltta-dedifkvhss--t
t-vggr---pksapp--dklggtdlskhpaeep------afittaks-if
--pgflftdtmqaihplvnaktapch--gnaitqaeaqaksfawlels-e
edipqi----nhkly--ralgrwhnsn---ql-------------kfvla
gtpsllhfkhn------qr--qatlafsvgq-klhatptpqlqpyiakfe
fgi---------kqggi-----fea-k--cmtikvrlitdhdqcrekgk
>ENV_HV2D1/24-501
--kmfvprsptyldqp---gpekklklaenyse----tasg-----ahas
ggkkamln-k-pk--fspg-llewrwl----glq--aenwp------esf
rnl----sgqlnvtggqevslnlgpkkkidy---------chas----gn
-dewiasknmnwdk-gktnyyrqypyntagkgargvlrteftk-nlnygh
klf-------kqygqtidgvtlcasiqa-------sd-s-lwltghidtd
aienyrcvl--r---------hg---ngiqagpaq--k------------
csymv-nky-gipng---l--lv-kgednrkvpl--yigvdgspkypyls
sradcfnlqrssgytpvpt------cenad----aevakrqakdiey-mv
patp-------mkllkvgal--aggf-------ste-dedifkvhss--t
t-vagr---pksapp--dklggtelskhpaeep------afisaakt-if
--pgfliadtlrtihpvvnattapch--gta-tqaeaqakafawlels-e
ddipqi----nhkly--ralgrwnndn---ql-------------kfvla
ttpsllhfkhn------qr--qatlafavgq-klhatpapqlqpytakfe
fgi---------nqggv-----fet-kllcmtikvrlitdhdqcreesk
>ENV_HV2D2/24-513
--kkfvprsptyleep---apekklkltnnyse----taas-----mhaa
sskkalln-kapk--fspg-llewrwl----glqgfaeswp------qsf
rnlg-t-saqlnvtgsddvtlnlgttkevdf---------chas----gn
-dewklpknmnwnkagktdyyrqypyntagkgdrgvlqsefak-ninygh
klf-------kqygqaiqavamgssiqa-------sd-shmwltgavdti
aieeyrcvlcsrallggimkqhg---naiqaggaq--k------------
csymv-nky-glpdg---l--lv-kgagkrkvplhayidennspkypyms
srgacfnlqrtsgyatvha------cedtd----aeissrqgkgiey-mk
pstp-------mrllkvsal--aggf-------ana-dedifrvhss--t
t-vggr---akstppkhdklgdtelsthraeep------lhittaks-if
rhngflftntkqtihplvnaktapch--gaa-tqaeaqaksyawlels-e
adipqi----nfkly--ralgqwnnst---ql-------------kfvfa
gtpslphfkhpdtkchaqs--qatl--svgq-klhssptpqlqpyiakfe
fai---------kqkhl-----fea-k--cmpikvrfitdhkqc-eksk
>node11
--kmfvprsptyldqp---apekklkltenyse----tass-----ahaa
sgkkamln-k-pk--fspg-llewrwl----glq--aenwp------esf
rnlg-t-saqlnvtggdevtlnlgpkkkidy---------chas----gn
-dewiasknmnwnk-gktnyyrqypyntagkgdrgvlrteftk-nlnygh
klf-------kqygqaidgvtmgasiqa-------sd-shmwltgaidte
aienyrcvl--r---------hg---ngiqaggaq--k------------
csymv-nky-glpdg---l--lv-kgednrkvpl--yigvdnspkypyls
srgdcfnlqrssgyapvht------centd----aeiasrqakdiey-mv
patp-------mkllkvgal--aggf-------tta-dedifkvhss--t
t-vggr---pksapp--dklggtelskhpaeep------afistaks-if
--pgflftdtmqtihplvnaktapch--gta-tqaeaqaksfawlels-e
edipqi----nhkly--ralgrwnnsn---ql-------------kfvla
gtpsllhfkhn------qr--qatlafsvgq-klhatptpqlqpyiakfe
fgi---------kqggv-----fea-k--cmtikvrlitdhdqcreksk
>node18
--kmfvprsptyldqp---gpekklkltenyse----tass-----ahaa
sgkkamln-k-pk--fspg-llewrwl----glq--aenwp------esf
rnlg-t-saqlnvtggdevtlnlgpkkkidy---------chas----gn
-dewiasknmnwnk-gktnyyrqypyntagkgdrgvlrteftk-nlnygh
klf-------kqygqaidgvtmgasiqa-------sd-shmwltgaidte
aienyrcvl--r---------hg---ngiqaggaq--k------------
csymv-nky-gipdg---l--lv-kgednrkvpl--yigvdnspkypyls
srgdcfnlqrssgyapvht------centd----aeiasrqakdiey-mv
patp-------mkllkvgal--aggf-------tta-dedifkvhss--t
t-vggr---pksapp--dklggtelskhpaeep------afistaks-if
--pgflftdtmqtihplvnaktapch--gta-tqaeaqaksfawlels-e
edipqi----nhkly--ralgrwnnsn---ql-------------kfvla
ttpsllhfkhn------qr--qatlafsvgq-klhatptpqlqpyiakfe
fgi---------kqggv-----fea-k--cmtikvrlitdhdqcreksk
>node8
---mfvprspyyldqp---apqkklklteny-----qtass-----aha-
-gkkdiln-a-pk--fspgtllnwrwm----glm--aenwpdtqqncesf
adpg-q-ksaanv--ddgvtvnv---kkvdy---------chgk----gd
-dewiagkntnwhk-akdnyyrqysyvtvgkgekeiymtqftkkgidygh
kif-------kqygraaqkvtlgadapt-------ad-armwltgsii--
----yrcvl--r---------qglalgaiqaggaq--k------------
cyyvi-nkf-gipng---l--lvkkgaenrkmsl--yikandgpkfplls
sradcfilqrssgyaptna------cente----aeistkpakdley-iv
satp-------mkflkvgalhaaggf-------kat-ddnifkvhpa--t
t-vggr---vkatppnh--nggttksthpstqa------dfittanslil
--ass----vmqtvhpfieartepch--sva-vqalaqassfawlelt-g
adigqv---rtfrly--rpngawnnpn---qllaehhrdaelefgkfvyi
napallhflhd------qr--hasvafsiqqaslhatp-----phmaqfe
fgi-srpftmynknagv-----fkl-k--cggikvqlitehehc-k---
>node17
--kmfvprsptyldqp---gpqkklkltenyse----tass-----ahaa
sgkkamln-k-pk--fspg-llewrwl----glq--aenwp------esi
rnlg-t-saqlnvtggdevtlnlgpkkkidy---------chas----gn
-dewiasknmnwnr-gktnyyrqypyntagkgdrgvlrteftk-nlnygh
klf-------kqygqaidgvtmgasiqa-------sd-shmwltgaidte
aienyrcvl--r---------hg---ngiqaggah--k------------
csymv-nky-gipdg---l--lv-kgednrkvpl--yigvdnspkypyls
srgdcfnlerssgyapvht------centd----aeiasrqakdiey-mv
patp-------mkllkvgal--aggf-------tta-dedifkvhss--t
t-vggr---pksapp--dnlggtelskhpaeep------afistaks-if
--pgflftdtmqtihplvnaktapch--gta-tqaeaqaksfawlels-e
edipqi----nhkly--ralgrwlnsn---ql-------------kfvla
ttpsllhfkhn------qr--qatmafsvgq-klhatptpqlqpyiakfe
fgi---------kqggv-----fea-k--cmtikvrlitehdqcreksk
