>ENV_HV2CA/25-512
nsqqdkslhiaqit--adkshi------ntatcktkkavkc--wn-hkke
tla-falgi------------gdcellgyeeadi---spksdkalkyav-
--------vtt------sy--knprhgatkyekt-----qstkc--aynh
k-vvakdndqftiaqrmstpeq--ytpe-mtltep-------g-hrrkdk
kddatshhep---itqtsyqnllavga----lrvrrcl----eytavgle
les---cpalmvgvc-fagaytgfam---n---kytm--dvysnccikva
atasikslwyprtaketfkeltanergvsamstnytacse----rqgkf-
----------------------s--------------------gf----p
i--------ghgkkyhefeitalndggefegkgam----kvhtggkr---
---r--e----pls-kc--yaeacvsayqkhn----ggekqmllrhdfvl
kaavtrlagptqekgwn--r--------s-hgvhlqtavqgsttghyrdi
q------lracssa-----------------geg-----ilpsq--phgr
vankr------epaenad-------------akndvte---psigynvds
eghqnhyapwgssct-efnhr--g---gf---irkld----mhshlfvrg
pgtmlsqntstkaaq-----a-tsl--gyfkpete-------vstsapy-
>ENV_SIVV1/24-538
nvtnd---------------ht------dtaacktekttpc--wdck---
--atfglgiqkeissgep--eaekevlgfeksdp---gakkdtqvkfra-
--------vat------ay--khpvngstyyeks-----dskkcvgpynh
k-visnqn-------emptpkq--ynpd-vsysdpsrgth--g-vkqme-
---atphpss---w-------hlvagdnagtlrtvvhm---keypeqqfa
-dsgqdsstgltgqckfggtlaslda---g---g--l--evfisycik--
--wai-clsrcavvaetfra--addpgpra--saykdmnk----rkgky-
-hld-msqtyapitmq----g-tl-atksqgdvlvlgyfvlksaf----p
ikksktrgpcn-----------veegaefedkgsi----rvhkgrkrs--
-iifspe----ets-k------acvdaykthklvedegeaq-----dykv
kgaldrvtgptedkgwntqr--------a-nalylqtpveasratdyrks
g------lnacaaa-----hrksphigekn--dp-----mqdpq--nier
vplkm------egvlegp-------------akeevtaaerpsivysv--
e-----ya-----ct-ifahr--g---gf---vhktd----mhshl----
----ytqhdmaeagk-----e-tplqlgy-kpe--------------py-
>ENV_HV2NZ/24-502
nteankclhiaqit--adkshi------ntatcktkkavkc--wn-hkge
tla-falsi------------gecellgyekadi---spksdkqlkyrv-
--------vtt------sy--knpkhgatkyekt-----qatkc--aynh
k-vvakdndqfti-qrmstpdq--ykpd-mtltep-------g-hrwvdk
kdaaaghhepgisit--ayqnllvvge----lrvrrcl----eytsvqle
les---cpalmvgqc-fagaltgfag---d---kytm--qiysdccikla
ataaisslwypmtaketfkeltadeagvsamstnytaastqnc-regkf-
----------------------sl-tak--------------ggf----p
i--------ghgskyhefeitalneggefegrgam----rvhtggkr---
---r--e----pls-kc--ygetcvsayqkhn----gwektmllrhdfv-
--------gecqekgwn--l--------a-h-vhlqsavdgsitgdykni
t------lracsaa-----------------gpd-----mlpsq--phga
isnkr------epaqyad-------------akddvte---psigynvdn
eghqnhyapwgasct-efnhr--g---gf---ihkidtgkamhshlfark
pgsglsrnsktkagq-----a-tpl--gyfkpete-------vsssapy-
>node8
nvsnd-----------akkpht------dtaacktektvtc--wdckkge
tlavfglgitkeva--ep--egesevlgfeksdi---gpksdkqvkyrv-
--------vat------ay--khptngatyyekt-----dskkcsgpynh
k-vvegqn-------emptpth--ynpd-vtysep-------g-vrridk
ddiatshhap---l----fqihlvvge----lrtvrhl---keyaesqfa
-es---sstgltgqckfggalaafna---g---g--l--evfinycikts
agsai-clsscltaketfre--anepgpraeasayknmnk----rkgry-
-hleatsqtlapitlq----i-tl-atk--------------aaf----p
ikkmktsspcnksky-------vnegaefeekssm----rvhkggkrs--
-ilk--e----els-kckgyseacvraykthk----egdqq-----dyvv
kgaltrvsgasedkgwn--r--------t-hglhlqtpvessrtsdyrkl
g------lnacaaa-----------------tdv-----mqapq--nfer
vtlkm------esveesp-------------akdnvtaaerpsivysv--
eghqfsya-----ca-ifarr--g---gf---ihktn----mhphl----
----ltqnsmaeagq-----e-tplqlgy-kpe--------------py-
>ENV_HV2D2/24-513
ntepn-----------akyshi------dtatckt-kavkc--ws-hkge
tla-falgi------------gdsellgyekadi---spfsdkqlkyrv-
--------vtt------sy--knpkhgatkyvkq-----hstkr--aynh
k-vveknndqfts-qhmstpeq--yypekm---ep-------g-hrrlek
kddatshhep---il--syqkllvvgd----irvircv----dytdtqla
-es---ssalmvgqc-fggvltgfam---d---kytm--evyskccikva
atgaisclwfpmtaketykeltaddagikams---------------kf-
----------------------sl-tak--------------ggf----p
ie-------ghgkkypeflitalnegdefagraak----rvhsgvkr---
---k--e----pls-kc--csdacvsayqk-n----agqkqmllshnfvl
kaavtrlageleekewk--s--------g-hglheetavdgsttgdyrnm
t------lkacsaa-----------------ged-----vlpsq--pfgr
vankr------dpveiad-------------akqdateterpsvaynmes
eghqnnyalwgntct-efahr-gg---gf---ihkvq----mh-hlfsrg
agaglsqna----gq-----a-tgl--gffkpe--------------py-
>node9
nteqa-----------akkshi------ntatcktkkavkc--wd-hkge
tla-falgi------------gesellgyekadi---spksdkqlkyrv-
--------vtt------sy--knpkhgatkyekt-----qstkc--aynh
k-vvekdndqfti-qhmstpeh--ynpd-vtltep-------g-hrrvdk
ndnatshhep---it--syqnllvvge----lrvircl----dytdtqla
-es---ssalmvgqc-fggaltgfam---g---kytm--evysdccikva
ataaisclsfpmtaketfkeltadeagpramstnytagsk----regrf-
----------------------sl-tak--------------ggf----p
ik-------ghgtkyhefqitalnegaefegraam----rvhsggkr---
---k--e----pls-kc--yseacvsayqkhn----egekqmllrhdfvl
kaavtrlageteekgwn--s--------g-hglhlqtpvdgsttgdyrnm
t------lracsaa-----------------ged-----mlpsq--pfgr
vankr------dsaeiad-------------akddvteaerpsiaynves
eghqnnyalwgnsca-efarr--g---gf---ihkid----mhphlfsrg
pgpglsqnskakagq-----a-tpl--gy-kpe--------------py-
>node19
nteqnkclhiaqit--adkshi------ntatcktkkavkc--wn-hkge
tla-falgi------------gesellgyekadi---spksdkqlkyrv-
--------vtt------sy--knpkhgatkyekt-----qstkc--aynh
k-vvakdndqfti-qrmstpeq--ynpd-mtltep-------g-hrrvdk
kddatshhep---it--syqnllvvge----lrvrrcl----eytsvqla
les---csalmvgqc-fagaltgfam---d---kytm--evysnccikva
ataaisslwypmtaketfkeltadeagvsamstnytagse----regkf-
----------------------sl-tak--------------ggf----p
ik-------ghgkkyhefeitalnegsefegrgam----rvhtggkr---
---r--e----pls-kc--yseacvsayqkhn----ggekqmllrhdfvl
kaavtrlagetqekgwn--s--------s-hglhlqtavdgsttgdyrni
t------lracsaa-----------------ged-----mlpsq--pfgr
vankr------epaeiad-------------akddvte---psiaynves
eghqnhyalwgssct-efnhr--g---gf---ihkid----mhshlfarg
pgsglsqnskakagq-----a-tpl--gyfkpeteagnccapvstsapy-
>ENV_SIVM1/24-528
nteqa-----------akkshi------nsatcktkkavkc--wd-hkge
tla-yalgi------------gesnllgyekadi---spksnkqlkyrv-
--------vtt------sy--knpkhgatkyekt-----qstkc--dynh
k-pvekdndqfti-thlstpeh--ydpd-vgldep-------g-hrrvdk
ndeatshhep---it--syqnllvvge----lrvircl----dytdtqla
-es---taallvgqc-fkgaltgfam---geplkytm--evysdccikta
ataaisclefpmtaketfkeltadeaggrsmstnytags-----regrf-
----------------------sl-kak--------------ggf----p
ik-------ghgskyhefqetvlgegaefegraam----rvhsggsr---
---k--e----plt-kc--yseacvsayqkhn----egdkqmllrhdfvl
ksavtrlageteekgwd--s--------g-hgqhlqtpadgtttgdyrnm
t------lracsaa-----------------gee-----mlpsq--pfgr
vankrtywdafdpaqvan-------------skddv-eaerpsiafdves
eghqnn---wgnsca-efarr--g---gf---ihkid----mhphlfsrv
pgpglsqnskasasa-----a-tpl--gy-kpe--------------py-
>node17
nteqnkclhiaqit--adkshi------ntatcktkkavkc--wn-hkge
tla-falgi------------gecellgyekadi---spksdkqlkyrv-
--------vtt------sy--knpkhgatkyekt-----qstkc--aynh
k-vvakdndqfti-qrmstpeq--ykpd-mtltep-------g-hrrvdk
kddatshhep---it--syqnllvvge----lrvrrcl----eytsvqle
les---cpalmvgqc-fagaltgfam---d---kytm--evysnccikva
ataaisslwypmtaketfkeltadeagvsamstnytaase----regkf-
----------------------sl-tak--------------ggf----p
i--------ghgkkyhefeitalneggefegrgam----rvhtggkr---
---r--e----pls-kc--yaeacvsayqkhn----ggekqmllrhdfvl
kaavtrlagetqekgwn--s--------s-hgvhlqtavdgsttgdyrni
t------lracsaa-----------------ged-----mlpsq--phgr
vankr------epaenad-------------akddvte---psiaynvds
eghqnhyapwgssct-efnhr--g---gf---ihkid----mhshlfarg
pgsglsqnsktkagq-----a-tpl--gyfkpete-------vstsapy-
>node18
nteqnkclhiaqit--adkshi------ntatcktkkavkc--wn-hkge
tla-falgi------------gesellgyekadi---spksdkqlkyrv-
--------vtt------sy--knpkhgatkyekt-----qstkc--aynh
k-vvakdndqfti-qrmstpeq--ynpd-mtltep-------g-hrrvdk
kddatshhep---it--syqnllvvge----lrvrrcl----eytsvqle
les---csalmvgqc-fagaltgfam---d---kytm--evysnccikva
ataaisslwypmtaketfkeltadeagvsamstnytagse----regkf-
----------------------sl-tak--------------ggf----p
i--------ghgkkyhefeitalnegsefegrgam----rvhtggkr---
---r--e----pls-kc--yseacvsayqkhn----ggekqmllrhdfvl
kaavtrlagetqekgwn--s--------s-hglhlqtavdgsttgdyrni
t------lracsaa-----------------ged-----mlpsq--pfgr
vankr------epaeiad-------------akddvte---psiaynves
eghqnhyalwgssct-efnhr--g---gf---ihkid----mhshlfarg
pgsglsqnsktkagq-----a-tpl--gyfkpeteagnccapvstsapy-
>node14
nteqnkclhiaqlt--adkshi------ntatcktkkavkc--wn-hkge
tla-falgi------------gesellgyekadi---spksdkqlkyrv-
--------vtt------sy--knpkhgatkyekt-----qstkc--aynh
k-vvakdndqfti-qrmstpeq--ynpd-maltep-------g-hrrvdk
kddatthhep---it--syqnllvvge----lrvrrcl----eytsvqle
les---csalmvgqc-fagaltgfvm---d---kytm--evysnccikva
ataaitslwypmtaketfk---adeagvsamstnytagse----regkf-
----------------------sl-tak--------------ggf----p
i--------ghgkkyhefeitalnegsefegrgam----rvhtggkr---
---q--e----pls-kc--fseacvsayqkhn----ggdkqmllrhdfvl
kapvtrlagetqekgwn--shegaeails-hglhlqtavdgsttgdyrni
t------lracsaa-----------------ged-----mlpsq--pfgr
vankr------epaeiad-------------tkddvte---psiaynves
eghqnhfalwgssct-efnhr--g---gf---ihkid----mhshlfsrg
pgsglsqngktkagq-----a-tal--gyfkpeteagnccapvstsapy-
>node7
nvtnd-----------akkpht------dtaacktektvpc--wdcksge
thavfglgitkeva--ep--egesevlgfeksdi---gpkkdtqvkyra-
--------vat------ay--khptngstyyeks-----dskkctgpynh
k-vvssqn-------emptptq--ynpd-vtysep-------g-vrrler
ddiatshhsp---l-------hlvage----lrtvrhm---keypesqfa
-es---sstgltgqckfggtlaafna---g---g--l--evfinycik--
--wai-clsscltiaetfre--anepgpraeasayknmnk----rkgry-
-hle-tsqtyapitlq----v-tl-atk--------------aaf----p
ikkmktsspcnksky-------vdegaefedkssm----rvhkgrkrs--
-ilk--e----els-kckgysnacvdaykthk----egdaq-----dyvv
kgaltrvtgptedkgwn--r--------t-nalhlqtpveasrasnyrkm
g------lnacaaa-----------------tdp-----mqapq--nfer
vtlkm------esveegp-------------akdnvtaaerpsivysv--
e-----ya-----ca-ifarr--g---gf---ihktn----mhphl----
----ltqnamaeagq-----e-tplqlgy-kpe--------------py-
>ENV_HV2G1/23-502
nteqnkclhiaqit--adkshiyqkaqcntatcntkkavkcevwn-hkge
tla-falgi------------gesellgyekadi---stksdkqlkyrv-
--------vtt------sy--knpkhgatkyekt-----qstkc--aynh
k-viakdndqfti-qrmstpeq--ynpd-mtltep-------g-hrrvdk
kddatyhhqs---it--syqnllvvge----lrvircl----dytsvqla
les---csalmtgqc-fggaltgfam---d---kvtm--evysnccikva
ataaidslwypmtaketfkeltaddagvsamstnytagse----regkf-
----------------------sl-tak--------------gnf----p
ik-------khgkkyhefevtalnegsefegrgalaylyrvhtggkr---
---r--e----pls-kc--yseacvsayqkhn----gpekqmllrhdfvl
kaavtrlaeetsekgwn--s--------g-hglhlqtavdgdttgdyrni
e------lracsaa----------------cgsd-----mlpsq--pfgr
vankr------epaeiad-------------akddvte---psiaynves
eghqnhysqwgssct-efnhk--g---gf---ihrid----mhghlfarg
pgsglsqysaaqagq-----a-tal--gyfkpeteagncctpvstsapy-
>ENV_HV2D1/24-501
nteqskclhitqlt--adkshi------ntatcktkkavkc--wn-hkge
tla-yalgi------------gesellgyekadi---spksnkqlkyrv-
--------vtt------sy--knskhgatkyekt-----qstnc--aynh
k-vvakdndqfti-qrfstpeq--ynpd-maltep-------g-hrrvdk
kddanthhep---it--syqnllvvge----lrvrqcl----eytsvqle
les---csalmvgqc-fagaltgfvm---d---kytm--evy--------
--aaitsiwypmtatetfk---adeagvsalatnytagse----regkf-
----------------------sl-tak--------------ggf----p
i--------ghgkkyhefeitalnegsefegrgam----rvhtggkr---
---q--d----pls-kc--fseacvsayqkhn----ggdkqmllrhdfvl
kapvtrlagetqekgwh--shegaesilsqhglhlqtavdgsttgdyrni
t------lracgaa-----------------geevagdhmlssq--pfgr
vankr------epaeiad-------------tkddvte---psiaynves
eghqehfalwgssct-efnhr--g---gl---ihkie----mhshlfsrg
pgvglsqkaktkagq-----s-tal--gyfkpeseagnccapastsepy-
>ENV_HV2BE/24-510
nteqnk-lhiaqlt--adkshi------ntatcktkkavkc--wn-hkgq
tls-falgi------------gesellgyekadi---spksdsqikyrv-
--------vtt------sy--knpkhgatkyekt-----qsnkc--ayng
a-vvakdndqftl-qrmstpeq--ynpd-maltdp-------g-hrrvdk
kddatthhep---it--syqnllvvge----lrvrkcl----eytsvqle
lqs---csaltvgqc-fpgaltgfvm---d---kytmraevysncclkvg
ttasitslwypmtaretfk---adeagvsalsanytagse----regkf-
----------------------sllgak--------------ggf----p
i--------ghgkkyhe-eitalnegsefkgrgam----rvhtggkr---
---q--e----pls-kc--fseacvsayqkhn----ggekqmllrhdfvl
kkpvtrlaagnqekgwn--shegaeails-hglhlqtavngsttgdyrsv
s------lracaaakqiag------------ged-----mlpsq--pfgr
vankr------epaeiad-------------ttddvte---qsiaynves
eghqnhfalwsssct-efnha--g---gf---ihkid----mhshlfsrg
pgsglaqngktkagqpeslga-tal--gyfkpeteagn--apvmtsapy-
>ENV_SIVGB/47-569
dvrnq---------kapkkpsf------deeictnkkvlic--wkck---
-------gikkevn--epiaee--p-lafqrsdkhfidpstktq-rykvg
kdkahelavgmrmlivtgymnk-pakgvtyyqqsethek-----ngpyeh
kcvtrcqg-------dmptkaqyqyttd-v--sep-------gevrkidk
eavatdqelp---l----fqirfihgk----irtvrkfykergctegrla
-es---astglekqcrfkealaafnfeacg---g--l--evlkpfctkvg
vgssk-cttgvltkidnfkk--asepgpr--apayhdm-k---arkgvld
spltvk--tlaaptlaskcdi-rm-ass--------------gdfltrmp
ikkk-----cgtkky-------vkean-----dal----rvfkgc-rsqw
cilr--dflcaeychkcgayseacv-s--nhr----egatn-----eyvv
kgnlsklsgkpavkgwn--h--------p-iglhv----mltr-------
gvntvtqldsysas-----------------tev-----mqvpvegafer
vctkm------enlreapngfddllpagtdn-kedigpgehatflfsv--
agnq-ean-----avalfetrl-geqagfsikiqqtn----itpql----
----lpqlqmaqagr-----eqqpvq----lqe--------------ayf
>node10
nteqn-----------akkshi------ntatcktkkavkc--wn-hkge
tla-falgi------------gesellgyekadi---spksdkqlkyrv-
--------vtt------sy--knpkhgatkyekt-----qstkc--aynh
k-vvekdndqfti-qhmstpeh--ynpd-mtltep-------g-hrrvdk
kddatshhep---it--syqnllvvge----lrvircl----dytdtqla
-es---ssalmvgqc-fggaltgfam---d---kytm--evysnccikva
ataaisclwfpmtaketfkeltadeagvsamstnytagse----regkf-
----------------------sl-tak--------------ggf----p
ik-------ghgkkyhefeitalnegsefegraam----rvhsggkr---
---k--e----pls-kc--yseacvsayqkhn----ggekqmllrhdfvl
kaavtrlagetqekgwn--s--------g-hglhlqtavdgsttgdyrnm
t------lracsaa-----------------ged-----mlpsq--pfgr
vankr------dpaeiad-------------akddvteaerpsiaynves
eghqnnyalwgnsct-efahr--g---gf---ihkid----mhshlfarg
pgsglsqnskakagq-----a-tpl--gyfkpe--------------py-
>ENV_SIVG1/22-522
nvtnd-----------akkppt------dtaackteatvpc--wdcksge
thavfglgitkeva--ep--egqsevlafqksdi---gpkkdtqvkyra-
--------vat------ay--khptngktyyeks-----dtkkctgpynh
k-vvssqn-------emptptq--ynpd-vsysep-----srg-vrrler
ddvatshnsp---l-------qlvage----lrtvrhq---keypesqfa
-em---sstgltgqckfggtlaafna---g---g--l--evfinycik--
--wai-clssclti--tfrk--andpgpraepsayknmnk----rkgry-
-hle-tsqayapitlq----vatl-atk--------------aaf----p
ikklktsspcnksky-------vgegaefedkssm----rvhkgrkrs--
-ilt--e----els-kikgysnacmdaykthk----egdae-----dyvv
kgaltrvtgptedkgwn--r--------t-nalhlqtpve---asnyrkm
g------lnacaaa-----------------idp-----mqapq--nfer
atlrm------esieegp-------------akdnvtaaerhsivyav--
e-----ya-----ca-ifarr--g---gf---ihkth----vhphl----
----ltqnampeagq-----q-tplqlgy-kpe--------------py-
>node11
nteqnkclhiaqit--adkshi------ntatcktkkavkc--wn-hkge
tla-falgi------------gesellgyekadi---spksdkqlkyrv-
--------vtt------sy--knpkhgatkyekt-----qstkc--aynh
k-vvakdndqfti-qrmstpeq--ynpd-mtltep-------g-hrrvdk
kddatshhep---it--syqnllvvge----lrvircl----dytsvqla
les---csalmvgqc-fggaltgfam---d---kytm--evysnccikva
ataaisslwypmtaketfkeltadeagvsamstnytagse----regkf-
----------------------sl-tak--------------ggf----p
ik-------ghgkkyhefeitalnegsefegrgam----rvhtggkr---
---r--e----pls-kc--yseacvsayqkhn----ggekqmllrhdfvl
kaavtrlagetqekgwn--s--------g-hglhlqtavdgsttgdyrni
t------lracsaa-----------------ged-----mlpsq--pfgr
vankr------epaeiad-------------akddvte---psiaynves
eghqnhyalwgssct-efnhr--g---gf---ihkid----mhshlfarg
pgsglsqnskakagq-----a-tpl--gyfkpeteagnccapvstsapy-
