>node10
iagspgldtkeqi--skr----hppqtttintwahgtshadn--rahga-
lcqtggv---k---nlgiflqseghffnlltryaltidqlkeglaqea--
pkleg---sktmesqvag--gcgpirlpvwghds----nhawlsiggsph
vgdslgarl--gawcardwtkctvna------rltvs----qvresfngd
k-----vartfmrllk--sdlrcyypklqflg--d----cpsp-------
-----pthqd--f-ysttekgeaspfrrdkkencmlvfpgkddfrtgewe
epagdsfrvvvllal----k-hdgs----gc-vtstggcqivv--hetak
yevgkts------cl-lkelav---efd---naidgk-daghkfen----
-aqd-----m-drtidksidrylf-----acpgcaakiggad-ngdgcvc
wgvtslvir----etk---gg----krk-kgr-skvdskne--vdvlaac
rqipkpywis--vagedspmlaea-dkgae--------ycgqr-------
----mmtdgkvikcrt-cy-eiifsniphthgcgdfki---dmp--sels
vgekfae------dsplk-------ptfs---c-iefplhyhksanpaev
qlsnkvt-slgt---------l----a-ktpgp---v
>ENV_HV2D1/24-501
iagsagldtkeqv--skr----hppqtitintwahgtshann--khhga-
lcesggv---k---nlaiflqkeghffnlltrysltieqlkeglaqea--
pkldg---sksmdsqvag--gcgpirlpvwghds----nhawlsigggph
vgdslgarl--gawcardwtkctvna----h-kltvs----qvresfnga
k-----vartfmrlsk--adlrcyypklqflg--d----cdsp-------
-----pthqe--f-ygttekaeaspfrrekkensllvfp----frtgewe
epaaqsfrvvvllal----k-hpgs----gc-vtstggcqkvv--hetak
ysvgkts------cl-lkvlav---efd---naidgk-daghkfed----
-aqd-----m-ertidksmdrylf-----acpgcaakiggad-ngdgcvc
wgmttlvir----etk---gg----nrktkgk-srvdskne--vdvlaac
rqvpkpfwis--aagedtpmlaea-dkgla--------ycgqr-------
----mmtegkvikcrt-cy-----saiphthgcgdfki---dti--selt
vgekfae------esplk-------ptfs---ckief----rksanpmav
qlsnkit-slgt---------l----a-napdp---v
>node19
iagspgldtkeqi--skr----hppqtttintwahgtshadn--rnhga-
lcqsggv---k---nlgiflqseghffnlltryaltidqlkeglaqea--
pkleg---sktmesqvag--gcgpirlpvwghds----nhawlsiggsph
vgdslgarl--gawcardwtkctvna------rltvs----qvresfngd
k-----vartfmrllk--sdlrcyypklqflg--d----cpsp-------
-----pthqd--f-ysttekgeaspfrrdkkensmlvfpgkedfrtgewe
epagdsfrvvvllal----k-hdgs----gc-vtstggcqvvv--hetak
yevgkts------cl-lkelav---efd---naidgk-daghkfen----
-aqd-----m-drtidksidrylf-----acpgcaakiggad-ngdgcvc
wgvtslvir----etk---gg----krk-kgr-srvdskne--vdvlaac
rqipkpywis--vagedspmlaea-dkgaa--------ycgqr-------
----mmtdgkvikcrt-cy-eiifsniphthgcgdfki---dmp--sels
vgekfae------esplk-------ptfs---ckiefllhyhksanpaev
qlsnkvt-slgt---------l----a-ktpgp---v
>node14
iagspgldtkeqi--skr----hppqtttintwahgtshann--knhga-
lcqsggv---k---nlgiflqseghffnlltryaltidqlkeglaqea--
pkldg---sksmdsqvag--gcgpirlpvwghds----nhawlsiggsph
vgdslgarl--gawcardwtkctvna------rltvs----qvresfngd
k-----vartfmrlsk--sdlrcyypklqflg--d----cnsp-------
-----pthqd--f-ysttekaeaspfrrnkkensmlvfpgkedfrtgewe
epagdsfrvvvllal----k-hpgs----gc-vtstggcqvvv--hetak
yevgkts------cl-lkelav---efd---naidgk-daghkfen----
-aqd-----m-ertidksidrylf-----acpgcaakiggad-ngdgcvc
wgmtslvir----etk---gg----nrk-kgr-srvdskne--vdvlaac
rqipkpywis--vagedtpmlaea-dkgla--------ycgqr-------
----mmtdgkvikcrt-cy-eiifsniphthgcgdfki---dmp--sels
vgekfae------esplk-------ptfs---ckief----hksanpaev
qlsnkvt-slgt---------l----a-ntpdp---v
>ENV_SIVV1/24-538
iahapgygekqhl--gkr----hlgqatthkawkqgtshlhn--rah---
----ggl---v---nltiflpsagdfftlltkyilk--klcggieqqvp-
---sggappkgveclvlecsns--metsgweaks----eqswltiegsqh
versllnll--gawcekdwtdckasg-----grlpvs----svreciked
k-----vartyiallr------cyypkqqflgagnnplvctkpg------
--lweagdtd--f-yvstekggdnafradkkqncfllflakeefqsgewa
nsnmgsfgttvtisl----k-hddt----ac-at------ivv--hevsk
ivvskta------sltlktlav---efd---kaideqdegghktldagqh
-phd----li-s---gpttnryvfhnslqacaasagklgdag-vsqgclc
rglaalrpr----krkaqvg-----lrs-kgrdpkieakdnsevdvltsc
rem--sywvnhgvgggd-pvlteghdkgyikqgmshidfcgqr-------
----lmsngsvircrs-cs-gaagkktpqtgacgdfk-----mn--vfls
vggqypqkiagcsdsplk-------stfsrqgc-iefplhyh---nhanl
ql----tkglga---------l----s-ratgpdlev
>node18
iagspgldtkeqi--skr----hppqtttintwahgtshadn--rnhga-
lcqsggv---k---nlgiflqseghffnlltryaltidqlkeglaqea--
pkldg---sktmesqvag--gcgpirlpvwghds----nhawlsiggsph
vgdslgarl--gawcardwtkctvna------rltvs----qvresfngd
k-----vartfmrlmk--sdlrcyypklqflg--d----cnsp-------
-----pthqd--f-ysttekgeaspfrrdkkensmlvfpgkedfrtgewe
epagdsfrvvvllal----k-hpgs----gc-vtstggcqvvv--hetak
yevgkts------cl-lkelav---efd---naidgk-daghkfen----
-aqd-----m-drtidksidrylf-----acpgcaakiggad-ngdgcvc
wgvtslvir----etk---gg----krk-kgr-srvdskne--vdvlaac
rqipkpywis--vagedspmlaea-dkgaa--------ycgqr-------
----mmtdgkvikcrt-cy-eiifsniphthgcgdfki---dmp--sels
vgekfae------esplk-------ptfs---ckiefllhyhksanpaev
qlsnkvt-slgt---------l----a-ktpgp---v
>ENV_SIVGB/47-569
sgessafstkahp--strntfshlnpaskip----------p--kaydr-
lcqkasgakkptpknliiflpsagsyfalltn-------lkghiaeknpy
a----caes-----lvlhansng-------egks----dpawlsvgptkh
sge-----l--atwcerewgkckaen-----nk-lvaavkkeqrtkim--
rkptda----iiavlr--------ygkqdylga-------qraggmtkql
iilkasahsdyef-fataqkgsqd-----------ll-pgnhefkrgery
spk--------------lcking-e----ac-at------s---------
---grtgttssctcltfkavavfkrdfrgqkkditdqsdggnvyletgqn
lpgn----lm-t---gpand--afqsdck---gaepkldaka-agnvcva
rsl----rrgqankkk---d-syta------------tkaqiegdllamc
wmm--pywve--vaggdn---le-------------snfcgf--------
----lmgnrgvitcwarss-dvagkllpavglcddnk-----mnna----
aaakfpe------edpfk-------iqytaqgc-khyp---------aav
dl----srslesshiidrypfnrffgnssadgg---a
>ENV_HV2CA/25-512
iagnpgldtkgqi--skr----hppgqttiktwaqgtshadnenrnhgas
-cqsggv---k---nlgiflqseghyfnlltmyaltidqlksglaqea--
gkldg---skvmesqvag--gcgpirlpvwphdsdqaknhawlsicga-h
vgdnlgarl---awcarkwtkctvda------rltvs----qkresyngd
k-----vartfm-lmkglsdlrcyypklqflg--d----cnsp-------
-----pthqd--fhystsnkgeaspfrrdkkensmlvfpgkedfrtgewe
esaadsfrvivllal----k-hvgs----gt-vtst---qvvv--hetak
yevgkts------cl-lkelav---efd---naiknk-kaghkfmn----
-aqd-----m-drtidraidryly-----acpgcpakiggad-ngd-cvc
wgvtslvir----etk---ge----krk-kgr-srvdsk--------aac
kqipkpywis--vagedspmlaea-dkgaa--------ycgqr-------
----mmtdgkvikcrt-cyteiifsnivqthgcgdfri---dmp--sels
vgekfte------esplkgvlwatepyft---ckiefllhyhksanpaev
alsnkvt-slgt---------l----a-rtagp---v
>ENV_HV2G1/23-502
iagspglatkeqi--skr----hppqtttintwahgtghaan--rnhga-
lchsggv---k---dlgiflqseghffnllvrhaltidqlkeglaqet--
pkleg---sktmesqvag--gcgpirmpvwghds----nhawlsiagsph
vgdslgarl--aawcargwtkcavna------rltvs----rvresfngd
k-----vartfmrllk--sdlrcyypklqflg--d----casa-------
-----pthqd--f-astaekgeaspfrrdkkenamlvfpgkedfrtgewe
epagdsfrvvvllsl----k-hdss----gc-vtstggc--vv--hetak
yevgkts------cl-lkelav---efd---naidgk-naehkfen----
-aqd-----midrtidtsidrylf-----ac--caskiggad-ngdgcvc
wgvaslvir----etk---gg----krk-agr-srldskne--vdvlasc
rqihrpywis--vagedspmlaea-dkgaa--------ycgqr-------
----mmadgkvikcrt-cy-eiifsniphthgcgdfki---dmp--sels
vgekfae------esplk-------ptfs---ckiefllhshknanpaev
qlsnkvt-stgt---------l----a-ktpgp---v
>node7
iaqspgydekqhi--skr----hlgqatsvkawkqgtshlhn--rahta-
lcqnggl---l---nltiflpsagnfftlltkytlk--klkggieqetpy
asfpgcaapkameclvlectns--mstpgwgnks----dqawltiegsqh
vehsllnll--gawcdkdwtkckapg-----grlsvs----svresikgd
k-----vartfiallr------cyypkqqflgagnhplvcakpg------
--lwepgqtd--f-yvttekgpdsafradkkencfllfpgkqefrsgewa
nseggsfratvaislqgeck-hsds----ac-at------ivv--hevak
ivvgkta------sltlktvav---efe---kaideqqegghkiidagqn
-phd----lm-t---gpttdryvfhnslqacagsaaklgdag-askgclc
rglaalrrr----krk---g-----lrs-kgr-pkieardndevdvlatc
rem--pywvsqgvgggenptlaeahdkgyikqgmshidfcgqr-------
----lmsngsvikcrs-cs-evagkkaphtgacgdfk-----mn--vfls
vgekyqq------dsplk-------ptfsrqgc-iefplhyh---nhaav
ql----tkslgs---------l----s-kangp---v
>ENV_SIVG1/22-522
iaqspgydekqhi--skr----hlgqatsvk----gashlhn--rahaa-
lcqnggf---l---nlsiflpsagnfftlltkytlk--kkkggfeqetpy
csfpgcaapkameclvlesang--mrtpgwgnks----dqawltiegsqh
aehsllnll--gawcdkdwtkck-pg-----gqlngs----svresikgd
k-----vartyiallr------syypkkqflgagnhagvcanpg------
--lwepgqtd--f-yvstnkgpdsafradkkencfllfqgkqqfrsgewa
nnengsfratvaislqgeck-hsds----ac-at------ivv--hevtk
ivvgkia------sltlktvav---efe---kaidqqqqgghkiidagqn
-phdphyklm-t---gptqdryvfhdslqac-gsaaklgdag-askgclc
rg------------rk---g-----lrs-kgr-pkievrdndevdvlatc
rem--pywvsqgvgggenstlaeahdkgyikegmshidfcgqr-------
----lmsdgsvikcrs-cs-evagkkaphtgacgdfk-----ln--vfls
vgekyqq------nsplk-------ptfsrdgc-iefplhyh---nhaal
ql----tkalgs---------l----s-kgngp---s
>ENV_HV2BE/24-510
iags--ldtkeqv--skr----hppqtttintwahgtshann--knhga-
lcqsggv---k---nlgvflqseghffnlltryaltidqlkeglaqea--
pkldg---sksmdsqvag--gcgpirfpvwghds----nhywlsvggsph
vgdslgarl--gawcarewtkctvna------rltvs----qvrevfngd
k-----vartfmrlsk--sdhrcyyeklqflg--d----cnkp-------
-----pthqd--f-ysttekaeaspfhrnkkensmlvfpgkedfrtgewq
epqgdafhvvillal----k-hpps----gc-vkstggcnvva--rettk
yevgkts------cl-lkefav---efd---naidvk-dagdkfeq----
-akd-----m-ertidlsidrylf-----actgcaakiggad-nadgcvc
wgmtslvvr----etk---ge----nrk-kgr-skvdskne--vdvlaac
rqipkpywis--vagedtpmlaea-dkgla--------ycgqr-------
----mmkdgkvikcrs-cy-eiifsniphthgcgdyki---nmp--sels
ygdkfae------esplk-------ptfs---ckief----hkpanpksv
emsnkvt-slgt---------l----a-ntpdp---v
>node11
iagspgldtkeqi--skr----hppqtttintwahgtshadn--rnhga-
lcqsggv---k---nlgiflqseghffnlltryaltidqlkeglaqea--
pkleg---sktmesqvag--gcgpirlpvwghds----nhawlsiggsph
vgdslgarl--gawcardwtkctvna------rltvs----qvresfngd
k-----vartfmrllk--sdlrcyypklqflg--d----cpsp-------
-----pthqd--f-ysttekgeaspfrrdkkensmlvfpgkedfrtgewe
epagdsfrvvvllal----k-hdgs----gc-vtstggcqivv--hetak
yevgkts------cl-lkelav---efd---naidgk-daghkfen----
-aqd-----m-drtidksidrylf-----acpgcaakiggad-ngdgcvc
wgvtslvir----etk---gg----krk-kgr-srvdskne--vdvlaac
rqipkpywis--vagedspmlaea-dkgaa--------ycgqr-------
----mmtdgkvikcrt-cy-eiifsniphthgcgdfki---dmp--sels
vgekfae------esplk-------ptfs---ckiefllhyhksanpaev
qlsnkvt-slgt---------l----a-ktpgp---v
>ENV_HV2D2/24-513
iagspglntkeqi--skr----nalgtttiptwahgtvhtdn--rehga-
lcqtgnv---k---nlgiflqseghffdlmtryalkidqikeglaqqa--
lkleg---aktmesqiag--gcg--rlpvwghds-----hawlsiggaph
vgetlgskl--gawcsrdwdkcktna------rvtvs----qvrdsfngd
k-----vartfvrllk--seprcyypkfqflg--d----cpvp-------
-----pthqd--f-ysttekgeaspfkrdkkencmlvfpgkddfrtgewe
epagdsfravvllal----k-hdgs----gc-vtstggcqivaghhetak
yevgkts------cl-lkekav---efd---naidgr-dagrkfed----
-aqd-----m-qrtvaksdekylf-----gcpgcpvkiggad-kgdgcvc
wgvtnlvir----ekk---gg----kak-kgr-skvdskne--i-vlgac
rdipkpywis--vagedspmlaaa-dkgge--------ycgqrivygyrv
qsrlmmtdgkvikcrt-cy-eiv-snipqthgcggfkilsddlp--sels
vgekyae------dsplk-------ptfs---c-vdfplhyhksanpsev
qlsnkva-slgt---------l----a-kapgp---v
>node8
iaqspgfdtkqht--skr----hlgqatsvnawghgtshlhn--rahga-
lcqnggl---l---nltiflpsagsfftlltkytlk--klkggiaqetpy
aklpgcaapkameclvlecknsgpmstpawgnks----dqawlsiggsqh
vghsllnll--gawcdkdwtkckapa-----grlsvs----evresikgd
k-----vartfiallr------cyypkqqflgagdhplmcakpg------
--lwepahtd--f-yattekggdsafradkkencfllfpgkqefrsgewa
npaggsfratvtislqgeck-hnds----ac-at------ivv--hevak
iavgkta------cltlkavav---efe---kaideqqegghkfidagqn
-pqd----lm-t---gpttdryvfhnslqacagsaaklgdag-askgcvc
rglaalrrr----krk---g-----lrs-kgr-pkieardedevdvlatc
rem--pywvs--vaggdnptlaeaqdkgsmkqgmshinfcgqr-------
----lmsnggvikcrt-cs-evigkkaphtgacgdfk-----mn--vfls
vgekyqq------dsplk-------ptfsrqgc-iefplhyh---shaav
ql----tkslgs---------l----s-kangp---v
>node17
iagspgldtkeqi--skr----hppqtttintwahgtshadn--rnhgas
lcqsggv---k---nlgiflqseghffnlltryaltidqlkeglaqea--
pkldg---sktmesqvag--gcgpirlpvwghds----nhawlsiggs-h
vgdslgarlvegawcardwtkctvna------rltvs----qvresfngd
k-----vartfmrlmkvasdlrcyypklqflg--d----cnsp-------
-----pthqd--f-ysttekgeaspfrrdkkensmlvfpgkedfrtgewe
esaadsfrvvvllal----k-hpgs----gc-vtstggcqvvv--hetak
yevgkts------cl-lkelav---efd---naidgk-daghkfmn----
-aqd-----m-drtidksidrylf-----acpgcaakiggad-ngdgcvc
wgvtslvir----etk---gg----krk-kgr-srvdsk--------aac
rqipkpywis--vagedspmlaea-dkgaa--------ycgqr-------
----mmtdgkvikcrt-cy-eiifsnivhthgcgdfki---dmp--sels
vgekfae------esplk-------ptft---ckiefllhyhksanpaev
qlsnkvt-slgt---------l----a-ktpgp---v
>node9
iakspgldtkeqi--skr----hppqtttintwghgtshahn--rahga-
lcqtggv---k---nlgiflqseghfftlltryalk--rlkeglaqea--
akleg---sktmesqvlg--gcgpirlpvwghds----dqawlsiggsph
vgdslgall--gawcardwskctvna------rltvs----qvresingd
k-----vartfmrllk--sdlrcyypklqflg--d----cpsp-------
-----pthqd--f-ysttekgeaspfrrdkkencmlvfpgkhdfrtgewe
kpagdsfrvvvllsl----k-hdes----gc-vt------ivv--hetak
yevgkts------cl-lkelav---efd---naidgk-daghkfnn----
-aqd-----m-d---dksidrylf-----acagcaaklgdad-ngngcvc
wgvdslvir----etk---gg----krk-kgr-skvdskne--vdvlaac
rqipkpywis--vagedspmlaea-dkgae--------ycgqr-------
----lmtdgkvikcrt-cy-eiifsniphtngcgdfki---dms--sels
vgekfae------dsplk-------ptfs---c-iefplhyhks-npaev
qlsnkvt-slgt---------l----a-kapgp---v
>ENV_SIVM1/24-528
iakkpgmdakeqi--skr----hppqtttintwghgaaytnh--rahga-
fcqsggv---k---nlgiflqseghfftlltkyalr--rskeglaqea--
dklqg---sktmesqalg--gcepirlpvwgqds----dqawlsiggsph
vgdslgall--gawcardwskctvna------kltvs----qvresidgd
k-----vartimrllk--sdlrcyypklqflg--d----cpsp-------
-----pthqe--f-ysttkkgeaspfrrdkkencmlvfpgkhdfktgewe
kpagdsfqvvvllsl----k-hdes----gc-vt------ivv--hetak
yevgkts------cl-lkelav---efd---taidgn-daghkfnd----
-dqd-----m-d---drsidrylf-----acagcaaklgdadgngnscvc
wgvdslvir----etk---gg----krk-kgr-skvdsqne--vdvlaac
rqipkaywis--vagedspmlaea-dkgad--------ycgqr-------
----lmtdgkvikcrt-cy-eilisniphtqgcgdfkv---dms--aels
vgekfae------dsplk-------ptfs---c-iefplhyhk-------
----kvt-slat---------l----t-kapgp---v
>ENV_HV2NZ/24-502
iagspgldtmeqielsns----dppqtttistwahgtshadn--rnhgas
lcnsggv---k---nlgvflqsegnffslltryaltidmlkegltqda--
pkfdg---sktmesqvag--gcgpfrlpvwghds----nhawlsiggs-h
vgeslgarlvqgawcarewtkctvnallnr--rltvs----lvresfngd
y-----varsfmrlmkvasdlrcyypklqflg--d----cnsp-------
-----pteqd--f-ysttdkgeaspfrrdkkvnsmvlfpgkddfrtgewe
esaadsfrvivllsl----k-hpgsggttgcsvtskascqvvt--hetak
yivgkts------cl-lselav---efd---ntidgk-daghkfmn----
-aqd-----m-drtidrsldr----------pgcaakiggad-ngdgcvc
wnvtslvir----etk---gg----krd-kgr-sivdtk--------pac
r---kpywin--iapddspmlaea-dkgaa--------ycgqr-------
----vltdgkvvkcrt-cy-eiifsnivhthgcgdfki---dlp--sela
vgekfae------esplk-------ptft---ckiefllhyhksgnpaev
qlsnkvt-tlgt---------l----a-ktpgp---v
