>node13
glclgsi-la--ylndl----ksvkyphngfef-t---pmti---fgcss
-lrkpipegagqkkrwac--sgcvflvekf--vlftkivhltwavelakp
la--vvnivas--tikkmhnvgaamkilk--snrtlg--ilslgv-----
-lsl-sstlktgag----l--pftcns-----aicen---gkp-hgl---
s-----rpgqmlk---vkrdehk-----y----assqgyedf-p---psc
f--f-----qefahvv-gleeldpvil-----kg--ilqllpavcfel-v
klf-navntrq-----ylfenhg-gl-g--------------altd---t
daygti-------h---vdrtykmqnevi--------a-------gmefk
rapniclsly--c-ls--------flyrgfnagngr---------dly--
gllphilhackslalhmg---ivaasa-ikgltpa-igyvllkk----ng
eikv------qed--------------kc-------e--s----k--y--
khqv-esyhtk-----pyfl-ny--gavp-rk---------cdaaseesr
ye-hklplgrikhg-egf-flgavagvtk-khtysaspvnklkaativsa
kfaaqvdclepvgh--pkpt--flltva------dl--apdp--ll--pf
d-----ggg---tsqvtrmpl-l--lly--------khtkv-------qv
qvtk------------hfasyai-ck-efyr--g---vv----gkeql
>A
dlaltpsgmv--fltqlekkiggvdceiedfvlfi---swtn---sccis
-l---vpp---rknrwvg--lpvvltvtafitnygptivfskweivlsgp
lt--lstli-----lglfikl--vakplr--vkasii--iagvdpskshc
alhl-srglkpgla----k--pfagrdgdptgvlmhk---gkpdyal---
g-----adgelsl---mk---cgigacpg---------fe-fdsgtapsc
s--f-----sssga------------p-----nv--lrmllaa----lvh
kla-kalhdkd-----hlfayfa-ld-ewlensvkatd----dfgt---v
ad--ri-------ylsqasqgcksfirte--------l-------gah--
qapmscleiy-ic-leyvs-vmr-vqyrayq--laa---------afy--
wi-----skvhamnlggpqyalvgvys-lkktntekl----iqq-----v
plly------vdv--------------qc-------l--y----qg-tle
qqgq-er--kt-----tfspdci--dgdter---t----ravssgtsahh
gd-qq--------p-nelsfrdstsplmn-eghgnvkstagyta-skvgg
qfghgkdclptsenhfaipl--fllklt-f-iqgvvvqhqlaawlf--in
e-----ggk---kqalcrlai-lgvvhy-----v-lngsts-------hv
dpkrdhhftkqaggpyqfeakvg--t-effldvg---tsaivygtsps
>node15
tlclgpvcla--ylgql----gpvkcgdkgfgf-p---swti---yacst
-vnr-ipkevvrhlrwvc--fhcvfvvkkf--vyfaklvydtwginlgap
la--vtnligp--tigtmriigrahkglk--vtrafa--vlslgv-----
-lal-dralksgag----l--pftgks-----vfchn---gtp-ael---
g-----gkgeklk---vn---he-----y---------yedf-p---psc
y--f-----qdfehal-glnel----t-----ng--vkqllathcfkltv
nlk-kalhtke-----ylfenfg-ml-d---rgliatt----elad---i
tn--ri-------p---veheckrffrvv--------l-------gmhik
haaaiclaly--c-lvsle-pgv-mlyrlfndasas---------ely--
sv-----ymcramnlgkp---igsasa-lkgmypd-i----lkk----hs
ecrf------anh--------------rc-------e--y----kd-yqe
nhla-qk--tk-----iyas-ct--gnap-kk---------vskaaeesr
ae-qklple--nrs-qglgfqntvasvtd-qpdhsiqaitnlavttepgg
afahgvdclqpsgh--atpv--fllnvp------vl--tqnsafll--ps
d-----ggn---ksevcklpl-lgvlay-----v-akgaka-------ea
sapk------------rfagysl-ck-effa--g---mi----skesl
>B
elglepgglv--ylielg---dsvgcgsqafefct---sh----------
-vsr-vgi---rhlrwvghdmscvlavtaf--lygq-------ntalggg
la--latli-----lgrykkt--idkplt--mkrsii--vvsvglaknsc
alhl-trgvkpgpg----l--pftght-----vlvrk---gvt-ypt---
g-----segelhl---mk---cel-a------------wq-fnk---pvc
hlaf-----qdaggtl-ilsda----l-----ng--dkqlhnvhcfslqv
aln-rarhadg-----hlfsyfg-vl-nwvdesv---e----dfva---c
ae--li-------plpqldrgcesfikldrkyspsysl-veecfgsaqhs
qapitclaly-hc-lvypey--r-vkfrgyl--vav---------amy--
wi-----sqshamnlagrqytlaglya-hkek--ekl----fpk----pg
vclf------vaa--------------rc-------l--y----an-yva
qhlq-nk--nk-----l--------ekat-k---a----pmvsnvtsqev
ad-se--------p-qklgftstvnqlin-ephvsvkasgnyel-yhvgn
hfgavcdcistsll--sipl--flarfp-f-hsavdatdq----li--vt
e-----ggs---rvglcrlgf-ldvvdy-----v-llgfsa-------ga
dapk------------qfeapvg--kreffleds---sp----ganal
>E
gllqdgaylagqylaql----hpvkceqkdfgf-itpgamsa---aaht-
-vrppkqkglithmqwac--sgagsilee---plleklidlawgmnvepa
fa--vttalgasstiqtmpsn--ahnvlkvgveralg--ntalga-----
-lsl-niilkdgag----l--vytptv-----iyhsn-srgkk-i-----
--------gnkkkvvlad---hk-----yhpvft-------f-p---psc
f--ael---qkyenal-glndm----l-----kv--lqdlvcaycfdl-s
tlr-kapdtre------linhhddgt-d--------------avrtfltv
tnyggi-------l---vgtmlgi-------------ie------vv-fi
rppacclkvy--c-l-----d-n-liyqgygevnvt---------aly--
gl-----igcragclgmk---ispagt-lttapse-tsfvvlgtylpphg
qykv------hed--------------tck------q--y----k--y--
ahqigpqyptk-----tyyf-sy--naad-ks---------vaggvqesg
-q-qmlsvv--qqg-agnvfqsgltatak-nqtyk-qqvdkkptkticaa
r----v-cldsgsh--akavdvilmsakd-----av--aedrggll--it
d-----dgsldeegatcrlplrl-lvlf--------wggas-------hk
qtek------------efadyrl-ak-eyyr--s---ii----qkesq
>node3
tlglapsgmv--fliqlg---gpvncgtegfqfav---swtt---lscit
-vst-vpk---rhlrwvg--lpcvltvtaf--iyaakivfdtwgialggp
la--lstli-----lgrfrkl--iakplk--mkrsiv--vvsvglakthc
nlhl-argikpgpg----l--pftghn-----vlchk---gts-yal---
g-----gdgelhl---mk---cgv-acsg---------ye-fnp---psc
h--f-----qdtggtl-alsdq----p-----ng--vkqllaahcfklqi
klk-kalhdkd-----hlfsyfg-ll-dwlensvittd----dfat---i
ae--hi-------plpqldqgcksfirtd--------l-------gahhg
qapitclaly-ic-lvyve-vsr-vqyrtfh--vaa---------afy--
wi-----skvhamnlggpqytlaglya-lknmyteki----fek----hg
gclf------vsv--------------rc-------l--y----en-yve
qhlq-er--kk-----lysadcl--dgat-k---t----rmisnatseeh
ad-qe--------p-qelgfrdtiaplin-ephdsvkatgsysa-skvgg
qfghgqdclpssln--aipl--yllklp-f-rnavivenqlsawli--in
e-----ggk---kealcrlal-lgvvdy-----v-lkgttn-------qv
dapk------------qfeayvg--k-effldeg---tp----gtnpl
>H
glclgsi-ma--ylsql----ktvkyqhggfef-t---pmtv---fecvs
-lhsplpegagekkvwec--ggcgflvakf--vlftkivhltws-qlatp
la--ivkivae--tdkklhnvtaaikilk--asrklg--ilslgv-----
-lgl-spillsgmg----l--pfscga-----a--en---akp-nglnnk
t-----rpgqmlk---vlrddhk-----y----ascqgyeef-p---pqc
f--f-----qdfahtgvgleqldpgilssiysrg--ilqlmpavcwql-v
klf-eavdtaq-----ylfenhg-gl-k--------------glad---t
vvygtl-------q---veatykmqddvi--------a-------gsefk
rppyvcqgly--c-va--------flyrafeagdgr---------dly--
glapnflnacrklaqhlg------ssa-vkglspa-igyvllkk----ng
elkefalemvqddkakslpigrqdelceh-------d--s----k--f--
khqv-esfvpt-----pyll-fy--gasp-rk---------sgeassegr
yegrkmpearikdg-egf-ylaavagvtk-egaygpsninelnvpflvai
kftgvvdclepigh--p-------ltcs------nl--ppep--ll--lf
d-----ggh---tsgitrgpl-v--laf--------lptvv-------ni
-------------------afvt-cr-efyr--g---vv----dkdql
>node7
tlglgpsgmv--ylgqlg---gpvkcgnagfgf-v---swtt---ytcit
-vst-ipk---rhlrwvc--fpcvlvinkf--vyfakivfdtwgislggp
la--lsnli-----lgrfriv--iakplk--vtrsfa--vvsvglakryc
elsl-trgiktgag----l--pftgkg-----vlchn---gts-lal---
g-----gdgekll---vk---hg-----c---------yq-fsp---pac
y--f-----qdfggtl-glndq----p-----ng--vkqllaahcfkmki
nlk-kalhdkd-----hlfeyfg-ll-dwiekgiiatd----elan---i
tn--hi-------p---vehgckrflrtt--------l-------gmhhg
hapalclaly--c-lvsle-vgr-vlyrtfhdpasa---------efy--
si-----srvqamslggpkytlasisa-lknmype-i----fdk----hg
vcrf------vnv--------------rc-------l--y----dn-yie
nhll-ek--kk-----lyaa-cl--ddat-kdirs----kmvsqateegr
ae-qk--------s-qelgfqetiapltd-qpddsikaaasyaa-tkvgg
afahgvdclqpskh--aipf--fllkmp-r-qnavivatqlsawll--ps
e-----ggk---kaelcrlql-igvvny-----v-lkgtta-------qv
qapk------------rfagfpl-ck-effl--g---ti----ktesl
>node14
slclgsvcla--ylsql----nsvkcdqkafgf-a---pmtv---facss
-lrkpipkgvvqhmrwgc--facvyivekf--vlfakivnltwgvelekp
la--vtniiga--tikkmlnvgrahkvlk--vnrala--vlslgv-----
-lal-dsalktgag----l--pftans-----vfcnn---gkp-idl---
a-----gkgeklk---vk---hk-----y----assrgyddf-p---psc
y--f-----qefehvl-gldel----l-----kg--ikqllaahcfel-v
nlr-kavntrq-----ylfenhg-gl-d--------------elsd---i
tnygnv-------p---vekkykmmfkvv--------l-------gmefk
rapticlgly--c-lvfld-pgv-mvyrgfgdgnvr---------ely--
gv-----fkcrpmslamp---imaasa-lkgmtpe-itfvllkk----hg
eckv------qdd--------------rc-------e--y----k--y--
khqv-qsyptk-----ayfl-ny--gaap-kk---------vdsaaeesr
fe-qklpla--kra-dgfafqstvvgvtk-dhdysvqavsklavttivga
afahqvdclqpvgh--lkpv--fllvva------tl--tpsrggll--ps
e-----ggs---ksevcrlpl-lgllly--------kgaka-------qa
qtsk------------kfatypv-ck-effr--g---iv----tkesl
>C
tlgltq----------ig---gktks-hatsgy-v---vwatpyiatcim
flks--ae---kslkwp---fncvlvitvf--vafakllfekwaialggn
lt--knclv-----lgnfpvv--iskptq--vkrkfdptvvsvslgqkfa
e-nl-lpginssag-kkpl--pfggkg-----vlcfg---glt-lgl---
g-----gagtkll---ik---eg-----p---------yt-------tds
y--l-----lnfggdl-agkad----s-----ngdegeqtvtshcfkmkl
nlk-qeletre-----hlfeylv-mltdwieqviipseralkelvn---i
ad--hl-------g---vehdcqrflqda--------l-------gmhqg
hlsalclmly--g-lvstk-vpn-vnyvnfrsp------------dyy--
sl-----tkvqp-sl--------kfdp-frdlyan-i----ms-------
----------vhv--------------ks-gkvphklldt----tktyiq
dhlf-gk--pkpgppplyvs-cl--gtgp-kkirfqfwdtivcqnvpssw
nv-di--------skqelgfhesrpardg-raearievwavyel------
as-------eankq--avay--flnkwe-raqdk--v--qllaghlslpv
allggqsgs---kndlcraal-ngavkytfelpralmtkld-------kl
rasd------------pfagpal-sk-qfyi--g---tf----kmdn-
>G
av---sv-la--clnkl----ksandphngfey-t---emtv---fgcgt
-fkksvkegaghkkpwpc--pgcafllery--vlfvtileltwevelakp
la--vvtvvat--tirkqhktvaamkmlk--rnqsln--imslgv-----
-ldh-sstlktgag----l--pltcns-----aictna--gkp-lel---
f-----rpgqllk---anrgshk-----y----assdsytdf-p---skc
f--f-----qefahva-sideldravl-----ks--ilhllpvvcfgh-v
kly-nqvksrq-----yylahsg-ge-g--------------plag---a
eayatv-------r---vdraykmdsevp--------a-------gmefr
rapnvclslys-p-la--------flykgfnagngr---------dlcyk
gllahflhac-qlalhlg---lvtatc-kmgfaaa-igvvqlkk----ma
efrv------ded--------------ac-------e--g----k--y--
khqt-gsyhsq-----pyfl-dynvggvp-pn---------cdna-ddsr
ye-hdlplgrirhg-dgf-yfsavtgvvk-khtykapavkklkaakiact
kf-----------h--tkgt--fllkse------dl--vpep--ll--af
d-----agg---tgsesrmpl-l--lty--------lhtkv-------qv
qssk------------hfpsyaikck-eiyr--s---fg----gke--
>D
dlglap----------lg---gpykcanasagy-v---swvp---itclg
flkp-sgi---kalkypc--fncvll----------kllfdawnvllvaq
la--vgkfv-----lglys-------ptq--lkrkfaasvvntllkkpyi
e-cvgkpgintstesk-dl--pfgan-------lchg---gvn-lgv---
gaavgigagdkll---vl---d-------------------fsi---est
t--f-----ldhggal-agkaq----s-----nl--vkqiltah-fhkrl
slkkkdledkegatgthlfdalg-ll-kwieksviatersikdfvn---v
an--hivlnsqks--------ckrylqdg--------i-------ganeg
hmpalcl--y--s-lvsld-vnk-viyrnwnssspi---------nff--
sl-----praga-vl--------sfna-fkdvfpn-i----fs-------
----------vhv--------------kc-gkipdklaggvvggskttiq
ghlf-ys--pk-----lslt-cl--qtap-rddrfq-wnapvskamqsgr
sd-vk--------taqswalkqtfpsladyqaeqkikswviyel------
tyar---crqknk------f--fllklp-rvqkt--i--qliathlplrg
ealgllggs---kndlcrnsl-fggv-------vdikttlqremiekckv
ksan------------pf----e-tk-dyfl--gplaaf----ptnn-
>F
glmmggvylt--flarm----dkagcpdknfgl-t---amna---pahr-
-lhapieagil--mrwgc--agcgtiveaf--pllpklidl---mdtksn
larfvtaallastevrkmlsklrkhk--kggvyralv--iaslgl-----
-lcl-tvtlksgig----vattysnsp-----ifcsd---gha-i-----
--------gdkkq---ae---hk-----yhntfaspttydhf-p---psc
y--aelngkqeadnav-gfhal----l-----ke--lpell-akcfhl-s
nlr-katetre------tfendgegv-e--------------kgkegmav
tdygki-------l---vekmfgv-------------ld------vs-qk
rppii---vy--cfl-----anepmtcrgygdghekhkangypdsely--
am-----lhcaagcnglk---vta-gpn-rsmkte-vsyvllkt----hg
qykv------sde--------------kg-------m--y----k-----
---------ak-----tyyl-ny--naap-kk---------vdsgikevg
-r-emlaig--dkg-asltyqkglpsvtk-epayrfqqvaklptntvcva
cfahly-cltsgse--aral--ilmvsl------il--mpkrggvl--ks
e-----vss---kgencklpl-l-lidf--------kggka-------rs
ktgk------------nm--apl-ak-dyyr--g---ii----ykqaq
>node10
glvmggvyla--flaql----hsvkceqkdfgf-a---amsa---sahs-
-lrapiqkgiinhmrwgc--sgcgtidekf--plleklvdlawgmnleaa
la--vttalgasttirkmlsnnrahkvlktgvarala--vlslgv-----
-lsl-nialksgag----l--tytsss-----iycsd---gks-i-----
--------gdkkk---ae---hk-----yhntfasstgydef-p---psc
y--ael---qkfdnal-glndl----l-----kt--lkellsakcfel-a
nlr-kapdtre------lfenhgegv-d--------------aakdgmav
tdygnv-------l---vekmfgv-------------ld------vv-fm
rvpticlgvy--c-l-----ane-mtyrgygdghvk---------ely--
gl-----ircrpgclamk---isaaga-lkgmkte-vsyvllkt----hg
qykv------hdd--------------tc-------d--y----k--y--
khqi-pgyptk-----ayfl-ny--naap-kk---------vdsgvqesg
fq-qmldig--kkg-agfvyqagltavak-dqdyrvqqvnklpttticva
rfahlv-clqsgsh--vkpv--ilmvaa------al--apdrggll--kt
d-----ggs---ksetcrlpl-l-lilf--------kggka-------qk
qtgk------------nfatypl-ak-eyyr--g---ii----hkesq
>node6
nlglpp----------lg---gpakcanasagy-v---twtt---itcvs
flkp-tai---kalrwpc--fncvlvinaf--vafakllfdtwnvalggq
lt--igslv-----lgsfrvv--itkptq--vkrkfaasvvsvglskryc
e-sl-npgintgaepk-hl--pfagkg-----vlchg---git-lgl---
g-----gdgdkll---ik---dg-----p---------yt-fss---tac
y--f-----ldfggtl-agkaq----s-----ng--vkqivnahcfrmkl
nlk-qelqdre-----hlfeylg-ll-dwiekaiiasertvkdlan---i
an--hi-------e---vdhnckrflqda--------l-------gmhqg
htpalclmly--a-lvsle-vnk-viyrnfnspssa---------dfy--
sl-----trvqa-sl--------sfna-fkdlypn-i----fd-------
----------vhv--------------rc-gkiphklvgs----tktyiq
nhlf-dk--pk-----myit-cl--gtaa-kdirfqfwktmvsqaiqkgr
te-qk--------skqelgfhetipalgd-qaeerikawavydl------
afarglecmqankq--alvf--fllkip-raqns--v--qliashlplpg
eslglmggs---kndlcrsal-ngavky-----vslkatlq-------kv
kapd------------pfagsql-ck-dffl--g---tf----ktdn-
