>C
f------------elqi-----en--itvar--a----------wpa--r
---aqkwelrygftvesntihky-nshckv-----------avq---vpl
-pr--------nli-----gcykd---gknppfk-kfqvvsi------ql
--skkhlvegsik-df----tnn--------adltl----wnmkpgptvf
ynkrdr---kksh----vnav---a-hackyalgv-sapft-----rgvs
p-------d---li--ilnflvfsvlvts-gnag--sclqrdvs---scl
etk--dlvag------ahtlclm-vr---qvasgvsdnkvlpgthvsikm
pvsgsrs-qpravv--ilesgptepalhhclkcsh--hddkyfadyltne
destwlhahldlnvs----a---------------l--------------
-gc-----vl---ak-----w-rtlcqlr---------------d--e-v
rnllrletkn---------gdkephp--vkvfikcntgigqhed------
k--yelqlvaeegiklglclr--s----ka-sdl--cga--l--mgy--l
vqlrhstctasasgslpvlqvhps---agapatkeqlaik--------k-
fiitkqanqlslk-cgsggh--tsnknyma------------gvngkskf
gkas----ekq--dgkpkdtilgvdakw-vvgpaikkfchkstykaeg--
--elacspk--grdk
>node10
l-fvsnkeftalasl-------nk--vkgci--e----------mpi--n
khlhatwlicacyndssspiari-p---aksr--------aclhyvkdrf
-pv---addthngn-----qafsalgnvsepetn-k-mia-v------ni
ldrktkngqnl-e-qy---pcpi--------pg-kl----wierhg-qiy
fm--vk---klvhk-va--lillis-ecalhplni-sghln-----rlvh
--------k---liqvil----adllips-dd----------lwki-apt
tgrialitst---nlaphsisl--lgihyqsge---ddqslerreeq---
-thlgql-hnrvav--slkqspekltlq-c---kd--ag-gfggdyipdg
grglrlktri-kavlpethqv----------c--k-----qdkrfkavll
agc-----ikksksk-----r-a-------------------------gg
selneteiaepanvckvaygfpqpepgpy-v---sqggvgeild------
twkfd-------elqlkecfk--g-----qlrvr--itasil--mty--l
fgskknk---avpgdevg----pv---imghqdspkqilp--------kd
cvism--ccgiln-cytygsaecnanp-ldfqghaslqfidstkqsflei
gslc--ivs--n-ppkgknsg----sivsgmdhgtrkys----ansdl--
--h-----a---rdk
>G
l-fagareyfalilmqg-----digdidgciele----------tpggak
htllafwrtkya-segareiaki-tdrsnkqk--------dclgyvkspf
-plg----lnqldp-----hclismgdvsfpepe-k-kgg-vydstltya
lkkkgklvenv-apey---vial--------pr-kin---wrikaa-pgf
ll--vrrfsslldq-vk--evl-iq-dctlyslqv-tghsg-----rvlw
y-------k---llqavl----ydgliraandpr--tci---lw--pecv
tpk--ggkav---dltlhdlp--------kitq--ykkknmgkfdke---
-afwghl-qsrinvdsvlk----yitlq-c---kkcmnnegekadyvpnl
gaelkfktql-natlasaksi----------c--e-----eykkfngatf
dsc-----ks---pk-----r-k-------------------------gd
vhlmhpdsth---------rfidpnv--i-t---csngagpt--------
----p-------nprlslcfgpas-----dfkqhvgiktdmi--msy--s
i-akrdt---tva-gdvg----hcvktlasq-evgsvlip--------k-
c------ccgkll-csaivr--csnqg-lda------rfvnaakqafldf
gglc--rga--d-paestkkllsesgvtdsldkapmkfsyryspgtll--
--q-----kik-hds
>node7
lcyg---qllaltdlgl-----dq--vkgck--d----------wpe--r
---eqtwdlrysfsagekeiskv-dshckl---------avgiq-qgvpf
-prtl-aeenrnmi-----gcyktvgnvsqpeyk-k-qiasv------hv
ldnknslargsiq-dywayscai--------pnlsl----wiikrg-qpy
ylrrir---akmqg-vk--li---a-escqyalgv-akrfd-----kvlt
y-------e---li--llknlvlsllipg-gtag--scl---vr---acl
agk--didsg------vhemclm-lr---evve--hnnrvlgnlaeq---
-vdgghf-hdkalv--ileqgpkestih-c---sn--heevfngdyfted
ghtvwlaanlnlpvtpgfhq--------------------qnknydakly
dgc-----ia---sk-----w-kthcqlr---------------a--d-g
hnllktetvq---------geiephi--lrv---chggvgqsld------
swmfn-------alrlepcar--a----kp-rnn--cgastl--msy--l
vaekkyscsvsvagsmvgitvrps---ttgpaekaplvik--------k-
iivtrkpccsalt-cdvygh--stsks-me------------dkkghrkf
gkgc--hpa--d-spklkdatlgddstw-gmspkikkfcyqftahaqg--
--qvacspq---kdk
>D
fcfg---qlvnmeplen-----dn--ikg--------------------r
---aqkwdlqlhfsaeeeamrrv-qanckv---------gigvq---kpl
-prst-vqlhrayv-----gchnehgtvaedpyk-t-avmnm------hl
ieskkhltkgavq-gfwayssht--------anftl----wn-kla-hgf
-vrpnh---tsmh------vi---d-dsckynigvkkspft-----ivls
eaikyltfi---li--vlsylvlivvv------g--kc----ih---acl
dvn--dlesg------gypmcvv-lr---qvve--tnnniqpatqvd---
-vkygln-qanslv--hlekgpkeqslhhcgkcnh--aeelylgdyltdd
sqtvwlsahfasnta----a---------------s--------------
-gc-----vr---ak-----w-kslcqlr---------------d--n-g
rillktedkq---------g--eepl--lns---chagvgklananwalk
k--yd-------alrlgpcvr--g----kp-rel--cgngal--lny--l
veqneykcteavklsmvgialep------apaldeqllak--------k-
filskkdtqtaik-cddngh--sacks-mv------------qnigkskf
ssactqqpe-k--nprpsdavlgieakw-gvtpkvkngcyk---------
-----cspk--aqek
>node14
l-yasskefialahlkg-----ne--vkgcl--e----------rpt--k
kqleatwqirygyndgsreilrv-strcekhk--------vclhyvkdsf
-pltl-peanhnas-----qcftalgdvaepeln-k-mva-v------ni
ldrkgkltsnl-d-ey---acai--------pg-kl----wierhg-qif
fm--vr---khvdg-ik--lil-vs-ecplyslsv-dghlg-----rlla
y-------k---liqavl----adllips-ddps--tcv---lwki-tci
tgr--gidsa---nltvheicl--lr---qige--hdnksmgkfekq---
-tdlghl-hgraav--vleqgpeplslq-c---kd--aeegfdgdyfpdg
gsslrlktqi-kavlpeahqi----------c--q-----qdkkfkaalf
dsc-----it---pk-----r-k-------------------------gg
sqlteteaaq---------gfldpqa--y-v---chggvgetld------
twkfd-------elqlkvcfr--a-----qlrqn--itasil--msy--l
fgskkns---svsggqvg----pv---imghqeaanllvp--------k-
ciisk--ccgmlt-cttygr--csans-lda------qfvdptkqgflef
gelc--rva--d-ppkgknsqlvdnaivggmdhgirkfsyrytantll--
--q-----p---kdr
>E
l-fvanrelsllvnl--nagnenk--vhgct--kkhcltaayfqlpi--t
kslhetwdicacygdtsesvarlks---aksr--------tclhyvknrf
-pv--vvpdthnan-vlarqafsalehvyepetnlg-pgs-v------ni
ldrktmnhqnl-m-ey---pcpi--------pg-nl----wakrng-qvy
fv--vk---kkvhk-vp--lill-spgyalpalkl-sghln-----rlva
--------k---liqvvl----qdllhpk-nd----------fw-i-apt
tgrialivkt---nfgaatatl--lgihfqsae---eqeml---------
-thlglq-hnrvsl--dliqtp-klslq-c---kd--av-gfggdyindg
sklvr-------avvpdthsvedgtaqkdtc---------qdkrfkpvlm
kgc-----ikksqpk-----r-n-------------------------ef
seldekeidepanv--vvygfpspekgpy-v---nqagvgaiid------
swpfr-------elql--cfn--g-----qlstr--itamgltarsy--m
fatkdnk---gvagdevg----av---lvtnqdtskeila--------ke
cvisk--ccgvlt-cytygdaenaatp-lgfqpqaskqfsdivqqsflql
asl-----------prgknsg----tvnsgmqqnsrkys-----rssl--
--h-----d---rdk
>A
l--e---ksltltslgl-----eh--ikeck--e----------wpd--r
----qtrhvrfsffcankgvr-v-nshckl---------gvg-d-qnlgf
-pktl-kdedrnvi-----gctrsineveds----q-qitsv------lh
ldqkngfqrgevq-dywtyacei--------ppasl-vgarcltkp-kpv
ylkkv----------tk--ma---t-atckyalgl-akrhd-----ellt
y-------eiyslr--llmglvptqlisg-gatgdwnce---vk---ayl
vn------ng------vhegcle-aw---dvvg--henkdlesva-s---
-vaegrf-hakiit--vldkhsavkniq-a---cp--qsqifdgqnftss
ghtswiaagaalpptp--qp----------------lsitqdlgi-----
--c-----id---pkyskies-ksmcqvralekqtgtpafracrasle-s
hgllkgntvn---------aeveshf--lki---cvgseqgsvk------
swlfn-------elrldpcis--nknngkp-rkn--ckeatf--lsy--l
ieykkqsgkisgagg-lgvavssn---tsepvvkspmvlqmpelplkfg-
ltvaskrccselg-cavvgk--sqskd-ms--------------------
------hps--v-tsklrgialeptttw-glcpdvkkfsyqftaqeas--
--kvggctq---tth
>node3
lcyd---qlltltelgl-----dh--ikeck--d----------wpd--r
---eqtrhirysffsaekdvs-v-nnhckl---------gvg-e-qgvpf
-prtl-knedrnmi-----gctrsvdnvpdpdyi-k-qissv------lv
ldnkngftrgnaq-dywtyscei--------pptsl----wcitkg-kpv
ylrri----------vk--lv---s-etcqyalgl-akrhd-----kvlt
y-------e---lr--llmslvpsllisg-gtagswscl---vr---ayl
vn------tg------vhevclm-aw---eivg--hdnkelesvads---
-vagghf-hdkvit--ilekhsavkkah-c---cs--qaevfdgdnftsn
ghtswlaasanlpptp--qp--------------------qdrglgariy
dgc-----id---ak-----w-ktfcqlr---------------a--e-g
hsllktntvn---------aevepqi--lrv---chggvqqsln------
swmfn-------alrlepcvr--np---kp-rkn--cgqstl--msy--a
ishrksscrvsgagg-vgvavrsn---ttgpavraplvitmpelplkfk-
vtvaskrccngla-cavvah--senks-ms------------a----rki
gkgc--hps--v-tpklkgaaldaattw-glcpkikkfsyqftaedds--
--qvacasq---ktk
>H
l-ytslrefaalahakg-----kv--iegcv--k----------rpr--k
ns-gafwr------vgprmilqi-ggk--kkn--------gcmgyknqpl
splqf-pgvwhldta----hcltrkdglaysepa-k-sgg-i------ya
lekkgkltsnv-d-df---nlvlkykkgsisag-klt---lkektg-vtf
wl--vl---nhlegpve--lih-vp-dcplyglqm-eghld-----rlfl
y-------d---laqavl----feglakp-nepk--tcg---lw---epi
igr--gvesv---dltipdlcl--lr---qvaq--qhnktmgnyqrq---
-snlghmlqpklgvdgvld-----ltlq-c---ekalnnegvganyvpqv
aaamkl---e-daalpaahqi----------c--e-----ekkkfkgalf
dac-----kt---ak-----rap-------------------------ga
sqllqtnaty---------rfldpda--y-l---chggateti-------
vwk------------lkv------------lk------gntm--mcyael
fpvrgns---pls-aqls----pcvsvlpaa-aatgqlvp--------k-
clvap--cigklmtattatr--cnaqs-ldt------rfvegkkqafldf
gnyc--ria--eakseetkialsnttisdglgssvmkytyrytpntqlst
lfs-----r---kdk
>node13
l-ytsarefialahlkg-----ni--vegci--e----------rps--k
nslgafwriryeyndgareilri-sgrcnkkk--------dclayvkdpf
-plsl-psvnhlds-----hcltsmgdvaypepn-k-kgg-i------ya
lerkgklvsnl-d-dy---vial--------pg-klt---wservg-qtf
fl--vr---nhleg-ik--lil-is-dcplyglev-dghlg-----rlll
y-------k---laqavl----ydglvra-ddpr--tci---lw---eci
tgr--gvnsv---dltihelcl--lr---qiaq--hhkksmgkfekq---
-sdlghl-qgrvgvdgvld----hltlq-c---kkcmnnegikanyipnl
gaalklktql-natlpsahqi----------c--e-----enkkfkgalf
dsc-----kt---pk-----r-k-------------------------ga
sqllhtdatq---------kfldpnv--y-l---chggagetle------
vwkfp-------narlkvcfgpss-----elrqh--ikadmm--mcy--l
fpakknt---svs-gqvg----pcvstlpsn-eagsllvp--------k-
civsp--ccgkll-ctaygr--csaqs-lda------rfvdatkqgflef
gnlc--rva--d-psedtktllsdsavtdgldkgvmkfsyrytpntll--
--q-----r---kdr
>node6
fcyg---qlltltelqi-----dn--ikgcr--a----------wpe--r
---aqkwdlrysfsaeddaihkv-dshckv---------gvgvq---vpl
-prtl-velhrnmi-----gcykdlgnvseppyk-k-qvasm------hl
leskkhltrgsiq-dywayscnt--------aditl----wnikrg-qvy
ylrrnr---kkmh------vi---a-esckynlgv-sspft-----rgls
e-------e---li--iltylvltllvts-gtsg--sclqhgvr---acl
eak--diesg------ghsmclm-lr---qvve--sdnkvlpgtqvq---
-vkggrn-qnkalv--ileqgpkdptlhhclkcsh--hedmyfgdylted
gqtvwlaahfnlnvt----a---------------l--------------
-gc-----vs---sk-----w-kthcqlr---------------d--d-g
rnllrtetke---------getephi--lkv---chagvgqhed------
k--yd-------alrlgpcvr--g----kp-kdl--cgasal--msy--l
vaqkhytctdsvsaslvgitvhps---saapaqkeqlaik--------k-
filtkkasqttlk-cgengh--tasks-mv------------dkvgkskf
gktcpknpekq--dpkpkdavlgvdakw-gvtpaikkfcykftchang--
--qlacspk--grdk
>F
l-l---kefehitsl-------pk--vkgiv--n----------apv--n
kqlhakwlicacytdssqplaki-p---smgr--------tclhynkdrf
-pv---addthngn-----qafsalayvseqevn-k-lia-v------ni
ldrktkt--sn-e-nl---pcli--------pr-kl----wmqrng-qiy
fm--vk---klipk-ta--lillls-echmhplgi-eshlk-----rvah
--------k---iiqtln----adllips-nd----------lwkv-spt
lgrislftstsvphvappsv-l-si-ikyqrki---ddgmferkenq---
-ihlgqv-hnrgat--slkkspekltlp-c---ke--ag-gfggdyepsg
gaglalttri-navlpksris----------chvk-----gagkfkamlt
dsy-----vkkdksk-----r-a-------------------------ag
selketeiaepasvckvaygfpqpepapy-v---nqggvgeilg------
vwesd-------elqlkecfk--g-----ilrvr--fsptif--vty--l
fggt-------vpgnepg----pv---imnkgdsskqi----------kd
cvvel--ccgf---cyqygspqceaap-kdfar-----------------
gklc--iis--e-ptkgkvtg----tlvsgldhgtprws----ansdl--
--h-----n---adk
>B
lcfg---llltlsvlsl-----dg--vkeck--d----------wpd--r
---dnrrhyryeffggetdvs-v-nnhcrl---------gvg-e-vavpe
-prfl-knksrkfv-----a-aksntrvpdagfi-k-qvtsv------vl
lkndtgfkrgaaq---wtyscei--------pptsl----wcikka-kpv
clrri----------vn--sl---s-enceyelgl-asthnankki--li
y-------q---lr--qllslvqtlsick-gtagawtcl---vs---ayl
td------ag------ehqvclk-aw---eimg--hdekdlakivds---
-vasghl-edkvtm--lle----vkkah-s---ca--qaevfdgdnvtgi
ghpswldasn-sapkl--dp--------------------qdngqggsiy
hgcrlihcid---ak-----s-ksfyhlg---------------r--q-g
lstlktgein---------advdpiv--nql---chggc-----------
nw----------alrlepcvw--sp---qp-rkn--cgqatl--msy--s
aphrkcsvrvqgvgg-vflagrsk---ttgpgvrtpliitlpelplefd-
tgvtekrccngms-ypvvnh--sknkt-tv------------g----vki
fk------------akllgakldtgitw-gtcp-ikkfhyqfkaed----
-----cppt---kss
>node15
lcysigkefvalanlnl-----dq--vkgcl--d----------wpe--k
sdhdqswqlrygfnngerellrv-dsrcka-kcphkvchavglq-vgnsf
-pltl-pevnrnit-----ecfktagsiaepdli-k-kvasv------hv
ldrkgsltsgl-d-dy---acai--------pg-kl----wilkrg-qpy
flkrvk---ervqg-vk--li---s-dcpqyklgv-darfg-----rllt
y-------a---li--vlkkfsasllips-dapg--tcl---vr---vcl
tgr--eidsg------vheiclm-lr---evme--hdnkvlgnfdkq---
-idgghl-hgkalv--ileqgpdpstlh-c---kd--eeegfngdyfpeg
ghslwlkthlnkavtpgfhqv----------c--e-----qdknynadlf
qsc-----ia---sk-----h-k-------------------------gg
sdlietqsaq---------geiepqv--f-v---chggvgepld------
awkfd-------elqlnacfr--a----kp-rqn--iaantl--mah--l
vaaksys---svagsqvg----ps---tggpaenanllvp--------k-
civtkkpccsmlt-cnvygr--sssks-mea------qfvgpdkrghhef
gdlc--raa--d-ppklkdaplgddsvvggmdhgirkfvyqftahalv--
--q-----h---kdk
