>node14
lrlnalv----v--klepanmgllg--spiid-q--pq----cnpeds--
d-faeav---sfdtkcqirflsdksf---rptiwg-------lcitt---
---vervekl-pkftvaplg----ks-cthqtnfiwrqchtvdmg---pt
vgklvkawssghi----lcllqypsavqvpggs-kk---v---dselcsv
--a--vkkngkapiafigachpiqigldg--lsilefq--mspdasnlrv
-cd-h--------e---------p--mptas---akgtyaldvi--psvl
qaaa-----henkgrsyclt--tpgigs-gikleaw-kat-s--isg-vt
hgsfidhptskq------alrklqp-apl------ak--kks--a-sanp
dl-----la-gfdptkl--s-vne-----mgpailkfmd---qrip-l--
-----nelq--g-stvsh--------ph---ckickllasgcs--llwdp
hklrvff---rmqg--------pghttawlapasldg--msel-raqkit
lgtthpad------sgklllafviphaq--ssspsg---div-gl-----
g--k--apfeyhaak--------p-tvlkp--kds---grvkg--tgylt
aalteytfyi-gv-dafaq-------qvlvfgk-----skvwpnvnss--
-lt---------fprlk----rvrelgg--------v-av---gkskf-g
akyepra-rg-sk-agadkch
>E
lrla--t----d--kfdpaslg-la--spivh-ektpq----t----s--
egftnta---sfarkcltfflsekaf---rytien-------lctvteaf
heevervenl-pafyvvplg----lqkcvwelvymsrachtadik---ht
kg-lpklwetgqi----lplnqfessfgtgese-ve---t---kseickp
--macekkn-kkpiayv---cpmrvglkg-ylalvdfg--mgenarllrt
-ca-s--------e---------p--mttaa---aksvyalpv-------
-gaptweakhlkagrlfcls--ahahgplsqkaenw-glt-tgringrvp
hgkfadngvike------tlgklnk-gpfglddlrad--skm--t-paae
tl-----lg-gfkpakl--k-llp-----kepaa--flk---grvp-l--
-----ngla-yg-skish--------ph---ctccevltsgckshllwdp
hklreffptl---q--------hphtakwlaafsvdp--mieythmqei-
------payhavagpgslqlttgvphtq--akn------dligkl-----
g--a--laeeyhqtg-----------------kea---trlkg--pgyrl
sgvgeesfavkgd-safaqgav----hvlafge-----gnvwptinvt--
-lhllytvashnlprli----rpkdinl--------iq-------arf-v
tkyaprgtrg-sg-agpgdch
>A
lfvtivt----v--kikpgkshltg--kgftd-k--shynmkcaisnn--
l-lf-c------gakcklpfiketacgi-rrsvng----------sg---
---nk---gl-pqflvskta----ks-ctttgpyawdrshildah---pp
e---gkdwn---a----i-gslfnegakipggpn-t---vgacseelcyv
lna--vssqdqgtvgffghcglfla--rif-lgllefs--adpnagvqlv
psd-vka-datlcs---------c--spnhh---t-gpyt---snkakav
gpgp-----r-------cla--ipgvnl-g----rr-ksn-l------vn
-----pssarrn------idckgea-as-------a----lk--v-srgp
sq--alssmat----------ekl-----lirelfkf-e---hrvd-l--
-----tesq--f-dvlqn--------vg---ckacshk-------lvwpk
rdlp--f---kvag--------ed--spwlqaslldq--mlaa-k---am
-ctp-------------lhlayaetsdd--gepvag---slm-hl-----
aftr--nvfehqkikkllacnhtkesllhg--thd---gsags--easiq
akfakya-------------------yvlpagk-----skvw------gc
ttv---------nvrlh----rvqqwth--------c-gg---eradmkg
sqyelka-sg-aq-lesdach
>G
lrllamv----vvkqlepsalgmlg--apvia-k---n----cgpqed--
d-lattvnvacfdgktqtrflsyks----rp-v-g-------lcikn---
---lqrvetlnpkynvaplgrgtkgs-caqqpsfiwpqcdaadmg---pt
cakliaaaasgdidgfylcclqepsyesipegn-mk---l---apqvcnv
--g--rerpakaeiafisschpirsnigt---s--at---lskdnislal
-cd-h--------e---------pkvlhavg---akatyv-dvq--pcvl
pgav-----hekkgaayrgl--gpgcga-eapdevw-kpcek--fsk-va
dapv-hhpavah------tlr-lqq-apl------ik--ksshyq-avep
kl-----ls-gfqpprltep-pyq-----lghkilkl-a---eril-l--
-----vefva-g-salkh--------an---cklcsllhgscg--liwep
hklrv-----rmas--------pghtraalaaqpvng--ma---rgtkcs
iatadead------l-kgllgfviphlq--sktaanedgqvt--pngckk
g--k--ap-thhsgl--------r-tvlkqtlket---pr--p--eryas
gaktqytffa-gvanlfvp-------eelisfq-----gkvwi--nss--
-lt---------naqvt----rmvefve--------v-nhlsatmskl-g
gktiar--sgrsn-tggedck
>node13
lrllalv----avnqlepsnlgllg--apiid-k--pn----clpqes--
d-fttsv---cfnnksqsrflsnksf--arpaiwg-------lcitt---
---larvetldpkytvaplg----gs-cahqsnfiwsqchavdmg---pa
ckklvaawtsghi----lcclqypsaeavpssn-kk---v---apelcsv
--a--rekagkapipfigschpiqsgigt--as--dtq--mspdeeklqm
-cd-h--------e---------p--lstas---akgtysvdvq--pcvl
pgaa-----hekkghaycll--qpgsgs-ggkpetw-kac-g--fgg-vt
qgsi-hhptvth------alrnlqq-asl------ak--ksshya-aaep
kl-----la-gfdptrltsp-pnq-----lgheilkf-n---qrip-l--
-----nefq--g-stlsh--------pn---ckicsllhngcg--liwep
hklrvff---rmqn--------pghttaalapesvng--mtel-rgqket
lataqpad------a-kgllafviphlq--shsaaneedevv--l-----
g--k--ap-qyhsal--------a-tvlkq--ket---ar--p--erylt
gaitqftffi-gvndlfvp-------eeliffk-----gkvwi--nss--
-lt---------gpqvt----rmaefla--------v-qhlsattskl-g
gkysvrv-rgksn-nggekck
>D
levntvttrnvi--slkppnvklng--itfkh-d--kd----cqgntp--
f-fsgtl---tlpsnchlpy-----egl-tptvwa-------vclas---
---idkglgl-pvfli-afi----kg-ctkgsafiwlqeqakemggappl
e---adswp---l----i-ls-------------rd---ia-------vi
--r--asphtwgkvfff----------elf-lgevhfr--adanpaqqiv
-cd-a--------g---hkngcgg-----paitkpaigkalnlt--pdvl
aie--------kd-ratelt--ipgtgt-t----kwhhrm-t--yag-sk
-----thapkrq------aktkg------------ak--edg--i-tras
er-----gl-gvdsdrl--pcggkcgcfdfqfdtfty-p---gwla-i--
--gnstkvt--e-ealps-------wiavnpaglcnir-------vlwrg
sklkv-f---likslrrvndvsae--aawlaaaevig--lcea-n---sp
---v-------------lnlaymeacne--hkpvt--------al-----
pftr--aaytarnannll----sd-vtlkg--rnmkntsld----edsiq
lplgdyp-------------------avlsrnk-----sqiw--------
-la---------ypnlaqvgfrlenvtd--------v-vr---grnt--g
qafegqa-----k-asalkch
>C
levatvttrsgv--ammstnvklng--ipfae-k--pe----cesnpp--
f-fsstl---pfpvkcklpyvfeqesgf-qptmwg-------mcars---
---iekaigl-pviiiakla----kg-ctkgsmfvwlqlslvdkggskkl
e---vkswp---a----f-lktvdaghdkpgqpcrakklvs-------lt
--a--assytd---vfh----------dvi-aievqfkadvnneakeqla
-cd-l--------d---------g-----paisksakgnslelg--sdyl
eltp-----rtkfgrapplf--tqeigt-r----pw-yrg-a--yeg-vn
-----kaivk-e------tritgtq-ekc------as--nkg--v-trpn
rr-----gl-aldgarl--aca--------kigrfsc-a---gwlvtl--
--ghctnfs--a-eavht-------wda---calc--k-------llwrk
pklkl-f---iiks--------ta--nvwlggpdils--lcdq-e---ap
-caa-------------mnlaymedyte--nqkvta---vvg-pl-----
pfas--aayekrkankll----ve-illps--kra---gap----desik
itlaeyp-------------------mvgqrsk-----ssvw--------
-ld---------ypklg----rqddvav--------i-ga---gvse--a
d----ka-----k-gkt--ch
>node7
lrvatvt----v--klkpanvrlng--kpfts-k--ph----certvs--
l-fteal---sftakcrlpfifdkgsgf-pptvwg-------vcvsa---
---iekvvgl-ptflvakla----kg-ctdgssfiwdqchvvdmg---pl
e---aknwa---a----v-lshytegvkipggpiqt---vgtidedlclv
--t--vnkndkgsvafygncvvirv--dgf-lsilqft--mgpdgeeqlv
-ce-q--------d---------g--tpvps---tnaanaleit--atvl
gata-----qqkkgragcla--tpgigt-g----kw-hrn-s--ymg-vk
-----thpvrrq------tlckgqs-arc------at--kkg--i-trap
ph-----gm-gldptkl--a-gkk-----lvrnlfkf-a---gwiq-l--
-----getr--a-talqn--------ea---cricslk-------llwpr
rklrvff---kvkg--------ad--sawlaasalds--mida-s---as
-cvt-------------lhlgymeaqae--gspvsg---gim-pl-----
pftr--apfenqkankll----as-tllrs--rhm---gsvag--dasir
vtlseys-------------------qvlqvgk-----pkvw--------
-lm---------yprla----rvqevtg--------v-ag---gradfsg
dryegka-sg-ak-lasqkch
>B
ihvatiy--------ikppdtmleg--kkfaalk--shhnlncgiega--
i-lvcal---tftakcrlpflndlgsgf-epeiwa----------sg---
---dqkatvl-pqylvskks----kg-cnkggeymrnqseilemg---ps
m---gkdwa---s----v-rthitqpatipsgps-k---vgagfdglcai
--a--vnldekgcvifygkcvvfkg--rpy-lgivgns--fgpgagvglv
psdciyqydpttcn---------a--tganl---aahsksleis--aksm
gatp-----a-------tva--iegvgv-g----rw-dsn-m------lk
-----lkrirkd------ivckgkn-ds-------s----lt--v-thas
sh--altgi-tlhrmkl--c-grv-----lvaqlfkv-a---apie-l--
-----kntk--sgsvlpk--------vg---ckaskln-------llwpr
rrlpafs---ktpe--------sd--sawlagnalen--kida-k---qg
-cvf-------------lhlgymevend--ggptpg---gem-hl-----
sftreanayedqkikcli----ttdsllhg--chm---eslgt--kattq
ivlhkya---------------lnfahvlpvgk-----skiw--------
-sv---------yfkln----rvsqkvd--------c-gv---eknefyg
dqyigka-aa-tq-lsaqach
>node6
levstvttrsgv--klkpsnvklng--ipfan-k--pd----cesnvp--
f-fsstl---sfpakcklpyvfeqdegf-aptvwg-------vclsa---
---iekglgl-pvfliakla----kg-ctkgssfiwvqthlvemggarpl
e---akswp---a----i-lshadegikkpgqpirt---vg-------lv
--s--assytrgsvsff----------daf-lsevqfr--mnpdheeqlv
-cd-l--------d---------g-----psiskpaagnaldlt--advl
altp-----qqkngraaalm--vpgigt-n----kw-hrg-a--yeg-vk
-----thpvkre------akikghe-arc------as--nkg--i-traq
pr-----gl-gldparl--acggk-----mqinrfky-a---gwli-l--
--gnstevt--a-ealqs-------wna---cricslk-------llwrr
tklkv-f---sikg--------ae--sawlaapeiis--mcea-n---ap
-cat-------------mnlaymeahte--nkrvtg---vvg-pl-----
pfar--aayenrkannll----ae-illrg--rrm---gaa----desiq
itlseyp-------------------qvlqrgk-----sdvw--------
-la---------ypkla----rvqevtv--------v-ga---grge--g
drfegka-----k-akalkch
>node3
lhvatvt----v--kikpantrldg--kpfte-k--shynmtcaisnt--
l-lhyal---sftakcrlpfindkgsgf-ppsiwg----------sg---
---dekavgl-pqflvskma----kg-ctdggsyiwnrshilemg---ps
e---gkdwt---a----i-gshftqgikipggps-t---vgaideelcyv
--a--vssqdkgsvvfyghcvvfkv--raf-lgildfs--mgpnagvqlv
psd-tlq-ngtlcn---------g--spahh---tsspktleit--akav
gatp-----k-------cva--ipgigv-g----kw-hrn-m------ik
-----ltpirrq------ivckgrs-as-------p----lm--v-srap
sh--alsgm-tlhrtkl--s-gkv-----lvrelfkf-e---nrve-l--
-----getr--p-avlqk--------vg---ckacnvk-------llwpr
rrlpafy---kvng--------dd--spwleasaldn--mida-k---ag
-cvs-------------lhlgymeaqdd--gspvgg---gim-hl-----
sftr--npfeeqkikkll----tnenllhg--shm---gsvgg--datiq
vslskya-------------------hvlpvgk-----pkvw--------
-ti---------ylrln----rvqqrtd--------c-ag---eraefkg
dryegka-ag-tq-lasqach
>F
lrltvit----v--nfepamla-lg--spirk-n--pq----ctpaee--
dgfadal---slntkcllfyilhkas---rktihkaghcagalci---vf
deklkrvemp-ptfyiesag----lqkcarmihnlarqchsedmh---ht
kgrlvkawgtgdi----lcllrisdslsvnnas-dg---t----gdmckf
--akcgkk-------yvgacqpthlglhq-cmivvkfn--mspeerllvm
-ce-t--------dalg------p--mtiap---lessyaldv-------
-gastpqakhskaisnycvtksqhgtgptaekaahw-tlk-p--vndrvg
sgkfaehgivkeapeagkalrklepygptglddlkak--kkp--g-sant
dl-----lt-sfkqtrm--n-lsp-----ngpaatkfldtyiakvs-l--
-----tglk-yg-htiavdtqgctr-ah---ckccnvlstgcksfllwdp
hklrkfy---rvqk--------pghdtawlaaysvep--qrey-hmqqv-
------ad------pqrralsygvphaq--art------dlagqm-----
g--n--iaveynqtk--------r-gvltp--ita---lrvrgdgsgylg
ltpaeytilvkga-gtifl-------qvltige-----grfwstanis--
-lel-----dsqvlrlk----rtkklngattansvhl-lg---erskf-g
pkygpracrg-gk-agpghch
>H
lrplalr----vvgaldpndlglfvanqplad-p--pn----clsqpgmp
d-fkvdv---cfdnkshakflpndsf--arpaiwg-------lcttt---
---larvntlakkytvtplg----gs-caersefiwsqcdaieme---va
ckklvsawtaghl----lcclhyppvkavphpn-nk---v---lpelcsv
--a--reqagkgpipfig----adssfqt--at--ntq--mseseeklem
-ce-f--------e---------r--idtas---akgtfgvdvq--pctl
paha-----knkkglaycll--qegsgs-gtkpdtw-kac-g--fgg-vt
agsi-scpdveh------aprnldq-aal------pkglknphyaraaep
klpm---la-gsettklanp-pvq-----lghevlrk-s---qria-lla
eg---safq--g-stlsh--------gn---ckic------cg--liwdp
hnlrvff---dmkd--------egagtpalapesqngesvfel-reskqi
iatgqpd-------q-kalnpfiiphlsdqshsatkgedevt--l-----
g--k--vp-qyhsai--------y-----h--ken---ak--p--ekflv
gaitqfaffi-gvgdlfvp-------edvifskgpkfnsriwl--nsg--
-vt---------nppat----kmalwla--------v-snlgvttsil-g
gkysvrv-kgnkqaeggekck
>node10
lrltaiv----v--kfepaslg-lg--spiin-e--pq----cdpeds--
dgftdav---sfntkcllfflseksf---rptihk-------lcistdvf
hedvervekl-ptfyivplg----lhkcvrethfisrqchtadms---ht
kgrlvkawgtgqi----lcllqfpdslgvsngs-gn---t---kgelckv
--aacgkkn-kppiayvgachpihvglde-clsivnfg--mapdarllrs
-ce-s--------e---------p--mttap---aksiyaldv-------
-gaatpqakhskagrnyclt--shgtgptgekaenw-slt-t--vsgrvt
hgrfadhgvvke------alrklqp-gplglddlrak--kkp--s-sant
dl-----la-gfkptkl--s-vtp-----kgpaalkfld---akvp-l--
-----nglq-yg-stish--------ph---ckcckvltsgckshllwdp
hklreff---rvqk--------pphdtawlaafsvdp--mley-hmqki-
------ad------pdrvlltygvphaq--akt------dlvgkl-----
g--k--laieyhqtk--------s-svltp--kds---srvkg--sgyla
vglseytfyikga-gtfaq-------qvlafge-----gkvwptvnvs--
-lal-----eqelprlk----rpkdlng--------l-lg---aeskf-g
tkygprasrg-sk-agpghch
>node15
lriatvl----v--klkpsnvsllg--kplit-q--ph----cdraes--
d-fteal---sftakcelpfvsdkgfgy-rptvwg-------lcipa---
---iekvapl-ptfmvaklg----ks-ctdgtnfiwrqchtvdmg---pl
vgmlaksws---a----vclshytsgvlipggpikk---v---dpelclv
--t--vkkkgkgtvaflgdchpiqvgldgy-lailqft--mtpdganerv
-cd-m--------d---------p--mptps---angtyalevt--vavl
data-----qedkgrayclt--tpgigt-g----kw-kst-s--fsg-vt
hgsfinhpvskq------tlckgqa-ari------ak--nkg--t-trsp
ph-----gm-sldptkl--a-gkk-----mtrailkf-e---arip-l--
-----nelr--g-ttvsn--------ep---ckictlktsgcs--llwqp
rklrvff---rmqg--------pehtaawlapasldg--msei-r---as
lgtt-------------lhlgyteshae--spsasg---gim-gl-----
gytk--apfeyhkan--------p-tllkp--knm---gsvkg--dgyvr
ptlseytfyv-sa-dnfgh-------qvlvfgk-----ckvwpnvkss--
-la---------yprle----rvqevag--------v-aa---gkakffg
dkyegka-rg-ak-lgaakch
