>G
---ap-rkkagttffifq--lfssspfl-petwydgeggilvlsgkyaet
---------gdyagyggv----a-------rgpankavlellkrqig-ps
ttava---cqkedeansvkypegh-argnvt--q-kd-dnfvgep-----
--s-gg-prlldsgnkn-chgtdll-------vvvmckst-----lilkv
ycynsgkgrkvtnek-vkag-kglnansry-vgfkglevg-----ka--e
-i------k--mgalg-taglmdknlhelvf--ltadylgqdlsadktsk
gqtaptfyd--agsacphe-prlvrgkfagdgte-nnvlel-----khal
nv------rvllcvhqtgqi-gk-k--nnwemtgayr-----------ip
vlynnfhdncatkl-------------qepa-grdmdc------tkgl--
--agkri----a---kkgpleklksnkhaqskafscpqvtk---ms-g--
-d-lk--lftilyalpfl---kkcl--aha-------------lkpgl--
---arrkvadd--sgfllmestndlrkll-ggyggkii-tlycmvtksaa
gwrktkari-v---g-------pr--gg---y-----llqhs--------
------igklal--lsvyrtgnleltffthehsyy----------flvm-
---yvfsvna-----sseesfltnifytnmqasvvgdsskdastk-gami
he-------qlsgl---------isv---mlek-khlkk
>node13
---ap-rkksgttffiyf--lfsgspfl-pqqwydgegaivvlngkyadt
trrglkaslgaftgyggv----t-------rgpvnk--lqllqtqig-en
tpatg---cakededssaifpegh-ttgavgkkm-tg-dnf---p-----
--s-gg-aklldsgssa-rhgsdlf-------ivimctsi-----pivki
ycynsgkgkkvtsde-vkag-kglnadnrysvgfkqqavg-----ka--e
-i------k--laalgltkglmvhnlhdlvf--ltaeylgqdlaadggsk
dqlcakfye--gngtcphd-pkltrgatakdgtd-dgipel-----khal
nv------rvl---hdfnei-gk-n--gnrdmtgsyr-----------ip
vmyntfveacegrlgdlsvlta--dlnqdpv-srdlnc------aksl--
--sgkni----a---kkgplpm-ksy------alscwlvph---mg-g--
-d-mk--livilyalpfl---kkcl--gha-------------lkpgq--
---arrkfgnd--aghlqlettndlrsll-ggyggkmivslwvvvtkkag
gwrktkarvgv---gatl----tr--gg---y-----lkehsd-n-----
------lgktal--lsvy-tgqlglsffthehsyy----------gfqm-
--tyvfsvna-----eaeesftk-----elahsctgks---astn-gakp
-e-------qlngl---------isvad-tlek-kylkh
>node6
---ve-tkskgitssacy--ift---fl-lqrffq-e-nvgvlggkftad
krsgm----tg-------kspprk-l--fsrgytra--ldvllsfrg-q-
vggsa---valheskgsmvfprkq-tkniygadkdtg-lti---p-----
--qlvp-tdltngaqpm-lgamelifflnapwhfki-psg------asei
y--npkkgnmelaeave----------cpngqgikh---------gs--k
-l------w--vgglaqtenfrghgvr-ics--tsakykkhslkadgneg
sahcdpifs--glegcdhlagsvtlptssrhlks-qcmkkhspvtepsif
gr------s-----iel--vsed-t--a--dis---q---ll------ik
egydvmfnachak-------qasagldkefs-akdcec------------
segqh-l----l---klgpa-----d--------qpwhqeqa-vvggd--
-a-dslalnvklqcqpiapkcl---------------------qdsmq--
spgpg-rf-rr--rrqkmldvareikpll-egfg--------vc------
-----sg--lv---tkpl----nt--an---y-----mggeae--gpltl
------ttkpmn--ldmg-snl--ltsfrig------------pvatdt-
--wyq---et-----arhqsyh----------hgas-----aplk-tadk
-a-------gmdka---------sk-gg-pvwttslpvh
>node14
---vp-skkggatfficf--lftdnafl-pqqfyd-egdivvlngkfaed
trkglnsdlagfqgyggv----s-------rgpvng--leilqaqig-q-
tpatn---sgteeedssavfpegq-ttgalgkkm-dg-ndm---p-----
--a-sg-akltatgnpa-rrgsdlf-------vvilsvtl-----pvakv
ycyksgkgnkvtsda-vnag-nglnadtryavgimqravs-----gt--k
-l------w--laalglskglmvhnlrdlty--lpaeyldhdltadggsa
delcamffe--glgtcshd-gkvtraattrnanh-dhipql-----khql
gv------kql---hnfadi-dh-t--gniemtgtyr-----------ip
tsynsffqacegkltdldvlta--slqqesv-akdlkc------sktl--
--vgrdl----l---ksgplpk-nkh------nlncwlvphm-vmg-s--
-d-kk--lviilyclpfl---kkcv--va--------------lkptq--
---vr-kfkdr--sghlalettwdlrslf-ggyg--------vi------
-----tgrvgv---srtl----ts--gg---y-----lneesevn-----
------qskpsl--lsli-tgl--lslfnhe--------------gfqs-
--syvfqvng-----daqhsftk-----elaatctg-----adtk-takp
-e-------qlngl---------isvsd-hvdk-mllkh
>node3
---vd-akpagttsafsl--vftgeyfiaperflk-g-etavlg-gftqd
srkslksdfsg-------hsshsa-l--fgrgyaas--lnilaatrg-q-
-----------eekkgsgvfpvaq-tghlfgaskdtg-nhr---a-----
--qldm-naltkmgnkm-tkgleti-------hfki-psg------s-dv
yank----nrvvagp-e----------gant-girssv--------s--n
-l------w--mgglvtteqfrghair-act--ldavyashqskvegneg
telreafid--gaaacdhlsqkvtltattrhlkf-ncrdlh-----phia
gh------k-----itf--vaqf-p--a--slntphr---ll------vk
etynvmfnvcgak-------kaskllkvqfq-etellc------dtpvsg
vypqa-l--rrl---rl-pt-----h--------hewhtsqa-lmggd--
-e-dr--valmincqtyleqcl--vntfp--------------ansvq--
apgvg-ry-qk--naqlpvsa---finllehtfg--------tc------
-----gg--gi-dgtmpm----nt--ad---y-----vdslgdvigplkl
------ek-sgn--lemw-s------vfkvs--------------ssea-
--wylfplet-----hdqqayqk-----evtstcha-----aplq----r
-g-------amsqa---------kk-kk-avwhttlhkq
>node15
---ve-tkhggstssfcf--vytdeafl-pqrffr-e-divvlngkfaqn
trkglnsdfpg-----------s-------rgpvga--leilaaemg-q-
tggta---tataesknsavfpsgq-tknayaksm-dg-ndm---p-----
--a-sg-aeltnggnpa-rrgself-------hvii-psl------vskv
ycykpkkgnkvtmea-vngg-nglkgkkkhspgikqtvvk-----gt--k
-l------w--lgglvlstgfkghdir-lcn--ipaeymdhdltadgndv
nelctmffe--glgacshl-gkvthpatsrhinh-dcvtrl-----qkvl
gv------kql---gtf--iaeh-t--gdfemsspyk---dl------ip
egynsffnaceak-------qagtslqqels-akelpc------skpl--
--gghnl----l---ksgpapk-ekh--------npwhaphs-vmgsa--
-d-dr--lgtilycqpvl---r--v--va--------------lkpiq--
---vr-kfkrr--sghlalevardlrplf-tgyg--------vi------
-----sg--gv---trtv----st--gg---y-----adgesevsgpgsl
------etkpsl--ldls-tgl--lslfkhe--------------stea-
--syvfqves-----daqrdfak-----elaasshg-----iptk-takr
-e-------amsel---------er-sg-hvhnallvkh
>H
---aghkkkggttffnyy--lfsgshfl-pecwydgqdavaglegkyaas
trrglitslgamtefggv----s-------qgpvsk---elhqsqse-en
tptsg---sgkeeestpvvypegs-gsdsdgkkm-tg-def---p-----
--s-ga-aallnsqsna-rhgcall-------lvimcdai------kmri
ycyiagkgkkvssda-vkaa-knlnadhrylvgldnpavg-----ks--a
-l------srnlaslaltkalvvhnvhglvf--lpleclghdlasssesn
dhacgkfyevpsrgacpsk-qkltrvcnadeasd-dgkgel-----khal
dv------rll---hdfiei-gd-n--gkrdv-gsyr-----------ip
amygtftnvhkprlgelstlsa--eleqd---drehqc------aanl--
--agkni----a---kkgplpm-dsy------alncwivph---fp-a--
-d-qk--liiifyaqpfk---kkcl--ghppnkdpmhqrigtllkpgq--
---aradfgld--gghlqpnttndlasll-ggyggkmvvslwvvieqkag
gwklakarvgv---gatl----valhgg---y-----lkedad-a-----
------vektplmnlavf-tgqvglvffinehsyy----------gydl-
------nvst-----eaq--fnk-----elaha--yre---pstp-gdkp
-epnsgahrqlsgl---------ihgsd-tlnn-kylkh
>F
---vr-sktggpsfficy--dfkeemfi-pkqfyd-gad--elkgrivdd
agk-----lgg----ggv----i-------ptvene--letlnglir-m-
vpacepnpgaesgashvvvypgdi-ptgrvg-km-dg-ndv---k-----
--s-vs-tkltsnghsarsmgadvf-------gvilditldesptpsadi
ycykpgkgaktgsag-ihlgfhaldpqarygmgrmqktvapelgngt--q
gi------s--ltqlkiernlmvaglrdllh--lalqrithnlsadggaa
edpcamipn--gigtcsnd-gkv-rsattdetfh-khfpnm-----khnl
gs------nhl---hhfadl-dp-n--kninttqsfr-----------hg
tfyksif-----kl--lhvltt--siqhntlcsqsdkn------etql--
--vgqdi----v---n-drfnh-npr------nldk--vphmnvas-svw
kh-rk--li---yclpfl---qsat--vg--------------l------
--------lkq--sghlgleikwdvrtls-gg----------vi------
-----hgkdgt---arsp----ts------------------evn-----
------rnipsl--lkiv-kgv--lelfdhs----tlradthn--glksy
hagyqfqshgkcvandaqhsftn-----alaapcpg-----etlmctsrn
-q-------dlgtv---------hsape-htdr-mvakh
>A
---va-ahpsgttsaftl--rfagqryikperflq-g-etaitg-dfyqd
nr------fpg-------hstlpi-k--fgggysaa--ldilavarg-g-
-----------eekkssdifpval-tghlfssskdta-hhr---a-----
--qlhi-dslnkkghel-tmslnef-------hfti-prg------g-di
ytkk----nkivy-s-e----------gans-gvrcgv--------wfsn
-l------w--mgglvhteefrstgir-act--mdavytshqgkvsg---
aalrqalid--egaacdnlskkttlsatsrhlkf-dccdlh-----phsa
ghfttitya-----iaf--vaqf-p--a--sidtpnrtlalp------vd
gtynvlfsacgsk-------kdskllrakfq-nsella------dsptag
iytha-i--arl---rl-pl-----h--------qewqksqp-vqgdd--
-k-nr--lkilrhcqsyleqyl--intl----------------------
----------kitgaelpvat---fitllertfg--------ac------
-----gg--svkkgtmpm----ks--ehfcktdaksh-----eiigparl
sgnsaned-gks--eemw-s------vftva--------------stda-
--wylfplec-----hdlhvyqk-----evtsacqa-----nplv----h
-d-------amrqr---------kd-kk-hvwvtslhkd
>node7
---ve-tkpkgtttafcf--vfteedfl-pqrffq-e-digvlggkftqd
trkglktdfsg-------ssspsa-l--fgrgytaa--ldiltairg-q-
vggta---valqeskgsavfppsq-tkhvygankdtg-nnm---p-----
--qlva-adltnggnpm-lkameli-------hfki-psl------ssdv
ygnkpkkgnkvvaep-e----------eantpgikqtvvk-----gs--k
-l------w--mgglvltegfrghair-ict--fsaiyknhdlkadgneg
nelcdtffd--glsgcdhlpgkvtlpatsrhlkt-dcmkkh-----pnil
gr------k-----itf--vaqh-p--a--eisspyr---ll------ik
egynvmfnacnak-------qasttlqhefs-akelqc------sppvsv
sygqh-l----l---klgpt-----h--------hpwhasha-ivggd--
-d-dr--lgvklqcqpilekcl--vdtia--------------ldsiq--
spgvg-rf-rk--sgqlplevarelkpll-ngyg--------vc------
-----sg--gi---tkpm----ht--an---y-----adgesdvsgpltl
------etkpsn--ldms-sgl--lslfkve--------------stda-
--wylfpves-----haqqgyhq-----evtsssha-----aplk-tadr
-g-------gmsqa---------dr-sg-pvwntslvkh
>C
---vk-nvskgiaq-acy----t---f--lprfyv-e-kvgvlgg-fsad
prsvv----ag-------kslpaq-ltkfargyska--ldirlsvkg-q-
iggsi---vtlhetkpgmifprkqcsnnkfgadkdtg-ltr---l-----
--elhpcsdltngpqgm-lgamnlshfpfspwhyii-rsg------aqe-
n--spkkgdltlaetae----------cpngedike---------gt--k
-l------w--vagmaetehfqshkvk-vca--psakyskkdlkangneg
nahcdpvys--gldscdhlggsvtlrn-----tn-mcm----gvkqpgvf
gr------s-----iel--isev-t--a--kvg---e---ll------id
egydvmfsachvk-------dkgagqakifs-tkecvc------------
cea--------l---klgps-----e--------qpwhrdia-tiggd--
-a-dslalnvslacqpiahkcl---------------------qdcmq--
spgpg-rn-rr--rrlralqvtrafkplp-t--g--------vc------
-----rg--ll---tral----gt--tn---y-----kggkad--gplsl
------sikpmh--ahmg-snl--mvtfqvg------------pvtndt-
--wyq---eh-----sr---yn----------qaag-----pplk-tank
-p-------gvdktlspsnvqeqfk-gg-pvwrsglavh
>B
---vd-skpagttnaatmkevftpeylyalqrflk-g-dsnvlg-gftrn
srrshtadfan-------ngshsavv--fgpaygas--lgvlaaasa-q-
-----------dqkkgygtfatar-gallfgapkdtg-nhr---a-----
--qldm-dtlskmgnkl-aashekv-------hfkl-ppg------s-dv
wanq----nhvvges-e----------gvht-giyssv--------e--d
-m--aqsgw--mgglikaekldghavk-act--legv-aphasevdgddg
aelpq---d--gatacthlvqkhtlaa------------lh-----thia
gq------k-----qty--vaqf-p--g--alktahr---ll------vk
etynvmfdvcgak-------rssrllhvqfq-vlella------gkpapg
vspqa-l--rrlrvysl-pc-----h--------hswqtnks-lmgde--
-e-ep--aslmikc---ldqcl--fhtfp--------------ipatq--
a-vig-rf-rk--karlpvsa---finlldvtfg--------tc------
-----ag--gv-dgivpm----n----e---y-----ansigeaigalka
------ek-ega--lskw-a------vlkvs--------------tsys-
--wylfpltn-----hpqqayqk-----eitstche-----apeq----r
-p-------alsqa---------rk-gk-avwhvslnkn
>E
rdyvv-pknggsalficf--afvnrlff-prqfye-egtivvlrakfaen
qsk-----lsg----ggv----i-------pgpegk--lseltglignv-
cpaadnktgaaeeatgivpyagdv-stgrlr-kr-dgsnnv---k-----
--q-is-pllvadgnaapklgsdly-------ivilsltfkeppdgvvev
ysyrdgdgekvatat-vavg-eslg-enrygvgklekilspelangs--q
gice----p--ltarnlsralmvsgvvdls---lpvhymsndlaskgnka
ddtcamfsd--nlgtcshe-gkv-raattrsifh-rhlpkv-----ksgi
gv------mhv---hr------q-t--knidsaray--------------
isyhsff-----k--dlhilrt--plqknslcgrgakptdirevsdkl--
--vgqdr----l---snqrler-npp------slqcwlvphi-vkg-s--
-et------pimyclpfl---qhkk--aa--------------m------
--------kdh--sgnlglgttwdyrklf-tvig--------vi------
-----rgksg----------------g--------------akad-----
-------ps--l--lsyv-kgl--lgkfahs--------------gfrs-
--kyqfqsngkcvpselkhsftk-----al-gpctg-----ililcnkkn
-k-------dsnvv---------vsasa-alds-maskn
>node10
---vs-skiggstfficf--aftnqmfi-prqfyd-dgdivvlkgkfadd
qsk-----lsg----ggi----v-------ptpene--letlqglig-m-
tpasdpnpggtdeasgtvvypgdq-ttgrlg-km-dg-ndv---k-----
--s-tg-skltahgnaaprmgsnlf-------vvilsitldeppdpvanv
ycykngkgekvasat-vhig-hslepearygvgrmekavspelgngt--q
gi------s--laalklaralmvaglrdlsy--lplqymdhdlaadggka
eescamfsn--glgtcshe-gkv-raattrntfh-khfpqi-----khdl
gv------khl---hhfadi-nq-t--kninttqsyr-----------ys
tfyksff-----kladlhvlsa--slqqdslcsrsakp------ssnl--
--vgqdl----l---tnerlnr-npp------nldcwlvphm-vmg-s--
-e-rk--lvpilyclpfl---qnan--aa--------------l------
--------kdq--sghlglettwdvrtmf-ggig--------vi------
-----pgrvga---artp----ts--g--------------seve-----
------rnipsl--lslv-kgl--lelfdhs--------------gfqs-
--syqfqsngkcvpddaqhsftk-----alagpctg-----aalmctakn
-k-------eldav---------vsvse-hvdr-mvakh
>D
---ve-tkgkgfgssdcy--vft---fl-lqkvfh-e-npgllagnftee
kcsnm----tg-------atpark-l--fgrgytra--ldglatfrg-k-
vagia---nkledkkggavyprkq-nknivgcdkets-vai---pecile
sarfvp-adlnngqqpm-wgdmelifilnarwhfal-ppg------vsev
y--tqkkggmelpdava----------cpdgegikh---------gs--k
-l------w--vqaa----dyraagv---crhcasakykkhslqadgneg
vahcdptfa--glqgcdhlegsvrlpysgrnlkssqcksrhsqvsqpaif
g-------s-----vel--gseengpfa--dia---q---llstvrlcik
esyndlfnscqak-------qasaglnknfs-akecac------------
wegqn-lll--p---klgpt-----d--------qpwhcdqa-vvpgd--
-a-ndlnlnvrlhcspiapspl---------------------qdkmhvg
spgag-if-rk--srekmldvakgekpll-egfg--------vc------
-----ds--lv---akpvvali---------y-----mggegp--gelsl
------ss------ltkk-adl--ltsfsin------------pvaaas-
--wyt---ai-----trhdsyy----------hnas-----sqqk-tgdk
-a-------dfdks---------ak-gggttrtvslsvr
