>G
c-----gp-s---arf---pksat---cgsa-cqaqink----nvgcd--
------e-------ic-kcrl--heqaatr-----vg--vdqlcaea--n
eiaa-ycw-gqaya-i---tp------lmnak------ivnl-dfi---m
ykkrgselt---g---lvtgvls---------yqpiqaknsakpkpgpks
nqppesarleakqvsar-eagg-g------ihs-----ihqvehlvnggv
-----------a-lfacargvanlgasip---v--fvsvatklct-----
k-klfpgqlsgid--------------------lsatp-el---kg-fkp
lgaiengi--anlevhggkklqef--s--lvqkvafrg--------d---
--d-rffrlsarirvlvnrks---ka--vg-gyfskiammacpcn-----
-apsvld---------nvlhng--------wystks----asvrgnvrhp
lgsefng-a-----gdsffeclrtgtwdkelyp--ggkeqgsvlivms--
ylvgf----vc------------------snkshgcfyffigdnsflfk-
-vt--elpr-vnyn-ep-----n---k-----pfnvlpl-------ktsp
na--ay------hrve-cnnrf-t--dgp-----kl-k--kaeqtepe--
----tee--g-a-dvaleghgrkiage---eggkvpvtkfdgfttgthq-
---ekpskkg-klqvash-ss-f---t
>E
k-----hasr---tsy--------------vgcsvahnk----alvcf--
------d-------lh-rt----dhelqk------pq--dyllaeg---g
evgp-ycw-talmhpc---tdal----yktak------vfglgeflalsg
fkgknsgtnncvg---lvsgpld-cpgvnkklnvspns---ak---pvgh
nhds----lepknirsk-ndakkg------satst---fhqleksipvhk
-------vfskm-i------------pig---g--ftnl-i-ltr-----
tl--fkglvsclq--------------------gknapkei---ks-tkv
ttppagsiyshk-------------vk--ltesvkkkg--------g---
--e-dqkqlnaktitrdqpkd---iqiste-lyaitfntpictsv---sd
ttgtsvk---------avlgdvkflcdmdfwcvdqifcfg-v-rsratlf
lgtsfkl-t-----gg---------ffdv------gdkgk-----vrv--
ylggf----ts------------------svqmdafryslmgnkkflle-
kvn--hlsllfytn-ei-----k---i-----ffdgnhl-------t---
glcesfakqspatwig-ckvff-p--eyt-----lkdk--psfdanda--
----neevaawd-dwaldgfaqe--------t---p-aaikqfaagcvgy
afkn--qrts-sqeyfhe-aa------
>node15
ss---vle-r---lef---pk------cnaagcektvsr----qvdcpmc
capqded-------vh-epnl--kd-cekkpeygari--nshlsga---g
qvva-fcw-igqydai---aq------fltpk------ifglgaflalpr
fkgkgsgtt---gqsvsvtelvn---------hhtvmk---sk---nakh
ghpsgnislnpsdirdk-sggk-geqsvamvhags---ipevdnlcrtsg
-------vfckq-i------------pis---t--ftav-l-thr-----
alklfrdhrsaiq--------------------ltgvn-eitafkg-fkv
lgpkkygiwdyrle-----klqrfslg--lvlrvnaksfftmhreaa---
--d-krteqkakllvledpie---vs--lk-sypsklgefacpdg---kd
asgsred---------aglnsn--------wcgndpftvavrvtgsartg
lggsfkv-a-----gqcy-ecgrqgawei------ggkgw-----vrv--
ylvgf----yc------------------svkdhafqyvlitdsnille-
kis--alisaayae-ea-----a---k-----pfqalqls------t---
ppvtav------arvk-cnghf-g--ngp-----krdk--ntyandde--
----leevggsd-dtafdgysmevkee---tp---p-tdfvpftsgcrd-
---e--grgg-kqeytvq-pk-yqqat
>B
sp---vle-r---vdfrslpv------cqcagceydqgc----pvecync
vatdeen-------fq-epds--kq-c--knesavrv--nsa-pkg-kag
avlnsfcl-vdkfqke---td--ehfafv---p--skgvlgvgpasfllm
fnsygkgkd---gagpsiielis---------dhramh---es---rgvl
ghrt------pddfrer-i--s-reqaakvshagl---icqagglsvygl
h-----fvlcrhti------------elaksct--lpkg-h-vvk----k
niklfkderhsta--------------------lpgll-dltafta-ikd
l--krsrrwdfrla-----cykkftvg--maldfeiaianqftrdv----
--s-aktenkanilllahpvn---vp--lplesgaklgenacpankkaqa
gvrtaan---------adlkkt--------lvlgtayelavtvavtas--
--gsfas-a-----gapy-prkgekhwpv------gsrnw-----arl--
ylnayivaqy--------------------------dyv-dsepevlas-
isk--nlipaglee-ec-----q---r---wgpvmsyaap------q---
apwgla------vgek-cngvf-htsgev-----kqekelpnntnsee--
----vakvnkpagdllfikvsgetnqshadas---q-aqfpqfvvgcye-
---d--prs---kefalq-prnfk---
>node10
k-----lpcr---ady---ll------cqasgceaniak----alvcf--
------e-------ih-rp----dhdlqkr-----vq--dyllseg---g
evgs-ycw-cailqpi---teal----fltak------vfglgeflalsa
frgkgggttnsmg---lvtgpldscpg----lhvavns---ak---ptgh
khssdniklepknvrdk-ngekkg------thsst---fhqleksvvvhg
-------afsrm-i------------plg---s--fanv-i-lyk-----
plnlfnghvsclq--------------------gkdapkei---ks-fkv
mtpkagaiynyklvahflkilrsfevs--ltesvkqks--------a---
--d-neveltakvvtiddpkd---sq--lq-syattfntmacpsa---sd
asgtstk---------avlhdekfqcgrdfwcptqvfcfg-vvrgrahns
lgtsfkl-s-----ga---------nwdi------gdkgr-----vrv--
ylvgf----ns------------------svknhafryllmgnkgflle-
kvt--hlgllayan-ei-----t---k-----ifdgkql-------t---
atcesy------srik-cdvhf-p--egs-----mkdk--hsfdadda--
----ndevapre-dsaldgfaae--------p---p-tgfkgfstgcaay
afkn--grrg-nqdyfie-ak------
>node14
s-----lp-r---aef---ak------cnaagceahisk----qvdcs--
------d-------vh-kpkl--deqldkr-----vq--ndqlsag---g
evsa-ycw-igayapi---aq------fltak------ifglgeflalai
frskgggtt---g---litgvln---------hhtvqs---pk---pakh
dqpsaniklepsnirdk-nggk-g------thsgs---ihqvedlistng
-------tfckk-i------------pis---p--fanv-i-lyr-----
alklfkdhissfq--------------------lndgp-ei---ks-fkv
lgpktggiynyrleahfgkklqrfelg--ltqrvnlka--------a---
--d-kqveltpkivvledpkd---sp--lk-sypsklgtmacpna---sd
tsgtsld---------avlhkd--------wyatqvfavkiavrgsarts
lgnsfki-a-----getf-ecarpgawdi------ggker-----vrv--
ylvgf----yc------------------stkdhafqyllvddngflle-
kvt--qmtmlvyas-ea-----v---k-----pfqglql-------t---
ptcssy------arik-cdghf-g--egp-----kkdk--ntydtede--
----neevggrd-dtalegygtevkee---kp---p-tnfagfttgcke-
---d--grkg-nqeytvq-ak-y---t
>H
c-----qp-p---pry---amsvq---cnga-ceaqipk----slgcg--
------t-------vnekard--demadkr-----ia--andlcaek--s
atat-fcw-ldgyv-i---kq------ivkak------nfgl-efa---l
fkkpggalt---g---ls--vld---------whaisa---sk---pvkg
aegnesakleksnikdr-dggi-l------shs-----ihqvgnlegggg
-----------k-lia-------vslsip---a--fasvqprlreliss-
n-klfdghisafdayideqhadsidkpqdpppclteap-el---------
-skkgggikegrleasggkylqef--g--lnqk-------------a---
--d-rfiqltlkhavlinwkt---sa--lk-kyngqvrslthpsk---sd
ttgtlls---------gvlhka--------wyaskglavsitvrngprlt
ldnefkv-yvr---gdsflecvragawdknlaeafggkqr-----vkv--
ylvgf----vcrmaplwyfcrysgdkqkgsgkdqgcqyfligacgflfy-
-mtqadmprlgear-ep-----vgwyk-----pynvlpp-------gssv
pe--sf------hpik-cdgrfrr--ega-----kqdk--ssyhmepe--
----nde--g-d-eigldgfgrkvdae---ds---pvsrfegfadgcsq-
---e--skng-ksevaah--------t
>F
k-----lpir---ady---ll------ceatgceaniakdwklslvcf--
---------------h-rs----dhellks-----gq--dyfidsg---g
evgs-ycw-ckilqpi---spsl----fltak------vfglqeflstma
frgqgggtttsmg---lvagplescpg----lhvs------------tfh
khackniqlepksvcekgpgdkkg------thsaaktgfhqaqqdvvvhp
-------afdrl-i------------plg---k--y-------yl-----
pikff----nclk--------------------gktaqaei---qatfkr
mapkasslykyiliahflkimrtfdvk--lvdsvkdka--------a---
------veltptlvslnttte---sq--kq-tyadvfntmgspsa---se
aslkiak---------ailhdekypcgkd-wcpgevfcfg-vvrgrphea
lgtsyrl-a-----gk---------nwdi------gdksk-----trild
ylvgf----es------------------tvkd----yllmgnqafmle-
kvt--hiillalsn-di-----t---k-----lftgkql-------s---
asceay------prig-cdvhs-p--qadtfgttvtdk--hsfnaaca--
----kdeiaprn-dkdlk-ytag--------p---p-tgfsgfstgcdah
afkh--grrgdnteyfve-lr------
>node6
rs---ild-rgeangfdglps------chfpgcekghgr----wvdppvc
cetegevkpndvrsyh-qpnl--rs-aekkpeygarl--tsr-ggp-vaa
evvg-fck-vgrfqgl---ta------flakkr--tknvlplshflllpr
fqlkgsgkt---tstqevtdlvg---------hhkvmq---dr---nakh
gqptgs--vlpsdtrek-vsdd-iqrsiklshggs---vcevdklck---
hdnyhpf-fckq-i------------pqs---n--f-------kq----a
tvnlfkdhrdala--------------------lpgat-eiai-qg-iav
lgtgrdgvl-frmp-----rhqrfash--lllr-avsdffilkredaqns
idd-kkaqkkghilvlncpld---la--lkrsnrnklaefgcpdg---ra
idpgank---------advake--------rcpgeaysvaisiskssrkg
igg--kv-s-----gqcy-psnregnwpl------gtkgw-----lrv--
rlvaytgkvwc------------------vvnetaaelv-vsdsevllen
kis--dlvaagfne-er-----e---klrc--pfmslnaa------q---
tpvssq------tnaq-cngvf-g--ags-----ktdkelrdyadnes--
----ieqvtkpq-dtdfetnnmevsadrtpar---t-adivprvvgcke-
---p--gksg-dqeyglh-pr-np---
>C
ag---fls-tgdangfesspt------cdfvvcekghgs----wvdhalc
cdtenepkasdvrqkh-qphlakks-kekkhefgakl--asr-gap-ltl
aela-fcgevgrfkgl---tt------flakkrsrtkkvvafshilmvpr
fqlsgtgkt---mqtqqvtd-ag---------hrkvvd---kr---ngnr
g--agg--vlpsdvrpk-isdd-inrniflsqg---------dnick---
ndnylsy-lckq-l------------pqa---h--y-------kh----q
tlqlykqnrdsmt--------------------liatt-eiam-qg-igv
lgssrdstl-lrmp-----rhqrfactdqlilp-vardvfvlkredglss
fdd-kkvrkkehivaincplnvvkla--lk-skrsewseygcadg---ri
inplskk---------idvskk--------rcpasayrletsvsktsrsg
igg--kv-s-----hqcy-pafreenwpl------gtkgw-----mrv--
rl---tgkiwc------------------vvnetapela-vsdsevlldd
kis--dllasgfre-hr-----q---kvrc--pytalnaakrtrhaq---
tpvpsq------tktd-idtaf-f--aag-----rvdke-rdygdsnp--
----vnqvtksr-etefetnnkeas--rtphk---p-gdvvrrvvsckg-
---p--atsg-dqeyilh-py-qa---
>node7
np---vln-r---idfhglpt------chsagcetnhsr----qvdcpvc
ceaedeg-------yh-epnl--ke-cekkpeygarl--nsr-sgp-mag
evvg-fcw-igrfqgl---te------fltakr--skdilglaaflllpr
feakgsgkt---gqsvevtelvs---------hhrvmp---dr---nakh
ghptgsvsllpsdfrek-iggk-nqqtvkmshags---icqvdnlcktsg
ha-yqpfvfckq-i------------pas---t--fsrt-l-vrr----t
tvklfrdqrhalg--------------------lpgvt-eiaafkg-ikv
lgskrndvwdyrlp-----rfqrftlg--lvlrygvsnffllkrdaa---
--d-kksqqkakvlvlenpvd---vs--lkrsnpnklgefgcpdg---ka
ssrtpnt---------adlrkk--------wcagaaygvaisvetsarkg
mggcfkv-s-----gqcy-prgregnwal------gtkgw-----lrv--
ylvafndkvyc------------------svkdtareyv-lpdsevllq-
kis--sliaasyde-es-----e---k-----pfmalgaa------q---
rpvssv------aqak-cngvf-g--ags-----kqdkelhtytnsen--
----leqvsrpq-dtafiaynmevkedrapap---k-adfvpftvgcnd-
---e--grsg-nqeytlh-pr-yp---
>node3
sp---vld-r---vdfrslpv------cqsagcdydqgc----pvecyvc
cgaedeg-------yq-epds--ke-cekkeensvrl--nsa-pkg-kag
dvvgsfcl-igkfqrl---td------fi---p--skgvlgvgafsllpr
fesrgsgks---gqgpdvielvs---------dhrtmp---er---rgkh
ghrtgsvkllpddfrer-i--n-thqtakvdragn---icqvgglckygg
ha-y-pfvfcrl-i------------pfa---t--lpkg-l-vvk----t
tvklfrddrhaig--------------------lpgll-eiaafkg-ike
lgekrnntwdyrlp-----cfkrftlg--mvmefgiaifnqlkrda----
--s-kksqnkakvlllahpvs---va--laidnasklgenacpggkkaqa
sartaat---------adlkkt--------wclgaayevaitvsttar--
--gcfas-a-----gacy-prggeknwgl------gtkgw-----lrl--
ylnafnvagya------------------s-----rdyv-dsepevlvq-
kik--nlipaglee-es-----q---r-----pfmsyaap------e---
apvssa------vqek-cngvf-g--ggt-----kqekelpsntnses--
----lakvsrae-dllfiavngetkgehadap---k-anfvqftvgcye-
---d--prs---keyalq-prnyr---
>D
re---trd-rgeantiggspa------crfptcekaqgr----wtappvc
cstegevkrndvrsvh-hpal--rs-vekkkqfhp--------sgq-vda
qvta-ick-vgkgkgl---sv------f-atqr--dsnvlalshflllph
-hltgagkp---tgtqevtdiid---------hpkalq---ar---gneh
aqptqs--vlpsdtrer-vsde-itrsvflahggk---vcdvdplck---
hdnyhpa-lcke-i------------pks---n--l-------kp----a
tvnl---hrhsla--------------------hagat-eaai-qg-vai
lsagrdgll-yrrs-----rrprfash--llmk-vgagffftkaksfqqy
ige-k--------lvvacsla---va--pkrsgrnklagigcdde---rt
ikhgsgd---------advakd--------gcp------livipkvsrkg
keg--ki-n--rdpgkcy-magrhpgwsl------lnkgw-----lk---
-avaypgkvwc------------------cksetaaelv-eteseimlns
-----dltgagfselsr----------lkc--pwmslnld------g---
lpvtsq------tnakrcsgif-g--agg-----ktdrelrdyaadiagk
gtkvvgqgskpq-dtdfqaanieiaadstpar---t-sdivervvgckd-
---i--gkag-ldeyglr-pk-at---
>node13
c-----qp-s---pkf---aksgt---cnsa-ceahisk----svgce--
------d-------vc-karl--deqadkr-----vq--adqlcaek--s
evaa-ycw-gqayt-i---aq------fmnak------ifnl-efa---i
fkkpggslt---g---litgvld---------whpvqa---ak---pakg
aepnesakleasnvrdr-ngga-g------vhs-----ihqvenlvsggg
-----------k-lla-------vsssip---a--ftsvearlye-----
k-klfkghisafd--------------------lteap-el---kg-fka
lgpksngikdarleahggkklqqf--g--ltqrvnlra--------a---
--d-rfvqlnakivvlinrka---sa--lk-gynskvstmacpsn---sd
tsgtlld---------avlhka--------wyatksfavkitvrgssrip
lgnefkv-a-----gdsffecirtgawdknlip--ggker-----vkv--
ylvgf----vc------------------snkghgcqyfligdngflfn-
-vt--dmprlanas-ep-----v---k-----pfnvlpl-------ttav
pa--sy------hrik-cdgrf-g--egp-----kkdk--ntyqtepe--
----nee--g-a-dialegfgrevqee---ea---pltkfdgfttgcke-
---d--akkg-kkevaah-ps-f---t
>A
aavrvvln-r---gsp--lat---ggdv---gcqydqgc----pv-cfvv
cgaeedg-------yd-epev--ke-cekkadnevrvlqnsa-kkg-rss
nvlgafcf-igkfgrlrpeet------ii---p--nksvlgvsafallpr
fqsvdsgkg---gqghevvdlvs---------ehgasa---aw---rgth
shstgsvtvlgdqfrer-a--n-vdqtakaeragn---icq---lcvypg
hm-y-pfvfcpl-i------------qfa---taalpdg-l-vvk----p
tvklfrdkrrgvg--------------------lpgla-qmhsfkg-vke
lgdkrndvwacrlp-----cfpwftlg--mrmefniaifyqlrrdt----
--scnksest-nhlflfhvvs---va--lvidkasklgnnacrggkklks
ngrtqanhfarhcflgadl--------------gatyepaitisttvr--
--gcfagka-----aacy-pkggnknwgl------gakgw-----lrl--
ylstfelavya------------------s-----reyi-dsspahllq-
k-k--klipiglee-epadnvwa---q-----pfmsyaap------e---
gpgnaa------vkea-c-svp-g--rgm-----sqdkplasaniaes--
----lgkvskaq-kamfvsiagetkvehanap---k-sgfvqftcgcyd-
---s--psv---kdyalkapryah---
