>B
sgkk-iaitaht---nmv---------------eh-klewc-dksalyde
qveygg-r----q--gh----pg----vnaqsegipllne-----c--dc
--arllgedpavgppspfv-lsglegla-------ykrc--ktksi--ka
ehygvgwl---sqveclhmgkf--eql-nidlhikwpcaaqc-iqg----
--gggn-t-------gda-------------gs--l-ah-----gakea-
ydp-----------paattkfyn--kh-----kcliyi------frdg--
-----wlgng---asqilpstmgsskec-------l-li----fqfrnv-
---ameanq-svalhk-----------el-t--pp---teflfhlina-a
hnpgcvdpv-af----yleyql-------re---------c--ay-gpta
hmkhgevtlnvall-------llvk----------plags-----gag--
-lqydsadiplmeagn-------s-----nhddratryv--k-----slk
gmavpclkldlslyfgpgid-------ik-vc--v----c--------gp
t----s--avhlstidhpc-etigggllgvtkkwkivtr--ttsgndkay
gtlkt---kksvc-hecdqrlqrakll------qvaflve-------epe
ggaltipnikptgd------------vdqqkgvkegch-iespwmakn--
----trarigavcg-ycqqaipkrlmkigarhkghfcf----fraac---
------css--kkaclns---klplpgs----agsakk--fg
>node14
igka-lf-----ahtnsvagvgigvi-------ak-lltw-------yte
pvayndle----gcgsh----pk-gk---satga---lda-----c--ft
--akll---rsahnaraya-lggldymn-------ykrd--nvkgl--kt
spfgrgwl---pqsaslteeryy-ehs-gvnl-gkwl----c-fkt----
--td----dmnlgeksas-------------qaggk-qa-----iakevq
sna-----------phsceryfq--kapktantylvyv------fngst-
-----fvsdg---dggllagphqkksgcf------l-mftnlqynfcvv-
---alhtyh-tvqlhdgp--f----vlee-v--st---aelafevqgp-t
rrpiclast--y----llgfll-------km---------c--lr-----
----vplklwaklv-------khta----------slgss-----kgp--
-vqydsaevsplkagk-g--a-cs-----ya--qek-------------e
--pl-dlllrsyyyaskvlqtv----ile-gclsv----g--------gd
aanvat--dqhmpdmsehc-piggygtalihkrw----q--linttsvy-
-----------fa-ht-drsgiklkly------qkkfgivstskfrtdp-
--avagpkvrp--e------------lhghgafksacm-egsvyfadeql
hfikamqgta-----y------------cakhktnfal----ytaack--
----nscdy--p--hfnl---ketalgg----gkavip--f-
>E
iika-lf----------------gdikdken--fnrqltf-------gtg
pvahkq-g----gcssh----psaga---gvtea---ldt-----c--ft
--ekll---kkglhgsaya-laeleake-------t------vkgvlale
sp---awfhadpaspsgaddhys-ehg-gaal-gkkl------lrt----
--sy----alnlgekgay------------igaigk-ss-----igkevq
ivs-----------phsatrpfl--aggqkahaflvyv------lngss-
-----fiavf---hggllpgahkkkqgcf------ndkwanllfnycva-
---gikafkdslalcdgp--f----mleq-v--epkdranlqfdittp-t
rkpvcfahv----------fllqgnegckdrvvtgvvalrc--kr-----
----vplk---klf--pkaggshal----------skdgh-----es---
-iqyesak-splktlkdgcasccscsvtgyl--qdk-------------t
--pl-dgllksylyeptvmqtsvltqill-gclaf----g--------an
aedvtt--nhhvgemqdyc-piagy--eiihkkw----d--vasttsay-
---------------a-nrtaaklkhy------qkqfvvfapakfrynp-
--ivaapqs-p--e------------lggkvafktdtv-dsilyla-eqv
hfvmslrgkt-----f------------cav--shfaa----featck--
----ftcis--a--dlkl---qeeglgs----gtalv---t-
>node15
vgka-lf-----ahtnsvagvgigvk-------gk-lltw-------yse
pvaygdle----ecqgh----pn-gkemdsvtva---lda-----c--fh
--akll---pspnnasays-lggldnmk-------yrrn--kvrgl--kt
spfgpgwl---aqlarlaegryf-ehs-rvnl-ikwk----c-tkt----
--ad----dlnlgekgav-------------egggk-dn-----iateal
ina-----------phscekffq--ka-----tclvyv------fngsa-
-----fvadg---dspllggprgnssgcf------l-tftnlqynfsev-
---plhtyr-tvqlhkgp--f----vlde-n--pt---tdlafqvvgp-a
kipvcldpi--y----llgyll-------km---------c--ly-----
----gplklwarli-------khvt----------slass-----kgp--
-lqyesaeltplkagk-------s-----ya--qdthslicr-----nle
klpl-elllklyyyaagiinti----vlk-gc--v----a--------ge
a----t--dqhmpnmpqhc-piagyglvaiskrw----p--kikvtsmys
gvlrk-----via-htcarslrkvkly------qnafglvttpkprsgp-
--tvagpkirp--e------------ldhhgalksgcm-aesqwfaen--
----gmpkrg-----y------------carrkenfcf----yetack--
----nscdy--q--slkl---ketalgg----qkavrp--f-
>G
lgkvhmf-----ahgssvigpvfgil-------hk-ihdw-------sae
papytdlgvgvsgcdsdlvcgft-al---hstcv---leattylpc--fq
asakll---qsahktnayp-ltgldfan-------fkks--nvkgl--ea
epfgkgal---ppessltdpkav-dhdlgngl-nkwl----vgylafyvq
litg----dmdtnqqsgs-------------eagge-qpaahflihkevr
tgg-----------shhcsryfq--krttaanacgtlagfngtdfhegvl
lfgekwvget---eggllagqp-kkaacf------f-kftnlayktcii-
---e-hayd-svelhags--fknvltaee-v--pt---ddvtldaqgp-p
------akg--y----flgyll-------km---------cieha-----
----fs-kkwnklv-------ehsackhgmqlflislegsytspfdgn--
-vdyq--ektplra---s--v-cp-----yd--rak-------------e
--el-gllmkayyla-kgleta------e-gclnv----g--------gd
agavni--i------tlhl-ciggyksggihqcw----m--lyekkscc-
-----------fvnnt-nrsgaknrlflslstndkkyaaysr-nfrtgp-
--n----gchp--a------------lhthkvyk--cf-egnlyfadsqk
hfkatpqggr-----f------------cvklktefvlvadnftnlck--
----spcdl--p--sanlga-kdtalgs----gkeiip--y-
>node13
igkv-lf-----ahgnsvagvefgil-------sk-ihdw-------yte
papysdle----gcasn----ps-gl---patcv---lda-----c--fa
-sakll---qsahkaraya-lagldfvn-------fkkp--nvkgl--dt
epfskgwl---pqasnltdprfy-dhd-ginl-nkwl----c-ykkfiiv
lktg----dmnageqsgs-------------eagge-ea-----ihkevt
tga-----------phnceryfq--kvttatnayqiga------fqggt-
-----wvgeg---dggllagppdkksacf------f-kftnlqykacvv-
---e-htyk-svelhqgs--f----vaeq-v--pt---aeltfdvqgp-p
rrpiclskg--y----llgyll-------km---------cieha-----
----ialkmwaklv-------rhaa----------slgga-----ngn--
-tqyqthektplka---s--v-cp-----yd--rek-------------e
--pl-gllmkayyfa-ktlntv----ile-gclnv----g--------ge
atsvni--kqnmldlslhs-piggyasglihkrw----q--liekkscc-
-----------fanht-drsgvknklf-citssdkkygtysr-sfrtgp-
--skagigvhp--a------------lhthkafknacm-eggiyfadtqk
hflaavqgnt-----f------------cakhktefslvdekfttlck--
----sscds--p--danl---kdtalgg----gkevip--f-
>F
mtra-lf-----esshscvgigvgelkdkek--sk-lltw-------gtg
pl--ydlg----gcgsl----ss-dk---svtga---vnt-----c--ft
--gkll---kdahhdmlyavieqldtln-------n------vrgl--kt
kpf--awfkghpacvsfaedhyyfehh-gvnl-akfl----c-lpt----
--ah----nmtlaerpaylmlksdaeancg-gavgk-qa-----iggsvv
misllls-------pcacqhpfl--repkkssafllyv------lngat-
-----fisdl---nggllsgshqkkegcf------gpaykenlisfcgt-
---nlhtykdgl-lcdgp--f----lyktvi--sp---skvefaveaa-t
rrnicfthil---------yal-------dk---------c--kr-----
----iplklwlkfipnpkagpkysl----------n---v-----sa---
-tqyl--d-splrilk-g--sacscsgtgyt--eek-------------e
--pl-elllriyfycgavvkgstlmhile-gcvsf----gdqvestthgp
aesva----hctgdmpqnc-miggy--slvhktf----q--vvgtsdsy-
-----pwg-------t-dragvklkhy------qkqfavastakfptdp-
--avagapi-p--g------------ptghgtfkadat-kcrvyva-dki
vfvgalsgge-----f------------cqv--tdfwa----yaatcn--
----dscay--s--efal---qepilkd----gkflv---s-
>node10
igka-lf-----enthscvgigvgdikdken--ak-lltw-------gtg
pvahkdlg----gcgsh----ps-gk---svtga---lnt-----c--ft
--akll---kkahhgkaya-laeleamn-------s------vkgl--ks
spf--awfhghpaspslsdehyy-eha-gvnl-akfl----c-lrt----
--gh----amnlgekpay-------------gavgk-qs-----igkdvq
mis-----------phscerpfl--raprtanaflvyv------lngst-
-----fisdl---hggllagrhqkkqgcf------ndmytnllfnfcva-
---alhtfkdslplcdgp--f----llda-v--np---snlqfdvetp-t
rrpicfthi----------fll-------dm---------c--kr-----
----vplklwlkli--pkagikhal----------smgss-----sa---
-iqyasad-splktlk-g--accscsgtgya--qek-------------e
--pl-dlllrsyfyagtvmqtsvlkhile-gclsf----g--------gn
adsvat--nhhvadmqqnc-piggy--aiihkkw----e--vvgttssy-
---------------t-drtgvklkhy------qkqfvvvsaakfrsdp-
--avagpkv-p--e------------lsghgafksdtt-esivyla-eqv
hfimslrggt-----f------------cav--tnfaa----yaatck--
----nscty--p--dfal---qettlks----gkalv---t-
>node3
sgkk-isitads---nmv---------------ed-llewv-qqaalyne
qveygn-h----e--gh----pa-gkevdakatg---lda-----c--kc
--akll---pspgpsspfv-lsglegme-------ykrs--kvkgl--kl
shfgvgwl---sqvdrlqvgry--ehn-ridlhikwp----c-vqh----
--gggh-tsdnlaekgda-------------qsvst-ah-----sskeg-
yep-----------psasekfyh--kh-----kclvyv------fsdas-
-----wvgdg---tepilpsskgsskpctkyqgpsl-li----fafrqv-
---amepyk-gvalhk-----------eq-s--pa---ndllfhlina-a
hqpgcldpv-af----ylayll-------re---------v--iy-gptg
amkhgqlklnvsll-------tlvr----------plaas-----ggp--
-lqyetadiavmeagk-------s-----ehddtetryllck-----wlk
gmatpvlmlelslyfspgvd-------lk-gc--v----c--------gp
t----s--dqhlstidqpc-qvagnglvsvtkrwkvvdr--vtkgtdmga
gtlkt---gksvc-hecdqrlqrarll------qvaflie-------ep-
--tvalpnirptgd------------vdqqralkegci-aesgwtakn--
----tksksggvcg-ycqqpipsslmknesrhkgnfcf----frtac---
------cda--k--clks---nlpvkgg----agalks--fg
>A
sgkk-lsisads---gmv---------------qe-lldwlekkaplyhe
qveygn-q----i--gp----ga-akevsvktsg---lga-----s--kc
--akll---pshapnspfh-lsglagle-------ykrs--rgrg----f
shfgvnwl---sgvdrlqvgry--ern-rinynimsp----g-vqs----
--gdgh-tsellaingda-------------dsast-ak-----skkeg-
yea----ivlhineasasenfye--kh-----kclvyi------yndaa-
-----wagegyslvdpilqstkgwakpcskyqggsl-ly----fafhel-
---agepyk-svalhk-----------eq-n--pg---ddlkfrlidpat
hqpgcfkpv-af----yvgysl-------qs---------v--my-gppg
emkkgqlkllvgll-------klvr-----------laar-----gga--
-lqydtgdvvvmdagk-------a-----khedtktkyllckrdggnwlr
vmgtpklvlelslyfapgvd-------lr-gc--vaktsc--------gp
k----n--sqhlstisqrv-tvaghgfvviakrwkivhr--vskgtdmga
gplkt---gggiy-dqcdeplqrqkll------piaflve-------ap-
--naaltnqlptga------------ldqdrtlkggvi-vegswntkn--
----aknksngvcqnycqqpipvslmkdqcrqkaifcf----fktac---
------cvg--k--clks---dlpekga----vvalns--fg
>C
vsgg--------artevv-------------ddnr-linwt-kgyeqlsd
qvqf-k-e----hcqgv----pg-gsqvqsaaig---lea-----c--ic
--trlm---psptplgnfp-lgvgdgqgkeqlgrmygrs--alcav--ly
pd-gihwl---agkdcl--gry--ipq-rqhv-vkwm----c-tek----
--gdgk-dendlgekdsv-------------qgscgmsd-----iaqeal
tsp-----------pdhydkfyr--kh-----eclvyl------lnasp-
-----fasag---qrgllgss--------kf--psl-vkvkmkfpfaety
kqaaykiyl-piqinkgh-------ilq------t---vgllfalse---
-----wnpv-sydqggiinyil-------e--------------------
--------lw-all-------tlar----------dlhta-----ggp--
-leaqttaiatmrvga-------g-----sa--trsqtlvvr-----slk
khpi-ikl---ayyaatlpn-----------c--v----s--------ge
i----d--gtdfssrarhcaedagsglpvit-rwvgddqvyvskmaqdva
ssvsd---ekias-hn---rl-----------------------------
--avaaatleh--nvpgnislfknrsadsegsfsdpc---esewgsdd--
----alpmhvtacg-y------------dsrkkddlcy----fv------
---kiacks--d--kfke---trpemgg----kpekrt--f-
>node7
vgkg-ia-----artntv---------------er-llnwv-qqfalyse
hveygd-e----dcqgh----pg-gkevdavaig---lda-----c--fc
--tkll---pspnnasays-lggldgmn-------ykrs--kvsgl--kl
sqfgigwl---sqlarlavgry--ehn-rvdl-ikwk----c-tkk----
--gdgh-sdnnlgekgav-------------qgagn-ad-----iakegv
isp-----------ptasekfyq--kh-----dclvyv------fndss-
-----figdg---dspllggskgnskpciky--psl-vfvklqftfsev-
---vietyk-evqlhrgp--f----ilee-n--pt---ddllfqlieh-a
nqpvcldpv-ay----llsyll-------rd---------c--ly-----
----gqlklwvrll-------tlvr----------alaas-----ggp--
-lqydtaeittmkagk-------s-----ea--ttthslicr-----nlk
nlal-vllvilayyaaaqvn-------lk-gc--i----s--------ga
a----n--dqhlsslaqhc-qiagyglvtitkrwkavep--vtkvtqmta
svlrd---ekvaa-hncarrlrkarly------qaafllva--k-rtap-
--tvaapkirs--d------------vdqngalksgcm-sesewfaed--
----nmpkaggvcg-y------------esrrkenfcf----yqtack--
----spcds--k--alka---nqpamgg----tsalrt--f-
>node6
vgkg--------artevv---------------dr-lenwa-kqfsllsd
hveygk-e----hcqgh----pg-gtevqsvaig---ldt-----c--fc
--tklm---pspnslgafs-lgavdgmgpeqigkmynrs--qvcal--nl
pq-gigwl---adkshl--gry--ihd-rvhl-vkwk----c-tkk----
--gegr-sdndlgekgsv-------------qgvsdvad-----iaqeal
isp-----------ptpydkfyq--kh-----eclvyl------fndsa-
-----fagtg---ergllgss--------kf--psl-vlvkmhfpfsevy
kqavlqtyk-piqinkgp-------ilqe-sanpt---edllfelse---
-----wnpv-ayddvgimgyll-------rd---------c--ff-----
----gelklwvall-------tlar----------nlhsa-----ggp--
-leydtsdiatmkvga-------s-----sa--tatnrlvir-----tlk
nlpi-iml---ayyaatlvn-------lkpgc--v----s--------ge
a----d--ntdfsslaqhc-qiagsglptitkrwmsdqp--vtkmaqeta
svlsd---ekvna-hn---rl-----------------------------
--tvaasklqn--napgqytlfkkravdqegafkascm-sesewgsdd--
----empknvgacg-y------------esrkkeklcf----fitsckgv
vgyktpcks--k--klka---nrpqmgg----tpanrt--f-
>H
igkh-pf-----shgnsvagvefgil-------p---mdw-------has
tgsynqmk----acstn----ps-sl---patcl---lng-----chdsa
-spklf---qaadkarsfa-laal-ivn-------fktahgqvkgl--dt
dpfkkgwl---pva--lkdprfy-deq-vihm-hkfl----c-ykkiidv
lkst----dmnsgqdngs-------------df------------hkdvt
ggd-----------thvcqvyfrhakitsasnayqiia------fqgsn-
-----reseg------liasprdkkescy------f-pftylqyracsi-
---q-dpys-avrlhqgsvvf----vpeq-v--pl---tglvfdhqgy-p
rrptcltkg--y----llnyli-------kl---------cithcp----
----falkmwakld-------rpsa----------elgga-----ngn--
-tqfqthdstplkt---t--v-cp-----yd--rek-------------e
--ph-salmklyyfi-ktlstv----ild-gclnl----g--------gd
aasvnvkgkqnlfdlslrn-kdsgysaglihksr----q--lierkavc-
-----------faaht-trsglnsklf-cttpsdkkygaygw-firngr-
--skagfgvqp--t------------lhthknykracm-eggiflsdtqr
hflgpvqggv-----f------------cqghkdeftmadarhttlcn--
----sqadsecp--dtnl---knkslgg----gssvqpsgf-
>D
tgkg--------artqlv---------------nr-lspwa-kqfsflsd
mveydn-k----hsqgr----vg-gtevetkava---lat-----c--fc
--vqlm---ppsksigafk-lgrvdgmgptifnkmvnrp--hvcal--nk
pq-gigwl---kdkshl--aqy--lfd-rvhl-vgwp----c-tks----
--gegkggdadlge---v-------------qsvgdvad-----ivneal
isp-----------pkpydkfyq--rr-----lcliy----------ss-
-----fsgig---ervllgss--------kw--ssf-vlitmhfpfssgy
kqlvlqtyk-pihisnap-------hlqs-nanqa---eelhfglpq---
-----wnsv-sndevrimgyls-------rd---------y--yf-----
-------klwvail-------slah----------alhsa-----ghvlk
ileystsetatekiga-------s-----ta--tatkklvik-----tln
nlpv-imp---avytsnlvp-------lkagc--v----v--------ge
f----d--danftamlqhc-qiasaglptitkhwmlhqp--vtkiagets
nvfsd---qrvts-hn---rl-----------------------------
--slsanslqn--ngrgqyglyqkravdgqggyrascvqsedawgs----
-------vnvgact-f------------enrrk-klcf----iidsckgv
vfyktpcks--k--klka--wnraqmaenafdtvanrt--f-
