>H
ethhctgkt--kv-wlcg----aa-stli-v-ig-----caeyvh-lte-
gclrattkv----------------pgtefirg-apknaal------fsg
svpq-----lkaggdfpavlakk------laqgagvfmqkcrtc------
yctgkavv---------ee--vtqskv--vkds-----svcl-laqilrl
aglgt-fh--lgy--tssqtgs----adysgskgrf-vdnckvqac----
------smmheeqkleckygtpklaevmgstgafkahlmpqdsepag-tc
ripgsepttrwslenfk-aeqg-----heytsr-----qawcse---nmk
gfkla---f--pskqsv---ca------------------ngstknrpll
kafkakt--d-----r----llgaanas---ad-------ka-lsy----
rstmpyvldqystcvhgncm-----rng--------------------rl
-vpstaqeivggllkr-rdqhprvkg-k-gkpltylpkagdgca-----g
grglnrprgrrnpqgkvkgmi----------nlypvdgmtyslcahpgfg
if---afrkre------------pvqivwe-asprkvdmg--------a-
--------avlrv--mkysekvshqap-------ger-kkgdprceclir
y----fs--------fqlpg-----lghvlalfek-lrpkvivlksrsnl
sllkhy--g---skeliypns----nrnrsvksradlargvntftes---
--skd--ke--nehncsaqctg--------
>node3
ttrksygnp--kd-sich----rvyvkll-v-vl-----ktslvv-fldm
ldl----dvvklhrkshvedy----nsarfvkgltareagk------ils
gkse-----k--------------------itgac-lkkkssafg-----
fciihildyvphealiras--anekrs--gvss-----qa-------lrl
vglsa-fyrmpnf--gpge-ml-----aq-----s-----cnkqac---f
---llvgtlhghqgmlckfagkk--kmsas---dngnllmgtp-hsgvs-
--------lafdi-----pepke----fefekk-----itwasalgsegp
pykki---f--pnkgvgvntcay---ccncgtslgiglrghp---ardlf
dpkkpfa--s-------flnh-eqvesg---aad-----qti-ley----
kedkpsalh----crlklyr-----ppsyy----h-----dgmcm--mtg
flpnskqaf---pfnw-rhrdarmky-kagn------------l-----n
drgdd-a-----------sil----------rarale-------------
di---asdkkeq-------pegnsfwivwv-eat--eild--------e-
--------gvl----sty------eas-------nya-ksggtwci---n
dsiisss--------fpgkq-pvkkvhtelgffeglvh-ltvafkaenkv
gwfvftw-n---typflfnsg----ykrndv---sr--rgravgampytc
-dqrecrkg--hqhsclikctt--mkgglt
>node14
athhctgkp--ka-slcr----tv-aeli-v-vk-----sigfvd-mfe-
tcl----kv----------------hgtnfirg-vprkasl------fpe
sqah-----lgeagdapamlten------lvqgateymqkcrvy------
fcanrvvl---------kg--atekgc--pknt-----qeci-alivlwl
vglgt-fy--pnf--ttts-gk----gdestsrtrf-veqckpqdc----
------grvheqqqavcrfeapkksdvggfagqfkatllsvkq-png-tv
k--glqhntawnv-----aeqge----lefrkk-----tdwcpr---egk
gfklv---f--pakeeavktctn-----------sdetrgdgraktrslf
kahsikk--d-----k----hledaqts---vfg-----kdt-lsy----
retkpstknqyatcihgnym-----pdgf--------------wk--mkl
-spcgrqtf---tlrk-reqhgrvkk-k-pn------------m-----g
grglkqk-----------smi----------gaypit-------------
vf---sfhkrpl-------pesgpvrivwd-psh--qdmk--------a-
--------palrg--mky------hgq-------ger-kkvgtrca---n
ynttvfs--------fqvpg-----ldkeltifen-lh-kivlvkskanv
klikha--s---trdllfgga----yrenta---tdplrgvnasada---
--qrs--kd--edhnctynctg--lr----
>A
asrkeygnp--ke-tgcd----rgvvkll-vvvl-----ktslal-f---
----------------hvdky----kfarfekgitardagk------ils
akkp-----k--------------------itggc-lkkkstsfg-----
fciiyikdygvhaaln--ssqaaekrs--gpts-----qi-------lrl
vglsa-fykvanf--gage-ml-----aq-----s-----aekgpc---f
---livatlhghqkalckweglk--kmsah---dnrsllvgqa-nscvs-
--------eafgl-----peptq----fnfqkk-----itwssafgtegp
kyrki---f--pnkgigvnncay---ccvcgsslgivlrgrp---asnlf
dpkkpfv--t-------flsy-eqvesg---aas-----qtv-lpe----
kesrpevkp----cranlyrlgkkgpptsy----h-----egmcm--ktg
ftsganqay---qfnw-rhkelrmkh-ktgq------------l-----s
drgdd-a-----------nil----------lsrsle-------------
ev---sdntkeq-------pegnsfwivwl-gat--evld--------a-
--------gip----sty------aas-------nya-kspsswcl---n
daiigns--------fpgka-pvksvhgevgfvekl---ltvafkkenkv
petvftw-apagtypflyvnt----ykrndf---sr--rskaigamsytc
tdqrscrkk--hlhtclvkstl--mrgshs
>F
gghdctekp--is-slcr----pk-aela-m-ik-----dipfsn-lfq-
tal----ea----------------hpdgkirg-rl-kaml------fee
gqnr-----lsetgngeaklhenttsplglvqdakeyvqkcray------
ncdfrchl---------de--a-skda--tehg-----hdcilglvivll
v-----fe--rvf--gti--ehmyfvagdnrtrvcf-seassssec----
------divhseenalatfsggktieesgfankltsglt-vke-ahs-ia
k--gle---awnv-----ndqaemagqfqfkrk-----r----h---egk
afriilarfnkvpkeeevklcsk-----------dansradskaknrkll
grfefkkctk-----a----hlddahsavgsefghpqksgnt----vgkg
-i------------iegsyv-----paat--------------wk--irl
-gtcgsqsl---kvrr-qetlgkdka-r-an------------mcpctga
trs-----------------------------pypte-------------
af--lefkhrslkvawhashksgatqkvwi-apn--q-------------
----------lag--key------hgd-------gqp-srvgskcd---s
ydasmys---------------------dlgvasc-lq-rivlnkaksdi
kfvdh-------tqnlflgnvcepcnknntp---hnplhhidlstng---
--ers--kd--idh--stqckgwylr----
>node15
tthhcygsp--kd-nvcr----av-vell-v-vl-----kvgfvd-lfd-
lsl----kv----------------hstrfikg-vsrraal------ite
skah-----lgdagnaaailted------lvvgaadylhkcsvfa-----
fciirvlefmphdtagsdg--atekec--aaek-----qa-------lwr
vgmgt-fyqlpnf--atta-vk-----de-----r-----cnpqdc----
------grvhsqqqilcrfeapkkskvsgfagkektnllmtkp-png-tv
k--elqhhtawdv-----pepkd----fdfrkk-----vdwcah---egs
afkmv---f--pargeavkscay-----------gdeargnprakardlf
dakkvna--s-----k----h-eeaeas---vag-----kkt-lsy----
kdtkpaavhqyatcihkeym-----pssf--------------sk--mka
-rpcgrqaf---slrk-reqdgrvkt-k-pk------------l-----g
dgglkqg-----------sfv----------raspln-------------
ai---syhkrpl-------pesgslrivwd-pdq--qdmn--------a-
--------paleg--mty------hga-------gqa-kkvgtwcv---n
ysvtrfs--------fqvpgdplkklsteltifegllh-ktvlgknksnv
alfkha--s---trpllfggg----yrenaa---kr--rgrsagaspysc
--qrs--kd--hehncvynctg--lk----
>node10
aghnctekp--na-slck----st-aela-m-ik-----digfvn-myq-
tal----dp----------------hptgfirg-slrkaml------fee
gqaq-----lseggkgeaklnenttsslglvpgateyiqkcrty------
fcnyrvvl---------ne--atakga--pkht-----qecilaliilwl
v-----fe--snf--gtig-ek----adqnrsricf-aeacrptec----
------drthsnqhavstfaggktadvsgfankfktglt-vkq-ahs-tv
k--glqhetawnv-----ndqaevlrqiqfkrk-----t----r---egk
afrlv---f-kvakdeavktcsk-----------nddtrgdsrnktrkll
kafsfkkctk-----r----hledahtsvgapfg-----gdt-lsyigkg
-itkpstknhhaqciegnyl-----pasl--------------wk--mkl
-ascgrqtl---kvrk-reamgkakp-k-pn------------m-----g
gra-----------------------------pypis-------------
vf---nfnkrplkv---aspksgpvrmvwi-apn--qdlk--------e-
--------ralas--kdy------hgq-------gqp-krvgtrcd---s
ydttmys--------favpg-----ldkdlsvfsc-lk-kivlskakakv
kliqha--s---tqelilggv----ykpnta---rsplhhvdvisda---
--hrt--kd--idh--ttdctg--lr----
>node13
ethhctgkp--ka-slcg----aa-aali-v-vg-----saeyvd-lte-
tclrattkv----------------pgtnftrg-vpkkaal------fnq
sqph-----lgaagdfpamltek------laqgakvymqkcrtc------
yctgkvvl---------qg--vtqssa--pknt-----sdcl-aalilwl
aglat-fy--lgy--tttq-gk----gdysgsrgrf-vqqckvqac----
------grvqdeqqavckfgtpklaevmgkagafkahlmsvds-pag-tv
r--gperdtswsl-----aeag-----hefvrr-----aawcpr---egk
gfkla---f--pakqav---can-----------adqprgngsaknrpli
kafktkk--d-----k----hleaahas---ad-------kq-lsy----
rstmpntldqyatcihgncm-----pdg--------------------kl
-vpctrqeyvggtlkk-reqhgrvkg-k-pkplsylpksgpsca-----g
grglkrk-----------gmv----------slypvd-------------
vf---vfrkra------------piqivwe-ash--vdma--------a-
--------avlrv--lkysekkathaq-------ger-kkvgtrcaclik
y----fs--------fqlpg-----lgkqlaifdk-lh-kvivvksrndl
kllkhy--s---srdlvfans----yrarsa---tdllkgvntsset---
--qkd--kd--edhnctcqctg--ln----
>G
dtrhctskk--ng-sfcgitcdna-paiilv-rg-----taeyvgsite-
--lrdttkl----------------pgynfskg-vpkkaal------fdq
gqpv-----lagagnfpgisnek------laqaakvymqkcqav------
yctgkvvl---------qg--gsgtst--pkhk-----aecq-aaiilwf
aglat-fk--l-y--httg-gt----gnfagargrgavqhcnvqac----
------artqdeqqaickfgtskladvmgatgsfkshvmlvqg-pat-tv
r--spekg-qwpl-----aeas-----hepvrk-----pawcpr---egk
dhkls---f--gekqav---can-----------adgrrthgsgksrpii
ksfktkk--dssaqnk----hl-dar-s---sd-------kq-mny----
rstlpntfdqyaacihghcm-----pdg--------------------kl
-vpctrqeyvggslhs-keqhgrvkgtk-pspfsylpktgssca-----v
grglnsk-----------giefagtpqnpvssrypgd-------------
vvla-vftkls------------piqivle-ash--adma--------a-
--------gelkivhlkfsqrgaihaq-------ger-kkggvrcaslir
y----ss--------felpg-----lgkqlaiyeq-lh-kvivvktrndl
klikhy--t---kreliyams----yrakpa---ndllkevakanas---
--ekc--rdkaadhrctaactg--la----
>E
etydcadqp--na-slck----an-aela---------------------
-el----es----------------npksfshg-qyhktmi------fep
gqgs-----lseglkgeaklkehttsslglvpatasyvqkcrsy------
acnysvgi---------ve--atdqaa--pkqt-----qdcnlvl-elwl
v-----fg--nhfgpgtlg-ek----keptmsalcf-hescranec----
------dpkhsnqhavssftrgksqdvsgfanswkygst-vkq-ahs-ai
m--glqhdtawel-----ldqpevlrqlqfqrd-----t----r---dnk
ifelv---f-kvgadqasktssk-----------ndesaadsrnktrqll
ktfsfqkcka-----r----hlanahlsvgspgg-----aee-lsyvsde
-likatakqnhtscikglyl-----pial--------------fk--mml
-sncyrhtl---kirkk-eaamkpkp-t-pn------------l-----g
gkl-----------------------------gwpis-------------
vf---tftkhplkv---aspesgqvrmvli-lpd--qdfkkqqsyqmhdg
tfraelkarafan--kny------heeclvclt-gqi-krletrhd---s
ydtamytynkngtnqfaspn-----mdkdlhvfsc-lk-kivlskakgkv
tlieqk--a---nndlilg---------hse---rtpfnnaeviadp---
--qwt--eh--idq--ttdctg--lk----
>D
athdcfng-nr----v-s----cv-vkdl-l-gl-----khgmvi-ple-
laa----nvkkvhayqtiegye-----mtakdt-tarhegl------iaq
avae-----k--------------------isatcnfmelcaqlg-----
f-iikimkflpesavkseq--aqekvg--sftq-----pv-------lwl
vvlvgefckvpaf--dhgs-lk-----er-----d-----cdahgcgarh
---mlvgaihadhpllyk-----dak--ayaarehgdliyan--------
------------------sdtkn----frfddhieperiewqan---aks
kykdi---f--msrgqvvh---f-----------gv-----pre------
-----yt--n-----av--me-enclta---spk-----ktt-lg-----
---ppsaahpypavk--eys-----plafwcpnin-----pgtclcglka
-lpvkrqtf---dytk-rkldeeerv-khgg------------l-----a
aeginqa-----------t-t----------ppaqmg-------------
dm---myd---------------kykpvwi-eie--asqs--------f-
--------gml----tty------dph-------nts-tvatkhc-----
yvtpice--------ralfhtvihkeqsdkpllqilvq-lvvpfgfhvkv
sifiwew-k---scafhfasg----ykgaag---sh-----------ytc
--qpn--ka--kkktcsekcag--ekgal-
>node7
tthhcygsp--kd-nich----tv-vkll-v-vl-----kvglvv-lld-
ldl----kvvklhriqdvddyqvfkhsarfvkg-varhagl------its
amah-----k--------------------itgacdfmekctvfg-----
fciirilefmphetaares--asekks--aatk-----qa-------lwl
vglgt-fyrmpnf--dpme-mk-----eq-----s-----cdthac---h
---klvgsihshqamlcrfngpkdgkvsafaakekgdllmttp-png-d-
--------tawdi-----pdpkd----fdfnkk-----idwvah---ega
pykki---f--pskgeavntcay-----------gihargnpretardlf
npkkvya--s-----tlflfh-eqveag---vag-----kat-lgy----
kddkpsavhqytacrqkeyr-----ppsfw----t-----pgtcl--mka
-lpisrqaf---sfnr-rkrdarmka-kagn------------l-----a
drginqa-----------sfv----------rasale-------------
ai---sydkkel-------peggslrivwt-eeq--qtlh--------s-
--------gvl----tty------eaa-------nsa-kkvgtwci---n
ystaifs--------fevkeapikkihtdlpffeglvh-ltvlfknkskv
glfiftw-t---typflfnsg----yrenta---dr--kgrgvgshpytc
--qrn--ka--hqhncvykctg--tkgglt
>C
tahqcfatpakka----h----sv-vkeq-v-vv-----kvllvp---a-
lsv----kvtkthvvqevdgykvlkvsmkamht-htrhtglcplrveiqs
amth-----r--------------------inracvgmglca-fg-----
f-iirrvkflgqmnangai--piqkvfhpsvqk-----rv-------lwf
vsqeg-fvriatl--ehss-v---------------------ndgy---h
---alvgtvhvdhpalys-----dgs--asaarehgellmasp-pdg-e-
--------aswge----lndtkd----lrvdpktesdrad-------ttg
eykdi---h--v-lgqttt---ydlf--------gi-----pkdtasal-
nptrvfs--n-----alflfg-d-vlat---irg-----kcthpg-----
---------sflpredneyr-----paaiwcgkvtkgdylpctclasltg
-vdlfrqaf---dysr-rkiedtlrv-qdad------------l-----p
nslvnqa-----------s-s----------pgtalk-------------
ql---tyd---------------sfrpgwk-vih--aslh--------l-
--------evl----ktf------eve------cdsa-taskkwc-----
yetgivs----------lmhitvrke----pflqilih-lsvplkarkkv
glfiygw-k---tcannfgsg----ykhasg---dk--kliasggnaytc
---hq--kl--hhkdcsykcag--tkmalt
>node6
tahhcfstpakkdppvcn----tv-vkdl-i-vl-----kvglvv-sld-
lav----kvkkihaiqevdgyevlkvsmtamnt-harhagl------iga
amah-----k--------------------itpacdfmelcavfg-----
f-iirivkflpqmnanseq--anekvf--svsk-----qv-------lwl
valag-fcrvpnf--dhss-lk-----er-----d-----cdthac---h
---llvgtihadhpmlyr-----dgk--ayaarehgdllmatp-pdg-e-
--------tswge-----sdtkd----frfdpkvereriewvah---aag
eykdi---f--lsrgqvvh---y-----------gi-----pretarqlf
nparvys--n-----alflfq-dtvlag---ipg-----kat-lgy----
-eekpsgvhpylavkdneyr-----paafwcakvt-----pgtclqslka
-lpimrqtf---aftr-rkidakmrv-kegd------------l-----a
apginqa-----------s-a----------pssqle-------------
nl---syd---------------sfrpvwk-diq--aslh--------f-
--------gvl----tty------eve-------nsa-kaamkwc-----
yetaivs--------falmhttirkeqsdppflqilvh-ltvpfktrgkv
glfiysw-k---scafhfasg----ykesta---dh--kvrgvgshaytc
--qrn--ka--hhkncsykcag--tkgalt
>B
ttrkgynmp--ka-svnv----rvyvkll-v-vltnevqktslvv-fldm
lil----dsvrlhrkshq-dy----hscrflkgltsktagt------ilc
agcstikkpk--------------------itgac-lnatstafgddgqe
yctihvldyiqhhgliraa--ahekrs--glgacgfkgqe-------lrl
tglsa-fypmpsf--gpgq-ml-----e------------c-rsaa---f
rnellvvalrkhqgmlcpfagpm--kmpss---gdhhllvntp-hlgnh-
--------lafgi-----pkpke----frfeqk-----iahg-algiag-
-ykai---f--stkgvgvqscey---cctcgtdlgyslrgvp---ardlf
dpkspfg--a-------flkk-gqvqgg---ih------dta-gqy----
kedapsalh----crlkly------ppsyf----h-----dgeck--ktg
flehsketf---panw-hhkearmky-kggn------------l-----n
drgdd-s-----------sil----------rakslk-------------
ei---asdkkga-------qegssfwigwaadad--eiid--------e-
--------gvl----sty------egs-------syasksgatwci---d
dsilsng--------lpskr-pvlkshteigafgglia-agvafqaeskv
gwlvfvwps---syplifnsg----yktndv---sr--rgkavpgeslec
-drmecrka--hqhgallkctt--mkgglt
