>node3
nqkkdpgskv-haya---madgnlhtecveagkryleparp---y-----
------------tp-fa----ggskcv---kayrgl--enl--dqptggd
---------------faqd--lrtng-----ck---dgtvlea-----ss
--il-dgslar------t-drgeaadmkgit------hgkv-----kdts
gvtcykka---gareps----f--d------vs---hpgfdpiptsstgl
av-mt-qksrh-qnpipesst--n-----wpa--t--qgakadtlaganp
pksephva----r--sav-rkti-airffplalaag--------------
--arceg----aqs--g----gpqe--k---mq-dh-ee-------ygl-
-----i---na----------vaylg---ltkvwl--kglyalnsigvvs
vae-lrthq---edwhtkhqgatltpn--riksage--vagqlc-ygn-s
gednaadgav------navpk-gnhrcga------vrnfktwcedi----
--r-nd-fghrfkyqeqvlklrldvnfn-qlehsvqrctnalvlavswri
p----kenc-ddctgde-eei---vqalvpaaqk----atrpvh----mk
dlaflrnp-nts-vdlnvfdia--qr-sllerls-i-pl------evfrn
frg-r---------vvfln---sdgyk------------gcnpraaql--
nenkatvhadtislgdh-aaer-----------csds-------------
---aellkaanpvg---vvafv---acqnflhkl--kse
>C
nkkklthtal-lefi---kqpdglefi-vevdvqflvplkpqvqy-----
------------sv-la----ggarcv---kyikra--khl--erh-gst
---------------ised-rltat------ik---dgt---p-----st
--il-dggfge------g-vkghdpel-glp------tasv-----rgsg
qiniykks---nsatts----fkia------ss---npgy--vpvqgdkl
n---a-skpremkrpvsltpt--y-----wegpinlhagttiaalvgtng
fa-----e----r--kpt-rtgd-sicfllltlepg--------------
--hacqdwrivven--geaikfdaa--k---fh-dr-aglcl-----al-
-----v---ss----------nvflg---lakfwl--kglyevnggggvd
------rhg---qn---shagakfthy--tikkkndkqvaetltvygaln
tddsavhvgv--------ark-kcvwct----------------pmaany
--r-qd-igfrfswkqevlkleddacfq-heapavqkgvdtlakttgwki
vgvaqkdfavehcaksgvqhtngkqh------akg--ldareaq----vk
tlffl-atcttd-gdlgtfema--dr-pliehls-i-elnpvkpekeyke
frk-q---------vfflr---srgykpsft--------gcvprgmqn--
kevkpnverenympgtn-lgpk-----------sann-------------
---gg-----kpii---listv---acqaflarl--kas
>B
kkkkdpgsqv-hdya---ladtnlhtacvqavrgllepars---y-----
------------tpffg----vsgkcp---kesrgl--enl--dqptggd
---------------fa-d--kgthf-----vq---dgtalea-----ta
--il-tgrfpr------t-drgend-mkkit------hgkv-----khts
gvtcckks---gareks----f--d------vr---hpginpiptssngl
tl-mt-rksrh-aaplpessq--f-----wps--t--egakadtlagaaa
kktepqvvaiavr--asv-rrai-avkffdlalagg--------------
--arces----aqs--g----gtqe--t---lq-dl-ak-------lgl-
-----i---ha----------iaylg---ltmvwl--ksfynlhwiavvk
gse-lkshqlgkegwht----gmlspn--rirsggv--vavdlc-ygs-t
gepaaadgas------dmvnk-gnhrcag------vrnfrtrceni----
--r-nq-fghkfkyrkrilhlrlevkfn-eldlsvqrcsnvlvla-swri
a----kenc-necvgey-eei---vealvgaaqg----an----------
glaflrnp-htc-lelavydnp--kr-atlarls-i-pl------evfrg
fra-q---------vvfln---sdgyk------------acssratrm--
qikdgtvhvnsitqgnm-vseq-----------cggs-------------
---aellkpannvg---vcafv---ssqkflhel--rki
>node15
ne-------p-lsyv---kddddiafv-vsvgkrmleqara---y-----
----------e-tp-fs----gglkcv---kafrsd--shm--drhtagp
---------------feqt--ltaas-----ck---dgtaedg-----sl
--il-dvafth------s-ireeapdmknan------hgrv-----kgts
rvdcykkr---dnratn----vrir------ts---hpgf--vavsisdl
qi-lp-hk---fqkpipmtst--y-----wea--s--sgdivnilltahp
tlrkphve----c--svgritdd-migfflselgpg--------------
--atcgs----tkn--g----saqe--s---fq-ak-talclghpnsgml
vdtitf---ag----------vayls---larvwl--kslydagaagavs
vad-adyhd---qg---ker---mtlg--riksggd--vgglfcvkgg-i
ceesaahvae--------vpk----rcgs------hrvfgrwcyprpdhc
--r-ed-vghpyplkeqilslkedacfn-rnessvqrcld----------
---altqkvadqctedgvd-i------ftpsaelg--adthels----pk
eitflrmdetts-gdlevfeia--ee-kllfrla-i-il------qtfsr
frg-kteraa-pkliifl------------------------prslql--
neqkn---ldniapggr-fger-----------csdp-------------
---gdlrralq-ig---fvlf------------l--kvi
>H
sh-------s-msvm---rntghvafi-gplgrndfaeaqi---y-----
----------a-vg-fa----gglkcv---kafhsq--gqm--eqgstga
klkfhvllwnykfe-lqlsw-ltapv-----ciddkdelsedg-----gl
--vl-eeafkfkncvssn-vg-----lth-----------------qavs
qqdcakqk---khkgqs----isig------telyh-----------nal
hiidkdvh---fddpltmspv--y-----wec--s--rgsavnilms---
iyrlsn------s--sferltd--srafilsnlgrgv---ilkaclakfp
kldvcsr----lke--d----ts-idlpqgaye-kg-krfvlahvndsri
v-nvtf---agaecpvsyfhgvafih-lgigkywl--rpmyeggk-----
------yhi---qs---ka-----klg--rgregtk--vcglacvsdn-f
seqfvevdpd--------vikd---rkgl------hqvf---tfanknhc
--rgeelhahlwpekegfpslk-neclnaaapssadtcl-----------
----------ehcveggvr-t------ykpssslgts--ipsfc----ak
dnnflemregnadpktd---ig--nh-rivyrlavi-tf------qtfsa
frg-k-krynpaklvmfl------------------------psnlivla
leqgn---dddvippas-fggh-----------ctdp-------------
---gdavrdlq--gelmfiap------------nsfrie
>F
ed-------g-mdfvggrhnadglsfv-vpsartllqeael---yltwrf
fgcelemksrd-ig-ft----gaaeeekrfwefrte--sql--ehtksss
--------------glel----veakggtaacr---nragngs-----nv
ctif-tltfty------s-ss-----hptknhqaskkkerg-----sest
ktdvtkkk---ddrkeg----inih------aslhv-----------lev
-v-vn-hk---fqrplakcgg--f-----gre--s--aaq----l-----
-qkqphqh----c--evcklgivgskgfllcglarv--------------
--tkckn----amdms--------qgfs---yqasg-mglnett--snti
v-tdpl---gg----------igylechrltkysl--wavydggegaslp
vmg-agfhv---lg---sek---a-lg--rsqvnvg--icdmfclkvg-l
crhngargad--------i-k----pkgv------nrlf---ceaa----
----ed-ithlktavskfsgkrhhgclfstidsgmqtcla----------
---sl-vdpger--netan-i------ykptnnlqrp--tntla----fk
aggflridessdcsekqvinta--kp-rlaftla-vkvl------qsfsa
lrh-dsr--------vfm------------------------prrlva--
gskeh---lecvargva-fgehdhfglpskkieypd-ahsgtqlg-----
---aqilqeaq--gapkfvnf------------n--kik
>node13
sh-------s-msfm---hntghvafv-vplgktefaeaei---y-----
----------a-vg-fa----gglkcv---kafrsq--sqm--erhrsgp
---------------lklat-ltqpv-----ck---daaaddg-----gm
--vl-dvaftf------a-vk-----lnhah--------pa-----qavn
qdqcskkk---gnknqs----iniv------tslhr-----------nal
hi-dk-ih---fqdpltmspv--y-----wec--s--kgsvvnilms---
tyrlsn------c--slgritdhgssgfilsdlgpgv---vlkaclan--
--avcgr----vkd--d----msymalp---ye-sg-rslclahtnegri
v-tvtf---agaeapvsyfhgvgfls-ssiakywl--rpiyeggn-----
------yhv---qs---rat---gtlk--raregtn--icglfcvkgg-f
cehfgevtpd--------sik----rkga------hhvf---sfakanhc
--r-eelqahlwpgkdqfpslrsnecldsvvpssvetcle----------
---avgqnaadqcvdggvk-i------ykpsdelgss--vhsfc----ak
entflrmdegtadseldvieig--nq-rllfrla-i-vl------qtfsg
frg-kskryspaklvmfl------------------------prsliv--
ieesn---gdvvipaas-fggh-----------ctdp-------------
---gdvvrdlq--gdamfvaf------------dnfrve
>G
sh-------s-msfm---ektslcafi-valgkpdfeeaer---y-----
----------e-vg-lssd--gslkcv---gifssq--sqm--erhragp
---------------lkvta-ldqsv-----ek---epaadkg-----gm
--vl-taafaf------k-vk-----ldhah--------pm-----tlvd
kevcakkk---gnkypk----kniv------tslhr-----------nal
yv-dk-td---lkdpltlspv--y-----wec--s--kgsvvhilla---
kksid----------slgrfsdhsnsgfifadlgtfvlkqvmnaclss--
--nvcgr----vke--a-----vytavp---yd-sgsrslcvahkdcgrv
v-ikaf---ngaespnsyfhsvgfls-qttkkywv--cgqndggk-----
------ysv---qq---kat---gtlk--raregtd--iccvyykkgg-f
cvhfgnltpe--------dik----rkga------nkvf---sipkttyh
--r-dglhahlwagknqfttlratatlesigkdetdv-------------
---avgqiaanqclegnvk-l------vkpkdqlgkc--vhsfc----dk
entf-------adgeldvieig--dq-kllfpla-i-vl------qtfsg
ff----ksyapdqlvmll------------------------grsliv--
laenk---gdv-ipttsvsgg------------ctsp-------------
---gdpirdlh--gdamfvvf------------dtfr--
>A
nekkdpgspi-htya---mpegnlqtecieagkryltsfrp---n-----
-----------ptp-fa--agggkkcv---kayaglsaenl--eqptsgd
---------------iaqe--lrtng-----cn---dgsvlaa-----it
--il-deslar------t-hhaeaadmkgin------hgkvvdgaekdvs
gqtcadta---dareastsngf--d------ee---hegfhpiptsssgk
gi-mt-hksnh-hnkipprsa--nlglavwpa--n--qaiqa-tlagyhp
pkpdthva----r--tav-kkvi-siryypmtlarg--------------
--arckg----aqs--s----aaqe--t---mq-dl-da-------fgl-
-----nhmskt----------qeyla---lgqtwl--rglysmtelsvis
vae-lrgqq---edwhtkhqgasdikg--sirsdge--vaahlc-ygn-s
gedrhknggasvlrvphpipq-gshrcga------vrnlktwcesy----
rir-nd-fghkfryqeqvlklrl--sln-qlyhaiqkctealalavswei
p----kenc-d--tgdg-aei---vtklvpva----------------mk
dlaflrnp-n------nkfdva--er-gllerls-i-pl------enfst
frg-r---------iviln---sdgyt----lhgdalvpgchpralql--
teqkatvhartvslgdh-tser-----------csdn--------tkgad
tkltevlstsdpvs---vgafv---tcqnyllnm--knk
>node6
nekkdsqtva-lafv---kepdglifi-vevgrrflapakp---y-----
------------ta-fa----ggarcv---keirsa--khl--drh-ggt
---------------isqd-rliat------vk---dgt---p-----st
--il-dvsftk------g-irgqapel-glp------hgmv-----kgng
dincykks---asrean----fria------ss---hpgf--vpvqsnkl
dv-ma-kkprqlerpislsst--y-----weaavs--ngttidallganp
va-----e----k--dvt-kksd-svrffllklapg--------------
--apcea----vqn--g----ldee--k---fq-dr-aglcl-----al-
-----l---ag----------nvflg---lakvwl--kglydvnagggvd
iael-nkhs---qn---qhsgatltpn--kikksnd--vaedlcvygeln
aeenaahvgv--------vrk-scvrcan------vrgfkkwcypkaayy
--r-qd-igfrfnfkdeilklkedacfs-heepsvqkcvntlakttgwki
sgvahkenvvnsctkagveeitgkqh------pkg--ndtresq----pk
tlffl-dtcttg-gdlgvfeia--dr-plvkrls-i-alnpvkpdqqfkk
frg-q---------vlflr---segykpkft--------gcaprgmqh--
eeakpnverdnimpgth-fapk-----------ctds-------------
---ge-----kpvv---listv---acqaflahl--kas
>node10
gh-------g-msfvgsrhdadqiafv-vpsaktllqqaei---y-----
----------e-lg-fs----gslgevnrfrafrte--sql--ertkanp
---------------lel----lepk-----cr---dgsargs-----sm
ctil-elafty------s-vk-----hktahhqcapkpgrs-----tast
kvqcskkk---dnrkqd----inih------tslhr-----------nal
-v-vk-hk---fqkplpqsgv--y-----gea--s--agd----l-----
-vkqphin----c--evcrltdhgssgfllsdlgpg--------------
--ttcks----smdlp--------qgfs---yqasg-mgleethpdsgsl
v-tqal---dg----------vgyla-srltkysl--wpvydggkaatvp
vmg-ggfhv---qg---snk---arlg--rsqdnan--icdlfclkva-i
cehngsrdad--------v-k----rkgt------hrvf---caahanhc
--r-ed-vahlkpavdkfagkrehgclfstvessmqtcle----------
---al-qnsger--neaan-i------ykptnelvkd--sntla----ak
ansflrideateanelevvdva--ns-rllfkla-v-il------qtfst
lrg-knr--------vff------------------------prrlvt--
neken---ldcvarggs-fgqh-----------yadsthtptdlg-----
---aqivqqlq--gaakfvgf------------d--kik
>node7
nqkkdpgska-layv---kdddglnfi-vsvgkrfleparp---y-----
------------tp-fa----ggakcv---kayrsa--khl--drhtggi
---------------feqd--lkatg-----ck---dgtaldp-----sl
--il-dvsftr------g-irgqapdmkgvt------hgkv-----kgts
dvncykkr---gtrean----fria------ts---hpgf--vpvsstql
ev-me-qksrelqkpiplsst--y-----wea--s--sgdkidvllgahp
vtsephve----h--svg-kktd-airfflldlapg--------------
--apcea----aqn--g----hpqe--k---fq-dr-salclsehgsgl-
-----f---ag----------vaylg---lakvwl--kglydvnaagavt
vae-mhkhq---qs---khrgatvtpn--rikssdd--vagqlcvygd-n
seenaahvgv--------vpk-gchrcgs------vrgfnswcypraehc
--r-dd-ignrfnfkdqilklkedacfn-hlepsvqrcidalvkasawri
psvalkenccddctedgveei---qqsfvptgekg--sdtrevh----pk
qltflrnaysts-gdlnvfeit--qr-klldrls-i-al------eafrk
frg-r---------vvfln---sdgyk------------gcsprglql--
eeqkpsvhadniapgdh-fadk-----------csdp-------------
---gelvkaanpvg---fvafv---acqaflhhl--kve
>node14
sn-------g-msfi---hdtdnvafv-vpvgktmleqaei---y-----
----------a-ig-fs----gglkcv---kafrsq--sqm--drhkagp
---------------lqla--lteps-----ck---dgaaedg-----sm
--vl-evafty------a-vk-----lknahhecaaqhsrv-----katn
kvqcskkk---dnrkqd----inin------tslhr-----------ndl
hi-lk-hk---fqkplpmtpv--y-----wet--s--kgdivnillk---
tvrkphve----c--svgrltdhggigfflselgpg--------------
--atcgs----tkd--d----mahmsfs---yq-sg-malclshpnsgrl
v-tvtf---ag----------vgyla-sclakywl--rpiydggkagavp
vms-agyhv---qg---snk---atlg--rtqdgtd--icglfcvkgg-i
cehagahsad--------vsk----rsgt------hrvf---cfarpnhc
--r-ed-vahlypakeqfvslrdnaclnsvvessvqscld----------
---algqnsgdrciddavk-i------ykpsdelgkk--thtla----ak
entflrmdeataaselevieia--ne-rllfrla-v-il------qtfst
frg-knkrsa-pklivfl------------------------prsliv--
keqnn---ldcvvpggs-fgeh-----------ctdp-------------
---gdvvrdlq--gaakfvnf------------d--kvv
>E
gh-------g-lrfvgcrhehdqiafv-ivsa-allqqaes---y-----
----------s-lg-ls----gslhevnefsafafq--sqvspertkanp
---------------met----lqpk-----cy---dgsardgdsrengm
tnilkelgfty------hqvk-----pktgdhrcapkpers-----apss
qvqcarkkrqtinrkqd----idih------st-----------------
-----------fykplpesgv--i-----gea--a--ggd----m-----
-vkrgnik----cgheccrlagqgsggfll-dlapg--------------
--atcrs----smdlp--------qgfa---yqtsg-tgleet----asl
v-dqal---dg----------igylt-crlvkypgvhwpvydggkpgstp
vmg-ggfkv---qg---vak---crlavqraeekak------fclevs-v
cqedgsrvtd--------v-k----rkgt------hpif---canhpnhc
--r-qd-vvrlkravdkfagrrehgclf-tvegslqtcle----------
---al-kdtger---eadn-i------ykpsnelvkd--dwtllcgpnat
aktflrideatlgnnlevvdvt--nttslkfkfa-i-vl------ktfst
lqgvdnk--------nff------------------------p----t--
qekei---lecvargqs-fgml-----------htesthghtdln-----
---tnsihele--clvkfvgf------------l--knk
>D
degkdsetvsglssl---kepdglsfi-veagrrflspakp---l-----
------------pe-fl----gsapcv---tgirsa--kqs--nrh-ggt
---------------fsqd-rlvqt------vk---sgi---n-----ss
--il-nvafik------g-lpaqapel-glp------hamn-----rsng
dincfkna---asreas----frisliikltsa---gsef--gssqpkkl
av-pl-kapraldkpvaqsstlvi-----fpavvs--ngvtvdalqqadp
at-----h----p--rvt-kkgd-nv--fvlnlapg--------------
--avcea----vqh--s----vaee--k---lq-dr-agtc-------l-
-----l---aa----------gtfvg---yaklwl--kglyn--------
--------e---qk---qigassltpn--ktkkgnd--tsddlcvyahln
adanaarvgv--------srd-sclrcskawvactvkgfakkcytkaayi
--r-ke-egfrflyidtiltlkadacfs-hedvqtqk-anslaksasw--
sgvshkknvvngctkpdieeltgraa------fkg--skarepe----dn
slfgl-vicasg-gnlgvfevamkdr-pltkrls-e-krntvkpdqlfkk
rrg-l---------llflkptikegykpkft--------gceprgmeh--
ttvhpqverdnvlpgah-----------------tds-------------
---sg-----kgvi---listvrcfvclgfla-l--kns
