>node10
raffkklfagetqfghksg--saicmgengd----vhqnpgtkikk---v
rcnpkiqlflaspdlqsra-----------nngpg-defnsrapnaghwn
ggdg---m----pgvlmmleik-stq-----------et--ygycm----
-----------ci--ghkvgvgqgie--vaktkqqnvmmvrgiargekqq
v-pkg---gm------vatlmg--gncfskdapfslk-a-g--ckfthea
rv--lskvqcpge---------qqtsgllmarpsqacmlgeshskpv-sr
wgiycvl--cy-hkg--wllrgtqvsvssshpvfcaldsvhhiqgftpla
vff-----mfqmqck--------eevhe--rr-cietekk-----clne-
av-----raf------------k------kndacrklys--k-g------
--fglftpdv-hcpeqn--------------kqc---lesy------vkl
epaicg-------fvhgh---atrkpvqt-----------vpydnacasc
----r----dsilaiannciilqvkpeltrgsfawn--qsfkcnnvakia
l------------dp--lp-lrky--dnkkm-----n------vilvics
y-gtkg--fag---harvtrsp-htkhlstda-ytn-fgeiasvkvdnph
aasakenlgisegf
>E
raffkklfagvsgfghktg--aalclgeggg----vpkkpgpkvkk---v
sctkslqlffqspdltprt-----------tnspg-deyntkapfaghwn
egdg---m----pgllmlleih-gtv-----------et--yvycm----
-----------ci--ghrfgldphin--vdrseeqn----sgiargekqq
v-srt---gm------lanrmg--gnsynndipfsln-e-g----ithdt
kv--lsrvqcqae---------rktsgllmakpshacmlsesnsktv-sr
wglystl--cyphsg--wllrgtqvqgsaeapvfcslasaghsqgfsmvv
vff--------aecg--------deiqd--rr-cie-ekk-----cike-
av-----raf------------m------khescrkpfs--rcv------
--f-lsaphf-hcfeqt--------------kqc---legy------vrl
eltgcgayfiavnfvhgn---vtrkpvqt-----------vpydnaiatc
----r----dsiltlnepcimqdvkqeltvggfawd--ksmrcnnvpnls
l------------ds--lq-lrky--edrrm-----n------vtqvvcs
y-atkg--fag---hartvrip-hvkdns-----------------ddtg
apsaktevgiredf
>H
k--lkglflgpsaldqktglmpvissgegadqegkvhqvtgfkl------
schesf-hylktstehlrapaislwsastyyssat-lefadrvknattwv
gqag----------lm-qaeck----c-vesaiqsynqd--fkyc----y
viksekgkaalccaygakvgmskgmq--paiakkrnflvsrgltkgqpkr
l-lkl---al------ptv----------tdlafgf---qg--akfv---
rg--itklrcpgianggssaslkqsastlitkgnktpl-ddgqqkpivss
wagfcds--cc-hcg--k----adptlnpaqsnyckldvippnqgltktv
vft-----klprqkk--------gkgpq--kk-cahiaekl-k-ecaiq-
ap-----enf------------h------agdtccqsqh--d-t------
--lgltvssvc-cppqv--------------rac---igny------gkv
evckcg-------fyhsf---ttqrpittch----kschrvwadadpl--
----------snitehhdctrlqagahvrp--------mpftanp---aa
vl------------------ftky--aekktgky--q------nelllca
y-gtqn---gssgkpad------------tkadnas-fgtlhpdklnkpq
iatgke-lglsngy
>node15
ntffktlfagdaalghkpg--slismsnggg----vhhnpgtkikh---i
rcarkm-vfaklqaaqlr------------yegag-dlykarsthagtwq
tdsg---vv---psvl-nigck-ssac-vnpsgp-lpqs--fvfcme--y
ltkk-------cv--gthvglgigte--laeeiqqdlaltrdvvrgydcq
v-pkgaqkai------mavlrg--g------psfg-rnl-g--gtfifei
rgailnsvqcpnf---------qltagllmawptniclrgeghakav-ar
wseycnw--cc-ycsplwl---aepslss----yclledvqprqgfspli
laa-----kiqrsvr--------gtgpq--rr-cvsteekl-g-eclld-
sv-----ref------------k------kngtcskmrs--e-ggs-avi
v-malvtasv-lpptqs--------------kqc---leny------gkl
kpaktv-------fvkgytkratrnpikath----khcnkvsyedsplnc
----k----htdfsanhnctlfysaptitpvsfawa--vsfkcqpvknia
lal----------ap--ll-fvkr--edpkc-----a------knlvvcs
y-gkrgrc-na---ptqvprkr-ipkhmsvms-dtd-fgelpgeklsnvq
itgikd-lglgqaf
>B
----lnl-agtamygqeic--tlf---------------pg---kh---i
rcngkt-aa--------l------------yledc-elykekglkdsqwf
tdyerglpv---pnak-hlccr-qkgc-vkafae-ltkgyafafcvekkt
npkk-------ca--ainvgl-sgf----------dl-iag------scq
k-srgasr-v------pav-hg--q------hqfg-skl-p--dpgsk-i
rdava----cany---------el-tagvlspatndalkaqdheksg-ir
whlf--------lcarlah---tppslir----killdnkv----fppl-
vlg-----kk----isgmhkfkaksgte--gvdrvsndatl-a-ecplak
ii-----ctf------------p------rsgtchrlrs--g-nsl-pvv
l-m-----kv-lpteqr--------------kla---glfgtddyfgsll
klgkks-------fakgyskkssk----lec----h--neakyattapev
----r----dadfsahlgtelyyhapatlsvgvdwa--v---cqqaqava
q------------vg--lnvsgmk--icprg-----s------mtlrgcq
f-gktgrc-kl---l---rkkksiprsnavmh-sls-ysaladqglagfl
ctgqrt-lgvaeqf
>node7
----ksl-agdatlgheac--tli---------------pgrkikh---i
rcaskm-vfepvqsarfk------------ymgag-dlytsrgynesvwq
tdsgpglni---psev-higcr-ttac-vkpfge-lpqg--fvfcme--t
lnkk-------cv--gihvglgigyn--lakeiqedlaitrdvvrgydcq
v-prnsak-v------mavvqg--n------htfg-knl-e--grfnf-i
rdailnslqcvef---------kl-aepvmdwatniclraeshskav-ir
whiycdw--cc-fciplsf---aepslsr----kcllencqprqgfspli
lig-----kiqrfvr--------gkgaq--kr-svnnenkl-g-dckldk
ai-----sef------------k------kngscesmrs--e-gga-pvi
e-mtlatatv-lpntqn--------------krc---asyy------gkl
kpakkv-------fekgysktttrdrvkvac----rhcnkikyeisapnv
----s----haefsahlgcdlfykapaitsvglewa--vcfkcqpvknia
l------------ap--ll-nakk--avpkt-----s------kttvgca
y-gkkgrc-nv---v---prkrglpkemtvms-dsg-ygklsgeklssfa
asglkd-lglgqaf
>node6
----ksv--gdatlgheac--nli---------------pgqklkh---y
rcankn-vfspiqgarfk------------yggag-alftsrdfnengwq
tdsgpglnt---ptev-nigcr-kiec-vhsfge-lvqg--fvfcle--i
lsdt-------ci--gihv--gtgyn--aakeiqedhaivsdvvraydhq
tdprnaak-v------mav-qs--n------htfa-kdl-q--srfdl-i
rpsivnslqyvef---------kl-agpvmelgtkfclraaehnkav-ir
nhi-cqwfsci-fciplsf---neptlne----aclvekcqprdgfgplp
lig-----kiqklmr--------nkgah--kn-svn-atkl-g-scklda
ai-----saf------------l------ddgpcgpkrq--e-egpspvd
e-mtlvvalv-lcnkqd--------------kmc---epyy------gkl
kpgkk----------------trrdrilvac----chcdkiayeitspkv
edsvs----haafsahvscvlfykqpeitsvalell--aclssqpikgid
l------------ap--ll-gakk--qvp-------------------vs
f-gvkgkc-hv---n---pwkrglpkemttmn-dsg-ignlsg--lstfl
tsglkd-lglgrsf
>F
raffnklfaaltqfhqdkg--teilmgdnan----vppdagvkvrk---v
kcdpkeqlflasrdlqhrv-----------nnlpg-eafktrapsaghwn
sgkg---m----psvlnmvdvd-saq-----------tk--fgyck----
-----------ck--ghkvggvqgiktavsktkqqk-mqvrgiargekeh
v-pkg---gi------iatlmg--gncfekdtpfalk-d-g--skfqhet
rv--lsavlcpve---------deaagllmarkrhssllseshakpv-sr
wgiycvl--cy-hka--wllkgsqvaltssspvfgalvsvqhiqsftsla
vfy-----mfqsqvk--------kevheafrk-tnekeek-----st-d-
av-----raf------------kkrsdcgksnakrklyd--k-g------
--aglf-----hcpael--------------kqc---lhny------skl
etaicg-------fvhgh---ntvkpaqt-----------lpytnncppc
----r----nslvtiadncitmqgkpdithggf-wd--snlecgnaskia
l------------dpyylp-lrkypsenkim---gqnhgiefkviliics
a-gekg--fas---h---tsce-hhkqlstds-yvs-fgemn-vkvgnah
assgnenlaikegf
>node3
----lsl-agaaafgheac--tlf---------------pgrkfkh---i
rcsgkk-agepiqsaqtl------------ylgds-dlyrskglkdsvwl
tdydpglti---pspv-hlcch-ttac-vkpfae-lpagylfafcve--t
lskk-------cv--dinvgl-sgyd--iak----dl-ian------scq
s-srgsar-v------mav-qg--q------hqfg-nkl-e--gsssk-i
rdavv----cadf---------el-aepvmdwatnislkaeahektv-ir
whlycdw---c-lciplff---tkpslsr----kflldnsv----fspli
lig-----km----isgkhqfkankgtq--qrdsvtndttl-a-ecklek
ii-----cef------------k------rqgtchklrs--d-gsa-pvi
l-m-----nv-lpttqk--------------kls---atyv------sll
ktgkkv-------fekgyskdtskervkvtc----r--nkakfettapev
----k----kadfsahlgcnlfykapatlnvgvewa--v---cqpakaia
q------------vp--lpynakk--tcpkg-----s------mtlpgcp
f-gktgrc-gl---v---prkralprdltvmh-nlp-ygalsdekladfl
atglkk-lglgqnf
>D
----kai--gdatlgkkac--nrv---------------pgqkleh---y
rcsnks-vfsdipgawfk------------ysgag-allq--gfnvngwh
tdagv----------------a-qvec-vhsfge-lvsg--fafcle--i
lids-------ci--gvh---gtayn--sakgvqgehetaedvvkaythq
tgpqiaan-v------lav-es--l------hafa-kdl-d--srtdl-i
rpnivndlpsvai---------kl-agpvlplgfslclkaaqtlnaa-ir
shl-cqwftsm-fc--lsf---kepvlsn----avlvancpgregfgplp
lig-----kihksgr--------tqgnh--ks-sae-gakl-akncklss
gvsggavaaf------------l------dgapcgsrrq--e-edpspvq
e-mtlvaali-tctkldnav-----------kkcvat--fy------skl
kqgkk----------------krrdnivvaa----chckkiayeitslkv
sqkvsgngvyqafpahvscvmffkapdisklalrlf--scfrsqpiraid
l------------km--li-atka--qvp-------------------is
s-gvkafc-qa---t---pwnpglpkemqsad-nsgqfgnlsa--lstfl
kkgiks-vglgrsf
>A
----qal-agapafgheac--nif---------------rgqkfkh---i
rcgakd-ag-ptqsgqtl------------yqgsa-nlyiskalkdgvwe
akyepglsi---p-pv-hlcchdttgckvgarae-lpggylfgfcsg--t
ltkk-------cv--echvgv-tghn--agk----el-isk------ss-
--grgsar-v------laa-qaqaq------hhfg-ntl-emgsssfk-i
rdsvi----cadf---------al-aspvmdkatnialkaevnsktv---
-----tw---c-lciplff---vkaslar----rfllrksv----rvpvt
lig-----kt----vaqkhqikagkgps--qrdsptndsgvva-hcdpkk
vi-----sdf------------s------rqghchklre--n-vsa-ptr
l-m-----ni-lpsaqk--------------kln---alya------glq
ktglka-------fhkvftkengkekikvtc----r--nkakiqttpndv
----k----radfsahltcnlfyk-aavtavgvewassa---capakpis
k--rsgelgqkekva--fpynakk--tcpkg-----s------milpgcp
f-grkgrc-kl---v---prkrplarnltamh-hlc-y-nlreekfahyl
asglhk-nglgqnf
>node13
k--lktlfmgpaalnqktglmpiicsgqggd----vhqtpgsklqe---v
hcnesf-mflksstehlra-----------yssat-eafaervpngstwt
gqag---m----pgvl-mseck----c-apptvqsytqa--fkycmq--y
viksengst-lcvaygakvgmgtgme--paiekkqnllvsrgitrgqndq
l-lkt---al------psvlmg--gdcfakdlafgf----g--gkfarei
rg--isklkcpgf---------qqaagtlltrgndtcl-eeghnkpv-sr
wasycds--cc-hsg--w----sdptlnaaqtnyclldgvqpkqgftplv
vft-----klqrqrk--------gkgpq--rr-ciqteekl-k-qckiq-
ap-----enf------------h------kdgacaklqp--e-v------
--mglvtssvc-cppqs--------------rec---lgny------gkv
epskcg-------fvhgy---ttqnpiktch----khchrvnaekdpnkc
----r----lsnftehhnctrlhagatlapgafvws--mpfkanp---va
ill----------ap--lp-ftky--gdkktgky--d------vdlvmcs
y-gtqg---gscatpadvspqp-vakhvstka-nvn-fgtlhgakvtkpq
iagpke-lglsegf
>node14
ktffkslfagdaalghksg--siicmgdggd----vhqtpgtklkk---v
hcnskf-vflkssteqlra-----------ydgag-dafkarapnagtwq
gqag---m----pgvl-mieik-stec-sppvgptfpqt--fkycmq--y
likk-------cv--gtkvgigvgie--taiekqqnvmmsrgiargqnqq
i-pkg---am------aavlmg--gncfskdaafgfrdl-g--gkfarei
rg--lskvqcpgf---------qqtagllmtrptdvclrgeghnkpv-sr
waqycdw--cc-htg--wl---tepslnsaqavfclldgvqprqgftplv
vfa-----kfqrqrk--------gtgpq--rr-cvqtedkl-g-qciie-
av-----ref------------k------kngscrklhs--e-g------
--mglvtpsv-hcptqs--------------kqc---leny------gkl
epgkcg-------fvhgy---atrnpiqtch----khcnrvpyedaplnc
----r----dsifstehnctvlhagatltrvsfaws--msfkcepvkkia
lal----------ap--lp-frky--edkkt-----s------vdlvvcs
y-gtrg---ga---pahvsrsp-vtkhvsvka-ntn-fgelpgakisnpq
iagtkd-lglsegf
>C
----ktv--gdatlghegc--niv---------------psqklkh---y
rcankd-vfspiqgarfp------------ygggg-alftkrnfkkgnwq
ansapgant---svev-yngcr-kvec-vhsfge-liqa--flfcge--v
vdds-------cv--girt--dtgyh--gareihgehavlitvvktyahq
tapkrtak-vvldgislgv-qs--s------stfv-ldl-q--arfpl-r
rptilnslqyvpi---------kl-tgpvm--viklclraaerhkkv-lk
kqi-cpwfaci-friplsi---ndpaide----avlvdkcqprdafsplp
llg-----kadkler--------dkgph----------tgm-g-nckpdk
tl-----ka--------------------------hkrqkad-sggtpln
eimtliaamv-lhqkqe---pgifkkvnkggklc---epyy------gkt
rdgkr----------------rqrhailvpc----chcqkiqyqvcgpkv
edslr----ha--tprvacifflkqlnitevplall--acliaqpikgad
l------------a-------akk--elp-------------------vd
f-d----c-hv---d---dwkrglpedmtgln-asg-idnlrg--latfh
teslkd-tslaraf
>G
k--lkmlfksssalnqktgarptvcsnygsh----vqetpgskqeephvv
kcnesf-mylkncsahqra-----------ypsakkesfgdrvpksntwt
aqdg---m-tdnpgkl-mntcn----c-sppt--syspg--fiycth--y
viknengph----------gkatgme--paidklqnalvsk--trgrsgq
l-lkt---tl------ppvrnv--gncfdkdlpfgf----g--gkfaqet
kg--isvmkcpkf---------kqgpgttga-----cl-eeghnkps-gq
waaycks--cc-hsa--w----edellyspqtkyclldavkpkqgfaplg
vftmdyscklsrtrk----------gpq--rr-ciqteetl-k-qgkiq-
ap-----edfckvkhgdsttpgh------kaaacvklqv--e-v------
--tgvvgssvc-satqs--------------rec---lagy------gsv
nsskcg-------fthg-----srtpiktcrhvflknchr--pekkpekc
----r----latfterhkctsleagptvtpgafvwt--mpfkanh---lp
ill----------ap--lp-ftny--anqktgky--d------vglvmcs
yggvqg---gscaipadaapqp-agehapnrt-nvl-fsalhgakvtkkq
dagpte-lelgdgf
