>node13
a-palgaly--------vvasehl--lrvgreyht--ahcilnykkigpk
sira----------isghdtm----dh-------lpmqpvvnyhlpatyg
---eahlnlkspscamgkn--k-f---rhq------kykckigve---t-
fvr--kekkr-----snpc-----fqhsdignttmscnqd-gelacc---
-sdqhg--ggdg--------fgghwchdtqs---lmhfgyqva-------
tekgrarhpl----qdty--d-svyhgtfesdnksksfaennelpgkv--
e---nkicisn-dt-qc-gld-a--glv-----------------glt--
---s-yaf---kh-l--tpy-kqlsgdt-------a----a-g-------
------fsildlvtcdkpg----enhg---pk---ltiwl-esgkc----
------arl--epkgmkdl-arqassvg--tclq----harqtghhssss
gha--a-anfvgdk-a--rkwnpq--ilhlhaq-h----riqkfttqltl
saalv--etaq----vfvl--talcvg-rqkfffsgyhdavecealpasf
vesgelr-nlsg----res---y-------iggckermhg---eidsael
adilhsdvygslfprarclgq---g----------gmsvms-plh-----
----vh--pdtq------c-gagt--yit------qappvg------
>node14
t-palgaly--------llasehf--lrvgreyha--ahcvlaykklgpe
sirt----------isgsdtldrdtdh-------lpmqpevhyhlpgtyg
r-qeahlllksancslakh--apf---rnh------kkkckigae---v-
fvv--kckkr-----gqrc-----yqqvdipntlksckrn-g----f---
-sdmhg--gsda--------fgvtwchdeqs---llhfgylla-------
tgkgrdqhsl----pdtf--e-avfhgdfnadnksqgfaeenafpgks--
v---skvclag-gy-qc-gld-p--gkv-----------------alt--
---t-ytf---khas--tpy-nqlagha-------g----v-d-------
------frilemktcdksg----gslg---pk---ltlwl-vggkc----
------arl--sakdardl-trrasvvg--tclh----sakqtgrgpssg
ggg-ha-akfvggk-a--rnwqpt--ilhlnqe-l----pfqkfttqltp
sislv--esaq----illl--i----g-rekyffsgfhdavniislpasp
agtgelk-ktsg----kealhpy-------iggckermhg---vnakarl
ahilyaeeygtlfpstrclgq---a----------amrvms-plh-----
----vh--pdtk------c-aags--y-v------darpvggygedl
>H
a-palgevy--------evakval--lrvgreyhtsgphcfl--krvgpk
gthp----------isghntv----eh-------lemgptvnyhlpa-yg
---esdlglkgpscamden--n-fvadrqq------kyncktgvs---t-
fvr--s-krm-----yngcddpaifqpsdigsttlpcnqd-gqlgcc---
-aspns--sggg--------iaghwchdtqs---kmsfgyqvp-------
kergkarhpf----qatyald-avyhgqfdnsnmsrsfaqnndlpgrt--
p---dkicvsn-dt-hcpgma-a--niv-----------------gvs--
---sllsfkhekk-l--tsy-kdllgdt-------a----a-g-------
------yaildlvtcnnpr----qghg---pk---lsiwl-esskc----
------gri--epkgmrdl-prqassvg--lclq----harqtgnqssss
g----a-anfagdk-a--rkwnpd--ilhitaq-h----aiqiystqlti
dtali--qleq----aivl--talcve-rqnfflggyhdaaace---arf
gkagnlfqnlag----sds---y-------yfgckeiaha---yidstal
aeilhsdvfggllrrgrclgk---spvlevathtfgmayms-pie-----
----vh--pdtq------c-gkgs--yrs------happvp------
>B
-g---shyl--------lvpkssegspqakkeyla--lkcavlyfrlnph
agvr----------hsgweyleralea--v--s-lllpsk--ytknsayg
v-pelqg----ndcplkqhdeppn---stantkahqrrkskvqgq---l-
f-----c-ll---gva----------gida---saprpsg-g----y---
-aktaggagnep--------fgvtwcyvvqkpgklvnkeyyvgersk---
-hdgkplqhlgeghaqnw--g-niy--------------hckkyppkknn
v-----ialkacgy-qa-gvdatllk-mdk--gsg--g----myvnly--
---d-mga---knkt--vey-idlsqpp-------s---gg-t-------
------aksl-phqspraa----gp-r---mt---lkdwt--tgtgsgay
mgkpvassl--rpv----------fdsg--vgla----svrhitrsvpph
gas-av-sk-------fdrgylckchsqpllvk-l----tyskfvipase
gvavd--dgvy----t-----------kksmypyknlhplayvialsske
y----kg--tatfgll-----grckfkdrp--gcidkkqg--nyras---
-nqqatad-------tdrlag--ea----------kpdh-applh-----
----sp--prtrf-----r-gkarpfy-va----sgaaevggfgyem
>C
-ggdngnfcpaentpfgivlksha--lrkgrayl---akaavaygklgge
lrkr----------lpawvtlpraiqa--a--pllmaaak--yhqpgqyk
qilgvlgmttppncplrsk--gsg---rtra---yekcrckmgsq---v-
fli--na-tv---vlg----------gpsg---hcpcsaa-g----f---
-atvhgvsgeda--------yaviwcyniladerhi-----vtveetvcs
eedkkddhnl----ipaf-------------------------ykptt--
v--agelsfeiasy-dc-alh-aalhdtdhgggaglhslgfkhtvgirky
lcem-ydk---khts--vey-ydlcdks-------g---vf-a-------
------ir-lkfnteprgldsyvgi-ssafki---lrfwdivqktc----
------nsl--lvrqlrhl-gkkiaasg--ssla----gprqvtksva-h
gvafkevsklv---------wlak--ttplath-ldpdltptkysvplsk
eveiv--vall----pfsidqy----akktnfcfeglrqlayldtapsqa
i----lt--kpa----qdgf-gy-------lssglqteep--afktna--
levlfmesf---akpdqslasvdhs----------sart-v-plykqtrn
ttaayg--padk------hqgkng--f-sv----ptttcitgnfdal
>E
t-palaply--------l---ehh--a-dgaeysg--tdcsv-----gpi
aiqe----------vavggtlqkdvevpk-----valqpvayyhlagtyd
p-qqa-illmctsnykqkh--atf---knh------kpkcrikvitdlka
iavpvrnkkr-----sqrs-----yqptelppslnacdrv-g----flla
rggqhg--ksdh--------fdikwchshqk---llpflnlla-------
askgsdrdcl----pqty--e-lvfrgdfesaakeqglceqnafhvka--
ath-prttftg-gy-pc-aes-p--icv-----------------at---
---s-lkf---khhg--anh-dqlskht-------p----vld-------
------frylemetcdrsr----gkli---pk---itefl-aggks----
------arl--ivkggrdldv-raavvgvgnclhlasetakelfnnpang
dga-vt-aifdggr-a--rrwept------aqsyl----pyhk--pe--p
giqlttegslv-----hfl--t----g-vqtcgyaghpdavnlfplpagp
agsgelk-kkcg----qnathph-------gggcnaritg---rnvkgrl
arllyedkygaifpvqkclgt---a----------ekrvmg---n-----
----vn--pntk------c-amtp--f-v------y---vgsykqll
>node15
ngpatgnly--------llanaht--lrggrdyla--ahcalaynklgpe
airk----------isgwdtldrhtea-------lplapdthyhipgtyg
q-qsahllsqgancslskh--apk---rthttmetekkkckigde---v-
fav--kckkr---tlgqrc-----fqevdipsthkpcksn-g----f---
-skmhgvlgsea--------fgvtwcyeaqd---llhytylltethvaca
vgkdredhsl----tqtf--e-avfhvafdansksqgfnqsnafppkf--
v---gkvtlas-gy-dc-gld-pllsrvn-------------nvigli--
---k-yaf---khtg--vhy-ielakha-------g---hv-d-------
------fktldlktcdksr----gs-a---ak---iklwlvvdgtc----
------arl--sakdkrdl-trrvnvtg--vclh----sprqasrgpssg
ggg-ha-akfvksklt--rnwspk--tkqlste-l----afakftirltr
gvpiv--eatq----vlal--i----akrekypfhnfhdmvniitlpakp
n----lk--tpg----keslhgy-------iggcvdrtha--gykakarl
lhilyaeey---fkptrclgq--ha----------atrvls-plh-----
----vh--pdtk------c-gaas--y-vl----sdsrpvggygqel
>D
-ggddgify--------vppkshg--lrrghall---t-ceiayskvqpe
lrsk----------lpawivapralqg--vkek-mllaek--yhvaptyg
lildllglipspqcplkqh--pst---qaravedyekcacslgse-----
--------kefdcvlp----------dpsa---hgpipap-s----f---
-svqggaqgeed--------favarcyhvq--eklq-----ite------
-gdnkedhql----iepf--d-daf--------------qcsnfkpat--
v---gkltlqptay-ec-dlh-gafqktdn--gsglcsavyrvsvglv--
---k-fqd---kqtk--vew-sdlcdmv-------dltvvf-t-------
------yrpmdldapgkgl----gp-t---kt---limw----gac----
------tylaaldrrqryl-skkiavgp--enls----giriavrsvt-h
glg-aa-celirtrlf--mhwvgq--tiryltq-l----tietfsvklak
evalh--qnlf----lftl--e----ekkgryvfddlhelvykdpaps-t
y----gt--gpa----kicfqsy-------ilglvqasqpqg--ksratl
lavhyasef---kkpgqalstthrg----------gakl-d-pyhkpkrs
ttepyrdcpakt------hgeidd--v-sm----ttgtcvsvyaeai
>node6
-ggdngnfy--------lvaksha--lrkgrayl---akcavaysklape
lrkk----------lpawitipralqa--v--p-mllaak--yhvpgtyg
qildllglapspdcplkqh--psa---ktraameyekcrcklgsq---v-
fsi--ks-ke---vlp----------gpsa---hapcpaa-g----f---
-atmngvegeda--------favtwcyhiqtderlv-----vteketvcs
agdnkddhhl----iapf--d-daf--------------qcsnykptt--
v---gklsleatay-ec-glh-aalhktds--gsglhssvirhtvglv--
---k-fda---khts--vdy-idlcdka-------g---vf-a-------
------frsldlntppkgl----gp-s---kk---lrlwdivngvc----
------ttl--larqqrhl-tkkiavsg--ssla----gprqvtksvt-h
glg-ka-sklirtrlf--thwiar--ttqlath-l----tyatysvklsk
evaih--qall----vfti--i----ekkakyvfenlhqlvyldpapsqt
y----vt--gpa----kdcfqgy-------lsgiiesaqp--afktsanl
laihyagef---vkpaqslaatehs----------aarl-a-plhkqtrs
tteays--padk------hsnkaa--y-sm----ttttcvsgngdal
>A
-g---shfl--------lvpkafngtpq-krdyla--lqcvllflktgpq
ffqt----------rsdsgvldhalea--v--s-lqlpae--fivngaag
l-lqleg----ancplke----------agptvdhekkkckvaaq---v-
fs----c-rf---alg----------siqd---htpkpnns---------
-gsksgglgkpq--------fdsvwcynvqnnarlihkvyyiversk---
-qe----hhl----iqfw--d-tll--------------qrskyppka--
v---gnvalkgsayc-----i-cllnqmdk--esa--g----hivalv--
---d-fvt---rhkn--lqy-ielgqsv-------g---kv-d-------
------tkrl-lhlslsss----gp-r---kd---lklws--aacc----
------tsl--rvkayg------pygsg--gglp----sesqsergggpn
vak-ha-sk---------rtftvk--tqpflvr-l----kyakp-isvgq
gvgvd--dgvn----c-----------kktkypyeklhvvtkviwvnakk
y----vt--apdfnll-----gq-------avactdktqg--ickts---
-hdhsaad-------ketlce--eg----------kanv-a-tlq-----
----nl--pktr-lsklsk-gkdr--f-vitldktgtraiagfgrnl
>node10
s-palgsly--------lstnehh--v-vgseytg--ahcvlnyklagpe
tire----------ipgsgtlekdvehpk-----lpkqpqvhyhlpgtyn
r-qqa-yllkctssslqkh--apy---rnh------kkkcrigtvtqlva
iav--rykkr-----girc-----yqqielpttlkscdrn-g----fllg
rggqhg--gsda--------fdvtwchnqqk---llpflnlla-------
tskgsdrtcl----pdty--e-vvfrgdfnsqarsqgiaeenafpgks--
v---akvcltg-gy-ac-ged-p--grv-----------------at---
---s-htf---kqhg--tpy-dqlskha-------p----v-d-------
------frvlemktcdrsg----aslm---pk---itlfl-vggkc----
------arl--avkdgrdmetrrasvvg--nclhkasesakelgrgpnsg
sgg-ht-sifgggk-a--rnwept--ilhvgqs-l----pfqrlvpe--p
piqli--dsqn-----hfl--i----g-retcgftgyhdavniiplpagp
agagelk-knsg----kdaqhpy-------tggcterlhg---vnvkarl
srilyeeeygaifpaqkclgk---a----------dkrvmg-plp-----
----vn--pntk------c-aaat--f-v------yqapvgsygqil
>F
p-aplesly--------lctegqr--l-vgceytg--aqcvlnykle---
-----------------sgsmyknvilpk-----lpkqpqmhyhlpgsyh
h-rqa-hllkcnvsqvekh--apn---rnh------kkkcrigt-telsa
cga--kyqrk-----gkkc-----yqlvelpttlrscgrn-g----ylgg
rggang--gsdqarsivdlcfsvtwcaepqp---hlpykelik-------
tsietsstcl----ssty--e-aifrgdqdstapsqgiaeggsapgkp--
m---ykvcllg-gy-ac-gdg-p--skv-----------------gt---
---n-htf---kqhpnrtpyedeldkha-------p----v-n-------
------fkvlemmvcdrgd-----alq---ds---islfl-v-gkc----
------eql--agkegktietrtpnvvg--nclhkatesgkefgqgp--g
sgg-ht-sifgggk-s--kawdpn--slhagqs-l----pfkffven--p
pirll--efhs-----qhl--v----g-kevcgftgghdaihtlnisngp
agsdemk-ksss----l---rpf-------tdgcteifhg---anikarl
kqilyeaelgpilpaqkilek---a----------ekrkqg-pls-----
----ss--lntk------c-aatt--f-v------yhalagsygqil
>node3
-g---shfy--------lvpkayegapqskrdyla--lkcaliyfklgpe
afqk----------hsgweyleramea--v--s-lllpak--yhiegayg
l-pdlqg----ancplkqhdeask---rtgttmdhekkkckvanq---v-
fa----c-kl---alg----------sida---haprpng-s----y---
-sttngglgnea--------fgvswcydvqnherlihkeyyiversk---
-hqdkenhhl----vqtw--d-tlf--------------qcekyppks--
v---gkvalkgcgy-qs-gle-tllnrmdk--gsg--g----kvinlv--
---d-yga---khks--vey-ielaqsp-------g---kv-s-------
------tksl-lhqsprsa----gp-r---kk---lklwt--ngtc----
------tsl--rakaha------pyasg--vglp----sgrqstrsvpph
ggg-qa-sk---------rnyqik--sqpllvk-l----kyakftiplsq
gvgvd--dgvh----v-----------kktkypyenlhaltyvisvpskt
y----vt--tpafgll-----gq-------vggcidktqg--nykts---
-hdhsaad-------tetlae--ea----------kakv-a-plh-----
----np--prtr------r-gkar--y-vi----sgtraiggyghel
>G
a-ppfggif--------hvskqgl--lrvnqefhs--seci--ykkigpe
ai-aaksapcqnavvsghesl----dk--------qmqpivnyhvpt--a
---taqvnlkspscgngkn--s-f---rnr------kytcnagvk---e-
yvk--kkkrr-----ampc-----fqhsdignttltcded-gelgcc---
-aaqag--v-----------fsgtwchdtqs---lqvftfpia-------
tqkgrakhpf----inny--elsvyhstfdndnnaksfrsgne-pgqv--
d---nkicvak-dt-qc-sla-a--glc-----------------avt--
---s-yaf---ph-l--dpy-kllsegtqdnvakat----g-allasnda
sifskkfsilemvicdapg----enes---atdttv-rwv-esdkc----
------afl--evngtgal-trhlstvg--sclq----harqtghh-ass
gsa--a-aniagqk-s--rkfkdq--klhfhgq-y----rveelgiqltl
savmi--rtadlhqgvfva--ttlcvg-pqkffsngyhdavqceklpshf
vesgelr-nlsg----tes---y-------iggcrermgk---avdtpnl
dhilhhdvhgglfpraqclgl---a----------kkglms-prh-----
----vn--hgtq------c-eets--yit------qahrig------
>node7
-ggdngnfy--------lvakpha--lrggrkyla--akcalaysklgpe
airk----------isgwetlpratqa--v--t-mllaad--yhipgtyg
q-qdlqglsqgancplkqh--apk---rtrttmeyekkkckigne---v-
fai--kc-kl---alg----------sada---hapcpsg-g----f---
-stmhgvlgsea--------fgvtwcyhtqnqdrlihytyyitekskacs
edddkedhnl----iqqs--d-tvf--------------qcnnyppks--
v---gklalagvgy-ec-gld-tllnrmds--gsglhgnvkrqviglv--
---k-yga---khts--vny-ielaeha-------g---nv-s-------
------fkslnlntspksq----gp-s---kk---lklwsvvngtc----
------tsl--rakdqrel-tkkinvsg--vcla----sprqatrsvssh
ggg-ha-nkfirtrlf--rnwiak--tkqlatd-l----ayakftiplsr
gvavd--qavh----vftl--i----akkgkypfenlhnliyvisapskt
y----vt--tpa----kecfqgy-------iggcvdktqg--gyktsarl
lhihyaaey---fkptqclae--ha----------aarv-a-plh-----
----yh--pstk------r-gkas--y-vi----sntravggygqel
