>C
fwhgrdpv---k------kggkvevvsapkitm-dqcpgvtl-qte----
khp----e-qal---------------igv---tvqqhg-----qlglti
-l-------e-eglklynglel-lesatcwnl----ms-qsl--ceh-ll
alpstatprkeanvpvtnv-kkhk----nggeeasaqlnda--afsnaya
kaipgyk------------cltak-e----htefe--igffkkfta----
ylskmy-------ggtnrfdr--avvvsvlkferffgel-----------
---gnlrl---rda--gqe-angpiq---pegtp--slqy----------
llsp-------------ht---rvlevtarrvlafslfistpl-gafcqg
dnskakiageleitg-cqygkhl-ttgnpqcaklmekaf---------la
rirltcnpiclaagpicsad---vhsvlpknegtk----egygrwpfeyt
p--c-glptdeskankkcyv-khdq-------------kmsg--glta--
a----lq---gypkhcp----mdcrv-snstlsaiheymgtyfd--vqth
aniklhpt-lg--c-leyelfaeksa-tdwlglevda-ptdvktfyad--
--lkssqavrl-sgrfm----------dpgkasfkavk--pkivs-----
d-d---kd-----frpcfltevpkgv-h------------dgnk-vrfhp
-v--------n-----c
>D
fwee-tpf---skqaemstsgnaepvaahridm-edcsersd-qag----
rip----e-esl---------------vgsrea-tdehgliwlyplsllv
-v-------d-elltvfkglql-qasgacwpl----kn-tai--ckyh--
-ltn----ihqgnvagdkm-rkhs----kstedqsaeaidp-----gcya
kakpsyi------------ci-gk-q----dakfd--lgyfspita----
pfagml-------g-vdrfds--svlqgilkfekyygtl-----------
---gnlal---rdf--pqi-vnggvk---sestp--sigy----------
ilat-------------va---tvvta----------fltapv-gpmsqg
hhprsklngdleisa-teygkgl-vlanaqctlfmekpl---------la
lvreschtltmaanpvgtse---vhalvpgkedtl----ee-------yp
v--c-gihnnacraspkcyv-glddntwmsgtp--hagtant--hles--
t----ap---gyrkrcitsiqmhdrl-sgf-lneihgnqstefs--tkah
aalrkqpt-ka----deydvftq--v-lgwlgldinaappg--tyykd--
--vkatgkikl-scryv----------rpgkttfnahklrknfld----g
e-d---he-----fracfltgtakgqwe------------dgsq-vmfnp
-s--------gyg---c
>A
ywkervptlasrgdlqmgtigsaelvsaynv-lgewcashtd-lpa----
sed----e-------------k----emgc----ltkhh------lgflv
gl---dtiqdatvl-------l-lakpdctdl----tgstst--cii-lg
stassiiplsigdasrseiavhhn----rgvdnsgptsgvpktayigcya
nrk--lq------------cl-ty-r----haefp--vgyfirgeahln-
gyannf-------a-asrfrrlseigvgqlkfsdyf--i-----------
---ppqrt---rlsdkdni-ldsgah---ivdkp--tvdyassndeddcs
flfs-------------aq---aswsh----------psegpl-qevhrq
nsalselegdhafaskdaygknl-vvpavdcktlvnkna---------ga
wl-igctaasesseplgvsk----kfv------------a----------
a---tllevstcrg------------aag-qap--ltgmerg--dlgv--
v----gr---dyrkkcl----lqp-----a-lagthpfg--yfdkgtely
fnlthhpi-fa--c-eeydhfsk--l-trw-----sv---------sl--
--lrtagkvtfgegqfaligydpqdrda-gralykghgvtkki-------
d-s---kd-----irshyltk-pkgqld------------dglr-klkgp
-rllalgmek-f-neha
>B
fwr--vst---egnlllsnigvselvsvfka-lgdwcpqkte-lpn----
sad----e-dradfp-----sk----avhs----lnrht------ygfli
gl---eavld-sllslfqglpw-makpkcwp------g-tpa--clk-ls
kmncnhaplnigavprseiksnht----kglddtvpatvdpkttyggvyr
nrk--f--------------f-qy-h----dgrfplgigylgrateqvn-
g----y-------g-parfrr--dvgigalksaefyg-------------
------kv---rfrdgedv-lqsgthvvvikaspdtkl------------
----------------------gtnsh----------ataapl-hslhsq
hkvvaeledahdfasteaceksl-vcpsttcsklgsknm---------as
sl-vgcgvltmhtdtlcvqk---vkii--------evnler-------ys
a--ctllhistcrs------------pgd-estnrltglerfvn--gv--
s----pr---gfkkqcl----ldskssags-lsgahpfsgtyfekslely
f------v-fa--cleefnefvk--l-tqw-----ta---------dn--
--lpsagsdkl-qgeya----------k-grvlykaygptrkive-----
d-a---kd-----fksgyltk-pepnla------------dgmrpvlysn
-dvlvk--lref----a
>node10
ywngrmsa---ltetsvskd--g--vnvptlal-atdcq--elnsastgd
elswclph-ttaain-----rq----llgd----vhrgs------lsiit
dkcrf----e-----------q-vgip--wvldvysdv-asq--cl----
dvpvceggvyqqqmpiaha-cktgasgdrnp-dqaghtsdqrggyggcfk
g-rpcfs------------cm-qy-qevp-gtsfh----fftrtvndvg-
fhlglkad----al-gepfdp--giakgmfpftgihgii-----------
---klepasetrqtks---------k---hkqta--tqey----------
fgatwnsgpf-------sa---aiwgn----------fssaplgavksdr
dkgkp-etdgqnvknnskygkkv-kagsgdcakvagrisaaakqqptglt
rtlvtcdgmslnagpfckvp---irtl------------ge-------yn
g--c-lgrltacrgdasvliahnevapkeaahg--iknkdnh--knavka
alg--gdtlkayqrv-------tarlavga-ivakrvyvdeylvd-teln
tnsrkhdtdls--c-rgyrtyer--l-spg-----a----------ra--
--lmkin-arl-kgrlt----------ragntsykvhavkrhsaq-----
dsn---k------rr--------ggryn------------nsrk-vffgv
-qslikgcsngy----c
>F
ywngnm-s---ltytmltkd--g--invptlal-gtece--elesgqtgn
qttwclpy-ttaain-----rkskmsllgd----vhrgt------lgivt
dkcwg----d-----------q-vglp--wvldahpdi-age--cl----
dlpvckagvyqkk-----a-ckasgsgtrap-dhkghtgnqkhgygvcfm
g-npcnf------------ca-ey-eevqldpafd----ffarnisdvg-
fdnntkag----gt-gepfdp--giakgkfpftglhgik-----------
---klepa-atrnfqs---------k---n--ia--tqey----------
fag--npgpfetsspag-g---givdh----------fttdpmstlrnak
dsakv-etnaehikengkygkkv-kqgfhenakvagrtgkgeenqptrlt
islvtcmglslwkapfckip---fktl------------de-------ys
g--c-enrtttcrgdttvseahhqlaplpstqn--iqnr-sh--pnavga
plg--ggrlkgyrri-------tarlavga-vvarriyiseylvd-tdle
shsrkhkteltpnc-rgyrtfer--ldipg-----a----------ra--
--mmken-arv-pgrlt----------hagetsykghatkahnae-----
dsd---q------rr--------gasyn------------nsrk-vffgv
-qsli---phan----c
>node14
ywpgrmaa---mggtnvskd--aevvsvptlal-srdcq--e-ssqsfgd
kss----h-stanip-----re----algd----vqrns------lgiit
dk-------e-----------l-lggp--waledysae-asm--cl----
eapmsashlyqaqapvahs-ckhgatgnrntddqggqtsdgrtgyggcfk
t-rpcfs------------cm-qf-q----gtsfp----ffdrttrdvg-
fhlglsan----aa-gdnfdp--giahgmlpfssfhgvi-----------
---gvapapekrrtigai-------k---hqeka--tiey----------
faatwnagpf-------sa---aiwgn----------fssapl-dvrsdr
dkstp-itdgqniksgskygknl-kagsgecaklagkilaasksqraglt
rtlvgceglslsagpfckap---vktl------------ge-------yn
t--c-ldrlsscrggarvviahnerapreageg--vkskskd--knav--
alg--sktlepyakh-------qtrlavga-itakhvfveeylvd-telh
thirqhnvdlg--c-dayktyqr--l-tgg-----t----------sa--
--lmkks-arl-qgrlt----------rpgktsykahsvkrnsvh-----
d-k---kr-----frscyeeh-ssgryd------------gsrk-vtfgp
-qtlidgssngf----c
>node6
fwedrkpf---kgqaelsnggkvevvsahkiam-eqcpevtn-qae----
kqp----e-dsl---------------vgm----vdqhg-----qlgllv
-l-------e-elltlfrglql-lasaacwpl----ms-tsl--ceh-ll
tlpnnasprnqanvpssng-kkhs----kgvedqspeandarmaysgcya
kakpgyk------------cltan-q----dsqfe--lgffskite----
efagmy-------g-gsrfdr--giivgvlsfgrfygtl-----------
---gnlrl---rds--aqv-angsak---pesap--siny----------
llaa-------------ta---avlnv----------fisvpl-gamsqg
hnprakiagdleitg-teygknl-vvgsaectklmdkel---------la
rvrvtcdaltmaanplctae---vhavvpeneatl----ee-------ys
a--c-sihttgcraspkcyv-khdpaarekgpp--hsgktng--glsa--
a----aq---gyrkhci----mdsrl-sgt-lsaihefqatyfa--tqah
anikkhpt-la--c-deynvfaq--v-tgwlgleina-psg--tyysd--
--lkttgsvkl-sgrfv----------kpgkasfkahkitkkivn-----
e-d---ke-----frpcfltnipkgqyd------------dgsq-vrfhp
-v--------syg---c
>H
fkngllsa---lgitntgsg--ddvitvsglsl-dwdcq--d-esqcfg-
kns----kgsrldnyhtgsqkd----alkk----iqkha------a-mvh
yr-------a-----------lrlsgn--svvsdysed-eflneal----
eetmaphhlyraqsalahs-cregktgnllqddtv-hatgg--dvggcfk
a-kscyqisqhppplhtklcq-qf-a----aakfa----fysrikk--ms
fhlalstd----ig---sfnp--edsh-----ssfhgnvnd---------
-kppfapdetkpr-agki-------k---lqnkg--lvda----------
faaawnlspf-------ga---eiwqg----------fsvprd-niqpdr
dg-----ndgpnvkadi--------------cglygklgtagrsqdrgls
rslsgaqslklrqaqfcfthaeavgnl------------aa-------yn
a--c-l-rmctcdpgtrvvivkderqprtagdq--rplnkkd--kmdv--
klnatgkplqsyskq-------evqnaipa-vrakhvfvaeylvn-taqr
thirshtpmlg--c-npfetcqr--g-ngg-----k----------sglf
nhimk-s-tkl-qqkle----------qpgkfacakhtakknvvhvqaw-
a-k---kr-----fsscykdh-asgpyalsslnea-----gsrp-vasqp
-qtlstdadqgf----c
>node3
ywrervpt---kgnlqmnkigsaelvsaykv-lgewcpqhte-lpn----
sqd----e-ddlgfp-----tk----avgs----lnrhs------ygflv
gl---eavtd-sllwlfkglnl-makpkcwpl----ig-tpt--cik-ls
tmesnntplnignvprseitsnht----kgvddasppsgepktayggcys
nrk--fq------------cl-qy-h----naefp--igyftraaeqvn-
gysgly-------g-garfrr--digvgvlkfadfygvi-----------
---gpirl---rlsegddi-lqsgah---insnp--siey----------
flaa-------------ae---vtwsh----------ascapl-hslhsq
hsamaelegdhdftstdaygkdl-vvpsadcsklankna---------aa
wl-igcdaltmaseplcvsk---vkfv------------ed-------ys
a--ctllhvstcrg------------sad-esp--ltgmerg--dlgv--
v----pr---gyrkqcl----lqsklttgt-lagahpfsdtyfdkgtely
fnltehpv-fa--c-eeyndfak--l-tqw-----sv---------sa--
--lrsagsakl-qgqya----------k-grglykghgitkkive-----
d-s---kd-----frscyltk-pkgqld------------dgmr-vlygp
-rvllkgtvrdf----a
>node15
ywedrmpa---kgemrvgke--aelistntlam-arcpqptd-haesfgp
kst----h-dtvnip-----re----algn----vqrhs------lgllt
dl-------e-----------l-lagpscwpledyaln-tam--ci----
ampmsssplhqgqnpvahg-gkhsfagkksvddqsgqssdartgyggcfk
nerpgyh------------cm-es-a----gtqfp----ffdrtthevs-
gfaglaan----aa-gdafsr--gigvgvlgfgqfhgli-----------
---gqlrm---rfsegedvpvaggan---nqekp--tiey----------
fmat-------------sa---aiwsn----------fssapl-svrseq
nkpkp-iagdhdiksgnnygknl-vtpsaectklagkil---------la
rtkvgceglsvasspfckap---vkti------------ge-------ys
t--c-ldqlsecrgaakvaignnehaqreagad--hktknkg--gnav--
afg--pkklepyakhci----iqtrltagt-lftkhvfsedyfan-telh
thikqhpv-lg--c-deyntfar--l-tgg-----si---------ae--
--lkkds-arl-qgrft----------kpgrtsykghtikrksvh-----
d-h---ks-----frscyegh-skgkld------------gsrt-vrfgp
-ktliegsmhgy----c
>E
ywdgkmsk---ltstfvnkd--g--lhaptlev---dcq--elpcaadgd
dv--cllh-ttppit-----rq----llge----ihrgp------lsaia
ndckf----e-----------r-vgip--lvldvysev-sse--sl----
evpeceggvydelmpiaha-cktgasddrdp-aqkghisdehggysscfk
g-kpcls------------cm-qy-qevp-gtsfh----ffkrlgnsvd-
fniglktdrdpial-denfnp--aiakgmfhltglpglt-----------
---kmeparetkqtks---------k---rkqaa--kgqf----------
fggtwhtghf-------edvrpa--dk----------fsssplgagksdk
dkgkp-kvngpnkknksksgkkvikngsgdcaavagradvgakqpatgla
ra-------d-nsgptckvs---lstl------------ge-------yl
g--c-vgflpqckgdattlhaeteiaprseshg--iknedsh--tnavra
slg--gdtmkasqrv-------tvqlargg-fvtkrvyldeylvd-telk
tkgdkhqadlc--v-rgyktyer--l-gpg-----s----------rd--
--lmemn-sra-sgklt----------ragntnykihnvkrhsaq-----
dsn---k------dk--------dgrtn------------tkrk-vfisv
nrnltrgc---------
>node7
yweerrpt---ngqmqmskigtaelvsankiam-ercpqstd-qae----
kdt----e-dtlnfp-----kn----avgs----vdrhs------lgllv
el-------e-ellwlfkglnl-laspscwpl----ms-tam--cik-ll
tmpsnnsplnqgnvppshg-skhs----kgvddqspqssdartayggcys
nekpgfq------------cl-es-q----gaqfp--lgffsrtteqvs-
gfpgly-------g-gsrfer--gigvgvlgfgdfygli-----------
---gqlrm---rfsegedv-vqggaq---nesnp--sidy----------
flaa-------------sa---aiwsh----------fssapl-salseq
hkpkaeiagdhditgandygknl-vvpsadctkladkdl---------ma
rlkvgcdaltmasnplcksq---vktv------------ed-------ys
a--c-llqvtvcrgsakvyi-nhdnatrekgsp--htgknkg--glav--
a----pr---gyrkhci----iqsrlttgt-lagihafsetyfan-telh
lnikehpv-la--c-deynvfaq--l-tgw-----nv---------sd--
--lktdgsakl-rgrfv----------kpgrasykghtitkkivn-----
d-h---kd-----frpcyltn-pkgqld------------ggrq-vrfgp
-rvllegtmhsy----c
>node13
fwagllaa---mgstntakg--eevitvsslal-swdcq--d-esqtfg-
kss----n-sradny-----ke----algd----vqkda------lgmvt
dr-------a-----------lrlsgs--stlqdysad-esm--cl----
eqtmasshlyaaespmahs-ckqgdtgnmnqddngghaaggrtgmggcfk
t-kscfqisqnppplhtkfcm-qf-a----atyfp----ffnrptr--t-
fhlglstd----ts---sfnp--epah-----ssfhgvvnd---------
-kppvapetekrralgti-------k---hqdkg--lvsy----------
faatwnaspf-------ga---aiwen----------fsgpav-dmqedr
dkstp-ltdgqniksankygkhl-kgsagecaslagklhtagksqdaglt
rslpgceslklraapfcfsh---vktl------------sa-------yn
t--c-lvrlsscsggariviakdervpreggdq--ikakskn--klkv--
slg--skplqpyskq-------qvrlavpa-irakhvfvpeylvh-ttlr
thirqhnpllg--c-dpfdtcqr--l-ngg-----k----------sgkf
ntvmkks-trl-qgklq----------rpgkysckkhsvkknavhvepw-
a-k---kr-----frscyedh-gsgryalstlnea-----gsrp-vtrgp
-qtltddssqgf----c
>G
fwtgh--------stnvakg--eeintvgglav-swncq--d-dsqtfg-
kns----n-grvdgy-----ke----sad-----vqrga------lgmms
dr-------s-----------lrlrss--atlqvyatd-dtm--sv----
eqrmasshleaaesplshn-c--gdvgqmgdqdngghaaggrtgvggcfk
t-kkcfqisenppalstkfcm-qyka----qiffp----ffnrsek--t-
fklglatd----st---sfgp--ehah-----flfqgpvkdhkyhiaslk
gkppva--------------------------rg--lvqf----------
faatwdagpf-------na---aiksn----------ffasai-dlqedr
dsdik-ltdgqrakeehkygkhl-tgsagecaslmgklhtagksqdaglt
rslpecdi-klrcapfcfgh---lttl------------ka-------fn
tmac-lvrlhdcnggarilihkdeaahkdgggq--vkakskn--klkv--
nls--nrklkpyskq-------aerlaasa-iraphvfvsayri--itlr
thvrehtpllg--s-dgmgscqk--l-nng-----r----------tgkv
ktvmkkg-tra-ggelq----------rpgkygckrhnvrkgagqvepw-
v-nviakqarevhfractddh-gsgryrssaisevftgsaaprp-vtpep
-qtladdssagf----c
