>node15
rkvktelcdqw---edaeirh--kaskaedtekktelnsdlredtqpigd
g-wdqkkfslvp----gac-lkvli---akqqaqysp---haaydkpdfl
pl---v--tllmhrf--mkanelpvelli-------lshddall--ae--
-----l---gcvgv---vnsegl-kgsealtdlvgk----ih-s------
----------eygptlla---eege-tskcanp---vg---wpg--ghcd
----spmqsmskn-tsnviaklvtfke---cin---knvsstvsnccdca
kmkapvv-vlg--lellgycdlkkgvhildarkggpssrsavllarsadk
k----gtk----iklvafltglyt--ahlfhgr-m---ptsfdkcgkkka
---gl--gv-akklkngaha-k---q------tsdl-------vmlmisq
q--ly--e---aqdrlcqn-----fpik---gym-sirvv-scfglyt--
---anid---kgvqapekegkwli-----appdvk---------------
--rgagr--n---hcadlsak--yng-ghg--fhenrmw-skg-g--eig
sgagptfkeegksldyys---tgii-----a----fn-l--q-------q
a-laadap-lrfpdkspggeiascsylip---------kynekaptgyg-
a--r--------haklggr---nveglqsipsykclawm
>D
rkvn--mpkhw---kqaevhh--k-geedktgkknefnaavgdnmrapya
i-wnfvkyprpa----qmc-lrvlv---ahlkegesqhgahasi-qadvl
dl---yghelliqhf--ayagelasglms-------ltlcqrlsvlat--
-----l---gcisvfvgvenega-rgkeplaalvtlavge---m------
----------efthavik---deag-nsdcsrp---ts---wpk--ghc-
----ittqpv----lsdv------fpq---cfg---dga------gygqr
rl----v-tlg--salvgnsglkrashylgavqgsgsswtgliimgeaem
g----tir-ltdlqlytfvvglfm--aelsdqk-v----tcyakchnaks
---aleytg-smklhsgt---s---q------aggvafllrtgvtlvagt
r--ylted---hkatvcnt-----gflklygayl-llrdl-agyilyt--
---s-iy---r-ipdssrpdiwei-----ts--hk---------------
--kaspcp-kg---hfdigsktasna-ghg--fhedriw-atgvg--a--
--yaprnngggrsaefts---pgvi-----t----yctl--d----fgaq
a-f-agap-lrfsnqptagnkgacaffka---------pvkmrg-qafg-
t--k-----sq-v--lgaa---llk----ipssnclcwl
>node6
kkvn--mpdhw---keaevsh--k-geadktgkkrelnatvrdntrasya
v-wdyvkfpkva----smc-lrilv---aqlkggyqqngkhesf-qadvl
pl---y--llliqhf--iyagelsaglms-------ltlsdivlllaa--
-----m---gcisvfvgvdadgl-kgretladlval----lklv------
----------efthavlk---eeag-ksecarp---ts---wpg--ghcn
----vkmqtv----ladi------fkq---sfg---egv------giger
rm----v-plg--galvgysdlkkgshflgavagadsswqglllmgeaem
k----tir-ltnlqlydfvpgmyi--aelmhsk-v---ptcyekcndaks
---aleytv-slklraga---d---n------tsai-------vnlvngp
r--yy--d---dktkvcht-----gflklyqsyp-qlrvl-ggyilys--
---s-in---r-ipeprrpdawgi-----ts--hk---------------
--kespc--ktsephfdlgsktafsg-ghg--fhdervw-atgvg--l--
--laprfkeggrsleyts---pgvi-----s----yc-l--e----ygpq
a-fnaqgp-lrysdqptagdkgacsffta---------svktra-agfg-
t--k-----at-viklgai---klk----ipisnclswq
>node7
rkvnsqmpdhw---kdaeirh--kagdaeetgkktelnstlrddthpafa
g-wdyvkfptip----smc-lrili---aklkgqytp---haaf-kpdll
pl---v--lllihrf--ikggelsvdlls-------lkhqdillflae--
-----l---gcisv---vdaegl-kgretlvdlvgk----lk-s------
----------efgptvlk---eeae-tsecarp---aa---wpg--ghcn
----anmqsmasn-lsniisklaafkq---cie---ekvfttvtnacdgs
km----v-vvg--galigycdlnkgshildavkgsnaswsalllaksadk
k----aik-laklklvaflpglyt--aalfhgr-v---pgcfekcgknke
---alefav-alklkgaaha-i---q------tgef-------vnlvpsq
q--yy--d---dkdrlcht-----fflk---syp-slrvv-gafalyt--
---s-in---kgvpaperpdkwsi-----tspdhk---------------
--kgssc--s---hhsdlpsk--fng-ghg--fhedriw-atg-g--qii
tgaapvfkeggksldyys---pgii-----a----fn-l--e----kgpq
a-laadgp-lrfpdksaggdkgacsyfva---------tvnera-tgfg-
a--r-----ad-vsklggr---nlegilgipttkclswq
>node3
kkvfshmgnhw---gdaeirh--kagdtse-gkktemnktlhgstvptfa
g-wtytkfptvt----slc-lrili---sklkgqytp---rgaf-kpdma
pl---a--llvihri--ikggelsvemls-------lkhqdillllpe--
-----l---acist---vesqgl-kgketvvelagk----lk-s------
----------evgptvlk---eea-------------a---wpg--ghcn
----aglqamasd-lskvvvrlaafkq---tfp---emifvvvasacdgg
ks----v-svg--galigycdieksaapldaikgsnaswsallgvrsvdk
k----aik------qvcflpslyt--allfhgr-v---pgclekcevdlg
---aiefgvkalklrggaha-l---p------sgef-------aklvpnv
q--yt--d---ekdslcrt-----wflm---syp-alyavdesfalyt--
---g-va---tlvpaperpdkwta-----tksnpk---------------
--kgtsg--e---hhsvlpss--lngggha--f----iwpkng-g--kvi
sa-apvfrnggks----------ii-----a----fq-l--eleaynspq
s-ltakgp--rfpnraagshkgicsyyvn----------vhewp-tgfg-
a--k-----ad-vsklggrtqy------geactkclswq
>A
kkilsnmgnnw---gdagirdttragdace-grktdmdktlrecevptys
--wtyakfptvk----gvc-lpili---skltqqyss-----af-khdlv
ih---s--llvilnq--irgaelsiemls-------lkhedvlhllpd--
-----ladfacisa---iqaegl-kgkeavtefpgk----lk-s------
----------eigptvlk---eda-------------agvewag--dhcg
----tgmppmard-lskvvirlaafkp---sfs---qmtfvvlasgcasg
ks----l-gvcgigtltnycdiekgsasldglngstagwslvhgsrsvgk
t----aak------kvaylerlyy--allfhgk-v---pgilercgvnng
---alafgvgalvlqasphr-l---p------sadf-------a------
l--yk--e---ekdslcrt-----wllv---aypgalcpvn----lfigr
rggg-vs---tlvpaperpkkwta-----tkanpk---------------
-----------------------lngggha--v----inpnee-p--kvi
sa-apvfrkggkw----------vi-----a----ye-l--eleasnaar
s-lsaknp--kfptraadrhtgisdfyvn----------gnnws-aafg-
h--k-----seslaklgyrtqy------ggacssclmwq
>node13
rkykgelcdew---ddadvtq--r-sndaetargsaleselenqkqd---
m-----qfelvp----gqc-vqvld---vphqapynp---hkrfdkpdll
plkvkv--tlginkl--mtadelpiallv-------lghdpeiv--pqkk
-vvdav---gcivv---rnghgm-kgrntmtdlvar----vh-p------
----------nyapsleg---kegn-nkksaap---ld---wpgdhshcn
----tpmqklakp-aasvvgrffvfkavedcik---kflspvivnccdcp
slrepvt-tlg--ggtlgecdlc--------------------aavtsgk
kdav-afka---vqlatfvsalci--shpfhtrcl---ptpfnkigkkka
---ef--gl-attvksgary-k---q------t--f-------amliikq
n--ms--ecgltkdqnckanagsvfakk---vym-strka-nclsmfn--
---kevs---ggihg-tyrgrwhl-----a-sdtkv-pkgarnngptsg-
--pakar--k---hcmklgkk--yks-ggg--qqeestw-hgg-a--qpg
pgvggpvfhpgkslsyak---vgvv-----g----yd-v--e-------q
d-lntqap-lrfpdktaggavacctylitaskdvpdvvmevakapngyg-
gytrpygei---qaeldgs---enndlecdqk--clnwm
>C
-kel--mrehw---kepeige--k-ngadktn--revsatmrtntriahs
p-wdyvqpptva----slcyyrilv---te-kggyprngrhesf-qfdvl
pl---f--lliiqdf--eyagelrgglat-------l----ihlllaa--
-----s---gciegfvavddegl-kgkgtvadltel----lka-------
------------thpvak---dkeg-ksdcshp---ts---wgd--gacn
----vkmqtv----lagm------frq---pya---kg-------gvgeq
rd----m-aia--gtlvglhdlkmsarflaavavvdgvwqglll-gdgei
k----tlk-annltlyefvvciyi--aeairtk-v---ttcykrcneaes
---sleyvv-nmklrata---d---nansadgsgli-------vnlvngp
rpqya--d---yttkvcys-----gflklyqsfa-alevl-ggyllyr--
---s-vn---q-fpegirphswgi-----in--hk---------------
--keapc-akttgphfdltskkttsg-dhg--fhdeerw-atgkd--v--
--ngsrlkegg---eyyk---ggvl-----srqlqfc-l--n----ygaq
a-fkangp-lrysdqptaqeqsa-----------------krrs-tgfg-
d--k-----lt-viklgai---klk----iavsnclswq
>F
rrykgylcedaghaapndltq--kdakcgqtgaadt---slenqsqnvgd
t-----etslvp----gec-gk------pkaevgldp---hg-farpeqi
--------------i--kkdgdlavallk-------v----------q--
-----v---gcfgv---rgvnft-arlkk-anacnk----vh-vvifkiv
ecglrlfpilnlgatlse---rwanfgkkcasp---vh---wphehghck
----aplekfskde--nfignfftykd---cgr---kfk--ivvmccscg
wlrappa-ala--ldtsaecllskgardfrihkggpaswtgllseisppk
keev-gll----cklsdfehvmyls-pedlngrsl---psgflrcgppnc
gstsf--qt-hkslikg---kg---y------tvcf-------gmlnvsq
g--lf--ecgvgksr-----------------hs-skrkv-lc--ltt--
---qpiepwangih----qndwhlqgdfqalvekrvprkaeqhtgpfdk-
--kvvhk--k---hkh-----------sstathpekclw-dkg-g--kvg
phpggdvyigsisiefyrngtvgva-----n----fd-trdv-------r
d-lsahlpkekfpdkhgakgivccnyltn---------tlvaaapsqyg-
rccq--------enklggp---escgtqcqak--slawl
>node10
rkyktelceeqghgapadlte--kdskaeqteaatamraeleeqtqnvgd
t-----qfslvp----sdc-vkvli---plsqagyhp---htrfgkpeql
--------------v--rkdgdlpvalli-------v----------e--
-----v---gsigv---ddtngl-krtttksslcqk----th-t------
----------dygptlee---rrsnfskncanp---vd---wphehghcd
----apmekfskda--niignfftykd---cvn---tfh--avgnccscg
rlreppd-ils--letmaecdlsngarefrvlkgapasrsgilaqitapk
kedv-gll----aeladfvkakyl--eqdlhgrsl---pssflkcgrrkc
gstkf--kt-hktmkkg----k---y------asdf-------gmldvsq
g--ly--ecgvgrsqackq-----fpks---gym-slrkd-tcfnmfa--
---qpin---ngihs-tkqkkwhlqgdfgaladrrvhrkseshngpfdk-
--rgvhr--k---hck-----------ast--hhenclw-ekg-g--kig
pnaggsvyvastslafyrsntvgva-----s----fd-ireq-------r
d-ltahlp-qrfpdksgsnaivccnylin---------slvekapnqyg-
rscq--------egklggp---escgveceik--clawm
>node14
rkyktelcdew---eeaditq--kasnaeetekgtalkaeleeqtqqigs
d-----qfslvp----gnc-vkvli---tkqqaqysp---htrfgkpefl
pl---v--tlgmnkl--mkadelpvalli-------lghdeall--pd--
-----v---gcigv---hnaqgl-kgtktmtdlvgk----ih-p------
----------dygptlqe---kegn-nkkcanp---vd---wpsthghcd
----tpmqkfskd-vasvigkfftfkd---cvn---kfvsptvgnccsca
klrepvt-ils--letlgecdlskgvhifdvrkggppsrtgvlaaitask
kedv-gyk----vqlaafvtglyi--ehpfhgrsl---pssfnkcgkkks
---ef--gt-aktvksgahn-k---h------asdf-------amliisq
n--ly--ecglardqnckq-----fpkk---gym-sirka-tcfsmye--
---edis---kgihs-tkqgkwhi-----aladtkv-pkgaphngpmsg-
--rgshr--k---hcsklgnr--ykg-gng--hqedclw-nkg-g--qig
pgagatvyhpgkslayyk---vgvi-----g----fd-i--q-------q
e-ltanap-lrfpdksagnavaccsylis---------klvekaptgyg-
aytr--------qaklggp---dsnglecdik--clawm
>G
kdyhdelckew---detdhtq--a-syyieaargnalssdlesek-d---
m-----qfelvq----aac-vqvvd---vphetpynp---hqrfnsedll
plavkv--tfsfnrl--kaaaeipfgllv-------ldhnlniv--paqs
-vvdaa---gcivv---rnghelgkgrntvsklvvk----vh-p------
----------dynpaied---kdsh-skksaapeasln---wpgdhnncn
vqdttkveklekp-apcvmgrffvfrtaddcitdfrkflspvcvdccdcp
tlstpia-tls--grtlghcdlc--------------------lastsgn
envs-pykt---vqlasfrseaci--thefhtrcl---ptpfqkitkksl
---dv--gl-adkvnngary-s---k------k--f-------tlliv--
-----------dkdpncraniggvfakk---lyl-svrks-nclsmfk--
---kevs---stshg-vyrmrllk-----a-gdtsv-ekgsrnsgpsga-
--pskpr--k---hclslgkr--yks-ggg--qqdestw-hgg-aaeqps
ag-agplfhpakslsydi---cgac-----g----yd-v--e-------h
q-letkap-ahfpdkrtgggvscncylitspkeapdvvvqnak-----gr
gysrsygni---ggqldss---enndmpcdqk--vmrwm
>H
rtydtelcsew---vhaevta--r-pshaengrspaleadleapkda---
t-----qfelqq----dqc-tiall---vphqaqynp---hrkfdkpall
llrikt--ttginil--mkteplpasllvcgksvprlghepeiv--rqkk
gvvdqi---gsvvv---rngfgm-ggrktmin---p----i---------
-----------yasslagmmmidvn-ekkaavp---lk---wpgahkeyn
----tpmqkgvkp-gasvaarllafkaivdcir---rilvpaivnccdcp
slrepvs-tlg--gdtlgscdlc--------------------ailtaas
kdsviafqa---vqfatfvtasci--nhgyhnqsl---qtpfnplakkks
---ef--gl-tteiriglrf-k---q------a--y-------gmhtike
n--kp--ecamtkdqsc---aghvfatk---vfa-gtrky-dclrmfp--
---kerv---gvlh--ifrgrwhl-----a--dgr----------ptgg-
--pakdr--i---ecaklakk--ykg-ggg--qkyestw-neg-g--dpq
pgvagpvfhpgkglp--k---igvv-----k----ye-a--e-------h
d-ldtqap-lrfptraaggavac--ylitaskdvhdvvvdv-kaptgrg-
gy-----qi---eselags---ennplqcnqn--clewl
>B
krvyvhtdtke---gesevrq--kagnkpt-gikteinksmhgsgvptfa
gfwtysklptviesnknlc-lrilfggegkttgqfkp---rasn-kpdmt
pl---e--vlcvhri--ingtefppetlg-------kkhq-----lle--
-----l---mciss---aegqgl-ngketavqlsgk----lk-c------
----------qagnrtlk---eda-------------a---wvg--gccq
----tslqvmaee-inraivrladfkh---tap---emifvvvastcdgg
ts----v-svg--gsligycdvdqtadslctksgtktswstllvvrevnk
k----svk------ricfllklyt-pavlfkgr-v---sgcrekcsadlg
---stefgvkalalkgsant-a---p------keef-------dkyvpnr
e--st--d---akdstcls-----wiem---syp-alysvddrfahyt--
---g-vs---ilvpapmrsdnwva-----arckvr--------------k
nlsntsg--e---qassapia--lmgssht--f----iwpalg-g--rmv
ga-apvfrvg-------------aicgvgkd----ft-l--alevynspd
s-lkakgg--rfk-rdagsymvactyyvn----------vnewp-sgfg-
p--k-----ad-vtklgt-kqy------gnackqcmnwh
>E
rredtvlceekghgap--l-e--iqsdgeqaepssig--dlqeqnqnvgp
t-----ef--vh----tnc-v--lv---plsqasyhp---htpfgkpasl
--------------vlg-rqvglpvglli-------v----------a--
-----v---gsigl---ddsnsl-k------------------t------
----------eynptlee---rksslsk--gdp-----------ehascs
----vpmakfskqa--nivgnfftykk---cvn---tfh--tignccscg
r-rqaydevlp--getltecdlsqngasfkvlggtp--ragvlaeiaapk
ksdv-sll----lkladfakasyv--qqelhgrnlggepssflkcgrrkc
getkf--kt-hkhmkkg----kgpny------ands-------amidkvq
g--ly--ecglarsdcckk-----fnm----gtm-elkkd-ttthmfa--
---npik---ngiha-skqkiwhlqgalgaleerrvhrksephngtfek-
--ksvhr--k---kcr-----------ake--yhndclw-dkk-v--ktg
psaglgaylaatslafkkpttvgis-----s----fd-lidq-------r
nvlkanvt-qr------tgaiicctylvg---------cmvekapnqyg-
race--------dgklgc-----------eiv--vipsl
