>ENV_SIVGB/47-569
hnpdk--------gvky--vsrqdelklstmrkl--svclfa-valrdaf
vydalangcakl--wedqlvcackpggdavk--vlkaakvkqsdvapsgs
ikqfmtkvakqdcldevna-tllgsdkr---t-----gkkad-----r--
lpvvvicfinpagldyllkvkrkgttsqii----------kk--------
-mgarlvclidtvfqlllaikthikisl--tslava----cvawnngenl
ceklarisvvnd---tgrgcqrgmatydirtepssgira---krthpef-
--kvlcdpalhshv----cydlvkkeipnlqgapdadlvcc-eesidssf
--ggket--dsngrailgkhggssprlhvcrkhakqkk--fysclpqaq-
-----e--vrgklghlapalf----------agnlfqedalc----glyh
fyhkqii-gklitgnhapdytagstsgkqg---------gntdppgappp
vpiggqkntmidfgyvqfsp----------asekvqdvyvsgkkgnnyla
kagvavaarvgglecgysqenasaktpdmirrgptra--gsvgesgsc
>ENV_HV2BE/24-510
hct-k--------gvkf--icmdga-----gkdh--ascyvaesal-eaf
aynmlanqcdd---kegdlvctcqalshsvktpckkdahfkksergtgsa
ieifmskapytlnieqvln-qflgkdkrf-farpga-aknnqsavqhkal
lqfvvkeffpraglnl-tkakrkg--vpfyldslgppgkhqkkqpddvps
cmggiikcyevte------igkhqklslhvtrlats-sqecaffpndepy
cvrtkgvktisd-------cgkslslfkaskes---irariakrmsaefc
vdqalchdyhe---dygqcfsslatvdgglngksntdlvcc-nnephgty
-kggget--gsssknqltkngassprldna--qs---sggfyicmapph-
-----r--v---lghfeaslfisgialtqape--afqrtttc----gmys
fyqkhfl-sklipdalagefkksaadsksg---------grtdlkggrpa
vplvd----lvqyaffdfgpg-cqmfevgnrcgklqkiylggkqastavc
sstlklalrvegfktayskkglta-epn--qpgevkm--stmsecttc
>ENV_HV2NZ/24-502
hct-k--------gvkf--ickdga-----gkdh--atcfvgqpal-eal
aynmlanqcdd---kegdlvctcqamshgvktpckkdthfkksergtgsl
veifmskapytlnidqvln-qflgkdkaf-fvkpds-vktnqsevqhryl
lqfavkqffppgglhl-tkakrkg--vpfyldtl----khqkkepddvps
amggiikcykvaa------igkhrkvslrvtrlaks-sqecaffpndepf
cvrtkgvktisgvgh----cgkslpvikgkkas---irariasrmsaefc
vdralchdyhe---vygqcfssiakvegglngksntdlvcc-dsephgty
-kggget--gssgknqltkngassprldtg--qs---segfyicvatph-
-----k--v---lghfepslfisglalvha-----feqtttc----gmys
fyqkhflrdsltpdakagqfkksgannktgkpvgfkdlygrtdlkggrpa
vplvq----lvqyaffqfgpg-cqmfevknrcgklqkvylggkeaskyic
gstlklalrvdgfktayskkglts-epn--qpgqvkm--samsecttc
>ENV_SIVM1/24-528
hctvk--------gvkf--ickdga-----gkdh--athftdqpal-eaf
aynilanhcdt---reaqlvctcqalshspktpckkdahfkksavgpgsl
vqifmskvsytlnidqvla-qflgkdkrftfvrpgs-vknnesdvqhryl
lqfvvteffppgdlnl-tkakrkg--vpfyldsl----khqkkepddvps
amggiykcyrltr------igkrqkvslivtrlpts-sqecafwpndepf
cvrtkgvktigd-------cgkslpvfnakkes---irarlakrmsaefc
kdqalcheylh---dygqcfssiaavegslqgksksdlicc-daeshgsy
--gaget--gtsgknqla------prlddaksqs---sdgfyiclgsph-
-----k--a---lshfepdllisgialthane--afqqattctfppgkys
fyqihfl-sklipdalagefsksgassktg---------grpdlkatrpa
vplvn----lvqyafiqfgpg-cqmfevknrcgklqkvylggkeartyvc
sgtlklalrvdgfktgyskkglta-epg--epgqvkm--samsecttc
>node11
hct-k--------gvkf--ickdga-----gkdh--atcfvaqpal-eaf
aynmlanqcdd---regdlvctcqalshsvktpckkdahfkksergtgsl
veifmskapytlnidqvln-qflgkdkrf-fvrpgs-vknnqsavqhryl
lqfvvkeffppgglhl-tkakrkg--vpfyldtl----khqkkepddvps
amggiykcyrvta------igkhqkvslrvtrlats-sqecaffpndepf
cvrtkgvktisd-------cgkslpvfkakkes---irariakrmsaefc
vdqalcheyhe---dygqcfssiaavegglngksntdlvcc-dsephgty
-kggget--gssgknqltkngassprldna--qs---sggfyicvapph-
-----k--v---lghfepelfisgialtqape--afqqattc----gmys
fyqkhfl-sklipdalagefkksgansktg---------grtdlkggrpa
vplvn----lvqyaffqfgpg-cqmfevknrcgklqkvylggkeastyvc
sstlklalrvdgfktayskkglta-epn--qpgqvkm--samsecttc
>node7
hftek--------gvqf--ickqge-----gkdl--aacflgqpal-d--
----lgnqcetlkpweadlvctcesgshtvk--cmkaahlkksevtaggm
ikifmaevsrtahigqtla-qslgkdkr---v-----vknas---qhryl
lqvvvleffppaglnlltkakrkg--lplivdgl----ehnkkepdnvpn
qlgglfkcyrvvv------idkhvkvslivtrlpta-sqecgfwsnndpl
cprpaktktitd---sgngcgralavfkirkes---irarfankmhaef-
--kalchehlhghs----cfasitkvtvnlqgkskadlvcc-ean---py
--stdet--gtdgrqqltkdggseprlnnirshs---r--fysclapph-
-----d--vrsrlsqfepdlf----------a--lfqqsatc----gkyh
fyqkqfl-nklvpggrygkytksgesgkqg---------gagdvkggrpa
vpvsn----liqfgfiqlgpgp--lfevklpcgklqevylaekkgrtylc
sltiklsarvsgfksgfskknata-epd--rrgavka--sdmgecata
>ENV_SIVV1/24-538
hftek--------gvqf--ickqge-----gknl--aacflgqpal-d--
----lgnqcetlkqweadlvctcesgshtvk--cvkaahlkksevvadgm
ikifmaylsrtthigqtla-qslgktkr---v-----vknpa---ehryl
lqvvvleffpssglnlltkqkrkg--lplivdgl----dhdkkepdnvpn
qlgglfscyrvvv------idaevnmrlivtrlpta-sqdcgfwsnndpl
cprpakakvfte---tgngcgramavfkirkeg---mrgkfankihaey-
--kalchehlhghs----cfasvtkvtanlqgkskvdlvcc-esd---py
--stdetscgtdgrqqltkdggseprlnnirshs---r--fygcltppa-
-----dgnvrsrlgqfdpdlf----------a--lfqqpatc----gkyh
fyqkmfl-nkmvpggrygkytksgkpgtqa---------gagnvkqgrpa
--dkn----laqfgfikigpgp--llaiklptggikevyraekkgrtllc
sltikvgarasdfktgfsktnitn-epn--rrgavkaaiadmaecgta
>ENV_HV2D2/24-513
hct-k--------svkfiaickdg------gkdq--atcfvaqpal-eaf
synmlaqecdd---r----vctcqslstsvktpckgdahfkksargtga-
------kapytlnveqvlnrhflakdkrf-fvrpgnpvkdnqsavrhryl
lqfvvkeffppggmhl-tkakrkg--vpfyldtl----khqkkeeddvas
smggiykcyrvtl------vgkhlkvslrvtrlats-sqecaffpndepf
cvrskgvktisd-------cgkslpvfkakkes---irarvakrmsaefc
raqalcheyle---dyaqcfssiaavegglngksntdlvcc-diephgty
-kgggqt--gssgknvltkngvswpqidna--qs---ngvyyicvapphs
lgtyrk--m---lshfepdnfisgialknapq--plqqattc----gmys
fyqkhfa-skliteslagqfpksg-hvktr---------grtdlkgsrpa
vplvn----lvqyaffqfgpg-cqmfdvknrcgklqkvylggknastyvc
sstlklalfvdgfkaaywrngfsa-epg--qpgqlkf--ssmsecttc
>node8
hytek--------gvqf--ickqge-----gkdl--aacflaqpal-daf
aydplgnqcetlkpweadlvctcqsgshsvk--cmkaahfkksevtaggm
iqifmakvsrtanidqtla-qflgkdkr---v-----vknan---qhryl
lqvvvleffppaglnlltkakrkg--vplivdgl----ehqkkepdnvpt
qmgglfkcyrvtv------idkhvkvslivtrlpta-sqecgfwsnddpl
cprpaktktitd---tgngcgralavfkirkes---irarfakrmhaef-
--kalchehlhghs----cfssitkvtvnlqgkskadlvcc-dankhspy
--sgdet--gtdgkqqltkdggseprlndckshs---k--fysclapph-
-----k--vrsklsqfepdlf----------a--lfqqsatc----gkyh
fyqkqfl-sklvpgarygeytksgesgkqg---------gasdvkggrpa
vplsn----liqfgfiqfgpgp--lfevklpcgklqevylggkkgrtylc
sstiklaarvngfksgfskknata-epd--rrgavka--sdmgecatc
>node9
hctvk--------gvkf--ickdga-----gkdh--atcfvaqpal-eaf
aynmlanqcdt---readlvctcqalshsvktpckkdahfkksevgtgsl
vqifmskvsytlnidqvla-qflgkdkrf-fvrpgs-vknnqsdvqhryl
lqfvvteffppgglnl-tkakrkg--vpfyldsl----khqkkepddvps
amggiykcyrvtv------igkhqkvslivtrlpts-sqecafwpndepf
cvrtkgvktisd-------cgkslpvfkakkes---irarlakrmsaefc
rdqalcheylh---dygqcfssiaavegslqgksktdlvcc-daephgty
--ggget--gtsgknqltkngassprldnaksqs---sdgfyiclapph-
-----k--v---lshfepdlfisgialtnape--afqqattc----gkys
fyqkhfl-sklipdalagefsksgassktg---------grtdlkggrpa
vplvn----lvqyafiqfgpg-cqmfevknrcgklqkvylggkeastyvc
sstlklalrvdgfktgyskkglta-epn--qpgqvkm--samsecttc
>node19
hct-k--------gvkf--ickdga-----gkdh--atcfvaqpal-eaf
aynmlanqcdd---regdlvctcqalshsvktpckkdahfkksergtgsl
veifmskapytlnidqvln-qflgkdkrf-fvrpgs-vknnqsavqhryl
lqfvvkeffppgglhl-tkakrkg--vpfyldtl----khqkkepddvps
amggiykcyrvta------igkhqkvslrvtrlats-sqecaffpndepf
cvrtkgvktisd-------cgkslpvfkakkes---irariakrmsaefc
vdqalcheyhe---dygqcfssiaavegglngksntdlvcc-dsephgty
-kggget--gssgknqltkngassprldna--qs---sggfyicvapph-
-----k--v---lghfepslfisgialtqape--afqqattc----gmys
fyqkhfl-sklipdalagefkksgansktg---------grtdlkggrpa
vplvn----lvqyaffqfgpg-cqmfevknrcgklqkvylggkeastyvc
sstlklalrvdgfktayskkglta-epn--qpgqvkm--samsecttc
>node10
hct-k--------gvkf--ickdga-----gkdh--atcfvaqpal-eaf
aynmlanqcdd---readlvctcqalshsvktpckkdahfkksergtgsl
veifmskapytlnidqvln-qflgkdkrf-fvrpgs-vknnqsavqhryl
lqfvvkeffppgglhl-tkakrkg--vpfyldtl----khqkkepddvps
amggiykcyrvta------igkhqkvslrvtrlats-sqecaffpndepf
cvrtkgvktisd-------cgkslpvfkakkes---irarvakrmsaefc
rdqalcheyle---dygqcfssiaavegglngksntdlvcc-dsephgty
-kggget--gssgknqltkngassprldna--qs---sggfyicvapph-
-----k--v---lshfepdlfisgialtnape--afqqattc----gmys
fyqkhfl-sklipdalagefsksgansktg---------grtdlkggrpa
vplvn----lvqyaffqfgpg-cqmfevknrcgklqkvylggkeastyvc
sstlklalrvdgfktayskkglta-epn--qpgqvkm--samsecttc
>node18
hct-k--------gvkf--ickdga-----gkdh--atcfvaqpal-eaf
aynmlanqcdd---regdlvctcqalshsvktpckkdahfkksergtgsl
veifmskapytlnidqvln-qflgkdkrf-fvrpgs-vknnqsavqhryl
lqfvvkeffppgglhl-tkakrkg--vpfyldtl----khqkkepddvps
amggiikcyrvta------igkhqkvslrvtrlats-sqecaffpndepf
cvrtkgvktisd-------cgkslpvfkakkes---irariakrmsaefc
vdqalchdyhe---dygqcfssiaavegglngksntdlvcc-dsephgty
-kggget--gssgknqltkngassprldna--qs---sggfyicvapph-
-----k--v---lghfepslfisgialtqape--afqqattc----gmys
fyqkhfl-sklipdalagefkksgansktg---------grtdlkggrpa
vplvn----lvqyaffqfgpg-cqmfevknrcgklqkvylggkeastyvc
sstlklalrvdgfktayskkglta-epn--qpgqvkm--samsecttc
>ENV_HV2D1/24-501
hct-k--------gvrf--icmdga-----gkdh--atcfsaqsal-eaf
aynmlanqced---kegdlvctc-althsvktpckkdahfkksergtgsl
veifmskapytlnidqvln-kffgkdkrf-fvrpgs-vknnqngvqnryl
lqfvvkeflprgglhl-tkakrkg--vpfyldtl----khqkkqpddvps
amggiikcynvta------igkhqkvslhvtrlats-sqecaffgndepf
cprtagvktisd-------cgkslplfkakkes---irariakrmsaeyc
vdqalchdyhe---dygqclssiataegglnsksntdlvcchdsephgty
gkggget--gssgkyqltknggssprldna--qs---nggfyicvapph-
-----k--v---lgqfepslfvsgiaitqepe--tfqqattc----gmyn
fyqkhil-sklipdalagefkksgadsntg---------grtelkggrpa
vplvn----lvqfaffefgpg-cqmfevgnrcgklqkiylggkeastyvc
sstlklalrvdgfktayskkglia-epg--qpnqvkm--samsecttc
>ENV_HV2CA/25-512
hct-kgadqsttlgvkf--ickdga-----gkdh--atcfvalpal-epf
afkml-nqcdd---regdlvctcqalshgvktpckkdthfkksergtgsl
veifmsktpytlnidqvfn-qflgkdnrf-fi-pgs-vknnqsavqyryl
lqfvvkeffppgglhm-tkakrkg--ipfyldtl----khqktepddvpr
amggvidcyrvta------igkhqkvslrvtrlatsfsqdccffpndepf
cartkgvntisd-------cgkslpvfkapges---irariakrmtaefc
vekalchdyhe---dyg----sitavegglngksnsdlvcc-dsnphpty
-ksgnet--gssgknqltksgassprldga--qs---segfyfcaasph-
-----k--v---lghfepfffisgialthape--afqeattc----gmys
fyqkhfl-sslipdalagefkknganaktg---------grtdlkgnrpa
vplvd----ivqyaffqfggg-cqmfeaknrcgkiqkvylggkeastyvc
mstlklalrvdgfktvysrkglaa-ern--qsgqvkl--kamsecttc
>node17
hct-k--------gvkf--ickdga-----gkdh--atcfvaqpal-eaf
aynmlanqcdd---regdlvctcqalshgvktpckkdthfkksergtgsl
veifmskapytlnidqvln-qflgkdkrf-fvrpgs-vknnqsavqhryl
lqfvvkeffppgglhl-tkakrkg--vpfyldtl----khqkkepddvps
amggiikcyrvta------igkhqkvslrvtrlats-sqecaffpndepf
cvrtkgvktisd-------cgkslpvfkakkes---irariakrmsaefc
vdkalchdyhe---dygqcfssiaavegglngksntdlvcc-dsephgty
-kggget--gssgknqltkngassprldna--qs---segfyicvasph-
-----k--v---lghfepslfisgialthape--afqqattc----gmys
fyqkhfl-sslipdalagefkksgansktg---------grtdlkggrpa
vplvn----lvqyaffqfgpg-cqmfevknrcgklqkvylggkeastyvc
sstlklalrvdgfktayskkglta-epn--qpgqvkm--samsecttc
>ENV_SIVG1/22-522
hftek--------gvqf--icsqad-----gkdltpaacflgqpae-g--
----lgnqcevlkpwevdlvctcestshtvk--cmkaahtkksevtaggm
ikifmaevsrtahigqtla-qsvgkdkr---v-----vknas---qhryl
lqavvvefyppaelnlltkakrkg--lplivdga----ehnkkepdnvpn
qlgglfkcyrvvi------idkhvkmslivtrlpaa-cqecgfwsnndpl
cpqpcktktiad---vgngcgralavfdirket---irsrfankmhaaf-
--kalchehlhghs----cfasitkvtvnlqgkskadlicc-ean---py
--sadet--gvdg----tkeggseprlnnirshs---r--fysclapph-
-----d--vrsrlgqfepdlf----------a--lfkqaatc----gkyl
fyqkqfl-nklvpggrygkytksgesgkqg---------gagdvkkgrpa
vpgsn----liqfgfidlgpgp--lfevklpcgklqetylsekqgrtflc
sltiklsarvsgfksgfskknata-epd--rraavka--sdlgeiata
>node14
hct-k--------gvkf--icmdga-----gkdh--atcfvaqsal-eaf
aynmlanqcdd---kegdlvctcqalshsvktpckkdahfkksergtgsl
veifmskapytlnidqvln-qflgkdkrf-fvrpgs-vknnqsavqhryl
lqfvvkeffprgglhl-tkakrkg--vpfyldtl----khqkkqpddvps
amggiikcykvta------igkhqkvslhvtrlats-sqecaffpndepf
cvrtkgvktisd-------cgkslplfkakkes---irariakrmsaefc
vdqalchdyhe---dygqcfssiatvegglngksntdlvcc-dsephgty
-kggget--gssgknqltkngassprldna--qs---sggfyicvapph-
-----k--v---lghfepslfisgialtqape--afqqattc----gmys
fyqkhfl-sklipdalagefkksgadsktg---------grtdlkggrpa
vplvn----lvqyaffqfgpg-cqmfevgnrcgklqkiylggkeastyvc
sstlklalrvdgfktayskkglta-epn--qpgqvkm--samsecttc
>ENV_HV2G1/23-502
hct-k--------gvkf--ickdga-----gkdh--atcfvaqpal-eaf
aynmlanqcdd---regdlvcicqalshsvktpckkdahfkkaergtgsl
velfmsknpytlnisqvlt-qflgkdkrf-lvrpgs-vknnkrvvqhryl
lqfvvkeffppgglhl-tkanrkg--vafyldtl----khqkkesddvpn
amggiykcyrvta------igkhqkvslrvtrlats-sqecaffpndepf
cvrtkgvktisd-------cgkslpvfkaktes---irariakrmsaefc
ldqalchsyhe---dygqcfssiaavegglngksntklscc-dsephgty
-kggget--gssgknqltkngassprlnna--qs---wgefyicvseph-
-----k--v---lghmepelfisgialtqapd--afqqattc----gmys
fyqkhfl-sklipdalageflksgansktg---------grtdlkggrpa
vplvn----lvqyaffqfgps-cqmfevknrcdklqkvylggkeastyvc
sstlklilrvdgfktayskrgyta-epn--qpgqvkm--saqpecttc
