>ENV_HV2D1/24-501
itwkt--lhqidaepp----ekvcdrvdfe------------------va
-cvksyvpkttpd------ftrvkylgvqrnctheeklkgyfdgsnyska
mlsaraagpvewhdlvi--dgaakkakmilkiqeqhmyllelvsdagrfr
pvrva-dvrdfmvkstgalvgyvsqkl-malgpfelsaiqilgaa-fekr
vggvvh-----fgnagedkggltpvscrekpipcpiidgqyalclgrefn
pnrttltecfkdsplmfardryfkagmvkeefkfmffsnddnpavwhevh
pqarpg--------psgvgl------------npnlilvsskklavqdnp
yfgapy---iltd----sakp---------------fsqvffptqecisg
eafssahvvyi-qklkghks--leglkg--------harhliqamir-gl
eahkee---lggkgl--vgakisapatlmfpr---hgqcqytkfnfltch
kvciridl-lnlykayilsgakfsvfgslg----hpe--splyinrtgra
i--------yhldayvlkgiglptgspdkdaykgp----llarpliffvg
msvstgakwlnanevqls---------fanhvall
>ENV_HV2NZ/24-502
lawkt--laqldaeppdlgaekvtdsvdgd------------------va
-cvkshipnptpe------ftrvkympvqrncthedklkayidgsnyska
mlaaiaagavpwndlvi--dgaakkakmilkiqeehkyllqlvsdagkfr
pvrlgkdvrefmvnstgalvgylsqklamalgpldasaiqilgaa-gekr
vggtvh-----fgnagedkgfllpvpcrenqipcpvidgqydlclgrefn
pnrlaltecfkgsplmhardryfkvgmikeeykfmffsadvnpavwhevh
pfprpg--------pasvgl------------spklilvsggklaiqdnp
yfgapy---ilne-------------------------------qecisg
eafvsghcvyv-qklkghqs--lvglks--------rarhliqslir-gl
eahkhamyllgghgl--vnapigapaklmyps---hgqcqftefnfqtck
kgciridl-fslykayilsgakfsifgslg----hae--nplyinrtgra
i--------yhlddyvlkgiglptgdadkqaykgp----vlahaliflvg
mavtsgekwldhsevqhs---------fanhvtll
>ENV_HV2CA/25-512
ltwnt--laeld-----------sdnvdge------------------va
-cvksyipnpdpd------ftpvkylpvqrncthedklkgyfdgstyeka
mlaavaagpvpwhdlvr--dgaakkakmiltiqevnkyllelvsdagrfr
pvrlgkdvreflvnatgallgylseklsmalgpldasaiqilaae-gkkr
vggvvhrqaelfgnvgegkgglspvicrenqlpcpiidgqyevclgrefn
pnrtaltecfkgsplmhardrytkvgmikeeckfmffladvnpavwhevh
pfahpg--------psgigl------------spnlilvtngklaiqddp
yfgapy---ilne----qakp---------------ysqvffptqecisg
eafqtghcvyv-qklrghqs--leglkg--------rarhfiqslir-gl
eahkqamyllgghgl--vgapigapatlkyar---hgqceytefefqach
racirqdl-fslykayilsgakfsvfgslg----rpe--mplyinrtgra
i--------yhledyvlkaiglptgdpdrdaykgp----ilshaliffvg
mavtsgskwldasevqhs---------fanhvtll
>node18
ltwkt--laqldaepp----ekvcdsvdge------------------va
-cvksyipnptpd------ftrvkylpvqrncthedklkgyfdgsnyska
mlaaraagpvpwhdlvi--dgaakkakmilkiqeqhkyllelvsdagrfr
pvrvgkdvrefmvnstgalvgylsqkltmalgpleasaiqilgaa-gekr
vggvvh-----fgnagedkggltpvtcrenpipcpiidgqyelclgrefn
pnrtaltecfkgsplmhardryfkvgmikeeykfmffsadvnpavwhevh
pfarpg--------psgvgl------------spnlilvsgkklavqdnp
yfgapy---ilte----sakp---------------ysqvffptqecisg
eafssghcvyv-qklkghks--leglkg--------rarhliqslir-gl
eahkhamyllgghgl--vgakigapatlmfpr---hgqcqytkfnfqtch
kvciridl-fslykayilsgakfsvfgslg----hpe--mplyinrtgra
i--------yhlddyvlkgiglptgdpdkdaykgp----ilahaliffvg
mavttgskwldasevqhs---------fanhvtll
>node19
ltwkt--laqldaepp----ekvcdsvdge------------------va
-cvksyipnptpd------ftrvkylpvqrncthedklkgyfdgsnyska
mlaaraagpvpwhdlvi--dgaakkakmilkiqeqhkyllelvsdagrfr
pvrvgkdvrefmvnstgalvgylsqkltmalgpleasaiqilgaa-gekr
vggvvh-----fgnagedkggltpvtcrenpipcpiidgqyelclgrefn
pnrtaltecfkgsplmhardryfkvgmikeeykfmffsadvnpavwhevh
pfarpg--------psgvgl------------spnlilvsgkklavqdnp
yfgapy---ilte----sakp---------------ysqvffptqecisg
etfssghcvyv-qklkghks--leglkg--------rarhliqslir-gl
eahkhamyllgghgl--vgakigapatlmfpr---hgqcqytkfnfqtch
kvciridl-fslykayilsgakfsvfgslg----hpe--mplyinrtgra
i--------yhlddyvlkg---------kdaykgp----ilahaliffvg
mavttgskwldasevqhs---------fanhvtll
>node11
ltwkt--laqldaepp----ekvcdsvdge------------------va
-hvksyipnptpd------ftrvkylpvqrncthedklkgyfdgsnyska
llaaraagpvpwhdlvi--dgaakkakmilkiqeqhkyllelvsdagrfr
pvrvgkdvrefmvnstgalvgylsqkltmalgpleasaiqilgaa-gekr
vggvvh-----fgnagedkggltpvtcrenpipcpiidgqyelclgrefn
pnrtaltecfkgsplmhardryfkvgmikeeykfmffsadvnpavwhevh
pfarpg--------psgvgl------------spnlilvsgkklavqdnp
yfgapy---ilte----sakp---------------ysqvffptqecisg
etfssghcvyv-qklkghks--leglkg--------rarhliqslir-gl
eahkhamyllgghgl--vgakigapatlmfpr---hgqcqytkfnfqtch
kvciridl-fslysayilsgakfsvfgslg----hpe--mplyinrtgra
i--------yhlddyvlkg---------kdaykgp----ilahaliffvg
mavttgskwldahevqhs---------fanhvtll
>node14
ltwkt--laqldaepp----ekvcdsvdfe------------------va
-cvksyipnatpd------ftrvkylgvqrnctheeklkgyfdgsnyska
mlaaraagpvpwhdlvi--dgaakkakmilkiqeqhmyllelvsdagrfr
pvrvg-dvrefmvkstgalvgylsqkltmalgplessaiqilgaa-gekr
vggvvh-----fgnagedkggltpvtcrenpipcpiidgqyqlclgrefn
pnrttltecfkgsplmhardryfkvgmikeefkfmffsndvnpavwhevh
plarpg--------psgvgl------------spnlilvsgkklavqdnp
yfgapy---ilte----sakp---------------ysqvffptqecisg
eafssghcvyv-qklkghks--leglkg--------harhliqsmir-gl
eahkea---lgghgl--vgakigapatlmfpr---hgqcqytkfnfqtch
kvciridl-lslykayilsgakfsvfgslg----hpe--mplyinrtgra
i--------yhlddyvlkgiglptgdpdkdaykgp----ilahaliffvg
mavttgskwldasevqhs---------fanhvall
>ENV_HV2BE/24-510
ltwks--laqvdcepp----ekvcdsvdfe------------------va
-cvksyipnatpd------ftrvkylgiqrnctheektkgyfdgsnyska
mlaaraagpvpwrdlvi--dgnaknakmilkmheqhsyllelvsdpgrfr
pvrvg-dvrefmvkst-alvgylsqkltmalgplhssaiqilgaa-gekr
vggvvh-----fgsvgedkggltpvtcrshpipcpiadgqyqlvlgkefn
pnrtpltecfkgsplvhardryfkvgmikeefkfmffandvkpalwhevh
plarpg--------psgvgl------------spnlivvsgsklavqhnp
yfgaay---ilse----sakp---------------ysqvffpdqecisg
eafpsghcvyv-qklkghks--leglkg--------hsrhliqamir-gl
eahkea---lgghgl--vgvkigapaylmfpr---hgqcqytklnfqtch
kvciridl-lslykayilsgakfsafgslg----hpe--mpmyinrtgra
i--------yhlddyvlkgiglptgdpdkdaykgp----ilahsliffvg
mavltgskwldasevqh----------fanhvall
>node17
ltwkt--laqldaepp----ekvsdsvdge------------------va
-cvksyipnptpd------ftrvkylpvqrncthedklkgyfdgsnyska
mlaaraagpvpwhdlvi--dgaakkakmilkiqeehkyllelvsdagrfr
pvrlgkdvrefmvnstgalvgylsqklsmalgpldasaiqilgaa-gekr
vggvvh-----fgnagedkggltpvtcrenqipcpiidgqyelclgrefn
pnrtaltecfkgsplmhardryfkvgmikeeykfmffsadvnpavwhevh
pfarpg--------psgvgl------------spnlilvsggklaiqdnp
yfgapy---ilne----sakp---------------ysqvffptqecisg
eafssghcvyv-qklkghqs--leglkg--------rarhliqslir-gl
eahkhamyllgghgl--vgapigapatlmypr---hgqcqytefnfqtch
kvciridl-fslykayilsgakfsvfgslg----hpe--mplyinrtgra
i--------yhlddyvlkgiglptgdpdkdaykgp----ilahaliffvg
mavtsgskwldasevqhs---------fanhvtll
>node7
ltwnt--laqldsiep----ektpdctdgeappgtkvsrcdtanemqtva
fevksyipnstad------ffrtkylpvgrncthedklkgyrdggfyskt
mlpikstnpvawhgkve--dgarkkakpvlkvagqqkyll-mvnnsgrfr
svqvakdvrefminstgglvgylshklfvslsslna--iqil-va-ahas
pggvvd-----sgndggdksglkpnncwqhpascavtngqselclkrdfe
pgrtnlpecfqgnpl----drcfkmgvfteeykfli---evncavwhdvn
pfnrpgmgpy---npskagl------------l--llplsgkcecvqani
ifgrpv---rlteslr-evkp---------------ysdtffpkancisa
etfnqghviyv-qkpmshmp--ldglkg--------rtssaieklir-gv
eahnndmyllggvgl--vdkgveapatlmfprqeahdqceytkfnfqvcq
kvcvkiel-yspytayilsgakfstlgtls----qpd--ttlfinrtgra
i--------yhldnyvlkg---------keafngahievilthalkffvg
etatngkkwlqahdflprehvkvg--ssakhltll
>ENV_HV2D2/24-513
ltwkt--lsqldaepp----ekvcksvdge------------------va
-hvrsyidsptpd------fermkymvvqrnctledslkgyldgsdytka
llasraagpvawhdvvi--hgpakkakmilkiqeqhkyllelvsdagrfr
gvrvgkdaralmvnstgslvgylsrkltmalgp---paiqil-da-gekk
vggvvh-----fgnagedkggltpvacqehpapcpiidgqyelclgrefn
pgrealtscfkgsplfhapdryfkvglikeeykflffaadansvlwhevh
pfarpm--------pskvgl------------spnlilvsgsklavqdnp
yfgapy---ilte----takp---------------ysqvffptqecfsg
etfssghcvyl-qklrghks--leglkg--------rarnniqslir-gl
sehkdpmyllgghgl--vgakigapatlmfpr---hglsqytkfnfqech
kvcsridl-fslyssyilsgakfsvlgslgyleghae--mplyinrtgra
s--------yhlddyvlkg---------kdayegp----ipghaliffvg
aavttgkkwldahekrhsshvkvg--afanhivll
>node8
ltwnt--laqldsaep----ektcdctdgeappgtkvsrcdsanemqtva
fevksyipnstad------ffrvkylpvgrncthedklkgyrdggfygka
mlpakatdpvawhgkvi--dgarkkaksvlkvagqhkyll-mvnnsgrfr
svqvakdvrefminstgglvgylshklsvslaslna--iqil-va-ahar
vggvvd-----sgndggdksgfkpnncwqhpascavtdgqyelclkrefe
pgrtnltecfqgnpl----drcfkmgvfkeeykfli---evncavwhdvn
pfnrpgmapy---npskagl------------l--llllsgkcecvqani
ifgaps---kltesvr-qvkp---------------ysdtffpkancisa
etfnqghivyv-qkpkshmp--ldglkg--------rtrsaieslir-gl
eahnnemyllggvgl--vgkavqapatlmfprqvahgqceytkfnfqvcq
kvcvridl-yspytayilsgakfstlgtlg----hpd--ttlyinrtgra
i--------yhldnyvlkg---------keafngahievilahalkffvg
eaattgkkwleahdflpsshvkvg--ssakhltll
>node10
ltwkt--laqldaepp----ekvcdsvdge------------------va
-hvksyipnptpd------ftrvkympvqrncthedklkgyfdgsnyska
llaaraagpvpwhdlvi--hgaakkakmilkiqeqhkyllelvsdagrfr
pvrvgkdvrefmvnstgalvgylsqkltmalgpleasaiqil-aa-gekr
vggvvh-----fgnagedkggltpvtcrehpapcpiidgqyelclgrefn
pgrtaltecfkgsplmhardryfkvgmikeeykflffsadvnpavwhevh
pfarpg--------pskvgl------------spnlilvsgkklavqdnp
yfgapy---ilte----sakp---------------ysqvffptqecisg
etfssghcvyv-qklrghks--leglkg--------rarhaiqslir-gl
eahknamyllgghgl--vgakigapatlmfpr---hgqcqytkfnfqtch
kvciridl-fslysayilsgakfsvlgslg----hpe--mplyinrtgra
i--------yhlddyvlkg---------kdayngp----ilahaliffvg
aavttgkkwldahevqhsshvkvg--afanhvtll
>ENV_HV2G1/23-502
ltwrt--lakldaepp----ekvcdsvdge------------------va
-hvksyipnaapd------ftsvkylpvqrncthedklkgyfdgsnysaa
llaaraagrvpwhnlvi--dgaakkagmilkiqeqhkyllelvsdvgkfr
pvrvgkdvrefmvistsalvgylsqkltmalgpleasaiqilgat-sekr
vggvvh-----fgnagedkgglnpvtcsenpipcpiidgqyelclgrefn
pnrtaltecfkgsplmhardryfkvgmikdeykfmffsgdvnpavwneth
pfarpg--------pspvdl------------spnlilvsgkklavqdnp
yfgapy---ilte---dsakp---------------ysqiffptqecisg
etfssgqcvya-qklkghkspmleglkg--------rarhliqslir-gl
eahkhamyllgghgl--vgakigapatlmfpr---haqchytkfnfqtch
kvciridl-fslysayilsgakfsvfgplg----hpe--mplyidrtgra
i--------ahlddyvlkg---------kdgykgp----ilahaliffvg
mvvttgskwldahevqhs---------fannvtml
>ENV_SIVG1/22-522
ltwnt--lsqldsiep----pktpdctddegppntkvsrcdtsnamitva
fevksyipnstad------ffrtkylpvgrncahedklkgyrnggfysks
mlpikdtnpvawhgkve--dgarnkakpvlkvagqqkyll-mvnnssrfr
siqvakdarefminstgglvgylshkmfvslsslna--mqil-ma-ahas
pggvvd-----sgndggdksglkanncwqhpascagtngqdelclkrdfe
pgwtnlpecfqgnpk----drcfkmgvfteeykfli---evncavwhein
pfnrpgigvy---npskagl------------l--llvlsgkcecvqgnt
ifgrpv---rlteslr-evkp---------------ysdtffpkancisa
etfgqvhviyv-qkpmfhmq--sdglkg--------rtsamieklir-ga
eahhndmyllggsgl--vdkgvdapatlmfprdeahdqcsytkfnfqvcq
nvcvkiel-yspytsyilsgakfstletls----qpn--ttlfidrtgra
i--------yhlnnyvlrg---------keafnnahieviqghalkyfig
etanngkkwlqahdflprehakvgtkssakhltll
>ENV_SIVM1/24-528
lvwkt--laqldaepp----ektcdsvdge------------------va
-hvksyipnstsd------firvkylaver---hedklkgyfdssnygka
mlagraagpvpwhdlvi--dgaakkakmilkvqeqhkyll-lvsnagrfr
pvrvgkdirefmvnstgaligylsqkltmslspleasaiqil-aa-geqr
vggvvh-----fgdkggdksgftpvtcreqpepcplvdgqyelclgrefn
pgrtgstecfqgspvmhardryfkvsmikqeykmlffsadvnpavwhdmn
pfgrpg--------pskvvlvtvnyqfvhyhe-pnlilvsgkslevqdnp
yfgapy---ilte----sakp---------------yaqvffpkqecisg
atfsnghcvyi-qklrghks--ldglkg--------rsrhaipslir-gl
eahnnalyllgghgl--vgakigqpatlmyprqvangqceytkfafqacq
kvciridl-fglysayiksgakfivlgnlg----hpe--mplyigrtgra
i--------yhlddytlag---------kdayngp----ilehaiiffvg
aivttgkkwldahevqhsshvkvg--afenhvt-l
>ENV_SIVGB/47-569
gasktpevanldpakp----ektydytngevplgdksfrcdtvgethtaa
favaaylpndkat------ffkvgylpvgknateeeklyaypggglygrg
ylparttepvtyegkvdfydgnkkkpr----vagrhkvll-mgkasgkir
fsksakdvrtflitctgglfgflahklg-stasl---------vlsvtsr
vagvvd-----fgkdaydksgfspnncwqhaapygptngnyqlslkhefq
sgaas------epp-----drcgntavyktgykfle---pvkcdvfhvah
afdr-esvpyllqnpskagv------------l--lltkskkcqakgani
n-naptehesltasvr-qvkd---------------fqesfftdadcrga
mtfnqvlvvyv-qkppnylp--ldglkgednaptslntksqldsiirrgl
eghsnegyllggaglgf-gkslatvskh---q--mpgrcdytkfkyqncq
klciivel-yspfaatilsgarhseanplg----npattllayitrsgrd
favhnafflyqlkhyivkg---------kelyggqkiklslahpvkiyta
qaalagkkwleshqflagdhcmgi--stnkhss--
>ENV_SIVV1/24-538
ltwdt--lsqlsgiep----ektpdcadgdappgtkvsrcdtpnemqdva
feiknyippstadygalasyfrgkylpvgwncthedklkgfrdggfysks
iltvkstnptawhgkve--dgark-------vagqekyll-mvsksgqfr
siqvandvqefmidstggligvlnhklfvsvsslna--iqil-va-aqes
pggvvd-----sgndggddqglkpnnswqqpascavsngqselclnrdf-
pgrtslvecfqgnrl----nrcfkmgiyteeykfli---evncavwhdvn
pfnrpgagpy---nsskagl------------l--llplggkcecvqanv
ifgrpv---rltealr-evkplhdsmgshdgfkrlrysdcffpkanci-a
dtfnqghviyakqkpmshep--ldglrg--------rtssaieklir-gv
eahnndmylmggvgl--vdkgveapatlmfpaqeahtqcsyakfsfqvcq
kvcvkielnycpyaeyvlnggkfstlsnms----rpd--ttlfinrtgra
i--------yhldnyvnkg---------kealsgahveiiltlalkffvg
eaatngkkwfqahdfqprehvkvg--ssashltll
>node9
ltwkt--laqldaepp----ektcdsvdge------------------va
-hvksyipnstsd------firvkylpvqrncthedklkgyfdgsnygka
llaaraagpvpwhdlvi--dgaakkakmilkvqeqhkyll-lvsnagrfr
pvrvgkdvrefmvnstgaligylsqkltmalspleasaiqil-aa-gekr
vggvvh-----fgntgedksgftpvtcrehpapcpivdgqyelclgrefn
pgrtaltecfqgsplmhardryfkvgmikeeykflffsadvnpavwhdvn
pfgrpg--------pskvgl------------spnlilvsgkslavqdnp
yfgapy---ilte----sakp---------------ysqvffpkqecisg
etfsnghcvyv-qklrghks--leglkg--------rarhaiqslir-gl
eahnnamyllgghgl--vgakigapatlmfprqvahgqceytkfnfqtcq
kvciridl-fslysayilsgakfsvlgslg----hpe--mplyinrtgra
i--------yhlddyvlkg---------kdayngp----ilahaliffvg
aavttgkkwldahevqhsshvkvg--afanhvtll
