>ENV_SIVM1/24-528
---lvymgyhe---vvfwql------pdlfes-glsgniknvvlkipfht
plcplsdg---gvmgsvstltgidlrvwtvptlakiiidqrtfkgqdkvi
ydhvkrsnggtlvgvipdlttddc-----dtgipnngnlpcf-gg-----
fivvtlhlkefstrkchtkpdlkhlqlpcd--cqptcggaltlniskqev
dilfckldegicdpngerici---------lpg-lpglekkvdathtyhv
--tksldhdic-lgmgmlhepagt---------eynfgfipktstwpivc
vfcyikiwkya-------pappvckagyaetatmkpkglaekn---lrly
fhllqglek-vilihlifriiavpsaa-scahrkaplgtvhecasknnlr
ggh--hdkspgkmgagppfldycefadfks--fqvkliasivpgyaygvs
alksdfvpilsndradfkl--kicc----mql--------cchaaffeqv
ct----yqisvkhkvdkvphlvcl--yndvgsidyclvafgavegvsdal
lcp-lvlkdytpqkwlatsaleve--laawgrdhvygrvtrl
>node19
---lvymghhe---vifwql------pdlfes-glngnvtdvilklqfht
p---lkdg---ggmgglsslaaitlrvwtvptlakiiidqrafkgkdkvi
ydhvkrsnggslvglipdlttddc-----etgipgngnlpcl-gg-----
fivltlhlddfstrkchakpdlkhlqlpcdgkcqttcggaltlniskqev
dilfckfddgicdpngerici---------lpg-lpglekkvdatlpyhv
--tkpldhdic-lgmgmlhepagp---------vygfgftpktgtwpivc
vfcyikiwkya-------pappvckagyaetatmkpkgmaekn---lrly
fhllqglek-vilthlgfriiavqsaapscahrneplstahdcaskhslr
ggp--hdkspakmgsgppfldycdfadfks--sqikliaaiyphyayavs
alrggfvgilsndradfkl--kicc----mql--------ychsaffeqe
cs----yqisvkhgvdkvhhlvcl--hntvgsidycllpfgapegvtdtl
lcp-lklkdytpqkwlak--leve--lanwqrdqvygrvtrl
>node9
---lvymghhe---vvfwql------pdlfes-glngnvkdvilkiqfht
p---lsdg---gvmgglstlagitlrvwtvptlakiiidqrafkgkdkvi
ydhvkrsnggslvgiipdlttddc-----dtgipnngnlpcl-gg-----
fivltlhlddfstrkchakpdlkhlqlpcd--cqptcggaltlniskqev
dilfckfddgicdpngerici---------lpg-lpglekkvdatlqyhv
--tkpldhdic-lgmgmlhepagp---------eygfgfqpktgtwpivc
vfcyikiwkya-------pappvckagyaetatmkpkgmaekn---lrly
fhllqglek-vilihlvfriiavqsaapscahrkaplgtvhdcaskhnlr
ggp--hakspakmgsgppfldycdfadfks--sqvkliaaivpgyayavs
alrsdfvpilsndradfkl--kicc----mql--------ychsaffeqv
ct----yqisvkhnvdkvphlvcl--hntvgsidycllpfgapegvtdtl
lcp-lklkdytpqkwlak--leve--laawqrdqvygrvtrl
>ENV_SIVV1/24-538
kskldhlgnhq---vhflel------msvsgr-nf-sfledivlkfqfht
p---l-----------igtlagvtf--rsvk--pkiviektafkgrdkvi
fedvkrksggplvgilkdlssqdcsilwedprspndgrlpcm-gglslvy
fivlvfeysdftpr-----pdlknlhlpcd--cekrvpgalnlnpgtqeg
dvlfcnftdgicdpsgerici---------lpghlptlqkkinatadyhv
krvtp---dia-psmgllhtnaap---------tygfglnaktgkwplic
mvcyin--kyascdassvsspaicnv--------------eidaaqlria
fhllqslsk-vfiihlafevlevqrvseacvqrqlpfgtdhdcanrhsll
glt--rassaarlgkgap-----dvaqvkn--alvqliaavvpgyaynv-
--rngfvpilcdekgeykl--kvvc----lal--------ychtaffqev
ct----yqltvklkv--vahlvclhgpsalgavefssmefnssektp---
---pikikeyvpqkkast--lqia--laawnrdqgydrvasl
>ENV_HV2CA/25-512
---lpymehhe---vifwdleadtfgpdlfes-gldgnvtdvilklqfkt
p---lkdg---sgmgglaslasitlqvwtvptlakiiidqhafkgkdkvi
-dhvkrsn-gslvgliqdlttaec-----eagipgngnlpclegg-----
flvltlhlddfgtrkchakpelkh---pcdgkcqttcggalalnipkqev
dilfckyhegacdpngerisi---------lpg-ppglekdidatlpyhv
--tkwldqdic-tgmgmlqepagp---------vyvfnftaktgawpidc
-fcyikiwkya-------pappvckagyaetatmkpkdmtekn---lkly
fhllqgldk-vilttlgfriiavssaapscvhrneplttaldcaskhslr
ggp--hdktpakmgsgppflkycdftdfks--skikiiaaiyphiayavs
aa-ggyvgilsndradfql--kicc----mql--------ychsafyeqe
cs----yqisvkhgvdkvhhlvcl--hntvgsidycllpfgapegvtdtl
lcp-lklkdytpkkwlak--leie--lanyrrdqvygrvirl
>node8
---ldylghhq---vhflql------pdvfer-nl-gnlkdiflkiqfht
p---lseg---gvmgsiatlagitlrvwsvt--akiviektafkgkdkvi
fedvkrssggplvgiipdlssqdc-----dpqspnggqlpci-gg-----
fiilvfeyddfttr-----pelkhlhlpcd--cepacsgalnlnpgkqdv
dvlfckfkdgicdpngerici---------lpghlptlekkvdataeyhv
rrtkpfdhdis-psmgllhepagp---------dygfgfqpktgkwplvc
vfcyik--kyasctassiaspaicnagyaetaemkakamaeke---lril
fhllqslsk-vfiihmafrvievqsvsetcvhrelplgtvhdcasrhsll
gda--ransparmgngap-----diaqfkn--alvklaaavvpgyaysv-
--ragfvpilsdeksefkl--kvcc----lel--------ychtaffqqv
ct----yqltvkhnvdsvphlvcl--hsalgavefslmpfgtsektt---
----ikikdyvpqktaat--lqva--laawnrdqgydrvarl
>ENV_SIVGB/47-569
---lsyvgl------qylvv------sklfqr-al-epttdiffkvlfht
n---lqealtdgv---ivtltgiklkvwsvt--qkvv-----fkg-----
----krdsggttmgtiaglseq-------npqtpagg-------------
-isvnfqseefacr-----pelkqlylpse--sgppctgefnlspgnqsv
evqfcsfkhgvrkangdaicvgitglkscpl--------kradcsnnyqt
eytnsfnndlgdsdtgllrdpagp---------dygyvfspscglspgac
v-cyia--------cpaiastdicnagnaeveammakamaqke---grid
iellksltkgnffvqmiykvitvqsiseacv-ralslatgkecdsehpll
ceaarrahgalrigngap-----svppfkhslmdlklgvavvpglnysa-
--smsyisresdekdafeltrkvvcnhetldl--------gchqaffqal
ct----yqlnikravdatlivvcl--psll-------lsfgvaksva---
----ikt--ygpkttvar--vple--lnaweraegyervarl
>ENV_HV2BE/24-510
---lvamgh-----vkfwql------pdlfqs-glngnvadvilslqfht
p---lkdg---gemgglsslaaivlevwtvptlakiiidqrafkgkdkvl
ydhvkessggdlcglipdlttdsc-----epgiqgngnlpcl-gg-----
fivltlhlddfsarkchskpdlkhlqipcdgkcqtscggaltlniskqiv
dilfckfddgicdpngerici---------lpg-lpglekkvdatlpyht
--tkpldhdic-lgmgmlpepagp---------vygfgftpktgswpivc
vfcyikiwkya-------pappvckagysesaamkpkgmsekn---lrly
fhllqglek-vilthlgfrilavqraqpscihrneplstahkcaakhslr
ggp--hdksppkmgsgppfldycdfgdfks--sqiklisaikphyayavs
alrggfvgilsndradfkl--ticc----mql--------ychwaffeqe
---------avkhaadkvhhlmcl--hntvgridycllpfgavesvtdtl
lcp-vklkdyapqkwlak--levd--lanwqrdqvygkvtrl
>ENV_SIVG1/22-522
---vdhlgshe---vhflql------mearar-dl-gflqdiilkfqyht
p---l-----------igtlagial--wsit--akiviektgfkgrtkvi
fedvkrrsggpfvgilpdlasqdc-----dpespnggrlpcm-gg-----
fivlvfeysdltvr-----pdlkhlhlpcd--cdkqcsgavnlnpgkqdg
dvlfckfkdgicdpsgerici---------lqghlptlqkkvdatadyhv
rrkkp---dia-ppmgllhepagp---------tygfglqpktgkwplvc
vfcyik--kyasctassiaspaicnvgyaetaemrakekadke---lril
fhllrslsk-vye-hmafevidaqr--etcvhrelplgtahdranrhsll
gga--rvnsaarmgngap-----dtpqykp--alvkliaalvpgyaysv-
--rtgfvtilcdekgeykl--kvvc----lel--------ychtaffqnv
ct----yqltvkhnvtpvahlvcl--nsalgtvafslmefetsekat---
----ikikdyveqkka------vaaklaasnwdqgydrvarl
>node7
---ldhlgnhq---vhflql------mevser-nl-gflqdiflkfqfht
p---l-----------igtlagitl--wsvt--akiviektafkgrdkvi
fedvkrrsggplvgilpdlssqdc-----dpqspnggrlpcm-gg-----
fiilvfeysdfttr-----pdlkhlhlpcd--cekqcsgalnlnpgkqdg
dvlfckfkdgicdpsgerici---------lpghlptlqkkvdatadyhv
rrvkp---dia-psmgllhepagp---------tygfglqpktgkwplvc
vfcyik--kyasctassiaspaicnvgyaetaemrakakaeke---lril
fhllqslsk-vfiihmafevidvqrvsetcvhrelplgtahdcanrhsll
gda--rassaarmgngap-----diaqykn--alvkliaavvpgyaysv-
--rtgfvpilcdekgeykl--kvvc----lel--------ychtaffqev
ct----yqltvkhnvtsvahlvcl--hsalgavefslmefetsektt---
----ikikdyvpqkkast--lqva--laawnrdqgydrvarl
>ENV_HV2G1/23-502
---lvymghhe---vifwql------pdlyes-glngnvtdvilklqfht
p---lkdg---ggmgglsslagitlrvwvvptlakiiidqrafkgkdkvi
ydhvkrsnggslvgfipdlttddc-----etgip-ngalpcv-gg-----
fivltlhldafstrkchakpdlqhlqlpcdgkcqttcggaltlninkqev
dilfckfddgicdpngerici---------lpg-lpsfekkvdatlpyhv
--tkpldhdic-lgmgmlhepagp---------vygfgftpktgtwpivc
vfcyikiwkya-------pappvckagyaetatmkpkgmaekn---l---
-hllqglek-vllthlgfriiavqsaapscahrneplstahdcaakhslr
ggp--hdkspakmgsgppll-----------------iaaiyphyayais
alrggfvgilsndradfkm--ricc----mqlarvakgnhychsaffeme
cs----yeisvkhgvnkvhhlvcl--hntvgsidycllpigapegvtdtl
lcp-lklkdytphkwlak--leve--lfnwqrdevygrvtrl
>node14
---lvamghhe---vifwql------pdlfes-glngnvtdvilklqfht
p---lkdg---ggmgglsslaaivlevwtvptlakiivdqrafkgkdkvl
ydhvkqssggslcglipdlttddc-----etgiqgngnlpcl-gg-----
fivltlhlddfstrkchakpdlkhlqlpcdgkcqttcggaltlniskqev
dilfckfddgicdpngerici---------lpg-lpglekkvdatlpyhv
--tkpldhdic-lgmgmlhepagp---------vygfgftpktgtwpivc
vfcyikiwkya-------pappvckagyaetaamkpkgmsekn---lrly
fhllqglek-vilthlgfrilavqraapscahrneplstahdcaakhslr
ggp--hdksppkmgsgppfldycdfadfks--sqikliaaiyphyayavs
alrggfvgilsndradfkl--ticc----mql--------ychwaffeqe
cs----yqisvkhgvdkvhhlvcl--hntvgsidycllpfgapegvtdtl
lcp-lklkdyapqkwlak--leve--lanwqrdqvygrvtrl
>node11
---lvymghhe---vifwql------pdlfes-glngnvtdvilklqfht
p---lkdg---ggmgglsslagitlrvwtvptlakiiidqrafkgkdkvi
ydhvkrsnggslvglipdlttddc-----etgipgngnlpcl-gg-----
fivltlhlddfstrkchakpdlkhlqlpcdgkcqttcggaltlniskqev
dilfckfddgicdpngerici---------lpg-lpglekkvdatlpyhv
--tkpldhdic-lgmgmlhepagp---------vygfgftpktgtwpivc
vfcyikiwkya-------pappvckagyaetatmkpkgmaekn---lrly
fhllqglek-vilthlgfriiavqsaapscahrneplstahdcaskhslr
ggp--hdkspakmgsgppfldycdfadfks--sqikliaaiyphyayavs
alrggfvgilsndradfkl--kicc----mql--------ychsaffeqe
cs----yqisvkhgvdkvhhlvcl--hntvgsidycllpfgapegvtdtl
lcp-lklkdytpqkwlak--leve--lanwqrdqvygrvtrl
>node17
---lvymghhe---vifwql------pdlfes-glngnvtdvilklqfht
p---lkdg---sgmgglsslaaitlqvwtvptlakiiidqrafkgkdkvi
ydhvkrsn-gslvglipdlttadc-----etgipgngnlpcl-gg-----
fivltlhlddfstrkchakpelkhlqlpcdgkcqttcggaltlniskqev
dilfckyddgicdpngerici---------lpg-lpglekkvdatlpyhv
--tkpldhdic-lgmgmlhepagp---------vyvfnftpktgtwpivc
vfcyikiwkya-------pappvckagyaetatmkpkdmaekn---lrly
fhllqglek-vilthlgfriiavqsaapscvhrneplstahdcaskhslr
ggp--hdktpakmgsgppfldycdfadfks--sqikliaaiyphyayavs
alrggfvgilsndradfql--kicc----mql--------ychsaffeqe
cs----yqisvkhgvdkvhhlvcl--hntvgsidycllpfgapegvtdtl
lcp-lklkdytpqkwlak--leve--lanwqrdqvygrvirl
>ENV_HV2D1/24-501
---lvamghhelctviflql------qdlfds-glngnvtdvilklqfht
p---lkdg---ggmggldslaaivlivwtvptlakiivkqrafkskdkvl
ydhvkqssggslcgliadlttddy-----etgiqgngnlpcl-gg-----
fivltlhlddfstrkchakpdlkhlqlpcdskcqttcggaltlniskqev
nilfckfddgicdpngerici---------lpg-lpglekkidatlpyhv
--skpldhdac-lgmgllhepagpvschrprkfvygfgftpktgtwpivc
vfcyikiwkya-------paspvckagyaetsamppkgmsekn---lrly
fhllqglek-tilthlgfrilavqrtapscahrneplstahdcaakhalr
gap--hdrsspnmgsgppfldycdfadfks--sqikliaadyphyayavs
alrggfvgilskdradfkm--ticc----mql--------ychwaffeqe
cs----yqisvkhgvdkvhhlvcl--hntvasinycllpfgapegvtdtl
lcp-lklkdygpqkwlat--leve--lanwqrdqvygrvary
>node10
---lvymghhe---vvfwql------pdlfes-glngnvkdvilklqfht
p---lsdg---ggmgglstlagitlrvwtvptlakiiidqrafkgkdkvi
ydhvkrsnggslvgiipdlttddc-----dtgipnngnlpcl-gg-----
fivltlhlddfstrkchakpdlkhlqlpcdgkcqttcggaltlniskqev
dilfckfddgicdpngerici---------lpg-lpglekkvdatlpyhv
--tkpldhdic-lgmgmlhepagp---------vygfgftpktgtwpivc
vfcyikiwkya-------pappvckagyaetatmkpkgmaekn---lrly
fhllqglek-vilihlvfriiavqsaapscahrkeplstahdcaskhnlr
ggp--hdkspakmgsgppfldycdfadfks--sqikliaaivphyayavs
alrgdfvgilsndradfkl--kicc----mql--------ychsaffeqe
cs----yqisvkhnvdkvphlvcl--hntvgsidycllpfgapegvtdtl
lcp-lklkdytpqkwlak--leve--laawqrdqvygrvtrl
>ENV_HV2D2/24-513
---mmymghhe---ivfwqi------pdlfesgslkgnvsdvilkfqfht
p---lsdg---ggmgglsslagitlrvwavptlakiiiddrafkhkdkvi
ydhekrsnggglvpimpdlttdnc-----ntgipnngnlpcf-gg-----
flvltlhlgdftsskchakpdlkhlqlpsdgkchttcggalklnisgqev
dil---fddgicdpngerici---------lpg-lpdlqkkvdaslpyhv
--tkpldhdic-lglgmlhepagp---------vygygftpktgtwpivc
vfcyakswlia-------pappvcqagyaetatmkpkgmaekd---lrly
fhllkglek-vilinlvfsiigvqsaapscahcreplstahhcaskhnlr
gap--hdkspakmgsgppildycdfadfks--sqikliaaivpdyayvvs
alrnqfvgilsndqadfkt--sicc----fql--------ychkaffeqe
cs----yqisvkhnvdkvphlvcl--hdtvgsidycllpfgasegvtdtl
lcp-lrlkgytpqkwlak--leye--ldawqrdqvygrvkrl
>node18
---lvymghhe---vifwql------pdlfes-glngnvtdvilklqfht
p---lkdg---ggmgglsslaaitlqvwtvptlakiiidqrafkgkdkvi
ydhvkrsnggslvglipdlttddc-----etgipgngnlpcl-gg-----
fivltlhlddfstrkchakpdlkhlqlpcdgkcqttcggaltlniskqev
dilfckfddgicdpngerici---------lpg-lpglekkvdatlpyhv
--tkpldhdic-lgmgmlhepagp---------vygfgftpktgtwpivc
vfcyikiwkya-------pappvckagyaetatmkpkgmaekn---lrly
fhllqglek-vilthlgfriiavqsaapscahrneplstahdcaskhslr
ggp--hdkspakmgsgppfldycdfadfks--sqikliaaiyphyayavs
alrggfvgilsndradfkl--kicc----mql--------ychsaffeqe
cs----yqisvkhgvdkvhhlvcl--hntvgsidycllpfgapegvtdtl
lcp-lklkdytpqkwlak--leve--lanwqrdqvygrvtrl
>ENV_HV2NZ/24-502
---lvymghhe---viywql------pdlfes-glhgnvtdvtlklqfhn
p---lkdg---sgtgglsslapitlqvwtvpslakiiidqrafkgrdkvl
ydhakrsn-nslvglipdlttadc-----etgipgngnlpcl-sg-----
fivltlhlddfslrkcyampelkhfqlpcdgkcqttcggaltlnlskqev
dilfckyddgicdpngericl---------lpg-lpglekkvdatlpyhv
--tkpldhdic-lgmgmlhapagp---------vyvfhftpktgtwpivc
ffcyikiwkya-------pappvckag--------pkemaekd---lrly
fhllqgldk-vilthlgfqi--vqgvapscvhrteplatahdcaanhnlr
ggp--hdttaakmgkgppflnycdfadfks--sevklvaaiyphygyavs
alrggfvgilsndradfql--ktcc----mql--------ychsaffeqd
csktgqyqisvkhgvdkvhhlvcl--lntvgsvdycllpfgapegvtdtm
lcp-lkvkdytphkwltk--leve--lanwqrdqvygrvirl
