>node10
eggtkgevggyhgkkaayhqvrkst----kvvhfpddekag---------
-cs----kcrnkadyhftfslhy-----dhhvgdkkvtsrkg------v-
-eaqknip-l----senlgn--lfckgeydltfn-ggt--fksdk-tvsp
a--aalp--g-te-tfgskttqkdskssavglkdk--qdq--qhlgdqdi
lsvgetaesrsgdlqirqepgvrytyhc--dqlkfltsv---hrckamla
ypadpqgqrqklgrkgeag-haalysdysgs-ggnatkmvqhvsqvrv--
gyp----tsglgfpsc-gpenfqygnia------wdpakptgdgiesvgk
alcqsk-pldag-------knkeckivvsltrle-aslppniaagialyn
ninfiapvhqktdsiq--------pcsda---ksidgdkqgiptr--tar
linlfy--ckgraqsgfmrhldaamtk-lyvsvsqldltpstvttcktnk
pvrtafnlcrsvlk-gatg----pkqvkadnd--pvtgpdqk--gqkilv
kfvltgidamenypg-nywslcqsy---asqrglhgspyd------kshv
--vr---rlagpgvv----cy-
>ENV_SIVGB/47-569
pkfnmgevdgskgrrvpyplvqsstvsspkvvyfpkvgkdgapgvaakqe
hvh----r-----dsimtfeihy-----d------qveavhgtanhkga-
-dspnavpvltydkgnkiigsdlfvklasdqsyntaka--yysan-ascq
l-datlpipd-tl-sskhaat------mchglkcaciknqpqqhkgdaai
lkkgdspdartgdlgpq-qegvpstctcriekieflhksknhhsrs-hme
yiadlatq-----asgets-ngskyktytgs-ggalqdmgggfnrvdlkr
rya----agviglssc-gp--fhrgslt------wnlfdpseatlensgl
llpqvk-age------------nckiplam-ra--aymmaknatgiev-k
ratfgaplhekrsgiemeaahtglacsdevvlkcvsgpktsliti--ggr
vvdmfy--issvpqsd----lqaalvk-iyvdedpqnmkgvaids-----
-lnadytldcsdlq-vava----applkaqastn-gsapdkdcggsstlv
rfqgvgvgapgkypgykywglc------qshkgqvtapyd------gkhv
--vr---wlaatcvv----cyg
>node18
egatkgevggyhgkkaaynqvrkst----kvvhfpdeekag---------
-csassakcrnkadyhftfslhy-----dhevgdkkvtsrkg------v-
-eaqknvp-l----senlgn--lfckgeydltfh-ggt--fksdk-tvsp
a--saap--g-te-tfgskttqkdskssavglkdk--qdq--qhfgnqdi
lsvgetaqsrsgdlqirqepgvrytyhc--dqlkfltsv---hrckamla
ypadpqgqrqklgrkgeag-haalysdysgs-ggnatkmvqhvsqvrv--
gyp----tsglgfpsc-gpenfqygnia------wdpakptgdgiesvgk
alcqsk-pldag-------knkeckipvsltrle-aslppniaagialyd
ninfiapvhqktdsiq--------pcsda---ksidgdrqgiptr--tar
linlfy--ckgraqsgfmrhldaamtt-lyvsvsqldltpstvttcktnk
pvrtafnlcrsvlk-gatg----pkqvkadnd--pvtgpdqk--gqkilv
kfvltginamenypg-nywslcqsy---asqrglhgspyd------kshv
apvr---rlagpgvv----cy-
>ENV_HV2NZ/24-502
egamkgevggyhgkkagynpvresl----kqvhypdeekag---------
-csaksakcrnkadyhfsfslhy-----dhevgdkrvstrkg------aa
leakknvp-v----setlgn--lfckgeydltfh-ggt--ftsnk-tvsp
d--satp--g-te-tfgskttqkdskasglglkdk--qdq--qhfgnqdi
lsvgataqsrsgdlqirrepgvrytyhc--dqlkfltsv---rrckaili
yraepkgqrrklgrrgeagfeaalysdysgs-ggnatrkvhhtsqvrv--
gyp----tsglgfesc-gpenftygnia------wdpakptgdgigsvgk
alcqgk-pldvg-------knkeckipvsltrle-yslppniaagialyd
kinfi--vhqksdslq--------pctqa---ksidgdrqgiptqvhtar
iinlfy------aqsgfmrhldramtt-lyvsgshldltpsvvttcktnk
pvrtafnlcrsvlkkgatgiysvpkqvkadnd--pvtgpdhk--gqkilv
kfvltginamenypg-nywslcqsy---asqrglhgstyd------kshv
apvr---rlagpgvvmlqvcy-
>node14
egatkgevggyhgkkaaynqvrkst----kvvhfpdeekag---------
-csasshkcrnkadyhftfslky-----dhevgdkkvtsrkg------v-
-eaqknvp-l----senlgn--lfckgeydltfh-ggt--fksdk-tvsp
a--saap--g-te-tfgskttqkdskssavglkdk--qdq--qhfgnqdi
lsvgetaqsrsgdlqirqepgvrytysc--dqlkfltsv---hrckamla
fpadpqgqrqklghkgeag-yaalysdykgs-ggnatkmvqhvsqvrv--
gyp----tsglgfpsc-gpenflysnia------wdpakptgdgidsvgk
alcqsk-pldag-------knkec-ipvsltrle-aslppniaggialyd
ninfiapvhqktnsiq--------pctda---ksidgdrqgiptr--tar
linlfy--ckgraqsgfmrhldaamtt-lyvsvsqldltpstvttckknk
pvrtafnlcrsvlk-katg----pkqvkadnd--pvtgpdqk--gqkilv
kfvltginamenypg-nywslcqsy---asqrglhgspyd------kshv
apvr---rlagpgvv----cy-
>node17
egatkgevggyhgkkagynqvrkst----kvvhfpdeekag---------
-csaksakcrnkadyhftfslhy-----dhevgdkkvssrkg------va
leaqknvp-l----senlgn--lfckgeydltfh-ggt--fksdk-tvsp
a--saap--g-te-tfgskttqkdskssavglkdk--qdq--qhfgnqdi
lsvgetaqsrsgdlqirqepgvrytyhc--dqlkfltsv---hrckaila
ypaepqgqrrklgrrgeag-eaalysdysgs-ggnatkkvqhvsqvrv--
gyp----tsglgfpsc-gpenfqygnia------wdpakptgdgiesvgk
alcqsk-pldeg-------knkeckipvsltrle-aslppniaagialyd
ninfi--vhqktdsiq--------pcsda---ksidgdrqgiptr--tar
linlfy--ckgraqsgfmrhldaamtt-lyvsvsqldltpstvttcktnk
pvrtafnlcrsvlk-gatg----pkqvkadnd--pvtgpdhk--gqkilv
kfvltginamenypg-nywslcqsy---asqrglhgspyd------kshv
apvr---rlagpgvv----cy-
>ENV_HV2G1/23-502
egatkgkvggyhskkaaynqvryst----kvvhfpddekag---------
-csassakcrnkadyhftfalhyenylpdheggdkkvtsrkg------v-
-aaqknip-l----senlgn--lfckeeyeltfh-ggt--fksdk-tvsp
a--saap--gate-tfgskttqkdpkssavglkek--qdq--qhfanqdi
lsvgetaqsrsgdleirqepavrytyhc--dqlkflttv---hrckamla
ypadpqaqrqklgrkgeag-haalysdysgs-ggnatk--qhvsqvkv--
gyp----psglgfpsc-gpenfqygnia------wdpakptedgiesvgk
alcqsk-pldag-------knkeckipvsltkle-a-------agialyn
ninfiapvhhktdsiq--------pcsda---ksidsdrhgiptk--tar
litlfy--ckgraqsglmrhldtgmtt-lyvsvsqlsltkstvttcktkk
pvrtafnlcrsvlk-gatg----pkqvgadnd--pvagpdqk--gqkilv
kfvltginamenypg-nywnlcqsy---asqrglngspyd------kshi
--vr---rlagpgnv----cy-
>ENV_HV2D1/24-501
egatkgevggyhgkkaaynqvrgsv----kvvhfpdsekag---------
-csassckcrnkadyhftfslky-----dhevgdkkvtslkg------v-
-qaqknvp-l----senlgn--lfckgeydltfq-ggt--fksdk-avnp
ak-saap--g-te-tfgskttqkdsksskvglkkk--qdq--khfgnqdi
lsvqetaqsr---------pgvrytyac--dqlkfltsv---frckamls
fpadpqgqrqklghkgeag-yaalysdyk---gdnatkmvqhvsqvrv--
gyp----tsglgfpsc-gpenyvysnia------wdpakptgdgidsvgs
alcqsk-pleaglpynpqtknkec-ipvsltrle-aslppkiaggialyd
ninfiapvhqktnseq--------pcnda---ksidgdrqgiptr--tar
linlfy--ckgraqsgfmrhldaamttklyvsvsqldltpstvstckkdk
pvrtafnlcrtvlk-katg----pkqvaadnd--pvtgpdqk--gnkilv
kfvltginamenypg-nywsqcqsy---asqrglhgspyd------tshv
apvr---rlagpgvv----cy-
>node9
eggtkgevggthgkkaayhqvrkst----kvvhfpedekag---------
-cs----kcrnkadyhftfslhy-----dhhvgdkkvtsrkg------v-
-eaqknip-l----senlgn--lfckgeydlsfk-ggt--fksdk-tvsp
a--aalp--g-te-tfgskttqkdnkstpvglkdk--qdq--qhlgdqdi
lsvgetaesrsgdlqirqepgvrytyhc--qqlkfltsv---hrck-mla
ypadpqgqrqklgakgeag-haalysdysgs-ggnatkmvqhvsqvrv--
gyp----tsglgfpsc-gpenfqygnna------wdpakptadgiesvgk
alcqsk-pldag-------knkeckivvsltrle-aslppniaagialyn
ninfiapvhqktdsiq--------pcsda---ksvdgdkqeiptr--tar
linlfy--ckgrtqsgfmrhldaamtk-lyvsvnqldltpstvttcktnk
pvrtafnlcrsalk-gatg----pkqlkadnd--pgtgpdqk--gqkilv
kfvltgidalenypg-nywslcqsy---psrrglhgspyd------kshv
--vr---rlagpgvv----cy-
>ENV_HV2CA/25-512
eaggkteaggyhgkkavynqvrkst----kvvhfpdeeksg---------
-csassakcrnkadyhftfslhy-----dhevgdkkvssrkg------va
leaqrnvp-l----senlgn--lfckgetdltfh-ggt--fksdk-avsp
a--saap--g-te-tfgskttqigsklsavglkdk--qdq--ehfgdqdi
lsvaetaqsrsgdlqirqepgvrytyhc--dqlrfltti---hrckaila
ypaepqghrrkagrrgetg-eaaiysdksgsfggnetkkvqhvsqvrl--
gypalistsglgfpsc-gpedfqygnia------wdpakptgdgiesvgk
afcqsk-pldtg-------knkeckisvsltrld-sslppniaagialye
ninfi--vhqktdsiq--------pcssa---ksidgdsqgiptr--tar
linlfy--ckgraqsdfmrhldaamtt-lyvsvsqldltpstvttcktnk
pvptafnlcrsvlk-gatg----pkqvkadnd--pvtgpdrk--gqkilv
kfvltginalenyag-nywflcqsy---asqrglhgstyd------kshv
apvrdvsrlagagvv----cy-
>node19
egatkgevggyhgkkaaynqvrkst----kvvhfpddekag---------
-csassakcrnkadyhftfslhy-----dhevgdkkvtsrkg------v-
-eaqknip-l----senlgn--lfckgeydltfh-ggt--fksdk-tvsp
a--saap--g-te-tfgskttqkdskssavglkdk--qdq--qhfgnqdi
lsvgetaqsrsgdlqirqepgvrytyhc--dqlkfltsv---hrckamla
ypadpqgqrqklgrkgeag-haalysdysgs-ggnatkmvqhvsqvrv--
gyp----tsglgfpsc-gpenfqygnia------wdpakptgdgiesvgk
alcqsk-pldag-------knkeckipvsltrle-aslppniaagialyd
ninfiapvhqktdsiq--------pcsda---ksidgdrqgiptr--tar
linlfy--ckgraqsgfmrhldaamtt-lyvsvsqldltpstvttcktnk
pvrtafnlcrsvlk-gatg----pkqvkadnd--pvtgpdqk--gqkilv
kfvltginamenypg-nywslcqsy---asqrglhgspyd------kshv
--vr---rlagpgvv----cy-
>ENV_SIVG1/22-522
iaetkgevkgtngkktpyhlvrksp----kvvhfpeaerdg---------
-ct----r-----dynftfnihy-----efhvgnnevapshg------v-
-eekkavr-l----gerlgg--lfckgaytlsyt-ggs--iksdk-vvsp
a--eama--g-tl-sfgekdt------gchglkct--qdn--qhtgdqei
lnlgeavdartgdlqekqskgaryayhc--eqlkflvkpstvhrck-lma
yvadvqpnkerlgakgeaa-hsnlyddysgs-ggnltkmvqhlagvrirr
tya----ppstgltsc-gpesfqkgnlaaiivpewdpykpttrgyesval
qlcgsk-pregg-------kmkecrvvval-kpeaatlnaniapgiav-n
ktnfvapihqktnggq--------pcydaivmscvggdpeeiltk--tsr
lidlfy--ckgktesgfkrhlqarmtm-fyvnedpidmtsgavtscktkk
pvgsnfsaccgdlr---------------------gtapqik--gqrtlv
kfpvpgvdts-gyeg-dyrklcqsy---atrqglhaapyd------gnhv
--vr---rlasasvv----cy-
>ENV_HV2BE/24-510
egatkgevggyhgkkaaynqvrkst----kvlhfpdeekag---------
-csasthkcsnkadyhftfslky-----dhevgdkkvtsrkg------v-
-eaqknvp-l----senlgn--lfckgeydlsfh-ggt--fksdkatvsp
a--saap--g-te-tfgskttqkdskssavglrdk--qdq--qhygdqni
lsvgetaqsrsgdlqirqepavrytysc--dqlkfltsv---hrckamla
fpa--qgqrqklghkgeag-yaalysdykgs-ggnatkmvqhvsqvrv--
gyp----tsgkgfpsc-gpenflysnis------wdptkptgdginavgk
alcank-slqsg-------kvkdc-tpvsltrle-aslppnlaggialyd
ninfiapvhekqnsiq--------pctda---ksidgdrrgiptr--tar
linlfyqackgraqsgfmrhldaamts-lyvsishldltpptvttck-nk
pvrtafnlcrsalk-katg----pkqvkadnd--pvtgpdqk--gqkilv
kfvitginamenypg-nywslcqsy---asqrglhgspyd------kshv
apvr---rlagpgvv----cy-
>ENV_SIVV1/24-538
iagtkedvrgttgkkmpyhlvrksp----kplpfpeankdg---------
-ct----r-----dyhftfsihy-----efhvgnghaapshg------v-
-qekkavr-l----gerlgg--lfckgaynlsyt-ggg--fkskk-vvsp
t--eala--g-tlvsfgqknt------gcrglkct--qdq--qhtgkedi
lnvsnptdartgdlqakqsqgtryayhc--aqlkfvvkpsvhhkck-ima
yvadvqpnkqrlgakgdvt-hsslyndysgs-gggltkmvthlagvrirr
tya----paplgltsctgpksfekgdvpeiitpewdpykpttqgyttval
qmcgsk-pvdgg-------kmkecktvvll-rpeaatlkgnsaagipv-n
ktnfvaplhqktngvd--------acsdavvmscaagdpeeiltk--tsk
lidiyy--cngktqsgfrrhlqarmam-iyvsedpldlttgaiaacktne
aveknfslccgelq-aals----nhslkadngykrgtepnql--gqrplv
kfpvagvdtl-nyeg-dyrslcqgy---atrqglhaapydckphcvgnha
--vr---rlagasvv----cy-
>ENV_HV2D2/24-513
gggtkgevggyyetkaaylqvrkst----kvihfpddekag---------
-cs----kcrnkadyhftfslay-----ghhvgdkkvtshkg------v-
-eaqkn-p-l----senlgn--lfckgenqltfd-ggt--fksdk-tvsp
a--atlp--g-te-tfgskttqkdskssavglkdk--qdq--qhlndqdi
lpvgetaegrsgdvqiregpgvrytyhc--drlkfltsv---hrckamla
yranprgqrqklgrkgeag-haplysdysgs-ggnapamvqhvsqvrv--
eas----tsglgfpsc-gpenfqygdia------wepakptgdgiesvgk
alcqtkrpldqg-------rnkdckivvsltrle-vslppniaagialyn
nidfvapvhqptds-q--------scsds---ksvdgekqdipar--tar
linlfy--ckgraqsgfmrhldatmtt-lyvkvsqldltpsavttcqtnk
pvktafnlcrsvlk-gapg----pkqvkadnd--patgpdkk--geqilv
kfvltvvdamenyag-pywspcnsy---asqkalhgspyd------hshv
--vr---rlagpgvv----cy-
>node7
iagtkgevkgtngkkvpyhlvrksp----kvvhfpeaekdg---------
-ct----r-----dyhftfsihy-----efhvgnnevapshg------v-
-eekkavr-l----gerlgg--lfckgaynlsyt-ggg--fksdk-vvsp
a--eama--g-tl-sfgqkdt------gcrglkct--qdq--qhtgdeei
lnvgeavdartgdlqakqsqgtryayhc--eqlkflvkpsthhrck-lma
yvadvqpnkqrlgakgeaa-hsglyddysgs-ggnltkmvqhlagvrirr
tya----psslgltsc-gpesfekgniaaiivpewdpykpttqgyesval
qlcgsk-pvegg-------kmkeckvvval-kpeaatlnaniaagiav-n
ktnfvaplhqktngvq--------pcsdaivmscvggdpeeiltk--tsr
lidlfy--ckgktqsgfkrhlqarmtm-iyvsedpldmtsgavtscktnk
pvetnfslccgdlq-aaig----ahplkadngykpgtapqqk--gqrtlv
kfpvpgvdtl-nyeg-dyrslcqsy---atrqglhaapyd------gnhv
--vr---rlagasvv----cy-
>ENV_SIVM1/24-528
eggtkgevggthgkkagyhsvrnst----kvvsfpedekag---------
-cs----kcrntadahftfslhy-----dhhvgakkvekrkg------v-
-eaqknip-l----teslgn--lfckgeydlsfk-ggtgefkadk-tvsc
a--aalp--v-te-tfgskttqkddkstpvglndq--qdq--qhlgeqdi
lsvvetaesrsgdlqirqdpgvrytyhc--qqlkflssv---arck-mla
ypadpqgqrqklgakgeae-haelytdyngs-ggnatkmvqhvsqv----
---------glgfass-gpenfqygnna------wdpakptadgiesvgk
alcqsk-pldag-------knkeckivvsltrle-aslppniaagialyn
ninfiapvhqktdsiq--------pcsda---ksvdgdkqgiptr--tar
linlfy--ckgrtqsgfkhhldaamtk-lyvsvnqldltpstvvtcktnt
pvrtafnlcrsalk-gatg----pkqlkadnd--sgtgpdqk--gqkilv
kfvlsgidalenypg-nywplcqsyaqmpsrrgthgspyd------kshv
--cr---rlagpgvi----cy-
>node8
ikgtkgevagtkgkkvpyhlvrkst----kvvhfpeaekdg---------
-cs----r-----dyhftfsihy-----eyhvgnnevaprhg------v-
-eekkavp-l----gerlgg--lfckgaydlsyt-ggg--fksdk-vvsp
a--ealp--g-tl-sfgrkdt------scrglkck--qdq--qhtgdeei
lnvgetvdartgdlqikqeqgvryayhc--eqlkflvkpkthhrck-lma
yvadpqsnkqrlgakgeaa-haalyndysgs-ggnltkmvqhlaqvrikr
tya----ssglgltsc-gpesfergnna------wdpykpttqgyesvgl
slcqsk-pveag-------kmkeckivval-rpe-atlpaniaagiav-n
ktnfvaplhqktngiq--------pcsdaivlkcvggdrqeiltk--tar
lidmfy--ckgrtqsgfkrhlqaamtk-iyvsedpldmtssavtscktnk
pvdtnfslccsdlq-aaig----akplkadndykpgtapqqk--gqrtlv
kfvvagvdtlgnyeg-kywslcqsy---ptrrglhaapyd------gshv
--vr---rlagacvv----cy-
>node11
egatkgevggyhgkkaaynqvrkst----kvvhfpddekag---------
-csassakcrnkadyhftfslhy-----dhevgdkkvtsrkg------v-
-eaqknip-l----senlgn--lfckgeydltfh-ggt--fksdk-tvsp
a--saap--g-te-tfgskttqkdskssavglkdk--qdq--qhfgnqdi
lsvgetaqsrsgdlqirqepgvrytyhc--dqlkfltsv---hrckamla
ypadpqgqrqklgrkgeag-haalysdysgs-ggnatkmvqhvsqvrv--
gyp----tsglgfpsc-gpenfqygnia------wdpakptgdgiesvgk
alcqsk-pldag-------knkeckipvsltrle-aslppniaagialyn
ninfiapvhqktdsiq--------pcsda---ksidgdrqgiptr--tar
linlfy--ckgraqsgfmrhldaamtt-lyvsvsqldltpstvttcktnk
pvrtafnlcrsvlk-gatg----pkqvkadnd--pvtgpdqk--gqkilv
kfvltginamenypg-nywslcqsy---asqrglhgspyd------kshv
--vr---rlagpgvv----cy-
