>node9
gn--------lffslinlge-----girpgrttvaqy-vtqkslrahyfr
ckvvksinnklkvesaakeealevkakhvhfnegddfd-ldas----hvs
spepdrdgeaqiktetaigd------------sr-stklvm--ycdsefg
sfliy-s---rkdt-ksvnwkllvgalsppaeskefaigtdstlsplkye
gtgsigkmslgetaqrsfq------ltkpantvlspvnvvyqkede----
-kdyvqwiivgagsgc---r-viagacpdqqkyaigqefvffkf-----h
akqnvhknit------plkscfrilki----hreig--kavqq--gahyl
vhimlgslgfriyve----kgiklhegekqidpyvlmtgrvktptqlrka
clshwsdqckdigpklfagdgdgkavaqdqkkl-svfiegfdtrk-lwve
tdltlkpfqnhlayigfgqatlvtlpeagsnaktedgassscvdvavi-k
fvlggvhsrrtsft-----vrlgvqy-qmlgqh-----gta-----tvkn
ffsglg-glyhfcvkddlfaktaypygaclf-------------------
-galgdnleldslysdrfthte
>ENV_HV2CA/25-512
gn--------lffqlinlge-----girpgrttvgqy-vtqkklrahyhr
ckvvklfinklkvqsaaakealdvkaervhfsegedfy-ldas----hvt
spepdkddaaqirtetaigadncpcdayckvhkr-stklvm--ycvsefg
sflty-skyyrkdt-ksvnwk------sppaeskefaiaidstlpqlkye
gagtigkmslgetpqsryq------ltkpanavlspanviyqkagv----
-kdyvqwiivgagsgc---r-viggacpeqqkyaigqevvffkf-----h
akadvhkdmt------slkscfrifri----hrpkg--ravqq--gahyl
vhimlgsigfpvyvs----kgaklhegekqcdpyllmtdavktptdlrka
clshwldsckdvgekllatdgngkahaadhkkl-svfikgfdtrk-lwie
sdltlkpfqnhlaylgfgqatlvtlpeaganaktedgassscvdvav-rk
fglggvhsrrssft-----vrlgvqytqmlgqh-----gtg-----tvkn
tfnglg-avyhfcvkddlftkaacpyvaclf-------------------
-gsngdnmemdslysdrftdtd
>ENV_HV2D2/24-513
gd--------lffsviklaepgfidgirpgrataaqy-vtqkslrahyfr
ckvvalfnnkleaqstakdealatkakhvhfnegddfy-ldas----hvs
spepdreggeqistetaigd------------sr-stklvm--ycdsefg
sflny-s---rkav-ksvdwklevgals-ppeskesaigtdstlsplkye
g--sigkmglgetaqrsye------ltpaastvlspvnvvyqkede----
-kdyvewiivgggsgc---r-viagacp---kfaigqellffkf-----h
tkanvqr----------lkgcfrilri----hrdig--ravqq--gahyl
vhtmlgslgfriyvs----kgvklhdgkkqrdpyvlmtgrvtsptqlska
cldhwsdtckgvgpklligdgngkahaadqkkk-svfiegfdtrr-lwvn
tsltlkpfqhqlayigfgqatlvtlpeaganakteqgasnsyvnvaa-rk
fvlggvharrttft-----vrlgvey-emlgqg-----stg-----tvkn
fmsglg-gvyhfcvkddlfakaaypygaclf-------------------
-galgdnmemdslysdrfthtd
>node17
gn--------lffslinlge-----girpgrttvgqy-vtqkslrahyfr
ckvvklfnnklkvqsaakeealevkakrvhfnegddfy-ldas----hvt
spepdrdeaaqirtetaigd------------sr-stklvm--ycqsefg
sfliy-skyyrkdt-ksvnwk------sppaeskefaiatdstlsqlkye
gtgtigkmslgetaqssyq------ltkpantvlspanvvyqkeda----
-kdyvqwiivgagsgc---r-viagacpdqqkyaigqevvffkf-----h
akanvhkdmt------plkscfrifri----hrpig--rsvqq--gahyl
vhimlgsigfriyvs----kgaklhegekqidpyvlmtdrvktptqlrka
clshwldtckdvgekllatdgngkahaadqkkl-svfvkgfdtrk-lwie
sdltlkpfqnhlayigfgqatlvtlpeaganaktedgassscvdvav-rk
fglggvhsrrtsft-----vrlgvqytqmlgqh-----gtg-----tvkn
ffsglg-avyhfcvkddlfakaaypygaclf-------------------
-galgdnmemdslysdrfthtd
>node18
gn--------lffslinlge-----girpgrttvaqy-vtqkslrahyfr
ckvvklfnnklkvqsaakeealevkakrvhfnegddfy-ldas----hvt
spepdrdgaaqirtetaigd------------sr-stklvm--ycqsefg
sfliy-s---rkdt-ksvnwk------sppaeskefaigtdstlsqlkye
gtgsigkmslgetaqssyq------ltkpantvlspanvvyqkeda----
-kdyvqwiivgagsgc---r-viagacpdqqkyaigqevvffkf-----h
akanvhkdmt------plkscfrilri----hrpig--rsvqq--gahyl
vhimlgslgfriyvs----kgvklhegekqidpyvlmtgrvktptqlrka
clshwldtckdvgpkllagdgngkahaadqkkl-svfvkgfdtrk-lwie
sdltlkpfqnhlayigfgqatlvtlpeaganaktedgassscvdvav-rk
fglggvhsrrtsft-----vrlgvqytqmlgqh-----gtg-----tvkn
ffsglg-avyhfcvkddlfakaaypygaclf-------------------
-galgdnmemdslysdrfthtd
>node11
gn--------lffslinlge-----girpgrttvaqy-vtqkslrahyfr
ckvvklfnnklkvqsaakeealevkakhvhfnegddfy-ldas----hvt
spepdrdgaaqirtetaigd------------sr-stklvm--ycqsefg
sfliy-s---rkdt-ksvnwk------sppaeskefaigtdstlsqlkye
gtgsigkmslgetaqssyq------ltkpantvlspanvvyqkeda----
-kdyvqwiivgagsgc---r-viagacpdqqkyaigqevvffkf-----h
akanvhkdit------plkscfrilri----hrpig--rsvqq--gahyl
vhimlgslgfriyvs----kgvklhegekqidpyvlmtgrvktptqlrka
clshwldtckdvgpkllagdgngkahaadqkkl-svfvkgfdtrk-lwie
sdltlkpfqnhlayigfgqatlvtlpeaganaktedgassscvdvav-rk
fglggvhsrrtsft-----vrlgvqytqmlgqh-----gtg-----tvkn
ffsglg-avyhfcvkddlfakaaypygaclf-------------------
-galgdnmemdslysdrfthtd
>ENV_HV2BE/24-510
gd--------lffslinlgq-----girpgrktvany-vtqkslrthyfs
ckvvklfnvklkvqsaakeealevkakrvhfnegddfy-ldas----htt
speparigaaqirtktaigd------------sh-stklvm--fvmsefg
sfliy-r---rkdv-ksvnwk------sppaeskefaigtdstlsqlkye
ntgsvgkmslgetnessyq------ltkpantvlspanvvyqkeda----
-kay--------gsgc---r-viagacpdqqryaigqeveffkf-----h
akanvhkdmt------plkscfrilri----hraig--ksvqqlagaryi
vhilfgslvfriyas----kgvklhegekqidtyvlmtgrvksptqlrka
cmshwletckdngpnllagdgngkahaadqkkl-gvfvkgydtrk-lwie
sdltlkpfqnhlgyvgfgqttlvtlpaagakvkteagassscvdvav-r-
----gvhsrrtsft-----vrlgvqytqllgqh-----gtg-----tvkn
ffsglg-avehfcvkqdlfaraaypygaclf-------------------
-galgdnmemdslfsdrfhhtd
>ENV_HV2NZ/24-502
gn--------lffslinlge-----girpgrttvgqy-vtekalrahyfr
ckvvklfnnklkvqsaakeealevkakrvhfnegddfy-ldas----hvt
svrpdqdeaaairtetaigd------------sr-stklvm--ycqgefl
sfliy-skyyrkdt-ksvnwk------spptesrefaiapdstlselkye
gtatigkmslgettqsayq------ltkpantvlspqnvvyqkedavfpl
skdyvawiimgagsgc---r-vipaacpdkqkyavgqevvffkf-----h
akanvhkdmt------plkscfrifrv----hrpig--rsvqq--gahyl
vhimlgsigfrvyts----kmaklhegekqidpyvlmtdrvktptelrka
clshwldtckdvgdkllahdkngkahaadqkkl-svfvkgfdtrn-lwpe
sdltlkpfqnhlayigfgqatmvtlpesganaktedgassscvdvav-rk
fglggvhtrriayt-----vslgvqytqmlgqh-----gtg-----tvkn
ffsglg-avyhfcvkdnlfakaaypygaclf-------------------
-allgdnmemdslysdrfthtd
>ENV_SIVG1/22-522
gn--------lfysminlgd-----gvkpsrntiaqy-vtqkslqgqyvr
cnyvatinnklrvnlpgkedglevmskhahfreshefn-fdns----hvs
cpeplrdpvamikatttigd------------sr-stklpmgnftkpefs
aflvf-q---rkdt-kattwkllvgalsprcetkpfasgtdsalspitye
ganaighiclsehaqerfh------lkepagtvlstigvvkvkted----
-kdyvqwmingagsackrcrsviegavpkqqryaisddfvffkf-----s
akqdiqnsik------plnmcfrflkk----hrqig--kteqk--aahyl
infvlislgskvyidqpyfdgfdehqgeksiqpfdlktarvktgthrrta
---nwsnqckdntaklfaktddgravlleqkkl-svtiegyaprtslwve
teysakglqehlayvgfgeatagstqesaadset--daacscaaaaii-k
fvlggipsrrtrftcdpgrvgvgtqf-qmlgphgafdrgta-----tvkn
yfpgrg-gtnpfclldelfgkkayitaaclf-------------------
-galgdnpeldglyvdrfthqe
>node19
gn--------lffslinlge-----girpgrttvaqy-vtqkslrahyfr
ckvvklfnnklkvqsaakeealevkakrvhfnegddfy-ldas----hvt
spepdrdgaaqirtetaigd------------sr-stklvm--ycqsefg
sfliy-s---rkdt-ksvnwk------sppaeskefaigtdstlsqlkye
gtgsigkmslgetaqssyq------ltkpantvlspanvvyqkeda----
-kdyvqwiivgagsgc---r-viagacpdqqkyaigqevvffkf-----h
akanvhkdmt------plkscfrilri----hrpig--rsvqq--gahyl
vhimlgslgfriyvs----kgvklhegekqidpyvlmtgrvktptqlrka
clshwldtckdvgpkllagdgngkahaadqkkl-svfvkgfdtrk-lwie
sdltlkpfqnhlayigfgqatlvtlpeaganaktedgassscvdvav-rk
fglggvhsrrtsft-----vrlgvqytqmlgqh-----gtg-----tvkn
ffsglg-avyhfcvkddlfakaaypygaclf-------------------
-galgdnmemdslysdrfthtd
>ENV_SIVM1/24-528
gnkagcllfvlffslinlge-----ginpgrttvaqy-vtqkslrahyfr
ckvvksinnklkvesaakdealevkakhvhfnegsdfd-ldas----hvs
spnperdgasqiktetaigd------------siqstklvm--ycdsefg
sfliy-s---rtdt-ksvdwklltgalsppaqskefaigtdstlsplkyv
gtgsigkmslgevaerrfq------ltkpantvlspvnvvyqkege----
-kdyvqwiivgagsgc---r-viagacpdqqkyaigqefvfykf-----h
akqd----ia------pltscfrilti----hkdig--kevqq--krhyl
vhimlgslgfriyve----kgiklhegekqidpyvlmtgkvktpnqlrkg
clshwsdqcksigpklfagdgdgkyvaqeqkkl-svfvegfdtrk-lwve
tgltlkpfqnhlayigfgqatlvtlpeagsnaksedgassscvdvavi-k
fvlggvhsrrtslt-----vrlgvqy-qmlgqh-----gts-----tlkn
ffgglg-glyhfcvkndlfaktayafgaclf-------------------
-galgdnlelaslysdrfthte
>ENV_SIVGB/47-569
gn--------lsfkmiefgd-----------snvgdrslahdnakgecir
chitastdqsikvevmaktldidvvarnihfrkshdnepsnskkesanvs
cvspardaqqkaqttctkga------------sp-sialpqgiitspsfg
aiitqpi---rkns-kstlwsylpgslaqriltkpfppgattaldaatye
esgaieraclgeaaqerfqnsgfdl----aatnldqigvn----------
-kifvhyaklgsntdsrkah-laqgacpkrckyglsqdftyfnfklwhsg
gnddvqkcsk------ppdesfqcleklysphppfa--gsvhl--dshyl
lgfklaafnf--yie----dsyalqsgqneidafslkngrvhtetpekte
---dwl-------vdlfagkksgkaqmqd-----------frpgd-qwak
tgftikpvhkalvysgfsd----sghdpgpa-----qtaclcvaasii-q
ilvnggaarnvsftcdpgrlavatqf-smlnph-----gtplqkaqtfkp
yfpgrs-slnefcvgde--gnnvyivsgclhtvenpassesgknlkggkg
ngalceipeldfnyatkfsers
>ENV_HV2D1/24-501
gn--------lffslinlns-----girpgrttvaky-vtqkslrasyfr
gkvvklfnnklkvqsaakeealevkakrahfnegddfy-ldan----hvt
ssepdregaaqirtetaige------------sh-saklvm--ycmsefg
sfliy-s---rkdt-kgvnwk------sppaeskefaigtdstlaqlkye
gtgsigkmslgetaessyq------ltkpantrmspanvvyqkeda----
-kayvqwiivasgsgc---h-viagacpdqqkyaigqevvffkf-----h
akanvhkdmtaesfgdplkscfrilri----hrpigekrsvqq--gahyl
vhimlgklpfkmyas----kavklhegekqsdpyvlmtgrvktptqlrka
clshwldtckdvgpnllagdgngkahaadqkkl-svfvk--dark-lwie
sdltlkpfqnnlayigfgettlvtlppaganvkandgqssscvdvav-rk
fglggvhsrrtkfv-----vrlgvqythalgqh-----geg-----tvkn
ffsslg-avykfcvkddlfakaaypygacif-------------------
-galgdnmemdslysdrfthtd
>ENV_SIVV1/24-538
gg--------ifysmtnlge-----gtmpsrttivqy-vtqkslqgkyir
cnyvgtinnklradipskenalevmtkhvhfreahefn-fens----hvs
caedlrepepmikttttige------------ar-gikapqanfkkpelg
aflvf-g---rkdtgkntswkllvgalsprcqtkpfasgtdsalngitie
gkgevghisvges--qrfh------ltkptgtvlstiglvkaktee----
-kdyvrwmglgdntscrrcrsvhegsvpegqryaigddfvffkf-----s
arqhiqnsik------qlhmcfrflkk----hrqig--esenk--aaeyl
vgfflaalgykvykdrsyfdgfdehqadshidpfamkstrvktgthrrta
---nwanqckddgarlfagtgegrpilleqkkl-svtignyeprtnlwve
teyelk-lrehlgyvgfgeqtagkteesgddadt--ngtciaivalii-k
filggipsrrtsftsepgrvgvgeqf-qllgph-----gts-----tvkd
ytpgqg-gsnpfcvldelfgkksyikaaclf-------------------
-galgdsrqldgvyadrfthqe
>ENV_HV2G1/23-502
gn--------lffslinlge-------rpgrttvaqy-vtqkslrahyfr
ckvvklfnnklkvqsaakeealevkakhvhfnegddfy-ldas----hit
spepdrdgaaqirtetaigd------------sr-stklvm--ycqsefg
sflvy-s---rkda-ksvnwk------sppaeskefaigtdstlsqlkye
gtgsigkmslgetaqssyq------ltkpan-----anivyqkedv----
-kdyvqwiivgaasgc---r-viaaacpdqqkyaigeevvffkf-----h
akanvhkdit------plkscfrilri----hrpig--rsvqq--gahyl
vhimlgflgfriyvn----kgvklhegekqidpyvlmtgrvktptqlrkn
clshwldtckdvgpkilagdgngkahaadqkklssvfvkgfdtrk-lwie
sdltlkpfqnhlayigfgqatlvtlpeaganaktedgassscvdtav-rk
fglgsvhsrrtsft-----vmlgvqytqmmgqh-----gtg-----tvkt
ffsglga--yhfcvkddlfakgsypygaclf-------------------
-galgdnmemdslysdnftntd
>node14
gn--------lffslinlge-----girpgrttvaky-vtqkslrahyfr
ckvvklfnnklkvqsaakeealevkakrvhfnegddfy-ldas----hvt
spepdrdgaaqirtetaigd------------sh-stklvm--ycmsefg
sfliy-s---rkdt-ksvnwk------sppaeskefaigtdstlsqlkye
gtgsigkmslgetaessyq------ltkpantvlspanvvyqkeda----
-kayvqwiivaagsgc---r-viagacpdqqkyaigqevvffkf-----h
akanvhkdmt------plkscfrilri----hrpig--rsvqq--gahyl
vhimlgslafriyas----kgvklhegekqidpyvlmtgrvktptqlrka
clshwldtckdvgpnllagdgngkahaadqkkl-svfvkgydtrk-lwie
sdltlkpfqnhlayigfgqttlvtlppaganvktedgassscvdvav-rk
fglggvhsrrtsft-----vrlgvqytqmlgqh-----gtg-----tvkn
ffsglg-avyhfcvkddlfakaaypygaclf-------------------
-galgdnmemdslysdrfthtd
>node8
gn--------lffsminlgd-----gvkpsrttiaqy-vtqkslrgqyvr
cnvvasinnklrveiaakedalevmskhvhfreshdfd-fdas----hvs
cpeplrdpearikttttigd------------sr-siklpqgnftkpefg
aflvf-q---rkdt-kattwkllvgalsprcetkpfasgtdsalspitye
gsgaigkmclgetaqqrfh------ltkpagtvlssigvvkaktee----
-kdyvqwmilgagsscrrcr-viegacpkqqkyaisqdfvffkf-----s
akqdiqksik------plnmcfrflkk----hrqig--ksvqk--aahyl
vnfmlaslgykayie----dgfdqhegekqidpfslktgrvktathmrta
---nwsaqcndngpklfagtgdgkavlqeqkkl-svtiegfaprn-lwve
tdyslkplqehlayigfgeatagslqesgpnaea--dascscvavavi-k
fvlggipsrrtsftcdpgrvgvgtqf-qmlgph-----gta-----tvkn
yfpgrg-glnhfcvmdelfgktayitgaclf-------------------
-galgdhpeldglyadrfthqe
>node7
gn--------lfysminlgd-----gvkpsrttiaqy-vtqkslqgqyvr
cnyvasinnklrveipakedalevmskhvhfreshefn-fdns----hvs
cpeplrdpeamikttttigd------------sr-siklpmgnftkpefs
aflvf-q---rkdt-kattwkllvgalsprcetkpfasgtdsalspitye
gsgaighiclgetaqqrfh------ltkpagtvlstigvvkaktee----
-kdyvqwmilgagsscrrcrsviegavpkqqryaisddfvffkf-----s
akqdiqnsik------plnmcfrflkk----hrqig--kseqk--aahyl
vnfmlaslgykvyidqpyfdgfdehqgekhiepfdlktarvktgthrrta
---nwsnqckdngaklfagtgdgravlleqkkl-svtiegyaprtnlwve
teyslkalqehlayvgfgeatagstqesgpdaet--dascscvavavi-k
fvlggipsrrtsftcdpgrvgvgtqf-qmlgph-----gta-----tvkn
yfpgrg-gtnpfcvldelfgkkayitaaclf-------------------
-galgdnpeldglyvdrfthqe
>node10
gn--------lffslinlge-----girpgrttvaqy-vtqkslrahyfr
ckvvklfnnklkvqsaakeealevkakhvhfnegddfy-ldas----hvs
spepdrdgaaqirtetaigd------------sr-stklvm--ycdsefg
sfliy-s---rkdt-ksvnwklevgalsppaeskefaigtdstlsplkye
gtgsigkmslgetaqrsyq------ltkpantvlspvnvvyqkede----
-kdyvqwiivgagsgc---r-viagacpdqqkyaigqevvffkf-----h
akanvhknit------plkscfrilri----hreig--ravqq--gahyl
vhimlgslgfriyvs----kgvklhegekqidpyvlmtgrvktptqlrka
clshwsdtckdvgpkllagdgngkahaadqkkl-svfiegfdtrk-lwve
tdltlkpfqnhlayigfgqatlvtlpeaganaktedgassscvdvav-rk
fvlggvhsrrtsft-----vrlgvqy-qmlgqh-----gtg-----tvkn
ffsglg-gvyhfcvkddlfakaaypygaclf-------------------
-galgdnmemdslysdrfthtd
