>ENV_HV2NZ/24-502
vktqae---gkvpaslelpttfgevkcheklvsfyitllvciqmfvllcc
elppfvflnnteaksiggndptqs-----kpllrladvmhdpvm------
-----aqslfacakklval---dhpkssvpyhfssftnggfr-s-----c
-----------------qpdeeacaisvp-arktteaaiyh--------y
nk----dlpl---ppaitsqleivdarsslysevs--kdppacp-inets
g----------adawaaad--apdgatgnnpipgvpef------------
--ayatg----vmva--------------------p-lpkqlilgaaqlk
riccdslg-k-kfeglsdipevhfgmgygkeiiv----finhliasccag
lfdcarelvss-kahknlnmllnylhgskvmirgcly--ygr-ispkgtd
stlqcnaekymavvtgeigkla---kmyffdthlfv-----eimeglcda
ri-------gggpkmgflarifggrpkagnyttvpgkaldeil-------
vaekikvwaevlvavke---gknnsq--qqaqlglvkfflsspeagkl--
---ggfgkdpgrktrvelpkda------le-----vyvakgtdklcssfa
kvvhalkdervdvcfsdsccvhi
>node8
vkkege---tkapasltmsttfkepnchnklvsiyiglvv----fvllcc
qlppflflgneetlgvggnaatngasvikkplrrlgdvmhepvmwvmdtt
nwlfhaqgflacaqklykl---dqgrsgvpyhlsaftndgyh-a-----c
avkqstc--leaspkkakpdemacaiska-grrkwnatiaq--------y
mk----ilaf---ppavtseleitqarksiygsma--ktpptca-inets
g----------ne-----dhpspdgstgadplhsvaeisdvssqfagpqp
pkayass----gmvh--------------------q-lpkqlilpaaqls
kvccpslg-t-rldlvsdipsvqfsmgygkdmvl----fidrlihncnas
llncarelhespkthsnltmllnyldggqpl----vy--fgr-vhlmgsd
ntlqykttkymivvtgqlgale---kmyffdshfld-----emmdgvsda
rv-------gggiktgyelrvfggsqktgndstvpgkvld----------
aadkagvwaevlvavld---gqkkslkttqaqlgfvkkfisstqygkmla
splagfgkdpgrktrvelpkee------le-----vyvdknehnmcgsfa
kvtdmltde--nvcfsgrc-vhp
>node11
vktqge---gkvpaslelpttfgevkcheklvsfyitlvvciqmfvllcc
qlppfvflnntetksiggndptes-----kpllrlgdvmhdpvm------
-----aqsffacadklvnl---dhpkssvpyhlssftnegfr-s-----c
-----------------rpdeeacaisrp-arktsnaaivh--------y
nk----ilpl---ppaitsqleivnarkslysdvt--knppscp-inets
g----------ad-----d--apdgstganpipgvaef------------
--ayata----tmva--------------------p-lpkqlilgaaqls
ricceslg-k-kfeglsdipevhfgmgygkeiiv----finhlianccag
lldcarelles-kahsnlkmllnylhgsavl----ly--ygr-isgkgsd
stlqfkatkymavvtgeigkla---kmyffdthfft-----eimeglcda
rv-------gggpkmgylqrifggrpkagnyttvpgkaldeil-------
vadkikvwaevlvavke---gknksq--qqaqlglvklflsspeygkm--
---ggfgkdpgrktrvelpkda------le-----vyvakstdklcssfa
kvvhalkdervnvcfsdrccvhv
>ENV_HV2CA/25-512
vktqgp---gkvpaslelpttfgevkcneklvsffitlvvciqmfvllcc
elppfvfldntetksiggndptes-----kpqlrlgdtmcdpvm------
-----aqsffacaeklvnl---dhpkssapyhlssfvnegfr-a-----c
-----------------rpdeeacaisvanarktseaaeyh--------y
nk----ilpl---ppaitsqleivdarkslysdvt--knnpscp-inets
g----------ad-----d--apdgstganpipgvaef------------
--ayata----tmvg--------------------p-lpkqlivgaaqls
ricceslg-k-kfeglsdvpevhfvmgygkeiii----finklianccag
lldcarelvts-kahpnlkmlldylhssahlmrgcly--cgr-isgkgad
stlqfnatkymavvtgeigkla---kmlffdthffa-----elmeglcda
ri-------gggpkmghlqrifggrpdagnyttvpgkalddil-------
vadkikvwaevlvgvre---gknnsq--qqaqlglvklflafpeygkl--
---ggfgkdpgrktrvelpkda------le-----vylakatdslcssfa
kvvhflkdervdvcfsdqccvhv
>ENV_SIVGB/47-569
ghkqsqgfvtktsanvsvs--frsagcrnklgtfykglvv----flllcc
ellafldlshddsvtlgghsas----vfkksfdklgdifrrafmwkvitd
kwlfhatlflacvve-iklvlngkgktgypfhfgafskdgyfialhtsgc
aakegacnnq-kgpkyammdaancalgra-ykrqwnagikqdwtqhivay
lnpgrmilaf---pptittelditdhkdtlygefe--gtppkcv-ldetg
g----------dq-----dapnddgivgsnslhsspqvtdvisqsegptp
skvsqssdkgppkvq--------------------l-lgselfvpaavl-
nlcsapia----ldlvtef--------yaknkli----fvdrlinkcnka
qldcaveltes-drhsylvkllvkfkdfqps----pfavygrwvhvdadn
taldyetsnfmivttgmlgvwepckktyfyasvfldivtivtmmdgvsps
rv-------gggikspyvarif--fdktgdkksipdkemd----------
tsknahvwdevlia--dkalggkkslkk-qahmeyivkflnaaqygkpgq
ns--gfgrsparsahh-lpkde------lepqvfglycdkfmanmtgafs
kgtpllcde--cacftdlc-mhg
>ENV_HV2G1/23-502
lstqge---gkvpaslelpttfgevkchekfvsfyvslvisiqmfvllcc
qlpafvflnntetrsiggndpteg-----kpllrlgdvmhdpvm------
-----aqtffacadklvnl---ehpkssvpyhlssfsnegfv-s-----c
-----------------rtdeeacatsrp-arkashaaivh--------y
nk----ilpl---ppaitsqleivda-eslysdvt--tspnscp-inits
g----------ad-----d--apdgstganpipgvaef------------
--ayata----tmvd--------------------p-lpkqlilgaaqla
riccdslg-k-kfeglsdipevhfgmgygkeiiv----finhlianccag
lldcpremles-kahsnlkmllnylhgsavl----ly--ygr-vsgkgsg
salqfkatkymavvtgeigkla---kmyffdthflt-----eikeglcda
rs-------g--pkmgylqrisggrpkagnyttapgkaldeil-------
vadkikvwaevlvavke---gknkaq--qqaqlglvklflsspeygkm--
---gafgkeparktrvelpkda------le-----vyvakstdklcssfa
kvvhalkdervnvcfsdrccvhv
>ENV_SIVM1/24-528
vkkqse---snvpasgelpttlgevkchdklvsfyitltvciemfvllac
qlppfiflnntetksiggnnptns-----kplrrlgdvfhdpvm------
-----aqsffacaeklvna---dqprsstpyhlssfanevfr-s-----c
-----------------rpdeeacaisrv-arkksnaaivh--------y
dk----iaal---ppniteqlaithgrkplygdvt--ksprscp-inetn
g----------ag-----dhpapdgsanadpipgvaefpdvcgdfpgpqp
pkaylta----tmvn--------------------phlakqlilgaeqls
rvccaslg-k-kfeglnaipevhfgmgygkeiilaedlyinhlianccat
llncerelles-kthsnlkmllnylhgsgpl----ly--ygr-vsldgsd
stlqfkttkymavvtgemskla---kmyffdthfft-----eimqgvcda
rv-------gggpktgylqrifggrpkagnystvpgkald----------
vpdkikvwaevlvdvie---gknkpq--qqaqlglvklflsskeygkl--
---ggfgkdpgrktrvelpsda------le-----vyvsksehklcksya
kvihalkds--nvcfsdgccvnv
>node17
vktqge---gkvpaslelpttfgevkcheklvsfyitlvvciqmfvllcc
elppfvflnntetksiggndptes-----kpllrlgdvmhdpvm------
-----aqsffacadklvnl---dhpkssvpyhlssftnegfr-s-----c
-----------------rpdeeacaisvp-arktseaaiyh--------y
nk----ilpl---ppaitsqleivdarkslysdvt--knppscp-inets
g----------ad-----d--apdgstganpipgvaef------------
--ayata----tmva--------------------p-lpkqlilgaaqls
ricceslg-k-kfeglsdipevhfgmgygkeiiv----finhlianccag
lldcarelvss-kahsnlkmllnylhgsavllrgcly--ygr-isgkgsd
stlqfnatkymavvtgeigkla---kmyffdthfft-----eimeglcda
ri-------gggpkmgylqrifggrpkagnyttvpgkaldeil-------
vadkikvwaevlvavke---gknnsq--qqaqlglvklflsspeygkl--
---ggfgkdpgrktrvelpkda------le-----vyvakatdklcssfa
kvvhalkdervdvcfsdrccvhv
>node10
vktqge---gkvpaslelpttfgevkcheklvsfyitlvvciqmfvllcc
qlppfiflnntetksiggndptns-----kpllrlgdvmhdpvm------
-----aqsffacaeklvnl---dqpkssvpyhlssftnegfr-s-----c
-----------------rpdeeacaisrp-arkksnaaivh--------y
nk----ilpl---ppaitsqleivnarkslygdvt--knppscp-inets
g----------ad-----dhpapdgstganpipgvaef------------
--ayata----tmva--------------------p-lpkqlilgaaqls
rvccaslg-k-kfeglsdipevhfgmgygkeiil----finhlianccas
lldcarelles-kahsnlkmllnylhgsapl----ly--ygr-isakgsd
stlqfkttkymavvtgeigkla---kmyffdthfft-----eimeglcda
rv-------gggpktgylqrifggrpkagnyttvpgkaldeil-------
vadkikvwaevlvavke---gknksq--qqaqlglvklflsspeygkm--
---ggfgkdpgrktrvelpkda------le-----vyvakstdklcssfa
kvvhalkde--nvcfsdrccvhv
>node19
vktqge---gkvpaslelpttfgevkcheklvsfyitlvvciqmfvllcc
qlppfvflnntetksiggndptes-----kpllrlgdvmhdpvm------
-----aqsffacadklvnl---dhpkssvpyhlssftnegfr-s-----c
-----------------rpdeeacaisvp-arktsnaaivh--------y
nk----ilpl---ppaitsqleivnarkslysdvt--knppscp-inets
g----------ad-----d--apdgstganpipgvaef------------
--ayata----tmva--------------------p-lpkqlilgaaqls
ricceslg-k-kfeglsdipevhfgmgygkeiiv----finhlianccag
lldcarelles-kahsnlkmllnylhgsavllrgcly--ygr-isgkgsd
stlqfkatkymavvtgeigkla---kmyffdthfft-----eimeglcda
rv-------gggpkmgylqrifggrpkagnyttvpgkaldeil-------
vadkikvwaevlvavke---gknksq--qqaqlglvklflsspeygkm--
---ggfgkdpgrktrvelpkda------le-----vyvakstdklcssfa
kvvhalkdervnvcfsdrccvhv
>ENV_SIVG1/22-522
vkkegk---tkaaaslpmsttykepnchhkltsiyvglvv----fvllcc
qlpaflflateenlgmggnaatngagvikfplrrlgdvshepvmwvm---
--lfhaqgilacaq-lykl---dqtksgvpyhlsafaddgyh-a-----c
aakasnc--leaspkkakpdemaca-ska-grrkwdaiiaq--------y
me----ilaf---ppevtneleitearkgiygsms--knppica-iners
g----------ne-----dqpstd----asaihcvadisdvksvfagpqp
pkaypts----glvl--------------------q-lpkqlmlvagqls
kvccpslg-tgrldlvsdipsvqyslgydkdnvl----fidr-ihncnas
llncskelheppkthsnlimllnyldggesl----vy--fgr-vhlmgsd
ntlqykttkymivvtgqlgale---kvyffdshfld-----ekmegvsda
rv-------gggikhgyelrvfggsqktgnestrpgkvle----------
aanktsvwaevliavid---aqkktlkts--klgfvkkfisstqygkalg
kplagfgkdpgskthvelpkeg------le-----vyvqlnernacgmfa
kvttmltdd--svcfsgrc-vap
>ENV_HV2BE/24-510
vktqge---skvpaslelpttfgetkcheklvsfyitlvvciqmfvllcc
qlppfvflnttetksiggndptes-----kpllrlgdvmhepvm------
-----gqsffactdllvnl---dhpkssvpyhlssfsnegfr-t-----c
-----------------rpdeeacvisvd-arktsgaaivh--------y
nk----ilplcktpqavtsqielv-qrknlysdvt--knppscp-inett
g----------ad-----d--apegstganriagvaef------------
--afdts----tmaa--------------------p-lqkqlil---els
riccegsdgk-kfeglsdipevhfgmgngkeiiv----fikhlianccag
lldcarnlles-kahsnlnqllnylhgsavllrgcly--ygr-isgkggn
sdlqfkatkymvvltgeigkla---kmyffdtkfft-----diedglcda
rv-------gggpkmgylqrkfggrpkagkyttlpgkaldell-------
vvdkikvwaevqvavke---gknnsh--qqaqiglvklflasqeyakm--
---ggfgkdpgrntrvelpkda------le-----vyvarstdklcssfa
kvvhalkddrvnvcfsdrccvhv
>ENV_HV2D1/24-501
vhtqgg---skvpaslelptsfgeskcheklvsfyitivtciqmfvllcc
qlppfvflndtetksiggndptes-----kpllrlgdvmadpv-------
-------nffscanklvnl---dhpkssgpyhlssftnkgfq-s-----c
-----------------radeeacaisvp-arrtsgaaivh--------y
sk----ilpl---ppamtsqtelvnarkslysdvd--knppscp-inett
g----------ad-----d--apnastganpipgiaef------------
--ayata----tmva--------------------p-lpkqlilgaaqls
riccesld-k-kfegls----------ygkeiig----fikhlianccag
lldcvrelles-kakselkmllnylhgsavllrgclh--ygr-csgkgsd
stlqfkatkymavvtsqigkld---kmyffdthfft-----dienglcda
rv-------gggpkagyqqrkfggrpkagnyttlpgkaldeil-------
vvdelkvwaevlvavke---gknnsq--qqaqlglvklflsapeygkm--
---ggfgktpgrktrvelpkda------lq-----vyvaksndkicksfa
kvvhalkterinvcfsdrccvhv
>node9
vkkqge---gkvpaslelpttfgevkchdklvsfyitlvvciemfvllcc
qlppfiflnntetksiggndptns-----kplrrlgdvmhdpvm------
-----aqsffacaeklvnl---dqprssvpyhlssftnegfr-s-----c
-----------------rpdeeacaisrp-arkksnaaivh--------y
nk----ilal---ppaitsqleitharkslygdvt--knppscp-inets
g----------ad-----dhpapdgstganpipgvaefpdvcgdfpgpqp
pkayata----tmvn--------------------p-lpkqlilgaaqls
rvccaslg-k-kfeglsdipevhfgmgygkeiil----finhlianccas
llncarelles-kthsnlkmllnylhgsapl----ly--ygr-vslkgsd
stlqfkttkymavvtgeigkla---kmyffdthfft-----eimegicda
rv-------gggpktgylqrifggrpkagnystvpgkald----------
vadkikvwaevlvavie---gknksq--qqaqlglvklflsskeygkm--
---ggfgkdpgrktrvelpkda------le-----vyvaksehklcssfa
kvihalkde--nvcfsdrccvhv
>node7
vkkege---vkapaslsmsttykepnchhkltsiyiglvv----fvllcc
qlppflflgteenlgmggnaatngagviksplrrlgdvahepvmwvm---
--lfhaqgflacaq-lykl---dqtksgvpyhlsafandgyh-a-----c
aakasnc--leaspkkakpdemacaiska-grrkwdatiaq--------y
mk----ilaf---ppavtneleitqarkgiygsms--kappica-iners
g----------de-----dqpssd----aaalhcvaeisdvssvfagpqp
pkaypss----glvl--------------------q-lpkqlilvaaqls
kvccpslg-tgrldlvsdipsvqfsmgygkdavl----fidrlihncnas
llncsrelheppkthsnlimllnyldggepl----vy--fgr-vhlmgsd
ntlqykttkymivvtgqlgale---kmyffdshfld-----emmegvsda
rv-------gggikhgyelrvfggsqktgndstrpgkvle----------
aadktsvwaevliavid---aqkktlkts--klgfvkkfisstqygkalg
kplagfgkdpgrkthvelpkeg------le-----vyvqlnehnacgsfa
kvttmltdd--svcfsgrc-vhp
>node14
vktqge---skvpaslelpttfgevkcheklvsfyitlvvciqmfvllcc
qlppfvflnntetksiggndptes-----kpllrlgdvmhdpvm------
-----aqsffacadklvnl---dhpkssvpyhlssftnegfr-s-----c
-----------------rpdeeacaisvp-arktsgaaivh--------y
nk----ilpl---ppaitsqielvnarkslysdvt--knppscp-inett
g----------ad-----d--apngstganpipgvaef------------
--ayata----tmva--------------------p-lpkqlilgaaqls
riccesld-k-kfeglsdipevhfgmgygkeiiv----fikhlianccag
lldcarelles-kahsnlkmllnylhgsavllrgcly--ygr-isgkgsd
stlqfkatkymavvtgeigkla---kmyffdthfft-----diedglcda
rv-------gggpkmgylqrkfggrpkagnyttlpgkaldeil-------
vvdkikvwaevlvavke---gknnsq--qqaqlglvklflsspeygkm--
---ggfgkdpgrktrvelpkda------le-----vyvakstdklcssfa
kvvhalkdervnvcfsdrccvhv
>ENV_SIVV1/24-538
vkkeae---vkaptslsksttfkdpnchhklssvyigliv----fvllcc
qlppflnlgaaenlsmggnaatngagtiksplrrlgdvahepvmwvm---
--llhaqgllgytq-lykl---datrtgppyhlsefgnagyh-v-----c
aakasnc--leaspkkakphemacaisra-gkrrwdatpah--------y
mp----ilaf---ppavtnelqvt---kgicgsmaspkahpvca-ineks
gpeiqrddtesde-----dhpssd----raalhcvaeisevssv--gpqp
pkpyast----glvllafgskstratndpqknpkah-lpeqlalvasqls
r--------kgaldlvsdipsvqfaggygkkavl-----idrvvhncnag
llncakelheppkthsnlimllnyidggepl----vy--fer-vhlmgsd
ntlqyktakymivvtgqlgalq---kmyfydshflq-----eildgvnda
rliqgshvtgagikhgyelrtfggsqktgndgtrpgkvle----------
aadktsvwaevfiavid---aqkkglktg--klgfvkkfigstdwgkalg
kplagwgkdpgrkaqvelakdv------le-----vyvqlnehnacgafa
kvtimledd--gvcfnkry-vhp
>ENV_HV2D2/24-513
aktkeg---gkvpaslelpttfgevkcfkklvsfvitlvvciqkfvllcc
qlppfiflnnteaksiggndptns-----kpllrlgdamhdvvm------
-----tqsffacaeklvnl---dtprssapynltsgtnegfr-s-----c
-----------------rpdeeacaikpp-aakksnaaivh--------y
ek----ilkl------issqleivnarknlygdgk--knppscpvinets
g----------ad-----dhpypdastgaspipgvaef------------
--ayata----ttia--------------------p-lpkqltlgagqls
rvcsaslg-k-kfqglseipevhfgmgtnkeiil----finnlianccag
lldcarelles-kahnnlkmllnymhgaapl----ly--ygr-isakgsd
stldfkstkymavetgeiakla---kmyffdthyft-----dimeslcel
rv-------ggdpctgylqrifggrpkagnyttvpgkaldeilqcsvtqw
vadkikvwaevlvavke---aknnsq--qqaqlglcklfltgpeygkm--
---ggfgksqgrktrvelskdaqagsdele-----vyvakstdklcssfa
kvvhalkdd--nvcfsdrccvhv
>node18
vktqge---gkvpaslelpttfgevkcheklvsfyitlvvciqmfvllcc
qlppfvflnntetksiggndptes-----kpllrlgdvmhdpvm------
-----aqsffacadklvnl---dhpkssvpyhlssftnegfr-s-----c
-----------------rpdeeacaisvp-arktsnaaivh--------y
nk----ilpl---ppaitsqleivnarkslysdvt--knppscp-inets
g----------ad-----d--apdgstganpipgvaef------------
--ayata----tmva--------------------p-lpkqlilgaaqls
ricceslg-k-kfeglsdipevhfgmgygkeiiv----finhlianccag
lldcarelles-kahsnlkmllnylhgsavllrgcly--ygr-isgkgsd
stlqfkatkymavvtgeigkla---kmyffdthfft-----eimeglcda
rv-------gggpkmgylqrifggrpkagnyttvpgkaldeil-------
vadkikvwaevlvavke---gknnsq--qqaqlglvklflsspeygkm--
---ggfgkdpgrktrvelpkda------le-----vyvakstdklcssfa
kvvhalkdervnvcfsdrccvhv
