>ENV_SIVV1/24-538
gqvalpdqvsvgyccfqkc-flqgkrvtgnss-----hakqnnveasnth
igtqai---vavknpadsafgdqtsa--k----skfqgnvkqadqkvaty
qvralresalqmiysqlckavktepimhgtthcsgkkswvaraavpssik
a-------------scmnk--neflhi-----advwsyyyphrah--mpc
g--l----pai--lnf-------ekqsdvhsgnltavlggvgpfgcttvs
dgyvlrvivgvgpgapnypnkgyas-------tl--agdsvy-saakkkk
tga--tphligiilkhkeeptffgyldqe--applkqtegvqtdaqqnma
g--lhqdtkllkntgqtasggqgtadptktgrhfclvfls------rekk
qdvglfeycr-sniltfly------svfmknkdkrqvsalahplf-hesg
ecqflaleesvppacaaqangvky---gkdkgkcaitsekage--gatsy
dkgppsfvhkiyt-mptvsdgcsidgka--aalnal---qsfvck-rkvm
dskrctdcapnkp--gvihglytcplsssalnkkvksghcagkp----an
liq-d
>node14
ahvalpphlnlsncgfkkcnfaq-khatasst-----d-----vdsqtte
igmtni---vhskdpgkstfssssta--k----infvaharesdgkvp-y
dvrnlrehrlqkay---ckahksdpilhgnadcstakswgkraavaeaik
drvscqkgcrfgldscmqm--ygflqishlrrtshfkyyypnsrr--mvc
g--h----ksv--lnn-------ekessvhggdlgsvlgglsgfgckals
egyvlrvyvqlgngppkypskayasgri--vspr--agqgiy-vnakdhk
ega--apalikiivkhtnap--msnidda--cpplgnthappsddqhnma
hvllhreanvr-gtgqtacnsqstadetktckpfclillk------rekk
--vvafaycatsnifdlls------svfmknknskrvgavnhel---gva
ecqfyslekacppacpgsspgvdy---gkdnkkcgia---asn--geecn
dkspaglipkiya-msrvsepcsrdgrv--pnlsal---qsfsck-kkff
eskkctdcasers--gvvhflytgplrpa------------gsh----ka
liqte
>ENV_SIVM1/24-528
ahvvlpphlnlsscgfkkcnfaq-khattnst-----n-----vgsktte
lgmkai---vhskdpsksnfasssta--k----snfvghtresdgkvp-y
dvrnlrkhqlqmay---ckgrksdpimhgsadcatkkswakppavaeaik
qrvscqkgcrfgldscmqm--sgrleishlqrtahfkyyypnssr--mic
g--h----ksm--lnn-------qdessvqggdlvsvlgglgsfgckals
egyvlrtyvqlgdgppiypskayasgri--aspr--gaqgiy-vnpkknk
esa--aptikgitvkhtnap--ttdieqe--spplghahaptsddqqnmg
h--lhrdengr-gtgqtackgkstadptttckphclvllk------rqkk
--svvfaycatweifdlla------svfmkdknstrvgavnhpl---gsa
ecqfysl----------qspgvdy---gkenkkcgia---aan--gepcn
dkaiaglvpkiya-r-kvsepctrdgrv--pdlsal---hsfsck-kkff
eskkctdcasqrs--gvvhflytgplrsaplikkiqasqcagnn----ka
l----
>node17
vhvalpphlnlsncgfkkcnfaq-khatasst-----d-----vdsqtte
igmkni---vhskdpgkstfssssta--k----infvahtresdgkvp-y
dvrnlrehrlqkay---ckahksdpilhgnadcstkkswgkraavaeaik
drvscqkgcrfgldsckqm--ygflqisnlrrtshfkyyypnsrr--mvc
g--h----ksv--lnn-------ekessvqggdlgsvlgglgsfgckals
egyvlrvyvqlgngppkypsnayasgri--vspq--agqgiy-vnakdhk
ega--apalikiivkhtnap--msnidda--cpplgnthappsddqqnma
hvllhreenvr-gtgqtacnsqstaeetktckpfclills------rekk
--vvafaycatsnifdlls------svfmknknpkrvgtvnhel---gva
ecqfyslekacppacpgnspgvdy---gkdnkkcgia---atn--geecn
dkspaglipkiya-msrvsepcsrdgrv--pnlsal---qqfsck-kkff
eskkctdcasers--gvvhflytgplrsa------------gsh----ka
liqte
>node19
ahvalpphlnlsncgfkkcnfaq-khatasst-----d-----vdsqtte
igmkni---vhskdpgkstfssssta--k----infvahtresdgkvp-y
dvrnlrehrlqkay---ckahksdpilhgnadcstkkswgkraavaeaik
drvscqkgcrfgldscmqm--ygflqishlrrtshfkyyypnsrr--mvc
g--h----ksv--lnn-------ekessvhggdlgsvlgglgsfgckals
egyvlrvyvqlgngppkypskayasgri--vspr--agqgiy-vnakdhk
ega--apalikiivkhtnap--msnidda--cpplgnthappsddqhnma
hvllhreenvr-gtgqtacnsqstadetktckpfclillk------rekk
--vvafaycatsnifdlls------svfmknknskrvgavnhel---gva
ecqfyslekacppacpgnspgvdy---gkdnkkcgia---asn--geecn
dkspaglipkiya-msrvsepcsrdgrv--pnlsal---qsfsck-kkff
eskkctdcasers--gvvhflytgplrsa------------gsh----ka
liqte
>node10
ahvalpphlnlsscgfkkcnfaq-khatasst-----d-----vdsktte
igmkai---vhskdpgksnfasssta--k----nnfvahtresdgkvp-y
dvrnlrehrlqkay---ckarksdpilhgsadcstkkswgkraavaeaik
drvscqkgcrfgldscmqm--sgflqishlrrtahfkyyypnsrr--mvc
g--h----ksv--lnn-------qkessvhggdlasvlgglgsfgckals
egyvlrvyvqlgngppkypskayasgri--vspr--agqgiy-vnakdhk
ega--apalikitvkhtnap--msnidqa--cpplgnthappsddqhnma
hvllhrdenvr-gtgqtacnsqstadptktckpfclillk------rekk
--vvvfaycatsnifdlls------svfmknknskrvgavnhql---gva
ecqfyslqkacppacpgnspgvdy---gkenkkcgia---asn--geecn
dkspaglipkiya-msrvsepcsrdgrv--pnlsal---qsfsck-kkff
eskkctdcasers--gvvhflytgplrsa------------gnh----ka
liqte
>ENV_HV2BE/24-510
shvalppalnlsncgfkkcnfaq-khatasst-----d-----vdsqsse
igmtni---vhdkdpgkstfnsssta--k----infiaharesdgkvp-y
evrnlrehrlqkay---hkanksdpilhgnadcstakswgkraavaeaik
drvscekgcrfghdscmqm--ygvlqlshlsrtshfkyyypngrr--mvc
gykf----ksv--lnn-------ekesgvhgfdlnsvlgglsdfgckals
egyvlkvyvqlgngppkypskdygsgri--vspr--agqgif-vnakthk
egs--apalikiivkhtnap--mseidda--cpplgnthtppsddqhnma
hvllhreanvr-gtgqtacnsqstadvtktckafclillk------rek-
----afaycanssifdllsgsfayysvfmkn-nst------hel---gva
eckfyslskacppacpggspgvdy---gkdnkkcgia---asn--geecn
dkspaglipkilaamsrvnepcsrdgkvgapnlsal---qsfnck-kkff
eskkctdcaserscsgvvhflytgplrpa------------gsh----ka
liqte
>ENV_SIVGB/47-569
ldvvinthvaleycrfnksnsfh-kflavsss-----h-----ldantqe
iamkdislkihtketvredlgshvnaegk----alnagnatke-------
ai---kecvlylan---cqskkteyitkgtatctakrtlvkppavpsplk
r-------------aclev--thfvrt-----egl--yiyphtgrdclpc
g--n----pnicplnhllslilkvksstirtgdltavyggngpfdtnvim
egrllqvypqvgahtnsyaakqyst--s--ealrqeagktfy-saa---t
tga--aphliavqvdnkdvp--fgnldeengaaplsqtegpptaghpeta
r--vhrdtkek-vtgttpkdgqkdndlpntgqnfcmvilk------kkmt
--salfnvsa--nlftllq------agfvndkrhkhlqeishppfvqkte
rchfygldakcss-spgqsggshysdagkqkhkcavr---nkiqegaita
ftgppsfap---------------ggnv--ekpktl---etfdck-kk-l
edrkcsaskprst--vvanpiyicplrktalnk-----hcpgvnrwgaas
llq-e
>ENV_HV2D1/24-501
anvalpphlnlsncgfkkcnfaq-khatasst-----d-----vdsqtte
igmtni---vhskdpgkstfssssta--k----infvtharesegkip-y
dvrdlrehrlqkay---ckahksdpilhgnadcstakswgkraavaeaik
drvscqkgclfgldscmqm--ygflqishlrrtahfky----arr--mvc
g--h----ksv--lnn-------ekdssvhggdlgsvlgglsgfgckals
egyvlkvyvqlgdgppkypakaygsgri--vspr--agqgiy-vnakdhk
ega--apalikiivkhtnap--msnidda--cpplgnteapasedqhnma
hvllhreanvr-gtgqtacnsqsntdetkqckpfclillkqhcelarekk
--vvafaycatsdvfdlls------svfeknknskrvgavnhel---gva
ecafytldkscppacpgsspgvdy---gkakkkcgia---asn--geecn
dkspaglmpkiya-msrvsepcsrdgrv--pnlsal---qsfsck-nkfy
eskkctdcatern--gvvhflytgplspa------------gsh----ka
liqte
>ENV_HV2G1/23-502
ahvalpphlnlsncgfkkcnfah-khatasst-----d-----vdtqtte
lgmkni---vhskdpgrstsssssta--k----infvthtresdgkvs-y
dvrnlreh--qkay---ckafksdpilhgtgdcstkaswgkrpavaeaik
drvscqkgcrfgldscmqmmkygflaishlrrtshfkyyypnsrr--mvc
g--h----ksv--lnn-------akessvhggdlgsvlgglgsfgckals
ngyqlrvyvqlgngppkypskayasgri--vapr--agqgiy-vnakdhq
ega--aptlikiivkltnap--msnidda--cpplgnthappsddqqnma
tvllhrdenvr-gtgqtacsnqstadetktckpfclillk------rekk
--vvafaycatssifnlls------svfmtnknskrvgavnhel---gva
ecqfyslesacppacpgnspgvdy---gkenkkcgia---asn--geecn
dkspaglipkiya-msrvsepcsrvgri--pnlsal---qsfsck-kqff
eskkctdcasers--gvvhflytgplrst------------gsh----ka
liqte
>ENV_HV2NZ/24-502
vhvalpphlnlsncgfskcnfgq-khstaskt-----d-----vdsqtte
igmkni---vhskdpgkstfsststa--k----infvahtresdgkvp-y
dvrnlrehrlqkay---cksnksdplthgnadcsakkswgkraavadaik
drvncqkgckfgldsckqm--ygflqisnlrrtshfkyyypnsrr--mvc
g--h----ksv--lnn-------nkessvqggdlgsvlgglgsfgckals
egyvlpvyiqlgngppkypsnayasgri--vspq--agqgiy-vnakdhk
ega--apalikiiikhtnap--msnidda--cpplgnthappsddqqnma
hillhrvenvr-gtgktainsqstaeetktckpfclills------rekk
--vvafaycatsnifelis------svfmknknpkrlgtvnhel---ain
ecqfyslekacpnacpgrspgvdy---dkdnrkcgia---atv--geecn
dkspaglipsiye-msrvsepcsrdgrv--pnlsaleqqqqfsck-nkff
eskkctdcasers--gvvhflytgplrsa------------ggh----ka
liqte
>node11
ahvalpphlnlsncgfkkcnfaq-khatasst-----d-----vdsqtte
igmkni---vhskdpgkstfssssta--k----infvahtresdgkvp-y
dvrnlrehrlqkay---ckahksdpilhgnadcstkkswgkraavaeaik
drvscqkgcrfgldscmqm--ygflqishlrrtshfkyyypnsrr--mvc
g--h----ksv--lnn-------ekessvhggdlgsvlgglgsfgckals
egyvlrvyvqlgngppkypskayasgri--vspr--agqgiy-vnakdhk
ega--apalikiivkhtnap--msnidda--cpplgnthappsddqhnma
hvllhrdenvr-gtgqtacnsqstadetktckpfclillk------rekk
--vvafaycatsnifdlls------svfmknknskrvgavnhel---gva
ecqfyslekacppacpgnspgvdy---gkenkkcgia---asn--geecn
dkspaglipkiya-msrvsepcsrdgrv--pnlsal---qsfsck-kkff
eskkctdcasers--gvvhflytgplrsa------------gsh----ka
liqte
>node9
ahvalpphlnlsscgfkkcnfaq-khatanst-----n-----vdsktte
igmkai---vhskdpsksnfasssta--k----snfvghtresdgkvp-y
dvrnlrehqlqmay---ckarksdpimhgsadcatkkswakpaavaeaik
qrvscqkgcrfgldscmqm--sgflqishlqrtahfkyyypnssr--mvc
g--h----ksv--lnn-------qkessvhggdlasvlgglgsfgckals
egyvlrvyvqlgngppiypskayasgri--vspr--agqgiy-vnakknk
ega--aptligitvkhtnap--mtnidqe--spplgnthappsddqqnma
h--lhrdenvr-gtgqtacngqstadptktckpfclillk------rekk
--vvvfaycatsnifdlls------svfmknknskrvgavnhpl---gta
ecqfyslqkacppacpgqspgvdy---gkenkkcgia---asn--gepcn
dkspaglvpkiya-mprvsepctrdgrv--pnlsal---qsfsck-kkff
eskkctdcasers--gvvhflytgplrsaalnkkiqasqcagnh----ka
liqte
>ENV_HV2D2/24-513
ahvtlpphlnlsscgykkcnfsq-khatgsst-----d-----vesktte
igmkai---veskdpgkndfassava--k----dsfvahtrptvgkvp-y
qvknlrehrlhkaf---ckarhsdptlhgsadvstktswgkraagaeslk
ervscqkgcrfgldscmqm--sgflqhvhlrktahfkyyysdsrr--mvc
n--hsitrksv--lnn-------rkegsvhggdlasvlgglgsfgckall
egyvlsvyvqlgegppkypskacasgri--vsqr--agqgiy-vkakehk
egalgapalikvtvkhtnap--lsnvdqa--sppvgnthappsddqhsmt
hvllhrdenvr-gtgqtacnsqstaditksckafclivlk------tekk
--vavyaycatsnkfdlls------svflkkknskrvgavnhql---gvs
qcqfhtlqkacppacpgdspgvdy---gkdnkkcgia---asn--geesn
dkvpaglipkiyn-msrvsegcardgrv--pnlspl---qsftckskkff
eskkvtdcaserd--gvihflytgplrsa------------gnh----ka
liqte
>node7
gqvalpahlslgycgfqkc-flq-khvtgnss-----h-----veasnth
igmqai---vavknptdsafgsqasa--k----skfvgnvkqadqkvaty
qvrnlresalqmvf---ckavktdpimhgstncsgkkswvaraavpasik
q-------------scmek--ndflqi-----aavwsyyyphsah--mpc
g--h----psi--lnp-------ekqssvhsgeltavlggvgpfgckavs
dgyvlrvfvqvgpgapnypskgyas-------tr--sgdgiy-saakknk
tga--aphligiiikhkeep--fgnvdqe--applkqtegpptndhqnma
h--lhrdtkvr-ntgqtasdgqgtadptktgrhfcliflk------rekk
--vglfkyca-sniftlle------svfmknknkrrvsalthplf-hdtg
ecqflsldescppacaaqsngvky---gkekkkcaia---tgq--gatny
dksppsfvpkiyt-mprvsdgcsidgra--anlnal---qsfack-kkfm
eskrctdcapeks--gvmhglytcplrssalnkkvqsghcagnp----as
liq-e
>node8
gqvalpahlslgycgfkkcaflq-khvtgnss-----h-----veasnth
igmqai---vttkdpsdsafgsqasa--k----snfvgnvkqadgkvaty
qvrnlresalqmaf---ckaiktdpimhgstdctakkswvkraavpdsik
q-------------scmem--tdflqi-----aavwsyyyphsar--mpc
g--h----psi--lnh-------ekqssvhsgdltavlggvgpfgckavs
dgyvlrvyvqvgpgapnypskgyasgsi--iatr--sgdgiy-saakknk
tga--aphligiiikrkdep--fgnidqe--applsqtegpptndhqnma
h--lhrdtkvr-ntgqtasdgqstadptktgrhfcliflk------rekk
--vglfkyca-sniftlle------svfmknknkkrvsalshplf-hdtg
ecqfysldescppacaaqspgvky---gkekkkcaia---tgk--gapsy
dksppsfvpkiyt-mprvsegctrdgrv--anlnal---qsfack-kkfm
eskkctdcapeks--gvvhglytcplrssalnkkvqsghcagnh----as
liq-e
>ENV_HV2CA/25-512
vhvalpphlnlsdcgfkkcnfaq-khatasst-----d-----vesqtte
igmkni---vhskdpgkstfssssta--kleeginfvantreqdgkvp-y
dvrnlrehrlqkay---ckahksdpilhgnadcstknswgkrgevaeaik
drvscqkgcrfgldsckqm--tgflqifnlrrtshfkyyypdsrr--mvc
g--h----ksv--lnn-------ekessvqgsdlgsvlsglgsfgckalh
egyvlrvyvqlgngpprypsna-----ihtvssq--agqgiy-inakdhk
ega--apalikiivkhlsap--msnidda--cpplgnthappsddqqkma
hvllhqeenvr-gtgetpcnsqstaeetktckpfclills------rekk
--vvafaycatsnifdllg------svfmknknparvgtvnhel---gia
ecqfyslnsacppncpnnspgvgy---qkdnkkcgia---ann--geecg
dkspsglipkiya-ssrvsepcsrdgrv--selsal---qqfsck-kkff
eskkctdcasdrs--gvvhflytgplrsa------------gsh----ka
liqte
>ENV_SIVG1/22-522
gqvalpahlslgycgyqks-flq-rhvtgnsspvhkdh-----veasnth
igmqai---vavknptdsafgshaaa--k----skfvgaikqadqkiaty
qvrnlretalqmvf---ckgvktdtimhgstncsdkkpwvaraavpgsik
q-------------scmek--ndflqi-----aavwsyyyphsah--mac
g--h----psi--lyp-------ekqssvhsgeltavlggvgpfgckgas
dgyvlrvfvevgpqapnyptkgyas-------tk--sgdgiaksaakkhk
tga--aphhigiiikhkeep--fgnvdqe--apptkqtddpptndhqnma
h--lhrdtkvr-ntgqtasdgqgtsdptktgrhfclvflk------rekp
--vglfkyca-sniftlle------sv-mknknkrfvsatthplf-hdtg
ecqflsleencppacaaqsngvky---gkdkktcavs---agq--gatny
dktppsfvpkiet-mprlsdgcsfdgra--anlnal---lsfack-kkfm
eskrctdcapess--gvkhglytcplrksalnkkvqgghcannp----aa
liq-e
>node18
ahvalpphlnlsncgfkkcnfaq-khatasst-----d-----vdsqtte
igmkni---vhskdpgkstfssssta--k----infvahtresdgkvp-y
dvrnlrehrlqkay---ckahksdpilhgnadcstkkswgkraavaeaik
drvscqkgcrfgldscmqm--ygflqishlrrtshfkyyypnsrr--mvc
g--h----ksv--lnn-------ekessvhggdlgsvlgglgsfgckals
egyvlrvyvqlgngppkypskayasgri--vspr--agqgiy-vnakdhk
ega--apalikiivkhtnap--msnidda--cpplgnthappsddqhnma
hvllhreenvr-gtgqtacnsqstadetktckpfclillk------rekk
--vvafaycatsnifdlls------svfmknknskrvgavnhel---gva
ecqfyslekacppacpgnspgvdy---gkdnkkcgia---asn--geecn
dkspaglipkiya-msrvsepcsrdgrv--pnlsal---qsfsck-kkff
eskkctdcasers--gvvhflytgplrsa------------gsh----ka
liqte
