>ENV_HV2NZ/24-502
ekscagihaec------ypdtevatdgpi-----fytkkgsythytgssn
lvgnkdpkfasts--nfrpfmdeahidtksphegyalkktslthttvlgv
ggklecllnalgcnlplyekgaalskgwhthpkrgknvlckkkldiqtwi
wknggkraakkmpttgkgtkmisepk-cgdllag-rdpqei---svksss
kkdivnsf-------qkiihldssaallaectiltdcaevgktp------
-----kiepvlglea-----------picqlflhthagnclgpkecrrga
hayasettrskqdgddvayaanmdsnwpavidsfegyqaglkleflnvea
etvdgawcala-wt---kavl--spqvedmqggyvipllrsdlcesdhfn
lkafrlgelvkykqvtqdycgparcvagcplg--cfgqgnvptkdshntg
gvtgvawv-----fltayqgqvyapti----apdqlydvtktldpvqyff
vicgeineflalkeggqrnkserddpawgfkqaadlnptcgiparvcrga
atq--ahaktik
>ENV_HV2BE/24-510
ekscagiraen------ypdtevktdgpi-----fytkkgtfthyngssn
lvegkdpkfgsst--sfrpfldeshietksphsgyalkktelthtktlgv
ggklecllnalgcnlplyekgaalskgwhdhskkgqpvlcskkldeqiwi
wknggkraadkmpttgrgtksisepk-cgdllpg-kdpqdi---svksnc
kkgivnsf-------qkinfldsnaallaecvsltdsadvgdap------
-----kvepvlglel-----------pvcqlflhihagnclgpkecrkga
hafasettgskqdgddiayvinmdsewtailntfegyragmkiqflnvep
etvdgawcalm-wt---kvvlpyspqveafqggyimpllrsdlcesthfn
lkdlrlgelvkykqttadycgparc-rgcglg--cfgqgnvpt----ntg
dvtgvlwv-----fltayqgqvyaptidmqsapdelydvaktlkpvqfff
vvcgevneflalkeggqrkkserddpawrfrqaadldptcgipasvcraa
ktq--ghaktik
>node14
ekscagiraen------ypdtevstdgpi-----fytkkgtythytgssn
lvgnkdpkfgstt--sfrpfldeshidtksphsgyalkktslthtkvlgv
ggklecllnalgcnlplyekgaalskgwhthpkrgqnvlckkkldeqtwi
wknggkraakkmpttgrgtksisepk-cgdllpg-rdpqei---svksnc
kkdivnsf-------qkiifldssaallaecvsltdsaevgdtp------
-----kvepvlglel-----------pvcqlflhthagnclgpkecrrga
hayasettrskqdgddiayvinmdsnwtailntfegyragmkieflnvet
etvdgawcalm-wt---kgvl--spqvedfqggyimpllrsdlcesdhfn
lkdlrlgelvkykqvtsdycgparc-rgcalg--cfgqgnvptkeshntg
evtgvawv-----fltayqgqvyaptidmqqapdelydvaktlepvqfff
vvcgevneflalkeggqrnkserddpawgfrqaadlnptcgipasvcraa
atq--ahaktik
>node17
ekscagiraes------ypdtevstdgpi-----fytkkgsythytgssn
lvgnkdpkfgstt--sfrpfmdeehidtksphegyalkktslthtkvlgv
ggklecllnalgcnlplyekgaalskgwhthpkrgqnvlckkkldeqtwi
wknggkraakkmpttgrgtkmisepk-cgdllpg-rdpqei---svksnc
kkdivnsf-------qkiifldssaallaectsltdcaevgktp------
-----kiepvlglea-----------picqlflhthagnclgpkecrrga
hayasettrskqdgddvayaanmdsnwpavintfegyqaglkieflnvet
etvdgawcalm-wt---kgvl--spqvedmqggyvmpllrsdlcesdhfn
lkdlrlgelvkykqvtadycgparcvrgcalg--cfgqgnvptkeshntg
evtgvawv-----fltayqgqvyaptidmqqapdelydvtktlepvqfff
vvcgevneflalkeggqrnkserddpawgfrqaadlnptcgipasvcraa
atq--ahaktik
>ENV_HV2G1/23-502
ekscagiraen------ypdkdvstdgpi-----fytkkgsythytgstn
lvgdkdpkfgstt--sfrpfl------tkspheayalkktslthtkvlgv
ggnlecllnalgcnlplyekgaalskgwhthtkrgdnvlckkklddhtwi
wknggkraakkmpttgkgsksvpepk-cpdllpg-rdpqei---svksnc
kkditnsf-------qkvafldssaalleectsltdcaevgkap------
-----kvelvlglel-----------pvcqlflhthagnclgpkecrrgn
hayasettrskqdgddiayainmdsnwtgvinlfegydaglkieflnvet
etvdgawcalm-wt---kgvl--rpqvedyqggyvapllrsdlcesdhfn
lkdltlgelvkykqvtsdycgparcvrgcalg--yfgqgnvplkeshntg
evtgvawvvngphfltayqgqvyaptidvqqapdelydvaktlepvqfff
vvcgevnsflalkegghknkserddpawglrqaadlnptcgipasvcraa
atq--ahavtik
>ENV_HV2CA/25-512
ekscagiraestqarhvy-dtevstdgpi-----sykkkgsythytgsan
lvgnkdpkfgsat--sfrpfmdeehidtksphegyalkktslthtkplgv
ggklecllsalgcnlplyekgaaltkgwhthpkrgqkvlckkkldeqtwi
wknggkraakkmpdtgrgakmiseck-cgdllpg-rdpqei---svksnc
kkdvvksf-------lkiifldssaallaecisvtdcgevgktp------
-----kiepilglee-----------picqlflqthagnclgpkecrrga
hayasnttrskqdgddvayaarmdnnwparinsiegyqaglkieamnvet
etvdgawcalm-wt---kgvl--sqqvedmqggfvmpllksdlcesdhfn
lkdlrlgelvkykqvtadycgparcvrgcalg--cfcqqnvrtkdshntg
evtgvdwv-----fltayqgqhyaptidmqqapdelydvaktlepvqfff
vvcgevneflalkgagqrnkserddpawgfrnaadlnptcgvpasvcrrt
ape--ahaktik
>ENV_HV2D1/24-501
ekscagiraen------ypdtkvstkgpi-----fytkkatythytgspn
lvgnkdpkfgstt--sfqp-ldeshidtksghsgyalkktalthtkvlgv
g--lecllnalgcnlplyekgaalskgwhthprrgqnvlckkklaedkwi
wknggkmaakkmpttgrgtksesdpk-cgdllpg-rdpqei---svksnc
kkdivhsf-------qkniflsssaallaecvsltdsaevgdtp------
-----kvepvaglel-----------pvcqlflhthagnclgpkvckrna
hayasettrskqdgydiayvinmdsnwtailktfdgyragkkieflnvet
etvdgawcalm-wtkyvkgvl--spqtedfqggyiipllrsdlcasdhfk
lkdlrlgdsvkykqvtpdycgparc-rgsalg--cfgqgnvptseshntg
gvtgvawv-----fltsyqgqvyaptidmqqapeelydvartlepvqfff
vvcgevieflalkeggqrnkserddpawgfrqaadlkpscgipasvcraa
atq--ahaktik
>ENV_SIVG1/22-522
eknc--irtes------ypdtevstdgpi-----yytiaaylehfsgpsa
lvgdkapefgstt--sf--faneg-vnaksldegyglkdscitqtkvagv
gskleclly----vlplyeqggaltkewkvhntrgqdv--------vawi
wkdggvraaqmmptsgrgtkstsgak-casvlag-pdpe----grlkrtc
nkdvasifkkyrailekiiflqagpgllalcttlkdcaqvqkth------
-----kvepvngfel-----------pvcplflh---------kqcirne
hayacdttraal------egkk-dttwtgvintfqgyqasltpeflnvnn
dtvesawcalmtwt---kgvl---psieefkggyspkllqdnlcaevhyn
lrdfklgkqvaftqasadicgpsrcvrqcelarfcfgqgnirtkaahktg
evsgvawv-----llvayksqcyaattnik---ddlldikkvlapiqfff
lvcseinsvlelkegsqrtksernnsgwgfrqtadldtacgtpssvcrga
pkq--peakifr
>node8
eknc--iraen------ypdtevstdgpc-----fytiaaayshytgsst
ltgnkdpkfgstt--sf--fanee-vnaksldegyglkkscltqtkvlgv
gskleclly----vlplyeqggalakewhthntrgqqv--------qawi
wkdggvraaakmptsgrgtkstsgpk-casllag-pdpeka---slkrtc
nkdvanif-------ekiiflqsgatllarcttlkdcaqvqktp------
-----kvepvlglel-----------pvcqlflh---------kqciraa
hayacdttraal------egkk-dstwtgvintfqgyqasltpeflstnt
etvesawcalm-wt---kgvl--rpsieefqggysmkllqgnlcaedhyn
lkdfklgeqvkftqvtadvcgptrcvracala--cfgqgniptkeshktg
evtgvawv-----fleayqgqvyaqttnikvtpdelfdvkkvlepvqfff
lvcteinsvlelkegsqrtkserddsgwgfrqtadldtacgapssvcrga
pkq--anaktfr
>node7
eknc--iraes------ypdtevstdgpi-----fytiaayyshytgpsa
lvgdkapkfgstt--sf--fanee-vnaksldegyglkdscitqtkvagv
gskleclly----vlplyeqggalakewhihntrgqev--------lawi
wkdggvraaakmptsgrgtkstsgak-casllag-pdpekapsgslkrtc
nkdvanifkkyrsilekiiflqagasllalcttlkdcaqvqkth------
-----kvepvngfel-----------pvcplflh---------kqcirne
hayacdttraal------egkk-dstwtgvintfqgyqasltpeflsvnt
dtvesawcalmtwt---kgvl---psieefkggyspkllqgnlcaevhyn
lrdfklgeqvaftqptadvcgpsrcvracala--cfgqgniptkaahktg
evtgvawv-----lleaykaqcyaattnikvtpddlfdikkvlapvqfff
lvcseinsilelkegsqrtkserddsgwgfrqtadldtacgtpssmcrga
pkq--aeaktfr
>ENV_SIVV1/24-538
lknc--nraqs------ypdttvsadgpisggpcfytlaanyqhypspsa
qvgdkapkfqstt--sf--faneg-vsaktldegyglqescitqtkvtga
gskvaclly----vfplyeqggdlskewhihstsgeev--------lpwi
wddggikaaknmptggrgtestsatk-vasllag-vdlekamsgslkrvc
nkdvpntfkkyrsilnkiif------llalcttlktcaqvkkgh------
-----kvepvngfel-----------pv--lflt---------kqcirne
hayacdltratl------egkk-gptwagvkstfqgyqasf--eftsvkt
dtvdsawcskmtst---kgvh---psiqeytgsyspkllegnlcsevhyn
lrdfklgeqvfftqstadicgpsrcvkac--a--cfgqghiptkeahktg
nvtgvpwl-----llesykaqcygaitnikvtpddlfdvkkvlapvqfff
lvcapissildlkegsqrtksdrndtgwgfrqtsdldtacgtpvrmcrga
pkqkqteaktfr
>ENV_SIVM1/24-528
eksc--iraek------ypdrelttdgpi-----fytkkgtythytgssn
lvgnkdpkfgstt--sf--flgee-idtkep-----------tytkvlgv
ggkleclly----nlplyekgaslskgwhthpkrgqnvlckkkldeqtwi
wknggkraakkmhttgrgtkstsepk-cgdllan-rdpqev---slkstc
kkdivniy-------qkliflecsaalvakctsftdcaevgktp------
-----kveptlglel-----------pviqlflh---------tectraa
hayacdttrsnqdgddvayvinlssnwtgvintfigyqagltieflnvet
ekvdgawcalm-wt---kgvl--rpqvedfeggyvlklvhsdlcesdhfn
lkdlrlgelvkykevtsdvcgpargvrgcalg--cfaqgnvptkeshstg
dttgiawv-----fltayqgqvyaptidmqtapdelydvaktlepvqfff
lvcnevnsflaleqgaqrnksdrddqawgfrqaaelhptcgipssvcraa
akq--anaktfr
>node19
ekscagiraen------ypdtevstdgpi-----fytkkgtythytgssn
lvgnkdpkfgstt--sfrpfldeehidtksphegyalkktslthtkvlgv
ggklecllnalgcnlplyekgaalskgwhthpkrgqnvlckkkldeqtwi
wknggkraakkmpttgrgtksisepk-cgdllpg-rdpqei---svksnc
kkdivnsf-------qkiifldssaallaectsltdcaevgktp------
-----kvepvlglel-----------pvcqlflhthagnclgpkecrrga
hayasettrskqdgddiayainmdsnwtavintfegyqaglkieflnvet
etvdgawcalm-wt---kgvl--spqvedfqggyvmpllrsdlcesdhfn
lkdlrlgelvkykqvtsdycgparcvrgcalg--cfgqgnvptkeshntg
evtgvawv-----fltayqgqvyaptidmqqapdelydvaktlepvqfff
vvcgevnsflalkeggqrnkserddpawgfrqaadlnptcgipasvcraa
atq--ahaktik
>node10
ekscagiraen------ypdtevstdgpi-----fytkkgtythytgssn
lvgnkdpkfgstt--sfrpflnee-idtksphegyalkktslthtkvlgv
ggklecllnalgcnlplyekgaalskgwhthpkrgqnvlckkkldeqtwi
wknggkraakkmpttgrgtksisepk-cgdllag-rdpqei---slksnc
kkdivnif-------qkiiflessaallakctsltdcaevgktp------
-----kvepvlglel-----------pvcqlflhthagqclgpkecrrga
hayasettrskqdgddvayainldsnwtgvintfegyqaglkieflnvet
etvdgawcalm-wt---kgvl--spqvedfqggyvmpllrsdlcesdhfn
lkdlrlgelvkykqvtsdycgparcvrgcalg--cfgqgnvptkeshntg
evtgvawv-----fltayqgqvyaptidmqqapdelydvaktlepvqfff
lvcgevnsflalkeggqrnkserddqawgfrqaadlnptcgipasvcraa
atq--ahaktik
>node18
ekscagiraen------ypdtevstdgpi-----fytkkgtythytgssn
lvgnkdpkfgstt--sfrpfldeehidtksphegyalkktslthtkvlgv
ggklecllnalgcnlplyekgaalskgwhthpkrgqnvlckkkldeqtwi
wknggkraakkmpttgrgtksisepk-cgdllpg-rdpqei---svksnc
kkdivnsf-------qkiifldssaallaectsltdcaevgktp------
-----kvepvlglel-----------pvcqlflhthagnclgpkecrrga
hayasettrskqdgddiayainmdsnwtavintfegyqaglkieflnvet
etvdgawcalm-wt---kgvl--spqvedfqggyvmpllrsdlcesdhfn
lkdlrlgelvkykqvtsdycgparcvrgcalg--cfgqgnvptkeshntg
evtgvawv-----fltayqgqvyaptidmqqapdelydvaktlepvqfff
vvcgevneflalkeggqrnkserddpawgfrqaadlnptcgipasvcraa
atq--ahaktik
>node11
ekscagiraen------ypdtevstdgpi-----fytkkgtythytgssn
lvgnkdpkfgstt--sfrpfldeehidtksphegyalkktslthtkvlgv
ggklecllnalgcnlplyekgaalskgwhthpkrgqnvlckkkldeqtwi
wknggkraakkmpttgrgtksisepk-cgdllpg-rdpqei---svksnc
kkdivnsf-------qkiifldssaallaectsltdcaevgktp------
-----kvepvlglel-----------pvcqlflhthagnclgpkecrrga
hayasettrskqdgddiayainmdsnwtavintfegyqaglkieflnvet
etvdgawcalm-wt---kgvl--spqvedfqggyvmpllrsdlcesdhfn
lkdlrlgelvkykqvtsdycgparcvrgcalg--cfgqgnvptkeshntg
evtgvawv-----fltayqgqvyaptidmqqapdelydvaktlepvqfff
vvcgevnsflalkeggqrnkserddpawgfrqaadlnptcgipasvcraa
atq--ahaktik
>ENV_HV2D2/24-513
epscagiraen------ypdkevstdgpt-----fytkpgty---tgsnn
lvgnkkpkfgttt--nfrpflkea-idtksphqgyalkkvslthtgvlgv
gg-----vyalgcalplyekgaallkgwhthpdrslevlckkklneqtwl
wk-vgkraskkmpstsrgtkalgepk-cgdllag-rklqei---slkgnc
kkdivkif-------qkiiflessaallakcdslidcfqvgktp------
-----kvepvlglelnwmlvlgspgrpvcqaflhthagqclgpmechraa
hlygsattrskqdgddvayaiyldvnwtgvinafdsyqaglkieflnvet
etvngdwcaim-wt---kgvl--slqvedfqggyvmpllrsnmcdsdhfn
lkdvrlgelvrymqatsdycgparcvcgcalg--cfgqgnvptkqshnts
evtgtawv-----fitayqgqvytptidmqqtpdqlydatktlepvqfff
lvigdvksflalkeggqrnkserddqawgfrqaadlsptcgipapvcraa
atq--ahaktik
>ENV_SIVGB/47-569
ekle--srgdg------yapvapltdiga-----lhgaghecqiatgsat
leggkepkfgsttkltf--fgnee-lnvqsldeslklkksclnnkkdlav
gsalnsflc----aaptyqqagslakdwhtnntsqdqv--------vawi
wr----------ptsnkgnastkgpkctanllaptqetdet---tltkt-
nseseslf-------eriiflpsgetkiahcttlkecaq--ktqscpdfi
nhesckaklvvglkl-----------avcqlfvh---------kidrpla
haygndtsrasl------egvk-aaewtnaistykgyeanltpnftsttt
etvgdawcalm-wt---kvrl--rpdlgqfegsfkmqllqgqicvqdvwg
lkdyrlfgrvkfshvksdigghtqctsgsqle--cysqgnmptkylhaag
evvgvarl-----fvnaysgqvyanqth-kiapde-fevrdalepaaflf
-----aaaglelkegslptkterrda-wsfrdgahlntacgapsavc---
--v--d----fr
>node9
eksc--iraen------ypdtevstdgpi-----fytkkgtythytgssn
lvgnkdpkfgstt--sf--flnee-idtkapdegyalkksslthtkvlgv
ggkleclly----nlplyekgaalskgwhthpkrgqnvlckkkldeqtwi
wknggkraakkmpttgrgtkstsepk-cgdllag-rdpqev---slkstc
kkdivnif-------qkiiflessaallakctsltdcaevgktp------
-----kvepvlglel-----------pvcqlflh---------kectraa
hayacdttrsnqdgddvayainldsnwtgvintfegyqagltieflnvet
etvdgawcalm-wt---kgvl--rpqvedfqggyvmkllhsdlcesdhfn
lkdlrlgelvkykqvtsdvcgparcvrgcalg--cfgqgnvptkeshntg
evtgvawv-----fltayqgqvyaptidmqtapdelydvaktlepvqfff
lvcgevnsflaleeggqrnkserddqawgfrqaadlnptcgipasvcraa
atq--ahaktfr
