>node9
lr-gqnllggsecalti--l----lgqlewykylkgslfy------grpp
apsllkyvsmmpayrasamgd--galasreakgetkdarnf-kqqrcvpc
gtmisrmasvyylfknycmkat---dlv----gfgvcnaevgqdhkpagl
yeakkcavntaqnsf--qavcritsllssgg---r--ci-tagpk----c
qvklktntqvevvrvkctnagfgcarcsgspatiak-ktkldlvvtmktc
frligksvliiaslsatlshllvr----tpfgvptgkkshrvlpqetapc
akn--cvea--ygrdp------------llvlnvffrlsaspkieayhen
aqksiktg-hsdvckaqggdyfqnat-hkacngaqpphlfrksvtihclr
ggrylivfkawglntpytdr-ffgevdqladdy-ck-lmtvgeckqk---
----mngpfsqypagnvdessdweefgkddhnekgtgpvlfnlkvawlhg
cvhkileiailghgsltvp-lknnasrpgktsh-nlpgmgggsqgvhfst
csivaeeplirkystl---vkkvt-k
>node7
lr-avnllggskcslsi--llps-lgqldwykylkgslfy------grpp
apsllkygglmptyranamgd--gvvrsceakgdtkdadny-kqtkcvvc
gtmtsrmaavyylfkklcmkat---qlv----gfgvttretsqnfkpagl
gdakrcavntaqqtf--qsvckitsllstggqyqk--ci-taaggvvtkc
qiklkdnsqv--vrvkcasag--ytlcaitptgiak-ktklsvivamkvc
frkitknvlvitr---alpllllr----tpfgvpsgkkshrvlqhdtapc
gkn--hada--fargp------------lqrtdtfiklnadpkmeayqak
aqksiksg-hndvcgeidgdyfekit-nkacnksrppqlfkkpvvvhclr
ggrylivftawgfd----dmkfftdvnqlaeav-cr-lfkvgepktk---
----msapfsilqsgnvaessdwddfgsnehnetvcsrvlfdlkcawwhg
cvhalleivvleqgtldvp-iesksarpgktsh-dlpgmggasqnihfpd
ctqvgeep-inkygsl---aekit-k
>ENV_SIVG1/22-522
lr-avnllggsktslsi--ilps-lgqldwykylkgslfy------grpp
apsllkyaglmptyranamgd--gvvrsceakgdtkdatny-kqtkcvlc
gtmtsklalvyylfkdlcmkav---qlv----gfestaqetshnfkpagl
gdakrcavntadltf--qsvckitsllatggqcqk--si-tgaggvvtkc
qiklkdgsqv--vrvkcasqg--ytlcailptgiak-ktqlsvivamkvc
frkitksvlvitr---aaallllr----tpfgvppgkrshrvlqhdtapc
gkn--hadarifargp------------lqrtdtfiklngdpkmeayqak
aqssiksg-hndvcgeidgdyfdkit-nkacnksrsplmfkkpvvvhclr
ggrflivf-awgfd----dmkfftdvnhlaeav-ck-vfkvgepktk---
----msapfsvlqsgntaessdwddfggnehnetvcsrvlfdlkcawwhg
cvhalleivvleqgtldvp-iesksarpgktsh-dlpgmggasqnihfpd
ctqvgees-inkygsl---mekis-k
>node19
lr-gqnllggsecaltiarl----lgelewykylkvslfy------grpp
apsllkyvsmmpayrasamgdpegalasrevkgetkdarnf-kqqrcvpc
gtmisrlastyylfknygakat---dlv----gfgvcntevgqdkkpagl
yaakkcavdtaknsf--qavcritsltnsgg---r--ci-tagpk----c
qvklktntqvevvrvkctnagfgcarcngspgtiak-ktkldlvvtmktc
frligksvlitatlsatlshllvk----tpfgvptgktshrvlpqetapc
akn--cvea--yerdp------------lmvlngffslsaspkveayhen
------tg-hndvckaqggdyfqnat-hkacngvepphlfrkhvtmhclr
agrflivfkawglntpytdp-ffgevkqladdy-ct-lmtvgeckqk---
----mngpfgqypagnveessdweefgkddhnekgtgpvlfnlkvawlhg
cvhkileiailghgsltep-lkanasrpgktah-nlkgmgggsqgvhfst
csivaeeplirnystl---vkkva-k
>ENV_SIVM1/24-528
lh-gqnllgdsecaltf--l----lgqlewykylkgslfy------grpp
apsllkylsvmpayrasamgd--galasreaksetkdersf-kqqrcvpc
gtmlsrmasvyylyknycmkatgdfdlv----gfgvcnaelgqdhkpagl
yaakkcavntaqnnf--qavcritsllstgg---r--ci-tagpk----c
qvklktntqvnvvrvkctnagfgcarcsgspatiak-kssldlvvtmktc
frligkslliianlsatlshllvr----tpfgvptgkkshrvlpqesapc
akn--cven--ygkdp------------llvlnhfyrlsaspkieayhen
aqkvikta-hsdvckaqggdyfqnat-hkacnnaqpphlfrksvtihclr
ggrylivfkgwalntpytdr-ffgqvdqlatey-ck-lmttgecdqk---
----mngpftqypagnvdessdwetfgrddhaekgtapvlfnlkvawl--
-vhklleiailahgsltvp-lknkasrpgktsh-nlpgmgggsqgv---n
csivaeeplikkyst------kvt-k
>ENV_HV2D2/24-513
hr-gdnllggaecalsi--l----lgevewykylrgslfy------grpp
apsllkyvsmmpacrasamrd--galasrdskgetkdarnf-krqrcvpc
gnmvsrmasvyylfknycakaa---dlv----gfgvcnaevgqdhkpagl
yaakkcavntaknsf--qaicritsltnngg---r--ci-tagpk----c
qvqlktntrvevvrvkssnagfgcarcngspgtiak-ktkldlvvtmktc
frlvgksvlitatltatlqhllvr----gpfgvptaktsdrvvpqetapc
akd--cvea--ygrnp------------lmtlnvffglsaspkveafhvn
------tg-sddvcraqggdyfqnatthkacngagpphlfrkslvmhcvr
agsflivfkawgqntpyttp-ffgevrqiaddy-ck-lmtvgeckqk---
----mngpfgqypankvdasneweefgkdhhkkkgtgpilfnlkvawlhg
cvrkileiailghgsltqp-lknkasrpgktsn-nltgkgggsqgvhfqt
csiiaaqplvrkwstl---vkkva-k
>node18
lr-gqnllggsecaltiarl----lgelewykylkvslfy------grpp
apsllkyvsmmpayrasamgdpegalasrevkgetkdarnf-kqqrcvpc
gtmisrlastyylfknygakat---dlv----gfgvcntevgqdkkpagl
yaakkcavdtaknsf--qavcritsltnsgg---r--ci-tagpk----c
qvklktntqvev-rvkctnagfgcarcngspgtiak-ktkldlvvtmktc
frligksvlitatlsatlshllvk----tpfgvptgktshrvlpqetapc
akn--cvea--yerdp------------lmvlngffslsaspkveayhen
------tg-hndvckaqggdyfqnat-hkacngvepphlfrkhvtmhclr
agrflivfkawglntpytdp-ffgevkqladdy-ct-lmtvgeckqk---
----mngpfgqypagnveessdweefgkddhnekgtgpvlfnlkvawlhg
cvhkileiailghgsltep-lkanasrpgktah-nlkgmgggsqgvhfst
csivaeeplirnystl---vkkva-k
>ENV_SIVV1/24-538
lk-avlllggskislsi--llas-tgqsdwykylkgslfy------grqp
apsllkrgglmptyradamge--glvqaceakgeskdadny-kqt-----
-smtsrmaavyyifkklcmkat---qlvdlrqsfgattrets-nfkpagl
gdskryevnsaqqty--qpvckitsllstggqaqr--cl-kavgcvvakc
qiklrdnsqv--lrvkcasaf--ytlceitptgiak-ktklsvivalkvc
fhkitknvvvitr---alpllllrkneitsfqvpsgkkthrvlqhnmagc
gkaakhgda--fargp------------lertdayiktnpdpkmegyqak
aakskksa-hadacgkidgdkfekit-nkacnhsrppelfkkpvvvhclr
hgryvivftawgfd----dmkfftnvnavaeay-crllfrlgkpktk---
----tsapfailpsgkvapsddwddfgsnehdesvcsrvlfslkcawwhg
cvhallesvvleqgtkdvpdvesesakpgktshhdlsggggarqnicfpd
cqqigeds-inkygsl---agkvt-k
>node17
lr-gqnllggsecaltiarl----lgelewykylkvslfy------grpp
apgllkylsmmpayrasamgdpegalasrevkgetkdapnf-lqqrsvpc
gtmisrlastyylyknygakat---dlv----gfgvcntevgqdkkpagl
yaakkcavdtaknsf--qavcritkltnsgg---r--ci-tagpk----c
qvklktntqvev-rvkctnagfgcarcngspgtiak-ktkldlvvtmktc
frligksvlitatlsatlshllvk----tpfgvptgktshrvlpaetapc
akn--cvea--yerkp------------lmvlngffslsaspkvegyhed
------tg-hndvckaqggdyfqnat-hkacngvepphlfrkhvtmhclr
aarflivfkawglstpytdp-ffgevkqladdy-ct-lmtvgeckqk---
----mngpfgqypagnveessdweefgkddhnekgtgpvlfnlkvawlhg
cvhkileiailghgsltep-lkanasrpgktah-nlkgmgggsqgvhfst
csivaiepl----stl---vkkva-r
>node8
lr-aqnllggskctlsi--l----lgqldwykylkgslfy------grpp
apsllkyvglmptyranamgd--gvvrsreakgdtkdadny-kqtrcvvc
gtmtsrmasvyylfkklcmkat---qlv----gfgvttaetsqnfkpagl
adakrcavntaqntf--qsvckitsllssgg---k--ci-taaag----c
qiklkdnaqv--vrvkcasag--carcaatptgiak-ktklsvivamkvc
frkitksvlvitr---alplllvr----tpfgvpsgkkshrvlqqdtapc
gkn--hvda--fargp------------lqrtdtfiklnadpkieayhak
aqksiksg-hsdvcgeiggdyfekit-hkacnkarppqlfkksvvihclr
ggrylivftawgfd----drkfftevdqlaedv-cr-lmkvgepktk---
----msgpfsivqsgnvaessdwddfgsnehnetvcsrvlfnlkcawwhg
cvhalleiaileqgaldvp-iknksarpgktsh-nlpgmggasqgihfpd
ctqvgeep-iskygsl---vqkit-k
>ENV_HV2G1/23-502
lr-gqnllggsecaltiarl----lgelewykylkvslfy------grpp
apsllkyvsmmpayrasamgdpegalasrevkgetkdarnf-kqqrcvpc
gdmisrlsstyylfknycakat---nlv----gfgvcttevgqdkkpagl
yrakkcavdtrknkf--qavcritsltnsgg---r--ci-tagpk----c
qvklkthtqvevvrvkctnagfgcakcngspgtiak-ktkldlvvtmktc
frlignsvligatlsatlshllvk----tpfgvptgktshrvlpqetapc
akd--cvea--yerda------------mmvlngffslsaspkveayhes
------ng-hndvckaqggdyfqnat-ppacngaepphlfrkhvtmhclr
agrflivfkawglntpytdp-ffgevkqladdy-ct-lmtpgdckqk---
----mngpfgqypagnveessdweefgkddhndkgtgpvlfdlkiawlhg
cvhkileiailghgsltep-lknnasapgdaah-nlkgmgrgsqgvhfst
cpivaeeplirnystl---vtkva-k
>ENV_SIVGB/47-569
trktqrllggpkcllsi--l---flpelnwlkylneslfftfridtprsp
carllky-----tyrsqalgd--avgrsrdakaathqsapytkrtraavc
gamaspvasvyylfkrlcirat---qll-----idvtmaantqrfspggl
aeskic------ntytyqsvckfallaskgg---kcpciraapgs----c
tlkprqk--r--sqvncvsyg--cssta---------itsinvpvlshvc
htrmkksllpscr---papalfvs----ssfdrpsar-frrdlr--caac
amh--hvdt--mgrgpgavpdvlrldgslqtadifvrletdatiedqhvk
glnsfrsclhrpvca------fekts-hkvcnkakppqlmkkgvivvclr
tksylivftawgfq------kffnensqlnkklgcr-elkigapssgylk
gdskmvgpftvvdagqvadngdwnvhdekekdnkvcpkdlfnlhca--hg
cvnvlleitnleasvlcvp-imekskrpastsh-klkgkagpkqgapfpa
ctqvgeep-mntygaemrkaqkeakk
>ENV_HV2CA/25-512
lr-gqnllggsecaltiarl----lgelewykylkvslfy------grpp
apglvkylsmmpayaasamgdpegalasrevkgetkdapnf-lqqrnvpc
gsmisrlassyylyknygakat---dlv----glgvcntevgqdkkpagl
yaakkcavdtannsf--qaacritklttsgg---r--ci-tagpk----c
qvklktktqvev-rvkctnagfgcarcngshgaiak-ktkldlvvtrktc
frligksvlitatlsatlshflak----tpfgvptgktshrtlpletapc
arn--cvea--yerkp------------lmvlhgffslsatpkvegyqed
------tg-hndvckaqggsyfqnat-hkacngvepphlfgkhvtmhclr
atrylivfkawalsspytdp-ffgevkqliddy-ct-lmtvakckqk---
----mnvpfgqapagnveecsdweqfgkddhnekatgpvlfnlkvawlng
cvhki-eiailghgsltep-lkanagrpgktah-alkgmgggsqsvnfnt
csivaiepl----srl---vkkvs-r
>ENV_HV2NZ/24-502
lr-gqnllggsecaltiarl----lselewykylkvslfy------grpp
apgllkylammpayrasllldpegalasrevkgetkdapdf-hqqrsvpc
gtmisrlastyylyknygakat---dlv----gfavcntevgqdkkpasl
yaakkcavdtqknsf--qavcritkltnggg---r--ci-tagpk----c
qvklktnaqvev-rvkctnagfgcarcngspgtiakiktkldlvitmksc
frligksvlitatltatlghllvk----tpfgvptgksshrtlpgetapc
akn--cveq--yerkp------------lmvlngffslsatpkvdgyhed
------tg-hndvckaqgsdyfqnat-ekacngvepphlfr--vtmhclr
aarflivfktwglsppytdp-ffgqvrqladdy-ct-lmtvgeckqm---
----mngpfgeypdgnveessdweefgkddhnekgtgpvlfdlkaawlhg
cvhkileiallghgslsep-lkadasrpgktah-nlkgmgggsqgvhfst
csivaiepl----stl---lkkva-r
>node14
lr-gqnllggsecaltiarl----lgelewykylkvslfy------grpp
apsllkyvsmmpayrasamgdpegalasrevkgedrdarnf-kqqrcvpc
gtmisrlastyylfknygakat---dlv----gfgvcntevgqdkkpagl
yaakkcavdtvknsf--qavcritsltnsgg---r--ci-tagpk----c
qvklktntqvev-rvkctnagfgcarcngspgtiak-ktkldlvvtmktc
frligksvlitatlsatlshllvk----tpfgvptgktshrvlpqetapc
akn--cvea--yerdp------------qmvlngffslsaspkveayhen
------tg-hndvckaqggdyfqnat-hkacngvepphlfrkhvtmhclr
agrflivfkawglntpytdp-ffgevkqladdy-ct-lmtvgeckqk---
----mpgpfgqypagnveessdweefgkddhnekgtgpvlfnlkvawlhg
cvhkileiailghgslsep-lkanasrpgktah-nlkgmgggsqgvhfat
caivaeeplirnystl---vkkva-k
>node11
lr-gqnllggsecaltiarl----lgelewykylkvslfy------grpp
apsllkyvsmmpayrasamgdpegalasrevkgetkdarnf-kqqrcvpc
gtmisrlastyylfknycakat---dlv----gfgvcntevgqdkkpagl
yaakkcavdtaknsf--qavcritsltnsgg---r--ci-tagpk----c
qvklktntqvevvrvkctnagfgcarcngspgtiak-ktkldlvvtmktc
frligksvlitatlsatlshllvk----tpfgvptgktshrvlpqetapc
akn--cvea--yerdp------------lmvlngffslsaspkveayhen
------tg-hndvckaqggdyfqnat-hkacngaepphlfrkhvtmhclr
agrflivfkawglntpytdp-ffgevkqladdy-ct-lmtvgeckqk---
----mngpfgqypagnveessdweefgkddhnekgtgpvlfnlkvawlhg
cvhkileiailghgsltep-lknnasrpgktah-nlkgmgggsqgvhfst
csivaeeplirnystl---vkkva-k
>ENV_HV2D1/24-501
lr-gqnllggsecaltiarl----lgelewykfltvslfy------grpp
apsllkyvsmmpayrasamgdpegalaprevkgedrearnf-kqqrcvpc
gtmisrlastyylfknygaaat---dlv----gfgvcntevgqdkkpagl
yaakkctvdtvknsf--eavcrltsltnsgs---r--ci-tagpk----c
qvklktntqvev-kvkctnagfgcarcnggpgtiak-ktkldlvvtmktc
frligksvlitatlsatlshllvk----tpfgaptgktsyrvl----apc
qkh--cvea--yernp------------qmvlngffslsatpkieayhen
------tg-hndvckaqggdyfqnat-hkacngvqfphlfrqhvtmhclr
anrflivfkawglntpytdp-ffgevkqladny-cv-lmtvgeckek---
----vpgpfgqypagnveetsd--efgkedhdekgtgpvlfnlrvawlhg
cvhkileiailghsslsep-lkanasrpgktah-nlkgmgggsqgvhfaa
caivaeeplirnystl---vnkva-k
>ENV_HV2BE/24-510
lr-dqnllgasqcaltiarl----lgelewykylkvslfy------grpp
ppallkyvtmmpayrasamgdpqaalasrdvkgedrdarnf-kqqrcvpc
gamisrlastyylfknygakat---dlv----gfgvcntevgqdkkpsgl
yaakkcavdavknsf--qavcritsltdsgn---r--ci-tagps----c
qvklktntqvev-rvkctnagfgcarcngspgtiak-ktkldllvtmktc
frligksvlitatlsatlshllvk----lpfgvptaktshrvlpqe--pc
akn--cfed--yerdp------------qmvlngffslsaspkveayhen
------tp-hndqckaqggdyfqdat-hkacngvepphlfrkpttmhclr
agrflivfi---lntpytnp-ffgevkqladdy-ct-lmtvgeckqk---
----kpgpfgqypagnveessdweefgkddhnekgtgpvlfnlkvawlhg
cahkileiailghgslsep-lkpnasrpgktdh-nlkgmgggsqgvhfad
caivae--lirnystl---vkkva-k
>node10
lr-gqnllggsecalti--l----lgelewykylkgslfy------grpp
apsllkyvsmmpayrasamgd--galasrevkgetkdarnf-kqqrcvpc
gtmisrmasvyylfknycakat---dlv----gfgvcnaevgqdhkpagl
yaakkcavntaknsf--qavcritsltnsgg---r--ci-tagpk----c
qvklktntqvevvrvkctnagfgcarcngspgtiak-ktkldlvvtmktc
frligksvlitatlsatlshllvr----tpfgvptgktshrvlpqetapc
akn--cvea--ygrdp------------lmvlnvffslsaspkveayhen
------tg-hndvckaqggdyfqnat-hkacngaepphlfrksvtmhclr
agrflivfkawglntpytdp-ffgevkqladdy-ck-lmtvgeckqk---
----mngpfgqypagnvdessdweefgkddhnekgtgpvlfnlkvawlhg
cvhkileiailghgsltqp-lknnasrpgktsh-nltgmgggsqgvhfst
csivaeeplirkystl---vkkva-k
