>node19
evvdahvsfghvpplsfvidtta----------tgshasligv-tctagd
psdl-haeeqdglmkrpvpayqhdvrgfrvgqpkdslnmv----------
kglhrgd-gysnanla-----taa-------kpcnqtaqlkciffftkta
ssfnkasmdmilpstlepgkitlktt--tvtsry--y-vvva-h-ladsk
kdcsvrtakevalllg--kgsskcc-----------kllamhfvspfycf
nelnrtvetvqtksaafvtgaqyggrnrnwhgs---nhd--lmaevvqgs
vskakcllcfietdiefgdeyfelrvaleklcaicgsfnwfppqdskdks
ktdaqeeqgkqmfvtdtvhgpleayweivtsecq-t---lfklkkfihkn
nagnccigws-akcccpiydmysp-fgsfmgtqfigcakiiwkatqgdgv
qcidlk-faavahks---------n-lhn--v-ktaegheknnanklkye
ill---kplt---kqva--ktnsaqdnklstdddlryfgeaylmg--gq-
ewepkrdslknhiah-lhsstrtlkvpgdlgfephkrsnrrg
>ENV_HV2D2/24-513
evaaapvsfghvpptsfvddtta----------tgahvaligv-actagd
pgdl-nseeqdglmkrpvpiyqhdlrgfrvgqpkgsqsmv----------
sgldrgd-gytnanlp-----tat-------rpcnqtaqlkcifffskta
ssfnsstl------nlepgkitlktt--tvtcrf--y-vvvs-h-yadsk
kdcsvrtakdvtllvg--kpssncc-----------kllamhfvspfycf
ndlnktvqtvqtksaafvtgaqyggcdrnwhgsskvnhd--lqaavvqgs
vsknkcllcfietddeygveyfelrvalekrcaicgsfswfppqdskdks
ktdareeqgkqmfatdtvhgpleaywemvtsacq-n---lfklskyihkd
nsgdccigws-akcccpvhdeysp-flsfmgtqfigcgkiiwkathganv
qcidlk-yaavahks---------n-lhn--v-ktaeghektdanklkye
ill---iplt---kqva--ktnsaqdnklstsdglryfgdayvmg--gq-
ryepkrdslkghiah-lhnrtselkvpgdlggephkrsnrrt
>ENV_HV2BE/24-510
evvdtsvsfghvpplsfviettp----------tdahaslvgv-tctegd
psdm-haeeqdglmkrpvpayshdvrgfrvgqpkdslnvv----------
kglhrgt-gysnenla-----taa-------kpcneiaelkciffftkta
ssfnkaalemilpstlepgkitlktt--tvtsky--y-vmva-h-vadsk
kdcsvrtakevklllg--kgtskcc------------llamhfvspfycf
nelnrtvetvqstgaafvtgaqyggrsrhwhgs---nhd--lmaevvrgs
iskakcllcfietdiefgdeyfelrvaleklcaicgsfnwfpaqiskdks
ktdaqdeqgkqmfvtdtvhgpldafweivksecd-s---lfklkkfihkn
aagnccigws-akcccpiydmysp-fgsfmgtqfigcakiefkptqgdgv
qcidlk-faavahks---------n-lhn--v-kaceghdkanakklkye
ill---kpls---kqva--ktnsarddklstdadlqyfgeaylmg--gq-
qweprrdslknhigh-lhsstrtlkvpgdlgfephkhsnrrg
>ENV_HV2CA/25-512
evvdahvsfghvpplsfvidtta----------tgghasligv-tctagd
psdv----epdglmkrpisayqhqvrgfgvvqpkdsldma----------
kglhrgd-gfsnanit-----kaa-------kpcnqtaqlkcqffftkta
safnkasmdmilpttlepgkitlktt--tvtsry--y-vvva-h-lgdsk
kdcsmrtpkevslllg--kgsfkcc-----------kllamnfvvpfycf
nelnrtvetvqtksaafvtgaqfggrnrnwhgs---nhd--lmasvvqgs
vskakcllcfietdvefgdeymqlrvaleklcaicgsfnwfppqdskdks
ktevmeeqgkqmfvagtvhgpleayrecvtsech-t---l---kkfihkn
nagdccigws-akcccpiydmykp-fgsfmglqfigcakiiwkatqgdgv
qcidlk-faavahks---------n-lhn--v-kteegheknnayklkfn
ill---kplt---kqva--tkgsaqdnklstdddlrysgaaylmt--gq-
ewep--dslknhiah-fhsstrtlkvpgdlgfdphkrsnrrg
>node10
evadahvsfghvpplsfvidtta----------tgahasligv-tctagd
psdl-haeeqdglmkrpvpayqhdvrgfrvgqpkdslnmv----------
kglqrgd-gysnanlp-----tat-------rpcnqtaqlkciffftkta
ssfnkatmdmilpstlepgkitlktt--tvtsry--y-vvva-h-ladsk
kdcsvrtakevtlllg--kgsskcc-----------kllamhfvspfycf
nelnktvetvqtksaafvtgaqyggrnrnwhgs---nhd--lmaavvqgs
vskakcllcfietdiefgdeyfelrvaleklcaicgsfnwfppqdskdks
ktdaqeeqgkqmfvtdtvhgpleaywemvtsecq-t---lfklkkyihkn
nagnccigws-akcccpiydmysp-fgsfmgtqfigcakiiwkathgdgv
qcidlk-faavahks---------n-lhn--v-ktaegheknnanklkye
ill---kplt---kqva--ktnsaqdnklstdddlryfgeaylmg--gq-
ewepkrdslkghiah-lhnrtrtlkvpgdlgfephkrsnrrg
>ENV_SIVGB/47-569
vsagphdsfghlgplsfvlaitlrnpcslngviiakdcklcgvdactad-
-spl-pygdedg-lkralalylld-kgfrlda--------fhrrckhc-q
tvmkhg--g--sqglptgaklt------rlvrpshadailpcgfffqsta
tsfsrttae----sslsspdislkaafk--vgrf--ysrvea-k-ltldq
ndskvgca-dvtllirdkkgcghcs-----------evlsnnlvgpylcf
ktfgqvphdqatrgtayvvpaeyagaseaiiks---stestvmpa-vpap
i--akcvkclideglefgndlyellaaipk-------iylfppvdgtska
ispssrpqskvtfgvktdpspihefwaivksnca-vamalfrlrkyadcn
anprgciawarakcccaffdrstp-fnaflg-rfttcskiiwkgedgdgv
acvnlk-fet-vregkvynaltti----a--tlktaagheetyahklste
ive---gpla---keiv--rdfag-dkdittnldlrflidgfimgapqq-
e------------srdlndkttslktpe--amipfkkpkrrg
>node7
etaephdsfghlpplslvvdvtl----------tgkhtglvgi-tctan-
-sel-pyseqdglkkrpfslylievq---------alkfmyhrkchnc-n
rg---gd-gyanaalptganltddrahlrlvrpsataaqlkcdfffqkta
ssfskttmd----tslspvnialktt--tvtsry--y-tvvp-a-laneq
kncgvrsa-hvtllva--kgcgrcc-----------kllaehftgpficf
nqltqmgesvhakgksyisaaqytgrtkathas---daedtmmta-vtgs
vckpkcllsfiqkslefadeffelrvalpklctvcgsfnwfppiagksks
kacanqeesklmfvvdtgqgpihafwelvtsacqlv---lfqlrkyahkn
tggrccigws-akccctlfdkytpifgtffdthlitcakivfkashgngv
qcigfk-fgtvahag---------n-lhs--ilktvqaheknntsslsee
ill---kala---rqih--rtngg-dkklstnvdlrffaeaylmg--gp-
er------lngyiar-lhnktrtlkvpe--gykpfkrpsrrg
>node17
evvdahvsfghvpplsfvidtta----------tgshasligv-tctagd
psdl-haeeedglmkrpvpayqhdvrgfgvvqpkdslnmv----------
kglhrgd-gysnanlt-----kaa-------kpcnqtaqlkciffftkta
ssfnkasmdmilpstlepgkitlktt--tvtsry--y-vvva-h-ladsk
kdcsvrtakevalllg--kgsfkcc-----------kllamhfvspfycf
nelnrtvetvqtksaafvtgaqfggrnrnwhgs---nhd--lmasvvqgs
vskakcllcfietdiefgdeyfelrvaleklcaicgsfnwfppqdskdks
ktdameeqgkqmfvtdtvhgpleayweivtsecq-t---lfklkkfihkn
nagnccigws-akcccpiydmysp-fgsfmglqfigcakiiwkatqgdgv
qcidlk-faavahks---------n-lhn--v-ktaegheknnanklkfe
ill---kplt---kqva--ktgsaqdnklstdddlryfgeaylmg--gq-
ewepkrdslknhiah-fhsstrtlkvpgdlgfephkrsnrrg
>ENV_SIVV1/24-538
evaqphdsfnhlpplslvvdatl----------ngkhtglvgi-tcsad-
-sel-pysqqdglnkrpfslylievq---------shkfmyhrkchsc-n
ga---galgyanaalptganltdekshlalvrpsataaqlkcnfffqnta
stmshitmd----tnlspvnintktt--tatsry--y-tvvp-aalaneq
kncgvrsa-hvtllva--kgcgrcc-----------kllsehftgpfici
aqlsqlnekvvakgkseisasqytgrtkathas---daedtmlta-vtgs
vckgkcllsfyqkslefaanffe-rvalpklctacasfnwfppiagksks
kacanqeekknmfvvdtgqapihafwelltsacplv---lfqlqkfahkq
tggrscigws-akccctlfdkytprfgaffdthlitcatvvnkaehgngv
qcigfn-fgavthag---------nllha--ilktvqahekkrtsslsee
ill---ksll---rqih--rthgg-dkklsvnvelkffteaylma--gp-
er------ltg---r-lhnktralkvpe--gykpfkrltrrg
>ENV_HV2NZ/24-502
evvdasqsfghvpplsfvidtta----------tgshagligv-tctagd
psdlpheeeedslmkrpvaayqhdvrgfgvvqpkdslnmv----------
kglnrgd-gysnanlt-----kav-------kpcnptaqlkciffftsta
ssfnkasmdmilpstiepgkitlktt--tvtsry--f-aivarh-ladgk
kdcgvrtakevallla--kgsfkccqevnrdlaadakllamhfvspffcf
nelnrsvenvqtksaafvtgsqfggrsrnwqgs---nhd--lmasvvqgs
vrkakcllcfietdiefgeeyfelrvalaklcaicgsfnwappqdskdka
kteameeqgsqmfvtdsvhgpleayweivtsecq-t---lfklkkfihkt
nagncyigws-akccspiydmysp-fgsfmglqfkgcakiiwkgtqgdgv
ncidlk-faavahkt---------n-ly---v-ksasghqknnanklkfe
i-livmkslt---kqvacgkkgtsqdnklstdedlryfasaylmg--gtn
ewepkrdslkssiah-fhsstrtlkvpgdlgfephkrsnkrg
>ENV_HV2G1/23-502
evidahvsfghlppisfvidtta----------tgshasligv-tctagd
psdl-haeeqeglmkrpvpayqhdvrgfrvgqpkdslnmv----------
kglhrgd-gysnanla-----taa-------kpcnqtaqlkciffftkts
tsfnkatmdmilpstlepgkitlntt--tvtsry--y-vvva-h-ladsk
kdcsvrtakevalllg--kgsskcc-----------kllamhfvspfycf
nplnrtvetvqtksaafvtgaqyggrnrnwhgs---nhd--lmaevvqgs
vtkamcllcfietdiefgdeyfelrvaleklcaiygsfnwfppqdskdks
ktdaqedqgkqmfvpdtvhgaleayweivtsech-t---lfklkkyihkn
nagnccigws-kkcccpiydmysp-fgsflgtqfigcakiiwkatqgdgv
qcidlk-faavahkp---------n-lhn--a-ktaegheknnanklkne
ill---krla---keia--ktssaqdnklstdddlryfgeaylmg--gq-
ewepkrdslknhiah-lhsstrtlkvpgdlgfephkrsnrrg
>node11
evvdahvsfghvpplsfvidtta----------tgshasligv-tctagd
psdl-haeeqdglmkrpvpayqhdvrgfrvgqpkdslnmv----------
kglhrgd-gysnanla-----taa-------kpcnqtaqlkciffftkta
ssfnkatmdmilpstlepgkitlktt--tvtsry--y-vvva-h-ladsk
kdcsvrtakevalllg--kgsskcc-----------kllamhfvspfycf
nelnrtvetvqtksaafvtgaqyggrnrnwhgs---nhd--lmaevvqgs
vskakcllcfietdiefgdeyfelrvaleklcaicgsfnwfppqdskdks
ktdaqeeqgkqmfvtdtvhgpleayweivtsecq-t---lfklkkyihkn
nagnccigws-akcccpiydmysp-fgsfmgtqfigcakiiwkatqgdgv
qcidlk-faavahks---------n-lhn--v-ktaegheknnanklkye
ill---kplt---kqva--ktnsaqdnklstdddlryfgeaylmg--gq-
ewepkrdslknhiah-lhsstrtlkvpgdlgfephkrsnrrg
>node14
evvdahvsfghvpplsfvidtta----------tgshasligv-tctagd
psdl-haeeqdglmkrpvpayqhdvrgfrvgqpkdslnmv----------
kglhrgd-gysnanla-----taa-------kpcnetaqlkciffftkta
ssfnkasldmilpatlepgkitlktt--tvtsry--y-vvva-h-vadsk
kdcsvrtakevalllg--kgsskcc-----------kllamhfvspfycf
nelnrtvetvqsksaafvtgaqyggrnrnwhgs---nhd--lmaevvqgs
iskakcllcfietdiefgdeyfelrvaleklcaicgsfnwfppqdskdks
ktdaqeeqgkqmfvtdtvhgpleayweivtsece-t---lfklkkfihkn
aagnccigws-akcccpiydmysp-fgsfmgtqfigcakiiwkatqgdgv
qcidlk-faavahks---------n-lhn--v-kaaegheknnanklkye
ill---kplt---kqva--ktnsaqdnklstdddlryfgeaylmg--gq-
ewepkrdslknhigh-lhsstrtlkvpgdlgfephkrsnrrg
>node9
eaadphesfghvpplsfvidita----------tgahasligv-tctagd
psdl-hfeeqdglmkrpvpaylhevrgfrvgqpkdslnmvfhrk---ckn
kglqrgd-gysnanlpsgvkltat-------rpcnqtaqlkcaffftkta
ssfnkgtmd----stlepgkitlktt--tvtsry--y-vvva-h-ladsk
kdcgvrtakevtllvg--kgsskcc-----------kllamhfvspfycf
neltktgetvhtksaafvtgaqyggrnkswhgs---nhddtlmaavvqgs
vskakcllcfietdiefgdeyfelrvalpklctvcgsfnwfppqdskdks
ktdaqeeqgkqmfvtdtvhgpleaywemvtsacq-t---lfqlkkyihkn
naghccigws-akcccpiydmysp-fgsffgtqfitcakiiwkathgdgv
qcidlk-faavahks---------n-lhn--v-ktvegheknnanklkye
lll---kplt---kqva--ktnsaednklstdddlryfgeaylmg--gq-
ewepkrdslkgyiah-lhnrtqtlkvpgdlgfepykrpnrrg
>ENV_SIVM1/24-528
eaadphesfghvpplsfvidi-------------gahatligi-tctagd
psdl-nheeqdgltkrpvavylhegrgfrvgqpknstnmvfhrk---ckn
ksiqrgd-gysnanlpsgvkltat-------rpcnqtlqlkcaffftkta
ssfnkgvmd----ntlepgkitlkit--kvtsry--y-vvva-h-ladsk
kdcgvrtakevtllvm--kgsskcc-----------nllamhfvspfycf
n--qktgetahtksaafvtsaqyksrfkslhgs---hhddtlmvavvqgs
vskakcllcfietdiefmdeyfelrvalpklitvcgsfnwfppqdskdks
kadameeqskqmfvtdtvhgplaanwkmvtsacq-t---lfqlrrylnkn
naghccigws-skcccpiydmysp-ygsffgtqfitcakiiwkathgdgt
tcidlk-fadvahks---------n-lhnqpv-kttegheknnanklhye
lll---kplt---kqvd--ktnsaddnklstdedlryfg-aylmg--ge-
ewepkrdslkgyiah-lhirtqtlkvpgdlgfepykrpnirg
>node8
etadphdsfghlpplsfvvditl----------sgkhtglvgi-tctan-
-sel-pyseqdglmkrpfslylievkgfrvgqpkdalkfmyhrkchnc-n
rglrlgd-gyenaalptgtkltddrahlrlvrpsataaqlkcgfffqkta
ssfskttmd----tslspvnialktt--tvtsry--y-ivvs-a-laneq
kncgvrsa-evtllva--kgcgrcc-----------kllaehfvspfvcf
nqltqmgesvhtkgtayvsaaqyagrtkathas---daedtmmta-vtgs
vckpkcllcfiqkslefgdeffelrvalpklctvcgsfnwfppidgksks
ktpanqeeskqmfvvdtvqgpihafwelvtsacq-v---lfqlrkyahkn
tagrccigws-akcccslfdkytp-fgtffgthfitcakivwkashgdgv
qciglk-fgtvahag---------n-lhs--ilktvegheknntsslsee
ill---kpla---kqia--rtnsg-dkklstnidlrffaeaylmg--gq-
er------lngyiar-lhnrtrtlkvpe--gykpfkrpnrrg
>ENV_SIVG1/22-522
etaephdsfghlpplslvidvtl----------tgkhtghvgi-tctan-
-nel-pyseqdglkkrpfsl----vq---------alrfmyhrkchnc-n
sg---gd-gyanaalptganltddrahlrlvrpsataahikcdfffqkea
hsyskttmd----tsltpvdialkat--tvtsry--y-tvvp-a-landq
kncgvrsa-qvtllva--kgcgrcc-----------kllaehfrnpfmcf
nq-tqigesvhgkgkayisaaqysgrtkathas---daedtmmta-vtgt
vckprcllsfiqkslefad-ffelrvalpklctacgsfnwfppiagksks
kacakkgeskllfvvdtgqgpihdfwelvtsacelv---lfqlrkyahkn
tggrcciews-akccctlfdkytpifgtffnahlitcakivfkaahgngi
qcfgfslfgtvahag---------n-lhs--ilktvqaheknatsslsee
ill---kala---hqih--rtkgg-dkklstnvdlrffaeaclmg--gp-
dr------lsgyvtr-lhnktrtlkvpe--gykpfkrasrrg
>ENV_HV2D1/24-501
evvdahisfghvpplsfvidtta----------tgshaslvgt-tctvgd
psdl-hadeqdglmkrpvpayqhdvrgfrvgqpkdslnmv----------
kglhrgd-gysnania-----taa-------kkcnetaqlkciffftkta
stfnkasldmilpatlepgkislktt--tvisrytty-vvla-h-vadvk
kdcsvrtaqevalllg--kgsskcc-----------rllamhfvspfycf
nelnrtvetvqsksaafvtgaqyggrnrnwhgs---nhd--lmaevlqgg
iskakcllcfietdiefgdeyfelrvalekvcaicgsfnwfppqdskdks
ktpaqeehgkqmfvtdtvhgpleayweivtsece-t---lfklkkfihkn
aagkccigwt-akcccpiydmysp-fgsfvgtqfigcakiiwkatqgdgv
qcfdlk-faavahks---------n-lhn--l-saaegheknnanklkye
ill---kpltqslkhva--ktnsaqdnklstddelryfgeaylvg--gq-
ewepkrdslknhigh-lhsstrtlkvpgdlgfdphkrsqrkg
>node18
evvdahvsfghvpplsfvidtta----------tgshasligv-tctagd
psdl-haeeqdglmkrpvpayqhdvrgfrvgqpkdslnmv----------
kglhrgd-gysnanla-----taa-------kpcnqtaqlkciffftkta
ssfnkasmdmilpstlepgkitlktt--tvtsry--y-vvva-h-ladsk
kdcsvrtakevalllg--kgsskcc-----------kllamhfvspfycf
nelnrtvetvqtksaafvtgaqyggrnrnwhgs---nhd--lmaevvqgs
vskakcllcfietdiefgdeyfelrvaleklcaicgsfnwfppqdskdks
ktdaqeeqgkqmfvtdtvhgpleayweivtsecq-t---lfklkkfihkn
nagnccigws-akcccpiydmysp-fgsfmgtqfigcakiiwkatqgdgv
qcidlk-faavahks---------n-lhn--v-ktaegheknnanklkye
ill---kplt---kqva--ktnsaqdnklstdddlryfgeaylmg--gq-
ewepkrdslknhiah-lhsstrtlkvpgdlgfephkrsnrrg
