>ENV_SIVG1/22-522
sskasleheqgevakvpplitnydsariprlrnvle--lqleasnvtvmk
aktfnpnsnl-lscvnlnkiyifgrrgkmhksvsdekvgtkkfhpqevcf
eyigs-kgddnskdpfyaavqpvtndcqgfginkkqapptydlgeawggv
lvkcahaamiqknelaalnvrrggerpvaknagtgtkcghlaravklgaq
cdhviawa-i-hklatseemgtkvackggvdyhghhptcdfk----fgii
amgt--alekanely--qvlegnpestacssrlekvelhirkcfvfkesm
akanylkk-tgaychtdesfsgl---erlsadsltfplldqeptkklpte
whlpnsrncnnvqhttsagdlqtsvfsvfelrhv---lvtlskdelavln
-----lstrckrggegkdk--kaqp--tskdhsaaefkhtlsvtisfvra
--skagywk-ypggvldifeakvglgldyneeqv-akqshes--lgf--r
sdrpgttn-------ytdlipmtgkfsdsrdgdtyhfhfsqyiskfi
>ENV_SIVGB/47-569
svrssleaeqgevsksppavnngdggkgqrirtvte--lelaeatvsvqr
akvlspdkgtdtacinltkvyifsqkgtaangvqdddggskfrkhpevaf
tyvrs-igqelttevfyagvqpeg------gikrkpavasfdlsdawytl
lvtcihral--kd-------lqgnemsvkkatnsgltcgc----vavkeq
cehiiawl-a-hklats------ltckggvhyrstqpfcdfgdgfdfgie
tlgtvralhqashvy---viqsn---leceaplek--------------a
msskylkp-aaslcqfqegfscf---ekltcgrknfplvpndpptalasg
whlpdarksntvdipkkvsttss--------------fttltkdekails
gk--dlshsckqnglghvi--keqptptgk--ksaefmhkfaivvtyvsa
--crygywk-ymgrvldifgqtcgkv----iisvtadqehaslalqy--s
ndrpfknnarapqgpftplipsggefanrkdddkyhipgdqyvskfv
>node7
ssrasleheqgevakvpplinnedsgkvprlrtvle--lqlaasnvtvmk
aktfnphsgl-lscvnlnkvyifgrrgkmhksvsdekvgtkkfhpqevcf
eyvgs-kgddnskdpfyagvqpvtndcqgfginkkqapptydlgeawggv
lvkcahaamlqknelaalnvrrggerpvakgagtgttcghlar-vklgaq
cdhiiawi-i-hklatsqemgtkvackggvdyhghhptcefk----fgii
amgt--alekakely--qvlegnpestacserlekvelrirkcfvfkesa
akahylkk-tgaychtdesfsgf---erlsggsltfplldneptkklpte
whlpnarncnnvqhtssagalqtsvfsvfelrhv---litlskdemavln
gk--slstrckrggegkdm--kaqp--tskdhssaefkhtlsvtvsfvra
--skagywk-ymggvldifeakcglgldynevqv-akqshes--lgf--r
sdrpgttn-------ytelipmtgkfsdsrdghtyhfhfsqyiskfi
>ENV_SIVV1/24-538
fsrasleheqgelakvpplinnedsgkvirirtvle--lqlaasnvtvak
akklnrhsgl-lscanlnkvyifgrrgkmhksvsaeslgtkkfhsqtvcf
eyvgs-kgg-----pfyvgvqpvtsdcqgfginkkqnsptydlgaawggv
lvkcahaamlqdnelfaldvkrggersvtkgcgsgttc-------klfaq
cahnvawi-i-hkmatgqqmgtkvackggvnyhghqptcdfk----fkti
smgt--alekakely--qvlegnpesttcseklakvelkirkcfvfkesa
akahflka-tgay-htdesfssf---eklsggsltfpllddeptrkletq
whlpngrncnnvqptssagalsaskfivfelrhv---litlgkeemavln
gk--snstrskrggegkem--ksqp--ttkdhtsaefkhtlavkvsfvrs
--skagywk-ymggghdifeskcglgldyaevqv-a--shds--lnf--s
sdrpgttn-------ytelipmtgkfsdsrdghtfhfhfsqalskfi
>node17
ssrvalenelghvsyvpplvnnedvgkvyrlktileltmqlaa---avvk
tktlkahrkf-lscvk--------rhaklhytesnnkrgtkkfyaqevgi
eyigs-knddesgdqfyagvqqdsndesgfgistkqappnfalgegwktl
lvrcghganmqkeelaglkvrkggerpvpkeagtgm---hlaa-vmlgae
cahviawa-k-iklstsadtgakaackggvdynfhqpqchfn----fgie
evgt--apnkatelf--lvleeq-egap-eerlekmvlrirkcfmfkqsa
vkthylnntsvvychknqsfsgn---eklsggsltfplvenepikkmpte
whlpnarnddsvnriggtgklqinvfivyqlrnhlttlitvtkgdmavlk
sd--nlsiscklagegqdmvgeaqpthtskdpgskpyknslsvtasfara
--prvgyrksymggvleifedkcglgldygqvevkakqshqt--lkf--r
tdrpsstn-------ysplipmigeigdtpdettfhllfseyvgkfm
>ENV_HV2BE/24-510
ssrvalenelghvgyvpplvnnedvgkvyrlktileltmqlaa---alvk
tktlkthrkf-lvcvk--------rhaklhvtssnskrntkefypqvvgi
eyags-kndaessdpfyagvqqesddqtgfgiptkqapanfalgegwkll
larcghganmqkdelaglkvrkggerpvpkeagtgm---hlaa-vvlgae
cahvlawa-k-iklsasadtgakaacrggvdynfhqpqchfn----ykie
elsv--asnkltnlf--lvleeq-egap-eerlekpvlrlrkcfmfkqsa
vkthylnnesvvycqknqsfsgk---enlsggsltfplvenepikkmhte
whlpnarkddsvsrvgptgllqidvfivyqlrnhlttlitvtkgdmavlk
sd--nlsrncklagegqamvgqaqtthaskdpggkpyknslsvtasfara
--prigyrksylggvlaifedrcgfgldygqvevkakqthqt--lkf--r
sdrpsntn-------ystlipmiggvgdtpkettfhllfseyvgklm
>node10
ssraalenelghvsyvpplvnnedvgkvfrlktileltmqlaa---avvk
tktlkahrkf-lscve--------rhaklhyttsnnkrgtkkfyaqevgf
eyigs-knddesgdpfyagvqqdsndesgfgistkqappnfdlgeawksl
lvrcghganmqkeelaglkvrkggerpvpkeagtgm---hlaa-vmlgae
cahviawi-k-iklstsadtggkaackggvdynfhqpqchfn----fgie
evgt--apnkasely--lvleeqsegap-eerlekmvlrirkcfmfkqsa
vkahylnntsvvychtnqsfsgn---eklsggsltfplvdnepikkmpte
whlpnarnedsvnriggtgtlqinvfivfqlrnhlttlitmtkgdmavlk
sd--nlstscklagegqdmvgeaqpthtskdpgskpyknslsvtasfara
--prvgyrksymggvleifedkcglgldygqvevkakqshqt--lkf--r
sdrpsstn-------ysplipmigeigdtpdestfhllfseyvgkfm
>ENV_HV2D2/24-513
ssratleneqdhvsyvgslv--eaggkvfrlktileltmslaa---svvk
tktlkahrqf-lscve--------rhaklhytkgnnirgtqkfyaqpvaf
eyigslkndtesgapfyadvqqdsneesgfaiktkqappkfdlgeawksi
llrcgegatmqkeeltglkvrkggempvpkeagtpm---hlaa-vmlaae
cahviawi-k-vklstsadtggkaackggvdynfhqpqchfn----fgie
etgt--apkkgselyvhlvlkeqsegtp-eerlekmvlrirkcfmfaksa
vrahylhftgvvychtdqsfsgnctiekvsggtltfplvdndpikkmstt
whlpdardkdsvnrlggtgtlqinvfivfqvrnhlttlitmtkgdmsvlk
skqsnlstscklagdgqdmvgeahpthtskdpgskpyknslsvtksfara
--prvgyrksymggtleiyedkcglgldygqvevkanqshqt--lkftrr
sdqpsstn-------ysplipligeigetpdsstfhllfseyvgtft
>node11
ssrvalenelghvsyvpplvnnedvgkvyrlktileltmqlaa---avvk
tktlkahrkf-lscvk--------rhaklhytssnnkrgtkkfyaqevgi
eyigs-knddesgdpfyagvqqdsndesgfgistkqappnfdlgegwktl
lvrcghganmqkeelaglkvrkggerpvpkeagtgm---hlaa-vmlgae
cahviawa-k-iklstsadtggkaackggvdynfhqpqchfn----fgie
evgt--apnkatelf--lvleeq-egap-eerlekmvlrirkcfmfkqsa
vkthylnntsvvychknqsfsgn---eklsggsltfplvenepikkmpte
whlpnarnddsvnriggtgklqinvfivyqlrnhlttlitvtkgdmavlk
sd--nlsiscklagegqdmvgeaqpthtskdpgskpyknslsvtasfara
--prvgyrksymggvleifedkcglgldygqvevkakqshqt--lkf--r
sdrpsstn-------ysplipmigeigdtpdettfhllfseyvgkfm
>node19
ssrvalenelghvsyvpplvnnedvgkvyrlktileltmqlaa---avvk
tktlkahrkf-lscvk--------rhaklhytssnnkrgtkkfyaqevgi
eyigs-knddesgdpfyagvqqdsndesgfgistkqappnfdlgegwktl
lvrcghganmqkeelaglkvrkggerpvpkeagtgm---hlaa-vmlgae
cahviawa-k-iklstsadtggkaackggvdynfhqpqchfn----fgie
evgt--apnkatelf--lvleeq-egap-eerlekmvlrirkcfmfkqsa
vkthylnntsvvychknqsfsgn---eklsggsltfplvenepikkmpte
whlpnarnddsvnriggtgklqinvfivyqlrnhlttlitvtkgdmavlk
sd--nlsiscklagegqdmvgeaqpthtskdpgskpyknslsvtasfara
--prvgyrksymggvleifedkcglgldygqvevkakqshqt--lkf--r
sdrpsstn-------ysplipmigeigdtpdettfhllfseyvgkfm
>ENV_HV2CA/25-512
ssrvalenelghvsyvpplvnnedvgkayrlktileltmqlaa---avvk
trtldahqkf-vecvk--------rhaqlhitesnkkrgtkkfyaqkvgi
eylgh-knddesadhfyagvqqdsndesgfgistkdappnfalgegwktl
lvrcghganmhkeelaglkvrkggewpvpreagtgm---hlas-vmlgad
cahviawa-k-iklstsaitgakaackggveynfhqpecnfn----fgie
evgt--apnkatelf--lvmeeq-qgap-eerleklvlrirkcfmikqga
vkthylnntsvvychknqsfagn---ekltggsltfplvenepikkmpte
whlpnarnddwvnrigatgklqinvfivyelrnhlttlitvtkgdmpvlk
es--tasiscklageghdmvgea------kdpgskpyknslsvtagfara
--prqgyrksymggvleifedkcglgldyg-idvkak-swqt--lkf--v
t-rpsstn-------ysplipmigeigdtpdet---llfseyvgkfm
>ENV_HV2D1/24-501
ssrvalenelghvsyvppvvnnedvgkvyrlktileltmqlaa---avvk
tktlkahrkf-lscvk--------rhaklhytssnnkrgtkkfyaqetgi
eyigs-knddksgdpsyaevqqdnndesgfgittkqapanfalgegsktl
lvrcghgaavqkdelaglkvrkggeravpkeagtgg---hlaa-illgse
cahviawa-kkiklsksadtgaktacrggvdynfhqpqchfn----ygle
evgd--apnkatelf--lvleeq-egap-eerlekmvlrtrkcfmfkqsa
vkthylnnesvvychktqsfsgk---eklgggsltfplvedepikkvhte
wnlpnarnddavnrvgvtgklqinvfivyqlrnhlttlitvtkgdmtvlk
sd--nlskscklagegqdmvgegrithiskdpgtkpyksslsvtesfara
--prvgcrksymggvleifedkcglgldygqvevkakqthat--lkf--c
sdkpssln-------yaplipmigeigetpeettfhllfgiyvgkfm
>ENV_HV2NZ/24-502
sshvalenelghasfvpplvdnidigkvyrlktileltmqlaa---avvk
tktlkaqrkf-lscvt--------rnsklhytesnnkrgtkkfyaqevgi
dyigs-kdddesgdqfyagvqqdsddesgfgistkqappnfalgegwktl
lvrcnhganmqkeeiaglkvrkggerpvpkehgtgf---hlga-vmlaae
cahaiawa-e-iklstsmdtgakaackggvdynfhqpqchfn----fgie
eagt--apnkatelf--lvleeq-qgaa-derlekmvirkkkcfmfkqsa
vktnylnntsvvychknesfsgn---eklsggsltfplvendpikkmpte
whlpnarnddsvnkiggtgklqisvfivyqlsnhlvtvitvtkgdmavlk
sd--nlglssklagegqdmvaesqpthtskdpgtkpyknnlsvtasfaha
--prvgykksymggvlemfedkcglglnygdvelkakqrhqt--lkt--r
tdrpsstn-------ysplipkigeigdtpdettfhllfseyvgkfm
>node18
ssrvalenelghvsyvpplvnnedvgkvyrlktileltmqlaa---avvk
tktlkahrkf-lscvk--------rhaklhytssnnkrgtkkfyaqevgi
eyigs-knddesgdpfyagvqqdsndesgfgistkqappnfalgegwktl
lvrcghganmqkeelaglkvrkggerpvpkeagtgm---hlaa-vmlgae
cahviawa-k-iklstsadtgakaackggvdynfhqpqchfn----fgie
evgt--apnkatelf--lvleeq-egap-eerlekmvlrirkcfmfkqsa
vkthylnntsvvychknqsfsgn---eklsggsltfplvenepikkmpte
whlpnarnddsvnriggtgklqinvfivyqlrnhlttlitvtkgdmavlk
sd--nlsiscklagegqdmvgeaqpthtskdpgskpyknslsvtasfara
--prvgyrksymggvleifedkcglgldygqvevkakqshqt--lkf--r
sdrpsstn-------ysplipmigeigdtpdettfhllfseyvgkfm
>node9
ssraslenelghvskvpplvnnedvgkvfrlktileltmqlaaasvavvk
tktlkahrkf-lscve--------rhaklhntvsnnkrgtkkfyaqevgf
eyigs-knddetgdpfyagvqqdsnddsgfgistkqappnfdlgeawkgl
lvrcghganmqkeelaglkvrkggerpvpkeagtgm---hlaa-vmlgae
cahviawi-k-iklstsadtggkaackggvdynfhqpqchfn----fgie
evgt--apnkasely--lvleeqaegat-eerlekmvlrirkcflfketa
ikahylkntsvvychtnqsfsgn---erlsggsltfplvdnepikkmpte
whlpnarnednvsriggtgtlqinvfrvfqlrnhlttlitmtkgdmavlk
sk--nlstscklagegqdmvgeaqpthtskdpgskpykhslsvtasfara
--prvgyrksymggvleifedkcglgldygqvqvkakqshqt--lkf--r
sdrpsttn-------ysplipmigefgdtpdentfhlnfseyvgkfm
>ENV_HV2G1/23-502
ssrvalenelghvcyvpplvnnedlgkvyrlktileltmqlaa---avvk
tktlkahrkf-lscvk--------rhaklhytssqnkrgtnkfyaqevgi
eyigs-keddessdpfyagvqhdsndesgfgistkqeppnfdlgegwktl
lvrcghganmqkeelaglkvrkgaerpvpkeagtgm---hlaa-vmlgae
cahviawvvk-iklsasadtggkaackggvdynfhqpqchfn----fgve
evgt--apnkatelf--yvleeq-egtp-earfekmelrirkcfmfkqsa
vkthypnatavvychknqnfsgs---eklsggeltfplvenepikkmptd
whlpnarnedsvnriggsgklqinvfivyqlrnhlttlitvtkgnmavlk
sd--nlsiscklagkgqdmigeeqpthtskdpgskpyknslsvtasfara
--prvgyrksymggvleifedkcglgldygqvevkatqshqt--lkf--r
sdrpsstn-------ysplipmigeigdtpdettfhllfseyvgkfm
>node8
ssrasleheqgevakvpplvnneeggkvprlrtvle--lqlaasnvtvmk
aktfnphsgl-lscvdlkkvyifgrrgkmhnsvsdektgtkkfhpqevaf
eyvgs-kgddnsndpfyagvqpitndcqgfginkkqapptydlgeawggl
lvkcahaamlqkeelaalnvrrggerpvakgagtgttcghlar-vklgaq
cahiiawi-i-hklatsqemgtkaackggvdynghhptcefk----fgie
avgt--alekakely--lvlegnpegtaceerlekvelrirkcfvykesa
akahylkk-taaychtdqsfsgf---erlsggsltfplvdneptkklpte
whlpnarnsnnvshissagtlqtsvfsvfelrhv---litmskdemavlk
gk--slstsckqagegqnm--kaqptptgkdpssaefkhtlsvtvsfvra
--skagywk-ymggvleifeakcglgldynqvqvqakqshes--lgf--r
sdrpsttn-------ytplipmtgefsdsrdghtfhfnfsqyiskfi
>node14
ssrvalenelghvsyvpplvnnedvgkvyrlktileltmqlaa---avvk
tktlkahrkf-lscvk--------rhaklhytssnnkrgtkkfyaqevgi
eyigs-knddesgdpfyagvqqdsndesgfgistkqapanfalgegwktl
lvrcghganmqkdelaglkvrkggerpvpkeagtgm---hlaa-vmlgae
cahviawa-k-iklstsadtgakaacrggvdynfhqpqchfn----ygie
evgt--apnkatelf--lvleeq-egap-eerlekmvlrirkcfmfkqsa
vkthylnnesvvychknqsfsgk---eklsggsltfplvenepikkmhte
whlpnarnddsvnrvgvtgklqinvfivyqlrnhlttlitvtkgdmavlk
sd--nlskscklagegqdmvgeaqtthtskdpgskpyknslsvtasfara
--prvgyrksymggvleifedkcglgldygqvevkakqthqt--lkf--r
sdrpsstn-------ysplipmigeigdtpeettfhllfseyvgkfm
>ENV_SIVM1/24-528
sarasleneaghvskvpplvnpeevekvfrlktvleltmelaaisvaivk
tktlkanrkf-lscve--------r--klhgtvsnnkkgtkkfyaqev--
--igt-knhdetgdpfyagvqqdgnddsgfgistkqapsnfklgqawkgl
lvrcghtahlqkeelaglkvrkggerpvvseagsgm---hlaa-vllgae
cahviawi-k-iklstsadtggkaackggvpynfhqpqcffd----fgie
evgt--apnkasely--lvleeqaegat-eerlekmtlrirkcflfketa
ikahylkntsvvychtnqkfsgn---erla----tfplgnnspikkmpte
whlpnaraednvsriggtgtlhknvfrvfqlrnhldtlitmtkggmavlk
sk--glstsckltgegedmvgeaqpthtskdpgskpykhslsvtagfara
viprvgyrksymsgvleifedkcglgldc-----kakqshqs--lkf--r
tdrpstsn-------ysplrpmigef-----enkfhlnfseyvgmym
