>ENV_SIVV1/24-538
gltvpgtsls-ftgpdhnkih------ytifgpletvtp-c-vnqgsggy
gnsqgc-leilggsycrpsgfiirttyvrgecspnrg----as-pqsdnh
asdgdlfavtafvslwrlea-----dhlhgdfg-----------pr----
-mhnqv--knnrrgqgsldllcsqlqlmaesf-------ivcllgiksat
aawrlsgdvddlkapkdpsawekgsfcvst--psligrlnepscagqlpg
pn----s-magvanaialp--aaigsmpedlqyctralvsqlnddnept-
-gmrdnsvsscped--vafagpkltgetvtdwaeggykskkclykppqma
----tkhakk--mydvaalgnqpkg-qkvl---aeshrla----lkpcvn
lgfryamaf-y-krslciatiaeayllkriflrnqtwaktrywkqssnk-
-elikt--s--dc-kcpanvgrnvldtgiprvgvcgntkflaasigskvg
vadelmgtdgvt----thftt---vdkapdeflldk---ninsvlcwkrs
ldntinkvepkkedhltkvfvvtavkhk---------a-----venvghe
krffpekgksipfyg
>node8
gltvpgtslsff---nhkkih------ysifgpletvtp-c-vn---ggy
gnstgc-lealggsycrlsgfiirttylrgacapsrg----as-pqddnq
ssegnlfentafvslwrldd-----dhlhgdfg-----------pk----
-mhnqv--khkrrgqgsldllcgqirlmaedf-------lvcllnikset
aawrlsgdidalkvpkkpg---kgsfcvst--ps-igrlkipscagqepg
pn----t-mggvanasalp--aaigslpndlhfctralvkqlhqnneatr
femkdssvsscpdd--vtyrgpkltgetvtdwadagyksklclykppqma
----trkadk--ewevga---qpkg-qdvl---agshrla----lipvpn
lgfkfamaf-y-srplctcsiaeayllrriflrnqtwaktrywketsdk-
-elync--a--ec-kcpanvgrdvvntgiprvgvcgnvdffaasngskvg
lskelmgtdgvt----thstt---vdkapdeflldk---nfnsvrcwtrr
ldhtgskvepkkedhltrvfgvtvikhk---------s-----venvvhe
krflsekgtsipfya
>node19
glavagtttsff---khkvir------ys---sletvssdcwvk---gay
gnstsc-mee----yyrltgfiikatylrgtcaptqg----as-pqddnq
ngq-dlfidmayvelwrlhdyglscshlhgnfg-----------pg----
-mhaqm--khkkkgqgslellcgqvrlsaedf-------lvcfltvktdl
aswrigspidspmvpkqva---kgafcvas--as-igklkipscagqelg
pn----p-lggvtn---ap--aevgsladdahfctrtllkqihqdleasr
fqi------evtdd--atyrgtkltgdvvsdwadgaykstacayrsaemg
----lrka-------------epka-qdel---agdhrgskvyslvev-n
lgfqfvlnf-y-artlctcsvaesyllkhiflkiqawsrqrywkkkshk-
-elync--a--dc-kcpaevstdvvktnipraavtantdffadadgskvg
lgrelattegvt----tscttakfvdka--gflldk---nfnevrcwtrr
lphretkvrpkkneeltnvlqplvikhklckthsgylgplgegtanvche
nrsfsekgtsipfyg
>node14
glavagtttsff---knkvir------ys---sletvssdcwvk---gay
gastsc-mee----yyrltgfiikatylrgtcaptqg----as-pqddnk
ngq-dlfidiayvelwrlhdyglscshlhgnfg-----------pg----
-mhaqm--khkkkgqgslellcaqvrlsaeef-------lvcfltvktdl
aswrigspidspmvpkeva---kgafcvas--as-igklkipscagqelg
pd----p-lggvtn---ap--aevgsladdahfctrtllkqihqdleasr
fqi------evtnd--akyrgtkltgdvvsdwadgaykstacayrsaemg
----lrka-------------epka-qdel---agdhrgskvyslvev-n
lgfqfvlnf-y-grtlctcsvaesyllkhiflkiqawsrqrywkkkshk-
-elykc--a--dcvkcpaevstdvvktnipraavtansdffadadgskvg
lgrelattegvt----pscttakfvdka--gflldk---nfnevrcwtrr
lphretkvrpkkneeltnvlqplvikhklckthsgylgplgegtanvche
nrsfsengtsipfyg
>ENV_HV2NZ/24-502
glavagtttsff---khkvirdavvlays---sletvssdswvk---gay
gnstsc-mee----yyrltgfivkstylrgtcaptqg----as-pvddnq
ngq-dlfidmayvelwrlhdyglgcsylhgnfg-----------pg----
-mhaqv--khkkggqgapevlcaqvrlsaedf-------lvcflpvktdl
aswrigapidspmvpkeva---kgafcvas--as-iaklkvpscagqalg
pn----p-iggvtn---apyfaevgrlandehfccrtllkqkhqdleesr
fqi------evndd--atylgtkltgdvvsdwadgaykskacayrsaems
----lrka-------------epka-qdelafqagdhrgskvyamvdv-n
lgfqfvlnf-y-gmklctcsvaesyllkhiflkiqawsrqrywkkkshk-
-alknc--a--dc-kcpaevstdvvktnipresitnasdffanaegskv-
lgrelaategvt----psyttakfvdka--gflldk---nfnavrcwtrr
lphrqtkirpkkteeltnvlqslvikhklcktqsgylgplgdgtahvche
nrpfsekgasipfyg
>ENV_SIVG1/22-522
gltvpgtklsff---dhkkih------ysihgpletvtp-c-vn---ggy
gnatgc-ldalggtycrlsgfiirttylsnecapsrg----ss-pqsdnq
sstgnlfaigqfvslwrlek-----dhlhgdfg-----------pk----
-mhnqv--khkrrgqgsldllaseirlmaedf-------lvclqniksnt
aawrlsgdiddlkvpkkps---kgvfclst--ps-igrlkepscaeqepg
pn----t-mag-lnaialp--aaigslpndlhyctralvkslhddneptr
femkgssvsscpdd--vtykgpkltgetvtdwadggyksklclfkpcqma
----srkapk--rwevga---qpkgrqnvl---agshrla----lkpvvs
lgfrfamaf-y-trplcict-----llrriflrnqtwaktrywkessdk-
-elykt--s--ec-kcpanvgrnvvntgiprvgvcggtkffgasngskvg
vtkelmgtdgtt----thfta---vdkspdeflldk---nmnsvkcwkhs
ldhlgnkvepkiedhltkvfgvtvvkhk---------s-----veevvhe
krflpgkgksipfyg
>node17
glavagtttsff---khkvir------ys---sletvssdcwvk---gay
gnstsc-mee----yyrltgfiikatylrgtcaptqg----as-pqddnq
ngq-dlfidmayvelwrlhdyglscshlhgnfg-----------pg----
-mhaqm--khkkggqgalellcaqvrlsaedf-------lvcfltvktdl
aswrigspidspmvpkeva---kgafcvas--as-iaklkvpscagqelg
pn----p-lggvtn---apyfaevgsladdahfctrtllkqihqdleasr
fqi------evtdd--atylgtkltgdvvsdwadgaykstacayrsaemg
----lrka-------------epka-qdel---agdhrgskvyslvev-n
lgfqfvlnf-y-grtlctcsvaesyllkhiflkiqawsrqrywkkkshk-
-elync--a--dc-kcpaevstdvvktnipraavtansdffadadgskvg
lgrelattegvt----psyttakfvdka--gflldk---nfnavrcwtrr
lphretkvrpkkneeltnvlqplvikhklcktqsgylgplgegtahvche
nrpfsekgtsipfyg
>ENV_HV2D1/24-501
glavggtttsff---knkvis------ys---sletvltdcwik---gvy
gastsc-mee----yyrltgfiikvtylrgtcaptqg----as-pqe---
--q-dlfvdinyvelwrlhdyglscsqlhgnfgkpdtgtf----pg----
-vhaqi--khkkkgsgslellcaqvrlsaeefy------lvcfltvktdl
aswrigspveepmvpkqva---kgvfcvas--as-igklkipscagqelg
pd----p-pggvtk---ap--aqigsladdahfctrtllkqinqdleasr
fqi------evtnd--akyrstklagdvvsdwadgaykdtacayrsaemg
----lrka-------------epka-qdel---vgdhrgskvyslvev-n
lgfqfvlpf-y-grtlctcsvadsyllkhifidiqawsrertwkkqshk-
-elykc--a--ecvkcpaqvstdvvktnvpraavtansdffadadgskvg
lgrelaategvt----pscttakfvdka--gflldk---nfsevrcwtrr
lphrstkvrpkkneeltnvlqpqaikhklckthngylgplgegtanvche
nksftengtsipffg
>ENV_SIVGB/47-569
alittatpfsfl---shkk-----------fspvetpev-c-vn---ggy
gnsngcnleaftakyckl-aflikcawlkgacapskg----at-atadqq
ppddtsfekqqfvpvwkldd-----dhirgvlg-------eclkpsacha
vmpksv--nqtrrsqgslpllcgeinlvnedf-------lvcnlyiksdt
gtwplvgd-atlkvpkppl---assfclst--ht-vghkkvgscvgqceg
plhiqhkgmsgrptleaip--rpvtslisglhfcsqaalsqlhhynettr
fgakqssvgvccqnalvtfvggrilaetfedwaeltyphmlcltnspqka
----ikqadrdgnreagq---hllg-edal---ygsnwla----lipvps
fgssfaipf-f-nrdl-tisiadgfflhrkflmsqt-pkrtywseisska
l----a--tksec-kctlnvgqqlassgiakvaecanvhffdgsggskag
lnfemmatdgvtspklmhgtt---vekapsdfllpkictgfdsvkcwsrh
ldhtgckgqdkkknvlsd---------t---------t-----ivgvtwe
kkllhdegtsipyya
>node9
gltvagtttsff---khkvir------ys---pletvss-cwvn---gay
gnntsc-mea----yyrltgfiikatylrgtcaptrg----as-pqddnq
nge-slfidvayvelwrlddynlscehlhgnfg-----------pg----
-mhaqm--khkrkgqgsldllcgqvrlsaedf-------lvcflnvktel
aawrigspidspmvpkqva---kgsfcvan--ag-igklkipscagqelg
pn----a-lggvtn---ap--aeigslandlhfctrtllkqihqdleatr
fqm------evtdd--atyrgtkltgdtvsdwadgaykstacayrsaems
----lrka-------------epka-qddl---agehrgskvyglvpipn
lgfqfvlnf-y-srtlctcsvaesyllksiflkiqswsrtrywkkkshk-
-elync--a--dc-kcpanvstdvvktnipraaitantdffadadgskvg
lgrelaatqgvt----tscttakfvdka--gflldk---nfnevrcwtrr
lphreskvkpkkndeltnvlgvlvikhk---------g-----tanvche
nrslsekgtsipfyg
>node10
glavagtttsff---khkvir------ys---sletvssdcwvk---gay
gnntsc-mea----yyrltgfiikatylrgtcaptrg----as-pqddnq
ngq-slfidmayvelwrlhdyglscshlhgnfg-----------pg----
-mhaqm--khkkkgqgsldllcgqvrlsaedf-------lvcfltvktel
aswrigspidspmvpkqva---kgsfcvas--ag-igklkipscagqelg
pn----a-lggvtn---ap--aeigslandahfctrtllkqihqdleasr
fqm------evtdd--atyrgtkltgdvvsdwadgaykstacayrsaemg
----lrka-------------epka-qddl---agehrgskvyslvev-n
lgfqfvlnf-y-artlctcsvaesyllkhiflkiqawsrtrywkkkshk-
-elync--a--dc-kcpanvstdvvktnipraaitantdffadadgskvg
lgrelattdgvt----tscttakfvdka--gflldk---nfnevrcwtrr
lphretkvrpkkneeltnvlqvlvikhklcktydgylg-----tanvche
nrsfsekgtsipfyg
>ENV_HV2G1/23-502
glapagtttsff---khkvir------ys---sletvssdcwvk---gay
gnnssc-med----fyrltgfiikatylrgtcapiqg----aaapqdddq
ngq-nl-idmayvelwrvqnlglscshlhgnfg-----------pg----
-mhaqlpvrhkkkaqgalellcgqvrlsaedf-------vlcfltvktdl
aswrigspidspmvpkqvv---kgafcvaseva--igklkipscagqelg
pn----p-lggvtn---ap--aeigslandahfcartllkqihqdleasr
fqi------evtdd--atyrgtkllgavvsdwadgaykstacayrstemg
datelrka-------------epka-qdel---agddrgtkvyslvev-n
vgfqfvlnf-ytartlctcsvaeaylvkhiflkiqawsrtrywqkkshk-
-elync--a--dc-kcpanvstdvvktnvpraavtantdffadsdgskvg
lgrelantegvt----tsittakfvdkv--gfmldk---nfnevrcwtrr
lphretkvspkkneeltnvlqplvikhklckkhsgylgplgyvtanvche
nrsftekgtgipfyg
>node11
glavagtttsff---khkvir------ys---sletvssdcwvk---gay
gnntsc-mee----yyrltgfiikatylrgtcaptqg----as-pqddnq
ngq-dlfidmayvelwrlhdyglscshlhgnfg-----------pg----
-mhaqm--khkkkgqgslellcgqvrlsaedf-------lvcfltvktdl
aswrigspidspmvpkqva---kgafcvas--as-igklkipscagqelg
pn----p-lggvtn---ap--aeigslandahfctrtllkqihqdleasr
fqi------evtdd--atyrgtkltgdvvsdwadgaykstacayrsaemg
----lrka-------------epka-qdel---agdhrgskvyslvev-n
lgfqfvlnf-y-artlctcsvaesyllkhiflkiqawsrtrywkkkshk-
-elync--a--dc-kcpanvstdvvktnipraavtantdffadadgskvg
lgrelattegvt----tscttakfvdka--gflldk---nfnevrcwtrr
lphretkvrpkkneeltnvlqplvikhklckthsgylgplgegtanvche
nrsfsekgtsipfyg
>node7
gltvpgtalsff---dhkkih------ysifgpletvtp-c-vn---ggy
gnstgc-lealggsycrlsgfiirttylrgecapsrg----as-pqsdnq
ssegnlfavtafvslwrled-----dhlhgdfg-----------pk----
-mhnqv--khkrrgqgsldllcsqirlmaedf-------lvcllnikset
aawrlsgdiddlkvpkkps---kgsfcvst--ps-igrlkepscagqepg
pn----t-magvanaialp--aaigslpndlhyctralvkqlhddneptr
femkdssvsscpdd--vtyrgpkltgetvtdwadggyksklclykppqma
----trkask--kwevga---qpkg-qnvl---agshrla----ltpvpn
lgfrfamaf-y-srplcictiaeayllrriflrnqtwaktrywkessdk-
-elykt--s--ec-kcpanvgrnvvntgiprvgvcgntkffaasngskvg
vakelmgtdgvt----thftt---vdkspdeflldk---nfnsvrcwkrs
ldhtgnkvepkkedhltkvfgvtvikhk---------s-----venvvhe
krflpekgksipfyg
>ENV_HV2D2/24-513
glavagttssff---khkvir------ys---sletvgsdcwvk---gay
gnntsc-mss----yyql----ikatylrntcaptrgvhqlns-peddnq
ngq-slfidmatvelwrlhdyglscshlngnfg-----------pg----
-mhaav--khkkkgqgsldllcgqirlsaeif-aadvvalvcfltgktel
mswkvgcpidfpmvpkqva---kgsfcvat--sg-igklkiencagqels
ge----a-lggita---vp--aevgslandahfc-rtllkqinqdlianr
fqm------dvtdd--ptyrntkvtvdvvndwvdgaykstacayraqkmg
----lrka-------------epka-qddl---agehrgskvyalvev-n
lgfqfvlnf-y-astlctctvaqsyllkhiflkfqawnrtrywkkkshk-
-elykc--a--dc-kcpahvstevv----praaitanteffadgggskig
lgrelatddgvt----tsittakfvdka--gfllek---kfsevrcwtrr
lghre------kneeltnvlqvtvikhglcktydgyeg-----tanache
nrsfsekgvsipfyg
>ENV_HV2CA/25-512
glsvahtttsff---khkvir------ys---sletvasdcwvk---gay
gvstsc-mee----yyrltgfiikttylrgtcaptng----as-pqddnq
ngq-dlfidmayielwrlhdyglscahlhgnfg-----------pg----
-mhsqm--khkkggqgalellsaqvrlsaedf-------lvcfhtvktdl
aswrigspiddpmvpkela---kgafcvas--as-iakvkipscagqelg
pn----p-lggvth---apyfaevgsladdahfctrtllkkihkdleanr
fqi------evtdd--atylgtklngdvvsdwndgaykstacayrsaemg
----lrra-------------epkv-edel---agdlrgssvyslvev-n
lgfqlvlnfny-grtlctcsvaeshllkniflkiqawsrqrywkkkshk-
-elyncefa--dc-kcpaevrtdvvktnipkaavtadpdffadadgskig
lgrelattegvt----psytaakfveka--gfnldk---nfnavrcwtrr
lphretkarpkeneeltnvvrplvikhklcksqsgypgplgwgtahvcqe
qrpfsekgtnipyyg
>node18
glavagtttsff---khkvir------ys---sletvssdcwvk---gay
gnstsc-mee----yyrltgfiikatylrgtcaptqg----as-pqddnq
ngq-dlfidmayvelwrlhdyglscshlhgnfg-----------pg----
-mhaqm--khkkkgqgslellcaqvrlsaedf-------lvcfltvktdl
aswrigspidspmvpkeva---kgafcvas--as-igklkipscagqelg
pn----p-lggvtn---ap--aevgsladdahfctrtllkqihqdleasr
fqi------evtdd--atyrgtkltgdvvsdwadgaykstacayrsaemg
----lrka-------------epka-qdel---agdhrgskvyslvev-n
lgfqfvlnf-y-grtlctcsvaesyllkhiflkiqawsrqrywkkkshk-
-elync--a--dc-kcpaevstdvvktnipraavtansdffadadgskvg
lgrelattegvt----pscttakfvdka--gflldk---nfnevrcwtrr
lphretkvrpkkneeltnvlqplvikhklckthsgylgplgegtanvche
nrsfsekgtsipfyg
>ENV_HV2BE/24-510
glavagtttsff---kskvir------ys---slevtssacwvk---gay
gagtsc-fee----yyrlsgfiikatylrgtcapthg----as-pqgdnk
ngq-dlfidiayvelwrlhdyglsishlsgnfg-----------pg----
-mhaqm--kqkkkgqsslellcsqvrlsaeef-------lvcfltvktdl
aswrigspidssmvpkeva---kgafcvas--as-igklkipscagqelg
ps----p-lggvtn---sp--aevgsladdahfctrtllkqehqdleaar
fqi------eitnd--akyrgtkltgdvvsdwadgaykstacafrsaemg
----lrka-------------epka-qdel---agdhksskvyslvev-n
lgfqfvlnf-y-grtlcscsvaesvllkhiflkiqpwsrqrywkkkshk-
-elykc--a--dcvkcpaevstdimktvipraavtansdffadadgskvg
lgrelatttgva----psctiatfvdla--gflldk---nfnevrcwtkr
lphretkvkpkkneeltnvlqplvikhklckthsgylgslgdgtadlche
swsfsengtsipfyg
>ENV_SIVM1/24-528
gltvagtktsff---khkvir------ys---pletvss-cwvn---gay
gnntsc-meg----ctkltgfiirttflrgtcaptrg----as-pqddnq
ege-slfvdvayvdlyrlddynlscehlhgnfg-----------pg----
-mhaqm--khkrkgqgsldllcgqvrlsaedf-------lvcflnvktgl
aayrigspidspmvpkqva---kgsfcvan--ag-igklkipscageelg
pt----a-lngvtn---ap--aeisslandlhfctgallkqihqdleatr
fqm------eitdd--atyrgtkltgdtvtdwadgayestacayrsaems
----lrka-------------epka-q--l---ageprgskvyglvpips
lgfqfvlgf-y-srtlctcavaesyllksiflkiqvwsrarywkkkshk-
-elync--a--dc-kcpanvstdvvktdipraaitaitdfladaegskvg
lgrelaatqgvt----tkcttaksvdka--gflldk---nfndircwtrr
lphkeskvkpkkndhltnvlgvlvikhe---------g-----tanvche
nrslsekgtsipfyg
