>node9
peinkiaddiktaftikgfvlqyqgrkdpfapa-----dtcfahlptykk
--itad-ggnagtl-adcapispsnf-sa---khtlakfggagtvienad
glv-lktn-vrptr-as---krgll--ggkffvds-nsslsghvskhhtp
-ei---pkeskpsakksrkqpev-frevhalg-sghspitnychhndmpd
qddgkvdtvatdkdkipwgnleqltshpkvm-neqpsfty--kqq---mg
ltqvvvsktsskikskdmpperl-hgltc-pvgl-ggdkqhtfaqeeq-l
kvclk---syteiekckpqeplplvrdakpatsfkv--ikgaetpltrgd
rgkdpgrvmckyqshcagkgsa----kfah-pastekatf---dhaqaaa
thysitc-yalhlvnrthwv---tv-------yknvs-----------id
-d--pnvghaenslapg-nagl-gslgsprhvlvpannckltpfmtcgle
nsrgkpliafdennppvpdyqnkcsgigalvtatnsea-thiktagckmg
ehrraeciaskggvlns-qvtvperpt---------a
>node19
peinkiaddiktafsikgfvlqyqgrkdpfapa-----dtcfaelptykk
--itad-ggnagtl-aecapispsnf-sa---krtlpkfggagtviedid
glv-lktn-vrptr-as---krgll--ggkffvds-nstlsahvskhhtv
-ei---pkesnpsaklsrkqpev-frmvhalg-sghspitnycshndmpe
qddgkvdtvatdkdkipwgnldqltshpkvm-negpsfty--kqq---mg
ltqvvvsktaskisskdmpperl-hgftc-rvgl-ggdkshtfaqeeq-l
kvclk---syteiekckpheplplvrdakpatsfkv--ikgaetpltrgd
rgkepgrvmckyqghcagkgsa----klaqspasyekatf---dhadpaa
shykits-yalhlvnrthwv---av-------yknls-----------ve
-d--pnvghaenslapg-nagl-gglgsprnvlvpannckltpfmtcgle
nsrgkplirfdennppepdylnkckgiggivtatnsem-thiktagckmg
ehrreecvaskggvlnstqvtvperpt---------r
>node18
peinkiaddiktafsikgfvlqyqgrkdpfapa-----dtcfaelptykk
--itad-ggnagtl-aecapispsnf-sa---krtlpkfggagtviedid
glv-lktn-vrptr-as---krgll--ggkffvds-nstlsahvskhhtv
-ei---pkesnpsaklsrkqpev-frmvhalg-sghspitnycshndmpe
qddgkvdtvatdkdkipwgnldqltshpkvm-negpsfty--kqq---mg
ltqvvvsktaskisskdmpperl-hgftc-rvgl-ggdkshtfaqeeq-l
kvclk---syteiikckpheplplvrdakpatsfkv--ikgaetpltrgd
rgkepgrvmckyqghcagkgsa----klaqspasyekatf---dhadpaa
shykits-yalhlvnrthwv---av-------yknls-----------ve
-d--pnvghaenslapg-nagl-gglgsprnvlvpannckltpfmtcgle
nsrgkplirfdennppepdylnkckgiggiv----sem-thiktagckmg
ehrreecvaskggvlnstqvtvperpt---------r
>ENV_HV2NZ/24-502
peinniaddiktgfnikgfvlqyqgrkepfppa-----dtcfaelptykk
--itad-ggnagtl-aecapispsnf-st---krtlpkfggagtviedid
glv-lktn-vrptr-as---krgll--ggkffvds-tstlsahvsklhtv
-ei---paqsnpsaklsrsqpev-vllvqalg-sghspitnycshnnvpe
qddgkvetiatdkdkiawgnldqltahpkvm-negpsfty--kqq---mg
ltqvvvsktaskisdkdmpperl-hgftc-rvgl-ggdkshtfaaeeq-l
kvclk---syteiikckkhealpltraakpatsfkv--fkgaetpltrgd
rgkepgrvmckyqghcagkgsa----klalspasyekatf---dhadpaa
shykits-yalnlvyrthwv---av-------yknls-----------ve
-e--psvghaenslapg-nlgl-gglgsprkvlvpandckltpfqtcgle
ksrgkpeirfdennppepdylnkckgiggiv----sem-thiktagckmg
ehrreecvaskggvlnstqvkvperpt---------r
>ENV_SIVGB/47-569
pevaeamkqfhkefcvrg--------aehckrsgtdqietcy----aykk
--vrag-kensgevnseckr--------s---akilpkyggtargiksat
plg-lkkqwakanrrvftdakrgll--gkkaypng-nfsldgh---htts
-nv---------------nemge-lrmarvlgsientpyqstgkhtkkpq
res-----lgveaarapwvglsqytatkkpmlsqalryst--kig---lg
lcrsvknkmkmkiqand-pahklqwaltc-p--l-ggstehivaaqdh-m
svc-------vpvamckssetldiskeakpstnlniggvkagavklargn
rayeagrmmctyeqeraikgsp----kfvn-aksteqarfdfvdqsgeas
klyymec-yilhlmsqtswi---vvlacgtsghkntg-----------se
le--pslk-------pa-tsgl-ghly--rhvlvdkdrckgsphllcdme
fsncqpdigfnghkepvpenvnqcsaipamvtkkkdep-dgtktkgcatg
dlrradcvaakggliva-qiitpnrpa---------g
>ENV_HV2CA/25-512
peinkiaddiktafsikgfvlqyqgrkepfapa-----dtcfaelptykk
--vaan-ggnagtl-aecapitcsnf-sp---krtlpkfggagtvie-id
glv-lktd-vrptr-as---krgll--ggryfvdsqnstlaahvskhhtv
-ef---pdesnpsaklsrkqpev-frmvqalg-sghspitsycshnavpe
qddgkvetvatdkdkiawgnldqltahpkvm-ndgpsftyifkqq---mg
lthvivnktaskiaekkmpperl-hgftc-rvgl-ggdksqtfaqeeq-l
kvclksfvayteiikckpheplplvrdakpatsfkv--fkgietpltrgd
rgkepsrvmckyqghcagkgsa----klalspasyekatf---dhadpaa
shykvts-yalnlvhrshwv---av-------yknls-----------vk
-d--pnvgnaksslvpg-nagl-gglgsprnvlvnannckltpfmtcgle
nyrgkplirfdennppepdnllkckgsggiv----sem-thiktagckmd
ehrreecvgpkggvlnstql--parpt---------r
>node8
peitriatnfrdeftirgfvlqflarknhcars-----etcf----tykk
--itag-tgnagtv-sdcapfsppefgsa---khilpkfggtgraienad
gla-lktdwgritrrtfgepkrgll--gadfyvdg-nfslggh---hhts
-ev---pkemkpsapkrkkepav-lrmvrvlg-sghcpytatchhndnpd
qddgaidaletnkgkipwvnlsqltsqpkvmpnaqpsste--kqa---mg
lcqvvssktgskikakd-gpqklqhgltc-p--l-ggdkqhtaahedh-m
kiclk---syteiemcksqeplalvrdakpatsfdv--ikagatplargd
rgkdpgrlmckyeqhcafkgsa----kfvh-paateeatfntvdhaqats
klysmac-yilhllnrthwt---mv-------yknac-----------ie
-d--pnvg-------pa-nagl-ghlyalrhvlvaadsckgspfmscnle
nskckpvigfdshnepvpdyqnkcsgigalvtatssep-thiktkgckvg
elrraecvtskggilis-qvtvpqrpt---------d
>ENV_SIVG1/22-522
peitrvatnfrdeltirgfvlkflarkahctrt-----etcf----tekk
--vttgit--agtv-secmpfsppdfgpa---khilpkfegtgraienad
slaalktawgkitrrtygnpkrall--gadfyvdg-nfslgdh---hnit
-ev---skemkpsapkrkkepav-lrlvkvlg-sghcpytatchhndnpw
qadgsigaletnkgkipwvnliqltsqpkhmpnaqpastd--rqa---mg
lcqvvssktgskikakg-gkqklqngltc-p--l-ggdsqntarhrdh-m
kiclk---syteiemckaheplalvrdakdassfev--nragptplargd
rgkdpgrlickyeqhcafdgsa----kfvn-paateestfntvdhsqavs
rlysmac-yilnllnsthwt---mv-------ygqgt-----------ie
-d--pnvg-------pa-qagl-ehlyvlrhvlvasdsckgspfiscnle
v----gvigfdshnepvpdyqvkcegvealvtvtssep-thiktkdckvg
elrraecvtakgnilt--qvpvpqrpt---------a
>ENV_SIVV1/24-538
peitriatnfrdeltikgfviqflarktncgrt-----etcf----tnkk
--vatgin--ggsv-sdcvpfsppefgpa---khvlpkfggtgraienad
gle-lrtewgkiarltfgnpkrgll--gaefyveg-nfslggh---hhsa
-ev---pkqlkpkvpkrksepavglrmvkvlg-sghcpvtatchhndlpd
eakgsidsletnkedipwvnlaqltsepkhlpntqpsste--kqa---mg
lcqvvsskkgvkikarg-gkqklqqgltc-p--l-ggdgqhtaaheds--
-i------sypeadvcksqeplalvrdardassfda--irtaptplargd
rgkdpgrlkckyeqhcalrgsartgskfvh-paatqenafnkvdhaqavs
klfsmfc-yilsqlnskhwtlllmv-------ykqgt-----------ig
-dsdpgvg-------pghqaglyehlyvlkhvfvaadsckgspfmecnle
nskckpiigfdshnepvpdydkkcedvealv-atssep-thrktkackvg
elrrcecvtakgvivt--gvtvpqrpp---------d
>node7
peitriatnfrdeftirgfvlqflarknhcart-----etcf----tnkk
--vttgit--agtv-sdcapfsppefgpa---khilpkfggtgraienad
gla-lktawgkitrrtfgnpkrgll--gadfyvdg-nfslggh---hhtt
-ev---pkemkpsapkrkkepav-lrmvrvlg-sghcpytatchhndnpd
qadgsidaletnkgkipwvnlaqltsqpkhmpnaqpsste--kqa---mg
lcqvvssktgskikakg-gkqklqhgltc-p--l-ggdsqhtaahedh-m
kiclk---syteiemcksqeplalvrdakdassfdv--iragptplargd
rgkdpgrlmckyeqhcafkgsa----kfvh-paatqestfntvdhaqavs
klysmac-yilnllnsthwt---mv-------ykqgt-----------ie
-d--pnvg-------pa-qagl-ehlyvlrhvlvaadsckgspfmscnle
nskckpvigfdshnepvpdyqkkcegvealvtatssep-thiktkgckvg
elrraecvtskgnilt--qvtvpqrpt---------d
>node17
peinkiaddiktafsikgfvlqyqgrkepfapa-----dtcfaelptykk
--itad-ggnagtl-aecapispsnf-sa---krtlpkfggagtviedid
glv-lktn-vrptr-as---krgll--ggkffvds-nstlsahvskhhtv
-ei---paesnpsaklsrkqpev-frmvqalg-sghspitnycshnnvpe
qddgkvdtvatdkdkiawgnldqltahpkvm-negpsfty--kqq---mg
ltqvvvsktaskisekdmpperl-hgftc-rvgl-ggdkshtfaqeeq-l
kvclk---syteiikckpheplplvrdakpatsfkv--fkgaetpltrgd
rgkepgrvmckyqghcagkgsa----klalspasyekatf---dhadpaa
shykits-yalnlvnrthwv---av-------yknls-----------ve
-d--pnvghaenslapg-nagl-gglgsprnvlvpannckltpfmtcgle
nsrgkplirfdennppepdylnkckgiggiv----sem-thiktagckmg
ehrreecvaskggvlnstqvkvperpt---------r
>ENV_HV2G1/23-502
peinriaddiktafsikgfvlqyqgrkdpfasa-----dtcfaelppykk
llitad-ggssgtl-aecaqispsdf-sd---krtlpkfggagtviedid
glv-lktn-vrptr-as---krgll--ggkffvds-ngtlsahvskhhtv
-ei---pkesnpsaklsrkqpev-frmvhalg-sghspitnfcthnampe
qddgkvdtvatnkdkipwgnldqltthpkvm-negpsfty--kqq---mg
ltqvivsktatkisskdmpperl-hgftc-raglsggdkshvfsqeeq-l
kvclh---syseiekckpheplplardakpatsfkv--ikgaetpltrgd
rgreptrvmckyqshcagkgaa----klaqspasyekatf---dhadpaa
shykita-yalhlvnrthwv---av-------ykkls-----------id
-d--pdvghaenslgpg-nagl-nglgsprnilvpannckltpfmkcgle
nsrgkplirfdennppepdylnkckgiggivtatnsem-thiktagckmg
ehrreecvaskggvlnstqvtvperpt---------r
>ENV_HV2D1/24-501
peinkiasdiktafsikgfileyqgrkdpfvpa-----dtcfaelptykk
--itad-ggnagtl-aecapispsnf-sa---krtlpkfggagnviedid
glv-lktn-irptr-en---krgll--ggklfvds-nsslaahaskhhtv
-ei---pkernpsgklsrkqpev-frmvhalg-sghspitnycshndmpe
sddgkvntiatdkdkipwgnldqltshpkvg-negpafty--tqqecfmg
lthvvvsktaskisskdmpperl-hgfsc-rvgl-ggdkshafaaeeq-l
kvclk---syteiikcspfeplplakeakpetsfky--ikgaetpltrgd
cgkepgrvmckyqghcagkgsa----klaqspssyekatf---dhadpaa
shykits-yplhlvnrtkwv---av-------yknls-----------vq
-d--p--ghtensvapg-nggl-gglgsprsvlipandctltpfmacgle
nsrgkplirfdennppetdylnkckgiggiv----sem-th--tdgckmg
esrreecvaskggllnstrvtvpdrpt---------r
>ENV_SIVM1/24-528
heidkmaddiktgftikgfvlqyqgrkdpfapa-----dtcfahlptykk
--ittd-ggntgrl-adcapispsnf-pa---khnlakfggagtvientd
glv-lktn-vrptr-ae---krgll--ggkffvns-nsslsghvskhhtp
aei---pkeskpsakksrkqpev-freahslg-sghkpitlychhndmpd
qddgkvdtlatdkdkkawgnleqltshpkvm-neqpsfty--kvq---mg
ltqvvvsatsskikskdmppewl-hgltc-pagl-ggdkqhtfaqeeq-l
kvclk---syteiekckpqeplplvrdakpatsfkv--ikgaeipltrge
rdkepgrvmckyqshcagkgsa----kfah-pastekaky---dhaqaaa
thyaatc-yalhlisrthwv---av-------yknvs-----------id
-d--pnvghaedsl-------l-gslassrhvlvfandcklspfltcgle
nsrgkplisfdesnpplpdyqnkcsgigalvtatnsesmthiktagckmg
ehrraeciaskggvlns-qvtkpdratkshatvkkga
>node10
peinkiaddiktafsikgfvlqyqgrkdpfapa-----dtcfahlptykk
--itad-ggnagtl-aecapispsnf-sa---krtlpkfggagtviedid
glv-lktn-vrptr-as---krgll--ggkffvds-nstlsghvskhhtp
-ei---pkeskpsaklsrkqpev-frmvhalg-sghspitnychhndmpe
qddgkvdtvatdkdkipwgnleqltshpkvm-negpsfty--kqq---mg
ltqvvvsktsskisskdmpperl-hgftc-pvgl-ggdkshtfaqeeq-l
kvclk---syteiekckpheplplvrdakpatsfkv--ikgaetpltrgd
rgkepgrvmckyqghcagkgsa----klaq-pasyekatf---dhadpaa
shyrits-yalhlvnrthwv---tv-------yknvs-----------ie
-d--pnvghaenslapg-nagl-gglgsprnvlvpannckltpfmtcgle
nsrgkplisfdennppepdylnkckgigglvtatnsel-thiktagckmg
ehrreecvaskggvlnstqvtvperpt---------h
>ENV_HV2BE/24-510
peinkiaseiktafsikgfvlhyqgrkdpfapa-----dtcfaelptykk
--itad-ggnagtl-aecapispsnf-saamgkrslprfggageviedid
glv-lktn-vrptr-ak---krgll--ggkffadt-nsslsahvskhhtv
-ei---pkernpsgklsrkqpev-frmvhnlg-sghspitdycshndmpd
eddgkvdtvvkdkdkvpwgdldqltshpkvm-negpsfty--sqqeclmg
ltqlvlsgtaskisskgmpperl-hgfsc----l-gddkshtfaqeeq-l
svclk---syttinkvkpfeplplvdeakpatsfkv--ikgaetpltrgd
rgkeparvmckyqghctgkgsa----klaqspasyekatf---dhadpaa
shykitspytlhlvkrtkwv---av-------yknls-----------vq
-d--pnvghaenslapg-nagl-ggqgspknilvpannckltpfmtcgle
nargkvlirfdedgppeadaldkckgiggiv----tem-th-gtcvckmg
ehkreeciaskggvlnstqvtvperpt---------r
>node11
peinkiaddiktafsikgfvlqyqgrkdpfapa-----dtcfaelptykk
--itad-ggnagtl-aecapispsnf-sa---krtlpkfggagtviedid
glv-lktn-vrptr-as---krgll--ggkffvds-nstlsahvskhhtv
-ei---pkesnpsaklsrkqpev-frmvhalg-sghspitnycshndmpe
qddgkvdtvatdkdkipwgnldqltshpkvm-negpsfty--kqq---mg
ltqvvvsktaskisskdmpperl-hgftc-rvgl-ggdkshtfaqeeq-l
kvclk---syteiekckpheplplvrdakpatsfkv--ikgaetpltrgd
rgkepgrvmckyqghcagkgsa----klaqspasyekatf---dhadpaa
shykits-yalhlvnrthwv---av-------yknls-----------ve
-d--pnvghaenslapg-nagl-gglgsprnvlvpannckltpfmtcgle
nsrgkplirfdennppepdylnkckgiggivtatnsem-thiktagckmg
ehrreecvaskggvlnstqvtvperpt---------r
>ENV_HV2D2/24-513
aeinkiaediktalmvpgfvfqyqgrknpfdps-----dtcfmhlptykk
--itpd-ggnagtl-aecgaispsnf-sa---iralptfggagtvvedid
gll-lktn-vrptc-as---krgllakggnffvds-nsalsghvskhhtp
-pirgcpkeskpsaklsrkqpdv-frvvhalg-aghspitnichnsdm--
qddgktdtgstdkdaipwgnleqvtshpkvm-negsafty--kqe---mn
qklvvvsntsskasskdmpperl-hgfscnpvgl-ggdnshtfaqeeqnl
--clk---pytdiekckpheplplprdskpatsfkv--ikgaetpltrgg
qgneparvmckyqghcagkgsl----klaq-pasyerstf---dhaapaa
thyrits-yalhlvdtthwt---sv-------ykgvrkllyaeltpshie
-e--pnvghaqnslaag-ndgl-gglgtprgvlipasnckltplmtcgld
nsrgkalisfdennppepdylndck-igglvtatnsel-thittqgckmg
ehvqedcvatkgvvlestqvavperpt---------h
>node14
peinkiasdiktafsikgfvlqyqgrkdpfapa-----dtcfaelptykk
--itad-ggnagtl-aecapispsnf-sa---krslpkfggagtviedid
glv-lktn-vrptr-as---krgll--ggkffads-nsslsahvskhhtv
-ei---pkernpsgklsrkqpev-frmvhalg-sghspitnycshndmpe
eddgkvdtvatdkdkipwgnldqltshpkvm-negpsfty--sqqeclmg
ltqvvvsktaskisskdmpperl-hgfsc-rvgl-ggdkshtfaqeeq-l
kvclk---syteiikckpfeplplvkeakpatsfkv--ikgaetpltrgd
rgkepgrvmckyqghcagkgsa----klaqspasyekatf---dhadpaa
shykits-yalhlvnrtkwv---av-------yknls-----------vq
-d--pnvghaenslapg-nggl-gglgsprnvlvpannckltpfmtcgle
nsrgkplirfdennppepdylnkckgiggiv----sem-thiktagckmg
ehrreecvaskggvlnstqvtvperpt---------r
