>ENV_HV2NZ/24-502
cgd---sggaggevvsrnkkgkirlarketvkscafqtylaalmhanahy
skkkrfnaesglavsl---------envgklrlvgafkcfgpw--npvsk
mcp----lgvvn--qnelithsarpancsrqgatlcevfyrvayvakelg
kpl--kfgskptrltwgtkqttyehrsdycvamc------c--hg--kkg
kqghtsdgatlkddlml---gsestggslgsndcgklqwnedwvdsisag
htnapkgrirpcspalgaipegha----hrp--sw------vdpcgshtm
paeysyl-----ltggtcrlggpeaanqvpi-fnsdrktqhkvvyymdle
lepsryqdgdlnlwng---vtl-----s----lhlhs-knrgvratl---
--nlgyrkysgeg----lpvnscrcgvkkgnadf---qkpka--npsnk-
------gctkdltsttddvs--------schvfhytyhmympfpamadis
wksqgysqscp--lvarlkkfpkgnpald------rydtecegynkkvkf
ygggvnngptgdhfivatercgtkgglgeqklaeaadegcagvmle---y
tvg
>node9
cgd---sggagggvvsrnskgkirlsrketvkacafqtylealmhanary
gkrkrfnvesglavsl---------tnvgklrlvgafkcfgpwsanplsk
mcp----lggvd--qnelitqtarpkhcsvdgaslcevfyrvayvakqlg
kpl--sfgfrptiltwgtnqttyehkgdycvslt------c--hg--kkg
lqggksdgaklrdslml---gsegtgptlgssdcakfqwnedwvdsitag
hpdapkgrcrpcspslgaipkthaceimhrp--sw------vdmcgthtm
paeysyl-----ltgntcqlggpeaaneipv-fnshrktqhkevyimdlk
l----yqdgd----dg---vtl-----s----vhlht-ksrgvratl---
--nlgyrkysgeg----lpmdscrcgikkgnaey---qkpka--npgnk-
------gctkdltsttndks--------tchvfnytyhmylpfpaladvs
wksqgykqkcp--lvarlkkfpkgnpald------rynyecenyngkvky
yggavnngptgdqfigatercgskgglgyqrlgeatdegcsgvmlegqty
svg
>node17
cgd---sggagggvvsrnkkgkirlsrketvkacafqtylaalmhanahy
skrkrfnaesglavsl---------pnvgklrlvgafkcfgpw--nplsk
mcp----lgvvd--qnelitqsarpahcsadgpslcevfyrvayvakelg
kpl--sfgfkptrltwgtnqttyehkgdycvalt------c--hg--kkg
lqggksdgatlrddlml---gsestggtlgsndcaklqwnedwvnsitag
htnapkgrcrpcspalgaipethaceimhrp--sw------vdpcgahtm
paeysyl-----ltggtcrlggpeaanevpv-fnshrktqhkivyymdla
levskyqdgd----ng---vtl-----s----vhlhs-ktrgvratl---
--nlgyrkysgeg----lpvdscrcgikkgnadf---qkpka--npgnk-
------gctkdltsttddvs--------tchvfnytyhmympfpamadis
wksqgykqscp--lvarlkkfpkgnpald------rydyecegyngkvkf
ygggvnngptgdqfisatercgskgglgeqrlaeatdegcagvmlegqty
svg
>ENV_HV2BE/24-510
cgd---ssgagggvvsrgkkgkirlsrketvkayafttrlaalmhanthy
skrkkfhaesgmavav---------pnvgklrlvgafkcfgpw--nplsk
lcp----lgvvd--qndliartarpahcsvdgpslcevfyrvay--nelg
kpl--sfgyrptrltwgtnqtdyehkgdycvals------c--hg--kkg
qqggksdgatlrddlml---gsestgptlgsndcaklqwnedwinsitag
hpnaskgkcrpcspaletipkthacetmhrp--tw------vdpcgqhtm
paeygyl-----ltgatcrlpgpqatneipa-fnshrktqhkivyymdla
lqvskyqdgd----ng---vtv-----s----ihlvs-ktrgvratl---
--nlgyrkysgeg----lpvdscrcgikkslaey---qkpka--npgnk-
------gctndltsttidvs--------tchcfsftyhmympfpaaaevs
wksqgfkqscp--lvkrlkkfpkgnpald------rydydcegyngkvkf
yggavntgptgdqfigatercgskgglaeqrlaeatdencagvmvegqty
svg
>ENV_SIVG1/22-522
cgd---adgtaggvtsrnskgkvrlsrkttvkacpfrtyleelmhanarf
gkkkrlnvesglav-kkaagltrstpdegnikglasfkcleswkseqlkk
mcp----lsaae--qhqlitqtsrpkncsveghglcevaykvaylakqld
nrl--tfglrtdvlawstnestykhkgdycvsltt----scgkhg--kkg
hqggkktgvklrdslml---ggeatdptldshecalfqwgenwvdsvtag
rpdappgrcspcsdslga-------aidqrp--swtpgtrqselcgvrti
eaaysylsgerkmpgatcqlglpesaydirv-fgnhr----------dlk
l----yhdgd----dg---vtg-----s----ihlht-rllgvraml---
--dlgyrkkseag----lpsngckcslkrgnaey---hrakg--npgsk-
------gcsktlesp---kg--------tcnvftytyhlympfavladvs
wyaegyknacer-lvpkdkkepkggpvld------ryeaecetydgkvky
yagavthdptceqfisatkrcgsrgglgyrrlpdatdngcsgaalecqty
tvg
>node7
cgd---adgtaggvtsrnskgkvrlsrkstvkacpfrtyleelmhanarf
gkkkrlnvesglav-mknagltrstpdegklkllasfkcfeswksnalkk
mcp----lsgae--qhqlitqtsrpkncsveghglcevsykvaylakqld
nrl--tfglrtdvlawstnestykhkgdycvsltt----sc--hg--kkg
hqggkstgvklreslml---ggdatdptldshecalfqwsedwvdsvtag
rpdappgrcspcsdslga-------eidqrp--swtpgsrqselcgvrti
eaaygylssqrkmpgatcqlglpesaydirv-fgnhr----------dlk
l----yhdgd----dg---vtg-----s----ihlht-rllgvraml---
--dlgyrkkseag----lpsngcrcslkrgnaey---hkakg--npgsk-
------gcsktlesp---kg--------tcnvftytyhlylpfaaladvs
wyaegyknacpr-lvaknkkdpkggpvld------ryeyecetydgkvky
yagavthgptceqfisatkrcgskgglgyrrlpdatdngcsgaalecqty
tvg
>ENV_SIVV1/24-538
cgd---adgtaggvtsrnakgkirlarkstlkacafrtyieqlmhavarf
gkkkqlnvesglav-mksagltrstpengklkllv-fkcfeswksnslkk
mcp----lsgad--khqlitqtsrpknasidghglcevsykgsylakkld
grl--tfslrtdvlawtnnessykhkgdycvslpt----ns--hg--kkg
hqggkstgvklreslml---gaeatdptldshgcamfqwsedwvdaatag
rpdappgrccpcsdalga-------eidqrp--swtpgsrhsevcgvrti
eaaygylssqkkmpagtcrldlpetaydirv-fgnpk----------dlk
l----yhdge----dg---vts-----s----iqlht-rlidvrall---
--dlgfrkkneagkaarlpsnscrcyekrgnady---hkakglvnpgsk-
------gcsntlqap---kghgtgynshtcnvftytyiiylpfaaiadvs
wyyenyrdacpr-lvaknkqeakggpvld------ryeyecepyngnvky
yagavthgptcdrfisttkrcsskggiayrrladatddgcsgaalecqty
svg
>ENV_HV2G1/23-502
cgd---sggagggvvswnskgkirlsreetvkacayetylaalmhanahy
skrkrfdaesglavsl---------pnvgklrlvgafkcfgpw--nplsk
mcp----lgvvd--qnelitqtarpahctvdgpslcevfyrvayvakelg
kpf--sfgfrpailtwgtnqttyehkgdycvslt------c--yg--kkg
lqggksdgatlrddlml---eaqstgptlgsndcaklqwnedwvnsitpg
qpnapkgrcrpcspalgaipkthaceimhrp--sw------vdpcgahtm
paeys-----------tcrlggpeaaneipv-fnshrktqhkivyimdla
levskyqdge----ng---vtl-----s----vhlha-ktrgvratl---
--nlgyrkysgev----lpvdscrcgikkgnagy---qkpka--kpgnk-
------sctkdltsttddvn--------tcqlfnytyhmympfpamadvs
wksqgykqgcp--lvarlkkfpkgnpald------rydyecegyngqvkf
yggavntgptgdqfigvtemcgskgglgeqrlldatdegcasvmlegqty
svg
>ENV_HV2D1/24-501
cgd---sggagggvvsrnkkgkirlarketeks-afqtylaalmfanahy
skrkrfnnesglavsl---------pnvgklrlvgafkcfgpw--nplsk
mcp----lsvve--qnelttrtarpahcpvdgpplcevfyrvayvakelg
kpi--afgykpnrltwgtnqtkydhkgdycvalt------c--hg--kkg
lqggksdggtlrddlml---gsestgpalgsndcvklqwnedwvqsitag
hpnadkgrcrpcspalgatpkthacelmhrp--tw------vdpcgahtm
paeysyl-----ltgntcrlggppaaneipv-fkshrktqhkivyymdla
lqvskyqdgv----ng---vtl-----s----vhlhs-ktrgvratl---
--nlgyrkysgeg----lpvdscrcgfkkdvaey---qkeka--npgnke
vttvdtgctndltsttddvs--------tchvfsygyhmympfpamaqvs
wksqaykqscg--lvarlkkfpkgnpald------rydyecegyngkvkf
yggaanngpasdqfigatercgskgglaeqraaeatdegcagvmlegqty
svg
>ENV_HV2CA/25-512
cgd---sggaeggvvsrnkkgkirlsrketvkacafqtylaalmhanahy
skrkrfnaesgfavsl---------pnvgklrlvgafkcfgpw--nplse
mcp----lgtvd--qnelitqsarpahcsadgpslcevfyrvayvakels
kpl--sfgfkpsrltwgtkqttyenkgnycvglt------c--hg--kkg
lqggksdggslrddlml---gsestggtlgsndcakltwnedwvnsitag
htnapkgrcrpcspalgaipethtcdimhrp--sw------vdpcgaham
saeysyl-----ltggicrlggpeaanevpv-fnghkktqhkivyfmdla
levskyqdgd----kg---vtl-----s----vhlhs-ktrgvratl---
--nmgyrkysgeg----lpvdscrcgikkgnadf---qkpkg--npgnk-
------gctkdltsatddva--------tchvfnytyhmympfpak-dis
wksqgykqscp--lvarlkkfpkgnpsld------rydlecdgyngkvkf
ygggvnngptgnqfilater-gsrnglgeqrlaeatdegcagvmfegqty
svg
>node18
cgd---sggagggvvsrnkkgkirlsrketvkacafqtylaalmhanahy
skrkrfnaesglavsl---------pnvgklrlvgafkcfgpw--nplsk
mcp----lgvvd--qnelitqtarpahcsvdgpslcevfyrvayvakelg
kpl--sfgfrptrltwgtnqttyehkgdycvalt------c--hg--kkg
lqggksdgatlrddlml---gsestgptlgsndcaklqwnedwvnsitag
hpnapkgrcrpcspalgaipkthaceimhrp--sw------vdpcgahtm
paeysyl-----ltgntcrlggpeaaneipv-fnshrktqhkivyymdla
levskyqdgd----ng---vtl-----s----vhlhs-ktrgvratl---
--nlgyrkysgeg----lpvdscrcgikkgnaey---qkpka--npgnk-
------gctkdltsttddvs--------tchvfnytyhmympfpamadvs
wksqgykqscp--lvarlkkfpkgnpald------rydyecegyngkvkf
yggavnngptgdqfigatercgskgglgeqrlaeatdegcagvmlegqty
svg
>ENV_SIVGB/47-569
chelmdqnansggvnnsnchgtgrinqrsaidp------leq---adkhf
sakkifsvdfalsa-lravkvdrsapdvpllrvvalfkpfsewngnslkr
vcpvsrlldgaeklqkqllaqtart-hcspkghglcevgmyasyqlthle
aqlkhkf-------awgtvkktsnekgaycvsleaakhvsc--rqsdkka
d-ggkttdddl-----s---dndagnpilgphdcpkfqwpddwvesvtwg
rpkgskpnchac-ntlpa-------rvqqrassvw------tvlaiakkr
galygyltseralvrstaqlnlppsvydirmsfgsgr----------dlp
v----lhead----qaksmvmfdeglgs----thlhaqklpghqgklflf
slelaykkkrtag----naiescdcsmkkgstky---hrykg---pgck-
------gcsntlgk--------------------yayhsylplhplaans
wfddgyknyit--qssknkkdtkgspvlq------kyqfecqsfngavhy
yggmethgsscvefimqtarcgskgglgfrrlakpsvnscsdspldgray
lvl
>node19
cgd---sggagggvvsrnkkgkirlsrketvkacafqtylaalmhanahy
skrkrfnaesglavsl---------pnvgklrlvgafkcfgpw--nplsk
mcp----lgvvd--qnelitqtarpahcsvdgpslcevfyrvayvakelg
kpl--sfgfrptrltwgtnqttyehkgdycvslt------c--hg--kkg
lqggksdgatlrddlml---gsestgptlgsndcaklqwnedwvnsitag
hpnapkgrcrpcspalgaipkthaceimhrp--sw------vdpcgahtm
paeysyl-----ltgntcrlggpeaaneipv-fnshrktqhkivyimdla
levskyqdgd----ng---vtl-----s----vhlhs-ktrgvratl---
--nlgyrkysgeg----lpvdscrcgikkgnaey---qkpka--npgnk-
------gctkdltsttddvs--------tchvfnytyhmympfpamadvs
wksqgykqscp--lvarlkkfpkgnpald------rydyecegyngkvkf
yggavnngptgdqfigatercgskgglgeqrlaeatdegcagvmlegqty
svg
>ENV_HV2D2/24-513
cgd---sggagggvvsrnkkdniklsrketvkgcafqtylaalkhanafl
skrkrfngesglsvsl---------tnagklrlvgafkcfgpwsagplsk
mcp----lggvd--hnelisqtprsahcsvegaslcevfyrvsyvakqls
kpl--sfgfrpdiliwgtnqttyahkgdycvslt------c--hg--nkg
lqggkspgedlkdslml---gseatsptlgssecaklqwnedwvnsitag
hpnalrgrckpcspgfgaipkthaceimhrp--sw------vdkvgtytm
paeysyl-----mtsnacqiggpeaandipv-fncnrptahkivyimela
levskyddgg----ng---ltl-----s----vhlhs-kfrgkrail---
--nlgyrknsghg----llvdscrcgikkgnatyellakpka--npgnk-
------gcvkdlsrttydqs--------tchvfnytyhmympfpaladvs
wknqgykqtcp-vmvarlnkfpkgnpaldaagsrirynyecegyngkvky
yggavnngptgdqfigatercgskgglgeqrlaeakdeacsgvimegesy
svg
>node14
cgd---sggagggvvsrnkkgkirlsrketvkacafqtylaalmhanahy
skrkrfnaesglavsl---------pnvgklrlvgafkcfgpw--nplsk
mcp----lgvvd--qnelitrtarpahcsvdgpslcevfyrvayvakelg
kpl--sfgyrptrltwgtnqttyehkgdycvalt------c--hg--kkg
lqggksdgatlrddlml---gsestgptlgsndcaklqwnedwvnsitag
hpnaskgrcrpcspalgaipkthaceimhrp--tw------vdpcgahtm
paeysyl-----ltgntcrlggpeaaneipv-fnshrktqhkivyymdla
lqvskyqdgd----ng---vtl-----s----vhlhs-ktrgvratl---
--nlgyrkysgeg----lpvdscrcgikkdnaey---qkpka--npgnk-
------gctndltsttddvs--------tchvfsytyhmympfpamadvs
wksqgykqscp--lvarlkkfpkgnpald------rydyecegyngkvkf
yggavnngptgdqfigatercgskgglaeqrlaeatdegcagvmlegqty
svg
>ENV_SIVM1/24-528
cgd---sggagggvvdrnskkki-------vkacayqtylealthanary
gkrkrfnvesglavsl---------tnvgklrlvgafkcfgpwsanpllk
mcp----lggvd--qnelitqtsrpkhcsvdgaslcevfyrvayvanqlg
nql--sfgfrptikpwgtnqttyehkgdyclslt------c--hg--kkg
lqsgksdgtkvcdsimlvsqgsegtgptlgssdcakfqwnedwvdsitag
kpdepkgrcrpcspslgsikkahtcevvhrp--sw------vdmcgshtk
paeysyl-----ltgetcqldgqeaaneipv-fnshrntqhkdvyimdlk
m----yqdgd----dg---val-----sgpavvhlht-ksrgvrttl---
--nlgypkysgeg----lamdscrsgikkgnaay---qkpka--spgnk-
------gctkdltsttndks--------tchvynytyhmylpfaaladvs
wksqgykqkcp--lvarlkkfpkgnpald------rynyecenyngkvky
yggavnngptgdqfigatercgskgglgyrrlgevvdescsgamlegqty
svg
>node10
cgd---sggagggvvsrnkkgkirlsrketvkacafqtylaalmhanahy
skrkrfnaesglavsl---------tnvgklrlvgafkcfgpwsanplsk
mcp----lggvd--qnelitqtarpahcsvdgaslcevfyrvayvakqlg
kpl--sfgfrptimtwgtnqttyehkgdycvslt------c--hg--kkg
lqggksdgatlrdslml---gsestgptlgssdcaklqwnedwvnsitag
hpnapkgrcrpcspglgaipkthaceimhrp--sw------vdkcgthtm
paeysyl-----ltgntcqlggpeaaneipv-fnshrktqhkivyimdla
levskyqdgd----ng---vtl-----s----vhlhs-ktrgvratl---
--nlgyrkysgeg----lpvdscrcgikkgnaey---qkpka--npgnk-
------gctkdltsttndqs--------tchvfnytyhmympfpaladvs
wksqgykqscp--lvarlkkfpkgnpald------rynyecegyngkvkf
yggavnngptgdqfigatercgskgglgeqrlaeatdegcsgvmlegqty
svg
>node11
cgd---sggagggvvsrnkkgkirlsrketvkacafqtylaalmhanahy
skrkrfnaesglavsl---------pnvgklrlvgafkcfgpw--nplsk
mcp----lgvvd--qnelitqtarpahcsvdgpslcevfyrvayvakelg
kpl--sfgfrptiltwgtnqttyehkgdycvslt------c--hg--kkg
lqggksdgatlrddlml---gsestgptlgsndcaklqwnedwvnsitag
hpnapkgrcrpcspalgaipkthaceimhrp--sw------vdpcgahtm
paeysyl-----ltgntcrlggpeaaneipv-fnshrktqhkivyimdla
levskyqdgd----ng---vtl-----s----vhlhs-ktrgvratl---
--nlgyrkysgeg----lpvdscrcgikkgnaey---qkpka--npgnk-
------gctkdltsttddvs--------tchvfnytyhmympfpamadvs
wksqgykqscp--lvarlkkfpkgnpald------rydyecegyngkvkf
yggavnngptgdqfigatercgskgglgeqrlaeatdegcagvmlegqty
svg
>node8
cgd---adgtsggvtsrnskgkvrlsrkstvkacpfrtyleelmhanarf
gkkkrfnvesglav-lknaaltrsapdegklkllatfkcfsswksnalkk
mcp----lsgae--qnqlitqtarpkhcspdghglcevsykvaylakhld
nrl--tfgfrtdvlawstnektykhkgdycvsltt----sc--hg--kkg
nqggkstgaklrdslml---ggdatnptlgshdcalfqwsedwvdsvtag
rpdapkgrcnpcsdslga-------eidqrp--sw------tdlcgvrti
eaaydylssqrtltgstcqlglpesayeirv-fgshr----------dlk
l----yhdgd----eg---vtg-----s----ihlht-klqgiraml---
--dlgyrkkseag----lplnacrcslkkgnaey---hkakg--npgsk-
------gcgktlesp---kg--------tcnvftytyhvylpfpaladvs
wlaqgyknkcp--lvarnkkdpkggpvln------ryeyecenydgkvky
yggavthgptcdqfigatqrcgskgglgyrrlpdatdngcsgvaleaqty
tvg
