>node9
gtvest-rsaqtianphwlakdkfalvrplingetkdggeiafavt----
drhadgclsglatpltgtsihfddckiy-arvkigtpanyvclqsavsrd
wglg-pgndmhvatqvgkrhm-fdcqe-nsd-----etqcveilkcrt--
-----hlplnpvallnpglfmcvv-kiqptkvcvaqgvfpa-gdyagsrr
vehdhsktvgiggvt-tadnamfppstrah--------ka---edskprq
qc--apiiph-------tqfhreerlrvf-rptlggqracckvgckvtah
pg--amhirgnpiiaavgalqqpcpcattellrnghakdt----------
---------rgylskgls------yqelsvctaggtkgva-lktgqpag-
-ygetneagtckalkpls-gltwkgskkfdgikllktn-kryfftflaka
ddvhescaalkislavg-cgkqnk----------------kgrstlqsal
pilll-aderpvgafk-----laasetvftklpstgekvacscqrkthik
ctacltiqsaecggpfhfgcyagdpatrla----------kggfptsrvy
gpkqs
>node17
gtgemt-rsaqtiaspnwlakgkfalvrplingetkdggeiafavt----
drhadgclsglatpltgssihfddckiy-arvkigtpalyvclqsnvsrd
wglg-pgndmhvasnvskrhm-fdcqe-tgdkpveyetqcvsilkcrt--
-----hlqlnpvallnpgllmcvv-kiqppqvcvvhgvfpa-gdyagsrr
adcdhsktvgiggvt-tadnamfppstrah--------ka---dksnprq
qc--apiipn-------tqihreerlrvf-rptlggqracckvgctvtah
pg--alhirgnpiiaavgalqqpcpcattelgrnghakdt----------
---------rgylskgls------yqelsvctsggtkgga-lkagqpgg-
-ygetneagtckakkplt-gltwkgskkydgikllktk-kryfftflaka
devhescaalkitlrvg-carqnk----------------kgrstlqsal
pilll-anerpvsafk-----iaasetaftklpstgekvacscqrkthik
ctacltiqgaecggpfhfgcyagdpathla----------kggfptsrvy
gpkqs
>node8
gtvqsg-rsgqpianehwmakekfalvgplingqsrdggeiafavp----
drsadgclsglatpltstsihfdncllv-arvdigdcgnfvclqsavsrd
wglg-pgndmhgatqvgerhm-fdchevntd-----ei-cvaivkcrv--
-----hlpesplalmrpglfmcgv-ktepkkiccaegvfpa-gdyegk-r
vehdhnktvgsgnvt-tydnpmfvpatrpd--------ka---dgtkprf
qc--ppiilh-------tqfhrdeklrvl-rplfgeqracckvgcpvtah
ag--amhvrgnpvvaavgalqqpcpcpt-ellrnghprdt----------
---------ygylskglsnla---yqelkvcaaggtravp-lktgnptg-
-ygasneagtckdlkplk-gltwkgskkfdginmlkvn-krffftflgrp
pdvhd-cplvkislaag-cgmqnk----------------kgrstlqnal
vplfl-advrpvgay------laasgtqftllpstgakvacgcqdkthvk
ctacltiqsaqcggafffgcyandpasraa----------kgafstsrvy
gpnqs
>node10
gtvest-rsaqtianphwlakgkfalvrplingetkdggeiafavt----
drhadgclsglatpltgtsihfddckiy-arvkigtpalyvclqsavsrd
wglg-pgndmhvatnvskrhm-fdcqe-tgd-----etqcvsilkcrt--
-----hlqlnpvallnpglfmcvv-kiqptkvcvvhgvfpa-gdyagsrr
aehdhsktvgiggvt-tadnamfppstrah--------ka---ekskprq
qc--apiipn-------tqihreerlrvf-rptlggqracckvgckvtah
pg--amhirgnpiiaavgalqqpcpcattellrnghakdt----------
---------rgylskgls------yqelsvctaggtkgva-lkagqpgg-
-ygetneagtckalkpls-gltwkgskkydgikllktn-kryfftflaka
ddvhescaalkislrvg-cgrqnk----------------kgrstlqsal
pilll-anerpvgafk-----laasetvftklpstgekvacscqrkthik
ctacltiqgaecggpfhfgcyagdpatrla----------kggfptsrvy
gpkqs
>ENV_SIVG1/22-522
gtiqeg-rsgqpiandhwmaktkfalvgplidgqsrgggeiafavp----
-rsaegclssiatsltstsihfdnclqv-arvdigdcanfvclqsavsre
wglg-pgndmhaatqpgekhm-fdchevnte-----ei-cvaivkcra--
-----hlpemplaplrpglfmcgv-kteprkiccaegvfpaygdyegk-r
vehdhnktvgsgnvt-ttdnplfvpatrpd--------macvcegpkprf
qc--ppiilh-------tqihrderlrvl-rplygkqkacckvg------
------hvrgnpvvaavgalqqacpcpk-ellrkshprdt----------
---------ygylskelndlagdeyqeikvcvgggtrsvp-lkvgnptg-
-ygashgaggckdlkplqmgliwkgskkfdginmlkvddkrfffsflgk-
------cvlvtislsag-cgmqnksdaeaqfepccelasskgratlqkpl
vplfl-advrpvgay------laasgtqfsllpstggkvacgcqdktnvk
ctaclkiqseqcggafffgcypndpackaa----------kgafstsrvy
gpnqs
>ENV_HV2NZ/24-502
gtgemt-rsahtiaspkwlakgkfalvrplingetkdggeiafavt----
drhavgclsglatpltgssihfddckiy-arvkigtqp-yvclrsnvsrk
wglg-pgndfhvasnvskrhm-fdcqe-tgdtpveyetqcvmvlkcrt--
-----hlqlnpvallnpgllmcvv-kvqppqvcv--------gdyagsrr
tdcdhsktvgiggvt-tadnamfppssran--------ka---dkanprq
qccrapiipn-------tqi-redglrtf-rptlagqracckvgckvtar
nh--alhirgnpiiaavgalq-----attslgrnghaktt----------
---------rgylskglr------yqelsvctsggtkgga-lkagqpgg-
-ygetveagtckakkplt-dltwkgskkydgikllktk-kryfftflata
devhescaalkitlrvg-carqnk----------------kgrstlqsal
pilll-aneqpispfk-----iaasetafvklkstgekvacscqrkfhvk
ctacltiqg---ggpfhfgcyagdpsthlt----------kggfptsrvy
gpkps
>node14
gtgemt-rsaqtiahpnwlakgkfalvrplingetkdggeisfavt----
drhadgclsglatpltgssihfddckiy-arvkigtpalyvclqsnvskd
wglg-pgnkmhvasnvskrhm-fdcqe-tgdkpveyetqcvsilkcrt--
-----hlqlnpvallnpgllmcvv-kvqppqvcvihgvfpa-gdyagsrr
adcdhsktvgiggvs-tadsamfspstrah--------ka---eksnprq
ec--apiipn-------tqihreerlrvf-rptlgglracckvgckvtah
pg--alhirgnpiiaavgalqqpcpcattellrnshakdt----------
---------pgylskgls------yqelsvctaggtkgva-lkagqpgg-
-ygetneagtckakkplt-gltwkgskkydgikllktk-kryfftflak-
-evhescaalkislrvg-carqnk----------------karstlqsal
pilll-akerpvgafk-----iaasetvftklpstgekvacscqrkthik
ctacltiqgaecggpfhfgcyagdpatgla----------kggfptsrvy
gpkqs
>ENV_SIVGB/47-569
stntva-rssdqivnkhslavqdfpgasplihaegrdggevgyavp----
gktdggclrgianalvgtnthflnpmli-ervdvpdvadfgclqravsrd
weisllgdqmcgftpvtiaqlvfvchrlwtd-----ei-cvaftkrkmrd
liipydlpelplkqhapvlfmnggqktkpak---psgahpa-----gk-r
aehehaksvgnthiskksdphmfvsaarpdckdqmyaddp---evtknkf
nc--gppilhwhqakwysqfqrdenlqll-qpqfgeikeycsvgcpdte-
-g--alhvrskplitaigqimqpcpcve-dllmdgnpyettigstpqlei
rapagadvkystlskglnnma---yqelevcnaggtrgip-iagggptc-
-dgpsaptgtctdtkslk-kalwkgsk-ydgiylekin-krlfiaflgrp
pqvnd-cplvkislaeg-ctqqdk----------------kgksslqkam
valfi-aevkp---------------tqfglldllqanidcnaedkahin
kstcasvhdiqc----yflcytyqpaar-----------------ta-qy
sptks
>ENV_HV2BE/24-510
gtgemt-rgaqtiahpnwlakgkfalvrphltgetkdggeasfavs----
drhadgclsglatpltgvsqhfddckiy-arvkiatpalyvclqskvrkd
wglg-pgnkmhvasnvskrhm-fdcqe-tgdkpvehethcvsilkckt--
-----hlqlnpvallnagllmcvv-kaqppqicvihavfps-gdyagsrr
ascdhsktvgvggvs-tadpamfnascrah--------kf---ekaeprq
ec--apiipn-------tqehreerlrvf-rptlgglracckvgckvtah
pg--alhirgnpiiaavgalqqpcpcattellrnshakdt----------
---------pvalsagls------yqqlsvctaggtlgva-lkagqpgg-
-ygdtneagtckakkplt-gltwkgskkydglkllkak-kryffnflak-
-evhescaalkislrvg-ctrqnk----------------karstlrsal
pilll-akarpvgafk-----iaasetvftslpstgekvacscqrkthik
ctacltiqg--cggpfhfgcyagdpatgla----------kggfpasqvy
gpkqs
>ENV_SIVV1/24-538
gaiqpgdrngqpiindhwlarwkfglisplid---kdggeiafavp----
drsadgclstlatpltspsisfddavlv-prvdigrcgificlpsavsrd
wglg-pgndmhaatqpaerhm-ldchevnte-----ei-cinivkcha--
-----hlpelplalkrpglfmcgi-ktepkkiccaggvhka-gdyegk-r
aehdhsktvgsgnvt-tydntffvpatrqd--------ta---dgtktrf
qi--apivlh-------tqihpdhklrvlgrplfgkpkacctvgcgvvgh
as--amhvkg--vvaavg-----cacpv-ellknshprd-----------
---------ygylskglndlagneyqevkvcaaggsravp-lktgnptg-
-yga-hgaggckelkplqmgl-wkgsksfdginilkvhvkrfffsflgrp
pdvha-ciivaislaag-cgmqtkasantqfepvcdlasskgrstlespl
vplflradvrpvgay------laasaaqfsllpstggmvacgcnkksnvk
ctacltiqsaqcgeafffgcypnnracnaa----------kdafstssvy
gpnqs
>node19
gtgemt-rsaqtianpnwlakgkfalvrplingetkdggeiafavt----
drhadgclsglatpltgssihfddckiy-arvkigtpalyvclqsnvsrd
wglg-pgndmhvasnvskrhm-fdcqe-tgdkpveyetqcvsilkcrt--
-----hlqlnpvallnpgllmcvv-kiqppqvcvvhgvfpa-gdyagsrr
adcdhsktvgiggvt-tadnamfppstrah--------ka---eksnprq
qc--apiipn-------tqihreerlrvf-rptlggqracckvgckvtah
pg--alhirgnpiiaavgalqqpcpcattellrnghakdt----------
---------rgylskgls------yqelsvctaggtkgva-lkagqpgg-
-ygetneagtckalkplt-gltwkgskkydgikllktk-kryfftflaka
devhescaalkislrvg-carqnk----------------kgrstlqsal
pilll-anerpvgafk-----iaasetvftklpstgekvacscqrkthik
ctacltiqgaecggpfhfgcyagdpathla----------kggfptsrvy
gpkqs
>node18
gtgemt-rsaqtianpnwlakgkfalvrplingetkdggeiafavt----
drhadgclsglatpltgssihfddckiy-arvkigtpalyvclqsnvsrd
wglg-pgndmhvasnvskrhm-fdcqe-tgdkpveyetqcvsilkcrt--
-----hlqlnpvallnpgllmcvv-kiqppqvcvvhgvfpa-gdyagsrr
adcdhsktvgiggvt-tadnamfppstrah--------ka---eksnprq
qc--apiipn-------tqihreerlrvf-rptlggqracckvgckvtah
pg--alhirgnpiiaavgalqqpcpcattellrnghakdt----------
---------rgylskgls------yqelsvctaggtkgva-lkagqpgg-
-ygetneagtckakkplt-gltwkgskkydgikllktk-kryfftflaka
devhescaalkislrvg-carqnk----------------kgrstlqsal
pilll-anerpvgafk-----iaasetvftklpstgekvacscqrkthik
ctacltiqgaecggpfhfgcyagdpathla----------kggfptsrvy
gpkqs
>ENV_HV2G1/23-502
gtgemt-rsaqtisnpnwlakgkfalirplidgetkdggeiafavt----
drhadgcltglatpltgssihfddckly-arvkigtpalyvcpqsavsrd
wglg-pgndmevasnvskrym-fdcre-tgekpveyetqcvsilkcrv--
-----hlqlnpvallnpgllmcvv-kiqppqvcvvhgvfpa-gdyagsrr
adcdhsktvgipgvt-tadnamfppstrth--------ka---eksnprq
qc--gpiipn-------pqihreerlrif-rptlggqraccklgckvtsh
pg--alhikgnpiiaavgalqqpcpcattellrngnakdt----------
---------rgylskgls------yqelsvctaggtkgva-lkagqpgg-
-ygetneagtckelkpls-glswkgskrydgikllktk-kryfftflgka
sevhescaalnislrvg-cgkqnk----------------kgrstlqsal
pilll-ankrpvgafk-----akasetvftklpstgekvacacqrkthvk
ctaclniqgaecggpfhfgcysmdpathla----------kgghpssrvy
gpkqs
>ENV_HV2D2/24-513
gtvest-rsaqtianphwlakakfalvrplingetkdggqiifavk----
drhadgclaglaaplsitaihfddckiy-rrakigtpamyvclqslvsrd
wklg-pgddmhvstnvskrhm-fncde-tgd-----etncvsilkcki--
-----nlqlnvvallnpglfmcvv-kiqptivcvvhgvfvq-gdysgsrr
adhdhsktagiggvt-tadnamfppstrkh--------ka---ekekprq
qc--spiipn-------tgihreerlkvf-rstlagrr-cckvgckvtah
pg--amhirgnpiiatfgalhqpcpcattellrn---kdt----------
---------rgylcsgls------yqelsvcrspgtkgvaqlkagnpgg-
-ygatnepgtckalspls-gltwkgskkydgikllktn-kryffaflakc
ddvhescaslkislrvgecarqnk----------------kgrsmlqsal
pilll-ansrpvgafq-----faasetvftklpstgekvacscqrkthlk
ctacltiqgancgepfhfgcyaadpatpiagydlhleqfnkggfttsrvy
gpkqs
>ENV_HV2D1/24-501
gtgemt-rsaqaiaqpnwlakgkfalvrplingetkdgneisfavt----
erhadgclsglatpltgssihyddckiy-arvsigtpamyvclqsdvskd
wglg-pgnkmhvasnvskrhm-fqcqe-tgdkpveyetqcvsllkcrt--
-----hlelnpvallnpgllmcva-kvqrpqvcvvhlvfpa-gdylgsrr
ddcdhsstvgiggvs-tadsamfspstrah--------ka---eksnprq
ec--apiipn-------tqihree-------ptlgglyacckvgckvkah
pg--alhirgnpvisaagalrqpcpcattellrdshakdt----------
---------egylskglt------yqelsvctaggtkgva-lkagqpgg-
-ygetneagtckakkplt-gltwkgskkydgikllktk-kryfftflak-
-evhesctalkislrvg-carqnk----------------karstlqsal
pilll-tkerpvglvkltsaginasetvftdlpstgekvactcdrkthik
ctacltiqgaecggpfhfgcyagdpssgla----------kggfptsqvy
gpkqs
>ENV_HV2CA/25-512
gtgemt-rspqtraspnwlakgkfvlvrplingetkdggevafavtdlid
drhadgclsglatpltgsdihfddckiy-arvkigtpalyvclqlnvsrd
wglg-pgndmhvasevskghm-fdcqe-tgekpie-evqcvsilkskt--
-----hlqlnpvallkpgllmcit-kihppqvcvvhgvfpa-gdyagsrr
adcdhnktvdiggvt-tadnamfspssrah--------ka---dksnprq
qc--ssiipn-------tqihreerlrvf-rptlggqracckvgctvtah
pgalalhmrgnpiiaavgaleepcpcattelgrnghpkdt----------
---------rgylakgin------yqelsvctfggtksgh-lkagqpgg-
-ygetneagtckakkplt-gltrkgskkydgiklnksk-kryfytflaka
ddvhescaalkitlrvg-carenk----------------kgrsklqsal
pilll-anerpvsafk-----iastdtaftqlpstgdkvacs-qrkthiq
ctacltiqgaecggsfhfgcyagdpatqla----------kggfptshiy
gpkqs
>node11
gtgemt-rsaqtianpnwlakgkfalvrplingetkdggeiafavt----
drhadgclsglatpltgssihfddckiy-arvkigtpalyvclqsavsrd
wglg-pgndmhvasnvskrhm-fdcqe-tgdkpveyetqcvsilkcrt--
-----hlqlnpvallnpgllmcvv-kiqppqvcvvhgvfpa-gdyagsrr
adcdhsktvgiggvt-tadnamfppstrah--------ka---eksnprq
qc--apiipn-------tqihreerlrvf-rptlggqracckvgckvtah
pg--alhirgnpiiaavgalqqpcpcattellrnghakdt----------
---------rgylskgls------yqelsvctaggtkgva-lkagqpgg-
-ygetneagtckalkpls-gltwkgskkydgikllktk-kryfftflaka
devhescaalkislrvg-cgrqnk----------------kgrstlqsal
pilll-anerpvgafk-----iaasetvftklpstgekvacscqrkthik
ctacltiqgaecggpfhfgcyagdpathla----------kggfptsrvy
gpkqs
>node7
gaiqeg-rsgqpiandhwmaknkfalvgplidgqsrdggeiafavp----
drsadgclsslatpltstsihfdncllv-arvdigdcgnfvclqsavsrd
wglg-pgndmhaatqpgerhm-fdchevntd-----ei-cvaivkcra--
-----hlpelplalmrpglfmcgv-ktepkkiccaegvfpa-gdyegk-r
vehdhnktvgsgnvt-tydnplfvpatrpd--------ma---dgtkprf
qc--ppiilh-------tqihrdeklrvl-rplfgkqkacckvgcpvtvh
as--amhvrgnpvvaavgalqqacpcpv-ellrnshprdt----------
---------ygylskglndlagneyqeikvcaaggtravp-lktgnptg-
-ygashgaggckdlkplqmgltwkgskkfdginmlkvndkrfffsflgrp
pdvhd-cilvtislsag-cgmqnksdaetqfepccelasskgratlqkpl
vplfl-advrpvgay------laasgtqfsllpstggkvacgcqdktnvk
ctacltiqsaqcggafffgcypndpackaa----------kgafstsrvy
gpnqs
>ENV_SIVM1/24-528
gtvest-rsaqtidnphwlardkfavvrplingetkdggeiafavt----
drhadgclhglaipltgtsihfe---iydarvkigtpanyvclksavsrd
wglg-pgnnmhvseqlgkrqm-fdcqe-tsd-----dtqcveilkcrt--
-----hlplnpvallnsgvfmcvv-kiqptkvcmaqgvfpa-gdyagsrr
vehdhsktvgigavt-taenamfppssrah--------ka---edqkprq
qc--apiith-------tqfhrearlrvf-rptlggqracckvgckvtah
pg--amhirgnpiiaavgalqqpcpcattellrnghakdt----------
---------rgtlrkgls------yqdlaictaggtkvva-lktgqpagg
sygesneagtckalkqls-gltwkgskkfegvqllktn-kryfftflakt
ddvhescaalklslaig-cgkqnn----------------kgrstlqsal
pvlll-aderpvgafk-----laasevvftklpsagekvacscqkkthik
csacltiqsaecggpfhftcyagdaaarla----------kggfptsrly
gpkqs
