>node9
etgvsasnsfa---nitrapptsggkqkmdtvpplgaas--hhdwgynad
ctscplgedvpltllhgralttpavkrnsattnpkdpecisai---keyv
cktls----------ltgsfkmvkekmydfy----atitpkeesrnaapr
lkakg--lyfhgcq-lavapysfvsa-----dtpvtnstvnklpktckaa
hdg--tnwsren--svplinqnkc----yrkegvltigaa-tdeltapai
agspgldgkdqitrrhepqtttiktwvhgtshadnrnhga----lcqsgg
vknlgiflqeeanhffnlltryal-aidqlkdgla------qeapkldgs
----kt-kdsqaaggcgpi-------rlpvwghqsnhawlsiggsahvgd
nlgarlgawcardwtkctvnarltv----sqvresfngdkvart--f---
lksdlrcyypklqflgdcpapp---thqdfysttekgegspfrr-dkkdh
smlvfpe---kedfrtkeweepagdsfrvvvl--lal-------rh-dgs
gcvt---stggiqvvvhetakyevgkt-scllkelavef---d
>node7
enga--snsfa---nitgaprtkggkqkmttvppegassvynhawgf-tn
cnkcplikdiplalfhgralstpaikrerarsnpkdnecfspv---knfa
cktst----------leasfkmikekfldfyaahgadikpkeettdaplr
akakg-----hgcd-lhiapytfssa----kgsptthssqskftktcnqs
h-s--tnwsrvk--svplidqnkc----ymkegrltiaapekdtlsapai
aanpglgskdritrrh----saskgwlhgtshtenenhga----lcntgg
lknlgif---sgnhffdllskygl-aieqlreglapkkgt-aeapkldss
----gt-ndshaaahcgri-------rlpvrghqakdawlpingsqhage
hig-klgawcrdtwdkctsdarlavkl--sqilelfesdkvars--f---
lknslrayyqklqllgdcggtp---ehhdfysttekgdgasfsrcdkkdh
gmiv-------aayrskdwdepagnsyrvvvl--ahyenpdktmkh-ngg
gcit---etggitvvthatakynvglt-scllkvlavef---e
>node10
etgvsasnsfa---nitrapptsggkqkmdtvtplgaas--hhnwgysad
ctscplgedvplallhgrplttpavkrntattnpkdpecisai---keyv
cktls----------lpgsfkmvkekmydfy----atitpkeesrnaapr
lkakg--lyfhgcq-lavapysfvsg-----dtpvtnstvnklpktckaa
hdg--tswsren--svplinqnkc----yrkegvitigaa-tdeltspai
agspgldgkdqiskrhppqtttiktwvhgtshadnrnhga----lcqsgg
vknlgiflqdeg-hffnlltryal-aidqlkegla------qeapklegs
----kt-kdsqvaggcgpi-------rlpvwghdsnhawlsiggsahvgd
nlgarlgawcardwtkctvnarltv----sqvrdsfngdkvart--fmrl
lksdlrcyypklqflgdcpapp---thqdfysttekgegspfrr-dkken
smlvfpg---kedfrtgeweepagdsfrvvvl--lal-------rh-dgs
gcvt---stggcqvvvhetakyevgkt-scllkelavef---d
>ENV_HV2CA/25-512
etgcsasnsfa---nitrapptsggkqkmdtktplgaas--hhnwgyssd
ctscplgedvplellhgrpltapsvkrntatthpkdpesisai---keyv
cktls----------lpgsfkmvkekmfefy----ttltrkeetk-agpr
lkakgvklyfhgcq-lptapysfvsg-----dtpvknstvkklpktcnaa
hdgcavsrgren--svplikqnkc----yrkegvvtigal-tdeltspai
agtpgldtkeqirkqhppqtttinnwahgvshadnrnhga----lcqsgg
vkkldiflntqg-halnlltryal-tidqlkegla------eeapkless
----kt-mesqgaggcgpi-------rlpvwghdsnhawlsiggs-----
--garlgawcardwtkctvnarltv----sqvresvksdklsrk--fmkl
lksdlrcyygklgfladcpsvp---thenfystpdegeaspfrr-dkken
smlvfpg---kedfrtgewedpagdtfrvvvl--lal-------eh-ggs
gcvq---stggcqvvvhesakyevgkt-scllkelaief---d
>ENV_HV2G1/23-502
qtgvsasksfa---nitrappvsggkq----vtplgaas--hhnwgysad
ctncplgedvplellhgrplntpsvkrntasthpkdpecisvi---keyv
cktlt----------lpgsfkmvkrkmydfy----stltekeesknagpr
lkakg--lyfhgcq-lpvapysfvsg-----stptthstvnklaktckan
hdg--tgrgren--svplinqnac----yrkegvitigaa-wdeltspai
agspgldtkeqiskrnppqtttintwahgtshadnrnhga----lcqsgg
vknlgiflqshg-hffnlltryal-tidqlkegla------qeapklegs
----kt-aesqvaggcgpi-------rlpvwghdsnhawlsiggsphvgd
slgarlgawcardwtnctvnarltv----srvrdsfngdkvart--fmrl
lksnlrsyypnlqflgdcpspp---thadfysttekgegspfrr-kkken
smlvipg---kedfrtgdweepagdsfrtvvl--laq-------kh-dgs
gcvt---stggcqvvvhetakyevgkt-sylikelavdf---d
>node18
etgvsasnsfa---nitrapptsggkqkmdtvtplgaas--hhnwgysad
ctscplgedvplellhgrplttpsvkrntatthpkdpecisai---keyv
cktls----------lpgsfkmvkekmyefy----stltpkeesknagpr
lkakg--lyfhgcq-lpvapysfvsg-----dtpvtnstvnklpktckaa
hdg--tswgren--svplinqnkc----yrkegvitigaa-tdeltspai
agspgldtkeqiskrhppqtttintwahgtshadnrnhga----lcqsgg
vknlgiflqseg-hffnlltryal-tidqlkegla------qeapklegs
----kt-mesqvaggcgpi-------rlpvwghdsnhawlsiggsphvgd
slgarlgawcardwtkctvnarltv----sqvresfngdkvart--fmrl
lksdlrcyypklqflgdcpspp---thqdfysttekgeaspfrr-dkken
smlvfpg---kedfrtgeweepagdsfrvvvl--lal-------kh-dgs
gcvt---stggcqvvvhetakyevgkt-scllkelavef---d
>node17
etgvsasnsfa---nitrapptsggkqkmdtvtplgaas--hhnwgysad
ctscplgedvplellhgrplttpsvkrntatthpkdpecisai---keyv
cktls----------lpgsfkmvkekmfefy----stltpkeeaknagpr
lkakgvklyfhgcq-lpvapysfvsg-----dtpvtnstvnklpktckaa
hdg--tswgren--svplinqnkc----yrkegvitigaa-tdeltspai
agtpgldtkeqivkrhppqtttintwahgtshadnrnhga----lcqsgg
vknlgiflqseg-hffnlltryal-tidqlkegla------qeapklegs
----kt-mesqvaggcgpi-------rlpvwghdsnhawlsiggsphvgd
slgarlgawcardwtkctvnarltv----sqvresfngdkvart--fmkl
lksdlrcyypklqflgdcpspp---thqnfystteegeaspfrr-dkken
smlvfpg---kedfrtgeweepagdsfrvvvl--lal-------kh-dgs
gcvt---stggcqvvvhetakyevgkt-scllkelavef---d
>ENV_HV2BE/24-510
etgvaasnsfp---gitrapptsggkqkldtvtplglas--hhdwgysad
ctscplgedirlalehgrpltspsvkrntatthpkepecisai---keyv
cktls----------lpgsfnmvkekmyefy----stltpkeesknpgpr
lkamg--lffygcq-lpvatysfvsgpkcg-dtpatnstvnklpkackaa
hdg--aswgren--svplinqnkc----yrkegtimigaa-tdeltspai
agspgvdtkeqiskrhppqtttidtwahgtshadprnhga----lcqsgg
gknlgiflqseg-pffnlltrytl-sidqlkegla------deapklegs
----kt-mesnvsggcgpp-------rlpawghdsnhpwmsiggsphvgd
slgarlgawcardwttctvngrltv----tqvresfngdkvart--fmrl
lksdlrcyypklhflgdcpsgp---thqdfysttekgsasrfrr-dkken
smlvfpg---kedfrtgeweepasdsfrvval--lal-------kh-dgs
gcvt---skggcqvvvheqakyevgks-scllkelaief---n
>ENV_HV2NZ/24-502
etgvsasnswa---nitrappttggkqkmntvtplgvas--hhnwgysad
ctscplpedvplellrgrplttpsvnrntattqpkdpecisai---siyv
cktls----------lpgsfkklkemmfefy----stltpkeeaknagpr
lkakgvklyfhgcq-lpvapysfvsg-----dapvtnstvnklpktckaa
hdg--tswgres--svplinqnkc----yrkdgtikigav-tdevtspai
agtpgldtkepivkrhnpqtttintwahgtahtddrnhga----lcqsga
vknhaiflqspg-hffelltryal-tidqlkegla------qeapklegs
----kn-mesevaggcgpi-------rlpvwghdsnhawlsvggsphvgd
slgarlkawcardwtkctlnarltv----sqvresfngdqvart--fmkh
lksdlrcyypklqflgecpspp---tvqnfysateegevspfrr-dkken
smlvfpg---kedhrtgeweepagdslravvl--lal-------kh-dgs
gpvt---stggcqgvihetakyevgkt-scllkelavdf---d
>node8
engaqvsnsfa---nitkaprtkggkqkmatvppegassvynhdwgy-an
cnkcplgkdvpltlfhgralstpaikrerartdpkdnecispv---kefv
cktat----------leasfkmikekflkfyaahgaditpkeettdaplr
lkakg-----hgcd-laiapytfssa----kgsptthssqskftktcnqa
h-s--tnwsren--svplidqnkc----ymkegrltigapqketltapai
agnpglggkdqitrrh----saikswlhgtshtenqnhga----lcqtgg
lknlgif---ganhffdlltkygl-aieqlreglapkkgt-aeapkldss
----gt-ndshaaggcgri-------rlpvrghqsthswlpingsahagd
nlg-klgawcsdtwdkctsdarlsvkl--sqilesfdgdkvart--f---
lknelrayytklqflgdcggpp---thhdfysttekgdgasfsrcdkkdh
gmlv-------eafrskdwdepagnsyrvivl--apyenpdktmkh-ngg
gcit---ntggipvvmhatakynvglt-scllkllavef---e
>ENV_SIVG1/22-522
enga--snsfa---nitgaprtkggkqkmttvpaegassvynhawgf-tn
cnkctlikdiplalfhgralstpaikrerarsnpkdnecftpv---knfa
cktsi----------leasykmtkekfldfyaahgadikpkeettdaplr
akskg-----pgcd-lhiapyafssa----kggptthssqskftktcnns
h-t--tswsrvk--svplidknkc----ymkegrltiagpakdtlsapsi
aanpglgskdritrrh----saskgwlhgtshtenenhga----lcntgg
lknlgif---sgnhffdllskygl-aieqlreglapkkgt-aeapkldss
----gt-kdshaaahcgqi-------wlpvkghqakdawlpihgsqkage
hig-klgarcrdtwdsctsdarlavkl--sqvlelfesdkvars--f---
lknslrayyqklqllgdcggtp---ehhefysttekgdgasfsrcdkkdh
gmiv-------aayrskdwderagnsyrvval--ahydnpiktmkhengg
gcitnt-etggitvvihftakynvglt-scllkvlavef---e
>node19
etgvsasnsfa---nitrapptsggkqkmdtvtplgaas--hhnwgysad
ctscplgedvplellhgrplttpsvkrntatthpkdpecisai---keyv
cktls----------lpgsfkmvkekmyefy----stltpkeesknagpr
lkakg--lyfhgcq-lpvapysfvsg-----dtpvtnstvnklpktckaa
hdg--tswgren--svplinqnkc----yrkegvitigaa-tdeltspai
agspgldtkeqiskrhppqtttintwahgtshadnrnhga----lcqsgg
vknlgiflqseg-hffnlltryal-tidqlkegla------qeapklegs
----kt-mesqvaggcgpi-------rlpvwghdsnhawlsiggsphvgd
slgarlgawcardwtkctvnarltv----sqvresfngdkvart--fmrl
lksdlrcyypklqflgdcpspp---thqdfysttekgeaspfrr-dkken
smlvfpg---kedfrtgeweepagdsfrvvvl--lal-------kh-dgs
gcvt---stggcqvvvhetakyevgkt-scllkelavef---d
>ENV_SIVV1/24-538
engv-----hd---niagaprtkggkqkmstvppegaasvyhkawgf-th
cnkcplskevllsllngrplstpaikrerarvnpkgnscfspv---knfa
cktsa----------nenslkmmdekfldfyaaqgadikpkeetddaplr
gkakg-----ngcd-lhfacytfsaa----rgspithskeskftktcdqs
h-s--tnwkrvk--slsligqnkc----ymkegrlgiaapekdtlndpai
aadpglgskdritrrh----saskgwlh-tshaenqnhgl----lcntgg
lknlg---------ffdllsksgl-aieqlreglspkkgt-atapklqss
----gt-ndsqasahc----------tlhvrghqaksawlpikgtqhggg
qig-klgawcrdtwdkctsdarlagkl--sqilelwesdkver-------
lkndlkgyy--lqllgecggtm---ehhefhratekgdgarfsrcnkkdh
amiv-------aaykskdwddpagnsyrvvvl--ahyenpdkttne-ngg
gcit---enggitv-thpvaky----t-dcllrvlavef---e
>node11
etgvsasnsfa---nitrapptsggkqkmdtvtplgaas--hhnwgysad
ctscplgedvplellhgrplttpsvkrntatthpkdpecisai---keyv
cktls----------lpgsfkmvkekmydfy----stltpkeesknagpr
lkakg--lyfhgcq-lpvapysfvsg-----dtpvtnstvnklpktckaa
hdg--tswgren--svplinqnkc----yrkegvitigaa-tdeltspai
agspgldtkeqiskrhppqtttintwahgtshadnrnhga----lcqsgg
vknlgiflqseg-hffnlltryal-tidqlkegla------qeapklegs
----kt-mesqvaggcgpi-------rlpvwghdsnhawlsiggsphvgd
slgarlgawcardwtkctvnarltv----sqvrdsfngdkvart--fmrl
lksdlrcyypklqflgdcpspp---thqdfysttekgegspfrr-dkken
smlvfpg---kedfrtgeweepagdsfrvvvl--lal-------kh-dgs
gcvt---stggcqvvvhetakyevgkt-scllkelavef---d
>ENV_HV2D1/24-501
etgvsasssfa---gitrapptsggkqkmdtvtplgaas--hhnwgygad
ctscplgedvpldlghgrplttpsvkrntatthpkdpecisai---keyv
cktms----------lpgsfkivkeklyefv----stltpkdesknagpr
lkakg--lyfhgcq-lpvatysfvsgpkcg-dtpatnstvnkepktckaa
hdg--tswgren--svplinqdkc----lrkegiitigaa-tgeltspsi
agsrgvaakekiskrhppqtttintwahgtshadyrnhga----lcqsgf
vknlgiflqseg-hffnlvtrytk-tidqlkngla------qeapklegs
----kt-mesqiaggcgpi-------llpvwghgsnhpw-----sphvgd
slgarmgawcardwtkctvdgrltv----sqvrqsfngdkvert--fmrl
lksdlrcyypklpflddcpspp---thqdfysttekgnaspfrr-dkken
smlvypgepnkedfrtgeweepagdsirvvvl--lal-------kh-dgs
gcvi---stggcqvvvhetakyevgkt-scllkelavaf---n
>node14
etgvsasnsfa---gitrapptsggkqkmdtvtplgaas--hhnwgysad
ctscplgedvplelehgrplttpsvkrntatthpkdpecisai---keyv
cktls----------lpgsfkmvkekmyefy----stltpkeesknagpr
lkakg--lyfhgcq-lpvatysfvsgpkcg-dtpatnstvnklpktckaa
hdg--tswgren--svplinqnkc----yrkegvitigaa-tdeltspai
agspgvdtkeqiskrhppqtttintwahgtshadnrnhga----lcqsgg
vknlgiflqseg-hffnlltrytl-tidqlkegla------qeapklegs
----kt-mesqvaggcgpi-------rlpvwghdsnhpwlsiggsphvgd
slgarlgawcardwtkctvngrltv----sqvresfngdkvart--fmrl
lksdlrcyypklqflgdcpspp---thqdfysttekgnaspfrr-dkken
smlvfpg---kedfrtgeweepagdsfrvvvl--lal-------kh-dgs
gcvt---stggcqvvvhetakyevgkt-scllkelavef---n
>ENV_SIVM1/24-528
ttgvsasnnha---nitrapppaggkqkmdtvpplgaas--hhdwgynsd
ckscrlgedvpltllhgrrlttpavkrdgattnpkdpecipai---keyv
ckals----------ltgsfklvkekmydfy----atitpkeesrkaapr
lkakg--lyfhgcq-lavapysfvsa-----dtpltnptvnslgktckaa
sdg--tnwsres--svpki--nkc----krkegvltigaa-tdeltapam
agspgldgknqifrrhepatttirtwvhgt----nrnhga----lcqaga
vknlgtfiqeeanhffnlltryal-ridqlkdgla------qeapkldgs
----ks-kdsqaaggcgpi-------klpvwghqsnhawlsiggsahvgd
nlgarlgawcgrdwskctvnarltv----sqaresfngdkvvrt--f---
lksdlrcyypklqfsgdcpapp---thqdfysttekgegspfrr-dkkdh
sqlvfpe---redfrtkaweepagdsfrvvvl--lal-------rh-dga
nyva---stggiqvvvhetakyevgkt-icllkemavef---g
>ENV_HV2D2/24-513
etgisdnnsfa---gitrapptsggkqkmdtvtplgaas--hhkwgysad
cincplgedvplallegrpsttpavkrntartnpsepecisav---keyv
cktls----------lpasfkmvkekmydwy----asitpkeesrnaspr
ikakg--lyfhgcr-lavgpysivsa-----ktpvtnstvnkipktcdha
hds--tswsken--slplinqdkc----yrkegvfsigak-ydeltslai
agspglsgkdqlskrhppqtttiktwvhgtshaqnrnhga----lcqsgg
iknlgifmqdes-hffnlltryal-sidqvkegla------qeapklegs
----kt-kdsqtaggcgpi-------rlpvwghdsnhtwlsiggsarvgd
nlgaklgawcardwtkctlnarltv----sqvrdsfsgdkvara--fmrl
lksdlrcyypklqflgdcpappcyathqdfysttdkgegspfrr-nkken
smlviag---kedfrtgeweepvgksfrvvvqiglal-------rh-dgs
gcvt---stggcqvvvhepakyevakt-scllkdlavef---n
>ENV_SIVGB/47-569
ttgakmatkfclspnlakgpstksgklklptvpcvsggda------y-cn
clkcplgkdvpltlflgrelsaaqiarsriradkkg--crqpvhplkeya
cksasiaglggtgeklasaakslkqkylqsfatnpaeitpkaattetplh
nlsta-----hgcdglaiapyalsaa----asgptthvqeaayek----l
a-g--rewgrawsmsveiindsicgesynkkeghltigapqvkyvtartv
agdgdlgaktqitrkt----sdvktwlpavsdtqeaeqaaacrklcspgg
lqnmaaf---ganhffdllssyglkvltqlrdslapskgtsaeippvesa
tvdagsgnnihakggcahidqtnvasalplkahesgqkfvtisgskhtgd
dlg-nlgnwc-dawdkcaadlklflkyceaqilesfeg--vsrigif---
lkss-rgyytrlqfvgqcgkpp---thhqlygssdkghgvnfsrcgrmnh
allf-------etykgkdwdqkag--yqviil--tphenpnkslkq-dgs
dcfa--eetgglpagfd--nqydvgwaesglfsmlcidftgre
