>ENV_HV2D2/24-513
hseckkpqgcq---klqkydsrgdvyalflcgpgpqqlrdcgfsltwdns
ltrfdlevlsalae---sfylhyklekaaqlat---glktagkaqktvnh
dti--------------dpgatnlgcngy------aglht-cn-------
----lptikaf----agrgefpvaasnlesaml---gssavaatvkethd
k---ldfklaskeke----elehehitkrigktrll---darddhke---
vgpknldrfpwlqyykvvnnirhingiilkenpltfdivlrwlvlngsav
ykaisdgvke-k-sphhtyitqgiaadkgvslmlglvatkhcrslyggsd
gg---ggghqkartetdgegae---------qlrpqd-----kcecgcvc
hckrehatvpgwfhdtplwg-----ntadgvitlpkgapgtesctn---h
vtvfv-----------gsshgh--------rvayighvninlanlvgiyg
yrk--ipsshgqtfnkrgh--k----gkl-------------eqtlggv-
qcslltaannkhggahfe-cl---------fglpekghs-mlmadsrgdp
aaapktegkarfeaihgvyfk
>ENV_HV2G1/23-502
hevtkkgqgcq---klqkydsrggvfalflcgp--qhlrdhgyslcwdhs
ftrldlevlkalne---pfylhfkllkaaelaa---glkypgkaqktvnh
dvk--------------dpgatdlgcngy------aglht-ct-------
----lptvkaf----tgrgefpvaatnlqstyl---ggsavqatikeshd
k---ldfklggkere----elehehinksagksrll---eakdehke---
vgpknldrfpflqyykvvneirhingiilkedpltfdivtrwlclnassv
ykaakdgvke-k-sphhahittgaaadrgislmlslvaskdcrslyagsd
gd---ggghqrartetegegadcfgtrerpyqlrppa-----kcpcgsvc
hckrenasppgwfhdsplwg-----nsadgvitlpqgppgsarcvn---h
vavfv-----------gschghnqqdyyrkrvaylghinlalatlvgdyg
nqk--lpsshtqtynkrak--kpekggkl-------------eqtlgav-
ecg-ltaankkhgganyeicv---------fslpekghs-mlkadsrgdn
aaapktvgkarfeaihsmyyk
>node17
hsvtkkgqgcq---klqkydsrggvytlylcgp--qhlrdhgyslswdns
ltrldlemlkalne---pfylhfklekaaelaa---glkypgkaqktvnh
dvk--------------dpgatdlgcngy------aglht-ct-------
----lptvkaf----tgrgefpvavtnlqsvkl---ggsavaatikdshd
k---ldfklagkere----glehehinksagksrll---eakdehke---
vgpknldrfpflqyykvvneirhingiilkedpltfdivtrwlclkasav
ykaakdgvke-k-sphhahittgiaadrgvslmlslcaskecrslyagsd
gd---ggghqkartetegegaecfgtrerpyqlrppa-----kcecgsvc
hcqrenatppgwfhdsplwg-----nsadgvitlpqgppssfrcvn---h
vavfv-----------gsshghnqvdyyrkrvaylghielalatlvgdyg
nrk--lpsshtqtynkran--kpekggkl-------------eqtlgav-
scg-lpaankkhgganyeicv---------fslpekghs-mlkadsrgdn
aaapktvgearfeaihgmyyk
>node7
h--ttkpevcq---hlkkcds-gglfslflcapgpnqlrdqgfslgweaa
ltrfelyvlkalae---sfymkgklekaaq--tevfdlkypgkhqkkvnh
dik--------------pqgatklgcdtfaatyqnsgvnr-ck-------
----pptvkpf----tlrgefpvkmtnlqsekl---gsqaiaatnnedhn
k---lefklqgkase----elehehilmaagqskglmlgnskdshke---
vkpkqaerfpelqyykvvnefqhlngii--------------------pa
yegsnngvkqlkpgppyalpttgigarraqalslklgatkegpsqygaad
gv---vggyqkah--tegngedcfgtadrpyqlepmvrghptkctcrsvc
nckrdkpsvpywfhesclwq-----nflagivt-prgp------------
vaifd-----------gshrhanvvdyyrtkcaflgki---laanigaya
hkk--lsishsqtynhqad--kpskggql-------------eqtggav-
qci-ttpeskkygdahfeicvilpssqvkllsfpeknpt-vlmgdsradh
at-pkavdtarfdasqnmyyr
>ENV_SIVV1/24-538
n--ttkpevcq---hqkkcdk-gglfalflcapganqlrdqgfslgweaa
ltrfglyvlkalae---sfykkgklekaaq--tevydlkypgkhqkkanh
gvketfrpdgmqpsprcpqgatklgcdtfaseypnsgvqr-ck-------
----pptvkpf----tlrakfpvkqtnlvseklphaggqaiaasnnhdhn
k---ldfklqgkpse----dlehehilqtaspskalmlgnskdthke---
vkskhaerfpelqyynivdefqhhtgii--------------------sa
ydgsnsgvkqlkhgasyplpstglgarqaralalklgtskkgpshygaaa
gv---vgsyqkah--tagigedcfgtadrpyqldpmvr---tkctcrsvc
nckrdkplvpywfhqsclwq-----nylngvvt-prdp------------
vaifd-----------gsqkhanvvdyyrtkcafleki---laanlgaya
hkk--lsisnnqtynhqa----pskggql-------------eqtsggv-
gci-ttpesrkygsaqfe--vilpsvqvkllsfper-pt-vamgdsraeh
tt-pkavdtarfdasqsmyyr
>node19
hsvtkkgqgcq---klqkydsrggvyalflcgp--qhlrdhgyslswdns
ltrldlevlkalne---pfylhfklekaaelaa---glkypgkaqktvnh
dvk--------------dpgatdlgcngy------aglht-ct-------
----lptvkaf----tgrgefpvavtnlqsakl---ggsavaatikeshd
k---ldfklagkere----elehehinksagksrll---eakdehke---
vgpknldrfpflqyykvvneirhingiilkedpltfdivtrwlclnasav
ykaakdgvke-k-sphhahittgiaadrgvslmlslvaskecrslyagsd
gd---ggghqkartetegegaecfgtrerpyqlrppa-----kcecgsvc
hcqrenatppgwfhdsplwg-----nsadgvitlpqgppgsfrcvn---h
vavfv-----------gsshghnqvdyyrkrvaylghidlalatlvgdyg
nrk--lpsshtqtynkran--kpekggkl-------------eqtlgav-
scg-ltaankkhgganyeicv---------fslpekghs-mlkadsrgdn
aaapktvgkarfeaihgmyyk
>node10
hsvtkkpqgcq---klqkydsrggvyalflcgpgpqqlrdhgyslswdns
ltrldlevlkalae---sfylhfklekaaqlat---glkypgkaqktvnh
dvk--------------dpgatdlgcngy------aglht-ct-------
----lptvkaf----tgrgefpvavtnlqsakl---gssavaatvkeshd
k---ldfklagkere----elehehinksagksrll---eardehke---
vgpknldrfpflqyykvvneirhingiilkedpltfdivtrwlvlnasav
ykaasdgvke-k-sphhshittgiaadrgvslmlslvatkecrslyggsd
gd---ggghqkartetegegaecfgtrerpyqlrpqa-----kcecgsvc
hckrenatvpgwfhdsplwg-----nsadgvitlpqgppgsfrcvn---h
vavfv-----------gsshghnqvdyyrkrvaylghidlalatlvgiyg
nrk--lpsshsqtynkran--kpgkggkl-------------eqtlgav-
scg-ltaankkhggahfeicv---------fslpekghs-mlmadsrgdn
aaapktvgkarfeaihgmyyk
>ENV_HV2D1/24-501
hevtkkgqkcq---klqkydsrggtyalflcgp--qhlrdhgyslswdns
ltrldlevlralne---pfylhfklekaaelaa---glkyagkaqktvnh
dvk--------------dpnatdlgcdgy------aglha-ct-------
----lptvkaf----kgrggfptavtnlqtakl---ggpavaatikeshd
k---lefklgskdre----glehehlnksasknrfl---dakdehke---
vgpknldrfpfieyyrvvseirhingiiakedpltfdivtrwlclnaaav
ykaakdgvke-k-sphhphlttriaadrgtslmlslvaskecrsiytgsd
gd---ggghqkarts-egegaecfgtrerpyqlrppa-----kcecgsvc
hcqresacppawfhdsplwq-----nsaggvitlpqgppgsfrcanaggh
vavfi-----------enspgnnqvdyyrkrvaylghielalatlvgdyg
nrk--ipashtqtynkran--kpekggkl-------------eqtlgav-
scg-ltaankkhkganyeicv---------fslpekghs-mlkadskgdn
aaapktvgkarfea-hgmyyk
>node14
hsvtkkgqkcq---klqkydsrggvyalflcgp--qhlrdhgyslswdns
ltrldlevlkalne---pfylhfklekaaelaa---glkypgkaqktvnh
dvk--------------dpgatdlgcngy------aglht-ct-------
----lptvkaf----tgrgefpvavtnlqtakl---ggsavaatikeshd
k---ldfklggkere----glehehlnksagknrll---eakdehke---
vgpknldrfpflqyykvvseirhingiilkedpltfdivtrwlclnasav
ykaakdgvke-k-sphhahittgiaadrgvslmlslvaskecrsiytgsd
gd---ggghqkartstegegaecfgtrerpyqlrppa-----kcecgsvc
hcqrenacppgwfhdsplwg-----nsadgvitlpqgppgsfrcvn---h
vavfv-----------gsshghnqvdyyrkrvaylghielalatlvgdyg
nrk--ipsshtqtynkran--kpekggkl-------------eqtlgav-
scg-ltaankkhkganyeicv---------fslpekghs-mlkadsrgdn
aaapktvgkarfeaihgmyyk
>ENV_SIVG1/22-522
h--ttkpavcr---hlkkcds-gglftlflcapgpnqlsdqgfslgweaa
ltrfelyvlkalae---sfymkgkleeaaq--tgvfelkypgkhqkkvnh
dnr--------------pqgatklgcdtfavtyknsgvnrlck-------
----pptvkpf----tlrgefpvkmtnlqaekl---gsqaiaatnneshn
k---lefklqgkase----qlshehvlkaagqtkglmlgnsddshme---
vkpkqaerfselqyykpvnefqhlngii--------------------aa
yegfdngvkqlkpsppfalpttgigarraqalslklgatkegpsqygaad
gi---vggyqkah--tegngedcfgtadrpyqlegmvrghptkctcrsvc
nckrdkpsvpywfgdsclwq-----nflggivt-prgp------------
vaiyd-----------gshrhanvvdyyrtkcsflgki---laanigsya
hkk--lsishsqtyaheadnhkpskggql-------------eqtggav-
qci-tapeskqygdahfelcvilpssqvtllsfpekqst-vlkgdsradh
dt-pkavdtarfsasknmyyr
>ENV_HV2CA/25-512
hsvtkkgqg-q---klakydsrggvytlylcgp--qhlrdhgyslswdds
ltrldfeklkalne---pfylhfklekaaelaa---glkypgkaqktvrh
dvn--------------qpgatdlgcngy------aglht-ct-------
----lptvtaf----tgrgefpvavtnlqsvkl---ggtavaatikdshd
k---ldfkqagkeke----gwehedinksagksrll---eakdehke---
vgpknldrfpflhyykvvneirhingiilkedtltfdivtrwlclklsag
ykeakdglke-k-sphhahittgisadrgvslvlttcaskecrslyagsg
gd---ggghqkartetegegaecfgtrerpyqlrppg-----kcecgsvc
hcqhenaqppgwfndsplwa-----nsadgvitlsqgppssyrcvn---h
vavfvgidtyfskvc-gsshkhnqvdyyrkrvaylghielalatlagdyg
nrk--lpsshsqtyskran--spekggkl-------------eqtlgav-
scg-lpaankkhvganyeicv---------fslpdkghs-tlkadsrgdk
asapktlgearfeaihgmyyk
>node9
hsvtkkpqgcq---klqkydskggvyalflcapgpnqlrdqgyslswens
ltrlelevlkalae---sfylrgklekaaqlatdvfglkypgkqqktvnh
dvk--------------tpgatdlgcngy------aglnt-ct-------
----lptvkaf----tgrgefpvavtnlqsakl---gssavaatvkeshe
k---ldfklagkerd----elehehigksagksrll---nardehke---
vkpknldrfpflqyykvvneirhingiilkedpltfdivtrwlvlnasav
ykaasngvke-k-sphhshvttgiaaergvslmlklvatkecrslyggad
gd---ggghqkar--tegegaecfgtrerpyqlqpqs-----kcecgsvc
hckrenatvpswfhdsplwv-----nfadgvitlpqgppgsfrcvn---h
vaifv-----------gshhghnqvdyyrkrcaylghi---latlvgiyg
hrk--lpsshsqtynkran--kpgkggkl-------------eqtlgav-
scg-ltaankkhgaahfeicv---------fsipekkhs-mlmadsrgdn
aaapkavgkarfeaihgmyyr
>ENV_SIVGB/47-569
ssigskhdvctskyhlkncep-gnlyslflcgpassqlkeeg-altwedt
ltrfqlyllpalhqtfffyhlrgkldiaeq--sngmnlkyshrhqekakd
vtk--------------klgtnk--------ayqksapak-ck-------
----eptlrty---ghkrgefpttafrlenakl---gsqavsatansyln
ttltlkfslqgkaaesiagslqrvyfldaagdsggpglddeensqkhmtl
vkpkdvsrfpnfqyysvikdferlsgii--------------------aa
vtgstngska-kpspndclttsaigqkkiqgvslrqgatkqgetqygign
gvvlkiegyhktr------ggg---tatriyhinhmiigkkakpscksvs
tcarekpavpywphaacmwq-----dypnaiva-prgsrgpykcvh---h
cpifr----------cgsnqethvaeayesrgvflvnq---lavtgggye
dkkhlqpksk-htfshqae--kptrsdalsqrnesfvfatqkaedgkpf-
vcv-ttpksqryadahfgaclilprmevrlgsf-----aallladsqgdh
gr-pkekhntqfdanldmyyk
>node8
hsittkpevcq---hlkkcds-gglytlflcapgpnqlrdqgyslsweaa
ltrfelyvlkalae---sfylkgklekaaq--tnvfdlkypgkhqkkvnh
nvk--------------tqgatklgcdtyaatyqnsgvnr-ck-------
----lptvkaf----tkrgefpvaitnlqsekl---gsqaiaatnnenhn
k---lefklqgkasd----elehehilkaagqskglllgnskdshke---
vkpkqaerfpelqyykvvnefqhlngii--------------------aa
ydgssngvkq-kpaphyalpttgigarraqaltlklgatkegpaqygaad
gv---vggyqkar--tegdgedcfgtadrpyqlepmvrghrtkctcrsvc
hckrdkptvpywfhesclwq-----nfpagivt-prgprgpfrcvn---h
vaifa-----------gshhganvvdyyrtrcaflghi---laanvgtyg
hkk--lpnshsqtynhqad--kpskggql-------------eqtggav-
aci-ttpdskkygdahfeicvilpssqvkllsfpekkps-llmgdsrgdh
ah-pkavdtarfdasqnmyyr
>node18
hsvtkkgqgcq---klqkydsrggvyalflcgp--qhlrdhgyslswdns
ltrldlevlkalne---pfylhfklekaaelaa---glkypgkaqktvnh
dvk--------------dpgatdlgcngy------aglht-ct-------
----lptvkaf----tgrgefpvavtnlqsakl---ggsavaatikeshd
k---ldfklagkere----glehehinksagksrll---eakdehke---
vgpknldrfpflqyykvvneirhingiilkedpltfdivtrwlclnasav
ykaakdgvke-k-sphhahittgiaadrgvslmlslvaskecrslyagsd
gd---ggghqkartetegegaecfgtrerpyqlrppa-----kcecgsvc
hcqrenatppgwfhdsplwg-----nsadgvitlpqgppgsfrcvn---h
vavfv-----------gsshghnqvdyyrkrvaylghielalatlvgdyg
nrk--lpsshtqtynkran--kpekggkl-------------eqtlgav-
scg-ltaankkhgganyeicv---------fslpekghs-mlkadsrgdn
aaapktvgkarfeaihgmyyk
>node11
hsvtkkgqgcq---klqkydsrggvyalflcgp--qhlrdhgyslswdns
ltrldlevlkalne---pfylhfklekaaelaa---glkypgkaqktvnh
dvk--------------dpgatdlgcngy------aglht-ct-------
----lptvkaf----tgrgefpvavtnlqsakl---ggsavaatikeshd
k---ldfklagkere----elehehinksagksrll---eakdehke---
vgpknldrfpflqyykvvneirhingiilkedpltfdivtrwlclnasav
ykaakdgvke-k-sphhahittgiaadrgvslmlslvaskecrslyagsd
gd---ggghqkartetegegaecfgtrerpyqlrppa-----kcecgsvc
hckrenatppgwfhdsplwg-----nsadgvitlpqgppgsfrcvn---h
vavfv-----------gsshghnqvdyyrkrvaylghidlalatlvgdyg
nrk--lpsshtqtynkran--kpekggkl-------------eqtlgav-
scg-ltaankkhgganyeicv---------fslpekghs-mlkadsrgdn
aaapktvgkarfeaihgmyyk
>ENV_HV2NZ/24-502
qsvtakgqgcq---klqkydtrggvytlyqcgp--qhlrdhgyslawdns
ltildlemltalne---pfylqfklekaaelaa---glkypgkaqktpnh
avr--------------dpgatdlgcngy------sglht-ct-------
----lptvkaf----tgrgefplavtnlqsvkl---ggsalaatiedshe
k---ldyklagnere----pleheh-nksngrsrll---eakeevke---
vgpkgldrfpylqyykvvndirhingiilkedpltfdivtrwlclkasav
ykaakegvke-k-sphhahittgiaadrgvslmlsliaskdcrplyagsd
ge---sgghqkartetegagaecfgtrekpfqlkppa-----kcecgsvc
hcqrqnttppgwfhdaplws-----esadgvitlpqgppsgfrcvn---h
vavfv-----------gsshghnqvdyyrkrvaylghialalttlvgdyg
nrk--lpsfhtqnynkran--kpekggkl-------------eqtlgagg
icg-lpgadkmhgsanyercv---------fslpekghs-mlkadsrgdd
aaapktvgearfeaihgmyyk
>ENV_HV2BE/24-510
hsvtkkgqkcq---klqkydsrggvyalfqcgp--qplhdhgyplswdn-
---ldlevlkslne---pfylhfklekaaelaa---glkypgkaqkyvhq
dak--------------dpgatdlgcngy------aglht-ct-------
----lptvkafphk-tgrgefpvavtnlqsakl---ggsaviatikasks
k---lnfklggkere----glehehlnksagknrll---eekdehke---
vgpknldrfpflqyykvaseirhvngeilkddpltfdivtrwlclnasrg
yksakngvke-k-tphhahittgiaadhgvslmlslvaskecrsiytgsd
gd---ggghqkartstqgegaecfgtrerpyqlrppt-----kcecgsvc
hcqrenacpqgwfhdsplwg-----nsadgvitlpqgppgsflcvs---h
vavfv-----------ggshghnqvdyyrkrvaylghielslatlvgdyg
ark--ipsshtqtynkran--kpkkggkl-------------sqtlgav-
kcg-ltapdkkhkgagyeicv---------fglpekghs-mlkadsrsdn
aaapktvgkarfetihgvyyk
>ENV_SIVM1/24-528
hsvakkpqgcq---kltkfdskggvyalflcasganqvrdqgyslswens
ltrlelevfkvaae---sfylrgklekaaqlatdvfglkypgkqqktvnh
dvk--------------tpgatdlgcngy------aglft-ctayitlql
raatlpvvkaf----tgrgefpvavtnlesakl---gssavaatvkeshe
----ldlkvagkerd----elehehvnksagqsrll---ntrgehse---
vkpgeldrfpflqyykvvneirhingiihkedaltfdivtrwlilnasah
ykaasngvke-k-sphhshvttgtsaqrgvslmlklvatkecralyggad
gd---ggghqkar--tegegaecigsrerpyqlqpqs-----kcecgsvc
hckrenatvsswfhdsplwvtswgsnfadgvitlpqgppgqfrcin---h
vaifv-----------gshhgdnqvdyyrkrcaflghi---latlvgiyg
hrk--lpsshsltynkran--kpgkggal-------------eqtlgav-
scg-ltgankkhgaahfeicv---------fsipekkhs-mlmadsrgdn
apapkavgkarfeaihgmyyr
