>F
eleqsqlfrcsqpaklnvlikstyngacsralvvllhgdnyvaylgdakg
qtgtnsrgpksgqkaqksqygqgyvllgpik--gsp-hastdcrvaetfs
af--alg-fkvskggclkggprasasal----cplpkdk----fqdvprl
qlknlkpkvtslsavvkpcfpkmvnkltpakqtsgit---edchqlelvl
qinsqqacaqlsqpdqki---------rgsitcflqgcw-tgfggskltt
gkarnwavcyste--cyglakgkqdyhgppdeegdglpgldlfegpgalh
sldygaieigykav-qaerqp-glrqadlddkvddqslg-ivvrmt----
---naklwfgkdqvlwemaclc---------ygepasksnhlvqlfmdgk
kqvqa---vlgdiyspthiplgtqhlpfeewesr-glqsv-epir-tkha
---ptpldqte-gqrrqtclkkthvlgceagdlgahwspypansrqfkte
-------ykp-prkvvmalrldhfkekfltqeiyrppfesf-kialecvs
prggwra-----pdlcgilpkldrvpk
>node3
gldqavlctcvhlgqlksefkhtygdqylrg----welghiagkggesk-
------yklavglnstkglqskpyflpfigv--gkpvtkrksrrsgsifh
pq--tvtyifeakevstssvmpkkaaasmsdgaplafgeesftiaklfrl
alkkkh-gietpirqpkgcfsflkaaqkqvnqarsfpvkafrpdgls---
lhpsegvggiqgrlnhkadgfclfrlargadtcylvask-asflqqqpst
skvtkmptcthspanygaagkdhdefds---vmftngrevqtvqepnsty
qfk--aveitkeatafdiqna-salekdfvdtlvevgll-ailhtv----
---glclwftnnavlqgrscycrscdidssafttsmvtdsqvidlilhgl
vpsye---agqevfhsplfrm--vanptsdweck-glklqqspld-skdn
tlkpmqlakgs-vikrvgcvgregmmgcfnanlg----rylanissnrdd
-------ykq-s-----a------srkfasnkvyrqdfesi-kdsdgyvg
gscdwld-----kvgcg-lgvvahrsa
>H
eledsalgrctdlgllkselksgygssclsg----walkalackdaptk-
------ylkaghvpsmrsaysntyvlhllgn--kvl-ekhkearegeifg
af--flv-vepnkggyskgettekpgatlnmgyplpmtr----gqpvlkm
alkppkmslivimaa------ytkvgqtqqkshkgfvlqgtqigqia---
qnnd--lcadggvqnskm---------agkvtcflsgawntgflvdklsv
nkprtwltcltspekcgdlkkektgfag---dnce-vkrkkevdnpgnlp
syk--giqkaceti-agerkp-nmnkkdlgqtvgssgaa-iilhva----
---slntwsdtkkvslemeccs---------aegsgakkpelfqlahcsk
dkvirrslpsnelyhnsefslgdhnv----wqtr-kmlmqpnqil-srkk
---apklpqsa-vlnrhghlnknlklkcsddnlg----gyladdsqtmsv
etdhtdrynt-mkstlla-----fkekfsesqvyspgftsf-tvslgsts
swlgssl-----kticgvlarlhvtkn
>node14
nldqtalsrcnqvgllkaelkttyggkclrg----walgdlepkagstk-
------ynpavnikhtkaqyskpyvlhyien--gtp-nkhkearggeifs
pf--tla-inpskggctkggttkrpspmmkmgnplpfdr----fqkvlrl
klkplrtsvdsiipelkgclaymkvkqtqhkqakgfplkggqvgqvs---
qnkdqgacanmgvhsqkm---------rgavtcfltgsw-tgflankltt
gkardwldcytapdgctglekerhdfag---eegegvrdkntfenpgtmm
syk--gievtsqav-agerdp-imqqkdfgnlvgsssia-ivlhvt----
---glnlwfaknpvvwemdcyc---------ygesaskephliqlaligk
kqvaa---vggdvyqssnfplgsqhlpiddwecr-gmqmqvnpvw-nkhk
---ppplakgn-vskrhtclskelilgcsennlg----ayladekqgkae
-------ykt-prkemsa-----fkdrftqgqvyrpgfssi-niglgcia
qwagwpt-----kavcgvlsklevvsn
>E
elekselfkcaqlaklldllrvaysglcpigmvvslnlgdyiprcgvnkg
gtgpedagaaggektaktqyssgytlqsltt--gdp-nratetrgsetfs
af--tll-fhackggcakgdttknpggt----cslplek----fqptpsl
kvktlrkkvdsigadaspcfsslvnkqvqlyeskdis---gevqevvlvi
slitqnacseaesqsakm---------rgaitcylvfcw-igfgasklhp
qpasvwlscyspd--cyalaksknefpspdeeesegrkatnayeapgtlh
iynhgtteieskti-sgkrdp-vvrvavlgnlqgtaglp-islrat----
---dlqlwfgkppvvwdvtcfc---------ytenvglsshlielfleek
kqvsa---vggeiyqtpvmtlgtqhlpidemdsq-gvkthvdpvi-kkqs
---ptamanvaqaarrhncfsnahvlgcaeadlkfpwddyladkkhfkgn
-------ikt-prkimsalrklqfkhr--agqryrpsystf-setsgciv
pwggwrd-----selcgvlsekhrask
>node13
dleetaltrcnelgllkpelktsygstclrg----waltalackggttk-
------ylkavntkatkaqysnayvlhyvgs--gvl-dkhkearggeifa
pf--tla-vgpskggytkgdtskkpsstlnmgyplpfdr----gqrvlrm
alkpprtsldsiipa------ymkvaqtqhkqakgfplqgkqigqvs---
qnkdlemcanmgvhsskm---------aggvtcflsgswetgfmadkltv
nkprdwltcvttpdgcagldkdkegfag---eecegvrkknsfenpgnlm
sfk--glevvsqtv-agerkp-amqkkdlgntvgasgia-ivlhvt----
---glnawfdtnrvswemecys---------adssgskapeliqlthcak
kqvvarslvggevyhgsnfslgarnv----wqtr-nmqmqpnpiw-tknk
---pprlaksn-vmkrhthltkelkldcsdnnlg----gyladdkqakad
-------yst-pktelsa-----fkerftqgqvyspgfssf-siglgcia
swagwpt-----ktvcgvlarlhvtsn
>D
klgeailyagltlaqlksnysnvfgnrcdta----welasikpkageqg-
------fkhiinlshlkpinekayylkfqaskwgrp-irkklehattryt
pf--tlnicfpgspqcltaglktipagairigatlfigc----getgfkl
flrskrpgdetlirlskgcftirkenntqneqgtffqegaappdpvg---
lhplggqaatqrhfggtmaegclakehngsqlclasssn-nlylqhqsps
kkageplscannptgy-agnkdpdaftt---afgaggrsaalfkasstay
vyk--fvdeavkglafdt-------qrdfgntlvffgll-dtmh-adgcd
nlsglclwftkapmlparncyi---------ffdtpgadrdlmtlilegl
dqvla---qgdevfqsplfrpiaprlqtsnwettkalklqnapqg-agnd
alksphrttag-ilkrpkcqirerakgcagssvp----ralsqlsktkpq
-------yks-p-----s-----fkknygsgevyqrgfgdivmlgdayai
gscnwls-----higcpvlhsvskrgd
>B
gydepvlctcvhlgeikpdfkhtsgdqylrg----wegapisgkvgesk-
------hkiavtlhskkglqskpylllflta--gksvpkrnsprsgtils
amgqtvtyffetkeqnspsvmakkaagsisdgsplptgaegflfakqfrl
ylqnkd-p--tpirqpsacfsslqapqksvnksrsfpvrdfrqdgls---
lhpsvlvggihgrlkskdddfclfklaqdidtcydvaaa-vsflqqraat
skvvkmptcthsaanygalghdndefds---imykegkqqqtaeepssgy
efk--avmitkqahgfgiqna-slltksfndalvevglltailhtv----
---gvclrltnnfvldgrscycsstqlassafvssmvvenaiiglighgq
ipspe---agqgifhsnlfkm--hespmsdwec--gvelkessld-rtsg
tlkpvqlakvs-tvkrrgcvgreglmvcfdaslg----rylsnasanidd
-------fkqca-----a-----------sgkvyqeelena-kdseayag
gkcdwld-----kvgca-lgvvashas
>A
gnkqaalcgcvllgqlkeafkntygdqylrg----welghisgrenpsk-
------yklavglnnkegleskpyfipflgv--grnyikrkgkrsgsifh
gq--tvtyifqvsevstsstmpqksantmtdgaplafgeesftiaklmsl
alkhrq-gietpirqpktclgflkatqkrvkqarsftvnsfhphsld---
nhpvqadtdikgrlshkadnfcllklargvdvcylvtnk-aaflqsnstt
kkvsklptcthsptgyaaegkdhdefaa---imythghevqtvqepnsay
qfe--aveitkqavgfgiqea-pqlekefveifveagll-avfhtv----
---hlcllfaavavfapkscycrtcdiggstigasmivgtevvnlilfgp
vpwye---arleayhsplyrv--vanpqfewecr-glkleqtpig-skgc
tlkpmqlakgs-vakrlgcvlreglmgcfnanlg----rylgeisntpen
---------q-n-----a------rkkfgsdklyiedleki-kgsdgycs
gdcdwfddvavtkvacg-vgvvthrsp
>C
kvaqavlyiglnlvpikaefknafgnrclil----welssqnvkagetd-
------yrhaiqlghvasmpgknyyiefqavlrgkp-trmklghsstris
pf--tlsfcltekrecltsvlkkmpsasinifngvligc----gqktyrl
elgekrpgpvaliklvkgcfavqkenetkhvqstffqdsasvrdlvh---
laplegtaaiqglfgpsmadgcvtrnedgarlcfleenr-sqfkhhqapf
kktgeplgcstgktgy-agnkehdeytt---amgpagrehqtlhalttgv
vfn--fidialestamdt-------ekelgdalvkvglv-divhtl----
---alclwfaktttlrgrncye---------yfesppavs---iliwqga
tpala---tgeavfhtplfrananplqignwgcrralnlqksqlg-gqdd
nlktpklaegg-iekrpgcqgkekamvifessmg----rylkelditkaq
-------ygk-q-----a-----ykkkygigevyrrgsgtfvgvgagyvt
asckwlg-----kgdsprlqdvvhtnn
>node6
klaqailyaglnlaqlksefkntfgnrclma----welgsidpkageek-
------ykhavnlghlksihekayylefqailrgkp-trkklahsstryt
pf--tlsfcfpgkrecltavlkkmpaasikigsellfgc----gqkvfkl
hlkskhpgvetlirlvkgcfavqkenetqhvqstffqdsaskpdtvg---
lqplegataiqnhfgptmaggclaknangsqlcflvssk-neflnhqsps
kkadeplscsnnptgy-agnndhneftt---amgaagretetlqasttgf
vfk--fveiavegvafdt-------ekefgdtlvdvgll-dilhtv----
---glclwfaktpmlrgrncya---------yfespgadsdlmtlilqgl
nptla---ageevfqsplfraaaeplqvgnwecrkglklqnsplg-akdd
slktpklakgg-vakrpsckgreramgcfnssmg----rylanldtgkpq
-------yqa-p-----a-----ykknygsgevyrrgfgtivkvgdgyvt
gscnwld-----kagcpalqdvahrsn
>node7
nldqamlcacqhlgqlksefkntfgdqclkg----welgniepkagqsk-
------yklavnlnhtkglhsksyflefigi--gkp-tkrknrrsgsift
pl--tlsfvfpgkeecttgvmpkkpaasmsigsplafgp----iqkvfrl
tlksahkgvetlirivkgcfayqksqqtqhtqarsfpvkaskpdtvg---
lhptdggggiqghfghkmggfclfkqakgsdlcylvgsk-ngflehqpst
kkvknllactnsptgyggaskdhhefns---vmgtggresetvqdpgttf
hfk--gveitaeaiafeirep-smpekdfgdalvdvgll-ailhtv----
---glclwfantpvlrgrtcyc---------ymespssdsqlldlilqgl
nptya---agqevfqsplfrmaaqalptgdwecr-glklqnspld-akdn
slkppklakgs-vtkrpgcvgreaamgcfnsdmg----rylanittgrde
-------yka-p-----a-----fkkkfgsaevyrrgfgsi-kvgdgyig
gscdwld-----kagcgglgnadhrss
>node10
eleqsqlfrcnqlaklkallkatyggkcprglvvklglgdyipyagstkg
gtgansagpaagekdektqysqgyvlqtlns--gtp-hrqtetrgaeifs
af--tlv-fkaskggcakggttkkpaam----cplpmer----fqavprl
rlknlrtkvdslaadvkpcfprmvnkqtqmkqtkgip---gqvnqvvqvi
qikdqnacaqmsshsqkm---------rgaitcfltgcw-tgfganklts
gkarvwlvcysae--cyglskarhdfpgpedeegegvratntfenpgtmm
synhgaiemeskav-anerdp-vlhqadlgnlvgdtsia-ivlrvt----
---dlqlwfgkdpvvwemacfc---------ygenaskeshlvqlfleek
kqvaa---vggeiyqsthiplgtqnlpfdewesr-gvqsqvdpvr-nkhs
---ptplaqve-asrrhtclskehvlgcaendlgfswsayladskqfkte
-------ykt-prkimsalrkahfkdrflegqiyrpryssf-niglscva
pwggwrt-----pdlcgvlpklnrvtk
>node15
nldqtamclcqqlgqlksefkstygasclkg----wqlgnlapkagssr-
------ykpavnihhtkalhskayvlqyldi--gtp-tkrkesrggkifp
sl--tlafifpskggcttgsktkkpapkmkmgnplafgr----iqkvmrl
tlkpthtgvdslfpvlkgclayqkaqqtqhkqargfpvkagqadtvg---
qnetegggasqghfghkmggfclfkqpkgsvlcfltgsw-ngflehkpst
skarnwlacysapsgcagiekerhefss---vqgsggrekntfqnpgttl
nfk--gveitaeai-sqirdp-tmrqkdfgdslgeasiv-iilhtv----
---glclwfannpvlrdvtcyc---------ynesassdsqlmqlvlqgr
kevsa---sggdvfqsalfrlvsqplpiddwecr-glqmqvnplw-akhk
alkppklakgs-vtkrhgclgkeialgcydndmg----pylanakggkde
-------ykt-prketsa-----fknrfsraevyrrgfssv-kislgyis
awcswad-----kavcgglcnldhist
>G
eleetatshcdelgivkselkteygitcirg----waltslsckdgtkk-
------yldavftkatkanyskgy--hyvte--avl-nkhkearvtevig
pf--vla-igpskggnaraetngkptdtlnlgypitfdr----gatilkv
alrprrtcliqlvsg------yakaaetvhkhdkgipiqgqhiggvn---
qskelemsanlg-------------------acflgnswqtgfmadklst
ekarkrlacvtisegcvglhgekggfgg---adclgvknkdsfdnpeelk
sfk--glqvvsqdi-ageakpspmdkkelgitigasgna-ivkhat----
---glnawidtnrvswevacfs---------gegspsktpalteltrcnd
kdviaralvggavyqgktfsflsryv----wqsk-nvqdparanwpslnk
---hphleksg-amrrmthsiseltldcsgnalg----gyladdkqvhae
-------ysk-srtslga-----fkeqaskgqvyaphfhrf-kvgigcva
llggwpt-----ktvcgvlgalqvtsn
