>node15
aillr--sh---dn--ivsgshqaeekkprqkngeappklsfqrdvn---
---------------sg-gwgakhstqgrahrigavthkttpqkrfsagh
taqavlfvgfwikhsgcticgdnekdk--fgavhvev---atddagqgli
lkktmfhtfaghskkgspheyldsfkgsclpnk---cfcgvlsttmda-s
--mptqsganhglvmrclchialksdycpvfltlqhpnyeniaigvhaia
laaddsrvkhsflpfpvyfinkdhvadfyal--fsrheqntahakgiv--
-aavcyhiknfvvgnt---slalegynrlkinllvek--gsvkfkaqayl
klpngeakf-ykvave------------ktvaksgkdgv-----------
--gaeeqrscfg-en-dgflvrtferklkflgkadslclnyagdmgachl
vlvgsmsmnkclvgntslkqgnkvwalrcqiaahfkyrrrptivvtwggk
d----ivdtqvya--------vnp----yggdghhfcakaqeahmle---
------ed----vkadlvqiepeisantikgyplkanavvgpeladlehf
qlvv
>C
killmftnh---kt--ivkggpgtdasrgiprigqqpdtlsfqreap---
---------------tg-rwkgkhvnqgysykqsilraakgpaskfgiaq
titgvlfktfwekhavqtacsepdkqs--fha----avgcksyevsdslk
lvrtkfhtlagngqksshhnyghpiehlcla-kasgc------dkdnh-n
--lsarrgngvltvprcgspselhshfcttflvlarrhwegvavgagtgk
fpggk-wadysfkpfpvflgnsaqma-ylhliafshtehgnnhdksav--
-tvnpyhirphvvenv---lmallgypqsavaynlgl--ggvgfknqafl
rlpevqfkl-ykivvq------------salatvgkppk-----------
--svavsrghlg-tl-eaf--------gnfdagehtm-qkirgelcgcal
sa---l--qgclagkspmkedpnvwalghnltlhvrytkgpvvvrrwlkk
d----vvtkpvfy--------vrp----ysgdnhkicalaqshgmlt---
------eh----tkhdkipysnelnascidgfelaapaviptalmsldql
rl--
>D
pills--dh---tg--iqkggadakatrplrrvgqqvaslnfqreaf---
---------------ag-rfknkhynqmkpnkvavlptttdpearlgiaq
iindilfkgfwdkhavcttcgnpqkdn--fhaiqved---egqdvgqtia
lviskfhsfatgsrnplhqnygnplhhqcla-rstgc------eesdhlg
--lsarqgkgvstpprcgphsalasdfcpaflilgrihwegvsvsqglad
lstgk-wsdysfkpyptflasngeld-yyclitfaktfqldahdkaaint
lmvspyqvkphpvtda---tmallgytslavayllal--gdvefdpktfl
klkeadktl-ykvsla------------pglskmgkdstlmtgdkqdgda
mtvvsesrsclakda-eaf--------srfdtgndsm-lkfafelhacpm
ka---lgnegclvgneamkeaaqawvitcklpmhfkykdgtvpirnwlge
e----aranpqyy--------gqp----ffstphqlstvspehamlt---
------eh----vrvdrtqqdddlgpscmkgyglktvsivpsafralehf
kl--
>B
kvllk--ap---ed--vtskghesetkknhrnlgeavgaeslhasva---
---------------sn-vwgvk---ggrkqsiavnnilatttkrvgpqh
tvpaskftafrkvhsldtecgakasdasqfgtinvdv---svhqrgendi
lqrakfrtnagsnikaweheyknaykpgcvteeansrfcgstftknet-g
--tqtqsgsdgdslvrceqlysakfhftggf---------qlahgigtte
lganrtwqtggtppfpvylvkdahvs-llhlvkfcrkkralqastvdv--
-siccfqgkgykgg-ltrsafalkgytwlgigilvdl--apnkylptavf
stlgnqgkt-ygskvd------------valmktpkkgi-----------
--nveeskccls-qh-ggf--------lafeggdiskspdycggmtsctl
kalsslsikgcllehasllegpsvwdltedssaifnfqkkavsivswesd
e----gtearfyeysgyeapg-sp----ygekahhypgssq-----g---
------kh----vktnlihdevelnsgivkeftlkatdiiptplvqlwff
se-v
>node13
palir--eh---dlsk-----w--------------ppnvkfehdid---
---------------sg-gwgskimvegkahpivaptfkiakrskfskgd
vseaylyigiwiihsgctdcganeeda--ygvvyvei---andeamaadi
lkksklhtfcgikkn-aphayfdsfggs-irng---cycghvakklna-t
gfmpndtghhdgivlrclchiklhkgycsifqrdqqanyefraigvhafp
lviedfqfpngyfgfhnyitesnhqngyydl--ltkpeesieqakpas--
-vtvvyrtkvlcidhe---wvglegfailncgglvvgkrgsvkyrtkafl
klpggeaafqykvpvd------------kptaktgpnav-----------
--ptekenkcys-ee-egylfrrferkfqyvgkkdlacli---emgscri
vvvgpsstskatcgttsleedskv---rcmdggsfaykrrpllvttwgkk
e----lqqaqvya--------var----yggtgrhfcakadfqftlslag
ggidnled----vdaeiqplfsgvqvpnyktyqlkttapvspdlavmeqf
ewav
>node14
pallr--eh---dltk-----h--------------ppkvsfehdvn---
---------------sg-gwgtkfsvqgkahrigavtykfpkqstfsagh
tsqaylfigiwiihsgctecganekdi--fgvvhvev---atddaleaqv
lkkskfhkfagltkkgspheyfdsfggscirnk---cycgpvarklda-s
--mptetgvhdglvmrclchialhtsycpvfqllahanyekiaigvhafa
lvaddfqiahgflpfvdyttekdhsadyydl--ltkheqsvahakaav--
-ptvcyhtkilvignt---svalegyailkcnllveg--gsvkykaqtyl
klpngqaafdykvave------------ktisttgkdav-----------
--pteeqhkcyg-ee-dgylsrkferrlkylgkadalcltyagemgtcri
vlvgplsnnknlvgttsliedskv---rcliavrfnyrrrpvivgtwgak
d----ivdaqvya--------vsp----yggdgahfcakadqaftlelvs
pgvnqldd----veadiaqiisdipvptykgyplkatavvgpdlanleqf
qwav
>H
ptlvr--eh---dlss-----w--------------ppyikfehdiq---
---------------sg-swgsrlmvegksnsivgpsfklakrtqfskgd
pkdgffyasiwiihsgctecvappega--ygvvf-nl---asdeavaad-
lkknalhsfggvkkn-aphayfsyfaga-irng---cycghvaskmes-g
afmpl-tghhhsivlrclckiklikgyccifqrnqqehyefriigvhlfp
lvieefqcpggyfwfqeyisevnqqngyyea--ltkpqesicqrepaa--
-invvtktkvlcidhe---wtflenfeilacdglavtgrgpvkyrtkyfl
klaggdaafqynvpvk------------khttktsphpi-----------
--dtgaedkcya-qe-eaylfrrferkfeymgkrdlacli---emgdcrv
vvigpsetskatcgptgleeqvrv---rcmdggdfayerppllgttwgdr
e----veqaqiya--------vkkkqkyygvtgqhfchkgefhftlslgg
gslnkaee----vhaevq--------easntyqlpvtapvsielttfepf
dwrv
>node3
qvllk--ah---ae--vvtggheseekknhrnigegvgnlgfhaavs---
---------------sd-vwggkhvsggraqrisiitmlattakragaeh
tipgsrfsgfrkkhsldsecgakasdawqfgsvnvdv---avhsrgesel
lertkfhtftgqvrmswpheyknpfkhgcvadkatsrfcgvvinksdh-g
--metqsgsdgniitrclthysakfhftpgfttvghpqnaqiasgigtie
laanktwnkgsfppfpvflvkdahvt-lyhlmtfcrkernaanskapv--
-siscyqakgfkaghltrsafalkgytrlsigllvdl--asvkfkaqaif
ptpgnqgkt-ygaavd------------valmksskdgi-----------
--gieesksclg-dn-ggf--------lrflggedsmspdycggmamctl
kalaslsingcllehasltdgpkvwelscdssstfnfrqkpvvnvswegs
d----gitarlyeytdyeagi-sp----ygekahhfsassq-----g---
------kh----vktnlihdevelnsniikgfglkasdvvpaplvrlwff
sldv
>E
paknk--ey---dltq-----h--------------pqkcgnekqvg---
---------------sv-awgkklsvesqshrdggvvtdyvkqatflaal
vadsylyvqiwiingactqcvsngkni--fqvvngdl---aadsnlgnqv
lkrlkylkyaghthnarangcfnaygsscitnk---cfcgsvgpklsd-s
--lptgtgvr--llvrcvcevalhasyc-----dphvnweevatgmhvft
lhvkeiqvqhgff----yvaestgeidyy------kqaksvekaegml--
-gtacshvktlltgnt---gtslesftfvkqdl--dc--dvkkfnghtdv
klprggvaydykvaakgpqplkcgylnlltisttakeah-----------
---tedlhacfg-eqaeflhlrkfeprmkflsqagaldlsyhekieecrv
lvggpfcnnvalasastlieanti---kcllsehfsyrrkpnvvptwgak
d----itnaiiyq--------vsp----fgapgslfcadnakpftmalia
lglgklgd----aesqmaqivievpepmfvgfelmgkavvstnlpklkcf
qwtd
>node10
paklk--eh---dltk-----h--------------ppkhgienqvd---
---------------sg-gwgnkfsveakahrdggvtyayvkqatftaan
ishpylyiniwiinggctqcgsnakdi--fgvanael---anddnlgaqv
lkklrfesfagltknastheyfdafgsscitnk---cycgsvahklsd-s
--mptgpgvr--lvvrcvcnialhasyctlfhllphanwenvatgvhaft
lhvkdfqvahgff----ytsekthevdyy------kheksvehakavl--
-ptvcthikilvtgnt---gvslegytilkhdl--eg--ggvkykphtyv
klpkgkvaydykvave------------rtisvsgkdav-----------
--ptedlhncfg-eq-eglhsrnferrlkflgqadalclsyhgemgncrv
ilvgplsnnlnlvpttsliennki---kcllverfsyrrkpvivgawgak
d----iadarlya--------vsp----ygapgahfcakaaraftlelia
lglnslgd----veaemeqivvdipqpqfkgfplmanavvspnlphlkpf
qwtd
>F
panfi--dhieepitk-----h--------------ppshaivsqie---
---------------sg-gwgnqvpveakahkgpgvtyaytphatfttak
ishpylyvqfwiinggctqcpsvdkni--fgvadael---ayddnl----
--glkfatftaltgnarthkffgaygsgcvtdk---cycagvihrlre-s
--apagpgev--lvvqcvhpilnhaeycsllqllpssnwenvatgvhaft
lrvrefh-sqlm------taektkevayy------qnahsveqqrsvg--
-pdvaahikivvagnt---gaslegysklknel--ek--ggakykghiyv
klpkgegpykfkvave------------rvisvsgkeag-----------
--paddghksfg-eq-eglhgkhferrlgfldqaqalilsyqgkmgncmv
havgtpannlnmvpvtalfkqgkv---kcllvprfsfrrkyvivggwgek
p----iasarlys--------lqp----yesseghfcvkqgkpfslelia
lglsslee----vegemdevvndipeplvkgfalkantvvcdklphlkpf
qwsd
>node6
nillr--dh---tt--ivkggpeseatrgirrigqqvgnltfqreap---
---------------tg-rwkakhinqgltykvsvlsatmnpaskfgiaq
tisgvlfkgfwdkhavattcgesqkds--fhaihvea---gshdvgdsld
lvrnkfhtfasnsrksthhdygnplhhlcla-katgc------ekadh-g
--lsarqgngvstvprcgshsalasqfcptfltlgrthwegvavgvglgd
lpsgk-wtdysfkpfpvflnnngqla-yfcliafakternnahdksai--
-avnpyhirphtvadi---lmallgytrlavayllal--ggvefkaqtfl
klpevqfkl-ykvgvd------------kslskmgkdst-----------
--gvaesrsclg-ns-eaf--------srfdsgedsm-lkftgemcacpl
sa---lsnqgclvgnkpmkegakvwvlscnlalhfrykkgpvvirhwlgn
d----vvanplyy--------vkp----yggephrlctmaqehsmlt---
------eh----vradkiqedndlnsscvkgfglkassvvpselsalehf
kl--
>A
qvlvk--ad---ae--vvhsstesnnpknlrkvgegvgslgfhvava---
---------------td-isggkhvaagwidsmaiitmlasaaqrageer
tvpgvrsagfrkdrelnndcnqkasdrwqflsveadv---hvnnrgdcdl
ldhpdfktftgevkmtwpaqykdafkqg---nkaagrfcsanehksdh-g
--mdgqeqsdgtiltrtlaqyselfhytegfsplghpqtaqipvgigdie
laenktwtkepftpfpafllkaphvt-lyqlatfckkhrnssnakavi--
-siscyqargfkaghyirsafplkgysrlkvgllvnl--asvkfkaqlif
ptpghrgln-ygepvd------------aalmkssrtgv-----------
--giddakdclg-ee-agf--------lgalggapglsndycggmaicml
kalarlamtgcllehatlgdppkiwglscdapstfnfrqkpvvnaswygs
dsgnlsltprlyeyneyqagi-sp----faatanhfsstsq-----g---
------ka-------nliqnavelsksiikgfgleatsvvqvslvrlwff
slhi
>node7
nillr--dh---an--ivtgsheseekkdrrkigedvgnlgfqrdvs---
---------------sa-swgakhvsqgrahrisiltqaaapqkrfgaah
tipavlftgfwnkhsvaticgdsqkde--fnavhvei---ashdvgqsli
lertkfhtfasqsrkssphdyknpfkhscladkasscfcgvlaskidh-g
--matqsgsgnsivsrclshkalashfcpvfltlghphweniaigvgiid
laankswnkhsflpfpvylvndghva-lfvlmaftreernnahsksav--
-avncyqiknfkvghi---amalkgysrlkvallvsl--gsvkfkaqafl
klpdgqgkl-yrvavd------------ktlaksgkdgi-----------
--gveesrsclg-en-dgf--------lrflggedsmclkytgdmaactl
valaslsiegclvgnkslkdgpkvwalscdiaasfkyrrrpvvivswegn
d----avttplya--------vkp----yggeahhfcamaqehhmls---
------eh----vkadlvqeeselnssiikgfglkasavvptalaglehf
kldv
>G
ealik--kq---nlek-----w--------------ppgvrfehdvkraq
kgfqtlelaacsdttsgwgwgskkmvegkshpiiaptfmiakrnkfskle
srqvylyvgiwisrqvckdcaefdeka--ygivkvhi---aqgdamagdi
lkktklktfsgikka-ipnpyfdafgtp-irsg---cycghvskklka-n
gfmkndsghhdgavlrclchvklhisycaifqadehadyefraigvhsfp
lveeayefpnsyfgfrdyicegdndngyydi--vtkpeesin---kad--
-vtvvymtcilcieqg---wiglepfaildcgglvvgeratvkyltkafl
-laggkasfqykvpld------------gptsvsaknkv-----------
--ktekpnkcls-ea-egylfrraekkfqyvgkkdlacli---dmagcri
veaapahaskltcttkslhedskv---vcfndgsyaykaapllvttwskk
a----lrqgqvyv--------vaq----yagtgrhfcpkadlqfglsfag
eeiaykeakskyldveiqplvsglqvpdyktyqlktaapmspdladvgpf
elaa
