>A
lcgwgldtsnefkapfigliyyvkacfadhedtnhgcaalfqwnvhtksq
l---pgalllgragftgcnc-------gvlkppthkkldiakkpsvhlvi
rvrihwspg-inlehema----eaagrasad---g----vq-dlqqggkv
veflelvvs-----pssaspvqrh--gpngcrrtdpfahqhfestvcgsp
dvvlsag-aliidkkaapynthpvqtdhqtvkglasekkasaqldlt---
dkcd-tasetrystllkhasgltlgnlrmqaqvrg-kclvnap--rm-nn
v--lihglnryalkrapqneipvvlyphslvdskrmvfgaqgtdciysdl
p-lslarek--nplrpqfslafssktaq---rkthttasfgaqvad--s-
lgtptske-lkeqfeeeqhgalcsgldyagqllslgtkegs-------sd
-gapicvfakheisgavrkvkeksdvtttttwtrwarigpct------vd
ietskdplgk---c------vhelgaecnhva----tdkey---pfd---
ikvl-vnlkc-gpalesndtwd-ltssynhhaav-ldpap--gd----vp
i------kenkmgq
>G
v--snstgks--kapylgllff-gpcfttkdesmvkgacsfswgta--lv
p---hrgtepeprvllqcgi-------q-----vgktglpnkqetsg---
-------rl-lnvkaeas----alngedlaeyllp----ap-lfkkvspk
na--mddda-----ghgivcevse--qpkgtchtqdfskenqgsamvlve
rgggpcv-tlkmeevmeklgcqkc----ngsiknkafqgvgtsmqarlqp
kcv-ldtkavadkkrlnlrrkvalrkpmlcvkaki-dcl---p--krlka
rlsfis---kfgfqlahgssfkigsyeqsrage-----------eahkal
fylaiswgq--tlqvdtfsreyepga--gltakglptafiqvrvgdhtf-
glkrevhatlcdd-rqqtnkadcnslpedmirgptg-qvkt-------s-
---aqrpfphqgarlrarlnespahcmtvyarpstvrvpklg------mg
lfveshphdpphkh------rqesglnpersr----vplky---afp---
ivll-fpfqi-gmp----kkfkvllacyakddlgqyngetkqcg----ll
p------peadash
>H
v--agtttkg--kak------f-gscfq---eslhsgacvftwsis--vv
v---vkgtqptpkallqssf-------e-----agrdglhgrgddag---
-------rt-lmlwaskv----vlngasvai---a----ypdefntippl
ng--gkass-----ghavncevre--qpgficnvdnpgrahrgsngaqaf
raggpcv-alrvekvmgclgaerc----ttklkskgfrigglnveiklqa
ksa-edakgvgnknilnlpraivmvrpklcikakd-hci---p--srlke
l--lik---kfpfklthdekfgvgsfgsgrthe-----------cyqsgl
i-valnwge--htqvdtfakeysppa--smgnkalptnfcnvrvgn--y-
sgkkdiqasafgd-rsqtdksdcdseegeliektag-gdkt-------s-
---aertfphkgaklsdkkkktpaqcmpivprpaitrvpklgpgipgcie
vfndmnvhespelhtardcfhqeggqnpgkta----iplky---afs---
lvlltydfkc-g-etdegtsfrvllpcyspgefgdfhedakpggsandvl
t------pvtegsh
>C
lagwvttipdeagvpvvsleey-gfcfttehdagetgvctykwkvhsygk
lkfinkvlvtkkakmmasdc-------gafvpiptkreveakdeavfqng
kvgcvspvg-vpikqrts----gcsahntga---g----vl-ehhrgepv
vs--deaqg-----g--vstqqhn--trngcnhnqpfseehmnvkhhapl
pcmfacl-alvmqgfegadndypvqdeqtivvdtkalks--aglipc---
esthdvsksgkyakllvkpcgltvgsfkldtndkt-qci--ea--kqacn
l--aeikacnvgfdvitedafhiefyahklids-----------cffasl
q-tplrwegpshaivedlsmaflsqe--glaknghpakffdaevge--s-
mglgeehk-lvdefhqnrhntgcsslglagalgalasngaa-------tk
-acegcklpntnsvgndnkcdsgtccsgcsawskwnkaghcr------vn
vsahlpgyeesaai------arqpgsackhln----qtief---tfkiav
tvll-akyka-ghglsqggrwn-vpckfshtvln-ghhtr--ck----vh
r------denriga
>node7
lpgwgtnnpdelkvpfigliyy-gpcfatqndtdhscrymfqwnihktak
l---nkalvperaslmkcnc-------galvppperkavvgkdeavflng
kvacvrppg-lwldhela----vasghasaa---v----vp-elhrggpv
vs--davqg-----gpsvapeqre--kpsgcnhsdpftaehlettgcgps
rcafvai-alimdkvvgpdnshpvendqhtmvstqalklgggslesn---
dkcddiaaggsyskllikpqglslgtlkmdahtks-qcldpdp--rkvnn
v--lvqnaskfvfkvakeatfqigfyphkltdr-----------cihsdl
q-vsltweg--hvtvanfslafdsrt--slskkghtaafidnqvgd--t-
lghsenhk-lvddfpqephtaactnldlsgvlagmgssgas-------tk
-nspacpfpnkditgeqrkvqaeaccktvatwnrwvrgsrcg------mn
vavqrdplesplty------vhepgnecnhiv----taiey---sfn---
ivll-vpykc-gvamsehgkwn-ltssyshhvla-lhpsq--cn----vp
v------senktga
>node15
l--sgttnpeeikvpflgliyy-gpcfaarddtyhrsaylfqwsip--vn
l---hralaperatlmrctt-------d-----agsegvvgkheagflsg
kvacvkppg-lwmnheva----vtsgkasaa---a----vp-dlhsggpl
vs--edveg-----ghsvvpenre--hpggcphsdpfttahlgsascspy
rcgfasi-alkmekvvgpedshkcenqgqtavsskalkiagfsletk---
akvedvaaggsyskilfmpqglamgnlkmnarika-qcldpgp--rkvkd
a--lvkdagkfvfkvandaafkigffhskligq-----------cihsgl
q-valtwge--hvgvgnfsmafdgst--slgkkghvaafietqvgd--t-
lahrevhp-ltdd-pqeaqtaactnlkneqvleamgatvkt-------tk
-nspaipfphkgitledrkveaegccmtvktwnswvraaqcg------ln
vfvdrdpgetplty------thdpgqdsnrip----tpley---afn---
lvll-vpykc-gvahaehgkfnrlassfshnalsnyhsqqmycd----vl
c------negktds
>B
lpgwgphgsnalkvpffgllyy-tscmvddekkkhsctylyqwnvyqsaq
v---pkaiipegagfsecdc-------gilvveaqkrlavakeppvflia
rikcvrsva-iplehelm----igagksvgd-------------------
-g--qevat-----stsvapaqrd--ktggcydtkpftaehlavtvcgpv
dcsfvamktliiqkfaegnnahsvhinhhtvqsteslqfggatle-----
-kcd-vsansryfslmkhaagltmgnlrmelyivg-kylepgp--km-dn
v--vvkgitktffkrakddgiqtglfpeklvdsarmifrqhgnecihpat
p-islawag--pplrphffigfkertpqticrkghrtgipasrgss--ar
lakpgshd-aveqlqqeqqgklcteldysailknm----ss-------sd
-hqcycqfakhdlvgalrkvqtkadcttdvtwgrwsksgrci------ld
------plek---y------vgklgaecdpfv----tdrpy---aye---
ivll-vdykc-tpgmsqtekfd-ltgkydhlsvn-lhaar--gq----ct
v------kqskkga
>node14
l--ssttnke--kvsflgliff-gpcftardetlhqgaclfqwtip--vn
l---hrgtrperatllqcti-------e-----agsdgvvgkeesgtlsg
klacakppg-lwmhhetv----vlsgkdvsv---a----vp-qfktsspl
ia--edida-----ghgmvsenre--hpggcphtdpfgtahsgsagcapy
rcgfaci-alkmekvvgksdshrc----hgavsskafkivglamevklhh
asv-nvasggsekkilfmpqglalgnsqlnvkvka-qcl---p--rkvkd
p--lik---kfafklaheakfkigtynckrtgq-----------cahsgl
i-aaltwgq--hfevgtfsteydsst--smgdkgfvatftetrvgd--i-
aanqeihstlcdd-rqeaqkgacnnlkaelistamgaavkt-------sr
tnnaerpfpnkgmtledrkaetegccmtvkarpswvrvpkvg------lq
vfvdrhpgdspdly------shdggqnseriv----tplky---afs---
lvll-vpykc-glsredhadfnvllacysqdelgdyhseqmfcd----il
t------easktnh
>D
lkgwg---lnqlqvallvlegf-gscfstehdtgeavkylyrwsinrsgd
l---knivivteanllmcac-------geflpiparraldgkegnvflns
kvscvravg-lhfkqqta----pssshgata---g----ct-elhhgdpv
id--nqvqg-----g--vntgqkk--tpdacnhsdpynnehlgv------
-----ai-alykegcvqagnghppeahqhlpvvtkalrs--agiipy---
ekcsgisksghfanlivkphalsvgrlnlntkaketqcl--dp--kdvsn
v--ivqkecqggfdvskkrafqagfyehkldlh-----------chgvdl
q-vslrwegnshtlvvnfsvpfdpke--glakkghsadffdsevge--s-
lkladeqk-fivefandlhhagcanlglsgalsgvgssgptglirplatk
-anegcevanvkssgedrkihgnapcktlagssswtkgarcd------lt
vghengaleetaay------aqqpgteikhlv----qtiefnrggfa---
aall-gkyncgghslkpygrwn-lsctfthsvld-daftr--ck----vp
r------qqnkiga
>node6
lpgwgtsipdelavpllsleey-gscfstehdtgeavkymfrwkihrsgk
l---nkilvsekanmmmcac-------gefvpiparkavdgkeeavflng
kvgcvrpvg-lyikhqta----pssahtsaa---g----vt-elhrggpv
vn--deaqg-----g--vstsqrd--tpngcnhddpfsdehmavshhgpl
hcafval-allmegyvgaenahpveeeqhiavvtkalks--aglipy---
escddiskggnyakllvkphgltvgslkldthtka-qcl--dp--kkvsn
v--ivqkacnvafdvskeaafqigfyahkladr-----------cnhsdl
q-vplrwegpshaivenfsmafnsrd--glakkghtadffdnevge--t-
lglgdehk-fiedfpqdmhhagcanlglsgalsgmgsngas-------tk
-asegckfpnkdtsgqdkkvhanaccstvaswskwvkggrcg------mt
vaaqngeleeaaay------ahqpgnecnhlv----ttief---tfs---
tvll-akykc-gqslsehgrwn-ltctfshsvla-lhfsr--ck----vp
r------denkiga
>node13
v--sntttkg--kapylgllff-gpcfttrdeslvsgacvfswsip--vv
v---hrgtqpepktllqcsf-------q-----agkdglhgkqeasg---
-------rg-llmsaetv----vlnggdvai---a----ap-qfktispl
na--edada-----ghgilcevre--qpggcchtddfgkahrgsagsaay
rgggpcv-alkmekvmerlgshrc----naavkskafkivglsievklqp
tsv-edtkgasdkkilnlpraialvkaklcvkvka-qcl---p--rrlkd
r--lik---kfpfklahdgkfkigsfnasrtne-----------cshsal
f-valdwgq--hfqvdtfskeydpsa--smgnkglptafievrvgd--f-
aakkeihstlcdd-rqqthkadcnsldgdmiagpag-gvkt-------s-
---aerpfphkgaklsdrkketpahcmnvyarpsnvrvpklg------ve
lfierhphdspelh------rqegglnperts----iplky---afs---
lvll-fpfkc-gmppdegtnfkvllacysqddlgdyhgetkpcg----il
t------patkash
>node3
lpgwgannpnelkvpfigliyy-tscfadqedtkhscaylfqwnvhqnaq
v---pnalvperagfmdcnc-------gvlippaqrklavakepsiflia
riscvrspg-itldhela----vaagrapgd---v----vp-elhrggsv
vn--davvg-----sssvapgqre--rpggcnqadpftaehlattvcgpt
dccftam-aliieklagpenshpvqndhhtvqgteslkmgggtleln---
dkcd-tasgsryskllkhasgltlgnlrmeahvrg-kclepep--km-nn
v--lvqgltrylfkrakedgiesglyphklvdsmrmifrkhgndcihsdl
p-islawes--nplrpqfslafssrtaqsicrkghttailasqvgd--t-
lgqpvshd-lveqfeeeqhgalcsnldfsgelasmdtsess-------sd
-hspvcqfakhditgalrkvqakadcktavtwarwarngrci------ld
ievsrnplek---y------vhelgaecnhiv----tdkey---afe---
ivll-vnykc-gpgmsehekwd-ltskynhhava-lhpsq--ge----vp
i------kenktga
>E
l--dvgkskd--qasgmgfyyt-gacggssdntlhqvaglfkfiyr--sn
l---qratrrahgtfcqccv-------e-----vdrglrvggadpgrlgg
kipcarppg-vdksnkta----vlvskdlqv---apglqva-sgkseppl
vi--qtiga-----shgyvtdnke--hpvgcphvapfgtvhngaagcaps
rcgienm-alkmelvvgkaesqrc----qggvskkpaniveldmqsglhp
aph-svgsgetpksilfpgsgllfggdrlnrklks-dcl---aekakvke
q--kim---kfafklehqdkyknstydckrklt-----------caqqai
i---lswgp--eyatatyspgyamqt--gmgdrgftnaftgtkasd--c-
andqeihgklces-rsrtgltacesl----vsarmgqrlkt-------nk
iiafvrsfpatpitledknaqngncvlivkarpewtraplgg------fa
iyagsgggtppel--------------kervvallgkalky---phv---
glvl-vpllc-kkgphspgqfivhvncyklrhlgtyhaaqrfcd----li
vwqaeknstgrtnh
>F
l--gvgkgke--qhgfkgfdyn-gicvgsrdnslhegaglstvtlp--vk
l---dratrkargttiqtcvyeadqevd-----adslgvfcsgqagslgg
kihrtkpdgsmssegdtagkfsvtsgedl-v---n----va-agethrgl
vm--qdrnaglkcaghgmvsg--enthpgncprvepfgnsqngaagcaly
scgfdsm-alraelvvgktdhdrc----hgglsskavkigdlgaqaklhn
sph-klapnqragvllflgrgllaapgplkvkvts-dcl---psrskgke
p--rfk---qftfkmeqeeklktgtfdctrtgk-----------cvpmvk
a---lswgq--efnttkyssetaigt--smgskgfitgftetkldn--c-
dmnhqvhttlcks-qnktamtncervkgqrisetmgprvrs-------ak
ivsttrpfvkkqisleektshkssccrtvkarpswtrvvmaa------lq
vfv-----napely------acpvtmpkertvailgkpldy---ali---
gllp-vpykc-glgraqggefsnmvvcykhdaignthsdqslcd----sl
s------eagrtnk
>node10
l--gvgknke--qvsfmgfsff-gpcissrdetlhegaglfkytlp--vn
l---hratrkargtfiqccv-------e-----adsggvvggadagtlgg
kihcakppg-msknndta----vlsgkdlqv---a----va-qgkthppl
vi--edina-----ghgmvsqqke--hpggcphvdpfgtahngaagcapy
rcgfesm-alkmelvvgradhqrc----qggvaskafkivdlgmqaklhh
aph-nvasgesakailflgrglllgnkhlnvkvks-dcl---pskakvke
p--kik---kfafkleheekfktgtydckrtvk-----------cvqvsl
i---lswgq--hfdtgtysseyamat--smgnkgfiatftetkvsd--c-
etdqeihstlcds-rsktgmtacdnlkaelisaamgpkvrt-------nk
iinaarpfpkrpitledknaqtesccltvkarpswtrvpmgg------lq
vfvdahagnspely------scaaavnkervvallgkplky---gmv---
glll-vpykc-glsrdqpgdfsvlivcykhedlgdyhsdqkfcd----il
t------eagrtdh
