>node13
nlhkpgkglkmri---ve------rsfvpvkga--c--ktgk-a-gv---
--hprtlkdlspqinysstgisgasglkksdkllgckfkkteqffrvatd
-ngpldi-mnr----------cckvqckskrhrpqi-lflttvslvfgcl
lfcgl--pavtsmgrilrtnr--qcdidhfaikgnaaldgiagslkdtre
--f--nqpqdlrgggaavdwqg--dvcaanggdavnfekhgllanplppr
prafrgaarmkllsgaggsvtakngvayl--------giygada--h---
eeaielqhinlprlcmcghlilhikadep-pksesmasyret-----fsa
sllanlq--klcfmdtlqlklkpvqvl-av----------ykeiegspqp
snpll------nikkgkparvtkqcgpgqtyafsn-------haeankfa
syhqtclfcp---k------gkswkfsglippnnrgisapalnhnarsha
gtgatgs-wlqdlkaaelqvtgkgritgkgggdnivdgag---nmaiavp
thryqhkvgnv--lstagfhihtyrmnlatge-----agkscdsesiktl
gsaelal
>node14
nlhkpgkglrmrv---ve------rsftpvkha--c--kegq-a-gv---
--harslkdlapqmnyssiglsgasslkasdsllgcsfk--eqffrvlad
-hgplec-lnq----------sckvqcrskrhkp-i-lflttvelvfgcl
lfcal--rmvtsvarifrtnr--pcradhvaakgnaalqgiasglknsre
--f--dqpqalrggtsavawqk--avctahggqyvvfekegllaaplppr
prafrgaermrlfsgsgvsglvkdgpafl--------giyglda--h---
kaaielthiklprlcicghlilqtkadrp-pkdetmatyldk-----frt
allanlr--klclmgelhyekkpveva-ap----------fkevatkeqt
st-vl------tikyvkpamvtrqcgsganyafgn-------paesnrfs
ryrqaavfpk---k------gkkndfndlippknsgiaatapthvaktht
gtgapgv-wltdlktaelqvaikgrltgkgsadniidsgg---nmlvavs
tpkyqpksgqv--lktsgfhirsfridlstge-----gamscqaeplktl
gsaelal
>node3
klrspakserlndegptq------ksethlmqv--c--tdgsgg-ft---
--hpksadeltqkmtwss-dllaakqaksnkallkchtn--vkffinamg
rqdfkdc-irp----------dcaqaaavkmeqp-v-lyltpael-fccl
vscav--alaalanfklrarr--acraddnvaegkcglns-apvtvnske
--i--mdrhalnskdgdsswle--tlreahgatyyvlekkalksghltpp
hqalcfatdlepfg-tnvsqlikdaplyl--------gvlklielvhglv
g---------mprtcvcshevidwtaglq-rklttkgkftdr-----frg
tlmldfk--kvclmgelcgqltimega-ka----------fkpigsktks
at-vlppgklatvgyenlpkkakqaesaqgysfpn-------stdssrfa
kycdtatvsk---k------qsdneyhdktgkkldgk--karthgpkvcr
gtssa------aqnygtdacaikgkasakdklenvsdsan---eqefdsn
mgkcqpkksqcmleanagpsitsfkvtlengt-----gtekchygplktl
glrqlsl
>node7
klntpaksqrlraedptq------ksitglkqv--c--tdgs-g-nv---
--hprsikdlaqtmaysg-dlaaakqakvnqallkcstn--vefftaavn
shdfmec-ikp----------ecaqqckvkrnhp-i-lylipsel-fccl
vscav--alatlvsfklrakr--dcraddnvaegkvglhg-aevtkdske
--f--mdrqalnsttadsawqd--slsgahggqyyvfektalisahltpp
pkalcigaklvpfgntnvsslikeaplyl--------gvvklielvhglg
k---------lprlclcghavidwtagmq-kkletmgsfidr-----frg
tlmvnfr--klclmgelcnqatimega-sq----------fkeigsktkt
tt-vlepgklatvgyvkqakkakqcgsgmnysfpn-------ssdesryt
kycdtatgpk---k------qnendyhnkvekksdgkevkarthgpktcr
glssagi-wl-aqqsttnacaikgrtsakgkledisdsag---eklfatn
mpkcqpknsqc--vasagtninsfrvklksgk-----gaqkcqyaplktl
gnaqlal
>node15
slhtpgkshrmra---tq------ksfaplkha--c--kegs-g-gv---
--harsikdlanqmdyssiglagaksqkiheallkcsan--vqffktvgd
-hgplec-lkp----------eckvqcrakrhhp-i-lyltstel-fscl
lpcal--mlatginrkfrtkr--pckadgnaakgngalhgtaeglkdsse
--f--keaqalagttsdsawqe--avttthggqyyvfekaglitpqltpp
prafcegarmktfsdtgvsglikegpayl--------gvyklie--h---
kttieytniklprlclcghlilksmadkq-pkletmatfidr-----frs
slmvnfr--klclmgelqyegtivesa-aq----------fkevgsktnt
tt-vlddgklatvkyvkpamktkecgsglnysfsn-------pseesrys
rycetatfpk---k------gkkndyhnlvekknngkaatarahgakths
gtgaagv-wltgqrttehqigikgrtkakgradditdsgg---eilvatn
mpkyqqkngqc--vksaginirsfridlstgq-----gsqkcqatplktl
gsaelai
>node6
kvdapaykvriqandptq------mtatgltqv--n--segs-g-nv---
--hprslkgkaqtmayss-dlafnkqpkvsqailkcsta--iefataeln
shqfmec-ikpkrktalaaylkcahqckvkrshq-s-lfliptsl-fccg
vscavtnaltalrnfkkrgkr--qgrgehnvgdgkvgfhs-edvtkdtke
--fvpmerrimnsnsahaawp---------ggqvyvfakmvlvhavltlp
pkalcdaaklvptgnvnvsslvkeaaadl--------gvvrlldlrhglg
i---------lhrpclcphtvidwnagmq-rhvngmgsfvdk-----frg
svavtly--klclmgqlchqsrvmdaagsm----------ykeidgkekt
tt-qldpgkltvqsyvkaakkppncangkefaltt-------asdnsqyt
kycdtptgpk---t------qnensyh----kkadgkevkapkhgpqtck
gisgagi-fl-ahqsttaacqikgktnpkgklqdvddsag---dklfpsn
mpqclpknsqc--vactgayintyqsklrrdt-----etskckysllkel
----lml
>G
nyhsggkglkmrr---ie------rgiipvkga--c--ktgk-a-gvaqa
dgfpwslkdlspeinytstskpgaag----dnllgckfkktdqfyrdatd
-daglet-mnv----------ycnvqcrshrhrpqm-lilntvslglscl
lfcgl--pavfsmgrwfrtsr--qcnidhiaikgnpvmaaka-alkstpd
--f--aqpkdlegadaavewqg--gvsvanagdgvkfsrhgmlstsvepr
praskgaakakllpgapgditttdgvhyi--------gaygnqa--h---
qeaielqhvdla--cmcghlilhitaddh-pktetmtgyrdt-----ysl
allgklq--klcfqdtqplkldpievl-gvgkhcgflenlyktiestgqp
sskll------nvmkgrpsavtkdcgagqtyafna-------hpeankfd
syhhtclfca---k------gngwkfdglippsdrgrsapslntrainhe
g-gatgd-w-------------kgrksgkgggdniadvsg---dmsitvp
thryghnigev--latngfschtfrlsiaigq-----tekacnsesnktl
anaeial
>C
kadqpaykqriqtndpvq------ktaanltev--lllyegs-g-dv---
--hprpfkglsqtkayss-dlafnkqakasqaalecntt--iafanseln
sqqfmec-lkpkrvtplpaylkcatqakvkrgnq-s-ialvlkgl-fccg
vscavtasltalknfnkrskr--qtrgqhdvgdgklamqs-edvakdkke
--fqpmkkrimns-----hyg---------ggeiyi-skmllvqqvldvp
rkllcdpskliplgevnvsklvqeppadl--------ggvrlldlrhgyg
i---------lhkpcvcphtvtnwrcgkqskhvnglgsfgkr-----sag
svavaly--kdcllrqlchhsrifntagss----------yteidgkqas
st-qlaaglleiqafvkgskkkqncidgkefalta-------asdthvyt
kycdsptgpk---t------adeksyh----kkasgkdikgpkhdpqpck
gvsgesa-fl-arqattascaiegknnaegkleqnnssag---kklfesn
mqnifkknssc--vdctgcyvdtfqstlrkekifvagaptkckysllkel
----tll
>E
aihkaskglrvkv---tk------isfippehastc--qdgq-gegs---
--ktkclktptrllkyytlal----slktpetmlacnfk--sefyrivld
-hcvptc-vey----------psvlkcktrqhlp-v-llqitvllvgpcl
--------mvnplcgifqsqs--kcrakhsgneglealrgfhaaalsggd
pgf--eqasafkgnapavewrs--avsi--------aeketllkaliank
krhntatqdlrvfmgntvsglidctqtfl--------givgleg--h---
qvtvaiainklpplctcgilmlqyegdqp-rdqdpmntylflnqhstfrt
allmtikrvrlclrgeihyekkavknl-dp----------fsqrnvkeiq
gt-vp------aityiepqlvankcggvanggytn-------paegnhyg
gyrrteifpk---ktkdsgnprkatfhkvmcskytaiamdadggagqmha
ttntpnq-sltelqnadiivavkgwlngkgkadkvlmsgg---smyasqq
lsqyhpkptqg--l-sscahirrfqitic-ge-----gampcqadplrtq
gtagltt
>D
mvstpvfkvriqantptq------maqtglkrv--n--cegs-a-nv---
--qcrtlntkaedttyns-dlafn-------nslkcdqs--vafagatvn
apkyqecpvkpkkattlqaylrcthkgnvkrshe-selfviptsn-fccg
aggtvtnaiialrkfqnqgsp--qgqgetsvgdgavdyhn-nevkndtke
--fvr-ekrlmnshgaham------------gqvyifadmllahgvltla
pqslcaaevlgstgnvnvsslvktaaadm--------gvirmadlrhnlg
v---------lqracpcpntvltwngdme-khvkgkgeyidr-----wkp
tvaktly--klclvnrfchgsssmdvtgel----------yseiagkens
ti-rldasklaaqpfvktakkppnceipaeltlkt-------gpndnqyt
nycdsakgsk---t------qikdneq----rkadgkevkapkhgpqtca
giagtgi-fl-ahgsttggcqlkgkidv---legtsds------ktfppn
mpeclpkntqc--vkstgactrkyqsklrrnt-----easrckysllkdl
----lml
>node10
nlhkpgkglrvkv---vk------isftpaeha--c--qegq-akgg---
--htkclktlsrlmkynslalsgstslkssetmlgcnfk--gqfyritld
-hccpdc-iey----------pcntkcktrkhkp-v-lllttvilvgscl
--------mvnpvckifqtts--kcradhagnedkaalqglsagaksgrd
--f--dqastfrggaaavswrt--avst--------fekevllkatlppr
srahagtenmrlfsgnsvsgliecgqsfl--------givglea--h---
kaavevahnklpplcicgivilqyqgdrp-psedtmatyler-----frt
allmnik--klclkgelhyekkavriv-dp----------ykeaaakeqn
at-vp------tikyikpelvpnkcggvagyafgh-------paegnhfs
gyrhaaifpk---k------pkkntfnkimapkytgialdadngiakthe
stktpgi-wltdlktaeiqvavkgwltgkgaaddviksgg---nmlasqn
lpkyqpksaqa--l-tscahirtfritmc-ge-----gamacqaeplrtp
gtaelti
>H
nlnkagkalkmri---ve------qsftpakge--s--rtgk-p-qv---
--hkriakdlppenaydytgispasghkksenllgckfktndqglrvatd
-nkaldl-mnr----------ccnvqcqgtthkaqi-lfasnvnfvfgcl
lfcgl--ppvtsvgrvlrvnr--scdidnfsikgnaaldgiagslkesce
--f--dqpvdvldnaytvtwlg--dvcaanagdgvgfgrhglladilppr
prtfqepadmkllagaggsvtskngvayl--------glygamp--q---
kepiqlqhlylprlckcdhvilhikidep-snvesmahhres-----fga
qrlailq--tlcfmgtlqlklkpvqil-gl----------ykaisgaegp
sepll------nnkkgkpvkvtkmcvpg-----tn-------hakpnkfa
syht----------------gkswkftglippdsrgigapplghnawths
gsgstgt-wlqdltavelqtvgqgrf-gktggfdisdggglpsnmaikvp
thhyqykasdv--livagfqihtyams-ggge-----sngshdskkrktl
glaelsi
>B
klkshakserlgkqgpeq------ksethlgqg--c--tdtsav-lt---
--qpknasdislk-------alagkkaknnkallkcqtn--sklfinamg
iqdfklv-ikp----------ncaqvadvkmdqa-v-lylapaea-fccv
mscvv--alaaladfklrdmr--acriddkvsvdkcglns-ttstvstkd
--v--mdrhtlnqndgastwlaavtltnniggtyyvlhkkklasgtltpa
qealcfatdlgpfa-tdvhqsi--ggvyl--------rsmklidrvngfv
g---------vprvcicgfdvlswtgglq-hkashagrlter-----fia
tlmldfk--nvcllgelcgqvtnmaga-ka----------fkgigtktka
ds-vlppakltpvsvdnlpkrareaestqgysfsn-------sldts---
kycetsgvst---k------qtnneyhdktgkrlegk--kvqthsakvcr
etkda------aqefeaqacaikgkagakdklqnaadhhn---epefdsd
agkceaastqcmleadsvpnitsynvtlengy-----gaekchfgplrts
nlrhlci
>A
qlpdpanserlnedeptqgteanlkiethlghv--c--tggsgg-ft---
--hpnaaddldqkmtwca-dlleaneaksskallncrsd--akffinv--
-----ec-vrp----------dcpqaaavkmeqp-v-lfltnsem-----
--cai--alaslatlklrgkr--acesgdnvaegtcglst-dpvsvnnke
--v--merhsldskdgdanwle--slrechgaayevlekraligghglpa
hqalcfahdlktfg-stvtqmvkdaplylhiftaeqgavlklvalvhgll
g---------mpktcvcsqqvidwtagla-rklgtsgkftdq-----frp
rlmlelk--kvcimyalcalltimkap-sa----------ykpvdndsms
st-vlppgklacvgytflpkktkqpesaqgssfpknmcrapwssdstrfa
ktvdsakvsk---s------qsdnsthdktgirlkgk--karthgpkvcp
gtvsn------aqsygaqacglrgptgaknklklvsdsan---etdfecn
lgkctpkrsqckveagagpasnafkvalengt-----gseqchynpakpl
gvrqlal
>F
slhtpakglrvtv---tk------isftpkevd--c--heve-akgg---
--htkcltklarllkyaslrlkggaslkgcetmlhaafr--dqffminlg
-qccpnc-iny----------pcnskcktrkdtp-m-lllvdvhlvgrcl
--------madsvtkvllttsvlvcrskhganqgkaalqgaaggsesard
--f--dldptfrgaaaavdwwt--vvtt--------fekdvllkapfpav
arahagtenmrlasgsnvsaliecgcswm--------gsvgfea--h---
kaaveqahtklspicvcgvpflqysddrp-dsdqtiaaylir-----grt
aliadvk--qacltdkwhhekaivrcv-dp----------fknatakeqs
st-vp------sikyvkralvmkkcdnvtgyafge-------paegnhfc
gyrhavlfptvrvk------pkkntlnkimadkyvgigldaehglgkshd
htktpglqwlgdlvlpeilvpvkgwlttkalteavikhsg---kklanhn
lakyqakpaqa--l-ptcahgktirvtmc-ge-----garacqseptkhh
gmaidtl
