>B
kvshsmlgkvgvgapktqagtrvrtskkrkds----qlavvpysasvgqi
tvvfinnesitvqktync----t--dd--amcedirw-kksyp-------
l---anvepsvdvglaileestsdpygfhsgptlfvdrvhqgeisakerv
wsgkalcamktlt-emavftlaslhhlcefcypim--lkamdlg-l--pl
----gysahggylgvtisaptecladg-----atnstalrstegesfitk
aad-----ddsdpagqerqp-----kaietstqylqsfipwggspg--st
ccqhgkifsasslqyhgv---ftpanyseydrrtk-yvsagtskltsdrg
lnglsk--ala------ggdafvdkprr-kn--svhgvkh------fgay
-vlfkrhkayll-----spmmk------devptlkkkt--peiplsqdvf
nklya-------------tlrgrslygdheegtddidgenagpp---ame
kgqtsgy-clqvsc-vaislaslqlavvkr--kakhahheggg-ktggyy
mfkldkpyptlpv--gvik--khq---it------------navgssdyp
lf
>node15
kcneevlaevgqdhpkqeagwrvkcakprkel----rlpissyeaivgrv
gklfvhtvleniprsfds----a--vg--tlkdsvrw-ehnhkekgsdmc
laylgggqpdiagglatlltsasepknfdyppaeyvdvtahidsapkarn
wdgashcglkamr---avvllvi--tfckqcypna--lagshmd-v--pl
----svrtkgdylsvmvceptacmhssssstcghdssvndktggatvpkv
sge-----adskt-enekdik--kaqanrtttqylqnwqvyygsvd--sk
tckasrlagagpltn--ashgitgatycdykgwnk-gneaglnavsngsn
lradsk--pla-----------lewprrara--vceetkg------iglf
gimldl-----v-----vesvk------gpigplnktk--pgvaiaqnaa
kklktpvqcgmnkkq---tkhcnslfadkvegtkdgggdeenvglcgg--
ddasrgctsmlkpc-yainlasfhlkaitk--qvhhnhddgnm-klgayf
tygadkpfkhlhg--pggrspseetptlv------------dnltyddcp
ly
>F
lcadvglnqtakdahkhdt-wkvraskgrldlyepgrmsvpsydsiavsi
galflndilpeqikkfaa----d--vs--klkertvlteheaqqsgaekc
lvrlaagqdttsggvpkvmvspsdkkefeyddnpyvkvkgqanlgaknkt
-----qgaqkaihc--aivilvi--swfslafpsi--legdnve-g--pa
----eertkgeyltdlaypptppkqstkatkcennkgarhatpkp-----
--------iatam-qtysdiq--rskpskpvtqflniwenyyplyp--kk
lcsvdrgpgaeplnq--smvaftaatycqfdgweknkvqsaikfaspksp
knpdtq--pla-----------kdwepnpvdpqlcdpts-------vnlf
gihlrl-----vryqtnvhyml------gpvftveatl--phptigyeas
ralkhpvgcglakra---ichcsqllgnvkdqvsksfaqadhvgmssp--
ddsydgs--rmrpc-fqvklihfhvgtvgk--avhadhenvgl-rmvlfy
iyglngplahlhs--aegqatfteyellg------------dpltydecl
ly
>node7
kcneqvlaevgvdapksesgsrvrcqkkrkdl----rlaiasyealvgri
gktfvnvvkeniqksync----a--gg--tmqdtlrw-qhtykakgkdlc
leylagsdpamavslaslltrtceprrfdygpavfvdkvsqvqssskarn
wagaslcglkalk---avvllvv--dlcrtcypna--lagthmd-m--pl
----svsthgdylgvtvadpnacmasgsssscgddssvvkktggaavptr
sge-----adskpadsergak--raqsnrtttqylqsfqvwygspd--nk
cckegklpgagplan--ashgitsaiycdydgwrk-gdeaglnrvtaasa
lngpna--pla------cgggtlewprr-pa--achetkg------fsdy
-ilvel-----v-----lepmk------gaigalrktk--pgtqlsqead
kklntpvncgmnkkh---tkrcsslytdkvdgtkdvggdeagvg---g--
dessrgckclqkpc-yaiglaslqltvvtk--kshhnhdegds-ktgayf
afglnktfkaihg--agvrssnqetpllv------------ngltyddcp
lf
>node14
mcpdgvldqvakdqhkhdtvwrvktakkrkdl----rlsissyesiavkv
gklflqtilqnfprdfea----d--vg--klkdsvvl-qhnhkesgadkc
larlaagqatvaaglqkvlvcaankkefeytptgyvavmsqintapkthn
wdsashcalkavh---svvllvi--sfckqcypni--lagkhld-g--pl
----qvrtkgdylsnmmceptacmhsyststcakdsevadptgnptlgsi
tge-----ldakt-ekekdvk--rskasraatqylkiwqtyygsta--kk
vckkqrvpgagplsn--avngitgavycqykgwek-eteaalklvshgsn
lrpetk--pla-----------wewpkkahv--vcsgtkg------iglf
giklnl-----vrqtppvhyvn------gpivslnktk--pgpaiavnaa
rklkspvdcgmskip---ikhcnslfpdimngtpksggdednvglcga--
ddapdgcksmlkpc-yavnlasfhvatvsk--qvhahhddgdm-klsayy
tyglekpfknlhg--asgdastveaetlt------------dnltydgcl
ly
>node3
kinhnmlaevgvgapktesgtrvrtskkrkds----rlaivpydatvgri
gltfinttainvqktync----a--ge--tmtdtlrw-khsyt-------
ieylanpnpamnvglavllestsdpysfeygpaifvdrvnqsqisskahn
wsgealcsmkalk-emavitlvaihqlcetcypim--lkstdmd-l--pl
----gisahgaylgvtvsdptaclanglksgcadnstavkatngevvitk
sad-----edsnpadaerip-----kadrtktqylqsfiswdgtpe--nt
ccqegklwgagslqhhgpshgltpalysdydrrrk-cveaglskltsdrg
lngpkv--ala------ggdgrienprr-rn--schetkh------fgdy
-ilfqrnmaylv-----lpvmk------dvigtlkkkk--pgtplsqdah
kklyaptncgmnrkg---tkrgrslytdkedgtkdidgdeagcp---ate
kgttrgckclqgpc-vaialaslqlavvkk--kgrhahheggs-ktggyf
mfklnkpfktvpa--gviksskhq---lv------------ngvgsddyp
lf
>A
kiynnmlkqigvglpksesgteirsvknrkds----rattvpydttvnar
altyihsaaindqqnydc----e--gk--klsaslrf-kneyt-------
laflaeanptlniglvtllestgdpykfesgpsihvdrmqqahiaskadp
wsgeaacsmktfk-ekpvaplvaihklcatcypim--lkdqala-l--sv
pgeagmsshgaylgdtvsdptavlagglksgcvsnstaikatngeavikk
gad-----eesnpanaerep-----kadktntqyvdsfiswggapevflt
ccqagklwgagnlqqhgsnhgltpalypdygirpk-cvqadlvtltasrg
lngpkd--pma------ggdvrigeprr-rn--scheakq------fgdy
-vlyrrsmaelv-----cdpsd------evlptlkrkk--pgtptcqdah
rklyasfncgmnkkg---adrerpldtqkeegtghidgnnagcp---ate
kgtirgckclqgpc-vgialtslqlfvnkk--kdrfphhesgslesaayf
mndlnrsftdlpa--siigdskhq---lv------------nvvggndyd
lf
>C
kcdeevlkeaavdaaksakgkrvacnkelqev----glqiqryeglpgrl
hktfvkvlksnlknqysv----t--ggrithgngvlw-tntyarlgkelc
leylaghplaltvgmvdmlkrtyepqrydyappkdvgklnavvhggktrk
wsgtatcglqalk---giipllv--slcrtcypdvsnassldkd-h--tl
----svvnhgeylgfahaepnacgnegsahkcgnksclvppqgglayqrr
ame-----gdtnsagaereik--ksdsn---tqylhkfdvwyacpt--ta
icgntttseggpvsn--psrtvmcgiyvaydtwke-sddaglervapesv
fkgdsa--afa------cheandawpqr-pk--acpgvqd------fsef
-vlle------------laett------gsigaerrth--pgpqlkvisd
skla-pvgkkmdrlvhggalrsasfafepmntskditgedfgvg---g--
netarvcaclqthc-yvaalaglnfsvvav--sshhqneeels-gsgeyy
yfglektfkkigd--kkirgadadskvlt------------sgltyapcp
ly
>node10
mcpdvglnqvakdnhkhdtvwkvkcskgrldlfqpsrmsvsgynsiavki
gklflktilqdhvrafta----d--vs--klkdsvvltehefqqsgaekc
larlaagqdtvsggvpkvlvcpaddkefeyadnpyvkvmahlnlgakthn
-----qcalraih---aivllvi--twyklcfpsi--lagdhld-g--pv
----eertkgdyltdlaceptpsmqststskcekdkevahptgkphlgat
tse-----iaagt-ekesdvk--rgkssrpatqylsiwenyystya--kk
icskqrapgadplnq--amngitaaiycqyegwek-kiqsalkfishnse
ispetk--pla-----------reweknpld--vcsqts-------vglf
gihlnl-----vrkqtnvhyva------gpiftvektn--pgpaisvdaa
rdlkspvncglakap---ishcnelfgdiknqtaksvaqedhvglcga--
hdaydgc--klrpc-ftvklasfhvptvgk--qvhadhengga-rlaayy
iyglsnpfgnlhs--adgqatfteyeslv------------dpltydgcl
ly
>H
lcpigirhdkandrnkherawllkmagnprnt----rlrlrsfsttvvgg
gklykhdmlsyftrefedsdpgg--ig--tlkpsvvl-thllkqnevhkc
lrkspagpttaiadsdkvgvcgteintflytsakdvpsepkvdtgcpnhy
wktasrcalqaqk---qvklrvi--nlckqcytdi--eagnple-atvgl
----qvrakgnfdtslfceparclygysmsafakdvevaesagnpdltsv
tqs-----sngdi-t------rsqaktmreaahyvkgwqqfysttg--kk
vcckdkcpgagpiva--avnditvaaycqaqgwer-dtanplklisr--a
lspdts--plgpshteg-----fnwppkahp--icqgvkqpskgyavg--
-mhlvl-----vrqpgsvhlptlycsvskaalslt-kt--a------dtt
nklenpldapmakgp---irhcecllpsikdsnprsgsggqnaglcgg--
tpapdqcksmlkpccyvislksfntesvarsvklhtqhngadk-klsvyy
aygpekpfkkvngkfssgesniaeastltityipvhqlfkgngvpyegcv
vh
>E
hclevglgevakdnhthdvfwrakcskgrldlsspsrmsisgynneevkl
gklflktilqdhviaftt----dfivs--klanssvlsdneferiaaekc
varlclgqdtvsgavpkltvcpadakeleyaddpyimvgphldlgakthn
-----qcalrain---afgllvi--trykfcfpdv--lasdhld-g--si
----eemtkgefladlscdsasnmqttnnsksekdrdvnhpvgqshlgvt
nsi-----iaagt-eneskvk--kgkfsapatqylalwdnyyshss--kk
ecvkqraagpdplnr--imagrtaaiycdfeewkk-gmqsalsfishnra
vsmivklgpva-----------rdwedlpld--vcsrtn-------lgkf
gihldv-----vgktsnshyva------gpiftvektt--papamsidga
relkcpvndglvrlv---vahcnelfdeitkqtaksvnaddhvalcga--
hkahdgc--klrpc-ynvrlpsfhvpnhgr--qvhqghvggga-platyy
vfglsnkfgdlna--addqaafeaydslv------------dpltyenyl
vy
>G
fctngviseksaeqvsnaavwtlkmtkpkhes----rlklrsferapigg
kklfkgsvlslfapdfeeaepsd--ig--alkpsvvi-senlaerevdkc
fcelpagpntalpegekvvlcsmgknnfdytptstfal------------
-ktvsnctlkapr---qltllvi--afckqeypdr--gagkqld-a--al
----lvvakghfqsdvlcepatclyayatskytktssiadtvgspdlgsv
ngn-----sddkr-t-----mrnrpsglptaaqtvkaweqfygtil--kk
vcekqkrngsgpvtd--kvndkttlaacqckgwek-aleaplkllargsn
lppqtk--plgtghedp-----agwpkkshv--gcqgtrtspseksignf
gmhldt-----srqhagihdil------apvismkktkvetpaasaadak
akleapddcpklksh---tsncdslfpdikdglgkagsegehvglcng--
haageycksmlkpc-yvvsnaefhpdsvsk--glhveeangdl-klttyy
kydtelpfaklqg--atsetgiaqastla------------ehlsyegcl
va
>node6
kcnnevltevgvdagksgkgkrvicqkkrndl----glqidryealparl
hktfvkvlkenlqkafnv----t--gg--vlgngvrw-thtysrkgkdlc
leylagpglalavgmvsmltrtcepsrydyspgvnveklnavvhggkare
wtgaslcglqalk---givqlvv--slcrtcypnv--lagtdkd-q--tl
----svvshgdymgfavgepnacmtpgssskcgddscvvkktggiavptr
sse-----adtrsanseresk--radsntttvqylhsfevwygcpt--ad
icgegtlsasgplsn--aahsvmcpiyvgydgwrk-gddagldrvnaesp
fkgdta--ala------cgaathewpqr-pe--achetkg------fsey
-vlvem-----v-----lgdtk------gsigaqrktr--pgpqlkqesd
skln-pvsqvmdrkhhggslrsasltfepmngtkdvtgeeagvg---g--
nessrvckclqshc-yviglaalrltvvti--tahhaneedes-ssggyy
tfglektfkning--tiirssnpdtkvlv------------sgltyaacp
lf
>D
kpdnevltqvgvaagkigdgkkvacqknrydl----glqiaryegmvahl
hktfvavlkkdlldaftv----v--gg--lldhaghw-grkysrkgkdiy
mqllsgpalsllvgltsmvartcdrsrfeytpgvhveksqavahggkvrn
wtgsnlcgl--lq---gmvtivi--slarvpypnv--lpgadkdsq--tm
----nvlshgdymgfvvgesadcmttghikkcavdacvvkktggiv--tk
sahilfglydnrwdssdqegk--radsnivtrrflhpfdiwyacpt--hk
ic--------gplsn--aaetvmcpvyvayggwrk-gddagveevnsdrp
ftggtq--gla------cgaatndwcqr-se--achetvn------fse-
-llfem-----l-----lvnnh------gsfgadrkmr--agsqlsedsd
skln-pvseildrknqggglrsaalsfevvngtkevlgaeasig---g--
aqtvrickcv------vtglaatrltvvti--tghqkegaden-adegyh
tfglgntfknltg--kiirtsgpdkavlv------------aglkysaca
lf
>node13
fcpngvlnektddqhkhdtvwrlkmtknrrds----rlrlrsfesiaitv
gklfkesmlshfthdfeeaepgd--ig--tlkpsvvi-shnlkenevdkc
lsslpagpatsaadgnkvvlcgankndfdytptndvavmsqvntgckthn
wktasncalkapr---qvtllvi--sfckqcypdi--qagkqld-a--al
----qvrakghfesnllcdpaaclygysmstcakdssiadptgnpnltsi
tgn-----sdakt-a-----krnrsktmrtaaqyvkawqqfygtta--kk
vcskekrpgagpiva--avnditsaaycqfkgwek-dteaplklisrgsn
lppetk--plgpsheda-----wnwpkkahi--icqgtrapgrdtsiglf
gmhldl-----vrqpasvhyit------kpvislkktk--asatkavdaa
nklenpldcpmakap---ikhcdslfpdikdglprsgsegqnvglcgg--
nsapdacksmlkpc-yvvtlasfhpetvsk--klhahhndgdm-klsayy
aygpekpfkklng--asgetsiaqastlt------------enltyegcl
va
