>E
gscnqaeesfssgspgdaectdllkvylqfvst-ngniykggldfplgft
lgsgqapkagrvapmraneqynktgdsa---ifkeltqlqqaiaqs-lsr
nlqdyqawelkpv--vn-flissagyyckatv------lphllnkkpqhi
dvytgaqkae-----lggqteq-hvhfrllygpg--fsarvveqsalidd
ktrssavfknahiswsghltelkcfde---------tcaagp----efav
qayncsfstggaaceltcgqkscagprtfdsltsdqpsmnghiiqasm-i
aesspmgwrvefgyhicgql------krwetnifgnlkqalschekknyl
lvyvdpfmfhrccfvlfadfknrkahiicqawpwggeqelrdqkepavtq
hhldyahtvspkgpdhg-------tkplieelghaqhs-ga-------fd
lkldkgltgkdnlctctpyskvewavggkafvtv---aglvthdk--kls
niphirftptqlrhlgvgc-glkq-kkeqtrgeallslqlgtavlifakg
gqvape---talyavpvgtatnsg
>D
ha---vtqayqppdpnsgtsctllkqyswywddapvphpmttlqygkgig
ikpasdmkggnyaalrhygyfkkeggtaahhcfpvrgeqiksfikaaaah
snvklanwqlqpt--sdkytl-kgg---gsig------tsqddkdlkhen
aiftsgckae-----icpngkealitarvgyapk--faegfyyhgdkkye
tcakagsakksparllyallhfkcide---fdgciitp---p--idefvi
dkyqcgdp-------------------dvehfkgkmatvlesvvnqva-l
hglgkimrigiafyescvvinsldhrskyvaalmsrdlpalsiphqksav
vkvtdefpyp-ccdafvllfqpafrkv------hgganripkhkd-----
----sdksaaakkatsd-------aata-kqdskavynfsp-------fh
-----gvsysdhvksslahpslewgdgafflgqvgakalltapae--akp
nltvsrimvvckpsltmdc-tipvklkrnlkvcdtipkklvnakltyvke
evpvlaeykk---sqssakhvlae
>C
hd---vaeayqpgkpnvssqctllkqydwywedastpkemntldfnkait
qkdakdlniskvitvrhsgyfkregdktthhcfpvrkkqlksilksglak
kevrlaawemapi--iesydi-ksg---saygakgnksvdndeqsikqen
qvtgedgkadltswclhppgkevlivfrvaftgk--ftagfyyqagknng
agqrsaqgnrseirlayalqhylciqe---fegciinp---p--pyafvv
dkyecaap-------------------niedfkgqftavldgvaqqsvdl
heigsilwigvfgyestlvidalenksqymaemmskapsaldisehngvl
vkisepfsfppcsnafilqfkaghkvv------cnganhiprhad-----
----ndnpaaagnvsed-------aata-kenslnlysnip-------fn
-----hlnfkehytsylpypsielvqggffqpkvgtkirlltpaglevsh
glsslkhmcgaspaltlgc-vlpvrlkrkvrvceflphklvapklaltqq
qgvclepykk---aeakgkevhde
>node6
ha---vaqayhpgkpnngssctllkdydwywedasspremktldynrgis
akpagdmkggkvvamrhygyfkkegdntahhcfpvrseqiksiikaglak
snvklaawemkpv--tetyti-ksg---ssmg------veqddqeikhen
qiftesgkae-----lhppgkealitlrvgftpk--ftagfyyqgdkkne
tgaraampkksqirllyallhylcfde---fdgciinp---p--idefvt
dkyecgvp-------------------niedfkgqsatvldgvvnqsi-l
hefgsimwigvfnyescvvieslenkskyvaelmsralaaldiphhksal
ikisdpfsfppccnafilqfkpgskkv------hnganhipkhks-----
----sdksaaaknased-------aata-redslnvyahip-------fh
-----glsfsehitsclaypsidwgdggfflpehgtkarlipptg--asp
klsilrimvvakptltmdc-tipvklkrhvkvceflphklvnaklayake
qdvilepykk---aeasgkhvhse
>A
ee---vtqvydcisaentgscilldtfswfreeaadsrqlgkldycrsi-
-------agktgngmiryttyaksnktpshnyfysmrkcvrrvlkpalck
nvfrvpawnvgsfrdtvtffg-aen---ggfl------lhqdqtdsrfdf
aagtsptadd-----vaqsvkdklmalqmflsnv--mtsafitegsrkde
iaksa-----------ydlvqflcfdeyghlpgsiehp---g--vigfia
kkyactca-------------------dfahpkthgsaalqslaeqal-l
hdflavrwflgynyqncavvhglqklgkyvvdlfakaleflnaphpkgvl
iivsragayppccttfvlqyqassgdiacyewrhvpgqdlqrhtv-----
----c----ipkngsnd-------gghg-wllshetsglvs-------yk
-----daslpe-vgqclvypalawadggafvkehgakqelapppl--tar
klekehilldthlhmgkdc-slkakkkrqskidgavtlklspnkrv-gke
enyipak--r---tssypihrfpq
>node7
ht---vaqvyhcgkpndgssctllkayswfredesdpremgaldyhrgis
akpaqymkgskvagmrqypyfhkngsttvhkhfpgrdqqmqsviqaplek
snlktsawemkpv--tetffl-teg---sgma------veqdqedikhef
qiftesgkae-----lhkpgkekltelrifftpg--ftggfynqgqkkde
tgkraalpkksqislpyalvhylcfdd---fpgciinp---s--vdefva
qkyacgvp-------------------nfsdfttqsatlldnvvnqsl-l
rqfgtigwiavfnyqectviesleklskyvvelfgraletldvphhksvl
ikisnpfsyppccnafilqfkassgkvacygwphnsqadlakhki-----
----sdqslapknaddd-------geta-rqishnvyglva-------fh
-----glslsehvtdclsyptldwgdggiflpehgskahlippsg--tap
klvrnrimlvakynlgkgc-slkvklkrhvkvtaflslrlsniklaygkd
qdvivek--r---avaegrqvhsq
>node13
gtrhrkysnfkcgaggeaediailnvvs--kht---dkdksaldfhlgfr
aepgqnnkgsavdqmrqypqyqktgras---y-----qllqavkqi-lar
gyfrglgwdlqpv--vn-fyt-elafpcksmg------mtrllektprqi
eifktgerae-----lsggagr-lviltvfygpg----adavkggplide
kqqksviaskghdtwpepasqlicycd---vvecalttlggs--kdefpe
qnyscayp-------------------eyvkfttdsatmdqnvvehsm-l
rsagtlgwkctynyqecasggetdahtklpfsfvgklvhklscvqvksfl
iqftgpfkwsricavfglafgskenrgvcdtlpwggdqdlkeeaiseati
pqldddhnlfpkiagee-------tdth-nrvgfg-----israkyfvfh
-----nvtggdhlcavvryarlswgeasrtyrah---aglikqda--wvn
nlkavrftnsakrdlgvpc-gfkv-kkeqlrveaflnlelsaalltyakg
ekigred--s---aanmgpavhad
>F
gechegvdglasgkpgigesnsfvkvylqylst-kgdadkgpldfpvgfv
ltpdhypksgkvadmrpypeydkagkas---afkqrtelmefitkg-v-r
aledyqdwelkav--vh-ffv-algnq--vsg------lghalerkpqll
fiytsnekgn-----lgeksnq-evhqrlffgpgqa--------tvlgdn
ngrqgsifkngnvkwkh-laeikcfde---fgssivtsyegs--nnelvd
enyncsfr------------kpvvgpttynsytshnsamekevmhasm-l
knskalgwrvqfvyqvcgqm------kqlstdivgtlkqelscqqkknyl
lryvnpasnpkcctvfitefkdkhkhvvcevwpwgghqelkaesiahvkn
nhldyeqavspnspadg-------tdlsiedighkqsa-vs-------fq
lifskglsggehlcssrpygmvqwteggkayrvf---aglimhnk--kis
kapqiifhcrhqshlsadc-glkl-kkghsqyidflapkletaisvfddg
lplape---salytvpsspeaysg
>G
garhrkytkfkcgagsaseeysflnvvn--kft---dkdkpaqhfhlgfs
aplgqdhknssteqaraypryrkpgrks---y-----qllqknkqi-ptk
gyfrglgwdlqpv--ld-ayk-elafvcrsvd------mtrlvqkrprdi
sifktgdrae-----laggtgr-llimavfygdg----sddvkggplndd
kqdrsvvvgkghdtwpdpasqlicycd---vvecalataggsgfmnefpk
aeyscgya-------------------syvmfiaqnatmtqkliepsm-v
sssgslgwkctfsyaecdsgaaldahirlpfsfvgkeahklacvqvksfl
lhfggpfkwsdicavfglpfgsserrspceelpwggdhevksealggstv
pelhdeqklfpnaagee-------teth-yrvsnp-----vsrttffvfn
-----kitggahfcnvvkyaklswgdls----------glikqea--yvc
nlkevhftntakrdmgvpvvgfkm-psqylsvegfvdlelkaillvykka
edigred--n---tgtfgasihta
>B
ha---vsqayscgrpgsk---tklkcfswlrdgasdprtmgsllycrdi-
-------kgkkiadirqysysttngkptnhkhfagtsrrersvvkpglck
svfkvsawemkvvmdnnaffp-gep---ggfa------lqqdgkaskldf
qaspvpnsdd-----lhksakneltelqlyfkd---flgafinqankkdh
lgksg-----------edllrylcfde---fpgciehp---g--vgafna
kkyaaqcp-------------------gfsdgategaamlqivaaqev-l
hdfttikwfavynyqactaveslrklekhvvnlflqklktlnapnpksal
dkvakplgyppcctafvlqlqnssgesayfewshvakqdlakqmv-----
----c----askpansd-------dgtg-wklthesyglvs-------fh
-----sltlleqrteclsfpalqkddsgifvtdheanqelppppl--str
rlvrehtmiiaqmnagkgc-stkvklnwqsevdssiplrlkkiqrp-grg
edlirpk--r---tvrhprqvfca
>node3
ha---vsqvydcgkaedtssctllkafswfredagdpramgtldycrdi-
-------kgkkiadmrqytyyakngkttghkhfigkskrvrsvvkpglck
svfkvpawnmksvmdtetffp-tep---sgfa------lhqdqkeskldf
qasteankde-----vhksakdelvelqlyfsdg--ftgafinqgqrkde
vgksa-----------ydlvqylcfde---fpgciehp---g--vdgfia
kkyacacp-------------------dfadpttqgpaalqnaaeqal-l
hqfaavkwlavynyqactvveslrklskyivnlflqaletldaphpkgvl
ikisrpsayppcctafilqfqassgetacyewshvpkqdlakhsv-----
----c----apknaddd-------ggtg-wklthdsyglvs-------fh
-----glslsehvteclsypaltwgdggifvkehgakqelapppl--tar
klvrehimlvaqlnlgkgc-slkvklnrqskvdgsitlrlskikra-gkd
edfirek--r---svshprqvfsq
>H
etrpqqyanfkc--ranaeeiallngva--kha---dkdgsaldfhtgyr
aapglddkgtavdqepqypaypssgrtt---y-----qmlspekev-lar
nyfpslgwelqpt--ie-fat-eiafpcnsmg------mtrlldksprda
aifksgerse-----lsgaagk-lsiltvfygvd----aqaikgvplidd
kgltrviplhshdtwpqpksklicycd---lvhcagtttdgk--kdeypq
lnyqcvyp-------------------eyskfttdssamdqkpvdhrm-l
hsmgalgwkcayayqacaspnetqshtklvgafvgklvhklacimiksyh
iqptgpstwsrlcvviglafggvknkgvcdalpwtghhhlkndfipqtti
sqldannnwlnkiaaekeaiqgnltdth-snvgfg-----iskvkyfvfh
-----evegedhlcstvryarafwcee--tykah---sglittda--wln
nlkgvrftgsgkrdlgvpc-kykv-skdqlrnqaflssnlsgglltyakg
eklgred--g---addmggavtsn
>node15
htrdqvaqsyhcgkpgdantcgllkvyplyradekgpkdmgalefhrgir
sdpaqykkggkvagmrqypyyhksgstsrqkfftgrthqmqsviqvevar
sllktlgwelkpv--tn-ffv-alg---sgiq------vtrdqekkkhqf
qifteggkad-----lhgpageklvhlrifytpg--ftgdvynkgqkide
kgkraalnkkghigwpnslthyicfad---fpacivntlpgs--vdefla
qnyncgfp-------------------nfqeftthsptllsdvvdqsl-l
resgtlgwnavfeyqecsivdnpetlskfvvelfgkliqtldvpdqksvl
irigepfsytpcckvfilqfkaksnriacdswphnsnedlkentisevsf
peldsdqslapqdtadk-------tetp-dqighnvynlaa-------fh
-----glsggdhvcncvpypsldwsdggifypehgsnanlitpsg--kvs
nltqqrfmmvpkrnlgtgc-glkv-lkehvkvdafldlrlsniklsygkg
ddvvlek--r---tvavgqavhed
>node10
gscnqtaedfscgkpgdaesnsllkvylqylst-kgdsekgaldfplgfa
lnpghypkggkvagmraypqynkagkaa---afkqrtqlmqavtqa-vtr
tledyqdwelkpv--vn-ffv-slgypckvtv------lnhlldkkpqhi
eiytggdkae-----lggqssq-evhlrlfygpg--fsakvveqpplidn
kgrqgaifkkghitwknhlselkcfde---fssciitsvags--inefae
qnyncsyp------------kpcigpstyqsftsndptmnsdviqasm-l
resgtlgwrvqfgyqvcgqm------krlsteifgplkqelschekknyl
lryvdpfmfarccmvfitqfkdrsnhiicqawpwggdqdlrensiaqvth
hhldyehavspkapadg-------tnpsieeighvqya-ga-------fh
lifdkgltggdhlcscspyskvewgeggrafrdl---aglithnk--kvs
dlpqirftpvqkrnlgvgc-glkl-kkehtraeaflnlqlattvlifakg
vqvape---salytvpvgpaahsg
>node14
gtrnqtadnfkcgkpgdaedttllkvypqyrht-kgdkekgaldfhrgfr
anpgqyskggkvagmrqypqyhksgras---yfkqrtqlmqaviqv-vtr
alfrslgwelkpv--vn-ffv-algypckals------vtrlldkkprqi
eifaegdkae-----lsgqagq-lvhlrlfygpg--fsgdvvkkgplide
kgrrsaltkkghitwpdplsqlicfdd---fpacvlstlags--vdefpe
qnyncayp-------------------dyekfttdsptlnsdvieesm-l
reagtlgwrvsygyqecgnmdnaaeltklvvelfgnliqtlscvekksyl
irfgdpfsfsrcckvfilqfktksnrivcdswpwggdqdlkensisevtf
pqldeehslspkataek-------tetp-dqvghvlys-aa-------fh
-----gltggdhmcscvpypkldwgdgsrayreh---aglitqha--kvn
nlpqvrftmgakrnlgvgc-glkv-kkehtrveaflnlrlstailtygkg
dqvamek--s---avavgpavhtd
