>node7
fscciisel---vavmnprapgekvlaadtea----gvlgagq--qlkki
vechlksvsvnarqddsddmigfflselgpgatty-epqessqve---q-
-lhgltatqwkegqltgtlvgyggyqge------hygylavaikypksgr
gpyalngclqsht-aatmlpla---fhiskpaqavivvlsapghlclhkk
kglqnnqafcfshnnvekitlayiv-----afqptt-vfcf----ykhvk
--sgvdse-rk-fmtnrdhtkrekggdmyvgvggrqhphkvpeyfs----
----------sacfgg--lsssefakarkmtqaggastwgsganctyksa
dhaasllkgragtrqdsreldlgqwhtfwgatqnrcvsygg-dgspghd-
---lgeiyir-wls-livleygtqplsgvkdqddv-ayiv-lvgk---km
vmqartyitsfvadlkclktfrtdaq---lgrhislsfeqtlvtacckng
ttq-egsiqldv-aishalrdiapnkkdamkgrvkgt-srvdcykkrdgr
atnvklktsq--psftn-vkv--------tgle-ilpqrfqkpip---mt
sty--wha
>node3
fscci--ek---vpvmnckgpgenglgdntel----gvkgagd--qakrv
vechlksvsvhrreedaeeligfflsdigpgatpf-epmdgnqvd---a-
-lhgltasdwkegdlkdalggyggyqge------qygylqgaakypksgr
gayavlgclqshtvaasllplc---vqiskpahavavnfpagghkclhlk
kglqgsggyafshenvakialayiv-----yfqast-lfcf----ykhik
glggvdsd-rk-fmtnkdhdnrekggrlytgkdgrqhptsspeyfs----
----------spcfeg--lespgyckarkakaaggantwgsgptctyksa
dhasellknraltgqdsrklelggwqtfwtagqnrcvt-sg-qgspphg-
---lgqvyar-fls-liilnygtqplaaikgqedv-ativ-gtgn---km
vlqgrstitpfsadlkclkkfkkdsq---vnrdicltfdetmesgcsksg
tss-adsvepnv-avskalqnfardkydarpgrikas-prvdcykksdar
atnvwlnnas--ksftg-akv--------tgld-ilanrlkkpip---ms
kty--w--
>B
fncca--ek---vpamnckapgnngtgdrrel----nlkgigd--htqiv
vechikgvavhrledelealtclflcdvhpgatpf-dpldgdlin---s-
-lqvlaasdfrqgaldselggfgayqad------hfgyvqgaekfprsgs
gaygvlgclqyhageapllpmc---lqiskpphavaaafpagrhrplhlk
sglqgggaypgehesdakislayiv-----yvgast-lfcf----ykhvk
glggvesd-rk-ftgekdqgkhedcerlyqgnegriettsrpavfs----
----------spcfne--lefpgyckaraakssgaantweppstcafksa
dhasqllknsegigkdsrcldlggweafwtagqprctt-sg-gsklphg-
---igqvyvq-fis-laivnfgaealasikgqedv-raiv-etgs---km
vkqgrstlepfsadlkcllkfsndad---vdhdvclafpptmdsacndsg
mst-hgsveqwl-pvamalhnynkdkysaksgrigas-pmvdcytradlt
agnvwanka----aftg-gkv--------tsid-ilakrlkspcp---mg
kty--w--
>E
lvcnlakfl---kevkatragvapgliveafqatspglyfwst--qkgrf
aqcrsgtvklhpaheeg----------------yc-ggdkracis---q-
-fhgfvskqwdkghmgsnfae------t------ntdyltvsikyglysr
lrmsrhkcvlsct-letlaeeq---f-tsfygkarrhllslrkkfisesa
sllvrssayaegdqsddpvalalivrkasfdrlkac-ltdfssvyyqhal
--qangnv--v-fllprkdkdaih---gyvgvadckdaep-pvvki----
----------sscyggleaanaefkndnnmaesgsaevweagaeceyktq
anstrllgnkkkavannpevevaqwlnpfelsnkrthnyge-iwrakedi
qgrlgdlykk-kvk-liglnyvg-tlfyvrgdev----vl-tvgt---v-
-------iipfignlrclkparassvpeehetysvggldpsrpvakcsgg
sle-egrliqev-qfthslrseapepdq-nherirqt-glvgcytiknrg
hdeghlrasw--spigtlvsi--------kglq-eqrrkfkprap---tl
nhyciwkt
>C
fvpcvlsem---atemkphagaslvlktdses----sttgsgt--qrsgi
lgchfksngvhskddgssqmkefvle--gaegdvy-rvdesfhlspsvr-
-hdglaakkwnfgrlagaltaygayaae------nyglleiglkyprpnq
glyglkgclqshn-tltkntld---yhvmkpaqenmvplngpthlvlhkk
kalsgdqafcftsdnvn--gllyil-----pfrsvs-afcl----hvqaq
--svih-e-rk-flsirapskrdkggsdyagvsgrknphkvqentn----
----------vac--g--pasakvsssskvtlaggvsnwnsslncsykts
hqcs--fkarsgthhdtrmvdladwhttngdssegchkhaefagqpghv-
---agnlylr-wlsgiivllyggqplcgasekvntkayvi-gclk---tt
gshakeyvisfiqilkclkpfktegq---rnreialhfsaslipacchnn
tse-qgtiqlhltsishcsedlapkreetkkggvkga-arvtcaawtgka
ldg-qnktin--kf-at-vka--------aife-vlpdpiaepiq---la
gvy--whs
>node13
ylcsvvkll---eaedgtrapeagglivesansafqhiffkaa--etkkf
aqcsqyalkvksahreg----------------sc-dlhkraeia---q-
-fdglipknwkkahltg--lgygp--ge------rkgllaagvmyhtygr
nkfskiscllsya-vqtlerekcwvf-itvlgkaksilldltgkffpdre
gglmhqqtyl---pvaeqieissik-----nrlstaqlsnf----ykhlk
--tgdgvv-tk-flknkrkinrak---myvhigdchtanl-rkseg----
----------dhcagglfdsnsvmqpgdkmaengmgsqwesgddcpyksq
ekttqlvkkgakprfggqdvdvskwqvpwaltgsrgssygg-lakgste-
---kgnfyet-kvg-lvvlefgsdpllyvrqengl-lfvv-pigk---im
leftrsypipfngglngikgghsqrhtpakgrktagnlesglpaancang
tfe-dgplvqav-hfehniddqnpgiktahhgevrag-srmgcykrierp
dannrlstaagsdgyta-isi--------kglq-flplkykkk-p---iv
tay--wka
>H
flcdvidkl---eaedgtraptagalivksipgslqsiffyei--etkka
aqcaiyalkiksvhreg----------------ss-elhkrthva---q-
-fhsliplsslkagla-----ygp--gpfatqlitkvvlaqlnmyhtyni
nryrqitcllsy----------ywdl-itvlgrskpilltiigrlfpqke
gglqhqqafl---avaeqvplssik-----drlgtapiahf----ykhlk
--tgdggv-tk-fvnatqkfsrar---myvdigdchttdl-kkseg----
----------eecvsglfdsnkkaqpgdsmaeagmdsqwesndecpyksq
ekptqlvkkgekprysgedvklskwstpwaalgstgssygg-lskgsse-
------fypv-kvs-ltmldfgsdpllyvrqedgl-lfvvhpigk---fm
leftkqypklfdggmkavkdgntqkhspakgnhtagifeagvpagncahg
tfeqdgplvqav-hferslgaenpeikalnhgevrag-ckmsclkhieri
eannrlsasagsggita-ysi--------kslktflptkykqk-pfakiv
ytc--wqa
>F
fv---atfl---tlvkatrspiaaglvveayqpkfsgelywst--qsnrf
kqcrqstakahaaedgg----------------fcnnanqralis---r-
-fkgfvakqwnkghpgntfsklgs--st------nfgylavailyhlyap
lkiskpkcviaht-lhemeqda---f-ttkggtgkkqllplcskftpdqe
rlllrtkstilseqgddrialallsrkvafdrlksc-qidf----ykhal
--kddgpi-al-frlprrdpkrer---ayvvipdckgpep-pkskg----
----------ahctgglvsekcdfkkdkrisnangc----------ykpr
ghvtqligqrkkaigpkrnvevgqwlvpwgfdtarthtygg-lcrgkde-
---lsdlykk-rek-mvtlnfvddpvffiradrii-pftv-kvtr---iy
lglpahfmipfhgglkclqpgrtndlpkahqkhaigglelnlsvascghg
sfa-dfnvfqnv-dfteslrseeneaknsdhnetsnpegiitcykqkqrg
nksghtrgtw--avfqkliai--------kglh-edprefkpthp---sq
gsyclwka
>D
ltsctlmaq---vkvmrnnapasdtlaaghet----galgagrffeiqdi
lechltsanvtsradesthmvdfils--genpety-qpqeqaqhnpavh-
-legintkvwrhekltgelvgyggyayt------hygllsdglkypngnq
gpyalkgplrsht-satkmnpg---ghvvkpsdtmlaalnavvnyclpai
kglqgheafcfttkeie--giayit-----kyqfvk-vycy----yihqq
--svvhia-rknvtsireprkrdkgtngyvgiggkklphkvpdnsr----
----------sgcyra--lassefsssakvkmaagvanwetqldctyksw
heat--fntrsgtkhevrdmkpadwhkaagapavghhkysefngspgqv-
---lgqvyir-wlktlvvlqygghpicgvtqkvt---lfi-tcnk---sm
vnhardyissfvkllkclktfktdgq---pnlh-------tlitaccqnn
vse-egsiqlhlvavsrcsaql---kkeakkgqatpg-gkincaarrskr
eegvkhnavn--qffts-vkt--------ggte-vlsdqsddpia---la
sty--wrn
>A
fsccf--ekmlkqpvascksageaglgantel----gvkgagd--takrv
qnchlqsvsvtkreelaeqltgyfvs--gpgstpi-ewkggneve---aa
vlhgleaaewkekdikeiaggygayeae------dygylnvtdkygksgr
gaytilgclqghtva-sllplc---vhiskvthaiagnfpagh----alk
qglqgsgvyanahesiakaelvynv-----tyqaaa-lfcf----ykhtk
giegvesetrv-iltamahgnrekagrlyagkdskhhptsspqyfs----
----------spcfeg--lenpgfcknqsgkpagaansnpnggtctyspp
ahtsellknravagqesrklelggw-tfwtagqsssvt-gg-agapphk-
---kgvvyar-fld-lfilnygtgpadqvkgqehs-ativ-atgsgacka
--qarktadplsadlkclkrgkrvaq---vsrdicltfaqsaerncsksg
tlq-sdsvdpnv-avykaqqrpardky-------sas-prvdcyakegir
vtnvslnavs--ksfek-lkvcpecwgkrtgld-ilpnklnkpif---ma
nnf--r--
>node15
facciiktl---vaiknprapgekvlvsdseasyygdvlftaa--qlkkf
aqchmnavkvnarqnda----------------sy-dphetahvd---k-
-lhglipkqwkkghltgtfvgygt--ge------hygylavaikypksgr
gsfamngcllsht-aqtmlqee---f-isnaaqgrmvllnlpahlclhkd
tglmhnqafvfthnnddniklavvv-----dfqptt-vfsf----ykhvk
--tgagaq-tk-fmtnkhdtnrek---myigvggrqnphslpassg----
----------tfcfgg--lntsdfeksnkmaqsggaetwesganctykia
dqsaqllkgrsgarsgprelemgqwqtfwgatqtrcssygg-egsgsne-
---lseiyvr-wls-livleygneplsyvkddddi-afvv-svgk---rm
leqarayetpfsgglkcvkafrsdsh---mdrhtagpfeqtltaasckdg
tae-dgslildv-afthsireeapdmknanhgrvkgt-srvdcykkrdnr
atnvrirtsh--pgfva-vsi--------sdlq-ilphkfqkpip---mt
sty--wea
>G
ylctavrll---raaegtiateagpvtvesamivfpkmlfkas--dtidf
aqcsqyaiyvksahreg----------------sc-dlhkraciv---e-
-ftslipkdwrkanmig--lgya----------------eigamfntfgr
nkfsmlsclfvya-tqtldrgicsvf-itvlakqktillelcekffpdre
gsliwnqtml---pvsdhieikeik-----nklstseissf----ykqln
--sgdgvv-ak-fltskqkinrak---myvhvgdchtlnl-rksegiqca
nysaqensdkehtagslfgdngvmqpgdkmadhgmgshwasgvdcpynkh
irktefvkraanapyggqdvdtskwqvpwmlsgskgsgygn-lakgsta-
---ksdfyetikvg-lallhfgggplfyarqagsl-lfvv-pvgk---vv
rdftrsspipfngglhgfkgghsvrhpppenrkqqgnlennlpgagcakg
sfd-gnplvehv-hfehdhdgedrgiktahkgnvrgg-srmgkykrierp
ddnnrlstsegsdghtd-isv--------kdll-ffplvlkkr-k---ii
sry--wka
>node6
ftsctvsel---vaimkphapgekvlaadhet----galgagk--qikgi
lechlksasvnsradestqmvdfvls--gpeadty-qpqestqqnpavh-
-ldglaakkwklgrltgdltgyggydge------hygllavglkyprgnq
gpyalngclqsht-satkltlg---fhvmkpaqavlvvlnapghlclhkk
kglqgdeafcftsknve--glayiv-----afqtit-vfcf----yihqq
--svvhse-rk-fmsirepskrekggnnyvgvggrkhphkvpdnsn----
----------sacfrg--lsssefasstkvtlaggvsnwgtsldctykas
hqts--fkgrngtrhdsrdldltdwhtangastagchkygdfdgspghv-
---vgeiylr-wlsglivlqyggqplcgvkekvdvpayfi-tcnk---tm
gshardyissfveilkclktfktdgq---snrhislhfeqtlitacchnn
tse-egsiqlhltaishcaadlapkkeeakkgqvkgd-grincaarrgkr
negvkhktln--qyfap-vka--------agle-vlpdriedpia---la
sty--whs
>node14
fvcsiikll---dtikatrapeegglvveseisafgdiffrsa--qtkkf
aqcqanalkvnaahkeg----------------sc-dphqrayvs---k-
-fhglipkqwkkghmtgtfvgygt--ae------hsgylavaimyhtygr
gkfnkqgcllsyt-vqtmeqek---f-itnvgkgrrilldlvskfiadre
sglmhnqayvfthsnddnielsliv-----drlats-ltsf----ykhvk
--tgdgav-tk-flsnkrdtnrak---myvgvgdcqdpns-pksag----
----------thcvgglfqsnsemeignkmaengggenwesgaecsyktq
ekstqllkkrskprggahelevgqwqvpwgltntrsssygg-egrgsne-
---lanlyts-rin-lvvldfgdeplfyvrdenai-afvv-sigk---im
lelargyiipfsgglkclkpgrsdshppakdrhtvgslestlpaascsng
tfe-dgsliqdv-qfthtirdeapeiknanhgqvrgs-grvgcykrknrp
atngrlrtan--agfta-vsi--------kglq-ilphkfkksvp---il
tny--wka
>node10
fvcslakfl---kavkatrspvaaglvveayqatfsglffwst--qsnrf
aqcrtstgkvhpaheeg----------------yc-ngnqravis---r-
-fhgfvakqwnkghmgstftdigs--st------htgylavaimynlygr
lkiskqkcilsyt-lqsmeqdq---f-ttnvgkgrrqllalipkfipdre
slllrtksyinseqsdepialalivrkasfdrlktc-lvdf----ykhal
--kadgpv-dv-flssrrdsnrar---tyvgvgdckdpep-pkskg----
----------aqctggllaansefkndnkmadnggaevweagaeceykpq
gqstqllgkkkkpignkrevevgqwlvpwalsskrsstygg-isrgkee-
---ladlykk-rin-lvvltyvdepvfyirgdqii-pftv-tvgq---il
lelprgfiipftgglkcikpgrtnnlpqahdthavggleptlpvascgng
tfa-dgsliqev-qfthslrqeapeaknanhdqvrqs-givgcykrkkrg
ntsghlrstw--asfdklvsi--------kglq-eqprkfkprvp---al
nsyclwka
