>node14
lcngkitykgkngacenymsqgske--vrtkhglpvqlllaapqrp----
------getaalhlqfiyqf---vliekvgspdvdkht-----gydaeha
kdsgdwwid---msgafy------i--vqytai-ded---hfgn------
----iykv----kfdkkshylcqe----rgkwkkpaq----vvnklmgsv
vlkvcdmngilflsrgagvkvvkykca-qgykcrvahvwak--ltdysky
ggctgwykkgigaveettkslgawkawk-igrfqptlvpeh-ilslk---
--------ekt---d-------------fkiksgaegd-hggvcfqtndq
taletklwphn---pidclskkg---nlrhgqtsgnlyllasgns----l
dtgreylaahcalaytklgpeaiskpggwqladkpthalplprdpsyevp
gtygqhsaqllqqgttcglckhvpkgtqtimhvtrkncsigdeafavkck
krf----lgpqqciqdvdvnpshkqckspgftemhnvlgseafevtwksc
gcyqdqdelgftflltsk----------qvqcavgrgpenhsltqsfeav
f-hvlfdan
>node15
lcsakitykgkkgacqryksqqpke--cntkyslpvqlllcgpqrq----
------gatatlhlrfvyrf---vlvekvgspdvdkhv-----gydknna
rnkgdwwvd---msvafyllrssei--iqysai-ded---kfgn------
----gikq--aesfdkkseylake----rgaykkpaq----ieknlmdqt
vlklcdlnpifflsrgagvravkyacn-egfichvvhvwak--lkdysky
ggcthwyqkgveqhyertkslkiwpawk-lgsfeptltpeh-vfhadakr
-------kgvt---v-------------fkkkseaygn-rgaicfqannq
tsldtkfwphn---pidc-skke---slrngpatgnlyllanaht----l
rggrdylaahcalaynklgpeairkisgwdtldrhtealplapdthyhip
gtygqqsahllsqgancslskhapkrthttmetekkkckigdevfavkck
krt----lg-qrcfqevdipsthkpcksngfskmhgvlgseafgvtw---
-cyeaqdllhytylltet----------hvacavgkdredhsltqtfeav
f-hvafdan
>H
ltgadtpykssggtcddflsdasre--vttshplgsdlrlpvnpkp----
------gnsgallanivyeyrcsklikklgssdvekcg-----gydgska
ndknswlvd---lpsafy------i--irfaai-eek---ffge------
----tfsv----rlekkhltlcae----rgdwtrtqg----minkv--av
vlkgcelmdivlltgasptgvy--------ykcrvkhiwae--ltdyaky
gscirwcrqgigadnersktltcykyft-tgrfqatkyge---vsln---
--------pla---d-------------ikvqgnaefe-agtvcfdtndh
ntlqgklwvhd---pkgcmfakrltcklr-vqsggklfiqesgsa----m
dysrffmrlhcafaykdlglahtpkp-amqlkdska-lvalpqnpdytvp
gtygqnnpqflengvtcglcyaihghtqtfmkvtvvkckfgaasfgdkch
krflksllppalcihevnvspyhnecqtpgftrfldpdkatgilipwknc
-cymgqssl-fsyvlatt----------aiqcavgrgaaqdcv--tye--
------atg
>G
laesraaykgnqgvceeylttnske--lsttthlpaqlrlptvrdp----
------edrgal----lyeynciklieklgsaevekcs-----gydggka
marghwwid---lvgkfy------i--irfaai-eek---kfgn------
----vfav----rlpkkghylclr----rgkwnkpeknekmvhskl--tv
vqkicelkdisflsrgqgvgiyryrcc-egykcrisqgrak--lssyaky
sgclrwykqnvgaaddkmktfacyssla-agrlqavlige---laln---
--------pka---d-------------tkfnsaaefd-pgavcydtidd
stihaylwphn---pdnclfakn---kls-aqsggslflqpngga----l
ptsrffipphcafpyikigltftpkpggldlkddkt-ivalprnpefavp
gaf-qhkprflqngkncghcthvpggsqttihimivnckvgtavmgtncn
krf----lpaalcvdqqaldtvd---aspsftkslkvrsappleiswknc
-cymgsnelgfkyllaar----------aaqvavgtggqdecvtrvysdp
flhllfavg
>B
lcasktvynnamfacyqyrntnstl--cnctyavkhllvaghnlvg----
------qknetlhfravsgf---ipvnkaa-pkieehg-----enseete
-akgkwwlq---gttsflkarkgli--asyivemdlkskpelgplakkvg
hveygsds--vqkfnkfanhlsad----rvsyrnpav----edcgvvdaf
ylkkcvrsglfvinygrklrshscgna-ialpchvvhiwav--llgcgdy
qvyqqwfhklssshkevsdnidswdykk-ilyfk-dtadnqtvfhaaadn
-------keav---e-------------rvkklswynk-egdaslpai-i
rcldtaywple---pvdy-tkke---sfrdapasgkivyygdskscskkv
ragrsfvpadsllvytalgtgaakgtygledmnshqaavalspgthyhrn
ggfqhkavhlhs-gtecsannklsmraintyvtdqkkckiasphfdgnca
ksk----lh-rqcyqpadpakiwaackqsvlitppkisnseplgfsw---
--snqdelvhfrasngti----------rvrgatslkqehyrliptfdgk
f-hevynta
>C
vcvrkkvykgpavgcanykngserd--cgek--dtvmlmscetlhq----
------gvagelhyriskap---lid-kag-pacdrhs-----sytqdsv
wtkhkwwln---lvvpfahlnqddvvnvatild-aeq---kvghlstsvg
lvgfghkq--sdpfdvaaggltsd----qgvfks--------hrnlvgvq
ylklcildavlsvdtgpevkdvkfarp-agfifhivhlfal--lkkcgkd
lsystwypkgtaqpthskkslamwdawk-iiktntsftepktvlknharh
pivldgdiggs---a-------------ygatyiwfek-hegccspad-l
sslnnkwwaklqrpkvgc-arke---ipqdgttigakffeg-twe----t
ksnksalpansfvafegagpnstcgvygdqtldchspilplgldspfheg
grygaaalrlykqghactlrqesrknteacsessdskdvialdrfhvlca
eea----vg-kanypdggvpnkwsrcmaalftglagspdaeaagtgw---
-cyegsellnnhwykehg----------rfngaakkdhkahvliprfeqk
f-hdgfvag
>node13
laeskvaykskegaceefltpssre--vstthalpsqlrlpvppkp----
------gepgsllaqflyqykclmliqkigssevekcs-----gydgeka
qdnghwwid---mpgkfy------i--vrytai-eek---yfgd------
----ifav----rlpkkghylcle----rgkwnkpek----vgnkl--tv
ilkvcelkgisflskgtgvgvykykcc-hgykcrvshawak--ltdyaky
ggcikwykqnigaadetsktlacykswt-tgrfqatlige---lsln---
--------pkt---d-------------ikvnsgaefd-pgavcfdtndh
ttlqaklwphn---pkdclfakr---klr-aqsggslflqpsgna----l
dtsrfflrphcafpytklglanvpkpgglqlkdakt-vvalprnpeyevp
gtygqhnpqflqngttcglcnhvpggtqtfmhvivvnckigaeafgrkcr
krf----lpaalcidevnvnpvhkqcqtpgftrfldvqsapalevswknc
-cymgqnelgfsyllask----------avqcavgrgpeddcvtqsyeeh
f-hvlfavd
>node7
lcsektvykgakvacqhykntnpke--cntkysltvllmlcvplsq----
------ganstlhfrfvttf---vlvdkvg-pdvekhg-----synednq
wtkadwwld---msvtflqlrsmei--vpyivd-dek---kfgnlakhag
hvdfglkl--gekfdkisdylasd----rgtyrnpai----pernivddt
ylklcildavfvldygpkvraakface-egiichivhvwal--lkdygny
qgytqwyqkgttshterskslnmwdawk-ivsfnpsitqeqtvfhndakr
-------kgdn---a-------------ykkknswygk-qgdicfpad-q
ttlekkfwpls---pvdc-skke---slrdgpatgnqylfgnsrt----l
rggrgflpadsflayktlgpasvrkvygwdaldshtaalplapdtpyhma
ggygqhsvhllaqgtncslrkhsrkrteatmvtdqkkckiggehfavkct
kkt----vg-qrcyqegdvpniwtpckanlfskahgvsdseafgiaw---
-cyepqdllhytyfkanp----------rfngavakdhehyrliqtfeak
f-heafnsp
>node6
lcvekkvykggkvgcqhyknatprd--cnakyadtvmvmlclplcq----
------gvagelhyrfaktf---llddkag-paidkhg-----sysedsv
wtktgwwln---mhvpflqlkqkdvvnvqsivd-dek---kignlsnnvg
hvgfglkl--sdpfdiisgalmsd----rgvfknpaf----pernivget
ylklcildavlsmdygpkvkdakyacp-agfifhivhlfal--lkkygkd
lgyspwyhkgtaqpteskkslhmwdawk-iisvnpsftqdrtvlhneakh
-------kggn---a-------------yatkniwygk-qggccfpad-e
ttlekkfwpme---kvdc-akke---takdgptvgnqyftgntrd----l
kgnkgfiptdsfvafkamgpnstrglygwqaldchntilplgpdtpfhea
grygasalhllgqgtncslrknsrkhteecvqgedekaliglehfavkca
ktt----vg-htcyqegdvpniwtkcmaalftgaagvpdaevfgtgw---
-cyepaellhnhyfrena----------rfngavkkdhkhyvlippfetk
f-hesfnas
>D
msveknvykaskigcnhwkphtard--csnkyeesiiavvclglcqllvg
fkflckgvasdlhyrfsrtf---lhdekvg-petdkhe-----sysedse
wskagwwlk---mvvaflqlmekavvncasiid-ded---kigdlgneag
hvgfdlkl--sdplniiasslmed----rsvfkdpnf----perkivgqt
ylklcnletvlsldcgprikeapyvciksgivflivhffal--lkkygdd
lgys-wynkggsgdlaskkslhlwdawk-ivtadpwltedrgvlhnflkh
-------kggs---shkdpdldciylgkyvvrdiwfgk-qggccnpsh-n
d-iqkkfhpma---kpdt-akke---aakdkptigseyftgtard----v
kgkegf-pqdgfvtfkavqanstrglfgyqelechtviltlgpddpfaag
grygssalhllgqspsstlrtdgkkhtdecvqggdskplvgldhlkvkcs
ptt----ig-htcvqegdrshvwtkcvaalfpggpgvpdaevfgtgw---
-cyastkkkhnqyfreha----------rfggslkkdlkpfalitafetk
f-aetfhas
>node3
lcasktvykgakfacyqyrhtnskl--cnityaitrllipgvplsg----
------ganstlhfrvvstf---vpvdklg-pnvqehd-----ehsedtr
-tkgnwwld---gtvnflklrkgqv--vpyivd-nqktkpeygalakhvg
hvdfgaqv--gqkfdkfgdflaad----rgtyrnpai----eergvvdat
ylkvcvlegvfvidygpqlrsprfgsa-ealachvvhiwav--lkdygny
qgymqwyhkltsahkersdninmwdykk-iltfn-dtaddqtvfhndakr
-------kesg---a-------------ylkksswykk-egdaclpas-i
ttlekkywpls---pvdc-skke---slrdgpasgnevlfgnsrtcsmkl
rsgrsflpadsllayttlgpasqrsvygweameshtavsplapgtpyhia
ggfehnsvhlhs-gtqcsankqlrmrtvntfvsdqkkckiasahfagnca
ksk----lg-rqcyqpedppnvwspckasifatppkvsnaesfglsw---
-ctnpddlvhfsaskgtv----------wykgavslkqehyrliptfeak
f-hetynsp
>A
lceakiaykgdkficyryrqtndki--ccisyqvtrrlfagvpise----
------saasilhfrvvstf---vpvgkla-vevqkrk-----ekted--
-------------tvnflklkkgqs--lpyiie-hqntkpeygalakhvg
hldfgakvifakkfskfgdflisddkslsgtygnsai----aergvvdva
flkvcvmqglfvkdlgperrnppyhst-dalacqvihiwai--lknygny
egfmhsfhklvsahkirpegenmwyytt-ilkfn-dtsddqtvfhgsagh
-------knsg---a-------------ylkksswykk-egdaclpps-i
gtlekkywpms---pvdc-pkks---slkdgpssggeilfagartckmkl
rss---lladsllafialapvaqrsvygwdamgshtsvpplapgtpyqiv
agfeqssvvfhs-kdqcscddqlrmrtvntfvsdqtkckveanhqagdca
kyk----lg-qqcyqpqdpnnvwspcrtpifaspsktansesfalcw---
-cngpsdlvelsaskgtv----------wnpgavalkqdnyklvptfqak
f-hetynsp
>node10
lcngnvtykgkngleeslmrqgskd--tktkhglplklflaapqtk----
------genaalhaqfiyqf---vliqkggnpdvdknt-----gmdndha
kdsaewwid---kngtfy------m--vqysai-deg---hfgq------
----iyka----kfsksqhyakqm----rakwqgpae----vvnrlmgsv
vlkvcemhgilflssgsdvkvlkykcp-qktacrvahsrtk--vtdysky
agctgwykkglgevqqttktlgahkawk-ivrfhpelvpeh-ilnfk---
--------ekt---k-------------y-iksgpeanqhqevcfqtndp
tlleaklwrhg---piscnskng---hlshglssgtlylikspdf----l
dtgkeylgvncalayaklgpaaiekpggwqltpkpthslhlprdps---p
gsyglhsaqelqigtsaalckhvpkdtqtrlhvnrkspnigavtfwtktk
kgf----lgpqhcaqevsvnhghkqcksplfvemtislgpqafqvswksc
gcyndqddygftfslysi----------qlqcavgrgpeghalhpvfipl
l-hvllaan
>E
iyhgnltykgknelegtlmkqgnkd--sekkdgfpldlfiaaphnn----
------gdkpghhaqfiyqy---vmahkggspevdrtikkilagmdneha
resqawwid---kngtfy------m--eqysav--eg---hhgq------
----nyka----rfnslrhfgqek----qspwqgpte----lvdrlrvkv
vlkvcamhavlsleagsnlkvlkyacp-attacrvspipdn--ttdyfny
agcttrykkglgevqqttkdlgthklwkdivrfrpqlvpeh-klyfk---
--------skt---k-------------y-gnvgpeadqqqdvclrtddp
glvaakpwshg---plgcnpkdg---hfsealldgtlyliksadf----l
etgkyylgvkcavpygglapagiekpgafelagkpshslhlprgps---p
sthgihpsqehkitvsallcshvpkdvhlrrhvnrkfpnegastfwtdtk
vgf----mapehyatqistnhgvkvcktalfvvavfslapktfmlnwrsc
scykdtgdyglvfslygv----------qiqctvgknpqghavhpiyial
l-qvilten
>F
pclggpsynnndgveeflqrqgskdsftkdkl--plmlflaapqdl----
------gqaadlhsqfisqf---vmiektgdpdvdkat-----glddqhi
knasdyweathaktftfy------m--vqhsvi-hes---hfgk------
----ifkp----kfanaqhyakqs----raswqggad----vvnkllasd
vlkgcekhaililpsssnlkvlkyrcf-qvtackvahvrskldtteygky
sfcagrfkegqvpaqhntkalgahkgwr-ivqyhpslvpek-ilnfk---
--------ekvtthk-------------y-tkvgpeatrhrslcfqtldp
tlleaelwqhg---pfccnakyg---ghdhglragavyiikspdf----i
ntgkekpgldcalvygklgtaglekpgdwqltpkprhtlhlpkdpt---p
gsygahsaqnlqigtsaalckevpkdkqthlqvnlkspnvvadtpwtknk
kgf----lgphhcekevsvahankqcknvlfvemtigngeqgfqvswksc
gcydneaeygltfslfmlvllmltdvagqlacalgrgpnadalhpvyfil
l-hllyagg
