>E
vdegkngyvapkkyf-eqrpseiytdmpwhgsyvc-gandygfnkh----
-------smppdnf----asyalavat--qwdihpqkqlpgygfaavvsn
riakenpl--ttsehnerrtgftnqglkeleivc-amhkrlnpgillget
mgvli--kyktpm-v-vnglkvqrestsft--fkaiekdl-wfmddng-n
lasknplayqeaddqydgqk-gsapgsshngqe-----vngpyvdkhpfq
evkittklgld--------kdfslalgprtakhkfpgldrvqvnakpflt
ccvvlrspe-hsqpeg--nltqryvgtnrapthreknapsgic-elfggp
csgqgte-t-----lhlepnflevldnrgeplie-lvkhpgdkd-----t
aaakptdsalefcksmkf--egpkpadstmssqgpkepdikgt----ten
h-k-rsc-------------sptiknvaltkeadrefdfalalrvkdhek
ck-ccefagtpqyy-rksrdlsiqssnda-mkdltrahgpgtyqcckvy-
-----lystknadahlkhpsyahriessr----q-srshqdsgvdkfqqt
algekq
>node10
-------------yl-eqradeiytdtpwhgsyic-ggddygfara----
-------snapddf----asyaiavat--qwdihpakqlpkygfvamvsn
kiqkeapl--ttsdddksrtgftsrnlmelelva-tmhkrfdtgvlipet
mgvli--gyktpm-v-vtgskvqrdnstft--fkavahda-wfmddng-k
laaknslayqeghdegeghk-gkapggnhgkeg-----vngpyadqhpfq
qvnitpklgld--------rhfslahgektakhnhgpldrqfvpakpflt
ccivlrspd-hs----lpdltdefa-tkrapthmekndpgglc-klfagp
ytgagte-t-----lhlepdfmtalynkgepmie-lvkhpgakd-qimqr
vnaspgngalefcknmay--qgpkvavstlncqppdepnlkss----thk
r-t-rac-------------npvltnidlhtethktfdfpldlplkehem
ci-ccefaatpqyy-rksrdgsiakanda-mkhltrslgngtyecclvy-
-----lyatqkadahlkhpyyahkmpsar--fvklsrshqdrmvgkfqqt
algesr
>G
-------------yv-dkrlleifdatlwhgrqvc-agekfgfgktvndc
caknkklsadaeqf----acfgrntat--kwelspgpeisnfkfgdllgf
evdkgt-lsrsickkqkshseptthssyeldlrg-tmnkrhgrsnmlcis
iglfn--afrtpslevaeavtlhqqdntfpgvskaiehea-wfpadfg-d
kvnnmalagdeapgegygdg-grgpsgkhakda-----sngssandklyq
kvkaspklgln--------rsfnvvkaatnkthhhqalgkhvtlemklml
tliglkppd-yv----rpelnapta-atksasnkerknacgsc-allalp
taggtnd-c-----vnlepvyigalfsirlkaid-rvastgadv-sisrl
tregqtsgdlpfcknhtf--lsgplstqtacctpsksehfkrt----thr
sl-lpac-------------aprlnglvmqpdstidfvfeldlakvahkp
cv-ccdnssseeyi-adnsdtkl-rigds-meqstaklngfeyecafeyc
e-------vntdaselksdfevpnaqrpk--fiklntiphnkaverfqks
mlgger
>node15
-------------yq-eprsneiytgtpwhgtelc-agqkygfdrs----
-------ksapenf----tslavayat--pwsthigkqltkftwvalaty
kitkeaplqrsisedkqaiqgfisqnckelrlgy-kmhktfnngnliyai
mgaar--syktpa-v-gagtnlphlnstys--fkaaahha-wfmddsg-n
ihpkksldsqngheedeqdg-gkasggnhgrnt-----vngpyadenpfa
rytmgqklsln--------safpvvhpqssnshtfgslnkhvtgasky-c
gcivirptd-hv----ipdltdefn-psrspthkdrseavgrc-nlfakp
aagggsd-s-----ldvkpefltalyghaepmidklvdqpgvka-qvmql
vkagvadgllefpndley--lgpkisvsnlagqaadgskykkt----sqk
s-p-rac-------------spvla----qsdvhlqfqfslnlaktqhkf
vt-ccdsilpakfc-rrpkdadittedea-ndqlaqritggtfnccfgy-
-----lyvtqsvgaklrhdfyahktsepk--lvilqkveqekacgkypka
llggsr
>node6
-------------yqndplcdeiytmlawnevalr-pgqksvfdrp----
-------nnangkf----hdlkpayvk--prsthddkklsklawsplaly
e-tkesplkksysetrqlvqgftaehc-eialsi---------geilyga
mssardhaykipk-c-nagttpthlhsdhk--ikcsagva-wmmedtv-n
rnpkhsfdptagnkeyeddgngrspgtshsnks-----vngpyagenpia
rddmnepldln--------nhyqatasqaslshvfavlhrhvvlavnf-c
gvlacrptd-hv----vadrsndfn-paretkkrnqceaammf-dlydtq
ptgeggepn-----ldvnpeflaihfarpdpclqkmveqpavka-eirqv
ikagnveelldfakttvlsmlgteyfaarlngqdpagckytkt----knk
s-p-rac-------------stvvd----qcdvhldfqfplekckkqekl
iktccntslqgkyc-krirdqagdsgdee-ddnrghpttagalscyyef-
-----wyv---vavklrlhfyvhkpsnpg--ltlvpkvaeeeacgrfsks
llagnr
>C
-------------yqndplchpiytmmaw-----r-rgqtsaydip----
-------qsaagkf----hnlepvyla--pvpthedkqisrlawsslaly
d-skesslknayketrelcqgftcehc-aravsi---------gellfgq
mtsardhaykiak-c-iggtganhmksdhn--ircsagleywmveetv-e
rnsrnrfspthgnre-----------sahsakkqavyafqg------aia
aqdadeplvlg--------shhddiasknslshvflllhrhvvlsiaf-c
gllayirae-dv----vldrspdfk-ptkeekkrracdapmvf-alyapq
ptgqggepn-----levepefltihfarpepclqlmltqpivkpknirqs
ikadkkadlidfaktcalsmlntdyfqarlnaldpqgckysyl----knk
t-p-hpc-------------slvvn----qsnphaefqfplekcrkaekl
iktcchtslqnkfcakkvkdragnsgaeq-denrg--tvsaqlncyyey-
-----wyv---qavklllhfyahkpsnvg--ltlipkvtegeecgkfska
llagnr
>D
-------------yqaqplcdaiytllqwkevalr-pgckkvadsp----
-------nnatgkf----adlktayvk--prishddnklsklqwapkaiy
g-vkeaplkkscsgasqlvqgfadehc-dvaltt---------sgilaga
llparnhaykvti-y-ncavqpthlhedpk--ikctagva-wvleevvrs
rdpkwsfpptpankgvadtgdssspgtchsdks-----vgnllasddtla
rtdmhepldlghykhiskgnlymavsshailshvfailerhvifakqf-c
gvlysrstq-hi----vadrsngfn-pakdkkkrhqcvaamnfadlydte
ptgeggdgg-----sdvnpdflaihfgrrdrclqtmvdqpaanv-kirqv
ikcgqvpeladfprvavlsmlstevflvhlngqdpnsckytkd----rqk
t-a-rac-------------ktvvd----qcdvhhdfqfpfekckmqepm
igtvcstsltgrkc-kpiadeagntadke-ddssghpadagaiscyfee-
-----wyv---aalklrlhfflakptapsrvltlipeaaeeqgctkfsks
llaqnk
>H
-------------yv-dqkskeifsgtawsgkqlcsaggtvvfgqtegpc
cdtqktlakekqef----scfgvstrg--rwnvhnepelnslkftnllty
aigrqnplsmtacdqkktrggpegqsflalslra-smskmherpnmlkva
aalft--eykqpelt-akgtniqrpeytfp--fkvvphea-wfrandg-h
evnniklsseeahnegygag-trtpsgiqakde-----ndggfgedilyq
kvkltqrlald--------rtfavvrasankshkhdpmdkqvtshmkavi
tsvsfrppn-hm----tgdlsdpti-anrspttkdakkavgsc-nllsvp
nagsvna-t-----ielepstltalfsksvkatd-hv-----------ra
vrsapasadrkfvmdhdf--lstnisfgticcqpadsdkfkks----thr
h-wlrac-------------ppvlkemilapfldvdfdfdldlekidhka
al-ccdestgdnyc-gsdraali-kagdp-mintapkltgfaheccftac
qgefslnaattggpdlrpnmdvhnadqpk--fidlkscrhdkmvgrfeka
llgsvr
>A
-------------ya-dptcdgvfsftprhgaelt-pdqkgev-------
-------aqasrkftrqqmlvtvvygtsvhwgthknklqenlgfypttig
kmgkqeplhkeyshtkhefqvivakhckdlrlny-klcksfangfmlygl
feaqh--thaipv-c-latnipahlqstyt--fkcqahna-wflidck-n
ghprpakltkavnrdnklvgdgkprqgphgrvs-----ktgpftaaaaea
levkgkpsclh--------asysmvhalqsvchvyehink---lvtyf-c
dclgvspvd-pl----iihvgeeir-pesytnkkqpsaqsncn-dlygap
stadgyg-skaavilhgknqfldaayahpda-fhktveeqgskk-qimvt
irsfvkedlldfaadsvfamlgpdffvnkqggragkgesytngalllkqp
q-p-rsclnkdn------hnapgfs----psninntfr-gvridrkqnnf
ik-ccdlslrakyc-rklkarlldggdie-esksphakagsslycyfdy-
-----alc---fiialrvvnvrhkpkmps--lgvivnnvttdvcg---lg
lhgasn
>F
-------------fl-hlradqiytdtpwhgsylc-ggddfgfere----
-------sgd--ei----asyaiavap--nwdkhaalqlpgygfvamvkl
kiqkaapl--vnaedhkskmvftfrslkqlelvaaqmhrrfetgvltger
lgili--nynspl-l-vtgskvqregsyft--fkasaled-wigddsg-q
vaadhslsyqeghasgeahk-gkapsgnhgkek-----isgpsadqhpfh
qvkfipklgle--------rafslahgpktrkcqhdtlnrqyipakpalt
ccvnlrsndhqe----iaeltvefs-tdrtathmekadpgglc-klfag-
yngqgtd-s-----l-------taiygkgeaaie-lvghpgand-qilps
lkaspgssslefcenlvy--qgpkstvptlscqldeepelksg----tak
s-k-kac-------------spvltsaevqeathktleypltlplkehem
ci-scdfakkpayy-rdaqhasvakakda-msqlgrsigsgtyecclvy-
-----lypshkansqsthayyehfmpsar--fvkltqcsqdrmlgkfeqa
tlgdsr
>node7
-------------yq-dplcdevytmapwhgaelc-pgqksgfdrp----
-------nganenf----qnlkvayvt--pwsthkdkklskltwvplaty
qltkesplkrsyseakqiiqgfisnhckelrlsy-klckgfnngnllygl
mgaar--aykapm-c-sagtnpthlhstys--fkcsahta-wfmedsg-n
ihpkhaldsaagnkedkqdgegktrggshgrks-----vngpyagenpia
revmgqplnln--------ahypvvhaqasvshifavlnrhvvlapny-c
gclavrptd-hv----ivnlsedfk-perdtkkkeqceaaerf-dlygap
atgagsd-n-----ldvnpeflnalfahpdptlqkivdqpgvka-qvmql
ikagvaeelldfaddtifamlgpdffvatlngqaangskytkt----nek
s-p-rac-------------spvln----qsevhlefqfplkiskkqnkf
ik-ccdttlrakyc-rrlrdqaldsgdde-dnqsghpitggtincyynf-
-----wyv---vavklrlhfyahkpsnpa--lviiqkveqeeacgkyskg
llggsr
>B
-------------yg-dpqcnglfrvaprhgahls-pkvkseyert----
-------dpatskfskqylnigvvygksgnwkthqdnmlqkleyypltia
qmngqepahreyanaknelpvfvgkhckslrlsl-klsklfqagnmmygl
fgadh--gekipm-y-sgyksr--vhttyh--fkcgahge-wfpencn-d
vvakpafntkagnkdnklrgdgrsrqgshgrtc-----etnpyagaatea
kevggahstlh--------pslpivhplatvshiyaeitrhivlvpnf-c
hraaarpla-hv----vvmlsetir-pprdtrakenfantecn-alygpp
vtgdnsm-s-----lnahpsllaeayahpqaafgkktgaqghkk-vqmrl
ikafdmedllgysddsafamlgpecmmkahngvagkgnkfkigsllikdp
a-e-qsclnadkalskys-fsasls----pgethltfrlglrisrkankf
ik-ccsmavrdktc-rklkaalfdrgnidaetksghgregsslycyfdy-
-----ala---lavilrlifhrhkpkmst--fvdiikvqeedacgkyqla
lfggsa
>node13
-------------yl-dqrtkeiftgtpwhgkelc-agdkfgfgrtvtec
cnkqkslsagaedf----acfgvstat--rwdihpapeisnfkfgnllty
eigkatplsksvcdekksrggptghsflelnlra-tmnkrhdrsnmlnvs
aglfs--eyktpsls-akgttlhrqdstfp--fkaiehea-wfmadtg-n
svnkmslsseethdegygeg-grapsgthakda-----ndgsyaddklyq
kvkmtprlgld--------rsfsvvrasankthhhdplnkhvvshmklmi
tsvslkppd-nv----qpdltdpta-anrspttkerknavgsc-ellavp
naggtne-s-----velepnyltalfsksvkaie-rvahpgvkv-klgrl
trdgpasgdlqfvenhdf--lstkisigtlccqppdnehykks----thr
r-plrac-------------tpvlkgmvmqpdthidfefdldlekidhkv
cv-ccdnstseqyi-atnraati-ragds-miqttqkltgfaheccfayc
elhytlnaastdgadlrpdfdvhnaqqpk--fiklrsirhdkmvgrfqks
llgtvr
>node14
-------------yl-eqrtneiytgtpwhgkqlc-agekygfdrt----
-------sngpddf----tsfavamat--rwdihpakqlskfsfvalvty
kiakstplaksvsddkktrqgftshnfmelrlga-tmhkrfnsgnlinvt
mgvfr--dyktpk-v-vagtklhrqnstft--fkavahda-wfmddtg-n
lvpkksldsqeghddgegdg-gkapggnhgkds-----vngpyadenafq
qvnmtpklgld--------rsfsvvhaaptnkhndgplnkhvvselkflt
scivlrppd-hv----lpdltdefs-tnrapthkerkdavgsc-dlfakp
aagagsd-s-----velepdfltalynkaepmie-lvdhpgvka-qvmql
vkggpangnlefpknley--lgpkvaigtlscqppdgphykkt----shk
r-p-rac-------------spvltgmgmqseihldfdfpldlaktehqv
ca-ccesvlsaqyy-rksrdativkanea-mkqltqaltggtyeccfvy-
-----lyatqkagadlrhefyahktpegk--fvklkrvhhdkmvgkyqkt
llggar
>node3
-------------ya-dplcdgvfkmaprhgadlc-pgqksgidrt----
-------apasskftrqqmnikvvygtsvnwkthkdkmlekldfypltia
qmskeeplhreysnakhelqvfigkhckdlrlsy-klckgfaagnmlygl
fgaah--ahkvpm-c-sgtkdpahlqstys--fkcsahta-wfiedck-d
vhpkpalntkagnkenklrgdgktrqgshgris-----etgpyagaasea
kevkgapstlh--------psypvvhalasvshiyaqinrhvvlapnf-c
dclavrpld-hv----ivrlseeir-perdtnkkqpyaqtecn-dlygap
ttgdgsk-s-----lhaspeflnaayahpdatfnkkvdepghkk-qimql
ikafvkedlldfaddtvfamlgpdffvtthngragkgnkykkggllikep
q-p-rsclnkdkalvkythkspsls----ptdthltfrlglrisrkqnnf
ik-ccdmtlrakyc-rklrarlldggdie-esksgharegsslycyfdy-
-----alv---lavklrlvfyrhkpkmps--lvdivkvdeedacgkyakg
llggsk
