>node7
iaghhvgtpgkggepgflgpyv-----------ltykamvka----hrds
gfghllflkihniralgsppslgapkfpvikyarftfgeaktklqaaskl
epfrnqkrfggqv-eptgtg-kciselaphsseaeekpkdcsshyg-rat
pmfmtslvvhsapkfclkfhvesninrsnvkhenelltiqfvpcpyhgvk
sk---sslnpglvggiga-------aifngl----pvftggaayttsk-g
kgclvsqaveiceknhlqaggtrseceqkkkahgvinqir---lalkgig
ptkdrlmslpgahvyetdat--ffvtfyad-gsptldvrmdravglsygf
sevnnaaadavkkatlpripsilgq-----cnvcnclk-t-gka--pclq
lallaaecgkaskcvivspygrtgkaevqamdhlvragptkldaslpnyg
vvevtyssghkyqfipykyvrveqgaylvqevkkfdtkqakgktamnihw
vklfewqtkknfpan---dlpt--kghasslpfcspcgathkrhtgcq--
mvkkpgksetarrl--nlqarvmvsl
>node15
vaghhvglankngakgylgpyv-----------ltykamtta----hrda
af-hllf----gfralgsrpalglrkfqvikesrftfgetktklqgssll
epfrnhkrfggha-epvasg-scirelaphsseaeekpkecashyn-rss
pmfmavpvvhslpkfcltfnvesninredirhdktfltihfvgcpyagvk
sk---psinaglvggiga-------kifngl----pvftdmasfstsk-g
kgclvadpa-------llaggvlkecehkkklhkvidqgr---lalrgig
ptraqllylpggqvwyndat--fsvqfydd-ggpthdigvddainltysf
sdvknaasdg-----hthipidlgq-----cnhcnclk-p-tka--pcmk
lvlnvaeckkasrclvvnaylrttkaqiqamdhllraaatkldpagpdyg
vhdviytsahaflfipykyv--dhvgylvekvlhfdtrqgmgkvamnihw
vdlfewqtkkefpqe---dlpt--kghgsslpfcspcgtthkqhvgga--
mvkkpgradtakri--elqervmvsl
>D
aagqnlvekgrggepgfcgtytapqrygl--nvdtfgaapms----hmdg
gvgmflflsarngrese------gprfsivayapfsfgqnkekahncck-
fpfiahgkfaaqv-lptpsa-acqttvkphssdaakkakdcdspys-dvq
prfkgnliahanskfclrfkvesriarllqrkkhenaviqikpcpyemvk
skgkgvsvncglaggygssvsptllgifagl----pifkgnleyttlksd
ksclvgslvevcerklvgagglksdlnqetnvdglinesr---eavkgia
saksrlpvlpagk--dqnatysffvnsyse-geptmevridlvgglhygl
hevndapgdagkgphlprrpialgg-----cfvcgyld-aegkg--pqlm
lg-lgsacggaprcvemslygwsqkddiqdae------ptkldgsmgaya
ismtryrtghklqfgtykyfrndqgeylvqddkfydakkakgggalgtqw
vkllsldakk--------alpt--kshavglqfcgpcgnkrlrrtdcq--
msnvadkcemsrhl--qlpdkvqlpi
>B
faaheidvpskagqagflesyv-----------fagadtpnk----hphs
gfahllfakildprslkdppalpapkfpf-ryrrfglgedkgdlqagfll
dpihsqaaf--------avaayaisdlkahraegeekpkdssshhkvrgl
phyltplvtrragkfclrahvft--nphnghhqgnmldvifvfctfpgas
cd---kahnpglvaaigv-------smfdgl----pdiypgaaytvya-g
tgctlkeavngcekirltacskrtecetkkkvhgainqir---lslpppg
ptehklakldsv----------ffisangd-agg-----vdkilglteal
advdneksdpvsrvtlakdlpveql-----ckvcdclr-s-dtadplclp
iglvieeygqdtscvkggpfgdvgqtevpsmemlvdkgvkknnkalehfs
lrkstysaahdyqflgymqlrvghgtylpeelkkadsredkhagapnivl
fkvlewqtqwgfppn---ssps--kahttsvffstpcgftalrqmgis--
kikkpgklqgdrklpvnvpnfvtvsv
>E
vlghqls-dkwintkgypgail-----------ltcaekatyepnlsqel
sf-anlf----glkglggkehlglkslqpahaakfsya-phv--pstqls
epffehsqygadvpepvats-kavkdlprqpvstagpktechsryn-ryg
amfipscvltfiqhshllfnpddkvqsssakkeagflwqdligcgftgvk
ns---ptvddgmitgtgv-------kiylga----asflntlsfva----
-----pera-------elagkl---vptkakyhkgephak---lt-esig
rqsaenfyihhnhhwnqpns--fhv--ydd-vvptvdrsvndkvdlgyel
np-ksgdnes-----hltkgvggrh-----cavcic---r-tkt--pcmq
lsgn-teikeisrdavnkayfkitttefkglnvtfsashlkltsagtgfi
vnaavqafthavcflpyryv--ddlglpvgrvlkfaskpslnkvspherr
vgkyewpqkgipklqglahltncnmssrstvpncpfftaptkqhivppdp
glnkpgksectnik--altakvlinl
>node3
faghqigvpgksgepgflatyv-----------lsgkdkvna----hrds
gfahllflkihdprslkappalgapkfpiikyrrftmaeakgdlqaafll
epfhrqtrfgght-epsatg-yciselaphsaeseekpkdcgshhgargi
phflasvvvrragkfclkahift--nhdngkhqdnmlaiqfvpckyhgak
sk---kshnpglvggigv-------tmfdgl----pdfnpgaaytasa-g
tgctvsqavngcekihltacskrtecdakkkihgvinqir---lslptvg
ptkdklaklnsvhvyspeaa--ffitften-ggpalsvrvdrtvglsdgl
advdnakadavskatlakelsvigl-----ckvcnclq-s-gkadplclq
lglviaecgqdtncvkvspygdtgqtevpamehlvesgvtknnnplehfg
lkevtysaghkyqflpymylrmehgaylvqelkkfdtkeakpkgapnivw
vklfewqtdknypps---elps--tghasslafstpcgpshrrqmgcq--
kvkkpgkmqadrrl--nlqsfvtvsl
>node6
laghhvatpgrggepgfvgpytvperygilvnvatygaapka----hreg
gvglylflkiqnnrese------apkfpvvkyapfsfgeskdkahaack-
ypfrsqkkfggqv-lptssg-kcetavgphsgdaaekpkdcsspyg-kvq
pmfkgallahanpkfclrfkvearinrlnqrkqhenaviqlipcpydgvk
sk---tsldcglaggygs-------aifngl----pvytggleyttsk-g
kgcmvgsvvevcerehvaaggshtegdqdaktdglinqir---laikgia
stksrlmvlpaar--etdat--ffvnyyae-gaptldvridlagglsygf
sevddaaadavkgahlpriptvlgg-----clvcaclk-t-gkg--pplm
lsllaaqcgnasrcvivspygrapkddvqatd------ptkldaalpnyg
vtqvkyssghkyqfatykyfrndqgdylvqdvksynarrakgsnamaihw
vklfelntkknppan---elpt--kshaaglqfcdpcgnkhmrhtgcq--
mghvaaksemarrl--qlpdrvqlpl
>A
iaghmigvpaksgermfpvkyv-----------isgkdkvga----hres
gfp----lmvhhvnmikapprlgapkfplikyrplafieqkadlqaayll
dpfhrqtsfsgkt-epsatg-ycvsltaplkahddekqkhcaphsgargi
phflaptvarrgkkfclkvhpyg--endngkhqdnmlaihrkpckysgsk
sk---kghdpgpvgglgi-------tlfdgl----edfntaatytvga-d
tgctvseevhakenvnlmkcskklecaprkkihgtlkkir---lsvptlt
pgkeepaklplvhaycesha----ipiaqd-gspalwvsvdrsvglsngv
gntdtakv----ktiiaagvssigl-----csvcncle-s-grgepscnq
-------vgqntkllktspfadtaeqqlpsldnptssglkksndaveqig
lkqvtyssapkykfvplkylrvkkgaylvrdhnkfdskqagpqgapsivw
kklfqwnsnknypps---plpn--tghatdlvfptavgprdrgrmgcq--
rvkkpgnmeadrkg--nvdsfltvwl
>node10
vlghqlaidkrldtkgypvail-----------lnfkekatyeqnlsked
af-hilf----afkglgskqrlglrklqsakdekfsyg-shv--ptsels
epfidhtrfgaqapqpvass-stvkdlprqstsaegprtechsryn-rys
amflpvcvvhfiprthlafknekkvcrsgakkeagflrldlagcgytgvk
ss---ptvdegliagtgv-------kiylgt----aafantqsfva----
-----pent-------dlygsilkecptklkahkglpaar---lp-egig
hqsaevfyihgnhhweqpha--fhv--ydd-ivpthdrgvddavdlayel
ns-knaddeg-----hteigidgrh-----cavcic---r-ska--pcmq
ltad-aeikdasrnlvdkayfrvtttdfkglnpvlraselkltaagtgyt
vnaavhalahalcflpyrfv--ddlglpvgrvlrfdtkpsmnnvsaaerr
vdqyewpnkgiyrlqglahlsncnmgngstlqfcplfvqpykehvvpp--
lvdkpgraectdki--plaakvlial
>G
vmgnkvg-dkrnattgysagff-----------laekalfafghd--rea
ad-hwly----gfhalgskqaeglqklhivtverfsyt-klv--nptdlv
qaitsh--liper-dalgsr-stlrdllpsfedadeapedchshlt-ryt
pvfegvrvlhslssaglrfflekkcnrehhkidglfmriedlasvtdksn
ga---skvregtvadvgs-------hvytaehmehapiapevhfdatk-t
k----ldag-------ftqggvckdsalklqvdielplpkleflplrgrk
dagneafylagaqhwgqpaa--lnv-fydgriartyaeipn-----nygf
sggkagqsga-----anqvgldakpeenavceqcicla-p-kms--mcvk
tlnn-adckdatsclvcapyfrttviqhqglkkvlmtvdnkmpangpeyf
sacpiqtyahtflflnynft--ehlktlgqmlltfhwnpnmggmgvrver
vvefssgvkgtfrdggrahldn--lghgvslqscsptgaafrqavkgs--
liv-psqveathdl--ask-----ql
>node14
vmghhvglanrngakgypvpfv-----------ltykamatyehnlhrda
af-hllf----gfkalgskqalglrkfqavkeerfsyg-sht--ettnlv
epftnhkrfgaha-dpvass-stvrdlpphndsaeespsechshyn-rys
pmflavpvvhslpkghlafslekkvsrednkrdatflriqgagcayagvk
ss---ptinagliggvgv-------kiyngd----aafsdtasfdtnk-t
k----ldpa-------llsggvlkecasklklhkglprar---lplkgig
hassevfylpgghhweqpqa--fnvlfydg-ivpthdkgvddaidltynf
sngknaapeg-----hthiaidpkh-----cahcicik-p-ska--pcmk
lvan-aeckdasrclvvnsyfrttkaqfqgldhvlratelkltaagpeyt
vncaihtfahaflflpykfv--dhlgllvervlhfdttpgmgkvsvaehr
vdlyewptkgvfpedglahlqt--lghgtslqfcspygtaykqhveap--
lvkkpgraesakki--plaervlvsl
>node13
vmghnvg-ndrnaakgysaaff-----------laktalatfghe--rda
af-hwlf----gfhalgskqaiglrklhavkgerfsyt-klv--qttnlv
dpltsh--fgada-dsvgsk-stvrdlapcydsaeeapdechshyt-rys
pvfdgvpvlhslpsahlrfnlekkcsrehhkvdatfmrildlgcataksk
ga---psveaglvedvgg-------qiytadqmdhaafsptaafdank-t
k----ldaa-------flqggvvkesalklhlhkglplpg---lplrgik
dagnevfylaggqhwgqpea--fnvhfydg-ivkthqeapndyveitynf
sngkegqsas-----hshididpkpeedaacdhcicig-p-kka--mcvk
mlan-aqckdaasclicapyfrttatqfqglkrvlmavqkklaaagpeyi
vscaiqtfahsflylsynft--ehlgilaqrvlifdstpgmggmnvrvqr
vvlfgwstkgtfpdegrahlet--lgqgmslqfcspygaaykqhvsap--
lvk-pgpvdsaqkl--alnekvivsl
>F
vlghqlavdrrwdtkgypvpil-----------ldykkkassneqfsked
sf-hvif----alkglgqklrvglrklqlaknekytkg-tnv--alagls
dpfie---seaaaspgvetp-revkrlprpstateaprtechthyn-hyg
alffpasvihyeprgklefkggkkvcrsgakkeagflqlelagcaftavk
sn---ptvdaglltgaav-------siylgs----etfgckmgfva----
-----pent-------dlygrylkecpvklkahkslpeaa---lp-egin
hegiqvfyihgnhhwqqrhg--fhe--ydd-iipthnrgvhdavneayql
de-ltaedeg-----haaigldgr-------avcvc---a-aka--pcih
laad-taikdarrdlvtkgyfehtttdfkglnpalrasdlkmtaavtgy-
-----kplgsalcflpyrfa--dqlglpigrvlkfdtkaatenvsaadrr
vgqydwsnngifrleglahlyqcemgngsslqfcplyvtpykeesvpn--
lvdtpgkancsdki--plapglvvel
>C
vaghhllrpgqagesafvgsytvsqkygiltgvasygdapka----qreg
gvglyrylliqdnagsa------agrfpsvtylpfafgenkdkihaacr-
ypfrppkryggav-lptasg-kcetavgphsgealdepkdcagaft-saq
plfqgallawanrayclrfkidlrinslkkfkqvdssvieavpcpfngvk
gk---hsldcgpsggyts-------aifagl-----vytgglqyttgk-a
rgcklgapiqvceragvtgggyhadgkqeaktdklvfqir---ltvtqii
ktqsrvfhlpaal--avqst--ffvanyai-gapsvavkldlgaam---l
asvdedssdaipgghlprgptvlgg-----cgvcaclk-s-ggg--qplm
lsllatqcgnaarcavvfpyghdpsdnveatd------pakldqvlpn--
vslvkytagpknqfsnykyphgdqgeylvqdqkaydarrasgqtamaihw
iklfsldtkktappn---elpe--kshaaglqfcdpcgnkklshtgce--
mghistksdvvtrl--qlftrvetel
>H
vvghnvg-tdrnpttgyspdff-----------lkkgaltafghe--kec
gf-hwlf----ggenlsskeamglsklhatngerysft-rla--qaskli
epttsh--fgadg-ddlggk-sdtrplepcydstaeapaechidyt-knf
lvfhglrslhnlpsahlrinlekvcskehhkvdtcflrildlgcakakss
na---tsveaglveevkg-------eiytadtvehaafsptapfdgnk-t
k----liga-------fyqggvikenalklhfhkgfpmpg---lplkglm
kggndvffldpgnhwgepeg--fivdlydk-rakthqlmpasyvtvdynl
ttgregenas-----hghikiqpkpeeqsacahhicignp-ksa--mcvk
mlap-aeckdapsclvctpylrttttq------vlmgiqkkigsanpdyi
vscaqqsfaqsflyffneft--ghigilsdmtlifesapgmngleprvqr
gilfewstagtlpkegrphlek--lgegmslqfcspygaayklhvsag--
lim-pspmdsgqkl--alkqkl----
