>D
gagqhegcmvdkhcgyklgasdgkmlkq-------qqgmvrlqqkedvka
cvfpvvlgtlmaaghgc---------ssskpflgeadlkvklpmqaksql
vtlfkcfsqw-----npmkkrcplcgvidahdq-rahsskpp-cvg-ekp
plcgdifrqayvteyl----nktapqrtglkpiasswgspstpydrvqgc
ytgvkciitvlgkkilikqggpgnestfke--------gftagsps---n
nndscnlqwntprvpmtsggttphpkgrcppckpnkgglpsaacclctvr
rkwitsclqpa----natnysrllkngg---cqltgpgtvgesdvfalah
rkelhkgeltk----tli---la---iimy-----e----dgdegvalra
-qehakkkhylha----ldftyqkysdqglkd-esev--kda-tgp----
---srydkpyk--g-----------------qvnitgeasdcictkykyq
aylsfatvvk-acwavqgfnapphytaqlarftkdapllnhy-yfcdgyg
akghlygadktnleavddfkkatdrcigeaqlgerkmgtkiadhac
>A
gvvahtlctqmcpcqknvpt-------l-------pkgi----q------
chfpacvavvrpnsqnl---------rmkrsfhletnldgaladkrkvvv
vanyigfgrw-----nplntlcgl-avgsqhva-pthssrpphayn-stp
glcaailrieyvneea----dklsp--igfrsiklswgdrkaayddikys
gskiase----akkgl--sggmshesnvhgkllnlmlllsafenni---g
sdqccdlqwkepwaagvvksqpilpdvrnepcvp-eanlpiincchalhk
lgwveacsset----spihftryltaes---cpmgksgnagdmsafnv-y
rkerhrvmvem----dme---ft---vqef-----qvtkrageqgavlrt
evlhdkkhcfkdt----taftyskesddpdsc-dqfp--chtekgd----
---rvythtyk--neade--------sctftstskpetqsccvcfkyann
tyssfppgaa-iawdkqgyrntsplealgrsdarespnghkyhfkckgyg
drprlyggasspegsagnfktptsrchvpdtigqedfidr-vnegc
>H
ggvemsicelgnhcgagggnahalinhvifvktiakrhkldltrrsefta
cafkiylsndmparvhhahkydysdcsskkrvytvpanslklsretsltm
sevffcfggwdqaveeslaifctl-gavdpnkg-likasrqlgpng-kga
alsaptfrmvvmgdpc----gknkt--fsmkasratwginesvyedesgy
cckvgge----akpgl--pfgkpdacvlkg---dqapglnvelatlgpps
pgnckrtswgdgwagclacghqrtnngrsc----deageayshkykvaqr
vdrddqcakpartdfmnteyvffllnnleyqaslaettlaiylcllar-n
qptvhksvyimgiklsls---le---daks-----k----iadsgvknvv
-vfesktrapgst----lrvgyhryagfaltq-gghy----glpvfvqts
ggetaa---kggdlpmpq--------lcakttvagad-aptcqvfg-tfh
rymafslian-ghwryhgskknssvvarlkrfakgdekdkncqleqggsg
gkvknygvidshgpvagqfmneaqrcagcgilgndqlsta-ingnt
>node7
savehsgcmvgihcgdslgtaggvmkke-------pkgmvrlrrkeevkg
cvfpaylpelmqasahy---------kkrkrfhsetglavtlptkgklri
vatfkcfgrw-----nplnkmcpl-gvveqhen-pthtarpahcsg-dap
alcaeifrvayvnedl----dkplp--vgfrpirltwgsdkatyehvgnc
tvsltcq----gkkgl--eggksdgatlrd---nlmlaaesigntv---g
snecadlqwnqpwvdsitaghpnapkgrcppcnptkgglpnvhccramqr
adwvescgtht----tpieysrlltagt---crlggpdaagemsvfna-h
rkerhkivyam----dla---le---vqmy-----q----dgdegatlnt
-hlhsktrpvrea----lqftyrkysdeslta-dsvl--cntkkgd----
---geynkpyk--gpgne--------sctndmtsktddvntcpcfnytyh
mymafpsvve-igwkaqgyknsspltarlakfakdspnvakydyecegyg
akarlyggatsngptsdqfiaatdrchgkgglgqqrlaek-tdegc
>node6
savqhtgcmvdihcgyslgatdgvmkke-------pqgmvrlqqkeeikg
cifpaylpdlmaaqhgc---------skrkrflsetglkvtlatdgksrv
vstfkcfgrw-----nplnkncplcgviethdn-pahaakppncvg-eip
slcgdifrvnyveeel----grptpnktgfrpirpswgsdnttydhvedc
ytgltcq----gkkvlvkeggpgngstlqe---hlmlpavsagspi---g
gndcanlqwnspwvdmvsggpanapkgrcpacnpnkgglpnapccratqr
rdwvvsvlqna----nsidysrlltags---crlngpgnvgekdvfsl-h
rkelhkveytm----tla---le---vimy-----e----dgdegatlka
-hlhaktrqvrha----lqftyrkysdqaldd-dsav--knt-kgp----
---srydkpyk--g-----------------kvsrtgevstcacfkynyh
pymsfatvvk-scwkiqgykdpprytaqlarftkdspnvahy-yycegyg
akshvyggansnaeaadpykkstsrcngkgqlgeqrmatk-tdesc
>B
neaehelcslacpcqkslpttegvsrke-------pkgm----i------
chf---vpvvrpngdnl---------gkrrsyrevtnlggklpdkgrlas
iatfkdfgrw-----talkklcpl-gvveqfnh-qthasrpqhcyq-pas
glcaqifrgpyvsedi----dhvsp--igfrsikatwgdkkktnddvlyc
trssssa----gkrvl--aggkskgaasrn---hlmllvwsadnkl---g
sdecsdlqeeekwtaaivkgnpvdpdsrgppndt-kgnlpnvsccrslqf
ldwvencsaqt----tpeafarylpggs---tkgggpkaacemsqfda-y
rkevhkvligm----dlp---ln---vhtl-----a----dgakkgilnt
nhlhnkarcvkas----lrfgetkdadettrcndplg--cqakkgd----
---svynhpfk--ergre--------sgtfamtykrnsesrcvclnysyd
vyksfanaaa-lgwnvqgfksvtpldallvkfqgqslgrppyhfdcegyg
skarlygaasppeypkqvyvaptarchvrgslghqafadk-veedc
>G
gtieigacgvgdhccdgvgashaisrdv-------krgkkqltrqtaira
cafdtyltssiparlph---------ssrkraysisgstlklpkegrlvl
tgkfksfgswdqnpeeelakfcal-etvqqkka-aikgskklisaa-dga
tmnetdfrlalfddsa----gpaqa--fgflaapvtwavpnsiyddgagy
cnklage----gskgl--qagspegctvkg---dvmggrevnvavl---n
tsdcdrkawqddwvgritcghqytsngrth----klgte-------vvtr
vsrnpskaahr----maseyvffllqsmgercklkdpdtgieivffnp-n
gdtihv--------llstgmile---eskv-----k----lkdtlyklvg
-afecktrlsapt----ltvtyhrhagyvlna-ggqh----nepgdvhts
ggelaiqdpkgddlsghq--------lcvkqtvdgidripkckvfa-tfh
rymsfslsat-shwkyagykengqtvarlqkfskaddpdkhcqfekegdq
vklklyvtlpshgpvssnfestsercayqgtlsksqlate-insgt
>node15
gavehggcqvgshcgdsggagggvvsrn-------kkgkirlsrketvka
cafqtylaalmhanahy---------skrkrfnaesglavslpnvgklrl
vgafkcfgpw-----nplskmcpl-gvvdqnel-itqtarpahcsv-dgp
slcevfyrvayvakel----gkpls--fgfrptrltwgtnqttyehkgdy
cvsltch----gkkgl--qggksdgatlrd---dlmlgsestgptl---g
sndcaklqwnedwvnsitaghpnapkgrcrpcspalgaipkthaceimhr
pswvdpcgaht----mpaeysylltgnt---crlggpeaaneipvfns-h
rktqhkivyim----dla---le---vsky-----q----dgdngvtlsv
-hlhsktrgvrat----lnlgyrkysgeglpv-dscr--cgikkgn----
---aeyqkpka--npgnk--------gctkdltsttddvstchvfnytyh
mympfpamad-vswksqgykqscplvarlkkfpkgnpaldrydyecegyn
gkvkfyggavnngptgdqfigatercgskgglgeqrlaea-tdegc
>node3
savdhtlcslscpcqkslptsegvnrkq-------pkgm----r------
chfpayvpvvrpnsqnl---------rkrrsfhlvtnldgtlpdkgklvi
vatykgfgrw-----nplnkmcsl-gvveqhnh-pthssrpahcye-sap
glcaeifriayvnedl----dkvlp--igfrsiklswgdkketyddvlyc
tssltae----gkkgl--aggkshgassrd---nlmllvssienkv---g
sdqcsdlqwnepwaaaitkghpiapdsrgppcnp-kgnlpnvsccralqr
ldwvescsaqt----tpiqfprfltaes---cqgggpgaagemsdfda-y
rkerhkvmiem----nmp---ld---vqef-----q----dgdqgailnt
nhlhnktkcvres----lqftysknsddktsc-dqlp--cdtkkgd----
---svynhpyk--gpgke--------sctftmttkadsqsscvcfnysyd
tystfapaaa-igwnvqgymnatplepllckfakqspnspkyhydcegyg
ararlyggasspetskgafiapterchvrgsigqqefvek-vdegc
>node10
ggvqvgtcqvgghcgssgfashglvngt-------kkpgikasrkntlka
cafktyvtgqmpsaahh---------skrkrenaapaktvvlshveklvl
vaat----gwhqvepgslaglchl-gateqkkafitdgskrancsl-dtg
tlsdpffklvymadav----gg-lt--mgfsegkmtwelyqgpydndggy
ciklncd----kskgl--qggmkdssalrg---kqmltaeseltal---g
vtqcdrlqwgdqwvstitashpnspkgrcr----elgaqakshvclamhq
igwdspcadsf----mssdynfflrsit---crlpgpdagigipvynp-r
hktghctvyvmglklsfa---le---dsht-----r----vgessvmmvi
-pgntqakqvhpk----mglgymkyagiaseg-gshh----vskgd----
---vdyqkeka--trman--------gcakeevssanqvptcrvfn-ssh
kykpfalapdgvqwkaqsytqshplvakadpfargdpvskqcrfecagcg
pkvkfyggqdtngpvggafvdtgercptkdglgnqhiqaa-sdggc
>node13
gavevgacavgnhcsdgggaahalindv-------kkgkiqltrqtalra
cafdtyltadmparaph---------ssrkrsysesgnalklpregplvl
tgafkcfggwdqvqeealakfcal-gaveqkka-likaskklgssa-dga
tlsntsfrmvlmddpa----gknrt--fgfrasrttwgvndsvyedgggy
csklgge----gkkgl--qagkpdgctlkg---dqmggidvnlatl---a
stncqrttwgddwtgsitcghqntangrth----eagaeaashscnvtar
verddpcaaha----maseyvffllknmgyqcrlgdpnagielcifnp-n
qktvhatvyimglklsfs---le---eaks-----k----iadtgykmvv
-afesktrlagpt----lpvgyhryagfalaa-gghf----nmpgdvhts
ggetavqkpkggempmpq--------lcakqtvagtervptcqvfa-tfh
kymtfplaan-ahwkyhgykesgpvvarlkkfakgdepdkhcqferegng
gkvklygsieshgpvagqfmdtaqrcassgtlgdnhlatg-idsgt
>F
ggvqadscqvgsdcgstgflshgllsgt-------akhgikatrknalks
cafkayvagqkpsashq---------apqapefdppaknvvlshvek-vm
ltst----gwhtveaksggdfchl-gakeqadsfiadackkpncsi-ata
tlahepfklvymggkv----gg-lt--mgfaegkmtwelyqnpydpaggy
cikvsck----gskgl--qgsmkdsnalpg---ddvltaqkeltal---g
ialcnrlewgdhwvsavttrdsnppkghcw----elggqakgydclaleq
igfdskcadnf----etlkynfflrsit---srlpgpehgkgiavysp-r
hkgghsltyimslklefa---ha---gphk-----r----vgessvkivi
-pgadqakqvqakgksykgvgymkymsiaseg-dklh----vskga----
---viyakrka--twksnqllvdcdpicnketpsaakqvaacrlfn-ssh
kiepfalacggsrwradgytqthilvakadafarknpvskqavfqctgcg
prvhfcggdetngpvggfyvdtgarcpaknglgnpriqat-gdagc
>node14
gavevgacqvgshcgdsggaghglvngt-------kkgkirlsrkntlka
cafqtyltaqmpanahh---------skrkranaasgltvslphvgklvl
vgafkcfggwqqvenealaklcpl-gaveqkka-itetskkancsa-daa
tlsdsffrlvymanpv----gkplt--fgfresrltwnvnqsvyendgdy
cvklgcd----gkkgl--qagkknsctlrg---dlmlgseldvatl---a
stdcerlqwgddwvnsitvghpnapkgrcr----elgaqanthacqvmhr
itwddpcaahs----mssdydfflrgnk---crlggpeagieipvfnp-h
qktshstvyvmglklnfa---le---dskt-----r----aaengvmmvv
-alnskakqvqpt----lslgyrkyagialeg-dshh----vskgd----
---adyqkpka--dpmtn--------gcakdivsttdqvptcqvfn-syh
kympfplaad-vhwknqgykqseplvaklkkfakgdpavdhcrfecegyg
gkvkfyggkdtdgptggqfvdtgercatkgglgdqhlaaa-tdggc
>C
sstqhagamvdihcvyalgandemtkka-------pqgtvrlqqkedisg
vefptylpdlifsengc---------skrnrflsetglrgtlsthgrshv
ithfkcfsry-----ntlfksctlcapidthdg-pahaakpsecvg-efp
alcgdlfrveylddkt----grqtrgmegi-------psnettydqmens
ytgktce----gkkilgktggppkghtnqe---hnrlkavdtsgpv---a
gndccnlkwndawvnevtlgptnepkgvcpgcdtnvsgladaptckaksk
rqwivsmldna----gsidynrllvggs---cklntqlsvtendvfpl-h
gkeyrrvafvl----tvv---lelcfvviyanilyd----dkdagaalra
-hlhpgcrqvrhp----nqfiyrkysdqalsd-dgtshapes-kap----
---saytkpyk--g-----------------rvsrtgtvstcacykydyp
pfasfsdvvg-pcwpvqayeepprytarlprfakdepsvahy-yfcegvg
akkhkyggaannaeqdnpfkktknrcngkgqldeqrmatg-tnqsc
>E
gvvmsttcaigdncgstgyaehglvnga-------kdpgtkgsvkntlqs
csnktyvtgqmptaahy---------sktksqhatpsktvvlahienlvl
vvaa----gwheiqhgskggichl-gatqqkkgfttdsckkanvtlseta
tlhetfmklvympdavyhgdgs-lt--ggasqgtltwelfqaayaneggy
cakfysd----ktegl--qggkkassilrg---kqmltaesevtal---g
ltqcdraqwgdqwalhliasepgspigrcr----elgaeaksltclamls
lgwknpcsdpf----vnsdynfflsavt---crlpaqdsgvgvcvynp-r
hkng-ctvfvmrlalsfa---le---dknh-----k----vghsnnllii
-pgqtqaeqinpk----lglgykkfagvfsdg-gsnh----vvkpd----
---ckykkeka--tkign--------ecakeergssnhfsscrvfk-tsh
kykpfalapesvefkaqgynqahplaakcdaflrsegvtkqckfdcagcg
akvkfygghenngeggsaflntgercptnngltqphvqaa-ndggc
