>E
ailf-----------------------------------dlasdipmtet
vriddtesvkdgtvvsedfqdpwkggkkqalgtn-----gfgwadthe--
-ghsyvkdg-dstpasfsrvsaynvhsnvfdtkvlgpg--hlpgkehenr
alseietkprpyplvykvqr------yvsaylgasegvffyhlhsp----
vqykpfnhwdgti-phsclgvmlgasfdpqygyddsarsmepkvkginl-
--ltawidfeifkypcpgtl-iagtkphpvkaylddlphkrmkvcas---
-----l--hqkvincgkvqekdkrgssgacwknrqfggfcaalrtwpatt
--telekkiklwalsktakgql-glygt-ltqieilanclvtglm--g-y
nprld-----ptsp--kqly-----tknsqlpypagaskrghvtgn---l
avnttskrnqtkcslrv--rfekckctegavhagkvqhlafnthtehash
akvippp---ksiqc--rasr-----wldiastpidgaarppdepqkvgd
filtkdaidlgkaac-igfls----tdggfppvlaygalatyhgfglaae
me----d--sca-hgve----vrsgpqec-rn
>node15
anlfvvilh---------------------------ggaaaagh-----d
ikfdfkgslsgtilegkdfsapwrgsepgvlmse-----sygeeltndng
sah--gvdg-dlvdnvlsi-gsynvktsifqrvilssg--altdkgveil
algecetqdhaygvmhkgva------avsrnltesepnfyhq--sg----
aqykpfeqwdgqm-qnacqevnags---pqyaydlehkklnphvkqdnl-
--ladwiyfsl----ctsglklasstahpviscls--dsktlecfsv---
-----l--hqkgrg-vrahdrskpgtsaecsksraysefcqilaawthgt
--mdrskkmsaymmseyakgqq-dlsldfftalgvvgqclvtgvv--s-y
nirld-----paqs--gqcc-----nmksnlcya-knckdaantgt---l
grkagkltnvnkctahv--qfeksrftegeayagkvshghftttvelstp
ctsisms---kcvkpklnkkv-----wfkqytlivvsagkdttlgnktgd
y----dgialgrysg-lglvn----tvplfdiivenenlgplhhvssetg
lq----l--gep-ydvl----iggrlvqc-rq
>node7
nqlfvvifh---------------------------ggaedagl-----n
ikyafkgaasgnmlegddytgpwrggapgilise-----kygseltkdng
gpy--gvdd-dtvenkppf-gsytlntsitqrailahg--sltdydvdlf
algvsptqdhsygvmhqgaa------vvtrnliesepn---i--sn----
nqyrsyaswgtdm-qkacedisseg---pqyaydvqqkklaeavkqdsl-
--ladwiyysm----stsgvkqaaspadpviscla--dgrtlecfdv---
-----l--qqkarg-grahdrskpskgaatgksrhfnkfchmleawtegl
--lersrkmnaymmseyaegee-nltlqffgalkvmgqclepgvv--t-y
nvrmd-----pass---qcc-----amkkhrcya-knckdglntgt---p
grkagsltdvskctahv--qfakcriaegeayavkvthshptstvsvatp
vksdams---kcvksklnkki-----wfksynlivvsdgkdvtagdkagd
y----esvalsrysg-lglgn----tvplf--iaedqslgplhnsdsetg
iq----l--gap-yeql----vggspvas-rq
>G
dsltvvilh---------------------------ggatgsghggprde
lqlqytggqtgsmigsknydnprndagwta-lsr-----nfgldn-----
-ththgaea-drphdgini-sst----svyegtiflsf--altsshissl
plsgceannrpyplspkglpgtsdhravsekqkaeepagyyq--sv----
kkygafdhwlptm-laqcnkarlga---tqyssdqeks---skvtiatl-
--lstraffgfys-tsqggekvvpsaahkvlpclgdsaqnslgcfai---
-----l--qskvvacmraheksspgvstncpaskayggfckvlnsrcheg
--dhhgkrlavytvthsgkgnq-smtln---kdadaisclgsnas--scn
sprld-----para--glvp-----kekthlcnp-ascrkgqlvgtdlkl
aievgklravhkckahi--ey-rcr-tegavragkrepfvfkknadlaqv
civftas---ecvagakqtep-----wlcikrelqaagvksaadahdtgd
sakpkegpaksvysg-lnlas----ptlcfdgivskdsvaslqsvytail
fq----h--gea-ygll----mqgpvdmpghe
>D
l-------d---------------------------sadksvgl-----h
tk--fkvngggpmlqsanwtgnwkvgapgtvi-------kydpelqksng
gsf--------dvdakppf-gsytatrantlkqlvkfs--sgasylpvvf
alsvgqseahcytvmrhgvs------vvswypiesdaf---y--ln----
aqfntnfkwgrhv-nglckd-sssq---shygldvqllk--------elc
hkesnwiyyav----stavytqadseaacllscys--dgssldcfaltaq
lgpntl--qrkntg-grshdepkasaasasgkarnfnqlcaalevwteel
--larsrrmknsvsleyaegsa-dtaiqyfglvvviaqcldpglv--a-y
kfkrg-----pass---dcpfpatetlsaameha-kdckstlntga---p
ipkigwlveshkssghiig-lakcrialseayvtqrkethptasvgipag
ergdvis---kcceiwiqkdq-----wfknynvvlvndvlessvaekmgg
r----qcvihdrysgvldvrnsmrestalf--laddeplgplhgpdaqst
fsgerrm--gpp-yaqf----dggssga----
>B
ggh-diifq---------------------------gagnepgf-----r
akyafkgeaapnllhgesytgawggpangilvwd-----ksdceltkksg
gah--aakt-dtvhkntpl-qnfalstpleirgvlshkiqclagagieln
gldkcktqerthgvlnltat------vvskdsidaqpp---l--dk----
tngrnysewgydl-dkacgtissda---pkyayhipksseaeglkrisl-
--lrdwvysev----rakgvkhtisggekvvalls--ssakfdclga---
-----i--qsknmg-grdpgrnkpasgvnvgdghhlsslchtlegwkagv
--pnkcrkitaygmneyaggeq-kislqvtgalkvkaqclvarvvwnq-y
kkrlehdskphpsa---qcc-----amrkhmcya-kniacflnpgs---t
srkagplaavtkcashf--dftkckveqkqslvvrkalahktvtlgvaka
l-------------nkfnrkt-----wfrefstavnhdvdevsdasnial
y----ewieldkktg-rgltk----nvply--erenqkvgpedaeykatg
lq----lglagppyvhl--glis--pvfs-ht
>A
naq-vvifq---------------------------aaaedsgf-----s
vkvafkteaepyllheqdykgawrsaapgvqfsd-----kfdpelastdg
gph--ggdt-dtvrnknpf-gafdlnpriqvrtilkhg--ckseyseqls
pvdvsktqkqsygvmnlnat------visrdgiegqrs---a--dk----
kqnrcysewnhdl-qkacdsvsved---pqygydiqkdplrvgvvseav-
--lndwtfydv----ksigikrfitngeiaigels--egrtlecfgv---
-----l--ehgsml-gsvpgrskpakgnnkikphhag-fchilegwslgl
--anrghkigaypvtehlndsv-kamvhitgalkvmgqclvarig--s-f
karmd-----ptss---qcc-----astkhkcfa-rgpktglnsga---n
arkagpladvarcldqp--efhkcdiaddeslatrkthakptvnvgisrp
mhcdgmt---pcvdpkfsrra-----wfrnystsvvndvgeltdggniwq
f----ewsqlnrlsg-hnrgn----avplf--tsenqklgpqdaeyskts
ve----l--ggacylnl----vggvpvfg-rc
>C
vehfpvale---------------------------aadqsial-----n
ikydlkgnmagrmlapddwtdpwrggkpglvv-------nfvseltkdse
gsy--gid--qdvganppf-gsyagsranssrtllsfg--ggtnaghslf
algaghtqnhftgvmhkgas------vvtwylvetdpq---y--anscse
sqfetfakwgkgv-atackdissdq---phygfntkltq--------ta-
--qvgwlyfam----gkavvkeaageaeciiscfa--dgravdcfpl---
-----lqeqkkasg-grshdqtdppkgaatgksrqynqfcaavnkwtegl
palekprpmtsyvsseytekra-dtplhsfallkvieqclepgvv--t-i
kvkmt-----pags---pcpfaakdtmltnrtyt-kacknglntgt---p
gkktgw--eahkctghlva-laicrvalsdaysgrrknthada-vaapaa
ltgdgmqcffkcmkssigkkq-----wfdpynlvivnegkvvatadkqgg
v----lhmvlsrlsgilgmdp----svdlh--fsddeflgqltncsaatg
ipggrkl--agp-ysqteq--vagsnva----
>node6
lehfpvvfn---------------------------aadqdagl-----n
ikyefksnasgpmlqsddwtgpwrggapgivv-------kyaseltkdng
gsy--gidd-eevdakppf-gsytatrsltlrsllsfg--sgtdygpalf
algvghtedhfygvmhhgas------vvtwylvesdpn---y--ak----
nqfktfakwgtev-atackdissdq---pqygfnvqltk--------tl-
--dstwiyyav----gtavvkqaaseadcviscya--dgrtldcfal---
-----l--qrktsg-grshdqskpskgsatgksrnfnqfcaaletwtegl
--leksrrmksyvsseyaegpa-dtalhyfgllkviahclepgvi--t-y
kikmd-----pass---ecpfpakdtmsksraya-kdcknelntgt---p
grktgwlvdphkctghiva-lakcrialseayairrkhthaessvavpap
vkgdams---kcvkssihkkq-----wfksynlvivnegmevavadkagg
y----qsivlsryggilglgn----svalf--iaedeslgplhnsdsktg
ipggrrl--gap-ysqf----vggspva----
>node3
naq-avifq---------------------------ggaeetgl-----r
vkyafkgeaepnllhgedytgawrgaapgilise-----kydceltkdsg
gph--ggdt-etvhnkppf-gtfdlntsieiravlshg--cladyavdls
aldvsktqdhaygvmnlgat------visrdtidaqpn---l--dk----
nqtrsysewgydl-qkacdsisseg---pqyaydiqkkslaegvkqisl-
--lndwvysev----ktkgvkhaitpgdiviavls--egrtlqcfgv---
-----l--qqgnmg-grepgrskpakgaqtgkshhlgkfchtlegwtegl
--sdrgrkisaygmteyangeq-kitlqitgalkvmgqclvarvv--t-y
karmd-----pgsa---qcc-----amrkhrcya-kspksglnsga---t
srkagpladvskctshp--efakcriednqnlavrhththptvtlgvakp
vhcesmd---pcvkskfnrki-----wfreystsvvndvaevtdgdnigq
y----ewaalnrlsg-rglgn----tiplf--psedqklgpqdgeysktg
iq----l--agpcyvql----vggvpvfn-rs
>H
dtlrivvlhslsrtafkrvfsmqnkgknsrhgtygctggtagghgplled
iklqygggrggqlfgnkyvekppkqtqravllskqkgplsygepn-----
-tyahgrsa-qkahdvisi-ssftikaivyqygfllag--alterhvgsf
tlygcetqdrpypl-lkglpgtaehkkigkhqtapepafsyh--sa----
tdfntfahwlpalklescfeinlea---thygtkeaks---sdvtkktl-
--saqwttfsllavicksgsk-----ahaviqcladsektklgcyav---
-----i--qhkvigcdeaydalpphvanacpkgkdyggycrvlaswchdg
--hkhgdratfyaasntgkveqiagtln-ltdiadahsclatnvl--a-y
sprlg-----ttet--glca-----kkkddfcyp-aeckevqlvtr---l
kidrdklrhshqcdphv--qf-kckwpegqiragkkapfvfnsvgdlsqa
csvvtlt---qcakgrqksdeaqiaawlihkrllfmsetktyavskhtgd
idapkegpklsiycs-pdlvp----ntpcydailskenmgsvhvaftsve
ta----h--gha-yavl----qqavveqcgqg
>F
amlf-----------------------------------sagahsplkds
vgkdfseyikggavv-kpfeahwegeekdafcvh-----ghgidnsvs--
-shahatdgesktldqlsivisydvavtvfdvivldsg--hlfknniedt
glanvegqdrpyslmyntkr------amtaykkasdptffchmr------
------dswqdpt-lhpcvgvklst---rqygyddgkraldpkgkhtnl-
--laawiefaifkpkcaeglklkggtthpvkacagdsehkrdkcyhn---
-----l--hqkvincgktkdkekpstsdscwkmrqygiychvlaawnrtt
--tslakrvgswtmtktskgqq-glsfg-gvepgvvgsclitgva--k-r
nprvn-----iatteyvlly-----aahslmtfpcvtckseqvasd---l
vtncsktraqdkceanl--rfekcqcsqapiyav----lgfntisenaga
arlsvlg---rcvkc--rttr-----ll-iymtpvdggakkpagadkigd
ffyakdgvdlskess-igvlt----atggfpakvepnalgtyptaepaig
lq----h--sca-ngvg----vrgprkqc-na
>node13
dtlsvvilh---------------------------tgataeghgplkdd
iqlqytggrsgsmignknyenprkssergallsk-----gygndn-----
-ththgqda-drshdvisi-snfninasifetpilvsg--altarhisss
plsgcdsqdrpyplmhkglpstsdhkaiskkqtapepafyyh--sv----
tdynafdhwlpal-lescedvnlgt---tqygsdeeks---tsvtketl-
--lstwsyfglfaatcksgekvaptaahavipcladsdktklgcyav---
-----i--qqkvigceqahdalppgisnscpkskayggfcrvlaswchdg
--dhhgkrltiyavthtgkgeq-svtln-ltktanansclatnvl--a-y
sprld-----ptqt--glca-----kkkdnlcyp-aecrkaqlvgt---l
vidvgklrdvhkcdahv--qf-kcrftegeiragkrspfvfktdvdlgqa
ctvitms---qcvkgkqksea-----wlsikrlllaseaksaaisehtgd
yedpkegptlsvyss-ldlvp----ttpcfdaivskdnmgslhsvytaid
iq----h--gqa-ygil----vqgpveqcgrd
>node10
avlf-----------------------------------taaahgpmkds
irfdftesikggivvgknfeapwkgsekqalatn-----gfgddnthn--
-ththakdg-dstleilsivssyninanvfdtivlasg--hlpkkevent
alaevesqdrpyplmykakr------tvsaylsaseptffyhlhsp----
vqykpfdhwdgal-lhsclgvmlga---pqygydeghrsmdpkvkginl-
--ltawikfaifkppcpgglklaggtahpvktcladldhkrmkcyan---
-----l--hqkvigcgktqekekpgssnscwksrqygvfchvlaawsqtt
--tslakrigvwamtktgkgqq-glsgg-iaetgivgsclvtgva--g-y
nprln-----ptet--tlly-----skksqlsypaktcrkeqmtsd---l
ainasklrnqtkcsakv--rfekckctdgaiyagkvrhlhfntntehaga
arvvvsg---kcvkc--ratr-----wlkiyktaidgaakapatpekvgd
filtkdgidlskyss-igfvt----ttggfpaivekkalgtyhsavpaig
lq----h--sca-ngvd----vrgpeqec-ks
>node14
ttlfvvilh---------------------------dgataaghgplkdt
irfeftggisgtmvggknfeapwrssergalmsd-----gygdentqs--
-ththgqdg-dvahdvlsi-ssfnintsifqtvilasg--altdkdveil
alaecetqdrpyplmhrgla------avsknlsasepafyyh--sa----
aqykpfdhwdgal-lnacqdvlags---pqygydeehrgmdpkvkkenl-
--ltdwiyfslfassctsglklasttahpviscladvdnkrlqcyav---
-----l--hqkvigcvqahdrkkpgssnecskskayggfchvlaawshtt
--gshgkrmgvyamtetgkgqq-gltln-ftetgiagsclvtgvl--s-y
nprln-----ptet--glcc-----kkksnlcyp-kecrkaqmtgt---l
sinagklrnvskceahv--qfekcrytdgeiyagkvshfhfttnvelaaa
ctvivms---kcvkakvkkka-----wlkiyklilasaaknpaisnktgd
yelskdgialsryss-lglvs----ttpsfdaivekdalgslhhiytaig
lq----h--gqa-ygvl----vqgpaeqc-rq
