>node10
lilgtrrd-f---hp----------------------------lveqygf
kfftah------------------vp------------------------
-dd---ihpyi-------r---sgpsgvglspntilasgsklamqdnpyh
naqyiltvaakp-ynevffntqdcisgktfqs--ghcvfvqkly------
lag--------tgrvrhliqrl-rgleatkqamyllggv---glpqaaa-
-ga-----r-----a-rl-s-arnges-eftnflfqac-------hrice
ri-dkfsfykgyil-lgtkysvfgslghpemsly------llyhlddy--
-vvrgndaynapifvhaliffvdm-vitg-----skwlnaselp-hsfvq
dvtlv--gldv-g-pdthla-----ld---------------lsggihcq
v-pmvlqmippsel----l-------qa-wtksklghaglysn-------
-aftdgglvkd-talgkayss---ttqaev---fl-paqfapdnskrkvl
--y----------geha-----tspff--------ldki--n---laqks
ggyrhldqmgfdsrskd----la---q--lhetctsstgvg-ddkcknki
lifrcfsrpkeplavnhqvnqkavkakknag------dgsr------tln
nvfqllsasgfp--llselrl
>C
lclg--rd-f---ivnrtelsraesfkgtphmytrdrcikvggvrlarkf
ryfstn------------------tnpah-kqny-------------epn
wpe---vhsfn-------p---gdqhgvglspnlglvsgrrlplhdepff
aapfiltecakpeyaqvlfptstcisgna-nv--ghcvytdelkgeqdwh
l--l-------s-----lmenlirgqesrkhs-yllggq---gl--rsar
iaaecsldp-----a------vsfeqc-emsqfsfqscnnmpacvhkvsi
hl-dlfslyqayvlyggarfn-----------lyvnrdgqnifhlaeyrs
dvfkgkdvyrg-llaaalyyfaglasaag-----qewidtaevq-hkfgk
hltl----lnvggpqeahie---hhle---------------lqg-ikmh
v-psviamspqaglwqtel-------es-wfkahhgtegiygn-------
-dfydg----d-thlgnaysd----gqlki---aelpgelvqnhkknmvl
--m----------hlhka---avsvaf---f------kmamn--gveek-
--yrhlenmaynarska----la---l--mqqtctpgagvgkidkckrea
lif----------aakhltn---------rs------dadk------rfk
avfelmkgsgft--lltqlrl
>A
kcig--re-f---dlrrtvlmrtkafkatplmhnkdrcfkvggvrieykg
nyfrad------------------v-----------------------sk
whdiahvhpfa-------pgggagasgv------ilvggrpvslhnepyf
ptpyfttecpkp-ysqvffptggsvsgapfen--grcvlilkvk-fqa--
lqglvtekkvncgraahlitslcrggegnknkayllvgq---gl--kgak
iaaecpadp-----a-----karyeec-qmtnfnfqlcn----cihkasr
rlaeleclnkayvhysgarfs-----------hyvn----nvhqlddypn
-pisgkdvy-------------smaseag-----qkwmnasevqphkfsk
hltv----lnvggpqdthla-----lk---------------lhs-lsmh
--pivvtmspqegl----lpelviqnep-whdtrysvasiygd-------
-dfydgsfvrd-tnlgnaygdktttgq--i---ne-sgelaqdhpktkvl
--v----------hlhna---atsvafwtlfhgyqmmrt--n---ka-ks
alyrhlde-ayngr--affktiawlqd--mh-------------k--nnl
lif----------aanqlaqekgvp--gtag------dger------tlq
plfqlmkdgglp--lliklkl
>E
lilgtrrd-f---hp----------------------------lveqygf
kfftah------------------va------------------------
-dd---ihpyi-------r---sgpagvglapntillsgsklvmqdnpyh
nsqyvltvsakp-ynqvffnghdcisgktfqs--dhcvfvkkiy------
vpg--------sgrvrhliqvl-rgleatkesmyllggv---glpqags-
-gd-----r-----a-rl-s-arkgesieftnflfhav-------hrice
ri-dkfsfltgyil-lgtkhsvfdslgqadmsly------llyhlddf--
-vvrgndafnapilvedldffvdm-ivtg-----skwlkgceip-hsfvq
disl------v-g-peshla-----ld---------------lsggehcq
eapmvlqmipesel----l-------qa-ltkggaghaglyae-------
-altdgalvkd-tvlnkaysa---ttqaev---fl-paqfapenakrktl
--y----------geha-----tspff--------leki--ddl-lvqks
ggyrhldrkgldskskd----la---q--lhetctssdgvg-ddkcknkv
lifrcfsrpneplavefh---gavkakkdvg------dgskktagvitln
nvyhllsasgfp--llkhlrl
>node6
lclg--re-f---vvnrtelsraesfkgtphlhsrdrcfkvggvrlaykf
kyfsad------------------tnpah-khny-------------epn
whe---vhtfs-------p---gdpsgvglspnlvlvsgrklpvhdepyf
kapyiltecakpeytqvffptaacisgttfsv--ghcvyveelkgeqn--
legl-------s-----liqslirgeeshkhs-yllggq---gl--raak
iaaecsadp-----a------vsfeqc-emtkfsfqtcngmpacvhkvsi
rl-dlfslyqayvlyggarfn-----------lyvnrdgqnifhldeyrs
dvfkgkdvyrg-llasaliyfaglasaag-----qewidtsevq-hkfgr
hvtl----lnvggpqethia-----le---------------lqg-ikmh
v-psviamrpqeglwqtel-------ep-wykghhgtagiygn-------
-efydgafvrd-thlgnayed----gqlei---selpgelvqnhrkntvl
--i----------hlhsa---avsvaf---f------km--n--glaqk-
--yrhleemaynarska----ia---r--mhqtctpsagvgkidkcknna
lif----------aakhlvn---------rs------dgdk------tfk
avfelmkgsglt--lltqlrl
>F
lllgtrre-f---hp----------------------------lvekygf
kfftah------------------vp------------------------
-nd---ihpyi-------r---sgpsgvglvpn---asgsklvmqdnpyh
nsqyiltvmakp-ydesffnsqncisgktfpsrgghcvfvqkly------
lag--------agrvrhllhrv-rglqlanqamyllggi---slpqsas-
-ga-----rnflkqa-rl-s-arages-eytgflfqac-------hricq
ri-dkfnfykgyil-lghkyavfgslghpemsly------llyhlndy--
-vlrkndaynapifvhaliffvdm-vitg-----siwlnaselp-halvq
dvtlvggglnv-g-pdthla-----ld---------------ldggvhcq
g-pmvlklippsel----l-------qa-wtksklghaalysn-------
-vftsgamvmd-qalgkvyss---ttqaqv---fl-paqfvpdnskrkvl
--yvaiemfgfgsgdha-----tap--------------------laila
ggyrhldqmgsdsrhkd----la---q--lhdtcssttgvg-d-rcknki
lifrcftrpkepmpvahqvsekaikakknag------edsr------tla
nvfqllsatgfp--llsel-l
>node3
kcig--re-f---nvkrtalmrakafkatplmhakdrcfkvggvrieykf
nyfsad------------------v-----------------------sn
whdikhvhtfs-------p---agasgvgltpdfilvggrplalhdepyf
ptpyiltecpkp-ysqvffptagcvsgatfen--ghcvyiqkvkgfqa--
lqgl-------saraahliqslcrgeevnknemyllagq---gl--rgak
iaaecsadp-----a-----karyeec-qmtkfnfqlcn----cvhkvsi
rl-eltclnkayvlysgarfs-----------hyvn----nvhqlddyrn
nvikgkdvyrm-il------fvsmaseag-----qewmdasevqphkfsk
hvtv----lnvggpqdthla-----lk---------------lhg-lsmh
--piviamrpqegl----lpkl--enep-wynthygtagiygn-------
-dfydggfvrd-tnlgnaygdktktgq--i---se-sgelaqdhskskil
--i----------hlhna---atsvaf---fh--qmprt--n---kaqks
agyrhldeaaydar--a----ia---d--mh-------------k--nni
lif----------aanqlaqqkgvp--ekag------dgdr------tlk
plfqlmkggglp--lliklkl
>H
lclg--rd-lplpqp----------------------------itsqykf
mfflasstfekladnskftvprhlln---y--------------------
-da---vmpfakpytvr-r---svpsgvglapngilvsgkilavqdspph
glatvykeaakp-fsqvfskt-d-------na--ahccfvvkln-cks--
lsg--------tgrdthliqrl-ralqapkqvtfmlgghkakglpqega-
-gv-----k-----e-rl-f-drhvqc-efnkflfhtc-------rkvcv
hi-nlfgfykayil-sgkpfsl-g---haemvlyvtrtgslvyhldky--
-alsgqdaykgp---hslvffcdmavgtgigiqetkwlda--la-hsfah
nvtli--glhvgg-peaqlatcq--p-hfgpvakevvypscvhiggvdvh
v-am-iakipkdel----l-------qakwykshqghaelygn-------
-afydggfvrd-tslgseyss---tsqlev---fl-paqfgpqsskrkvl
--i----------tghpnngfatapff--------ldkl--r---vsrqs
ggkrhlgqagfdnrska----lg---q--lrqtctpatgig-inmiknnv
avy-----pkesqadnhllqqeavkrkekag------dgsw------kln
ntfhlmpaaafp--ltaeyrp
>node14
lclg--rd-f---hp----------------------------iteqykf
mfftan------------------vn------------------------
-de---ihpfa-------r---sgpsgvglspntilvsgkklavqdnpyh
gaayiltesakp-ysqvffntqecisgetfqs--ghcvfvqklnghks--
lag--------tgrarhliqrl-rgleapkqamyllggh---glpqagak
iga-----r-----a-rl-f-arhgqc-eftkflfqac-------hkvci
ri-dlfsfykayil-sgtkfsvfgslghpemplyvnrtgrliyhlddy--
-vlsgndaykgpilvhaliffvdmavitg-----skwldaselp-hsfah
nvtlv--gldvgg-pethla-----le---------------lsgginvh
v-pmviamippsel----l-------qa-wykshlghaglygn-------
-afydggfvrd-tslgkayss---tsqlev---fl-paqfapdqskrkvl
--i----------gehak---atspff--------ldkl--n---laqks
ggyrhldqmaydarskg----ia---q--lhqtctpstgvg-idkcknni
lifrcfkrpkeslaanhliqqeavkrkenag------dgsr------tln
nvfqlmrasgfp--llselrl
>node7
mclg--re-f---hvkrtalmraesfkgtplmhardrcfkvggvrqeykf
kyfsad------------------vnpav-khny-------------esn
whd---vhtfs-------p---agpsgvglspnlilvsgrklavhdepyf
gapyiltecakp-ysqvffptaacisgttfss--ghcvyvqklkghqs--
legl-------saraahliqslirgeeahknemyllggq---gl--rgak
iaaecsadp-----a------vrfeqc-qmtkfnfqtcn----cvhkvsi
rl-dlfslykayvlysgarfs-----------lyvnrtgrniyhlddyrn
nvikgkdvyrg-ilapaliffvgmataag-----qewldasevq-hkfgs
hvtl----lnvggpqethla-----le---------------lhg-ikmh
v-pmviamrpqegl----l-------ep-wykthhgtagiygn-------
-dfydggfvrd-tnlgnaygd---tgqlei---se-pgelaqnhsknkil
--i----------hlhaa---atsvaf---fh--rmpkl--n---laqks
ggyrhldemaydarska----ia---q--mhqtctpstgvg-idkcknni
lif----------aanhlaqqkgvp--ekag------dgdr------tlk
pvfqlmkgsglp--lltklrl
>node15
lclg--re-f---npnrtalt--ecfkgsplmhardryfkvgmikeeykf
mffsad------------------vnpav---------------------
whe---vhpfa-------r---pgpsgvglspnlilvsgkklavqdnpyf
gapyiltesakp-ysqvffptqecisgetfss--ghcvyvqklkghks--
legl-------kgrarhliqslirgleahkhamyllggh---gl--vgak
iga-----p-----a-tlmf-prhgqc-qytkfnfqtc-------hkvci
ri-dlfslykayil-sgakfsvfgslghpemplyinrtgraiyhlddy--
-vlkgkdaykgpilahaliffvgmavttg-----skwldasevq-hsfan
hvtl----lnigg-qethla-----le---------------lng-ikmh
v-pmviamippaal----l-------qa-wykshlgtaglygn-------
-afydggfvrd-tnlgnaysd---tgqlei---se-pgqfaqdqaknkvl
--i----------hqhat---atspff---fh--rmpkl--n---laqks
ggyrhldemaydarska----ia---q--lhqtctpstgvg-idkcknni
lifr---------aanhllqqegvprkekag------dgtr------tlk
nvfqlmkgsgfp--lltklrl
>node13
lclg--rd-l---qp----------------------------itsqykf
mffiasstleklednskftvprllln---y--------------------
-da---ihpfa-------r---svpsgvglapnsilvsgkklavqdnpkh
glayvlkeaakp-ysqvfsntedcisges-na--ahcvfvqkln-hks--
lsg--------tgrarhliqrl-rglqapkqsmfllggh---glpqagas
iga-----k-----a-rl-f-drhvqc-efnkflfhac-------hkvcv
hi-dlfgfykayil-sgtkfsvfgplghaemllyvnrtgsliyhldky--
-vlsghdaykgp---haliffvdmavatgisvedtkwlda--la-hsfah
nvtli--gldvgg-pevqla-----t----------------liggvnvh
v-amviamipkdel----l-------qa-wykshlghaelygn-------
-afydggfvrd-tslgsayss---tsqlev---fl-paqfgpdrskrkvl
--i----------aehanngfatspff--------ldkl--k---varks
ggyrhlgqmgfdnrskg----la---q--lrqtctpstgvg-idkcknni
aif-----pkenqadnhlieqeavkrkekag------dgsw------kln
ntfhlmraagfp--llselrl
>G
nclg--rd-l---qs----------------------------vasqckf
mffiassaldklednskfkmprvlln---y--------------------
-da---ihpws-------r---pvpsgvgvapnsvlvsgkklavqnnpkh
glayivkgaanp-csevfsntedcvsget-na--ahcvfvqkln-hka--
lsg--------tgrgrhliqkl-rglrapkqsmfllgg----glphaa--
--------------sdrl-f-drhvqc-tfhkflfhac-------hkicv
hi-dlygfykayia-sgtkfsvfgplghaemmvyanr-gsliyhldky--
-vlsgheackgp---haliffvdmavatgvsveetkwlda--la-hgfah
nvtli--gldvgg-pevqla-----t----------------liagvnvh
v-akviamitkdel----l-------qa-wckshlghaelygnlnlcfkd
dafydggfirdpaslgsaytk---tsqlevtvg---padfgpdrs---vl
--i----------aehsdngfatspff--------ldkl--r---varks
ggyrnlgqmgfdnrskg----la---qnglrqtctpstgvg-idkckkei
aif-----pkenqadnvlteqeavkrkesag------egsw------kln
ntfnlvraagfp--llsel--
>D
lclg--reaf---vvnrtdlsrsetfkgtphfhsrdrcfkvggvplaykf
ky------------------------pah-khnykegvrlarnllsfepn
whe---vhtfs-------p---gdssgvglspnlvlvsgkkppvhdepyf
kapyiltectspeytqvffqtaaciagtsfsy--ghcvyreelkgeqv--
legl-------s-----liqsltrangshkhs-yllggq---gm--rlak
iaaecsgdp-----a------vsfdqc-eptkftiqtcngmpacvmkvsi
rl-slfslyqafvlykgalfe-----------iyvaragenifhldkyrs
dvwkgkdvyrg-llasaviyfcglasaag-----hewidtsevq-htfgr
hial----lsvggpqetqia-----ld---------------lqv-ikmh
v-asviamrpqeglwqtpl-------ep-wykghhgtagrygn-------
--fyegafvrd-tffgnafee----gqlei---sdtpgelvhdhrkntvl
lki----------hlhda---avtvaf---f------km--k--ghaek-
--yrhlenkshdsrtka----ia---r--lhqtctpeavggiidkcktna
lif----------aakhlvn---------rs------sgdk------tfk
gvfermkgsgli--llthlrl
>B
kceg--ke-f---kvkktallrakafkatplmhakdrcfkvggvrieykf
d----d------------------v-----------------------sn
whdlshvhtfg------pp---agasgvgltrdfillagrpfamhdepyf
pntlfltdcpkp-ysqvyfpt--cgsgakfen--ghclyiqkvktfsa--
lr---------------miqsiirgeevnknemyllagq---gl--rgak
radecsadp-----a-----kpryqec-qntkfnfqlch----c-hvvgi
rl-eltclnrnyvlysgarfn-----------hyvn----nvhqmdeyrr
nvlkgdnvyrm-vl------fvsmdaeem-----aewmdasevqphkfas
hvtv----vnvggpqdthlp-----lk---------------lkg-ts--
--pmvigmrpqegl----lpr---indp-wynahygtagiygn-------
-dfynggfvrd-rhiskaygdktktgq--v---ae-agemaqnhskskll
--i----------hlhnr---atsvaf---fh--qmprt--n---kaqks
agyrlldeaaydar--a----ia---e--mn-------------k--sni
ivf----------aadqlaqqkgvp--qkagricehadgel------tlr
plfplmkdgglpatlli-lkl
