>C
---tkrgksfg---ek----alri-------yfqllkdlekgvlahqg--
fktta------qaldyvvadtascvhrseivpashscag-----khslkg
gahnkf----phkm-----f-------lgccd------fsnfkseqikle
tciy------pqhdyaan----alhggfvgllaaerdn------klkvcc
melycl--gayfekqcn-ytvsvkh------hfvc---tmgsiqycmhp-
gaagkghlkege--------gs--glnteyhnllcp-----ltlk-----
-----gfapskwmnkvatd-ql-tnw--irdqvvgkiprhlpdtyvlwew
irlhsgsvnkcgvfkyehadklqtrhgagkdvq-------kttgslk---
-lvpnpqyqqgkimefgcvgsstvsalmpgcneg---------atkseit
tadkd---dveqctttslswlv---v-nelmldpvggkrtldk---fpk-
t--------tt-t--esfgndt--------arpa-g--g--ntskmglkl
qknkdhqqa--s---------skkafy---kywsqslegicl---l-kkc
e----dsvdapqserlvtf------mgkflkkgqaqnladaera------
--tceckdspptedvsfasece--r-ralavqdyalspsgpntlv---gi
glvg--------------svterasltk-----------k-tsc--i---
---------eddfe--eak
>node7
---tmkpkgla---ek----ilrv-------yfhllqglekgilthlg--
fkiiavq---sq--------apscahrnetlstahdcas-----khslkg
gahnky----phkmgsgapf-------laycd------fanfkssqirli
aciy------phyayavs----alrggfvgilsndrnn-----fklkicc
mqlycl--saffeqecn-ytvsvkhg-----hliclhntvgsidyclhpf
gasnkglltgpe--------gv-----td--tllcp-----lklk-----
-----dftpqkwlgk--level-anw--hrdqvygritrlfpdayplwew
iklhsgqvkkcglfkyersdkpqtmrgag-daq-------k---------
-lmprpq------vdfgcvvsstvsarmpgyaeg---------attggit
tssmd---sveqctntskewlv---a-nqlmidpvggkrtlnk---fpkm
tti----drtt-t--eswakdt--------ahpa-g--g--ntskm---l
qkdknnqhs--h---------nseafy---kywsetlsgscl---l-kkc
q----esieephserl-kf------mgrflk-g----ladperv------
--tgeckdpvptmdvrfssece---iralavqeytlkpanpnvlip-qgi
--vg--------------svserakltk-----g-----k-tsc--i---
---------edkfe--etk
>node15
---tmkpkgma---ek----nlrl-------yfhllqglekvilthlg--
friiavq---sa--------apscahrneplstahdcas-----khslrg
gphdks----pakmgsgppf-------ldycd------fadfkssqikli
aaiy------phyayavs----alrggfvgilsndrad-----fklkicc
mqlych--saffeqecs-yqisvkhgvdkvhhlvclhntvgsidycllpf
ga--------pe--------gv-----td--tllcp-----lklk-----
-----dytpqkwlak--level-anw--qrdqvygrvtrlfpdsypvwew
iklhagqvkkaglf--eradkpqtmrgas-dqq-------k---------
-vmprpq------vdfgcvvsstvsakmpgyteg---------attgglt
taspd---sveqvtntskdwll---m-gqlmide----rtlek---fpkm
atl-----rstst--egwakdt--------ahpa-g--g--ntskm---l
qkekgnqhs--a---------nseefy---kywgqtlsgscf---l-kks
q----esceephskrl-kf------lgrflk-g----la---rv------
--tgirndptptmevrfssece---iralevqeytlktanpdglip-hgi
--vg--------------slkdraeltk-----g-----k-itc--ievn
walqn----edkfe--ett
>E
---tmk----alhgyk----nlrt-havkstffnllqvgqevvmthla--
frviavq---as--------agfcanfnqllvtardcvs-------p---
------iavhpanigsgpv-gvrlpiqleycevstrsyflafktevvlli
favp------phyayavg----alkg--vgifvgdkpd-----fmlktct
ialych--sdf---dcalyevsvkhg-dkvqqevclhhtvgsidyclnpl
av--------peg-------gv-----td--tllcpg--vdlkpk-----
-----hntpqkwl----levee-anw--qrddvygtvtrlfgvaytvwew
ikidsgqvkitnif-----gkpetarggs---e-------k---------
-v--------------gclvksvvsaklrgyadgi---rhpwtattsglk
h--pd---tieavakddkds-i---l-ghlmfgd----rpvek---fqkl
akl-----rqtsr--pgwakns--------aepa-g--awtansks---l
raekgsqeg--sgthk--hgidtqsfy---mywvr-lpgscf---l-kit
ewflaqgceiphtkrl-tf------vgrflk-g----ia---rv------
--agirndpthsmevkftpich---iaal--------vakpdgliv-hgi
--ag--------------tlkdradltk-----g-----r-itc--idvn
----n----phkferkehk
>F
---tmkptgmalr-akkdlfnlrtlhavkpiffhllqvgeevvmtala--
frvisvq---aa--------apccanvnqllvtarecas-----nhp---
----------panvgsgpp--------l-----------isfktdqivlv
savv------p-fkyavg----vlksgfvgifssskpd-----fkvkvca
iaaycn--adf---ecaiyevscrhg-dkvqhevclnntvgsidycllpl
pv--------peg-------gv-----td--tlvcpgvrvnhkpg-----
-----hnspqkwl----level-anw--qrddvygrvnrifa--------
----sghlrntnly-----nkrqvsrggs---d-------k---------
-v--------------gclvss----klrgygdsv---rhpwtattsglt
n--pd---tiesvanadkds-i---i-gqllidd----rpvek---fqll
atl-----rqttv--p----------------------------km---l
qaekgsqhg--pgthk--ndldsenfy---l----------f---lgknt
ewfpaqsceepstkka-af------lgrfkk-g----sq---rv------
--vgvrndpsltmevkytsicq---igkle-------canpdgliv-ngi
--vg--------------slkdraeltk-----g-----h-itc--i-vn
yshqn----phkfe--vdk
>node3
---kmkpknlp---ek----ilri-------yfhllqgleagiltnlg--
fkaiavq---aq--------apscahsnetlntahdcas-----nhslkg
gahnky----phkmgsgapf-------laycd------fanfkssqirli
acvy------ghyaiavs----alrggfvgtlsndmnn-----fklkicc
mqlyclgssaffeqecn-yavkvkhg-----hliclhntvpsvdyclhpf
gasnkglltgpd-kpddehvgv-----td--tllcp-----lklk-----
-----dytpqkwlgk--gdvvlkanw--hkdqvygrftslfqdayplwew
irg-sgqvkkcglfkyersdkpqtmrsag-aaq-------k---------
-lmprph------vdfgvvvkstvssrmpgnaeg---------asaggit
tttmd---sveqcpnthkewlv---a-nqlmidpvgdrrtlnt---fpkm
tti----erat-dnyeswakdt--------ahpa-s--g--ntskm---l
qkeknnpha--h---------pseify---kawsetlsgscl---l-kkh
q----esveepdserl-rf------mgrflq-g----taepdqv------
--kgqcmkqvptmdvrfssecd---iralavqeytlkaansnvlip-qgg
------------------svsdmakltksaakfg-----k-ttc--t---
-----kyptndkfq--etk
>node6
---tkrpksfa---ek----vlrv-------yfhllqglekgvlthlg--
fktta------q--------tpscahrseilaaahdcas-----khslkg
gahnky----phkmdsggpf-------lvycd------fsnfkssqirlv
tciy------phhayadn----alhggfvgilandrnn------klkvcc
mqlycl--gayfekqcn-ytvsvkhg-----hficlkntmgsieyclhpf
gaankgrlkape--------gt-----td--tllcp-----lklk-----
-----gftpqkwmgkvalevel-tnw--vrdqvvgkiqrhlpdsyvlwew
iklhsgqvnkcglfkyehadkpqtmrgagkdaq-------kttgslk---
-lvprpq------ldfgcvlsstvsalmpgyneg---------atpseit
taekd---dveqctttslswlv---v-nqlmldpvggkrtlnk---fpkm
t--------tt-t--eswakdt--------ahpa-g--g--ntskm---l
qknknhqhs--s---------skkafy---kywseslsgscl---l-kkc
e----dsveapqserl-kf------mgrflkkgqaqnladperv------
--tgeckdsvptmdvrfasece--r-ralavheytlsptnpnmlip-qgi
glvg--------------svserakltk-----g-----k-tsc--i---
---------edkfe--etk
>node10
---tmkptgmalrgak----nlrt-havkpiffhllqvgeevvlthla--
frviavq---aa--------apscanvnqllvtardcas-----nhp---
----------panigsgpp--------ldyce------fisfktdqvmli
iavv------phyayavg----alkggfvgifasdkpd-----fmlktca
ialych--sdf---ecalyevsvkhg-dkvqhevclnntvgsidycllpl
av--------peg-------gv-----td--tllcpg--vdlkpk-----
-----hntpqkwl----level-anw--qrddvygsvtrlfavaytvwew
ikvhsgqvkntnly-----dkpqtsrggs---e-------k---------
-v--------------gclvpstvpaklrgyadgv---rhpwtattsglt
n--pd---tieavantdkds-i---l-gqlmfdd----rpvek---fqkl
atl-----rqtst--pgwakns--------ahpa-g--a--anskm---l
qaekgsqhg--sgthk--ndldsesfy---mywvr-lagscf---l-kht
ewfpaqsceephtkrl-af------lgrflk-g----sa---rv------
--agvrndpthtmevkftsicq---iqale-------canpdgliv-hgi
--vg--------------tlkdraeltk-----g-----r-itc--idvn
wshqn----phkfe--ehk
>node13
---tmkptgmairgnk----nlrl-hkvspi-----qvldecvlthls--
frtlave---ga--------apscts------karncas-----ahnlhg
--qeks----panigtgpp--------ldycd------fadgksnqtklv
aavy------phyafavs----alrgafldivssdkad-----fmlktca
ialych----------alyevskdhgvdkvhhdcclndtvksigycllpl
gv--------pe--------gv-----rd--tllcpg--vqlkvk-----
----ahntlqkrl----leiel-akwprqrdqvagsitplfpdaytvrqw
ikldagqvkntglf--erkdkspqmrggs---eltidkhak---------
-v--------------gclvsstvpakmpgytngv---rgpw-aatsglt
n--ps---kieeventdkdwll---l-gqlmide----rklek---fpkl
atl-----rqtsa--pgwamnd--------ahpa-g--g--ttskm---q
qkekgsqhg--sgthk--ndldseafy---mywvr----scf---l-kkp
qwf--qsceepttknl-af------lgrflk-g----sa---rv------
--apiredptptmevkfssice---iqalevqeqtlktanpdgliv-hg-
---------------------draelsk-----gtlksfk-itc--idvh
wshqn----pdkia--eak
>B
---kmkpkglp---gk----klri-------yfhllqgldagiltnggng
fkaiavk---aq--------gpscahsdetqntahdcaqslhalnhslkg
gahnry----phkmgsgahf-------laycd------fakikssqirli
dcvyatkfdlehyaiavs----alsggtvgalsndvnn-----fklkicc
kqlyiagsaaffehecn-yavkvkhg-----hltclhttvrfvdycihpf
gvgnkgvltgtd-kpdeehv-------td--tllcp-----lklk-----
-----dyspmkwlvk--sdrvlksnw--hkdqvygrfttlf-dtypiwew
irg-ngnvkkcglfkyersdkpqtmrss----q-------k---------
-l----h------vdfavmvkstvssrqpgnaeg---------asavglt
tttmd---sveqcpgaskewla---a-tqlmvgpvgdrvtldt---fpkk
ttivmvcnrat-dnydswdknnkydqstphapp--------nsskv---l
kkiknnphs--h---------pseify---kawsetlssscl---l-kth
q----esviepdserl-sf------lgrflq-g----taecdqv------
--kgqcmkqvptmdvrfssece---ir--svqdytlkaansnvlip-qgg
------------------svsdmaklatsaakfs-----ktttc--t---
-----nyptngkfq--ev-
>G
---qmkgtg---rgnk----nirl-hkpspi-----hvvdscvlthls--
fttlaveskqga--------a---tt------nlrnyas-----aqnlhp
--qeks----panig--------------ycd------fadgksdqtrlv
aaiy------nhypfav------lrgaflelv-------------lktca
ialych----------tlydvskdhgvskvhhdcclndtvtsigycvlpl
gv--------pe--------gv-----rd--sllcpg--vqlkaktsvtq
vshq--------l----leiel-akwprqrdqvaksitplfpdaynarqw
vkldagqlqntghf--erkdksa-mrggs---------hak---------
-i--------------gclvsstvpakmpgytngm---rgaw-avtsglt
n--ps---kyeeaed-dkdsll---l-gqlmige----rklek---fpkl
ail-----rqtsa--pgwamnd--------ahpa-glvg--ttskm---q
qkekgtqha--sgthkpgisldpeasy---mywvr----ncfhcll-kkp
qwf--qsceepttsnl-afvsaitllgrflr-g----gt---rv------
--aparyeatpgmdvkfsaicd---iqalevqeqllkaanpdgltl-hg-
---------------------dqag--g-----gtlknfk-itclviqfh
wsqqd----pnktg--eak
>node14
---tmkptgmalrgnk----nlrl-hvvkpiffhllqvleevvlthlg--
friiavq---sa--------apscthrnellvtardcas-----nhslrg
gpheks----panigsgpp--------ldycd------fadfksnqvkli
aavy------phyayavs----alrggfvdilssdkad-----fmlktca
ialych--sdf---ecalyevsvkhgvdkvhhdvclndtvgsidycllpl
gv--------pe--------gv-----td--tllcpg--vqlklk-----
-----hntpqkwl----level-anw--qrdqvygsvtrlfpdaytvwew
iklhagqvkntglf--ervdkpqtmrggs---e-------k---------
-v--------------gclvsstvpakmpgytngv---rgpw-attsglt
n--pd---kieevantdkdwll---l-gqlmide----rtlek---fpkl
atl-----rqtst--pgwaknt--------ahpa-g--g--ntskm---l
qkekgsqhs--sgthk--ndldseafy---mywvr-lsgscf---l-krs
qwf--qsceephtkrl-af------lgrflk-g----sa---rv------
--agirndptptmevkftsice---iqalevqeytlktanpdgliv-hgi
--vg--------------slkdraeltk-----g-----k-itc--idvn
wshqn----pdkfe--esk
>D
---skrpksfa---ek----vlrv-------yfhl-qalengvlthlg--
fkvts------q--------tpgcahra-ilaavaecas-----khslrg
gsh-ky----cdk-dsggaf-------lvfcd------fsnyksiqirlv
tciy------hhhayadn----alhggfvgilandran------klkvcc
mqlycl--gaynekpan-ytvhvklg-----pfislkntmgsidfclhpf
gaankgrlkape--------gtgv---re--ttlcp-----lkmd-----
-----nftpqkwlgkvalevel-tnw--vrdqvvgkiqrhlpdsyiqwew
ik--sgqvhrcglfkyehsdkpqtmrgggkdrq-------ktagslk---
-lvprgh------ldfgyilsssvnalmpgyneg---------atcsein
taekdvdaevepctttslswlitrfvenqlmldlvggkrvlnk---fpkm
v--------tt-t--eawakdt--------ahpa-g--g--svskm---l
rksknhqhssps---------skkafy---kyws--lsgscl---l-kgc
e----ssvdapqserl-kf------lgrfl-------ladperv------
--ageckdslptmdvrfssnce--r-ralavhqytlsptnadmlin-qgv
rlvg--------------svsirakltk-----g-----k-ts-------
-------------------
>A
---kmk--ntp---ek----flri-------yfhmlqslpcgfl------
---ialq---aq--------apscvhsdetlntahdcar-----nhsldg
gahsky----phnmgsgrpf-------lafcd------fanlkctqirli
ncly------ghyaih--------rggfvgnlsndmnn-----fklkisc
mqlyclgssaffeqei---avkveng-----hgicvqntvpsvplclhpf
gapdkglltgpd-qpkdehvgv-----td--almct-----lklk-----
-----dytpgkwlgk--advvlkanw--hkdqvygrfaslfqdayplwew
vra-sgqvkkcglfkyersdkpqtmkaag-avv-------k------dan
rlmprph------adfgvvvmstsssrmpggaeg---------asaggit
sttmd---svqqcpnthkewlv---a-dqlmidpvgdsrelstegqgpks
tti----erat-dnyegwakdt--------ahpahs--g--tgskm---l
qkeknnphg--h---------preifygkkkawsetlgascl---l-kkh
q----dsveepdserl-rf------mgrflq-g----taepdhghvgasy
nlkgecmkqvptldvrfdsecd-----------------nsnvlep-qge
----slvktvmlggvgsmsvsdmaklkkaaakfg-----k-ttc--t---
-----kypsndkfq--qtk
>H
caltmkptgmairgdk----nlrl-hrvgai-----kvlsecvlthls--
frtl-------------------cts------kardcss-------nlhg
--qtks----pgnigtgpp--------ldycd------fadtkshqkklv
aavy------ehyafavsgscyplrgafldivssdkvneclklfmlktca
ialych----------alyavskdhgvdkvphdcclhdtvksigycllpl
av--------pe--------gv-----rg--tllcpg--gil--------
----sqntlqkrl----leiel-amwprqrskvggsitplfpdaytirqw
lkldagqdkydgly--ervdkspqmrggs---eltvdkfak---------
-v--------------gc--------------hgvnvlrgpw-attgglt
n--pi---kieeventdkdvla---t-gqlmi-------klek---fpkl
atl------dtsa--pgwalni--------ahpa-g--g--ttskm---e
qkakgrqng--ssthk--ndlesqaff---mywyr----tcf---l-ksp
qwf--qscvdpttknl-af------lgrflk-g----sa---rv------
--apiretptat--vkfnsicevg-iqalqvqegtlktatpdglivyhg-
---------------------drael-k-----gtlnsfk-itn--vdvh
wchqn----pdkia--eak
