>node14
kv-qtefklkgflhk-gav---khl-ernadahsynylpatel----sts
vviygt----rek-----gctcglvpkmglle------tmq-----kvad
------lpwcqffr-pegttg---aavaqeqs----pqlgk-ksagletr
gdqaiyknat----nnvsllvca-at-----------t------------
----papp-------yymfgspsaavrgllqaafadck---qhtk-w-fk
tlge------ag-dcvf----wdklhegllsghglttqkrgi--kgngh-
--------ktgaq----weng---taaernv--wlgsfmg-iedlpiepd
dq--krtv-a---srlg-----fspmlga--------rkdrkakppwyva
-ak----ah-tvla-eicssiipsasntpr-------ge--yln----l-
q---sh-ansan-arfgksd--yaatesireelkta---rcf----c--d
svh-----l-----lvnly------kcvg-------qa--slagkevgkk
lf---pgfsrk-gf--plsalssakqydd--k-ahslpavagcla-----
-----kspapckglypkivkactgvl----pep----qvlptagkrlppv
e----lliavkpgef---naktkytatnpmktcfyeln-i---ippekrm
lssrvlfqa-hst--v-tq-llspdtchdvkvisym---tr--k
>H
lv-qtefdltgflhn-gev---knh-prnstaeaykylpaaelmagtsts
aviygt----hdkinsvsdctcgl-pqlgllq------dgq-----kvtd
------qplcqffh-pegtdg---aa----es----iqlgk-ksasldtr
-dqaiyklqt----nnislavca-ae-----------t------------
----pspvvdtkk--yymfgsp---vrvllkasfaeckglilhsk-w-fk
trse------ggteclf----wdvlnhaqvaghtltthkmtt--kpnga-
--------ktaagfkaiwesg---aaaihnv--wltshmg-cedfpvepd
eq--krtv-s---srlg-----fspilg-aggrvrlrrkdrdakpgwyvh
-sk----vn-tvmv-elasevlvsdgnipk-------ge--yln----l-
rthsshiahsan-drfgkstk-caatekirdqlktg---rcf----c--e
vvh-----l-----lvnlf--------vg-------qi--slgskqtktn
lf---sgfsrkegf--pistlstareykdrfmnafslpavagclt-----
-----kspat-------iiqactavi----pepfllyqllpdagkrlppk
eldwtleiamkpgef---naktkytgtshmkscfyeit-v---ippdvrv
lknrvlfka-qnt--v-kql--spdichdvk----kkgadk--p
>G
lv-esefdvsgflhn-gel---rnl-eidaaaapfnylpavevmagasta
aviyvt----req-----dctcglvpklglle------tmq-----klad
------lplceffh-pegttg---ga----qd----vqlgk-ksagldtr
seqaifklvt----nnltltaca-sd-----------t------------
----pgppvdtkdgqylmfgsp---vrvlqqasfedckaliq-------k
-rse------sgtdcly----wdklnhgllsghtltthkmgt--kgggr-
--------ktaar----wesg---syakhnv--wlgsfmg-iaeinvspe
sq--kksvvad--arlg-----fssmmgaaggrsrirrkdrdakpgwyva
-gk----gk-tvla-dlcadvlpsagnipr-------gk--yln----l-
r---nyiahntg-arfgkgdk-caatesirdqlksa---kcf----c--e
apq-----l-----lvnl---------vg-------qa--glgekavkkt
ll---egftkkdgf--pisaltsakqykdrfk-qfslpevagclt-----
-----knpapcrglypkiikactgvi----pqh----qllptapkplpat
e----lrfavkpgef---nakakytttmhmkncfhqit-i---idpekr-
-knrvlfka-qst--v-kql--speihhdvk----k---dr--k
>node15
kf-qtefklkgflhq-gav---khl-drnaephsynylpavel----tts
vevygt----rek-----gctcslvpkmelld------amq-----kvdd
------lpwcqgfn-pegttg---apvaqeqdecsapqlgk-asagletr
rdqavyknea----nnvsllvcapvt-----------a------------
----paa------------gspshtvrgllsaafaack---qhts-w-fr
alge-vnpgvtg-nytf------------laghglsttkrsi--kgndh-
--------ktgaq----lasg---taaernv--wlgsfvg-iedlptepd
dl--krtv-a---sr--tgtcvfapmlga--------rrdrkakpewyta
-vk----ah-tvla-eicssiipsasntprgff----se--yls--dnl-
q---gh-ansanparfgksd--yaatvtireelksa---rcf----c--d
sih-----l-----lvaly------kcvg-------qt--svaggevgnk
mf---pgfprk-gf--plsalssvkqydd--k-ahglpavagcfa-----
-----ksvapckglnpkivkactgvl----pep----qvaptagkrlppv
e----lliavkpgef---haktkytatdpmktcfyevn-i---ippekrm
lssrvlfqs-hst--v-tq-lldpdtvhegraipym---tr--k
>node6
-f-gtefklkdflhq-gsvwgekdl-srnyephsyyvlpavel----kts
veaygt----rak-----lckctlvppmelld------atqlienskved
------lpwcngls-pettsg---aavaqqqaehftpqlgk-tsggfetq
rdlavyknkt----nnv---vcanvtgklpglgakgstqaepfkvval--
asqlpai------------ggpshslqglvsdafaack---phtt-w-fr
vladfanqagtg-sytl------------laqhglgttkrsitlkgnqn-
--------ttgae------------aaernv--wlgaf----edlskepd
hlip-rtl-d---tr--agtcvflpmvqe--------rrdkkakpewytt
-tk----ah-tlla-eiclsiipsagntpraff----se--yls--ddl-
q---ga-anp---qrlgnad-fyestviiinelsss---kcvwvikc--t
sihe---kl-----liasy------ncvg-------qt--svangtvgyk
mf---pgfprk-gfpd------------e--k-shglpnvagyfa-----
-----kglssckgltptivkgctgvqcryaqep----evapsnglrlppv
a----lprssepsef---nqktkytateqkqtcfyevg-i---ippekrt
lanrlllht-ygt--vstn-alnpdsvhdgrpiptm---iy--k
>E
rv-ttefklkq--rnhgss---khd-lrnanshkynylplsel----sss
iaiygtnattrek-----gcecglvpkmglnegpgdsasmq-----kvah
------lpwcqfsr-pagsakhlnavvfqeqn----pgvgk-stagldtr
gkagifkdaa----nnvsllici-at-----------s------------
----pgrp-------yyikgtpsnavrgliianfaeck---ahsk-w-fk
dlgg------ag-dcvfdhke-n----ntlsghalnaqkrgi--rgngr-
--------ktsae----w-ng---tssqrnv--wsssfkteieelaiesn
nq--krtv-a---srtg-----fspmlga--------lkdrktkpk----
--------h-tvle-npctsvfpqasnspk-------gd--yln----lg
q---ch-mnsen-gryg-----yasgeairedlkta---rcf----c--g
svh-----l-----lvkly-------cvs-------qt--slpdkevskk
if---pgltqk-gf--pagtltsakqyee--k-ahsltsvagcaa-----
-pchwkspapciglypkivkactgvl----pep----qvlatagkrihpv
-----klvavkpgef---ndrtqftgtnpmktcyyslnhi---ahpqkki
llsrv-fhkehtk--v-te--lsqdcchdvkiisym---tr--k
>node3
-f-qaefklkgfilq-hsvwgeqdl-nanaephsyfylpaael----kts
veaygt----rak-----lctctlipkmel--------paq-----kvnd
------lpwcngfn-psatt------vtqqhaehytpqqkk-agggfetr
gdq-vfkkea----nkv---vc-pvtgklpgwgakgst------------
----pav------------gsashilqgllseafadck---psttgw-yp
algdfvnpgstg-nyal------------laghglgttqrsi--ndyqh-
--------ttgae----lasg---taaernv--wlsif----edlstepe
hlip-rtv-d-lasr--tgncvflpmlsa--------lrdwkakhewytv
-vk----eh-tvfa-eic---ipaasntargff----s----ls--ddl-
q---sh-ans---prfgnad--yestviiindlssgkqmrcvwiikc--v
sih-----l-----llaly------dcvg-------qt--svgggavgnk
gf---pgfprk-gfsdslsklssvkqydd--q-ahgmpavagyfa-----
-----krlspckgltpsivkactgil----pep----qvtpts---lppv
e----lliaskstvf---nakakytgtepkqtcfyeln-i---ipperrs
lanrvlfqt-yat--estf-vldpdavhegr-iptm---ty--t
>F
kv-tvefklrq--kk-kyg---khl-lrkadthrynymplael----sts
viiyet----rkk-----gctcvlvpkmglne------smq-----nvad
------lpwcqffr-pegtanhlkgvvfqeqn----paigr-ktngl-ti
nkaavfkdsg----nnvsllvci-aa-----------t------------
----pgrp-------yyisgtpsnaargllqanfaack---qhtk-w-ak
dlgg------ag-dcvf----wnnlhenilsgkglkaqkrgi--rdngh-
--------kaggd----wdng---tasernl--wassfaseieavvigan
nq--rrtp-a---shtg-----fqpmlgp--------kkdrstkhk----
--------h-tvlveepcstifppainspk-------ge--fln----l-
p---th-angan-grfg-----ygaseaireelkta---rcl----c--a
gah-----lhaalglvkly------kcvg-------qs--slpgkevgkk
sf---pgltkk-gf--tlnsstsakqyde--k-ahvlptvvgcavalydl
lpcrwkspapckglydkivka---------pep----vvlptagkrshpv
q----kldavktg-------kteytgtnamktcynhlnhi---iheekrs
lldrv-fha-htk--v-tg-klsqemchdvkivaym---tp--k
>B
-f-qasfklkgfilq-hsvwgeqql-nassephsyyylpaaei----kts
veaygt----rak-----lctcklipkmel--------ppq-----kvnd
------apwcng---psahd------vtqqhaehytpnqkkf-----dvr
geq-vykkea---lnkv---lc-pvtgklpswgakgta------------
----pav------------gsvshilqgllaeafadck---pstssws-p
algdfvkpdsvg-nyal------------laghglgttqrsi--ndyqh-
--------tigae----lpsg---taaarni--wlsif----edlstepe
hlia-rtv-d-i-sr--tpncvflpmltg--------lrnwkskhdwysv
-vk----eh-safa-kic---ipaasntakgff----s----lsmddel-
q---sq-a-s---prfgna---yestvviinnlsssnqmrciwai-----
-ih-----l-----llslyeeafmsncvg-------qt--nvgggavgnk
gf---psfpr-----dslsalssvkqydd--s-ahgmpavaayfa-----
-----trlspckglkpsivnactgll----pep----qvtpts---lppv
e----lliaskstvf---nakakytgtdpkltcfyevn-i---ippekrs
lanrvlfqt-yat--esty-vldtdplhegr-iptm---ay--t
>node13
lv-qtefdlkgflhn-gev---knl-ernaaaqaynylpavelmagtsts
aviygt----rdk-----dctcglvpklglle------tmq-----kvad
------lplcqffh-pegttg---aa----qs----vqlgk-ksagldtr
ndqaiyklat----nnvslavca-ad-----------t------------
----psppvdtkkgqyymfgsp---vrvllqasfadckaliqhtk-w-fk
trse------sgtdclf----wdklnhgllsghtltthkmgt--kgngh-
--------ktaaq----wesg---saaehnv--wlgsfmg-iedfpvepd
eq--krtv-a---srlg-----fspmlgaaggrsrlrrkdrdakpgwyva
-ak----ah-tvla-elcsdvlpsagnipr-------ge--yln----l-
r---shiahsan-arfgksdk-caatesirdqlkta---rcf----c--e
avh-----l-----lvnly--------vg-------qa--slggkqvkkn
lf---pgfsrkdgf--pisalssakqykdrfk-pfslpavagclt-----
-----kspapckglypkiiqactgvi----pep----qllptagkrlppt
e----lkiamkpgef---naktkytatmhmktcfyeit-i---ippekrm
lknrvlfka-qst--v-kql--spdichdvk----k---nr--k
>D
-f-gtefnlsdflhq-gsvwaekdl-srkyepdtfyvlpavel----kts
vdeygt----rak-----lckcallppmesld------asqliegskved
------lprcnglaqpettsg---aaiaqhqaelftpklge-trgmfese
rdlavykkkt----nnv---vcanvtgklpglgskgstqaepfkvtgl--
sshlpgi------------ggpshnvealetdafaack---phtg-w---
--adfanqagag-sytl------------lpqhglgttkrsitlkgnenf
dingfpafdtga---------------ernvvmwlgaf----edlskk-d
h-ip-rvl-k---t----gacvflpmlqe--------rhdkkakpewhtt
-tq----ah-tlma-evclsiipssgnkprtfy----sdldyls--ddl-
q---qa-anp---qrlgdve-fyestaiviselsss---kcvwiikc--t
svhemqrkf-----liasy------dcvg-------ht--tvalgtvgyk
mf---pgfprr-gfpe------------e--k-shslrhvqgyfa-----
-----kglasckgltptmvkgctgvqcrya-ep----evqpsdglrlppv
a----lpltsepsef---nqkskytateqkqicfyevg-i---vppekrt
lenrlllha-ygt--vsne-alnpdseedgkaiptm---iyikk
>node10
kv-ttefklkq--rk-gaa---khl-lrnadshrynymplael----sss
viiygt----rek-----gctcglvpkmglne------smq-----kvad
------lpwcqffr-pegtanhlkavvfqeqn----pgigk-ktagletr
gkaaifkdaa----nnvsllvci-at-----------t------------
----pgrp-------yyisgtpsnavrgllqanfadck---qhsk-w-fk
dlgg------ag-dcvf----wntlhenilsghgltaqkrgi--rgngh-
--------ktgad----wdng---tasernv--wassfkgeieelaiesn
nq--krtv-a---srtg-----fspmlga--------rkdrktkps----
--------h-tvle-epcssifppasnspk-------ge--yln----l-
q---sh-ansan-grfg-----yasseaireelkta---rcf----c--g
svh-----l-----lvkly------kcvg-------qs--slpgkevgkk
if---pgltrk-gf--plssltsakqyde--k-ahslpavagcaa-----
-pcrwkspapckglypkivkactgvl----pep----qvlptagkrihpv
q----klvavkpgef---ndktqytgtnpmktcyyslnhi---ihpekrm
llsrv-fha-htk--v-te-klsqdtchdvkiisym---tr--k
>node7
-f-qtefklkgflhq-gavwgekdl-drnaephsyyylpaael----tts
veaygt----rak-----lctctlvpkmelld------atq-----kvdd
------lpwcngfn-peatsg---aavaqqqaehftpqlgk-asagfetr
rdqavyknea----nnv---vcapvtgklpgwgakgst------------
----pav------------gspshtvqgllsdafaack---phtt-w-fr
aladfvnpggtg-nytl------------laghglgttkrsi--kgndh-
--------ttgae----lasg---taaernv--wlgtf----edlstepd
hlip-rtl-d---sr--tgtcvflpmlsa--------rrdrkakpewytv
-vk----ah-tvla-eiclsiipsasntprgff----se--yls--dnl-
q---gh-ans---qrfgnad--yestviiindlssa---rcvwvikc--v
sih-----l-----lialy------dcvg-------qt--svaggavgnk
mf---pgfprk-gfpdplstlssvkqydd--k-ahglpavagyfa-----
-----kslspckgltpsivkactgvl----pep----qvaptngtrlppv
e----lliaskssvf---naktkytatepkqtcfyevn-i---ipperrt
lasrvlfqt-yst--vsth-vldpdtvhegrpiptm---ty--k
>C
-fggtgfklkdflhq-gsvwgqkdlcsrnyehhsyyvlpavel----kas
vevygt----rgk-----lckctlvpalslln------aallienskved
------lpscngls-petttg---vavapqqadhftpqlgk-asggfeta
rnl--fknkeyth-ddi---vcnnvtv----lgekgsaqaeefkvvalgk
ashlaai------------ggpthsleglvadafaack---phtt-w-fs
vlasfgqragsn-sytl------------laqhglgttkkavskkgnqn-
--------ttsae------------aaernv--wlgaf----edlskdpd
hlip-rml-e---tr--agtcvflpmvqe--------rrelkakpewytt
ktk----sq-tlla-elclsiiptaggtprafy----ne--yls--ddl-
q---ga-agp---qrlgnas-fyettviiineisss---kcvwvikcqvt
giha---nl-----liasy------ncigiletyllet--svangtsgyk
mf---pgfprk-gfpd------------e--k-sqslpnv-gyfa-----
-----pglsaakaetptiv-gcsggacryaeqp----evapsnalrlppt
a----mprssepsdl---nqktrfkqterkqtcfyeig-i---ipagkrt
lvdqlllha-ygtlvvatn-vldpdsvhdgrpiptl---ly--k
>A
-f-qteftlkgftlq-hsvnsqddl-nanaevhsffylpaael----kts
vq-cgk----rqk-----lctct-----------------q-----kvnd
nemlrnlpwingfn-psatt------vtqqhaehytpqekk-asggfesr
gdq-vfkkea----gkv---vc-pvtgplpgwgakgst------------
----pav------------gdsshvlqgllneayadcr---sattgw-yp
algdfvsp-------al------------laqhglgdtqrsa--enyqh-
--------tsgan----lasgptqtaaernl--wlsir----edlptdpe
hlip-rtv-d-lasr--tgdcvflpmlaa--------lsawkpkhewyti
-vkpkvdehhtvfa-eic---i--asntardffsylgn----lp--edl-
q---sh-ans---prfanad--yepttiiiddlssgkqmrcvwiikc--v
sih-----l-----llply------dcvg-------qtessvgggavnak
gfshsnnfprk-gfsdsltklssvkeydd--l-argmpavagyfa-----
-----krlssckgltpshvkactpil----pep----qvtrtg---ippg
a----lliaskstafkaqnakakytgtepkqtcfyelk-iplvvpperks
lanrvlfqt-yat--estf-vldpdavhesr-iptm---tq--s
