>E
ptlcyl----gt----wlllk--------yahsq-------aglknn--l
-----sagyarekqr--------------eqkkp---------mh-----
k--aslkfgtdllkfesailchkpqaqrtlirvcg-gsv-------rgda
tvdmry-kdetahlyptrrahvfnylislc---------agn---ilvlr
--gkrla---gsgsatsqkstyacvfknl--e-----sgn-iskshs---
l---l-c-yhteq--g--nvptgapfn---nelpyrckcsswkavseitr
tandltlack-si-laidsgkgglcrg--phclks--ccisa--------
----thvialakpgag---tdss-----tsydqlrlpvrfvqrg-pykin
adylkt-rrkttidkvqsp-------gye-tgrvl--dspiadnwspefe
i-gtpqdpmcs-egc--kcsfsrk------kgta-----h-yvn----l-
hnsgg--ni----kvp-k-iv--iitcdavqggk--kqvk----ag--s-
----ksgk--yra--pysdhp-------a-cet---ep-------gvawn
ssy----yeannvigmpswksaddfll---gki---vgcksvsnc-----
l-t---vsyfgfe--ehlflsvl--wagdlgakh-t-lal--egmkygrv
radgn------htwgiiniq
>A
rklefl----av----llllqqplwalteykhsqfg---tagvakastdl
-----dgdyakkrhr--------------gvyp----------ih-----
tg-agltflgsl-rlqkahkcykada---lvr--a-tfv-------rdrs
aisl-hpkgesgh----rntyvfyfl---y---------eah---vlvl-
-------------apgsqksayacvlknl--p----rfsg-mpream--i
hfgap-y-ygdgnsl-e---p----yq---rdlkyrckcaswk-------
nadkldvhskpti-aavnvgtgginrh--phcfka--csgga-------k
aairte-----kpvgh---anap-----vgfenlpvrvtyvqvge-----
---fktgrrktckkrvepqkdkg---gyd-agkpearhrpvreiwcpefe
i-gssqdpicy---c--na-fpratrvtt-kgtictlrgh-gqgigggfg
hdygmrvniallgkev-e-iv--vlgcdevhilv--klttrlqfhg--k-
dscm-----------pssatp-------g-sen---epggpqtsinmaw-
---------sn--egmpnwap----------kvdggescqclalc-----
ehg---aky--ceqvqhalpasv--tskdagskcst-lsilt--m---rv
rtdgs------anwgttkiq
>D
rklefl----gi----l--------alqeflnshfr---tpsvaraspnl
-----dgkfakgkhr--------------danrh---------ls-----
tg-agltfgnsl-rfktqhkcykaqg---lvr--tivlveddlalsrdka
piei-h-kdetah----rkshvyyfv---y---------esh---vlvlr
--gervt---tagragnqkt---catkkl--eskalrftg-vpkkapqgl
ffgpt-c-hhcgksdak---p----y--------fkckcttwtpasq---
aagklkvpsk-kia-aigqslggacgh--prcfks--csiga--gkq--k
--trtrgfarlkdgghpgiaagr-----qsyghlpiainyvqvgq-----
---lkt-r--ycvkkvgpdkekg---aydglahpprrqrpvrniwcsefg
i-gipnkpicy---c--ng---s-qrvvt-kgtlctprghkygg----l-
hnaglkvnl----kev-h-iv--vlsceaiqiia--klaw----ngeks-
easmia-rygfrsttpngasp-------ggcddglpqpghhhapltmaw-
---------st--sgmpsrtsvd---l---anirgkss--cvtnci----
-----------------alpialvetskeignkvitalslln--m---rv
ragwg------taw-tnkir
>node7
rklefl----gi----llllrqpvwalqeylhsqfa---tpsvaraspdl
-----ngdyakgkhr--------------ganph---------lh-----
tg-agltfgssl-kfqtahkcykaqg---lvr--g-tfv-------rdra
siei-h-keetgh----rrthvfyfl---y---------agh---vlvlr
--gqrlt---ssgsagnqkssyacvtknl--e----rftg-ipkeap--l
ffgat-c-yhsgkslae---p----yq---kelkyrckctswkpasq---
sagklkvqsk-si-laigsgtggacrh--prcfka--csaga--gkq--k
-atrthgiartkpggh---ansr-----tayehlpipvtyvqvgq-----
---lkt-rrkycmkkvepekdkg---gyd-agkphqrhrpvreiwcpefe
i-gtpqdpicy---c--nadftsaqrvvt-kgtictlrgh-yqg----l-
hnaglrvni----kev-q-iv--vlscdavqilv--klat----hg--s-
dscmks-rygfratnpsgatp-------g-cdd---epgnhqtsinmaw-
---------sn--tgmpnwtpsd---l---dkitgkescqcvtnc-----
ahs---aky--yeqvqhalaaal--takelgdkcit-lsllt--m---rv
raegg------tnwgttkiq
>F
ptlvyl----gv----llilr--------ylhsqyl---tsavak----t
-----nggyarekqk--------------eakhpdtvlvkklrlh-----
k--aslkfgsqlwnfdsaikchkpqa---liqvcg-gtv-------rgda
siqlrh--datad----rrrhvfnyl---c---------agn---vlvlr
--gkrla---gsdsatsqkntydcafknv--q----rngn-lskshp---
f---tpc-ihgekslaeynvpsespyn---tevayrckcsswkaaseier
taneltlask-vi-laiatgsggacrf------ks--cctsa--------
----shvitlykpsag---hd------------lrlsvrfvqrg------
-------rfkvsrvkvqpekdkr---gyd-agrvl--arpvgdtwcpefe
i-gfpqesvcs-dac--kcsfsskedivtvkgttctlkph-yvs----l-
hn-----si----kvps--aa--vltcdaihamk--lqik----sg--e-
----ksgkpgyre--py-ahp-------y-c------avlhsgdigvswr
nayelsgyqannvigmppwkaad--kl---dki---isckcngnc-----
l-t---taylgfq--thlflsvl--ssgdlgakc-t-lslasedmkygrv
sedan------htwgivniq
>node14
pkldyl----gv----llllr--------ylhsqya---tptvaras--l
-----nggyarekqr--------------ganhh---------lh-----
kg-asltfgssl-kfesvtkchkpqa---lirvcg-gfv-------rdpa
siei-h-kdatah----rrthviyyl---c---------agh---vlvlr
--gkrlt---gsgsatsqkssyacvsknl--e----rpgn-iskaap---
ffgat-c-yhsekslaefdvptgapyn---telayrckctswkaase---
sagklalqsk-si-laidsgsggacrg--phcfks--cctsa--gkq--r
-tkrthvialakpggg---hdsr-----tqydqlplpvrfvqvgq-----
---lkt-rrkvtmkkvqpekdkg---gye-tgrvl--aspvrdtwcpefd
i-gtpqdpicy-dac--kcnftskehvvt-kgtictlrsh-yvs----l-
hntgarvni----kev-h-iv--vltcdavqagk--klak----ag--s-
----ka-rfgyrakkpygarp-------g-ced---epglhqadigmsw-
---------andvagmpswkssdhfkl---dki---vsckcvanc-----
l-t---tsylgye--qhlflavl--sakelgakcit-lslas--mkygrv
radgn------htwgtisiq
>B
rklefl----gv----llllhqpvwslteylhsqfe---tpsvtraksdl
-----egdyekkkhk--------------eanph---------lh-----
ag-galtfvssl-rfqtghqtykaqg---lvr--d-tfi-------rdka
risi-h-kgeggh----rnnhviyfl---yqtriavgtktah---vlvl-
-------------spq--kgayacvvknl--e----hftg-ipreap--i
hfgat-c-yhngesl-e---p----yhttnkdlkyhckcaswkpasq---
nagklkvqdk-ti-lavktgtgglsrh--phcfaaapcaggaflgkq--r
-avrth-----ksegh---ansr-----vgfenlpvrvtflqvgg-----
---lkagrrkkcrkkvepqkdkg---nyd-agkpekrhrpvrqiwclqfe
i-gskqsp--y---c--ns-lpraqrvit-ratictlrgh-aeaigsgf-
kdaghnvni----kev-e-ivekvlgcdevqilv--klatwlkfhg--t-
dscm---------------tp-------g-ced---epgghqnsinmaw-
---------sd--sgmpnw--------------dgkqscqcltfc-----
gda---sky--peqvqhalaanv--tgkehgagcrt-lallt--l---rv
ptegs------agwgttkiq
>node13
pklpyv----tv----llllr--------ylpsqya---sptvasas--v
-----sggyarekqaykynchqggpfgktganhh---------lhadgiv
kg-asltlgssl-kfesvttchkpqa---lirlcg-gfv-------rdpa
siev-h-kdatan----rhtnviyyl---c---------agh---vlgls
--gkrlt---gsglatsqkssyncvsknl--d----rpgntirkaap---
ffgat-c-yhpenslaefdvptgapyn---tdlafrckstswkagne---
nag---lqhk-si-laiangsqsacrg--phcfka--cctsa--gkhdlr
-skkshvialaksggg---hesr-----tq-nqlptpvrfvqlgq-----
---ikt-rrrvsmkkvqpekdkg---gyq-tgrpl--aspvadtwnpefd
i-gthqdpicy-dac--kcnftsksrvvt-ratictlskh-yvs----m-
nntgarvni----kev-h-iv--vytcdavqagkskklak----ag--s-
----ka-rfgyrsrqpyaarprqt-sftl-crd---epg--qsdig--w-
---------addvsgmp-wksddhfkl---nki---vtckcvanc-----
l-v---tkylgye--qhlflevl--sgkdlgatcia-lsles--mkfgrv
radgd------htwgemsia
>node3
rklefl----gv----llllhqpvwalaeylhsqfs---tpsvaraspdl
-----dgdyakkkhr--------------gatph---------lh-----
tg-agltfvssl-rfqtahkcykaqg---lvr--g-tfv-------rdra
sisi-h-kgeggh----rnthvfyfl---y---------aah---vlvl-
-------------spgsqksayacvtknl--e----rftg-ipreap--i
hfgat-c-yhngnsl-e---p----yq---kdlkyrckcaswkpasq---
nagklkvqsk-ti-lavntgtggisrh--phcfka--csgga--gkq--k
-avrth-----kpggh---ansr-----vgfenlpvrvtfvqvge-----
---lktgrrktckkkvepqkdkg---gyd-agkpeqrhrpvreiwcpefe
i-gspqdpicy---c--na-fpraqrvit-kgtictlrgh-aqgigsgf-
hnaglrvni----kev-e-iv--vlgcdevqilv--klatwlqfhg--t-
dscm-----------psgatp-------g-ced---epgghqtsinmaw-
---------ss--tgmpnwapse---lglydkvdgkescqcltlc-----
ahs---aky--ceqvqhalaanv--tskeagakcst-lsllt--m---rv
rtegs------anwgttkiq
>node15
rkldfl----gv----llllrqpvwalqeylhsqya---tptvaraspdl
-----ngdyargkhr--------------ganph---------lh-----
tg-agltfgssl-kfqtvnkchkpqa---lvr--g-gfv-------rdra
siei-h-keetah----rrthvfyyl---c---------agh---vlvlr
--gqrlt---gsgsagtqkssyacvsknl--e----rptg-ipkaap--l
ffgat-c-yhsekslae---psgapyh---teltyrckctswkpasq---
sagklgvqsk-si-laidsgnggacrh--phcfka--cstga--gkq--k
-asrthgiamakpggs---adsr-----tqyehlpipvsfvqvgq-----
---lkt-rrkycmkkvepekdkg---gye-tgkpl--hrpvretwcpefe
i-gtpqdpicy---c--nseftsaqhvvt-kgtictlrgh-yqg----l-
hntglrvdi----kev-h-iv--vlscdavqila--klak----ng--s-
dscmka-rfgfratkpygayp-------g-ced---epgnhqanigmsw-
---------an--agmpswtpsd---l---dkitgkesckcvtnc-----
aht---tkylgye--qhsfaaal--sakelgdkcit-lslvt--mkygrv
raegn------ttwgtikiq
>C
rklefl-----flkqrllllrqpvwa----lhshfr---npsvaraspdl
-----ngklakgkcr--------------gsnah---------lh-----
tg-sgftfggsl-kfraqhrcyralg---lvr--gitlvp-----krdra
pidi-h-khetaq----grthvsyfv---y---------egh---vlvtr
kkgerlalnatsgregnqk------tkkl--e----sftn-vpkeapqgl
ffgpt-cvhhcgkssdg---p----ye---rslkfrcncttwtpatq---
rtgklkvask-ti-laigaslggacrh--prcfka--csiga--gkq--k
-aikthgfarlkgq--q--taariipraqeyg---itityvqvgd-----
---lka-rkrycvklvepskekgvgigyegaanphrrhrpvrntwcaehg
i-sipqhpicy---cvvngeytt-qrvit-kgtictakgn-yqg----q-
ntaglrvnl----kdv-q-iv--vlscdavqiia--klas----qa--sv
eacmia-ryvfratnpdgasp-------ggc-d---qpgehhtplnmaw-
---------sn--sgmpswtpvd---l---aklrgkeschcvsncidsdt
nhargwtky--y-------asel--t--elgnkcit-lslld--m---sv
radwg------aqq-ttkiq
>node6
rklefl----gi----llllrqpvwalqeflhshfr---tpsvaraspdl
-----ngkfakgkhr--------------gsnah---------lh-----
tg-agltfgnsl-kfktqhkcykaqg---lvr--gitlvs-----krdra
piei-h-kdetah----rrthvfyfv---y---------egh---vlvlr
--gerlt---tsgragnqks---cvtkkl--e----rftg-ipkeapqgl
ffgpt-c-hhcgkssae---p----yq---ralkfrcncttwtpasq---
sagklkvqsk-ti-laigsslggacrh--prcfka--csiga--gkq--k
-atrthgfarlkggghp--aasr-----qsyghlpitityvqvgq-----
---lkt-rkrycvkkvepdkdkg---gydgaanphrrhrpvrniwcaefg
i-gipqdpicy---c--ngeftt-qrvvt-kgtictprgh-yqg----l-
htaglrvnl----kev-q-iv--vlscdavqiiv--klas----hg--s-
eacmia-rygfratnpsgasp-------ggcdd---qpgnhhtplnmaw-
---------sn--sgmpswtpvd---l---akirgkeschcvtncidsdt
nhargwtky--yqqvhhalaaal--tskelgnkcit-lslln--m---rv
radwg------tqw-ttkiq
>G
pnlpyv----tv----llllr--------ylsslyatnlsptvarag--v
sgnglsggya---qaydynchqaapfgktganhs---------lnadgiv
kg-aslalgasl-kfeyvtvchkpta---lirlcg-gfv-------knpa
siev-h-kdatan----rhatvvyyl---c---------aghkssilgls
--gkrlt---esglavsqassyncvsknlkcd----rpgntirkia----
ffgat-c-yhpenslseydvptgapys---tdlsfrckcaswkagne---
ngg---lhhk-si-eaiangaqsacrg--phcfka--cctsa--gkhglr
-nkkshvialtksgag---hesr-----lq-tqlrppvrfvhlgq-----
---iks-rrrvsmkkvqpkkdkg---gya-sgrpl--aspstdtwapefd
i-gthqdpicykkac--kcnfakksrvit-raticslnkh-yvs----m-
nntgarvni----kel-h-va--vyscdavntgkskklak----ag--s-
----ka-kfgyrgrqsyadhprqtqsftl-crd---epa--qsdvt--w-
---------addvsgmp-wksdqhfkl---nki---vtckcvanc-----
m-v---skylgyp--qhlflgvl--sgrdlgatcda-lglek--kkfgrv
radgdfsqickqrwgemsia
>node10
ptlvyl----gv----llllr--------ylhsqym---tsavakas--l
-----nggyarekqr--------------eanhp---------lh-----
k--aslkfgsdlwkfesaikchkpqa---lirvcg-gsv-------rgda
sielrh-kdatah----rrthvfnyl---c---------agn---vlvlr
--gkrla---gsgsatsqkstyacvfknl--e----rngn-iskahp---
f---t-c-yhtekslaeynvptgapyn---telpyrckcsswkaaseier
taneltlask-si-laidsgsggacrg--phclks--cctsa--------
----thvialakpgag---hdss-----tqydqlrlpvrfvqrg------
---lkt-rrkvtrekvqpekdkg---gye-tgrvl--aspvsdtwcpefe
i-gtpqdpics-dac--kcsfsskehivtvkgttctlkph-yvs----l-
hnsga--si----kvp-h-iv--vltcdavqagk--kqvk----tg--s-
----ksgkfgyre--pynahp-------a-cet---epglhsgdigvswn
say----yqannvigmpswksadhfkl---dki---vsckcvanc-----
l-t---tsylgfe--ahlflsvl--ssgdlgakc-t-lslasedmkygrv
radgn------htwgivniq
>H
pklpyvrskavv----llllr--------ylpaqya---spttlaap--f
-----sggyarekqqynyncqdggpfgktgahhh-----------avgmv
kdsanltlgssl-rfeevtachkpqa---lirvcg-d-------------
-----------------------yfi---c---------agh---vlgfs
--gkrla---gsglatskknsyncvsknl--d----rpgnsikkaat---
ffsat-c-yhpenalaefdvptgspys---td---rcksttwkagnd---
nag---lkhk-sv-lafsngsqtacrdssppchka--cctha--gkhdlw
-srkshvialaksggg---h-sr-----tq-tqfpapvdfvqlgc-----
---ikt-rrf-tmkkvqpekdig---gyq-tgrpl--aspvidtwkpefd
ilatlqdpicy-nac--kcnftnvsrvvt-kgtictlskh-yvs----k-
dnsgarvni----nev-teiv--vytcdavqdgkskkmqk----ag--s-
----ra-rfgyrsrqpyaarpret-sstl-crd---epg--asdig--w-
---------addasalp-wtsdahfkl---kkv---vtckcva-------
l-s---tkylgye--qhlflevv--sakdlgatsva-lslet--mkfgrm
raegd------htwdemsis
