>E
v--rm----egncil---r---a---gseefh-gfelkidgt--------
prhev-------tegesefal-----vtkykvspl-rvhn-e--ptflle
aetllaek--lfla-g---------eptvl-nldfpnc--d---gagcqk
---rh----e---scplcctp-----evgvvnnvheaeikd------yss
kiptfiagvg-e---icwivvhevivqyltpkrng------lssgftfev
alg-i-----ilalpryk-------g-k-g-----------qkgtlvelv
-dyrtiikakntrhghpsgniss----gdirdkyymklhggglrqtvaml
--h-egsi--------tagvfcnk---ktfdsmlrhk-----alk---lf
sheksavhlt-gldcitayhgfkllg--kygirdyrleklqrff-vmalk
nfsk-sff----tmhrn-tiekkt------rhkqerala--klqgiddpt
qislks-----------------yparl----gela----hsadgsre--
-keddcaagglvanws-a-eteftkgnr-t---gqvrtgla---gtf---
---------k-vagqcy-e----gqq--gagevagkgyikvylvgfysst
khhafq---avri-edsnimiekipplgy----i----------------
--saayqeea-skhfls---s
>node6
actwm----agy-----mr---avrpgcddfhhgvele---sa--cdgtd
qr-ea-------tpah-efgvfkakkvgryncspk-ki-tsn--alflha
aailmvqk--sfqg-l---------erstlarlvfpks--g---aagcek
tv-rqfvpfv---qcriccap-----q---ayevnnpnl----kkpefta
rtnshlstag-qvvascwigqynafaqflkpn---------ifg------
-vg-a-----lltaprfk-------g-k-s--tg--------elsvvelv
-thhtiappkngkhghpsgnipl--nps------------------vamv
--h-aggipdldnlcrtsglfckklpiscfdavlahh-----alk---lf
rahrsviqlp-gvneitafkgfkvlgpnkygiwdykleklqryslnlvl-
vnsersff----tmqrevakdkrt------yqk-----a--nlllledpi
evhlks-----------------ypskl----sefscpdgkeassvree-
--------tplnsewc-g-ndsftvavhva---gsaltdlg---gsyekv
atl------k-nagpcy-ecvya-rh--dawevggkswtrvylvgfycsv
kdhafq---yvki-tdrnvlleklsel------d----------------
--saayaeqatakslealkln
>F
g--rme---ggyciv---r---airkgsedfh-gfhln---i--------
arhev-------a--lqefal-----vtrykcgpl-tvgs-e--ptflha
sdtlladpsllfla-h---------dptilaklefpkc--e---gagcqk
---nh----eatsdcpmcctpsccrlevgcdegvheanlkdcetkaeyga
ktpdyivgvgne---iswevvyeviveyltpk---------fftgfgfev
alg-v-----iltlpryk-------g-k-g--tgs----kgqsttlvelv
vdyrtlvkakntkhghpsgnirs----gdirdkyymrlhggtlkqtvamm
--h-egsi--------tagvfcihnpiesidfvlaht-----alk---lf
shektsthlt-gldqiaayhgfkllt--kysrwdyr-eklprfliglaaa
dftk-sf-------------qkkk------kpkherala--klavigepn
qislks-----------------ysakl----gefacpdghgakgsre--
--------gglnsnwc-a-ttgftagpr-s---kgartgla---gtf---
---------k-vagqcy-g----grq--gtgeiggkgyirvyligfygst
khhtf---------edsniliekfsqlgytwpai----------------
--saayeeea-pkhfl-----
>H
g--pm----aafctl---rtlieisg-snsfh-gvean---s--------
phnev-------tqgeaefal-----vtkyrceplnkvgs-i--t--ahp
sat-lahd--vlla-r---------kp-vlerlelpkc--n---aagcgk
---rh----e---dt-tccgp-----n---eqnvhepnlkncstmgeyga
pisgvlggag-g---f--itvydsiihflg-------------g------
-ag-ickdptflslpr---------aek-d-ssgtkltgsgrsvtltqls
-dyhtvkk---skhehpsgniklmmdpgdvrdkyylklhge--dqsigml
--hypgne--------iagvfcidihisifnmvltnn-----aln---lf
hherfalhlt-sidevsafagfkllgpkkygiwdykmdktqrffmglelk
ifan-sffy---tmhrn-tiqakstpsreflqk-----a--kllviaepv
gislkd-----------------faskf----gefacadqrng-gsrkd-
--------aglnanwc-a-ampftasir-tdrig--rtglpenagpf---
---------k-vagqch-nc---srh--gaweiggkdyv---lvsfycqi
ehhafq---cviitaehnkliikingl------lalpphseaapkacrgr
mpaavyaeep-sknfhs---k
>B
vciwi----agycamacms---svrpgmkefq-----d---sv--csgkn
hkrev-------tegh-nysvfkakkvnryac------vp-e--alflpg
aeilltqr--lfl-rl---------esstlarivfpkc--g---pag-ek
tvpresvpfv---qantccrp-----q---aeeahnpnv----kkadyga
rinthlsseg-qvvafcwvgqysalaqflkpd---------i--------
--g-l-----flalp-gkadnvwfsg-e-g--fa--------evsvcqis
-t---flaskngkqghsngsvkl--hacenrnk-----ngvkgeasaptv
--h-aasipdvdnlcrssgafckql--------lght-----afk---fv
rphra--hia-gvtaitafkgfkilgpkqygiwqykse-------glvlr
vnse-nfy-agktmqre-dkdkrt------hqd-----a--kllvf--pi
evhlks-----------------yrkkl----gefaccdgkdatka----
--------tslasnscsg-n--ftvavpva---gsaltnlg---tsf---
---------kglaapvy-ecvyg-rh--gaseig-pswvivylggfycsi
kdhafq---nflp---kdvllqkinkl------d----------------
--tvqypdqaaakdleakead
>G
g--rm----agfcql---m---elan-tdqfh-gvean---a--------
pqhev-------tqgeaefal-----atlyscdplnkvgs-d--tafaha
aae-laqd--llla-h---------kp-vlerlefpkc--n---aagce-
----n----s---etplccgp-----n---eenihnsnlkdcdtmseyga
pisgvlggvg-g---fcwivayapyieflspk---------ifg------
-lg-ickdptflslpr---------vdk-dlssgt----dgsfvtltqlt
-dyhmvkk---akhghpsgni------gtprdkyylalhgg--desigml
--h-agsi--------tanvhcihi----fnmvlqtk-----tln---lf
hqeksalhlt-sldeiaafagfkllgfkkfgiwdykmdrlqrffm----k
ifan-gff----sqhrn-tiqsrttpd--flqk-----aqsklviicepi
elslkecmapfdaihkgsgksplftskf----vefacadarna-gssash
l-------aglsanwc-a-avpfiagik-terig--rkglp---tpf---
---------k-vttqcndec---grh--gaweiggqdyv---lvsfycef
drhafqiakcviisedhniliikinal------v----------------
--aavyeeea-sln------k
>node7
actwm----aayctmvcmr---svrpgsddfhhgveld---sv--cdgtn
qrhea-------tegh-efsvfkakkvsrykcgpk-kivp-e--alflha
aeilmaqk--lfla-l---------esstlarlvfpkc--g---aagcek
tvsrqfvpfv---qcpvccap-----q---aeevhepnl----kkpeyga
rinshlssag-qvvafcwigqynafaqflnpn---------ifg------
-lg-a-----flavprfk-------g-k-g--tg--------evsvvelv
-thhtimkskngkhghpsgnisl--npsdirdk-----aggkgeqavamv
--h-agsipdldnlcrssgafckqlpissfdavlahr-----alk---lf
rahrsaiqlt-gvneitafkgfkvlgpnkygiwdykleklqrfslglvlr
vnse-sff----tmhre-akdkrt------yqk-----a--kllvledpi
evhlks-----------------ypskl----gefacpdgkdassaree-
--------tslnsnwc-g-ndpftvavpvt---gsaltdlg---gsf---
---------k-nagpcy-ecvyg-rh--gaweiggkswtrvylvgfycsv
kdhafq---yvli-tdrnvllekisal------d----------------
--saayaeeatakplealkln
>D
actwm----ady-----mr---avppgcddfnhavele---sa--csgtd
qr-ea-------tgah-efgvfkahnvgryncspk-ei-tsnnftlflha
aavlmgqk--sfhg-lwpgkglfvigrselallvfpks--g---tsgcek
nv-ktlipyv---qcriccap-----e---ayevnnsnl----kkpeyaa
rgksnlstvg-qvpascwigqyhnyaqflkpn---atsfttvfg------
-vn-t-----lskaprfk-------g-kks--tg--------elsvvelv
-thhelappkngkhghpsgnlpl--dps------------------vgmv
--h-aggipdlanlcrtsglfckklpiscfdaelphh-----avk---lf
ksrrpviqlplgvnaitafkgfkvlgpskygvfdyklervqryslnlvl-
insdrsff----tiqrevakdkrt------hqk-----i--nlllleepi
evhfks-----------------ypaslististfacpdakeassvsne-
--------tplrsnwc-s-ndsnsvavhra---gyaltdlg---gsydkv
atl------v-nggacy-evvya-rhtvdaweiggkastrvylagfycwv
kthafk---yvka-tdrnvlleklsml------n----------------
--saayaeqatakrldem---
>A
vctwi----pgycamactk---avrpglrefqhganle---sv--cdgtn
rkrea-------tedr-qfsvfkvkkvsrytc------vp-d--slwlpg
aeilatqr--afl--l---------els-lprlvfpkcqqgergvag-er
tvirhlvpfv---qavtcctp-----q---aeeaq-pnv----kkaeygg
krn--lsaeg-qvavfcwigqynafahflnpn---------i--------
--g-i-----ilalp-gk-------a-e-g--sa--------avsvsevc
-vhqtilkskngkhghgngqvsl--hpyeiknk-----kgvqgeaavati
avh-agsypnvdslcrssggfckslplssfdgmlaht-----vlkpnsla
rp-wa--qlt-gvnditaftgfkilgpkqygfwdyksd-------glvlr
vnse-sff-tgktmpre-ikdkrt------hqk-----a--kllvledpi
vih--------------------ypkkl----geftskdgkdatns----
--------aavngswc-g-t--ftvavsts---gsaltnig---sef---
---haggeekgvagpvy-ecvyg-rh--gaweiggnsrsrlylggfycsl
kdhafq---lvmi-tdnnallqkigkl------d----------------
--saayadeavvraleamklt
>node14
g--rm----aafctl---r---airpgsddfh-gveln---t--------
prhev-------tqgeaefal-----vtrykcgpl-kvgs-e--paflha
aetllaek--lfla-h---------epsvlarlefpkc--n---aagcek
---rh----a---dcpmcctp-----d---eenvhepnlkdceskgeyga
kiasflsgvg-e---fcwivayeaivqfltpk---------ifg------
-lg-i-----flalprfk-------g-k-g--sgt----kgqsvsltelv
-nyhtvvksknakhghpsgnirl--npgdirdkyylrlhggafdqsvamm
--h-agsi--------tagvfcihipiktfnsvlthr-----alk---lf
rhersaihlt-gldeitafpgfkllgpkkygiwdyrleklqrfflglalk
ifak-sff----tmhrn-tiekrt------eqk-----a--kllviadpi
qislks-----------------ypskl----gefacpdgkdakgsree-
--------aglnsnwc-a-tdpftagvr-t---ggartgla---gpf---
---------k-vagqcy-ec---grq--gaweiggkdyirvylvgfycsv
khhafq---cvii-sdsniliekisal------i----------------
--saayaeea-skpfqs---s
>node13
g--rm----aafctl---r---eiaa-sdqfh-gvean---s--------
phhev-------tqgeaefal-----vtkykceplnkvgs-e--tafaha
aat-laed--llla-h---------kp-vlerlefpkc--n---aagcek
---rh----a---dtpmccgp-----n---eenvhesnlkdcstmgeyga
piagvlggvg-g---fcwivayeaiiqfltpk---------ifg------
-lg-ickdptflslpr---------aek-d-ssgt----dgrsvsltqls
-dyhtvkk---akhghpsgnikllmdpgdirdkyylglhgg--dqsigml
--h-agsi--------tagvfcihipiktfnmvlthk-----aln---lf
hhersalhlt-sldeitafagfkllgpkkfgiwdykmdklqrffmglelk
ifan-sff----tmhrn-tiqsrttpd--flqk-----a--kllviaepi
qlslkg-----------------ypskf----gefactdgrna-gsrae-
--------aglnanwc-a-adpftagir-terig--rtglp---gpf---
---------k-vagqcn-ec---grh--gaweiggkdyv---lvsfycei
dhhafq---cviitadhniliikinal------i----------------
--aavyeeea-sknfhs---k
>node15
gctwm----aafctl---r---sirpgsddfh-gveld---thckcdgtn
prhea-------tqgd-efalykatkvtrykcgpl-kvgs-e--alflha
aeilmaek--lfla-h---------essvlerlefpkc--n---aagcek
tvsrq----v---dcpmccap-----q---dedvhepnlkdcekkpeyga
rinshlsgag-qvvafcwigqydaiaqfltpk---------ifg------
-lg-a-----flalprfk-------g-k-g--sgt----tgqsvsvtelv
-nhhtvmksknakhghpsgnisl--npsdirdk-----sggkgeqsvamv
--h-agsipevdnlcrtsgvfckqipistftavlthr-----alk---lf
rdhrsaiqlt-gvneitafkgfkvlgpkkygiwdyrleklqrfslglvlr
vnak-sff----tmhre-aadkrt------eqk-----a--kllvledpi
evslks-----------------ypskl----gefacpdgkdasgsred-
--------aglnsnwc-g-ndpftvavrvt---gsartglg---gsf---
---------k-vagqcy-ec---grq--gaweiggkgwvrvylvgfycsv
kdhafq---yvli-tdsnillekisal------i----------------
--saayaeea-akpfqalqls
>node10
g--rm----ggycil---r---airsgsedfh-gfeln---t--------
prhev-------tqgeaefal-----vtrykcgpl-kvgs-e--ptflha
aetllaek--lfla-h---------dptvlanlefpkc--e---gagcqk
---rh----e---dcpmcctp-----evgvdenvheanlkdcetkgeyga
kipsfisgvg-e---icwivvyetivqyltpk---------ffggfsfev
alg-i-----ilalpryk-------g-k-g--tgt----kgqtatlvelv
-dyrtivkakntkhghpsgnirs----gdirdkyymrlhggalkqtvamm
--h-egsi--------tagvfcihipiksfdsvlthk-----alk---lf
sheksavhlt-gldqitayhgfkllg--kygiwdyrleklqrfflgmalk
nfak-sff----tmhrn-tiekkt------kqkqerala--kllviadpt
qislks-----------------ypakl----gefacpdghsakgsre--
--------gglnanwc-a-tteftagnr-t---ggartgla---gtf---
---------k-vagqcy-e----grq--gageiggkgyirvylvgfysst
khhafq---cvri-edsniliekisqlgy----i----------------
--saayeeea-pkhfls---s
>node3
vciwi----agycamacmr---svrpglkefqhgveld---sv--cdgtn
qkrea-------tegh-nfsvfkakkvsryac------vp-e--alflpg
aeilmtqr--lfl--l---------esstlarlvfpkc--g---aag-ek
tvsrqfvpfv---qantcctp-----q---aeeahdpnv----kkaeyga
rinshlsseg-qvvafcwigqynafaqflnpn---------i--------
--g-i-----flalp-gk-------g-d-g--sa--------evsvsevs
-thhtilkskngkhghpngsvsl--hpceirnk-----ngvkgeaavatv
--h-agsipdvdnlcrssgafckqlplssfdgmlaht-----alk---la
rphra--qlt-gvneitafkgfkilgpkqygiweykse-------glvlr
vnse-sff-tgktmhre-akdkrt------hqk-----a--kllvledpi
evhlks-----------------ypkkl----gefacsdgknatka----
--------tslnsnwc-g-n--ftvavpvt---gsaltnlg---gsf---
---------kglagpvy-ecvyg-rh--gaweiggkswtrvylggfycsi
kdhafq---fvli-tdrnvllqkigkl------d----------------
--saayadeaaakpleamkln
>C
actwl-lgsagy-----mr---avrpgcddfhhgvqle---sa--cdgsd
qr-eatavdtsrspaq-efavfkakkvgayncspk-kl-tan--alflna
aailmvqk--snkg-l---------qrntlarlmfpni--g---dagcek
tv-rqfvpfv---qcriccap-----q---ayevnnhnl----krpe--a
gtnsnlsssg-qivapsalgrkeafaqflnpn---------iyg------
-vgwa-----lltaprfk-------g-k-s--t-------------ielv
-thhtiappkngkrghptsi-pl--npw------------------vamv
--h-agg-psmddlcrtsglfck-lplncfdavlahhlrcetali---lf
sahrsivqlp-qvieitafkgykvlgankfgiwefklemlqryslnlvi-
vnsekaff----tmqrsvar--rt------nsk-----a--dllkledpi
evhlks-----------------ypaka----sefsspdgkeassvree-
--------kpvvaewc-gvnesfavavhva---gsalaelg---gssekv
atl------n-dagpcy-ectya-rh--eawevgekswtriylvgfycsv
kdhafq---yvki-tdrnvllgklssq------e----------------
--saaypsqataktlgalkln
