>B
tqtvqaa-----ststqylk-swqpchlvyygg-v-dtktckst-----v
tplkvvrlsgagavsdahrgvt---gigyedykgwslggafgv---nats
ngnavrgfqngdtkpaalt-whktlarmvcedvkghglfgtl---vnlva
edv--gdyspkgplkgihckkvkpavaiaa--atgtakk---sqesapek
ketkhc---nalyadk----segt-s--g-e--a-en----------sgl
c--ggakvsrgcgvmfkpsyaiklagdhik-------------------l
itnqvg------------qdhqnghkvadeffs-ygakp-----------
-------pfk---dpl--argqngktya-----sgdt-talvdnlsyddc
alyqk-------klnc---pseydsd--ts--knemst-----gwyhrkn
q--vilgcrkvsiepr-----gfr---dkat-------ngd-------gg
gn------fpv------vg---tknviq----------aqt---levqv-
-----asrkgdkhmpknkvallgmiiv-ckgtvhpkp------ea-----
ttl-----fecld--tqrrkll---dhlgvnrrferl--laqmyp---am
igqkmdyp-qi-qyatkg-f--ldf-------aamg--gqggiy------
-----------pesknlmlvefrcqvl-yadhslyrdhnythqfdq----
--kkv--ngh---silkdgkekitvt------------wevg----plpf
kaa
>node7
iqkvqaa-----rttaqylq-swqpchfvyygs-v-dsktckpn------
------rlagagplsdashgit---gagypdykgwslgnevgv---navs
ngsnlra----dskpapls-wpkr-aravceevkgiglfgim---vnlvv
env-kg---pigpln-----kvkpgvavae--t--takklkapvqcepnk
kqtkhc---nslfgdk----aegtkdggg-d--e-en----------agl
c--ggadasrgcssmlkpcyaislasfhlk-------------------a
itnqva------------hnhddghkkpgayfs-ygadk-----------
-------pfk---dpl--ars------a-----sdet-ttlvdnlsyddc
plyqkse--lvaklnc---akdhdsg--ts--knemsa-----gwydrkn
vlsvilgcr-----prvhpvhgfr---dkak-------ngd-------qg
nn------fpl------vg---tknsve----------aqt---lelpv-
----------dkplp-nkgaqlgmitv-cngtvkpqp------ea-----
---trllfyecfq--tnkrkll---nhlgvnkkfdtl--lp-lya---am
vtqkmdqp-si-ryatkg-y--vdf-------aame--gq-giy------
-----------ksskslglvefrcqvl-ysg--------ythdfeq----
--skv--ns-ckdailkkqkatinvt------------weig----plpf
kai
>node14
ikkhean-----rattqyla-nwq----vyygs-i-ngkackag------
------rltgtgplmdschaim---gltycsyhgwnkggetgl---nlvs
kgtnlra----eskplale-wpkr-prsvceetkelgmfgcm---ldlvv
gsv-kd---pigpld-----ktkpgvaiaq--n--askmlktpgkcgmak
kqlkhc---nslfadk----gegtkdggg-d--e-ek----------vgl
c--ggeddsrgcntmlkpcyaenlasfhlq-------------------a
itkqvh------------hnhddgnkklgsyyg-ygadr-----------
-------pfk-----gvkgrs------p-----seet-ptgvnnltydec
plyqkae--lviklnc---akdhdsg--ta--knyisalf---gwydrgk
vlspilgcr-----paihpvhafr---ekdk-cqlrflhankiam-skqg
nl------fplggldcetg---tknsve--lvgcp---ars---lelpv-
----------dkkfp-nntaqvgmlav-csgtvkpqpkdht--eg-----
---srllfydcfeldnnkqkll---nhlgcnkkratl--lp-lya---ai
vaqkmddp-si-ryatkgvy--idfyges--gaamdvfgq-giy------
-----------kpsaskglvef-cqv-------------------q----
--skd--ds-ckdailk----tlnvt------------weig----plpf
kai
>node6
fqkvqaa-----rttahyle-swgmchfiyygs-v-dlktckpg------
------rlagagplsdagagvt---gagypdykgwslgdevgn---navs
ngsnlra----eakpapls-wpkv-skavcedvkgiglfgim---vdlvi
env-kg---pfgpln-----kvkpgvava--------krlkspaqceltk
kqtkhchsasslfgdk----adgtsdggg-d--e-en----------agl
c---ardayrgcgsmlkpcyaiclagfhlk-------------------s
itseva------------enhddvhkkpaayys-ygadk-----------
-------pfk---dpl--qrs------e-----veet-ttladglsyedc
pvyqkae--lvaklnc---akehssg--tp--knemsn-----gwydrsn
vlsailgcr-----prv-aq--fr---dkak-------ngd-------a-
--------ypl------vgrgwtklsme----------akt---lelpv-
----------dkplp-nkgaqlgmitv-cdgtvkpqp------ea-----
---trlkfyecfq--tdkrkfg---ahlgvnkkfd-q--lp-lya---vm
vtqkkaqp-si--yvtkg-y--vdf-------casd--g--giy-revfc
rapdqm---iekntkslglvefrcqvlnysg--------yaedf------
--gev--ng-ckpailkkqkstisat------------weis----plpf
kei
>G
iknheak-----qattqyla-swq----ayyas-i-ngkvckagtlggq-
------rvkgegplsdtchgiv---gltycsyhawdkggetsl---nlvt
kgtqrra----qsktlale-wpkr-prklceeakepgnfgcm---ldlvv
gsv-rd---avdcld-----karpgaacteeg--------------gmem
kdlkhc---nslfadk----gealmdggg-g--e-ek----------vgl
ckkggendsrgcstmqkpcyaenlgtfhlp-------------------a
iheqvh------------hnhgqgdpkfgpyys-ygadr-----------
-------s-------g-kgrs------pfkgmeseeifpagvhhltyedc
plyqkae--ldielkc---akdqnsg--ta--knyisaly---gwydrgk
vfssvlgcr-----pt--svhafk---skds-cqlrflhahniam-skqa
gl------yplggldceta------kvn--lvgcp---aks---nelpm-
rdydv-----dkkfc-ng-aqv-------gptvkpqpkehtlasg-----
---skhmlydcfdlentkqrllctwrqlgcnkrrttl--lk-lyd---av
vsskmedp-sm--------------ynesasgvamdlsak-gly------
-----------kps-skgliif-chv-------------------e----
--sqdqsns-csnailk----tlnatmdqagmemklelwvig----klpa
k-m
>E
ikshesnetgydracvehlakkwq----vyyas-v-sskdckag------
------iltgttplldgchgimkkrgltyspyvgwnkggetga----lvs
tctdarg----a--------wpk----gvcdesketgmfgcm---nnlvv
gsg-rd---pigple-----ktrprvyiaq--d--adrkmk-pgecgmak
kdlkqv---nslfpsk--lggsgtkdagg-dgeeedkqlpetvslptvgl
c--ggedesrecdtmlkscyaenl-----r-------------------a
ftkevh------------hnhhdgykevsayyg-ygadr-----------
-------pyk-----g---rp------p-----saea-qsgv---nydec
pvfqkae--lvikldcdkfardhdgg--trraknyissvf---gwfecgk
ilspilgcr-----paihpihyfr---aqdk-cqlrflhankldliikps
klktgnfvfplgglacdag---akngt---vvgca---trn---pelpt-
----------skkyp-nntgkvgaltvgcaekeepqskdhk--qgdctpa
---srllfyecfeldehkqkfa---nqlgcnnkrvtlqllp-lyd---ak
vaqkkadp-ss-qyankgvy--idfygns--gaamqc-gh-giy------
-----------krsaskglvef-cqv-------------------q----
--skd--hs-cksli---------vt------------weiscankplpf
qsi
>F
vkrhern-----rvsaqyla-nwp----vyygs-p-ggkeckag------
------rldtaaplldsshaimkkrgltyssyhgwnkggdtgakcln--s
kgtnlre----a--------wpk----nvcnenkefgmfgcm---lnliq
asg-rd---pigsld-----ktrprvaiaq--d--ldkkik-pgscsmnt
kqlk------smfatrfllagsgskdggg-dged-daq---tsslptvgl
c--ggeddsrgcgtmlkpcyaenl-----l-------------------a
itrqvhdikysilktccdhdnnqgyrkvfayfg-ygadr-----------
-------pyk-----g---rp------p-----seep-psav---nydec
plfekaehalvvklsc---srdhngg--vfrageyvsnvf---gwfecgk
vlspilgca-----paiqpieafh---amdk-cqlkflhanktsl-tkeg
nl------fplggldcatn---aknsi---lvgca---ars---lelpt-
----------skkfp-nhttkvgmlavpcagtvkpqpkthk--eg-----
---srllfydcfeldnhkqkla---dhigcnkkrvtlqllv-gya---gk
vaqmmgdp-nv-rysakqvy--isfytes--gaavpcfgh-giyn-----
-----------krsaskgmvef-cqv-------------------q----
--gkd--hq-ckdii---------vt------------weiscakkplpf
ksi
>node10
ikrhesn-----rasvqyla-nwq----vyygs-v-ggkdckag------
------rltgtaplmdschaimkkrgltyssyhgwnkggetgak-lnlvs
kgtnlra----a--------wpk----svcdeskefgmfgcm---lnlvv
gsg-rd---pigpln-----ktrprvaiaq--d--adkklk-pgkcgmak
kqlkhc---nslfpsk--lggsgtkdggg-dgee-dkq---tsslptvgl
c--ggeddsrgcdtmlkpcyaenl-----q-------------------a
itkqvh------------hnhndgyrkvsayyg-ygadr-----------
-------pyk-----g---rp------p-----seea-psgv---nydec
plfqkae--lviklsc---ardhdgg--trraknyisnvf---gwfecgk
vlspilgcr-----paihpihafr---aqdk-cqlrflhanktnl-tkpg
nl------fplggldcdtg---aknst---lvgca---ars---lelpt-
----------skkfp-nntakvgmlavgcagtvkpqpkdhk--eg-----
---srllfydcfelddhkqkla---nhlgcnkkrvtlqllp-lya---ak
vaqkmgdp-sv-ryatkgvy--idfyges--gaamqcfgh-giy------
-----------krsaskglvef-cqv-------------------q----
--skd--hs-ckdai---------vt------------weiscakkplpf
ksi
>node15
ikkaqan-----rtttqylq-nwq----vyygs-v-dsktckas------
------rlagagpltnashgit---gatycdykgwnkgneagl---navs
ngsnlra----dskplale-wprr-aravceetkgiglfgim---ldlvv
esv-kg---pigpln-----ktkpgvaiaq--n--aakklktpvqcgmnk
kqtkhc---nslfadk----vegtkdggg-d--e-en----------vgl
c--ggddasrgctsmlkpcyainlasfhlk-------------------a
itkqvh------------hnhddgnmklgayft-ygadk-----------
-------pfkhlhgpg--grs------p-----seet-ptlvdnltyddc
plyqkse--lvaklnc---akdhdsg--ts--knnmsalf---gwydrkn
vlcvilgcr-----pavhpvhgfr---dkak-------nddkvdm-skqg
nh------fpl------tg---tknsve----------art---lelpv-
----------dkkfp-nngaqlgmltv-csgtvkpqpedht--ea-----
---trllfyecfe--nnkqkll---nhlgsnkkrdtl--lp-lya---am
vaqkmdep-si-ryatkg-y--vdfyges--gaamegfgq-giy------
-----------ksssskglvef-cqv-------------------q----
--skd--ns-ckdailk----tlnvt------------weig----plpf
kai
>node13
ikkheak-----rattqyla-swq----ayyas-i-ngkackag------
------rlkgdgplmdschgim---gltycsyhawnkggetsl---nlvs
kgtkmra----egkalale-wpkr-prklceeakeagpfgcm---ldlvv
gsv-kd---avdcld-----kakpgaacaeeg--------------gmem
kdlkhc---nslfadk----geatkdggg-g--e-ek----------igl
cnvggeddsrgchtmikpcyaenlgsfhlp-------------------a
ianqvh------------hnhgqgdpkfgpyya-ygadr-----------
-------pyk-----g-kgrs------p-----seei-ptgvnnltyedc
plyqkae--lvidlnc---akdensg--ta--knyisaly---gwydrgk
vfssvlgcr-----pt--pvhafr---skdr-cqlrflhahkiam-skqg
nl------yplggldcetg------kvd--lvgcp---aks---nelpvp
rdydv-----dkkfs-nd-aqv-------sgtvkpqpreht--sg-----
---srhllydcfdlentkqrll---nqlgcnkpratl--lk-myd---av
vaskmddp-siarystkgvyqfidfygesytgvamdvsaq-giy------
-----------kpslskglief-chv-------------------e----
--sndmdds-csdailk----tlnvtmkqggmemklelwvig----plpa
k-m
>node3
tqkvqaa-----kttaqylq-swqpchfvyygs-v-dtktckpt------
------rlagagplsdashgit---gigypdykgwslgnavgv---navs
dgnaira----dtkpaals-whkr-aravceevkghglfgil---vnlva
edvakg---pigplngihcgkvkpgvavaa--t--takk---precapek
ketkhc---nalfgdk----segtkdagg-e--e-en----------sgl
c--ggadasrgcgamikpsyaislagahlk-------------------l
itnqva------------qdhqdghkvpgayfs-ygakp-----------
-------pfk---dpl--arg------a-----saet-ttlvdnlsyddc
alyqks---rvqklnc---psdhdsg--ts--knemst-----gwyerkn
qlsvilgcr-----prvhpvhgfr---dkak-------ngd-------gg
dn------fpl------vg---tknvvq----------aqt---lelpv-
----------dkhlpknkvaqlgmitv-cngtvhpqp------ea-----
---tklllfecfd--tqrrkll---dhlgvqkrfetl--lp-mya---am
vaqkmdhp-si-qyatkg-f--ldf-------aama--gqggiy------
-----------ksskslelvefrcqvl-ysd--------ythdfeq----
--skv--nghckdailkdgkekisvt------------wevg----plpf
kaa
>C
fqkvqaa-----rtvahyle-awvmchfvyygniv-dlktckpg------
------rlagagpltdagtavt---gpsypdykglvlgdevgn---navs
tgsnnha----eakpatls-wpki-nsavcddvkgcalfgiv---vnlvi
env-kg---pfapln-----kvkpgvava--------krlkspaqcemnk
kqtkhchsastlfgnk----adgstdggg-d--e-en----------agl
c---ardayrgcgsmlkvcyaiclagfhlt-------------------c
iss--a------------enhddvhkrptayystygadh-----------
-------pfk---dpl--qrs------d-----leet-ttlanglsyygc
-vyqkge--lcakfnc---areftsg--tp--ksemsn--qeigwydrsn
plskilgca-----prv-aq--fh---dkii-------ngd-------a-
--------ypl------vgrgwtklsma----------dkt---lelpv-
----------qkplp-nkggqlgmitv-aegptkpqp------ta-----
---kglpfyecfq--tdkkkfg---ahlgaykkfd-q--lp-lya---vm
hte-------i--yvtng-y--vdf-------casg--t--eiy-revfc
rapdqm---iakrnkseslvafrcqvltysa--------faedf------
--gev--ng-ckpavlkkqnsgi---------------weis----plpf
kei
>H
ikkhepv-----rqsieyfa-awe----ty-an-ilngkackas------
----------dgpaldtcngvm---gltycsyhawnkggqatl---nids
kgtkmre----dgkalalevwpkr-prklceeakeagpfgsmgaqldlva
gsv-kd---avdcld-----kvkpaaacaeeg--------------glpm
tdlkhc---nslfadk----vqatkdgggpg--e-ek----------igl
cheggeddsrgchtmikpcyaigltsfhfp-------------------a
ipnlvh------------hnhgqgdpkfgpyya-ygadr-----------
-------pyr-----g-kgr--------------eai-ptgvpslsyqdc
slyqkae--lvidlnc---tkdedhgsetp--knyicyly---gwydkgk
vfsavlgcr-----pk--pvrafr---rkdrtcqlrfghalqiam-skqg
nl------yplggqdcdtg------kvdaplvgc----aka---enlpvp
rdyev-----dkkfp-nd-aqv-------agtvkpeprrhy--sg-----
---srhllydcfdllntkqrll---nqlgcrhpratl--lk-mydfkqav
vaskmdga-siarhstkgvy--ldfngesytgvamdvsvq-gvy------
-----------kpslskgslvf-chv-------------------kggrl
sssndmeds-csdavik----tlnvtmkqfgmemklelwtik----slha
k-a
>A
tqkaqaa-----nttvqylq-twqpchfvyygs-v-dtkgckpt------
------r----gslsepshgit---gigypd---walgnmvgv---nais
dgnanva----dtmpaals-wssv-aralceevkghglfgvl---knls-
-dmakg---pvgplngivcgkvkpgvataa--t--ttkk---precppek
ketkhc---nalfgdk----negaydagg-e--e-en----------sgm
c--sgkdqsrgcgamikpsyaislagarlktseskkdydalnhsvsrall
itnqvd------------qahqdghkvdgayfr-ygakpvgllggikyqq
gayvivhtfk---dpi--arg------a-----saet-ttlvdnmsyddc
alyqks---rvqklnc---psnhegg--ta--keemtt-----gwyerka
kvsvvlgcr-----prvhpvhgfrygkdpak-------ngd-------gg
dw------fpl------vg---aknvvq-------qddaqtrgsldlpv-
----------dkhlpknkvaslgmvtv-cngtvhpqp------ea-----
---tkllllecfd--tqrrkll---dhlpvqkrfetf--lp-myv---am
vaqkmdhp-ai-qyttkg-f--ldf-------aama--ghggiy------
-----------kkgksle------qvl-ysd--------ythdfeq----
--skv--nghcknaiqkdgkekisvt------------wevg----plgf
kvs
>D
lqkvkae-----rtgahyle-dwgmchfiyygs-v-dlktckpg------
------rlagagplsdggagvt---gagypgykgwslgdeags---nais
nggslka----eak--als-wpkv-skaicedvkaiglfgvm---ldlvi
env-rg---pygpln-----kvkpgpava--------krv--kgqcelvk
kqtkhchsatsllgdk----aegtsdgag-d--e-ek----------aem
c---ardlyrvcgtmlkpcyaiclagfhlk-------------------d
itseia------------edhesvqkkpvsyfs-ygadk-----------
-------efk---t--------------------qet-ntladgldyeec
pvyqkae--lvaklnc---aqehssh--tp--kdem-n-----gwydrln
elsaklgcr-----prf-gq--wr---ekak-------nsa-------p-
--------ypl------vgrawtklsme----------pkt---lelpv-
----------dkplp-nkq-qlgivtv-cegvvrpep------ea-----
---nrlkfydcfe--tdkrtfg---ahlgvnqkfd-q--lp-lya---vk
vtqkkaqptsi--yvtkg-----qf-------casn--g--giy-revfc
rapdqmlvaiskntkslglvefrcevlnygg--------yandf------
--gqv--ng-ckpailkkqkvtisay------------weis----plpf
kee
