>F
h--------------------kepl---avlpnftrtegdlgg-atvsqs
c--kkslscllgqlglnkgay-gtkwnkkq---------kkirp------
dvaehrnapndadfl--tvpfvadasdr-----------vsdfeivvvq-
-eac-v--epnv----slpgaasigvdalpfidifrkvas-wmkdaeyla
weeialkmnggkggknkeiggggqghk--pglgtqkdqrskmihrtggkd
yqqvgiatprevvftmpshrsleffvvdqnngpkgsfphsegtakpscll
lak----angmdtfearva--fsvfmggekglvydknagngvvral-vts
aclpefkhvlvv-igvsqskkqkrg------tdg---mk-r-vry-----
----qatqg-----------g----isl------pasacvn-------fa
at--vn--gl-egikdqflpealstlr-ckegakvviiindlwdls-iai
vgknvrr-evqanppntfmlpncifrtpfgsgsvrmg-qiwfpslcfvsg
nlidchkvrctgqsl----g-pggaarg-------------------ksv
ksqarlrid--tcvcqpvggrqgnalli---ctrc---gaatnhpsrh--
--cvamqpit-sgggcntsh----gslis
>node6
har-----fa--------eqkkdkpflcavlmifnrt-----i-ltlsqs
c---rphnsllgalqlkkvvcytvqwseaqtp---gy--rafrp------
kiavk-------------i----dasdkftfksqfrggktstfeiaaiv-
-elt-gkntpgi----dapssps-dvtrfafvtylh---sdwmhsagyfd
fdrtavkihgaeggldntvgsgnagnk--anmgqqh--------pnsgkd
faps-kpgprevlfalp------fflrdt--g------rvqatek-----
lgk----a---ktqvikal--yks-tgalrgldynhtk-sgvprafqvrd
aclpsflntllg-vfacqlqkqtrrd-ai-wsta---tk-r-npy-----
----epsnhsdcg-------gfrpyppllpayglf-----n-------fq
sg--vt--gprggfkqel--ed----i-vkesskaeivskklwelp-i--
-gkdfth-dvqqhqpsdyalgncievsp-aggmmrvn-eywypplcfvw-
---kcln--cksqal----n---------------------------kqt
---akirtd--tclcarisgmqgesf-------rt---gtst-n-dqh--
--g--------sgagcn--y----gqimm
>node7
harngasyfpma------qqakdklflcavlkifnrt-----i-mtlsqs
c---rprnsllsalqlkkgvcfgvewskaqtp---dy--rafrp------
kiavn-------------idfeadasdkftfksqfrggktstfeiaavd-
-elc-gkntpgi----napgspsidvtrfafityln---sdwmneaeyfd
fqqaaikihgaeggldhtigsgnagnk--adlgeqh--------pnsgkd
faptgkpgprevlfalp------fflrdt--g------qveatek-----
lgk----angmktqvvkvl--yss-tgalrgldynkta-sgvpraf-ird
aclpaflntllg-vfacqvhkqtrki-av-ltda---tk-r-gpy-----
----epsnq-dcg-------gfrpypplapa---ygsacvn-------fq
sg--vp--gprggfkqel--ed----i-ikesskahiirkklwdlp-i--
-gkdfth-dvqqnqpsdyalgnciyvsp-apgmvrvd-eywfpplcfvw-
---kcln--cksqal----ngpgsvsry-------------------kqt
---akirtd--tclcahiggmqgesf-------rt---gtat-n-dhh--
--gvam-avvtsgggcn--h----gnimt
>node14
hardggeffplv------qqgkerlllcavlkafhrtesdlgi-itlsqs
ckvkrppscllgqlglkkgvcfgvewnksq---------riirp------
evaqhkn------fl--tisfvadasdr-----------astfeiaave-
-eac-vndapni----napgaasigvtrlafveyfhev-sdwmkeaeyfd
wqelalkmnggkgglnkeigsgeagnk--adlgaqk--------rkggkd
yaptgkpaprevlfampsrrtlefflvdtaggtk----qseatak-----
lgk----ahgmdtqavrvl--ysv-agaqrgllydkta-ngivral-vss
aclpdfldtlvv-vsvsqtkkqtrkr-vv-ltdg---tk-r-gry-----
----apnqg-----------g----pll------gasacvn-------fa
at--vp--gp-dgfkqellpedlatir-ckesakvhilvtnlwdls-i--
-gkdfsh-evqqnqpsnfllgnciyvspfgsgsvrvg-efwfpplcfvwg
nlinchkvrctsqpl----a-pggvakc-------------------ksv
ksqakirid--tcvcqpvggkqgnalliy--carc---gtat-h-nhh--
--ciam-aitksgggcn--h----ghilt
>A
harngasfhpm-------eesrdkl-lt--lvifnrt-----ismt---s
c---rprsstlsalqlkkgv----nwngaqtp---dy--rqfrpsnsglk
kiaan-------------ldlekdasdkfafksqfrggkastfqtaavn-
-nlc-ghnt-kv----nepg--sidvtrigfrtylg---sdwmsessyld
fqqsanrihgldgnldhtistgnaesk--aalseth--------knsgkq
faasgtpgpravlfglt------ffireg--g------qvettek-----
lgk----dnemktqvvkvltpfst-tg--rgmdyqpaa-pgapraf-ikg
aclk----nqlgevftcqvnkqtr-i-av-lass---tkvr-gpy-----
--naepngq-dsg-------gfgpypelrpn---ypgicln-------h-
-g--vp--gpr--fkegl--ed----i-ikesrkthimrsplwkvpvi--
-s------dvsqnhagsyalgnciyvss-apg-vrvd-eywfpplcfvw-
---ncle--cksqsl----ngpgt-sry-------------------tqt
---akisvdngtclcahiggmqag-f-------rt---gksa-d-dh---
--giam-tvvasgggce--q----gni--
>node3
harngasfhpma------qqardklylt--lkifnrt-----i-mtlsqs
c---rprnsllsalqlkkgv----nwngaqtp---dy--rafrpsepglk
kiaan-------------ldlekdasdkfafksqfrggkastfesaavn-
-elc-ghntsnl----nepg--sidvtrigfitylg---sdwmneadyld
fqqsaikihgaignldhtigtgnaenk--adlteqh--------knsgkq
faatgtpgprevlfalt------ffirdg--g------qvettek-----
lgk----dndmktqvvkvltpfst-tgalrgldyhkta-pgvpraf-ikd
aclpaflnnllg-vftcqvnkqtr-f-av-lasa---tk-r-gpy-----
--dsepnvq-dcg-------gfgpypplapa---ynaicvn-------f-
-g--vp--gprggykegl--ed----i-ikesskahiirsklwklpvi--
-gkdfth-dvnqnhassyalgnciyvss-apgmvrvd-eywfpplcfvw-
---kcld--cksqal----ngpgsvsry-------------------kqt
---akistd--tclcahiggmqgegf-------rt---gtaa-n-dhq--
--giam-tvvtsgggcn--h----gnimt
>node10
h--------------------kerl--cavlpsftrtegdlgv-itvsqs
cklkkslscllgqlglkkgay-gtqwnknq---------kiirp------
evaehkn------fl--tvpfvadasdr-----------vstfeivvve-
-eac-v--epnv----sapgaasigvdclpfveifrevasawmkqaeyls
wqdialkmnggkgginkeigsgeaghk--pdlgaqk--------rtggkd
yaptgkaaprevlftmpshrsleffvvdqaggpk----qseatakpccll
lak----ahgmdtgearva--ysvfmggekglvydktagngvvral-vts
aclpefkhvlvv-isvsqskkqtrgr-vv-ltdg---mk-r-gry-----
----apnqg-----------g----ssl------gasacvn-------fa
at--va--gl-dgikeqllpenlstlr-ckesakvpiivnnlwdls-i--
-gknvnr-evqqnppnnfmlsnciyrspfgsgsvrvg-qiwfpclcfvsg
nlidchkvrctsqpl----g-pggvakn-------------------ksv
ksqakvrid--tcvcqpvggrqgnalli---carc---gaatnh-nrh--
--ciam-pit-sgggcnsph----ghiit
>D
har-----fn--------eqkkdkafl---lsifnrt-----i-ltlghs
c---kphssllealhlkegncyt-qwseaqaprltgydrrafrp------
kiavk-------------i----dasdkftfksqfrgakastfeiaaiv-
-e-----ntpgi----dppgspk-evtrfafvtylh---sdwmnaagyfd
fdrtavkihgaeggl-dtvgsgnaggk--anvghqh--------pnagkn
yaps-kpgpseafyalp------fflrdt--g------rveatek-----
igk----a---ktqvikal--yks-vgelkqldynqgk-sgvarafqvrd
acfpfflntllg-vfqcqllkqtr---aiywsta---dn-mdapy-----
----epcnhsdcg-------gfrpyppllpaygly-----n-------fq
sg--ii--gprggfkqep--ed----i-ykeaskaeivpkmlwelp-v--
-gkdfah-dvqqhqpsdyvlgkcisvsp-asgeirvn-efwyeplcyvw-
---tcle--ckgqal----y---------------------------kqt
---arirtd--tclcaqqsgaqgesf-------ri---gtst-n-ddh--
--g--------sgdg----y----gqimv
>B
harsgatfhpmg------qqarnklylt--lkifsrp-----i-mslsqt
s---qprnkllsalqmrkgv----nwgaaqtp---ey--rafrpsepalk
kiaan-------------ldlekdandkfafktqfrggkaatfgsapln-
-elc-ghsttnlikag-------idvtrigfitylt---gnwmnevayld
fqksvtqihgavgnldhtigtgntenk--adldeqh--------knsgkq
faatgapaprevlftlt------ifirdg--g------qvettek-----
lgk----dndmktqvvdvltpftt-kgalrgldyhkta-pgpphal-ikd
aclpaflnnllg-ifacqvdkqvr-fsmv-lqga---tk-r-gpy-----
--dserniq-dcg---vgisgfgpypplgpa---ydaicvn-------f-
-gev-p--gprggykegi--ek----i-ikesnkphiirlklwklpvv--
-gkdfthydvaqnhaspyvldnciyass-apgmirvd-eywfpplcfvw-
---kcld--ckeqql---yngpgsvsry-------------------kqi
---akistd--tclcvhiggmqgsgf-------rg---gtat-n-qhq--
--giai-ivvtsgggsn--h----gdvmt
>E
h--------------------kqrl--callppfprttgslgv-ltvsks
cklkkslscllgqlglakgaf-gtqwnkgq---------kiirp------
evaehin------fvsitvpfvatasdr-----------vsafeivvte-
-eac-v--eptv----sasgvgeigvdclpfveifrevadasmkqadyls
wqavalkmnggkggvnksvgfgeaahk--pdlgsqk--------rtggkd
yagtgpaaprdvlytmpshrsleffvvdqaggek----qsessskpcclf
lanvgptahgmntgmarlt--ysvflggekally----gngvvral-vtg
aclpefkhvlvv-isvvqskksargr-iv-vtdg---mk-k-gry-----
----a--qg-----------g----ssl------gasdcvn-------fa
aa--va--gl-dgik------elstlr-ckqsaklp-vvdnlwdfr-i--
-gk--ir-evnpdppehfrlsqcvyrepfgsgsvrvg-qlwfpslcfvsg
nlidchkvrcvsqplsrn-s-pggvgkn-------------------ksv
ksqatvrie--tcgcqpiggrpadalli-pkcars---gaatnh-nrq--
--ciam-pka-sgfgcnsphmptaghiik
>node15
hardgaeyfpmv------qqakdrlflcavlkifhrtesqlgi-itlsqs
ckvkrprscllnalqlkkgvcfgvewnksq---------reirp------
eiavn-------------isfsadasdk-----------tstfeiaave-
-elc-vndapgi----napgapsigvtriafidyfhlq-sdwmkeaeyfd
wqqaaikmhgaqggldhtigsgnagnk--adlgqqq--------rdtgkd
faptgkpgprevlfalpprrtlefflvdt--gtk----qveatak-----
lgk----angmdtqavrvl--ysv-aaaqrglhynkta-sgvvraf-vss
aclpdfldtllv-vsacqthkqtrkr-av-ltdg---tk-r-gpy-----
----epsqq--cgkaf----gfrpypplapa---tvsacvn-------fq
ag--vp--gprdgfkqellpedlptii-inesakvhilrtklwdls-i--
-gkefsh-dvqqnqpsdfilgnciyvspfgpgmvrva-eywfpplcfvwg
nlikchn--cksqpl----a-pggvakc-------------------ksv
krqakirtd--tcvcahiggkqgnsf-------rc---gtat-h-dqh--
--cvam-avvtsgggcn--h----ghimt
>G
hardggeffplviteshlhqgkerlllcavlkafhhtekdfgi---lsql
c--krnpscphgelglkdgacygtewntaq---------rvirp------
evaqqkt------il----ffladtpdk-----------aepfelgave-
-eackvngapsv----aargsasvgvtrlafvdyfhet-gd---daeyfd
wqaldlkmnaekgglkddigsgeagnk--adlgavk--------qhggke
yaqtgkpepkemlfgmpsirsl----vetaggik----qdealg------
tgi----ahafdtqavrvl--yss-aaaqrgl---sts-egitrsl-vss
gcdpdaldtlil-atvght----rkr-vv-ladg---tk-k-gtytnkra
qy--aeeag-----------g----pll------gasesgn-------fa
tt--vp--gp-ndfkaellseelatiryckeaapvhllvtnnwdls-l--
-grqlsh-evsqgqaaylglgnclylapfggvsvrvs-eywfppfcfvwg
ylinyhkvrcksqpl----v-pdgvtkc-------------------kav
ksq-kihid--scvcqpisgkqgngllty--cgrs---gsaa-h-hhh--
--cram-aiyksggvca--h----afils
>H
hardggeffplv------eqgkerlllcailkaghrtekdfgv---lsql
c--krspscmmgdlglkdggcygaewntaq---------ravrp------
egaqrkn------vl--amsfladdpdr-----------aptfeigaveq
geackvndapsi----nsrgtasvgvtrlayldyfhet-sd---rteyfd
rqeltmkmnggkgglkdeigggeagnkgiadlgaik--------qnggke
yaptgkseprellfampnrktl----ietaggtk----qsq--a------
v------dhamntqatsrl--ysv-agvqrgl---kts-ngmvral-vsa
gvlpdaltelvv-atvshp----rdr-vv-ladgvgftk-r-ar------
-----pna-----------------pll------gasesvd-------fa
vt--vpglgp-ndfkqellpedlatvryckesakvhllvtnnwdla-i--
-gkdlsd-avqqsqpanlglgsciylspfggvservsqvywfpplcfvwg
slinchkvrcksqpl----a-pggvakc-------------------rav
knqpk---d--kcvcqp----qgdelliy--carcrggetat-h-hehyk
aiciam-aiskggggcn--h----ghvls
>node13
hardggeffplv------qqgkerlllcavlkafhrtekdfgi---lsql
c--krnpsclmgelglkdgacygtewntaq---------ravrp------
evaqqkn------il--tvsfladapdk-----------astfeigave-
-eackvndapsi----napgtasvgvtrlafvdyfhet-sd---daeyfd
wqelalkmnggkgglkdeigsgeagnk--adlgavk--------qnggke
yaptgkpeprevlfampsrrtl----vetaggtk----qdeaaak-----
vgk----ahametqavrvl--ysv-agaqrgl---kts-ngitral-vss
gclpdaldtlvv-atvsht----rdr-vv-ladg---tk-r-gry-----
----apeag-----------g----pll------gasesvn-------fa
tt--vp--gp-ndfkqellpedlatvryckesakvhllvtnnwdls-i--
-gkdlsh-evqqnqpanlglgnciylspfggvsvrvs-eywfpplcfvwg
slinchkvrcksqpl----a-pggvakc-------------------kav
ksqakirid--scvcqpiggkqgnalliy--carc---gtat-h-nhh--
--ciam-aisksgggcn--h----ghils
>C
har-----fa--------qqrkdkpflcahllifnrt-----i-lglnqa
c---rphasllgslqlkkvvcypvnwseaqtp---gy--tafnt------
kiavk-------------i----dssdkfkfkaqfrggktstfeiaav--
-----------i----dspsspn-avtafayvkyl---------sagyfd
fdrtavkihgtdgeldksvgsgnagnk--qnmgqqh--------pnsgkd
fsps-kpgprevlfalp------filrdt--g--------qaaek-----
vgk----a---ktrvlkal--yks-sgalrgldynhtk-ssvprafqikd
aclsshlktllg-vfacqaek----------dta------r-npy-----
----epsnhaecg-------gfrpyppllpaydmf-----gageaawqfq
ag--vt--gprgkfrqel--ed----i-vkesskaeivnkklwnlp-i--
-gkdfth-daqqhdtsdyelgncidvsp-cggmmivn-efwypplsfvw-
---kcin--cktqal----n--------glnldcteakntsqdqesgkqt
---akiran--tclcaritglqgesf-------rt---gtst-d-dqh--
--a--------sgagcd--y----gqimm
