>node10
dvasiykflnpfea---i------------iqpdscgyiat--gaqa---
--gvsl----gvs--------tkwvfrv--ygarekg--ggpr-fp----
-tea-----fgnpypvadrg---vde--------fsvstpv-apt--prs
lpmwt-fdikaarfgnv------m--aavecsqpne---vythrypgkag
tl---me----hgtd-kvyrggswgelfardadpy--------lpilpky
pgspearqpaeinrkvgsva-s---------vlinv---ndeglilg---
--gieflpnhgapnlmaaaklapqr-ailyeiqgfek----ltlpagvsc
qvtregggcr-vsagg---asvgq-tvgawfgphvsk---ty--------
--yqkpggyftrpyi----psr------kpafasyknvpgfsfalv--hv
lplsg--------igayhimcks------k---gelaa--anvcl-lsev
skvt-gskds-ladtgc----qkfaikly--nwlli---e-pqsvecyar
qklaids--al----tngvpskadg----v--efhaigmvktttark-ig
eggd--kkyrtmavawlmpgkfver--ffhtlvfa-rpagagda--nvrt
---aedkcg-yme-c------pqavgsapqtkgkawplknl-v-------
--------qv------sgfqfrk-leqgpvvfin-qphs---tl--ks
>E
dvadiykflnpfea----------------iepdscgyiat--gaqa---
--gvsl----nvsrmagahklthwsfri--hgarekg--gspr-fp----
----------gnpy-vadrggmpvdesvhhlpanfsgstpl-dpa--trs
lpmwy-fnikaa--gks-dd---vtkpaveitqpke---tythrypgksg
tl---leivskhgtd-kayrggsfgdlfardanty--------lpvipky
pgspearqpaevnkkvgsvv-s---------vlinv---kdsnlieg---
--giqflqnhgapdqmasaklapqw-pilyifrgfek----mtfpadvsc
qvtregggcr-vsngg---asvgqltigvrfgphvsk---ty--------
--yqkpggtytr-------plr------kpafasyrnvkgfsfalv--hv
lplsg--------igafhimcks------kkgvgdlaa--aavclfvsev
skvt-gskss-iadtgcdkscqkfnikly--nwsli---a-pqsvdcfar
q--------am----tngvptraeg----v--efhtigmiktttark-ig
aggv--kkyrn-tvaw---gkfver--ffhtfvst-rpa--gda--nvrt
---addkcg-yle-c------pqavgsakktkghawplkdl-v-------
--------ql------nafqfrk-meqapvalvn-qphs---tl--ks
>node3
drqseykflss--------r---rtnddngsqpdtctyist--gaqn---
--avsl----evg--------tkskfrm---gvrdkn--gapr-lp----
-tni-----fgtpypvaarg---vgs--------y-----v-vne--prs
npvwthfqdtavrfgnvn---ngl--aa-------------tqkiaadgk
pf---ke----yg-n-kvylfgkwgdl-praaepy--------ltvvpry
phteagpqagqisrkvk-vtgn---------i---v---kddglvlg---
--aldf-pengapylvgtsklapep-lvrfql--f------vaippavac
qikkqgggck-vsaag-dkyevvd-avgkw-----sh---ayekkrlawk
rafdnpggyfnepfiyala-----------qltsyktvndyslelvr---
--lgg--------taayhimskf------k---telgd--tgvc-----v
skvvkgsneh-ladtgc--------yklypknhliy---dpadai-c---
qrlviqc--al----tagvrgr-------a--eytgv-----------ys
kgggtpekyktpalawdms-k---r--ff-avvfa-rp--atda--dvvv
---andkcgfytd-c------pdeegnapgtrgkgwplgtv-v-------
--------fvly--caw-fqyrk-vedgplifip-qa--ptd----kp
>B
erqseyktvss--------r---rsnqddgeqpetctfist--gaak---
--avsl----evg--------skskfrm---gtrdkn--gatr-lp----
-tnv-----fg--y--aakg---vgs--------y-----v-vne--ahs
npvwshfqdtavrfgtvn--ynvl--at-------------tqmitadgk
pfeetke----yg-i-kmyl---wgdl-qraaepy--------ltvvpry
phtepgpqagqvsrkvk-vtgn---------i---vtkrkddglvlg---
--aldf-pqngapylvgtsklapep-lvrfql--f------vaiepavsc
qitkqgggsk-vaaas-nkyevvd-svgkw-----sp---ayeksrlawk
rapdnpggyfndpfiyala-----------qltgymtindfslelvr---
--lgg--------tn---lkskf------k---telgd--tgvc-----v
akvvkgpheh-ladtgc--------fklypkdhliysshdpaagi-c---
qrlviqc--al----tagvrgr-------a--eyadv-----------ys
kdggtpnkykvpvlawnms-k---r--ff-avvfa-rs--atda--dvvv
---ardksgfytd-c------pdeedkppgtrgkvwplftv-v-------
--------fvly--caw-fqyrh-vddgplvfip-qa--pts----kp
>G
dlasiygfltvfea---i------------lnqdscgy------vsv---
--yvgl----g-a--------akrvfrlygygtfdeg--ggprvfpgpnk
v-------------pvaeks---pde--------y-----v-ak---pds
lpmwt-fsvkaarfgdv------m--sgvecs------lvftqrytgknv
rl---md----hg-ddkvyergpwgevlpreaspy--------laivpry
patpearpvatinrkvssvm-e---------v---v---ndnslala---
--giefq--ggvpnlmdagklahdr-silyev--f----------esvsc
hitregggcr-vsaggtdhysagq-tvgaw-----sk---tf--------
--ygkpggyftnpyivgvssar------kpe-----nvngfsfal-----
---sg--------tstyhimcky------e---selaa--tivcl-laev
tkvt-nttek-laetgc----dlfavkll--kw-------------c---
-----dc--al----t--------------------igmv-------sva
eggd--hkyrtmtpawllpgkfverlkyfptvafa-kd--agea--dgky
tmpaedqtgfyaa-c------pqalvsdpdsr---wpmknl-patkehne
lhlhktrtfv------sdfqfdk-vldgpvifik-q------------
>C
dkdsdykfssmfqcrvdlrr---kanddnglqpdtcpvistlggah----
--pvtllakeevd--------tknkfrl---gvnkrgviggpr-vp----
-eevesvkqfgaaypiaarg---dge--------y-----i-vke--prg
npvwt-feitaarfadvn---vgl--ag-------------iqrlsakgg
ti---me----yg-k-kgyqfgkwgal-kstaapy--------vavvpry
prtqqtrestqvgrnvktttgk---------v---v---kddvlvlg---
--glnf-phnga--lvdtaklgegpksvmfql--f--taksipl--atsc
qvkkqgggckrvsagg-dlyevve-avsnw-----rh---ayerkklv--
--ftkpggnfsnpfiyglapargy---fapqfhsykvvnayslalvr---
--lsg--------satysimtkl------k---gelgs--tkvc---aev
tmeinnnkah-laetgc--------gelf--nhlii---npaddv-c---
qklciqc--alkdfetggirtr-------slna--ei-----------ys
kggstpekykqtklalkls-kfvdk--ff-tvvfkarp--aaeanpgvkv
---gnkmcgfyvc-c------pqgeqekpgtrgkgwplgkv-v-------
--------fviyqgcvw-yqyrg-vee-plifiaiqa--plagl--h-
>node14
dvasiykflspfea---i------------lqpdscgyiat--gaql---
--gvsl----gva--------tkrvfrl--ygvrekg--ggpr-fp----
-tda-----fgnpypvadrg---vde--------y-----v-akt--prs
lpmwt-feikaarfgdv------m--agiecsepte---vytqrypgkag
tl---me----hg-d-kvyqggnwgeilprdadpy--------laivpry
pgspearqpaeinrkvssvt-s---------v---v---ndeglvlg---
--gieflpnngapnlmdaaklapdr-ailyei--fsk----lalpanvsc
qitregggcr-vsagg-dhysvgq-tvgaw-----sk---ty--------
--fpkpggyftnpyivgmgpar------kpefasyknvngfsfalv--hm
--lsg--------tgayhimcks------k---gelaa--tnvcl-lsev
skvt-gskds-ladtgc----ekfavkly--nwlli---d-aqsv-c---
qrlaidc--al----thgvrsk-------v--eftgigmv-------gig
eggd--qkyrtmavawlmpgkfver--ffhtlvfa-rp--agda--nvrt
---aedkcgfyma-c------pqalgsapetrgkawplknl-v-------
--------fv------sgfqfrk-veegpvifit-qp-----tl--ks
>node6
dkdseykfsstfqcrieirr---kanddnglqpdtcsvistldgah----
--pvsl----evd--------tkskfrm---gvnkrgiiggpr-lp----
-adveevkqfgtpypiaarg---vge--------y-----v-vke--prs
npvwt-fqitaarfgdvn---vgl--ag-------------iqrlsakag
tl---me----yg-k-kvyqfgkwgal-artaapy--------ltvvpry
phtqesrqstqvgrkvktatgk---------i---v---kddvlvlg---
--gldf-phnga--lvdtaklvpepksvmfql--f--taksial--gvsc
qvkkhgggck-vsagg-dhyevve-avtnw-----rh---ayekkrlv--
--fakpggnfndpfiyglapargy---fgpqfasykvvngyslalvr---
--lsg--------tatyhimakf------k---gelgt--tkvc---aev
tmevnnnkdh-laetgc--------gelf--nhlii---dpadav-c---
qklciqc--alddfetsgirsr-------plneyvgi-----------ys
kggstpekyktpklawkms-kfvdr--ff-tvvfaarp--aaea--svkv
---andkcgfyvs-c------pqdeqdspgtrgkgwplgkv-v-------
--------fviyrgcvw-fqyrk-veegplifit-qs--pfagl--h-
>node13
dvasiygfltpfea---i------------lnqdscgyiat--gaql---
--svgl----g-a--------akrvfrlygygvfeeg--ggprvfp----
-tdv-----fg---piaqrs---pde--------y-----v-akt--pns
lpmwt-fsikaarfgdv------m--sgiecseptdvsnvytqrytgkag
tl---me----hg-d-kvyeqgswgevlpreaspy--------laivpry
pgspearhpadinrkvssvt-s---------v---v---ndnplvlg---
--giefl--ggvpnlmdagklapnr-ailyei--f----------esvsc
qitregggcr-vsagg-dhysagq-tvgaw-----sk---ty--------
--fampggyftnpyivgvasar------kpe-----nvngfsfalv--hm
--lsg--------tsayhimcks------k---gelaa--tivcl-lsev
tkvt-ntkes-ladtgc----elfavkll--kw-------------c---
-----dc--al----t--------------------igmv-------gia
eggd--qkyrtmtpawlmpgkfver--ffhtlafa-kd--agda--nvky
---aedqagfyma-c------pqalvsapdargkawpmknl-p-------
--------fv------sgfqfdk-vedgpvifik-qp-----tl--ks
>node7
dkaseykflssfqc---vrr---randdnglqpdtctyist--gaqn---
--avsl----evd--------tkskfrm---gvrkkg--gapr-lp----
-tdv-----fgtpypiaarg---vge--------y-----v-vke--prs
npvwt-fqitaarfgdvn---ngl--ag-------------tqrisakgg
tl---me----yg-n-kvyqfgkwgdl-prtadpy--------ltvvpry
phteesrqaaeisrkvksvtgn---------i---v---kedglvlg---
--gldf-pqngapylvdtaklvpep-lvmfql--f------valppgvsc
qikkqgggck-vsagg-dhyevae-avgnw-----sh---ayekkrlvwq
rafakpggyfndpfiyglapar------kpqftsyktvngyslalvr---
--lsg--------taayhimskf------k---gelgt--tkvc---aev
skvvngskdh-ladtgc--------vkly--nhlii---dpadav-c---
qrlviqc--al----tggvrsr-------a--eytgi-----------ys
kgggtpekyktpalawkms-kfvdr--ff-tvvfa-rp--aada--nvrv
---andkcgfyva-c------pqdegnspgtrgkgwplgtv-v-------
--------fvlyrgcaw-fqyrk-veegpaifit-qa--pidtl--kp
>node15
dkasefkflspfec---v------------lqpdscgyist--gaqn---
--gvsl----gva--------tkrkfrl---gvrkkg--gapr-fp----
-tda-----ygtpypiakrg---vge--------y-----v-akq--prs
lpmwt-feikaarfgdvn---hgl--ag--cseptq---vytqrisakgg
tl---me----hg-d-kvyqggkwgdi-prdadpy--------lavvpry
phsdearqpaeisrkvssvtgn---------i---v---keeglvlg---
--gleflpnngapnlvdasklvper-avlfqi--fsk----valppnvsc
qikregggcr-vaagg-dhyevgq-avgaw-----sk---syekkhlvwh
rafpkpggyftdpyiygmapar------kpefasyksvngfsfalvrdhm
--lsg--------taayhimcks------k---gelaa--tkvcl-msev
skvtngskds-ladtgc----e--avkly--nwlli---dpaqsv-c---
qrltinc--al----tggvrsr-------a--eftgigmv-------gys
kggg--qkyrtmalawkms-kfvdr--ff-tlvfa-rp--agda--nvrt
---agdkcgfyva-c------pqdlgsspetrgkgwplktv-v-------
--------fvlyrgcasgfqyrk-veegpaifit-qa-----tl--kp
>D
dkdseykfastfqcrieikrecskdnddagfspdtcsavstldgaq----
--pvgl----evd--------tkskfrm---gvnkrgiigapr-lp----
-ae--evkqfgvpypivarg---sge--------y-----v-vkd--prg
nsvw--fqisptrfgdvn---vgl--ag-------------iqrlsakag
gm---me----yg-k-kvyqfgdwgal-trtaapy--------ltvisry
phtqesresthvgrsvktstgkiielsksgki---i---kgnvlvlg---
--didf-pnngp--lvdtaklspepksvmfql--f--tsksfal--gvsc
qvkkeggack-vstgg-dpyevve-aianw-----rhclkaeekkwlv--
--lakpggafnapfaygtapargygpdfgpqfasykivngypaalar---
--lsg--------paty------------q---galgt--akvc---aev
tmeanentehmlassgc--------gelf--shlvi---npaddg-v---
ekmciecdcalddfetsgyrar-------pnteylti-----------ys
kggstpeky------------fvdr--ff-tvvfaarp--aaea--svkv
---andkcgfyvs-c------pqdeqdspgtrgkgwplgkv-v-------
--------fviyrdcvw-fqyrk-veegplifin-es--tlanl--k-
>A
drhaeykflsk--------r---randsngtqnatctyist--daqnsci
tgavsl----evd--------tnnkfrm---gtrdkn--gaar-lp----
-tni-----fgtpypmaakg---vgs--------y-----v-vna--pqs
spvwthfqdtavrfgn-n---dgl--aa-------------tqriaqngk
kf---ke----yg-d-riylygkwgdl-prnaepy--------ltvvpry
pyteagaqagqiiravk-vtgn---------r---e---pdgglvlgegl
tsaldf-penganylvgtskqapep-lvrfel--f------vaippavac
efkkqgggck-vgaag-dkievvn-avgkw-----st---ayekarla-k
rafenpgayfdepfiyala-----------ql-syktvndyklelvh---
--lgg--------taayhvmsks------k---telgd--tgvc-----v
skvvkgnnen-lsdtgi--------yalvpknhliy---dhadqi-c---
qkwviec--al----tagvrgr---dseka--eytgv-----------ys
kgggtphkyktpaltwdms-k---r--ff-gkvft-rh--atea--evvv
---andkcgfyadrc------pdeegnargsrgkgwplgtv-v-------
--------fvly--caw-fayrk-vtdgplifip------------kp
>H
dvgtiygfltpyqa---i------------lnqdscgyiat--gaql---
--svgl----g-a--------akrvyrlyaygvtdeg--ggprvfp----
-kdv-----fg---aleqrs---qde--------y-----vapktdslns
lpmwt-fsikaarlgnt------m--sgiecseptdvsnvytqrytgkad
sl---me----hg-d-kvfeqgswgevltralspy--------laivrry
pksaesryaaainrkvssvt-g---------v---t---sddklvlg---
--gikfl--g--phlmdagklap------yen--f----------esvpc
kiaregggcr-vssgg-dhytagk-tvgaw-----tk---ty--------
--ylmpgayfvnpyivgpgsar------kpe-----kvtgfsfali--ht
--ltgrdpeqpehtstyfimcksfhglkkk---gdlaa--tivcl-lgev
tkva-nsk----tdtsc----elfavkll--kw-------------c---
-----dc--al----t--------------------igmv-------gfa
aggn--esyrt-----impgkfver--ffhtldfa-k----vdg--tiky
---aenhldfyma-cwgggnaphallsapdargkawpmknl-p-------
--------fv------vgfqfdkgvedgpvifik-qp-----tlglks
>F
dvgsvykflnpfdd---v------------vqfdscaylpt--g------
--flsl----gis--------tkwvlri--yaarekg----pr-fp----
-se-----------paadrg---vde--------fsiatpv-apt--arn
ipmwt-feikaarfghv------m--aapncskpne---vythrypgkag
sl---ie----hgtd-----sgswgelifrsadtykpqvesqslpiatkf
pgspdareaaeinrkvg----g---------vlvnv---kdeglilg---
--gieflpnhgapnpmaaaklaaqr-ai-----sfek----ltlpqgvsc
----egggcn-vaagg---asvgq-yvgewyapqvsk---ay--------
--yeknggyytrpyi----pnr------kpafptyknvpgfpfslv--pv
lpssg--------igayhilcks------k---gelaasqanvcl-lsev
skvt-gtkds-ladtgc----skftikly--kwlli---e-prsvecyar
qklaids--al----tngvpskneg----v--efhaigrvktttark-ig
eggd--kkyrtkavswlmpgkfver--ffhtlvla-spagagda--nvrt
---aedkcg-yme-c------pqpvgtapqtkgrsw--knlvv-------
--------qv------ssfhfkk-leqgevvfln-qphn---tl--ka
