>node14
e---adggsg--qfq-d---eerwkskfqnlqsda-dlnckniv--ncvt
iq-npaaaavh--dhvh----arkkp--avy--tk-----cfdaikgava
ql---adfkcly-rlgfsgasdiksgpy--f-yk-ql--------lhayr
----avck---cnhpc-l-gmtah--pttgkyvnwaks-kt-khffkat-
-s--igacrl---likv-h-fastvstiseh---------------adtp
t---nta-irvlavfsks-y--------i-p----llk-p-----egska
flit----sf----gngkq-lkigqrym-----agppl----------nk
gssssedv-----fy----ledklrf--gaktmrv--alsvnk----lqg
--ltvcnglccl---g---qdklagvenggkfwvddclskkkdnslaisi
tqntklpk-g---pn-----------gdvvreglcieltelhq-------
-kshlin-nhnki-pe---atikln--tgrtql-slcknsanad---yfq
dg------------gqr--dp-----skwsr-l-lpvdyvgnpttikadv
vtlnkpeat-q-----avkktn-gflg-egv---------------gapv
------kimftcqeakkrwclkvhh----r--------------vsnelc
-lgfcfcfgfp-gyfkffyptilrnlgpaqce----haq-----------
-vsa--cslpvmfasvvgvdr---acvshqcdcyc-----htg
>B
e---ceggig--qfqnr---arw--tayti------glncksiv--scvt
ea-teagqatniaqhv-------nmppeavy--vk-----cfdaikgsva
qa----gfkcif------gaststtgpf--l-yklqr--------lqaar
----avcs---cnrdcfl-----hsnpdtglyinwyks-ds-shya----
-----gtprl---pikvdfhysggihsviasdpregarspytdervedvs
t---ntavaslssvlpdk-fk---sdgtivgv---lltlp-----digms
flts----sf----ahgksilkvp-----------ppi----------tk
dtdssgiv-----ry----aqnktafsrpyktlqvngqlsdnk----mea
--ltscsglccl---n---kdrltgieasg----aesmpk----ql----
aedsklgk-----------ekipdepkdvlstglcielnalhe-------
-gshlis-nnnkg-he---akvqle--sgrtel-ilclsraknd---yfe
pgs--gpgscrn-edqs--dp-----plwgg-l-aavdfvghnptlvnev
vtlvk-evpeq-----tvkn-----ld-qgiykkathdysfenpnvgqpl
ghggkqpamytcsqalsksclkahq----s--------------ge----
rmdfcfc----diy-kffy-----eleagqcq----rghgfhlsfttptp
fvscvlcnipvkga-vvgidr---dclsehvecyc-----hts
>node3
e---cdggig--qfqkk---arwwktayqi------glnckniv--scvt
ea-teagqatn--qhvh----prnkpaeavy--vk-----cfdaikgsva
qa----gfkcif------gasttttgpf--l-yklqr--------lqaar
----avcs---cnrdcfl-----h--pdtglyinwyks-ds-ghfa----
-----gtcrl---pvkvdhhysggihsvias---------------ddvs
t---ntavasvssvlpdk-yk---vdgtivgv---lltlp-----dvgms
flts----sf----shgkqilkvp-----------ppi----------tk
gtdssgev-----iy----fqdktafsrayktlqv--slsvnk----mqg
--ltacdglccl---t---kdrltgiedsg----aesmpk----slnvvi
aqdtklakkt---ptepkre------kdvlseglciqlkalhe-------
-gshlin-nnnki-he---atvqld--sgrtel-ilcqssaknd---yfe
pgl--gagscrn-edqr--dp-----plwgg-l-vpvdfvghnptlvnev
vtlvk-eapeq-----tvkntn-nfld-egiykkathdysfetslvgqpl
------kimytchqalkkwclkahh----r--------------gd----
rmnfcfc----dyyfkffy-----eleagqce----hsh-----------
-vas--cnipvmga-vvgidr---aclseqvecyc-----hts
>node6
e---cdggid--lfq-d---arwwksayqg------alnckhml--sclt
va-eeaaqaah--qhvh----prkkpaeaiy--v------cydgikgsia
qv----gfkclygr--fagastitsgpf-vf-yklqr--------pqatr
----avck---cnkdcfl-----h--pdtslyvnwakg-dk-phlfkqt-
-s--mgtcrl---kvkveh-yspgvhsaias---------------sdtp
t---nvapmivaavlphe-t--------lvgvdasllelp-----egpka
flts----sl----shgkqvlkva-----------pp-----------tk
gtvssgeg-----vy----fgdstafsrgyktlkv--slavnk----mqg
--qtvcnglccl---a---kdslagvegnn----dds-pk----glavvi
aqdtklpkksvllpt-----------kevlreglchelkelnq-------
-gahlid-nnnkl-he---atvqln--sertql-ilcqstanad---yle
pgl--gegscvkveddr--sp-----alwsr-l-lpvdyvgrpptisndv
vtmvk-aapeq-----avkktn-nflg-egifkkatyeysletnl-----
------------hqacrkwclkahh----q--------------gp----
rlnvcfc-------frfff-----eiqagqce----hlr-----------
-vas--cnipvmgasvvgier---aclsnqcdcyc-----htg
>C
e---cdggve--lfd-d---trwwkssyqg------a----hml--sclt
va-eegaqaah--qnvh----prkkpaevif--g------cydgingsva
ev----gfkclfgr--fagastvtsgpfg-f-ykqqr--------pqask
----aisk---cnkdcfl-----h--patslyvswakn-dk-phlfkqt-
----mgtcri---kvkveh-yppgvhsaias---------------sdtp
nievnvsplivaailphp-t--------ivgvdasllelp-----egpks
flts----sl----shgkqvlk-s-----------pp-----------tk
gvvksgesvtdgivy----fggstafsrgyktlka--slavsk----mqg
nkqvvcnglccl---a---kdslatvegnn----des-pk----glevvi
aentkppkkrvllpk-----------kevlkdgachdlkelnq-------
-gahlld-ynskl-hq---gtiqls--sertql-rlcqptdead---kle
pgl--gehscvkvdddr--sp-----alws----------------anei
vtmik-aapeqvktqqevkktn-kaltmegifkkatheyslpvnl-----
------------nqacrkwclkahh----q--------------gp----
klnvcfc-------fifff-----evqagqcenkclhlr-----------
-vas--cnvsvlgssvvgier---aclsndcecyc-----hsg
>F
d---aesggg--qfq-n---eqrwkgmyqnlknda-dlncnhkv--ncat
id-npvgvsvh--dqvhtnararkkp--avn--tk-----cfdaikgtva
ptwgva-fkcly-rlgyskecsik-gpy--f-kk-qlgwvnmvmylhawr
----ahckvldvnhpc-l-gmtvh--pttvkyttwakn-kt-khfykst-
-s--idacna--------h-facvvstiseh---------------adtp
t---nta-nrvlpvfpkn-y--------i-p----ilk-pteteyegska
flitndtgta----gggmq-lkigvrym-----agpai----------kt
gspss--i-----fy----lddalrl--ssntgqv--aleinkrggglqg
--lkvcnglccl---g---setlagiekggkywtddclsskkkdsleidi
tqnvklpk-g---pa-----------gdvtdpglcieltnlhe-------
-kshlit-nhkki-pe---asiklnvstgrt---------anqqtsgyfq
ds------------gakcaeq-----skwsk-l-kavdfvanpttikvep
iklakptet-q-----pvkkvn-gfl--egv---------------gapp
------kvmft--------cldthh----r--------aavsqkvsdklc
-igfcfcfsfp-gyykftiptal----paqcd----hnq-----------
-isa--ctlavkfasvvhvdr---acvcqecdcsc-----yag
>H
s---aeggag--qfq-d---eekdkakfqnlqqda-dlscknyvasn--t
ae-lpapadqh--drch----erkkp--aiylatkkrpsdcfgrikaava
ql---adfkylp-klgyhaasdikggpy--f-yk-ql--------lhvyr
----avcn---cph---l-gmgaq--pnt------aka-ktpkl------
---------------------vstvstiveh---------------aedp
d---nta-irhlaifnkt-y--------k-p----llk-p-----egskq
flit----gf----gagkq-lklgqryl-----agpplaanm----pank
gssstedv-----ff----ledklaf--gvk-----------------qg
--ltvcygecaltatgnthqdklngadnggnfwvddclfngknpslavev
sqkaklp------pn-----------gdvereglci--ndinq-------
-kdhfip-ahnki-de---atikln--sgrkqlksvckhsadae---yfq
dg------------gfr--kp-----akwfr-l-y----cgnpttrqs-a
ttvnkp-at-q-----aientnfgflg-dgv---------------gepv
------kamficqeak----lkvle----r--------------vgtelc
-lgfcl------tfakfyypsilrnldptqce----hvq-----------
-vya--cslsvlfasgvgvdqfgepcaanqcdcycqhgtcht-
>G
k---aepgag--qfq-d---eekdtskfqnlqqeagdl--kncggs---a
tevlpapaaqh--dryh----avgkp--aiy--tk-----cfssvkamvs
dl---adykcly-glgysgatdfkngpy--fslk-ql--------lhvyr
incksvcn---cphec-lsgmtaq--pat------aks-rtkklf-----
--------------vkv-q-fgktvstiveh---------------agtp
n---nta-irllaiasks-y--------k-p----llk-p-----egske
ylvt----gfkgksgdgkr-lrlghrylqqaslagpplpphkyekqpask
gasrtedg-----ay----lednerf--gtk-----------------qn
--ltgchgl--------------egvenggkfwveaclskgkggpltvhv
tqntqlp------pn-----------gtvereglcvklttinq-------
-kshlih-nhski-de---alikln--kgrkql-svcklsaetd---yfq
dg------------ghr--npwdeksskwfrgl-l----vnnpttira-a
ttltkp-pt-q-----avdken-gflg-dgv---------------gapv
------kimfscqearkrwcirila----r--------------vatelc
-lgfcf------gyaeifyptilralgpaqcd----haq-----------
-vya--cclpvmfasavgvdqfgepctahqcdcacqhgrtht-
>node10
d---aeggsg--qfq-n---eqrwkgkyqnlksda-dlncknqv--ncat
id-npaavsvh--dhvhseararkkp--avy--tk-----cfdaikgava
rlwgva-fkcly-rlgyskasqiksgpy--f-nk-qlfwvnmvmylhayr
----avckvldcnhpc-l-gmtvh--pttvkyvnwakn-kt-khffkat-
-s--inacsa---likv-h-facvvstiseh---------------adtp
t---nta-nrvlpvfpkn-y--------i-p----llk-p-----egska
flitsdsgsl----gggkq-lkigqrym-----agppv----------nt
gssss--i-----fy----lddklrl--gantmqv--alevnk----lqg
--ltvcnglccl---g---pdklagvenggkfwaddclsskkkdsleiei
tqntklpk-g---pa-----------gdvtspglcieltelhe-------
-kshlin-nhkki-pe---asiklnvstgrtel-slckdsanhdtsgyfq
dg------------gqrcrdq-----skwsk-l-kpvdfvgnpttiktdp
iklakptat-q-----pvkktn-gfl--egv---------------gapv
------kvmft--------clkthh----r--------gavnmkvsdklc
-lgfcfcfgfp-gyykftiptil----psqce----haq-----------
-isa--cslpvmfasvvhvdr---acvshecdcsc-----htg
>D
e---cdggid--ffl-e---arwwksayqg------alsskhml--sclt
va-tgagqsah--qhvh----prkkpaqaiy--v------cydsikgnia
qv----gfkclygr--fadvsqitsgpf-li-ynlqr--------pqptr
----aick---ckkdcfl-----q--pdtrlyvnwardamk-hhlikqt-
-dqgmgtcrl---kikveq-ykpgvhna--------------------tq
t---nvapmivaevlphd-t--------lvgvdaslvelp-----egska
flts----sl----thgkpvlqva-----------tp-----------sk
etvgsgeg-----ingshffgdstafsrgyktlkv--klavnk----mq-
------nglccl---a---kdnlggveghd----tda-pk----glavvi
aqdtklpkatvlmat-----------kevlsdglchelkernl-------
-ggdlin-nnskl-he---atvhln--sertqi-ilcqqtgnad---yla
pgl--gesscvmvedd-----------lwsr-ldlpvdfpvrpptisndv
vamik-asdeq-----aakktd-nflg-egifknttyeygletkl-----
------------qqacrkwcvkahhgwplq--------------gg----
rlnvcfc-------frfff-----eihagqce----hlr-----------
-v----clipvkgasvvgier---kclsnqcdcyc-----htg
>node15
e---cdggig--qfq-d---eerwkaayqslqsda-alnckniv--ncvt
aa-naaatavh--ehvh----arkkpiegiy--tk-----cfdaikgava
qv---adfkcly-r--fsgastitsgpy--f-yk-ql--------lhayr
----avck---cnrpcyl-----h--pttglyvnwaks-kt-rhffkat-
-s--vgtcrl---pikveh-ysspvssvvat---------------adtp
t---ntapirvvavlpne-y--------v-g----llt-p-----egsks
flit----sf----gngkq-lkvgqrym-----asppl----------kk
gtnssedv-----fy----fedktafsrgaktmkv--slsvnk----lqg
--ltecnglccl---g---kdklagvedsg----ddslsk----slavsi
aqntklpk-s---pt-----------gdvlreglciqltelhq-------
-gahlin-nhnki-he---atvkln--tgrtql-vlcqssanad---yfq
pg------------gqr--dp-----alwgk-l-lpvdyvgnpptitsdv
vtlnk-eapqq-----avkktn-gflg-egvfkksth-----tflvgspv
------kimftcheakkkwclkvhh----r--------------ve----
hlgfcfc-----gyfkffy-----dleaaqce----haq-----------
-vas--cnvpvmfasvvgidr---acvsnqcdcyc-----htg
>A
e---cdgpikpiqfqkk---arwwktayki------glnckniv--scit
ea-teagqatn--qhvh----pdkkpaqavy--vk-----cfdaikssva
qa----gfkcif------gatttttgpf--l-yklqr--------lqtar
----avcs---cnrdcfl-----a--sntglyinwyks-ds-ghfa----
-----gtcrl---pvkvdhrydggdhsvias---------------ddvs
t---ntgvgsvstvlpdknykqmtlddtivdv---lltlp-----dvgrg
fmtc----------shgkqilkvp-----------ppi----------tk
gtdssgev-----lf----fqnntafsstyndlqv--slsvkk----mqg
--ltacdglcci---s---kdrltgiedsg----aenmpk----slnvvi
tq---lakks---ptehsre------nnvlqeglciqlkalhe-------
-gvhlinlsnnki-nyvcnatvqld--sghkel-tlcqtsakke---yfe
pglltaaqgcrn-edqr--dt-----plwgg-l-vpvdyvsenptlvngv
ltlvk-qapeq-----tvknan-nfvd-agvykngtrdytfetslvgrpl
------kflytchqelkkwclnahh----r--------------gd----
rmnfcfs----aysfkffy-----eleagqce----ysh-----------
-cas--cnitvmga-vvgvdr---aclaeqvecyc-----hts
>node7
e---cdggig--qfq-d---arwwksayqs------alnckniv--scvt
va-neaaqath--qhvh----prkkpaeaiy--vk-----cydaikgava
qv----gfkclyqr--fagastitsgpf--f-yklqr--------lqavr
----avck---cnrdcfl-----h--pdtglyvnwaks-dt-phffkqt-
-s--igtcrl---pikveh-yssgvhsvvas---------------sdtp
t---ntapisvaavlpne-y--------vvgv---lltlp-----egpka
flss----sf----shgkqilkva-----------ppl----------tk
gtdssgev-----iy----fedktafsrgyktlkv--slsvnk----mqg
--ltvcnglccl---a---kdklagvedsg----deslpk----slavvi
aqdtklpkks---pt-----------kevlreglciqlkelhq-------
-gahlin-nnnkl-he---atvqln--sgrtql-vlcqssanad---yfe
pgl--gegsctn-edqr--np-----alwgr-l-lpvdfvgnpptitndv
vtmvk-eapeq-----avkktn-nflg-egifkkatheysfetnlvgqpl
------kimftchqaakkwclkahh----r--------------ge----
rlnfcfc-----fyfkffy-----eleagqce----hah-----------
-vas--cnipvmgasvvgidr---aclsnqcdcyc-----htg
>E
niitgeggsg--qfq-nhtreqrwrgkyqglksda-dlkcknqv--ncal
vd-nptavslh--dhvgnesraqkkp--avy--tk-----cfdaikgtve
rlwgvp-fkcly-rlgyskasqiktgpy--f-kk-qafwtnmvmyihgyr
----gvckviecnhpc-l-gmtvh--pitlkyinwass-kn-khffkata
it-----cpaaerlikd-h-facvvstissh---------------vdtp
a---sta-nrvlpifppk-h--------m-p----llk-p-----egska
flitsdppse----gagkq-lkigqrym--------pv----------nt
gstks--i-----fy----lddklkl--ganimqv--alevnk----vqg
--lnvcptlccl---g---pdklagvenggkfwaddclsskkkdsleiei
tantklpd-g---ss-----------sdvtapglcielmelhestakvgd
akthltn-nhkkitke---rsakrnvstgrtel-slckdsanhda-----
dg------------gqrcrde-----pkwsk-l-rpvdfvgnptsiktdp
iklarptat-h-----paaktn-gfl--ngv---------------gdpv
------qvmft--------clkthh----rmkyigrgvgavnrklsdklc
-lgfcfcfgfp-gyydftipail----psqce----haq-----------
-isa--cslpvmflsavhvdi---gcvshecdcsv-----htg
>node13
k---aeggag--qfq-d---eekdkakfqnlqqda-dlsckncvgsn--t
ae-lpapaaqh--dryh----arkkp--aiy--tk-----cfgsikaava
ql---adfkcly-rlgysgasdikngpy--f-yk-ql--------lhvyr
----avcn---cphec-l-gmtaq--ptt------aks-ktpklf-----
--------------vkv-q-fastvstiveh---------------adtp
n---nta-irllaifsks-y--------k-p----llk-p-----egske
flit----gf----gdgkq-lklgqryl-----agpplaank----pank
gssstedv-----fy----ledklrf--gak-----------------qg
--ltvchglcaltatg---qdklqgvenggnfwvddclskgkgnslsvhv
tqntklp------pn-----------gdvereglcikltdinq-------
-kshlin-nhnki-de---atikln--sgrkql-svcknsaead---yfq
dg------------ghr--np-----skwfr-l-l----vgnpttiqa-a
ttlnkp-at-q-----avektn-gflg-dgv---------------gapv
------kimftcqeakkrwclrvlq----r--------------vatelc
-lgfcf------gyakffyptilrnlgpaqce----haq-----------
-vya--cslpvmfasvvgvdqfgepcashqcdcycqhgtcht-
