>E
hdg-------spdir-mkatvlrtrkcy-mfqfpsvrtryl-ktsvvycd
rdqs-ffisgnqqlsggaitf-pltet-------------hpitkmpfkw
nlpdsrngdav----gsgnlkitvsiafqleshm----stl---vtvtka
nqavld-aadlstsck-f-----pgesldmvgdsqsdhk--sknraskry
alsltv-t----tcyaraap---vnyskvyqggvhdmileercg-lgpey
g------------vev----dakdshqsnkf-------------------
-rvdkqsst----kysdlipmfgipgigpdpketafhll----v-tmg--
------kfldsndlehl-rasgg--gstg---------caldqtkklvlr
a-------iacpf----kgya------kgqfnregtkkqyplysk--gsy
aaatfggcamvqkg--------------vkrt-------ilvdmp-vf--
yakcpnkaeldata-gekapglmeepc--tpkqika-------lptqnrt
sgylnncekq----pqkpsgls-dy----tgte------ck----hk-fp
--vqplpsvts-------vks----------lpccrng-kfr-------g
qaq-------lsdkltstaapkkgallqq---vanewv-----------n
gadml
>node10
hdg-------apdir-mdamvlrtrkcy-mfklssvktkylnktsvvycn
rdqs-f--sgnqqlsggaitf-pltet-------------epitkmpskw
nlpdsrngdav----gtgnlqitvfiafqlenhm----stl---vtvtkg
dqavle-annlstsck-f-----pgegldmvgdaqsdht--sknraskpy
slslsv-t----tcyaraap---vnyrkvyqggvld-ileercg-lgtey
g--q---------vev----dakdshqslkf-------------------
-radkqsst----nysdlipmlgipeigptpkettfhll----v-tmg--
------kfldsndlehl-tptgg--gstg---------cale---klvlr
a-------vtcqf----kgya------kgqfnrestkkqyplysk--gsy
aaatfpgcvmvqkg--------------vlrt-------ilvdmp-vfha
yakcpnkaelgata-gekapglmielc--apkqika-------lesqnrt
sgylnncekq----pqrpsgls-df----tgte------ck----hk-fp
--vqplpstts-------vks----------lpccrng-kfr-------g
qap-------lsdkltsdaapkkgallqe---vindwv-----------n
gadml
>G
tdg-------spddr-mekmvlrtrkcy-afknanvkthylnsr--vych
gdks-f--aqhqensggalafdplvet-----yvklrpemepitklptrw
rlpdarnddainriagsgklqisvflispltndv----vtv---------
dmsveh-ndhlsnpck-f-----ageghhmvgdshpeqt--s-------y
kdalsv-t----acfaraprvvla---ksyqggilk-cleekig-mgte-
--------------------vakevhvtlkf-------------------
-rtdkpsasgivphfsrlvpmse--eigdtp-easfhq-fs--sptvs--
------kfl-----------------ttg---------cave---k-alr
ed------vtpqfavniqgfa------tgrfqvdeqaspyplysk--gsy
aatasgdcvvvkgaglgsnanlpad---vvns-------il-----vfna
yakcqnkaelgdta-sekpcgltyyf--katdqvsk-------ldtskrs
kgymdnsein----prkpg--s-df----aa-qgdlrnack----hk-vs
--vqplksvss-------tksdkh-----yglpccang-rfr-------n
dstilrslsglvnklttakskknnalvqk---viddwv-----------t
qaeml
>F
hdg-------apdir-mdamtlctrk---mfglktvktkylnktsvvfcn
rdqs-f---gnqqlsgggitf-pltet-------------epadkipsrw
alpdsrngdai----gtgnlqitmfiafqlenhm----atl---vtvakd
dqalle-sndmttsck-f-----pgegldmagdaqsdht--tknraskpy
klslcv-t----tcyaraap---dnyrkvyqegvle-ilqekcg-lgndy
g--q---------pevalaidsnds-qslkf-------------------
-lsdkqast----kygdlvpmlgikaigptpkettf-ll----v-tig--
------kfldsndldhl-tptga--gstg---------cple---ksvlr
m-------vtcef----kgya------kgqfthestkkqyplyvk--gsy
avasfpgcvvvqkg--------------slrn-------ilidmp-vfha
lakcpniaalgata-gdkapglmielc--apkqlka-------lesqkrt
ggylnncekq----pqrpggik-df----tahe------ck----hk-fp
--vqrlpltts-------vks----------lpccrng-kfr-------g
dnp-------ltdkltsdaapkkgailke---vvkdwv-----------k
ganml
>A
qeahlgfdkvapser-ld-mvlrsrkcl-vfkeaaitt---ayskvvdcn
t-esaf--sgn--ytggsltf-r--ee-------------ppfrkgp---
--------dsanivggigkltvnviivyqlmndl----tsl---mtvtkg
d---fk-sdals-dcksf-----apdsidlvgeadpsnksegkehkskdy
knslsv-tgstetsfsripr---iafkrsfmgsvlt-ifsdica-ltley
g--q---------lev----qtkkakqlvaf---------tlyiisekds
ekkdr----------anllpkls--eiky--aeatfrllyi--e-nes--
------qfln-pdveqlveatpsphgsig--nanglggciis---kavlq
sg------incayevsnvgfd------geqyga--tith--lyaknlaaf
aadsspgcvtdhkkdlqaladlpe-nstvkk--------vlid-sdlfha
yv-----aqlgktv-aqkppamtytfcgsptknpksllkhimf-------
-gfehhc-de----khkps--a-qf----aiqegnlktactgtgenkkfa
--leayptitsptlgkplvtterd-tklcfslpcctnglalq-------s
eat---------kkletdtvstsqpllqegfvvvniwigkeltceadvrt
g-qal
>node6
qdg-----svaseerafekmilrtr-------dpgvkthfknnssivycq
t-qs-f--sgnekltggslvf-p--dn-------------ppiqktp---
--------dsvnrvggtgvvliniiivyqlknhl----ttl---itvfkg
dmvkfk-sdnltvdcknl-----ageg---vgnaqpthkteskdhgskpy
enslsvpt----asfarapr---vayrlsykggile-ifegqce-lgldy
g--qfsyeagprhvev----hvrkshqaiay---------q--ilsekda
dksdrpsat----nysplipklg--kiheaptessfqllyspie-nvt--
------pylhshglehlveptps--sgig---------cvia---kavlr
eg------insnyevtskdfg------gdqfga--tinhyplysk--gsf
aakksvgcvmdhk----aladlps----vrra-------vlvd-sdvfha
yvkcpngaqlgkas-aekppgknytfcgkatkhvtsllkhi-f-------
-gyenhcead----sqkpg--a-qfa-iyavqegdlrnackkpsssk-fa
yaveslgsilsp------vt---eg----ynlsccr----fqdlfwgpkg
evt---------nkltadtnsnnqpflqegfvgindwvg------selrt
g-eal
>node7
qeg-----rvapeer-ldkmvlrtrkcl-mfkesavkthfknnssvvych
k-qs-f--sgneklsggsltf-p--en-------------ppikktp---
--------dsvnrvggtgkllinviivyqlknhl----ttl---itvtkg
dmvvfk-sdnlsvdcksl-----agegqdlvgeaepthkseskdhgskpy
knslsv-t----asfarapr---vayrksymggvle-ifedicg-lgldy
g--q---------vev----kvkkshqtlaf---------q--ivsekda
dksdrpsst----nysplipklg--eigdtptetsfhllys--e-nvs--
------kflashdleqlveptpg--gsig---------cvia---kavlr
eg------insnyevtnkgfd------gdqfga--tithyplysk--gsf
aattspgcvmdhkkdlqaladlps----vkrt-------vlvd-sdvfha
yvkcpnkaqlgkts-aekppgmtytfcgkatkhtkallkhi-f-------
-gyehhcedd----sqkpg--a-qf----avpegdlrnackntgank-fa
--veplpsitsp------vtsdkeg----ynlpccrnglrfq-------g
eat---------nklttdtasknqpllqegfvvindwvgaelvcetelrt
g-dal
>node13
kdg-------apddr-mekmvlrtrkcy-afknsnvkthylnsr--vych
adqs-f--aqhqensggalaf-plvet-----fvklrpemepitkkptrw
hlpdarnddavnriagsgklqitvfiiyqltnhm----ttl---itvskg
dmavlq-sdhlsnpck-f-----ageghhmvgdaqpeqt--skdpaskpy
knalsv-t----acfaraarvvltnyqksyqggvlk-ileerig-mgtey
g--q---------vev----vakevhvtlkf-------------------
-rsdkpsps----nysrlipmie--eigdtpnettfhqlfs--sptig--
------kfldshdllhl-vptgg--sstg---------cave---k-vlr
en------vtpqfevnakgfa------tgqfqvestaspyplysk--gsy
aataspecvvvqkagleslanlpsd---vlrs-------il---p-vfna
yakcsnkaelgdta-aekppgmtyef--katkqiks-------ldtqkrs
sgylnnsein----phkpg--s-df----aa-qgdlrnack----hk-fa
--veplksvss-------vksdkq-----yvlpccsng-rfr-------n
dat-------lvnklttatakknaalvqk---vvddwv-----------t
kaeml
>H
ksg-------pkdsd-laklalrsrkcy-nyktnsskthylnsr--vych
adqs-f--aehqeatggalaf-plvetgdatifvklrpemdaitkkptrw
hlpdaryddavnriagsgklpitv-----ltnhlpeatetl---itvskg
nmavlq-sdhlsgpck-f-----ageghhmvgdaqpekt--skdsaskpy
knalsv-p----acfaraarvv------syqggvlk-ilnerig-mgtsy
g--q---------vev----vvkevhatlkf-------------------
-rsdkakps----nylhliplte--efglthnetqfhqlfs--sptig--
------kyldshdllhl-vptag--sssg---------cave---k-vnr
en------ctpqfkvnakgypht----tgqfqvgssaapyplysn--gsy
aategpecvvtqkpgleslanlpad---rlrs-------il---s-vfna
yarcsnkpelsdtt-gekppgkthef--dvsk--ks-------ldtqkrs
sgylks-ein----pqkps--s-nf----aa-qgdlrngck----nk-fa
--vdplksvss-------vk---q-----yvlpccsdh-rfr-------n
adt-------lanklatltgkkkaglvqk---vpddwv-----------t
kaqml
>node14
hdg-------apedr-mekmvlrtrkcy-mfkqssvkthylnktsvvych
sdqs-f--sgnqqlsggaltf-plvet-------------epitkmptkw
hlpdarnedavnriggtgklqitvfivyqlknhm----ttl---itvtkg
dmavle-sdnlstsck-f-----agegldmvgdaqpdht--skdpaskpy
knslsv-t----acfaraar---vnyrksyqggvle-ileercg-lgtey
g--q---------vev----takdshqtlkf-------------------
-rsdkpsst----nysplipmig--eigdtpnettfhllfs--e-tig--
------kfleshdlehl-tptgg--gstg---------cale---kavlr
eg------vtsqfevnskgya------kgqfnvestnkpyplysk--gsy
aattspgcvmvqkaalqalanlpse---vlrt-------ilvdmp-vfha
yakcpnkaelgdta-aekppgmtyefcgkatkqiks-------lesqnrt
sgylnnceid----pqkpg--s-df----aapegdlrnack----hk-fa
--veplpstss-------vksdkq-----ydlpccrng-rfr-------g
qat-------lgnklttdtakkngallqe---vindwv-----------t
gadml
>D
qdg-----svaseekafnklilr----------pgvktnfknnssitycq
t-ds-f--sgneklsggslvf-q--gs-------------ppiqktp---
--------dpvnrvggtgvvlieiav------------vilsasvtvfkg
dmvkfafsdnltvecknl-----aeeg---vgnaqpthkteskghggkpy
enslsvpt----tafarapr---vayrlsykggile-ifvghci-lgldy
gqgqfsyeagprhvev----hvrkshsaiaysfglltgavq---lsekda
dksdrpsat----nygplip-lg--kih-vptgstfqllyapie-nat--
------pylhshg-ehllertps--agigsn-------cvia---kavlr
eganinvalnsny--tskdfg------gdrfgg--tinhyplygk--gsl
aakntvgcvmdhk----aladlps----fk-----------vd-sdlfha
ytkcpqggqlgkas-aekppgknytfcgkatkqfttllkhi-f-------
-gfenhceadfksdsqkpg--a-qfq-iyagqegdlrnackkpsgsk-fa
yavdslvstlsp------vt---eg----ynpaccr----fqdlfwnpkg
qv----------nkltadldsnnqpflqegfvg-----------------
---al
>node15
qeg-------apeer-lekmvlrirkcf-mfkqsavkthylnntsvvych
knqs-f--sgneklsggsltf-plven-------------epikkmptew
hlpnarnddsvnriggtgklqinvfivyqlrnhl----ttl---itvtkg
dmavlk-sdnlsisck-l-----agegqdmvgeaqptht--skdpgskpy
knslsv-t----asfarapr---vgyrksymggvle-ifedkcg-lgldy
g--q---------vev----kakqshqtlkf-------------------
-rsdrpsst----nysplipmig--eigdtpdettfhllfs--e-yvg--
------kfmeshdleqlvtptsg--gsig---------caid---ktvlr
eg------vnsqyevnskgfa------ggqfna--tnthyplysk--gsy
aattspgcimdqkkdlqaladlps----vlrt-------ilvd-s-vfha
yvkcpnkaqlgdts-aekppgmtysfcgkatkqtkallkhi-flesqnrt
sgyehncedd----sqkpg--a-df----avpegdlrnack----hk-fa
--veplpsttsp------vksdkng----ynipccrnglrfq-------g
qat---------nklttdtakknqpllqegfvvindwv-----------t
g-dal
>B
qeahlgydkvdp--r-lk-mvlrcrtclkmfkeaavkthikgyskvvgcn
t-hshf--ngn--yagneltf-r--qn-------------ppikrtp---
--------qsadivggvgkllinvimvyqlsnnl----tal---kavtrg
emvvfk-sngls-ecksf-----ppdsqdlpgeadihnksegkergskdy
kdslev-i----tsfarapk---vahrrsyvggvft-ifealcg-ltlay
g--k---------vea----qvkkapqtiaf---------t--ivnekda
dkkdrpett----iyanlipkls--dige--aeasfrllyi--e-nvs--
------rftnvhdlehlheptpa--gsig--narglggciia---eavlq
sg------idyayevtng--d------gdqfga--tithyp-----laaf
aadtspgcvvghkkdlqsladlps----vkkt-------vlld-ndllha
yvncpskaqlgktaqaekppamtytfcgset--------hvmf-------
-gfehhc-de----shmps--apqi----avpeadlrpgckgtgankkfs
--ldafpsis--slgkpvvssdrd-----yslpcctnglall-------g
eat---------ktlatdtestnqallqegfvkvhiwtgaelacktdlit
g-drl
>C
qdg-----pvaeeerafetsilrtr-------dpgvkvhfnnas------
--ep-f--pgneklk-gs--f-q--dn-------------ppikntp---
--------nsvkkeggtgvvlinfiivyqlknhl----ttl---invfrg
dmvk------l----skleslcaages---vggeqpthrteskdhgakpy
enslsvet----essarapr---vayrvnykggile-vsegqcaalgldy
g--nlsyeagprhvev----hlrkshqatay---------e--ilsekda
dksdrpsat----nysptipklg--kvpaaptessfqtlyspie-ytifl
plgdtlpylhanglehlvgpips--tgig---------cvva---aaplr
eg------instyevtspdig--vlcpgdqfga--tinhyplyrk--ssf
aakksvgcvkerk----aladlpn----vpratskvglpvlve-pdvfha
yvkcpyggqlgras-aekppgknhtfcgkatkhvacllkhi-f-------
-gyqnqiead----ndkps--a-hfapvyavaegdlpnackkpssss-ia
yaveplgsilsp------at---eg----yslpscr----fqdlfwgpkg
svt---------nklsadtnsdnqpfvqegfvgindwvg------sefrt
g-eal
>node3
qeahlgydkvapeer-ld-mvlrsrkcl-mfkeaavkthfksyskvvncn
t-qsnf--tgn--ytggsltf-r--en-------------ppikktp---
--------dsanivggvgkllinviivyqlknnl----tal---mavtkg
dmvvfk-sdsls-dcksf-----apdsqdlvgeaepnnksegkehgskdy
knslsv-t----tsfarapr---vayrrsymggvlt-ifedicg-ltldy
g--q---------vev----qvkkahqtiaf---------t--ivsekda
dkkdrpstt----nyanlipkls--eige--aeasfrllyi--e-nvs--
------kflnvhdleqlveptpg--gsig--narglggcvia---kavlq
sg------incayevtnvgfd------geqfga--tithyplyakalaaf
aadtspgcvvdhkkdlqaladlps----vkkt-------vlvd-sdlfha
yvncpnkaqlgkta-aekppamtytfcgsatkhpkallkhimf-------
-gfehhc-de----shkps--a-qf----avpegdlrtackgtgenkkfa
--leafpsitspslgkpvvtsdrd-----yslpccsnglalq-------g
eat---------kklttdtastnqpllqegfvvvniwigaeltcetdlrt
g-dal
