>A
aqdli---kishyppwp-vqqqplf--tkira-------nngqr---f--
-aavet-s----tkkhpagigpl-------aglgqsta---lkn-tak--
-k---vtvir-----------daqmlvltqahtlpephddt--atkski-
-tslapqksnkpavf--laf-sfasg-------artq-akwpkklahass
gnpaea------a----gtldkgqvratakgpflkkdveds--dp-----
---tpaqyfqfk--scgey-arlkllew-----------vsmeg------
-vc------ss----------gkgg-l--vylntectqrtknnmnssvsp
nkrtgkkqkklafptkqstlrk-----k--ps------qttagkkrwkla
ldv---ddll-g-lv---yaaeavgk--iass-----vrsgatifqlsap
gkvge-------pvgvanv-------lieslqelvgnlsn----ifdpnv
agagvalsrpetsl----rgr-rp-fhlckpnrsiqkenlsafgdeskta
nr---gpch---rgvrdnfl--lsarnglgndkeaymeylflay-----a
lris---et-v---sggdggekksakgs-----ts--d---lgtn-ssvh
aage---------------gg---gt----asgkagpkktiagpalggy-
evkktd-lscklai-------hhyf---------atniqrladapyc---
kvdvflpmtgq-eg
>node14
tqdlitsgklkrynpwc-vaeatif--t-ckp-------dtgqn---fn-
naahdt-s---nttrhpagvaplehkvptgqe---saa---lrndtqk--
-kep----vr-----------dgqllqlngtqkvpep-gkt--vtkmli-
-tpeapqsankp-----l-f-sfdtgh-eiltvarmg-arwphq---ess
gnrsel------aqa-kdtfkkspkrasakgrfprkepdds--daak---
--rtsyqwfqfd--nc--fktk-kllewg----------vpmpg------
-ftkhnd-katgvk--fcdydgrac-l--pylna---------lsealaa
nkkcgmr---lflpakqcihrkftkpgkfspt------ytdsprrkw-lk
lan---ddly-g-aa---yawqasgk--gqgsmavd-vvagktifqlsgp
gktgeafys---vvv--sa-------kvgcvqglvgalsqteckdldsnv
tgqgs-----dsei----sci-rdg----kearspqketlgpfgtesrld
vhpslgtch---rgvkenst--mntraglgtrreayldyiflsy-----a
lkis---gp-f---sggd--gkksakgtalaiallryd---ldvn-sgvh
aaak---------------gg---pa----a-g------kaeg-------
gsgtsa-mscqtcs-------ntyf---------ann----seakyc---
dvdvflpmsvq-eg
>node15
aqdlitsgklkrynpwc-vpehplf--tkcrp-------ntgqn---fh-
dtasdt-s---ntkrhpagvapl-------qq---saa---lrndtak--
-k-p----vr-----------daqllqlsgpqtvaqp-nkt--vtksli-
-tplapqsankpavl--l-f-sfttg-------armg-arwphq---ess
gnksel------a----ntfkktqkrasskgpfakkdpeds--daai---
--rtpyqyfqfk--sc--fkdrlkllew-----------vsmpg------
-vtkhnd-ktt----------gkas-l--pylna---------laealas
nkkcgmr---lflpskqckhrkfvspgkfsps------ytdsprkkw-lt
lds---ddll-g-aa---yasqaagk--vqss-----vvagatifqlsgs
gkvge-------vvm--ta-------kvacvqglvgtlsktevkifdpnv
tgagt-----dssl----scl-rdgshlckqdrspqretlspfggesrrd
hh---gpch---rgikensl--mntraglgtrreayleyvflsy-----a
lkis---ee-f---sggd--gkksakgtalaigtfryd---ldvn-stvh
aaak---------------gg---ps----a-g------paegpaltgf-
gvkqsa-lscklss-------nnyf---------ahn----seasyc---
dvdiflpmsvq-eg
>node7
aqdlitagklkrynpws-vpehplf--tkira-------ntgqn---fe-
dtatdt-s----tkkhpagiapl-------qelgkssa---lrn-tak--
-k-p----ir-----------daqlltlsgpqtvpep-nnt--vtksli-
-tplapqkankptvl--l-f-sftsg-------armg-arwphe---qss
gnksel------a----ntfdkaqkrasakgpfakkdveds--da-----
---tpiqyfqfk--sc--yndrlkllew-----------vsmpg------
-vtknddpktt----------gkas-l--vylea---------laeatas
nkkcgmk---lflptkqckhrk-----kfsps------ytnssrkkw-lt
lds---ddll-g-aa---yasqavgk--vqss-----avagatifqlsgp
gkvge-------vvgvasv-------liacvqalvgtlsnkevkifdpnv
agagt-----dssl----scl-rd-shlckqdrspqretlsafggesrsd
nh---gpch---rgikdnsl--mntrsglgtrreaymeyvflsy-----a
lris---ee-f---sggdtggkkstkgs-----taryd---ldtn-stvh
aase---------------gg---gt----a-g------paagptlggf-
gvkqsa-lscklsr-------nnyf---------ann----gdatyc---
dvdiflpmtvq-eg
>H
------sgdlnryapwctvseatag--t-ckp-------gtgqd---yd-
na---trpfnghttrhpag------------t---sas------------
-qlp----vr-----------dghllqltgtek------kp--vttmlie
esppapqspsip-----l-flt---gh-eiltgarms-krwphh---ess
gnksnl------sha-kssfkkgpkrasakgrfpkkepddk--dsakerg
ksrtgvqwvqfe--nc--fkmk-lllvwg----------vpepg------
-----------gvk--fcdyqgrac-lskaylna---------lsedlav
nsksgir---vlappnecahrtftkpgkfsps------ftdaprrkm-tr
aakkihdqly-gspg---ytwqqsek--gegsmsve-vvtgksigeligp
gkggegfys---vvv--skkkrrahakvgcvqgligelteteckdlgadv
ngqgp-----ntei----ncisrdq----ketrsheketlvpfggdyrms
vhpalgtchsykngikedea----traglgtrsqsyln----sy-----i
lkis---gp-l---sggg--gkrsskstnltatllhyd---lnvn-sgvh
aaar---------------gg---smyaaea-g------dgdg-------
tsgtsacl-cetcs-------ntyf---------psn----tdakycaad
dlevflpmclqkeg
>B
aqnlitageiaqftpwp-vpeqplf--trvra-------qngqr---f--
-tames-a----ykkhpagigpl-------qevtkstd---lrn-tak--
-k-agittir-----------daallsrtgaqtcpek-ndt--atksli-
-talapqksskp--f--laf-niafg-------artk-ak---hlahqst
ghsada------a----ntlnkgqkrasakgpfdkkdveds--dp-----
---tsaayfqfk--rc--y-arlrllew-----------aslplkvsrdv
l--------ss----------gkag-l--vylnaectqvpknnlgsvlas
nkkagmkqkilafptkqsihrk-----k--ss------attagrrrw-la
lds---ddll-k-lv---yaaesvgk--nqss-----avagatifqlsgp
gkige-------vegvaqv-------vvacehalvgklsnmqiklfkpkv
agagaalsrpdtsl----rcr-kq-fhlckqnrspqrenlsafgdesrte
nr---gpsr---rgvkdsslvaknarsslgnsreaymdyvflay-----q
lrisadaes-t---sgghgggkksakgs-----tar-dpselged-ssvh
aase------------lagggqnggt----aqgkagpkknaagpslgdfl
eskktv-lscklar-------hqyf---------ank----gdatyc---
n--vflpkagq-eg
>E
tqdlitsgklkryppyc-vaeatif--d-ckpsvkgqsdetgqk---fn-
naahdt-s---nttrhpagvapva-----gqe---naa---frndtkkqd
mkdp----vr-----------dgallnmngtqkvpep-gkvsgatnmii-
-vpespqtvnka-----i-f-eidtghieilsvprmg-q--pht---dad
gnkadl------atakketnkksakrattkgkfprkapqdyhvdatk---
--rspyrwfhfd--hc--fkdk-dllhwg----------vsmpg------
-gaklnd-pftgvk--fcdydgkac-v--pylra---------fketvgs
rkkcgmr---lslpskqcihrkltmpgkyspt------ytdtpqqkw-lk
lsg---davygg-sa---ypwvangkh----smvvnlvvtesvlfhlsgp
skcgealfg---svv--st-------kagcv--lvgalsqteckdleskv
rgqsd-----dsdisnklsci-rhg----k--rspqkemlgafgtegald
vhasvrtch---rg--------mntrgglgtrr----dyiflsy-----v
lkig---apkf---sgma--akksaqhtn-------------dan-sggh
alak---------------gg---pv----a-g------naeg-------
gsgaee-qfcktcs-------ntyfiernvndglann----cegkyc---
dve-f--ltlq-en
>node3
aqdlitagkiarytpwp-vpeqplf--tkira-------nngqh---f--
-tavet-s----tkkhpagiapl-------qelgksta---lrn-tak--
-k-agvttir-----------daqlltltgaqtvpep-ndt--atksli-
-tplapqksnkptvf--laf-sfasg-------artk-akwphdlahqst
gnsaea------a----ntldkgqkrasakgpfakkdveds--dp-----
---tpaqyfqfk--sc--y-arlkllew-----------vsmpg------
-vc------ss----------gkag-l--vylnaectqrpknnlasaias
nkkagmkqkilalptkqsthrk-----k--ps------yttagrkrw-lt
lds---ddll-g-av---yaseavgk--vqss-----avagatifqlsgp
gkige-------vvgvanv-------liaclqalvgnlsnmqikifdpnv
agagtalsrpetsl----rcr-re-fhlckenrspqretlsafgdesrte
nr---gpch---rgvkdnsl--mnarsglgnsreaymeyvflay-----a
lris---ea-t---sggdaggkksakgs-----taryd---lgtn-ssvh
aase---------------gg---gt----asgkagpkkpaagpalggf-
evkkta-lscklar-------hhyf---------ann----gdatyc---
nvdvflpmtgq-eg
>node13
tkklitsgklkryspwc-vaeatif--t-ckp-------etgqn---fd-
naahdtrs---httrhpagvnplehkvptaqt---saa---lrnnaqk--
-kvp----vr-----------dgqllqlngthkvaap-gkt--vtkmli-
-tpeapqspnkp-----l-fls---gh-eiitgarmg-nrwphh---ess
gnksnl------aha-kasfkkspkrasakgrfpkkepdds--dsak---
--rtgyqwfqfd--nc--fkmk-lllewg----------vplpg------
-----------gvk--fcdyhgrac-l--aylna---------lseelaa
ntkcgir---llappkqcihrnftkpgkfsps------ytdtprrkf-lk
aakkihddly-gsaa---yawqqsgk--gqgsmave-vvtgktigelsgp
gkagegfys---vvv--sktkrrahakvgcvqgmigelseteckdldadv
tgqgp-----ntei----nci-rdq----kevrsadketlvpfggdsrms
vhpalgtchsykagvkensa--mntraglgtrseayld----sy-----a
lkis---gp-l---sggd--gkrsskgsnlaaallhyd---ldvn-sgvh
aaak---------------gg---smfaaea-g------dadg-------
tsgtsaclscqtcs-------ntyf---------pnn----teakyc---
dvdvflpmsvq-eg
>D
aqdmssdgkvkrltpwg--pehplylhtkikg-------stgqn---fk-
dtstat-s----tekhpagiavg-------qelgksta---lrn-tek--
-m-p----irydqsgrhtqiidaqlltlagsqtvadq-dnn--vtkaln-
-tplhpqkaikptvlvgl-f-rpt---------------rwphd---qtk
gdksea------p----g----------------rkdveds--na-----
---tsieyfqfdhctc--ykhrvkllew-----------vskpg------
-iakydvqktd----------gkps-l--vt-la---------laeatas
rk-------------------k-----kfssekgkflaytnsarkkw-lt
lnt---ddle-g-aa---yatqvvgs--vhvs-----avggpttfqlsgp
gkvge----sgavvgvagv-------viacvgslvgalsnrevkffspni
kgvat-----dssl----acl-rd-thlckqkvsperevlsafgpqtrps
ph---spcq---raimd-----mnlkaglgtsregymdytilsynpaaga
lmie---eq-f---sng--gmkkstkgs-----tgs------dtd-atvh
aase---------------ag---gp----t-g------pasgpslggf-
--kqqa-lscnlsk-----lssnyf---------nns----g---yc---
dvdiflpmviq-eg
>F
tqdlitsgslkryppwc-vteatif--t-ckp-------etg------eg
naindt-s---ttttnaagvapiaa----gqe---saaksa--------d
mkdp----ar-----------dgqllqlpgtqkiadp-gklsgatnmvi-
-ape---sankp-----l-f-sfetshfeiltvprmg-r--pht---gts
gnisel------aqakketskkhpkranvkgkfprrepenfhvdatk---
--rsayrwfhfd--qc--fkdk-dllnwg----------lpmpg------
-fsklnd-pftgvkvpfcdyngrvc-l--pylka---------fseplgs
dkkcgmr---lflpskqcihrkitkppkkspt------yndtprkkw-lk
lad---dsvysg-pafrnypflangrhggqnamvgnlvvagstlyqlsgp
gkcgeafyg---pvv--st-------avacv--ivgklsq------dskv
rsqsd-----eadi----n-i-rhs----k--rspqketlgafgtgpeld
ihaslctch---rg--------mnargglgtkrqglldyiflky-----v
tkvg---gqky---sgmg--akkspehtklgv--lr------dvsgpgvh
aaskrpakkaysvayh---gg---pa----a-g------kseg-------
gsgay--mfcqtcs-------ntyy---------snn----ceakyc---
svevf--lslq-ed
>C
aqdlasdgkvkrltpwc--pehply--tdikt-------ntgqnlglfk-
dtdtdt-g----tnkhgagiasl-------qelgksaa---lkn-tad--
-m-p----ik-----------eatlltlsgpptvpep-dnn--vtssip-
-tplqpqpadkltvmvgl-f-rattg-------armglsrwphe---esk
gdk-et------t----ntfddaqkrasakgpft-kdveas--na-----
---gpmeyftfd--tc--cnerlkllew-----------iskag------
-vvkyddnktt----------gkptgl--vt-la---------laeatap
rkkcgmk---lflpakqs-rrk-----kftpgpgnflay-nsvrknw-lt
lnt---dekn-g-aa---yltqstgs--ttps-----avagptifqltgt
gkvgq----tganvgvagv-------liacvqslvgtlsnkkvpffkpri
agaat-----dssl----acl-rd-ahlckqkvspdrgvlsafgpenkps
kh---spch---kaikn-----mntkaglgtrregymdytilnykpagga
lriq---sq-f---pdgpvggkkcskgs-----aaryt---ldtn-stih
aase---------------cg---gp----t-g------pargpslggf-
--kqng-lscnlerlggiqltsqyf---------hnn----ggasyc---
dvdiflpmqvq-eg
>node6
aqdltsdgkvkrltpws--pehply--tkirt-------ntgqn---fk-
dtatdt-s----tnkhpagiasl-------qelgksta---lrn-tak--
-m-p----ir-----------daqlltlsgpqtvpdp-dnn--vtssli-
-tplhpqkadkptvlvgl-f-rpttg-------armglarwphe---qtk
gdkset------t----ntfddaqkrasakgpftrkdvees--na-----
---tpieyfqfd--tc--ynerlkllew-----------vskpg------
-vtkyddqktt----------gkps-l--vt-la---------laeatas
rkkcgmk---lflptkqskrrk-----kfspskgkflaytnsarkkw-lt
lnt---ddln-g-aa---yatqavgs--vhss-----avagptifqlsgp
gkvge----tgvvvgvagv-------liacvqslvgtlsnkevkffspni
agaat-----dssl----acl-rd-thlckqkvsperevlsafgpeskps
nh---spch---raikd-----mnlkaglgtrregymdytilsynpaaga
lriq---eq-f---sdgdvggkkstkgs-----taryn---ldtd-stvh
aase---------------ag---gp----t-g------pasgpslggf-
--kqsa-lscnlsr-----lssnyf---------hnn----gdatyc---
dvdiflpmqvq-eg
>node10
tqdlitsgklkryppwc-vaeatif--t-ckp-------dtgqn---fn-
naahdt-s---nttrhpagvapiaa----gqe---saa---frndtkkdd
mkdp----vr-----------dgqllqlngtqkvpep-gkvsgatnmii-
-apeapqsankp-----l-f-sfdtghieilsvprmg-q--pht---das
gnksel------aqakkdtfkkspkrastkgkfprkepedfhvdatk---
--rsayrwfhfd--nc--fkdk-dllnwg----------vpmpg------
-ftklnd-pftgvk--fcdydgrac-l--pylka---------fsetlgs
dkkcgmr---lflpskqcihrkltkpgkyspt------ytdtprrkw-lk
lad---dsvysg-sa---ypwqangrhggqnsmvvnlvvagstlfqlsgp
gkcgeafyg---pvv--st-------kvgcv--lvgalsqteckdldskv
rsqsd-----dsdi----sci-rhg----k--rspqketlgafgtesald
ihaslstch---rg--------mntrgglgtrreglldyiflsy-----v
lkig---gpkf---sgmd--akksaqhtklav--lr------dvn-sgvh
aaak---------------gg---pv----a-g------kaeg-------
gsgaee-mfcqtcs-------ntyf---------ann----ceakyc---
dvevf--lslq-ed
>G
tkklitsgklkiypawc-lveatif--t-ckp-------eagqn---fd-
naa---ra---kttrhpagvnplehkvpsaqt---saa---lrnnaqk--
-kip----vr-----------kgqllqlngthkvaap-gkt--vakmli-
-apeapqsp-------------------etitgarmg-nrwahh---ens
gnksnlslatmaeha-matfkksprrasakgrfpkkdpeds--d------
--rsgyqwpqfd--sc--fklk-lllesgahcgegcqrvvplpg------
-----------gvk--ycdyhgqpc-v--gymna---------lseelsa
askcgic---llapvkqcihrdlvkpg-----------ftdtprsqf-lk
aa-kihqdly-gsaa---yawqqsgd--gegsm--e-vgtagtigelsgp
gksgdgfyn---vvv--sktkrrahalvgcsaamigeltetecknldadv
agegp-----nsei----nci-rdq----kevrgedkdtlvpfggdsrms
vnpalg--hrysagvkenvt--mntraplgtrsaayld----sy-----a
wkis---np-lprktggn--gkrss--------llvyd---ldva-sgvh
-eak---------------gp---nmfaaea-g------dadg-------
tsgasaclscqtcs----------s---------pns----keskyc---
nvdvflpmsvq-eg
