>node10
agvicppcqrgkdvpe-------av--sksplhcqeka----------dt
cc----dfc-pkargysk---ka---------igyvflcrlde-----me
dnaeglehc-hcshgyaksnagnq--ptcektdhfv---dg------sld
sctkdfqka-------ekdiyyh---------rhatv-aysvhlqs----
-------vvsvvvdtwflierverlaakq---tgt----g-glvni--ge
maggt---------ph----rtqkf-----------pr----linyig--
--qan----es-----liqpq-wks-----etavhsipgkfaqkd----e
etigdaqd----nvgyfrql------a--af--as---qel--y-gakgk
smlcdpvgtq---rlcifkgagehnll-----a--dvrigrtldgttsvf
-lkacacrsscthcvcgctiqcgkak------adaead---it---knar
lksklgsr---apgv-qasnll-gsepki-------pllr-------nqg
dssqcaa--la--e----pg-------frkg---n---ssfavpqerl--
sqqghstisgetgtvmdf--icgnghftgrgye-l-gnannlr-----rh
-g--ttkaatgqyk--e-grhkqslrfk-tf--gk-kkgnactkd--ncl
etntigkahiptmkakrhnqm--shidlpfi----kys--nlwk-----e
fdd-----------stfcras
>node6
ggvvchgcqksddvsq----iddav--s-pglhckeeaydcs----dta-
-c----dycqpkargydavlekp---------igfvfkcrldq-----la
akgdg-nhc-hccpvypsdgssle--haqektdhfv---dg------klg
fcakdfyidr------fkeiyfk-------------laaycv--------
-------la-vrsstgfliervgclaatq---kst----gsglvaa--ge
----t---------pa----qrqkf-----------qr----lig-----
--rvn----kganpvtd-----wkt-----d-aclt--------k----t
dkvggsq-----nagyfqhk------a--df--sk---edv--y--akgk
sviytgvaaqelaklctfkgpgeehll-----a------geqidgtts-f
tlksvackgmclhsgctcs-qcekskeefgynsnakge---vt---kpgw
lhgr-gak---sp------nll-gseasvnlfse-dqllr-------nda
assqcsa--iapve----p--------fkkgcage---sgfavk--al--
--qgynatsdd-ttvmdi--vcgnshyvgtgye-l-psgrglnqvlemrd
-g--st-tptdfyk--d-grhadrlhfn-tftgpk-kndqacnld--dcl
dvatfghtpcagmkakkhhet--cliglpfipehitysvtglwr----cn
fdd-----------sdfcept
>H
agsvcppcnkadgvselivl---avgcnkpplhcheta----------gi
cc----dnc-pkgrsysp---qa---------igyryyckldq-----mg
vkadaldhc-hckqsyatddaagk--atsgkpdhfv---dg------sln
sccsgfykar------ekqiyyq---------rrttv-afsvhles----
-------vl-vgantwflidrvarlaake---kgv----gdqva------
--sgt---------ph----stekf-----------pr----linftt--
--las----eg-----liep----amtvsle-gshs--------d----e
eetadtq-----nvgdlqkk------a--as--ag---egm--ysgakgk
sflcdpvgavvlsrlcelkgpgedgll-----aavdmrkgakldsaps-l
-lkgc-----cshcgcica-qca--kkd----a---gn---it---knar
hksklgak---a----aapell-gsepki-------pvlq-------nng
gsspcarslla--a----pd-------frkg---t---snfa----glaa
spqghnavssrvgkvgdf--vcglafytgkgye-v-gevgslqdvpemrh
-g--ttkaadneyk--e-grhkhalqfk-tf--gk-rnnnacnld--ncl
dkisigkthipnmtakrhhqmqvchidlnfi----rys--slwk-----e
fdgdvk--------tefcsan
>node3
ngivcvpcqksedvse-------av--s-pglhckeeayncs----dte-
-c----dycqpkarlyeallekp-----gdh-igyvflcrldq-----ma
ekqeglnhc-hccpqfpkegnalq--qarektdhfv---dg------klg
fsakdfyidr------fkeiyyp-------------ltsycv--------
-------la-vrdntgflidkvgclaak------t----gcglvaagkge
----s---------pt----rrqkf-----------qrkfevlig-----
--rvn----gg-----n-----wks-----n-scls--------k----e
dktggsq-----nimyferk------s--af--sk---eev--f-sakgk
tviytgvaaedlaklctfrgpgeehll-----a------gdqmngtts--
-------------cgctcs-qcekskkeygysstadge---vt---kqgr
lhsr-gqk---asglq-ynkrldgseps---fve-dqllr-------kkg
srsqcsa--iap-a----p--------fkkgcagk---sgfavl--pl--
spqehnassgdtstvmdl--vcghghyvgpgyevl-psgsggqqvfdmrd
-g--st-tplvnyk--d-grhgtrlhft-tftgsk-kndqacnlddqdcl
diasfggatcpkmkakkhhem--cqidlpfikehitys--glwr----ya
fdd-----------sdfseps
>C
ggvvchgcdksddvle----iedav--s-palhckeeayecsqgayets-
-c----ey-qpkargydavlekp---------agfvfkcrldq-----la
akgdg-hhc-fccpvypsdgksld--haqsktqhft---eg------kig
fcpkdfyids------yeeiyyk-------------laaycv--------
-------lp-vrsstdfiiervgclaaaq---vgt----gsgivaa--ge
----t---------pa----krarf-----------qr----lig-----
--rvnldqdkgakpvtd----awkt-----d-acln--------r----t
-kvggdq-----naeyyehk------a--df--sk---edatsy--akgk
sviytgvaaqelakmctfkgpgaehll-----a------gdnidgtss-f
tlkavackamclhggctcs-qaekskenfgynsnakga---vt---kpgw
lhgr-gek---sp------nll-gnearvtlfssseqlmk-------adt
assqcsa--vapve----p--------fkkgcagd---sgyavt--af--
--kaynatsee-ttvmdiyvvcg-----gtgye-l-ppgrslnhvlemrn
-gpgst-tpteffk--dpgrhadrlhfn-tftqpk-kndeacnld--dcl
divtfghtpctakkpkkhhet--cli----dqehitysltglwr----cn
fdd---dkkpgvslsqfsepv
>A
ngivcvpcqhaeevye-------av--s-pglhckeeefncf----dte-
-c----dycqpkarlyiallekp-----gdh-igyvflvrleq-----va
ekqeglshc-hccpqfpkeasalqtnqarekhahyv---dgvvyttkklg
fsakdfyidr------fkeiyyp-------------ltsy----------
------------dntg-----vgclaak------tgdfdgcglvaaakge
----a---------pt----rrqkf-----------qrkfevlig-----
--rvn----gg-----n-----wks-----n-sclr--------k----e
dkiggsq-----ni--fdmkthckeds--sf--sk---t-v--y-sgkgk
kviytpvaaedlak--tfrgpgeehll-----a------gdqmngatg--
-------------cactcs-qcekskkdygysatgnge---vn---kqgr
lds--gqk---asalq-ynksldgseps---fve--qalr-------kkg
gqsqcsa--iah-s----p--------frkgcask---sgfavl--pl--
spqdhstptcpttsvmdl--vcghghnsgpgyeil-psgsggqvvfdmrd
-g--st-tpllqyk--a-drhgtqlhft-tftgas-rsdqacnlndqdcl
eiasfgggtcpkmkakkrhem--cqidlsfiqehitys--glwr----ya
hqd-----------sdfsaps
>node15
ngvicppcqrsddvse-------av--skpplhcleda----------a-
-c----dyc-pkargydnllekp---------igyvflcrldq-----mg
akgegldhc-hccpvypkdnnslq--ptrektdhfv---dg------klg
fcakdfyiar------skeiyyp-------------i-aysv--------
-------vv-vradtgfliervaclaakq---kgt----gtglvaa--ge
----t---------ph----rrqkf-----------pr----lieytn--
--rvn----dg-----liqpq-wkt-----d-achs--------d----d
sktgdaq-----nigyfrqk------a--af--ak---edl--y-gakgk
sviydgvgahtlaklctfkgpgeesll-----a--nvrkgeqidgtts-f
-lkgvackslclhcgctcs-qcskakkeygfnsdaqge---it---kqgr
lkgk-gtk---apglqpasnll-gsepsinlfih-dpllr-------ndg
assqcaa--iap-e----pe-------frkg---n---ssfavlrepl--
spqghsttsgetgtvmdf--vcgnghyvgrgye-l-psvndlqqvsdmrh
-g--ttktptneyk--e-grhadrlhfk-tftggk-knghacnld--dcl
drasfgkthipnmkakkhhem--clidlpfi----tys--glwk-----e
fdd-----------sefceas
>E
ialicppcqrgkdvpd-------gv--spspllcqeka----------dt
cc----dfc-pkargyak---ia---------igyvflcrlde-----te
dnaeghenc-hcshayaksntgne--pvchktdhfv---dg------sld
scskdfqka-------ekdvyyhksnfgaglsrhata-aysvhleh----
-------vvsvvgdawflierverfatkq---tgt----g-gqvdi--ge
maggt---------ah----rtqkf-----------pr----linyig--
--qan----dv-----liq---wky-----etaihsipgkfaqkesgvke
etigdaqp----nvgffrqf------a--af--vs---qel--a-gakgq
salcdplgtq---rlclfkragernllgsdehg--dvrigrtldgttsvf
-leayacrsscthcvcgcti----------------------t---knar
lrskfgsr---apgv-qasnll-gsekki-------pllr-------ndg
dsgqcaa--la--e----pg-------frkg---n---srfvvpqerl--
-------iagetgtvldf--icgkghftgrgys-l-ensdapk-----mh
-g--ttkadtggyk--e----kqslrfkqsf--gq-kkgsgctkd--ncl
ktntigkahiptmkakrhnqm--shidfpfl----kys--dlwk-----e
kdd-----------stfcras
>D
ggvvcngcqksddvsq----idnev--s-pglhckdkgydcs----dtn-
-c----dycqpqargadaglqtp---------vgfifkcrgaqdet--la
pkgdg-thcrhccpvyssdgssle--hatektdh-v---dg------klg
fcvkeyyvdr------fkecyfk-------------lasycv--------
-------ld-vksstgfliervgclaasq---rst----daaliaa--ge
----t---------pschedakr-------------qk----lig-----
--rvh----kpasqvtd-----wkt-----k-aclt--------k----t
ntvggsq-----gagyfqhk------s--df--sk---env--y--aknk
klvatgvtvtelaklctfkgpgsehll-----a------geqidgkes-v
tlksvackgmclqkgctcs-hcekskedfaygskakgh---vt---kpgw
lhgr-gak---pp------ell-gaelpvnlfaq-dqllriaklqardda
asnqcsa--iapve----p--------fkkgcage---tgyavk--al--
--lgynattqd-ttvmgi--scgdshlvgtghe-l-ssgsglnqclemrd
-a--st-tstdlfkcvd-gkhaarlhfn-titgpkekndqsisqd--dcl
dvatfghtpcagmasqkhhat--cliglpfitehiiyantglwrveekcs
fdd-----------tnfcdpt
>node13
agvvcppcakadgvselivl---av--tkpplhcqeta----------gt
cc----dnc-pnarsysp---qa---------igyhyycrlde-----mg
vkadaldhc-hcsqsyatdnaask--ptvekpdhfv---dg------sls
scckgfykar------ekqiyyq---------rrtav-afsvhlea----
-------vv-vgantwflidrvarlaake---kgv----gdgva------
--sgt---------ph----rtqkf-----------pr----linftt--
--qas----eg-----lidp----a-----e-ashs--------d----e
eatgdaq-----nvgdfqrk------a--as--ag---qgl--y-gakgk
sficdpvgahvlsrlcifkgpgedgll-----a--dvrkgakldgaas-l
-lkgc-----cthcgcica-qcakakke----a---gn---it---kdar
lksklgak---a----paskll-gsepki-------pvlr-------nng
gsspcarnlla--s----pe-------frkg---n---ssfa----plaa
spqghsavsgntgkvmdf--vcalahytgrgye-l-gavnnlqdvpdmrh
-g--ttkaadneyk--e-grhkhslqfk-tf--gk-kngnacnld--ncl
dkisigkthipnmtakrhhqmqvchidlnfi----rys--glwk-----e
fdd-----------sefcdas
>G
agvvcpvcakasgvselivl---av--lkpplhcqqva----------es
ccrrlldny-snarrysp---qa---------isypyycrlde-----mg
vkldaldhc-hcsqsfatdnsvsk--ptvekpdhf--------------s
scckgfymarqhllneekqkyyq---------rrtvv-ahsvhvqa----
-------vv-agantwflfkrvarlaekg---kgv----degva------
--sgeggnkptskrph----ktgkflaskpiiksqlpr----linfatmq
qsqad----eg-----liep----a-----d-anha--------d----e
ealgdaq-----dvgdfqrk------a--as--ag---ggl--y-gakgk
sficdalgahvlakfctlkgpgedgll-----a--dvrkgakldgaas-l
-lkrc-----cthcgcica-qc--akke----a---gs---it---kvar
lrsklgak--------psskll-gaepki-------avlr-------ntg
gsapcprt--a--s----pe-------frkg---n---gsfa----plaa
sasahshgsdnggmvrdf--vcalshytargye-l-gavgdlhdvpdikh
vg--ttkaadn-----------halqfn-tf--gk-knnnscnld--kci
tkisigkthi-nmtpkqnhhkqvthidlkfi----rls--glwk-----e
fdd-----------sqfceas
>node14
agvvcppcqrsddvse-------av--skpplhcqeda----------gt
cc----dyc-pkargysk---ka---------igyvflcrlde-----mg
akaegldhc-hcsqgyakdnasnq--ptcektdhfv---dg------slg
scakdfykar------ekeiyyq---------rrnav-aysvhlea----
-------vv-vvadtwfliervarlaake---kgt----gnglvsa--ge
masgt---------ph----rkqkf-----------pr----linytn--
--qan----eg-----liqpq-wks-----e-avhs--------d----e
eptgdaq-----nvgyfrqk------a--af--as---qel--y-gakgk
smicdpvgahvlarlcifkgpgedgll-----a--dvrngsdldgtts-f
-lkgcacrsacthcgcica-qcskakke----adaqgd---it---kdar
lksklgak---apgvqpasnll-gsepki-------pllr-------ndg
gssqcaa--la--e----pe-------frkg---n---ssfavpqepl--
spqghstvsgetgtvmdf--vcgnghytgrgye-l-gavnnlqdvsdmrh
-g--ttkaatneyk--e-grhkhslhfk-tf--gk-kngnacnld--ncl
drnsigkthiptmkakrhhqm--chidlpfi----kys--glwk-----e
fdd-----------sefcdas
>B
ngivcvpcqkseevse-------av--s-p-lhcgeegyscs----dte-
-c----dycqpka-lyeallekpnsgcmsdhqpgdvflcrldt---nnfa
ekqeglnhc-hccpqfpkegnalq--qasektnhfv---dg------klg
fnakdffidr------fkeiyyp-------------lteycv--------
-------lt-vrdntgflinkvgcllak------a----gcglvaagkge
----a---------ps----rrqkf-----------qrkfdvlin-----
--rvn----gg-----d-----wgs-----n-rcfn--------k----e
ektggsq-----nimyferk------evram--qkeeqeqi--f-sakgk
tviytgvaaedlaklctfrgsgmehll-----k------gdrmngtts--
-------------cgctcs--cqksrdesgygstadgd---vthtakqgr
lhtr-gqk---atglq-ynkrldgsdrs---fie-dqllp-------kkg
praqcda--iap-avggfp--------fkkgcagkcpfsnfavl--pl--
spqehnpsagdtat---------hghyvgpgyevllpsgsgglhvfdmre
-g--s--tplvkyk--d-grngtrlrft-tftgsk-kndqackldd---v
diasfggatcrkmqakkq-em--cqfdlpfikehieyw--glwr----ya
fdd-----------safsdss
>node7
ngvvcvpcqksddvse-------av--s-pglhckeeaydcs----dta-
-c----dycqpkargydallekp---------igyvflcrldq-----ma
akgeglnhc-hccpvypkdgnslq--harektdhfv---dg------klg
fcakdfyidr------fkeiyyp-------------laaysv--------
-------la-vradtgfliervgclaakq---kgt----gsglvaa--ge
----t---------pa----rrqkf-----------qr----lig-----
--rvn----ng-----n-----wkt-----d-scls--------k----d
dktggsq-----nigyfrqk------a--af--sk---eei--y-sakgk
sviytgvaaqdlaklctfkgpgeehll-----a------geqidgtts-f
-lkgvacksmclhcgctcs-qcekskkeygynsnakge---vt---kqgr
lhgr-gqk---apglqpynnll-gsepsvnlfve-dqllr-------nng
assqcsa--iap-e----p--------fkkgcagk---sgfavl--pl--
spqghnatsgdtstvmdi--vcgnghyvgsgye-l-psgnglqqvfdmrd
-g--st-tptneyk--d-grhadrlhfk-tftgsk-kndqacnld--dcl
dvasfggthcpgmkakkhhem--clidlpfikehitys--glwr----cd
fdd-----------sdfceps
>F
esvictpcqrnkevpe-------av--nksplhcqekd----------dt
cc----dfc-pkargysk---ka---------igyvflcqtdg-----md
dnaeglehc-hcphgyekanagnq--ptcertdhfvgrydg------rld
sctkdfqks-------ekdiyyh---------kqatl-rysrhlqtklml
kchgnqqvvsvviiswflierierlaakqeccagt----g-glvnl--gd
maggt---------ah----rgqsf-----------pr----linyig--
--qag----ps-----liqpq-wka------savhstpekfgqk-----q
dsigdsqdkssanvgyfrpl------e--tfvtas---qel--y-gakgk
smlcdpvgtr---rpcifkgagehell-----a--svridrtldgatsvi
-lkacacrssvthcvcgctiqcgkak------sdaeantigit---khqr
lktklssrllarpgv-qsskll-gsepki-------pllr-------nag
dsshcaa--la--e----pgskkedidfrkg---n---ssfavpqdrm--
sqqqhstvsgetgtvmdf--tcgnghftgrgyq-l-gnafnlr-----kh
-g--ttkaatgqyk--e-grhkhglrfk-ty--sa-kkgdactke--nrl
etdtiakshi-tmkakrynqm--shielpfv----kys--qlwk-----e
fdd-----------itfcras
