>node15
--kltenysetassahaasgkkamlnkpk----fspgl------------
lew-----rwlglqaenwp--esfrn-lgtsaql-----n-vtggd----
--e-vtlnlgpkk--k-idychasgndewiasknmnwnkg---------k
t----nyy-rq------ypynta-gkgdrgvlrteftkn--lnygh-klf
kqygqaidgvtmgasi-qas-------dshm---wltgaidteaien---
----yrc-vlrhgng------iqaggaqkc---symvnkygipdgllv--
kge-d-n-rkvp-----lyigvd--nspkypylssrgdc---fnlqrssg
yapvhtc--entdaeiasrqakdi-------eymvpatp--mkllkvgal
aggf--tta-d-------edifkvhss-ttvggrpksa-------p--pd
kl---ggtelskhpaeepafistaksifpgflftdtmq------tihplv
na-ktapchgtatqaea--qaksfawlelseedi--p----qinhkl---
-----yralgrwnns-n--ql--kfvlatt--psllhfkhnqrqa---t-
------------lafsvgqklhatp-tpql------q----pyia--k--
---fefg-ikqggvfe-akcmtikvrlitdh---------dqcr-----e
kska-yeitaeegfehtldirkmg
>node7
--kltq-ysetapsahaaagkktmlakpk----fnhgl------------
lew-----rwlgl--ekfp--esfcn-lgtsaql-----s-vtgge----
--e-vtlhlgpkk--t-idychpsgndawvaskgmswekg---------k
tlyatgyy-kq------ypyata-gkgdravlrteftkn--lhygh-klf
neygqaiegvtmggsq-qah-------dshv---wlsgainteaien---
----yrv-vlqhgng------lqaggaqkc---aykvnktgipdgllv--
kge-d-n-rkvp-----lfigvd--nspkypylsshgdc---fnlqrssg
yapvqtc--entdaeiagrqtkdi-------eylvpatp--kkllkiggl
vggf--tta-d-------edltkvhss-ttyggepkta-------p--pa
kl---gggeltkhpaeepafiatakaifpgflftdtmq------ttppll
na-kaapchgtatqamd--qaksfkwlelseddi--a----qinhkv---
-----yralgswnns-n--al--kfvlgtt--psllhfkhsqrda---t-
------------lafsvgqklhptp-npql------q----pyis--k--
---fefa-igqggvfe-tkcmtikvrlithh---------dqcr-----e
kska-ieigveegfeqtld--kmg
>H
--kfnenffetasaahvtpgkklmlnkpe----fapgq------------
lsw---------lqhqawp--q--ry-lrvtsal-ntkss-vtgge----
--efvtlnl--ks--kcidychasgnhewvaskdmawhre---------k
n----sfyhmq------ysyldf-gkgnrgvlrreftkd--lnygh-kll
iqygqaidalsspgei-qat-------dsnv---wltgavdiet------
-----rc-dlrhgsg------iaagsa-ka---acmvknygipegllv--
rgnfv-k-rpva-----fyikvd--ssqvypyitirntcgckydnqrksc
yephhdc--estsaerav-eakqt-------gylfpvsgaa-kllslgql
tggf--q-amh-------qkifkvlkt-tdvgkrpkra-------p--ph
al---gggelskqp--------------pgfmisdarp------tlhpia
ka-ktvpch-tatqa------kalswlepsee----------ftdkf---
--------lgklndg-t--tl--efvlatt--asmlsfkhsrhqalhpi-
------------heftpgqklhanpestql------qgwslpyia--k--
---fayg-ikqkglfe-akcmtiktrllgdh---------skc-------
rtkv-fevtaqpgfedsldv-kmg
>C
--kltq-ysesvptahaaagmktmlgksk----fnhsl------------
lew-----rwlgl--dkfp--epfcn-latsaq------g-vtgge----
--e-vtlhlg-qs--t-idychpkgndawaatkgmswekgtcasgvksa-
ilyatryy-kv------ypyala-skgeravlkteftkn--fhygh-riy
aeygqavqltalggaq-qdytnleikadsqv---rltgavttdaldnygt
vvrsnkvgvlq----------lqtngarrc---gyktvktgipdgllp--
kge-d-d-rkvt-----lflgvgkgnapkypylssrgec---fnlhkstg
lapv------ttdaeia--lakdinrgtgvhrfiaa--------lk-gkl
vggf--atd-d-------qdltkvhss-ssyggeekta-------p--ss
kl---gagdltkhpaeqpgfiataksvfpgflfsvtme------tvtpll
ha-kgppcdgtdtkald--qaksfkwleltesdi--aemi-qinhrv---
-----y-----wndp-nargs--kfvl--t--pallrfknt---------
------------lals---t------npll------q----p--sngk--
---fdfa-fgrggvfh-thsmaiktrffnhd---------dqcr-----s
kskakvekgieeafehtld--kmg
>F
--kfredysdgaqsghvmsgqklmvgka---------l------------
lpw---------lqkqnwp--q--snvqavnselektktn-ltgme----
--afvtsalglks--k-idyshssgnsewv--kkmewnrd---------n
a----syyhrq------ypyndv-gkggrgvlrsqfsqn--ltygh-klf
kqfnmgidgvtm-geivqaa-------dsqm---wltgtieiqavdn---
----yrc-dipqgngdyydkivdagsa-na---cymvkkygipnsllv--
kgq-i-tvkpvg-----lyigve--cspkyafidsrnnc---ydndsksc
yapvhtc--esndearatrqgknv-------eylksaigal-kllkvgsn
aggf--r-a-tggkvdklqdifelqtsqtnvggrpkaa-------p--ph
sl---vggelsmhptdeptfispsk--fpggiiqdakpanlirkilhplk
kaantalc--gath----------awlelneedl--p----sishdf---
-----yralg--gnp-t--hidvklvlatt--p---dfkssrhqe---tf
ymkkcnllvlfllvfsvgqklnanpdapql------q----pyca--h--
---fnfgavkekgv-------tvkaalisdhkrtywgnctaqcpgdrehq
ktra-yelteeqgfeqsllar---
>node14
--kltenfsetassahvtsgkklmlnkpk----fgpgl------------
lew---------lqpqnwp--e--rn-lgvssql-ktksn-vtgge----
--efvtlnlgpks--k-idychasgndewiasknmawnrd---------k
a----syyhrq------ypynda-gkgnrgvlrteftkn--lnygh-klf
kqygqaidgvsmggei-qas-------dshm---wltgaidieaien---
----yrc-dlrhgng------idagsa-ka---symvnkygipdgllv--
kgq-t-t-rpva-----fyigvd--sspkypyitsrnsc---yenqrksc
yapvhtc--estdaeratrqakdv-------eylvpasgaa-kllkvgal
aggf--e-a-t-------qdifkvhts-tdvggrpksa-------p--ph
al---ggtelskhpteepafistak--fpgflftdamp------tlhpiv
ka-ktapchgtatqa------kslawlelseedi--p----qishkf---
-----yralgkwnng-t--hl--kfvlatt--psllnfkhsrhqa---t-
------------lafsvgqklhatpdtpql------q----pyia--k--
---fefg-vkqkgvfe-akcmtikvrlisdh---------nqcr-----q
ktka-yeitaeegfehsldirkmg
>node10
--klrddfsetassghvmsgkklmlnka---------l------------
lew---------lqpqnwp--e--rn-qgvsselektktn-ltgve----
--efvtlnlglks--k-idyshasgnnewv--kkmewnrd---------n
a----syyhrq------ypyndv-gkggrgvlrnkftqn--ltygh-klf
kqlgqaidgvsmggeiiqaa-------dsqm---wltgtidiqaven---
----yrc-dlpqgngdyyekiidagsa-na---cymvnkygipnsllv--
kgq-t-t-rpva-----lyigve--sspkypyitsrnsc---ydnerksc
yapvhtc--estdaeratrqaknv-------eylrsaigaa-kllkvgal
aggf--r-a-t-------qdifelqts-tdvggrpkna-------p--ph
sl---gggelskhpteepafisptk--fpggiiqdakp------ilhplk
kaantapchggatha------ssfawlelneedl--p----sishkf---
-----yralgkwdns-t--hl--kfvlatt--pslinfkhsrhqd---tf
ymkscnllvlfllvfsvgqklhanpdapql------q----pyca--n--
---fnfgavkqkgv-------tvkvalisdh-rtywgqcqsqcp-----q
ktra-yeitaeqgfehslear---
>D
--kitq-ysesapsahsaagkktmlgkpk----fahglcaqqnltsaawf
lew-----rwlgv--dkfp--esfan-mafspa------a-htgge----
--e-vtlslgsks--t-idychpkgndawvsskgmawekgs------gt-
tpyvttyy-kq------ypytta-gkgdratlrtdftnn--lhygn-rnf
peygqatastalaash-qaytnveikgdshv---rltaavttdaidqtgt
vvhtyrv-flqhgng------lqsngsqkc---gykvlktgiqdglla--
kgd-dla-rkip-----lf--------pkypynssrgec---fnlhnstg
ltpv------ntdadit--qtkdiskg-gvhqfavp--------lkiqsl
tggf--ptd-d-------dgltkvhys-tsygeeakta-------s--sg
kltckgagelgkhpadapgyiatlkavfpgf--sqtke------tvttll
sa-kaspchgtdtkpld--qaksfkwlnltegai--aeii-qinhrv---
-----prvlgswndp-aarns--kfvmgat--pallhpkna---------
------------lalsvvqklqpkp-npql------q----pyis--r--
---sdfa-igqngifq-thcmalkgrfgnhk---------dqck-----i
ksqariqkgieegfeqtld--kmg
>G
--nfsdnffetkpgahvtngkkpmlgkqqskpvygpgq------------
lew---------lkhenwp--q--sy-lritsgp-ktksy-vaggerspd
akafvtlnl--nn--kcldychaggaq---sskdmawhre---------k
a----tyyhrq------ypnndf-gkgnpgvlstefgtd--ldygh-rlf
mqygqaidqvsmpgei-qgs-------qsnlntmwqsfaigiet------
-----rc-df------------esgsa-kayskacivsnygqpegllv--
fgq-t-k-rpva-----yyigvd--sshiypyittrnpcgckydkqrtsc
yepvhtc--estsaqravrqakqt-------gylspasgsa-qllalgaf
gggfatq-a-p-------qaifkvhtv-ldvgkrpkra-------p--ph
al---g--elskhp--------------pgfmysdamp------slhptv
ra-ktvlchstatqa------ksaswiepaea----------itkky---
--------lgklsns-t--np--kfglaatk-apmlsfehsrhqt---a-
------------lavnsgqklhaspqapql------q----pyia--k--
---fdft-tkqkgvfelskcmtietrllgdh---------nkc-------
kttt-qevyaqpgfnhsldirkmg
>E
--klrdqfsetassghv-sgkklmlnk-----------------------
-ew---------lqpqkwp--e--rn-egisselekvktn-ligve----
--efvtlnlglks--k-vays--ngnnewv--kkmdwtrg---------k
s----gyyhkq------ypyndq-gqsgrgvlrnkftqn--ltygh-klf
kqlg--idgvsmggeniqaa-------nsqm---wltgnidihaven---
----yrc-dlpqgsgdyyekiveagsa-na---cymvnkygipnsllv--
kgq-t-t-ravaear--iyfgve--aspkyphktsrntc---ydnernrc
yapahtc--egsdaeratrqakkl-------eylrtaigla-kllkvgal
cggf--r-a-s-------qdifelnds-tdvggrpkna-------p--ph
sl---sggehnqqpteepatisptk--fpgaiiqdmkp------ilhplk
kaa------gaaihp------ssfa--------lavp----sishkf---
-----yralgkwadn-t--hl--kfvlatt-fpslinfkhtrhqd---tf
ylkssnllvlfllvfsvgqklhanpdapql------q----pyca--nfp
mgffnfgsvkkkgv-------svkvalisdh-itywgqcqsqcp-----q
ktra-yeitadqnfehaiear---
>A
lkklsq-ysetapgahaaagkktlltkpq----f----------------
-ewlryrtrwlgl--ekfpqadafca-ivtsavv-----w-vtgge----
--e-vtlhlgpkk--s-iay------dtwvamkgmawdkg---------k
glyatgyf-khrevcklypyara-g---------efaaggglhy----lf
geyaqgirgvtmggga-ksh-------dahi---wlseaveteatdk---
----yrv-vlergng------lqsggaqkc---gcklnktgvpddila--
kge-i-l-rkvh---talfegvd--nspkypylsahgnc---felaras-
-eavptc--dntdaelngrltke----------lvpa----kkmlkvgti
vg-f--tta-d-------edl--vhld-ttygsepktactfekakpsgpv
kl---dggqltdvpaeeptfiatdssispgflftetlq------vrqall
na-kagpchgtqpramd--qpkafkslelveddi--a---keinhkv---
-----yrafgywnnsps--al--qfvlgtt--pnllhfsnsqkda---t-
------------vtfsegqeihpns-dphl------k----qyig--k--
---fqfa-igpggtfe-akcmninvrflthh---------dqcr-----q
kpkr-iengveegfaqcld--kma
>B
lkklgq-ysetapsahadagkktllhkph----f----------------
-iw-----ralgl--ekyph-------------l-----kaitgge----
--e-itlhlgskdegt-itvccssggdtwvamkgmswdkk---------k
slyaqgyy-kh------ypyaaecg---------efsdn--lhysherlf
deyghairgvtmgggs-rar-------dahv---wlsglvdteaien---
----yrv-vldhgng------lepggaqkc---acklnktgipdgilvqh
kgq-d-q-rkvp---ttlfegvd--qspkypylsshdhc---fdlerssg
farqpacsedntdaelagrvtkd----------vvlptt--kkmlkvggl
vngf--tti-g-------kdltklhmk-ttiggepsta-------p--pa
ki---nggelednpgeepafiatasavspgflftdame------vkqail
na-kpapchgtsnraleagqakapkwlelceddi--a----einhkvkle
ndvlg----gswnnsps--al--kfglgtt--psllhfwhsqgdd---t-
------------ltfsesqelhptp-kpqlchavstk----qyin--k--
-----fs-igqggife-akcmtikarlltlq---------dqcr-----e
kakr-iesgveesmeqtlq--kmg
>node6
--kltq-ysesaptahaaagkktmlgkpk----fnhgl------------
lew-----rwlgl--dkfp--esfcn-latsaq------g-vtgge----
--e-vtlhlgpkr--t-idychpkgndawvaskgmswekgt------st-
tlyatayy-kq------ypyata-gkgdravlrtdftkn--lhygh-rif
neygqavegtalggsq-qaytnieikgdshv---rltgavttdaidnygt
vvhsyrv-vlqhgng------lqtngaqkc---gykvvktgipdglla--
kge-d-d-rkvp-----lfigvd--napkypylssrgec---fnlhrstg
lapv------ntdaeia--qtkdinkg-gvheyivp--------lkigsl
vggf--atd-d-------edltkvhss-tsyggeekta-------p--sg
kl---gageltkhpaeepgfiatakaifpgflfsqtme------tvtpll
na-kaapchgtdtkald--qaksfkwlelteadi--aemi-qinhrv---
-----frvlgswndp-nargs--kfvlgat--pallhfkns---------
------------lalsvvqklhpip-npql------q----pyis--k--
---fdfa-igqggvfh-thcmaiktrffnhn---------dqcr-----s
kskariqkgieegfeqtld--kmg
>node3
lkklgq-ysetapsahaaagkktllakpq----f----------------
-ew-----rwlgl--ekfphadsfcn-lvtsavv-----s-vtgge----
--e-vtlhlgpkk--t-idychpsggdtwvamkgmswdkg---------k
slyatgyy-kh------ypyaaa-g---------efadn--lhysh-klf
neyghairgvtmgggs-qah-------dahv---wlsgavdteaien---
----yrv-vlehgng------lqsggaqkc---gcklnktgipdgilv--
kge-d-i-rkvp---ttlfegvd--nspkypylsshgdc---fdlarssg
fapvptc--dntdaelagrvtkd----------lvpatp--kkmlkvggl
vggf--tta-d-------edltkvhln-ttyggepkta-------p--pa
kl---dggeltnhpaeepafiatssaispgflftdtmq------vkqall
na-kaapchgtatramd--qaksfkwlelceddi--a----einhkv---
-----yralgswnnsps--al--kfvlgtt--psllhfshsqkda---t-
------------lafsegqelhptp-npql------k----qyin--k--
---fqfa-igqggife-akcmtikvrllthh---------dqcr-----e
kakr-iengveegfeqsld--kmg
>node13
--kfsenffetapsahvtsgkklmlnkpq----fgpgq------------
lew---------lqhqnwp--q--ry-lritsgl-ktkss-vtgge----
--efvtlnl--ks--kcidychasgndewisskdmawhre---------k
a----syyhrq------ypyndf-gkgnrgvlrteftkd--lnygh-klf
mqygqaidavsmpgei-qgs-------esnv---wltgaidiet------
-----rc-dlrhgng------ieagsa-ka---acmvnnygipegllv--
ngq-t-k-rpva-----fyigvd--sshiypyittrntcgckydnqrksc
yepvhtc--estsadravrqakqt-------gylipasgaa-kllslgal
tggf--q-a-t-------qaifkvhtt-tdvgkrpkra-------p--ph
al---ggtelskhp--------------pgfmfsdamp------tlhpiv
ka-ktvpchgtatqa------kslswlepsee----------itkkf---
--------lgklnng-t--nl--kfvlatt--asmlsfkhsrhqa---t-
------------lafnsgqklhaspespql------q----pyia--k--
---fefg-vkqkgvfe-akcmtiktrllgdh---------nkc-------
rtka-fevtaqpgfehsldirkmg
