>C
kggp--tlnvi-shar----gqpdyctglgaedss------k-sepm---
cyy----lhtagevrk------pdvnvey---tvds---sdqa--ahdlv
agy-tl-haq-----kntekeacgfane--fppvrvagpgmntkgltytl
fveav-rgnainkaffrgn-faltgiva---ndtrgvipgaktfelqmme
mqys-----vknvqgsalhpwad-ig--eicc-yfva------------a
iylslyqggg--t----------skmvehegtalpssrdcegttrlpfpq
klkp-teaafwg-sdn-------ay-kmetkga--fdmlghgkea-lsng
eamqledcv----------qfkpae---ady-ypkqpqpkagyrgiphrs
elcw-----k---tkvcs---------ldtvlcefdkecctsafni-s--
--p-ykha------------------------srlgg----aaracdgts
-glfg----hlcp---------------hgyfvkqs-------d-egwkg
dvvrnnlgdaggaq----------epingrs-gqfs-efgwlvgaflim-
--edvwfi-lilykl-lgkl-qlalskalqll--tcidlgfgnlfs---t
kynkg-wervfcirvygrdrlavgi-vpa-eelslkswsfe
>node14
kggt--iltg---nvr----grldycialgarets------e-sdpf---
cyy----ldnsgevrkvhrskspgvnvey---svda---sasa--gpnl-
-dg-sllhtk-----ingeqhacgfaq-----ptavvnigddaaglgytv
fvdnl-mgs-rtkaifreh-famtegtggprdeqvgkip---------me
lqca-----hpnvksapvktwad-lg--hicc-ffvndlk-----rllls
fylklyk-----s-arytgnankaklvehegtglpsswesfaavklsfaq
kfkp-asvgfwg-t------------------c--fd-----mga-lstg
eamniagcvssesplgtmvqakktq---sgfaapsspqpka-ftgvqtmg
elcw-----k---mkqcs---------mdkylcafn-qccsrgfnv-n--
--p-yktlvh----------------------rklht----aasaststs
-elfg----rifp---------------kgyfvkqsh------d-edwre
aavrstlgtlgaaqgphgltal--rtinghs-aelsskf--vigaflil-
--eaawliililfty-lsii-llpmgkrlrdlsrt-tqvgfnnlfrnlg-
tygsg-wkwlfcthiysrervavge-ppc-qgfklsnwnfn
>node13
kggtqpiltg---nvrrdqngrldycia----kts------e-kraf---
cyy----lenggdvkkvnkgkspg----y---nvdaknisasa--gpnl-
-dg-sl-htq-----ingeqnasgfaq-----ptavvtvgddaaglgyt-
-vdnl-mgs-rtkavfyehsfamteetggpreeqvvnip---------ie
hqca-----npdvksdpaq--ad-lg--hicc-ffvkdlk-----rlllg
fylqlyk-----p-aryagnan-------egtgfpsawesfaavklsfaq
ifkp-asvgfwg-t------------------c--ld-----mga-lstg
eamniag-vsldaplvtmiqakktqgqnsgfaaktspipsa-ftgvttmg
elcw-----k---mkqcs---------mnkyfcafn-qccsrgfnv-n--
--pryktlvh----------------------rklnt----aaaavtsts
-elfglanlrvlp---------------kayfvkqth------d-adwrd
aavhgtlgtlgaiqgphgleal--r---gqs-aelsskf--gigaflll-
--ekawlivlilftl-lssi-llpngkrlltlsrt-tqvgfnavfqngd-
tygsg-wkwlfcthiysrervavgd-ppc-pgfklpnwnyn
>node3
kggt--tligtyknar----gqmdyctglgakdts------r-cepf---
clyp--flnnsga-rk------pgvniey---tmds---rlqa--gpna-
-dy-tllhek-----rntakqgcgfanniawppvqvvaigmdaagltfsv
fvesf-mgs-itkgffreh-famagsta---daargpip---------me
mqcd-----vpnvkgiavhtwae-lg--qict-llvadlk-----kllls
vylelykgggass-aryt-qngktkmaevegqglpssrerfaavrlsfpq
kfkp-savgfwd-snt-------sy-klevkgc--fe-----mta-lstg
iakqledcv----------eikpaq---adfaqsaevqpkatlrgsdssg
elcw-----qdgsanvcshstpnrsksmdtilcafnkecctrgfnv-t--
--p-yknavh----------------------sklql----garacsatv
-elfg----hiyp---------------qgkfvkps-gvaldhd-qawre
dvva-------gaq----------rsinghs-gqls-el--lvgpfivl-
--eavhlitlflfkl-lgkltllpigkplrtlprtcsdlgfgnlft----
kydkg-wnwtfcih-ygrdrvtvge-vpt-qgfslkswtfs
>node15
kggt--tligtyrnar----gamdyctglgarets------k-sepf---
cyy----ldnsgdvrk------pgvnvey---tvda---sapa--gpnl-
-dg-tllhgk-----ingerhgcgfane--fppvavvnigedaagltytv
fvdnl-mgs-rtkaffreh-famtggta---ddavgkip---------me
mqcd-----hpnvkgapvnawae-lg--hicc-ffvadlk-----kllls
fylllyk-----s-arytgesnkakmvehqgtglpssrerfaavrlsfpq
kfkp-asvgfwg-tet-------syckleaksc--fd-----maa-lstg
eamqiqgcvsseaplgtnaqakpaq---agfaqpsspqpkatftgtqtmg
elcw-----k---mkqcs---------mdtylcefnkqcctrgfnv-s--
--p-yknlvh----------------------rklql----aasactats
-elfg----hifp---------------qgyfvkqs-------d-qawre
dvvrntlgnlggaqgphglgvl--rsinghs-gqls-kf--ligaflil-
--eaawliililftl-lgii-llpmgkrlrtlprtctdlgfgnlfrylg-
tygkg-wnwtfcthiysrdrvavge-pps-egftlsnwnfs
>node7
kggt--tligtyrnar----gqmdyctglgakets------r-sepf---
cyy----lhnsgdvrk------pgvniey---tvds---saqa--apnl-
-dy-tllhgk-----rntekqgcgfane--fppvqvvaigmdaagltytv
fvesi-mgs-itkaffreh-famtgkta---ddargkip---------me
mqcd-----vpnvkgapvhawae-lg--qicc-yfvadlk-----kllls
iylllykgggass-aryt-qnnkskmvehegtglpssrerfaavrlsfpq
kfkp-aavgfwg-snt-------sy-klevkgc--fe-----maa-lstg
eamqvedcv----------qtkpaq---adfaqpkspqpkatfrgsdtsg
elcw-----k---akvcs---------mdtylcefnkqcctrgfnv-s--
--p-yknavh----------------------sklql----aaractats
-elfg----hiyp---------------qgyfvkqs-------d-qawre
dvvrdslgdmggaq----------rsinghs-gqls-ef--lvgpflil-
--eavwlitlilfkl-lgkl-llpmgkplrtlprtctdlgfgnlfs----
kydkg-wnwtfcihiygrdrvavge-vpt-qgftlkswsfs
>A
kgg---tligtyknar----gqmdycfglqaykta------r-cdpf---
clypapflnisga-rk------pgveiey---amds---rlqp--gpna-
-dy-dllhen----------qgcgfannilwspiqvvpigmdaagltfsv
fvesf-mgy-itkglfreh-fpmaggtt---daargpip---------me
mqcdgvarsv--vkgisvntwae-lg--qict-llmadlg-----kllls
vylelyrggaassraryt-qggptkmaevegiglpssqersaavklsf--
kfkp-savgfwdpsnsektacasp------------e-----mta-lctg
vaklledci----------aikpaq---adfaqtaevqpkatlrqsdssg
elcw-----qegganvcthgapnrgksmdtivcafnkecctrgfsv-t--
--s-ykqavh----------------------sklql----gkracsatv
-esfa----hiyp---------------egkfvkps-gvaldha-qawke
nvva-------gaq----------rsinghs-apls-el--lvgpfiil-
--davrlitlflfdl-lgklttlpigkplptlrrtcselgfanlft----
kydkg-snwtfcih-ygrdrvtvgs-vkt-qgfslkswtfg
>D
kgga--tlaatyrhga----aqmdyctglaaedtsllegkrk-sepf---
cyy----lhtagdvrk------pevkiey---tves---sdqadcahdl-
-dy-tl-hak-----rntekegcgfane--fppvrvagqdfhsigltytl
fvesi-rga-iskaffrdh-maltgkva---ddargvip---------mk
mqcd-----vphvesatlhpwan-ig--qicc-yfva------------a
iylalydgggatq-try--------mvehegtglpssrdsigtvrldfpq
kfkp-saaafwg-sth-------ay-kmelkgt--fdrlghgadaklstg
gglqvedcv----------qfkpsq---adf-ypkqpqpkagfrgaasss
elcw-----k---vkvcs---------mdtvlcqfnkdcctsgfnn-r--
--p-ykha------------------------sqlgl----aardcdgts
-glfg----hlcp---------------qgyfvkrt-------d-dgfkd
eivrdnlgdmggaq----------raiaggs-gkf-------igaflim-
--eaawlt-ltlfk----kl-qlpmskplrtlprtmkdlifgnlfs---t
kykkg-wewtfciriygkarlavvq-vps-qafslkswsya
>node6
kggs--tlnatyrnar----gqmdyctglgaedts------k-sepf---
cyy----lhnagdvrk------pevniey---tvds---sdqa--ahdl-
-dy-tl-hak-----rntekegcgfane--fppvrvagqgmnaigltytl
fvesi-rgs-iskaffrdh-faltgkva---ddargvip---------me
mqcd-----vpnvqgatlhpwae-ig--qicc-yfva------------a
iylalyqgggast-tryv-nnnkskmvehegtglpssrdsegtvrlsfpq
kfkp-taaafwg-sdn-------ay-kmevkga--fdslghgmda-lstg
eamqvedcv----------qfkpaq---adf-ypkqpqpkagfrgsatss
elcw-----k---vkvcs---------ldtvlcefnkecctsgfnv-s--
--p-ykha------------------------srlgl----aaracdgts
-glfg----hlcp---------------qgyfvkqs-------d-egwkg
dvvrdnlgdmggaq----------qpingrs-gqfs-ef--lvgaflim-
--edvwli-lilfkl-lgkl-qlpmskplrtlprtcidlgfgnlfs---t
kynkg-wewifciriygrdrlavge-vpt-qgfslkswsfd
>E
kggt--iltg---s-------rldyciaqgaresv------nspd-----
-------lddrgderkvhk-kapgsnvey---gada---gaks--sskl-
-sg-sllntk-----idgeshsygfar-----pttvtnvgddatglgytv
pvenf-lgg-rskaifrth--amtqg-ggprgetikktp---------ma
lhca-----rpnnksarvkawad-lghlqi----------------glas
fylkvyk-----s-gayidaakkarlvehe-kdlsgswqsftavrlafar
kfqp--avgfwg-t------------------vnrfd-----kng-ltts
namllassvssesslgtviqakktq---svfvaptksqpka-fkgiqimg
elcw-----k---mkqcs---------kdkylcafn-qccsrgfnv-n--
--a-fktlvh----------------------kklht----aesistsag
-evfg----rvlptk------apvnclvkgyfrkei-------a-adwrd
aaiksrlgtlgdaanphslaalyirgingct-aelnskf--llgafmilf
hanaawliiwiffqy-lsii-llam---i--------------lfrdlg-
tfgsg-wtwefc-riysqesnpvge-ppc-qgfklsnwnfn
>node10
kggt--iltg---s-------rldyciaqgareta------dssd-----
-------lddsgderkvhrskspgvnvey---gvda---gaks--spkl-
-sg-sllntk-----idgeqhscgfaq-----ptavvnigddaaglgytv
fvenl-mgg-rtkaifrah--amtqgtggprdesvkkip---------me
lqca-----rpnnksapvktwad-lg--hi----------------glls
fylklyk-----s-aryignakkarlvehe-tglssswqsfaavklsfaq
kfqphasvgfwg-t------------------v--fd-----msg-ltts
namniagcvssesslgtmvqakktq---sgfvarskpqpka-ftgvqimg
elcw-----k---mkqcs---------kdkylcafn-qccsrgfnv-n--
--p-fktlvh----------------------kklht----assastsas
-evfg----rvfptk------apvnclvkgyfvkqah------a-aewre
aavrstlgtlgeaqnphglaalyirtinghs-aelnskf--llgaflil-
--eaawliiwiffqy-lsii-llpmgkrlrdlsrt-tqvgfnnlfrdlg-
tygsg-wtwqfc-riysqeseavge-ppc-qgfklsnwnfn
>F
kggt--vltg---s-------rldyciaegapetg------dste-----
-------lddsgderpvhrsksagvavey---tida---gsks--spkl-
-sgssllntk-----idgeqhscgfaq-----pspltkigddtaglgytv
fvenl-mgg-rskaifrah--amtsgtggprdesvkkip---------me
lqca-----rpnnksapvkawadslg--hi----------------glls
fylklyr-----s-ary-gnakkarlyehe-tglrsswlafaavtls-sq
kfnphasvgfwg-t------------------v--fd-----msg-ltss
nam-iggcvssea-lgtmvqakrah---pgfaarskpqpda-ftavqimg
elcwrfsakk---mkact---------kdgylcpfs-qccnrgftv-n--
--p-fkvlch----------------------kslht----assasssss
-dplg----rvfptkkqyqplapvdclik------ah------v-aewwq
aavrstlgilgdaknphglaalyvrsinghs-aglndtf--llgtflvl-
--daawlviwif----lsii-llpmgkrlvg--------gfnnlfrdlg-
tyggg-wtwqfc-riysqdmeavgelptc-qgfklsnwnyn
>G
kggvqpiltg---nvrrdqhgrldycia----ktt------e-krgfrkk
cyy----leggsdvkkvnkglspg----yhdenvdaknvsasd--gpnl-
-ng-sl-htnqfhgpvqgeqnasgfsq-----ptavvt---dttalgyn-
-vdnlamgs--tkgafyivtfamkeetgapheeqvinip---------iq
pqca-----npnvkmdpaq--ad-le--hncc-ffvkdlk-----rallg
fylqlyr-----p-aryaghan-------egtdfplawesfaavklgfaq
ifkq-a--afwg-s------------------c--vd-----mga-lsns
hamniga-vsletplvtmicakktpgqnsgfpaktspipst-ftgvahmg
elcw-----k---lkqcs---------tytyfcafn-qccsrgfni-nsd
kstryktnvh--lhsesrkhtvekiikryykprklntaqksasavaacts
nelfglsnlrvlp---------------kayfvkqte------dtsdwrd
salhgtlgtlgsvqnpheleal--r---gqn-veksssy--gigafllm-
--akawlivlilfql-lssi-llpn--rllslsra-sqvgfkavfqhaa-
tyggg-wnwlncthiysrervavad-ppc-kgfslpnwnyn
>H
kgglqpiltg---nvrrdqngrvdycha----kts------e-kraf---
cyy----letagevnkisksksps----y---nvdqknvsas------l-
-dg-sl-htq-----ingeqgypgfeq-----ptavvtvgdeaavlgyt-
-vdnl-kgs-rtkavfyqhsfaetegtggpreeqvvnip---------in
hqca-----nsevkknpaq--ad-tg--hicc-ffvkdlk-----rlllg
fylqmyk-----p-arysgsan-------egalfpsawesfaavklsfap
ifkp-sgvgfwg-t------------------c--vd-----mgg-lstg
daigiag-vsldsplvtmiqakktqgqnsgfaaksspippl-fsrvttvg
elcw-----k---mkqcn---------mdpyfcafs-qccsrgfnv-n--
--pryqtlvhqn--------------------rkldt----avaavasns
-glfglsnlrvlp---------------kayfak-------------wrd
egvqgtlgtlsaiqgphgleal--r---gqsvaelsskf--digaflll-
--ekawlivlivltl-lssi-lspngkrlltlnrt-tqvgfsavfqngs-
tygsglwkwqfcthiygreritvgd-pnc-pgfklpnwnyn
>B
ksgt--tlignyknar----gqmdycvglgakdta------r-ceaf---
clyp--f---sgv-kk------pgvniey---tmds---slqa--gpna-
-dy-illher-----rqtakqgcgyanniawnpvqvgaigmdaagftysv
fvesf-mgn-itkgffheh-ftmaakia---davrgpip---------me
mqcd-----lpnvkfiavrtwae-lg--qictkllvfdvkllcivk--ls
vfmely--ggass-akyt-kngktkmadppgqglpssperlaahrlsf--
--kp-savgf---snt-------sy-klevegc--fp-----mtv-lstg
iakqledcv----------qilpaq---aefgqsaevgpkatawgsdssg
elcw-----aegsanacshttptrskcldtvlcefnrecctrgfnvht--
--p-yknfvq----------------------sqlqn----haracsatv
-elfg----hiyp---------------rskfvkps-gv-----------
------------------------rcinghs-gqls-kl--lvgp--vl-
--eavrlitlflfrlv-grltllpigkplrtlprvcsdlgfgnlft----
kydng-wnwtfci---grdrvtvae-vstiqgpslkswtft
