>node7
eyakgh--qd-l---------------------------sldfft-ai--
-----gv--vgqclatgavsy------------kirldpaqsgqccnmk-
rl-c----y-------------sknckdta---nq--------agkl---
-----sdvn---ar-efektr-----ype--geayagkvsh--ghftatv
ql-tp--ctsismskcvk--pklnkkvwtkeytlivist-----------
gkdstlvtpgnktgdyegi-------a--l-gk---ysgl---glvntvh
l--fdimvedenlgplchvssetglql----gq-----------------
----py-----nv--lvggrlv--rqkdf--wgg--lg-pai--slrhhq
vk-kcgvafkvksarggrvsq--adgcl-glsl--etkvkfkeytgql--
----fn-vyaekg----trlavvtrq-lfdtemgh--qglng-----etf
--------q-efkldka--------s--v--tclla-----ql-----lg
-ldsnrklkeqd-ver--ryqpr---qecplph-eivasfnnt---dltg
srlyavtkv--ikhagslkcplsfellhlyedrdllvehllvvtafvp--
-vpvfn-----llhtwkfg--rpnvelha-algqylv-tkk----wh---
-------sh--vlsl-pvelcg-s------dett--s-------ps-vpy
naakekevlvagtdwqtschifd------cva-grlt--gl---lq-f-l
-d-----
>B
eyakghkgqd-l---------------------------gldarg-at--
---scgv--vgqcllnggvsy------------likldpalrglcceva-
rl-c----y-------------gg----ae---nq--------ngkl---
--kyvsdvn---ar-efqktk-----ype--vqavtgevsh--gffaviv
ql-sp--ctaismkkcvk--p---slvwtkeytlivitt-----------
gldstlvttsdrtgqidgi--cmaagical-gd---yp--------dtth
l--fevmvdgdnsveicpvs-----ql----gqrtpaalhlivfcli---
----py-----nl--lvgar-v--rqkey--wgg--lg-------lrhhq
gk-kckvdfkvkqargghvtqhsldgcl-gvsl--dtkadfkeyssql--
----fn-ayadgg----trliiitra-lfdvelvh--qg-mg-al-----
-pihfrvrq-qfkleka--------s--v--tcgla-----ql-----lg
-lk---------------ryqpq---tecaiah-dviasfedt---dlag
p----vtkv--iknggalncplsfallhlyedrsllvehllvvtafvp--
-vpvfg-----llhswkfgetrpniqlh---lgdyqaktkk----whcna
vdgrkgsnf--vlel-paelcg-a------dest--s-------et-vmy
dqakekealpdgpdwqtschifn------cia-grlt--sl---lk-f-l
qd-----
>A
eyakghngqhdl---------------------------gldffg-ai--
---scge--vgpclliaavsr------------ltkldpadrgqccnmn-
rl-c----yvhlaspvekpwqhpkackdta---nd--------ag-m---
--kyvsdgn---ir-dfqknkvvrpnypd--qealtgevah--sffsllv
ql-gp--ctaisknkcvr--p---klvwtkaytliaist-----------
gkdstlvasgnktgqfegi--cmtagicll-gk---ypga---elvdtth
l--fqvaveddnsvpicpvssepalml----gq--------------lrv
tvmhpy-----tl--lvggrlv--rqkey--wgg----------alrhhq
gk-kckydfkvrearggrvsqhafdgal-glsl--dtkekskqytsqlgv
raldfn-alaekahgadtrllsvtrq-lfdvqmvhwyqglmgsalaletf
hpihfrvrq-qykldkg----kyhps--v--t---a-----ql-----lg
-lkterkrkeqd-vrr--rykpp---tecplah-aiiagfedt---akig
p----vtkv--ikhsgaldcplsiallhlyedrallvehllvvtafvp--
-vtvfg-----ll-swkfa--rpnvemh---lg-yqakvrt----lh---
-------sf--vlel-paelcg-q------detv--s----ptlps-vpy
naatekealpqgpdwqtschifn------cia-grlt--sl---lk-f-m
qdsifpp
>node3
eyakghngqd-l---------------------------sldffg-ai--
---scgv--vgqclltgavsy------------likldpaqkgqccnma-
rl-c----y-------------gknckdta---nq--------agkl---
--kyvsdvn---ar-efqktr-----ype--veavtgevsh--gffsvlv
ql-sp--ctaismnkcvr--p---klvwtkeytlivist-----------
gkdstlvttgnktgqfegi--cmtagicll-gk---ypga---elvdtvh
l--fevmvdddnsvpicpvssepglql----gq-----------------
----py-----nl--lvggrlv--rqkey--wgg--lg-psv--slrhhq
gk-kckvdfkvkearggrvsqhaldgcl-glsl--dtkdkfkeytgql--
----fn-ayaekg----trllavtrq-lfdvemvh--qglmg-alaletf
hpihfrvrq-qfkldka--------s--v--tcgla-----ql-----lg
-lksdrklkeqd-vrr--ryqpp---tecplah-eiiasfedt---dltg
p----vtkv--ikhagaldcplsfallhlyedrallvehllvvtafvp--
-vpvfg-----llhtwkfg--rpnvelh---lgdyqaktkk----wh---
-------nf--vlel-paelcg-s------dett--s-------ps-vpy
naakekealpegpdwqtschifn------cia-grlt--sl---lk-f-l
qd-----
>E
eyakpq--le-l---------------------------nykd--eslvd
rkt--gikaagqclltgivsy------------nsrldpaqpgqccnqk-
tdlc----y-------------akeck---gpkn---faikrnagkl---
-----tnvlrctnnaqfekss-----ftkhkggafagsvfh--ghf-nsv
elrtp--ctseveskcvksksklddkvwfkqytllvvtaynk-------l
cknpal---gattaayeaige-----t--l-gr---fagaggmgv----p
v--fel------------v--qthiqlkt---------------------
----sn-----dd--l----mvrcgqkklqkskglrlnhpal--tlrvhg
vir---srfevgsaqvgki------gcl-alaqtlenkqsfreftgll--
----fdigyadrg----tamsvikrq-vl-npmnh--qg-----------
--------q-vytadkg--------s--n--kvl-a-----ha-----rf
-ldsskrlkqq--ikk--ryqpk---qksplpn-dvaic--nk---avtg
srly-vtav--nkhaarlkcp-rfnsfhlyndh-lledflvvvagrvptf
nvpafn-----llqkwpfg--rl---lhp-lrgqllv-tdktaykrh---
-------ce--iltl-pae----slnfadsseat--sgvpl---ps-apy
eqlkdkevlveesdweakchiid------citagklt--elklskqdlhv
-n-----
>H
dylkgq--rd-lqvlnlgveqpfifknvgrnllvtsmpysydafp-klag
rrt--gi--gglcl-tgavsyhqgrlegyyvgcntrrdhaqrgqschmk-
sslckken----------------ecr------d---lgvkrka--l---
-----tavsrctaqerfetsk-----fas--ggasagkvfh--ghf-stv
slstpkvc---------k--aklenkswfkkftllvvap-----------
ekectl---gts-gaypav-------a--lggp---ysat---aa----p
r--fgnivenmnlg---hvhsstnlalkgkfae-----------------
----pd-----dv--liggri-----kslqkwdg--lgkpaf--elrhhq
vkrhcssklkvgpgllgkvaq--gagcl-glae--etkikfkdftgll--
----fnagyrdra----tvfslvkrsf---apmgh--pgvdg-----tgf
--------qhdyaglkt--------g--ivpkvl-a-----ql-----ly
-lnsnrrlkeqdtikk--knqpkyehqdcplpn-evittypdt---smts
srly--tkv--hkha----cp-sfeilhlysgqelkadlllvvagvvp--
-vpafs-qndalihkwpfk--kl---lfp-vlghllv-akksaykrh---
-------st--vetl-sge----s------nenaiil-------pp-apy
apll---vlvaasdweskchlre------cls-srlq--dl---kegflg
-q-----
>node13
dylkgq--rd-lqvlnlgvgqpfifknvgrnllvaampysyenfs-klad
rkt--gi--vgqcl-tgavsy------------ntrldpaqrgqcchmk-
sdlctken----------------ecr------d---lgvkrkagkl---
-----tavsrctaqarfetsr-----fts--geacagkvfh--ghf-stv
slstp--ctaism-kcvk--akldnkswfkkfsllvvap-----------
qkdntl---gtstgdynai-------a--lggp---ysaa---gl----p
r--fasivehmnlg---hvnsntnmplkgkfge-----------------
----pn-----ev--liggrl-----kslhkwkg--lgrpaf--alrhhq
vkrhcssklkvgsglvgkvaq--gdgcl-glaq--etkvkfkeftgll--
----fnagyqdra----tvlslvkraf---apmgh--pgldg-----tgf
--------qneyagdks--------g--i--kvl-a-----ql-----lf
-ldsnrrlkeqdtikk--ryqpkyedqdcplpn-evittysdt---svts
srly--tkv--hkhaarlkcp-sfeslhlysnqelkadyllvvagivp--
-vsafnvqndallhkwgfk--kl---lfp-vlgqllv-tkktaykrh---
-------st--vetl-pae----s------nektiil-------pp-apy
apll---vlvaesdwetkchlke------cls-grlq--sl---kqgflg
-q-----
>D
qlvegn--qd-l---------------------------tlnfft-ai--
-----gv--vntclatg----------------kvklela-sghcc-mde
--------y-------------skncrdta---ds--------tgqlqll
gv---sav--------fgkar-----fpg--g--------h--gnftati
ql-tp--cvsitkskcvk--pkllkkvwareftlivist-----------
geqstlvtpssetaeyagv-------v--l-akgmqyngl---gvink--
----dvmvddknlgplchvsmetgl------th-----------------
----qy-----nvlelvggwvv--rqknf--wmg--lg-ppvasslqqhk
vk-kcgvifkvppvkgarvsq--gdgcl-klsl--elkikfrac-gvl--
----yn-vygqka----tslavgtre-vfdtemah--qning-----ndp
--------q-eykldsg--------t-----tclla-----ql-----lp
vldssrllkged-vgrcarydar---necpv---eilvsesnt---edvg
armyavkkp--arhvg-----lavevlhlfedkellvdhllispsfva--
-vpvyn-----llhswkfg--rpsvqlhaa--gqylv-skk----wh---
-------sh--vgsl-pvelcget------dett--t-------psiapy
gaakekevlvastd--------------------rlt--nk---le-f-i
-t-----
>node6
qwvdgh--qd-l---------------------------sldfft-ai--
-----gv--vgtclatg----------------kikleiaqsgqcc-mde
--------y-------------sknckdta---ns--------tgql---
gv---sav--------fgktr-----fpe--geayvgkvth--gnftatv
ql-tp--ctsitkskcvk--pklnkkvwakeftlivist-----------
gedstlvtpgnktaeyagv-------a--l-gk---yngl---gvvnk--
----dimvqdenlgplchvssetglql----tq-----------------
----qy-----nv--lvggwlv--rqkdf--wmg--lg-ppi--slqhhr
vk-kcgvifkvspakgarvsq--adgcl-nlsl--etkikfkec-gel--
----fn-vygdkg----tplavvtrq-vfdtemgh--qging-----etf
--------q-eykldkg--------t--v--tclla-----ql-----lp
-ldsnrllkeed-vercrrydar---qecpv---eivasisnt---epvg
srmyavtkn--frhvg-----lafevlhlyedkdllvdhlliatafva--
-vpvfn-----llhswkfg--rpsvelha-algqylv-skk----wh---
-------sh--vlsl-pvelcg-t------dett--t-------ps-vpy
naakekevlvastd--------------------rlt--gl---le-f-i
-d-----
>G
dylkgq--kd-llilsfgvgqpfvfknvgpdllg-ampyhyqnfs-klgd
hkn--gi--vgqc---gavcy------------nvrldpaev-----ge-
ndlctkes----------------eck------d---lgverkagkl---
-----tsvsrcadqarlensr-----fvs--gqacagksfh--ghf-skv
slsap--ctaism-kcvk--tklehkswfkkfsllvvap-----------
qkd-tl---gttigdynai-------a--ldgp---yga-----------
------ivehmdlg---hvnsntnmllkggfgp-----------------
----pnvdvggev--liggrq-----ksihkwkg--larpaf--alrnhq
vgrhcssklkvgs------tq--gdgcl-glaq--atkvkfkeftgll--
----fnagyqera----tvlklvkraf---lpvgv--agmdg-----tga
--------qnefadeknakcm----g--f---vl-atggllal-----lf
-ltadsrlqkqdtikk--ryrpkyddpecplpg---ittyadtrhl--ts
srly--nkv--hkhqarlkcp-sfeslnlysnkelkasyllagagivp--
-vaafsvqndallhkhgfk--kl---lfp-vlghlla-tkktaykrh---
-------st--vetlqpye----s------nektr---------pp-apy
vpll---vlvaesdwetkchkkepkgh--sls-greq--sl---kqgflg
-q-----
>C
qrvdgh--qd-l---------------------------glefft-av--
-----gv--igtclatd----------------krdleiaqagqcc-mde
--------y-------------sknvkdta---ns--------aeql---
gv---sav--------fgktr-----fpe--gaayvdkvsh--gtytatv
ql-sp--cttrtkskcvk--pklnkkvwaseftlaivsa-----------
dedstlvtpgketpeyagv-------a--m-gk---yngl---gvink--
----di-vqdqnlgplcpvssetglqv----gq-----------------
----qy-----nv--lpgqwlv--rqkdf--wms--lg-ppi--glehhr
vk-kcgivfkvspakgartaq--aqgclfsltl--dtqikfkec-gel--
----fn-vygdkg----tplavvtrq----teqgh--pgvng-----etf
--------q-eykldkg--------t--v--tclls-----pl-----lp
-ldsnrllkeed-vercrrydar---qscrv--epivasisdt---epvg
srmyavtkecgfrhvg-----lafavlfl--dkellvdhllvatafva--
-vpvfn-----llhsw---------elsa-alnqylv-skk----wh---
-------shaavlsl-pvnlcg-t------deat--t-------is-vpy
naanekealvysta--------------------rlt--gl---lq-f-i
-d-----
>node10
eyakpq--qe-l---------------------------nyen---slvd
rkt--gi--vgqclvtgivsy------------ntrldpaqpgqcchqk-
tdlc----y-------------akeck------n---faikrkagkl---
-----tnvsrctshaqfekss-----fte--gsafagsvsh--ghf-nyv
elstp--ctsiveakcvk--pklddkvwfkqytlivvtaynk-------l
cknaal---gtttaeyeaige-----p--l-gr---ysgaggkgv----p
s--feiilehanlg---hv--dtdiqlkskyge-----------------
----sn-----dd--lisgrlvqcsqkklhkskglrlnhptl--tlrhhg
vkrhcssrfkvgsaqvgkiaq--gdgcl-alaqtletkqkfreftgll--
----fnagyadrg----tamsvvkrq-ll-npmgh--qg-----------
--------q-eytgdkg--------s--n--kvl-a-----qa-----lf
-ldsnrrlkeqd-ikk--ryqpk---qdsplpn-evais--nk---avtg
srly-itkv--nkhaarlkcp-rfnsfhlyqdh-lledylvvvagnvptf
nvpafn-----llqkwsfg--rl---lhp-lvgqllv-ttktaykrh---
-------sp--iltl-pae----s------neat--sgvpl---ps-apy
ealkdkevlveesdweakchiid------cltagklt--slk-gkqdllv
-n-----
>node14
eyakgq--qe-l---------------------------syenft-slad
rkt--gi--vgqclvtgvvsy------------ntrldpaqpgqcchmk-
sdlc----y-------------akeck------n---lgvkrkagkl---
-----tnvsrctahaqfeksr-----fte--geayagkvsh--ghf-stv
elstp--ctsismrkcvk--pkldkkvwfkqytlivvta-----------
skdntl---gtktgdydai-------p--l-gr---ysga---gl----p
l--fdiivehenlg---hvqsdtniqlkskyge-----------------
----pn-----dv--liggrlvqcsqksfhkwkg--lgrptl--alrhhq
vkrhcssrfkvgsaqvgkvaq--gdgcl-glaq--etkvkfreftgll--
----fnagyadrg----tvlsvvkrq-lf-apmgh--qgldg-----agf
--------q-eytgdkg--------s--i--kvl-a-----ql-----lf
-ldsnrrlkeqd-ikk--ryqpk---qdcplpn-eviisfsnt---avtg
srly-vtkv--nkhaarlkcp-sfeslhlyqdqelledyllvvagivp--
-vpafn-----llhkwgfg--kl---lhp-llgqllv-tkktaykrh---
-------st--vltl-pae----s------nett--l-------ps-apy
ealkdkevlvtesdwetkchiid------clt-grlt--sl---kqdflv
-q-----
>F
-yakpq--qe-l---------------------------hyen---thvd
kst--gi--vgqclvykivsy------------slrltpnhpgqccdhk-
tdlc----y-------------tgecr------n---faikrkagkl---
-----sevsrcnshaqfeksc-----ftd--gddfagsvshhtghf-nyv
elsta--ckalvedkclk--pklddsvwfkqytlmvvtsynkrwagkfkl
sknypl---gtttaeyeaiae-----p--l-gr---ysgaagkgv----n
kvlfviifehanlg---hv--etnielkskyge-----------------
----sd-----dd--nisgrlvqvsqkklhkskglrlnhptl--dlrhhg
vkrhcstrfrvgsaqvgktaq--gdgcm-alaqaletkqkfrtftgll--
----fnagygdrg----aamtvvkhq-ll-npmgh--qg-----------
--------q-dytgdkg--------shnl--kvl-a-----qalestglf
-ldqdrklke---ikn--ryqpk---qdsplps-evais--kk---avtg
srly-ittv--nkhaarlkcp-kfnsfrlyqdh-llddylvvvagt----
-----------llpkwsfg--rl---lhs-lvgqllv-ttktafqrh---
-------tp--iltl-pae----s------heat--agvpl---ps-apy
ealrekevlveesdweakchtsd----dachadgrltvkslk---qdllv
-n-----
>node15
eyakgq--qd-l---------------------------sldfft-al--
-----gv--vgqclvtgvvsy------------nirldpaqsgqccnmk-
snlc----y-------------aknckdaa---ntgtlg--rkagkl---
-----tnvnkctahvqfeksr-----fte--geayagkvsh--ghftttv
elstp--ctsismskcvk--pklnkkvwfkqytlivvsa-----------
gkdttl---gnktgdydgi-------a--l-gr---ysgl---glvntvp
l--fdiivenenlgplhhvssetglql----ge-----------------
----py-----dv--liggrlvqcrqkdf--wgg--lgrpal--alrhhq
vk-kcsnrfkvksaqvgrvsq--gdgcl-glal--etkvkfreytgtl--
----fnavyadkg----trlavvtrq-lfdtqmgh--qglng-----etf
--------q-eytldka--------s--i--kcl-a-----ql-----lg
-ldsnrrlkeqd-vkr--ryqpk---qdcplpn-eiiisfnnt---dltg
srlytvtkv--ikhgaslkcp-sfellhlyedkelladhllvvtgfvp--
-vpafn-----llhkwgfg--kl---lhp-llgqylv-tkk----rh---
-------sh--alti-pad----s------dett--f-------ps-vpy
eaakdkevlvtesdwqtschiid------clt-grlt--nl---lqdf-l
-d-----
