>F
yalaineakyealgladereapklegaemmegmvpgg--------shwgh
qskha------wlvissccrpvlgdslgsrhgafcsk-----sv--htrl
s---is-----qvrdhysy--dkvtrpyf--rvlkgdir----cyypalq
v--igna-sppp---pqtfygakelekaeaspfhk--ikqhsllafpgrk
----dfttg-----mleqpg-gga--f--kpk-------vmfglyvlml-
-at----rh-egsacvtgtlgaacg-g---cskevv--------vqdnad
yeigkprcilk-dnavefdeafekkdgnldfe---------qkrvv----
qkg-itrvffscdkknp------gcs--aaknsgsedadgc-vcsgttr-
-------l-------vise-trggqrkkg----karie--gkydksnekk
v--qkpc------celrrpqwls------pmlastg-------grmladg
kiik----------------ys----niph--ihg--ctdytwktkipge
---geayaksvpgpi-psfecktelslh-y--hktg--------nsvevh
heq-t-------------vst-lnsvaktqgpvldyseltlgp--as---
aegy--ca---yvkgkgycksnpmlv-------cmgg--etdaplpta-v
khvqgg-rccstgit-kpvk---------------rf-sveseadhl
>node3
faltidqakeg---lk--qeagqleggktmdrqvadgcg--cvrlgvwgh
asaha------rlsiags--ahvgnslgaklgawca-----aiv--ssrl
t---vs-----kvkesfng--ekvgttfl--rl--ndfr----ctyyk-h
l--lggcpsppt---eldfystt--akgeassfrk-ekkeysmlgfpaka
fdekklrtg-----qreqsa-gvs--f----r-------v-----lvll-
-sl----kkqdgsgcvas-----dg-g---c--qvvrsvkciegvhesak
aesgkascllk-qlav-f---vsgkdaah-fenaqn-----ldktl----
drs-idkylfpv----p------gc-caaa---------gc-acwgvat-
-------l-------tmrg-drgakrkkg----rqrvd--ak----eqtq
vtlv--c-----ssqiarpfwasvvgedapm-aetnkgaaycgarmldgg
tvik----cr----f----ifg----ii----------------idlpse
laage-fp--eesnlkptfscklnflld-y--hasi--------apadvq
avn-k--kafrallllepvaa-lqslsktpgdvlny-vlalsp--pn---
aqay--cpqhgyksgkdyc------a-------clgf--eddsprgvg-v
khvqgghrcgsnsis-ktvaimfhdd------agvkt-avdra---m
>B
yaltidqayeg---lk--qdagqleggktmdrqvadgcg--cvrlgvwgh
angha------rlsipgs--ahvgnalgaklgawca-----aiv--ssrl
t---vgaaghtkikesfng------ttfl--rl--ngfr----ctyyk-h
l--lagcpappt---eldfysts--vrgeassfrk-ekkeysvlgfpaks
f--kklrpg-----lreqsaegis--f----k-------v-----avll-
-sl----kkqdgsgcvas-----ng-geapc--qvvrlvkciegvresak
hesgkascllk-elvv-f---vfgkhaaq-fdngqn-----ldksl----
drs-idkylfkv----p------gc-capa------------acwpvat-
-------l-------tmrg-drdakrkkg----rqrvd--gk----eqtq
vtlv--c-----taqiakpfwasvvgedapm-aet--rtaycgarqldgg
sivk----cr----ftlrqifg----ii----------------idlppe
ltage-fp--essnlkptfacklnflld-yel---i--------apadvv
avn-k--kafralllldpvaa-nqslskipgdvlny-vlalsp--pn---
sqtyaycpqhgyksggdyc------a-------clgf--kddppegvgav
khvqggercgnncis-atvaimfhdnlgctplagvkt-avgra---l
>D
fgltldqlkdg---ld--qaegalegpkam------------vqlsgwgh
ntkna---eyqrlsigts--ghiektlsarlsawcp-----cia--daal
t---vs---------sfeg-------tff--rllkndl-----------h
l--lnncaipgt---ereftrt---argdagpfrk-ekleasahvgpgks
lgdaklr-------qa------------------gklkdv-----avll-
-n-------rdgpqcias-----tg-g---p--dvsrtvrcvdgvhepsk
yetgktlclktg-----------gkdagq-fsnaqd-----mgkal----
eksek-aylysc----p------ac---ai---------nc-gcwglpt-
-------l-------imra-tkgakrrkg----rkkvq--ak----eesh
vtnv--s-----rsaigkp--aavvgesld----tnkgptycaahmmtgg
rtdrvyrgcs-----------prpqnti----------------ldlpse
lavserfs--aqsalapifsckltf--------asi--------np-avq
pcn-keg-----------vts-lstlakdpgpvlsstmlaldpcfp----
---y--cp---ylhnkdyc------g-------clgf--eeednpp----
---qsg-rcghdgms-ksisfmhhqd------ggvrykavers---l
>C
fnltqdqikeg---lg--eeegpvegpktm------------vrlsvwgq
ntkna------rssigtt--ghigkslsarlsswca-----civ--nasl
t---vs---------sfdg-------tffklrllkndl-----------n
l--igdcgvpgt---skefaatt--argdagpfrk-dkreyslhvgpgke
lgegklrta-----qre----gqtalf----hedgklkdl-----ivll-
-n-------rdgseclas-----tg-r---p--dvsktvkcvdgvhassk
ye---tfclih-elgv-f---vagknagh-fenaqd-----mskkl----
ersdkdqynysc----pygitvrgc---gl---------gc-vcwglpk-
-------l-------ilrg-tkgakrkkg----rskvq--ak----qqah
vvdv--c-----rraigkp--aavigeplgm-tdtnkgatycgarmltgg
ktdrvhrgcs-----------prpqhsi----------------idvpsd
maagkkfs--qqspltpifscklnfllk-y--hasi--------nptavq
scnek-------------gts-lstlaktpggvlsstvlalsn--p----
---y--cp---ylhskdyc------g-------clgf--ededkpp----
---qgg-rcgyeg-----------qd------agirykavers---l
>node6
fgltidqikeg---ld--qeegqlegpktm------------vrlsvwgh
ntkna------rlsigts--ghigkslsarlsawca-----civ--nasl
t---vs---------sfdg-------tff--rllkndl-----------h
l--igdcaipgt---ekefastt--argdagpfrk-ekkeysmhvgpgke
lgeeklrta-----qre----gqsalf----hedgtlkdv-----ivll-
-n-------rdgsecvas-----tg-g---p--dvsrtvkcvdgvhessk
yesgktlclik-elav-f---vagkdagh-fenaqd-----mdkal----
ersekdqylysc----p------gc---al---------gc-vcwglpt-
-------l-------ilra-tkgakrkkg----rskvq--ak----eesh
vtav--c-----rraigkp--aavigeslam-tdtnkgasycgarmltgg
ktdrvyrgcs-----------prpqhti----------------idlpse
lavgekfs--eqsaltpifsckldflln-y--hasi--------npaavq
scn-k-------------vts-lstlaktpgpvlsstvlalsp--p----
---y--cp---ylhskdyc------g-------clgf--edddkpp----
---qgg-rcgndgms-ksvafmhhqd------agirykavers---l
>node14
yaltidemkeg---laeeqeapklegsetmegqvaggcg--pirlavwgh
dsnha------wlliggscrphvgdslgarlgawcardwtk-tv--nirl
t---is-----qvrenftg--dkvartym--rllksdlr----cyypalq
l--vgdc-sppp---pqdfyaat--ekgeaspfrr-dkkensmlafpgke
----dfktg-----eleapg-ggs--f--kpr-------v-----vvll-
-al----rh-egsgcvts-----cg-g---c--qvv--------vhdtaa
yevgktscllk-dldvefdnafdgkdaghefenaqd-----mdrti----
dkg-idrvlfacdnknp------gcs--aaknggsdngdgc-vcwgatr-
-------l-------vise-trggkrkkg----ksrid--gk----hekd
v--q--c------relrkphwlst-----pmlaeas-------grmmtdg
kiik----crtcydi----ifs----niph--ihg--csdytwkikepse
---geaya--eegpi-ptfeckndlalh-y--hksg--------kpaevh
hse-k-------------vtt-lntlaktqgpvlsyaelslgp--ps---
aqsy--cp---yingkgyc------v-------cmgg--endsprpvg-v
khvqdg-rccsngit-ktvt---------------rf-svdsd---l
>node15
yaltidqlkeg---la--qeapklegsktmesqvaggcg--pirlpvwgh
dsnha------wlsiggs--phvgdslgarlgawcardwtkctv--narl
t---vs-----qvresfng--dkvartfm--rllksdlr----cyypklq
f--lgdcpsppt---hqdfystt--ekgeaspfrr-dkkensmlvfpgke
----dfrtg-----eweepa-gds--f----r-------v-----vvll-
-al----kh-dgsgcvts-----tg-g---c--qvv--------vhetak
yevgktscllk-elavefdnaidgkdaghkfenaqd-----mdrti----
dks-idrylfac----p------gc---aakiggadngdgc-vcwgvts-
-------l-------vire-tkggkrkkg----rsrvd--sk----nevd
vlaa--c------rqipkpywisvagedspmlaeadkgaaycgqrmmtdg
kvik----crtcyei----ifs----niph--thg--cgdf--kidmpse
lsvgekfa--eesplkptfsckiefllh-y--hksa--------npaevq
lsn-k-------------vts-lgtlaktpgpvlsytelslgp--ps---
aqay--cp---ylngkgyc------a-------cmgg--eddsprpvg-v
khvqgg-rcgsngit-ktvs---------------rf-avdrk---l
>G
yalnidqmkgg---laepqeadnmvgsetmeaivggacgpfpvrlav-gh
dskha------wiliggschshvgddlgapmsawcariwsk-ts--nniq
sctkin-----hvkenktg--dkvarkfl--rqakdklrtakvcyfptlq
i--vgdc-qepptymppdfytat--ekgpaspfrsgdrkyntmfafpgkq
----dfktg-----q-eapg-dgs--fiskvr-------v-----avll-
-altnayrh-egsgcvta-----cgqg---c--s----------ihntga
ydvgksscllk-dfdve----fegknatqqfqnaqd-----mehad----
eks-idrvlsicd---v------gcr--aannagadegdgcfvs---trl
kkdf---l-------linegprggkqrksftsdkskne--sk----hesd
v--d--caalcg-yplrkphwlkt-----rmlaeas-------griltdg
kivk----crn-yql----eft----niphvvihgcecngcnwkik--ie
---keays--ekgpi-psfecktdlqlh-y--hksg--------ksneah
hse-k-------------ptsvlntlaktqg----yrelalgp--pa---
vqky--r-----fsakgya------msghmtdqskqg--dndsphqvn-v
khiq---rccsngiipkavt---------------rf-tiese---l
>node10
yaltineakydalglaeekeapklegaetmegmvpgg--------nvwgh
dskha------wlvissccrphvgdslgsrlgaycak-----sv--htrl
t---is-----qvrdhytn--dkvaraym--rllkgdar----cyypalq
l--vgdc-sppp---pqtfygakelekgeaspfrr-dkkensllafpgre
----dfttg-----eleapg-gga--f--kpr-------v-----vvml-
-at----rh-egsgcvtg-----cg-g---cskevv--------vhdsat
yevgktscilk-dndvefddafekkdgghefetaqd-----rdrvv----
kkg-itrvlftcdtknp------gcs--aaknggsenadgc-vcwgttr-
-------l-------vise-trggkrkkg----kgrid--gk----hekk
v--qkpc------celrkphwlst-----pmlaetp-------grmltdg
kvik----crtcydf----ifs----niph--ihg--csdytwktkipge
---geayakpvagpv-ptfeckndlslh-y--hktg--------ksaeih
hse-a-------------vtt-lnsvaktqgpvldyaeltlgp--ps---
aesy--cp---yingkgyc------v-------cmgg--endaprptg-v
khvqgg-rccsngit-ktvt---------------rf-svesdadhl
>node7
faltidqikeg---ld--qeagqlegsktmerqvadgcg--pvrlsvwgh
dsnha------rlsiggs--phvgnslgarlgawca-----civ--narl
t---vs-----qvkesfng--dkvgttfl--rllkndlr----ctysklh
l--lgdcasppt---eqdfystt--akgdaspfrk-ekkeysmlvfpgke
ldelklrtg-----qreepa-gqs--f----r-------v-----ivll-
-sl----khrdgsgcvas-----tg-g---c--qvvrsvkcvegvhesak
yesgktscllk-elav-f---iagkdagh-fenaqd-----mdktl----
drs-idrylfac----p------gc---aa---------gc-vcwgvas-
-------l-------imra-tkgakrkkg----rsrvd--ak----eqth
vtav--c-----srqiakpfwasvvgedapm-adtnkgaaycgarmltgg
kvik----cr----f----ifs----ti----------------idlpse
lavgekfp--eqsnlkptfscklnflln-y--hasi--------npaevq
scn-k-------------vts-lktlsktpgpvlsytvlalsp--ps---
aqay--cp---ylnskdyc------a-------clgf--eddsprpvg-v
khvqgg-rcgsngis-ktvafmfhqd------agiry-avdra---l
>A
---tidqakeg---------------gktrdrqvgegcg--cvplgswgh
l-----------lsiegr--shvanslgaklga----------------l
a---vr-----kvkesing--asvgttfl--rl--ndlr----ctyfk-h
lvllggcpkppt---elefyett--akgesgsfrk-skkeysllgfpska
ftekklqts-----qreqsa-gvs--f----k-------c-----lvllk
tsl----kkedgsgcvan-----dg-g---c--qvvrsvsciegvhekak
aesgkvscllk-qlav-f---vsgkdaah-fenaqngkkflldkql----
krs-idkyllav----p------gc-caat---------gc-acwgvat-
-------ltrkaqsttmrs-drgakrrkg----rqrvddsat----eqtq
vtlv--c-----sskilrp-waavvgedapm-adtnkgtaycgarmldgg
tvna----ck----f----ifg----vv----------------inlpsv
ltade-fp--easnlkpafccklnflld-y--hasi--------qptdvq
avn-k--kaikalllldiian-lqafsktpgdvlpy-vlalsp--pnlnh
aqay--cpqhgykrgkgyc------a-------clgf--edngprgvg-v
thvqggrrcgsngis-k---imfpqe------agvkt-avdrt---k
>node13
yaltidqmkng---laepqeapklvgsetmegilaggcgpfpirlav-gh
dskha------wlliggscrshvgddlgapmsawcardwsk-tv--dirl
s---is-----qvkenktg--dkiarkfl--rqakddlrtaklcyfptlq
f--vgdc-sepptyippdfyaat--ekgeaspfrrgdkkentmlafpgke
----dfktg-----q-dapg-ggs--f--kvr-------v-----vvll-
-al----rh-egsgcvta-----cggg---c--s----------vhntga
ydvgkpscllk-dfdve----fdgknaaqqfqnaqd-----mdrav----
ekg-idrvlficd---v------gcr--aannggsdegdgc-vcwgatrl
krdy---l-------lise-trggkrkks----ksrie--gk----hesd
i--n--c------yelrkphwlqt-----pmlaeas-------griltdg
kiik----crncyqi----efs----niphvvihg--csdytwkiknpie
---geays--eqgpi-ptfecktdlqlh-y--hksg--------kpaevh
hse-k-------------pttvlntlaktqg----yrelalgp--ps---
aqky--cp---yfsgkgya------msghmtdsckgg--endsprqvg-v
khiqdg-rcctngii-ktvt---------------rf-tvese---l
>E
yaltinearydalglaeakeapqldsaetlegmvpgg--------nvwgh
dskhanva---wlvisgcciphvgdslgnrlgaycak-----ta--hqri
t---is-----qvrdhytn--dkvargym--rnlkgdtr----cyypglq
l--vgec-tpsl---pitl----alekgedspfrr-dkkeyklltftgre
----dyttgflaplrleleg-gga--f--kpr-------v-----ivrl-
-at------------vtg-----cg-g---cckedv--------vhdsat
yeigktacvlk-nnnvefddafekkdgghefe------------------
------rvlftcdskgp-------ce--taksggsddadgc-tcwgttr-
----ntal-------vise-prggkrkkg----kgrld--gk----hekk
f--qkpc------cdlrkphwlsl-----pmlrdtp-------grmltdg
kvik----crlcydf----ifs----siph--ihg--ysdytwktkkpge
---gesykktkagpv-plfes---ls-------------------sdeth
pse-g-------------vth-lnsvakkqgpvldypeltlgp--pa---
aesy--cp---yisgkgyc------v-------cmgn--dsegprpkg-v
khaqgg-rccssgcn-rtvt---------------rf-pvdsdadql
>H
yglt---mkng---laqpqeapklvgsekmggileggcgpfqirlav-sh
dskha------wleisgscrshvgdslgatmcawcrrdwsk-tvmhdirf
t---ls-----qlkenrsglldkvarkfl--rdakedlrtaklcyfptiq
f--vgdc-sdpktyippdfysat--ekgeaspfkrgdkkedtmlafpgke
----dfkkg-----q-napg-gga--l--kvr-------c-----vvll-
-al----rs-qesgcvsa-----cgag---c--a----------ahnvgd
ydvgkpgcllk-sfdve----fdgkn-vqqfknaqd-----mdsdvsfak
ekg-idrvv---------------cr--eatndgnneadgc-vcwgptrl
kkdy---l-------liae-grggkrkks----kpri---------pesi
i--d--c------yelrkphwlqy-----pmlaeps-------grvlteg
kiik----crncyqi----efp----niphivihg--csdytwkikk--e
---nevys--aqg---ptfeckndlqlhkf--hksggnifrgvyspdevh
hse-k-------------pttvlntlpktqa----frelalgs--ps---
aqiy--cp---ffsnkgya------msgemkdpckggesendspkaig-t
k-iedp-rcc----i-ktve---------------mf-tvkse---l
