>H
hvaldkmsigpgdatvqlpaakgkdadlltrvqykfadptvsvlngsgsh
ikalnsaaiqqeltkcicak-------fenksdtfalqkeldekgqwkir
qplsklcetyghppmsgrelrkpe----gkhqkkkvvicstlfkllahak
faigfgtlthlsfgwigkkktkcmrdgnekpdrgslkiskceqrqnkqqe
f--dfrlyydesvlkgpgdyyvkikkdgkddvcagyhgnvyvdksespps
ldpla----ygarsggvdnhkrenplwgspnpavkiqqdlnc----kdak
hwssgkafcefcihaktyvgdkvcktkvktdkvdvqlgftikrasdciki
scla-----vpsttrevllplidstmkissdiaggvck--tlqaiedadd
tsrtaptvvkgkcrtqgagakcerawialfqlyignlvghifgpatgfng
lpfdcvviappeplslqpqtklflkcyaallyqa-aldrcfgtgpeg-at
nanclckpglqsvklhiafrpgi--esftfsnn----vdyq
>node3
nvamrklsagpgqetvqlqatkgkv--lltrvqfkfgkatlsvlngkgth
vkelesavikqeltkcv----------fekksdtfalqklldakaqwkvr
dplaklcetfghadmsgrnlrkpe----gkhrkkkvvacsktlkllahtk
fpig-----------vpkkqttcmpdgnkkpgkgpgkitkcaerqnkqee
f--vfsayfeesvlrgagdyyvklkrngkdnvcaiyhanvyvdksapppa
ldpla----egarsggvdn-rregplwsspypavkiqqdancvg--ksdk
hw-----fcsfvihaktfvgdtvckakvktdnvevklgfcvkalsncikt
acla-----vpapnrevmaplvkksmkitgdagasvck--llmkaedagd
tsrtlptvikskcrtvgnvakclrdwislfp-yi----ghifgpdpgfng
--kdctvmappkplnlpgrsklfqgcaegllyea-slvrcfgtgregspt
nvncmckpglqrvdlhsslrppi--enftfsnprtgggacq
>B
nvtmrklsagpgqetvqlqstkgka--lltrvqfkfgkahlsvlegkgth
vkelesavikqeltkcv----------fekkseafalqklldakaqwkvr
dplsklcetfghadmggrnlrkpedvivgkhrkkkvvacsktlkllahtk
fpig-----------vpkkqttcmpdgnkkpgkgsgmitkcaerqnkqae
f--vfpeyteesvlrgagdyyvklkrngsdnvcaiyhanvyvdksapapa
ldpla----egarkggmdn-rregplwsspypavkiqqdancvg--ksdt
hw-----fcsfvihgk---gdtvckakvkpdsvevklgfcvkalancikt
acla-----ipapnrevmvplvkrsmkitgdagasvck--lllkaedagd
tsrtlptvikgkcrtvgdvakclrdwislfp-yi-----hifspdpgfng
--kdctvmappkplnlpgrsklfqgcaegllyea-slvrcfgtgreaspt
nvnclckpgmqrvdlhsslrppv--eeftysnartgggacq
>node6
nvamrklsagpgqetvqlpptkgkg--lltrvhfkfgkatvsvlngkgsh
kkglesavimqeltkcv---rrggftefekksdtfalqkllddkaqwkvr
dplaklcetfghsgmsgrnlrkpk----gkhrkkivvacsklfkllahtk
fpigfktlthlgfgwipkkqtscmrdgnekpgkgsgkttkcadrqnkqee
f--pfsayfeesvlrgggnyyvklkrngknnvcaiyhsnvyveksasppa
leplatqvmegarsggidn-rregplws-rypavkiqqdaicvg--knak
hw-----fcsfvihaktfvgdtvsktkvktdslevklgfsvkrlshcvks
scla-----vpaanreaiapavqksmpitsdaaanvck--ammdaqdspd
tsrtlpavikskcrtannvatclsdwislfq-yi----ghvfgpdpgfng
--kdcvvmappkplnlpgqsklfqgcapgllyqa-slvkc---sreggpt
qanclcnpglqrvklhkslrpgi--dnfrfsnprtvggacq
>E
qvaldklsagpvqavvqlpaangkdakll--vqfhfadpavkvvtgkgs-
-----stqiqqe-pkcvcak-------fekksgtfelqkiidekvlwtvh
dplsklcevyghpsmsgrnlkkre----gkhrqtklipcsllfkllahtk
lavgfgtlyhlsfgwigkkrttcltdgnekpnrgskkiakcparqskqqe
f--pyrdyfeestlrgcgdyyvkiksngkdnvcadfhgnvfvdkresppa
frpla----ffarsggldn-sredplwgppfpaakaqrd-------kdak
hwssgsafcsfgihaktyggdtvfktkvktvaldvqlgfrlkrlqeciki
dcla-----vpstnrevllplidktmkvsseaaggvck--tlmavddagd
tsrtlltvvkskcrtdgngamcqrawigffh-yignslghlfgpdpgfng
kpddclvmpppepiplmgqsklfqdcaaaliyqa-alercfgtspegvgk
easclck----svkahssfqlgigptsftfsnhrtggvayq
>node15
nvaldklsagpgqatvqlpatkgkdaklltrvqykfadptvsvlngngsh
vkalesaaiqqeltkcv----------fekksdtfalqkilddkaqwkvr
dplaklcetfghpgmsgrnlrkpe----gkhrkkkvvacsklfkllahtk
fpigfgtlthlsfgwipkkrttcmrdgnekpdrgsgkitkcedrqnkqee
f--pfrayfeesvlrgagdyyvkakrngkdnvcaiyhsnvyvdksesppa
ldpla----fgarsggvdn-rregplwgspypavkiqqdlncvg--knak
hw-----fcsfiihaktfvgdtvcktkvktdsvevqlgfsvkrlsnciki
scla-----vpstnrevilplidksmkissdaaagvcr--almaiedasd
tsrtlptvvkskcrtagnvakclrdwialfq-yigngvghifgpdpgfng
--kdcvvmappeplnlmgqsklfqdcapgllyqa-alvrcfgtgpeggpt
nanclckpglqsvklhssfrpgi--esftfsnprtgggacq
>A
dvgmrkl-agqgqetvqlq----kv--lvtrvefkfgkatvsvingkgth
vkelesavikqd--kcv----------fekksdmfalhklldhkaqwkvr
dplaklcetfahadmsgrnlrkpe----gnhrkkkvvacskslkllahtk
fpig-----------vpkkqttcmpdghkkpgkgpgkitkcaerpnkqde
f--vfsmyfeesvmrgagdyyvklkrngkdnvctiydanvyvdksapppa
ldpla----egartggvdn-rregplwsspypavkiqqdancvg--ksdk
yw-----fccfvihaktfvgdtvckakvkednvevklgfcvkmlsncikt
aclnhvldkvpapnrqvmaplvkksmkitgdaaasvck--llmkaedagn
tsrtlptvitskcrtvgnvakclrdwislfp-yi----ghifgsdpgfng
--ld----aapkplklpgrsklfqgcaegllfea-slvrcfgtgregspt
nvncmckpglqrvdlhsslrppi--enftfskprtgggacq
>node7
nvamrklsagpgqetvqlpatkgkg--lltrvqfkfgkatvsvlngkgsh
vkalesavikqeltkcv----------fekksdtfalqkllddkaqwkvr
dplaklcetfghagmsgrnlrkpe----gkhrkkkvvacsklfkllahtk
fpigfgtlthlgfgwipkkqttcmrdgnekpgkgsgkitkcadrqnkqee
f--pfsayfeesvlrgagdyyvklkrngkdnvcaiyhsnvyvdksasppa
ldpla----egarsggvdn-rregplwsspypavkiqqdancvg--knak
hw-----fcsfvihaktfvgdtvcktkvktdsvevklgfsvkrlsncikt
scla-----vpatnreviaplvqksmkitsdaaasvck--almkaedssd
tsrtlptvikskcrtagnvakclrdwislfq-yi----ghifgpdpgfng
--kdcvvmappkplnlpgqsklfqgcapgllyqa-slvrcfgtgreggpt
nanclckpglqrvklhsslrpgi--esftfsnprtgggacq
>C
nvamrklsagpgqatvqlpptkgkg--lltrvhfkfgkatvsvlngkgsh
kkgldsavimqgltkcv---rrggftefekksdtfalqklledkaqwkvr
dplaklcetfghsgmsgrnlrkpk----gmqrkkividcsklfkliahtk
fpfgfktlthlglgwipkkqtscmrdgdakpgkasgktskcagrqnkseg
f--pfsayfeesvlraggnyyvklkrkgknnvcaiyhsnvyveisasppn
letlatqvmenarsggidn-rmdgplws-rfpavkiqqdaicvg--knar
hw-----fcsfvihaktfvgdtvsktkvktdslevklgfsvkrlshcvks
scla-----vparnreavapavqksmpittdaalnvck--smmdaqddpd
tartlpavikskcrtantvatclsdwislfq-yi----gevf-pdpgfng
--kecvvmapekplnlpgqsklfqdcapgllyqa-slvkc---sretgpt
qanclcnpglqrvklhkdlrpgv--dnfrfsnprtvggacq
>D
nvamrklsanpgqetvqlpptkgng--llthvhfqfgkatvsvlngkgph
kkgletavimqqltkcv---rrggftefekktdtfafqkllddkaqwkvr
dplaklcetlgqsgmsgrklrkpk----gkhrkklvvgcskllkllshtk
fpigfktlshlgfgwipkkqtscirdgnekpgkgsgk-tkcadrqnkqee
f--pfsayfeeqvergggnyyvklkrngkndvcaiylsnvyveksasppa
leplasrvmegarsggidn-rregplws-rysavkaeqdaicvg--khar
hw-----fcvfvihaktfvgdtvsktkvetdslevkigfsvkrlshcvks
scla-----vqaanrepiapgvaksmpittdaaanvckcaammdaqdspd
tsktlpaviksncrlanlvatclsdwislfq-yi----ghvftpdpgfng
--kecvvmslpkplnlpgqsklfqgcapgllyka-g--kc---sreggpt
qanclcnpglqrvklhkslrpgi--dnfrfsnprtvggacq
>node10
svaldklsagpgqavvqlpaangkdaklltrvqynfadpavkvvtgkgs-
-----stqiqqelpkcvcak-------fekksdtfalqkildekvqwtvh
dplsklcetfghpsmngrnlkkpe----gkhrkkkviacsrlfkllahtk
favgfgtlyhlsfgwigkkrttcmrdgnekpdrgsnkiskcpdrqskqqe
f--pfrdyfeesvlrgcgdyyvkikrngkdnvcadfhgnvfvdksesppa
lkpla----fgarsggvdn-rrenplwgppypaakiqrdlncvglskdak
hwssgkafcsfaihaktyagdtvfktkvktvavdvqlgfrvkrlqeciki
ncla-----vpstnrevllplidktmkisseaaagvck--tlmavedadd
tsrtlltvvkskcrtdgngakcqrawiglfh-yigngvghifgpdpgfng
kpddclvmpppeplplmgqsklfqdcaaaliyqa-aldrcfgtspegvgt
danclck----svkehssfhpgigpesftfsnhrtggvayq
>node13
hvaldklsvgpgdatvqlpaakgkdaklltrvqykfadptvsvlngsgsh
ikalnstaiqqeltkcvcak-------fekksdtfalqkeldekgqwkvr
qplsklcetfghpsmsgrelrkpe----gkhrkkkvvicsrlfkllahak
faigfgtlthlsfgwigkkkttcmrdgnekpdrgsnkiskcedrqnkqqe
f--dfrlyydesvlrgpgdyyvkikkngkdnvcagyhgnvyvdksespps
lkpla----fgarsggvdn-krenplwgspypavkiqqdlncvg--kdak
hwssgkafcsfiihaktyvgdkvcktkvktdavdvqlgfsvkrlsdciki
scla-----vpstnrevllplidgtmkisseiaggvck--tlqaiedadd
tsrtlptvvkgkcrtdgnvakcqrawialfqlyigngvghifgpdtgfng
lpfdciviappeplslmgqsklflkcyaallyqa-aldrcfgtgpegaat
nanclckpglqsvklhiafrpgi--esftfsnhrtggvayq
>node14
nvaldklsagpgqatvqlpaakgkdaklltrvqykfadptvsvlngsgsh
vkalestaiqqeltkcvcak-------fekksdtfalqkildekaqwkvr
dplsklcetfghpsmsgrnlrkpe----gkhrkkkvvacsrlfkllahtk
faigfgtlthlsfgwigkkrttcmrdgnekpdrgsnkiskcedrqnkqqe
f--pfrayfeesvlrgagdyyvkikrngkdnvcaayhgnvyvdksesppa
lkpla----fgarsggvdn-rrenplwgspypavkiqqdlncvg--kdak
hwssgkafcsfiihaktyvgdtvcktkvktdavdvqlgfsvkrlsnciki
scla-----vpstnrevllplidktmkissevaagvck--tlmaiedadd
tsrtlptvvkskcrtdgnvakcqrawialfq-yigngvghifgpdpgfng
kpndcivmappeplslmgqsklfqdcaaallyqa-aldrcfgtgpegvpt
nanclckpglqsvklhssfrpgi--esftfsnhrtggvayq
>F
svaldklsagpgqavvqlpaadgkdgklltrvqygfalpavkvvtgkgs-
-----stqiqpelrkcvcak-------fekksdtfalqkildekvewtvh
dplsqlcetfghgtmngrnlkkpe----gkhrkktvigcsrlfkllahtk
favgfgslyhlsfgwigkkrttcmrdgnekpdrgsdkiskcpdresrqqe
f--hfrdyfdesvlrgcgdyyvkikqsgkdhvcadfhgnvfvdksespsa
lkpla----fgarspgvdn-rr---lwappypapkiqrdincvglskdak
hwssgkafcsfaihaktyagdtvyktkvkdvsvdvqlgfqvkrlqeciki
ncla-----vpdtnrdsllplidntmmisseaaagvck--tlmavedand
tdrtlltvtkskcrtdgnfakcqrvwiglfh-yrgdgvghisgpdpgfng
kpddclvmstpeplplmgqsklfqdcsaaliyqaraldrcfatspegvgt
nanclck----svkehssfhpgigsesftfsnhrtggvayq
>G
hvaldalstgpgdatvqlpavkgkkakhlhrmqykiadptvsvfngsgeh
lkalkstsiqqelikcvcak-------fekksdtfalqkeldekgqwkvr
qpltqlcetfghtpmsgrelrkpe----grhrkkkvvii---fkllahak
favgfgnlahlsfgwigkkktacmrdgnekpdrgsnkiskcedrqnkqqe
fgndyrlvydesvlrgpgdyylkfkkngkdlvcagyhgnvyvdrsespps
lkpla----faartgavdn-krenpvwgspypevkiqqdlncvg--kdak
hwssgkafcsfiihtktfvgdkvcktkvktdavdiklgfsvkrlsdaiti
scqa-----vpstdrevllplidgtmkisseiaggvck--tlqaiedadd
tsrtlptvvkgkcrtdgnvakcqhawialfqlyigngvghmfgpdtgfng
lpfdciviappepfslmeqhklflkcyaallyqn-aldrcfgtgpegast
nanclckpalqslkihiafrpgi--esftfathrtggvgyq
