>node15
awcrvnsfmtncpldttyqdqqnvnhgvfdteilplsskgqmcnvsaddk
kalyswslahpeltlgvfimpqgqvyvsaligvsssayfgfgvkgvpign
vpganaqeas--svanasdktllaggakgkekkfgrdvsntttkevlfke
sig--vsrl--dacepalsqrlkdhdgdvgrqttnwq-rksgrggdqigv
paeclygrmllttftdvewksaehcf-qhagdigampclsplipk-irlg
v-npqtlsglkeqdsrpdrdselthdavdgdplycn-rngnqhfrsdvvg
shlqdilstvlwkpleivgiflhlvvctp--fsaha--------mallyc
l-----------lecfgmigavypsvadlk----sqetlrsfgktvgasc
fskl-lfeigtnsvkli--vdgstdhkhkkni--ltrlgspk--------
----akglssannhvwlgkilmtevfeaqdlvielqkakdgrsedgriii
mavleevskhetqgvgsrsgchklrfvsyygprfqatgmaynaqvawdls
pds
>D
awcrannfmtncgldtvyddqqkvnssvfdteilplnskgqmchvsadak
kalyswelsspamqlgvfimaqgtvyvnpplgissslyfffgpkgvpi--
vsgatgqesg--mvpaasdktllagggkgk-----------ttkeglyke
ilg--vnrlchd-----------dhagdmgrpatnwqdrksgkggdqlgv
aaeclyaklllttftnsewsasehcf-qhggdigamgclsplipngirlg
i-dpetltslkeqdlrpandselthkv-dgeplycnlrtnkqhfrsdvvg
shlqtifstvlwkplevqgiflhlvvcsp--fsanv--------lsllyc
f-----------lqcfgmvgtvyrsvpdlksvsgshqvlvsigpsgganc
fkdl-lfeigsngvkli--vdgptdpkhkkdi--l-qlsspr--------
----akganatkdhvwlgkvimtdvfdakqlviefakakdgrrvdgriip
mstlenvskhetggvssrsachtltfvsafg--fqasgmsy-ahvawtls
ees
>node3
awcrvnsfmtncvvdtvyqqqqkvnhgvfdteilplsskgqmchvsaddq
nalyswslahselqlgvfiipqgqvyvsalfgvsvsayfffgpkgvpigg
vpsataqdagypmvpaasdktllagggkgkdkkfvrdgsntttkevlfke
iig--vnrlchnaceptlrqklknhaedvgrpttnwq-rksgrgfdqigv
paeclyarmllttftdsewssaeh-f-qhagdigampclsplipk-irlg
i-qpqtmsslkeqdsrpdkdseltvdi-dgdplfcn-rtgkqhfksdvvg
shlqnilstvlwkplevvllflhlvvcap--fsahtifnysyslaallyc
f-----------lqcfgmvgsvypsvpdlk----sqetlrsngptvganc
fskl-lfeigtsavkli--vdgltdhkhkkni--ftrlgapk--------
----a-dgnasndhvwlgkvlmtevfdakdlivelqkakdgraedariig
mavlqevskhesggvgsrfgchklrfvsyfgprfqasgmaynaqvawdls
pes
>node13
awcrvnsfmtncpldpgyqdqqsvnesvfeaqilplsskqpmcnvsgdnk
kalyswslahsd-----fimvqaqvyvsvligvsssgyfgfgvhsvpcgs
vpganaqear--svatesertflaggargnekkfgrgasntttkdvlfke
aig--lgrl--dacdpalsqrlkdhdadvgrqttnwh-kksgrgdnqvgi
paeilhgrmhlttftdvewkraddcf-qhigqigampclsplipk-iwlg
v-npqtlaglreedsrpdrdsvlthdavdgdelfcn-ragnqnfrsdrvg
-hiqnllstvvwkpleivgiflnlvvctp--fsaha--------mallyc
l-----------lnclgmigavypsvadlk----tqetlqafgktlgvsc
fsklalfeigtnsrkli--vdgstdhkhkkni--ltrlgsak--------
----akglssavnhvwlgkillnevfeaqdlvlelqkakisrnedgriii
mtvlgevskhetqgvgsragchklrfviyygnrfqatgmaynahvawdvs
pds
>node7
awcrvnsfmtncaldtvyqdqqkvnhgvfdteilplsskgqmchvsaddk
kalyswslahpelqlgvfimpqgqvyvsaligisssayfffgpkgvpigg
vpgataqeas--mvpaasdktllagggkgkdkkfvrdgsntttkevlfke
iig--vnrlchdaceptlsqrlkdhagdvgrpttnwq-rksgrggdqigv
paeclyarmllttftdsewssaehcf-qhagdigampclsplipk-irlg
i-npqtlsslkeqdsrpdkdselthdv-dgdplycn-rtgkqhfrsdvvg
shlqdilstvlwkplevvgiflhlvvctp--fsaht--------mallyc
f-----------lqcfgmvgsvypsvpdlk----sqetlrsfgptvganc
fskl-lfeigtnsvkli--vdgptdhkhkkni--ltrlgspk--------
----akganaandhvwlgkvlmtevfeakdlvielqkakdgrsedgriia
mavleevskhetggvgsrsgchklrfvsyfgprfqasgmaynaqvawdls
pes
>E
awcrvnsfmsscpldpayqdqqnvnqsvyeteilpssskgqmcnvssddk
kalycwslahsn-----fimv----fvsvligissssyfgfgvkavpiga
vpeadaqear--gaanasertflagaargdekkfgrgasnttgkdvlfke
atg--lgrl--dacepalsqqlmdqqgdvgrqttnwh-kkagrggnqagi
paeivygrmllatftgvewkraehcfsqhighagsmpcltpllak-lrag
d-npqilaglredssrpdadsvlehglidgdaafcd-ragsqnfrsdvvg
shlqhilstviwkpldivgvflhlvlcsl--fsvqa--------mgllyc
i-----------lecfgmcgavypsvadlk----sqetldsfnktlgptc
fskl-yfeigtnsvlli--vdgstdhkhkkni--lavlgppr--------
----arglssavnhvwlgti---avyeaqdlvldlqkakeprsedariii
lgvlgeigkhetqgvgsrsgcnklrfvsyyspkfqatlmaynirvswdlt
psn
>C
awcrvnsflancsldtgyqdhqkvnhsvfdveilplssqgqmcsvsaddk
kalyswslaspamqlgvfimaqgnvyvepllgissslyfffgpkgvpi--
vpgatgqeav--mvpaasdktllcggskgk-----------ttkevlyke
iigeyvnrlchdacepkfserlkdhagdmgrpatnwq-rksgkggdhigv
paeclyaklmlttftvsewssaehcl-qdggdiggmpclsalipknirlg
i-npevlsslreqdsrpdndselthdv-dgeplycnlrtgkqhfrsdvvg
shlqtifspvlwmplevdgiflhlvvctp--fsant--------mallyc
f-----------lqcfamvgnvycsipdlksvsdshqtlvsfgptvggnc
fsdl-lfeigtsgvklk--vdgptdpkhkkdi--l-rlsspr--------
----akggnaandhvwlgkvvmtevfdakdlvielakakdarsvdgriip
msvlenvskhevggvssrsgchmltfvstfg--fqssgmsy-phvawtls
ees
>node14
awcrvnsfmtncpldpayqdqqnvnqsvfeteilplsskgpmcnvssddk
kalyswslahsd-----fimvqgqvyvsvligvsssayfgfgvkavpigs
vpganaqear--svanasertflagaargkekkfgrgasntttkdvlfke
aig--lgrl--dacdpalsqrlkdhdgdvgrqttnwh-kksgrggnqigv
paeilygrmllttftdvewkraehcf-qhigqigampclsplipk-irlg
v-npqtlaglreedsrpdrdsvlthdavdgdalfcn-ragnqnfrsdvvg
shlqnilstvvwkpleivgiflhlvvctp--fsaha--------mallyc
l-----------lecfgmigavypsvadlk----sqetlrsfgktlgasc
fskl-lfeigtnsvkli--vdgstdhkhkkni--ltrlgspk--------
----akglssavnhvwlgkillnevfeaqdlvlelqkakdsrsedgriii
mavlgevskhetqgvgsrsgchklrfvsyygprfqatgmaynarvawdls
pds
>G
awcrvngfmttcplepgyqdqksvnvsvfealilplsmkqpmcsisgdnk
kalyawslahsd-----fimvqaqiyvsvligvssfgyfgfglhsvpcga
vpgasaqea-----ates----laggargneekfgrgasptttkdvlfke
aig--lgkl--iacdpalsqrlkehdadcgrqttnwh-kksgrgdnqtgi
paqilhgrmhlttftdvewkrtddcf-qhigqigtmpclsplipk-iwlg
v-npqtlaglreddsrpdrdsvlthnavdgdelfcn-ragnqnfrsdrvg
-hiqnllstvvwkpldivgiflnlvvctp--fs-ha--------mallyc
l-----------lnclgmigavypsvadln----tqetlqafaktlgvsc
fgklqlfeigtkvrkli--vdgstddkhkknikdltrlasaknhgfkgaa
stgnakglsaavnhvwlgkillnevfeeqdlvlelqkkeisrnddgriii
mtvlgdvskhedqgvgsragchklrfviyygnrfqatgmaynahvawdvp
pds
>H
awcrvnsfltncpldpgyqdqqsvnesvfeaqvlplsskqpkcnvsgdnk
ralyswslahsd-----filvqaqvyvsvligvsssgyfgfgvhsmacgs
vpganaqagr--tvatesertflaggargnekkfgrnasnsttkdvlfke
aig--lgrl--dacdptlsqrlkdhdadvgrqttnwh-kksgrgdnqvgi
tasilhgrmhlttvtdvewkraencf-qhigqigvmpclsplipm-iwlg
v-gpqtlaglreedskpdrssvltpdavdgdelfcd-ragnqnfrsdrvg
-hiqnilstvvwksleivgiflnlvvctp--fsghl--------mallyc
l-----------lnclgmigavypsvadlk----tqetlqafggtlgvsc
fslldlfeigtnsrkli--iagstdhkhkqni--ltrlgspk--------
----akglssavhhvwlgkimlnevfeaqdvvlelqkvkvsrnddgrivi
mtvlgevskhethgvgsragchklrfviyygnrfqatgmaynahvawdva
pds
>B
awcrvnsfmtncvvdtvyqqqq-vnhgvfdaeiwplsskgqmchvsaddq
nafyswglahselqlgvfiipqgqvyvsalfgvsvsayfffgpagvpigg
vssataqdagypmvpaasdktllsgggngkdkkfardgsntttkevmfke
iig--vnklchnaceptlrqrlknhaeevgrpttnwq-rksgrgfdqigv
paeclynrmllttftdsessaaeh-f-qhagdigampclsplipk-islg
itqpqtmsslkeqdsrpdkdseltgdl-dgdplfcn-rtgkqhfkedvvg
shlqnvlsivlskplevvnlflhlvvcap--fsahtifnysyslsaalyc
f-----------lqcfgmvgsvypsvseak----sqetlrsngptvganc
fakl-lfeigtsavkli--vdglsehkhkkni--ftrlgapk--------
----a-dgnasndhvwlgkvlmtnifdakelivelqkqksgraedariig
mavlqevskhesggigsrfgchklrfvsywgprfqasgmaynaqvawdls
pes
>node10
awcrvnsfmtncpldpayqdqqnvnqsvyeteilpksskgqmcnvssddk
kalycwslahsd-----fimv----yvsvligissssyfgfgvkavpigs
vpganaqear--gvanasertflagaargdekkfgrgasnttgkdvlfke
atg--lgrl--dacdpalsqrlmdqqgdvgrqttnwh-kkagrggnqvgi
paeivygrmllatftdvewkraehcf-qhigqigampcltplipk-irlg
d-npqilaglrednsrpdrdsvlqhglidgdalfcd-ragsqnfrsdvvg
shlqhilstviwkpleivgiflhlvlcsl--fsaha--------mallyc
i-----------lecfgmcgavypsvadlk----sqetlksfnktlgatc
fskl-yfeigtnsvkli--vdgstdhkhkkni--larlgppr--------
----akglssavnhvwmgkillnevfeaqdlvlelqkakdsrsedariii
mavlgevskhetqgvgsrsgcnklrfvsyysprfqatlmaynarvswdlt
pdn
>F
awcrvnkfmtkcpldpayqdqqnvnqsvyeteilpksskgqmcnvssddk
kalycwslahed-----fimv----yvsvligitsssyhgfgvkavpigs
vpganaqear--gvanesergflagatrgeekkfgrgaqnttgkdvlfke
atg--agrl--hacdptlpqrlmdqqgdvgrqttnwh-kkasrggkqvgi
paeavygrmllatftdvkwkraehcf-qhigqigarpcltplipk-irmp
d-npqilaglreensrpdrdsvlqhgvingdalfcd-ragsqnfrsdvhg
ghlqhilstviwkfleivgmflhlvlcsl--lsahr--------malmyc
a-----------lecfgmcgdvypsiadlk----sqetlksfkktlgatc
fskl-yfeigfnsvkli--vdgstdhkhkkni--larlgppr--------
----akglssavehvwmgkillnevfeaqdlvlelhkakdsrsedariiv
mavlgevrkhetqgvgsrsgcnklrivsyysprfqstlmaynarvswdlt
ldn
>node6
awcrvnsfmtncaldtvyqdqqkvnhsvfdteilplsskgqmchvsaddk
kalyswslaspamqlgvfimaqgnvyvdpllgissslyfffgpkgvpi--
vpgatgqeag--mvpaasdktllagggkgk-----------ttkevlyke
iig--vnrlchdacepkfserlkdhagdmgrpatnwq-rksgkggdqigv
paeclyaklllttftdsewsaaehcf-qhggdigampclsplipknirlg
i-npetlsslkeqdsrpdndselthdv-dgeplycnlrtgkqhfrsdvvg
shlqtifstvlwkplevqgiflhlvvctp--fsant--------mallyc
f-----------lqcfgmvgsvypsvpdlksvsgshqtlvsfgptvggnc
fsdl-lfeigtngvkli--vdgptdpkhkkdi--l-rlsspr--------
----akganaandhvwlgkvvmtevfdakdlvielakakdgrsvdgriip
msvlenvskhetggvssrsgchmltfvstfg--fqasgmsy-ahvawtls
ees
>A
awcrvdefmtqcvvdtvyqqqekvahgvfdteilplsskgqmshvsaddq
nalyswslahselqlgvfiipqaqvyvsalfgvsvpayffygpkgvpigg
vpsataqdggypmvpaasdktllggggkgkdkkfvrdgsntttkevlfkd
ivg--vnrlchnaceptlperlqkrgeevgrpttnwq-rksgkgfdqigv
paeclyarmlettftdsewssaeh-f-qhagdigampclsplipk-irlg
i-qpqtmsslkeqdsrpdkdsevapdi-dgdplfcn-rtgkqhfksdvva
nhlrnilktvlskplevvllflhlvvcapirfaahtifncsyslnallyc
fsgvalnliatvlqcfgmvgsvyphvpdlk----sqetlrsngptvaanc
fskl-lfeigtwavkligsvagltehkhkkni--ftrlgapk--------
----a-dgnasneavwlgkvlmtevfdakdlivelqkakdsraedariig
msvlqevskhesggvgsrfgchklrylsyfgprfqasgmaynaqvawdls
pds
