>node3
varvrtsyggiplymgkfigaqsglkae---sqpdrssifcraemtngrg
gtpyccfaagpdeer-----psdkapaahlfpvdepqrewftlaaytnkf
gcrlagiyltacgpldeskpvhcvigtqkfatdmsv----ktqgeg-kvp
aslefpatfgevkcreklvsfyitlvvcvqmfvllccqlpafvflnvtet
ksigdnddtesklllrlgevmhdpi--------------maqtffacatk
lvnldqpkpsveynsasft-nqgffpcmpdedvcavsv-pgrktsnaaia
hynkilplpstmtspleiitark---slycdvtksapscpknetsatdda
pdgttgspdlpgvaefaygtatfvaplpkqlilg----asqlswiccesl
gkkfeslsvipevhfgkgygkeii------vfan-hliakccdslldcak
ellesnaqshqnmilnylhvtanllrgcpyygrisgkgsd-----ktlqf
ketkymaivngeigklekmyffdthffteamerlcdsrigggpkmgf
>A
varvrlsyggiplymgkfigaqsglkae---sqperttifcraemtngrg
gtpyccfatgpdeer-----vsdkaptanlfpvdepqrewf-----snkf
gcrlag-yltacgpidesipvhcvigiqkfetdmsv----ktqgeg-kvp
aslegpatfgevdcreklvkfyitvvvcvqmflllccqlpafvflnvtet
ksigdnddaeskllrrlg----dpi--------------maqtffacstk
lvnldqgkptveyngasft-nqgffscmpdedvcavsvlpgrktsnaaia
hynkilplpstmtspleivtark---slycdvtksapscaknetsatdda
pdgtsgapdlpgvaefaygtatfvaplpkqlvlg----asqlawiccefl
gkkfeslsvipevhfgkgygkeii------vfan-nliakccdalldclk
ellesnaqshqnmitnyl--aanllrgcpyygrisgkgsd-----ktlqf
ketkyeaivngemgklekmyffdthffteamerlcdsridsgarmgf
>G
mpqvltsygglplsmgkflgppsglkagrcgqqngrisaycypaltntkg
gtsycciargpeeeh-----psdsppaahlyqvdeakdtwf---aysnrf
gcrqaavyqtacgpmgncrpv--cvgtkkfatdmnl----ktqgdgvkva
aslelctdfndvkchdelitfyitlvksiemfallccqipsfiflnnket
ktnggnepteskpllrlgdimgepv--------------maqsffpcidk
lvnlqhpkesvpyhlssfr-devf----------qdsn-pvrkksnaaiv
hyntilalssditsqldivdtrk---alysdstkapptcpindvsagdde
pegragsnaipgvaefayasaafvpslakqlilactesaaefsriccesl
lkkfeglsdipevhf-ssygkeiv------vfvnvqlsanccagllgcar
elletkvhsnlkllleylhgtsvllkgciyygrysgnnsd-----stlqf
katkylavvtgdigklakmyfydshfyteimeglcdsrvgggpkmgy
>node10
mpqvltsygglplymgkflgapsgqkagrcgtqpgsasiycraeftnsrk
gtsyccfargpeeer-----psdsppaahliqvdeakktwftlaaysnqf
gcrlagiyltacgpmgnckpv--cigtkkfatnmnv----rtqgeg-kva
aslelattfgevkcheelvsfyitmvksiqmfvllccqlpsfvflnntkt
ksvggnepneikpllrlgdvnadpv--------------maqsffacadk
lqnle---esvpyhlssfrvdkvfrtcrpeeeacsisl-pvgknsggayl
nynkilplppaitsqleivdtrkfpcslysdvtrnsptcpineesgaget
pegrtgenpipgvaefaytaatmvpplpkqlilgctesadqfsriccesl
gkkfegladipevhfgsgygkeiv------vyinvqlianccagllqcar
ellaskahsnlkmlleylhgtylllrgclyygrasgkggd-----stlqf
katkymavvtgeigklakmyfytshfyteimeglgdsrpgggpkmgy
>E
mpqvltsygglllymgkflgassgqkagrcgtqpgsahiycpaeftnsrk
assyccfargpeeer-----psdsppgnhliqvgeakktwftlaaysnqf
gcrqaaifltacgpmgnckpv--cigtkkfatnmnv----rtqgeg-kva
aslelattfgevkcheelvkfyitmvkaiqlfvllccqlpsfifltntra
kslggkepneikvllrlgdvnadpvmdsqlcvsirlclgmaqsffacadk
lqnle---esvpyhassfrvdkvfrtcrpeeeacsisl-pvgknsggayl
nynkilplppaissqleivdtrkfpcslyskvtrnsptcpineesgageg
pegrtgenplpgvaefaytaatlvpplpkqlilgctesadqlsriccesl
gkmyegladipqvnfasgyskeiv------vyinvql---ccagllqcaa
ellaskahsnlkmlley---tylllrgclyygrasgkgad-----gtlqf
kavkymagvtgeigklakmyfytskfyaaimeglgesrpgggpkmgy
>F
mpqvttsygglplymgkfagapsaqktgrcgtqpgaaaiycraeftssrn
gtsyccfgrgpeeer-----psdapcaahliqideakktwftlaaysnqf
gcrlagiyltacgpmgickpv--cigtkkfatnmnlfdpertqgeg-kva
esldlattfgevkcheelvsfyitmvrsiqmfvilccqlpsfvfinntki
ksvtgnepneikpllrlggvnaspv--------------msqsffacadk
lqnle---esvpyhlssfkvdkvfrtcspdeeacsisl-pvgknsggayl
nynkilplppaitsqleivdtrkfpcslytdvtrnspt----eesgaget
pegrtgenpvpgvaefaytsvsmvpplpkqlilgctesadqfsriccesl
gkkfegladipevhfgsgygneiv------cyinvqlianccagllqcar
ellaskahsnlkmlleylhgtylllr-clfygrasskggs-----stlqf
katkymavvtaeigklakmyfytshfyteimeglgearpgggekmgy
>D
mpqvltsygglplylgrfigaqsnlkae---sqpdrssmfcraemirgrg
gssyccfasgpnqer-----psdkgptahlfpvdehkptwftlaafsnrf
acklagiylracspmqdskpv--vl------------------geg-dvp
aslelpttfgevkchdklvpfyitvlvciqmfvllccqlpafvfldvtat
kniggndpiesnpllrmgdvmhdpi--------------maetyfacank
lvnlthhkpsipynsssft-negffkcrpddeacavsv-parknsnania
qynkilplppaltsqleivtdrk---slysdvvkslpacpkgeasgadda
pkgatgsnplpgvahfaygtatfvarlpkqllll----aaalswlccesl
gkkfeslsdipaahfgkdyakhiisqqhtnpfan-hliakccdslldcak
elleskahknlrmilnylhgsavllrgclyygrisgkgsdpepstkflif
kgakymdvvtgeigilenmyffdtnffveymeavcdakiagspkmgf
>B
varvrtpyggiplymgkfigaqsnlkae---sqpdrssvlcradmtngrg
gfpyccfaaspdeer-----psnkapaadlfavdepqrewfsvaaytnkf
gcrlagiyltacgppdsskpihcvigtqkfandksv----ktqgeg-kvp
aslefpatfgevkcreklvsfyitlvvcvqmfvllccqlpafvflnvtet
kstgdnedtesklllrlgevmhdpi--------------maetffacatk
lvnldqpkpsveynsasfn-nqgffpcmpdddvcavsv-pgrktsnaaia
hynkllplpttmtsplvimtard---slycdvtksapscpknetgatnda
pdgttgspdlpgvaefacgtavfvsplpkqlilg----asqlswicceal
ggkyealsvipdvhfgkgygkeii------vfaa-hliakccdslldcak
ellesnaqshqnmilnylqvtanllrgcpyygrisgkgsd-----mtlaf
ketkymeivngeigklqksyffdthffteamerlcdsrvgggpkmgf
>C
mprvltsygglplylgkfiggqsnlkae---sqpdrapmmcraemtmgrg
gtsyccfasgpnqdrpgaegpndrapashlfptpehrhtwfslaafsnrf
scrlagvyltacnpmddsksv--vlgtqkfatdm-------tqgeg-kvp
aslelpttfgeadchdklvkfyitvlvcvqmlvllccrllafvfldvttn
kniggndpieshpllrmgevmhdpi--------------maqtyfacenn
lvnldhhkpsipynsssft-segffpcrpddeacvvsv-parkngnaaia
hynkilplppaltsqleivnsrk---slyadvtksipgcpkgetsgadda
pegtlgsnqipgaanfaygtatfvarlpkqlill----aaalswiccdsl
gkkfeslkdipevhfgkgyaaeiisqqhtnpfan-dliatccdslldcar
ellestahsnlriilnylhgsavllrgclyygrisgkgsd-----ktlqf
kaskfmavvkgeigkmekmyffdtnlfveimegvcdakiaggpkmgy
>node6
mpqvltsygglplylgkfigaqsnlkae---sqpdrssmfcraemtmgrg
gtsyccfasgpnqer-----psdkapaahlfpvdehkhtwftlaafsnrf
acrlagiyltacspmddsksv--vlgtqkfatdmnv----ktqgeg-kvp
aslelpttfgevkchdklvkfyitvlvcvqmfvllccqlpafvfldvtat
kniggndpiesnpllrmgdvmhdpi--------------maqtyfacank
lvnldhhkpsipynsssft-negffpcrpddeacavsv-parknsnaaia
hynkilplppaltsqleivndrk---slysdvtkslpacpkgetsgadda
pegstgsnqipgvanfaygtatfvarlpkqlill----aaalswiccesl
gkkfeslsdipevhfgkgyakeiisqqhtnpfan-hliakccdslldcak
elleskahsnlrmilnylhgsavllrgclyygrisgkgsd-----ktlqf
kaakymavvtgeigklekmyffdthffveimegvcdakiaggpkmgy
>node15
mpqvltsygglplymgkfigapsglkadrcgsqparasiycraeftntrg
gtsyccfargpeeer-----psdnapashlfqvdeakktwftlaaysnrf
gcrlagiyltacgpmddskpv--cigtqkfatnmnv----ktqgeg-kvp
aslelpttfgevkcheklvsfyitlvvciqmfvllccqlppfvflnntet
ksiggndpteskpllrlgdvmhdpv--------------maqsffacadk
lvnldhpkssvpyhlssft-negfrscrpdeeacaisv-parktsnaaiv
hynkilplppaitsqleivnark---slysdvtknppscpinetsgadda
pdgstganpipgvaefayatatmvaplpkqlilg----aaqlsriccesl
gkkfeglsdipevhfgmgygkeii------vfin-hlianccaglldcar
elleskahsnlkmllnylhgsavllrgclyygrisgkgsd-----stlqf
katkymavvtgeigklakmyffdthffteimeglcdarvgggpkmgy
>H
mpqalasygglplymgkflgppsglkagrcgtqpgrisiychpaltntkg
gtsyccfargpeeeh-----psdsspatnlfqvdkakdtwftlaaysntf
gcrqatvyltacgpmgkcrpv--cvgtksfatdmdl----ktqgegvkps
aglelantfnevkchkelvtfyitlvksvqlfvllccqipafiffnntes
ktiggneptetkpllrlgdvmtdpv--------------maqsffpcidk
lvnnqhakesipyhlssfr-deafkicrpeeetcqiss-pvrkktnaaiv
hynlflalppaitsqieivdtrg---slysdgtnapptcpindvsagdde
pegraganalpgvgefayatatfvpplpkqlvlactektaqfsriccesl
gkkfegltdipevlfgsgygkeiv------vfvdvqlsanccaglldcar
elletkahsglklllkylhgtsvllracaiygrysgkhsd-----sslqf
katmymavvtgdigklaemyfydshfyveiieglcnsrvgggpkmay
>node7
mpqvltsygglplymgkfigaqsglkae---sqpdrssifcraemtngrg
gtsyccfaagpdeer-----psdkapaahlfpvdepkrtwftlaaysnrf
gcrlagiyltacgpmdeskpv--vigtqkfatdmnv----ktqgeg-kvp
aslelpttfgevkcheklvsfyitlvvcvqmfvllccqlpafvflnvtet
ksiggndpteskpllrlgdvmhdpi--------------maqtffacank
lvnldhpkpsvpynsssft-negffpcrpddeacavsv-parktsnaaia
hynkilplppamtsqleivnark---slysdvtksppscpknetsgadda
pdgstgsnqipgvaefaygtatfvaplpkqlilg----aaqlswiccesl
gkkfeslsdipevhfgkgygkeii------vfan-hliakccdslldcak
elleskahsnlkmilnylhgsavllrgclyygrisgkgsd-----ktlqf
katkymavvtgeigklekmyffdthffteimeglcdarigggpkmgy
>node13
mpqvltsygglplymgkflgppsglkagrcgtqpgrisiychpaltntkg
gtsyccfargpeeeh-----psdsppaahlfqvdeakdtwftlaaysnrf
gcrqaavyltacgpmgncrpv--cvgtkkfatdmnl----ktqgegvkva
aslelattfnevkchdelvtfyitlvksiqmfvllccqipsfiflnntes
ktiggnepteskpllrlgdvmadpv--------------maqsffpcidk
lvnlqhpkesvpyhlssfr-devfrscrpeeetcqisn-pvrkksnaaiv
hyntilplppaitsqleivdtrk---slysdstkapptcpindvsagdde
pegrtganaipgvaefayatatfvpplpkqlilactesaaqfsriccesl
gkkfeglsdipevhfgsgygkeiv------vfvnvqlsanccaglldcar
elletkahsnlkllleylhgtsvllrgcmyygrysgknsd-----stlqf
katkymavvtgdigklakmyfydshfyteimeglcnsrvgggpkmgy
>node14
mpqvltsygglplymgkflgapsglkagrcgtqpgrasiycraeftntrg
gtsyccfargpeeer-----psdsppaahlfqvdeakktwftlaaysnrf
gcrlagiyltacgpmgnckpv--cigtkkfatnmnv----ktqgeg-kva
aslelattfgevkcheelvsfyitlvksiqmfvllccqlpsfvflnntet
ksiggnepteskpllrlgdvmadpv--------------maqsffacadk
lvnlehpkesvpyhlssfr-devfrscrpeeeacsisv-pvrknsnaaiv
hynkilplppaitsqleivdtrk---slysdvtknpptcpinevsgadda
pegrtganpipgvaefayatatmvpplpkqlilgctesaaqfsriccesl
gkkfeglsdipevhfgsgygkeiv------vfinvqlianccaglldcar
elleskahsnlkmlleylhgtsvllrgclyygrssgkgsd-----stlqf
katkymavvtgeigklakmyfydshfyteimeglcdsrvgggpkmgy
