>node14
awghhnyv-lcewrriksvtsgfpdkgyspilvhvdsgikdssegsdsqg
shgkaglakstwekhtlekenqyygmgkdacfyphldwaepgtaqkgsqs
kerhn-------inapy---flpggdsvfka-------ilaagaeplqyd
tddaisgtfglthglhdvlvpdavavtsvalrl----llkedthpgrvyw
mlclnwfskrkpalgqapltnhrkicqqgdi--lrdgqctq--earfcda
gsiktgpayykiadacvf-ndaaggrrqnanaptlgesvdstteaandcl
dedtfthsgkpgpvkpnac-dygaqaksnswklesfkraqlygqpkvkgn
mlegwgqdptnfdnqsaigglghaefeilmfhpfat-------hlfetgs
vgvelhesseqsvdackpeccctfhda-----gqmgfyiahactpgktre
vvqqhslafqkqktkhkthslkdtrncvrvlaetfgenggfnqlnkfagf
fetkfketaqegsavgtpldsstvkvvhfvkhlqivy---hernqrgqmt
pgftk
>F
gwghhnyv-lcewrriksvfsgfpnkgydpilvhvdsaikdssq------
-hgkaglakgslekhtfekgaqyygmgkdacfypnldwaepgtalkkaqs
kerhn-------inapykkryvpggdsvfra-------ileaggepleyd
tgdaisgafgl--glrdvlvpdsvgvtsvslrl----llkedthpgrayw
mlclswfskrkpalaqapltyhrkicqasda--lkdgpsaq--earfcda
gsiktgplsfkiadgcif-ddgasgrrqngdaptlgesv--tteaangcl
dddtfthsgkpgpvkpnap-dygaqaksnswnlesfkraglkgqpkvkgn
mlegwgqdptafdnqsaigglghaafevlmfhpfatkipegnfhlfetgg
mgvelhesseesvdackpkccctfqda-----gqiafyiahactpgktre
viqdhssatqkqktkhktdplkdtrkcvrvlagafgenggfsqlnkfagf
fetkfketalegnsvg----sstvkvpqfvkhfqlsyfdsnepnhrgqkt
paftk
>node7
awghhnyv-lcewrriksvasgfpdkgy--vlvevasgvkdssegtgsqg
sqgkaglakstwakhtmakdnqyigmgkhacfyphldwaepgiaqkgsqs
kekdd-------inapy---flpggdsvfks-------imaggaeplqyd
vddaisgsfglthgledvlvpntlavsaaalrl----llkddthagrvyw
mmcldwfskrkpaagqapltdhskisqqgdi--lrtgqcth--earfcea
gaik----------ncvftndaagnrrqtanapsltesvnsstklenhcl
nentfth-----------------qaksdswklesfkphqlfeqpkvkgn
mlegwgqdptn---qaaigglghaqfdflmihqfak-------qlfetgs
-gvelhpgseeavdpckgeccctfhda-----gqmgfyithactpakare
vvqqhstaf---knkhkthslndirncvrtlaetfgenggfnqlkkfagf
fdvkfketaqegsavgtpldsatvkvvhftihleivy---hernqrgkmt
pgftk
>A
asghhdyv-vcewrriksvasgfpdkgy--vlvevpsgikdneegtgsqg
sqgkaglakstwdkhtmakdnqymgmgkhasfyphldwaepgiaqkgsqs
kkkdd-------ingpy---flpgsdsvfks-------imaggaepldyd
vddaisgglglteglddvllpntlataaaalrl----llkddtnegrtyw
mmcldwfgkrkpsagqapladhskvnqqgdi--lhtghcth--enrfcea
gaik----------gcvftneitgnrrqtkrspkstepvnsstkvenhcl
nedvfth-----------------qaksdtwklesfkphklfeqpkrkgh
mlegwgqdptn---qaaigglghaqfdfvmihqfak-------qlfetgs
-gvelhpnseesvdpckgeccctfsdasvadlgqmgfhfthactpaksre
vvqqhstaf---ktkhkthslndfr---ralaqtfgqtegfnqqkkfggf
fdvkfketaqegsgvgtpldaatvkvvhftihlqivy---hdrnqrgkmt
sgftk
>node15
awghhnyv-lcewrriksvtsgfpdkgy--ilvhvdsgvkdssegsgsqg
shgkaglakstwekhtlekenqyygmgknacfyphldwaepgtaqkgsqs
kekhn-------inapy---flpggdsvfks-------ilaggaeplqyd
vddaisgtfglthglhdvlvpdtvavtavalrl----llkddthpgrvyw
mlcldwfskrkpalgqapltdhskisqqgdi--lrtgqctq--earfcda
gaik----------acvf-ndaagnrrqnanapsltesvnsstetenhcl
dentfthsakpgpvqpnac-dygaqaksnswklesfkrdqlyeqpkvkgn
mlegwgqdptnfgnqaaigglghaqfdflmfhqfat-------qlfetgs
lgvelhpsseqavdackpeccctfhda-----gqmgfyithactpgkare
vvqqhslafqkqktkhkthslkdirncvrtlaetfgenggfnqlnkfagf
fdvkfketaqegsavgtpldsatvkvvhfvkhlqivy---hernqrgqmt
pgftk
>C
awghhnfv-lcewrrvksvapgfpakgy--vl-evasgpndtsegtgsqg
sqgkaglaksswvkhsmandnqyigmgqhacfyphfdwaepgiaqkgsqt
qe------------aey---flpdgdavfks-------imaggaeplqyd
vdqaiagqfglthglpnvlvpktlavsaaelrlntsillqdethagrvyw
afclswfsnrkpa--sspltdhskighqgdisdfragqyah--edrfceg
gafk----------ncvftndavgnrrptanapsltetvhsstklenhcl
nehtfah-----------------qsksdnwklegfkphelfeqpkvkgn
mlegwgqdptn---qaaigplgsaqfdflmihllak-------hlfesgn
-gvdlhpgqeeavepckgeccctfhda-----nqmgfyithactpakare
vvqqhstaf---dnklrthnlndirdcvrtlaetlgesgsf--lkerdgf
fevkfketdqegsavetpldsatikvvhftihaeqly---hernqrgkmt
pgftk
>B
awghhdya-lcewrriksvasgfrdkgy--alvevppgvknseegtgsqg
sqgkgglakstwakhtiakdnsymgmgkhasfyphldwaepgiaqkgaqs
kkkdn-------inapy---flpgsdsvfas-------imaggaeplqyd
vddaisaglgltqglddvlvpaslavsaaalrl----llkedtnngrtyw
mmcldwfskrkpaagqapltddkkvnqqgdl--lhtghcth--edrfcea
gaik----------gcvftneaagnrrqvkkspkstqsvnsdtkvenhcl
nedkfth-----------------qaksdtwklesfkphklfeqpkvkgh
mlegwgvdptd---qaaigglghaqfdflmihqfak-------qlyetgs
-gvelhegseesvdpckgescctfhda-----gqmgfyithactpaksfd
vvqqhstaf---ktkhkthslndirscmr-----fgekggfsqlkkfagf
ftvkfketaqegsgvgtpldsatvrvvhftihlpivy---heryqrgkmt
pgftk
>H
awgdhnfvhlcewrryksvtsgfpdkgyspikvhvdvskrassegsdsqg
ahgksglaistwqkhtlekdnqyygmgkdgcfykhldwaepgtaqkgsqs
kdkqk-------fnapy---flpggdsvfka-------ilaagaeplmyp
tdqgisgtfglthglhgvlvpdaaavasvqlrl----llktdthpgsvyw
mfclnwfsktkpalgpapltnhrkicqqgdv--lrdgkctq--sarfcea
gsiktgpayykiadacvf-ndaaggrrqnanapkpgesvgstteaandcl
dqdtf-hsgkpgpvkpnac-dygseaksnswkiesfkraqlygqpkvkgn
ilegwsqnptnfdnqsaisglghaefeiamfhafat-------qlfetgs
vgvelhesseetvdackpeccctfhet-----gqmgfv---sctpgstre
vqqhsslafqkeknkhkthslkdtrscvkvlgetfgdkggfnqltkfagf
fyskfketetpgsavgttlesstvkvvhfvknlqivy---qdfnqksqmt
pgftt
>node6
awghhnfv-lcewrriksvasgfpakgy--vl-evasgpndssegtgsqg
sqgkaglaksswvkhtmandnqyigmgqhacfyphfdwaepgiaqkgsqt
ke------------aey---flpggdsvfks-------imaggaeplqyd
vdqaiagsfglthglpnvlvpktlavsaaelrlntsillqddthagrvyw
mmcldwfsnrkpaagqspltdhskishqgdisklrtgqyah--edrfceg
gaik----------ncvftndaagnrratanapsltesvnsstklenhcl
nentfth-----------------qaksdnwklesfkphqlfeqpkvkgn
mlegwgqdptn---qaaigplghaqfdflmihllak-------hlfesgd
-gvelhpgqeeavdpckgeccctfhda-----gqmgfyithactpakare
vvqqhstaf---dnkhkthnlndirdcvrtlaetlgenggfnqlkkkdgf
fdvkfketdqegsavgtpldsatikvvhftihaeqly---hernqrgkmt
pgftk
>node10
awghhnyv-lcewrriksvfsgfpnkgydpilvhvdsaikdsse------
-hgkaglakstwekhtlekekqyygmgkdacfyphldwaepgtalkgaqs
kerhn-------intpy---ylpggdsvfka-------ileaggepleyd
tgdaisgtfgltqglhdvlvpdavgvtsvalrl----llkedthpgrvyw
mlclswfskrkpalaqapltnhrkicqagdt--lrdgpctq--earfcda
gsiktgpasfkiadgcvf-ndgaggrrqnanaptlgesvdstteaanecl
dedtfthsgkpgpvkpnap-dygaqaksnswklesfkraqllgqpkvkgn
mlegwgqdptnfdnqsaigglghaefevlmfhpfatkipegnfhlfetgs
mgvelhesseqsvdackpkccctfhda-----gqmgfyiahactpgktre
vvqqhstayqkqktkhktdslkdtrkcvrvlaetfgenggfnqlnkfagf
fetkfketalegnsvgtpldsstvkviqfvkhfqlsyfdsheqnqrgqkt
paftk
>D
awghhnfv-lcewrridsvgsgfpakgy--al-evgsgpndssdgtgsng
sqgdaglaksswvkhtmanenqyigmgehacfypqfdweepgiaqkgsqn
ke------------aey---flkggdnvfkslhcyvnqimaggsnpleyd
adqaiagsfgl--glpnv-------vsaaelrlnssillqddthagrvyw
mmcldwfsnrkpaagqtpltdhskisrqgeisnlrtgqyah--edrfceg
gaik----------kcvftndaadnrsatanapkltes---ttklenhcl
nentfth-----------------qaksdnwklesfkphqlfeqpkvkgn
mlegwdqdptn---qnaiq-----qfdflmihlqsk-------hlfesgd
-gvelhpgqeeavdpckgeccctfhda-----gqmgfylthacqpakare
vvqqhstaf---dnkhkthnlndirdcvrtlaeklgengafsqpkkkegf
fdvkfketdqegsavgmatdtatikvvhftihaeqly---hernqrgkmt
pgftk
>E
vwghhn----cewrriksifsgfpnkgydpvllhvdsaikdsse------
-hgkaglakstwqkhtlekekqyygmgkeacffphldwiepgtalkgaqs
kerhn-------intpy---ylpggdavyka-------iletggepleyd
tgn----tfgltqglhdvlvpdavgcssvalrl----llkedthpgrvyw
llclswfakrkpklaqgpltnqskvcqagdt--lrdgpckq--earfcda
gsiktgpasfkiadgcvf-gdgaggrrqnanaptlgesvdspteaanecl
dedtfthsgkpgpvkpnap-dagaqaksnswklesfkraqllgqpkvkgk
llegwgvdptnfdnqsaigalghaefevlmfhpfatkipqgnfylfeggs
mgvelhysseqsvdackpkccctfhda-----gdmgvyiahgctpgktre
vvqqhctayqkqktkhktdslkdtrkcvrvleetfgenggfdqlkkfagf
fetkfketalegnsvgtpldfstvkgiqfmkh--lsyfdsheqskrgqkt
paftk
>G
awgdhnfvhlcewriikkvtsgfpdkgyspilvrvdssirassegsdsqg
sltkaglaistwekhsleadnqyygmgkdacyykhlewaepgtaqkgnqs
kdknnpapakllinapy---flpggdsvfka-------ylnagteplqyd
tdqgisgtfglthglydllvpdaatvtsvalrl----llkedthpgsvyw
myclnwisktkpalgpapltnhrkiceqgdv--lrdgqctqmgsarfcea
gsiktgpayykiadacvf-ndaaggrrqnanaptlgepvdstteglndcl
dedtf-hsgkpgpvkpnacvdygsqaksnswkinsfkraelydqpkvkgn
ilegwgqdptnigkqsaigglghaefelamnhsfvt-------hlfetgs
vgvelhepneesmdackpeccctyhdt-----gqmgfviahactpgktre
vhqhhnlafhkeknkhkthslkdtrncvkvlaetfgekggfnqltkfagf
fytkfketatagspvgtpldsstvkvvqfvknlqivy---hefnqrsqmt
pgftk
>node3
awghhdyv-lcewrriksvasgfpdkgy--vlvevpsgvkdseegtgsqg
sqgkaglakstwakhtmakdnqymgmgkhasfyphldwaepgiaqkgsqs
kkkdd-------inapy---flpgsdsvfks-------imaggaeplqyd
vddaisgglglteglddvlvpntlavsaaalrl----llkddtnegrtyw
mmcldwfskrkpaagqapltdhskvnqqgdi--lhtghcth--enrfcea
gaik----------gcvftneaagnrrqvkrspkstesvnsstkvenhcl
nedtfth-----------------qaksdtwklesfkphklfeqpkvkgh
mlegwgqdptn---qaaigglghaqfdflmihqfak-------qlfetgs
-gvelhpgseesvdpckgeccctfhda-----gqmgfyithactpaksre
vvqqhstaf---ktkhkthslndirncmrtlaetfgenggfnqlkkfagf
fdvkfketaqegsgvgtpldsatvrvvhftihleivy---hernqrgkmt
pgftk
>node13
awgdhnfvhlcewrriksvtsgfpdkgyspilvhvdssirassegsdsqg
shgkaglaistwekhtlekdnqyygmgkdacfykhldwaepgtaqkgsqs
kdrnn-------inapy---flpggdsvfka-------ilaagaeplqyd
tdqgisgtfglthglhdvlvpdaaavtsvalrl----llkedthpgsvyw
mfclnwfsktkpalgpapltnhrkicqqgdv--lrdgqctq--sarfcea
gsiktgpayykiadacvf-ndaaggrrqnanaptlgesvgstteaandcl
dedtf-hsgkpgpvkpnac-dygsqaksnswkiesfkraqlygqpkvkgn
ilegwgqdptnfdnqsaigglghaefeiamfhsfat-------hlfetgs
vgvelhesseesvdackpeccctfhdt-----gqmgfviahactpgktre
vvqhhslafqkeknkhkthslkdtrncvkvlaetfgdkggfnqltkfagf
fytkfketatagsavgtpldsstvkvvhfvknlqivy---hefnqrsqmt
pgftk
