>D
hegeragywglrklcttmkvggqvhdltlsevkvrahrll--teprasvr
hvaklplvwdkmfpeiqspgpnlknctfvgcfdkip--ngrk----l--k
apyhdvdnisalkrkldags--daq-------maqhgpakley----rhd
frdnvvpglfvlqqdrfypt-n--flwspgcsglavnqgrhtllkrtkdt
vqpdrwh-----pvsldnecaalsepvtwqmt---aqgvavkiegplegt
vy-dhrdq--siikfs-----llkncgyhenvfltamvfmvdlnlyavsm
mwnneavcrqqf--qerdgvpgvkrtggyqvaveglhsgsekvtyca---
----nlvwvpkscac--sqdsah--dphksverqcc--tlagevlm----
--lqia-g-kesgvafkipq--------tf------ipgedsdggfcemf
gthtqalfhkvgeryaglgsaafcclaev-s--gpdkpdqktkglsasly
sgntcpipsanlsgi---------pmkhlnlmgllnqgrdgktg-----y
gacavhggsktcevstevsyck-----------pevwtrdhditidl
>A
negdragyrglrklcptkkvgdlvhdvafsevdvslhrll--tdpkssls
hlaklpvvwdklfpeiqtkgp-vnnctfvgclekip-hnark----l-vt
aeysavdeitaikrkadaga--dpqaprmlkpmvqrcpakyeyplalrhe
sfndivpglfvlkedklfst-s--flwdpgcsalav--srrqllkstkdt
vqpvkwhah-----vldnecetlsepmawkkt---aqgvakkldgplegt
vy-dhkaqtvvitsfs-----lmkgcgyhenvflapmafmvdlnlypvtm
mwn-eavcrqqf--qeregvpgvkrtmgyivavkglqtgnekvayca---
----dllwapltcacfptqdsahfqdphksverqcc--tlaaenlm----
--le----------afklag--------af------lpgqdsdkgfcgtf
gthaqdvfhkaneryvglgtggfccladvasrgvpdypdhktkgltadlf
sanscpipsgnlsgi---------pvrqlsmvalldqerdgkts-----y
gaccvnggshtcqvdtgiqyck-----------pdiwtrahevvidf
>G
dngkktgyrglrklcsdkkvgdqvndlafsvvkirahrll--tepqssir
h------vwkklttgiqtkgpesn--tfvgcfdkip--narkgkgrl--k
aeyhdvdgliaikrknecgsmadal-------makrgpakyey----rhd
ffnevvhaififnqdkfystvnvhfvwepacsvlaiaqtrhtllksakgt
lqpvkwsaptkvptrldneyavlsepmswqvtycqaqgvatdldgplegt
vy-dqrtqivviitfn-----lmkgcgyaanvyltpmtl-------pvkm
mwn-eaacrqqfklqerggvpgvkssggyielvegletdtekvsycs---
----dvlwaartcacfpsqgsthfldphrsmerecc--slagetlm----
--vqqe-sgtedsyafkiag--------pfdafrnsipgedsesgscgmf
gtqtqdvfh----rynglgtpgfcclaqlagtfgptnpehmskglsadlf
sgnsgpvpsaklsnh---------pvkhltmrgllsqgrdrkas-----y
gdgcvhggsksvivhagvgyckfdy------sppdvwtrahevkvda
>B
hegdragyrglkklcptkkigdqvhdlafgevevslhrll--tdpkspvr
hlakmavvwdklfpeiqtkgpnvnnctfvgcftkip-h---k----l-vt
astsavdditaikrkadagn--vvq-------mvqhgpakyeypltlrye
tfndvvpglfvlkedcfyst-s--flwdpgcgalavsqnrrqllkstkdt
vqqvkwhah-----vldnecetlsepmawkkt---aqgvavklqgplegv
vy-sqkaqtvtitnfa-----llkgcgyrenvfltpmafmvdldlypvtm
mwn-eavcrqqf--qeregvpgvkrtlgyivavegldtgnekvayca---
----dllwaplscacfpsqesehfqdphkraerqcc--tlaganlmhtqg
edleva-gsyedtysfklag--------af------lpgqdsdrgfcgtf
gthaqdvfhknseryvglgsggfccladlasrggpdnpdnknkgl---lf
sanscpipsgnlsgv---------pvrhlsimslldqgrdgktsyhkady
gaccvkggahtcavdtnihyck-----------pavwtrahqitidf
>node14
dngkrtgyrglrklcstkkvgdqvhdlafsvikirahrll--tepkasvr
h------vwdklftgiqtkgpevnnctfvgcfdkip--nark----l--k
aeyhdvdgliaikrklecgsmadal-------makrgpakyey----rhd
ffndvvpglfvfkqdsfystan--flwepgcsvlaisqtrhtllksakgt
vqpvkwsahtkvptvldneyaplsepmswqmt---aqgvatklegplegt
vy-dqraqivviitfs-----lmkgcgyhanvyltpmtfmvdlniypvsl
mwn-eaacrqqftvqerngvpgvkrtggyiqlvegletgnekvayca---
----dvlwaartcacfpsqgsahfldphrsverecc--tlagetlm----
--vqva-sgtedsyafkiag--------pfeafrdsipgedsesgfcgmf
gthtqdvfh----ryaglgtpgfcclaqlastggpdnpdhktkglsadlf
sgnsgpipsanlsni---------pvkhltmrglldqgrdgkas-----y
gdccvhggsktcevntgvryckfdy------fppdvwtrahevkvdl
>node3
hegdragyrglrklcptkkvgdqvhdlafsevevslhrll--tdpkssvr
hlaklpvvwdklfpeiqtkgpnvnnctfvgcfekip-hnark----l-vt
aeysavdditaikrkadagg--daq-------mvqrgpakyeypltlrhe
sfndvvpglfvlkedrfyst-s--flwdpgcsalavsqsrrqllkstkdt
vqpvkwhah-----vldnecetlsepmawkkt---aqgvavklegplegt
vy-dqkaqtvvittfs-----llkgcgyhenvfltpmafmvdlnlypvtm
mwn-eavcrqqf--qeregvpgvkrtmgyivavegldtgnekvayca---
----dllwapltcacfpsqdsahfqdphksverqcc--tlagenlm----
--leva-ggyedsyafklag--------af------lpgqdsdkgfcgtf
gthaqdvfhkaneryvglgsggfccladlasrggpdnpdhktkgltadlf
sanscpipsgnlsgi---------pvrqlsmmslldqgrdgkts-----y
gaccvnggshtcevdtgiqyck-----------pdvwtrahevtidf
>node15
degkragyrglrklcptkkvgdqvhdlafsvikirahrll--tepkasvr
hlaklpvvwdklfagiqtkgpevnnctfvgcfekip--nark----l--k
aeyhdvdgitaikrkleags--daq-------makrgpakyey----rhd
ffndvvpglfvfkqdsfyst-n--flwspgcsvlaisqtrhtllksakdt
vqpvkwhahtkvptvldneyaplsepmgwqmt---aqgvavklegplegt
vy-dqraqtvviitfs-----lmrgcgyhnnvyltpmtfmvdlnlypvsl
mwn-eavcrqqf--qerngvpgvkrtggyiqlvegldtgnekvtyca---
----dllwaprtcacfpsqesahfldphrsverqcc--tlagenlm----
--vqva-ggtedsyafkiag--------af------ipgedsdsgfcgmf
gthtqdvfh----ryaglgspgfcclaqlassggpdnpdhktkglsadlf
sgnscpipsanlsgi---------pvkhltmmglldqgrdgkas-----y
gdccvhggsktcevntgvqyck-----------pdvwtrahevtvdl
>H
dngkttgyrglrklssdkkvgdqvhdlafsvikirahrml--tepkasvr
h------vwkklttaiqtkdpesn--tfvgcfdkip--nark----l--k
aeyhdvdglialkrknkcgsmadal-------kakrgpakyey----rhe
ffaevvhaififkqddfystvn--fvwqpacsvlaiaqtrhtllksakgt
vqpvkwsahtkvptvidneyavlsepmswqmtycqaqgvaeklegplegt
vycdqraqivvivtfstkgkvlmkgcgyhanvyltpmtf-------pasm
mwn-eaacrqqfslqerggvpgvk-tagyielvegldtdtekvpyca---
----dvlwaartcacfpsqgsthfldphrsmerecc--slagetlm----
--vqid-satedsyafniagglafdarspfdpfrngipgedsesgscgmf
gtqtqdvfh----ryaglgapgfccltqlastggptnqahmakglsadlf
sgdtgpipsarlsniglpiakkerpvkhltmrgllsegrdrkas-----y
gdgcthggskscivh-glmyckfdykndaqpfppdvwtrahevkldl
>node6
hegdragywglrklcptkkvgdqvhdlalsevkvrahrll--tepkasvr
hvaklpvvwdklfpeiqtkgpnlnnctfvgcfdkip--ngrk----l--k
apyhdvdditaikrkldags--daq-------maqhgpakyey----rhd
frndvvpglfvlqqdrfypt-n--flwspgcsglavsqsrhtllkrtkdt
vqpdkwh-----pvcldnecaalsepmtwqmt---aqgvavklegplegt
vy-dqraqtvtiitfs-----llkncgyhenvfltamvfmvdlnlypvsm
mwn-eavcrqqf--qerdgvpgvkrtggyivavegldsgsekvtyca---
----nlvwvprtcac--sqdsah--dphksverqcc--tlagenlm----
--lqia-g-kedsvafkipg--------tf------ipgedsdkgfcgmf
gthtqdvfhkvseryaglgssafcclaelassggpdnpdhktkglsadlf
sanscpipsanlsgi---------pmkhlsmmgllnqgrdgkts-----y
gacavhggsktcevstgvsyck-----------pdvwtraheitidl
>F
dngkrtsyrglrklcktkkvndqvhqmafsvirikahrlv--tepkasvr
h------vwdklftaiqtrgpevsncafvgcfdkip--aprk----l--k
aeyhdvqgivavgrkldcgsmadal-------miargpakye-----rhe
yfndvvpglhvfkqnsfysttd--flwepgcsvlaasqtrhtvlksakgt
vepvkwtahtsvpavldneyaalsepiswqls---aq----nlegplens
vy-dqraqivviitfs-----fvkgcgyhanvylssmtfmvdlniypvsl
mwn-naacreqftiqerngvpgvkrtggyiqlvegletgnekvaycttsd
cnkchvlwakrncmcfasqgsahfldphrsvqrecf--alaedtlm----
--vqva-sgtadmyafkiag--------pgeafrdklpgeafesg-----
atatqdvfh----r-aglgtggfcclaqlaetggadnpdhkvkglsgnlf
sgnsgpipsanlski---------pvkhltmrglldqgrdgkaa-----y
geccvhggsktcevntgvrkckfqy------fppdvwvrahe--val
>E
dngkrisyrglrklcstkkvddqvhdlafsiirikahrlvamtenkasvr
h------hwdklftaiqtkapevshctfigcfdkip--dprk----li-k
aeyhdvqgivavgrklgcgsmadal-------mikrgpakye-----rhs
ifndtvpglhvfsqdsfystan--flwvpecsvlaasqtrhtvlksakgt
vqpvkwtahtsapavldneyapltdplswqmt---tqgvatnleg-----
-y-dqraqivviitfs-----fmkgcgyhanvnltsmtfmvdlniypvsv
mwn-saasrdqfivqekngvpgakrtggyiqlvegletgdekitycatsd
cnkcdvlwakrtcacfpsqgsahfldphrsverecs--tlaeqtlm----
--vqva-sgtgetyafkiag--------pgeafrdklpgdasesgycgmf
gtdtqdvfh----rytglgsggfcclaqladtggpddpdnktkglsgdli
sgnsgpipssnvski---------pvkhltmralldqgwngkaa-----y
gdccvhggsktcevntgpryckfdy------fppdvwvrahevkvvl
>node7
hegdragyrglrklcptkkvgdqvhdlafsevkvrahrll--tepkasvr
hlaklpvvwdklfpeiqtkgpnvnnctfvgcfekip--nark----l--k
aeyhdvdditaikrkadags--daq-------maqrgpakyey----rhd
ffndvvpglfvlkqdrfyst-n--flwspgcsalavsqsrhtllkstkdt
vqpvkwhahtkvptvldnecaalsepmswqmt---aqgvavklegplegt
vy-dqraqtvviitfs-----llkgcgyhenvfltpmtfmvdlnlypvsm
mwn-eavcrqqf--qeregvpgvkrtggyivavegldsgnekvtyca---
----dllwaprtcacfpsqdsahfqdphksverqcc--tlagenlm----
--lqva-ggtedsyafkiag--------af------ipgedsdkgfcgmf
gthtqdvfhkvneryaglgspgfcclaelassggpdnpdhktkglsadlf
sanscpipsanlsgi---------pvkhlsmmglldqgrdgkts-----y
gaccvhggsktcevntgvqyck-----------pdvwtrahevtidl
>node10
dngkrtsyrglrklcstkkvddqvhdlafsvirikahrlv--tepkasvr
h------vwdklftaiqtkgpevsnctfvgcfdkip--dprk----l--k
aeyhdvqgivavgrklecgsmadal-------mikrgpakye-----rhe
ffndvvpglhvfkqdsfystan--flwepgcsvlaasqtrhtvlksakgt
vqpvkwtahtsvpavldneyaplsepiswqmt---aqgvatnlegplent
vy-dqraqivviitfs-----fmkgcgyhanvyltsmtfmvdlniypvsl
mwn-eaacreqftvqerngvpgvkrtggyiqlvegletgdekvaycatsd
cnkcdvlwakrtcacfpsqgsahfldphrsverecs--tlaeetlm----
--vqva-sgtgdtyafkiag--------pgeafrdklpgeasesgycgmf
gtdtqdvfh----rytglgsggfcclaqlaetggpdnpdhktkglsgdlf
sgnsgpipsanlski---------pvkhltmrglldqgrdgkaa-----y
gdccvhggsktcevntgvryckfdy------fppdvwvrahevkval
>node13
dngkktgyrglrklcsdkkvgdqvhdlafsvikirahrll--tepkasvr
h------vwkklttgiqtkgpesn--tfvgcfdkip--nark----l--k
aeyhdvdgliaikrknecgsmadal-------makrgpakyey----rhd
ffnevvhaififkqddfystvn--fvwepacsvlaiaqtrhtllksakgt
vqpvkwsahtkvptvldneyavlsepmswqmtycqaqgvatklegplegt
vy-dqraqivviitfs-----lmkgcgyhanvyltpmtf-------pvsm
mwn-eaacrqqfslqerggvpgvkrtggyielvegletdtekvpyca---
----dvlwaartcacfpsqgsthfldphrsmerecc--slagetlm----
--vqvd-sgtedsyafkiag--------pfdafrnsipgedsesgscgmf
gtqtqdvfh----ryaglgtpgfcclaqlastggptnpehmtkglsadlf
sgnsgpipsaklsni---------pvkhltmrgllsqgrdrkas-----y
gdgcvhggskscivhagvmyckfdy------fppdvwtrahevkvdl
>C
hegdragywglrklcptkkvgdevhdlalsevkvrahrll--tepkakvr
hvgklpvvkdklfpeiqtkgpnlddctfvgcfdkipl-tgrk----l--k
apyhdvdditackrrldggs--kaq-------mahhgpakyey----rhd
frkdvvpglfvlqqdrfypt-n--flwspvcsglavsqsrhtllkrtkdt
vqpdkwh-----pvcldnecaalsepmtwqms---aegvavklegplegt
ay-dqhaqiatvitfs-----llkncgyhenvflaamvfmpdlnlfpvsm
mwn-eavcreqy--adrdgvpgvkrtggyivavtgldsgsekvtycs---
----slvwvprtctc--cqdssh--dphksvprdccietlasdnlm----
--lqiadg-kedsvafkipg--------tf------ipgedsdkgfagmf
glhtqdvfhkvseryaglgspafcclaelasgggpdnpdhdtqglsadlf
sanscttpsanlsgi---------pmkhlsmmgllnqgrdgkts-----y
gacavhggsktcevstgvsycn-----------pdvwtkaheitidl
