>node13
frlkeggkr-----avktgsmglsgdnm-rnaeeakndekviatcataik
pfqyaavkpgklagqeknffrppsiweaygnkvikhgagkeavekkeahl
mltrrvnnytalkgig-fskdgtifgagdnkinktaeqtadlv-----cr
knsvageadfvha-----khgrdslwdrqidqi----------gkqrttg
vkpcgpgglfgltntsfaadsskenlafsdkvtddttvtarddvkdahqd
savtgwivg------tvkdssypmtrnpksvaqwftppggqpddigygrn
rv------tvsyrism--lncvvgtghhnr-----arkqgpcsf----mf
hveplcgsnqlslsp-----ren-ldvlegtlsvilkhtnlmalddspls
ayepvlf-----dmdfcgaltsrkti---qkwvrenkftlvpsrialgrv
tyhalcqgcwatal--gylhyesvgdklkaqtassksflhkndsdsarii
kvtcgqggcirraylvfrihhagagprvk-------sggtlnaksi----
tkvsepvtlkpvfadveskrkqels
>H
frlkeggkr-----avktgsmglsgddm-rkaeegkndekviascataik
pfqyanikpgklagqaknffrppsiweafgnkvikhgagkeavekkeahl
mltskvndytalkgig-fskdgtifgagdkkinktaeqtadlg-----cr
knsvtgeadfvha-----kherdslwdrqidqi----------gkqrttg
vkpcepgglfglt------nsskenlafadqvaddttvtardddkdahqd
savsawvvg------tvkdssypitrnpksvaqwftppgcepddigygrn
avttltratvshrism--lncvvgtghdnr-----arkqgpcwf----mf
hveplcgsnqlslsp-----rdn-ldvlegvlsvilkhtnlmalddspls
eyepvlf-----dmdfcgalasrnti---qksvrenkftlvrsrialgrv
tyhalcqgcwatal--gylhyesvgdklkaqtassksflqkndsdsarii
kvfcgqggcirraylvfrihhagagarvk-------sggtlhaksi----
tmvsepvtlkplfadveskrkgeln
>C
fsgdegtkah--gqelkngsvalsgdhm-rnaeeakddeklastcattid
tfqyavvrpgklvghkmnffrcnkywegygnkiithgagkdaneskdqhl
mltmrvkkytalkgigafakdgtvfgagakrinktaqqvadlaairagcr
knavansppfvge-----kqgrqslwtreihqnldae------gkqstsg
vkacgpgglfaltntsfvdegskekldfshkaadtatvtgredtkderqd
taltdwivs------lakessfpstrnpksvkqsftppagtskeigygnn
ll------vvsysvam--lscvv---hnnrtndlaahkqgscafltygmf
rrqplcssgq--lsp-----rh--idvlkgtsslpynhstqdaldddple
elapvlf-----dmnlcealtsnkay---qkavveskftlvpglevmgkv
myhglcq----tqq--ayy-yesig-klkggtetakcflhkndsdssrvl
kvicgqggckikpylvlqmpqagvgsnvk-------pagghaakslagkh
tdvsepvslkavftdvdskrkqtls
>B
frldaggkahqrgdavktgavalsgghm-rnaeeaknd--vastcatkik
tfvyavvrpgklvghkinffrchkfweaygnkvlghgaakekvakkdqhl
mltlrvrkytglkgigsfskdgttfgtgdknisktvvqvaslv-----cr
knavanepsfvhqgrkkhkhgr-glwd-qihqnlegq------geqrtsq
vvpcgpgglfaltstsfvddgsketlafstkvcdtatgtgregtkderrd
taqtgwlvg------vvtesnypstrkpkpvseaftvpggtskevgygan
rq------vvtyrvsm--lncav---hhnrtddlsarkqggcdfltsgmy
rreplcssnqvalsp-----rq-gldklqgsraldlnhsyldanqtdple
elaavlfflncedmsycgaltsqkpy---qkaereskftlvptliamgdv
iyhglcqacwstaq--ayfhyealg-klkhgtssaksfihkndsdttrvv
kvfcgqggciikpylvfaihsasvgpnvk-------qvgglaaksiggkq
tnvsepvalkslftkveskrkqkls
>G
frlkeggqr-----avktgsmglsgdnm-rnaeeakndekiiatcataik
pfqhsavkpgklagqennffrppsiweaysnkvikhgag----ekkeahl
mlssrvnnftslkgig-fskdgtifgvgenkinktaeqtadlv-----cr
knsvageadfvha-----khgrdslwdrqidqi----------gkqrtgg
vapcgpgglfgltntsfaadkskehlafsdkltddttvtarddvkdahqd
stvtgwvvg------tvkdgsypmtrnpksvaqwftppggqpddvgygrn
rv------tvfyrism--lncvvgtghhnr-----srkqgpcsf----mf
hvdplcgeyqlslsp-----ren-ldvlegtltvmlkhsdlmalddspls
aydpvlf-----amdfcgpltsrksi---rrwvrenkftlvpsrialgrv
tyhalcqgcwatdl--sylqyesvgdklkaqtassksflhkndsdsarii
kvtcgqggcirraylvfrihhagagprvk-------sggtlnaksi----
tkvsdnltlkpvfadaenklkqeln
>F
frlkeggkw-----avktgsmalkaddm-rsaeeakniekvpatcataik
pfqyaavkpgklpgqkknffrchkiwegyankvishgagkeavekkeahl
mltkrvnnytafkgi----edgti-----------aeqtttfv-----cr
knavageacfvhi-----khgrdslwnrqidqi----------gkqkpsg
vkpcgpgglfgltntsfaadktkeklafsskvtdhttvtarddvkegrae
spqtgwivgkpangstvkessyhttrkpksvaqrftppggqsdeigygsn
rv------vvsyhvam--lncvv---hqnp-----arkegpcsf----kf
qadpvcgsnqlg---paealtq--ldvlegtlsiifkhtylkafddspls
alakvlf-----dsdfcgalterkta---qkgvreakftlvphrialgqa
syhalaqgcwatalatgylhyesvg-klsastaaaksflhknkrdsaiit
kvtcgqgrci---ylvfqihhagagprvkyldckqlpggtlnvksi----
tdvsepvtlklvypdveskrkqqqs
>node6
frldegtkah--gdelktgsvalsgdhm-rnaeeakndeklastcattik
tfqyavvrpgklvghkknffrchkfwegygnkiithgagkeanekkdqhl
mltmrvkkytalkgigsfakdgtifgagakkinktaeqvadlaairagcr
knavanspsfvgq-----kqgreslwdreihqnldge------gkqrtsg
vkpcgpgglfaltntsfvaegskeklafshkatdtatvtgrddtkderqd
taqtdwlvg------lvkessfpstrnpksvkqsftppggtskeigygsn
rv------vvtyrvam--lncvv---hnnrtedlaahkqgscafltsgmf
rrqplcssgq--lsp-----rq--vdvlegtrslplnhsyldaldddple
elapvlf-----dmnfcqaltsskay---qkavreskftlvpgliamgkv
myhglcq----tqq--ayyhyesig-klkggtetaksflhkndsdssrvl
kvicgqggciikpylvfqihqagvgpnvk-------pggglaakslagkh
tnvseplalkavftdvdskrkqels
>D
frldeetkah--gdelktgsvlisgdhm-rnaeeavkddklastcattik
tyqyavvrpgklvghnknffrchkfwegygnkiishgagkeanekkdq--
-lgrqvkkytankgignfakdgaifgdgakkinktaeqvadlaairagcr
kntvantpsfvsq-----kqskeslwdreihqnldge------gkhrtsg
vkpcgpgglfaltnssfvaegskeklafshkandtadvtgrddttdtred
naqtdwlvg------vikegqfpstrnpksvkqsftppnstsseigygsn
kv------vvtyrvam--lhcvv---hdnkkedlaahkqgscafltsgmf
rkqplcssgq--lsp-----rq--vdvlegtvslplndsyldald-----
elqpvtf-----dmnfcqaltsakay---qkavrepkfpmvpglfamgkv
myhglcq----tqq--ayyhyesig-k-----etaksflhkndsdssrvl
kvicsqggciikpylvfqiheagvgpnvk-------pggglaakslagkh
snvtepfalkavftdvdskrkqels
>node15
frlkeggkqh--gsavktgsvalsgdnm-rnaeeakndekvpatcataik
pfqyavvkpgklaghkknffrchkfweaygnkvithgagkeavekkeahl
mltrrvenytalkgig-fskdgtifgagdkkinktveqtadlv-----cr
knavageasfvhq-----khgreslwdrqidqi----------gkqrtsg
vkpcgpgglfgltntsfaaesskeklafsnkvtdnatvtgrddvkddrqd
taqtgwlvg------avkdssypstrkpksvaqwftppggtskeigygan
rv------vvtyriam--lncvv---hhnr-----arkqgscdf----mf
raeplcssnqlglsp-----re--vdvlegtrsiilnhsyldalddnpls
alapvlf-----dmnfcgaltsrkti---qksvreskftlvptliamgkv
tyhglcqgcwataq--ayfhyesvg-klkgstssaksflhkndsdssriv
kvtcgqggciikaylvfqihhagvgprvk-------pgggldaksiggkq
tnvsepvtlkavfpdveskrkqels
>node7
frldeggkah--gdavktgsvalsgdhm-rnaeeakndekvastcataik
tfqyavvrpgklvghkknffrchkfweaygnkvithgagkeavekkdqhl
mltmrvkkytalkgigsfskdgtifgagdkkinktveqvadlv-----cr
knavanepsfvhq-----khgreslwdrqihqnlegq------gkqrtsg
vkpcgpgglfaltntsfvaegskeklafsnkvtdtatvtgrddtkderqd
taqtgwlvg------lvkessypstrkpksvsqsftppggtskeigygan
rv------vvtyrvam--lncvv---hhnrtedlaarkqgscdfltsgmf
rreplcssnqlglsp-----rq--vdvlegtrslplnhsyldaldddple
elapvlf-----dmnfcgaltsrkay---qkavreskftlvptliamgkv
iyhglcqgcwataq--ayfhyesvg-klkggtstaksflhkndsdssrvv
kvicgqggciikpylvfqihhagvgpnvk-------pggglaaksiggkq
tnvsepvalkavftdvdskrkqels
>node14
frlkeggkr-----avktgsmalsgdnm-rnaeeakndekvpatcataik
pfqyaavkpgklagqkknffrchkiweaygnkvishgagkeavekkeahl
mltrrvnnytalkgig-fskdgtifgagdkkinktaeqtadlv-----cr
knavageasfvhq-----khgrdslwdrqidqi----------gkqrtsg
vkpcgpgglfgltntsfaaesskeklafsdkvtddttvtarddvkddrqd
saqtgwivg------tvkdssypstrkpksvaqwftppggqsddigygrn
rv------vvsyriam--lncvv---hhnr-----arkqgpcsf----mf
qaeplcgsnqlglsp-----re--ldvlegtlsiilkhtylkalddspls
alapvlf-----dmdfcgaltsrkti---qksvreskftlvpsrialgrv
tyhalcqgcwatal--gylhyesvg-klkastssaksflhkndsdsarii
kvtcgqggcirraylvfqihhagvgprvk-------pggtlnaksi----
tnvsepvtlkpvfpdveskrkqels
>node3
frldeggkah--gdavktgavalsgnhm-rnaeeaknd--vastcattik
tfvyavvrpgklvghkknffrchkfweaygnkvithgaakekvdkkdqhl
mltmrvrkytelkgigsfskdgttfgagdkninktvvqvatlv-----cr
knavanepsfvhqarkkhkhgreglwd-qihqnlegq------gkqrtsq
vvpcgpgglfaltstsfvadgsketlafstkvsdtatgtgrentkderqd
taqtgwlvg------lvtessypstrkpkpvseaftppggtskeigygan
rv------vvtyrvsm--lncvv---hhnrtedlaarkqggcdfltsgmf
rreplcssnqvalsp-----rq--ldplegsrslqlnhsyldanetdple
elapvlfflncedmsfcgaltsrkay---qkaereskftlvptliamghv
iyhglcqacwstaq--ayfhyeavg-klkngtssaksfihkndsdtsrvv
kvicgqggciikpylvfqihhasvgpnvk-------qvgglaaksiggkq
tnvsepvalksvftkvdskrkqkls
>A
yrldeggksh--gdavktgavalsgnhmaraaeefkne--vasacvstik
tlayavvrpgklvahkknllrchkfweafghkvithgaakekvdkkdqhl
lltmrvrkytelkgigsfskngctfgagdksink-vtrvatlv-----cr
knavgnepsfvhqarkkhkhgreglwd-qvhqnlegqgdtkippkqrksq
vvpcgagglfalastafvadgsketlafstkvsdtatgtgrentkderqd
taetgwlvs------lvtessypstrkpkpvseaftppggtseeigygan
ri------vvqyrvsmaclncvv---hhnrtedlaarkqegcdfltsgmw
rreplcssnqvalsp-----rq--ldplegnrslqlnhsyldaketeple
elaevlfflscedmsfcgeltsrkayvdaqkaereskftlvptliamghv
iyhglsqgcwstaq--ayfqyeavg-klktgtssaksfihkndsdtskvv
kvicgqggciikpyliiqihhasvapnvk-------qvgglaaksiggkq
tnvservalksvftkvdtkrkqklp
>node10
frlkeggkr-----avktgsmalnadnm-rsaeeakndekvpatcataik
pfqyaavkpgklagqkknffrchkiweaygnkvishgagkeavekkeahl
mltrrvnnytalkgig-fsqdgtifgagdkkinktaeqtttfv-----cr
knavageasfvhq-----khgrdslwnrqidqi----------gkqrpsg
vkpcgpgglfgltntsfaaektkeklafsskvtddttvtarddvkddrad
spqtgwivgkpangstvkdssyhttrkpksvaqwftppggqsddigygsn
rv------vvsyriam--lncvv---hhnr-----arkqgpcsf----mf
qaepvcgsnqlgkspppealte--ldvlegtlsiifkhtylkalddspls
alakvlf-----dadfcgalterkti---qkgvreakftlvphrialgrv
tyhalcqgcwatalatgylhyesvg-klkastssaksflhkndrdsarit
kvtcgqgrcirraylvfqihhagagprvkyldckqlpggtlnvksi----
tdvsepvtlklvypdvdskrkqels
>E
frlkeggkr-----alktggmslnadnm-rsaeeakngekvpatsataik
pfqyaavkpgklagqkknffrcrkiweaygnkvishgagkeavekkeahl
mltrrvnnyaalkgig-fsqdgtlfgagdkkinktaeqtgtfv-----cr
knavageasfvhq-----khgrdslwnrkiddi----------vkqrpsg
akpcgpgglygltntsfaaektkeklafstkvtddttvtakddvkddrad
spqtgwivgkpaagstvkdsafhtthkpkrvaqwftppggqsddigygsn
rv------vvsyriam--ldcvv---hhnl-----arkqgpcsf----mf
qaepvcgsnqvgkkpppealte--ldvlegtlsiifkqtylkalddspls
alakvlf-----dadfcgalterrtv---qkgvreakftlvphrialgrv
tyyalcqgcwatsl----lhydsvg-klkastgsaksilhkndkngarns
kvtsgqgrcirraylvfqihhagagprvkyldckelpggalnvkni----
tdvsepitlklvypdvdsqrkqeld
