>node10
flkveg-----lkkdqsktpipa-------w-lpwelsdggcvgcidsnk
idgdtgateevf---ytaetwekmktv--kaiicgseslkpis------t
lgnklsegagpkpsgvlem----kclgldermpslstfheiqqpvq----
----lsgtvdlcpkf-leyaatkppehnpl-tkd--actyphhgqlklfd
vpkn-tnnc---nl-ldnhgefslvecttngtsvphannalrgghflyvt
kaettqasrdhpnk---nlgicgisavagggtkvsggiclsfkacewsvs
wrsfamvgllkpeqlcytannskksfyftyavkgmrdffakdgskeggna
lndkacvrwgdqdsiinvlkfvdhhpknvgvisgdpvnfpaaarpgpfhs
scgrglrekepanqynvhakgaly--ngkvkiiqrewcvranlpnkgse-
----gkrasgpfvvesvnvslcerrtqtfnvadstdkkkaagvkcqatwv
rsrgqhcralecigyfnarrv-snadvkeccteapkcagvgsaevqfdhk
haafrvvlktfakrhkvlmkng
>node13
flkmeg-----lkkdhaktpipa-------w-lpwelldggvvgcidsnk
idgdtgatqevf---ysaetwekmkngkqkyiicgseslkpas------t
lgnkldegagakpsgvlem----kclglddrmptlstfndvnqpvq----
----lsgtvrlcpkf-laydatkppdsnal-kkd--sctyph--------
--kn-tnnc---nl-lddhgefsvvecttngtsvthant------flyva
kaatsqagrdhpnq---nlgvcgisrvagggqkvsggiclsfkacewcin
wrnfavvnllkpeqlcytannskksfyfttavkgmrdffagngakesgna
lndkssvrwgdqdsiisvlkfvdhhpkdvgvvdgdpvdfpaatrpgpfhs
scgrglrekvpadqykvhpkgalypgngkvki--rewcvranlpnkgsd-
----gkratgpfivesitvslcerrtqmfnvadstdkkkaagvkcqaswv
rgrgqhcralecigyyntrrv-snadvkvccaeapkcagvgsaevqfdhk
haafhvilktfakrhkklvkns
>node6
flkmeg-----lskdhakapipi--avgtlw-lnwglndggcsgciesne
idgdtgiteqvf---ysneswekmkfd--kaiicgddsmkptsrkhsvqt
ipnklsegagegppgvlqm----kslgseesmpslstfnsidqpvqmrys
qffslagtvricpkf-ldydatkppesnal-tpd--sctyphhgql-lld
vpkn-tnnc---nl-lndrgessllectsdgtpithaht------flyva
keettqaamdqasq---nlglcgisriagggqkvsggmclafkgctwcin
wrafavvnllkpeklcftdnnsgkafyftyevkgkrdfyvgdgakeggnt
lkdkacvrwgepdliinvlsfvdhhshevgvvagdpvdfeav--------
-sgrglreneppdqyqvhpkgslc--ngkvkiqqrdnctrsnleakgde-
----gktssgpfvaesvsvslvqrrthlfdvadsadkkkkagvkcdatwv
rgrgehcralesigifdaqra-pdadveecctespkcagvgtatvhfdhk
hasfhiilksfvkrhkklakfs
>A
flkkeg-----lkkdhakepipi-------w-lnwgladggcsgciesnk
idgdavatenvf---ysaeswekmkfd--kaiicgddsmkptsrrhsvqs
mpnklaegagagpsgvlel----kclgvdtrmpslktfntvnlpvq----
----lagtlhvcpdf-ldydptrppesnpl-lkd--sctypqhgql-lle
vpkn-tnnafianltindhgessllkctsdgtpitqaht------flyvg
keqttqaamdrasq---nlglcgisrialggtkvsggmclaykgctwctq
wrsfavvdllkpeqlcfatnnsgkaiyftyaqrgmrdflvgdgakavsnt
lkdklctrwgeqdpfinvlkfvdhhskeigviagqpvnf-----------
-sgrglwdkepadeyqvnpkgvlc--ngkvkiiqrenckrsnleakgdeg
qklmgkrasspivvespslslcqrrantfdnaepadkdkkagvkcaatwv
rgrgehcraleniailntrrt-skadvkeccnelpacagvgtatvqfdhk
nasihiilksyvrrhkklakns
>node7
flkmeg-----lkkdhakapipi-------w-lnwglsdggcsgciesnk
idgdtgateevf---ysaetwekmkfd--kaiicgddsmkptskkhsvqt
ipnklsegagagpsgvlem----kclgveermpslstfnavdqpvq----
----lagtvhicpkf-ldydatkppesnal-tkd--sctyphhgql-lld
vpkn-tnnc---nl-indrgessllectsdgtpithaht------flyva
keettqaamdqasq---nlglcgisriagggtkvsggmclafkgctwcin
wrsfavvnllkpeqlcyttnnsgkafyftyavkgmrdffvgdgakeggnt
lkdkacvrwgeqdpiinvlnfvdhhskevgviagdpvdfpat--------
-sgrglrekepadqyqvhpkgslc--ngkvkiiqrenctrsnleakgde-
----gkrasgpfvvesvsvslcqrrthmfdvadsadkkkkagvkceatwv
rgrgehcralesigifdtrra-snadvkeccteapkcagvgtatvqfdhk
hasfhiilksfvkrhkklvkns
>C
flrmeg-----lskdhtkapkpi--avgtlw-lnwglndggcagciesne
idgdtgiteqvf---ysneswdkmkfd--kavicgddskkpvsrkhsvqt
ipnklkesagegppgvlqmldqggslgseesmsslssfdsidqpvqmrys
qffslagtlricpkf-ldydatkppesnal-tpdhtsckyphhtql-lld
vpke-nnnc---nl-lndrgessllectsdgtpiahaht------flyva
kddttqaamdqasqatqnlglcgisrfagggdkvgggmclafkgctwcin
wrafavvnllkpdklcftannsgkafyftyavkgkrefyvgdgakeggnt
ikdkscvrwgepdlirkvlsfvdhhshevgvmagdpvdfeav--------
-sgrglrpneppdqyqvhpkgslc--lgkvkiqqrdnctrsdlegkgde-
----gktssgpfvaesvsvslvqrrahlyevadsadkkkkagvkcdatwv
rgrgehckslesigifdaqr---dadveecctdgskcagvgtatvhfghk
hasfhiilksfvkrrkklakfs
>E
flkveg-----hkkdqsktpipp-------w-lpwelsdggcvgcidsdk
idgdtgateevf---ytaetwekmktv--kaiicgsdslkpil------t
lgnklsegggpkpsgvlem----kclgldermpslssfheiqrpvq----
----lsgtievcpkf-lewaatkppehspl-trg--actyphhgqlklfd
vpkd-tnnc---nl-ldnhgefslvectpngtsvphannaarsghflyht
kaettqasrvqpnk---nlgicgisaqngggtkvsggiclsfkacewsvs
wrgfamvgllkpedlcytansskksfyftyavkgmrdffakdgskeggna
lndkacvrwgsqdsfintlkfvdhhpknvgvhsgnpvnfpaaarpgpfks
scgrglrekepsnaynvrakgaly--ngkvkiiqrewcaraslpskgse-
----gkrasgp-vvesinvslcerrtqafkvaestkkkkaggqkcqaawe
rsrgqhcralecigyfnarrv-snadvmeccteagkcagvgspevqfehk
haafrvvlktfakrhgvlmkng
>node14
flkmeg-----lkkdhaktpipa-------w-lpwelsdggcvgcidsnk
idgdtgatqevf---ytaetwekmktg--kaiicgseslkpas------t
lgnklsegagakpsgvlem----kclglddrmpslstfnevnqpvq----
----lsgtvhlcpkf-leydatkppesnal-tkd--sctyphhgql-lld
vpkn-tnnc---nl-lndhgefslvecttngtsvthant------flyva
kaettqaardhpnq---nlgvcgisrvagggtkvsggiclsfkacewcin
wrsfavvnllkpeqlcytannskkafyftyavkgmrdffagdgakeggna
lndkacvrwgdqdsiinvlkfvdhhpkdvgvisgdpvdfpaaarpgpfhs
scgrglrekepadqykvhpkgaly--ngkvkiiqrewcvranlpnkgse-
----gkrasgpfvvesvtvslcerrtqmfnvadstdkkksagvkcqatwv
rgrgqhcralecigyfntrrv-snadvkeccteapkcagvgsaevqfdhk
haafhvilktfakrhkklvkns
>D
flkmeg-----lskdhvkapipi--avgtlw-anwglpeggcsgciesne
idgdtginqqvf---ysneswekitfd--kapicgndsmkptsrkhsvkt
ipnklsegagegppgvlqm----kslgseesmpslptfnsidqpvqiryt
qffslagtvricpkf-lnydatkppesnal-tpd--sctypnrgql-lld
vppn-tnnc---nl-lnergessllectsdgtpithaha------flyvs
keetaqaamdqasq---nlglcaisriagggqkvsggmclafkgctwcfn
wrafvvvnllkpeklcftdnnsgkafyftyevngkrdfyvgdaakdggnt
lknkacvrwgesdliinvlsfvdhhshevgvvagdivdfeav--------
-sgmglrenefpeqyqvhpkgslc--naavkiqqrdnctrsnlgakgde-
----gkissgifvsesvsvklvqrpthlfdvansgdkkkhagvkcdatfi
rgsgelcralesigifdaqragpgaeveeccsespkcagvgtatvhfdhk
hasfqiilksfvkrrkklakfs
>node15
flkmeg-----lkkdhaktpipa-------w-lnwglsdggcsgciesdk
idgdtgateevf---ytaetwekmkfg--kaiicgndslkpts------t
lgnklsegagagpsgvlem----kclgiedrmpslstfnavnqpvq----
----lsgtvhicpkf-ldydatkppesnal-tkd--sctyphhgql-lld
vpkn-tnnc---nl-lndrgessllecttngtsvthant------flyva
keettqaardqanq---nlglcgisriagggtkvsggiclafkgctwcin
wrsfavvnllkpeqlcyttnnskkafyftyavkgmrdffagdgakeggnt
lndkacvrwgdqdpiinvlyfvdhhpkevgviagdpvdfpaa--------
-cgrglrekepadqyqvhpkgsly--ngkvkiiqrewctrsnleakgde-
----gkrasgpfvvesvsvslcqrrthmfdvadstdkkksagvkcqatwv
rgrgehcralesigffdtrrv-nnadvkeccteapkcagvgsavvqfdhk
hasfhiilksfakrhkklvkns
>node3
flkmeg-----lkkdhakepipi-------w-lnwglsdggcsgciesnk
idgdtvateevf---ysaetwekmkfd--kaiicgddsmkptsrkhsvqs
ipnklsegagagpsgvlel----kclgvdtrmpslstfnavdlpvq----
----lagtlhvcpdf-ldydptrppesnpl-lkd--sctypqhgql-lld
vpkn-tnna---nlsindrgessllectsdgtpitqaht------flyva
keqttqaamdqasq---nlglcgisrialggtkvsggmclaykgctwctq
wrsfavvdllkpeqlcyatnnsgkaiyftyaekgmrdflvgdgakevsnt
lkdklctrwgeqdpiinvlnfvdhhskevgviagqpvnfpat--------
-sgrglrekepadeyqvnpkgslc--ngkvkiiqrenctrsnleakgde-
----gkrasspfvvesvslslcqrrahtfdnadpadkkkkagvkcaatwv
rgrgehcralesiaivdtrra-skadvkecctevpkcagvgtatvqfdhk
hasihiilksfvkrhkklakns
>B
flkmegcneenlkkdhakepipi---------lnwglstggcsgciesnk
idgktvateevf---ysaetwekmkfd--kaiicaddamkptsrkhgvqs
vpnklsegagegpagvldl----kclgvdtrmpslstfnavdipvq----
----lagtlhvcpdytldydptrppesnpl-lrd--sctypqhgel-lln
vpkdptnna---nlsindrgetsllectsdglpitqaht------flyva
keqttqapmdqash---nlslcgisrialggtkvsggmclaykgcswctq
wrsfsvvdllkpeqlcyatnnsgkaiyftlaekgmrdflvgdgakdvsnt
lkdklctrwgeqdriinvlhfvdhhskevgviggqpinf-----------
--grglrekepadeyqvnpkgslc--ngkakiiqrenctspslqakgde-
----gkrasspfivesvslstcqrrahtfdnansadkrkkavvkcaatwv
rgrgeacralesiaivdtrra-skaevkecctevpkcagvgtatvqfdhk
haskqtilksfvkkhkklakns
>G
flkmdg-----lkkdqaktpipa-------w-lpwelldggvvgcidsnk
ikadtgstqevf---ysletwekmkngkqkyiacgaeplkpas------t
lgnlldegagakpsgvlem----kclgledrmptlstfndvnqpvq----
----lsgtvrlcpkf-laydatkppdanallkkd--sctyph--------
--kn-qnnc---nl-lddhgefsvvectangtsvthant------flyva
kaatsqagrnhpnq---dlgvcginrvggggqkvgggiclsfkacewcin
wrnfavinllkpeqlcytannskksfyftttvrgmrdffkgngakesgna
lndkssvrwgdqdsiisvlkfvdhnpkdvgvldgdpvdfplaqrpgpffe
scgralrekvpaeqysvhpkgplypgngkvkl--rewcvrpglpnkgsn-
----gkratgpfiveaitvslcerrtqmfnvadstdkkkapgvkcqaswv
rgrgqhckalecvgynnvrrv-snhdvtvccaeapkcagvgsaevqfdhk
haafhvvlktfanrhkklvkhs
>F
flkveg-----lkkeqsktpipatk-----w-lpweledggcvgcsdskk
idgdtgatdelf---ytaltwgkmrtv--kaiicgsdplkpis------t
lgnklsegagpkpsgvlem----kclgldermpslstfheiqqivq----
----lsgtvdlcpkf-leyastkplehnpl-tkd--acthphhgqlklfd
vpkn-tnnc---nl-ldnhgefslvecttdgtsvphainalrggyflyvt
rftkteasrdhpnk---nlgicgitavagggtklsggicpsfkiaewsvs
wrsygmvgllkpeqlcytadlskkpfyftyvvkgmrdffakdgskeggna
lndkacvrwgdqdsiinvlrfvdhhpknvgvisgdavnfpaaaqpgpfhs
scgrglrekdpanqynvhakgaly--ngkvkicqrewcvsanlpnkgsk-
----gkrasgpfvvetvnvslcerrtqtfnvadstnkkkpagvkcratwa
rnrgqhcralecigyfnarrv-snydvkeccteaprcaglgssevqfdhk
haayrvvlqtfakrhkvlmkng
>H
flkmeg-----lkrdhaktpipp-------whlpwelldggvvgcidsnk
idadtgatqevfpgpfsaetwekmkngkqkyiicgseslkpag------t
lgnklddgadpkpsgvlem----kclgldqrmptlssfndvnqpvq----
----lsgtirlcpkf-lafdatkpadsnal-kkd--sctyph--------
--kk-tnac---nl-lddhgefsvvqcttngtsvthakt------flyva
kaatsqagrddpnq---nlgvcgisrvagggqkvsggiclsfkacelcin
wrnfavvnllkplqlcytannskksfyfttalkgmmdffagngakesgna
lndkssvrwgdsdslisvlkfvdhhpkdvgvvdgdpfdfpaatrpgpfhs
scgrglrekvpaeqyklhpegalypgngkvav--rdwcvkaslpnkgsd-
----gkratgpfihesitlslcerrtqmfnvadstgkkkaagvkcqaswv
rgrgqhcralecigyyntrrv-snadvkvccaeapkcagvgsgevqfdhk
haafhvifktfvkrhkklvkns
