>D
kgltlhfdestitqvti--raieshastriqkqvmlnfi----iltykad
leeccsnfgpgkvallashlswnmpgskfdgkkpkaadlvcshdnaisev
hghshtglsnknaakgylpphvvtekllttthrdapfalllgfkpldsrp
glgmrkfqvikegrfifgetktklqgssllgpfrnhkhygvhaepvaspd
cvrelap----hsdegeekpke----ctshynhdsksfsgvpvlygwpkf
katfntasninredi--tqektsltehfigcpysgv----kskp-s--gg
lvggigakifng----laiftnmasfskaegkaclvsdpdllg----ifk
e----kklqkyiedgrlpirgvgptrgdhlylpggqvwyndatfriq---
-fydnggpthdinapd------sfsdvkhaaagghthipidieqc--nhc
hclkpakapcmklvagvaeckkasrckvvntylrltka---qiqsvemdq
llgdtatnlnpqgpdygvhnvlytsahvf----lfiqykfiahvgylve
>node6
kgltlhfdtrtitqvtl--rainshasakiqkqvmmtfs----iltykad
leeccsnfgpgkvallashlrwnmpgskfdgkkpkaadlvcshdttispv
aghshtglanknaakgylpphvltekalttthrdaafslllgfkpldsrp
glgmrkfqvikegrftfgetktklqgssllepfrnhkhygvhaepvasts
cvrelap----hsdeaeekpke----ctshynrdskmfmgvpvlagwpkf
sgtfnvasninredi--tqektfltihfigcpyagv----kskp-s--ag
lvggigakifng----lavftdmasfstaegkgclvsdpdllg----ifk
ec--kkklqkyieqgrlplrgvgptrgellylpggqvwyndatfsiq---
-fydnggpthdinapd------sfsdvknaaagghthipidleqc--nhc
nclkpakapcmklvanvaeckkasrclvvntylrltka---qiqsvemdq
lladtatnldpqgpdygvhnvlytsahvf----lfiqykfiahvgylve
>node3
ksltlnfdtrtitqlvl--raidthasakiqedvmltfs----iltykak
geeccnnfgpakvallashfrwimpgskfgdkkpkatdlvcshdttprtv
aghshtglsnkneakgylppyvltekamttahrdaafhlllgfraldgrp
alglrkfqvikegrftfgetdtklqgssllepfrnhkhfggnaepvaags
cvrelap----hsseveekpkedqvlcanhynrdakmfmgvavvaslpkf
clafnvqsninrndi--rqaktfltihflgcpyagv----kskpks--ag
lvpgigakifng----lpvyrdmasfstadgkgclvadpdlla--ggllk
ec--kkkihvyidqgrlalrgagptrgellylpggqvwyndatfsvq---
-fynnggptqdigvddaihltysfsdvkn-----hthiaielgacsvnhc
nclkpakapcvklvanvaecnkasrclvvnaylrltkt---hiqsvamdd
llretatnldpqgpdygvhdtlytcahgf----vfipykfvahpdylve
>node10
qgla------tltqlsl--rritphasakiqeqvvmtfstiwgiltykad
gegccstfspskvallasrlrwimpgskigakkpkaedlvcshettpatg
adh-higlankngapaylgpyvltykamttahrdaafhllfgfrakgtrp
algl-sfqviketrftfndpktklqgptllepfrnhkrfggnaepvgsls
cirelap----nesaaeekpke----cdstynks----mavpaahslpkf
sltfnvesnisrdnv--rhddtflsyhfvgcpyagv----kkkp-ainag
lvggigakifnd-arilpvfndmvsfstsrgkgclvsdpalla--ggglk
acehkkklhkvidqgrlalrgig-apaqllylpggqvwykdtyfsvk---
-fyddgglthdigvdeamnltykfsdpknaasnghthipidlstc--nhc
nclnstkapciklilgvseckkasrclhvaqilrttgapfgqiq--smeh
llraaatklhpakpnfgchdvfyssahhm----fyipykyvdhvgylae
>node15
ksla------titqltl--raisphasakiqeqvmmtfs----iltykad
geeccstfgpakvallasrlrwimpgskigakkpkasdlvcshdttpstv
agh-hvglankngakgylgpyvltykamttahrdaafhllfgfralgsrp
alglrkfqvikesrftfgetktklqgssllepfrnhkrfgghaepvasgs
cirelap----hsseaeekpke----cashynrsspmfmavpvvhslpkf
cltfnvesninredi--rhdktfltihfvgcpyagv----kskp-sinag
lvggigakifng----lpvftdmasfstskgkgclvadpalla--ggvlk
ecehkkklhkvidqgrlalrgigptraqllylpggqvwyndatfsvq---
-fyddggpthdigvddainltysfsdvknaasdghthipidlgqc--nhc
nclkptkapcmklvlnvaeckkasrclvvnaylrttka---qiq--amdh
llraaatkldpagpdygvhdviytsahaf----lfipykyvdhvgylve
>C
kgltlhfdtrtiaqvtl--rainshasakiqkqvmmtfs----iltykad
leeccanfgpgkvallishlrwnmpgpkfdgkkpkaadltcshdttispv
dghshaglanknaakgylpphvltertlttthrdaafslllgfkpmdkre
glgmrkfavikegrftfgetktklqgssllepfrnhkhygvhaepvasts
cvrelap----yndeaeekpke----ctshydrdskt---vpvlagwpkf
agtfavashinredi--tqektfltihfigcpyagv----kskp-s--aa
lvggigarifng----lavftdvtsfsaaegkgclvsdadilg----ifk
ec--kkklakyieagrlplrevgptrgellylpggqlwnngsafsiq---
-fydngepthdakapd------sfsdvknasagghthvpidleqa--ghc
nclkpakapcmklvlnvaeckkasrclvvntylrltka---qiqsvemdq
lladtaanldpqgpkyavhgvlytsahvf----lfidykfvahvgylve
>G
kgla------tltqlsl--reitphtpakiqdevmmtfstiwailtykad
gegccaswgpakvallasrlkwimpaskvgakrpksedlvcshdtpp--v
adh-higlantngapgylgpyvltykhmatahrdaafqllfgfralgtrp
alglskvqviteskfsfneaktklqaptllepfrnhkrfgghaeptgsgs
cikelap----htsesddkpke----caphydks----mavpavhnlpkf
sagfnvesainrddi--phddtflsyhfiacpyggvdspqdkkp-einag
lvgsvvakvfgs----lpvftdmvgfekskgkgclvadpallacggsglk
scqhkkklhkvvdqgrlalhgig-apaqllclpggqvwykdayfsv----
------glthdigvneavnldfsfssvknaakdghthiptdlsqc--khv
nclkptkapcialivgvaackkasrcfhvpnylrttnapfgqvq--smeh
llraaptklhpanpnfgchdviftstqaf----ffipyqyldrvg----
>node14
kgla------tltqlsl--rqitphasakiqdqvmmtfstiwgiltykad
gegccstfgpakvallasrlrwimpgskigakkpkaedlvcshdttpstv
adh-higlankngapgylgpyvltykamttahrdaafhllfgfralgtrp
alglrkfqvikesrftfneaktklqgptllepfrnhkrfgghaepvgsgs
cirelap----hsseaeekpke----cashynks----mavpavhslpkf
sltfnvesninrddi--rhddtflsyhfvgcpyagv----kkkp-sinag
lvggigakifnd----lpvftdmvsfstskgkgclvadpalla--ggglk
acehkkklhkvidqgrlalrgig-apaqllylpggqvwykdayfsvk---
-fyddgglthdigvdeavnltysfsdvknaasdghthipidlsqc--nhc
nclkptkapciklilgvaeckkasrclhvanylrttnapfgqiq--smeh
llraaatklhpagpdfgchdvfytsahaf----ffipykyvdhvgylve
>F
qgla------tliqlsl--qritphataqvqqqvvmtfstiwgiltykae
gesccstflpckvallasrlrwimpgskkg----kaedlvcahettpatg
adh-higlansngppaylgpyvltykamttahrdagfhlkfgfrakgtrp
algl-sfqvikearftfndpktklqaptllepfrnhkrfggnaepvgsls
cikelap----seaaaeekake----cdstynka----mavkaahslpkf
slsfnaesnisrdnv--rhddtflsyqfvgcpyagv----kkkp-atngg
lvggiggkifndmvrilpvfndmvsfttsrgkgclvgdptlla--ggglk
acehkkklhkvinqgllalrgig-apaqllylpagqawykdtyfsvk---
-fyddggltreigveqamnltykfsdpknaasnghthipidlstc--nhc
nclnstkapciklilgvsaakkasrclhvaqilnttgapfgqiq--smeh
llraastklhpakpnfgahdvfygsahhm----fyypykyvdhvgylae
>E
qgla------altqlsl--rritphasakiqeqvvmtfstiwgiltykad
gegccstfspsktellasrlrwimpgskigakkpkaeslvcghettpatg
adh-higlanknnapaylgpyvltykamttahrdaafhllfgfrakgtrp
aigl-sfqvikearftfndpktklqgptlleafrnhkkfggnadpvdsls
cirelap----nesageekqke----cdstynks----mavpaahslpky
sltfnvewniskdnvlfrhddtflsihyvgcpyagv----kkkp-avnag
lvggigakif-n-arilpvfkdmvsfstsrgkgclvsdpalla--ggglk
acehkdelhkvidqgrlglrgig-apaqllyligtqvwykdtylsvk---
-fyndgsltndigvdeamnltykfsdpknaasnghthipidlssc--nhc
sclnstkapciklvlgvseckkasrclhvaqilrttgapfgqiq--smdh
llraaatklhpahpnfachdvfysaahhmafwvfyipfkyvdhvgylne
>H
kgla------terqpaltrrqitphthakiqdavmmtfsm--giltyktd
gegccadfgpdkvallasrlrwimpgskvgakkpksedmvcahdtqp--v
adh-vigldntngapgylgpyvltykamatahrdaafhllfgfralgtrp
dfglrkfqvikeskfsfnesktklqgpsllepfrnhkrfgghaepvgsgs
ciaelaaeynlhtseaddkpke----caphynks----mavpavhempkf
slafnvesaihrddi--phddtflsyhfigcpyagvdspqkkkp-sinag
lvggigarvfgs----lpvftdmvgfstskgkgclvadppllacggsglk
acrhkkklhkvedqgrlalrgig-apaqllclgggqvvykdayfsv----
---degglthdigvneavdltfsysevknaakdghthipidltkc--nhc
nclkftkapcirlilgvasckkasrcfqvpnylrttgapfgqiq--smeh
llraaltklhpanpgfgchdvfftetqef----ffipykyvnkvgylve
>node13
kgla------tltqlsl--rqitphtpakiqdqvmmtfstiwgiltykad
gegccasfgpakvallasrlrwimpgskvgakkpksedlvcshdtqp--v
adh-higlantngapgylgpyvltykamatahrdaafhllfgfralgtrp
alglrkfqvikeskfsfneaktklqgptllepfrnhkrfgghaepvgsgs
cirelap----htseaddkpke----caphynks----mavpavhnlpkf
slafnvesainrddi--phddtflsyhfigcpyagvdspqnkkp-sinag
lvggigakvfgs----lpvftdmvgfstskgkgclvadpallacggsglk
acqhkkklhkvvdqgrlalrgig-apaqllclpggqvwykdayfsvk---
-yyddgglthdigvneavnltfsfsdvknaakdghthipidlsqc--nhc
nclkptkapcirlilgvaackkasrcfhvpnylrttnapfgqiq--smeh
llraaatklhpanpdfgchdvfftstqaf----ffipykyvdrvgylve
>B
kglvlnfdtrtvthlll--ravdthapakvqedvmltfs----iltynay
gedcchnfgpaklallashfrwimpgskfgdkkpkanelvcshdttprtv
aghshtslgnkneskgylppyiliekamttahrdaafhlllgfraldgrp
alglrkfevikegritfghtdtkvqgpslldpfrnhkhfggnaepvaags
yvrelap----lssqleekpkeeqtlcanhynrdaklfqgvavvaslpkf
clafnaqfeinrndi--rqaktfltihflncpyagv----kskpks--ag
lvpgigaeifng----apvyrdlaafssadgkgclvadpdllp--ggllk
ec--kkkipvyidqgrlalrgaggnrgellylpggqvwyndavfsvqvva
dfynnggptqnigvddaihltysftdvkn-----hthvaielgacsvnhc
nclkpakkpcvklvanvlecnkasrclvvnaylrltkt---hiqsvamdd
llretaanldhqgpdygvhdtlftcahgf----vfipykfithpdylve
>A
ksltlnfdtrtitqlvl--raidthasakiqedvmllfs----iltykas
geeccnnfgpakvallashfrwimpgskfgdkkptatnlvcshdttprtv
aghahtglsnknegkgylppyvltekamttahrdaafhlllgfrvldgrp
alglrkfhvikegrftfgdtdtklhgsslleplrnhkhfggnaepvaags
clrelap----hssevedkpkedqvlcanhynrdkmmfmgvavvaslpkf
clafnvesnivrndi--rqaktfltihflgcsykgi----kskpka--ag
lvpgigakifng----lpvyrdmasfstadgkgclvadpdlla--ggllk
ec--kkkihvyidqgrlalrgagptrgdllylpggqiwyndrtfsvq---
-fynnggptqeigvddaihltysfsdvkn-----hthiaielgapnvhhc
tclkpakapcvklvahvaecnkasrclvvnaylrltkt---hiqsvamde
llrgtatnlepqgpdygihdtlyscaqgf----vflpykyvshpdylve
>node7
ksltlhfdtrtitqltl--rainshasakiqeqvmmtfs----iltykad
geeccsnfgpakvallashlrwimpgskfgakkpkasdlvcshdttpstv
aghshtglankngakgylppyvltekamttahrdaafhlllgfraldsrp
alglrkfqvikegrftfgetktklqgssllepfrnhkhfgghaepvasgs
cvrelap----hsseaeekpke----cashynrdskmfmgvpvvaslpkf
cltfnvesninredi--rqaktfltihfvgcpyagv----kskp-s--ag
lvggigakifng----lpvftdmasfstaegkgclvadpdlla--ggvlk
ec--kkklhkyieqgrlalrgigptrgellylpggqvwyndatfsvq---
-fydnggpthdigvddaihltysfsdvknaaagghthipidlgqc--nhc
nclkpakapcmklvanvaeckkasrclvvnaylrltka---qiqsvamdq
llrdtatnldpqgpdygvhdvlytsahaf----lfipykfvahvgylve
