>node7
tyti--------rrhtekttrhklapvgltkrahgafeaqalccvefeae
g---vtyfidam-pskvghkcctskafsesyierskipcilgtaldagil
rlkghtdrnigvtghgmnqesngqaalavralsellqeghkkaleggsgd
-grdei-lvavelnfadmlllednenckvkvavkkntlfcqcar----nc
mnvtaeglnpgselkiagecikvckaekgtdnlyv----gpgftsap---
hqgvaqpacasvrplytyldentqacknykgwidtewv---gkfslpta-
---irpvahktatnkykmgwsdpaekatvgigqacsegarphkgevsvkk
lghasi--qprvgddkysyqlnqm---qnfkdrsslcnsgtfkgarsafp
ccsflekecggrlalgshlkgcqlkeihivfgfkmqkqc---------ee
arhcqqkfmsvikariapalgsts-kahgchgtayrlaffftfeadrrdf
wgswnlavpkcesqtneeesflhadekaknewkrpv-vts--dknwe--r
l
>ENV_HV2BE/24-510
ayaf--------krhtnkttryklgpvglnkrahgafttqalcclefeie
g----nyfigimapskighkvctskgfsdsyierskf-cltgsalgagil
rlkglnernigvtgngtneeanghsallsgals--lqqkhkkalqqgcge
-greea-lvavtlnftdmllfeenetvkvkvavkkntvfcqcir----kc
lnvtaegldpgadlkiaaecikvckaekgkdslyv----gpgftsap---
hqgvahpacasvrplygynddnsqacktykgwidcewv---gqfaqptsg
nrri--vahktttakyrmgwhqpsdkntvg-gqgcaegakahkgevnvkk
lghats--gprvgkdnfsyelntm---qgfkdrsslctsgtfngatgafp
ccsflekecggkitvgcnlkgcqlkevhiyfgfkmqkkc---------ed
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wgswnltvpkcdsgtneevswlhageraknewnrpt-sas--dknwahgr
l
>ENV_SIVGB/47-569
tykf--------rrnggsklshnlahvgltkramgnft------vdfean
gtteityfingm-pskvehkcctsgafsemyaecskvacllgtaleagil
rlkghtgravgvtshg------gqsalavgals--vqeghkkaleggged
pgrddi-lvcvdlhfaetlllednenckvkvgikknkkfcrclrgaeenc
mgvaaeglepaaeasfagecikvckgergkdklyv----sprfe------
-qgvsqpacksvkakytylden---vknyqgwiv--------qfalrsg-
---irpvahktatnrykmgwdnssvkaslgvgqhcgagtephkdevsvtr
lghasi--qtrcsndkysyalnhmhsvegfkdrnsq----------sqfs
ccsyldkecgasialgshlkdcqvkdldivfgmkmqkqc---------ea
arhyqqkfmsvvkawiavalgatsd--hgchgaaysfafffafeadrkrf
wgswtlavpkcdsqeneqhsflhapekakadwmqvv-vas--sknwe--r
l
>node11
ayaf--------krhtnkttryklgpvglnkrahgafttqalcclefeie
g---vnyfietmapskighkvitskafsesyierskf-cltgsalgagil
rlkghdernigvtghgmneeanghsallsgals--lqqkhkkalqqgcge
-greea-lvavtlnftdmllleenetvkvkvavkkntvfcqcir----nc
lnvtaegldpgadlkiaaecikvckaekgkdslyv----gpgftsap---
hqgvahpacasvrplygynddntqacktykgwidcewv---gqfalptsg
krri--vahktttnkyrmgwhqpsekttvg-gqgcaegarahkgevsvkk
lghats--gprvgkdkfsyqlntm---qgfkdrsslctsgtfngatgafp
ccsflekecggkitlgcklkgcqlkevhiyfglkmqkqc---------ed
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wgswnltvpkcdsgtneevsflhaderaknewnrpt-sas--dknwahgr
l
>node9
tytf--------krhtnkttryklgpvgltkrahgafttqalcclefeie
g---vnyfietmapskighkvitskafsesyierski-cltgtalgagil
rlkghternigvtghgmneeanghsallsgals--lqekhkkalqqgcge
-greea-lvavtlnftdmllleenetvkvkvavkkntlfcqcir----nc
lnvtaeglnpgadlkiaaeclkvckaekgkdslyv----gpgftsap---
hqgvahpacasvrplytynddntqacknykgwidcewv---gqfalpts-
---irpvahktttnkykmgwhqpsekatvg-gqgcaegarphkgevsvkk
lghatl--gprvgtdkfsyqlnqm---qgfkdrsslctsgtfngatgafp
ccsflekecggkialgsklkgcqlkevhiyfglkmqkqc---------ee
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wgswnltvpkcdsgtneevsflhadekaknewnrpt-aas--dknwehgr
l
>node10
ayaf--------krhtnkttryklgpvgltkrahgafttqalcclefeie
g---vnyfietmapskighkvitskafsesyierskf-cltgsalgagil
rlkghdernigvtghgmneeanghsallsgals--lqekhkkalqqgcge
-greea-lvavtlnftdmllleenetvkvkvavkkntlfcqcir----nc
lnvtaeglnpgadlkiaaecikvckaekgkdslyv----gpgftsap---
hqgvahpacasvrplydynddntqacktykgwidcewv---gqfalptsg
krri--vahktttnkyrmgwhqpsekttvg-gqgcaegarahkgevsvkk
lghats--gprvgkdkfsyqlntm---qgfkdrsslctsgtfngatgafp
ccsflekecggkitlgcklkgcqlkevhiyfglkmqkqc---------ed
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wgswnltvpkcdsgtneevsflhadekaknewnrpt-sas--dknwqhgr
l
>node18
ayaf--------krhtnkttryklgpvglnkrahgafttqalcclefeie
g---vnyfieimapskighkvitskafsdsyierskf-cltgsalgagil
rlkghdernigvtghgmneeanghsallsgals--lqqkhkkalqqgcge
-greea-lvavtlnftdmllleenetvkvkvavkkntvfcqcir----nc
lnvtaegldpgadlkiaaecikvckaekgkdslyv----gpgftsap---
hqgvahpacasvrplygynddntqacktykgwidcewv---gqfalptsg
krri--vahktttnkyrmgwhqpsekttvg-gqgcaegarahkgevsvkk
lghats--gprvgkdnfsyqlntm---qgfkdrsslctsgtfngatgafp
ccsflekecggkitlgcklkgcqlkevhiyfglkmqkqc---------ed
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wgswnltvpkcdsgtneevsflhaderaknewnrpt-sas--dknwahgr
l
>ENV_SIVM1/24-528
tytf--------krhtnkgtryklgpvgltkrahgafttealcclefeie
g---vnyfietmapskighkvitskafsesyierski-cltgtalgagil
rlkghternvgvtghgmneeakghsallsgals--lqerhkkalqqgcge
-grdea-lvavtlnftdmllleenetvkvkvaqkkntlfcqcir----nc
lnvfaeglnpgadlkianeclkvckaekgkdalyv----gpgftsap---
hqgvahpacasvrhlytynddntqacknykgwidcewv---gqfalpts-
---irpvahktttnkykmgwhppsekagvg-gqgcaegarphkgevsvkk
lghatl--gprvgtekfsyqlnqm---qgfkdrsslctsgtfngatgafp
ccsflekecggkialgsklkgcqldevhiyfglkmkkqc---------ee
vrhcqqkflsvvktpiapslgsts-davgchgvayllaffymfeaprrdf
wgswnltvpkcdsgtneevsflhadekaknewnrpt-aas--dknwehgk
l
>ENV_SIVV1/24-538
tyti--------rrhtekttrhklapvgltkrahgsfeaqalccvefiad
g---vtyfiham-pskvghkcctskafsesymerskipcilgsaldtgil
rlkdhtdrnigvtnqgmhqesngqaaldvralgellqdehkkaleggsgd
-grdei-llpvelnfadmlllednenckvkvavgkntlfcqcar----nc
mnvtaeglnpgdqlkiageclkvckaekgtdnlyv----gpgftsap---
hqgvaqpacvsvrplytyldkniqacknykgwidtewvqgfgkfsltta-
---irpvdnktatnkykmgwsdpagkatv-igqacsegarphkgevsmkk
lghasinreprvggdkyyyqlnam---qnfkdrtslcnsgtfkgarsafp
ccsflqkecrgplalgshlkgcqlkeihivfgfkmqkqc---------de
arhcsqkfesvikariapalgsts-kangchgteyslaffftfeadrq--
-gswklavpkcesqtneeesflhcdekaknewkrpv-vtn--ekgre--r
l
>node17
ayaf--------krhtnkttryklgpvglnkrahgafttqalcclefeie
g---vnyfieimapskighkvitskafsdsyierskf-cltgsalgagil
rlkghdernigvtghgmneeanghsallsgals--lqqkhkkalqqgcge
-greea-lvavtlnftdmllleenetvkvkvavkkntvfcqcir----nc
lnvtaegldpgadlkiaaecikvckaekgkdslyv----gpgftsap---
hqgvahpacasvrplygynddntqacktykgwidcewv---gqfalptsg
krri--vahktttnkyrmgwyqpsekttvg-gqgcaegarahkgevsvkk
lghats--gprvgkdnfsyqlntm---qgfkdrsslctsgtfngatgafp
ccsflekecggkitlgcklkgcqlkevhiyfglkmqkqc---------ed
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wgswnltvpkcdsgtneevsflhaderaknewnrpt-sas--dknwahgh
l
>node8
tytf--------rrhtekttrhklapvgltkrahgaftaqalccvefeae
g---vnyfidam-pskighkcctskafsesyierskipcllgtaldagil
rlkghtdrnigvtghgmnqeangqsalavgals--lqeghkkaleggsgd
-grdei-lvavelnfadmlllednenckvkvaikkntlfcqclr----nc
mnvtaeglnpgselkiagecikvckaekgtdnlyv----gpgftsap---
hqgvaqpacasvrplytyldentqacknykgwidtewv---gqfslpta-
---irpvahktatnkykmgwsdpsekatvgigqacaegarphkgevsvkk
lghasi--qprvgddkysyqlnqm---qnfkdrsslcnsgtfkgarsafp
ccsflekecggsialgshlkgcqlkeihivfglkmqkqc---------ee
arhcqqkfmsvikariapalgsts-kahgchgtayrlaffftfeadrrdf
wgswnlavpkcdsqtneeesflhadekaknewkrpv-vas--dknwe--r
l
>ENV_HV2G1/23-502
ayaf--------krhtnkktryklgpvglnkrahgafttqalcclefeia
g---vnyfintmapskighkvitskafsessierskf-clkgsalgagil
rlkghdernigvtghgmneeanghsallsgalt--lqqkhkkaleqgcge
-greea-liavtlnftdlllleenetvkvkvavkkntvfcqcir----nc
lnvtaegldpgadlkiaaecikvckaekgkdslyv----gpgftsap---
hqgvahpacasvrplygynddntqacktykgwidcewv---gqfalptsg
krri--vahktttnkyrmgwhqptekttvg-gqgcaegarahkgeltvkk
lghats--gprvgkdkfsyqlntm---qgfkdrsslctsgtfngatgafp
ccsflekecggkitlgcklkgcqlkevhiyfglkmqkqc---------ed
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wsswnltvpkcdsgtneevsflhadersknqwnrpt-sas--dknwahgr
l
>ENV_HV2D2/24-513
ayaf--------krhknkttryklgpvgltkrahgafttqalccvefeia
g---vkyfietmapskiphkvitskafsesyierskf-cltgsalgagvl
rlkghdernigvtghgmneeadghsallsgals--lqekhkkalqqgcge
-greea-lvavtlnftdmllleenetvkvkvavkkntlfcqcir----nc
lhvtaeglnpgadlkiaaehikvckaakgkdslyv----gpgftsap---
hqgvahpacgsvrplydynddnsqacstykgwidcewv---gqfalptsg
erri--vahkvttnkyrmgwerppekttvg-gqgcaegarahkgdvrvkk
lghats--gprvgkekfsyqlntm---qgfkdrsslctsgtfngaaggfp
ccsflekecgkkitlgcklkgcqlkevhiyfglkmqkqc---------ed
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffyafeaprrdf
wgsanltvpkcdsgtneevsflhadekaknewnrptksasgcdknyqhgr
l
>node19
ayaf--------krhtnkttryklgpvglnkrahgafttqalcclefeie
g---vnyfieimapskighkvitskafsesyierskf-cltgsalgagil
rlkghdernigvtghgmneeanghsallsgals--lqqkhkkalqqgcge
-greea-lvavtlnftdmllleenetvkvkvavkkntvfcqcir----nc
lnvtaegldpgadlkiaaecikvckaekgkdslyv----gpgftsap---
hqgvahpacasvrplygynddntqacktykgwidcewv---gqfalptsg
krri--vahktttnkyrmgwhqpsekttvg-gqgcaegarahkgevsvkk
lghats--gprvgkdkfsyqlntm---qgfkdrsslctsgtfngatgafp
ccsflekecggkitlgcklkgcqlkevhiyfglkmqkqc---------ed
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wgswnltvpkcdsgtneevsflhaderaknewnrpt-sas--dknwahgr
l
>ENV_HV2NZ/24-502
ayaf--------krhtnkttryklgpvglnkrahgafttqalcclefeie
g---vnyfieimapgkighkvitskafsdsyidrskf-cltgaalgagil
rlkghdernigvtghgineeanghsgllsgals--lqqkhkkalqqgcgs
-grdea-lgavnlnftdmlllqenetvkvkvavkknsifcqcir----nc
lnvtaegldpgadlkiaaecikvckgekgkdslyv----gpgftsapidp
hqgvahpacasvrplygynddntqacktykgwidcewv---aqfalpisg
ksri--vahktttnkyrggwyqpsekttvg-gqgcaegarahkgevsvkk
lghats--gprvgkdnfsyqlntm---qgfrdrsslctsgtfngat---p
ccsflekecggkitlgcklkgcqlkevhiyfglkiqkqcfklslsdsldd
vrhcqqkylsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wgkwnltvpkcdsgtneevsflhaderaknewnrpt-sas--dknwahgh
l
>ENV_SIVG1/22-522
tyti--------rrhtekttshklapvgltkrphgafeaqalccvafead
g---vtyfidam-pskvghkcctskafsesyiersdipcilgtaldagil
rlkghtdknigvtghgmnqesngqaalavraltellqeghkkaleggsgd
-grdei-lvavelnfaaklllndnenckvkvavkkntlfcqcar----nc
mnvtaeglnpgselkiagecikackaekgtdnlyvarlkgpgftsap---
hqgvahpacasvpplytypdentqacktykgwidtewv---gkfslpta-
---irpvahktatnkykmgwsdpaekatvgi--acsegarphkgevsvkn
lgsasv--qprlgddkysyqlnql---qnfkdraslcnsgtfkgarsafp
ccsflekecggrlalgshlkgcqlgeihivfgfkmqkqc---------ee
arhcqqkfisvikarianalgsks-kahgchgtayrlaffltfeadrrdf
wgswnlavpkcesqtneeesflhadekaknewkrpv-vty--dknwe--r
l
>node14
ayaf--------krhtnkttryklgpvglnkrahgafttqalcclefeie
g---vnyfieimapskighkvitskafsdsyierskf-cltgsalgagil
rlkgldernigvtghgmneeanghsallsgals--lqqkhkkalqqgcge
-greea-lvavtlnftdmllleenetvkvkvavkkntvfcqcir----nc
lnvtaegldpgadlkiaaecikvckaekgkdslyv----gpgftsap---
hqgvahpacasvrplygynddntqacktykgwidcewv---gqfalptsg
krri--vahktttnkyrmgwhqpsdkttvg-gqgcaegarahkgevsvkk
lghats--gprvgkdnfsyelntm---qgfkdrsslctsgtfngatgafp
ccsflekecggkitlgcklkgcqlkevhiyfglkmqkqc---------ed
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wgswnltvpkcdsgtneevsflhaneraknewnrpt-sas--dknwahgr
l
>ENV_HV2CA/25-512
ayaftqvskggfkrhtnkttryklgpvglskrahgafttqavcclefeie
g---vnyfieimapskighkvitskafsdtyierskf-cltgsalgagil
rlkghdernigvtghgmneeanghsallsgals--lqqkhkkalqqgcge
-greeavlvavslnftdmllleenetvkvkvavkkntvfcqcir----nc
lnvtaegldpgpdlkidadcikvckaekgkdslyv----gpgftsap---
hqgvahpacasvrplygynddntqacktykgwidcewv---gqfalptsg
krri--vahkttsnkyrmswyqpsekttvg-gqgcaegsrahkgevivkk
lghats--gpsvgkdnfeyqlntm---qgfkdrsslctsgtfngatgafp
ccsflekecggkitlgcnlkgcqlkevhqyfglkmqkqc---------qd
vrhcqqkflsvvktpiapslgsts-davgchgvayvlaffytfeaprrdf
wgnwnltvpmcnsgtneevsflhaeerqknewnrpt-sas--dktwengh
l
>ENV_HV2D1/24-501
ayaf--------nrhtnktnryklgpvglnkrahgafatqalcclefeie
g---vnyfieimapskighkvetskafsdcyierskf-cltgsalgagil
rlkgldernigvtghgmneeanghsallsgala--lqqkhkkalqqgcge
-greea-lvavtlnfidmllleenetvkvkvavkkntvlcqcir----nc
lnvtaegldpgadlkiaaecikdckaekgkdslyv----gpgftsap---
hqgvahpacasvrplygynddntqacktykgwidcewv---ghfslptsg
krri--vahktttnkyrmewhqpsdkttvg-dqgcaegarahkgevsvkk
lghats--gprvgkdnfsyelntm---qgfkdrsglctsgtfngatgafp
ccsflekecggkitlgckakgcqlkevhiyfglkmqkqc---------ed
vrhcqqkflsvvktpiapslgsts-davgcdgvayvlaffytfeaprrdf
wgswnltvpkcdsgtneevsflhantraknewnrpt-sas--dknwahgr
l
