>ENV_HV2G1/23-502
rvdsalssaygdqtwkctgvtckvpksifiidrdgwielntgysyflpaf
caemf--------dwkehcqathcklglsqlfgctklagatnntll---p
tslirffafvplgkadrsfmavndnkcasapqilvd------agekleat
agdrsqtydkrglfakshinqsmighsks----sestndgeqtvklg-cp
akfsnfkkkwsvnvshstsasikr---vlnk------mnnkqalggneet
a---vqegillyvsgtgcvdgfftcgtnvklnvpkfgfecppkaksa---
-glcfagcaddgtvrsggkptlrprahpp--vlkgceaqklngri--lpe
tg---setacsapfvsrgeaeltytrglpvakcvswd-eigdvtavagfe
vcdhsgaki---kgddaerlclkvgafr--s--ynqfcsergcmdckmvv
daeyrfetvavaraakkigylqlregnfgrepgqgprenahaptisapsp
lvgsdeevsmalgkvll-----gqvgpmmdvspkagrysgsgk-sveiyk
hhgtpskdilraas
>ENV_SIVG1/22-522
rdestlsskygdqawkcngttckvpkfifi--kdgwidlntgygyflpav
csemf--------dwkehcqathcrlglsqifgsttl-gatsgtll---p
tsl--afaffplgkadr-ymq-----cdsaphiidd------agekleat
ggargetydkwtlfekshinqnmighs------san--ageqtvklg-cg
asfskfkkdwslnvndsasasvkp---vl-sfflpqamnnrqvagqseat
t---ieqgillyvsgtgclkgyfscgnnarlsvpkfgfecqpkaksaatn
aglcfsgcpndghvrpggkptlrprahpp--vlkgcpadklygri--lpe
tghyhgetacgnpfankgeaeltytrnipddkcvswgrevadvtavavfe
vcdqsgsri---kgddveplclkagafr--pydytqfcsdrgcldckmtp
-----fatvsvaraakrigylqlweshfgrepgqaprhsghaptisapsp
lvgkdenvimaagkvll-----gevgqmmevspkagrlsgtgk-svevyk
hhgtpnkeilrdgs
>ENV_HV2BE/24-510
rvdsalssaygdqtwkcsgvtckvpksvfiidkdgwielntgysyflpaf
caemf--------dwkehcqathcklglsqlfgcteiasatnntll---p
tslirvfafvplgkadr-fmav----cacapqllvd------ageklqat
agarsqtydkrglfgkshinqvmighsks----tesindgeqtvklg-cp
gsfsnfkkkwslnvshsasatvkr---vlnk------mnnkqalggseet
a---veegimlyvsgtgcadgfftcgnniklnvpkfgfeckpkatsa---
-glcfagcaddgtvrsggkptlrprahpp--vlkgcesqkhngrilelpe
tg---setactvpfisrgeaeltytrglgvakcvrwd-evgdvtavagfe
vcdhsgaki---kgddadplcldvsafr--s--ynqfcsergcmdckmvv
daeyrfetvavaraakkigylqlrggnfgrepgqsprenahaptisapsp
lvgsdenvsmpmgkvll-----gqvgqmmevspkagrysgsgk-sveiyk
hhgtpskdvlraas
>node17
rvdsalssaygdqtwkcsgvtckvpksifiidkdgwielntgysyflpaf
caemf--------dwkehcqathcklglsqlfgctklagatnntll---p
tslirafafvplgkadr-fmav----casapqilvd------agekllat
agarsqtydkrglfakshinqsmighsks----sesindgeqtvklggcp
asfsnfkkkwslnvshsasatvkr---vlnk------mnnkqalggseat
a---veegillyvsgtgcvdgfftcgnnvklnvpmfgfeckpkaksa---
-glcfagcaedgtvrsggkptlrprahppgyvlkgceaqklngri--lpe
tg---setactapfvsrgeaeltytrglpvakcvswd-eigdvtavagfe
vcdhsgaki---kgddaeplcldagafr--s--ynqfcsergcmdckmvv
daeyrfetvavaraakkigylqlregnfgrepgqsprenahaptisapsp
lvgsdenvsmalgkill-----gqvgqmmevspkagrysgsgk-sveiyk
hhgtpskdilraas
>ENV_HV2CA/25-512
rvdsalssaytdqtwkcsgvtckvpnsifiidkdgwielntgysyflpaf
caeif--------dwkehcqathcklglsqlfgctklagatnstll---p
vslirafafvplgkadr-fmsv----casapqilvd------agekllat
agarsqaydkrglfakshikqsmighsks----seslndgeqtvklggcp
asf----kkwslnvshsaratvkkiffvlnk------mnnkqalggsdap
a---veegillylsgtgcvdgfftcgnnvklnvpmfgfecqpkaksa---
-glcfagcaedgtvraggsptlrprshppgyvlkgceaqklagnn--lpe
tg---sqtactapfvsrgeaeltytrglpvakcvswd-eigdvtavagfe
vcdhsgaki---kgddaeplcldagafr--s--ynqfcsergcmdckmvv
daeyrfetvavaraakkigylqlregnfgrepgqsprenahaptisapsp
lvgsddnvsmalgkill-----gqvgqmlevslkagrysgsgk-saeiyk
hhgtpskdilraas
>node14
rvdsalssaygdqtwkcsgvtckvpksifiidkdgwielntgysyflpaf
caemf--------dwkehcqathcklglsqlfgctklagatnntll---p
tslirvfafvplgkadr-fmav----casapqilvd------agekllat
agarsqtydkrglfgkshinqsmighsks----sesindgeqtvklg-cp
asfsnfkkkwslnvshsasatvkr---vlnk------mnnkqalggseet
a---veegillyvsgtgcadgfftcgnnvklnvpkfgfeckpkaksa---
-glcfagcaddgtvrsggkptlrprahpp--vlkgceaqklngrilelpe
tg---setacsapfvsrgeaeltytrglpvakcvswd-eigdvtavagfe
vcdhsgaki---kgddaeplcldagafr--s--ynqfcsergcmdckmvv
daeyrfetvavaraakkigylqlrggnfgrepgqsprenahaptisapsp
lvgsdenvsmplgkvll-----gqvgqmmevspkagrysgsgk-sveiyk
hhgtpskdilraas
>ENV_HV2D1/24-501
rvdsalsspygdqtwkcsgvtckvpksifiidkdgwielntgysyylpaf
caemf--------dwkehcqathcklglsqlfgctklagatnntll---p
ttlirvfafvplgkadr-fmav----casapqilvd------agekllat
agarsqaydkrglfgkshinqsmighsks----sesikdgeqtvklg-cp
asfsnfkkkwslnvchspsatvkr---vlnk------mnnkqalggsees
a---vekgillyvsgtgcadgfftcgnnvklnvpkfgfeckpkaksa---
-glcfagcaddgtvrsggkptlrprahpp--vlkgceaqklngrilelpe
tg---setacsapfvsraeaqltytrglpvakcvtwd-qigdvaavagfe
vcdhsgaki---kgdepeplcldagafr--s--ynqfcsergcmdckmav
daeyrfetvavaraakkigylrlrggnfgrepgqsprenahaptisapsp
lvgsdqnvsmplgkall-----gqvgqmmevspkagrysgsgk-sveiyk
hhgtpskdilraas
>ENV_SIVGB/47-569
rdeskmsskygdqnwkcnltsckvpklliv--kkgwiklnsaygiflhef
cself--------dwrehcqasvcelglrqifgqdsm-gavkstmlghfp
ssl--gfefiplgkaar-aml-----casapqilqdvflktwpgkklvqi
vgapaaaydkwtlltknhlnqkstghv--aqpfsqq--ngeqtv------
----kfhkkwslnidhsassnvss---vlnsfnlpqamnnkqaaggtaes
sattieqgillyicgagcvngyfscgntaklnipifgfecrphgkspatk
agqcfsdcpndglvrpvgqpglrqr-hpp--vlegcpadkldhrv--lpa
sgghtsenacggpfvskgdaeltynrhvpaekctmwgaevddvtavdvfe
tcdqkgfgrggfkgddvehlclkigafa--p--yteycsdhgclgckmi-
-lgymfgtisvacpakqkrylqlwdghfnvepgqlp--sghfptinappp
mvgkdsnekmalgkvll-----gegikmlevssragrysstgknsvilyk
hhsqpsk-ilrggs
>node18
rvdsalssaygdqtwkcsgvtckvpksifiidkdgwielntgysyflpaf
caemf--------dwkehcqathcklglsqlfgctklagatnntll---p
tslirafafvplgkadr-fmav----casapqilvd------agekllat
agarsqtydkrglfakshinqsmighsks----sesindgeqtvklg-cp
asfsnfkkkwslnvshsasatvkr---vlnk------mnnkqalggseet
a---veegillyvsgtgcvdgfftcgnnvklnvpkfgfeckpkaksa---
-glcfagcaddgtvrsggkptlrprahpp--vlkgceaqklngri--lpe
tg---setacsapfvsrgeaeltytrglpvakcvswd-eigdvtavagfe
vcdhsgaki---kgddaeplcldagafr--s--ynqfcsergcmdckmvv
daeyrfetvavaraakkigylqlregnfgrepgqsprenahaptisapsp
lvgsdenvsmalgkvll-----gqvgqmmevspkagrysgsgk-sveiyk
hhgtpskdilraas
>ENV_HV2NZ/24-502
rvdsalssaegdhtwkcsgvtckvpksifaidkddwielntgysyflpaf
cavmf--------dwkehcqathcklglsqlfgctklagatnntll---p
tslirgfafvplgkadr-fmav----casapqivvd------agekllat
dgarsqtydkrglfakshinqtmighsks----sksindgaqtvklggcp
asfsnfkkkwslnhshaasatvkr---vlnk------mnnkqalggseat
a---veegillyvsgtgcvdgfftcgnnvkltvpmfgfeckpkpksa---
-glcfagcaedgtvrsggkptlrprahppgyvlkgtedqkldgri--lpe
tg---setactapfvsrgeaeltytrglpvakctswd-evgdvtavagfe
vcdhsgaki---kgddadplcldpgafr--s--ynefcnergcmdckmvv
daeyrfeavavaraakkigylqlregnfgrepgqsprenahaptiaapsp
lvgsdenvsmalgkillgnwvdgqvgqmmevsvkagrysgeci-sveiyk
hhgtpskdilrags
>node8
rdesalsskygdqtwkcngttckvpkfifi--kdgwidlntgygyflpaf
csemf--------dwkehcqathcklglsqifgsttl-gatsstll---p
tsl--afaffplgkadr-yml-----cdsapqiled------agekleat
ggarsetydkwtlftkshinqnmighs------sqn--ngeqtvklg-cs
asfskfkkkwslnvnhsasasvkp---vlntfflpqamnnkqaaggseet
t---ieqgillyvsgtgcvdgyfscgnnarlnvpkfgfecqpkaksaatd
aglcfagcpndghvrpggkptlrprahpp--vlkgcpadklngri--lpe
tgnytgetacgspfvskgeaeltytrnipdakcvswgrevadvtavavfe
vcdhsgari---kgddveplclkagafr--p--ytqfcsdrgcldckmtp
dvpymfatvsvaraakrigylqlweghfgrepgqapresghaptisapsp
lvgkdenvkmalgkvll-----gevgqmmevspkagrysgtgk-svevyk
hhgtpskdilrdgs
>node11
rvdsalssaygdqtwkctgvtckvpksifiidkdgwielntgysyflpaf
caemf--------dwkehcqathcklglsqlfgctklagatnntll---p
tslirafafvplgkadr-fmav----casapqilvd------agekleat
agarsqtydkrglfakshinqsmighsks----sestndgeqtvklg-cp
asfsnfkkkwslnvshsasasvkr---vlnk------mnnkqalggseet
a---veegillyvsgtgcvdgfftcgnnvklnvpkfgfeckpkaksa---
-glcfagcaddgtvrsggkptlrprahpp--vlkgceaqklngri--lpe
tg---setacsapfvsrgeaeltytrglpvakcvswd-eigdvtavagfe
vcdhsgaki---kgddaeplclkagafr--s--ynqfcsergcmdckmvv
daeyrfetvavaraakkigylqlregnfgrepgqsprenahaptisapsp
lvgsdenvsmalgkvll-----gqvgqmmevspkagrysgsgk-sveiyk
hhgtpskdilraas
>node19
rvdsalssaygdqtwkcsgvtckvpksifiidkdgwielntgysyflpaf
caemf--------dwkehcqathcklglsqlfgctklagatnntll---p
tslirafafvplgkadr-fmav----casapqilvd------agekllat
agarsqtydkrglfakshinqsmighsks----sestndgeqtvklg-cp
asfsnfkkkwslnvshsasasvkr---vlnk------mnnkqalggseet
a---veegillyvsgtgcvdgfftcgnnvklnvpkfgfeckpkaksa---
-glcfagcaddgtvrsggkptlrprahpp--vlkgceaqklngri--lpe
tg---setacsapfvsrgeaeltytrglpvakcvswd-eigdvtavagfe
vcdhsgaki---kgddaeplcldagafr--s--ynqfcsergcmdckmvv
daeyrfetvavaraakkigylqlregnfgrepgqsprenahaptisapsp
lvgsdenvsmalgkvll-----gqvgqmmevspkagrysgsgk-sveiyk
hhgtpskdilraas
>node9
rvesalssaygdqtwkcngvtckvpksifiidkdgwielntgynyflpaf
cgemf--------dwkehcqathcklglsqlfgctkl-gatnstll---p
tslirafafvplgkadr-ymav----casapqiled------agekleat
agarsqtydkwglftkshinqsmighsks----sestnngeqtvklg-cp
asfsnfkkkwslnvnhsasasvkr---vlnk------mnnkqalggseet
a---veqgillyvsgtgcvdgfftcgnnaklnvpkfgfeckpkaksa---
-glcfagcaddgtvrsggkptlrprahpp--vlkgceaqklngri--lpe
tg---setacsspfvsrgeaeltytrglpvakcvswg-eigdvtavavfe
vcdhsgani---kgddaeplclkagafr--s--ynqfcsergcmdckmvv
daeyrfetvavaraakkigylqlregnfgrepgqspresahaptisapsp
lvgsdenvsmalgkvll-----gqvgqmmevspkagrysgsgk-sveiyk
hhgtpskdilrags
>node10
rvdsalssaygdqtwkcngvtckvpksifiidkdgwielntgysyflpaf
caemf--------dwkehcqathcklglsqlfgctklagatnstll---p
tslirafafvplgkadr-fmav----casapqiled------agekleat
agarsqtydkwglfakshinqsmighsks----sestndgeqtvklg-cp
asfsnfkkkwslnvnhsasasvkr---vlnk------mnnkqalggseet
a---veegillyvsgtgcvdgfftcgnnvklnvpkfgfeckpkaksa---
-glcfagcaddgtvrsggkptlrprahpp--vlkgceaqklngri--lpe
tg---setacsspfvsrgeaeltytrglpvakcvsws-eigdvtavagfe
vcdhsgani---kgddaeplclkagafr--s--ynqfcsergcmdckmvv
daeyrfetvavaraakkigylqlregnfgrepgqsprenahaptisapsp
lvgsdenvsmalgkvll-----gqvgqmmevspkagrysgsgk-sveiyk
hhgtpskdilrats
>ENV_SIVM1/24-528
rvesalssaygdqtwkcngvvckcpksifiihkdgwielntgynyflpaf
cgemf--------dwkehcqathcklglsqlfgctkl-gatnstll---p
tslirafafvplgkadr-ymav----casapqiled------agekleat
agaqsetfdkwglftkshtnqsmighsks----sestnngeqtvklg-cp
asfsnfkkkwslnvnhsasasvkr---plnk------mnnkqalggseet
a---veqgillyvsgtgcvdgfftcgnnaklnvpkfg-eckpkaksa---
-glcfagcaddgtvrsggk-tlrprahpp--vlkgceaqklngrr--lpe
tg---setacsspfvsrgeaeltytrglpvmkcvswg-eigdvtavavfe
vcdhsgasi---kgddaeplclkagafr--s--ynqfssergcmdckmvv
daeyrfetvavaraakkigylqlregnfgrepgqspresahaptisaptp
lvgsdenvsmalgkvll-----gqvgqmlevspkagrysgsgk-sveiyk
hhggpskdilrags
>ENV_HV2D2/24-513
rvdsalsaaygdqtwkcngvtckvpksifiidkdgwtelntgysyf----
-------------dwkehcqmthcklglsqlfgctklagannstll---p
tslirafafvplgkadr-fmav----casapqiled------agekleat
agtksqtydkwglfskshihqsmighsks----sestndgeqtvkpg-cp
asfsnfkkkwslnvnhsssasvkr---vlnk------mnnkpalgvsaet
a---veegillyvsgtgcvngfftcgnnvklnvpkfgfeckskakpa---
-glcfagcandgttrsggkatlrprahpp--vlkgceaqklngri--lpe
tg---sedacsspfvsrgeaeitytrglpvakcvswa-eigdvtavagfe
vcdhsgadt---kgddaeplclkagafr--s--ynqfcsergcmeckmlv
iaeyrfetvkvaraaknigy---regkfarepgqsprenahaptitapsp
lvgpddnvsmalgkvll-----gqvgqtlevspkagrfsgsgk-sveiyk
hhgtpskdilrats
>ENV_SIVV1/24-538
rdestfsskygdqtwkcngttckvpkflfi--kdgwidlhtgygyflpav
csemfttdphnhtdwtehcqgthcrlglsqifgsttl-gattgtll---p
tsl--afaffplgkadr-yml-----cdsapqiied------agekleat
ggargetydkwtaftkahinqnmighs------sat--ngeqtvklg-cg
aafskfkkkwslnvndsasasikp---vl-tfftaqamnnrqaagqseet
t---ieqgillyisgtgclkgyfncgnnarlsvpkfgfgcqpkgksaatn
aglcfagcandghvrpggkptlrprahpp--vlkgcpadklygri--lpe
tgnytaetacsnpfankneaeltytrnipdakcvswgrevadvtavavfe
vcdesgari---kgddveplclkagslrvip--etqfcsdrgcldckrtp
dvpylfatvsvaraakrigylqlwegefgrepgqaprds--avtisapsp
lvgkdenakmalgkvll-----ggvgqmmgvsphagrysgtgk-svevyk
hrgtpskeilrdge
>node7
rdestlsskygdqtwkcngttckvpkfifi--kdgwidlntgygyflpav
csemf--------dwkehcqathcrlglsqifgsttl-gatsgtll---p
tsl--afaffplgkadr-yml-----cdsapqiied------agekleat
ggargetydkwtlftkshinqnmighs------san--ngeqtvklg-cg
asfskfkkkwslnvndsasasvkp---vl-tfflpqamnnrqaagqseet
t---ieqgillyvsgtgclkgyfscgnnarlsvpkfgfecqpkaksaatn
aglcfagcpndghvrpggkptlrprahpp--vlkgcpadklygri--lpe
tgnytgetacgnpfankgeaeltytrnipdakcvswgrevadvtavavfe
vcdqsgari---kgddveplclkagafr--p--ytqfcsdrgcldckmtp
dvpymfatvsvaraakrigylqlweghfgrepgqaprdsghaptisapsp
lvgkdenvkmalgkvll-----gevgqmmevspkagrysgtgk-svevyk
hhgtpskeilrdgs
