>ENV_SIVV1/24-538
g------dptrkr-rcathdsfkfitfgdenaataflvdytlslmeyvna
iadvkeaamkfakavpgnsrgevgn-fdylpnvagvfaqdsghgngnsas
lktapwcrgdssgyalcnvgltanyalsqtpliavpskgpkrnicvgtva
hi-sasgscyaakikatc-tlfr-aaekeslrhslrvgdndlhlfadygq
nlhsgelagak-mrdlse---yk-----artkalsieyggpksseaklry
sglvregtipadqapsef---------lnglciiviikds-rehiqekqv
tsfedlfakngl--t-----mktssgvhcamrtgkvhmptkkdpst--ag
-lvmyrqksqkais-vykcdgakglanlalentrrqagpstfdeelk-sp
siifpcppclekrsarehwnlrpvrpeatlissftsyskrlktlpgqcki
rskihqakgpfplnemgcstqeslnahlalfdvisqa-vra----tivcp
kkfaaegqdkierkarvkslgddstslekptpgrka-psnsymarghhvn
vfaygwg---s-fqitseakg
>node9
g------dptrkr-siaahdsfkfitfgnenaptaflvayklrlleyakg
fvdvregamkiakavpggsrgdqgn-ad-lpttggifpqdsgdgngants
lkiapwcrgdssgyglcnvalthnyal-etpliaipssgpsrkicvgtva
hicsasgpcyeakigaicgtlfr-aahkesfr--lqigdnnidlfgdfaq
dlqtgqllgak-mvdlsn---yr-----aqtkalaidyggpkstdaklqy
agkvregtipadqapsef---------lnslciiviikdsareyiedkqv
tsfqdlfakhgltet-----mktnsgihpaqrvgkahlpnkknpsn--sg
plvmfnnknqkvvsfvykpdgskslvnlamentrrq---------ln-ap
ceifpcppclekrsarehwylqpvrpgstkissfapyskrlkvlpgqcki
kakihqakgpfppna---akrevlskhhalldvis-a-vavsalatitcp
kkfdaegldkia--------asnstamkkplpgraa-psnsylrrglhvd
vfaygwgegvp-yqiesevkg
>ENV_SIVG1/22-522
g------dptrkr-rcaahdsfkfitfgdenaataflvaftlslmeyvna
fadvreaamkfakavpggsrgevgn-fdylppvagvfaqdsghgngnnas
lkkapwcagdssgyglcnvaltanyalcetpliaipskgpsrkicvgtva
hicsasgpcyaakikaicgtlfr-aaekesfrdglqvgdndvnlfadygq
nlhtgqlagak-mrdlse---yraasvpartkklsieyggrksseaklry
sgmvrngtipadrapgef---------lnglciiviikdssreyiedkqv
tsfedlfakhglket-----mktnsgihpamrtgkvhmptkkdpsn--ag
-lvmynqksqkvis-vykcdgakglaklalentrrqagpaafdeelk-ap
siifpcppclekrsarehwslrpvrpeatlissftsyskrlkvlpgqcki
rskihqakgpfppndlgcstqeslskhhalfdvisqa-vrv----tivcp
kkfaaegedkiarkarvkslgndstalskplpgrka-psncylarglhvn
vfaygwt---s-fqitseakg
>node18
g------dptrkr-siaahdsfkfitfgnenaptaflvayklrlleyakg
fvdvregamkiakavdggsrgdqgn-ad-lpttggvfpqdsgdgngahts
lkiapwcrgdssgeglcnvslthdcal-etpliaipssgpsrkicvgvva
hicsasgpcyeakigaicgtlfr-aahkesfr--lqigdndidlfgdfsq
dlqtgqllgak-mvdlsn---yr-----aqtkalgidyggpkstdaklqy
agkvregdipadqapsef---------lnslciiviikdsareyiedkqv
tafqdlfakhgl--t-----mktnsgihpaervgkahlpnkknpsp--sg
plvmfnnknqkvvsfvykpdgakslvnlaientrrq---------ln-ap
ceifpcppclekrsarehwylqpvrpgktkissfapyskr------qcki
kakihqakgpfppna---akrevlskhhalldvis-a-vavsalatitcp
kkfdaegldkia--------afnstamkkplpgraa-psnsylrrglhvd
vfaygwgegvp-yqiesevkg
>node7
g------dptrkr-rcaahdsfkfitfgdenaataflvaytlslmeyvna
fadvreaamkfakavpggsrgevgn-fdylppvagvfaqdsghgngnnas
lktapwcrgdssgyalcnvaltanyalcetpliaipskgpsrkicvgtva
hicsasgpcyaakikaicgtlfr-aaekesfrdglqvgdndvnlfadygq
nlqtgqlagak-mrdlse---yq-----artkalsieyggpksseaklry
sgmvregtipadqapsef---------lnglciiviikdssreyiedkqv
tsfedlfakhglket-----mktnsgihpamrtgkvhmptkkdpsn--ag
-lvmynqksqkvis-vykcdgakglanlalentrrqagpatfdeelk-ap
siifpcppclekrsarehwnlrpvrpeatlissftsyskrlkvlpgqcki
rskihqakgpfppndmgcstqeslskhhalfdvisqa-vrv----tivcp
kkfaaegqdkiarkarvkslgndstalskplpgrka-psnsylarglhvn
vfaygwg---s-fqitseakg
>node17
g------dptrkr-siathesfkfitfgnenaptaflvayklrlleyakg
fvdvregamkiakavdggsrgdqgn-ad-lpttggvfpqdsgdgngahts
lkiapwcrgdssgeglcnvslthdcal-etpliaipssgpsrkicvgvva
hicsasgpcyeakigaicgtlfr-aahkesfr--lqigdndidlfgdfsq
dlqtgqllgak-mvdlsn---yr-----aqtkalgidyggpkstdaklqy
agkvkegdipadqapsef---------lnslciiviikdsareyiedkqv
tafqdlfakhgl--t-----mktesgihpaervgkahlpnkknpsp--sg
plvmfnnknqkvvsfvykpdgakslvnlaientrrq---------ln-ap
ceifpcppclekrsarehwylqpvrpgktkissfapyskr------qcki
kakihqakgpfppna---akrevlskhhalldvis-a-vavsalatitcp
kkfdaegldkva--------afnstamkkplpgraa-psnsylrrglhvd
vfaygwgegvp-yqiesevkg
>node10
g------dptrkr-siaahdsfkfitfgnenaptaflvayklrlleyakg
fvdvregamkiakavpggsrgdqgn-ad-lpttggvfpqdsgdgngants
lkiapwcrgdssgeglcnvslthdcal-etpliaipssgpsrkicvgtva
hicsasgpcyeakigaicgtlfr-aahkesfr--lqigdndidlfgdfsq
dlqtgqllgak-mvdlsn---yr-----aqtkalaidyggpkstdaklqy
agkvregtipadqapsef---------lnslciiviikdsareyiedkqv
tafqdlfakhgl--t-----mktdsgihpaqrvgkahlpnkknpsn--sg
plvmfnnknqkvvsfvykpdgakslvnlamentrrq---------ln-ap
ceifpcppclekrsarehwylqpvrpgktkissfapyskr------qcki
kakihqakgpfppna---akrevlskhhalldvis-a-vavsalatitcp
kkfdaegldkia--------asnstamkkplpgraa-psnsylrrglhvd
vfaygwgegvp-yqiesevkg
>ENV_HV2BE/24-510
g------dptrkr-siaahesfkfitygnenaptvflvayklrlleyakg
fvdvregamkiakavdggsrgdqgn-ad-lpttggvfpqdsgdgngahds
lkiapwcrgdssgqglcnvslthdcal-evpliavpssgpsrkicvgvva
hicpasgpcyeakkgalcgtlfr-aahkesfr--lqigdndidlfgdfsq
dlqtgqllaak-mvdlsn---yr-----aqkkslgidygnpkstnaklqy
agkvregdipadqapsef---------lntlciiviikdsareyiedkqv
tafqdlfakhgl--t-----mktnsgihpaervgkahlpdkknpsp--sg
plvmfnngnqkvvsfcykpdgakslvnlaientrrq---------ln-ap
ceifpcpsclekrsarehwylqpvrpgktkissfapyskr------qcki
kakihqakgpfppna---akrellsshhalldvis-a-vavselatitcp
kkfdaegldkia--------afnstamkkplpgraa-qsnsylrrglhvd
vfaygwgegvp-yqiesevkg
>node11
g------dptrkr-siaahdsfkfitfgnenaptaflvayklrlleyakg
fvdvregamkiakavpggsrgdqgn-ad-lpttggvfpqdsgdgngahts
lkiapwcrgdssgeglcnvslthdcal-etpliaipssgpsrkicvgvva
hicsasgpcyeakigaicgtlfr-aahkesfr--lqigdndidlfgdfsq
dlqtgqllgak-mvdlsn---yr-----aqtkalaidyggpkstdaklqy
agkvregtipadqapsef---------lnslciiviikdsareyiedkqv
tafqdlfakhgl--t-----mktnsgihpaervgkahlpnkknpsn--sg
plvmfnnknqkvvsfvykpdgakslvnlamentrrq---------ln-ap
ceifpcppclekrsarehwylqpvrpgktkissfapyskr------qcki
kakihqakgpfppna---akrevlskhhalldvis-a-vavsalatitcp
kkfdaegldkia--------afnstamkkplpgraa-psnsylrrglhvd
vfaygwgegvp-yqiesevkg
>ENV_HV2CA/25-512
g------dptrkr-siathksfkfitygnenaptaflvayklrllkygkg
fvdlragamkiprtvdggsrgdqgn-ad-lpttggvfpqdsgdgngants
lkiapwcrgdssgeglcnvslthncal-etpliavpssgpsrkicvgvva
ricsasgpcyeakvgaicgtlfr-aahkesfr--lqigdndidlfgdfsg
dlqtgqilgak-mvdlsn---yr-----aqtkalgidyggpkstdsklqy
agkikegdipadqapsef---------lnslciiviikdsareyiedkqv
tafqdlfekhgl--t-----kktesgihpaervgkahlpnkknpsp--sg
plvmfnnknqkvvsfvykpdgakslvnlaientrrq---------ln-ap
ceifpcppclekrsarehwylqpvrpgktkissflpyskr------qcki
kakihqakgpfppta---akrevlskhhalldvis-a-vtvsalatitcp
kkfdaegldkia--------afnstamkkplpgraa-psnsylrrglhvd
vfaygwgegvp-yqiesevkg
>node14
g------dptrkr-siaahdsfkfitfgnenaptaflvayklrlleyakg
fvdvregamkiakavdggsrgdqgn-ad-lpttggvfpqdsgdgngahts
lkiapwcrgdssgqglcnvslthdcal-etpliaipssgpsrkicvgvva
hicsasgpcyeakigaicgtlfr-aahkesfr--lqigdndidlfgdfsq
dlqtgqllgak-mvdlsn---yr-----aqkkslgidyggpkstnaklqy
agkvregdipadqapsef---------lnslciiviikdsareyiedkqv
tafqdlfakhgl--t-----mktnsgihpaervgkahlpnkknpsp--sg
plvmfnnknqkvvsfvykpdgakslvnlaientrrq---------ln-ap
ceifpcpsclekrsarehwylqpvrpgktkissfapyskr------qcki
kakihqakgpfppna---akrevlskhhalldvis-a-vavsalatitcp
kkfdaegldkia--------afnstamkkplpgraa-psnsylrrglhvd
vfaygwgegvp-yqiesevkg
>ENV_HV2G1/23-502
g------dptrkrasiaahdsfkfitfgnenvptaflvayklklleyakg
fvdvregamkvvkavpggsrgdqgn-ad-lpttggvfpqdsgdgngahts
lkiapwcrgdssgeglcrvslthdcal-etpliaipssgpsrkicvgvva
hicsasgpcyeskigaicgtlfr-athkesfr--lqigdddidlfgdfsq
dlqtdqllgak-mvdlsn---yr-----aqtkalaidyggpkstdaklqy
agnvregtipadqapsef---------lnslciiviikdsareyiedkqv
tafqdkfakhgl--tknlysmktnsgihpaervgkghlpnkknpsn--sg
plvmfnnknqkvtsfvykpdgakslvnlamentrrq---------ln-ap
ceifpcppclekrsarehwylqphrpgktkissfapyskr------qcki
kakihqakgpfppna---akrevlskhhalldvis-a-vavsalatitcp
kkfdaegldkia--------afnstamkkplpgraa-psnsylrrglhvd
vfaygwgegvp-yqiesevkg
>ENV_HV2NZ/24-502
gffnqpgdptrkr-siathesfkfitfgnenaptaflvayklqlleyakg
fvevrk--mkiakavdggsrgdqgn-ad-lpttggvfpqdsgdgngahts
lkiapwcrgqssgdglcnvslthdcal-etpliaipssgpsrkicvgvva
hicsasgpcyeakigascgtlfh-yahkdsfk--lqigdndidlfgdfsq
dlqtgqllgak-mvdlsn---yr-----aqtkalgidyggpkstdaklqy
agkvkegdipadqapsef---------lnalciiviirdaarnyiedkqv
tafqdlfakhgl--t-----mktesgihpaervgkahlpnkknptp--sg
plvmfnsknqkvvsfvykpdgakslvnlaiestrrq---------ln-ap
ceifpcppclekrsarehwylqpvrpgktkissfapyskr------qcki
ktkihrakgpfppna---skrevlskhhalldvis-a-vkvsalatitcp
kkfdaegldkva--------afnstamkkplpgraa-psnsylrrglhvd
vfaygwgegvp-yqiesevkg
>ENV_SIVM1/24-528
p------dptrkr-siaahesfkfitfgndnaptgflvayklrlleyakg
fvdvrdgamkiakavpggsrgdqgn-ae-lpttggifpqdsgdgngants
lkiaswcrgdssgyglcnvalthnyal-etpliaipssgpsrkicvgtvl
hicsasgpcyeakigaacgtlfr-aahkesfr--lqigdnnidlfgdfaq
dlqtgqllgak-mvdlsd---yr-----aqtkalaidyggpkstdaklqy
agrvregtipadqapsef---------lnslciiiiikdsareyvedkqv
tsfqdlfakhgltet-----mktnsgihpaqrvgkahlpnkkdpsn--sg
pvvmyngknqkvvsfvyrpdgsrslvnlamentrrq---------ln-ap
ceifpcppclekraarehwylqpvrpgsvkispfapyskrlkvlpgqcki
kakihqakgpfppna---akrevlskhhalldvis-a-vavsalatitcp
kkfdaegldkia--------asnstamkkplpgrag-psnsylrrglhvd
vfaygwgegvp-yqiesqvkg
>ENV_HV2D1/24-501
g------dptrkr-siaahdsfkfitfgnenaptaflvayklrlleypkg
ftdvregamkiakavdggsrgdqgn-ad-lpttggvfpqdsgdgngahts
lkiapwcrgdssgqglcnvslt-dcaw-etpliaipssghsrkicvgvva
hicsasgpcyeakigaicgtlfr-aahkesfr--lqigdndidlfgdfsq
dlqtgqllgak-mvdlsn---yi-----aqkkslgidyggpkstnaklqy
agkvregdipadqapsef---------mnslciiviikdsareyiedkqv
tafqdlfakhgl--t-----mmtnsgihpaervgkahlpnkknpap--sg
plvmfnnknqkvvsfvykpdgakslvnlaaentrrq---------ld-ap
ceifpcppclekrsarehwylapvrpgktkissfapyskr------qcki
kakihqpkgpfppne---akrevlakhhalldvis-a-vavcalatitcp
kkfeaecldkia--------afnstamkkplpgraacpsntylrrglhvd
vfaygwgegvp-yqiesevkg
>ENV_SIVGB/47-569
g------dptkkr-ntaahasfnfltfgdanaavaflapytlalieyttg
fadv--aalkfttavgagnrgeggapad-ipciigvfaqdsghgnpnnas
lktlpwcsgqsagygl-qvlltndtal-espliavpas-------vgdva
picsasgpcyiakisakcgtlfrttankesfvdeihvgnndvillvqyak
nvrvgal---kvmralsnknayq-----grakslcieygvpkasdaklry
agmvkeltipaeespsefapekythvvlsalpsvviiqessrefiedkqv
tcfetlfarh---et-----vqtnpgchpamrsgkvhmptkknpsnkese
-lvmfnqknqkvik-vystdgs-glialaldhsrrqagpaefdedlkeap
eeifavpnclelsrarewfylrpvrptatlvsafspyskrlnvlpgrcgi
lagihqakgplppndkgcatqetlfkhhylfghvsqayvkv----aivcp
kqfdpedqdkvilktlvkslgsqstsltkplqgnaa-psnkylrrtlhlg
vfaygwf---syfeiaadvkn
>node19
g------dptrkr-siaahdsfkfitfgnenaptaflvayklrlleyakg
fvdvregamkiakavdggsrgdqgn-ad-lpttggvfpqdsgdgngahts
lkiapwcrgdssgeglcnvslthdcal-etpliaipssgpsrkicvgvva
hicsasgpcyeakigaicgtlfr-aahkesfr--lqigdndidlfgdfsq
dlqtgqllgak-mvdlsn---yr-----aqtkalaidyggpkstdaklqy
agkvregtipadqapsef---------lnslciiviikdsareyiedkqv
tafqdlfakhgl--t-----mktnsgihpaervgkahlpnkknpsp--sg
plvmfnnknqkvvsfvykpdgakslvnlamentrrq---------ln-ap
ceifpcppclekrsarehwylqpvrpgktkissfapyskr------qcki
kakihqakgpfppna---akrevlskhhalldvis-a-vavsalatitcp
kkfdaegldkia--------afnstamkkplpgraa-psnsylrrglhvd
vfaygwgegvp-yqiesevkg
>ENV_HV2D2/24-513
g------dptrkr-siaahdsfkfitfgnenaptaflvayklrlleyakg
fvdvregamkiakavpggsrgdhgn-ad-lpttggvfpqdsgdgngantn
lkiapwcrgdssaeglcnvslthdcal-etplisipssgpyrkvcvgtva
hicsasgpcyeakigaicgtlfr-aahkesfr--lavadndidlfgdfsm
dlqtgqwlgak-mvnlsn---yr-----aqtkdlaidyggpkstdakley
agkvregtipadqvpsef---------lnslciivvikdgereyiedkqv
aafqdlfvkhgl--t-----mktdsgihpaqrvgkahlpnkka-sn--sg
plvmfnnknqkvvsfmykadgakslvnlamenarrq---------ln--p
ceffpcppclekrsarehwylqpvrpgktkissfapyskr------qcki
kgkihqakgpfspna---akrevkskhqalldvis-a-vavsslatitcp
kkfdkegldkia--------asnstamkkplpgraa-prdsylkrglhvd
vfafgwgegvp-yqieseikg
>node8
g------dptrkr-riaahdsfkfitfgdenaataflvaytlslleyvng
fadvreaamkfakavpggsrgevgn-ad-lptvagvfaqdsghgngsnas
lktapwcrgdssgyglcnvaltnnyal-etpliaipssgpsrkicvgtva
hicsasgpcyaakikaicgtlfr-aaekesfrdglqvgdndvdlfadyaq
nlqtgqlagak-mrdlsn---yq-----artkalsidyggpkssdaklry
agmvregtipadqapsef---------lnslciiviikdssreyiddkqv
tsfedlfakhglket-----mktnsgihpamrsgkahmptkkdpsn--ag
-lvmfnqknqkvis-vyksdgakglvnlalentrrqagpstfdeelk-ap
seifpcppclekrsarehwylrpvrpeatlissftpyskrlkvlpgqcki
rakihqakgpfppndmgcatqeslskhhalfdvisqa-vrv----tivcp
kkfdaegqdkiarkarvkslgndstalskplpgraa-psnsylqrglhvn
vfaygwg---s-fqitsevkg
