>node14
qtthghev--qacssvpn-lvqft--drgrgskesangasnapwctnvcq
mvfagspsglat-gndhtetgrccptyciecaghgiscalldtkgca---
-knesnlncdqkidasggigefadqstqlsdskglhllfakkmaa-ekva
igcgagyh-a--tfkksspcaqhmllqvirhpypglktgglrsyghkasi
sgnvviakhgklqscvwviicgpce-yhfpnefkaitmgdsdfgfnkklk
llsapakfggpthgsrsklpcpdvhsvneslsflylfahvhnpakilikv
srfqf--had-----qsdvqssrhevk--q----ntrdpddgghdsl--l
vfdphvalsmkltdgrladratngahyalresnlmcfkvktyldlggapa
ghnl-------illsdpvdlriatvl---vklkpsnvsl-lgkplitqph
cdraesdftealsftakcelpfvsdkgfgyrptvwglcipa-----iekv
apl-----ptfmvaklgksctdgtnfiwrqchtvdmgplvgm-lakswsa
vc
>ENV_HV2NZ/24-502
qtthghev--evcssvpn-lvqft--drgrgskesangasnapwctnvcq
lvfagypsglat-gndhtetgrccptyciecaghgiscalldtkgca---
-knesnvncdekidanggvgefadqntqlsdskglhllfakkmaa-dkvn
igcgagyhhg--tfkksspc-khmllqvirhpypglktgglrsyghkati
psnvviasdgklqacawviicgpce-yhfpeefkaitmgdqdfgfnkqlk
llsapakfggpthgsrsklpcpdvrsvneslsflylfahvhnpakilikv
srfqf--had-----qsdvqssrhevk--q----ntrdpddgghdslqpl
vfdphvalsmkltdgrladratngfhyalresnlmcfkvktyldlggmpa
ghnl-------ilvsdpvdlriatvl---vklkpsnvsl-lgkplitqph
cdradsdftealnftakcelpfvsdkgfgyrptvwglcipa-----iekv
apl-----ptfmvaklgksctdgtnfiwrqcqtvdmgplvgm-faknwsa
vc
>ENV_HV2BE/24-510
qtthghev--qdsssvpn-lvqfi--qrgrgskesangasnapwctnvcq
mvfagspsglat-gndhtetgrccptyciecaghgiscalldtkgcaknp
gknesdlncdqkidasggagefadkstqlsdskglhllfakkmaa-dkta
igcgagyh-a--tfkraspcaqhmllqvirhpypglkteglrsyghkani
sgnvviakhgklqscvwviicgtce-yhfpnefkaitmgdsdfgfhkklr
llsapakfggpthgsrsklpcpevhsvndslsflylfahvhnpakimikv
srfql--had-----qsdvqsgrhetk--q----ntrdpdegghdtl--l
vfdphvalsmkltdgrladratngahyalresnlmcfkvktyldlggapa
gqnl-------illsdpvdlrnatvl---vklnpsnpsn-lgkplitqph
cdraesdfsealsftakcelpfvsdkgfgyrpsvwgicipa-----iekv
apl-----ptfmvaklgksctdgtnliwrqchtvdtgplvgm-lakswsa
vc
>ENV_HV2D1/24-501
qtthghev--qacsavpn-lvqft--drgrdskesangasnapwctnvcq
mvfagspsglat-gndhtetgrccptyciecaghgiscalldtkgca---
-knesnlncaqkidatggvgefadqst-lsdskglhllfekkmaa-ekva
igcgaeyh-a--tfkksspcaqhmllqvikhpypglktgglrsyghkasi
sgnvvidkhgklqsvvwviicgpce-yhfpnefkaitmgdsdfgfnkklk
llsapaklggpthgsrsklpcadvhsvneslsflylfahvhnpakilikv
srfqf--hid-----qsdvqssrhevk--q----ntrdpddgghdsl--l
vfdphvalsmkitdgrladratngahyalresnlmcfkvktyldlggspa
ghnl-------illsdpvdlriatvl---vklkpsnvsl-lgkpliaqph
cdraesdftealsftakcelpfvsdkkfgyrptvwglcipa-----iekv
apl-----ptfmvaklgksctdgtnfvwrqchtvdmgplvgg-lakswsa
vc
>ENV_HV2D2/24-513
qtthghev--ha-ssvpn-lveft--nrgrgskesanaasnapwctnvcq
mvfaaspsglat-gnkhtevgrccptyciecaghgiscalleskgca---
-kneanlncdekidasggvgefadqstqlsdskglhllfakkmea-geva
igcgagyh-a--tfkrsspcaqhmllqvirhpypglktgglrsyghklti
sgnvviakhgklqscvwvircgpce-yhfpnefkaitmgdnefafnkkvk
llsapakfggpthgsrsklpcpdahsvneslsflylfahvhdpakiliki
srfqf--hgd-----qsdvqssrhevk--q----ntrdpddskhdsa--l
vfdphvalsmkltdgrladratngahfalresnlmcfklktyldlggmpa
ghnl-------illsepvdlriatvl---vklkpsnvsl-lgrplikqph
cqraesdftdglsftakcelpfvtdkgfgyrptvwglcipa-----iekv
apl-----pslmvakfgkscadgsnfiyrqchtcdmgplvgm-lakswsa
vc
>node8
estqghev--qgcssvpn-lvqft--qrgrgskesanaasnanwctnvcq
mvfagsgsalet-ggehheggkcvsdyciecaentiscaqldlkgca---
-kneanencnakidasggvgefadhstqlshgkglrllfakkm---gkva
vscaagyh-s--tfkksspcaqnmllqlikapypglksgalktyghklti
sgqvviakhgklqscvwvlrcgpve-yhfpdefkaitmgdsefgfnkrlk
llsalakfgrnthgsrsklpcpdahsvnesmsylylfehvhnsakvlckv
spyqr--had-----qsdvqrsrneiklvq----nirdppdgvhnpy--l
afdphpglamkftdgaladratngahfalresnlmcfkvksyldlggmpa
shglestrkyyivlddpvdlriasvl---vkiksssvsl-lgkplitqph
cdrieadfsealsfaskcelslvsskgfgyrptvwglcipt-----iekv
apn-----pdfmvaklgksctdgtnfvlrvchtvdmgpllgm-lakswse
ac
>node11
qtthghev--qacssvpn-lvqft--drgrgskesangasnapwctnvcq
mvfagspsglat-gndhtetgrccptyciecaghgiscalldtkgca---
-kneanlncdekidasggvgefadqstqlsdskglhllfakkmaa-gkva
igcgagyh-a--tfkksspcaqhmllqvirhpypglktgglrsyghkati
sgnvviakdgklqscvwvircgpce-yhfpnefkaitmgdsefgfnkklk
llsapakfggpthgsrsklpcpdahsvneslsflylfahvhnpakilikv
srfqf--had-----qsdvqssrhevk--q----ntrdpddgghdsl--l
vfdphvalsmkltdgrladratngahyalresnlmcfkvktyldlggmpa
ghnl-------illsdpvdlriatvl---vklkpsnvsl-lgkplitqph
cdraesdftealsftakcelpfvsdkgfgyrptvwglcipa-----iekv
apl-----ptfmvaklgksctdgtnfiwrqchtvdmgplvgm-lakswsa
vc
>ENV_HV2G1/23-502
qtthghdv--qacstvpn-lvqft--drgrgskesangasnapwctnvcq
mvfagspsglat-gndhtetgrccptyciecaghgiscalldtkgca---
-kneanldcdekidasggvgefadqstqlsdskglhllfakkmaa-gkva
igcgagyh-a--sfkkstpcaqhmllqvirhpypglktgglrnyghkati
agnvviakdgkmqscvwvircgpce-shfpnefkaitlgdsefgfnkklk
llsaparfggpthgsrsklpcpdahsvneslsflylfahvhnpakilikv
srfqf--had-----qskvqssrhevk--q----ntrdpddgghdsl--l
vfdphvalsmkltdgrladratngahyalresnlmcfkvktylelggmpa
ghnl-------illsdpvdlriltvl---vklkpsnvsl-lgkplitqph
cdraesdftealsftakyelpfvsdkgfgyrptvwglcipa-----iekv
apl-----stfmvaklgksctdgtnfiwrqchtvdmgplvgm-lakswsa
vc
>ENV_SIVM1/24-528
qtthghev--qacssvpn-lvqft--drgrgskesanaasnatwctevcq
mvfagspsglat-gndhtetgrccptyciecaghaiscalldtkgca---
-kndanlncdskidapggvgefadqstqlsdskglhllyakkmaa-grva
iacgsgyh-s--tfkksspcaqhmllevipqpypglktgslrsyghklti
sgqvviakhgklqsvvwvircgpce-yhfpnefkaitmgdnefgfnkklk
llsapakfggsthgsrsklpcpdahavneslsflylfahvhnpasvlikv
srfqf--had-----qsdvqtsknevk--q----ntrdnddgghdsl--l
vfdphvalamkltdgrladratngahfgmpqsnlmcfkaktylhlggmpa
ghnl-------illndpvdlrvatvl---vkikpsnvsl-lgkpliaqph
cdraesditetlsftakcelnfvsdkgfgyrptvwalcipa-----iekv
aplltqtkptfmvaklgksctdgtnfiyrqchtvdmgpllgm-lakswst
ac
>node19
qtthghev--qacssvpn-lvqft--drgrgskesangasnapwctnvcq
mvfagspsglat-gndhtetgrccptyciecaghgiscalldtkgca---
-knesnlncdekidasggvgefadqstqlsdskglhllfakkmaa-ekva
igcgagyh-a--tfkksspcaqhmllqvirhpypglktgglrsyghkati
sgnvviakdgklqscvwviicgpce-yhfpnefkaitmgdsdfgfnkklk
llsapakfggpthgsrsklpcpdvhsvneslsflylfahvhnpakilikv
srfqf--had-----qsdvqssrhevk--q----ntrdpddgghdsl--l
vfdphvalsmkltdgrladratngahyalresnlmcfkvktyldlggmpa
ghnl-------illsdpvdlriatvl---vklkpsnvsl-lgkplitqph
cdraesdftealsftakcelpfvsdkgfgyrptvwglcipa-----iekv
apl-----ptfmvaklgksctdgtnfiwrqchtvdmgplvgm-lakswsa
vc
>ENV_HV2CA/25-512
etthghev--qacsnvpnfliqft--drnrgskesgngasnapwctnvcq
mvfagspsglat-gndhtetgrccptysiecanhgiscalldtkgcv---
-knesnlncdekidasggvsefsdqasqlsdskglhvlfakkmaa-ekvp
igcgagyh-a--tfkksspcaqhmllqvirhpypglktgglrsyghkati
sgnvviakdgklqscvwviicgpce-yhfpnefkaitmgdsdfgfnkklr
qlsapakfggpthgsrsklpcpdvysveeslsflylfahvhnpakillkv
srfqf--had-----qsdvddsmhevk--h----ntrdpddgghdslqpl
vfdphvalsmkltdgrladratngahyalresnlmcfkvksyldlggmpa
ghnl-------illsdpvdlriatvl---vklkpsnvsl-lgkplitqsh
cdrpisdftealsltakcklpfvsdkgfgyrptvwglcipa-----iekv
apl-----ptfmvaklgksctdgtnfiwrqcqtvdmgplvkm-lakswsa
vc
>node7
estqghev--qgcssvpn-lvqft--grgigskesanapsnatwctnvcq
avfagsgsglet-ggeqheggkcvsdyciecaentiscaqldlkgca---
-kneanescnakidasggvgefedhstqlshgkglrllfakkm---gkvs
vscaagyh-s--tfkksspcaqnmllqllkapysglksgalktyghklti
sgqlvipkhgklqscvwvlrcgpve-yhfpdefkainmgdsefgfnkrlk
llsalakfgrnthgsrsklpcpdahsvnesmsylylfehvhnsakvlckv
spyqr--had-----qsdvqrsrnenkldq----nirdppdgvhnpy--l
afdpnpelamkftdgalaeraangahfalresnlmcskvksyldlggkpa
shglestrkyyivlddpvdlriastl---vkiksssvslgv-kplitqph
cdreeadfsealsfaskcelslvsskgfgyrptvwalcipt-----iekv
apn-----phfmvaklgksctdgvnfvlrvchtvalgpllgm-lakswse
ac
>ENV_SIVG1/22-522
gstqghev--qgcssvpn-lvrft--grgigskesanapsnatwctnvcq
avfagsgsglpt-ggeqhdggkcvgdycidcaenliscaqldlkgca---
-kneanescnakidasggvgefedhstqlshgkglrllfakkm--pgkvs
vicaagyh-s--tfkksspcaqnmllqllkapysgkksgalktypqklti
sgqlviplhgklqscvwvlrcgpvelyhfpdefkainmgdsefgfnkrlk
llsalakfgrnthgsksklpcpdahsvnesmsylylfehshnsakvlckv
spyqk--had-----qsdvqrsrnenkldq----nirdppdgvhnpy--l
afdpnpelamkftdgalaeraangahfalresnllcskvtsyldlggkpa
shnlestrkyyivlddpvdlriastl---vkiksssvslgv-kplitrph
cdrdeadfsealsfaskcelslvspkgfgyrptvwalcipt-----iekv
apn-----phfmvaklgksctdglnfvlrvchtvalgpllgm-lgkswse
ac
>ENV_SIVV1/24-538
estrghevrwqgcsnipn-lveft--grgvgskesanapsnatwctnvcq
avfagsgrglet-ggeqreggkcvsdyciycaqntiscaqldlkgca---
-kdeanescnakidasggvgefqdhatqlshgkglrllfakkm---gkvs
vscaagyh-s--tfkksspctqnmllqlqkaqysglksgalktfghslti
kgqlviprhgklqscvwplrcgpve-yhfpdefktinvgdsemgfnkrlk
llsalakfgrnthgsqsrlpcpdghsvnesvsylylfehvhnsakvlckv
spyqr--haneyvasqsdvqrgrnenkldq----nirdppdgihnpy--l
afdpnpesamkftdgalaeraangahfalkesnlmcskvksyldlggkpa
shgleskrkyyivlddpldlrlastlrngvkikastvslgv-kplitqph
cdree--lseglafaskcelslvsskgfgykptvwalcipt-----ie--
apn-----phfmvaklgksctagvnfvtrvchevalgpllgm-lakswse
ac
>ENV_SIVGB/47-569
ertqghtv--qgcstvap-lvhftqarrghgsndsnevgrnmswctavce
mvfagrgsaletpageshesgtcvsqyciecadsaidcaqvilrgca---
-keesn---knkvdtvggvgtftehptqmshgkgvrllfakkk---gkvl
shcasgyn-srdtfkkenpcsvs----qikaaypdl--galktygqkatl
sgqvvlgnhgtlqccawvlrcgsve-yhfpdefkaihlgatdfafnrrvk
lvsnlfkferkthgarsriscpdahhvaesmsyiflfehvhdsakvlckv
spyqrtkhad-----ncevqrtrhliklvqvshgsvrappegvnnpy--l
afephaglamkftdsalgnrvtsgahfalhegnlmcfkvkcylelsgvpl
s-glaakrkyyivlddpvelqietll---vkakssdeav-lgqplitqph
cdrveadfadapafvgkvelalekqkgfaykpflwglcspynrmqrfekv
ppa-----pdfsiakltrsctdgtnfllsvchtvdigplfgvllaknwse
ac
>node17
qtthghev--qacssvpn-lvqft--drgrgskesangasnapwctnvcq
mvfagspsglat-gndhtetgrccptyciecaghgiscalldtkgca---
-knesnlncdekidasggvgefadqstqlsdskglhllfakkmaa-ekva
igcgagyh-a--tfkksspcaqhmllqvirhpypglktgglrsyghkati
sgnvviakdgklqscvwviicgpce-yhfpnefkaitmgdsdfgfnkklk
llsapakfggpthgsrsklpcpdvhsvneslsflylfahvhnpakilikv
srfqf--had-----qsdvqssrhevk--q----ntrdpddgghdslqpl
vfdphvalsmkltdgrladratngahyalresnlmcfkvktyldlggmpa
ghnl-------illsdpvdlriatvl---vklkpsnvsl-lgkplitqph
cdraesdftealsftakcelpfvsdkgfgyrptvwglcipa-----iekv
apl-----ptfmvaklgksctdgtnfiwrqchtvdmgplvgm-lakswsa
vc
>node9
qtthghev--qacssvpn-lvqft--drgrgskesanaasnatwctnvcq
mvfagspsglat-gndhtetgrccptyciecaghaiscalldtkgca---
-kneanlncdskidasggvgefadqstqlsdskglhllfakkmaa-gkva
iacgagyh-s--tfkksspcaqhmllqvirqpypglktgglrsyghklti
sgqvviakhgklqscvwvircgpce-yhfpnefkaitmgdsefgfnkklk
llsapakfggsthgsrsklpcpdahsvneslsflylfahvhnpakvlikv
srfqf--had-----qsdvqssrnevk--q----ntrdpddgghdsl--l
vfdphvalamkltdgrladratngahfalresnlmcfkvktyldlggmpa
ghnl-------illndpvdlriatvl---vklkpsnvsl-lgkpliaqph
cdraesdftealsftakcelnfvsdkgfgyrptvwglcipa-----iekv
apl-----ptfmvaklgksctdgtnfiyrqchtvdmgpllgm-lakswst
ac
>node10
qtthghev--qacssvpn-lvqft--drgrgskesanaasnapwctnvcq
mvfagspsglat-gndhtetgrccptyciecaghgiscalldtkgca---
-kneanlncdekidasggvgefadqstqlsdskglhllfakkmaa-gkva
igcgagyh-a--tfkksspcaqhmllqvirhpypglktgglrsyghklti
sgnvviakhgklqscvwvircgpce-yhfpnefkaitmgdsefgfnkklk
llsapakfggpthgsrsklpcpdahsvneslsflylfahvhnpakilikv
srfqf--had-----qsdvqssrhevk--q----ntrdpddgghdsl--l
vfdphvalsmkltdgrladratngahyalresnlmcfkvktyldlggmpa
ghnl-------illsdpvdlriatvl---vklkpsnvsl-lgkplitqph
cdraesdftealsftakcelpfvsdkgfgyrptvwglcipa-----iekv
apl-----ptfmvaklgksctdgtnfiyrqchtvdmgplvgm-lakswsa
vc
>node18
qtthghev--qacssvpn-lvqft--drgrgskesangasnapwctnvcq
mvfagspsglat-gndhtetgrccptyciecaghgiscalldtkgca---
-knesnlncdekidasggvgefadqstqlsdskglhllfakkmaa-ekva
igcgagyh-a--tfkksspcaqhmllqvirhpypglktgglrsyghkati
sgnvviakdgklqscvwviicgpce-yhfpnefkaitmgdsdfgfnkklk
llsapakfggpthgsrsklpcpdvhsvneslsflylfahvhnpakilikv
srfqf--had-----qsdvqssrhevk--q----ntrdpddgghdsl--l
vfdphvalsmkltdgrladratngahyalresnlmcfkvktyldlggmpa
ghnl-------illsdpvdlriatvl---vklkpsnvsl-lgkplitqph
cdraesdftealsftakcelpfvsdkgfgyrptvwglcipa-----iekv
apl-----ptfmvaklgksctdgtnfiwrqchtvdmgplvgm-lakswsa
vc
