>ENV_SIVV1/24-538
ygqakl----a----ncgpgmpnvakqyplcgmvcgvgnpasavldteqg
sytsicdhiwtvatdvqgkgrsdttlksnccpyack-v-vysvcwitpkn
asdnsldwgls--ptekwkgaqsa------dgckkdlmtkqhkksvaela
gkwvlhavwdysaglgcsakssraapghvvdrqettdvvedkkacktrfv
rvitsrryidtvncggktlsgalfivalkcqiiaykevd---hkalmqvk
ayykplrr--tpaehlasrsgmlntkpdekpatagdddkppepveht-ig
etskttsggdglrsctavavifmyvlsedghagyldcawlngqmrvsylf
mnhvgigg-kgdgq---lga-yslatslrnlpwtvvqhpvgyphdphns-
-spayhegrgaat-hcpadtadkdllahiatenfklteyqreslelepgs
veklfhti--iveqmvaqkflvlsa--eqnvgvlpgggegdfaaksvkls
nqfsvvyepekkki--lgsvenvanttdsgggqkskgdlqaglnygvklq
hlwavsv
>node19
ypqasl----a----ncgpgmpnvakpyelcglvcgvgnpenavldtq--
------------gtdieakglpdttmwanccpyaak-vgvksvc------
----plgwgln--pterwkghqkalgdvetegrkkdlmpkqnmrsvsemq
tnwvlhavwdytaglgcsakae----ghvvdrahttdavddskdckirfi
nvvtsrrytetvscggkslagalfvvavrcqiityqdvegsshkalmqvk
ayykplrr--tptvhltsrqgslnnkpdeklgaagdldkppiprehtkig
etskstaggdgmrscaafttifmyv-sedghvgyldcawmngrkrvqymy
lnhvgigg-kadgq---lsa-yslattlkaqpwtvvqhplgyphdrhns-
-tpayhpgwsfat-hcpgdtsdrdll--istekyklteyqreglelqkgs
veklfrsiry---mmtsqkflslpg--yqyvgvlpggsegefapkaikls
nhfsliyetgkskelalgsvdnvatqtlngagqksnakletglaygvklq
hlwavsg
>ENV_SIVG1/22-522
ygqakl----a----nsgpgmpgvakkypvcgmvcgagnpedavldtqqg
sytsicnriwtvntdiqgkgkpdttlrsnccpyatk-v-vysvcwv----
----sldwgls--pterwkgaqss------egckkdlmtkqnvksvseia
gkwvlhavwdytaglgcsakssraapghvvdrqettdvvednkdcktrfv
rvitstrvidtvncggktlagalfivalrcqiiaykevd---hkalmqvk
syykplrrvrtpaehlaarrgslnnkpdekpgtggdddkppipveht-ig
etskttsggnglrscmavtvifmyvlsedghagyldcawlngqmrvsymf
mnhvgigg-kgdgq---lsa-yslattlrnlpwtvlqhplgyphdphns-
-tpayhegrgaat-hcaadtadkdllahiasenfkltqyqreglelekgs
veklfrti--iviqmvarkflvlsa--yqnvgvlpgggeddfaakaikls
nqfsvvyetgktke--lgsvenvanttdsgagqkskgnlqagltygvklq
hlwamsv
>node10
ygqasl----a----ncgpgmpnvakpyelcgmvcgvgnpenavldtq--
------------gtdieakglpdttmwanccpyaak-vgvksvc------
----plgwgln--pterwkghqkalgdvetegrkkdlmpkqnmrsvsemq
tnwvlhavwdytaglgcsakae----ghvvdrahttdavddskdcktrfi
nvvtsrryietvscggkslagalfvvavrcqiityqdvegsshkalmqvk
ayykplrr--tptvhltsrqgslnnkpdeklgaagdldkppiprehtkig
etskstaggdgmrscaaittifmyv-sedghvgyldcawlngrkrvqymy
lnhvgigg-kadgq---lsa-yslattlkaqpwtvvqhplgyphdrhns-
-tpayhpgwsfat-hcpgdtsdkdll--istekyklteyqreglelqkgs
veklfrsiry---mmtsqkflslpg--yqnvgvlpggsegefapkaikls
nhfsliyetgkske--lgsvdnvatqtlngagqksnanletglaygvklq
hlwavsg
>ENV_HV2NZ/24-502
ypqasl----a----ncgpgmpnvakpyelcgltcgvgnpanavldtq--
------------gtdieakglpittmwanccpyaas-vgvksvc------
----plswgln--pterwrghqkalgdvetegrkkdlmpkqnmrsveemq
tnwvlhavwdytagigcsakae----ghvvdrahttdavedskd-kikfi
dvvtswrytetvscggkslagalfvvavrcqiityqdvegsshkalmqvk
ayykpl-r--tptvhltsrqgslnnkpdeklgaagdldkppiprehtkig
etskstaggdgmrscaafttihmyv-sedghvgyldcawmngrktvqymy
lnhvgigg-kadgqkvglsa-yslattlkaqawtvvqhplgyphdrhntr
ltpayhpgwsfat-hcpggtsdrdll--istekyklteyqreflelqkss
vgklfrsiry---mmtsqkflslpg--yqyvgvlpgasegefapkavkls
nhfs-iyetgkskelmlgsvdnvatqtlngagqkshakletglaygvklq
hlwsvsg
>node17
ypqasl----a----ncgpgmpnvakpyelcglvcgvgnpenavldtq--
------------gtdieakglpdttmwanccpyaak-vgvksvc------
----plgwgln--pterwkghqkalgdvetegrkkdlmpkqnmrsveemq
tnwvlhavwdytagigcsakae----ghvvdrahttdavddskd-kirfi
dvvtsrrytetvscggkslagalfvvavrcqiityqdvegsshkalmqvk
ayykplrr--tptvhltsrqgslnnkpdeklgaagdldkppiprehtkig
etskstaggdgmrscaafttifmyv-sedghvgyldcawmngrkrvqymy
lnhvgigg-kadgqkvglsa-yslattlkaqpwtvvqhplgyphdrhnsr
ltpayhpgwsfat-hcpgdtsdrdll--istekyklteyqreglelqkgs
vgklfrsiry---mmtsqkflslpg--yqyvgvlpggsegefapkavkls
nhfsliyetgkskelalgsvdnvatqtlngagqksnakletglaygvklq
hlwavsg
>ENV_HV2CA/25-512
ypqasl----a----ncgpgmpnvakpyelcglvcavgnaqnavlttq--
------------gtdveakglpdttmwanccpyaak-vgvksvc------
----plgwgln--ptqrwnghqkalgnvetegrkkdlmpkqnmrsveemq
tnwvlhgvwdytagigcynkae----gqvvdpahttdavddskd-kirfi
dyvtsrrytetvssggkslagalfavavrcqiityqdvegsshkalmhvr
ayykplrr--tptvhltsrqgslnnnpeaklgaagdldkppiprehtkig
etskstaggdgmrscaafttifmyv-sedghvgyldcawmngrkrvqymy
lnhvgigg-kadgqkvglsa-ysltttlkaqpwtvvqhplgyphdrhnsr
ltpayhpgwsfat-hcpgdtsdrdll--istekyklteyqreglelqkgs
vgklfrairy---mmtsekflsmpg--fqyvgvlpggsegefapkavkls
nhfsliyetgkskglalgsvdnvatqtlngagqksdakletglaygvklq
hlwavfg
>ENV_SIVM1/24-528
ygqasl----a----ncgpgmpnvakpyalcgmvcgvgnpedavldtq--
------------gtdiegkglpdttmwanccpyaak-vgvksvc------
----plgwgln--rterwkghqkalgdvetegrkkdlmpkqnmrsvsemq
tnwvlhavwdytaglgcsakas----ghvvdranttdavddskdcktrfi
hvvtsrryietvscggksiagalfivamrcqiityqdvegsshkalmqvk
ayylpmrr--tptihlssrqgflnnkpdeklgtagdldkppfpiehtkig
etskstaggdgmrscaavttifmyplsedghvgyldcawlngrkrvqymy
anhvgigg-kkdgq---lsa-yslattlrnqpwtvvqhplgyphdrhns-
-tpayhpgrsfat-hcpgdtsdkdll--iatenyrlteyqreglemqkgs
veklfrsirf---mmtaqkflslpg--yqnvgvlaggsdgefapkaikla
nhfsliyetgkske--lgsvdevatqtlngagqksnasletglaygvklq
hlwavsg
>node11
ypqasl----a----ncgpgmpnvakpyelcglvcgvgnpenavldtq--
------------gtdieakglpdttmwanccpyaak-vgvksvc------
----plgwgln--pterwkghqkalgdvetegrkkdlmpkqnmrsvsemq
tnwvlhavwdytaglgcsakae----ghvvdrahttdavddskdckirfi
nvvtsrrytetvscggkslagalfvvavrcqiityqdvegsshkalmqvk
ayykplrr--tptvhltsrqgslnnkpdeklgaagdldkppiprehtkig
etskstaggdgmrscaafttifmyv-sedghvgyldcawmngrkrvqymy
lnhvgigg-kadgq---lsa-yslattlkaqpwtvvqhplgyphdrhns-
-tpayhpgwsfat-hcpgdtsdrdll--istekyklteyqreglelqkgs
veklfrsiry---mmtsqkflslpg--yqnvgvlpggsegefapkaikls
nhfsliyetgkskelalgsvdnvatqtlngagqksnakletglaygvklq
hlwavsg
>node14
ypqasl----a----ncgpgmpnvvkpyelcglvcgvgnpenavldtq--
------------gtdieakglpdtamwanccpyaak-vgvksvc------
----pggwgln--pterwkghqkalgdvetegrkkdlmpkqnmrsvsdmq
tnwvlhavwdytaglgcsakae----ghvvdrahttdavdeskd-kirfi
navtsrrytetvecggkslagalfvvavrcqiityqdvegsshkalmqvk
ayykplrr--tptvhltsrqgslnnkpdeklgaagdldkppiprehtkig
etskstaggdgmrscaafttifmyv-sedghvgyldcawmngrkrvqymy
lnhvgigg-ksdgqkvglsa-yslattlkaqpwtvvqhplgyphdrhns-
-tpayhpgwsfat-hcpgdtsdrdll--iatekyklteyqreglelqkgs
vgklfrsiry---mmtsqkflslpg--yqyvgvlpggsegefapkaikls
nhfsliyetgkskelalgevdnvatqtlngagqksnakletgldygvklq
hlwavsg
>node7
ygqakl----a----ncgpgmpnvakqyplcgmvcgvgnpedavldtqqg
sytsicdriwtvgtdiqgkgrpdttlrsnccpyatk-v-vysvcwv----
----sldwgls--pterwkgaqsa------egckkdlmtkqnmksvsema
gkwvlhavwdytaglgcsakssraapghvvdrqettdvvednkdcktrfv
rvitskryidtvncggktlagalfivalrcqiiaykevd---hkalmqvk
ayykplrr--tpaehlasrrgslnnkpdekpgtagdddkppipveht-ig
etskttsggdglrsctavtvifmyvlsedghagyldcawlngqmrvsymf
mnhvgigg-kgdgq---lsa-yslattlrnlpwtvlqhplgyphdphns-
-tpayhegrgaat-hcpadtadkdllahiatenfklteyqreglelekgs
veklfhti--iveqmvarkflvlsa--yqnvgvlpgggegdfaakaikls
nqfsvvyetgktke--lgsvenvanttdsgagqkskgnlqagltygvklq
hlwavsv
>ENV_HV2D2/24-513
ygqasl----a----ncgpgmpnvakpydlcgmvcgvgnpenavldtq--
------------gtdieakglpdttmwanccpygek-vgvkrvc------
----plgwgln--pterwkghqkalgdvetegrkknlmpkqnmrsvtemq
tawelhavwdytsglgcsaksd----ghvvdrahttdavdaskdcksrfi
nvvtsrqyietvscggkslasalfvvavrcqiitykdgegsshkalmqvk
af--plrr--tptvhlasrqaslnnkpddklgaagdldkppiprphtkig
etkkstagqdgmrscaqittifmyv-sedghvgyldcawlngskrvqymy
lnhveigg-kadgq---lsaqyclastlkaqpwtavqhslgyphdrhns-
-tpayhpgwsfag-hcpgdtsskdll--nstekykltvyqrgglelqkgs
veklfrsiry---mmtsqkflslpg--yqnagvlpggsegefapkaikls
nhfsliyetgksse--lgsvenvatqtlngagqksnahletglsygvklq
hlwavsg
>ENV_SIVGB/47-569
lgevklarglp----ncapgdgnvarqhplcglvcdvgdpeeaildpq--
------------gkatqgkdapdvtmrtnacpvd-kyv-vfsvp------
----slgwgls--pterwkgnqsp------egc-----------------
------avweytaglgcgskssmaspghivdqqhttdalddakdcslkfv
hvitskrytktvtcgtkslagqnfavfl---iiaykevddsshkalmqrk
syykplkr--tpadnllsrrgsldnkaaakkgvsgdhdkkpiplaht-vg
-tsktesggdgmwsvaaiilifly-laddthnkcldcgwmnglkrvsyff
vehvgvsgctgqgk---lta-yalaatlksvprkvvqhplvypndphks-
-nsaysrgqsaaqghcpgdradndvlahvptknfklidyqreelelqtgs
ieqlfrsi-----qmtaqkflvnga--yknvgvlsdggegdngskaikis
sqf--vyetgkgkq--lqnlhdlapntlngagqkskdnleagptygvkla
hlwsisv
>node9
ygqasl----a----ncgpgmpnvakpyalcgmvcgvgnpedavldtq--
------------gtdiegkglpdttmwanccpyaak-vgvksvc------
----plgwgln--pterwkghqkalgdvetegrkkdlmpkqnmrsvsemq
tnwvlhavwdytaglgcsakas----ghvvdrahttdavddskdcktrfi
hvvtsrryietvscggkslagalfivamrcqiityqdvegsshkalmqvk
ayykplrr--tptvhltsrqgslnnkpdeklgtagdldkppipiehtkig
etskstaggdgmrscaavttifmyvlsedghvgyldcawlngrkrvqymy
lnhvgigg-kgdgq---lsa-yslattlraqpwtvvqhplgyphdrhns-
-tpayhpgrsfat-hcpgdtsdkdll--iatenyklteyqreglelqkgs
veklfrsiry---mmtaqkflslpg--yqnvgvlpggsegefapkaikls
nhfsliyetgkske--lgsvdnvatqtlngagqksnanletglaygvklq
hlwavsg
>ENV_HV2D1/24-501
ypqasl----aklhgncgpgmpngvkpyelcglvcgvgnpenavldtq--
------------gtdieakglpdaamwanccpyaak-vgvksvc------
----pggwglnnhpterwkghqkalgdvetegrgkdlmpkqnmrsvsdmq
tnwvlhavwdytaglgcsakae----ghvvdhahttdavdeskd-kirfi
navtsrrytetvecggkslagalfvvavrcqiityqdvegsshkalmqvk
ayytplrr--tptvhltsrqgslnnkpdeklgaagdldkppiprehtkig
etskstagtdgmrscaafttifmyv-nedghvgyldcawmngkkrvqymy
lnhvgigg-ksdgqkvglsa-yslattlkaqpwtvvqhplgyphdkhns-
-tpayhpgwafat-hcpgdtsdrdll--iatekyklteyqreglelqkgs
vgklfrsvry---mmtsqkflslpg--yqyvgvlpggtegefapkaikls
nhfsliyetgkskelalgevdnvatqlllgagqksnakletgldygvklq
hlwavsg
>node18
ypqasl----a----ncgpgmpnvakpyelcglvcgvgnpenavldtq--
------------gtdieakglpdttmwanccpyaak-vgvksvc------
----plgwgln--pterwkghqkalgdvetegrkkdlmpkqnmrsvsemq
tnwvlhavwdytaglgcsakae----ghvvdrahttdavddskd-kirfi
nvvtsrrytetvscggkslagalfvvavrcqiityqdvegsshkalmqvk
ayykplrr--tptvhltsrqgslnnkpdeklgaagdldkppiprehtkig
etskstaggdgmrscaafttifmyv-sedghvgyldcawmngrkrvqymy
lnhvgigg-kadgqkvglsa-yslattlkaqpwtvvqhplgyphdrhns-
-tpayhpgwsfat-hcpgdtsdrdll--istekyklteyqreglelqkgs
vgklfrsiry---mmtsqkflslpg--yqyvgvlpggsegefapkaikls
nhfsliyetgkskelalgsvdnvatqtlngagqksnakletglaygvklq
hlwavsg
>node8
ygqakl----a----ncgpgmpnvakqyplcgmvcgvgnpedavldtq--
------------gtdiqgkglpdttmrtnccpyask-v-vysvc------
----sldwgls--pterwkgaqsa------egckkelmnkqnmrsvsemq
gnwvlhavwdytaglgcsakssraapghvvdrqhttdavedskdcktrfv
hvitskryidtvscggkslagalfivalrcqiiaykevdgsshkalmqvk
ayykplrr--tpaehlasrrgslnnkpdeklgtagdddkppipveht-ig
etskttsggdgmrsctavtvifmyvlsedghagyldcawlngqkrvsymf
mnhvgigg-kgdgq---lsa-yslattlrnlpwtvvqhplgyphdphns-
-tpayhpgrsaat-hcpgdtadkdllahiatenfklteyqreglelqkgs
veklfrti-----qmtaqkflvlsa--yqnvgvlpgggegdfaakaikls
nqfslvyetgktke--lgsvenvatqtlngagqkskanleagltygvklq
hlwavsv
>ENV_HV2BE/24-510
yphasl----a----ncgpgmpnvvkpyelcglvcgvgnpenavldtq--
------------gtdieakglpntamwanccpyaak-vgvksvc------
----pggwgln--pterwkghqkalgdvetegrkkdlmpkqnmrsvsdvq
tnwvlhavwdytaglgcsakae----ghvvdrahttdavdeskd-kirfi
navtarrytetvecggkslagalfvvavrcqiityqdvegsshkalmqvk
ayykplrr--tptvhlaarqgslnnkpeeklgaagdldkppiprehtkis
ettkstapgdgmrscaafttifmyv-sedghvgyldcswmngrkrvqymy
lnhvgigg-ksdgqkvglsv-yseattlkaqpwtvvqhplgyphdrhns-
-tpayhpgwsfat-hcpgdtsdrdll--latekykltecqreglelqkgs
vgklfrsiry---mltsqkflslpgfiyqyvgvlpggsegefapkgikla
nhfsliyetgkskklalgevdnvatqtlngagqkskakletgldygvklq
hlwavsa
>ENV_HV2G1/23-502
ypqasl----a----scgpgmpnvakpyelcglvcgvgnpentildtq--
------------gtdieakglpdttmwanccpyaak-vgvksvc------
----plgwgln--pterwkghqkalgdvetegrkkdlmpkqhmrsvsemq
tnwvlhavwdytagvgcsakae----ghvvdrahttdavddskdckirfi
nvvtsrrytetvscggkslagalfvvavrcqiityqdvegsshkalmqvk
ayykplrr--tatvhmtnrqgslnskpdeklgaagdldkppiprehtkig
etskstaggdgmrscpafttifmyv-sedghvgyldcawmngrkrvqymy
lnhvgigg-kadgq---lsa-yslattlkaqpwtvvqhplgyphdrhns-
-tpayhpgwsfat-hcagdtsdrdll--istekyklteyqreglelqkgs
venlfrsiry---mmtsqkfl--pg--yqnvgvlpggsegefapkaikls
nqfsliyetgkskelalgsvdnvatqtlqgagqksnakletglaygvklq
hlwavsg
