>ENV_HV2CA/25-512
vvrges--mklehgpgayd--ykvnyllrkagytlpkkqldgataasgnh
kkrscafaqlhvgkgftfrcycftp--ggvsispgevadgnsdgitlvva
apasvplnggcgenkddqpkcrcapfekgrisffkkikmpasyqilflph
atqkagwnphqqcawtsqqmrgaawieeyaghkgtvkphktetkeqamf-
-t--tgdvhaellndfkpefiikkygdsqlqrktaeaklka-epkytnil
hekssqcyshtqkwsasglpcingaravqtrdshtmalcplqssql---y
svnhvvrredtkmlvythksepesv-gekgtaschvqesvvisehddecv
vlygpvgdclnkdil-----aanfteahtiafgiktke------lnvskv
nistavyafinenqliifrklkvsrlalipslpsvg-----lndecf-vv
rssgeddsafnerkigdstidikctnhavvrfavskqegcltvaknghee
askmgvaaiegfhtw---tgitkaitsghlylsthaqfgrvk
>ENV_SIVG1/22-522
lqrges--vkledgpgayt--ykinyllkktsyvlpkrqidapaaasgfp
skrlcpfgtlhvtksftfkcycfnp--gkvsigpgeiadgnddgivlvva
apasvnlnsgcgqdvddepi----pfskgvipffkkiklpasyqilflph
atqkadwnphqqcartsqhmmgvawteeyaghkgrvkphktntkdlamy-
-t--skdvhaellsafkpeyivkkygesqlersttqatfqp-npkyinil
sekgsqcwsktqkwsasglpclgsaravqsrdphtaalcplqqsqlgrgy
svnqvvr-----llvychksepesl-gekgtadcnldesmvvsehddecv
----pvgncl--dil-----sagfteahtvgfniktke------lsaykv
nistahfaflnaiqtivyqklt------iatlpcag-----lnkayl-vv
rtsged-asfngrtvgnsafkikctnlarlrfavatqegcltv---gnde
eskvgvv-----htwgykdnsarttksehvylsthaqfgrak
>ENV_HV2BE/24-510
lvrgeg--mklehgpgayd--ykvnyllrkagytlpkkqldgatsasgnh
kkrscsfaqlhvgkgftfrcycftp--ggvsispgevadgnsdgivlvva
spasvplnggcgenkddqpkcrcspfekgrirffkkikmpasyqilflpr
atqkadwnphqqcawtsqqmrgaawieeyaghkgtvkphktntkeqtmf-
-t--tgdvhaellnefksefiikkygdsqpqrktaeaklka-epkytnil
hekvsqcyshtqkwsasglpcingaravqardshtmhlcpltssql---v
svnhvvr-----mlvykhksepesv-getgtaschlqesvvisehddecv
vlygpvgncl--dilkpdffaanfteahtiafgiktie------ldvskv
nestavyafisqnqliifrklkvsrlalipslpcvg-----lndecf-iv
rspgeddsafnerkigdstidikcknhavlrfavskqdgcltvaknghen
askmgvaavedfhtw---tgttkaitsghlyltthaqfgrvk
>ENV_SIVM1/24-528
lihges--mklehgpgayn--ykvnyllrksgytlpkkqldgataasgnh
tkrscafgqlqvgkgftfrcycftp--ggvsispgevadgnsdgivlvva
apasvglnggcgqnkddqptcrcapfekgripffkkpkmpasyqilylph
atqkadwnphqpcawtsqqmrgvawfdeyaghkgsvkphkthtkeetmf-
-t--tgqvhaellsdfkpeyiikkygdrqlqrktpeaklka-epdytnil
hekgsqcyshtqkwsasglpclnsaraaqardshtmalcpvqssql---y
svnhvvr-----mlvyvhksepesv-gekgtaschldesvvisehddecv
vlhgpvgncl--dil-----aakfteahtigfgiktke------lnvakv
nissavyaflgqnqliifrklk------ipslpcvg-----lnddcf-vv
rssgidasafngrkigeatfnikctnhavlrfavakqegcltv---dhee
askmgvatvegfhtw---dgstkavksghlyisthaqfgrvk
>node8
lqrges--mklehgpgayt--ykinyllkkssytlpkrqidgpaaasgfh
skracpfgtlhvgkgftfkcycftp--gkvsispgeiadgnddgivlvva
apasvnlnggcgqnvddqpi----pfdkgvipffkkikmpasyqilflph
ttqkadwnphqqcawtsqhmmgvawteeyaghkgrvkphktntkdlamy-
-t--sgdvhaellsafkpeyivkkygesqlerkttqatlqp-npkyanil
hekgsqcyshtqkwsasglpclgsaravqsrdphtaalcplqssql---y
svnhvvr-----llvychksepesv-gekgtadcnldesmvvsehddecv
----pvgncl--dil-----sagfteahtvgfgiktke------lnatkv
nistavyaflnalqtivyqklt------iptlpcvg-----lndacl-vv
rssged-ssfngrkvgnstfnikctnlavlrfavakqegcltv---gnde
eskvgvv-----htw---dnsakaiksehvylsthaqfgrsk
>node19
lvrges--mklehgpgayd--ykvnyllrkagytlpkkqldgataasgnh
kkrscafaqlhvgkgftfrcycftp--ggvsispgevadgnsdgivlvva
apasvslnggcgenkddqptcrcapfekgrisffkkikmpasyqilflph
atqkadwnphqqcawtsqqmrgaawieeyaghkgtvkphktntkeqtmf-
-t--tgdvhaellndfkpefiikkygdsqlqrktaeaklka-epkytnil
hekssqcyshtqkwsasglpcingaravqardshtmalcplqssql---y
svnhvvr-----mlvythksepesv-gekgtaschlqesvvisehddecv
vlygpvgncl--dil-----aanfteahtiafgiktke------lnvskv
nistavyafinqnqliifrklkvsrlalipslpcvg-----lndecf-vv
rssgeddsafnerkigdstidikctnhavlrfavskqegcltvaknghee
askmgvaavegfhtw---tgstkaitsghlylsthaqfgrvk
>ENV_SIVGB/47-569
lgkdea--lknqngpgayttaykinfllklsaytlpkididgpannssyh
skrtcpfnslhvkkgftgkcycfvpflpkikispgaisdqpsdgivlvia
appsvdlndgsnnnlddqpl----p-drsvivffkriklptgylilflpq
vtqycgnhpnqqcawsaqhmmasawkialaghkgrvkahkdnkkdlamn-
-n--aya--aeiaspfkpesivkqygeteldrksakaslqpanpknakil
dtkgrecyssthkwgasglpclgsarevksrdpvtallcglesspl---f
svhhsvr-----lltyckksepeaaggekgtancnvdesvvvfedaaqcv
----svgkcl--dil-----slgysyangigfgikihe------vnttvv
gfqtaayaflhglqnipyhdfi------iptlpctgykppglndacl-vi
rsspee-snfngrkvgkatfnikitnfallgfpvagqn------------
------p-----hdw---nnpatnieseqv-lethaqfgrsk
>node14
lvrges--mklehgpgayd--ykvnyllrkagytlpkkqldgataasgnh
kkrscafaqlhvgkgftfrcycftp--ggvsispgevadgnsdgivlvva
apasvslnggcgenkddqpkcrcapfekgrisffkkikmpasyqilflpr
atqkadwnphqqcawtsqqmrgaawieeyaghkgtvkphktntkeqtmf-
-t--tgdvhaellndfkpefiikkygdsqlqrktaeaklka-epkytnil
hekssqcyshtqkwsasglpcingaravqardshtmalcpltssql---y
svnhvvr-----mlvythksepesv-gekgtaschlqesvvisehddecv
vlygpvgncl--dilkpdffaanfteahtiafgiktke------lnvskv
nistavyafinqnqliifrklkvsrlalipslpcvg-----lndecf-vv
rssgeddsafnerkigdstidikctnhavlrfavskqegcltvaknghee
askmgvaavegfhtw---tgttkaitsghlylsthaqfgrvk
>node17
lvrges--mklehgpgayd--ykvnyllrkagytlpkkqldgataasgnh
kkrscafaqlhvgkgftfrcycftp--ggvsispgevadgnsdgivlvva
apasvslnggcgenkddqpkcrcapfekgrisffkkikmpasyqilflph
atqkagwnphqqcawtsqqmrgaawieeyaghkgtvkphktntkeqtmf-
-t--tgdvhaellndfkpefiikkygdsqlqrktaeaklka-epkytnil
hekssqcyshtqkwsasglpcingaravqardshtmalcplqssql---y
svnhvvr-----mlvythksepesv-gekgtaschlqesvvisehddecv
vlygpvgncl--dil-----aanfteahtiafgiktke------lnvskv
nistavyafinqnqliifrklkvsrlalipslpcvg-----lndecf-vv
rssgeddsafnerkigdstidikctnhavlrfavskqegcltvaknghee
askmgvaavegfhtw---tgttkaitsghlylsthaqfgrvk
>ENV_HV2D1/24-501
lvrges--mklehgpgayd--ykvnyllrkagytlpkkqldgataangnh
kkrscafaqlhvgkgftfrcycftp--ggvsispgevadglsdgivlvva
apasvslnggcgenkddqpkcrcap----risffkkikmpasyqilflpr
atqkgdwnphqqcawtsqqmrgaawieeyaghkgtvkphktntkeqgmf-
-t--tsdvhaellndfkpefiikkygdsqlqsktaeaklka-kpkytnil
hekssqcythtqhwsasglpcingaravqardshtmalcpltssql---y
svnhvvr-----mlvythksepesv-gekgtaschlqesvvisehddecv
vlygpvghcl--dilkpdffaakfteahtiafgiktke------lnvakv
nistavyafvnqnqliifkklkvsrlalipslpcvg-----lndecf-vv
rssgednsafnerkigdstiditctnhavlrfavskqegcltvaknghee
askmgvaavegfhtw---tgttkaitsghlylsthaqfgrvk
>ENV_HV2NZ/24-502
lvrgds--mdlehgpgayd--ykvnallrkagytlpkkqlegataasgnh
kkrscafaqlhvgkgftfrcycftp--ggvsispgevadgntdgivlvva
apasvslnggcgenkddqpkcrcapfeegkisffkkikmpvsyqmlflph
atqkagwnphqqcawtiqqmrgaswieeyaghkgtvkphktntkeqtvf-
-t--sgdvhaellsdfkaefiikkygdsqlqrktavaklka-epkytnil
hdkssqcyshtqkwsesglpcingaravqardshtmalcplqntql---y
yvnhvvk-----mlvythksqpesv-gekgtaschlqesvvisehddecv
alygpagncl--dil-----aanfteahtiafgiktks------lnvskv
nistavhafvnqnqliiasklkvsrlalipslpcvg-----lndecf-vv
rssgennsafnerkigdstidikctnhavlrfavskqegcltaaknghee
askmgvaavegfhtw---tgttkaitsghlylsthaqfgrvk
>node11
lirges--mklehgpgayd--ykvnyllrkagytlpkkqldgataasgnh
kkrscafaqlhvgkgftfrcycftp--ggvsispgevadgnsdgivlvva
apasvglnggcgenkddqptcrcapfekgrisffkkikmpasyqilflph
atqkadwnphqqcawtsqqmrgaawieeyaghkgtvkphktntkeqtmf-
-t--tgdvhaellndfkpefiikkygdsqlqrktaeaklka-epkytnil
hekssqcyshtqkwsasglpcingaravqardshtmalcplqssql---y
svnhvvr-----mlvythksepesv-gekgtaschlqesvvisehddecv
vlygpvgncl--dil-----aanfteahtigfgiktke------lnvskv
nistavyafinqnqliifrklkvsrlalipslpcvg-----lndecf-vv
rssgeddsafnerkigdstfdikctnhavlrfavskqegcltvdknghee
askmgvaavegfhtw---tgstkaitsghlylsthaqfgrvk
>ENV_HV2G1/23-502
lirges------hgpgayd--ykvnnllrkagytlpkkqldgataasgnq
kkrscafavlhvgkgftfrcycftp--ggvsispgevadgdsdgtvlvva
cpasvgldggcgenkddqptcrcapfekgrisfykkikmpasyqilflph
atqkadwnphqqcawtsqqmrdaawieeyaghkgtvkphktntkeqtmf-
-t--tgdvhaelindfkpefiiskygdsqlqrktaeaklka-epkftnil
heksiqcyshtqkwsasglpcingaravqardshtmalcplqsaql---y
svnhvvr-----mlvythksepesv-gekgtaschlqesvvisehddecv
vkyspvgncl--dil-----aanfteahtigfgiktke------lnvssv
nistpvyafinqnqliifrklkvsrlalipslpcvg-----lndecf-vv
rssgeddsafnerkigdstfdikctthavlrfavskqegcltvdknghee
askmgvaavegfhtw---tgstkaitsghlylsthaqfgrvk
>node7
lqrges--mkledgpgayt--ykinyllkkssyalpkrqidapaaasgfh
skrlcpfgtlhvgksftfkcycfnp--gkvsispgeiadgnddgivlvva
apasvnlnsgcgqdvddqpi----pfskgvipffkkikmpasyqilflph
ttqkadwnphqqcartsqhmmgvawteeyaghkgrvkphktntkdlamy-
-t--skdvhaellsafkpeyivkkygesqlerkttqatlqp-npkyinil
hekgsqcysktqkwsasglpclgsaravqsrdphtaalcplqssqlgrgy
svnqvvr-----llvychksepesl-gekgtadcnldesmvvsehddecv
----pvgncl--dil-----sagfteahtvgfniktke------lnatkv
nistavyaflnaiqtivyqklt------iptlpcvg-----lndacl-vv
rssged-ssfngrtvgnstfkikctnlavlrfavakqegcltv---gnde
eskvgvv-----htw---dnsaktiksehvylsthaqfgrsk
>ENV_SIVV1/24-538
lqrgesvsmklengpgayt--ykinyllkkssfalpkaqvdapaaasgfh
skrlcpfgtlhvgksftfkcycfnp--gkvsispgeiadgnddgivlvva
apcsvnlksgcgqdvgdqpi----pfskgvipffkkikmpasyqilflph
ttqkgdsnphqqcartsqhmmgvawtesyaghkgrvkphktntkdlaiyn
lt--lkdvhaellsalkpeyivkkygesqlerkttqatkqp-npkyinil
hekgsqcysktqkwsasglpclvaaravqqrdpqtaalcplqssqlgrgy
avdqvvr-----llvychktepesl-gekgsadcnldesmlvsehddecv
----pvgncl--dil-----gagfteahtvgfnikake------lnatkv
nistavyaflnaiqtkvyqnlt------iptlpcvg-----lndaclvvv
rssgkg-cdfngrtvgnstfkigctnlavlrfavakqegcltv---gkde
eskvgvv-----htw---dhsaktiksehvylsthaqfgrss
>node9
lirges--mklehgpgayn--ykvnyllrksgytlpkkqldgataasgnh
tkrscafgqlhvgkgftfrcycftp--ggvsispgevadgnsdgivlvva
apasvglnggcgqnkddqptcrcapfekgripffkkikmpasyqilylph
atqkadwnphqqcawtsqqmrgvawieeyaghkgsvkphktntkeqtmf-
-t--tgdvhaellsdfkpeyiikkygdsqlqrktpeaklka-epkytnil
hekgsqcyshtqkwsasglpclnsaravqardshtmalcplqssql---y
svnhvvr-----mlvyvhksepesv-gekgtaschlqesvvisehddecv
vlygpvgncl--dil-----aakfteahtigfgiktke------lnvakv
nissavyaflnqnqliifrklk------ipslpcvg-----lndecf-vv
rssgeddsafngrkigdstfnikctnhavlrfavakqegcltv---ghee
askmgvaavegfhtw---dgstkaiksghlylsthaqfgrvk
>ENV_HV2D2/24-513
lirges--mklergpgayn--ykvnyllrkagytipkkqldgetaasgnh
tkrscafaqlhvgkgftfrcycftp--ggvsissgdvadgnsdsivlvva
apas-----gcgqnkddpatcrcapfekgripffkkikmptsyqilylph
aaqkadwnphqecawtssqmrgvawveeyaghkgsvkphktnikeqgkf-
-taitgdvnaellsefkpeyiikkygdsqlqrktaqaklka-epkytniv
hdksshcyshiqkwsasglpclngaravqardshtmalcalqssql---y
svnhvvr-----mlvyvhkcaaest-gekgsaschlqestiisehddecv
vlygpvgncw--dil-----ranfteartidfgikakencflgelnvakv
nissavyaflnqndliifrklv------ipslpcvg-----lnddcf-vv
rssseddsafngrkigdstfnikctnhvvlrfavsrqegcltv---ghee
asnmgvaavegfhsw---tgskksitsghiylsthaqfgrvk
>node18
lvrges--mklehgpgayd--ykvnyllrkagytlpkkqldgataasgnh
kkrscafaqlhvgkgftfrcycftp--ggvsispgevadgnsdgivlvva
apasvslnggcgenkddqpkcrcapfekgrisffkkikmpasyqilflph
atqkadwnphqqcawtsqqmrgaawieeyaghkgtvkphktntkeqtmf-
-t--tgdvhaellndfkpefiikkygdsqlqrktaeaklka-epkytnil
hekssqcyshtqkwsasglpcingaravqardshtmalcplqssql---y
svnhvvr-----mlvythksepesv-gekgtaschlqesvvisehddecv
vlygpvgncl--dil-----aanfteahtiafgiktke------lnvskv
nistavyafinqnqliifrklkvsrlalipslpcvg-----lndecf-vv
rssgeddsafnerkigdstidikctnhavlrfavskqegcltvaknghee
askmgvaavegfhtw---tgttkaitsghlylsthaqfgrvk
>node10
lirges--mklehgpgayd--ykvnyllrkagytlpkkqldgataasgnh
tkrscafaqlhvgkgftfrcycftp--ggvsispgevadgnsdgivlvva
apasvglnggcgqnkddqptcrcapfekgripffkkikmpasyqilylph
atqkadwnphqqcawtsqqmrgvawieeyaghkgsvkphktntkeqtmf-
-t--tgdvhaellsdfkpeyiikkygdsqlqrktaeaklka-epkytnil
hekssqcyshtqkwsasglpclngaravqardshtmalcplqssql---y
svnhvvr-----mlvyvhksepesv-gekgtaschlqesvvisehddecv
vlygpvgncl--dil-----aanfteahtigfgiktke------lnvakv
nissavyaflnqnqliifrklk------ipslpcvg-----lndecf-vv
rssgeddsafngrkigdstfdikctnhavlrfavakqegcltv---ghee
askmgvaavegfhtw---tgstkaitsghlylsthaqfgrvk
