>node9
eta--------fvrpntlr--gvarkdvelr-----ctgkgciatnkkcg
kikhsgvcsqkkpppdkeadkyavgrgaa--sivv----eqalggfrpaa
rq----------rkvasscyqarfeysgahatpdtag--kkegyslekeh
trggfkckkaksldlyatpkftvapkwsgciltleiekhlpsepsvfagy
--vdtneltvnnsvvkcnafsktqlhacvfasapvkta---qlcsvknev
qg--ktglecksskagt--lknpgyamgcdvgllavakwvrkksvvittd
e-klqgkyiitpmrskfvktgfcvvaveivynrlyflferkcqwef-grs
hvcgpykalakaqsv--gapeisrdllckakelikmcqtkdatpsahlqk
ysgshgdtrgganfdsssqapkpnpsycedfi--sthscqrsrlicshfp
glvrsrvraketvspmakggqaeavvnkrv----ifpigdlrtcisesng
rvkglvklspgkanitctnitratytae--------------npggkrcl
iggrgafspivqaegl
>ENV_SIVM1/24-528
eta--------fvranklr--gvarkdvelr-----ctgkgciaankkcg
kighsgvcaekkpppdkeadkyavgrgaa--sivv----eqalggfrpaa
kq----------rkvasscyqarfeysgahatpdtag--kkegynlekeh
trggfkckkaksldlyatpkftvapkwagciltlqiekhlpsepsifagy
--vdtneltvnnsvakcnafsktqlhacvfasapvkta---qlcgvknev
qg--ktglecksskagt--lknpgfamgcdvgllavakwvrkksvvittq
e-klqgkyiitpmrskfvktgfcvvaveivynrlyflferkcqsef-grs
hvcgpykaltkaqtv--gapeisrdllckamelikmcqtkdatpsahlqk
ysgshgdtrgganfdsssqapkpnpsycedfi--sthscqrsrlicshfp
glvrsrvraketvspmskggqaeavvnkrv----ifpigdlrtcisesng
rvk--------kanipctnitratytae--------------np-gkrcl
iggrgafspivqaegl
>ENV_HV2D1/24-501
eta--------fvrpntlr--gvarkdvelr-----ctgkgciatnkkcg
nikhtgvssqkkpppdkaadkyatgrgaa--svvv----thalggfrpaa
rq----------r-vasscyearfeysgahatpdtag--kkfaytleaeh
trggfkckklksldlyaipkfhvapkwsgciltleiekhlpsepsvfagy
hkvdtaaltinns-vkctafsktelhacvfasapvkss---qlcsvknev
qggkktglecgsskagt--lkkpgyamgcdvgllgvakwvrkksvvittd
e-klqgkyvitpmrskfvktgfcvvaveiiynrlyflferkcqwef-grs
hvcgpykalskaqsv--gapeisrdllckakelikacqtkdatpsahlqk
ysgshgdtrgganfdsssqspkpnptycedfi--sghscqrsrlicshfp
glvrarvraketvspmakggqaeavvnkrv----ifpigdlrtcisksng
rvkglvklspgkahitctnitratytae--------------npggkrcl
iggagafspivqkegl
>node8
eta--------fvrpntlr--avarkvvelr-----ctgkgcivankrcg
qikhggvcsqkkpppdteadkyaigrgaa--sivc----eqafggfrhaa
rhkleeftrdrvvkvasscyqprfeysgahaapdvas--kkegyslekeh
trgnfkckkgksldlystpkftvaqkwggciltlkvekhipsepsvfaay
--vdtneltansavvkcnafhktqlhacvfastpvkna---qlcelknev
qg--htglecksskpgl--lkhpgyamgcdvgllavakwvrkksviittd
e-klqgnyiitpvrskfvktgacivavefvynrlyflferrcqwef-grs
rvcgpykslakaqsv--ggpeinrellckskeliklcqtpdatasahlqk
ysgshddtrgsakfdsnvqapkptppycedfi--stksiqrtrlicshfp
glvrtrvrikealspkadggqadavvnkrv----tfpignlrscisesng
rvkglvglsagklnftctnitratytae--------------npgftrcl
lggrgafsaivqaedl
>ENV_HV2BE/24-510
eta--------fvrpntlr--gvahkdvelr-----ctvkgciatkkkcg
hikhtgvcsekkpppdkeadkyatghgat--aiav----eqalggfrpaa
rq----------rkvasscyearfeysgahatpdqag--kkfgysleeeh
arggfickkaksldlyatpkfhvtpkwsgciltleiekhlpsepsvfagy
--vdgaaltidnsvvkcnafsktqlhacvfasapvksa---qfcsvknev
pggkknglecgsskagt--lkkpgyamgcavgllgvakwvrkksvvittd
e-klqgkfvitpmrpkfvktgfcvvaveiiynrlyflferkcqwef-grs
wvcgpykalskaqsv--gapeinrdllckakvlikacqtkdatpsahlqk
ysgshgdtrggsnfkssnhspkpnpaycedli--sthscqrsrlicsqfp
glvrarvraketvspmanggqaeavvnkrv----tfpigdlrtcisksng
rvkglvklspgkahitctnvtratktae--------------npggkrcl
iggagafspivqkeal
>ENV_SIVGB/47-569
etavqfscira-vrpsaln--tverklielr-----ctgkgcivankrcg
qikhggvvghrkpapdmeadkfaiapgas--sivf----aqafsgfreea
shkieefsrskvikvasscygprfeysgshtasdvac--kvdgyglekqq
tksdfkckkgnaldlystakytkdqrwggcvqslkvekfipsertvfgay
--vksneltveatvvksqafdktqlhacvfsatpvkna---llcnldnev
kg--hvglecmvskaglaklkhagytlgcnvglfavakwvrekstiiyid
e-qlqknytitqvrskfsktgmcivadnlmynrfyilfnfrcaref-gkt
rvcspyraldkiqnvcsgapeinrnlvckhkelvnlchcpqakttdn--n
ypkv-----gsakfetnvqapkpsppycsdfikcsarsldrtrliasnfn
glvktrvrknlplfpkaeigeaatvtnkpvpylctfptqdfrscisetkv
rikslvvlsavklkptcsntsnavytae--------------npgfsrcl
lggqgaisvivqfedl
>ENV_HV2CA/25-512
eta--------fvrphtlw--glsrkevevr-----ctgkgciatskkcg
kikhsgvcsqkkpppdkeadkyatgrgaa--sivvksnfeqalggfrpaq
kq----------rkvasscyearfeysgahatpetag--kkfgyslekeh
trggfkckkaksidlyatpkihvapkwsgciltldiekhlpsepsvfagy
--idageltinnsvvkcnafnktqlhacvfasapvksa---qlcsvknev
qg--ktglqcksskagt--lkkpgyamgcdvgllavakwvrkksvvittd
e-klegkyvitpmrskfvktgfcvvaveiiynrlyflfertcqwef-grs
hvcgpykalakvqdv--gapeisrdllckakelikacqtkdatpsahlqk
ysgshgdtrgganfdassqspkpnpsycedfi--sthscqrsrlicsqfp
glvrarvraketvaamaragqaeavvnkrv----ifpigdlrtcisksng
rikglvklspgkghitctnitratytae--------------npgekrcl
iggagafsaivqkegl
>node17
eta--------fvrpntlr--gvarkdvelr-----ctgkgciatnkkcg
kikhsgvcsqkkpppdkeadkyatgrgaa--sivv----eqalggfrpaa
rq----------rkvasscyearfeysgahatpetag--kkfgyslekeh
trggfkckkaksldlyatpkfhvapkwsgciltleiekhlpsepsvfagy
--vdtneltinnsvvkcnafsktqlhacvfasapvksa---qlcsvknev
qg--ktglecksskagt--lkkpgyamgcdvgllavakwvrkksvvittd
e-klqgkyvitpmrskfvktgfcvvaveiiynrlyflfertcqwef-grs
hvcgpykalakvqsv--gapeisrdllckakelikacqtkdatpsahlqk
ysgshgdtrgganfdassqspkpnpsycedfi--sthscqrsrlicsqfp
glvrarvraketvapmakagqaeavvnkrv----ifpigdlrtcisksng
rvkglvklspgkghitctnitratytae--------------npggkrcl
iggagafspivqkegl
>node11
eta--------fvrpntlr--gvarkdvelr-----ctgkgciatnkkcg
kikhsgvcsqkkpppdkeadkyatgrgaa--sivv----eqalggfrpaa
rq----------rkvasscyearfeysgahatpdtag--kkfgyslekeh
trggfkckkaksldlyatpkfhvapkwsgciltleiekhlpsepsvfagy
--vdtneltinnsvvkcnafsktqlhacvfasapvksa---qlcsvknev
qg--ktglecksskagt--lkkpgyamgcdvgllavakwvrkksvvittd
e-klqgkyvitpmrskfvktgfcvvaveivynrlyflferkcqwef-grs
hvcgpykalakaqsv--gapeisrdllckakelikacqtkdatpsahlqk
ysgshgdtrgganfdsssqspkpnpsycedfi--sthscqrsrlicsqfp
glvrsrvraketvspmakggqaeavvnkrv----ifpigdlrtcisksng
rvkglvklspgkahitctnitratytae--------------npggkrcl
iggagafspivqkegl
>node18
eta--------fvrpntlr--gvarkdvelr-----ctgkgciatnkkcg
kikhsgvcsqkkpppdkeadkyatgrgaa--sivv----eqalggfrpaa
rq----------rkvasscyearfeysgahatpdtag--kkfgyslekeh
trggfkckkaksldlyatpkfhvapkwsgciltleiekhlpsepsvfagy
--vdtneltinnsvvkcnafsktqlhacvfasapvksa---qlcsvknev
qg--ktglecksskagt--lkkpgyamgcdvgllavakwvrkksvvittd
e-klqgkyvitpmrskfvktgfcvvaveiiynrlyflferkcqwef-grs
hvcgpykalakaqsv--gapeisrdllckakelikacqtkdatpsahlqk
ysgshgdtrgganfdsssqspkpnpsycedfi--sthscqrsrlicsqfp
glvrarvraketvspmakggqaeavvnkrv----ifpigdlrtcisksng
rvkglvklspgkahitctnitratytae--------------npggkrcl
iggagafspivqkegl
>node10
eta--------fvrpntlr--gvarkdvelr-----ctgkgciatnkkcg
kikhsgvcsqkkpppdkeadkyatgrgaa--sivv----eqalggfrpaa
rq----------rkvasscyearfeysgahatpdtag--kklgyslekeh
trggfkckkaksldlyatpkftvapkwsgciltleiekhlpsepsvfagy
--vdtneltinnsvvkcnafsktqlhacvfasapvkta---qlcsvknev
qg--ktglecksskagt--lkkpgyamgcdvgllavakwvrkksvvittd
e-klqgkyiitpmrskfvktgfcvvaveivynrlyflferkcqwef-grs
hvcgpykalakaqsv--gapeisrdllckakelikacqtkdatpsahlqk
ysgshgdtrgganfdsssqspkpnpsycedfi--sthscqrsrlicshfp
glvrsrvraketvspmakggqaeavvnkrv----ifpigdlrtcisksng
rvkglvklspgkahitctnitratytae--------------npggkrcl
iggagafspivqaegl
>ENV_HV2NZ/24-502
eta--------fvrpntlr--gaarkd--lr-----ctgkgctatnkkcg
kikhsgvcsqkkpppdkegdkyatgrgaa--sivv----qqalggfrpaa
rq----------rkvasscyeahfdysgahatpetag--kkfgysleken
trggfkckrarslelyntpkfhvspkwsgciltlqiekhlpnepsvfagy
--vdtneltinnsivkckafsksqlhacvfasapvksa---qlcsvknev
qg--ktglecksskagt--lkkpgyamgcdvgllavakwvrkksvvittd
e-klqgkyvitlmrskfvktgfcvmaveiiynrlyflfertcqwef-grs
hvcgpykplakvqsv--gapevtrdllckskelikacqtkdatpsahlqk
yqgshgdtrgganfdassqspksnpsycedfi--sthscqrsrlicsqfp
glvrarvkaketvapmakagqaeavvnkrv----ifpigdlrtcisksng
kvkglvklspgkghitctnitratysae--------------npggkrcl
iggagafspivqkegl
>ENV_HV2G1/23-502
eta--------fvrpntlr--gvarkdvelrtsgsnctgqgciatnkkcg
kikhsgvcsqkkpppdkeadkyatgrgaa--sivv----eqalggfrpaa
rq----------rkvatscyearfeysgahatpdtag--kkfgyslekeh
trggfkckkaksldlyatpkfhvapkwsgciltleiekhlpsepsvfagy
--vdtneltinsavvkcnafsktqlhacvfasapvksa---qlcsvknev
qg--ktglecksskpgt--lkkpgyamgcdpgllavakwvrkksvvittd
e-klhgkyvitpmrskfvktgfcvvaveivynrlyflferkcqwef-grg
hvcgpykalaksqsv--gapqisrdllckakelikacqtkdatpsahlqk
ysgshgdtrgganfdsnsqspkpnpsycedfi--sthscqrsrlicsqfp
glvrsrvraketvspmakggqaeavvnkrv----ifpigdlrtciskang
rvkglvklspgkahitctnitratytae--------------npsgkrcl
iggagafspivqkegl
>node14
eta--------fvrpntlr--gvarkdvelr-----ctgkgciatnkkcg
nikhtgvcsqkkpppdkeadkyatgrgaa--sivv----eqalggfrpaa
rq----------rkvasscyearfeysgahatpdtag--kkfgysleaeh
trggfkckkaksldlyatpkfhvapkwsgciltleiekhlpsepsvfagy
--vdtaaltinnsvvkcnafsktqlhacvfasapvksa---qlcsvknev
qggkktglecgsskagt--lkkpgyamgcdvgllgvakwvrkksvvittd
e-klqgkyvitpmrskfvktgfcvvaveiiynrlyflferkcqwef-grs
hvcgpykalskaqsv--gapeisrdllckakelikacqtkdatpsahlqk
ysgshgdtrgganfdsssqspkpnpsycedfi--sthscqrsrlicsqfp
glvrarvraketvspmakggqaeavvnkrv----ifpigdlrtcisksng
rvkglvklspgkahitctnitratytae--------------npggkrcl
iggagafspivqkegl
>ENV_SIVG1/22-522
etg--------fvwpntlrdqavarkvvelr-----ctgkgcivankrcg
qikhqgvcsqkkppadtqadkyaigrgaa--sivc----eqafdgfrhpg
rhkleeftrdrvvkvatscyqprfeysgahaapdvas--kkegyslekeh
trgnfkckkgksldlystakftvaqkwggcvltlkvekhipsepsvfaay
--vdtndltgdsavvgcnafhktqlhacvfastpvkqaitaqlcelknev
qg--htglecktskpgl--lkhpgyamtctvglmavakwvhkksviitts
dtklqgqytiasvrskfvktgacivavdfvfnrlyflierrcqwelsgrs
rvigpykslskaqsi--ggpeinrellckrkdliklcqtpdatasahlqk
yssshddtrgsakfdsnvqapkptppfcedfi--atksvqrtrlicshfp
glvgglvkikealspkadggqadsvvnkrv----tfqvgnfrscisetkg
rvkglvglspgklnftctnitratytaeviesvqfagskmvvnpgftrcl
lggrgafsl-vdaenl
>node19
eta--------fvrpntlr--gvarkdvelr-----ctgkgciatnkkcg
kikhsgvcsqkkpppdkeadkyatgrgaa--sivv----eqalggfrpaa
rq----------rkvasscyearfeysgahatpdtag--kkfgyslekeh
trggfkckkaksldlyatpkfhvapkwsgciltleiekhlpsepsvfagy
--vdtneltinnsvvkcnafsktqlhacvfasapvksa---qlcsvknev
qg--ktglecksskagt--lkkpgyamgcdvgllavakwvrkksvvittd
e-klqgkyvitpmrskfvktgfcvvaveivynrlyflferkcqwef-grs
hvcgpykalakaqsv--gapeisrdllckakelikacqtkdatpsahlqk
ysgshgdtrgganfdsssqspkpnpsycedfi--sthscqrsrlicsqfp
glvrsrvraketvspmakggqaeavvnkrv----ifpigdlrtcisksng
rvkglvklspgkahitctnitratytae--------------npggkrcl
iggagafspivqkegl
>node7
etg--------fvwpntlrdqavarkvvelr-----ctgkgcivankrcg
qikhggvcsqkkpppdtqadkyaigrgaa--sivc----eqafdgfrhaa
rhkleeftrdrvvkvasscyqprfeysgahaapdvas--kkegyslekeh
trgnfkckkgksldlystakftvaqkwggciltlkvekhipsepsvfaay
--vdtneltgnsavvkcnafhktqlhacvfastpvkqaltaqlcelknev
qg--htglecksskpgl--lkhpgyamtctvgllavakwvhkksviitts
d-klqgqyiiasvrskfvktgacivavefvfnrlyflferrcqwelsgrs
rvcgpykslakaqsv--ggpeinrellckrkeliklcqtpdatasahlqk
ysgshddtrgsakfdsnvqapkptppycedfi--atksvqrtrlicshfp
glvrtlvkikealspkadggqadsvvnkrv----tfqvgnlrscisetng
rvkglvglspgklnftctnitratytaeviesvqfagskmvvnpgftrcl
lggrgafsa-vqaenl
>ENV_HV2D2/24-513
eta--------fvrpntlr--gvarkdvelr-----ctgkgciatngkcg
kikhsgvcaakkpppdkeadkyatgrgsatgsivv----eqalggfrpav
hq----------rkvasscyearfeysgahatpdtag--kklgyslekeh
tkggfkckkaksldlyatpkftvapkwsgciltleiekhlpsepsvfaay
--vdtneltinnsvikcnafsktqlh-cvfasapvkta---qlcsvknev
qg--ktgldcksskagt--lkkpgygmgcevsllavakwvrkksvaittd
e-klqgkyiitpmrskfvktgfcvvaveivhnrlyylferkcqwef-grs
-vcgpykavpkaqsv--gapeisrdllckakelikacqvkdatpaahlqk
ysgshsdtrgganfdsssqspkpnpsycedfi--s-hscqrsrlicshfp
glvrsrvrakeivspmakggqaeaveskrv----ifpisdlrtciskkng
rvkgmvklspgkahitctnitratytae--------------npggkrcl
iggagafspivqaegl
>ENV_SIVV1/24-538
gtg--------fvwpntirdqavarrvvelr-----ctgkgcivan----
---hggvcsqkkpppdtqaekyaigrgaa--kivc----eqafdgfhhaa
rhsleeftrarvvkvasscyqprfeysdahsipdvasgkkkegfsleksh
tranfrckkgksldlystakftvaqkwggciltlkvekhipsepsvfaay
--vdtseltgntavvkcnayhktnlhacvfastpvkqalvaglcelknev
qg--htgvecksskpgl--lkhpgfamtctigllavakwvhkksviitts
d-klqgqyivasvrskfvktgacivavefvfhrlyflfarrcqwelsgrs
rlcgpykslakaqnv--ggpaenrellckrkdlmklcqtpkatasahlqk
ysgshddtrgsakfhsnvlspkptpayckdfi--atksvqrtrlvcsrfp
glvrtlvkvsqalspkvdagqadsivnkrv----tfqvnnlrscieatng
rvrglvgkspgklnftctnitratstaevteavqfagskvvvtpgaprcl
lgnrgaisp-vqadnl
