>node14
efkekfkqhgedv---yglpf------ntk---alpgs-ldlflphkngd
hprr-vadcqditnnkldagdlmetkavylrpefvlvkhtgqrlvalknf
-nsfyglvvyattwaraqcegliklskkqgyvpplkacltscqqlplvnm
viaapdchf-qydrnvrglqssqtssggfgdtkqklekdylgk---adnp
pig-dahkveslqrgvllslipkepfvsghkel---avekilyykaiaet
qnpifanhlargalwshvgdt------ryklpqyakvnlsstskkgakdg
vcddtvckdtrwakaycgcn-----------lgidis----lgdgsvims
-stkrlqiavgcvckqdkhrratcslgvlgwahinviqpkdifqilkkpd
k--dw-gqrtghdrfstkfaksgadwggrlaqicd-gifltedlyvdqhr
cikvymsmssdlgvghtpcglvghqiival--fkpgkflqnkqnqfnhs-
-aiaaflrlavskhkfadrlckhpngtlvk---htevskckragrhcfcp
svlkhc
>node10
efkdkfkqhgedm---ygfpf------ntk---alpgs-ldlflphkngd
hprr-vagcqditnnkldagdlmetkavylrpefvlvkhtgqrlvalknf
-nsfyglvvyattwaraqcegliklskkqgyvpplkacltscqqlplvnm
vlaapdchf-qyernvrglqssqtssagfgktkqklekdflgk---sdnp
pig-darkveslqrgvllslipkepfvsghkel---avekipyykaiaet
qnpvianhlargalwshvgdt------ryklplyakvnlsstskkpakdg
vcddtvckdtrwakaycgck-----------lgidis----lgdgsvims
-stkrlqiavgcvckqdkhrratcslgvlgwahinviqpkkifqilkkad
k--dw-gqrtghdrfskkfaksgadwggrlaqicd-gifltedlyvdqhr
cikvymsmssdlgvghtacglvghqiival--fkpgkflqnkqnqfnhs-
-aiaaflrlavskhkfadrlckhpngklvk---htevskckragrhcfcp
svlkhc
>node8
efkvkfkregnek---ygfsf------ntk---alpgk-ldlflphkdgd
hprrgiagchditndklgagdlmntkamylrpdfv-----gqrlvalsnf
-nsfyglavyatnsareqcegliklskkqgyvpptkaclsscdqlpledm
viaapdchfkeyernvrglqssqtgshgfdkteqklekdfvgk---sdnp
pig-etrkveslqrgvllslipkepfasghkal---avekiphykaiaea
qnpvianhlargalwthvgdt------rfqlplytkvnlsmsskkpakdg
vcddtvcketrwakaycgck-----------lgidis----lddgsvils
-nskrlkiamgcvchqdrhrratcslnvlgwahvgviqckkifqilkkag
k--dwygqraghnrfadkfarggadwggrlaqicd-gvfltedlqvdqhr
cikvymsmssdmgvsqtacslvghqiivcl--fksgkilrnkqnqfnhs-
-piqafnkfavskhkfadllckspngrlvknvg---vtkckrggrhcfcp
sv-knc
>node11
efkdkfkqhgedv---yglpf------ntk---alpgs-ldlflphkngd
hprr-vagcqditnnkldagdlmetkavylrpefvlvkhtgqrlvalknf
-nsfyglvvyattwaraqcegliklskkqgyvpplkacltscqqlplvnm
vlaapdchf-qydrnvrglqssqtssagfgdtkqklekdflgk---adnp
pig-darkveslqrgvllslipkepfvsghkel---avekilyykaiaet
qnpvfanhlargalwshvgdt------ryklplyakvnlsstskkgakdg
vcddtvckdtrwakaycgcn-----------lgidis----lgdgsvims
-stkrlqiavgcvckqdkhrratcslgvlgwahinviqpkkifqilkkad
k--dw-gqrtghdrfskkfaksgadwggrlaqicd-gifltedlyvdqhr
cikvymsmssdlgvghtpcglvghqiival--fkpgkflqnkqnqfnhs-
-aiaaflrlavskhkfadrlckhpngtlvk---htevskckragrhcfcp
svlkhc
>ENV_SIVGB/47-569
afkvkfkread-lpgiedfsf------nakeyqllpgtrlqlflphkegq
hprrgiescnelsndslsagdvlntnafflrpdfe-----shrkvglakf
tntfyglaiygtnnare-----iklsrslgyvppakacvsscdqlpledp
vmatsdcpfkeyestvrsvqssqsgshgfhkteqkaakdfvnkthtpdnp
pit-etrkvevlqrgvlldlipqepfstdhkalaltaceglpqykaipea
lntaianhlarstlwthvgetseikavrfqlplytkvnfsatgkkpakkg
vckenlsketrwaktycacklvgsmavsnlpkgvdia----lddgsvvls
-a----kiamgcvchherhrsatctlntlgwghvgvaqckkifqvlnktg
k--dwygekvghnkfadkfargaakwggrvaevcn-gvrltedtqvqqhr
cinvy-slysdrdvaqtacslaghsivvclenfkggqilrnkrnqfndaa
ipiqdfnaftvsqtklkdllckspksrliknig---vqkcklggrhcfcp
av-kdc
>node9
efkdkfkqhgdem---ygfpf------ntk---alpgs-ldlflphkngd
hprr-vagcqditnnkldagdlmetkavylrpefvlvkhtgqrlvalknf
-nsfyglavyattwareqcegliklskkqgyvpplkacltscqqlplvdm
vlaapdchf-eyernvrglqssqtnsagfdktkqklekdflgk---sdnp
pig-earkveslqrgvllslipkepfvsghkel---avekipyykaiaet
qnpvianhlargalwshvgdt------ryklplyakvnlsstskkpakdg
vcddtickdtrwakaycgck-----------lgidis----lndgsvims
-stkrlqiavgcvckqdkhrratcslnvlgwahinviqpkkifqilkkad
k--dw-gqrtghdrfskkfaksgadwggrlaqicd-gifltedlyvdqhr
cikvymsmssdlgvghtacglvghqiival--fkpgkflqnkqnqfnhs-
-aiaaflrfavskhkfadrlckhpngklvk---htevtkckragrhcfcp
svlkhc
>ENV_SIVM1/24-528
efkdkfkqhgdev---ygfpf------ntk---alpgs-ldlflphkngd
hprk-vagcqditnnkldagdlmetkavylrpefvlvkhtgqrlvalrnf
-nsfyglavyattwpreqcegliklskkhgyvpplkacltsceqlplvnm
vlappdchf-eyernlrglqssqansagfdktkqklekdflgk---sdnp
pig-earkveslqrgvltslipkepfvsghkei---avekipyydsiaet
qnpvfanhlargalwshvgdt------ryklplyakvnlsstskkpekdg
vcddtickdtrwakaycgck-----------lgidil----lndgsvims
-stkklqiavgcvcvqdkhrratcslnvlgwahinviqpkkifqilkkad
k--dw-gqrtshdrfskkfaksgtdwggrlaqicd-nifltedlyvdqhr
cikvymsmssdlgvghtacglvghqiival--fklgkflqnkqnqfnhs-
-aiaaflrftvskhkfadrlckhpngklvk---htevtkckragrhcfcp
svlkhc
>node7
efkvkfkregnek---ygfsf------ndk---alpgk-l-lflphkdgd
hrrrgiagcdditndklgagdlmntkamylrpdlv-----gqrllalsnf
-hsfyglavyagnsareqcegliklskkqgyvpptkaclsscdqlpledm
vvaapechfkeyernvrglqssqtgshgfekteqkldkdfvgk---sdnp
pig-etrkveslerglllslipkepfasghkal---avekiphykaiaea
qnpvianhlargylwthvgdt------rfnvplytkvnlsmsskkpakdg
vcddtvcketrwakaycgck-----------lgidin----lddggvils
gnskrlkiamgcvchqdrhrratctlnvlgwahvgviqcknifqilkkag
k--dwyaqraghnrfadkfarggadwgkrlaqicd-gvfltedlqvdqhr
cikvymsmssdmgvsqtacslvshqiivcl--fksgkilrnkqnqfnhs-
-pvqsfnkfavskhkfsdll---------knvg---vtkckrggrhcfcp
sv-knc
>ENV_HV2NZ/24-502
efkekfmqhgedv---yglpf------nak---alpgs-ldlflphkngd
hprr-vaqcqditnnkldaadlmetkavylrpefvlvkhtgqrlvalknf
-nsfyglviyattwaraqcegliklkkkqgyvpplkacltscqqlplvdm
vlaapdchf-qydrkvrglqssqtssagfgdtkqkleksllgk---adsp
pig-nahkveelqrsvllslipkepfvsghkel---avkkilyykaiaet
qnpvfanhlargalwshvgdn------ryklplyakvtlsstskkgakdg
vcddtvckdtrwakaycgcn-----------igidis----lgevsvims
-stkrlqiavgcvckqdkhrratcsvgvlgwahinviqskdifrilkktd
t--dw-gqrtghdrfskkfgksgadwggrlaqicd-gifltedlyvdqhr
cikvlmsmtsdlgvghtpcnlvghqiival--fkpgkflqnkqnqfnhs-
-aiaaflrlavskhkfadrlckhpngtlvk---htevskckragrhcfcp
svlkhc
>ENV_HV2D2/24-513
efkdklkqhgedm---ygfpf------ntk---alpgn-ldlflphkngd
hprr-vsgcqditnnkldagdlmetkavyirpefvlvkhtgqrlvalknf
-nsf-givvyattwarapcegliklskkqgyvpplkacltscqqlplvnm
vlaapechf-qvdrnvrglqsgvassagfgktkqklakdflgk---sdkp
piggdarkveslqrgvllplipkepfvsghkel---avekipyykaitet
qdpvianhlargalwshvget------ryklplyakvnlsstskkpakdg
vcddttckdsrwakaycgck-----------lgidis----laggsvmms
-stkrlqiavgcvckqdkhrraacslgvlgfahinviqpkklfqilkkad
k--dw-gqrtghdrfskkfaesgadwggrlaqicd-giflpedlyvdgrs
cikvymsmssdlgvghtacglighqvilal--fkpgkflqnkqnqfvht-
-aiaaflplavskhkfadrlckhpngklvk---htevskckragrhcfcp
avlkhc
>node17
efkekfkqhgedv---yglpf------ntk---alpgs-ldlflphkngd
hprr-vagcqditnnkldagdlmetkavylrpefvlvkhtgqrlvalknf
-nsfyglvvyattwaraqcegliklskkqgyvpplkacltscqqlplvnm
vlaapdchf-qydrnvrglqssqtssagfgdtkqklekdflgk---adsp
pig-nahkveelqrgvllslipkepfvsghkel---avekilyykaiaet
qnpvfanhlargalwshvgdt------ryklplyakvnlsstskkgakdg
vcddtvckdtrwakaycgcn-----------lgidis----lgdgsvims
-stkrlqiavgcvckqdkhrratcslgvlgwahinviqpkdifrilkkad
k--dw-gqrtghdrfskkfaksgadwggrlaqicd-gifltedlyvdqhr
cikvlmsmtsdlgvghtpcglvghqiival--fkpgkflqnkqnqfnhs-
-aiaaflrlavskhkfadrlckhpngtlvk---htevskckragrhcfcp
svlkhc
>ENV_HV2G1/23-502
efkdkvkqhgedv---yglpf------ntk---alpgs-lalflphkngd
hprr-vagcqqitnnkldvgdlmetkavylrpefvlvkhtgqrlvalknf
-nsfyglvvfattwaraqcngliklskkqgyvpplkacltscqqlplvnm
vlaapdchf-qydrnvrglqssqtksagfgdtkqklekdflgk---adnp
pig-darkveslqrgvllslipkepfvsghkel---avekilyykaiaet
qnpvfanhlargalwshvgdt------ryklplyakvnlrstskkgakdg
vcddtvckdtrwpraycgcn-----------lgidig----lgdgsvims
-stmrlqiavgcvckqdkhrratcslgvlgw-----ikpkkifqilkkad
k--dw-gqrtghdrfskkfaksgadwggrlaqicd-gifltedlyvdqhr
cikvymsmssdlgvghtpcglvghqiival--fkpgkflqnkqnqfnhs-
-ataaflrlalskhkfadrlckhpngtlvk---htevskckmagrvcfcp
svlkhc
>ENV_HV2BE/24-510
efkekfkqhgedv---yglpf------ntk---alpgs-ldlflphkngd
hprr-vadcqditnnkldagdlmetkavylrpefvlvkhtgqrlvalknf
-lsfyglvvyattwaraqcegliklskkqgyvpplkacltscqqlplvnm
viaapdchf-qydrnvrglqssqtssggfgdtkqklprdylgk---adnp
pig-dahkvdslqrgvllslipkepfvsghrel---avekilyykaiaet
hnpifsnhlargalwthvgat------ryklpqyakvnlsstskkgakdg
vcdetvckdtrwakaycgcp-----------lgidis----lgdgsiims
-stkrlqipvgcvckqkkhrratcslgvlgwahinviqpkdifqilkkpd
kicdw-gqrtghdrfstkfaksgsdwggrlaqicd-difltedlyvqqhr
cikvymsmtsdlgvghtpcgmvghqiival--fkpgkflqnkqnqfnrs-
-aiaaflrlavskhkfadrlckhpngtlvk---htevskckragrhcfcp
svlkhc
>node18
efkekfkqhgedv---yglpf------ntk---alpgs-ldlflphkngd
hprr-vagcqditnnkldagdlmetkavylrpefvlvkhtgqrlvalknf
-nsfyglvvyattwaraqcegliklskkqgyvpplkacltscqqlplvnm
vlaapdchf-qydrnvrglqssqtssagfgdtkqklekdflgk---adnp
pig-dahkveslqrgvllslipkepfvsghkel---avekilyykaiaet
qnpvfanhlargalwshvgdt------ryklplyakvnlsstskkgakdg
vcddtvckdtrwakaycgcn-----------lgidis----lgdgsvims
-stkrlqiavgcvckqdkhrratcslgvlgwahinviqpkdifqilkkad
k--dw-gqrtghdrfskkfaksgadwggrlaqicd-gifltedlyvdqhr
cikvymsmssdlgvghtpcglvghqiival--fkpgkflqnkqnqfnhs-
-aiaaflrlavskhkfadrlckhpngtlvk---htevskckragrhcfcp
svlkhc
>node19
efkdkfkqhgedv---yglpf------ntk---alpgs-ldlflphkngd
hprr-vagcqditnnkldagdlmetkavylrpefvlvkhtgqrlvalknf
-nsfyglvvyattwaraqcegliklskkqgyvpplkacltscqqlplvnm
vlaapdchf-qydrnvrglqssqtssagfgdtkqklekdflgk---adnp
pig-darkveslqrgvllslipkepfvsghkel---avekilyykaiaet
qnpvfanhlargalwshvgdt------ryklplyakvnlsstskkgakdg
vcddtvckdtrwakaycgcn-----------lgidis----lgdgsvims
-stkrlqiavgcvckqdkhrratcslgvlgwahinviqpkkifqilkkad
k--dw-gqrtghdrfskkfaksgadwggrlaqicd-gifltedlyvdqhr
cikvymsmssdlgvghtpcglvghqiival--fkpgkflqnkqnqfnhs-
-aiaaflrlavskhkfadrlckhpngtlvk---htevskckragrhcfcp
svlkhc
>ENV_HV2D1/24-501
efkekfkkhgedv---yglpf------ntk---alpgs-ldlflphkngd
hprw-vadcqditnnkldagdlmetkavylrpefvlvkhtgqrlvalknf
-nvfyglvvyattwaraqcegliklskkqgyvpslkacltscqplplvnm
viaapdchf-qydrnvrglqssqtssggfgdtkqklekdylgk---adnp
pig-dahkveslqrgvllsliptepfvsghkel---avekilyykaiaet
qnpifathlargalwshvgdt------ryklpqyakvnlsstskkgakds
vcddtvckdtrwakaycgcn-----------lgidis----lgdgsvims
-stkrlqiavgcvckqdkhrrptcslgvlswahinviqpkkifqilkkpd
k--dw-gqrtghdrfstkfaksgadwggrlaqkcdsgifltedlyvdqhr
cikvymsmssdlgvghtpcgkvghqiival--fkpgkflqnkqnqfnhs-
-aiaaflrlavskhkfanrlckhpngtavk---htevskckragrhcfcp
svlkhc
>ENV_SIVV1/24-538
gfkvkfkregngk---ygfsf------ndk---alpgk-l-l-lpykdgd
hrrrgiagcdeithdklgagdlmntkamylrpdlv-----gqrllalshf
-hsfyglavyagnsareqceglikiskkqgyvpptkaclssceqlpledm
viaapechfgeyqrnvrglqsshsgkhgfektqqkldkdfvgk---sdnp
pig-etrkveslerglllslipeepfatghkal---lvekiphykaiaea
qnpvianhlargylwthvggt------rfnvplytsvnlkmsgkkpgkdg
vcqatvcketrwakaycgck-----------lgadin----lddggvrls
gnskrlkiemgcvchqdqhrratctfnelgwahvgvnqckhifqilkkag
k--nwyaqhanhgrfadkfargggdwgkrlgqice-gvfltedlqvdqhq
ciklymsmssdmgv---acslvshqiivcl--fnsgkilrkkqnqfnhs-
-pvqsfnkgavskhkfsvll---------knvg---vtkckiggrhcfcp
sv-knc
>ENV_SIVG1/22-522
efkvkfkregnek---ygfsf------ndk---alpgk-l-vflphkdgd
hrrpgiagcdditndklgagdlmntkamylrpdlv-----gqrllalsvf
-hsfyglavyagnsareqcegliklskkqgyvpptkacmsscdqlpledm
vvagpechfkeyernvrglqssqtgshgfekteqkldkdfvgk---sdnp
pig-etrkveslerghllhlipkepfasghkal---avqkinhyksiaea
qnpvianhlakgylwthvget------rfnvplyttvnlslplkkpakdg
vcgdtvcketrwakaycgck-----------lgidin----lddggails
gnskrlkiamgcvchqnrhrratctlnvlgwahvgviqcvnifqilkkag
k--dwyaqraghnrfadkfarggadwgkrlaqicd-gvfltedlqvdphr
cikvymsmssdmgvsqtacslvshqiivcl--fksgkilrnkqnqfnhs-
-plqsfnkfavskhkisdll---------knvg---vtkckrgdrhcfcp
sv-kdy
>ENV_HV2CA/25-512
efkekfkqhgedv---yglpfyyfdlkntk---dlpgs-lnlflphkngd
hprr-vsgcqditnnkldagdlmetkavylrpefvlvkhtgqrllalknf
-nsfyglvvyattwaraqceglikltkkqgyvpplkacltsvqqlplvnm
vlaapdchf-qndrnvrglqssqtssagfedtkqklekdflgk---adsp
pig-nahkveelprgvllsllpkepfvsghkel---avekilyykavaet
qnpvfathlargalwsqvgdt------ryklplyakvnlsstskkgakdg
vcddtvckdkrwakaycgcn-----------lgidisgktalgdgsvims
-stkrlqiavgcvckqdkhrratcslgvlgwakinviqpkdifrilknad
k--dw-gqrtghdrfskkfaksgadwggrlaqicd-gifltedlyvdqhr
cikvlmsmtsdlgvghtpcglvghqiival--fkpgkflhnkqnqfnhs-
-aigaflrlavskhkfadklckhpnatlvk---htevskckragrqcfcp
tvlkhc
