>ENV_SIVV1/24-538
aglgvvpktrclrdaenlacpninqnvghd-geqgaapyykrsyytmgge
tl-----hlstyihadrtlinfsgv---qraqscvvtyfgfdkkvaqa--
--vsdektgkirashfftcpynqcanipkivesckeatielcagaspvgk
riktrcqshatqs-tksspgklpdyqvgsagmfdaqgrkcefngsgydev
mglvktnlvtatqleggplcsrpkqgi--dmassnketghqgl--pvpnl
lesasqctrstkfhwahlnqllfaygg-----illktnrhgagkltpeit
akcvatyqakcakdldmdvygrqapddtfcfv----ykaagctkevwsek
lqpvgakdkydaeypdg------------f-akpcgeplkstkkveladl
lhsgrkvwkeiwtsteealig-vc------vyegsasksyyyaitsykyd
cilrtahvaldckaala-----------vvgydkwpgpqprevg------
-------ragmntahlpfawygaasgsftfqggmkkhrdanyfsptd
>node18
adlgvvpktrcledaknlvcpsinqtvghq-neqsavpyykrgyygktpe
ilvkgsthlstyihen--girfsgv---qraqscvvtyfgyddlvaqs--
--vrdektgkirssqfftcpngqcrdfptiaesceaatiqtc-gaspvgk
rvgtrcrsyatqp-tkaapnklldyssgtagmfda--rkcefnnggydev
lglvesnlatipqleggllcsrplrdi--dlastsketdhqglaypvpnl
ldpasrcirptrfhwthldrliftygg-----lllmtkpnga----peit
gkchatyqskcskeldmevygrqapddsycfvslpfykasgctrevhgek
lqpvkskdsysvdyptgestgaeqcdeeaf-aspcgeplkstkkielgdl
lnsgckvwgdiwasseeslyk-ica-pntkvyeskakksyyyaisnyeyd
cilrathvaaaskiaiaiilftgfqvgtvvgy-dwpgvhvretg------
-------gtgmstahlpyalygtangs-----gmkkhrealyfsttk
>node14
adlgvvpktrcledaknlvcpsinqtvghq-neqsavpyykrgyygktpe
ilvkgsthlstyihen--girfsgv---qraqscvvtyfgyddlvaqs--
--vrdektgkirssqfftcpngqcrdfptiaesceaatiqtc-gaspvgk
rvgtrcrsyatqp-tkaapnklldyssgtagmfda--rkcefnnggydev
lglvesnlatipqleggllcsrplrei--dlastsketdhqglaypvpnl
lgpasrcirptrfhwthldrliftygg-----lllmtkpnga----peit
gkchatyqskcskeldmevygrqapddgycfvslpfykasgctrevhgek
lqpvkskdsysvdyptgestgaeqcdeeaf-aspcgeplkstkkielgdl
lnsgckvwgdiwasseeslyk-ica-pntkvyeskakksyyyaisnyeyd
cilrathvaaaskiaisiilftgfqvgtvvgy-dwpgvhvretg------
-------gtgmstahlpyalygtangs-----gmkkhrealyfsttk
>node8
aglgvvpktrclrdaknlacpninqnvghq-gergaapyykrgyygkspe
tlvkgsdhlstyihad--ginfsgv---qraqscvvtyfgfdklvaqa--
--vsdektgkirashfftcpynqcadfptiaesckeatievcagaspvgk
rvktrcqshatqs-tksspgklpdyrsgtagmfdaqgrkcefngsgydev
lglvetnlvtipqleggllcsrpmrgi--dmassnketghqgl--pvpnl
ldpasrctratkfhwahlnrliftygg-----illktkrhgagkstpeit
gkchatyqakcakeldmevygrqapddtfcfv----ykasgctkevwsek
lqpvgakdsysvdypdgest---------f-aspcgeplkstkkieladl
lhsgckvwaeiwtsseeslig-vc------vyesrasksyyyaitsykyd
cilrsphvaadckaala-----------vvgy-kwpgvhprevg------
-------ragmstahlpfawygaangs-----gmkkhreanyfsstd
>node19
adlgvvpktrcledaknlacpsinqtvghq-neqsavpyykrgyygktpe
ilvkgsthlstyihen--girfsgv---qraqscvvtyfgyddlvaqs--
--vrdektgkirssqfftcpngqcrdfptiaesceaatiqtc-gaspvgk
rvgtrcrsyatqp-tkaapnklldyssgtagmfda--rkcefnnggydev
lglvesnlatipqleggllcsrplrdi--dlastsketdhqglaypvpnl
ldpasrcirptrfhwthldrliftygg-----lllmtkpnga----peit
gkchatyqakcskeldmevygrqapddsycfvslpfykasgctrevhgek
lqpvkskdsysvdyptgestgaeqcdeeaf-aspcgeplkstkkielgdl
lnsgckvwgdiwasseeslyk-ica-pntkvyeskakksyyyaisnyeyd
cilrathvaaaskiaiaiilftgfqvgtvvgy-dwpgvhvretg------
-------gtgmstahlpyalygtangs-----gmkkhrealyfsttk
>node7
aglgvvpktrclrdaenlacpninqnvghq-geqgaapyykrgyygksge
tl-----hlstyihad--ginfsgv---qraqscvvtyfgfdkkvaqa--
--vsdektgkirashfftcpynqcadfpkiaesckeatievcagaspvgk
rvktrcqshatqs-tksspgklpdyrvgtagmfdaqgrkcefngsgydev
lglvktnlvtipqleggllcsrpkrgi--dmassnketghqgl--pvpnl
lesasrctratkfhwahlnrliftygg-----illktkrhgagkstpeit
akcqatyqakcakeldmdvygrqapddtfcfv----ykasgctkevwsek
lqpvgakdsysaeypdgdst---------f-aspcgeplkstkkveladl
lhsgckvwkeiwtsseeslig-vc------vydsrasksyyyaitsykyd
cilrsphvaadckaala-----------vvgy-kwpgthprevg------
-------ragmstahlpfawygaangs-----gmkkhreanyfsstd
>ENV_HV2D1/24-501
aslgvvpktkcledaknlvcpsinqtvghq-neqsevpyykrghygktpe
ilvkgstllstyihen--girfsgv---qrahscvvtyfgyndlvaqs--
--frdektgkirssqfftcpngqcrdfptiaesceaatiqtc-gaspvgk
kvgarcrsyatqp-tkaapdklldyssgtagmfda--rncefnnggysev
lglvesnlatipqleggllcsrplrei--dlastsketdhrglaypvpnl
lgpasrcirptrfhwthldrlifsygg-----lllmtkpnga----peit
gkchatyqskcskelemeaygrqapddgycfvslpfykasgctrevhgek
lepvkskdsysvdyptgesigaeqcdedaf-aspcgeplkstkkielgdl
qnsgckvwgdiwaspeeslyk-ica-pntkvyeskakksyyyaisnyeyd
cilrathvaaaskiaisiilftgfqvgtvvgy-dwpgvhvretg------
-------gtgmstqhlpyalygtangs-----gmkkhrealffsttk
>ENV_HV2D2/24-513
adlgvvpktr--qdtknlacgsidatvghq-neqsavpyykrgyygktpe
ilvkgsthlstfihan--girfsgg---vraqpcvvtyfgyddlvaqs--
--vrdekdgkirdsqfftcpngqckdfatvaesceaatiqtcagaspvgk
kvgtrcrsyatqp-tkaapnklldyspgt----da--rkcefngggydev
lglvesglatrpqleggllcsralrni--dlpstskdtdhqgltypvpnl
lspdskcirptkfhwthldrlifpygg-----lllmttpnqa----pevt
gkchatyqakcskeldmevygrqapddsycfvnlpfykasgctrevhgek
lqpvkskdsysldyptgestgaeqcdeeaf-gspcgeplkstkkielgdl
lnsgckvwgdiwasseeslyggica-pntkvyeskakksyyyaisnyeyd
cilrathvaaaskiaipiilftgfqvgtvvgy-dwpgvhvretg------
-------gtgmatahlpyalygnangs-----gmkkhrealyfsttk
>ENV_HV2CA/25-512
adlgvvpktrcledaknlvcqsinqtvghq-neqsavpyykrgyygktpe
llvkgsthlstyihen--girfsgv---qraqscvvtyfgyddlvaqspp
nvvrdektgkirssqffdcpngqcrdfpaiaesceaatiqtc-gaspvgk
rvgtscrsygaqp-tkalpnklldaasgtagmfda--hkcefnnggydev
lglvesnlatipqleggllcsrqlrdi--dlastskgvdhqglaypvp--
ldpasrcirptkfhwthldrliftygg-----lllmtkpnge----peit
gkchaayqskcgkeldmevygrqapddsycfvslpfykasgcsrevdgek
lqpvkakdsysvdyptgestgaeqcdeegf-arpcgeplkstkkielgdl
lnsgckvwgdiwasseeslhk-icavpntkiyeskakksfyyaissyefd
cilrathvaaasrialdiilfvgfqvgtivgy-dwpgvhvrttg------
-------gngmssahlpyalygtangs-----gmkkhrealyfsttk
>ENV_HV2NZ/24-502
adlgvvpktrcledaknlvcqsinqtvghq-neqslvpyykrgyygktpd
ilvkgsthlstyihen--girfssv---qraqscvvtyfgyddlvaqshp
nvvrdektgkirsaqfftcpngqcrdfpaiaesceaatiqtc-gaspagk
rvgtrcrsyatqp-tkaapnklldyasgtagmfda--rkcefnnggydev
lglvesnlatipqleggllcsrplrdi--dlastsketdhqglaypvp--
ldpgscctrptrfhwthldrliftygg-----lllltkpnge----peis
ggchaayqskcskeldmevygrqapedsycfvslpfykasnctkevhgek
lqpvsskdsysvdyptgestgseqcdeeaf-aspcgeplkstkkielgdl
lnsgckvwgdiwasseeslhk-ics-pntkvyeskakkayyyaisnyeyd
cilrakhvaaaskialaiilftgfqvgtvvgy-dwpgvhvrttg------
-------gngmssahlpyalygtangs-----gmkkhrealyfstqk
>ENV_HV2G1/23-502
adlgvvpktrcledakslacpsinqtvghq-neqsavpyykpgyygktpe
ilvkgsthlstyihdd--girfsgv---qraqscvvtyfgyddlvaqs--
--vrdektgkirssqfftcpngqchdfptiaesigaatiqtc-gaspvgk
rmgtrcrsyatqp-skaapnklldyssgtagmfda--rkcefngggydev
lglveanlatipqleg-lfcsrplrdi--elastsketdh----ypvpnl
ldpasrcirptrfhwkhldrliftygg-----lllmtkpnga----pevt
gkchatyqakctkeldmeiygrqapddsycfvslpfykasgctravhgek
lqpvkskdsysvdyptgestgaeqcdeeaf-aspcsnplkstkkielgdl
lnsgckvwgdiwasseeslyk-ica-pntkvyeskakksyyyaisnyeyd
cilwathvaaaskiaiaiilftgfevgtvvgy-dwpgvhvretg------
-------gtgmstahlpyalygtasgs-----gmkkhrealyfsttk
>ENV_SIVG1/22-522
aglgvvpktrclrdaenlacpnidqnvghq-geqgsawyykrgyygksge
tl-----hlstyvhad--ginfsgv---qraqscvvtyfgfdkkvaqa--
--vsdektgkirashfftcpynqcadfpkiaesckvatievcagaspvdk
rvktrcnshatqs-tksspgklpdyrvgtagmfdaqgrkcefngngydev
lglhktnavtipqleggllisrpkr-i--dmassnketghqgl--pvpnl
lescsrctratkfhwahlnrliftygg-----illktkrhgagkstsait
akcqatyaakcakeldmdvygrqapddtfcfv----ykasgctkevwnek
lqpvgakdsysaeypegdst---------f-aspcgeplkstkkveladl
lhsgskvwkeiwssseeslig-vc------vydsrasksyyyaitsykyd
cilrsphvaaeckaala-----------vvgy-kwpgthprevg------
-------ragmstahlpfawygasngn-----gmkkhreanyfsntd
>node10
adlgvvpktrclqdaknlacpsinqtvghq-neqsavpyykrgyygktpe
ilvkgsthlstyihan--girfsgv---qraqscvvtyfgyddlvaqs--
--vrdektgkirssqfftcpngqcrdfptiaesceaatiqtcagaspvgk
rvgtrcrsyatqp-tkaapnklldyssgtagmfda--rkcefngggydev
lglvesnlatipqleggllcsrplrdi--dlastsketdhqglaypvpnl
ldpasrcirptkfhwthldrliftygg-----lllmtkpnga----peit
gkchatyqakcskeldmevygrqapddsycfvslpfykasgctrevhgek
lqpvkskdsysvdyptgestgaeqcdeeaf-aspcgeplkstkkielgdl
lnsgckvwgdiwasseeslyg-ica-pntkvyeskakksyyyaisnyeyd
cilrathvaaaskiaiaiilftgfqvgtvvgy-dwpgvhvretg------
-------gtgmstahlpyalygtangs-----gmkkhrealyfsttk
>node17
adlgvvpktrcledaknlvcqsinqtvghq-neqsavpyykrgyygktpe
ilvkgsthlstyihen--girfsgv---qraqscvvtyfgyddlvaqshp
nvvrdektgkirssqfftcpngqcrdfpaiaesceaatiqtc-gaspvgk
rvgtrcrsyatqp-tkaapnklldyasgtagmfda--rkcefnnggydev
lglvesnlatipqleggllcsrplrdi--dlastsketdhqglaypvp--
ldpasrcirptrfhwthldrliftygg-----lllmtkpnge----peit
gkchaayqskcskeldmevygrqapddsycfvslpfykasgctrevhgek
lqpvkskdsysvdyptgestgaeqcdeeaf-aspcgeplkstkkielgdl
lnsgckvwgdiwasseeslhk-ica-pntkvyeskakksyyyaisnyeyd
cilrathvaaaskialaiilftgfqvgtvvgy-dwpgvhvrttg------
-------gngmssahlpyalygtangs-----gmkkhrealyfsttk
>node9
adlgvvpktrclrdaknlacpsinqnvghq-neqsavpyykrgyygktpe
ilvkgsthlstyihad--girfsgv---qraqscvvtyfgyddlvaqa--
--vrdektgkirssqfftcpngqcrdfptiaesceaatiqtcagaspvgk
rvgtrcrsyatqp-tkaapgklldyssgtagmfda--rkcefngggydev
lglvetnlatipqleggllcsrplrdi--dmasssketdhqglaypvpnl
ldpasrcirptkfhwthldrliftygg-----lllmtkpnga----peit
gkchatyqakcskeldmevygrqapddsfcfvslpfykasgctrevhgek
lqpvkskdsysvdypdgestgaeqcdeeaf-aspcgeplkstkkielgdl
lnsgckvwgdiwasseealyg-ica-pntqvyeskakksyyyaisnyeyd
cilrathvaaaskiaiaiilftgfqvgivvgy-dwpgvhvretg------
-------gtgmstahlpyalygaangs-----gmkkhrealyfsttk
>ENV_HV2BE/24-510
anlgvvpktrcledaknlvcpslnmtvghq-neqsavpyykrgyygktpe
mlvkgsthlstyihen--girfsgv---qraqacvvtyfgyedlvaqs--
--vrdektgkigssqfftcpngqcrdfptiaesceaatiqtc-gaspvgk
rvgsrcrsyatqp-tktapnklldyssgttgmfda--rkcefnhggydev
mglvesnlatipqleggllcsrplrei--dlsstsketdhqglaypvpnl
lgpaspcirptrfhwthldrliftygg-----lllmtkpnga----peit
gkchatyqskcskeldmevygrqapddgfcfvsipfykasgctrevhgek
lqpvkskdsysldypsgestgaeqcdeeaf-aspcgeplkstkkielgdl
lnsgckvwgsiwasseeslyk-ica-pdtkvyeskakksywyaisgyeyd
cilrathvaaatkiaisiilftgfqvgtvvgy-dwpgvhvretg------
-------gtgmstahlpyalygtangs-----gmrkhrealyfsttk
>node11
adlgvvpktrcledaknlacpsinqtvghq-neqsavpyykrgyygktpe
ilvkgsthlstyihen--girfsgv---qraqscvvtyfgyddlvaqs--
--vrdektgkirssqfftcpngqcrdfptiaesceaatiqtc-gaspvgk
rvgtrcrsyatqp-tkaapnklldyssgtagmfda--rkcefngggydev
lglvesnlatipqleggllcsrplrdi--dlastsketdhqglaypvpnl
ldpasrcirptrfhwthldrliftygg-----lllmtkpnga----peit
gkchatyqakcskeldmevygrqapddsycfvslpfykasgctrevhgek
lqpvkskdsysvdyptgestgaeqcdeeaf-aspcgeplkstkkielgdl
lnsgckvwgdiwasseeslyk-ica-pntkvyeskakksyyyaisnyeyd
cilrathvaaaskiaiaiilftgfqvgtvvgy-dwpgvhvretg------
-------gtgmstahlpyalygtangs-----gmkkhrealyfsttk
>ENV_SIVM1/24-528
adlgvvpktrclrdgdnlacpsinpnvghq-neqsavpyykrgyygktpd
ilvkgsthlstyihad--girfsgv---qr--scvvtyfgyddlvaqa--
--vrdektgkirssqfftcpngqcrdfptiatsceattiqtcagaspvgk
rvgtrcrsyatqp-tkaapgklldyssgtagmfda--rtcefngggydei
lglvetnlatipqleggllcsrplrdiqddmanssketthqglaypvpnl
lepasrcirptkfhwthldrliitygg-----lllmtkpnga----pett
gkchatyqakcskelnmevygkqapqdafcfvslpfykasgctrevhgek
lqpvkskdsysvdypdgestgaeqcdeeaf-aspcgeplkstkkielgdl
ltsgckvwgdiwasseealyg-ica-pntqvyeskpkksfyyaiswyeyd
cilrathvaaaskiaiaiilftgfqvglvvgy-dwpgvhvretg------
-------gtgmstahlpyalygaangs-----gmkkhrealyfsttk
>ENV_SIVGB/47-569
sglgvqpdtralrdaknlacaninqnighvsearg---yfkrsyygkppq
tlvlgsnhlseythad--ginfagvqrakkaqacavsyfgfndlasaa--
--isdektgkiqashlf--pynqcadfssiaqsckeatievcagalhvns
rvksqc--hctqgslkstrgklpsy--gtagmfdsegrkcefngsgydnv
mglvqnnlgtvpqleggll--rplrgv--dmacwnketgnqgl--pvpnl
ldpvsrctqftkfhwsplnrlaytyggelyls----kkrhgtgksgpait
akshapynskcakdldkeiygriaadstycfg----ykvsdcaketwsek
fqpvgakdsygvdytdvest---------ftaspcgeplkstkkvdmsdl
lnsgvkgwkeiwssseqdlig-vc------vy-----dsyyyaihaykyd
cilasphvaa--ksala-----------iigf-kwplvlprdigklfagv
lkvmfvfrasmngahlpfslygaangt-----sqkrhreldyfssrd
