>node19
kpdeg-------frkeeaayaekqc-iqphlakgkratekavvlgvykak
kvghtkqvgqlrpa-----vgtdvlpgkpganhvatrgqengakcssan-
---knpdvlgswelsglelfylggrp------dgagraakktgnrsytva
tlspqqs--ely--ggflsvaegvysqaqgmlaadgenknvtdnvfeeyk
kkg-gqed--v--qylpqahv---nia----nhg--eqgthe-kqqsvdp
rgpeicelnrtqlaslgkmkgpnteyfhisrelpfpylergnppdqdstg
vvelacclqtgachvgklhqknklcpsaktvimgitevcahngkhvrpps
ktahvqkfvfagnpdvrnhq-lgiamlsekltravkgtedgpahalypgl
taepkpritggklfcanltsacmnessvfelclkkyakc--aeihaakle
ayhpfelsdhglwmggvhtdiktv---ekgsfkltcihagrqldkfrdcf
teipdnksrsgtgtpkrelghaaqlkplnagtqemdfvetdklveils
>node14
kpdeg-------frkeeaayaekqc-iqphlakgkratekavvlgvykak
kvghtkqvgelrpa-----vgtdvlpgkpganhvatrgqengakcssan-
---knpdvlgnwelsglelfylggra------dgagraakktgnrsytva
tlspqqs--ely--ggflsvaegvysqaqgmlaadgenknvtdnvfeeyk
kkg-gqed--v--qylpqahv---nia----nhg--eqgthe-kqqsvdp
rgpeicelnrtqlaslgkmkgpnteyfhisrelpfpylergnppdqdstg
vvelacclqtgachvgklhqknklcpsaktvimgitevcahngkhvrpps
ktahvqkfvfagnpdvrnhq-lgiamlsekltravkgtedgpahalypgl
taepkpritggklfcanltsacmnessvfelclkkyakc--adihaakle
ayhpfelsdhglwmggihtdiktv---ekgsfkltcihagrqldkfrdcf
teipdnksrsetgtpkrelghaaqlkplnggtqemdfvetdklveils
>ENV_HV2NZ/24-502
kpdeg-------frkeeaayvakqc-iqphlakgkratekavvlgvykak
kvghtkqvgqlspa-----vgtdvlpgkpganhvatrgqdnsakcssan-
---knadvlgswelsglelfylggrp------egggravkmtgnrsytva
tlspqqs--ely--ggflsvaegvysqaqgmvaadgenknvtdsvfeeyt
kkg-gqed--v--qylpqahvsesnia----khg--eqglhe-kqqsvdt
rgpeicelnrtqlaslgktkgpeteyfhisrelpfpylergnppdqdrtg
vvelacclqtgachvgkvhqknklcpsaktvimgitevcahngkvvrpps
kiahvekfvfagnpdvrnhq-lgiamlsekltravketedgpphalypgl
taepkprltggklfcanltsacmnetsvfelclkkytkc--adihaakle
ayhpfelsdhalwmggvhtdiktv---ergsfkltcihagrqldkfrdcf
teipdnksrsgtgtpkrqlghaaqlkplnagtqemdfvetdklveils
>ENV_SIVV1/24-538
kpdeg-------fnkesgaypekqc-iqphvakskranekadvlaiykdr
kvg------qlhps-----vgtdvlpgkagd---------------sas-
---kspdllgsweqsglhlfyiggra------ngfgrpakktgnrdytaa
tlgpqesrk-ty--ggfvsgangvysqtqvilaadqesenqsdnlfdeyk
kkp-gtea-si--qylpqahv---kitpveckhq--esgthd-kkqsvnp
kgpdtseldqtqlgalgkvkgasteyfhispdlsfpylergeppdqdaag
vveidtcsrtgacyvgklhhknklcsspkksimgiadlcahda-----ps
ksanvqkfvflak--vrsrqgigiqmasekltr----aqdgtahelvp--
taepkpmitggklfcaklasacvskesifefclkkyakc--aedhgakle
eyqplelsdpglwragvhtdikav---gkgsckltcphsgrqmekfrdff
tgvpdnksrsgigtpkkelpqtaminplglntqe---nevnklgei-i
>ENV_HV2CA/25-512
kpdeg-------frkeekafedkqc-iqphlakgkratekavvlgvykak
kvghtkqvgqlrpa-----vgtdvlpgkpgsnhvatrgqengakcssan-
---knadvlgsweltglelfylggrp------dgggraakktgdrsytva
tlspqqs--ely--ggflsvaegvyslaqgmlaadgtnknvtdsvfeeyk
kkg-gqed--v--qylpqahv---nia----nhgedeqgthe-kqqsvdp
rgpeicelnrtqlaslgkmkgpdtdyfhisrelpfpylergnppdqdstg
vvilacclekgachvgklhqknklcpsaktvimgitevcahngkvvrpps
ktahvqkfvfaghpdv------------ekltravkgtedgpahgllvgl
taepkprltggklfcanltsacmnespvfelclkkyarc--adihaakle
ayhpfelsehgfwmggahtdiktv---ekgsfkltcihagrqldkfrdcf
teipdnksrsgagppkrelghaaqlkplnagtqemefvetdklveils
>ENV_HV2BE/24-510
kpdeg-------frkeeaayaekqc-iqphlakgkratekavvlgvykak
kvghtkqvgelrpa-----vatdvlpgkgganhvatrgqengakcssan-
---kspdvlgnwelsglelfyltgra------dgagraakktgnrsksvs
tlspqqs--ely--ggflsvtegvysqahgmlaadgenknvtdnvldevk
kkg-gqed--v--qylpqshv---nia----nhg--eqgthe-kqqsvqp
rgpeicelartqlaslgkmkgpnteyfhisrelpfpylergnppdqdstg
vvelacclqtgachvgklhqknklcpsaktvimgitevcahngkhvrpps
ktahvqkfvfagnpdvrnhq-lgiamlsekltravkgtedgpahalypgi
ttepkpritggklfvanltdacmnessvfelclkkyakc--adihaakle
fyhpfelsdhglwmggihtdiktvnltekgsfkltcihagrqldkfrdcf
teipdnksrsetgtpkrelghaaqlkplnggtqemdfvetdklveils
>ENV_SIVGB/47-569
lpeeg-------fnkdeanypeksceiqpllakskrtnvradvlgiykar
kvg------elklspsyvavgsdplmvepgd---------------srnv
rdtkrgdllgswedkgiqlfysggka------nafgnpagkpenraytsa
tlgprksskplydfggfiggasgvnsqaegmlaadqesrnqndnmfdvyk
kkv-gted-pvvlrylpqahi---k------shg--eegtfekkgqgvia
kglntceldrtqlatlgkstdgnteyyhvhrdlafpynqrgqppdqdseg
vvrlaacshagkcqvgslhrknklcdspkkvimgihelcnhfl-----pa
ktanvekfvfaal--gsare-vgikmlsekltr----aedgqahelvp--
veehkpkikgaklfcskltsaclgndsvfepclkkyakcggadn-ggnle
ayrpfeqsdpglwrdgiitdlrsv---gkglvkltcinsgqqlekfrdcf
taiagnksrsgigtpkgelpqtallkpl--ntqdfnfaeieklveisi
>ENV_SIVG1/22-522
rpdeg-------fkkeeaaypekqc-iqrhlakskranekadvlgiykdr
kvg------qlhps-----vgtdvlpgkpgd---------------ssk-
---knpdllgsweqsglqlfyiggradksrykngfgrpakktgnrsytta
algpqedrkaly--ggfisgangvysqtqgmlaadqesknqsdglfdeyk
kkg-gtes-sv--qylpqahv---kit----nhq--eqgthd-keqsvnp
kgpdtseldrptlgalgkvknpsteyfhispdlafpylergqpldqdatg
vveiatcsatgacyggklhqknklcsspkkaimgiaelcahna-----ps
ktanaqkfvflak--vrsrq-igiqmlsekltr----eedgtahqlvp--
taepkpritggklfcaklasacvskesifelclkkyakc--aenhggkld
afqpfelsepglwragvhtdiktv---gkgscmltcihsgrqmekfrdcf
tgipdnksrsgigtpkrelpqtaqlkplglntqefdfaevdrlgevsi
>node17
kpdeg-------frkeeaayaekqc-iqphlakgkratekavvlgvykak
kvghtkqvgqlrpa-----vgtdvlpgkpganhvatrgqengakcssan-
---knadvlgswelsglelfylggrp------dgggraakktgnrsytva
tlspqqs--ely--ggflsvaegvysqaqgmlaadgenknvtdsvfeeyk
kkg-gqed--v--qylpqahv---nia----nhg--eqgthe-kqqsvdp
rgpeicelnrtqlaslgkmkgpdteyfhisrelpfpylergnppdqdstg
vvelacclqtgachvgklhqknklcpsaktvimgitevcahngkvvrpps
ktahvqkfvfagnpdvrnhq-lgiamlsekltravkgtedgpahalypgl
taepkprltggklfcanltsacmnessvfelclkkyakc--adihaakle
ayhpfelsdhglwmggvhtdiktv---ekgsfkltcihagrqldkfrdcf
teipdnksrsgtgtpkrelghaaqlkplnagtqemdfvetdklveils
>node10
kpdeg-------frkeeaayaekqc-iqphlakgkratekavvlgvykak
kvghtkqvgqlrpa-----vgtdvlpgkpgd---------------san-
---knpdvlgswelsglelfylggrp------ngagraakktgnrsytva
tlspqqsrkely--ggflsvaegvysqaqgmlaadnenknvtdnvfeeyk
kkg-gted--v--qylpqahv---nia----nhg--eqgthe-kqqsvdp
rgpeicelnrtqlaalgkmkgpnteyfhisrelpfpylergnppdqdstg
vvelacclqtgachvgklhqknklcpsaktvimgitevcahngkhvrpps
ktahvqkfvfagnpdvrnhq-lgiamlsekltravkgtedgpahalypgl
taepkpritggklfcanltsacmnessvfelclkkyakc--aeihaakle
ayhpfelsdhglwmggvhtdiktv---ekgsfkltcihagrqldkfrdcf
teipdnksrsgtgtpkrelghaaqlkplnlgtqemdftetdklveils
>ENV_HV2D1/24-501
kpdeg-------frkeeaayaekqc-tqphlakgkratekavvlgvykak
gvghtkqvgelhpa-----vgtnvlpgkpganhvatrgqengakcssan-
---knpdvlgnwelsglelfflggra------dgaghaakktgnrsftva
tlspqqs--ely--ggfvsvaegvysqaqgmlaadgenknvtdnvfeeyk
kkgvgqedv-v--qylpqahv---sss----nhg--eqgthe-kqqsvdp
rgpeicelnrtqlaslgkmkgpnteyfqisrelpfpylergnppdqdstg
vvelacciqtga-hvgklhqknklcpsaktvimgktevcahngkhvrpps
ktahvqkfgfagnpdvrnhq-lgiamlsekltravkgtedgpahalypgl
taepkpritggklfcanltsacmnesnvfelclkkyakc--adihaakle
ayhpfelsdhglwmggihtdiktv---ekgsfkltcihagkqldkfrdcf
teipdnksrsetgtpnrelghaaqlkplnggtqemdfvetdklveils
>node7
kpdeg-------fkkeeaaypekqc-iqphlakskranekadvlgiykdr
kvg------qlhps-----vgtdvlpgkpgd---------------ssn-
---knpdllgsweqsglqlfyiggra------ngfgrpakktgnrsytta
tlgpqesrkaly--ggfisgangvysqtqgmlaadqesknqsdnlfdeyk
kkg-gtes-sv--qylpqahv---kit----nhq--eqgthd-keqsvnp
kgpdtseldrtqlgalgkvkgasteyfhispdlsfpylergqppdqdatg
vveiascsqtgacyvgklhqknklcsspkkaimgiadlcahna-----ps
ktanvqkfvflak--vrsrq-igiqmlsekltr----aedgtphqlvp--
taepkpritggklfcaklasacvskesifelclkkyakc--aenhgakle
ayqpfelsdpglwragvhtdiktv---gkgsckltcihsgrqmekfrdcf
tgipdnksrsgigtpkrelpqtaqlkplglntqefdfaevdklgevsi
>node8
kpdeg-------fkkeeaaypekqc-iqphlakskranekadvlgiykar
kvg------qlhps-----vgtdvlpgkpgd---------------ssn-
---knpdllgsweqsglqlfyiggra------ngfgrpakktgnrsytta
tlgpqesrkaly--ggfisgangvysqtqgmlaadqesknqtdnlfdeyk
kkg-gtes-sv--qylpqahv---kit----nhg--eqgthd-keqsvnp
kgpdtceldrtqlaalgkvkganteyfhisrdlsfpylergqppdqdstg
vveiascsqtgachvgklhqknklcssakkvimgiadlcahna-----ps
ktanvqkfvfaak--vrsrq-igiqmlsekltr----aedgtahalvp--
taepkpritggklfcakltsacvgkesvfelclkkyakc--aenhgakle
ayqpfelsdpglwrggvhtdiktv---gkgsikltcihsgrqlekfrdcf
tgipdnksrsgigtpkrelghtaqlkplglntqefdfaevdklveisi
>node11
kpdeg-------frkeeaayaekqc-iqphlakgkratekavvlgvykak
kvghtkqvgqlrpa-----vgtdvlpgkpga---------------san-
---knpdvlgswelsglelfylggrp------dgagraakktgnrsytva
tlspqqs--ely--ggflsvaegvysqaqgmlaadnenknvtdnvfeeyk
kkg-gqed--v--qylpqahv---nia----nhg--eqgthe-kqqsvdp
rgpeicelnrtqlaalgkmkgpnteyfhisrelpfpylergnppdqdstg
vvelacclqtgachvgklhqknklcpsaktvimgitevcahngkhvrpps
ktahvqkfvfagnpdvrnhq-lgiamlsekltravkgtedgpahalypgl
taepkpritggklfcanltsacmnessvfelclkkyakc--aeihaakle
ayhpfelsdhglwmggvhtdiktv---ekgsfkltcihagrqldkfrdcf
teipdnksrsgtgtpkrelghaaqlkplnagtqemdfvetdklveils
>ENV_HV2G1/23-502
kpdeg-------frkeeaayaekqc-iqphlakgkratekavvlgvykak
kvghtkqvgqlrpa-----vgtdvlpgkpga---------------san-
---knpdvlgswelsglelfylggrp------dgagraakktgnrsytva
tlspqqs--ely--ggflsvpegvysqaqgmlaadnenknvtdnvfeeyk
kkg-gqed--v--qylpqahv---nia----nhg--eqgthe-kqqsvdp
rapevcelnrtqlaalgkmkgpnteyfhisrelpfpylergnppdqdstg
vveldcclqtgvchvgklhqknklcpsakyvimgitevcnhngkhvrpps
ktahvqkfvfagkpdvrnhq-lgiamlsekltravkgtedgpahalypgl
taepkpritggklfcanltsacmnessvfelclkkyakc--aeihaakle
afhpfeltdhglwmggvhtdiktv---ekgsfkltcihagrqldkfr---
-eipnnksrsgtgtpkrelghaaqlkplnagtqemdfvetnklveils
>ENV_SIVM1/24-528
kpdeg-------frkeeaayaeqqc-iqphlvkgkranekavllgvykak
kvghtkqvtqlrla-----vgsdilpgkpgd---------------ssn-
---knpdvlgswelsglelfylggrp------ngagraakktgnrsytva
tlspqesrktly--ggfvgvaegvysqaqgmlaadnenknvtdnvfeeyk
kkg-gtee--v--qylpqahv---gis----nhg--eqgthd-kqqsvdp
rgsqicelnrtqlgalgkmkgpnteyfhisrdlpfpylergnppdqdstg
vveiaccl-------gklhqknklcpsaktvimgitelcahnakhvraps
ktahvqkfvftgnpdvrnhq-lgiaklsekltravkgtedgpahalypgl
taepkpritggklfcanltsacmnkesvfelclkdyakc--aeihgaklq
ayhpfelsdhglwmggvhtdiktv---ekgsfkltcihagrqldkfrdcf
teipdnksrsgtgtpkrelghamqlkplslgtqemdftetdklvdiss
>ENV_HV2D2/24-513
kpdegsatmfahfrkeyaayaekqg-iqphlaegkratekavvlgvykak
kvghtkqvgqlraa-----v-sdvlpgkage---------------sgn-
---knpdvlgswelsglelfylggrp------agagraakktgkrsytva
slspqqsrkely--ggflsvaegvysqaqgmlaadnenknvtdnvfeeyk
kkg-gted--v--qylpqahv---nia----nhg--eqgtre-kqqsidp
rgpeicelnktqlpalgkmkgpnteyyhisrqlpfpylergnppdqdstg
vvelacclqtgacfvgklhqknklcpsiktvimgitevcahsgkhvrpps
ktahvqkfifagnpdvrnhq-lgiamlsekltkavkgtedaaaqalypgl
taepkpritggklfcanltsacmnessvfelclkkyakc--aeihaakle
ayhpfelsdhglwmggvhtdiktv---ekgsfkltcihagrqldkfrdcf
teipgnkspsgtgtpkrelghaaqlkplnlgtqemdftesdklveils
>node9
kpdeg-------frkeeaayaekqc-iqphlakgkranekavvlgvykak
kvghtkqvgqlrpa-----vgtdvlpgkpgd---------------ssn-
---knpdvlgswelsglelfylggrp------ngagraakktgnrsytva
tlspqesrkely--ggfvsvaegvysqaqgmlaadnenknvtdnvfeeyk
kkg-gted--v--qylpqahv---nis----nhg--eqgthd-kqqsvdp
rgpqicelnrtqlaalgkmkgpnteyfhisrdlpfpylergnppdqdstg
vveiacclqtgachvgklhqknklcpsaktvimgitelcahnakhvrpps
ktahvqkfvfagnpdvrnhq-lgiamlsekltravkgtedgpahalypgl
taepkpritggklfcanltsacmnkesvfelclkkyakc--aeihgakle
ayhpfelsdhglwmggvhtdiktv---ekgsfkltcihagrqldkfrdcf
teipdnksrsgtgtpkrelghaaqlkplnlgtqemdftetdklveiss
>node18
kpdeg-------frkeeaayaekqc-iqphlakgkratekavvlgvykak
kvghtkqvgqlrpa-----vgtdvlpgkpganhvatrgqengakcssan-
---knpdvlgswelsglelfylggrp------dgagraakktgnrsytva
tlspqqs--ely--ggflsvaegvysqaqgmlaadgenknvtdnvfeeyk
kkg-gqed--v--qylpqahv---nia----nhg--eqgthe-kqqsvdp
rgpeicelnrtqlaslgkmkgpnteyfhisrelpfpylergnppdqdstg
vvelacclqtgachvgklhqknklcpsaktvimgitevcahngkhvrpps
ktahvqkfvfagnpdvrnhq-lgiamlsekltravkgtedgpahalypgl
taepkpritggklfcanltsacmnessvfelclkkyakc--adihaakle
ayhpfelsdhglwmggvhtdiktv---ekgsfkltcihagrqldkfrdcf
teipdnksrsgtgtpkrelghaaqlkplnagtqemdfvetdklveils
