>ENV_SIVV1/24-538
---akgclktt---nmllklilstppvsaaydmvtgygttmalvyksvkg
lqfclpdgellyv-----hswydeanspaldplsrgcep-pntvgeelfk
pdtnvlrsvlftaslalccnaaq---vplvvpfhatqfarlcvnlltnis
ignygclgsglvnyaianatnvnkakayiacnvngnlrg---ktiqfpac
fkgtdyegtalnltqvgyklqit-----pfvvtrvrfqhragkrefghvq
qlgkfnlaiheligtsskalghpqdficaqcpmflsrgdarpiygsalfg
qkkqaslkyymlkyldlhqsysylgklcgtrelg---rtleaihagssta
sfnfaagqltlfnfsakgn--epvmcftpcntepa-gstclrkggkkrvp
arpsfaiagglrttldptsspyrraeildalacsskdsklll-agylyew
tryrhlthgmsamdehlrtdgsgliqstaagyptespkvcrdlaetanfy
ygtfhkaniwp-livtlahchr----------ptweflafkgqqaarksv
ealansg
>ENV_SIVM1/24-528
---akgc--ttflwkmllsl----ltlvnaygmiagygttmalvykavka
lqfcltdgdlly-qlaawhtwfd---shafeslnrncaplvdtlgeelfk
petdvlvrvvfasslalccnldqatlvslivpfhktqflkqcv-lltnis
vgnygcldsgiqnyniagpayvdklkayiacnvdgnlrg---ktvqfkac
fksldykgtvldldevgykhqva-----pftmtqfrfqhkagsrlfgq--
tlgafnyaihsllgtttkelgepqdlvcaqcpmflsvknanpiygssl--
-kkpaslkhymltylnlhqtysyngklcgtrdlg---rtleaihs-----
-----akkl-mfnfsakgn--epvmcfvachtepp-gts----ggkrrve
srlaftvagmlrtvltpdsspyrrsevldalacslkdsklll-enylyew
tryrqlahgksatddhlvtndsgliqstaag-ps--pkvvreygatgnfy
fgtfhkaniwp-livklahchr----------ssweylqfkglqaarksv
eelagag
>ENV_HV2BE/24-510
smqakgc--ttflwkmlhsi----ltvvnaygfiagygntmgvtykavkg
lqkcltdgdlly-qlaswhtwfd---spafeslgrncaelvdtlgeelfr
petdvlvrviftstlalccnldqa-lvslvvpfhktqflklcv-lltnis
vgnygcldsgvigysiaglayvdklkqyiacnvdgklrg---ktvqfnac
fkglqykgtalnldqvgykhqva-----pyvmtqfrfqhkagsrlfgqvq
tlgdfsyaihallsttskelgdpqdlvcaqchvflkvrdarpiygssl--
-kkpaslkyymltyldlhqtysyigklcgtrdlgdtqrtleaihs-----
-----akkl-mfnfsakan--eivlcftachtept-gss----ggkkrae
srpsfsiagmlhatltpdaspyrktevldalaclpkdsklll-gnflyew
tryrqlshgnagtddhlpnnnggliqstaag-psaapkvvreygetgnfy
fgtfhkaniwp-livklavchr----------ssweylqfkglqaarksv
nelagag
>node10
---akgc--ttflwkmllsi----ltvvnaygmiagygttmalvykavkg
lqfcltdgdlly-qlaawhtwfd---spafeslnrncaplvdtlgeelfk
petdvlvrvvftstlalccnldqa-lvslivpfhktqflklcv-lltnis
vgnygcldsgvqnysiagpayvdklkayiacnvdgnlrg---ktvqfnac
fkgldykgtalnldevgykhqva-----pfamtqfrfqhkagsrlfgqvq
tlgdfnyaihsllgttskelgdpqdlvcaqcplflsvrdarpiygssl--
-kkpaslkyymltyldlhqtysylgklcgtrdlgdtqrtleaihs-----
-----akkl-mfnfsakan--eavmcftachtepp-gts----ggkkrvq
srpafsvagmlhatltpdsspyrkaevldalacapkdsklll-enflyew
tryrqlshgkaatddhlvtndsgliqstaag-psdapkvvreygetgnfy
fgtfhkaniwp-livklahchr----------ssweylqfkglqaarksv
pelagag
>ENV_SIVG1/22-522
---akgclkta---nmllkl----lpvcaaygmvagygttlalvykavkg
lqfclsdgellyv-----hswydeanspaldplnrgcaplpdtdgeelfk
pdtdvlssvlftsslalcc--aq---vpllipfhgtqflrlcinlltnis
ignygclgsgvqnygiagatnvnkakayiacnvngnlrg---ktiqfpac
fkgldysgtalnltevgyklqip-----pfvvtrvrfqhragsrefghvs
qlgkfnlaiheligttskelghpqdfvcaqcpm-lsrrdarpiygsalfs
qkkpgslkyymltyldlhqtysylgklcgtrnlg---rtleaihsgssta
sfsfaaadltlfnfsakgn--epvmcftpcnteap-gttclrkggkkrvp
arpsfsiagglrttlsptsspyrraeildalacsskdsklll-agylyew
tryrhlshgmsamdkhlrtngsglihgtaag-ptdspkvirdlgetanfy
fgtfhkaniwp-livklahcqr----------atweflafkgqqagretv
ealanag
>node17
---akgc--ttflwkmllsi----ltvvnaygmiagygttmaltykavkg
lqfcltdgdlly-qlaawhtwfd---spafeslgrncaplvdtlgeelfk
petdvivrvvftstlalccnldqa-lvslvvpfhktqflklcv-lltnis
vgnygcldsgvqnysiagpayvdklkayiackvdgnlrgevsktvqfnac
fkgldykgtalnldevgykhqva-----pfvmtqfrfqhkagsrlfgqvq
tlgdfnyaihsflgttskelgdpqdlvcaqchlflsvrdarpiygssl--
-kkpaslkyymltyldlhqtysylgklcgtrdlgdtqrtleaihs-----
-----akkl-mfnfsakan--evvlcftachteps-gts----ggkkrvq
grpafsiagmlhatltpesspyrkaevldalaclpkdsklll-gnflyew
tryrqlshgkagtddhlvnndsgliqstaag-psaapkvvreygetgnfy
fgafhkaniwp-livklahchr----------ssweylqfkglqaarksv
pelaggg
>ENV_HV2D2/24-513
---akgc--ttflwkmllsi----ltvvkaygmiagygttmalvykavkg
lqfcltdgelly-qlaawhtwfd---spafeslnrncaplvdslgeelfk
pepdvlvrvvftstlalccnldqa-lvslivpfhktqflklcv-lltnis
vgnygclddgvqnysiagpayvdklkayiacnvdgnlrg---ktvqfnas
fkgldyegtalnldevgykhqva-----pfamtqfrfqhkaasrlfgqvq
tlgdfnyaihsllgttskelgdpqdlvcaqcplflnvrdarpiygssl--
-kkpaslkyymltyldlhqtynylgklcgtrdlldtqrtleaivs-----
-----akkl-mlnfsakan--eavmcftgchtepp-gtg----ngkkrvq
srpafsvagmlhatlppdsspyrkaevldalacppknsklll-enflykw
tryrqlnhgkagtdghlvtndsgliqstaag-psdapkvrreygetgnfy
fgtfhkandwp-livklahchr----------ssweylqikglqaarksv
pelagan
>node9
---akgc--ttflwkmllsl----ltvvnaygmiagygttmalvykavkg
lqfcltdgdlly-qlaawhtwfd---spafeslnrncaplvdtlgeelfk
petdvlvrvvftsslalccnldqa-lvslivpfhktqflklcv-lltnis
vgnygcldsgvqnysiagpayvdklkayiacnvdgnlrg---ktvqfkac
fkgldykgtalnldevgykhqia-----pfamtqfrfqhkagsrlfgqvq
tlgnfnyaihsllgttskelgepqdlvcaqcpmflsvrdarpiygssl--
-kkpaslkyymltyldlhqtysylgklcgtrdlg---rtleaihs-----
-----akkl-mfnfsakgn--epvmcftachtepp-gts----ggkkrvq
srpafsvagmlrttltpdsspyrraevldalacspkesklll-enylyew
tryrqlshgksatddhlvtndsgliqstaag-psdapkvvreygetgnfy
fgtfhkaniwp-livklahchr----------ssweylqfkglqaarksv
eelagag
>node7
---akgclkta---nmllkl----lpvcaaygmvagygttmalvykavkg
lqfclsdgellyv-----hswydeanspaldplnrgcaplpdtvgeelfk
pdtdvlssvlftsslalccnvaq---vpllvpfhgtqflrlcvnlltnis
ignygclgsgvqnygiagatnvnkakayiacnvngnlrg---ktiqfpac
fkgldyegtalnltevgyklqip-----pfvvtrirfqhragsrefghvq
qlgkfnlaiheligttskelghpqdfvcaqcpmflsrrdarpiygsalfs
qkkpaslkyymltyldlhqsysylgklcgtrdlg---rtleaihsgssta
sfsfaasqltlfnfsakgn--epvmcftpcntepp-gttclrkggkkrvp
arpsfsiagglrttltptsspyrraeildalacsskdsklll-agylyew
tryrhlshgmsamdehlrtngsgliqstaag-ptdspkvirdlgetanfy
fgtfhkaniwp-livklahchr----------atweflafkgqqaarktv
ealanag
>node19
---akgc--ttflwkmllsi----ltvvnaygmiagygttmaltykavkg
lqfcltdgdlly-qlaawhtwfd---spafeslgrncaplvdtlgeelfk
petdvlvrvvftstlalccnldqa-lvslvvpfhktqflklcv-lltnis
vgnygcldsgvqnysiagpayvdklkayiacnvdgnlrg---ktvqfnac
fkgldykgtalnldevgykhqva-----pfvmtqfrfqhkagsrlfgqvq
tlgdfnyaihsllgttskelgdpqdlvcaqchlflsvrdarpiygssl--
-kkpaslkyymltyldlhqtysylgklcgtrdlgdtqrtleaihs-----
-----akkl-mfnfsakan--eivlcftachtepp-gts----ggkkrvq
srpafsiagmlhatltpdsspyrkaevldalaclpkdsklll-gnflyew
tryrqlshgkagtddhlvnndsgliqstaag-psaapkvvreygetgnfy
fgtfhkaniwp-livklahchr----------ssweylqfkglqaarksv
pelagag
>node11
---akgc--ttflwkmllsi----ltvvnaygmiagygttmaltykavkg
lqfcltdgdlly-qlaawhtwfd---spafeslnrncaplvdtlgeelfk
petdvlvrvvftstlalccnldqa-lvslvvpfhktqflklcv-lltnis
vgnygcldsgvqnysiagpayvdklkayiacnvdgnlrg---ktvqfnac
fkgldykgtalnldevgykhqva-----pfvmtqfrfqhkagsrlfgqvq
tlgdfnyaihsllgttskelgdpqdlvcaqchlflsvrdarpiygssl--
-kkpaslkyymltyldlhqtysylgklcgtrdlgdtqrtleaihs-----
-----akkl-mfnfsakan--eivlcftachtepp-gts----ggkkrvq
srpafsiagmlhatltpdsspyrkaevldalaclpkdsklll-enflyew
tryrqlshgkagtddhlvnndsgliqstaag-psaapkvvreygetgnfy
fgtfhkaniwp-livklahchr----------ssweylqfkglqaarksv
pelagag
>node18
---akgc--ttflwkmllsi----ltvvnaygmiagygttmaltykavkg
lqfcltdgdlly-qlaawhtwfd---spafeslgrncaplvdtlgeelfk
petdvlvrvvftstlalccnldqa-lvslvvpfhktqflklcv-lltnis
vgnygcldsgvqnysiagpayvdklkayiacnvdgnlrg---ktvqfnac
fkgldykgtalnldevgykhqva-----pfvmtqfrfqhkagsrlfgqvq
tlgdfnyaihsllgttskelgdpqdlvcaqchlflsvrdarpiygssl--
-kkpaslkyymltyldlhqtysylgklcgtrdlgdtqrtleaihs-----
-----akkl-mfnfsakan--eivlcftachteps-gts----ggkkrvq
srpafsiagmlhatltpdsspyrkaevldalaclpkdsklll-gnflyew
tryrqlshgkagtddhlvnndsgliqstaag-psaapkvvreygetgnfy
fgtfhkaniwp-livklahchr----------ssweylqfkglqaarksv
pelagag
>ENV_HV2D1/24-501
---akgc--ttflwkmllsv----ltvvnaygfiagygttmpltykavkg
lqycltdgdwly-qlaawhtwfd---spafeslgrncaplvdtlgee--k
petdvlvrvvftstlalccnldqa-lvslvvpfhktqflklcv-lltnis
vgnygcldsgvqnysiagpayvdklkayiacnvdgnlrg---ktvqfsac
fkgldykgtalnldevgykhqva-----pfvmtqfrfqhkagsrlfgqvq
tlgdfnyvihsllsttskelgepqdlvcaqchlflkvrdarpiygssl--
-kkpaslkyymltyldlhqtysylgklcgtrdledtqrtleaihs-----
-----akkl-mfnfsakan--eivlcftachteps-gts----ggkkrae
srpafsiagmlhatltpesspyrkaevldalaclpkdsklll-gnflyew
tryrqlshgkagtddhlvnndpg-iqstaag-psaapkvvreygetgnfy
fgtyhkaniwp-livklavchr----------ssweylqfkglqaarksv
pelagag
>ENV_HV2G1/23-502
---akgc--ttflwkmllsi----ltvvnaygmnagygttmaltykavkg
rqfcltdgdlly-qlaawhtwfd---spafeslnrncaplvdtlgeelfk
pntdvlvqvvftstlalccnldqa-lvslvvpfhr-qflkfcv-lltnis
vgnygcldsgvqnysiagaayvdklkayiacnvdgnlrg---ktvqfnac
fkgldykgtalnldevgykhqva-----sfvmtqfrfqhkagsrlfgqvq
tlgdfnyaihcllgttskelgdpqdlvcaqchlflsvrdarpiygssl--
-kkpaslkyymltyldlhqtygylgklcgtrdlgdtqrtleaihs-----
-----akkl-mfnfsakan--eivlcftachteppggts----ggkkrvq
srpafsiasllhatltpdsspyrkaevldalaclprdsklll-enflyew
tryrqlshgkagtddhlvnndsgliqstaag-psaapkvvreygetgnfy
fgtf---diwp-livklshchr----------ssweylqfkglqaarksv
pelagag
>ENV_SIVGB/47-569
---akgc--ttflwamiasl----lpvcaaygmsagfgatmalvykevgg
lqfcvddgdliyv-----hswydeanrpnfhp----caplpgstgeelfr
pdtdvlssvlfnsslalccnvpq---vcllvpfhqtqlskfcinlltnit
vkhygrllsgtgnyscagshnvnkakayiacnvngnlrg---ktvtfpec
fkggnyeatalnlkqvgykdkqp-----pfvvahirthfragsqefghvq
qwgkfilaihallgtgskeldhpwelvcaqcplylsdrdsraiygsal--
-kkssnlkyymltylemgegytykgplcgakdls---rslqathsgsstg
sftfagsklllfnfstkgnaqepvmcftpchfdpp-gnsclrkggkkrvq
srpsh------wtalapasapyrrqeildalgcadrdsklsliagylyea
arykqkqhgksgtdelmmfngggikssnatg-pcdsskvikdlahstddy
fgtfprgniwvplivaleqchr----------tvreylsfkglevarknv
dalanae
>ENV_HV2CA/25-512
---akgc--ctflwkmllsi----llvvnaygmiagygttmaleykavkg
lqfcitdgdlly-qlaawhtwfd---spafetlgrncaplvdtlgaelfk
petdvivrvvftstlalccnldqa-lvslvipfhktqflklpv-lltnis
vgsygcldsgaqnysiagpayvdklkafiackvdgnlrgevsktvqfnac
tkgldykgtalnldevgykhqva-----pfvmtqfrfqhkagsklftqvq
tlgdfnyaihsflgttpkelgdpqdlvcaqchlflsvrdarpiygssl--
-kkpakvkyymltyldlhqtytnlgklcgtrdlgdtqrtleaihs-----
-----akkl-mfnfsakan--evvlcftachteps-gts----ggkkrvq
grpafsvagmlhatltpenspyrkaevldalaclpkdsklll-gnflyqw
aryrqlshgkagtddhlvnndsgliqstaag-psaapkvvreygetgnfy
fgafhkaniwp-livklahchrkafvitdeawskweylqfkglqaarksv
pelaggg
>ENV_HV2NZ/24-502
---akgc--ttflwkmllsi----ltvvnaygmiagygttmaltykavkg
lqfcltdgdlly-qlaawhtwfd---sppfeslgrncaplvdtlgeelfk
petdvivnvvftstlalccnldqs-lvslvppfhkvqflklcv-lltnis
vgnygcldggvqnysiagpayvdklkayiackvdgnlrgevsktvqfnac
fkgldykgtalnleevgykhqvaifgespfvmtqfrfqekagsrlfgqvq
tvsdfnyaiqsflgttskelgdpqdlvcaqchlflsvrdarpiygssl--
-kkpaslkyymltyldlhqtysylgklcgtrdvgdtqrtleaihs-----
-----akkm-mfnfsakan--evvlcftachteps-gts----ggkkrvq
grpafsitgmlhatltpesspyrraevldalaclpkdsklll-gnflyew
tryrqashgkagtddhlvnndsgliqstaag-psaapkvvreygetgnfy
fgafhkaniwp-livklahchr----------ssweylqfkglqaerkkv
pelaggg
>node14
---akgc--ttflwkmllsi----ltvvnaygfiagygttmaltykavkg
lqycltdgdlly-qlaawhtwfd---spafeslgrncaplvdtlgeelfk
petdvlvrvvftstlalccnldqa-lvslvvpfhktqflklcv-lltnis
vgnygcldsgvqnysiagpayvdklkayiacnvdgnlrg---ktvqfnac
fkgldykgtalnldevgykhqva-----pfvmtqfrfqhkagsrlfgqvq
tlgdfnyaihsllsttskelgdpqdlvcaqchlflkvrdarpiygssl--
-kkpaslkyymltyldlhqtysylgklcgtrdlgdtqrtleaihs-----
-----akkl-mfnfsakan--eivlcftachteps-gts----ggkkrae
srpafsiagmlhatltpdsspyrkaevldalaclpkdsklll-gnflyew
tryrqlshgkagtddhlvnndsgliqstaag-psaapkvvreygetgnfy
fgtfhkaniwp-livklavchr----------ssweylqfkglqaarksv
pelagag
>node8
---akgc--taflwnmllsl----lpvcaaygmiagygttmalvykavkg
lqfcltdgellyv-----hswfdeanspafdplnrgcaplpdtvgeelfk
pdtdvlssvlftsslalccnvaq---vsllvpfhgtqflrlcvnlltnis
vgnygclgsgvqnysiagatnvnkakayiacnvngnlrg---ktiqfpac
fkgldyegtalnltevgykhqip-----pfvvtqirfqhragsrefghvq
qlgkfnlaihsllgttskelghpqdlvcaqcpmflsvrdarpiygsal--
-kkpaslkyymltyldlhqsysylgklcgtrdlg---rtleaihsgssta
sfsfaaskltlfnfsakgn--epvmcftpchtepp-gttclrkggkkrvq
srpafsiagflrttltpasspyrraevldalacsskdaklll-agylyew
tryrqlshgksatdehlvtngsgliqstaag-ptdspkvirdlgetanfy
fgtfhkaniwp-livklahchr----------atweylsfkglqaarktv
ealanag
