>node19
vpafvlsdi---------------------------talneks-----vp
nhplgc-plscktk-----------------halpplgsklldlafatcp
l-----gtgsvvvgcianeige--gtlkkfppsgfggsivkh----dpaa
nlfvvilhggaaaagh--dikfdfkgslsgtilegkdfs------apwrg
sepgvlmsesygeeltndngsahgvd-gdlvdnvlsigsynvktsifqrv
ilssgaltdkgveilalgecetqdhaygvmhkgvaavsrnl--tesepnf
yhqsgaqykp-feqwdgqmqnacqevnagspqyaydlehkklnphvkqdn
lladwiyfslctsgl-klass-tahpviscl-sds----kt--lecfsvl
hq----kgrgvrahdrs-kpgtsaec---sksraysefcqilaawthgtm
drskkmsaymmseyakgqqdlsldfftalgvvgqclvtgvvsynirldpa
qs-----gqccnmksnlcyaknckdaantgtlgrkagkltnvnkctahvq
feksrftegeayagkvshghftttvelstpctsismskcvkpkln
>node17
vpafilsdi---------------------------talneks-----vp
nhplgc-plncktk-----------------halpplgsklldlafatcp
l-----gtgsvvvgcianeige--gtlkkfppsgfggsivkh----dpaa
nlfvvilhggaaaagh--dikfdfkgslsgtilegkdfs------apwrg
sepgvlmsesygeeltndngtahgvd-gdlvdnvlsigsynvktsifqrv
ilssgaltdkgveilalgecetqdhaygvmhkgvaavsrnl--tesepnf
yhqsgaqykp-feqwdgqmqnacqevnagspqyaydlehkklnphvkqdn
lladwiyfslctsgl-klass-tahpviscl-sds----kt--ldcfsvl
hq----kgrgvrahdrs-kpgtsaec---sksraysefcqilaawthgtm
drskkmsaymmseyakgqqdlsldfftalgvvgqclvtgvvsynirldpa
qs-----gqccnmksnlcyaknckdaantgklgrkagkltnvnkctahvq
feksrftegeayagkvshghftttvelstpctsismskcvkpkln
>node10
vpafvlsdi---------------------------talneks-----vp
nhplgc-plscktk-----------------halpplgsklldlafttcp
l-----gtgsvvvgcianeige--gtlkkfppsgfggsivkf----npaa
nlfvvilhggaaaagh--dikfdfkgslsgtilegkdfs------apwrg
sepgvlmsesygetltndngsahgvd-gdlvdnvlpagsynvktsifqrv
ilssgiltdkgveilalgecetqdhaygvmhkgvaavsrnl--tesepnf
yhqsgaqykp-feqwdgqmqnacqevnagspqyaydlehkklnphvkqdn
lladwiyfslctsgl-klaas-tahpviscl-sds----kt--lecfsvl
hk----kgrgvrahdrs-k-gtsvec---tksrpysefcqilaawthgtm
drskkmsaymmseyakgqqdlsldfftalgvvgqclvtgvvsynirldpa
qs-----gqccnmksnlcyaknckdaantgtlgrkagkptnvdkctahvq
feksrftegeayagkvshghftttvelstpctsismskcvkpkln
>ENV_SIVG1/22-522
vptfvladisklmdpllhassfleqtavgfasldeftaldgkk-----vp
nhplgc-plsckvklrlgy------------nalvplgsklldmafttcp
ltgpc----glvvgcivekege--gslknfppagfagsivrf----kpaa
nlfivrkkggaddagv--dikfdfkgai-dtmldgktfs------apwss
sepgvlmsicytesltsdkgsahgadkgniakkvlvngtynamtstyt-v
imtpgilaergvemralsecetqd-----mhkgvagvsrll--tdtapnf
ygesasqykk-fekwegqkqnacqevnagspqyaydlehkkldshvkqpn
lladwryfslcsanlgkfadgltanpvrtcl-sds----kd--lncfsll
hk----dghgvrqndrrpk-gtsvrc---tksrpysefclilsawtnatm
drskkmeaymmseyakgqqelkldyytalgvvaqclvagvvshifr--pg
qsehqaygqccnmngtlcykgkckdaattgglgrrqgtpsnvdkctanvq
fdktrftageayvgnvahgnftntvklstpcssttkskcpkpkln
>node14
vpafvlsdi---------------------------talneks-----vp
nhplgc-plscktk-----------------halpplgsklldlafatcp
l-----gtgsvvvgcianeige--gtlkkfppsgfggslvkh----dpaa
nlfvvilhggaaaagh--dikfdfkgslsgtilegkdfs------apwrg
sepgvlmsesygeeltndngsahgvd-gdlvdnvlsigsynvktsifqrv
ilssgaltdkgveilalgecetqdhaygvmhkgvaavsrnl--tesepnf
yhqsgaqykp-feqwdgqmqnacqevnagspqyaydlehkklnphvkqdn
lladwiyfslctsgl-klass-tahpviscl-sds----kt--lecfkvl
hq----kgrgvrahdrs-kpgtsaec---sksraysefcqilaawthgtm
drskkmsaymmseyakgqqdlsldfftalgvvgqclvtgvvsynirlnpa
qs-----gqccnmksnlcyaknckdaantgtlgrkagkltnvnkctahvq
feksrftdgeayagkvshghftttvelstpctsismskcvkpkln
>ENV_SIVV1/24-538
vpafvladisklmdpilhtksfleqtavgfarleeftalegkk-----vp
nfplgc-rlsckvklrlsy------------haltplgtklldmaftvcp
lkgps----gvvvgcivedige--gslknfgptgfaksivrf----kpaa
nlfivrkkggaddagv--dikfdfkggi-damldgktfs------apwsg
aepevlmsicytesltndkgslhgadkgnigkrvlvagtynamtctyt-v
vmtpgiladrgveihalsecetqd-----mnkgvagvsrll--tdtapnf
ygqnaaqykk-fekwegqkqnacqevnagspqyaydldhkkldahvkqpn
lladwkyfslctsglgklastltanpvrtclagdncalekq--vecfgil
hr----dghgvwqndkr-k-gssvrcgkvtnsrpysefcvilaawtnagm
drs-tmsaymmseyakgqqelkldyytelgvvaqclvlgvvshifrldpg
qseiqayghccnmsstlcfkgkctdaattgglgrragsasnvdkctanvq
fdktrftagenyvgnishgnftntvklstpssavnkskcpkpkln
>node7
vptfvladisklmdpilhtksfleqtavgfasleeftaldgkk-----vp
nhplgc-plsckvklrlsy------------halvplgsklldmafttcp
ltgpc----gvvvgciveeige--gslknfppagfagsivrf----kpaa
nlfivrkkggaddagv--dikfdfkgai-dtmldgktfs------apwsg
sepgvlmsicytesltndkgsahgadkgniakkvlvagtynamtstyt-v
vmtpgilaergveihalsecetqd-----mhkgvagvsrll--tdtapnf
ygesaaqykk-fekwegqkqnacqevnagspqyaydlehkkldshvkqpn
lladwryfslctsglgklasgltanpvrtcl-sds----kd--lecfsll
hr----dghgvrqndrr-k-gtsvrc---tksrpysefcvilaawtnatm
drskkmsaymmseyakgqqelkldyytalgvvaqclvagvvshifrldpg
qseiqaygqccnmnstlcykgkckdaattgglgrragtpsnvdkctanvq
fdktrftageayvgnvshgnftntvklstpcssvskskcpkpkln
>node11
vpafvlsdi---------------------------talneks-----vp
nhplgc-plscktk-----------------halpplgsklldlafatcp
l-----gtgsvvvgcianeige--gtlkkfppsgfggsivkh----dpaa
nlfvvilhggaaaagh--dikfdfkgslsgtilegkdfs------apwrg
sepgvlmsesygeeltndngsahgvd-gdlvdnvlsigsynvktsifqrv
ilssgaltdkgveilalgecetqdhaygvmhkgvaavsrnl--tesepnf
yhqsgaqykp-feqwdgqmqnacqevnagspqyaydlehkklnphvkqdn
lladwiyfslctsgl-klass-tahpviscl-sds----kt--lecfsvl
hq----kgrgvrahdrs-kpgtsaec---sksraysefcqilaawthgtm
drskkmsaymmseyakgqqdlsldfftalgvvgqclvtgvvsynirldpa
qs-----gqccnmksnlcyaknckdaantgtlgrkagkltnvnkctahvq
feksrftegeayagkvshghftttvelstpctsismskcvkpkln
>ENV_HV2G1/23-502
tpafvlsdi---------------------------talneks-----vp
nhplgc-plscktk-----------------halpplgsklldlafatcp
l-----gtgsvvvgcianelge--gtmkkfppsgfggsivkhngvrdpaa
nlfvvvlnggaaaagh--dikfdfkgslsgtilegkdfa------apwrg
sepgvlmsesygeelkndngsahgvd-gdlvdnalaigsynvktsifqrv
ilssgaltdkgveilalgecetqdhaygvmhkgvaavsrnl--tesepnf
yhksgaqykp-feqwdgqmqnacqdtnagspqyaydlehkklnphvkqdn
lladwiyfslctsgl-klass-tahpviscl-nds----kt--lecfsvl
hq----kgrgvrahdrg-kpgtsaec---sksraysefcqilaawthgtm
drskkmsaymmseytkgqqdlsldfftalgvvgqclvtgvvsynirldpa
qs-----gqccnmksnlcyaknckdaansgtlgrkagkltnvnkctahvq
feksrftegeayagkvshghftttveistpctsismskcvkpkln
>node18
vpafvlsdi---------------------------talneks-----vp
nhplgc-plscktk-----------------halpplgsklldlafatcp
l-----gtgsvvvgcianeige--gtlkkfppsgfggsivkh----dpaa
nlfvvilhggaaaagh--dikfdfkgslsgtilegkdfs------apwrg
sepgvlmsesygeeltndngsahgvd-gdlvdnvlsigsynvktsifqrv
ilssgaltdkgveilalgecetqdhaygvmhkgvaavsrnl--tesepnf
yhqsgaqykp-feqwdgqmqnacqevnagspqyaydlehkklnphvkqdn
lladwiyfslctsgl-klass-tahpviscl-sds----kt--lecfsvl
hq----kgrgvrahdrs-kpgtsaec---sksraysefcqilaawthgtm
drskkmsaymmseyakgqqdlsldfftalgvvgqclvtgvvsynirldpa
qs-----gqccnmksnlcyaknckdaantgtlgrkagkltnvnkctahvq
feksrftegeayagkvshghftttvelstpctsismskcvkpkln
>ENV_SIVGB/47-569
vptfllvdkpklmekklqakeflaqteveysrvndftmlddkk-----vp
nqplgc-plsckvklhlscgpfltsqeadvgfvlvplgsklldwafttcp
ltgpclgltgavvgti--eige--gsykdfepagfggtivrf----rpde
nlflitrsgstddsevald--------v-atmldgktfd------agwsg
septvlmalcyge-ltndkgkahavdkgniaekvlvaatynavtstfsrv
imapgvlaargvqihalsecaphn-----rhkevhasskal--tdlapki
tgesfsqykp-fekwegekqnacqavlagspqygydlekkdldshvkeag
lltdwhffgliasglgkvlksqtgnptrpcl-cds----kslhlecfsll
hk----egqsvrtsnsq-k-gassvc---aksrpyfqfcvimgawtdssl
netkkmtaykmgdya----dlkfdyytalgvvarclvpgvpakifkldpa
p-eaasygqccsmkdslcfkgkcktkattgslgkkagkpssvnkcsarad
fvqvrftdgeayvgkvahqsfdntvkqstacakaasckcpkptlh
>node8
vptfvladisklmdailhtksflaqtavefasveeftaldekk-----vp
nhplgc-plsckvklhlsy------------halvplgsklldmafttcp
ltgpclgtggvvvgciaeeige--gslknfppagfggsivrf----kpaa
nlfivtkkggaddagv--dikfdfkgai-gtmldgktfs------apwsg
sepgvlmsicygesltndkgsahgvdkgnivdkvlvagtynamtstytrv
imtpgilaergveihalsecetqd-----mhkgvagvsral--tdtapnf
ygesgaqykp-fekwegqkqnacqevnagspqyaydlehkkldshvkqpn
lladwryfslctsglgklasgqtanpvrscl-sds----ks--lecfsll
hk----dghgvrqndrr-k-gtsvrc---tksrpysefcvilaawtngtm
drskkmsaymmseyakgqqdlkldyytalgvvarclvagvvshifrldpa
qsesqaygqccnmkstlcykgkckdaattgslgrkagkpsnvdkctahvq
fdktrftegeayvgkvshgnfnntvklstpcssvskskcpkpkln
>ENV_SIVM1/24-528
vpafvlsgi---------------------------talnekr-----vp
khalgc-llscktkmhlsc------------halpplgsklldlafttcp
l-----gtgsvvvgcianeige--gtlkkfppagfggsvvkf----npaa
nlfvvilhegaaaagh--dikfdfkgalsgtilegkdfs------apwrg
sepgvlmsesygetltndngsahgve-gdlvdnvlpagsynvktsifqrv
ilssgiltdkgveiltlgecetqdhaygvmhkgvaavsrnl--tesdpnf
yhqsgaqykp-feqsdgqkqnacqevnagspqyaydlehkklnphvkqdn
lladwiyfslctsgl-klasg-tahpviscl-sds----kt--lecfsvl
hk----kghgvrahgrs-k-gtsvec---tssrpykefcqilaawthgtm
dpskkmsaymmseyakgqqdlsldfftalgvvarclvtgvvsynisldpa
qs-----gqccnmksnlcytknckdaantgslgrkagkptnvdkctahvq
feksrftegetyagkvshgnfsttvekstpctsismskcvkpkln
>ENV_HV2D1/24-501
vpafvlsdi---------------------------talneks-----vp
nhplgc-plscktk-----------------halpplgsklldlafatcp
l-----gtgtrvvgciaaeige--gtlkkfpssgfggslvkh----dpaa
nlfvviahggataagh--dikfdfkgslsgtilegkdfs------apwrg
sepgvlmsesygeeltndngsahgvd-gdlvdnvlsigsynvktsifqrv
ilssgaltdkgveilalgecegqdhaygvmhkgvaagsrnl--tesepnf
yhqsgaqykpsfeqwdgqmhnacqevnagspqyaydlehkklnphvkgdn
lladwiyfslctsgl-klass-tahpviscl-sds----kt--lecfkvl
hq----kgrgvkahdrs-kpgtsadc---sksraysefcqilaawtngtm
drskkmsaymmseyakgqqnlsldfftslgvvghclvtgvvsynirlnpa
qs-----gqccnlkdnlcyaknckdaadtgtlgkkagkltnvnkctahvq
feksrftdgeayagkvshghftttvelstpct--amskcvkpkln
>ENV_HV2D2/24-513
vpafvlsdi---------------------------talneks-----vp
nhplgc-plscktk-----------------halpplasklldlaftacp
l-----gtgsvvvvcianeign--gtlkkfppsgfggsivkf----npaa
slfvvilhggaaaagn--dikfdfkgslsgtilegknfs------apwks
sepgilmsesygetltndngsahgvd-gdlidnvlpegaynvktsifrrv
ilssgvltdkgveilalgecgtqdhaygvmhkgvaaaarnl--tesep-f
yhqsgaqykp-feqwdgqmqdacqevnagapqyaydlehkklnpqvkqdn
llsdwvyfslctsgl-klaas-tahpviscl-sds----ks--ldcftvl
hklgmlkghgirahdrg-k-gtsiec---tksrpygefcqilaawthgtm
drskkmaaymmketakgqqdlsldffkalgkvglcmvtgvvsykirldpa
qs-----gqcinmksnlcyaknckdaantgtlgrkagkpanvdkctahvq
feksrftegeayagkvshghftttvelstpctsismskcvkpkrn
>node9
vpafvlsdi---------------------------talnekr-----vp
nhplgc-plscktkmhlsy------------halpplgsklldlafttcp
l-----gtgsvvvgcianeige--gtlkkfppagfggsivkf----npaa
nlfvvilhggaaaagh--dikfdfkgalsgtilegkdfs------apwrg
sepgvlmsesygetltndngsahgvd-gdlvdnvlpagsynvktsifqrv
ilssgiltdkgveilalgecetqdhaygvmhkgvaavsrnl--tesdpnf
yhqsgaqykp-feqwdgqkqnacqevnagspqyaydlehkklnphvkqdn
lladwiyfslctsgl-klasg-tahpviscl-sds----kt--lecfsvl
hk----kghgvrahdrs-k-gtsvec---tksrpysefcqilaawthgtm
drskkmsaymmseyakgqqdlsldfftalgvvarclvtgvvsynirldpa
qs-----gqccnmksnlcyaknckdaantgslgrkagkptnvdkctahvq
feksrftegeayagkvshgnfsttvelstpctsismskcvkpkln
>ENV_HV2BE/24-510
vpafvlsdi---------------------------talneks-----vp
nhplgckplscrtk-----------------halpplgsklldlafatca
l-----gtgsvvvgcianeige--gtlkkfppsgfggslvkh----dpaa
nlfvvilhggaaatsh--dikfdfkgslsgtilegkdfslvgvyaapwrn
sepgvlmsesygeeltnidgsahgvd-gdlvdnvlsigsysvktsifqrv
ilssgaltddgveilalgecetqdhaygvmrkgvaavarnl--tesepnf
yhqsgaqykp-feqwdgqmqnacqevnagspeyaydlehkklnphvkqdn
lladwiyfslctsgl-klass-tahpviscl-sds----kt--leyfkvl
hq----kgrgvrahdrs-kpgtsaec---sksraisefcqilaawthgtm
drskkmsaymmseyakgqqdlsldfftalgvvgqclvtgvvsyeirlnpa
es-----gqccnmksnlcyaknckdaantgtlgrkagkltnvnkctahvq
fevsrftdgeayagkvshnhfittvelskpctsismgkcvkpkln
>ENV_HV2NZ/24-502
vpafilsdv---------------------------talnekspilagvp
nhplnc-plncktk-----------------hsapplgsklldlafatcp
l-----gtgsvvvgcianeige--gtlkkfppsgfggsivkh----dpaa
nlfvvilhggaaaagh--dikfdfkgslsgtilegkdfs------apwrg
sepgvlmsesygeeltngngsahgvd-gnlvdnvlsignynvktsifqrv
ilssgaltdkgveilalgecetqdhaygvmhkgvaavnrd----esepnf
yhqsgapykp-feqwdgqmanlcqevnagtsqyaydlehkklnphvkqdn
lladwiylslctsgl-klass-tahpviscl-sds----dt--ldcfsvl
hq----kgrgvrahdrs-kpgtsaec---sksraysefcqilaawthgtm
drskkmssymmseyakgqqalsldfftalgvvgqclvtgvvsynirldpa
qs-----gqccnlksnlcyakncmdaadtgklgrkagkltnvnkctahvq
feksrftegeayagkvshghftttvelstpctsismskcvkpmln
>ENV_HV2CA/25-512
vpafilsdv---------------------------talneks-----vp
shplgc-plncktk-----------------halppfgsklldlafatcp
l-----gtgsvvvgcianeigeetgtlkkfppsgfggsivkh----dpas
nlfvvilhggaaaagh--dikfefkaslsgtilegkdfs------apwrd
sepgvlpsesygeeltndngtahgvd-gdlvdnvlsissynvktsffqrv
ilsdgaltdkgveilalgecdtqdhaygvmhkgvaavsrnladtesepnf
yhqsgaqykp-feqwdnemqnacqeinagssryaydlehkklnphvkqdn
lladwvyfslctsgl-klass-aahpvlscl-sdp----kt--ldcfsvl
------kgrgvrahdrs-kpgtsaec---sksraysefcqilaawthgtm
drskkmsaymmseyakgeqdlsldfftalgvvsvclvtgvvsynirhdps
qs-----gqccnmksnlcyaknckdaantgklgrkagkltnvnkctahvq
feksrftegegyagkvshghftttvemstpctsismskcvkpkln
