>node18
lfsrh---eq---ntahakgivaa--v--cyhik----------------
--nf-vvgntslalegynrlkinllvekg---------------s-----
-vkfkaqa--------y---l---klpngeakfykvavektvaksgkdgv
gae-eqrscfgen--dgflvrtf--erklk-flgkadslclnya--gdmg
achlvlvgsm--smnkc----lvgntslkq-------gnkvwa-----lr
cqi--aahf-kyrrrpt-ivvtwggkdivdt-----qvyavnpyggdg-h
hfcakaqe-a-----hmleddvkadlvqie----peisantikgyplkan
avvg-p-eladlehfqlvvhrdagvif-----lfrapsvr----e---eg
taegggeagycnalln--clpedel---a-svv----scq---ei-gqlr
tvq-dga-emtvk-tfepakt--gaqassfkfgrfl--------lkt---
-----aayhvp--i-lnmgisscqglcglny--vdgsswaatirvqdlh-
--lrasv-fv----------akiskf--ahykepagvk---fp--relhi
-qgihgkcksenvfrr--gggmtc-----khesw--------ga----d-
---f-------aanrdkdqertkdhckstqd----lavrdverrvdgnr-
-a------vvvmtksqsaa-lfn-----lghlgk----hnyesngyv
>ENV_HV2NZ/24-502
lfsrh---eq---nt-------aa--v--cyhik----------------
--df-vcgntsltqeaynrlkinllvekg---------------s-----
-vkfkpqa--------y---l---klpngapkffkvavkktvakegadgv
gah-eqrscfggn--dgflvrsf--erklk-fmgnaepipldys--gdmg
acflvlvgkm--vmnkc----la-------------------------vr
cli--vahf-kyrrrpt-ivvnwggktivda-----nvyavnstgadg-h
nfcvkaqe-a-----hmleddvecdlvete----pavsentidgyplkan
gvvg-a-altalehlqlvvhrtagvif-----lfreptvr----e---eg
takgngevgycdpllk--clpedey---a-svv----scq---dl-gelr
grkldaq-eltvn-tfepskt--naqsasfkfgrfp--------lrt---
-----tayvgp--i-lnmgisaceglcgley--vkgsgwtttiraqnlh-
--fresi-fl----------ariakf--ahyk---gvtqlqfp--relhi
-qgihgkcksenvfrr--ggamtc-----khesw--------ga----q-
---f-------svnkdkdqtrtkdhckstqd----lavrdierrtdgnr-
-i------givmtnsrgap-lfn-----lahlak----hnfesdgyv
>ENV_SIVG1/22-522
hnskhp-pee---dvahtkwfags--i--tfhir----------------
--tf-vrsnvrlplegynglevglgasdi---------------r-----
-kkfklva--------c---l---rlnganl--ydvtanralqrkelqvl
ggh-cpkkmfsatvihgiiltg-lnn----tfnkkvstlslaya--keig
gcagalvttv--rvarc----lagssh----------------dlisyhv
--------wadyrhkpq-mihtwgireiaae-----hv-----------h
qlckew----------lvvqglksslihkn----pvts------ys-kfn
nvvg-a-hiatskkteyvhhrkgavvy-----lfk-pslspsvsv---gd
yaggggnagycsdllg--cl-wsdlvhf--cvgfsp-vcq---ea-glfi
tir-sesaemess-tfqppsf--idqhilykfprylglkkqlgflkv---
-----dlfhaa--vsldlgskvalslydlalvs-egishsvgk---s---
--vkqnvnvirgpgktvgylgkrglf--ptfkaqqgvc---fn--rnlei
-vptedsvkqgcvlrdlnaqgqva-----tdq-wyphgdchgag----e-
---h-------rntdnttkgip-------------m---qiidpidpnr-
-a------gdvknrphggs-klh-----qa--------hkysd-e--
>ENV_HV2BE/24-510
lfgrh---eqfgpnvadasgivta--v--cynik----------------
--gfivvanessqlegyerlkinlltekg---------------skhlai
gvkfkaqv--------y---l---nlpngaakfykvmvekfvlkhgkdgv
gae-pqrgcfges--ggflvr--------k-hldkadslclayt--gnmg
achlvlvasm--smnkc----qvgnsslkq-------gnrvwa-----lr
ctv--ea---kyrktvs-ivvtwggkqivet-----qvyavnpyggdg-h
hfcnkdqe-t-----hkheedvra----ve----sensantikgyslktn
avvg-p-amadlehfqlivhrdpgatf-----iikgpsvr----e---dg
taqvggeagyckavln--clpedel---nktvv----tcqwkndl-gqlk
tva-dgd-qm-vk-tfepnkt--gaqaqafkfgrfl--------ikt---
-----asypvp--i-lnqgassyqglvglhn--vdsstwaatirvqqlr-
--lnasv-fv----------akiakf--ahykdpagak---lp--relhv
-qgihvdcklpnalrk--gggetc-----khrsw--------gt----d-
---f-------yankdkdqepakafvkpaqdltyalpvrdierrvdghr-
-a------avvmtnsqsaa-lfn-----lsplgk----hnyysngyv
>node17
lfsrh---eq---ntahpkgivaa--v--cyhik----------------
--nf-vvgntslalegynrlkinllvekg---------------s-----
-vkfkaqa--------y---l---klpngeakfykvavektvaksgedgv
gae-eqrscfgen--dgflvrtf--erklk-fmgkadslclnya--gdmg
achlvlvgtm--pmnkc----lv-------------------------vr
cqi--aahf-kyrrrpt-ivvtwggktivdv-----nvyavnpyggdg-h
hfcakaqe-a-----hmleddvqcdlvqie----peisantikgyplkan
avvg-a-elaelehfqlvvhrdagvif-----lfraptvr----e---eg
taegggeagycdalln--clpedey---a-svv----scq---ei-gelr
tvq-dga-emtvk-tfepskt--gaqassfrfgrfl--------lkt---
-----aayhvp--i-lnmgisscqglcgley--vdgsgwtatirvqdlh-
--lrasv-fv----------akiskf--ahykepagvk---fp--relhi
-qgihgkcksenvfrr--gggmtc-----khesw--------ga----e-
---f-------aanrdkdqertkdhckstqd----lavrdverrvdgnr-
-v------gvvmtnsqsaa-lfn-----lghlak----hnfesngyv
>node8
lnskhp-pek---dtahtkwitls--i--sfhiq----------------
--tf-vmsqvrlslegydglevglladtv---------------d-----
-qkfkvvp--------c---l---klngaklqfynvgadkalqkkeiqvl
ggh-cpkkkfseavihgiivrg---n-----fstkvdslclsya--keig
kcrggmvtsv--rvarc----ltgsthlkt-------n-vvkn-----lv
--------wsdyrnrpd-vvhtwgirdiaga-----rv-----------h
hlcnewhe-t-----hlvnqglkaaliqme----pvns------ys-kfn
nlag-s-hlantkkfefvhhrkaavvy-----lfr-ptlkpgisv---gd
yaeagggagycsellg--cl-wsdlqqf--cvgfag-gcq---ev-glfi
tik-tts-dmavs-tfeppsa--vgqhilykfqrflalkkqlgflkv---
-----diyhaa--vsldlgartalslyifgfrs-egiskgvam---n---
--lrenv-vvrgadsavgylskigaf--prfkaargvs---fh--rslsi
-vavkddvkrdcvfrdngaagqvs-----ddq-wyphgdchgda----d-
---h-------rdndntakgrt-------------lsvqqvikkvdpnr-
-a------vdvkskppaga-kfh-----lgalgk--dahkyie-a--
>ENV_HV2D2/24-513
hfsrh---da---ntsstsgitpa--v--ciynk----------------
--hf-dvgntslalsgynkievkll---g---------------s-----
-a-fiiqp--------y---f---tlvnvnaryydsavektvaesgkdtv
gaedaqratqgee--dgflvrt---grklk-flakgeslcldyavngdmg
gchivqvkti--rmpkc----lqgnsslkq-------npkvwe-----nr
chi--parf-kfkvkpt-ilvawgsadivds-----lv----------gq
hfcatpqe-e-----vmveedvnad--------------------slknd
yivg-p-elaeldhlqlvlhrsanvif-----lhhvptlr---ge---dg
tadagektgyckavln--clpedkl---n-svafrg-gsq---qe-gqfr
ivq-dgt-emtlk-tyqplkt--gtqassfkfgrfl--------lst---
-----atihvp--i-hnmnvsackalcsfdy--vdgpnwaptirvqdld-
--lragv-fi----------adqskf--pkyrepssvk---fa--ralhl
-agthgkckhnnvfrr--gvgdnc-----khpsw--------ga----d-
---f-------elnrngheert-------------lyvrkveprvdgnr-
-a------lillkksnspt-lfn-----lghlgk----hnyesn-yv
>ENV_HV2CA/25-512
lferq---ek---nt-----------t--cylik----------------
--nf-avgdtalalegynrlkinmlvekg---------------a-----
-vkfkaqa--------y---l---alpngeakfykvavgntvakskedsv
gae-eqrdcfgen--dgflvrki--esklk--mgkadsl-lnna--gdke
ich-vlvgtm--dmnkc----lv-------------------------ar
cqvhvtehf-kykrrpt--ivtwggktavav-----dvyavkpyggek-h
qfaakare-a-----hmlqddvkcglvqie----peisantidgyplkat
avvs-a-eltelehfqlvvhknsgvvf-----lfraatvr----d---eg
tahgegeagycdallnepclpedey---a-ssv----scq---ei-gelr
avq-dgt-emtlk-afenskt--giqasafkfgrfl--------lkt---
-----asyhvp--i-ldmsipscqglcsl-----dgsgwtatirvgdlh-
--krtsi-fl----------atishf--aiykepsgvk---fa--relhi
-qgihgkcksdnvfrr--gggmvc-----klesw--------gg----er
csvf-------gatrdkdqertkdhcksaqd----lavreverrvngrr-
-h------gvvvantpsav-lfn-----lgnlsk----hnfektggi
>node7
lnskhp-pek---dvahtkwfags--i--tfhiq----------------
--tf-vkshvrlplegynglevgllasdv---------------h-----
-mkfklvs--------c---l---rlngakl--ydvgaeralqkkelqvl
ggh-cpkkmfsetvihgiiitg---n-----fnkkvatlclaya--keig
kcpgafvtsv--rvarc----lagsshldt-----------knnlvsyhv
--------wadyrnrpa-mihtwgireiaga-----hv-----------h
hlckewfe-t-----hlvaqglkasliqkd----pvtn------ys-kfn
nvag-a-hiattkkaeyvhhrkaavvy-----lfr-pslspgvsv---gd
yagaggdagycsdllg--cl-wsdlqqf--cvgfsa-gcq---ev-glfi
tir-ttsadmess-tfeppsv--vgqhilykfqrylglkkqlgflkv---
-----difhaa--vsldlgakaalslyvfafvs-egiskgvgm---n---
--vrenv-virgpgstvgylsklgaf--pkfkaqhgvs---fh--rslsi
-vptkddvkrvcvlrdlgaagqva-----tdq-wyphgdchgga----d-
---h-------rnadnttkgit-------------m---qvidpvdpnr-
-a------gdvksrphgga-klh-----lgavgk--dahkysd-e--
>ENV_SIVM1/24-528
lfnrh---eq---npahtkgvvla--v--cyhir----------------
--sf-lvgntnlaleqynkleikllaakg---------------a-----
-akfkvvp--------y---l---nhqggkakfynmavektvaksgkdkv
gld-cprskfgan--dgillrs---qrklk-ligkvgslclnht--gemg
achlhmvnsi--rmakc----ligntslkg-------nevvwn-----lr
cqi--gagf-kyrrnpt-ivhtwggkdvadt-----qv-----------h
hfcskpqe-t-----hllhrrvksdlvqie----pdissktikayslksn
gvvg-p-eladlgdfeqvkhrdaglif-----lfraptvr---se---gg
yvegaldagycngsln--capeskl---s-cvtfrgkgcq---ei-gdfr
viq-dgt-eqtvk-tfepayt--gsqratykfgrfl--------lkv---
-----aifhvp--a-lnmgvsscqglcglgy--idgsswagayrhqelh-
--lrasv-fv----------aniski--prykeprgvk---yn--rtlr-
-igghnqck-esvfrr--ssglis-----khekw--------ga----d-
---f-------aanrpkneerk-------------lavksveksvesikq
pa------vvvmtspqgatlqfntekeglvnlgk--dahnyqsnpyv
>ENV_SIVGB/47-569
vvsgrpwlar---dtsfkkylald--kafsfqvk----------------
--tl-aieetklarailarlqk------nattegvlifavhnaf------
-------v-------ecqtkigpkwls------fslsqkkalktgaveal
gaq-cphpvlkpimtqaigvrs----------ntpvegls-lqv--tefq
parpsv-vyism----c----v-------lqptvllvd-ilgd-----il
--------kgdqtskq--tgettlwktrngt-----lf-----------h
eichhwsmfs-----vsgskgvvgvlihvdikkg-vtl------ah-hfp
rtsa-rqhlsiaakfrflhhhhnt---------fr-lgekpkilt---ee
yan-lgsagtmh---------k--------crelal-gtt---etg----
krr-hds-lmkva-afspketgptaeqalsna---larqeamgfmnahqg
eagyspcddnnvtftlrmkkhlsvfgyrlniis-nsithalgf---y--r
slvwq---mkwasdtalgvlnkdgsgnappfltpvadh---thtisrsda
pllvd---kkspdlsdddasvanttvggg-k-------a--glhvcfgn-
---nvfr----hantealkgwd-------------kavsvvi--------
-vdsqrralactspkpdsg-gfn-----llkvhtpghnht-yv-n--
>ENV_HV2G1/23-502
lfsrh---eq---npahakgivaa--a--cysik----------------
--tf-vvgntklafegynrlkipmfvelg---------------s-----
-akfkaep--------y---l---klpdgeqtfyrvafdktvakneksal
sad-eqrscfgnn--dgflvraf--erkvn-flgkadgiclnya--gdmg
achlvlvgsm--sgnmcairdlvgntglkq-------gnkvwi-----lk
cqr--aahf-nyrrrft-iavtwggrdivdt-----qvyapnpyggdg-h
hfcampae-nksvnlhmleedvkadlvtie----peisantikgyslkaq
tvvg-d-eladqehfqlvthrdagvif-----lfrgpavr----t---qg
tcegggdagycnamln--clpedel---a-svv----scq---ei-gqlr
tvq-dga-emtvk-tfepakt--gaqassfrfgrfl--------lrt---
-----atfhlp--a-lnmgissnqglcalny--heggswaetirvqdlh-
--lrasv-fv----------anvskf--ahykepagvk---fp--rglhi
-qgihgkcksenvfrr--aggvtc-----kiesw--------ga----d-
---f---ksgsaanrdkdqers-------------navrnverrvdgnr-
-a------vvvkknsqsla-lfn-----lghlgk----hsyesnsyv
>node14
lfsrh---eq---ntahasgivaa--v--cynik----------------
--nfivvgntslalegynrlkinllvekg---------------s-----
-vkfkaqa--------y---l---nlpngaakfykvavektvlksgkdgv
gae-eqrscfgen--dgflvrtf--erklk-llgkadslclnya--gdmg
achlvlvgsm--smnkc----lvgntslkq-------gnkvwa-----lr
cai--aahf-kyrrrvs-ivvtwggkdivdt-----qvyavnpyggdg-h
hfcakaqe-a-----hkleddvkadlvqie----peisantikgyplkan
avvg-p-aladlehfqlivhrdagvtf-----lfkapsvr----e---eg
taegggeagycnalln--clpedel---aksvv----scq---ei-gqlk
tva-dga-qmtvk-tfepakt--gaqastfkfgrfl--------lkt---
-----aaypvp--i-lnmgasscqglvglhy--vdgsswaatirvqdlh-
--lkasv-fv----------akiskf--ahykepagvk---lp--relhi
-qgihgkcksenvfrk--gggmtc-----khksw--------gt----d-
---f-------aankdkdqerakdhckstqdltyalavrdverrvdgnr-
-a------vvvmtksqsaa-lfn-----lghlgk----hnynsngyv
>node9
lfsrh---eq---ntahtkgivla--v--cyhik----------------
--sf-vvgntslalegynkleikllaekg---------------s-----
-akfkvvp--------y---l---klpggkakfynvavektvaksgkdkv
gae-cprstfgen--dgilvrt---qrklk-flgkvdslclnya--gemg
achlvmvnsi--rmpkc----lvgntslkq-------neivwn-----lr
cqi--aagf-kyrrrpt-ivhtwggkdvvdt-----qv-----------h
hfcakpqe-t-----hmlhervkadlvqie----pdisaktikgyslksn
avvg-p-eladlenfelvkhrdagvif-----lfraptvr---se---gg
yaegggdagycnalln--clpeskl---s-cvtfrg-gcq---ei-gqfr
tiq-dga-emtvk-tfepayt--gsqratykfgrfl--------lkv---
-----atfhvp--v-lnmgisscqglcgfny--idgsswaaairvqdlh-
--lrasv-fv----------aniskf--prykeprgvk---yn--rtlhi
-igvhnkcksesvfrr--sggmic-----khekw--------ga----d-
---f-------aanrskdeert-------------lavrdveksvdgnr-
-a------vvvmtkpqaat-qfn-----lgnlgk--daqnyesnpyv
>ENV_HV2D1/24-501
lfcrh---eq---ntahasgivaa--v--cypikacsplvvrtpleivcl
dgnfivignaslalegynrlkvnllvekg---------------s-----
-vkfkaks--------y---l---nlpnksakfnkvaaentvltsgkdgt
gae-eqrscfgdn--dgflvrtf--vrkmk-plgkadslclnya--ndmg
nchlvlvgsm--smtkc----lvggtslkq-------knkvwa-----ls
cai--aahf-kfpkrvs-ivvtwggkdvvdt-----qvyvvnpyesdg-d
hfcak--e-c-----hkqeddvkadlvlie----peigantlksyalkag
avag-p-alaqlehfqlivhrgagvtfggrsvlfkvpsv---------ag
taegggeagycsalln--clpeeel---ak-vv----scq---ei-eqlk
taa-dga-qmslk-tfepakt--gaqaqtfkfgrff--------lkt---
-----aahpvp--i-lsmgantckglvalqy--adgsswyatikvealh-
--lkqev-lv----------akiskf--ahykepdgir---lp--relhi
-rsiqakcktgnvfrk--gggmtc-----knksw--------gs----d-
---f-------aankdkdqerakdvckstqdltvalsvrdverrvagnh-
-v------vvlmtkaqspa-lfn-----lghlgn----qnynsnkyv
>node11
lfsrh---eq---ntahakgivaa--v--cyhik----------------
--nf-vvgntslalegynrlkinllvekg---------------s-----
-akfkaqp--------y---l---klpngeakfykvavektvaksgkdav
gae-eqrscfgen--dgflvrtf--erklk-flgkadslclnya--gdmg
achlvlvgsm--smnkc----lvgntslkq-------gnkvwa-----lr
cqi--aahf-kyrrrpt-ivvtwggkdivdt-----qvyavnpyggdg-h
hfcakpqe-a-----hmleedvkadlvqie----peisantikgyplkan
avvg-p-eladlehfqlvvhrdagvif-----lfrapsvr----e---eg
taegggdagycnalln--clpedel---a-svv----scq---ei-gqlr
tvq-dga-emtvk-tfepakt--gaqassfkfgrfl--------lkt---
-----atfhvp--i-lnmgisscqglcglny--vdgsswaatirvqdlh-
--lrasv-fv----------aniskf--ahykepagvk---fp--ralhi
-qgihgkcksenvfrr--gggmtc-----khesw--------ga----d-
---f-------aanrdkdqert-------------lavrdverrvdgnr-
-a------vvvmtksqsaa-lfn-----lghlgk----hnyesngyv
>ENV_SIVV1/24-538
pakkhp-pak---elgh-----ggnsi--tymiq----------------
--ni-vkshvrlplggynelevslladd----------------------
-lafklsvglvvarn-y---l---rlngakl--ynvgaervlnkkdlevl
tap-gaeklfsetvihgllivg---e-----ldkkaatlslaya--kevg
ncpgwfvtnv--iyarc----laltnhvdt-----------knhaggthv
--------wadyrntpdymvllrseksvagaliitkdv-----------h
alcgewfe-t-----ylvaeglkaslipkd----paag------ys-tfd
ptsgra-fiptt-----------tvay-----lfr-palslgiavkftgt
flgaggtaqtctealg--im-ws----f--vvgfsg-gcq---di-glfv
nii-lssldmeastkfkpqsa--vgqhilykyqryiglkkqlairhl---
-----dsfqat--vtldlfgmeslslyvfafvs-eeiskgvgq---k---
--mrenv-vvhgqgwtigylgplgaf--vkfkenhgis---yc--rglsi
-vppkdgikkscilrdlsanpkvt-----gdq-waphnechgaa----d-
---y-------rngkngvkgis-------------m---hilepgdp---
-a------gdvkdiphgae-klh-----lgsvgk--gassfad-e--
>node19
lfsrh---eq---ntahakgivaa--v--cyhik----------------
--nf-vvgntslalegynrlkinllvekg---------------s-----
-vkfkaqa--------y---l---klpngeakfykvavektvaksgkdgv
gae-eqrscfgen--dgflvrtf--erklk-flgkadslclnya--gdmg
achlvlvgsm--smnkc----lvgntslkq-------gnkvwa-----lr
cqi--aahf-kyrrrpt-ivvtwggkdivdt-----qvyavnpyggdg-h
hfcakaqe-a-----hmleedvkadlvqie----peisantikgyplkan
avvg-p-eladlehfqlvvhrdagvif-----lfrapsvr----e---eg
taegggdagycnalln--clpedel---a-svv----scq---ei-gqlr
tvq-dga-emtvk-tfepakt--gaqassfkfgrfl--------lkt---
-----aayhvp--i-lnmgisscqglcglny--vdgsswaatirvqdlh-
--lrasv-fv----------aniskf--ahykepagvk---fp--relhi
-qgihgkcksenvfrr--gggmtc-----khesw--------ga----d-
---f-------aanrdkdqert-------------lavrdverrvdgnr-
-a------vvvmtksqsaa-lfn-----lghlgk----hnyesngyv
>node10
lfsrh---eq---ntahtkgivla--v--cyhik----------------
--nf-vvgntslalegynrleikllvekg---------------s-----
-akfkvqp--------y---l---klpngkakfynvavektvaksgkdav
gae-aqrstfgen--dgflvrt---erklk-flgkadslclnya--gdmg
achlvlvnsi--rmpkc----lvgntslkq-------nekvwa-----lr
cqi--aahf-kyrrrpt-ivvtwggkdivdt-----qv-----------h
hfcakpqe-a-----hmleedvkadlvqie----peisantikgyslknn
avvg-p-eladlehfqlvvhrdagvif-----lfraptvr---se---eg
taegggdagycnalln--clpedkl---a-svtfkg-gcq---ei-gqfr
tvq-dga-emtvk-tfepakt--gaqassfkfgrfl--------lkt---
-----atfhvp--i-lnmgisscqglcgfny--vdgsswaatirvqdlh-
--lrasv-fv----------aniskf--pkykeprgvk---fp--ralhi
-qgihgkcksenvfrr--gggmtc-----khesw--------ga----d-
---f-------aanrnkdeert-------------lavrdverrvdgnr-
-a------vvvmtksqsat-lfn-----lghlgk----hnyesngyv
