>node11
----w---gn---ag----evi------y--cessv--aeisyvkqrqvk
vfyyvndrftkwllkh------pth---kh-------gqtmytkgn----
--tm-----pklfagtg--ctmlkgqfskviapwellvikypsfgtkv--
ilcsdekigskqvlgd---sgtsllllaf-we----alsmklgvlv----
-------v-gtlllhlqs-h---k-ahvsgk-lltagcvessa------l
p--lfmaediidiskp--pllaptv----sr-k------pvraeggtdrf
ss----nehek-v-----dlkvvsa----------v-------cet-ppl
rgcadc----aa--pafa------lnpalaslfacs--------kccfts
----c----i--lvapvgamisqef-tgdhvgflmppg---krsraf---
---r---n---lylrlfi-etypgdgg-------aycn----nipiali-
-gs-hspvdt-edl-------a---egvqvp-v-sikhq----ececgdn
agketaclafsystg-lqitsgggarasqdkeqfyss----qcaegmcg-
iilgkvkfal---sgq-i---l----pdedylpggkr--tdvll---ftp
flshaie--aql-yavdd-slqhhyv-lknvyypn--s--lleyihl-nt
-vgg--kd-------nala---c--------khpiyh--------t----
---------l--r-leeyg--ftd-----g----wv--adhcg-------
-----pq---gta
>ENV_HV2D1/24-501
----w---gd---gg----avi------y--cqtig--aeissvkqrqvk
vfyfvndrltkwpleh--------h---kh-------gqtlatkgh----
--tm-----palfagsg--ctmlkhqftkviaprellvmkypsfgvkv--
ilcddekigsksvlan---sgtallllaf-we----hlfmklgvlv----
-------r-gtlfvq-qs-h---k-ahvkgk-lltygcv-----------
p--lfmaddiidvskp--pl----v----sr-k------pvrteggtdrf
ts----kdhee-v-----dlkvvsa----------i-------cet-p--
-----c----aa--pafa------lnpslaslfaca--------kscfea
----c----v--laapvggmsshel-vgdrvgflmppg---krsqaf---
---r---n---lylrlfi---ypgdgg-------aycd----nipiali-
-gs-qspvdt-edl-------p---egvhvp-i-aikhe----ececgdn
pgdesaclafsystg-fhvtssggarrnadkeqfyss----lcaagm-g-
ivlckvkfglalnsgq-i---l----pdedylpggkr---gals---ftn
flahave--dql-esvde-tlqhhyv-lkavyyan--s--llsyihl-dt
-vgg--kd-------sals---c--------dypiyh--------t----
---------l--r-leeya--fid-----g----wv--vdncg-------
-----pq---nsa
>ENV_SIVV1/24-538
---eneilan---akermeytc-----ef--cegfmka------------
ililnkevykkkhdshqgvrpdcrk---m----------pmkakgk----
--ti-----tqlfhcdg--y-----------------vsciqsfdgkl--
idcmprkygaktqksilvsvggdlltfts-wd----pltvmgpiylngla
igtekqai-gglvidlvgvhlipk-etlaak-ilhg-----ka------v
y--pflfdplldig----tllernaarlvgr-k------plsargf----
sgkhrgkefeq-vaptsdraqgag---------------------l-sap
---dea----ik--vafgthsegflppvttcrlkln--------kdclqp
l-vgckdtlq--pgasi-----nay-gkcdvrslsksl---vthrtidat
kndr---y---lalssyi-rvvkglmg-------cfca----nes-----
------qqna-dql-------t---ksdkkltqkkcehh----t------
-----vgqrfsygqg-lrvpgteaa----s----fgs----ecsigmi--
tplggsr-dl------th---h----pknsystttdsgkigpaq---fka
asfnmtd--sqiwratgyrnftgp-v-cvdvyyst--lravyk-hra-kt
-idt-----------dcar---a--------yekiyk--------t----
---------l--a-vrdygkkwtdqagstg----wf--gshcsiieddsp
isaivvk---atf
>node8
---es---gn---ak----tvp-----hf--cegfi--ttvkyiksragd
ifvylrdiytksagmh------cid---e----------pmnskgk----
--kl-----aqlfacdg--cpmien-------pfelviskmpyfntkl--
vdclsqkigsktfsgdlvgagtalllfaf-we----alnimgaifl----
-------v-gdlllhlvgvhlvnk-gnlagk-llyg-----ka------l
k--lflfdciinigdc--vllerki----sr-k------pleargf----
is----peyqn-v-----keqvigp----------l-------cav-tps
rgaddc----lk--vdig------lpptvasdlria--------kcclqp
l-vgckntia--pqggvgsmiaqaf-gssqvpfltkav---tthrgs---
---r---y---ltlfsfi-raykglmd-------cfcn----dvp-----
------qina-dql-------t---ksdknptvkkcahq----s------
-----acewfsysqg-lqvtgaaga----t----fps----qctigmvg-
lplagvk-pi---alrtr---h----pkadyntgves--aeplv---fkp
eafdatd--aql-rapdlknfsaq-t-ykqvyypa--srpvyk-lhy-kt
-igg--gd-------kclp---a--------yqpiyr--------n----
---------l--a-lhdygkkwtd-----g----wy--gshckv------
----vvr---gti
>ENV_HV2D2/24-513
---gw---gn---ag----evi------y--cessi--aeisyvkqrqvk
vfyyhddifkkwldkh------pth---sh-------gknkytkal----
--tm-----pkl---tg--cpmlkg-------pwqllvmkypsfgtkt--
sncss----ssqvqgn---gggkvlglaf-we----vl-----vlv----
-------a-mtllvnlit-q---r-tvvvga-lfha---dss-------l
p--lfqaedivdiskp--plvaplv----sr-t------vvraeggkdhf
ta----nghek-a-----dlkvsaa----------v-------cev-psl
kgcgdctkpnaa---kfn------lnpalaslyscs--------rycytn
----c----d--lsqavggivsqdf-ttdhvafllptg---krrraf---
---r---n---lelplfr-ddytgege-------aycn----nvprpli-
-gt-htpvdt-dhm-------a---qgvhvp-v-sikhm----a------
-----aclafsystg-lpinsdsdarastdkeqfysn----dctegacg-
silgkvkiel---ngq-f---l----wdedyipgvnr--tdvll---fkp
flfdaia--gql-yavde-gtqhhyv-vknifyan--a--flefifl-ng
-aigepae-------eala---c--------mhpiyh--------t----
---------l--a-adaye--ftk-----p----wv--adrkd-------
-----dt---gka
>node19
----w---gn---ag----avi------y--cessv--aeisyvkqrqvk
vfyyvndrftkwllkh------pth---kh-------gqtlytkgn----
--tm-----pklfagtg--ctmlkgqfskviaprellvikypsfgtkv--
ilcsdekigskqvlgd---sgtsllllaf-we----alsmklgvlv----
-------v-gtlllhlqs-h---k-ahvsgk-lltagcvessa------l
p--lfmaediidiskp--pllaptv----sr-k------pvraeggtdrf
ss----nehek-v-----dlkvvsa----------v-------cet-ppl
rgcadc----aa--pafa------lnpalaslfacs--------kccfts
----c----v--lvapvgamisqef-tgdhvgflmppg---krsqaf---
---r---n---lylrlfi-etypgdgg-------aycn----nipiali-
-gs-hspvdt-edl-------a---egvqvp-v-sikhq----ececgdn
agketaclafsystg-lqitsgggarasqdkeqfyss----qcaegmcg-
iilgkvkfal---sgq-i---l----pdedylpggkr--tdvll---ftp
flshaie--aql-yavdd-slqhhyv-lknvyypn--s--lleyihl-nt
-vgg--kd-------nala---c--------khpiyh--------t----
---------l--r-leeyg--ftd-----g----wv--adhcg-------
-----pq---gta
>ENV_SIVG1/22-522
aqaet---gn---vk----nva-----hf--cegfl--ttvkfvptktks
vfvylreeytkkhggh------cik--------------pmgtkgi----
--si-----aqlfacvg--cpliks-----------atsrvpsfdgkl--
vsc----igaktfsgelvgvgapllvgaf-wd----sltnmgpiflngsq
fghahngi-gglllhlmgihliak-enlagk-llyg-----ka------l
k--pf-f-silnigav--lllprkp-----r-k------plsargf----
vskrrgneyqn-v-----kiqvtgp----------l-------cav-tat
kggeag----lk--lgvga----flppktasnariv--------khclqp
l-vdckdtlg--pqev--skvvkay-gsstvpfliksv---tthrgs---
---r---y---ltlfsfirrvvkglie-------cfcg----avp-----
------hvya-ngl-------i---ksdkkltvkkcahh----s------
-----acerfsysqg-lrvpatptr----t----fps----qcsigmig-
lplpgsk-di---ai-tk---h----pkpdyntgtesgkaqplv---ika
dsfeasndkehiwsapdyrtfsaa-a-cvtvhyas--ghavyk-hry-kp
-idp--gd-------eclr---d--------yqptyr--------d----
---------l--a-lqdygkkwtd-----g----ry--gshcev------
----vvr---kaf
>node14
----w---gn---ag----avi------y--cqssv--aeisyvkqrqvk
vfyyvndrftkwllkh--------h---kh-------gqtlytkgh----
--tm-----pklfagsg--ctmlkgqfskviaprellvikypsfgtkv--
ilcsdekigskqvlan---sgtsllllaf-we----alfmklgvlv----
-------v-gtlllh-qs-h---k-ahvsgk-lltagcvdssa------l
p--lfmaediidiskp--plvaptv----sr-k------pvraeggtdrf
ss----kehek-v-----dlkvvsa----------i-------cet-ppl
kgcadc----aa--pafa------lnpslaslfacs--------kccfts
----c----v--lvapvgamishef-tgdhvgflmppg---krsqaf---
---r---n---lylrlfi---ypgdgg-------aycn----nipiali-
-gs-hspvdt-edl-------p---egvqvp-i-aikhe----ececgdn
agkesaclafsystg-lhvtsgggarasadkeqfyss----qcaagmcg-
iilgkvkfgl---sgq-i---l----pdedylpggkr--tgall---ftp
flshaie--aql-esvdd-slqhhyv-lksvyypn--s--lleyihl-nt
-vgg--kd-------nala---c--------dhpiyh--------t----
---------l--r-leeyg--ftd-----g----wv--adncg-------
-----pq---gta
>ENV_SIVGB/47-569
---ar---spfqqgq----tvgylail-f--cekfv--akttnyst----
--qylka---rpps----------r---n----------rsiartatchq
qskadlvnccflyacvnkfv------------------tkmscvnpkfgp
sncepshiatksahgkli---rklrlvqftwhvfqqci-smtaigl----
-------adgsltlkglnehlsve-ga--ak-l--g-----rvstfdakg
k--lflgpkila---ckgal-rgkl----lgae------gl--rgw----
ml----aeynk-d-----spqsfgavgrvtrgkhl--------------l
cspisc----lvfqt-------------------------------clsa
lcepcnaeia--pkagrgimmrrgfygstadpflqmcvaplqsrtgr---
---lfggy---lsk------pygglmsivhdkcvarcg----aqa-----
------glgs-egnggalriiavdskvmnaaatsscvllfqkvs------
-----pheffkfneskk---pragq----k----ltcaldvrcklthvas
lv-fnf--pl---hlikkvaar----nfk---dgihd--aqplvpakygf
qv-itdn--iaf-rgakmesngsv-nyadgvftpw--k-gsyk-lelysg
sivh--geggespyv--ipkfrvmpafhdvvvvtvyk--------iykhl
faiqfilmlfsre-llqf--aplk-----geprlwd--assvan------
----tvrpkleke
>node7
---et---gn---ak----tva-----hf--cegfm--ttvkyirtkags
vfvylrevytkkhgkh------cik---a----------pmnskgk----
--ki-----aqlfaceg--cpmids-----------visripsfdgkl--
vdclsrkigaktfsgdlvgvgaallafaf-wd----altnmgpiflngsq
ighahpgi-gglllhlvgvhlink-enlagk-ilyg-----ka------l
k--pflfdsilnigac--vllerkp----gr-k------plsargf----
vskrrgneyqn-v-----keqvagp----------l-------cav-tas
rggdes----lk--vaigt----flppttasklria--------khclqp
l-vgckntig--pqgsvgskivqay-gssdvpflsksv---tthrgs---
---r---y---ltlssfi-rvvkglmd-------cfca----nvp-----
------qvna-dql-------t---ksdkkltvkkcahh----s------
-----acerfsysqg-lrvpgtaaa----t----fps----qcsigmig-
lplagsk-di---am-tr---h----pkpdyntatesgkaeplv---fkp
dsfdatd--ahiwrapdyrnfsae-a-cvtvyyps--gravyk-hry-kt
-ids--gd-------dclr---a--------yqpiyr--------d----
---------l--a-lqdygkkwtd-----g----wy--gshckv------
----vvr---gaf
>ENV_HV2CA/25-512
----w---gn---ag----avi------y--chssp--eeipyvkqrlvk
vlyymneeftkfllgh------qsp---kn-------getlyaksn----
--tm-----pklfagts--ctlln--fskviaprellvikypsfgtkv--
elcsdqkiggkqalgn---sgsslallaf-we----altmklgalv----
-------v-gtillhlqs-h---k-ahvsgk-llsagcnespt------l
p--llraeaiveiskp--pilkpkv----ar-k------pvsaeggadrm
ss----iehvk-v-----dlsvgsa----------v-------cke-pkm
rgcaec----aa--pafa------lapslaslfacr--------kcci-s
----c----v--vvapvstlikael-tgdhvsflmtpg---iksqgf---
---r---n---lylrlfi-dtypgtgv-------vycn---ahiqi-vi-
-aahesnvdt-edl-------a---hgiqvp-v-sikkm----scacgdn
tqkeia--afsfssg-letrsggggraaqdkdqfygd----qcaeglcg-
iilakvkfgl---sgh-i---l----sdedylsggkr--gtvll---fap
flshaie--ael-faldd-plqhhyv-lkslyyps--g--lleyipl-it
-vgg--ke-------eafn---c--------ilpiyh--------s----
---------l--r-leeyg--ftd-----g----wvvatdhcg-------
-----pa---gta
>node18
----w---gn---ag----avi------y--cessv--aeisyvkqrqvk
vfyyvndrftkwllkh------pth---kh-------gqtlytkgn----
--tm-----pklfagtg--ctmlkgqfskviaprellvikypsfgtkv--
ilcsdekigskqvlgd---sgtsllllaf-we----alsmklgvlv----
-------v-gtlllhlqs-h---k-ahvsgk-lltagcvessa------l
p--lfmaediidiskp--pllaptv----sr-k------pvraeggtdrf
ss----nehek-v-----dlkvvsa----------v-------cet-ppl
rgcadc----aa--pafa------lnpalaslfacs--------kccfts
----c----v--lvapvgamisqef-tgdhvgflmppg---krsqaf---
---r---n---lylrlfi-etypgdgg-------aycn----nipiali-
-gs-hspvdt-edl-------a---egvqvp-v-sikhq----ececgdn
agketaclafsystg-lqitsgggarasqdkeqfyss----qcaegmcg-
iilgkvkfal---sgq-i---l----pdedylpggkr--tdvll---ftp
flshaie--aql-yavdd-slqhhyv-lksvyypn--s--lleyihl-nt
-vgg--kd-------nala---c--------khpiyh--------t----
---------l--r-leeyg--ftd-----g----wv--adhcg-------
-----pq---gta
>node10
---gw---gn---ag----evi------y--cessi--aeisyvkqrqvk
vfyyhndiftkwlgkh------pth---kh-------gqtmytkgn----
--tm-----pklfagtg--ctmlkg-------pwqllvikypsfgtkv--
incssekigskqvlgd---sgasllllaf-we----vlkiklgvlv----
-------v-gtlllhlvs-h---k-ahvsgk-llta---essa------m
p--lfmaediidiskp--pllaptv----sr-k------pvraeggtdrf
ts----nehek-v-----dlkvvsa----------v-------cev-ppl
rgcgdc----aa--pafa------lnpalaslfscs--------kccfts
----c----i--lhapvgamisqef-tgdhvgflmppg---krsraf---
---r---n---lelplfi-etytgege-------aycn----niprali-
-gs-hspvdt-eel-------a---egvqvp-v-sikhq----e------
-----aclafsystg-lqitsgggarasqdkeqfyss----qctegmcg-
iilgkvklal---sgq-i---l----pdedylpgver--tdvll---ftp
flfhaid--aql-yavde-stqhhyv-lknvyypn--s--yleyihl-nt
-vgg--ke-------nala---c--------khpiyh--------t----
---------l--s-leeye--ftd-----g----wv--adhcg-------
-----pq---gta
>ENV_HV2NZ/24-502
----w---gn---vg----asv------yslchnsa--eeisyisqrqid
vfyylkerstkfllgh------pthlknkh-------gq-lyakid----
--sl-----pklfagtg--ctllkgefqkgiaprellaiaypsfgtkv--
ilctgksigskqvfgs---gghslallvf-wd----afvmkigvvd----
----------tillclep-a---k-ahisgk-lltagcvekaa------l
psllfiaadivdiakp--rlyaptv----gr-kkdkktgpvrsdggkdra
sp----denqk-v-----dlkvven----------lansspttcet-pqm
rgcasc----ta--palq------lnpalaslfkcs--------kccfts
----c----klhlvspvgalistky-sgdhigylmppg---kksqaf---
---g---nlpelylhlfi-etypgntg-------afcnsat-hipialil
taaqhsnvdtladl-------a---egikvp-a-tikh------cecgen
agkesa---fsfssg-lqinsgggarasqskeqfyad----kcaegmcg-
iilgdvkfml---nge-i---lkakqqdeqhlpggkr--tqmll---fva
flshaie--vel-ygved-slqhhyv-lksvfyan--g--llectgl-at
-igg--ka-------ngla---c--------khpiyh--------a----
---------l--r-lsayg--ftq-----g----wv--edrcg-------
-----pq---gta
>ENV_HV2G1/23-502
----w---gd---ag----evi------y--cessv--adiayckqrqvk
vfyyvndrfkkwllkh------ptf---kh-------gqtmykrgh----
--tm-----palsagtg--ctmikgtfskvitpwelllikcqsfgtav--
ilcsedkigskqvlgd---tgtslllvtf-we----altmklgvla----
-------a-gtlylhlrs-h---k-ahvsgk-vlta-ciessa------l
p--ifmsehiidiskp--pllaptv----sr-k------pvkaeggtdwf
gs----aegek-v-----dlkivsa----------i-------cet-ppl
rgcadc----aa--pafa------lnpa-aslydcshfvdpkhtkccfts
----c----i--lvapvgamlaqdf-tgdhigflmnpg---kksrsf---
---r---n---lylrlfi-qtypgdgg-------aycn----nipfali-
-gs-hspidt-edl-------e---eavqvp-v-s-knq----ecervdn
ngketacllfsystg-lqitggggarahqgkeqfyas----qcaegkcg-
iilgkvkfal---sgq-v---l----rdedflpggkr--tdvll---ftp
flsqaie--arl-yavde-slqhhyv-lknvaypn--s--llgyinl-nt
-vgg--kd-------nala---c--------khpalhpdknqdhrt----
---------l--ralaeyg--fad-----g-----v--edhcg-------
-----pq---gta
>ENV_SIVM1/24-528
---dw---an---gg----hlv------y--censn--aeityvqdrrvg
ifyyht--ftkflakh------kdh---kh-------gqtmhsdgr----
--dm-----pklfagtg--ctml---------pwqvll--------kv--
ihcnsekiglkqllgd---vgagilllaf-we----tlkiklgvkv----
-------v-gtlllhlva-g---kkshvsgrklltk-----sa------l
t--lflaediidipkp--lllartv----gr-k------pvlaeggtkrf
ts----pehah-g-----slkvvha----------v-------cnv-pal
rgcgnc----as--pafa------lelalaskfdcs--------kcclts
----c----i--pdepvgamaseef-ggehvgfmipav---krsraf---
---v---e---lelflfi-etyagqgq-------aycd----niphali-
-gq-hsqldt-eql-------a---esvqvp-v-aikhd----e------
-----aclafsystg-lqitsgsgarpskd----ysn----ncteslcg-
iiigkvklgl---snq-i---l-----eedylpgvdr--tevll---ftp
fyfhaie--pal-falde-nvnnhyp-lksvyypn--s--fldylsy-dy
-tag--ke-------kaqa---c--------yhpfyh--------t----
---------l--s-lqeyp--fsd-----g----wv--gdhcgt------
----vpq---gta
>ENV_HV2BE/24-510
----w---gn---ag----avv------y--cqpsv--aqisyvkqkhvk
vyyyvndrftkwllkh--------h---ikkgailvpgqtlytkgh----
--tm-----pklfatsg--ctmfkgefskvlapkellvikypnfgakv--
ilcsdekisagnvlan---tgtslllfaf-we----avfmklgvlv----
-------v-ttlllh-as-h---q-ghvsgk-lltagcvdsgk------l
p--lfmaeniidisrp--plvvpkv----sr-k------parseggtdrf
gs----kldekgv-----dlnvvsa----------k-------cekappi
kgcadc----aa--ssfa------lapslaslfa-----------ccfts
----y----i--lvapvgamisqef-tgelvgflmppg---krsqaf---
---r---k---lylrlfi---ypghgg-------aycn----klpiagi-
-gg-htpvdt-edl-------p---egvqvp-i-aikyq----scdcgen
agketailafsywag-mhvksgggarqsadeeqffss----qcaagmcg-
illgkvkfgl---sgk-i---l----pdedylpggkk--tgall---f--
flheaie--aqv-epvdd-slqqcyv-lksvyyanrgp--llefkhl-nt
-vag--kd-------naaa---c--------dhpiyh--------f----
---------l--r-leeyg--fya-----g----wv--addca-------
-----pq---gta
>node9
---dw---gn---ag----qiv------y--cessi--aeisyvkqrqvs
vfyyhtdiftkwlgkh------pth---kh-------gqtmhskgr----
--tm-----pklfagtg--ctmlkg-------pwqllvtkypsfgtkv--
incgsekigfkqllgd---sgagllllaf-we----vlkiklgvlv----
-------v-gtlllhlva-h---k-shvsgk-llta-----sa------l
t--lflaediidiskp--lllartv----sr-k------pvraeggtdrf
ts----pehek-v-----elkvvsa----------v-------cev-ppl
rgcgdc----aa--pafa------lepalaskfscs--------kcchts
----c----i--phapvgamvsqef-tgdhvgflvpav---krsraf---
---r---n---lelflfi-etytgqge-------aycn----niprali-
-gs-hspvdt-eql-------a---esvqvp-v-sikhq----e------
-----aclafsystg-lqitggggarpsqd----yss----qctegmcg-
iilgkvklal---snq-i---l----peedylpgvdr--tevll---ftp
flfhaid--aql-favde-nvqhhyv-lknvyypn--s--yldyihy-nt
-vgg--ke-------nala---c--------yhpiyh--------t----
---------l--s-lqeyp--ftd-----g----wv--adhcgt------
----vpq---gta
>node17
----w---gn---ag----avv------y--chssv--eeisyvkqrqvk
vfyyvndrftkfllgh------pth---kh-------gqtlytksn----
--tm-----pklfagtg--ctllkgefskviaprellvikypsfgtkv--
ilcsdekigskqvlgn---sgtslallaf-we----alsmklgvlv----
-------v-gtillhlqs-h---k-ahvsgk-lltagcvessa------l
p--lfmaediidiskp--pllaptv----sr-k------pvraeggsdrm
ss----nehek-v-----dlkvvsa----------v-------cet-ptm
rgcadc----aa--pafa------lnpalaslfacs--------kccfts
----c----v--lvapvgalisqef-tgdhvgflmppg---kksqaf---
---r---n---lylrlfi-etypgdgg-------aycn----hipiali-
-gahhsnvdt-edl-------a---egvqvp-v-sikhq----ececgdn
agketaclafsfssg-lqitsgggarasqdkeqfysd----qcaegmcg-
iilgkvkfal---sgq-i---l----pdedylpggkr--tdvll---fvp
flshaie--aql-yavdd-slqhhyv-lksvyypn--g--lleyihl-nt
-vgg--kd-------nala---c--------khpiyh--------s----
---------l--r-leeyg--ftd-----g----wv--tdhcg-------
-----pq---gta
