>node18
lqvdltelvyivatykgpagct---nepg-------pvlv-----hmcpp
af----------s---elvvgkatfqdycvsafc-l-ws-ydnlghsire
t-sttclhnnsdddh---cdfe------dkcps-----st-skglli---
thdtlgv---nl-a--t---------patalqlptesgkveiavtrlvne
lt---vglsppeayalnq----phl-------svk------ea-ael--q
g----gs---gl---itf-----iq-----kanalrvdetcvfhgdsnca
qvda-----hp---aakhegga-ctlmehakifaknhh-khrqveayccr
grlglc------ngeedsfkeqsqya-cwvlpd----ns-adgqi--lvq
canltad-amgkdireqvlaaykgrw-pa--mqakflndwvwifknckea
mekaekwvp----k--k-afgpklnil------------af-------af
aksgkkgeqella----vrp-cka--mg-adhtd-----ptgyi-fvg--
---------------ekasyhsnyndgrt--ktlg------h--v--atg
avsgsq-----yghg----eerpda----wseal-g--fgivqk--legk
nvnm--vfisvpggplvsergvh-------anginginaklv----qtll
hghtvaagrkrllataagvallraeedgaaktnhgglv-vh
>ENV_HV2G1/23-502
levdvqemvyiaatykgpggcs---nepg-------pvlvktahthmcpp
af----------a---alsvgkatfqdycvsafc-l-ws-ydnlg---rd
t-sstclhnnsddd---------------kcps-----sr-skglni---
thavlga---nl-a--aasdealarypatalqlpiesgkvdeavtrlvpa
lt---vglsppdvyalnq----phl-------svk------dasael--q
g----gs---gt---itf-----iq-----kansfrvnetcvflgdanca
qvda-----hp---aakhdgga-ctmmehakiflknhh-khrqveafccr
gqlglc------dgaedpfkehsqya-cwvlpd----hs-kdgqm--lvq
cadltad-amgkeireqvlaaykgrw-aa--mqakflndwvwlfknckea
mqkaekwvp----k--k-afgtklnil------------nf-------af
aksgkkgeqella----irp-cka--mg-adhtdfdrrnptgyv-fgg--
---------------ekvayhskynegrt--kilv------h--v--atg
alsgsq-----yghg----enrpda----wseal-g--fgivql--leg-
---m--vfis----plvsergv-------------ginaklv----qtll
sghtvaagreqllataegvsllraeedgatktnhgpli-vq
>node9
levdlpellyinavykgpggct---nepg-------pvlv-----hmcpp
al----------l---alvvgkatfesysistfc-l-wa-ydhlghsise
t-sttc---ksdddh---cdfe------drcps-----ss-syglli---
thetlga---sl-s--a---------aatavqlptqsvkvelavektine
lt---vnlgppeayalnq----phl-------tvr------ea-ael--q
g----gs---gl---iqf-----ie-----kanpfdvmetcvfhgdshca
qvna-----hp---vakhegsf-cslmehakifaknhh-khrqveayccr
grvglc------sgeedafn----yp-cwvltd----kn-adgqi--lvq
canlted-amgkdireqvlaaykgtw-ps--mtadflndwvwifneckqa
mqkadtwvp----k--t-tfgpklnil------------af-------af
aktgkkgeqevla----vrp-ckp--kg-tdhte-----ptgyskfvg--
---------------ekgpchanfndgrt--ktlg------h--v--atg
avggvq-----yghg----gerpni----wseal-g--fgvvqk--legk
nanl--lfit----plvsgrgvh-------asgilgqnlklv----qtlv
hghtvaegrqrllattagvallrteedgaaktnhggli-vh
>ENV_HV2BE/24-510
lqvdltelvyivagykmaagct---sepg-------pllv-----hkclp
af----------s---elvvrkatfddycvaafc-l-ws-ygnhahsvre
t-sttclhnnsdndh---ceie------dkrps-----st-ekgmli---
shdtlnv---nl-a--s---------peaalqlpteagkaevavtrlvke
lt---vglsppeaynldl----phl-------svk------ta-adl--q
g----gr---gl---isf-----it-----krtslkvdetcvfhgdsnca
qhsaygd--qp---aannegge-stlmehakifanyhh-khrqvnaycck
grlglc------ngeadsfgdhaqyg-cwvlpd----ns-qdgqv--lvk
cenltpe-amgknirdevlavyngrw-pa--meakflndwvwpfkncega
metaekwvp----n--kiafgpqlnil------------kf-------af
aqsekkgkqella----vrp-ina--vg-lehkd-----ptgym-fvg--
---------------dk-gyvsnyndgrk--ktlg------k--i--atg
avggsq-----y-hg----edrpda----wseal-g--fglvek--laek
nvsm--vfisvpadplvsergvq-------a-----lndklv------ll
hthtvaagrkrllatgagaal--akeegnaktdngglv-na
>ENV_HV2CA/25-512
vsvd---lvyvvatyrgpagct---depg-------pvlv-----hmcpp
af----------s---qlvlgkatfqdwcaspfg-l-ws-fdnlghsird
t-sttclhntsdedhasicdfe------dqcps-----st-smgllv---
tqdtlev---nl-a--t---------ppialqlptesgkveiavarfvne
ls---vgls-pepyalne----phi-------rvkakesdhea-aeq--q
g----gs---el---vgfrasyfiq-----kadelrvdeqctfqggsgca
pvda-----ep---aaknasgy-ctlmehgkifaknhh-rhr-veayycr
grlgvcglsvfelg--dsfkeqsqfgycwvkpd----nt-adgqi---vq
ccnitad-efglderaqimaaykgrwise--mqamflkdwvwifknckea
gdkadksvp----k--k-afspqlgil------------af-------ef
aksvktgeqelvt----arg-skapgmg-aattd-----ptgyv-fvg--
---------------eaisyhsnynggrt--kilg------h--l--atg
aisgga-----yghg----eerpqg----wpeal-g--favvqn--legk
--ni--vfisvpgsplvsergaa-------vnginavegklv----etlq
hgntaaagkkkllakgggaavlkaaedgaadtnqggli-vh
>node19
lqvdltelvyivatykgpggct---nepg-------pvlv-----hmcpp
af----------s---alvvgkatfqdycvsafc-l-ws-ydnlghsire
t-sttclhnnsdddh---cdfe------dkcps-----st-skglli---
thdtlgv---nl-a--t---------patalqlptesgkveiavtrlvne
lt---vglsppeayalnq----phl-------svk------ea-ael--q
g----gs---gl---itf-----iq-----kanalrvdetcvfhgdsnca
qvda-----hp---aakhegga-ctlmehakifaknhh-khrqveayccr
grlglc------ngeedsfkeqsqya-cwvlpd----ns-adgqi--lvq
canltad-amgkdireqvlaaykgrw-pa--mqakflndwvwifknckea
mekaekwvp----k--k-afgpklnil------------af-------af
aksgkkgeqella----vrp-cka--mg-adhtd-----ptgyi-fvg--
---------------ekasyhsnyndgrt--ktlg------h--v--atg
avsgsq-----yghg----eerpda----wseal-g--fgivqk--legk
nvnm--vfis----plvsergvh-------angilginaklv----qtll
hghtvaagrkrllataagvallraeedgaaktnhgglv-vh
>node11
lqvdltelvyivatykgpggct---nepg-------pvlv-----hmcpp
af----------s---alvvgkatfqdycvsafc-l-ws-ydnlghsire
t-sttclhnnsdddh---cdfe------dkcps-----st-skglli---
thdtlgv---nl-a--t---------patalqlptesgkveiavtrlvne
lt---vglsppeayalnq----phl-------svk------ea-ael--q
g----gs---gl---itf-----iq-----kanafrvdetcvfhgdsnca
qvda-----hp---aakhegga-ctlmehakifaknhh-khrqveayccr
grlglc------ngeedsfkeqsqya-cwvlpd----ns-adgqi--lvq
canltad-amgkdireqvlaaykgrw-pa--mqanflndwvwifknckea
mqkaekwvp----k--k-afgpklnil------------af-------af
aksgkkgeqella----vrp-cka--mg-adhtd-----ptgyi-fvg--
---------------ekasyhsnyndgrt--ktlg------h--v--atg
avsgsq-----yghg----eerpda----wseal-g--fgivqk--legk
nanm--vfis----plvsergvh-------angilginaklv----qtll
hghtvaagrkrllataagvallraeedgaaktnhgglv-vh
>ENV_SIVGB/47-569
kavqsaqmiy---deadkdkml---plaq-----fqnlie------vhpk
vpaidralrrcev---tvldv--------kndtc-lpw--ldqnghr---
----vv---kgsmdg---chfe------tlaq-------q-gtpfar---
apvkfqh---tlrpgki---------dygaiphst----tnfpkfgpvsq
-h---fls----gy-isidarv-fg-------ses------ge-geimks
e----vgngagv---etf-----lntkceifvlhlttteicqiqaeh---
-ika---nrql---ikkqrlrfqcktskdigm---gpmptrrgs------
-t---c----------avlg----yw-mwvvydlperqq-ghgpvkpglr
cdtikqkaalgv-------vagevn---l--vlrsflkeyqwlyqgclve
l---sgwikrgras-kg-g---klpvq------------a----------
-k-----epdtltatykqaglcts--rgssqqdl-----hp-yg-yktsl
hpv------lsy---------nymntdpnqgkke----------------
---swhlvtgdygev----kerdsayafvwdqhitashttslrigivgpl
tav---lfla----py---pasqvi-----gfvaqqnn---ffpyidpvv
qsl---egv----ltkagasktgkt---trtyhkstfq-vd
>node7
ravdlpetkyt------plgclipgggndvetanyapil-------gcp-
ea----------i---allag--------kgnec-kpw--i---gtsi--
---tan---tlnddn---cnfe------iqskg-----ss-segyli---
chgtlet---kl-t--p---------sksaeqnptvgvhnqfsqlvpird
ls---fkdgfpstyavsv----pdl-------tqt------et-ldl--p
g----gg---ai---lef-----ge-----yvkvlqiiaicsvpaes---
-vki---kthp---vakhqlvf-crladngeifvkghi-thkev------
-pvdvc------vsedavfr----yy-pwvvfdlskkkp-gkgrv--giq
cdvlnqr-qlnpdargqmvagykts---a--vtadfvkdwgwifegcsqs
i---aewvt----kfth-tfqprla-------------------------
ak-------eama----pdp-ckp--rg-sehdq-----tseys-fvkgh
svs------sey--lqkgkcqaygtvgrtgskala------q--l--gag
iiggav-----ygegkllrgekdsv----wpqqlsg--ngvayt--lepk
tdyf--lfls----gt-iamdltel-----aaakvgma---a----kali
hgk---nghhkqlkttagvdrgrkqsrgevkthkgsvg-vd
>node17
lqvdltelvyivatykgpagct---nepg-------pvlv-----hmcpp
af----------s---elvlgkatfqdycaspfc-l-ws-fdnlghsire
t-sttclhnnsdddh---cdfe------dqcps-----st-skglli---
thdtlgv---nl-a--t---------paialqlptesgkveiavtrfvne
lt---vglsppepyalnq----phi-------svkarevshea-ael--q
g----gs---gl---igf-----iq-----kanalrvdeqcvfhgdsgca
pvda-----hp---aakhegga-ctlmehakifaknhh-khr-veayccr
grlglc------ng--dsfkeqsqyg-cwvlpd----ns-adgqi--lvq
canltad-amgkdireqvlaaykgrw-pa--mqakfladwiwifknckea
mekadksvp----k--k-afgpklnil------------af-------af
aksgkkgeqellt----vrp-cka--mg-adhtd-----ptgyi-fvg--
---------------eaasyhsnynggrt--ktlg------h--v--atg
avsgsq-----yghg----eerpda----wseal-g--fgivqk--legk
nvnm--vfisvpggplvsergvh-------anginginaklv----qtll
hghtvtagrkrllataagvavlraaedgaaktnhggli-vh
>ENV_HV2NZ/24-502
lsvdltsevyivatykgpaecs---gepg-------pvlv-----hmcpp
vy----------s---elvigkatfqqycaapfc-l-wsyfvnlghskre
t-sttclhnhgdddp---cdfsprvleyeqcatgtdlgst-stgllirem
sndtlga---nl-a--t---------prialh------kneiavtrfvne
lt---vdlsppeqyelnq----phi-------sikayevshga-egl--k
s----gs---gl---igf-----iq-----kahnhrvdqpcvfhgeseca
pvnt-----hp---aakhegga-cvlmphsglfaknhq-khk-veayccr
arvglc------lg--ddfkvqsnfg-cwvlen----ns-atgqv--flh
cakltad-nmgkdiseqvvtackgrw-ps--mqtkflanwiwlfksckea
meksgksvp----k--q-sfgpklnim------------afgaghtdmaf
akngrvgeqellt----vra-cka--mg-anhkd-----ttgyi-fig--
---------------daasyysnysdgrt--ktlg------n--v--atn
avsgqq-----ygng----eehpea----wsdal-g--fsivqk--lege
nvnm--gfisvpggplvsdrgvh-------angidhadaklv----esll
ighdvtpgrkrfiavaavfamlrakeddaaktnyggl--vh
>node8
kavdlpetlytqqnykspggcl---senn-----yapilv------vcpp
ea----------i---alvtg--------kgshc-kpw--idqhgqsi--
---taa---kpnddn---cnfe------iqskg-----ss-segyli---
ahgtldt---kl-t--a---------tnnaeqmptigvhnqfartvpird
ls---fnsgppaayaist----ppl-------tet------en-lel--p
g----gs---ai---ief-----ve-----yvnvleiiavctvpses---
-vki---kphp---vakhqlvf-crlpddneifvkghv-thkev------
-rvnvc------gsddavfg----ys-pwvlfelsakks-gegrv--giq
cdvlnqr-eldgdargqliaaykgs---s--vtadflkdwgwifegcsqt
l---aewvs----k-th-tfeprlnil------------iy--------f
ak-----dqevma----aqp-ckp--rg-sehnq-----asgya-fvkgh
svs------kdy--lekgpchaygtvgraggkala------q--l--pag
ivggav-----ygeg----gerdnv----wsqqlsg--ngvank--lepr
tdsf--lflt----si-kamdlqev-----asailavs---f----ktli
hgk---eghqrqlkttagvnlgrkesrgavkthkgtvd-vh
>ENV_SIVG1/22-522
rp-dlpttryt------plgclvpgggndietanyapil-------gcl-
ea----------i---allag--------kgnec-kpw--i---gtsi--
---aan---tltddd---cnfe------iqskg-----ps-segyli---
chgtlet---kl-y--p---------sksaeqnptggvksqtaqlipird
lc---fkknfpstfavsv----pdl-------tqt------ek-ldl--p
g----gl---ai---lif-----ga-----yvkilqiivicstpaeg---
-pki-------------hplvf-crlaghgeifakghl-tkkev------
-qidvc------vsedavfr----yy-pwvvydlakkklcgkgrv--gvq
cdvfdqr-nlnpdarsglaagykts---a--vaadyvldwgwildgcsrs
l---qewvt----kfth-tfmprna-------------------------
ak-------iamv----pdp-ckp--rs-fqhdq-----tsdys-fvkdh
svs------se---lekekcqtygtvgrtgskana------qigm--gag
-iggav-----ygeakllrgekdsv----wpqqlsg--savayt--lepk
tdyv--lfll----gt-kagdlse----------vama---g----ktli
ngk---nghhkelkqsagddrgknqsrgdvkthigtvg-vd
>node10
lqvdltelvyivatykgpggct---nepg-------pvlv-----hmcpp
af----------s---alvvgkatfqdycvsafc-l-ws-ydhlghsise
t-sttc---ksdddh---cdfe------dkcps-----sa-skglli---
thetlga---nl-s--t---------astalqlptesgkvelavtkline
lt---vglgppeayalnq----phl-------svr------ea-ael--q
g----gs---gl---itf-----iq-----kanpfkvmetcvfhgdsnca
qvna-----hp---vakhegsa-ctlmehakifaknhh-khrqveayccr
griglc------ngeedafk----yp-cwvlpd----kn-adgqi--lvq
canltad-amgkdireqvlaaykgrw-pa--mpadflndwvwifknckqa
mqkaekwvp----k--k-tfgpklnvl------------af-------af
aksgkkgeqevla----vrp-ckp--kg-tdhtd-----ptgyi-fvg--
---------------ekgsyhtnfndgrt--ktlg------h--v--atg
avsgvq-----yghg----eerpdv----wseal-g--fgivqk--legk
nanl--vfis----plvsgrgvh-------angilginaklv----qtlv
hghtvaagrkrllataagvallraeedgaaktnhggli-vh
>ENV_SIVV1/24-538
ra---petkym------plsclcpgggdnvtlmiyapil-------vcp-
ea----------i---ailva--------rggec-eq--------tgi--
---tin---plndan---cefh------tqskg-----satseryln---
chgtlkagirkt-t--p---------ttsadqppsagkhnrfsqlva---
------kagfpa--nvna----tdlapggrlltap------da-ldl--p
gqfdfgg---ae---adf-----ad-----yvkvlaiinicsvpaas---
---i---kthp---vnkhklvf-crlanvneifvsgfl-thvek------
-pvdvc------vnedvvqr----nf-pwvvfnmskkkp-gkpkv--gvq
calnsrt-qlnpdpsgrrqagclsw---pdnvalslpkdwnwifeacaqv
i---gdlva----dftd-s--arla-------------------------
s--------dkmg----cdp-cks--ks-ae--q-----aseys-yvkgq
kvsyfcaag-sflplqkdkcqiygtvgragnkama------e--lqdgvg
llgatv-----tgdgkllrgek-------wpqklhg--dgvayt--lvhl
edli--mfks----gt-ealglskqadefpaeandgma---a----ksie
pgk---knhnnqlkltqtngrkrnqgrgkgnnhkasvg-vg
>ENV_HV2D1/24-501
lqvqltelvyiitkykgpagcs---kdpg-------avlv-----elgpp
af----------s---elvvgkatfqdycvqafc-l-ws-ydhlahsire
t-sttclhsnkdddh---cefe------hkr----------pkglli---
shdtlgv---nl-a--t---------qatalqldtesgkagiavtrlvne
la---vglsppdayslsq----pql-------vik------ea-eem--a
g----kr---gl---vtf-----iq-----kanallvdetcvfhgetnca
qvkk-----he---aanheggp-stlmdhakifakyhh-khrevqayccq
grlalc------sgeetrfgdesqfa-cwvapm----ns-adgqi--lmk
canvtad-gmgkdir--vlaayngrw-pa--mdpkfvndwvwffkeckea
mekvekysp----k--k-afgpklnil------------af-------af
gksgkkgkqplla----vsp-ska--mg-anhtd-----praym-fva--
---------------nkqsyngnyndgra--ktia------h--v--aag
svsgs-------ghg----edrpda----wseal-g--fgiiek--laek
nvnm--vfisvqagplvsergvh-------a-----invklv----qill
hghtvaagrdhllptgagvellkadqtgvaktdngglv-dq
>node14
lqvdltelvyivatykgpagct---nepg-------pvlv-----hmcpp
af----------s---elvvgkatfqdycvsafc-l-ws-ydnlahsire
t-sttclhnnsdddh---cefe------dkrps-----st-skglli---
shdtlgv---nl-a--t---------patalqlptesgkaeiavtrlvne
lt---vglsppeayalnq----phl-------svk------ea-ael--q
g----gr---gl---itf-----iq-----kanalrvdetcvfhgdsnca
qvda-----hp---aanhegga-stlmehakifakyhh-khrqvqayccr
grlglc------ngeedsfgdqsqyt-cwvlpd----ns-adgqi--lvk
canltad-amgkdireqvlaayngrw-pa--meakflndwvwffknckea
mekaekwvp----k--k-afgpklnil------------af-------af
aksgkkgkqella----vrp-cka--mg-adhtd-----ptgym-fvg--
---------------dkqsyhsnyndgrt--ktlg------h--v--atg
avsgsq-----yghg----eerpda----wseal-g--fgivek--laek
nvnm--vfisvpagplvsergvh-------a-----inaklv----qtll
hghtvaagrkrllatgagvallraeedgaaktdngglv-nq
>ENV_SIVM1/24-528
levdlpellyinavykgpggct---nepg-------svlq-----hlcpp
al----------lkypslvvsratfesysissac-l-wa-ydhlghsire
tvgttc---ksdddh---cdfe------drcps-----gs-ly--li---
tnellgn---sl-s--g----------attvhlpthsvkvdisvkkaidd
ltfgrvnlgppdafalne----phl-------tvr------ea-ael--q
g----gs---el---iaf-----ie-----kadpfevmetcrfhgdshca
mvga-----qn---vvrekgtf-cslmehakifaknhh-thrqveayccr
grlglc------sgeeeafn----yp-cwvlad----ks-adgki--lvq
cgnlted-avskdvkeqvlaaykgtw-ps--mnadflndwvwifneckiv
mqkhetwvs----k--t-tlgpkmsil------------an-------af
nktgkkgdqavla----arp-ckp--kg-tdhte-----pydysnfvg--
---------------ekgpchanfnegrt--kslg------h--v--aag
avggvq-----yghg----geranv----wpeal-g--favvqk--leek
tanlkyyfit----plvsgqgvh-------asgilgqhlklv----ltls
hghtvatgkqrlfattagvallrteeagvaktqhggli-vv
>ENV_HV2D2/24-513
lqadltelvyivatymgpgnat---nep--------pavi-----hmcpp
af----------s---alvtgnatfqeycvdafctl-ys-cnhrdishae
t-stac---ssttdh---cdla------dkcps-----ag-nrgllv---
---tlga---kl-r--t---------hstvl------arvemtvtrline
lr---l-----egyaldn----phl-------cvr------ea-agl--q
g----gs---glawyitf-----iq-----kdnqfnvmetcvihsyknca
qvna-----hpvlgvgkhnqgv-cvlmehdkifakthh-kqrviganccr
arvgfc------hneedsfq----yp-cwvlsd----kn-vgggi--lvq
caavttd-algknirdqvlraykgsw-pa--lpaeflldtvwifkhcpqa
lrkaqkwip----k--k-tlgtslnvlasrhfhivftfaaf-------sf
aksstkgdqevla----vsp-ckp--rs-ceftd-----pvgyi-fvs--
---------------nkkeyhtdfnegrs--knlglkvytkh--g--atg
aisgve-----yvhg----eerpnv----wsedl-g--dgiirk--legr
nany--vfis----plvapggvn-------anailglnaklv----qaev
hhhvvapnrkrllatpadcalvraeedgagkvnhggiildh
