>node17
parvfv---svsfhsqq---gvfkh-----ggpherasgsffndakkntn
lakgvphpga--icvgcqcsyyn--fhmditdradmlkkrlpsava--gk
lpsiaignwnagtsssdvtwhcgq---yvispkpngtqk--------pep
kqsl--cksakdvvqeiegckgs---leyl--d---fdikege---kvss
evdyfmfspqqgemthtttadlhtahq-prtl----ktvyglfagrahna
spcakvavynepsikv----weiqytclpc---qdfipvaapedqreddr
g-ltkpc--fqllmeclrettihlratgpcet-kcadantkpkcacapvi
plvyv-lllavvltkqh----ym----------gpyrpkvs--kgecdhe
kkk--kmlksakpghlva---------passrgtlvdypg--kmkclct-
-----gyyhpkgekhkvlfvgk---imdpdvcdh-----------kegg-
eem-tfykkegeylrvlayra------------cgvfngsseegm-----
--lqkkmfp-----p-k----fll-cfttstnslkl----w-qc----hl
--wrtpevnqrsvad-vcldck--v-dplspaf-sphql-krikff-ska
gl--ndkri-slw
>node9
---------sesfhsqq---gvfkh-----ddahdsasgsffndvkkntn
lakavphptapevcvgcqcpyyn--f--dvtekidmlkkrmpsava--gk
ipslaigiwhagtsaadvdwhcgq---yvvspkpngaqk--------pqp
kksl--cksakdvv----ackds---lkyl--d---fdirene---kvts
eegcfmwspqqgekphttipdlhtahq-tktl----ktt-glfagrahaa
spcakvtvysepkikv----weilytclhc---vdfippappedqrkddr
g-ltkpc--fq---kclreytvflratgpcst-kcadantkppcdcapvv
plvyh-tllavvpttnqlrnsym----------gtyrpkvs--kaecnhe
rkk--dvlksakpghlvk---------pssyrgtladyag--astclct-
-----gyyqskgakhavlfvgs---ildpdicdh-----------kegg-
edf-tyynkdgqylkilayra------------cgifngsdeegm-----
--lqkkmfp-----p-k----fll-pftlstnslkl----w-qc----pl
--wrtpevnqisvad-vcpdck--i-eplspkl-sphql-krvkff-tka
gp--ndkki-nlw
>ENV_HV2BE/24-510
phrvfl---sesfnshq---gvfkhdqwkrgdpherakgkffndgkkntn
lakav----------gcqcsykn--frlddsntaeilkkklpaava--gk
irsiaignweagtssanptwqctq---yvispklngtqk--------pqp
kqtl--cknakelvqeldgckds---lsylg-d---fdikedt---kvds
eedtfmfnpqqgekaqsatadlktahq-prtl----ktpheffptrtqaa
spcaqvsvysapnikv----kerqytclpc---qdfipiaapedqrdddk
g-laspc--fq---nctrattihlratgpces-kcaesntnakcgaaprv
pllfnrlllavtltknr----yl----------gpfrpkve--kgecnhp
kkk--kmlhsasqghlvk---------pasqrgtlvdype--glkslct-
-----gyyqpkgkkhkvlyvgs---vmdpdvcd-----------------
--m-stykkdg-ymrvltysa------------cgtlnvseeegv-----
--lqkrafp-----p-k----fll-gfttstnsigl----w-qc----hl
--wrtpqvgqrpvae-vcmdck--i-qpispaf-spdql-rrikff-gra
-----dkraqslw
>ENV_SIVGB/47-569
---------ndtaqklaht--paem-----rcs----------ks-----
v------------tiscvfayvwehv--afsg---kksksvsaqvg--dh
r-----------------asacank--ehdeav--pgsa--------tee
erayqvp--------------svasknlsl--t---nagknks---lcqs
gsatydwaasfphnaltalkeahkhpa-tgvl----ltv-n-vtstgkit
eqfvkwllfslkavgsiwniwgig--cvac---ifndtseqk------ek
g-htegspkk---------dvmltkenlda---lkq-t----sssrlkrk
---------kftqmgqg----stil------nca--ktransg--kc---
-rheenyskak---iwekeadcsqtds---skgswaggng--lvscvdl-
-----syearqkkl--glyvtk---eklakk---------------acs-
antvtdnvg-khyntnvlysvkypwfatsseea-glf---gva-l-----
--------kdkvyas-h-----------------lpavadw-acmfakpr
qksedspielggct--------svhngglfdkk-lerlk--rkaa--v--
gt--kd----efl
>node10
---------sesfhsqq---gvfkh-----ddahdrasgsffndvkkntn
lakavphptapeicvgcqcpyyn--fhmdvtekidmlkkrlpsava--gk
ipsiaignwnagtsaadvtwhcgq---yvispkpngaqk--------pqp
kksl--cksakdvveeieackds---lkyl--d---fdikede---kvss
eegyfmfspqqgekphttipdlhtahq-pktl----kttyglfagrahaa
spcakvavysepkikv----weilytclhc---qdfippappedqreddr
g-ltkpc--fq---kclreytihlratgpcet-kcanantkpkcdcapvv
plvyh-tllavvlttqh----ym----------gtyrpkvs--kaecnhe
kkk--kmlksakpghlvk---------pssyrgtladyag--kskclct-
-----gyyqpkgakhavlfvgs---imdpdvcdh-----------kegg-
edf-tyykkdgqylkilayra------------cgvfngsdeegm-----
--lqkkmfp-----p-k----fll-sfttstnslkl----w-qc----hl
--wrtpevnqrsvad-vcldck--i-dplspdl-sphql-krikff-tka
gl--ndkri-nlw
>ENV_SIVV1/24-538
---------qdlrnndv--aglvth-----eghsknaip--ftkvsgnay
vtkttneeefeeccigcefpyyg--p--tvtqtihk-gkhmpeavafvgs
c-----------------gwqcsqmkcekvtps--gkqa--------tet
rref--f--------------dr---akyl--d---ctirnks---kceg
gdtcfswgdhvetepatslstlgktqs-vrgm----ktl-svfmshsh--
-pckqliylcehvvpsawlhygtc--csecicspgysgsagh-dgnsseh
ikfakac--f---------ttvlakpgndcgd-rgregsrtsnhmcakki
---------chvpscaqilnqqnffvgghvgpqgmykprgal-kgvs---
-le--dplkpa---iwfk---------ledyqgswenkag--ggncvsle
de-s-cnyvtenki--slavatgcwlkqhnq---------------ssga
eqs-nfypk-qaytpelaylavyagfsg---etvell---geegk-----
--------sakrfyk-k----vlrqrvvqtvnrirtt--gw-dc----gh
--wkeseaeeap--------------splnggp-gphllwlpvryqgn--
gpsspekad-tpf
>node8
---------tdmshsev--davltr-----egghdneip--ftkvkgntn
lakavphpeaeecctgcefpyyg--l--nvvqsidklgkampgave--gs
v-----------------dwpcsqmscetvspi--ggqk--------aqt
rref--c--------------ar---akyl--d---ftirekn---kcaq
geacfawgpqvgansatnipdlhaehq-tkgl----rti-vlfmgrthat
apciklvffcqhkvgaawlhwgic--cvlc---vqyepsdgh-dakkaer
g-fakgc--f---------ytvlikptgkcsd-kcteaarnpsaqcsrri
---------chvppctqvlanpmflastevsphgmykskgsl-kpkc---
-kd--dalkta---lwik---------iddfkgpwadkag--agtcvsl-
-----cyyvsensm--alfvgr---iklpdv---------------acg-
dds-tsysk-haydailaykavynwfas---eecgif---geesm-----
--------parifys-k----imw-qtvqtvnnlraavgaw-ec----ah
--wrhseveeasva----------h-nplspkl-aphlllvpinyytt--
gp--gqknt-tll
>node11
parvfv---sesfhsqq---gvfkh-----gdaherasgsffndvkkntn
lakavphpsa--icvgcqcpyyn--fhmdvtdridmlkkrlpsava--gk
ipsiaignwnagtssadvtwhcgq---yvispkpngtqk--------pqp
kqsl--cksakdvvqeieackds---leyl--d---fdikede---kvss
eedyfmfspqqgekthttipdlhtahq-prtl----ktvyglfagrahaa
spcakvavysepkikv----weiqytclpc---qdfippaapedqreddr
g-ltkpc--fq---eclrettihlratgpcet-kcadantkpkcgcapvv
plvyh-lllavvltkqh----ym----------gpyrpkvs--kgecnhe
kkk--kmlksakpghlvk---------ppssrgtlvdyag--kskclct-
-----gyyqpkgakhkvlfvgk---imdpdvcdh-----------kegg-
eef-tyykkdgeylrilayra------------cgvfngsdeegm-----
--lqkkmfp-----p-k----fll-sfttstnslkl----w-qc----hl
--wrtpevnqrsvad-vcldck--i-dplspaf-sphql-krikff-ska
gl--ndkri-slw
>node7
---------rdmrhgev--dgvlth-----egnhdneip--ftkvkgnty
lsktvphaefeecctgcefpyyg--l--nvvqsidklgkampgava--gs
c-----------------ewpcsqmkcetvapv--ggqq--------vqt
rref--c--------------ar---akyl--d---itiknkq---kcaq
gdscfgwgphvepnaatsisnlrkqhq-tkgl----ktl-alfmarshat
apcrkliflcqhkvpaawlhwgtc--cvlc---pqyapsdgh-dgktser
g-fakac--f---------ntvlakpggncsd-rareasrnpksvcsrqi
---------chvpsctqvlseplffagadvsphgmykpkgsl-kpgc---
-vd--ealnta---lwfk---------iddfkgswankag--ggtcvsld
kkva-cyyvsensi--plfvgr---lklpdv---------------acgn
eds-nlyak-naysailaylpvyswyas---etcgvf---geesk-----
--------sarrfys-k----ilwsrsvqtvnnirasvggw-ec----gh
--wrdteteeasvg----------h-nplnpkl-pphllwlpvnyymn--
gp--cqknd-tpf
>node14
parvfv---sesfnsqq---gvfkh-----gdaherakgkffndakkntn
lakavphpga--icvgcqcsyyn--fhmdvtdsadmlkkrlptava--gk
ipsiaignweagtssanptwhcgq---yvispkpngtqk--------pqp
kqsl--cksakelvqeiegckds---lsyl--d---ydikede---kvss
eedyfmfspqqgekthtttpdlktahq-prtl----ktpyelftsrahaa
spcakvsvysapkikv----weiqytclpc---qdfipiaapedqreddk
g-ltkpc--fq---nclrettihlratgpcet-kcadantkpkcgcapiv
plvyh-lllavvltkqh----ym----------gpfrpkvs--kgecnhp
kkk--kmlksakqghlvk---------pasqrgtlvdypg--kmkslct-
-----gyyqpkgakhkvlfvgk---imdpdvcdh-----------kegg-
eem-tyykkdgeylrilayra------------cgvfngsseegm-----
--lqkkmfp-----p-k----fll-sfttstnslkl----w-qc----hl
--wrtpevnqrsvae-vcldck--i-dplspaf-sphql-rrikff-ska
-----dkri-slw
>ENV_HV2D1/24-501
pgkvfv---seaftsee---gvfkh-----gdqherakgkffhdakkntn
lskavphrga--icfgcqctfyn--fhkdvtdsadmvkkrlptata--gk
ip-------eagtssanqtahcgq---yiispkpngaqk--------pqp
krsl--cksakelvqeiegckds---hsyl--d---ydikede---kvss
eekyfmfspqqgekthttapplktlhs-prtl----rkpyelftsrahge
apcakmavysapklkv----weiqyaclpc---qdf-hvaaaedqreddk
g-ltkpc--fq---nclrntsiklratgpcet-pcadantkpkcgcapnv
qlvyh-llfavvltklh----hl----------gqfrpkvs--kgpcnhp
kkk--kmhksvkqghlvk---------pasqkgtlvdypd--nmkslct-
--------qprgpkhkvlfvgr---imdkdvcdh-----------kedv-
edp-tyykkdgeylrilayra------------cgvfigsceegm-----
--lqkkvfp-----p-k----fll-afttstkslkl----w-qc----hl
--whtpevnqksvai-vcldck--i-dplspaf-sshql-prinff-smp
-----dkri-slw
>ENV_SIVM1/24-528
---------sgsfhsqg---gvfkh-----ddshdgatgaffndvkrntn
lakalphptapevcvgcqcpyyn--f--ehtekiealkkrmpvava--gr
vpglaigiwhagasaaevdwhcgq---yvvspkpagdqkwkcfacvqshp
kkgl--vksakdvv----acsda---lkyl--d---seirene---nass
eegcfvrspqqgekppstirelhtaqqgshtl----ktt-glfsgrfkaa
spcaqv---sdpkikv----weilyiclhc---vdfippqppederkeer
g-lskpc--fq---hclreysvflratgpcpt-kcrdantkppcdcapvv
plvyh-qlltvvptttdlrssyl----------gtlrplvs--kaecshq
akk--dv-kspm--rlvk---------pssyrgklsdyag--easclcs-
-----afyqskgakhavafvgt---il-pdicqhslyrkrqfkvskegf-
edf-tyynkdgqylaflayra------------ceifngsdaegi-----
--lrnkmfq-----a-k----flf-tftlstgalkl----w-qc----pl
--wrsqeinqasvqd-vctdck--i-eplspkv-spqqi-krvkff-tka
gp--ndkgt-slw
>ENV_HV2NZ/24-502
pawvfv---slsfhsqk---gvfth-----eapherssgsffnnskkntn
mlsavprpga--icvgclcsyyn--fnmditnradmlkkrmpsaai--gk
lptipignwgagtsasdvlwhagq---yvispkpngtqk--------pep
kqdl--cvsskdvvqeiegckgs---leyl--d---fdttege---kvss
qieyfmfspqqgevkhttttelttahq-pstlekgqktvyglfaakahka
sicakvsvynepslkv----seiqytclp-------ipvaapeavsdedr
g-ltkpc--iqllmqslreipinlratgpcet-k-adantkpthacaqmt
plvyv-lllavvltrqh----ym----------gpyrskdt--kgecdhe
kkk--kmlksgkpgslma---------avssrsslvdlpg--kfkclat-
-----gyyhpkgekhrvlfvgk---vmdpnvcdh-----------kega-
eem-afynkegeylrllayrd------------cgvfngsseegr-----
--lqkkrfp-----p-klnhrfvl-cittstnslkl----w-qc----hl
--wrkpevnqrevanvvvlqck--v-nplsdafisdhel-kaikfi-nnp
gl--ndkri-siw
>ENV_SIVG1/22-522
---------rdirhgel--nailth-----egdhdneik--fnkvkdnty
lsktvphaeieecctgcefpyyg--l--nvvqsvdklgkampgave--gs
c-----------------ewaccqmkcntv-ps--ggqq--------vhs
rkef--c--------------gr---akyl-td---iteknkq---kc--
-dscfgrgthvatkditsvsrlrkqhq-tkgl---------lfmakahat
spcrkleflcqhkvpaawnhwstc--cvlc---pqyapkdgh-dgk----
--farac--l---------ntplskrgglckd-rnregsrnaksvcsrst
---------vqvpsctqckseplfnkgadvtphgmykpkas--kpgc---
-vd--ealava---lwfk---------iadfksswankdg--ggtcvsld
keva-ifyvsensi--plfvnr---vnlpdv---------------acgn
eqg-nlyak-ngysatlaflpaaawyas---etcgsf---geesk-----
--------sarrfys-k----ilksrsvetvhnipasvgaw-ec----gh
--rqdtdtdegtvg----------h-kplnpkl-pnhllwltvfyyln--
gp--cqknd-tpf
>node19
parvfv---sesfhsqq---gvfkh-----gdaherasgsffndakkntn
lakavphpga--icvgcqcpyyn--fhmdvtdradmlkkrlpsava--gk
ipsiaignwnagtssadvtwhcgq---yvispkpngtqk--------pqp
kqsl--cksakdvvqeiegckds---leyl--d---fdikede---kvss
eedyfmfspqqgekthttipdlhtahq-prtl----ktvyglfagrahaa
spcakvavysepkikv----weiqytclpc---qdfippaapedqreddr
g-ltkpc--fq---eclrettihlratgpcet-kcadantkpkcgcapvv
plvyh-lllavvltkqh----ym----------gpyrpkvs--kgecnhe
kkk--kmlksakpghlvk---------passrgtlvdyag--kskclct-
-----gyyqpkgakhkvlfvgk---imdpdvcdh-----------kegg-
eef-tyykkdgeylrilayra------------cgvfngsdeegm-----
--lqkkmfp-----p-k----fll-sfttstnslkl----w-qc----hl
--wrtpevnqrsvad-vcldck--i-dplspaf-sphql-krikff-ska
gl--ndkri-slw
>node18
parvfv---sesfhsqq---gvfkh-----gdaherasgsffndakkntn
lakavphpga--icvgcqcsyyn--fhmdvtdradmlkkrlpsava--gk
ipsiaignwnagtssadvtwhcgq---yvispkpngtqk--------pqp
kqsl--cksakdvvqeiegckds---leyl--d---fdikede---kvss
eedyfmfspqqgekthtttpdlhtahq-prtl----ktvyglfagrahaa
spcakvavysepkikv----weiqytclpc---qdfipvaapedqreddr
g-ltkpc--fq---eclrettihlratgpcet-kcadantkpkcgcapvv
plvyh-lllavvltkqh----ym----------gpyrpkvs--kgecnhe
kkk--kmlksakpghlvk---------passrgtlvdypg--kmkclct-
-----gyyqpkgakhkvlfvgk---imdpdvcdh-----------kegg-
eem-tyykkdgeylrilayra------------cgvfngsseegm-----
--lqkkmfp-----p-k----fll-sfttstnslkl----w-qc----hl
--wrtpevnqrsvad-vcldck--i-dplspaf-sphql-krikff-ska
gl--ndkri-slw
>ENV_HV2D2/24-513
------sahsdtlhtrq---giykh-----ddanskasktfintlnkdtd
laeapphptspelcqpcqc------fhmdvaskldmlkkrlpasva--gk
vpsisignwnagtstaevswkcgq---yvaapkpegqqy--------pqa
kkvl--sksakdgveaidackns---lkyf--eghlfdikekq---kass
eegyflispqqgdkphstipelhtghq-pkvl----ktsyglfagrthad
spcakvsvysepsika----wpilytclhc---qefippggnevkrqddr
g-lt-----fq---kclrantihlvatgpcepdkcntartkpkcdcapvi
alvyh----avalt-------------------gtyrpkvs--kaecnhe
kkk--kmlksakpghlvk---------p----galnnypg--kpkdlct-
----kgeyppkaathavqfv------ldpdlcah-----------kegg-
knf-hyykkdgqylkivsyra------------cglfnganidgmeagvg
hvlqkktfs-----p-k----yll-sfstttnsval----w-n------l
--w-tpei--------tcl-ck--i-eplspel-sphvl-klikff-akt
gl--tdmsi-nlw
>ENV_HV2G1/23-502
parvfv---nesfhaqh---gvfkh-----gdahsrgggsyfnnvkkntn
lakavphpsa--vcvgcvcpyfr--fhmdltdridmvkkrlpcava--gk
ipsiaignwnagtssadvtwhckq---yailpkpngtqk--------pqa
kesl--ckkandvhqeieacnns---leyl--e---fdilede---kass
eedyflfqpqqgekthttipelhsahq-prtl----ktvyglfagvkhta
sscasv---sepaikv----weiqytclpc---qdfipsaapedqreddr
g-ltkpc--fq---eclrettihlratgpcet-k--dasvkpkcgcspvv
plvyh-lllgvvltkqh----hm----------gpyrpkvs--kdecnhe
knk--kmlrdakpghlvk---------ppgsrgllvdyagarkskclct-
-----gyfqpkgakhkvlfvgk---imdpnvcdh-----------regg-
eef-tycktdgeylrilayra------------cavfngsaekdm-----
--lqkkthp-----p-k----ill-sfttstnslkl----n-ac----hl
--wrtpevnqrsvad-icldck--i-dplspaf-spnql-krikff-kka
gl--kdkri-alw
>ENV_HV2CA/25-512
paqifs---nisfhsqh---gvfkh-----gspherasgdfyndakkntn
lakgvphpga--pcvgcqcsyyn--fhmeiknraemlkkrlasava--gk
vpsiavgnwnagpspsdvtwncge---evispkpngtqk--------gep
kqsl--cksmk--------cmgp---leym--d---fdlkegeeiqkvsg
qvdfftfppeqpemthtkgadlktahq-argl----ktafgllaghahha
spckkvavydhpsitv----weigytalpc---qdflplaeqedqredak
g-ltklc--fqllmkclrettihleatgpcef-kcadsgtkpkcpctpii
plvyv-tllvvvltkqh----fl----------gayrpkvt--kaqcdne
kns--kmiksqkpsnlia---------papsrgtlvtypa--kmkclct-
-----glyhppgqrhqvlfvgk---iidpdvcdh-----------tegg-
eda-vfydtegqylrvlgyla------------sgvfagpseegm-----
--lqkrkfp-----psk----fll-cftttthslkl----wwqc----hf
--wrvpeveqrsvsd-vcldcr--v-drlaptl-tphql-kwikff-cpa
ga--ddnkv-slw
