>node9
pmkkesqdds---gigavklat-vamsl---taptcf---rtvagahntp
kgpltls-----gnrnvrdllsl----d-t------ltdee-rdilqgs-
qsalfflsp--------tg----dspastvltl----tpt--wfpdggpq
gkctpdggatkep------nh--qnatg--vs------cfrlaavysign
d-rc-ps-----i--tscrqdt--gfv-i----wlhdg------------
--scvtikacka--sla---tyea--afhdtntpp----sk--ilkqg-d
vpkkr--alnae-gn------rk----vqaskgvsg-ga---irrttqp-
-----pqakgarqgfyp-ng-f-hspytt---klvyml-aepyaaeveyv
vvgcpeflhwrdsgs----avp---ipqangf---arhlhr-aliavdnt
vyhvi-------k---kn--ackqihetqlwyphdfhlgn--------id
e-tqtrfvcwpp---laa-glc-nawayimagvvrmlfae---atltvvc
i-esgats--vcgrvnn-dgnygslivralpyktkckaevilghkgvaca
lllth--arkg----cglcvgenndvgn----lklaa-qyh---s---ca
p-n-llia----kyrglnfmsdyffkvla----------l---psqlsth
nadkq
>ENV_SIVV1/24-538
pkdt------rkgsetaq-----gslpg---agltcf---ataegehes-
------------nphskptdqal----edyscdpgyl--sa-sncgitri
apvlmlfcs--------as----llpsv-vlcv----npd--yfvqhgap
al-----------------nh--ttae----g------ayafvvqyspsv
n-qc-sncapkkv--ahcnqdd--gsv-kgfanwlslgdsgrdgir--gf
re-aqviipcka--glsgqagyea--alqhtefgvtkrgakgtvls--qq
ithtk--qlktl-gvcnagmppk----vppkr---g-e-htlsskatep-
-----getqnigpafye-lsay-ngkynaqknklmwvg-glplpeateyq
vegcpgfmakrsatt----pgv---spvsekf---gpyl-d-v--t---s
kyhtv-------d---ge--rcnql--tqlwvipgyqlkk--------vk
r-vgerfqcwes---las-alc-hrrgyrragillrlqap---vkiisva
t-ntcadi--gkgrvgr-ng-------rnlpwaskckd---lagkagdci
ltvdp--aakg----csk--------sgtvkvhklyg-pyq---t-----
r-s-lldg----eyrg-sflptlftsvfp----------r---lahftai
datkr
>ENV_HV2NZ/24-502
pmkkkaqnds---gysevklsv-vamal---aacqcfnkk------hlap
rgqlnls-----glknvrdllkl----d-n------lvdke-railqgs-
qqalfflgp--------gg-qdgetpgstvltf----ski--wfpkggpq
gkckpdggitkir-------h--rlass--es------cgrlkaiysngs
t-rc-tn-----vrqpscrakt--gln-i----wlhdt------------
--scltiksckarnalk---ayea---fhgtntpp----sk--ilkqg-d
vsekrktefeds-gd------rk----vkvgkdvsg-ga---vkrtqhp-
-----tqedgdrvg--p-a-----gpytt---kqtymt-gepyaanvrye
htdcveflhwreeaa----kvp---fpqangf---ar-----plievqta
vfevi-------k---kykkdckpvsetqlwypqdfyvgegkqngkivld
easqarfvcwsetlglcayglc-kawtylitgavrmlfqa---eslvavc
i-eshgrg--itgpshd-egnyaslivralpflskckasvpldhkgatcv
lvlth--vpkg----cglcivekngigt----lklaa-vyh---i---ca
p-t-lvva----kyrgltfm---ifkilt----------l---peqllth
nakkq
>ENV_SIVG1/22-522
pkdt---------getap-----dslpv---agpdcf---ktvegahqsk
kssrktp-----gkdstpaisal----ddypcvpeyldled-sdalvsav
vgtlllfcq--------eg----nsptp-iltv----ppn--wfpqhgaq
al-----------------nh--ktaa----g------cfnfvafcaidv
e-ec-nn-----v--ascqqdg--gsv-agfvlrlqeedcgrdnik--al
sepcqlllackv--gleeheayes--dlshaefga----sagtvis--qe
vphk----------k------pk----vepta---g-e-htptfkktep-
-----advkgmgpt--e-lssy-hakysaektkllwva-glpfnegkeyq
vpgcpgflakrastt----gev---ipvsskf---apyl-r-a--t---a
kyhvv-------d---ad--rckqi--aqsltppgyqlkn--------vk
r-gqnhfscwe----laa-glc-hsrgykrkgvldqlsap---vgltsvs
vhdvcadi--gknkvgsaee-------anlryvakske---lankpqqcs
llvdsaaarkg----cgk--------kavtkihklhg-pyn---t---ca
t-k-llvg----syqg-tylss--ykvla----------k---ldhftiv
sakkr
>ENV_SIVGB/47-569
amss-----------pva------g--m---qeh--y---tgpqsahnfa
svale---------qnasrnqilktgvknlncqpaslkreq-dhcdhsks
alqdfdisn--------pg----llae----dr----rpkflwfptdayq
lkcaths-gkenntqrlkdkfpmkadt----snlgrccc----------f
s-tkvtn-----g--lstpdlpllpeydl----etanaagkkkqlgadqa
ndacflvaacel--gkg---tcgdkaaettt-vrt----s-pltlr---e
vakkg--f-kdeldd------ih----g-----vyq-aehtaelgeddpt
akcripdvkkws--antnl-------yglkkkeg------------tsah
saackgtlcs-easivkgvistdavnpgaetl---afhi-k-a--g---r
--rvpysekepl----------qge--tsswaa-fftftd--------sk
d-nhgr-----s---lva-ilv-haqay---agkppghad-------cag
f-apsaegggskvkagq-sn-------kdvqy-akckh---yvgk---cl
iefta--svsamllycgn--------pv----ld--sipyp---a---cv
ehv-evltdrire----kfi-------lapqkghgdtglf---ltmyggv
p--kq
>ENV_HV2BE/24-510
pmkkegqnnp---gvgsvkistq---gl---aaatcf---rtvvgvhnap
kgqlklsplsgvglrsvrdllsl----d-h------lkdre-ndtlqgs-
pealfslgpppqrkvpqtg-lkgesrlssvlsf----tls--wfpksgpq
skckpdggitsdp------dq--qntlg--va------cfrlkdmyskgn
t-rc-ps-----i--tscrakm--gfi-i----wmhdg------------
--scvvikacka--ske---vyea--gfhdskapp----sm--ivkqd-d
vpkrk--vlade-gn------rk----iqaskgvtgrgs---errrctp-
-----pqdkgarvn--p-ng-f-hapytt---kkvyky-sepfgvevqyk
hsdcpgflhwrdegt----tvp---ipdengfadkarhlhr-alfavqnt
vihvs-------k---kykkackeihetplwyphefhlgagattgkvale
e-tdtrfvcwpe---laa-glcfkswsylapgvvrmlfkepctatlvavg
i-qsqaag--icdspns-ngsyteaivralpymdkcktsvalrhngvtcv
lllah--vpkf----sgtcvgakndvgt----lklta-kyh---tesica
p-t-lila----kyrglkfmsqyifkila----------l---pnqlttn
nak--
>node19
pmkkeaqnds---gvgevklst-vamsl---taatcf---rtvvgahnap
kgqlkls-----glrnvrdllsl----d-h------ltdre-rdilqgs-
qealfilgp--------tg-vkgespastvltf----tpt--wfpdggpq
skckpdggitkdp------nq--qnatg--vs------cfrlkavysign
t-rc-ps-----i--tscrgkt--gfv-i----wlhdg------------
--scvtikacka--ala---ayea--afhdtntpp----sk--ilkqg-d
vpkkr--elede-gn------rk----vqaskgvsg-ga---vrrttqp-
-----pqakgarvg--p-ng-f-hapytt---kkvymy-aepyavnvqyd
hadcpeflhwrdegs----avp---ipqangf---arhlhr-aliavqnt
vfhvi-------k---kykkackqihetqlwypqnfhlgegkatgkiald
e-tqtrfvcwpe---laa-glc-kawtyliagvvrmlfne---atlvavc
i-esegsg--icgrand-dgnytslivralpymskckasvalnhkgvtcv
lllth--vpkg----cglcvgekndvgn----lklta-qyh---t---ca
p-t-liia----kyrglnfmseyifkila----------l---pnqlsth
nakkq
>node11
pmkkeaqnds---gvgevklst-vamsl---taatcf---rtvvgahnap
kgqlkls-----glrnvrdllsl----d-h------ltdke-rdilqgs-
qealfilgp--------tg-vkgespastvltf----tpt--wfpdggpq
skckpdggitkdp------nq--qnatg--vs------cfrlkavysign
t-rc-ps-----i--tscrgkt--gfv-i----wlhdg------------
--scvtikacka--ala---ayea--afhdtntpp----sk--ilkqg-d
vpkkr--elede-gn------rk----vqaskgvsg-ga---vrrttqp-
-----pqakgarvg--p-ng-f-hapytt---kkvymy-aepyavevqyd
vadcpeflhwrdegs----avp---ipqangf---arhlhr-aliavqnt
vyhvi-------k---kykkackqihetqlwypqnfhlgegkatgkiald
e-tqtrfvcwpe---laa-glc-kawtyliagvvrmlfne---atlvavc
i-esegss--icgrand-dgnytslivralpymskckasvnlnhkgvtcv
lllth--vpkg----cglcvgekndvgn----lklta-qyh---t---ca
p-t-liia----kyrglnfmseyifkila----------l---pnqlsth
nakkq
>ENV_HV2CA/25-512
pmkkeaqges---gigg-klfv-vqmtl---taaecf---rtvvgahnap
kgqvklg-----glknvrsllsl----q-n------asdre-rdifqga-
qevmfilgp--------hg-vkgenpastvltf----spn--wfpkggpq
skckpdggitnnp------ns--sn-------------csrlktiysikn
t-c-------------scrgat--gfv-i----wfhdk------------
--tcvtikacka--vla---ayev--afhdtttpp----sk--ilkhg-n
vnekr--eldde-gn------rk----vqaskgvaa-gs---vrrtthp-
-----qqaksvrvg--p-ng-f-rapytt---klvyms-aepyalnvdyd
nadcveflhwrqegs----avp---ipdangf---hrylhk-aliavrnt
vfhvi-------k---kykkgckqiketqlwypqkfylgeqkapgkiald
e-tqarfvcwpe---laa-glc-kawtylqsgalrklfge---etivatc
t-elegsg--icgrrnd-dgdyaseivkalpymskcvvkvalnhkgitcv
lvlth--vrkg----cnlcvvdrnavgn----lklga-hyh---p---cy
p-n-ltis----kyralcfm---vlkivt----------l---qeqlsth
kakks
>node8
pkdt---------getga-----tslpn---ashtcf---ktvegahqtk
kgplkkp-----ggdstsaiqtl----ddyscvpgyldsea-sncllgav
psvlfifcq--------ag----nlppv-vltv----spg--wypqggpq
akctthgaagkep------nh--knaa----g------cflfvvyysidv
e-ec-an-----v--apchqdt--gsv-v----wlqegdskrdnir--gl
sepclvikscka--gld---syes--alsnaeiga----akgdvls---e
ipvkk--vlktq-gk------rk----veptkdvng-eqhnpnfkstep-
-----pdakgispgfyp-lsgy-hasysvekkklvwvl-slpfnegkeyq
vtgcpgflakrdsts----pav---ipvsskf---aphl-r-a--t---a
myhvv-------d---se--pckqi--tqlwtppgyhlkn--------ik
d-aqnrfncwls---las-glc-hsrgykrkgvlarlsae---vdltcvs
i-dtsads--ikgkvgr-de-------rslpykakckd---lagkassca
llves--arkg----cgk--------ga----lklha-pyh---t---cd
t-n-llvg----dfrg-tflssffykvla----------l---ashfttv
naskr
>node10
pmkkeaqnds---gvgevklst-vamsl---taatcf---rtvvgahnap
kgplkls-----gnrnvrdllsl----d-h------ltdee-rdilqgs-
qaalfflgp--------tg-vkgespastvltf----tpt--wfpdggpq
skckpdggatkep------nq--qnatg--vs------cfrlqavysign
d-rc-ps-----i--tscrgkt--gfv-i----wlhdg------------
--scvtikacka--ala---ayea--afhdtntpp----sk--ilkqg-d
vpkkr--alnee-gn------rk----vqaskgvsg-ga---irrttqp-
-----pqakgarvg--p-ng-f-htpytt---kkvyml-aepyaaevqyd
vvdcpeflhwrdegs----avp---ipqangf---arhlhr-aliavqnt
vyhvi-------k---kn--ackqihetqlwyphdfhlgegkatgkiald
e-tqtrfvcwpe---laa-glc-nawaylvagvvrmlfne---atltavc
i-esegss--icgrtnd-dgnytslivralpymskckasvilnhkgvtcv
lllth--arkg----cglcvgerndvgn----lklta-qyh---t---ca
p-t-liia----kyrglnfmsdyffkvla----------l---psqlsth
narkq
>node18
pmkkeaqnds---gvgevklst-vamal---taatcf---rtvvgahnap
kgqlkls-----glrnvrdllsl----d-h------ltdre-rdilqgs-
qealfilgp--------tg-vkgespastvltf----tpt--wfpkggpq
skckpdggitkdp------nq--qnatg--vs------cfrlkavysign
t-rc-ps-----i--tscrgkt--gfv-i----wlhdg------------
--scvtikacka--ala---ayea--afhdtntpp----sk--ilkqg-d
vpkkr--elede-gn------rk----vqaskgvsg-ga---vrrttqp-
-----pqakgarvg--p-ng-f-hapytt---kkvymy-aepyavnvqyd
hadcpeflhwrdegs----avp---ipeangf---arhlhr-aliavqnt
vfhvi-------k---kykkackqihetqlwypqnfhlgegkatgkiald
e-tqtrfvcwpe---laa-glc-kawtyliagvvrmlfne---atlvavc
i-esegsg--icgrand-dgnytslivralpymskckasvalnhkgvtcv
lllth--vpkg----cglcvgekndvgn----lklta-qyh---t---ca
p-t-liia----kyrglnfmseyifkila----------l---pnqlsth
nakkq
>ENV_HV2D2/24-513
pmkkqeqngs---avgetklaa-vtvsr---sat-------tvvgghhgp
agplkld-----gttnikd--tl----n-q------stdde-kdvlqgk-
qaplfflgp--------tgeekaessatavltf----aps--wypdgspe
skckpdggadkpp------ne--qnatg--vp------cykleavyslgn
hlrc-vs-----i--tscrgks--gfv-l----wmhkg------------
--scptvkacka--ahq---aaev--vfhnyhtph----sm--lvk----
--------------n------rklsakvqpskgvsg-gt---srrtaqp-
-----aqakgar------tg-fkhtkntt---kkvymv-kepyaaeveyk
vvnctgflhlrdegq----dvp---fpeasgf---trlmqk-aliavqdt
tyhvi-------kgaddn--ackrihevqlwythhfhmsegkaggkvsid
e-aetrfacwpe---las-glc-dawatlvaavpkslyte---apltav-
-----gss--icgksnd-dgdytsliiraypytakcdasiimshkgatcp
llmth--arkd----yglcvgdrnevgd----lklts-qyh---a---ca
v-tsllik----kyraltfisdcffkvlv----------l---tsalga-
-----
>node14
pmkkeaqnds---gvgelklst-vamal---aaatcf---rtvvgahnap
kgqlkls-----glrnvrdllsl----d-h------ltdre-rdtlqgs-
qealfilgptperkvpqtg-vkgespastvlaf----tpt--wfpksgpq
skckpdggitkdp------nq--qnatg--vs------cfrlkavysign
t-rc-ps-----i--tscrgkt--gfv-i----wlhdg------------
--scvvikacka--sla---vyea--afhdsntpp----sk--ilkqd-d
vpkkr--elede-gn------rk----vqaskgvsg-ga---vrrtcqp-
-----pqakgarvg--p-ng-f-hapytt---kkvymy-sepygvnvqyd
hadcpeflhwrdegt----avp---ipeangf---arhlhr-aliavqnt
vfhvi-------k---kykkackqihetqlwypqdfhlgegkatgkiald
e-tqtrfvcwpe---laa-glc-kawtylipgvvrmlfne---atlvavc
i-esegsg--icgsans-dgnytelivralpymskckasvalnhkgvtcv
lllth--vpkg----cglcvgekndvgn----lklta-qyh---t---ca
p-t-liia----kyrglkfmseyifkila----------l---pnqltth
nakkq
>ENV_SIVM1/24-528
pmskkihdds---gagavklps-vlmsl---iaptcf---rtvagahntp
egplfag-----gprnvrdllsl----d-t------lteed-rdavqgn-
vsalyflsp--------tg----dspaatvltltdgttpv--wfpaggpa
gkctpdggstkep------gh--qnvti--vs------cfrlaavy--gn
d-rc-pc-----i--tncrqds--afv-i----whhdg------------
--scvtieacka--sla---tyea--afhdthtpp----sd--ilkqg-n
vhkkr--alnae-gn------rt----vqankgvsg-ga---irattqh-
-----aqakgarqafhp-dg-f-hsptkt---rliymlfaepyaaecdyv
vvgcpeflhrrdpdn----avp---ilqvngf---arhlhr-aliavsnk
vyhvi-------k---kn--ackd---selwyphsfhlgn--------id
e-tetrfvcwpp---laa-mmc-ftwaytlagvvrglfae---aallvvc
i-esktts--vvgrvsk-qpnysslivrvlpcktkcksehilgnkgvaca
llvth--arkg----cglcvgenndvgs----lklsd-qyhkkat---ca
p-d-llie----kyrglafmsgyffkvle----------l---psqlcth
ntdkq
>ENV_HV2G1/23-502
hmkkeaqndp---gvgevkfsp-vamsllgetaatcy---rsvvgahnap
kgklkls-----glrngr--lsl----d-h------ltnk---divqgs-
qealfilgp--------tg-vkg--patpvltf----tpt--wfpqggpq
skckpdggitkep------nq--qnstg--vs------cfrlkavycigs
t-rc-ps-----i--ttcrgkt--gfv-i----wlhdg------------
--scvainpcka--ala---syea--tfhdtstpp----sk--avkqg-d
vpskr--eldde-gh------rk----vqaskgveg-ga---vrkttqp-
-----pqapaarig--p-ng-f-hapytt---kkvymy-aepyaievqyd
vadcpaflhwrdegs----avp---ipqangf---arqlhr-flvavqgt
vyhfi-------k---kykkcckqihetqlwypqnfhlgegkakgkiald
--aqtrfvcwpe---lea-glc-kawtyliagvvrmlfse---atlvaac
i-esegss--icgpanv-dgnytslvvralpymskckasvnlnhkgvtcv
lllth--vpkg----cglcvgekndvgn----lklta-qyh---t---cv
p-t-liiq----kyqglsfmseyiykila----------l---pnqlsta
hakkq
>node17
pmkkeaqnds---gvgevklsv-vamal---taatcf---rtvvgahnap
kgqlkls-----glknvrdllsl----d-n------ltdre-rdilqgs-
qealfilgp--------tg-vkgenpastvltf----spt--wfpkggpq
skckpdggitkns------nq--qnatg--vs------cfrlkaiysign
t-rc-ps-----i--pscrgkt--gfv-i----wlhds------------
--scvtikacka--ala---ayea--afhdtntpp----sk--ilkqg-d
vpekr--elede-gn------rk----vqaskgvsg-ga---vrrttqp-
-----pqakgarvg--p-ng-f-hapytt---kkvymt-aepyavnvqyd
hadcveflhwrdegs----avp---ipeangf---arhlhr-aliavqnt
vfhvi-------k---kykkgckqinetqlwypqnfylgegkatgkivld
e-tqarfvcwpe---laa-glc-kawtyliagavrmlfne---qtlvavc
i-esegsg--icgrrnd-dgnyaslivralpymskckasvalnhkgvtcv
lllth--vpkg----cglcvvekndvgn----lklta-qyh---a---ca
p-t-liia----kyrglsfm---ifkilt----------l---peqlsth
nakkq
>ENV_HV2D1/24-501
pmrrdaqdda---gvgelglst-vasal---aeatcf---rtvvgahnap
kgqlkls-----dlrsmkellsl----d-h------ltdrerrdasqgs-
qealfilgptperkvpqtg-akaetptstilaf----tpa--wfpksgpq
pkckpdcgitkdp------nh--qsatgplvs------cfwlkavysign
t-rc-ps-----n--ascrgkt--kfv-i----wihdg------------
--scvvikeckg--sla---vyea--afhdssstp----sk--ilkqd-a
vpkkr--elede-gt------rk----vqtstgvsg-gk---akhgcep-
-----peakgprvg--p-ng-f-hapyyt---kkvymy-sqaygvkvqyd
hadcp---hwrdgga----avp---ipeangf---crhlhrns---vtkt
lfhif-------k---kynkackqvhetevwypedfhldegkatggismd
p-sktrfvcwpe---vaa-glc-kaw-ylipgvvrmlfnq---atlvaic
i-ksegsg--icggang-dgnytelivralpymskckasvalkhkgvtcv
lllvh--vpkg----cglcagekndvgn----lk--------------ca
p-t-lita----kyhglkfmseyifkila----------lheipnnltth
nakkq
>node7
pkdt---------getaq-----sslpg---ashtcf---ktvegahqtk
keplkkp-----gkdstpaiqal----ddyscvpgyldsea-sncllsav
vsvlllfcq--------ag----nlptv-vltv----spg--wfpqhgpq
al-----------------nh--ktaa----g------cfnfvvyysidv
n-ec-sn-----v--apchqdg--gsv-agfalwlqegdsgrdnir--gl
sepcqviiacka--glegheayes--plshaefga----akgtvls--qe
iphkk--vlktq-gk------sk----veptk---g-e-htpsfkstep-
-----adakgigpafye-lsay-hakysveknklmwvl-glpfnegkeyq
vpgcpgflakrdstt----pav---ipvsskf---apyl-r-a--t---a
kyhvv-------d---ge--rckqi--tqlwtppgyqlkn--------vk
k-aqnrfscwev---las-glc-hsrgykrkgvlnrlsap---vgltsvs
v-dtcadi--gknkvgr-ee-------rnlpykakckd---lagkandcs
llvds--arkg----cgk--------kattkihklhg-pyh---t---cd
t-n-llvg----dyrg-tylssffykvla----------k---lshfttv
daskr
