>ENV_HV2BE/24-510
vqvptfgatvdwqtq---e--glckqtynqglfdlpvckt-clqckqhff
tv--------g---dksrnnf----kgacsy---aydvgp-----ecaen
il-lf---akdsvlfka--va-kkiyrvqyaqitt----------ghgsq
sgvmnnaa--rs---tsgrknpvfe--ksvcrg-g---g-mecc------
-------n--tkecfwavghvrkclg--mssacrkrwv-snyhgr-----
--wpqqglvskikydesnl-----depdl------nkqgln----ntfge
klhqnwcgvtlkkka----ade----akastvattclvavqdnacaltnk
---sgncpridgggrdla--aa-yaqtis--------qyeyr-w-a---n
a-l--kngghv-agae---ngpgepanavgnklgqatsa-----------
-qkgfktnggq-----samkgakqyfyysf-yasn-pflgnttptmaapa
---idfwlarqpfnllwgvkli-----vk----rcsg-tgiltngepl--
a---lkcgntqlsst------pgvtcetqtnfd-------gllrht-gav
kekpl--vyf-cs---fakgvsgytlsqklde-pynder-----vdg-vy
------tada-ymdelpsninydkkndlvgvell------lpafkfkpv-
---pp---nephat---ar
>ENV_HV2CA/25-512
vgvpkf------------e--glckqtydqslldlpvckt-cldckqhyf
dgq-------t---dkarsnfkdvakgacti---tydispvpdtkqcaah
il-li---aheavlpsv--va-kdpcrvqysqfttagigvlfgelgr---
-----kga--td---i--rdfavfeteksvakg-n---g-mqcc------
-skgpiaydptkecffipghvrkcag--mtsscqkrwvkssyhaa-----
--wpqeklvsrakyaesnlfs-randptl------glegln----ttles
klha-wcpvslkkev----asf----skvryvantcllqahenecraenk
tglsnhcpridsagrtlg--ts-hlqt-e--------qyeyr-w-a---n
a-r--kpgshl-agqe---ggpgepanalgdkmgqgvttmaplppsskel
kqkgfkdnggq-----spmkggreyftysf-yatr-pffgsaissfvapp
---teyri--qpfnlllgms-------vr----rsdg-tgvle-gdpl--
l---qkagrtqlsal------pgaacetqtkne-------glrren-eav
kekpl--vyfgcy---naksvsdythkqklds-pyhddm-----vpg-vy
------taep-imdeqlsnekyarkndllgvgll------apafnlkpl-
---pp---t-lhaa---lr
>node9
vevpkf------------e--glckqtyndrlldlpvckt-cidckvhff
ds--------v---ekgrnnf----kgacni---nydvsp-----qcsan
il-lv---tndailssi--la-kkvy----------------------sq
nldmtkga--qq---iggrkfpvfd--ksvvdgrd---gqmhcc------
-skgptqn--tkecfwipgharkcag--vssgchkrwvydnyhvt-----
--wpqemlvskikydegklfs-paedpdl------gkeglh----ttlgs
klha-wcg-slkkth----aes----akirtvaatcllevhqnlcaltqd
aglsnhcqridnsgrtla--ga-nlht-s--------syetr-w-a---n
a-y--dpgghv-agqe---dgngkppngvgdklghgttn-----------
-qkgfknnagq-----samksareyflcsf-ygsn-pffastlssydahp
---tdywlprepfnl--gvs-------vr----rcag-ngvmt-gspl--
l---lkcgntqysal------pgvtcetqskfe------hglrrqg-g--
--apr--vyf-cf---gakgvpgytlkqklqs-pyneem-----vdg-vy
------taea-imdslasnenydkkselagtgll------spafqlkpl-
---pp---nevhaa---ar
>node18
vevpkf------------e--glckqtynqslldlpvckt-cldckqhff
ds--------v---dkarsnf----kgacsi---tydvsp-----qcsan
il-lv---akdavlsna--va-kkiyrvqyaqitt----------grgsq
nlsmtkga--rn---iggrnfpvfd--ksvckg-n---g-mqcc------
-skgptqn--tkecfwipghvrkcag--mssgchkrwvnsnyhvs-----
--wpqeklvskikydegnlfs-paedpdl------gkegln----ttlgs
klha-wcgvslkkka----ads----akirtvantcllavqenlcaltdk
aglsnhcpridsagrtla--as-hlqt-s--------qyeyr-w-a---n
a-h--kpgghv-agqe---dgpgepanavgdklgqgtta-----------
-qkgfkdnggq-----samkgareyflysf-yasn-pffgntissfqapp
---tdywlprqpfnlllgvs-------vr----qsag-tgvlt-gdpl--
l---lkcgntqlsal------pgvtcetqtkfe-------glrren-gav
kekpl--vyf-cy---fakgvsgytlkqklds-pyhdem-----vdg-vy
------taea-imdelasnenydkkndlvgvgll------apafqlkpl-
---pp---nevhaa---ar
>node7
vkipka------------lllglckaafqkktldipicgpktigckhpfh
ge--------v---ey-kqei----rgwchv---nykiph-----qatat
il-llksctnlgvlgcaedss-kkvy----------------------sq
eldlarvk--ge---iearkysled--t-----qkek-addpcc------
-atgptka--aahcfwatgykkkcad--vetgchkswlatdihvs-----
--wqpagltskqkydsg-vmg-pqeepgl------qmdg-----------
-------g-tkkgkhgs-gs----------pgaamrlvpivhgvsaghta
tdfanpctv-egkknpag--aa-klyt-n--------tyeva-w-tksgd
g-l--yptghv-tgqq---dghl--ptgagdkhgrgeat-----------
-tpsnmaetgsfglaayvgktgkeya--af-fgvfkaflanilqc----c
---kefwvskdpftl--alp-------ak----kgggsk-vhr-ssrl--
l---vicgrtkydsa------pgvkcevagkfhketevwhg----d-g--
--aprelmsf-ct---gpqasqardmkkklms-sytkkt-----cta-dy
qkvgfatsda-wvqkvkgsenynkklelagtgkl------hggvelldq-
---pp---nevgga---sq
>ENV_SIVGB/47-569
tagqlt------------llia----gy---dlavavaalinil--qpfp
as--------t---hv-pqal----tiwchg---tamigh-----rtntp
lfssg---ndapiplsv--wd-qrsy----------------------sg
yldcadak--nd---vatna--ked--e-----lkik-v--iam------
-aahpdka--pve------kk-------vttichkarltdvaada-----
--wpksrvaakkgyt----lkgatdg-gf------rtqvpkapetp----
------ce-asicdkaailk--vk-------dgvtkle-lihgv------
---npvcsn-qskskqlalylefvlcr-lalhpefvi---pthrvacep-
--e--yrlqpi-mdek--gngrg--qhsgadryislg-s-----------
-kyfskgkemdlavngya----sstg--lfgfsdqlaltaala------p
pgvekfwttkapfvl--rlp--ltkagvk----rqnggd-vn---ahlta
l---vr-g-tkphsd------alkknlpsak--------hs----g-g--
--tpitdm-f-gynrg-klgcvhpe---krdtgcyepqd-----c----s
tsqey------qltnsdgglphss-ilvivkgqlsldykrnsssileekf
gintgshtlevgeaarlir
>node14
vevptfgatvdfqaq---e--glckqtynqslldlpvckt-cldckqhff
tt--------v---dkarsnf----kgacsi---aydvgp-----qcsan
il-lv---akdavlfna--va-kkiyrvqyaqitt----------grgsq
nltmtkga--rs---tggrdfpvfd--ksvcrg-n---g-mqcc------
-skgptqn--tkecfwapghvrkcag--mssgchkrwvnsnyhas-----
--wpqeklvskikydegnlfs-paddpdl------gkegln----ttfgs
klha-wcgvslkkka----ads----akirtvastcllavqenlcaltdk
---snncpridgagrtla--as-hlqt-s--------qyeyr-w-a---n
a-h--kpgghv-agqe---ngpgepanavgdklgqgtta-----------
-qkgfktnggq-----samkgarqyflysf-yasn-pffgntipsfaapp
---tdywlprqpfnllwgvs-------vr----qsag-tgilt-gdpl--
a---lkcgntqlsam------pgvtcetqtkfe-------glrren-gav
kekpl--vyf-cc---fakgvsgytlkqklde-pyhder-----vdg-vy
------taea-imdelasnenydkkndlvgvgll------apafqfkpl-
---pp---nevhaa---ar
>node19
vevpkf------------e--glckqtynqslldlpvckt-cldckqhff
ds--------v---dkarsnf----kgacni---tydvsp-----qcsan
il-lv---akdavlsna--va-kkiyrvqyaqitt----------grgsq
nlsmtkga--rn---iggrnfpvfd--ksvckg-n---g-mqcc------
-skgptqn--tkecfwipghvrkcag--mssgchkrwvnsnyhvs-----
--wpqeklvskikydegnlfs-paedpdl------gkegln----ttlgs
klha-wcgvslkkka----ads----akirtvantcllavqenlcaltdk
aglsnhcpridsagrtla--as-hlqt-s--------qyeyr-w-a---n
a-y--kpgghv-agqe---dgpgepanavgdklgqgtta-----------
-qkgfkdnggq-----samkgareyflysf-ygsn-pffgntissfqapp
---tdywlprqpfnlllgvs-------vr----qsag-tgvlt-gdpl--
l---lkcgntqlsal------pgvtcetqtkfe-------glrren-gav
kekpl--vyf-cy---fakgvsgytlkqklds-pyhdem-----vdg-vy
------taea-imdnlasnenydkkndlvgvgll------apafqlkpl-
---pp---nevhaa---ar
>ENV_SIVG1/22-522
mkipka------------lllglcragfqkksleipicgpkaigckppfh
gg--------v---ey-kqei----rgwcnv---aakiph-----qstaa
il-laksctnlgvlgatedrs-kkvy----------------------sq
eldlarvk--gk---inartysled--t-----qkeklgdgpccvapvn-
-staptka--ashyfwatgykkkcad--vttgchkswvatdihvg-----
--whpagltskqkydsg-vkg-pqeepgl------emda-----------
-------g-krkgrhgs-gs----------pgaimrlvpvvhgvvvghta
tdfanpctv-egkknpag--aa-klft-s--------tye---w-pdsgd
g-l--ypsgrv-sgeq---yghl--ptgagqkhgseeat-----------
-spahmadtgsfglvafvgkmgkeyv--sf-ypvfkaflvnilec----c
---kefwvskgpfkl--afp-------ak----kgggck-vhr-ssrl--
l---vicgrskyssa------pgvkcevaakfnketaawhg----d-a--
--vprelmsf-ct---gpeasqprelkk-----sytkkt-----cta-dy
qkvghavsda-wvqkvkgaehysdklelagagkl------hgsvelldq-
---pp---aelgga---sq
>ENV_SIVM1/24-528
vevpkf------------e--glckqtyddklldlpvckt-cinckvhff
ds--------v---dkgpngf----kggcni---tynvsp-----qcsah
tl-fv---tndailssi--la-gtvy----------------------sh
nldmdkga--qd---igtrkfpayt--kniidard---gqmdcc------
-skgpttp--akdcfwtpgharkcag--vstscqkrwvydnfhvt-----
--waqsmlvt-----egklfs-pgedpnl----scgkeglh----ttagt
klha-wcg-qlkkan----ges----akirtvaatclltahq-lcaltrd
aglsdhcqr--nsgrsls--ga-nqht-s--------syetk-w-a---n
agy--dpgghv-a--q---dgngkppngvgdklghgttg-----------
-qkgfknkagq-----sakgsareyflcsf-hqsy-pslastlssydahp
---ldywlkrepfkl--gva-------vrkyqgrcag-ngvmq-gspg--
lcallkcgntqypal------ggvtceteqkfe------nglrrqg-g--
--apr--vyf-cf---glkgvagyalkeklqs-pyneem-----vdgkiy
------teea-imdelasgehndkktelaglgll------spafqlkpl-
---pd---nevhaa---ar
>node17
vevpkf------------e--glckqtynqslldlpvckt-cldckqhff
ds--------t---dkarsnf----kgacti---tydisp-----qcsan
il-lv---akdavlsnv--va-kkiyrvqyaqfttkgigilfgelgr---
-----kga--rn---igfrnfpvfd--ksvckg-n---g-mqcc------
-skgptqn--tkecfwipghvrkcag--mtsgchkrwvnsyyhva-----
--wpqeklvskskydegnlfs-paedpdl------glegln----ttlgs
klha-wcgvslkkka----ads----akvryvantcllqvqenqcrltnk
tglsnhcpridsagrtla--as-hlqt-s--------qyeyr-w-a---n
a-h--kpgghv-agqe---dgpgepanavgdklgqgtta-----------
-qkgfkdnggq-----samkgareyfvysf-yasr-pffgntissfqapp
---teyrvprqpfnlllgvs-------vr----qsag-tgvle-gdpl--
l---lkcgstqlsal------pgvtcetqtkfe-------glrren-gav
kekpl--vyfgcy---haksvsgytlkqklds-pyhddm-----vdg-vy
------taea-imdelgsnenyskkndlvgvgll------apafqlkpl-
---pp---ndvhaa---lr
>ENV_HV2D2/24-513
veapkf------------e--amcrrtynq--------------cnvhaf
ds-aftetakv---etqqpaf----sgansl---ayq-sp-----qcspa
il-lv---akdtilska--vpfakvy----------------------sq
dmsmlkgt--sq---iggrnfpvfd--tdvhkgrn---g-kgcc-----g
vakgpten--tkecfwtpghvrkcig--vssgchkrwvfdnyhvt----e
nlwpqellvskikydqgnqfk-saeepsl------gkegah----stlgn
kvha-wcgvplskkg----aea--hlakirsventcllgsheslc-----
---ghhceridsagktmg--ds-dlht-s--------eydtr-w-a---h
a-y--kpgghi-agee---dapgkpaqavgdkldqgtte-----------
-qktynhngaq--------------flysy-ygas-pfkasnissyqsqp
---tdywlprnpfnlalgvn-------aa----qraq-gyimv-gdpl--
l---ikcgntelsalllsqkf-------hkkfa-------gvqrsaagsa
nakpm--iyf-ty---ganavsgytlqqnlqd-pyyddmilvgapdg-vy
------saea-mldtlassgsypkrndlpgvgll------aeafqlkpl-
---ap---etihaa---er
>ENV_HV2G1/23-502
vkvpkf------------a--glcththdqslldlpvckn-cleckqqff
es--------v---dkarsnf----kgacnt---nydvsp-----qcnan
il-lv---akdavlnnt--iv-kkvyrvqsaqitt----------qrgtq
nlsmtkga--rn---igernfpvfd--ksvcpg-n---g-mqcp------
-dkgptqn--tkecfwmpghvrkcag--vvsgchkrwvnsnyhas-----
--wpqsiliamikydegnlfs-paedpdl------gkeglp----atlgs
klha-wcgvshkkka------s----akirtvantcilavndsvcaltnk
aglsnhcpridstgrtla--as-hlqt-a--------eyeyr-w-a---n
v-y--kpgghv-agqe---dgpgkpangvedrlgqgmts-----------
-qkafkdnggd-----samkgareyylygf-ygsn-dffgsrigsysapp
---teywlphqpfrlllgvs-------ls----qtag-tgvlt-gdpl--
l---lkcgntqlssl------pgvttatqtkfk-------alrrkn-sav
mekpl--lyf-cf---fakgtsgytlkqklds-pyhddm-----vdg-iy
------taespimdnlashqnynkkndlgavhll------apafqlkpf-
---pp---nnvhaa---ar
>node11
vevpkf------------e--glckqtynqslldlpvckt-cldckqhff
ds--------v---dkarsnf----kgacni---nydvsp-----qcsan
il-lv---akdavlsna--va-kkvyrvqyaqitt----------grgsq
nlsmtkga--rn---iggrnfpvfd--ksvckg-n---g-mqcc------
-skgptqn--tkecfwipghvrkcag--vssgchkrwvnsnyhvs-----
--wpqemlvskikydegnlfs-paedpdl------gkegln----ttlgs
klha-wcgvslkkka----ads----akirtvantcllavqenlcaltdk
aglsnhcpridsagrtla--as-hlqt-s--------qyeyr-w-a---n
a-y--kpgghv-agqe---dgpgkpanavgdklgqgttn-----------
-qkgfkdnggq-----samkgareyflysf-ygsn-pffgstissyqapp
---tdywlprqpfnlllgvs-------vr----qsag-tgvlt-gdpl--
l---lkcgntqlsal------pgvtcetqtkfe-------glrren-gav
kekpl--vyf-cy---fakgvsgytlkqklds-pyhdem-----vdg-vy
------taea-imdnlasnenydkkndlagvgll------apafqlkpl-
---pp---nevhaa---ar
>node8
vkipka------------lllglckaafkkrtldipicgtkainckhhfh
de--------v---ey-khei----kgwchv---nyevsh-----qstat
vl-ll---tnlgilati--la-kkvy----------------------sq
eldltrvk--dd---vggrkyslqd--t-----kkek-adlscc------
-atgptka--aaecfwaagnkkncag--vatvchkswlaanvhvs-----
--wqpaaliskhkydsgkvlg-pqeepdl------qmdgma----a----
------cg-tkkakhat-aa----------ggaamrlvpivhglcalhtd
adlanpctl-dgkkniag--aa-klyt-n--------tyets-w-akpgd
g-t--ypaghv-agqe---dghi--ptgagdkhgrgvgt-----------
-tkgnkaetgsfgiaaypsrtgkeya--af-fgaskaffadilqc----c
---pafwvakdpfsl--ams-------vk----kaggnk-vhr-asrl--
l---vrcgrtkydst------pgvkcevagkfkketevwhg----d-g--
--sprvlmsf-cy---gpeacpardmkqkles-sytnkk-----caa-qy
sdvgfatnda-rvqhtkgsenynkklelagagvl------hsglelknh-
---pp---nevgga---sq
>node10
vevpkf------------e--glckqtynqslldlpvckt-cldckvhff
ds--------v---dkarsnf----kgacni---nydvsp-----qcsan
il-lv---akdailsna--va-kkvy----------------------sq
nlsmtkga--rq---iggrnfpvfd--ksvckgrn---g-mqcc------
-skgptqn--tkecfwipghvrkcag--vssgchkrwvydnyhvt-----
--wpqemlvskikydegnlfs-paedpdl------gkeglh----ttlgs
klha-wcgvslkkkr----aes----akirtvgntcllavhqnlcaltkk
aglsnhcqridsagrtla--as-dlht-s--------eyetr-w-a---n
a-y--kpgghv-agqe---dgpgkpanavgdklgqgttn-----------
-qkgfknnggq-----samkgareyflysf-ygsn-pffastissyqahp
---tdywlprqpfnlllgvs-------vr----qsag-ngvmt-gdpl--
l---lkcgntqlsal------pgvtcetqskfe-------glrreg-gaa
kekpr--vyf-cy---gakgvsgytlkqklqs-pyhdem-----vdg-vy
------taea-imdslasnenydkkndlagvgll------spafqlkpl-
---pp---nevhaa---ar
>ENV_SIVV1/24-538
vagpkn------------glmghckpgfqkktlavpkcgp-aigckhpfh
gq--------tepfly-peev----rdwcpvirmtlktpq-----kaktt
if-llkscknlgvagsaestn-kkvy----------------------sq
elplarskpegegrvidehkasfed--d-----qkek-seeacc------
-asgatsa--galcywakeymkscak--adkgcikawlatdidss-----
--tsdtdltskeryaas-vlg-ppayggl------qmdg-----------
-------h-arkgdrgy-gv----------pktgtklvpelrgvnsshta
ighgcpctv-eggknsvg--ga-klyk-g--------iyava-w-tkngd
p-l--ylyghvgtgdqkg-dghi--plgagdthsrgean-----------
-keggmaetgrfkptayvgqafkdya--af--gvfkafldsilqc----c
---kafw---dpftm--alp-------se----kgggkd-thr-aarl--
l---ilcgrstydss------rnptcevagkfhkdle--------d-g--
--aprellsy-ct---gph--qsrdmkknvmg-nytrma------aa-ay
qmvgfaiadd-wlqkakgaehyskrlqlialsrl------g-----ndk-
---pp---sengg------
>ENV_HV2D1/24-501
vevptfgaavdfqaqekn-----ckqtynqplldlpvckt-cldceqhyf
st--------v---dkarknf----kgacsi---aydvgp-----qcsan
ql-lv---akdavlfha--gv-ksiyrvqyaqitt----------grgsq
nltltkgg--rn---tsdrdfplyd--ksacrg-n---g-lecc------
-skgptqg--skecfwspghvrkhagnqm-agthkewvttryhaa-----
--wpqeklvskikyddgplfs-pavdpdlkkvf--gkegln----atfgs
kiha-wcgvdlkkka----ads----akirtvastcmlavhenlaaltdk
---tdncprndgaavtla--at-hlqt-s--------qydyc-s-a---n
a-h--khgghv-ggqe---ngpgepanevgddlgngtta-----------
-ekgfktnegq-----samkgarqyflysf-yasn-pffgatipsfaapp
---adywlprqpfdllwgvs-------vr----qssg-tgilt-gepl--
a---lkcgnaqlsam------pgvdcetqtkfd-------glrian-gnv
kekpl--vff-cc---fargvsgytlkqklde-pyhddr-----vdg-vy
------tsea-ikdelaskanydqksdlagvgll------apgfqskpl-
---pp---navhaa---ar
>ENV_HV2NZ/24-502
veiskf------------d--glckqtynqslldipvcka-cldckqhff
ds--------t---dkassnf----tggcti---ayaiap-----dcaan
i--lv---akdavlshv--va-kkiy--------tkgddvifgelgr---
-----kga--rn---iafknfpvfn--kavcng-a---g-mqcc------
-segpnhn--tkeslwvsghvrscag--mttgchkrwvssyyyvglgfv-
-----eklvgiskydednlfr-pvedpdl------glegll----lslgs
klha-wcgvtlnkka----adp----aknrcvantcmlqvqdnqcriknk
tglsthcprvdstgrtla--ts-wlqt-s--------qyeyi-w-a---s
p-hsvkpgghv-agqe---dgpgepanavadklgggtts-----------
-qmgfkdnggq-----s--kgapeyfvydf-yapr-pffgstisslqapp
---teyrvprqnfnlllgvs-------ik----qspg-igvle-gdvm--
l---lkc---qlsal------pgvtcetptkft-------tlrren-gac
kekpi--vyfgcy---hvksvsghtlkqklgs-pchdam-----gdg-vy
------vaea-vldelgaaenyskkknlvgigll------apgfqlkpl-
---ap---kdlhqa---lr
