>ENV_SIVV1/24-538
fitvnkdpe------tseaitnygnaesvsp-----k---------na--
--daal-m----i-eqliltlmwnihptttlelvlltkvalhtnkhkaps
vgsedvsnshvlggal--lkcffalltgeaydakitsnkwwsggs-dec-
-dw---tnm-----------ehgvaqcdcqkvhdrpalhge----dge--
rlav---trfatmhyea-vsskgrra-------lvdetsl----------
ailg-lesl----stdssvsqiav-ed--vvsttccs---ing-k-----
---------dkayvapeyq------a--a-elhl-yhe-------aeg--
s--matkadfats--kaerglli--r------a----rlesd---caken
vpkineyksetqpga-----gdane----prn-fegtrpksevskr----
-pdkqytlk--aaiigid----sssfaketr-kikvy-qcdtv----dak
sfcek----n----kpakgreprfkw----------yakweggamal---
-------------ff-kaalffklqeksdslk--qcvgykk--------y
vkgaeptyqlfkelccg-engnktdsigdakik--gdedh-ktepnswlg
-htftli---v-fs------mgnl-----------shdg--svashathq
-eidveaalg----------qsp--kllsnaafkdls-----rnmevsci
tlpgnlckn-g--i-----ek--q-pvykdndg
>node9
aisn-nakrvtkme---------knvppvhg-----kslv----gqri--
--sat--------nhsiilsgvlegdpk---------------------m
vgm--------lg-daisckcffdlqyrqvidakmiirdwwsskaiaqcf
lewpgitgt---nrr---cignti---dvlkfr--------------q--
tlsk---krfvkvrinp-igtkgeklp----ppwtdqkp-eqde------
-ilr-vaetlmm-madftcvqaav-ng--lidsaaca---n-q-qsk---
-ldifa---laaflaplhn------g--g-gyhs-fht-------elf--
qpcmgpttalicp--qapqlali--k------s----rdkpv---cseqe
qpkigkyksqtplgm-----kptnv----pgt---------dscwv----
-a------p--deyvaieklkglh-----lk-kfrtf-gcgkvaqlrqsn
efcik----nyeqhessfgskgyynw----------fvskdngama----
-lql-------glff-adk----lddkenvln--qcagfrrg-------y
vqktdlcynenvalacgkqngtcksiveas---lnperqk-ghaaas---
--nfdkclgfv-l-------lghl-----------rstqanevanhstpq
-atngapalgeht--ls-at--skfklletrefirln-----kaadlgca
slpgsmykagd--d-----nk--glrtfpyirt
>node17
sikd-dakrvtkmq---------knrppvhg-----knlv----gqk---
--sgt--------nhsrilsgvlegdpk---------------------i
vgm--------lg-daicckcffdlqyrqiidtkmiirdwwptkavvkcf
ldspgitgt---trr---ciekti---hvlkfr--------------q--
tlsk---nr-------p-igskgdklp----ppwtdskp-lqde------
-ilr-vaetfvm-aanhtcvkaal-ng--lidsaaca---k-q-qsk---
-fntfaslslasflaplqn------g--g-syfs-lht-------elf--
qpcvgptaavicp--rapqiali--k------s----rakpl---cseda
kpkvgkyksttplgmginswkdanv----pgt---------dscwv----
-t------p--deyveveklkglh-----hk-sfrtf-gcskiaqlrqsn
afclk----------asfgskgyfdwrrq-----qkfisatngama----
-lll-------glffkpds----lddkkniln--hcagfkrg-------y
vqktdlcyngntllacgkdngtcnstvean---lnqed-----asga---
--hfdkclgfv-l-------lghi--------lmkrstqakevvnhgtpq
-atngspalgeat--ls-st--tkfsllatrefirln-----kaanygcs
slcgvmikggd--n-----sk--glp-fpyvrt
>node11
sikd-dakrvtkmq---------knrppvhg-----kslv----gqk---
--sgt--------nhsrilsgvlegdpk---------------------m
vgm--------lg-daicckcffdlqyrqiidtkmiirdwwptkavvqcf
ldspgitgt---trr---cigkti---hvlkfr--------------q--
tlsk---nr-------p-igskgdklp----ppwtdnkp-qqde------
-ilr-vaetfvm-aadhtcvkaal-ng--lidsaaca---k-q-qsk---
-fdtfaslslasflaplhn------g--g-syfs-fht-------elf--
qpcvgptaavicp--rapqlali--k------s----rakpl---cseqg
kpkvgkyksttplgmginswkpanv----pgt---------dscwv----
-t------p--deyveveklkglh-----hk-sfrtf-gcskiaqlrqsn
afclk----------asfgskgyfdwrrq-----qkfvsadngama----
-lll-------glffkgds----lddkknvln--hcagfrrg-------y
vqktdlcynentllacgkengtcnsiveas---lnpen-----asga---
--hfdkclgfv-l-------lghi--------lmkrstqakevvnhstpq
-atngspalgeat--ls-st--tkfkllatrefirln-----kaadlgca
slpgvmykagd--n-----sk--glr-fpyvrt
>node19
sikd-dakrvtkmq---------knrppvhg-----kslv----gqk---
--sgt--------nhsrilsgvlegdpk---------------------m
vgm--------lg-daicckcffdlqyrqiidtkmiirdwwptkavvqcf
ldspgitgt---trr---cigkti---hvlkfr--------------q--
tlsk---nr-------p-igskgdklp----ppwtdnkp-qqde------
-ilr-vaetfvm-aadhtcvkaal-ng--lidsaaca---k-q-qsk---
-fdtfaslslasflaplhn------g--g-syfs-fht-------elf--
qpcvgptaavicp--rapqlali--k------s----rakpl---csedg
kpkvgkyksttplgmginswkpanv----pgt---------dscwv----
-t------p--deyveveklkglh-----hk-sfrtf-gcskiaqlrqsn
afclk----------asfgskgyfdwrrq-----qkfvsadngama----
-lll-------glffkgds----lddkknvln--hcagfrrg-------y
vqktdlcynentllacgkengtcnsiveas---lnpen-----asga---
--hfdkclgfv-l-------lghi--------lmkrstqakevvnhstpq
-atngspalgeat--ls-st--tkfkllatrefirln-----kaadlgca
slpgvmykagd--n-----sk--glr-fpyvrt
>ENV_HV2NZ/24-502
sikd-dakrvtkrq---------knrppvcg-----khlv----gqk---
--sat--------nhnrilggvlnsgpk---------------------i
vgm--------lg-daicckcffelqykqvintmniirnswptkyvvkcf
lespgitgt---trr---cidkti---lvlkfr--------------q--
tlpk---nr-------p-igskgdklp----ppwtdskp-lqde------
-llr-vadsfvm-lsghtcqkavi-ng--lidsalce---t-n-qsk---
-fktfaslslpsflaplqn------g--v-tyfs-lhi-------elf--
qpcvgrtaavlca--rapqmali--k------rcdsqrakpl---caedv
kpkvgkykattplgvginswketnv----rgs---------dscwv----
-t------a--neyieveklkglt-----hk-sfktfrgctkiaqlrqss
tfclk----------asfgkksyfdwrre-----qkflsatngama----
-lll-------glfftpds----lgaktdiln--hcaglksg-------n
vqktdlcyngntllacgkdngtctstvqqs---lnqey-----angt---
--hfdkclgfv-l-------lghikfyfqkyclmkrstqpksvvnhgsah
-anngssalgdpt--ll-st--tkfalfanrefirln-----kagdygct
plcgvmidggn--k-----sk--gls-fpylrt
>node7
iitvhktaei---eeksdaanfyghvpsiss-----kt-------rkv--
--saav-l----l-qvvvltvvlngqpk---------------------a
vgesdvshtqtlg-tl--ikcffalltgeaydaniipnkwwsgms-gec-
-dw---tas-----------dptvaqcecqkihdrpalhgc----dse--
slav---trfailryqa-istkgtrd-------lieqapi--essgqhkf
viia-ldel----stdtsvsqvav-tg--lmsttccs---t-h-k-----
---------akpyvapafk------a--g-eyhl-yht-------adg--
s--matkadfvsp--raerglli--r------g----rsdpi---cdkqe
apkiteyksetpaga-----geane----pgn-fdgarpkadssrr----
-retkytsk--aeligie----nsrfspetr-kikmf-qcdsv----kak
sfcek----n----krargqngsfnw----------yvhwetgamal---
-------------ff-paaffgklqdkndclk--qcisfqrg----lyay
vkkvdlsyqffkglccgkengkknnsigdslns--geskh-gteatsllg
-htfnrc---v-ls------lgnm-----------rndgpksaanhatnq
-dievsvalgehte-le-taectqfklltaaafiels-----rnaelgcs
slpcnlckagg--i-----ek--qlrvypdvdg
>ENV_HV2D2/24-513
eiks-dakrvtklq---------khssavhs-----krliaglpgnk---
--kat--------nftvilegvldsdpk---------------------m
pge--------ig-egicykcyfdlvyrqvldtkniirswwasravvhcf
ldkpgiaat---srr---cigrti---rvlkfh--------------q--
tlsk---nkfvklrinp-entkgdrle----ppwvdnap-ande------
-ilr-iadtfll-aadfacvkast-ng--lldtatca---k-e-qsk---
-fdifa---latflhplhn------v--g-gy-p-fht-------elf--
qpcvgpqaalicp--rcpqlflv--r------s----kekpv---cgeqg
rpvvgkykpktpmgm-----rp--------ak---------dscwa--dc
is------p--deyveidklkglh-----hk-sfraf-gcskvsqlresd
eycif----------ssfgsksyynw----------flskikgsms----
-plt-------avffy--t----lddkedvvg--qcagfhrg-------f
veksdlcyqanmllscgkedgtcktvvaap---lnpey-----nsta---
--kfqkclgfm-l-------vgli--------fvkrhtqardvtnhalpp
-atngspalddst--lt-da--qkfslletrefirfn-----kaanlgca
rl--vmyka-efls-----sk--glr-fpyvkt
>ENV_HV2CA/25-512
svks-dakrvskmq---------knrppvhg-----knlv----gqk---
--ngt--------nhsqvlsgvlqgdpk---------------------i
sgm--------lg-daicckcffdlqyrqiidtnviirdwwptkapvkcf
vnapgitat---trr---ctekti---hvlhfr--------------hhm
tlsk---nr-------p-vgtkgeklp----ppwsdtkp-lqde------
-imr-iadafvm-pashtcvkaal-sg--liksaaca---s-q-qhk---
-yntfaslslasflaplqn------g--g-syfp-eht-------elf--
shcvgpttavicp--rasaivli--k------s----rtkpl---ysenf
kpkvgkyksstplgmsinsykdanv----pgt---------dccwv----
-s------p--dtylevyklkglh-----hkpnfrtf-gcakiaqlrqsn
alclkgsvy------aafatkgyfdwrrqgvfgsqkfikattghmd----
-lll-------glffkpds----tedkkniln--dcagfkkg-------y
vqktdlcfdgktllacgkdng---civepn---lnqad-----agna---
--hfekclgylal-------pgni--------lmkrslrakevinhgtpk
-vtsgrpalgelt--ls-st--tkfsflqthdfirln-----ktanygcs
slcgvlikggd--s-----sk--glp-lpyvrt
>ENV_SIVG1/22-522
iitvhntaei---eessqganfyghvrsrss-----is-------rkv--
--saav-l----l-evvvlavvlngkgn---------------------g
vgesepshsqslg-dl--ikcffallaaetydgkiipnkwwrgms-gtc-
-dw---tvs-----------dpt-aqcvcmkihtrpplhgc----nse--
slav---vkfailkyqv-c--kgtmd-------lieqdpm--essgehki
tiig-ldel----stdtsvgqvgv-ig--lmtktccd---t-q-k-----
---------akpyiapsfk------s--g-eyhl-yhkrmlpgcaads--
s--mapkadfvsp--rserglli--r------g----rndpi---cdkqe
apkiieykpetasgh-----skane----pgg-fgganpkmdssrk----
-keskytsk--aeligie----etqfspdvr-kiklf-qcdsv----kak
sycqk----n----krskgrnggfnw----------yvhwetgavsl---
-------------ff-paamtgklqdkyeclk--hcvmfqks----lyva
vkkvklsyqffkglccgkenakknnskgssldw--neskh-gteatsllg
-htfnqc---v-lt------lgnm-----------rhdgpesganhatna
-dievsiamgehte-ln-tgsvtqfklltaaafidle-----adgelgcs
atpcnvckagp--i-----q---------dvng
>ENV_HV2D1/24-501
sikd-da---tkkq---------knrppvhg-----knlv----gqk---
--sgt--------shprvlkgvieddpr---------------------l
egm--------lr-daicckcffdmqfrqildtkmikrewwpkkavgqcy
ldspaitgt---thhdiscilkti---nqlkfr--------------l--
tmfknvknr------------ngnklp----vpw--nkp-qqne------
-ilr-vaetfvm-saghtcvqaal-ng--vid----a---k-q-qsk---
-fdtfqalslasynaplhn------g--g-syfd-fht-------elf--
qpcvgptkraict--rapklaqi--k------s----rakpl---csedg
kpqvgkyk--pplsvnvnswkmanv----pgg---------dmcwv----
-t------p--dqyvdveslkglh-----hk-sfrtf-gcskiaqlrqen
sfclk----------asfnskgyfdwrre-----qkfvsldhvaft----
-llldlgaricglff-gds----lddkknvvn--hccgfrrg-------y
vqkddlcysggtllacgkedgtcdsiveas---ld--------agga---
--hfdkclgfl-l-------lghi--------l------atevvdhstpi
-atngsaaqgett--ls-sk--tkfkllatr----ln-----kaadlecs
alpevvykggk--n-----sk--glr-ypygrt
>node18
sikd-dakrvtkmq---------knrppvhg-----knlv----gqk---
--sgt--------nhsrilsgvlegdpk---------------------m
vgm--------lg-daicckcffdlqyrqiidtkmiirdwwptkavvqcf
ldspgitgt---trr---cigkti---hvlkfr--------------q--
tlsk---nr-------p-igskgdklp----ppwtdnkp-qqde------
-ilr-vaetfvm-aadhtcvkaal-ng--lidsaaca---k-q-qsk---
-fdtfaslslasflaplhn------g--g-syfs-fht-------elf--
qpcvgptaavicp--rapqlali--k------s----rakpl---csedg
kpkvgkyksttplgmginswkpanv----pgt---------dscwv----
-t------p--deyveveklkglh-----hk-sfrtf-gcskiaqlrqsn
afclk----------asfgskgyfdwrrq-----qkfvsadngama----
-lll-------glffkgds----lddkknvln--hcagfrrg-------y
vqktdlcyngntllacgkengtcnsiveas---lnpen-----asga---
--hfdkclgfv-l-------lghi--------lmkrstqakevvnhstpq
-atngspalgeat--ls-st--tkfkllatrefirln-----kaadlgcs
slpgvmykggd--n-----sk--glr-fpyvrt
>node10
sikd-dakrvtkmq---------knvppvhg-----kslv----gqk---
--sat--------nhsiilsgvlegdpk---------------------m
vgm--------lg-daicckcffdlqyrqvidtkmiirdwwpskavvqcf
ldspgitgt---trr---cigkti---hvlkfr--------------q--
tlsk---nrfvkvrinp-igtkgdklp----ppwtdnkp-eqde------
-ilr-vaetfmm-aadftcvkaav-ng--lidsaaca---k-q-qsk---
-fdifa---lasflaplhn------g--g-gyhs-fht-------elf--
qpcvgptaalicp--rapqlali--k------s----rekpv---cseqg
qpkvgkyksqtplgm-----kptnv----pgt---------dscwv----
-t------p--deyveieklkglh-----hk-sfrtf-gcskiaqlrqsn
efcik----------ssfgskgyynw----------fvskdngama----
-lll-------glffkgds----lddkenvln--hcagfrrg-------y
vqktdlcydentllacgkengtcksiveas---lnpen-----asta---
--hfdkclgfv-l-------lghi--------fmkrstqakevanhstpq
-atngspalgeat--ls-st--skfklletrefirln-----kaadlgca
slpgvmykagd--n-----sk--glr-fpyvrt
>ENV_HV2BE/24-510
sikd-dakrvnrmq---------ktrpnvkg-----knlv----gek---
--ags--------nhskmlsgvlagepk---------------------m
vgm--------lr-eaicckcffnlqfrqlietkmiikdwwptkavaqcf
ldspgiegtkkh--------lk----------------------------
------------------lgskgdklp----ppwkddkp-hqne------
-ilr-qadtfvm-padhpcvk--l-ngkkvldspsca---n-q-htpavv
afanfaslnlasldaplhn------a--g-syfs-fht-------elf--
epcagptaaticp--rtgkleli--k------a----rakpl---csedg
npqvgkyktappvgmninswkrasv----pgt---------dscwv----
-t------p--dgyidvenlkglh-----qg-sfsef-gcskiaklkqsn
afclk----------anfgskgyfdrrre-----akfssgdnvama----
-lllnlntkicglffkist----lddrknvln--hctdfrrglnkr---y
vqktdlcysgntllacgkemgtcnsiveaa---lhpen-----ssgp---
--hfekclgfl-l-------hghi--------l------psevvhhstph
vatygspafteaa--ls-sk--sqfkltatknfvrln-----kaadlgcs
ilpgvmykggp--n-----pk--glr-fpyvks
>ENV_SIVM1/24-528
pisn-ngkrvskme---------knvppvhg-----kslv----ggri--
--sas--------nhaiitsgalsgspk---------------------m
vgm--------lg-daisckcffdlqyrqavdvkmmtrdwwsgkaigqcf
lewpgitgs---nrr---cignsi---dvlkfr--------------q--
tlsk---krfvkirinp-ydtkgeklpstaispwsdrkp-eqde------
-ilr-kahtlmm-madftcvqatv-ng--lyesaacd---d-q-qse---
-lgifa---lsaflallrg------g--g-gyhs-sht-------elf--
qpciapttalicp--qkpqlali--k------s----qdkpv---cseqe
epkigkeksqtsmgm-----kltnv----sns---------dscwv----
-t------c--defiaieklkgsh-----lk-kfrtf-acakvaelrqsn
dlcir----nydqnq-sfgspgyflr----------fvskndgama----
-lvl-------giff-adk----lddkdnvln--qcaafktg-------f
yhktdvcyaanaalacgkqngtcksivevs---lnperqk-ghapas---
--nfnicllfa-l-------lgpl-----------rstqaneiahnsnpq
-atdaaptlgeht--ls-dt--skdkllgvrefvrlnlvmqakttdpgca
slpgsmykagd--d-----dk--glrtfayirt
>ENV_HV2G1/23-502
sikd-dakkvtkmq---------knrqpvhgkklgfkslv----nqk---
--sgt--------nhsrilsgvvegdpk---------------------m
vgm------------licckcffdlqhrqiidtkmikrdwwpttavgqcy
lnlpgitgt----rr---cvgkti---hvlkfr--------------q--
tlsk---nr-------p-igskgdklp----ppwtenra-qqde------
-ilr-vaetfva-aadhtcvkgal-ng--lidsasca---k-q-esk---
-rdtftslslssflapvhn------q--g-syfs-fht-------plf--
qpcvgptaaalcp--rapqlali--k------s----rakpl---caeqg
khkvgkcksttplgmginswkpanv----pgt---------dncwn----
-t------p--deyveveklkglh-----hk-sfqsf-gcskiaqlrqin
tfcik----------asfgskgyfewrn----------aadngama----
-lll-------glffkgng----ladkknvls--hcagfkra-------y
iqktdlcynentlmacgrengtcnsivets---lnpdn-----asgp---
--hfekcigfv-l-------lghi--------lmkkstdakevvnhstpq
-atnsspplgeat--ls-at--tkfkllatrefirls-----kaadlgca
slhgvmykggd--n-----sk--glr-fpyvrt
>node14
sikd-dakrvtkmq---------knrppvhg-----knlv----gqk---
--sgt--------nhsrmlsgvleedpk---------------------m
vgm--------lr-daicckcffdlqfrqiidtkmiirdwwptkavvqcf
ldspgitgt---trr---cilkti---hvlkfr--------------q--
tlfk---nr-------r-igsngdklp----ppwtdnkp-qqne------
-ilr-vaetfvm-aadhtcvkaal-ng--vidsaaca---k-q-qsk---
-fdtfaslslasfhaplhn------g--g-syfs-fht-------elf--
qpcvgptaavicp--rapklali--k------s----rakpl---csedg
kpqvgkyksapplgmninswkpanv----pgt---------dscwv----
-t------p--deyvevenlkglh-----hk-sfrtf-gcskiaqlrqsn
afclk----------asfgskgyfdwrrq-----qkfvsadnvama----
-lllnlgaricglffkgds----lddkknvln--hcagfrrg-------y
vqktdlcysgntllacgkengtcnsiveas---lnpen-----asga---
--hfdkclgfl-l-------lghi--------l------asevvnhstpv
-atngspalgeat--ls-st--tkfkllatrefvrln-----kaadlgcs
slpgvmykggd--n-----sk--glr-fpyvrt
>node8
ivtvkknrei---e---------ghvppiss-----kt-------kkv--
--sapv-l----l-qvviltgvlkgdpk---------------------m
vgmsdvpqtqtlg-ti--ikcfftlnfsqvydadiignkwwagks-gec-
-nw---tas---hrr---cldptvqqceckkihdavalhgc----dse--
tlak---trfailrhqp-igtknqkv-------lidetp-eqesstkhkf
vila-vdef----ttdtsvvqvav-tg--lvsstccs---s-h-e-----
---------tkpfvapvyk------a--g-eyhm-yht-------adg--
s--mattadfvsp--haiqglli--r------s----rndei---cddqe
ppkivdykaqtplga-----geanq----pgn-fdgvrpipdssrr----
-retkfatk--aeyigie----dsrfssetr-kirmf-qckkv----kak
sfcik----n----krsfgqngsfnw----------yvqwetgamsqhh-
-lsl-------glff-paafftrlqdknecln--qcigfrrg----lfvy
vkkvdlcyqfftglccgkqngkknnsigdslas--getke-gteatslld
-hninkc---v-l-------lgnl-----------rsngpksaanhstnq
-dtevsvalgeht--le-ta--tqfrllssrefiels-----raaelgca
slpcdlckagg--i-----ek--tlrvfpdvdg
>ENV_SIVGB/47-569
--pakkyklg---d---------gaakp--------ht--------vlak
hislsvtlycavl-vatiqsgllmlh-r---------------------i
artkphpseeigv-aa--ikgyfpighgefydhsklggswrhifa-kgc-
-lw---sts---kdv---yrs---l-adcgkltdea---iirnhgek---
-ark---stgamllpmavggemsvgs-------shnqg---------rtl
atingkegg---tstkqmqhaagvskg--vtketccpgeag-psk-----
---------dapymqtrgrteafqdtqiakinfsgyi----------fgt
p--lk-sa--yhpaphgtsp-pggprkipkdp-------n-risqrhetg
fmkieqympr-slsa-----gegasariapsitfqqtr-l---cpkst--
-wa---ltqss-nfegiq----lnrfhamyh-rvh-----tkl----dp-
-lcvk----k----t-qfagslvyfw----------ngewdiksivpnnl
qeam-------glaf-ev--fsrltalsvcfqyleh-p---l----ffky
yrkaelfhhhlkniccgkenskga-kesg--nt--tlqrdhgpsggtvvg
d---------l-f-tgltssqgpl-----------rargkkcahrhapse
-k---stdvkpev-rlnvsa--v--dlvckksiktnt-----fslkggct
miacekcak-i--llnrlcanrpgkrsgparae
