>ENV_SIVG1/22-522
tarerp--s-qsh--------fgfisl--nkliylwklnvghvpl-tpsf
pcv-----srkkac-fagkgska-----n--egg--faqr--q---lapn
agqrg---------------qvlwngal-khrkinmlrp--pftvs-tyh
nelan----------tgvenvdakn-------dwvatgktl-aqglalin
qmgflrvklit-lrapekragdsidlgaag--vnarndeeqagivtikle
pklgl--rhgepiesldnlgvh---hvlrvtgse--t-a-kseekivivg
kyaaet--kqap---ekps-------------vf---ctegysttnfkvp
gglksstflqlaiaynryswp--cerpettdnvspahc-k------kpwg
i--q---alyvkn-r-lfcvfacatt-----h---eavihl----yhlsp
egngqlv-vg----eiltslygsvg---gnyhh--------ekglvavs-
--v-------nctsall-----fpk-------hgq----sgqa-------
----vsncvgre----------e-ttkct-afathkkakv-sd-ts----
----------------tasg---nqkpapgglwaetdkpsedghiqnpnt
nkyrfsr------tagydyvtfdaq---a-kacaadggl----lrlaltp
vl-----qglea-siqmsaannlmlkefdsrp-----pakftn---vn--
-----vdlpnapsih----------n-efvqcdvve-----cdk
>node17
vkkvdi--s-tav--------yafinq--nqliifrklkvsrlal-iptl
pcv-----glndec-fvvrssge-----d--dsa--fner--tigdst--
-------------------------vei-kctnhamlr----favs-kqe
gcltvakngheeaskmgvaavegfn-------twtgstkaitsghlylst
haqfgrvkalt-lrvesq-------l---gahavslhveedavittlkls
vkldl--knnfhedtsekmgan---ptanaiskr--s-a-keaidlfrsk
nstglsqkqpag---dagg-------------if---vasgyv-----ha
gnlqggtmahvttsfqrkq--q-cdrsvtgahmmtg-ckr------kswk
f--n---pvyhkn-k-ylcllecavp-----a---dpifnm----fhlpp
dphsdfavip----nvaagmyvsvg---tnydkevstlwggsgqlfelvv
tvv-------kc---ll-----fcr-------qcqnveepaqd-------
----aahcvs-s----------h-nyssi-n--hankvnv-re-------
--------------------q--qass-----------------vqdpgt
dtfafdphttlraty-----tispvrslq-dqagatkvi----salr--a
nl-----ngkqv-emnmepadcpvckdfeyna-----pasfps---fn--
-----ieasgspkvh----------glqfttckltq-----vqk
>node18
vskvni--s-tav--------yafinq--nqliifrklkvsrlal-iptl
pcv-----glndec-fvvrssge-----d--dsa--fner--kigdst--
-------------------------idi-kctnhavlr----favs-kqe
gcltvakngheeaskmgvaavegfh-------twtgstkaitsghlylst
haqfgrvkalt-lrveaq-------l---gthaaslhveedntittlkln
vkldl--knnfhedtsekmgan---ptanviskr--s-a-keaidlfrsk
nstglsqkapag---dagg-------------if---vssgyv-----ha
gnlqggtmahvttsfqrkq--q-cdrsvtgahmmtg-ckr------kswk
f--n---pvyhkn-k-flcllecavp-----a---daifnm----fhlpt
dphddfavip----nvaaglyvsvg---tnydkevatlwggegqlfelav
tvv-------kc---ll-----fcr-------hcqnveepaqd-------
----aahcvs-s----------h-nysci-n--hanksdv-re-------
--------------------q--qass-----------------vqdpgt
dtfafdphttlraty-----tispvrslq-dqagatkvi----salr--a
nl-----dgkqv-kmnmeaadcpvckdfeyna-----pasfps---fn--
-----ieatgspkih----------glqfttckltq-----vqk
>ENV_HV2G1/23-502
vskvnv--s-taa--------yafinqrngplvvfcrlqvtllal-ipsl
pcv-----glndec-fvvrssgd-----d--d-s--fner--kigdvt--
-------------------------idi-kctnhgvlr----faisfrqe
gcltvaknghdgaskmgvaaiegfl-------twtgstkai-terlylst
haafgrvkapt-lrpsaq-------l---gshpaslhveedhtittlkmn
vkldl--kndfhedtseymvsn---ptanvlskr--s-a-keavdlfat-
---------------degg-------------if---vsrgyv-----hp
snlqggtvadvtltftrkq--d-cdrsvdgahmmtg-cdr------kswk
f--n---piyhrn-k-flcqlecavp-----s---daifkm----ihlpt
dphedlavvp--tadvaaglyvsvg---tnydkevstlwgsegqlyqlgv
tvv-------kc---vl-----fcr-------hca-veepgqn-------
----aahcva-s----------h-nysci-e--hlnksdi-re-------
--------------------q--qatt-----------------vknpgt
dtfardpfttlraiy-----tispvwsleqdqtgatkvv----talr--p
nl-----dgkdv-klnlgasncpvckeheyna-----ptsfps---fg--
-----mqatgspkin----------glqaqtcklte-----vqk
>node14
vakvni--p-tai--------yafinq--nqliifrklkvsrlal-iptl
pcv-----glnaec-fvvrssge-----d--dsa--fner--kigdst--
-------------------------idi-kctnhavlr----favs-kqe
gcltvaknghdeaskmgvaavegfh-------twtgstkartsghlylst
hapfgrvkalt-frveaq-------l---gthaaslhveddntittlkld
vkldi--knnfhedtsekfgan---ttanviskr--d-a-keaidlfrsk
nstglsqkapag---dagg-------------if---vssgyv-----ha
gnlqggtmahvttsfqrkh--q-cdrsvtgahmmtg-ckr------kswk
f--n---pvyhkn-k-flcllecavp-----v---daifdm----fhlpt
qphddfavip----nvaaglyvsig---tnydkevaslwggegqlfelav
kvv-------sc---ll-----fcr-------hcqnveepaqd-------
----aahcvs-s----------h-nysci-n--hanksdv-re-------
--------------------q--qass-----------------vedpgt
ttfafdphtalraty-----nispvkslh-dqagatkvi----salr--a
dl-----dekql-kvnmeaadcpvckdfeyna-----pgsfps---fn--
-----ieatgsphih----------glhfspckltq-----vqk
>ENV_HV2CA/25-512
vkkvdi--s-tai--------yafinq--nqllifrglkvsrlal-ivtl
pcv-----slndec-fvvrspge-----d--dsa--freh--tigdtt--
-------------------------vdi-kctihamlq----faia-kve
gcltvaknghveakkmgvaavegfn-------twngssk----ghlylat
htqfgrvkalt-lrvqvq-------k---gahaitldaeegavitslkln
vkldl--knnfhedtsekmgpn---ptesginkq--s-a-keaiellrsk
qetglserqqag---daggisgctriev----if---vapgyv-----kn
gnlpggtmahvtvsfqraq--l-sdkcvsgahmmtg-ckr------kpwk
f--g---pvyhan-k-yicllecavp-----a---dpifnm----fhesp
dphsdfavip----niaagmyvsvg---tnydkvvstlwggsgslfelvg
svl-------rc---ll-----fck-------hcqdltepaqd-------
----gahcis-t----------h-nyssi-n--hankvnv-re-------
--------------------q--qass-----------------vmdpgs
diftldphtnlrasy-----mctpvrslk-dqagaskvi----salr--a
nl-----nsktv-qmnm---dcpvckdfeyna-----pasfps---hg--
-----feprgspkvh----------glqfttckltq-----vqk
>ENV_SIVGB/47-569
laghks--l-dgstpgkdknmfhfvnv--c-lflfgkfqeamnrfkvt-l
ltkmkqdqrmkkvs-lvgqvyikttanvdrttkgsivq----n---iphn
pnave---------------nslwhaai-q----pdsqhvf-gtyn-gsl
namg--------------gttqgprpkvktqvkwnwackya-pqlmafeh
stiallc---cssrvvdd-------q------ikgkt--nrstmkqipvh
sdlsl--rdahvka-------------------n--nllcecppklsfke
gyldid--ttiqnvfsegv-------------------lkgypvynlk--
-sltlgkvplisckaaky-----i-cdpsledssgsep-kqvaadilvwg
rtaq---tl-----relhvrlafavw-----e---eaitsldiplflfk-
-shvqckg---------qsrfvi-------fep--------ngsmqglq-
fkg-------kc---edlspgv--qilttatrhiq----pdhr-------
--npvancggagksaivgltakksayasvr-----rnskl-akqqaahas
vlndlsgtgykadtrlssskl--g-teeptsat------------kghsa
divqyqt------fpad-----tck---d-nktgchgkv----lk--lap
llavklksyltvarkvitsvd-ycv-nfk-iqttsege-nfa----ihkg
relvlgsnpklytfdgkfntgqkvln-afpdc-klqdlqnqsga
>node8
vardap--s-rth--------fgfigv--nklvffwklkvghlpl-iptl
pcv-----smkkac-fggdsska-----d--egg--ftqr--s---aass
agqra---------------evlwndai-khkklhmlrp--pftia-tdh
nalsn----------igvvdiegrh-------twggaaksl-sehialts
aggfsrvkvlt-lrvldt-------l---g--vqgkpaeeqativtikvd
hkldl--knssqiesadnlgvh---hslsvtane--t-a-kpeekliymg
kytaet--kqga---ekas-------------vf---ctegyshtsfkhp
galkdgtflqitssfnrys-s--csrpetldnvspahc-r------kvwg
f--q---slyqkn-r-llcllncals-----q---eavihl----fhlsp
eshgqlvivg----niftglfvavg---adyek--------ektlvalsa
trv-------nc---ll-----fpk-------hcq----paqa-------
----vsncvgrg----------d-tykca-t--gnkkakv-sdsta----
----------------tsggl--hptpgpgglraetdkitedghiqepst
nkfrfsh------taaydyptfdpv---e-kacgadgrl----irlaltp
pl-----dslev-kilmaaadslvlnefdsra-----pasftg---ve--
-----vdisnvssiq----------n-efvacdqve-----cgk
>ENV_HV2D1/24-501
vakvni--p-tai--------yafins--gqliifrklkvsrlal-vpvl
pcv-----glnaes-fvvrssgq-----d--dta--fner--kigdst--
-------------------------vdi-rivnhavlr----favs-kee
gcltaaknghdeadkmgvaavegfh-------twtgs----tsghlylst
hapfnrvkalt-frvhaq-------l---athatglqvadentistltld
velni--knnfhedtsekfgan---ttanliskr--n-a-keaidlyrsk
nstglqqktpag---dasg-------------if---lnsgyv-----ha
gnlqggtmahvttsfqrkh--q-cdrsvkgehlmtg-crr------kawk
f--n---ptyhkn-k-flallecsvp-----v---daifdl----thlpt
qphddfaiip----nveaglyvnig---cnydkdvts----egqlfelev
kvl-------sc---vl-----fcr-------qcqnveepsqd-------
----amhcvs-s----------h-nynci-h--qanisda-rk-------
--------------------q--qass-----------------vedpgv
ttftfdphtdlraay------ispikslh-dhagatkvi----tklr--a
ki-----dekql-ktnmeapdcsvctdfnyna----------s---fd--
-----iqvtksahih----------glhfspckltq-----vqk
>ENV_HV2BE/24-510
vtkvnisqp-tai--------fsfinq--nqlftfpklkvtrlal-iptl
pcv-----glnaec-flvrgsge-----d--dsa--ygdh--digdst--
-------------------------sdi-kctnhavlr----favs-vqe
pcltveknghaeaskedvaavegfr-------twtgstqartsghlylst
hgafgrvkalt-frvekq-------m---gmhptsleveddntitplkld
vkfev--kkhlhedtserfgan---stanvislktid-a-keakelfrak
dstglsqkapag---dagg-------------if---vsggyv-----ha
gklqggtvahvtvsfqrkn--n-cdrsvtgahmmdg-cnr------kswk
f--n---pvyhkn-q-f--lldcavp-----vrscdaitdm----fhlpt
qphhqfatip----nvastlyvsig---tdydknvtelwggkgdlfelav
kpv-------dc---ll-----fcr-------hcqhvedpaqd-------
----ashcvs-s----------h-nysci-n--hsnks------------
--------------------q--qass-----------------vddpgt
ttfrfdphtalraty-----nispskslh-dqagttkvv----aalr--a
dl-----dekel-dvnmekapcpvckdleyna-----pgsfsa---fn--
-----igetkslhih----------plhfspckltq-----lqk
>ENV_HV2D2/24-513
vskmni--s-taa--------yafind--nqliff----vdrlaq-vvtl
--v-----glkdacpfvvwssgd-----d--nsa--fndr--kigdcp--
-------------------------ddv-kcashavlr----fsls-ked
gcittqkkghielskkgvvaiegfh-------twsgavkav-sghvylta
hgqfdlvkalt-lilesq-------l---gthaqtmsihepddittlkni
vklnlviaesshnntselmgvn---stahiaslr--s-a-dpafrkfktk
nyteetqdsaag---kagg-------------ifngsvaaayg-----ha
galegstmaqcslcfhrkp--egcnrgvtgahmmtglckr------ksrs
f--n---plfhki-r-flcflecavk-----s---daigtv----lhlpt
aphddfsvlasg--nvatglyskvg---tnyekevatlwggegqlfeyas
tvv-------nc---ll-----lck-------hseksgeppqk-------
----gahcvs-t----------h-dyscv-n--hatksnv-re-------
--------------------hnaqasv-----------------iqlpgt
dkftydsyatlraey-----tidsvkslp-iqgsatavp----sslr--g
dl-----dgkqv-kmnmeatacpacpdfeyha-----pasyptadcpk--
-----feltstpkiq----------glqfatcnlvq-----cqk
>ENV_HV2NZ/24-502
vrkvdi--a-tav--------yafihq--tplivfsklkvnrlal-ipal
pcv-----gfhdec-fvirpsge-----k--dsa--fner--tigdst--
-------------------------vei-tctnhsllr----fava-kqe
gcltvadnghkeadkmsvaavygfn-------iwtdntkaitsahlylst
yaqfgrvqalt-lraesq-------l---aahavspqikedaviitlkls
vklql--kdsfhedttekmgan---ptanshlkr--s-a-keaievfrsk
nakglsqkqpag---dggg-------------if---vatgyv-----ha
gtlqggtmahttttfhrkq--e-cdksvtgshvmtg-css------kswk
f--s---plyhkn-y-ylcllecavpkwkkdg---dpifnm----fhlap
------avip----nvaagfyvsvsvpstnydkgssalwggsgqlfglvv
ivv-------kc---fl-----fch-------ecqyvddpaqn-------
----aahcvs-a----------h-nyari-n--nankvnv-re-------
--------------------e--qass-----------------aqdfgt
atfafephqtlraay-----tvspvrslq-nqagntkhl----stlr--a
dl-----ngkqv-vmhmvpvncpvckdfqyda-----pasfas---fr--
-----ieasghakvh----------glqfttckltq-----iqn
>ENV_SIVM1/24-528
vsrvai--g-kav--------ykfcdv--nqliffrklkvtklsl-ipsl
pca-----smkqac-tvvrdsea-----a--esv--fstlwlkvggcg--
-------------------------dai-kckrhavlrp--pfsvs----
gclhvdrkgheeassmsvvavqgfh-------twsgatkai-aghlylyt
hvefnrhkals-lpv------------------ddvhadenktittlkvq
velal--kanlhndsaenmgan---ptanvisnr--a-a-keatglfwsk
nyfgst--tegg---gegg-------------if---cssgyg-----ha
anlqggtveqittcfhrks--e-cdheattahmatglckr------kswq
f--hgagpvyhkd-r-ficllvcama-----a---datynm----fhlpd
dpyddyavcp----niaaglyvavg---tnnedevkalwggegqlvalal
--vllgrvaarc---ll-----fck-------hcqhiegptqd-------
----aahcns-s----------n-kytci-k--htrkskv-rt-------
--------------------q--eassagsglra-vdkveeagkiqepgt
dkfgydpfttlrvtytsafltidpvhslq-dlagatahegtgqaplp--g
nl-----pskev-ganmaptscpvckdfeynv-----pvsfpn---fd--
-----feasgttkvq----------vlqfsmcalre-----cqk
>node19
vskvni--s-tav--------yafinq--nqliifrklkvsrlal-ipsl
pcv-----glndec-fvvrssge-----d--dsa--fner--kigdst--
-------------------------idi-kctnhavlr----favs-kqe
gcltvakngheeaskmgvaavegfh-------twtgstkaitsghlylst
haqfgrvkalt-lrveaq-------l---gthaaslhveedntittlkln
vkldl--knnfhedtsenmgan---ptanviskr--s-a-keaidlfrsk
nstgltqkapag---degg-------------if---vssgyv-----ha
gnlqggtmaqvttsfqrkq--q-cdrsvtgahmmtg-ckr------kswk
f--n---pvyhkn-k-flcllecavp-----a---daifnm----fhlpt
dphddfavip----nvaaglyvsvg---tnydkevatlwggegqlfelav
tvv-------kc---ll-----fcr-------hcqnveepaqd-------
----aahcvs-s----------h-nysci-n--hanksdv-re-------
--------------------q--qass-----------------vqdpgt
dtfafdphttlraty-----tispvrslq-dqagatkvi----salr--a
nl-----dgkqv-kmnmeaadcpvckdfeyna-----pasfps---fn--
-----ieatgspkih----------glqfttckltq-----vqk
>ENV_SIVV1/24-538
tasiap--snrsh--------yqfngi--knlvafwklkvghlpl-vpsl
pct-----trkkgc-fggssska-----d--egg--faqr--n---isvs
vgergawndlefdryptwqtqvlwnseigkhskldmrkp--sftta-snn
qqlsg----------egvveihgrd-------dwvaaseai-aqgvalsn
lgaflkdnlis-lkelpvrsydsitd---g--vperhkeqqasivtv---
hkigl--khgeqtealdnlgvhctahrmkvaggn---------eksiymg
knsaet--kqal---enaa---------ightvy---ckqaystvcfrlt
gslkdatmlqlte-ynryawq--cqrpdeldgtspvrc-r------kpw-
--------lykkkrr-lfclldcsvs-----h---eavlsa----ftvsp
eghgnlv-vg----yiftgnyvs--------------------tlvavs-
--s-------gc---ll-----fpr-------hcq----ngqpvegaipk
rg--vsncvgws----------d-ttkca-a--ddkkekltsiata----
----------------assg---hhkptqggqwaeaekstqdgqtqnpas
-----------------thppfdal---e-nscaaegsl----lrlalka
vl-----dalqi-nvllvaaegfvlnef--rv-----pikytg---ve--
-----vdisdvataq----------n-tfkvcilvq-----cdk
>node7
tareap--s-rsh--------fgfigv--nklvyfwklkvghlpl-ipsl
pcv-----srkkac-fggngska-----d--egg--faqr--s---lavs
agqrg---------------qvlwngai-khsklnmlrp--pftia-tnh
nalsn----------tgvieidgrn-------dwvaagktl-aqglalis
aggflrvklit-lraletragdsidl---g--vhgrhkeeqasivtikle
hklgl--khgeqiesldnlgvh---hslkvtgne--t-a-kpeeklvymg
kyaaet--kqap---ekas-------------vf---caegysttsfklp
galknstflqltntynrysws--cerpetldnvspahc-r------kpwg
f--q---slyskn-r-lfcllncats-----h---eavihl----fhlsp
eghgqlv-vg----eiltglyvsvg---adyhr--------ektlvavs-
--v-------nc---ll-----fpk-------hcq----sgqa-------
----vsncvgra----------d-ttkct-a--tnkkakv-sdtta----
----------------tssg---hqkpapgglwaetdkstedghiqnpst
nkfrfsr------tavydyptfdal---q-kacaadgsl----lrlaltp
vl-----dslqv-dilmaaanslvlnefdsra-----pakftg---vd--
-----vdisnvasiq----------n-qfvdcdlve-----cdk
>node11
vskvni--s-tav--------yafinq--nqliifrklkvsrlal-ipsl
pcv-----glndec-fvvrssgd-----d--dsa--fner--kigdst--
-------------------------idi-kctnhavlr----favs-kqe
gcltvakngheeaskmgvaavegfh-------twtgstkai-sghlylst
haqfgrvkalt-lrveaq-------l---gthaaslhveedntittlkln
vkldl--knnfhedtsenmgan---ptanviskr--s-a-keaidlfrtk
nstgltqkapag---degg-------------if---vssgyv-----ha
gnlqggtmaqvttsfqrkq--q-cdrsvtgahmmtg-ckr------kswk
f--n---pvyhkn-k-flcllecavp-----a---daifnm----fhlpt
dphddfavip----nvaaglyvsvg---tnydkevstlwggegqlfelav
tvv-------kc---ll-----fcr-------hcqnveepaqd-------
----aahcvs-s----------h-nysci-n--hanksdv-re-------
--------------------q--qass-----------------vqdpgt
dtfafdpfttlraty-----tispvrslq-dqagatkvi----talr--a
nl-----dgkqv-kmnmeaadcpvckdfeyna-----pasfps---fn--
-----ieatgspkih----------glqfttckltq-----vqk
>node9
vsrvai--s-kav--------ygfidv--nqliffrklkvsrltl-ipsl
pcv-----gmkeac-fvvrssga-----d--esa--fner--klggca--
-------------------------dai-kcknhavlrp--pfsvs-kqd
gclhvakkgheeaskmgvvavqgfh-------twsgatkai-sghiylst
haefnrikalt-lrveaq-------l---gthqqslhadenktittvkvd
vkldl--knnfhndsaenmgvn---ptanvisnr--s-a-keainlfwsk
nyfgnt--tagg---degg-------------if---cssgyg-----ha
gnlqggtvaqittcfhrks--e-cdreataahmatglckr------kswq
f--h---pvyhkn-r-flcllecams-----a---davfnm----fhlpe
dphddfavip----nvaaglyvavg---tnyekevktlwggegqlvdlav
tvv-------kc---ll-----fck-------hcqhvegpaqd-------
----aahcvs-s----------n-nytci-k--htkkskv-re-------
--------------------q--qassaggglra-vdkveeagkiqepgt
dkfafdpfttlrvtyasafltidpvrslq-dqagatami----tplr--g
nl-----dskev-kmnmaaadcpvckdfeyna-----pasfps---fd--
-----ieatgtpkiq----------glqftmcdlre-----cqk
>node10
vskvni--s-tav--------yafinq--nqliffrklkvsrlal-ipsl
pcv-----glkdac-fvvrssgd-----d--dsa--fner--kigdca--
-------------------------ddi-kctnhavlr----fsvs-kqd
gcltvakkgheeaskmgvvavegfh-------twsgatkai-sghiylst
haqfgrvkalt-lrveaq-------l---gthaqslhveenntittlkvn
vkldl--knnfhddtsenmgvn---ptanvisnr--s-a-keainlfrtk
nytgltqksaag---degg-------------if---vssgyg-----ha
gnlqggtmaqvttcfhrke--q-cnrevtgahmmtglckr------kswk
f--n---pvyhkn-r-flcllecavs-----a---daifnm----fhlpt
dphddfavip----nvaaglyvsvg---tnyekevstlwggegqlfelav
tvv-------kc---ll-----fck-------hcqnveepaqd-------
----aahcvs-s----------h-nysci-n--hanksnv-re-------
--------------------q--qass-----------------iqdpgt
dkfafdpfttlraty-----tidpvrslq-dqagatavi----tplr--g
nl-----dgkqv-kmnmeaadcpvckdfeyna-----pasfps---fn--
-----ieatgtpkiq----------glqfttckltq-----cqk
