>ENV_HV2NZ/24-502
vyvtngrhlg---ydh--irvl-------gg--hscdkrksll----akr
vldgl---lglfkgtrsaetgspgtiskc-v-----------rlpe----
-lfkacs-fvtgiq---ahcdgsg-pkm----teeklvkekgcgvmv---
--vlaclthddpiakev------sg--lls-vallrgknwqdlpsywsqe
pvvflek--nvtslvlsaglisgygpgqfypaa-------srns-aktdh
glaaphrelt--eytc-------srtrtfd---------cfqdrninphp
ask-sdgtkkttfs-krayagl--pnrclgkqshlvg-----f--pgpvd
h---avnt--------saysylpkff-----rwg--krwvvdhckskskl
tsvnklf--cgqc-saah-ka--s-----ggnqqk-------------ct
al---pfngyc------hr-alieakcp---e-----------a----vg
pgavekdr-------hssitailgfcftrplvkillasylndaqmggvtd
rvaisetwgvgt----nkcedphvalrcpkilrlcgstaghlrfskeqlg
fn-gpt--nleds-----ykeeqv------ykkvn-agftrl-asadpln
imrskdiv-aaak-lyvtel-----kn-lvcersndfsdsvt-g--lyrk
tm----
>node14
vyvtegrhlg---ydq--mrvl-------sg--pscdqrssll----gkr
vlqgl---lgpfkgprstetgdpgaiqkc-v-----------klpe----
-lfkacs-fqggvk---ahctgsnkpkm----teeklvkekgcgvmh---
--v-aslthddpiakde------dg--lls-vsllrgshwqdlpvywske
pvvflek--dvtslvlgaglipgygpgqfypaa-------srns-s-tdq
glaaphrelalneytc-------artktyn---------cyqdrnlpphg
tsk-sdghkknfts-kraydalktpnrcegkqehlvg-----f--v--vd
h---evna--------sayfflpksf-----rwg--krwivnhckakssl
ttvprln--cghc-taah-kglaa-----ggdqlkdrp------sr-mct
al---pfngyv------h--alieakcp---e-----------a----vg
pggveqdr-------nlsvtaylgfcfnrpllkillasylndiqpgevks
rvaigiawgrvt----k-----avalrchpilrlcgptaghlrfgkaqlg
rd-sgt--nleds-----ykhqsv------fkdin-afsarl-gaahpln
imkskdiv-asar-lfvpel-----ks-lmcerttsfsdalt-d--lfrk
tm----
>node8
vyicagkhlg---ydq--kqpl-------vg--psrhkmrgfv----gfk
vlkalpskvgqfk---itgqgn-----------------------efavs
klfrtcmlivdsvt---lnc-dnhganvpappgedsivh-----------
-------wndqpaa--------------------lwg-----------rq
aeltlek--dhksvvldas--cgtgvgpiivdp-------arht-r-lgq
gldgphaelnmesasyl------aqkktya---------cyngraksnkg
------dtpgttkp-kqryavvraqdplagdesnlvg-----f--rgpvg
hlsadvns--------cvfylldnatggvatqwt--snwe--dcpqkkdl
av--pna--igns-pdah-k-h-------ggdgltgrp------sr-lcn
sl---pvvgyp------yi-atieypcr---g-----------a----vn
nngidkak-------sftvnp--gfcgarglmqi---------rrskait
kis--vpwgasp----n-----avsfrshpilrlcgasaghkrfvkghrg
rp---t--klqka-----ytvkfi------fkkygkcgqnrlggpgcpyp
sqknkdii-aapkqvfgpel-----kt-s----tagycpdlpyt--tlkd
gv----
>node7
ayicaaahlg---yag--kqpl-------vg--parhkmrgfi----gfk
vlkalprkvgqfk---itgqgq-----------------------efavs
klfrtcmlivdspt---vec-dnhgavvpvppgedsivh-----------
-------wnnqpeg--------------------lws-----------rq
aeltleklgdhksvvl-at--cgagigpvlval-------vrht-r-laq
gqdgphgelniesashl------sqkktys---------cysgrpksekv
------nttgstel-kqrfevvrvqspllgeesnrvg-----y--rgpvg
hltadang--------cvfylldnakvgvatnwt--snwe--dcaqkkdq
gv--pnasgisgs-peah-k-h-------gg-gltgrpgqkeilsr-lcd
sl---pvqgyp------yi-----ypck---g-----------a----in
anavdkak-------nfntnr--gicgarslmqi---------rrnkait
iis--vpweasa----d-----avsfrnhcilplcgasaghknfikghng
rp---tmirllnl-----ygvkfigdtpsayykygkcgaaklggpg---p
sdkdkdii-aapkqvfgve------kt-s----tsmycpdlpyt--tlkd
pv----
>ENV_HV2CA/25-512
vymtgsrhla---ydq--krvi-------ggcipqcekrrsll----akn
vhdgl---lspfkgpratqtgdpaaiskcsv-----------rlse----
-lfkacs-avtgvk---ahcagsnkpkm----tdeqldkekgcg------
----esltqddpiakqe------sg--lls-vtllsdthwqnlsvywskd
gvvflek--dvtslvigsglisgygpgqfypaa-------srna-a-svq
glaaphrelsldeytc-------vrsktfn---------cyverglsphp
tst-sdgskkttas-trrydgl--pnrca-kqehlvgacer-f--pgpve
h---einc--------rayffvpksf-----rwg--krwivnhcnsksml
ssvnrln--cghc-sran-kg--v-----ggillk-------------ct
al---gfndyc------hs-alveakcp---e-----------a----vg
pggvdqar-------n--vsmylgfcfsrgllkillesylndvqppgvks
svaigiswgigt----n-----svllrchpvlrlcgstaghlrftkaalg
fa-gpt--kldds-----ykqqsv------fkdin-agst---npgdpln
imkskqvv-aatk-lfvpeg-----ka-lmceptiefsealt-g--lfqk
tm----
>ENV_SIVG1/22-522
gyicapahlk---ytg--pqpl-------vg--parhkvrafv----gsk
vlkvlsekvgqfk---ingqgq-----------------------efavs
klfrtcmlvvdsvt---vec-dnhcavvlvppdldaimh-----------
-------wnsqpqg--------------------lws-----------rq
kgltleklgahksgvf-ag--cgagiglvldal-------ikht-r-laq
gddapngelgiesashl------sqkktys---------cfsgspksekv
------dttgstel-kkrfeivrvqsplldeasdrvg-----y--rgrvg
hl--dang--------ivfyladnakvgtatnwt--snwe--nceqkkdq
gv--pdasgisgg-pdah-t---------gg-gltgrpgqkevlsr-lcd
sl---avqgyg------yi-----yqck---g-----------a----in
tasvdkpk-------nfnysr--glcgarslkdi---------krskait
iis--vpweasr----n-----avsfrnhvilplcgssadhknfleghng
mp---gmirllni-----fgvkfqghtpsayykygkcgaatlggps---p
cakdksii-eapkpvygtd------kh-s----tsmycpdlpft--tlke
pi----
>ENV_SIVM1/24-528
vyvaegrhvg---ydq--mrvl-------sg--pacdkrrnlv----gkr
vlqgq---lgqfk---vteagdpgniqkc-v-----------slpewsre
kfikeck-fvtgvi---lhcvgsnegkm----nedkfvkvkgcgimq---
--k-gaithddpia-------------llt-vlllkg--wedvpldw---
---fldk--datrlvlggllicgtepgqiipip-------arns-r-ndq
gvstphadlslnesscf------artkafn---------cfhdrhlsphg
tan-sggrkqkaks-krayealstqspcdgkqghlva-----f--pgpvg
h---disc--------sayyilpkgi-----vwg--kgwlvhhcksksdl
ttpcrln--c----------nhks-----agdelkgrp------sr-mct
am---pfngyv------yt-aiidykcp---a-----------a----lg
gagvdqnr-------kltlraylgfcldhvlmrilmatylnv---ggvid
sva--ipwgqgt----k-----av--rchpclrlcgthsgnlrlvktqlg
kt-sdt--nleag-----ykqqsi------fkelg-agpirl-gaacplk
gmkskdiv-taatglfvpelgnlvcks-l----tagyadkla-d--lakk
tv----
>node9
vyitegrhlg---ydq--mrvl-------sg--pscdkrrnll----gkr
vlqgl---lgqfk---vtesgdpgaiqkc-v-----------klpefsva
klfkacr-fvtgvt---lhcagsnkakm----nedklvkqkgcgvmq---
--r-gslthddpia-------------lls-vyllrg--wedlplhwske
pivflek--dstrlvlgaslicgtgpgqfipap-------srns-s-tdq
glsaphadlsldestcf------artksyn---------cyhdrhlsphg
tak-sdgrkqktks-kraydalktqnpcegkqghlvg-----f--pgpvg
h---dinc--------sayyllpkgi-----pwg--kgwivhhcksksdl
ttmprln--cghc-saeh-kshka-----ggdelkgrp------sr-mct
al---pfngyv------yt-avieykcp---e-----------a----vg
gagvdqnr-------kltvqaylgfcfdrvlmkilmatylnviqqggvid
sva--ipwgrgt----k-----avalrchpilrlcgttsghlrfvkaqlg
ra-sgt--nleds-----ykqqsi------fkeig-agaarl-gaacpln
smkskdiv-aaarglfvpel-----ks-l----ttgfsdala-d--lakk
tv----
>ENV_HV2D1/24-501
vl--qgrhlg---ynq--mrvl-------sg--pncdqrsall----gkr
vlkgl---lgpfkgsrnaesgdpgsiqkc-v-----------klpe----
-sfkacs-fqggvk---ghctgsnkpkm----leeklvsekpcgimhlfe
avv-aslthddpiakeetfnalpdgaqlls-isllrgshwadlpvywske
pgvflek--evtslvlgaglipgygpgqfypaa-------lrds-s-qdq
glaaphrefalneyac-------artktya---------cyqnrnlpphl
tfkfsdghkknfta-kraydalktpgkcegkqehlvg-----f--v--vd
h---evna--------sayfflakgl-----rwg--srwiikhcramsnl
ntvprln--cghc-saah-kglaa-----ggdqvkdrp------ap-mct
av---pfngyv------n--alieaksp---e-----------a----vg
pggveqnq-------nlavtayigfcfnkplmkillvsflneiqpgevkt
pvaiaiawgrva----k-----apamrcypilrlcgpn---lrfgkaqlg
rd-dgi--nleeslam--ykhqsv------fkdin-afsarl-gathpln
imktkeiv-astr-lfvpel-----ks-lgcerttsfgdalt-d--lfrk
tm----
>ENV_HV2BE/24-510
vyktegrqlg---ydq--lrll-------sg--pscdgrsslladekgkr
vlqgl---lgpfngpratdagdpgavdkc-vhvdagvkrrscklpe----
-lfkgcs-fqggyk---ahctssnkpnm----teeklvkekgcsvmh---
--v-atlthddgvakee------eg--llssvtllrgsnwnempvcwste
gvvflek--evtalilgaamipvygpgqff-----------------ndq
gltasrrel---eytc-------nitktynssggeasafcyldrnlpgqa
tpr-seghkkdftsikkaydalktpsksegkqehlvg-----r--v--vt
h---evps--------sayffipasf-----rwg--kswivnnckakssl
ttvprlg--cghc-taah-kglag-----ggkqmknrp------sr-mct
al---pfngyv------h--alieakcp---e-----------a----vv
pkgieqdr-------nmsvtaylpfcfnrpllktllasyiddie----kn
avaagiawgavg----k-----avamrchpilrlsgptaghlrygraqlg
rd-pgt--tleds-----ykhmgv------fknin-yfsarf-gpahs--
----------saa-lfvpel-----ks-lmcerttkfsnavt-d--lfrs
tm----
>ENV_SIVGB/47-569
ay-c-dafla---eeg--iaer-------ig--k---------------n
sikalegqikplr---vkptge-----------------------qyqvs
s-------vvstlvqlelg---d----------tqsllt-----------
-------wgqrhtl--------------------iwt-----------rs
gklre----yk-tlltnan--cartidslihkamysncfslknnah-lvk
c-elkg-dsaaicekyvtemkfirce-tae---------iftpsgeskkg
------q-pgtkpa-qqpfatdrvqhp--tggkdela-----qqaqyna-
-ldaslnc--------ccflvmktvsggtmadrt--fsws--hclpkdtm
rv--a-n--gpaaaprelsd-f--qepssleegfpgaa------ek-lgg
esmpmacvhtn------cvdsiipiqcrvtlaagprpsrwikcgvamp--
-kgrkkea-------py-----------nkimrp---------esgmdal
qtr--ppwgapvhptlk-----vlsfrsvlklrlappvatwwyfitsgna
rk---a--dlqk-------htafr------yleygr--------ppcn--
-----sygpfaaalsfgpel-----ktkt----ktgfc--pafiqrqlkl
dnpkgl
>node11
vyvtegrhlg---ydq--mrvl-------sg--pscderrsll----gkr
vlqgl---lgpfkgprstetgdpgaiqkc-v-----------klpe----
-lfkacs-fvtgvk---ahcagsnkpkm----teeklvkekgcgvmh---
--v-aslthddpia-------------lls-vsllrgshwqdlpvywske
pvvflek--dvtslvlgaglipgtgpgqfypaa-------srns-s-tdq
glaaphrelslneytc-------artktyn---------cyqdrnlsphg
tsk-sdghkkktns-kraydalktpnrcegkqehlvg-----f--pgpvd
h---evni--------sayfflpksf-----rwg--krwivnhckskssl
ttvprln--cghc-saah-kglaa-----ggdqlkdrp------sr-mct
al---pfngyv------hr-alieakcp---e-----------a----vg
pggveqdr-------nlsvtaylgfcfnrpllkillasylndiqqggvks
rvaigiswgrgt----k-----avalrchpilrlcgstaghlrfvkaqlg
rn-sgt--nleds-----ykqqsv------fkeig-agaarl-gaahpln
tmkskdiv-aaar-lfvpel-----ks-lmserttsfsdalp-d--lfkk
tm----
>ENV_HV2G1/23-502
vyvtegrqlg---ydq--mrvf-------vg--ps-derrsll----gkr
vlqgl---lgpfkgprstetrapgafqkc-v-----------klfe----
-lfkaca-fatgvk---ahcagsnkpkm----teqklvkedacgvmh---
--v-aslthddpia-------------lls-vsllrgshwedvpvywtke
pvvflqk--dvtglvlggdlipatvpgqfapas-------srns-s-tdq
glaaphrelslneysc-------artktyp---------cyqnrnlgphg
tsk-sdghkkktks-krayatmkapercegkqehlvg-----f--pipvn
h---dvns--------sayfflpkaf-----rwg--krwivnhckskssl
ttvprlw--cghc-saah-kglad-----sgdqlknrp------sq-mca
al---pfngyv------hr-akidysca---e-----------a----vg
pggleqdr-------nlsvtkylgfcfsrpllkilfasylndiqlggvts
rvavgiswgrgt----k-----avalrchpilklcgstaghlrfvkaqlg
rn-sgs--hledr-----ykhqav------fkeig-asasrl-gaan-ln
tmrtkdva-saar-lfipel-----ks-lmsertssftdalp-d--lfkk
sl----
>ENV_HV2D2/24-513
iyitdgrhfgvgpfdqkslrvlcenynpkng--pscgerrnll----vkr
vlggl---lgqfk---gketgdpdavqkc-v-----------nlpe----
-yfgacs-fvtaik---ghcgasnkgsm----dkaklvkqkgcgvma---
--v-gslarnd-----------------ls-vsllrgshwen----wsk-
pvaflpk--dvtslvlgagllsctgpgqfiiaa-------srnt-s-ikr
gl----rslelnnatcf------artktyn---------cyhdrnlsang
aak-tdgrkrkaks-kraydalkvpkpcdgkk-hmvg-----f--pspvg
h---yvncqaniyagd----ylskti-----pwgklkrwllpvckskpdl
hteprde--cedc-saav-ksfkg-----ggdelk------------kct
gl---plngyvysccgrht-allqakca---d-----------a----vg
gagvesdr-------tlqveaylgyctdt--lktllanflnevqqdvvkl
rla--vawgrgs----n-----avalrchpilkl---paghlklvktalg
rsgtgt--nlddk-----tkdhsv------fkenn-vgivrl-gdactln
pmkskdiv-aaakglfvpel-----kh-llkaqtysfsdalp-g--flkd
ta----
>node10
vyitegrhlg---ydq--mrvl-------sg--pscderrsll----gkr
vlqgl---lgqfk---stetgdpgaiqkc-v-----------klpe----
-lfkacs-fvtgvk---ahcagsnkgkm----neeklvkqkgcgvmq---
--v-gslthddpia-------------lls-vsllrgshwqdlplhwske
pvvflek--dvtslvlgaglipgtgpgqfipaa-------srns-s-tdq
glaaphrdlelnestcf------artktyn---------cyhdrnlsphg
tsk-sdgrkkktks-kraydalktpnpcegkqghlvg-----f--pgpvg
h---dvnc--------sayfflpksi-----pwg--krwivhhcksksdl
ttvprln--cghc-saah-kslka-----ggdelkgrp------sr-mct
al---pfngyv------hs-alieakcp---e-----------a----vg
gggveqdr-------klsvqaylgfcfdrvlmkillasylneiqqggvkd
rva--ipwgrgt----k-----avalrchpilrlcgttaghlrfvkaqlg
ra-sgt--nleds-----ykqqsv------fkeig-agaarl-gaacpln
smkskdiv-aaarglfvpel-----ks-lmserttsfsdalp-d--lfkk
tm----
>node18
vyvtegrhlg---ydq--mrvl-------sg--pscderrsll----gkr
vlqgl---lgpfkgprstetgdpgaiqkc-v-----------klpe----
-lfkacs-fvtgvk---ahcagsnkpkm----teeklvkekgcgvmh---
--v-aslthddpiakee------sg--lls-vsllrgshwqdlpvywske
pvvflek--dvtslvlgaglipgygpgqfypaa-------srns-s-tdq
glaaphrelslneytc-------artktyn---------cyqdrnlsphg
tsk-sdghkkktss-kraydalktpnrcegkqehlvg-----f--pgpvd
h---evna--------sayfflpksf-----rwg--krwivnhckskssl
ttvprln--cghc-saah-kglaa-----ggdqlkdrp------sr-mct
al---pfngyv------hr-alieakcp---e-----------a----vg
pggveqdr-------nlsvtaylgfcfnrpllkillasylndiqpggvks
rvaigiswgrgt----k-----avalrchpilrlcgstaghlrfskaqlg
rn-sgt--nleds-----ykqqsv------fkein-agsarl-gaahpln
imkskdiv-aaar-lfvpel-----ks-lmcerttsfsdalt-d--lfrk
tm----
>node17
vyvtegrhlg---ydq--irvl-------sg--pscdkrrsll----gkr
vldgl---lgpfkgprstetgdpgaiskc-v-----------klpe----
-lfkacs-fvtgvk---ahcagsnkpkm----teeklvkekgcgvmh---
--v-aslthddpiakee------sg--lls-vsllrgshwqdlpvywske
pvvflek--dvtslvlgaglisgygpgqfypaa-------srns-a-tdq
glaaphrelslneytc-------artktfn---------cyqdrnlsphp
tsk-sdghkkttss-kraydgl--pnrcegkqehlvg-----f--pgpvd
h---aina--------sayfflpksf-----rwg--krwivnhckskskl
tsvnrln--cghc-saah-kg--a-----ggdqlk-------------ct
al---pfngyc------hr-alieakcp---e-----------a----vg
pggveqdr-------nssvtaylgfcfsrpllkillasylndvqpggvks
rvaigiswgvgt----n-----svalrchpilrlcgstaghlrfskaqlg
fn-gpt--nleds-----ykqqsv------fkein-agstrl-naadpln
imkskdiv-aaar-lfvpel-----ks-lmcerttdfsdalt-g--lfrk
tm----
>ENV_SIVV1/24-538
ayvcatphld---hag--sppa-------vs--ptrhkfkgfi----afk
vlnqiprkfgsfk---vtggaq-----------------------esdas
klfrtcvlvvdstt---vac-snvqecvtlgpledikvh-----------
-------wendveg--------------------lwa-----------kq
aeltleklgdnksvvl-at--cplgigpslgal-------vrht-r-laq
gedsphaelqspss--l------sqmktys---------aysgkvkaera
------lttgasdl-khsfevvrvrlpplaeecdrvg----ty--kapvg
hlsadant--------cvyyllknavvkiapnwt--sswe--ectekekq
vv--sntsgiats-eevr-k-h-------gg-gstgrperkdalgrslcd
-l---ptqpfp------yd-----ypce---g-----------n----ap
anavqagkqldelvinfntnr--gicvaralmqi---------rtnksts
ila--vpyiqda----n-----disfrnhciisl-gasagtdnfiknnkg
rp---h------l---rsygvkfigtthsssyiygkcgavkfgapt---p
gqkdkd---------------------------tnmycadlpyt--twke
si----
>node19
vyvtegrhlg---ydq--mrvl-------sg--pscderrsll----gkr
vlqgl---lgpfkgprstetgdpgaiqkc-v-----------klpe----
-lfkacs-fvtgvk---ahcagsnkpkm----teeklvkekgcgvmh---
--v-aslthddpiakee------sg--lls-vsllrgshwqdlpvywske
pvvflek--dvtslvlgaglipgtgpgqfypaa-------srns-s-tdq
glaaphrelslneytc-------artktyn---------cyqdrnlsphg
tsk-sdghkkktss-kraydalktpnrcegkqehlvg-----f--pgpvd
h---evna--------sayfflpksf-----rwg--krwivnhckskssl
ttvprln--cghc-saah-kglaa-----ggdqlkdrp------sr-mct
al---pfngyv------hr-alieakcp---e-----------a----vg
pggveqdr-------nlsvtaylgfcfnrpllkillasylndiqpggvks
rvaigiswgrgt----k-----avalrchpilrlcgstaghlrfvkaqlg
rn-sgt--nleds-----ykqqsv------fkein-agsarl-gaahpln
tmkskdiv-aaar-lfvpel-----ks-lmcerttsfsdalt-d--lfrk
tm----
