>node18
erl-------ekmvlr-irkcfmfkesavkthylnnttvvychknqsfsg
nekl---sggslt-fplven-e---pikkm-------------ptewhlp
narnddsvnri-gg---tgklqinvfiv-yql-rnhlttlitvtkgd---
--mavlksdnlsisc-klagegqdmvgeaq-pt--htskdp----gskpy
knslsvtasfaraprvgyrksymg-gvle-----------ifedkcglgl
dygq---v-evkak--qshqtlkfradrpsstn---------ysplipmi
geigd----tp--dettf----------hllfseyvgkfme--sh-dleq
lvt--p---------t--sggsigcaidktvlregvnsqye---------
-vnskgfaagqfnat-----nthyplyskgs----yaattsp----gc-i
mdqkkdlqaladlpsv---lrtilvdsvfha-yvkcpnkaqlgdtsae--
kppgmtysfcgkatkqtk-all--khi-flesqnrts-----gyehnced
dsqkpgad-f-----avpigvlrn----ackhkfavep--------lpst
ts--pvksdkng----yn----ipccrn----glrfqgqatnkltt----
------------d--takknppllqegfvviddwvtgdalkk--------
---p-igt
>node8
ecl-------aklllk-walsfafgdsalksdfnadtpvvychnsnwfkg
radl---vatilm-fslgsaqd-----ktm--------ydpesppevaai
gvrnd----rf-qg---stapqthvfiv-yeh-kdhltttvpvhkgg---
--ma------lnisc-kilsnvrqgigsaq-qv--tcpkta----ggk--
dd-------sakgprvktsksntn-gklk-----------g---kcgasf
eygq---v-dirsk--afhd------dqpstnh---------ydsmiavv
ceigdqdgfdq--dqetys--------atvifplfat-fvk--tn----d
vii--p---------k--gas--------------fhgqys---------
-vstdgyaaknmelh-----hghyclyt--------dyasrp----dd-i
iepknglvaeaelpfm---lrailhdtvflt-yp------------vp--
sstgstygycgkddd----kwl--kqk-flkpgnrhs-----gyvdhc--
dskkpgld-f-----n-pasdlpa----aykspfsgda------pklpgt
ai--n------g----fm----yptchsvsltgvrld-----hlaglad-
--------yekgd--rarknealligkfgvitdwittqdlra--------
---n-gsk
>node14
erl-------ekmvlr-irkcfmlkesavkthylsnttlvychktqsfsg
nekl---sggslt-fplven-e---pilkm-------------ptewhlp
narnddsvnri-gg---tgklqinvfiv-yql-knhlttlitvtkgd---
--mavlksdnlsisc-klagegqdmvgiaq-pt--hvskdp----gskpy
tnslsvtarfaraprvvyrksyrg-gvle-----------rfeikcglgl
dyge---v-evkvk--qshqtlkfradrpsstn---------yspliami
geigd----tp--dettf----------hllfseyvgkfme--sh-dleq
lvs--p---------tv-sggsigcaidktvlregdnsqye---------
-vnskgfaagqfnat-----nthyplyskgs----yavvttpyaamgc-i
mdqkkdlqalaelpsv---lrtilvdsvfha-yvkcpnkaqlgdssae--
kppgmtfsfcgkatkqtk-all--khi-flesqsrts-----gcehnced
esqkpgad-f-----avpigvlrn----ackhkfavep--------lpst
ts--pvksdkng----yn----ipccrn----glrhqgqatnklta----
------------d--takknppllqegfvviddwvtgdalkk--------
---p-mgs
>ENV_HV2D2/24-513
skl-------ekvvlr-talcysnkqstvkthyisgtsvvcc---esfps
nekl---sgdsli-yplvdn-e---pikkm-------------ppewhld
ssrnddsanvi-gg---taklqanvkii-ykl-rehvtsl---mdgv---
--kavlkrdnlsysc-lnagdghemvgdgk-pt--harkda----gaqpy
knnlghksafakapqvgerknymg-gvle-----------vfedktgqgl
qygq---v-enkskstqaqqplkfrpgd---------------spltplv
gnine----tp--dettf----------rflfnhyvse-le--rh-dlnq
lvt--p---------t--aagstvcaisktilregidsrne---------
-sttkalaggaykvt-----dthy--yakgd----yaatkap----es-i
mdqknemlafadlpsvpsslit-lveavyds-yvkcpdraqlgatsae--
kppgmtyglcgnatkqtk-alv--rhi-flqaqqrqs-----gyehqcee
dnqepeae-f-----a-pqgdtrn----ackhkfavep--------lpst
tt--pikaqkag----yhaefgkpccrnaslkgfrfqghagnklkt----
------------t--kakkdqpllhdgyvvisewatgqaaiq--------
---p-isa
>ENV_SIVG1/22-522
qclpg-----aklllk-wavsfssnd--lkanfgpdtpevychdsqwfkg
rsdg---ladilm-fdlgsaqd-----ktm--------yqpeappelaat
gihad----rfgqg---ntaanahvylp-yqh-kghltptvpahsgg---
--ma------lnisc-tiligvrhgqgtae-lv--tcpkaa----ggk--
ad-------saqgprletdknnsn-aktk-----------s---kcgtfl
efgq---vgnikak--afhe------spps-da---------ydtkigvp
ceighqkgfdahcpqetys--------stvifplfat-fvk--tn----a
aih--p---------k--ggn--------------fegeys---------
-vpttkfarkdmilhlqt--hghyclhn--------dytsrp----id-a
vepksglpgeaenafq---irpilqeavfls-yp------------vp--
sstsssygfcgkdee---ktwltskns-llkptnrhs-----gvgdhc--
dssspgld-f-----n-tasdlps----aykrpfsgdg------pklpaa
al--n------g----fk----nptcssvgltgvklq-----hlvgpsdk
l-------fdve---------glllaifgvitd------lrp--------
---n-dsr
>node11
erl-------ekmvlr-irkcfmfkqsavkthylnntsvvychknqsfsg
nekl---sggslt-fplven-e---pikkm-------------ptewhlp
narnddsvnri-gg---tgklqinvfiv-yql-rnhlttlitvtkgd---
--mavlksdnlsisc-klagegqdmvgeaq-pt--htskdp----gskpy
knslsvkasfaraprvgyrksymg-gvle-----------ifedkcglgl
dygq---v-eikak--qshqtlkfrsdrpsstn---------ysplipmi
geigd----tp--dettf----------hllfseyvgkfme--sh-dleq
lvt--p---------t--sggsigcaidktvlreginsqye---------
-vnskgfaggqfnat-----nthyplyskgs----yaattsp----gc-i
mdqkkdlqaladlpsv---lrtilvdsvfhs-yvkcpnkaqlgdtsae--
kppgmtysfcgkatkqtk-all--khi-flesqnrts-----gyehnced
dsqkpgad-f-----avpegdlrn----ackhkfavep--------lpst
ts--pvksdkng----yn----ipccrn----glrfqgqatnkltt----
------------d--takknqpllqegfvvindwvtgdalkk--------
---p-igt
>node7
qcl-------aklllk-wavsfaand--lkanfgadtpvvychnsdwfkg
radg---vadilm-fdlgsaqd-----ktm--------ydpenppelaav
gihsd----rfgqg---stasnahvyip-yqh-kghltatvpvhggg---
--ma------lnipc-kilsnvrhgsgsae-qv--tcpkaa----ggk--
ad-------sakgprvetdksntn-gklk-----------a---kcgtfl
efgq---vanikak--afhd------npps-na---------ydskiavv
ceighqdgfdphyeqetys--------aavifplfat-fvk--tn----a
aii--p---------k--ggs--------------fegkys---------
-vgttnfarkdmilhlqt--hghyclhn--------dyasrp----dd-i
vepknglaaeaenafm---lrpilhesvfls-yp------------vp--
sstgstygfcgkdee----twltskqs-flkpsnrhs-----gvvdhc--
dsrkpgld-f-----n-pasdlpa----aykrpfsgdg------pklpaa
al--n------g----fk----yptchsvgltgvrle-----hlvglsdk
h-------fevge--rarknealllgifgvitdwiitrdlrp--------
---n-dsr
>ENV_HV2BE/24-510
erm-------ermvlr-arksfmlkesavmtqylsntslvychktqslsg
ketl---sggrlt-yplvet-e---pilkm-------------stewhlr
narnddsinri-gg---tgkleisvvvv-yql-knhltpli-----d---
--msvlksghipikc-klagegqdmvgsen-pt--hvskdp----gskpf
lsslsvtaqfaraprvvyrksyrg-ttld-----------ryeircgigi
dygg---v-evkvg--kghqtlkfrgqsasstn---------yspliama
teigd----tp--dettf----------illfsayvgkfme--rr-dleq
ins--p---------tl-sggsigcaitktvlrdgdnsqye---------
-vnskgfaagqfnaa-----nthfplyskgs--alyalvtspygtlgc-i
mdkkkdlqalaelssv---lrtilldsvlha-yvkcpnkaqlgdtsge--
kppgmtfafcgkatkttk-all--khv-flesa--ts-----gcehncad
esqkpgpd-f-----avpigvfrn----ackqkfavep--------lpst
ts--tiksdkng----yn-----p--rn----alrhqghatnkmaa----
------------e--iakkdpsvlqegyvsidewvtgdafkk--------
---p-ags
>node9
ekl-------erlvlr-falafmfkqsavkthylsnasvvychktqsfsg
kekl---sgsslv-fplven-e---aikkm--------yntdkppeshmp
sarnddsvnrf-sg---ttklqanvyvi-yql-rdhlttliavtkgd---
--mavpegsnlnisc-nlagegqdvvgdaq-pt--qtpkdp----gskpy
knsvtvksgfaraprvearksylg-gvle-----------ifedkcglel
eygq---v-qihak--qthdtlkfrssrpsptn---------ysplipmi
geigd----tp--dettf----------hllfshyvgeflq--sh-dlen
lit--p---------t--aggstacaiektvlregingqye---------
-vnpkafaggnlkvh-----nshyplyskgs----yaaatsp----gs-i
mdqkngllpesdlpsv---lrtilhdsvfht-yvmcpekselgdtsae--
kpsgmtysfcgkaek----all--khi-fleshnrts-----gyehnced
dsqkpgld-f-----a-pagdlrt----ackhkfrvep--------lpgt
ta--pgksdkgg----yn----ipscrnaslkglrfagqatdkltg----
------------d--takkdqpllptgfvvitdwvtaqalrk--------
---p-iss
>ENV_HV2NZ/24-502
srl-------ekmvlr-irkcfmfdqssvqshylintcvvycsknqsfkg
kekle--sgeslt-fplven-elcmpikkm-------------pnewklp
hakndgstdni-gg---tgklqihvfiv-yql-vshltllitvtkgd---
--mavlkadslsvtc-klagpgqdmsgtaq-pa--qtskqp----gsmpy
ktkltltasfnkaprvgyrhtymg-gvld-----------ehedkcglgl
dygq---i-evkak--asnhtrkfradkqssta---------ysslidmv
gevgd----tp--demtf----------hnffsdyvgkfme--sh-qleq
lvt--p---------t--sggcigc-itqtvlreavggqye---------
-vnskgfesgefdat-----sthyplyckgspl--ygatapp----gc-v
kdqkkdlqaledlpsv---lrtdlvssvfhalyakcpskanlgdsage--
epqgatysfrgkatkqtk-tll--khi-fveghnrmskyialdyqhnced
adqlpgad-f-----tvpigvlrn----sckhkfaves--------sast
tn--pvkgd-ng----yn----ipvcrt----glrfqgdsagkltt----
------------dffsakknpgllqegfvvle---tgdvlkk--------
---pviat
>node10
ekl-------eklvlr-ialcfmfkqsavkthylsntsvvychknqsfsg
nekl---sggsli-fplven-e---pikkm-------------ppewhlp
sarnddsvnri-gg---ttklqanvyii-yql-rdhlttliavtkgd---
--mavlksdnlsisc-nlagegqdmvgeaq-pt--htpkdp----gskpy
knslsvkssfaraprvgarksymg-gvle-----------ifedkcglgl
eygq---v-eikak--qshqtlkfrsdrpsstn---------ysplipmi
geigd----tp--dettf----------hllfshyvgefme--sh-dleq
lvt--p---------t--aggstacaidktvlregidsqye---------
-vnpkgfaggqfkvt-----nthyplyskgs----yaattsp----gs-i
mdqkndllalsdlpsv---lrtilvdsvfhs-yvkcpnkaqlgdtsae--
kppgmtysfcgkatkqtk-all--khi-flesqnrts-----gyehnced
dsqkpgad-f-----a-pegdlrn----ackhkfavep--------lpst
tt--pvksdkgg----yn----ipccrnaslkglrfqgqatdkltt----
------------d--takknqpllqdgfvvitdwvtgqalkk--------
---p-ist
>ENV_SIVV1/24-538
dcl-------akinlk-wgvsfpadn--lkasfgadtpevicqtedwf-g
radg-knvgeilm-fdlgsaqd-----rsm--------y---------av
gahkd----rftpg---sqadd---yip-yqh-mehldagvavhegg---
--ma------fnypcvrvltnvrhgtsree-qvmascpkaq----gsk--
gg-------sgesprvetdksntk-gklq-----------s---vcglfk
dfgq---vapirak--afnn------npps-ntkplgpnaysydpkvpvv
ceigqqdgfdghyegetya--------savifplfgt-ftk--tg----a
ple--p---------k--ggs--------------fegkyn---------
-vgitlfarkdlianlrt--hahaclhp--------dyashr----ed-i
hegktelageaehafm---gr-ilheavila-dq------------vpr-
sttgstygfcgknee----awlsakqs-fvkpsgmhs-----givdpc--
phr---------------asdgpd----sckqpfsgda------plisaa
al--s------glarafk----ypachwaglgparlq-----hlvgmtdk
h-------hevke--rarmnkklllaifgyildwlitrdlrpypnlyeta
qvtd-gst
>node19
erl-------ekmvlr-irkcfmfkqsavkthylnntsvvychknqsfsg
nekl---sggslt-fplven-e---pikkm-------------ptewhlp
narnddsvnri-gg---tgklqinvfiv-yql-rnhlttlitvtkgd---
--mavlksdnlsisc-klagegqdmvgeaq-pt--htskdp----gskpy
knslsvtasfaraprvgyrksymg-gvle-----------ifedkcglgl
dygq---v-evkak--qshqtlkfrsdrpsstn---------ysplipmi
geigd----tp--dettf----------hllfseyvgkfme--sh-dleq
lvt--p---------t--sggsigcaidktvlregvnsqye---------
-vnskgfaggqfnat-----nthyplyskgs----yaattsp----gc-i
mdqkkdlqaladlpsv---lrtilvdsvfha-yvkcpnkaqlgdtsae--
kppgmtysfcgkatkqtk-all--khi-flesqnrts-----gyehnced
dsqkpgad-f-----avpegdlrn----ackhkfavep--------lpst
ts--pvksdkng----yn----ipccrn----glrfqgqatnkltt----
------------d--takknqpllqegfvvindwvtgdalkk--------
---p-igt
>ENV_HV2G1/23-502
erl-------akmvls-irkcfmfkqsalkthylnnapvvychkpssfsg
nekl---sggslt-fplvek-e---pirkm-------------ptewhmv
narnadrvnhi-gg---tgktlinvfiv-fqlernhlttletvtkgs---
--lailksdnlsisc-klagkaqqgvgerq-pt--htskdpetgkkgmpy
knslsvkaafaraprvgyrngymg-gvle-----------vfddkcglgl
dyaq---v-emkak--tshqtlkfrtdrpssts---------ynpliemi
gnigt----ip--det-f----------hllfseyvkkfmdeeshkdlen
lgt--p---------a--sggplgcaidktvlregidsqye---------
-vngkgfeggqhnat-----ntnyplyskgs----ygatvsp----gcem
mdqvkdleplddqpsv---lrtilgdsafha-ftdckhkaqlgstsae--
kppgmtysfcgkstkqtk-all--khi-fldsqnrdg-----gyeha---
-sqkpgad-f-----avpegplrn----dckhkfavep--------lpkq
ts--pvksdkng----yn----ipccrn----glrfkgqatnkltt----
------------d--tgkknnsllqegfvvindwctgdamkk--------
---p-iaa
>ENV_HV2CA/25-512
erl-------erivlr-irtcfmfkvsavkthnynntivvyctknqslpg
nekle--hgsslq-fplven-q---pikklaaggtvat-----ptewhlp
narnddsvnri-gg---sgklqinvfii-ykl-warfttlitvtkgd---
--mevlkseglsvkc-rlagpsedmvkdae-pa--htskqp----gskpy
mdsitvtapfarsprvgyrnstqg-gagg-----------fledkcglal
dygq---i-eikak--eshqtkkfrvdrpantn---------nsplisai
geird----tp--devtf----------hnlfsdyvgkfme--sh-elde
lvt--p---------g--sggsagcaidktvlrdavts-ye---------
-ihsadfesgqfdat-----syhyplyakgs----yaaatsp----ac-i
mdqkmdlleledipsv---lrtdpvgsiyqg-fvkcpn---lgdttee--
eppgmtysfsgktteetk-ayl--nhi---esqyrmsvyveldyehnceh
qsqepgae-f-----vvplgllrn----scahmfaves--------smst
sy--ptkdn-ng----yn----ipccrs----glrfqgpatemltt----
------------d--sskknpgllqeafvatd---rgdalrk--------
---p-igt
>ENV_SIVGB/47-569
ncl--iscskpkvtlkt-pscfi---rdimtnfnnag-------ekrvng
gc-l---m--filgffld--ns-----ldg--------enpdaenrics-
------------ssitiaesggkdlfknk------tl----p---gaflt
mqas------lsltc-ntksknphnvptskigv--dvkakh----ags--
ln-------cmkgqeddsnrqgdadvsydnkilaskctags---rcdigp
esakknq---e-qk--------------emmdn---------ytakgmc-
clvdgedafsr--shv--snggwplsshsnmvpnstl--kq--ra----g
lyysgtkvhvgptgpr--gdt--------------fagqynsseltkwke
vtstn--ggkkmefe---atlrrfspyt--------yylgrt----dd-m
iallgalvign----t---artwf----fls-tt------------gk--
hargesrdfaeknee----awy--lesa--------l-----savdg---
kvsgkgfsvpalgrqt-kyrilpekhvksfgndyqakpkiitayprleg-
ihyq------------hm----edtctai---gvsga-----tik---p-
-iealhggyt-gs--rvkekpeiqvgkiyild------------------
-------h
>ENV_HV2D1/24-501
drl-------enmvlr-irkcfmlkekavkthylsnttlaychktqsysg
ndkl---aggslt-fpfves-e---pilkm-------------ptawhls
narnedsvnri-gg---tgkmqinvfiv-yqi-knhlstlisvskad---
--mavlksdklsisc-klagegqdmvgiaq-at--hvakdp----askpy
tnslsvtarfarapkvvyrksyrg-gvre-----------pfeikcglgl
dyae---v-evtvk--htnqtlkfradrpestn---------yspllaki
gevgd----tp--eettf----------hllfseyigkfme--sh-dleq
lvs--p---------kv-ssgeigcaiektvlregdnsqyt---------
-vnskgfaaaefnst-------hsplysegs----yavvttpyaamgp-i
mdqkkdlqalaelpav---lrtilvnsvfha-yvkcpntaqlgaksaq--
kppgmsfelcgkatkqtt-all--khi-flenqsrts-----gcehdced
esqkpgad-i-----avpigvlrn----ackytfavep--------lpst
tk--pvksdkng----yn----ipccrn----glkhqgqatnklts----
------------d--takknppllhegfvviddwvtgdalkk--------
---p-mgs
>node17
erl-------ekmvlr-irkcfmfkesavkthylnnttvvyctknqsfsg
nekle--sggslt-fplven-e---pikkm-------------ptewhlp
narnddsvnri-gg---tgklqinvfiv-yql-rahlttlitvtkgd---
--mavlksdnlsinc-klagpgqdmvgdaq-pa--htskqp----gskpy
knsltvtasfaraprvgyrnsymg-gvle-----------ifedkcglgl
dygq---i-evkak--qshqtkkfradrpsstn---------ysplipmi
geigd----tp--devtf----------hnlfseyvgkfme--sh-dleq
lvt--p---------t--sggsigcaidktvlreavnsqye---------
-vnskgfesgqfdat-----nthyplyskgs----yaattsp----gc-i
mdqkkdlqaledlpsv---lrtdlvdsvfha-yvkcpnkaqlgdtsae--
eppgmtysfcgkatkqtk-all--khi-flesqnrmskyieldyehnced
esqkpgad-f-----avpigvlrn----sckhkfaves--------sast
ts--pvksd-ng----yn----ipccrn----glrfqgqatdkltt----
------------d--sakknpgllqegfvvid---tgdalkk--------
---p-igt
>ENV_SIVM1/24-528
ekl-------eilvlr-falafffkqsavkthyltnaavvychktqrfsg
kdkl---sgsslv-fplved-e---airkm--------yntdkppessmp
sgrnddsvnrf-ss---ttklqanvfvi--ql-rdhlttliavskgd---
--maypegshvsisc-nlagegeyvvndaq-ps--qspkdp----ndepy
nnsvtvmagfarapkcearksylg-gvle-----------ifedkcglel
eydq---v-rihak--qtsetlkfqssrpnath---------ytpllpmi
geagd----tp--detaf----------hllfshyvdeflk--ah-dlen
lft--t---------n-kaggstviaiekavhregiggnhe---------
-iqpkafag--lkvh-----nshyplyskgs----yaaatsp----gs-i
meqkngllpsadlpsv---msailhdsvfht-yvmcpetgdlgdtnde-k
kpkgmtysfcgraek----all--khi-flethnrks-----syaqncee
dsqksglt-f-----a-sgadlws----ackhkfrvep----------at
ta--pgksdngs----yn----ipscrnaslkgqrfagqatdkttg----
------------d--takkdqsllqtgfvvitdwvtaqtlre--------
---p-vss
