>node17
wdlyqgtdrcgvcfvkl--dqqvlsgh--fsiyqlslfikskas------
akk-----c-cehp------e-er-sqsvp---lsnwgs-ltkltmpeek
----gqiptlpkggfskptgh-aatleifhcsn---g--taah---ila-
---vqtdak--dk-------ttmdelvlkegnpti-d---kkdwsgykvl
vasilnlq-lkkhscglk--fg--evinccgptvgs-eni----h-ec-y
t-lp------k-a----lg------ynnkevlk--hk-------qlgilq
l-ksqdvckvvvcarry-lacagnvdlfteipvvpkd-------------
-hlthfsvvpsenpatkdpl-----qh--lli--tlva----isaiegka
gatht-hi------m-------wk---waftaae----------------
----tl---vawassk-ky------v---rl----------pe----fss
drh-k--ke--gsdn--rqsitvqias--ta-fck----r-etgvsk-f-
---------kahntaepll--vdgackks-llac-isg-----kldlpvd
-rskqypraphcisa--kygdlryelyafefr---laynlgafet-----
rddqpva-yrkflnr-agskyvpstreatteqdrfreepgfifaasfarr
laklgakdasepvl-feilkl---apgcplsg--deghihkkna
>ENV_SIVV1/24-538
raeyahgsk----aakhlfatvfikf-------hihl----gar------
ydk-----c-ldhr------a-qa-pvcir---lqgwselplkgalckek
dsligkvp--------s-----fggwavlscas---g--tlgq---lll-
---veskve--gs-------vnlegegyrnkadr------ssgwdgaah-
-ravlelp-lkrekcglksefg--splkscsvqgge-khv----dvrc-h
k-kvpsglgvktgsvefls------fnvqgslkanhp-------tl--vk
lgkhfnackvfvcqidc-lkcea---lygdlf----gyrg-----lfitp
lhlgrwplgpcvp--------sa-dpr--vfm--hlls----cggppakg
gtthv-ld------d-------wv---wsfhafg------fldviegr--
-agg-------wgtkkpkv------s---ni----------tl----rrk
kqd-kkaknlggcnlpdk-sigtgdta--vg-ycr----t-qggs-kgf-
---------ikkgqgvaflytirdlshkrdrsic-iaa-----pkplsms
-rt-------vcgfa--snaqiifsfygyiip---anvrlngylatatgt
---wdta-dqapiar-mggkyvplds-----vpr---e--fgfaatiirr
nkakaaktkrahvllfkpekl---tkgcglga--ggsnmdp---
>node7
rdkyehsar----agkhvfqqvfinf-------hihl----msr------
ydk-----c-ldhr------d-da-pvcvs---lqgwsp-alkgalaqek
d-figkvp--------gakgk-fggrdvmscas---g--glgq---lla-
---idskvk--gs-------vtlegegfrektpk------stgwdgyaa-
-raildmp-lkrekcglksefg--qplkccgvqagq-khv----dgkc-y
a-mvasgilvkta----lg------fnnqgslkathk-------tl--vk
lgkghnickvqvceinc-lkcea---lfself----gykg-----lfttg
lqlgrwcvgpcvq--------ga-dph--lli--hlln----cgkpngke
gtthv-ni------d-------wv---wsfqafg------fldviegr--
-ggg-------watnk-kf------v---kl----------td----frk
nrh-kkgknlggsnlpnkqsiatgeta--vg-fcr----s-qggkdksf-
---------lkkghgapfl--isnlsqkkdrfic-ftg-----pkplsid
-rs-------acgva--snaqikfslygfifp---anvrlgaylttakgv
---satt-yqnpiar-lgskyvsads-----vqr---e--fvfnaalkrr
nttkpakessadvlifkiqkl---trgcglaa--sgahlnn---
>ENV_SIVM1/24-528
wdkyegter----rvkq--dqdisngp--fqiyqvtlflkakaa------
ykk-----c-cehq------e-vr-aqstp-alldhwgp-ltglaepegk
----grvpslpk---gkqtgr-n--------ak---g--tasp---lla-
---lvtdak--dk-------asmkalvlkeknphi-n---kkdwtgfki-
-ytflkie-fkrnkcglk--fn--eaikccgveaga-thv----h-rc-f
t-iv------r-g----lg------ynnkevlk--hk-------elgivk
l-ksqevckvhvcarrc-ltcag---lfteidvvpsdftg-----llahg
vhlnhfsvrpsdlraakdppfgg-dqh--lli--clvt----cakvegqg
gathv-hi------a-------wk---wvftlag----------------
----vlvgklawaask-ky------v---rl----------pd----ftn
nqe-k--pg--gsnf--rqstttrvas--ta-fck----r-kggvs----
------------shaahli--lkgkcqka-llac-iag-----klnlpvn
-rskefsrapgciga-ckygqlryelyafefr---vayhlgayet-----
sddgqif-yrkalgk-dgskytyktheattneer---dlgfvfaasfkrr
lakegardtfeivflfsvlkl---asgcslag--edghvakkts
>ENV_SIVGB/47-569
ktvknkaek----vend--mkvpygy-------raqt----tnltrrrqt
vdp-----c-aa-r------g-at-fvcipd--lpe-tc-vgraalsgnp
h-tdv--p--------rpklk-pgglk--lcsevdn----gnkhldfiv-
---ihpsrqleqf-------vtvgslafwvqaq------------gkpt-
-sgtlklp-qfkarcgkrms-----hlkccikyghsp--------gegdy
kivlpwgvtvrnp----lk------ymtses----ytlsvwpar-l--pk
haqerhkcpvplcpmgc-i---t---vfaewfvcgk---plafla-----
-----------ve--------sskfahqi-------ad----ctsfgslq
eeesg-dilnneeqh-------wa-nl----kvg------gntplgsdwv
agga-------wgtta-ky-----------lpsaptcypacnn----yph
iqead--ef--iarl--kkarvqdegg--vpgfaqaaqek-rtsfnkal-
---------iakkaapafk--kdhpsekgtdlad-llg-----rlarain
-kk-------h-g---------pkp----slgswttpmr--kihk-----
rsslpp--kssplplgggkrfdvlva-----ipn---p--yvqdcpltes
dyrsffnqnnrikvefnahkailg---------------gleiq
>ENV_HV2NZ/24-502
wdlyqgtdkcavcfvkf--kqqmlqgh--fsvyqlnlfikskts------
akr-----cpcqhp------d-er-aqsvp---lsnwgs-lt------qn
----ghiptlpkggfskptgh-aasleifhcsn---g--psah---ilar
lfatqtdad--dk-------tskdeiilkdgnvti-d---kmdwegckvl
vasilnlq-lkksscgva--fg--evinscgptvts-env----k-kc-y
t-lp------r-a----lg------khhksvlk--hk-------qlgilq
l-ksqdvckvvtcaery-lacavnvdiiteipvvpkk-------------
-hlthfsvyscentatkgpl-----qy--llv--slva----isaldska
gasht-vi------v-------wkd--waftaae----------------
----tl---vawsskk-ry------i---kl----------pqilegfas
drh-k--ke--gndn--rqsvtvqias--ta-fck----r-elgvsk-l-
---------mahetsepll--vdgackks-llac-isgqlaggklglpvd
-rskqypkakhcisa--kygdlry-lyaiqfr---laynlgaymt-----
rdenpva-trkfinr-agskyvpssramateqdkfreepgfifaasfarr
--klgakdadepal-feilkl---apgcplsg--pdghihkkna
>node19
wdkyqgtdrcgvcivkl--dqqilngh--fsiyqlslfikskas------
akk-----c-cehp------e-er-sqsvp---lsnwga-ltklampeek
----gqiptlpkggfskptgh-aatleifhcsn---g--taah---ila-
---vqtdak--dk-------ttmdelvlregnpti-d---kkdwtgykvl
vatilnlq-lkkhkcglk--fg--egikccgptvgs-env----h-ec-y
t-lr------k-a----lg------ynnkevlk--hk-------elgilq
l-ksqevckvhvcarry-ltcagnvdlfteipvvpkd-------------
-hlthfsvvpsenpatkdpp-----qh--lli--tlva----ismiegka
gatht-hi------m-------wr---waftaae----------------
----tl---vawassk-ky------v---rl----------pe----fss
drh-k--ke--gsnn--rqsitvqias--ta-fck----r-ktgvsk-f-
---------kahntaapll--vdgackks-llac-iag-----kldlpvd
-rskqypraphcisa--kygdlryelyafefr---layhlgafet-----
rddqqvt-yrkflnr-agskyvsstreatteehrfreepgfifaasfarr
laklgakdasepvl-feilkl---apgcslsg--deghihkkna
>node14
wdlyhgtdrcgvcivkl--eqqvlngh--fsiyqlslfikskas------
akk-----c-cehp------e-er-sqkvp---lsnwga-ltklampeek
----gqiptlpkggfskptnq-aatleifncst---gsgtaah---kla-
---vqtdek--dk-------ttmdelvlqegnpti-d---kkdwtgykvl
vaailnlq-lkkhscglk--fg--egikccgptags-env----h-ec-y
t-lr------k-a----lg------ynnkevlk--hk-------elgilq
l-ksqevcrvhvcarry-ltcagnvdlfteipvvpkd-------------
-hlthfsvvpsenpatkdpp-----qh--lli--tlva----ismiegka
gatht-hi------m-------wr---wafaaae----------------
----tl---vawassk-ky------v---rl----------pe----fss
drh-k--ke--gsnn--rqsitvqias--ts-fck----r-ktgvsk-f-
---------kan----pll--vdgackks-llas-isg-----klnlpid
-rskqypsaphcvsa--kygdlryelyafefr---layhlgafet-----
vddqqvt-yrkflnr-agskyvpstreatteehrfreepgfifaasfarr
lak-----asepvl-feilkl---apgcsltg--deghihkkna
>node9
wdkyegsdr----rvkh--nqpilngp--fsiyqvslfikakas------
ykk-----c-cehq------e-er-sqsvp---lnnwga-ltklampeek
----gripslpkggfgkqtgh-ngtldifhcan---g--taah---ila-
---vqtdak--dk-------atmddlvlkeknpni-n---kkewtgykv-
-ytvlklq-mkrhkcglk--fg--egikccgveags-dhv----h-rc-f
t-lv------k-a----lg------ynnkdvlk--hk-------elgivk
l-knqevckvhvcarrc-ltcng---lfteisvvpkdykg-----llahg
lhlnhfsvvpsdnpaakdppfgg-dqh--lli--tlva----cakiegke
gathv-hi------a-------wr---waftaag----------------
----ilvgklawaank-ky------v---rl----------pd----fss
nqh-k--ke--gsny--rqsitvrias--ta-fck----r-kggvsk-f-
---------kkrshaapll--vkgncqks-llac-iag-----klnlpvn
-rskqyprapgciga--kygqlryelyafefr---layhlgayet-----
rddgqit-yrkalgr-agskyvsstreatteehr---dlgfvfaasfkrr
lakkgardasetvllfevlkl---asgcslag--edghvhkkts
>ENV_HV2BE/24-510
wdlyngtercgvcivkl--aqqvligh--fsiyqlslfikakgs------
skk-----c-cehp------ea-r-sqkvp---lsnwga-ltklamaeak
----g-iptlpqggfskgtnq-aakleeftcpt---gsgtaah---klv-
---vqteek--dk-------ttmdelvlqennpti-d---kkdwngytvl
vaailacg-lkkhscglk--gglgdgikcaaptags-qnv----h-ec-y
t-lr------e-a----lg------yn--qvlk--hk-------elpild
l-ksqavcrvhvcarry-ltcagnvslfteipvvpkd-------------
-hhthfpvvpsenpatrdpp-----qn--llt--klvagnpqiskiegkt
gakhtthv------m-------wr---wafqase----------------
----tl---vawassk-kykdktggv---rl----------pe----fss
drh-k--ke--ssne--resitvqiaa--tg-yck----r-dagvsk-y-
---------kan----tlv--vdgackka-llts-vsv-----klnlaid
-rsiqypsgphcvsap-dygdlryelysfefq---ltyhlgafet-----
vddqqvt-yrkflnr-aglr--pstreattedhrfpeepgfifkggfarr
lak-----aaepil-feilkl---apgsmltg--dqghihkkng
>ENV_HV2D2/24-513
wdkyeggnkcgacildl--dqqllngpisfsyyqvslfinakar------
fkg-----c-cehp------e-eqgahsvp---lsnwga-lkrlsmpddg
----gqfpglpkggfdkrtghiaaalelfqcss---g--taah---ila-
---v--------------------dnvvkegqpsi-g---kkdwpvymvl
vytilkie-akkhkcgvk--fg--egmkcca--vga-dyv----h-ec-y
t-mm------k-d----lg------ynnkdvlk--hs-------elgile
l-ssqevcevhvcakky-vickgkvelftevryapmtfkr------ldhs
lhlehfsvvpsehpatkepp-----qh--lfildslls----isk-----
gav----i------aynpqtatws---waftrad----------------
----alvnkvawgdsk-ky------vtgrwl----------pe----ftt
nqh-k--ke--gsnp--rqtikvkils--aa-fck----rrkagisk-f-
---------karnnassll--vrghcqks-ilstqmvn-----klsl---
----------gcesa--kfgqlryqlyyflfn---lgynmnafdt-----
lddsqianvrdfngk-egdkyvcstknastderkfkeepnfvfevsftrq
tpkkgpesasssil-f-lfkl---gpgccvsg--ndgivhkkat
>node18
wdlyqgtdrcgvcivkl--dqqvlngh--fsiyqlslfikskas------
akk-----c-cehp------e-er-sqsvp---lsnwga-ltklampeek
----gqiptlpkggfskptgh-aatleifhcsn---g--taah---ila-
---vqtdak--dk-------ttmdelvlregnpti-d---kkdwtgykvl
vaailnlq-lkkhscglk--fg--egikccgptvgs-env----h-ec-y
t-lr------k-a----lg------ynnkevlk--hk-------elgilq
l-ksqevckvhvcarry-ltcagnvdlfteipvvpkd-------------
-hlthfsvvpsenpatkdpp-----qh--lli--tlva----ismiegka
gatht-hi------m-------wr---waftaae----------------
----tl---vawassk-ky------v---rl----------pe----fss
drh-k--ke--gsnn--rqsitvqias--ta-fck----r-ktgvsk-f-
---------kahntaapll--vdgackks-llac-isg-----kldlpvd
-rskqypraphcisa--kygdlryelyafefr---layhlgafet-----
rddqqvt-yrkflnr-agskyvpstreatteehrfreepgfifaasfarr
laklgakdasepvl-feilkl---apgcslsg--deghihkkna
>node8
rsryehsar----agkh--nqvflnf-------hvhl----ksr------
ykk-----c-ldhr------d-ea-pvcip---lrgwsp-ankgampqek
n-fmgkvp--------gakgk-sggldvmscas---g--glgq---lla-
---idskvk--ds-------vtlegegfkektpk------ktgwdgyaa-
-fsilkpp-lkrakcglksdfg--qplkccgvqsgn-khv----dgkc-y
a-lvasgilikta----lg------fnnqgslkathk-------dl--vk
lakeheickvqvcemnc-lkcea---lfselfvvakgykg-----lfthg
lqlgrwcvapcvq--------gg-dph--lli--qllk----cakpdgke
gtthv-ni------d-------wa---wsfqstg------fleviegr--
-ggd-------watnk-kf------v---rl----------sd----fkk
nrh-k--kn--gsnl--kqsiaigesa--vp-fcr----r-qggksksf-
---------lkkahaapfl--ignechkkdrfic-fvg-----rkslsvd
-rs-------acgva--snaqikynlysfsfp---aevrlgaylt-----
rtngatt-yqnpiar-lgskyvspds-----iqr---e--fvfnaalqrr
natkvakessesvlifkvlkl---trgcglag--tsahldkkan
>ENV_HV2CA/25-512
welypgtdrcgvcfvkl--deqvlsah--fscyhl----rskps------
akk-----c-cehp------e-er-sqsvp---lsnw---ltkltmpedk
----sqiptlpkngfskpkgh-aatleifhckd---g--taah---ilt-
---vptcak--dr-------ttmdel---egdptvgn---kkdwsgykvv
vasildlq-lkthscslk--fg--evinccgqtvgs-enipllhh-eh-y
t-lp------k-v----lg------ynkkdvlk--hk-------qltill
l-raqdvckvvv-earyelscpgnvdlfterpvvpsd-------------
-hvtkhavlssenpanrdhv-----qq--slv--tlmt----isaingkv
gashs-ni------i-------wk---weftave----------------
----tl---vawastk-ky------g---kl----------pd----fsa
drh-k--ke--gsgn--rqsiesqlss--tt-fcr----r-etgltk-l-
---------hahntaepvl--vdgacktk-llkc-lsg-----kldlpvd
drskqyprtphcksa--kygdlryelnafpfr---layrlaafda-----
rdddpls-yrkfvnr-agskgapstreatteqdrfreepgfifavsfsrr
laklgikdtsepvt-feilkl---npgcplsg--edghihkkpa
>node10
wdkyqgtdrcgvcivkl--dqqilngp--fsiyqvslfikskas------
ykk-----c-cehp------e-er-sqsvp---lsnwga-ltklampeek
----gqipslpkggfgkqtgh-aatleifhcsn---g--taah---ila-
---vqtdak--dk-------atmddlvlkegnpni-d---kkdwtgykvl
vytvlkle-mkkhkcglk--fg--egikccgptvgs-dnv----h-ec-y
t-lr------k-a----lg------ynnkdvlk--hk-------elgilk
l-ksqevckvhvcarry-ltcngnvdlfteipvvpkdykg------lahg
lhlnhfsvvpsenpatkdpp-----qh--lli--tlva----iskiegks
gatht-hi------a-------wr---waftaad----------------
----tlvgkvawassk-ky------v---rl----------pe----fss
nqh-k--ke--gsnn--rqsitvrias--aa-fck----r-kggvsk-f-
---------karnhaapll--vkgncqks-llac-iag-----klslpvd
-rskqyprapgcisa--kygqlryelyafefr---layhlgafet-----
rddgqit-yrkflgr-agskyvsstreatteehrfkeepgfvfaasftrr
lakkgakdasetvl-feilkl---apgcslsg--ddghvhkkts
>ENV_HV2G1/23-502
wdkyegtdrcgvcivkl--dqrilngh--ysiyqltlfvkskgs------
ekk-----a-cehpvkpiglq-er-rqsvp---lsnwga-lttlampees
----geiptlpkggfskptgh-aatleifhcsn---g--taah---ila-
---vqteak--nk-------stldelvlregnpti-dackkkdwtgykvl
vatilnlk-lskhkcglk--yg--egikccgptvgs-adv----h-ec-y
t-lr------n-s----lg------ynlkevlk--h-------------k
l-ktqmvckvhvcarrs-ltcagnvdlitaipvvpgd-------------
-hlthfsvvpsenpaskdgp-----kh--lli--slva----vsmiegka
gstht-hi------m-------wn---waftate----------------
----tl---vawssck-ky------v---rl----------pg----fss
drh-k--ke--grnn--rdtipvqiad--ta-fck----r-ktgvsk-f-
---------ksqnhnapll--vdgsckks-llac-iag-----kldlpvn
-rskqyprdphcisa--kygelryelyafefr---layhlgafet-----
rddpqvt-yrkflar-agskyvga-----------reepafifvdsfsrr
lgklgakdasetvl-feiakl---apgcalsg--deghihkkta
>ENV_HV2D1/24-501
wdlyhgtdrcdvcivkl--eqqvlngh--fsiyqlslfikakal------
akk-----c-cehp------e-er-sqkvp---ltswga-ltrlampeek
----g--ptlpkggfakptnq-aatleifncss---gsgtaan---kla-
---vqtdek--dkplkg---ttledlvvqennpai-q---kkdwtgytvl
vigiinlqlskkhscglk--fg--egikccgptans-snv----h-ec-y
t-lr------k-------g------ynnkevlk--hk-------etgilq
l-ksqdvcrlhvcarry-lgcvgnvdlyteipvvpnd-------------
-hlthfsvvasedpatkepp-----qh--lli--tvva----ismiqgka
gakst-hi------m-------wr---wafaaae----------------
----tl---vawassk-ks------a---rl----------pe----fts
arh-n--ke--gsnq--rqsikvevas--tt-fck----r-ktgvnk-f-
---------tan----pll--idsachkg-llat-isg-----klnlpie
-rpklyptaphcyga--kygdlryelyafefr---layilgafgq-----
vddeqvt-yrkffnr-agskyvpsereatteehrfkddagfefaqgfamr
lak-----atepvl-fqilni---assctltapqeeghihkkna
>ENV_SIVG1/22-522
rgkydhsag----sgkhvfqqvfinf-------hihl----mgr------
ydktdylac-ldhn------d-da-pvcvp---lqgwnp-alkgtlaqqk
d-fivkvp--------gatgr-fggrtvkscas---g--glgh---lva-
---idskvk--gs----aak-tlegeggrekefk------stgsdayag-
-raildmp-lkrgqcglksefd--qpnkgcgvqaga-thv----ggqc-y
a-mvasgilakta----lghqklamfnnegslm-----------tl--vk
lvkghnickvqpsein------a----fgelf----gykd-----lfttg
lqlgrwcigsciq--------ga-dph--lli--hlly----cgkpngqa
gttpa-na------d-------wv---wsfkafgicvlvdfldviegr--
-ggk-------watnk-kf------v---kl----------td----frk
trh-kkgqnlggsslpnklsiatgetatkig-vcr----t-qsqrdksiq
eylpvaaralkkgngapfl--ishlsqkkdrfic-ytd-----pkplsid
-hs-------acgva--snaqikfslhgfifn---asvklgaylstakgv
---sant-yqnpigr-lgtkyvvaes-----iqr---e--flfnsalprr
ettmpgkessadvlif--qkl---tkgsgleg--sgahvnn---
>node11
wdkyqgtdrcgvcivkl--dqqilngh--fsiyqlslfikskas------
akk-----c-cehp------e-er-sqsvp---lsnwga-ltklampeek
----gqiptlpkggfskptgh-aatleifhcsn---g--taah---ila-
---vqtdak--dk-------ttmdelvlregnpti-d---kkdwtgykvl
vatilnlq-lkkhkcglk--fg--egikccgptvgs-env----h-ec-y
t-lr------k-a----lg------ynnkevlk--hk-------elgilk
l-ksqevckvhvcarry-ltcagnvdlfteipvvpkd-------------
-hlthfsvvpsenpatkdpp-----qh--lli--tlva----ismiegka
gatht-hi------m-------wr---waftaae----------------
----tl---vawassk-ky------v---rl----------pe----fss
nrh-k--ke--gsnn--rqsitvqias--ta-fck----r-ktgvsk-f-
---------kahnhaapll--vdgackks-llac-iag-----kldlpvd
-rskqypraphcisa--kygelryelyafefr---layhlgafet-----
rddqqvt-yrkflnr-agskyvsstreatteehrfreepgfifaasftrr
laklgakdasetvl-feilkl---apgcslsg--deghihkkta
