>node11
gweavml-----k--yity---afqwtkegl----tlasratngggqgaa
qst--aleelhgynfdk---gdvearcknlglsdllfmsd---tqavagl
tplpnrcinrnrvsa-----cdgtdginaldpaaa--fkli-c---dlpk
de-------qq---kr----n-np---fadg--kqaqtcmtvgd------
-------ngkltnalhpgkedq-------ein---yvvgr--lsae-n--
dta--g--------nktylnkqregr--gdaeggdvsnfdtffyrapg--
-g------a-----tvt-tpls---kftvhfrtqasv---cpsyac----
--fwtnkvgsirvdvdweyvtn---geaask-g----qpfgsagde----
---qmpanpqqc-erpga--f--q---serhlr--hc--krldgk-pcsv
-ekeyvav---klqflkkhks-----kst------vdcgkcvpyaksgnn
aneleagerlafa---sglvnn-atyttt--rpkeq--------svy---
-l-vgqgvc-ttygcgslkdqt------e-q--aqtaela-it--gntgt
-lrkgck----------ias------------l------f---n------
-hplknkscvkdc--csese-tgk----dinghrlric-lsdpsvglk--
--nlgct-----sqgpt--g-gnfsl---------------cngiglg--
kanerdyhfaq--k--kqrqnlsnk
>ENV_HV2NZ/24-502
gwetvml-----k--nity---afqwtkegl----aiisrssskggqgag
qnt--kleevhg-------------------lsd--fmsd---tegvagl
tplpnkcvhrnrvsa-----cegtdgikavdptaa--fkll-c---slpk
dn-------qq---kr----n-np---ledglekqaqrcmtvg-------
-------sgkltdnlhpgeedt-------etn---yvvgr--vyae-d--
dqa--a--------nktylkkqkegr--gdaedadvsnfdtffywapt--
-a------a-----tvt-tplkklvkfdvhfstqssv---cpsyacglev
sgywtnslgsirvdvdweyvtn---gelast-gkie-hsfg---------
---glpaapiqc-n--gt--f--q---serhlp--hc--ksldgt-pcgv
-akeyves---klqflkkhrs-----kst------adcgkcvpfvkssnn
steleagerfafa---aglvnd-atytst--rpkeq--------svf---
-f-agqgvs-tvydcgslqdqt------e-s--gqtadla-it--gntgt
-lrkgck----------vss------------h------y---g------
-hplkhvscttdc--csese-agk----disghrlric-vsepevslk--
--nlact-----aegat--g-gnfsl---------------cngiglg--
kgndrkyhfar--k--knrqslsnq
>ENV_SIVM1/24-528
gfqatml-----q--fity---ayqwvgssl----tltsrakhgggqgaa
dlt--pleeldgykgdk---gdvear-----lalllimsd---tqaaagl
tplparcdnrarvsa-----cngtdsagaftpagv--yklv-c---dmpk
eececlsvtst---kk----g-na---fadg--qnaqtcmtagg------
-------ggqstdclnqakegk-------dva---ylvgr--lcgned--
dvaitg--------nk-yfnrqvegr--geakgdedv--dayfykcpg--
-g------alsdvatvt-splg---sftihyrtkycv---cptftp----
--frtnkvgs---eveweyvtn---gisatk-g----dpfapagde----
---qmpanpqqa-erpga--f--h---tkkplk--hc--ktlgsn-psrv
-ekeyvaa---klqflkkhkq-----att------vdcgkcvp--rsgsr
rtelepgerllyapssaglvna-atyaqt--rssdq--------gvy---
-l-vpegvc-saygseslkdrq------eae--aqtneka-it--gnsgg
-lqkacr------vgvntek------------f------f---n------
-kqlkgtscvknc--csese-tgk----aisgfllrlc-lstpseglk--
--klgcv-----sqapt--g-gqfpi---------------cdgsglg--
knlnrdhhyah--g--terqnlgnk
>ENV_SIVG1/22-522
vfkspildi--lp--fnsy---tl---kgtl----aippitsdgdgdgsa
hsp--gl-kae----na---gdngp------lqmlfivss---hkalhgv
kpiskrckkkclnsa-----llgtnaindltpanvdgfylpsl---anpi
dsckclimdsr---dnaragkpnp---yrdg--qvkhtclalgg------
-------fgst--cirpgkeescrvvkgchtd---sicgr--lhrq-d--
evs--as----imahgsffgsekggsrfagkkaaatp--tdyffvcpgha
yt------tflditrvvhas---------lfkvksst---seshtc----
--fhsrclgi---ineweffskkilpiqkgrgg---a------snkpeea
ikgdkvasseqp-trpfg--f--tdkqd---kkvdky--ngvtggvhcav
-fklctaa---kfefieha--------------------yvcpytcdghe
p--vdvvnmlayn-avggltrg-t--lhc--kgnm---------vvy---
-l-vgvisy-cmyargslkqwsfr----e-e--s--eaaqlad--psacn
-ahkkgr----------lrv------------c------f---nqhvekf
ia--------------cksd-apd--lsvncd--ls---fgtstvafn--
--lis--------hggf--pkng-daggmgednkql-----ckaakld--
vklasdiyypm--g--ssrknlnnp
>ENV_HV2D1/24-501
gweiaml-----r--yity---afqwakegl----tlasrsqnasgqgaa
qss--aleelhgylfkk---gdvearcknlglsdllflsd---iqgvagt
tplpdrsinrhkvsa-----cngtdgidtldpaaa--ftli-c---dlgk
de-------kq---kr----n-np---fadg--rgaqacmtvgd------
-------svkmtnamhegkedd-------ein---yvlar--vsdt-n--
dqa--g--------nkaylnpqkegr--gdadggdvsnfdtffrrapg--
-gipprsas-----ava-tplt---rftahfratasv---cpsysc----
--fwtnmvssiraevdweyvtq---geaask-g----hpfgsagde----
---qmpaephqc-nrpga--f--q---kerhlr--gc--krldge-panv
-deeytea---klqflkkykg-----kst------vdcgkcvsyapsgnn
sndleagerlaya---tglsys-atytta--rpkdq--------gdnaai
klkvgegvc-tvygvgtlkdqt------e-q--a-----a-vt--gndgs
-lrkgck----------ita------------v------f---n------
-hplklrscvkdc--cseme-tgk----didphrlkic-lsdppvslk--
--nlgct-----tqgpt--g-tnfsl---------------cdgiglg--
ianeriyhfaq--k--kqr------
>node7
vfktpvldi--lp--ftty---sl---kgsl----tipprtnegggdggt
hsp--glskie----nr---gdngp------lqmlfivsa---nkalhgl
kpvskrcdkkclnsa-----vlgtdaindltpagv--fyfprl---gnpi
dsckcmimdsr---dk----kpnp---yrdg--qashtclavgg------
-------mgat--cirpskdakcrvvkgchtd---sicgr--lprq-d--
eet--ag----ilahgsffgrqkgasrfagkkaaakp--tdyffncpghp
yt------afldltrvvfapl----kidklfkvkkct---sesytc----
--fcsrqlai---vaewefftk---liqkgrgg---n------anedeea
isgdkaasaeqp-trpfg--f--tdkqd---kkvdqy--hgvagg-pcav
-fklctaa---kfqfiena--------------------yvipytcdghe
p--vdainilayn-avggltrg-tvclhc--kdnl---------vvy---
-l-vgaisy-cmysrgslkqwsfr----e-e--s--daae-id--pnasw
-ahkrgr----------lqv------------c------f---nanvemf
id--------------sqsd-apd--rsvncd--ls---fgtptvvfn--
--lis--------hgef--prgg-daggmgeqnkql-----ckaadle--
vklasdfdypm--g--ssrknlnss
>node14
gweivml-----k--yity---afqwtkegl----tlasrstnaggqgaa
qst--aleelhgynfdk---gdvearcknlglsdllfmsd---tqgvagt
tplpdrcinrhrvsa-----cdgtdginaldpaaa--fkli-c---dlak
de-------qq---kr----n-np---fadg--rqaqtcmtvgd------
-------ngkltnalhpgkedd-------ein---yvvgr--vsae-n--
dqa--g--------nktylnpqregr--gdaeggdvsnfdtffrrapg--
-g------a-----tva-tpls---kftvhfrtqasv---cpsypc----
--fwtnmvgsirvdvdweyvtn---geaask-g----qpfgsagde----
---qmpaepqqc-erpga--f--q---serhlr--hc--krldgk-pcsv
-ekeyvev---klqflkkhks-----kst------vdcgkcvpyaksgnn
aneleagerlafa---tglvyn-atyttt--rpkeq--------svyami
kl-vgegvc-tvygcgslkdqt------e-q--aqavela-vt--gntgt
-lrkgck----------ias------------v------f---n------
-hplknkscvkdc--csese-tgk----dinghrlric-lsdpavglk--
--nlgct-----sqgpt--g-gnfsl---------------cngiglg--
kanerdyhfaq--k--kqrqnlrnt
>node9
gfqaaml-----k--yity---afqwvgasl----tlasrandgggqgaa
est--sleeldgynfdk---gdvear-----latllimsd---tqavsgl
tplparcdnkarvsa-----cngtdsigaltpagv--fkli-c---dlpk
decqcltvtst---kr----n-np---fadg--qnaqtcmtvgg------
-------ngkttnclhpgkedq-------dvn---yvvgr--lsge-n--
dta--g--------nktyfnrqregr--gdakgddea--daffykcpg--
-g------afmdvttvt-tplg---kftvhfrtkscv---cpsfac----
--frtnkvgs---eveweyvtn---giaask-g----epfgpagde----
---qmpanpqqc-erpga--f--q---tqknlk--hc--ktldgn-pcsv
-ekeyvaa---klqflkkhke-----ntt------vdcgkcvpyarsgnn
ptelepgerlayaassgglvna-atytqt--rssdq--------gvy---
-l-vpegvc-ttygseslkdrt------e-e--aqtnela-it--gntgt
-lrkacr----------ies------------f------f---n------
-hqlkgascvknc--csese-tgk----eisglrlric-lstpsvglk--
--klgcv-----sqgpt--g-gnftl---------------cngsglg--
knlsrdyhyaq--g--serqnlgnk
>ENV_SIVV1/24-538
vfkspvlel--vp--fety---sn---kggl----vipprtnegsadaet
hap--glpsve----qp---gddvp------lqlllilsa---gkslqtl
kpvgkrcikkcldsa-----vlatagsnemtpsav--fyfa-------pi
ttckcvivdsq---ak----nsnp---yrea--qavyscltvaa------
-------lavt--cvrpakdakcrvvkgchkd---nrggq--wckq-s--
eqs--gg----ql----fagrqkgagrfaakkaalkp--tdyffncpgrp
y----------dld-vvlgpl----tqddlfkldkgt---sksytc----
--fcavqlaf---isqwafftt---aitkgagg---n------qnddeeg
gsgnnlasdeqp-trpfd--y--te-------kvdq---hgitgg-pcay
-fklctn-----fnglgys--------------------yvipytcsgqe
p--vdavdvlayn-nvdgltrg-svclrc--kdsl-asslsgakvih---
-l-vgsltf-clsakesfsqwsfn----d-dwks--dhdq-ie--pqlvw
-ghkrgk----------lhm------------c-------------vsmf
id--------------sqqe-tad--rtaact--la---fgdptvafn--
--lvc--kvhr--haef--prgs-pdagigevdkqm-----ckpedlk--
vklandleypm--g--ssrknlars
>node18
gweivml-----k--yity---afqwtkegl----tlasrstngggqgaa
qst--aleelhgynfdk---gdvearcknlglsdllfmsd---tqgvagl
tplpnrcinrnrvsa-----cdgtdginaldpaaa--fkli-c---dlpk
de-------qq---kr----n-np---fadg--kqaqtcmtvgd------
-------ngkltnalhpgkedq-------ein---yvvgr--vsae-n--
dqa--g--------nktylnkqregr--gdaeggdvsnfdtffyrapg--
-g------a-----tvt-tpls---kftvhfrtqasv---cpsyac----
--fwtnkvgsirvdvdweyvtn---geaask-g----qpfgsagde----
---qmpanpqqc-erpga--f--q---serhlr--hc--krldgk-pcsv
-ekeyvev---klqflkkhks-----kst------vdcgkcvpyaksgnn
aneleagerlafa---sglvnn-atyttt--rpkeq--------svy---
-l-vgqgvc-tvygcgslkdqt------e-q--aqtaela-it--gntgt
-lrkgck----------ias------------l------f---n------
-hplknkscvkdc--csese-tgk----dinghrlric-lsdpsvglk--
--nlgct-----sqgpt--g-gnfsl---------------cngiglg--
kanerdyhfaq--k--kqrqnlsnk
>node17
gweivml-----k--yity---afqwtkegl----aiasrstngggqgag
qnt--kleelhgynfdk---gdvearcknlglsdllfmsd---tqgvagl
tplpnkcinrnrvsa-----cdgtdgisaldptaa--fkli-c---dlpk
dn-------qq---kr----n-np---ladg--kqaqicmtvg-------
-------sgkltnalhpgkedq-------ein---yvvgr--vsae-n--
dqa--g--------nktylkkqregr--gdaeggdvsnfdtffyrapg--
-g------a-----tvt-tplk---kfdvhfrtqasv---cpsyac----
--ywtnkvgsirvdvdweyvtn---geaask-g----qpfgskgde----
---qlpanpqqc-erpgt--f--q---serhlr--hc--krldgt-pcsv
-ekeyvep---klqflkkhks-----kst------vdcgkcvpfaksgnn
ateleagerlafa---sglvnn-atyttt--rpkeq--------svy---
-l-vgqgvc-tvygcgslkdqt------e-q--aqtaela-it--gntgt
-lrkgck----------ias------------l------f---n------
-hplknvscvkdc--csese-tgk----dinghrlric-lsdpsvglk--
--nlact-----sqgpt--g-gnfsl---------------cngiglg--
kgnnrdyhfaq--k--kqrqnlsnk
>node19
gweavml-----k--yity---afqwtkegl----tlasratngggqgaa
qst--aleelhgynfdk---gdvearcknlglsdllfmsd---tqavagl
tplpnrcinrnrvsa-----cdgtdginaldpaaa--fkli-c---dlpk
de-------qq---kr----n-np---fadg--kqaqtcmtvgd------
-------ngkltnalhpgkedq-------ein---yvvgr--lsae-n--
dqa--g--------nktylnkqregr--gdaeggdvsnfdtffyrapg--
-g------a-----tvt-tpls---kftvhfrtqasv---cpsyac----
--fwtnkvgsirvdvdweyvtn---geaask-g----qpfgsagde----
---qmpanpqqc-erpga--f--q---serhlr--hc--krldgk-pcsv
-ekeyvev---klqflkkhks-----kst------vdcgkcvpyaksgnn
aneleagerlafa---sglvnn-atyttt--rpkeq--------svy---
-l-vgqgvc-ttygcgslkdqt------e-q--aqtaela-it--gntgt
-lrkgck----------ias------------l------f---n------
-hplknkscvkdc--csese-tgk----dinghrlric-lsdpsvglk--
--nlgct-----sqgpt--g-gnfsl---------------cngiglg--
kanerdyhfaq--k--kqrqnlsnk
>ENV_HV2G1/23-502
gwqavml-----k--yiky-sfvfqftkegl----tlmsratnggsqgaa
dst--aqeelhgnnfdd---gdvdarcknlaladflfmad---tqavpgl
lplsdrcinrnrvsa-----cdgtedinaldpaaa--fkli-c---elpk
de-------qq---kr----v-np---sadg--kdthtcmtvgd------
-------dgklknnlqpgkedq-------ian---yvvgr--lkae-n--
kaa--g--------nktylnkhregr--gdaeggdvstfktffyrapg--
-g------a-----tvt-tpis---kftvhfrtqasv---cptfac----
--fwvnkvgsirvdqdweyvln---getadk-g----qpfgnagde----
---smpanpqqp-akpgi--f--q---serhlr--hc--krldgk-scsv
-ekeyvlv---klqflkqlkr-----kst------vdcgqcvpyaksgkn
vyeleggeslafa---spvvkn-atyttt--rpkeq--------svy---
-v-vgqgvc-ttygcgslkdqt--lcvaa-q--aqtaela-it--gntgt
-lrkgck----------vas------------l------f---n------
-hpmknescvkdc--cresa-tgk----dinghrlric-ladpsvglk--
--nlgct-----sqgrt--g-gnfsl---------------cngiglg--
kanqrdyhfaevpknhkqrqnlstk
>node8
vfktpvlqi--lp--ftty---sf---kgsl----vlaprtnegggdggt
qss--glddldgyshdr---gdnga------letlfivsd---nkalhgl
kpvskrcdrkckksa-----vvgtdaidkltpagv--fyfa-v---alpi
esckcmimnsr---dr----dpnp---ysdg--qashtcmavgg------
-------mgkt--cirpvkegscrvvkgcnad---siagr--lprq-d--
eet--an----iladgsffgrqkggsrfagtsagaqa--ddyfyncpghp
yn------afldvtkvtgtpl----kinllfktkkct---sesytc----
--fcssklgi---aaewefftk---liqagk-g---t------geed---
---dkaanaeqp-trpfg--f--srkqd---kklnqc--nglaag-pcai
-fkectaa---kfqfiensle-------t------ldcsycvpytcdghe
p--ldsnnilays-avgglisg-ttclhc--kdnl---------vvy---
-l-vsaisy-cmfgrgslkewtfr----e-e--a--daae-td--pnasr
-lhkrvr----------vqv------------y------f---nadvvef
vdgls-dgc------csdsd-apd--rseicd--lr---fgsptvvfn--
--qis--------qssy--argg-da---------------ckasgle--
aklasdfnysq--g--sarktlgns
>ENV_SIVGB/47-569
d-qctglddckceylyaky---tf---vgve----cmecsstniidgkdd
qadtsalgdmngyeaqrrklhvsgv------vhnvqvttq---pg-----
-------eklcnpkf-----vvttkqkpalvaslp--fy-p-vqtlptsm
hdrnstikmkhpggtr-----iqplal-nl----fvgacfgvakkrielg
grskeddvkki--cldplksnnrsivfncghtiyvlpglr--wpte-nlp
-----gnhllrvfseady--qtkgidth----lpn----gwvffmsagqp
yt------catqstkggssad----rfa------rsdiyqf---------
--vcsvclm------------e---l-------------------ar---
---stdglms-aslrpfeqne--teqde----qkicgllsgiaad-teav
edvkkafpqmh-------rvr-------peghkqyfa-snkkdkfcgvvs
n--qhgsstfglt-sigqkssaptvcalenia-------------gf---
-l-pgslcykcvyshgtlvkwafv----g-g--l--ghah-kevtdigdr
yltkersvakgil-----hlidqkivfipqtvf-----pfnlvtqrlvrm
ldant-dgv----akpatqrrapsttnnedct--ld--lyrcksilkgst
nvgyq--------rrnl--srlp-te----------dgesvcdasmap--
p---eqyshpn--e--hgsart---
>ENV_HV2BE/24-510
cyeivll-----k--yity---afqwtkeglnhnltlaprstnaggqgaq
qst--aleelhdynfdk---gdveatcknlglsdllfmna---tqevpgt
tplpdqcinririsa-----cdgtdginaidpaaa--frli-c---dllk
de-------qq---rr----n-gp---fadg--retqtcmnvgd------
-------ngkltdalhagkedd-------ein---yvagr--vsae-n--
dei--g--------nktyldsqvegr--gnaeggdmsyfdtffkrapg--
-g------a-----tah-tplh---kftvhfrtqssv---cpsypc----
--fwkdmvgsfridlnweyvtn---geegsk-s----qsfssegde----
---qipaeaeqc-eraga--f--q---serhlr--hc--krldak-pctv
-dkeyvev---klqfmikassvkkhtdst------vdcgkcvpytksgnn
ansldigerlaft---tglvyn-atyttt--kpkeq--------svyami
kl-vaegvc-vvyaclsfkddt------d-q--anevela-vt--gntgt
-lrkgck----------aas------------vfltls-f---n------
-hplknkscvkdc--csdse-sgk----dtkghrlrlc-lsesavsfe--
--nltct-----gqgpt--g-gnlsl---------------cngigig--
kanerdfhfaq--k--kqrqslrnt
>node10
gweavml-----k--yity---afqwtgagl----tlasratngggqgaa
qst--sleeldgynfdk---gevear-----lstllimsd---tqavsgl
tplpnrcinkarvsa-----cngtdgigaltpaaa--fkli-c---dlpk
de-------eq---kr----n-np---fadg--kqaqtcmtvgg------
-------ngkvtnclhpgkedq-------ein---yvlgr--lsae-n--
dta--g--------nktylnkqregr--gdaeggdvs--dtffyrcpg--
-g------a-----tvt-tpls---kftvhfrtqtsv---cpsfac----
--fwtnkvgs---eveweyvtn---giaask-g----qpfgpagde----
---qmpanpqqc-erpga--f--q---sekhlk--qc--ktldgn-pcsv
-ekeyvav---klqflkkhks-----kst------vdcgkcvpyaksgnn
aneleagerlaya---sglvna-atyttt--rpkeq--------svy---
-l-vgqgvc-ttygsgslkdqt------e-q--aqtnela-it--gntgt
-lrkacr----------ias------------l------f---n------
-hqlkgascvkdc--csese-tgk----einghrlric-lsdpsvglk--
--nlgct-----sqgpt--g-gnftl---------------cngsglg--
kalerdyhfaq--k--tqrqnlsnk
>ENV_HV2CA/25-512
gwqhvml-----s--yity---sfqwtkegl----avanrstngggqggd
hnt--kleelhgynlek---gdvearcknlelsdllfmnd---kqgvmgl
tplpnkcinknrvsa-----cdgtegisaldptaa--fkli-c---dlpk
dn-------qq---kr----e-np---lasg--reaqvcmtvg-------
-------ngklsnalhpgkedq-------eid---fivdr--vsae-n--
kqa--s--------fktylksdragr--sdaeaadvsnfdgffyrspd--
-g------a-----tvk-tplk---kfdvhfrtqanv---cpnyac----
--ywtnkvasirvevdwdfvtn---gaassk-g----epfgskgte----
---qlpanphqc-erpgt--igsq---sekhlh--hc--krldet-acsv
-ereyvep---klqflkkhks-----kst------vgcgkcvifaksgne
vteleaterlafa---sglvnn-atyttt--kpkek--------cvy---
-l-vgqgvc-tvygcgalkeqt------e-q--aqq------------ga
-vrkgak----------ias------------l------f---n------
-hplhnvpcvkdc--cseae-tgk----didghrlric-lsnpsvgls--
--nlact-----sqspaalg-gnfsl---------------csgiglg--
ksnnrdyhfpq--k--kqrqnlask
>ENV_HV2D2/24-513
gwtnvml-----q--yitfl--cydwvgakl----klaahgtngggqgga
rss--alpeaagynfdk---gevaar-----lsgalimpetkktqaisgl
t-aahrcinkervsakdvpgcnvtd---pltqpvd--lnli-c---elq-
--------------------a-ns---faeg--krfmtcmevng------
-------nskikyclnptrida-------ein---yvfghgtlsae-n--
etp--g--------nktylskqregl--gdaegdevc--gtfffrcpg--
-g------a-----kas-tpls---nftihfrkqnkm---lpayac----
--fwthavgs---dvrweyttn---giaaak-g----qpfgpagks----
---qvpvnptsc-errga--f--q---aekhlk--ec--ktvged-pcgv
-eketvvv---s-----ghmt-----kss------vncgksmpyaksgnn
tneseagerlaya---sglgek-vtytta--rpkei--------tvy---
-l-vgqgvc-ttygngslkdqt------e-q--aqtdala-it--gttgt
-ltkacr----------iat------------l------y---d------
-hqtkgsscvkvg--ssesd-ls-------------------ptvglk--
--nmgct----i--------------------------------sglgav
kglerdyhfpe--k--tqrqdlstk
